### ISSUE TITLE
mech pad rebalance

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1]
**Describe what you would like changed, and why.**
Mech pads require *power*, but the amount doesn't matter as long as its there.
This lets you power all your pads from a single solar panel, like with incinerators, menders (I think there's no speed decrease), etc.

**Describe the changes you want to propose. Include possible alternatives.**
Mech "equip" speed may be determined by power satisfaction.

Additionally, I believe that they could take power (and maybe resources) to produce a mech, and players may quickly switch into them, leaving uncontrolled (probably easy in 6.0) mechs behind that eventually despawn if not used.
Switching to the same mech type could simply create a copy of it instead of turning back into a default mech. This could be used as a way to quickly heal back up. The core could be used to switch into the default mech.

#1

**Comment by Quezler** [comment]
>  Mech "equip" speed may be determined by power satisfaction.

what if you respawn on a pad with next to `0%` power, wait 10 minutes to respawn (if at all)?

**Comment by Anuken** [comment]
I think "mech pads" should cease to exist completely in 6.0, and player should instead be able to assign themselves to a unit factory and respawn with the next created unit. If that takes too much time, they could also choose to reassign themselves to the core or an existing unit already in the field.

**Comment by DeltaNedas** [comment]
good idea, this suggestion was more 5.1 based

**Comment by JackAtak1103** [comment]
Leaving my mark. ❌

**Comment by Evanevoyo** [comment]
oldest issue in mindustry suggestions

**Comment by traincrisis** [comment]
> oldest issue in mindustry suggestions

true
