### ISSUE TITLE
Ping on player list

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#10]
**Describe the content or mechanics you are proposing.**
Have a ping count next to each user on the player list.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes its nice to know other peoples ping to see if the host has bad connection or if your ISP is just trash.

**Before making this issue, replace the underscores in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Nicknakin** [comment]
https://github.com/Anuken/Mindustry/pull/1678

**Comment by Katsute** [comment]
Closed due to inactivity
