### ISSUE TITLE
Dark sand

### ISSUE THREAD

**Issue by potatoisagender** [Anuken/Mindustry-Suggestions#100]
Little bit of backstory. I live in Alberta, oil province, and so when I see dark sand, the first thing I think of are the oil sands. The feature I'm proposing involves the oil extractor, and the dark sand. Basically, dark sand is now a different item from regular sand. It could have all the properties of regular sand, with one additional feature. Now here, we could go several different ways.
1. Completely change the way the oil extractor works. Make it only work with dark sand, the placement doesn't matter. Increase efficiency of the extractor by placing it on thermal spots, or some other idea I haven't come up yet. Produce oil and regular sand as output.
2. Have it increase the efficiency of the oil extractor. I don't know how this can be explained, so I will leave it up to you.
3. Have another building to extract the oil from the dark sand instead. Keep the oil extractor separate from this. 
4. Have the oil extractor increase efficiency on oil sands. By far the simplest one, just requires some balancing.
This will probably have some edits in the future as I come up with new ideas.

**Comment by itcannotbe** [comment]
Is the oil extractor fracking or seperating oil from oil sands?

**Comment by itcannotbe** [comment]
Also. Shale has positive effects with oil extractors already......

**Comment by potatoisagender** [comment]
Ik both. I just thought that dark sand has some missed functionality.
Does it matter which? (either one, depending on the option anuke (anuken?) chooses)

**Comment by potatoisagender** [comment]
Oops

**Comment by jjlearbo** [comment]
Add a unit to the mining section that separates the sand from the oil that can be sent out to its respective areas. And if you don't want to do that you can put down a normal mine and it will mine the dark sand for use in factories that need just sand.  
Although having the miner that does both would make that a little OP in multiplayer so there needs to be some sort of balancing. 
Like itcannotbe said shale already males extractors more efficient.

**Comment by Anuken** [comment]
Dark sand is now one of several blocks that are required for oil extractor. It has the highest production efficiency.

**Comment by potatoisagender** [comment]
cool
