### ISSUE TITLE
Issue 1000

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry-Suggestions#1000]
**Describe the content or mechanics you are proposing.**

Yeet

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I don't care if you close this i just want bragging rights

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
Brueh

**Comment by rodrigolitzius** [comment]
bruh

**Comment by Bohaska** [comment]
- [ ]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
- [ ]   I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
- [ ]   I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
I doubt you actually meet any of these requirements.

**Comment by Bohaska** [comment]
Also
1. If your suggestion is implemented, it will break the game
2. A Yeet turret has never been suggested, because it is really unpopular
3. If you still want to make a Yeet turret, do it in a mod.
4. Who cares about issue 1000?

**Comment by strugee** [comment]
Heh. Reminds me of https://bugzil.la/100000 :joy:

**Comment by ThatOneBepis** [comment]
this could be used for a much better shitpost

**Comment by userlol2** [comment]
Tf

**Comment by Esnardo** [comment]
> this could be used for a much better shitpost
Yea but it wouldn't be *my* shitpost

**Comment by 50275** [comment]
close this

**Comment by scarf-generic** [comment]
> close this

nO
