### ISSUE TITLE
a New Naval Branch (expiremental idea)

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1002]
**Describe the content or mechanics you are proposing.**
A new branch of naval units which carry ground, naval and air units on them. They would have **alot of health** with low amounts of firepower, but still capable of taking out zeniths, horizons and flares. They would also be good commanding units and can carry resources over water. The T1 unit would have the ability carry 3 daggers or 2 maces with a duo on the top of it. The second, can carry 2 fortresses, 3 maces or 5 daggers with a hail on it and a scatter. The third, 3 fortresses, 5 maces and 8 daggers with 2 scatters and a salvo. The fourth, a scepter, 6 fortresses, 8 maces and 13 daggers with a spectre. The T5, can carry a T5, 3 T4s, 10 T3s, 12 T4s, 20 T5s with two ripples and two spectres on board.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We only got 1 naval branch

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by userlol2** [comment]
Good but i think it wont be add as we already got mega

**Comment by 50275** [comment]
sounds like a really bad oct

**Comment by jaygamer81** [comment]
> sounds like a really bad oct

How so? It has weapons. I also forgot to mention some more perks.
