### ISSUE TITLE
Give The Title Screen Units Their Team Lights

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1004]
**Describe what you would like changed, and why.**
That's literally it. Just make the title screen units belong to the Sharded team, so the Zeniths don't look weird without their hover-rotor innards, etc. 

**Describe the changes you want to propose. Include possible alternatives.**
It would look cleaner and neater.

**Comment by Bohaska** [comment]
just ask someone to make a mod, for goodness sake.

**Comment by Catchears** [comment]
But... Suggestions exist to make the game better in general. Do you have a reason why this should be a mod and not added to the game?
