### ISSUE TITLE
Swarmer missiles loaded with liquid

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1005]
**Describe the content or mechanics you are proposing.**
Make Swarmers missile be able to be supplied with liquid. For example, if supplied with water, missiles will explode with water, if supplied with slag, missiles will spray slag everywhere, if supplied with oil, becomes incendiary rocket and sprays oil, if supplied with cryofluid, it splashes cryofluid everywhere and freezes enemies. However, missiles need to be supplied with lots of said liquid for them to work

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will make the Swarmer more useful and will add more types of attack. It will also balance the game if a new 'fast' unit is added.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I like Mindustry
5. - [X] You have read this suggestion.

**Comment by ritzip** [comment]
Committing war crimes with anuke episode 82838838382882

**Comment by Bohaska** [comment]
What the...

**Comment by userlol2** [comment]
Well,shot liquid as missels make no sense

**Comment by Colonizor48** [comment]
This is actually a good idea.

**Comment by Bohaska** [comment]
Do you prefer upgrade to swarmer or new tower for this?

**Comment by 50275** [comment]
This is called a wave turre5

**Comment by Bohaska** [comment]
ik whats wave turret, but I want more water towers (wave doesn't do much explosive damage)
