### ISSUE TITLE
a New Naval Branch (expiremental; updated)

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1007]
**Describe the content or mechanics you are proposing.**
A new branch of naval units which carry ground, naval and air units on them. They would have **alot of health** with low amounts of firepower, but still capable of taking out zeniths, horizons and flares. They would also be good commanding units and can carry resources over water, they can also protect nearby units.. 

The T1 unit would have the ability carry 3 daggers or 2 maces with a duo on the top of it. 

The second, can carry 2 fortresses, 3 maces or 5 daggers with a hail on it and a scatter.  

The third, 3 fortresses, 5 maces and 8 daggers with 2 scatters and a salvo. It also has an onboard refill station to refill ammunitions.

The fourth, a scepter, 6 fortresses, 8 maces and 13 daggers with a spectre. It comes with a refill station and a built-in overdrive projecter which boosts nearby units and buildings speed and firerate by 33%

The T5, can carry a T5, 3 T4s, 10 T3s, 12 T4s, 20 T5s with two ripples and two spectres on board. Including a overdrive dome which boosts nearby units and buildings by 56% via speed and firerate, it also comes with a refill station with an additional force projecter with the power of an octs. This is better than the oct in all ways, but it cant go on land nor space.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We only got 1 naval branch

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by z0mbiesrock** [comment]
Not happening. 100%. 
![image](https://user-images.githubusercontent.com/19158169/97637659-73882300-1a11-11eb-8000-a58ed3c8195e.png)

**Comment by jaygamer81** [comment]
> Not happening. 100%.
> ![image](https://user-images.githubusercontent.com/19158169/97637659-73882300-1a11-11eb-8000-a58ed3c8195e.png)

Maybe next update

**Comment by kingb74** [comment]
Not gonna lie even though its nit happening 

That would be game breaking if anuke added that it sounds way to op
