### ISSUE TITLE
Friend System, related things

### ISSUE THREAD

**Issue by PlanetOrca** [Anuken/Mindustry-Suggestions#1008]
**Describe the content or mechanics you are proposing.**

This is a big one. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by nodevlfrb** [comment]
Bruhhh

**Comment by PlanetOrca** [comment]
> Bruhhh
I closed this because I accidentally posted it before I was finished writing it (or even starting it).
My fatass finger slipped and accidentally hit enter

**Comment by sk7725** [comment]
Steam version exists for a reason
