### ISSUE TITLE
Maessages save in the message when copied

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1009]
When you copy a message it doesn't save right now i want that to change it would help in schematics

When you copy a meassage building the message should be saved in the copied message so you can place it and not have to readd the message makeing messages in schematics useful to tell you what you originally typed in to it

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sk7725** [comment]
It ***does*** copy
Do you happen to live under a rock?

**Comment by Ilya246** [comment]
yeah, that's already implemented for a long time, close the issue
