### ISSUE TITLE
Ekranoplanes

### ISSUE THREAD

**Issue by USMP-Mandarin** [Anuken/Mindustry-Suggestions#1010]
I propose to add a new type of units: ekranoplanes. They will act as support units, but from the naval industry. They can usually float in water, but with the gear key pressed, they can hover over water / land at high speed. Construction cost: 60 Silicon, 30 Meta-glass and 80 Titanium.
T1 will be equipped with volley cannons. Hail will be added to T2. T3 - will have missile weapons and a salvo. T4 - They will already have a laser turret, two volleys and the ability to heal allied units near. Two fuses will be added to T5, missile weapons and a mono factory and heal ability.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by l-Luna** [comment]
> mono factory

no. the flares produced by an Omura are attacking units and don't build up like Monos would.
