### ISSUE TITLE
Different launchpads should launch to different locations

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#1011]
**Describe the content or mechanics you are proposing.**

If you have 2 or more launchpads, they all have to launch to the same destination, which doesn't make sense. This suggestion is to make each launchpad's destination independent of each other

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I have a central silicon smelting sector and tried to have multiple launchpads launch silicon to other sectors. It would be nice if it worked.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
this would be very useful, but would also be very annoying unless we could do #720 this.

**Comment by sample-text-here** [comment]
How would that work though? I assume you could do `@ground-zero` but what if you name a sector "silicon"? Would there be a `getsector` block?

**Comment by alexobviously** [comment]
Just want to revive this because I was playing and it took me a long time to realise launchpad destinations aren't independent, and was wondering why some of my worlds weren't receiving any resources. Having each location only allowing launchpads in that location to ship to one location (as it is currently) doesn't make any sense, imo.

**Comment by sample-text-here** [comment]
amazing, you are the first person i've seen who actually searched issues before making a new one, and i'm not even being sarcastic

<details><summary>enjoy your award</summary><img src="https://user-images.githubusercontent.com/56274831/107905280-1c945400-6f03-11eb-9a1b-13ef012dcd68.png" />
</details>

**Comment by Kyllingene** [comment]
Where do you get those?

**Comment by G0nTar** [comment]
Bump, it may have to do with the fact that it would need more code n weeks
of testing to check if it works, make it compatible with the campaign
module, make sure it doesn't break anything, that it is performance
friendly (important AF on this kind of game) and that's more time and
effort put into changing/testing/implementing something that already works
n runs properly! but it just not "comfortable" or as complex to the extent
we want.

I wish launchpads behaved as you, me, and hope anuken wants too, it would
actually help me a lot to send silicon, metalglass and titanium from the
same area to 2 different regions.

It would be nice to have, but the list of To-do Things is BiG AF too, and
there's only so much a person can do in a week, ask yourself how much Most
of people asking for stuff on the internet do in a week, and look at the
massive list for Mindustry.
