### ISSUE TITLE
Make Tainted Water improve Cultivators

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#1013]
**Describe what you would like changed, and why.**

Currently, tainted water is just purple water, and provides nothing that regular water doesn't already provide. Giving them spore attributes (might) make them more interesting. 

**Describe the changes you want to propose. Include possible alternatives.**

Give tainted water spore attributes (and also allow cultivators to be placed on the edge of water).

**Comment by Quezler** [comment]
it would require the addition of a new fluid entirely + adding/rebalancing the existing things that use normal water 🤔

**Comment by genNAowl** [comment]
I didn't mean a new fluid, I mean like placing cultivators on tainted water would give cultivators a bonus (considering stereotypical plants grow better in lush areas)

Sorry if that wasn't clear in the suggestion

**Comment by l-Luna** [comment]
I think this has been implemented?

**Comment by itcannotbe** [comment]
> I think this has been implemented?

Just checked and it is implemented.

**Comment by genNAowl** [comment]
nice
