### ISSUE TITLE
Show (force projector) shield health on hover

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#1015]
**Describe the content or mechanics you are proposing.**

![force projector](https://user-images.githubusercontent.com/56274831/97688383-4f4f3500-1a57-11eb-8872-7bf8a8848a60.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Nice quality of life feature, you can see how much longer the shield will last. Good for planning on whether to start building or wait for the shield to regenerate. It would also be nice to be able to check with logic blocks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by kingb74** [comment]
Yea its a pretty good thing to add

**Comment by DeltaNedas** [comment]
close this suggestion, implemented

**Comment by sample-text-here** [comment]
cool
