### ISSUE TITLE
Unit factories 

### ISSUE THREAD

**Issue by kingb74** [Anuken/Mindustry-Suggestions#1016]
**Describe what you would like changed, and why.**
Its quite simple really on mobile u can't move the unit factory to a different direction(I'm pretty sure I've tried every type of swipe)

**Describe the changes you want to propose. Include possible alternatives.**
Its simple really to not mess with any other controls if u want to move the direction of the factory hold on it then swipe in the direction u want it to move 

*A very simple solution to a simple problem*

**Comment by QmelZ** [comment]
try breaking and replacing, its just an unit factory

**Comment by DayTimer** [comment]
Breaking a tetrative reconstructor? Okaay.

Btw you can enable mouse&keyboard controls and bind rotation to the volume up/down buttons

**Comment by itcannotbe** [comment]
You also seem to forget the amount of items the reconstructor can hold also.

**Comment by Legomonster33** [comment]
> Its simple really
i can assure you that this is nearly **never** the case

**Comment by scarf-generic** [comment]
So basically #937

**Comment by itcannotbe** [comment]
> So basically #937

Exactly.

**Comment by QmelZ** [comment]
> Breaking a tetrative reconstructor? Okaay.

they said a unit factory, not a tetrarive reconstructor.

**Comment by DayTimer** [comment]
The thing is, recontructors have the same problem.

And I'm pretty sure he meant recontructors too...

**Comment by kingb74** [comment]
> The thing is, recontructors have the same problem.
> 
> And I'm pretty sure he meant recontructors too...

Yea I did

**Comment by kingb74** [comment]
> Breaking a tetrative reconstructor? Okaay.
> 
> Btw you can enable mouse&keyboard controls and bind rotation to the volume up/down buttons

Dude what do u mean like 
Blind rotation 
Volume 
What do the volume buttons have to do with it

**Comment by DayTimer** [comment]
> Dude what do u mean like
> Blind rotation
> Volume
> What do the volume buttons have to do with it

I meant that:
![IMG_20201031_205240_395](https://user-images.githubusercontent.com/69920617/97784947-9e15df80-1bbb-11eb-868f-cc6be44438d9.jpg)

When you press the volume up button, the building you clicked on will be rotated by 90°. Thats the only way to rotate an exciting building in mobile version

**Comment by scarf-generic** [comment]
> > Dude what do u mean like
> > Blind rotation
> > Volume
> > What do the volume buttons have to do with it
> 
> I meant that:
> ![IMG_20201031_205240_395](https://user-images.githubusercontent.com/69920617/97784947-9e15df80-1bbb-11eb-868f-cc6be44438d9.jpg)
> 
> When you press the volume up button, the building you clicked on will be rotated by 90°. Thats the only way to rotate an exciting building in mobile version

Yes. Navigating multiple menus, changing keybinds, rotating, and changing everything back is extremely impractical compared to pc users pressing a button and moving their index finger.
