### ISSUE TITLE
Let us build T1 factories on top of other T1 factories

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#1017]
**Describe the content or mechanics you are proposing.**
Similarly to how walls/conveyors/pipes/turrets can be built on top of each other

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
+1 QOL 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
> Similarly to how walls/conveyors/pipes/turrets can be built on top of each other
Wait WHAT?

**Comment by TheSlaylord** [comment]
1. what
2. what
3. what

**Comment by the-kido** [comment]
is he talking about the ground, naval, and air factories? If so that makes more sense

**Comment by summetdev** [comment]
@Highfire1 implemented by me. :+1:
