### ISSUE TITLE
Ability for a server to disable mobile autotarget

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1018]
**Describe the content or mechanics you are proposing.**
Make servers able to disable the autotarget feature mobile clients have.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would allow for gamemodes such as fog of war to work properly, currently mobile autotarget breaks them as it allows mobile to spot things in the darkness easily. (See: routerchain.ddns.net on 6.0)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
mod/fork that disables disabling auto target or jerry rigs its own

**Comment by Ilya246** [comment]
you can disable lighting via clientside console too, which is much easier, but does anyone do that? Also the same ^ argument could be used against many other things already in the game
