### ISSUE TITLE
Tsunami liquid consumption nerf

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1019]
**Describe what you would like changed, and why.**
Tsunami's liquid consumption, which is currently equal to that of Wave.

**Describe the changes you want to propose. Include possible alternatives.**
Increase the liquid consumption to proper values.

**Comment by Slava0135** [comment]
Initially I didn't think it's possible: every other turret doesn't have multiplier below 1. But I've just looked into the code now it should work perfectly. I did want to do it in first place...
