### ISSUE TITLE
Builder drone idea.

### ISSUE THREAD

**Issue by potatoisagender** [Anuken/Mindustry-Suggestions#102]
I've seen a few ideas here that involve AI and repathing the builder drones (https://github.com/Anuken/Mindustry-Suggestions/issues/19, https://github.com/Anuken/Mindustry-Suggestions/issues/13, https://github.com/Anuken/Mindustry-Suggestions/issues/33). One of the problems I find most irritating is when all the drones flock around a single person in multiplayer. Perhaps a new pathing system could involve splitting the drones equally (or as equally as possible) among all the players.

**Comment by itcannotbe** [comment]
Fun fact. More builder drones focused on one block builds that block faster.

**Comment by itcannotbe** [comment]
The problem comes from people build unnecessary massive stuff right off the bat which makes those builder drones be unnecessarily occupied.

**Comment by potatoisagender** [comment]
I know about the above. The problem is with the below. If the drones can be split evenly, the gives everyone a little bonus, which can be stacked if people start to help build large schems. This feature would be easier if #101 were incorporated.
