### ISSUE TITLE
Patrol

### ISSUE THREAD

**Issue by DatOnePlayer** [Anuken/Mindustry-Suggestions#1020]
I want a block that has a purpose as patrol points, like a beacon that if you put two in lines, they will automatically go on their patrol route, and if you put several, they will head to point 1-2-3 and then return to their starting point

This feature will help the usage of combat units in survival games, and instead cramping and camping on enemy spawn points (especially multiple which all units will focus on the nearest ones) they will patrol on most likely weakspots (off base power lines, or rare resources mining spot)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
bruh just use anuke logic

**Comment by Catchears** [comment]
nice idea but how would you set the order and Delta's point above is also true: use logic, it's not as hard as it looks.
