### ISSUE TITLE
Increase Ammo Multiplier of Surge Ammo (for missiles, at least)

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#1022]
**Describe what you would like changed, and why.**

In a way, you can rank all Mindustry materials with a point system. For example lets say:
copper = 1 point
lead = 1 point
sand = 1 point
coal = 1.5 points
titanium = 2 points

Then something like graphite would be worth:
graphite = 2 * coal = 2 * 1.5 = 3 points

I do realize this is not an accurate system, but it was the best I could come up with (for now). 

I'll spare you the math; Surge alloy is worth 21.5 points. 

Now lets compare it to another ammo, Pyratite, a material worth 5.5 points. 

*These stats were taken from the swarmer in build 10951*
| Stat            | Pyratite | Surge Alloy |
|-----------------|----------|-------------|
| Damage          | 12       | 18          |
| Splash Area     | 2.5      | 3.1         |
| Splash Dmg      | 20       | 25          |
| Ammo Multiplier | 2        | 2           |
| Status Amount*  | 1        | 2           |
| Status Dmg**     | 60       | 10          |
| Status Area***    | 2.5      | 10          |

**Status Amount = lightning tendrils/amount of burning;*
***Status Damage = lightning damage/burning damage over 8 seconds;*
****Status Area = lightning length/Splash Area*

Well, the surge alloy missile ammo is still trash, considering one surge ammo should be is worth 4 or 3 pyratite. No wonder the only people who use it are people with item sources.

**Describe the changes you want to propose. Include possible alternatives.**

Clearly, it needs a buff. But I don't think it needs one in damage. Any more Dps and it will unbalance the game. So instead, I suggest an **Ammo Multiplier buff**.

**Comment by D-player1** [comment]
~~the point of surge swarmer is to trade higher dps with more ammo consumption when compared to surge cyclone~~

**Comment by genNAowl** [comment]
~~Fair enough, but it doesn't have enough dps to matter~~

**Comment by genNAowl** [comment]
bonk
