### ISSUE TITLE
Allow Servers To Disable Unit Control/Command

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#1023]
**Describe the content or mechanics you are proposing.**

Make a setting to allow servers to disable unit control and unit command, so you have to rely on the AI, and not rely on cheesing your opponents defences...THIS WOULD BE OPTIONAL (please no hate), on the servers settings...

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Lots of people enjoy this feature, however lots of people don't like getting horizon bombed like 5 minutes into the match.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by BlueWolf3682** [comment]
we should notify you that the units from the core ARE considered full on units, so you wouldnt be able to spawn.

**Comment by 50275** [comment]
The main advantage of unit control is being able to micromanage faster
Have you ever tried building a defense against any T3 without using any support units? It's not happening, ever.

And if you are worried about someone cheering your defenses get a few quasars and say goodbye.

**Comment by Ilya246** [comment]
You know that if it were that way the game wouldn't ever end? Currently most PVP matches have the ability to end solely due to that way of unit control; And also, instead of controlling them yourself, you can control them indirectly via a processor

**Comment by scarf-generic** [comment]
Whats with people wanting options to make the game worse in map settings? Not make the game harder or easier, just straight up disabling features of the game. Oh and also unit control is kind of an anti-stalemate thing for pvp, so enjoy your never ending matches.

**Comment by ShadeStrike62** [comment]
look, all I'm saying is in the current state, it is WAY to overpowered for griefing...maybe not a flat removal, but at least a scale. Maybe limited control over units like not being able to change their pathfinding but use their targeting, or taking control of units costs something, so it is not so cheap a tactic...perhaps a new block called the control station, allowing players to command units within its radius (quite large but around the size of a mass driver). This block might need upgrading depending on the tier of the units...just putting out ideas

**Comment by ShadeStrike62** [comment]
> You know that if it were that way the game wouldn't ever end? Currently most PVP matches have the ability to end solely due to that way of unit control; And also, instead of controlling them yourself, you can control them indirectly via a processor; Shouldn't be implemented due to lack of uses.

I agree, I just think that the feature causes most PVP matches to end far to early...in V5, you didn't win with 3 horizons, and in V6, your opponents have to make defences potentially right next to their core just so you don't game end them 2 mins into the match...

**Comment by 50275** [comment]
Griefing is completely different. In that scenario, intelligent griefers can use logic to screw everything up such as wasting ammo, suiciding or mass deleting automatically with all of your megas.

And, if you were effectively required to use processors to indirectly control units the same way wouldn't that completely remove the entire point of the suggestion itself?

**Comment by 50275** [comment]
Close this.
