### ISSUE TITLE
New small addons

### ISSUE THREAD

**Issue by Hexacrab** [Anuken/Mindustry-Suggestions#1026]
-details like dirt example unit goes through the mud and gets dirty

(because that gonna look better and just add small details for the game)

-Animations of the core being thrown from space, Mother ship or Shot from a Planet of origin in the sectors

(I think core going to the sectors looks very simple just fall from the sky)

- sector control system like if you conquer all sectors around one (min 3 surrounding a Hexagon) that one will not be attacked

(Like a total capture of the sector but maybe random events for don't be just a farm and boring sector)

-random events like an asteroid crash to destroy buildings or an enemy capital ship with X number of waves ↑↑↑

- Planetary Domination example 1 so Faction on one planet or 2-3 in the same conflicting AIs, possibility of having Diplomacy among other AIs in exchange for resources, etc.

↑↑↑ (That i think it's just for don't get bored and maybe a Game mode option instead of play alone maybe)

and the last one thing is the Hexagons with simbols showing you warnings like a skull for a high enemy aglomeration or a enemy core And sectors with (?) maybe grey colour like unknown or dont "claimed" for enemies

**Comment by DayTimer** [comment]
Your sector will not be attacked if there is no enemy base nearby (a sector with enemy core). Sectors with an enemy core has a red outline.

And as i know, Anuke will not add anything new because the game will be released soon...

**Comment by a-soulspark** [comment]
> And as i know, Anuke will not add anything new because the game will be released soon...

v6 will be released soon, not the game. I believe Anuken meant there won't be any new major features until **the next update**.

**Comment by DayTimer** [comment]
Yeah i meant in v6. Imo the development of 7.0 will start no earlier than mid-2021 so there is no sense in these suggestions...
