### ISSUE TITLE
Unit teaching/learning

### ISSUE THREAD

**Issue by RGOTI-Official** [Anuken/Mindustry-Suggestions#1027]
**Describe the content or mechanics you are proposing.**

Ai Learning/Teaching. (add a button that tells units when to record and play movement)

once you recruit units to follow you (like flares, daggers, and such) they copy your moves right? (direction, attack, item grabbing) so why not implement a feature that tells them to do and repeat? that can be helpful for people who dont want to just use units for fighting and instead use them for special purposes without learning the logic system, which can help alot because me and quite a bunch of people tend to struggle to make a proper logic display or even do a simple delivery system, so adding a learning/teaching mechanism for certain units can be helpful espeicially if your playing single player and need some resource delivering help instead of defense.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

• Ai Learning/teaching can be useful for single player users when they need a helping hand but dont have other players to invite
• Ai Learning/teaching can be very accessible for people who dont know how to use the logic system properly
• Ai Learning/teaching can be useful for covering a huge area without spending alot of time

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RGOTI-Official** [comment]
> No need to do that, logic is extremely easy; Also, that would probably take a lot of effort

You cant just say logic is extremely easy while a bunch of people including me struggle to make a unit do a delivery system without the unit having a seizure. The thing i find hardest on logic is making a do and repeat unit control.

**Comment by TheSlaylord** [comment]
_logic:_ am I a joke to you?

**Comment by scarf-generic** [comment]
> You cant just say logic is extremely easy while a bunch of people including me struggle to make a unit do a delivery system without the unit having a seizure. The thing i find hardest on logic is making a do and repeat unit control.

I am one of these people. This suggestion sucks.

**Comment by PlanetOrca** [comment]
I appreciate the idea buddy, but if you want teaching and learning check out Autonauts. That’s probably more your style, and it can help you learn the logic system here as well
