### ISSUE TITLE
Big blocks + deepwater

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1028]
**Describe the content or mechanics you are proposing.**
Instead of having big blocks not able to be placed on deep water at all, make them placeable as long as the nearest land/shallow water is at least as close as the size of the block.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make sense that big blocks can be placed deeper in.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
We really need walls on water at the very least.
