### ISSUE TITLE
Make mindustry suggestions a reddit community not a github repository

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1029]
**Describe the content or mechanics you are proposing.**
Im asking for this suggestion system to be on reddit so people can properly upvote the ideas to make them seen more instead of great ideas being lost in new. This would make it so Anuke can see the best ideas at the top that the community has upvoted.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

N/A

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
1. reddit sucks

2. it was like that before with feathub but anuke scrapped it

**Comment by GlennFolker** [comment]
> N/A

exactly. this is not needed
