### ISSUE TITLE
Players send language settings to server to allow autmatic translations

### ISSUE THREAD

**Issue by Recessive** [Anuken/Mindustry-Suggestions#103]
**Describe the content or mechanics you are proposing.**
It would simply be a field in the player object, such as `player.language` so the server can know what language the player has their Mindustry set to.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would really help servers mitigate the language barrier, by providing translations to command descriptions, motd etc.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
already possible with plugins, which are  the only thing that could use this

**Comment by DeltaNedas** [comment]
@Recessive pr made
