### ISSUE TITLE
Watch Tower

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1030]
**Describe the content or mechanics you are proposing.**
A 2×2 tower which can be used to control your unit guards. The watch tower would be made with 50 graphite, 100 copper, 65 silicon and 35 titanium. It would be pretty straight forward, it would call any idle units to the location of a enemy in the watch towers range and the supposed guard units would then pursuit the units to where the units last were seen (from the watch tower). Using multiple towers could make a system where if your defences fail you, your idle guard units would chase after them, instead of running straight to the enemy spawn.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
logic processor is a 2x2 block that can bind units make them approach the processor and follow any enemies

**Comment by nodevlfrb** [comment]
> logic processor is a 2x2 block that can bind units make them approach the processor and follow any enemies

Yeah but maybe not everyone knows how to use the processor in this way

**Comment by 50275** [comment]
Command center or manual control
