### ISSUE TITLE
Abandon/Reroll/Reset sector option

### ISSUE THREAD

**Issue by Phantom-Kit** [Anuken/Mindustry-Suggestions#1031]
**Describe the content or mechanics you are proposing.**

An option to 'abandon' a sector, resetting it to an 'unexplored' state, and allowing for the re-roll of the player core spawn point and the enemy drop point.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently, sectors will roll a core spawn point and an enemy drop point (for sectors that have more than one option) the first time they are entered, and then will keep that same set of spawns for the rest of that campaign, including if the core is destroyed. This results in the possibility of getting a bad spawn (a tight canyon for example), and no way to improve this without resetting the whole campaign. 

My suggestion would be to add an ability to 'abandon' a sector, as you had in v5.0. This would mean the player loses all resources in the sector, and resets it completely, allowing for a re-roll of the rng elements. This would reduce the frustration of a bad spawn from making the choice between playing the bad spawn anyways or resetting the whole campaign, to playing it anyways or resetting the sector. It also would open up the idea of resetting a specific sector to build more efficiently from the start if the player has the resources to lose an established sector and restart it. This would improve replay-ability for the campaign, allowing people to replay sectors without sacrificing their other sectors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Just intentionally die

**Comment by Phantom-Kit** [comment]
The problem is that the sector will not reset when you die. It keeps the same spawn for you and for enemies.

For example, on frozen forest, if you spawn in a canyon on the right side of the map with enemies spawning on the top right, and then die, returning to the frozen forest later will spawn you in the exact same place with the same enemy spawn. If you were to start a new campaign and go there your spawn would be random again, but would be locked liked that until you cleared the campaign again.

The idea is to have the ability to reset the map without having to reset everything.

**Comment by 50275** [comment]
it isn't a big deal, you shouldn't need to depend on RNG for things

**Comment by Phantom-Kit** [comment]
While I would agree, there isn't a need to depend on the RNG (the sector can still be completed with a 'poor spawn') it does subtract from the 'fun' for me. Primarily because a bad spawn feels like a let down that has to be worked around as opposed to an interesting challenge, and is permanent for a campaign run. I feel RNG should never create something permanent as that interferes with player agency. That may be just something I'm feeling, but I figured the option would be easy enough and wouldn't hurt anyone who found it a fun challenge. In my mind its less about 'beating the RNG' and more about creating a more enjoyable experience.

Another possibility would be allow the core to be moved at some point (when you get to the point of being able to build higher level cores.) However that idea feels much more complicated and results in a similar outcome to my mind.

**Comment by Phantom-Kit** [comment]
Another problem I've not personally experienced but saw another person get on the subreddit is that the enemies polys can build close enough to attack the core, so returning to a sector lost like that will result in the core being fired upon immediately. A reset ability would solve that problem (though lore wise it may not make sense, abandoning the sector makes the enemy do the same?). Though that problem probably also has other, more direct solutions.

**Comment by alexHunter854** [comment]
> Another problem I've not personally experienced but saw another person get on the subreddit is that the enemies polys can build close enough to attack the core, so returning to a sector lost like that will result in the core being fired upon immediately. A reset ability would solve that problem (though lore wise it may not make sense, abandoning the sector makes the enemy do the same?). Though that problem probably also has other, more direct solutions.

it could work lore wise if you do somthing with satellites, maybe like a "satellites bombing" button, and just say the enemy rebuilt what it had in the start, and maybe have it cost 5k blast compound so you can't just do it over and over without sufficient infrastructure or maybe some other explnation but thats what i had in mind

**Comment by Phantom-Kit** [comment]
Yeah, honestly just having a reset button I think would be enough. Sometimes things following 'game logic' are fine. I like the idea of the abandon button like was present in v5.0

**Comment by TheEvilSkeleton** [comment]
Open sesame.

**Comment by UltraBlackLinux** [comment]
Bump...
(Don't mind me)

**Comment by itcannotbe** [comment]
That's not how it works. You can't bump a bot closed issue.
