### ISSUE TITLE
Start building instantly (option for mobile users)

### ISSUE THREAD

**Issue by MHeMoTexHuK** [Anuken/Mindustry-Suggestions#1033]
**Description:** An option/setting for mobile version. When enabled, planned buildings will be built immediately without needing to press the accept button (long-press deletion already works like this)

**Why:** Sometimes you really need to build something faster. That would be helpful. In addition, the constant pressing of the accept button is annoying...

------

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by YellOw139** [comment]
Or how about double tap on building plan to start building it?
This way you can specify the position of a building *and* build it fast. Precision and efficiency.

**Comment by itcannotbe** [comment]
Great suggestion but didn't even bother using the template like a normal person would.

**Comment by itcannotbe** [comment]
A toggle between plan then build and place then build is a welcome change for mobile. Maybe for desktop as well?

**Comment by DayTimer** [comment]
> Great suggestion but didn't even bother using the template like a normal person would.

Wdym? I simply shortened it. "Description" = "Describe what you want to be added.. blah blah blah"
"Why" = "Describe how it would improve the game... Blah blah blah"

**Comment by scarf-generic** [comment]
> A toggle between plan then build and place then build is a welcome change for mobile. Maybe for desktop as well?

For desktop: press e
