### ISSUE TITLE
Specify port to join when joining a server

### ISSUE THREAD

**Issue by Kyllingene** [Anuken/Mindustry-Suggestions#1034]
When you try to join a Mindustry dedicated server, it assumes port 6567. It would be very helpful if you had a way to specify what port you are trying to join.

It would be best to not have it be a config, because that would be quite annoying, especially if someone (like myself) tried to use a program (like ngrok) to forward a port temporarily. Two potential ways to implement this are: 

1) If just given an IP, assume port 6567 (such as if you enter "a.b.c.d", it would assume "a.b.c.d:6567"), but if a port is specified (such as "a.b.c.d:12345"), use that port. Or, you could 

2) Add a box on the same screen, maybe like this:
```
               +-------------------+
    Address:   |                   |
               +-------------------+

               +-------------------+
       Port:   |                   |
               +-------------------+
```

**Comment by DeltaNedas** [comment]
did you try that very format you specified?

**Comment by Kyllingene** [comment]
Yes, several times.

**Comment by BlueWolf3682** [comment]
uh, [server.ip]:[port]

**Comment by Kyllingene** [comment]
That did not work for me, maybe there was something wrong with my computer / ngrok? I usually don't have problems with ngrok though...

**Comment by 50275** [comment]
I remember using something like ggg.sytes.net:0000

**Comment by Kyllingene** [comment]
OK, since it seems to already work (even if I can't get it to), I will close this.
