### ISSUE TITLE
NERF FUCKIN' HORIZON!

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#1035]
**Describe what you would like changed, and why.**
It's too OP as fuck, horizon has 350 hp, that's like 5x the health of a flare, it's damage is too powerful, 7 of them can destroy a core shard easily, horizon is the fastest T2, just rush horizons and enemies can't react fast enough to counter it,
You can literally cheese any place in the enemy base if it has no scatters, it can make your coal factory on fire, horizon is the easiest T2 to get, only needs 55 silicon and 40 graphite, only 2 kinds of materials, just put them in your siicon lane, and that's it. You have a horizon, even though scatter solves this problem, do we have to waste thousands of copper and lead to build scatters, and that's not even considering refilling their ammo, command groups exists, players often come in group to get past scatters and go straight for the core instead, making it an instant win

**Describe the changes you want to propose. Include possible alternatives.**
Nerf their health, damage, or speed, and possibly their command limit, a swarm of horizon just felt like a mini quad now

**Comment by scarf-generic** [comment]
While the damage of them is a bit absurd, i dont think they need a nerf. 20 is the maximum amount of them you can make in pvp. Given that you can **defend against 20 horizons before making any silicon**, i think its pretty balanced. Try using a wave with water to push them back, and make metalglass scatters.

**Comment by Sanya2907** [comment]
Yeah, I agree too, their health and speed needs to be nerfed, but damage is fine.

**Comment by GlennFolker** [comment]
Its balanced geez, clearly more expensive than revenants

**Comment by RouterChainsSuckk** [comment]
Someones salty about losing

**Comment by D-player1** [comment]
> Someones salty about losing

And seeing the same unit over and over again, seriously, why don't people just use Mace, Pulsar, and Atrax. Pulsars can fly anway

**Comment by GlennFolker** [comment]
i sense someone ragequitting

**Comment by Ilya246** [comment]
no need to nerf them - scatter ABSOLUTELY kills them and you don't actually need much of it for full coverage

**Comment by D-player1** [comment]
Horizon is not Flare

**Comment by D-player1** [comment]
Plis, Scatter is very inaccurate, literally takes more than 10 seconds when a horizon standing still in it's range

**Comment by D-player1** [comment]
For the people who said i'm losing at pvp
![Screenshot_2020-11-02-12-30-13-97](https://user-images.githubusercontent.com/70744599/97883026-ef0e0b00-1d56-11eb-910e-43dd60bb045b.png)
![Screenshot_2020-10-29-07-12-16-96](https://user-images.githubusercontent.com/70744599/97883049-f6cdaf80-1d56-11eb-88b3-40f22c0bcc55.png)

**Comment by RouterChainsSuckk** [comment]
> For the people who said i'm losing at pvp
> ![Screenshot_2020-11-02-12-30-13-97](https://user-images.githubusercontent.com/70744599/97883026-ef0e0b00-1d56-11eb-910e-43dd60bb045b.png)
> ![Screenshot_2020-10-29-07-12-16-96](https://user-images.githubusercontent.com/70744599/97883049-f6cdaf80-1d56-11eb-88b3-40f22c0bcc55.png)

Atrumba isn't that good tbh t4 support is much better so yes you are losing

**Comment by D-player1** [comment]
I don't, someone else made it

**Comment by 50275** [comment]
nice to see someone else make your base I guess
anyway, you can simply just use lead scatters like everyone else provided you have enough mono drones
also why not store some lead in a few bridges and just wait for when they come- you can just use a ~30-40 lead stockpile and shoot them down

**Comment by D-player1** [comment]
> Plis, Scatter is very inaccurate, literally takes more than 10 seconds when a horizon standing still in it's range

**Comment by D-player1** [comment]
And i'm the one who made all the Horizons and that one Quad
