### ISSUE TITLE
[Logic] Make it so common logic functionalities have dedicated and simple blocks

### ISSUE THREAD

**Issue by AceWall0** [Anuken/Mindustry-Suggestions#1036]
**Describe what you would like changed, and why.**

The current logic units, although powerful, they have a bad workflow. Even for people like myself that know how to code. I have some suggestions that could simplify that and still have the current blocks as an end game thing or even only sandbox. It would make it more like working with redstone and less like command-blocks.

**Describe the changes you want to propose. Include possible alternatives.**

My changes, as the title suggests, are to make more blocks less dependent of commands and would need only some configuration. Some examples are:
1. Switchs should connect directly to blocks you want to control
1. Make a "Turret Control Unit", where you just select the turrets and configure their priorities to targets
1. "Display Sequencer", where you open a dialog similar to the one we have, but instead of drawing something like a canvas API, we just add frames and each frame opens a new dialog with a canvas for us to paint in low res (maybe 16x16?). This could still be read by the processor units (image #3 at sequencer1) or just draw directly to the display with a configurable time delay.
1. "Sensor block". For this to work, It would be important if all the logic block only worked if they had power. This sensor block would work similar to a comparator in Minecraft. You put it adjacent to anything and configure it to sense something. Than, it would only pass power to another thing if said block is read.

These are some of the blocks that I thought, but they don't have to be implemented together, neither needs to be exactly like that. They are just some ideas. But I still think that the logic system needs a simpler version or a complete UI revamp so it could be not only powerful, but most important, fun.

**Comment by Humanoid-X** [comment]
That will require Anuke to rewrite his logic program near-entirely.

**Comment by DeltaNedas** [comment]
if you call yourself a koder no wonder you find pseudo assembly confusing

**Comment by AceWall0** [comment]
> if you call yourself a koder no wonder you find pseudo assembly confusing

Not confusing. Just bad to """write""". We have to be clicking stuff, dragging stuff, having to deal with big blocks of commands instead of just lines of code, things takes to much space, "go to"s become even more spaghetti than in real code... It's just a bad workflow. 
And if you think about the people who doesn't have affinity to coding, THEY would feel it pretty confusing or intimidating

**Comment by AceWall0** [comment]
> That will require Anuke to rewrite his logic program near-entirely.

Not really. Most of the things that I proposed can be like a preset of the current processors. And the current processors would still be in the game.
