### ISSUE TITLE
Let Surge Smelters be Boosted by Heat Tiles

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#1037]
**Describe what you would like changed, and why.**

Currently, due to the overwhelming amount of ingredients the surge smelter uses, they are only found near the core, making using surge as an ammo inconvenient (Its annoying to route surge from core to front line).

Allowing surge smelters to be boosted by heat tiles might encourage people to build them further away from the core, maybe increasing the use of it as an ammo. 

Dunno if this is a good idea, kind of just want to see another `attributeSmelter`.

**Describe the changes you want to propose. Include possible alternatives.**

Give Surge Smelters heat affinities.

**Comment by itcannotbe** [comment]
Anyway people won't use it since we have a magical thing called an overdrive.

**Comment by genNAowl** [comment]
fair enough

**Comment by genNAowl** [comment]
but imagine a 400% boosted surge smelter

**Comment by itcannotbe** [comment]
> but imagine a 400% boosted surge smelter
That's kinda stupid. You basically made the alloy smelter run at 1/0.3333 secs. And the attribute won't allow that.

**Comment by itcannotbe** [comment]
Although Overdriving increases power cost, using attributes don't.

But power is so easy to produce.

**Comment by scarf-generic** [comment]
More tile affinities? Dont we have enough already...

**Comment by itcannotbe** [comment]
> More tile affinities? Dont we have enough already...
Don't you want buff? Here is one.

**Comment by 50275** [comment]
don't you want to be forced to be used to use underflow gates everywhere and calculate all your ratios? here is one

**Comment by genNAowl** [comment]
bonk
