### ISSUE TITLE
translation into Russian: flying - летающий | can boost - может поднимать постройки

### ISSUE THREAD

**Issue by Motobot22** [Anuken/Mindustry-Suggestions#1038]
![IMG_20201102_104540](https://user-images.githubusercontent.com/73528418/97842745-277efc00-1cf9-11eb-96a4-54e482f8cee7.jpg)
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Who gave this person the link to the BE build again? I think this person is incapable of browsing the about this game section in game.

Also, for reference, here is the guide where you can help translate mindustry to your language [Contributing to Translations Guide](https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md)

**Comment by Motobot22** [comment]
Я вас не понял, вы ругаетесь на меня? Что я зделал не так?

пн, 2 нояб. 2020 г., 11:37 itcannotbe <notifications@github.com>:

**Comment by T1murik** [comment]
[sorry for russian *@*all_users_there_on_github]
< моё мнение >
can boost - не определено, это ещё незаконченная возможность юнитов в v6, неизвестно что они "бустят"
Летающий - да, следует перевести
</ моё мнение >

**Comment by TheSlaylord** [comment]
@Motobot22 do not send translation related issues here

**Comment by XEN0PHIL** [comment]
Can boost - может взлететь.
Есть только у наземных единиц, способных летать.

**Comment by Meltdown-Altair** [comment]
oh god no who gave him the BE download link 
shut this PR down

**Comment by Meltdown-Altair** [comment]
idk why but why post a russian pic into here and ask for help?

**Comment by Motobot22** [comment]
sorry, I forgot the rules a little, I will not make such mistakes

пн, 2 нояб. 2020 г., 16:16 Roomba <notifications@github.com>:

**Comment by TheSlaylord** [comment]
just close this.
