### ISSUE TITLE
New unit: Firefighters

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry-Suggestions#1039]
**Describe the content or mechanics you are proposing.**
New air unit class. Wold take liquid as cargo and drop it from air.
Also they would be faster than other units but at cost of health
Only tiers 3, 4, 5 would have attack
Rest would have wave-like turret
Build cost of T1 unit - 15 silicon, 20 metaglass

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Fire is a problem, and in early game, when somethin sets on fire you have not much ways to get rid of it. Buildong waves can take all resources. Units like that would help take over fires faster and easier.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
why not just let megas drop a few liquid conduits with water or cyrofluid or something
no need for another unit
