### ISSUE TITLE
Explosive barrels or objects 

### ISSUE THREAD

**Issue by Breadcommander** [Anuken/Mindustry-Suggestions#104]
**Describe the content or mechanics you are proposing.** a barrel or an object you can build then have it blow up by shooting at it

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** it would add a new reason to use oil or any barely used items or liquids, and help defend against enemies or attack a base without destroying your own builds when your defending or destroy/damage your mechs when you attack an enemy base in campaign, Pvp, or in custom maps

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Did you know that you can fill up liquid tanks with either cryo, oil, or slag and have the enemies shoot them?
You can also thorium reactor bait and drop some fuel into the reactor, blowing up air troops...

**Comment by Breadcommander** [comment]
Good to know, thx Potatoisagender

**Comment by DeltaNedas** [comment]
you can use oil to
- make coal and then graphite silicon scorches power etc
- make plastanium
- use it in waves (reaper killer)

oil is not useless

**Comment by RoyalFunnyDude** [comment]
Also this is just giving griefers another way to grief lmao
