### ISSUE TITLE
[Suggestion] Processor command 'NOT' is ambiguous

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry-Suggestions#1040]
**Describe what you would like changed, and why.**
On "Operation" command, there are 2 NOT commands, this will cause confusion in programming without printing the result out to message node.
For example:
```
set a 1
op notEqual b a a
op not c a b
print a
print b
print c
printflush message1
```
This will result in: a=1, b=0, c=-2

**Describe the changes you want to propose. Include possible alternatives.**
Change https://github.com/Anuken/Mindustry/blob/082d157c86cb0a936c2c5ff5d1919c59d327fd49/core/src/mindustry/logic/LogicOp.java#L14 to "lnot"
Change https://github.com/Anuken/Mindustry/blob/082d157c86cb0a936c2c5ff5d1919c59d327fd49/core/src/mindustry/logic/LogicOp.java#L31 to "bnot"

Because logical not of 1 is 0 -> !1 = 0, while bitwise not of 0001 is 1110 -> ~1 = -2

**Comment by itcannotbe** [comment]
Bug report might not be the best of titles.

But labeling the them different would indeed cause less confusion.

**Comment by mangblekok** [comment]
@itcannotbe There are only 3 labels: `balancing/feedback`, `feature request` and `duplicate`.
If you're saying that I'm not doing this right, what do you suggest then?

**Comment by itcannotbe** [comment]
If you're really looking to make a bug report. Why didn't you read the readme then?

**Comment by DeltaNedas** [comment]
`notEqual` says it all, no?

**Comment by mangblekok** [comment]
Implemented in https://github.com/Anuken/Mindustry/commit/6eaec7d50561e85be4465e4d73acb92125bb0569
Issue closed.
