### ISSUE TITLE
Ability for maps to execute JS on startup

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1041]
**Describe the content or mechanics you are proposing.**
Add an option for maps to execute javascript on startup. There could be a special button in the editor for that. For safety reasons, the game should notify the player if the map the player wants to load has JS or/and mention it in the map name when loading the map into the map selector.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Way more possibilities for mapmakers.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
already possible with mods

**Comment by Ilya246** [comment]
how about on a public server without every single person that wants to join having to download a mod?
