### ISSUE TITLE
Auto Bridge Conduit/-Conveyor

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#1042]
**Describe the content or mechanics you are proposing.**
Pretty much the same as auto-junctions, but bridges get placed.
It does not replace the junctions, its more an addition for spots, where a junction wouldn't work, like plastanium coveyors, power nodes, 3-block-thick rock formations, ... (Maybe even with phase conveyors?)
This makes building way faster and less annoying

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Pretty much has the same use as auto junctions, they save alot of time.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by T14D3** [comment]
Duplicate of #32

**Comment by UltraBlackLinux** [comment]
bruh, github issue search is scuffed - or I made typos
