### ISSUE TITLE
"Path to spawn" Tool improvments

### ISSUE THREAD

**Issue by Bedsurfer** [Anuken/Mindustry-Suggestions#1045]
**Describe what you would like changed, and why.**
Path to spawn is a great addition and helps alot with procedural maps, but I think the paths it creates are very straight and don't blend in well with most maps.

![image](https://user-images.githubusercontent.com/72096570/97902149-65305480-1cfa-11eb-98c1-baa9d0362be8.png)
Maybe add some noise/deviation to the paths so they don't look as jarring.
**Describe the changes you want to propose. Include possible alternatives.**
Add a slider below the "Radius"slider labled "Octaves" or something like that.

**Comment by Anuken** [comment]
That's what the "distort" tool is for. Run it after the path to make it look natural.

**Comment by Bedsurfer** [comment]
Alright, so using the "distort" tool to make the terrain look natural has led to several issues. Even at the lowest settings ( and I've tried several combinations of scale and magnitude) distortion makes the terrain look odd, and even blocks the paths "Path to spawn" opened previously
![image](https://user-images.githubusercontent.com/72096570/97908189-995c4300-1d03-11eb-998e-3843480efeef.png)
 The main issue is that distortion can block paths using any level, making it a terrible way to make it look natural.

**Comment by Bedsurfer** [comment]
![image](https://user-images.githubusercontent.com/72096570/97909699-dfb2a180-1d05-11eb-999e-46240dd2755f.png)
(An example of even modest/small amount of distort blocking paths created by "Path to spawn")
