### ISSUE TITLE
Limited Unit Control Block (Fog of War Related)

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#1047]
**Describe the content or mechanics you are proposing.**
Just saying, if for of war is added, because I know it is very popular, unit control will mess things up, just being able to go scout manually...I propose a block type (The Command Tower) that allows you to control units of a certain Tier within a certain Radius, and only in revealed areas of the fog. The radius and Tier would increase with better command towers, 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will add more strategy to a potential fog of war mode, so in the tense environment of not knowing what your opponent is doing, you get get horizon rushed in the first 2 minutes.
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
The fog of war idea would be very dumb. Custom clients, the minimap and even unit AI would completely invalidate the gamemode, revealing enemy bases and ores. Manual unit control for scouting would... simply not really work. Units have a very low view range too, which would make manual scouting a terrible idea that has no benefits.

**Comment by 50275** [comment]
https://github.com/Anuken/Mindustry/issues/545#issuecomment-517973832 golden
