### ISSUE TITLE
Thermaformers (Thermal Terraformers) 

### ISSUE THREAD

**Issue by SarisWinterwisp** [Anuken/Mindustry-Suggestions#1048]
**Describe the content or mechanics you are proposing.**

A 5 by 5 structure that would be able to slowly change land tiles when given blast compound and cryofluid. It would consume massive amounts of those resources, as well as energy and time. It'd take surge and plastanium to build as well as a hefty amount of silicon. Upon building this structure, you would be able to set it to change the five by five area to thermal spots, water, ice. Maybe it could melt snow or ice to reveal small amounts of a random vein of substance. It would start from the center square and slowly move outwards, such that you can terraform specific locations instead of a blanket 5 by 5 area each time. It might take more time to get water and thermal spots than ice or snow as well.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This structure would allow you to have better access to water, which can give you access to a navy as well, access to thermal spots since most maps lack them, access to extra ores, access to snow and ice for better water drilling, and other such things. It'd be a tool to give you greater customization of each map, because as is you just have to search to eventually find a map that suits you for whatever base you want. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
So, let's say that I needed to clear some ice to make it become water for a navy. I think you can see the problem with how many of these I will need to place.

**Comment by UglyBugly** [comment]
you can make it so that this building can change the ground in a certain radius, and not directly below it.  you can definitely change the required resources and their quantity.  you can also add the ability to modify other surface types such as stone, sand, moss, or metal panels.  for example, letting stone blocks be shattered into sand
