### ISSUE TITLE
Control options to rebuild, repair or upgrade

### ISSUE THREAD

**Issue by SarisWinterwisp** [Anuken/Mindustry-Suggestions#1049]
**Describe the content or mechanics you are proposing.**

Mass rebuild: upon losing a portion of your defense or losing the sector and coming back the ability to mass rebuild would tell your ship to rebuild all the parts that have been destroyed.

Mass repair: once you tell your ship to do this you can build over a structure or part that was damaged to make it at full health. It would likely proportionally take as long to repair as the structure is damaged

Mass upgrade: upgrades all your mechanical drills to pneumatic and regular conveyors to titanium. It utilizes all the currently available resources and won't try to upgrade something else if it were to consume more resources than currently housed.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

These would make rebuilding, repairing and upgrading things a lot less menial. You usually have to completely destroy something before repairing it, or have to mouse over every single conveyor and drill to upgrade, and then overshoot how much you can actually upgrade at one time. And rebuilding can be chaotic and time consuming as well. These'd just be nice adjustments. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
sounds like a job for polys + logic

**Comment by 50275** [comment]
"Dani: ... and then I did some googling, and then found code for a toon shader. _Our_ toonshader."
Mass rebuild is already possible. Poly drones can rebuild lost buildings even after losing the sector completely and returning. Even if the poly fails, you should be shown the previous locations of destroyed buildings - if I remember correctly this was a toggleable setting.
Mass repair can be done with any support units; megas do this automatically.
