### ISSUE TITLE
Add an easter egg screen when you capture every sector

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1052]
**Describe the content or mechanics you are proposing.**
when you capture every sector nothing happens so it would be cool if you got a little reward screen, like the game over screen but maybe it says "congration u don it"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
will make capping every sector have a fun reward to try and get

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
cont.add("behold").row();
cont.image(Core.atlas.find("god"));
buttons.button("i see", Core.app::exit);
