### ISSUE TITLE
Rebuild button

### ISSUE THREAD

**Issue by RedRanger5577** [Anuken/Mindustry-Suggestions#1053]
**Describe the content or mechanics you are proposing.**

A button to rebuild destroid buildings

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would make the game easier for maps that you wont have or need builders or if you just don't have builders yet

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by anar4732** [comment]
nope

**Comment by 50275** [comment]
Poly drone. Problem solved.
