### ISSUE TITLE
make meltdown take power when firing, NOT when targeting

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1054]
**Describe what you would like changed, and why.**
meltdown should only consume power when its laser its active, and should not while it is locking onto units (and not firing). same goes for other power based turrets too.

**Describe the changes you want to propose. Include possible alternatives.**
at the moment if you control a meltdown yourself, you just have to click for a tiny amount of time and the laser goes its full duration while consuming no power. on the flipside if you hold the mouse down and turn the meltdown without it firing the meltdown will drain power as normal. i cant see why you would want the meltdown to fire its full duration not consuming power, nor rotating and consuming power without firing. i did not test this with other turrets but its probably the same deal with those too.

**Comment by unjown** [comment]
True
