### ISSUE TITLE
 Realistic storms [probably a nerf]

### ISSUE THREAD

**Issue by Firegoesblue** [Anuken/Mindustry-Suggestions#1056]
I. Describe the content or mechanics you are proposing.

Sandstorms are a beautiful thing but this are the thing I want propose:

1. After a regular sandstorm, the efficiency of the large and a normal solar panel will be reduced to 10%
2. After a strong sandstorm with a moderate rain, the  efficiency of the large and a normal solar panel will be reduced to 50%
3. The only thing that it restore its efficiency is a turret that extinguish fire(like waves) but can't use cryofluid. 
4. The speed of a unit will be reduced to 20% when on the sandstorm and windy spore pod 
5. The speed of a ground unit will greatly reduce when on a strong sandstorm with rain.
6. Units that has a "sandy" debuff can be remove by wave.
7. Dust storms are a thing when there is a sandstorm

II. Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more 
    gameplay options or how it will fill a new niche.

Its more like a nerf to me but it should be realistic. also this request will give more importance to wave and other liquid turrets

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by BoopKittie** [comment]
One question: _why_

**Comment by QmelZ** [comment]
realistic? the rain is literally parallel to the ground, it rains from north to south. and a lot of thing i am not going to bother listing. this is just a game and it doesn't have to be realistic. i don't think it should either.

**Comment by Firegoesblue** [comment]
> One question: _why_

Why not?

**Comment by Firegoesblue** [comment]
> realistic? the rain is literally parallel to the ground, it rains from north to south. and there is a lot of things i am not going to bother listing. this is just a game and it doesn't have to be realistic. i don't think it should either.

I just want to make it balanced to the game, it would be weird if the solar panel work at complete darkness.

**Comment by scarf-generic** [comment]
> I just want to make it balanced to the game, it would be weird if the solar panel work at complete darkness.

Yeah because everybody knows one of the worst power sources in the game needs another nerf

**Comment by Firegoesblue** [comment]
> > I just want to make it balanced to the game, it would be weird if the solar panel work at complete darkness.
> 
> Yeah because everybody knows one of the worst power sources in the game needs another nerf

At the same time, this can nerf the speed of the units making the game more difficult

**Comment by 50275** [comment]
how would a covering a unit with a little bit of dust slow down the unit without having the unit walk on sand terrain slow the unit down WHAT

**Comment by 50275** [comment]
also @Firegoesblue you do realize that the solar panel already works worse when it is darker, and that we can easily pass off the dust hurting the panel by saying it is tilted or something right

**Comment by Firegoesblue** [comment]
> why does a sandstorm slow down units even after it ends while walking on sand not slow down units
> and if a dust storm is enough to hurt a unit, then pouring water on it should electrocute it LOL
> also @Firegoesblue you do realize that the solar panel already works worse when it is darker, and that we can easily pass off the dust hurting the panel by saying it is tilted or something right

No, imagine the unit a car, if it has the "sand" debuff, it decreases the speed of a car because you can't see who are the nearby cars to you and it won't get shocked because it has a safety parts or a insulator so the machine would not go nuts
Secondly, I know it's bad but can't we just agree that we use solar power to have backups and it's reliable when you don't wanna waste ammo for your weapons?

**Comment by 50275** [comment]
Realism is not important here, even Anuke said so.
![image](https://user-images.githubusercontent.com/68676339/98281646-002f6580-1f6b-11eb-9c9c-585a4578a8fd.png)
If you want realism then there's a ton of things that don't make sense such as how units e.g. flare can literally be made out of sand and coal and how oil and titanium can make a special metal literally stronger than normal titanium. Or how surge alloy has electric shock effects, while not having any power stored or anything like that. 
Actually, solar power is completely replaceable. Although free power squares are effectively removed, RTGs (they use thorium, but anuke buffed them so much that you can run a few hundred with a single airblast), and you can use impacts. (the only expensive material here is titanium)

**Comment by 50275** [comment]
Realism is not important here, even Anuke said so.
![image](https://user-images.githubusercontent.com/68676339/98281871-5c928500-1f6b-11eb-85ad-c6023a74e1db.png)
This doesn't contribute to gameplay by any means; it really just looks like a way to force players to put waves everywhere, or make games more RNG based as early game unit rushes are hindered by a sandstorm, ruining the entire rush and then killing you because of the time you wasted getting a unit you couldn't use.
Actually, solar power is completely replaceable. Although free power squares are effectively removed, RTGs (they use thorium, but anuke buffed them so much that you can run a few hundred with a single airblast), and you can use impacts. (the only expensive material here is titanium)

**Comment by Firegoesblue** [comment]
> Realism is not important here, even Anuke said so.
> ![image](https://user-images.githubusercontent.com/68676339/98283129-2b1ab900-1f6d-11eb-9921-b4dcf0328807.png)
> This doesn't contribute to gameplay by any means; it really just looks like a way to force players to put waves everywhere, or make games more RNG based as early game unit rushes in PVP are hindered by a sandstorm, ruining the entire rush and then killing you because of the time you wasted getting a unit you couldn't use - you then learn that you can only make units for combat after you get metaglass. Or, in survival a fun boss wave made by the map developer the sandstorm ruins the entire crux attack, meaning the map developer would have to remove the sandstorm for balance, which could ruin the theme of the map.
> Actually, solar power is completely replaceable. Although free power squares are effectively removed, RTGs (they use thorium, but anuke buffed them so much that you can run a few hundred with a single airblast), and you can use impacts. (the only expensive material here is titanium)

Yes I know they are useless but they give you power without asking any input, but what your saying it's like choosing a gun over a knife, a gun gives you a easy kill but you consume bullets, then a knife, hard to kill someone but doesn't need bullets. Secondly, I get it, all of the resources are expensive there but can't we just use solar as our main power/backup power supply to put the materials go to the core and focus on the turrets?

**Comment by 50275** [comment]
Solar power is useless you said it yourself
Do you have a basic understanding of the game? Solar power simply costs too much. There are better alternatives like diodes or reactors.

**Comment by 50275** [comment]
The question here is why should anuke go out of his way to make things that are already bad, worse
Who wants RNG based early game rushes in PVP?
Who wants ruined boss waves in survival and attack?
Who wants solar panels to require even more things to be usable - not like you'd use them anyway, but you may as well remove them by that point

**Comment by Firegoesblue** [comment]
> The question here is why should anuke go out of his way to make things that are already bad, worse
> Who wants RNG based early game rushes in PVP?
> Who wants ruined boss waves in survival and attack?
> Who wants solar panels to require even more things to be usable - not like you'd use them anyway, but you may as well remove them by that point

Let us just wait if anuke close this or add this

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/98375429-14796e00-2010-11eb-989b-c2f052931997.png)
![image](https://user-images.githubusercontent.com/68676339/98375381-0592bb80-2010-11eb-9490-7bb4ec11cfca.png)
About that... it's been 2 days.

**Comment by Firegoesblue** [comment]
> > ![image](https://user-images.githubusercontent.com/68676339/98375429-14796e00-2010-11eb-989b-c2f052931997.png)
> > ![image](https://user-images.githubusercontent.com/68676339/98375381-0592bb80-2010-11eb-9490-7bb4ec11cfca.png)
> 
> About that... it's been 2 days.

Yea I can wait until it collected a ton of dust

**Comment by Firegoesblue** [comment]
> > > ![image](https://user-images.githubusercontent.com/68676339/98375429-14796e00-2010-11eb-989b-c2f052931997.png)
> > > ![image](https://user-images.githubusercontent.com/68676339/98375381-0592bb80-2010-11eb-9490-7bb4ec11cfca.png)
> > 
> > 
> > About that... it's been 2 days.
> 
> Yea I can wait until it collected a ton of dust

Unless anuke add it.

**Comment by bsjohnson20** [comment]
I find it hilarious that the worst power source is getting worse its literally just 4.2 power units and you want to nerf it even more?

**Comment by Firegoesblue** [comment]
> I find it hilarious that the worst power source is getting worse its literally just 4.2 power units and you want to nerf it even more?

Probably, I want solar panels glow like illuminator because I saw on the internet that you can turn solar panels to led.

**Comment by Firegoesblue** [comment]
Anyway, I. Ima close this.

**Comment by Firegoesblue** [comment]
Ima close this

**Comment by Firegoesblue** [comment]
Ok, it's closed

**Comment by itcannotbe** [comment]
> I find it hilarious that the worst power source is getting worse its literally just 4.2 power units and you want to nerf it even more?

To bo honest I find this reasonable provided that it gets a buff before getting a storm nerf.

The only thing that makes solar panels suck is that they essentially provide free energy and it is also the reason why they give not much.

**Comment by Firegoesblue** [comment]
> > I find it hilarious that the worst power source is getting worse its literally just 4.2 power units and you want to nerf it even more?
> 
> To be honest I find this reasonable provided that it gets a buff before getting a storm nerf.
> 
> The only thing that makes solar panels suck is that they essentially provide free energy and it is also the reason why they give not much.

Yes, because we don't have a Dyson sphere
