### ISSUE TITLE
Remove processor links outside schematic selection

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1057]
**Describe what you would like changed, and why.**
Fix processor connectivity in schematics

**Describe the changes you want to propose. Include possible alternatives.**
The problem is that processor remembers connections with deleted blocks and they are not being shown. So you can easily mess stuff up by forgetting to delete the connections. And I suggest to delete all connections outside schematic selection from the processor so there won't be any "phantom" links.

**Comment by scarf-generic** [comment]
1. You say "fix processor connectivity" as if something is broken when nothing is broken
2. There is a much better suggestion to fix this "issue" ( #1043 )

**Comment by Slava0135** [comment]
>     1. You say "fix processor connectivity" as if something is broken when nothing is broken
> 
>     2. There is a much better suggestion to fix this "issue" ( #1043 )

It's broken because it's confusing

**Comment by scarf-generic** [comment]
#1043 is better than this
1. It gives more control over schematics than just removing links entirely
2. It has another good idea (flattening links)
3. Some situations need the "phantom links" you are talking about, #1043 allows for you to choose if they stay or not
