### ISSUE TITLE
Capture points for PVP and attack

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1058]
**Describe the content or mechanics you are proposing.**
The idea is that you can capture this block and get yourself a free shield field at the point. Moreover it won't allow other teams to build in a certain radius so it can be only captured by units located nearby.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
One thing I hate the most in pvp is spamming turrets on an enemy land instead of using units to attack. Arc + lancer spam is a thing and has nothing about skill but just building speed. In overall this will make fights less dumb at least. But you still will be able to use ripples as an artillery to weaken enemy positions.

Plus, you can make a new PVP mode where you need to capture these points to get score. And when your team reaches target value - you win.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by D-player1** [comment]
Or just make enemy team can't build in allied force fields, that would probably solve the problem and make force field more useful

**Comment by 50275** [comment]
Plugin that spawns quasars at captured points?

**Comment by Mothership007** [comment]
"capturable blocks" seems like a good idea in my opinion! Anuke please add!
