### ISSUE TITLE
Device Support

### ISSUE THREAD

**Issue by FootCabinet** [Anuken/Mindustry-Suggestions#106]
I play Mindustry on a dell chromebook, and I was happy to learn that I can use wasd to move. It would also be nice if there were some hotkeys/keyboard shortcuts hat could be used to make the UI more easy to use.

Adding this will make gameplay more enjoyable and make slightly tedious things be reduced.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

I'm not sure if you are.

> wasd to move

It's in the tutorial

**Comment by FootCabinet** [comment]
in the mac version, you can use right click to destroy stuff, on
chromebook, you cant. thats an example of one of the things i was talking
about. I wasn't talking about simply moving, I knew that you could use wasd
to move. also i would recommend not talking to a potential
client/customer/user like they are worthless dirt

>

-- 
This is a student email account managed by the
Iowa City Community School 
District.

**Comment by zethnest** [comment]
You should specify more clearly

**Comment by FootCabinet** [comment]
other examples would be pressing ctrl to make diagonal lines and stuff
that would be good
also thanks for responding nicely
i shouldve done that the first time
sorry

>

-- 
This is a student email account managed by the
Iowa City Community School 
District.

**Comment by zethnest** [comment]
The problem with chromebook being not fully supported because Anuke does not have one and cannot test it. I don't too. Currently not sure if there are any contributors using chromebook. Until we have one that is willing to spend their time or Anuke buys one, chromebook might not be a viable option.

Have you tried something like this?
https://platypusplatypus.com/chromebooks/enable-java/

**Comment by FootCabinet** [comment]
I've tried stuff like that before, they all lead back to having to download
and run linux aka hackerman os, and I can't do that because I can't enable
dev mode on my chromebook.
I assume that when you mean a contributor that I would have to donate or
something but if not I would be happy to test stuff.

-- 
This is a student email account managed by the
Iowa City Community School 
District.

**Comment by zethnest** [comment]
I mean a contributor that is willing to test and make it compatible with a
chromebook. They're most likely just volunteers though. I don't think
contributors get any donations.

**Comment by FootCabinet** [comment]
is there a place I can go where I could become a volunteer?
im willing to test to make sure it works on chromebook
i still have a week of online school though, but its not very time consuming
also btw my spacebar is wack so i might miss a few spaces now and then

-- 
This is a student email account managed by the
Iowa City Community School 
District.

**Comment by zethnest** [comment]
Just compile https://github.com/Anuken/Mindustry yourself and see what works or what went wrong. Do some fixing and submit a PR (Pull Request) to the repo. Owner will see anything that's unfit and request for changes if necessary. Then owner will merge.

**Comment by FootCabinet** [comment]
ive never done this before so I don't know what that means

>

-- 
This is a student email account managed by the
Iowa City Community School 
District.
