### ISSUE TITLE
the game has a problem with too many "walls" in the "walls" category

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#1060]
the game has a problem with too many "walls" in the "walls" category
here is my idea
if the walls are not in advance 1 and 2 tiers
all walls will be only 1 shooting gallery in the "walls" category, but if you put 4 small walls next to each other, they will unite and create a wall of shooting gallery 2
if you overlay it with such walls, you get a wall of tier 3 and so on
Each increase in a wall tier gives + 50% wall durability of the previous tier

also my ideas for new "walls"
walls made of scrap metal distribute damage to nearby similar walls something like “1 wall got 33% 2 got 33% 3 wall got 33% of incoming damage

lead wall “damage to the next block is 50%

also bug report
you need to remove the flammability of the "core" and give 90% protection from the damage of thorium reactors, otherwise griefers use it

**Comment by scarf-generic** [comment]
What happened to template?

**Comment by scarf-generic** [comment]
And core taking damage from things that deal damage is not a bug, and this is not for bug reports.
