### ISSUE TITLE
Some T5/T6 suggestions

### ISSUE THREAD

**Issue by LynxKFM** [Anuken/Mindustry-Suggestions#1061]
T6 Unit
-Name: Mothership/Celestia 
-Buildable: Nah
-Size and look: Was thinking of something maybe circular (inspired by Starcraft II Protoss Mothership); 20x20 tiles (at least) 
-Armament: 1 central laser turret (Vela) and around 8-12 smaller turrets at the edges; 3 zenith factories (3 active zeniths at a time); 6 flare factories (24 active flares at a time)
-Speed: 0.2
-Health: 50000

I think this can serve as an additional challenge on some maps. Would be a fun thing to play with.

T5 Turret
-Name: Tormentor
-Size: 5x5 Tiles
-Look: It's shaped into a U. When charging it creates a plasma ball within the "U".
-Range: 35 tiles
-Attack: Locks onto an area (like Corvus); aims 4s; Direct hit - 1500 dmg; area dmg - 6 tiles, leaves plasma puddle for 5s dealing 200dmg/s; after shot recharges for 6s
-Cost: 1200 surge alloy; 1000 plastanium; 750 metaglass; 750 phase fabric; 700 thorium
-Input: 50 cryofluid/s; 175 thorium/shot
-Power use: 1500/s
-Targets ground, but air units in range of plasma puddle get affected (half damage) 

A really expemsive heavy T5 assault turret for massive cleareout of units. Long charge, aim and area lock gives a balance to it's massive damage.

**Comment by scarf-generic** [comment]
Whats with people killing the format

**Comment by Catchears** [comment]
Isn't that turret just a corvus which can't move and uses more power?

**Comment by LynxKFM** [comment]
> Whats with people killing the format

Well, first I didn't know there is one, second this is just straightforward

**Comment by LynxKFM** [comment]
> Isn't that turret just a corvus which can't move and uses more power?

Well theoretically yes, although it shoots a ball of plasma instead of a giant laser penetrating everything

**Comment by the-kido** [comment]
I'm addicted to the oct so I like that top idea but what would It be upgrading from? also there is no t6 factory and i don't think people will like the idea of a 9x9 factory :/

**Comment by LynxKFM** [comment]
> I'm addicted to the oct so I like that top idea but what would It be upgrading from? also there is no t6 factory and i don't think people will like the idea of a 9x9 factory :/

Well I did include "Buildable: Nah", cause like I wouldnt want a 9x9 factory as even that wouldn't be able to fit that (it'd need to be at least 18x18 lmao). It would rather serve as some sort of only enemy thing.

**Comment by 50275** [comment]
Close this. Chances are your suggestion won't be added after the beta version.

**Comment by itcannotbe** [comment]
Why on earth would someone close a suggestion because you said so?

**Comment by LynxKFM** [comment]
> Close this. Chances are your suggestion won't be added after the beta version.

I am open to feedback on my ideas, so no. Perhaps it wont get added

**Comment by 50275** [comment]
Everything about this is ridiculous
175 thorium/sec makes the turret completely unusable without logic

**Comment by 50275** [comment]
50000 HP Mothership can easily just walk through any defenses you can make in a reasonable amount of time, and can probably outrange any turrets you can make - then again it's damage output is a joke. Its support units are worthless. Fighting it would simply be about getting a few plastanium walls, and enough salvos or something to eventually mow it down.

The Tormentor... with the firerate about half the foreshadow (foreshadow is 0.3, tormentor is 0.166) but with a 6 tile splash radius meaning that it completely outclasses every single turret in the entire game (note that the ripple) destroying any kind of balance. If I remember correctly, the ripple has a range of 37.5 tiles. It requires 29.16 thorium per second to fire.
