### ISSUE TITLE
Logic Operations For Working With Strings (And A New Block)

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1062]
**Describe the content or mechanics you are proposing.**
I propose that a few new operations and one new block be added to the game.

The new operations:
`concat`: joins two numbers/strings together at the ends, so that [12, 3, 7] becomes 1237, or ["orange", "peel"] becomes ["orangepeel"]. 
`len`: returns the length of a string as a double.
`char`: returns the _n_th character of a string, also as a string.
`num`: converts a string composed of numbers into a double. Returns `null` if any letters are present in the string.

New Block:
Input Block. Holds one line of text, **cannot** be printed to. Retrieving the `@config` of this block spits out a string.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Simple logic tweaks, would make mlog a little more diverse and allow for more complicated creations as well as adding a better overall input method.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
bruh deltanedas/anuke-logic has all that, besides strtod
anuke will not add operations that create garbage so string ops will never exist in vanilla

**Comment by sample-text-here** [comment]
> bruh deltanedas/anuke-logic has all that, besides strtod

I would prefer to have my logic work in a vanilla server though

> anuke will not add operations that create garbage so string ops will never exist in vanilla

cri
