### ISSUE TITLE
Allow Freely Building Cores In Sandbox Mode (Also, Ghost Mode)

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1063]
**Describe the content or mechanics you are proposing.**
(reopening because of a format error)
When in sandbox mode, you shouldn't need a core base to build another core. Also, in sandbox mode, you should not need to have a ship present on the map to build and interact (think _Factorio_ sandbox mode).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Simple enough, would allow sandbox users to boost the unit cap and storage cap for experimentation. 
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
Sounds good but why would not having a ship be helpful?

**Comment by YellOw139** [comment]
> Sounds good but why would not having a ship be helpful?

It's not about not *having* a ship. It's about not *needing* a ship to interact with stuff.

Basically what Violet's suggestion implies is that if your ship is destroyed by an enemy, you shouldn't have to wait for it to rebuild for you to be able to build and remove blocks.
