### ISSUE TITLE
Add a tutorial for logic because some of us might not know what we are doing

### ISSUE THREAD

**Issue by sirgamesalot010** [Anuken/Mindustry-Suggestions#1064]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
Make sure to fill out the template first
Also there is a tutorial website coming soon, for now use [DeltaNedas/rtfm](https://github.com/DeltaNedas/rtfm) (a mod)
