### ISSUE TITLE
Ground builder units

### ISSUE THREAD

**Issue by Buffoonogg** [Anuken/Mindustry-Suggestions#1066]
**Describe what you would like changed, and why.**
A ground unit type of alpha, beta and gamma. 
They should continue the greek name with Delta, Epsilon and Zeta

**Describe the changes you want to propose. Include possible alternatives.**
Able to set unit type ground or air in editor

**Comment by jaygamer81** [comment]
Perhaps the air player units can turn into ground ones when they stay still.

**Comment by 50275** [comment]
Give players the nova, pulsar or quasar. Problem solved.
