### ISSUE TITLE
Nerf quad Nerf quad Nerf quad Nerf quad Nerf quad 

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry-Suggestions#1067]
**Describe what you would like changed, and why.**
Quad needs a nerf, badly, in pvp its always what decides the game, I've seen quads tank over 75 scatters with metaglass and just kill my teams base. 

**Describe the changes you want to propose. Include possible alternatives.**
Nerf quads damage, Hp, attack speed, or fly speed, I think fly speed, damage and health would be good. Comparing quad to any other T4 and it is absurdly overpowered

**Comment by Jornker** [comment]
Please nerf this, I'm tired of having all games just instantly be decided because of it

**Comment by the-kido** [comment]
no keep the speed just lower the health or damage

**Comment by Legomonster33** [comment]
if your pvp matches are lasting to the point where the enemy has quads, you should be able to have units of your own to defend against them, or more likely already have won/lost.

**Comment by Jornker** [comment]
Even outside of pvp, in general this thing is absurd, compare its damage to the other T4s

**Comment by D-player1** [comment]
Foreshadow exists

**Comment by scarf-generic** [comment]
Hm yes #980

**Comment by scarf-generic** [comment]
> Foreshadow exists

While foreshadow does kind of counter them, surge is a very end-game material while plast and cryofluid (the things needed to build quad) are more mid-game. You should not need end-game materials to counter mid-game units.

**Comment by scarf-generic** [comment]
> if your pvp matches are lasting to the point where the enemy has quads, you should be able to have units of your own to defend against them, or more likely already have won/lost.

While this is true, quads can just fly away from any units that are attacking it. Go ahead and try to defend against 3 quads with 9 antumbras, it wont work at all.

**Comment by D-player1** [comment]
You literally need thousands of silicon for reconstructor and the units, plus phase, while foreshadow only need 900 silicon to make surge

**Comment by 50275** [comment]
Are you serious? Let's say you had 1 foreshadow. Alright, I'll just take my 9000 HP quad for a stroll in your economy area for 22 seconds, nothing wrong right? Not like I can just go straight to your foreshadow and your core or anything...

**Comment by a-soulspark** [comment]
I believe you forgot about

> Overdrive Projectors 
> Tsunamis
> Parallaxes

combined w/ Foreshadows, they can take on several Quads at a time with ease. Tsunamis push them away, Parallaxes slow them down, Foreshadows rip them apart, and Overdrive makes sure all of that happens as quickly as possible.

**Comment by Jornker** [comment]
What about all the power for that? you need a ton of power for that  to work well, and by the time you get all of it set up, you have likely had a quad kill 80% of your base, rushing for a quad can be done very quickly if done well, I'd also like to note, Most times I got rushed by quads, I've had them get hit by like 30 meta scatters and survive and kill me

**Comment by Bohaska** [comment]
Have you ever heard of a parallax?

**Comment by Jornker** [comment]
Yes but in things like pvp games, they just still go by

**Comment by Bohaska** [comment]
You seriously had to make a suggestion for this... Just ask someone to help you make a mod that nerfs quad.

**Comment by scarf-generic** [comment]
> You seriously had to make a suggestion for this... Just ask someone to help you make a mod that nerfs quad. Isn't that hard.

It appears you dont know that mods are a modification of the game. You cant play multiplayer with mods, unless everybody else has the same mod. You cant play pvp by yourself. Hope this helps you understand what this suggestion is about, you obviosuly dont right now.
