### ISSUE TITLE
[logic] Global variables

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry-Suggestions#1068]
**Describe the content or mechanics you are proposing.**

A prefix to variable names to make it global so multiple processors can access it

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think it would greatly extend the ability for logic to monitor and control various base systems by eliminating the distance restriction

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
this would make memory cells largely redundant, perhaps wifi similar to tpt could be done with special phase cells?

**Comment by anar4732** [comment]
use memory cells. you can close this.

**Comment by Austin5003** [comment]
I think chaining processors and memory cells to transmit data over distances is just a solution we're forced to use rather than what memory cells were actually designed for

**Comment by YellOw139** [comment]
Another problem I see with this is that it would be easier to get an existing global variable which already controls stuff properly, ”feed” it a value via a hidden processor (just put it somewhere no one searches for it) and then use the value to cause stuff to malfunction (e.g. you can force stop cryo conduits from any processor as long as the variable the local processor uses to stop them is global).

**Comment by YellOw139** [comment]
Wireless and Mindustry seem to simply mix up badly. Having an invisible connection to a local processor is already good enough for griefers and bad enough for players.

**Comment by Austin5003** [comment]
Have a server option to disable them, I guess

**Comment by Austin5003** [comment]
> 
> 
> Another problem I see with this is that it would be easier to get an existing global variable which already controls stuff properly, ”feed” it a value via a hidden processor (just put it somewhere no one searches for it) and then use the value to cause stuff to malfunction (e.g. you can force stop cryo conduits from any processor as long as the variable the local processor uses to stop them is global).

By your own admission, this griefing is only available if you opt into the global variable

**Comment by Austin5003** [comment]
> 
> 
> use memory cells. you can close this.

Transmitting with memory cells is slow and can't be branched easily

**Comment by Austin5003** [comment]
Issue closed since it's been a week
