### ISSUE TITLE
Fix the supporter air unit names please my OCD

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1069]
**Describe the content or mechanics you are proposing.**

Mono, Poly, mega, Quad, Oct. These were _almost_ nice and formal and since I like the last two instead....

Uni, Duo, Tri, Quad, Oct - but quad and oct are the only ones that double so...

Uni, Duo, Quad (it even has 4 guns), Oct, and Sedeca (I added an a to sound more like "deck" as per its use) 

_Please make the unit names in order as Uni, Duo, Quad, Oct, and Sedeca._ 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

My OCD.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

gotcha 

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
`Duo` is already the name of a turret so that will cause a lot of confusion

**Comment by the-kido** [comment]
> `Duo` is already the name of a turret

Yeah but spectre is also a unit. Just this once pretty please

**Comment by genNAowl** [comment]
Check out the newest builds, there is no unit named spectre, if you really believe there is a unit named spectre prove it.

**Comment by Syncinus** [comment]
I think he means scepter

**Comment by the-kido** [comment]
Yeah but it sounds practically the same

**Comment by TheTrueForce** [comment]
Not really. Spectre is "spek-ter" and sceptre is "sept-er"

**Comment by MEEPofFaith** [comment]
Why not just
`Mono` -> `Poly` -> `Mega` -> `Quadra` -> `Octo`
2 syllables each.

**Comment by 50275** [comment]
Just keep it the same, there are no issues with the current naming.

**Comment by Bohaska** [comment]
Seriously, just make a mod. Renaming stuff in programming is like singing ABC song in English. If you happen to not be able to make a mod, ask someone else to do it.

**Comment by catatagun** [comment]
> > `Duo` is already the name of a turret
> 
> Yeah but spectre is also a unit.

Wat its scepter

**Comment by itcannotbe** [comment]
Why are people making pointless comments on an suggestion that's quite literally already months inactive?

**Comment by the-kido** [comment]
lemme close this why is it still alive i don't even agree with it anymore
