### ISSUE TITLE
Allow processors to change sorters to inverted sorters, and inverted sorters into sorters.

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1070]
**Describe the content or mechanics you are proposing.**
As in the title. Let the control command change the item configuration as well as if the sorter is inverted or not.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would allow for more things to do with logic, and open up new options for schematics using logic.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by QmelZ** [comment]
i agree with the iten configuration but you might as well use a poly to place a sorter/invsorter on top of it

**Comment by 50275** [comment]
control configure sorter1 @copper 0 0 0

**Comment by scarf-generic** [comment]
> i agree with the iten configuration but you might as well use a poly to place a sorter/invsorter on top of it

Item config already exists, this suggestion is for conversion between inverted and non-inverted through the processor.

**Comment by QmelZ** [comment]
> > i agree with the iten configuration but you might as well use a poly to place a sorter/invsorter on top of it
> 
> Item config already exists, this suggestion is for conversion between inverted and non-inverted through the processor.

though your wording makes it sound like configuration doesn't exist. as i said, bind some polys and place inverted/regular sorters on top of each other because they are different blocks.

**Comment by scarf-generic** [comment]
> though your wording makes it sound like configuration doesn't exist. as i said, bind some polys and place inverted/regular sorters on top of each other because they are different blocks.
It is very impractical to bind a unit for the sole purpose of switching one tile between two states, hence me making this suggestion.

**Comment by QmelZ** [comment]
the point is, they aren't 2 different "states", they are 2 different blocks. thats why your suggestion makes no sense

**Comment by scarf-generic** [comment]
> the point is, they aren't 2 different "states", they are 2 different blocks. thats why your suggestion makes no sense

the point is, they are so similar (build cost, function, use, build time, etc.) that they might as well be the same block in different states. i wouldnt suggest this if they were not nearly identical. thats why this suggestion makes sense

**Comment by 50275** [comment]
why would you ever need to switch sorters to inverted sorters what

**Comment by QmelZ** [comment]
> why would you ever need to switch sorters to inverted sorters what

^

**Comment by scarf-generic** [comment]
> why would you ever need to switch sorters to inverted what

Mostly for schematics involving separators/dissasemblers, although really for any schematic that involves silicon crucibles, pyratite, blast, surge, or scrap. Can you name some reasons why this is a bad suggestion? Its not unbalanced, its not going to change the game for the worse, so whats wrong with it?

**Comment by 50275** [comment]
try making a design that might potentially require your suggestion to be implemented to work (provided that the user does not use unit control, or units to build)

**Comment by scarf-generic** [comment]
> try making a design that might potentially require your suggestion to be implemented to work (provided that the user does not use unit control, or units to build)

Check discord

**Comment by sample-text-here** [comment]
> Check discord

send link?

**Comment by scarf-generic** [comment]
It got added apparently, you can basically invert one by disabling it. Yey!
