### ISSUE TITLE
More easy interface for logic

### ISSUE THREAD

**Issue by anar4732** [Anuken/Mindustry-Suggestions#1071]
**Describe the content or mechanics you are proposing.**

Logic interface currently comlex and non-readable.
A puzzle like programming interface will fix this. like this.
![image](https://user-images.githubusercontent.com/10792085/98196732-64880000-1f3e-11eb-8646-6f493f2220df.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
the photo you posted makes zero sense and seems quite a bit more complicated than mindustry needs.

**Comment by RedstonerKBC** [comment]
That would be cool. I've never seen a programming interface like that. But I don't think that is appropriate for Mindustry and it is way too complex to implement. I agree our current system is a bit unintuitive and could use some tweaks. I think Mindustry was going for an assembly-like-pseudocode type of interface.

**Comment by YellOw139** [comment]
Yeah. I agree making it more like Scratch or like your picture would make it less intimidating to people who've never touched programming before. However I'm not sure if that's possible for Mindustry, especially for jumps. How would you "interface" those to be prettier? Still, the question of whether logic is supposed to feel more welcoming than it does now remains.

**Comment by Catchears** [comment]
I would suggest giving jumps more space to spread out at the side of the screen (so it's easier to tell them apart) but otherwise think the current logic system is fine.

**Comment by mwoehlke** [comment]
We need this, and/or a tutorial, or *something*. I'm a freaking *software engineer* and I have no clue what I'm supposed to do with logic. And then there's stuff like "build"... WTH is a block "0"? What direction is "2"?

**Comment by anar4732** [comment]
a interface like a code editor and auto-compileate also would good. (a help panel on side panel)
