### ISSUE TITLE
Resprite Parallaxes

### ISSUE THREAD

**Issue by chichens27** [Anuken/Mindustry-Suggestions#1072]
**Describe what you would like changed, and why.**

Here is the current parallax sprite: 
![parallax](https://user-images.githubusercontent.com/71808638/98200277-1fce7b80-1ee2-11eb-9286-54244ae19026.png)

The problem (at least in my eyes) about this sprite is the turret-to-base ratio. 

If you look at all other turret sprites, their pixels all have around 50-60% "turret" pixels (pixels that are part of the turret including outlines), the rest being "base" pixels. 

Parallaxes, on the other hand, is made up of only 40% "turret" pixels. 

This creates the issue of having too much "turret base" showing, making it stand out in the turrets page (at least to me). 

**Describe the changes you want to propose. Include possible alternatives.**

Resprite Parallaxes (make them bigger)

Segments also suffer from the same problem, but it is not as severe, so you can leave the sprite as it is.

**Comment by Bohaska** [comment]
Can't see how you can make it bigger without the parallax touching the edges. Parallaxes are narrow, so of course it will have more 'base' space.

**Comment by chichens27** [comment]
Bonk
