### ISSUE TITLE
Make Cryofluid More Efficient at Putting out Fires compared to Water

### ISSUE THREAD

**Issue by ab1gy0t3** [Anuken/Mindustry-Suggestions#1073]
**Describe the content or mechanics you are proposing.**

Cryofluid and Water Waves/Tsunamis both put out fires, but they both have the same degree of efficiency. 

Intuitively, Cryofluid should be better at putting out fires. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

PVP players need a better way to fight fires (tsunamis take way too long to put out burning cores).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
I'm pretty sure this is already a thing

**Comment by ab1gy0t3** [comment]
Yeah I just checked, and I think this is implemented
