### ISSUE TITLE
add unit statistick sensor

### ISSUE THREAD

**Issue by JellyRoad** [Anuken/Mindustry-Suggestions#1074]
Describe the content or mechanics you are proposing.
this sensor would check like a normal sensor in buildings. only that it checks in units :health, ammunition and objects that have one unit 
(sensor structure) 
result=@(health/ammo/storage) in [here you choose the type of unit]

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this unit sensor can help with to transport and mining souce and theposid source in storage block.Also it can be uesfu to auto refell ammo for unit

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - X I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - X I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - X I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
I believe that this is already possible. Bind the unit and then sense @health in @unit to sense health in the currently bound unit.

**Comment by DeltaNedas** [comment]
likewise with @itemCapacity
