### ISSUE TITLE
Graphics setting to show allied build buffers

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#1075]
**Describe the content or mechanics you are proposing.**
A toggleable graphics setting to allow players to see build buffers of other units on the same team. Mobile queues are not counted, as they're clientside. Possibly with an opacity option?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The problem of modern 5.0 and 6.0 PvP is lack of coordination, specifically building structures - one player might build logistics differently from another, have the base factory location somewhere else, etc. Adding a build buffer visualisation will allow players, regardless of communication, to either spread out or optimize build methods of another player with less conflict, as well as potentially improved handling of builder units, allowing to clear block buffers of those units (which are also known for blindly going in to build a single conveyor ignoring the entire wave in front of them)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by BasedUser** [comment]
This used to exist back in 4.0 development (?), but was never properly implemented

**Comment by BlueWolf3682** [comment]
fyi, mindustry is so entirely crossplatform that pc and mobile handle everything but ui and controls the same. in other words, pc also has build buffers clientside.
