### ISSUE TITLE
New Buildings

### ISSUE THREAD

**Issue by LynxKFM** [Anuken/Mindustry-Suggestions#1077]
**Describe the content or mechanics you are proposing.**

New Cores
-Command Center
6x6; 10000 health; 17000  items; 10k copper 10k titanium 6k silicon 6k thorium; 28 units (factory)

-Paramount
7x7; 15000 health; 25000 items; 12,5k titanium 10k silicon 7,5k thorium 5k plastanium 5k surge alloy; 40 units (factory)

3x3 walls would be a great addition in my opinion

T4 Turret - Electron
-3000 health; 4x4; build time 30s; Cost - 1000 copper 500 lead 400 surge alloy 300 titanium 300 silicon; Power use: 1500 power units/s; Input - 40 water/cryofluid (1.4 fire rate) per second; Direct hit: 500 dmg, 1st chain 250 dmg, 2nd chain 125 dmg; 3rd chain 62.5 dmg; 4s reload; 26.5 range; targets air and ground

The Electron is a giant tesla. It can fire up to 3 shots simultaneously that chain up to 3 enemies each

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Hm... More stuff is cool?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
>as well as 3x3 or even 4x4 doors (when there are a lot of units the passage clogs up)
Doors placed next to each other will open in a group.

**Comment by LynxKFM** [comment]
> > as well as 3x3 or even 4x4 doors (when there are a lot of units the passage clogs up)
> 
> Doors placed next to each other will open in a group.

oh right i forgot im stupid

**Comment by RedstonerKBC** [comment]
I always wanted 3x3 and 4x4 walls but that might be too op becuase healer blocks and units heal by percentage of health rather than fixed amount. The healers would heal health on 3x3 walls faster than anything could damage them.

**Comment by ShadeStrike62** [comment]
It kinda feels like you have not actually played the game that much, or at least not thought through your suggestions very well. Mindsutry has a very specific balance style and building sizes, anything over 4x4 needs a great reason to be so big, and the new 4x4 turret would render the foreshow rather useless in terms of damage...

**Comment by LynxKFM** [comment]
> It kinda feels like you have not actually played the game that much, or at least not thought through your suggestions very well. Mindustry has a very specific balance style and building sizes, anything over 4x4 needs a great reason to be so big, and the new 4x4 turret would render the foreshow rather useless in terms of damage...

So you suggest that the Electron is too op?

**Comment by LynxKFM** [comment]
> I always wanted 3x3 and 4x4 walls but that might be too op becuase healer blocks and units heal by percentage of health rather than fixed amount. The healers would heal health on 3x3 walls faster than anything could damage them.

In that case the healers could work differently either for 3x3 walls or all walls altogether... Cause like when setting a block to be 100x the menders render you invunerable and I don't want to be invulnerable, I want to be hard to beat lol

**Comment by Arackulele** [comment]
this islike the perfect example of a bad suggestion

**Comment by 50275** [comment]
The thing is that menders heal by a percentage of the HP of a block, so giving the same block more health (even though you made it bigger) still makes it much, much stronger
also you're really just better off making a mod, those cores will be unused
