### ISSUE TITLE
Show Leftover Required Resources when building

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#1078]
**Describe the content or mechanics you are proposing.**
If you hover over a building-in-progess block, you should be able to see what leftover resources are required to build that block.
Thanks!

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Better resource Management.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
if you select that same building with the middle mouse button then you can see what resources you need to complete it in the bottom right; in other words, this is already implemented

**Comment by rmperkow** [comment]
I think this suggestion means if you have a block that takes 50 phase fabric and you've already used 27 to build it, it will display 23 phase fabric.
