### ISSUE TITLE
Need this fixed

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1079]
Straighten the conveyor belt

This would make Conveyors not look like they are drunk and help with ascetics of the Conveyors and the other werid off sprites

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
This is the sort of thing you would want to include photos for

**Comment by DeltaNedas** [comment]
or make a bug report

**Comment by RedstonerKBC** [comment]
This is one of those pics or it didn't happen situations

**Comment by UltraBlackLinux** [comment]
Seems like nobody knows, what drunk conveyors are lol

**Comment by sample-text-here** [comment]
screenshot?

**Comment by XxsuperdeadlysniperxX** [comment]
Wobbley Conveyors

**Comment by XxsuperdeadlysniperxX** [comment]
Already fixed
