### ISSUE TITLE
New Conveyor

### ISSUE THREAD

**Issue by SpaceTime-exe** [Anuken/Mindustry-Suggestions#1080]
**Describe the content or mechanics you are proposing.**
I want a new type of conveyor that wider, like a 2 unit wide conveyor 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes when resources get all crowed in a conveyor, it gets stuck so a wider conveyor would prevent this in tighter spaces.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Mass conveyor. Plastanium conveyor. What more do you need?

**Comment by the-kido** [comment]
Yeah i dont think item transportation is an issue now

**Comment by SpaceTime-exe** [comment]
oh
