### ISSUE TITLE
Core enhancements for v6 campaign

### ISSUE THREAD

**Issue by saladbean** [Anuken/Mindustry-Suggestions#1081]
Ideas for Core Extension to complete v6 Campaign

The purpose of this buildings/enhancements is to 
-	prevent the situation where ‘captured’ sectors aren’t really captured for long, by providing a cloaking shield to the sector. The downside of this is that operating the shield takes resources, and has some drawbacks as detailed below.
-	Try to formalise the ‘launch core’ concept.
-	Allow for exploration of sectors without committing time and effort to launching and establishing a base

**The Sector Shield**
A four tiered module with the primary function of masking your sector from enemy sight.
_Tier 1_
Requires 5 copper / second and 1 lead / second to function.
Prevent enemies from scanning and attacking your sector. 
Can only be activated at key waves (like the v5 LAUNCH option) 
Can be deactivated at any time once active. Deactivation will immediately start wave counter.
Tier 1 has very basic functionality. Because it is a weak shield, no resources can be shipped off-world, so your excess copper, lead etc is stuck in that sector.
Launch pad buildings do not function when Tier 1 shield is enabled. 
_Tier 2_
Requires 5 copper / sec, 1 lead / sec, 1 graphite / sec and 30 W power.
Same as Tier 1 with following changes.
Allows small shipments to pierce the shield without enemy detection. Copper, Lead, Graphite and Silicon can be accessed off-world. All other elements/components are stuck. 
Access rate is limited to maximum of 5 units per second of each.
_Tier 3_
Requires 5 copper / sec, 1 lead / sec, 1 graphite / sec, 1 metaglass / sec, 1 spore pod / sec, 2 titanium / sec and 300 W power.
Same as Tier 2 with following changes.
Stealthed cargo ships can now export metaglass, pyrite, coal, sand, titanium.
Remove the rate limit.
Launch pads now function.
_Tier 4_
Requires 5 copper / sec, 1 lead / sec, 1 graphite / sec, 1 metaglass / sec, 1 spore pod / sec, 2 titanium / sec, 1 plastanium / sec, 1 surge / sec and 2000 W power.
Same as Tier 3 with following changes.
Can off-world all substances at any rate.

**The Core Launch Module**
This module must be built on a core before any new cores can be launched. Effectively creates a separate pot of resources that, once stored, are not accessible but are used on the next launch to a sector.
This is required to go to any sector, even ones that you have already established a base, and even shielded. Every time you change map it requires resources.
Costs copper and lead to build (so can be made on all maps). 
Possibly has an upgradable capacity? 

**The Sector Scanner**
Provides intel on adjacent sectors. Need to decide how much intel to balance…

**Comment by itcannotbe** [comment]
Sectors being attacked after being captured is a game mechanic that "prevents afking"

**Comment by saladbean** [comment]
I think my balance to prevent getting resources can prevent that AFK ing... and what does it matter it someone AFKs in a single player campaign?

**Comment by DeltaNedas** [comment]
bruh just capture enemy bases

**Comment by saladbean** [comment]
To me this is far too hard early on, and I think it's very off putting for
players who are only on say, level 3 of the campaign, to be told "ground
zero is under attack" and then lose ground zero. It's just unnecessary
stress.

And what? You have to get to some major research milestones before you're
big enough to go back and capture ground zero? Feels too grindy.
