### ISSUE TITLE
Make black coloured buildings can be captured by players

### ISSUE THREAD

**Issue by DatOnePlayer** [Anuken/Mindustry-Suggestions#1082]
Make the black coloured buildings can be captured by players

So I've seen the black coloured buildings and they did nothing if you come near it or fix their broken conveyors, I think if we can capture it would be neat, i don't know how to do it though, either using a specified building (i.e : Converting beacon : Converts buildings or units within the area)

The reason why is if this mechanic added, we could have a headstart, for instance we could have 3 laser drills and coulle defense turrets as a basic defence if we can capture it with said building

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
did you try breaking them

**Comment by genNAowl** [comment]
Yeah breaking grey buildings already gives you a head start if you have played Mindustry enough you will realize that the deconstruct refund can give players a massive head start.

**Comment by 50275** [comment]
you can already configure them anyway
if it's important stuff then blame the map developer
