### ISSUE TITLE
Water for graphite press

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#1083]
**Describe what you would like changed, and why.**
Add option for graphite press to take water to make it 20% faster. It would bake designs more compact, and increase water usefulness. Water is said to be most useful liquid, so...

**Describe the changes you want to propose. Include possible alternatives.**
Instead of water, it might be able to take cryofluid, but in my opinion water is better.

This would make early game designs better and easier to make.

**Comment by 50275** [comment]
If you can afford getting water for a graphite press, *why aren't you using a multipress?*

**Comment by genNAowl** [comment]
In my opinion, factories should not be boostable by items, as it is not an existing game mechanic nor makes sense considering Mindustry's current meta.

**Comment by 50275** [comment]
phase overdrive be like

![image](https://user-images.githubusercontent.com/68676339/98455024-5baf4e00-2139-11eb-81d4-23102cb8640b.png)

**Comment by ab1gy0t3** [comment]
@50275 Sorry if I wasn't clear on this, but I meant anything that outputs items does not take items as a booster.

**Comment by genNAowl** [comment]
Wait wrong acount that was an alt.
