### ISSUE TITLE
Gravometric mines

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#1084]
**Describe the content or mechanics you are proposing.**
A new block. Upgraded shock mine, and here are block stats:
*Powerful mine, damages and stuns enemies stepping on it. Will instantly trigger nearby mines.*
Size: 2x2
Damage: 350
2.5 tiles AOE
HP loss per hit: 100%
Build costs:
100 copper
60 graphite
30 thorium
45 plastanium
*Can not be mended*

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Mines are useful. Shock mines often get spammed. Thats why we need a better mine. To avoid spamming, its blast deals damage to nearby mines as well, setting them off.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by the-kido** [comment]
This is 350 AoE damage, right? Also, what would the range for a mine be if it _is_ AoE?

**Comment by BorisA11** [comment]
2.5 tiles
