### ISSUE TITLE
Mine spam

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#1085]
**Describe what you would like changed, and why.**
Make all mines trigger nearby mines when activated. This includes shock mines, and a potential tier 2 mine. It is useful against mine spamming, especially with new logic, you can command Polys to auto-mine a selected sector. This is wrong.

**Describe the changes you want to propose. Include possible alternatives.**
If not trigger nearby mines, make them at least more expenisve.

**Comment by 50275** [comment]
Shock mines are already very expensive
Also I'm pretty sure you can use units and logic to automatically destroy them
