### ISSUE TITLE
Making Mindustry look better (Splited)

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1086]
**Describe the content or mechanics you are proposing.**

I realized when I suggested this last time I suggested way too many things so this time I'll just mention the glowing unit lights.

There would be a setting to allow units to glow like this:
Before:
![oct without](https://user-images.githubusercontent.com/63456333/98371346-0294cc80-200a-11eb-9db6-77bc1cc726f6.png)
After:
![oct with glow](https://user-images.githubusercontent.com/63456333/98371363-0b859e00-200a-11eb-8669-c067784fc927.png)

Now with Corvus: 

Before:
![Corvus without](https://user-images.githubusercontent.com/63456333/98371622-78009d00-200a-11eb-919e-b2fb38f82bd0.png)
After:
![corvus with](https://user-images.githubusercontent.com/63456333/98371638-7fc04180-200a-11eb-9647-1dcc24dd2c97.png)

Lastly with antumbra:

Before
![antumbra without](https://user-images.githubusercontent.com/63456333/98374071-28bc6b80-200e-11eb-85bd-3af99e0fc659.png)
After:
![antumbra with](https://user-images.githubusercontent.com/63456333/98374088-2f4ae300-200e-11eb-9a9a-49ecc4b254e3.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It'll help make the game look nicer that's all.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
Just snap a .zip file of all the glowing versions of the units along with this suggestion. Maybe you can code like for example if glow-unit-setting = true, then it will find unitname-glow.png instead of unitname-png

**Comment by the-kido** [comment]
> Just snap a .zip file of all the glowing versions of the units along with this suggestion. Maybe you can code like for example if glow-unit-setting = true, then it will find unitname-glow.png instead of unitname-png

yeah thats what i was expecting. This shouldn't be too difficult to implement at all.

**Comment by BorisA11** [comment]
It seems great!

**Comment by sample-text-here** [comment]
Right now the units sprites are split into `unit` and `unit-cell`. Instead of adding a whole new set of sprites, which would take a ton of space, their sprites could be split into the two sprites above + `unit-glow`.

**Comment by the-kido** [comment]
@sample-text-here if it works it works. I'm not knowledgeable enough to coin my ideas when it comes to implementation.

**Comment by Bohaska** [comment]
Well, can you at least snap a .zip of every unit's glow variant?

**Comment by Bohaska** [comment]
Also I'm not sure this meets the requirements of mindustry sprites https://cdn.discordapp.com/attachments/656612099128164362/658614341611945994/how_to_make_sprites_U2.png (tell me if I'm wrong)

**Comment by the-kido** [comment]
Well if he hasnt implemented this by now I assume he's seen this and disliked it. Its fine tho. Clos e

**Comment by the-kido** [comment]
summetdev liked my comment my soul has been revived
