### ISSUE TITLE
Corvus, Too powerful? 

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry-Suggestions#1087]
**Describe what you would like changed, and why.**
Corvus feels pretty stupid powerful imo, On attack maps, if there are not plast walls (aka its only counter) the map is just ruined instantly as you kill everything in a few shots, if you don't have plast walls its pretty much game over for you, not really anything else that can counter.

**Describe the changes you want to propose. Include possible alternatives.**
Nerf corvuses range or attack damage, so its no longer a free win ticket and you can blindly fire and still win

**Comment by Legomonster33** [comment]
you do realize its a t5 unit and its meant to be super good,
you can get plast walls about 5 minutes into the game
you can get a corvus about 30 minutes into the game (if your trying moderately hard)

**Comment by scarf-generic** [comment]
"Corvus is good at the one thing its supposed to be good at, it needs a nerf"

**Comment by Bohaska** [comment]
I agree with the guy on top of me

**Comment by Bohaska** [comment]
@Legomonster33 Same

**Comment by the-kido** [comment]
platinum exists

**Comment by sample-text-here** [comment]
If you're in pvp, they would need 450 (exponential reconstructor cost) + 650 (for the vela) + 600 (tetrative reconstructor cost) +600 (for the corvus) = **2300** plast in total to make their first corvus. If you can't get enough plast to set up some walls, that's on you. (Also the [foreshadow](https://github.com/Anuken/Mindustry/blob/bfb3cf32f6fc3ea5758fa4708799a1d2f6c7decb/core/src/mindustry/content/Blocks.java#L1726) has a longer range than the [corvus](https://github.com/Anuken/Mindustry/blob/bfb3cf32f6fc3ea5758fa4708799a1d2f6c7decb/core/src/mindustry/content/UnitTypes.java#L510))

I actually think they need a buff. They can be stopped by a few plast walls and any other t5 can defeat a corvus.

**Comment by Sanya2907** [comment]
T5 units on attack maps 👍

**Comment by Bohaska** [comment]
@Jornker You ARE supposed to have plast walls by them. If your opponent can get 2300 plast, what stops you from getting a few hundred?

**Comment by scarf-generic** [comment]
🎉
