### ISSUE TITLE
Conveyor switches (no, I'm not trying to revive sneks)

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1088]
**Describe the content or mechanics you are proposing.**
A conveyor switch that can be toggled by a processor. The processor can change like what the switch should do (e.g. if the processor finds out that the cryofluid machines have too much titanium, it can switch the conveyor switch to redirect all titanium (switch includes sorting) to another factory, and if the factory has too much titanium... You know how it goes.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Make logic immeasurably more useful and allows for more complex bases. Also helps you fine-tune your industries so that you can extract the maximum resources possible.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

clearly not, you can use overflow/underflow gates to do just this. you can also do this with logic fairly easily.

**Comment by the-kido** [comment]
And I'm also pretty sure you can change the state a conveyor is from 1-6 with logic which further proves the unnecessity of this.

**Comment by DeltaNedas** [comment]
bruh disable underflow side conveyor

**Comment by Bohaska** [comment]
> > I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> clearly not, you can use overflow/underflow gates to do just this. you can also do this with logic fairly easily.

Can you show me? I can't find anything about it when playing in sandbox.

**Comment by sample-text-here** [comment]
![image](https://user-images.githubusercontent.com/56274831/98423034-44da0000-2042-11eb-8a40-32656c2ec0b3.png)

**Comment by Bohaska** [comment]
I know what they are. I meant like how can you use them to do what I said above.

**Comment by Bohaska** [comment]
I will like to for example use conveyor switches so that for example if my core has 2000 silicon or more, my conveyor switch will redirect them to the launch pad.

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/98454966-b85e3900-2138-11eb-9f18-36cdbcbbf04f.png)

logic code
sensor result nucleus1 @silicon
print result
print " silicon in core"
printflush message1
jump 7 greaterThan result 2000
control enabled conveyor1 1 0 0 0
end
control enabled conveyor1 0 0 0 0

**Comment by Bohaska** [comment]
thx. Didn't know that you can do that with sorters.

**Comment by scarf-generic** [comment]
> thx. Didn't know that you can do that with sorters.

Lmfao what. There is not a sorter on that screen, and it can be done with any distribution block. Whats important here is the processor.

**Comment by TheSlaylord** [comment]
50275 has suddenly mentioned a person with username `silicon` oh no

**Comment by silicon** [comment]
> 50275 has suddenly mentioned a person with username `silicon` oh no

The secrets up! Hide the missiles....

I'm use to it, i just muted it.
