### ISSUE TITLE
remove or make smooth light around bullets and units

### ISSUE THREAD

**Issue by KOT4N11** [Anuken/Mindustry-Suggestions#1089]
Light around units doesn't look good. It hurts your eyes and is very uncomfortable.
I suggest making something smoother and making it a little "bigger"

**Comment by Legomonster33** [comment]
rip format

**Comment by 50275** [comment]
I don't know about you but I like to be able to see my units
Also they're probably carrying flashlights

**Comment by the-kido** [comment]
> Also they're probably carrying **_flashlights_**

yes hyper futuristic robots with flashlights lmao.

Ik what u mean tho. Some units do need more light IMO

**Comment by KOT4N11** [comment]
you do not understand, the light contrasts strongly with the whole environment, I am for smoothness, and not for fanarics in futuristic robots
