### ISSUE TITLE
Custom win conditions

### ISSUE THREAD

**Issue by bestGaming1320** [Anuken/Mindustry-Suggestions#109]
**Describe the content or mechanics you are proposing.**

If you are making maps you should be able to make custom win conditions

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

People could easily create minigames and similar. For example there could be “Fight till wave X and collect X amountd of copper to win” 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
already possible with plugins

**Comment by bestGaming1320** [comment]
> already possible with plugins

I dont play on servers and dont have a possibility to host one by myself so an integrated function to do that would be nice

**Comment by HaphLife** [comment]
> already possible with plugins
Ahh yes, that feature exists, if you mod it in yourself. That’s an unhelpful reply. And not even using the pre-built in-game modding system either.

**Comment by DS-3K** [comment]
I suppose plugins only work on servers and not on a map specifically, so if
I want to make maps without having a public server those will be useless to
me, right?

Am So., 26. Apr. 2020 um 19:35 Uhr schrieb HaphLife <
notifications@github.com>:
