### ISSUE TITLE
Enable mobile features on desktop

### ISSUE THREAD

**Issue by mwoehlke** [Anuken/Mindustry-Suggestions#1092]
**Describe what you would like changed, and why.**
It is much, much more difficult to use the player's ship effectively in an offensive role on the desktop version. It's also harder to see what is going on and to move around the map.

**Describe the changes you want to propose. Include possible alternatives.**
Enable auto-targeting and ability to move the map (when not paused) separate from the player's ship on the desktop version.

**Comment by DeltaNedas** [comment]
1. auto aim exists because everything is painful on mobile
2. what do you think freecam does?

**Comment by scarf-generic** [comment]
Playing offensive with units on mobile is hell, you cant manually shoot and move to evade projectiles...

**Comment by BlueWolf3682** [comment]
playing offensive on mobile is admittedly better in many cases, but trying to use it on pc would be annoying

**Comment by mwoehlke** [comment]
> what do you think freecam does?

And where would that be?

> Playing offensive with units on mobile is hell, you cant manually shoot and move to evade projectiles...

Actually, I find dodging *easier* on mobile... and maybe it's just me, but I find it *extremely* hard to actually *hit* anything when I have to shoot manually... which is the whole point of the request. Anyway, auto-aim is an *option* on mobile, so if you'd rather shoot manually, nothing is stopping you even if this request is implemented.

Seriously, having played both, the only pain-point on mobile is the lack of feedback when you long-press (right-click equivalent). *Maybe* (though it's only really an issue with v6; I've only played v4 on mobile) the clunkiness of orienting buildings.

**Comment by mwoehlke** [comment]
Also, it might make sense for decoupling camera and movement to only apply the the *player* mech, or maybe have a key to quickly toggle between modes.

**Comment by silasary** [comment]
As someone playing on a laptop, a lot of the pain-points that exist on Mobile also exist when playing with a trackpad.   
My current solution is to just point my mouse in an arbitrary direction and just try to move my mech to hit the enemies.

Yes, I'm sure that aiming with keyboard+mouse is better than auto-aim.  But auto-aim is much better than just using the keyboard -_-
