### ISSUE TITLE
No bullet settings

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#1093]
**Describe the content or mechanics you are proposing.**
A settings that makes bullet invisible by player,can be turn on and off at graphics

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More challenge ideas

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
What the... Invisible bullets... No way, but more transparent bullets may be added.
