### ISSUE TITLE
Speak Polnish

### ISSUE THREAD

**Issue by Polskiklift** [Anuken/Mindustry-Suggestions#1094]
+nowe wieżyczki obronne 
+dodać kable podziemne z prądem
+stacje z stronami budowniczym
+ułatwić grę multiplayer żeby w łatwy sposób zagrać z znajomym z innego miasta
Dziękuję za rozważenie obcji

**Comment by itcannotbe** [comment]
1. I think this person doesn't know that everyone does understand polish and in that regard I think replying to him in English is fair.

2. Given that he can't understand English, I think, the poster didn't even tried to use google translate on the template provided.

In that regard, here is his translated suggestion:

> + new defense turrets
+ add underground cables with electricity
+ stations with builder parties
+ facilitate the multiplayer game to easily play with a friend from another city
Thank you for considering the option

**Comment by itcannotbe** [comment]
1. Too vague.
2. Kindly refer to the "do not suggest list" found in the readme of this github repository
3. Already in the game, duh.
4. Already in the game, why the fuck does a lot of people suggest this when it is easy enough to do, and even if you're lazy there are other ways to do it.
