### ISSUE TITLE
Logic: Locate buildings by Attributes

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#1095]
**Describe the content or mechanics you are proposing.**
I pretty much need this because I want units to locate a specific structure, that has e.g. a specific amount of cyrofluid in it. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It opens way more possibilities in terms of controlling units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
What if more then 1 building has the attributes you described?

**Comment by 50275** [comment]
how is that an issue

**Comment by UltraBlackLinux** [comment]
Then I've got a problem - maybe add the option to filter by multiple variables?
