### ISSUE TITLE
Cooling Yes

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#1096]
**Describe what you would like changed, and why.**
Cooling on Foreshadow

**Describe the changes you want to propose. Include possible alternatives.**
Why would you need to cool down Foreshadow when you have an overdrive dome that can boost the turret up to 250%.
You need 120 cyrofluid/s and you need to distribute them everytime because Foreshadow consumes cyrofluid even though it's not shooting, not to mention that it only boosts 1,2 times the speed.
So conclusion: Buff coolant, it's pointless when you have overdrive

**Comment by a-soulspark** [comment]
Better yet: boost coolant and nerf Overdrive for Foreshadows specifically.

**Comment by Bohaska** [comment]
better yet, change your issue title to 'Buff effectiveness of coolants.

**Comment by itcannotbe** [comment]
Well. The overdrive also increases the power consumption of the foreshadow, while using coolant doesn't have additional considerations.

**Comment by scarf-generic** [comment]
Use logic to disable foreshadow unless there is a target within range, helps deal with the absurd liquid cost

**Comment by YellOw139** [comment]
> Use logic to disable foreshadow unless there is a target within range, helps deal with the absurd liquid cost

Albeit this process can be triggered manually by logic, it is supposed to happen regardless. The other turrets don't constantly consume cryofluid.
