### ISSUE TITLE
Surge Boost

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1098]
**Describe the content or mechanics you are proposing.**

Alloy Smelters should be able to benefit from cryofluid input. It makes sense: the faster the smelter can cool an ingot of surge, the faster it can start making a new one. Ideally, at full cryo input (maybe 36/s) it would work at 3x speed. Note that 36 cryo/s is not a trivial amount, and requires more than one cryo mixer or at least half the output of my proposed t2 cryo mixer. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This isn't the same as a previous request to allow boosting with heat tiles, which in my opinion would have broken the game balance, but being able to boost an endgame alloy producer with an expensive semi-endgame fluid feels about balanced to me. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by bsjohnson20** [comment]
I think we'd also need some speed increase from unloaders as they would probably become the limiter

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
I think you could make the normal surge maker smaller and have a t2 surge maker the normal size. The t2 one would use cryo to be fast.

**Comment by Catchears** [comment]
>I think you could make the normal surge maker smaller and have a t2 surge maker the normal size.


Surge is pretty much the definition of an end-game resource, it makes sense for the factory to be larger.

>I think we'd also need some speed increase from unloaders as they would probably become the limiter.

But then again this could provide a reason to not build surge factories with unloaders. A surge factory boosted to 3x speed uses 9.6 lead/second, which is very close the the maximum unloader and titanium conveyor speed anyway (I think that 3x is too fast anyway, but I'll get to that in a moment).

>it would work at 3x speed.

Sorry, but I reckon that's too much. If you have a look at the other things boostable by cyro (mostly turrets), you'll see that they function at (mostly) 1.9x faster. I would propose the same (or 2x) for this.

>It makes sense: the faster the smelter can cool an ingot of surge, the faster it can start making a new one.

Yes. I agree. It does make sense. However, mindustry isn't meant to reflect real life. It's a nice idea, but I reckon it's not going to be added.

**Comment by potatoisagender** [comment]
I wonder... What if there was a boost for slag in factories? A lot of people try to make scrap to surge designs, why not melt the scrap and feed it into the smelter, as like a boost additive. It would reduce the number of resources each alloy would need, and maybe speed it up...

**Comment by sample-text-here** [comment]
> However, mindustry isn't meant to reflect real life.

There are a lot of in-game elements that have good gameplay and reflect real life. Going by your comment, water shouldn't exist because it already exists in real life. I think cooling surge is a good idea because it will finally make people make good unloaderless designs.

**Comment by Catchears** [comment]
![image](https://user-images.githubusercontent.com/57631841/98632910-b951bf00-2320-11eb-9991-bdc425cb391d.png)


> Realism has no bearing here.

**Comment by Catchears** [comment]
![image](https://user-images.githubusercontent.com/57631841/98633084-03d33b80-2321-11eb-9ce4-91075563a3a6.png)


>Reality has no bearing here

>Even if it did [in this case it does], **it would be irrelevant**.

>game balance is what matters.


Imo surge is a relatively easier (for an end-game resource) to produce. The factory requires lead, thorium and silicon and the components needed for the resource are probably in your core anyway, which makes unloader designs very popular. Do you think that it needs to be even easier? Why does surge need a buff?
