### ISSUE TITLE
Let surge alloy/plastanium and silicon being used as Scatter ammo

### ISSUE THREAD

**Issue by toarch7** [Anuken/Mindustry-Suggestions#1099]
**Describe what you would like changed, and why.**
Scatters is best (imo) and most commonly used air defence. It should have more ammo types to clear enemies at wave 100+, since lead turrets are too weak for killing Flares and Horizons with a lot of extra health. First ones are too fast for most turrets exept Spectres and second is too fat

**Describe the changes you want to propose. Include possible alternatives.**
Also it would be neat if some kinds of ammo will deal extra damage to shields (eg. surge, plastanium, phase fabric?)

**Comment by Bohaska** [comment]
scatters aren't end game towers, you should be using cyclones by then.

**Comment by D-player1** [comment]
This guy hates cyclone

**Comment by Bohaska** [comment]
use parallaxes then (and a lot of power)

**Comment by Bohaska** [comment]
And a wall of cyclones can knock off a swarm of flares.

**Comment by 50275** [comment]
duplicate of https://github.com/Anuken/Mindustry-Suggestions/issues/770 also get a cyclone you have no excuse to make mass amounts of surge alloy before 80 plastanium come on
