### ISSUE TITLE
Better Hotkey Tip

### ISSUE THREAD

**Issue by Aqzhyi** [Anuken/Mindustry-Suggestions#11]
**Describe what you would like changed, and why.**

I play many games, and games have many difference hotkeys and position.

And this game hotkeys will changes if new tech gets unlock or steam module gets added.

If I can see hotkeys number on build panel in a quick way. I can build faster like geeker in streaming Live.

**Describe the changes you want to propose. Include possible alternatives.**

![貼上的影像_2020_3_2_下午3_39](https://user-images.githubusercontent.com/1500206/75658580-8b04e580-5ca3-11ea-85fb-132c1965b2b2.png)

**Comment by Katsute** [comment]
#6

**Comment by DeltaNedas** [comment]
when you hover over a block it shows its hotkey if you enable it in settings
additionally you can see key for info in settings

**Comment by hilezi** [comment]
> when you hover over a block it shows its hotkey if you enable it in settings
> additionally you can see key for info in settings

Thanks for your information.

I wish the hotkey tips always show, not just on hover.

The current version, I want to see and remember the hotkey, I have to do, for example.

1. hover to category and see [1] or [2] or ...[0]
1. hover to items of category and see [1,1,6] or [1,2,8]
1. and when the new tech unlocks, the [1,1,6] will become to [1,1,7] and [1,2,8] will become to [1,2,9].

It bad user experience for me.

**Comment by Phinner** [comment]
It would be cool if people were closing dead pulls...
