### ISSUE TITLE
t2 crawlers/crawler rebalance and new surge wall stuff

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#1100]
**Describe the content or mechanics you are proposing.**
Crawlers are basically useless with their low health. Unless you cover 1/2 the map with factories they won't do much. I think crawlers should get a health buff and a damage nerf because if you do get a lot of crawlers and they touch then they will usually instantly destroy everything.
Either make normal crawlers less bad or have t2 crawlers. The t2 ones would probably have more health and more damage and be made or pyra or blast and something else.
Surge walls should be able to be powered. If you power 1 wall, everything around it will also be powered, but they use infinite power (or something absurdly high). When they are powered, they would zap more often when hit and also zap randomly. This way power diodes won't be used for just power generation.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Better crawlers would make a practically unused unit significantly more useful. If you could make surge walls zap more people will be more pressured to learn diodes and let you be able to use all the extra power you have late game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
Higher tier crawlers are spider units. We already have t2 crawlers.

**Comment by 50275** [comment]
Crawlers are surprisingly useful against their counterparts. It's never been so effective at killing other T1s and T2 units.

**Comment by Esnardo** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

This is there for a reason. Play 6.0 before making suggestions, units are completely different, and there are T2 crawlers.

Also, diodes only transmit stored battery power, due to technical limitations they can't transmit generated power.

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
I meant crawlers as in explodey things. The other upgraded ones are guns on legs.

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
Also what I meant for diodes was any extra power gets sent to a battery with the diodes and the battery is connected to the wall.

**Comment by DayTimer** [comment]
T1 units must be weak. They're only usefull in swarms
