### ISSUE TITLE
Diffuse walls

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1102]
**Describe the content or mechanics you are proposing.**
A diffuse wall with 2600 health. It takes half the damage it was hit by, and spreads the rest of the damage to neighboring diffuse walls (only diffuse walls) and so on and so forth.
Some images of what might it look like
<img width="32" alt="diffuse-wall-large" src="https://user-images.githubusercontent.com/73286691/98454513-2853da00-21a0-11eb-9501-a56aeaad985f.png">
<img width="16" alt="diffuse-wall" src="https://user-images.githubusercontent.com/73286691/98454512-24c05300-21a0-11eb-9f7f-4d080e6ecd37.png">

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
New challenges, new difficulties. It will also make menders more useful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
You dont need to encourage players to use walkers, they are already pretty good. This is like making ripple deal 3x as much damage because air units underused. This is a bad way of nerfing non-walker units, they are already kinda avarage.

**Comment by Bohaska** [comment]
Ok, I will drop that. Wasn't my main reason for making this suggestion anyway.

**Comment by Bohaska** [comment]
I wonder what should this block should be made out of... Plastanium and phase fabric?

**Comment by Esnardo** [comment]
This seems very OP, and it also seems like it would make a terrible combo with Corvus lasers

**Comment by Bohaska** [comment]
Just because it is made out of plastanium doesn't mean it has total resistance against lasers Lasers can pass through diffuse walls, but damage will be halved.

**Comment by Bohaska** [comment]
This is how much damage each block will take.
<img width="576" alt="Screen Shot 2020-11-08 at 11 11 19 AM" src="https://user-images.githubusercontent.com/73286691/98456032-4119bb00-21b3-11eb-9887-79245f7cb6c1.png">

**Comment by Bohaska** [comment]
Accident, ignore that

**Comment by Bohaska** [comment]
maybe this wasn't a great idea...

**Comment by 50275** [comment]
alright, guys, today we're going to crash mindustry using the diffuse wall, now, I have a 498*498 block of small diffuse walls here, and I've surrounded all of it with arcs, now-
