### ISSUE TITLE
shield gen bars

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#1103]
**Describe the content or mechanics you are proposing.**
Have an hp bar for the shield health over the block health bar when hovering on a shield.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would be a pretty big QOL thing for me because I want to know exactly how much health is left.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [\] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by EnganK** [comment]
> I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.


I strongly doubt that. This feature is already present in the latest beta.

**Comment by DeltaNedas** [comment]
the return of caggggggggggg?

**Comment by sample-text-here** [comment]
#1015
