### ISSUE TITLE
Make Horizons not damage through forcefields

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry-Suggestions#1105]
**Describe what you would like changed, and why.** Horizons are able to damage blocks under the forcefield while not damaging the shield itself. This makes the force projector somehow useless against tough Horizons.

**Describe the changes you want to propose. Include possible alternatives.** Horizon's bombs should damage the shield, and damage blocks only when it is at zero health.

**Comment by D-player1** [comment]
Actually, everything can damage blocks below force field

**Comment by DeltaNedas** [comment]
yes

**Comment by Humanoid-X** [comment]
WHAT? AM I IN MY DREAM? WON'T THIS MAKE FORCE FIELDS USELESS?!?!
