### ISSUE TITLE
Day-Night-Cycle-Button

### ISSUE THREAD

**Issue by Minze0** [Anuken/Mindustry-Suggestions#1106]
Can you please add a button that let's the player enable/disable the day-night-cycle?

I'm playing on mobile and when I want to play Mindustry outdoor it is really hard to see anything in the night (especially the coal-ore or oil). I think it would be very helpful, if there was a button that gives the player the option to play always with daylight.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
yes
