### ISSUE TITLE
Builders drones more smarter

### ISSUE THREAD

**Issue by DastalyPhantom** [Anuken/Mindustry-Suggestions#1109]
**Describe what you would like changed, and why.**
construction drones could be smarter, when I’m building a scheme, they all build the same building that I’m building, instead of each one building a separate part of the whole scheme, making them smarter would be much more  effective, a tip, is to do the bigger the size of a specific building, the more drones build it together, the smaller the size of a specific building, the more they spread and build separately

**Comment by scarf-generic** [comment]
This is pointless. Regardless on what order the drones build your schematic, it will always finish at the same time.

**Comment by DeltaNedas** [comment]
more smarter

**Comment by 50275** [comment]
just write your own logic to control the polys for you if it matters

**Comment by potatoisagender** [comment]
#750
