### ISSUE TITLE
V6 AI can build close enough to destroy player's core with ripples. (even after restarting the level)

### ISSUE THREAD

**Issue by readmexx** [Anuken/Mindustry-Suggestions#1110]
**Describe what you would like changed, and why.**

I would like the no-build radius on attack maps in the campaign increased. 

On attack maps, the enemy can build within ripple targeting range of the player's core. When you restart the level, the ripple simply destroys the core again. It looks like the player can also build ripples within direct targeting range of the enemy core.

See attached video for example of what I am describing:
[2020-11-07 23-20-51.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5506955/2020-11-07.23-20-51.zip)

**Describe the changes you want to propose. Include possible alternatives.**
I propose that the no-build radius be increased so that it does not become impossible to progress after restarting attack maps where the enemy has built turrets within range of the player's core.

**Comment by DeltaNedas** [comment]
on one hand, git gud skrub.
on the other, once you are defeated the enemy should pull back defences as they're no longer needed as far as they can tell.
