### ISSUE TITLE
More item effects for units and storage devices

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1112]
**Describe the content or mechanics you are proposing.**
have more items other than just flammables do things upon dying.
Metaglass = sends shards flying in all directions
coal = set the ground on fire
thorium = violet explosion
plastanium = leave a pile of green waste, which cannot be built onto of for a short while
surge alloy = send electric tendrils everywhere, similarly to batteries getting detonated
blast compound = deal large amounts of damage to things in close proximity

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this would make items more unique and have their own risk/reward for storing them in bulk, i.e. you want thorium reserves for your salvos, but you have to consider that if the container gets destroyed it will explode.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. (currently only for flammables)

**Comment by BlueWolf3682** [comment]
hm

**Comment by genNAowl** [comment]
Seeing how plastanium ammo has a frag effect, I think it should also have the same effect as metaglass

**Comment by scarf-generic** [comment]
Risk reward except theres no new rewards so its just a cool looking nerf :(

**Comment by cpaca** [comment]
copper, lead, and titanium could pour across the ground and make a mess (that vanishes after some time)

ground units move slower through the mess, meaning that you *could* put some storage crates at the front of your base, fill them with copper/lead, and then when the ground units destroy them, they are really slow while your turrets fire away

**Comment by Legomonster33** [comment]
> Risk reward except theres no new rewards so its just a cool looking nerf :(

the new reward is units carrying these items have a death effect, 
have a flare carry surge alloy and bam you have a portable arc-explosion.

**Comment by BlueWolf3682** [comment]
hm

**Comment by sample-text-here** [comment]
looks interesting except
> plastanium = leave a pile of green waste, which cannot be built onto of for a short while

why?
> coal = set the ground on fire

i think this would re-add coal bombing

**Comment by Legomonster33** [comment]
> why?

oil is sticky and causes contamination

> i think this would re-add coal bombing

not necessarily

**Comment by sample-text-here** [comment]
> oil is sticky and causes contamination

ok, though isn't it hardened oil? like plastic? it wouldn't be sticky, then
> not necessarily

if you set the ground on fire, it can spread over to other blocks. this is coal bombing
