### ISSUE TITLE
Custom ports when hosting a multiplayer game

### ISSUE THREAD

**Issue by SirFancypants** [Anuken/Mindustry-Suggestions#1113]
**Describe the content or mechanics you are proposing.**
Allow the usage of custom ports when hosting a multiplayer game via the host menu.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Hosting a server would be easier for some people who can only forward certain ports, or whose internet service providers only open a few select ports.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Ummmm...... You can forward a different external port to a different port internally,

Say you tell your router to port foward port 42069 from wan to 6567 on your device.

People will just have to connect to you using (my ip here):42069 and it would work.

Otherwise just use the dedicated server for a better hosting experience.

**Comment by SirFancypants** [comment]
> Ummmm...... You can forward a different external port to a different port internally,
> 
> Say you tell your router to port foward port 42069 from wan to 6567 on your device.
> 
> People will just have to connect to you using (my ip here):42069 and it would work.
> 
> Otherwise just use the dedicated server for a better hosting experience.

While that could possibly work, I'm talking about people who don't have network administration.

**Comment by itcannotbe** [comment]
Port Forwarding entails loging in yo your router.

If you don't port forward, people outside your "wifi" can't even connect*

**Comment by DeltaNedas** [comment]
if you cant log on to your router you cant port forward at all, what is the use case
additionally anuke has already addressed this in that it would break local game discovery, just use the server jar
