### ISSUE TITLE
its serious bug.

### ISSUE THREAD

**Issue by Shiningdark0930** [Anuken/Mindustry-Suggestions#1114]
I am not very good at English, so I use a translator to speak.
It's a feature that's been around since version 6.0, but it's a bit weird.
Maybe it's a bug.
For example, let's say you are going to sort out from Zone 1 to Zone 2.
Then resources are consumed, right?
But it is not. The resources in Zone 1 are still there.
For reference, I am Korean, so if you can speak Korean, please answer in Korean..!

**Comment by itcannotbe** [comment]
You do not use the resources of zone 1 when you are in zone 2.

**Comment by QmelZ** [comment]
> You do not use the resources of zone 1 when you are in zone 2.

pretty sure they meant something like "launching doesn't cost anything"

**Comment by DayTimer** [comment]
This is a repo for suggestions. You should send this to [Anuken/Mindustry](https://GitHub.com/Anuken/Mindustry/issues)
