### ISSUE TITLE
Plastanium Spectre Ammo

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1115]
**Describe what you would like changed, and why.**
Pretty simple, allow spectre to fire plastanium rounds.

**Describe the changes you want to propose. Include possible alternatives.**
As above, give spectre plastanium rounds to fire. Would probably have a low ammo multiplier. These bullets would not act like normal spectre bullets, they would be similar to reign bullets (that break apart into smaller bullets) but with slightly less damage. Possible alternatives are to do nothing, this is not something thats needed for spectre to be balanced but it would be neat.

**Comment by ThatOneBepis** [comment]
plastanium mainly frags. If you want unit-piercing rounds, how about look something that may seem more logical, such as idk, Phase Fabric maybe? Also frag bullets with pierce are a guaranteed to cause chaos.

**Comment by 50275** [comment]
c y c l o n e

**Comment by scarf-generic** [comment]
Honestly i just want a turret to shoot reign projectiles. Spectre made the most sense for it.
