### ISSUE TITLE
why did i make this

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1116]
**Describe the content or mechanics you are proposing.** On ammo based maps, have flying units crashing deal an aoe damage based on dps x ammo remaining.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** make the game more realistic and make quads into flying nukes

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I want to make the game be cancerously painful on maps with an ammo rule.

**Comment by the-kido** [comment]
You want flying units to be _better?_

**Comment by BlueWolf3682** [comment]
hehe yes

**Comment by RedRanger5577** [comment]
do you want to indirectly nerf the parallax?

**Comment by BlueWolf3682** [comment]
i want to watch the world burn
