### ISSUE TITLE
Multiplayer awareness 

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1118]
**Describe the content or mechanics you are proposing.**

Instead of having multiplayer in the "join game" section (which is in "play") make it the second button on the opening screen. This will make multiplayer a less hidden part of the game. It took me 1 month to realize it existed so I  hope that can help fix that.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Bring more attention to multiplayer. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
> Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

nice

**Comment by the-kido** [comment]
oh frick sorry

**Comment by the-kido** [comment]
Oh how ive ruined myself

**Comment by 50275** [comment]
That would ruin the organization. You play a game from the play menu... how would you miss it?

**Comment by DeltaNedas** [comment]
>have mindustry
>never clicked "play" once
>opinion has any value

**Comment by the-kido** [comment]
I need 👓
