### ISSUE TITLE
Cores reaquiring propellant to launch other blocks

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#1119]
**Describe the content or mechanics you are proposing.**
As of current build, you can configure "drop pods", core schematics which you select when launching. You can strap any parts to it. This means, that you can pretty much land with a fully installed Eclipse factory, which isnt really fair and ruins fun. So, my solutions would be this:

1) For any additional block, blast compound or pyratite is needed to launch. It is the most flammable substance, so it can be used as fuel. Every 500HP of launched blocks, you need 1 blast or pyratite. This also makes these 2 more useful.

2) You need power. If Cores use ion thrusters, power is needed. So make each core have a "battery", a certain capacity of energy. Shard has 50k, Foundation 100k and Nucleus 200k. Each HP launched takes 10 power. Meaning you need power to launch stuff. You also get a limit, since you cant store infinite power. Started schematics take no power to launch, these drills come for free

3) Limit block count. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will stop you from landing with an Eclipse factory. Currently you theoretically can load all the mats and blocks to build a damn Eclipse in wave 1. If thats not enough, you can cover the whole schematic range in drills! Which, well is unrealistic:

Core has launch thruster. No other blocks do. Means you need to use more fuel for Core to transport all of these

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
or just limit it to 3-5 tiles outside of core to limit it to vaults **or** very small factories only

**Comment by 50275** [comment]
This just sounds like an excuse to make players put more wave turrets around their core or suffer from fires and stupid vault explosions leading to death

**Comment by DeltaNedas** [comment]
vaults were not introduced in 6.0 and as i said you can just choose to not use them if you are scared of fire

**Comment by 50275** [comment]
Can cores still catch on fire?
