### ISSUE TITLE
Lumberjacks

### ISSUE THREAD

**Issue by Vladislav117** [Anuken/Mindustry-Suggestions#112]
I read on trello that you have come up with roles for mechs. So why not make lumberjacks? Currently, pines and spore pines do not carry any function. At the same time, lumberjack drones can fix this. Wood would become an irreplaceable resource. I would have to fly all the time traveling around different planets to replenish the supply of wood

**Comment by jaygamer81** [comment]
Wtf no

**Comment by Vladislav117** [comment]
> Wtf no

Why not?

**Comment by Anuken** [comment]
Why would an advanced robotic attack force with access to coal need wood?
