### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by Firetick7** [Anuken/Mindustry-Suggestions#1120]
A power node that can be turned on or off to control the flow of power

It will allow people to turn on or off certain buildings such as kilns when resources are not currently required, as well as things such as shield bubbles or unit constructors when not being actively engaged or when you don't want to make units. 

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
what do you think:
- disconnecting them from power nodes
- logic
- diodes
do?
additionally if crafters are full they wont consume anything so your example is bad

**Comment by DeltaNedas** [comment]
ok

**Comment by Legomonster33** [comment]
> * logic

sadly doesnt work :[

**Comment by DarkBrick** [comment]
It does, you just don't know how to do it

Set result to enabled of switch1
Set enabled of node1 to result

**Comment by QmelZ** [comment]
> It does, you just don't know how to do it
> 
> Set result to enabled of switch1
> Set enabled of node1 to result

still passes power

**Comment by sample-text-here** [comment]
you have to use a diode, they are the only power distribution block that can actually be disabled

**Comment by DeltaNedas** [comment]
^
but i was referring to disabling the factory, still correct
