### ISSUE TITLE
sandstorms should flicker/lie about the power you have 

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1121]
**Describe the content or mechanics you are proposing.**

When there is a sandstorm the number shown on nodes should flicker and/or lie about the power you have. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Just a nice detail.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
sand isnt a conductor why would it short out/whatever the power grid
a hypothetical ion storm should

**Comment by the-kido** [comment]
But you cant have sandstorm without storm. I would say the _wind_ would be the one doing the whole deception stuff.

**Comment by 50275** [comment]
This sounds stupid. Completely unnecessary, inconvenience that does not make sense or add to gameplay.
