### ISSUE TITLE
Smarter enemies

### ISSUE THREAD

**Issue by RedRanger5577** [Anuken/Mindustry-Suggestions#1122]
**Describe the content or mechanics you are proposing.**
If you lose at a survival sector, nothing really happens and you just launch there again,but I think the enemies should send a core to the sector, so they will start capturing the sector

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think it would make the game feel more realistic

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x]I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
if this were the case, why dont the enemies just send all of thier units to ground zero on wave 0, (yes all 1 million toxopids).
realism isnt always what works in case of gameplay. if you fail to capture a sector and the punishment because of it is harsh people will just avoid that sector.

**Comment by Humanoid-X** [comment]
That is an INFINITE loop.
The sector is hard. I tried to beat oit but I lose. Then I tried again. The enemies set a core that make the level even harder. I lose. The enemy set a new core. Then the level is even harder. I lose. There are now three cores in the sector. This loop repeat over and over again. The level is now unbeatable.

**Comment by DeltaNedas** [comment]
leave it as a rule disabled by default for noobs
