### ISSUE TITLE
Logic + r

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#1123]
**Describe the content or mechanics you are proposing.**
LET US USE LOGIC TO ROTATE BLOCKS
- with control -> suboption: rotate
- or through unit build -> config in the manner of #937 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

So many possibilities:
- better unit factories
- more control over payload / conveyors
- rube goldberg machines
- ~~trains~~

As for griefing potential, it is a little powerful, but it isn't going to do anything a player with a script can't do

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
Woohoo if this gets added mobile users will finally be able to rotate stuff. Was thinking of suggesting this but thought nobody else would want it. 👍 good suggestion, hope it gets added

**Comment by Anuken** [comment]
I usually don't comment on suggestions, but this is something that I've discussed and explicitly rejected. **Rotation is not supposed to be used this way.** It's there for player convenience so blocks don't have to be rebuilt, but it is in no way something that should be automated. It doesn't make any physical sense for a static block like a unit factory or conveyor to spontaneously rotate with logic. 

Rotating payload routers, maybe - those blocks are *designed* to have a dynamic output direction, and have a smooth animation when changing directions. Anything else? Absolutely not.

**Comment by scarf-generic** [comment]
Not even with a bound unit doing it? Aw
