### ISSUE TITLE
Shields

### ISSUE THREAD

**Issue by RedRanger5577** [Anuken/Mindustry-Suggestions#1124]
**Describe the content or mechanics you are proposing.**
Over your health there could be a yellow shield meters if the unit has shield, maybe there could be a block to apply shield to units so the sheild meter will be used more

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this could also be usefull with the quasar and pulsar so you can tell when the shield is going to break

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
> maybe there could be a block to apply shield to units

If you are talking about force fields like Quasar and Pulsar have, then I think this is too op.
