### ISSUE TITLE
Allow for player controlled units to stagger their attacks with a keybind.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1125]
**Describe what you would like changed, and why.**
with how player commanding units is. specifically attacking with units.

**Describe the changes you want to propose. Include possible alternatives.**

 it would be ***highly epic*** to have a keybind to press that would cause all controlled units to offset their attacking, such that if you were controlling 8 corvi you could have a continuous beam, instead of a single big beam. (which already can be done but is painful to do)

so instead of every Corvus attacking at the same time, each would start firing after the exact amount of time it takes for the previous ones shot to dissipate.

**Comment by QmelZ** [comment]
too op, but cool and also useful.

**Comment by Legomonster33** [comment]
> too op, but cool and also useful.

you can achieve this in game, its just a massive pain

**Comment by itcannotbe** [comment]
Can't this be done with unit logic?

**Comment by BlueWolf3682** [comment]
just flick between units and fire

**Comment by Legomonster33** [comment]
> Can't this be done with unit logic?

as i said
**yes** *however*
its quite a pain

**Comment by QmelZ** [comment]
> > too op, but cool and also useful.
> 
> you can achieve this in game, its just a massive pain

yeah that negates the opness of this feature
