### ISSUE TITLE
make the water tank correspond to the team colour

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1126]
**Describe the content or mechanics you are proposing.**
Right now we have team color dependant blocks like vaults, cores, etc. But the tank isnt yet, and it has a perfect color pallet for it too!
![Screenshot_20201109-221931_Mindustry](https://user-images.githubusercontent.com/57872394/98623591-1413f800-22da-11eb-962f-f6293038614f.jpg)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Another team dependant block

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
I agree, but we'd have to see how bad a yellow one looks.

**Comment by 50275** [comment]
Also the cyclone, foreshadow and... maybe arc?
