### ISSUE TITLE
Increase the copy limit

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1127]
It's not necessarily a change but an improvement please increase the copy beyond the delete limit so we can have bigger schematics that are not in pieces makes schematic saving 300 million times more easier because you can have 1 schematic instead of 4 different pieces of the same schematic

Well the change is above but im going to give more details about how much to expand it (if you choose to follow) and a new feature

New feature: auto save allows for you to automatically save a schematic with a option to either allow without permission and an option the require your permission with preview to save or not to save

Scaling details: expand it like 5x the size of the delete box

Misc details on feature: make the power more clear like instead of the same icon for the pos power and neg power have like usage, output, and total power needed to start if it has impacts and things that require power to start

**Comment by DeltaNedas** [comment]
use `mschmagick cat` when i port it to 6.0

**Comment by BlueWolf3682** [comment]
how about we just remove schematics and save the veteran players some pain

**Comment by DeltaNedas** [comment]
yes on your epic pro server use the rule to disable schematics and see how many people like it

**Comment by XxsuperdeadlysniperxX** [comment]
I don't own a server
