### ISSUE TITLE
Incinerators output Scrap Metal, if you need it

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1128]
**Describe the content or mechanics you are proposing.**
Incinerators output 1 scrap metal for every amount of items they burn. If an incinerator gets full of scrap metal it will automatically burn away any excess it produces. Maybe the amount of scrap they produce depends on what they burn? So 1 scrap for every 5 copper, 1 scrap for every 1 thorium, or maybe its a flat rate for all of the items? The point here is they produce scrap.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Some maps don't have scrap metal. It makes perfect sense as a way to get scrap metal. "But incinerators will be useless because you have to burn the scrap they produce and it will clog the lines and ugh!" I hear you say. No, actually because incinerators are incinerators and what do they do best? Burn excess materials. Incinerators automatically burn scrap they produce when their output buffer gets full. This means you can still use them as they are without worrying about emptying their scrap when they get full. It opens up new ways to play the game, and gives more options for mapmakers willing to create challenging maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RedstonerKBC** [comment]
Forgot to mention, incinerators can still burn scrap if you input scrap into them. Their old functionality barely changes, all we're doing is adding new functionality.

**Comment by Quezler** [comment]
this would probably be a major balancing issue

**Comment by itcannotbe** [comment]
> this would probably be a major balancing issue

basically that's what anuke said in #190

**Comment by RedstonerKBC** [comment]
Make it so 5 copper = 1 scrap or something? Or 5 anything = 1 scrap?

**Comment by Bohaska** [comment]
Maybe adding a second tier incinerator which does what you said will be better.

**Comment by 50275** [comment]
You should need all the materials you need to build scrap to be allowed to produce scrap which would completely remove the point of making it in the first place because you shouldn't be using it anyway

**Comment by Bohaska** [comment]
Should I make a pull request for it?
