### ISSUE TITLE
Naval units floating/moving in space.

### ISSUE THREAD

**Issue by LeggedMacQueen** [Anuken/Mindustry-Suggestions#1129]
**Describe the content or mechanics you are proposing.** Naval units should be able to move in space, with less friction than water, making them harder to stop/steer

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** I believe it would give a different feel to naval units, making them something akin to space"ships". It is a minor feature, considering that naval units can already be placed in Tar and Slag. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
can imagine them just floating away forever never to be seen again

**Comment by LeggedMacQueen** [comment]
You realise that it would not be that different to water, no?

**Comment by mick-2006** [comment]
Tbh it would be nice and navel shoulden be on slag makes no sense cuse they would melt

**Comment by WilloIzCitron** [comment]
Yes

**Comment by HaphLife** [comment]
Seems pretty cool tbh.

**Comment by WilloIzCitron** [comment]
oh no
