### ISSUE TITLE
Color label

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1131]
A label that acts like a junction but is just a titanium conveyor belt with a sorter based display but that takes over the block entirely 

The label block will help with schematics by labeling belts that require a specific resource without the label interacting with other labels aka screwing up the entire line if another resource is introduced or mixing the entire line also gives players an opportunity for order and enabling others to fix problems that arrive in the production of resources by simply connecting the belts that has that resource to that label also make it player specific to edit so the player that places can edit while others can't but others can break so its not a nightmare situation for players when a greifer comes. if you could add this will legit praise you because you are an awsome human being

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
You can already do this with normal sorters set to the resource that you need, or if you can't recognize the resources by colour you can use a logic display and processor to show the resources needed.
For example, 
![image](https://user-images.githubusercontent.com/68676339/98718358-58e07300-235c-11eb-8224-27cc2a8e13fb.png)

**Comment by XxsuperdeadlysniperxX** [comment]
I meant as like a custom Conveyor ya know
