### ISSUE TITLE
Curved conveyor emoji for server

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1132]
**Describe the content or mechanics you are proposing.**

Kinda self-explanatory. Please add the curved variants of the regular conveyor emoji's for the people who use them in channels for fun. Also, a conveyor with copper (just copper) would also be cool.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This isn't about the game but more so the discord community. It would give the players a new way to use emoji's

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
it would flood the available emoji slots though

**Comment by the-kido** [comment]
But curved emojis tho :(

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/98725925-c5ab3b80-2363-11eb-8d8f-34786cf81323.png)
8

**Comment by the-kido** [comment]
> If we are not considering both directions a conveyor goes...

**Comment by the-kido** [comment]
There isnt an up conveyor or left conveyor and I don't think there needs to be

**Comment by QmelZ** [comment]
adding left and down conveyors makes more sense than adding curved ones.

**Comment by the-kido** [comment]
he hasnt responded in 24 hours so this is a bust
