### ISSUE TITLE
Set Build Speed Modifier to 0 Disables Building Altogether

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#1133]
**Describe the content or mechanics you are proposing.**
When creating a map or playing a custom game, setting the Build Speed Modifier to zero should be possible, and doing so should disable the construction/deconstruction mechanic for players altogether.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Having this as an option would open up a wide variety of new gameplay possibilities, paving the way for "adventure" style maps where players can interact with, but not change their environment. Possibilities could include puzzle maps requiring skillful manipulation of routers to get items where they're needed, or 'battle royal' style pvp where the focus is on combat rather than infrastructure. There's no negative impact on players who prefer the construction side of Mindustry, as it's still a wholly customizable setting.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
alternatively, you could ban every block

**Comment by Bohaska** [comment]
lol...

**Comment by motaywo** [comment]
> alternatively, you could ban every block

Doesn't stop people from destroying what's already there
