### ISSUE TITLE
Redoing The Command Mechanic, Redux

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1136]
**Describe what you would like changed, and why.**
The command mechanic needs a little reworking. It's currently functional enough, but I personally think it could stand a little improvement still.

**Describe the changes you want to propose. Include possible alternatives.**
First, make it so that units can be added one-by-one into your "command ring". Instead of G binding all units in a certain area, it would make any unit that's hovered over glow like the selection mechanic. Clicking on units while G is held will add them to the ring, and clicking a unit that is in the command ring while G is held will release it from command. 
Second, make it such that units that are commanded cannot be possessed by players.

**Comment by Legomonster33** [comment]
yus
