### ISSUE TITLE
Major Attack Sector Redo

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1137]
Linked with #1135.
  I have been playing campaign for a while and I have a few ideas. This will be a major change to the game if implemented.
  1. Attack sectors become derelict upon capture. #1135.
  2. Captured attack sectors lose their red outline and become normal sectors if lost after being captured.
  3. Randomize attack sectors, with fewer attack sectors. 
  4. Enemy can capture sectors. This means that over time, the crux team can capture sectors and add red hexagons to the map. MAKE SURE THIS DOES NOT OVERWRITE ALREADY CAPTURED SECTORS OF EITHER TEAM.
  5. Remove the current baseparts and let the veteran players handle making baseparts, as the current baseparts are low quality.
  6. Enemy AI does not crash. I have noticed that the enemy AI core unit crashes to the ground. Fix it to simply poof out of existence and deal no damage to structures upon crash like the sharded core units.
  7. Enemy can claim your lost sectors as bases. Upon losing a sector, add a small chance that the enemy can claim the sector as a base and make your life harder.

1. [x] - **Don't worry, I checked the GitHub and Trello and am familliar with the current content of the game.**

yes, you will all hate me for deleting the template but i still stuck the necessary information in. deal with it. 
edit: check mark failed

**Comment by Legomonster33** [comment]
> Enemy can claim your lost sectors as bases. Upon losing a sector, add a small chance that the enemy can claim the sector as a base and make your life harder.

apart from this, which would just be annoying I think most of these are a good idea.

**Comment by Bohaska** [comment]
Good idea, but I want to add my own suggestions
1. After you conquer all research sectors, there will be a harder version of Campaign called Hardcore which will have everything you said on top.

**Comment by BlueWolf3682** [comment]
this isnt hardcore mode, this is to make it so that the enemy is more equal to the player, and also i think it should be a chance due to the ability to capture enemy bases and make them into your bases

**Comment by Bohaska** [comment]
Yea but some people like to play easy stuff, so I propose splitting up the difficulty levels.

**Comment by BlueWolf3682** [comment]
mindustry, but it actually has different campaign difficultes. bruh

**Comment by Bohaska** [comment]
what does bruh mean.

**Comment by BlueWolf3682** [comment]
how about we dont, i wanna see the noobs make continuous issues about the campaign being too hard.

**Comment by Bohaska** [comment]
Thats mean...

**Comment by BlueWolf3682** [comment]
either you will learn to get better at the game or you will eventually quit. either way, you wont be causing veterans as many issues.

**Comment by Legomonster33** [comment]
> either you will learn to get better at the game or you will eventually quit. either way, you wont be causing veterans as many issues.

you strive to get better so that you can play on hardmode

**Comment by Legomonster33** [comment]
then the game aids people in mastering the game

**Comment by Bohaska** [comment]
@BlueWolf3682 You are going to forever split the Mindustry community and widen the gap between veterans and noobs... Unacceptable!

**Comment by BlueWolf3682** [comment]
but why should the game be easy just because someone cant get good at it?

**Comment by Bohaska** [comment]
@BlueWolf3682 It should be easy because some people **haven't** got good at it yet. It is like a transition mode to help you prepare for hardcore mode.

**Comment by BlueWolf3682** [comment]
the old noob playerbase would suffer, but fully new players would take the difficulty as it is and try to defeat the campaign normally. also, this doesnt make the campaign that much harder, it just makes it so that the crux team can act much more like the player.

**Comment by Bohaska** [comment]
@BlueWolf3682 Haven't you realised that if the crux team acts like a player, it becomes more difficult to beat?
