### ISSUE TITLE
Mindustry Hardcore mode (related to #1137)

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1138]
**Describe what you would like changed, and why.**
https://github.com/Anuken/Mindustry-Suggestions/issues/1137 was a great suggestion, but I wanted a slightly different version of it (and the author of it was extremely stubborn)
I want a harder version of Mindustry

**Describe the changes you want to propose. Include possible alternatives.**

After you conquer all research sectors, there will be a harder version of Campaign called Hardcore which will have everything in this suggestion. You can choose whether to make a new save with Hardcore mode or just continue playing.

1. (All modes) Attack sectors become derelict upon capture. Refer to https://github.com/Anuken/Mindustry-Suggestions/issues/1135 for more information.

2. (All modes) Captured attack sectors lose their red outline and become normal sectors if lost after being captured. Taken from https://github.com/Anuken/Mindustry-Suggestions/issues/1137

3. Enemy can capture empty sectors. This means that over time, the crux team can capture sectors and add red hexagons to the map. MAKE SURE THIS DOES NOT OVERWRITE ALREADY CAPTURED SECTORS OF EITHER TEAM. Taken from https://github.com/Anuken/Mindustry-Suggestions/issues/1137

4. Enemy will learn from you (like real AI) and fix its mistakes after periods of time. It will act like a player, it has to make units in bases and launches them to nearby bases. It starts from the sector directly opposite Ground Zero. Expert Mindustry players can help teach AI to do this.

5. After it captures a sector from you, it will take around 40-60 minutes for it to turn into an enemy base (you will be alerted to this if the sector involved is adjacent to you or a research sector you researched) and after 0-20 minutes it will start building structures in the bases (you will also be alerted about this if the sector involved is adjacent to you or a research sector you researched). Partly taken from https://github.com/Anuken/Mindustry-Suggestions/issues/1137

6. When you attack enemy bases in Hardcore Mode, you don't start off with cores. You will need to send units to the area and adjust your waves so that the enemy will lose. You can send T1 and T2 units from the start, you can start sending T3 units at wave 20, you can starts sending T4 units at wave 40, and you can start sending T5 units at wave 100. (the limit will be gradually be reduced as both you and the enemy progress)

This suggestion will also add the ability for Large Launch Pads to launch small units and a new launch pad called the Gigantic Launch Pad which can launch really big units but launches less frequently. (partly related to https://github.com/Anuken/Mindustry-Suggestions/issues/861)

Edit: This suggestion also prohibits you to launch your core to sectors which aren't adjacent to your sectors or have been researched in Hardcore Mode. (Partly related to https://github.com/Anuken/Mindustry-Suggestions/issues/1130)

**Comment by Legomonster33** [comment]
sounds highly epic

**Comment by Bohaska** [comment]
Anyone have any ideas to improve this?

**Comment by userlol2** [comment]
Chill mindustry v6 is hard enough

**Comment by Bohaska** [comment]
@userlol2 I know, but some pros have mastered it, and I expect more and more people to master/get bored of v6 so I am giving them a new option to continue playing.

**Comment by BlueWolf3682** [comment]
i hope you realize how much the playerbase would be split by having different modes, as all veterans would be on hardcore mode and all newer players never able to pass easycore mode. veterans would easily flex their hardcore skill and the veterans would become known as hardcore players, which would make them feel more above the normal base and possibly entirely tear the playerbase apart.

**Comment by Bohaska** [comment]
Stop assuming that you can never go up to Hardcore mode.

**Comment by abowen** [comment]
Personally, give people the option to just start a game on hardcore without having unlocked it.

4. AI that learns from players is extremely difficult to implement, I'd suggest changing this point to something achievable.
e.g. Predefined tactics, such as bulk sending troops, or sending mixed units to attack a single output.
