### ISSUE TITLE
Suggestion reee

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#1139]
So basically for schematics show estimated bulid time based on current unit ur in(or if that's to complicated just normal bulid time lol) also idk why tf uh I don't have the checkmark things so uh yeah

**Comment by QmelZ** [comment]
reee no template

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/98844218-05345f00-241a-11eb-8e56-31df9c9b90b3.png)
How do you miss this what

**Comment by RouterChainsSuckk** [comment]
Idk how its possible to skip it

**Comment by QmelZ** [comment]
you are the one who did though.
