### ISSUE TITLE
[6.0] 5.0 campaign maps planet

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#114]
**Describe the content or mechanics you are proposing.**

A planet with sectors that correspond to the 5.0 campaign maps.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

At the moment old campaign maps will only be playable in sandbox which is sad.
A retro/legacy/forgotten planet could keep these maps (spare desert wastes because it sucks and uses its own class to generate the map)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> At the moment old campaign maps will only be playable in sandbox which is sad.

The old maps are already going to be repurposed into preset sectors in the campaign. A separate planet for them doesn't make any sense.
