### ISSUE TITLE
Tap to remove destruction order on mobile.

### ISSUE THREAD

**Issue by YourCommonBro** [Anuken/Mindustry-Suggestions#1140]
Tap to remove destruction order on mobile.

If you want to delete something on mobile, and you accidentaly select a block you don't want to delete, you either:
a) Have to cancel your plans which sucks if you planned to do a lot of stuff in one go
b) Have to delete the block and rebuild or wait for the deleting process to start and start rebuilding, which still loses resources and is even more painful with unit factories/storage since they lose their held items and factories lose their progress and or held unit, which wastes time

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by QmelZ** [comment]
you can just tap on the block to remove it from breaking plan.
