### ISSUE TITLE
Make sectors use cliffs instead of walls

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1141]
**Describe the content or mechanics you are proposing.**
Make sector generation not use walls, but use cliffs.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make sectors look like actual terrain instead of caves.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by FarmerThanos** [comment]
yes

**Comment by DeltaNedas** [comment]
also, if the elevation is high enough just cap it off with walls e.g. for a mountainside
