### ISSUE TITLE
Access to more sprite enums

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#1144]
**Describe what you would like changed, and why.**
The current system of drawing images currently does not allow subimages, i.e. -liquid, -rotator, and there is no reason why you shouldn't be able to get the Mindustry logo, for example.

**Describe the changes you want to propose. Include possible alternatives.**
Add more enums, each with their respective images. As this may clutter up enum space, it would be good to add the following structure:
```
 content
 - @sprite
   | - @leg
   | - @weapon (may be too far fetched?)
   | - @liquid
   | - @engine
   | - ...
```
...or avoid this mess and add strings to draw such sprites - replacing them with error.png if such a string does not exist

**Comment by DeltaNedas** [comment]
this would require a ridiculous number of variables
having an instruction to get an arbitrary textureregion (hint: mods) would suit it better

**Comment by BasedUser** [comment]
> strings
