### ISSUE TITLE
The whole planet as a server

### ISSUE THREAD

**Issue by blinnchick** [Anuken/Mindustry-Suggestions#1146]
**Describe what you would like changed, and why.**

Anuken, the company is a great way to play with friends, but unfortunately all players are focused on one location and when the host moves to another location, all the players who were on the server are simply thrown into the main menu.

**Describe the changes you want to propose. Include possible alternatives.**

Option 1: All players can be in different locations while still on the server. (Pros: The launch pad becomes more in demand)
Option 2: Move all players with the host to another location. (Pros: Easier to implement)

#Translated by Google translator.#  :3

**Comment by DeltaNedas** [comment]
option 1 is impossible as everything relies on a single Vars and it would be insanely laggy, especially on a phone

**Comment by bsjohnson20** [comment]
This is pretty funny 'company is a great way to play with friends' Also the gamemods would get that boring it isn't worth playing the gamemode.

**Comment by Bohaska** [comment]
This has literally been suggested like a zillion times and all of the problems with this have been pointed out in other versions of this suggestion. This should go in the list of what NOT to suggest ever again.

**Comment by Nhimanss** [comment]
its unfortunate to see
reopen this I got an idea
use a /vote-move system
to allow the players to vote on when to launch and where to go
