### ISSUE TITLE
Launch Pad Global Launching

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1148]
**Describe the content or mechanics you are proposing.**
Have an option for launchpads to attempt to launch to "every" sector, spreading all the launched resource over all of your sectors.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it will make launch pads more useful as instead of having to set a destination you could just tell them to launch everywhere and not have to worry about overfill etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
Realistically it does not make sense

Conceptually it is really nice though
