### ISSUE TITLE
Overflow junction

### ISSUE THREAD

**Issue by savetyle** [Anuken/Mindustry-Suggestions#115]
**Describe the content or mechanics you are proposing.**
A junction that will only allow two streams of items to pass through it as long as 1 set path is full. If the set path is not full no items can pass through the other side of the overflow junction

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
For example this will allow things such as thorium reactors to have a sort of safety
I.E. thorium cannot reach the reactor unless there is an access of titanium for cooling 
This will also enable many other creations to be possible

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
6.0 logic stuff would make this obselete
