### ISSUE TITLE
T2 Water extractor (for all your watery needs)

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1150]
**Describe the content or mechanics you are proposing.**

Water is a literal pain to get in places without it. Water extractors were recently nerfed (which I do enjoy) but I think a tier 2 water extractor should exist. However, I think it would be interesting if it was a 4x4, used ~ 500 power units, and outputted ~30 units of water/sec

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Just for places without water. If you're in a place with no water it becomes annoying to get water. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

I have the memory of a single cell organism.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
Maybe make liquids launchable?

**Comment by scarf-generic** [comment]
> Maybe make liquids launchable?

Doesnt fix multiplayer maps with no water.

**Comment by Legomonster33** [comment]
current watex= 1.5 water per tile per second
t2 watex (from your suggestion) = 1.875 water per tile per second

it would need to be quite a bit better, and use more power

**Comment by genNAowl** [comment]
I feel like any T2 extractor would just encourage the power-from-nothing and sand-to-graphite/silicon schematic spam from 5.0.

**Comment by scarf-generic** [comment]
> current watex= 1.5 water per tile per second
> t2 watex (from your suggestion) = 1.875 water per tile per second
> 
> it would need to be quite a bit better, and use more power

Hmm or just keep it as is but make it not react to the tiles its placed on

**Comment by potatoisagender** [comment]
you could take a map (like ground zero or ruinous shores) and farm the water out of it.

**Comment by Bohaska** [comment]
@the-kido the coding part shouldn't be too hard to implement, but we will need sprites for this

**Comment by the-kido** [comment]
> I feel like any T2 extractor would just encourage the power-from-nothing and sand-to-graphite/silicon schematic spam from 5.0.

Thats more than enough for me
