### ISSUE TITLE
Research Costs and completing the planet

### ISSUE THREAD

**Issue by SarisWinterwisp** [Anuken/Mindustry-Suggestions#1151]
**Describe what you would like changed, and why.**

Change how research works so that it encourages/demands players conquer more sectors and fully utilize them instead of just getting 1-2 good sectors and camping them until the entire tech tree is finished. Once you have everything unlocked you can use launchers and surge to build cyclones and foreshadows to take enemy sectors and snipe the core or build a wall near the spawn points and kill everything that spawns. By slowing progression of the tech tree, and making it so that you have to capture more sectors at a low tech level to progress it will make the campaign more unique, take longer, and leave each map as something that's relatively important rather than just 1-5 sectors that produce everything and you just launch resources from them into the next area. Within my personal play through upon conquering the nuclear production complex I conquered these areas and unlocked 80% of the tech tree. I have less than 90% of the planet conquered but have no need to expand outwards, which hurts the campaign a bit.
![image](https://user-images.githubusercontent.com/73077434/98891128-60824380-2452-11eb-806c-54daaad66f00.png)
Similar games to Mindustry have built in limits that force the player to progress. In Factorio it's very time consuming to produce science by hand, so you have to set up a massive complex to produce it for you in vast quantities instead of slowly waiting for it to be done by hand. In Shapez.io you require massive amounts of each shape you make, so that although you made it one at a time you need to think about and focus on how you make more of it and faster with less space. Similar limitations would be beneficial to Mindustry

**Describe the changes you want to propose. Include possible alternatives.**

There are three methods to go about this:
1. Revert the research costs to what they were at first, but require that the entire cost must be fulfilled at once. Instead of submitting 5k silicon at once, and then another 5k to reach a 10k cost, you have to have 10k total all at once to unlock that specific item. Maybe even require all the resources all at once at max capacity. Instead of just 10k silicon you need 20k titanium at the same time to go with it.
2. Massively increase the research costs so that if you were to squat on one sector you would spend a very long time waiting for it to be issued. I'm talking 100k to 1million in research costs, such that the only way to effectively fill it out is to expand and produce more of the resource.
3. Both of the above. Though I personally think that either of the methods work better than using both of them at once.

**Comment by SarisWinterwisp** [comment]
A lesser note that's also worth talking about: it can feel slow/pointless/tedious to conquer new sectors after completing the tech tree since you can of course just launch resources in over time. The old campaign didn't have this since you wouldn't get a steady flow, only a one time shipment. As is desolate rift, previously the hardest map is now arguably one of the easiest since by the time you get there you can just unload massive amounts of resources. Where you would have lead shortages you can just unload it from your core. But you don't even need lead any more, just unload surge and watch Cyclones go brrr. I'm not sure how one would fix this other than slowing down getting to this phase via research costs. Here's a screenshot of what my desolate rift is, and you can compare it to pre v6 versions where people crowed about getting to wave 1000 
![screenshot-1605151659955](https://user-images.githubusercontent.com/73077434/98891908-05e9e700-2454-11eb-8a32-472d15488c2e.png) https://www.youtube.com/watch?v=HLbKR0CkQI4 (wave 1000 footage. Notice how much more cluttered and busy it is, and thus shows that someone had to process and build all of it over the course of hours. It took me half an hour to build mine)

**Comment by theredstone496** [comment]
For the first method, you can launch resources from the one production sector to other sectors and they only act as storage instead of building production in those sectors. I think the second option is better because it gives the player a choice to wait for a very long time in a sector, or get resources from other sectors.
