### ISSUE TITLE
Unit Transport

### ISSUE THREAD

**Issue by DarkStalker42** [Anuken/Mindustry-Suggestions#1152]
**Describe the content or mechanics you are proposing.**
As the title says, adding a new transportation unit would be nice. It would work where they can transport units from sector to sector, and the higher the tier, the further they can go. Ground units need this to move around, while air units can do it based on tier ( wraith can move one sector, horizon two, and so on). Transportation units can increase travel distance for air units as well.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
>  I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

bruh
