### ISSUE TITLE
Harder campaign sectors

### ISSUE THREAD

**Issue by DayTimer** [Anuken/Mindustry-Suggestions#1155]
**Description of what i would like changed and why.**
As the title says. Difficulty 6 sectors are too easy. Seriously, 40 waves with just 1 T5 and several T4? In the late game it is nothing.

**Description of the changes im purposing. Including possible alternative.**
I would suggest adding some difficulty 8/10 sectors (theу should be rare). Or, as suggested before, a "hardmode" in which all sectors become much more difficult.

---

- [X] I have done a quick search in the list of suggestions.

**Comment by userlol2** [comment]
Maybe one t5 and few t4 is easy to u ,but do u ever think about new players,they will have a long suffer

**Comment by DayTimer** [comment]
someone forces them to launch to a diffuclity 6-10 sector? Why are some people always against hardness? Even if it's optional?

**Comment by BlueWolf3682** [comment]
i have the same question, just get good or suffer
