### ISSUE TITLE
Quality of Life: Better Bridge Conveyor placement

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#1156]
So, basically, I'd like to suggest that clicking and dragging your mouse while placing bridge conveyers would space them out three tiles apart, similar to how power nodes can be placed perfectly far apart, but only in cardinal directions. This would make placing a large amount of bridge conveyors much easier, and should also be applicable to Phase Conveyors, only 15 tiles apart this time.

**Comment by Legomonster33** [comment]
should be the max range of the thing, not just some arbitrary "almost" number
still good idea tho

**Comment by QmelZ** [comment]
i actually made a pull request for this but it didn't get accepted, i might make one again

**Comment by D-player1** [comment]
Anuke already stated that he won't encourage bridge chaining

**Comment by iLagSoUhax** [comment]
wait what

**Comment by Bohaska** [comment]
He wouldn't encourage people to never use conveyors and use bridges.
