### ISSUE TITLE
Mindustry Launcher

### ISSUE THREAD

**Issue by LynxKFM** [Anuken/Mindustry-Suggestions#1157]
**Describe the content or mechanics you are proposing.**
A Mindustry Launcher for PC.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would be nice to have this, because with each new build you need to download a new version from Itch.io.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Itch.io app: Am I a joke to you?
