### ISSUE TITLE
We need a long ranged shotgun like those in the heavy armaments mod

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1158]
Its a shotgun to do more damage to enemies earlier on in the game

This gun will use copper and graph as ammo t1 shotgun is built out of copper t2 out of copper and graph t3 out of copper metaglass and plastanium t4 and t5 out of copper surge metaglass and silicon t1 is a 1x1 block like the duo t2 is 2x2 t3 3x3 t4 5x5 t5 is 7x7 the t5 is the most powerful shotgun with a range that is longer than the ripple but only targets units that are tougher than a titan or what the scortch unit is called t4 targets air and ground but same units that t5 targets t3 targets only air but has elemental bullets with the ability to put out fires with a built in wave t2 air and ground targets all units and t1 air and ground targets all units the shotguns do damage per pellet so like 18 per pellet and the like anuke i swear this will attract players like a magnet if you would add this your a legendary dev

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by userlol2** [comment]
Bruh how could shotgun have long range

**Comment by D-player1** [comment]
Fuse exists

**Comment by DeltaNedas** [comment]
ok use those broken mods

**Comment by Catchears** [comment]
>earlier on in the game

>range that is longer than the ripple

>plastanium

:hmm:


>if you would add this your a legendary dev

that's not gonna work


>Fuse exists

^


>ok use those broken mods

^

Use the fuse, use the foreshadow and consider learning what the following things mean and can be used for:

.

,

!

?

the format

**Comment by scarf-generic** [comment]
How do i close somebody else's suggestion

**Comment by itcannotbe** [comment]
You can't, unless you're the repository maintainer.

**Comment by XxsuperdeadlysniperxX** [comment]
It was a good idea tho because fuses are already existing and there supper cose range and if anuke hasn't looked at it he never will
