### ISSUE TITLE
Small change to camera movement while paused

### ISSUE THREAD

**Issue by Traister101** [Anuken/Mindustry-Suggestions#1159]
When you are paused you can freely move the camera about and I have no issue with this but as a newish player (played classic but v6 is the oldest version besides that) I need to look at the block stats often and I tend to use the question mark since its easy to access. The issue I'm having is it re-centers the camera on your ship which has been frustrating since I then need to pan all the way back to where I was.  

Ideally you'd simply change this as it doesn't seem intentional but a simple toggle key-bind would would fine for me and any others who are frustrated by this

**Comment by Catchears** [comment]
Well the ship isn't supposed to move while the game is paused. Are you suggesting that when you unpause the game that the ship moves to the camera? Or that you can access the block stats while the game is paused? Next time, try sticking to the template.
