### ISSUE TITLE
Make Units less stupid + more unit-related buildings

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#1160]
**Describe the content or mechanics you are proposing.**
Basically, units in the game right now are dumb and need more brainpower, but more things included.

**Make units smart:** Don't make units stray directly into enemy lines. If, for instance, there are four daggers and one quasar near each other, for cat-worship's sake, make the daggers stay near the quasar for safety. Right now, they'll just dazedly stroll into a ripple and die. Strength lies in unity.

**Make command centres useful:**

- Firstly, command centres should have another row of commands for Attacking. This row of commands should be separate from the row of position [rally, idle, attack], and would have two commands, `Fire at Will`, `Fire if Provoked` and `Hold Fire`.
  - Fire at will is the usual firing command; if enemy in sight, shoot them.
  - Hold Fire would be to not fire at all, even if there's an enemy in range. This would be useful for maps with `Units require ammo` rule enabled, where units randomly shooting deserted structure just wastes energy and copper.
  - Fire if provoked is a bit of a stretch, but it makes the units attack at anything which shoots at them first, mostly turrets.

- **More unit-based buildings:** The first that come to mind are airlocks, which units can go through to re-enter payload chains, Healing stations, where damaged units can enter to heal themselves fully [the time taken would be proportional to the amount of health to be healed]

- **Better command centres in general:** A lot of things:
  - the ability to select particular units, or unit types, to do particular chores. Kinda like the logic interface, but much easier. An example: if there are ten allied daggers on the map, clicking on the command centre and then on the ten daggers, like selecting components through a logic processor. Then, clicking on a button [like that used my messages, launch-pads and logic processors] would open an interface where units could be sorted into different 'guards'. For this example, put half the daggers in guard 1 and commend them to attack, and put the other half in guard 2 and command them to defend. This way, for example, half the daggers could attack the enemy base while five stand by for defence. Command centres could also link with each other to command them to 'patrol' between the two, or more, command centres [of course, command centres are expensive, so this will be fairly balanced.]

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
>Better command centres in general: A lot of things:

>the ability to select particular units, or unit types, to do particular chores. Kinda like the logic interface, but much easier. An example: if there are ten allied daggers on the map, clicking on the command centre and then on the ten daggers, like selecting components through a logic processor. Then, clicking on a button [like that used my messages, launch-pads and logic processors] would open an interface where units could be sorted into different 'guards'. For this example, put half the daggers in guard 1 and commend them to attack, and put the other half in guard 2 and command them to defend. This way, for example, half the daggers could attack the enemy base while five stand by for defence. Command centres could also link with each other to command them to 'patrol' between the two, or more, command centres [of course, command centres are expensive, so this will be fairly balanced.]

I'm pretty sure that's why unit logic was added,

>Healing stations, where damaged units can enter to heal themselves fully

What happened to repair points?

**Comment by iLagSoUhax** [comment]
1. Unit logic is difficult and can't be used by everyone.
2. Repair points need to be spammed in order to heal larger units, which wastes time and space

**Comment by Bohaska** [comment]
Maybe only add this for enemy AI, but not for players since unit logic exists.

**Comment by mwoehlke** [comment]
If you're going to use "use Logic" as an excuse, how about explaining *how*? The Logic system is pretty inscrutable right now. (I'm not even sure it's entirely *working*; I can't get `move` to work for anything other than a hard-coded X/Y.)

**Comment by itcannotbe** [comment]
RTFSC.

**Comment by marek22k** [comment]
Hi, I'm currently playing Mindustry and need to capture an enemy base with crawlers and daggers. How can I get the units to do this? Currently they are just standing around. When I tried to use a microprocessor, they did a lot of things, but not what they were supposed to do.
Has this suggestion been implemented so that I can have the units attack without weird logic?
