### ISSUE TITLE
Give Custom Maps the Option of a Day-Night Cycle Rule

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#1162]
**Describe the content or mechanics you are proposing.**
Custom maps should have the option of a day-night cycle rule, to bring it more in line with the campaign mode. The duration of the day/night could possibly be configurable, but that's not necessarily required.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, it's impossible to give maps a dynamic light level, meaning they're either locked in a perpetual state of light, dark, or somewhere in between. Allowing creators to enable a day-night cycle if they choose would give them far more leeway to be creative.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by HaphLife** [comment]
Sounds like a good idea to me. Do you think it should be customizable (like how long a day is, and what peak light and minimum light are)?

**Comment by motaywo** [comment]
Absolutely - I'm always in favour of more customizability, but since I don't know how difficult it would be to transfer the code from campaign maps to custom maps, I figured I'd keep my expectations low to start
