### ISSUE TITLE
Allow Cliff Tile Data to be Interpreted from an Image Import

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#1165]
**Describe the content or mechanics you are proposing.**
Cliff tile data should be imported and exported in a map image file, within the Blue (or red, or green) colour channel. By assigning cliffs a specific R and G value, but leaving the B channel open, all of the cliff tile data can be stored without interfering with the standard colourmapping of all other blocks.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, cliffs can only be added and modified through the use of scripts or code, which limits their availability to people with the programming knowledge to do so. By also allowing cliffs to be edited "_in photo_", would give advanced mappers who lack programming experience the chance to include cliffs in their maps. By taking the data directly from the image import/export, it eliminates the need for a complicated algorithm to generate orientations, because the data is provided by the image. Furthermore, by adding it to the image import/export only, it also removes any need for a clunky interface within the editor, and maintains the current limitations of cliffs only being used by those that know how to use them well.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Ruichka** [comment]
Image import exists for backwards compatibility, not for making maps using Paint. Also, to unlock cliffs all you need is to download a single mod (DeltaNedas/cliff).

**Comment by itcannotbe** [comment]
Image import is actually called legacy map import.

Emphasis on ***LEGACY***
because that's how we saved maps in v3 or as people know it now as classic (and it is still downloadble as classic)

**Comment by motaywo** [comment]
Feel like I ought to point out that in V6, the image importing function was renamed from "Legacy Map Import" as you kindly mentioned, to "Import Image File". Furthermore, Anuke re-introduced the ability to export map terrain as an image file, and changed many colourmappings to accommodate blocks added in V6, meaning backwards compatibility isn't exactly the primary focus anymore. 

DeltaNedas' cliff mod only provides one specific facing algorithm, that does not work well with walls not to be converted to cliffs. All other modifications to cliff faces have to be done manually through the JS console, which is accessed through his devmode mod. Letting the importer translate colour to tile data would change exactly nothing for people who don't care for it, but make a huge difference for mappers.
