### ISSUE TITLE
Add a way to unbind units with logic

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1166]
**Describe the content or mechanics you are proposing.**
Similar to unit bind, add a unit unbind command for logic.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
There is not a reliable way to quickly unbind a unit with logic, this would fix that. Pretty simple qol idea, im guessing it would not be too complex to add to the game but please correct me if i am wrong. Maybe add a way to unbind units with a specifc flag or something. Thanks for reading.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
> I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

binding a new units unbinds the old one.

**Comment by sample-text-here** [comment]
> binding a new units unbinds the old one.

then you have a new unit that you have to unbind and how do you do it then

**Comment by QmelZ** [comment]
> > binding a new units unbinds the old one.
> 
> then you have a new unit that you have to unbind and how do you do it then

just bind a gamma or something, you can't spawn gammas that can be bound

**Comment by scarf-generic** [comment]
> > > binding a new units unbinds the old one.
> > 
> > 
> > then you have a new unit that you have to unbind and how do you do it then
> 
> just bind a gamma or something, you can't spawn gammas that can be bound

While this is true, it can be cofusing for someone unfamiliar with the game. An unbind command would fix this.

**Comment by DeltaNedas** [comment]
you already can:
- implictly, just do nothing to the unit for a few seconds
- `unbind` from deltanedas/anuke-logic best mod
