### ISSUE TITLE
bosses for champion

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#1168]
**Describe the content or mechanics you are proposing.**
Well i suggest to add a few t3 t4 t5 type bosses into champion,they are unbuildable (only can summoned in waves) and they are more powerful than other units with the same tier.

To make sure players will fight them,players must defeat them to unlock other sectors.(maybe with medals

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think it gives more reasons to complete champion( just an idea

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
If the champion is a status/buff for any unit, then we have the guardian/boss title which makes units marked as a guardian stronger.
If the champion is a separate unit, then there's not enough information.
There is no need to unlock sectors with medals. It's an open world.
