### ISSUE TITLE
Liquid missile turret

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1172]
**Describe the content or mechanics you are proposing.**
A new end-game liquid turret called the Splash which shoots liquid missiles at enemies. Upon explosion, said liquid will splash everywhere.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More liquid turrets would be good, so that liquids will have more use in the game

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. I did suggest a variation of it before, but it was a little different...
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. 
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
anuke will not be adding any more turrets.
read README.md

**Comment by the-kido** [comment]
no turret more until not now
