### ISSUE TITLE
Heavily nerf overdrive projector and dome

### ISSUE THREAD

**Issue by Zagrox11** [Anuken/Mindustry-Suggestions#1173]
**Describe what you would like changed, and why.**
Overdrive projectors and domes are too overpowered currently. They are easy to use, they are not so expensive and the effect they provide is just too strong. Instead of building more power generators, factories or turrets, the player can just place a projector and solve most of the problems. This is not interesting and I think this is not how game should work. Overdrive projectors/domes should act more as a helping tool and not as the thing that can solve all the problems the moment you place it.

**Describe the changes you want to propose. Include possible alternatives.**
I suggest reducing projector's speed boost to around 120% without phase and 160% with phase. Dome should provide around 180%. Their phase and silicon consumption could also be increased up to twice the current usage.

**Comment by D-player1** [comment]
Do you know how slow phase is made? Also, overdrive consumes power, and not only they consume power, all building in their range also need more power, they can mess up ratios.
Overdrive is helpful when you know how to use it, if you place an overdrive to power only 1 generator, it will consume more power instead. Also, overdrive need plastanium, and plastanium isn't easy to get because you need oil extractor that can't be placed anywhere now, and using spore to oil is too inefficient, except of course, if you have an oil patch that most maps don't have, and Overdrive dome needs surge, gathering 4 materials to one isn't an easy job except if you have more than one core, they also consume more energy, all the building in their range consume more than twice the power, this sometimes can cause power to fail and mess up your gameplay.

**Comment by Zagrox11** [comment]
Well, of coarse projectors increase power usage of other buildings, but the thing is it also increases power generator's efficiency. It just feels weird to see the power jumping from -200 to 1000 after placing a projector near steam gen setup. It is too overpowered. Plastanium isn't really hard to get. Spores may be inefficient, but you need only 30 plast to build a projector and it can be easily done using spores. Also, only one fully working phase weaver can supply up to 3 projectors, and this gives you more then double speed boost.

**Comment by scarf-generic** [comment]
> Well, of coarse projectors increase power usage of other buildings, but the thing is it also increases power generator's efficiency. 

Hmm, thats rough. You do realize that overdrive can actually fail your power if you dont know what you are doing?

> Plastanium isn't really hard to get. Spores may be inefficient, but you need only 30 plast to build a projector and it can be easily done using spores. Also, only one fully working phase weaver can supply up to 3 projectors, and this gives you more then double speed boost.

So, you are saying that its easy to get a phased overdrive? You need a good supply of sand (which could be used for other things), you need thorium (the ore that is found latest in the game), and you need plastanium (made from titanium which is a midgame resource and oil which reauires a large amount of power or more sand tiles to produce). For something that does not cost surge, its one of the most complex things to make.

**Comment by itcannotbe** [comment]
To be honest, there is nothing negative when using overdrives.

The only penalty is just the power and items you would use to run the actual overdrive.

That's how overpowered it is.

**Comment by itcannotbe** [comment]
And you might be thinking "but it increases power usage and resource consumption"

Yes, yes it does, but did you consider for you to produce and consume the same without the aid of an overdrive, you'll have to build more, thus using more space.

So no, using more resources and power is not a drawback of overdrives.

**Comment by itcannotbe** [comment]
Also the reasom why power cubes were overpowered on v5 because their designed rely on making more power using overdrive. And the additional power made with their aid is actually substantial.
