### ISSUE TITLE
delete history of mindustry

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1174]
**Describe what you would like changed, and why.**

Mindustry takes far too long to clone.
It's about 2GB right now.
Not all us have terabit internet and nasa supercomputers you know.

**Describe the changes you want to propose. Include possible alternatives.**

Rename the repo and start fresh to make cloning momentary.

**Comment by sk7725** [comment]
~~then dont clone~~

**Comment by summetdev** [comment]
--depth 1

**Comment by BlueWolf3682** [comment]
suffer

**Comment by Bohaska** [comment]
Misleading title...

**Comment by DeltaNedas** [comment]
@summetdev yes but what if i want to merge or push
then i have to download the 2gb anyways

**Comment by sk7725** [comment]
...This issue should be directed at Github and not Anuke. Github should not force you to do that and have a more efficient way of dealing with irrelevant history.

Also no delet nooooooo...

**Comment by DeltaNedas** [comment]
it would be renamed not deleted

**Comment by vgaming** [comment]
@DeltaNedas does it make sense for you to change the title to something like `Squash Mindustry git history to reduce its size` ?

**Comment by ritzip** [comment]
> --depth 1

no
