### ISSUE TITLE
Buff solar panels. The big one and the small one.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1175]
**Describe what you would like changed, and why.**

 Everyone in the discord agrees no one uses them. They are expensive and they make like, 3.6 energy units? Even if it makes energy from _thin air_ so do factories such as spore --> oil --> coal --> Energy. The panels _need_ a buff. The big ones are even worse because it needs phase which is an end game item. 

**Describe the changes you want to propose. Include possible alternatives.**

Make the small solar panels make ~15-20 energy per panel and the 3x3 ones 175-200 energy per panel (considering there is night and day). Compared to something like a steam generator, the steam gen would be about 10x more effective per tile. But, with the old small solar panel, the steam generator would be **_40_** times more effective per tile. I think this is fair enough of a change.

**Comment by scarf-generic** [comment]
Spore power got nerfed into the ground. Small solar panels have higher ppt than any spore power schematic.

**Comment by the-kido** [comment]
> Spore power got nerfed into the ground. Small solar panels have higher ppt than any spore power schematic.

Spore to oil is what I was talking about. Im pretty sure that actually got _buffed_ acually.

**Comment by DeltaNedas** [comment]
solar makes 4.2/s

**Comment by DeltaNedas** [comment]
steam requires coal and water
solar requires jack shit
thats why its useless without covering the entire map
use solars to coldstart rtg

**Comment by itcannotbe** [comment]
Why not a weather that buff solar's production by a lot but it doesn't last long?

**Comment by Bohaska** [comment]
@itcannotbe Or an affinity like sand (desert) which boosts production?

**Comment by scarf-generic** [comment]
> > Spore power got nerfed into the ground. Small solar panels have higher ppt than any spore power schematic.
> 
> Spore to oil is what I was talking about. Im pretty sure that actually got _buffed_.

Hm yes talking about spore oil.

> spore --> oil --> coal --> Energy

**Comment by scarf-generic** [comment]
Care to explain what creating oil has to do with ppt of solar panels?

**Comment by Bohaska** [comment]
@the-kido Some people are too lazy to make mods for this purpose... and are too lazy to ask other people to do it for them...

**Comment by the-kido** [comment]
cleaning up open issues doo doo doo
