### ISSUE TITLE
Change working of Rally command in command centres

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#1177]
**Describe what you would like changed, and why.**
Make command centre 'rally' command specific to the command centre.

**Describe the changes you want to propose. Include possible alternatives.**
Right now, using the 'rally' command will rally units to their nearest command centres. This can prove a problem if and when there are multiple command centres, which would separate the units. Hence, I propose that the rally command should be specific to the command centre, and not common to all command centres.

**Comment by DayTimer** [comment]
But what about maps with 2-3-4 frontlines? Having multiple rally points is very useful sometimes.
