### ISSUE TITLE
Make unit build return a value when it is done building

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1178]
**Describe the content or mechanics you are proposing.**
This is logic related, apparently some people did not get that. As in the title. When building something with a unit, make it return a value when the building is finished. I realize that there are ways of doing this already, but making it return a value when it is finished building is much simpler.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would simplify things and make unit building more streamlined.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
1. Unit cap isn't tied to the building in v6.
2. How do you even use that value when it starts building the next one as soon as the pevious one leaves.

**Comment by scarf-generic** [comment]
> 1. Unit cap isn't tied to the building in v6.
> 2. How do you even use that value when it starts building the next one as soon as the pevious one leaves.

I think you are missing something.
I never mentioned unit cap, nor did i intend to.
This suggestion is about logic controlled units building something.

**Comment by scarf-generic** [comment]
Having it built into unit build is not the best way to do this.
