### ISSUE TITLE
some old fashioned choosing the difficulty of the campaign

### ISSUE THREAD

**Issue by dakosm32** [Anuken/Mindustry-Suggestions#1179]
**Describe the content or mechanics you are proposing.**
Choosing the difficulty of the campaign

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this will help a lot with first time players who get though the first level but cant get though any others because of those annoying flamethrower bots. it would really improve the game not only in player base but also if anybody wants to speed run, lets mindustry. but have only 1 difficulty. they would have a hard time and would rather do something else. BUT if mindustry had a choosing difficulty before a campaign it would attract speed runners and also a larger fanbase.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by dakosm32** [comment]
yes. I know this. but I was talking about before the release the new update. as i have been playing the beta and testing it. going form very easy to very hard is kinda annoying and I just don't feel like that's something a game dev shouldn't do. and 2. the most recent update that isn't the beta has a campaign. but very different to the one we know in the beta. I play on mobile btw.

**Comment by BlueWolf3682** [comment]
sUrE, ThIs Is So HaRd AnD aNnOyInG, pLeAsE mAkE eAsY
![423C7C56-A94C-43F3-A7F0-90BB27A4A693](https://user-images.githubusercontent.com/61173114/99131023-3c983c80-25cf-11eb-87bb-29dea1b7a9bd.png)

**Comment by Bohaska** [comment]
- [ ] You haven't checked the list of suggestions to see if this suggestion hasn't been suggested yet.

**Comment by dakosm32** [comment]
i giving a more like. yeah hardcore. but also casual or hard or medium or something like that... also bluewolf, I'm talking about the levels themselves. not the world map silly...
