### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by owocowyyy** [Anuken/Mindustry-Suggestions#118]
Hi, can you are youtuber/youtuber-miniq rang?

Like

Youtuber- 300 Sub, 8 Mindustry videos.
Youtuber-mini- 3 Mindustry videos.

 1 video minimum 5 minutes

**Comment by potatoisagender** [comment]
What

**Comment by DeltaNedas** [comment]
zacbytes doesnt deserve any more roles for his 3 alts
