### ISSUE TITLE
%built function for getblock

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1180]
**Describe the content or mechanics you are proposing.**
A function for getblock to sense how much a building is built.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Allow getblock to sense how built a tile is. For example, this scatter is about 60% built, so getblock on this scatter would return a value around 60.
![20201113_123608](https://user-images.githubusercontent.com/69741577/99108527-195c9580-25ad-11eb-85a8-9a5890937195.jpg)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Legomonster33** [comment]
yis
