### ISSUE TITLE
When a unit is tarred and is then hit with slag, they should burn into a raging fire

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1181]
**Describe the content or mechanics you are proposing.**
In mindustry, when tar is struck with slag, it will start a massive fire. This should be the same in combat. When a tarred unit is on fire, they should burst into a big massive fireball. Dealing heavy damage of around 150/second. This would make the tsunami more usefull in combat

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be a cool addition, making a turret useless in battle when not accompanied by another.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by userlol2** [comment]
Dude,150 damage persecond by two turret only cost lead and metalglass?

**Comment by Bohaska** [comment]
I thought slag was incendiary...
