### ISSUE TITLE
vr

### ISSUE THREAD

**Issue by bishbosh69420** [Anuken/Mindustry-Suggestions#1182]
**Describe the content or mechanics you are proposing.**

It will get turned down but eventually mindusrty in vr maybe?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

well it would be hella cool for starters but it would probably make you vomit from the amount of movement but also imagine taking over a T5 bomber in vr and bombing your enemies untill they're dead

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Catchears** [comment]
I don't think that this is really an option at all right now, as  Mindustry is 2d and 2d VR makes no sense.

**Comment by Bohaska** [comment]
@bishbosh69420 wait for a 3D mindustry. Also, I'm pretty sure you didn't check in the list of suggestions to make sure that this has not been suggested yet.

**Comment by bishbosh69420** [comment]
> @bishbosh69420 wait for a 3D mindustry. Also, I'm pretty sure you didn't check in the list of suggestions to make sure that this has not been suggested yet.

no I didn't because it's such a stupid idea I didn't think anyone would of suggested it

**Comment by Bohaska** [comment]
@bishbosh69420 If it is stupid, then don't suggest it.

**Comment by GlennFolker** [comment]
Close this

**Comment by userlol2** [comment]
Bruh how can 2D game turn into vr,or u just think turn a game into vr is easy as how u lose ur braincells

**Comment by Bohaska** [comment]
Turning this into 3D is already near impossible, let alone VR. VR isn't mainstream yet, Anuke can wait a few years if he really wants VR in his game.

**Comment by DeltaNedas** [comment]
mindustry is a 2d game you buffoon

**Comment by userlol2** [comment]
Let me tell u something, mindustry is an indie game not made by some company,its hard to turn 2D game into 3D with few peoples' power,and then,turn a game into 3D sometimes dont make the game better or even worst,mindustry is not suitable for a 3D version.

**Comment by bishbosh69420** [comment]
y'all are taken this too seriously, if it was turned into vr it would be more of a joke than anything and it would also be pretty cool to have some depth in mindusrty

**Comment by DarkBrick** [comment]
Why is this even a suggestion
