### ISSUE TITLE
Global Constants

### ISSUE THREAD

**Issue by MukulK98S** [Anuken/Mindustry-Suggestions#1183]
**Describe the content or mechanics you are proposing.**
Global constants for logic makes code more readable

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
example : 
in a scenario where water tank is full or not plays an important role in logic processing, lets say
> jump 5 lessThan currentWater 1500  

1500 is max liquid tank capacity instead we can write something like @MAX_LiquidTank
> jump 5 lessThan currentWater @MAX_LiquidTank  

so it's apparent that when we write 1500, we mean liquid tank capacity
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
This would make mods easier to work with because say a modder changes the max-liquid-capacity of a vanilla tank you have to hardcode in new values into all of your processors. It's not needed since you can hardcode the values yourself, but it's nice to have so you don't have to lookup the values of all of the variables of different blocks.

**Comment by sample-text-here** [comment]
`@liquidCapacity`

**Comment by DeltaNedas** [comment]
sense @liquidCapacity in @liquid-tank

**Comment by MukulK98S** [comment]
> 
> 
> sense @liquidCapacity in @liquid-tank
this is messy because you need to do this in every processor, adding a seperate line(s) adding to clutter, not to mention it's just not about one liquid tank, I am talking about all similar cases (container, vault and so on).

**Comment by Nhimanss** [comment]
@MukulK98S  a clutter cleaning proposal was made in #1219 
this may be a good compromise

**Comment by MukulK98S** [comment]
> 
> 
> @MukulK98S a clutter cleaning proposal was made in #1219
> this may be a good compromise

nesting saves code from clutter, while that may be objective of #1219, my thread has a separate objective, nesting does not declare global constants without adding extra lines of code in every separate processor. Also, adding global constants feature might be wrapped up in a day's work while nesting feature needs adding/redesigning of the whole UI, I think for any scripting like programming such constants are very important both to save from clutter and processing power.

**Comment by DeltaNedas** [comment]
use higher level languages
