### ISSUE TITLE
AI camping 

### ISSUE THREAD

**Issue by dragonhunt98** [Anuken/Mindustry-Suggestions#1184]
Its annoying when ai camp at your defense its almost impossible to passed the level becuse the AI can build anything and expand to your base which is impossible if you don't have any resources left becuse the AI defend it

**Comment by GlennFolker** [comment]
I woner what people thinks when they just short-mindedly _deleted_ the issue template before they submit an issue.
<br>
Close this please

**Comment by GlennFolker** [comment]
And worse, all people that delete the template are mostly the ones who are terrible at english

**Comment by scarf-generic** [comment]
> And worse, all people that delete the template are mostly the ones who are terrible at english

You cant really blame someone for not speaking english or being too young to speak english

**Comment by UltraBlackLinux** [comment]
True, but the issue-template deleting is actually dumb

**Comment by Bohaska** [comment]
You can use translator to translate templates...
