### ISSUE TITLE
Have Monos Circle Around The Ore Tile They Are Mining

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1186]
**Describe the content or mechanics you are proposing.**
similarly to how phantom builder drones used to in v5 have monos circle the ore they are mining.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
would make monos more visibly interesting instead of just having them all in a big clump.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RogueRedHawk** [comment]
Speaking of, why don't polys circle while building? That was actually a pretty cool feature in my opinion.

Related though, this might be bad because it would cause some cases where the ore is near the core but just far enough away to where a circling drone would be able to put it directly into the core in some spots and have to pick it up in others.

**Comment by itcannotbe** [comment]
> Related though, this might be bad because it would cause some cases where the ore is near the core but just far enough away to where a circling drone would be able to put it directly into the core in some spots and have to pick it up in others.

Doesn't anuke want to remove that behavior that allows unit to just mine one ore tile next to the core?

**Comment by Legomonster33** [comment]
> Doesn't anuke want to remove that behavior that allows unit to just mine one ore tile next to the core?

at one point he said how he wanted monos to be more interesting, (after he reverted the single tile mining). this might help to do that.
