### ISSUE TITLE
Have Research Require The *Entire Cost* to Be Fulfilled in order to research

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1187]
**Describe the content or mechanics you are proposing.**
Have it so you can only research something if you have every material required for the whole cost.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
"forces" players to explore maps to have enough storage for researching things. (play the game)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
kindof but was part of a larger suggestion.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
> afk

**Comment by itcannotbe** [comment]
Wasn't partial researching had been just added in v6?

**Comment by BlueWolf3682** [comment]
**partial research was only recently implemented into mindustry, why are you making an issue about it already?**

**Comment by Bohaska** [comment]
@Legomonster33 Same thing for all your other suggestions. Just make a mod for it or ask someone else to do it for you.

**Comment by Legomonster33** [comment]
> @Legomonster33 Same thing for all your other suggestions. Just make a mod for it or ask someone else to do it for you.

that defeats the whole point of the suggestion, i suggest because i think it would fit into the base game. not as a mod.

**Comment by Legomonster33** [comment]
> **partial research was only recently implemented into mindustry, why are you making an issue about it already?**

because it fits in with the new item storage mechanics
