### ISSUE TITLE
Discord: Bugs Info Channel

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry-Suggestions#1188]
**Describe the content or mechanics you are proposing.**
Split #github into two channels: #github and #bugs;  All issues from the Mindustry repository will go to #bugs, and other events to #github.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Cleaner #github channel.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
@summetdev The issues from the Mindustry repository goes in #github, and the suggestions of in #suggestions

**Comment by summetdev** [comment]
@Bohaska yes, I know. I want **new** channel with issues from **Mindustry** repo.

**Comment by Esnardo** [comment]
I don't think that's possible using mee6

**Comment by summetdev** [comment]
@Esnardo in GitHub webhooks you can specify which events will be delivered.
