### ISSUE TITLE
Logic: Delay Block

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#1189]
**Describe the content or mechanics you are proposing.**
I pretty much need a block to delay certain activities, e.g. when I want to display multiple informations in one line but make it so slow, that I can still read it or something like that.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's just a very useful block, that weirdly enough isn't in the game yet.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ilya246** [comment]
you can do that in logic already, just use @time

**Comment by UltraBlackLinux** [comment]
hm, but i's somewhat complicated and annoying. Also takes up space all the time

**Comment by itcannotbe** [comment]
Space? What the hell are you talking about?

**Comment by UltraBlackLinux** [comment]
I will close this, @Ilya246 you are right, but I will make a seperate issue building on this.
