### ISSUE TITLE
Easier playing multiplayer 

### ISSUE THREAD

**Issue by owocowyyy** [Anuken/Mindustry-Suggestions#119]
Hi anuke, 
I have idea, 
New option: 
You play Lan and with code
Like  u click HOST GAME and everyone in same wifi join and host + you got code and u can say/send to friend, when he click JOIN GAME (in lobby) he can type it and join game like max 5 players or more

Good idea?
I think you will respect it

**Comment by potatoisagender** [comment]
did you know, that you can easily set up your own server, assuming you are on pc?

**Comment by DeltaNedas** [comment]
if you are on lan why is this needed

**Comment by owocowyyy** [comment]
> did you know, that you can easily set up your own server, assuming you are on pc?

Im mobile

**Comment by itcannotbe** [comment]
> > did you know, that you can easily set up your own server, assuming you are on pc?
> 
> Im mobile

Did you know you just have press host while in game to create a multiplayer session that's accessible if other players are on the same wifi?

Also the game has a feature that will detect if there is a someone hosting in the same wifi you are connected too.

**Comment by Anuken** [comment]
This is already in the game.
