### ISSUE TITLE
Define Code Blocks

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#1191]
**Describe the content or mechanics you are proposing.**
![example](https://user-images.githubusercontent.com/62404294/99146673-999cfc80-267a-11eb-8233-7c21d563ab14.png)
I hope you understand my suggestion via the screenshot

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
What I forgot: There should also be a way to input stuff into the def brackets.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
It makes code easier to read because you don't need chunks of code hannging around somewhere in the middle, you can just define the code in the beginning and read from it from everywhere via the sensor block.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Catchears** [comment]
>I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

 Pressing `x` to doubt, see 889

**Comment by UltraBlackLinux** [comment]
I searched, and found nothing

**Comment by DeltaNedas** [comment]
this is a duplicate just close it

**Comment by Legomonster33** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

this is very correct indeed mm yes,
oh wait, you can do this already.

**Comment by Catchears** [comment]
And how would you do that?
