### ISSUE TITLE
The ability to change teams in sandbox

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1194]
**Describe what you would like changed, and why.**
If there are multiple cores in a sandbox world, you can change teams. This would be usefull for me to bugfix my maps. You could also turn this off in settings if you dont like it.

**Describe the changes you want to propose. Include possible alternatives.**
Add a change team panel in sandbox like how there is in map editor in-game. I cannot see any possible alternatives.

**Comment by sample-text-here** [comment]
first this is a feature request

second this is already on the [trello](https://trello.com/c/1v40jFbL/708-sandbox-menu)

**Comment by Nhimanss** [comment]
glad to see this coming to mindustry! it needs it
