### ISSUE TITLE
Minke is too OP

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1195]
**Describe what you would like changed, and why.**
Nerf Minke incendiary bullets

**Describe the changes you want to propose. Include possible alternatives.**
Minke's incendiary gun is too op, it can burn anything in like 50+ tile radius. I am abusing it quite a lot in pvp by dropping them on enemies with megas. They should shoot similar to fortresses so the walls can stop bullets from reaching important building this easy

Last time I played in pvp... You can see how powerful they are. We won that round just by dropping those.

![screenshot-1605362980297](https://user-images.githubusercontent.com/40753025/99149088-05905c80-269d-11eb-98bd-d93a28ce089a.png)

**Comment by Slava0135** [comment]
You just need to land a couple of shots to make everything burn...

**Comment by D-player1** [comment]
Or just make it a regular artilery bullet but can still get over walls

**Comment by Slava0135** [comment]
![20201114181313_1](https://user-images.githubusercontent.com/40753025/99151101-e815bf80-26a9-11eb-9352-29fdcd17c013.jpg)
have just won another game... by destroying all teams with minkes mostly
