### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by 5382Ander2** [Anuken/Mindustry-Suggestions#1196]
**I would like if you add support naval units, and possibly crawler air**, *and more...*

Things I placed in **bolded** I like the most, things that are *italic* would be just a good thing to have

**Support naval** could be able to pick up units and deploy them on ground, and they could act as aircraft carriers.

You could possibly add upgraded version of *cultivator* and *spore press*
You could add upgraded *pyratite mixer* and *blast mixer*; better **plastanium compressor and phase weaver**

**Configurable command centers, option to select which units are controlled by it, and an extra option for moving to a selected point** would be a great thing!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
> 1. * [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

lies. also why kill the template? its there for a reason.

**Comment by genNAowl** [comment]
> support naval units

Suggested many times already

> crawler air

Bruh what

> better spore press

Spore press's are already pretty good; Any better version would just further encourage power cube spam

> better plastanium compressor

Already a PR: https://github.com/Anuken/Mindustry/pull/2800

> better phase weaver

See https://github.com/Anuken/Mindustry/pull/2836 for why this is a bad idea

**Comment by 5382Ander2** [comment]
I have done a **QUICK** search in the list of suggestions to make sure this has not been suggested yet.
I done a quick search, but I did not read all suggestions

**Comment by 5382Ander2** [comment]
And why not support naval

**Comment by 5382Ander2** [comment]
And what is wrong with crawler air

**Comment by 5382Ander2** [comment]
Does anyone know what version of mindustry had 2 draug drones from one factory

**Comment by 5382Ander2** [comment]
> Crawler Air
I want this, flying bombs would be a nice addition to the game

**Comment by genNAowl** [comment]
Very well. I shall clarify further. 
> Naval support
![naval support](https://user-images.githubusercontent.com/68400583/99450746-0829c680-28d6-11eb-9fe7-6fe4aa8923e7.gif)
See how many people have made naval support suggestions? How did you miss that?

> Crawler air
Is there a good reason to create another entire air type just for this one unit?
You'll notice that every tier-1 unit (crawler, flare, dagger, nova, risso, mono) each have 5 tiers. Adding a flying crawler would also add the need for 4 other tiers of this unit, which is not acceptable.

**Comment by 5382Ander2** [comment]
Naval support, I am probably blind;

I wanted to add 5 tiers of crawler air units
First is unguided and often misses its target
Second is guided
Third is a flying fortress that fires bullets from its sides (explodes after being destroyed)
Fourth is a larger flying fortress that fires bullets and bombs
Fifth is the largest of them all. It fires bullets only, but it can also explode like a nuke

**Comment by 5382Ander2** [comment]
I see, but if everyone wants support naval, then you should add it, crawler air too pls, I saw someone suggesting crawler naval too, it would be nice to have all three unit types for air, ground and naval

**Comment by 5382Ander2** [comment]
Pay attention please

**Comment by genNAowl** [comment]
If you want me to make a PR implementing this I won't because:
1. I'm lazy
2. Content PRs usually are not accepted, especially since 6.0 will be released soon

I mean, Anuke didn't implement naval support even after seeing the amount of naval support suggestions, so I don't think I will either. 

You can ask other contributors to try implementing this though (I'm not a very good one, my name isn't even in `contributing.md`).

**Comment by 5382Ander2** [comment]
Contributors, pls read this

**Comment by 5382Ander2** [comment]
Anuken is working a lot, can you add support naval to the game
