### ISSUE TITLE
Seperators and cryo/water

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1198]
**Describe the content or mechanics you are proposing.**

So I was thinking, slag is hot and it has lots of metals and the separator separates the metals from the slag. However, the metals are cold and the slag is hot so shouldn't it need coolant to make the recourses solid/make it happen faster?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Make separators use water or cryo as a booster - I don't think many people will like the idea of making it _need_ cryo/water.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

ye

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Honestly though, nobody likes the idea of a building that takes inputs for more than one liquid, no matter how intuitive the idea is.

**Comment by wenzmen** [comment]
Not really, i like this idea.

**Comment by the-kido** [comment]
the gods have spoken and they said "no"
