### ISSUE TITLE
add various buttons for mobile

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#120]
**Describe the content or mechanics you are proposing.**

On-screen buttons for console, map screenshot, etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A keyboard is required to press P, F8, etc. which have no buttons. Adding, and perhaps gating behind "advanced input" setting, buttons for these actions would help people out as lots want screenshotting, fewer but still some the console for easy debugging of mods.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by tiktaktekno** [comment]
yes

**Comment by DeltaNedas** [comment]
ui lib
