### ISSUE TITLE
Toggle the mobile auto-fire system for PC

### ISSUE THREAD

**Issue by RedNova25** [Anuken/Mindustry-Suggestions#1200]
There should be a way to key-bind a button that switches between the mobile version's auto-fire and auto-target and then the PC's default aiming and shooting system. When using a mech that is meant to be a heavy hitter, this will make it easier to hit the targets consistently. I don't know how difficult this would be, but you could also make it so that in the auto-fire mode you click on the unit you want to target.

Thanks for reading

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
im going to warn you that it is a mixed blessing, and usually i play on mobile without an autotarget.

**Comment by DeltaNedas** [comment]
1. use the template
2. git gud

**Comment by RedNova888** [comment]
I thought I used the template correctly

**Comment by Legomonster33** [comment]
> I thought I used the template correctly

lol no

**Comment by mwoehlke** [comment]
Duplicate of #1092?

**Comment by WinterCrystal** [comment]
> I thought I used the template correctly

You're far from using the template correctly.
