### ISSUE TITLE
Minor resource consumption while building rework/balancing suggestion

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1201]
**Describe what you would like changed, and why.**
Currently, when building structures that cost multiple types of resources you must all of the resources needed in core. (Example: i am building an unloader. If i have 0 titanium in core, it wont build at all regardless of the amount of silicon i have.) I think this needs to be changed.

**Describe the changes you want to propose. Include possible alternatives.**
I suggest that building consumes avaliable resources, regardless of other resources needed to build the building. For example, after this change, to build a sorter (costs 2 copper and 2 lead) i could build it 50% of the way if i only had copper in core. It makes sense, and would save a bit of time while building without changing the game very much.

**Comment by DeltaNedas** [comment]
idiot on v6.abandoned.io places power cube
before: there is no silicon, not much harm done and he can be banned without consequence
after: now theres no lead or copper and the world is fire and everyone very sad

**Comment by D-player1** [comment]
> there is no silicon, not much harm done 

Impossible, running out of silicon will always cause a problem

**Comment by genNAowl** [comment]
So basically make building like researching in the tech tree?

**Comment by scarf-generic** [comment]
> idiot on v6.abandoned.io places power cube
> before: there is no silicon, not much harm done and he can be banned without consequence
> after: now theres no lead or copper and the world is fire and everyone very sad

Im sorry that .io's player base is self-destructive? I dont really know what to say to this.
This is like complaining about logic because it can be used to fill the map with routers: logic is a great feature to the game, but do you want it removed/heavily nerfed due to its griefing potential?

**Comment by scarf-generic** [comment]
> So basically make building like researching in the tech tree?

This is an amazing example, i dont know how i didnt think of it. Exactly.

**Comment by RedstonerKBC** [comment]
> idiot on v6.abandoned.io places power cube
> before: there is no silicon, not much harm done and he can be banned without consequence
> after: now theres no lead or copper and the world is fire and everyone very sad

Honestly if you're that worried about people using resources, then make more. What you want players to just sit around and watch everybody else play the game?

**Comment by BlueWolf3682** [comment]
just make more silicon, its really not that hard to make silicon @DeltaNedas

**Comment by Ilya246** [comment]
@BlueWolf3682 have you played multiplayer? almost every player on the server spends about several tens of thousands silicon per frame

**Comment by Nhimanss** [comment]
closer to tens of thousands per minute.
