### ISSUE TITLE
Weather effects are annoying

### ISSUE THREAD

**Issue by Medicinexs** [Anuken/Mindustry-Suggestions#1202]
**Weather effects should be reduced because it is so annoying and makes the game less enjoyable
I can barely see the game but it is so annoying.**

**A few youtubers even said if the weather effects are annoying. I also asked some players and they also said the same thing. The weather effects is cool but dont make it too bold or too much effects because it making the game unplayable.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Isn't real life weather actually annoying and sometimes you can't see through it?

**Comment by GlennFolker** [comment]
Wait for a storm. And when it comes, go outside. Try to reach the nearest structure from your home. Annoying.

**Comment by sk7725** [comment]
Tell that to your weather outside

**Comment by ab1gy0t3** [comment]
> A few youtubers even said if the weather effects are annoying

Lol normally this would be a fine point but in my opinion the Mindustry YouTube community isn't too great

**Comment by RogueRedHawk** [comment]
>go outside

>Tell that to your weather outside

>Isn't real life weather actually annoying

Video games ≠ real life. General equipment failure is also annoying, but including it into a game design for "realism" would be dumb. What if your factories occasionally just stopped working?

From a game design perspective, challenges or setbacks in a game should be a punishment to the player for playing poorly. You should be able to do something to prevent a punishment, and absolutely should be able to prevent a severe punishment. Currently, sandstorms are a very annoying punishment **with no way to prevent them**. The most skilled and well equipped Mindustry player cannot dampen the visual effects of a sandstorm. 

Something I would suggest to fix this is for higher tier units to be able to see through sandstorms to varying degrees. Perhaps Metaglass visors on T3 units allow higher visibility, or a radar array allowing motion tracking through visual noise. There needs to be some way of fixing the storms if they are going to be as severe as they are now.

**Comment by itcannotbe** [comment]
Following that train of thought.
Dying in-game is annoying, the dev should remove it.
Losing the game is annoying, the dev should remove it.
Nerfing blocks is annoying, the dev shouldn't do that, with no way to prevent them.
What else to add?

Sand storms are a type of challenge, not a penalty.
Know the difference.

**Comment by sk7725** [comment]
Tbh the damn sandstorm in SMM2 is more annoying than this

**Comment by userlol2** [comment]
When theres a storm in night u can barely see anything,maybe need an option to close them

**Comment by RogueRedHawk** [comment]
@itcannotbe 

>Dying in-game is annoying, the dev should remove it.

Dying and losing are punishments for the player building an inadequate defense. To compare that to a sandstorm, which is impossible to circumvent, is a false analogy and a logical fallacy.

A sandstorm isn't a challenge that can be avoided. It randomly shows up on maps in the campaign, midway through capturing sectors.

A sandstorm has no way for a good player to avoid. It is a bad mechanic in its current state.

See my comment for how I would fix this.

**Comment by scarf-generic** [comment]
> > Dying in-game is annoying, the dev should remove it.
> 
> Dying and losing are punishments for the player building an inadequate defense. To compare that to a sandstorm, which is impossible to circumvent, is a false analogy and a logical fallacy.
> 
> A sandstorm isn't a challenge that can be avoided. It randomly shows up on maps in the campaign, midway through capturing sectors.
> 
> A sandstorm has no way for a good player to avoid. It is a bad mechanic in its current state.
> 
> See my comment for how I would fix this.

Having no sand in a sector is also a challenge that cannot be avoided, and is not given to you because you play badly. You simply have to deal with it. Launching sand to that sector with launch pads, turning scrap into sand, etc. are options to deal with this challenge. Just like lack of sand, a sandstorm has ways to manage. Get a different power source, use different units, whatever.
Personally, i dislike weather and anything that makes the game more map/rng based, but that does not mean anything. Its a challenge, and its out of your control. You just have to deal with it.

**Comment by RogueRedHawk** [comment]
@scarf-generic 

>Having no sand in a sector is also a challenge that cannot be avoided

If I have no sand, a good player can launch with sand or move sand to the sector or pulverize scrap. How are you not able to see that "no sand" is a challenge with good game design, as it can be avoided or prepared for, while sandstorms cannot be avoided or prepared for, and are therefore bad game design.

>a sandstorm has ways to manage. Get a different power source, use different units, whatever.

How are those ways of managing a sandstorm?

There is no way of avoiding a sandstorm right now. Is there a unit or building which dampens their effects? No, not in the game. There have been suggestions that things like force projectors should block sandstorms, or a new building. But currently, the world's best Mindustry player can do _nothing_ to combat a sandstorm.

**Comment by RogueRedHawk** [comment]
@itcannotbe 

>Sand storms are a type of challenge, not a penalty. Know the difference.

Challenges in a game should ultimately be controlled by the player. If they want to go to a super hard sector, they will likely be rewarded with access to thorium and titanium. If a player would rather stay at the difficulty level 2 sectors at first, they are clearly not looking for a challenge.

A sandstorm is not a challenge. It does not reward a player brave enough to risk taking it on. It is forced upon players. It does not feel rewarding to weather a sandstorm.

>There is nothing preventing you from skipping that certain map.

Yes there is. How can you progress in the campaign if you are just avoiding playing ever map with sandstorms? I don't think this point holds up.

However, I do think it would be cool if sandstorms _were_  a challenge. What if enemy waves did not attack during sandstorms? The sandstorm prevents their technology from safely identifying the drop point, so waves cannot be sent in. If a player feels like it, they can continue building their defense through the storm to get the upper hand on the enemy. However, if they'd rather just go to a different sector and not experience the storm, they give up on time they could be fortifying defenses and increasing production.

**Comment by kdvolder** [comment]
The weather effects and also night-day cycle are indeed annoying. If they are meant to be a challenge, I don't think its the right kind of challenge. Good challenge is something you overcome by playing strategically. What kind of strategy can you employ do combat barely being able to see what's on your screen?

**Comment by Buddermario7** [comment]
I think a good compromise would be to have the option to reduce the visibility loss, like turning off weather particles in Minecraft. Randomly spawning storms are an interesting mechanic and extra challenge when they occur, but they aren't really challenging to prepare for unless you exclusively use solar panels for power. I can see how others might be bothered by the low visibility though, so the option to reduce visibility loss would be helpful for them.

**Comment by kdvolder** [comment]
Good point about other 'non-visual' effects caused by weather, such as solar panels. Yes, that is the 'right  kind' of challenge. 

The visibility reduction to me is nothing but annoying. If this is the kind of challenge we 'enjoyed' we would all be deliberately turning down the brightness and contrast on our monitors up to a point where we can barely see what's on the screen.

**Comment by hfs2** [comment]
I agree 200% that the visible "artifacts" of the weather are intensely annoying.

It is apparent that a lot of time and thought and coding effort have gone into weather and day/night cycles. And I know the way to get an idea/opinion considered is to present it in a calm, rational manner. But...

It's just horrible. I hate it.

In fact I've abandoned v6 (last tried sector 173 on Bleeding Edge 20132) in disgust until / unless those effects are dramatically reduced. Ideally there'd be an option to disable the effect entirely. (Un-checking "Show Planet Atmosphere" had no discernable effect. I may file this as a bug report but am not 100% it is supposed to remove clouds.) Clouds at 10% opacity
might be OK - I probably won't play v6 again unless the night cycle becomes optional.

I can understand the attitude that this is another challenge. I agree with kdvolder that this (the effect on visibility) isn't the kind of challenge I'm interested in. In fact it is a little insane when you think about it.

- Many players have spent big $$ on precision monitors, advanced graphics cards, and high end CPUs.

- The developer has toiled mightily and produced fairly polished and responsive graphics.

- A lot of the appeal of the game is the incredible detail and activity on the screen at any instant.

Then you... shroud it all in darkness and cover it with clouds. For me, the appeal is lost.

I've not played v5 yet. Once I complete that campaign I'll check the status of this issue for v6.
