### ISSUE TITLE
Make units do something when no cores/spawns are present

### ISSUE THREAD

**Issue by mwoehlke** [Anuken/Mindustry-Suggestions#1203]
**Describe the content or mechanics you are proposing.**
When there are no enemy cores, units should do something instead of idling around uselessly. Right now you have to manually control them to get them to do anything if there isn't anything in their range to shoot at, which is incredibly annoying. Ideally, they should seek out the nearest enemy building, but failing that it would be nice if, in attack mode, they would follow the player around. (Path-finding optional; AFAICT path-finding only works to go to a core or rally point.)

Note: I've tried using Logic to get them to be less useless, but every attempt to get them to go somewhere other than a fixed x/y results in them moving to `0,0`.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make it *much* easier to clean up a sector after destroying all the enemy cores.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
RTFSC?

**Comment by mwoehlke** [comment]
@itcannotbe, riiiight, because people that just want to play the game should have to RTFSC to do that. Maybe try being *helpful* instead of a condescending jerk; why not show an example of "make units follow the player and attack anything nearby" logic? Also I can't figure out how to debug anything; `System.out` seems to go to `/dev/null`. Nor is there any in-game deugging AFAICT; `print` does nothing.

It would ***REALLY HELP*** if there was some documentation.

Anyway, sorry, but "use Logic" is not the answer to everything; even if it *worked*, it's a right proper PITA to have to write code to do things that should be *basic features*. Especially when the interface is so clunky. (At minimum, there ought to be a way to load and save code to a library, the way "schematics" let you load and save tiles.)

**Comment by itcannotbe** [comment]
THERE WILL BE DOCUMENTAION WHEN THE GAME IS RELEASED AS STABLE.

I would kinda be stupid to waste time documenting your code when you're making constant changes to it.

**Comment by itcannotbe** [comment]
Print doesn't work because that's not how print works.

**Comment by imreallybadatnames** [comment]
bruj
you use printflush after print

**Comment by sample-text-here** [comment]
> I've tried using Logic to get them to be less useless, but every attempt to get them to go somewhere other than a fixed x/y results in them moving to 0,0.

send the code

> print does nothing.

as people said already, use printflush. did you even try to use logic for more than 10 seconds?

> It would REALLY HELP if there was some documentation.

try "deltaNedas/rtfm". official documentation will be on the wiki once the full version releases

> "use Logic" is not the answer to everything

you're right. but for this, it is

> At minimum, there ought to be a way to load and save code to a library

open the processor, click edit, click copy to clipboard. functions are possible through `@counter` but aren't very useful unless you really need to use them

**Comment by imreallybadatnames** [comment]
@mwoehlke wake up

**Comment by mwoehlke** [comment]
>> "use Logic" is not the answer to everything
>
> you're right. but for this, it is

Really? Please show code for how to select the player, because I *cannot* figure out how to get it to work consistently. `radar` doesn't seem able to do it and `uradar`... sometimes works and sometimes doesn't. Considering I can select damaged buildings, or ore, or turrets *anywhere on the map*, the inability to select enemy *units*, or the player, is baffling.

>> At minimum, there ought to be a way to load and save code to a library
>
> open the processor, click edit, click copy to clipboard

Okay, let me amend that. Some way that *doesn't involve an external application*. (Because that's going to work ever so well on mobile. Even on desktop, that's pretty terrible.)

Also, by clarification, by "library" I mean "a collection of saved code", not in the usual programming sense. You know... *like schematics*.
