### ISSUE TITLE
A popup that tells you how to bring back your hud the first time you press c

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#1205]
**Describe the content or mechanics you are proposing.**
Its a bit of a long shot if *minecraft* of all games doesn't even do this but it would be nice.

*alternatively, include it in some sort of extended tutorial or move it on a harder to press key*

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

![image](https://user-images.githubusercontent.com/45698812/99181208-dea84980-26e1-11eb-8445-66320d30567e.png)
![image](https://user-images.githubusercontent.com/45698812/99181227-f384dd00-26e1-11eb-9052-f0222c291feb.png)
![image](https://user-images.githubusercontent.com/45698812/99181213-e4059400-26e1-11eb-9f3c-a2b7b1970880.png)
etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
oo thats a good idea

**Comment by DeltaNedas** [comment]
@Highfire1 made pr, close

**Comment by Highfire1** [comment]
yay
