### ISSUE TITLE
About Schematics

### ISSUE THREAD

**Issue by lINSTINCTl** [Anuken/Mindustry-Suggestions#1206]
**Describe the content or mechanics you are proposing.**
Since logic related Schematics is now a thing to save time from putting commands and players have many schematics now. It would be great if groups/folders will be added

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will help us to oraganize and locate our schematics because like me I'm having a hard time to find the schematic that I will use.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
There is already a search function... but groups or folders would be a good thing to add.

**Comment by DeltaNedas** [comment]
>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by scarf-generic** [comment]
#220
Strange though, it does not seem like anuke rejected this idea. Maybe nobody has had the time to make it into a pr?
