### ISSUE TITLE
Set daylight cycle in custom maps

### ISSUE THREAD

**Issue by Arackulele** [Anuken/Mindustry-Suggestions#1208]
**Describe the content or mechanics you are proposing.**
We should be able to set a day night cycle in the map editor , right now you can only set a fog color that will always be there. 
I suggest a menu where you can set fog day , fog night , how long a day night cycle takes and maybe something else idk

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Better custom maps and more immersion in maps , it would make maps possible where you can only see at certain times and  just
overall coolness

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Catchears** [comment]
> [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Pressing `x` to doubt, see #1162

**Comment by Arackulele** [comment]
> 
> 
> > [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> Pressing `x` to doubt, see #1162

quick search,ive looked in the discord channel and sarched for day night cycle and didnt fins a nything

**Comment by Catchears** [comment]
> in the list of suggestions

3rd (2nd on discord) result for "day"
4th (2nd on discord) result for "night"
2nd (2nd on discord) result for "day night cycle"
