### ISSUE TITLE
Add logic tiles to the same group

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1210]
**Describe the content or mechanics you are proposing.**
Pretty simple, add logic tiles to the same group so we can place them over each other.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It makes sense and it will be consistant with other grouped blocks. There is not really a reason to avoid doing this as far as i know.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
5. - [x] I have put an x in a box.

**Comment by DarkBrick** [comment]
Either i don't understand this suggestion or there alredy is a 'logic' category

**Comment by itcannotbe** [comment]
If you don't understood what OP means with his suggestion, you shouldn't probably be commenting on this suggestion.

**Comment by scarf-generic** [comment]
> Either i don't understand this suggestion or there alredy is a 'logic' category

"grouping" tiles means you can build them over each other. For example, you can build a power node over a battery but you cant build a processor over a switch.

**Comment by scarf-generic** [comment]
woohoo it got added!
