### ISSUE TITLE
Show sector minimap on planet overview screen

### ISSUE THREAD

**Issue by jcharaoui** [Anuken/Mindustry-Suggestions#1211]
On the planet overview screen, display sector minimap along with other sector information.

The v6 campaign involves lots of jumping around sectors on the planet, namely to defend, upgrade cores, launch resources from one sector to another, etc. It would be a great QoL improvement to show a visual cue of what each (discovered) sector looks like (map + built-up areas), just like with the in-game minimap.

I know that you can already rename a sector, but it doesn't convey the "which sector is that again" information as efficiently as a visual cue.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by mwoehlke** [comment]
Not raining on the idea, which I think would be neat, but personally I rename my sectors according to what they produce and where they send it. (A longer name limit would be nice! Or, even better, show this information along with the core production rates :slightly_smiling_face:.)

**Comment by dudecon** [comment]
I re-name sectors by function as well, but a minimap thumbnail in addition would be really helpful.
