### ISSUE TITLE
Bridge conveyor output

### ISSUE THREAD

**Issue by cl1pr3** [Anuken/Mindustry-Suggestions#1212]
**Describe the content or mechanics you are proposing.**
To be able to toggle which direction the output goes to

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Instead of needing to keep a bubble around the bridge output, one can simply toggle the output to the desired direction

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Esnardo** [comment]
> I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
Liar. This is in the list.

**Comment by itcannotbe** [comment]
> **A few things you shouldn't suggest**
> *These have been proposed many times already, and I won't be adding them.*
>    Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

Now tell us that's it's not in the do not suggest list.
