### ISSUE TITLE
Fix sector damage/base destruction

### ISSUE THREAD

**Issue by andr658** [Anuken/Mindustry-Suggestions#1213]
**Describe what you would like changed, and why.**
The sector damage system is meant to prevent you from just launching to all the sectors at once and removing any challenge, but it's way too harsh as it is. Managing more than two Sectors at once is a garbage fire of repairing bases, repairing bases, and repairing bases. If you god forbid have a mediocre defense, your base is going to be 30% destroyed by the next minute if you're lucky. Even 2 sectors can be a bit of a mess if their hard enough.
**Describe the changes you want to propose. Include possible alternatives.**
1. Reduce the harshness of sector damage, either by just doing less damage, or avoiding things annoying to repair like power/liquid lines
2. Or, adding an "auto-repair-base" type button. It would queue up all destroyed buildings and maybe even give vastly increased building range until the base is repaired. Polys should already do this in theory, but since them and their factories typically get destroyed upon daring to check on the other sector for 2 seconds, it doesn't do what it do.

**Comment by kingb74** [comment]
Yea and a simple thing for ure second suggestion would be to make poly drones work if ure not in the sector it would make life like a million times easyer
