### ISSUE TITLE
[Feedback]: Prevent Air Units From Flying On Black Area

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry-Suggestions#1214]
**Describe what you would like changed, and why.**
Currently all flying units (including players) can fly outside of the map and bypass AAs easily because players are way more smarter than the AI, thus they can search for weakest side and navigate through the base's defenses.
On most of the community map, the Core will be placed near the black area, and that makes it impossible to defend against player's attack as air units.

**Describe the changes you want to propose. Include possible alternatives.**
Is it possible to limit air unit's movement so they can't fly on black area? (Use same path as ground unit).

**Comment by D-player1** [comment]
> On most of the community map, the Core will be placed near the black area,

~~It's the community's problem, not the game~~

**Comment by scarf-generic** [comment]
Cheesing defenses is the only thing that makes air units remotely viable. You want to remove that?

**Comment by itcannotbe** [comment]
To force people to actually try different tactics?

**Comment by Legomonster33** [comment]
then air units would be identical to spider units.

**Comment by genNAowl** [comment]
^

**Comment by mangblekok** [comment]
Maybe it's better to rephrase my proposal to be like this:
"Please add an option to enable/disable the flying restriction in the map editor", so it wouldn't disable on all map.


> ~It's the community's problem, not the game~
Yes it is, and I admit that I spend most of my playing time in community servers, so my answer to these quoting below is for gameplay in community servers.


> Cheesing defenses is the only thing that makes air units remotely viable. You want to remove that?
Player's intelligence can't be compared to AI.
Players can easily pick a path which has the weakest defense on enemy base.
For example, even though my team members are veterans, we usually only get to midgame stage where each teams has a decent amount of T3-T4 units, the game ends and a new map is played.
Have you ever feel the adrenaline rush from intense battle in lategames, where both of teams has T5 and advanced turrets, where each sides are trying their best to capture and defend strategic areas?
This is what I feel lacking from current community gameplay, because air units can fly by through the black area, so they can simply end the game (for example by coal bombing using low leveled air units).
I feel the satisfying win or even defeat when everyone can advance to lategame without having their base burnt down by small low level air units.


> To force people to actually try different tactics?
Yes, and it's tightly connected to the layout of the map itself, therefore this suggestion is for the map maker, it wouldn't be good if this suggestion is implemented globally (if it's going to be implemented, that is).

> then air units would be identical to spider units.
Yes and no, there are several differences between their stats. Such as HP, firepower, movespeed. Spider units can't easily do a hit & run tactic because they are slow, but they pack a bigger punch if compared to air units.
IMO air units are deadlier because spiders are more noticable in the radar, therefore they usually get intercepted before they can get near to base. But it's a different story for example a Quad, most of the time it's already too late to intercept before the unit cause wreak havoc and make someone's base beyond repair, even with lots of Polies, rebuilding doesn't even worth it.
Of course, having enemy air units from being too close to a base can be prevented if someone choose to play another role, as a recon.

This game is not simply a sandbox game, it's also a complex roleplay game. Someone can choose to become a:
- Builder (Resource gatherer, turret builder, attack outpost builder, etc)
- Soldier (Players who like to become a unit rather than building things)
- Commander (Lead their team about what to do)
- Reconaissance (Watch their surrounding and pay close attention to the minimap more than everyone else in their team)
- Technician (Players who likes to tinker with logic processors and tries their best to optimize every aspect of their base)
And so on...
Note: These roles above are not really exist in the game, but if you play lots of community games, you can eventually feel it too! 😸 

So back to topic, this suggestion is not for ALL maps, it's better suited for map makers to decide whether their map needs it or not.

More inputs are appreciated, keep it coming bruh 😉
