### ISSUE TITLE
Achievements! 

### ISSUE THREAD

**Issue by popitka360** [Anuken/Mindustry-Suggestions#1215]
Hello Anuke! I would like TV to add achievements to the game! It's fun! Example of achievement: Copper! Description: Get copper!

**Comment by SteelBlue8** [comment]
This already exists if you have the steam version, I believe- it's kept that way as an incentive for people to buy the game. (This is baseless and I am unsure, so correct me if I'm wrong)

**Comment by scarf-generic** [comment]
For future refrence: dont kill the format
