### ISSUE TITLE
Please, please update iOS

### ISSUE THREAD

**Issue by lookinformods** [Anuken/Mindustry-Suggestions#1216]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Wait for v6 to be released as stable.

**Comment by lookinformods** [comment]
Ok sorry for any trouble if there was

**Comment by DayTimer** [comment]
Have you ever heard about templates?

**Comment by wenzmen** [comment]
https://discord.com/channels/391020510269669376/396416151032299521/757972562885214238
