### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by lookinformods** [Anuken/Mindustry-Suggestions#1217]
**Describe the content or mechanics you are proposing.**

Please update iOS

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A lot of iOS players that find out about a update that isn't coming to them wouldn't be fun

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" categorie

**Comment by Legomonster33** [comment]
>  I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

right, its not like anuke is going to make it work on ios after the official v6 release or anything.

**Comment by BlueWolf3682** [comment]
i mean, my ipod is running 113.2 just fine, i dont see what your issue is

**Comment by DeltaNedas** [comment]
unfortunately anuke didnt drop ios support
