### ISSUE TITLE
New purpose for surge towers

### ISSUE THREAD

**Issue by Wetelemon** [Anuken/Mindustry-Suggestions#1218]
**Describe the content or mechanics you are proposing.**
Allow surge towers to connect between sectors, so you can turn one of them into a power plant and distribute power around the whole planet.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would help to power sectors that have no coal/thorium (for reactors)/heat sources so defending the harder ones would be a bit easier. Also in attack sectors you wouldn't need to care so much about power while you're getting attacked. This is not a big change but definitely would be a useful QoL feature.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by wenzmen** [comment]
I think it would need to be really expensive/hard to send energy and easy to receive it, but a surge tower is definetly too cheap for sending and too expensive for receiving because you're not gonna have any surge if you dont have a lot of power.

**Comment by QmelZ** [comment]
> I think it would need to be really expensive/hard to send energy and easy to receive it, but a surge tower is definetly too cheap for sending and too expensive for receiving because you're not gonna have any surge if you dont have a lot of power.

kind of balances each other i guess, but there has to be a static price

**Comment by mwoehlke** [comment]
Orbital power transmission would be neat, but I don't think surge towers are the way (maybe a new building?). There are ways to build power from nothing, however, e.g. solar panels, and chains using cultivators. (If you have sand, you can also drill for oil.) As a last resort, launch thorium from another sector.

> you're not gonna have any surge if you dont have a lot of power

Again, launch it from another sector. Or give yourself some to start.

**Comment by wenzmen** [comment]
> Again, launch it from another sector. Or give yourself some to start.
Oooh, a battery in the core? Thats a neat idea.

**Comment by Wetelemon** [comment]
Well then if buffing the surge tower would be so op, then maybe allow it to connect sectors together, however there would be power losses, and to send power one sector that you have a core in, would send power to another core, or maybe only captured sectors that are next to the receiver can send power? Idk, but I just want a feature that would allow you to connect sectors' power together. It would need some balancing or something but it still would be good.

**Comment by Wetelemon** [comment]
> 
> 
> > Again, launch it from another sector. Or give yourself some to start.
> 
> Oooh, a battery in the core? Thats a neat idea.

mwoehlke most likely meant sending resources, not a battery or anything but actually? being able to charge your core with some power like maybe 50k units of it and launching ur core would be neat, or maybe the amount would depend based on core size? that's a good idea, worth noticin

**Comment by RebornTrack970** [comment]
Its a neat idea, but hard to implement and op
