### ISSUE TITLE
Allow Grouping/Nesting and Hiding Code in Logic Processor

### ISSUE THREAD

**Issue by wenzmen** [Anuken/Mindustry-Suggestions#1219]
**Describe the content or mechanics you are proposing.**

Basically a tool to select a bunch of code to group/nest it, you can than name the group and hide it , and you could also set a jump block to jump to that group, running the code in the group instead of a specific block.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will make writing code much cleaner, when working on complicated things it is a pain to sift through the 100s of blocks to find the right one, especially when the colors dont really stand out and can mean many things

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Catchears** [comment]
So basically #889 or #1191 but you can collapse it? Sounds good.
