### ISSUE TITLE
Add "Banned Blocks" and similar options from the Editor to the headless server options.

### ISSUE THREAD

**Issue by Momiro** [Anuken/Mindustry-Suggestions#122]
In the Rules section of the Editor there are some custom rules for the map. Things like "Wave Timer" "Respawn Time" "Banned Blocks" "Player Health Multiplier" etc
These rules would be useful to modify as a server owner. Specifically I want to use "Banned Blocks" to make a server with limited technology for use with a plugin that generates a map when you start hosting a game.

**Comment by DeltaNedas** [comment]
this is already possible

**Comment by v6** [comment]
> 
> 
> this is already possible

Which begs the question, how?

**Comment by itcannotbe** [comment]
Which begs the question, how did you not know how. It's easy to find that information from documentation on the source code.

**Comment by Anuken** [comment]
`rules add <rule> <value>`

e.g. `rules add bannedBlocks [conveyor]`, `rules add playerHealthMultiplier 0.5`

**Comment by tsal** [comment]
> Which begs the question, how did you not know how. It's easy to find that information from documentation on the source code.

 "read the java docs" isn't helpful for non-java-developers, and seems pretty out of place on a "suggestions" response that led to a _valid question_.
