### ISSUE TITLE
Haste + Dampening Projector for Units

### ISSUE THREAD

**Issue by Andraez** [Anuken/Mindustry-Suggestions#1223]
**Describe the content or mechanics you are proposing.**

### Haste Projector.
   (Simple idea) A new defensive effect tower, capable of giving units a speed boost within its field, with only a minor increase in fire-rate. _(fire-rate +10%/25%, movement speed +25-75%)_
The boost provided within its field would allow allied units to travel faster.
_It is possible instead of adding a new tower, it could be implemented as a mechanic of the command center when supplied with fluid/items._

### Dampening generator.
  A new offensive effect tower that applies the opposite effect to enemy units within its field. It will slow down enemies, but with each enemy being effected in the field, it will increase the tower's "load." If it's load reaches a certain point, it "overheats" and has to restart, similar to the force projector. It too can be supplied with coolant to increase its load capacity.
_It could be possible instead of adding a new tower like this, you could implement this mechanic into the force projector, which will have this effect when supplied with a certain item (with a slight power increase.)_

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would allow for some more strategic gameplay with units and commanding them, and adding more challenges to overcome. It would allow for Parallax trapping by pulling enemy units into a dampening field, another strategic approach to the new tower.
I think this would be a greatly appreciated feature for the community overall.

-

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
> *[X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

your "haste projector" already exists in the game, its called a "minke"

**Comment by Andraez** [comment]
> > * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> your "haste projector" already exists in the game, its called a "minke"

Uh, that's a naval unit, and I'm referring to a building, not a unit to begin with.

**Comment by QmelZ** [comment]
a block boosting blocks makes sense. an unit boosting units makes sense. a block boosting units doesn't make any sense at all, minke is supposed to be the unit overdrive projector.
