### ISSUE TITLE
A Very Important Feedback Post, Probably the Best Feedback You Have Seen in a While

### ISSUE THREAD

**Issue by RogueRedHawk** [Anuken/Mindustry-Suggestions#1224]
**Describe what you would like changed, and why.**
I think it would be really cool if people didn't sit in this repo with their wet fingers hovering over the 'Ctrl'+'V' keys ready to paste their pre-typed sob story about how western civilization has fallen because people don't follow the template or didn't read every single one of the 1,200 issue threads to see if Anuke has hinted at thinking about the feature before.

Often times, the same dozen or so people will lurk in this repo for the sole purpose of putting an unhelpful comment on a new feature request or feedback simply saying "muh template" or claiming the issue already exists. They never mention or link where it exists. It is demeaning and unhelpful. See my issue #1111 , where two people say the feature has already been considered with no intent to show me where they exist (it ended up being #459) while clearly having not even read my request.

I am a person that calls out duplicates, but I ALWAYS link AT LEAST ONE duplicate or relevant thread. Not linking is not helpful.

**Describe the changes you want to propose. Include possible alternatives.**

If you are going to call out a repost, link or cite where the original thread was, and potentially include how you got there.

If you are going to criticize someone for not following the template, first make sure it doesn't follow the template. Sometimes people delete the headers when they type their answers.

Stop being toxic. See the comments on #1202. There is no good discussion on that thread, only one side bringing up something wrong with the game and the other side calling bad game design a "challenge."

**Comment by RouterChainsSuckk** [comment]
Look at suggestions first or else your gona cause ww3

**Comment by sample-text-here** [comment]
#459 

please search before you post a new suggestion

**Comment by mwoehlke** [comment]
> If you are going to criticize someone for not following the template [...]

...then *explain* what they did wrong. We aren't psychic.

> Stop being toxic.

:+1:

BTW, thanks for posting this; I'd been considering the same thing. I've noticed a real issue with certain users being arrogant, condescending jerks, and I'm not the only one that's been on the receiving end of these individuals. (If anything, I'm *less* offended by them because I know they aren't singling out *me* to offend.)

**Comment by RogueRedHawk** [comment]
@sample-text-here Thank you for linking the thread, however your request is unreasonable. I could not be expected to search for and read every single post with "Multiplayer" and "campaign" in the title. When I made my post, I searched those terms and read every post I thought was relevant, in addition to checking the Trello.

The post you linked was not named in a way that made it clear that it was the same as my suggestion, although it is very similar upon inspection. However, it is not identical. #459 suggested new game mode with PvP on a planet wide scale, while my suggestion was to improve the current PvE campaign by adding just one feature.

Finally, that post was 600 posts ago. I could not have rigorously checked to find that post as it would have taken way too long to read through the 600+ posts it would have taken to get there, and as someone who doesn't know if the suggestion exists, it might just be a waste of time.

The fact of the matter is that doing a "quick search" will not always identify the existence of a suggestion. I agree that many of the posts on this repo could be classified as posts that could be resolved through a quick search. But that doesn't mean we should just comment that on every post. Linking, as you did, is the first step to helping people avoid reposts, but also linking relevant results would make it easier for people to find requests if they do exist.

**Comment by DeltaNedas** [comment]
1. there is never any excuse for not using the template
2. yes i agree that "duplicate" is bad

**Comment by scarf-generic** [comment]
Just gonna slip this in here: we would not have this problem if people followed the template and put 5 minutes of effort searching for duplicates.
This would save everybodys time. Example: we would not be having this discussion.

**Comment by mwoehlke** [comment]
> we would not be having this discussion [if everyone followed the template]

Maybe... but we *would* be having a similar discussion. Yes, there are some instances where people explicitly don't follow the template (e.g. a recent request that was explicitly one of the features called out in the README as a will-never-implement), but there is also a pervasive problem of certain users behaving in a way that is simply inappropriate and unjustifiable. Honestly, if this was Stack Exchange, I would be flagging those users' comments as possible CoC violations. Alas, the process here seems to be that Anuke is expected to moderate, and that does not seem to be happening.

**Comment by scarf-generic** [comment]
> Alas, the process here seems to be that Anuke is expected to moderate, and that does not seem to be happening.

Ironic.
Take a look at `README.md`

**Comment by sample-text-here** [comment]
> Finally, that post was 600 posts ago. I could not have rigorously checked to find that post as it would have taken way too long to read through the 600+ posts it would have taken to get there, and as someone who doesn't know if the suggestion exists, it might just be a waste of time.

if you don't want to search 600+ posts, you can make github do it for you
![image](https://user-images.githubusercontent.com/56274831/99452906-07defa80-28d9-11eb-9d92-b106f324bda7.png)

also even though reason for #459 isn't exactly the same, the game mechanics are. they both want multi-hex multiplayer.

also most people aren't usually toxic, we just don't like seeing people not bothering to search before posting a duplicate. there are some people i've seen that are just h though

**Comment by scarf-generic** [comment]
wot

**Comment by RogueRedHawk** [comment]
@scarf-generic I closed the issue... since it ended up being a duplicate :P
