### ISSUE TITLE
Alpha/Beta/Gamma Idling

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1226]
**Describe what you would like changed, and why.**
Whenever I play Mindustry, I like to take control of a turret. The problem is, OOPS i forgot to supply the turret with ammunition. So I say, "okay lets just fix this". But the issue is that I have to scroll all the way back to my core to do so, which is abnoxious. So my idea is that when the player decides to control a nearby unit or turret, the player's core unit (default starter unit, such as gamma, beta, alpha) will idle. Idling means that the ship will stay still and will just chill. It can be destroyed but wont attack back and nor will it move. Lastly, if you decide to then respawn from the core, your original idling ship will just fall to the ground.

**Describe the changes you want to propose. Include possible alternatives.**

What I mentioned earlier.

**Comment by RedstonerKBC** [comment]
I'm assuming you meant to put X's in all of the boxes lol. I think we all want something like this.

**Comment by rmperkow** [comment]
I think only the Gamma should have this.

**Comment by jaygamer81** [comment]
> I'm assuming you meant to put X's in all of the boxes lol. I think we all want something like this.

I dont think its for feedback. I think its for features only.

**Comment by jaygamer81** [comment]
> I think only the Gamma should have this.

Yes. Good point. Perhaps beta should also have it but gamma could maybe perhaps be sentient? (Gamma could help you build and would attack enemies while your controlling the block/unit)

**Comment by 5382Ander2** [comment]
Use DeltaNedas/unit-factory
You need to remove the line limiting you to use it only in sandbox. This will open a possibility to cheat in campaign, but do not do that, it will spoil the game
Dependencies: DeltaNedas/ui-lib

**Comment by 5382Ander2** [comment]
![unit-factory_main js at master · DeltaNedas_unit-factory and 1 more page - Personal - Microsoft​ Edge 11_18_2020 15_05_03](https://user-images.githubusercontent.com/57288843/99540157-73939700-29af-11eb-91bf-d944728cff3a.png)
Remove this and it will work everywhere
