### ISSUE TITLE
New Use For Surge Tower

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1228]
**Describe the content or mechanics you are proposing.**
Have surge towers serve as a means of connecting sectors power,

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
simmilarily to launch pads launching items, it would be very ***epic*** if surge towers could be used to "connect" power across sectors

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
*rubs hands together*

Alright before anyone gets mad that there was already a suggestion about this made, notice Lego checked box 1 meaning they in fact DID search to make sure this wasn't suggested already but they did not find the other post. So if you're going to point them out for making a duplicate post, you can't say they didn't search for it when they just said that they did. Ok, now you can carry on with whatever angry comment you were going to post. lol

**Comment by genNAowl** [comment]
Yeah seems like you didn't see this: https://github.com/Anuken/Mindustry-Suggestions/issues/1218

**Comment by QmelZ** [comment]
i came here to say what 2 people already said so i will shut up and go.

**Comment by WilloIzCitron** [comment]
Hello

This is clone on #1218
See in this request or delete

**Comment by itcannotbe** [comment]
It would be very ***epic*** if have done a quick search in the list of suggestions to make sure this has not been suggested yet.

And yes, I just copied and pasted that.

**Comment by Legomonster33** [comment]
oops :|
