### ISSUE TITLE
Unit Minimap Color Change

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1229]
**Describe what you would like changed, and why.**
Currently when looking at units against a minimap that's full of buildings, it's nearly impossible to find said units unless they pass across empty spaces. This is unappealing visual uniformity, and I have a simple solution for it.

**Describe the changes you want to propose. Include possible alternatives.**
When a unit is drawn on the minimap, draw the unit's icon in its unit color. Octs are green, Flares are grey or dark orange, Reigns are also grey/dark orange, Spirocts are purple, etc.

**Comment by Legomonster33** [comment]
It would have to be an outilne around the unit otherwise telling what team the units is on would be, rather painful.
