### ISSUE TITLE
Old Music

### ISSUE THREAD

**Issue by SuperTux20** [Anuken/Mindustry-Suggestions#123]
**Describe the content or mechanics you are proposing.**

Technically this is for Mindustry Classic (which I'm sure is over and done with), but I was wondering if there could be a switch in the settings to turn on the old chiptune music?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I'm sure that at least somebody aside from me misses that music. It was more cheerful in a way, like "Ah, what a great day to build a factory!" The current music sounds ominous, almost menacing, though I'm sure lots of people like that too. Adding a toggle for it could make (almost) everyone happy.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
If you want the old music, you can just play it on loop in the background for the same experience. I don't have the rights to use any old music commerically, and I wouldn't want to even if I could.
