### ISSUE TITLE
Campaign difficulties

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1230]
**Describe the content or mechanics you are proposing.**
Add difficulty setting(s) to campaign. They could affect research costs, enemy base generation and waveset generation. Can be switched at any time - though already generated enemy bases won't generate anew. A way this can be done is the same way you adjust game rules in the map editor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Add choice to the difficulty of the game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
pretty sure has been suggested before...

**Comment by QmelZ** [comment]
#1137 #1138 #1179 and many others suggest this

**Comment by Legomonster33** [comment]
https://youtu.be/GooIKQs6SlY
for a good explanation as to why difficulty levels are ungood.

**Comment by abowen** [comment]
> 
> 
> #1137 #1138 #1179 are related

Yes they are related but different to this suggestion.

I really like this proposal because it's simple / relatively easy to implement compared to previous suggestions.

I'm honestly not that good at the game but once you understand the fundamentals, the campaign is a walk in the park with exception of 1 maybe 2 maps.

My suggestion to start would be

- Normal: Current rules
- Hard: Double enemies per wave, halve the time between waves
- Veteran: Hard with a boss every 5 (or so) waves

**Comment by abowen** [comment]
> https://youtu.be/GooIKQs6SlY
> for a good explanation as to why difficulty levels are ungood.

If you are going to link a 20min video, please provide a short summary. Not everyone has 20mins to spare to see if it's relevant or not.

My TL;DW from video: Make it granular difficulty, not predefined difficulty.

I'm also fine with this:
i.e. Allow each player to adjust times between waves, enemy multipliers, boss frequency, etc.
