### ISSUE TITLE
Possibility of choosing the output rate of a item/liquid source

### ISSUE THREAD

**Issue by nodevlfrb** [Anuken/Mindustry-Suggestions#1231]
**Describe the content or mechanics you are proposing.**
Being able to change / choose the flow of items or liquids getting generated by an item or liquid source block. i.e. choose 5/s instead of 10/s.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
A part of the game is making new schematics to use in-game or in multiplayer. We all know that we don't always get a full item belt in survival/attack or multiplayer. Being able to generate less items would allow to make more precise and accurate schematics, following what we actually get in-game. Moreover, ratios in schematics are an important parameter to take account of: we could easily choose the flow of items to reproduce a factory production.

The menu allowing to change the flow of items would be in the same place as the item selection one, maybe in another tab.

English isn't my native language, so if someone understands what I suggested and wants to explain it better, they can go ahead in the comment section.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WilloIzCitron** [comment]
The liquid or item source had controlable output rate

**Comment by QmelZ** [comment]
> *[X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

![Screenshot_20201117-125014_Chrome](https://user-images.githubusercontent.com/59574967/99374323-82a51700-28d3-11eb-9b12-9212ea452f36.png)

**Comment by nodevlfrb** [comment]
> > * [x]  I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
> ![Screenshot_20201117-125014_Chrome](https://user-images.githubusercontent.com/59574967/99374323-82a51700-28d3-11eb-9b12-9212ea452f36.png)

Hmm thanks you but it's not this at all. I suggested this as  a testing purpose for only source blocks and only in sandbox. It's almost the same as configurating the type of item you want to be generated out a item/liquid source....

**Comment by nodevlfrb** [comment]
i could even extend the analogy to logic blocks, so you say that we shouldn't be able to add new variables in a logic block? It's the same as a _configuration_

**Comment by QmelZ** [comment]
> Hmm thanks you but it's not this at all. I suggested this as a testing purpose for only source blocks and only in sandbox. It's almost the same as configurating the type of item you want to be generated out a item/liquid source....

thats still "additional configuration of blocks" so stop

**Comment by nodevlfrb** [comment]
show me where it has been already suggested then

**Comment by QmelZ** [comment]
i never said it has been suggested, my comment was about the "do not suggest" part in the readme.md

**Comment by nodevlfrb** [comment]
whatever it's not a proper config as anuke said. Maybe let's see what he thinks about this suggestion.

**Comment by QmelZ** [comment]
see you later, after 15 hours.

**Comment by Nhimanss** [comment]
Mabe he wants a "valve" block

**Comment by nodevlfrb** [comment]
What would be a "valve" block?

> Mabe he wants a "valve" block

**Comment by nodevlfrb** [comment]
@Anuken if you could have a look at this if you haven't already did

**Comment by itcannotbe** [comment]
![Screenshot_20201119_080854](https://user-images.githubusercontent.com/45280919/99603649-b2246280-2a3e-11eb-82de-f8db231c6488.jpg)

**Comment by itcannotbe** [comment]
I have doubts that you read README.md.

**Comment by QmelZ** [comment]
> I have doubts that you read README.md.

same
