### ISSUE TITLE
A "Resource Richness" setting in the editor

### ISSUE THREAD

**Issue by wenzmen** [Anuken/Mindustry-Suggestions#1232]
**Describe the content or mechanics you are proposing.**

A setting of how much resources you get from tiles, for example on a map that has 100% resource richness, a drill can output 0.12 resource/second/tile but if the map has 150% resource richness, it can output 0.18 resource/second/tile

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will help in maps that dont want to waste space for big sources of ore or it could make the game harder by requiring more drills to drill the same amount.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Most likely senario of this gets through:

Basically every map on every server filled with noobs: Resource Richness:  1x10^infinity %

**Comment by wenzmen** [comment]
why would that happen with this setting? what stops people on servers from making maps that are really easy now?
