### ISSUE TITLE
Speed up building/destruction once a sector is captured.

### ISSUE THREAD

**Issue by Klokinator** [Anuken/Mindustry-Suggestions#1234]
**Describe what you would like changed, and why.**
Right now, it is agony to slowly take apart a sector's defenses once captured. Truthfully, it's often a good idea to leave some defenses up, but in all seriousness, it's a HUGE time-sink destroying all of the turrets and lanes and other such systems one by one. The sector is captured, so why not let me build and destroy like ten times faster?

**Describe the changes you want to propose. Include possible alternatives.**
Increase the take-down speed of buildings by at least 10x. Increase the building speed of structures too. Just make this part of the game faster and less tedious.

**Comment by lINSTINCTl** [comment]
I would recommend make 9 mega's to destroy or build faster

**Comment by Klokinator** [comment]
So your solution to making sector removal stuff take less time is for me to spend a bunch of time building machines that can help me speed up that process?

Spend time to save time?

Yeah, sure, that's 'intuitive.'
