### ISSUE TITLE
Ability for logic to draw text

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1237]
**Describe the content or mechanics you are proposing.**
Make logic be able to draw text on displays

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make it vastly easier to display text

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
this would definitely allocate font cache stuff which needs to be gc'd, use anuke-logic char displays or routers textlib program

**Comment by RedStoner** [comment]
... Wish this was a thing..
