### ISSUE TITLE
Launch Pads are op as hell

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1239]
https://github.com/Anuken/Mindustry/issues/3428
https://discordapp.com/channels/391020510269669376/396416151032299521/778299889729667112

**Comment by Draco18s** [comment]
You can't link discord server messages like that. Anyone *not already in the server* can't find anything at that link.

**Comment by itcannotbe** [comment]
Here is a snippet.

![Screenshot_20201119_101309](https://user-images.githubusercontent.com/45280919/99612203-17cd1a80-2a50-11eb-8776-2ce09715d729.jpg)

**Comment by Legomonster33** [comment]
> You can't link discord server messages like that. Anyone _not already in the server_ can't find anything at that link.

but i did soooo :|
join the discord?

**Comment by Draco18s** [comment]
Only works if you also tell me what server I have to join. ;)
Yes, it was the official Mindustry server, but just the link doesn't give anyone any information what so ever which is my point.

I can get any link for any message for any server (including DMs!) and you won't be able to tell the difference.
