### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mirdevCodeSchool** [Anuken/Mindustry-Suggestions#124]
this is REALY GOOD no COOL!

I  want to modding this and make this game on scratch!

:D

**Comment by potatoisagender** [comment]
What.

What is the point of this statement??

**Comment by DS-3K** [comment]
It seems like he wants to recreate mindustry because it´s good but isn´t
cool.

Am Mo., 27. Apr. 2020 um 18:11 Uhr schrieb potatoisagender <
notifications@github.com>:

**Comment by bluet-it** [comment]
Scratch is not a _real_ programming language, do not attempt to recreate Mindustry on it. How would you change scene, spawn units, etc. Scratch is an educational program. Does not even handle IO operations
