### ISSUE TITLE
block status obscures 1 X 1 block completely

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry-Suggestions#1241]
**Describe what you would like changed, and why.**
the status indicator is a fixed size. It obscures a (1 X 1) sized block almost completely. 

**Describe the changes you want to propose. Include possible alternatives.**
toggle block status icon so player only sees when they want to know the status.

- when a ( button / toggle ) is pressed
- when moused over
- a button shown in the menu is toggled

**Comment by RedstonerKBC** [comment]
This is very noticable when you try to link a processor to the 1x1 block above it but you can't because the edit button is in the way.

**Comment by notrealn** [comment]
you can barely see if something is a duo or a hail from zoomed out with this on
