### ISSUE TITLE
Allow unit locate to locate a specific building

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1242]
**Describe the content or mechanics you are proposing.**
An addition to unit locate that allows you to locate a specific building (like locate @router or @lancer or whatever)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will allow for more unit control to be more efficient and make unit locate more useful. Adds more gameplay options by giving processor controlled units more information about their surroundings.

If you believe this is a duplicate suggestion please provide the link to it, i searched but was not able to find any issues (open or closed) suggesting this mechanic. Its been discussed multiple times on the discord server but i guess nobody got around to it. Thanks!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
would trim down your code, but caching **every single block type**'s buildings would be insane for the poor server which may be a phone from 2014.

**Comment by Legomonster33** [comment]
#974

**Comment by scarf-generic** [comment]
> #974

Ah, there it is. I even commented on it lol, goes to show how bad my memory is.

**Comment by scarf-generic** [comment]
> would trim down your code, but caching **every single block type**'s buildings would be insane for the poor server which may be a phone from 2014.

Lag is an issue, yeah. Maybe limit the amount of buildings you can locate per processor (for example, each processor can only search for 5 different specific buildings)
I dont know if this will even change anything, just a thought.
