### ISSUE TITLE
Optional JS in Mods

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry-Suggestions#1243]
**Describe the content or mechanics you are proposing.**

A field in mod.json which makes the javascript in the mod optional.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

With this feature added, if a mod uses javascript but it is not necessary to run the mod, the author might enable optional javascript and this way ios and old android users won't get a "this mod has scripts and your device does not support javascript" but instead they will still be able to use the json features.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been  yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GlennFolker** [comment]
This is complex, especially for mod dependencies. Also who cares about iOS users

**Comment by itcannotbe** [comment]
Well some older phones don't support more methods introduced in more recent versions of java. (And yes, I know java 8 isn't even recent.)

**Comment by QmelZ** [comment]
> This is complex, especially for mod dependencies. Also who cares about iOS users

i dont really know how to write java code but i know how stuff should work, it shouldn't be hard reading a value from mod.json, which is already done for the `hidden` value, then checking if the js is compatible (which is again, already done for the "your device doesn't support scripts" dialog) and not loading the scripts accordingly.

Also i care about ios users, they play the game too
And this script thing affects some older android versions alongside ios.

**Comment by QmelZ** [comment]
> Well some older phones don't support more methods introduced in more recent versions of java. (And yes, I know java 8 isn't even recent.)

this is kind of unrelated, i am talking about optional js loading based on device support, read my first paragraph above for detail

**Comment by itcannotbe** [comment]
Basically JSON only fallback if JS + JSON doesn't work because the device doesn't support JS loading?

**Comment by QmelZ** [comment]
> Basically JSON only fallback if JS + JSON doesn't work because the device doesn't support JS loading?

yes, but only if you specifically mention it in mod.json
