### ISSUE TITLE
iOS Achievements!

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1245]
**Describe the content or mechanics you are proposing.**
  iOS has a compete with friends platform called "Game Center". Why not use it and add achievements on iOS?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Steam has it, and it would be a fun feature to have around for iOS users. Finally, we can achieve heresy on mobile!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have actually checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version this time.
3. - [X] I have the experience to say it does not exist, unless it only works in the official Mindustry app in 6.0. (turns out TestFlight Mindustry doesn't count)
4. - [X] `README.md` is hot for this one.

**Comment by QmelZ** [comment]
knew you would suggest this lmao

**Comment by the-kido** [comment]
Doesn't google have google play? You could do something with that too.

**Comment by T1murik** [comment]
google play games goes brr brr

**Comment by BlueWolf3682** [comment]
*hmm*

**Comment by DeltaNedas** [comment]
why wouldn't anuke just write his own achievements ui and tie it in with steam? that would be much easier and not need integrating with ios shit

**Comment by itcannotbe** [comment]
Wasn't there a suggestion for google play achievement way back but anuke basically said, that is what steam was for?

**Comment by QmelZ** [comment]
but ios is paid too, so it would make sense to have achievements

**Comment by itcannotbe** [comment]
But iOShit is paid too but I doesn't have steam assisted multiplayer nor steam work shop access nor the ability to run JS based mods.

The only reason why Mindustry on iOShit is paid is the absurb cost to actually publish on the platform.

$100 USD yearly fee* vs one time payment on google play store?
