### ISSUE TITLE
V6 Launch pad

### ISSUE THREAD

**Issue by Bob20bob** [Anuken/Mindustry-Suggestions#1249]
**Describe the content or mechanics you are proposing.**

in the planet View menu give the option to pool all active launchers to a chosen sector, or allow the configuration of launch pad sector destination to be selected from the map menu

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

instead of having to tediously visit each sector and set the launch pad location to the desired sector, you can do it instantly from the map menu and reduc the risk of receiving damage if you are attacking a sector  

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
YES I LIKE THIS

**Comment by DeltaNedas** [comment]
you can already do this by pointing all your farms to a central relay sector which can then distribute resources to new sectors with one reconfiguration

**Comment by QmelZ** [comment]
> you can already do this by pointing all your farms to a central relay sector which can then distribute resources to new sectors with one reconfiguration

~~this is how v6 is supposed to be played~~

**Comment by Bob20bob** [comment]
> you can already do this by pointing all your farms to a central relay sector which can then distribute resources to new sectors with one reconfiguration

are you saying to send all the resources to a single sector then use unloaders to send them to launchers so that sector becomes a relay sector? if that is what you mean then yes i thought of that before but the issue with this is I have that selector sector needs to open space around the core and it needs sufficient resources to make power for all the launchers, and with there being a limited number of unloaders that u can put on a core even with vaults attached which limits the amount of resources launchable and the excess resources sent to that core are automatically wasted. on the other hand making a configurable launch pad selection from menu is way more simpler and efficient
