### ISSUE TITLE
add "signal junction" to byte-logic

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry-Suggestions#125]
**Describe the content or mechanics you are proposing.**
I propose adding a signal junction to the byte-logic. That _should_ look somehow like signal-router, except the circle in the middle. Its logic _should_ work this way: 
![Screenshot from 2020-04-27 12-10-34](https://user-images.githubusercontent.com/53530661/80360882-4ef39880-8880-11ea-89d0-9d4edf69861d.png) 
This mechanic in one node.
 image of signal-junction:
![logic-base](https://user-images.githubusercontent.com/53530661/80360368-844bb680-887f-11ea-96de-8076917220ef.png)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think that this mechanic, for example:
![Screenshot from 2020-04-27 12-14-34](https://user-images.githubusercontent.com/53530661/80361189-d214ee80-8880-11ea-8d11-4f71f0225d28.png)
_will_ be much smaller with this node. Note the large square around the signal-node: this, and 3 pairs of logic-nodes could be eliminated by crossing the relays with this junction.
**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Closing due to discontinuation of byte-logic.
