### ISSUE TITLE
Buff copper blocks a little bit

### ISSUE THREAD

**Issue by OmletteBoi** [Anuken/Mindustry-Suggestions#1253]
The copper blocks seem useless in defending, just buff it a little bit

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by genNAowl** [comment]
1. Do you mean copper wall?
2. It is the first wall you unlock, so its meant to suck

**Comment by notrealn** [comment]
thats like saying "buff leather armor in minecraft"
if you want better blocks, use titanium or smth

**Comment by itcannotbe** [comment]
OP be like: But I only have access to copper right now
Community: Git Gud.

**Comment by DeltaNedas** [comment]
also use the template you skrub

**Comment by Bohaska** [comment]
> The copper blocks seem useless in defending, just buff it a little bit
> 
> **Describe the changes you want to propose. Include possible alternatives.**

I feel like titanium needs to be buffed, it isn't much better then copper...
