### ISSUE TITLE
New command center feature

### ISSUE THREAD

**Issue by OmletteBoi** [Anuken/Mindustry-Suggestions#1254]
The command center isn't really a command center anymore, should be a feature that makes the boys patrol around the core, you know, for the people who don't know what the logic processors do, and also you should remove some blocks for the multiplayer that seems to be scuffed as frick

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RouterChainsSuckk** [comment]
You checked none of the boxes.....

**Comment by itcannotbe** [comment]
Actually he borked the template before not marking any of the boxes.

Why do people not read again?

**Comment by OmletteBoi** [comment]
> You checked none of the boxes.....

I'm new so no

**Comment by Bohaska** [comment]
"also you should remove some blocks for the multiplayer that seems to be scuffed as frick"
Elaborate.
