### ISSUE TITLE
better plasterium convayor support with routers

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry-Suggestions#1255]
**Describe what you would like changed, and why.**
#629 exists.
make past conveyors not get slowed down passing thru a router

**Describe the changes you want to propose. Include possible alternatives.**
make conveyors hold 10 of 1 type of item.

**Comment by D-player1** [comment]
> make past conveyors not get slowed down passing thru a router

That's not how you use it

> make conveyors hold 10 of 1 type of item.

Already is

**Comment by notrealn** [comment]
bruh the creator of plast conveyors said that they arent supposed to be a direct "upgrade like titanium is for a normal conveyor "
that is intentional

**Comment by itcannotbe** [comment]
What is a **plasterium convayor** and why I can't find it in game?

**Comment by DeltaNedas** [comment]
use plasterium ratour from daltenudes/ratoereo
