### ISSUE TITLE
Beta & Gamma Idling

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1256]
I made an idea a while ago and decided to update it to make it more balanced.
**Describe what you would like changed, and why.**
The two player ships known as beta and gamma can idle. When you control a unit or turret, beta/gamma will begin idling (beta wont move or do anything untill repossesed), if you decide to respawn at the core, the ship will fall and will be destroyed. Gamma on the other hand, will work the same way but will do things while idling (auro pilot); gamma will help the player build while also being able to be rallied (by a unit commander aka double clicking the unit to make a formation) and can also attack enemies while idling. 

Alpha will stay the same way it is now.

**Describe the changes you want to propose. Include possible alternatives.**

I see no possible alternatives

**Comment by genNAowl** [comment]
![bruh](https://user-images.githubusercontent.com/68400583/99619920-5378cd80-29d9-11eb-8688-a1dcd2fc31df.jpg)
Why would you make two issues about the same thing?
