### ISSUE TITLE
A keybind to respawn

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1257]
**Describe what you would like changed, and why.**
A keybind to respawn on pc and maybe a button somewhere on mobile. This would be helpfull when your done using a turret and you have to scroll back to your core to respawn to build again and stuff

**Describe the changes you want to propose. Include possible alternatives.**

I see no possible alternatives

**Comment by D-player1** [comment]
Tap player icon on top left

**Comment by QmelZ** [comment]
press v on pc.

**Comment by scarf-generic** [comment]
> [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
lies. this is already something that exists in the game. a keybind for pc exists (its v or c or something i cant remember) and mobile, click on the status indicator on the top left of the screen (between where health and ammo are shown). close this.

**Comment by itcannotbe** [comment]
It doesn't exist in game........

![Screenshot_20201119_101825](https://user-images.githubusercontent.com/45280919/99612549-c1141080-2a50-11eb-962f-c37f62c83939.jpg)

**Comment by TheTrueForce** [comment]
@itcannotbe check that image again. The bind you're saying doesn't exist is the seventh from the top.

**Comment by sample-text-here** [comment]
> check that image again. The bind you're saying doesn't exist is the seventh from the top.

that moment when you couldn't tell it was sarcasm

**Comment by TheTrueForce** [comment]
I wasn't being sarcastic.
Alternatively, if you were pointing out sarcasm, no, if there was sarcasm in his post, it wasn't obvious. Inflection does not carry over text. I have to say this everywhere because apparently nobody else realises this. Can you tell this makes me incredibly salty? Because it does.
