### ISSUE TITLE
Poly & Mega Fire Extinguishing Systems

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1258]
**Describe the content or mechanics you are proposing.**
For the mega and poly to have a way to defuse fires. I think Polys should be able to fire water filled rockets while megas would just fire a thin strong fast beam of water. This would help take out fires since waves and tsunamis dont cut it sometimes. Also perhaps quad could have a water bomb?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would be nice as it is suggested all the time before the v6 update and its still not implemented.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by bsjohnson20** [comment]
If its been requested before v6 and still not in then why do you think it would be now?

**Comment by Arackulele** [comment]
but like wouldnt that remove the entire point of the unit, by adding weapons to them theyd be way too strong and if you replaced the weapons with water weaponry theyd loose their point of beig heaing units
