### ISSUE TITLE
 hope to add an infinite map mode to the map mode

### ISSUE THREAD

**Issue by NWYLZW** [Anuken/Mindustry-Suggestions#126]
1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

I hope to add an infinite map mode to the map mode, so that I can operate my own base for a long time.
Infinite map mode can be loaded in blocks, similar to MC.
Hope to get your adoption.
我希望在地图的模式中添加无限地图模式，这样的话就能很长时间的去经营一个自己的基地
无限地图模式可以采取区块的方式去加载，类似于mc的那种形式
希望得到你的采纳

**Comment by Katsute** [comment]
An infinite map would cause memory issues in the long run; the more factories and conveyors on the map, the more calculations that the game has to process.

**Comment by potatoisagender** [comment]
Me chilling with 32 gbs of RAM.

**Comment by RebornTrack970** [comment]
It would be awsome and if you dont have a high tech phone/pc dont play that map...

**Comment by Anuken** [comment]
This isn't going to happen.
