### ISSUE TITLE
Liquids affect buildings.

### ISSUE THREAD

**Issue by YourCommonBro** [Anuken/Mindustry-Suggestions#1261]
(Credit to LightningSniper200 from the Discord Server. My original idea was similar but this is the better version)
 Title. Buildings/tiles that have been recently soaked in say, water, should have a certain cooldown before they can be set on fire. Buildings/tiles soaked in oil should maybe spread fire quicker or take more damage from fire for a short period. Cryo could perhaps be a better version of the water effect and possibly(if it doesn't make it too powerful) cool down turrets it hits. And slag... idk make it set ground oil on fire or smth, I don't wanna make another Issue for the slag.

 Not only would it make pvp more dynamic and also further encourage use of the somewhat underrated wave and tsunami, but it would also "nerf" coalbombing. Currently, coal-bombing is a very cancerous tactic that is very hard to recover from. You either don't have enough resources to put out the fire(especially on maps where each team has 4 nuclei all clumped together) and you die, or you DO manage to put it out, but at that point you are way, waaaaaaaaayyyyyyy behind the other teams. Such unfair tactics that are hard to deal with if you haven't dealt with them could possibly turn players away from the pvp part of the game, atleast vanilla pvp, which should be the most fun and balanced in ANY game.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
This honestly, doesn't fit in Mindustry's theme.
