### ISSUE TITLE
Megas and retreating

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry-Suggestions#1263]
**Describe what you would like changed, and why.**

Megas do not retreat anywhere once they have no block to heal/nothing to defend the block from/nothing to defend themselves from. This has the following negative effects:

As allies, once megas finish healing everything, they start attacking every enemy block that's in their range. Assuming your base is at 100% health, megas will start attacking blocks in their range. Block by block, they destroy everything, approaching the heart of the enemy base more and more.
- This is dangerous. Suppose the enemy has a line of copper walls leading to a meltdown. Megas will attack the copper walls then jump straight into the meltdown's range and get killed. This wastes resources and production time, and megas are the most expensive T3 air. There is no way to spontaneously stop this from a far, and no way a player will be able to always watch for his dumb megas which have no instinct of self-preservation.
- This is a stupid AI behavior. They are made to defend, attacking only when controlled, to defend themselves, and as enemies in non-attack maps. Heck, they have RepairAI; they are made for repairing, not attack. Besides, all the other units can be spontaneously told to retreat to repair points at any time, with no need for manual control. But megas just suicide themselves... You'd expect the most expensive T3 air to be smarter than v5's repair drones. Yes, v5's repair drones, were smarter. I've never seen one deliberately jump into the enemy weapons and kill itself. Yes, previous repair drones were unable to attack; megas being able to attack is the sole reason why they suicide themselves using the current AI. The current AI should have been changed to account for megas being able to attack. Being able to do one extra thing compared to its v5 ancestors should not make megas dumber.

**Describe the changes you want to propose. Include possible alternatives.**

Make megas retreat to the nearest friendly block when they have no block to heal and no enemy turrets/units are shooting within the mega's healing range.

Alternatively allow the player to control megas (defender units) separately via the command center (which currently controls attack unit behavior).

**Comment by Wetelemon** [comment]
Maybe "green command center" controlling megas and stuff

**Comment by XxsuperdeadlysniperxX** [comment]
I wasn't able to make the megas heal themselves cuz i don't understand the logic and how the code even works
