### ISSUE TITLE
Complete footstep sound effect

### ISSUE THREAD

**Issue by Diegator04** [Anuken/Mindustry-Suggestions#1265]
**Describe what you would like changed, and why.**

In V6 there are footstep sounds for ground units when they step in water. For this reason I would like a more sound effects.

**Describe the changes you want to propose. Include possible alternatives.**
I propose to add for every type of terrain (snow, stone, dacite and other ones...) a sound effect.
I've already done some examples and if it will be approved, I'll be happy to give some help.

_NOTE: The file is only an example and it **doesn't represent** the final sound and it will changed and improved in the time by me based on **external suggestions**._

**Here is the file:**[test_alpha.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5568435/test_alpha.zip)

**Comment by Anuken** [comment]
Similar: #1145

The problem with footstep sounds is that I don't know of a way to dynamically handle many of them at once. ~20 units are all shooting at one target all at once is already a mess; playing footstep sounds every time a unit moves would be even worse.

I am aware that some advanced audio frameworks handle this by reducing overall volume of loud sounds (dynamic range compression?), but I'm not sure how to implement that in the current framework.

**Comment by Diegator04** [comment]
> Similar: #1145
> 
> The problem with footstep sounds is that I don't know of a way to dynamically handle many of them at once. ~20 units are all shooting at one target all at once is already a mess; playing footstep sounds every time a unit moves would be even worse.
> 
> I am aware that some advanced audio frameworks handle this by reducing overall volume of loud sounds (dynamic range compression?), but I'm not sure how to implement that in the current framework.

I've noticed that problem and another person reported it with sound of fire. What's the current  framework?
