### ISSUE TITLE
The Interplanetary Accelerator.

### ISSUE THREAD

**Issue by Cobbet2** [Anuken/Mindustry-Suggestions#1267]
I know v6 is still not finished, and the Interplanetary Accelerator was introduced only today, but it's still too easy to build and maintain.

My idea is to make it hard to build and use it. So, it should require way more resources to build so maybe you even have to launch resources from other sectors and build large storages, as well as maybe use some incendiary resources, or even tar (AKA fuel, but it's just an example). Lastly, it should use a LOT of power (maybe even up to 50k per sec or even more), so you have to make giant powerplants, ultimately making this the endgame challenge. (And, after all, this is a electromagnetic railgun)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
better suggestion
require pylons to be built on every pentagon

**Comment by Legomonster33** [comment]
> better suggestion
> require pylons to be built on every pentagon

YES

**Comment by Cobbet2** [comment]
*Well it not as early in development, but I think this should be done before the original release. Also, many people are wondering if it's compatible with mods.

**Comment by QmelZ** [comment]
why shouldn't it be compatible with mods?

**Comment by Cobbet2** [comment]
> why shouldn't it be compatible with mods?

Nobody thinks it should be, I'm asking will you be able to use it in mods, for example create modded planets, etc.

**Comment by DeltaNedas** [comment]
you can already create planets, why do you think anuke is adding this
he stated before that he will only focus on one planet

**Comment by DeltaNedas** [comment]
it appears that I'm wrong, there's a commented second planet.

**Comment by Bohaska** [comment]
Yea, Anuke added a file called TantrosPlanetGenerator to the source code.

**Comment by QmelZ** [comment]
> > why shouldn't it be compatible with mods?
> 
> Nobody thinks it shouldn't be, I'm asking will you be able to use it in mods, for example create modded planets, etc.

sorry, my english is pretty bad. i meant "why wouldn't it be compatible with mods". you already can make planets with mods.
