### ISSUE TITLE
Naval Support Submarines

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1268]
![image](https://user-images.githubusercontent.com/54417042/99741899-44108780-2aa0-11eb-8e4f-6c0aa6e822ff.png)

All submarines go undetected by enemy units, like shock mines until they are "detected" (aka they do something / get hit). they can also control any units, not just other naval units.

t1 = nearby units go 50% faster, 5 block range, 6 command limit.
costs 
50 silicon
30 plastanium
25 thorium
20 metaglass
10 phase fabric

t2 = nearby units shoot 50% faster, 10 block range, 8 command limit.
t3 = nearby units have 50% more range, 10 block range, 10 command limit.
t4 = nearby units have a stealth cloak hiding them until they shoot, 15 block range, 12 command limit.
t5 = nearby units shoot and move 100% faster + any damage is redirected to the t5 sub (like a force projector but it absorbs all damage directly into the unit), 15 block range 16 command limit.

[X] here is an "X" in a box

**Comment by scarf-generic** [comment]
Hmm a mix of 2 ideas that everybody has suggested

**Comment by Legomonster33** [comment]
> Hmm a mix of 2 ideas that everybody has suggested

kinda yeah, but with a smol amount of my own 3rd ideas

**Comment by scarf-generic** [comment]
> kinda yeah, but with a smol amount of my own 3rd ideas

Whats the 3rd idea? Unit overdrives and naval support/submarines have already been suggested, just not mixed together.

**Comment by Legomonster33** [comment]
> > kinda yeah, but with a smol amount of my own 3rd ideas
> 
> Whats the 3rd idea? Unit overdrives and naval support/submarines have already been suggested, just not mixed together.


> All submarines go undetected by enemy units, like shock mines until they are "detected" (aka they do something / get hit).

**Comment by scarf-generic** [comment]
Submarines that "submerge" and dont take damage arent new. #690 is the first one ive come across, still searching though

**Comment by scarf-generic** [comment]
#550

**Comment by scarf-generic** [comment]
#69
(nice)

**Comment by scarf-generic** [comment]
#477

**Comment by scarf-generic** [comment]
Doesnt seem new. Although none specifically compared it to shock mines, its a near indentical concept.

**Comment by the-kido** [comment]
Today i had a dream anuke was adding support naval units. I woke up in disappointment

**Comment by Legomonster33** [comment]
> Today I woke up in disappointment

same

**Comment by scarf-generic** [comment]
> > Today I woke up in disappointment
> 
> same

Never said it was a bad idea, just that its been suggested before. Maybe it will get added, the cat did say that there would be more navals

**Comment by the-kido** [comment]
I suggest a change for the attack speed buff and range. Remember these are water units so the range should be 
T2: 25% Buff and 8 block range
T3: 35% Buff and 12 block range
T4: 35% Buff and 30 block range (the cloak thing is pretty good already)
T5: 75% Buff and 35 block range

To make t4 and t5 a bit more special: Like a repair point, they will heal units. For t4 they will heal full health in 20 seconds and for t5, 10 seconds.

Unrelated but your idea for the support navals are amazing.

**Comment by Bohaska** [comment]
<img width="407" alt="Screen Shot 2020-12-28 at 11 02 23 AM" src="https://user-images.githubusercontent.com/73286691/103186655-56ca7780-48fc-11eb-8153-cc8b9c9d4717.png">
