### ISSUE TITLE
Button that lets you skip waves in custom games. 

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1269]
**Describe the content or mechanics you are proposing.**
A button that lets you skip waves in sandbox (in attack mode with AI building, skipping waves also improves the enemy base)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When I play attack maps, sometimes I want to speed up the enemy's AI so that it builds faster or go to a certain wave in a certain map. If this wouldn't be added to the main game, can someone at least make a mod?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [ ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
quick fyi, this is under the "few things you shouldnt suggest" category

**Comment by Legomonster33** [comment]
> quick fyi, this is under the "few things you shouldnt suggest" category

notice they didn't check the box saying that it isn't in the `README.md`

**Comment by GlennFolker** [comment]
> FAILURE TO DO SO MAY RESULT IN YOUR REQUEST BEING CLOSED AUTOMATICALLY

I noticed you didn't even read the simple `README.md` _in the root directory of this repository_. How is that thing so hard for you? What the hell is wrong with you? Close this.

**Comment by Bohaska** [comment]
I DID SAID THAT IF THAT IDEA IS REJECTED, THEN INSTEAD ADD A BUTTON THAT LETS YOU SKIP WAVES.

**Comment by Bohaska** [comment]
never mind I edited the suggestion review it.

**Comment by Bohaska** [comment]
> > quick fyi, this is under the "few things you shouldnt suggest" category
> 
> notice they didn't check the box saying that it isn't in the `README.md`

well, I was honest...

**Comment by Bohaska** [comment]
> > FAILURE TO DO SO MAY RESULT IN YOUR REQUEST BEING CLOSED AUTOMATICALLY
> 
> I noticed you didn't even read the simple `README.md` _in the root directory of this repository_. How is that thing so hard for you? What the hell is wrong with you? Close this.

easy there don't swear at strangers.

**Comment by Bohaska** [comment]
I'm gonna close this and make a new, identical issue... to start up discussion.
