### ISSUE TITLE
Ping for server listings.

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#127]
**Describe what you would like changed, and why.**
Have a ping number in the top right of server listing. This would make it easier to see which servers we shouldn't join (due to high latency).

**Describe the changes you want to propose. Include possible alternatives.**
Ping number in top right of server listing. This shouldn't be a burden on the client, as they already ping each server for the info/MOTD and player count anyways.

**Comment by potatoisagender** [comment]
I mean, you could just join the server...

**Comment by Katsute** [comment]
By that logic you could also join the server to see the map and player count. I'm just saying that if the client pings the server for that information, it might as well get the ping.

**Comment by potatoisagender** [comment]
True, true.

**Comment by Anuken** [comment]
Implemented.
