### ISSUE TITLE
Interplanetary Accelerator Multiplayer Use

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1270]
**Describe the content or mechanics you are proposing.**
Give the interplanetary accelerator a possible use in multiplayer. Assuming the "interplanetary accelerator builds shard cores" box is checked in the map editor (unchecked by default), allow players to build them, and make it build a shard core inside it. You need an oct to pick up this core from the building and to place it somewhere. Once the core is placed, it cannot be moved again.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More gameplay options for non-modded multiplayer. This would be probably the most balanced way of building a core in multiplayer, and would be an amazing feature for some servers. *The fact that this has to be enabled by the server and map makes it not harm campaign/current multiplayer at all. Thank you for reading!*

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
judging by the resource consumption, it makes nucleus cores instead of shards

**Comment by scarf-generic** [comment]
> judging by the resource consumption, it makes nucleus cores instead of shards (although shards wouldn't be as game-breaking)

Thats the idea. Its supposed to be as underpowered as possible, because another core is really really good.

**Comment by hadron13** [comment]
well, interplanetary accelerator is supposed to launch a core into another planet, and core is self replicating as the description says, so, this could be done with the core itself, replicate into the same sector, following the logic
