### ISSUE TITLE
Smooth Walls/Mergeable Walls (You prob dont want this)

### ISSUE THREAD

**Issue by FollowTheTrain-CJ** [Anuken/Mindustry-Suggestions#1271]
**Describe what you would like changed, and why.**
I found it sometimes very hmm... not good lookin for walls to be placed with in  blocks and with a border. I am pretty sure some ppl dislike this too so i want to have an option in menu for _Smooth/Merge Walls_ . It is completely personal preference for some people. Like the _Pixelated_ option.

**Describe the changes you want to propose. Include possible alternatives.**
Well the walls can merge with more than one wall horizontally or vertically adjacent to it. 
Since i am not an expert on mindustry texture,i cannot show you how it is exactly.
But here is my HIDEOUS drawing of the concept of this suggestion,i made it with canvas too so its very ugly that you might die if you see it. If you are offended by my drawing, dont kill me
https://prnt.sc/vmmfas

**Comment by scarf-generic** [comment]
Not too bad of an idea, maybe wouldnt look as awful as the solar panels. Heck, id use it.

**Comment by FollowTheTrain-CJ** [comment]
crap i found that it should be in features instead of feedback,i originally wanted to make it to change for everyone but not an optional feature,sorry for that yeesh
