### ISSUE TITLE
In router language make the logo "Mindustry" "Router" instead

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1273]
**Describe the content or mechanics you are proposing.**

The people of router may not understand what a mindustry is so it is important to respect their dialect and make mindustry router when router language is chosen. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Big funny!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
ahhh amazing suggestion lol, i wasn't expecting the router language to be added in the first place. it was just a joke pr

**Comment by Quezler** [comment]
it would probably just inflate the size of the compiled application & take up space in the precious spritemap 🤔

**Comment by QmelZ** [comment]
> it would probably just inflate the size of the compiled application & take up space in the precious spritemap 🤔

~~wdym "take up space" i don't think sprite map is something finite~~

**Comment by genNAowl** [comment]
No spritemap space is precious and its better to use as less as possible

**Comment by the-kido** [comment]
its been one day

sad router noises

**Comment by QmelZ** [comment]
> one day

i think you misspelled three
