### ISSUE TITLE
plastanium conveyor 2: electric boogaloo

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1274]
> **tldr** i am proposing to remove side unloading since it just looks and feels wrong, examples below:

i have spend a few days observing plastanium conveyors being used in the wild, and would like to make an adjustment.

the unloading dock tile just seems to cause more harm than good, and threading to much on bridge territory.

this suggestion is just to get some community votes, fully prepared to make a pr (or not) based on the response.

### exhibit A

- when having a mix of conveyor types going to the same block items can bleed into other lanes:

![Screen Shot 2020-11-20 at 17 00 10](https://user-images.githubusercontent.com/3179271/99821094-e0469700-2b51-11eb-851b-f8f2ad8f4e24.png)

### exhibit B

- using side unloading only makes sense in setups like these, but then often its split with routers:

![Screen Shot 2020-11-20 at 17 04 12](https://user-images.githubusercontent.com/3179271/99821574-8397ac00-2b52-11eb-8759-d7a17c239cbb.png)

### exhibit C

- they can hitchhike a conveyor going the other way (e.g. when making surge):

![Screen Shot 2020-11-20 at 17 06 39](https://user-images.githubusercontent.com/3179271/99821922-e721d980-2b52-11eb-9397-376a350b8b94.png)

### exhibit D

- it is just weird that this works:

![Screen Shot 2020-11-20 at 17 10 31](https://user-images.githubusercontent.com/3179271/99822326-5992b980-2b53-11eb-8e67-235800d984bb.png)

### exhibit C

- and this does not:

![Screen Shot 2020-11-20 at 17 11 05](https://user-images.githubusercontent.com/3179271/99822366-6b745c80-2b53-11eb-9638-e4de3f30eb74.png)

### exhibit D

- blending calculation suffers due to the side being in a quantum entangled state:

![Screen Shot 2020-11-20 at 17 12 47](https://user-images.githubusercontent.com/3179271/99822601-b2fae880-2b53-11eb-94c6-dcd59f0c4a0d.png)

### exhibit E

- unloading on just a side leaves for a weird feeling of it not being centered or making sense:

![Screen Shot 2020-11-20 at 17 14 06](https://user-images.githubusercontent.com/3179271/99822743-de7dd300-2b53-11eb-80c6-0a09a6abd05a.png)

### exhibit F

- sideloading at the back isn't causing any distress so that can perfectly stay the same for now:

![Screen Shot 2020-11-20 at 17 18 54](https://user-images.githubusercontent.com/3179271/99823347-914e3100-2b54-11eb-9795-2b27b34ab351.png)

> the roomba union supports these new work ethics since it lessens the strain on their rotational bearings 📜

**Comment by bsjohnson20** [comment]
They need buff... Why not have support for multiple items to be input into a roomba and also have them send all the time like normal Conveyor but can take in more items to fill the roombas more...

**Comment by bsjohnson20** [comment]
Plast is only slightly better than titanium :(

**Comment by itcannotbe** [comment]
> Plast is only slightly better than titanium :(

Can you shove 40 items per second through a titanium conveyor?

**Comment by scarf-generic** [comment]
> Plast is only slightly better than titanium :(

Yeah only 4 times better :(

**Comment by Quezler** [comment]
> They need buff... Why not have support for multiple items to be input into a roomba and also have them send all the time like normal Conveyor but can take in more items to fill the roombas more...

them not being able to carry different items was an intentional design choice i made when creating them.
this thread is just for deciding whether or not to keep allowing them to unload on both sides as well.
any other boost/nerf suggestions should ideally just be created in a thread of their own.

(since i want to focus the discussion & votes in here on this aspect alone)

**Comment by Legomonster33** [comment]
in my opinion side unloading greatly increases their usability, and removing it would be a direct nerf, to something that is already under/misused.

**Comment by Quezler** [comment]
> in my opinion side unloading greatly increases their usability, and removing it would be a direct nerf, to something that is already under/misused.

but it goes against the logic of how the other conveyors are used, and spawns a visual mess, if this happens to pass it is of course possible to look at ways to buff it again with something (speed/capacity/etc), but side unloading is just a clutter.

**Comment by hribik100** [comment]
> > They need buff... Why not have support for multiple items to be input into a roomba and also have them send all the time like normal Conveyor but can take in more items to fill the roombas more...
> 
> them not being able to carry different items was an intentional design choice i made when creating them.
> this thread is just for deciding whether or not to keep allowing them to unload on both sides as well.
> any other boost/nerf suggestions should ideally just be created in a thread of their own.
> 
> (since i want to focus the discussion & votes in here on this aspect alone)

If the exhibit C worked then it is good Idea that it will not send stuff on sides

**Comment by Legomonster33** [comment]
> > in my opinion side unloading greatly increases their usability, and removing it would be a direct nerf, to something that is already under/misused.
> 
> but it goes against the logic of how the other conveyors are used, and spawns a visual mess, if this happens to pass it is of course possible to look at ways to buff it again with something (speed/capacity/etc), but side unloading is just a clutter.

it goes against the logic of normal conveyors, but so does literally everything else about them, the visual spaghetti isnt great (would be cool if was fixed) but they are unique and useful in thier own ways,
For example a plastanium junction 
![image](https://user-images.githubusercontent.com/54417042/99826766-cba0d980-2b26-11eb-814b-28905bf810a1.png)

its bigger, but its a workaround you have to deal with when using the unique and tricky plast conveyors.

**Comment by Quezler** [comment]
> plastanium junction

i have already had some ideas for one, the most prominent one being a junction tile that happens when "1 of them points away from a T junction", and it would only allow the roomba's to go straight over it, but only if the tile on the other side can receive in order to prevent deadlocking it, but its still on the drawing board, sideloading is currently the top priority 🔪

**Comment by DeltaNedas** [comment]
side-exporting is fine
quantum blending is not.

**Comment by Quezler** [comment]
the latter is caused by the first

**Comment by BlueWolf3682** [comment]
id suggest keeping it as is. after all, you are trying to use plast conveyors to spite bridges and i find this relation to bridge outputs to be a great irony

**Comment by JamesTheNerd** [comment]
If this is added, there would need to be a way to stay able to unload quickly into blocks that don't unload instantly i.e. routers conveyors and stuff.

**Comment by genNAowl** [comment]
~~Why do I feel like you told a server to upvote this~~

**Comment by hribik100** [comment]
> ~Why do I feel like you told a server to upvote this~

Because if he thinks it is major change he pings his server so your feeling right (I started discuss here because of that)

**Comment by BlueWolf3682** [comment]
![B88690A6-46B5-4024-B9F0-DBC1E3C133E6](https://user-images.githubusercontent.com/61173114/99892139-068e3480-2c2f-11eb-8901-382f888087d5.png)
with exceeding annoyance, yes

**Comment by Quezler** [comment]
owo

**Comment by braainsiogame** [comment]
go ahead, mr. quezler

**Comment by Quezler** [comment]
> go ahead, mr. quezler

the gears in my head are turning 🍿

**Comment by HaphLife** [comment]
The trouble with plastanium conveyors is that unloading resources from them all around sucks. when unloading to conveyors/junctions/over(and under)flow/sorters(and inverted) it, for some godawful reason does it one at a time. This shoots the 40 items/sec straight in the foot, and leaves you with roughly 15/sec. 

To try and fix it, they did this silliness with unloading. But it doesn’t fix it. It makes everything a bulky mess, except dumping to the core.

Honestly, plastanium conveyors should not break up packaged roombas when interacting with routers/overflow/sorter (maybe junctions too?). Instead the routers/overflow/sorter should just take the whole roomba, and happily plop it on another plastanium conveyor, just as it was, with no funky delay.

Of course a router/overflow/sorter with a roomba inside shouldn’t be able to output to anything other than another router/overflow/sorter, or a plastanium conveyor, that way the code is simpler, and plastanium conveyors are still not a direct upgrade.

If we could split plastanium conveyors like this, it would make them suck much less, and this funky monkey business with wacko new unloading rules not needed.

**Comment by itcannotbe** [comment]
Plastanium conveyors are meant to be dumped into something that had a large storage.

**Comment by HaphLife** [comment]
> Plastanium conveyors are meant to be dumped into something that had a large storage.

That’s the only thing they are usable for, but I don’t know that that that’s the only thing they’re meant for.

**Comment by TNT331** [comment]
@Legomonster33 use inverse sorter, instead of junction.

**Comment by TNT331** [comment]
plast conveyor is only good at moving resources and nothing else, it does not give a steady output. When you have mass drivers, who needs platinum conveyor to transport items.

**Comment by Anuken** [comment]
:eyes:
