### ISSUE TITLE
Add a small block that does the described

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1277]
Plz add a block that is survival and attack specific that redirects enemies that are parallel to the block and slow enemies coming straight at it and make it unable to be shot at and put a limit on how close you can place the block next to itself in a radius

This will help people get a defense ready on harder maps so they have somewhat of a chance actually defending

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
Anuke you do what you will with this suggestion i just want to provide an idea that hasn't been provided yet

**Comment by Legomonster33** [comment]
> Anuke you do what you will with this suggestion i just want to provide an idea that hasn't been provided yet

bruh did you even read https://github.com/Anuken/Mindustry-Suggestions

**Comment by Legomonster33** [comment]
if he likes your suggestions (likely not), he will implement it.

**Comment by XxsuperdeadlysniperxX** [comment]
> > Anuke you do what you will with this suggestion i just want to provide an idea that hasn't been provided yet
> 
> bruh did you even read https://github.com/Anuken/Mindustry-Suggestions

Yes i have and didn't see a single suggestion like the one i have introduced

**Comment by XxsuperdeadlysniperxX** [comment]
> if he likes your suggestions (likely not), he will implement it.

Well i just provided the suggestion and he just do what ever he was wants if he doesn't do it this version he mostly likely will do it in the next who knows ya know?

**Comment by Legomonster33** [comment]
> > > Anuke you do what you will with this suggestion i just want to provide an idea that hasn't been provided yet
> > 
> > 
> > bruh did you even read https://github.com/Anuken/Mindustry-Suggestions
> 
> Yes i have and didn't see a single suggestion like the one i have introduced

I was meaning about the comment where you were asking him to tell you if he saw your suggestions

**Comment by XxsuperdeadlysniperxX** [comment]
I wasn't asking him if he looks at my suggestion i already know he does i meant with the comment is he can customize the idea to a point where its useful yet not op

**Comment by XxsuperdeadlysniperxX** [comment]
At this point he definitely saw my suggestion issue closed
