### ISSUE TITLE
Simmilarily to to core dropping "cutscene" add a "cutscene" for the core being launched.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1278]
would be pretty epic

X[]X <- this is a box in some "X"s

**Comment by 5382Ander2** [comment]
I agree

**Comment by QmelZ** [comment]
what is with you and the boxes, and x'es

**Comment by Legomonster33** [comment]
> what is with you and the boxes, and x'es

part of the original format wants an x in a box
so i put some boxes and xs together

**Comment by QmelZ** [comment]
> > what is with you and the boxes, and x'es
> 
> part of the original format wants an x in a box
> so i put some boxes and xs together

cant you just put the x normally and continue lol

**Comment by YellOw139** [comment]
> cant you just put the x normally and continue lol

He can't press X. There is no doubt.
