### ISSUE TITLE
Command Center Modification

### ISSUE THREAD

**Issue by 5382Ander2** [Anuken/Mindustry-Suggestions#1279]
**Describe the content or mechanics you are proposing.**
Command Center has **Attack**, **Rally** and *Idle**
I want:
 **Move to**
**Patrol**
And separate command centers for air ground and naval (or one that is configurable)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would be nice to have that. You would not be forced to build 10000000 command centers to relocate units, or use logic to do that. Sperate command centers would be great too!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
(I found one, but that guy broke the template, and he wants patrol feature only)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
just use anuke logic you skrub

**Comment by Legomonster33** [comment]
patrol would be good, but `move to` doesnt make much sense

**Comment by antonilol** [comment]
or that you can set the rally point to another position, not just the position of the command center

**Comment by Xuhybrid** [comment]
"Separate command centers for air ground and naval (or one that is configurable)."
100% yes
