### ISSUE TITLE
have a priority system for parallaxes

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1281]
parallaxes right now, don't always try to pull the same unit, making them useless against a large amount of "big" units,
I propose having them prioritize units based on how many other parallaxes are targetting that unit, such that they will all focus on 1 unit.

**[X]** <- Obligatory X In A Box

**Comment by JamesTheNerd** [comment]
Good idea

**Comment by sample-text-here** [comment]
i think a round-robin system would be nice. each parallax targets the unit with the least number of other parallaxes targeting it. (sorting by distance if multiple have the same number of targeters)

so if you have 5 parallaxes and 2 units then 1 unit would be targeted by 2 parallaxes and the other by 3

**Comment by Legomonster33** [comment]
> i think a round-robin system would be nice. each parallax targets the unit with the least number of other parallaxes targeting it. (sorting by distance if multiple have the same number of targeters)
> 
> so if you have 5 parallaxes and 2 units then 1 unit would be targeted by 2 parallaxes and the other by 3

That would make them even more useless, typically you want the all to target the same unit not have them all be targeting diffirent ones

**Comment by sample-text-here** [comment]
> That would make them even more useless, typically you want the all to target the same unit not have them all be targeting diffirent ones

i think it would be more useful. parallaxes are mainly for flares or horizons so targeting as many different units as possible would be good

the best option would be to be able to use logic with them

**Comment by Legomonster33** [comment]
> > That would make them even more useless, typically you want the all to target the same unit not have them all be targeting diffirent ones
> 
> i think it would be more useful. parallaxes are mainly for flares or horizons so targeting as many different units as possible would be good
> 
> the best option would be to be able to use logic with them

i personally use them to pull bigger units closer to my fuses, which dont have any troubles dealing with small units
