### ISSUE TITLE
Allow parallax to be controlled by logic, and target units of its own team

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1282]
**Describe the content or mechanics you are proposing.**
Currently, parallax cannot be controlled by logic. What i propose is a special type of `control` block that similar to `radar` lets you change which unit is targeted. No shootx/shooty, just choosing which unit is targeted. With this, you could make custom ai for parallaxes and make them pull units of their own team. When pulling a unit of its own team, damage is nonexistant or heavily reduced.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would allow for more gameplay options with logic without changing any current mechanics. More strategy, more logic options, no real downsides to adding this as far as i can tell. Thank you for reading.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Legomonster33** [comment]
logic powered unit yeeting

**Comment by sample-text-here** [comment]
logic powered zenith railgun

**Comment by JamesTheNerd** [comment]
Logic powered eclipse hyperloop
Please add

**Comment by Violet-Scarelli** [comment]
logic unit yeeting sounds just fine to me, please add-

**Comment by QmelZ** [comment]
yay logic powered oct yeeters

**Comment by DeltaNedas** [comment]
shootp = lock onto unit
shoot = move unit to here
