### ISSUE TITLE
Campaign: choose which sector to launch from

### ISSUE THREAD

**Issue by 19lamanna** [Anuken/Mindustry-Suggestions#1283]
**Describe what you would like changed, and why.**
Currently, when launching to another sector in the campaign, the game automatically selects the closest sector to launch from.

For instance, if I want to launch from tar fields to sector 75, the game instead chooses ruinous shores as the "launch base".

This lack of choice often forces the player to launch from resource bare sectors, which leads to a tedious "resource forwarding" playstyles. 

**Describe the changes you want to propose. Include possible alternatives.**
Allow the player to launch from the sector they are currently on, rather than automatically selecting the closest. Also, the menu can be modified to allow this.

**Comment by Legomonster33** [comment]
this was a feature, was very op, was removed

**Comment by Legomonster33** [comment]
i suggest removing launchpads, as they are the only reason that "resource-forwarding" is possible (one of the most op+broken things)

**Comment by 19lamanna** [comment]
What would happen if the player was forced to launch from a sector without
coal?

**Comment by Legomonster33** [comment]
> What would happen if the player was forced to launch from a sector without coal?

the same thing that happens on ground zero, you play the sector without coal.

**Comment by 19lamanna** [comment]
Fair point. But the scenarios are different in other low-resource sectors,
as they can have different difficulty levels that could crush the sector
before it has the chance to build up properly (also neighboring attack
sectors keep up the pressure)

**Comment by Legomonster33** [comment]
so you mean varying sector difficulty, based on the resources it has?
thats a **good** thing.

**Comment by 19lamanna** [comment]
I would normally agree with you. Cases like Salt Flats pose a fun
challenge, but I feel that that sector's balance was not achived in the
others sectors (even worse resources like no coal and greater challenges).
However, since I do not know the game as much as others, I guess it is not
my place to comment.

**Comment by Legomonster33** [comment]
> I guess it is not
my place to comment.

never **ever** say this, no matter your opinion or your experience level your thoughts are valid

**Comment by 19lamanna** [comment]
In that case, I will elaborate further regarding my opinion of launch pads
and sectors. I feel that launch pads are absolutely necessary for the
current game, but could definitely be phased out or rebalanced later in
development.

For instance eradication level sectors like 200 or 202 are unbalanced as
standalone experiences, and need rebalancing, or support from other
conquered sectors. I feel this way because their resources are equal in
tier to that of salt flat's but have a far higher difficulty level and
danger of sustained re-invasion from neighboring attack sectors.

Also, there are the no-coal sectors I mentioned before, which I feel are
more appropriate as tutorial sections, rather than later game challenges. Like
before, I also feel that they currently need support from conquered sectors. I
feel that some sectors like these could be engineered into a fun (and
isolated) experience like salt flats, but are hindered by the unending
pressure of neighboring attack sectors.

My final words regarding a way address launch pads would be to replace them
with instant sector-to-sector transfer, and with tangent sectors only. I
feel this would promote a better form of exploring, as the player would put
more attention into the sectors as becoming "resource highways", rather
than relying on "touch and go" playstyles, or ignoring them altogether.

**Comment by BlueWolf3682** [comment]
uh, im pretty sure that by resuming a sector and then selecting the one you want to launch to makes the launch happen from the sector you are in

**Comment by 19lamanna** [comment]
It was that way up until now:

**Comment by 19lamanna** [comment]
I just realized that all sectors say 'resume' regardless of whether or not
that is your active sector. But take my word that tar fields was my active
sector at the time...
