### ISSUE TITLE
Server Force download mod

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#1284]
**Describe the content or mechanics you are proposing.**

Servers can force download (send the mods to the client from the server) in order to join

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Like a required texture pack or custom units

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Idk about forcing them to download stuff. That's sketchy af. Maybe a prompt that shows a list of required mods and the user can pick if they want the server to send them those mods or not to connect?

**Comment by sample-text-here** [comment]
> Idk about forcing them to download stuff. That's sketchy af. Maybe a prompt that shows a list of required mods and the user can pick if they want the server to send them those mods or not to connect?

I think that’s what they meant. When you try to join it should say “this server requires mods a, b, and c. click to download”

**Comment by QmelZ** [comment]
> > Idk about forcing them to download stuff. That's sketchy af. Maybe a prompt that shows a list of required mods and the user can pick if they want the server to send them those mods or not to connect?
> 
> I think that’s what they meant. When you try to join it should say “this server requires mods a, b, and c. click to download”

yeah, adding the "click to download" part would be amazing

**Comment by DeltaNedas** [comment]
why have the server waste precious bandwidth when it can say install deltanedas/routorio and gdeft/please pls

**Comment by QmelZ** [comment]
> why have the server waste precious bandwidth when it can say install deltanedas/routorio and gdeft/please pls

server will just supply the github username/modname and the client can use that to install the mods with one click
