### ISSUE TITLE
Have Commanded units go in rings/tiers, instead of one big hoop

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1285]
similar to the structure of atoms.
(rotation is optional)
![image](https://user-images.githubusercontent.com/54417042/99871331-66d99380-2ba7-11eb-855c-aad6f7a7e251.png)

**[x]** the "x" has been successfully enslaved

**Comment by BlueWolf3682** [comment]
this has the smell of already suggested

**Comment by Legomonster33** [comment]
> this has the smell of already suggested

I don't remember seeing it, but maybe it was idk

**Comment by YellOw139** [comment]
Having them constantly move could be annoying, but multiple rings would be nice.

**Comment by mwoehlke** [comment]
Wasn't this in v4?
