### ISSUE TITLE
Not having to capture a sector to research something in the Tech Tree

### ISSUE THREAD

**Issue by Blubvis725** [Anuken/Mindustry-Suggestions#1286]
For some technologies you have to capture a sector to research the tech. For some people (Including me) this can be annoying, because I don't like my sectors far away from each other. I like my sectors against each other, and not loose, it looks so messy. Hope this gets removed.

**Comment by Bohaska** [comment]
Make a mod for it (or ask someone else to do it). I am 99.99% sure that Anuke did this intentionally and will not implement your idea.

**Comment by Legomonster33** [comment]
This is intentional.
Although it would be nice if it were implemented in a less gameplay restrictive manner.
