### ISSUE TITLE
Shield HP of units should be included in the Total health part of the Wave editor graph

### ISSUE THREAD

**Issue by XxSpiritDuoxX** [Anuken/Mindustry-Suggestions#1287]
**Describe what you would like changed, and why.**

The "health" in the graph of the wave editor should have shield hp included as well

**Describe the changes you want to propose. Include possible alternatives.**

i would like for the "health" part of the waves in wave editor in maps to also include the shields as well,or to add new tabs to the wave editor graph relating to the "shield" hp of units

**Comment by 50275** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/965
