### ISSUE TITLE
more weather effects

### ISSUE THREAD

**Issue by arro423** [Anuken/Mindustry-Suggestions#1288]
**Describe the content or mechanics you are proposing.**
add more effects to weather

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

this will be a good thing and a bad thing on both sides (attacking and defending) like rain making most ground units slippery and sandstorm increasing the spread of all shots and moving air units slightly depending on there size

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 50275** [comment]
This has no positive effect on gameplay. It just makes mindustry more RNG based.
