### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by Vertix8** [Anuken/Mindustry-Suggestions#1289]
when I put pipelines sometimes message blocks are put fix this bug please

**Comment by Ruichka** [comment]
Wrong repo, report bugs [there](https://github.com/Anuken/Mindustry/issues)

**Comment by itcannotbe** [comment]
🎒 vs. 🐛

**Comment by Bohaska** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/875 + https://github.com/Anuken/Mindustry-Suggestions/issues/414 = https://github.com/Anuken/Mindustry-Suggestions/issues/1289

**Comment by XxsuperdeadlysniperxX** [comment]
Nice
