### ISSUE TITLE
Python logic system

### ISSUE THREAD

**Issue by blahblahbloopster** [Anuken/Mindustry-Suggestions#129]
Python is pretty beginner-friendly, and I think it would make a good logic system because it's also very powerful.  Maybe do i/o with variables, and sandbox it somehow?

It will make logic very easy, which will make gameplay much more interesting, such as allowing people to make backup power systems and automated resource prioritization (if there's more than x of it in the core and the defense is running low, direct it to the defense).

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
There is already a logic system being implemented. Also, why go through the trouble of incorporating a new language when most languages by default already have a good logic system? You kind of need a logic system to be a language...

Additionally,  implementing a second language on another isn't easy, and might require the installation of a few compilers.

**Comment by blahblahbloopster** [comment]
What's the logic system currently being implemented?  bytes-logic hasn't been updated in a while.

**Comment by potatoisagender** [comment]
no, there isn't one in place. It is being developed.

**Comment by IpProxyNeon** [comment]
I think this would be a great idea as Python is a common and simple language, and since it's fairly simple to use it would allow most people to make more complex mods then they would normally be able to woth normal hjson mods

**Comment by Anuken** [comment]
The logic system won't be using a programming language.
