### ISSUE TITLE
Boosters displayed on the block status panel.

### ISSUE THREAD

**Issue by Andraez** [Anuken/Mindustry-Suggestions#1290]
**Describe the content or mechanics you are proposing.**

When hovering your mouse over a tower, the status panel (where health, liquid, power, etc is listed,) will display current boosters applied to the tower, such as drills receiving water. It can have the indicator in the lower right corner, and say a "+256%" overlapping a water icon. The same goes with whatever it is drilling, or for oil/water extractors/cultivators, what tile it is placed on. It will also display any overdrive boosts. (+150%, +225%, +250%, you get the idea.)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Obvious reason for adding. I'd make this as a "balancing and feedback" issue, but really I am asking for a new feature to be added to something that already exists.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
its +156% though, x2.56
