### ISSUE TITLE
Thing like a datapack in minecraft

### ISSUE THREAD

**Issue by Mesokrix** [Anuken/Mindustry-Suggestions#1292]
**Describe the content or mechanics you are proposing.**
Make a thing like datapack in minecraft for mindustry for execute logic in background without logic block, you can make for exemple a new type of file (for exemple ".logic").

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
That can reduce lag and we don't need to have logic block on the map.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
...

**Comment by QmelZ** [comment]
^

**Comment by sample-text-here** [comment]
75 73 65 20 6D 6F 64 73

**Comment by QmelZ** [comment]
also ^

**Comment by Nhimanss** [comment]
try the mod system (added in v5)
