### ISSUE TITLE
[discord] make corebot autoreply to certain keywords in the discord

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#1293]
**Describe the content or mechanics you are proposing.**
Often, questions in #help go buried and unanswered, and it seems a lot of people don't read #faq or pins.
 
Thus, I suggest if certain keywords in a message are found, corebot will autoreply with a message/embed with more info.

(also while I'm here, corebot tells you to check out #servers in the join message but that doesn't exist anymore)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

![image](https://user-images.githubusercontent.com/45698812/99889550-2dd30a80-2c0b-11eb-8a4e-3207d4147747.png)
![image](https://user-images.githubusercontent.com/45698812/99889557-34618200-2c0b-11eb-910f-5afe40b491cf.png)

^ are worst two offenders but other stuff in faq pops up sometimes too

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
Some other features i think would be useful:
- "how to download 6.0" and "how do i download v6" would also reply with an embed or something (until v6 is released anyway)
- if 10 people react with a specific reaction to a core bot message, it gets deleted
