### ISSUE TITLE
Potential mender redeisgn

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#1294]
**Describe what you would like changed, and why.**
I doubt this will get added but I think it will be a intresting idea (for mods if not real game)

**Describe the changes you want to propose. Include possible alternatives.**
Basically instead of how menders currently work they will instead heal more  the closest blocks to them and the further away blocks are the less healed they get (to off set this basically nerf buff range and speed)

**Comment by QmelZ** [comment]
> basically nerf buff range and speed

what is a nerf buff?

**Comment by RogueRedHawk** [comment]
@QmelZ 

>>basically nerf buff range and speed

>what is a nerf buff?

I think they meant to say: "to offset the negative effects of this suggestion, which is basically a nerf, buff the range and speed."

**Comment by 50275** [comment]
So.... we have to put our menders directly behind our wall? Not a fan of this.
