### ISSUE TITLE
New turret with T5 Corvus shot.

### ISSUE THREAD

**Issue by firstcreator48** [Anuken/Mindustry-Suggestions#1295]
this idea was inspiring me so please anuke add this
it must have corvus-like blast that deals +65 dmg
0.3 shots per second and it does not heal blocks so that will never be op

**Comment by D-player1** [comment]
Anuke already stated that he won't add any more turrets

**Comment by genNAowl** [comment]
Please follow the template next time you make a suggestion

**Comment by 50275** [comment]
This is called... a meltdown.
