### ISSUE TITLE
Allow to rebuild derelict structures for 50~25% resources

### ISSUE THREAD

**Issue by DayTimer** [Anuken/Mindustry-Suggestions#1297]
**Description of the mechanic im purposing:**
Players should be able to rebuild derelict structures (and cores) for 50~25 % of their initial cost. (Rebuilding == constructing a building on top of an existing one)

**How would this impove the game:**
It will give some usage to derelict structures in campaign and custom maps. Because they are almost useless rn. Also it will give more options for mapmakers.

---
**I've placed some Xs in the brackets**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet (did not found anything similar).
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
ah yes the x's in the brackets

**Comment by Nhimanss** [comment]
cool idea
