### ISSUE TITLE
comon AI select modes + manual entity path find

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry-Suggestions#1298]
**Describe the content or mechanics you are proposing.**
a switch on all mechs (potentially they're factories) that sets the AI that they will use.
it may contain:

- normal/attack: common behavior
- rally: go to and stay at rally point
- retreat: common retreat behavior
- none: no behavior
- follow: follow closest thing
- go to: path find to a given area, return to last AI mode

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
l o g i c

**Comment by Nhimanss** [comment]
cool

**Comment by Nhimanss** [comment]
mabe it may be better to have a "bind to 1 mech only" option
