### ISSUE TITLE
more world UI logic blocks (pickers)

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry-Suggestions#1299]
**Describe the content or mechanics you are proposing.**
new logic blocks designed to interact with the world

- block picker block: allows player to pick a block in the world
- tile picker block: allows player to pick a location in the world
- tile marker block: marks a spot in the world
- block marker block: (optional) marks a block in the world

tile picker & marker blocks may use "shoot" data to communicate with logic

all these should be in the form of a block like how the switch is

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
for a script that uses a block that not a part of the schematic, it is useful to be able to pick the block from a GUI rather than connecting it to the processor, manually editing the schematic

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
mod

**Comment by Nhimanss** [comment]
?
