### ISSUE TITLE
Rebuild Drone

### ISSUE THREAD

**Issue by HiGHiKEY** [Anuken/Mindustry-Suggestions#13]
I am proposing the addition of a drone that will rebuild destroyed blocks for the player automatically, but at an additional cost.

One of the most frustrating things in the game right now is having to hunt down any blocks that have been destroyed by incoming waves, especially since it can be a single 1x1 block causing many systems to be disrupted. This drone would automatically find those destroyed blocks and replace them so the player does not have to do so manually. However, there would be an additional cost for each block replaced. The cost could be a simple multiplier, like double the resource cost for each block, or it could be a flat fee for each 1x1 block (so 4 times the cost for a 2x2, etc.), such as 5 titanium or something else that would be meaningfully expense so the drone isn't too OP. There could also be a multiplier for build time so that one drone can't rebuild the entire base between rounds. This would allow the player to spend more time focusing on the more fun parts of the game, such as building and designing, without taking away too much of the consequence of having enemies get past the player's defenses.

Aside from balancing, an additional hurdle to overcome would be figuring out a way for the drone to rebuild everything in the right order, as order can obviously have an impact on the functionality of the system.

1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Katsute** [comment]
Phantom Builder Drone already does this; do you want a balance change?

**Comment by ZkyLB** [comment]
already exists, so please take the knowledge pill

**Comment by HiGHiKEY** [comment]
I didn't realize the Phantom Builder Drone did this because they do not behave this way for me and it is not in the description of the drone. When I am on another area of the map and the location of the destroyed block is not visible, these drones just stay on me and follow me around.

**Comment by MEEPofFaith** [comment]
They have to be in your building range I believe, so just stay around the broken blocks.

btw, they don't rebuild Shock Mines and Thorium Reactors. (reason blah blah modding blah blocks.java)

**Comment by MEEPofFaith** [comment]
I believe they prioritize building over rebuilding, so just don't build anything while setting near destroyed blocks.

**Comment by TNT331** [comment]
I feel like phatom drones should have the setting of building, destroy and repair... cus sometimes all your econimy is down but you managed to suvive, there is no way you can build all the things back. In mulitiplayer, people just continue building and the drones take that as a higher prioty. dus to that the base slooly runs out of resorce and space...

**Comment by MEEPofFaith** [comment]
*Phantom drone version of command center why not*
