### ISSUE TITLE
Rotary pump is too OP?

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry-Suggestions#130]
**Describe what you would like changed, and why.**
I'd like to nerf rotary pump or buff thermal pump. Spanning 8 tiles and consuming 18 power, 2 rotary pumps output 96 liquid/s. Spanning 9 tiles and consuming 18 power, 1 thermal pump outputs only 90 liquid/s. Imo that's not enough for *the ultimate pump.*

**Describe the changes you want to propose. Include possible alternatives.**
Maybe make those pumps output the same amount of liquid per tile, like laser/airblast drills do?

**Comment by itcannotbe** [comment]
This is a variation of #82, but essentially similar.

**Comment by DS-3K** [comment]
Oh, I already issued this problem. I´m happy I´m getting some backup xD And
I would prefer the buff over the nerf, as in most cases, water extractors
are used instead of pumps anyway. Good luck with your suggestion!

Am Mi., 29. Apr. 2020 um 11:25 Uhr schrieb itcannotbe <
notifications@github.com>:

**Comment by itcannotbe** [comment]
For all intents and purposes. This issue should be closed in favor of the older issue.
