### ISSUE TITLE
campaign hexes have thicker red outline depending on difficulty

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1302]
**Describe the content or mechanics you are proposing.**
basically, the red outline that appears on an enemy base hex would e given a slightly thinner/thicker outline based on the difficulty level of the sector. ideally, its not too prevalent and the outline cannot get thin/thick enough to look visually displeasing.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
itll make the campaign map just a bit neater, and will let you see how difficult an enemy base is to defeat upon unlocking it before selecting it. it isnt much but it would be a nice little visual change.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
I think that enemy bases will have 'towns' on them. Easier ones will have 3d towns with smaller buildings, and harder ones will have bigger buildings.
