### ISSUE TITLE
Have core bot delete a map/schematic when the poster reacts with an :x: (or some other emote)

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1303]
it would be useful because sometimes you post the wrong schematic/map and cant remove it.

[X] <- this signifies my ability to have ~~good~~ ideas

**Comment by Bohaska** [comment]
- [X] This is not the place to make suggestions to the Mindustry discord
- [X] You are incapable of filling the template, but capable of deleting it.

**Comment by itcannotbe** [comment]
Unless there is a dedicated place to give suggestions relating to the discord, this place is the place for such suggestions.

**Comment by Legomonster33** [comment]
> * [x]  You are incapable of filling the template, but capable of deleting it.

I am capable of filling the template, my suggestions are just too brief for it to work.
