### ISSUE TITLE
Allow clients to access server ratelimits

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry-Suggestions#1304]
**Describe the content or mechanics you are proposing.**
Allow the client to access the `interactRateWindow` and `interactRateLimit` values from Administration.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would just be handy for custom clients, I want to add a  configuration queue to my client but theres no proper way to check whether or not you will hit a ratelimit at any given point.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Nhimanss** [comment]
interesting
