### ISSUE TITLE
Skip wave button for custom games

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1305]
**Describe the content or mechanics you are proposing.**
A button that lets you skip waves in custom games

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes, in attack maps, I want to skip some waves so the AI building makes a base I can attack. Sometimes, I want to test out late-game designs. Sometimes, I want to test a defense for defending against wave 1000.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

0. - [X] I have completed the checklist.
1. - [X] This is a duplicate, end of discussion. (https://github.com/Anuken/Mindustry-Suggestions/issues/1269)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` 
5. - [X] I am sure that my idea is **not** included under the "A few things you shouldn't suggest" category.

**Comment by buthed010203** [comment]
Just like you said, this is a dupe of the last request that you made which *multiple* people told you to close because it is in the dont suggest list... Just make a map in the editor and setup custom waves

**Comment by Bohaska** [comment]
> Just like you said, this is a dupe of the last request that you made which _multiple_ people told you to close because it is in the dont suggest list... Just make a map in the editor and setup custom waves

I changed it... now it isn't in the don't suggest list

**Comment by buthed010203** [comment]
Just use a custom map with hard waves if you want to test an endgame defence not to mention that the suggestion literally says "sometimes in attack maps, i want to speed up the ai building process".

**Comment by Bohaska** [comment]
> Just use a custom map with hard waves if you want to test an endgame defence not to mention that the suggestion literally says "sometimes in attack maps, i want to speed up the ai building process".
I will change it then.

**Comment by Bohaska** [comment]
Well, I have a (not similar) suggestion that will let me shut up about this, default maps with actual bases
