### ISSUE TITLE
Campaign:Reset sector

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#1306]
**Describe the content or mechanics you are proposing.**
Reset Sector to like it was just generated so you can retry the sector and try different stratifies

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more game play options or how it will fill a new niche.**

This could allow people to commit different stratifies or replay and see how they can improve

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
- [X] There are multiple duplicate suggestions of this. No use of making **another** one

**Comment by Legomonster33** [comment]
you can already do this by deleting the msav files. but an ingame method would be epic
