### ISSUE TITLE
Difficaulty Spike: Nuclear Production Complex

### ISSUE THREAD

**Issue by HTMLPhoton** [Anuken/Mindustry-Suggestions#1307]
The Problem with Nuclear Production Complex (NPC) is that it can be access before plastanium tech. In order to capture and hold it one must deal with an Guardian Antumbra and hordes of other enemies.
Against the Antumbra,  the best anti-air defense the player has is cryo-cooled thorium salvos (They grey team Specter will not fight for you unless you deconstruct and reconstruct it, which requires plastanium) Salvos, even with thorium ammo suffer from short range and relatively low damage output (further compounded by the fact that not a lot of salvos will be shooting at once) compared to plastanium-tech defenses (Swarmers Deleted the Arkyid on Overgrowth). Without an extremely overkill defense (4 layers of cryo+thorium salvos, with half a dozen Parallaxes mixed in) the Antumbra will punch a pretty big hole.
The Real danger is wave 41, Which punched a hole in even that overkill defense. and against any smaller defense, you can image what will happen. Really not much to say other than "It's kinda big"

The Solution to this would be quite simple, either make swarmers or plastanium compressors a prerequisite for Nuclear Production Complex, or warn the player that "Advanced defense technologies are highly advised, if not necessary." In big, red letters. The problem is in no part to the waves themselves, since they are quite adequately sized and a good preparation for what I image would come.

**Comment by 50275** [comment]
Bosses are supposed to deal more damage. Anyway, you really should need to build a lot of weapons to defend against bosses.

**Comment by HTMLPhoton** [comment]
The problem is not that the sector is hard, it's that it can be accessed when you are under-prepared by a long shot. which I would consider a regular wave smashing a hole in a 10+ blocks thick wall of the strongest turret you can unlock (due to sector limitations) with the strongest ammo it can fire to be a sign of. Now with the enemy bases moved it's even a bigger problem, since now with 4 enemy bases around it I would imagine NPC being sieged a lot. I can't image how a new player would hold onto NPC without plas tech.
Tar fields, which in the old campaign was basically NPC but easier, indirectly requires the player to have plas before entering, which NPC does not.
