### ISSUE TITLE
Plastanium Missing From Campain Tech Tree

### ISSUE THREAD

**Issue by HTMLPhoton** [Anuken/Mindustry-Suggestions#1308]
Plastanium Is missing from the Campain tech tree. It is not under titanium, thorium or oil. It is available in the core database however.

**Comment by sample-text-here** [comment]
1. bugs go in Anuken/Mindustry issues
2. it's not a bug, you need to complete campaign maps to unlock research

**Comment by GreyMario** [comment]
Mm, no, it _is_ a bug, in a sense. Plastanium doesn't appear in the tech tree; if it did, you'd find it [somewhere in the neighborhood of this section of the code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/TechTree.java#L564).

It could be equally valid to consider it a suggestion to add Plastanium to the tree in this location as it is to consider it a bug that it is missing, as other alloy compounds are present.

**Comment by QmelZ** [comment]
> Mm, no, it _is_ a bug, in a sense. Plastanium _as a resource_ doesn't appear in the tech tree; if it did, you'd find it [somewhere in the neighborhood of this section of the code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/TechTree.java#L564).
> 
> It could be equally valid to consider it a suggestion to add Plastanium to the tree in this location as it is to consider it a bug that it is missing, as other alloy compounds are present.

this, but i still suggest making a bug report.

**Comment by HTMLPhoton** [comment]
Ok, I've moved this Issue to Anuke/Mindustry/Issues. Time to close this one
