### ISSUE TITLE
A really helpful feature

### ISSUE THREAD

**Issue by LeChop** [Anuken/Mindustry-Suggestions#1309]
When the blocks break and you go in build mode they are lightly still visible (or something), it would be extremely helpful if there was an option to rebuild all destroyed blocks while building if there are any.

basically (rebuild destroyed blocks button)

This would help if a large portion of you base gets destroyed or a very complex machine and you know you have enough resources but it would literally be a giant time waste to fix manually especially without pause on multiplayer modes.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category. 
(I can't I'm using blue stacks)

**Comment by D-player1** [comment]
Just make poly, or you want them to be more useless?

**Comment by Cliftonz** [comment]
I would love this feature too.
I would equate this to the robots in Factorio fixing your walls or buildings when they are broken. Its a big time saver and something like that in this game would be great too. 
To be fair, I also think that if you are killed then you should not be able to automatically rebuild, just like how to ghost items disappear when you are killed and working to build something.

**Comment by hadron13** [comment]
> I would love this feature too.
> I would equate this to the robots in Factorio fixing your walls or buildings when they are broken. Its a big time saver and something like that in this game would be great too.
> To be fair, I also think that if you are killed then you should not be able to automatically rebuild, just like how to ghost items disappear when you are killed and working to build something.

There are polys already, they rebuild broken blocks

**Comment by LeChop** [comment]
There are polys already, they rebuild broken blocks

i know but a giant (FIX ALL) that you can use so you're able to fix things and decide what needs fixing first etc. 
not just a basic auto on some random blocks

**Comment by TimotheeMathieu** [comment]
I also agree that this feature would be great, when I play I spend a lot time rebuilding. 
There are a lot of times when you have to rebuild and you may not have polys at the moment, you may also want to reconstruct one part urgently... 
Polys are great to rebuild automatically as a maintenance type of thing but when you are under attack, they don't prioritize what I would prioritize and when they go down I loose a lot of time pausing to redo the whole thing as it was before.
