### ISSUE TITLE
Enemies not spawning at start of wave

### ISSUE THREAD

**Issue by KnowinglyUnknown** [Anuken/Mindustry-Suggestions#131]
Through this, you can launch before the wave of enemy comes

**Comment by DS-3K** [comment]
Before the wave timer hits 0, you have a good amount of time to leave.
Delaying waves would just offset everything instead of helping with
launching, I don´t see how that would be beneficial for any situation.

Am Mi., 29. Apr. 2020 um 15:42 Uhr schrieb KnowinglyUnknown <
notifications@github.com>:

**Comment by Anuken** [comment]
This doesn't make much sense.
