### ISSUE TITLE
Launchpad menu in map screen to choose launchpads in a sector to send resources to another sector

### ISSUE THREAD

**Issue by Junicari** [Anuken/Mindustry-Suggestions#1310]
As it currently stands, to make a launch pad in a sector send items to another sector you have to actually go into the sector as if playing on the sector to manually click the launch pad then click the sector you want to send resources to. I'm suggesting a UI in the map screen, maybe a drop down menu of the sectors with launchpads in order to choose which sectors to send items to without having to go into the sector and do it manually.

Quality of life improvement/ease of access. Also possibly a select all launchpads feature as well with the ability to choose which sector to send the items to in the map screen without manually going into each sector with launchpads to designate the sector to have them launch items to.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Legomonster33** [comment]
yis
