### ISSUE TITLE
Sectors too hard and a glitch

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry-Suggestions#1311]
**Describe what you would like changed, and why.**

I would like the sector waves to come at a slower pace and weaker, so when this glitch occurs, I can defeat it. the glitch is, when I leave and come back to the sector, it adds 20 more waves. is this intentional?

**Describe the changes you want to propose. Include possible alternatives.**
can you slow the waves or make them weaker, and remove the glitch that adds 20 more waves.

**Comment by Anuken** [comment]
That's not a glitch. Sectors are invaded by nearby bases.

**Comment by sample-text-here** [comment]
issue close speedrun anuke%

**Comment by DeltaNedas** [comment]
yes this is the glitch reporting repository
