### ISSUE TITLE
update the AI buildings and some habits.

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1312]
**Describe what you would like changed, and why.**
there are currently 4 big issues about the AI buildings (most should be easy to solve):
1. the AI buildings still follow the old 1 water extractor -> 2 steam gens rule. this causes all the steam gen based buildings to actually drain power instead of making some. the issue is worsened depending on how many steam gens an ai building uses. 
2. AI built unit factories can have their outputs clogged due to the automatic wall coating the AI does.
3. some power based defense buildings lack batteries, crippling their turrets (one example is the large solar panel + parallax building.
4. a few schematics which use drills and weapons as a defense will accidentally place drills over other resources, clogging the turret. one example is a fuse defense schematic that built its drills on a titanium deposit next to a lead one.

**Describe the changes you want to propose. Include possible alternatives.**
1. AI buildings should be updated to follow the new 1 water extractor -> 1 steam generator rule.
2. the AI should not leave a wall on the end of a reconstructor or unit conveyor.
3. batteries should be added to all AI defense schematics that include energy consuming turrets.
4. schematics that drill resources for defense should include sorters before turrets paired with solar powered incinerators to filter out unwated resources, or have better conditions that make sure they wont be drilling the incorrect resource.

**Comment by SteelBlue8** [comment]
This is largely because the AI schematics are made by people who are rather terrible at making schematics, most of them are bad- for example, one of the schems is SUPPOSED to be nothing to ripple but it's so unbelievably bad that they can only fire once every 30 seconds.

**Comment by Legomonster33** [comment]
another example of a bad schematic is one where 1 large solar panel (no batteries) is powering 4 arcs, which can only fire about once every 10-15 seconds.

**Comment by Catchears** [comment]
I can fix 1 and 3, 2 is done automatically (I think) so I won't fix that (although you could with enough java knowledge), and I would do 4 but the issue is that incinerators require 6 solar panels to work which is a bit expensive for a simple duo defence. I'll make a PR in the next few days for 1 and 3.

**Comment by Catchears** [comment]
See [this](https://github.com/Anuken/Mindustry/pull/3596) for my implementation of 1 and 3.
