### ISSUE TITLE
Docks for naval units

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry-Suggestions#1313]
**A water structure where ground units can walk and naval units can dock, being able to pickup the units**

**An alternative way to transport ground units across rivers and seas will be useful, specially with slow units like mace**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
- [X] This is good
- [X] But this will probably be added to a new class of support naval units, not omuras

**Comment by Bohaska** [comment]
- [X] This is good
- [X] But this will probably be added to a new class of support naval units, not omura's
