### ISSUE TITLE
The Omura and Sei should be able to hold units

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1314]
**Describe the content or mechanics you are proposing.**
The omura is supposedly a carrier ship since it makes drones so I think it should be able to hold them too. It would be able to hold as many drones as a quad can. The sei would be between the mega and quad in how much it can hold.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will give us an aircraft carrier. Also sei is kinda weird and non-unique.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
What's the point of carrying an unit that is faster than you

**Comment by hadron13** [comment]
I already suggest something like that #1313

**Comment by marky0470** [comment]
> What's the point of carrying an unit that is faster than you

For when there is a body of water units cant cross

**Comment by itcannotbe** [comment]
Air units that can carry other units be like:

Whut?
