### ISSUE TITLE
Coal bombing should be toggleable

### ISSUE THREAD

**Issue by SlavaCat118** [Anuken/Mindustry-Suggestions#1315]
**Describe what you would like changed, and why.**
Coal bombing should be able to be disabled by map creators. This would stop the people who mine coal in the first 10 seconds of a PvP game and go over to a core and bomb it.

**Describe the changes you want to propose. Include possible alternatives.**
Change: Have a toggleable option in the rules tab, similar to the fire option, that stops things like coal/pyratite/blast bombing.
This should be different from turning off fire because destroying coal plants actual strategy, while bombing is just plain stupid. 

Alternatives: Have only blast have the fire effect. Due to it being a more late game item, players would have the necessary defenses to combat it.

**Comment by D-player1** [comment]
RTF map editor

**Comment by D-player1** [comment]
You obviuosly didn't look at the environment settings

**Comment by scarf-generic** [comment]
plugins. also this feature should not be disabled, it is what makes some servers unique

**Comment by SlavaCat118** [comment]
> You obviuosly didn't look at the environment settings
![image](https://user-images.githubusercontent.com/71950453/100037379-39ffc900-2dbf-11eb-9273-f99fa0d3d37b.png)
If you are referring to these settings, yes I am aware of them and addressed that. I think that the block and unit explosions should be separated.

**Comment by DeltaNedas** [comment]
bruh core units cant coal bomb

**Comment by SlavaCat118** [comment]
> bruh core units cant coal bomb

I've tested on both v6 and v5, and all basic core units can coal bomb

**Comment by 50275** [comment]
The main issue is building in opponent bases here
Spam conveyors on their stuff and if they try to break it put a conveyor with coal to start a fire - this is V6 PVP unless you disable fires, but coal explodes too...
