### ISSUE TITLE
statements for LPL (logic processor language)

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry-Suggestions#1317]
**Describe the content or mechanics you are proposing.**
*C-like statements in LPL*
* while
* for
* if

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
*will be better to visualise and accelerate the development of mechanisms*
*jump if should be keeped so, the legacy code still working*

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
- [X] I am capable of filling boxes, but not actually doing any things mentioned in them.
#880

**Comment by Legomonster33** [comment]
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

clearly not, the 3 things you mentioned are very trivial to do with jumps

**Comment by hadron13** [comment]
> > 1. * [x]   I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> clearly not, the 3 things you mentioned are very trivial to do with jumps

I know it's possible, this visual assembly is almost turing complete, but still very easy to make the code be spaghetti and bad looking, almost impossible to read other's code

**Comment by hadron13** [comment]
this title was bad, the real thing I want is transform LPL in a structured language, with statements, functions, arrays, types etc

**Comment by GreyMario** [comment]
consider for a very brief moment that the language is Assembly-like for a reason

**Comment by Anuken** [comment]
> this visual assembly is almost turing complete

1. As it can branch and read/write memory, it **is** Turing complete.
2. I am **not** adding while/if/for statements. Jumps are enough. The language is designed to be as simple as possible; those constructors do not and should not apply.

**Comment by DeltaNedas** [comment]
help pls add while/if/else/for to nasm pls like in c
so use c

**Comment by vsmelov** [comment]
I thought about writing a primitive compiler from C-like language to LPL. But was too lazy to do that.
Reach me by email if you want to collaborate.
