### ISSUE TITLE
satellites

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1318]
**Describe the content or mechanics you are proposing.**

1. satellites should do *anything*
2. satellites should have some way to enter a sector (e.g. a space station interior map), planets should not be used for single-sector space stations
3. obj loader for meshes

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

satellite doesnt even add itself to planet.satellites h its that useless
making a space station shouldnt require ungodly hacks with planets

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.**
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. (extra bits for stations)
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ThatOneBepis** [comment]
Satelites are on trello, in the "future" category
i think it should be discussed when relevant

**Comment by lu-meiagui** [comment]
also add planet and solar systems and that objects can be transferred from one map to another

**Comment by lINSTINCTl** [comment]
Maybe in the future like V7

**Comment by lu-meiagui** [comment]
with that my idea of ​​the ´´portals´´ could be connected

**Comment by hadron13** [comment]
there is sattelites in the game code, but it's just a class and has nothing yet.

**Comment by lu-meiagui** [comment]
may also have a laser beam
