### ISSUE TITLE
Rescale liquid production and consumption.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#132]
**Describe what you would like changed, and why.**
Current production and consumption stats of blocks that require or produce liquids aren't that condusive enough to use pipes. Given the maximum throughput of liquid transport blocks are significantly huge compared to the needs of the block it doesn't make sense to keep them that way.

Do drive the point, here are the consumption/production rates of every block in mindustry.

Mechanical Pump: 6.0/s
Rotary Pump: 48.0/s
Thermal Pump: 90/s
Mechanical Drill: 3.0/s
Pneumatic Drill: 3.6/s
Laser Drill: 4.8/s
Airblast Drill: 6.0/s
Water Extractor: 7.8/s
Cultivator: 10.8/s*
Oil Extractor: 9.0/s In | 15.0/s Out
Steam Generator: 3.0/s
Differential Generator: 9.0/s
Thorium Reactor: 2.4/s
Impact Reactor: 15/s
Multi-Press: 6.0/s*
Plastanium Compressor: 15/s
Cryofluid Mixer: 12.0/s* In | 12.0/s* Out
Melter: 12.0/s*
Separator: 4.3/s*
Spore Press: 18.0/s*
Coal Centrifuge: 5.4/s*

**Describe the changes you want to propose. Include possible alternatives.**

Rescale it. Change the values around so that it would make sense to just use pipes

**Comment by DS-3K** [comment]
I agree with you
I guess it´s scaled for a situation like this:
-you require a lot of water
-you are low on power overflow
-there is a rather large body of water in a secure area nearby
Wich this situation is sadly rather rare.
Eventhough water extractors are pretty power expensive and inefficient the
pure lack of accessible water everywhere and the time needed to build
conduits and protect them doesnt add up to it.

Am Mi., 29. Apr. 2020 um 16:00 Uhr schrieb itcannotbe <
notifications@github.com>:

**Comment by itcannotbe** [comment]
Actually it was barely changed ever since we got past classic.

**Comment by itcannotbe** [comment]
Whoops

**Comment by potatoisagender** [comment]
usually one uses conduits when supplying water to cryo, or cryo to buildings. I think that conduits and pumps are going to become a lot more popular if the #28 suggestion is made.

**Comment by itcannotbe** [comment]
The backlash from it especially from one server owner is not necessarily to be taken lightly.

It's meta breaking. But the meta is meant to be broken. Power cubes are actually broken like the thermal generator of early v4.

**Comment by itcannotbe** [comment]
But this serves as an alternative to #28. It aims to increase the consumption rate of blocks since it's comically small compared to the maximum throughput of liquid transport blocks.

**Comment by potatoisagender** [comment]
one server owner?

Right. Maybe Anuke could create something like the mega factories some people have been talking about.

**Comment by itcannotbe** [comment]
How are "mega factories" hypothetically relevant to this suggestion?

**Comment by potatoisagender** [comment]
mega liquid production factories. E.g thicc cryo.

**Comment by itcannotbe** [comment]
Boxfort is not a map for sane people to play on. For all intents and purposes the map is a glorified playground resembling sandbox mode.

That being said. People still do power cubes there and/or slap water extractors on everything, even if the block in question is literally beside actual water.

Going back to the topic. There will be no incentive to not use water extractors because of the annoying fact that it's too convenient not to use akin to teleporters of classic.

**Comment by potatoisagender** [comment]
'There will be no incentive to not use water extractors because of the annoying fact that it's too convenient not to use akin to teleporters of classic.'

What?

'Consequently. Nerfing them to pointlessness would result to them being alike to thermal generators post nerf.'

So you would like to nerf water extractors. Okay. How does that change your original request? In fact, by nerfing water extractors, you get rid of the somewhat popular use of water extractors and pipes to feed large cryo networks.

**Comment by itcannotbe** [comment]
To point out that this maybe a good idea. Here is a list of production and/or consumption rates of the block currently in game:

Mechanical Pump: 6.0/s
Rotary Pump: 48.0/s
Thermal Pump: 90/s
Mechanical Drill: 3.0/s
Pneumatic Drill: 3.6/s
Laser Drill: 4.8/s
Airblast Drill: 6.0/s
Water Extractor: 7.8/s
Cultivator: 10.8/s*
Oil Extractor: 9.0/s In | 15.0/s Out
Steam Generator: 3.0/s
Differential Generator: 9.0/s
Thorium Reactor: 2.4/s
Impact Reactor: 15/s
Multi-Press: 6.0/s*
Plastanium Compressor: 15/s
Cryofluid Mixer: 12.0/s* In | 12.0/s* Out
Melter: 12.0/s*
Separator: 4.3/s*
Spore Press: 18.0/s*
Coal Centrifuge: 5.4/s*

**Comment by potatoisagender** [comment]
can you list the input/output ratio of the conduits?

**Comment by itcannotbe** [comment]
Per testing a conduit can handle around 10 rotary pumps, while the pulse/plated conduit can handle 10 thermal pumps

**Comment by potatoisagender** [comment]
Alrighty then, I guess I have to agree now, because I see where you are coming from.
