### ISSUE TITLE
´´portals´´

### ISSUE THREAD

**Issue by lu-meiagui** [Anuken/Mindustry-Suggestions#1320]
Hello, I would like you to add a block that can be connected between maps called portals that can transfer drones and units from one map to another.

1) would be created with:
2k copper
4k lead
3k silicon
3k graphite
2k titanium
1k metacrystal
500 electric alloy

2) to unlock it you have to complete ground zero.

3) you only have to make one and you have to choose the destination

that is my idea.

**Comment by lu-meiagui** [comment]
you can choose a better name for the block

**Comment by itcannotbe** [comment]
@lu-meiagui You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by lu-meiagui** [comment]
I didn't know what to wear

**Comment by scarf-generic** [comment]
> I didn't know what to wear

pants and a shirt probably. the template exists for a reason, try to follow it so that people actually look at the suggestion instead of complaining about the lack of template.

**Comment by itcannotbe** [comment]
If anyone actually understood the template, and read the "read me" file, they would realize that this suggestion is similar in nature to a teleporter cause it essentially "teleports" already made unit from other sectors.

Also what the hell is metacrystal and electric alloy?

**Comment by lu-meiagui** [comment]
is the metaglass and surge alloy

**Comment by lu-meiagui** [comment]
but what is special is that it is unlocked in ground zero and that it transports all units, large or small, to any part of the map

**Comment by lu-meiagui** [comment]
and no other portal is needed

**Comment by itcannotbe** [comment]
![image](https://user-images.githubusercontent.com/45280919/100181545-76453d80-2f15-11eb-89d6-52ed496dce0f.png)

**Comment by lu-meiagui** [comment]
says teleporters but doesn't say between maps

**Comment by lu-meiagui** [comment]
and if they add planets you can also.

but well it's just an idea

**Comment by Bohaska** [comment]
they have launch pads for this... you can always code in a new one it isn't that hard... and you can ask someone else to do it for you

**Comment by hadron13** [comment]
enemy units look that they are falling when they spawn, makes total sense launching from launch pads, no need for portals

**Comment by mwoehlke** [comment]
...and speaking of not filling out the template, this is very, very similar to #1236.

**Comment by lu-meiagui** [comment]
I called my project portals in quotes but it can be called something else, the similar project says that it launches them to the enemy's area in a wave but mine launches it anywhere on the map and helps you build and defend (launches to explored parts and enemy core).

**Comment by lu-meiagui** [comment]
Y puta la wuea solo es una puta idea malo que wevean con la wuea wueones culiados

**Comment by scarf-generic** [comment]
> Y puta la wuea solo es una puta idea malo que wevean con la wuea wueones culiados

nice
