### ISSUE TITLE
fix bombs dropped by units

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1321]
**Describe what you would like changed, and why.**
this video is self explanatory, essentially, units dropping bombs will cause far less damage if dropped directly onto a building vs close to it on the ground. i didnt record it but this behavior happens with all buildings, not just walls.

![ezgif-3-5f1f3299d1ff](https://user-images.githubusercontent.com/47570570/100169132-91fa0680-2e77-11eb-9dd0-5233159d2eda.gif)

**Describe the changes you want to propose. Include possible alternatives.**
updates to the code to make bomb droppings fair, im not sure how it is now but it should just be changed to prevent this if possible.

**Comment by D-player1** [comment]
That's because Quad's damage is spread, the first bomb hits more blocks, means that the damage is reduced, while the second bomb hit less blocks, causing more damage.
