### ISSUE TITLE
Bring Back Snake but with some nerfs

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1322]
**Describe the content or mechanics you are proposing.**
Allow for snakes to work, but have a throughput and speed limit.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
would allow for better use of sorters to sort things, the unique properties of snakes to be used, while also not being a complete replacement for every other transportation method.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
not this shit again

**Comment by GreyMario** [comment]
No. You just want your teleporter back.

It's because of people like you that we can't have a small group of weapons loaded by chained over and underflow gates to prioritize which ones get ammo.

**Comment by sample-text-here** [comment]
> No. You just want your teleporter back.

@GreyMario did you read the suggestion? they don't want infinite throughput. snek would be fine if there was a throughput limit

**Comment by Legomonster33** [comment]
> No. You just want your teleporter back.
> 
> It's because of people like you that we can't have a small group of weapons loaded by chained over and underflow gates to prioritize which ones get ammo.

i very specifically do not want an infinite range teleporter

**Comment by scarf-generic** [comment]
> > No. You just want your teleporter back.
> 
> @GreyMario did you read the suggestion? they don't want infinite throughput. snek would be fine if there was a throughput limit

It had a throughput limit at some point in development, then anuke removed it completely. This mindless argument wont solve anything, please stop. 6.0 releases in a couple days, anuke is not going to be adding this back.

**Comment by RedstonerKBC** [comment]
Keep talking, I'm just watching the show

**Comment by RedstonerKBC** [comment]
I don't get why over/underflow gates and sorters have insta-throughput? Why not delay the output like routers/junctions but they have the same output speed as they normally do? This makes it so sneaks 1) work as expected 2) aren't op teleporters.

**Comment by sample-text-here** [comment]
^^^^
yes someone gets it
just limit throughput and re-add snek

so designs still work but snek isn't op

**Comment by itcannotbe** [comment]
Here are the facts about flowgate-sorter chains:
1. There was a bug that allowed flowgates to process more than 1 item per tick in v5
2. The bug was fixed in v6, thus flowgates are now limited to 1 item per tick.
3. Anuke disabled flowgate-sorter chaining in v6 to prevent people from using flowgate-sorter chains.

**Comment by itcannotbe** [comment]
> I don't get why over/underflow gates and sorters have insta-throughput? Why not delay the output like routers/junctions but they have the same output speed as they normally do? This makes it so sneaks 1) work as expected 2) aren't op teleporters.

Sorters doesn't store items, flowgates does.
So technically, flowgates doesn't have insta throughput.

**Comment by D-player1** [comment]
Random comment

**Comment by Legomonster33** [comment]
> ^^^^
> yes someone gets it
> just limit throughput and re-add snek
> 
> so designs still work but snek isn't op

yes, that is literally what i want, not op but still useable

**Comment by scarf-generic** [comment]
how do i close somebody else's issue

**Comment by sample-text-here** [comment]
> how do i close somebody else's issue

why

**Comment by D-player1** [comment]
> > how do i close somebody else's issue
> 
> why
> 
> you still haven't given a good reason why this shouldn't exist

Do you want brainless noobs to spam snek even though it's already nerfed to death?

**Comment by scarf-generic** [comment]
> > how do i close somebody else's issue
> 
> why
> 
> you still haven't given a good reason why this shouldn't exist

this argument happened a long time ago. anuke already made his choice. nothing will change.

**Comment by scarf-generic** [comment]
setting records here

**Comment by scarf-generic** [comment]
at this rate the remove ru pull will have less comments by tomorrow

**Comment by sample-text-here** [comment]
> at this rate the remove ru pull will have less comments by tomorrow

forget about snek

i want to break records

**Comment by Legomonster33** [comment]
> > at this rate the remove ru pull will have less comments by tomorrow
> 
> forget about snek
> 
> i want to break records

yes of course, because why else would you do things lol

**Comment by Bohaska** [comment]
Seriously, nerfing sneks isn't even **that** hard... Most people who have a basic understanding of coding can do it...

**Comment by scarf-generic** [comment]
> Seriously, nerfing sneks isn't even **that** hard... Most people who have a basic understanding of coding can do it...

@Bohaska yes, and anuke did nerf them at some point (deltatime throughput from limitless to 60i/s). **a short while after this nerf, anuke decided to remove them completely**. this idea has already been tried, anuke didnt like it apparently.

**Comment by Legomonster33** [comment]
60i/s is still ridiclous, 10-15 would be better

**Comment by itcannotbe** [comment]
> 60i/s is still ridiclous, 10-15 would be better

Just so you know, routers and distributors are maxed at the same throughput.

**Comment by XEN0PHIL** [comment]
There's absolutely no scenario where you'd need snek instead of legit blocks

**Comment by Legomonster33** [comment]
> There's absolutely no scenario where you'd need snek instead of legit blocks

there is absolutely many scenarios
