### ISSUE TITLE
Contact Overdrive

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1323]
**Describe the content or mechanics you are proposing.**
Sometimes, there's just one or two buildings you want to boost. A whole overdrive field would be overkill at this point, because what you need is a scalpel, and using a field or dome would be like using a sledgehammer. So, I am proposing the Contact Overdrive, a 1x1 block that projects no field at all, but only provides a flat 115% boost to each block in direct contact. It can be boosted itself with phase like a full dome, but receives no range boost, only an additional 30%, for a max of 145% overdrive. 

Keep in mind these numbers are subject to change, but I feel that the contact overdrive would reside below the overdrive projector in terms of boost, but when boosted, would jump to be between the projector and the dome.

Importantly, contact overdrives cannot boost other contact overdrives. That would just be scary.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Having the ability to boost just one building would open up a lot of options for minimaxers, as well as people who just need to boost one or two things, or need to fill a gap. 

A few example scenarios it would be useful in:

- Increasing the output of a drill without imbalancing a nearby factory
- Increasing the load rate of a plast conveyor by overdriving the unloaders that feed it
- Increasing the throughput of a factory by selectively overdriving the feed lines while leaving the factory buildings themselves untouched
- Boosting a pair of mass drivers to increase throughput
- Increasing the DPS of a turret by placing a contact overdrive on it

In general, this idea would be the scalpel to the projector and dome's hammer. Boost just one or two things, to keep the whole machine running smoothly, or increase its output without changing how much power it's using.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Look mom, another unnecessary OP block that we should have!

**Comment by Violet-Scarelli** [comment]
> Look mom, another unnecessary OP block that we should have!

Again, it's not meant to be OP. You can't stack them, and boosting them is complicated and expensive.

**Comment by Legomonster33** [comment]
![image](https://user-images.githubusercontent.com/54417042/100183283-82e17b80-2eac-11eb-8d69-996b1846a426.png)

**Comment by Legomonster33** [comment]
would be highly epic

**Comment by itcannotbe** [comment]
Define "Complicated".

**Comment by Legomonster33** [comment]
> Define "Complicated".

they only boost the blocks they are touching, so you cant use them to overdrive large things, and they might take up valuable factory space

**Comment by itcannotbe** [comment]
For Reference: OD Dome only boost blocks up to + 150%

Yes this suggestion is OP as fuck.

**Comment by Violet-Scarelli** [comment]
Edited to reflect the comment that @itcannotbe made, I wasn't properly accounting for the fact that blocks operate at 100% normally, and was factoring that 100% in on accident.
