### ISSUE TITLE
la nueva barra que muestra los recursos que están en el núcleo 

### ISSUE THREAD

**Issue by Fryto012** [Anuken/Mindustry-Suggestions#1324]
mi sugerencia es que sea despegable se pueda esconder que este una flecha indicando que esta la barra, y, o que se pueda mover a los lados en la configuración del juego

**Comment by Bohaska** [comment]
你可不可以写英文？ 我不知道怎么读西班牙语，对不起。
Translate it yourself.

**Comment by Bohaska** [comment]
Also

- [X] 我不可以填写表格，可是我可以删去表格。

**Comment by Fryto012** [comment]
my suggestion is about
the new bar that shows the resources that are in the core
My suggestion is that it is removable, it can be hidden that there is an
arrow indicating that the bar is, and, or that it can be moved sideways in
the game settings.
I dont know English
I use a translator
sorry

I'm @fryto



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by hadron13** [comment]
template v:
