### ISSUE TITLE
IdkJavoos list of suggestions for mobile

### ISSUE THREAD

**Issue by ClockAndBallTorture** [Anuken/Mindustry-Suggestions#1325]
**Describe the content or mechanics you are proposing.**
Update mobile
New placeable unit for the water: Raft, lets you put stuff on it
More turret emotes for the discord (we don't have enough.)
A few extra ship upgrades (maybe a laser based?)
Impossible versions of a few maps (like it spawns a hard to kill enemy on wave 5 or smthn idk)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Update for mobile: dude, I'm still on basically beta..
Raft: water turrets
More emotes: why not?
Ship upgrades: we have like, 5 on mobile..
Impossible versions of maps: so we can have a challenge!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
> More emotes: why not?

![image](https://user-images.githubusercontent.com/56274831/100185343-6d625680-2e98-11eb-8220-abe28b6a4666.png)
because it costs mone

**Comment by D-player1** [comment]
> Update for mobile: dude, I'm still on basically beta..

Every platform is on beta
> Impossible versions of maps

Obviously haven't captured all the attack maps near Nuclear Prod

> Raft: water turrets
Use waves and Tsunami

> Ship upgrades: we have like, 5 on mobile..

You don't even specify what they're doing on each tier

**Comment by ClockAndBallTorture** [comment]
I just said it's on mobile what is a tsunami? And when I said water turrets I meant stuff like spectre, not wave..

**Comment by itcannotbe** [comment]
This is called mindlessly placing X in the [] without doing what they actually say.

**Comment by hadron13** [comment]
every feature is on every platform, except auto shoot from mobile
