### ISSUE TITLE
bug the fps drops drastically when it rains and you select any object to build (beta 117)

### ISSUE THREAD

**Issue by Fryto012** [Anuken/Mindustry-Suggestions#1326]
**Describe what you would like changed, and why.**

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by itcannotbe** [comment]
Ah yes.
![Screenshot_20201125_130737](https://user-images.githubusercontent.com/45280919/100185630-413de880-2f1f-11eb-80aa-0a973ddd92d7.jpg)

**Comment by itcannotbe** [comment]
Also Shitty GPU detected.

**Comment by D-player1** [comment]
Go to bug report
Use the template

**Comment by Fryto012** [comment]
yes
like the one you have in your head


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sample-text-here** [comment]
> like the one you have in your head

yes exactly like the one in my head
![image](https://user-images.githubusercontent.com/56274831/100186387-bd421d00-2e9a-11eb-89b9-10e521329217.png)

**Comment by itcannotbe** [comment]
Probably Close this issue now.

**Comment by DeltaNedas** [comment]
how do these "people" manage to breathe on their own
