### ISSUE TITLE
Smarter Bridge Conveyor

### ISSUE THREAD

**Issue by Humanoid-X** [Anuken/Mindustry-Suggestions#1327]
**Describe the content or mechanics you are proposing.**
Umm,I'm not sure if it's very hard to code(I suppose so), but I hope that Mindustry can have a better bridge conveyor pathfinding.

![m1](https://user-images.githubusercontent.com/60562028/100202087-cdf69f80-2f3b-11eb-938d-f002b37001b8.png)
This is an image I took in a "Crash Course" I made myself. It is too recourse expensive and time wasting and space filling..

![m2](https://user-images.githubusercontent.com/60562028/100202089-ce8f3600-2f3b-11eb-9898-e5047ca7c6a3.png)
When using curvy conveyors.

![m3](https://user-images.githubusercontent.com/60562028/100202092-cf27cc80-2f3b-11eb-81a5-a0df940adad3.png)
This is fine, but what about this?

![m4](https://user-images.githubusercontent.com/60562028/100202084-cc2cdc00-2f3b-11eb-84e5-15e4152ed784.png)
So I hope it can have some sort of pathfinding...

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Quality of Life and Better PvP

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by uAliFurkanY** [comment]
this is a*, implementable

**Comment by itcannotbe** [comment]
Why on earth you use bridges over normal conveyors in that example?

**Comment by Humanoid-X** [comment]
Umm, dunno, making a snek?

**Comment by hadron13** [comment]
on Discord Anuke showed smart power nodes, could be reused to make this

**Comment by Legomonster33** [comment]
some1 did this already, it mightve been a mod tho.

**Comment by Bohaska** [comment]
anuke doesn't want bridge chaining (using bridges instead of conveyors), and your idea will support that.

**Comment by Humanoid-X** [comment]
Oh... alright... Do I need to close this issue?

**Comment by Humanoid-X** [comment]
Yeah, Anuken did made smart power node placement, but bridge is different because they can only chain with other bridge if their x or y is the same. Unlike power node which only require it to be in range.
