### ISSUE TITLE
Custom schematics

### ISSUE THREAD

**Issue by KoolKcd** [Anuken/Mindustry-Suggestions#1328]
The ai building is very good but it need little changes its very simple but change a lot i hope it will be added sooner or later

Custom schematics:
I've done tests with the ai building and what schematics they can build and i found out 2 things 

1 limit amount of schematics for every ore
2 there limit where it can build around the core
Its all good but very boring 
The ai need to be little faster it can fixed by building polys with the ai it make the building faster but case bug
The bug is the polys   build what been destroyed
Very fast that you cant pass it 
Also i noticed that the ai build walls over everything its very bad when the ai build units sometimes it get blocked by walls its pertty useless
How to fix it? 
Yes i cant code but i can make ideas

/
The custom schematics is very simple 
Make menu for every ore and there  list of schematics the ai can build on the ore 
/
Simple right?
I hope this get noticed 
I dont even use github but i wanted go suggest this idea so bad(and issue) 
Thanks for the great game!! 
![Screenshot_20201124_015204_io anuke mindustry](https://user-images.githubusercontent.com/75015249/100210564-32096b80-2f1c-11eb-977c-4629581f5cb4.jpg)
![Screenshot_20201124_094459_io anuke mindustry](https://user-images.githubusercontent.com/75015249/100210576-33d32f00-2f1c-11eb-8152-32740cf67fe7.jpg)

Example of ai building walls over the units

**Comment by Humanoid-X** [comment]
I must say that AI wall coating is really very dumb. It is coded to be dumb.

**Comment by hadron13** [comment]
I heard that those schematics are made by people and _they are very bad at doing this_

**Comment by scarf-generic** [comment]
> I heard that those schematics are made by people and _they are very bad at doing this_

Yeah, were told to make them bad. If the ai had the best/most compact designs there would be no conveyors to cheese and honestly would be kind of scary for a new player to fight against. Yeah, some of them could use work but they are not supposed to be perfect.
