### ISSUE TITLE
Make textures packs work on previews of blocks in menu, ui and font

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry-Suggestions#1329]
**Describe the content or mechanics you are proposing.**
Make textures packs work on previews of blocks in menu and in game, ui and fonts
Texture-override is not supporting many things. This sometime breaks this textures that for example change colors of blocks, look.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Give texture pack makers more freedom in work - change ui, font, etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GlennFolker** [comment]
Pft, it's possible to change UI icons. How?
<br>
<br>
<br>
<br>
<br>
That's right, scripting.

**Comment by DeltaNedas** [comment]
bruh Texture-override does nothing
you must mean sprites-override
if you want your texture pack to apply to everything then just do it
