### ISSUE TITLE
Getting some echoes

### ISSUE THREAD

**Issue by abiel-wd** [Anuken/Mindustry-Suggestions#1330]
I want echoes, and sounds to the game. I want it to be good

This will help, no... scare or give determination to people. Echoes are good as hell

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I want [insert random want] to the game. I want it to be good

**Comment by genNAowl** [comment]
A few things that you should include when making a suggestion like this: 
a. **xs in boxes**
b. How will a mechanic like this work? Will sounds "echo" off walls, or will they just echo all the time?
c. h

That is all
