### ISSUE TITLE
 solar panels are *poop* and RTGs are op

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1331]
**Describe what you would like changed, and why.**
I did some calculations... you need ~200 silicon for solar to achieve energy production of 1 combustion gen, ~1000 silicon for steam gen and ~2700 for thorium reactor. Which is ridiculous. Especially considering that 95% of time in multiplayer you don't have enough silicon. Everyone would like to blame you if you build solar panels. 

Expensive in early-game and mid-game, while RTGs are cheaper and better in late-game. Speaking of them you can feed a ***very*** big amount of these by one drill. ***Who even bothering yourself using phase solar if you have RTGs in late game?***

The only application for solar if there is no anything in miles away including sand. 

***make solar panels cost less silicon and make RTGs consume more fuel or increase their costs***

**Comment by itcannotbe** [comment]
Solar Panels be like: Fuel cost who?

**Comment by scarf-generic** [comment]
Solar panel is cheap shit power for early game when theres not much resources nearby for other generators.
Phase solar panel is for later game when ores are needed for things besides power, like silicon or whatever.
Rtg is for very late game, high build cost but hardly any resource consumption.

Solars dont need a buff honestly, just remove the sunlight nerf and explain it as they store power and release it through the night.
Rtg could use a rework, make them 2x expensive and not use any thorium to produce power.

**Comment by genNAowl** [comment]
^

But I would say large solar panels are not great...

**Comment by ShadeStrike62** [comment]
guys I think you are completely missing the point of solar panels. They are not designed to be efficient, they are designed to work all the time and make reliable power from literally nothing with no requirement on where you place them. They are essentially a fall back for when you sector is low level, and has no coal, or hot rock, or any of that. You can bring in the materials and have power.

**Comment by scarf-generic** [comment]
> they are designed to work all the time and make reliable power from literally nothing with no requirement on where you place them.

Except this is not true because of day/night cycle. Read my previous comment on how to fix this.

**Comment by ShadeStrike62** [comment]
> > they are designed to work all the time and make reliable power from literally nothing with no requirement on where you place them.
> 
> Except this is not true because of day/night cycle. Read my previous comment on how to fix this.

yeah i know, but that was the intention...

**Comment by Slava0135** [comment]
> guys I think you are completely missing the point of solar panels. They are not designed to be efficient, they are designed to work all the time and make reliable power from literally nothing with no requirement on where you place them. They are essentially a fall back for when you sector is low level, and has no coal, or hot rock, or any of that. You can bring in the materials and have power.

I don't really care about campaign. In a usual game it's not reasonable to build them.

**Comment by itcannotbe** [comment]
The last time solar panels were reasonable to build is basically never since v4 stable.

**Comment by XxsuperdeadlysniperxX** [comment]
Actually rgt generators are trash too

**Comment by itcannotbe** [comment]
Do you even know how many RTGs you can run off a single water boosted airblast? Though nmaking a lot of RTGs in the first place.........

**Comment by XxsuperdeadlysniperxX** [comment]
I mean on the power makeing side of the rtgs they are shit at making power mid to late game early game isn't possible to make them and **_because_** mid game your base so big at this point rtg generators become basically useless cuz they physically can't maintain enough power if the base requires power over the amount that rtgs offer which one on thorium runs at 270 power/sec which isn't alot reactor easily beats it with 900 power/sec and the impact beats everything with 6300 power/sec and enough thermals can beat the impact slightly tho you'd need all of them to be 250%
