### ISSUE TITLE
more specific robot binding in processor

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1334]
Describe the content or mechanics you are proposing:

I think that the processor should be able able to specify the amount of robots it wants to bind and to say if it should be already selected ones or ones that haven't been selected yet.

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche:

you can have squads.

**Comment by Ruichka** [comment]
processor can bind only one unit at time

**Comment by catsz** [comment]
the logic processor

**Comment by Ruichka** [comment]
I understood which processor you are talking about. These can bind only one unit at time.

**Comment by catsz** [comment]
I setup a simple logic processor and the code is:
unit bind: dagger
unit control: move: x: thisx y: thisy
end
controls everysingle unit that is made

**Comment by Ruichka** [comment]
because processor loops when the code ends, and ubind instruction is called several times so it seems like it controls all units

code showing that only one unit is binded:
```
ubind @dagger
ucontrol move @thisx @thisy
jump 1
```

**Comment by catsz** [comment]
oh ok that works I thought that end was supposed to reset the processor but ok.

**Comment by catsz** [comment]
will the processor choose already selected robots though?

**Comment by Ruichka** [comment]
ubind command loops around all units of selected type you have, so yes

**Comment by scarf-generic** [comment]
> [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

lies

**Comment by scarf-generic** [comment]
each time the unit bind command is run, another unit is bound. if you wish to bind x units, run unit bind x times.
