### ISSUE TITLE
Balancing enemy bases. 

### ISSUE THREAD

**Issue by Meriotes** [Anuken/Mindustry-Suggestions#1335]
**Describe what you would like changed, and why.**
After trying to attack enemy bases, i noticed that they have too little time in the 1st wave, and with the build speed that you have, it's almost impossible to build enough defenses against enemy units, specially flying units like Horizons. So you either need to build defenses really close to your core or get them constantly destroyed a bit farther on the map. I know that Polys can help you with building but it takes some time for them to be done, and some more to build energy generators. I just think that it's a bit unfair to have to do so much things in just 1 minute and not have much space after that to start building attack units. 

**Describe the changes you want to propose. Include possible alternatives.**
The most obvious change that i can propose is to put more time on the first wave of enemy bases, but also maybe have some pre-placed defenses and maybe unit factories in these at the cost of additional resources if balance is needed. 
A possible alternative, if possible, would be to buff the build speed on harder maps. 

I hope you can understand this because i'm not good explaining stuff, and english is not my native language.

**Comment by D-player1** [comment]
Those attack maps are meant to be hard, use loadout and launch pad

**Comment by Meriotes** [comment]
> Those attack maps are meant to be hard, use loadout and launch pad

I'm sorry but have you read what i wrote? I know it's supposed to be hard but the problem isn't on the resources you have in them or launch to them. It's on the little time you have to do things on the first waves.

**Comment by Bohaska** [comment]
easy peasy to implement. Just find the right file and change some numbers.

**Comment by mwoehlke** [comment]
> It's on the little time you have to do things on the first waves.

Build air factory and additive constructor *first*. Problem solved. (More specifically, those, plus unloaders, plus routers/conveyors as needed, plus some power generation even if it's solar panels. If you're trying to build silicon *production* at this point, you're doing it wrong.)

Also, capture lots of non-attack sectors and have them launch to the sector you're trying to capture. With enough of that plus loadout you can pretty much ignore production.
