### ISSUE TITLE
A cool new weapon idea

### ISSUE THREAD

**Issue by LeChop** [Anuken/Mindustry-Suggestions#1337]
OVERFLOW, surge flow, something??

A weapon that fires titanium and uses cryo to cool down, if it isn't using cryo then it can use slag for a special effect.
ok prepare for a read.
The weapon will fire titanium at 1 every five seconds however if there is more titanium flowing in than fired out it will continue to increase it's fire rate to a maximum set by how much cryo is in it (that being fully maxed at 5 shots per second with full cryo) now if it reached it's maxed fire rate and still has a build up of titanium at the back it can become a giant cryo coloured version of the meltdown and create a continuous beam ,as long as there is still titanium, at the cost of the weapon and surrounding objects losing a small amount of health per second as long as the beam is being fired (if the health of the weapon reaches 0 then it explodes in a similar fashion to a thorium reactor but smaller).
If however you don't want to power it with cryo then every shot fired (maxed at 1 every 5 seconds) will cause the weapon to loose 50% of it's health (it will fire if it has more than 50% health e.g. %51 fire then be on 1%) this does cause a special effect for the major health cost, that being that all the bullets fired cause incendiary and deal, %50 of the enemy's health, damage to whichever the enemy is (even the big bois), same thing happens when the weapon's health reaches 0. The weapon will always require quite a high amount of power to run and more so if using the cryo version.
cost to build.
1000 silicon
350 titanium
200 surge
100 phase fabric
build time (10 seconds)
air - yes
ground - yes

(please feel free to nerf it but keep the same sort of effect with the slag and cryo titanium mixing)

This weapon would be a really good wave 100 type weapon or an extremely strong endgame weapon as there are tons more mid game weapons than end game ones. (also a cool option for cryo or slag special effect things is epic)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
![IMG_20201126_070627](https://user-images.githubusercontent.com/70744599/100293352-04710080-2fb6-11eb-8b4d-f11434ea181d.jpg)

**Comment by Legomonster33** [comment]
maybe for v7, unlikely tho.

**Comment by genNAowl** [comment]
Yeah F for all turret suggestions that won't ever get implemented in game

**Comment by genNAowl** [comment]
Of course, you could just make a mod

**Comment by LeChop** [comment]
yes i know
