### ISSUE TITLE
Lights/illuminators

### ISSUE THREAD

**Issue by bobert2112** [Anuken/Mindustry-Suggestions#1338]
**Describe the content or mechanics you are proposing.**

I want something either in the graphics settings or in game that allows you to turn on and off the lights for units and building, but leaving the heat vents, other natural sources of lights, and the generators alone.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

because pretty much everything that makes materials like metaglass to surge, and power nodes makes light which makes the illuminators somewhat useless. So this would make the illuminators more useful but wouldn't be forced for someone who doesn't like the addition

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Illuminators have colors

**Comment by hadron13** [comment]
illuminators make a lot more light than anything else (except core?)
