### ISSUE TITLE
The fuse should be like a shotgun (ammunition wise)

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1339]
**Describe what you would like changed, and why.**
What I am suggesting is that the fuse ammunition should be like a shotgun. What I mean by this is that the fuse would fire diffrently depending on ammo based on real life shotguns. Here are some examples:

Classic buckshot: graphite (would be the same as it is with titanium right now)

Slugs: thorium. This ammo would make the fuse fire a single bullet and would make your fuse's range bigger while giving it more damage with less total potential damage at that. It would also have less firerate.

Birdshot: Plastanium. This ammo would make your fuse fire 5 shots at once. Each of these shots would deal less damage but with a higher potential damage if you hit all pellets. 

Incindiery: pyratite. This ammo would just be buckshot but incindiery.

Explosive: blast compound.  this ammo would be a slug but explosive

Energy Rounds: surge alloy. This would make your buckshot beams lancer beams instead with the same damage but it would be lancer so it can pierce through overdrive projecters.

**Describe the changes you want to propose. Include possible alternatives.**
This would make fuses more unique as they can have multiple diffrent uses due to their ammo type. This would make them also unique as they could have diffrent amounts of bullets based on the ammo.

**Comment by scarf-generic** [comment]
> pierce through overdrive projectors

what

**Comment by scarf-generic** [comment]
uhm also i think fuse is supposed to be a fusion weapon (thats why it uses thorium), the shotgun/artillery turret is the ripple. (rng spread, large aoe, less effective at longer range, etc.)

**Comment by XEN0PHIL** [comment]
There's already turrets that fire at medium and long range and default fuse tri-shot is shotgun enough
