### ISSUE TITLE
add radar to byte-logic

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry-Suggestions#134]
**Describe the content or mechanics you are proposing.**
Add a radar or radar-signal to byte-logic. This works by either:

- detects enemies around it in a circle and outputs the number of them
- detects enemies in a configurable area and outputs the number of them
- detects enemies in a 90° arc and outputs the number of them
- mix of them, configurable

sprite:
![logic-base](https://user-images.githubusercontent.com/53530661/80695047-9e7ed200-8ad5-11ea-93a0-fafc8cad7577.png)
(sprite not final, there is a green forcefield around it, and the the top part is spinning in the case 1)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In byte-logic, one could make an alarm system, spare resources for defense, reroute factories to defense, route power to defense instead of factories, automatically deploy shields, or take resources out of core in case of attack.
**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Closing due to discontinuation of byte-logic.
