### ISSUE TITLE
Ai building need changes

### ISSUE THREAD

**Issue by KoolKcd** [Anuken/Mindustry-Suggestions#1340]
**Describe what you would like changed, and why.**

PLEASE fix the ai building System 
The ai somtimes block unit path like this 
![Screenshot_20201124_015204_io anuke mindustry](https://user-images.githubusercontent.com/75015249/100298727-e8b02f00-2fa2-11eb-90cd-f5a2c51d7f65.jpg)
![Screenshot_20201124_094459_io anuke mindustry](https://user-images.githubusercontent.com/75015249/100298732-ea79f280-2fa2-11eb-9da7-dc23c63e5097.jpg)
Also they are so slow at building i hope you can change the speed or make it faster

One last thing they have pertty bad schematics 
Please make it Editable it

They are great but need changes

**Comment by Bohaska** [comment]
If you want to give them better schemes, this is the easiest way
1. Ask Anuke for the base schemes role
2. Wait for him to give it to you
3. Post a scheme in the new #base-schematics channel you now have access to
