### ISSUE TITLE
A new way of adding new units for v7.

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1341]
**Describe the content or mechanics you want Anuke to waste his time on.**
I would like to suggest different reconstructors. For example, you can make a specific reconstructor that upgrades Minkes into submarines, or Quads into expert bombers.

**Describe how you think this content will damage the game. If you're proposing new content, mention how it may annoy more players or help cheaters.**
Better way of adding more types of units easily, allowing for greater variety. However, I am not sure that new units will be added to Mindustry in later versions.  If not, then this suggestion can be discarded.

**Before making this issue, place a bunch of X's in the boxes. Failure to put a bunch of X's in the boxes may lead in a bunch of people being very angry at you.**

1. - [X] I have looked at a bunch of stuff other guys wrote to make sure that this isn't the same.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't wasting Anuke's time already.
3. - [X] I play Mindustry or took a quick look at the thing that tells you everything that is in Mindustry v5.
4. - [X] I have read the list that has a bunch of things you shouldn't suggest to make sure that Anuke will be more likely to waste his time on this.

**Comment by Humanoid-X** [comment]
PENTATIVE RECONSTRUCTOR

**Comment by Humanoid-X** [comment]
You can already use mods to do that.

Or if you want to code it yourself, I can tell you that the class is named "Reconstructor".

**Comment by Bohaska** [comment]
True, but I want this to be added into the vanilla game so that it will be easier to add new classes of units

**Comment by DeltaNedas** [comment]
how would that make it easier by adding more vanilla units

**Comment by Bohaska** [comment]
Bye
