### ISSUE TITLE
New type of maps

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1342]
**What in the world do you want me to waste my time on?**
A type of map in which the left and right sides of the map are connected and the top and bottom sides are connected. If you go to the very bottom and still continue going, you will end up in the top. Optional

**Why in the world should I waste time on your stupid idea?**
It will open up more ways to attack, and require more places to defend. Harder maps.

**We like X's. Put some here!**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
h

**Comment by Legomonster33** [comment]
nice format lul

**Comment by Axzye** [comment]
good idea but how does it make sense

**Comment by Bohaska** [comment]
> good idea but how does it make sense

How does what make sense?
