### ISSUE TITLE
Calculate Mono

### ISSUE THREAD

**Issue by OinkyPlayz** [Anuken/Mindustry-Suggestions#1343]
**Describe what you would like changed, and why.** So recently I have started using mono to drill for copper and lead instead of using drills, however it appears that when using only mono to get copper and lead, it isn’t calculated when you are not in the sector, so if there is any build that saps copper or lead from the core to make stuff, (eg. metaglass) the production will stop if you are not in the sector.

**Describe the changes you want to propose. Include possible alternatives.** Detect the amount of mono in a sector and make them actually produce stuff when you are gone.

**Comment by D-player1** [comment]
Not filling the template
Amazing

**Comment by OinkyPlayz** [comment]
Oops sorry

**Comment by OinkyPlayz** [comment]
I fixed it now

**Comment by hadron13** [comment]
https://github.com/Anuken/Mindustry/issues/3573 already fixed 🤔
