### ISSUE TITLE
Civilizations for V7

### ISSUE THREAD

**Issue by lINSTINCTl** [Anuken/Mindustry-Suggestions#1344]
**Describe the content or mechanics you are proposing.**
As we go to other planets now each team colors will have own logos and own specialties for example red team are specialized when it comes to drilling and mining their drills will have x% more faster than usual and their units mines x% faster than normal

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will change the gameplays especially on camPAIN I mean Campaign 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - []X I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ah yes, that's called a death sentence when you have to balance gameplay.

**Comment by Bohaska** [comment]
- [X] This is the best idea for wasting Anuke's useless time.

**Comment by genNAowl** [comment]
> []X

The X has been freed

**Comment by Bohaska** [comment]
> > []X
> 
> The. - [X] has been freed
