### ISSUE TITLE
Hashing entityMapping

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry-Suggestions#1345]
**Describe the content or mechanics you are proposing.**
Since Unit is serializable, they use EntityMapping and classId for write-read.
But there's problem that modded units can't get appropriate classID.(I saw you recognized this problem)
So I suggest hashed map for modded units with String.hashCode().
pseudocode?
```
public UnitType(String name){
    ...
    EntityMapping.hashMap.put(name.hashCode(),constructor)
}

classId(){
    if(modded) return type.name.hashCode();
    else return ...
}

writeInt(entity.classId());
typeId=readInt();
if(typeId>=256) entity=EntityMapping.hashMap.get(typeId).get();
else if ...

``` 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
quality of life

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
what would be better is simply using a unit registry in the save and having classid refer to that registry, like block ids in schematics.

**Comment by younggam** [comment]
according to Schematics.java,
it uses registery that consists of string,
and writes index of them for each block. I guess it would be better becuz it guarantees neat code

**Comment by GlennFolker** [comment]
`if(minfo.mod != null)`
