### ISSUE TITLE
refund when building over existing stuff

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1346]
**Describe what you would like changed, and why.**

currently when you upgrade any block by placing it over existing blocks (conveyors/walls/etc) you do not get a refund.

**Describe the changes you want to propose. Include possible alternatives.**

for the building(s) under it to be refunded against the `deconstructRefundMultiplier` rule.

**Comment by Catchears** [comment]
I can't believe that this hasn't been suggested before

**Comment by scarf-generic** [comment]
You get a refund in less construction time, no need to get items back too

**Comment by Quezler** [comment]
really, its faster?

**Comment by Axzye** [comment]
yeah because you need to destroy the block first and you don't do that with replacing

**Comment by Humanoid-X** [comment]
Destroy, then rebuild  ===>  More time, more refund
Directly rebuild over   ===>  Less time, less refund

So they are actually totally balanced (in my opinion).
