### ISSUE TITLE
spore press balancing

### ISSUE THREAD

**Issue by bar0nch** [Anuken/Mindustry-Suggestions#1348]
**Describe what you would like changed, and why.**
if you make a schematic for energy from an energy kickstart with spore presses the amount of energy consumed is higher than the amount of energy gained. Now that the oil extractor is nerfed the spore press could become much more used to make energy.

**Describe the changes you want to propose. Include possible alternatives.**
make the spore press produce more oil/sec or just lower the requirements.

**Comment by itcannotbe** [comment]
Ah yes. It seems that 1 spore pods for 6 oil every third of a second is apparently too much.

Nope it isn't.

**Comment by itcannotbe** [comment]
Also stop reminiscing your wet dream of power made from power (To be frank, that was hilariously overpowered). If you want to do that use impacts.

**Comment by D-player1** [comment]
Stop

**Comment by Bohaska** [comment]
wonder how I can make scrap to power...

**Comment by Bohaska** [comment]
Also, powercubes still work. I'm trying to make more efficient powercubes.
