### ISSUE TITLE
E

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#1349]
**Describe what you would like changed, and why.**
Nerf Mega, Buff Zenith
Reasons on why Mega should be nerfed:
2.5 speed
Can mine
Can build
Can carry blocks
Can carry units
Can heal blocks
Can make a bigger advantage on all the stats above by unit command
Has more range than Zenith (26)
Has more single target dps than zenith
Bullet speed is faster than Zenith
No inaccuracy
Can beat Zenith

Reasons on why Zenith should be buffed:
Slow 1.7 speed
Can't
Can't
Can't
Can't
Can't
Range is 23
Lower dps than Mega
Has inaccuracy
Lose against Mega

**Describe the changes you want to propose. Include possible alternatives.**
Make Zenith has a greater advantage than Mega

**Comment by RedstonerKBC** [comment]
I feel like the mono-line shouldn't be suited for attack except the T4 bomber thing whatever it's called. The thing that drops green bombs. Anyways, it's weird knowing megas, a utility mech, can beat a freaking Zenith, an attack mech.

**Comment by YellOw139** [comment]
Yes, right? It's even more frustrating when you realize you can't beat megas with zeniths. Heck, you can't beat megas without parallaxes, as they are the only turret capable of outranging megas before they destroy your stuff (not including foreshadow).

**Comment by sample-text-here** [comment]
> Heck, you can't beat megas without parallaxes

(unrelated) i see people finally admitting parallax is useful

**Comment by Humanoid-X** [comment]
What?! Did I read wrongly!? Mega can beat Zenith?!

**Comment by YellOw139** [comment]
Mega used to have 28 range. Parallaxes have 28.75 and it's the highest in the game, if you don't count foreshadows. Zenith always had 23 range.

This has changed a few commits back. Mega has been rebalanced. Mega now has 23 range, same as zenith.

Damage is an entirely different issue. Let me go and do some math.

**Comment by YellOw139** [comment]
Theoretically mega used to have a range that was too high. Which meant that it could destroy all of your non-parallax and non-foreshadow turrets without the turret even touching the mega.

**Comment by YellOw139** [comment]
Mega has somewhere around 25 DPS now, no inaccuracy and is faster. It can mine, build, carry, heal and do all sorts of stuff.

Zenith has 18.6 DPS and 18.6 splash DPS across 3.1 tiles, all homing, inaccurate bullets. It is slow, cannot mine, build, carry or heal.

Now it seems more balanced. Not sure if it changed recently or if that's how it used to be.

**Comment by YellOw139** [comment]
So mega right now has 56 DPS, no inaccuracy. It's faster, can build, mine, carry, heal.

Zenith currently has 42 DPS and 42 splash DPS across 3.1 tiles, all inaccurate, homing bullets. It's slower, cannot, cannot, cannot, cannot.

It seems to have been recently rebalanced, but I'm not sure if it's balanced right now in terms of DPS. Well, at least we've got a fair range.

**Comment by YellOw139** [comment]
As soon as this map starts, build Zeniths. Red team will build megas. Both sides are evenly matched, save for zeniths and megas.

[MegaZenith.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5607425/MegaZenith.zip)

After all of Anuke's rebalances, Zeniths finally win in BE 20102. It's a debatable win though, as megas are faster, can heal, build, mine and carry. On PvP, logic-controlled or player-controlled megas might actually win. But on attack, it's Zeniths that win in terms of raw DPS.

**Comment by XxsuperdeadlysniperxX** [comment]
**_why would anyone wamt the mega weak and useless its a t3 unit dude on the mono line all mono line units are actual healers (excluding the mono) and thus very powerful_**

**Comment by RedstonerKBC** [comment]
I've done attacks with both and I feel they are balanced. A Mega attack does decent damage to quickly wipe out power nodes, conveyors, and enough damage to take out low-tier turrets. On defense their bullets get blocked healing your buildings so they're better as support units than defense. Zeniths on the other hand are overall better for attack/defense because their shots follow players and don't get stopped by your buildings to heal them.

**Comment by XxsuperdeadlysniperxX** [comment]
Mega
Unit type: repair
Unit function: repairs buildings and will only shoot at things to defend itself
Unit ai: repair and defend (defend means to defend itself not your base)

Unit stats: see in game **_core database_**

**Comment by XxsuperdeadlysniperxX** [comment]
Zenith
Unit type: attack
Unit function: seeks out enemy core and attempts to destroy anything it sees (aka the to do as much damage as possible whilest approaching the core)
Unit ai: seek and destroy 
Unit priorities:units if in range guns or power depending on where it happens to attack upon approach

Unit stats: see in game **_core database_**

**Comment by XxsuperdeadlysniperxX** [comment]
If this is not accurate enough use the unit and test in sandbox with it

**Comment by XxsuperdeadlysniperxX** [comment]
I'd recommend not to possess it tho as this overrides the ai and replaces it with player control until you possess the core again
