### ISSUE TITLE
add bell to byte-logic

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry-Suggestions#135]
**Describe the content or mechanics you are proposing.**
Add a new object to byte-logic: the bell-signal. This is a tile that when a signal is input, either:

- make alarm sound or pop up
- make sound with specified or input frequency (in Hz) or pop up input signal

sprite:
![logic-base](https://user-images.githubusercontent.com/53530661/80695972-041f8e00-8ad7-11ea-8d37-aa582add0ac4.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This is useful, for example, when a thorium reactor is running out of cryofluid, to tell the player to fix it. Also when out of power, enemy approaching, core is under attack, defense is breached, and so on.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Closing due to discontinuation of byte-logic.
