### ISSUE TITLE
[Feedback]: Basic drone shouldn't be able to burn

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry-Suggestions#1351]
**Describe what you would like changed, and why.**
Description: Alpha, Beta & Gamma should NOT be able to burn when they are shot down while carrying combustible materials in their inventory.
Reason: Many good games got ruined by mere coal bombers flying through weak spots which are not covered by strong AA turrets (Often times, they are flying through the black area, related to https://github.com/Anuken/Mindustry-Suggestions/issues/1214)
Nowadays, more and more players are rushing to bomb in early games. Before metaglass can be produced, defenders simply have no way to extinguish fire.

Metaglass needed to make 1 wave turret = 45, 1 mechanical pump = 10, not including 30 graphite needed to build a kiln + many conduit pipes + power generator + nodes + mechanical drills.
Most of the times, it's simply not enough resource and time to get enough fire extiguishers in hand.

**Describe the changes you want to propose. Include possible alternatives.**
Remove the possibility of Alpha, Beta & Gamma to crash and burn, or just decrease the burning chance of those 3 unit types.

**Comment by hadron13** [comment]
this already can be disabled
![image](https://user-images.githubusercontent.com/62845905/100384313-a0265f00-2ffe-11eb-81cf-1c92140e15bf.png)

**Comment by GreyMario** [comment]
If you'd take about six seconds to read the suggestion, what's being proposed is a "happy medium" that forces players to actually construct units before they can attempt the incredibly cheap and dishonorable tactic of coalbombing.

**Comment by liliam2007** [comment]
I had someone use a REAPER to kamikaze the enemy base. A REAPER. The reaper takes an extremely long time to build and tons of energy to make and has massive amounts of firepower and this player uses it to kamikaze the enemy base. That kind of thing is too expensive to do

**Comment by DeltaNedas** [comment]
bruh anuke disabled core units coal bombing months ago

**Comment by D-player1** [comment]
And he enabled it

**Comment by GreyMario** [comment]
[And disabled it.](https://github.com/Anuken/Mindustry/commit/dae46ceb6d91740ae03969afa08f5e9d8e861838#diff-dae4ad7d84141b1d23fb81d4542d734131bc743144f4ba54c6951bda039a2baa)

**Comment by mangblekok** [comment]
Implemented in https://github.com/Anuken/Mindustry/commit/91c50ae1260d72ea1e41bf88ed52f8c936f60878
Closed.
