### ISSUE TITLE
more boats on windswept islands

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry-Suggestions#1352]
**Describe what you would like changed, and why.**
*more naval units on windswept islands, less air ones, it will incentivate the player produce more naval units and make the map more interesting, with a new unit class*

**Describe the changes you want to propose. Include possible alternatives.**
* *starting with 1 risso, +0.5 rissos every spawn, ends at wave 23*
* *wave 2 with flare, spawns every 2 waves, +1 per spawn*
* *wave 10 with minke, +0.4 per spawn*
* *wave 24 with bryde every 3 waves, +0.7 per spawn*

**Comment by Bohaska** [comment]
Ok. I will replace the original waves with these, but keep horizons though.

**Comment by Bohaska** [comment]
Here! Github forced me to send a zip
[New Windswept Islands.msav.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5627970/New.Windswept.Islands.msav.zip)
