### ISSUE TITLE
Add weather hints

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry-Suggestions#1353]
**Describe the content or mechanics you are proposing.**

Add tutorial hints when a certain weather type appears for the first time.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Weather is the most obscure area of your game. It's not explained anywhere. I think it should. I, for one, despite knowing weather since it was added to the game, and despite playing the campaign and encountering weather numerous times, always forget the exact effects all the different weather types have.

All I can recall right now is spore storms boosting cultivators and sandstorms temporarily nerfing solar panels.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Wait what, weather actually does stuff?
