### ISSUE TITLE
Allow changing of seeds for campaign

### ISSUE THREAD

**Issue by Monkeychow01** [Anuken/Mindustry-Suggestions#1354]
**Describe the content or mechanics you are proposing.**

Within the campaign, you already have seeded sectors (maps) next to your default hardcoded ones.   Within these seeded sections, I'm making the assumption that they are infinite.   It may be a bad assumption, but hopefully makes the feature request easier.   The ask is to add a way on a new campaign to "randomize" your seeded sectors.  Allowing us to not always start with the same "174, 175, etc".   Give the ability to put in starting seeds or randomize them so that every playthrough of the campaign can be "different".

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This simple addition to change up the sector seed randomization, allows for infinite replayability, and "freshness" when playing multiplayer with friends, or running a second campaign.   From our many hours of playing the game, this is the only thing my friends and I feel is "missing" from the game, keeping us from playing it more.   While each of us could take different paths on the planet, ultimately we're playing "the same game".   Each map is it's own "puzzle", so allowing us to randomize the puzzles we get, will allow us to have different experiences each time we play.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
https://github.com/Anuken/Mindustry/issues/3245#issuecomment-720631967

anuk no like
