### ISSUE TITLE
Change backup location

### ISSUE THREAD

**Issue by Susideur** [Anuken/Mindustry-Suggestions#1355]
**Describe what you would like changed, and why.**
Have the ability to change the game save folder

**Describe the changes you want to propose. Include possible alternatives.**
It would be nice to have the option to change the location of the save folder of the game, especially when I have different versions of the game, as this can create conflicts between save games.

(Translate by Google Translate)

**Comment by DeltaNedas** [comment]
you can recompile it

**Comment by Susideur** [comment]
and how i do that ?

**Comment by Susideur** [comment]
hey, hello ?
