### ISSUE TITLE
decide what core to use when launching

### ISSUE THREAD

**Issue by rileythedragon** [Anuken/Mindustry-Suggestions#1356]
Playing through the campaign currently, when launching to a new area it can, in some situations, be difficult to get the materials you wish to launch with. 
for example if I want to launch to a new area that I haven't been to previously and I want to bring titanium with me so that I can build things like separators, I am unable to as my nearest core to the location is unable to contain titanium because it is not present on that map.
what I suggest is adding the ability to select what core you would wish to launch from by clicking on that core and then clicking on the new place in which you want to travel to.
I also believe that another feature that would also combat this problem would be the ability to move items around your cores after capturing the sector, this would keep the difficulty of each level intact whilst also allowing players to upgrade and improve the productivity and defence of their weaker bases leading to what I believe would be an increase in playtime and enjoyment as, in my opinion, it is fun to make things that you previously made better and better.  

In the occasion this got added to the game I believe it would increase the re-playability and enjoyment of the game as said previously, and would also allow players to make a "supply chain" of sorts coming from their strong bases to the weaker bases and improving the strength of their new industrial empire.  
upon searching the trello page I found sector transfer, but didn't think this was entirely reason to not post as the ideas, whilst similar, are different.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by UnionofSovietSocialistRepublics** [comment]
ok
