### ISSUE TITLE
A new Living type of enemy for waves/new planet idea

### ISSUE THREAD

**Issue by EvilBadger34** [Anuken/Mindustry-Suggestions#1357]
**Describe the content or mechanics you are proposing.**
I propose that there should be a new type of enemy for another planet(or the current planet, I'm not sure where you want the games story to go), that has waves of creatures to defend from.
I was watching Maze Runner: the death cure, and saw huge guns on giant walls to shoot at zombies if they came close, which gave me an idea! 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Usually we fight against enemy mechs, an industrialized enemy force, so what if we were up against creatures for a new type of challenge in campaign? Adding a living enemy force can invoke many routes for Mindustry to develop on, enemy mechs will look for the perfect route to your core, but creatures are more unpredictable, which can throw players off creating more difficulty, creatures don't know where your core is, they will attack anything that makes noise like conveyors, factories, generators, units, unnatural light sources at night, and of course the player's core. So if a wave of creatures destroys your Frontline defense there are possible strategies to lure them into a trap zone by making alot of noise/light in one area. You can also play with friends to help ward off the aggressive creatures, and there may be nests along a new sector that hasn't been explored yet, nests will send creatures at you if noise or unatural light sources are detected, it may be optimal to send units to destroy a nest. As for anti air creatures, they could spit acid or try to jump onto the aircraft and start tearing it up, aircraft with built in guns will have no chance alone but aircraft with built in turrets can shoot the creatures off.

I know some players will just avoid creatures altogether and sit the whole game out safely, so to prevent that style of gameplay, when a creature spawns and has no targets around and can't hear or see anything, they will trot around the sector minding their own business, resting etc. until they can hear something close by or see light sources at night, making the map progressively dangerous and harder to capture if the player doesn't secure land.

Creatures may not spawn within a certain area, there may be a dead zone that's made far from the core that spreads around the map that creatures spawn from, a sector is considered captured when all nests are clear, but that doesn't make it safe, defenses will still be needed, guarding the deadzone.(units may also have a "patrol" feature from the command block, patrols can be set by the player by selecting the command block and choosing an option to set patrol route, where they can place a route and direction and choose which units built by specific factories use that patrol. Patrols can help the player clear out undefended space). 
When a player captures all sectors adjacent to a sector, that central sector will no longer attract creatures, and defenses may be removed without risk, unless a guarding sector is lost. All sectors on a creature planet will be infested by difficulty levels: low medium high extreme and eradication. There may be a few sectors that creature do not possess, creating a safe zone.

Basis Ideas, of course I am happy to let them be bent in any way to possibly have them in the game! 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ShadeStrike62** [comment]
did you actually watch maze runner though...
please tell me you have read the books first...

**Comment by EvilBadger34** [comment]
I did watch the Maze runner, all 3 of the movies. But I never read the books

**Comment by Buddermario7** [comment]
The books are much better. The first movie omits so many of the details that it hardly makes sense and the second and third movies more or less just do whatever while keeping some random things from the books.
