### ISSUE TITLE
Rebuild destroyed in area button

### ISSUE THREAD

**Issue by Crutchmaster** [Anuken/Mindustry-Suggestions#1358]
Subj. Rebuilding all destroyed things with one click without pausing and select everything or saving schemas of base. At leash for singleplayer.

--

Нужна кнопка для восстановления разрушенных строений в выбранной области. Ставить на паузу и перестраивать руками очень геморно. Нужно хотя бы для одиночного режима.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Singleplayer at leash visualized.

![Leash](https://c.tenor.com/q0lLOSPbhA0AAAAM/babysit-brooke-candy.gif)

**Comment by genNAowl** [comment]
This has been suggested so many times that I won't even bother counting anymore.

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1309

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1049

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/81

**Comment by genNAowl** [comment]
and probably more because I only did a quick search
