### ISSUE TITLE
Show total/max drill/pump output in selected area 

### ISSUE THREAD

**Issue by Crutchmaster** [Anuken/Mindustry-Suggestions#1359]
When selecting an area (f) show max and current output of drills and pumps for better traffic planning.

--

При выборе области было бы не полхо показывать общих вылхоп шахт и насосов в ней, чтобы лучше планировать нагрузку за производство и транспортную сеть.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
So.................

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Comment by Crutchmaster** [comment]
>Describe how you think this content will improve the game

>better traffic or production planning
