### ISSUE TITLE
Kicking griefers

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1360]
**Describe what you would like changed, and why.**
Griefers are getting smart and mainly go to servers that have insta-build turned on. What they do is start a vote then proceed to grief as everyone is rendered helpless for the next 15 seconds. Make it so you are able to vote on kicking multiple people at once.

**Describe the changes you want to propose. Include possible alternatives.**
In the tab player list, when players are being voted on thier hammer button changes to 2 buttons that let you vote yes or no. This is the easiest way to implement it in my opinion because you can see everyone being voted on and vote on specific players the fastest.

But if you must stick to commands, make the syntax for kicking people /kick (player) [y/n] to kick a specific player or start a votekick with /kick (player).

I know what you're thinking, Griefers can spam this command. Make it so each player can only start a votekick once every minute. This makes it so griefers can't spam the command but also stops them from using it to protect themselves from being kicked.

**Comment by scarf-generic** [comment]
Hm yes we know how easy it is to type in `/kick £ə₩§ßį y`
Get a plugin that does this, or disable instant build on the server you run. Maybe this will happen in v7 but it seems like anuke is done with v6 and is just doing bugfixes/translations.

**Comment by itcannotbe** [comment]
The best way is to count vote kick triggers via player panel as individual votes instead of it initiating a vote.

**Comment by RedstonerKBC** [comment]
> Hm yes we know how easy it is to type in `/kick £ə₩§ßį y`
> Get a plugin that does this, or disable instant build on the server you run. Maybe this will happen in v7 but it seems like anuke is done with v6 and is just doing bugfixes/translations.

Like I said I prefer using tab to vote/start a votekick since you can click a button next a user's name to cast your vote

**Comment by Humanoid-X** [comment]
If the player is using color coded or special symbols as their name you will not be able to write their name out without using a lot of time. 
So instead of using command, kick them from the player panel.

And I discovered something about votekick! 
If you type in "/votekick" only, it will show all the players and their UUID. 
Then, you can type in "/votekick <UUID>".
