### ISSUE TITLE
allow the oct to cary the omura

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1361]
**Describe what you would like changed, and why.**

currently if you end up with an omura in the highest reconstructor there is no way to get it out if its not near a water tile.

**Describe the changes you want to propose. Include possible alternatives.**

letting the oct be able to transport it directly from the constructor to a pond.

**Comment by Bohaska** [comment]
Are you sure this wouldn't be to OP?

**Comment by scarf-generic** [comment]
> Are you sure this wouldn't be to OP?

it can already carry one. this suggestion is just to let it carry directly from a reconstructor.

**Comment by Quezler** [comment]
the oct can already carry an omura?

**Comment by Humanoid-X** [comment]
Really? I tested it myself. It didn't even move it by a pixel.
Sei and Omura should really lose some weight... They are really too massive.
And! How can Omura produce Flare? Won't it clog air production?!

**Comment by HaphLife** [comment]
> Really? I tested it myself. It didn't even move it by a pixel.
> Sei and Omura should really lose some weight... They are really too massive.
> And! How can Omura produce Flare? Won't it clog air production?!

Production isn’t stopped when you hit cap, only units leaving conveyors is.
