### ISSUE TITLE
make Last Accessed not count just reading processor code as an interaction, and add an exit-without-saving button to logic

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1362]
**Describe the content or mechanics you are proposing.**
If you're doing logic on the fly, it can sometimes get wiped by players wanting to read it and closing their logic panel after you close yours. This can be prevented by adding an exit-without-saving (with confirmation) button. Additionally, currently Last Accessed is almost useless at detecting logic grief, as it logs even players that did no change to the code.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Makes logic much easier to handle in multiplayer.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Griefers are doing exactly what I warned people would happen when "last accessed" appeared. I get votekicked from servers all the time because they grief where others interected with blocks but they themselves never intereact with any blocks so my name is the only one that remains on the blocks.

**Comment by LottieVixen** [comment]
I agree this would be nice, just discovered this issue testing, last person to close it is the state that is saved, which can be highly annoying
