### ISSUE TITLE
[Feedback]: Add some kind of statistics

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry-Suggestions#1363]
**Describe what you would like changed, and why.**
In v5, Fuse turret was the most preferred turret in mid and lategames.
Now, even though Fuse's ammo has been changed to easier ammo (Titanium) it's still being underused in most games, along with Scorch, Swarmer, Segment and Spectre.

Back to topic, what I'm proposing here is to add a statistic, so developer / server owner / player knows which unit and/or building that rarely used. 
So developers could know which things should be reworked or not, because if some unit/turrets are rarely used for long time, there has to be some reason (ie not enough range / damage / requirement too high, etc), although this behavior is linked to the map being played itself (resource availability, amount of open space, etc).

**Describe the changes you want to propose. Include possible alternatives.**
Add statistics to each unit & turret.

**Comment by itcannotbe** [comment]
TBH. v5 Fuse is a piece of shit in v5 during late game.

**Comment by mangblekok** [comment]
In v5, against horde of Revenants, correctly placed arrays of Fuse do their job real quick 👌

**Comment by DeltaNedas** [comment]
if anuke really wants to know the communities' views on stuff he can make a poll rather than adding trackers to mindustry

**Comment by itcannotbe** [comment]
The only late game unit in v5 is eradicators. Take it or leave it.

**Comment by scarf-generic** [comment]
Fuse is rarely used because its rarely useful. In situations where it is useful, it is an amazing turret. Its an amazing area denial turret for air units when you cannot afford multiple spectres. This game does not need statistics or trackers. If you want this, make a mod for yourself or a plugin for your server.

**Comment by Legomonster33** [comment]
> if anuke really wants to know the communities' views on stuff he can make a poll rather than adding trackers to mindustry

![image](https://user-images.githubusercontent.com/54417042/100522869-fa97fa80-3179-11eb-8f79-9c5ffa4bd464.png)
