### ISSUE TITLE
Oval Planet

### ISSUE THREAD

**Issue by Voz-Duh** [Anuken/Mindustry-Suggestions#1365]
**Make the poles of the planet (north and south) and flatten the planet on the each of them, thereby making the effect of an oval planet.**

**I think adding a more oval planet will make the graphic part of the game better..**

1. - [X]
2. - [X]
3. - [X]
4. - [X]

**Comment by itcannotbe** [comment]
How exactly does making an planet will make the graphic part of the game better?

**Comment by joshuaptfan** [comment]
The term you're looking for is [oblate spheroid](https://simple.wikipedia.org/wiki/Oblate_spheroid). Planets IRL are slightly squished at the poles due to their rotation flinging their mass towards their equators.

**Comment by Voz-Duh** [comment]
Okay
