### ISSUE TITLE
Roof defense

### ISSUE THREAD

**Issue by SpaceTime-exe** [Anuken/Mindustry-Suggestions#1366]
**Describe the content or mechanics you are proposing.**
Like a roof/ceiling that can protect buildings from air attacks and bombs

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Because air units when used in swarms are too op and destroy everything and they fly over walls. With this air attacks aren't too op in servers

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
Ah, so a force projector.

**Comment by itcannotbe** [comment]
Exactly........

**Comment by GreyMario** [comment]
There are so many overpowered anti-air solutions in the game it's not even funny...

Have you ever considered a cluster of Parallax underneath a force projector?

**Comment by Humanoid-X** [comment]
Force Projector: Exist

**Comment by itcannotbe** [comment]
Exactly........



Wait. I think I already said that a while ago.

**Comment by Kyllingene** [comment]
Wait, you checked the "I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet" box, yet the Force Projector is a thing. I would say this doesn't fit the requirements.

**Comment by Stardust9681** [comment]
A lot of people are saying "Oooo, force projector" but it can be inferred from the original post that they're not talking about that stage in the game. Early on, especially in PvP gamemodes, people can rush Flares and Horizons, and because some fall and outright explode, it can be devastating. I believe the suggestion is to provide a defense against these falling units earlier on. Furthermore, force projectors apply to ground and air units, whereas suggestion is strictly for air units.
Personally, I think this would be a great idea, and perhaps could be added in a similar way to force projectors currently.

**Comment by HaphLife** [comment]
> A lot of people are saying "Oooo, force projector" but it can be inferred from the original post that they're not talking about that stage in the game. Early on, especially in PvP gamemodes, people can rush Flares and Horizons, and because some fall and outright explode, it can be devastating. I believe the suggestion is to provide a defense against these falling units earlier on. Furthermore, force projectors apply to ground and air units, whereas suggestion is strictly for air units.
> Personally, I think this would be a great idea, and perhaps could be added in a similar way to force projectors currently.

Also force projectors don’t (or didn’t) stop air units from doing damage. Air units crashing literally just ignored force projectors.
