### ISSUE TITLE
A team of 'helpers' for Mindustry. (I can't put this suggestion anywhere else...) 

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1368]
**Tell me the stuff you want to suggest.**
A team of 'helpers' for Mindustry. They will be developers, and they will be solely responsible for making pull requests for issues here which are relatively easy to fix.

**Tell me how you think this stuff will make the game good. If you're suggesting new stuff, say how it may add more gameplay options or how it will fill a new niche.**
Accelerate the process of suggestion\-dev-pull request-game

**Tick the boxes unless you like angry people shouting at your suggestion**

1. - [X] I didn't do anything below this
1. - [X] I did do everything above this
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Goobrr** [comment]
There's already this thing called Contributors.

**Comment by DeltaNedas** [comment]
go implement them yourself if theyre so easy

**Comment by GlennFolker** [comment]
Why the hell do people change the subtitle, it's extremely cringe and unnecessary

**Comment by itcannotbe** [comment]
I didn't do anything below this

I did do everything above this

**Comment by Bohaska** [comment]
> go implement them yourself if they're so easy

Say that to the average Mindustry player.

**Comment by Bohaska** [comment]
> There's already this thing called Contributors.
True, but suggestions still aren't implemented that quickly for most of them.

**Comment by Bohaska** [comment]
> Why the hell do people change the subtitle, it's extremely cringe and unnecessary

Maybe because I was the author of this issue, and you are not?

**Comment by Bohaska** [comment]
> go implement them yourself if they're so easy

Say that to the average Mindustry player.

> There's already this thing called Contributors.

True, but suggestions still aren't implemented that quickly for most of them.

> Why the hell do people change the subtitle, it's extremely cringe and unnecessary

Maybe because I was the author of this issue, and you are not?

**Comment by Anuken** [comment]
Not sure who this suggestion is supposed to be for. If someone wanted to help, they could do so without needing to be told about it here.

> they will be solely responsible for making pull requests for issues here which are relatively easy to fix.

There are already some people who do this. Problem is, it can be hard to tell what's easy to implement and what shouldn't be added in the first place.

**Comment by DeltaNedas** [comment]
anuke maybe you could flag certain suggestions as good / easy to implement but i cant be bothered right now / good but not interested / wip
