### ISSUE TITLE
A upgraded 3x3 scorch

### ISSUE THREAD

**Issue by Precixion** [Anuken/Mindustry-Suggestions#1369]
**Describe the content or mechanics you are proposing.**

This will be an upgraded version of the scorch
A bigger better scorch that is 3x3  and will deal a lot of damage like the broken scorch in v5  . This will be like the tsunami but it shoots fire 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

There will be more options for turrets and diffrent defense layout plus there is a upgraded version of the wave it makes sense to have also an upgraded version of scorch 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Yoy already have Fuse, don't try to bring v5 scorch

**Comment by itcannotbe** [comment]
TBH. There is only a single use case with the broken v5 scorch. And it's so specific it's stupid tbh.

And the only reason why scorches and fuses were broken on v5 is that they somehow damage the same unit with the same shot. And it got fixed.

**Comment by DeltaNedas** [comment]
>  I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
> > I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Looks like it, can't find anything in there that said you can't have this.

**Comment by Bohaska** [comment]
> Yoy already have Fuse, don't try to bring v5 scorch

What about a better v6 scorch, but not based on v5? Maybe like a turret that uses the new fireball bullets added/

**Comment by mangblekok** [comment]
Wouldn't it be equal to Tsunami + Slag?

**Comment by bvcbvc** [comment]
> TBH. There is only a single use case with the broken v5 scorch. And it's so specific it's stupid tbh.
> 
> And the only reason why scorches and fuses were broken on v5 is that they somehow damage the same unit with the same shot. And it got fixed.

this was because of how he programmed pierce, in v5 it hit every unit within its hitbox every frame, which obviously made them really, really powerful, which was kinda balanced with the lack of range
