### ISSUE TITLE
[6.0] Different music for different biomes 

### ISSUE THREAD

**Issue by kapzduke** [Anuken/Mindustry-Suggestions#137]
**Describe the content or mechanics you are proposing.**
The title is self explanatory. (i.e the snow biomes' theme would use the triangle as their main instrument)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This feature would really enhance the game atmosphere.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
This could get very annoying with maps that have a lot of mixed ground. Where does a biom begin and end if they are scrambled all over the place? All you would hear at most is the first 5 seconds of the music before it switches

**Comment by kapzduke** [comment]
> This could get very annoying with maps that have a lot of mixed ground. Where does a biom begin and end if they are scrambled all over the place? All you would hear at most is the first 5 seconds of the music before it switches

agred

**Comment by kapzduke** [comment]
> **Describe the content or mechanics you are proposing.**
> The title is self explanatory. (i.e the snow biomes' theme would use the triangle as their main instrument)
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> This feature would really enhance the game atmosphere.
> 
> **Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 2. * [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by jaygamer81** [comment]
Make the change happen after the track is done. So if you left a biome the biome music would keep playing till the track hits a "checkpoint" where the game would check which biome your in and either: continue the track or change it.
