### ISSUE TITLE
Make air units move back when player approaches them

### ISSUE THREAD

**Issue by DragonMadness** [Anuken/Mindustry-Suggestions#1370]
Sometimes when you make a lot of air units, they can crowd in the spot that you wanted to modify or rebuild. And it can be quite tedious to move everyone when there are a lot of them.

This small tweak will help to speed up building and make it easier to react quick enough to, for example fix the thorium reactor.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by antonilol** [comment]
Same problem as https://github.com/Anuken/Mindustry-Suggestions/issues/1376#issue-752954749

**Comment by DragonMadness** [comment]
Does that mean that i have to close my request?

**Comment by kiVts** [comment]
So air units should move away from you like 'KING IS HERE!' 'MAKE WAY FOR THE KING!'

**Comment by DragonMadness** [comment]
Yes, I think that it would be quite useful. You got it just right

пн, 7 дек. 2020 г. в 20:13, kiVts <notifications@github.com>:
