### ISSUE TITLE
skip build cycle for just rotation changes

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1371]
**Describe what you would like changed, and why.**

current if you place the same block over another of the exact same block but with a different rotation it redoes the build cycle.

this wasn't a big deal with conveyors & conduits, but now with reconstructor blocks its taken to an insane degree.

(building materials lost, as well as whatever expensive unit is/was in the conveyor, precious time, item module, etc)

**Describe the changes you want to propose. Include possible alternatives.**

for the build queue to just call rotate on any request where the rotation is the only difference.

i'm wiring this mostly out of frustration from players who do not understand rotation, e.g. when i deliberately rotate a reconstructor to have an unit output early, only for them to "fix" the rotation by building again over it, what a loss.

![4o8fmf](https://user-images.githubusercontent.com/3179271/100540725-4cef1f00-323f-11eb-9cdb-b50cef86a99d.jpg)

**Comment by Arackulele** [comment]
i mean y ou can rotate blocks with the R key on pc at least

**Comment by Quezler** [comment]
yes, i know, but the problem is that some people don't understand that or play on mobile, and just build over the existing block causing it to get built again from scratch, instead of just rotating ^

**Comment by MEEPofFaith** [comment]
Haha 4000 surge alloy for tetrative to brrrrr

**Comment by Quezler** [comment]
looks like this got implemented

**Comment by scarf-generic** [comment]
woo

**Comment by scarf-generic** [comment]
i suggested this a while ago let me find it

**Comment by scarf-generic** [comment]
#1143

**Comment by Quezler** [comment]
interesting

**Comment by scarf-generic** [comment]
> interesting, wasn't aware nor checked, but i'm glad it made it in now 😇

yeah, me too. thank you, this makes life a lot better for mobile players ❤️
