### ISSUE TITLE
Android: Pointer Capture implementation, or any mouse location related features present on PC

### ISSUE THREAD

**Issue by pimikiel** [Anuken/Mindustry-Suggestions#1372]
Hi.
Is there are any chances of implementing pointer capture feature to Android's version of Mindustry or any mouse tracking?

Using mouse on a PC is diffrent than using it in android regardless of control change in a settings. Building new structures does not follow a cursor, building infos doesn't show up unless you click on it, etc, and obviously a cursor style does not change to what is seen on a PC version

I play Mindustry on a PC as well as on samsung DeX using mouse and keyboard, and I wish there was a pointer capture implementation since it's avaible from android 8 and higher to make it more similar to PC version while using mouse and keyboard.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
cant you just enable it in developer options

**Comment by pimikiel** [comment]
There is no such feature to enable in developer options. This needs to be coded into the app. What I'm talking about is not about mouse not being present. Mindustry does not track it's position, only clicks. With pointer capture you could change it's visual appearance as well.
