### ISSUE TITLE
Illuminators working like power nodes for other illuminators

### ISSUE THREAD

**Issue by SomeRandoGithubber** [Anuken/Mindustry-Suggestions#1373]
I think that it would be better it was that illuminators can transfer power to other illumintaors, either im doing it wrong but ive noticed the the line of power nodes that i placed to power the illuminators can light up the area almost as well

1. - [ X ( a bit) ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X ( a bit ) ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
                            ??? /\ ????

**Comment by RedstonerKBC** [comment]
Also can we increase the contrast of the illuminators? The black and white lights look almost exactly the same. I can't even tell what colors which illuminators are shining.

**Comment by itcannotbe** [comment]
Black be like: Why do I feel useless? Wait...... Black is the absence of light right?
Black: Ohhhhhhhhhhhhhhh

**Comment by Bottinator22** [comment]
You can barely notice the colour of illuminators, because they constantly produce normal light even with black. Maybe change the illuminators so they produce no light passively, instead only producing configured light.

**Comment by itcannotbe** [comment]
> You can barely notice the colour of illuminators, because they constantly produce normal light even with black. Maybe change the illuminators so they produce no light passively, instead only producing configured light.

That's very similar to #742
