### ISSUE TITLE
Rename corvus unit

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry-Suggestions#1374]
**Describe what you would like changed, and why.**
There is a unit named corvus, in Latin this means raven and is not the best name for a ground unit.

**Describe the changes you want to propose. Include possible alternatives.**
(i have no idea for alternatives)

**Comment by Kyllingene** [comment]
Interesting point, however I do not believe that there is any problem.
Also, try renaming the issue to "Rename Corvus Unit" or something similar (I thought you were requesting a new unit)

**Comment by sample-text-here** [comment]
If you looked at the names, the other ground support units' name theme is "objects in space".

So that means that the corvus that Anuke meant was not "raven", but [this](https://en.wikipedia.org/wiki/Corvus_(constellation))

**Comment by Humanoid-X** [comment]
Nova    : A type of, umm, exploding star?
Pulsar   : A type of rapidly spinning neutron star
Quasar : The mysterious quasi-stellar-object
Vela      : A constellation
Corvus : A constellation

**Comment by Quezler** [comment]
face the raven from dr who is a scary countdown of death you can't escape 👀

**Comment by catatagun** [comment]
![Screenshot_2021-01-13-00-30-56](https://user-images.githubusercontent.com/76461235/105249404-adaf1f80-5b3d-11eb-8e34-9acc0f340c6b.png)
