### ISSUE TITLE
A small Quality of life inprovement : Buttons, and or timers in processors

### ISSUE THREAD

**Issue by SomeRandoGithubber** [Anuken/Mindustry-Suggestions#1375]
Buttons or even a timer command would be super usefull in minedustry v6 with all the logic, Buttons make it so that if you only want something to be active for a sertian amount of time you dont have to sit there and wait for it to finish to turn the swutch off, also when trying to make buttons using switches that turn of instantly it sometimes doesnt render in which could be a problem.

**Comment by QmelZ** [comment]
good job on removing the template, what you said already exists in the game.

**Comment by DeltaNedas** [comment]
see RTFM logic examples, using a switch as a button

**Comment by scarf-generic** [comment]
you can use unix time with `@time`.
you can enable things if a condition is met with `control`
close this, both things are already in the game.

**Comment by itcannotbe** [comment]
This is mindustry, not minedustry.

**Comment by Humanoid-X** [comment]
[X]I am incapable of reading, comprehending, and filling out the template, but capable of deleting it   entirely.

(Credit : itcannotbe)

**Comment by QmelZ** [comment]
> [X]I am incapable of reading, comprehending, and filling out the template, but capable of deleting it entirely.
> 
> (Credit : itcannotbe)

thank you for this
