### ISSUE TITLE
Unit transparency toggle, to see buildings/terrain underneath units

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry-Suggestions#1376]
**Describe the content or mechanics you are proposing.**

Create a keybind to toggle unit transparency, so that user can see buildings/terrain underneath units without having to force those units to move. This must also disable unit selection/hover info so that buildings can be interacted with/inspected.

Units should still be visible, just semi-transparent. Perhaps reuse the "power laser opacity" graphics setting to allow user to configure transparency.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This is useful if units are your defense, as moving them can be dangerous if you cannot get them back in place before the next wave arrives. On some maps, the wave timer is so fast that moving units away from the enemy spawn is never feasible.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by antonilol** [comment]
Also annoying when you have hundreds of miner drones and you can't see thing near the core.

**Comment by antonilol** [comment]
Same problem as https://github.com/Anuken/Mindustry-Suggestions/issues/1370

**Comment by joshuaptfan** [comment]
No, not the same at all. My suggestion doesn't involve moving units out of the way.

**Comment by Bohaska** [comment]
> Same problem as #1370

Which is the same problem as https://github.com/Anuken/Mindustry-Suggestions/issues/873 which is the same problem as https://github.com/Anuken/Mindustry-Suggestions/issues/103

**Comment by Bohaska** [comment]
Stop making duplicates of suggestions, both of you!

**Comment by joshuaptfan** [comment]
I was wondering how it could be that no one had suggested this before.
