### ISSUE TITLE
Folders for schematics

### ISSUE THREAD

**Issue by a-letter** [Anuken/Mindustry-Suggestions#1377]
Player can save schematics in folders.

It help finding the right scheme a lot faster. I have over 120 schematics in my library and most of them are experimental or just useless, which create a lot of frustration when trying to find the right one. However, this frustration can be easily avoided with a better saving system, I recommend saving in folders.

This feature will not affect normal players much, but it would definitely increase the productivity of map makers and schem designers.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
this has been suggested before

**Comment by scarf-generic** [comment]
#1206

**Comment by scarf-generic** [comment]
#220

**Comment by scarf-generic** [comment]
#706

**Comment by scarf-generic** [comment]
#460

**Comment by scarf-generic** [comment]
> [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

you know you are supposed to do the thing next to the box before you place an x in it right

**Comment by DeltaNedas** [comment]
h

**Comment by itcannotbe** [comment]
Basically he removed everything from the template aside from the checkboxes.

**Comment by Humanoid-X** [comment]
We should reaklly put this into Do Not Suggest List

**Comment by sample-text-here** [comment]
>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

\*doesn't search\*

\*checks box anyway\*

nooooo aaaaaaaa you cant do that
