### ISSUE TITLE
conveyor upgrade pathfinding

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1379]
**Describe what you would like changed, and why.**

for the conveyor pathfinding mode to path along the current conveyor only if the starting position is also a conveyor & pointing in the same direction.

**Describe the changes you want to propose. Include possible alternatives.**

so you can easily upgrade a line of conveyor by just dragging from the start to the end tile in one go.

![Untitled](https://user-images.githubusercontent.com/3179271/100548928-2bf2f200-3270-11eb-9185-44ef237eebdf.png)

**Comment by DayatXD** [comment]
if this get implemented, we'll able upgrade conveyor faster than before!

**Comment by itcannotbe** [comment]
Isn't this somehow implemented/has a PR already?

**Comment by Kyllingene** [comment]
Yeah, I recall seeing a PR about upgrading conveyors on the repo.

https://github.com/Anuken/Mindustry/pull/3912
