### ISSUE TITLE
Ban / Vote Kick is based on UUID which a user can easily change

### ISSUE THREAD

**Issue by jeffcollar** [Anuken/Mindustry-Suggestions#138]
In a recent game a user started griefing another player by destroying everything they built.  The user started a vote kick which failed but resulted in the griefer threatening them and others in chat.  They then started to greif the entire team.  Another vote was held and the user was vote kicked.  Within 30 seconds they rejoined with a new UUID.  The user was vote kicked repeatedly but continued to change UUID, join the game, and grief.  They ended up griefing both teams, both teams were kicking repeatedly but the offending player just kept rejoining with a new UUID.

I know an authentication system for servers is being developed and perhaps that will address this issue but in the meantime it is too easy for a single player to ruin a multiplayer game.

(griefing is sometimes mis-used - in this case I mean a user deleting belts near the base and removing large sections of the map)

**Comment by Katsute** [comment]
IP ban could be a potential solution

**Comment by itcannotbe** [comment]
Given the fact that the method of evading bans is advanced enough not anyone can do. And an authentication server is not too cost effective for a FREE GAME. I think there is not much you can do in thay senario. Also FYI actual bans are not just UUID based.

**Comment by DS-3K** [comment]
At least steam using me can´t change that xD

Am Fr., 1. Mai 2020 um 04:51 Uhr schrieb itcannotbe <
notifications@github.com>:

**Comment by potatoisagender** [comment]
Mindustry is free? I paid on steam...

**Comment by itcannotbe** [comment]
You paid it on steam for steam features. It is free for most platforms, but they don't have access to steam features @potatoisagender

**Comment by potatoisagender** [comment]
steam features like?

**Comment by Katsute** [comment]
workshop & achivements

**Comment by itcannotbe** [comment]
Don't forgot steam has steam assisted multiplayer.

**Comment by potatoisagender** [comment]
oh. Didn't know that. Cool. (What about the ability to have multicolour names)

**Comment by itcannotbe** [comment]
Unfortunately, Player Names on the steam version are tied to your steam username.

**Comment by DeltaNedas** [comment]
admins can already ip and rangeban

**Comment by Anuken** [comment]
There is no way to fix this.
