### ISSUE TITLE
console should use hack

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1380]
**Describe what you would like changed, and why.**
The console uses the regular font which is not monospace.
bad.

**Describe the changes you want to propose. Include possible alternatives.**

Including and using Hack for F8's console and log.
Other monospace fonts would do.

**Comment by joshuaptfan** [comment]
This issue's title is deceptive, it should be renamed "Console should use monospace font".

**Comment by YellOw139** [comment]
Or how about a monospace version of the current font? I don't see why this wouldn't be doable, provided someone with enough competence makes an attempt.

**Comment by Bohaska** [comment]
What characters would we require for this? I don't want to do all of Unicode.

**Comment by sample-text-here** [comment]
> Or how about a monospace version of the current font? I don't see why this wouldn't be doable, provided someone with enough competence makes an attempt.

![image](https://user-images.githubusercontent.com/56274831/100579506-34abee00-3299-11eb-8be1-2e324d8c27c7.png)

**Comment by YellOw139** [comment]
@sample-text-here I know. It's me who asked (you can check the Discord username). Right after I shared my opinion about it on here.

Nice attempt at helping though!

**Comment by sample-text-here** [comment]
h

i am dumb
