### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by SomeRandoGithubber** [Anuken/Mindustry-Suggestions#1381]
Can you add a undo button to the logic processors in v6, I was coding a graph that can express how much electricity i stored over time but a miss click made me import previous work and erased my current work. I think that it would be extermely helpfull if you added a undo and redo button for the small mistakes we make

**Comment by DeltaNedas** [comment]
nano has meta-u and meta-e for undo and redo

**Comment by Kyllingene** [comment]
nano? what does nano have to do with mindustry logic?

**Comment by mangblekok** [comment]
Related to #1362  🍔
