### ISSUE TITLE
New ground unit (Spider)

### ISSUE THREAD

**Issue by ToorpedoXPshARK** [Anuken/Mindustry-Suggestions#1382]
A new spider-shaped ground unit, which in its first upgrade has 4 legs and uses a continuous laser to attack. In its second upgrade it is bigger, with 6 legs and attack with a charging laser. In its third improvement, add two more legs for a total of 8 and acquire another laser, one on each side that attacks the same as the previous improvement and that for its last improvement has a total of 12 legs, an immense size and three lasers , two on the side and one central that is continuous.

"Translate with Google Translate"

**Comment by Bohaska** [comment]
Have you ever tried toxopids?

**Comment by Humanoid-X** [comment]
Crawler, Atrax, Spiroct, Arkyid, Toxopid & Corvus : exist

**Comment by Mothership007** [comment]
To my knowledge, spider units already exist, they work a bit differently. Crawler->

**Comment by UnionofSovietSocialistRepublics** [comment]
toxopid atrax spiroct arkyid corvus vela is spider

**Comment by Humanoid-X** [comment]
vela is not

**Comment by Mothership007** [comment]
> vela is not

Yes it is, the spider legs are short, but they are there. Also it can WALK through walls so it is a spider.
