### ISSUE TITLE
Don't Allow Overage Selection, Max Resources Button, Combine Interfaces (Campaign)

### ISSUE THREAD

**Issue by JesseFlorizone** [Anuken/Mindustry-Suggestions#1383]
I grouped this as one suggestion as not to have to explain myself each time, it is entirely about _resource selection_ for Campaign mode.

When you go to launch to another sector and you are trying to launch with as many resources as you can it is frustrating to spam click the **+** buttons for each resource. Further more, you then often end up _selecting too much_, selecting _back_, and seeing that you are in the _red zone_. You then need to go back and try to select a correct amount or enter it in manually number by number.

### Three suggestions
1. **Don't allow selection** past what is available. What is the point of being able to select 6000/5465 copper and have it tell you that you don't have enough, the + button should just go 4000 -> 5000 -> 5465 and cap out if that's all you have available.

2. **Add a "Max" button for each resource**, this way I can click maybe 6 times to get everything I want to launch instead of clicking 60 times. 

3. **Combine Resources with Core Select**, remove the resources button, people ALWAYS click the resources button so I believe it should be front and center, and I believe there is space for the resources on the core select page. In my opinion this would feel way more polished, smooth/streamlined , and enjoyable.

This would be a HUGE improvement for a relatively small amount of work that will undoubtedly be a great addition to the game. I think the issue has been unnoticed because experienced who contribute here are the same players who focus a lot on Multiplayer. However, many new players play a lot of campaign, and experienced players will be revisiting it with this update.

Thank you so much for reading my post. I hope it was understandable. It there is anything you need clarification on please do not hesitate to reply.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Why is the title "Don't allow over-age selection"???

**Comment by JesseFlorizone** [comment]
> Why is the title "Don't allow over-age selection"???

It isn't over-age, its overage,
Overage Definition - 
an excess or surplus, especially the amount by which a sum of money is greater than a previous estimate.

**Comment by captainju** [comment]
I was about to make the same feature request.

For the 2nd point, we could also have a global "max" button for all the resources at the same time.

**Comment by h3rlihy** [comment]
Completely agree with this. Would be super helpful

**Comment by captainju** [comment]
A "max" button has been added, very useful !!
