### ISSUE TITLE
New Map type: Planet

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#1384]
**Describe the content or mechanics you are proposing.**

A new map type that could be selected when creating a new map in the editor (i.e. a new button for it, or a selector between normal and campaign type.) This map type could for one, have a option to import .msav files for every sector, two, add a generation option (similar to the one in the editor, but for the entire planet,) or three, a mix of both, with importing certain sectors and procedurally generating the rest (like the current campaign.)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

For one, this could solve issue #3245, two, it would add a lot more options for mapmakers. This content will improve the game by adding the ability to create your *own* campaign, and being able to play it. (possibly with a hosting system like the current one in the campaign)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
(This has been, but this is an entirely different take on it)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by parkuristt** [comment]
sounds nice

**Comment by Bohaska** [comment]
Didn't you copy my suggestion???

**Comment by nichrosia** [comment]
My suggestion is similar but contains more detail.
