### ISSUE TITLE
Option to switch to basic loading screen

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#1385]
**Describe the content or mechanics you are proposing.**
A switch somewhere in settings that will either use the old v5 loading screen or the new one from v6

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

My poor pc really hates all the animations

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
h
![IMG_20201130_112450](https://user-images.githubusercontent.com/70744599/100568792-c26df480-32fe-11eb-9027-e11de93284e6.jpg)

**Comment by Anuken** [comment]
The loading animation is not slowing you down.

**Comment by QmelZ** [comment]
animation might not intentionally slow you down but bad pcs like mine lags when the animation plays.

**Comment by BlueWolf3682** [comment]
thats cause loading the entire game is laggy, not the animations themselves

**Comment by Anuken** [comment]
Exactly. The loading screen is also super "laggy" in 5.0 too, you just can't tell because it's so simple.

**Comment by itcannotbe** [comment]
Even if you took the loading screen out, loading times will be the same, but, you'll be stuck with a dull screen.

**Comment by QmelZ** [comment]
> Exactly. The loading screen is also super "laggy" in 5.0 too, you just can't tell because it's so simple.

6.0 loading lags my whole pc. 5.0 loading doesn't.

**Comment by Anuken** [comment]
Yes.

**Comment by QmelZ** [comment]
okay
