### ISSUE TITLE
expansion for modding

### ISSUE THREAD

**Issue by DrPhagon** [Anuken/Mindustry-Suggestions#1386]
Requests (for modding):

-output array (for multiple outputs)
-output for impact and thorium reactor
-impact reactor should accept JUST items as input too
-solar-processor ... A machine how work more efficient, more higher the sun is but does not work at night (like solar just with items and fluids) (as example for solar thermal water evaporator)

**Comment by Gdeft** [comment]
**All the thing you mentioned can be done with scripts.** JSON-only mods can only use the class that exists in the game (or "built-in" basically). To create a custom one, as mentioned above: use scripts.

> multiple outputs

This exists, see [younggam/multi-lib.](https://github.com/younggam/multi-lib)

> output for ...

`extendContent` on the power generator and use `dump` and more stuff.

> impact reactor should ...

h

> solar processor ...

what

**Comment by D-player1** [comment]
Bruh
