### ISSUE TITLE
An endgame conveyor

### ISSUE THREAD

**Issue by coolestuserever** [Anuken/Mindustry-Suggestions#1387]
A conveyor that can transport multiple types of items on top of each other, almost like stacking conveyors. Items automatically get put into different conveyor layers when they get loaded onto the conveyor. You can pull out a specific item type from one of the layers using a sorter, or it could just output all into into nearby normal conveyors similar to the plastanium conveyors. It would likely be something 'phase' related. the different items on the conveyor would occupy the same space but wouldn't interfere with each other. It would only have a limit of 2-3 different item types occupying the same space at the same time.

It's a creative way to add more efficient conveyor belts without straight up making it faster. It could serve as the absolute end of the game conveyor belt. It also has unique properties like some of the other conveyor belts which could be helpful in certain situations.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
Plastanium is the best that you will get and anuke will not be adding any new conveyors as I don't think there is a reason for one.

**Comment by BlueWolf3682** [comment]
*this is just bridge stacking in a single tile lmfao*

**Comment by itcannotbe** [comment]
Does this fall under "additional configuration of blocks"?

**Comment by sample-text-here** [comment]
phase conveyors?
![image](https://user-images.githubusercontent.com/56274831/100651348-293cdf00-32fa-11eb-9c3e-b3bc3a399123.png)
