### ISSUE TITLE
Fungal pass is a bit too easy for a "hard" enemy base.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1388]
**Describe what you would like changed, and why.**

The enemies are fine and I can find someone not prepared to struggle with them but the structures themselves are way too weak and I can find myself breaking everything with my maces in 10 waves. 

**Describe the changes you want to propose. Include possible alternatives.**

I think using thorium walls is the best you can do as I know you want to keep the old maps similar in v6. Possibly also change/add a few weapons such as a lancer or a wave just to spice things up a bit from just duos, scatters, hails, and scorches. 

Otherwise, you can also just change it from hard to medium.

**Comment by Bohaska** [comment]
Make your own improved fungal pass first! You can download fungal pass in a .zip file here.
[fungalPass.msav.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5639315/fungalPass.msav.zip)
