### ISSUE TITLE
this is a terrible but realistic idea

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1389]
Hear me out. This is a very bad idea but one that will make the game much more realistic.
Payload units carrying blocks or units with explosive or flammable items/liquids should cause an enhanced detonation or fireball when the unit goes down with the cargo. Batteries and such should cause arcs.
This would make payload units unbalanced in PvP, but wouldn't make people facepalm when their mega with a container of coal hits dirt and doesn't explode more violently.
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
5. - [X] Every PvP player will hate me for this if it gets implemented.

**Comment by D-player1** [comment]
This is why Zenith should get buffed

**Comment by mangblekok** [comment]
Since coal bombing is now obsolete, the next thing is 'battery bombing'? 🤣

**Comment by BlueWolf3682** [comment]
no, oil tank nuking

**Comment by HaphLife** [comment]
> no, oil tank nuking

Maybe crash a slag tank into steam generators.
