### ISSUE TITLE
Machine State Indicators as Part of the Sprite

### ISSUE THREAD

**Issue by DARK0717** [Anuken/Mindustry-Suggestions#139]
**Describe what you would like changed, and why.**
Make the machine state indicators part of the sprite (or atleast look like it is)
In the dev-previews, it looked quite intrusive (in a sense, especially with smaller machines) when a lot of machines are packed together

**Describe the changes you want to propose. Include possible alternatives.**
a small triangle (slantingly halved square) in the lower right corner of machines. The indicators will look like a small screen inside a machine. instead of a UI on top of a machine.
Maybe the state indicators be permanent OR there be an option to toggle indicator-less sprites.

**Comment by DS-3K** [comment]
Nice name
Anyway, at least most machines except pumps look different depending on
their state.
They have animations to indicate that they are currently working, so what
is it that you are suggesting?

Am Fr., 1. Mai 2020 um 14:17 Uhr schrieb DARK0717 <notifications@github.com

**Comment by DARK0717** [comment]
If uve seen the dev preview for machine ste indicators in the discord
server, it's a diamond shaped icon on the lower right of machines, orange
is output error and red is input error

**Comment by potatoisagender** [comment]
Pumps also have look different. It is a small difference, but the little circle in the middle changes depending on if you are pumping water or oil./
