### ISSUE TITLE
Cheapen scatter cost + build time

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1390]
**Describe what you would like changed, and why.**

 For a starter weapon, it's too painful to make and I think it's also much too expensive. It's also pretty mediocre at defending later waves or in PVP, t3 air units.

**Describe the changes you want to propose. Include possible alternatives.**

 I think the damage it does stays the same but make it take ~30 copper and ~30 lead instead of what it is now and let the build time be ~0.8 seconds rather than 1.23 seconds.

**Comment by BlueWolf3682** [comment]
~~make scatter op like in v5~~

**Comment by itcannotbe** [comment]
~~Why the fuck would you expect an early game turret to be reasonably effective against T3s?~~

**Comment by D-player1** [comment]
> PVP

I see

T3 Reconstructor takes 650 thorium, this means you already have graphite, titanium, and silicon.by that time you can already afford parallax, T3 costs 40 metaglass in their build cost, means you can afford metaglass Scatters. Or even better, Thorium Salvos, the only problem here is that you have to build it all around your base, but you can use parallax to pull air units. So the conclusion is:

Git Gud

**Comment by DeltaNedas** [comment]
change nothing about damage, only make it cheaper

**Comment by the-kido** [comment]
i said dont do anything with damage already

**Comment by the-kido** [comment]
> ~Why the frick would you expect an early game turret to be reasonably effective against T3s?~

I actually have no clue why I mentioned that. This is the closest I've felt like I've been on drugs.
