### ISSUE TITLE
Usable ruins

### ISSUE THREAD

**Issue by SpaceTime-exe** [Anuken/Mindustry-Suggestions#1391]
**Describe the content or mechanics you are proposing.**
In V6, the ruins on campaign like the spectre or thorium reactor on Nuclear Production complex should be usable and shouldn't just be there taking up space.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will makes sense that surviving structures would still work.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EnganK** [comment]
1) Start demolishing the building
2) Immediately after the start of the demolition, cancel it
3) Click on the building to complete it
The ruin building now belongs to your team and can be used.

**Comment by Humanoid-X** [comment]
Close this issue

**Comment by RedDragonMZ** [comment]
I think its not about that you cant claim it.

New players dont know how to capture blocks

**Comment by Chiel92** [comment]
The method described by @EnganK is quite convoluted and labor intensive. I think a feature that would allow and encourage users to use existing structures makes a lot of sense. This would also allow for all kinds of very cool scenarios based upon a post apocalyptic narrative or something of the like.

Of course such a feature should be implemented in such a way that enemies don't destroy unused ruins. So ruins cannot simply be owned by the player from the start.

**Comment by dramageek** [comment]
What if the ruins could be repaired via regular methods (mender, poly, etc.) to 'claim' them? @EnganK 's method works for lone structures, but takes too long for anything more than a couple. This method would still impose a cost (building/spawning menders) to claiming them.

**Comment by Kyllingene** [comment]
> The method described by @ EnganK is quite convoluted and labor intensive.

***What.*** I cannot imagine how anyone could call clicking (or tapping) twice "quite convoluted and labor intensive". Sure, and dramageek pointed out, it takes a bit for more structures, but not very long on PC, and not much longer on mobile (and everything is already slower on mobile).
