### ISSUE TITLE
QoL - coloured text for research prices

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1392]
Research panel
It would be nice if the colour of the amount of resources that remains to be paid reflected whether you can afford it.

0 of resource = red (this is already in game)
1 to < full payment = Orange
>= full payment = green.

Currently the later two are both grey.

**Comment by Bohaska** [comment]
Lemme try to make a pull request for it.

**Comment by Bohaska** [comment]
I can't find out how to do it.
