### ISSUE TITLE
Armour piercing - Tutorial & stats

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1394]
Beta 119
Couple things:
1) It'd be very useful to know that guardians require armour piercing ammunition BEFORE the first guardian turns up (tutorial tip). Telling a player their copper powered duo's are a waste of time just as a guardian's hammering at them is far *far* too late.

Also of course, during their first guardian is a bad time for a tutorial tip because the player's attention is going to be focused elsewhere (namely their crumbling front line); they're unlikely to have the time to read the message.

2) Some indication as to what ammunition is "Armour piercing" on the turret's stats.

(It's a nice change btw, just needs to be clearer to the player)

**Comment by Anuken** [comment]
1. The guardians you get in the first few presets are easy enough to defeat without any special ammo.
2. There is no armor piercing property. More damage is simply better against armor.

**Comment by CitrusWire** [comment]
> 
> 
>     1. The guardians you get in the first few presets are easy enough to defeat without any special ammo.
Well, I lost against the tar-sands one and I can handily hold my own against almost anything in 5.0 (got up to wave several hundred on most levels before launching), at least with the fully researched tech tree. It was 50% down by the time it had finished laying waste to my thorium coated front line, and I suspect most of that was the Lancers (best I had).


>     2. There is no armor piercing property. More damage is simply better against armor.

I have no easy way to check now, but I could have sworn the tooltip blurb said that ammo like copper etc did no damage, rather than "little damage", and implied there was an armour piercing ability. But as implied, I was a little distracted at the time, so didn't parse it fully... :-/

**Comment by Anuken** [comment]
> Well, I lost against the tar-sands one

That's a later-game sector. You're likely running an older version where previous preset sectors did not have guardian appearances.
