### ISSUE TITLE
libretro port? :3

### ISSUE THREAD

**Issue by DartPower** [Anuken/Mindustry-Suggestions#1395]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/100677722-9e7bd480-3339-11eb-95f2-6efb92a2d84a.png)

Looks like this would involve porting the entire game over to C, C++ or a language that compiles to either, which... just isn't going to happen. Everything notable is currently written in Java, and porting it over to a completely new framework and language will not be viable.
