### ISSUE TITLE
Big version of unit repair point

### ISSUE THREAD

**Issue by PhilipPurwoko** [Anuken/Mindustry-Suggestions#1396]
**Describe the content or mechanics you are proposing.**
In late game defense mode, I often used units (dagger, revenant, titan mech, etc) in front line. I used command center to rally the units for better position. After surviving waves, my units is repaired by repair point.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
By having the big version of repair point, it would be much effective if I had big version of repair point to mend my units in area effect. This is for end game feature so it could be expensive considering the balance of the game mechanics. But it would make end game longer to achieve.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - x[] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[LOL NOPE] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
#759 be like: 🔪

**Comment by D-player1** [comment]
Just spam the small one

**Comment by sample-text-here** [comment]
noooo if you check a box that means that you did it

> -[x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

noooooo stoppppp please search first please

**Comment by scarf-generic** [comment]
how to make 2x2 repair point:
1. place 4 repair points in a square (note: this is 4x as expensive as a 1x1 repair point)
2. provide power (note: will consume 4x as much power)
3. heal units! (note: heals 4x as fast as a repair point)

**Comment by PhilipPurwoko** [comment]
What I mean is healing units in area. Like mender, but for units
