### ISSUE TITLE
Escape (menu) button should first deselect currently selected item

### ISSUE THREAD

**Issue by lostmsu** [Anuken/Mindustry-Suggestions#1397]
**Describe what you would like changed, and why.**

This is the first instinct. You select something (a turret to build) - you hit Escape - selection goes away. I know I am supposed to do a right-click, but I still hit Escape first.

**Describe the changes you want to propose. Include possible alternatives.**

When you hit Escape, clear selection. Only when there's no selection, open the game menu.

**Comment by GlennFolker** [comment]
Your instinct sucks then

**Comment by genNAowl** [comment]
In all the games I play, esc opens the game menu. If your instinct makes you want to hit esc, than you can probably change the keybinds in settings
