### ISSUE TITLE
Tinting while hovering over Overdrives or Menders

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#14]
**Describe the content or mechanics you are proposing.**
When your mouse hovers over/you tap on an Overdrive or Mender, blocks in their range have an orange/green tint applied respectively. Helpful to make sure something on the edge is actually in or not. Also, apply these tints when you have Overdrive/Mender selected for building.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Really, It's just a small quality of life thing.

**Comment by MEEPofFaith** [comment]
Represents what I was thinking, so I'd say yes.

**Comment by DeltaNedas** [comment]
@MEEPofFaith close
