### ISSUE TITLE
Naming against your steam username on multiplayer.

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#140]
**Describe what you would like changed, and why.**

I´d like the ability to edit your name in the steam Version, and if it is necesarry, on the player server list have the steam name stand in a smaller fond bellow.

**Describe the changes you want to propose. Include possible alternatives.**

I don´t see why the paid version should have a disadvantage over the free version. I´m sure you have great reasons for having the steam username forced but please find a compromise.
Anyway, thank you for taking the time to read this feedback. Have an amazing week,

**Comment by DeltaNedas** [comment]
that implementation of nick + username is exactly what i imagined

**Comment by DeltaNedas** [comment]
@DS-3K close, implemented
