### ISSUE TITLE
foreshadow is too effective

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1400]
**Describe what you would like changed, and why.**
1350 damage per 1 surge... is too effective. E.g. frag surge bullets per surge (cyclone) deals max. 250 dmg (actually not cos of accuracy).
Also T5 require 600 surge, and you need just only like 10 shots (10 surge) to wreck them. Yes, It needs power but not as much really.

**Describe the changes you want to propose. Include possible alternatives.**
I want to make shots more expensive (ammo multiplier = 0.1).

**Comment by GreyMario** [comment]
Have you taken the two seconds it requires to calculate the total damage you get from one piece of Surge Alloy in each weapon?

Have you taken the three seconds it requires to calculate maximum DPS for each weapon?

Have you factored in build costs, build speeds, and other relevant input resources?

**Comment by GreyMario** [comment]
Have you also considered gitting gud and not feeding a T5 to the enemy's Foreshadow first thing?

**Comment by GreyMario** [comment]
Have you considered that maybe it's not Anuke's job to banish every single little thing to Brazil just because you didn't want to learn how to deal with it?

**Comment by itcannotbe** [comment]
You forgot you also need power to make a foreshadow shoot.

**Comment by Slava0135** [comment]
***FORESHADOW:*** 15 surge and 30000 energy to destroy Eclipse

**Comment by Slava0135** [comment]
***CYCLONE: 160 surge***

**Comment by Slava0135** [comment]
***SWARMER:*** 600 surge

**Comment by Slava0135** [comment]
@GreyMario and you say it is balanced ok

**Comment by Slava0135** [comment]
yes, they are cheaper to build but once built foreshadow is op

**Comment by Slava0135** [comment]
> You forgot you also need power to make a foreshadow shoot.

30k is nothing

**Comment by BlueWolf3682** [comment]
the single target damage per shot and the range are whats op about it, though the range is normal for a railgun style weapon it deals a biiiit much for damage

**Comment by sample-text-here** [comment]
> CYCLONE: 160 surge

> SWARMER: 600 surge

you forgot that cyclones and swarmers can damage multiple enemies at once.

**Comment by SupremeTurtle** [comment]
I would agree on increasing the item it consumes per shot, but I disagree that the damage is too much.

**Comment by Bohaska** [comment]
Everyone, what is your final conclusion about the Foreshadow? I will make a pull request shortly if needed, and cite you for suggesting the changes.
