### ISSUE TITLE
Simply a nuke

### ISSUE THREAD

**Issue by KingBoom34YT** [Anuken/Mindustry-Suggestions#1401]
It's a nuke....
I mean what do that do the best "deleat any living and or nonliving object"
Honistly I dont expect this to eavin be remotely implemented 
But hay it's your choice

**Comment by hadron13** [comment]
you literally killed the template
also, it's already planned in Trello

**Comment by KingBoom34YT** [comment]
Ight I'll close this than and I didint see anywhere whare it sead it whuld be cumming to the game
