### ISSUE TITLE
Change the image shown in discord embeds

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#1403]
**Describe the content or mechanics you are proposing.**
Change the image shown in discord embeds
![image](https://user-images.githubusercontent.com/57631841/100751082-2ff55000-33e7-11eb-8ef5-ce1ed3b11568.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When you send a link on discord and have perms to embed stuff, it shows an older image with v5 unit factories. I don't know where else this image is shown or where it is stored but thought I'd suggest you change it to show v6 unit factores / maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
lol

**Comment by braainsiogame** [comment]
.

**Comment by genNAowl** [comment]
H

**Comment by Humanoid-X** [comment]
LOL that's funny.
Really gotta change it.

**Comment by Catchears** [comment]
Seems to have been changed.
