### ISSUE TITLE
 Virtual joystick

### ISSUE THREAD

**Issue by Krizis112** [Anuken/Mindustry-Suggestions#1404]
Add a virtual joystick for more comfortable control of combat units for Android and IOS

**Comment by itcannotbe** [comment]
[X] I am incapable of reading, comprehending, and filling out the template, but capable of deleting it entirely.

**Comment by Bohaska** [comment]
> [X] I am incapable of reading, comprehending, and filling out the template, but capable of deleting it entirely.
1. [X] - I am incapable of making an actual checkbox.

**Comment by Humanoid-X** [comment]
How did you make one!?
