### ISSUE TITLE
Make units already controlled by someone not controllable

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1406]
**Describe the content or mechanics you are proposing.**
The title.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently "unit stealing" is a major problem. 
(People fighting over 4 fortresses on survival, happens with any unit)
![изображение](https://user-images.githubusercontent.com/57039557/100777473-4cad7a00-341f-11eb-8bd7-bb02a2fafedd.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Wait so does this mean a unit that was previously controlled can now only be controlled by the original controller?

Or something else

**Comment by itcannotbe** [comment]
Simple, the previous owner must relinquish control one or another for the unit to be able to be controlled again.
