### ISSUE TITLE
Weather effect performance

### ISSUE THREAD

**Issue by valtsu41** [Anuken/Mindustry-Suggestions#1407]
I was playing PvP recently, and everything was running smoothly, untill a sandstorm happened. That made my fps drop to levels where the game was pretty unenjoyable. I play on Android, and my device is not from the most powerful end, and I don't think I can be the only one with this issue.

This is why I would like to suggest a way to reduce the quality of the weather settings. How that would be implemented is another question, but it would be nice to have even some way to avoid the fps dropping because of performance-heavy weather effects.

**Comment by the-kido** [comment]
same here my tablet is quite new and the hardware is low-end and it suffers when there is a sandstorm. Not so much rain but yeah.

**Comment by valtsu41** [comment]
Yes, the sandstorm is really the only one that makes gameplay difficult by dropping fps for me too.
