### ISSUE TITLE
non=static server list

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry-Suggestions#1408]
**Describe what you would like changed, and why.**
Community server list is not static, but arranged depending on client ping. Servers on the bottom may be at a disadvantage due to their placement. Should the server list be arranged by ping, the most enjoyable experience, network wise, would be on top, and the aforementioned issue mitigated.

**Describe the changes you want to propose. Include possible alternatives.**
Community server list arranged depending on client ping, like old server list.

**Comment by DeltaNedas** [comment]
yes
