### ISSUE TITLE
Suggestion: select unit before its being made

### ISSUE THREAD

**Issue by Coopyy** [Anuken/Mindustry-Suggestions#1409]
its really annoying having only want to make lets say a Mega unit, and having to cut the conveyor so that it goes free, and not to the exponential reconstructor. I recommend having all units of that type (flying, ground) selectable in the first constructor for however many constructors you have lined up. this way it would automatically spit out when the unit you've selected has been made

this update just came out but from what ive tested theres no way to do what i just described, unless theres a variable with logic to count units of type??

**Comment by sample-text-here** [comment]
rotate the reconstructor either by hovering over it, pressing r, and scrolling or by placing a rotated reconstructor on top of the old one

> unless theres a variable with logic to count units of type

there isn't one
