### ISSUE TITLE
Add option to change zoom behaviour whilst holding conveyor belt

### ISSUE THREAD

**Issue by technologicalMayhem** [Anuken/Mindustry-Suggestions#141]
**Describe what you would like changed, and why.**
It would be nice if there would be an option added to change how rotating and zooming works whilst holding a belt.

Currently whilst holding a belt trying to zoom out does not work like normal, you have to control since otherwise you are rotating the conveyor belt instead. I find this behavior inconsistent, since you can zoom out whilst having selected any other object except for the conveyor belt.

**Describe the changes you want to propose. Include possible alternatives.**
Adding a menu option that inverts this behavior (zooming out by default, rotating with control held) would be nice.

**Comment by zethnest** [comment]
Do you have any idea on how it should work? Or maybe how you want it to behave?
