### ISSUE TITLE
Illuminator range indicator

### ISSUE THREAD

**Issue by joaomarcosh** [Anuken/Mindustry-Suggestions#1410]
**Describe the content or mechanics you are proposing.**
Illuminator quality of life changes: Range indicator and smart placement like power nodes

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This change would make it easier to properly space out the illuminators

**Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.**
[x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
[x] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
[x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
[x] I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
may implement later

**Comment by Bohaska** [comment]
Range indicator? Up to where?
