### ISSUE TITLE
balance plastanium walls

### ISSUE THREAD

**Issue by bar0nch** [Anuken/Mindustry-Suggestions#1412]
Corvus is an exageratedly powerful unit but it has a weak point beeing the plastanium wall so it sould be already balanced. The thing is that plastanium walls make the unit totally harmless so now they just aren't an option. Basically you can defeat a corvus ONLY using plastanium walls and if you do so, defeating a corvus becomes a lot easier. I suggest making an attribute called electricResistance so the damage would be calculated like   actual damage / (100 * electricResistance)  that would also be a benefit for modding because you could set and modify that attribute for every wall. Others simpler ways to do it could be Increasing the amount of damage plastanium walls get from every attack, making a limit of attacks beeing blocked (ex: they could block weaker attacks but would not cover corvus ones) or just making corvus range and plastanium walls weaker.

**Comment by itcannotbe** [comment]
Actually, Plast walls are unique in that manner. They don:t let arcs nor lasers pass through them. So you have to deal with them in another manner. That said, there should be a lower tier plast wall.

**Comment by the-kido** [comment]
I do agree Corvus is pretty pathetic against plastanium. I think Corvus should be able to one-shot two platinum walls by letting corvus have a damage multiplier against plastanium. If you go against two corvuses then you're screwed and that is how it should be.

**Comment by DeltaNedas** [comment]
1. template
2. why would you use plast walls then? to block your own arcs and maybe lancers?
