### ISSUE TITLE
Add split screen or tabs to android

### ISSUE THREAD

**Issue by Rickcreate** [Anuken/Mindustry-Suggestions#1413]
**Describe the content or mechanics you are proposing.**

Adding split screen or tabs to android

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Enabling the player to play the game while simultaneously using other app like YouTube, Twict, Discord ect ect(Currently its not possible to do without the use of third app parties)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Android doesn't let you have more than 1 foreground app at the same time, unless I am proven wrong.

**Comment by DayTimer** [comment]
It does. In android ≥ 7.0, you can enable split screen mode (long-press the "last opened apps" button). 
Also you can enable the split screen mode for any apps in the developer settings

**Comment by mangblekok** [comment]
![Screenshot_2020-12-02-22-10-27-995_io anuke mindustry](https://user-images.githubusercontent.com/26910478/100890839-41278500-34eb-11eb-88ec-4671ca0f06be.jpg)
It works bruh, but you need to adjust the UI scale by going to Setting > Graphics > UI Scaling

**Comment by DeltaNedas** [comment]
@Rickcreate close this you egg

**Comment by Rickcreate** [comment]
Yes its work for some devices, but the thing is most of the device like mine for example literally said *mindustry does not support split screen*
![Screenshot_2020-12-03-14-00-53-42](https://user-images.githubusercontent.com/75365628/100967114-c5245000-3571-11eb-9a42-9d575b60b537.jpg)

**Comment by itcannotbe** [comment]
This would be pointless as I mentioned mindustry does not run while in the background.

**Comment by DeltaNedas** [comment]
then thats an issue with your device, not mindustry
