### ISSUE TITLE
Disable night

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1414]
I'm not sure if the "night" has any gameplay effect, but it's really hard to see stuff at night, especially on maps that are already dark. This is even worse if I'm playing in a well lit room. And I don't even have any visual impairments.

Given this, I'd like to be able to disable the "night".

**Comment by D-player1** [comment]
Imagine if you can see at night IRL

**Comment by mangblekok** [comment]
Isn't there illuminator to light up your surrounding area?

**Comment by CitrusWire** [comment]
> 
> 
> Isn't there illuminator to light up your surrounding area?

Yes, but that's a gameplay solution, not an accessibility solution.

My issue is seeing things like coal seams on dark ground textures. They're already hard to spot in daylight when they're on the black textures; there's basically 0 contrast between them in night mode.

**Comment by RouterChainsSuckk** [comment]
Uh foo's anti greif client allows you to ignore any kind of lighting filter (aka fulbright from minecraft to mindustry) also holy shit people on discord that react to suggestions are stupid 
Also heres the link @CitrusWire 
https://github.com/blahblahbloopster/mindustry-client-v6/releases/latest/download/desktop-release.jar

**Comment by hfs2** [comment]
@RouterChainsSuckk thanks for link. I first tried v6 but abandoned in disgust at night mode and [weather](https://github.com/Anuken/Mindustry-Suggestions/issues/1202) adding pointless (IMO) frustration. I'll try the link after deciding the best method not to torpedo my v5 game state.

Almost off topic but I wonder what's the best way to "vote' on an issue like this. Forbidden or severely frowned on to open a duplicate. But if I add a comment to a 3 week old suggestion, I doubt the developer will ever see it.

**Comment by XxsuperdeadlysniperxX** [comment]
@CitrusWire CLOSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEE THISSSSSSSSSSSSSSSSSS
