### ISSUE TITLE
More accessibility options

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1415]
It would be good if Mindustry had more accessibility options to allow more people to play; there are millions of gamers out there with one sort of impairment or another.

This site has tons of suggestions:
http://gameaccessibilityguidelines.com/full-list/

Mindustry already implements some of these (I.e. UI resizing; discretely adjustable volume), but there are no-doubt lots of other low hanging fruit too.

**Comment by itcannotbe** [comment]
Most of the things on the list is incompatible with how RTS games work in general. But some of the things are already in the game.

**Comment by DeltaNedas** [comment]
excuse me but how in the holy feline fuck is changing sound volume accessibility?

**Comment by CitrusWire** [comment]
> 
> 
> excuse me but how in the holy feline fuck is changing sound volume accessibility?

http://gameaccessibilityguidelines.com/provide-separate-volume-controls-or-mutes-for-effects-speech-and-background-music/
