### ISSUE TITLE
Small QoL change to logic co-ordinates variables

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry-Suggestions#1416]
**Describe what you would like changed, and why.**
Instead of default values of x=0, y=0 in various logic components (mainly unit control)
I propose those variables to be copied from player current position.

**Benefits**
Less time spent on copying desired location in various situations: gathering units, puting ore co-ordinates to mine, cargo take/drop destination ect.
Player as always can change x,y value manualy.

**Describe the changes you want to propose. Include possible alternatives.**
More advanced alternative: adding button near particular nodes to paste player position.

**Comment by Legomonster33** [comment]
no

**Comment by Kubek0212** [comment]
> no

Could you explain why do you think as such?

**Comment by Kubek0212** [comment]
Just learned about @this, @thisx and @thisy. It shares the simillar purpose, so I'm closing this thread.

**Comment by Legomonster33** [comment]
> > no
> 
> Could you explain why do you think as such?

I was just paraphrasing a quote from anuke about same thing.
