### ISSUE TITLE
Targetable Core

### ISSUE THREAD

**Issue by Minimoed** [Anuken/Mindustry-Suggestions#1417]
**Describe what you would like changed, and why.**
I would like to suggest a change to the core. The change to the core is that the core is a targetable block. 

**Describe the changes you want to propose. Include possible alternatives.**
If the core is a targetable block, the mass driver would be able to target the core and shoot items to the core. 
This change doesn't include any possible alternatives.

**Comment by itcannotbe** [comment]
Doesn't this merges a mass driver to the core?

**Comment by scarf-generic** [comment]
> Doesn't this merges a mass driver to the core?

Nah, just makes core able to recieve mass driver bullets. If mass driver was merged to core, core could shoot resources out of it.

**Comment by itcannotbe** [comment]
> > Doesn't this merges a mass driver to the core?
> 
> Nah, just makes core able to recieve mass driver bullets. If mass driver was merged to core, core could shoot resources out of it.

I'm asking if this falls under the list.

**Comment by itcannotbe** [comment]
> > Doesn't this merges a mass driver to the core?
> 
> Nah, just makes core able to recieve mass driver bullets. If mass driver was merged to core, core could shoot resources out of it.

I'm asking if this falls under the list.

**Comment by Minimoed** [comment]
I suggested this because there wouldn't be any room for a mass driver when all the sides are used by conveyors going in/out of the core.

Link to the picture that is referenced: `https://cdn.discordapp.com/attachments/783725097064202286/783732731188084776/unknown.png`

**Comment by BlueWolf3682** [comment]
why would a core, a structure designed to be aerodynamic enough to travel safely in a planets atmosphere, have something as large and aerodynamically rough as a mass driver built into it? this makes no sense, and if you did it with real physics it would cause the core to become unbalanced and spin out of control while launching/landing.

**Comment by joshuaptfan** [comment]
> I suggested this because there wouldn't be any room for a mass driver when all the sides are used by conveyors going in/out of the core.
Well, then you just gotta decide which you want more then.

**Comment by GreyMario** [comment]
Let's slippery slope this, then.

Mass Drivers need a receiver that can safely decelerate fired payloads; specifically, another Mass Driver.

If you ignore this requirement for the Core, you must then also ignore it for Vaults and Containers, because they are functionally near-identical to the Core.

This already _halves_ the cost of installing a Mass Driver pair because you can now disregard logic and use a Container destination with an Unloader.

Okay, so now containers accept Mass Driver payloads. Why not production buildings directly? Their inventory is no different than a Container, just a lot smaller.

Now you're shooting Mass Driver payloads directly onto conveyor belts.

Do you understand how ridiculous it is to catch Mass Driver payloads _without using another Mass Driver?_

**Comment by Bohaska** [comment]
> Let's slippery slope this, then.
> 
> Mass Drivers need a receiver that can safely decelerate fired payloads; specifically, another Mass Driver.
> 
> If you ignore this requirement for the Core, you must then also ignore it for Vaults and Containers, because they are functionally near-identical to the Core.
> 
> This already _halves_ the cost of installing a Mass Driver pair because you can now disregard logic and use a Container destination with an Unloader.
> 
> Okay, so now containers accept Mass Driver payloads. Why not production buildings directly? Their inventory is no different than a Container, just a lot smaller.
> 
> Now you're shooting Mass Driver payloads directly onto conveyor belts.
> 
> Do you understand how ridiculous it is to catch Mass Driver payloads _without using another Mass Driver?_

Slippery sloping stuff is ethically wrong.

**Comment by Humanoid-X** [comment]
Do not suggest list : No merged behavior blocks
