### ISSUE TITLE
Quality of Life for Upgrade screen. 

### ISSUE THREAD

**Issue by MoonFlux97** [Anuken/Mindustry-Suggestions#1419]
**Describe the content or mechanics you are proposing.**
_When you Highlight something you want to upgrade, it also will highlight the "prerequisites" that you must unlock first._

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would help show much more quickly where things are, or maybe how far up the tree they will be until you can upgrade it. Good example of this would be all the prerequisites for unlocking a new map. Hovering over or pressing a button would quickly show what needs to be gotten/what is left. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
and/or a list next to/under the info box

**Comment by itcannotbe** [comment]
Just make it clickable but change the research button to something unpressable and maybe with the text "Prerequisites needs to be researched first"
