### ISSUE TITLE
Metaglass Walls

### ISSUE THREAD

**Issue by Onii-Mindustry** [Anuken/Mindustry-Suggestions#142]
Walls made out of Metaglass. Enemies would be able to see through these walls and if a player built structure that is not a wall is on the other side they will path find to try to go through the wall. However these walls would be fairly weak, around 2000HP but with a possible modifier that if phase walls are touching it, it becomes "bullet proof" where some projectiles are deflected less, but not more than the minimum of phase walls

This could open a whole new design for defense than multiple layers of walls in the front. The risk of having a walkway to an open hole in defense to direct enemies would be eliminated.

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
so... Like an open door, but actually closed, that enemies automatically path to, but have to destroy in order to pass.

**Comment by DeltaNedas** [comment]
what does this provide over existing walls/doors
this is more ridiculous than using copper for walls, glass will shatter when shot while copper will deform
