### ISSUE TITLE
WASD navigation for tech tree

### ISSUE THREAD

**Issue by varlokkur** [Anuken/Mindustry-Suggestions#1420]
**Describe the content or mechanics you are proposing.**

Mouse dragging appears to be the only means of moving around on the tech tree.  Keyboard navigation using WASD to scroll vertically and horizontally would make the tech tree faster and easier to use.  This could be in addition to the existing mouse-based movement. Since the game already relies on WASD navigation for the control ship, implementing a similar method of moving around in the tech tree would feel more native. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This is a quality of life / UI improvement. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
good

**Comment by varlokkur** [comment]
I haven't played in a while -- was this implemented?
