### ISSUE TITLE
Unpowered buildings indicator

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1421]
It would be super helpful to have an indicator somewhere on the screen telling you there are unpowered buildings somewhere on the map; this would let you see if a hole in your powergrid has appeared due to (usually air) attack.
Actually there are several possibilities:

* Indicate there are unpowered buildings
* A number telling you how many there are
* The ability to click it to be taken to a building. Repeated clicking takes you to the next unpowered building.

**Comment by D-player1** [comment]
Settings
Graphics
Display block status

**Comment by CitrusWire** [comment]
Thanks but doesn't quite cover what I mean.

My suggestion is for an indicator on the side of the screen somewhere that tells you where unpowered things are anywhere on the map. That way you can readily discover when there's a hole in your power structure due to an attack.

**Comment by itcannotbe** [comment]
Ah yes. a red icon on the lower part of the blocks won't tell you that something is wrong with your blocks......

**Comment by CitrusWire** [comment]
> 
> 
> Ah yes. a red light on the lower part of the blocks won't tell you that something is wrong with your blocks......

Much as I appreciate sarcasm, you're not really adding anything to the conversation are you?

Yes the red light tells me there's something wrong with the blocks that are ON MY SCREEN. But if I'm the other side of the map where are the red lights then? That's the issue this suggestion is meant to ameliorate.

**Comment by Humanoid-X** [comment]
The red lights are already good enough. 
If you are on the other side of the map, you simply can't know it. And are not allowed to know it.
If you are in USA, you will not know what happened in China, is it?
If you really want this, you can always use logic.

**Comment by Bohaska** [comment]
> If you are in USA, you will not know what happened in China, is it?

Your argument is flawed. I live in China and can tell you what happened in there.

**Comment by itcannotbe** [comment]
That counter argument is flawed as it's more reliable if you actually seen it which is the actual intent of the statement.

**Comment by CitrusWire** [comment]
> 
> 
> The red lights are already good enough.
> If you are on the other side of the map, you simply can't know it. And are not allowed to know it.
> If you are in USA, you will not know what happened in China, is it?
> If you really want this, you can always use logic.

Huh? Of course you can know if something on the other side of the planet is turned off.
Here I can see which bits of CERN are turned on/off - http://meltronx.com/ - no need to be in Switzerland. Here's a global status panel for AWS - https://status.aws.amazon.com/

**Comment by itcannotbe** [comment]
> > The red lights are already good enough.
> > If you are on the other side of the map, you simply can't know it. And are not allowed to know it.
> > If you are in USA, you will not know what happened in China, is it?
> > If you really want this, you can always use logic.
> 
> Huh? Of course you can know if something on the other side of the planet is turned off.
> Here I can see which bits of CERN are turned on/off - http://meltronx.com/ - no need to be in Switzerland. Here's a global status panel for AWS - https://status.aws.amazon.com/

That's called remote monitoring which entails automation. And you have the tool with mindustry logic to actually make that happen.

Also if the dev made a minimap filter for this, a lot of request regarding minimap filters will ensues.

**Comment by Humanoid-X** [comment]
That's called remote monitoring. Why don't you use logic? Put logic Displays anywhere like how you put all those screens for the remote monitor.

**Comment by Humanoid-X** [comment]
Oh yeah, itcannotbe had already said everything I want to say. Thanks.
