### ISSUE TITLE
Add a Wait command for logic

### ISSUE THREAD

**Issue by dojoman500** [Anuken/Mindustry-Suggestions#1424]
The Wait command would allow players to set a logic block to hold its command process for a player selected amount of time in seconds, supporting decimals as well, Control variables such as Enabled would be held in their current state while this command is running, unless controlled by other logic blocks.

This could help players make systems such as countdown timers on messages/displays, easier timeouts, ETC. (EG. you could make a system that waits a certain amount of time while holding a conveyor to gather for example, pyratite for a quick burst of extra power)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. [X]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

is the x that you put is to make us doubt that you really did it?

**Comment by itcannotbe** [comment]
#1189 says 🔪

**Comment by dojoman500** [comment]
I did search it. I did not see a wait command suggestion Sent from Mail for Windows 10 From: itcannotbeSent: Thursday, December 3, 2020 10:03 AMTo: Anuken/Mindustry-SuggestionsCc: dojoman500; AuthorSubject: Re: [Anuken/Mindustry-Suggestions] Add a Wait command for logic (#1424) [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.is the x that you put is to make us doubt that you really did it?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by scarf-generic** [comment]
this suggestion is redundant, `@time` exists.

**Comment by itcannotbe** [comment]
1. You fucked up replying to the issue through email. Please do not include the orginal message the next time.

2. You did not searched similar keep words such as: delay, or time,

**Comment by itcannotbe** [comment]
> this suggestion is redundant, `@time` exists.

Actually the issue this duplicates points that out.

**Comment by dojoman500** [comment]
If your going to cuss then don’t email me Sent from Mail for Windows 10

**Comment by itcannotbe** [comment]
> Sent from Mail for Windows 10 
Nice.

**Comment by itcannotbe** [comment]
I didn't email you, github did.

Also this is how your reply looks like mr. "Sent from Mail for Windows 10"

![Screenshot_20201204_020006](https://user-images.githubusercontent.com/45280919/101069091-84a9ee00-35d4-11eb-9e4c-fb446307dce1.jpg)

**Comment by DeltaNedas** [comment]
lol
