### ISSUE TITLE
Modding: Allow to add new Planets

### ISSUE THREAD

**Issue by pyDebugger** [Anuken/Mindustry-Suggestions#1425]
**Describe the content or mechanics you are proposing.**
I think it would be cool for modders if they can add new planets to the game's campaign and add their maps to those.
If you made 20 maps and then add them to a own planet, for example. It would be in the following folder structure:

```
mod
|-- maps
     |-- planet1
          |-- planet1.json
          |-- some.msav
          |-- new.msav
          |-- map.msav
    |-- planet2
          |-- planet2.json
          |-- map1.msav
          |-- map2.msav
```

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think it could enhance campaign mods by a lot and the maps folder would be easier to read.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This looks like #1384

**Comment by DeltaNedas** [comment]
you can already do this

**Comment by sample-text-here** [comment]
use scripting and `extend` `Planet`

**Comment by Kyllingene** [comment]
> This looks like #1384

That is asking for planet-making in the editor, this is asking for easier map-making using mods (so as to include them).

> use scripting and extend Planet

Mindustry Pre-Json-Modding: *has no easy way to mod without writing scripts*
Player: "Can i have an easier way to do this?"
Anuken: "Sure here you go"

Modern Mindustry: *has no easy way to add planets without writing scripts*
Player: "Can i have an easier way to do this?"
Community: **"learn to script"**
