### ISSUE TITLE
Drag&Drop for maps, schemes and mods

### ISSUE THREAD

**Issue by Vladislav117** [Anuken/Mindustry-Suggestions#1426]
**Describe the content or mechanics you are proposing.**
It was nice to see drag & drop in the game, if possible. This will work with saves, schemes, mods and maps. (When dragging and dropping a .msav file, you will be asked whether it is map or save). That is, the user needs to select the files and just drag them into the game window.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will significantly speed up the installation time for maps, schemes, etc. Sometimes it takes a very long time to import many files separately, and it is also quite inconvenient to search for the AppData / Roaming / Mindusrty folder all the time.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
A batch import is more doable than a full pledge drag and drop.

Also technically there is no map files, they're just save files with waves set at the beginning (0).

**Comment by DeltaNedas** [comment]
1. pretty sure you can already drag in schems
2. man mv
3. if you dont want to go to some folder every time use a symlink in a convenient area

**Comment by sample-text-here** [comment]
also would be nice with #914
