### ISSUE TITLE
Unit scrap

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry-Suggestions#1428]
**Describe the content or mechanics you are proposing.**
A new type of decoration blocks (like boulders or spore clusters) that are deteriorated units, with missing/broken parts etc
Longer deconstructing time depending on the tier
They appear over Serpulo, like, some random flare scrap in g0, an aground minke in ruinous shores, a dead lich in desolate rift

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
They will increase the aesthetic in the maps, *just imagine finding a dead Toxopid somewhere*

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
Good idea. But who has the sprites?

**Comment by hadron13** [comment]
maybe it could be generated with image processing when sprites are needed, removing colors and parts, making holes, etc, this also could be used to generate an unique texture for every sector.

**Comment by the-kido** [comment]
just add that good old sapia and erase and rust the units maybe chip them about using a lasso and boom:
![Capture](https://user-images.githubusercontent.com/63456333/101167744-652cb880-3608-11eb-9600-34be519436fb.PNG)

**Comment by WilloIzCitron** [comment]
hmm its used for unit workshop for rebuilding or you can research a unit
