### ISSUE TITLE
Option to export and import processor commands

### ISSUE THREAD

**Issue by ToorpedoXPshARK** [Anuken/Mindustry-Suggestions#1429]
**Describe the content or mechanics you are proposing.**
a new option to export and import processor commands such as schematics.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think it would be better to keep all the commands in an organized folder, than to have them saved in the schematics. It would be less troublesome and more practical.
                                                                       **Translated by: Google Translator**

**Comment by sample-text-here** [comment]
edit -> copy to clipboard

edit -> import from clipboard

save it to a text file, with a custom extension if you want

**Comment by Humanoid-X** [comment]
- [X] I am incapable of reading, comprehending, and filing out the template, but capable of deleting it entirely.

Also what you said already EXIST in game.

**Comment by Bohaska** [comment]
> * [x]  I am incapable of reading, comprehending, and filing out the template, but capable of deleting it entirely.

hey look he filled the template humanoid, just that this template is different and he picked different template.

**Comment by itcannotbe** [comment]
No. He cut out the part to make sure the suggestion isn't a duplicate, already planned, already in the game, or listed under the do not suggesy list.

**Comment by itcannotbe** [comment]
No. He cut out the part to make sure te suggestion isn't a duplicate, already planned, already in the game, or listed under the do not suggesy list.

**Comment by Kyllingene** [comment]
This is already in the game. Please actually look at the logic system/look up how to do this before making an issue.
