### ISSUE TITLE
Buff surge towers

### ISSUE THREAD

**Issue by Bananycus** [Anuken/Mindustry-Suggestions#143]
Right now, surge towers are completely pointless if you are not playing on a map specifically designed for it to be useful. 

Make surge towers have 50 connections and consume power for each connection, so there is still a choice between normal power nodes and surge towers. They also could be powered with a very small amounts of surge alloy instead.

**Comment by potatoisagender** [comment]
uhhhhh...
Surge towers are not completely pointless. In case you haven't noticed, they have a working radius of hundreds of blocks. That isn't pointless. If you need to get power past a giant wall, you use surge towers, or you route 50 regular nodes around the obstruction (if you can). Their use is certainly niche, but buffing them and changing them to your specifications completely changes their core task.

**Comment by Bananycus** [comment]
> uhhhhh...
> Surge towers are not completely pointless. In case you haven't noticed, they have a working radius of hundreds of blocks. That isn't pointless. If you need to get power past a giant wall, you use surge towers, or you route 50 regular nodes around the obstruction (if you can). Their use is certainly niche, but buffing them and changing them to your specifications completely changes their core task.

There are no maps in mindustry that take advantage of surge towers. When you get them you most likely already have power almost everywhere

**Comment by potatoisagender** [comment]
are you talking about campaign or custom maps? And even then, you could easily use surge towers to replace the areas with power nodes, to save space. For example, in nuclear production, people like to mass driver stuff to the core (especially when they land in the middle left position). In that position, it is hard to get power to the mass drivers, unless you use a surge node to jump the giant wall that lies between. Maybe there aren't any maps that specifically need surge towers, but they are like an optional item that helps you if you want to use them.

**Comment by itcannotbe** [comment]
I think the better option is to just make maps that make you use them for what they are already in the game.

**Comment by Syncinus** [comment]
Surge Tower's do need a significantly longer radius though. Their current radius makes them useless for a lot of massive ravines, so giving them the same radius as a Mass Driver would make them way more useful.
