### ISSUE TITLE
Ability to pick from the predefined core launch locations

### ISSUE THREAD

**Issue by Fipico2** [Anuken/Mindustry-Suggestions#1432]
**Describe the content or mechanics you are proposing.**

Currently, when first entering one of the main sectors, there are a few predefined locations that your core may get launched to. This is currently left to chance, my suggestion is to either allow the player to pick one of the predefined locations, or to at least re-roll the core location every time it gets destroyed.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

There are multiple predefined core locations, and some are definitely better than others. As opposed to v5, you cant abandon a sector anymore in v6, and thus will be stuck with whatever location you got. Implementong my suggestion would allow for the player to pick whatever position they think is better without breing stuck with it forever, enjoying the map much more.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fipico2** [comment]
This suggestion is similar to another one made not too long ago, but i think mine is substancially diferent since it asks for a mechanic that is currently left to luck to be cpntrolled by the player

**Comment by sample-text-here** [comment]
> -[x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

you know you're supposed to do the things you check, right?

#1423 is the same suggestion

**Comment by Fipico2** [comment]
> > -[x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> you know you're supposed to do the things you check, right?
> 
> #1423 is the same suggestion

I stated in my comment that i knew about this suggestion. That suggestion never mentions the predefined locations, its asking for the player to chose exactly where the Core would be, which would be way too overpowered.
I also suggested changing the Core location upon dying in a sector, and that was in no way mentioned in #1423
