### ISSUE TITLE
Mass relays and Launch pads to transport units and transfer them between sectors. 

### ISSUE THREAD

**Issue by ScolarIronFist** [Anuken/Mindustry-Suggestions#1433]
**Describe the content or mechanics you are proposing.**
Allowing the use of mass relays to transport them in battles and launch pads to transport units and transfer them between sectors.  

![image](https://user-images.githubusercontent.com/44145043/101105391-b0a08180-358a-11eb-9371-5a2e079886c4.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Connecting the unit conveyors to the mass relays to transport the units from the factories to the combat zones. Using the unit conveyors with launch pads to defend/attack 

sectors at the campaign. it would become a way to allow the efficient massive mobilization of armies in the game. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. 
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
You are supposed to use air units to transport units, not mass drivers!

**Comment by RojoDev** [comment]
> You are supposed to use air units to transport units, not mass drivers!

can you actually use air units to transport massive ground armies?

**Comment by sample-text-here** [comment]
> can you actually use air units to transport massive ground armies? 

yes. use the logic system to control payload units.
> Can you use the air units to transfer your units between sectors?

no, you can't. if you really wanted to get t5s quickly, you could launch with a core to t5

**Comment by RojoDev** [comment]
> > can you actually use air units to transport massive ground armies?
> 
> yes. use the logic system to control payload units.
> 
> > Can you use the air units to transfer your units between sectors?
> 
> no, you can't. if you really wanted to get t5s quickly, you could launch with a core to t5

Yeah but that is why this suggestion was made. so i dont have to do that and plus its better at the long term.

**Comment by Bohaska** [comment]
> > > can you actually use air units to transport massive ground armies?
> > 
> > 
> > yes. use the logic system to control payload units.
> > > Can you use the air units to transfer your units between sectors?
> > 
> > 
> > no, you can't. if you really wanted to get t5s quickly, you could launch with a core to t5
> 
> Yeah but that is why this suggestion was made. so i dont have to do that and plus its better at the long term.

You are not supposed to have that! It was an intentional decision.

**Comment by RojoDev** [comment]
> > > > can you actually use air units to transport massive ground armies?
> > > 
> > > 
> > > yes. use the logic system to control payload units.
> > > > Can you use the air units to transfer your units between sectors?
> > > 
> > > 
> > > no, you can't. if you really wanted to get t5s quickly, you could launch with a core to t5
> > 
> > 
> > Yeah but that is why this suggestion was made. so i dont have to do that and plus its better at the long term.
> 
> You are not supposed to have that! It was an intentional decision.

And you are not a dev you are just an user just like i am. is not your decision to add this into the game. its Anukes decision. you literally have nothing to do here besides being annoying.

**Comment by Bohaska** [comment]
https://trello.com/c/eYmSkIDI/813-payload-cannon I have nothing to say... Congratulations, @RojoDev , Anuke will implement your suggestion!

**Comment by Bohaska** [comment]
> > > > > can you actually use air units to transport massive ground armies?
> > > > 
> > > > 
> > > > yes. use the logic system to control payload units.
> > > > > Can you use the air units to transfer your units between sectors?
> > > > 
> > > > 
> > > > no, you can't. if you really wanted to get t5s quickly, you could launch with a core to t5
> > > 
> > > 
> > > Yeah but that is why this suggestion was made. so i dont have to do that and plus its better at the long term.
> > 
> > 
> > You are not supposed to have that! It was an intentional decision.
> 
> And you are not a dev you are just an user just like i am. is not your decision to add this into the game. its Anukes decision. you literally have nothing to do here besides being annoying.

You mean 2 users

**Comment by godotgamedeveloper** [comment]
For the remaining part of your suggestion, see the Trello card on Sector Transfer:
https://trello.com/c/TogJg9CP/612-sector-transfer

It solves your need to move units between sectors, albeit not in the same way you suggested.  Your suggestion is a unit launchpad, while the Trello card says that flying units can carry units over to an adjacent sector.
