### ISSUE TITLE
Indication as to what part of a logic system is being read.

### ISSUE THREAD

**Issue by Munchykin5** [Anuken/Mindustry-Suggestions#1434]
**Describe what you would like changed, and why.**
I am currently in the middle of an uphill battle with the new logic systems, and something I've noticed is some way to watch the system go through my code would help massively. It can get stuck, or something doesn't work correctly and I have no way of knowing because I can't see where it's at.

**Describe the changes you want to propose. Include possible alternatives.**
In the logic menu if there was say a small white arrow on the left side next to whatever "block" of code it's on, or the block was to be highlighted/glow while being read then I can watch as it goes to root out problems, and fix incorrect code.
![Mindustry_arrow](https://user-images.githubusercontent.com/75456982/101105757-03326b80-3594-11eb-837e-b6bb6a9d5cfb.PNG)

Something like this which goes down with the flow of code.

Potential other idea semi related if this is brought into consideration would be a slider to slow down the code between say 0.1x - 1x speed while working on it to ensure everything works properly.

**Comment by sample-text-here** [comment]
> a slider to slow down the code between say 0.1x - 1x speed while working on it

if you used this suggestion, you would *need* this or it would be useless because the code runs so fast. 

also it would be nice to have a "step code" button that runs code one line at a time every time you click it and a "pause code" button, too

**Comment by DeltaNedas** [comment]
yes

**Comment by Catchears** [comment]
> step code

ohyes
