### ISSUE TITLE
Add teams for wave enemy units.

### ISSUE THREAD

**Issue by aFuschia** [Anuken/Mindustry-Suggestions#1436]
**Describe the content or mechanics you are proposing.**
Adding a team option for wave enemies in the map editor would be a nice edition to the editor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will add more variety for the maps and give the mappers more options for enemies.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Isn't this #325?

**Comment by Bohaska** [comment]
> Isn't this #325?

That suggestion is very broad.

**Comment by itcannotbe** [comment]
And this isn't?

**Comment by sample-text-here** [comment]
i don't see anything about changing unit teams in 325, so i would say this is a different suggestion.

the only thing it mentions is having different spawn points for each unit (type)

**Comment by itcannotbe** [comment]
What even is a unit team?

**Comment by sample-text-here** [comment]
I think they mean that some units can come from crux, some units can come from green, etc...

**Comment by itcannotbe** [comment]
But won't they just kinda kill each other in the process?

**Comment by sample-text-here** [comment]
hmm good point

actually i just came up with a new idea as i wrote that: allies

like sharded and blue are allies, so they can't hurt or destroy each other

and they team up against red and green

could be interesting

**Comment by Bohaska** [comment]
> But won't they just kinda kill each other in the process?

Not if their spawns are placed in separate areas.

**Comment by Bohaska** [comment]
> hmm good point
> 
> actually i just came up with a new idea as i wrote that: allies
> 
> like sharded and blue are allies, so they can't hurt or destroy each other
> 
> and they team up against red and green
> 
> could be interesting

Get that into a new suggestion here before someone else does
