### ISSUE TITLE
Set individual destination for the launch pads in one sector

### ISSUE THREAD

**Issue by kyoul1** [Anuken/Mindustry-Suggestions#1437]
**Describe the content or mechanics you are proposing.**

If I build multiple resource launch pads, it seems like the area will only be delivered to one different region (if I change the destination of one resource launch pad, the destination of others will be changed automatically)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

If this can be modified so that different destinations can be set up on different resource launch pads, it will help to build more systematic, complex and planned resource production networks. This is one of the attractions of this game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DockedSiamang22** [comment]
I'm fairly certain that the opposite of this was also a community suggestion- making all launch pads in one sector go to the same destination

**Comment by Bohaska** [comment]
> I'm fairly certain that the opposite of this was also a community suggestion- making all launch pads in one sector go to the same destination

Maybe we should make an option called 'Set all to' which changes all launch pads in sector to launch to one place. If not selected, the only launch pad that changes destinations would be the selected one

**Comment by sample-text-here** [comment]
> -[x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

please actually do the thing the checkbox mentions next time

duplicate of #1011

**Comment by kyoul1** [comment]
Oh, I couldn't find it when I first searched...
Anyway, what I want is to give at least an option to set an individual destination in the lunch pad setting.
