### ISSUE TITLE
Bot that closes suggestions without ticked checkboxes

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1438]
**Describe the content or mechanics you are proposing.**
Bot that closes suggestions without ticked checkboxes

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
So that people actually tick the checkboxes.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Make the bot first to close this issue. No cheating by closing this manually*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
HAHA LOLOLOL good work
 - [X] This a good suggestion
 - [X] Good work not checking the checkbox to test it

**Comment by BlueWolf3682** [comment]
sounds like someone saw my not on my last suggestion

**Comment by matkoniecz** [comment]
Bot also could close issues with many downvotes. Maybe issues where number of downvotes larger than number of upvotes, with difference greater than 2.

https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions--1-desc

**Comment by itcannotbe** [comment]
Actually as evidence by a long long history. It doesn't matter if something gets downvoted to death, as long as it's a good fit for the game.

**Comment by Kyllingene** [comment]
> Bot also could close issues with many downvotes. Maybe issues where number of downvotes larger than number of upvotes, with difference greater than 2.

Umm, no. "Hey, here is a good suggestion that gets downvoted by a few noobs who dislike things being balanced. It has 1 upvote and 3 downvotes, so goodbye!" Seriously, at least more than 5, probably 10 if implemented.
