### ISSUE TITLE
Option for Old Sounds

### ISSUE THREAD

**Issue by TheFuryBumblebee** [Anuken/Mindustry-Suggestions#1440]
**Describe the content or mechanics you are proposing.**
While the new sounds, such as the player shooting sound, are pretty cool, the old sounds were nice as well. So, I propose an option in the `Sound` settings category to switch between the old and new sounds whenever you'd like.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This option would allow players who prefer the old sounds to use the old sounds, while still allowing the players who prefer the new sounds to use the new sounds.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Cuber02** [comment]
Can we change Impact Generator to Fusion Reactor?

**Comment by Bohaska** [comment]
Anuke said this a long time ago
<img width="488" alt="Screen Shot 2020-12-04 at 7 05 41 PM" src="https://user-images.githubusercontent.com/73286691/101156649-dcdc0100-3663-11eb-991a-0e0345b69105.png">

**Comment by the-kido** [comment]
i think he means v5 and v6 sounds in which case you can A. change the sounds yourself it isnt that hard (literally i can do it) and B. the new sounds are much more pleasing to your ears and your opinion does not matter.
