### ISSUE TITLE
Change "Impact Generator" to "Fusion Reactor"

### ISSUE THREAD

**Issue by Cuber02** [Anuken/Mindustry-Suggestions#1441]
Since you need energy to start up a nuclear fusion reactor, it would make sense. Also it sound a lot cooler.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Sure no problem!

**Comment by potatoisagender** [comment]
IT'S NOT MEANT TO REPRESENT A FUSION REACTOR. IT DOESN'T WORK LIKE A FUSION REACTOR. THUS, IT ISN'T A FUSION REACTOR.

**Comment by DeltaNedas** [comment]
why do you think anuke didnt call a fusion reactor "fusion reactor"? wait a minute...

**Comment by itcannotbe** [comment]
Anuke already said why in an older issue.

**Comment by sample-text-here** [comment]
![image](https://user-images.githubusercontent.com/56274831/101191300-5c3ee580-360e-11eb-9c1c-0ab921358027.png)
Anuke says [no](https://github.com/Anuken/Mindustry-Suggestions/issues/163#issuecomment-627702204)

**Comment by RedstonerKBC** [comment]
Fusion works by smashing atoms together, not by blowing explosive blast compounds.

**Comment by Kyllingene** [comment]
The only reason I have any opinion here is because of that quote from Anuke (btw, why light mode? Join the dark side). If Anuke said no, please close this.
