### ISSUE TITLE
Commandable / controllable turrets 

### ISSUE THREAD

**Issue by RETSINAC** [Anuken/Mindustry-Suggestions#1445]
**Describe the content or mechanics you are proposing.**
Similar to units, players should be given the ability to posses a turret and command other nearby turrets to fire simultaneously in the same direction.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This allows players to better defend an area by having more control of one's turrets, instead of only being able to control one.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Legomonster33** [comment]
players can posses turrets, commanding other nearby turrets would be p epic tho

**Comment by the-kido** [comment]
using logic you can do that pretty easily already.

**Comment by RETSINAC** [comment]
> using logic you can do that pretty easily already.

Maybe I am stupid...

**Comment by RETSINAC** [comment]
> using logic you can do that pretty easily already.

Still it would be better without logic. Just imagine 500 duos.

**Comment by Humanoid-X** [comment]
You can use logic... And WHY ARE YOU USING 500 DUOS?! O_o Use Salvo or Spectre...

**Comment by RETSINAC** [comment]
> You can use logic... And WHY ARE YOU USING 500 DUOS?! O_o Use Salvo or Spectre...

It's a joke... but just imagine being able to control 500 duos all at the same time just like you can with units.

**Comment by XxsuperdeadlysniperxX** [comment]
The game already has the possession feature

**Comment by Kyllingene** [comment]
This is not a hard thing to do with logic (although it requires a little manual setup).

**Comment by XxsuperdeadlysniperxX** [comment]
And a knowledge of the coding language

**Comment by Kyllingene** [comment]
Which you can learn by looking at the blocks + reading the manual
