### ISSUE TITLE
Overdrive Tower

### ISSUE THREAD

**Issue by Void-Syrex** [Anuken/Mindustry-Suggestions#1446]
** Describe the content or mechanics you can offer.**

Overdrive tower
This is a block of 5x5 cells with a viewing radius equal to the power tower. This block should have a 400% amplifying effect (1.6 times more than the Dome)
Construction cost: 3680 lead, 3040 titanium, 2040 silicon, 1300 plastania, 1245 kinetics, 2300 thorium, 530 Metaglass.
Research cost: 1
Consumes 2400 energy per second
Usage (in 8 seconds) :[
Kinetic alloy: 2
Silicon: 2
Phase fabric: 2
Thorium: 3
{Water: 12.8 units (per second!!!)}
:
Cryogenic liquid: 18 units per 1 second increases radius to 55 blocks
Description in blocks:
a large building that uses technology similar to a pulse generator, but completely different from it. It takes a lot of resources to work. It pays off well later.

** Describe how you think this content will improve the game. If you offer new content, mention how it can add more gameplay features or how it will fill a new niche.**

This projector helps (finally) close the problems of mass destruction of resources to support 10-20 domes. Also, this thing will solve all issues at the expense of resource production, for example, putting it in the place of mass production, you can forget about the constant problems with the lack of a particular resource.
But, if the player hopes to smear this thing as a permanent replacement for all problems and give himself an advantage, then he will simply be destroyed by the space price for 1 tower

** Before asking this question, put an " X " in the fields below to confirm that you have recognized them.*

1. [X] I quickly looked through the list of offers to make sure it hadn't been offered yet.
2. [X] I checked [Trello] (https://trello.com/b/aE2tcUwF/industry-trello) to make sure that my offer is not planned or implemented in the development version.
3. [X] I am familiar with all the content already in the game, or I looked at the Wiki to make sure that my offer doesn't already exist in the game.
4. [X] I read `README.md -so that my idea doesn't fall into the category of" a few things you shouldn't suggest.

**Comment by D-player1** [comment]
Even overdrive dome is not enough for you huh, also this will completely break the game because you can't speed up the game too fast or everything will go down to shit

**Comment by Void-Syrex** [comment]
> Even overdrive dome is not enough for you huh, also this will completely break the game because you can't speed up the game too fast or everything will go down to shit

Question: what are the limits in the game itself ( in terms of speed)?

**Comment by Bohaska** [comment]
kinetics aren't materials and wth is kinetic alloy?

**Comment by Legomonster33** [comment]
> > Even overdrive dome is not enough for you huh, also this will completely break the game because you can't speed up the game too fast or everything will go down to shit
> 
> Question: what are the limits in the game itself ( in terms of speed)?

60

**Comment by Humanoid-X** [comment]
He is using Google Translate. Just look at "Kinetic Alloy", "Plastania" and "/industry-trello"

**Comment by Void-Syrex** [comment]
> He is using Google Translate. Just look at "Kinetic Alloy", "Plastania" and "/industry-trello"

You're right, I'm actually Russian.

**Comment by Void-Syrex** [comment]
> > > Even overdrive dome is not enough for you huh, also this will completely break the game because you can't speed up the game too fast or everything will go down to shit
> > 
> > 
> > Question: what are the limits in the game itself ( in terms of speed)?
> 
> 60

Thanks you.
