### ISSUE TITLE
Attack map start out generation as part of core buiding

### ISSUE THREAD

**Issue by Superchubs05** [Anuken/Mindustry-Suggestions#1447]
**Describe the content or mechanics you are proposing.**
Much like how you now can modify the core when launching into a map, I feel that it would be a worthy improvement to have the ability to create the startout resources (i.e ground factory and basic silicon production) and have the cost come out of your global inventory. Because it comes from your global inventory, this will prevent people from just harvesting the resources at the start.

Perhaps this could be included within the core generation menu and included in the launch requirements.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think that it will improve the game by stopping the "try once, be handicapped for all other tries" mentality, which it seems quite a few people run into.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Ever heard of core schematic?
