### ISSUE TITLE
Impact 0078

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1448]
The map is not possible to beat because quesar units come at wave 15 and you can't kill these shielded units with dous and basic equipment 

Increase the waves for that unit and allow the more basic units to attack before you hit us with late game units immediately

**Comment by D-player1** [comment]
I can't afford plast walls yes

**Comment by DeltaNedas** [comment]
just dont use duos noob

**Comment by sample-text-here** [comment]
> you can't kill these shielded units with dous and basic equipment

but by the time you reach impact 0078 you shouldn't have to use duos anymore

also use plast walls from launchpads

**Comment by BlueWolf3682** [comment]
WHY ARE YOU ATTEMPTING AN ENDGAME MAP WITH DUOS AND BASIC EQUIPMENT

**Comment by lINSTINCTl** [comment]
Why still using duos WHY

**Comment by Humanoid-X** [comment]
WHY ARE YOU ISING DUOS AND BASIC EQUIPMENTS IN AN ENDGAME MAP

**Comment by Untouchable11** [comment]
Simple solution: _Stop using basic equipment_

**Comment by XEN0PHIL** [comment]
If you want to use duos no matter what then feed them with graphite ammo.

**Comment by XxsuperdeadlysniperxX** [comment]
I use dous to get better guns delta and also don't call me a noob for not being able to make salvos in time boi

**Comment by XxsuperdeadlysniperxX** [comment]
Plus the if you have 2 or quasars comeing at you on wave 15 and you only just got to get thorium and stuff wouldn't you panic if suddenly your defense dies before an upgrade is even close to happening

**Comment by XxsuperdeadlysniperxX** [comment]
> just dont use duos noob

You don't know the pain of just gettimg better resources then every chance to of winning goes to 0 fast

**Comment by XxsuperdeadlysniperxX** [comment]
> just dont use duos noob

You don't know the pain of just gettimg better resources then every chance to of winning goes to 0 fast and i can bet you haven't touched impact 0078

**Comment by XxsuperdeadlysniperxX** [comment]
> WHY ARE YOU ATTEMPTING AN ENDGAME MAP WITH DUOS AND BASIC EQUIPMENT

Im not in endgame dude i legitimately don't have launchpads idk why i don't i have everything else but launchpads

**Comment by XxsuperdeadlysniperxX** [comment]
> WHY ARE YOU ISING DUOS AND BASIC EQUIPMENTS IN AN ENDGAME MAP

Bruh

**Comment by XxsuperdeadlysniperxX** [comment]
The only thing you can really get going is duos due to no launchpads plus the waves are really fast

**Comment by hadron13** [comment]
derp unlock launch pads before going to impact 78, I literally go with *3 foreshadows, 1 meltdown, phase walls, tons of surge cyclones and it was very ez*

**Comment by XxsuperdeadlysniperxX** [comment]
Stop yelling people

**Comment by Sky4ce09** [comment]
this madlad still using duos in impact 0078

**Comment by XxsuperdeadlysniperxX** [comment]
Issue closed
