### ISSUE TITLE
Traduction uncompleted

### ISSUE THREAD

**Issue by Stratoger** [Anuken/Mindustry-Suggestions#145]
I come from Belgium so my game is in french but not all of the text in-game are translated. It is not a problem for me, because my English is good (at least I think so). But it could be a problem for someone else and it will improve the quality of the game, which is already great.
There it is, just a suggestion.
Sincerly yours

**Comment by Quezler** [comment]
then submit your own translations to the french language file: https://github.com/Anuken/Mindustry/blob/master/core/assets/bundles/bundle_fr_BE.properties

**Comment by Anuken** [comment]
Translations are done by the community, so if you see something missing, you'll have to finish it yourself or find someone to do it.
