### ISSUE TITLE
Payload overflow gates, sorters and more

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry-Suggestions#1450]
**Describe the content or mechanics you are proposing.**
All gates for conveyors but then for payload conveyors

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
- Nice to have when putting different units in the same conveyor.
- Actually need a payload overflow gate before a reconstructer because the higher tier reconstructers are slower.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
This might clutter up the transportation section even further though...

**Comment by Bohaska** [comment]
Feels more like a mod thing...

**Comment by Kyllingene** [comment]
If this was implemented, it may merit a new section (ESPECIALLY if payload conveyors ever transport item payloads).

**Comment by antonilol** [comment]
With a mega you can drop containers on payload conveyors
