### ISSUE TITLE
UI in recent update

### ISSUE THREAD

**Issue by shaunrc493** [Anuken/Mindustry-Suggestions#1451]
Hey. Loving the game so far, but the most recent update has made certain tasks difficult on an iPhone XR.

As the UI components are anchored to the top left, bottom right, and some addition buttons on the centre bottom, the iPhone XR either hides these components behind the silly black bar where the speaker/camera is, and the replacement home button kicks in before the game’s UI does. All in all, it’s still playable, but they are small cross compatibility bugs that are disruptive to game play.

Still, fun game :)

**Comment by DeltaNedas** [comment]
1. this is not the bug tracker
2. template
3. this bug has been reported 5+ times already

**Comment by shaunrc493** [comment]
A. My sincere apologies, I couldn’t see a bug reporting place and deducted that feedback would have been suitable

2. Good word

Oranges. Thanks for the tally

**Comment by Catchears** [comment]
For next time, [here](https://github.com/Anuken/Mindustry/issues/new?assignees=&labels=bug&template=bug_report.md&title=)'s where you report bugs.
