### ISSUE TITLE
Rallying Poly's/Megas

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1452]
120.3

The command centre rallys attack units but not Poly's/Megas; make's sense. But my Poly's and Mega's all cluster just above the front line after an attack doing all their work, fine. But when the work is done they STAY over the front line, and so the next attack they get decimated.

It would be nice if there was a way to set a "rally to here when idle" for Poly's\Megas.

**Comment by Bohaska** [comment]
Use logic to do this, or grab someone else's code.

**Comment by CitrusWire** [comment]
> 
> 
> Use logic to do this, or grab someone else's code.

I appreciate this as a workaround solution (though I have zero interest in relearning assembly), but longer term it's worth thinking that just because any problem _can_ be solved using the new logic stuff doesn't mean it _should_ be.

**Comment by Bohaska** [comment]
> I appreciate this as a workaround solution (though I have zero interest in relearning assembly), but longer term it's worth thinking that just because any problem _can_ be solved using the new logic stuff doesn't mean it _should_ be.

You really don't get the point of why logic was introduced. Logic was introduced for people to be able to do all of these cool things without Anuke being buried in stuff a mile high. If you can't do it, then ask someone else to do it.

**Comment by Humanoid-X** [comment]
This is not hack nor mod. This is... like... Redstone in Minecraft.

**Comment by Legomonster33** [comment]
People are saying to use logic, it is very hard to detect whether or not a unit is idle, logic rebuilding is near impossible.
