### ISSUE TITLE
Overdrive "'ínsert cool name here''

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1453]
**Describe the content or mechanics you are proposing.**
A new overdrive block which is 3x3. It has mostly the same requirements as overdrive dome, and only boosts up stuff from 100% to 150%, but has the range of a Surge Tower + 8 tiles

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Players will have to choose whether they want speed or range when making bases

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
I would actually make the boost percent even lower, to about 150%, to help emphasize the fact that it is a overdriver that focuses on range; That said, lowering the boost percent too much will probably make this building useless, so more range or lower passive/build cost might help balance it a bit.

**Comment by Bohaska** [comment]
> I would actually make the boost percent even lower, to about 150%, to help emphasize the fact that it is a overdriver that focuses on range; That said, lowering the boost percent too much will probably make this building useless, so more range or lower passive/build cost might help balance it a bit.

Sure

**Comment by Humanoid-X** [comment]
Boost 100% = No Effect

**Comment by HaphLife** [comment]
So basically an overdrive dome, except it’s even longer range?

**Comment by Kyllingene** [comment]
> So basically an overdrive dome, except it’s even longer range?

And lower boost.
