### ISSUE TITLE
New tile types for editor

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#1454]
**Describe the content or mechanics you are proposing.**
Read the title. I am about to propose some new tile types, mostly for aesthetics, but one type would have an impact on units.

- Gaseous tiles. Since planets come in two brands, terrain and gas, having a shit ton of terrain tiles and no gaseous tiles is kinda selective ngl. These tiles would be of these types:
  - silicate gaseous tile: reddish-yellow in colour, similar to colour of jupiter/saturn. Ground units can walk over these, but naval units can not. Any ground unit above tier-three would slowly sink into the gas. Up till tier two, units are unaffected. Tier threes are given a speed loss on this tile [reduced to around 60% would do well, imo]
  - ammonia gaseous tiles: light blue in colour, similar to colour of uranus. Naval units units can walk over these, but ground units can not. Any naval unit above tier-three would slowly sink into the gas. Up till tier two, units are unaffected. Tier threes are given a speed loss on this tile.
  - methane gaseous tiles. Same as ammonia gaseous tiles, but deep blue in colour, similar to that of neptune.
  - Alkali-metal gaseous tiles. Same as Silicate gaseous tiles, but a deep gray in colour, almost black.
  - Ammonia-water tiles. Water tiles with a light-blue hue in them. Behave like deep water.
  - Methane-water tiles. Water tiles with a deep-blue hue in them. Behave like deep water.

Affinities:

Water extractor: 0%. For all these. We need a challenge for future planets, and no water extractors would fit in just right. If you're bent on keeping water extractors, put it down to 20%-ish.

Water

Now, for the spores.

Spore-silicate tiles. Reddish-yellow with a purple hue. Same properties as silicate tiles.
Spore-ammonia tiles. Light blue with a purple hue. Same properties as ammonia tiles.
same for all other gaseous tiles, sans the water-tiles.

Affinities: 

Cultivator: mild increase, about a 110%

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

- gas planets have feelings too
- might be suitable for harder planets, don't underestimate the community, they'll reach wave infinite on a map with just monos.
- no water extractor = more challenge.
- might open up a way to get a new fluid, which the the gas, not too sure about this one
- there is no point in getting lower tier units when you have higher tier ones, so this will be a nice counter, especially for some pvp maps.
- ties in to how planets exist in a galactic system.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RogueRedHawk** [comment]
r.i.p. #development, it died to bring this post here

**Comment by iLagSoUhax** [comment]
shh, this wasn't technically a suggestion there.

**Comment by sample-text-here** [comment]
*h m m m*
![image](https://user-images.githubusercontent.com/56274831/101230903-0b0a1280-365d-11eb-9b16-879c58c05bed.png)

**Comment by iLagSoUhax** [comment]
it wasn't put forward for consideration, i was just asking for others' thoughts, which is not a suggestion. also, wrong place to mention.

**Comment by itcannotbe** [comment]
![Screenshot_20201205_113658](https://user-images.githubusercontent.com/45280919/101232730-659f7f00-36ee-11eb-95e4-1331b19f9521.jpg)
![Screenshot_20201205_113805](https://user-images.githubusercontent.com/45280919/101232732-689a6f80-36ee-11eb-810c-fff667db8518.jpg)
