### ISSUE TITLE
The three other payload blocks.

### ISSUE THREAD

**Issue by JakeffGithubbers** [Anuken/Mindustry-Suggestions#1455]
**Describe the content or mechanics you are proposing.**
In the Dev Previews Anuke shown (and others, in Reddit), there were three other payload blocks that didn't make it to the final build. Three of them would be called Block-Loader, Block-Unloader and Block-Production, might be different to what I've seen, but yeah, those are the three other payload blocks.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would actually help a lot. One, remember the dev previews Anuke showed to where you placed a container to the unloader block, it would unload the contents of the said container? Yeah, that'd be interesting if we made some sort of factory or something, payload to payload. They'd get loaded up, unloaded down, made a block to keep the stuff repaired and all that.

It was meant to be in the game, but I'm not sure why it didn't make the cut. It does exist, but just stuck on the experimental build.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
They are all debug blocks aren't they

**Comment by JakeffGithubbers** [comment]
> They are all debug blocks aren't they

Well, one of them, no, it was legitimately shown on the dev previews, it was supposedly a planned feature. As well as the loader payload. As for the Payload Maker, I'm not sure.

**Comment by HaphLife** [comment]
Yeah, as is, with payload conveyors only transporting units feels a bit underdeveloped. 

To have better throughput than plastanium conveyors, it would have to move more than 120 items/sec (cause it’s three tiles wide) Containers have a capacity of 200 items (and it appears to move ~1 thing per second) which would put it above that speed (further if you can put multiple item types in each container).

BUT the I/O has to be usable. If items emptying out of the payload conveyor are bottlenecked, it won’t be usable. Period. Plastanium conveyors struggle with bottlenecking for anything other than vaults, containers, and the core, which makes them a struggle to use for anything else, and they are nice and small. Having to make your outputs 6 or 9 tiles wide would rapidly become unwieldy, and unusable.

Personally, I use chained fluid containers for transporting mass fluids (especially water). They are bulky, but the loading and unloading of them is trivial, so it isn’t an issue. Payload conveyors need to be like that.
