### ISSUE TITLE
A use for unused large launchpad

### ISSUE THREAD

**Issue by WHITED4WN** [Anuken/Mindustry-Suggestions#1456]
**Describe the content or mechanics you are proposing.**
The large launchpad can launch units to other loathe launchpads, up to t3 as the t4 and t5 reconstructors are larger than the launchpad as (t3 might be too). The launchpad can store X amount of an individual type of unit and when full will launch, calculation for unit exports will be floored to prevent decimals and to help prevent cheesing it. The units can either be unloaded o to a unit conveyer or unloaded and used directly, if a unit cannot be released and a new export comes in, all units inside the launch pad are destroyed. Launchpad will release units based on tier, higher tier first, lower tier last. If units of the same tier exist it will go as follows, highest to lowest priority; ground attack, ground repair, spider mechs, air attack, air repair.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently all units in a sector must be made in that sector, but with this, like items you can import units into a sector. This will make it easier to complete attack maps such as sector 69. It will also mean that you can focus more on construction of higher tier units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Pretty sure Anuke doesn’t want that

**Comment by HaphLife** [comment]
Pretty sure anuke has a plan for the interplanetary pads already. Involving interplanetary travel I presume...

**Comment by WHITED4WN** [comment]
I’m not saying for this to be used for interplanetary travel, because that’s what the interplanetary accelerator will do, I’m saying this launchpad can launch low tier units to other sectors hat also have a functional large launchpad

**Comment by RogueRedHawk** [comment]
I like this idea.

1. It allows you to set up drone production in sectors and launch them to other sectors.
2. It could give good use to payload conveyors, ferrying units into the pads for launch.
3. It brings back an old item (the large launch pad) and gives it a new twist.

It would have to be balanced, as already said launching only a few low-tier units at a time, but I think this is a cool idea.

**Comment by RogueRedHawk** [comment]
Also, large launch pads would be good for launching superweapons or satellites, both of which are things that have been at least considered to be added.
