### ISSUE TITLE
Having mindustry implement the keyboard more

### ISSUE THREAD

**Issue by reNemesic** [Anuken/Mindustry-Suggestions#1458]
**Describe the content or mechanics you are proposing.**
Having mindustry implement more keyboard uses / improve keyboard usage, through shortcuts for some actions. The most notable possible improvement has been the item selection system (1-2-3 etc.) which I find rather inconsistent and hard to use (probably could be better than my text construction in this suggestion though, lol).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I know that mindustry already uses the keyboard a lot, like F for selecting chunks for schematics / copy-pasting or ']' for mass-selection in improved units, however what I'm talking about is allowing the player to interact with buildings or units (mainly getting info) through a simple shortcut. A good example would be being able to place your mouse over a building in the side menu tab (toggled by pressing C) and using a shortcut to get to the info menu, without having to click on the question mark. 
 
To go back to the item selection system I mentioned earlier, I suggest removing the first number of the number series and having selection happen in the current tab (which could potentially be chosen using the Tab button).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
I implemented the block selection hotkey system. What specific suggestions do you have for it?

**Comment by joshuaptfan** [comment]
I implemented the block selection hotkey system. I disagree with your suggestion, as the current method allows you to rapidly switch between blocks in different categories.

However, I have found myself using the directional selection keys on M+KB recently, even though they were intended for use with a controller. Just press any of the arrow keys to simultaneously navigate and select blocks.

**Comment by reNemesic** [comment]
Thank you for receiving my input, I hope development isn't going too bad

As a side question, I have noticed that mindustry seems to be running smoother, but the FPS counter is outputting the same values... 
I haven't checked the source code yet, but did the algorithm handling FPS outputting change?=
