### ISSUE TITLE
Unit repairing laser bolts

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1459]
**Describe the content or mechanics you are proposing.**
Support unit weapons that heal buildings should be able to heal units as well.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Because it makes sense and gives extra reasons to actually use the heal function of support weapons. After all, if blocks of any kind can be healed by a support weapon, so should units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have not checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I haven't fully read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quick-korkc** [comment]
nova and poly can heal unit too,
but with aura

**Comment by Bohaska** [comment]
Lemme go check out the code for these laser bolts...

**Comment by Kyllingene** [comment]
> Lemme go check out the code for these laser bolts...

Any discoveries?
