### ISSUE TITLE
A few aesthetical decoration blocks to make late game bases look nicer

### ISSUE THREAD

**Issue by SlavaCat118** [Anuken/Mindustry-Suggestions#1461]
**Describe the content or mechanics you are proposing.**
A few aesthetical decoration blocks to make late game bases look nicer

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The title really says it all, These blocks would have no effect other than making things look nicer.
A few ideas:
- Corner pieces
- Path blocks, with different degrees of weathering
- Directional arrows
- Statues
- Trees
- Item Frames
- Decorative walls
- Other mechanical looking décor
These could be helpful on servers so new people joining could be directed where to go without having to pester everyone in chat.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Should these be built by a player in-game, or they can only be set by a map creators?

**Comment by SlavaCat118** [comment]
> Should these be built by a player in-game, or they can only be set by a map creators?

Built by players in game, they would have their own tab.

**Comment by HaphLife** [comment]
Definitely an interesting idea. Perhaps there should be different aesthetic blocks for each tier of materials?
As is the game is entirely focused around functionality, and it might be cool to add aesthetic blocks.

**Comment by Bohaska** [comment]
Imagine if someone spammed a wall of trees to block enemies...

**Comment by HaphLife** [comment]
> Imagine if someone spammed a wall of trees to block enemies...

Presumably they would be destructible.

**Comment by SlavaCat118** [comment]
> Imagine if someone spammed a wall of trees to block enemies...

Yeah I mentioned they would have no functional purpose

**Comment by Kyllingene** [comment]
I see no reason why not. In fact, I am sure that there are probably more than a few mods that have this, because it just seems nice to have. If I get around to it, I will probably throw together some poor sprites and make an example of how they might work (not a PR, since it would be low-effort and messy).
