### ISSUE TITLE
Bring Back The Ability To Unlock Materials While Playing Remotely on Someone Else's Campaign

### ISSUE THREAD

**Issue by zicklag** [Anuken/Mindustry-Suggestions#1462]
**Describe what you would like changed, and why.**

Me and my brothers would play multi-player Mindustry campaign but with the latest 6.0 release we noticed that you can't actually build upon your own campaign and tech tree while playing multiplayer.

**Describe the changes you want to propose. Include possible alternatives.**

I think it still makes sense that you should be able to unlock materials that can be used to advance your own tech tree while playing multi-player campaign. I'm not sure if maybe it should be an option, whether or not you want to use the tech tree of your host or to use your own tech tree.

**Comment by RogueRedHawk** [comment]
I have been trying to advocate for multiplayer campaign functionality throughout much of the development process the past 6-7 months for exactly the same reason. My brother's and several of my friends like to play Mindustry together. Based on the way development has continued to progress, it is unlikely this feature will be brought back. Anuke has mentioned multiple times that campaigns transferring does not make sense to him.

**Comment by Anuken** [comment]
I understand the need for shared progression, but I don't really see a good way to implement it. The old campaign system was much simpler, and made for designing co-op easy - ***obvious***, even. I can't just take those old mechanics and shove them into this new complex system where the entire framework for it is gone.

I *would* like to implement more co-op features, but there is no obvious means of doing so without introducing complex and confusing mechanics.

**Comment by zicklag** [comment]
@Anuken You have a decent point. With the new campaign system a way to co-op campaign is not as obvious.

I would say that maybe the most disappointing thing about the multi-player campaign was that the materials that I gathered with the players I was playing with were not collected for my campaign and I couldn't use them to contribute to my Tech tree. Maybe it makes sense that the materials you gain are the only thing that transfer over on multi-player campaign.

The other thought is that I'm not sure if it makes sense to have like a checkmark or an option somewhere that determines whether or not you use your own tech tree when joining somebody else's multiplayer campaign. I can see players in different situations wanting both:

- On one hand, being able to join somebody else's campaign with your own personalized tech tree and the things you have been able to unlock is cool. That's how we used to play on the old campaign.
- On the other hand, if you are a newbie who hasn't unlocked anything, it would be nice to maybe be able to join somebody else's campaign and share what they have unlocked because they are playing a difficult level and you are going to need the extra turrets from their tech tree.

Adding settings that you don't really have to is always lame, but it seems like this might be one that warrants a simple option either in the settings or in the multi-player join menu or something.

Anyway, just my thoughts. Thanks for the great game!

**Comment by zicklag** [comment]
From the latest release notes.

![image](https://user-images.githubusercontent.com/25393315/101290206-5ab81d80-37c6-11eb-8bb0-9369b8a1d5dc.png)

I'll test it with my brothers soon, but that looks like it covers what we were wanting, thanks!
