### ISSUE TITLE
Double clicking a normal conveyor belt with a titanium one should already replace all the other ones next to it

### ISSUE THREAD

**Issue by bloool** [Anuken/Mindustry-Suggestions#1464]
Basically, if you have a normal conveyor belt, double-clicking it while having a titanium conveyor in hands, would replace the whole conveyor line with titanium (with replacing I don't mean instantly replacing it and more of just putting it on the "build queue"), this could also work with titanium and the other 2 types of conveyors.

I think this would overall just make the gameplay faster because even without it, the player can just pause and replace all the conveyors manually and get the exact same result as if this would be implemented but in a longer amount of time.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RogueRedHawk** [comment]
This is a good idea.

**Comment by itcannotbe** [comment]
This is kinda of hard to implement and easily be converted to a greifing tool. Also you will have complications with the armored conveyor and plastanium conveyor.

**Comment by blool22** [comment]
> This is kinda of hard to implement and easily be converted to a greifing tool. Also you will have complications with the armored conveyor and plastanium conveyor.

How could this work as a griefing tool and what are the complications?

**Comment by Catchears** [comment]
I wouldn't do it for plastanium conveyors because they don't always work like normal conveyors.

**Comment by Kyllingene** [comment]
[A version is already implemented](https://github.com/Anuken/Mindustry/pull/3912)
