### ISSUE TITLE
death during formation

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1465]
**Describe what you would like changed, and why.**

currently when you die while commanding units you jump to the nearest of the same type, and any formation is lost.

**Describe the changes you want to propose. Include possible alternatives.**

when you die while in formation, if the unit you jump to was part of that formation: keep the formation alive on that unit.

(and possibly switch to any unit in the formation upon death, and not just commanded units of the same type)

**Comment by HaphLife** [comment]
Perhaps it should also try to make another unit join the formation, if there is one nearby, to replace the one that died.

**Comment by Quezler** [comment]
that doesn't sound like the best idea ^

**Comment by HaphLife** [comment]
> that doesn't sound like the best idea ^

What’s wrong with that idea?

**Comment by hribik100** [comment]
> > that doesn't sound like the best idea ^
> 
> What’s wrong with that idea?

Nothing
