### ISSUE TITLE
Units "Rally"ing at a command centre should actually attack

### ISSUE THREAD

**Issue by h3rlihy** [Anuken/Mindustry-Suggestions#1466]
Units set to rally at a command centre, perhaps near the core for example as defense, shouldn't just sit there & do literally nothing as enemy units walk past. They should stay near the rally point but still actively attack enemy units

**Comment by h3rlihy** [comment]
I tried "idle" stance after rallying to the command centre, they still sat there & did nothing

**Comment by matkoniecz** [comment]
And on "attack" they will happily leave and run into turret wall. Especially flying units like to attack flak groups and die pointlessly in hail of scrap.

**Comment by h3rlihy** [comment]
> And on "attack" they will happily leave and run into a turret wall. Especially flying units like to attack flak groups and die pointlessly in hail of scrap.

Yes exactly! But if they attacked nearby units when rallying at a command centre you could actually have them defend a point of your choosing

**Comment by matkoniecz** [comment]
I think that in v5 rallying units actually attacked - so you could use it for desperate defence of core, especially in PvP.
