### ISSUE TITLE
Unlocking Research Feels A Bit Backwards

### ISSUE THREAD

**Issue by h3rlihy** [Anuken/Mindustry-Suggestions#1467]
Playing through the v6 campaign from the start & the way you are unlocking techs feels a bit backwards. The craters is your first sector with water, but you have to capture the sector before you can unlock any of the water tech. When really, while capturing this sector is when you feel like you want to be experimenting with it. Similarly, ruinous shores you have to complete to be able to research the naval factory, right as you have just completed the sector where the naval factory would have been a good structure to play around with. Things are locked away requiring you to capture the sectors where you would otherwise want to use them.

**Comment by joshuaptfan** [comment]
Yeah, perhaps such tech should unlock upon launching into the map. The slippery slope is that players could launch into maps and abandon them, but you lose undefended sectors if you are playing on another map, launching costs resources, and you'd be wasting an opportunity to unlock the next sectors by capturing that one.

**Comment by h3rlihy** [comment]
> Yeah, perhaps such tech should unlock upon launching into the map. The slippery slope is that players could launch into maps and abandon them, but you lose undefended sectors if you are playing on another map, launching costs resources, and you'd be wasting an opportunity to unlock the next sectors by capturing that one.

You need to finish the maps that allow you to research new tech to progress further in the campaign to unlock the next stuff though, so I think not so much a valid concern. & you do still need to put the resources into researching stuff. I think some of the tech that is unlocking on capturing sectors makes more sense to become available for research at the start of the sector. If the player then abandons that sector then they still aren't going to be able to progress further in the campaign

**Comment by HaphLife** [comment]
> You need to finish the maps that allow you to research new tech to progress further in the campaign to unlock the next stuff though, so I think not so much a valid concern. & you do still need to put the resources into researching stuff. I think some of the tech that is unlocking on capturing sectors makes more sense to become available for research at the start of the sector. If the player then abandons that sector then they still aren't going to be able to progress further in the campaign

    Yeah. Totally. As long as the next tech tier is gated behind actually finishing the map, this shouldn’t be an issue. People might launch and abandon, but they still have to go back when they want to unlock the next map.
    I guess you *could* try to specifically avoid capturing the tech unlocking sectors and find the next map by capturing adjacent sectors all the way around the world, but that’s so much more work, so I don’t see that as an issue.

**Comment by HaphLife** [comment]
No clue how I did that text thing...

**Comment by h3rlihy** [comment]
> ```
> No clue how I did that text thing...
> ```

I'm offended by the text thing

**Comment by h3rlihy** [comment]
Also, campaign maps don't unlock via adjacency, you have to capture the required sector to abvance

**Comment by Bohaska** [comment]
> like this? <

**Comment by Humanoid-X** [comment]
`This is called github code block.`
