### ISSUE TITLE
display payload unit contents

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1469]
**Describe what you would like changed, and why.**

currently there is no way of knowing what kind of payload is in which unit.

**Describe the changes you want to propose. Include possible alternatives.**

display it somewhere in the placement fragment on hover or under the health in the top left corner.

i've played a round a little with the on hover method just now, but it didn't feel right enough.

nevertheless ima leave the patch here, maybe it can inspire someone: 
[0001-hi-anuke.patch.txt](https://github.com/Anuken/Mindustry-Suggestions/files/5649305/0001-hi-anuke.patch.txt)

screenshot of the latest attempt, unfortunately didn't make a screenshot for all of them:
![Screen Shot 2020-12-06 at 19 16 05](https://user-images.githubusercontent.com/3179271/101288662-0cbc0d80-37f8-11eb-8b7b-21b1a07af023.png)

**Comment by Slava0135** [comment]
***oh yes***

**Comment by Slava0135** [comment]
It seems ok to me, why not try making a PR and work together on it?

**Comment by Slava0135** [comment]
The only bad thing is that it's too wide, especially for mobile.

**Comment by Quezler** [comment]
> The only bad thing is that it's too wide, especially for mobile.

that is just one of my many failed attempts, i don't have pics of the first few i've tried ^
