### ISSUE TITLE
Creep pathing is prioritizing shortest path too much

### ISSUE THREAD

**Issue by tmanpdx** [Anuken/Mindustry-Suggestions#147]
**Describe what you would like changed, and why.**

While I think that the feature of having creeps attack weak walls is an interesting twist to TD genre, TD games are about pathing and with the great maps that Mindustry has, it's a shame that it's so difficult to implement a maze. Today, the creeps prioritize shortest path over fastest path and will head straight towards a wall instead of going around . This causes the creeps to bunch up and be easy to kill. 

I think the the fact that creeps fire and weaken walls is a great feature and over time this can cause a breech in the wall thus shortening the path. I feel this is enough of a deterrent to making really long overlapping mazes with small copper blocks. 

**Describe the changes you want to propose. Include possible alternatives.**

Have ability to maze creeps and have creeps prioritize freedom to move over shortest path, but do keep minimal weighting to shortest path to reduce super long paths that people could make.

**Comment by potatoisagender** [comment]
creeps?

**Comment by Anuken** [comment]
Seems reasonable. With the current balance, units could only choose to go up to 20 (open, with no walls on any side) tiles further for each block in their way, which was a bit unreasonable. In terms of tile distance around an object, 20 is a very small number. I have significantly increased that cap, and made units more likely to go around walls.
