### ISSUE TITLE
Block Payload Control for Units [Logic]

### ISSUE THREAD

**Issue by FlippingPotatoes** [Anuken/Mindustry-Suggestions#1470]
**Describe the content or mechanics you are proposing.**

In mindustry v6, using logic processors you can command a unit capable of picking up payloads to pick up units, however it currently doesn't allow for moving of blocks.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The core mechanic is already there in the game, just very limited for factory purposes. With this feature, logic can be used to move factories or small setups, transport thorium reactors to do bombing runs more swiftly, or move batches of items in storage blocks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[A Definite No] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by FlippingPotatoes** [comment]
> [A Definite No] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

I have extensively tested this with logic processors as they currently exist in the game, they can’t cause a unit to pick up blocks, if you can make a schematic or paste code that accomplishes this it would be very appreciated and I’ll close this thread.

**Comment by itcannotbe** [comment]
> > [A Definite No] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> I have extensively tested this with logic processors as they currently exist in the game, they can’t cause a unit to pick up blocks, if you can make a schematic or paste code that accomplishes this it would be very appreciated and I’ll close this thread.

You need 3 things, of the 3 you need, you already have one.
1. Knowledge of which units can pick up blocks and how large they can carry.
2. Knowledge in Mindustry Logic, Especially on how to use PayTake and PayDrop instructions
3. A brain that can understand how to code mindustry logic.

Thank you for cooperation.

**Comment by FlippingPotatoes** [comment]
There’s not much point with you stating this if you can’t prove contrary, it’s rather simple, the current logic operations only have a control that interacts with units, specifically “ucontrol payTake” specifies takeUnits, and only works with units unsurprisingly by its labeling, however this is counterintuitive to the player having the ability to pick up blocks while controlling any unit that is capable of payloading.

**Comment by FlippingPotatoes** [comment]
Actually apologies, the current system can’t take referenced objects, it only works through object names, I apologize for wasting the time of anyone who’s viewed this.

**Comment by RogueRedHawk** [comment]
https://cdn.discordapp.com/attachments/742769933926269069/778310742038413323/5fb406e931826382447829.gif

It's ok, sometimes it's hard to find stuff like this in the ocean on Mindustry..
