### ISSUE TITLE
campaign volcanoes

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry-Suggestions#1471]
**Describe the content or mechanics you are proposing.**
Volcanoes around Serpulo, because actually, I've never found liquid slag in any sector, from g0 to planetary launch terminal.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
possibility of finding liquid slag and other *hot stuff*, next to poles, with bases using separators and disassemblers.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Did you check every unnamed sector?

**Comment by itcannotbe** [comment]
Also you can't pump lava directly from the lake and convert that into everything because that would be OP.

**Comment by hadron13** [comment]
> Also you can't pump lava directly from the lake and convert that into everything because that would be OP.

this is why it should be on poles with erad difficulty
