### ISSUE TITLE
Logic Repository 

### ISSUE THREAD

**Issue by Lunardog15** [Anuken/Mindustry-Suggestions#1472]
It would be cool if there was some sort of repository or something for Logic Code

**Comment by benelverson** [comment]
Yeah that way you wouldn't have to reinvent the wheel every time you did something basic, and it'd save you from debugging stuff too

**Comment by itcannotbe** [comment]
The template died when you ignore to choose a label during issue creation. Also schematics already exist. Why is this relevant? Because logic blocks carry their code in them in schematics.

**Comment by Kyllingene** [comment]
> Yeah that way you wouldn't have to reinvent the wheel every time you did something basic, and it'd save you from debugging stuff too

r/Mindustry

This issue is not well made. For one, there is no label, so it's hard to tell what type of suggestion it is. Two, it leaves out the information the template was made for, which makes it hard to understand. I am honestly confused, it took extra work to bypass the template.

**Comment by Lunardog15** [comment]
1 I don't even know how I messed up the template
2 can someone help me put a label on this?

**Comment by Kyllingene** [comment]
By "messed up", we mean you didn't use it. That template includes information that is helpful (as in often necessary) to have. And as for a label, "feature request" would be a good one.
Here is the template:

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

```

**Comment by RogueRedHawk** [comment]
@Lunardog15 I've done this before where the label/template didn't load, and it made me create an issue without the template. Not your fault, GitHub just messes up sometimes idk why

**Comment by Lunardog15** [comment]
Ok I'll fix in the morning

**Comment by itcannotbe** [comment]
It's called not using the right link.
