### ISSUE TITLE
Friend System

### ISSUE THREAD

**Issue by GlowScarf** [Anuken/Mindustry-Suggestions#1473]
**Describe the content or mechanics you are proposing.**
Friends list. Online status. If on server tap to join them.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Lol I just found someone, was having fun until they banned him from a server and never to be seen again. So friend list can help with communicating with others e.t.c.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by HaphLife** [comment]
Since there aren’t any accounts, I don’t know how this would work.

Unless you are on steam, but there’s probably already a steam friend system.

**Comment by itcannotbe** [comment]
Is this part of why steam version existed?

**Comment by Quezler** [comment]
^

**Comment by GlowScarf** [comment]
Hm you are right I guess. Then maybe make an account system to also save out progress online in case something happens to your device and you didn't save it. Idk.

**Comment by kiVts** [comment]
Not a game where friends list should exist

**Comment by DeltaNedas** [comment]
why should every game implement its own friends system
use steam
close this

**Comment by GlowScarf** [comment]
What about mobile players lol

**Comment by GlowScarf** [comment]
Anyway close it. I don't see any hope

**Comment by DeltaNedas** [comment]
if you want to back up your game without using steam see git(1)
