### ISSUE TITLE
Spot lights

### ISSUE THREAD

**Issue by SomeRandoGithubber** [Anuken/Mindustry-Suggestions#1474]
I love this game, but as ive been playing it daily ive noticed some things that i think would improve the game

Spotlights could be a nice addition, basically lights that don't have a wide area but launch light in a specific area for the nights which are great but its low visibility could be annoying, it would be super useful if i could keep lights behind my turrets but still see ahead of them

**Comment by Bohaska** [comment]
A pull request for them is underway... check Anuken/Mindustry and click pull requests and you will find that someone is trying to make floodlights/spotlights.

**Comment by itcannotbe** [comment]
I love this suggestion repository, but as ive been going through it daily. I've noticed some things.

1. [X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

That aside, can directional casting of illumination be done?

**Comment by sample-text-here** [comment]
@itcannotbe here's the pr that Bohaska mentioned: https://github.com/Anuken/Mindustry/pull/3806. it looks like it is possible, though with some glitches

**Comment by matkoniecz** [comment]
> I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

Bot that would close all issues that failed to fill template would be maginficent.

**Comment by sample-text-here** [comment]
yes yes we need a bot #1438
