### ISSUE TITLE
QoL: Using F as a Pipette tool when selecting a single object

### ISSUE THREAD

**Issue by TeoNikolov** [Anuken/Mindustry-Suggestions#1475]
**Describe the content or mechanics you are proposing.**
You have the ability to copy-paste existing objects with F and you can select a single object.
One reason why you may want to select a single object is because it is (for me) much faster to start building it, rather than pressing hotkeys / clicking the menu bottom-right.

I propose that when you select a single object via F, you are able to place the object as you would as if you selected it via hotkey / the menu. Specifically, if you select a belt (or something like a drill), you would be able to DRAG and have the original functionality of building a belt, forming a row of said object.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This is just a QoL change, which probably targets a bit of a minority. This mechanic is present in Factorio, where Q acts as a pipette tool and selects what is beneath your cursor so you can place it afterwards. This seems a lot faster, as you select based on visual queues, rather than (muscle) memory.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Would appreciate a response on this if possible :3

**Comment by GreyMario** [comment]
Counterpoint: using the selection copy will also copy a logic processors' code, including block bindings.

There's already this exact function anyway: _press the mousewheel._

**Comment by TeoNikolov** [comment]
> 
> 
> Counterpoint: using the selection copy will also copy a logic processors' code, including block bindings.
> 
> There's already this exact function anyway: _press the mousewheel._

Tested and I agree at this point. I guess I missed the middle mousewheel option.
Closing the ticket then, thanks for the info!
