### ISSUE TITLE
Maps N' Zones

### ISSUE THREAD

**Issue by Kicrops** [Anuken/Mindustry-Suggestions#1478]
As in the V6 the map chart dissappeared and we now have the planets (cool ngl) I suggest that there is a button in tech three that you touch it and shows you a list of every single deployable place. Showing what items you can get, total rounds, enemy troops and if it is Attackk or Survival. I think it would help a lot because idk where to go

**Comment by itcannotbe** [comment]
A list of 275 sectors is not going to be remotely helpful because the numbers themselves doesn't mean nothing useful.

**Comment by Legomonster33** [comment]
> A list of 275 sectors is not going to be remotely helpful because the numbers themselves doesn't mean anything useful.

it would also have to include a relative location so you can find it
ie, 2 sectors sorthweast from sector 3
(pentagons could be landmarks)
