### ISSUE TITLE
Building scheduled for deconstruction and destroyed by enemy should not be reconstructed by drones

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry-Suggestions#1479]
**Describe the content or mechanics you are proposing.**

Rebuild drone rebuilds what I want to demolish as it is a lost area, overtaken by enemy. Rebuild drones waste resources endlessly as a result.

Right now cancelling building is ignored by drones.

See https://github.com/Anuken/Mindustry/issues/3829 for more info

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Right now poly drones are extremely irritating in some cases like losing territory what start making them negative and burned in some cases.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. Directly confirmed by @Anuken - https://github.com/Anuken/Mindustry/issues/3829#issuecomment-739590012 "There simply is no implementation of this."
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Delete the ghost of the old building and be done with it.

**Comment by Erisfiregamer1** [comment]
That's the problem. It rebuilds the ghost.

**Comment by matkoniecz** [comment]
> Delete the ghost of the old building and be done with it.

How can I do this?

![Peek 2020-12-07 00-13](https://user-images.githubusercontent.com/899988/101296071-b4016a80-3821-11eb-96c1-45526acce9b9.gif)

**Comment by RogueRedHawk** [comment]
> Delete the ghost of the old building and be done with it.

If you're playing on servers, the ghost isn't there when things are destroyed.

**Comment by Legomonster33** [comment]
> Delete the ghost of the old building and be done with it.

that nearly never works :\

**Comment by itcannotbe** [comment]
Probably what would work is a cancel + deconstruct mode.

**Comment by Legomonster33** [comment]
> Probably what would work is a cancel + deconstruct mode.

nop

polies = annoying fuckers

**Comment by itcannotbe** [comment]
> > Probably what would work is a cancel + deconstruct mode.
> 
> nop
> 
> polies = annoying fuckers

Same issue with v5 phantoms tbh.

**Comment by matkoniecz** [comment]
Yeah, it is not new.

**Comment by Bohaska** [comment]
Force the Poly's to rally to command centre and then delete the ghosts and ask them to go back with their work

**Comment by matkoniecz** [comment]
Ghost is not shown until rebuild drone starts rebuilding.

**Comment by Legomonster33** [comment]
> Force the Poly's to rally to command centre and then delete the ghosts and ask them to go back with their work

Polies don't follow command centre orders

**Comment by Bohaska** [comment]
first, nuke your poly's using thorium reactor and thorium, then delete the ghost and then rebuild the polys

**Comment by Bohaska** [comment]
first, nuke your poly's using thorium reactor and thorium, then delete the ghost and then rebuild the polys

**Comment by Bohaska** [comment]
It works...
