### ISSUE TITLE
C/C++ api for mods/plugins

### ISSUE THREAD

**Issue by IpProxyNeon** [Anuken/Mindustry-Suggestions#148]
1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Heya, i want to have to have the ability to write mods/plugins in C or C++, because I can't understand Java (and JavaScript uses ES5 right now and is extremely limited) and it's not really convenient to learn a language for a game i like playing, so i think a C or C++ api would be nice. The benefits of having an api for C/C++ would be that:

A) Many other languages would be able to use the API (not just C or C++)

B) This would attract more developers who do not know Java or any jvm-based langs to develop for this game, which would be nice

**Comment by Xusk947** [comment]
Not Lua api for mods

**Comment by DeltaNedas** [comment]
very bad idea

**Comment by KSean222** [comment]
The only way this can be safely achieved is likely through WebAssembly, which is a recent technology, and may not be supported on mobile devices. It may also not be available for embedding in Java. Simply loading a dynamic library has terrible security implications, and is also not cross platform.

**Comment by IpProxyNeon** [comment]
Yeah, i thought this would be the response 😅

How about if it was Python? (very unlikely to get implemented) Since there are Python for mobile projects, and Python is a good scripting language imo

**Comment by Anuken** [comment]
> because I can't understand Java

This is a terrible reason for creating an entirely new plugin API. If you really know C/C++, Java should be easy to learn. I have no interest in adding support for yet another language.
