### ISSUE TITLE
The campaign

### ISSUE THREAD

**Issue by Peter-L-H** [Anuken/Mindustry-Suggestions#1480]
I think it is better to add a feature of **resources transmission**. Also, I would like to have **infinite wave** instead of leave the base alone and have nothing to do.

**Comment by BlueWolf3682** [comment]
template.

**Comment by Arackulele** [comment]
1.Have you heard of launchpads
2.Infinite waves are a thing.Sectors get attacked again after a certain time

**Comment by DarkBrick** [comment]
Removed template - Check
Custom games and launch pads exist - Check

**Comment by DeltaNedas** [comment]
@Peter-L-H close this you egg
