### ISSUE TITLE
Comment block in logic

### ISSUE THREAD

**Issue by Teok25** [Anuken/Mindustry-Suggestions#1481]
I think many of us who have been enjoying the logic system this week will agree, but commenting in programming is _essential_ for readability and sanity.
For this, I think a comment block would be good to add into the system, which does nothing apart from allow the user to put in a string of text for code hygiene. This block could be green so it stands out against the other blocks, making it easier to read overall.

Not only do I think this would be easy to add into the game, I think it would make creating and using logic blocks multitudes easier for both the programmer and the end user, as one can have inbuilt instructions on how to use it, or one can clearly see what part of code is doing what.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[You didn't] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
Before you say you actually did.
This is a duplicate of #413

**Comment by Teok25** [comment]
I did do a quick search, but only from 6.0 launch onwards, as I didn't know that there was access to a branch with microprocessors months ago.

**Comment by DeltaNedas** [comment]
`# i am a comment`
if you value readability, why are you using the visual editor?

**Comment by Teok25** [comment]
@DeltaNedas Did you read why I wanted comments in the visual editor, or no? It's because it's a lacking feature _of_ the visual editor. Why even gatekeep this, it harms nobody and benefits everybody if logic systems **in game** are more readable for both programmer and user.

**Comment by Legomonster33** [comment]
`set comment "type here"`
