### ISSUE TITLE
Change sorter mechanics to be map-oriented rather than object-oriented

### ISSUE THREAD

**Issue by Ozymandias42** [Anuken/Mindustry-Suggestions#1482]
**Change input-output directionality of sorters to map-orientation**
**Reason:**
Enables sorter junctions and makes more sense in games with a static map-orientation.

**Why this is not possible as of now**
With object relativity an item coming from the right can be filtered. If it passes it continues forwards, in this case to the right if not to the sides, which are up and down the map.
A secondary belt coming from below with a non-passing item-type would now be blocked instead of passing through and out the top unimpeded because the direction relative to the incoming belt would be forwards, hence the filter would not let it pass. 
![image](https://user-images.githubusercontent.com/664534/101371566-341fe280-38ab-11eb-831b-dbe30e13bc1a.png)

**How tying the sorter to map-directions makes it possible**
If forwards and backwards are tied to north and south, then filter-passing input will always exit in those directions no matter if the incoming belt comes from the top, below or the sides.
This enables two input-belts coming from the right and one from below with a filter that filters both inputs such, that non-passing input leaves at the top and passing input on the left.

**Comment by itcannotbe** [comment]
1. This is something only you would like.
2. How on earth woulf the game determine what the primary and the secondary belt is?

**Comment by Kellegram** [comment]
>     1. This is something only you would like.
Did you survey everyone to come to this conclusion? 

If you disagree, provide reasoning instead of being a dick.

**Comment by Ozymandias42** [comment]
>     1. This is something only you would like.
> 
>     2. How on earth would the game determine what the primary and the secondary belt is?
> 
>     3. How hard is it to solve your problem with a junction amd a sorter?

1. doubt.
2. there is no primary or secondary. No belt takes precedece because there are only inputs and outputs. Filter direction is tied to the map, not inputs. This means it doesn't matter what belt I connected first or second. the filter filters what it is told to to an output at north and south.  
If at one of those directions is an input it naturally will not be outputted there. The game has nothing _to_ determine.
3. why would I waste resources doing something complicated if a single unit would do if used smart?

**Comment by itcannotbe** [comment]
1. Sorter mechanics have been the same for years already. And no one even hinted that they wanted this.
2. This would break thousands of designs already used by players in the player base.
3. This would actually complicate thing as it would only have fixed outputs, hemce less flexibility.

**Comment by scarf-generic** [comment]
for once in my life, i agree with itcannotbe. this really is a terrible suggestion.
all this really does is break schematics for no reason (what we have now works fine, nothing needs to be changed), as well as make rotating schematics practically impossible. heres an image of all the possible needs for sorting items, which you can already do without breaking sorters.
![20201207_102354](https://user-images.githubusercontent.com/69741577/101376567-5fd4a580-3876-11eb-9058-be736eb9b899.jpg)
making sorters/inverted sorters rotation based will do nothing but make the game worse. you can already do everything with them and they have gone years without complaint.

**Comment by Ozymandias42** [comment]
> as well as make rotating schematics practically impossible. 
I didn't think about rotating schematics. That's true. That _would_ break if it was tied to the map.

Anyway, your screenshot does not have _all the possible needs for sorting items_ as you put it.
In every case you have shown there is only a single unsorted input-belt.
My specific case would have two unsorted belts, where item type 1 is supposed to go left, wether it comes from below or from the right and type 2 to go up. 

Maybe a workaround might be a combination of a distributor and sorters...

**Comment by scarf-generic** [comment]
![20201207_153906](https://user-images.githubusercontent.com/69741577/101408599-42b5cc00-38a2-11eb-8536-37c81e0f6d39.jpg)
tada.

**Comment by DeltaNedas** [comment]
1. do not mix belts
2. you dont need to break sorters for your very specific use case
3. mods

**Comment by scarf-generic** [comment]
1. close this issue
2. the dislike to like ratio is 6:0 on github and 12:0 on discord
3. its unlikely to get added
4. ok really, close this issue
