### ISSUE TITLE
Planet/Mission selection

### ISSUE THREAD

**Issue by hidenwolf** [Anuken/Mindustry-Suggestions#1485]
**Describe what you would like changed, and why.**
Navigation of the planet is rather Aggravating and you can get lost or spend what feels like a silly amount of time trying to figure out where to go next.  While that is annoying, it is pretty cool, more so than the previous 5.0 msn selection, just needs a bit of love and sprucing up.

**Describe the changes you want to propose. Include possible alternatives.**
Add a list on the side that lists out all the available places.  You should have filtering buttons such as:   All, msns only, non msns, completed, uncompleted, named, resources available, resource production rate, and most importantly a quick search function to get through the ones you name.

When you click on a map name, planet should automatically orbit there.

I apologize if this is already planned.

**Comment by firstcreator48** [comment]
i love it
