### ISSUE TITLE
Difficulty Curve Is A Bit Crazypants

### ISSUE THREAD

**Issue by h3rlihy** [Anuken/Mindustry-Suggestions#1486]
**Describe what you would like changed, and why.**
I remember this was an issue in v5 too, been playing through the v6 campaign from the start & it is not ideal that you have no idea what is coming. Just been entirely steamrolled by the guardian on wave 30 of stained mountains, thought this guardian was an air one, had a gratuitous amount of scatters loaded with metaglass. But it was not & the defense that was otherwise very adequate for the preceeding 30 waves was a complete flop vs the guardian. Now I've launched back into the sector & am building a big ol' bunch of ripples that should handle it no problem. The silly thing is, I could have had the big ol' bunch of ripples no problem the first time, but they would have been significant overkill vs the rest of the waves. How is the player to expect this & prepare appropriately?

**Describe the changes you want to propose. Include possible alternatives.**
Some sort of indication, even if it is vague, on what is likely to be coming at you. Just knowing air guardian or ground guardian would allow better prep. Along the same lines would be useful to know if a sector was going to send air units at you, at times you find yourself building air defense that sits there & does nothing at all.

If the difficulty curve is going to be a right angle, then fair enough, lol, but if you don't know that right angle is coming you have no chance

**Comment by DeltaNedas** [comment]
git gud and use generators to bait air units

**Comment by h3rlihy** [comment]
> git gud and use generators to bait air units

Literally entirey besides the point. Could've built the ripples the first time, there was no need at all as the previous 29 waves were a walk

**Comment by SupremeTurtle** [comment]
If you didin't know what was coming, why did you assume it was just simply an air guardian without even knowing?
Should've built both Ripples and Scatters.

**Comment by h3rlihy** [comment]
Because the difficulty curve wasn't this sharp on stained mountains in v5, only Overgrowth. All well & good saying you should always build a shitload of ripples but when your defense isn't otherwise as much as tickled by the previous 29 waves you don't expect it to be necessary.

**Comment by Psirus** [comment]
I have to agree with this. The first 29 waves didn't get past the "outskirts" of my defense, but the boss just calmly walked by all of it. I would have had the resources to do more, but when I want to try that now, I have to replay all the 29 previous waves, which is quite tedious.
