### ISSUE TITLE
Adding A New Toggleable Setting in Editor for Maps

### ISSUE THREAD

**Issue by TNT331** [Anuken/Mindustry-Suggestions#1488]
**Describe the content or mechanics you are proposing.**
Adding a toggable setting which allows the map to be dark(gray). When an area has not been explored, it will not show what is there untill a unit/building is there. Lighter gray can represent scouted areas, shwoing the buildings that was last scouted by the team/player/unit. See StarCraft II for refernce.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This could add more stratagies and differnt new gamemodes to the game(Could be added to Campaign as well)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
5. - [x] :+1:

**Comment by TNT331** [comment]
Just a fun feature to have, Allowing more competitve pvp(ranked)<- ranked just as an example, but having more "creative" gamemodes would be very intresting

**Comment by itcannotbe** [comment]
This is clearly not called **FOG OF WAR**
Duplicate of #498
