### ISSUE TITLE
Tech/Upgrades

### ISSUE THREAD

**Issue by TNT331** [Anuken/Mindustry-Suggestions#1489]
**Describe the content or mechanics you are proposing.**
Being able to upgrade turrets/units in terms of damage, weapons, health, and speed.(armor, shield batteries, extra weapon, range etc.......) Reqiure upgrade centrues which can be added in to the future.

Building expensive upgrade buildings to advace to the next level, unlocking more building each time.(Like teirs in StarCraft)

This will limite rushes, and adds more stratagies to the game.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[No. You didn't even try] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
Duplicate of #283 and #1483 583

**Comment by TNT331** [comment]
its not
this is because its a differnt idea

**Comment by TNT331** [comment]
and I am not saying it will add a new weapon, its when you compleat a reserch, or a building, the new units which are now produced gains that status

**Comment by TNT331** [comment]
upgrading turet is just like damage upgrade or adding new attribute like fdaster cooldown and less heat or smt

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081327](https://user-images.githubusercontent.com/45280919/101420501-47739200-392d-11eb-8a2f-2f6cc13f8bb1.jpg)

**Comment by TNT331** [comment]
well thats differnt

**Comment by TNT331** [comment]
idm its just a suggestion

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081448](https://user-images.githubusercontent.com/45280919/101420669-9e796700-392d-11eb-8108-58e0d5823e7b.jpg)
![Screenshot_20201208_081505](https://user-images.githubusercontent.com/45280919/101420675-a20cee00-392d-11eb-8ff6-f805edcf7377.jpg)

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081753](https://user-images.githubusercontent.com/45280919/101420786-e4cec600-392d-11eb-9965-ed7324c658ee.jpg)

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081753](https://user-images.githubusercontent.com/45280919/101420786-e4cec600-392d-11eb-9965-ed7324c658ee.jpg)

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081753](https://user-images.githubusercontent.com/45280919/101420786-e4cec600-392d-11eb-9965-ed7324c658ee.jpg)

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081753](https://user-images.githubusercontent.com/45280919/101420786-e4cec600-392d-11eb-9965-ed7324c658ee.jpg)

**Comment by itcannotbe** [comment]
![Screenshot_20201208_081753](https://user-images.githubusercontent.com/45280919/101420786-e4cec600-392d-11eb-9965-ed7324c658ee.jpg)

**Comment by TNT331** [comment]
how about research centers loljust saying

**Comment by TNT331** [comment]
even though he said that, he added unit ungrades and core upgrades XD

**Comment by TNT331** [comment]
who knows humans change

**Comment by itcannotbe** [comment]
> how about research centers loljust saying

No he didn't. He added just added replacing your core with a bigger one. which was already in the game since v4.

Also those are not unit upgrades, since each unit is not a direct.upgrade from what it was built from.

**Comment by nichrosia** [comment]
> upgrade turrets/**units** in terms of damage, weapons, health, and speed

I seem to remember something called a Reconstructor

**Comment by DeltaNedas** [comment]
please close this

**Comment by TNT331** [comment]
i never said it should be magical...
I never give a specific suggestion, I only give ideas which he can build on. but tech though, you need to get to the next tier to unlock more building. like tier 2 for
