### ISSUE TITLE
Visual alert when trying to upgrade a drone to an unresearched tier

### ISSUE THREAD

**Issue by SmolBig** [Anuken/Mindustry-Suggestions#1491]
**Describe the content or mechanics you are proposing.**

If a drone follows a conveyor or etc. to the entrance of a reconstructor, but can't be processed because the next tier is not researched, then the reconstructor should show a small "research required" icon, or perhaps the tech tree icon in a red triangle.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Upon unlocking the multiplicative reconstructor, I spent the better part of an hour trying to get my T2 drones to enter it from the assembly line. It wasn't until I finally gave up and went to see what else was unlocked in the tech tree that I saw what the issue was.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
good

**Comment by firstcreator48** [comment]
it as to be a research required message

**Comment by Kyllingene** [comment]
agree
