### ISSUE TITLE
More tools for Map editor.

### ISSUE THREAD

**Issue by Nekuna** [Anuken/Mindustry-Suggestions#1492]
The map editor is lacking certain tools that causes map making/editing to be less convenient and more tedious. 

Tools such as a copy and paste feature (much like the one in the campaign) would be very helpful when making patterns or adding specific details to a map. Another feature would be a function to change the geometry of the drawing tool from a circle to other shapes such as triangles, hexagons, and ovals. Additionally the spray-paint tool needs a slider to control the amount of tiles being applied each time the tool is utilized. 
There should more options for foliage and greenery, as well as other brighter colors in general to allow for more variety in and aesthetic options. Some examples of this would be: Flowers, green trees (similar to the white trees), sprouting grass, algae water, and so on.
Finally, a tutorial or help menu would be really great for allowing map makers to have a better grasp on what every option and feature does, and how they can effectively utilize it.

By adding the mentioned features to the map editor, maps will have more options to fit the creators desired aesthetic. It would allow new players to have an easier time learning how to create a map, and it would open up a whole new realm of player created content for the community to enjoy as a whole.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[You didn't even tried] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Also for a wasteland type of game I think the lack of vegatation is on point TBH.

**Comment by itcannotbe** [comment]
Tools such as a copy and paste feature (much like the one in the campaign) would be very helpful when making patterns or adding specific details to a map.
Duplicate of #259

**Comment by TNT331** [comment]
I like this, as a map maker I know the pain to do things like this manual. Adding line tool for eraser would be real useful. Copy and past is too useful if it is ever added

**Comment by RedstonerKBC** [comment]
I was just about to suggest this. I'm making maps but they take days just to design because the floor is so tedious to hand-paint.

**Comment by AntiDrag0n** [comment]
Sorry for Deleting Templates. It was an accident.
