### ISSUE TITLE
h

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#1493]
**Describe the content or mechanics you are proposing.**
Add a hint about unit limit

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
So people won't ask why their units stuck

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

 - [X] Box

**Comment by itcannotbe** [comment]
My factory is stuck at 8/8, it can't produce more units. Why? Anuke please help. This is bug. Game broken.

**Comment by TNT331** [comment]
@itcannotbe Don't be mean tell him why not

**Comment by XxsuperdeadlysniperxX** [comment]
Some constructive criticism helps ya know

**Comment by Kyllingene** [comment]
1: Please rename to something useful.

2: This is a legitimate suggestion, to help with those people who don't bother to try to fix the problem before complaining about it.

**Comment by XxsuperdeadlysniperxX** [comment]
>1: Please rename to something useful.
This helps anuke
@D-player1
