### ISSUE TITLE
Add Survival Mode 

### ISSUE THREAD

**Issue by zeaxgg** [Anuken/Mindustry-Suggestions#1494]
Survival mode like the old mindustry 

The survival mode has infinite wave

if you died and have items it will save

the reason why im suggesting this is the waves are so short that i can complete under hours
so i want survival mode

**Comment by DeltaNedas** [comment]
ok if you captured an entire planet in a few hours:
- play
- custom game
- map here
- survival

**Comment by Bohaska** [comment]
In case you want some good maps.
[Campaign Maps!.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5659667/Campaign.Maps.zip)

**Comment by TNT331** [comment]
@zeaxgg ask people who make maps for maps.
U can contact me though discord. I make challenging maps
