### ISSUE TITLE
Enemy drop point should be shown on map

### ISSUE THREAD

**Issue by sudobeans** [Anuken/Mindustry-Suggestions#1495]
I think the drop point (the zone that the enemies drop in) should be displayed on the map when you open it with "M." This would be a good quality-of-life feature. When I first drop on to the map, I often spend a bunch of time looking for the enemy drop point instead of spending time building production lines and defences. Maybe it could just be a dotted-line circle in the enemy's color, like it is when you fly next to it.

I was sure I had seen someone suggest this before, but I couldn't find this in the issues section or Trello, so I decided to.
Thanks for reading.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ah yes. Make spawn camping easier than it needs to be.

NOPE.

**Comment by TNT331** [comment]
This is true, we need this. As a map maker I know in V5, spawn point is shown as a dark Red colour. However now, it does not show where EXACTLY the spawn point is

**Comment by sudobeans** [comment]
> Ah yes. Make spawn camping easier than it needs to be.
> 
> NOPE.

Mindustry is a tower defense game, silly. There is nothing wrong with spawn camping! Besides, the inability to see the drop point on the map hasn't stopped anyone from spawn camping.

**Comment by SupremeTurtle** [comment]
Anuke will very likely not accept this suggestion, as Anuke said that he wants you to explore the map looking for the drop point.

**Comment by itcannotbe** [comment]
I do remember him saying that, I just can't remember where.

**Comment by sudobeans** [comment]
> Anuke will very likely not accept this suggestion, as Anuke said that he wants you to explore the map looking for the drop point.

I suppose that's a pretty good reason to not show the drop point. I'll take y'alls word for it that Anuke has said he won't do this, and close the thread. Thanks for letting me know.

**Comment by Kyllingene** [comment]
>Why is this a problem? Exploring the map and finding out where everything is part of the challenge. You have to know the terrain a little before placing down turrets.
-Anuke, #312
