### ISSUE TITLE
Make mining units (or any units) mining and in range of the core opaque 

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1496]
**Describe the content or mechanics you are proposing.**

This happens all the time where a stack of poly's mine in one spot obstructing the view I have on the place I want to do something with. This especially shows on mobile and is quite infuriating. This obviously happens close to the core because mining units mine as close to the core as possible (as they should).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will let me be able to see what I'm doing around my core which basically means less frustration. If not become opaque in range, make them opaque using a setting of some sort which will also effectively sort out this problem. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sudobeans** [comment]
Units are already opaque, so I'm assuming you mean that you wanted units to be transparent. [(Opaque definition](https://www.merriam-webster.com/dictionary/opaque)) Otherwise, I think this is a pretty good idea. Maybe it would be nice to have a checkbox/slider in the settings.

**Comment by the-kido** [comment]
> Units are already opaque, so I'm assuming you mean that you wanted units to be transparent. ([Opaque definition](https://www.merriam-webster.com/dictionary/opaque)) Otherwise, I think this is a pretty good idea. Maybe it would be nice to have a checkbox/slider in the settings.

Yeah by opaque I mean transparent. Also thanks for 1 upping the suggestion

**Comment by the-kido** [comment]
anuke no like idea i close 😢
