### ISSUE TITLE
Buildings disabled by logic should be visually obvious and some other things related.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#1498]
**Describe the content or mechanics you are proposing.**
Make building be visually obvious when disabled by logic and indicate the processor's coordinates that disabled it in the window on the lower right.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
QOL and Anti-Grief.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
The code will mostly be some variant of if building is disabled, add this fancy image filter/load different pic. The show coordinate code will be something like if building disabled grab coordinates of the processor responsible and put the coordinate into text.

**Comment by Legomonster33** [comment]
purple diamond for when block statuses are enabled (f6) would likely be cool

**Comment by itcannotbe** [comment]
> purple diamond for when block statuses are enabled (f6) would likely be cool

Why a diamond why not a straight up X?

**Comment by TNT331** [comment]
yeah toggleable would be nice, also ♢ 🗡️

**Comment by Legomonster33** [comment]
> > purple diamond for when block statuses are enabled (f6) would likely be cool
> 
> Why a diamond why not a straight up X?

because the f6 block status toggle uses coloured diamonds

**Comment by itcannotbe** [comment]
> > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > 
> > 
> > Why a diamond why not a straight up X?
> 
> because the f6 block status toggle uses coloured diamonds

I thought the diamonds are just sprites not rectangles rotated and filled with color?

**Comment by Legomonster33** [comment]
> > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > 
> > > 
> > > Why a diamond why not a straight up X?
> > 
> > 
> > because the f6 block status toggle uses coloured diamonds
> 
> I thought the diamonds are just sprites not rectangles rotated and filled with color?

so the sprite would be purple???

**Comment by itcannotbe** [comment]
> > > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > > 
> > > > 
> > > > Why a diamond why not a straight up X?
> > > 
> > > 
> > > because the f6 block status toggle uses coloured diamonds
> > 
> > 
> > I thought the diamonds are just sprites not rectangles rotated and filled with color?
> 
> so the sprite would be purple???

Why purple of all the colors that the indicator is not using currently?

**Comment by TNT331** [comment]
cus ANUKEN SAID SO

**Comment by Legomonster33** [comment]
> > > > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > > > 
> > > > > 
> > > > > Why a diamond why not a straight up X?
> > > > 
> > > > 
> > > > because the f6 block status toggle uses coloured diamonds
> > > 
> > > 
> > > I thought the diamonds are just sprites not rectangles rotated and filled with color?
> > 
> > 
> > so the sprite would be purple???
> 
> Why purple of all the colors that the indicator is not using currently?

because the rest of logic blocks are purple. so having it be purple would let people know that its not working because of logic.

**Comment by itcannotbe** [comment]
> > > > > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > > > > 
> > > > > > 
> > > > > > Why a diamond why not a straight up X?
> > > > > 
> > > > > 
> > > > > because the f6 block status toggle uses coloured diamonds
> > > > 
> > > > 
> > > > I thought the diamonds are just sprites not rectangles rotated and filled with color?
> > > 
> > > 
> > > so the sprite would be purple???
> > 
> > 
> > Why purple of all the colors that the indicator is not using currently?
> 
> because the rest of logic blocks are purple. so having it be purple would let people know that its not working because of logic.

Wait do people actually know what the color even mean?

**Comment by Legomonster33** [comment]
> > > > > > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > > > > > 
> > > > > > > 
> > > > > > > Why a diamond why not a straight up X?
> > > > > > 
> > > > > > 
> > > > > > because the f6 block status toggle uses coloured diamonds
> > > > > 
> > > > > 
> > > > > I thought the diamonds are just sprites not rectangles rotated and filled with color?
> > > > 
> > > > 
> > > > so the sprite would be purple???
> > > 
> > > 
> > > Why purple of all the colors that the indicator is not using currently?
> > 
> > 
> > because the rest of logic blocks are purple. so having it be purple would let people know that its not working because of logic.
> 
> Wait do people actually know what the color even mean?

red = unable to function (no power etc.)
green = working good
orange = unable to work but has the resources to (clog etc.)

**Comment by itcannotbe** [comment]
> > > > > > > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Why a diamond why not a straight up X?
> > > > > > > 
> > > > > > > 
> > > > > > > because the f6 block status toggle uses coloured diamonds
> > > > > > 
> > > > > > 
> > > > > > I thought the diamonds are just sprites not rectangles rotated and filled with color?
> > > > > 
> > > > > 
> > > > > so the sprite would be purple???
> > > > 
> > > > 
> > > > Why purple of all the colors that the indicator is not using currently?
> > > 
> > > 
> > > because the rest of logic blocks are purple. so having it be purple would let people know that its not working because of logic.
> > 
> > 
> > Wait do people actually know what the color even mean?
> 
> red = unable to function (no power etc.)
> green = working good
> orange = unable to work but has the resources to (clog etc.)

I mean there is no mention of it in-game and we're throwing in another color.

**Comment by Legomonster33** [comment]
> > > > > > > > > > purple diamond for when block statuses are enabled (f6) would likely be cool
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Why a diamond why not a straight up X?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > because the f6 block status toggle uses coloured diamonds
> > > > > > > 
> > > > > > > 
> > > > > > > I thought the diamonds are just sprites not rectangles rotated and filled with color?
> > > > > > 
> > > > > > 
> > > > > > so the sprite would be purple???
> > > > > 
> > > > > 
> > > > > Why purple of all the colors that the indicator is not using currently?
> > > > 
> > > > 
> > > > because the rest of logic blocks are purple. so having it be purple would let people know that its not working because of logic.
> > > 
> > > 
> > > Wait do people actually know what the color even mean?
> > 
> > 
> > red = unable to function (no power etc.)
> > green = working good
> > orange = unable to work but has the resources to (clog etc.)
> 
> I mean there is no mention of it in-game and we're throwing in another color.

ok, but adding a colour doesn't really change or have much to do with the meaning of the other ones. its more of a debug feature anyway?

**Comment by DeltaNedas** [comment]
currently, any disabled block has a red x when hovered
logic-disabled blocks should have a constantly visible red or purple x

**Comment by Bohaska** [comment]
The code will mostly be some variant of if building is disabled, add this fancy image filter/load different pic. The show coordinate code will be something like if building disabled grab coordinates of the processor responsible and put the coordinate into text.

**Comment by RogueRedHawk** [comment]
I like the purple diamond indicator. It seems very intuitive for me and I caught on right away. There is already an indicator for when a block has been disabled by logic, so with the purple diamond plus the disable indicator, that covers all the information that was requested in this suggestion.

**Comment by scarf-generic** [comment]
> Why a diamond why not a straight up X?

straight up X already exists, hover over it and you will see it.

**Comment by itcannotbe** [comment]
> > Why a diamond why not a straight up X?
> 
> straight up X already exists, hover over it and you will see it.

Visually obvious means you can notice it by just glancing at it.

**Comment by sample-text-here** [comment]
I think it's visually obvious when some blocks aren't working. Then you can hover over it and see it was disabled by logic or not.

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
