### ISSUE TITLE
Shield/Health Improvements

### ISSUE THREAD

**Issue by TNT331** [Anuken/Mindustry-Suggestions#1499]
**Describe the content or mechanics you are proposing.**
Energy shields (yellow, extra health) Should be rechargeable by the unit repair point INSTEAD of the unit repair point healing the unit's health. The shield should have around equal amount of health as the unit health. The shield will have a health bar which is like energy bar. Once the energy runs out the shields will shut down(force shields will constantly draw power WHICH SHOULD BE MADE TOGGABLE) and the "yellow" shield that is around the unit will use the batterie when attacked/hit.

This means increasing unit health overall but the "health" of the unit will not be regenable, only the shield is rechargeable.

(Minor/optional) I recommend force shields will be turned off as default to not draw power from batteries and will turn on when the unit is attacked or manually activated.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The more logical way is for shields to be recharged like energy based weapons tbh.

**Comment by the-kido** [comment]
Just saying, shields can easily be togglable using logic.

**Comment by TNT331** [comment]
@itcannotbe what u mean
?
