### ISSUE TITLE
unofficial servers notice

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#15]
**Describe the content or mechanics you are proposing.**
add a notice when first clicking Join tab that all servers, par official hexed/be, are unofficial, go to their owners for support

"These servers are unofficial and not affiliated with Mindustry, [red]ask their owners for help with them[]"

Additionally, id like for default servers and official servers to be separated. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

reduce load on mindustry help channel, most of these servers show a discord server invite

there are 3 hexed servers on default list atm, they should be separated between official and unofficial

also just a version property for servers would be nice so you can specify only custom builds, only BE > 6000, etc. or it wont show up like be_servers.json

**Before making this issue, replace the underscores in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. [X] yes
2. [X] see #help "how do i get verified for vpn" every 5 minutes

**Comment by mRebornM** [comment]
How do i upvote this

**Comment by Bohaska** [comment]
anuke never reads stuff with the wrong type of checkmarks.

**Comment by itcannotbe** [comment]
This is a relatively old issue.

**Comment by DeltaNedas** [comment]
yes

**Comment by DeltaNedas** [comment]
implemented
