### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by TNT331** [Anuken/Mindustry-Suggestions#1500]
**Describe the content or mechanics you are proposing.**
Land mines and maybe some new units can be hidden and can be only targeted/spoted whrn you get an certain type of unit.

THIS IS JUST AN IDEA, I DO NOT STRONGLY SUPPORT THIS IDEA BUT IT IS MINE.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
this is not a new concept, it has been suggested before

**Comment by Kyllingene** [comment]
If you would like to suggest something, you should probably brainstorm it a little. I don't know how I feel about this idea right now, because there is so little info. Next time, maybe try making some ideas as to how it could work.
