### ISSUE TITLE
Show logic processor block coordinates when unit is controlled by it.

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry-Suggestions#1501]
**Describe the content or mechanics you are proposing.**
Show logic processor block coordinates when unit is controlled by it.
Basically that would be under "Processor controlled"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Because of addition of "last ascend" which made catching griefs easier but they can use logic to make units go bye bye from defense line and go in random way or make them build stuff like conveyors, routers everywhere. Sometimes highlighting logic block don't works because space my be too crowded or processor is far. Or both. Basically to make life better.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Nikolass1000** [comment]
Yes, arrows showing where processor is are useless

**Comment by itcannotbe** [comment]
This is a UI nightmare TBH.
