### ISSUE TITLE
Decrease Campaign Tech Blocks

### ISSUE THREAD

**Issue by NateSav** [Anuken/Mindustry-Suggestions#1502]
**Describe what you would like changed, and why.**
After playing lots of 5.0 Mindustry campaign I am very impressed with new features.  However, the map clearing tech locks are frustrating enough in early game that I have done some crazy digging to redownload an old version.  Specifically around the craters level where there is scrap, sand, and lead but I cannot research a kiln or refine slag (therefore no pumps, spores, plastanium...) 

**Describe the changes you want to propose. Include possible alternatives.**
Keep the resource locks that make it impossible to progress too far too fast, but eliminate map clearing locks (or loosen them) so that craters (and even early replays of ground zero) can be fun and challenging rather than a slog.

**Comment by NateSav** [comment]
Side comment I love Mindustry and have paid for it, but that alone took crazy digging.  A donate button inside the app would have made it much easier to pay you for your work (unless google takes a massive percentage).

**Comment by HaphLife** [comment]
I think that the sector capture unlocks are a good thing. They teach people to interact with the maps, and not just bang their heads against the auto-generated sectors.

**Comment by NateSav** [comment]
I suppose people could just grind in the auto generated sectors, so you are not wrong. I had a bit of the opposite reaction though, there is almost nothing to interact with on the first three levels without the tech to prices scrap, sand, or metaglass so I just blew through them without enjoying it focusing on them. In 5.0 I had every scrap of the craters developed since there is so little space. It was a fun challenge rather than sorry a place to pass through.

**Comment by Kyllingene** [comment]
> Side comment I love Mindustry and have paid for it, but that alone took crazy digging. A donate button inside the app would have made it much easier to pay you for your work (unless google takes a massive percentage).

I'm assuming Steam wasn't an option. It's $5 on there, and has a few nice features (multiplayer and achievements only, obviously). I agree though, having to go so slowly can be quite frustrating, although there is probably a reason for it.

**Comment by XxsuperdeadlysniperxX** [comment]
2 months later....
