### ISSUE TITLE
Show armor in unit/block descriptions

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1504]
**Describe the content or mechanics you are proposing.**
title.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
so that we can actually see unit or block armor.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I am too tired to quickly search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I haven't checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I haven't read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category, but why would it be?

**Comment by itcannotbe** [comment]
I will rate your checkbox usage 1 out of 4.

**Comment by sudobeans** [comment]
I didn't know that there was a such thing as armor in this game. If it exists, maybe it should be shown in unit/block descriptions.

**Comment by BlueWolf3682** [comment]
> I will rate your checkbox usage 1 out of 4.

i can be lazy too :p
