### ISSUE TITLE
Logic Speakers (Yes, people suggested this too.)

### ISSUE THREAD

**Issue by Orange-Leaf-36** [Anuken/Mindustry-Suggestions#1505]
**Describe the content or mechanics you are proposing.**

A block that plays sounds and can be used to compose music

### Command in the processor:
```
Sound Wave (blockID) (waveform) (pitch) (duration) (For 8-Bit/NES-like sounds)
Sound Play (blockID) (soundID/sound name) (duration(optional))
Sound Stop (Stops the sound before the sound itself stops)
Sound Volume (volume) (Adjusts volume)
Sound Mute (Mutes sound, Can be unmuted using Sound Volume (something higher than 0))
```

### Examples:
```
1 Sensor power = powerNetStored in battery1 (Detects energy in battery)
2 Jump if power <= 0 >> line 4 (If battery energy is lower or equal to 0, go to line 4)
3 End
4 Sound Play speaker1 Explosion (can be changed to something else) 
```

Either there will be a "Soundboard" for these speakers or you have to use a processor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Some logic games need sound or it can be an indicator for something like low power, defense breach, coal in the core, and etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

(**Yes, I know people suggested this already, This is already planned as seen from Trello, I saw other suggestions asking for the same thing.**)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. [You haven't] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

2. [You also didn't] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version..

**Comment by itcannotbe** [comment]
Before making this issue, Author placed an X in the boxes below to confirm that you have acknowledged them, but didn't actually do them.

**Comment by Orange-Leaf-36** [comment]
> 1. [You haven't] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. 2. [You also didn't] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version..

I saw the Trello that they were already planning but forgot to put a note that I did.
I also looked if there were similar suggestions to this one, yet again forgot to put them.

**Comment by DeltaNedas** [comment]
1. ok close this
2. deltanedas/anuke-logic

**Comment by matkoniecz** [comment]
> I saw the Trello that they were already planning

So why you decided to ignore request by Mindustry author and spammed pointless issue here?

**Comment by sample-text-here** [comment]
> (Yes, people suggested this too.)

if you know other people suggested it already why did you open another issue

**Comment by Orange-Leaf-36** [comment]
Issue Closed. Happy? (not mad lol)

**Comment by Orange-Leaf-36** [comment]
> 1. ok close this
> 2. deltanedas/anuke-logic

Issue Closed

**Comment by XxsuperdeadlysniperxX** [comment]
@itcannotbe what is logic sound is like logic based music i saw it on trello

**Comment by Kyllingene** [comment]
> what is logic sound is like logic based music i saw it on trello

Basically, you make music through either a new block or a processor, using logic.

Also, I know this is closed, but why would you make it if, from the start, you knew it was a duplicate?

**Comment by XxsuperdeadlysniperxX** [comment]
If yall wondering why i ask what is logic sounds heres the trello link

https://trello.com/b/aE2tcUwF/mindustry-trello

I understand this is closed but thats why this an opportunity
