### ISSUE TITLE
Ability to disable borders on a display

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1508]
**Describe the content or mechanics you are proposing.**
The ability to toggle whether a display has borders (by a button? could also make them really thin instead).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
A way to make certain logic look better.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This would be nice, but the fact that this just worsen shit on servers that doesn't have display blocks banned cannot be ignored.

**Comment by joshuaptfan** [comment]
Probably a thing best left to mods.

**Comment by Kyllingene** [comment]
@itcannotbe, what do you mean? I cannot imagine how a lack of borders would make things much worse on servers, while it would be super nice for making any sort of display larger than 176x176 (which is often necessary).

**Comment by erSlippers** [comment]
@Kyllingene I think it might be because people go "oh we can draw anything, huh?" and abuse that power. Now imagine they can do that with a 24x24 tile array of screens. Oh dear.

**Comment by Kyllingene** [comment]
Fair, fair. Maybe two new blocks (I realize how annoying this could be) that are mirrors (same cost, same size, same function) as the current display blocks, except they don't have borders. Then, you could simply ban that block on a server, while keeping the normal displays.
