### ISSUE TITLE
Address spawn camping inside the dropzone.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#1509]
**Describe what you would like changed, and why.**
Charged batteries placed inside the drop zone can actually insta kill the wave that spawns on spawn.

**Describe the changes you want to propose. Include possible alternatives.**
Alternative 1: Make dropzones produce damage every tick.

Alternative 2: Prevent building inside the dropzone

**Comment by matkoniecz** [comment]
>  Charged batteries placed inside the drop zone can actually insta kill the wave that spawns on spawn.

Why it is a problem? This is pretty cool.

**Comment by itcannotbe** [comment]
> > Charged batteries placed inside the drop zone can actually insta kill the wave that spawns on spawn.
> 
> Why it is a problem? This is pretty cool.

Makes the game too easy.

**Comment by the-kido** [comment]
I didn't even know this happened and really this is a high priority to fix as this is much too OP. 1+ ing this.

**Comment by RogueRedHawk** [comment]
>Make dropzones produce damage every tick.

This is a good solution, but it also doesn't prevent placing the batteries right before the wave comes (easily doable with a few polys helping out).

**Comment by XEN0PHIL** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/949
Anuke doesn't seem to check suggestions *too often*

**Comment by itcannotbe** [comment]
Welp. Duplicate I guess. #949 
@XEN0PHIL You should really change the title of that one.
