### ISSUE TITLE
Multiplayer Campaign Hosting

### ISSUE THREAD

**Issue by Earthy1231** [Anuken/Mindustry-Suggestions#1510]
**Describe the content or mechanics you are proposing.**
Anybody who joins a server/lan server will autojoin the host if they move to a different sector

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will just save people time

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
**Some has kinda suggested this, but it would work for the entire planet. https://github.com/Anuken/Mindustry-Suggestions/issues/916#issue-728917691**
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RogueRedHawk** [comment]
This has already been implemented.
