### ISSUE TITLE
Tetrative Reconstructor sprite symmetry

### ISSUE THREAD

**Issue by TrippleTrip** [Anuken/Mindustry-Suggestions#1513]
**Clean up of the Tetrative Reconstructor sprite.**

**Old:**
![tetrative-reconstructor](https://user-images.githubusercontent.com/60444925/101680369-9e14c500-3a2e-11eb-9261-8933cf1391c5.png)
I noticed some small offsets and symmetry issues in the Tetrative Reconstructor sprite. I couldn't help myself and cleaned up the sprite. I saw this while using the vanilla sprites for basing my mod sprites off of. 

**Here is the cleaned up version:**
fixed my own mistake, sorry.
![tetrative-reconstructor cleanup](https://user-images.githubusercontent.com/60444925/101957761-0b139080-3bd0-11eb-89b9-7d3abd21562e.png)

**Comment by BlueWolf3682** [comment]
*looks at both*
*sees no difference*
***[visible confusion]***

**Comment by GreyMario** [comment]
So you...

Removed the top and bottom middle markings?

Really? That just makes it worse.

**Comment by BlueWolf3682** [comment]
***OH***

**Comment by GreyMario** [comment]
Oh, and the gaps between the round things and the overhanging lip on the left side of the original graphic are slightly the wrong size.

So you fixed one small problem and ended up creating a bigger one.

**Comment by rodrigolitzius** [comment]
*?*

**Comment by XxsuperdeadlysniperxX** [comment]
> *looks at both*
> *sees no difference*
> ***[visible confusion]***

I agree with this..........where is the offsets tho?

**Comment by XxsuperdeadlysniperxX** [comment]
oH

**Comment by XxsuperdeadlysniperxX** [comment]
They still look the same **visible confusion**

**Comment by rodrigolitzius** [comment]
It looks more the same then before...

**Comment by Kyllingene** [comment]
A PR may be in order.
