### ISSUE TITLE
Data sync

### ISSUE THREAD

**Issue by tester1200** [Anuken/Mindustry-Suggestions#1514]
**Describe the content or mechanics you are proposing.**
Can you add a fata sync between a phone and pc

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

You can play the game from different devices 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
Anuke has said he will not add cloud/sync

**Comment by Quick-korkc** [comment]
Also you can just export your data, then import to another

**Comment by sample-text-here** [comment]
![image](https://user-images.githubusercontent.com/56274831/101697287-6b69cd00-3a2c-11eb-85a1-ad264d6eba14.png)

![image](https://user-images.githubusercontent.com/56274831/101697236-512fef00-3a2c-11eb-8bac-5f867b73b683.png)

Fun fact: you're supposed to do the things in the checkbox before you check them

**Comment by tester1200** [comment]
Im dumb

**Comment by DeltaNedas** [comment]
`man git`

[mindustry.txt](https://github.com/Anuken/Mindustry-Suggestions/files/5671020/mindustry.txt)
