### ISSUE TITLE
Plastanium Bridges

### ISSUE THREAD

**Issue by Xentha** [Anuken/Mindustry-Suggestions#1515]
**What?**
The means to sort and split plastanium belts cleanly exist, but there is no clean way to cross belts or other obstacles. So, I'd like to propose plastanium bridges, which only accept input from and output to, plastanium belts.

**Why?**
Junctions work decently, but lack the full throughput of a plastanium belt, causing stuttering if full capacity is achieved, requiring needlessly inefficient methods to work around it. Bridges on the other hand, simply do not have the throughput to cater to plastanium belts without even more awkward methods, making them out of the question for certain setups. Furthermore, _phase bridges have a nasty issue where inputting a second packet before the first fully transfers, causes resources to become jumbled_ up, requiring sorters to be used to remedy it.

A bridge type that only accepts and outputs plastanium packets would solve these issues, though it would be desirable for it to be at least a little longer range than regular bridges, to reflect its advanced tech level. Perhaps 7 instead of 5 blocks, so as to not completely depreciate phase bridges.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

found #629 by searching the exact phrase "plastanium bridges" and also found [why they probably won't be added](https://github.com/Anuken/Mindustry-Suggestions/issues/629#issuecomment-699777511)

for now just use this
![image](https://user-images.githubusercontent.com/56274831/101707383-f607f780-3a3f-11eb-9bf2-df96b3f3c824.png)

**Comment by scarf-generic** [comment]
> > I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> found #629 by searching the exact phrase "plastanium bridges" and...

this comment is what i was going to comment but better. anyway, should probably close this issue.

**Comment by Xentha** [comment]
> 
> 
> > I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> found #629 by searching the exact phrase "plastanium bridges" and 

I did make the effort to search, but I am fallible, as is anyone else. Whether by incorrect terms, or lack of familiarity with github's search system, my searches failed to yield relevant results.

That out of the way.. I heavily disagree with the design ethic expressed by the block's designer, as it seems like an arbitrary limitation. But, it isn't my decision, and if that's how it has to be I wont fuss about it further. I already have my own solutions to the problem, I had simply hoped for something more streamlined.
