### ISSUE TITLE
Highways Between Sectors to move Resources

### ISSUE THREAD

**Issue by BlofeldReturns** [Anuken/Mindustry-Suggestions#1516]
**Describe the content or mechanics you are proposing.**
So, as we may know, certain sectors have certain resources, and others do not.
This means that if you have a base getting attacked next to Ground Zero, you might only have access to Silicon level stuff.
This is almost always outmatched by the enemies, which (I'm pretty sure) get stronger the more attacks you defeat.
I propose a special feature which will enable resource transfer between sectors.
Basically, in the planet map, you press a button called 'Highway'. You click on one sector, then drag a line to another sector to show which sector you want to link to.
This then creates a sector which you launch a core into. This sector will look mostly like a straight path from one end of the screen to the other. Your core lands on one end of this map. This is a special type of core which can only hold 1000 of every resource, and its only purpose is to construct a highway.
You do your normal Mindustry resource collection, but are not required to place any defenses, since no enemies will attack.
Once you have linked one end of the map to the other with conveyor belts, you can launch your core and the conveyor belts you placed will act as resource transport between sectors. On the planet map you will see a line linking these two sectors, as well as an arrow showing which direction the resources are moving in.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
For players who envision a vast empire with specific sectors performing specific tasks, such as resource/ energy storage or collection, unit depot, or otherwise, this will be a tool for customization of sectors in the early-mid through late game.
For people who don't care too much, they can just make a tiny highway with only one or two conveyors, it will take only a few minutes, and they will still get all the benefits of the feature.

- OPTIONAL BALANCING SUGGESTIONS -
Make it so that if you didn't add walls around your highway when building it, the elements will slowly eat away at the conveyor belts, slowing their speed and eventually destroying them. This will add some time to the construction, however.
Make it so that you have to build an entrance into the target sector, which will appear as a tunnel exit coming out of the map border's darkness. Physical conveyors will come out of it.
Make it so that you have a limited area (in terms of width) to build the highway in, and must pay some resources to unlock more space to fit in more conveyors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

- NOTE ON THIS FROM PERSON SUGGESTING THIS FEATURE -
I checked the Trello and there is a plan for resource transfer, but it only involves transport of resources by units, not conveyors as I suggest.
I realize the similarity in concept, but I believe my suggestion could be a little bit more engaging than just units ferrying resources.

3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Hope you take it into consideration ;)
-Jeb T. Firefly

**Comment by itcannotbe** [comment]
[That's a no for me] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Launchpads exist in the game to move resources in campaign to abother sector.

**Comment by scarf-generic** [comment]
launchpads exist. close this.

**Comment by GreyMario** [comment]
[ ] OP is familiar with all the content already in the game or has glanced at the wiki to make sure his/her suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
[X] op is egg

**Comment by BlofeldReturns** [comment]
OK, thanks!
