### ISSUE TITLE
Opposite of Launch Pad, Drop Pad

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry-Suggestions#152]
**Describe the content or mechanics you are proposing.**

An object that can pickup dropped stuff from the place where the cores launch to.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think this will be a great addition to the game, because sometimes you need a resource, but you don't have it in your core, and you can't normally get it on the map.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Have you heard of loadouts? They already exist in the game.

**Comment by nichrosia** [comment]
For mid-game, not the start

**Comment by itcannotbe** [comment]
So basically an op teleporter from classic?

**Comment by nichrosia** [comment]
I just realized what you mean. I retract my suggestion

**Comment by DeltaNedas** [comment]
close it

**Comment by kapzduke** [comment]
yes, that doesnt make sense, how would the pad collect materials from the mothership if it can only load materials into cores? (no irony intended)
