### ISSUE TITLE
Read/Write and attribute values

### ISSUE THREAD

**Issue by RethIit** [Anuken/Mindustry-Suggestions#1523]
**Describe the content or mechanics you are proposing.**
  The read / write commands currently do not accept anything other than number for the ``at ...`` part, including attribute values,
  meaning that you can't do something like this:

  ``  [Set num = 5]
  [Write 1 to cell1 at num]``

  Please make them be able to do so.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

   Them being able to use attributes and attribute values would drastically decrease the amount of commands needed to verify/
   change a value in a memory cell. This would speed up code using a multiservice for controlling units or a conveyor line and 
   make it easier to use in general.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
- [X] I am capable of filling all boxes, but not actually doing any things mentioned in them

**Comment by DeltaNedas** [comment]
yes they do who told you that
![Screenshot_19:39:52](https://user-images.githubusercontent.com/39013340/101821147-7a7d7780-3b1f-11eb-9844-de56460b60cb.png)
![Screenshot_19:40:11](https://user-images.githubusercontent.com/39013340/101821230-97b24600-3b1f-11eb-98e0-b2ae5c25d1e8.png)

**Comment by DeltaNedas** [comment]
@RethIit close this you rotten egg

**Comment by Kyllingene** [comment]
>  - [X] I am capable of filling all boxes, but not actually doing any things mentioned in them

 - [X] I am capable of accusing others of something, but not actually explaining what they did.

**Comment by Ruichka** [comment]
> > * [x]  I am capable of filling all boxes, but not actually doing any things mentioned in them
> 
> * [x]  I am capable of accusing others of something, but not actually explaining what they did.

I am being clear about what they did. They have checked all boxes, but didn't actually done anything what they (boxes) said.

**Comment by Kyllingene** [comment]
What I meant was that you never clarified what Trello plan, issue, "A few things you shouldn't suggest", and/or current game feature that they missed. Clearly, they cannot have missed both a Trello plan and README.md line, since then what would be the point of the "don't suggest" list? If you have evidence that they did not, in fact, do all 4 tasks, please provide it for everyone's benefit.
