### ISSUE TITLE
Make Mindustry for the 3DS

### ISSUE THREAD

**Issue by AquaStarOP** [Anuken/Mindustry-Suggestions#1525]
**Describe the content or mechanics you are proposing.**
Make Mindustry available on the 3DS store - be it free or for money.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The 3DS was recently put out of production, meaning they got cheaper - but a lot of people have DS's, and the portability of them, the multiple buttons, stylus, and dual screen is far better fit for mindustry gameplay than a phone.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
Making the game for consoles is an extension of "controller support", which is in the README.md as something that will _Never Happen._

**Comment by DeltaNedas** [comment]
thankfully nintendo released the source code of everything so it'll be possi- nope

**Comment by Anuken** [comment]
There are so many problems with publishing on the 3DS that I don't even know where to begin.
