### ISSUE TITLE
Launch timer

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1526]
Tells you when the next resource/planetary accelerator launch is and resets after the launch completes

Just tells the time until next launch like its that simple

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
Delta you toxic

**Comment by scarf-generic** [comment]
> Delta you toxic

what

**Comment by itcannotbe** [comment]
> > Delta you toxic
> 
> what

Same question.

**Comment by XxsuperdeadlysniperxX** [comment]
He knows he toxic

**Comment by XxsuperdeadlysniperxX** [comment]
That telling anuke its slow this just to add a timer

**Comment by XxsuperdeadlysniperxX** [comment]
To next launch

**Comment by sample-text-here** [comment]
> > > Delta you toxic
> > 
> > 
> > what
> 
> Same question.

^

**Comment by flarefluffsune** [comment]
It launches every minute. Or once full if a minute has elapsed. How hard is that for you to understand that?

**Comment by XxsuperdeadlysniperxX** [comment]
Its not

**Comment by XxsuperdeadlysniperxX** [comment]
Also a visual of when the launchpads will launch helps

**Comment by XxsuperdeadlysniperxX** [comment]
Also bringing more drama in to this gray mario isn't good and doesn't help the curremt topic

**Comment by flarefluffsune** [comment]
> Also a visual of when the launchpads will launch helps

There is one, its when the Item's bar reaches 100.

**Comment by XxsuperdeadlysniperxX** [comment]
Well thats inconvenient when you aim them at a sector under attack because you won't know when it launchs until it happens, which is also werid if you have a low resource rate entering the launchpads cuz then it won't launch until it is full.

**Comment by XxsuperdeadlysniperxX** [comment]
I did close the issue tho

**Comment by notrealn** [comment]
[this trick](https://vimeo.com/user125812762/review/491407149/0125548e78) might help you.

**Comment by XxsuperdeadlysniperxX** [comment]
Thanks for the link and a possibly saving me a headache in the future

**Comment by XxsuperdeadlysniperxX** [comment]
@notrealn the link says the page couldn't be found

**Comment by notrealn** [comment]
works on my machine

**Comment by XxsuperdeadlysniperxX** [comment]
Idk why its not even appearing for me

**Comment by XxsuperdeadlysniperxX** [comment]
Is the video one you made? @notrealn

**Comment by notrealn** [comment]
https://streamable.com/bvek7y
try this one

**Comment by XxsuperdeadlysniperxX** [comment]
The new link to streamable did work however due to internet issues i'll have to watch it later
