### ISSUE TITLE
payload transfering

### ISSUE THREAD

**Issue by SomeRandoGithubber** [Anuken/Mindustry-Suggestions#1528]
a way to transfer large amounts of resources like a middle ground to the mass diver and using logic to control bots to drop stuff off

**Comment by itcannotbe** [comment]
Dials 911:
I would like to report someone killed the template again.

**Comment by GreyMario** [comment]
Would you mind completing the campaign through Tar Fields for us, then finish all item transport related researches before coming back to this issue? What you're asking for already exists.

**Comment by scarf-generic** [comment]
dispite OP's best efforts, i have managed to partially understand what this issue is about. they want units to be able to deliver items to mass drivers, i think.

**Comment by itcannotbe** [comment]
He wants a in between method of transfering resources that can do more than a mass driver but less that what can unit logistics can do.

**Comment by GreyMario** [comment]
Oh.

Well.

I'm glad SOMEBODY here understands American.
