### ISSUE TITLE
iPad Keyboard & Mouse controls

### ISSUE THREAD

**Issue by isametry** [Anuken/Mindustry-Suggestions#153]
iPadOS 13.4 adds full mouse & keyboard support to iPads, and since the "mouse and keyboard" section was never gone from the iOS version of Mindustry, could iPad users have the option to use their keyboards and mice to play? 

Here is Apple's documentation on [Mouse Input](https://developer.apple.com/documentation/uikit/pointer_interactions) and [Keyboard Input](https://developer.apple.com/documentation/uikit/keyboards_and_input) in iPadOS. It currently doesn’t support relative cursor coords and fixed cursor, but to my knowledge that shouldn’t be a problem because Mindustry doesn’t use these control mechanics.

Thank you!

   1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by bruno-robert** [comment]
I tried out the mouse and keyboard option on iPad and it doesn’t seem to be working, even though the option is still in the menu.
Is this just a bug or is it just an side effect from the pc or android version?

I’m using an iPad pro running iOS 14.6

**Comment by itcannotbe** [comment]
Try actually making a bug report @bruno-robert
