### ISSUE TITLE
Error in editor

### ISSUE THREAD

**Issue by lu-meiagui** [Anuken/Mindustry-Suggestions#1530]
**Describe what you would like changed, and why.**
The editor 

**Describe the changes you want to propose. Include possible alternatives.**
I was in the editor when this error appeared, it cannot be removed with the eraser and it cannot be ground
![Screenshot_2020-12-11-04-01-12](https://user-images.githubusercontent.com/74993826/101874712-2c409680-3b68-11eb-980d-2067ffadaab6.png)
![Screenshot_2020-12-11-04-02-05](https://user-images.githubusercontent.com/74993826/101874730-32cf0e00-3b68-11eb-9d2c-64b41c57cc5b.png)
![Screenshot_2020-12-11-04-02-16](https://user-images.githubusercontent.com/74993826/101874741-3793c200-3b68-11eb-9b3d-84a8e1dc8dc8.png)
![Screenshot_2020-12-11-04-03-07](https://user-images.githubusercontent.com/74993826/101874756-3bbfdf80-3b68-11eb-81e2-52cbcea4c4db.png)

**Comment by lu-meiagui** [comment]
I happened in version 120.2 in android I don't know if it happened in pc

**Comment by GreyMario** [comment]
Three step process:

One: post this in the correct issue tracker (you have _suggestions_)
Two: prove to yourself that saving and reloading the map doesn't fix it
Three: submit the map file so someone can discover what the offending issue actually is
