### ISSUE TITLE
Bring back the Block Select Timeout setting

### ISSUE THREAD

**Issue by AbbyNode** [Anuken/Mindustry-Suggestions#1532]
**Describe what you would like changed, and why.**
In v5, there was a slider in Settings to adjust the Block Select Timeout.
![Block Select Timeout](https://i.imgur.com/TO71k6K.png)
This setting [was removed](https://github.com/Anuken/Mindustry/commit/455e3188c492a85c8839c1115625e98aba8c9824) in v6. I'm having trouble adjusting to the delay. I keep accidentally selecting blocks when I want to change to another category.

**Describe the changes you want to propose. Include possible alternatives.**
Please bring back this setting, even if it's in an "Advanced Settings" section. :)

**Comment by DeltaNedas** [comment]
good

**Comment by DeltaNedas** [comment]
https://github.com/Anuken/Mindustry/pull/3939
