### ISSUE TITLE
Remove graphite from ripple ammo list

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1533]
**Describe what you would like changed, and why.**
We already have 5 types of ammo for ripples and... guess which one is overused. It makes sense that hail is low-tier artillery with low-tier ammo, and ripple is mid-tier artillery with mid-tier ammo. And graphite is low-tier ammo. It takes no effort.

**Describe the changes you want to propose. Include possible alternatives.**
So what I want is to encourage players to use different ammo types. Also hail is kinda abandoned and misused, most people prefer ripples over them. This is also the point.

**Comment by AnOreo1** [comment]
graphite is used in spectre and thats not an issue to you?

**Comment by AnOreo1** [comment]
and what about salvo?

**Comment by Slava0135** [comment]
> graphite is used in spectre and thats not an issue to you?

this is also an issue for me...

**Comment by Slava0135** [comment]
how often do you see people feeding turrets with silicon? Imo it should be used as basic ammo for higher tiers turret

**Comment by the-kido** [comment]
> how often do you see people feeding turrets with silicon? Imo it should be used as basic ammo for higher tiers turret

1. Silicon is precious especially early-game and in v6. If graphite isn't an option people will still not use silicon.
2. Why do you think it should be used as basic ammo?

**Comment by Slava0135** [comment]
What makes graphite special - it is being produced using a single resource and other ammo are harder to make. You have to do some logistics and stuff, not just build some presses nearby the ore patch.

**Comment by GreyMario** [comment]
Oh no! The cheapest ammunition available for a tier 1 weapon is still available for use in the equivalent tier ~~2~~3 weapon!

By that logic, Salvos shouldn't have access to Copper.

**Comment by Slava0135** [comment]
> > how often do you see people feeding turrets with silicon? Imo it should be used as basic ammo for higher tiers turret
> 
>     1. Silicon is precious especially early-game and in v6. If graphite isn't an option people will still not use silicon.
> 
>     2. Why do you think it should be used as basic ammo?

1. They will try pyrotite or silicon as there is no other options on this stage of the game. Or just use hails
2. because it's made from coal too.

**Comment by Slava0135** [comment]
> > how often do you see people feeding turrets with silicon? Imo it should be used as basic ammo for higher tiers turret
> 
>     1. Silicon is precious especially early-game and in v6. If graphite isn't an option people will still not use silicon.
> 
>     2. Why do you think it should be used as basic ammo?

1. They will try pyrotite or silicon as there is no other options on this stage of the game. Or just use hails
2. because it's made from coal too.

**Comment by Slava0135** [comment]
> Oh no! The cheapest ammunition available for a tier 1 weapon is still available for use in the equivalent tier ~3~2 weapon!
> 
> By that logic, Salvos shouldn't have access to Copper.

actually, yes

**Comment by the-kido** [comment]
Make a new PR with all the changes you want rather than making up your mind in chat. I think that might give the PR more strength imo.

**Comment by Slava0135** [comment]
yeah I guess so
