### ISSUE TITLE
Ammo tiering rework

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1534]
**Describe what you would like changed, and why.**

There are quite a lot of concerns I have about current ammo tier division:

Graphite is used in all turrets: from basic (duo) to most advanced (spectre). *Why?* Why not make silicon base ammo type for 2/3 tier turrets. Ripple with graphite is being overused. And there is already 5 ammo types. Consider making ripple real tier 2 turret and removing the graphite from their ammo list. Silicon fits better. Hail is forgotten because of ripple.

Salvo using copper: tier 2 turret is being powered by a raw basic resource. Why not try using silicon instead?
Salvo using graphite... is somewhat reasonable.
Salvo using thorium: too big dps for tier 1/2 turret. Yes, thorium is quite limited but you are not under attack most of the time. Also salvos are relatively compact.

Spectre using graphite as well. w H y N o T t R y S i L i C o N i N s T e A d.
Spectre using thorium. It's effortless. Just a fun fact: Spectre shoots rapid moving bullets - why not make it use phase instead of thorium and also reduce other ammo bullet's travel speed?

Fuse... should use blast compound - it makes sense. It looks like fuse makes a directed explosion towards the enemy. And titanium/thorium is quite easy to obtain and use. Damage per item is insane.

**Comment by the-kido** [comment]
The fuse using blast compound thing actually does intrigue me. How about it shoots 3 grenades that extend its AoE and reach? Its damage will be less than 50 tho.

I also agree with the salvo and copper thing

**Comment by Slava0135** [comment]
Also if I remember correctly, Fuse used to use blast compound as ammo in initial version.

**Comment by Slava0135** [comment]
but yeah i T w A s U n P o P u L a R - thus Anuke decided to make it use graphite (which was terrible imo) instead and now it uses titanium / thorium.

**Comment by Slava0135** [comment]
Also swarmers use way too much ammo considering how fast they can shoot and how hard is to make blast/surge.

**Comment by nodevlfrb** [comment]
This is true. Ripples with graph are overused as you said. Also, the other problem with salvos w/thorium is that thorium isn't _that_ hard to obtain, and you can place it in long-term storage between the waves. Otherwise, i tested Salvos + cryo+ thorium + ODD and this is just too OP. It shoots a constant flow of thorium, and if you place a container with only a unloader in-between the salvo and the container, you get a instant throughput thorium consumption by the Salvo. So,maybe yeah upgrade silicon for salvos.

**Comment by ritzip** [comment]
With swarms still in use we won't see uses of salvos anytime soon, they simply are too expensive and needs to be spammed to be "effective". They also cost too much to maintain when used with other ammo.

**Comment by ritzip** [comment]
It may be easy to drill a lot of thorium but doesn't mean they are easy to come by.

**Comment by itcannotbe** [comment]
> With swarms still in use we won't see uses of salvos anytime soon, they simply are too expensive for what it does and needs to be spammed to be "effective". They also cost too much to maintain when used with other ammo.

Salvos aren't meant to handle swarms.
