### ISSUE TITLE
Steam achievement "Shapeshifter" bug

### ISSUE THREAD

**Issue by rtommyj** [Anuken/Mindustry-Suggestions#154]
I received the Shapeshifter achievement on Steam, yet I have not researched Omega Mech or Glaive Ship, much less transformed into them. I did transform into every other available mech, though.

![Annotation 2020-05-08 194752](https://user-images.githubusercontent.com/65050304/81457637-ed2b0c80-9164-11ea-8b41-af08d0158134.png)

**Comment by Anuken** [comment]
This isn't relevant in 6.0, since there are no mechs in the same sense.
