### ISSUE TITLE
Underground water layer for extractor.

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1541]
**Describe the content or mechanics you are proposing.**
Yes, this an another suggestion to "nerf" water extractors but in a very different way.
So basically the idea is to have some sort of underground water layer from where you can pump water. There will be underground rivers and lakes and etc. So you can't place water extractors everywhere but only above underground sources. 
You can research the area using scanner or something.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The water extractors won't be that convenient. They will be very similar to pumps except they can be used on every map. It will make players actually use conduits and stuff.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quick-korkc** [comment]
>I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

You basically didnt read point 3 :
>Underground map layers

**Comment by Slava0135** [comment]
> > I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
> You basically didnt read point 3 :
> 
> > Underground map layers

It's a different thing. It's not an actual map layer.

**Comment by Slava0135** [comment]
Every tile will just have boolean property undergroundWater or something. And if water extractor is above one - it will gain 25% efficency and etc.

**Comment by Slava0135** [comment]
Or there could be just a boolean matrix that is generated randomly on every map to make players play differently.

**Comment by itcannotbe** [comment]
But it is actually a map layer.

Cause you don't expect for every tile to have two type and the feasible option is map layers but as the read me says..... yeah. I don't think so.

**Comment by Quick-korkc** [comment]
>It's a different thing. It's not an actual map layer.
You literally said **underground water layer**
Also water extractor can just melting ice, cleaning water from mud, etc

**Comment by Slava0135** [comment]
By underground layer Anuke meant an actual playable map linked to surface. That's a completely different idea.

**Comment by itcannotbe** [comment]
> By underground map layer Anuke meant an actual playable map linked to surface. That's a completely different idea.

Actually, even tunnel like conveyor suggestion is considered as a underground map layer.

**Comment by Quick-korkc** [comment]
> By underground map layer Anuke meant an actual playable map linked to surface. That's a completely different idea.

Doubt until Anuke himself confirm it

**Comment by Slava0135** [comment]
> > By underground map layer Anuke meant an actual playable map linked to surface. That's a completely different idea.
> 
> Doubt until Anuke himself confirm it

~~***yes***~~

**Comment by itcannotbe** [comment]
Also how on earth would someone implement this without even making it a map layer?

**Comment by Slava0135** [comment]
> Also how on earth would someone implement this without even making it a map layer?

It can be just a single boolean variable in Tile.

**Comment by flarefluffsune** [comment]
I'm just going to point to #1539 which this user also has posted.

This issue is really very much looking entirely personal because people use Water Extractors too much apparently.

**Comment by Slava0135** [comment]
I am going to make a PR with an implementation relatively soon? I guess. I just want to liquid part of game feel differently.

**Comment by flarefluffsune** [comment]
> I just want.

Have you heard of the term "I want, doesn't get."?

If you want to change Water Extractors so badly to suit **your** own tastes make a mod then. You seem to think yourself a coder so it shouldn't be outside your possibility.

**Comment by Quick-korkc** [comment]
> I am going to make a PR with an implementation relatively soon? I guess. I just want to liquid part of game feel differently.

make your own plugin
lot of player dont want more nerf for water extractor

**Comment by Slava0135** [comment]
> > I just want.
> 
> Have you heard of the term "I want, doesn't get."?
> 
> If you want to change Water Extractors so badly to suit **your** own tastes make a mod then. You seem to think yourself a coder so it shouldn't be outside your possibility.

Imo using water extractors sometimes is equals using a routerchain. But the difference is that players usually quite fast understand that using latter is a bad practice.

**Comment by itcannotbe** [comment]
> > Also how on earth would someone implement this without even making it a map layer?
> 
> It can be just a single boolean variable in Tile.

How are map makers going to toggle that boolean?

**Comment by Slava0135** [comment]
> > > Also how on earth would someone implement this without even making it a map layer?
> > 
> > 
> > It can be just a single boolean variable in Tile.
> 
> How are map makers going to toggle that boolean?

Mot the field itself. This underground layer will be generated randomly every time but I guess you can configure the percentage of cover. It will work quite similar to river noise generation in editor.

**Comment by itcannotbe** [comment]
That's isn't even user friendly at all. People want control when making a map.

**Comment by Anuken** [comment]
> underground water layer from where you can pump water. There will be underground rivers and lakes and etc

This is very much an "underground layer", as mentioned in the README.

**Comment by GreyMario** [comment]
Did ANYONE in this clown car of a thread mention that _different floor tiles_ already HAVE varying efficiencies for Water Extractors placed on them?

@Slava0135 If you're that god damn deadset on killing Water Extractors, follow these steps:

1. Cry me a river, Karen.
2. Distill the salt water from your tears.
3. Pave a custom map with the salt from your tears, which has an incredibly poor efficiency for Water Extractors.

**Comment by Quick-korkc** [comment]
Lmao told ya

**Comment by T1murik** [comment]
i think he meant a special ore
