### ISSUE TITLE
BUG: CPU can't compare "string" values

### ISSUE THREAD

**Issue by gmnenad** [Anuken/Mindustry-Suggestions#1542]
When obtaining string value from objects with sensor command ( like 'type' ), it is not possible to compare that string value to normal string, even if it can be printed out.

*For example:
getlink a 0 // this get whatever is first link (in my case it was 'vault1')
sensor aType a @type // this put type of that in variable aType ( in my case, that was 'vault' )
print aType // this correctly print out "vault" ( without parentheses )
op equal cmpType aType "vault" // this should have put 1 in cmpType but it does NOT !
print " eq: "
print cmpType // this prints 0 instead of expected 1
printflush message1

*On the other hand, setting string literal directly to variable works for comparison:
set b "vault" // set variable directly to string literal, instead of reading with sensor
op equal cmpB b "vault" // comparint that variable to same literal now works
print cmpB // this prints '1' as expected

Some additional informations:
- JUMP command is also not able to compare aType to string literal "vault" ( same error as op equal)
- string addition (op add ) does not work either - adding two strings result in number 2 , so I would guess that game treat each string as integer value 1
- sensor reading 'name' property of links does not work from some reason ( empty result, I would have expected 'vault1' in above example)

My guess is that using sensor to obtain string property of some object ( like type or name) does not in fact return string but some complex type - and game did not overload that type to compare to strings.

**Comment by itcannotbe** [comment]
Wrong repository.

**Comment by itcannotbe** [comment]
If only people actually read the read me, they know they're making bug reports in the wrong repository. Heck even the repository name has the word suggestion in it, I wonder why.........

**Comment by gmnenad** [comment]
Well, I did not expect multiple repositories for every different purpose,  as more usual way to do that on github is to use labels like 'bug' , 'suggestion', 'technical issue' etc.  But I guess I could have read the read me anyway.

**Comment by DeltaNedas** [comment]
having a thousand open suggestions would clutter the bug tracker
