### ISSUE TITLE
Just some feed back

### ISSUE THREAD

**Issue by Thecheezie1** [Anuken/Mindustry-Suggestions#1543]
**Describe what you would like changed, and why.**

Ive been playing for a few months now and love the game and have spentt far too many hours playing it lol. I would like to be able tonlaunch resourses again it might just be me but i like my stash and miss it. I love the new units and buildings but i can only build 16 units ground and air then it stops. And id love to see a way to reset individual levels like ground zero or have a way ro drop additional resources on it id like to build it up with advanced tech. Thats all i can think of thanks for the awesome game! I have more ideas but i forgot. Sorry bout any grammer and spelling errors

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by itcannotbe** [comment]
> I would like to be able tonlaunch resourses again it might just be me but i like my stash and miss it.

The game mechanic has already changed. Many already adapted to it.

> I love the new units and buildings but i can only build 16 units ground and air then it stops.

Another changed mechanic, a unit limit now exist. Again many have adapted to it.
Also the type of core you have determines the unit limit.

>  or have a way ro drop additional resources on it id like to build it up with advanced tech.

Make a feedback once you actually far in the game. Launchpads exist to send resources to other sectors.

**Comment by DeltaNedas** [comment]
@Thecheezie1 close this you egg
