### ISSUE TITLE
Logic jump instruction could accept variable value as first parameter

### ISSUE THREAD

**Issue by snizzo** [Anuken/Mindustry-Suggestions#1544]
**Describe the content or mechanics you are proposing.**
Hi, would it be a terrible idea if jump could accept a var as a parameter?

Example:
set i 0
set address 2
add i i 1
jump address

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I'm writing a pseudopython -> mindustry compiler and this change would allow for functions and other more complex block-based programs to work. As of now jump accepting only an hardcoded integer as a parameter only allows a change of context when entering a function. When the function execution ends jumping back to the caller is difficult, requiring an hardcoded jump for every function call that has been made (theoretically doable but crazy?).
If I'm missing a way to do that please let me know!

I think this could open up for more complex software running on processors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
`set @counter address`

**Comment by snizzo** [comment]
Thanks! Missed that.
