### ISSUE TITLE
BUG: Local game tech tree

### ISSUE THREAD

**Issue by RocketSheepOriginal** [Anuken/Mindustry-Suggestions#1545]
When I hosted my campaign game, My friend unlocked all items I've unlocked at research tree, On his game he earned every finished new blocks and ores that I had for free, and collected ores that we both collected during the game, he also earned ores that he doesn't discovered yet.
 Also during the game I unlocked new builds and blocks, he automatically earned that ones without using his ores, while I used it and unlocked for both of us.

**Comment by DeltaNedas** [comment]
how do people mistake this for the bug tracker

**Comment by RocketSheepOriginal** [comment]
> This was intentionally added.

Why?

**Comment by joshuaptfan** [comment]
> Why?

At the initial release of 6.0, there was no co-op progression. Only the host could unlock research and collect resources. It made sense given the structure of the new tech tree and how it was tied to campaign progression. If you wanted to join someone's campaign game, you did it for fun, not to get anything out of it.

[There was a thread on Steam](https://steamcommunity.com/app/1127400/discussions/0/2961643431523504630/) where a lot of co-op-only players asked for co-op progression. They didn't like that after they spent a lot of time helping their friends, they then had to spend the same amount of time progressing their own campaigns separately.

[So, Anuke added tech tree progression and resource sharing.](https://steamcommunity.com/games/1127400/announcements/detail/2901970757302390920) It's not currently a perfect solution, but it's a compromise.

**Comment by itcannotbe** [comment]
> how do people mistake this for the bug tracker

The repository has even the word suggestion in it. I wonder as well.
