### ISSUE TITLE
Block Transport, and overall usage ingame.

### ISSUE THREAD

**Issue by Chickennuggetma** [Anuken/Mindustry-Suggestions#1546]
T5 ground units with legs can pick up blocks, and either place them, or throw them.

This makes transporting blocks somewhat more convenient for those who do not have a entire flying support ship lying around.
The blocks can be Shot out of the Corvus's gun. While the Toxopid, can Pick up blocks and use them as a wrecking ball.
This is mainly about the Toxopid, because i think the "suicide" class needs more of a hands on way of attacking.
NOTE: The Toxopid can pick up enemy blocks, but will move a lot more slower holding said block.

Thank you for reading this, and i am very grateful to be able to play your game, and interact with the Mindustry community.
Have an amazing rest of your day/night. 
Goodbye.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quick-korkc** [comment]
uhhh...
**WHAT**

**Comment by Bohaska** [comment]
I don't like this..

**Comment by sudobeans** [comment]
This would be hilarious and awesome to see in-game, but I don't think it would be very balanced or easy to use. For starters, none of the T5 units with legs can place blocks, so they'd need to get the poly+ units to place them for them. Unless they got their blocks from the enemy's base, but that would be pretty broken too. Can you imagine building a bunch of walls and thinking "oh yeah baybee, my defense is looking pretty good" only to have them instantly ripped off the ground and thrown at you?

Of course, T5 units are already pretty busted, but this would make them even more busted! This is a creative idea, but I think it would be best off as a mod.

**Comment by Kyllingene** [comment]
>This idea would probably be best off as a mod.

You have fun scripting that mod. However, I agree.
