### ISSUE TITLE
Builder drone AI 

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1547]
**Describe what you would like changed, and why.**
BuilderAI.java because the changes will be a nice QoL change.

**Describe the changes you want to propose. Include possible alternatives.**
If builder drone can't find someone to follow, then just build the plans that the player made on its own.

**Comment by MEEPofFaith** [comment]
Doesn't it already do this?

**Comment by Bohaska** [comment]
A comment in another issue called justice to builder drones says no.

**Comment by MEEPofFaith** [comment]
[yawns] time to open obs...

**Comment by Bohaska** [comment]
> [yawns] time to open obs...

What's that?

**Comment by MEEPofFaith** [comment]
[I don't see what you mean by they don't build.](https://cdn.discordapp.com/attachments/663853133587546138/787479445882535936/2020-12-12_16-39-44.mp4)
