### ISSUE TITLE
`draw colour` colour preview

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1548]
when creating a colour it can be a bit tricky to tell what the final colour will be. i suggest having a small square that shows the colour when you are doing `draw colour…` 

possibly have it clickable for a colour picker menu.

[X] <- yes

**Comment by Kyllingene** [comment]
1: I have to presume that you didn't want to take the time to put in several different X's into separate boxes, and so combined them into one. Please let that be true.

2: To anyone who has a browser, finding RGB codes is quite easy ([Google,](https://www.google.com/search?q=rgb+color+picker) [W3Schools,](https://www.w3schools.com/colors/colors_picker.asp) and [First result](https://www.rapidtables.com/web/color/RGB_Color.html))

3: Making a robust color picker is probably harder than it seems. Either you have a few blocks you pick from (not super helpful), or an art-program-worthy color square/triangle/dodecagon for picking your colors.
