### ISSUE TITLE
Compound Jump Comparison(s) [Logic]

### ISSUE THREAD

**Issue by Stardust9681** [Anuken/Mindustry-Suggestions#1549]
**Describe the content or mechanics you are proposing.**
As it is, we have the ability to add "if" conditionals that jump to a line given a certain scenario (Ex: jump 0 x lessThanEqual 10). However, it quickly becomes a mess when you try to make it so that multiple conditions jump to that line, or only jump to that line of multiple conditions are met. Thus, I propose a way to compound these jump statements.
Add a button to the right side of all jump statements, labelled "Add Condition". This will then be displayed on another line in the same jump command (for clear reading). The user can choose to make it an AND or an OR conditional.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make a good deal of Processor Code easier to read ingame, not having 200 (exaggerated, of course) jumps all doing the same thing for different situations. It would also speed up the code writing process, for the same reason.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
guess what `op` does

**Comment by vsmelov** [comment]
> guess what `op` does

@DeltaNedas where did you find any documentation about commands?
I cannot find anything clear on the internet.
