### ISSUE TITLE
Phantom drones continue building after canceling

### ISSUE THREAD

**Issue by feu-follet** [Anuken/Mindustry-Suggestions#155]
**Describe what you would like changed, and why.**
When you're building something and builder drones are helping you, if you cancel the building, they continue, and it's awkward when they're using a resource you need for another thing.

**Describe the changes you want to propose. Include possible alternatives.**
When canceling building, miner drones stop building too.

**Comment by itcannotbe** [comment]
Miner drones don't even build stuff.

**Comment by feu-follet** [comment]
Yes that's an error *builder* drones

**Comment by feu-follet** [comment]
Thank you
