### ISSUE TITLE
Mindustry Logic Processor Coding Toturials

### ISSUE THREAD

**Issue by InLiothixie** [Anuken/Mindustry-Suggestions#1550]
The Game should have its very own toturials on how to use Logic Processors, add a help button  when selecting a logic proccessor.

    Adding an in-game toturials on how to use logic proccessors will greatly help newbies and veterans on their experience.

Using logic proccessors help players to customize specific function of an In-game Entity / Blocks

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quick-korkc** [comment]
just use deltanedas/rftm

**Comment by DeltaNedas** [comment]
use wiki and rtfm

**Comment by Mdbgamer** [comment]
> just use deltanedas/rftm

What if it doesn't work? There are some(me specifically) who cannot despite all efforts get the mod to work.
