### ISSUE TITLE
Don't let Foreshadow shoot through blocks (or above them?)

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#1551]
Foreshadow is designed to kill heavy **units** like T3 and above. But players can use it as a siege weapon that is better than any artillery, because it bypasses any blocks and power fields. Reduced damage to blocks does not balance it because it can still oneshot most of important blocks like power nodes, conveyors, menders and others.

I suggest reworking Foreshadow **to not bypass blocks** and hit the first block in a line, even if aimed behind it manually (but keep the power field piercing). It will still be able to aim through the swarm of enemies to target a specific target.

**Comment by Arackulele** [comment]
The point of foreshadow is the sniping,its very expensive and needs end game ressources for a reason.Like it literally shoots the hardest to obtain material.If you manage to get up a foreshadow it should be fair game to be able to snipe crucial things in ones base.

**Comment by XxsuperdeadlysniperxX** [comment]
Then what is the point of a **railgun** thats exactly what the foreshadow is a huge **railgun** the **railgun** is definitely a bypass weapon because of the sheer power ut has when launching its **projectile** because its going near or at the speed of light it pierces through walls and stuff if the **railgun** can't do that then whats the point of it even existing

If you don't believe me lookup on youtube railgun and you'll see what i mean

**Comment by XxsuperdeadlysniperxX** [comment]
Anuke has seen this by now

**Comment by JamesTheNerd** [comment]
> Then what is the point of a **railgun** thats exactly what the foreshadow it's a huge **railgun** the **railgun** is definitely a bypass weapon because of the sheer power ut has when launching its **projectile** because its going near or at the speed of light it pierces through walls and stuff if the **railgun** can't do that then whats the point of it even existing
Railguns go nowhere _near_ the speed of light. Do not insult physics.

**Comment by XxsuperdeadlysniperxX** [comment]
> > Then what is the point of a **railgun** thats exactly what the foreshadow it's a huge **railgun** the **railgun** is definitely a bypass weapon because of the sheer power ut has when launching its **projectile** because its going near or at the speed of light it pierces through walls and stuff if the **railgun** can't do that then whats the point of it even existing
> Railguns go nowhere _near_ the speed of light. Do not insult physics.
> 
> 
>The railgun shoots out projectiles at almost the speed of light and can hit targets in milliseconds, according to reports.Jul 10, 2020


I looked up how fast a railgun fires and its almost to the speed of light

**Comment by XxsuperdeadlysniperxX** [comment]
Thats purpose of the "at or near" one or the other

**Comment by XxsuperdeadlysniperxX** [comment]
It may jot look like it is on youtube because there a long ways away from the actual railgun

**Comment by SecretMink** [comment]
> > > Then what is the point of a **railgun** thats exactly what the foreshadow it's a huge **railgun** the **railgun** is definitely a bypass weapon because of the sheer power ut has when launching its **projectile** because its going near or at the speed of light it pierces through walls and stuff if the **railgun** can't do that then whats the point of it even existing
> > > Railguns go nowhere _near_ the speed of light. Do not insult physics.
> > 
> > 
> > The railgun shoots out projectiles at almost the speed of light and can hit targets in milliseconds, according to reports.Jul 10, 2020
> 
> I looked up how fast a railgun fires and its almost to the speed of light

My man, no it does not. the speed of light is 1,079,000,000 km/h and the muzzle velocity of the biggest railgun ever built is 12,600 km/h. Please gather data from reliable sources. I completely agree with the foreshadow not piercing walls. Even with its block damage nerf it is still way overpowered. Making it get stopped by walls, but perhaps removing the block damage nerf would be a great way to balance it out and prevent it from completely denying enemy activity in an area. Right now the foreshadow is practically unstoppable, and in pvp whatever team gets the first few of them up wins.

**Comment by Arackulele** [comment]
who cares about real life physics in mindustry when anuke himself said real life doesnt matter to mindustry

**Comment by XxsuperdeadlysniperxX** [comment]
Well a railgun does have penetration powers tho
