### ISSUE TITLE
Force Projector rebalance

### ISSUE THREAD

**Issue by Bluphenyx** [Anuken/Mindustry-Suggestions#1552]
Force Projectors should have a much, much stronger shield while lowering, if not entirely getting rid of the shield regeneration without the projector "resetting".

I believe that the Force Projector is underwhelming in its current state- it's highly ineffective against many units and higher waves for the size, and the maintenance it requires. I believe a rebalance is in order, if not like this, then at least in some other fashion. It honestly feels more worth my time to get another turret or supply line in there.

Thank you for your time, I hope this was clear and concise.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SuperficialIntelligence** [comment]
It's more efficient to spam mend projectors than use a force projector filled with cryofluid. Force projector definitely needs a buff.

**Comment by T1murik** [comment]
~~nerf mend projectors~~
phase boost must be buffed

**Comment by XxsuperdeadlysniperxX** [comment]
Why would anuke nerf the mend projector tho the mend projector is fine, however i do agree with the force projector being underwhelming because i mainly use it to protect the sensitive to damage blocks like Conveyors that simply can't be healed quick enough from bombers but the segment does exist however the segment sucks down power like it's nothing if you don't have better power setup or can't have better power because you already are useing most of them and in the (procedurally generated sectors where resources are scarce)

**Comment by itcannotbe** [comment]
Segments sucks power? Batteries and battery diodes exist.

**Comment by XxsuperdeadlysniperxX** [comment]
I look at it as if someone didn't use diodes or batteries

**Comment by itcannotbe** [comment]
It's in the game to make your power system not crash.

Why not use them in the first place?

**Comment by XxsuperdeadlysniperxX** [comment]
Like i mostly meant at the start of the campaign when you don't have plastanium unlocked and even then they do require plastanium and not many players know how to use them or they just don't use them period, i don't use them.

**Comment by itcannotbe** [comment]
To be honest I use force projectors less than battery diodes.

And I don't even use battery diodes that often.
