### ISSUE TITLE
Sandthrower

### ISSUE THREAD

**Issue by Typyyie** [Anuken/Mindustry-Suggestions#1553]
I think it would be nice to have a weapon that throw a sandcloud at the enemies that block there view and does a little bit of damage.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Play terraria

**Comment by G-mage** [comment]
so pocket sand but its a gun?

**Comment by XxsuperdeadlysniperxX** [comment]
🤦‍♀️ didn't put x's in the boxs

**Comment by XxsuperdeadlysniperxX** [comment]
>Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically. 
Its clear this was not read

**Comment by Kyllingene** [comment]
1: R.I.P. format. May its glory live on past its death.

2: How would blinding enemies work, and how would you make it so you can't just blind them with a couple, and kill them with a few small turrets?

Otherwise, cool idea!

**Comment by XxsuperdeadlysniperxX** [comment]
🤦‍♀️you blinding units makes them lose sight of the objective so that go off in a random direction cuz they are _blind_ and confused

**Comment by Kyllingene** [comment]
Ok, so they still see + shoot. However, the turret would have to be expensive in some way, bc otherwise you just place a bunch with mending walls, and the enemies never reach you.

**Comment by XxsuperdeadlysniperxX** [comment]
Expensive like useing 
For example (only an example):

300 surge
30 plast
5000 copper
1000 lead
300 phase
12000 thorium

This once again is an example to put into perspective the the turm **_expensive_**

**Comment by Kyllingene** [comment]
Yeah, that seems about right for something that routs units.
