### ISSUE TITLE
A final boss for Mindustry/Planet capture.

### ISSUE THREAD

**Issue by Chickennuggetma** [Anuken/Mindustry-Suggestions#1554]
A Campaign/Planet final boss. 
A "cutscene" plays showing a  T5 Corvus (or any T5 unit because its randomized) being put into an extremely large machine, called the Pentative Reconstructor. then, a timer appears showing 5 or 10 minutes until Annihilation.
The unit will be several times larger then the oct, and will have alot of health, but no regeneration. 
A special boss music can play sounding more "dreadful" then the others.
When its done, a flash of light covers the screen, and everything's silent...
Then, the fabled T6 Appears, with a health bar on top of the boss.
The T6 Corvus, will be able to fly, have smaller yet more rapid lasers on the sides, and move extremely slowly. The ground shakes every step it takes, and the boss makes otherworldly noises every so often. 
The T6 units will each have their own weaknesses.
Ill leave the sprite designs to you, because I'm bad at spriting.

A final boss is fitting to a game like this, and would be a fitting ending to a planets capture.

Thank you very much for reading this.
I really do appreciate the community seeing my various ideas and giving feedback.
Most of all, i Appreciate you, and your game, Anuken.
It has helped me through some tough times.
Even a little game can change lives.
Good day/night, everyone!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
Interesting idea i have no idea if anuke will ever look at this (will check trello) but i like this idea

**Comment by Chickennuggetma** [comment]
Thank you very much for replying, this made my day!

**Comment by XxsuperdeadlysniperxX** [comment]
He hasn't looked yet but he might

**Comment by Chickennuggetma** [comment]
ok, thank you!

**Comment by XxsuperdeadlysniperxX** [comment]
No problem

**Comment by FarmerThanos** [comment]
i want this, i really do
but i do wonder if Anuke will accept this

**Comment by Arackulele** [comment]
this idea seems kinda way too specific,it slike it will and it does when its a suggestion
You should suggest a generla idea not a super specific boss cutscene that should play out exactly to your liking

**Comment by T1murik** [comment]
~~the whole campaign is super specific~~
camera moving is enough
after completing all waves a black part of map reveals, camera moves for a short time. not specific but cutscene
but i think foreshadow spam can easily kill t6 boss

**Comment by XxsuperdeadlysniperxX** [comment]
@Arackulele so you want vague details of the boss fight with 0 chance it would go in this guy's favor?

**Comment by XxsuperdeadlysniperxX** [comment]
Enough foreshadows can destroy anything

**Comment by Arackulele** [comment]
> @Arackulele so you want vague details of the boss fight with 0 chance it would go in this guy's favor?

Well,the person was using terms as ''it will'' and ''will be'' its a suggestion not a request to make anuke implement your lazy idea instead of making it a mod,you suggest things that imporve the game and not just add more content because cool and if you suggest something,unless you have a mod or specific worked out idea in your mind that would actually be good gameplay wise you dont just ask anuke to basically implement the exact thing like that because haha funny

**Comment by Chickennuggetma** [comment]
Very interesting discussion, I would like to hear more opinions about this.

**Comment by XxsuperdeadlysniperxX** [comment]
> > @Arackulele so you want vague details of the boss fight with 0 chance it would go in this guy's favor?
> 
> Well,the person was using terms as ''it will'' and ''will be'' its a suggestion not a request to make anuke implement your lazy idea instead of making it a mod,you suggest things that imporve the game and not just add more content because cool and if you suggest something,unless you have a mod or specific worked out idea in your mind that would actually be good gameplay wise you dont just ask anuke to basically implement the exact thing like that because haha funny

You do realize this is not my suggestion right? @Arackulele

**Comment by XxsuperdeadlysniperxX** [comment]
I can't freaking believe arackulele thinks this is actually mine 😁

**Comment by Arackulele** [comment]
haha,so funny,does it change my point.is my entire point invalid becasue haha you thought i was addressing you specifically?

**Comment by XxsuperdeadlysniperxX** [comment]
No and im sorry for offending you howecer you quoted my comment

**Comment by XxsuperdeadlysniperxX** [comment]
So i was telling you because you quoted **my** specific comment that thisn't my suggestion more like a response again sorry if i offended you

**Comment by XxsuperdeadlysniperxX** [comment]
Also being actually nice helps to instead of actually targeting me and being not nice😑

**Comment by Arackulele** [comment]
> 
> 
> Also being actually nice helps to instead of actually targeting me and being not nice😑

says you,who just made 2 comments baout how its so funny that i quoted you

**Comment by XxsuperdeadlysniperxX** [comment]
🤔😑 well you quoted my comment _then_ was mean to me for literally nothing, like i even told you that im not the one that owns the suggestion, @Chickennuggetma does, i for one asked a question, not an aggressive just one that is telling you mindustry is more specific then you actually realize and _even_ more complex than it is specific (fun fact: you can possess a router) just the regular one not the distributor))

**Comment by Kyllingene** [comment]
1: The past seven comments are completely off-topic. Find a different chat, please.

2: The suggestion, whether good or bad, was well thought-out. Suggestions that go like "here is a vague idea, make it good" are not very helpful, and are unlikely to be implemented. While their choice of words may have seemed forceful and demanding to you, to me it simply felt like someone trying to get their thoughts into words, and not trying to nitpick everything in their issue. If I was making a game, I would want people giving me well thought-out ideas, although bugging me about them (which this person is not doing, notice how their comments have simply been "Thanks!" and "I would like to hear more.") would stop them from existing in the game. It simply makes the development easier, as you have to brainstorm less. All in all, there is no harm done either way, stop fighting about it.

**Comment by XxsuperdeadlysniperxX** [comment]
> 1: The past seven comments are completely off-topic. Find a different chat, please.
> 
> 2: The suggestion, whether good or bad, was well thought-out. Suggestions that go like "here is a vague idea, make it good" are not very helpful, and are unlikely to be implemented. While their choice of words may have seemed forceful and demanding to you, to me it simply felt like someone trying to get their thoughts into words, and not trying to nitpick everything in their issue. If I was making a game, I would want people giving me well thought-out ideas, although bugging me about them (which this person is not doing, notice how their comments have simply been "Thanks!" and "I would like to hear more.") would stop them from existing in the game. It simply makes the development easier, as you have to brainstorm less. All in all, there is no harm done either way, stop fighting about it.

Im not talking to chickennuggetma its Arackulele im talking to so actually ask before assuming im arguing with chickennuggetma plz
@Kyllingene if you read the comments that are supportive those are the ones that are telling chickennuggetma that his idea is awsome but the template needs to be followed in order to be implemented @Arackulele is the one that isn't supportive and very crude about applying their opinions i hope this clears things up **i swear im trying to keep things on topic what would you do if your being attacked out of no where by some random person that bumps their way in to the comments**

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene i recommend reading every comment next time to see who is talking to who and why they talking that way?😑

**Comment by XxsuperdeadlysniperxX** [comment]
For some reason im confused 🤔

**Comment by Kyllingene** [comment]
>Im not talking to chickennuggetma its Arackulele im talking to so actually ask before assuming im arguing with chickennuggetma plz

I knew that. Try reading my comment. Why would I ask you to stop talking to the OP?

>if you read the comments that are supportive those are the ones that are telling chickennuggetma

I was referring to the OP's comments, not yours or Arackulele's. I was explaining that the OP stated their suggestion well and did exactly what Anuken wants. You got me completely wrong, 
> so actually ask before assuming

what I was talking about.

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene im trying was trying to talk to the OP <-- (is like the short for operater or something) but arackulele step in with rudeness then will i was still talking to chickennuggetma i was trying to at the same time trying to get this guy to not offend some guy that is just both being supportive and voicing my opinion 

My opinion: i absolutely love the suggestion 

Someone who has apparently no idea want is happening and targets me as a result:
_brings a thing entirely unrelated to the issue (feature request) and attacks me for this making me think he's attacking me about chickennuggetma's feature request_

Also its called a **_request_** for a reason because you are **_requesting_** the feature it actually doesn't mean it will be approved tho

**Comment by XxsuperdeadlysniperxX** [comment]
And the request part is where the template plays its part

**Comment by Chickennuggetma** [comment]
I appreciate all the feedback, and criticism of my request!
thank you all for being so generous to comment and share your opinions!
:)

**Comment by Kyllingene** [comment]
>And the request part is where the template plays its part

You realize that you have definitely used language like that (certain in an uncertain situation) on a thousand different occasions? Would you get mad at me for saying 'we will win this!' when the game is tied? No, of course not!

**Comment by XxsuperdeadlysniperxX** [comment]
I realized this 🤔 i wasn't certain at all and idk why i wrote that wow im strange

**Comment by Chickennuggetma** [comment]
![Uploading Mindustry 12_19_2020 12_54_17 AM.png…]()

T6 unit

**Comment by Zarcana-The-Hypermech** [comment]
Seems interesting, but i think the final boss should be a T7 instead of a T6 to make sure it's a high difficulty thing
