### ISSUE TITLE
[logic] adding new statements should initiate a drag n drop

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1555]
**Describe what you would like changed, and why.**

Currently if you want to add a statement to the middle of a program you need to
1. add it
2. scroll to the bottom
3. drag it along to hopefully where you were before

**Describe the changes you want to propose. Include possible alternatives.**

1. add instruction
2. ghost statement follows your mouse/finger and will stay when you click or release.

**Comment by JamesTheNerd** [comment]
This would be amazing. Huge QOL improvement.

**Comment by Overblob** [comment]
As an alternative way to solve this problem, I think it could be done by adding the ability to select a statement so that when we click the add button, the new statement is inserted below the selected one.
(Maybe easier to implement?)

**Comment by Kyllingene** [comment]
Please!
