### ISSUE TITLE
Virtual joystick

### ISSUE THREAD

**Issue by Krizis112** [Anuken/Mindustry-Suggestions#1557]
Management on phone devices is not suitable for active battles due to its imperfection. I suggest adding the * combat mode * function, namely, that when the game interface is minimized, two separate joysticks are displayed that are responsible for movement and shooting. This will make PC and Android/IOS players more or less equal in capabilities.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
This suggestion would get android users a very high disadvantage because joysticks suck on mobile devices and pc users have a extremely high advantage cuz they use keyboard and mouse and if the controller has support on the game then they my also use that

**Comment by itcannotbe** [comment]
[Did you even try?] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by Nikolass1000** [comment]
> 
> 
> This suggestion would get android users a very high disadvantage because joysticks suck on mobile devices and pc users have a extremely high advantage cuz they use keyboard and mouse and if the controller has support on the game then they my also use that

Imagine punctuation marks

**Comment by Krizis112** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1557#issuecomment-744062823 This idea has a right to life, especially since it is not bad.

**Comment by itcannotbe** [comment]
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [This idea has no right to life because you didn't even try doing this] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
[This is what you would have seen of you actually did **a quick search** in the list of suggestions **to make sure this has not been suggested yet**.](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+joystick)

**Comment by XxsuperdeadlysniperxX** [comment]
Not many people of the internet are going to use punctuation but i can try to use it to reduce that number @Nikolass1000
