### ISSUE TITLE
Mass driver

### ISSUE THREAD

**Issue by DUDE44850** [Anuken/Mindustry-Suggestions#1558]
**Describe what you would like changed, and why.**
i would like it so the mass driver can transport all materials

**Describe the changes you want to propose. Include possible alternatives.**
i was trying to use the mass driver to transport some coal across the map for a silicon smelter and i was unable to do this using a mass driver and thought it would be very helpful to be able to use the mass driver with coal and other materials like sand

**Comment by DeltaNedas** [comment]
that already works, close this @DUDE44850
