### ISSUE TITLE
Cryo fluid for high level drills

### ISSUE THREAD

**Issue by jjlearbo** [Anuken/Mindustry-Suggestions#156]
So like the title says it's quite simple. The Air Blast drill and the laser drill are both theoretically would generate a lot of heat especially the laser drill. So my proposition is simple. Allow both the Air Blast drill and the laser drill to be supplied with cryo fluid. 

This would make the drill more efficient. This is something that popped into my head and I'm kind of new to this so bear with me. 

For balancing purposes I suggest making the amount of cryo fluid needed a little bit on the absurd side. My thoughts are about 15 cryo fluid a second for the Air Blast drill and 12 cryo fluid a second for the laser drill. This makes it a little more expensive by needing an extra cryo fluid factory for just one extra Air Blast generator. 

But my thinking is that if you really need a certain resource really desperately, even though water is the more cheap option, the slightly more expensive option will get you a lot more. Now the added multiplier from cryo will need to be experimented with but im thinking x3.75 or x4.15. I don't know why but I seem to have a lot of extra titanium just sitting around doing nothing. One extra thing needing titanium would be fun. 

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by jaygamer81** [comment]
Idk... do we really want a more op drill?

**Comment by stuffyAI** [comment]
With this title your suggestion has no chance of making it trough mate
