### ISSUE TITLE
[logic] dropping items into null = throwing away

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1560]
**Describe the content or mechanics you are proposing.**

if the building dropped to with `itemDrop` is null, throw away the item stack.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

rather than finding the local incinerator, this would allow for discarding items like a player can.

in terms of griefing, players can already do this *much* faster than units can so it's not a risk.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
Problem is, it may be easy to accidentally drop something and waste resources when you forget to check if a building is `null`.

**Comment by JanKaifer** [comment]
+1 for this feature

If `null` seems too risky it can always be something like `@air` or a completely new symbol like `@void`

**Comment by G0nTar** [comment]
Bump, I need this, so I can use mono miners to transport resources, and not get stuck if they have lead or copper from mining on their inv from mining when traveling from sector to sector
