### ISSUE TITLE
Command centers should require power!

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry-Suggestions#1561]
**Describe the content or mechanics you are proposing.**
Yes, I only need that to control units automatically, because units are annoying to do stuff with... unless logic

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I just need this to have an enemy base that deploy enemies in certain locations depending on certain criteria. Command center should trigger if it gets powered and no others are powered. That way commanding units autonomously should be possible without logic, because I’m that kind of guy.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
I...

I don't think you quite understand how Command Centers _work._

**Comment by sudobeans** [comment]
I'm confused by what you're saying. 
> I just need this to have an enemy base that deploy enemies in certain locations depending on certain criteria.
What kind of certain criteria?
>if it gets powered and no others are powered.
By "powered," do you mean receiving energy, or when it's been clicked on? Having to disconnect and reconnect power to get command centers to work sounds like quite a hassle.

**Comment by AESIR-Foopy** [comment]
Allow me to elaborate, Command Center to different action depending on what setting/mode it is in, but I want to have a requirement that it needs power for it to do any actions and powering it will trigger/allow it to function. But, when multiple command center exist, they all change setting/mode if one gets changed. I don’t know why some people have multiple Command Centers at one but I dunno. I guess this should only apply to single play and custom maps. I just feel that commend centers have next to no purpose because logic (which I dislike) is the main focus for players to command units with.

**Comment by AESIR-Foopy** [comment]
That didn’t seem simpler

**Comment by TrinityXYZ4544** [comment]
So basically if the command center is powered it will do what its supposed to do based on what's it's set on (Attack, idle, Retreat)? and it's settings don't or no longer share with other command center?

**Comment by Kyllingene** [comment]
I think what they are getting at. They want command centers to take power, and when they lack power, they stop functioning, almost as if it wasn't there. However, if it alone has power, it will act independent of disabled centers. When more than one are enabled, they all share a command, just like it is currently.

I have no idea how you would make a system without logic that enables them when criteria are met, but this seems reasonable. One question: would they consume power, or just require a connection to it?
