### ISSUE TITLE
make units parts fall off when they die

### ISSUE THREAD

**Issue by theangelurd** [Anuken/Mindustry-Suggestions#1562]
it would be better if the parts of a unit fell off when they die, it would leave a cool effect. this includes mechs too
e.g make weapons or mounts fall off, maybe make legs be scattered around.

**Comment by XxsuperdeadlysniperxX** [comment]
Robots don't just fall apart tho

**Comment by itcannotbe** [comment]
OP forgot this

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
To be honest, this is going to be a lot of unnecessary work if implemented.

**Comment by theangelurd** [comment]
this was the first suggestion I put for mindustry, so I didn't exactly know what to do
also, I realize now it's not a good idea

**Comment by BlueWolf3682** [comment]
actually, this would be quite cool

**Comment by itcannotbe** [comment]
Until you factored in the work to be done to make sprites for every severed part of every unit and coding how it breaks apart......

**Comment by XxsuperdeadlysniperxX** [comment]
And to add to that its visual only

**Comment by theangelurd** [comment]
wait what if it wasn't actually visual only and it actually collided with other units

**Comment by DeltaNedas** [comment]
nice effect of having arms and legs fall of then exploding
would probably be too much work though

**Comment by XxsuperdeadlysniperxX** [comment]
Well it is depending on the many units and tiers of those units there are in the game. heres a good list of the work someone attempting to implement this pretty cool idea has to do as an example:
#1 individual spriting of every gun of every unit
#2 individually spriting every locomotive piece of the mechs aka the legs 
#3 makeing a second sprite for the unit ships hull without guns
#4 then finally codeing the entirety of the last 3 steps to fall apart a specific way, angle, velocity of the parts, where they land, the rotation of the pieces, the start of the effect, and working out the bugs that come with this 

All this will most likely need lots of space and lag mobile players and some lag in game *might* occur because of the amount of content also crashs

**Comment by XxsuperdeadlysniperxX** [comment]
Other than the effort i sopport the idea also you'd have to add collision to the death of the ships if you want some functionality like moveing units around

**Comment by theangelurd** [comment]
technically you don't need to resprite due to units dropping their pieces, you could just copy the already existing sprites

**Comment by theangelurd** [comment]
and yes i want the fallen parts to block another unit's path

**Comment by theangelurd** [comment]
should i reopen this issue?

**Comment by XxsuperdeadlysniperxX** [comment]
I look at it in a way that if they didn't have the different sprites you know like if this game was made lazily (i know anuke put a *lot* of effort in to the game, just look at the game in the light of a knockoff version of mindustry)

**Comment by theangelurd** [comment]
so should anuke just remake sprites to make them be exactly the same as the original ones?

**Comment by theangelurd** [comment]
why would the sprites be different, if they are literally parts that are already in a unit

**Comment by XxsuperdeadlysniperxX** [comment]
Im not meaning to remake them unless the individual ones don't exist not saying they don't exist. 🤔 i just haven't looked at the the Sprite file yet, does the file even exist on github?

**Comment by XxsuperdeadlysniperxX** [comment]
> technically you don't need to resprite due to units dropping their pieces, you could just copy the already existing sprites

I agree with this sorry about the confusion

**Comment by theangelurd** [comment]
i'm also planning there to be a limited amount of parts that could be configured so it doesn't lag

**Comment by XxsuperdeadlysniperxX** [comment]
If you reopen the issue anuke may comment although there might some toxic others that are legitimately toxic and not just judgmental i think gray mario said she liked so who know who else will like

**Comment by XxsuperdeadlysniperxX** [comment]
Because in every player base theres those people with a god complex and a feeling of being unphaseable oh and those people who don't actually think before typing (**_no one has targeted so plz don't make drama for nothing thank you_**)

**Comment by Arackulele** [comment]
shy reopen it,its a stupid suggestion with no meaning and comical parts falling off of units would look wuite out of place for mindustry,the effect right now is fine isnt it? What would this bring to the game??? it would require wayyy to much work for a basically unnoticable visual change

**Comment by XxsuperdeadlysniperxX** [comment]
#1 @Arackulele correct grammers helps make sentences make sense

#2 i would love to anukes opinion on the suggestion

#3 harsh behaviour aka being controling isn't recommended

#4 it would be noticeable because of the game being **_2d_**

If anuke finds this **_ok_** to do then it might be added we will know until anuke actually shares his opinion or well concerns with this because anuken is not mean nor is he that nice but he is i guess a neutral type where you never know for sure what he's going to say (not trying to judge anuke and im sure this is relatively unbiased)

**Comment by theangelurd** [comment]
> 
> 
> shy reopen it,its a stupid suggestion with no meaning and comical parts falling off of units would look wuite out of place for mindustry,the effect right now is fine isnt it? What would this bring to the game??? it would require wayyy to much work for a basically unnoticable visual change

how would it be unnoticable
there would be a bunch of parts lying around and you would obviously see them

**Comment by XxsuperdeadlysniperxX** [comment]
🤣

**Comment by theangelurd** [comment]
are you going to comment again?

**Comment by XxsuperdeadlysniperxX** [comment]
Oh also i don't see the checkboxes so he most likely ignored the issue

**Comment by XxsuperdeadlysniperxX** [comment]
I would either go the the link to get to the feature request template copy it and cancel the issue creation or close the issue if you make the issue valid again he might actually consider it

**Comment by XxsuperdeadlysniperxX** [comment]
Btw i was decorating my Christmas tree

**Comment by Arackulele** [comment]
yay,dismissing my comment because wrong grammar,anyways
Its unnoticable because its literally a death effect it doesnt change any gameplay even if it did m the gameplay change wouldnt imrpove the gsmeplay.This suggestion would literally just increase lag for a very minor effect that doesnt even fit the style of mindustry.

**Comment by XxsuperdeadlysniperxX** [comment]
🤔 i agree with none of that comment if you add this type of effect to a _2d_ game you will notice a difference and do you **_even_** understand how noticeable things are like death effects in a **_2d_** game? _VERY_ noticeable like the alpha unit for example the change is on death the ship persists until it hits the ground while it has black smoke on the the ship and the ship does damage upon impact of a building tho a minor amount, this death animation / effect is flexible you can make the individual pieces explode and do more damage to the base multiple times you're trying to dismiss this as "useless" and "unappealing" while i see "potential" and "pride for effort" in this also making much more sense of the discription of of scrap "the leftovers of old buildings and **_units_**" which this effect will make that make sense of how the mechs leave metal all over the ground. (@theangelurd im so sorry to say this but you need to follow the template and leave the checkboxes marked)

**Comment by XxsuperdeadlysniperxX** [comment]
@Arackulele have even attempted to play the game or the classic version of the old version of the game if you haven't why even look at the suggestions if you have 0 knowledge of the game if have good for you you still know barely anything about how every little change can effect a 2d game and games in general

**Comment by XxsuperdeadlysniperxX** [comment]
@theangelurd if you would have followed the template you'd have an awesome effect possibly implemented

**Comment by Arackulele** [comment]
eid any of you focus on any other part of my comment?
No?
Thank you very much
im gonna make an entirely new one then,this would not fit the game and its more minimalist style without tons of effects and comically stupid looking things like a unit part that would according to this suggestion lie flat with the same orientation as on the actual unit.Like thats a very low effort flash game thing to do and according to anything Anuke has done with mindustry would not fit the game at all

**Comment by theangelurd** [comment]
> 
> 
> @theangelurd if you would have followed the template you'd have an awesome effect possibly implemented

i didn't know how to do suggestions at all

**Comment by XxsuperdeadlysniperxX** [comment]
> eid any of you focus on any other part of my comment?
> No?
> Thank you very much
> im gonna make an entirely new one then,this would not fit the game and its more minimalist style without tons of effects and comically stupid looking things like a unit part that would according to this suggestion lie flat with the same orientation as on the actual unit.Like thats a very low effort flash game thing to do and according to anything Anuke has done with mindustry would not fit the game at all

You know for one im trying to stay on topic _however_ there are ways to make this suggestion not lag

**Comment by XxsuperdeadlysniperxX** [comment]
> > 
> > 
> > @theangelurd if you would have followed the template you'd have an awesome effect possibly implemented
> 
> i didn't know how to do suggestions at all

A template appears in ever feature request which you follow the layout by putting in the first one what you want in the game then in the step how you want it to be put in the game and then you put an in between the brackets after you have checked what it says you agreed on checking like for example [x] <-- these make your suggestion valid but you have to make sure that your suggestion wasn't suggested previously or is actively open

**Comment by Arackulele** [comment]
> 
> 
> > eid any of you focus on any other part of my comment?
> > No?
> > Thank you very much
> > im gonna make an entirely new one then,this would not fit the game and its more minimalist style without tons of effects and comically stupid looking things like a unit part that would according to this suggestion lie flat with the same orientation as on the actual unit.Like thats a very low effort flash game thing to do and according to anything Anuke has done with mindustry would not fit the game at all
> 
> You know for one im trying to stay on topic _however_ there are ways to make this suggestion not lag in game (tho im no coder so i couldn't tell you how)

this is so cool doing the same thing agan, maybe respond to my main point,that it does not fit the game

**Comment by XxsuperdeadlysniperxX** [comment]
@Arackulele then explain _how_ it doesn't fit so we know your opinion on the issue plz?

**Comment by Arackulele** [comment]
> 
> 
> @Arackulele then explain _how_ it doesn't fit so we know your opinion on the issue plz?

i already did,well ill explain again.Mindustrys style is more focused on minimalistic,effective effects.The effects are mostly kept at particles and sound and nt a goofy looking , unrotatable enemy part falling off wich would in mindustrys artstyle always look goofy and weird.Also even the flying Units crashing has a gameplay effect that enhanced the game and if this goofy unftting thing was added it would have no gameplay effect or even if you think of some crazy cool gameüplay effect it would either be unnoticable or make the game worse.

**Comment by XxsuperdeadlysniperxX** [comment]
**_visible confusion_** it won't make the game worse also like i meant to say it either a sequenced thing or upon explosion have parts scatter and have them also do damage in some way

**Comment by Arackulele** [comment]
> 
> 
> **_visible confusion_** it won't make the game worse also like i meant to say it either a sequenced thing or upon explosion have parts scatter and have them also do damage in some way

would it make the game more visually appealing and does it fit the style? No.
Does it cause extra lag?Yes.
Therefore it makes the game worse.
Just it doing something dooesnt automatically make the game better,there needs to be a good reason.Air units crashing was added to go against Scatter spam.Whats the thing so good that a ground unit explosion would be nice to have.Walls?

**Comment by XxsuperdeadlysniperxX** [comment]
The shock could trigger it (with the shock your would essentially overload the ship's software and because its bullet i will knockoff guns or at least have a chance to)

Frag ammo could trigger it (because your legitimately blowing huge holes in to the hull of a ship so this would make it to where guns will fall off)

Specters can trigger it (this ones obvious why)

Also pierce ammo would have a chance to cause this effect

And the effect would cause the guns to explode upon contact with the ground upon splitting causeing the ammo in the gun to fire in whatever direction it is facing  upon _rotation_ of the piece and cause damage and the other parts would have a chance to hit a building if a building is in the blast radius and cause a little bit more damage and disappear upon hitting a building or the ground so that it won't cause lag

**Comment by Arackulele** [comment]
> 
> 
> The shock could trigger it (with the shock your would essentially overload the ship's software and because its bullet i will knockoff guns or at least have a chance to)
> 
> Frag ammo could trigger it (because your legitimately blowing huge holes in to the hull of a ship so this would make it to where guns will fall off)
> 
> Specters can trigger it (this ones obvious why)
> 
> Also pierce ammo would have a chance to cause this effect
> 
> And the effect would cause the guns to explode upon contact with the ground upon splitting causeing the ammo in the gun to fire in whatever direction it is facing upon _rotation_ of the piece and cause damage and the other parts would have a chance to hit a building if a building is in the blast radius and cause a little bit more damage and disappear upon hitting a building or the ground so that it won't cause lag

why damage? If theres no reason for it to do damage **Gameplay wise** then it shouldnt do damage

**Comment by theangelurd** [comment]
> 
> 
> > The shock could trigger it (with the shock your would essentially overload the ship's software and because its bullet i will knockoff guns or at least have a chance to)
> > Frag ammo could trigger it (because your legitimately blowing huge holes in to the hull of a ship so this would make it to where guns will fall off)
> > Specters can trigger it (this ones obvious why)
> > Also pierce ammo would have a chance to cause this effect
> > And the effect would cause the guns to explode upon contact with the ground upon splitting causeing the ammo in the gun to fire in whatever direction it is facing upon _rotation_ of the piece and cause damage and the other parts would have a chance to hit a building if a building is in the blast radius and cause a little bit more damage and disappear upon hitting a building or the ground so that it won't cause lag
> 
> why damage? If theres no reason for it to do damage **Gameplay wise** then it shouldnt do damage

i mean, if the parts are going at high speeds it kinda makes sense that it would do damage

**Comment by theangelurd** [comment]
wow no one said anything in 14 days
it's new year already

**Comment by Kyllingene** [comment]
Look at how many effects are in the game already:

> none unitSpawn unitCapKill unitControl unitDespawn unitSpirit itemTransfer pointBeam pointHit lightning commandSend upgradeCore placeBlock tapBlock breakBlock select smoke fallSmoke unitWreck rocketSmoke rocketSmokeLarge magmasmoke spawn padlaunch vtolHover unitDrop unitLand unitLandSmall unitPickup landShock pickup greenBomb greenLaserCharge greenLaserChargeSmall healWaveDynamic healWave heal shieldWave shieldApply hitBulletSmall hitFuse hitBulletBig hitFlameSmall hitLiquid hitLancer hitMeltdown hitMeltHeal instBomb instTrail instShoot instHit hitLaser hitYellowLaser despawn flakExplosion plasticExplosion plasticExplosionFlak blastExplosion sapExplosion massiveExplosion artilleryTrail incendTrail missileTrail absorb flakExplosionBig burning fire fireSmoke steam fireballsmoke ballfire freezing melting wet muddy sapped sporeSlowed oily overdriven overclocked dropItem shockwave bigShockwave nuclearShockwave impactShockwave spawnShockwave explosion dynamicExplosion blockExplosion blockExplosionSmoke shootSmall shootHeal shootHealYellow shootSmallSmoke shootBig shootBig2 shootBigSmoke shootBigSmoke2 shootSmallFlame shootPyraFlame shootLiquid casing1 casing2 casing3 casing4 casing2Double casing3Double railShoot railTrail railHit lancerLaserShoot lancerLaserShootSmoke lancerLaserCharge lancerLaserChargeBegin lightningCharge sparkShoot lightningShoot thoriumShoot reactorsmoke nuclearsmoke cloudsmoke nuclearcloud impactsmoke impactcloud redgeneratespark generatespark fuelburn coreBurn plasticburn pulverize pulverizeRed pulverizeRedder pulverizeSmall pulverizeMedium producesmoke smokeCloud smeltsmoke formsmoke blastsmoke lava dooropen doorclose dooropenlarge doorcloselarge purify purifyoil purifystone generate mine mineBig mineHuge smelt teleportActivate teleport teleportOut ripple bubble launch launchPod healWaveMend overdriveWave healBlock healBlockFull overdriveBlockFull shieldBreak unitShieldBreak coreLand


Straight from the updated wiki. Do you see how many unnecessary effects are there? There are two unitLand's, unitSpawn and unitControl are pretty darn similar, purifyoil and purifystone look the same to me, etc. For goodness' sake, there is pulverizeRed and pulverizeRedder! So, the "it would cause lag" argument doesn't seem very strong anymore.



And now for the "looks goofy" bit. I see this as a subtle, but nice change; not flying guns, simply dropping guns. Legs flopping slightly. Unit body rotating a tiny bit. I agree that if the guns flew really far or anything dramatic, it would look silly and out of place; at the moment though, all you need to do is look at the turret shoot effects to see that a new effect would look fine.


And last of all, the "no gameplay, no reason" bit. Because the previous two have been weakened at least slightly, this one should be a little easier. Obviously, that argument doesn't apply to everything, because if it did, games would consist of boxes and squares. So, does it apply here? I say no. It belongs just as much as turret cooldown effects do; it brings reason and believability into the death animation, just as the turret animations bring believability into them.


Also, @Arackulele, it is really hard to comprehend what you are trying to say in your comments. Unless you have some sort of handicap (mobile, hurt hand, etc.) your typing shows that sometimes, you don't try. Whether or not English is your native language, you misspell things a lot in a way that indicates hurried typing. You know how to spell these words (unless, somehow, you can speak English without knowing how the word "not" is spelled), so if you can, could you please spend a little more care when typing? Again, English might not be your first language, but these are typos, not mispells.


**If anything in my comment seemed rude or toxic, please forgive me and let me know. I am, in fact, human.**

**Comment by itcannotbe** [comment]
> anything in my comment seemed rude or toxic, please forgive me and let me know. I am, in fact, human.

Nah. Being frank is never rude however the delivery is.

**Comment by BlueWolf3682** [comment]
> Until you factored in the work to be done to make sprites for every severed part of every unit and coding how it breaks apart......

what? the sprites are already there

**Comment by theangelurd** [comment]
> 
> 
> Look at how many effects are in the game already:
> 
> > none unitSpawn unitCapKill unitControl unitDespawn unitSpirit itemTransfer pointBeam pointHit lightning commandSend upgradeCore placeBlock tapBlock breakBlock select smoke fallSmoke unitWreck rocketSmoke rocketSmokeLarge magmasmoke spawn padlaunch vtolHover unitDrop unitLand unitLandSmall unitPickup landShock pickup greenBomb greenLaserCharge greenLaserChargeSmall healWaveDynamic healWave heal shieldWave shieldApply hitBulletSmall hitFuse hitBulletBig hitFlameSmall hitLiquid hitLancer hitMeltdown hitMeltHeal instBomb instTrail instShoot instHit hitLaser hitYellowLaser despawn flakExplosion plasticExplosion plasticExplosionFlak blastExplosion sapExplosion massiveExplosion artilleryTrail incendTrail missileTrail absorb flakExplosionBig burning fire fireSmoke steam fireballsmoke ballfire freezing melting wet muddy sapped sporeSlowed oily overdriven overclocked dropItem shockwave bigShockwave nuclearShockwave impactShockwave spawnShockwave explosion dynamicExplosion blockExplosion blockExplosionSmoke shootSmall shootHeal shootHealYellow shootSmallSmoke shootBig shootBig2 shootBigSmoke shootBigSmoke2 shootSmallFlame shootPyraFlame shootLiquid casing1 casing2 casing3 casing4 casing2Double casing3Double railShoot railTrail railHit lancerLaserShoot lancerLaserShootSmoke lancerLaserCharge lancerLaserChargeBegin lightningCharge sparkShoot lightningShoot thoriumShoot reactorsmoke nuclearsmoke cloudsmoke nuclearcloud impactsmoke impactcloud redgeneratespark generatespark fuelburn coreBurn plasticburn pulverize pulverizeRed pulverizeRedder pulverizeSmall pulverizeMedium producesmoke smokeCloud smeltsmoke formsmoke blastsmoke lava dooropen doorclose dooropenlarge doorcloselarge purify purifyoil purifystone generate mine mineBig mineHuge smelt teleportActivate teleport teleportOut ripple bubble launch launchPod healWaveMend overdriveWave healBlock healBlockFull overdriveBlockFull shieldBreak unitShieldBreak coreLand
> 
> Straight from the updated wiki. Do you see how many unnecessary effects are there? There are two unitLand's, unitSpawn and unitControl are pretty darn similar, purifyoil and purifystone look the same to me, etc. For goodness' sake, there is pulverizeRed and pulverizeRedder! So, the "it would cause lag" argument doesn't seem very strong anymore.
> 
> And now for the "looks goofy" bit. I see this as a subtle, but nice change; not flying guns, simply dropping guns. Legs flopping slightly. Unit body rotating a tiny bit. I agree that if the guns flew really far or anything dramatic, it would look silly and out of place; at the moment though, all you need to do is look at the turret shoot effects to see that a new effect would look fine.
> 
> And last of all, the "no gameplay, no reason" bit. Because the previous two have been weakened at least slightly, this one should be a little easier. Obviously, that argument doesn't apply to everything, because if it did, games would consist of boxes and squares. So, does it apply here? I say no. It belongs just as much as turret cooldown effects do; it brings reason and believability into the death animation, just as the turret animations bring believability into them.
> 
> Also, @Arackulele, it is really hard to comprehend what you are trying to say in your comments. Unless you have some sort of handicap (mobile, hurt hand, etc.) your typing shows that sometimes, you don't try. Whether or not English is your native language, you misspell things a lot in a way that indicates hurried typing. You know how to spell these words (unless, somehow, you can speak English without knowing how the word "not" is spelled), so if you can, could you please spend a little more care when typing? Again, English might not be your first language, but these are typos, not misspells.
> 
> **If anything in my comment seemed rude or toxic, please forgive me and let me know. I am, in fact, human.**

thank you for defending my suggestion.

**Comment by theangelurd** [comment]
at this point, i doubt anuke will acknowledge this but eh

**Comment by Kyllingene** [comment]
> at this point, i doubt anuke will acknowledge this but eh

Sadly, that seems to be correct. If anyone here wants to, a PR would really help this out; I would, but 1: I suck at Java, and 2: I suck at the base code.

**Comment by SavageCreeper64** [comment]
Idea: 
New unit called scrapper that can pick up broken pieces of units and can scrap them into various resources.
Details still to be worked out

**Comment by BlueWolf3682** [comment]
this would be easy to implement for one that knows java: its just making the weapons go off in a forwardish direction and thats it. sprites are there already cause who knew, the weapons have their sprites we can use

**Comment by theangelurd** [comment]
i am commenting so that this does not die

**Comment by theangelurd** [comment]
nvm
this time it did not work
guess this is the end of this suggestion

**Comment by rylid-umil** [comment]
there can be an option to disable unit fallapart in settings
