### ISSUE TITLE
Worm-like Digging Units

### ISSUE THREAD

**Issue by SuperficialIntelligence** [Anuken/Mindustry-Suggestions#1563]
**Describe the content or mechanics you are proposing.**
Segmented units that travel through natural terrain walls but are very vulnerable when in open areas especially to piercing turrets. Their presence is signified by the glowing lights it's segments emit whilst it's in the walls, it's lights will turn off if it doesn't move. Their main way of dealing damage is ramming into buildings and maybe a few weak laser turrets on some of the bigger unit's segments. They will gain momentum when in walls and lose it when in open areas, the amount of damage they do depends on the speed of which they ram into said building.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make terrain walls less safe in the later stages of the game forcing players to create defenses on the walls to prevent a worm ambush. It also gives a new way of damaging things by ramming straight into buildings which would be very satisfying to do. These units are unique in the fact the specialize in melee damage and ambush attacks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
We have air units.

**Comment by G-mage** [comment]
isnt there a "no underground map layers" rule? cool idea but im pretty sure its forbidden

**Comment by SuperficialIntelligence** [comment]
> isnt there a "no underground map layers" rule? cool idea but im pretty sure its forbidden
I'm not talking about underground, I'm talking about the natural walls/terrain. What I'm proposing is a unit that moves inside natural walls. I never mentioned underground layers.

**Comment by SuperficialIntelligence** [comment]
> We have air units.

Naval units are a thing even though air units can already traverse over water. So why not have a unit that is dedicated to moving through walls.

**Comment by Kyllingene** [comment]
Honestly, I like the idea. Since they would be late game, they wouldn't make the early game defense impossible, but the late game turrets + production can handle it. Any idea on the tier progression?

**Comment by notMEEPoffaith** [comment]
PU WILL have worms, but isint PU coming out in 2022?
