### ISSUE TITLE
Liquid launch pad thing (name it whatever you want)

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1564]
Its like the launchpad but its to launch liquids

Thes liquids woukd be stored a block you place on the ground like point a to b system but it is specifically for holding the launched liquids it'll make coal making easier for those maps with no place to put oil extractors and very little coal (nucear production complex) and maps with little to no water or if you need slag somewhere where it has no scrap this could help (i doubt anuke will add this if anyone even slightly cares) in that sense (i didn't see anything about this in the open and closed issues)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
I just ask no harrassment if you do harrass me or someone else you will in direct violation with harassment gidelines of github and may result in action taken on your account

**Comment by GreyMario** [comment]
I'm sorry, aren't you still stuck on Fungal Pass? Nuclear Production Complex is locked behiind Fungal Pass.

**Comment by NajimiOsana** [comment]
> I just ask no harrassment if you do harrass me or someone else you will be in direct violation with harassment gidelines of github and may result in action taken on your account

You're calling it *harrassment* because your opinion got shot down and you couldn't fight back?

**Comment by nichrosia** [comment]
Also, don't water extractors require beating Salt Flats which is *even more* difficult than Fungal Pass?

**Comment by XxsuperdeadlysniperxX** [comment]
Harrassment is legit bullying someone because they have mistakes in there work or their beliefs or behaviors even other things i don't want to list because im too lazy to write for an hour

**Comment by XxsuperdeadlysniperxX** [comment]
My "why did i even do that idea" got shotdown so what?

**Comment by XxsuperdeadlysniperxX** [comment]
Gray mario im at planitary launch terminal im far past fungal pass

**Comment by XxsuperdeadlysniperxX** [comment]
Im at the last map of the game

**Comment by XxsuperdeadlysniperxX** [comment]
I've learned not to be stupid so if you would not be the one to harrass me again that would be great

**Comment by aFuschia** [comment]
a

**Comment by XxsuperdeadlysniperxX** [comment]
And also just because it happens once it doesn't mean im going to be an idiot and do it again

**Comment by nichrosia** [comment]
Alright, I for one will stop "harassing" because yes, this is against the community guidelines.

**Comment by nichrosia** [comment]
But you don't really need to transport resources other than maybe slag which could be exported from Ruinous Shores because the of the excess scrap, also, you would have to unlock this after salt flats and tar fields because otherwise it would defeat the point of not having water extractors pre-salt flats

**Comment by NajimiOsana** [comment]
or you could just launch scrap to melt it into slag??

**Comment by NajimiOsana** [comment]
and you can just unload it from your core

**Comment by nichrosia** [comment]
this is highly true

**Comment by NajimiOsana** [comment]
you can even use scrap to get cryofluid

**Comment by GreyMario** [comment]
> Gray mario im at planitary launch terminal im far past fungal pass

How many mods did it take you to get past Fungal Pass?

**Comment by XxsuperdeadlysniperxX** [comment]
Theres some resources you can't just load into the launchpad to launch that to the core like oil for coal scrap is kinda everywhere

**Comment by nichrosia** [comment]
> Theres some resources you can't just load into the launchpad to launch that to the core like oil for **coal** scrap is kinda everywhere

HMMMMMMM, you totally can't just launch with coal

**Comment by nichrosia** [comment]
And use launch pads to import even more

**Comment by itcannotbe** [comment]
Oil? Cultivators/Oil Extractors
Slag? Scarp
Cryo? Titanium
Water? Do I even have to point out this?

**Comment by aFuschia** [comment]
^^^^^^
Oil = Tar Pools, Cultivators > Presses, Oil Extractors
Slag = Slag Pools, Melters
Cryofluid = Titanium > Mixer, Scrap > Titanium
Water = Pools, Wexts

**Comment by GreyMario** [comment]
Why make coal on-site if you can literally just launch with it in your inventory and import more using Launch Pads?

Slag as a weapon is something you kind of just do on a whim. You don't export scrap just to process it elsewhere unless you are literally out of space to process scrap to materials in the source sector... and if you manage to produce so much scrap that you need more space than is physically present in the map you are sourcing the scrap from... there's something very, very wrong.

Cryofluid is something you generally create on-site when an application requires it. You generally won't be using it at all if the map doesn't have titanium... generally because if the map doesn't have titanium, it's probably a very, _very_ easy map.

And if you need to import water from somewhere in order to get a job done? Salt Flats should have taught you how to get work done without using a single drop of water.

**Comment by ritzip** [comment]
> Harrassment is legit bullying someone because they have mistakes in there work or their beliefs or behaviors even other things i don't want to list because im too lazy to write for an hour

That's not harassment, did you even go to school?

**Comment by ritzip** [comment]
One phrase. Core does not store liquids.

**Comment by ritzip** [comment]
> My "why did i even do that idea" got shotdown so what?

If you can't even give a proper reasoning and call arguments "bullying" you shouldn't be making suggestions nor should you be in the internet.

**Comment by XxsuperdeadlysniperxX** [comment]
Theres whats call harrassment its about the same as bullying but worse however if you can't say anything nice don't say anything at all also its wrong to tell someone that they should not be on the internet just because they can't reason if someone is told they have no experience that equals a reaction to say they have "some experience" ritzip have you even looked at githubs guidelines **at all** doesn't seem like it (you do not have to reasonable on the internet anyway because being mean to someone in anyway is harrassment theres just different severities of harrassment

**Comment by XxsuperdeadlysniperxX** [comment]
> Core does not store liquids.

And yes i know the core doesn't store liquids

**Comment by aFuschia** [comment]
> > Core does not store liquids.
> And yes i know the core doesn't store liquids

Then where _Liquid Launchpads_ launch to if core doesn't store liquids? Shower them onto the sector?

**Comment by XxsuperdeadlysniperxX** [comment]
**i would recommend looking at the guidelines of github to make sure you don't get banned/your account deleted**

**Comment by ritzip** [comment]
**This is the mindustry suggestions repo, We need reasoning here.** And no, It's not only your reasoning; Did you read my whole message?

I never said I had more experience than you. When was a general rule of the internet ever a harassment? **There is a fine line between discussion and harassment, and there is a fine line between refuting and bullying.**

**Comment by itcannotbe** [comment]
Is that an actual threat? Cause at this point your actions are actually classified as harrasment.

**Comment by ritzip** [comment]
> 3. [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet

I would recommend not telling someone to read the guidelines when you don't even read this repository's guideline.

**Comment by GreyMario** [comment]
> **i would recommend looking at the guidelines of github to make sure you don't get banned/your account deleted**

You're so hellbent on threatening _us_ with punishment because you're unhappy that you're being told you're _wrong_? Sweetie, _that's_ harassment and bullying. Ask Mommy, she'll tell you.

**Comment by itcannotbe** [comment]
> > **i would recommend looking at the guidelines of github to make sure you don't get banned/your account deleted**
> 
> You're so hellbent on threatening _us_ with punishment because you're unhappy that you're being told you're _wrong_? Sweetie, _that's_ harassment and bullying. Ask Mommy, she'll tell you.
> 
> In fact, go on. Report the lot of us. Stop waving around your _big stick_ of _I'm Going To Tell Daddy_ and actually swing it. GitHub will tell you you're wasting your time. And theirs.

Let him swing his and let us swing ours.

**Comment by XxsuperdeadlysniperxX** [comment]
That was an example also being reasonable also requires the people on the other side of the conversation to also try to not offend others. I try not to offend others but because of my werid mindset i can't seem to not offend people also i closed that suggestion i wanted to actually delete it but being that im not a maintainer of the repo i can't so i really would love to not be offended because being off topic doesn't improve the topic

**Comment by XxsuperdeadlysniperxX** [comment]
Im not threatening you with a report im mentioning the guideline because i feel like im being attacked for existing and have a different idea then everyone else a mistake is a mistake ok

**Comment by ritzip** [comment]
You are contradicting yourself. Who again attacked someone for having his youtube channel have 30 subscribers only?

**Comment by GreyMario** [comment]
What was that about me being "marked" as a "content creator" like that's some kind of sign of the devil?

**Comment by XxsuperdeadlysniperxX** [comment]
I was attacked first so is self-defense not allowed im closeing this thread

**Comment by XxsuperdeadlysniperxX** [comment]
😶

**Comment by GreyMario** [comment]
XxsuperdeadlysniperxX: "I was attacked first"
Also XxsuperdeadlysniperxX: _I'm going to open an issue to complain about Fungal Pass and pre-emptively call everyone noobs and accuse them of using mods to beat it_ ![](https://puu.sh/GXkRA.png)

**Comment by XxsuperdeadlysniperxX** [comment]
Can you not be brought up again and again i didn't say specific names so you can't exactly say i was calling yall noobs

**Comment by ritzip** [comment]
You *were* claiming *the one who created the video* was using mods. You *were* implying that the one reading the issue was a nimwit/troll.

**Comment by GreyMario** [comment]
> so you can't exactly say i was calling yall noobs

> (don't you even mention that its easy you actual nimwits try it without mods and you'll see what i mean)

So you do _not_ admit to writing the quoted string from the pictured post? You do _not_ admit to pre-emptively calling all who would respond to your issue report "nimwits" and accusing them of using mods to cheat their way through what is ostensibly--and proven to be--a very easy attack sector?

**Comment by XxsuperdeadlysniperxX** [comment]
It wasn't targeted to specific people it is in the past please stop bring up things that have no relation this repository and stop attacking me at the personal level i am very sorry for offending you and anyone else can you please forgive me for assholeish nature and move on to doing sonething else please

**Comment by XxsuperdeadlysniperxX** [comment]
I have lost a lot in my life and simply...........can't..........handle it all i ask for is forgiveness please i have been bullied all my life lost a a family member seen a dogs death and nearly died myself because of an asthma attack i have been on the brink of fucking death so please if you actually care about a life i only ask for forgiveness so im not depressed on Christmas day the only year of happiness i have and a time for joy......................

**Comment by Cherriodude** [comment]
Ok

**Comment by Bohaska** [comment]
@XxsuperdeadlysniperxX [Citation needed]

**Comment by XxsuperdeadlysniperxX** [comment]
No normal seen what happens ~10 seconds after death and i have technically for ~10 and because i had more will power to stay alive i seen shit not a single person wants to ever see in there like time to this day i feel like my soul is dead due to sheer amount of stuff i've seen and i know @GreyMario maybe hasn't been at this state hopefully not but i seriously doubt my existence every.single.day so this whole experience i will remember for the rest of my entire life and i will never forget that day

**Comment by Bohaska** [comment]
> No normal seen what happens ~10 seconds after death and i have technically for ~10 and because i had more will power to stay alive i seen shit not a single person wants to ever see in there like time to this day i feel like my soul is dead due to sheer amount of stuff i've seen and i know @GreyMario maybe hasn't been at this state hopefully not but i seriously doubt my existence every.single.day so this whole experience i will remember for the rest of my entire life and i will never forget that day
 
I asked for citations

**Comment by aFuschia** [comment]
> > No normal seen what happens ~10 seconds after death and i have technically for ~10 and because i had more will power to stay alive i seen shit not a single person wants to ever see in there like time to this day i feel like my soul is dead due to sheer amount of stuff i've seen and i know @GreyMario maybe hasn't been at this state hopefully not but i seriously doubt my existence every.single.day so this whole experience i will remember for the rest of my entire life and i will never forget that day
> 
> I asked for citations (and popcorn)

popcorn

**Comment by XxsuperdeadlysniperxX** [comment]
I ask myself every fucking day this same miserable question every time i have bouts of depressive thoughts: "why me?" This was enough to traumatize me to my very core to this day i keep seeing myself dieing over and over again alone and afraid of what will happen next

**Comment by Bohaska** [comment]
> I ask myself every fucking day this same miserable question every time i have bouts of depressive thoughts: "why me?" This was enough to traumatize me to my very core to this day i keep seeing myself dieing over and over again alone and afraid of what will happen next

I ASKED FOR CITATIONS i.e. how do we know you really are like that? Also, make my popcorn caramel flavoured.

**Comment by ritzip** [comment]
You are being too personal.

**Comment by GreyMario** [comment]
Y'all got kettle-cooked? Hold the salt.

**Comment by Bohaska** [comment]
Still waiting for my popcorn. Also add some Coca Cola to it, it will be delicious.

**Comment by sudobeans** [comment]
Yo sniper do you have a Discord account so I can DM you about something

**Comment by XxsuperdeadlysniperxX** [comment]
So your asking for proof?!

**Comment by XxsuperdeadlysniperxX** [comment]
Yes i have a discord account its XxsuperdeadlysniperxX#7998

**Comment by Bohaska** [comment]
> So your asking for proof?!

Yes...

**Comment by XxsuperdeadlysniperxX** [comment]
How am i going to prove that i had these experiences theres no legal documents that i know of because of the way my parents are and i don't need to to disclose private info like diagnoses on the internet because its not a public thing 😑

**Comment by XxsuperdeadlysniperxX** [comment]
Not to be aggressive in anyway because i don't want people to misuse sensitive information of me for nefarious purposes

**Comment by Bohaska** [comment]
> How am i going to prove that i had these experiences when theres no legal documents that i know of because of the way my parents are and i don't need to to disclose private info like diagnoses on the internet because its not a public thing 😑

too bad....

**Comment by sudobeans** [comment]
Sniper can you accept my friend request on Discord

**Comment by XxsuperdeadlysniperxX** [comment]
And gray mario is the one i seriously apologized to. im actually very sorry about everything i did and i admit i was wrong. if you can forgive me that would be very appreciated and because i was in the wrong i forgive you. im sorry very very sorry.

**Comment by XxsuperdeadlysniperxX** [comment]
@sudobeans i won't be able to respond to the message cuz internet issues

**Comment by Bohaska** [comment]
Anyway let's get back on topic guys do we all agree that liquid launch pads are bad

**Comment by D-player1** [comment]
Can't wait for someone suggesting building launch pad

**Comment by XxsuperdeadlysniperxX** [comment]
Now that think about it yes the idea seems worse now that im thinking about it

**Comment by XxsuperdeadlysniperxX** [comment]
@sudobeans a problem has arisen i seem to be logged out of my discord account i hope wasn't hacked i probably know who it might be if it has been but not going to say anything specific yet

**Comment by G-mage** [comment]
what the fuck happened here?

**Comment by flarefluffsune** [comment]
> what the fuck happened here?

A child had access to the internet, salty that he can't be fungal pass.

**Comment by Bohaska** [comment]
> as someone who is on medication for it and it having therapy sessions for it

Wait, how in the world did you know this...

**Comment by itcannotbe** [comment]
> > what the fuck happened here?
> 
> A child had access to the internet, salty that he can't be fungal pass.
> 
> Also apparently talking about depression, as someone who is on medication for it and it having therapy sessions for it, I don't think this kid knows what he's talking about. I don't use my depression as a bloody excuse for my actions.

This is the most wholesome comment on this issue.

**Comment by flarefluffsune** [comment]
> > as someone who is on medication for it and it having therapy sessions for it
> 
> Wait, how in the world did you know this...

I think you may need to read up on your English Grammar. I was talking about myself adding a point of my own within the statement I made about this child making excuses.

**Comment by GreyMario** [comment]
> > as someone who is on medication for it and it having therapy sessions for it
> 
> Wait, how in the world did you know this...

Oh no you don't. We have a low enough average reading comprehension in this thread and the one prior, we don't need you fucking it up even worse.

It doesn't matter what kind of sob story this kid cooks up, or if it's real or not. It's an incredibly childish tactic to switch to, especially given the _timing._

Hell, the fact that he thought it'd work _at all_ is just even more telling as to his actual age.

**Comment by aFuschia** [comment]
> what the fuck happened here?

an argument which took a few days, as usual.

**Comment by XxsuperdeadlysniperxX** [comment]
Report me see what happens

**Comment by sample-text-here** [comment]
🍿

**Comment by QmelZ** [comment]
yep amazing as always

**Comment by Kyllingene** [comment]
Please, stop this thread. Now.

**Comment by genNAowl** [comment]
Well they did stop more than a month ago

**Comment by Kyllingene** [comment]
Ah fair. I will unsub and leave this "discussion" to wither and die.

**Comment by genNAowl** [comment]
Same
