### ISSUE TITLE
Ways to transport liquids between sectors, but with some disadvantages so they aren

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1565]
**Describe the content or mechanics you are proposing.**
I have ideas for 2 types of ways to transport liquids between sectors without being too OP. The first method is to first send your liquid into a Pod Factory which encases liquids in pods, uses 100 energy units per second, and uses 1 plastanium and 3 metaglass every 2 seconds to encase 50 liquid units into 1 liquid pod. Liquid pods act like items. After they arrive, you can open them using a Pod Opener which opens the pods and uses 100 energy units per second and opens pods at a speed of 1 pod/1.5 seconds. 

The other idea only works with water, and involves a Ice Machine that changes 50 liquid units of water into 1 ice block in 2 seconds, and uses 140 power units per second, and an Ice Melter that changes 1 ice block into 35 units of water in 2 seconds and uses 140 power units per second

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More choices almost always = better

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Accident and sent duplicate suggestions 2 times

**Comment by XxsuperdeadlysniperxX** [comment]
How did it post 2 suggestions?
