### ISSUE TITLE
Make blocks that can't be breaked

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry-Suggestions#1567]
As the title say, i suggest a block that CAN'T be breaked or by a enemies/players. also enemies/players can't interact with it.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Sometimes, i want to force players/enemies to do a specific thing, like pass through a certain way, and make something, like a puzzle, if i just place the blocks, some player will break it, like on a server. (and only with walls i can't make a puzzle).

I thought about something really interesting that can be make by this, as you know, logic blocks can control units, with this, i can make units go to a specific way, being able do strategies, like separate units to various ways, making the player need to make specific strategies to beat them.

On a server this will be impossible, some player will broke the processor.

I hope you add it :)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Is another #394?

**Comment by rodrigolitzius** [comment]
No, it there says banned blocks, i suggest a new a block that tou can if it can be breaked or not.

**Comment by itcannotbe** [comment]
The point of the suggestion is actually unbreakable blocks, but the OP, used banned blocks as a starting point for implementation of the idea.

**Comment by rodrigolitzius** [comment]
It's better to suggest that there?

**Comment by itcannotbe** [comment]
Probably just rename this to something more obvious as to the actual point of it and maybe let the op of that old suggestion close his.

**Comment by itcannotbe** [comment]
Also it's better if the blocks set as unbreakable cannot be interacted with (ie. locate block with logic or get the block shot at by ai or auto target.

Also I think the best way to implement this is with a team color but it's not really a team XD.

**Comment by joshuaptfan** [comment]
[This was attempted before as a ground tile type that would "lock" any block placed on it.](https://github.com/Anuken/Mindustry/pull/1150)

**Comment by rodrigolitzius** [comment]
> Also I think the best way to implement this is with a team color but it's not really a team XD.
Good idea too

**Comment by rodrigolitzius** [comment]
But with this will be impossible to make what i said.

**Comment by Kyllingene** [comment]
Here's the problem:
I go onto an innocent, pure (no banned blocks, plugins, whatever) server, and place a bunch of these. Maybe I cover the coal, maybe I surround the core, whatever. By the time they ban me, the damage is complete and irrevocable. And don't throw the "the server can ban it" argument, because your reason for wanting it is because of server stuff. And also, imagine a 1v1 where I get air superiority, then block of the path for ground troops so they can't use them.

I do like the (scrapped) tile idea though, because then it's up to the mapmaker to place the tiles, so the only griefable places are put there on purpose, and can be managed.

**Comment by joshuaptfan** [comment]
@Kyllingene No, the idea is that this would be a property you can apply to blocks only in the map editor, not during a game.

**Comment by Kyllingene** [comment]
Ah, I see. I was under the impression that you wanted a *type* of block that couldn’t be broken, but you simply want a *flag*. In that case, +1.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rodrigolitzius** [comment]
> I was under the impression that you wanted a *type* of block that couldn’t be broken, but you simply want a *flag*.

Yeah, only the mapmaker can place this blocks on editor.
