### ISSUE TITLE
Programming languages in Logic blocks

### ISSUE THREAD

**Issue by sinder38** [Anuken/Mindustry-Suggestions#1568]
I want to be able to use programming languages in Logic blocks (processors). For example Python, Java and C variations.  

I think this feature will make programming logic blocks faster and easier. Players will have more control on their variables, functions and others.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Notsinder** [comment]
I think Java is the easiest to make, but very high-level languages like Python will be nice for beginners.

**Comment by GreyMario** [comment]
No.

**Comment by itcannotbe** [comment]
Have you tried actually making a programming language dumb enough for people in game to be at least making simple code with?

**Comment by WHITED4WN** [comment]
The current logic system is pretty much fine as it is, it’s good for beginners and has great capability, and works well across all devices

**Comment by WilloIzCitron** [comment]
Yes

**Comment by WilloIzCitron** [comment]
It's need a mindustry api

**Comment by WilloIzCitron** [comment]
And api wrapper

**Comment by GreyMario** [comment]
@WilloIzCitron Do you even know what those words _mean_?

The Logic system uses a simplistic Assembly-like language for several reasons, none of which I have the inclination to waste my time explaining to either you or the OP.

**Comment by DeltaNedas** [comment]
if you want to write a compiler for a higher level language go ahead, theres no reason for anuke to make every language you like

**Comment by sudobeans** [comment]
I think Mindustry logic is a simple and limited language on purpose. The lack of for loops / arrays / lists forces you to find new and clever ways to implement things. If you could just program in a higher-level language, then no one would use memory cells because they could just create arrays.

**Comment by Kyllingene** [comment]
Ok, first of all, how easy is it to make a bunch of different languages able to interact with another one? I honestly don't know, I only make single-language projects. Also, as a Python programmer who has had trouble with mlog, I cannot endorse this suggestion. The difficulty of including even one language in the game without breaking the logic system entirely seems way to large for anyone to do, and forget 3. Java, **maybe**, but for one, how would you protect against people reading/writing files? Making loops that hurt your fps? Crash your computer? How would you protect against Mindustry opening programs? Also, how would you slow the language down to the processor speed? And finally, would these languages be able to interact with each other and the assembly one? The amount of problems that would have to be tackled is immense, especially if you wanted to do it for more than one language. And, as mentioned by others, mlog is designed to be simplistic and limited.

**Comment by neumond** [comment]
I'm developing Python to mlogic compiler, seems like it does the trick. It's very limited subset of Python, but it helps a lot to write programs faster.
https://github.com/neumond/minpiler

**Comment by Vilsol** [comment]
When I saw this issue at first, I thought it was a meme. So I made it a reality. 

Go to MLOG Transpiler: https://github.com/Vilsol/go-mlog

Web IDE/Playground: https://vilsol.github.io/go-mlog-web/
