### ISSUE TITLE
Logic Comments

### ISSUE THREAD

**Issue by rafaelandrepedro** [Anuken/Mindustry-Suggestions#1569]
**Describe the content or mechanics you are proposing.**
Two new logic blocks.
1-"Comment Blocks" used to divide visually the code (don't have direct impact in the performance)
2-"L Blocks" similar to the Comment Blocks, but also contains code. Has the increased feature of export/import a segment of code.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Both Blocks Would help read code from other programmers and would help to copy and paste repetitive code segments (and label them)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Number 1 would be comment blocks or something.

**Comment by rafaelandrepedro** [comment]
Name fixed!
Can't change title tho.

**Comment by itcannotbe** [comment]
> Number 1 would be comment blocks or something.

> Name fixed!

It's already in game.

**Comment by T1murik** [comment]
it is already in game, but:
1) comments in mlog disappear while copying to processor
2) "Print", "Set" commands affect performance
it can be yellow "#" block
