### ISSUE TITLE
Tower Upgrades

### ISSUE THREAD

**Issue by Gamingtank** [Anuken/Mindustry-Suggestions#157]
When playing this I thought it would be nice if I can use all the towers or make all viable. So I was thinking of tower upgrades like in most tower defense games I have played. Each tower should get 3 tiers so the basic, advance, and expert, these upgrades up make the ammo do more damage.

How do I upgrade? First, you would need to get the research for the new tiers (this could be separate ie. one for advance and one for expert or together). Then when you start building you can upgrade it with stronger materials.

Why would this help the game? I feel that in most of the tower defense games I play there is some sort of physical upgrade to the towers. I know that you can add liquid to each tower so it shoots faster but no visual difference of an upgrade to the tower. By doing this it makes it more satisfying to upgrade them. In turn, this would make the towers more useful in the later waves and make them not feel so wasteful and just remove them to make more space for other towers.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I'm not interested in adding external tower/block upgrades. Mindustry isn't that type of game.
