### ISSUE TITLE
Liquid Tanks and being able to transport huge amounts of liquid per second.

### ISSUE THREAD

**Issue by Wetelemon** [Anuken/Mindustry-Suggestions#1571]
**Describe what you would like changed, and why.**
As the title says, liquid tanks and juntions can transport gigantic amounts of liquid, up to even 330k/s in case of tanks and 10k/s in case of junctions on my tests.

**Describe the changes you want to propose. Include possible alternatives.**
I just want liquid tanks and liquid junctions to have limits, on how fast they can transport, maybe limit equal to pulse conduit. I also have noticed that the speed of the liquid is dependent on your max fps, on around 1k frames it was running with the speed of 330k liquid per second (10k for junction), but on 60fps limit it was just 20k (620 liquid/s for junction).

**Comment by itcannotbe** [comment]
This isn't an issue because first and foremost, you don't even have the inputs to make tanks behave like that in a normal gameplay.

**Comment by scarf-generic** [comment]
anuke is aware. this issue has no reason to remain open

**Comment by BlueWolf3682** [comment]
> This isn't an issue because first and foremost, you don't even have the inputs to make tanks behave like that in a normal gameplay.

thats what you think *hehe*

**Comment by BlueWolf3682** [comment]
@Wetelemon fyi, junctions are infinite, tanks are actually more limited than junctions

**Comment by itcannotbe** [comment]
> > This isn't an issue because first and foremost, you don't even have the inputs to make tanks behave like that in a normal gameplay.
> 
> thats what you think _hehe_

XD
