### ISSUE TITLE
Schemes Categories

### ISSUE THREAD

**Issue by GlowScarf** [Anuken/Mindustry-Suggestions#1572]
**Describe the content or mechanics you are proposing.**

The ability to create Scheme categories.
{ I know there is a search bar and you can search your schemes but let's say you have many many schemes, it would be better to assign them into categories e.x. all pixel arts you have made into the pixel art category e.t.c.}

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Better scheme organization.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[Did you even actually try?] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by GlowScarf** [comment]
You are right. I found it now. A folder suggestion. I did my search here and on trello also on discord about categories. But didn't even think of the world folder. But yes I really tried . :)

**Comment by Catchears** [comment]
You can close this issue now.

**Comment by scarf-generic** [comment]
close this, its been suggested many times before and has not been added.

**Comment by DeltaNedas** [comment]
@GlowScarf close this you egg

**Comment by GlowScarf** [comment]
Lol why u mad
