### ISSUE TITLE
Display the number of each unit on the player's team in the HUD

### ISSUE THREAD

**Issue by sudobeans** [Anuken/Mindustry-Suggestions#1573]
**Describe the content or mechanics you are proposing.**
I think that it would be nice to have something in the HUD that tells us the number of each unit that our team has, kinda like how there's a thing that displays the amount of each item in the core.

I've made a fake screenshot of what this might look like: [https://i.imgur.com/OaIw7kG.jpg](https://i.imgur.com/OaIw7kG.jpg)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would just be a nice quality of life feature. At the moment, the best way to see how many units of one type there are is to hover over the factory or reconstructor. But if a reconstructor isn't working on a unit, then you can't see the amount of each unit.
 
This feature would be especially useful on community servers so that I know how our team's doing as soon as I join.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

I have done all of these things, but someone might have already suggested this using different words than I did. I'll probably close this thread if someone has. This wasn't in the Trello, unless it falls under "complete UI redesign."

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Overblob** [comment]
It would be very useful on server connect indeed.
I think it should also be useful when we try to know which units the team should start or stop producing, depending of the current game phase/context, eg number of support or attack units
