### ISSUE TITLE
Unloader inconsistent flow

### ISSUE THREAD

**Issue by bigminigame** [Anuken/Mindustry-Suggestions#1574]
It seems like one of the unloader you can see there has a problem, and doesn't allow enough coal to flow. While all of the others are fast enough.
![image](https://user-images.githubusercontent.com/45541958/102140093-13352f80-3e5f-11eb-97e2-5421ca3cf0c6.png)

**Comment by itcannotbe** [comment]
If that's a bug report, this is the wrong place to make one.

**Comment by GreyMario** [comment]
In before this is a backflow problem

**Comment by bigminigame** [comment]
Sorry for the wrong section, I wasn't sure.
Still, if this is a backflow problem, this is inconsistant because the machine you see is the only one having this problem, the others are all receiving enough coal.

**Comment by bigminigame** [comment]
Try it if you want, depending on the orientation you'll get between 0 and 3 machines only operation at about 95% capacity.
`bXNjaAF4nFWTa3KbMBRGLwi9eEkk2YYX0Q10Dw5mOmRs8GBIm410sZ1p3Xv15TH8iK8g0tV3dAQ90VNOxXS8DFSsw22l6jTc+mW8ruM8EVUUb+N57Ofp0C9bPz6fB4rH5TIvw+nAb1+Ht3mh8LyMpx/D1wv3sk196mCWeVuHherr/HNYDrd5W/qB3Dad5+OJ37fXt+W4jutwuIy/+Lnj8XEat8tXM8//vRxe5/FEVRq+NyH6TZSRpzwjSapyLrXln2/89z2Tx1Ye6X6//yPFg0CpRMoLLh1lmhtYJ+t1ZnhcaR4py6Na2mbUklJceGHBJVImTx3ljnKysn0uO0vhmQWXQLniEmVdLjN92pIXyEolJUdRKAWKRjHSRVGKXTAbt1ZgU3s2tWdTYFNgU7xxavdAquTyyFiFMtwxAeaWRwmwAGABwEJWy1MnZBpkGmQaZBpkWqYQx0ynb5DQ7BOafUKDhAYJjZy+45ISmveEmjtaV9z/ksjTXPX9D+9g+P2HGovkFsktklvEslBj0dWmrpocObhyIHIgciByWOrgysOVhysPVx6uPFx5uPJw5eGqhCuPk/D7k/D7k/A4CY+T8HIShht8qCkBWAKwBGCJlCXUVACpAFKhX4UpFdQ0UFMjUL0PVO8D1WhQI1CND6NhE0Zuq9j4MJEuKj6W5jNwg8ANAjcI3CBNAyMtBLTI3SJ3CwEtZrYQECAgQECAgAABAQICBAQICBAQISCAN+x5w543gDeAN0BA/OSJ4IngieCJ+PgjBHQA6QDSAaQDSCdTHF/BICAPsokUpivpkQJvkmUyiulCy6iTy5//B7XTd6k=`

**Comment by itcannotbe** [comment]
And this is a topic to long to discuss on what things could affect unloader operation with blocks.

**Comment by XxsuperdeadlysniperxX** [comment]
> It seems like one of the unloader you can see there has a problem, and doesn't allow enough coal to flow. While all of the others are fast enough.
> ![image](https://user-images.githubusercontent.com/45541958/102140093-13352f80-3e5f-11eb-97e2-5421ca3cf0c6.png)
> 
> 
> 

Its because the container and silicon crusible is conflicting with each other because both can have the unloader used on them im a little triggered by that too

**Comment by XxsuperdeadlysniperxX** [comment]
I have a image that gives me an error of unloading coal from a crucible, if its possible with this its as possible with the silicon smelter

**Comment by XxsuperdeadlysniperxX** [comment]
> In before this is a backflow problem

Actually they are trying to extract coal from both the crucible and the container it is a bigger backflow problem but they in contest with each other aka cross flow problem

**Comment by XxsuperdeadlysniperxX** [comment]
I fixed your problem for ya 😁
bXNjaAF4nFWUfZKbMAzFBcZffBnS7TFyiF6gd8gS2qGTQMYJ2+6NesbOtKnkt5Nd/khkGyS9nx5AT/Q5p2I+nEfS36Zf45Gq43gd4nS5TctMVFF3nU7TsMz7Ia7D9HwaqTvE8xLH455PX8bXJVJ4jtPx+/h+4H6s85AqmListzFSfVl+jnF/XdY4jOTW+bQcjnzeXl7j4Tbdxv2Z20fqeX2Yp/X8Xszz1fP+ZZlYXFq+FSH6TZSRpzwjUaok1KRyDo3lvy/8+5rJNsiW7vf7P1K86CiFnvKCw44yzXWsU3yakyHJMFnGZ1zUcKg1kVaWV400yyiQUhy4TsGhl3IZ18kd51oRlUNPLnokcELBITXOOUFJ4ASfhHCeFFAuXU1BIRQIGsFIFcUdcmnspbRCIwVwtQVXW3CF/grgivuTVP1EquTwxJAFlypAXTyoC1AXoC5AXUgR2e0EV0OFBq4GrkY7DVwtdxJrT34ZJBjINlvZZivboI6BbMN1eBgGss2bbM2FrTP3v5Tf/8gMYSTvzZuZFlj2gWWBZYFlgWW5SSa7ZKZFE5uaaB6Wg7sO6h1wHXAdZDrgOrjr4a6Hux7uerjr4a6Hux7uepLHjEq469HIY0x+Oya/HZNHf48xeRhTgrp8UJegLkFdgroEdYmcCk0r0FWg4w+B+F2BroKZDcyskVBDZb1VWW9V1lBZQ2UtdTTXsU5/9O6Dbw0ImgdBA4IGBA0IGuhq4FsLm1roagHSAqTlBL6zRUILmwJsCrApwKYAmwJsCrApwKaAl7CDTQGNAgYQtgMI2wEEDCBgAEG+PvIhSZDdA7IDZAfIDpAdNHewqUfTHnQ96Hq+mskLnu7s8YrvxDsJPQIjl/xkd9wry2TVp66y2snblP8HSo16Pw==

**Comment by bigminigame** [comment]
Hi superdeadlysniper (nice nickname :p), thanks for your time, but I already had this solution in mind, and it makes the schematic 1 line larger, which is not what I wanted. Also, this problem is only affecting about half of the machines, and only make them lose 5% productivity, so the the trade of is not worth it in my opinion.

**Comment by XxsuperdeadlysniperxX** [comment]
You could replace the unloader with a conveyor or in someway use plastanium conveyors to your advantage _or_ using some other solution that i didn't mention

**Comment by XxsuperdeadlysniperxX** [comment]
Its the same hight that you had it at but i think i improved it it looks good too

bXNjaAF4nG2U3XKbMBCFFwRC4k+Q5AG46aUv+0DEpqkaG3kwJM079Qn6aJ3puLucjFNmcmFWyNrd8+0B6IEeYkrG/jRQdwzh+dId/fPQzd/7ufv6pfOXzo/dOVz87F+oOAyX/eTPsw8jUUXNxR/9Poy7/bTs/eNxoKafTmEaDjvefRnewkTucfKHp+Fjw/xYxv1aoV7GwzB9O4bX3VM/D1Sew+sw7S5hmfYDmWU8hp4PUH1+m/rZz8Pu5H/yfcvrfvTL6aOo5X9Pu5fgD6SnsMx8qli33ovlKD2Gw0BEv4giMhRHvM5JSSgQSlIxhyq7Xq8T/36vt3XGF+Lbq1K8cEQSGooTDi2plMtpI3ua/4n5GkcR73FtzaFIiVKV8aqUnhHVxHUiqZNwaHDXUmzWXF7HkBVDViwJCQcnJ2MkxJJgVyGcJwWUWZuvQSEkCCkprieypKORmgodFDoogKstuNqCK4ArgCvuH0nxO1Jcg+4ZMuFSCaiTG3UC6gTUCagTQCRchJWnEJNCTArcFLgpTqZykiiDbRoJGgka6vVWvd6q11CvoV5LOcNhVa/f1adcXxt9/Uvx9Y8Mi2T9v6cZ6LIbXQa6DHQZ6DJozuBphibZ2iTlrgYmG0AYQBhQG1AbVDAw2cJkC5MtTLYw2cJkC5MtTM5hskUHiw4WY7LbMdntmCzGZDEmK0+3PMcrdX6jzkGdgzoHdQ7NOTwt0LtA7wJ0BegKnCzgaQVPSySUSCghttyKLbdiS4gtIbbEq1ixhelnFrJ9FUCqG0gFkAogFUAqyKtgXw23asirIa8GTw2eGgk13HJwy8EtB7cc3HJwy8EtR/J54OTVLYcODh0cBuC2A3DbATgMwGEATgYgw9BGvmVaybdlBW5uwA2AGwA3AG6gv4FzLXS00NGCtAVpi5MtXp87oZPQIDB+QffkuFcUyapZu8qqlRcs/gdDqbUs

**Comment by bigminigame** [comment]
No, you still didn't improved it, it's still bigger than my schematic ^^
Here is a reminder : bXNjaAF4nEVQW26DMBAcP0GJ1PYI/egvHyVpq56jJyDGqlyBHRmImmv1Aj0a9eISQHh3Zjz7ADtoAemb3mL/4Tpn3NQ/XmoUw2ib3rXY1Ye6Pr48v7+9Yt/awUR3Hl3wQIHya/JmATqGabQRD03sQ7RtZYK/2GuIuD9F137ajbg7X2MzutFWvftOlnLyXWhaMg80QPCViZNxp84CeMLyCDoYBEuBrxQBSDCKKl9YDrYmnBJGZqJkThQZ/mvwrPL0CiJFRjIHBcFzZ567kcyLdQRxu5/+YBbVJkriwORSjCUpOed5/knfLyeoNsihseygwdIiihHBqZKmBsTLG58SjZLGoZDW/wOgjEJd

**Comment by XxsuperdeadlysniperxX** [comment]
But how is it bigger **_visible confusion_**

**Comment by XxsuperdeadlysniperxX** [comment]
Im still having issues with uploading images 🤔could be a network problem

**Comment by XxsuperdeadlysniperxX** [comment]
oH i see what i did wRoNg

**Comment by XxsuperdeadlysniperxX** [comment]
This is me: 🤦‍♀️

**Comment by XxsuperdeadlysniperxX** [comment]
Well in it's "original fix" it is as efficient as it is going to get

**Comment by XxsuperdeadlysniperxX** [comment]
If you change up the design it would be better but you must note the with the current input you are filling every single junction there so the resources will never stop flowing and pyratite needs:
1 coal
2 sand
2 lead

Plus the storage space of a junction

The spacing prevents the cross flow problem

And the underflow gates increase efficiency by forcing the flow to become layered improving speed and coverage

There's no way to avoid junctions from storing items without having a logic processor on every little junction (which would be a headache to make the logic work)

With the added fact that the crucible uses:

4 coal
6 sand
1 pyratite

Per 8 silicon every 1.5 seconds
