### ISSUE TITLE
ban some people from suggestions

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1575]
**Describe what you would like changed, and why.**

theres currently a lot of suggestions that are closed after a day or so, typically made by the same group of people (you know who you are)

bad suggestions are why theres 1k, and counting, open suggestions

**Describe the changes you want to propose. Include possible alternatives.**

A) ban them from making bad suggestions.
B) have purgatory so if they somehow make a well thought suggestion its published

**Comment by Anuken** [comment]
I don't really care. If a suggestion is bad, it's usually clear from the title, and I don't bother reading it. Neither should you.

**Comment by DeltaNedas** [comment]
hhhhh

**Comment by DeltaNedas** [comment]
at least make some users like quezler jannies that can force close suggestions

**Comment by BlueWolf3682** [comment]
*amazing*

**Comment by Anuken** [comment]
> at least make some users like quezler jannies that can force close suggestions

Somehow I'm not so sure that Quezler would want to waste his time closing bad suggestions.

**Comment by itcannotbe** [comment]
How about closing duplicates? Open issues are close to 1k now

**Comment by XxsuperdeadlysniperxX** [comment]
Thats mostly because theres a lot of people who play the game

**Comment by XxsuperdeadlysniperxX** [comment]
The game do have 1 million+ dowloads tho
