### ISSUE TITLE
bigger maps, command center, more turrets, turret upgrade, more enemies, allies and rare items and raid system?

### ISSUE THREAD

**Issue by roaringwriter13** [Anuken/Mindustry-Suggestions#1576]
**Describe the content or mechanics you are proposing.**
these Features are for the v6 of the game

1. when I mean bigger maps I mean it, like about 3x bigger, obviously their limitations in the rendering pipeline but that could fix with chunk loading or other methods if that a problem. it just sometimes everything is crowded plus it will play a big role for the next ideas.

2. Command centers sound basic but could change the game I'll explain it. remember when I said bigger maps this is why partly... Anyway Command centers will work like territories, bases, free turret, and a free projector or a low-quality mender. basically theirs a certain range like 50 tiles where the player is allowed to place their blocks but blocks like power nodes, Bridge conveyors, and conveyors aren't affected because of reasons. but when the command center is lost to the enemy it's either turns on you or you lose it completely(by that I mean it shuts down and you lose territories). but the command center doesn't get destroy instead you can reclaim it once you deal with its forces (just in case). so how do you reclaim it, well there will be tiers for the Command centers and each one will require a number of resources to get it up a running like 100 lead and 200 copper just an example. to get the command center you will have to research all of its tiers to get more range, obviously, you start with tier 1 that is free to place (the reason is because of how the ores generate and you don't want to be harsh on them) but the next command center will cost you. this will also be the same for the cores and they will have a bigger range (this will make mass drivers look useful not that they already are but more useful). lastly, the Command centers aren't affected by the limited block placement so they can be freely (also make it to where modded blocks can or can't depend on this feature). by adding this conquering will feel more satisfied.

3. More turrets, I ran through the suggestions and haven't found this idea yet... anyway more turrets could benefit the game and give it more variety. 

4. turret upgrades, I am aware "TNT331" also said this idea but my is different I promise, anyways turret upgrade would work differently in my world. you see it wouldn't be simple as clicking a turret and getting the resources then upgrading it. so what I
propose is upgrade chips or modules that can be placed in any turret so that it can upgrade its rate of fire, damage or range to both upgrades or all by points or percentage and that each turret can hold 2 (but in mods, this can be change). How to get the upgrade or upgrades, it simple, just make them by gathering the materials and research the module you want then research the module builder and build the module. those are the steps. (it plain I know)

5. more enemies, that it just more enemies that's all.

6. allies and rare items and raid system?, this feature is inspired by the gold mod. by far this could be idea one and it also supports my other ideas. so basically an allied faction will be stationed around the planet fighting off the robot enemies I guess. you can choose to help them or destroy them. (helping them) you can help them by trading resources and rare items(that may or may not help you). (destroy them [don't do it]) you can be an enemy to them by raiding their bases all around the planet. how will the raiding system work? well, build the newest block in the game the "unit launch pad" basically you store your units to the space station or where ever your resources go when you launchpad them. Anyway now that their store them now you can go raid someone the allied faction or the enemy faction bases. how would it work well it like playing mindustry but instead of defending you are attacking from where the enemy spawns. okay, the rare items basically they can help research other kinds of tech. the way you get them is by savaging rare blocks, turrets, etc.

also "AESIR-Foopy" made the Suggestion of a command center idea but it was a different idea than mine.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it's all up there

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. Chunk based map loading/processing has been tried before but the performance was significantly worse and leads to many errors

**Comment by joshuaptfan** [comment]
If you want to be taken seriously, I suggest you focus your effort on 1 suggestion at a time. Nobody likes to read a wall of text, and even less so when poor grammar and punctuation make comprehension take more effort. Vague, low effort suggestions like "more <thing>" also give people nothing to work with.

> upgrade chips or modules that can be placed in any turret so that it can upgrade its rate of fire, damage or range

That's what different ammo types, coolants, and overdrive projectors already are.

**Comment by itcannotbe** [comment]
4. See readme.md

A few things you shouldn't suggest
These have been proposed many times already, and I won't be adding them.

Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

And yes, starcraft-terran-like building upgrades haa been also.suggested before

**Comment by GreyMario** [comment]
> turret upgrades, I am aware "TNT331" also said this idea but my is different I promise, anyways turret upgrade would work differently in my world. you see it wouldn't be simple as clicking a turret and getting the resources then upgrading it. so what I
propose is upgrade chips or modules that can be placed in any turret so that it can upgrade its rate of fire, damage or range to both upgrades or all by points or percentage and that each turret can hold 2 (but in mods, this can be change). How to get the upgrade or upgrades, it simple, just make them by gathering the materials and research the module you want then research the module builder and build the module. those are the steps. (it plain I know)

> I have read `README.MD` to make sure my idea is not listed under the "A few things you shouldn't suggest" category

![](https://puu.sh/GXDis.png)

_You are proposing block configuration._

**Comment by itcannotbe** [comment]
3. The only reason why you don't find this suggestion is people actually take time to suggest actual turret ideas.

**Comment by itcannotbe** [comment]
5. Ah yes. 30+ units are not enough enemies for you?


Also, the only reason why you don't find this suggestion is people actually take time to suggest actual unit ideas.

**Comment by itcannotbe** [comment]
2. People make use of the logic system to actual control units in advance manner.

**Comment by itcannotbe** [comment]
For the love of everyones sanity, why did all of your suggestions as bundled up in one issue?

Discussions for this would be all over the place.

**Comment by Anuken** [comment]
> more turrets
> more enemies

incredible. nobody has ever even considered suggesting More Turrets or More Enemies before. this is a revelation. I would never have thought of adding More Turrets myself. this idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Turrets immediately.

**Comment by BlueWolf3682** [comment]
i want to salute this but i also dont want to anger anuke by saluting this
