### ISSUE TITLE
Discord: Archive #mindustry channel.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#1578]
**Describe what you would like changed, and why.**
Title.
'Cause it's a useless channel, since no one is using it for it's intended purpose.
95% of the things discussed there is off-topic stuff anyways and #social exists.

**Describe the changes you want to propose. Include possible alternatives.**
Close and archive.

**Comment by GreyMario** [comment]
Possible alternatives: Moderate the damn chann--
![](https://puu.sh/GXFTk.png)
--never mind.

**Comment by itcannotbe** [comment]
Breaking news: Greymario is a discord member.

**Comment by Bohaska** [comment]
> Breaking news: Greymario is a discord member.

So what?

**Comment by RebornTrack970** [comment]
**_Approved_**

**Comment by ifritdiezel** [comment]
The only purpose of #mindustry is to keep crowds of newcomers out of #social. It's pretty good at that

**Comment by GreyMario** [comment]
I'm pretty sure that members of the community are outright leaving the server because of a lack of moderat--
![](https://puu.sh/GXFTk.png)
--never mind.

**Comment by itcannotbe** [comment]
> I'm pretty sure that members of the community are outright leaving the server because of a lack of moderat--
> ![](https://camo.githubusercontent.com/bf5934e1d6b8f2ba36f7ddf9f3a8a75eadcace339ed4d6753dc4e1db52f20195/68747470733a2f2f7075752e73682f475846546b2e706e67)
> --never mind.

Actually most people who play in servers don't even bother joining the official discord server.

**Comment by ifritdiezel** [comment]
Maybe it's actually worth to ramp up server moder-

jk jk.
keep locking channels down!
spanish people must love having no place to talk! screenshots channel wasn't that useful after all. and development? who cares about development!

**Comment by itcannotbe** [comment]
How do you even moderate a channel in a laguage you do not speak in the first place?

**Comment by itcannotbe** [comment]
Also in the long run. Shutting down channel is more effective in keeping the community in check than actually moderating the channel

**Comment by ifritdiezel** [comment]
Of course! No channels — no channel misuse. Archive everything other than info channels. 

Might also delete the whole server, there's github for development.

**Comment by G-mage** [comment]
yeah, you better leave it open, i wonder how will anuke react to this

**Comment by Gdeft** [comment]
You can just mute the channel and enable **Hide Muted Channels**, *or alternatively you can just not care about it at all.*

**Comment by itcannotbe** [comment]
Kids be like: BuT sOcIaL iS dEaD

**Comment by GreyMario** [comment]
Never mind that #social gets more actually spammy traffic than #mindustry does on average. It's never dead. Ten year olds just don't like being told to use their inside voice.

**Comment by aFuschia** [comment]
a

**Comment by GreyMario** [comment]
![Screenshot_20201215-010153_Discord](https://user-images.githubusercontent.com/502797/102193682-3e287f00-3e71-11eb-9c0b-9328126b626e.jpg)
"Nothing to moderate here" 2: Electric Boogaloo

You can't just nuke the spanish channel and then decide you're not going to enforce "speak English in main channels" and "don't spam _CUM_ using the regional indicator emojis".

So... Yeah. Just shut the whole damn server down, if there's only _one_ person in moderation who even gives enough of a fuck to take their job seriously.

**Comment by itcannotbe** [comment]
Being a mod is not a job. Mods don't even get paid to do it.

**Comment by GreyMario** [comment]
> Being a mod is not a job. Mods don't even get paid to do it.

This isn't even remotely close to a valid "argument".

You accepted the role, you should accept and meet the responsibility that comes with it. If you're not meeting that responsibility, _especially when the community asks you to_ and the evidence is right there and you take the time to just add some stupid reacts and then go "hmm nah don't care" and you still have that role, you are reflecting badly on yourself _and_ the leader of the community.

The responsibility you accepted was to keep the chaos to a minimum, not go "haha I have a purple name whee" and munch on a bag of Doritos while watching the server fall into anarchy.

**Comment by itcannotbe** [comment]
You can't force people to do it. Since there isn't any compensation. It's a onerous agreement to say the least.

**Comment by ifritdiezel** [comment]
there are people who _want_ to help the community

**Comment by ifritdiezel** [comment]
the situation is so bad it's even discussed in other places
in at least 3 of other communities i'm in mindustry discord is known as a half abandoned mess

**Comment by BlueWolf3682** [comment]
if you archive mindustry then we will have more kids in modding-general and nobody here want that ever for any reason at all

**Comment by itcannotbe** [comment]
Why modding-general?

**Comment by Anuken** [comment]
> 'Cause it's a useless channel, since no one is using it for it's intended purpose.

Every time I check it, there's Mindustry-related discussion at (or near) the bottom. Right now, for example. 

Point to specific examples of bad behavior that should be eliminated.

**Comment by GreyMario** [comment]
Try checking in the neighborhood of when anyone tries to ping Quezler, Epowerj, Prosta, what have you.

We know when bad behavior is happening, and we try to get someone to deal with it. Just because it's not right there at the bottom when you click the channel to make ping notifs go away doesn't mean it's not happening.

We're also learning who is reliable and _when_ they're reliable. And some of your staff have basically admitted to refusing to be reliable (_cough_ Epowerj) so we've come to the point where we don't even try to catch their attention.

**Comment by Anuken** [comment]
> Try checking in the neighborhood of when anyone tries to ping Quezler, Epowerj, Prosta, what have you.

This is harder than it sounds, since the people causing trouble usually get banned within 24 hours and their post history is deleted. I did find some nastyness from 3+ days ago, though.

> We're also learning who is reliable and when they're reliable. And some of your staff have basically admitted to refusing to be reliable (cough Epowerj) so we've come to the point where we don't even try to catch their attention.

TCEO and Epowerj are busy now, so I don't expect them to moderate at all. I haven't removed them yet because an inactive moderator is better than nothing at all. If people start trying to ping them instead of other moderators, however...

---

Closing `#mindustry` is out of the question. I could try finding some moderators, but there are few active users that seem promising. Opening mod applications is also an option, but I'd rather not deal with a flood of applications unless absolutely necessary.

**Comment by GreyMario** [comment]
> > Try checking in the neighborhood of when anyone tries to ping Quezler, Epowerj, Prosta, what have you.
> 
> This is harder than it sounds, since the people causing trouble usually get banned within 24 hours and their post history is deleted. I did find some nastyness from 3+ days ago, though

Understandable, given how poorly Discord handles audits by default. I should pick through recent postings of known trouble users, but _right now (as of this posting)_ I don't have the time to sit down and figure out who, what, and when.

> > We're also learning who is reliable and when they're reliable. And some of your staff have basically admitted to refusing to be reliable (cough Epowerj) so we've come to the point where we don't even try to catch their attention.
> 
> TCEO and Epowerj are busy now, so I don't expect them to moderate at all. I haven't removed them yet because an inactive moderator is better than nothing at all. If people start trying to ping them instead of other moderators, however...

The community tries to shoot for "whoever's online at the time" and, well, only goes for Prosta/Quezler if they're not logged in if the trouble gets serious.

> Closing `#mindustry` is out of the question.

I'm pretty sure this is ultimately memeing about how #development got canned (and the events leading up to).

> I could try finding some moderators, but there are few active users that seem promising. Opening mod applications is also an option, but I'd rather not deal with a flood of applications unless absolutely necessary.

_Applications_ are a nasty process, I'll give you that. 💦

**Comment by itcannotbe** [comment]
You'll get better people by choosing them. Cause most of the moderators I been with on other servers chosen through applications just vanish in 2 weeks and doesn't do any moderation at all.

**Comment by itcannotbe** [comment]
> > 'Cause it's a useless channel, since no one is using it for it's intended purpose.
> 
> Every time I check it, there's Mindustry-related discussion at (or near) the bottom. Right now, for example.
> 
> Point to specific examples of bad behavior that should be eliminated.

Everything in between.

**Comment by itcannotbe** [comment]
> > 'Cause it's a useless channel, since no one is using it for it's intended purpose.
> 
> Every time I check it, there's Mindustry-related discussion at (or near) the bottom. Right now, for example.
> 
> Point to specific examples of bad behavior that should be eliminated.

Here's a marker.

https://discord.com/channels/391020510269669376/391020510269669378/788661642275323945

**Comment by Legomonster33** [comment]
> Cause it's a useless channel, since no one is using it for it's intended purpose.
95% of the things discussed there is off-topic stuff anyways

that is a very good reason for it to stick around
it keeps the off-topic non #social chat out of other channels,
more channels is typically better

**Comment by BlueWolf3682** [comment]
> Why modding-general?
some think its to speak to moderators, others are developing mods, and a *lot* of people actually dont know what #social does, so theyre going to scroll around the chats and find an active one... or theyre actually going to try making a mod and though some are good modder candidates some... well... no.

**Comment by BlueWolf3682** [comment]
> You'll get better people by choosing them. Cause most of the moderators I been with on other servers chosen through applications just vanish in 2 weeks and doesn't do any moderation at all.

*one of the reasons i openly halt or protest application methods*
(the other being that you dont know them personally but whatever)

**Comment by itcannotbe** [comment]
> > Why modding-general?
> 
> some think its to speak to moderators, others are developing mods, and a _lot_ of people actually dont know what #social does, so theyre going to scroll around the chats and find an active one... or theyre actually going to try making a mod and though some are good modder candidates some... well... no.

Rename to Game-Modification-General XD

**Comment by BlueWolf3682** [comment]
now how would i change channel names? 🤔

**Comment by itcannotbe** [comment]
> now how would i change channel names? 🤔

Not you, It's up to the cat with the red hat.

**Comment by BlueWolf3682** [comment]
amazing
