### ISSUE TITLE
EMP emitters

### ISSUE THREAD

**Issue by SuperficialIntelligence** [Anuken/Mindustry-Suggestions#1579]
**Describe the content or mechanics you are proposing.**
Buildings/turrets dedicated to disabling nearby electricity powered buildings. Plastinium walls can be used to shield defenses from the effects of this building. Will probably require surge alloy to build.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This is intended to prevent the enemy from using lancers and arcs to destroy your defenses. And to disable exposed enemy defenses that rely on electricity. . This can also be used to economically damage opponents by disabling their electric powered buildings.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
For as much as I hate new weapon ideas, this is one I actually like. I feel the colour scheme should be similar to parallaxes and (insert other support weapon) so imo it would be white and some other colour.

**Comment by the-kido** [comment]
![Uploading emp.png…]()

**Comment by the-kido** [comment]
![Shorter lines](https://user-images.githubusercontent.com/63456333/102234947-cafa2980-3ebf-11eb-9e48-7c2803fd3e41.png)
Possible sprite?

**Comment by the-kido** [comment]
![possible sprite](https://user-images.githubusercontent.com/63456333/102235137-05fc5d00-3ec0-11eb-9f01-e2f4d1b94838.png)
Possible sprite?

**Comment by SecretMink** [comment]
perhaps this functionality could be added into the force projector, and only happens when it is phase boosted. Any enemy building inside the force field has its electric capabilities disabled.

**Comment by SuperficialIntelligence** [comment]
> perhaps this functionality could be added into the force projector, and only happens when it is phase boosted. Any enemy building inside the force field has its electric capabilities disabled.

The force projector could definitely use a buff but force projectors are known to fall victim to piercing weapons which makes them weak against lancers and arcs which the whole point of this new mechanic is to stop lancers and arcs. Also force projectors overheat when the force field is damaged which will disable all of it's functionality therefore disabling it's disabling ability. The force projector's range is disappointing if you plan to use it to disable enemy buildings. But I think this would be a great mid game secondary ability to make the force projector more useful. But a dedicated turret/building would probably have more powerful effects and longer range.

**Comment by SuperficialIntelligence** [comment]
> Possible sprite?
> ![finalized](https://user-images.githubusercontent.com/63456333/102243347-12d17e80-3ec9-11eb-885d-6d9e430a2440.png)

Looks nice, but the green might make people mistaken it for a mending turret. Maybe make it yellow?

**Comment by XxsuperdeadlysniperxX** [comment]
> perhaps this functionality could be added into the force projector, and only happens when it is phase boosted. Any enemy building inside the force field has its electric capabilities disabled.

Anuke will not merge blocks together aka combined buildings

**Comment by SuperficialIntelligence** [comment]
> > perhaps this functionality could be added into the force projector, and only happens when it is phase boosted. Any enemy building inside the force field has its electric capabilities disabled.
> > anuke: do not suggest Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills
> 
> Anuke will not merge blocks together aka combined buildings

What they meant was instead of adding a new block they could just add an extra ability to the force projector. It wouldn't be considered merging blocks if there was no block that had that functionality.

**Comment by XxsuperdeadlysniperxX** [comment]
But wouldn't it be then considered a side configuration?

**Comment by SuperficialIntelligence** [comment]
> But wouldn't it be then considered a side configuration?

Think of it like using different types of ammo for turrets. If the force projector is given a certain item it would gain an ability based on the item.

**Comment by XxsuperdeadlysniperxX** [comment]
Now that way might actually be viable

**Comment by SavageCreeper64** [comment]
This is a bit OP but I like the idea, though there is a few things I would change
1. The EMP would require massive amounts of power and only lasts 10 seconds
2. The EMP cannot destroy force projectors but can damage them a bit
3. The EMP will have a range meaning its not endless but the range will still be extremely big
4. The EMP will also be able to disable units that use energy weapons temporarily or maybe even disable processor or processor controlled units.
