### ISSUE TITLE
Show resources launched

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#158]
**Describe the content or mechanics you are proposing.**

When starting a campaign map, save the resource count.
When looking in the tech tree or game over screen, show resources launched with current - old.
I propose for it to be in yellow like the launch pad.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would make it easier to see how many resources you got in total from a zone.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. (havent checked 6.0)

**Comment by zethnest** [comment]
You mean the total profit and loss from the campaign map?

**Comment by Rybadour** [comment]
What's the purpose of this change? Why would we need to know how much we made in the past?

**Comment by DeltaNedas** [comment]
no longer relevant
