### ISSUE TITLE
Suggestion to add a "Unit Production Cost Multiplier" setting in the rules for custom maps.

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry-Suggestions#1580]
**Describe the content or mechanics you are proposing.**
To add a "Unit Production Cost Multiplier" setting for custom maps.

(Not to be confused with "Build Cost Multiplier" which exists but does not affect units.)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Being able to set a low build cost multiplier will help a lot in large custom attack maps:
- Sending large waves of units to crash into the enemy base is just super fun 😄
- Tier 1 and Tier 2 units are bad and you need a lot to make even a bit of progress in larger enemy bases. You can only make T3 when you have access to Thorium.
- High Tier units are even more expensive.
- In multiplayer attack maps, people are often fighting over units that spawn, this setting can help to give units to more people.

The "Unit Production Speed Multiplier" setting helps but is not enough on its own as resources are usually a much bigger issue than speed.

Thank you for reading.

Proof that it doesn't exist yet so you don't need to check it yourself:
![20201215223625_1](https://user-images.githubusercontent.com/75215867/102279069-1d246480-3f2b-11eb-9383-637dcdc86c6f.jpg)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Sending large waves of units to crash into the enemy base is just super fun 😄

Unit Limit: No.

**Comment by NoExit4U** [comment]
> > Sending large waves of units to crash into the enemy base is just super fun 😄
> 
> Unit Limit: No.

Custom maps can add more player cores which increases the unit limit.

Even with a low unit limit you still won't have to wait as long until your units are maxed = more fun :).
