### ISSUE TITLE
Bigger and more complex sorters

### ISSUE THREAD

**Issue by Bladeking2020** [Anuken/Mindustry-Suggestions#1581]
The idea of the new sorter that I'm suggesting is to have a sorter that sorts 2 different materials in the left and right side of the sorter, and if the material that isn't being sorted is sent foward.

The Way it can help people is by allow for more smaller devices that can deal with the amount of materials that machines like the separator and dissembler outputs. as with the sorters that we have now it for the example that I'm using, it takes 3 sorters at minimum to deal with one of them and it takes 5 if you want to combine both of them into one sorter. with this device that i'm suggesting it would allow you to make one that only takes two that would work for both. It really isn't a huge game changer, it just makes a very few situations more easy to deal with.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Pretty sure that there is something in the read me that said something about.....

###Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

And you just need 2 sorter and an underflow to fix this.

**Comment by GreyMario** [comment]
Now, see, I _like_ this conceptually, but it still falls under the "additional configuration" no-no. Pretty much all blocks have a maximum of one thing you can configure, if they have anything at all.
