### ISSUE TITLE
Campaign Balance

### ISSUE THREAD

**Issue by Marchthemonth** [Anuken/Mindustry-Suggestions#1582]
I've been playing Mindustry for over a year now, and v6 is very exciting. I'm entirely a PvE (campaign) player, just to share where my perspective is.
Although with the campaign, I greatly enjoy/tolerate the new shared resource mechanism, the campaign (so far) is way too easy. I just finished up Nuclear Complex, and it wasn't that difficult at all to do. Of course, being a v5 player, I knew to upgrade as much as I could before progressing. Even still, there was tremendous challenge about the successive and increasingly difficult waves. It made it a strategic choice when to launch.
Obviously, "launching" in the v5 sense is definitely gone and I'm open to how this new mechanism works, and generally for the new progression. But I'm incentivized to get through the waves then just acquire as much materials as possible. And to me, the worst part is that I have no fear of additional waves. It's way too easy and borderline boring that I have no threat.
Of course, I have a few other maps to get through, but it doesn't yet seem that there's a real threat on the horizon.
nothing to really challenge me with these new weapons or awesome units.

The real "change" I'm expressing here is to have a "threat" during the campaign. In v5, it was the ever growing invading forces.

**Comment by itcannotbe** [comment]
Actually Captured Sectors can get attacked plus you can use launch pads unlocked later in the campaign to send resources from captured sectors to sectors of your choosing.

**Comment by BlueWolf3682** [comment]
i totally agree with this guy, campaign remains too easy

**Comment by Marchthemonth** [comment]
> Actually Captured Sectors can get attacked plus you can use launch pads unlocked later in the campaign to send resources from captured sectors to sectors of your choosing.

Indeed they do, but that's nothing compared to the steady, incremental increase of units attacking a base in v5.

**Comment by itcannotbe** [comment]
Actually in v5 even though waves don't end, they don't progress beyond a certain point unlike v3.x

**Comment by Marchthemonth** [comment]
> Actually in v5 even though waves don't end, they don't progress beyond a certain point unlike v3.x

You seem to be squabbling over details simply to argue. Sure, quite a few of the campaign maps had a "cap", but Nuclear Complex and Desolate Rift were pretty challenging with boss waves of increasing amounts.
My point was that there is no threat like that at all in v6, currently.

**Comment by itcannotbe** [comment]
Only units above T2 pose challenge for early game turrets to say the least.

**Comment by SuperficialIntelligence** [comment]
I think to solve this the enemy should be able to capture sectors as well so that you have to expand fast or the enemy will become overwhelming.

**Comment by Arackulele** [comment]
> I think to solve this the enemy should be able to capture sectors as well so that you have to expand fast or the enemy will become overwhelming.

that idea sounds interesting,but i think itd be too overwhelking for new players also the auto generated enemy bases are well lacking in multiple aspects.
I think itd be better to have the nemy be able to attack sectors far away fom their bases by getting units through other sectors,basically if a sector is near an enemy base on the left of it the enemy would sort of ''go'' through the sectors til it reaches one of your bases.
i think with a system sort of like that theres still a big reward for destroying nearby enemy bases and theres a steady threat until you have captured everything.
