### ISSUE TITLE
conveyor and gate throughput is different

### ISSUE THREAD

**Issue by flololody** [Anuken/Mindustry-Suggestions#1584]
**
hi, I noticed that the throughput of the redundant gate or redundant gateway when turning on the filled titanium conveyor is kept at around 10.5/second, and the throughput of the conveyor fluctuates at a slightly lower throughput, which causes things to be thrown sideways (at random intervals, but quite often) even when the front conveyor is passing freely. I don't know if this is a bug, so I'm writing here, thank you! <3
**

**Comment by DeltaNedas** [comment]
why did you remove the template
