### ISSUE TITLE
Units with long range should attempt to avoid firing range of turrets if possible.

### ISSUE THREAD

**Issue by SuperficialIntelligence** [Anuken/Mindustry-Suggestions#1585]
**Describe what you would like changed, and why.**
Units with long range must not run straight into short range turrets. It would make more sense for them to fire from a distance than press their guns against the wall in an attempt to break it. And this will make enemies more challenging as you would need longer ranged turrets to outrange the enemy units.

**Describe the changes you want to propose. Include possible alternatives.**
Make units with long or medium range weapons attempt to avoid turret range. Make the units not attempt walk straight into the walls and actually make use of their ranged weapons.

**Comment by Ruichka** [comment]
Zeniths are firing from distance.
If you apply such AI to every unit, then Ground Zero would be impossible to pass, as daggers have longer range than duos.
Also, Omura outranges Foreshadow.

**Comment by SuperficialIntelligence** [comment]
Oh ok, Did not know the Omura has the longest range.

**Comment by T1murik** [comment]
must be applied to corvus

**Comment by Anuken** [comment]
This makes waves annoyingly difficult. AI Corvus units would be nearly impossible to defeat without Foreshadows or special strike units.
