### ISSUE TITLE
New feature, About very own custom vehicle buildable. as like own custom

### ISSUE THREAD

**Issue by TigerustEarth38** [Anuken/Mindustry-Suggestions#1586]
**Describe the content or mechanics you are proposing.**
----------------------------------------------------------------------------------------------------------------------------------------------
Hello there.

I have some idea about Module in own premises of airplane / vehicle / on the sea vehicle.

Own custom design from factory. as I can recreate on Reaper with Rippe on one made like this, it would be cool if that added with turret and hull on your own custom and each plate in its own shape, but determine the cost of building where it was placed. and there is also limit of space. i hope there will be some more added to biggest factory or something home Factory, whatever.

Anuke / everyone, Have great day. And a very happy new year !!

Ps. i am welles worst at english language and also lack words to understand. Pm I agree if you need to understand something more, and yes I had quite a lot of idea to put on Mindustry! that is my first time suggestion.

----------------------------------------------------------------------------------------------------------------------------------------------
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
i had a very broken 5.0 mod that would allow building your own units, but 1. never made it functional outside of conveyors 2. didnt port to 6.0 (yet)

**Comment by SavageCreeper64** [comment]
This is a good idea concept but you might want to consider this:
What if you have a new factory called the Unit Adjuster and you put any unit into the unit adjuster and you can adjust it. Adjustments such as different weapons, different armor and etc. 
Of course this will all cost materials such as titanium armor would require titanium.

**Comment by Kyllingene** [comment]
> This is a good idea concept but you might want to consider this:
What if you have a new factory called the Unit Adjuster and you put any unit into the unit adjuster and you can adjust it. Adjustments such as different weapons, different armor and etc.
Of course this will all cost materials such as titanium armor would require titanium.

Very close to the last line of the README.md. I hope this doesn't get added...

**Comment by itcannotbe** [comment]
> > This is a good idea concept but you might want to consider this:
> > What if you have a new factory called the Unit Adjuster and you put any unit into the unit adjuster and you can adjust it. Adjustments such as different weapons, different armor and etc.
> > Of course this will all cost materials such as titanium armor would require titanium.
> 
> Very close to the last line of the README.md. I hope this doesn't get added...

This is proof that people just put X in the - [ ]

**Comment by Kyllingene** [comment]
> This is proof that people just put X in the - [ ]

The line addresses *block* config, not *unit* config.

And for clarification, I was stating that I hope it doesn't get added to the README.md. I *do* hope it makes it into the game.

**Comment by itcannotbe** [comment]
So how are you going to make custom units without the proposed block not having additional configurations?

**Comment by Kyllingene** [comment]
> So how are you going to make custom units without the proposed block not having additional configurations?

True. So in the end, this requires something outlawed. I don't blame you for not thinking about this, but it is sadly impossible to get implemented at the moment.
