### ISSUE TITLE
Multidirectional bridges/conduits

### ISSUE THREAD

**Issue by wtfisgithub** [Anuken/Mindustry-Suggestions#1589]
Allow bridges and conduits to transport items within a set radius.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I feel that this ability will allow for more flexibility in schematics as well as making some of the more constrained maps easier to maneuver resources through until mass distributors can be built. 

Additional functionality could be automatically placing and linking bridges/conveyors in build mode similar to how power nodes can automatically be spaced in build mode now.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Legomonster33** [comment]
that is op beyond belief

**Comment by itcannotbe** [comment]
This is op beyond belief (2)

**Comment by itcannotbe** [comment]
[Refer to #185] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by wtfisgithub** [comment]
OP beyond belief in what way? Instead of going only horizontally and vertically it now go diagonally within a 3 tile radius for regular and a ~10 unit radius for phase? Plus if something is OP you balance it with resource/power costs. This is essentially the functionality of the mass driver already, just at a smaller scale.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/185#issuecomment-631595492

**Comment by Legomonster33** [comment]
> OP beyond belief in what way? Instead of going only horizontally and vertically it now go diagonally within a 3 tile radius for regular and a ~10 unit radius for phase? Plus if something is OP you balance it with resource/power costs. This is essentially the functionality of the mass driver already, just at a smaller scale.

It invalidates any other means of item transport
It leads to bridge spaghetti beyond belief
Other problems
