### ISSUE TITLE
.

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1590]
Killing suggestion because lol

**Comment by XxsuperdeadlysniperxX** [comment]
And i did do a long extensive search and say 0 meantion of phase weaver balancing

**Comment by itcannotbe** [comment]
But the inputs for the phase weaver wasn't changed since they have been first introduced...........

**Comment by the-kido** [comment]
This is untrue as a watered airblast makes 7 sand a second (more than that but for the benefit of the doubt). Phase weavers need 5 sand a second (10 per two seconds). I have a feeling you overdrive the phase factory as well because what you are describing does NOT add up

**Comment by GreyMario** [comment]
I have a feeling that these exaggerations are typical of children.

**Comment by notrealn** [comment]
theres this little known gamer trick called "getting good", you should try it

everyone else is fine with phase needing a million sand, its supposed to be hard to get

**Comment by NajimiOsana** [comment]
There's a reason why Phase is marked as "Expensive", and we like to keep it that way

**Comment by XxsuperdeadlysniperxX** [comment]
Gray mario plz stop assuming my age when you don't even know me

**Comment by XxsuperdeadlysniperxX** [comment]
But im not running 1 phase weaver im running 5

**Comment by XxsuperdeadlysniperxX** [comment]
@GreyMario would you like it if i started assuming your age? don't assume some guy on the internet you never met in you entire existence is three just because the way he types english it seems like your more of unhelpful character rather than helpful

**Comment by XxsuperdeadlysniperxX** [comment]
> There's a reason why Phase is marked as "Expensive", and we like to keep it that way

I gave options if he wants to any of them he can if doesn't i'll just close the issue and move on

**Comment by XxsuperdeadlysniperxX** [comment]
I will not close this because of the comments

**Comment by GreyMario** [comment]
> But im not running 1 phase weaver im running 5

So...

Make five drills???

_This isn't that damn hard._

**Comment by XxsuperdeadlysniperxX** [comment]
-_-

**Comment by XxsuperdeadlysniperxX** [comment]
Its not possible to make _5 drills_ if a sector is sand poor

**Comment by GreyMario** [comment]
Then...

Why are you trying to make Phase Fabric _en masse_ in it?

Import it from somewhere else with a Launch Pad.

**Comment by itcannotbe** [comment]
> But the inputs for the phase weaver hasn't been changed since they have been first introduced...........

^

**Comment by XxsuperdeadlysniperxX** [comment]
> Then...
> 
> Why are you trying to make Phase Fabric _en masse_ in it?
> 
> Import it from somewhere else with a Launch Pad.

To import the phase you to _make_ the phase

**Comment by XxsuperdeadlysniperxX** [comment]
> > But the inputs for the phase weaver hasn't been changed since they have been first introduced...........
> 
> ^

I give options he can make it easier on himself or not implement at all it simple enough

**Comment by GreyMario** [comment]
> > Then...
> > Why are you trying to make Phase Fabric _en masse_ in it?
> > Import it from somewhere else with a Launch Pad.
> 
> To import the phase you to _make_ the phase

Tar Fields. You would have seen there's a lot of sand in there, had you not cheated your way from Fungal Pass to Planetary Launch Terminal.

**Comment by XxsuperdeadlysniperxX** [comment]
And phase is end game and an updated version would help i provide he choose or if he doesn't think its a good idea to do anything or may think is too hard or just doesn't want to implement a new block i don't care the only person that decides if he cares is the developer aka anuke

**Comment by XxsuperdeadlysniperxX** [comment]
> > > Then...
> > > Why are you trying to make Phase Fabric _en masse_ in it?
> > > Import it from somewhere else with a Launch Pad.
> > 
> > To import the phase you to _make_ the phase
> 
> Tar Fields. You would have seen there's a lot of sand in there, had you not cheated your way from Fungal Pass to Planetary Launch Terminal.

How rude assuming i cheated!!!! I do games legit gray mario i do not cheat

**Comment by Geogamer2019** [comment]
Well im sorry mate but i think you miss the point
First off i have to agree with Grey here, he does try to give you tips and told you that absolutely no one cares how much phase costs. I dont personally use much of phase, i always launch with 13k but i end up using less than 2k, so its not really a needish material.
Second off, why not use a sector with high sand and thorium (launched or mined) as for a phase factory? Im pretty sure it wont hurt to try.
You sound like you either make phase in sectors which are under attack and almost lost, and you need phase instantly to save it, or you just cheated your way through the campaign. Maybe you didnt even bother trying to see how to get more phase.
Why 5 phase weavers in a sector with low sand mate, it dosent make sense, it seems like you did it for fun, got mad because it barely gives you phase and then decided to make this issue just for complaining that you cant get phase. Please get better at the game.
Also, you pretty much started a drama and you will probably complain about us start drama just because you dont want tips from other players?

Ah yes, long messages

**Comment by XxsuperdeadlysniperxX** [comment]
I made in nuclear complex because theres was unused thorium there why does people think i cheated 
#1 im still offended that i was assumed to be a child
#2 people assumes i cheated which _again_ i do not cheat nor do i condon cheating
#3 im not the only one with either bad ideas and im not the only one that has bad ideas
#4 plz don't do #1
#5 i will close the suggestion cuz no one cares **_once again im not the only one_** plus i can easily ignore this cuz 0 notifications coming through

**Comment by Arackulele** [comment]
reading this hurt me mentally and physically

**Comment by Geogamer2019** [comment]
my attempt in making him stop was succesful... for now

**Comment by notrealn** [comment]
btw i have like 8 phase weavers in nuke prod sector. im turning a bunch of scrap into sand, which gives me more than enough to fuel them. in fact, my bottleneck is that im running out of thorium, not sand

**Comment by the-kido** [comment]
> But im not running 1 phase weaver im running 5

Well, then you'd need 5 watered laser drills, not 2 watered overdriven airblast drills. Either way, you're overexaggerating the amount it needs. Also, phase is supposed to one of the hardest resources to get. There is a reason you cant build that costs more than 600 phase.

**Comment by the-kido** [comment]
I also very much dislike the fact you are trying to shun away criticism for this idea by saying "no toxicity". If you make a suggestion be prepared for people to dislike it. Although i do agree sometimes people _can_ be ruder than they need to be saying "no toxicity" is you basically saying "i cannot handle criticism".
