### ISSUE TITLE
Armored power nodes, vaults and more 

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#1591]
**Describe the content or mechanics you are proposing.**
A bunch of armored version for power nodes, router, junction(and others), vaults with at least 4x health

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
These blocks are important and too easy to get destroyed

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
They're...

Easy to destroy...

By design...

**Comment by PlanetOrca** [comment]
have you considered defending them?

**Comment by userlol2** [comment]
Of course we need to defend em,but i mean,when u kill a flying unit,itsself will crush to the ground and theres no way to stop flying unit fall damage ,thats quite annoying

**Comment by notrealn** [comment]
1. force projector
2. wave can push away dead plane corpses
