### ISSUE TITLE
Highlight blocks red (or an exclamation mark) if they are in the annihilation zone.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1592]
**Describe the content or mechanics you are proposing.**

Show blocks that will get destroyed by the annihilation zone because there is a thin line between what can be in the zone and what can't. This indicator will show that thin line. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Being able to see if the block I will be constructing will be destroyed is just a convenience. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
I makes making a defense easier for sure so you don't have to be in on near your wall to see the dropzone

**Comment by catatagun** [comment]
Yes

**Comment by the-kido** [comment]
is got 60 likes but I guess it's not enough to warrant this being implemented.

**Comment by joshuaptfan** [comment]
Anuke may not do it because he's got other priorities than little QoL stuff, but someone else might.
