### ISSUE TITLE
Disable Shake Option

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry-Suggestions#1593]
**Describe the content or mechanics you are proposing.**
"Disable shake" Option.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When your are playing next to a big turret or something that can shake your screen, it's painful to play, mainly on mobile, because your touches are not very Accurated, you touch were is not to touch, so a button that can disable shake will be great.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
> [nope] I am familiar with all the content already in the game

turn screen shake to 0% in settings, this already exists.

**Comment by rodrigolitzius** [comment]
In V5 this did not exist i think, i didn't see the option, sorry

**Comment by Anuken** [comment]
It has existed in basically every version.

**Comment by DeltaNedas** [comment]
why are you

**Comment by rodrigolitzius** [comment]
> It has existed in basically every version.

i play this game for almost 1 year and i didn't knew that, WTF
