### ISSUE TITLE
mod.js

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry-Suggestions#1594]
**Describe the content or mechanics you are proposing.**

add the ability to use mod.js instead of mod.json

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

it doesn't have any practical use case, its just so it exists and we can achieve true "all-js mod". also i would like to use js for my mod.json file

and also why not.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
> it doesn't have any practical use case

then why bother?

>  its just so it exists and we can achieve true "all-js mod"

why does this matter?

> also i would like to use js for my mod.json file

*Why*? JS is for scripts, JSON is for data. There is no reason to have JS in the mod meta file, and no way for it to be "parsed" for use in the game. This makes absolutely no sense.

**Comment by QmelZ** [comment]
~~yes i never said it made sense~~

**Comment by sample-text-here** [comment]
you... actually made the suggestion

**Comment by QmelZ** [comment]
> you... actually made the suggestion

ofc i did why wouldn't i?

~~now wait for the pr for the absolute uselessness~~

**Comment by sk7725** [comment]
just...do java, java mods are essentially what that is

**Comment by QmelZ** [comment]
no, not really
