### ISSUE TITLE
Easily Rename Sector

### ISSUE THREAD

**Issue by dudecon** [Anuken/Mindustry-Suggestions#1595]
New mechanics: `none`
The ability to easily re-name the sector one is currently playing in.

My play-flow when running non-mission low, med, and high threat sectors is to
1. Launch in my defense core
2. Do a survey from the minimap
3. Rename the sector to denote my survey findings.

The first two steps are streamlined. Step 3 requires closing the Minimap, bringing up the Planet Map, clicking on the current sector, and finally clicking the little rename button at the bottom of the screen.

I recommend adding the F2 hotkey to rename the current sector, but any improvement here would be welcome. Maybe duplicate the "Rename Sector" interface at the top of the full-screen Minimap view? There's plenty of visual realestate up there, and it would have the added benefit of allowing you to remind yourself of what sector you're working in without going all the way out to the Planet Map.

Thanks for the great game! Having a blast.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
Synergy with #1211
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
This can wait for https://trello.com/c/g8j2OF5O
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Press "N" to open the planet map. This works even while the minimap is open.

**Comment by dudecon** [comment]
> Press "N" to open the planet map. This works even while the minimap is open.

Bugged. See https://github.com/Anuken/Mindustry/issues/4035
