### ISSUE TITLE
Transparent Circle around players when they're building

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1596]
**Describe the content or mechanics you are proposing.**
A small transparent circle around the player that shows the ground. This small circle is only visible to the player. Maybe it only appears when you are building or holding a building to build? This circle allows the player to see through other players/units so they can see where the ground is in areas with lots of units around. Maybe an option to toggle this on/off in graphics settings?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Pretty annoying when a swarm of 40 monos hovers over the area where you need to build and you can't see the ground. Also annoying when you're building and the lot of polys shows up to help you build but they block your view of the ground. Besides building, it makes it difficult to interact with blocks when there's dozens of them hiding the block you can't see. You can wait until monos leave but polys stay. Controling them with logic isn't practical to code up a whole program just for the 10 seconds you need to see the ground. Moving them manually doesn't work either since monos go right back to mining the same spot and polys go too when you start building again.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
i don't think making a circle is the most elegant way of solving this problem. I asked for this: https://github.com/Anuken/Mindustry-Suggestions/issues/1496 but anuke disliked it too. I do wish the whole "units covering where you are building" thing gets fixed somehow.

**Comment by sample-text-here** [comment]
instead of around the player, it would be better if it was around the cursor

**Comment by RedstonerKBC** [comment]
> instead of around the player, it would be better if it was around the cursor

That would be sweet too. Sorry for the copy. I swear I did do a quick search to make sure it wasn't suggested, but when there are thousands of posts sometimes you don't have time to go through them all lol.

**Comment by Voz-Duh** [comment]
@RedstonerKBC nice idea, thx 👏
