### ISSUE TITLE
Enemy threat type display

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1598]
**Describe the content or mechanics you are proposing.**
on the sector infor screen include what types of enemies can spawn.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
allow you to better plan and build your defenses, so you don't build anti air for a non-air map. etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
This would make it MUCH easier to prepare and predict how the wave will turn out

**Comment by NajimiOsana** [comment]
This is a good suggestion, but anuke not adding a certain thing like that might be intentional, since there wouldnt be any point to try and explore a sector if you already know which enemies are in it

**Comment by Legomonster33** [comment]
> This would make it MUCH easier to prepare and predict how the wave will turn out

Thats the point...

**Comment by XxsuperdeadlysniperxX** [comment]
I have even better fix to NajimiOsana's comment have it only display the highest tier of unit that can spawn after the sector has been explored so that you can properly prepare without ruining the gameplay

**Comment by XxsuperdeadlysniperxX** [comment]
> > This would make it MUCH easier to prepare and predict how the wave will turn out
> 
> Thats the point...

@Legomonster33 yeah i know im just interpreting the suggestion for the people who don't or can't do interpretation themselves due to either a mental issue (example) or laziness

**Comment by XxsuperdeadlysniperxX** [comment]
Not saying there are people who are this way or anything (im quite unsure if people like that plays mindustry if so then cool people will just have to try to deal with it in someway in my opinion i don't really care if anyone is this way because i don't like discrimination)

**Comment by joshuaptfan** [comment]
IMO, all the only extra help players should get is to announce the tier of the final guardian, e.g. "Tier 3 Guardian approaching in 10 waves".

Everything else should remain a mystery for the challenge. Players should develop a habit to always build anti-air defenses just in case.

**Comment by Legomonster33** [comment]
> IMO, the only extra help players should get is to announce the tier of the final guardian, e.g. "Tier 3 Guardian Approaching in 10 Waves".
> 
> Everything else should remain a mystery for the challenge. Players should develop a habit of always building anti-air defenses just in case.

Mindustry is a tower defense resource management strategy game, part of a strategy game is to know what your preparing for.
You shouldn't have to waste your resources on something that might not even be useful.

**Comment by joshuaptfan** [comment]
You can (usually) predict what type of enemy the guardian will be by the preceding waves. Players are empowered by being given room to apply light deductive reasoning, rather than being handed a script to follow. ("This map has air enemies, so build AA.")

I would focus on fixing the campaign maps where the guardian type doesn't match the preceding waves, e.g. Craters.

> You shouldn't have to waste your resources on something that might not even be useful.

Defensive building games are about preemptive over-preparation. When the wave timer runs out, you'd better have what you need to wipe out the wave already built. That includes anticipating multiple possible contingencies at once.

**Comment by XxsuperdeadlysniperxX** [comment]
Why tho?

**Comment by Legomonster33** [comment]
> You can (usually) predict what type of enemy the guardian will be by the preceding waves. Players are empowered by being given room to apply light deductive reasoning, rather than being handed a script to follow. ("This map has air enemies, so build AA.")

I never mentioned guardians???

> 
> I would focus on fixing the campaign maps where the guardian type doesn't match the preceding waves, e.g. Craters.
> 
> > You shouldn't have to waste your resources on something that might not even be useful.
> 
> Defensive building games are about preemptive over-preparation. When the wave timer runs out, you'd better have what you need to wipe out that wave already built, or you're good as toast. That includes anticipating multiple possible contingencies at once. Overkill is the SOP.

literally all of other tower defense games ive played will have to disagree with you

bloons td? waves are the same each time, you know when to prepare for what
pvz? shows you what you'll be fighting against
various flash games? show you what enemies come on what waves
infinitode? tells you what types of enemies you'll be facing
other games I've likely forgot about? have indication of what type of enemies you'll be dealing with

**Comment by joshuaptfan** [comment]
Ah, ok. Touché. Mindustry doesn't deliberately stand apart as a hardcore game, so I suppose some vague threat preview may be ok.
