### ISSUE TITLE
Arrows Logic, and new var type (runnable)

### ISSUE THREAD

**Issue by TheXeony** [Anuken/Mindustry-Suggestions#1599]
**Describe the content or mechanics you are proposing.**
**New var type** - A new type of variables, their value can be put in the logic code.
**Arrows logic** - The arrow function block will be able to run code from a new type of variable.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This content will expand the functionality of logic. Players will be able to create code that can generate other code and run it. This will allow you to import the code (let's say this code can control units) in the arrow function block and run it at any time, by the way, you can import several codes at once. In addition, it will allow people to create features without having to use jumps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
> arrow function

why specifically an arrow function

also how would you make a function?

**Comment by Catchears** [comment]
As far as I can tell (although I may be wrong), what you're trying to add is some sort of function or `for` statement. If that's the case, Anuke himself said this:

>I am not adding while/if/for statements. Jumps are enough. The language is designed to be as simple as possible; those constructors do not and should not apply.

[source](https://github.com/Anuken/Mindustry-Suggestions/issues/1317#issuecomment-733289699)

Also, then it has already been suggested before (see #880 and #1317).

**Comment by DeltaNedas** [comment]
close this
