### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by syuten2002** [Anuken/Mindustry-Suggestions#16]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the underscores in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
can nobody read

**Comment by CaribbeanMax** [comment]
what even?

**Comment by MEEPofFaith** [comment]
so

**Comment by MEEPofFaith** [comment]
uh

**Comment by MEEPofFaith** [comment]
*Ya like jazz?*

**Comment by micoplasma** [comment]
the hell does this even mean

**Comment by itcannotbe** [comment]
Maybe he thought anuke can read minds.

**Comment by MEEPofFaith** [comment]
mmmmm yes

MIND BEAM
