### ISSUE TITLE
Tabs in the schematics menu

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#160]
be able to make tabs to sort your schematics for example put factories in factories tab, power, pixel art, etc
This would help people navigate the schematics menu menu

**Comment by itcannotbe** [comment]
How would a pixel art tab be even helpful?

**Comment by itcannotbe** [comment]
Also this issue is out of format.

**Comment by Peter1095-game** [comment]
i think he means to be able to make your own tabs to sort your schems

so maybe like you can make a tab and name it what you want
