### ISSUE TITLE
Weathers that interacts with buildings

### ISSUE THREAD

**Issue by BedoAkgun** [Anuken/Mindustry-Suggestions#1602]
**Describe the content or mechanics you are proposing.**
Rain, fog, wind, sunny days etc.
example effects: Rain cools the blocks, fog limits the turret detect range, sunny days heats up the turrets so they will need to shoot slower and also it will cool down the reactors heat production etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It can make the game a bit more realistic and a bit harder
and it will also make the game's graphics better

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
Some of this already exists in the form of affinities; for example, a Sporestorm greatly increases the efficiency of all Cultivators on the map.

Further interactions is an interesting idea to explore, though.

**Comment by BedoAkgun** [comment]
if i can found a way to make mods, i will test how it looks

**Comment by GreenCurve** [comment]
Nice idea i suppose,you can try to make simple demo mod and show it us

**Comment by RedstonerKBC** [comment]
This would give more use for weather effects. Currently I don't see weather being used much in maps.
