### ISSUE TITLE
Logic functions

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1603]
**Describe the content or mechanics you are proposing.**
Add a `def` instruction, which can create functions and has 1 argument - the function's name. has an (orange-colored?) arrow going out of it. Anything under that arrow will be included into the function (and could be colored as well). Add another instruction - `run`, which takes 1 argument and runs the function that has the same name as the argument. Functions would take in arguments by the player simply `set`ting them before running the function.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Certain logic being vastly easier to manage.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (Yes i've done, but i haven't seen one which properly explains how will the concept work)
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Catchears** [comment]
Similar to #1599 and #880 and #1317, 

here's a quote by anuke:

> I am not adding while/if/for statements. Jumps are enough. The language is designed to be as simple as possible; those >constructors do not and should not apply.

[source
](https://github.com/Anuken/Mindustry-Suggestions/issues/1317#issuecomment-733289699)

**Comment by DeltaNedas** [comment]
use a higher level language

**Comment by RedstonerKBC** [comment]
You can get function functionality by storing the state of the program and functions variables in a memory cell/bank, jumping to the function start, and jumping back to the point where you left off after the function end. When you break away the abstraction of higher level languages that's what functions really are, a couple of jumps.

**Comment by Ilya246** [comment]
Yes, but this suggestion would make it way easier to handle

**Comment by Kyllingene** [comment]
There is also ```set @counter <lineno>```, which allows you to make functions. Line from *the manual* ([read it](https://mindustrygame.github.io/wiki/logic/0-introduction/)):

> ```@counter``` variable number
A variable that represents the next line the processor will read code from, equivalent to %IP in x86. It can be changed like any other variable as another way to perform jumps.
>
> An (advanced) example of setting ```@counter``` to jump to a function, then jump back to the caller:
>
>```
> op add retAddr @counter 1 # Save where we will continue after the function returns by adding 1 to the counter
> set @counter myFunc       # Jump to the line representing myFunc
> ...
> set @counter retAddr      # Return to the line set earlier after the function is called
> ```
