### ISSUE TITLE
Java(Jar) mods: Import from Github

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry-Suggestions#1604]
**Describe the content or mechanics you are proposing.**
Allow jar(Java) mod repos to be downloaded from Mindustry's `Import from Github`, checking the Actions(might want to inform modders to setup and specify the action names/types) or use a built-in CI, or some other cool way of allowing this that I am not aware of.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Java mods are so complicated than js/json mods to download, too much that many people would just not bother.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
why not just /releases

i think the complexity is good as it represents the jump between deltanedas/yes and deltanedas/ransomware
