### ISSUE TITLE
When satellites get added, they can tell you things about a sector.

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1605]
**Describe the content or mechanics you are proposing.**
In the Mindustry trello, it says that "sattelites will be added" (atleast when i looked on it last). So I think sattilites should tell you what should be in a sector. 

There could be multiple tiers of sattilites at that, with a t1 sattilite telling you the resources, t2 telling you resources and units and with t3 saying the exact number of resource ore deposits and if its an enemy base, it will tell you how many units are required to capture the base.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This is just my idea on how this idea could be implemented and also, it would help me plan out my strategies and my tactics before attacking or defending.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fipico2** [comment]
Am i confusing this or doesnt sattellites mean moons?

**Comment by Catchears** [comment]
It can, but jaygamer is referring to [these](https://upload.wikimedia.org/wikipedia/commons/b/bc/Soyuz_TMA-7_spacecraft2edit1.jpg).

**Comment by jaygamer81** [comment]
> Am i confusing this or doesnt sattellites mean moons?

Yes, natural sattellites are moons. But artificial sattelites are man-made ones too spectate things in space.

**Comment by shadoxxhd** [comment]
I'd rather say top tier satellites should let you look at the map terrain (incl. resource distribution), while enemy unit spawns should stay secret...

**Comment by SavageCreeper64** [comment]
Good idea but free cam exists too...
