### ISSUE TITLE
Change the sprites for block forge, loader and unloader in the build menu

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#1606]
**Describe what you would like changed, and why.**
Yes, I know the blocks are WIP. If you don't want feedback for WIP things, that's fine.
I suggest that the block forge, the block loader and the block unloader get sprites like the unit factories in the build menu. The difference is that the block forge, loader and unloader don't have an output on that sprite, but that could be seen as confusing as you'll never see them built without an output.
![image](https://user-images.githubusercontent.com/57631841/102699605-3b99a100-4246-11eb-845e-6b46d60afb8e.png)
**Describe the changes you want to propose. Include possible alternatives.**
I suggest that the block forge, loader and unloader have outputs in the build menu sprites, so that all blocks which interact with payload conveyors look similar. I would place the output on the left to match the unit factories and reconstructors.

- [X] Hasn't been suggested before
- [X] Isn't on the trello
- [x] Isn't in the game
- [X] Isn't on the list

**Comment by Humanoid-X** [comment]
good

**Comment by Quezler** [comment]
i personally have no problem with how they currently look
