### ISSUE TITLE
Launch screen max available resources button

### ISSUE THREAD

**Issue by MattMills** [Anuken/Mindustry-Suggestions#1607]
**Describe the content or mechanics you are proposing.**

On the Launch -> Resources screen, a button that would set all values to the current max available, as seen on the previous screen in red.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I don't have to edit each resource to the exactly correct value and can just click the button. After you have researched everything and just want to jump through easier sectors and clean up you don't often need full resources, esp if you have launch pads launching resources or are going to fairly easy sectors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

xxxx

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
[It's been added to the game](https://github.com/Anuken/Mindustry/pull/4238), it will be live next update. OP, please close this suggestion.

**Comment by MattMills** [comment]
Fancy.
