### ISSUE TITLE
CPU, Logic Mechanics

### ISSUE THREAD

**Issue by Xusk947** [Anuken/Mindustry-Suggestions#1609]
***Get Unit ID, String >> Hash number***

> **Get Unit ID**
this will help to create a database on memory blocks, which you can select units through their IDs or create some operations on them 

> **String to Hash number**
this will also help to save the names of the players as a number that you can refer to when you get data from a cell, you can also do it back, from a hash number to a string to use it further 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Legomonster33** [comment]
> _**Get Unit ID, String >> Hash number**_
> 
> > **Get Unit ID**
> > this will help to create a database on memory blocks, which you can select units through their IDs or create some operations on them

Flags bruh

> 
> > **String to Hash number**
> > this will also help to save the names of the players as a number that you can refer to when you get data from a cell, you can also do it back, from a hash number to a string to use it further

String ops == no

**Comment by Xusk947** [comment]
> > _**Get Unit ID, String >> Hash number**_
> > > **Get Unit ID**
> > > this will help to create a database on memory blocks, which you can select units through their IDs or create some operations on them
> 
> Flags bruh
> 
> > > **String to Hash number**
> > > this will also help to save the names of the players as a number that you can refer to when you get data from a cell, you can also do it back, from a hash number to a string to use it further
> 
> String ops == no

you cannot take the flag from a unit that belongs to the player

**Comment by DeltaNedas** [comment]
ids: mindustry netcode already gives everything ids, why not

hashing:
should be one-way, unhashing (ha) would create garbage
you can already manually hash a string with anuke-logic but itd be nice to have that
