### ISSUE TITLE
more turrets

### ISSUE THREAD

**Issue by electrogon69** [Anuken/Mindustry-Suggestions#161]
scatter is the only air only weapon that uses ammo and arc is the only ground electric turret its vetter to have
an electric arc that is for air only
and a version of scatter that shoots ground units to and maybe a sniper turret that can shoot very very long

these maybe not a big ask and expand the game or somthing but its a way that makes stuff more convinient

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X]

**Comment by itcannotbe** [comment]
Arcs that can target air has been a thing before. but they were removed because it was too powerful.

Also there are a lot of weapons that can target air, not just scatter.

As for your sniper. It's basically too op. Duh.

**Comment by Peter1095-game** [comment]
the sniper would work if it had a slow firerate

**Comment by itcannotbe** [comment]
Not if you spam a lot of them.

**Comment by electrogon69** [comment]
cuase if we have a turret that has a damge that is approximately higher
than all the turrets and have a fire rate that is more than 0.4 or 0.6 per
second is very pointless and overpowered

**Comment by electrogon69** [comment]
yep and even i think its better to make it like the bullet pierce through
enemies and shot multiple enemies behind that enemy
and im really waitinf for mindustry v6 im really excited for it

**Comment by nichrosia** [comment]
Also, anyone else wanting to know the story behind: "the optimal place to begin ONCE MORE"

**Comment by jaygamer81** [comment]
Sniper would be cool. Good for anti boss. Should be a railgun tho.

**Comment by liliam2007** [comment]
the new turret control can let you target anything so if you control an arc you could go ahead and hit air
