### ISSUE TITLE
Minimap Zoom

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1610]
**Describe the content or mechanics you are proposing.**
On the minimap when you zoom far enough in it makes it like you panned over there and when you zoom back out you go back into the minimap.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this will allow looking at how stuff is going in other places without panning over and it taking as long as panning. this will also help in pvp.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
That would be nice. Not sure how it could be implemented though.

**Comment by martosss** [comment]
example:
 - the **minimap has a white rectangle** that shows where your screen is currently.
- If you **left-click** on the minimap it changes the view and goes to that part of the map so you can quickly check what's happening in a different area of the map or if there are any problems with belts/production
