### ISSUE TITLE
[QOL] Massdriver sound cue and screen shake

### ISSUE THREAD

**Issue by Vlexa** [Anuken/Mindustry-Suggestions#1612]
**Describe what you would like changed, and why.**
Massdriver sound and screenshake.
While a sound at all is questionable, as there will be alot of noise having many mass drivers, 
the screen shake is a nono in my opinion. At times it throws of my block placement. It also interferes in the perception of the game field and causes me some mental stress. 

**Describe the changes you want to propose. Include possible alternatives.**

Do away with the shake. The sound could use some engineering into a more pleasant sound cue.

**Comment by GreyMario** [comment]
Wasn't there an option in the game config to change the intensity of screen shake?

**Comment by D-player1** [comment]
That moment when you don't know what Settings, game, screen shake is for

**Comment by DeltaNedas** [comment]
b r u h

**Comment by Vlexa** [comment]
Even though thats quite interesting, disabling the whole screenshake is not what i was suggesting. Its different.
