### ISSUE TITLE
make construction damage lower completion

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1613]
**Describe what you would like changed, and why.**

instead of giving the build block a super small health pool, just make it lost construction progress when it takes damage.

**Describe the changes you want to propose. Include possible alternatives.**

take for example the current scenario: reconstructor almost done, a few air units fly by and do a pew pew, fully gone:
![Screen Shot 2020-12-20 at 15 14 38](https://user-images.githubusercontent.com/3179271/102715505-3edc6d80-42d6-11eb-9b26-cdd61e429aae.png)

so instead of exploding, just lower the percentage of completion based on incoming damage and items used in the build and/or the health of the resulting structure 🤔

**Comment by GreyMario** [comment]
potential counterpoint: the AI doing the same thing to you with walls/thicc turrets in lower level AI-rebuilding campaign sectors

**Comment by joshuaptfan** [comment]
Sorry, but this suggestion reeks of salt.

This would reduce the risk vs reward of building in a hostile situation. It would make the game easier, and probably be terrible for PvP balance.

**Comment by Legomonster33** [comment]
> Sorry, but this suggestion reeks of salt.
> 
> This would remove the risk vs reward of building in a hostile situation. It would make bad choices easier, and probably be terrible for PvP balance.

There currently is no risk-reward because the risk outweighs the reward 1000 to 1

**Comment by joshuaptfan** [comment]
The health of unfinished structures is low to discourage players from building until all threats have been cleared, especially for more powerful/expensive structures.

If you just lose construction progress, that means there is minimal penalty for building in the thick of battle, construction will take longer, but you can just brute force it until it's done.

There are other less drastic ways to soften the blow of losing expensive structures during construction:
* Buff the health of unfinished structures a little, proportionally to their cost
