### ISSUE TITLE
allow processors to write and read other processors

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1614]
**Describe the content or mechanics you are proposing.**
processors being able to read and write the code of other processors similar to memory cells.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
would be interesting for self replicating programs and maybe useful for other logic things.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
So self replicating programs.......

Griefing time.

**Comment by DeltaNedas** [comment]
deltanedas/anuke-logic
this doesnt belong in vanilla, especially since its severely limited without string ops

**Comment by RedstonerKBC** [comment]
Have you ever seen computer viruses? All u gotta do is slap 1 processor down with the virus program near some other processors, link them, and watch as computer-covid-19 does its work.

**Comment by rodrigolitzius** [comment]
> Have you ever seen computer viruses? All u gotta do is slap 1 processor down with the virus program near some other processors, link them, and watch as computer-covid-19 does its work.


> So self replicating programs.......

Griefing time.

A way to prevent viruses is making a processor not able to link itself to another processor, only a player could do this.

**Comment by itcannotbe** [comment]
Don't underestimate how griefers make tools to automate this kind of fuckery.

**Comment by Yell245** [comment]
And is there another of using it which isn't griefing? You can simply use "set @counter"  command to go to the function in one processor

**Comment by rodrigoNOTyouramigo** [comment]
> **Describe the content or mechanics you are proposing.** processors being able to read and write the code of other processors similar to memory cells.
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** would be interesting for self replicating programs and maybe useful for other logic things.
> 
> **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 2. * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 4. * [x]  I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
i dont know why people are so opposed to this like there's way worse things you can do
