### ISSUE TITLE
Trace placement instead of diagonal placement

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1615]
**Describe the content or mechanics you are proposing.**
diagonal placement doesn't always make the best paths so it should turn into trace placement. trace placement will rotate the conveyor towards where your dragging it and will allow for turns. this could just be turned into a option for manual diagonal placement or auto placement.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this will make it faster to place down conveyors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
I've been wanting this forever. Allowing you to trace where the conveyers should go would be huge, especially for mobile. Also may help with the making conveyers easier than bridges thing on the discord.

**Comment by Kyllingene** [comment]
I agree that this should be a mode, but turning the old mode into this would make a bunch of people mad. Many people use it, and removing it for a more manual mode would ruin some peoples methods entirely.
