### ISSUE TITLE
Support SRV lookup for ip address

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry-Suggestions#1616]
**Describe the content or mechanics you are proposing.**
Support SRV lookup for ip address
I hava Suggest it in discord, and i work out a way just using UDP request.
```kotlin
import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress
import java.nio.ByteBuffer
import kotlin.random.Random

data class SrvRecord(val ttl:Int,val priority:Short,val weight:Short,val port:Int,val target:String)

fun getSrvRecord(dnsHost:String,name:String): SrvRecord {
    val id = Random.nextInt()
    //build request pocket
    val data = ByteArrayOutputStream().apply {
        DataOutputStream(this).use { stream ->
            stream.writeShort(id)
            stream.writeByte(1)//Recursion
            stream.writeByte(0)
            stream.writeShort(1)
            stream.writeShort(0)
            stream.writeShort(0)
            stream.writeShort(0)
            //endHeader
            name.split('.').forEach {
                stream.writeByte(it.length)
                it.forEach { c ->
                    stream.writeByte(c.toInt())
                }
            }
            stream.writeByte(0)
            //end Name
            stream.writeShort(33)//SRV
            stream.writeShort(1)//Internet
        }
    }
    //request dns server
    val socket = DatagramSocket()
    socket.send(DatagramPacket(data.toByteArray(), data.size(), InetAddress.getByName(dnsHost), 53))
    val res = ByteArray(512)
    socket.receive(DatagramPacket(res, 512))
    //resolve response from dns server
    ByteBuffer.wrap(res).apply {
        //short following is ByteBuffer.getShort()
        assert(short.toInt() == id)
        position(data.size())//Pass Header and QRecord
        assert(short == (0xc00c).toShort()) { "Lookup fail" }
        assert(short == (33).toShort())//SRV
        assert(short == (1).toShort())//Internet
        val ttl = int
        short//Data Length,ignore
        return SrvRecord(ttl,short,short,short.toInt(), buildString {
            var l: Int
            do {
                l = get().toInt()
                repeat(l) {
                    append(get().toChar())
                }
                append('.')
            } while (l != 0)
            delete(length - 2, length)
        })
    }
}
```
That is written in kotlin using java DatagramSocket, all have alternative in arc. 
I believe it can be implemented in mindustry with arc.  
One thing i don't know is how to get proper dns host, or it must be const.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why not make a PR?

**Comment by way-zer** [comment]
May I modify mindustry.ui.dialogs.JoinDialog.Server?

**Comment by itcannotbe** [comment]
Well it's called a pull request after all.
It still needs to be merged by the dev.
