### ISSUE TITLE
Enable/activate default blocks on maps

### ISSUE THREAD

**Issue by sffc** [Anuken/Mindustry-Suggestions#1617]
**Describe the content or mechanics you are proposing.**

A lot of maps have "default" blocks, like conveyors, containers, and turrets. I should be able to left-click on these blocks and have them activated and usable.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I can activate large turrets by right-clicking to start destruction and then quickly left-clicking to start reconstruction. However, this is inefficient and doesn't work well for conveyors, which destruct before I can reconstruct them.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NajimiOsana** [comment]
or you could just rebuild all the conveyors? and let alone the factories that can be deconstructed, then immediately rebuilt after?
