### ISSUE TITLE
Planet creation in editor.

### ISSUE THREAD

**Issue by Wetelemon** [Anuken/Mindustry-Suggestions#1618]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As the title says, I would like to see a "planet" option in editor. It would enable planet mode, in which you could make your own planet, and sectors for it. You could use it as a custom campaign, or maybe for testing purposes. This feature would make adding new planets way easier for people that just don't know how to make mods (like me), and definitely would extend playtime of many people. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Wetelemon** [comment]
Don't mind the edit history, I have accidentally deselected the boxes

**Comment by Ruichka** [comment]
#1384
