### ISSUE TITLE
Disassembler and Separator should be buildable from fundamental elements

### ISSUE THREAD

**Issue by sffc** [Anuken/Mindustry-Suggestions#1619]
**Describe what you would like changed, and why.**

To build a Disassembler (to produce Thorium), you need Surge Alloy. The Alloy Smelter requires Thorium to build. Likewise, building a Separator (to produce Titanium) requires Titanium.

This is unbalanced because normally, if you launch onto a map with zero resources, you can, given enough time, build the same factory as if you launched with all required resources. However, on maps with Scrap but no Titanium or Thorium, seeding the map with exotic resources is the only way to build certain factories.

**Describe the changes you want to propose. Include possible alternatives.**

- Separator: replace Titanium with Metaglass in construction cost
- Disassembler: replace Surge Alloy with Metaglass or Plastanium in construction cost
    - Alternative: on the Alloy Smelter, replace Thorium with Titanium

With these changes, you can start with zero resources on a map with only Copper, Lead, Coal, and Scrap and work your way up to the top-tier resources.

**Bonus: Boards without Coal**

You can chain Cultivator, Spore Press, and Coal Centrifuge to produce Coal on a map like Ground Zero. However, this requires seeding the map with Silicon and Graphite in order to build those blocks.

Lots of ways to resolve this issue. Here's one: allow Coal Centrifuge to accept Scrap instead of Oil (doesn't have to be efficient), and remove Graphite/Titanium from the build cost of Coal Centrifuge. Then you'd be able to chain a Mechanical Drill into a Coal Centrifuge, and then into Graphite and Silicon, to kick-start Ground Zero.

**Comment by Yell245** [comment]
Nope. You have a load out function. And export from sectors in campaign

**Comment by Quick-korkc** [comment]
You can use launchpad to transport the building materials to other sector
also if the separator and disassembler use material like you said, i think that make the game unbalanced
imagine you can just mining titanium but you use scrap to get it
And about the ground zero...
that map suppose to be starter map without any coal

**Comment by D-player1** [comment]
Stop reviving powercubes, if it's dead, it's dead

**Comment by Humanoid-X** [comment]
Loadouts : Exist

**Comment by joshuaptfan** [comment]
You're missing the whole point, that ore placement is a tool for map makers to limit players. You're also missing the point of the tech tree, that it works by gating higher technologies behind discovery of higher tier resources, and you're not supposed to be able to get them all on the first map.

**Comment by RedstonerKBC** [comment]
Cant make scrap-only challenge maps without placing at least 1 disassembler (for thorium) because it wouldnt be possible any other way. By the way, before you tell me scrap is op, know that I posted 2 scrap-only challenge maps and when I told the scrap haters they should have no problems making it to wave 300 they were dead silent. It's been months and they still haven't even tried. Unless you're willing to try my maps I don't want to hear that scrap is op.

**Comment by sffc** [comment]
Okay, so this is Working as Designed. I didn't consider the perspective of map makers. Thanks.
