### ISSUE TITLE
The Entire Solar System!

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry-Suggestions#162]
We should have a giant mega ship and we could control it to go over a place in the V6 planets, And than we launch to land on that spot. We can controll that giant star ship to go to other planets in a 3D solar system and lauch to them! Maybe, other planets like Mars and Mercury have more metals and unique stuff like Mineable Blast Compound! Also a moon for the planet and a trading planet to trade resources for other resources!

It will add sooo much more oportunities to add stuff in V7 and Make the game a lot longer to complete and more exiciting! Maybe enemys drop from another star ship? This would be great for multiplayer as well, Servers can make galaxys with everyone having a planet, pvp can be planet raiding, survival can be tradeing and fighting enemy star ships, atack can be raiding enemy planets and so on! This would add infinite content to the game!

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
I wish it was obvious that people should check out the trello board making suggestions.

**Comment by kingb74** [comment]
That's great and all but no way that coming in this update maybe in mindustry V10 or 11 we will get a solar system

**Comment by Anuken** [comment]
I have my own plans for this.
