### ISSUE TITLE
A harder mode for campaign - V7

### ISSUE THREAD

**Issue by Yell245** [Anuken/Mindustry-Suggestions#1620]
**Describe the content or mechanics you are proposing.**
The title explains everything. You can increase difficulty by decreasing resources on the planet, making weather changing more often (and there are more debuffs than buffs), making enemy to also grow and making more of them.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will add optional extra challenge to professional players. It may be a new planet.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
I heard someone said that Anuke is adding a new planet named "Tantros".
I think the Interstellar Accelerator is used to bring players from Serpulo to Tantros if it is added.

**Comment by Jammo2000** [comment]
Mindustry v14 - New planets include Jupiter, Mars, and Earth.

**Comment by Legomonster33** [comment]
difficulty modes = bad

**Comment by Axzye** [comment]
Casuals can take it slow and capture many easy sectors, experts can rush hard sectors. I don't see a problem with the skill ceiling.
