### ISSUE TITLE
Should i make a suggestion?

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry-Suggestions#1621]
**Should i suggest something?**

*I asked in #pulls and quezler told me to make a suggestion for wether or not i should suggest something.
![21F89180-C030-4258-8BBC-53DC2F39C1F3](https://user-images.githubusercontent.com/62565267/102802408-a1f9fd00-43c7-11eb-975f-9ce87d2c5795.jpeg)
Im sorry if its wrong to do what a Moderator said. :/

**Comment by Quezler** [comment]
hmm, yes, great idea, this should be implemented 👍

**Comment by QmelZ** [comment]
waiting for anukes answer

11/10 suggestion

**Comment by Humanoid-X** [comment]
This suggestion must definitely get implemented.

**Comment by Kyllingene** [comment]
This is one of those suggestions that should never be closed because the ideas are too top-notch to hide.
