### ISSUE TITLE
Require resources to be unlocked on preset sectors

### ISSUE THREAD

**Issue by andr658** [Anuken/Mindustry-Suggestions#1622]
As of now, launching to sector 175 right next to Ground Zero gives the player access to abundant coal, sand, titanium, and scrap. That's 3 major ones all on an easy level next to the start. This is just the first example that came to mind, there are many other holes that players can use to get endgame resources obscenely fast and non-linearly. 

A fix could include requiring resources to have captured certain sectors to unlock them, thus preventing collection. An alternative could be preventing launching to sectors without unlocked resources.

**Comment by Legomonster33** [comment]
this, along with blocks requiring specific sectors to be captured, kinda defeats the purpose of having numbered sectors in the first place.
