### ISSUE TITLE
Include Sectors More

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1624]
**Describe the content or mechanics you are proposing.**

1. Research Center:
A research center can connect to the core like a container or vault and will contribute all its items (maybe liquids as well?) to the tech tree. You can also just pipe resources into it to select what items you want to use for the tech tree. For tech tree sectors you would need to place a research center to complete it on the tech tree.
A research center could also have drones that fly around scanning blocks and can unlock the blocks just by scanning them instead of needing resources.

2. Attack Waves:
[Unit transter](https://trello.com/c/TogJg9CP/612-sector-transfer) is in trello but I think they should be based on wave and difficulty on what mechs you can send, when you can send mechs, and how many you can send. There should also be a specific launchpad for units that goes in varying sizes and the larger it is the more rare resources it needs. When a sector is being attacked some of the units being transfered should have a lower chance of getting through.

3. Reinforced Sectors:
If there is a sector with captured sectors next to it wave strength in that sector will go down.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

1. Research Center:
This will allow you to choose what sectors you want to pull for the tech tree and make research a little harder.

2. Attack Waves
Unit transfer is in trello but this is just saying how to balance it.

3. Reinforced Sectors
This will allow for not have the best defense but still able to survive very high waves. This may be very hard to implement due to how waves are setup in maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quick-korkc** [comment]
>Research Center
I think this one exist in alpha, for some reasons this is deleted

**Comment by Arackulele** [comment]
1.Terrible idea,theres a reason the tech tree was changed to just use ressources directly its the simplest and most effective method without weird caps and shenanigans 
2.Eh,this isnt even a suggestion
3.more than just counter intuitive,you are saying if a sector has more sectors around it the waves should be easier?
