### ISSUE TITLE
A Thruster Revamp

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#1625]
**Describe the content or mechanics you are proposing.**
All the thruster is right now is a big, slightly-more-fancy wall. A lot of tower defense games that I've seen have some kind of non-buildable technology on the map that you can harness for additional defense. The thruster is a prime candidate for that. I was thinking that when fed fuel such as coal, pyratite, or oil, the thruster could periodically produce jets of flame that can severely damage _anything in front of it_ (an important distinction to make). However, you can't rebuild them or move them easily (an Oct could do that but by the time you have t5 tech you won't really need the thruster any more), they're not turrets (so they can't be possessed or boosted), and they're only per-map. There could also be a hidden stat that determines whether a thruster will stop working after a preset amount of firings. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Having an early-game option for high damage with tradeoffs would be a boon for procedurally generated levels, as well as for mapmakers. The concept of "non-replaceable tech that offers a unique bonus" could be expanded upon, but for now, the concept of the thruster being a source of damage instead of just a wall is interesting and possibly unique enough to be included.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
> All the thruster is right now is a big, slightly-more-fancy wall.

What is the thruster? Otherwise, cool idea!

**Comment by Humanoid-X** [comment]
It's a type of wall. You can only find it in the map editor.

**Comment by Kyllingene** [comment]
Ah, ok.
