### ISSUE TITLE
spiricots and higher tiers have purple building lasers

### ISSUE THREAD

**Issue by catatagun** [Anuken/Mindustry-Suggestions#1626]
**Describe what you would like changed, and why.**
Basicly it makes it look like the lasers have more purpose such as building and that tier 3 4 and 5 all can build and all have lasers perhaps with this included building lasers from core units could have colors for the team they are on

**Describe the changes you want to propose. Include possible alternatives.** spiricot having purple build laser and possibly core units having the build laser color of the team they are on

There are no possible alternatives sorry

**Comment by joshuaptfan** [comment]
Animations should not be team colored, because color can convey unintended meaning (red = destroy, green = heal), and black team animations would be hard to see.

**Comment by catatagun** [comment]
Yes but they are building lasers

**Comment by Kyllingene** [comment]
So?

**Comment by catatagun** [comment]
They are not projectiles not sure how you did not know

**Comment by Kyllingene** [comment]
I did know (I'm a mini modder, kind of hard to *not* know), my question is why does the fact that they are not projectiles mean that color implying different meanings/being hard to see is ok?

**Comment by catatagun** [comment]
They are really small

**Comment by catatagun** [comment]
Also it seems like anuke no want this
