### ISSUE TITLE
Discord: #ideas channel

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1627]
#ideas channel for discussing suggestions and ideas that may be suggested. Keeps channels clean and gives a good place for actual idea-based discussion without "DO YOU WANT THIS CHANNEL TO BE ARCHIVED?!" being thrown out constantly.
also what was the point of archiving #off-topic? just deny image attachment perms and memes cannot be sent. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content I can access already in the server or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
bad memes were hardly the only issue with #social/#off-topic.

**Comment by itcannotbe** [comment]
> cannot be sent
Noooooooo. I don't want to be sent.

**Comment by BlueWolf3682** [comment]
> bad memes were hardly the only issue with #social/#off-topic.

true but it would make the chat a lot less painful for our very rare moderators

**Comment by WilloIzCitron** [comment]
We need. Offtopic channel because we want to send a offtopic content

#bringbackofftopicchannel

**Comment by markozajc** [comment]
this repository is for ideas silly man
discord is not a forum

**Comment by joshuaptfan** [comment]
Allowing suggestion discussion on the Discord would also allow some bad suggestions to get cleaned up or filtered out before they make it to this GitHub, thereby saving Anuke time.

**Comment by catatagun** [comment]
Yes

**Comment by WilloIzCitron** [comment]
hmm need autoclose?

**Comment by BlueWolf3682** [comment]
this will be closed if anuke either closes it himself or adds an #ideas channel

**Comment by Kyllingene** [comment]
anuke does not close issues.

>Manually closing invalid or completed requests is tiring. I'm not going to explain why I don't like your suggestion anymore - I just won't do anything.

**Comment by itcannotbe** [comment]
OP just said he won't be closing this issue.

And yes, anuke still closes some issue, though not all.

**Comment by Kyllingene** [comment]
Not closing an issue just because you like the idea is stubborn. Imagine if every single issue was like that. There are 598 closed issues. Lets say Anuke closed a (generous) 98 of those. There would be 500 stale, unused issues lying about just because their owners never closed them. Trying to find anything *new* in that mess would be a pain. So please, after a month or so, close this.
