### ISSUE TITLE
Drone build range viewer

### ISSUE THREAD

**Issue by Tripwiregamer** [Anuken/Mindustry-Suggestions#1628]
When hovering your mouse over or close to a unit (including the player), it shows the build range in the form of a team colored dashed line circle (like an attack/detect range of a immovable ground turret) and if the unit can build.
You can also see the player character's build range as a transparent circle while anything is in the build queue or an oscillating alpha circle while you have something buildable in your (hand/cursor)

It will show if you can build something from the distance you will be at, and encourages players to get closer to the things they're building, and helps players more quickly recognize if they are out of building range of something

Looks something like this
![image](https://user-images.githubusercontent.com/45953835/102911108-3eacb100-4441-11eb-9d02-b2399a3b83b4.png)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Tripwiregamer** [comment]
Fun fact: The build range of this unit is approximately 28 blocks!

**Comment by Kyllingene** [comment]
The player build circle could also appear when you are building *and* have your cursor within ~5 blocks of the edge. That removes unnecessary clutter when you don't need it, but keeps the functionality.

**Comment by catatagun** [comment]
Yes
