### ISSUE TITLE
Random Reactor Things...

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#163]
**Describe what you would like to be changed, and why.**
*#1. Thorium Reactor explosions.*
*#2. Impact Reactor explosions.*

**Describe the changes you want to propose. Include possible alternatives.**
*#1. Thorium reactors should have a blast radius and damage based on fullness at critical, not the same no matter fullness. Also a minor power buff, from 840 power/sec to 1080 power/sec.*
*#2. Impact reactors should explode more violently than thors if their cryofluid is shut off while they are running.*

**Comment by ifritdiezel** [comment]
Thorium reactors are very efficient already, buffing them would mean no other reactors would be ever needed, which isn't good gameplay-wise.
And impacts are too high-level tech to explode just because cryofluid is off.

**Comment by ritzip** [comment]
why

**Comment by BlueWolfGaming** [comment]
I'm afraid not. Impacts are fusion reactors, correct? well fusion reactors explode too if not cooled, as you need coolant to contain a small star.

**Comment by ritzip** [comment]
gameplay-wise its better as it is
"thorium reactors can coldstart"
- original poster

**Comment by itcannotbe** [comment]
Well...….. Fusion reactor aren't stars to begin with.

Also refer to: https://en.wikipedia.org/wiki/Tokamak

**Comment by BlueWolfGaming** [comment]
And yet because impacts are a teensy bit more power dense and cause everyone is afraid of thors i thought making diffs the safest power would be the best idea cause everyone uses impacts, diffs are set up even less than thors

**Comment by BlueWolfGaming** [comment]
Also making impacts *less* power dense than thors would fit nicely into how anuke likes to have the second-highest tier the secretly best tier

**Comment by itcannotbe** [comment]
The fear caused by thorium reactors is due to it's Greifing potential.

**Comment by ritzip** [comment]
theres also the cryofluid mixer buff

**Comment by ifritdiezel** [comment]
Thorium reactors are probably the best already. Generating 720 power using only 1 piece of cheap fuel each 6 seconds is overpowered.

**Comment by itcannotbe** [comment]
Don't forget the miniscule cryofluid consumption.

**Comment by BlueWolfGaming** [comment]
its actually 840 @ifritdiezel 
@itcannotbe hmhm, and impcts die w0the second someone crashes the grid even slightly, but t0everyone still uses impacts

**Comment by ritzip** [comment]
The only thing that doesn't make sense here is the cryofluid and thorium consumption.

**Comment by BlueWolfGaming** [comment]
considering that a small star only needs 25 cryo/sec, it kinda does make sense

**Comment by ritzip** [comment]
Battery diodes also exist.

**Comment by BlueWolfGaming** [comment]
ok, honestly, do you expect the average player to diode?!

**Comment by ritzip** [comment]
> Well...….. Fusion reactor aren't stars to begin with.
> Plus they don't even use that much cryofluid to begin with to suggest it runs it's parts at a high enough temperature.
> 
> Also refer to: https://en.wikipedia.org/wiki/Tokamak
^

**Comment by ritzip** [comment]
Do you have to be the average player to use diodes?

**Comment by BlueWolfGaming** [comment]
fusion reactors *literally* are basically star cores, its high-pressure and high-temp hydrogen being fused together

**Comment by BlueWolfGaming** [comment]
@ritzip 99% of the time, theres no diodes on higher tier power.

**Comment by itcannotbe** [comment]
Actually, Stellar Nucleosynthesis is a self sustaining reaction.

**Comment by ritzip** [comment]
Thermonuclear does not equate to high pressure by itself.

Once again, Its the player's fault.

**Comment by BlueWolfGaming** [comment]
I'm going to point out *right* now that impacts reactors are self sustaining fusion reactors.

**Comment by itcannotbe** [comment]
Read up:
https://en.wikipedia.org/wiki/Tokamak
https://en.wikipedia.org/wiki/Stellar_nucleosynthesis

**Comment by BlueWolfGaming** [comment]
I read those.

**Comment by itcannotbe** [comment]
Self Sustaining does not equate to more energy released than consumed.

**Comment by ifritdiezel** [comment]
Where and when did Anuke say that they are fusion reactors?

**Comment by BlueWolfGaming** [comment]
To actually sustain a fusion reaction, you need **BOTH** high temperatures and high pressure, temp to make the protons move and pressure to force them together and cause a chain reaction that results in a self sustaining, stable reaction.

**Comment by BlueWolfGaming** [comment]
> Where and when did Anuke say that they are fusion reactors?

impacts are literally based off fusion, the correlations are really obvious

**Comment by ritzip** [comment]
No, thermonuclear fusion is not exactly the same as stars do.

**Comment by itcannotbe** [comment]
You also forgot that you need to contain the reaction somehow.

The sun does this via it's sheer mass.

A fusion reactor? By a way of containing it.

**Comment by BlueWolfGaming** [comment]
Magnets, duh.

**Comment by ifritdiezel** [comment]
It's just a game. Not all things should have real life counterparts. Draug miners create matter out of energy. Yet no one tries to explain it the physical way?

**Comment by BlueWolfGaming** [comment]
Mindustry seems to at least be somewhat based off of reality in vanilla. again, actually look into the game before telling me how it works

**Comment by ritzip** [comment]
The sun uses its own mass to create pressure. You wont get anywhere near that pressure. To compensate for this, high temperatures are used, high temperature = more free flowing particles = more particles bumping.

**Comment by BlueWolfGaming** [comment]
Precisely, which is why impacts should explode when not supplied with coolant.

**Comment by itcannotbe** [comment]
Apparently you didn't read enough did you?

https://en.wikipedia.org/wiki/Tokamak#Plasma_disruptions

**Comment by ritzip** [comment]
Except unlike reactors, pressure isn't present, therefore, no explosions. Just stopping the reaction because technology.

**Comment by BlueWolfGaming** [comment]
However, pressure *is* present in fusion. It is literally impossible to reasonably sustain a fusion reaction without high pressures.

**Comment by ritzip** [comment]
Do you even know __thermo__nuclear fusion?.

**Comment by itcannotbe** [comment]
> Apparently you didn't read enough did you?
> https://en.wikipedia.org/wiki/Tokamak#Plasma_disruptions

When the plasma touches the vessel walls it undergoes rapid cooling, or "thermal quenching". In the major disruption case, this is normally accompanied by a brief increase in plasma current as the plasma concentrates. Quenching ultimately causes the plasma confinement to break up. In the case of the major disruption the current drops again, the "current quench". The initial increase in current is not seen in the VDE, and the thermal and current quench occurs at the same time.[83] In both cases, the thermal and electrical load of the plasma is rapidly deposited on the reactor vessel, which has to be able to handle these loads. ITER is designed to handle 2600 of these events over its lifetime.

If you actually read the whole thing, you wouldn't missed this.

**Comment by ifritdiezel** [comment]
Thorium reactors are unique because they explode. Impacts drain power instead of exploding which may be even more dangerous. 
What would harm more, an explosion that breaks a part of your base that could be rebuilt quickly by phantoms or a -50000 main power line?

**Comment by BlueWolfGaming** [comment]
The problem is, you cant cool several million degrees celsius at ungodly pressures easily, and several million degrees celsius at ungodly pressures not cooled would just kinda... melt... the reaction chamber, as theres is no actual material that can withstand that heat directly.

**Comment by itcannotbe** [comment]
> Apparently you didn't read enough did you?
> https://en.wikipedia.org/wiki/Tokamak#Plasma_disruptions
> 
> 
> When the plasma touches the vessel walls it undergoes rapid cooling, or "thermal quenching". In the major disruption case, this is normally accompanied by a brief increase in plasma current as the plasma concentrates. Quenching ultimately causes the plasma confinement to break up. In the case of the major disruption the current drops again, the "current quench". The initial increase in current is not seen in the VDE, and the thermal and current quench occurs at the same time.[83] In both cases, the thermal and electrical load of the plasma is rapidly deposited on the reactor vessel, which has to be able to handle these loads. ITER is designed to handle 2600 of these events over its lifetime.
> 
> If you actually read the whole thing, you wouldn't missed this.

Why are you ignoring this?

**Comment by BlueWolfGaming** [comment]
> Thorium reactors are unique because they explode. Impacts drain power instead of exploding which may be even more dangerous.
> What would harm more, an explosion that breaks a part of your base that could be rebuilt quickly by phantoms or a -50000 main power line?

simply this: irl the reactor would go boom, no arguing, itd just instantly vapourize.

**Comment by ifritdiezel** [comment]
This place is for discussing the game mechanics not nuclear physics. Making impacts explode by themselves is just pointless.

**Comment by BlueWolfGaming** [comment]
its more realistic than thors blowing up the same no matter fullness, hmhm?

**Comment by ifritdiezel** [comment]
The entire idea of an impact reactor is that they use power to run while also generating power. They're not supposed to explode.

**Comment by BlueWolfGaming** [comment]
@itcannotbe cause explaining experimental, unsustainable fusion is irrelevant, sinc im talking actually running fusion

**Comment by ritzip** [comment]
From: google
> To produce usable heat, the neutron streams carrying 80 percent of the energy from deuterium-tritium fusion must be decelerated and cooled by the reactor structure, its surrounding lithium-containing blanket, and the coolant.
Of course you need to use the heat why would you reduce energy that you could have absorbed

**Comment by itcannotbe** [comment]
> Apparently you didn't read enough did you?
> https://en.wikipedia.org/wiki/Tokamak#Plasma_disruptions
> When the plasma touches the vessel walls it undergoes rapid cooling, or "thermal quenching". In the major disruption case, this is normally accompanied by a brief increase in plasma current as the plasma concentrates. Quenching ultimately causes the plasma confinement to break up. In the case of the major disruption the current drops again, the "current quench". The initial increase in current is not seen in the VDE, and the thermal and current quench occurs at the same time.[83] In both cases, the thermal and electrical load of the plasma is rapidly deposited on the reactor vessel, which has to be able to handle these loads. ITER is designed to handle 2600 of these events over its lifetime.
> If you actually read the whole thing, you wouldn't missed this.
> 
> Why are you ignoring this?

Still ignoring this.

And also this:
https://en.wikipedia.org/wiki/Temperature#Heat_capacity

**Comment by BlueWolfGaming** [comment]
> The entire idea of an impact reactor is that they use power to run while also generating power. They're not supposed to explode.

and yet, they should. reactors are honestly dangerous to use irl and an impact irl would explode if not cooled(or supplied with sufficient power to conatin the reaction after being started up)

**Comment by itcannotbe** [comment]
> @itcannotbe cause explaining experimental, unsustainable fusion is irrelevant, since im talking actually running fusion

Theories are one thing but experiments are another.

**Comment by ritzip** [comment]
Actual fusion reactors only had their cores melted.

**Comment by BlueWolfGaming** [comment]
lets see, impacts take an entirely different material than anything near pure hydrogen, so ofc the tokamak doesnt mean jack here.

**Comment by ifritdiezel** [comment]
who cares about theories and experiments 
mindustry is a sandbox game not a physics simulator

**Comment by BlueWolfGaming** [comment]
> Actual fusion reactors only had their cores melted.

that means you should have to at least replace the block, hmhm?

**Comment by ifritdiezel** [comment]
if you want realism TPT is a better choice

**Comment by ritzip** [comment]
> Which shouldn't be a problem in itself considering mindustry.

**Comment by ritzip** [comment]
You have:
heat tolerant surge alloy
crazy semiconductor
who knows how strong magnets in spectres

**Comment by BlueWolfGaming** [comment]
lets let anuke decide, hm? i dont want to waste my apm yelling at dumbfucks about a subject i have looked into many times.

**Comment by ifritdiezel** [comment]
might as well go to minecraft suggestions and suggest removing zombies because they don't exist irl

**Comment by ritzip** [comment]
Switching to insults ah yes

**Comment by Anuken** [comment]
If impact reactors were fusion reactors, they would be called fusion reactors. Real fusion reactors don't run off of cold liquids and high explosives. 

Realism has no bearing here, as we don't have anything that functions like this block. Even if we did, it would be irrelevant; game balance is what matters. Every starter drill and conveyor in this game is moving on its own, seemingly without a power source, and yet nobody seems to be complaining.

**Comment by DeltaNedas** [comment]
>complain that impact isnt as realistic as irl fusion reactor
>uh idiot it not a fusion reactor i am genius
>mindustry universe simulator need realism for something that doesnt exist
