### ISSUE TITLE
Name msav files as the map metadata name

### ISSUE THREAD

**Issue by Kickbut101** [Anuken/Mindustry-Suggestions#1630]
**Describe the content or mechanics you are proposing.**
Save custom map files (both created and imported) as the name of the map, instead of "Map_16.msav"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will help with people managing and working with larger number of maps, making it easier to keep them distinguished and easier to share/move around.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Agreed. If possible, doing the same with schematics would be great.

**Comment by Kickbut101** [comment]
This doesn't seem prudent to close out
