### ISSUE TITLE
UI ambience depending on units you're controlling

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1631]
**Describe the content or mechanics you are proposing.**
basically, if the UI were to be redesigned it should be slightly different if youre in certain units. there could be preset colors, and configurations. here are two major ideas:
1: glow. you have a very subtle glow around the edge of your screen, almost hardly noticeable. it and some basic designs are based on the unit youre driving and/or your team color. this effect would be toggleable if too annoying in settings.
2: design. perhaps something like the current UI would appear when youre in a ship that can build. however, if you enter a unit that cant build, your UI changes drastically. this can mean everything from a more informational map to removing the building menu and making health/ammo more prevalent. a lot is adjustable between builder and fighter units.
3: detail. if youre in a core unit, the ui has a little bit of detail. if you control a t1-t5, the UI becomes much more detailed by t5. this could mean more informational indicators like speed, or just a "cooler", more detailed design around the edges.
you can imagine the implementation of this suggestion to work out like this:
-you spawn in a pvp map, on the blue team. since youre in a beta unit you have subtle yellow glow, and maybe a few elements (like lines or triangles) that are blue. you go to control an arkyid, and the glow changes to purple, you suddenly gain an interface more suited to attacking instead of building.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
a complete UI redesign is in the trello - i think having the ui change depending on what unit youre driving could add more depth, and "feel" like youre in the unit more. if done right you could feel like youre piloting a star destroyer while driving an eclipse. this whole suggestion is just a concept and can be changed, its just my ideas.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
I like this idea. +1
