### ISSUE TITLE
Highlight damaged buildings on the minimap if a support unit is controlled

### ISSUE THREAD

**Issue by ifritdiezel** [Anuken/Mindustry-Suggestions#1632]
**Describe the content or mechanics you are proposing.**
When the player is controlling a support unit capable of repair, buildings below a certain health threshold are better visible _on the minimap_. Possibly an exclamation mark over each block with <95% health.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make it much easier to use repair units since the player wouldn't have to check every building's health individually and would know exactly where to go without having to run around the base and shoot everything.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
But there's autoaim? I think it'll be more useful if it would highlight on the game's screen, not minimap

**Comment by catatagun** [comment]
Yes this very good suggest

**Comment by Jammo2000** [comment]
This would help a lot, and would also make things feel more right. Unit AI would see damaged blocks, why not player UI?
