### ISSUE TITLE
"real-view" mode for minimap

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1633]
**Describe the content or mechanics you are proposing.**
Have a mode for the minimap that displays blocks as their actual sprites instead of just a yellow color (Perhaps you could use scaled-down versions to not harm performance?).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Adds a mode for the minimap that allows actually seeing what blocks are - very useful for the fullscreen minimap.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by zethnest** [comment]
So,  this would be the same for #1610 ?

**Comment by Ilya246** [comment]
Almost - this one allows toggling it at any time and any zoom

**Comment by catatagun** [comment]
Yes

**Comment by Dennis44ff** [comment]
Download link?

**Comment by Kyllingene** [comment]
> Download link?

For what?
