### ISSUE TITLE
Unloadable server plugin

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry-Suggestions#1634]
**Describe the content or mechanics you are proposing.**
Make plugins unloadable so plugins can be updated __without stopping the server__

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Like Minecraft. Server managers no longer need to stop the server to update the plugin, and can prevent the server itself from shutting down immediately due to an error.

![image](https://user-images.githubusercontent.com/44261958/102988813-e1efea00-4557-11eb-8096-dc1e2bb00b48.png)
Some plugins don't shut down the server if there are working threads. (like my plugin)
So need to create an ``unload`` function.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sk7725** [comment]
+ let java mods also do that when appliable, for auto-updates without restart or stuff!
