### ISSUE TITLE
Blacklisted mods in mod browser

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry-Suggestions#1636]
**Describe the content or mechanics you are proposing.**

a new text file (or something similar) in [MindustryMods](https://github.com/Anuken/MindustryMods) which will be read by the update script and these mods will not be put in the mod browser.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

so people can pr to put mods like [bleach](https://github.com/gdeft/bleach) in the text file and it can be discussed whether or not to blacklist to mods

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
oh absolutely

there's been talk for days ~~months years~~ about how to deal with malicious/critically broken mods
