### ISSUE TITLE
Show spawn zones on map

### ISSUE THREAD

**Issue by SmolBig** [Anuken/Mindustry-Suggestions#1637]
**Describe the content or mechanics you are proposing.**
Just a transparent red circle showing where the spawns are on the big map or something would be great.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would eliminate the need for flying around trying to find out what cul-de-sac the spawn is hiding in.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
#1495 #312

**Comment by SmolBig** [comment]
Ugh.

**Comment by NajimiOsana** [comment]
it doesn't really matter if its a duplicate, what matters is that anuke would at least see that the community wants it and see it.

**Comment by itcannotbe** [comment]
![Screenshot_20201224_182252](https://user-images.githubusercontent.com/45280919/103082508-386f2e00-4615-11eb-950b-d95dbf00da96.jpg)

It actually matters @NajimiOsana , because the developer won't add it in if it is not a good fit for the game, no matter how hard a certain group of people want it.
