### ISSUE TITLE
Add game rule that makes AI team logic blocks indestructible

### ISSUE THREAD

**Issue by Fish-Noises** [Anuken/Mindustry-Suggestions#1638]
**Describe the content or mechanics you are proposing.**
In game settings, both in the editor and before starting a game, there should be a toggleable setting that makes all Red Team logic blocks indestructible.
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As of now, using enemy logic blocks in a map has significant issues: Concealing it in a corner of the map makes it vulnerable to destruction. Fortifying the processor with defences causes the processor to not fit in with the environment.
Making enemy logic blocks indestructible solves the issue by safely allowing the blocks to hide away in a corner without unwieldy defences. This will preserve a map's terrain and atmosphere while still running its processes.

**Comment by joshuaptfan** [comment]
Should be solved by implementing an ["indestructible" flag](#1567) in the map editor for any block, not specific blocks.

**Comment by Kyllingene** [comment]
#1567
