### ISSUE TITLE
Double phase weaver's buffer/capacity

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry-Suggestions#1639]
**Describe what you would like changed, and why.**

Attempting to feed a phase weaver with 5 sand/s is very intensive. With the introduction of the new unloading mechanic from plastanium belts, it should make it some setups have improved flow due to an increased buffer.

Compared to other machines, this is only enough to run two operations if full.
Silicon,plastanium,alloy smelters, crucibles are capable of handling 5

**Describe the changes you want to propose. Include possible alternatives.**

Multiple the current buffer from 20 thorium and 20 sand, to be enough for at least 4 operations,
40 sand + 40 thorium
Possibly 
60 sand + 60 thorium (5 operations)

This will make it more consistent with other machines as well.

**Comment by sample-text-here** [comment]
If you only have 5 sand/sec, why/how would a buffer help?

**Comment by claw4oo** [comment]
> 
> 
> If you only have 5 sand/sec, why/how would a buffer help?

The input rate may vary, but it's mostly to match the amount of operations that other machines can do at a full inventory.
This would mostly effect distribution that have relatively slow/unstable input
