### ISSUE TITLE
Meltdowns shouldn't be fly swatters.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#164]
**Describe what you would like changed, and why.**
Since Meltdowns are too powerful. I propose a way to at least make units/blocks not vaporize immediately when a meltdown fires at it.

**Describe the changes you want to propose. Include possible alternatives.**
Meltdown damage shouldn't be a linearly dealt.

Like 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70

But more like 4, 8 ,12, 16, 20, 24 and so on.

Point being that the longer an entity is being hit by a meltdown, the higher damage it will receive.

Currently being hit by a meltdown for it's entire duration will deal 3080 damage spread around 220 ticks or 3 and 2/3 second.

While the incremental damage based on this suggestion will deal 3960.
For a comparison, being exposed for 1 sec will deal 312 instead of what would have been 840.

A good addition to this is having meltdown's fire time be affected by the type of coolant. not reload speed.

**Comment by TheSlaylord** [comment]
That could be useful if Meltdown's laser was persistent, but it only lasts for ~5 seconds after being shot and then recharging for ~3 seconds (with cryofluid).
That means that the damage would reset back to 4 after ~8 seconds. I don't think that meltdown should have such a change.

**Comment by itcannotbe** [comment]
Actually in code it delivers damage 12 times per second.
