### ISSUE TITLE
UnitLocate logic function addition

### ISSUE THREAD

**Issue by Mdbgamer** [Anuken/Mindustry-Suggestions#1641]
**Describe the content or mechanics you are proposing.**
Adding things like Conveyors and other things that are not already part of the function would greatly help with things like:
Automatic conveyor replacement logic!

Yeah, mainly that. Trying to brute force it left me with headaches and back to square 1.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Having this would help simplify things immensely, as stated previously. While you're at it, adding these kinds of things to other functions that don't already have them would be fantastic!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by scarf-generic** [comment]
this had been suggested before.

**Comment by scarf-generic** [comment]
#1260
#1242

**Comment by scarf-generic** [comment]
#974

**Comment by scarf-generic** [comment]
> [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

searching for `ulocate` allows you to find multiple issues suggesting this exact same thing. hmmm

**Comment by Mdbgamer** [comment]
> > [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> searching for `ulocate` allows you to find multiple issues suggesting this exact same thing. hmmm

Ah, there has? I tried everything I could think of to find it, amd couldn't. Er....oops?

**Comment by Mdbgamer** [comment]
> this had been suggested before.

Obligatory "If we make enough of these, maybe Anuke will add it"

**Comment by itcannotbe** [comment]
Ah yes. Obligatory "If anuke thinks it is not a good fit for the game, he won't add it. No mattter how many people ask for it"

**Comment by Mdbgamer** [comment]
> Ah yes. Obligatory "If anuke thinks it is not a good fit for the game, he won't add it. No mattter how many people ask for it"

You missed the joke lmao.

**Comment by Kyllingene** [comment]
So, since this is a duplicate (not going into whether or not it is your fault), can you close this?

**Comment by Mdbgamer** [comment]
> So, since this is a duplicate (not going into whether or not it is your fault), can you close this?

Oh, yeah, sure.
