### ISSUE TITLE
Merge stacks on StackConveyors

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#1642]
**Describe the content or mechanics you are proposing.**

![image](https://user-images.githubusercontent.com/56274831/103063273-a52aef80-4565-11eb-8b1f-090c217b4369.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Because of the new plastanium belt unloading feature, it's common to see smaller stacks than normal on conveyors. When backed up, merging the stacks on a conveyor would look cleaner.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
You have the simplest possible example here of two 5-stacks merging into one 10-stack. Any less convenient scenarios, such as a 1-stack followed by many 10-stacks, will lead to long cascading chain reactions.

**Comment by itcannotbe** [comment]
Also you forgot that plast conveyors don't really stop. So triggering a merge is more complicated than it seems.

**Comment by GreyMario** [comment]
..If your plastanium belts are backed up while you're using unloaders, you might be doing something wrong.

**Comment by oinkymoo** [comment]
have you considered that they might just be producing input in excess?
