### ISSUE TITLE
Show enemy drop zone while paused and/or on map

### ISSUE THREAD

**Issue by zackman0010** [Anuken/Mindustry-Suggestions#1643]
**Describe the content or mechanics you are proposing.**
I would like the enemy’s drop zone to be displayed in situations other than the player physically approaching it, such as looking around the area while paused or viewing the map.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
My play style is to quickly prepare defenses in advance before building up a larger supply line near the core. This usually ends up with me spending 1-2 minutes running around the map trying to find where the drop zone is located. Being able to easily find it from the beginning would seriously help pre-planning.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[Try again, but this time, Search harder] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by joshuaptfan** [comment]
Anuke stated his opinion on this in #312:

> > the player who is unfamiliar at the map doesnt need to search/go around the entire map which saves time.
> 
> Why is this a problem? Exploring the map and finding out where everything is part of the challenge. You have to know the terrain a little before placing down turrets.

**Comment by zackman0010** [comment]
Ah, thank you @joshuaptfan. I did do a quick search, but it’s hard to find things in over 1000 issues, especially when you’re on a mobile browser.
