### ISSUE TITLE
Suggestion to annoy anuke

### ISSUE THREAD

**Issue by catatagun** [Anuken/Mindustry-Suggestions#1644]
Im sorry anuke
**Describe the content or mechanics you are proposing.**
3 stuff first add rails plz 
2 stuff add teleport
1 stuff add speed up time thing

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Teleport cool
Rails look nice
Time speed useful

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by catatagun** [comment]
To make sure anuke no see this i close this

**Comment by catatagun** [comment]
Bye

**Comment by GreyMario** [comment]
How to get banned from posting issues in one easy step:

**Comment by catatagun** [comment]
Yes

**Comment by QmelZ** [comment]
amazing

**Comment by catatagun** [comment]
That is goal

**Comment by QmelZ** [comment]
![image](https://user-images.githubusercontent.com/59574967/103086341-6f354c00-45f5-11eb-97b7-6d96a6b32697.png)
yes

**Comment by NajimiOsana** [comment]
_**what's the point of annoying anuke**_

**Comment by catatagun** [comment]
Getting anuke annoyed

**Comment by Quezler** [comment]
ohno

**Comment by catatagun** [comment]
Oh no indeed

**Comment by catatagun** [comment]
Im not banned yet

**Comment by QmelZ** [comment]
> Im not banned yet

because the issue is closed
