### ISSUE TITLE
V6 Moding

### ISSUE THREAD

**Issue by Cardlo45** [Anuken/Mindustry-Suggestions#1645]
My Idea is to make an ingame Modmaker with grafical overlay an Mod/Map List

This Idea will help making Basic Mods witchout really needing to know how it works or needing how to setup everything. You will get an small UI with the mod-maker where you can set wich type what it should do and where you can see it
I personaly would say that then there is an implemented Example mod with all basic and the advanced Possibilitys for modding so you can get a better loock for modding also i would like to see an ingame mod list/mod search where you can see mods from other players (same with Maps)

*Edit because of so mush negative commands
To be clear:
1. I can Code a Mindustry mod
2. Im not a big fan of coding to code things i usualy ask my friends or use an grafical overlay
3. I am not THAT good at Coding (most time i get errors or something works wrong/not)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
Is it so hard to learn JSON?

**Comment by Cardlo45** [comment]
> Is it so hard to learn JSON?

No not for me but it would make it easyer for the who cant rraly code and it would make it easyer for the one who can code

**Comment by BlueWolf3682** [comment]
the wiki is updated

**Comment by Cardlo45** [comment]
> the wiki is updated

What?  I dont find the new things

**Comment by Humanoid-X** [comment]
I agree that some species of human really can't code, but HJSON is designed for someone who can't code. And is coding really that difficult after all?

**Comment by Cardlo45** [comment]
> I agree that some species of human really can't code, but HJSON is designed for someone who can't code. And is coding really that difficult after all?

For me it is not that hard but it would make it easyer and faster even for the people that can code fast and it would be possible to learn basic coding witch this

**Comment by itcannotbe** [comment]
[Does X means I didn't now?] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by Cardlo45** [comment]
> [Does X means I didn't now?] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

X = I have looked

**Comment by sample-text-here** [comment]
> This Idea will help making Basic Mods witchout really needing to know how it works

hjson is for people who dont know how to use javascript or java

> or needing how to setup everything. 

is making mod.json and a few folders that hard?

> You will get an small UI with the mod-maker where you can set wich type what it should do and where you can see it

an in-game mod maker would add too much bloat for something which is already very easy to make

> also i would like to see an ingame mod list/mod search where you can see mods from other players (same with Maps)

already added
![image](https://user-images.githubusercontent.com/56274831/103194040-197dcf80-4893-11eb-8a75-d869dc87a261.png)

**Comment by Kyllingene** [comment]
HJSON is horrendously easy as it is. I mean, how hard is it for a human being who knows English to read this:
```type: SingleTurret
name: My Turret
description: My Turret
reload: 1
ammo: {
  copper: {
    damage: 20000
    lifetime: 20000
  }
}

requirements: [
  copper/1
  lead/1
]

category: turret
research: duo
```

Imagine asking the developers of JavaScript to make a thing that makes programming easier for people who don't know how. Things like [Scratch](https://scratch.mit.edu) exist. This is a job for people who like to make things like this, not a job for people who are already making a hundred other things.

**Comment by Cardlo45** [comment]
> > This Idea will help making Basic Mods witchout really needing to know how it works
> 
> hjson is for people who dont know how to use javascript or java
> 
> > or needing how to setup everything.
> 
> is making mod.json and a few folders that hard?
> 
> > You will get an small UI with the mod-maker where you can set wich type what it should do and where you can see it
> 
> an in-game mod maker would add too much bloat for something which is already very easy to make
> 
> > also i would like to see an ingame mod list/mod search where you can see mods from other players (same with Maps)
> 
> already added
> ![image](https://user-images.githubusercontent.com/56274831/103194040-197dcf80-4893-11eb-8a75-d869dc87a261.png)

Firts some people dont want to know how it works they just want make a new turret


> HJSON is horrendously easy as it is. I mean, how hard is it for a human being who knows English to read this:
> 
> ```
> type: SingleTurret
> name: My Turret
> description: My Turret
> reload: 1
> ammo: {
>   copper: {
>     damage: 20000
>     lifetime: 20000
>   }
> }
> 
> requirements: [
>   copper/1
>   lead/1
> ]
> 
> category: turret
> research: duo
> ```
> 
> There aren't even any quotes!
> 
> Imagine asking the developers of JavaScript to make a thing that makes programming easier for people who don't know how. Things like [Scratch](https://scratch.mit.edu) exist. This is a job for people who like to make things like this, not a job for people who are already making a hundred other things.

And what is wrong that i want something to be easyer even it easy

**Comment by itcannotbe** [comment]
> And what is wrong that i want something to be easyer even it easy

The question itself.

**Comment by Cardlo45** [comment]
> > And what is wrong that i want something to be easyer even it easy
> 
> The question itself.

-_- ...

**Comment by itcannotbe** [comment]
Also maintaining a gui for a mod maker is actually a lot of unnecessary work. This is a game, not a programming software.

Heck if there is a GUI for every program possible I want to code. It would make a life a lot easier. But there isn't. Because you can't account for every edge case.

Also if a GUI gets added it would easier to make trash mods, like literally one liner edits. No one wants that, but many would really want to make it for stupid reasons.

So yes. Asking for something easier for a thing very easy to do is the problem.

What's next? Asking a gui for making JS mods? That's ~~redacted~~

**Comment by Kyllingene** [comment]
> And what is wrong that i want something to be easyer even it easy

The reason this is wrong is because not only does it show you aren't willing to put in effort to learn something, you also want other people to spend their time on an unnecessary addition so that you don't have to.

**Comment by Kyllingene** [comment]
Another thing I just thought about:

> Also if a GUI gets added it would easier to make trash mods, like literally one liner edits. No one wants that, but many would really want to make it for stupid reasons.

> also i would like to see an ingame mod list/mod search

How would you find anything worthwhile if you are enabling hundreds upon hundreds of terrible, no-effort mods to be published with zero limiting factor?
