### ISSUE TITLE
update the guns with the next massive update

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#1647]
update the guns with the next massive update so that they improve with the incoming resources and how the core could improve with its more free-spirited versions, for example, the incinerator normally works fine, and if you apply the kinet, it enters overload mode and takes damage from extreme overheating, but does 300 percent more damage
![2020-12-25_00-23-03](https://user-images.githubusercontent.com/71027210/103101073-5dc95f80-4648-11eb-9b94-1aa4bc53621a.png)

**Comment by Jammo2000** [comment]
Recoil? There is no recoil in this game. Do you mean knockback?

**Comment by GreyMario** [comment]
This falls under "additional configuration of blocks". Also, no.

**Comment by Goobrr** [comment]
~~cant you find a mod for this~~

**Comment by Axzye** [comment]
this looks very suspiciously like it's been google translated 20 times

**Comment by GreyMario** [comment]
Speaking of translations, what the _hell_ language is this being translated from that "Surge Alloy" ends up translating back to "kinetics"?

I know we're having some Blind Idiot Translation problems overall, but yikes.

**Comment by Humanoid-X** [comment]
>what the *hell* language is this being translated  from that "Surge Alloy" ends up translating back to "kinetics"?
Stop talking about surge alloy, "surge alloy" don't exist in real world. But... what the hell... "Thorium" ends up translating to "noriy"!?

**Comment by GreyMario** [comment]
@Humanoid-X Translations that don't suck will at least come up with something similar to "electric alloy", not something so ass-backwards that it machine back-translates to "kinetics".
