### ISSUE TITLE
Add searchbar to mod browser

### ISSUE THREAD

**Issue by Surviavlist** [Anuken/Mindustry-Suggestions#1648]
**Just searchbar for mod browser.**

**This will help you find mod you need. Now there is some mods, but sometimes you need to find a mod by name.**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Gdeft** [comment]
It's already implemented.

**Comment by QmelZ** [comment]
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

press [X] to doubt
