### ISSUE TITLE
IDAES FOR THE FOLLOWING TOOLS

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#1649]
![2020-12-25_00-40-50](https://user-images.githubusercontent.com/71027210/103106679-0f2cbd00-466a-11eb-94e3-7a2f61647390.png)

**Comment by GreyMario** [comment]
What are you yammering about? Use words, not pictures. Also, _use the template._

**Comment by ZirKNkium611** [comment]
what is rhos supposed to mean

**Comment by the-kido** [comment]
Ive been sat here for 10 minutes thinking about what the hell this is

**Comment by Goobrr** [comment]
He clearly wants unit factories to be put into reconstructors to make more reconstructors, and the tsunami turret to build giant squares of liquid routers which can be given metaglass and surge for enhancements.

**Comment by Quick-korkc** [comment]
what the hell is this?

**Comment by Humanoid-X** [comment]
Mmm... What are you saying? Do you want tsunami to follow liquid routers and shoot them? Or do you want tsunami to build liquid routers? And where is the template? Aaa what is this? Why aren't you replying to them which is clearly waiting for some appropriate explanation? Mmm? Why?

**Comment by Yell245** [comment]
I think he's talking about more tiers of wave. Why tho

**Comment by Kyllingene** [comment]
It may be that they want more levels of... liquid routers?

**Comment by Kyllingene** [comment]
Now that I see it again, it is most certainly a request for more wave levels.

> Why tho
