### ISSUE TITLE
[QOL] Resource Indicator for Schematic Drills

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#165]
**Describe the content or mechanics you are proposing.**
Add an indicator on schematic drills so you can see what resource the drill will be mining.

Schematic does not show what resource is being mined
![Schematic has no indicator](https://user-images.githubusercontent.com/58778985/81723083-51ddb400-9450-11ea-889f-ccec189a15ec.jpg)

**Adding something like this to schematic drills:**
drill with resource and speed
![Default indicator with speed](https://user-images.githubusercontent.com/58778985/81723031-3c688a00-9450-11ea-92fb-5085a6ce35ec.jpg)
drill with resource
![Default indicator](https://user-images.githubusercontent.com/58778985/81723056-468a8880-9450-11ea-84bf-a16a39794b94.jpg)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would prevent resource contamination when placing schematics with drills (because now you know what resource is about to be mined).

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
Implemented and can be closed
