### ISSUE TITLE
Schematic Opacity

### ISSUE THREAD

**Issue by bruhmoment271** [Anuken/Mindustry-Suggestions#1651]
**Describe the content or mechanics you are proposing.**
Implement a setting which controls how opaque schematics or buildings will appear when selecting where to place them.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Being able to see the ground under a schematic when selecting where to place them would make placing schematics including drills or pumps easier.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
good

**Comment by Dasius** [comment]
I would prefer this be a toggle key, press Alt for example and it goes normal ghost, release and back to normal. That way you get the best of both worlds.
