### ISSUE TITLE
Printflush to unit/Ucontrol say

### ISSUE THREAD

**Issue by Jammo2000** [Anuken/Mindustry-Suggestions#1652]
**Describe the content or mechanics you are proposing.**
Add the ability to printflush to a unit, which would make the text display above the unit in a similar way to how chat messages are displayed above a player. Alternatively, a ucontrol say command could be added, but that option seems less useful because it would be more difficult to add programmatic variables to the text.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would allow:
1. Better debugging of logic functions that use multiple units, and better unit debugging in general.
2. Units being used for something could be labeled with what they are doing, ex: "Ferrying titanium from 270,110 to core" This would allow for easy identification and location of logic unit control, and also allow it to make more sense to players who don't use logic.
3. (less likely) If a logic script needs to get a player, a unit could go to the player and say "follow me". Not sure if this would be useful, but it occurred to me.
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
good
