### ISSUE TITLE
Indicator for very slow firing unit weapons

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#1653]
**Describe the content or mechanics you are proposing.**
A small bar (or some other shape) on very slow firing unit weapons which empties when it fires and becomes full when it can fire again.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
While the recoil of a weapon already exists for this purpose, it can be hard to make out in combat and isn't too intuitive. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
This would be nice. Sometimes it can be confusing to tell if you are not firing or just reloading.
