### ISSUE TITLE
Hint about red sector

### ISSUE THREAD

**Issue by Quick-korkc** [Anuken/Mindustry-Suggestions#1655]
**Describe the content or mechanics you are proposing.**
i found some people have no idea what red sector is
and why not?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Hopefully people can understand what red sector is and can handle them

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
Like, if you choose the red sector it literally says "Enemy base", that should be self-explanatory

**Comment by Legomonster33** [comment]
Red = danger / bad

Red sector hmmmmmm
Maybe it is *dangerous* or *difficult*
Also you can select it and it literally says its an enemy base

**Comment by Yell245** [comment]
If people don't understand that literally danger color colored sector with the same red text saying it's an enemy base that it's an enemy base, it's their problem

**Comment by Dasius** [comment]
I agree its obvious it represents an enemy base but less obvious is what that means. It might be mistaken to mean only that this is an attack map rather than it also means your sectors can come back under attack until it is beaten, so I don't think a little clarification on that would hurt.
