### ISSUE TITLE
Respawn in core should be available even when you are in your base unit

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1656]
**Describe what you would like changed, and why.**

To respawn in core, I currently have first to find another unit and enter that unit before I'm allowed to respawn.  I think this should be changed.

**Describe the changes you want to propose. Include possible alternatives.**

I propose that respawn always be available, e.g. on PC the default key of 'v' should respawn me any time.

For example, if my main ship is damaged, there are currently two ways to repair it.
1. Build a Repair Point or fly to an existing one, then wait for it to repair me.
2. Find another unit of mine, then respawn.  If I'm nearby another of my units already, this is MUCH faster than the former because it is instantaneous - no need to wait for a block to build and for its beam to actually repair me.

That seems silly to me.

Additional thoughts:
Perhaps limit this to only be available if damaged?
Perhaps allow it to be disabled in a map if desired?

**Comment by Legomonster33** [comment]
yes

**Comment by itcannotbe** [comment]
Or we could just penalize respawning at the core by:

Killing the unit controlled prior to respawn and making the respawn timer equivalent to the time needed to reach the core with the current unit, say distance/(speed/second)

**Comment by Humanoid-X** [comment]
no

**Comment by itcannotbe** [comment]
Yes.

**Comment by Humanoid-X** [comment]
Well imo we should never respawn in core (too OP) but respawn in your own unit. I mean have your unit hovering idly there when you enter another unit.

**Comment by Legomonster33** [comment]
> Or we could just penalize respawning at the core by: Killing the unit controlled prior to respawn and making the respawn timer equivalent to the time needed to reach the core with the current unit, say distance/(speed/second)

No

**Comment by itcannotbe** [comment]
Yes

**Comment by itcannotbe** [comment]
> Well imo we should never respawn in core (too OP) but respawn in your own unit. I mean have your unit hovering idly there when you enter another unit.

What are the reasons why we actually want to respawn from the core?

I mean as a core basic unit.

**Comment by sk7725** [comment]
3. place down a router, control, press v.
4. Not instant but if your game rules are "reasonable" it should take less than 2 seconds.

**Comment by Mothership007** [comment]
Just build a router and take control and respawn, its that easy

**Comment by swenkeratmicrosoft** [comment]
@itcannotbe 

> > Well imo we should never respawn in core (too OP) but respawn in your own unit. I mean have your unit hovering idly there when you enter another unit.
> 
> What are the reasons why we actually want to respawn from the core?
> 
> I mean as a core basic unit.

To repair damage on your core base unit.

Right now repairing damage requires a repair point (requires power, silicon), a unit that can repair you, or respawning in core.

@Mothership007

> Just build a router and take control and respawn, its that easy

Wait, you can take control of a ROUTER?  WHY?!?

And it gives you a silly achievement, too.  LMAO.

Ok, yeah, given that, I really don't need this feature, so I'm going to close this issue along with this comment...but HOW the FRAK was I supposed to know I could do that?

**Comment by laok233** [comment]
router best block

**Comment by Axzye** [comment]
you can press ctrl on a core to regenerate your health
