### ISSUE TITLE
In a build queue, clicking one should switch to build it.

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1657]
**Describe what you would like changed, and why.**

Consider the case where I queue 15 not-fast items up for build (anything that takes a second or more).

After I've started building one of them that takes time, I move away from the group (so I'm building nothing) but one or more items are left partially built.  I then move back.  As I approach, the closest thing to me starts building.  I can then click on any partially built item to switch to building (finishing) it.

However, if I have NOT started an item, I can't choose to build it next by clicking on it.

If I'm careful, I can fly around to force every single item to start building a tiny bit, then I can choose the build order by clicking each item.  I shouldn't have to fly around to choose the build order - I should just be able to click an item that's queued and say "build that next".

Mostly, this is useful when I queue up several items, then realize I want to switch the order afterwards in some significant way, e.g. move the last item first.  Right now, I can do this in two ways - un-queue everything and re-queue them in the order I want (painful), or do some fly-around nonsense to start them all building then click them in the order I want (also painful).

**Describe the changes you want to propose. Include possible alternatives.**

The limitation that I can only click a queued item to build it next should be removed.

**Comment by RedstonerKBC** [comment]
I think this used to be a feature and I prefered it the old way. Sometimes you build many things but the silicon is out so you build other things to let the silicon fill up. Please add this back.

**Comment by swenkeratmicrosoft** [comment]
@RedstonerKBC 

There are situations even more important than low resources.  Here's an example.

Make a Schematic that has a Melter and Disassembler hooked up to each other via a pipe.  On a new map, build the drills and belts carrying the scrap to the input locations where you intend to build the schematic.  (That way, you will have some scrap built up to start being used by the time the schematic is finished - useful if the source of scrap is far away from where you intend to build the melter).  Then, lay down the schematic.

If the melter and pipe build before the Disassembler, the scrap melts into slag and leaks out of the pipe in the location where the Disassembler is going to get built, and the Disassembler is destroyed by melted slag during construction!  This has happened to me several times.  :(

**Comment by Jammo2000** [comment]
> @RedstonerKBC
> 
> There are situations even more important than low resources. Here's an example.
> 
> Make a Schematic that has a Melter and Disassembler hooked up to each other via a pipe. On a new map, build the drills and belts carrying the scrap to the input locations where you intend to build the schematic. (That way, you will have some scrap built up to start being used by the time the schematic is finished - useful if the source of scrap is far away from where you intend to build the melter). Then, lay down the schematic.
> 
> If the melter and pipe build before the Disassembler, the scrap melts into slag and leaks out of the pipe in the location where the Disassembler is going to get built, and the Disassembler is destroyed by melted slag during construction! This has happened to me several times. :(

This new feature would only change build order if the player wants it to. That problem does not apply here.

**Comment by swenkeratmicrosoft** [comment]
> > @RedstonerKBC

> This new feature would only change build order if the player wants it to. That problem does not apply here.

That problem totally applies here.  If I could choose the build order, I would immediately choose to build the disassembler first every time I placed the schematic.  Problem is then solved.

**Comment by Kyllingene** [comment]
I have been aggravated by this *so* much, please do add this!
