### ISSUE TITLE
Dark sand and dark 'not' sand are too hard to distinguish

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1658]
**Describe what you would like changed, and why.**

Refer to these screenshots from PC.  Inside the red circle, dark sand is on the right and what I'm calling dark 'not' sand is on the left.  The first screenshot is on the regular map; the second is on mini-map at maximum zoom.

![Screenshot](https://user-images.githubusercontent.com/37818012/103141675-808d5f80-46ac-11eb-873c-dfdb8c9f8c28.jpg)

![screenshot2](https://user-images.githubusercontent.com/37818012/103141697-cf3af980-46ac-11eb-8e2b-04cddf9eccf6.jpg)

Right now, texture is the only way to distinguish between dark sand and dark 'not' sand.  On the mini-map, it's completely impossible.  I have to pause and scroll around the entire map to figure out what's what (not using the mini-map), but that's the ONLY terrain difference where I can't use the mini-map.

**Describe the changes you want to propose. Include possible alternatives.**

Make one of the two terrains a different color so that it can easily be distinguished.  For example, a lighter grey for dark 'not' sand (on both regular map and mini-map) would be super useful.  (Keep the texture difference, of course.)

**Comment by joshuaptfan** [comment]
The "dark not sand" is called stone in the map editor.

**Comment by QmelZ** [comment]
"dark not sand" sounds cooler than "stone" though

**Comment by swenkeratmicrosoft** [comment]
Even the good purple and even better purple ;) terrains are distinguishable on the mini-map.

**Comment by catatagun** [comment]
> The "dark not sand" is called "stone" in the map editor.

Totaly not called basalt

**Comment by joshuaptfan** [comment]
Oops, stone is the default ground tile, but basalt is the one that has the exact same color scheme as dark sand, only the pattern is different.

**Comment by whio** [comment]
Coal patches on dark sand are also difficult to spot. I would suggest making dark sand a shade lighter, something in between regular sand and what it is now, and leaving basalt alone.

**Comment by swenkeratmicrosoft** [comment]
> Coal patches on dark sand are also difficult to spot. I would suggest making dark sand a shade lighter, something in between regular sand and what it is now, and leaving basalt alone.

Well, coal patches on basalt are equally hard to spot, so that's honestly a separate issue.

What really bugs me about dark sand versus basalt is that the minimap doesn't help - they appear identical.  At least you can see coal on the minimap even if it's hard to see on the main map.

**Comment by swenkeratmicrosoft** [comment]
...
...
...

I just encountered campaign sector 161 (adjacent to Biomass Synthesis Facility) and got to play "find the sand".  It was...not exactly my favorite moment of gameplay so far.  Check it out if you think this isn't a problem.

**Comment by itcannotbe** [comment]
Lets play a game of which one is basalt and which one is dark sand.

![Screenshot_20201230_151011_io anuke mindustry](https://user-images.githubusercontent.com/45280919/103335808-2e37ae80-4ab1-11eb-9465-1186e05bf5a0.jpg)
![Screenshot_20201230_150806_io anuke mindustry](https://user-images.githubusercontent.com/45280919/103335811-30017200-4ab1-11eb-9942-362cf3e49e34.jpg)

**Comment by swenkeratmicrosoft** [comment]
@itcannotbe 

Sure.  But you're only allowed to use the minimap.

**Comment by itcannotbe** [comment]
Guess which one is it.

**Comment by swenkeratmicrosoft** [comment]
Since I just spent quite a bit of time distinguishing it, I happen to know that dark sand is on the left, in your extremely simple case.

Now, go and find it in sector 161.

**Comment by itcannotbe** [comment]
Anyone got a full minimap of 161

**Comment by swenkeratmicrosoft** [comment]
What, you haven't finished the campaign?

**Comment by itcannotbe** [comment]
No. I just don't have my savefile with me at all times.

**Comment by swenkeratmicrosoft** [comment]
There is only one patch of water in sector 161.  There are at least 11 patches of sand.  Only two of them are water-adjacent.

**Comment by swenkeratmicrosoft** [comment]
Oh, and that sand can only be accessed if you can make a phase conveyor or mass driver.  All of the sand you can reach by regular belts is not anywhere near water.

**Comment by swenkeratmicrosoft** [comment]
@itcannotbe 

Finally, once you've spent your time finding the dark sand on sector 161 (whenever that's convenient)...

Convince me that it was *just as easy* as finding literally any other resource on that map.  Convince me that you had FUN doing it.  Convince me that you'd LOVE to do that every time you play Mindustry.

Good luck.

Because that's the point of the OP.  It's not that it can't be done, it's that it's harder than it should be and makes the game less fun as a result.

**Comment by whio** [comment]
I play on mobile, and there's no minimap there, so that's something to take into consideration as well. It doesn't help that the screen is tiny either.
