### ISSUE TITLE
Multi-factory

### ISSUE THREAD

**Issue by SnakkiZXZ** [Anuken/Mindustry-Suggestions#166]
### multi-factory 
The furnace is capable of producing several types of materials that can be switched with buttons. 
![miniGif_20200512205627](https://user-images.githubusercontent.com/62109325/81725352-26ce8100-949f-11ea-84e5-5192c5021e07.gif)

I believe that this type of factory will help reduce and facilitate the creation of improved replicas of conventional Factories **6.0**
I've shown the method of combining a _large silicon smelter_ and a _large metaglass forge._

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

_P.S. This time he painted it in detail. _

**Comment by SnakkiZXZ** [comment]
I hope it's all good this time.

**Comment by RogueRedHawk** [comment]
I believe this has already been confirmed as a feature that will not be added, sorry.
