### ISSUE TITLE
Mono's, Poly's, and Mega's should go to nearest repair point when at low health

### ISSUE THREAD

**Issue by bloool** [Anuken/Mindustry-Suggestions#1660]
**Describe what you would like changed, and why.**
When flying support units lower than the mega are at low health they should automatically fly towards the nearest working repair point

**Describe the changes you want to propose. Include possible alternatives.**
Currently, in the game mega units will heal any structure that is damaged, however, most of the time, the structure is a wall, and they normally get themselves damaged or even killed while doing it, so that's why I want this change. An alternative to this could just be a change in AI to stay away from enemies' projectiles and enemies themselves.

**Comment by catatagun** [comment]
Yes

**Comment by Humanoid-X** [comment]
yes

**Comment by GreyMario** [comment]
No.

No other player-owned AI features this kind of avoidance and self-preservation behavior

**Comment by Quick-korkc** [comment]
lets wait until someone make logic about that

**Comment by D-player1** [comment]
Use logic

**Comment by the-kido** [comment]
unit bind :mega:
sensor the health of the unit
if health < (max health - 1)
unit locate repair point rx ry
unit move rx ry

Let me say I am horrible at logic yet i still know how to do something as simple as this. 
This doesn't have to be a thing that happens in the game, rather, controllable by the player.

**Comment by Kyllingene** [comment]
```
sensor repairx point1 @x      #gets the location of a repair point it is bound to

sensor repairy point1 @y

ubind @mega      #replace @mega with whatever unit you desire

sensor maxhp @unit @maxHealth      #gets the current units max health

sensor hp @unit @health      #gets the current units health

op div percent hp maxhp      #gets the current units health percentage

jump 8 greaterThan percent 0.75      #if its health is greater than 75%, skip the next line

ucontrol move repairx repairy 0 0 0      #make the unit go to the heal point

set @unit 0      #unbind the unit, because either it is healed or doesnt need healing
```

Now, keep in mind, this has two minor problems: one, the units hover for a few seconds after being unbound. However, this can be both a blessing and a curse, depending on how fast they get healed. Also, it requires you to bind the processor to a repair point. But seriously, this would be super easy to make into a cheap schematic. This is easy enough to do with logic that I do not believe that a new piece of pathfinding (however simple) is necessary.

**Comment by Humanoid-X** [comment]
@Kyllingene Wow, good work. Well done!

**Comment by Kyllingene** [comment]
Thank you!
