### ISSUE TITLE
Ai core units do full damage to buildings

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1661]
**Describe what you would like changed, and why.**
Ai controlled gammas alphas and betas should do damage to building
Cuz it makes them like mini zeniths on survival
And makes them more attacklike on survival

> 

**Describe the changes you want to propose. Include possible alternatives.** ai gammas betas and alphas would deal full damage to buildings on the enemy team

**Comment by catatagun** [comment]
Yes

**Comment by Quick-korkc** [comment]
i think anuke already said about that somewhere

**Comment by catatagun** [comment]
Said about what

**Comment by Quick-korkc** [comment]
damage from those 3 units

**Comment by ZirKNkium611** [comment]
no

**Comment by Humanoid-X** [comment]
What do you mean by "full damage"? Aren't they already dealing damage?

**Comment by joshuaptfan** [comment]
[Quote from Anuke](https://steamcommunity.com/app/1127400/discussions/0/2961643452364046880/):

> All core-made ships deal about 1% of their normal damage to structures. This was originally implemented to prevent PvP rushing, but it also prevents players from cheesing early attack maps by chipping away at the enemy core.
> 
> If you want to deal damage to structures, make Flare units, they're cheap and can be commanded into position around core units easily.

**Comment by catatagun** [comment]
A

> [Quote from Anuke](https://steamcommunity.com/app/1127400/discussions/0/2961643452364046880/):
> 
> > All core-made ships deal about 1% of their normal damage to structures. This was originally implemented to prevent PvP rushing, but it also prevents players from cheesing early attack maps by chipping away at the enemy core.
> > If you want to deal damage to structures, make Flare units, they're cheap and can be commanded into position around core units easily.

I said ai controlled like when they are spawned in by a enemy spawn
