### ISSUE TITLE
new construction effect feedback

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1662]
**Describe what you would like changed, and why.**

the new building lasers are visually confusing, nice that they are team colored but deconstruction looks like crux.

**Describe the changes you want to propose. Include possible alternatives.**

never render the lines like this:
![Screen Shot 2020-12-26 at 17 58 59](https://user-images.githubusercontent.com/3179271/103155946-44d5c100-47a4-11eb-9f2e-3af7b37df18c.png)

but always like this:
![Screen Shot 2020-12-26 at 17 59 10](https://user-images.githubusercontent.com/3179271/103155943-43a49400-47a4-11eb-8022-0102a4da6e49.png)

and when deconstructing, don't chance the color but just simply move the lines to the player instead of away.

**Comment by Anuken** [comment]
> the new building lasers are visually confusing, nice that they are team colored but deconstruction looks like crux.

I am aware, but destruction effects are always red, while construction effects are always orange. Orange deconstruction beams are inconsistent with building effect colors, and make it harder to spot griefing/deconstruction in general.

> never render the lines like this:

I knew someone would say this, but it's not possible without massive performance penalties and/or a visual mess. Beams are all drawn in a single buffer, like shields. Encoding directional data in the RG channels is possible but messy and won't look good when multiple beams overlap.

> and when deconstructing, don't chance the color but just simply move the lines to the player instead of away.

That is subtle to the point of being nearly impossible to differentiate.

**Comment by Legomonster33** [comment]
> I knew someone would say this, but it's not possible without massive performance penalties and/or a visual mess. Beams are all drawn in a single buffer, like shields. Encoding directional data in the RG channels is possible but messy and won't look good when multiple beams overlap.

have the pattern that they overlay from be a set of circles, expanding away from the thing being built, instead of a set of lines?

**Comment by Anuken** [comment]
> expanding away from the thing being built

Again, it's one big buffer. There is no information about "the thing being built" in the buffer. It encompasses *the whole screen*.

**Comment by joshuaptfan** [comment]
> I knew someone would say this, but it's not possible without massive performance penalties and/or a visual mess. Beams are all drawn in a single buffer, like shields. Encoding directional data in the RG channels is possible but messy and won't look good when multiple beams overlap.

Perhaps the effect should be changed to something that looks less directional, then.

**Comment by Legomonster33** [comment]
> > expanding away from the thing being built
> 
> Again, it's one big buffer. There is no information about "the thing being built" in the buffer. It encompasses _the whole screen_.

It could expand away from the center of the screen?, but that isn't perfect either.

**Comment by RogueRedHawk** [comment]
@Legomonster33 

>It could expand away from the center of the screen?,

This wouldn't work, because it would look weird on mobile or while free panning, and more importantly the effect wouldn't work on teammates.

**Comment by Legomonster33** [comment]
> @Legomonster33
> 
> > It could expand away from the center of the screen?,
> 
> This wouldn't work, because it would look weird on mobile or while free panning, and more importantly the effect wouldn't work on teammates.

Yeah thats why I say it isn't perfect
