### ISSUE TITLE
Logic: Keep jump arrow highlighted on tap

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry-Suggestions#1663]
**Describe the content or mechanics you are proposing.**
When a jump statement points off-screen, there is no way to confirm in-editor where it is pointing to, without transferring the logic to an external text editor and looking at line numbers.

Desktop users are currently able to highlight the arrow by hovering over the start point (why isn't the hover target larger, like the entire jump statement?); mobile users have no way to highlight the arrow.

I propose that when you click/tap on the drag handle (the title bar) and/or uninteractive areas of a jump statement, the jump arrow will stay highlighted until you click/tap on something else, so that you can scroll up/down to see the destination.

![Logic Jump](https://user-images.githubusercontent.com/15149002/103156370-cf92cd80-475c-11eb-8b1c-3c5f390c1724.png "Where does this go? No one knows.")

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will make troubleshooting logic, and understanding logic written by others, much easier, for both desktop and mobile users.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
#1529 would also help out with this issue, although has a different implementation.

**Comment by joshuaptfan** [comment]
That suggestion is asking for a lot more. I'm keeping this suggestion small and simple enough that it should be extremely easy to implement. Jump arrow highlighting is already implemented, all that is needed is for the conditions for the highlight to be shown to change.

**Comment by Kyllingene** [comment]
Yes, it is much easier to use this suggestion, I was mostly just linking the two.

**Comment by Philosophist** [comment]
As I mentioned on #2017, a solution for down the road with greater popularity and resources would be to style the editor as a jigsaw style scripting tool, as is done on MIT's Scratch.

Also, one more idea to throw at this problem would be allowing the object lines of the arrows to also function as a part of the overall button that highlights the arrow. Right now, only the triangle head of the arrows triggers the highlighting when you hover over it.
