### ISSUE TITLE
A volcanic sector

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1664]
**Describe the content or mechanics you are proposing.**
I think there should be another mid-game sector called "The Hotlands". The hotlands would be alike the Biomass Synthesis Facility as it would unlock new technologies. I think that this sector would have alot of basalt, slag (which is never seen in the campaign) and also other hot stones. It would also have alot of magma rock for thermal power. When you capture the hotlands, you would unlock thermal power generator, the melter and everything after the melter. This would be a hard sector. There would be all resources exept thorium. The sector would be captured at wave 35 when a Arkyid attacks.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will add a sector with slag and will bring more oppoturnity to what mindustry players can do. For example, you could do alot with the slag such as make a surge alloy factory, etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
There was a new map added in 6.0, called Molten Lake, it should have been added to the campaign (after replacing the random ore generation with manually placed patches).

The ship has probably sailed for map changes to Serpulo, as some players have already been to every sector.

**Comment by jaygamer81** [comment]
> There was a new map added in 6.0, called Molten Lake, it should have been added to the campaign (after replacing the random ore generation with manually placed patches).
> 
> The ship has probably sailed for map changes to Serpulo, as some players have already been to every sector.

Hmm I still think it could be added. I thought of a moon for it but thatd be stupid since you need the planetary launcher to go anywhere off Serpulo.

**Comment by Sanya2907** [comment]
Or just make a zone on serpulo with molten lakes and magma blocks. ATM I didn’t see any slag/volcanic blocks on serpulo excluding campaign.
