### ISSUE TITLE
power source: 10k is not enough

### ISSUE THREAD

**Issue by laok233** [Anuken/Mindustry-Suggestions#1665]
**Describe what you would like changed, and why.**
![image](https://user-images.githubusercontent.com/72604018/103158179-68f0cc80-47bb-11eb-954f-2ee3fb7d5156.png)
10k is not enough to run thing that requires a big amount of power.

**Describe the changes you want to propose. Include possible alternatives.**
more power, like 20k o higher.

**Comment by Legomonster33** [comment]
just build more power sources

**Comment by laok233** [comment]
so....
![image](https://user-images.githubusercontent.com/72604018/103158366-31831f80-47bd-11eb-9cd7-3610fbde603f.png)

**Comment by joshuaptfan** [comment]
[It was buffed to 100k just after the recent update.](https://github.com/Anuken/Mindustry/commit/da96b234413b2a5ad54f9408dcdcb15cac5d6fa7)

**Comment by Quezler** [comment]
^

**Comment by DeltaNedas** [comment]
@laok233 close

**Comment by laok233** [comment]
> @laok233 close

ok

**Comment by Legomonster33** [comment]
> so....
> ![image](https://user-images.githubusercontent.com/72604018/103158366-31831f80-47bd-11eb-9cd7-3610fbde603f.png)

infinitely outputs power =! outputs infinite power

**Comment by catatagun** [comment]
Power 100k
