### ISSUE TITLE
World domination achievment

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#1666]
**Describe the content or mechanics you are proposing.**

Achievement for when you have conquered all of the sectors of serpulo

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The end game goal

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
You mean this Steam achievement that is already in the game?
![Global Domination](https://user-images.githubusercontent.com/15149002/103160570-ca00ac00-478b-11eb-8135-12415982c0b7.png)

**Comment by walksanatora** [comment]
I am gound zero nub
