### ISSUE TITLE
unit command balancing

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1667]
**Describe what you would like changed, and why.**
give players more control of their commanded units.

**Describe the changes you want to propose. Include possible alternatives.**
any or all of the following would be good for increasing the control players have over the units they command
- allow dragging of items from commanded units inventory to other commanded units/the player
- allow the player to control the order and orientation of commanded units
- allow the player to control the distance between player and commanded units
- add a preview that can be enabled/disabled in settings for which units would be commanded if the command key was pressed

**Comment by SMOLKEYS** [comment]
People agree with this in discord quite well, i think this should be a feature request.

**Comment by scarf-generic** [comment]
> People agree with this in discord quite well, i think this should be a feature request because it adds new additions.

yeah, i started writing it in the form of just rebalancing commanded units because they kind of suck compared to logic. near the end i decided to bundle all the other related ideas i had. whoops :/
