### ISSUE TITLE
show enemy block health on hover

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1669]
**Describe what you would like changed, and why.**

currently this line of code prevents any bars from rendering on blocks not of your team:
https://github.com/Anuken/Mindustry/blob/8d186493238dfba25137d8398c8eef2c51849ef0/core/src/mindustry/entities/comp/BuildingComp.java#L1024

**Describe the changes you want to propose. Include possible alternatives.**

would be neat if there was a whitelist for the health bar, since judging damage just by the visual break overlay is tedious 🤔 

(tried implementing it myself by staring at the code for a while but i couldn't find a clean point in the code to modify)

**Comment by zethnest** [comment]
Suggestion for the display? The ol classic simple red and green healthbar hovering above or below them?
