### ISSUE TITLE
Correct the Inverted Sorter + Unferflow Gate

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#167]
**Describe what you would like changed, and why.**
Simply removing the mechanic of inverted sorter + underflow would break a lot of schematics, but there is different solutions other then that.

**Describe the changes you want to propose. Include possible alternatives.**
I think that what should happen is when you chain inverted sorter and underflow, there should be some kind of delay with it, so instead of happening instantly or at the FPS of the host, it would transfer slower with some kind of delay like a router chain.

**Comment by ritzip** [comment]
[Anuke does not want to](https://github.com/Anuken/Mindustry/pull/1791)

**Comment by ritzip** [comment]
I still want it to change though
![Screenshot_20200502-2119572](https://user-images.githubusercontent.com/49394064/86310687-383b3a80-bc51-11ea-8049-e88a824053ac.png)

**Comment by zethnest** [comment]
I don't understand what you're showing

**Comment by itcannotbe** [comment]
[It is a link as well as this one.](https://github.com/Anuken/Mindustry/pull/1791)
