### ISSUE TITLE
Who allowed this to exist?

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry-Suggestions#1670]
**Describe what you would like changed, and why.**

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by TranquillyUnpleasant** [comment]
Oops pressed enter accidentally, ignore pls

**Comment by joshuaptfan** [comment]
Y'know, you can _edit_ issues after they are submitted. This isn't Twitter.
