### ISSUE TITLE
But seriously who allowed this to exist? (Issue with diagonal mirror in editor)

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry-Suggestions#1671]
Fix diagonal mirror on map generation
It rotates first off and not mirrors, but that's fine it needs to do that.
But why is it one tile off? Why anuke why!!!!
![image](https://user-images.githubusercontent.com/62061444/103174364-58a42480-4883-11eb-9497-a740a1585bfc.png)

**Comment by sample-text-here** [comment]
[bug reports go here](https://github.com/Anuken/Mindustry/issues/new?assignees=&labels=a%20disgrace&template=bug_report.md&title=i%20found%20a%20bug)

**Comment by zethnest** [comment]
And close this.

**Comment by iLagSoUhax** [comment]
smh my head
