### ISSUE TITLE
Unit source

### ISSUE THREAD

**Issue by rmuchan** [Anuken/Mindustry-Suggestions#1672]
**Describe the content or mechanics you are proposing.**

A block that can create units out of nowhere in sandbox, like item/liquid source, but for units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It makes testing about units easier, especially high tier ones. Building an unit from scratch takes too long, T5 units take over 2 minutes even with an overdrive dome. This can be annoying in sandbox. Besides, it's also boring and error-prone to configure item sources for reconstructors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quezler** [comment]
hmm, i can make this, already had some ideas in mind but some extra thought would be needed 🤔

**Comment by joshuaptfan** [comment]
I guess it would have to be the size of T5 reconstructor? 🤔 Would be kind of funny seeing T1 units pop out of that.

**Comment by Kubek0212** [comment]
All sources are 1x1, so technically...
On the side note, you can speed up process in map options, when you can increase unit construction speed up to 99 times.

**Comment by Quezler** [comment]
yes, but changing the rules isn't very practical

**Comment by Quezler** [comment]
also, it would be dangerous for crux, since they have no unit cap while they're spawning waves

**Comment by joshuaptfan** [comment]
I assume it would also be impractical to make the unit source pump out units as fast as they can get out, as you would hit the unit cap within seconds of placing the thing. Perhaps it should just make 1 at a time, but how would you tell it to "make another unit" (some kind of "dispense" button) without logic? If using the factory config menu, it would be annoying to have to go through that repeated to make many units.

Also, with so many units on your hands, it would be nice to have an convenient way to dispose of them as well. How would a Unit Void work? Like a command center set to rally, but deletes all units that touch it?

**Comment by walksanatora** [comment]
If you want to spawn units mods exist for that

**Comment by sk7725** [comment]
sk7725/testers

**Comment by sk7725** [comment]
> hmm, i can make this, already had some ideas in mind but some extra thought would be needed 🤔

I do have one in my mod above, how do you think about my version?

**Comment by sample-text-here** [comment]
while this is possible with mods, a vanilla version would be better (usable on servers)

i think if this was added, the dispense button idea is the best. (maybe let logic activate it?)

**Comment by Sanya2907** [comment]
I think of 2 options: the unit and the speed of spawning

**Comment by joshuaptfan** [comment]
I think "slow" production is the most technically feasible solution right now, without reworking how blocks and their config menus work.

* No block, besides the logic switch, functions as a button when you tap/click on it
* Block config menus only support configuring a single thing
* There would be all kinds of weirdness with a block having both a config menu _and_ functioning as a button like the logic switch (it's currently off, you just want to configure it, but tapping it turns it on too and spits out a unit you don't want)

With "slow" (but still way faster than even T1 unit factories) production, you have time between each production to unset or delete the unit source. If you want lots of units quickly, just build lots of unit sources.

**Comment by sample-text-here** [comment]
instead of it being a switch, there could be a button in the config that spawns a unit (think scatter silo from #dev-previews)

**Comment by DeltaNedas** [comment]
mods

**Comment by Sanya2907** [comment]
> mods

No.

**Comment by Kyllingene** [comment]
> instead of it being a switch, there could be a button in the config that spawns a unit (think scatter silo from #dev-previews)

Umm...
> Block config menus only support configuring a single thing
