### ISSUE TITLE
Bringing back the old AI building

### ISSUE THREAD

**Issue by Qwertly-boop** [Anuken/Mindustry-Suggestions#1674]
Yes, I am trying to get this feature back. Back in the older builds we had poly's attacking sectors and they dont simply attack like a flare like they do now. They built a base, The first time ive seen that, it was insanly fun! Knowing i could make fun   gameplay since you have the editor was very fun. Sadly it got removed. The cause of the removal is pretty dumb. Some players thought it was too hard. To easilly combat the poly's Just make a trap i mean you have launch pads just get near a building make a scorch then an anti air to destroy them its that simple! I really want the feature back. The point of this is that The AI can build even without the core. For enemy bases once theyre core is destroyed and the builder unit has died they cant build no more. The way they can build is by sending out any builder unit in a wave like it did in the campaign back then.
Thank you for reading this.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niches **

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] X
2. - [] X
3. - [] X
4. - [] X

**Comment by Quick-korkc** [comment]
before theres ton of sector have ai poly
>Some players thought it was too hard

YES IT IS
WHY A NORMAL-MEDIUM SECTOR HAS THAT THING
also i think that break game balance, player in pvp need core to build, if their core destroyed, they cant build anymore
in attack sector : basically the enemy have infinite item in their core, so they can build more and repair destroyed buildings. But the poly... 
and why you delete this :
> have done a quick search in the list of suggestions to make sure this has not been suggested yet.
 I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
 I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
 I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Qwertly-boop** [comment]
Now some might not like this in their maps. I understand why so.. Theres a way we can help with that. In the rules section we can add that button So if you want the AI polys or any builder unit to be able to build when they spawn You turned that baby up. If you want them to absolutely get rekt when they lose their core you leave that button untouched. Not sure how to call that button probs "No core building" 
Anyways cya.

**Comment by Qwertly-boop** [comment]
> before theres ton of sector have ai poly
> >Some players thought it was too hard
> 
> YES IT IS
> WHY A NORMAL-MEDIUM SECTOR HAS THAT THING
> also i think that break game balance, player in pvp need core to build, if their core destroyed, they cant build anymore
> in attack sector : basically the enemy have infinite item in their core, so they can build more and repair destroyed buildings. But the poly... 
> also why you want convert a survival sector become attack sector?
> and why you delete this :
> > have done a quick search in the list of suggestions to make sure this has not been suggested yet.
>  I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
>  I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Its still a survival sector Just kill of the polys and bam you captured the sector.
I would't call it converting it just adds up more of the gameplay. Mindustry survival plays like this:
Economy-Defence
If you were to have this feature on 
Economy-Defence-Attack
If you think its still hard 
Well i mean launchpads exist you can make an eclipse and the polys are most likelly dead. Plus im not saying this should be added in all sectors. The only thing hard is the fact that you dont play the campaign enough to have working launch sectors so get goin to work. Theyre most likelly to build only Duo and scatters whats hard there. Anyways if youre asking why did i delete that since i needed more room to type its not like i was trying to bypass anything. Now when you say about the pvp thing you need core to live i agree. 
But if we think smart for instance. You destroyed an enemy base and now its getting attacked wouldnt they try to re establish a base again? And if you went on a survival sector with the polys what would you think? Theyre scouting and they will first build a defence before launching a core there. If you were to have that power you would do the same wont you? 
You can build a defence and have no troubles of losing it because of youre core getting destroyed. Now to make this fair there will be only A Few kind of sectors like that from 3-5.  If you lose at that sector the next time you visit it will be a enemy base the most ussual dificuilty is medium and rarelly high. If you attack again this time there will be a core and no poly's are gonna be around only the Alpha unit. Its still survival 
All you have to do is survive 30 waves, kill of the poly's and you win!. What this basicly means that you and the AI are building bases. If you fail to survive it will turn into a attack map. But a weak one.
I hope this can change youre mind i knwo you might not like the idea but it was one of my favourite features in the unreleased version. Anyways cya

**Comment by Quick-korkc** [comment]
>The only thing hard is the fact that you dont play the campaign enough to have working launch sectors so get goin to work

You want a newbie in campaign who even not unlock the launchpad attacked by poly?
>Theyre most likelly to build only Duo and scatters whats hard there

You even not check what they build
here all ai schematic in that version where ai poly exist
[ai-poly_brain.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5745583/ai-poly_brain.zip)
>I hope this can change youre mind i knwo you might not like the idea but it was one of my favourite features in the unreleased version

i actually agree, but why in a easy sectors
back when even easy sector have poly who ruined everything
i rather make them exist in hard sectors
or we got warning about them

**Comment by Qwertly-boop** [comment]
> You want a newbie in campaign who even not unlock the launchpad attacked by poly?
You might be wich one day youll go pro. But when were dealing witha community that has lots of pros they will have that research.
> >Theyre most likelly to build only Duo and scatters whats hard there

> You even not check what they build
> here all ai schematic in that version where ai poly exist
> [ai-poly_brain.zip](https://github.com/Anuken/Mindustry-Suggestions/files/5745583/ai-poly_brain.zip)
I know what they can build it was only an example with those weak turrets on easy sectors thorium isnt around for the AI to build a spectre.
> >I hope this can change youre mind i knwo you might not like the idea but it was one of my favourite features in the unreleased version

> i actually agree, but why in a easy sectors
> back when even easy sector have poly who ruined everything
> i rather make them exist in hard sectors
> or we got warning about them

Not allways in a easy sector. I REALLY do agree with a warning idea. What kind of a warning message? It hard to think of.. id say "Enemy Outpost" Then again these kind of sectors will be rare the biggest ammount of those kind of sectors would be 3.  So you have alot of free survival sectors. While were at it itd be a cool idea for the enemy base to attack a uncaptured and make a enemy base so basicly theyre expanding theyre bases and youre expanding youre bases. For a chance id say 1/10 chances every hour of game time. Still not sure about frequency but if anukes adds  this he can pick the frequency. Anyways thanks for understanding.

**Comment by NajimiOsana** [comment]
have you ever heard of enemy core ships?

**Comment by Qwertly-boop** [comment]
> have you ever heard of enemy core ships?

And how does that help it will turn into attack map. Lol. Polys building without a core like from scratch. Thats the point

**Comment by Kyllingene** [comment]
R.I.P. template. You seem to realize that there is already AI building in attack, so do you want it in survival too? Because that just doesn't make sense to the mode. Either you fight a changing enemy that fights back, or you try to survive against endless waves of enemies that *don't* build. Survival is more of a passive mode, while attack is more of an active mode.

**Comment by catatagun** [comment]
I would like the old one when polys on your team would build and help you

**Comment by Kyllingene** [comment]
Wait, so you want polys building random stuff all over? NO. You want polys helping you build whatever you are building? Exists. You want polys re-building broken things? Megas.

**Comment by thw0rted** [comment]
I'm a newb having a little trouble following the conversation.  The description for polys says it rebuilds destroyed stuff -- is that no longer the case?  I just want drones that repair stuff automatically, and it would be awesome if they'd also replace completely destroyed stuff.

**Comment by Kyllingene** [comment]
I believe that Polys also rebuild buildings, I just believed (not a unit expert by any means whatsoever) that Megas were the preferred tool for the job.
