### ISSUE TITLE
Atomic read-write instruction(s) for unit flags and memory blocks

### ISSUE THREAD

**Issue by Farraginous** [Anuken/Mindustry-Suggestions#1676]
**Describe the content or mechanics you are proposing.**

For unit flags and memory cell values, I think there should be a way to simultaneously read an old value and write a new one. Specifically, I am suggesting atomic fetch-and-set instructions, but any kind of synchronization primitive would be nice.

For the fetch and set approach, atomic readWrite for memory cells could potentially be implemented either as a fusion of the old read and write instructions, or as an additional instruction. In either case, the new instruction could be structured like this:

`readWrite <double writeVal> <double store> <Building cell> <int address>`

For unit flags, the atomic readWrite could either be an additional instruction, or a replacement of the old flag instruction, though personally I prefer the latter. A replacement instruction could be structured like this:

`ucontrol flag <double flag> <double store> 0 0 0`

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think an atomic read-write instruction is needed for proper processor synchronization, since two or more processors checking and modifying the same spot in memory or unit flag can result in race conditions. For example, suppose you have two micro processors that are trying to reserve the same type of unit by changing its flag to a special value when the flag was previously 0. Here is an example of a race condition in this situation:

1. Micro processor 1 gets flag of unit 1; it is 0, so it thinks unit 1 is unreserved
2. Micro processor 2 gets flag of unit 1; it is 0, so it thinks unit 1 is unreserved
3. Micro processor 1 sets unit 1's flag to special value x, thinking it is unreserved
4. Micro processor 2 sets unit 1's flag to special value y, also thinking it is unreserved

Now, both microprocessors think they reserved unit 1, which defeats the purpose of the unit reservation. While at first it may seem that this can be solved by having both microprocessors checking the flag again, keep in mind that to many players' knowledge (mine included), the exact ordering of instructions is unknown and may not always be the same (for example, what if micro processor 1 double checks before microprocessor 2 sets the flag?). This is made worse by the fact there are multiple types of processors with different instruction execution rates.

With atomic read-write instructions, this problem could be solved in an accessible and (in-game) performant way. Furthermore, the above example is just one of many; it is easy to see how race conditions can pop up in other scenarios, both for unit flags and memory cells, which could benefit from an atomic instruction. With better processor synchronization, players will be able to use shared memory resources in their logic systems without fear of those systems breaking.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
> Here is an example of a race condition in this situation:
> 
> Micro processor 1 gets flag of unit 1; it is 0, so it thinks unit 1 is unreserved
> Micro processor 2 gets flag of unit 1; it is 0, so it thinks unit 1 is unreserved
> Micro processor 1 sets unit 1's flag to special value x, thinking it is unreserved
> Micro processor 2 sets unit 1's flag to special value y, also thinking it is unreserved

this isnt a very good example.
1. micro processor 1 gets flag of unit 1 and sets it to `1`.
2. the flag was already set/reserved to `2`, but the processor set the value to `1` before it could check the value

same thing with memory cells

**Comment by DeltaNedas** [comment]
1. you can already use locks
2. do atomic operations on x86 need hardware support? no of course not

**Comment by Farraginous** [comment]
> 
> 
> > Here is an example of a race condition in this situation:
> > Micro processor 1 gets flag of unit 1; it is 0, so it thinks unit 1 is unreserved
> > Micro processor 2 gets flag of unit 1; it is 0, so it thinks unit 1 is unreserved
> > Micro processor 1 sets unit 1's flag to special value x, thinking it is unreserved
> > Micro processor 2 sets unit 1's flag to special value y, also thinking it is unreserved
> 
> this isnt a very good example.
> 
>     1. micro processor 1 gets flag of unit 1 and sets it to `1`.
> 
>     2. the flag was already set/reserved to `2`, but the processor set the value to `1` before it could check the value
> 
> 
> same thing with memory cells

I don't 100% follow; are you suggesting that the microprocessors should check the flag again after they set it to make sure they have secured the unit to solve the problem?

If that is what you are suggesting, the issue I have with that is that it requires that the double check is guaranteed to occur after the last time flag gets set. However, my main concern is that the play does not know how processor instructions are scheduled, so to them it is possible that microprocessor 1 could possible read the flag again before microprocessor 2 sets the flag the first time. I suppose you could probably use a small delay before double checking that reasonably guarantees all competing processors have read and set the lock, but I think an atomic operation would be faster and a lot more elegant.

> 
> 
>     1. you can already use locks
> 
>     2. do atomic operations on x86 need hardware support? no of course not

1. I understand you can use locks, but my concern is that these locks are not guaranteed to be used correctly without atomic instructions.

2. As for x86, I believe atomic operations actually use synchronization primitives, namely the [XCHG instruction](https://c9x.me/x86/html/file_module_x86_id_328.html). Please correct me if I am wrong here.

I also understand there are potential alternatives to an atomic instruction; for memory cells, Peterson's algorithm comes to mind since there is support for multiple memory values, and for flags a delay based system I proposed earlier this post. However, my problem with these is that they require a decent amount of overhead, and for the delay-based solution finicky to get right. To me, 
an atomic operation seems to be most elegant way to handle locks, and makes sense given that assembly instruction sets generally contain synchronization primitives.
