### ISSUE TITLE
logic - add @nextItem to sensors

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1677]
**Describe the content or mechanics you are proposing.**
Add `@nextItem` to sensors in logic. This iterates between item types in the container you're sensing the same way binding units iterates between units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More logic possibilities.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
So, a use case might be going through the resources in a block and displaying them without having a case/processor for every resource?

**Comment by InvalidError404** [comment]
Another option would be to do it more like links where you use an index to walk through the list of items counts and types, then you don't need to worry about keeping track of where both the count and type operators are relative to the first item or each other.

Either of those options would have been preferable to unrolling the whole search for the highest inventory item in my core overflow dumper controlling six unloaders feeding 10 launchers on the Nuclear Production campaign map.
