### ISSUE TITLE
Area of effect Unit repair structure aka "Repair Projector"

### ISSUE THREAD

**Issue by Nekuna** [Anuken/Mindustry-Suggestions#1678]
The Repair Projector is a 2x2 block which continuously repairs all units that are in range simultaneously. Its range would be a few tiles larger than the repair point — I would imagine a range of 10-12 tiles would work well enough, but it'd be up to you. It would require 160 power per second. An idea I have is that it can be boosted/enhanced with Cryofluid and phase fabric, either on their own, or in tandem. It has the same modifiers as the mend projector. Sticking with continuity, Phase fabric would increase the range by 6.25 blocks. Cryofluid would "cool" the Repair Projector, allowing it to work at 2.36 times its base rate.  
It's build cost would be the same as the overdrive projector. 
        A group of units in the Repair projector's vicinity would be repaired as if each unit was being repaired by its own personal repair point. For Balancing reasons, the repair projector will become less effective if more than a certain number of units are being repaired at a time. This number can be increased by 5 if Cryofluid is used

Due to how repair points work, even if there are a dozen repair points in a given area they will only repair one unit at a time and this can prove to be an issue. Because a multiple repair points will repair one unit until it reaches full health, this leaves every other unit vulnerable to an attack that will destroy them in one hit. As a result, a significant number of units are destroyed, which in turn leaves the player's base vulnerable to attacks. This applies even more so when a higher tier unit is being prioritized over lower tier units, since it will take far longer to be fully repaired.
         While the aforementioned situation can be somewhat avoided by adding more repair points, it ends up with repair points taking up far too much space, which is a detriment to ground units returning from an attack, or makes the use of the rally feature of the command center near undoable with the number of repair points taking up the surrounding area.  
       All of the above issues would be fixed with the addition of a Repair Projector, and it could prove to be even more useful for PvP players. 
In conclusion, a Repair projector would circumvent the issues of it's predecessor, and would be extremely beneficial to all players both in the campaign, and in multiplayer, which is why its addition would be a worthwhile feature to Mindustry.

P.S. This reads like a bad essay because that's what sophomore English did to me :/

Edit: 1-2-21, To clear up any confusion surrounding my suggestion, no, the repair point Would Not repair/heal blocks, only units. I only used the Mend projector as an analogue for the idea to be more clear. When I typed "A mix between" I was referring to the mend projector being able to heal multiple blocks rather than only focusing on one at a time.

(Just in case it isn't clear, I'll replace the X's with something better because It may cause confusion) 

1. - [✔] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [✔] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [✔] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [✔] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quezler** [comment]
oct be like

**Comment by RedstonerKBC** [comment]
Build lots of repair points, slap a bunch of batteries down and contain it with diodes. That's what we have to do now. It's not hard, but I think people get annoyed by how many repair points are required to heal quickly and when they all target the same unit. Most of the time this doesn't matter but when multiple players are using the same repair points one has to wait for the other to heal because they all target the same player.

**Comment by Kyllingene** [comment]
I wonder if repair points might be controlled by logic similarly to turrets? Then, a simple logic processor could make a pack of repair points distribute their healing.

**Comment by catatagun** [comment]
Wait this is merge behavier

**Comment by Kyllingene** [comment]
No, he wants a block that is to the repair point what the mend projector is to the mender; an upgraded repair point, not a repair point + mend projector

**Comment by catatagun** [comment]
> No, he wants a block that is to the repair point what the mend projector is to the mender; an upgraded repair point, not a repair point + mend projector

Still a repair point mender

**Comment by itcannotbe** [comment]
[X means He didn't]  I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
![The DO NOT SUGGEST list](https://user-images.githubusercontent.com/45280919/103256647-f6553c00-49c8-11eb-846b-0d5e821d2667.jpg)

**Comment by itcannotbe** [comment]
"Merged Behavior Blocks"

**Comment by Kyllingene** [comment]
It is not both a mender and a repair point. It is an upgraded repair point. It does one thing: heal troops. Therefore, NOT a merged behavior block.

**Comment by itcannotbe** [comment]
A structure which is a mix between a repair point and a mend projector, that acts as an upgrade to the Repair point.

**Comment by itcannotbe** [comment]
Basically he wants something that does this, but in this manner. Kinda merged right?

**Comment by Kyllingene** [comment]
No, that's not merged! Merged is two behaviors in one block, this is one behavior. Not merged. Would you call the overdrive dome a merged block, since it's like a mend projector but for overdrive? No, of course not. Thus, this is not a merged block; it's like a mend projector but for units. NOT merged behavior.

**Comment by itcannotbe** [comment]
> Would you call the overdrive dome a merged block, since it's like a mend projector but for overdrive?

🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴

**Comment by Kyllingene** [comment]
>  > Would you call the overdrive dome a merged block, since it's like a mend projector but for overdrive?
>
>🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴

Never answered the question.

**Comment by itcannotbe** [comment]
> > > Would you call the overdrive dome a merged block, since it's like a mend projector but for overdrive?
> > 
> > 
> > 🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴🥴
> 
> Never answered the question.

Well It wouldn't be. Why?
Because Mender and Mend projectors were and are healing blocks it it's area of effect same of the Overdrive and the Overdrive Dome.

So why on earth would one make that statement just to justify something completely unrelated to it?

**Comment by Kyllingene** [comment]
@itcannotbe, you seem to have a habit of not reading things before you reply; would you do me a favor and read *all* of my comment *before* ignoring what it says? Thanks!

---
My point was that the overdrive dome is an upgrade to the overdrive projector (the names mean literally nothing, they might as well be things 1 and 2, so don't use the names as a reason), similar to the mend projector being an upgrade to the mender. Here is an attempt to show what I mean:

Mender Series:
    Mender - Mend Projector
Requested Repair Point Series:
    Repair Point - Repair Projector (or some other name)
Overdrive Series:
    Overdrive Projector - Overdrive Dome

You dismiss the Repair Projector as being a merged behavior block. This is analogous (according to the above chart) to dismissing the Overdrive Dome as a merged behavior block. All the Repair Projector is is a Repair Point + 1. All the Overdrive Dome is an Overdrive Projector + 1.

The whole point of this is to clear the misconception people seem to have that this suggested block would heal both blocks and units. That would be nonsense. The request is an upgraded version of the Repair Point. Nothing more, nothing less.

**Comment by itcannotbe** [comment]
> @itcannotbe, you seem to have a habit of not reading things before you reply; would you do me a favor and read _all_ of this comment _before_ ignoring what it says? Thanks!
> 
> My point was that the overdrive dome is an upgrade to the overdrive projector (the names mean literally nothing, they might as well be things 1 and 2, so don't use the names as a reason), similar to the mend projector being an upgrade to the mender. Here is an attempt to show what I mean:
> 
> Mender Series:
> Mender - Mend Projector
> Requested Repair Point Series:
> Repair Point - Repair Projector (or some other name)
> Overdrive Series:
> Overdrive Projector - Overdrive Dome
> 
> You dismiss the Repair Projector as being a merged behavior block. This is analogous (according to the above chart) to dismissing the Overdrive Dome as a merged behavior block. All the Repair Projector is is a Repair Point + 1. All the Overdrive Dome is an Overdrive Projector + 1.
> 
> The whole point of this is to clear the misconception people seem to have that this suggested block would heal both blocks and units. That would be nonsense. The request is an upgraded version of the Repair Point. Nothing more, nothing less.

Point taken. Let's stop dragging this thread even further.

But still repairing multiple units at the same time without an increase in resource consumption is OP considering how units are used in-game at the moment.

**Comment by Kyllingene** [comment]
> But still repairing multiple units at the same time without an increase in resource consumption is OP considering how units are used in-game at the moment.

Actually, the OP never mentioned *anything* about them using the same resources as the repair point. Unless you meant it repairing multiple units at the same time without an increase, in which case:

> For Balancing reasons, the repair projector will become less effective if more than a certain number of units are being repaired at a time

**Comment by Humanoid-X** [comment]
@itcannotbe But it is not a merged behaviour block... Actually @Nekuna just need to delete his first sentence.
Repair Projector : Can repair a large crowd/troop of units.
Mend-Repair Merge : Can both repair units and mend blocks.
So it's not the same concept. It can't be called a "Merge Behavior" block.

**Comment by Kyllingene** [comment]
> > The whole point of this is to clear the misconception people seem to have that this suggested block would heal both blocks  and units. That would be nonsense. The request is an upgraded version of the Repair Point. Nothing more, nothing less.
>
> Point taken. Let's stop dragging this thread even further.

**Comment by Nekuna** [comment]
@Kyllingene  and @Humanoid-X  are on point. It only now (at the time of this comment) occurred to me to check this suggestion, so apologies for a late response to the confusion. Looking back at my post I can understand where the misunderstanding stemmed from.
I've edited the suggestion with a clarification at the end to drive my point home.
