### ISSUE TITLE
Ghost schematic placement

### ISSUE THREAD

**Issue by Dasius** [Anuken/Mindustry-Suggestions#1679]
**Describe the content or mechanics you are proposing.**
A key you can hold (say Alt for example) to turn a schematic to a ghost and back to normal when the key is released.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When placing large schematics, its hard to tell if a miner is on unwanted resources without moving back and forth, especially when you have lots of miners in the same schematic. This would mean you could line up your schematic where you wanted it and just press Alt for a second to check you haven't clipped some copper with your coal mine for example.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dasius** [comment]
Just found something similar that I missed on my first search. Duplicate.

**Comment by Quezler** [comment]
link it?

**Comment by Kyllingene** [comment]
I do believe they mean #1651
