### ISSUE TITLE
ChatBot Protection

### ISSUE THREAD

**Issue by devilofhell** [Anuken/Mindustry-Suggestions#168]
**Describe the content or mechanics you are proposing.**

When playing on a public server, there are sometimes people, who just want to destroy the game. There is currently a griever just spamming the global chat with following text "add Nexity#2671 on discord to join griefer group". In order to protect spamming the chat, a maximum of chat messages per second / minute would be great. It is not even possible to use the ingame kick mechanism, because, the other players can not communicate with each other.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will help to get rid of players, who want to destroy the game in multiplayer.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Isn't !vote mute a more practical way of solving this issue?

**Comment by devilofhell** [comment]
well, the bot was texting so much and so fast, I was not able to actually see, that there even was a vote alive. thats the reason "!vote kick" did not work. so i think "!vote mute" will not work, too. 

What I think, how this feature should be implemented, is like other games like "League of Legends" or "Overwatch" handle spamming chat. If you send 10 messages is less than like 5 (?) seconds, you are temporary not able to use the chat again. I don't know how long you are then banned, but i think that the chat should then not be available for like 20-60 seconds, just for this one user.

**Comment by itcannotbe** [comment]
Vote Mute would work if the person has no clue that he was already muted

**Comment by Anuken** [comment]
Rate limit is implemented in 6.0.
