### ISSUE TITLE
Team Change

### ISSUE THREAD

**Issue by MichaelTrudeau** [Anuken/Mindustry-Suggestions#1681]
**Describe the content or mechanics you are proposing.**
A command that lets you change team.
Example: From red to yellow. (MULTIPLAYER)

P.S. for the toxic people in the comments:
"*This command should be FORCIBLY included in all servers* I'm not suggesting a mod, don't be dumb."

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I'd just like a command that lets you change team. I mean, people like me who have a bad connection are prone to crashing out of the game, when I rejoin the game, the server assigns me to another team than the one I was on, which really triggers me cause when you build in red team for a full hour, I'd want to stay on my team, not be forced to work for a random new team. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NajimiOsana** [comment]
that would mean most people would join the winning side, instead of staying with their team.

**Comment by MichaelTrudeau** [comment]
> that would mean most people would join the winning side, instead of staying with their team.

This could be fixed by making sure you can only switch to the team you were in before you crashed.

**Comment by NajimiOsana** [comment]
if the specified server had a memory system or something along the lines of it, it could probably work.

**Comment by itcannotbe** [comment]
[Does putting an X here means you haven't?] I have done a quick search in the list of suggestions to make sure this has not been suggested yet

**Comment by Quezler** [comment]
plugins go brr

**Comment by RedstonerKBC** [comment]
Make the command have a cooldown. You can only change teams once and only before a certain amount of game time has passed, like 5-10 minutes or something.

**Comment by Kyllingene** [comment]
Mods are really, really not that hard to make for things as simple as this... did you try looking one up?

**Comment by DeltaNedas** [comment]
there are no plugins that exist that let you change team

... wait a minute
https://github.com/J-VdS/PVPPlugin
https://github.com/J-VdS/TeamPlugin

**Comment by MichaelTrudeau** [comment]
Thanks for making fun of me and this request but If you've got a logic mind you'd understand that I didn't mean to "get it for my own server" but that I was requesting this to be *forcibly* included in all servers. Now if you wanna make fun of people, go get a job at a circus.

**Comment by itcannotbe** [comment]
> I was requesting this to be forcibly included in all servers.

Make your own game then.
This way you make the rules.

**Comment by MichaelTrudeau** [comment]
> > I was requesting this to be forcibly included in all servers.
> 
> Make your own game then.
> This way you make the rules.

I wonder how much free time you have to argue with people online.

**Comment by RedstonerKBC** [comment]
We live in a world fraught by the power of mob mentality and snowflakes getting what they want simply by whining on Twitter. In the old days I would ask how you expect to get anywhere in life if you let harmless words hurt you, but it's 2020 and I have to say good job using modern-day techniques to get what you want. I won't be surprised if this blows up on Twitter and Anuke is forced to add it so he doesn't get murdered or canceled by random strangers who have no idea what is going on and are caught up in drama out of sheer boredom because they have nothing better to do but attack others for not living their lives the way they do.

**Comment by Kyllingene** [comment]
> but If you've got a logic mind you'd understand that I didn't mean to "get it for my own server" but that I was requesting this to be forcibly included in all servers

I understood that. My point was that it is easy to get on an individual basis. That way, people can't grief by swapping teams. Also, @RedstonerKBC, I do believe you are over-dramatizing this case. Yes, what you say is true, but people were simply pointing out that there were better ways to do this. We were *not* in fact attacking this person for not living their life the way we do. It's the difference between exclusively pointing out alternatives (maybe in a rude manner, maybe not) and insulting someone for wanting this feature.

**Comment by MichaelTrudeau** [comment]
> We live in a world fraught by the power of mob mentality and snowflakes getting what they want simply by whining on Twitter. In the old days I would ask how you expect to get anywhere in life if you let harmless words hurt you, but it's 2020 and I have to say good job using modern-day techniques to get what you want. I won't be surprised if this blows up on Twitter and Anuke is forced to add it so he doesn't get murdered or canceled by random strangers who have no idea what is going on and are caught up in drama out of sheer boredom because they have nothing better to do but attack others for not living their lives the way they do.

Hmmm I forgot to spray the anti-toxic detergent.
*sprays anti-toxic detergent*

**Comment by MichaelTrudeau** [comment]
I thought closing this would keep toxic people way. Guess toxicity follows you everywhere.

**Comment by Kyllingene** [comment]
I hope you realize that I am trying my best to keep toxicity out of my comments.

If you don't like my comments, just say it. Don't make a fool of yourself and assume everyone that disagrees is toxic.
