### ISSUE TITLE
Jump tags to avoid jump # for line items using external editor

### ISSUE THREAD

**Issue by ericwhite100** [Anuken/Mindustry-Suggestions#1682]
**Describe the content or mechanics you are proposing.**
First, I am pretty new to all this, so forgive any ignorance.  This feature may exist, but haven't found it in searching. I like to use VSC for editing logic.  However it uses numerical line numbers which need constant adjustment on line inserts above the jumps.  I suggest tags, something like this:

current example:
12 jump 13 lessThan lead 14000
13 control configure unloader1 @copper 0 0 0

instead:
12 jump tag1 lessThan lead 14000
13 $tag1
14 control configure unloader1 @copper 0 0 0

Or some such logic.  Would appreciate if someone could point me to an example if this already exists.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Already stated.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
1. what does vs kode have to do with mindustry
2. example code you provided doesnt do anything (assuming you're using line number instead of address) please learn how jump works

**Comment by Ruichka** [comment]
There's a lot of player-made scripts that give you ability to make labels. Use them and close this issue.

**Comment by ericwhite100** [comment]
> 1. what does vs kode have to do with mindustry
> 2. example code you provided doesnt do anything (assuming you're using line number instead of address) please learn how jump works

Programs 100's of lines long are easier to write in an external editor.  The game interface is fine for small.   Block copy/paste is very helpful.  The example was intended to give some concept of how tags would avoid specific numbering when pasting in a clip.  You wrote an amazing game here, and I get you get swamped with stupid a lot, but unfortunately that goes with the territory.

**Comment by ericwhite100** [comment]
Working on my own scripts.

**Comment by DeltaNedas** [comment]
yes, so labels are either:
A) something you write a preprocessor for
B) something you use with a text editor plugin

neither of which belong on the mindustry suggestion tracker.

**Comment by lheckemann** [comment]
If anyone's written a preprocessor or editor script for this, I'd greatly appreciate if they could share it :)

**Comment by calmofthestorm** [comment]
@lheckemann I wrote [a command line processor](https://github.com/calmofthestorm/routerbolt) that can do this. There's also a rudimentary [webapp](https://calmofthestorm.github.io/routerbolt/web/dist) interface.

**Comment by lheckemann** [comment]
Oh, very nice! I've written a little script for this by now, but the correctness of my approach is a bit questionable and a proper compiler looks much nicer (and makes a lot of things easier). Thanks for making and sharing!
