### ISSUE TITLE
Campaign Loadout: Too hard to choose how much resources you want, need a maximize button or at least better display

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1683]
**Describe what you would like changed, and why.**

Often times, I just want to take every resource I can possibly carry of a given type from the source planet regardless of how much that is.  Right now, I have to first manually type in the maximum amount the destination can hold (i.e. 4000/9000/13000), then go back a screen to see how much the deficit is, then go back and edit the amount to be the correct maximum.  Further, I have to do math manually, e.g. subtract off the copper that I'm required to carry just to launch.

**Describe the changes you want to propose. Include possible alternatives.**

Add a single button, "max", next to each resource type when choosing the amount (next to +/-/edit).  It automatically does the math and selects the minimum of the following pair: Max resources as source (e.g. 9000), Max resources the destination can take (e.g. 9000 minus copper cost).

Alternative: Display the aforementioned maximum on the loadout selection screen so I can at least just type it in.

Alternative: At least display the amount the source planet HAS on at least one of the loadout screens without me having to manually look at the source planet or typing in a number and going back a screen to see the deficit!

**Comment by ShadeStrike62** [comment]
this is useful
