### ISSUE TITLE
Start another wave before current one finishes

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1684]
**Describe what you would like changed, and why.**

Sometimes you can tell that the current wave is trivial.  I'd like to be able to start the next wave without waiting for all the current wave's enemies to kill themselves trying to get past my defenses.

**Describe the changes you want to propose. Include possible alternatives.**

When a wave is in progress (i.e. enemies remain), leave the triangle to start the next wave available.  If used, enemies for the next wave appear immediately, the enemy count increases by the appropriate amount, and the wave number increases by one.

Allow this to be repeated, e.g. have 3, 4, or more waves started at once.

If you think it's necessary, make the triangle red or something to make sure the user really wants to make the game harder by kicking off the next wave early.

I see no circumstances where this would make the game easier, so why not allow a user to make their own game harder by choice?

**Comment by joshuaptfan** [comment]
What if the user taps/clicks twice by accident on a less-than-trivial wave?

**Comment by Quezler** [comment]
i believe something like this was suggested either here or on the main repo, and got shut down by anuke since it could break waves in a number of ways or something, i don't recall a link

**Comment by itcannotbe** [comment]
> I see no circumstances where this would make the game easier, so why not allow a user to make their own game harder by choice?

Turrets which deal AOE Damage exist so..... by allowing people to essentially send a massive wave. It will make the game easier as you're using less ammo/power to kill the waves.

**Comment by ShadeStrike62** [comment]
NOOO u kant just beet a sector kwiklee, ther must be pane....

**Comment by rMuchan** [comment]
> What if the user taps/clicks twice by accident on a less-than-trivial wave?

Maybe ask user to confirm it. Remember in v5 what happens when you have an opportunity to launch and try to start the next wave

**Comment by zethnest** [comment]
> Turrets which deal AOE Damage exist so..... by allowing people to essentially send a massive wave. It will make the game easier as you're using less ammo/power to kill the waves.

That's practically what most Tower Defense games tend to do.
