### ISSUE TITLE
Show resources available even when paused

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1685]
**Describe what you would like changed, and why.**

The <Paused> text prevents me from seeing how many resources are in my core.  Preventing this makes planning my next move, a major reason to pause the game, much more difficult because I have to remember how much of every resource I have in my core.

**Describe the changes you want to propose. Include possible alternatives.**

Leave the resource count in core displayed when paused.

**Comment by Catchears** [comment]
You probably know this but you can also see the resources in your core by selecting it. Nevertheless, I still think that you should be able to see the core resources using the overlay at the top while the game is paused.

**Comment by itcannotbe** [comment]
I wonder how much space this would eat on mobile.

**Comment by swenkeratmicrosoft** [comment]
@itcannotbe 
> I wonder how much space this would eat on mobile.

Good point, I didn't consider the mobile case.  If that's an issue, maybe make it an optional feature in the game menu?

**Comment by zethnest** [comment]
@itcannotbe Mobile never had the resource HUD in the first place (at least in my case, where I have small screen). Unless there are plans for bringing the resource HUD to mobile, mobile can be put aside.
