### ISSUE TITLE
Core units can carry things

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1687]
**Describe the content or mechanics you are proposing.**
Correct units can carry 1x1 blocks and units
Alpha can carry 1 thing
Beta can carry 2 things
Gamma can carry 3 things

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Makes the core units more of a jack of all trades, and allows for easier movement of small blocks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
That would reduce the incentive to produce and command payload-carrying units.

**Comment by scarf-generic** [comment]
> more of a jack of all trades

but... they never were. core units can shoot and build. compared to a unit like nova which can shoot, repair buildings, heal units, and build, or mega which can shoot, repair buildings, use payload, and build, core units are hardly a jack of all trades to begin with.

**Comment by Legomonster33** [comment]
> > more of a jack of all trades
> 
> but... they never were. core units can shoot and build. compared to a unit like nova which can shoot, repair buildings, heal units, and build, or mega which can shoot, repair buildings, use payload, and build, core units are hardly a jack of all trades to begin with.

They can do lots of things, poorly
I just think having more things they can do (poorly) would be benificial

**Comment by Kyllingene** [comment]
> 

And mine, if it makes a difference.
