### ISSUE TITLE
Oil needs a use case that doesn't require titanium (besides Wave)

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry-Suggestions#1688]
**Describe what you would like changed, and why.**

Right now, Oil has exactly three use cases.
1. Convert to Plastanium using Plastanium Compressor.
2. Convert to coal using Coal Centrifuge.
3. Use as ammo in Wave or Tsunami.

Both 1 and 2 require Titanium as does Tsunami.  Wave's range is short enough that it's rarely, if ever, worth piping oil to where you would use it.

As a result, a map with Oil without Titanium makes the oil pretty pointless.  There's no reason to import Titanium to such a map so you can convert the oil to something else; directly importing Plastanium and/or Coal is FAR more efficient.

Oil needs a use case that doesn't require titanium.

**Describe the changes you want to propose. Include possible alternatives.**

Here are a several examples of ways oil could see some use without titanium, but I'm sure you can think of others.
1. Allow combustion generator (or a new power source) to burn oil.
2. Allow oil as an alternative to coal for at least one other low-tech building(s), e.g. Pyratite Mixer
3. Allow oil as an alternative input to Cultivator.  (Cultivator -> Spore Press -> Cultivator would result in a net loss, obviously.)
4. Allow oil as an enhancer for some buildings, e.g. drills.
5. Remove Titanium as a build requirement for Coal Centrifuge.

**Comment by Quick-korkc** [comment]
>Remove Titanium as a build requirement for Coal Centrifuge.

NO
Oil is for advanced tech, so you need titanium for processing oil

**Comment by itcannotbe** [comment]
A map with oil, but without titanium can be used later on when you have launch pads. Duh.

**Comment by itcannotbe** [comment]
A map oil without titanium can be used later on when you have launch pads, since making oil in the first place is a pain and using actual oil from tar pools is extremely lucrative.

**Comment by swenkeratmicrosoft** [comment]
@itcannotbe 

> A map with oil, but without titanium can be used later on when you have launch pads. Duh.

Perhaps you misread the original OP?

"There's no reason to import Titanium to such a map so you can convert the oil to something else; directly importing Plastanium and/or Coal is FAR more efficient."

It's INCREDIBLY inefficient to "import Titanium" (which you can only do using launch pads, DUH) to a sector with Oil just so you can convert that Titanium to Coal or Plastanium.


@Quick-korkc 
> NO
> Oil is for advanced tech, so you need titanium for processing oil

Creating Coal can't possibly be called "advanced tech" in *game terms*.  That's ludicrous.  Coal is one of the earliest resources in the game.

So for "Advanced tech" you can only mean Plastanium because oil isn't required for anything else.  But you already can't create Plastanium without Titanium - two Titanium is required for every one Plastanium.  I would never suggest removing that requirement.

**Comment by DeltaNedas** [comment]
steam gens can already burn coal which comes from oil, why do you need a single block that does that?

**Comment by itcannotbe** [comment]
ebacsue mioptrnig itatinmu si ushc a ahssel vene fi oylu'l noyl od ti noec.


-------- Original message --------

**Comment by RogueRedHawk** [comment]
@itcannotbe 

"because importing titanium is such a hassel even if you'll only do it once"

↑for the lazy

**Comment by RedstonerKBC** [comment]
I doubt theyll give oil many use cases since griefers are the ones who benefit the most from oil and coal having usefulness

**Comment by RedstonerKBC** [comment]
any*

**Comment by swenkeratmicrosoft** [comment]
@DeltaNedas 
> steam gens can already burn coal which comes from oil, why do you need a single block that does that?

Because you can't convert oil to coal without titanium.  The request is: "Oil needs a use case that doesn't require titanium."

I listed several possible cases.  I don't care which one(s) are added (or if a different one entirely).  I just want oil to be useful on maps without titanium.

@RogueRedHawk 

> "because importing titanium is such a hassel even if you'll only do it once"
> 
> ↑for the lazy

You misspelled "because importing titanium doesn't solve the original problem".

Let's say you import titanium.  There are two things you can suddenly do with oil.
1. You can convert the oil to coal.  Yay!  Except you can more efficiently import coal directly.  WORTHLESS.
2. You can convert the oil to plastanium.  Yay!  Except you can more efficiently import Plastanium directly.  WORTHLESS.

Importing titanium DOES NOT HELP.  Oil on maps without titanium HAS NO VALUE.

**Comment by ShadeStrike62** [comment]
> @DeltaNedas
> 
> > steam gens can already burn coal which comes from oil, why do you need a single block that does that?
> 
> Because you can't convert oil to coal without titanium. The request is: "Oil needs a use case that doesn't require titanium."
> 
> I listed several possible cases. I don't care which one(s) are added (or if a different one entirely). I just want oil to be useful on maps without titanium.
> 
> @RogueRedHawk
> 
> > "because importing titanium is such a hassel even if you'll only do it once"
> > ↑for the lazy
> 
> You misspelled "because importing titanium doesn't solve the original problem".
> 
> Let's say you import titanium. There are two things you can suddenly do with oil.
> 
> 1. You can convert the oil to coal.  Yay!  Except you can more efficiently import coal directly.  WORTHLESS.
> 2. You can convert the oil to plastanium.  Yay!  Except you can more efficiently import Plastanium directly.  WORTHLESS.
> 
> Importing titanium DOES NOT HELP. Oil on maps without titanium HAS NO VALUE.

Look, as a player who values the kind of maps you say are worthless, I have to disagree about importing titanium. Early to mid game, when plastanium is being made, it is hard to find safe sectors with oil in them, most that have both are vulnerable. By saying just import plastanium if you want it, you are disregarding the fact that it has to be made somewhere. I agree it would be nice if oil had more uses, but it isn't bad in its current state. Oil is one of the most rare resources in the game, a map simply having it is enough to start making a plastanium factory there...

**Comment by swenkeratmicrosoft** [comment]
@ShadeStrike62 

> Look, as a player who values the kind of maps you say are worthless, I have to disagree about importing titanium. Early to mid game, when plastanium is being made, it is hard to find safe sectors with oil in them, most that have both are vulnerable. By saying just import plastanium if you want it, you are disregarding the fact that it has to be made somewhere. I agree it would be nice if oil had more uses, but it isn't bad in its current state. Oil is one of the most rare resources in the game, a map simply having it is enough to start making a plastanium factory there...

Oil isn't rare.

It's totally fair for you to disagree and say that oil has value on such maps if you've found a use for it in the early-game, but you can make oil anywhere there's water - Cultivator plus Spore Press.  I didn't pump oil at all until I had a safe zone that included titanium as well, but I still had plenty of plastanium before that by just using water and titanium.

On the other hand, I've conquered half the world and am still encountering zones with high and extreme danger levels that have oil without titanium.  By the time I can even get to those zones, I have more than enough plastanium in other zones.  If I need more titanium than my initial launch in such a zone I'll import it, but I *certainly* won't be wasting that imported titanium by converting it to plastanium just because there happens to be oil present - I'll import plastanium directly if I need it.  I usually ignore the oil on those maps.

The existing uses for oil make total sense to me, but making *all* oil use depend on titanium massively decreases oil's value.  You can pump oil without titanium...and then dump it on the ground, I guess?  ;)

**Comment by Kyllingene** [comment]
I believe that the difference between you two players is playstyle: one (OP) likes to get things built faster, where as the other (ShadeStrike62) prefers building only when you get maximum reward (or something similar, apologies if I got either of you wrong). Therefore, OP has no use case for oil without titanium, because they already have plast, whereas Shade waits for those maps where you have oil, then imports titanium so they can make plast. Personally, I think that a low-/mid-level generator that uses oil wouldn't be terrible (maybe something like the steam gen, but worse and takes only oil?), because that makes it useful, but without making it overpowered. Also, may I point out how civil this thread is so far?

**Comment by swenkeratmicrosoft** [comment]
@Kyllingene 

> Personally, I think that a low-/mid-level generator that uses oil wouldn't be terrible (maybe something like the steam gen, but worse and takes only oil?), because that makes it useful, but without making it overpowered.

Yeah, I start building new stuff as soon as I can, and I'm definitely not looking to change game balance.  I just hate seeing a resource I have no use for, heh.

**Comment by itcannotbe** [comment]
You haven't considered game balance outside campaign maps with OP's  suggestion TBH.

**Comment by Kyllingene** [comment]
Actually, I believe that this would be a great addition to a mapmakers toolbox.

**Comment by itcannotbe** [comment]
> Actually, I believe that this would be a great addition to a mapmakers toolbox.

Now that's a funny joke.
Did you know that oil was something you can use for combustion and steam generator back then. But it removed cause basically no one used them.

Also blast mixer required oil as an input before instead of coal. Dunno why it was changed to coal.

**Comment by Kyllingene** [comment]
> Now that's a funny joke.

Might you explain why?

> Did you know that oil was something you can use for combustion and steam generator back then. But it removed cause basically no one used them.

1: Did plast exist? What version was this?
2: That isn't a negative, it's simply a fact. Also, how about we forget that metas change with updates, because that way your arguments actually make *sense*.

**Comment by itcannotbe** [comment]
> > Now that's a funny joke.
> 
> Might you explain why?
> 
> > Did you know that oil was something you can use for combustion and steam generator back then. But it removed cause basically no one used them.
> 
> 1: Did plast exist? What version was this?
> 2: That isn't a negative, it's simply a fact. Also, how about we forget that metas change with updates, because that way your arguments actually make _sense_.

1. Most stuff haven't been changed at the time they were introduced into the game.
2. This just shows that adding a feature so niche is just a waste of time.
Did I also mentioned that oil in steam generator is removed because the code for it is so buggy and hard to maintain and barely anyone used it anuke removed it from the game?

**Comment by swenkeratmicrosoft** [comment]
>    Did I also mentioned that oil in steam generator is removed because the code for it is so buggy and hard to maintain and barely anyone used it anuke removed it from the game?

OP suggested a bunch of possible ways to use oil without titanium.  If power generation makes no sense for whatever reason, that doesn't negate the entire original suggestion, merely one of a multitude of options.

**Comment by Kyllingene** [comment]
I asked several questions. Can you answer them? They will severely impact my thoughts on your argument. Without the rough date on question 2, I must assume it was ages ago and therefore had a completely different meta. Without the answer on question 1, I have to assume you have no argument, and therefore I was correct on that point.

> Most stuff haven't been changed at the time they were introduced into the game.

Do you mean that the (unannounced, suspicious) release date on there was recent? Ok then, tell me ***when!***

> This just shows that adding a feature so niche is just a waste of time.
Did I also mentioned that oil in steam generator is removed because the code for it is so buggy and hard to maintain and barely anyone used it anuke removed it from the game?

1: ***The metas CHANGE.***
2: How about a separate block then? See my earlier comment:

> Personally, I think that a low-/mid-level generator that uses oil wouldn't be terrible (maybe something like the steam gen, but worse and takes only oil?)

This proves you don't bother to read what we say.

**Comment by itcannotbe** [comment]
> Did I also mentioned that oil in steam generator is removed because the code for it is so buggy and hard to maintain and barely anyone used it anuke removed it from the game?

This is why no block ingame uses 2 liquids.

**Comment by Kyllingene** [comment]
> This is why no block ingame uses 2 liquids.

The suggested block takes exactly 1, see, 1, liquid. I suggested:

> but worse and takes only oil?

***only takes oil***. Please, read before disregarding it.

**Comment by Kyllingene** [comment]
Also, @itcannotbe, I really, really would like to avoid reporting a valuable Mindustry and Github contributor, so please, let me quote the [Github Community Guidelines](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines):

> Respect each other. **Nothing sabotages healthy conversation like rudeness**. **Be civil and professional**, and don’t post anything that a reasonable person would consider offensive, abusive, or hate speech. Don’t harass or grief anyone. Treat each other with dignity and consideration in all interactions.
>
>You may wish to respond to something by disagreeing with it. That’s fine. **But remember to criticize ideas, not people**. **Avoid name-calling**, ad hominem attacks, responding to a post’s tone instead of its actual content, and knee-jerk contradiction. Instead, **provide reasoned counter-arguments** that improve the conversation.

**Comment by itcannotbe** [comment]
Bumping up the OP's suggestions

Here are a several examples of ways oil could see some use without titanium, but I'm sure you can think of others.

>    Allow combustion generator (or a new power source) to burn oil.



>    Allow oil as an alternative to coal for at least one other low-tech building(s), e.g. Pyratite Mixer

Would make coal centrifuge used less.

 >   Allow oil as an alternative input to Cultivator. (Cultivator -> Spore Press -> Cultivator would result in a net loss, obviously.)

This sound counter productive.

>    Allow oil as an enhancer for some buildings, e.g. drills.

The last time oil can be used on drill, the drills self combust. Was removed because too many complaint of burning drills.

>    Remove Titanium as a build requirement for Coal Centrifuge.

But don't we need titanium for rotary and thermal pumps anyways?
Either way your need titanium in the long run if your going to use more oil.

**Comment by Kyllingene** [comment]
> Would make coal centrifuge used less. Considering coal centrifuged was the block added to make oil see more use.

Now I don't know a whole ton about the meta, but to me, the coal centrifuge is used quite a bit... some might say too much? Not that it needs a nerf, but why does that "block added to make oil see more use" act as a reason if this gives it *more* use and in more ways? Also, the "Oil Generator" (random name) would probably be worse than the steam gen because of the fact that it only takes oil. The centrifuge would still be used for literally everything but steam gen/pyra mixer, so what's the problem there?

**Comment by swenkeratmicrosoft** [comment]
@itcannotbe 

> Bumping up the OP's suggestions
> 
> Here are a several examples of ways oil could see some use without titanium, but I'm sure you can think of others.
> 
> > Allow combustion generator (or a new power source) to burn oil.
> 
> > Allow oil as an alternative to coal for at least one other low-tech building(s), e.g. Pyratite Mixer
> 
> Would make coal centrifuge used less. Considering coal centrifuged was the block added to make oil see more use.

Refer to Kyllingene's comment.

> > Allow oil as an alternative input to Cultivator. (Cultivator -> Spore Press -> Cultivator would result in a net loss, obviously.)
> 
> This sound counter productive.
> 

Spores can be used as input to other things, e.g. Combustion Generator and Steam Generator.  Oil cannot.  If you don't have titanium, spores are more useful than oil.  Thus, you'd convert spores to oil when you need oil (e.g. to make plastanium) and convert oil to spores when you don't have titanium (e.g. to power generators).

> > Allow oil as an enhancer for some buildings, e.g. drills.
> 
> The last time oil can be used on drill, the drills self combust. Was removed because too many complaint of burning drills.

That's a totally fair point - I wasn't aware of that history.  That said, drills was just an example in the OP ("e.g. drills").  It could instead be added it as an enhancer to non-drill non-titanium-requiring building(s) that already combust, although I'm not sure which buildings qualify - if none do, then you're right, this suggestion doesn't make sense.

> > Remove Titanium as a build requirement for Coal Centrifuge.
> 
> But don't we need titanium for rotary and thermal pumps anyways?
> Either way your need titanium in the long run if your going to use more oil.

You're obviously going to still need titanium to get the *most* out of oil, but that's not relevant to the OP.  The point of the OP is that oil currently has *zero* uses without titanium.  If you've already got enough plastanium and then hit a campaign map with oil but without titanium, the oil just sits there doing nothing - there is no incentive to use it.  Making the oil useful for *something* in this situation is what the OP is about.
