### ISSUE TITLE
Making permanent weather togglable, or give a warning to the map creator

### ISSUE THREAD

**Issue by Excavator987** [Anuken/Mindustry-Suggestions#1689]
**Describe the content or mechanics you are proposing.**
Make the "always" function on weather in map editor togglable or at least give a warning that the action cannot be undone. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will prevent unsuspecting map makers from having to restart entirely after removing the permanent effect for whatever reason: enabling it by accident, changing their mind on the fact that they don't want to make it permanent, etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Excavator987** [comment]
This was made as a solution to [issue 4167](https://github.com/Anuken/Mindustry/issues/4167)

**Comment by joshuaptfan** [comment]
Better to automatically turn off the weather right away whenever any weather setting is changed from permanent to not.

**Comment by RogueRedHawk** [comment]
Yeah, just running the weather after turning it to permanent even after removing the weather is stupid.
