### ISSUE TITLE
Landing Pad

### ISSUE THREAD

**Issue by ZygZagGaming** [Anuken/Mindustry-Suggestions#1690]
**Describe the content or mechanics you are proposing.**

A "landing pad" of sorts that picks up units of all kinds on top of it and outputs them to adjacent Reconstructors or Payload Conveyors.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently, once a unit is deployed into the world, there is no way to reconstruct it, and the only way to control non-ground units is with processors or manually.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
This is good, but to prevent abuse, here's what i can think to prevent abuse:

- A cost needed to use
The unit is kind of like, mounted to a "rocket" that sends it to the select Payload Conveyor or Reconstructor, and that "rocket" dosen't just come out of nowhere, it needs resources to be built. The cost partially multiplies depending on the unit's tier.

It is Anuke's choice how much resources it needs to be built.

**Comment by itcannotbe** [comment]
> This is good, but to prevent abuse, here's what i can think to prevent abuse:
> 
>     * A cost needed to use
>       The unit is kind of like, mounted to a "rocket" that sends it to the select Payload Conveyor or Reconstructor, and that "rocket" dosen't just come out of nowhere, it needs resources to be built. The cost partially multiplies depending on the unit's tier, because the higher tier unit is much heavier.
> 
> 
> It is Anuke's choice how much resources it needs to be built.

How on earth does this fit wit OP's use case?
This suggestion exist to put units back into reconstructors or payload conveyors once outside of them.

**Comment by SMOLKEYS** [comment]
Adios suggestion, you will be ~~forgotten~~ remembered
