### ISSUE TITLE
Steam beta usage for version control

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry-Suggestions#1691]
**Describe the content or mechanics you are proposing.**

Use steam beta feature to give users version control.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

iOS updates lag at the same rate as releases.  It’s impossible to keep updates sync’d up across steam and iOS platforms without version control of the fastest (steam).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
you want to use the beta branch for making updates slower?

**Comment by Kyllingene** [comment]
I think they mean that because iOS lags behind in updates, it makes it near impossible for Steam players to play with their iOS friends, because Steam is ahead. Thus, they want the beta branch to do the opposite of its name (hold outdated versions).

**Comment by itcannotbe** [comment]
It's not the entire community that is playing not on iOS fault that the apple appstore take ages to approve app updates. Why the fuck would we wait for the apple app store before having the ability to update. It's not like the rest of use not using iOS can't side load stuff.

**Comment by willis936** [comment]
What’s the issue?  I’m not suggesting anything that introduces a hindrance to players on other platforms or puts serious load on the developer.  Factorio makes great use of steam’s beta feature and everyone loves them for it.  It’s just handy to be able to choose the release.

**Comment by Kyllingene** [comment]
@itcannotbe: *They want the OPTION to play earlier releases, NOT for it to be delayed.* PLEASE read before deciding to be rude.
