### ISSUE TITLE
Commanded units immediately add to core resources when mining near core

### ISSUE THREAD

**Issue by GoboII** [Anuken/Mindustry-Suggestions#1692]
**Describe the content or mechanics you are proposing.**
Currently, when the player mines resources while close to the core, the resources are automatically added to the core without having to drag them. Units currently being commanded will mine when the player-controlled unit mines, but the resources mined by commanded units will not be automatically deposited into the core. I am proposing that this be changed so that they are.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would reduce hassle when mining with commanded units because players would no longer have to switch control to different units in order to deposit resources.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quezler** [comment]
this was done as a performance thing, since the transfer caused a lot of packets
