### ISSUE TITLE
Gas planet? 

### ISSUE THREAD

**Issue by Joshwelyt** [Anuken/Mindustry-Suggestions#1693]
**Describe the content or mechanics you are proposing.**

Just a planet idea like a planet with gas but had rock in it but mostly gas

And like some gasses dmgs buildings and units and enemy units not core tho thatll be too um bad?,and others will boost buildings and units if they get builded or the units pass thorugh the gad maybe like carbon boosting combustion and steam gen maybe? 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Itll add a uniqueness to the planet and modders can add theyre own gases to further content 
Idk its just an idea for a planet

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Quezler** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1576#issuecomment-745019121

**Comment by userlol2** [comment]
But how should you build things on gas planet
