### ISSUE TITLE
Edit unit formations using mouse drag.

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1694]
**Describe the content or mechanics you are proposing.**
Let's say you have a circular formation and you want to modify it - just click on the unit and drag them using mouse (touch).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You can make a whatever formation you want.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slava0135** [comment]
However I am not really sure about controls, perhaps you have to hold G button.

**Comment by iLagSoUhax** [comment]
https://trello.com/c/aWaX8E9F

shelved, I don't suggest you close this though, I like the idea and hope anuke will consider it.
