### ISSUE TITLE
Diagonal Line tool

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry-Suggestions#1695]
A new option for Line tool in map editor that allow us to draw perfect diagonal lines.

Drawing long and perfect diagonal lines is too hard for map making and it makes map making harder, with diagonal support for line tool players can draw long and perfect diagonal lines so making symmetric and smooth maps will be easier.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
what does the line tool
draw a curved line
yes

**Comment by Kyllingene** [comment]
This might be better as a mode for the line tool, like orth mode but diagonal.

**Comment by iLagSoUhax** [comment]
Or, rather, maybe holding shift whilst using the line tool could result in a perfectly diagonal line.

**Comment by Kyllingene** [comment]
You could also make the orth tool the shift thing, then replace it in the line tool modes menu with diag.

**Comment by MrByars** [comment]
> Or, rather, maybe holding shift whilst using the line tool could result in a perfectly diagonal line.

Mobile...

**Comment by Kyllingene** [comment]
> Mobile...

True... I guess it would have to be content as an ordinary mode.

**Comment by Kyllingene** [comment]
Also, shift is already the pickblock keybind...

**Comment by Bohaska** [comment]
> Also, shift is already the pickblock keybind...

Then use the Delete key

**Comment by Kyllingene** [comment]
I don't know about you, but if I had to hold the delete key, I would probably prefer it as a mode. Moving my hand *that* much for a simple diag line just seems annoying. Yes, this sounds nitpicky, but it's easier to do it with mouse at that point.

**Comment by itcannotbe** [comment]
How can someone make 2 duplicates of his own suggestion?

#807 #495

**Comment by Kyllingene** [comment]
Oh, those were both his? Yeah, please close at least 2 of them. This is unnecessary spam that no-one wants.
