### ISSUE TITLE
trading cards for steam ver.

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1696]
**Describe the content or mechanics you are proposing.**
simply add trading cards to the steam version. you could include the planets, and units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
itll add depth to the steam version, and is very easy to implement. there shouldnt be a huge hassle for a nice extra feature for the steam version. plus, why not?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
good

**Comment by Gdeft** [comment]
https://trello.com/c/0GrlFqqX

**Comment by iLagSoUhax** [comment]
@sup3r87 This has already been planned in the Trello. please read through the Trello before making a suggestion, since it's likely that your suggestion is already planned. Close this.

**Comment by sup3r87** [comment]
> https://trello.com/c/0GrlFqqX

whoops, didnt see the trello post when i did a quick scan
