### ISSUE TITLE
Show ghosts while placing schematics

### ISSUE THREAD

**Issue by SmolBig** [Anuken/Mindustry-Suggestions#1697]
**Describe the content or mechanics you are proposing.**
Title

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When re-entering a lost map and trying to rebuild it's helpful to have the ghosts present to see where the destroyed things were at, but when I see a destroyed structure that was made from a schematic I always run into the problem of grabbing the schematic and then not remembering exactly where to place it because the ghosts are no longer visible. If the ghosts were visible for schematic placement the way they are for normal placement then I wouldn't have to cancel and place marker blocks and then fetch the schematic again.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
yes

**Comment by Humanoid-X** [comment]
good
