### ISSUE TITLE
Comments cannot be used inline

### ISSUE THREAD

**Issue by Lonami** [Anuken/Mindustry-Suggestions#1698]
**Describe what you would like changed, and why.**

I would to change this [LAssembler.java#L64-L65](https://github.com/Anuken/Mindustry/blob/5654e3120dfa0398e1199a1748c38b6e6b63208e/core/src/mindustry/logic/LAssembler.java#L64-L65):

```java
            //comments
            if(line.startsWith("#") || line.isEmpty()) continue;
```

As it stands, comments are kind of useless, because it's already hard enough to keep track of the jump line numbers. Comments, needing their own line *which is then removed*, screw up those line numbers even more. With inline comments, the line numbers would be respected and it would be a lot easier to follow the jumps.

**Describe the changes you want to propose. Include possible alternatives.**

The proposed change (formatting aside) is the following:

```java
            // comments
            int commentIdx = line.indexOf('#');
            if (commentIdx != -1) {
                line = line.substring(0, commentIdx).trim();
            }
            if (line.isEmpty()) {
                continue;
            }
```

I'd also like comments to be better documented.

I spotted this while trying to find how I would fix https://github.com/Anuken/Mindustry/issues/4189.

**Comment by sample-text-here** [comment]
~~if you have the code, make a pull request~~

**Comment by Lonami** [comment]
Normally I'd prefer to first get feedback and not bother with the PR process if there's no chance of this getting merged, but this is small enough where this is fair enough.
