### ISSUE TITLE
Scrap Separators

### ISSUE THREAD

**Issue by WellsEvan** [Anuken/Mindustry-Suggestions#1699]
**Describe what you would like changed, and why.**

When you launch into a new area with no titanium, it's impossible to acquire titanium unless you include titanium in the launched supplies. Because you can get titanium from separated scrap, turning slag into resources is a viable option. However, because the separator requires titanium to build, you can't acquire it in a new zone unless there's buildings to deconstruct in your new zone. Additionally, once you're in a zone, you can't relaunch to include the minimum 25 titanium, so even if you launch from a world with titanium and didn't include it, you're now stuck without it for good in that zone. 

**Describe the changes you want to propose. Include possible alternatives.**

I would say requiring something instead of titanium for the separator makes it more balanced and allows for scrap separation to become a more valuable method for acquiring resources.

**Comment by Yell245** [comment]
No, it will disbalance things. If the map creator doesn't include titanium - you won't be able to get more advanced technologies. It's better control for map makers

**Comment by iLagSoUhax** [comment]
This could be a viable option, although it might result in a player separating titanium in a map in which it is not meant to be separated. In short, it might lead to titanium being made in any map with scrap, regardless of whether or not the map is meant to have titanium. 

In short, Anuke is very likely to reject this.

**Comment by Yell245** [comment]
*Plus you didn't search another suggestions, it was already suggested and yeeted off*

**Comment by WellsEvan** [comment]
I don't see how it disbalances it - you can launch titanium to the zone
with your starting resources, and with that you can get the titanium from
scrap.

**Comment by Kyllingene** [comment]
I think they meant it disbalances custom maps; look at this line:

> If the map creator doesn't include titanium

Most sectors are proc gen, if I'm not mistaken. Thus, that line wouldn't make much sense in terms of campaign.

**Comment by WellsEvan** [comment]
I haven't had any experience playing custom maps - I'm referring entirely to the campaign and system of launching resources to new sectors from sectors you have cleared.

**Comment by WellsEvan** [comment]
Or another possibility would be to allow interchange of resources between different cleared adjacent sectors after clearance.

**Comment by Kyllingene** [comment]
The thing is, whatever changes you made here would affect mapmakers, servers, etc, not just campaign. And yes, while making players get titanium through scrap is a nice option to have as a mapmaker, you don't want it to *always* be possible. Imagine trying to make a low-tech map, but players beat it with tons of enemies.

> Or another possibility would be to allow interchange of resources between different cleared adjacent sectors after clearance.

Good idea, I like it.

**Comment by WellsEvan** [comment]
> The thing is, whatever changes you made here would affect mapmakers, servers, etc, not just campaign. And yes, while making players get titanium through scrap is a nice option to have as a mapmaker, you don't want it to _always_ be possible. Imagine trying to make a low-tech map, but players beat it with tons of enemies.

I understand, that totally makes sense. Thank you for showing me that perspective.

**Comment by Kyllingene** [comment]
> Good idea, I like it. I think it's called a Launch Pad.

**Comment by NajimiOsana** [comment]
There's a thing called "Loadouts" and "Launchpads", would you mind using them?

**Comment by Kyllingene** [comment]
Loadouts are one-time:

> Additionally, once you're in a zone, you can't relaunch to include the minimum 25 titanium

And launch pads are already suggested (and use titanium):

> called a Launch Pad.

**Comment by InvalidError404** [comment]
Well, if you are playing campaign and have cleared a map that contains titanium as you should have to unlock tech that requires it, then launching titanium to maps that don't have it and you forgot to pack some at launch is definitely the way to go to get self-supply on the otherwise titanium-less map started.

I launched thorium (and everything else) into the Ground Zero and other earlier maps from the Nuclear Production map to max out core storage so I I can relatively easily re-launch into NP from one of the other maps with enough resources to let polys automatically rebuild most of it whenever it randomly gets wiped,
