### ISSUE TITLE
[discord server] reading comprehension test

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#17]
**Describe the content or mechanics you are proposing.**

before entering the server, corebot must check that someone can read english or use a translator.
maybe a simple "React with :router: to enter the server" is all that is needed.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

keep out people who arent able to read

**Before making this issue, replace the underscores in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Katsute** [comment]
This sounds more like of a plugin; and mindustry is a multilingual game so forcing English upon users in all servers doesn't seem right.

**Comment by DeltaNedas** [comment]
the rules are all in english and say to use a translator 
its for the discord server so it could be added to corebot, its unrelated to mindustry servers

**Comment by KK6DOC** [comment]
That guy who pinged anuke 3 times I think is the reason for this

**Comment by DeltaNedas** [comment]
correct

**Comment by micoplasma** [comment]
either they don't/can't read rules and channel description or just don't respect any of it
the previous can atleast be helped with this

**Comment by MEEPofFaith** [comment]
I mean, I still don't know how to translate Java to JS because no one told me how *cough* Egg *cough*.

**Comment by Axzye** [comment]
It's been a year and people can still get into the server without actually reading the rules..
