### ISSUE TITLE
Query System

### ISSUE THREAD

**Issue by ViperZeroOne** [Anuken/Mindustry-Suggestions#170]
**Describe the content or mechanics you are proposing.**

For those of us hosting servers off our own dedicated systems, it would be nice if there was a way to query the server for the map name and number of players.  I couldn't find anything anywhere saying this was already possible.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will improve hosting options, so server owners can advertise their servers more freely.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ViperZeroOne** [comment]
I should also note, I attempted to use the standard "Steam Query" method in my php script but it didn't return me any information from the server.

**Comment by Anuken** [comment]
This is already possible, see how CoreBot pings servers.
