### ISSUE TITLE
daily missions: asteroid belt

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1700]
**Describe what you would like changed, and why.**
theres a "daily missions" page on the trello. im proposing that, an asteroid belt be added to the star system, for daily missions. 

**Describe the changes you want to propose. Include possible alternatives.**
essentially, every day an asteroid from the tumbling chaos comes close enough to serpulo to launch to (without the accelerator). daily missions can be carried out this way. additionally, this will allow the use of the 𝓯 𝓪 𝓫 𝓾 𝓵 𝓸 𝓾 𝓼 space floor tiles that you cant experience anywhere in campaign. you can even make the asteroids diverse, like having molten ones, allowing you to use the slag tile floors.
another idea, based on the fact there are multiple planets, is that there are asteroids just floating around the star system. this way asteroids can come by planets that arent by the asteroid belt. maybe even, the belt could be a few planets away, and the missions on the belt are notoriously difficult. theres lots of room for adjustment here.

**Comment by Humanoid-X** [comment]
good

**Comment by iLagSoUhax** [comment]
agreement noise.

**Comment by Bohaska** [comment]
Have you checked the trello?

**Comment by Kyllingene** [comment]
Oh, just realized: this is a feature request, and not a feedback/balancing thing (asking for something new, not a change to something old).
