### ISSUE TITLE
builder drones are a prime tool for griefing.

### ISSUE THREAD

**Issue by Frontrider** [Anuken/Mindustry-Suggestions#1703]
**Describe what you would like changed, and why.**
When a bot is placing things there is no way to figure who coded it in, making it an extremely easy and straightforward way to grief, with practically no repercussions. May not get found out until we just lose.

**Describe the changes you want to propose. Include possible alternatives.**
I see 2 solutions:
- allow servers to disable drone building (they suggested it to me but I do not like it, feels like mc servers disabling redstone as is)
- make the drones inherit the name of the coder in the "last interacted with" field so it can be found out, and can be acted upon with no loss of features. I'd prefer this solution.

Before making this issue, replace the underscores in the following boxes with an X to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

- [x]   I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
- [x]   I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RedstonerKBC** [comment]
"Last accessed" currently does not help much. Griefers know about it and quickly destroy things rather than interact with blocks and risk being found out. In fact, I've been kicked more times for people mistaking me for the griefer because the stuff I built has my name on it and is near where the griefer griefed. Most of the time people have no idea who the griefer is and ban random people. Even when they see with their own eyes there's no guarantee a votekick will win enough votes to kick them. The griefer will leave and come back with a different username and grief all over again. 

As for processors, I actually think adding "last accessed" to drones might help because theres almost no way I can think of to confuse other players. The griefer places a processor and all units it binds to have their name on it even if you possess and unpossess they get rebound with the griefer's name.

**Comment by Yell245** [comment]
It's too complex for a griefer. They're often stupid and couldn't make a scheme. They'll just unbuild stuff manually

**Comment by Frontrider** [comment]
> It's too complex for a griefer. They're often stupid and couldn't make a scheme. They'll just unbuild stuff manually

Third round in a row, with the same grief? 1 click to place schematic? You don't need to know how to make it, just take one from anywhere. That is never a good argument. If something is possible then people are doing it.

> As for processors, I actually think adding "last accessed" to drones might help because theres almost no way I can think of to confuse other players. The griefer places a processor and all units it binds to have their name on it even if you possess and unpossess they get rebound with the griefer's name.

That is the idea. random stuff everywhere can not have any other purpose, and you do not need to look for who to ban. Still need to find where is the processor, but at least you can get rid of the perpetrator fast, and can attempt to trace back the griefer's steps. It literally turns into "I hereby announce that I want to be banned".

**Comment by Frontrider** [comment]
Last accessed may not cut it, may need a specific "last edited" flag on the processors, as I got banned because someone touched what I placed.

**Comment by HaphLife** [comment]
Perhaps a full blown actions list with each player’s interaction with the world that can be indexed by time, player, or location is in order. Want to know who broke the block here? Search by location, pick a person that broke there, search by that person, and you can suddenly see the context.

**Comment by Kyllingene** [comment]
Let's say you are playing on a 500x500 map (ideal for any large server), and with 20 people. Well, assuming every player interacts with half the tiles exactly once, that is ***2,500,000*** interactions the server has to store. Without some sort of cap, this would make any large server crash, and several smaller ones too. A plugin for this, maybe, but not a built-in feature, would be handy.

**Comment by Frontrider** [comment]
> > Perhaps a full blown actions list with each player’s interaction with the world that can be indexed by time, player, or location is in order.
> 
> Let's say you are playing on a 500x500 map (ideal for any large server), and with 20 people. Well, assuming every player interacts with half the tiles exactly once, that is _**2,500,000**_ interactions the server has to store. Without some sort of cap, this would make any large server crash, and several smaller ones too. A plugin for this, maybe, but not a built-in feature, would be handy.

Definietly. You need a dedicated database for that at least, and that is a burden on small scales.
