### ISSUE TITLE
T3 or below units can "posses" payload conveyor/router 

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry-Suggestions#1704]
**Describe what you would like changed, and why.**
Ability for T3 units or below to "posses" payload conveyors/routers such that the unit is placed into a belt.
Uses: Upgrade unit instead of waiting for new one to be created (low income maps)
Transport Naval units from one water mass to another (instead of having to rely on megas and such)

**Describe the changes you want to propose. Include possible alternatives.**
Just like you can posses core, ya posses the payload conveyor to place unit into the belt, then you get spawned in core / another unit of same type

**Comment by itcannotbe** [comment]
Alternative: #1690

**Comment by L0615T1C5-216AC-9437** [comment]
true but i doubt anuke would add a block for such feature, for v7 maybe but i want such feature for v6

**Comment by HaphLife** [comment]
Honestly you should be able to just walk up onto it and snap onto the conveyor IMO. If a unit is on a conveyor, they should be pushed by it. Might make some funny defenses possible if you can use payload conveyors to move enemies, but I don’t 
think it would be particularly powerful.

**Comment by hoxu** [comment]
#521 is a similar suggestion.

**Comment by hoxu** [comment]
#620 is also related.
