### ISSUE TITLE
Let Quezler close issues and PRs

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#1706]
To clean up duplicates and troll posts so you don't have to.
It'll keep your sanity intact which will positively affect Mindustry development.

**Comment by DeltaNedas** [comment]
autoremove ios bug reports

**Comment by Humanoid-X** [comment]
good

**Comment by Kyllingene** [comment]
poor quezler

**Comment by Bohaska** [comment]
> To clean up duplicates and troll posts so you don't have to.
> It'll keep your sanity intact which will positively affect Mindustry development.
           
Also, Quezler will auto remove any posts which don't follow the template. (I'm looking at YOU)
