### ISSUE TITLE
Ore can be placed on shallow water

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1707]
**Describe the content or mechanics you are proposing.**
Let shallow water tiles contain ores. These ores would be underwater and can me mined or drilled with drills. You can't place ores on deep water, slag, oil, or deep spore water, only on shallow water tiles where you can already place blocks. Drills placed on underwater ores are automatically cooled by water.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More options for mapmakers. Allows more gameplay possibilities in maps with lots of water. In real life people drill for oil in the ocean so it makes sense. This doesn't count as anything "underground" since ores already spawn on top of other blocks. All this does is allow ore to spawn on top of shallow water blocks. It makes sense they'd be automatically cooled since they're literally drilling underwater. Why pump water from a block away when you're literally standing on top of water? Of course you'd need to implement the graphics to make it look like they're actually underwater, but ores already wave around when they spawn on mud tiles so I imagine that's doable.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
![Screenshot_20210102-150853](https://user-images.githubusercontent.com/61173114/103467455-7a325f80-4d0c-11eb-97f6-a0d506ac0b42.png)
this can only be found on campaign sectors so i agree

**Comment by Humanoid-X** [comment]
good

**Comment by Kyllingene** [comment]
> good

**Comment by HaphLife** [comment]
> > good

**Comment by QmelZ** [comment]
> this can only be found on campaign sectors so i agree

it is possible to put them in custom maps with mods actually, but it would be good to have them in vanilla

**Comment by itcannotbe** [comment]
This a bad idea because.........

People will ask for having drills boosted when drilling under water ores.

And yes, that's the only reason I can think of. XD.

**Comment by QmelZ** [comment]
> This a bad idea because.........
> 
> People will ask for having drills boosted when drilling under water ores.
> 
> And yes, that's the only reason I can think of. XD.

what do you mean, that's the entire point

**Comment by itcannotbe** [comment]
Same reason why you need sand for oil extractor.

**Comment by RedstonerKBC** [comment]
Drills only liquid booster is water. It's not like it will prevent players from using cryofluid to cool drills.
