### ISSUE TITLE
More Distribution options for liquids. (Valves and Siphons + Sealed Tanks)

### ISSUE THREAD

**Issue by Nekuna** [Anuken/Mindustry-Suggestions#1709]
**Describe the content or mechanics you are proposing.**
New Distribution options for liquids to allow for more versatility. Overflow siphon, Underflow siphon, Gateway valve, Sealed Liquid Tank, and Faucet. 
All of these suggestions (with the exception of the gateway valve) are nearly identical to the existing distribution blocks meant for items. The list below will give a short description of each features purpose, it's size, and it's pre-existing counterpart (For better understanding).

1. Overflow siphon. 1x1. Only outputs liquids to the left or right if the front path is blocked. Cannot be used next to other siphons. (Liquid version of the Overflow Gate)
2. Underflow siphon. 1x1. Opposite to an overflow siphon. Outputs to the front if the left and right paths are blocked. Cannot be used next to other siphons. (Liquid version of the underflow gate)
3. Gateway Valve. 1x1. Blocks liquid from passing when closed. Allows liquid to pass when opened. Only allows flow in one direction. (Unique feature, Will go into greater detail later on)
4. Sealed Liquid Tank. 2x2. Stores a medium amount of liquid. Requires a Faucet to output liquid. (Liquid version of the container)
5. Faucet. 1x1. Outputs selected liquid from nearby blocks. (Liquid version of the unloader)

Clarification of the Gateway Valve and Sealed Liquid Tank. 
*Gateway Valve*- I'm not entirely sure if I can explain this one clearly, but I'll do my best. The Gateway Valve can act as liquid junction, allowing intersecting conduits and their respective liquids to cross over each other. However, instead of allowing both liquids to pass at the same time, the valve will only allow one liquid to 'cross over' the other liquid until the valve is toggled. This toggle will be visualized with a Line that represents which way liquid can flow.
        Just in case you're still confused, here's an example of how the Gateway Valve would work with two conduits: Two conduits need to cross paths. A gate valve is used to allow intersection. both conduits are intersecting at a 90 degree angle and are therefore perpendicular. One conduit holds slag, the other holds oil. The visual indicator on the valve is parallel to the slag conduit and perpendicular to the oil conduit, meaning the oil cannot flow, while the slag can flow through the valve. The Valve is then toggled, causing the visual indicator to rotate by 90 degrees, making it parallel to the oil conduit, and perpendicular to the slag conduit, therefore stopping the slag from passing through the valve, while instead only letting the oil pass through the valve.
Hopefully you get it now.

*Sealed Liquid Tank [SLT]*- In the same way a container or vault does not output items to surrounding blocks on their own, the SLT would not output liquids to any surrounding conduits or blocks. Only a faucet can allow an SLT to output any liquid.

The ingredients required for the Overflow and Underflow siphons would simply consist of metaglass and graphite. The ingredients required for the Gateway valve and Faucet would consist of metaglass, graphite, and titanium. The ingredients required for the Sealed Liquid Container would consist of metaglass, titanium, and plastanium.

Note* Liquid sorters are pointless, hence why they weren't suggested.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
V6 did not add any new content to the plumbing section (Tsunami is a turret, So it doesn't count) aside from minor changes to the pumps. These new Distribution options would make the plumbing section feel loved. Jokes aside, these new distribution features would allow for more versatility when dealing with liquids, especially for schematics dealing with oil or cryofluid, since the acquisition of said liquids both require water. (I know oil can be pumped, but 2/3 ways to acquire oil also use water.) The additions of features such as the Sealed Liquid Tank or the Gate Valve would allow for more complex designs and schematics to come into fruition. Casual players would be able to use them intuitively as they are not overly complicated, while more experienced players could make good use of them in schematics and other miscellaneous scenarios such as turret cooling.
This is all without mentioning that the lone liquid router is just not the best for the plumbing section, especially since it is completely outshined by the liquid tank. 
For these reasons any many more I couldn't fit on here, I believe that more liquid distribution options would make a great addition to Mindustry.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [✔] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [✔] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [✔] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [✔] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
2x2 liquid tank?

https://github.com/Anuken/Mindustry-Suggestions/issues/360#issuecomment-667441008

Also tanks don't even output on their own.

**Comment by itcannotbe** [comment]
Also you cannot realistically make the same pipe carry different liquids. Both in real life and in-game.

**Comment by itcannotbe** [comment]
> This is all without mentioning that the lone liquid router is just not the best for the plumbing section, especially since it is completely outshined by the liquid tank.

Furthermore instead of suggesting a dozen more things why not just rebalance the tank and the liquid router.

**Comment by Nekuna** [comment]
> 2x2 liquid tank?
> [#360 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/360#issuecomment-667441008)
2x2 to sacrifice capacity for versatility. Was my idea of balance but I don't mind changing that.


> Also tanks don't even output on their own.
Yes they do. If you put a conduit next to a tank with liquid in it, the liquid will go into the conduit. If you put multiple tanks side by side, they act as one tank. the idea is that it won't automatically output any liquids from the tank.

**Comment by Nekuna** [comment]
> 2x2 liquid tank?
> 
> [#360 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/360#issuecomment-667441008)
> 
> Also tanks don't even output on their own.

1. just my idea for balance. I can change that part.
2. Tanks output a liquid automatically if there is a liquid inside.

Had to redo the reply.

**Comment by Nekuna** [comment]
> Also you cannot realistically make the same pipe carry different liquids. Both in real life and in-game.

What is this in reference to? I never suggested anything like that.

**Comment by Nekuna** [comment]
> > This is all without mentioning that the lone liquid router is just not the best for the plumbing section, especially since it is completely outshined by the liquid tank.
> 
> Furthermore instead of suggesting a dozen more things why not just rebalance the tank and the liquid router.

rebalancing wouldn't do anything because to "rebalance" the tank and router to do the things I suggested, you would have to change them completely.

**Comment by itcannotbe** [comment]
> > 2x2 liquid tank?
> > [#360 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/360#issuecomment-667441008)
> > Also tanks don't even output on their own.
> 
>     1. just my idea for balance. I can change that part.
> 
>     2. Tanks output a liquid automatically if there is a liquid inside.
> 
> 
> Had to redo the reply.

To where? They need something that actually accepts the liquid before they can output.



> > Also you cannot realistically make the same pipe carry different liquids. Both in real life and in-game.
> 
> What is this in reference to? I never suggested anything like that.

"these new distribution features would allow for more versatility when dealing with liquids, especially for schematics dealing with oil and cryofluid"

And apparently I didn't read what came next. XD.

> > > This is all without mentioning that the lone liquid router is just not the best for the plumbing section, especially since it is completely outshined by the liquid tank.
> > 
> > 
> > Furthermore instead of suggesting a dozen more things why not just rebalance the tank and the liquid router.
> 
> rebalancing wouldn't do anything because to "rebalance" the tank and router to do the things I suggested, you would have to change them completely.

#1711 A simple rebalance. It would be effective enough to kill tank sneks.

**Comment by Nekuna** [comment]
These replies will get big so I'll just shorten with quotations.

Q:"To where? They need something that actually accepts the liquid before they can output."
A: That's what I was referring to. If a conduit is making contact with a tank, it will accept the liquid. You know how a container/vault doesn't automatically output items onto a conveyor belt if it doesn't have an unloader? That's what I want. 

The thing about mixing liquids. I should fix the wording. 
I'm not suggesting liquids can share a conduit, I used that as an example of how the different features can be utilized. I'm talking about compact schematics where liquids are at risk of going where they aren't meant to go. That's the whole reason I never suggested a "liquid sorter". 

"#1711 A simple rebalance. It would be effective enough to kill tank sneks." 
This is a content idea, not a balancing or feedback issue. My post has nothing to do with balancing liquid routers and tanks, it's about content that can serve a purpose that pre-existing content can't do. The things I suggested are to do exactly that.

**Comment by BlueWolf3682** [comment]
> Also you cannot realistically make the same pipe carry different liquids. Both in real life and in-game.

junctions do it but junctions dont exactly transport the liquids in code, more teleport them (a heavily abused feature at least by me)

**Comment by InvalidError404** [comment]
> Also you cannot realistically make the same pipe carry different liquids. Both in real life and in-game.

You can have multiple things share the same pipe in real life. As long as they aren't miscible or reactive with each other, there should be a combination of mechanical, chemical and physical process that can separate them: crude oil is a mix of 50+ chemicals from methane to heavy hydrocarbons, sulfur compounds and other stuff, most of which separated by distillation to give us methane, ethane, propane, butane, gasoline, diesel, kerosene, multiple grades and blends of engine and other oils, etc.

Using one pipe to transport multiple things is feasible IRL, though not practical if you cannot tolerate trace amounts of cross-contamination.

A real-life example of the same "pipe" being used to transfer different fluids albeit at different times is gas stations: the same nozzle is used for all grades of gasoline blends.

**Comment by XEN0PHIL** [comment]
Liquid over/underflows make no sense, you cannot define a "blocked" state.

**Comment by Nekuna** [comment]
> Liquid over/underflows make no sense, you cannot define a "blocked" state.

If you completely fill a liquid tank, no more liquid can flow into it, therefore making it "Blocked". If you are inputting oil into a coal centrifuge and the centrifuge is full for even a brief moment, that is a blocked state.

**Comment by BlueWolf3682** [comment]
...liquids are wierd, reaching this blocked state is janky
