### ISSUE TITLE
unloader speed

### ISSUE THREAD

**Issue by simon-auch** [Anuken/Mindustry-Suggestions#171]
**Describe the content or mechanics you are proposing.**
Increase speed of the unloader to match the speed of blue conveyors.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Everyone knows that belts that aren't completly full are bad, right?
I know its also possible to use a overdrive projector to increase the unloader speed, but that also increases the speed of the local belts, which therefore doesn't help to get full belts.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SnakkiZXZ** [comment]
I think the unloader has a normal speed. I don't think it requires improvement.

**Comment by Absolute359** [comment]
@Anuken a little reminder to this suggestions
it seems like its the only thing left to balance to match titanium conveyors
additional 0.5items/sec would allready be enough
![image](https://user-images.githubusercontent.com/66265700/103487914-04f88480-4e09-11eb-8c96-a5062e217e45.png)
