### ISSUE TITLE
Nerf max transfer between adjacent tanks.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#1711]
**Describe what you would like changed, and why.**
Title.

**Describe the changes you want to propose. Include possible alternatives.**
Limit the transfer to just 25%x10^-1 of what is currently possible.

**Comment by BlueWolf3682** [comment]
whats the point? this is only abused by the 10% that actually know how to liquids logistics, noobs always use massive conduit sneks

**Comment by itcannotbe** [comment]
> whats the point? this is only abused by the 10% that actually know how to liquids logistics, noobs always use massive conduit sneks

Same with all sneks, it doesn't take long before almost everyone uses them.

**Comment by BlueWolf3682** [comment]
its been more than soon since its been discovered, the best way to not have it used is dont make a big banner of a suggestion about it

**Comment by XxsuperdeadlysniperxX** [comment]
@itcannotbe i agree with bluewolf also tanks are big so you can't always spam them and making a suggestion that announces the feature with the possibility of anuke saying "why nerf this?" Is like ~51%-49 so to speak. If he doesm't fix then this suggestion is just going to it a meta i like op things however tanks are expensive to build (in terms of nonmaxed out resources)

**Comment by XxsuperdeadlysniperxX** [comment]
Though that is my opinion someone could have there own

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
