### ISSUE TITLE
Playable Sun Sector(s)

### ISSUE THREAD

**Issue by HaphLife** [Anuken/Mindustry-Suggestions#1713]
**Describe the content or mechanics you are proposing.**
In the v7 update, alongside the other planets, I’d love to have at least one sector on the sun. Even if just as an easter egg. Perhaps it could take advantage of/be related to the “launching resources into the sun” text that shows up when a launch pad loses it’s destination? 

It definitely needs to be gated heavily and be hard to access so that newish players don’t get confused by it when first exploring interplanetary travel. Perhaps you could fulfill issue#1052 (https://github.com/Anuken/Mindustry-Suggestions/issues/1052) or something like it (but for all planets) with this?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would be funny as heck. It wouldn’t really be useful, except maybe if launchpads losing their destination was a common issue you could use the sun sector to launch them elsewhere. You might want to add a few “sun tiles” which could be good for mapmakers. Thermal generators could perhaps work very well on the sun, but since you can’t launch power, that’s likely not very useful. Perhaps a huge boost to silicon crucibles as well? Water extractors shouldn’t work on sun tiles.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. At least I don’t think it does. You might be a sneaky boi and just nobody knows about it yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
It's a game. It doesn't have to be realistic. It just has to be good. Keep that in mind before you comment below about how suns aren't solid yadda yadda lol

**Comment by itcannotbe** [comment]
Also take note it's supposed to be an easter egg suggestion.

**Comment by joshuaptfan** [comment]
We already have "sun tiles". Have the entire map be an ocean of slag with small islands of cooler rock, which are comprised mostly of magma tiles.

**Comment by HaphLife** [comment]
> We already have "sun tiles". Have the entire map be an ocean of slag

The fact that you can pump slag and use a separator with it, and that hot rock has so much solid parts seems wrong for the sun, but if he doesn’t want to add any new tile varieties this is a good idea.
