### ISSUE TITLE
remove router highway

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1714]
**Describe what you would like changed, and why.**

bullshit checkerboard of routers and conveyors popularized by zacbytes has taken over many public servers

**Describe the changes you want to propose. Include possible alternatives.**
- clog routers
- disable conveyors
- thorium explosion
- random fires like nydus 5.0 snek protection

**Comment by itcannotbe** [comment]
Disable the conveyor if it has 4 routers adjacent to it on all sidea.

**Comment by joshuaptfan** [comment]
It's just a fad, it will go away on its own (I hope).

**Comment by DeltaNedas** [comment]
it has been here for weeks it must be destroyed

**Comment by GreyMario** [comment]
the problem here is that a titanium ruouter highway is actually legitimately better than an equivalent section of pure titanium belts

faster transport for the same throughput and footprint, at least in straight lines

and anything done to rebalance routers/etc in checkerboards will cause problems when routers and distributors are used as designed/intended

**Comment by itcannotbe** [comment]
The fix for that is even more simpler, add a speed penalty for conveyor in between routers.

**Comment by DeltaNedas** [comment]
yes and then you play multiplayer and one item can clog them all
as usual noobs should be banned from multiplayer

**Comment by itcannotbe** [comment]
> yes and then you play multiplayer and one item can clog them all
> as usual noobs should be banned from multiplayer

Exactly.

**Comment by itcannotbe** [comment]
The fix for that is even more simpler, add a speed penalty for conveyors in between routers and in extension distributors.

**Comment by ThatOneBepis** [comment]
facts: it looks ugly and is like a v5 snek, a bug that is abused

Though i think this would become a plugin, but then realize some servers wouldn't implement it for the sake of extra players, and the fact that it wasn't how sneks were killed.

**Comment by BlueWolf3682** [comment]
theres no way of removing this without fucking up the basegame.

**Comment by RedstonerKBC** [comment]
This is like asking him to remove pixelart because of the inappropriate drawings some people build. It takes more away from the game than it does to protect you.

**Comment by RedstonerKBC** [comment]
> as usual noobs should be banned from multiplayer

This is why people who can't get jobs in real life because they have no experience can't get experience.

**Comment by sample-text-here** [comment]
this needs to be stopped somehow

i think "stop conveyors if they're surrounded by routers" is good

**Comment by joshuaptfan** [comment]
Router highway is different from sorter+overflow chains. Sorter/overflow was optimal, so it needed intervention to be stopped. Router highway is popular but not optimal, and has various downsides such as easy clogging and massive usage of space.

**Comment by itcannotbe** [comment]
Well by know you should know people won't stop using this until 1 out of 2 things happen.

Either the game prevents them from using it

-or-

Something more op/looks op comes along.

**Comment by Bohaska** [comment]
> as usual noobs should be banned from multiplayer

Seriously, dude? Maybe instead of your idea, we should have 'pro only' servers and have 'welcome to noobs' servers

**Comment by Bohaska** [comment]
> this needs to be stopped somehow
> 
> i think "stop conveyors if they're surrounded by routers" is good

You do realize that they can ditch routers and use sorter and inverted sorters to make better highways (also, why the name?)

**Comment by itcannotbe** [comment]
Then do the same with them. Easy.

**Comment by Bohaska** [comment]
> Then do the same with them. Easy.

To do so, the system needs to check if a router, sorter type or overflow type is bordering at least 3 sides of a conveyor. If yes, then the neighboring router sorter types and overflow types blocks will be disabled.

**Comment by Legomonster33** [comment]
they are very good,
except that noobs use them on multiplayer
where they dont work,

**Comment by Jammo2000** [comment]
Router highways are like wexts: very useful in certain situations, but commonly misused. They don't need banning.

**Comment by itcannotbe** [comment]
They're very efficient at destroy brain cells (if you still have them).

1. There is no actual benefits using them.
2. There no way you can cross them.
3. They take up a large space.

All in all they should be broken. Just because it's just most effective at being an eyesore than anything else.

**Comment by itcannotbe** [comment]
> they are very good,
> except that noobs use them on multiplayer
> where they dont work,

You forgot custom games.

**Comment by Legomonster33** [comment]
> > they are very good,
> > except that noobs use them on multiplayer
> > where they dont work,
> 
> You forgot custom games.

No I didn't forget custom games because if your the one making them its you who is the noob, not one of your idiot teammates

**Comment by catatagun** [comment]
Yes router converyer look ugly

**Comment by BlueWolf3682** [comment]
jesus yall are fricking toxic, your choices are these: 
make a pr that fixes this
dont play multiplayer
suffer

thats it. those are all of your options. pick one, no extras are allowed.

**Comment by Bohaska** [comment]
> make a pr that fixes this
> dont play multiplayer
> suffer

Make a mod for this
Ask anuke to do this

**Comment by Humanoid-X** [comment]
Yes they look ugly and I don't like them too (Although I like DARK). But it is actually the same as some router-conveyor chains put together. It's actually same, just more clogging.

**Comment by RedstonerKBC** [comment]
Before we even consider banning router highways which are merely an annoyance, we need to consider banning water extractors which are easily the most misused block in the entire game. Every server I go to people will use water extractors where pumps could have been substituted. They'll even place extractors directly next to the water. People actually prefer paying for less water than pumping more water for free. You want to ban something that people misuse then start with that.

**Comment by Kyllingene** [comment]
Actually, completely, utterly, BAN water extractors? Goodbye challenge maps, any proc gen map with little water, oh hey look, ***bye-bye meltdowns on hard levels***. Banning the water extractor entirely is a terrible idea, balancing it is not.

**Comment by RedstonerKBC** [comment]
I wasn't being serious. But if we do ban something banning water extractors would be better than banning router highways, if we're banning things based solely on how annoying they are.

**Comment by Kyllingene** [comment]
Oh, lol, ok. Sorry, I didn't read the emotion you wrote. My bad!

**Comment by itcannotbe** [comment]
> I wasn't being serious. But if we do ban something banning water extractors would be better than banning router highways, if we're banning things based solely on how annoying they are.

My only response to this is.....

STOP THREAD-JACKING.

**Comment by Jammo2000** [comment]
It's not thread jacking, he's just making a point.

**Comment by Kyllingene** [comment]
The point was not discussing the banning of water extractors, but that banning things just because they are annoying is iffy logic.

**Comment by RedstonerKBC** [comment]
I don't what thread jacking is. I'm guessing it either means changing the thread's topic or posting my own suggestion in someone else's thread instead of making my own thread?

Either way, that wasn't my intention and I'm sorry for the confusion. Like they said I was just making a point. I don't like water extractors or router highways but to me it doesn't make sense to ban either of them simply because they're annoying. It's just another one of those things like griefing that there's no easy solution to other than educating people not to misuse the tools they're given.

**Comment by sample-text-here** [comment]
noobs arent going to learn if you dont teach them

so read up (click the tabs to open them)
<details><summary>1. throughput is not speed</summary><img src="https://user-images.githubusercontent.com/56274831/103960407-ef37d780-5106-11eb-9b98-922c9b144f6f.png" />


after testing, i found that there is almost no difference in how fast the containers fill up and that "router highways" are useless.

routers are fast, but routerchains can passback and destroy speed, so its logical to assume that adding things that prevent passback e.g. titanium conveyors, will help fix it. 

<img src="https://user-images.githubusercontent.com/56274831/103960821-eeec0c00-5107-11eb-920b-882d67e7ef92.png" />

when an item enters the router, it travels faster. but then eventually the item will have to travel through a titanium conveyor, which will slow it down. building these have the same effect as a bunch of standard titanium conveyors. there is only one benefit: speed. speed it **not** throughput. items on the routered titanium belt speed up
</details><details><summary>2. slowing down</summary>
<img src="https://user-images.githubusercontent.com/56274831/103960642-771de180-5107-11eb-9196-4c4748d45459.png" />

in this example, plastanium is moving at 11 items/sec through the titanium belt. but then it reaches the normal conveyor and slows down to 4.1 items/sec. but because of that slowdown, the throughput is still destroyed.
</details>
<details><summary>3. belt mixing</summary>
another reason why router highways should die are because they  will make your item belts mix and become messier
<img src="https://user-images.githubusercontent.com/56274831/103961145-b567d080-5108-11eb-9c87-c4f709635914.png" />
this is an example of belt mixing. it isnt just aesthetics. it can make it much harder to filter out items. on multiplayer it will clog belts unless the core burning items rule is enabled
</details><details><summary>4. then what</summary>
junctions are heavily nerfed, but they still can *almost* provide a decent 4:3 compression ratio
<img src="https://user-images.githubusercontent.com/56274831/103962827-ae42c180-510c-11eb-9957-faff176c900f.png" />

they only cost copper, and have an internal storage buffer. early game, the're very useful
<img src="https://user-images.githubusercontent.com/56274831/103963222-91f35480-510d-11eb-9490-ecf5d31ad21d.png">

the 4:3 ratio i mentioned can become ~10:3 with normal conveyors! use junctions instead. 

later in the game, plastanium belts are great, especially with the new belt unloading feature. even later, you get mass drivers and phase conveyors

just please, dont use router highways.
</details>

so there. that's why router highways suck.

**Comment by Legomonster33** [comment]
> They're very efficient at destroy brain cells (if you still have them). 1. There is no actual benefits using them. 2. There no way you can cross them. 3. They take up a large space. All in all they should be broken. Just because it's just most effective at being an eyesore than anything else.

They have benefits but you seem to be far too closed minded to see them

**Comment by Kyllingene** [comment]
> They're very efficient at destroy brain cells (if you still have them). 1. There is no actual benefits using them. 2. There no way you can cross them. 3. They take up a large space. All in all they should be broken. Just because it's just most effective at being an eyesore than anything else.

Ok, so they're an eyesore. Since that shouldn't be an issue on singleplayer/custom games, I have to assume you mean in multiplayer. Well, my good friend, here is the solution: ***replace the highway with something better***. Not hard. Assuming they don't build it snaking around the map, it shouldn't take long. And if they do, you have bigger problems from that player. That way, you don't have to break certain (poorly designed but harmless) schems just so you don't have to look at a sub-optimal arrangement of conveyors and routers.

**Comment by itcannotbe** [comment]
> noobs arent going to learn if you dont teach them
> 
> so read up (click the tabs to open them)
> 1. throughput is not speed
> ![](https://user-images.githubusercontent.com/56274831/103960407-ef37d780-5106-11eb-9b98-922c9b144f6f.png)
> 
> after testing, i found that there is almost no difference in how fast the containers fill up and that "router highways" are useless.
> 
> routers are fast, but routerchains can passback and destroy speed, so its logical to assume that adding things that prevent passback e.g. titanium conveyors, will help fix it.
> ![](https://user-images.githubusercontent.com/56274831/103960821-eeec0c00-5107-11eb-920b-882d67e7ef92.png)
> 
> when an item enters the router, it travels faster. but then eventually the item will have to travel through a titanium conveyor, which will slow it down. building these have the same effect as a bunch of standard titanium conveyors. there is only one benefit: speed. speed it **not** throughput. imagine a system where you can transfer 1000 items a second, but it takes 10 minutes for the first item to reach the core. (low speed, high throughput). or some machine that instantly teleports items into the core, but only one every 10 seconds (high speed, low throughput)
> 2. slowing down
> ![](https://user-images.githubusercontent.com/56274831/103960642-771de180-5107-11eb-9196-4c4748d45459.png)
> 
> in this example, plastanium is moving at 11 items/sec through the titanium belt. but then it reaches the normal conveyor and slows down to 4.1 items/sec. but because of that slowdown, the throughput is still destroyed.
> 3. belt mixing
> another reason why router highways should die are because they will make your item belts mix and become messier ![](https://user-images.githubusercontent.com/56274831/103961145-b567d080-5108-11eb-9c87-c4f709635914.png) this is an example of belt mixing. it isnt just aesthetics. it can make it much harder to filter out items. on multiplayer it will clog belts unless the core burning items rule is enabled
> 4. then what
> junctions are heavily nerfed, but they still can *almost* provide a decent 4:3 compression ratio ![](https://user-images.githubusercontent.com/56274831/103962827-ae42c180-510c-11eb-9957-faff176c900f.png)
> 
> they only cost copper, and have an internal storage buffer. early game, the're very useful
> ![](https://user-images.githubusercontent.com/56274831/103963222-91f35480-510d-11eb-9490-ecf5d31ad21d.png)
> 
> the 4:3 ratio i mentioned can become ~10:3 with normal conveyors! use junctions instead.
> 
> later in the game, plastanium belts are great, especially with the new belt unloading feature. even later, you get mass drivers and phase conveyors
> 
> just please, dont use router highways.
> 
> so there. that's why router highways suck.

Nice explanation. I hope people notice this.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1714#issuecomment-756489422

Nice explanation. I do hope people notice this.

**Comment by Jammo2000** [comment]
Router highways don't have more throughput than titanium bands of the same
size, what they do is make it easy to use all of the throughput, instead of
partially using all your titanium belts and having to add more.

**Comment by Kyllingene** [comment]
So what you're saying is that because you already have a large track that splits up resources, you don't need to add more lines? But to negate that you literally just place the titanium lines where there used to be highway, and bam, you have more efficient transport.

**Comment by Jammo2000** [comment]
What I'm saying is that router highways allow you to use throughput that
would be wasted if you just used conveyors.

**Comment by sample-text-here** [comment]
router highways

<h1> <b><i>do not</i></b> </h1>

increase throughput

**Comment by ThatOneBepis** [comment]
One does not simply

increase throughput trough routers

**Comment by Legomonster33** [comment]
> router highways
> 
> # do not
> increase throughput

Correct

They are not meant to
# increase throughput

**Comment by Jammo2000** [comment]
In a typical scenario with a band of titanium belts, one for each resource,
you'll use like 15 belts, but you won't usually be using the full capacity
of each of those belts. Router highway helps use less space by
automatically consolidating belts.

**Comment by GreyMario** [comment]
that is literally incorrect and you should be saturating your belts at the source, not the destination

**Comment by GreyMario** [comment]
also, this thread is stupid and should have been locked after literally the first post.

**Comment by BlueWolf3682** [comment]
jesus mario stop being aggressively toxic

**Comment by Jammo2000** [comment]
He's probably right, this should be locked.

**Comment by Kyllingene** [comment]
> jesus mario stop being aggressively toxic

Agreed.

> He's probably right, this should be locked.

Also agreed.

**Comment by sample-text-here** [comment]
> They are not meant to
> 
> increase throughput

ok so then they're pointless

**Comment by Jammo2000** [comment]
Their function is to make it really easy to saturate the highway, allowing
you to use space more efficiently. This does lead to more throughput, but
it's not their number one goal.

**Comment by sample-text-here** [comment]
it does not use space more efficiently

**Comment by Kyllingene** [comment]
> Their function is to make it really easy to saturate the highway, allowing
you to use space more efficiently.

If you put 20 items/second, then there will *always* be 20 items/second or less. You will not get any benefits by having 4 tracks each carrying 5 items a second (and swapping around) that you will not get from 1 track carrying all 20.

**Comment by Legomonster33** [comment]
> it does not use space more efficiently

Yes it does
If you have 6 half belts you are using the same space as 3 full belts

**Comment by sample-text-here** [comment]
> If you have 6 half belts you are using the 2x the space as 3 full belts

what's a half and full belt?

<details><summary>also, they dont use space more efficiently</summary>

![image](https://user-images.githubusercontent.com/56274831/104366110-b9f80480-54cd-11eb-9005-acf3b8dc12ba.png)

if you read https://github.com/Anuken/Mindustry-Suggestions/issues/1714#issuecomment-756489422, you would know that they dont have more throughput. but did you know that throughput affects space efficiency? in the image above, they both have the same throughput. in the same amount of space, you could replace router "highways" with normal titanium belts. the same items/sec in the same space. that means they have the same space efficiency. 

if they have the same space efficiency, then why use titanium belts? titanium belts avoid belt mixing, which is a big problem in multiplayer. also they don't "leak" items to the sides if there are factories nearby. in singleplayer, do what you want, excess items in mixed belts will be incinerated anyway. in multiplayer, the server would have to enable core burning excess items. not many servers i know enabled this. also, mixing belts will make your base more messy, and make it harder to build factories based off of a main, sorted, highway. (also mixed belts look worse)
</details>

**Comment by Jammo2000** [comment]
Your throughput measuring device does not accurately reflect real
situations. Try using actual drills. Router highways are only useful when
your inputs vary in throughput.

**Comment by itcannotbe** [comment]
When do drills even vary their outputs?

**Comment by Jammo2000** [comment]
They don't, I was talking about differences between inputs, not variation
within a single input.

**Comment by Kyllingene** [comment]
Ok, technically, if you have enough copper to fill half a lane and enough titanium to fill a lane and a half, you would require 3 lanes of normal conveyors compared to only 2 lanes of router highway. However, you can manually mix the titanium and copper anyway, making the router highway useless. Example pic included.
![norouterhighway](https://user-images.githubusercontent.com/69094702/104385169-9641b800-54e7-11eb-8afd-b5f24f51b474.png)
Note: I realize that technically the third example is different in the fact that it has a slightly different rate limiting setup. The difference is literally nonexistant in the results (item voids have no incinerate speed limit), I just did it differently for some reason.

**Comment by Jammo2000** [comment]
However, as you progress in the game and get more resources, manually
mixing belts gets more difficult.

**Comment by itcannotbe** [comment]
Mixing belts is stupid in the mid to late game.

The logistics of actually pulling resources out of a mixed belt, let alone multiple belts is horrendous.

**Comment by sample-text-here** [comment]
first, mixing belts is not a good idea

but if you want to mix belts for whatever reason, just use a single router/overflow/underflow, don't put them everywhere.

but the best option imo is bridge weaving:
1. 4x the throughput of a titanium conveyors (tons of throughput, most space efficient)
2. can hold 4 different items with different types without mixing
3. cheap (a good, maybe best, option for early game)
4. looks better than router highways
5. extremely easy to set up with the new bridge dragging feature

![image](https://user-images.githubusercontent.com/56274831/104392477-f724bc80-54f6-11eb-9c52-97b4d206cbf8.png)

**Comment by Jammo2000** [comment]
This should be closed. Maybe discuss more on discord?

**Comment by itcannotbe** [comment]
This is right venue to discuss this.

And if we were to discuss this on discord, this discussion get shallowed by random banter/unintelligible responses.

**Comment by Jammo2000** [comment]
I thought we had reached the conclusion that router highways are bad but
they shouldn't be banned. Am I missing something? If we have answered the
ban question, this isn't the place to continue bashing highways.

**Comment by Kyllingene** [comment]
> If we have answered the
ban question, this isn't the place to continue bashing highways.

I do believe the ban question was being disputed on the grounds that it is the best tool for the job in certain circumstances. Therefore, bashing highways was part of the dispute. But anyways, I agree in the fact that I saw no real opposition to the ban, especially not from DeltaNedas. The only opposition I saw was answered by itcannotbe and sample-text-here.

**Comment by BlueWolf3682** [comment]
my only issue is that you just cannot without breaking something in the basegame. and breaking the basegame is large bad.

**Comment by ThatOneBepis** [comment]
Then make something that doesn't cause eyerape be appealing enough to replace it.
Or develop a bunch of code for that one specific case

**Comment by BlueWolf3682** [comment]
> my only issue is that you just cannot without breaking something in the basegame. and breaking the basegame is large bad.

**Comment by BlueWolf3682** [comment]
ill pause here to take a moment to mention: because of how mindustry is coded and how it works, there are NO current methods of stopping this from happening without ruining a different aspect of the game. period. that is probably the reason why deltanedas made a suggestion issue instead of a pr. (other may be that hes lazy)

feel free to try this for yourself, you will fail.
