### ISSUE TITLE
QOL | Current date & time as the default name for save export

### ISSUE THREAD

**Issue by lorenuars19** [Anuken/Mindustry-Suggestions#1715]
**Describe what you would like changed, and why.**
When exporting game save for playing on another device, I have to enter a name manually each time.
Adding a QOL update that has the current time & date as the default file name, when exporting saves.

**Describe the changes you want to propose. Include possible alternatives.**
Having probably a setting allowing to change the format of the default file name for exporting saves, maybe using java string formatting convention.

**Comment by Kyllingene** [comment]
Did Github glitch, or did you delete the handy boxes?

**Comment by lorenuars19** [comment]
There was no handy boxes in the issue template

**Comment by Kyllingene** [comment]
Sorry, forgot the difference between feature request and feedback. My bad!

**Comment by lorenuars19** [comment]
no prob
