### ISSUE TITLE
Steam Generator Build Cost Rebalancing.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#1717]
**Describe what you would like changed, and why.**
Title. To promote making metaglass and by extension using liquid transport items.

**Describe the changes you want to propose. Include possible alternatives.**
Alternative 1: Add Metaglass.
Alternative 2: Replace Silicon with Metaglass

**Comment by BlueWolf3682** [comment]
oh thats the thing you did

**Comment by Bohaska** [comment]
Answer: Do it yourself. This type of suggestion is so easy to implement, almost anyone can do it.

**Comment by Kyllingene** [comment]
How much metaglass would you like to be added to the recipe?
Here is the line to edit ([in this file](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/Blocks.java#L1315)):

```requirements(Category.production, with(Items.copper, 25, Items.graphite, 25, Items.lead, 20));```
Change it to:
```requirements(Category.production, with(Items.copper, 25, Items.graphite, 25, Items.lead, 20, Items.metaglass, <Metaglass Cost>));```

Bonus: You become a contributor (if it makes it in)!

**Comment by itcannotbe** [comment]
Contributor Role goes brrrrrrr.
It's such a simple change it's not even pr worthy.

**Comment by Kyllingene** [comment]
Ok then, I can make a pr for that... it is literally just saving Anuke time. Not much, but yes, time.

**Comment by BlueWolf3682** [comment]
anuke doesnt accept balance prs.

**Comment by Kyllingene** [comment]
Ah, ok, I didn't know (never contributed, new to the Github). Sorry!

**Comment by catatagun** [comment]
Well what if you cant code

**Comment by Kyllingene** [comment]
If you can't code (or possibly sprite), you can't help in any truly large way. If you cannot help in any large way, you don't deserve to be called a contributor. There are other ways to help, it just happens that the main one is an uncommon one for people to know how.

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
