### ISSUE TITLE
spawn units and resource

### ISSUE THREAD

**Issue by skvventus** [Anuken/Mindustry-Suggestions#1718]
**Describe what you would like changed, and why.**

in the editor,theres no way of adding a unit other than S enemy spawnzone (without factory) as well as resources in something
for example,a enemy core spawning with resource inside or turrets spawned with ammo and the enemy base with a mega(without spawning it using factory or enemy spawn landing zone)

**Describe the changes you want to propose. Include possible alternatives.**
maybe add a button to add resources to players when using "In game-editor" and add a menu to spawn units in the editor

**Comment by itcannotbe** [comment]
That was a thing that actually got remived because spawning units that way were buggy.

**Comment by RenanJooj** [comment]
sorry

**Comment by DeltaNedas** [comment]
possible with mods

**Comment by skvventus** [comment]
so do i close this

**Comment by Kyllingene** [comment]
probably
