### ISSUE TITLE
the AI of an enemy Poly

### ISSUE THREAD

**Issue by skvventus** [Anuken/Mindustry-Suggestions#1719]
**Describe the content or mechanics you are proposing.**
when we have the poly,it fly around randomly and rebuild stuff,but when an enemy (attack map)when have a Poly instead of hanging around the base and rebuild destroyed structures,it just fly straight to your base and die

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
maybe add a toggle or litterally make it the same AI as when a player haves it

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
1: agreed, this is a problem
2: Adding the other 3 boxes (click "Edit" above the post) increases the likelihood of your suggestion getting added.
> Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

**Comment by bsjohnson20** [comment]
Well polys also like to rebuild stuff in front of multiple T4 units and just when getting built just goes back to rebuild It in endless resource waste and suicide by polys.
