### ISSUE TITLE
Buffing Spectre's

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#172]
**Describe what you would like changed, and why.**
One of the problems with Spectre's right now, is that in almost any scenario, a Cyclone would be better. Spectre's lack area damage which makes them only good against single targets, and even then, a meltdown will normally perform better. My idea would be to add area damage to spectre's in some way either that be more ammo types or just adding it to existing ammo types. Or even better, making it have spread out shots similar to the Eradicator does, which would be a great improvement

**Describe the changes you want to propose. Include possible alternatives.**
I think that spectre's should not accept plastanium to avoid being too overpowered, but instead they should accept blast compound and have high area damage on blast compound which would be lower then the damage on thorium, like having 10 damage, but then having something around 30-40 area damage. The other possible idea would be to add in area damage to it's existing ammo types like thorium (which it accepts uniquely), which would also be made more interesting by making it actually explode or something.

My other idea would be to make it have multishots that are partially spread out, similar to eradicator. It's raw DPS when shooting is currently lower then a meltdown, with spectre DPS being 650, and meltdown being 840 (thought spectre lacks chargeup), but it is a disadvantage to spectre because it requires ammo, and it also doesn't penetrate through multiple targets and hits everything. I think that each shot of a spectre cannon should fire out multiple partially spread out shots, similar to Eradicator, or at least have higher actual DPS then a Meltdown, which would make them more practical to use for any scenario rather then just going with Meltdown, which is generally the cheaper option to Spectre and is currently way more powerful.

**Comment by itcannotbe** [comment]
Actually the dev is considering adding an armor of sorts on laterr game units that significantly reduces the damage of low damage turrets.

**Comment by Syncinus** [comment]
That would kind of help, though Spectre and Cyclone already do similar damage in general because Cyclone just deals it in area damage, and Spectre is still decently good of a turret, it's just terrible compared to other turrets you could get when you are able to obtain it. Again, the biggest problem with Spectre is meltdown has much more DPS, in a large area, which pierces, and meltdown can be considered less expensive then Spectre as well as it having more health. I think Spectre's bullets should have more damage if it's going to stay as single target though, like doing 120 damage for a thorium bullet or something (or doing more shots like Eradicator as I proposed). Spectre should be at least 1000DPS if it doesn't do any area damage.

**Comment by Anuken** [comment]
Buffed a while back.
