### ISSUE TITLE
More detail about Mindustry and the development process

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1721]
**Describe the content or mechanics you are proposing.**
I think that the README.md file should have several new things
Firstly, the file should state what is Mindustry, as in the type of game it is, the developer of the game and what the developer of the game wants Mindustry to become
Secondly, there should be a review of Mindustry every year. In this review, the developer of the game will look at the game and study the changes of the game throughout the year and how they correlate to the amount of users that downloaded Mindustry to create a graph in which the developer projects the amount of users gained next year. In the next year, the developer will look back on the projected amount of users vs the actual amount of users to further refine next year's projection.
Lastly, the developer will also study the ratio of people that downloaded the game: people that bought the game and the ratio of people that downloaded the game: amount of money earned to extrapolate future earnings if the projection of the amount of users is correct

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

More transparency is always good.

**Before making this issue, place an `X` in the boxes below.** *Failure to do so may result in your request having a bunch of angry people in the comments.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
but why

**Comment by Kyllingene** [comment]
Wait, how do those things fit in this README.md? Mindustrys, MAYBE, but it already has a website and a Steam store page. Also, how much money Anuke makes on his *optionally free* game should not need to be our concern if he does not wish it. Also, this is a fair bit of work for Anuke to do for some info for us to use for... what exactly? Seriously, I think that you might just not want to look at the website, because honestly, "who the dev is" is such an easy question to find out. For goodness' sake, *it's in the official repo*, ***linked to in this README.md!*** This repo is not a website for people interested in Mindustry (that would be [this](https://mindustrygame.github.io/)), nor a place for Anuke to tell us all his secrets.

**Comment by itcannotbe** [comment]
My take: 🤢🤢🤢🤮🤮🤮🤮🤮🤮🤮

**Comment by Bohaska** [comment]
I like eggs

**Comment by joshuaptfan** [comment]
This game already has one of the most transparent development processes that I've ever seen, and you want more? We can browse the source code, submit changes ourselves, and talk directly to the dev to influence the direction of the game.

Projections? Correlate? Extrapolate? Future earnings? To determine what? Whether or not to add cosmetic microtransactions, or whatever other predatory BS MBAs have been using to squeeze gamers like a dying oil well?

**Comment by Bohaska** [comment]
I prefer chocolate ice cream though

**Comment by DeltaNedas** [comment]
die

**Comment by Kyllingene** [comment]
Unnecessary much?

**Comment by catatagun** [comment]
Anuke need money so he can make mindustry update faster

**Comment by Kyllingene** [comment]
But this doesn't help him earn money, unless it helps him to figure out

> Whether or not to add cosmetic microtransactions, or whatever other predatory barely legal BS MBAs have been coming up with to squeeze gamers like a dying oil well?

The worst part about that is that if he did add those things, he would have to make at least part of the game no longer open-source, thus defeating the purpose of this issue.

**Comment by Bohaska** [comment]
Now shut up please

**Comment by Bohaska** [comment]
Almost forgot my favourite flavour

**Comment by BlueWolf3682** [comment]
...what the sweet flying fuck

**Comment by joshuaptfan** [comment]
Yeah this suggestion is deader than dead. Bohaska's ego is on the brink of collapsing into a black hole.

**Comment by BlueWolf3682** [comment]
commence yeet the human

**Comment by Kyllingene** [comment]
Unnecessary toxicity: check;
Unnecessary toxicity on a *closed issue*: check;
Unnecessary toxicity on a *closed issue* that brings nothing new to the table: check;

**Comment by itcannotbe** [comment]
> Unnecessary toxicity: check;
> Unnecessary toxicity on a _closed issue_: check;
> Unnecessary toxicity on a _closed issue_ that brings nothing new to the table: check;

Unnecessary title change: Check.

**Comment by Bohaska** [comment]
i closed this issue why the heck do you care about this issue

**Comment by Bohaska** [comment]
I WANT it left dead

**Comment by Bohaska** [comment]
> this suggestion is deader than dead. 

That's good. This suggestion was a bad suggestion, so I closed it but stop pestering me about how bad it was.

**Comment by Kyllingene** [comment]
> > Unnecessary toxicity: check;
> > Unnecessary toxicity on a _closed issue_: check;
> > Unnecessary toxicity on a _closed issue_ that brings nothing new to the table: check;
> 
> Unnecessary title change: Check.

Lack of explanation for said toxicity: check;

And for your sake Bohaska, on the right towards the top you should be able to unsub from the discussion.
