### ISSUE TITLE
Liquid routers being controlled by logic

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#1722]
**Describe the content or mechanics you are proposing.**
Allow liquid routers to be controlled by logic. You can control the minimum and maximum amount of liquid outputted to each side.
<img width="209" alt="Screen Shot 2021-01-04 at 10 17 20 AM" src="https://user-images.githubusercontent.com/73286691/103495678-95b97980-4e76-11eb-977d-84072b8408d4.png">

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Increase efficiency of schemes using water and more fine tuning.

**Defeat the boxes by putting X's in them!*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You have been defeated.

> Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

**Comment by Bohaska** [comment]
> You have been defeated.
> 
> > Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

Isn't using logic to control sorters "additional configuration of blocks"?

**Comment by Ruichka** [comment]
Sorters control is something that you can do manually already for a long time. Logic is just a way to automatize that process. Also, the thing you suggested can be done by disabling/enabling pipes.

**Comment by Yell245** [comment]
PWM exists. It's when you turn things on-off with n frequency so it'll be slightly turned on, like slightly lit LED

**Comment by itcannotbe** [comment]
Is this talk still about the op's topic or a thread on how to distribute liquids with logic with the help.of conduits?

**Comment by BlueWolf3682** [comment]
too much of a griefing tool. you can just bind routers and freeze them in place.
