### ISSUE TITLE
About Swarmer 

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#1724]
**Describe what you would like changed, and why.**
Swarmer is a little unbalanced, i mean, literally no one use it

**Describe the changes you want to propose. Include possible alternatives.**

1.Allow swarmer use silicon as ammo(swarmer only use expensive ammos
2. Longer range like 25-28 blocks (so players will use it

**Comment by itcannotbe** [comment]
Making Swarmers use silicon is crazy talk.

**Comment by catatagun** [comment]
> **Describe what you would like changed, and why.**
> Swarmer is a little unbalanced, i mean, literally no one use it
> 
> **Describe the changes you want to propose. Include possible alternatives.**
> 
> 1.Allow swarmer use silicon as ammo(swarmer only use expensive ammos
> 2. Longer range like 25-28 blocks (so players will use it

Yes cuz sili desc is used for homing ammo and stuff make it so if it use sili ammo it is weak

**Comment by Bohaska** [comment]
I'm gonna try to implement this suggestion

**Comment by userlol2** [comment]
> I'm gonna try to implement this suggestion

How

**Comment by Humanoid-X** [comment]
pr exist

**Comment by Kyllingene** [comment]
Does this qualify as a balance change? If so, then I would like to inform you that Anuke does not accept balance changes (thank you joshuaptfan for letting me know).

**Comment by userlol2** [comment]
Bruh

**Comment by Bohaska** [comment]
Never mind I don't want to implement this cuz I'm lazy

**Comment by notrealn** [comment]
my problem with swarmers is that they just eat all your ammo. ive tried to defend sectors with only swarmers/lancers before, and every time they use up all the ammo. A full titanium line of pyratite gets used up by only 3 swarmers, but a full line of blast can fuel 7 cyclones.

**Comment by GreyMario** [comment]
Sorry, what? Do you people have Cyclones and Swarmers switched around?
