### ISSUE TITLE
Mobile; stretching conveyors control issues

### ISSUE THREAD

**Issue by AhaWarrior1** [Anuken/Mindustry-Suggestions#1725]
A special button on mobile that enters you into conveyor stretching mode. Not sure if this is already a thing, but it just wont work for me. I can stretch a converyor after like 5 minutes of trying to do so, as controls for that are funky on mobile. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [xve read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
What do you mean by "stretching a conveyor" ?
