### ISSUE TITLE
conveyor upgrade button

### ISSUE THREAD

**Issue by TurtlZ247** [Anuken/Mindustry-Suggestions#1728]
add a conveyor upgrade button. This button replace conveyor to titanium conveyor.
it's a quality life upgrade)

**Comment by itcannotbe** [comment]
You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by joshuaptfan** [comment]
[We already have a conveyor upgrade system.](Anuken/Mindustry/pull/3912)

**Comment by RedstonerKBC** [comment]
Why do regular conveyors even exist again? Even shockmine have more uses than regular conveyors.

**Comment by itcannotbe** [comment]
Because can't make titanium conveyors the very start.

Also shock mines don't get used pretty often because it requires silicon and is frankly misunderstood but this isn't the right place to discuss that.

**Comment by Legomonster33** [comment]
> Because can't make titanium conveyors the very start. Also shock mines don't get used pretty often because it requires silicon and is frankly misunderstood but this isn't the right place to discuss that.

shock mines main downfall is that polies dont auto, rebuild them.
(not the place idc)
