### ISSUE TITLE
Larger scale version of a flamethrower turret

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#173]
**Describe the content or mechanics you are proposing.**
One of the most interesting turrets in the game is probably the Scorch, it has a high firerate and is the only flamethrower turret in the game. The thing is that unlike the other two low end turrets, it lacks a higher end counterpart (Duo -> Salvo, Hail -> Ripple). I think that a larger (presumably 3x3) flamethrower turret should be implemented. It would take in coal and pyratite (similar to the Scorch), and basically be a larger, more powerful version of the Scorch with a longer range, and with the same flame capability of Scorch, but better.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think one of the aspects that would make this interesting is a better structure destruction turret. Ideally this turret would deal relatively high continual damage and light stuff on fire, and the ammo is also decently cheap. I think a turret like that would be interesting for a lot of PvP maps as well as attack.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
The idea of the scorches low range is so that it isn't suddenly end-game meta that vaporizes 500 erads.  Scorches are already really really high damage, easily enough to kill erads. Several players actually use them in their end game defenses. The problem with upgrading them is that it would make the turret extremely broken.

**Comment by Syncinus** [comment]
Are you sure their that powerful?

**Comment by potatoisagender** [comment]
Yes. If you cryo overdrive them, they melt everything. base dmg of 108 dmg per second.

**Comment by Syncinus** [comment]
Their very impractical due to total lack of range.

**Comment by Syncinus** [comment]
Dead suggestion
