### ISSUE TITLE
Wireless data transmission between processors and possibly between sectors

### ISSUE THREAD

**Issue by Alex-Hoeft** [Anuken/Mindustry-Suggestions#1731]
### **Describe the content or mechanics you are proposing.**
As the title says. While this is vaguely similar to #684 I think the implementation is different enough to warrant discussion.
I propose the addition of two more blocks, a 2x2 radio tower requiring power and a 1x1 antenna that doesn't. It doesn't require any addition to the logic system to make it work. Normal read and write operations work just as they do now.

**Radio Tower** 
The radio tower would essentially function as a memory cell shared between processors connected to radio towers. This would mean 64 different "broadcast frequencies" to be used. Though this could be limited to, say 16 if we think 64 is to many. These values are read/write on radio towers. These memory slots could be read by processors connected to antennas on the same sector or by processors connected to radio towers on different sectors on the same planet. A radio tower would "rebroadcast" all the data from other sectors in the sector it is built in. Meaning that antennas are only useful when there is a radio tower on the map. Has a blinking red light on top to tell when it is operating. Requires power to function and has essentially unlimited range on a given planet. All values being sent from a given tower are reset to zero if the tower loses power or is destroyed. Bonus: could be used to communicate with satellites if/when those get added (though I don't think I saw them on trello anymore?). I have other satellite ideas that I'll probably make another post about later.

**Antenna**
This would only be able to read the state of the broadcast memory cell values. Optionally I think it would be neat to be able to receive data values from other allied player in multiplayer by having the processor be able  to configure the player to receive from but this isn't a big priority for this idea. Bonus: If there sprites have little yagi's that always point at the closest radio tower on the map.

**Other Possible Variations**
These are some other ideas that may address some concerns or provide functionality in a different way.
- Rather that having radio towers communicate between all sectors have a third block added that is an uplink block. It connects to another uplink block in another sector. It only connects to one sector at a time, similar to a launch pad. Though unlike launchpads where all of them in a given sector launch to the same destination, multiple uplinks on the same sector would be able to connect to different sectors. 
- Some sort of message block functionality in addition to the memory cells to easily send text over radio. Might be more useful with the multiplayer stuff. Not quite sure how this would work. I suppose it would work the same way as message blocks do.

### **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will provide the ability to send data around the sector and around the planet.

**Possible Uses In A Sector**
- Initiate "Attack Mode" for all sections of a base when an enemy is detected at the first one or when a switch is flipped.
- Report the position of a particular enemy or boss back to base to command all units to attack it. Allowing the unit control processor to be in a different location from the unit being attacked
- Remote request for more resources from storage
- Remote start of a resource creation system when a resource is low
- Notify the player of things in other locations e.g. a display at the core that shows the status of reactors elsewhere or ammo amounts elsewhere.
- Once logic sound is added players could make radio stations that play music. This wouldn't be useful but it would be pretty neat.
- I'm sure more stuff I haven't though of

**Possible Uses Between Sectors**
- Request specific resources be sent via launchpad on command
- Create a global dashboard of what resources are where
- Overall automation of resource management across sectors
- Heartbeat to see if specific sections of a sector are destroyed.
- Commands to or information from future satellites
- Players could program TDMA or CDMA transmission schemes to save bandwidth or have different command groups on one memory slot.
- Also probably more cool stuff I haven't thought of

This essentially provides parity for data as a resource that can be utilized across a sector and exported to other sectors. It doesn't require many changes to existing systems like logic. It could be used alongside some sort of hardware data transmission line like #684 proposes but it doesn't require them nor make them useless.

I would love to hear everyone's thoughts on this.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
But only one sector is running at a time........

I don't see the use case at all for cross sector data Tx Rx

Also #684 is a suggestion for long range data relay.

**Comment by Alex-Hoeft** [comment]
Resources are still passively exported from other sectors via launchpads even when you don't visit them and resources are still produced there. The other sectors are not fully running, but things are still happening. Waves are calculated differently and resource production may be calculated differently as well. If I set up some units, via logic block, to carry resources from one place on the map to factory with no conveyor that factory will still produce things when I'm not there. Requesting specific resources be sent or knowing how many resources a given sector has can automate the sending via so that you don't send resources to a sector that is full (thus losing the extra) or you only send to a sector that needs that resource and requested it. The main use case is automating things like that. Right now that is information that you have no way to programmatically access and if you want to change those things you, the player need assess the information to do it manually at each sector that has a launchpad. Though I do agree somewhat in that it has less usefulness than using it inside a given sector. It may not be worth it. I don't know.

**Comment by DeltaNedas** [comment]
in order to run logic processors youd have to load other sectors which can't happen.

**Comment by Yell245** [comment]
You already can make logic wires - processor which is reading variables from one memory cell and writing it to another

**Comment by mockwriter7772** [comment]
Still not a bad idea
It sounds cool

**Comment by Alex-Hoeft** [comment]
@DeltaNedas I guess I assumed that some processing was still happening since factories that depend on a processor controlling units still happen while it is not loaded. I wasn't really sure how that happened and what went into that calculation and I just assumed that some things like this could be added to the calculations for dormant sectors without loading them, my mistake. Hopefully the rest of the idea still stands up to scrutiny. 

@Yell245
I guess I was just thinking we could treat data like we do items and have different tiers that can move them over longer distances rather than settle for short, expensive hops or rig something up like bit banging I2C protocol over two isolated power lines with battery diodes (though that would be pretty cool, someone should attempt this, we could theoretically get like 100kbits/s data rate).

**Comment by Humanoid-X** [comment]
Imagine running MORE THAN 200 MAPS at the same time in V5

**Comment by Kyllingene** [comment]
If processors don't process in unloaded sectors, this idea is good but only the on-sector part. If they do, you can use some launchpad finnicky stuff to transmit data based on amounts of an item sent via launchpad. Again though, I like the on-sector part.

**Comment by sample-text-here** [comment]
> ...and possibly between sectors

that would be useless. 

> If I set up some units, via logic block, ... still produce things when I'm not there.

thats because of how its calculated. when an [item enters the core](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/entities/comp/BuildingComp.java#L673-L675) it updates the [production stats](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/game/SectorInfo.java#L93-L97). then, when its [updated](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/game/SectorInfo.java#L201) it does the [thing](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/game/SectorInfo.java#L208-L220) which lets the [other thing](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/type/Sector.java#L90-L92) do [another thing](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/game/Universe.java#L190) and dukfhgidugh  gfuydnyuscny  ksiuindr du buyseygf suyg yf and there.

its not actually doing anything, it just precalculates how many items are traveling where and how fast.

and im not 100% sure but i think that's why the [launchpad](https://github.com/Anuken/Mindustry/blob/4c2f330e511284d24cd7d6c5480aacc5eb09ca91/core/src/mindustry/world/blocks/campaign/LaunchPad.java#L73-L77) cant be disabled

but anyway, because your computer isnt running/simulating multiple worlds at once (that would be awful for performance), sending logic to another sector would be useless because it doesnt update

**Comment by Legomonster33** [comment]
> Resources are still passively exported from other sectors via launchpads even when you don't visit them and resources are still produced there. The other sectors are not fully running, but things are still happening. Waves are calculated differently and resource production may be calculated differently as well. If I set up some units, via logic block, to carry resources from one place on the map to factory with no conveyor that factory will still produce things when I'm not there. Requesting specific resources be sent or knowing how many resources a given sector has can automate the sending via so that you don't send resources to a sector that is full (thus losing the extra) or you only send to a sector that needs that resource and requested it. The main use case is automating things like that. Right now that is information that you have no way to programmatically access and if you want to change those things you, the player need assess the information to do it manually at each sector that has a launchpad. Though I do agree somewhat in that it has less usefulness than using it inside a given sector. It may not be worth it. I don't know.

sectors dont run *at all* while your not in them, numbers are calculated while your in the sector and then those numbers are used to calculate production values, survival time, etc.

**Comment by Alex-Hoeft** [comment]
@sample-text-here I really appreciate the detailed breakdown, thank you, I did not know exactly how this process worked.

So I don't quite know how to implement it but, do you (or anyone else I suppose) think it would be appropriate to make a separate feature request for the ability to adjust the export amounts and locations either programmatically or via menu/dashboard, such that you didn't have to go to a given sector to adjust it's exports or destinations (limited to within its production amounts obviously)? Obviously there would be issues with launchpads that aren't connected to the core because "total launch capacity" is not necessarily accessible by all resources produced if they aren't going to the core so maybe it would need to be limited to launchpads attached to the core or something. I know Anuken has "Display Total Production" on the trello board so it could be incorporated into that and/or the individual stats pages of the sectors. But my limited (and now slightly expanded thanks to you) understanding seems to indicated this would not be trivial to implement. A related suggestions is #1680 but it makes no mention of changing the exports only finding information about where things are globally produced and exported.

This would obviously be separate and unrelated to the radios I have proposed in this issue. I would love your thoughts on this.

**Comment by deltanedas** [comment]
replying to 3 year old issue real
