### ISSUE TITLE
Melee Units

### ISSUE THREAD

**Issue by TheThane** [Anuken/Mindustry-Suggestions#1732]
**Describe the content or mechanics you are proposing.**

Melee units. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

T1: Shank (2 Short blades, which look basicly like a short isosceles triangle which attack rapidly at low damage)
T2: Blade (Small- Combat-Like Knifes Blades which )
T3: Katana (Meduim rangem Slighly Curved blades which attack at a 45 degree angle Mediocre heath/defence speed like a fortess)
T4: Gugnir (Longer Range, goes in a straight line, High Health and defence, slow speed. Can Peirce, 110% more unit Damage)
T5: Excaliber (Giant Torso, Simalar body type to Reign, gains crawler legs such as Corvus Long sword like blades which attack slowly, but do very high damage output [More than Toxopid]

(There was a melee unit post, but that was before 6.0 and i will talk about the tiers)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Uhm... There are already melee units + blades are not so futuristic as the game's thematic. T2 units are melee, plus there are many other melees such as toxopids which deal more damage with their fuse turrets

**Comment by TheRealIvyX** [comment]
literally every T2 unit other than minke (very situational, only usable on maps with water) and poly (rarely ever used for attacking) has a range of under 10 blocks, does this game really need more short range units if there already are 4 units that have less range than a duo

**Comment by NajimiOsana** [comment]
Have you ever heard of "Crawler" Units?

**Comment by Kyllingene** [comment]
"Crawler" Units are not melee. They are close range, but suicide. I personally think melee units could be either underpowered or overpowered, but probably not just right.

**Comment by TheRealIvyX** [comment]
im pretty sure they meant the crawler line in general and not just crawler itself. crawler, atrax and spiroct are all short range

**Comment by Kyllingene** [comment]
But none are true "melee". They all have turrets. The Atrax has medium range turrets, the Spiroct has healing/traction beam lasers, and the Arkyid has both. After that, they don't even attempt to be close-range. Also, most of them go over blocks, which these melee units would be incapable of (except for T5).
