### ISSUE TITLE
Slightly lower difficulty if adjacent attack sector is captured

### ISSUE THREAD

**Issue by CaeciliusInHorto** [Anuken/Mindustry-Suggestions#1733]
**Describe what you would like changed, and why.**

I would like the difficulty of sectors next to attack sectors to be lowered when the attack sector is captured. Many sectors that are next to attack sectors have higher difficulty, even after the attack sector is captured. This does not make sense, because the sectors would no longer receive support from a captured base.

**Describe the changes you want to propose. Include possible alternatives.**

Have a chance for a sector next to an attack sector lose 1 or more levels of difficulty when the attack sector is captured. This might be able to work if the sector is near multiple attack sectors, with each one lowering its difficulty (ex: sector 234).

**Comment by Kyllingene** [comment]
I feel like I've seen a version of this, but since I can't find it, all I can say is that I totally agree.

**Comment by itcannotbe** [comment]
With this regard I think the opposite should happen too,

Slightly higher difficulty of the attack sector if adjacent sectors are still not captured.

**Comment by XxsuperdeadlysniperxX** [comment]
It would be a little off balanced if it were it anyway glitch (for example: a wave spawning it shouldn't Or difficulty raises when it shouldn't or other mythical rareity stuff) like not saying it will function differently but like visible changes, also it could make certain sectors impossible

**Comment by XxsuperdeadlysniperxX** [comment]
Not required sectors the optional ones

**Comment by Yell245** [comment]
> I feel like I've seen a version of this, but since I can't find it, all I can say is that I totally agree.

Well, there was a suggestion about reinforced sectors: more player sectors nearby - less difficulty of them

**Comment by Kyllingene** [comment]
Ah yes, that was the one. However, this is entirely different, so my statement still stands.
