### ISSUE TITLE
Restrict the rotation of a unit's weapons.

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry-Suggestions#1734]
**Describe what you would like changed, and why.**
Restricting the rotation of a unit's weapons functions both as a visual and balancing improvement. It also allows for more flexible units.

Certain mechs can benefit from an improved way of shooting at an angle. I find it more visually appealing for a reign's bullets to shoot properly from its weapon, rather than this awkward way:
![unknown](https://user-images.githubusercontent.com/19158169/103678436-86f3c500-4f51-11eb-835c-9ae15a4b4fc7.png)

**Describe the changes you want to propose. Include possible alternatives.**
[I have made a pull request that adds a variable to weapons that limits their relative angle from their initial rotation. This can prevent a mech's "arms" from rotating at awkward angles, or shooting from strange angles, etc.](https://github.com/Anuken/Mindustry/pull/3928)
![101992576-6c943780-3c82-11eb-8bda-2776302eb15f](https://user-images.githubusercontent.com/19158169/103678392-77747c00-4f51-11eb-9826-56c5ed62110d.png)

**Comment by DeltaNedas** [comment]
you already have a pr
why did you make this

**Comment by YellOw139** [comment]
To ask for feedback in a place that's not #pulls, for getting the opinion of a wider audience probably.

**Comment by BlueWolf3682** [comment]
the reigns still look mighty sus no matter what you do

**Comment by XxsuperdeadlysniperxX** [comment]
They look stranger with tiltable weapons in my opinion

**Comment by Yell245** [comment]
Maybe make them a limit in rotation of weapons? It looks unnatural for their weapons to cover their body

**Comment by Humanoid-X** [comment]
Imo it must automatically turn to face the direction when shooting, like V5
