### ISSUE TITLE
Allow for long-range liquid transport, like a liquid mass driver

### ISSUE THREAD

**Issue by thompson8964** [Anuken/Mindustry-Suggestions#1735]
**Describe the content or mechanics you are proposing.**

some from of long-range liquid transport, like a liquid mass driver or a liquid form of the phase conveyor

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

i know that every liquid is obtainable, but it would help in the early campaign when oil drills and water pumps are not avaible

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
#384 #197

**Comment by BlueWolf3682** [comment]
phase conduit:

**Comment by itcannotbe** [comment]
Oh... A Box. I shall put an X in it.....

The box:

-[] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Also the box:

😑

**Comment by laok233** [comment]
phase conduit exist

**Comment by joshuaptfan** [comment]
Please close this issue.

**Comment by scarf-generic** [comment]
> phase conduit exists

phase conduit also sucks
regardless, close issue when
