### ISSUE TITLE
Additional types of barrier blocks. (Terrain only)

### ISSUE THREAD

**Issue by Nekuna** [Anuken/Mindustry-Suggestions#1736]
**Describe the content or mechanics you are proposing.**

Some sort of block or tile type that can impede aerial/flying units. Something along the lines of thick volcanic ash clouds that do a lot of damage to flying units, or "taller" terrain that can block units with the ability to hover/walk over . Ideally there should be four kinds of blocks.
*Aerial only*- a block that ground units or hovering units can pass under, but air units cannot. (Pyroclastic Ash clouds make sense)
*Hovering/crawling only*- a block that air units can pass over, but units with the ability to hover or units that can bypass terrain cannot bypass. (Something like steep cliffs would work)
*All Types*- a block that no unit can pass over regardless of its type. (Possibly high elevation mountains or Volcanic ash plumes)

Let me be clear that these are only terrain options meant for the map editor. Players being able to block flying units would be ridiculously op. 

Things can be adjusted to make more sense or to just balance things out. For example, since the Volcanic ash would work more as a damage based barrier instead of an impassible barrier, depending on the thickness of an Ash cloud it would be possible for higher tier units like the Antumbra or Eclipse to tank the damage and get through. The same can be said for other terrain, but I'll leave it at that. 

(And because I'm sure it will come up, I don't know about bridges. There are multiple way to go about them, but this is more about an new option for maps to balance units, not bridges. So I won't be addressing them. If you're asking why I don't suggest "jUsT NeRfinG ThE uNiTs" its because I'm not the person to make that call, and it would drastically change an element for everyone, instead of being an optional tool for map creators to utilize without altering the core mechanic of another feature [hovering]. )

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

For one, these types of terrain would allow for map makers to balance the functionality, improve on lore, and enhance the gameplay of a map. In PvP, units such as quasars are being overused since they can bypass all terrain and defense of another player. This problem can be solved by having the map maker of a map choose whether or not they want to keep certain units from being overused. 
I often hear map makers complain about aerial units being a pain to incorporate, or not working in their favor. By giving map makers these terrain options, They can greatly improve upon enemy waves or can make more challenging/engaging map mechanics.
By adding these terrain blocks, a multitude of new and exciting single player or multiplayer/pvp maps would be possible. Map makers would be able to flex their creativity and skills, and PvP players could be challenged to come up with new strategies that don't consist of spamming Pulsars and Quasars. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [✔] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [✔] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [✔] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [✔] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
oh no

**Comment by Nekuna** [comment]
Before anyone makes a comment about the logistics of volcanic ash impeding certain units or some inane detail, this is a post about the point of the barriers, not what the barriers are. Those can change, the purpose they serve won't.

**Comment by itcannotbe** [comment]
#862

**Comment by Nekuna** [comment]
> #862

Can't believe I missed that. Fortunately I think the two posts differ enough to not directly violate the rules. This post is more in-depth and covers more than just blocking air units.

**Comment by itcannotbe** [comment]
Yeah. I think legged units weren't a thing then.

**Comment by Kyllingene** [comment]
I actually have made a map that requires banning of air units, but the addition of these blocks would be great. With these, I could make it so you can make air units that bypass your defenses, but can't pass the barriers that I had to ban them for. Good idea, I like it!
