### ISSUE TITLE
Automatically spawn in largest core

### ISSUE THREAD

**Issue by Coolhandluke348** [Anuken/Mindustry-Suggestions#1737]
**Describe what you would like changed, and why.**
Currently, if you have a large core and a small core, you spawn in the small core by default. When you spawn in the small core, your build speed is much slower. This is an issue for new players that don’t know this and for servers that have unit control disabled. 

**Describe the changes you want to propose. Include possible alternatives.**
It would be nice to automatically spawn in the largest core on your team, or to change the way you switch drones so it isn’t disabled with unit control.

**Comment by itcannotbe** [comment]
Sound like this behavior is due to the server's config....

**Comment by Axzye** [comment]
Another idea is to always spawn from the core that you have last interacted with.

**Comment by Ilya246** [comment]
> 
> 
> Another idea is to always spawn from the core that you have last interacted with.
yes, good solution

**Comment by Ilya246** [comment]
Yes, spawning from the core you last spawned from is a good idea

**Comment by DeltaNedas** [comment]
^^^

**Comment by laok233** [comment]
but choose a core that u want to spawn is more better

**Comment by Coolhandluke348** [comment]
Maybe make it so the drone you spawn with isn’t from the core you spawn in, but the game checks if your team has a larger core, and gives the right drone based on that.

**Comment by Coolhandluke348** [comment]
> Sound like this behavior is due to the server's config....

Even on servers with unit control enabled, a lot of people still don’t know about it
