### ISSUE TITLE
Targeting Options For Turrets

### ISSUE THREAD

**Issue by Ultradrive** [Anuken/Mindustry-Suggestions#1738]
**Describe the content or mechanics you are proposing.**
add targeting options for turrets to either target the strongest, weakest, closest to the core, etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think it will help the players by allowing them to modify the turrets so it only attacks a certain enemy, which can be beneficial in a lot of ways

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Oh look a box! Lemme put an "X" even if I didn't actually do what it actually said to do.

The box:

 - [ ]  I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Also the box:
![h](https://c.tenor.com/nv7f19HKB2oAAAAM/blank-stare-really.gif)

**Comment by Yell245** [comment]
Processors: mmmm cool

**Comment by laok233** [comment]
just use processor
