### ISSUE TITLE
Phantom Drone Multiplayer- BIG Problems with Easy Fix

### ISSUE THREAD

**Issue by Loocsinatas** [Anuken/Mindustry-Suggestions#174]
Hello, I'm a hardcore mindustry gamer and mindustry youtuber, who only plays pvp! That being said I just wanted to shed some light on phantom builder drones and their serious problems in pvp!

The other day I played an hour long map on a Hex War pvp server. I had 8 phantom builder drones. Not a single drone helped me construct a single structure! Why? Because they're all too busy trying to rebuild the one cyclone turret that keeps getting blown up over and over and over again. Effectively wasting all my plastic, and wasting time for my drones! "well just delete the cyclone blueprint and they wont rebuild it" You might say? Well imagine a large blueprint filled with very small tiles, now imagine your drones trying to rebuild them one by one, you're sitting there like a nincompoop trying to delete the tiles 1 by 1 as they are reconstructed, all while they're getting shot down by turrets. You just can't delete the blueprints quick enough before they're all destroyed. And with 40+ hex tiles to do manage, there's no way I could prevent this from happening everywhere. **Also there's a common glitch where my drones fly across the map to someone who just quit, and rebuilds his entire base thinking it was under my control!**

So whats this easy fix? Split phantom builder drones into two separate drones! A building assistant drone, who's ONLY job is to fly around with me and help me build. Then another separate drone, just for reconstruction! This would free up the building drones to help me build. I dont know about you guys but it infuriates me when I'm building really slow and my drones just refuse to help.

The reconstruction drones would still be stupid though right? Rebuilding structures doomed to get blown up. We need some kind of -Clear Destructed Blueprints- button. In other words- forget about all the destroyed buildings and do not rebuild them! Almost like a /CLS or clear all button. 

This is one of two of my biggest issues with this game! I've talked to many other players online and they all think splitting them into two drones is a great idea. I also hear COUNTLESS people online say how stupid builder drones are, and I've even heard PRO top 10 players say they won't even bother making them anymore because of their tendency to waste resources.

So there's my problem presented to you guys, with a couple possible solutions! Let me know your thoughts. Thanks for reading, and praise be to Anuken for this treasure of a game!

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by kingb74** [comment]
Actually yea that makes sense but instead of having two types of drone u can set ure miner drones to reconstruct or assist in building

**Comment by itcannotbe** [comment]
Phanthoms and their AI won't be a part of 6.0

**Comment by kingb74** [comment]
Wait so don't tell miner drone have to be part of V6 right we can't not
have miner drones we are nothing without them
