### ISSUE TITLE
Requesting for auto-target in PC version

### ISSUE THREAD

**Issue by Force950** [Anuken/Mindustry-Suggestions#1740]
I have seen and played the mindustry android version and recently downloaded the PC version. I discovered that unlike mobile version their is no mechanic that can shoot automatically when enemy is in range or a mechanic that just aims at enemy while we shoot it.

I think this will improve the gameplay a lot as the PC players have a really hard time shooting the flying mech enemies(Or whatever they are called). This feature will make the gameplay much more better and will help in defeating the first few waves. I really have a hard time aiming at the ground units and I think this is not only my problem.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
This has been requested before.

**Comment by Force950** [comment]
> This has been requested before.

But I did a quick check on but didn't find any. Could you please send the link.

**Comment by laok233** [comment]
#1200
