### ISSUE TITLE
Cross-Sector power sharing

### ISSUE THREAD

**Issue by CaeciliusInHorto** [Anuken/Mindustry-Suggestions#1742]
**Describe the content or mechanics you are proposing.**

A way to share power between sectors.
This could be done in many different manners, but would need to be balanced well because it could be very OP.
Some ways to do this could be:
- A "Surge pylon" or something of the like that works like regular power nodes but across sectors
- A way to send filled batteries between sectors ("Battery launchpad")
Ways this could be balanced include
- Only 1 way transfer, you set an amount and you lose any excess power
- Needs coolant
- Needs lots of resources to build and/or work
- Space consuming

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will improve the game by allowing players to not have to build large power generation structures in every sector they want to use. This can allow players to expand into more sectors and experience more enjoyable activities, instead of repetitive building.

EDIT:
Another way this could improve the game is by allowing players to have power if they don't have much space to generate it, such as in a sector already full of infrastructure for other things (I'm looking at you, [sector that makes surge alloy])

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
(Cross sector power has been shared before, but not all of these specific ideas)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
1. create power schematic
2. launch/enter (to) the sector
3. send coal/thorium/spore pods/whatever to this sector
4. place power schematic
5. get resources from core into this power schematic
6. ???
7. PROFIT

**Comment by laok233** [comment]
just make power there, why not?

**Comment by CaeciliusInHorto** [comment]
> * create power schematic
> * launch/enter (to) the sector
> * send coal/thorium/spore pods/whatever to this sector
> * place power schematic
> * get resources from core into this power schematic
> * ???
> * PROFIT

> just make power there, why not?

What if you're doing a high level attack sector and don't have time to build a large power generation? Your best option is to stick a few RTGs on a core schem, and that doesn't generate much power and takes up a lot of core schem space.

**Comment by sample-text-here** [comment]
this wouldnt even be possible with the current sector system. or if it was, it would be very buggy and possibly be easy to get lots of power for free.

to everyone who wants to have "cross-sector sjfdhksdfjh", **please** do not suggest them. they would need a rewrite, and would most likely be bad for performance

ok, if this was possible, what would you use it for? if you have a rtg to kickstart enough diff gens (from core), you would have enough power to get t5. more if you use the diff's power to kickstart impacts.
