### ISSUE TITLE
Delete bundle_fr_be or merge it with bundle_fr

### ISSUE THREAD

**Issue by Phinner** [Anuken/Mindustry-Suggestions#1743]
**Describe what you would like changed, and why.**
Delete or merge bundle_fr_be because the french "written" in Belgium and France is almost the same. The differences are mainly in the "spoken" french. Plus, Having one single bundle for french would be simplier to update and adding new content and it would be less confusing.

**Describe the changes you want to propose. Include possible alternatives.**
Delete bundle_fr_be or merge it with bundle_fr.

**Comment by DeltaNedas** [comment]
also delete pt_br

**Comment by Anuken** [comment]
I don't understand either language, so I would be unable to merge the two bundles with any degree of accuracy. This is best discussed and implemented by other speakers of the language(s).

**Comment by Phinner** [comment]
I'm belgian so I can merge them.

**Comment by Phinner** [comment]
Imma try
