### ISSUE TITLE
Allow unit cap to be edited/fixed in the map rules.

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry-Suggestions#1744]
**This will essentially add a new feature to map creation and not affect current maps.**

Add a unit limit field in the map settings panel as well as a toggle to enable or disable core contribution towards the limit, enabled by default. 

If the core contribution is disabled the unit cap for the map will entirely be dependent on the limit being manually set. If core contribution is enabled the amount of units will be the unit cap + whatever amount the cores add.

This will I believe be beneficial in two ways:
- Maps that have a lot of cores will have a method to prevent people spamming units without literally banning them and making the map a lot less fun.
- Maps that have only one core but would like there to be more units can use the cap to increase the limit.

I did find a similar suggestion #1457 by Quezler but I don't think it is suggesting the same thing.
Also, I would be willing to add this feature myself with a pr if you like the idea but its not worth your own time.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
agree

**Comment by RedstonerKBC** [comment]
Some pvp maps are so huge they allow things like 90 corvuses and 80 octs and 120 toxopids and you get the idea. It lags and causes frequent server crashes especially when you do an attack and you have no control over what they do because so much is going on at once and your framerate drops to single-digits. On the other hand, enemy foreshadows are basically the only thing that defines pvp teams' territories and without lots of units there's no way to get past them. This would help us a ton.

**Comment by itcannotbe** [comment]
Why not both?
A fixed one and a dynamic one.
Fixed: Fixed through out the game
Per Core
Map Variable
Dynamic: Can change in the course of the game
Based on highest core
Core Multiplier

**Comment by TranquillyUnpleasant** [comment]
> Why not both?
> A fixed one and a dynamic one.
> Fixed: Fixed through out the game
> Per Core
> Map Variable
> Dynamic: Can change in the course of the game
> Based on highest core
> Core Multiplier

That is in fact precisely what i am suggesting, maps can have the option to do either one and its on the creators discretion.

**Comment by SavageCreeper64** [comment]
Yesss please, I have to suffer on single player attack maps with only 24 flares and very limited units.
