### ISSUE TITLE
Console button for mobile

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1745]
*I suggest adding a console button for mobile clients that support it. PC uses F8 for this, but mobile console can only be accessed by dev-mode and often doesn't show errors in scripts and such due to how mods are handled.*

*This would allow mobile clients to actually see whats wrong with code and mods and make debug easier. Button would be in top left or a small button next to the top left buttons in-game.*

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - X[] (<- nice X loser) I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have not entirely read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
> I have not entirely read ```README.md```

I hope that's a joke. It's a joke, right?

Otherwise, since I don't play on mobile, I cannot comment in any other way than this makes sense.

**Comment by joshuaptfan** [comment]
The button could be placed in the menu, like a small button on the bottom separate from back, settings, etc.

**Comment by BlueWolf3682** [comment]
> > I have not entirely read `README.md`
> 
> I hope that's a joke. It's a joke, right? This isn't in there, but still, if that is true...
> 
> Otherwise, since I don't play on mobile, I cannot comment in any other way than this makes sense.

i cant remember all the things it says no to so thats not a joke

**Comment by Kyllingene** [comment]
Well, if you have read it and have an idea of what it says, that's fine (not that I'm some sort of moderator, so don't take my word as law obviously). Since I have seen you around here a bit, I assumed you had, but was just making sure.

**Comment by BlueWolf3682** [comment]
i got the general idea of it

**Comment by sample-text-here** [comment]
> mobile console can only be accessed by dev-mode 

same with pc, you need any mod to enable the console. also the console is disabled by default for a reason

**Comment by BlueWolf3682** [comment]
i meant viewing the console, not writing into it.

**Comment by sample-text-here** [comment]
oh ok

**Comment by QmelZ** [comment]
just, press f8
![image](https://user-images.githubusercontent.com/59574967/104602289-4fd98e00-568c-11eb-9915-5f62681c4ef9.png)

**Comment by itcannotbe** [comment]
Is that an insult to people who can use actual keyboards on mobile?

**Comment by BlueWolf3682** [comment]
qmelz, please re-read the title of this suggestion.

**Comment by QmelZ** [comment]
> qmelz, please re-read the title of this suggestion.

okay, this is mobile

**Comment by BlueWolf3682** [comment]
not all mobile devices come with a pc running a mobile ui or a handy dandy f8 button.

**Comment by QmelZ** [comment]
> not all mobile devices come with a pc running a mobile ui or a handy dandy f8 button.

bind volume key to f8, problem solved

**Comment by BlueWolf3682** [comment]
and how will i change the volume of the music i listen to all the time?

**Comment by QmelZ** [comment]
press the unbound volume key and then use the onscreen slider

**Comment by BlueWolf3682** [comment]
too complicated and rebinding hardwired keys requires jank.

**Comment by QmelZ** [comment]
no it isnt, you can bind keys in mindustry

**Comment by BlueWolf3682** [comment]
...you cannot bind keys on mobile with mobile controls enabled.

**Comment by Yo0o0o** [comment]
I'd like bring this suggestion under the attention again. There's a valid usecase for this imho.

**Comment by BlueWolf3682** [comment]
Ping Anuke and hope he adds it. Since v7 comes with console access as an option, this should also be supported.
