### ISSUE TITLE
big sorter pls

### ISSUE THREAD

**Issue by SorterBoi** [Anuken/Mindustry-Suggestions#1746]
we need big sorter, anuek pls add it

**Comment by itcannotbe** [comment]
Can someone ban this troll account?

**Comment by Kyllingene** [comment]
Even if this is not a troll account, they clearly didn't bother to read any of the docs for the repo.

**Comment by Catchears** [comment]
> Even if this is not a troll account, they clearly didn't bother to read any of the docs for the repo.

I reckon it's a troll account.
https://github.com/Anuken/Mindustry/issues/4279#issue-780956591
