### ISSUE TITLE
give unitbind flag parameter

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1747]
**Describe the content or mechanics you are proposing.**
Make ubind have a flag as well as type parameter.  Null would mean no flag or any flag.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this means that on setup of the processor you can bind some units and set a flag to them. after setup you can then loop through the flagged units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
But how do you loop through the flaged units?

**Comment by catsz** [comment]
unit bind works by binding a unit and then when it ends it binds another unit.

**Comment by Ruichka** [comment]
I do not understand. What's the problem with giving out flags using `ucontrol flag`?

**Comment by itcannotbe** [comment]
He's suggesting something to make life easier.

**Comment by sample-text-here** [comment]
i think this would be mostly useless. if you check the flag of an unflagged unit, it will be 0, so all you need to do is end when you detect that.
