### ISSUE TITLE
Additional functionality for payload conveyor.

### ISSUE THREAD

**Issue by hhhi17** [Anuken/Mindustry-Suggestions#1748]
**Describe the content or mechanics you are proposing.**

At the moment, Mindustry has the ability to install and remove blocks from the payload conveyor using some iterations of the mono unit. Unfortunately, this is absolutely useless.
  You can add the ability to unload blocks from the payload conveyor. If there is not enough space, it will move the existing blocks forward. (If the size and number of blocks allow it).
  Various factories and storage blocks. For balance, factories produce blocks with less resources than the player. (controversial idea).
![2021-01-07 (4)](https://user-images.githubusercontent.com/77075911/103860563-e62a1480-50cc-11eb-8c5c-492b52cb5987.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

1)Development and use of existing mechanics.

2)Alternatives to some drones.

3)Another way to transport resources and energy.

4)Additional features for creators of mini-games in Mindustry.
![2021-01-07 (7)](https://user-images.githubusercontent.com/77075911/103860586-f0e4a980-50cc-11eb-94b3-195104dfa93e.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
Block factory already exists

**Comment by Kyllingene** [comment]
In beta, yes, but not currently in the actual game. Also, 

> You can add the ability to unload blocks from the payload conveyor. If there is not enough space, it will move the existing blocks forward. (If the size and number of blocks allow it).

That is requesting that the game attempt to unload blocks from a conveyor. I do believe that is also a block in the beta. We shall see if these two blocks get implemented (I sure hope so).

**Comment by Ruichka** [comment]
> In beta, yes, but not currently in the actual game.
It IS in the actual game and can be enabled using dev console or mods. It was in the game for a long time already. Please differ "beta" from "debug only".

**Comment by Kyllingene** [comment]
Ah yes, I am sorry. I thought it was a beta that was just hard to access, which in a way it is. However, it is still factually incorrect.
