### ISSUE TITLE
Pixelate Visual Effect

### ISSUE THREAD

**Issue by vb0t** [Anuken/Mindustry-Suggestions#1749]
**Describe what you would like changed, and why.**
The pixelate visual effect is only applied to the world in game, the gui's and everything else like the tech tree and campaign world remain default.
I like the pixelate effect as it gives the game a retro style, and the option to pixelate more than just the game would add a nice sense of depth.

**Describe the changes you want to propose. Include possible alternatives.**
Just an option to apply the pixelate effect to the whole screen or include the gui's. I understand that pixelating text might be an issue, so I completely understand if you close this. 
Thanks in advance!

**Comment by Catchears** [comment]
> so I completely understand if you close this.

Anuke rarely closes issues. The readme says that he checks this repo daily and implements any suggestions he likes, but leaves closing them up to the person who made the issue.

**Comment by Kyllingene** [comment]
I agree, and especially like to find someone who requests something in the correct format and without any unreasonable attachment to a bad request (not that this is, again, it would be nice).
