### ISSUE TITLE
Shockwave Sphere Turret - Shoots Electric Spheres that do...

### ISSUE THREAD

**Issue by SonPlaying** [Anuken/Mindustry-Suggestions#1750]
**Describe the content or mechanics you are proposing.**
The Shockwave Sphere Turret. This turret uses nothing but electricity to shoot. The turret shoots out electric spheres with the max shooting range of 8/10 blocks, with the fire rate of 0.4 shot per second. The turret only attacks ground units. You name the turret.

The sphere, upon contact with enemy, or when it reaches the maximum range, will explode and cause a small AoE damage of 4 blocks to the enemy around it. Also, it will inflict slow effect upon enemies that got hit with the explosion.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This turret will be an addition for turrets that need electricity only. The turret is useful for slowing down powerful enemies. The turret also will be useful to make other turrets do more damage to the enemies inflicted with the slow effect. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
So a more wave-like turret, but electric. Considering the lack of non-liquid, non-air support turrets, I like this. If you are able to mod, an example could be very beneficial to your case, although it's obviously fine if you can't. +1
