### ISSUE TITLE
Research Center and Knowledge Points

### ISSUE THREAD

**Issue by OptimalPrimus** [Anuken/Mindustry-Suggestions#1751]
**Describe the content or mechanics you are proposing.**
I hope you add a Research center for upgrades on various blocks like the drills or turrets. Example: The mechanical drill could drill more faster without replacing it with a pneumatic drill, but doesn’t have the same features as the pneumatic drill like drilling titanium. All blocks have a limit for upgrade, say about up to 10 and cannot upgrade it more than 10 times. Each upgrade gets more expensive if the upgrade is higher. You have to supply the research center with supplies like copper or titanium for it to start researching it. It also takes time for it to upgrade and the time gets longer as the upgrade goes higher. 
It saves for the whole entire planet so whenever you go to a new sector, you don’t have to start researching it again. You also need knowledge points to research it and to get those, you need to wait. Say you get about 10 every 2 minutes. The knowledge points cost will also go up when the upgrade gets higher. One of the upgrades could be more knowledge points for every 1 minute. Destroying the research center will make you restart researching everything. Also, having more research station could make the researching faster for what you are researching, but you also need to supply it with the right materials to make it start researching. Supply it using conveyor belts. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will improve the game since it will be more harder on the higher waves and starting off you only have limited supplies, so with a normal turret couldn’t stand a chance against like 30 maces on the first wave. Plus, you only need one research center in the planet so you don’t have to worry about having another one in another sector. This gives you a choice for an upgrade or replacing a block with a better block. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

nah

**Comment by joshuaptfan** [comment]
Duplicate of #1489 #583 #203 #157

Please close this.

**Comment by RedstonerKBC** [comment]
> > I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> > I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
> nah

To be fair though, their idea is not actually listed in the README.me and also when you have thousands of issues it can be easy to miss duplicates when doing "quick searches" to check if your idea has already been suggested. This happened to me I think twice now even though I did search for duplicates of my ideas both times. Lol it happens.

**Comment by Kyllingene** [comment]
> To be fair though, their idea is not actually listed in the README.me

This line here:

> Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

e.g means "for example", which tells us that just about *any* additional config of blocks, *not* just I/O side config, is not to be suggested. Here is the line rewritten to explain it better:

> Additional configuration of blocks such as (but not limited to) I/O side configuration, which has been suggested a million times

So while missing a few duplicates is understandable, this line does indeed state that things such as upgrades should not be suggested.

**Comment by genNAowl** [comment]
Sounds like monkey knowledge from BTD6
