### ISSUE TITLE
A new flying snake like unit as the next new enemy in the next planet

### ISSUE THREAD

**Issue by Eldeston** [Anuken/Mindustry-Suggestions#1754]
**Describe the content or mechanics you are proposing.**
A new branch of flying units with a unique behavior to form a snake. This unit lines up and form together to become a snake like shape. It can move fast when alone, but gets slower as more units add up to the line. The 1st tier unit alone, will act like a crawler, except its explosion damage is less than that of a crawler. It flies very fast, but is not capable of grouping/lining up into a snake. The 2nd tier, instead of exploding, this unit will have the ability to shoot like turret arcs. It will have the ability to group into a snake and allows the tier one versions to link up and form a body. The 3rd tier will be less faster and shoots weak homing missiles and pulses an EMP like ability that temporarily disables any nearby units or low tier buildings that consume power(e.g. arcs and lancers) for a few 5 or less seconds. It will also have the ability to group its lower tier counter parts. The 4th tier, will be really slow, and drops blue bomb clusters that disables any building that consumes power and units for a good 10 or more seconds. This unit will also have the ability to link up with its lower tier counterparts. The final tier, will not be able to use any weapon, but will have a special blue shield that any unit that enters it disables until it is outside its shield and defend from any power consuming turrets(non power consuming turrets can get through the blue shield) and have lots of health. It uses EMP pulses that disables any power consuming building for a good 18 seconds, but has a cooldown of 24 seconds. The cooldown stacks up the more units link up with this tier(2 units adds 2 seconds to the cooldown).

Here's some rough ideas of how this unit looks:
![textures](https://user-images.githubusercontent.com/59617287/103962753-204cf200-5171-11eb-95cc-93c7a6ee5375.png)
Original concept using alphas
![textures](https://user-images.githubusercontent.com/59617287/104023547-4313f080-51db-11eb-90ec-aef08337d7af.png)
Tier 3 units and a tier 5 unit, based on "the Javeler" from v5 color palette

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Dealing with these kinds of units will force players to also use non-power consuming turrets and introduce a new enemy in the planet. This will also introduce a new fighting style and introduce the EMP skill.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Unit limit be like: *_cough_*  *_cough_* I exist *_cough_* *_cough_*

**Comment by joshuaptfan** [comment]
Too many weird cross interactions to be practically implemented or used in-game. Can the body be made up of higher tier units (lower tier than the head)? Can it be made up of a mix of tiers of units (T4 head controlling T1, T2, T3 body segments)?

There also doesn't seem to be any significant benefit to units to joining together. Au contraire, it combines them into a single target, making them easier to kill.

**Comment by RedstonerKBC** [comment]
Cool but how do T1 segments attack if they group together? It's like a chain of T1's that explode automatically?

What do the 'body' units contribute to the overall snake? Can they shoot?

This is a really amazing idea but it needs lots of details worked out to be implemented. If not in vanilla someone should make a mod out of this.

> Unit limit be like: *_cough_* *_cough_* I exist *_cough_* *_cough_*

Yes but that doesn't stop people from making lots of flares and monos.

> Too many weird cross-interactions to be practically implemented or used in-game. Can the body be made up of higher tier > units, e.g. T3 head controlling T2 body segments? Can it be made up of a mix of tiers of units, e.g. T4 head controlling T1, T2, > T3 body segments? How does the player control joining/splitting of these units?

Maybe when you press the command key instead of going in a circle around you snake units connect to your body and disconnect when you release them?

**Comment by itcannotbe** [comment]
> > Too many weird cross-interactions to be practically implemented or used in-game. Can the body be made up of higher tier > units, e.g. T3 head controlling T2 body segments? Can it be made up of a mix of tiers of units, e.g. T4 head controlling T1, T2, > T3 body segments? How does the player control joining/splitting of these units?
> 
> Maybe when you press the command key instead of going in a circle around you snake units connect to your body and disconnect when you release them?

The question is not how to control them. it's more of how the game and the player handles multiple different senarios.

**Comment by sample-text-here** [comment]
> > Unit limit be like: cough cough I exist cough cough
>
> Yes but that doesn't stop people from making lots of flares and monos.

it does

> Cool but how do T1 segments attack if they group together?

look at this

>  but is not capable of grouping/lining up into a snake



and also, yeah, there are too many edge cases to implement this well.

**Comment by DeltaNedas** [comment]
flying routerpede
@sample-text-here works but rotation is offset by 90 degrees dont know why, too hard to fix

**Comment by Eldeston** [comment]
> Too many weird cross-interactions to be practically implemented or used in-game.
> 
> * Can the body be made up of higher tier units, e.g. T3 head controlling T2 body segments?
> * Can it be made up of a mix of tiers of units, e.g. T4 head controlling T1, T2, T3 body segments?
> * How does the player control joining/splitting of these units?
> * What happens when a player relinquishes control of joined units?
> * If they are worth joining together, how does the default AI make use of that functionality when they are not player controlled?
> * How does enemy AI join them together, or spawn them already joined?
> 
> There also doesn't seem to be any significant benefit to joining units together. Au contraire, it combines them into a single target, making them easier to destroy.

When one of the segments are destroyed, they disconnect for while, then reconnects to the nearest main body. Higher tiers will be the head and tiers lower than it become the segment. When the player controls it, the priority will be the main head. Other players may be able to control body segments, but cannot move and follow/stick to the rest of the segments. It must first check for the nearest units available to attach and make a body, will work the same way when they first spawn.

**Comment by Eldeston** [comment]
> Cool but how do T1 segments attack if they group together? It's like a chain of T1's that explode automatically?
> 
> What do the 'body' units contribute to the overall snake? Can they shoot?
> 
> This is a really amazing idea but it needs lots of details worked out to be implemented. If not in vanilla someone should make a mod out of this.
> 
> > Unit limit be like: __cough__ __cough__ I exist __cough__ __cough__
> 
> Yes but that doesn't stop people from making lots of flares and monos.
> 
> > Too many weird cross-interactions to be practically implemented or used in-game. Can the body be made up of higher tier > units, e.g. T3 head controlling T2 body segments? Can it be made up of a mix of tiers of units, e.g. T4 head controlling T1, T2, > T3 body segments? How does the player control joining/splitting of these units?
> 
> Maybe when you press the command key instead of going in a circle around you snake units connect to your body and disconnect when you release them?

The rest of the body with weapons can shoot, but will remain intact with the main body. The lower tier units that explode, detach from the body then explode if its health is less than the inputted threshold(maybe at 50%).

**Comment by Eldeston** [comment]
> Maybe when you press the command key instead of going in a circle around you snake units connect to your body and disconnect when you release them?

Yeah it could use the command key

**Comment by joshuaptfan** [comment]
Again, what makes it worthwhile for units to connect together? What can they do together that they can't do separately, besides "snake is kewl"? OP, you didn't think this through, but I'll do it for you. Let's suppose that:
* Snake body segments can still target enemies independently and fire their weapons
* The snake head gains a buff to its health equal to a small percentage of each body segment's health (to account for the fact that body segments can be mixed tier units)
* The snake head's weapons are upgraded according to how many body segments it has, e.g. fires more/bigger projectiles per shot, T5 fires electric arcs, etc. This is the point that connecting worthwhile!
* And as OP said, speed is decreased depending on number of body segments

Therefore, the optimal strategy to counter a snake would be to snipe out the body segments, which are not buffed. This will challenge turret logic designers, because the current optimal strategy of targeting the strongest enemy is inverted for this unit type. This in turn incentivizes making higher tier body segments, so that they have more health.

Let's look at linking behavior; perhaps it can be automatic, which would make the units actually useful without requiring player micromanagement. Suppose that the units have a range, that increases with tier, in which all lower tier snake units will be signaled to automatically seek out and connect to the end of its tail, like magnets, until the snake is at the max length, which we will say is 8.

What happens in combat?

When a body segment is destroyed, the body segments behind it now have a new head, which is the front-most unit. Any body segments lower in tier than the head are automatically disconnected, which means that the entire severed tail will disband instantly if they are all the same tier.

Because of the nature of unit caps (same cap for every tier) and the supposed automatic linking behavior, a max cap group of snake units will consist of some max length snakes, some shorter snakes, and some leftover higher tier units with no tails. As some snakes are severed, their body segments will disband and automatically connect back to the original snakes, or other leftover heads.

**Comment by notMEEPoffaith** [comment]
aaaaaaaa noooooo please no you will put PU out of buisness

**Comment by Zeniku** [comment]
You can try [Pankiwi's Snake Lib](https://github.com/pankiwi/snake-lib) 
For snake units

**Comment by Eldeston** [comment]
> Again, what makes it worthwhile for units to connect together? What can they do together that they can't do separately, besides "snake is kewl"? OP, you didn't think this through, but I'll do it for you. Let's suppose that:
> 
> * Snake body segments can still target enemies independently and fire their weapons
> * The snake head gains a buff to its health equal to a small percentage of each body segment's health (to account for the fact that body segments can be mixed tier units)
> * The snake head's weapons are upgraded according to how many body segments it has, e.g. fires more/bigger projectiles per shot, T5 fires electric arcs, etc. This is the point that connecting worthwhile!
> * And as OP said, speed is decreased depending on number of body segments
> 
> Therefore, the optimal strategy to counter a snake would be to snipe out the body segments, which are not buffed. This will challenge turret logic designers, because the current optimal strategy of targeting the strongest enemy is inverted for this unit type. This in turn incentivizes making higher tier body segments, so that they have more health.
> 
> Let's look at linking behavior; perhaps it can be automatic, which would make the units actually useful without requiring player micromanagement. Suppose that the units have a range, that increases with tier, in which all lower tier snake units will be signaled to automatically seek out and connect to the end of its tail, like magnets, until the snake is at the max length, which we will say is 8.
> 
> What happens in combat?
> 
> When a body segment is destroyed, the body segments behind it now have a new head, which is the front-most unit. Any body segments higher or equal in tier to the head are automatically disconnected, which means that the entire severed tail will disband instantly if they are all the same tier.
> 
> Because of the nature of unit caps (same cap for every tier) and the supposed automatic linking behavior, a max cap group of snake units will consist of some max length snakes, some shorter snakes, and some leftover higher tier units with no tails. As some snakes are severed, their body segments will disband and automatically connect back to the original snakes, or other leftover heads.

So sorry for the late reply. Let's just say that this concept is heavily inspired by Terraria's worm bosses, such as the Eater Of Worlds or The Destroyer.

After seeing a video showcase of Mindustry v8 with a humongous snake like enemy in Creslex video, I recently came back to check on this suggestion. The idea of an infection type enemy (like the Crimson or Corruption in Terraria) is absolutely nuts! Though I kinda expected that there would be a spore variant in the first planet...
