### ISSUE TITLE
Increase uradar (unit radar) range to cover all unit weapons

### ISSUE THREAD

**Issue by thunkk** [Anuken/Mindustry-Suggestions#1756]
**Describe what you would like changed, and why.**
Currently it seems that the uradar range does not cover the range of all weapons the unit has. For example in case of Toxopid, which has fairly long range cannon, the urange command seems to start functioning when enemies have reached the range of the lasers (basically crawling between it's legs). This severly limits the potential effectiveness of logic controlled units, leading to odd situations where a logic controlled unit can be attacked by an uncontrolled unit of the same type without being able to respond. Corvus however does not seem to suffer from such issues, as it only has the long range laser.

**Describe the changes you want to propose. Include possible alternatives.**
Increase uradar range of a unit at least to the range of that unit's longest ranged weapon.

**Comment by thunkk** [comment]
Unsure if the current behavior is intended for some reason, maybe this is a bug?

**Comment by joshuaptfan** [comment]
The range is probably that of whatever the "first" weapon is for simplicity. It shouldn't be too hard to make it be the max of all weapon ranges.

**Comment by Jammo2000** [comment]
> The range is probably that of whatever the "first" weapon is for simplicity. It shouldn't be hard to make it be the max of all weapon ranges.

Never EVER say it shouldn't be hard. You have jinxed the implementation. You will cause this scenario:
One little bug in the game
One little bug,
Take it down, patch it around,
Thirty-two little bugs in the game.

**Comment by Kyllingene** [comment]
> Never EVER say it shouldn't be hard. You have jinxed the implementation. You will cause this scenario:
One little bug in the game
One little bug,
Take it down, patch it around,
Thirty-two little bugs in the game.

I have a similar shirt to that, actually.

But yes, this would be a job for someone who has more time for digging through files than Anuke does, or at least it would optimally be done by someone of that sort.

**Comment by joshuaptfan** [comment]
The issue has been [fixed](https://github.com/Anuken/Mindustry/commit/7372bf37c28561ef66898995f607aba4f2c14d6f).
