### ISSUE TITLE
Change Processor Set Type

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1757]
**Describe the content or mechanics you are proposing.**
With unit bind and sensor there is a little pencil to edit what its binding or whatever. But with set its impossible to add this so there should be a way to change the set type.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make processors more user friendly for people who barely know logic.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
because you can set anything? why should it list every single builtin variable? what about program-defined ones?

the solution is to use your head
