### ISSUE TITLE
Separate display of the amount of electricity consumed and generated.

### ISSUE THREAD

**Issue by KirillAldashkin** [Anuken/Mindustry-Suggestions#1759]
**Describe what you would like changed, and why.**
When you click on the power node, display (separately) the amount of electricity generated and consumed. This feature will make it easier to understand the processes in the power grid.

**Describe the changes you want to propose. Include possible alternatives.**
In the "Power" bar of information about the power node, separately display information about the generated and consumed electricity. For example:
![image](https://user-images.githubusercontent.com/52224930/104084062-d8b48c00-527e-11eb-823e-d12fb3238b0f.png)

**Comment by Kubek0212** [comment]
You can use logic processors with @powernetin and @powernetout variables. Then outputting the results to message block.
