### ISSUE TITLE
Utility unit factory

### ISSUE THREAD

**Issue by cosMICrus** [Anuken/Mindustry-Suggestions#176]
Utility units factory

Lets you make draugs, spirits and other utility units (if they'll be added)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
uhh. This already exists?

**Comment by Katsute** [comment]
He means a multi-type unit spawner, like the ones being added in 6.0

**Comment by potatoisagender** [comment]
oh
