### ISSUE TITLE
New towers

### ISSUE THREAD

**Issue by MaksNiko2** [Anuken/Mindustry-Suggestions#1760]
**Describe the content or mechanics you are proposing.**
Vulcan - machine gun: a lot of shots per second, medium range (15?), reduced effectiveness against high-tier enemies, 2x2 or 3x3
Meteor - mortar: high damage on very large area (10-15?), very low rate of fire and accuracy, long range (40?), probably minimal range, 3x3
Railgun/Gauss: very high single target damage, probably some pierce, long range (40?), energy usage measured in mass (E=mc2, just to make sure), 2x2 or 3x3, kinda small Foreshadow
Storm - rocket launcher: insane area damage along with high rate of fire (barrages of 10+ rockets every few seconds), very long range (50?), activates only if tier 4 enemy is in range, absurdly high ammo consumption, targets only ground or only air depending on ammo, 5x5 or 6x6, maybe a superweapon mentioned on Trello

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Vulcan - an expensive and very effective way of dealing with weaker units not being a late game defence
Meteor - a way of dealing with crowds in late game without wasting a hundred surge alloy
Railgun/Gauss - something to deal with tier 4 units in earlier game, such as Scepter in Stained mountains, which may be very hard to kill with weapons like hail or lancer
Storm - to make a relatively small, effective defense against tough enemies and to grant a way of making late game defense without spamming towers

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Basically more effective weapons because...........

**Comment by BlueWolf3682** [comment]
mods.

**Comment by AnOreo1** [comment]
mods

**Comment by Kyllingene** [comment]
This may not be original, but... mods. Anuke doesn't like turret suggestions, for several reasons, the chief being (I believe) that it would be really hard to root through all of the turret suggestions just for the 2 good ones.
