### ISSUE TITLE
Atrax and higher with deep water / slag

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1761]
**Describe what you would like changed, and why.** atrax and higher walking on slag and deep waters pretty sure you know what i mean and it should be changed so they could get slowed down in deep water like dagger in shallow water. on slag it should get damaged

**Describe the changes you want to propose. Include possible alternatives.** atrax slower on deep water and get damage on slag

**Comment by catatagun** [comment]
Its cuz atrax leg touch slag and no die

**Comment by WinterCrystal** [comment]
The whole idea of the crawler tree is that it can walk over most terrain except the t1 version without getting unfavorable affects such as getting burned on slag or get slowed down or get drowned on tar/water. It's the only ground unit tree that is able to do that. it's what makes them stand out from the other ground unit trees, they can go to places faster than the dagger or nova tree units, your suggestion gets rid off of what makes unique in the first place. Atrax already has terrible movement speed, and rarely anyone uses them, nerfing it even further by making them burn on slag or get slowed down on deep water is pointless as it is. Close this.

**Comment by RedstonerKBC** [comment]
Still not closed lol. But yeah I think crawlers being slowed in deep water makes sense, though slag damage is debatable. Being able to dip your foot in liquid earth is impressive.

**Comment by Kyllingene** [comment]
Being able to pipe liquid earth through glass is even more impressive.
