### ISSUE TITLE
Touch / mobile controls need better documentation

### ISSUE THREAD

**Issue by thw0rted** [Anuken/Mindustry-Suggestions#1763]
**Describe the content or mechanics you are proposing.**

I played exclusively on mobile for a long time but recently tried desktop. I really like conveyor pathfinding (hold CTRL while dragging) but I don't think there's a way to do it on mobile. (If I'm wrong, somebody please tell me and I'll edit the title to "document mobile controls better"...)

I'm not sure how to implement. Either it's always on when the checkbox in Settings is enabled, or there's a toggle in the UI - long press the direction arrow and it gets a box around it like the indicator around the hammer that shows remove mode is active, etc. You could do something tricky like start dragging, then use a second finger to touch nearby, and as long as the second touch point is there it's equivalent to holding CTRL on desktop. (You'd have to release the first finger before the second, which is hard to explain, so maybe not this?)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Routing conveyors is the most frustrating part of playing on mobile, and also like 80% of what you do minute to minute. It should be as easy as possible.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[LOL Nope] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
![Screenshot_20210110_184137](https://user-images.githubusercontent.com/45280919/104120677-9d47b980-5373-11eb-8f1f-787a791db4b5.jpg)

**Comment by thw0rted** [comment]
As promised...

Seriously though, how is a brand new player supposed to know what that button does? I remember trying to guess when I got started, couldn't figure it out, and just figured it was some advanced thing I'd get to later.

Maybe I need to make a new suggestion, tooltips for all UI buttons - hover on desktop, long press on mobile.
