### ISSUE TITLE
"Infinite" power source

### ISSUE THREAD

**Issue by breadbug23** [Anuken/Mindustry-Suggestions#1764]
Setting the power input of the power source back to what it was originaly, as some multiplayer servers use it for custom game modes. 
The change of the output of the power source wasn't necesary, as it is normaly only aviable in sandbox and in map editor, and used on some maps as an "infinite power source". the change possed quite some problems on some servers, requiring to change the output in the plugins, causing some confusion player-side.

**Comment by itcannotbe** [comment]
How so?

**Comment by Yell245** [comment]
> How so?
> 
> Also what on earth of a map uses source blocks outside sandbox anyways?

Maps with many mending projectors, overdrives, energy turrets, parallaxes, segments, [insert many energy consumers you need to power as compact as you can here]

**Comment by laok233** [comment]
https://github.com/Anuken/Mindustry/commit/da96b234413b2a5ad54f9408dcdcb15cac5d6fa7
buffed to 100k

**Comment by laok233** [comment]
close

**Comment by Catchears** [comment]
I'm pretty sure it's been buffed to a million.

**Comment by breadbug23** [comment]
> 
> 
> How so?
> 
> Also what on earth of a map uses source blocks outside sandbox anyways?

I know it's been several days and it's a late reply, but some server use those.
I can cite [AA]'s plague game mode, which use the power source for one of the team.

**Comment by laok233** [comment]
close this issue because is already buffed
Anuken/Mindustry@da96b23
