### ISSUE TITLE
Automatic game data export

### ISSUE THREAD

**Issue by thw0rted** [Anuken/Mindustry-Suggestions#1765]
**Describe the content or mechanics you are proposing.**

A lot of people are asking for accounts or cloud sync but it's on the do not suggest list. I'm not surprised, that would require you to host a sync service or integrate with a provider like Google Drive / Dropbox / GitHub / whatever, plus handle conflicts / stale saves, etc.

What if instead, you just did a "game data export" automatically to a chosen directory every time the user goes back to the main menu from Campaign mode? (I *think* that's the only time "game data" changes, unless it also tracks something about multiplayer?) That way, the "sync" part is somebody else's problem. No conflict merges, no lost progress - I'm responsible for getting the file somewhere else via whatever mechanism I want, I'm responsible for manually importing it if it's changed. You just provide the first link in the chain - keeping my local progress state up to date.

I know I can do this manually, but I always say that a backup you have to think about might as well not even exist.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Everybody can stop nagging you about accounts 😁

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Isn't this already enough?
![Screenshot_20210110_185427_io anuke mindustry](https://user-images.githubusercontent.com/45280919/104120906-64a8df80-5375-11eb-9839-24cfe9d6c730.jpg)

**Comment by thw0rted** [comment]
> I know I can do this manually, but I always say that a backup you have to think about might as well not even exist.

If the game can just keep a file on disk that always has my latest progress, I can take care of making sure it's backed up / sync'd to my phone / whatever. If I have to do it myself, I'm *going* to forget. (File under "QoL", if you like)

**Comment by DeltaNedas** [comment]
```sh
#!/bin/sh
cd $HOME/.local/share/Mindustry
java -jar Mindustry.jar
git add -A
git commit -am "$(date)"
```
yes this requires divine intervention on mindustrys part

**Comment by thw0rted** [comment]
Thanks, @DeltaNedas!  I wasn't sure if the "export" function did something special to make it portable/cross-platform-robust.

On desktop, I'm playing the Itch version on Windows, so I think the equivalent is `%appdata%\Mindustry`.  On Android, I see similar files under `/Android/data/io.anuke.mindustry/files/`.  It looks like campaign "progress" is all in the `saves` subdirectory -- it's full of `.msav` files.

If I were to sync this directory between platforms, should I expect that to Just Work?  If it does, maybe I can write up an entry in the docs somewhere -- it'd be nice to have a page to link to when people suggest "accounts" or "cloud save".

**Comment by DeltaNedas** [comment]
yes it does, albeit identical performance settings on a phone may not work nicely, you may want to put settings.bin in your .gitignore

**Comment by thw0rted** [comment]
I actually don't think anything else under the game's "data root" needs to be sync'd -- I don't use mods, and I don't need to version-control / sync the `cache` or `previews`.  I think the `saves` subdir should be plenty.

**Comment by DeltaNedas** [comment]
settings.bin also contains campaign sector metadata

**Comment by thw0rted** [comment]
This is starting to sound like *on mobile* it's a little tricky to fully automate. Maybe a Tasker script? Hrm.

**Comment by Johnystar** [comment]
> settings.bin also contains campaign sector metadata

@DeltaNedas 

That is the main problem here, at least in my eyes. https://github.com/Anuken/Mindustry-Suggestions/issues/380#issuecomment-846549516

**Comment by thw0rted** [comment]
Per @Johnystar I think this ticket could be considered solved if the game stored campaign progress under the `saves` folder, separate from the performance/UI settings.
