### ISSUE TITLE
Tags for Schematics

### ISSUE THREAD

**Issue by marky0470** [Anuken/Mindustry-Suggestions#1766]
**Describe the content or mechanics you are proposing.**
A way to create tags in the schematics window, making finding schematics easier
Here are a few ways I have thought that this could be implemented.

#### Name-based Search
* No new tag system needs to be implemented, essentially the user would be able to create buttons with some text, say, "Surge" and when clicking this button, it would replace the search bar's text to "Surge" and start searching. For multiple tags, one could simply hold the shift button and click multiple buttons.

ex. If done with "scrap" and "surge", the game searches for schematics with names containing "scrap" and "surge", with a space in the middle.

It decreases the amount of time required to search to just a few button presses before the sought schematics is within view. However,
this would of course only be useful if all schematics were named respective to their function. 

#### Icon Tags
* Schematics could be tagged with icons similar to how sectors on Serpulo can have different symbols. Multiple tags could be used. A box to the side of the schematics window shows icons that are used for an existing schematic, unused icons could be grayed out. Clicking on the tag shows all schematics with said tag(s).

Instead of words, icons for easier identification.

#### Block-Based Searching 
* Similar layout to the Icon Tags, with blocks themselves, the topmost blocks to be presented are usually production blocks. When a block is selected, schematics with the corresponding blocks are displayed.

Least favorable since it's basically the same as going through the schematics page. And selecting a silicon smelter with the intention of making silicon might show scrap to surge schematics. A way around this would be to allow the user to designate the key block in the schematic when first saving it. Searching with the silicon smelter would leave out scrap to surge because the key block for those schematics would have been the alloy smelter.

They could even be made to display most frequently used tags at the top.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It makes schematic finding easier, especially once a player has filled their page with dozens of schematics. Some may even have PVP specific schematics or give them obscure or detailed names, this is just a way to add some meta-organization or filtering

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
woah imagine if the description box was searched in that would be crazy

**Comment by Kyllingene** [comment]
> A way around this would be to allow the user to designate the key block in the schematic when first saving it. Searching with the silicon smelter would leave out scrap to surge because the key block for those schematics would have been the alloy smelter.

How would Mindustry decide what the "key block" was? Would you have to designate it? In that case, it seems like a little too much effort for anyone who doesn't make tons of schematics, and thus is not worried about finding them (as they have so few and don't really care for them). Otherwise, it doesn't seem too hard to implement, so it seems fine to me.
