### ISSUE TITLE
Better pathfinding AI

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry-Suggestions#1767]
**Describe what you would like changed, and why.**
@Anuken wrote:
> I don't see why this is a problem. Picking the path of least _terrain resistance_ makes sense ... breaking through all those walls would take much longer than breaking through the turrets. 

However, a _better_ AI would pick multiple routes of attack instead of focusing all units into a single predictable path. Even if it would take longer, it keeps defenders on their toes to make sure every possible path to their base core is at least secured.

>A super-intelligent AI that picks the path of least turret coverage isn't a fun mechanic.

This is exactly what the AI of legs units, such as Corvi and Toxopids, can do anyway, which makes said units annoying without proper preparation. Take Planetary Launch Terminal, for example.

**Describe the changes you want to propose. Include possible alternatives.**
Allow unit pathfinding to be more flexible, allowing units to pathfind to specific coordinates, instead of a predetermined target flag. Units should also be able to deviate from the "main" path in order to flank if possible. For example, command centers can have a "split rally" command that makes units pathfind to different command centers, instead of the closest one; another command would be "flank attack", which makes units take multiple different paths to the enemy, or approach different enemy spawners instead of the closest one (especially if said drop points are separated from each other).

**Comment by DeltaNedas** [comment]
yes

**Comment by Humanoid-X** [comment]
wow good yes

**Comment by Mee42** [comment]
on an aside, the proper way to say "yes" on github is to use the :+1: reaction, so people don't get push emails.

On topic though, what if there was some element in randomness when pathfinding? In maps where there's 2 distinct ways for enemies to pick between, if they didn't pick the one with the least turrets/walls/terrain/whatever-your-hueristic-is, they'd actually go both ways sometimes.
