### ISSUE TITLE
Make cmd centers only affect them selves

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry-Suggestions#1768]
I'm playing on .io and it is very annoying, it just makes boats and air attack when boats I want them to stay

**Comment by BlueWolf3682** [comment]
what

**Comment by Kyllingene** [comment]
Neil2101, is there any particular reason you deleted the template and made it unviewable in the history? And why did you not give a label? This suggestion will be discarded by Anuke because of the lack of template and lack of label. Please re-add them. Also, what do you even mean?

**Comment by Humanoid-X** [comment]
what are you saying

**Comment by Yell245** [comment]
I think he means "Add ability to command units in command center separately by their classes"

**Comment by itcannotbe** [comment]
> I think he means "Add ability to command units in command center separately by their classes"

If that's the case, that's already been suggested.

**Comment by antonilol** [comment]
he deleted the templated because he had to tick the box 'Not already suggested'

**Comment by Kyllingene** [comment]
I believe that this should be closed. It is probably already suggested, if not an actual thing in the game. Also, they put deliberate effort into making this harder to classify and think about (deleted issue + template).
