### ISSUE TITLE
BulletHitEvent for modding

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1769]
**Describe the content or mechanics you are proposing.**
Add a BulletHitEvent which fires every time a bullet hits something and has the bullet + whatever the bullet hit (.bullet and .target?) in it.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More modding possibilities without having to mod the source code.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
good

**Comment by GlennFolker** [comment]
You really shouldn't, event classes don't implement `Pools.Poolable`. You do know how many bullets that could hit a target in the same tick, don't you?
