### ISSUE TITLE
Remove liquid incineration

### ISSUE THREAD

**Issue by harsspartan118** [Anuken/Mindustry-Suggestions#177]
Incinerator shouldn't delete liquids. Since there is no liquid mixing or liquid sorters, incinerators never get used for liquids. Unwanted liquid from a pipe can already be removed by leaking it into the ground.

Restricting incinerator to only items, will make it easier to place it in very tight spaces, without really affecting the rest of the gameplay.

**Comment by itcannotbe** [comment]
But liquids being incinerated was actually an implemented suggestion.

**Comment by harsspartan118** [comment]
I've never seen anyone use it though.
Leaking an unwanted liquid works pretty quickly if you have pressure from the desired liquid coming in.

Don't see any other use for an incinerator for liquids.
