### ISSUE TITLE
A brand new design to simplified the belt machine interaction to some extreme.

### ISSUE THREAD

**Issue by YagaoDirac** [Anuken/Mindustry-Suggestions#1770]
**Describe what you would like changed, and why.**
Now all the machines give out productions to the conveyor next to them. This makes a lot of issues. People are forced to separate the ingredients and productions everywhere. Theoretically, the reason is that the input and output share the same position.
![1](https://user-images.githubusercontent.com/16892000/104401588-7239b180-558f-11eb-81c5-d6b703314dcf.png)
This is due to the positions a machine searches for input and output are the same, or they share some tiles. But if the productions are put to a farther position? Let's say a tile away from the machine.
![2](https://user-images.githubusercontent.com/16892000/104401899-17548a00-5590-11eb-97ac-4cab6ff970df.png)

With the suggested style, the graphite press zone should look like:
![4](https://user-images.githubusercontent.com/16892000/104402836-22a8b500-5592-11eb-82c4-f790c53bb8d0.png)
Also, if a machine search items automatically from conveyors next to itself, the zone is possible to simplified further like this:
![3](https://user-images.githubusercontent.com/16892000/104402071-70242280-5590-11eb-90f4-7b473a1023fb.png)

For 2 -> 1 recipes, like silicon smelting:
![5](https://user-images.githubusercontent.com/16892000/104403038-9f3b9380-5592-11eb-8444-f0fb7024b310.png)
Only machines, conveyors, and power nodes are needed.

For recipes require more then 2 ingredient, people need to mix the ingredient somehow, which is a very simple and popular tech. The pyratite mixing in suggested style:
![11](https://user-images.githubusercontent.com/16892000/104403449-7e277280-5593-11eb-99a1-e3b667c03e34.png)
Or due to the quantization, this is possible to be simplified even more:
![12](https://user-images.githubusercontent.com/16892000/104403452-7ff13600-5593-11eb-9c53-b7f0c7dd6df9.png)

Something very handy but doesn't help very often:
![13](https://user-images.githubusercontent.com/16892000/104404109-e32f9800-5594-11eb-857b-b076e1a0b6c2.png)
But the suggestion introduces some "not intuitiveness". This structure stucks:
![14](https://user-images.githubusercontent.com/16892000/104404374-7963be00-5595-11eb-90a1-b2a6d577ee19.png)
![15](https://user-images.githubusercontent.com/16892000/104405599-4e2e9e00-5598-11eb-8026-e9de9b930d4b.png)

For the cases machine gives items directly into other machines, this suggestion affects almost nothing, unless the corresponding machine is somehow 1 by 1 tile big. According to all the schematic I have seen, this suggestion only simplified the very simple structures and does nothing to those consist of multi stage of crafting.

Anyway, this is way way way simpler than it is for now. People can literally focus on fighting and get more excited.

**Describe the changes you want to propose. Include possible alternatives.**
Everything that needs only input or only output is ok and doesn't need this improvement. This description includes drills, turrets. They are already good enough. This proposal affects only machines. 
I don't have any alternatives for now. But if you are interested in this and what I proposed in this thread is too wild and not very practical, let me know, I'll try inventing some alternatives.

Dirac Institute of Game 2021-01-11

**Comment by DeltaNedas** [comment]
when you router chain

**Comment by itcannotbe** [comment]
Is this another attempt at giving machines additional configuration options?

**Comment by GreyMario** [comment]
Could you explain this like I'm five?

**Comment by Yell245** [comment]
We have armored conveyors and junctions

**Comment by YagaoDirac** [comment]
> 
> 
> when you router chain

Routers mix ingredients and productions.

**Comment by YagaoDirac** [comment]
> 
> 
> Is this another attempt at giving machines additional configuration options?

I'm new to this game. I have no idea about the code or api at this moment. Any approaching is great. But if we need to set some config for every machine, it also needs a way to paste the config, which is very alike Factorio.

**Comment by YagaoDirac** [comment]
> 
> 
> Could you explain this like I'm five?

OK, I'll try upload some more concrete doc tomorrow.

**Comment by joshuaptfan** [comment]
You are still learning the game, and how to handle inputs and outputs optimally. I assure you that the game does not need anything like you are suggesting, once you get better at designing.

It's usually best practice not to mix belts, to avoid clogging. Each belt should be dedicated to 1 type of item. Do not place routers/distributors/junctions/overflow/underflow gates directly next to production blocks to use for input, as those blocks can input/output in any direction, which means that production blocks will output into them and clog your input lines. You should use conveyors facing into the block to input, and conveyors facing away from or parallel to blocks to accept output.

[This production guide](https://steamcommunity.com/sharedfiles/filedetails/?id=1935045318) is outdated, but provides better details with pictures.

**Comment by potatoisagender** [comment]
> People are forced to separate the ingredients and productions everywhere.

... Isn't that the point? That's how the game is played, and is part of the challenge. Look at how most factories are made, and you will realize that the people who made them do exactly this.

**Comment by GreyMario** [comment]
![](https://puu.sh/H65jO.png)

**Comment by itcannotbe** [comment]
> > Is this another attempt at giving machines additional configuration options?
> 
> I'm new to this game. I have no idea about the code or api at this moment. Any approaching is great. But if we need to set some config for every machine, it also needs a way to paste the config, which is very alike Factorio.

See above.

**Comment by YagaoDirac** [comment]
> 
> 
> Could you explain this like I'm five?

I didn't figure out how to quote an image. I know in such a game, what you high lighted is destined to be suggested a million times. But my suggestion is not about the direction or the concrete position(if the machine is 2 by 2 or 3 by 3 or even bigger). Mine is about the distance, and based on my exp in Factorio( a bit less then 2k hours, and I mostly focused on conveyor belts. I also 2 very famous inventions about the conveyor belts.). If you are still interested in my version, I'll edit the 1st layer of this thread. If this is not the case, OK, forgive me.

**Comment by scarf-generic** [comment]
none of the suggested mechanics are needed. once you become competent in item distribution, stop mixing conveyor belts, and gain a good grasp on the mechanics already in the game, you too will realize that this suggestion is pointless.
