### ISSUE TITLE
Select team before starting multiplayer game

### ISSUE THREAD

**Issue by eklann** [Anuken/Mindustry-Suggestions#1771]
**Describe the content or mechanics you are proposing.**
When starting a multiplayer game, it would be nice to be able to start through a lobby or similar. That way all players that want to join can connect, select teams, any settings can be visible etc. Then when the game actually loads, everyone is ready.

This is a feature I miss when playing PvP games with friends.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would make it much easier to play with friends, balance teams when there are new and inexperienced players etc. Also, it would make a game a bit mor fair to have both teams start out complete at the same time.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
what is a plugin

**Comment by laok233** [comment]
so why u don't use a plugin

**Comment by eklann** [comment]
What plugins are there that have this function?

**Comment by RedstonerKBC** [comment]
It can be annoying when you disconnect and reconnect only to find out it placed you on a different team.

**Comment by itcannotbe** [comment]
LeMmE dIsCoNnEcT aNd JoIn ThE wInNiNg TeAm.

**Comment by userlol2** [comment]
It just gonna cause more griefers

**Comment by Gussoh** [comment]
Sounds great to have a lobby like most other games. Makes it easier for the users to understand what happens as well. Perfectly fine to have a button in that lobby which just says [X] Random teams. I've also noticed that it is hard to understand what settings there are in a game as well. Perhaps this lobby should be visible so that you can see which plugins are loaded and what not also when joining a game after the game has started.

**Comment by Gussoh** [comment]
I'd argue that this feature request should not be closed just because it is not active. This is a great feature in my opinion.

**Comment by itcannotbe** [comment]
The bot is indiscriminate.

Also.....

### LeMmE dIsCoNnEcT aNd JoIn ThE wInNiNg TeAm.

**Comment by eklann** [comment]
The request is to be able to select teams *before* the game starts. I can't see how that would lead to "LeMmE dIsCoNnEcT aNd JoIn ThE wInNiNg TeAm". 

The request says nothing about what should happen when joining an ongoing game, but if anything I think is should be possible to disallow it entirely. Like how most other RTS games works.
