### ISSUE TITLE
Allow us to control parallaxes with logic and by going into it 

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry-Suggestions#1773]
**Describe the content or mechanics you are proposing.**

It’s sad that turret with potential like parallax cannot be controlled by logic.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Hundreds of new pvp schematics, better defences 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

no you didn't

#1726 #593 #1282

**Comment by Sanya2907** [comment]
I’m sorry!

**Comment by DeltaNedas** [comment]
why did you not search for "parallax" but also check the box?
