### ISSUE TITLE
campaign advancement

### ISSUE THREAD

**Issue by bestSuggestions** [Anuken/Mindustry-Suggestions#1774]
I would like to have something that allows you to see, to which destination the launchpads launch the items.

this could maybe be done with showing arrows (for example green) on the map that lead from the launchpad district to the receiving district on the map

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - X[] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kubek0212** [comment]
The title is very misleading, but the idea itself would be very helpful. I wanted to suggest that few days ago.
