### ISSUE TITLE
Limiting Launch Loadouts

### ISSUE THREAD

**Issue by don-tnowe** [Anuken/Mindustry-Suggestions#1775]
The change: the total amount of launched resources is limited, but the played can select which are. This means the player can choose to launch, for example, 2000 copper, or instead, 1000 copper with 500 lead and 500 graphite.

The reason: launching with maximum amounts of all resources can make clearing sectors trivial, especially when the player can just wait for them to replenish.

Providing a cap on total launched resources can provide an interesting challenge:

- Players get a choice when launching to a new sector: "Do I launch with more copper to get a more reliable start, or should I grab some rare metals to build strong defenses quicker?"
- No more starting with T5 unit offence/all-meltdowns defence. The need to actually produce resources makes players engage more with the production-defence balancing gameplay.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
No.

**Comment by Yell245** [comment]
Launch pads: lmao

**Comment by DeltaNedas** [comment]
lunch pad relays make this irrelevant as youll have a full core in a minute or so
otherwise i agree with it
