### ISSUE TITLE
Plastanium and Surge allow for colorblind users

### ISSUE THREAD

**Issue by Rayson-R** [Anuken/Mindustry-Suggestions#1776]
**Describe what you would like changed, and why.**
Statistic says that 10% of men and only 0.5% of women are colorblind, not much actually... 
Everything is just perfect in your lovely game, the only difficulty (for minor users) is to recognize Plastanium and Surge allow, they have the same shape and similar color (for sure it sounds ridiculous to people with normal color sense). It's easy to remember their positions in Unloader and Sorter but on Conveyors or in storage it's a challenge... All other items just easy to recognize, but those two I've to remake for every new release, that isn't a big job to me actually, but maybe help a lot to other gamers, who cannot reassemble the source code. 

**Describe the changes you want to propose. Include possible alternatives.**
Maybe just make one (Plastanium or Surge allow) mirrored - symmetric to another - so they will have a different shape. 
![item-surge-alloy](https://user-images.githubusercontent.com/77309745/104263700-b45bd980-544f-11eb-9be3-6a3dc3faa38b.png)
I see it's not the best solution at all - you know better. I cannot propose changing color because it's big change for majority of users, also hard to say which is easy to see for us. We have colorful  - not monochromic vision as some people believe, but some combinations of colors make problems to us.
Thank you for understanding.

Wish you great luck with the project
Thank you for such a nice job

**Comment by joshuaptfan** [comment]
Here is every resource in B&W.
![Resources BW](https://user-images.githubusercontent.com/15149002/104265535-ad7a9a00-5442-11eb-9021-9196c14f4944.png)
IMO metaglass, plastanium, and surge alloy are too similar to each other, as well as blast compound and pyratite. There are so many more possible shapes they could be.

**Comment by Rayson-R** [comment]
Thank you for your reply
It's a very popular delusion. As I mentioned, we have not monochromic but color vision, just difficulties with some shades - so B&W is even worse
also we can perfectly see metaglass and other items but only pair of plastanium and surge alloy are just the same
Thank you for understanding

**Comment by Humanoid-X** [comment]
good

**Comment by Yell245** [comment]
Maybe add some kind of vision defect mode? And if you enable it, some textures will have figures or other things to indentify them

**Comment by Humanoid-X** [comment]
Dunno... Maybe Setting->Graphics->ColorBlingMode ?

**Comment by joshuaptfan** [comment]
No need for any settings if a few shapes are just changed.

**Comment by Humanoid-X** [comment]
@joshuaptfan hmm good

**Comment by Rayson-R** [comment]
I didn't expect that is so complicated
Thank you for your attention and efforts

**Comment by Kyllingene** [comment]
I definitely agree. No reason to lock a percentage of the population out from the game needlessly.

**Comment by Rayson-R** [comment]
> 
> 
> I definitely agree. No reason to lock a percentage of the population out from the game needlessly.

Thank you for understanding

**Comment by Jammo2000** [comment]
This could be a bug. 10% accessibility is big.

**Comment by Rayson-R** [comment]
Hi all
I have no clue how many players are girls, but science says that only a little part (less than 1%) of women have violation of color perception and not such bad as men. Genetically...  If only half of players are men then let's say around five percent of us have that difficulty. I would love to read more feedback from players or better ideas than changing shape of the tile.
Thank you all

**Comment by Jammo2000** [comment]
Could editing the shading be a good solution?

**Comment by joshuaptfan** [comment]
[The plastanium sprite has been changed](https://github.com/Anuken/Mindustry/commit/81ce3a28a19adaaf457a626d713fdc68e80b442e?short_path=7c68ab4#diff-7c68ab4f37a73b7c109c800fe92bc2e36bfe268905535ffb7e5ba96a627fd956) to be more distinct.
