### ISSUE TITLE
Move water extractor from drills tab to liquids tab

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#1779]
**Describe what you would like changed, and why.**
Move water extractor from drills tab to liquids tab. There is no way that a water extractor is a *drill*, and it would fit much better in the liquids tab.

**Describe the changes you want to propose. Include possible alternatives.**
I don't see any alternatives[apart from ignoring this], since the liquids tab is where the water extractor would fit in the best.

**Comment by GreyMario** [comment]
The Cultivator is not a "drill" either, and yet it belongs in Drills too, as it produces a material from basically nothing.

Water pumps belong in the liquids section because they need to be placed on a liquid. Cultivators and Water Extractors do _not._

**Comment by itcannotbe** [comment]
It extracts water by drilling underground. Or maybe processing available water like resources on the tile.

**Comment by BlueWolf3682** [comment]
did you all forget oil extractors exist?

**Comment by itcannotbe** [comment]
> did you all forget oil extractors exist?

Moving the oil extractor to the liquid category is the stupidest thing anyone would think of in line of the currently discussed topic.

Why?

Simple answer: Fracking.

**Comment by BlueWolf3682** [comment]
exactly

**Comment by BlueWolf3682** [comment]
i just mentioned oilext cause we cant be oilextist lol

**Comment by Yell245** [comment]
These are not drills, these are **extractors**. They **extract** things: ores, water and oil, (digging underground), spores (from atmosphere). They all have special tiles where they just extract / increase efficiency

**Comment by XEN0PHIL** [comment]
Drill tab is "Resource extraction", it doesn't matter if it drills the ground or not.

**Comment by iLagSoUhax** [comment]
point taken

**Comment by wojtekpolska** [comment]
I know this is closed, but i'd still want to reconsider this. can i make a new issue for this?
