### ISSUE TITLE
Change Desert Wastes map generation so maps have enough lead/coal

### ISSUE THREAD

**Issue by sudobeans** [Anuken/Mindustry-Suggestions#178]
**Describe what you would like changed, and why.**
Desert Wastes in the Mindustry campaign often generates with little coal or no coal at all. This also happens with lead. Sometimes I need to reset so I can have a map with coal on it! 

I think Desert Wastes map generation algorithms should be changed so it generates with a fair amount of resources.
Here is a picture of a Desert Wastes map. The coal in the picture is the only coal on the map.
![20200517210551_1](https://user-images.githubusercontent.com/12636657/82173676-f877e980-9882-11ea-8f11-5b397846f453.jpg)

**Describe the changes you want to propose. Include possible alternatives.**
I think the Desert Wastes generation could use some sort of check on how much coal/lead is on the map. It would re-generate the map if there was not enough coal/lead on it.

**Comment by Anuken** [comment]
Desert Wastes doesn't exist in 6.0.
