### ISSUE TITLE
Cultivator Buff

### ISSUE THREAD

**Issue by SonPlaying** [Anuken/Mindustry-Suggestions#1780]
**Describe what you would like changed, and why.**
Cultivator Production. It produces slow, and also needs a lot of water. One water extractor produces 6 water. And one cultivator takes 12. Making power would be hard in a map with less coal and no water.

**Describe the changes you want to propose. Include possible alternatives.**
Decrease the production time, make it at least  1.25 second per spore. And decrease the water requirement.

**Comment by itcannotbe** [comment]
There are better ways to make power aside from using spore pods.

**Comment by RedstonerKBC** [comment]
Plants and fungi take time to grow. Even the fastest growing plant in the world only grows 3 inches a day.

**Comment by GreyMario** [comment]
![Screenshot_20210112-032317_Mindustry](https://user-images.githubusercontent.com/502797/104308452-8db89580-5485-11eb-8714-91cbb4d305d4.jpg)
This screenshot shuts down this "please buff cultivators" discussion entirely.

It's bad enough that this powercube exists. You want to make it even MORE powerful?

**Comment by Quick-korkc** [comment]
go search the sector that has lot of spore tile
usually they have spore storm which make cultivator more efficient
>Making power would be hard in a map with less coal and no water

water extractor and oil extractor exist
usually these sector is dessert type so oil extractor can works
make first power with solar panel

**Comment by RedstonerKBC** [comment]
I was wrong. Apparently some species of bamboo can grow 2 meters a day. Bamboo is something else lol. Anyways my point from earlier still stands since spores are not bamboo.
