### ISSUE TITLE
Ground Miner Units

### ISSUE THREAD

**Issue by SonPlaying** [Anuken/Mindustry-Suggestions#1781]
**Describe the content or mechanics you are proposing.**
Ground Miner Units. These units mine ores like Monos. They should be a little faster than Daggers.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will add miner unit variations. Also, when our mono unit has reached their limit, we can depend on the ground miner units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
> I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

nova branch be like

**Comment by Yell245** [comment]
Monos are air support units and novas are ground supports. Simply use processors or control units manually. You don't have to rely on units, you also have drills

**Comment by joshuaptfan** [comment]
[Here is logic to control ground units to mine.](https://steamcommunity.com/sharedfiles/filedetails/?id=2333571302) Using logic, you can have up to 120 mining units (monos, polys, megas, pulsars, quasars), excluding corvuses which can technically mine, but move too slowly.
