### ISSUE TITLE
Znajomi

### ISSUE THREAD

**Issue by Iskra-YT** [Anuken/Mindustry-Suggestions#1782]
**Describe what you would like changed, and why.**

Dodajcie możliwość dodania do znajomych

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by Yell245** [comment]
*inhale
What

**Comment by Yell245** [comment]
You didn't search good enough. There's already a suggestion about account system. Why did you remove template?

**Comment by Humanoid-X** [comment]
what?

**Comment by Humanoid-X** [comment]
![wtftf](https://user-images.githubusercontent.com/60562028/104329069-77fbac80-5527-11eb-8c57-3949a468e82e.png)

**Comment by Humanoid-X** [comment]
oh, im sorry, its polish.

**Comment by DeltaNedas** [comment]
install debian

**Comment by itcannotbe** [comment]
I command this suggestion to be closed by the power of #1473 !

Heck it even has the wrong template and label to begin with.
