### ISSUE TITLE
Plastanium walls refract laser beams, in a similar way to Phase walls

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#1783]
**Describe the content or mechanics you are proposing.**

A plastanium wall would refract the laser beam (with the length refracted being the maximum length subtracted from the distance before hitting the wall, at the opposite angle is was hit at [basically the mechanics for phase walls, but for laser beams.])

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would slightly debuff lancer/corvus, but it would be useful for preventing lancer spam in attack sectors, as depending on the angle, the beam has a high likelihood of hitting itself, meaning you would have to take measures to prevent itself from hitting itself.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by iLagSoUhax** [comment]
1. it's 'reflect', not 'refract'
2. it would be a little op, considering that the Corvus/Lancer lasers are strong

all in all, I'm not against it, but some method of balancing might be useful for this

**Comment by nichrosia** [comment]
> it's 'reflect', not 'refract'

No, refract means making a ray of light change directions, which is relevant for this case, as we're dealing with laser beams.
> it would be a little op, considering that the Corvus/Lancer lasers are strong

Yes, but it would become standard protocol to automatically prevent this, as phase walls already exist and can reflect Reign bullets right back at it.
> all in all, I'm not against it, but some method of balancing might be useful for this

Yes, I agree, this is just a suggestion, it is entirely subject to change.

**Comment by nichrosia** [comment]
For clarification, the dictionary definition of refract from Oxford is "(of water, air, or glass) make (a ray of light) change direction when it enters at an angle."

**Comment by Axzye** [comment]
How about instead it sends off short-range sparks which would be larger the higher the damage? Also makes more sense because plastanium is (presumably) an insulator.

**Comment by itcannotbe** [comment]
For clarification see:

https://www.britannica.com/science/light/Reflection-and-refraction

**Comment by itcannotbe** [comment]
For clarification, see:

https://www.britannica.com/science/light/Reflection-and-refraction

**Comment by RedstonerKBC** [comment]
As soon as I saw the first reflect/refract correction I knew this entire thread was going to be able the proper usage of those terms.

**Comment by SheepCommander** [comment]
lmao

**Comment by iLagSoUhax** [comment]
> For clarification, the dictionary definition of refract from Oxford is "(of water, air, or glass) make (a ray of light) change direction when it enters at an angle."

exactly. when it *enters* it from on angle. refraction is when light is bent through a medium while passing through it, whilst reflection is when it just touches the surface and bends.

**Comment by catatagun** [comment]
> > it's 'reflect', not 'refract'
> 
> No, refract means making a ray of light change directions, which is relevant for this case, as we're dealing with laser beams.
> 
> > it would be a little op, considering that the Corvus/Lancer lasers are strong
> 
> Yes, but it would become standard protocol to automatically prevent this, as phase walls already exist and can reflect Reign bullets right back at it.
> 
> > all in all, I'm not against it, but some method of balancing might be useful for this
> 
> Yes, I agree, this is just a suggestion, it is entirely subject to change.

Meltdown is are screwed

**Comment by Yell245** [comment]
But plastanium is an **isolation** material, not refracting like phase and bullets. See: energy nodes even need conscious connection, they can't magnetize energy into one net

**Comment by nichrosia** [comment]
> But plastanium is an **isolation** material, not refracting like phase and bullets. See: energy nodes even need conscious connection, they can't magnetize energy into one net

Ah, good point

**Comment by nichrosia** [comment]
> Meltdown is are screwed

What? Please explain further what this means.

**Comment by BlueThecno** [comment]
> 
> 
> > Meltdown is are screwed
> 
> What? Please explain further what this means.

I guess they mean that the meltdown in a 90 degree angle will just hit, burn and (possibly), destroy itself and everything behind it, and when it can't hit itself it would just destroy your things around it.

**Comment by Jammo2000** [comment]
Perhaps we could add a metaglass wall - very very fragile, but reflects lasers/laser bolts

**Comment by Kyllingene** [comment]
> Perhaps we could add a metaglass wall - very very fragile, but reflects lasers/laser bolts

#1786 is on this topic, although the opposition is pretty large.

**Comment by Humanoid-X** [comment]
Hmm, I don't think so. I mean plastanium can only absorb and not reflect. I think only things like metal can reflect... And metaglass must refract isn't it?
