### ISSUE TITLE
Core Incineration OP

### ISSUE THREAD

**Issue by SneakIrwin** [Anuken/Mindustry-Suggestions#1784]
**Describe what you would like changed, and why.**
Hello, big fan! Have about 90 hours in V5. I love everything about V6 so far EXCEPT the core incineration? Core incineration removes the necessity for sort/overflow networks going to the core. Creating these while having to adapt to the surrounding terrain was at least half the fun for me personally. Carelessness should not work well; that's so much of what makes this game excellent!

**Describe the changes you want to propose. Include possible alternatives.**
1) Remove or handicap core incineration.
2) Launch Pads could retain the opportunity for passive income.

**Comment by itcannotbe** [comment]
Find a substitute for computing passive core income first.

**Comment by SheepCommander** [comment]
Wdym? It makes it even harder, does it not? It means that you'd need to use logic to detect when the core is full and then re-direct the wasted resources to better use, such as a defense or factory

**Comment by itcannotbe** [comment]
Um..... The only reason why core incineration is a thing is because the game uses the constant flow of resources to the core to compute the passive income of that sector in campaign. This has nothing to si with M(industry)Log(ic)

**Comment by AnOreo1** [comment]
why not ask for a setting to turn it on/off

**Comment by SheepCommander** [comment]
No that wouldn't do. And itcannotbe ah makes sense

**Comment by AnOreo1** [comment]
ok but I'm just saying that would have been better than asking to remove something that almost everybody loves

**Comment by SneakIrwin** [comment]
@SheepCommander I've always just had factories and defenses supplied prior to the core, so I don't have much call for using logic blocks in that scenario.

I'm not super far into V6 yet so I can't say I'm totally familiar with this passive income mechanic yet. I immediately noticed I was having less fun constructing around my core.

Peeps really love the incineration huh? Do I just need to grind it out for some light at the end of the tunnel or something?

**Comment by AnOreo1** [comment]
yes because it prevents mass clogging and you always are gaining, there never is something blocking input.

**Comment by SneakIrwin** [comment]
@AnOreo1 that's what I mean though. In v5 I always found creating overflow networks that went to exporters a couple times then finally an incinerator was like the most fun thing ever. Not having to do that and adapt to the core's surroundings feels like too much of a nerf imo.

**Comment by AnOreo1** [comment]
but its called v6. there are giant metal spiders. naval battleships, router control. commanding units logic.

its just a new buff to the core, after all, all core units got nerfed, they suck on buildings.

**Comment by SneakIrwin** [comment]
I'm totally on board with v6 having its different priorities, and I think 95% of them have been really cool so far. But this game is still a routing and effeciency based challenge, and supplying your core is still at the heart of it. Maybe I need to play more to get a fuller idea of what passive income contributes but I'd still wager it could be done in a more fun way if it wasn't generated via core incineration.

**Comment by AnOreo1** [comment]
but no

**Comment by SneakIrwin** [comment]
oh

**Comment by AnOreo1** [comment]
dont ruin v6 please, its fine, just some minor rebalance changes are all thats needed

**Comment by AnOreo1** [comment]
core inceration is not one of them, the core units got nerfed to compensate and everybody liked that

**Comment by SneakIrwin** [comment]
I'll keep playing more to see what additional conclusions I can draw. I enjoy that few things in this game are just taken care of for the player, core incineration's current state feels like an injury to that. But like I said, I'll put in some more time and try to have an open mind about it.

**Comment by AnOreo1** [comment]
ok


router

**Comment by itcannotbe** [comment]
Core units just don't damage building as much because it's damage is lowered to 3% if a core unit is shooting at a building.

This is just so that you cannot realistically rush the enemy with just a core unit.

Core incineration has nothing to do with the above.

**Comment by AnOreo1** [comment]
wrong 1% damage.

says it in the unit stats

**Comment by itcannotbe** [comment]
Typo. It is 1% LOL. Need to edit that..,.

**Comment by itcannotbe** [comment]
So basically you need to have 100x more units to deal the same damage as you would to another unit to buildings.

**Comment by AnOreo1** [comment]
besides core units arent good at all, I dont see any logical reason for this change other than to case pain and anger

**Comment by RedstonerKBC** [comment]
You know I've been getting non-stop notifications for days about having router-trains removed entirely and core-incineration solves this problem by letting noobs/bored players do whatever they want.

**Comment by AnOreo1** [comment]
everybody was a noob at once and routers should never be touched for they are perfect

**Comment by GreyMario** [comment]
Core incineration is _not_ "overpowered", it's "Occam's Razor to the problem of _how do you measure production rates once the core is full_ so that your bases will continue to replenish their resources once you have used them all up for research_".

End of discussion. This never should have reached five comments, let alone twenty-five.

**Comment by SneakIrwin** [comment]
~which is why I propose utilizing export buildings similar to the way V5 did. It worked great.

**Comment by AnOreo1** [comment]
why is this still going

**Comment by SneakIrwin** [comment]
I was being sassed :p

**Comment by AnOreo1** [comment]
oh

**Comment by GreyMario** [comment]
> ~which is why I propose utilizing export buildings similar to the way V5 did. It worked great.

Did you mean: ***Launch Pad***

**Comment by AnOreo1** [comment]
launch pad, wish we had large one

**Comment by SneakIrwin** [comment]
Yeah Launch Pad, sorry. I couldn't recall the name, it's been a few months.

**Comment by itcannotbe** [comment]
The problem with that idea is the use of the launchpads are different comparing v5 and v6.

**Comment by AnOreo1** [comment]
can we let this thread die

**Comment by notrealn** [comment]
I kind of like the core incineration, whenever I play multiplayer with friends its really annoying how you can't have any mixed lines and stuff will clog if you have 1 copper in the titanium line.
> Creating these while having to adapt to the surrounding terrain was at least half the fun for me personally.
It kind of is a pain for me on some sectors.

**Comment by SneakIrwin** [comment]
@notrealn it'd really make more sense to keep incineration in multiplayer if anywhere. In general, a handicapped incineration on ALL buildings would also be cool for the jam reason you mentioned.

**Comment by notrealn** [comment]
> handicapped incineration

what does that mean? only a certain amount of items can be incinerated per second?

**Comment by AnOreo1** [comment]
can this die this has 38 comments what

**Comment by AnOreo1** [comment]
I'm confused how you can't just accept that it won't be changed, this is like trying to reason with shoving your hand in a blender, nobody else wants to do it but you

**Comment by SneakIrwin** [comment]
@notrealn Firstly yes, handicapped=capped incinerations/second. Second yeah sorry I originally had better description in the op suggestion, but decided it was too unrelated. For general buildings I thought it would be cool if they *slowly* incinerated incompatible resources, not just anything that happened to be stacked at all.

**Comment by SneakIrwin** [comment]
@AnOreo1 I can assure you in today's America a LOT of people want to shove their hand in a blender.

**Comment by AnOreo1** [comment]
wait they do?

**Comment by SneakIrwin** [comment]
Oh yeah, trust me.

**Comment by AnOreo1** [comment]
then uhh I guess my example is ruined but this needs to stop dragging on

**Comment by SneakIrwin** [comment]
I am here as a personal torturer for the poor wanderers of this thread.

**Comment by AnOreo1** [comment]
this is getting utterly stupid so I'll stop commenting but I'll watch you torment

**Comment by CoinCaribou2070** [comment]
one more comment

**Comment by AnOreo1** [comment]
not you too why we work together

**Comment by CoinCaribou2070** [comment]
guess this is the final comment

**Comment by CoinCaribou2070** [comment]
one more to make it 50 comments lol

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/pull/4264#issuecomment-765478615
