### ISSUE TITLE
Fragile and energy resistant wall

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#1786]
**Describe the content or mechanics you are proposing.**
A fragile but is immune to energy weapons such as corvus lasers, fuse beams and nova beams (if thats what you call it) by redirecting the lasers/beams to opposite direction, i think it would be made out of pure metaglass and would be a little transparent on the ground, although it would more likely to have lower health than titanium wall and the enemy lasers/beams shouldn't damage the enemy

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Much more interesting pvp and attack maps, interesting gameplay and more use to metaglass

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by rMuchan** [comment]
how is it better than plastanium wall?

**Comment by AnOreo1** [comment]
so a phase plast wall?

**Comment by userlol2** [comment]
1. metalglass wall better than plastinium wall is unbalanced
2.imagine reflex a corvus attack with some metalglasses

**Comment by GreyMario** [comment]
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

that's a lie fam

**Comment by Yell245** [comment]
Plast walls absorb energy beams already

**Comment by Humanoid-X** [comment]
What you are trying to say,  is to make metaglass better than plastanium.
Yeah, I agree. That's VERY logical indeed.

**Comment by WinterCrystal** [comment]
Plastanium wall absorbs energy beams, they exist already. I don't see the point of having a fire resistant wall when the only unit that has the ability to make fire is the Atrax, and it's not even a guarantee that it can do it all the time, and even if you have a fire outbreak happening, just deleting the blocks that are on fire can prevent it from spreading, or you can use water filled waves/tsunamis.
