### ISSUE TITLE
Multiple game profiles

### ISSUE THREAD

**Issue by abomb4** [Anuken/Mindustry-Suggestions#1787]
**Describe the content or mechanics you are proposing.**

Players can choose a profile, each profile has different researching progress, settings, mod configuration and saves.
Just like 'Person' in Chrome.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Mods may damage campaign saves. So if we can choose profiles between mods and no mods, mod players can freely switch between multiple mods without worrying about saves data corruption.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (The most similar suggestion is "Multiple campaign saves #913", but there are some differences)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheRealIvyX** [comment]
this is technically already in the game since you can export and import game data

**Comment by abomb4** [comment]
> this is technically already in the game since you can export and import game data in the settings

Some people may switch mods frequently, sometimes forgetting to open a necessary mod, will cause data corruption.
In this scenario, players must often import and export archives. I think if we can switch directly on the game menu, it will be much more convenient than import and export...

**Comment by DeltaNedas** [comment]
`man git-checkout`
or have $XDG_DATA_HOME/Mindustry be a symlink to a profile

**Comment by abomb4** [comment]
> 
> 
> `man git-checkout`
> or have $XDG_DATA_HOME/Mindustry be a symlink to a profile

More complex... And Steam game data is not in that path.
I believe that most players and even experienced players cannot do this, git, $XDG, %APPDATA%, etc.

**Comment by DeltaNedas** [comment]
then rtfm

**Comment by ThatOneBepis** [comment]
Ok lets be honest here. Thought there is campaign save data and that its accessible in the options menu, it would indeed be a QoL for the game to be able to create copies of said data (ie. multiple saves of a single campaign). Plus, like how it works with servers, if a mod exists/n't outside of the already defined list, which is decided when said campaign save is made. just prohibit it from said campaign being launched. This won't really work if the existing campaign has mods installed, but would be something. This also may extent to creating blank campaign saves containing a combination of mods that currently doesn't exist in an existing campaign, of if player wishes so.

**Comment by Kyllingene** [comment]
I like this.

**Comment by iLagSoUhax** [comment]
Agreement noise.
