### ISSUE TITLE
AI attacker are norhing just a bunch of idiots. 

### ISSUE THREAD

**Issue by agergo100** [Anuken/Mindustry-Suggestions#1788]
These AI attacke have zero IQ. 
These bots are building blind. 

They should be smarted up.

- More construction plans 
- Faulty structures repair and (or) develop 
- Map smarter to analyze

**Comment by Yell245** [comment]
Mmmmmyess why do we need template

**Comment by Yell245** [comment]
It's still in progress. Anuke will add it in further updates. What did you expect? It's not a simple tower defence with locked path, it's a sandbox game where there are many combinations available

**Comment by agergo100** [comment]
I know, but if you test it on an open empty map, they'll build it blindly.

**Comment by catatagun** [comment]
TEMPLATE IS GONE

**Comment by itcannotbe** [comment]
The game is laggy enough with a stupid ai. Now you're saying you want it smarter? That's not's an easy feat to do.

**Comment by marky0470** [comment]
I agree with @itcannotbe, AI takes a decent amount of computing power to execute, not to mention an AI whose environment is constantly changing as it constructs more buildings.

**Comment by Humanoid-X** [comment]
Agree with @itcannotbe. They are just AI, what do you expect

**Comment by WinterCrystal** [comment]
This is such a vague suggestion, and also, where is the template? Anuke added a template for a reason. Also, making the AI "smarted up" is a hard thing to do especially when the game only has a single developer.
