### ISSUE TITLE
Серебреный реактор

### ISSUE THREAD

**Issue by kots532** [Anuken/Mindustry-Suggestions#1789]
Серебряный реактор будет работать на серебре потребляет 1 серебро вырабатывает 5 энергии в секунду

**Comment by XEN0PHIL** [comment]
1. Ты удалил весь шаблон;
2. В игре нет серебра;
3. В игре хватает реакторов, работающих различными способами;
4. Используй моды.

**Comment by Kyllingene** [comment]
> 1. Ты удалил весь шаблон;
> 2. В игре нет серебра;
> 3. В игре хватает реакторов, работающих различными способами;
> 4. Используй моды.

Все это правда. Пожалуйста, если вы не можете понять шаблон, потому что он на английском языке, переведите его.

**Comment by userlol2** [comment]
1.no template
2.english only

**Comment by Kyllingene** [comment]
> 1.no template
2.english only

1. нет шаблона
2. только английский
