### ISSUE TITLE
Making solar power a viable form of energy production.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#179]
**Describe the content or mechanics you are proposing.**
A solar power tower.
https://en.wikipedia.org/wiki/Solar_power_tower

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would be using tier 1 and/or tier2 solar panels in constructing them thus giving use to relatively unused blocks.

The tower would be generating power proportionate to the number of solar panels around it to a certain degree and their base energy production and water availability (Water would also be a limiting factor to it's production similar to how the fullness of the thorium reactor is with regards to thorium stored).
The setup would be similar to this IRL structure:
https://en.wikipedia.org/wiki/Crescent_Dunes_Solar_Energy_Project#/media/File:Crescent_Dunes_Solar_December_2014.JPG

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
this totally reminds me of an early game io survival on boxfort, where an idiot spammed 10k solar panels and murdered silicon.

**Comment by itcannotbe** [comment]
At least you would have to murder silicon to get a decent amount of power with this.
