### ISSUE TITLE
Swarmer ammo multiplier buff

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry-Suggestions#1790]
**Describe what you would like changed, and why.**

It would be nice if the ammo multiplier for swarmer was increased especially with surge/pyratite. Currently with the 2x ammo multiplier one surge/pyra gives you two individual missiles out of swarmers volley of 4. With one blast compound you get one full volley of missiles. Due to swarmers having 8 shots/sec it effectively uses 2 blast, or 4 surge/pyra every second with no buffs. 

This is extraordinarily expensive considering the slow production rates of its ammo types. One pyra factory produces every 1.3 seconds meaning you need at least five in order to have one swarmer firing at 100% at all times. With surge its the same thing. 5 surge factories for one swarmer to fire at all times. Yes buffers exist in the form of vaults. But this is still only ONE swarmer that is not being buffed with an overdrive/water/cryo

With cryo you need to have 7.2 pyra/surge per second, or 3.6 blast/sec for one swarmer

With cryo and an unboosted overdrive you need 10.8 surge/pyra per second, or 5.4 blast/sec for one swarmer

With cryo and overdrive dome you need 18 pyra/surge per second, or 9 blast/sec for one swarmer 

This is absolutely ludicrous. Depending on how many swarmers are in your defence it is nigh impossible  to actively feed them all. Just 12 swarmers fed with pyratite/surge require you to have a total input of 216 items per second with a max boost. With blast this number is halfed to 108 items per second in total. Swarmer uses more ammo than a plastanium Cyclone, which also is a 2x ammo multiplier.

I understand that having 12 swarmers with a max boost does kill an oct in around 6-8 seconds, but that uses around 1200 surge with 12 swarmers at max boost. Currently you can easily achieve the same thing with 5-6 spectres with cryo and ODD for a significantly less amount of ammunition, even less if you replace the spectres with foreshadows, and both of said turrets are capable of doing so at a much much further range and lead to a much more effective defence.

The fact that this 2x2 turret uses this much ammo is completely stupid and need to be changed to be more ammo efficient, otherwise it is easily outclassed by a salvo, scatter, or anything else due to you not needing to have an insane production 

**Describe the changes you want to propose. Include possible alternatives.**

Double or triple the ammo multiplier on the swarmer turret for all 3 ammo types in order to actually make the swarmer useful as a midgame turret. At this time it is hardly ever used period. Yes I saw a pr that increased its range slightly which was very good. But its not good enough if 12 can use 1200 surge/pyra in around 7 ish seconds

One or two full volleys of 4 missiles should be good per one unit of ammo. Not two ammo for 4 missiles.

**Comment by the-red-soul** [comment]
![image](https://user-images.githubusercontent.com/31638088/104532867-7638f400-55ce-11eb-9c95-417c9daea3ce.png)


this is the 12 swarmer schematic if anyone was really interested in it. no im not giving you a direct schematic. And with all the swarmers firing it does exceed the amount the single item source can give you with an odd on it.

**Comment by claw4oo** [comment]
I do agree, swarmers eat up insane amounts of ammo in a very short amount time. Having something much more modest like 4 swarmers in a line with normal overdrive is also extremely ammo hungry, and inpratical to use/feed.
