### ISSUE TITLE
(logic) allow unit locate to locate enemy spawns

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1791]
**Describe the content or mechanics you are proposing.**
add enemy spawns as an option to unit locate

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
more logic options

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by laok233** [comment]
im pretty sure it already exists

**Comment by Kyllingene** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

![spawnlocate](https://user-images.githubusercontent.com/69094702/104665529-798fb680-5686-11eb-9e6b-723abc95383e.png)

please close

**Comment by Sp3rw3r** [comment]
This works, but does not return radius. Approach with radius 32 often works, but spawn size is not always same.

**Comment by Ilya246** [comment]
was quite sure it didn't exist

**Comment by joshuaptfan** [comment]
You can order them to move to the center of the spawn, and they will be repelled at the radius.

You can also "unbind" them (there are ways) so that they follow their default behavior, which for attack units, is to go to the edge of the spawn.
