### ISSUE TITLE
 Code project "Moon"

### ISSUE THREAD

**Issue by Goc1n** [Anuken/Mindustry-Suggestions#1792]
**Describe the content or mechanics you are proposing.**

Moon project with a small story about the past of our hero.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
At the beginning of the game, our character appears in a place with the core and the Boers, there is no plot in the game, but it is unknown about the character's past and how he got here. I suggest that after passing a certain location, we learn by chu-little who we are, who are the enemies and what purpose, our past, as well as the goal and past of the enemies that fall on us and build a base. Gradually, we learn that this planet is one of the few on which our civilization lived and it was attacked, our planet is colonized (locations with enemy bases). We are fighting for the life of our species and after the liberation of the Planet we move on to the liberation of our satellite Moon. Our main character understands that the battle is not the right way and everything needs to be resolved peacefully, see the civilization of our character has achieved such success thanks to love and help to each other. But love did not come immediately and the "Earthlings" fought for a long time, someone from outside may be GOD or the higher cosmic mind directed us, but we still do not know who it is, and after long wars they united for common goals and development. Our character understands that enemies also need to understand what love is and show them the true path.
This is just a concise story and it is you who can change it or take it as a basis to improve the content in our favorite game.
2-3 question with an X in part.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
there is no lore, only cat god

**Comment by Anuken** [comment]
> characters

Mindustry has intelligent systems, but it does not (and will never) have characters.

**Comment by catatagun** [comment]
Mindustry lore is oh planet look cool i visit there

Oh no i am in danger

**Comment by Yell245** [comment]
Lore is actually very easy to understand if reading descriptions. Cores can self-replicate thus colonising other sectors to mine more resources. We also have Interplanetary accelerator which is launching cores to other planets. I think in further updates planets will be like islands in "Forager" - 1 island = 1 story. Also, our avatar and player are not the same thing. Probably player is a commander of this hive and that's why our avatar is not like others

**Comment by BlueThecno** [comment]
The idea of self-replication comes at hand with Bon-Newmann (I'm pretty sure I wrote that wrong)  probes, so a good idea would be finding out about who was the original creator, and the crux looks like a group that (by deviation of the original programming) decided to become it's own group that sees the player's group (the shardred) as enemys.

Thats my idea tho.
