### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Fnaflover2** [Anuken/Mindustry-Suggestions#1795]
How to delete this?

**Comment by Kyllingene** [comment]
1: You deleted the template (found at the bottom of this comment); Anuke will ignore this and people will ridicule you unjustly for deleting it.
2: Please, PLEASE explain what you mean by 'bots' and how you might implement them. Anuke will most likely ignore this otherwise.

Template (literally just do what the boxes tell you and format your post ever so slightly to fit it):
```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by joshuaptfan** [comment]
Robots? [This game has tons.](https://mindustrygame.github.io/wiki/units/0-dagger/)

**Comment by itcannotbe** [comment]
Anuke be like:

incredible. nobody has ever even considered suggesting More bots before. this is a revelation. I would never have thought of adding More bots myself. this idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More bots immediately.

**Comment by SheepCommander** [comment]
This sounds like a memepost if you ask me

**Comment by Kyllingene** [comment]
> Anuke be like:

For clarification, that is a slight reformatting of an actual comment he made. Specifically, on a "More Turrets" post.

**Comment by iLagSoUhax** [comment]
I'm conflicted as to whether this person is actually incoherent enough to suggest with no template or this is a meme post

**Comment by iLagSoUhax** [comment]
also @Fnaflover2 please close this issue, since anuke will no longer close or comment on these, and make a new one with a touch more template if you're serious.

**Comment by DeltaNedas** [comment]
troll post, do not respond to him
