### ISSUE TITLE
Item taking from T1 unit factory

### ISSUE THREAD

**Issue by RedRadiation** [Anuken/Mindustry-Suggestions#1796]
**Describe the content or mechanics you are proposing.**
The ability to take items from T1 unit factories as units.
Add or combine the existing item taking, unit type select UIs.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently T1 factories are the only ones players can't retrieve resources from.
It would only make sense if the action was possible. Making it easier to micro resources when they are scarce.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
This would be nice, it's good to have consistency.

**Comment by BlueWolf3682** [comment]
bridges and junctions and mass drivers:

**Comment by sample-text-here** [comment]
unloaders?

**Comment by Jammo2000** [comment]
No, directly with units.

**Comment by Kyllingene** [comment]
Good luck making the UI look nice. As Jammo2000 said,

> it's good to have consistency.

No other block UI has multiple sections, and thus this would be out-of-place and weird-looking. No problems with the actual suggestion, just the necessary steps. It is how it is for a reason.

**Comment by Humanoid-X** [comment]
good idea
