### ISSUE TITLE
Processor bug

### ISSUE THREAD

**Issue by qjxtony** [Anuken/Mindustry-Suggestions#1798]
![Screenshot_20210115_153752_com.discord.png](https://user-images.githubusercontent.com/72866113/104695399-a8ba2c80-5747-11eb-8c55- -ff494bf25e58.png)

Sent to anuke on discord already.[]()

**Comment by BasedUser** [comment]
Use Anuken/Mindustry for such reports.

**Comment by Cherriodude** [comment]
You should post it here:
https://github.com/Anuken/Mindustry/issues/new?template=bug_report.md
Instead of here.
