### ISSUE TITLE
Missile silos

### ISSUE THREAD

**Issue by smolkaguya** [Anuken/Mindustry-Suggestions#1799]
**Describe the content or mechanics you are proposing.**

Missile silos that fire missiles to enemy. Some missiles can be controlled by the players. They can deal a blast damage to the enemies and the can pass walls. It need missiles as it's ammo. They can take 5 seconds to refill. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche**

Right now air units are overpowered. Missiles can balance that out by destroying multiple air enemies

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
guess what frag ammo in a cyclone does

**Comment by TheRealIvyX** [comment]
seems like someone doesn't know what a "scatter" is.

**Comment by Quick-korkc** [comment]
missiles? use swarmer
air-only def? check all turret description
air unit crashing into defense? wave and tsunami
>I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

i doubt it

**Comment by smolkaguya** [comment]
@Quick-korkc what i meant was it kinda like this
https://www.reddit.com/r/Mindustry/comments/kxrdhp/haha_missiles_go_brrrr_vozduh_is_amazing_at/?utm_medium=android_app&utm_source=share

It's not air only def. 

@TheRealIvyX That doesn't mean Anuke can't add more defense. With air units like this anuken can add more powerful units. Maybe I am wrong about air units being overpowered.

**Comment by sample-text-here** [comment]
the closest thing to meep's missile silos are ripples. they aren't missiles, but
- ripples can be controlled by the player (like almost all other turrets)
- they can pass over walls
- not sure what you mean by blast damage. if you mean area damage, rippes do that
- it takes a 1-2s to reload
- but **ground only**

if you want missiles, use swarmers
- they actually shoot missiles
- can target ground and air
- *very* good at taking out air units
- reloads quickly, but uses tons of ammo quickly
- cannot go over walls

if you want the best overall air defence, use cryo-cooled surge cyclones
- very expensive
- a pair of them took an eclipse out in about 15 seconds from my testing
- the same pair destroyed 50 flares in a second
- more than enough for air defence, if you can afford them

also, you gave a link to a mod preview and said "i want this to be in mindustry". why don't you just... install the mod? (meepoffaith/progressed-materials)
