### ISSUE TITLE
make emoji usage outside ingame easier

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#18]
**Describe the content or mechanics you are proposing.**

Currently there are `(char)` emoji's, they work great inside the game, but not so well outside.

I propose adding something similar to how colors work, e.g. `:titanium-conveyor` / `:icon-star:`

Since currently bundle/config/etc outside the game appears as strange chars, it would be nice to be able to "see" which one was used in e.g. the console, its of course possible to modify the jar or do this via a plugin, but native support would be preferable:
<img width="655" alt="Screen Shot 2020-03-05 at 10 55 56" src="https://user-images.githubusercontent.com/3179271/75969921-eca99780-5ecf-11ea-871e-393638bd9220.png">

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Makes it easier to recognize/use emojis in configs/chat/bundles by having textual shortcuts.

**Before making this issue, replace the underscores in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
Is this still needed?

**Comment by Quezler** [comment]
> Is this still needed?

i don't recall it having changed?

**Comment by Quezler** [comment]
👀
