### ISSUE TITLE
6.0 launchpads mechanic

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry-Suggestions#180]
**Describe the content or mechanics you are proposing.**
I propose that there would be an extra space either on sector 0, or somewhere off the planet, where launchpads deposit their contents. This is a normal area, except there are no enemies. There is a core, or a launchpad station, which accepts launchpad contents. In this limited area one has to build a containing mechanic. The resources button in the sector selection brings the player here. There could be a reverse launchpad, which unloads the launch station. Reactor explosions are disabled. There are ores, and the launch station requires power. Solar panels cannot be used. This also solves #45. In the tech tree, if one wants to unlock something, it drains resources from the core in this area. If there are not enough resources, then future launches directly apply to the tech tree, without unloading. Also on normal levels, add a reverse launchpad that unloads this area.
![Screenshot from 2020-05-18 11-20-33](https://user-images.githubusercontent.com/53530661/82196253-c2298100-98f9-11ea-8b88-c0f0e5847120.png)
This sketch shows the extra area. the small launchpad represents the receiver, which will receive normal launchpad contents. The large one sends these resources evenly on every sector with a launch receiver. The resources in the core will be used for the tech tree. There are random ore patches, and the player is not able to make a schematic and share it, because the pad requires much power, which is up to the player to solve. Maybe there could be expansion areas, that can be unlocked by buying, draining resources, or even destroying the enemy core there, by creating an attack map, by random generation. Or there is a door, which cannot be walked through by enemies, but one has to conquer this area to expand. Something like:
![Screenshot from 2020-05-18 11-37-02](https://user-images.githubusercontent.com/53530661/82197962-eede9800-98fb-11ea-9e09-c5a051bbb752.png)
This is also a sketch. Enemies cannot shoot or move over the wall, and the player cannot also, but can build turrets in the enemy area. The doors and all structures in that area get removed when the enemy core is destroyed, and is then safe to build to.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make the players think, to make the most efficient storage. Sometimes the player has to switch to it to get thorium for example, if it is not present in that area, and requires it.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I know there is a similar idea in Trello, I just tell how could it look like.

**Comment by itcannotbe** [comment]
#152

**Comment by bluet-it** [comment]
Okay, minus reverse launchpad. But is it basically good?

**Comment by nichrosia** [comment]
Yeah, #152  failed
