### ISSUE TITLE
shield detecion adding should be useful.

### ISSUE THREAD

**Issue by qjxtony** [Anuken/Mindustry-Suggestions#1800]
**Describe the content or mechanics you are proposing.**
Logic command to read shield in units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, the commands can only detect health in units, so when a unit has a high strength of shield, it could be useful to show it if shield can be detected.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
good
