### ISSUE TITLE
Unit boost status detection

### ISSUE THREAD

**Issue by BlackDeluxeCat** [Anuken/Mindustry-Suggestions#1802]
**Describe the content or mechanics you are proposing.**

Logic command to detect unit (nova, pulsar, quasar, vela) boost status.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Sensor can't detect unit boost status.
Detection of boost status is useful to unit's attack, move control. Complex actions on specific tiles (such as deep water, slag) will be also possible.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
> Complex actions on specific tiles (such as deep water, slag) will be also possible.

i think what you want to do with logic needs a different suggestion - detecting the floor of a tile with logic. i'm not sure how unit boost detection would help

**Comment by Jammo2000** [comment]
For logic unit control, check if player is boosting and boost other units.

**Comment by liuxilu** [comment]
It's done, close this then.
