### ISSUE TITLE
Building Adjustments

### ISSUE THREAD

**Issue by Parkman145** [Anuken/Mindustry-Suggestions#1803]
Currently, the options you have for building, has a decent amount of options, but I feel there is a lot more that could be done. One feature I'd like is a drawing tool that conforms more to the path of your cursor/finger, rather than just the shortest path between the start and the end. 
Another one, that is less important but still would be nice to have, is a mode where the path would conform very closely to obstacles, like shrinkwrap-ing around it. This would make it a lot faster to build thinks like conveyor belts that sort of stick to a wall to save space and for organization. 
Another minor problem that I had was that when I had electric buildings in schematics that are connected to other buildings, when building the schematic, it wouldn't seem to save the connections. I know this one isn't a feature, but I didn't want to make a whole new request, and I felt it fit in here.

**Comment by Kyllingene** [comment]
1: Please use the template. People will ridicule you for not doing so, and Anuke will filter it out. It is at the bottom of this comment.

2: The suggestions seem reasonable (although the first might not get implemented), so I agree. +1

**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**


```
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
5. ```

**Comment by Jammo2000** [comment]
The first thing, the placing blocks following the cursor path, would be nice to see implemented. It would make it so much easier to place conveyors exactly where you want them.

**Comment by sample-text-here** [comment]
i found a similar suggestion: #1615

anyway, i think this would be a nice feature to have

**Comment by joshuaptfan** [comment]
> Another minor problem that I had was that when I had electric buildings in schematics that are connected to other buildings, when building the schematic, it wouldn't seem to save the connections.

In 6.0, power connections are saved in schematics, however they are useless because power nodes will still connect to whatever they can before the schematic has finished building. I will make a suggestion to resolve this problem later.
