### ISSUE TITLE
Weather Mechanics

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1805]
**Describe the content or mechanics you are proposing.**
Rain: Exposed slag tiles (so not ones covered with thermal generators/pumps) and slag puddles produce a steam particle effect. Rain also slowly puts out fires.

Snowstorms: The same as rain but with more particles.

Sandstorms: Puts out fires but does not cause slag to produce steam particles.

Sporestorms: Causes exposed slag tiles (so not ones covered with thermal generators/pumps) and slag puddles to catch fire. Causes active fires to last longer and/or do more damage.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Slag is basically lava so it can't be put out by water just like in real life. All this is is a graphical effect that occurs when it's raining/snowing.

With the fires, normally fires can't be put out unless you have waves/tsunamis so this adds that. Fires usually destroy buildings before players can put them out. Rain/snow/sand adds a mechanic so that players who target flamable buildings during weather events can't rely on the fire to do most of the damage.

Spores increase the fire hazard by fueling the flames. Spores are already highly flamable so this makes sense. Sporestorms are a rarely used weather event in maps anyways. I know thermal generators could then catch fire but most maps tend to use heated rock tiles since you don't have to place thermal generators on the shore.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
i like it

**Comment by Humanoid-X** [comment]
oh good

**Comment by catatagun** [comment]
Very nice

**Comment by SheepCommander** [comment]
I like it too. But maybe snow should have a more amplified effect than Rain, since it could only snow if it's a lot colder? Or what that be leading into a completely separate mechanic for temperatures

**Comment by blahblahbloopster** [comment]
Perhaps snow could also increase the effectiveness of thermal generators due to the heightened temperature differential?
