### ISSUE TITLE
new dimension thats basically the old campaign

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1806]
**Describe the content or mechanics you are proposing.**
this is gonna sound like a lot but i promise you it wouldnt be a monster to code.
the idea is, after unlocking phase fabric, and beating a lategame level (desolate rift, impact, or nuclear) you can build an "interdimensional gateway" block. 
it'd be about 5x5, or something around that size, and cost lots of power - around 5-10k per second. if adequately powered it'd look like space tiles, but with orange nebulae instead of purple.
clicking it would display a window, like a unit factory or command center does. it would read something like "traverse dimensions". clicking it would send you to the serpulo view, except nothing is visible but ground zero, and the nebulae surrounding the area is orange (or any color that'd look good) instead of purple.
there'd also be an icon that looks like the portal, and clicking it would take you back to viewing normal serpulo and your captured zones. but you can only enter the new dimension by clicking the portal you built.
this new area would be like the 5.0 campaign - sectors are never captured, waves are endless, and there are launch waves. areas are unlockable but only the points of interest. its impossible to go to the other sectors. launched resources stay in a resource poo that can be used for research, etc. completing it would'nt yield any rewards back at normal serpulo.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this sounds like a lot but why i think this is a good suggestion is because when you released 6.0 the old playstyle of "lets see how long i can last" vanished. you can have a sector constantly under attack but the process is much slower than endless waves and thats if an enemy base is next to it. a lot of people loved the endless waves and people flexed their desolate rift builds but that all vanished with v6. this is a way to bring that back - maybe not for all players, but the players that loved the old campaign - and players that wanna give it a shot.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
> i promise you it wouldnt be a monster to code.

"interdimensional portal" "a whole different set of campaign"

**Comment by Kyllingene** [comment]
1: The glaring issue here is *storing and playing a campaign inside the campaign*. Forget the massive amounts of storage taken up by *two campaigns*, but think about mobile players playing *two campaigns*. Goodbye, sweet RAM.

2: The other issue is *making a campaign inside the campaign*. How on EARTH would one manage that? Well, you could make it go to a hidden menu screen - but that removes you from your map. That would be aggravating in many ways. Well then, let the map play while you fight endless waves! That won't destroy everything you've been working towards!

The better way to handle this is to make a handful of campaign maps that use the old systems. Preferably, they would be maps that we don't already have remasters of in the new campaign. And you need to realize that *you cannot hold onto the past* for too long. Especially the digital past. Bloating the game with an impossible-to-implement (forget balance) campaign just so that you can play it is not a good way to go about it. I would prefer that Anuke (or someone else) simply makes a backup of v5 without the multiplayer. That way, you have both worlds, but without the absolutely terrible bloat to the game that would come from this.

**Comment by sup3r87** [comment]
> 1: The glaring issue here is _storing and playing a campaign inside the campaign_. Forget the massive amounts of storage taken up by _two campaigns_, but think about mobile players playing _two campaigns_. Goodbye, sweet RAM.
> 
> 2: The other issue is _making a campaign inside the campaign_. How on EARTH would one manage that? Well, you could make it go to a hidden menu screen - but that removes you from your map. That would be aggravating in many ways. Well then, let the map play while you fight endless waves! That won't destroy everything you've been working towards!
> 
> The better way to handle this is to make a handful of campaign maps that use the old systems. Preferably, they would be maps that we don't already have remasters of in the new campaign. And you need to realize that _you cannot hold onto the past_ for too long. Especially the digital past. Bloating the game with an impossible-to-implement (forget balance) campaign just so that you can play it is not a good way to go about it. I would prefer that Anuke (or someone else) simply makes a backup of v5 without the multiplayer. That way, you have both worlds, but without the absolutely terrible bloat to the game that would come from this.

agree with point three, but you dont need RAM to hold two campaigns at once so long as one is accessed.
anyway people seem to be hating this suggestion on a cult-like level so im just gonna close it before i get asked to leave the internet

**Comment by Kyllingene** [comment]
> anyway people seem to be hating this suggestion on a cult-like level

I dislike it, but please show what comments were "hating this suggestion on a cult-like level"? Mine simply showed that it was a technical problem, whereas sample-text-here simply explained that 1: it would indeed be a monster to code and 2: there are other ways to play true survival maps. No cult-like hate whatsoever.

**Comment by Kyllingene** [comment]
[The last update to v5.0](https://github.com/Anuken/Mindustry/releases/tag/v104.6)

**Comment by sup3r87** [comment]
> > anyway people seem to be hating this suggestion on a cult-like level
> 
> I dislike it, but please show what comments were "hating this suggestion on a cult-like level"? Mine simply showed that it was a technical problem, whereas sample-text-here simply explained that 1: it would indeed be a monster to code and 2: there are other ways to play true survival maps. No cult-like hate whatsoever.

wasnt you, but i was called retarded by multiple people in the discord when i asked about it :/

**Comment by Kyllingene** [comment]
People are indeed random jerks sometimes.

**Comment by catatagun** [comment]
> [The last update to v5.0](https://github.com/Anuken/Mindustry/releases/tag/v104.6)

I NEED A GOD DAMN APK

**Comment by catatagun** [comment]
> > > anyway people seem to be hating this suggestion on a cult-like level
> > 
> > 
> > I dislike it, but please show what comments were "hating this suggestion on a cult-like level"? Mine simply showed that it was a technical problem, whereas sample-text-here simply explained that 1: it would indeed be a monster to code and 2: there are other ways to play true survival maps. No cult-like hate whatsoever.
> 
> wasnt you, but i was called retarded by multiple people in the discord when i asked about it :/

Why tho i want old unit making system and that would be nice too i also want the player pads back

**Comment by itcannotbe** [comment]
> > > > anyway people seem to be hating this suggestion on a cult-like level
> > > 
> > > 
> > > I dislike it, but please show what comments were "hating this suggestion on a cult-like level"? Mine simply showed that it was a technical problem, whereas sample-text-here simply explained that 1: it would indeed be a monster to code and 2: there are other ways to play true survival maps. No cult-like hate whatsoever.
> > 
> > 
> > wasnt you, but i was called retarded by multiple people in the discord when i asked about it :/
> 
> Why tho i want old unit making system and that would be nice too i also want the player pads back

That system was too easy and too broken tbh.
