### ISSUE TITLE
Water interactions

### ISSUE THREAD

**Issue by TheDragonVin26** [Anuken/Mindustry-Suggestions#1807]
**Describe the content or mechanics you are proposing.**
When water touches power nodes/battery it will make them release a electric blast and dealing damage to nearby buildings and entities depending on how much power is stored.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
make it more logical i guess

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Trying to shoehorn realism in a video game with no thought about how this affects the game's balance?...

**Comment by Humanoid-X** [comment]
Ughhh…… The game itself is not realistic…… Just look at the most basic things. Conveyors, Conduits and Drills don't even need power. You can infinitely respawn without any loss of material and power.

**Comment by genNAowl** [comment]
Here is an Anuken quote to help facilitate the point: 
![Anuken Quote](https://user-images.githubusercontent.com/68400583/104819627-92fa4500-57e3-11eb-8f3a-e914f2aec0e3.jpg)
