### ISSUE TITLE
plastanium conveyors sorter, bridge

### ISSUE THREAD

**Issue by EldoreiJK** [Anuken/Mindustry-Suggestions#1809]
**Describe the content or mechanics you are proposing.**
Sorters: it's very difficult to sort content of plastanium conveyors to improve it's usability. If I use them to transport multiple item types, I often find a need to use one of the transported materials to be unloaded elsewhere that the rest (for example improving production with production boosters, building new production sites etc). At the moment it's nearly impossible to effectively sort content and use it.
As for the bridges: plastanium conveyors only work on ground level. While I'm perfectly fine with that, it needs huge rework on every map I decide to use plastanium conveyors as every other conveyors need to be bridged in order to allow plastanium ones pass on ground level. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's just about extending plastanium conveyors with features available for lower grade conveyors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slava0135** [comment]
*no*

**Comment by Kyllingene** [comment]
![plastconv](https://user-images.githubusercontent.com/69094702/104820093-7bbd5680-57e7-11eb-8ec9-73db321d33af.png)

**Comment by Quezler** [comment]
shout-out to unloaders

**Comment by EldoreiJK** [comment]
Unloaders works like magic, I didn't know they would work. So perhaps at least please somehow mention this in block description? That would be very appreciated by players I guess, as I played the game a lot but never thought about using it as such.

**Comment by joshuaptfan** [comment]
[Unloaders were only recently changed to work with plastanium conveyors.](https://github.com/Anuken/Mindustry/pull/4087)

Also, it's possible to bridge plastanium conveyors over things, just takes some creativity.

![Plastanium Bridge](https://user-images.githubusercontent.com/15149002/104821615-03a85e00-57f2-11eb-9d18-56948308da4a.png)
```
bXNjaAF4nEWNAQoCIRBFv+PmBhERXaALdIlO0BVsV0JodVELOkKntnFlU53R9/iD2EISOqcng+PtqWPSzr6m8zXY8WGwG00cgp2T9Q6QOM3/yGXw7m0+PuBwX8JNqOhDMgHAnguiHG49vzvUJVZLzTLUkFyQeItqqVmBDYdyzl8uKQrSikxQ9UNVWrmozPWFfsXxK00=
```
