### ISSUE TITLE
Blue drones

### ISSUE THREAD

**Issue by AstronautCat380** [Anuken/Mindustry-Suggestions#1810]
The game has red, purple, green, yellow drones. But there is no blue. It would be interesting to have a special type of drone that builds things just like the artificial intelligence you have in the game. For example: instead of a drone building what was destroyed or helping the player. Build things automatically by yourself.

**Comment by Kyllingene** [comment]
1: Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will filter it out.

2: No-one wants a drone that spends their resources building stuff at random. "Hey, look at this ore patch! Better make a turret here." *builds behind your defenses and right next to a conveyor messing everything up*


Template (just fit your issue to it):
```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by AstronautCat380** [comment]
Then dismiss the idea of ​​a random builder drone.
But I miss the blue armor I had in the previous version. The terrestrial was weak, it was. But the ship was fast and it was strong yes it would be nice to have it back even though weaker than the Flares but Drones.

**Comment by AstronautCat380** [comment]
I'm using translator so it can go wrong

**Comment by Kyllingene** [comment]
It's ok, I understand the potential translation problems. Could you tell me your native language so I can maybe find a more accurate translator?

**Comment by AstronautCat380** [comment]
Português Brazil

**Comment by Kyllingene** [comment]
Thank you!

**Comment by AstronautCat380** [comment]
Seria legal ter de volta a nave azul de volta só que como drone e tendo a principais características:
Ser rápido, o ataque ser forte. Mas pra não ficar chato eles terem menos ou a mesma vida que os Flares tem.

**Comment by joshuaptfan** [comment]
I shall apply the same amount of thought in this comment as was applied in creating this suggestion.

**Comment by Kyllingene** [comment]
Translation I got: "It would be cool to have the blue ship back, only as a drone and having the main features:
Be quick, the attack is strong. But not to be boring they have less or the same life that the Flares have."

O que você quer dizer com "navio azul"?

**Comment by AstronautCat380** [comment]
Disse apenas azul por que não lembro da armadura antiga que era uma nave azul

**Comment by AstronautCat380** [comment]
Não lembro o nome

**Comment by Kyllingene** [comment]
(Translated: I just said blue because I don't remember the old armor that was a blue ship. I do not remember the name.)


Então você quer dizer o Dar (Dart)? É como o novo Alpha.

**Comment by AstronautCat380** [comment]
Falo sobre a armadura aérea

**Comment by Kyllingene** [comment]
(Translated: I speak about aerial armor)

Você quer dizer a velha nave que você tirou do núcleo?

**Comment by AstronautCat380** [comment]
Era uma das últimas naves pilotaveis que tinha
Era azul e o ataque eram mísseis. E quando corria muito ele soltava uns raios que davam um pouco de dano.

**Comment by AstronautCat380** [comment]
A versão que tem essa nave tem na itch.io.
Pelo mesmo da última vez que olhei era a versão que tinha essa nave.
Ela era da versão que tava fixa antes de todas essas mudanças da v6

**Comment by AstronautCat380** [comment]
Que vc tinha um esquema diferente de armaduras em que vc construía uma mini base em que vc acionava e a nave ou a armadura entrava e se transformava em outra nave ou armadura.

**Comment by Kyllingene** [comment]
(Translated: It was one of the last pilotships that had 
It was blue and the attack was missiles. And when he ran a lot he released rays that did a little damage.)
(The version that has this ship has itch.io.
For the same last time I looked it was the version that had this ship.
It was the version that was fixed before all these changes in v6)

(That you had a different armor scheme in which you built a mini base in which you activated and the ship or armor entered and became another ship or armor.)

Você quer dizer este?
![javelin-ship](https://user-images.githubusercontent.com/69094702/104821410-84fef100-57f0-11eb-8daf-ca2017276398.png)

**Comment by Kyllingene** [comment]
Eu concordo, seria um bom navio ter novamente.

**Comment by Kyllingene** [comment]
Não traduza isso

I do believe that AstronautCat380 is requesting that the Javelin ship be re-introduced in some way. I agree (as long as it can be balanced), as it had a unique behavior that would be very interesting to see as a unit.

**Comment by Kyllingene** [comment]
Se eu estiver certo, tente fazer sua sugestão da seguinte maneira:

```
**Describe the content or mechanics you are proposing.**
That the Javelin mech be reintroduced as a unit.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The Javelin mech had highly unique and interesting behavior not found in the game today, and was a joy to use. It would be great to have it back in the game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by catatagun** [comment]
YES THE POLYS IN V6 BETA WHEN THEY BUILD ON THERE OWN

**Comment by AstronautCat380** [comment]
.

**Comment by Yell245** [comment]
We don't have specialist drones btw
