### ISSUE TITLE
Javelin

### ISSUE THREAD

**Issue by AstronautCat380** [Anuken/Mindustry-Suggestions#1811]
**Describe the content or mechanics you are proposing.**
That the Javelin mech be reintroduced as a unit.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The Javelin mech had highly unique and interesting behavior not found in the game today, and was a joy to use. It would be great to have it back in the game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
use anuke-logic messenger instead it has a jump drive very good

**Comment by joshuaptfan** [comment]
Maybe OP as a unit, since you can make lots of them.

**Comment by Kyllingene** [comment]
Just a note: This suggestion is made by a native Portuguese speaker.

> Might be OP as a unit, since you can make lots of them.

True. Is there any feasible way to make this as a reconstructor or something of the like?

> use anuke-logic messenger instead it has a jump drive very good

I have no clue what you mean. The Javelin mech had abilities no unit in the game has anymore. Therefore, mlog is useless.

**Comment by genNAowl** [comment]
As a side note, the code is still there though thanks to https://github.com/Anuken/Mindustry/pull/3058, so this would be relatively easy to implement via mods and such.

**Comment by Kyllingene** [comment]
Hmm... If I ever decide to figure out how to nicely make things in Java, I might make a PR myself on this. Possibly a whole new line of units...

**Comment by joshuaptfan** [comment]
Also, a unit with movement-based attacks would be pretty useless when controlled by the default AI, as their attack would stop working once they get within range of their target and stop moving.

**Comment by Kyllingene** [comment]
> when controlled by the default AI

I won't expect Anuke to work on that, but it could definitely be fixed my a new AI, just like how the leg units have different AI (although not by much, too be fair).

> Since the code is present in the game, it's ideal territory for mods.

Indeed it is. I just wish there was some way for it to get into the core game...

**Comment by BlueWolf3682** [comment]
i miss rodeoing around the map, it was a lot of fun, so i agree with this

**Comment by AstronautCat380** [comment]
Dá pra fazer o seguinte. Em vez de ficar sempre mechendo sem parar. Dá pra fazer como que uma nave que fica parada no lugar mas que se desvia de tiros comuns tipo os do dupla.
Ou então que desvia do tiros mas não 100% das vezes e sim 30%.

**Comment by joshuaptfan** [comment]
I know a lot of Javelin nostalgia comes from its speed. But, due to the lightning weapon's ineffectiveness with the default AI, I feel it would be more appropriate on a high tier (T4/5) unit as a secondary weapon that wouldn't be relied on for damage, but mostly for the awe factor. ("OMG this huge scary beast with lightning shooting out is approaching... slowly.") The speed required for max lighting strength would be scaled down, and the lightning damage would be buffed as appropriate for a high tier unit.

And I know just the unit to put it on: the Oct. It currently has no weapon and is mainly used as a transport, so giving it a weapon with unreliable damage is fine. This would also align it more thematically with the Quad, which is a bomber. Make the lightning green and able to heal friendly blocks as well.

**Comment by catatagun** [comment]
> **Describe the content or mechanics you are proposing.**
> That the Javelin mech be reintroduced as a unit.
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> The Javelin mech had highly unique and interesting behavior not found in the game today, and was a joy to use. It would be great to have it back in the game.
> 
> **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 2. * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 4. * [x]  I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

YES AND IT SHOULD HAVE 40 RANGE CUZ OLD JAVLIN HAD LIKE 70 OR 60 RANGE AND MAKE IT A DIFFRENT COLOR

**Comment by Humanoid-X** [comment]
It's a mod… isn't it?

**Comment by marky0470** [comment]
There's a mod that implements Javelin-like units already. Missing unit categories, it adds an entire new line of units with Javelin's properties. Though instead of missiles they shoot lasers.
