### ISSUE TITLE
Targeting System for Turrets

### ISSUE THREAD

**Issue by catsz** [Anuken/Mindustry-Suggestions#1812]
**Describe the content or mechanics you are proposing.**
A targeting system for turrets it could be a radar block or just a option on the turrets.

The targeting would be: strong, highest health, close, far, weak, flying, ground

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would help with parralaxs or other turrets that you want to target only the strong ones instead of weak ones.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Logic already has a `radar` command, with filtering for most health, closest, flying/ground, etc, and logic can control turrets to target specific enemies. So what you're asking for is already in the game.

The only issue currently is that parallax targeting cannot be controlled with logic.

You are not:
> familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Please close this suggestion.

**Comment by itcannotbe** [comment]
This is what happens when you blindly put X in the box without doing what they ask you to.

Try reading the "read me" again.

**Comment by scarf-generic** [comment]
the radar cannot target buildings though, while default turret ai can
