### ISSUE TITLE
Risso's family could cargo units

### ISSUE THREAD

**Issue by PolloUsami** [Anuken/Mindustry-Suggestions#1813]
**Describe the content or mechanics you are proposing.**
like the t3 or the mono family that can carry units along the map i was believing that rissos could make the same moving ground units along the water tiles, but removing the capacity of atacking and be a little slow for the cargo

like brydge could carry t1 units, sei t2, omuras t3

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this will be a good adition for the atack maps where there is water arround the enemy core for a sneck atack 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by catatagun** [comment]
I was thinking a more unit factory role

**Comment by Kyllingene** [comment]
#1730 #1675 #1313 #1300 and more.
![image](https://user-images.githubusercontent.com/69094702/104850710-8f2ef700-58a5-11eb-835a-62dc0f89044d.png)
