### ISSUE TITLE
Scrap Walls to be buildable with a cost

### ISSUE THREAD

**Issue by AnOreo1** [Anuken/Mindustry-Suggestions#1815]
**Describe the content or mechanics you are proposing.**
Allow building of scrap walls, but they have a little cost. They cost the same, but when they are hit with anything over a certain amount of damage, they lose part of the wall (aka a frag comes out from a random part of the wall) and it damages both your structures and the enemy team. These can deal higher damage the stronger/bigger the scrap wall. Scrap walls could also be unable to block energy bolts from the mega and pulsar. Increasing the cost of scrap walls would be a decent idea, as scrap has the hardness of sand currently. One other thing that would be nice is that scrap walls take more damage from bullets than lasers, as the walls are made out of sand, graphite, titanium, thorium, copper, and lead.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would add a nice little cost to the walls and finally add a use for them outside of sandbox pvp and map lore. It would also add a neat little risk to using them, as they would destroy your structures if left unchecked without any menders. A risky cheap earlygame wall, if you will.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AnOreo1** [comment]
also I can't be certain if this was suggested, I can't search through all 1000+ suggestions

**Comment by BlueWolf3682** [comment]
mods.

**Comment by catatagun** [comment]
Yes

**Comment by AnOreo1** [comment]
scrap walls are currently ingame and have no real useage despite having a build cost preset, along with proper health values for the cost.

**Comment by Yell245** [comment]
It doesn't make sense because these were regular walls in the past. Scrap walls are ruins and ruins shouldn't be built by player

**Comment by AnOreo1** [comment]
but it'd be a nice aspect, as they have added build cost to them.

**Comment by joshuaptfan** [comment]
Not block that exists in the game needs to be buildable by the player. This is one of those poorly justified "give us everything just because" suggestions.

Scrap walls' purpose is to be environmental objects, making them buildable would be pointless and reduce immersion, in the same way that making boulders buildable would be.

**Comment by AnOreo1** [comment]
But then, why did they add build cost to it? I understand the 3x3 and 4x4 not being buildable, and the other things, but this seems right to me, they have everything ready

**Comment by joshuaptfan** [comment]
I don't know, maybe it's a technical reason relating to how every other block has a build cost field, or to make them not free just in case a mod decided to add them, but that fact in no way justifies making them buildable.

**Comment by Ruichka** [comment]
Scrap walls have a build cost so they give scrap when you destroy them.

**Comment by AnOreo1** [comment]
But they aalso made scrap naturally generated in the planet, and how scrap walls are natural.
at least add this effect ingame for the derelict team, a diffirent hazard

**Comment by AnOreo1** [comment]
all I'm asking is for the scrap walls to break apart in frags really. I don't care much if they are buildable or not.

**Comment by joshuaptfan** [comment]
You're asking for a completely new, complex mechanic that would take a lot of effort to implement and be of questionable gameplay benefit.

**Comment by AnOreo1** [comment]
ok I'll just leave it then.

**Comment by joshuaptfan** [comment]
Nothing wrong with making a suggestion, but gameplay benefit should be the foremost consideration.

**Comment by scarf-generic** [comment]
> also I can't be certain if this was suggested, I can't search through all 1000+ suggestions

github has this incredible feature, called a search bar. you can type things into it, and it filters out unrelated suggestions. its really handy for finding duplicates, i suggest you try it sometime.
