### ISSUE TITLE
you shouldn't be able to select a block to build if the unit can't build (or at if you can, you should still zoom by scrolling)

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#1816]
**Describe what you would like changed, and why.**
when you are a unit / block that can't build, you shouldn't be able to select a block to build. also, even if you can select a block, scrolling should still zoom, not rotate the block (which you can't build and therefore not see the preview for).

**Describe the changes you want to propose. Include possible alternatives.**
- no selecting blocks in things that can't build
 - if you decide to keep it so that you can select blocks, scrolling should still zoom, not rotate the block (that you can't even see the ghost of)

**Comment by DeltaNedas** [comment]
bruh

**Comment by joshuaptfan** [comment]
Preventing selection of blocks for building will also prevent scroll from trying to rotate that block, since no block has been selected. So there's really only 1 change to be suggested here.

**Comment by Kyllingene** [comment]
> So there's really only 1 change to be suggested here.

The second part was more an "if this doesn't happen, at least this", not both.

**Comment by QmelZ** [comment]
why remove the ability to view info of a block when you can't build it? the second part *only* makes more sense if you ask me.

**Comment by Yell245** [comment]
Maybe let players place blocks, but don't rotate them? Because it's useful to check turret detection range

**Comment by Catchears** [comment]
> > So there's really only 1 change to be suggested here.
> 
> The second part was more an "if this doesn't happen, at least this", not both.

yes


> why remove the ability to view info of a block when you can't build it? the second part _only_ makes more sense if you ask me.

Good point. I agree.

**Comment by joshuaptfan** [comment]
I suppose units that can't build still have to be able to select blocks, because that is what allows the "Unit can't build" message to be displayed. I've pushed a fix for zooming.
