### ISSUE TITLE
Max All button on resouces allocation menu when launching

### ISSUE THREAD

**Issue by MacroJack** [Anuken/Mindustry-Suggestions#1817]
**Describe the content or mechanics you are proposing.**

A button on the resource allocation menu that say's "Max All" that allocates the maximum number of all resources availabe when launching that sector. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will speed up starting a new sector, and remove the tedious back and forward between menus when you over allocate too many of one resource and then can not launch the sector need to go back and lower the amount by a bit. There's no way currently from the resource screen to know if you've over allocated too much of one resource until you go back to the previous menu. The resource allocation part of launching a new sector becomes annoying after 10 or so sectors. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X]  I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by joshuaptfan** [comment]
[It's already been added to the game](https://github.com/Anuken/Mindustry/pull/4238), it will be live next update. OP, please close this suggestion.

**Comment by DeltaNedas** [comment]
@MacroJack close

**Comment by genNAowl** [comment]
^

**Comment by MacroJack** [comment]
Thanks
