### ISSUE TITLE
Difficulties for custom maps and campaign (only affect AI)

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1819]
**Describe the content or mechanics you are proposing.**
Add selectable difficulties for custom maps and campaign (probably changed in the game's settings for campaign?). Those would only affect how smart the enemy AI is - as in, on harder difficulties the enemy AI could take turret coverage into account or even use boost on boosting units to fly around defenses.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Possibility for gameplay where the AI is actually competent.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GlennFolker** [comment]
Good luck making 3 new smarter AIs

**Comment by BlueWolf3682** [comment]
it doesnt need a new ai, it would be nice if you could just set what tier of (trashy) baseparts the ai uses when building cause they all use copper walls and that junk in custom maps

**Comment by itcannotbe** [comment]
AI is just a set of instructions, you can tell it to not use or use that part of code.

**Comment by Yell245** [comment]
It'll actually be a neat idea, but hard to implement. Talking about builders, it's muuuch harder to make them smarter: you can't emulate a player. But who knows... Maybe when Anuke makes a big dev team, he'd be able to analyse how players play and make a neural network out of it. But it'll be veeeeeeery hard

**Comment by itcannotbe** [comment]
You need more complex AI for something that can barely mimic a player.
