### ISSUE TITLE
coal ex

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry-Suggestions#1820]
how close

**Comment by itcannotbe** [comment]
Now where is that giant red button to flag this suggestion as "super effing overpowered" I left lying around somewhere?

**Comment by DeltaNedas** [comment]
titanium extractor
you can already separator, why not 1x1 block that turn scrap into tinanium???

**Comment by Quick-korkc** [comment]
>Coal extractor. Requires water of around 13/s and power of 250/s to extract 7 coal with a production time of 0.7 seconds 3x3 block.

Bruh just use the coal centrifuge, and the oil? you can use spore, oil extractor, and tar lake

**Comment by GreyMario** [comment]
Some thoughts are better left unsaid.

**Comment by Slava0135** [comment]
*cringe*
Close this asap or else you are nerd

**Comment by NajimiOsana** [comment]
There are a shit ton of reasons why this shouldn't exist, but listing all of those would waste more time than the time you spent making this.

Too overpowered and too stupid. you're just making an excuse to make this game more easier for you.

**Comment by Yell245** [comment]
You can already make it out of chain of water extractor / pump, cultivator, spore press and coal centrifuge

**Comment by BlueWolf3682** [comment]
as always, ***mods.***

**Comment by WinterCrystal** [comment]
Why is this even a suggestion? There's various ways of getting coal that someone already mentioned, you're just making this one in hopes of personal gain, that is making the game easier for you.

**Comment by itcannotbe** [comment]
Congrats, you just awaken a thread that no replied to in 19 days by a comment that doesn't bring new insights.

Really useful.

**Comment by BlueWolf3682** [comment]
dingus

**Comment by bendnuts** [comment]
ight ight

**Comment by bvcbvc** [comment]
coal anywhere is op without some harsh negatives, one can barely make sport power now, and said spore power has to use PUMPED water, not extracted water
