### ISSUE TITLE
when a container (and other blocks) are full items 'lie on top'

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry-Suggestions#1821]
**Describe what you would like changed, and why.**
it looks nicer

**Describe the changes you want to propose. Include possible alternatives.**
render blocks (except conveyors) over items
![container](https://user-images.githubusercontent.com/49868160/104919983-62f3a300-5997-11eb-83ef-89f4322c1b4a.png)

**Comment by DeltaNedas** [comment]
adding a little shadow over it would look nice too so it doesnt appear to be phasing through the container/factory/etc

**Comment by the-kido** [comment]
You gotta remember to keep the format otherwise people will rip you to shreds. But I do like this suggestion.

**Comment by joshuaptfan** [comment]
This suggestion could have used a better title ("Prevent items from overlapping blocks"), but it's a great and doable idea.

**Comment by sample-text-here** [comment]
you can close this, it’s been added

**Comment by Kyllingene** [comment]
@antonilol ^^^

**Comment by antonilol** [comment]
junction now (bleeding edge release):
![image](https://user-images.githubusercontent.com/49868160/105205256-5745df00-5b45-11eb-9f2b-f660b5565514.png)

would be nicer (to me) is items go through like this
![image](https://user-images.githubusercontent.com/49868160/105205673-ccb1af80-5b45-11eb-885e-402cfc2a9561.png)

same for router:
![image](https://user-images.githubusercontent.com/49868160/105205353-77759e00-5b45-11eb-8118-66ceb83335cd.png)

nicer router:
![image](https://user-images.githubusercontent.com/49868160/105205948-169a9580-5b46-11eb-9971-6ec34382b136.png)

**Comment by antonilol** [comment]
and power nodes don't accept items
![image](https://user-images.githubusercontent.com/49868160/105206270-76913c00-5b46-11eb-86c7-d407b91e60fe.png)
(same happens with boulders and walls and many other blocks)

**Comment by joshuaptfan** [comment]
> and power nodes don't accept items

That's not a problem. Visuals would not be improved by rendering items over blocks that don't accept items.

**Comment by antonilol** [comment]
then maybe only let the items go till here
![image](https://user-images.githubusercontent.com/49868160/105207316-aa209600-5b47-11eb-9d6f-04493c961777.png)
(nice photo edit)

**Comment by joshuaptfan** [comment]
It's just doing the same thing as when there's nothing at the end of the conveyor. Conveyors don't check if there's anything after them.

**Comment by antonilol** [comment]
i think not
the sorter and the junction only accept items if they can put it in another block so it is already in the code
