### ISSUE TITLE
Map Editor: Publish map as new Workshop Item/ unlink from old Workshop Item

### ISSUE THREAD

**Issue by TheNightglow** [Anuken/Mindustry-Suggestions#1822]
**Describe the content or mechanics you are proposing.**

Right now if you were to make a variant to a map, you can not publish it independently to the steam workshop, you can only override the old one.
If the game thinks your map is already linked to a workshop item, it is impossible to publish it without overriding the existing workshop item.

So I would like an option in the map editor to unlink your map from a workshop entry, or to publish your map as a new workshop entry instead of overwriting an old one.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I have this problem with one of my maps, where I created a survival map and published it to the workshop.
Later I used the in-editor function to copy the map, create a new one with a different name and paste the old map into it, so I could alter it to be an attack map, without messing with my old survival map.
I changed the layout a bit, changed the player spawn, added enemy defences as well as ores.
But when I was done I noticed I can not actually publish this map to the workshop, instead I can only overwrite the workshop listing for my old survival one.

Right now I m in this position:
In game I have both my attack map and my survival map listed as completly seperate entities I can select and play on.
But if I enter either map in the Editor, they both only have the "Edit Workshop Listing" button linked to the same workshop entry.

An option as proposed here would allow for a workaround for whenever the editor falsely links your map to an already existing one you dont want to override.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
I have had this problem with several survival-to-attack/survival conversions, and see no reason not to add a "Unlink Workshop" button, maybe in the "Upload to Workshop" dialog.

**Comment by joshuaptfan** [comment]
You may be able to work around this by exporting the map to a file and then reimporting it.

**Comment by TheNightglow** [comment]
> 
> 
> You may be able to work around this by exporting the map to a file and then reimporting it.

I tried that and sadly it does not work.
After importing, the editor always thinks it is linked the old workshop item.
I think the information about what workshop item it is linked to is saved in the mapfile you export.

**Comment by joshuaptfan** [comment]
I face a similar problem with Steam Workshop schematics, because the workshop ID is saved to schematic files/codes as well. At least that is easy to work around by placing the schematic, selecting it, and saving as a new unlinked schematic. There used to be a bug where if people imported a schematic with a Steam ID, [they were unable to delete the schematic](https://steamcommunity.com/app/1127400/discussions/0/3145133021635675833/) because the delete button was replaced with a link to the workshop. This was fixed by stripping the Steam ID from all imported schematics. The same may need to be done for map importing.

**Comment by InfernoSuperNova** [comment]
the only way around this is to start a new game, export that save, then import it as a map. all the waves need to be redone, but overall it is really frustrating not being able to unlink it
