### ISSUE TITLE
Big tree

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1823]
**Describe the content or mechanics you are proposing.**

I would like to add a big tree to the editor catalogue just as a decoration block map makers can use. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It's purely esthetic but I think it would be used extensivly by map makers.

![example](https://user-images.githubusercontent.com/63456333/104959185-9e926b00-599f-11eb-86d5-7adb2156c8ea.png)
This is a very rough example but I think it gets the idea across. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
So like spore tree but regular tree version?

**Comment by DeltaNedas** [comment]
hhhh that would make wood exist
so far green trees have been only known to have leaves

**Comment by the-kido** [comment]
> So like spore tree but regular tree version?

ye

> hhhh that would make wood exist

Its plastic. You're welcome

**Comment by Kyllingene** [comment]
> hhhh that would make wood exist

Yes, it would. However, I fail to see the deadliness of this fact pertaining to this suggestion.

> so far green trees have been only known to have leaves

If you mean IRL, I live surrounded by pine trees. If you mean in-game, I have no clue what you mean, as the "trees" already in the game (the wall ones) look nothing like either leaf or pine trees.

**Comment by genNAowl** [comment]
Why is wood deadly? I dunno but It might cause more issues like this: https://github.com/Anuken/Mindustry-Suggestions/issues/112

**Comment by iLagSoUhax** [comment]
i think normal trees don't tie in with the spore trees otherwise used, and the concept of spores seem to be important to the canon. normal trees wouldn't fit in.

**Comment by Kyllingene** [comment]
> i think normal trees don't tie in with the spore trees otherwise used, and the concept of spores seem to be important to the canon. normal trees wouldn't fit in.

Trees already exist though. True, they don't *look* like trees when you glance at them for a split-second from high up, but they are canonically trees.
![snowpine](https://user-images.githubusercontent.com/69094702/105099760-08bf1480-5a61-11eb-8448-f53c3294d2f6.png)

**Comment by the-kido** [comment]
this is a sad day for big tree gang

**Comment by Kyllingene** [comment]
#bigtreegangforever
