### ISSUE TITLE
Metaglass walls

### ISSUE THREAD

**Issue by THEGAMER-10n** [Anuken/Mindustry-Suggestions#1824]
**Describe the content or mechanics you are proposing.**
Metaglass walls that can affect enemy and ally lasers in different ways depending on the wall at the back of it. It will only be available mid-game to late-game because of the need of plastanium.
If it has no block behind it, it will make both ally and enemy lasers have a piercing to plastanium walls for every metaglass wall it passed through.
If there's phase walls behind it, it will reflect lasers(but with only 50%-75% the damage).
If there's surge walls behind it, it will double the damage at the cost of range.
If there's plastanium walls behind it, it will double the range at the cost of damage.

Health:
1250

Build cost:
24 metaglass
5 titanium
3 plastanium

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1.) Metaglass is very rarely used. It will only be used on making a few turrets and plumbing. Using it on walls that has special abilities will fix this.
2.) It will add interesting new mechanics to the game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
24 metaglass
5 titanium
3 plastanium

But why?

**Comment by Quick-korkc** [comment]
>1.) Metaglass is very rarely used. It will only be used on making a few turrets and plumbing.

T3 unit : am i joke to you?

**Comment by iLagSoUhax** [comment]
I don't think making walls out of glass is very advisable. moreover, the mechanics seem finicky and will be difficult to understand and use correctly. all in all, I disagree.

**Comment by QmelZ** [comment]
1. hard to implement
2. hard to understand
cool feature, but no. doesn't fit the game if you ask me. just use mods

**Comment by Yell245** [comment]
Hp of walls should be less than copper ones. This is **glass** not mirror, plus it's glass with **metall** in it. Okay, if we close eyes on it, there are no 100% deflecting. Maybe it will heat up? And if it's on 75% of heat it'll start taking constant damage until it cools down. It'll increase damage the more it heats up and can be cooled down faster when liquid turrets fire water / cryofluid on it. And if it reaches 100% it'll catch on fire
uh
no
it's too complex

**Comment by SheepCommander** [comment]
Ye I think this should be closed
