### ISSUE TITLE
plastanium force field

### ISSUE THREAD

**Issue by NEO245LOL** [Anuken/Mindustry-Suggestions#1825]
its like a phase but plastanium but no boost on the range it can stop corvuses fire

**Comment by GreyMario** [comment]
No.

Install Plastanium walls.

**Comment by Quick-korkc** [comment]
hey
where the template
and plastanium and phase literally very different
plastanium is an advanced metal
phase is a radioactive product

**Comment by Yell245** [comment]
Phase fabric is an energy-concentrating material when plastanium is an isolation one. You don't spray plastanium into field - it goes into projector. Use plastanium walls instead

**Comment by Kyllingene** [comment]
1: Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will automatically filter it out to save him time.

2: As GreyMario mentioned, plastanium walls are the necessary preparation for a laser gun like a Corvus.

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```
