### ISSUE TITLE
Специальный перекресток для конвейеров из пластания

### ISSUE THREAD

**Issue by QQWW1234PRO** [Anuken/Mindustry-Suggestions#1827]
Хотелось чтобы добавили специальные перекрёстки для пластанеевых конвейеров. Сейчас неудобно их использовать.

**Comment by genNAowl** [comment]
Here's a google translation of what he is saying: 

Title: 
Специальный перекресток для конвейеров из пластания
Dedicated crossroads for laminated conveyors

I guess he wants plastanium junctions?

Description: 
Хотелось чтобы добавили специальные перекрёстки для пластанеевых конвейеров. Сейчас неудобно их использовать.
I would like to add special intersections for the bed conveyors. It is inconvenient to use them now.

H
