### ISSUE TITLE
Foreshadow and overdrive

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1829]
**Describe what you would like changed, and why.**foreshadow can be overdrived so just a 200% boost can make it shoot every 1.5 sec pretty sure you dont want this cuz of foreshadow and cryo

**Describe the changes you want to propose. Include possible alternatives.** make foreshadown non overdrivable just like meltdown and spectre also why is spectre non overdrivable

Make it non overdrivable or decrease overdrives affectiveness on turrets

**Comment by itcannotbe** [comment]
Overdriving anything is too easy.

**Comment by catatagun** [comment]
> Overdriving anything is too easy.

Thats the reason

**Comment by Yell245** [comment]
You literally collect surge alloy and other for it. Why should we nerf an *endgame* turret?

**Comment by itcannotbe** [comment]
Also cryo boost is just 1.3x
While....
OD 1.50x
POD 2.25x
ODD 2.50x

Converted to Foreshadow Fire rate in ticks:
Base 270
Cryo 208
OD 180
POD 120
ODD 108
ODD + Cryo = 84

Overdriving it just makes it too fucking easy.

**Comment by QmelZ** [comment]
![image](https://user-images.githubusercontent.com/59574967/105244995-5a12f500-5b82-11eb-957b-cfb1df12d705.png)
it is, and it also is pretty good when od domed + cryo cooled

**Comment by Catchears** [comment]
> ![image](https://user-images.githubusercontent.com/59574967/105244995-5a12f500-5b82-11eb-957b-cfb1df12d705.png)
> it is, and it also is pretty good when od domed + cryo cooled

the quote feature feels left out

**Comment by QmelZ** [comment]
sorry, a bit too used to screenshotting stuff

**Comment by catatagun** [comment]
Turret overdrive needs a nerf
