### ISSUE TITLE
Planet Map should indicate neighboring Enemy Bases better if they are locked campaign sectors

### ISSUE THREAD

**Issue by GreyMario** [Anuken/Mindustry-Suggestions#1830]
**Describe what you would like changed, and why.**
Locked campaign sectors that are Enemy Bases can threaten their neighboring numbered sectors. The only indication to a new player that this locked sector is actually the cause of attacks is a thin red line leading from the locked sector to the vulnerable sector; this line is quite easy to miss, in all honesty.

**Describe the changes you want to propose. Include possible alternatives.**
Suggest a more visible indicator, such as one similar to the indicator on _unlocked_ Enemy Base sectors.

**Comment by sup3r87** [comment]
my solution to this is to just launch "scout cores" with no resources on suicide missions, for the purpose of scanning the grounds around them. i then give the sectors icons based on what they are and this way i know exactly what many sectors's threat levels, enemy base or not, etc, without even having them unlocked. its all about finding ways around the problem.

**Comment by GreyMario** [comment]
> my solution to this is to just launch "scout cores" with no resources on suicide missions, for the purpose of scanning the grounds around them. i then give the sectors icons based on what they are. since icons are still visible even when a sector is locked, this way i know exactly what many sectors's threat levels, enemy base or not, etc, without even having them unlocked. its all about finding ways around the problem.

This does literally nothing to address the problem.
