### ISSUE TITLE
Territory Terrain

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#1832]
**Describe the content or mechanics you are proposing.**

Being able to mark terrain with a team as their "territory". This would be shown as a nearly transparent overlay of the team colour. You cannot build with a different team on marked territory tiles. They would disappear upon destruction of the enemy team and derelict would be "unmarked" terrain and would not draw any overlay.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

this is a draft concept drawn up from some stuff in #pulls and it would be interesting to have for more difficulty and fun with attack and "checkpoint" style attack maps. also would remove the need for core nobuild - core would have a radius of territory around it. Feel free to modify the concept as you feel fit.
May add stuff in the future as i flesh this concept out.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have not completely read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

i actually dont know if this goes under suggestn't but if it does notify me

**Comment by TheNightglow** [comment]
So kinda like how things worked in Anno 1404, where specific building would automaticly expand the faction territory, and those have to be destroyed befor other factions can build in it?

I like the idea I always feel like I m cheesing the attack maps a bit when i simply spamm copper walls in the middle of their defences to out nutrition their towers, and then swoop in when nothing has ammo anymore xD

Doesnt really feel like I m supposed to be able to place walls inside or behind the enemy defences.....

**Comment by joshuaptfan** [comment]
> I like the idea I always feel like I m cheesing the attack maps a bit when i simply spamm copper walls in the middle of their defences to out nutrition their towers, and then swoop in when nothing has ammo anymore xD
> 
> Doesnt really feel like I m supposed to be able to place walls inside or behind the enemy defences.....

Whoa. Yeah, you should not be allowed to build on top of and replace enemy blocks. You should only be able to build in on that tile after destroying the enemy block occupying it.

**Comment by sk7725** [comment]
This was possible in 5.0 by setting the air blocks/tiles' team to something other than derelict, idk about 6.0

**Comment by GlennFolker** [comment]
haha yes no more freedom for the damn crux's gamma

**Comment by genNAowl** [comment]
Of course this would make it possible for people in early PVP games to cover the map with spaced conveyors, destroying any way the other team can build there.

**Comment by Jammo2000** [comment]
Only certain blocks should be able to expand the territory. Or it could be the other way around i.e. certain blocks can't expand territory. Maybe factories, drills, and transport don't expand territory.

**Comment by sk7725** [comment]
*having clash of clans vibes*
