### ISSUE TITLE
(1.Different Music Themes to Different Planets & (2.Music configuration in editor.

### ISSUE THREAD

**Issue by Laggyboi0701** [Anuken/Mindustry-Suggestions#1833]
**Describe the content or mechanics you are proposing.**
1.Just for planet themes for a better themed levels like terra, martian, etc..

2. Changes music for maps that help it fits for a theme. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1. connects to number two

2. this will help map editors to improve the map, with many music themes added.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
![Trello Music](https://user-images.githubusercontent.com/68400583/105207803-d19e4100-5afc-11eb-9386-f2a9c7194f1a.jpg)

There is something in the Trello about adding new music, like biome specific ones, and if different planets become have different biomes, different planets will have different music.

**Comment by Jammo2000** [comment]
It's in the trello, so don't suggest it here.
[X] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
