### ISSUE TITLE
Addition of 'contour terrain' to map editor

### ISSUE THREAD

**Issue by EnglishDotpl** [Anuken/Mindustry-Suggestions#1834]
**Describe the content or mechanics you are proposing.** 
The addition of 'contour lines' to the map maker. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I have played on many wonderful .io maps that include this terrain in them. It can be used as an impression of higher/lower ground. As with 'wall terrain', you cannot build on it. But unlike 'wall terrain', insect ground units can walk all over it, no matter the thickness of the wall. It would surely be a handy thing to have in one's mapmaker. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
These are "cliffs" and are obviously already implemented in the code, but there isn't a way to use them yet.

In the meantime, there's a mod (abtly named "cliff" iirc which can aid in using them.

**Comment by Kyllingene** [comment]
> In the meantime, there's a mod (abtly named "cliff" iirc which can aid in using them.

Link?

**Comment by EnglishDotpl** [comment]
The so-called 'Cliff' mod does not show up in mod browser. Could you give a link, @GreyMario

**Comment by sample-text-here** [comment]
deltanedas/cliff
