### ISSUE TITLE
Advanced Map Maker tools

### ISSUE THREAD

**Issue by Engineer26** [Anuken/Mindustry-Suggestions#1835]
I propose some new tools for the mindustry map editor:
- **Area select tool**: With this tool you can select a specific area
- **Cut tool**: With this tool you can cut out a certain area and insert it again at a certain point
- **Copy tool**: copy the selected area to your clipboard. the area select tool is used here to select a specific area.
- **paste tool**: with this tool you can insert an area from your clipboard.

**Describe how you think this content will improve the game**. 

-it would be really great if these tools were in the game. then you could create maps much easier, faster and more conveniently.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
I've already suggested this a very long time ago, but yes if someone could add this that would be super super awesome.

**Comment by sup3r87** [comment]
even though this is likely a duplicate suggestion as a map maker i very much would appreciate these finally being added

**Comment by Fish-Noises** [comment]
agreed. this is super useful.
