### ISSUE TITLE
Better block graphics

### ISSUE THREAD

**Issue by parkuristt** [Anuken/Mindustry-Suggestions#1836]
Maybe solid blocks can look less-blocky, like the ground blocks but not that much. (i tried to draw a concept but I realised I will fail miserably)

I think it can look better, especially it can bring new players. 

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slava0135** [comment]
*understandable, have a nice day*

**Comment by the-kido** [comment]
This is just too vague. Also, I don't agree. Every block in its place right now seems fine and the style Mindustry has will be tampered with this suggestion. Not to mention who's gonna make all of those sprites?

**Comment by joshuaptfan** [comment]
It's so easy to ask for "better", "more", etc isn't it?

The shorter the suggestion, the more work is required to implement it.

**Comment by parkuristt** [comment]
yo people i asked "maybe", i sent this with a think of "maybe it is acceptable", not like annoying people who think their idea is the best.

**Comment by parkuristt** [comment]
> This is just too vague. Also, I don't agree. Every block in its place right now seems fine and the style Mindustry has will be tampered with this suggestion. Not to mention who's gonna make all of those sprites?

hmm i actually didn't want new sprites, just a little improvement(?) to the _existing sprites_, but you might be right.

**Comment by the-kido** [comment]
>hmm i actually didn't want new sprites, just a little improvement(?) to the existing sprites, but you might be right.

Either or, this suggestion must be more specific otherwise anuke will shun it away. Better yet, if you can get someone to make a few sprites for reference, that can make this suggestion have more of a chance at seeing day.

**Comment by GreyMario** [comment]
Ah yes, the fallacy that _everything must be hyperrealistic or people won't play it_.

**Comment by Slava0135** [comment]
Stop commeting this shitpost - notifications are keep going...

**Comment by parkuristt** [comment]
> Ah yes, the fallacy that _everything must be hyperrealistic or people won't play it_.

Did I say "i want _round_ stones"?
Ok, I don't think people got it, to be clear: i thought maybe _texture connections with solid blocks can be great_, not "**yo i want real stones in game lol**"

**Comment by Kyllingene** [comment]
> texture connections with solid blocks can be great

Ah, so that's what you want.
1: Connections between factories/walls/etc would look weird and not made sense.
2: Connections between enviroment blocks (like rock walls) already exist.

Is there something I'm missing?

**Comment by parkuristt** [comment]
why is this still open
