### ISSUE TITLE
Enable working Input/Output ports of blocks

### ISSUE THREAD

**Issue by gregorynikif** [Anuken/Mindustry-Suggestions#1837]
Have you grown tired of doing complicated turns, putting bridges, and generally avoiding factories, mines, distributors,  routers, and other production blocks with multiple input/output ports? 

If your answer is "no" then there is nothing for you to see here. However, if your answer is "yes" then we have the best solution for you, it's the 20.20k upgrade. 

This bad boy allows you to turn on and off any ports of a block and prevent it from interacting with a conveyor belt or any other block. Now you can place two routers next to each other and they will not exchange or allow resources to pass through them combining their quantity. 
The function is as simple as clicking which port is closed and which is not. It's simple, select the block and all ports will be shown as green boxes if they allow resources passing or red if they don't or they are not connected. Clicking on them will change between allowing or not. Enjoy having the ability to build a gigantic mass of facilities and conveyors with everything running as you intended.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
Im pretty sure this suggestion has been made before and this is in "a few things you shouldn't suggest" 

"Additional configuration of blocks, such as I/O side configuration, which has been suggested a million times"

**Comment by RedstonerKBC** [comment]
You know you're having a bad day when you have read the README.md which only has 9 items on it and still missed it.

**Comment by gregorynikif** [comment]
Yes which is why I closed it immediately after I found that out.

**Comment by gregorynikif** [comment]
I don't know how to delete it.

**Comment by gregorynikif** [comment]
> You know you're having a bad day when you have read the README.md which only has 9 items on it and still missed it.

I have no excuse. I may or may not failed to pay attention to what I was reading. I take the blame for being an idiot.
