### ISSUE TITLE
changes to bosses II: better health bar

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1838]
**Describe what you would like changed, and why.**
i would like a few minor-ish changes to the way guardian health bars are displayed. currently the health bar is a bit boring, and just kinda there.

**Describe the changes you want to propose. Include possible alternatives.**
an idea is to display the health bar at the center of the screen, either just below the resource monitor at the top middle or at the bottom middle. also, "guardian health" would be replaced by the unit's name. and, the health bar would be slightly longer/larger based on unit tier. so a tier 3 guardian would have a health bar that's about 40% smaller than a tier 5 guardian's. it doesnt have to be based on health, but health bar size gives you a better idea on what you're going to fight, even if it isn't based on size.

**Comment by the-kido** [comment]
1. The format!
2. If you can specify any changes that will help this suggestion. This is too vague just saying "its a bit boring". Maybe explain some ideas you may have for it. 
3. I do agree.

**Comment by joshuaptfan** [comment]
Keep both mobile and desktop versions of the game in mind when suggesting UI changes. A centered boss health bar would obscure a significant part of the screen.

**Comment by sup3r87** [comment]
> Keep both mobile and desktop versions of the game in mind when suggesting UI changes. A centered boss health bar would obstruct a significant part of the screen on mobile. For the same reason, unnecessarily scaling the health bar would be obtrusive.

shoot, forgot about that bit. i only generally think of the desktop version when i make suggestions

**Comment by GreyMario** [comment]
And what if there are multiple types of Guardians at the same time? Suddenly, unit name doesn't work.

**Comment by sup3r87** [comment]
> And what if there are multiple types of Guardians at the same time? Suddenly, unit name doesn't work.

maybe there could be a ui change to display multiple bars, though this problem already exists in the game

**Comment by rdragonrydr** [comment]
> > And what if there are multiple types of Guardians at the same time? Suddenly, unit name doesn't work.
> 
> maybe there could be a ui change to display multiple bars, though this problem already exists in the game

It would be nice if the health of each of the Guardians could be shown. There are a lot of times there are, say, two or three, and I can't tell if any are taking damage or how much, since it won't change until there's one left.

**Comment by genNAowl** [comment]
Of course, if there are too many guardians, then the bars would just obstruct the screen.

**Comment by YoMamaLlama1** [comment]
Then maybe limit it to X amount of bars that won't fill the whole screen/that side of the screen. If there are more guardians, show only the guardians with the lowest health

**Comment by YoMamaLlama1** [comment]
> Of course, if there are too many guardians, then the bars would just obstruct the screen.

Then maybe limit it to X amount of bars that won't fill the whole screen/that side of the screen. If there are more guardians, show only the guardians with the lowest health
