### ISSUE TITLE
Rotate Core Schematic before launch + Warning for if no space.

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#1839]
**Describe what you would like changed, and why.**
When launching with a core schematic, it's quite annoying when you land and discover some part of it was destroyed by landing on terrain, especially if it's some unit production schematic for landing in attack sectors.

**Describe the changes you want to propose. Include possible alternatives.**
Before launching, you'll receive a warning that blocks would get destroyed on landing, as well as allow you to rotate the core schem before landing to attempt to avoid this blockage..

**Comment by joshuaptfan** [comment]
When is there time to give the player this warning? Perhaps it should just be rotated automatically.

**Comment by itcannotbe** [comment]
The only time when you can possibly do this is before the core drops to the ground.

**Comment by joshuaptfan** [comment]
An alternative solution is to modify campaign random map generation to guarantee that unbuildable tiles are not generated under the core schematic.

**Comment by MEEPofFaith** [comment]
no, i'm thinking from the launch screen somehow, like an extra button next to setting starting resources or something.

**Comment by itcannotbe** [comment]
> An alternative solution is to modify campaign random map generation to guarantee that unbuildable tiles are not generated under the core schematic.

While that would be a great idea. I'm not a fan of having a circular hole so that a core schematic would fit in.



> no, i'm thinking from the launch screen somehow, like an extra button next to setting starting resources or something.

That would involve either blindly doing it or loading the entire map and making it a preview then presenting it that way......

**Comment by joshuaptfan** [comment]
> While that would be a great idea. I'm not a fan of having a circular hole in the terrain so that a core schematic would fit in.

There are more elegant ways to do it. The map generator can look at tiles actually used by the core schematic (with a buffer radius around that), and try to generate natural-looking terrain edges by pathfinding a boundary around that, similar to the algorithm used to guarantee a path from the enemy spawn to the core.

**Comment by lammaer** [comment]
I would say lets aim for the perfect solution: upon landing, the player can place the core schematic in the designated area (just as we can place any schematic during the regular gameplay). 
Lets say scrolling of the map is disabled and the selected schematic cannot be changed.

**Comment by UltraBlackLinux** [comment]
bumping this because man is it annoying
