### ISSUE TITLE
Mining Drone Resource Selection

### ISSUE THREAD

**Issue by JCollins2** [Anuken/Mindustry-Suggestions#184]
**Describe the content or mechanics you are proposing.**

I think players should be able to select which resource they want a Draug Miner Drone Factory to focus on. This would mean a resource selection menu like a sorter's or like the players selection of resources to mine (since only certain materials are available at each location, letting the player find a patch manually denies the possibility that the mining drone could be without resources to mine).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will allow players to more freely decide how they control Draug Miner Drones, and therefor get resources faster in early stages of the game when only mechanical drills are available. Players will have more choice this way.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
so.. You want a control module, for a bot, that can only mine two resources, when the ai auto paths to mine the closest ore of the material that is lowest in the core.

**Comment by itcannotbe** [comment]
"I'm just not sure how well this plan was thought through." - Dinosaur from Meet the Robinsons

**Comment by nichrosia** [comment]
I have a very similar idea, which is allowing mining drones to deposit their resources in containers/vaults other than the cores.
(Yes, I know you can use an unloader block on the core.)
Also, in my previous feature request for upgraded draug drone, Anuken responded saying they are on the Trello, so choosing which resource would be useful later with more powerful mining drones.

**Comment by jaygamer81** [comment]
Smart idea. Pretty useless when it can mine 2 items doe.
