### ISSUE TITLE
Sandbox logic processer

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1840]
**Describe the content or mechanics you are proposing.** a sandbox logic processer with massive range like 100 or more and has customizable logic reading speed or just make it 3000 speed

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**it will allow for better sandbox logic possibilitys and more sand box fun!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

I am not a logic person but i think this will help every person who uses logic out there

**Comment by DeltaNedas** [comment]
mod

**Comment by DeltaNedas** [comment]
> I am not a logic person

then why did you open this, surely a logic user would've done so before.

**Comment by TheNightglow** [comment]
I think this is actually a good idea

for my attack map I gave the enemy logic to improve their factory build units, aswell as some other logic to launch specific behaviour when specific structures were destroyed

and I had some trouble with processor range when doing so.

A large-range high speed sandbox processor would do great for attack map design, simillar to the sandbox item sources

**Comment by itcannotbe** [comment]
Player be like: snipe snipe the processor.

**Comment by TheNightglow** [comment]
> 
> Player be like: snipe snipe the processor.

yea exactly, I build my attack map to have specific weakpoints, so the player has a chance/ specific strategies that work better or worse against the enemy

kinda like a puzzle you need to figgure out

like it is pretty much neccessary to go out of your way to take over the control room and the power sources befor you really have much of the chance to attack the core

its something you can well balance in the attack map design, and an additional objective the enemy tries to defend besides the core and the power generation

**Comment by joshuaptfan** [comment]
> has customizable logic reading speed

Nah, letting the player set the speed is like [downloading more RAM](https://downloadmoreram.com/). Otherwise good suggestion, a logic counterpart to item/liquid/power sources.
