### ISSUE TITLE
Refresh Button for Mod List

### ISSUE THREAD

**Issue by FadeShock** [Anuken/Mindustry-Suggestions#1841]
**Describe the content or mechanics you are proposing.**

Since the implementation of the automatic list refresh is now live, how about the ability to manually refresh the mod list with a button? It could be present on the opposite side of the search bar.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It adds the option of being able to manually refresh the mod list, which is nice when, say, you know a mod update hit but the mod list won't refresh for the next 4 hours. I'm aware you could go to the mod's Github page and manually download and import it, but the need to do that by refreshing the mod page when you need to, in addition to the automatic refresh.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
The mod list is not stored on the client, it's stored [here](https://github.com/Anuken/MindustryMods). You can't refresh it from the client with a button.
