### ISSUE TITLE
Units shouldn't flash when taking very small amounts of damage

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#1842]
**Describe what you would like changed, and why.**
When a unit gets hit, it and its health bar will flash white. However, it will do this regardless of how negligibly low the damage is. Mostly to stop tsunamis and waves filled with water, cryofluid or oil from preventing readability of other damage.

**Describe the changes you want to propose. Include possible alternatives.**
If a unit takes damage under a very small percentage of its max health then it will not flash.
An alternative is to scale the length or brightness of the flash based on the percentage or amount of damage the unit takes.

**Comment by SheepCommander** [comment]
I think I like the scaling idea

**Comment by Humanoid-X** [comment]
good
