### ISSUE TITLE
A unit type that can produce units

### ISSUE THREAD

**Issue by hiimdug2** [Anuken/Mindustry-Suggestions#1843]
**Describe the content or mechanics you are proposing.**
for this unit t1 it can only repair other t1-2 units, t2 it can create t1 units, t3 it can repair t3-4 units, t4 it can create t2 units, t5 it can repair all units. it would have its own unit building station and would cost a lot to build. it would need resources to be put in it manually to construct units, but you could use logic to automatically feed it what it requires. it would be stationary on the ground when creating units. it would also have low health so that it would need to be escorted places. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it would make more people be interested in learning how to use logic and working out specific routes to attack. it could also be used to create more interesting maps because instead of having a large area and building units to go into enemy territory you may only have a small are to work with getting resources in so you'd need to create a unit to slowly build units as you go. it could be used to make maps where you don't have time to build units then take them to the enemy area instead you need them there immediately.  basically it could be used to be more tactful with attacks and make more interesting maps. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Axzye** [comment]
That's what payloads, the two support trees and omura are for...

**Comment by Quick-korkc** [comment]
omura can produce flare...
nova, poly, and oct have heal aura
