### ISSUE TITLE
When making a naval factory, it should by default be the risso tree

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#1844]
**Describe what you would like changed, and why.**
Title. This is since we have only one naval tree anyway, might as well have it default when you make a factory.

**Describe the changes you want to propose. Include possible alternatives.**

eh.

**Comment by SheepCommander** [comment]
That is some top tier laziness.

Both the suggested content, and the suggestion itself, are complete shows of laziness.

Anyways I guess I half agree
