### ISSUE TITLE
Allow multiple IP addresses to connect to a server

### ISSUE THREAD

**Issue by DarkChowder** [Anuken/Mindustry-Suggestions#1845]
**Describe what you would like changed, and why.**
I noticed in the release notes that duplicate IP addresses are blocked, this would prevent people from playing on the same server from the same building, if the server isn't on the local LAN, because the server would see them all under the same IP. This is more likely to hurt family members who are trying to play on the same server together, which is why most games don't do this.

**Describe the changes you want to propose. Include possible alternatives.**
Let server owners see the duplicate IP, and decide, so people in the same house can play on a server if they decide to pay for a server host.

**Comment by itcannotbe** [comment]
This is a server config already.

**Comment by itcannotbe** [comment]
See responses:

https://github.com/Anuken/Mindustry/issues/4396

**Comment by DarkChowder** [comment]
There is a setting for duplicates, but it's no longer reasonable to have it turned on, because it blocks people who share the same IP, which is fairly common. If you want to play with someone, it's probably someone you know. That person may live in the same place as you, so you connect to the same server, and then it fails. This means servers will lose all duplicate protection to avoid having the setting on.

I also want you to consider
If someone malicious does join the server, it's actually better in the long run if they do something obvious, because you can ban them, and get it over with, rather then them ruining the game for a longer period of time in a more sneaky way.

A malicious person is still malicious, and on your server whether they connect once, or multiple times. So the malicious person can still connect to the server, while you, your friend, or family member cannot connect, because one of them is already on the server.

**Comment by itcannotbe** [comment]
I don't get it why this needs to be discussed further because of 2 reasons.

1. It's a setting that the server owner can toggle at the owners own discretion depending on his preference or the need of the server he runs.

2. If the devs removes this setting for the use of server owners, there are plugins to take it's place anyway.

**Comment by DarkChowder** [comment]
1. It's a setting that previously only blocked malicious people, so was enabled on most servers, but has been changed to also block legitimate users. People will update, and some users won't be able to connect, and they will see a message about already being in the server, and unless they understand networking, which most people don't, they won't be able to figure out why it's not working, or be able to work around it.
2. They don't need to remove the setting, they just need to make it work how people expect it to work.
