### ISSUE TITLE
New naval tree

### ISSUE THREAD

**Issue by juanel-router** [Anuken/Mindustry-Suggestions#1847]
**Describe the content or mechanics you are proposing.**
The naval tree has been a gamechanging addition, but only has 1 tree. Me and others where talking about adding a submarine tree. Submarines will surface in shallow waters, making them vulnerable to normal attacks and will submerge in deep water, being killed by naval units or antisubmarine turret. This turret could be a torpedo launcher. Submarines would use torpedoes against units and coastal sedense and missiles of increasing range (I can accept anything, I just think naval isn't receiving enouth attention)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make naval warfere interesting, as making submarine defense will be important and will make players make normal risso tree just to defend from subs, instead of making water-walking ground units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
mods.

**Comment by itcannotbe** [comment]
What's that #477?

You think OP didn't actually done a quick search in the list of suggestions to make sure this has not been suggested yet?

You know what? I agree with you.

**Comment by RedstonerKBC** [comment]
> You think OP didn't actually done a quick search in the list of suggestions to make sure this has not been suggested yet?

>[X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Well they checked the box so they acknowledged that they did in fact do a quick search, but searching for and actually finding stuff are two different things. Sometimes people miss things, sometimes people choose to ignore what they find. We'll never know. All we know is that they did do a quick search.

Anyways, I agree we need another naval branch. It can't be as op as Rissos are though. Rissos are already crazy strong. A fleet of Brydes can take down anything except foreshadows but a few Omauras are enough to take out any foreshadow defense. Submarines are the most common requested ship I see people talking about.

**Comment by Kyllingene** [comment]
![image](https://user-images.githubusercontent.com/69094702/105401534-3a5beb00-5bdb-11eb-80c5-274e648b5efa.png)

> searching for and actually finding stuff are two different things

#1675 #1268 #690 #550 etc. etc.

### My point is that while they may have checked, literally just looking [here](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+submarine) (I searched "submarine"), you find plenty of previous suggestions. They did not do a thorough search in the least.
