### ISSUE TITLE
New looks with 3D shaders

### ISSUE THREAD

**Issue by Soham-maiti** [Anuken/Mindustry-Suggestions#1848]
**Describe the content or mechanics you are proposing.**
I think the game would be better in looks with the new 3D-2D shader which could be given when you are in a sector.
So, that will give the game a better UI and while gameplay it will look awsome as the sun goes down and night takes
place.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this might be the last ever thing u needed for the UI and gameplay so please think about this very well before closing the issue

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Soham-maiti** [comment]
It might seem too much work but if u could do the 3D planets why not this?

**Comment by Cherriodude** [comment]
What exactly do you mean by these "3d" shaders? Are you talking about shadow? How is it related to the UI?

**Comment by the-kido** [comment]
If you are talking about shadows, ive already suggested it here: #911

**Comment by Kyllingene** [comment]
I think they want the game to be rendered in 3D, and have shadows as a result. *If* I am correct, I wholeheartedly disagree. If I am wrong, please explain what you mean.

**Comment by Soham-maiti** [comment]
ok i guess the fact that about shadows is correct but i also wanted the UI to be a bit more 3D.
PS : if u need some more info hit me in the DM in discord my name is sm#6900.

**Comment by Soham-maiti** [comment]
One more thing is they need reflections too

**Comment by notrealn** [comment]
3d ui????? what????
