### ISSUE TITLE
Wave limit

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#1851]
A setting in the rule of the map, where you can limit how many waves before map ends (just like how survival campaign sectors works)

There are times, where lategame is just so boring because defence is powerful (especially multiplayer where you might get banned) so this issue ends the map when a selected wave is completed

1. - [X] - yes
2. - [X] - yes
3. - [X] - yes
4. - [X] - yes

**Comment by Cherriodude** [comment]
Why did you delete the template?
Altho I do agree after late game it just becomes boring, you basically just finished the map.

**Comment by itcannotbe** [comment]
The OP just didn't include the actual template but everything the template asks, OP answered.

**Comment by Jammo2000** [comment]
He followed the template, then removed it. That's fine.

**Comment by SheepCommander** [comment]
That makes sense

**Comment by Cherriodude** [comment]
But why?
