### ISSUE TITLE
Reimplement Unit Health Multiplier

### ISSUE THREAD

**Issue by Fish-Noises** [Anuken/Mindustry-Suggestions#1853]
**Describe what you would like changed, and why.**
The Unit Health Multiplier was suddenly removed in Build 123.1 for no apparent reason. It cannot be found in the customise rules page before starting a custom game, nor can it be found in the editor's map rule settings. If this is an error, please reinstate this option.
**Describe the changes you want to propose. Include possible alternatives.**
Title. I believe its removal was most likely an error.

**Comment by itcannotbe** [comment]
It isn't.

**Comment by Humanoid-X** [comment]
But why

**Comment by Humanoid-X** [comment]
@itcannotbe But why

**Comment by Fish-Noises** [comment]
![image](https://user-images.githubusercontent.com/76248882/105455173-0106a680-5cd3-11eb-9c09-45506017a9cb.png)
@itcannotbe Explain. Unit Health Multiplier had previously been above the Unit Damage Multiplier. But now it isn't.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry/issues/4395

**Comment by Fish-Noises** [comment]
oh.
