### ISSUE TITLE
small cutscene and credits after accelerating from serpulo

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1855]
**Describe the content or mechanics you are proposing.**
right now, when you finally activate the accelerator, after that tense final battle against the crux core, after all your preparations and exports and hours of grinding, all that shows up is "youve reached the end of the campaign!". no "thank you", no "good job", no nothing, so i really think the campaign should get itself a credits screen. to make players actually feel accomplished after completing the campaign. in fact, i was more excited doing basically everything else at PLT than when i clicked the accelerator. it's just really underwhelming.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it'll give players a sense of reward when finishing the campaign, something lots of people never end up doing. you could thank the community, the people who greatly helped you, etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
There's really no reason to add all that, because the accelerator is just unfinished content. It's not the end of the game, and I'm not going to waste time making an elaborate credits sequence just to remove it the next update.

**Comment by sup3r87** [comment]
> There's really no reason to add all that, because the accelerator is just unfinished content. It's not the end of the game, and I'm not going to waste time making an elaborate credits sequence just to remove it the next update.

good point, maybe after the last planet on the vanilla campaign could be an option? not sure what the plans are for the other planets

**Comment by Soham-maiti** [comment]
Maybe not credits but the whole games and every sector need a cutscene and more story play.
