### ISSUE TITLE
Remove Slava0135

### ISSUE THREAD

**Issue by Sh1tonfire** [Anuken/Mindustry-Suggestions#1857]
**Describe what you would like changed, and why.**

I suggest the removal of @Slava0135

reasons: 
- clutters up `#development` with "petition"s
- opens pull requests that were already proposed in `#pulls` and disliked by many people (sometimes including anuke)
- this, and stuff similar
![chrome_X9HvijQaHI](https://user-images.githubusercontent.com/76805872/105525732-82b9fc80-5cf2-11eb-8863-1041e6a7bbe6.png)

**Describe the changes you want to propose. Include possible alternatives.**

possible alternatives mostly exist in `#pulls`, though there is no need for an alternative.

**Comment by RedstonerKBC** [comment]
I thought this place was for the game, not for Discord. Then why tf do mods even exist if we have to come here to report people?

**Comment by genNAowl** [comment]
![8A030A96-4634-42DA-BE32-AFAE7C3E6259_4_5005_c](https://user-images.githubusercontent.com/68400583/105538042-b58ad300-5ca7-11eb-93e0-d4d1d16803e7.jpeg)

![6529D0B3-3D12-4F06-BE38-88F6A4E14BA4_4_5005_c](https://user-images.githubusercontent.com/68400583/105538113-c9ced000-5ca7-11eb-8cb9-81d8f13a1277.jpeg)

Oh No

**Comment by QmelZ** [comment]
~~does that mean the suggestion is accepted?~~

**Comment by SheepCommander** [comment]
**Yes**

**Comment by QmelZ** [comment]
alright then, lets just

**Comment by Sh1tonfire** [comment]
:)

**Comment by catatagun** [comment]
SLAVA0135 IS NO MORE

**Comment by SheepCommander** [comment]
Lmao on one hand **yes** on the other hand *imagine having an entire petition to remove you from suggesting*
