### ISSUE TITLE
Added Schematic support for mobile

### ISSUE THREAD

**Issue by FoolishFooler** [Anuken/Mindustry-Suggestions#1858]
I suggest that there become an easier way to import schematics into Mobile Mindustry, as most file formats, including the one used on the Mindustry discord server, cannot be downloaded on certain mobile devices.

This will help fix gaps of possibilities between platforms.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Text codes can be easily copied to the clipboard regardless of platform. Unfortunately, on the Discord, they are automatically converted to files which are a pain to download and browse for (mostly a complaint about the file browser).

**Comment by DeltaNedas** [comment]
if proprietary file pickers being terrible is the issue, what does mindustry have to do with it.

**Comment by TheNightglow** [comment]
well i guess the only way to solve this would be to host an own server for schematic sharing purposes and have an interface in game to download from this server.

sounds expensive tho
