### ISSUE TITLE
Fast resource launch selection

### ISSUE THREAD

**Issue by Avinash12429** [Anuken/Mindustry-Suggestions#1859]
Can you can make fast launch panel in screen which can make fast launch selection to sectors without going into each sector and selecting from its launch pad to select sectors and dont remove the current system just add this together.this will make launch much fast and accessible without wasting time.

**Comment by SheepCommander** [comment]
Don't delete the template, and I can't quite figure out what you're saying

**Comment by TheNightglow** [comment]
I think what Avinash is trying to say is:

Entering every sector to select the launch pad and link it to the new location is bothersome,
a button on the world map (to for instance tell all launch pads to target the current sector) would be prefered

Anyway, I personally would prefer something like being able to visually connect launch paths in the world map (as in dragging a path from Sector A to Sector B to say A should launch to B)

**Comment by Avinash12429** [comment]
I am a android platform mindustry player and its really time consuming when selecting sectors to launch to a sector from a launchpad from each sector's launchpad.And i am not good enough in english i wish feature come in this game or similar feature like this
