### ISSUE TITLE
Weapons Modifications Factory

### ISSUE THREAD

**Issue by DAVEtheDuck2287** [Anuken/Mindustry-Suggestions#186]
What is the Weapons Modification Factory? Well, it's a new construct for player controlled drones to edit and adjust their current mech with different types of weapons. I.e. Anti-air, Ground, Laser, etc. or even upgrade the stats of the current mech. These upgrades will have a cost in power and resources of course. Specific mechs can only get specific upgrades.

How will this improve the game? Well, it opens up the game to more variety of gameplay and versatility to already existing mechs, and increase the general playing experience since certain mechs have different stats can't really be used in certain situations.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
un-believably, this is already being implemented. If only it were possible to check the future changelog for the game. Oh wait, https://trello.com/b/aE2tcUwF/mindustry-trello has it. AMAZING!!
