### ISSUE TITLE
Alarm Block (Logic)

### ISSUE THREAD

**Issue by FoolishFooler** [Anuken/Mindustry-Suggestions#1860]
**Describe the content or mechanics you are proposing.**
I propose the concept of an “alarm” block. It can be set to show an in-game message upon being activated through the use of other logic blocks. It may be used to show the lack of a specific material in your sector, loss of power, or the breach of defences during an attack.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I believe this will help people retain control over their sectors, as they can immediately notice and fix problems.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
duplicate of: #1108 #810 #680 #263

*and* its on the trello

don’t open an issue unless you checked all the boxes

**Comment by joshuaptfan** [comment]
Everything you're asking for can be done with logic without a new logic block. Learn more logic.

**Comment by RedstonerKBC** [comment]
Wow! Someone who's being honest and not just saying what they have to just to survive in these hard times. You don't see that very often anymore. Wouldn't it be nice if all of the other duplicate posts were honest too?

**Comment by Humanoid-X** [comment]
lol such an honest man must be treated well...

**Comment by Catchears** [comment]
> Everything you're asking for can already be done with logic without a new logic block. Learn more logic.

I think @FoolishFooler may mean a block which will alert you across sectors, so that you can be informed when your power dies in a different sector and go to fix it.

**Comment by Kyllingene** [comment]
> which will alert you across sectors, so that you can be informed when your power dies in a different sector and go to fix it.

Actually, no real actions go on when you leave a sector (see comments on #1731), which means power cannot be functional when you leave and die as you are on a different one. In fact, power doesn't even affect anything in the sector, as the outputs/inputs of each important block (launch pad, core, etc.) is pre-calculated and then the game assumes that it will maintain that exact performance after you leave.

**Comment by Catchears** [comment]
> > which will alert you across sectors, so that you can be informed when your power dies in a different sector and go to fix it.
> 
> Actually, no real actions go on when you leave a sector (see comments on #1731), which means power cannot be functional when you leave and die as you are on a different one. In fact, power doesn't even affect anything in the sector, as the outputs/inputs of each important block (launch pad, core, etc.) is pre-calculated and then the game assumes that it will maintain that exact performance after you leave.

Ah, I assumed that it would update them occasionally. Thanks for correcting me.
