### ISSUE TITLE
rename dark panel 1

### ISSUE THREAD

**Issue by Mieew** [Anuken/Mindustry-Suggestions#1861]
**Describe what you would like changed, and why.**
rename dark panel 1 in the editor to damaged dark panel beacuse it makes more sense like that and it looks damaged

**Describe the changes you want to propose. Include possible alternatives.**
i cant think of an alternative

**Comment by RedstonerKBC** [comment]
Bruh you didn't check the boxes. This means you admitted you have no idea about how the game even works. How can we trust that you even know what a Dark Panel is?

**Comment by catatagun** [comment]
> **Describe what you would like changed, and why.**
> rename dark panel 1 in the editor to damaged dark panel beacuse it makes more sense like that and it looks damaged
> 
> **Describe the changes you want to propose. Include possible alternatives.**
> i cant think of an alternative

BAD NO CHECK BOX

**Comment by Kyllingene** [comment]
> BAD NO CHECK BOX

> Bruh you didn't check the boxes. This means you admitted you have no idea about how the game even works. How can we trust that you even know what a Dark Panel is?

The "balancing/feedback" format ***has no checkboxes***. Only the "feature request" template does.

**Comment by Humanoid-X** [comment]
@Kyllingene Yeah, agree, I wonder why you guys are not even looking at the tag

**Comment by Kyllingene** [comment]
@RedstonerKBC @catatagun Have you two realized your mistake? If so, please remove your overly hasty comments or otherwise indicate that you realize this is perfectly fine. Also, I agree, Mieew.

**Comment by RedstonerKBC** [comment]
I realize this is perfectly fine, this as in it's ok to not have to check any boxes. I was wrong. Sorry Mieew. I thought suggestions and feedback/balancing had the same required checkboxes.

No I will not remove my comment. Unlike mainstream values I do not believe in censorship. If you don't like your past you shouldn't have made those mistakes in the first place. The mainstream demands transparency but they remove anything that offends them, which is very hypocritical. I'm leaving it there so that anyone in the future can understand the context of the past and form their own ideas rather than being told what to think.

**Comment by Kyllingene** [comment]
> Unlike mainstream values I do not believe in censorship.

Neither do I, I just wanted some acknowledgement.

> The mainstream demands transparency but they remove anything that offends them, which is very hypocritical.

I agree more than you know.

> I'm leaving it there so that anyone in the future can understand the context of the past and form their own ideas rather than being told what to think.

Fair, although I'm not sure how removing that comment which says nothing about the original post forms peoples ideas of said post.

**Comment by Mieew** [comment]
> I realize this is perfectly fine, this as in it's ok to not have to check any boxes. I was wrong. Sorry Mieew. I thought suggestions and feedback/balancing had the same required checkboxes.
> 
> No I will not remove my comment. Unlike mainstream values I do not believe in censorship. If you don't like your past you shouldn't have made those mistakes in the first place. The mainstream demands transparency but they remove anything that offends them, which is very hypocritical. I'm leaving it there so that anyone in the future can understand the context of the past and form their own ideas rather than being told what to think.

its okay

**Comment by RouterChainsSuckk** [comment]
> Bruh you didn't check the boxes. This means you admitted you have no idea about how the game even works. How can we trust that you even know what a Dark Panel is?

how can we trust that you even know how github works?
