### ISSUE TITLE
older OpenGL support

### ISSUE THREAD

**Issue by AstronautCat380** [Anuken/Mindustry-Suggestions#1862]
**Describe the content or mechanics you are proposing.**
older opengl supports a game that weighs nothing

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

since the game is very light, I try to run on cell phones.
but I find it a bit annoying that it is not supported by older opengl, ex: opengl 1.4 table.
why this supports minecraft which is heavier. but the mindustry, which is 10x lighter, does not support it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AstronautCat380** [comment]
just before letting me know i use a translator so a wrong translation can come out

**Comment by AstronautCat380** [comment]
just a warning i use translator

**Comment by Anuken** [comment]
Not happening. Minecraft was designed with ancient OpenGL immediate-mode rendering initially; Mindustry uses shaders only and has absolutely no support for such things. Any phone/PC too ancient to support OpenGL 2.0 (*released in 2004!*) is likely too weak to run Mindustry properly anyway. Get a better device.

**Comment by AstronautCat380** [comment]
but my graphics chip was made in 2009 not to mention that my cpu is a 3.2ghz dual core so i believe it is strong enough to run

**Comment by AstronautCat380** [comment]
I tried to update my video drive but it never leaves opengl 1.4 which is strange.
but even being older my pc is strong only because of this problem he doesn't even want to open it

**Comment by AstronautCat380** [comment]
always shows it:
Your graphics card does not support the right opengl features.
try to update your graphics drivers. if this doesn't work, your computer may not support mindustry.
full message: opengl 2.0 or higher with the fbo extension is required. opengl version:1.4 mesa 20.2.6

**Comment by DeltaNedas** [comment]
ok then install opengl 2.0 or higher:
`apt install libgl1-mesa-glx`

**Comment by Kyllingene** [comment]
> ok then install opengl 2.0 or higher:
> `apt install libgl1-mesa-glx`

Linux only (according to command prompt and Google).
