### ISSUE TITLE
Incomplete translations (Spanish)

### ISSUE THREAD

**Issue by AdriaGar** [Anuken/Mindustry-Suggestions#1863]
**Describe what you would like changed, and why.**

I don't know if it was intentional, but the turret names are not translated (at least into Spanish).  I say this because before if they were translated.

**Describe the changes you want to propose. Include possible alternatives.**

If possible, you could translate the names of the turrets. Maybe you could also translate the logic section, or / and put a manual or a small tutorial

**Comment by RedstonerKBC** [comment]
Spanish got banned in the discord. They don't even care enough to provide a link to the new spanish channel. I highly doubt they care about spanish translations or else this wouldn't be suggestion.

**Comment by DeltaNedas** [comment]
1. theres 3 suggestions here
2. since you know english and splanish, translate them yourself (i highly doubt all the turrets are not translated though)
3. deltanedas/rtfm

**Comment by AdriaGar** [comment]
> 1. theres 3 suggestions here
> 2. since you know english and splanish, translate them yourself (i highly doubt all the turrets are not translated though)
> 3. deltanedas/rtfm

Duo==duo
Scatter==dispersor
Hail==granizo
Salvo==salva
Cyclone==ciclón
Spectre==espectro
Scorch==quemador
Arc==arco
Lancer==lancero
Meltdown==fusion de reactor
Segment==segmento
Ripple==onda
Fuse==fusible
Swarmer==enjambre

I hope it helps you
Attentively
AdriG

**Comment by Kyllingene** [comment]
I believe the idea was to update [this](https://github.com/Anuken/Mindustry/blob/master/core/assets/bundles/bundle_es.properties#L995) file with those translations. Note: Anuken put in this line:

> #Names of Units and Turrets look better untranslated, since they are proper/own names

so he might not want them changed. Still, you could do a quick PR and test his thoughts.
