### ISSUE TITLE
Chat translator

### ISSUE THREAD

**Issue by AdriaGar** [Anuken/Mindustry-Suggestions#1864]
**Describe what you would like changed, and why.**

I propose to add a translator to the chat on the servers, for better communication between people from different parts of the world

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by joshuaptfan** [comment]
Would require a [translation API](https://blog.api.rakuten.net/top-10-best-translation-apis-google-translate-microsoft-translator-and-others/#Top_10_Best_APIs_for_Translation) with source language detection, many of which charge a fee. Probably not feasible.

**Comment by DeltaNedas** [comment]
i believe theres a plugin for this already and see above

**Comment by Brandons404** [comment]
> i believe theres a plugin for this already and see above

Could you point me to this if it exists? I've been looking around and cant find anything. I've definitely seen it on one of the servers before.
