### ISSUE TITLE
conveyor and drill automatic upgrader

### ISSUE THREAD

**Issue by Minimaxi28** [Anuken/Mindustry-Suggestions#1865]
**Describe the content or mechanics you are proposing.**

Like the upgrade planner in factorio, a new button (see picture) that will let you make an area (like the one that copy things) and when released it will automatically put pneumatic drill instead of mechanical drill and titanium conveyor instead of normal conveyor. It wil not construct instantly, it will just plan it.
![Captture](https://user-images.githubusercontent.com/68665659/105613162-3b4e7180-5dc1-11eb-97b5-2e6725673134.PNG)
(I was thinking of a white arrow pointing up)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This is a QOL feature, when you want to optimise an ore patch at the beginning of a game you put drills in weird ways so you need to click on every one of them to upgrade them. Same goes for the conveyors, you put them in weird ways and you need to click on every one of them to upgrade them.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
> maybe here
> ...
> i was thinking of a white arrow pointing up

what about mobile users? on mobile that part has 4 buttons and has no free space

also, this sounds a lot like #1728, #1049, and quite a bit more that i am too lazy to find.

**Comment by joshuaptfan** [comment]
> Same goes for the conveyors, you put them in weird ways and you need to click on every one of them to upgrade them.

[There is a conveyor upgrade system in the game.](https://github.com/Anuken/Mindustry/pull/3912)

**Comment by Minimaxi28** [comment]
> > Same goes for the conveyors, you put them in weird ways and you need to click on every one of them to upgrade them.
> 
> [There is a conveyor upgrade system in the game](https://github.com/Anuken/Mindustry/pull/3912), just hold Ctrl.

Oh my god I didn't know you could do that thanks for showing it to me :)

**Comment by itcannotbe** [comment]
Can we get some closure then?
