### ISSUE TITLE
Add a balancing channel

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry-Suggestions#1866]
**Describe what you would like changed, and why.**
Only one thing: pollution. Say what you will, but if anyone needed message pollution, #development would still be here.

I think it's better to add a new channel. Because frankly, there's plenty of discussions happening in #pulls that are healthy for the community. Balancing discussions people have there are often better than those that happen on this repo. But rules prohibit them. This creates confusion. Should a user contribute to the existing discussion and risk a channel getting closed, or should he just shut up and reduce his actions to what's allowed?

**Describe the changes you want to propose. Include possible alternatives.**
Add a new channel. Alternatively, get more aggressive mods (the downside of this is that there will still be no place for the discussions to take place).

Things that don't work:
- Existing moderators. They are nice, that's all.
- Backseat moderating, because rules get no respect if you don't have a role.
- Doing nothing.

**Comment by YellOw139** [comment]
I don't really see how sending reactions but no messages, and less reactions than initial polluting messages is more polluting.

Yet I have to admit, it's not efficient.

**Comment by joshuaptfan** [comment]
If we had an informal suggestion channel (#1627) that puts no pressure on Anuke to monitor, that would pretty much cover the topic of balancing, as a lot of suggestions are going to be suggestions about balancing.

**Comment by DeltaNedas** [comment]
https://matrix.to/#/#mindustry-balancing:matrix.org

**Comment by YellOw139** [comment]
That was actually a good idea, Delta, but good luck getting people to actually move their discussion there.

**Comment by GreyMario** [comment]
Why should _you_ care? Your only contribution to #pulls is spamming reacts anyway.

**Comment by Kyllingene** [comment]
> Why should you care? Your only contribution to #pulls is spamming reacts anyway.

Whether or not that is factually correct, it was unnecessary and completely unconstructive (and the slightest bit toxic).

**Comment by GreyMario** [comment]
> > Why should you care? Your only contribution to #pulls is spamming reacts anyway.
> 
> Whether or not that is factually correct, it was unnecessary and completely unconstructive (and the slightest bit toxic).

So... basically... no worse than the OP in this thread. Cool double standard.

**Comment by YellOw139** [comment]
> Why should _you_ care? Your only contribution to #pulls is spamming reacts anyway.

I participated in balancing discussions in #development because despite the rules nothing was enforced there. For instance, I kept running my test map for various versions of BE, agreeing with the fact that megas were too strong. I noticed when Zeniths were finally rebalanced to beating Megas in my map and posted my results there, ending the whole debate. Search for it.

It's hard to contribute without spamming when everyone agrees: buff that, nerf that, what does Anuke win if I just add my message to the countless messages saying the same thing? I usually like to prove points or express something different, but most times there's no such stuff to be said.

As for my contribution to #pulls, I did comment on an open PR once. Again, it's hard to talk about the game's code when all you know about Java is your intent to start learning it at a later date. So I just follow the channel, seeing what happens, what others think, not having much to contribute unless it's rule breaking discussions, and even there I won't share pointless agreeing. I will share new facts, provided that I have any.

That still doesn't mean that I don't follow the channel on an almost daily basis or sympathize with how many not on topic discussions Anuke has to go through every day. (Remember Slava's petitions? Doubt Anuke needed to see most stuff he said there more than once per topic.) I wish joking around was on topic, but it's not, otherwise I'd have probably joined the party by now.

As for the reacts tried to keep the channel clean. I am aware it was not efficient. I am aware I could have just shut up (or sent messages to make things even worse). At this point, I am wondering why I keep refusing to join the not on topic discussions there, because I wanted to on occasion, but no, cuz rules, cuz poor Anuke, cuz, cuz, cuz...

So I'd say stop judging. I don't think it does matter too much who within the userbase cares when Anuke does. (If he didn't, #development would still be here, and rules of #pulls would not tell those who do not talk about PRs or the game's code to shut up.) That channel is needed for collaboration between contributors, not for feedback. Feedback gets itself lost here, when it would propaply feel more at home in a new balancing channel.

**Comment by YellOw139** [comment]
> So... basically... no worse than the OP in this thread. Cool double standard.

I agree. Cool. Now what did _you_ do?
Nothing, and that's not a big problem. But when everyone does nothing, it becomes a big problem. Remember #development? That was chaos, and that's what we risk.

**Comment by Kyllingene** [comment]
> So... basically... no worse than the OP in this thread. Cool double standard.

Except that their suggestion makes literally *any sense*, whereas your comment only served to mention a completely irrelevant fact.

**Comment by SheepCommander** [comment]
I do not think suggestions would work well as a channel. Using issues is much easier since you can track each one, close them, search for duplicates easier, and not have overlapping hectic conversations.

This way you can also leave them alone. Turning this into a discord channel would only increase the problem of polution, and same with Moderators. Using Issues if they're not accepted they can simply be ignored

**Comment by YellOw139** [comment]
>  Using issues is much easier since you can [...] not have overlapping hectic conversations.

Hectic conversations about balancing seem to be very in need of a separate dedicated place. Despite this repo existing and despite balancing suggestions being posted here, they persist, bleeding into other Discord channels.
I left the channel alone while sleeping.

![image](https://user-images.githubusercontent.com/70975516/105817836-d3657a00-5fbe-11eb-8c15-cdb645a52a95.png)

I've got to give credit to Slava for stopping the discussion. After starting it. And participating. Still, he stopped. Well, after all people started to realize, so that is good. I wonder what happened... I wonder where we'd be if nothing happened. Or if nothing keeps happening. Let's see how the situation evolves.

> This way you can also leave them alone. Turning this into a discord channel would only increase the problem of polution, and same with Moderators. Using Issues if they're not accepted they can simply be ignored

I never suggested turning *this repo* into a channel or moving all suggestions there.

I suggested having a separate place inside the Discord server to discuss balancing specifically instead of polluting #pulls. There are some balancing discussions people will refuse to have *only* here or here at all no matter what.

There are a lot of questions asked hypothetically, like why are T3 units like that or why are solar panels like that... Issues craving, perhaps, too much attention. Issues related to changing individual values (buff this, nerf that), and not to making specific sections of code better. Arguably better code can create better balance, but #pulls is for code, not for 'make this simple change to this little value and suddenly the balance is perfect and everything about multiplayer is all good'. Such discussions leave the code itself untouched.

If you think balancing should be discussed *only* here, feel free to suggest stuff that facilitates or enforces that. Needless to say, it will not happen on its own, and I do not see how moving from Discord to other place on Discord will affect the amount of discussions that do not happen here regardless.

**Comment by joshuaptfan** [comment]
> I do not think suggestions would work well as a channel. Using issues is much easier since you can track each one, close them, search for duplicates easier, and not have overlapping hectic conversations.

A suggestions channel would not be a place to submit suggestions, only discuss them with other players before submitting. If there is consensus in the discussion there that a suggestion is good, people should encourage the person who came up with the idea to fill out a template here to formalize it.

**Comment by SheepCommander** [comment]
Guess that could make sense but who knows how many people will be too lazy to use their eyes but can type up a full suggestion and assume that's where suggestions go

**Comment by joshuaptfan** [comment]
That's fine. If they're too lazy to take their suggestion from the discussion channel to here, then they probably would not have filed a coherent suggestion here.

It would be a relief valve to relieve pressure on other channels where suggestions don't belong, and a place where more experienced players can reject bad ideas before they get submitted here.

**Comment by SheepCommander** [comment]
Guess that makes sense I'm with you now

**Comment by itcannotbe** [comment]
Why not an "open" suggestions channel that deletes messages except that message that suggestions and their respective discussions go in this repository?

**Comment by SheepCommander** [comment]
that would work I guess

**Comment by YellOw139** [comment]
> Why not an "open" suggestions channel that deletes messages in 5 seconds except that message that suggestions and their respective discussions go in this repository?

That's besides the scope of this suggestion, as it doesn't stop the #pulls pollution at all. If a balancing or suggestions channel like that would be added though, expect no one to use it.

People just want to use Discord. Discord fulfills their need for fluent communication, but it doesn't fulfill the important need for organized communication that's so pressing. But people can't understand that, and use Discord almost exclusively. It's unfortunate, I know. 

One cannot stop people from using Discord. Great. If one can't stop them from using Discord, then one can at least find a way for them to use Discord without disrupting other important discussions, which is annoying.

**Comment by YellOw139** [comment]
Thank you.
