### ISSUE TITLE
Space exploration using interplanetary launch pad?

### ISSUE THREAD

**Issue by DaWolfyGamer** [Anuken/Mindustry-Suggestions#1867]
I just recently finished the campaign and was thinking about what the interplanetary launch pad could bring to the game, perhaps where ever u have built the interplanetary launch pad there could be a new type of factory the could build a massive rocket ( very resource heavy ) and then u could use pay load conveyors to bring it to the launch pad or maybe once the launch pad is fully powerd u could click on it and a GUI would pop up that would sorta be simlar to the editor except without infintie resources, u could then pump resources ( copper lead titanium thorium ) to build the space ship, and possibly even bring units as well , cuz i have noticed that u might already be making something like this, cuz in the editor, their is a floor type called space which would be a perfect back drop for a new space map , as well as block named " thurster " as well as other special blocks like the " block forge " that could point towards building of a space ship also, but if something like that was added it would be cool if u could not only go to other planets, but also go to astroids that would have very rare resources like uranium, cuz i looked on the trello board and u plan on adding nuclear tech, so u would have to go to space and wait for a uranium astroid to come by, as well as they would have a limited time in the solar system so u would have to act fast try to get as much of the resource as u can then blast back into ur space ship, possibly even setting up space outposts in the solar system could be possible where they can be attacked at any time but will be able to launch missions to astroids.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it could add new resources, add something that makes going to other planets more fun and dangerous, as well as having limited time astroid go by would make players want to play more. as well as something that could also be attached to it is a better multiplayer system, cuz at the moment its preatty hard to play with friends , especially if their on a phone or tablet, perhaps each solar system could have its own id and then u can give ur friend it and they can come and visit and maybe when a player is in ur solar system, their would be a friend option that would allow u to play with friends much easyier.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
You've done an awful lot of tangential research and put an incredibly ridiculous amount of effort into writing two individual run-on sentences (rather than paragraphs) which can be shut down by the following words:

_Interplanetary travel is slated for V7, and the Interplanetary Accelerator's intended purpose is to enable that._

You've wasted an incredible amount of time dreaming up something incredibly complex, presented so poorly that I'm not even going to bother trying to read even half of it.

**Comment by GreyMario** [comment]
You used an astoundingly low _three_ period symbols across 426 words of run-on _mush_. No one is going to try to read that.

**Comment by MEEPofFaith** [comment]
Have you ever considered reading the pop-up that appears when trying to launch the Interplanetary Accelerator?

**Comment by GreyMario** [comment]
Perhaps [this](https://www.star-made.org/) is the video game you were looking for?

**Comment by flarefluffsune** [comment]
I think I lost IQ reading this.

**Comment by QmelZ** [comment]
seeing the above comments, i am not going to kill my eyes reading that

**Comment by AxemaVales** [comment]
It doesn't hurt to wait for this feature in the future.
