### ISSUE TITLE
block feature.

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry-Suggestions#1868]
**Describe the content or mechanics you are proposing.**
block feature. if you block a player none of theyre messages would appear in chat.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

some people really tick me off, be very racist and all that, but theyre admins. i wanna be able to blokc em

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [z] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
Maybe... go to the community for that server and discuss the problem?

And if they refuse to change, spread the word that that community enables that kind of behavior?

Don't just sit there and say "it's not my problem", because it will only ever get worse.

**Comment by Cherriodude** [comment]
"some people really tick me off, be very racist and all that, but theyre admins."

If the admins are doing that, that's a very concerning problem

**Comment by DeltaNedas** [comment]
still a nice feature

**Comment by RedstonerKBC** [comment]
Best way to deal with this is to screenshot what they say and post it on social media. In a few days the Twitter hyenas will be all over their server demanding it be shut down and the racist lose their job and future careers. I know that sounds stupid but I've seen this happen a billion times over the last decade even with both my college and high school. Cancel culture is a powerful thing, but remember you are ruining someone's entire life by doing so so think carefully if this person really deserves that kind of pressure. Many people have committed suicide because of this.

**Comment by RedstonerKBC** [comment]
I like this idea because a lot of players fight in chat all the time. It gives you peace and quiet and it leaves the server with the right to free speech. If you don't like what someone says they can still play the game but you don't have to listen to them and the server doesn't have to punish everybody for a few bad apples.

**Comment by TeamDoodz** [comment]
> Best way to deal with this is to screenshot what they say and post it on social media. In a few days the Twitter hyenas will be all over their server demanding it be shut down and the racist lose their job and future careers. I know that sounds stupid but I've seen this happen a billion times over the last decade even with both my college and high school. Cancel culture is a powerful thing, but remember you are ruining someone's entire life by doing so so think carefully if this person really deserves that kind of pressure. Many people have committed suicide because of this.

The best way to deal with some stupid toxic kid is to ruin the rest of their life? Sorry Skai Jackson, but I disagree.

**Comment by SheepCommander** [comment]
Although I do agree with a block players feature, the "very racist" part appears to have sparked a mostly separate conversation.

If you are dealing with someone who really ticks you off it can be best to ignore it, but @RedstonerKBC brought up cancel culture in the case that they're excessively racist and @TeamDoodz referred to them as toxic kids.

Both of you are kinda exaggerating. Cancel Culture isn't strong enough or bountiful enough to extend that far easily, much less ruin an entire life, and a toxic kid isn't the same as a racist asshole.

**Comment by RedstonerKBC** [comment]
Kids got to learn somehow. If we don't teach them now what will they become when they turn into adults? You think kids are bad oh no adults are something else! Ruining their entire life that way is the easiest method but it is admitedly messy. I certainly don't want these types of people apart of the Mindustry community but I also don't want to give up our right to free speech. I probably should've thought about this more before commenting but after some time I think bendnuts is right. Adding a block feature protects you from toxic chatters without sacrificing your freedom of speech and also doesn't restrict servers from running the server how they want. Now we'll have a way to kick griefers and ignore toxic chatters without sacrificing anything.
