### ISSUE TITLE
picking up things that is in conveyors

### ISSUE THREAD

**Issue by TheDragonVin26** [Anuken/Mindustry-Suggestions#1869]
**Describe the content or mechanics you are proposing.**
Mix all conveyor's materials into one inventory like core extension

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes it's pretty frustrating picking up ores that shouldn't be in the conveyor belt, especially when they are moving

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Oh, I think I should rephrase it so others wi understand it.
"Mix all conveyor's incentories into one inventory like core extension"

**Comment by itcannotbe** [comment]
> Conveyors should just contain all the materials of the conveyors instead of only 1

I guess stopping the conveyor by destroying 1 tile ahead of the thing you want to remove is extremely hard to do then.

**Comment by QmelZ** [comment]
i dont understand what this is supposed to mean..? its not that hard to take stuff out from conveyors

**Comment by TheDragonVin26** [comment]
I mean sometimes you mess up the entire conveyor its pretty annoying + if they are moving

**Comment by itcannotbe** [comment]
> > Sometimes it's pretty frustrating picking up ores that shouldn't be in the conveyor belt, especially when they are moving
> 
> I guess stopping the conveyor by destroying 1 tile ahead of the thing you want to remove is extremely hard to do then.

My sarcasm didn't work.....

**Comment by SheepCommander** [comment]
No, although if you mean being able to take items out from anywhere in the conveyor line maybe

**Comment by EhTre** [comment]
Maybe just add filter conveyor or something..
