### ISSUE TITLE
Hovering over force projectors show range

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#187]
**Describe the content or mechanics you are proposing.**
Hovering over force projectors should show a hexagonal outline of the force field it's projecting.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Because turrets, mend projectors, and overdrive projectors show range, it would be nice to see the range of force projectors too.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Discussed over at [Add preview outline for Force Projectors on hovering](https://github.com/Anuken/Mindustry/pull/1314)

> Unlike other projectors, force projectors display their radius visually when active. Even when they're broken, you can visualize their radius by middle clicking, so I don't think this is necessary.
