### ISSUE TITLE
Large Launchpad in campaign?

### ISSUE THREAD

**Issue by Blue-Beaker** [Anuken/Mindustry-Suggestions#1870]
**Describe the content or mechanics you are proposing.**
Add Large Launchpad back to the campaign techtree
After the normal launchpad, besides the planetary accelerator.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The Large Launchpad exists, but currently not unlockable in campaign.
If the large launchpad is back, players can use less space for launching items at same rate.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mothership007** [comment]
As far as i know from his trello page, it will probably be used to transfer payload (units, 2x2blocks, etc.) to adjacent sectors.

**Comment by catatagun** [comment]
> As far as i know from his trello page, it will probably be used to transfer payload (units, 2x2blocks, etc.) to adjacent sectors.

Yes answer to how the fuk are the ground units getting to me sector

**Comment by Mothership007** [comment]
> > As far as i know from his trello page, it will probably be used to transfer payload (units, 2x2blocks, etc.) to adjacent sectors.
> 
> Yes answer to how the fuk are the ground units getting to me sector

are you asking how are units getting to your sector? well, using the drop zone. Or they are made on the sector.

**Comment by DeltaNedas** [comment]
>  I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

**Comment by Mothership007** [comment]
> > I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

![Screenshot_20210124-203459](https://user-images.githubusercontent.com/65804425/105641345-b4160200-5e83-11eb-817d-71f4586f946b.png)
This?

**Comment by Blue-Beaker** [comment]
> > > I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
> 
> ![Screenshot_20210124-203459](https://user-images.githubusercontent.com/65804425/105641345-b4160200-5e83-11eb-817d-71f4586f946b.png)
> This?

so this was planned to not only a larger launchpad but also a payload launchpad?
I hope the payload launchpad to seperate from the large launchpad. The large launchpad needs to be the same usage of the normal launchpad according to its name.

**Comment by Kyllingene** [comment]
> The large launchpad needs to be the same usage of the normal launchpad according to its name.

But why? Why can't it also move units?
