### ISSUE TITLE
Unloaders working with turrets

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry-Suggestions#1871]
**Describe the content or mechanics you are proposing.**
Basically unloaders being able to suck items from turrets. This feature works on any container but turrets. As of ui, simmilar effect is noticeable where thorium is unloaded from nuclear reactor- power level goes down as the item amount diminishes.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As various designs benefited from making unloaders work with factories, this time defensive structures would have wider variety to be made.
That's how it could look like:
![unloaders](https://user-images.githubusercontent.com/33349024/105648180-6e206480-5eaa-11eb-8c83-c6528ad1883e.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Impossibru.

**Comment by GreyMario** [comment]
For various reasons that I'm not going to take the time to explain because you could learn them yourself within minutes of investigating, _no._

**Comment by joshuaptfan** [comment]
While this suggestion can technically be implemented by preventing from turrets from instantly converting items into ammo, this is a bad idea for balance reasons.

It would allow players to concentrate large numbers of turrets in small areas with much less space spent on distribution. You would only have to run a conveyor to 1 turret, then feed the rest using unloaders, as can currently be done with RTG generators. Also, since distribution is the weak point of any turret-based defense, it would make turret defenses much harder to defeat in PvP.

**Comment by itcannotbe** [comment]
You would be breaking ammo multiplier if you do that though.

**Comment by Yell245** [comment]
Turrets store amno, not items

**Comment by BlueWolf3682** [comment]
this is possible, if complicated

**Comment by Kubek0212** [comment]
Ok, thanks for clarification. Closing
