### ISSUE TITLE
Jetpack fuel for nova tree

### ISSUE THREAD

**Issue by a-letter** [Anuken/Mindustry-Suggestions#1872]
**Describe the content or mechanics you are proposing.**
Add flying fuel system to nova tree to limit their flying ability. The fuel can be recharge by just standing or by item/power consumption. Similar to ammo, this feature can be disabled in map setting.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Disable anxiaty, enable strategies.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
How is this going to "disable anxiety"? Bruh, just change it so they can only travel in the same places a legs unit can while boosting (unless they're already a legs unit, in which case flying go brrr).

**Comment by Yell245** [comment]
What if your fuel went off when you're on a solid block? Death!

**Comment by itcannotbe** [comment]
The point is for boost to not be infinite, so thing like when to boost are considered by the player.

So yes. Not boosting over a solid block means death.

**Comment by SheepCommander** [comment]
Hmm a per unit fuel system that's refueled via consuming power or resources. What about on a defense map? Does the Nova then suck your stuff or does it just die
