### ISSUE TITLE
draw items flying from core to construction

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1873]
**Describe the content or mechanics you are proposing.**

when a block is being built, draw the items flying from the core to it, similar to the transfer effect but more discernible.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

"wait theres no silicon/copper/lead/titanium"
"always has been"
except you can fly along the silicon snake and ban whoever is wasting

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SheepCommander** [comment]
This does seem kind of cool but I feel like this could effect game performance or get in the way maybe

**Comment by DeltaNedas** [comment]
so does bloom, which is why you can disable it.

**Comment by QmelZ** [comment]
> except you can fly along the silicon snake and ban whoever is wasting

wouldnt expect anything less from you.

cool feature also

**Comment by Yell245** [comment]
It sounds cool and logical like if the core has a magnetic mechanism throwing things into our unit

**Comment by SheepCommander** [comment]
> so does bloom, which is why you can disable it.

true ye. I'd like it as a toggleable feature in settings, wonder if there should be a keybind for it

**Comment by Violet-Scarelli** [comment]
This sounds incredibly useful for multiplayer.

**Comment by SheepCommander** [comment]
Actually ye it does I think I like it even more suddenly lol

**Comment by Slava0135** [comment]
![Peek 2021-01-27 12-43](https://user-images.githubusercontent.com/40753025/105974340-d9cb2300-609e-11eb-8e21-12215e088831.gif)
made a concept

**Comment by Quezler** [comment]
and what if the person is on the other side of the map? super fast particles or the same speed?

**Comment by Slava0135** [comment]
> and what if the person is on the other side of the map? super fast particles or the same speed?

time is constant - so particles will be faster

**Comment by Quezler** [comment]
> particles will be faster
yea don't, on long distances you'll only see 1 or 2 frames from particles passing by, right now the frame count is already like 10 and that's right next to the core

**Comment by Violet-Scarelli** [comment]
If you made the flow begin instantly but flow speed constant, such that particles were "buffered" from the core to the construction as soon as things started to be built there would be particles flowing, that would make it more workable, imo.

**Comment by Quezler** [comment]
+ this can cause visual desyncs, when the core has plenty of items the effect works just fine, but when an item is empty only the server knows where it has gone, causing some construction sites to "speed up" and others to "slow down", so the client side particle wouldn't accurately know where it actually went
