### ISSUE TITLE
The ability to set all troops to go towards a specific area, or follow the person with an advanced command center

### ISSUE THREAD

**Issue by Roger3434** [Anuken/Mindustry-Suggestions#1874]
**Describe the content or mechanics you are proposing.**
The ability to set your troops to go towards a specific area. (using the minimap?)
and/or all following the player with an advanced command center.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will improve troop related gameplay, and give a new goal to achieve when manufaturing troops.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
This can already be done with logic, and was one of the purposes logic was made for.

**Comment by Roger3434** [comment]
thank you
