### ISSUE TITLE
Re adding the retreat command for the command center

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1875]
**Describe the content or mechanics you are proposing.**re add the retreat command for the command center so they return to the core

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** it works now because units dont die when there factory is destroyed and adds more options when a defense is breached

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x
3. ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by catatagun** [comment]
> 
> 1. * [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 2. * [x
> 3. ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

Why does that happen with the x so much

**Comment by TheRealIvyX** [comment]
just use rally

**Comment by SheepCommander** [comment]
Oh return the core was removed? I didn't even realize. I would like it back and as for "just use rally" if your core is under attack you generally don't get to build a command center then call rally and the enemy will probably destroy it and cancel the rally.

**Comment by SheepCommander** [comment]
Actually I suppose maybe you can use logic instead

**Comment by Kyllingene** [comment]
> Why does that happen with the x so much

you realize you can edit your post, right? But anyway, seems fine to me. +1
