### ISSUE TITLE
To get more detailed information from command `ucontrol getBlock`

### ISSUE THREAD

**Issue by FeelUsM** [Anuken/Mindustry-Suggestions#1876]
To get more detailed information from command `ucontrol getBlock`

**Describe what you would like changed, and why.**
I want to write algorithm which will place drills and route conveyors.
For this I need to know configuration of ore and possible places for building.
Now with command `ucontrol getBlock` I can detect type of building and if there is no building I can detect `@air`/`@solid`
But this is not enough to detect can I build there or not because there may be deep-water or space.
Also I want to know is there ore or liquid and which because `ulocate ore` return everytime the same point and this is not enough to choose optimal configuration of drills.

**Describe the changes you want to propose. Include possible alternatives.**
I propose:
1) in command `ucontrol getBlock` rename parameter `building` to `block`
2) add constants `@liquid` (only for deep-water, slag and oil, not for water) and `@space`;
rename constant `@air` to `@floor` (place where I can build (conveyors for example. Pumps I can build in liquid if they border to floor.))
3) that when `type==@floor` `block` reflects the presence and type of ore/`@water`/`@ice`/`@snow`/`@spore-moose`/`@hot-rock`
when `type==@liquid` `block` reflects type of liquid
3+) that I can use command `ulocate ore` to find corresponding "ores"
Also ships to check where they can go will need to check `block==@water` regardless of the `type` (`@floor` or `@liquid`) 
4) that when `type==@floor or @liquid` I can check is the block located near to enemy core in zone where I can't buid - with command `sensor block@team` (like when `type`== some building)
5) align constants and printed (converted to strings) values so that they do not mislead the user

**Comment by joshuaptfan** [comment]
`@solid`, which currently means only stone wall, is functionally identical to space. They are both tiles you can't do anything with, and legged units treat them identically. You may as well make `@solid` refer to space as well.

**Comment by Kyllingene** [comment]
And as for the `@liquid` idea, you might want to change that to `@nobuild` or something like that so that you don't have `@liquid` excluding actual liquid (water).
