### ISSUE TITLE
Make solar panels not being affected by overdrive (and thus buff them)

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1877]
**Describe what you would like changed, and why.**
It doesn't make any sense. How does it even work? ~~angry photons noises~~

**Describe the changes you want to propose. Include possible alternatives.**
Essentially, I want to make solar panels not be affected by overdrive but instead make them cheaper / or increase their power output. Solar power is not really accessible atm. They should be somewhat reasonable to build with a cost of space and not be a waste of silicon.

**Comment by itcannotbe** [comment]
And here's an alternative #179.

**Comment by XEN0PHIL** [comment]
Overdrive increases panel's absorbtion effectiveness, what's the problem with that?
It doesn't have to do anything with photons

**Comment by Slava0135** [comment]
Overdrive projector increases ***speed*** - not the effectiveness

**Comment by joshuaptfan** [comment]
Stop taking all descriptions literally. This is not a realistic game. For gameplay purposes, increasing efficiency = increasing speed.

**Comment by XEN0PHIL** [comment]
> Overdrive projector increases _**speed**_ - not the effectiveness

It speeds up each cell's absorption rate, allowing for more photons to be captured
~~come on let's stop this nonsense~~

**Comment by Slava0135** [comment]
> > Overdrive projector increases _**speed**_ - not the effectiveness
> 
> It speeds up each cell's absorption rate, allowing for more photons to be captured
> ~come on let's stop this nonsense~

ok, somewhat reasonable explanation

**Comment by DeltaNedas** [comment]
since you can see a solar panel, its clearly not 100% efficient

**Comment by RedstonerKBC** [comment]
The real question you should be asking is how an overdrive works. Does it speed up time for buildings? Does it force electricity to travel faster? Do all buildings have microchips that detect overdrives that tell them when to operate faster?

**Comment by SheepCommander** [comment]
Now that sounds like fun theorizing

**Comment by Kyllingene** [comment]
> The real question you should be asking is how an overdrive works. Does it speed up time for buildings? Does it force electricity to travel faster? Do all buildings have microchips that detect overdrives that tell them when to operate faster?

The real question you should be asking is why it took a suggestion (as well as 8 comments) to show that 
`realism != fun`

**Comment by itcannotbe** [comment]
In OP's defence, making something that makes something out of nothing is kinda stupid in the first place, making it produce more out of nothing by applying something makes it more stupid.

**Comment by Kyllingene** [comment]
> In OP's defence, making something that makes something out of nothing is kinda stupid in the first place

Have you ever heard of a "solar panel"? They are this magical technology that makes power from photons. Of course, the in-game block of the same name is just a magical generator.

> making it produce more out of nothing by applying something makes it more stupid.

How about the overdrive is making some sort of magnetic field (or whatever) that increases the efficiency of the "light harvesting"? I mean, they are obviously not perfect, because as DeltaNedas said, they cannot be perfectly efficient if you can see them. I have to assume you are aware of how light works, but these statements make no sense if you do.

**Comment by itcannotbe** [comment]
As someone who said

Realism != Fun

Making something that make something out of nothing js bad for game balance.

**Comment by Kyllingene** [comment]
Ah, you meant for game balance. Pardon my incorrect assumptions. However, I still disagree, as a trifle of power for a fair cost seems fine to me.

**Comment by itcannotbe** [comment]
I concur.

The only thing preventing it being from overpowered is its power output.

**Comment by Kyllingene** [comment]
> The only thing preventing it being from overpowered is its power output or lack there of.

Oh yes, I forgot to mention that I think that solar panels are supposed to be used in more fringe scenarios, and thus should not have much power output. So yes, I agree.

**Comment by itcannotbe** [comment]
> > The only thing preventing it being from overpowered is its power output or lack there of.
> 
> Oh yes, I forgot to mention that I think that solar panels are supposed to be used in more fringe scenarios, and thus should not have much power output. So yes, I agree.

Senarios that necessitate the use of solar panels i.e. (Lack.of fuel sources nearby) is rare that I am questioning their existence already.

It's dirt cheap to just make a map wide power grid anyways.

**Comment by Kyllingene** [comment]
Sometimes, throwing in solar panels instead of having a schematic rely on outside power can be the easiest route, and not an overpowered one. Now, I realize that solar panels being efficient is the only reason power cubes have ever been able to exist in a true form, but I believe that the pros outweigh the cons.

**Comment by itcannotbe** [comment]
Multiplayer be like:

WTF solar panels!
Proceeds to rip them off.
Connects to power grid.

Power grid crashes.
Forgets the point that the thing that is used to be powered by the solar panel is a critical part in the power production chain.
