### ISSUE TITLE
Static conveyor placement option in lieu of dynamic by Shift key during placement.

### ISSUE THREAD

**Issue by ajepalmer** [Anuken/Mindustry-Suggestions#1878]
**Describe what you would like changed, and why.**
The current function of placing a conveyor belt 90 degrees relies on dynamic decisions made by the game. However, when trying to place a 90 degree thorium conveyor next to a drill or some other objects it will not turn 90 degrees and will instead stay vertical. 

**Describe the changes you want to propose. Include possible alternatives.**
I propose that when placing a conveyor you can hold Shift to open a popup menu to pick the conveyor you want to set down manually rather than the dynamic option. Then when done placing hold Shift and deselect the conveyor angle to have it go back to dynamic. This way when the game just refuses to understand what direction you need that thorium conveyor placed to quit grabbing neighboring inputs you can force it.

**Comment by Jammo2000** [comment]
Scroll wheel on desktop, little arrow in the bottom right for mobile.

**Comment by ajepalmer** [comment]
This does not answer the post…. Please re-read my suggestion. This is for placing conveyors at 90 degrees where the game isn’t recognizing it as normally a 90 degree angle. Specifically attempt to set a 90 degree Thorium conveyor up against a pneumatic drill. 90 degree thorium conveyors exist so it shouldn’t matter what I place it against.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Jammo2000** [comment]
So you want to be able to place conveyors against drills without the
drills outputting onto them?

**Comment by ajepalmer** [comment]
I have had instances where I needed a 90 degree bend coming out of a drill but there’s a under/overflow box 1 conveyor space away doing other logistics that I don’t want auto attaching to my conveyor coming out of the drill. But because of lack of space and need the conveyor that’s coming out to be a 90 degree bend. So I need it to 1. Be a 90 degree bend and 2. Not accept input from adjacent conveyors/blocks. Therefore a 90 degree thorium conveyor attached to a drill. I can get it to go 90 degrees if going INTO the drill and I can get it to go 90 degrees with a Titanium conveyor going out of the drill but I cannot get a Thorium conveyor to go 90 degrees output of a drill. However, I run into these nuances all the time where I place a Thorium conveyor that I DO NOT want it to accept input from a neighboring block during a 90 degree turn and it thinks I want it to go directly into the wrong block. Being able to just place the correct angle I want in those instances would solve a ton of my redesigns.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Jammo2000** [comment]
Try using sorters, you can usually make stuff like that work.

**Comment by ajepalmer** [comment]
I’ve been “making it work” since I started playing… however the most useful would be a 90 degree thorium conveyor when I need a 90 degree thorium conveyor lol. Hence the #suggestion. I’m not at a game breaking stoppage by not having it, it’s just silly I can’t place a 90 degree conveyor belt when 90 degree conveyor belts exist simply because of the dynamic logic. IDK if you’re one of the coders or just IT support for tier 1 people that can’t figure out how to launch the game, but I’m not asking for support to play the game, just inputting suggestion for an issue in conveyor placement. As someone that works helpdesk already for IT as far as I’m concerned my issue is resolved and would just like to see this elevated to coders eventually that can see there’s an issue with their dynamic placement when it takes away user control because it assumes they want one thing when they want another.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mnrsU** [comment]
Isn't this technically an additional IO configuration?

**Comment by joshuaptfan** [comment]
Please don't reply using email. The metadata is creating a ton of text pollution.

**Comment by ajepalmer** [comment]
okay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by joshuaptfan** [comment]
You just did it again. Open this page in your browser and see what you have wrought.

**Comment by ajepalmer** [comment]
Ah, I see what you mean. That's amusing it gives you my full title and email address. Rather frustrating for a casual game to give feedback suggestions giving out personal information.

**Comment by ajepalmer** [comment]
Deleted all of my email replies. To answer all the queries above, there's lots of times the dynamic placement of conveyors for Thorium Conveyors will accept inputs from neighboring blocks not intending to which I believe includes bridges and when wanting the conveyor to bend 90 degrees such as when trying to get ore out of a drill. A thorium conveyor can only go straight next to a drill, it cannot go 90 degrees. However there's other instances where it can be bent 90 degrees so its a matter of the dynamic function not realizing my intent. I wish to be able to hold a hotkey such as Shift and pick the type of conveyor I want to place statically, not using the dynamic tool.

**Comment by joshuaptfan** [comment]
Additional UI for such minutiae is far too complicated, and probably out of the question. This suggestion would be best served refocused as "make armored conveyor prioritize input from another armored conveyor from the side", which is more feasible.

**Comment by Jammo2000** [comment]
I think there has been a suggestion about making armored conveyors only being able to take one input.

**Comment by ajepalmer** [comment]
They could just add 90 degree bends to the scroll wheel/^ arrow tool so not just up/right/down/left....

**Comment by joshuaptfan** [comment]
For now, you can use a small section of plastanium conveyor at the bend, as those will ignore all inputs along their route.

![Plastanium bend](https://user-images.githubusercontent.com/15149002/105902905-19790880-5fd4-11eb-98fa-84ce5d4842f2.png)

**Comment by ajepalmer** [comment]
![image](https://user-images.githubusercontent.com/73671627/105903337-5dc0d480-5fe5-11eb-9008-fe9dacd9e291.png)
yes, that works. I don't know why it will not work with thorium but this will work for now. 

Perhaps Shift+Scroll Wheel then to go through all 12 configurations instead of 4, and for the mobile could long press the ^ arrow maybe? I don't play on mobile.

**Comment by ajepalmer** [comment]
![image](https://user-images.githubusercontent.com/73671627/105903885-138c2300-5fe6-11eb-8020-e88caf445a21.png)
Using a filter at least alleviates my pain of placing a bridge next to the conveyor...although I adamently disagree that bridges should connect to Thorium/Plastanium from the side...
