### ISSUE TITLE
Flying suicide unit

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry-Suggestions#1879]
**Describe the content or mechanics you are proposing.**

a unit like the crawler but flying

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

more defense against air attack

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Gives me StarCraft vibes for some reason...

A carrier type unit that created suicide units would be cool.

**Comment by BlueWolf3682** [comment]
![Screenshot_20210118-172222](https://user-images.githubusercontent.com/61173114/105936836-a1313800-6011-11eb-981c-180383f0cd5a.png)

**Comment by Kyllingene** [comment]
What is the above picture? It seems to be a large number of modded air units destroying a base. Are you saying that an air unit that shoots homing missiles (such as the one joshuaptfan suggested) would look like this?

**Comment by joshuaptfan** [comment]
There are a lot of possibilities with ~suicide air units~ homing missiles. But first, the sprite should be much smaller and missile-like.

* Cruise missile silos
* [Missile massacre&trade;](https://tvtropes.org/pmwiki/pmwiki.php/Main/MacrossMissileMassacre) as depicted above
* Tiny slow-moving clouds of homing death, like [grey goo](https://tvtropes.org/pmwiki/pmwiki.php/Main/GreyGoo)

The missiles could be made to prioritize other units, turrets, whatever.

**Comment by antonilol** [comment]
@joshuaptfan nice i also play starcraft
I mean units like the scourge

**Comment by antonilol** [comment]
a suicide air unit that can only damage air units

**Comment by BlueWolf3682** [comment]
> What is the above picture? It seems to be a large number of modded air units destroying a base. Are you saying that an air unit that shoots homing missiles (such as the one joshuaptfan suggested) would look like this?

flying crawlers

**Comment by Kyllingene** [comment]
OOH. I see. I forgot that they have to fall and then explode, so I saw the barrage of bullets and assumed they were simply short-range air units.
