### ISSUE TITLE
overflow gate,router and sorter resource flow rate bug?

### ISSUE THREAD

**Issue by ikmjssc** [Anuken/Mindustry-Suggestions#1881]
![Screenshot_20210127-114303_Mindustry](https://user-images.githubusercontent.com/59211989/105940124-8e604700-6095-11eb-8af4-b04a5ab694d7.png)
![Screenshot_20210127-114252_Mindustry](https://user-images.githubusercontent.com/59211989/105940130-90c2a100-6095-11eb-82f5-62a03954857e.png)
If you connect a router to an overflow gate, the resource flow rate will decrease.
But if you change the order of these blocks, the flow rate doesn't change.
Same thing happened to the sorter.
![Screenshot_20210127-115246_Mindustry](https://user-images.githubusercontent.com/59211989/105940559-91a80280-6096-11eb-843b-b4610cccd8bc.png)

Just let them be the same. I can't understand why they are not.

**Comment by sample-text-here** [comment]
Bug reports go [here](https://github.com/Anuken/Mindustry/issues), though i don't think this is a bug.

**Comment by Kyllingene** [comment]
I think it's because the overflow gate can pass its items back into the router, but not vice-versa.

**Comment by GreyMario** [comment]
Router-flowcontrol is deliberately slowed down by design.

**Comment by itcannotbe** [comment]
This can be solved by putting a check for

If from sorters and flowgates then apply speed limit.

**Comment by ikmjssc** [comment]
> I think it's because the overflow gate can pass its items back into the router, but not vice-versa.



> I think it's because the overflow gate can pass its items back into the router, but not vice-versa.

Well then, probably a feature.

**Comment by ikmjssc** [comment]
> Router-flowcontrol is deliberately slowed down by design.

But sorter-flowcontrol isn't. Make sense to me.

**Comment by DeltaNedas** [comment]
imagine reading the readme that says to not put bug reports here

**Comment by ikmjssc** [comment]
sorry about that, I'm not so sure if this is a bug.
Thank you for your time.

在 2021年1月27日星期三，DeltaNedas <notifications@github.com> 写道：
