### ISSUE TITLE
Logic Editor Changes

### ISSUE THREAD

**Issue by Parkman145** [Anuken/Mindustry-Suggestions#1882]
**Describe the content or mechanics you are proposing.**
These Are several changes that should make editing logic a lot more fluid, organized and intuitive.
_________________________________________________________
1.Context Menu
         When right-click is pressed (or two finger press/very long hold on mobile) in the editor, a context menu with several options will be brought up. Options are shown below.
2. Insert from clipboard
         This will be an option in the context menu. When this option is chosen, code from the clipboard will be inserted below where the cursor was when the context menu was brought up, and the inserted blocks will be automatically selected.
3. Block Selection
         Blocks can be selected by by holding control (long press and hold on mobile) and dragging over blocks. Holding shift and control will allow you to add more blocks to a selection. When blocks are in a selected state, they can all be moved, copied or deleted. Blocks will be slightly darkened and given a slight red tint to show that they are selected. The connections of any jump blocks will also be highlighted in red.
4. Group Block
         The Group block is a block that has no operational function, it is purely visual. The group block is a block that contains or "groups" other blocks and is used to hide/group other blocks to help keep your code organized and clear. The group block can be collapsed to hide any blocks contained within it. You can also give this block a custom name. The group block will be represented in text one of two ways. Either as its own line of code, having two variables; an integer representing the last line of code in the group (either relative or absolute), and a string representing the name of the group; or with a special symbol either at the beginning or end of the starting line and ending line.
5. Shy State (alternative to the group block)
         The shy state is another way of hiding code that you are not currently working on. When a block is in shy mode, it will be collapsed to about the same size as the end block, and will be slightly darkened to help visually differentiate it from non-shy blocks. Shy mode can be toggled by pressing the eye icon next to the copy icon, or via the context menu.
6. Active Block
         When you open the logic editor, the block that is currently being processed will be surrounded by a yellow box.
7. Error Highlighting
         Parameters that have errors will be highlighted in red. Things like invalid data types, undefined variables, invalid attributes or just general syntax errors will be highlighted. 
8. Reset Processor
         The processor can be reset from within the editor (button in the top-right corner), or by clicking the option when the building is selected. Resetting the processor is effectively the same as calling the end function.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Overall, I think all of these changes will drastically help improve the logic editing experience, making it faster to make changes, as well as making it easier to solve problems. 
More Detail:
1. Context Menu
         The context menu would be a very important feature if some/all of the other features are implemented, because it would help keep the UI clean and clear, while still providing all of the necessary functions.
2. Insert from clipboard
        This feature would help make it easier to mix scripts or parts of scripts together, without having to worry about fixing jumps. It should also make it easier to quickly insert an updated part of a script from one processor to a different processor, without having to worry about changing any variables that could be different.
3. Block Selection
         Being able to select blocks could help speed up the workflow. For example if you want to move several blocks to a different part, you can do it all at once, and you won't have to worry about putting blocks in the wrong place. 
4. Group Block
         The group block should drastically improve visual clarity. The group block should make it far easier to find a certain part of your code, and not have to spend a bunch of time scrolling through it. If custom names for groups is also implemented, it should also help you to be able to better understand your code.
5. Shy State
         The shy state will also improve visual clarity, like the group block, but comes at the cost of not visually separating different parts of your code. 
6. Active Block
         Being able to see exactly what step your code is on should help you quickly determine if your code is constantly looping. This would be far better than using a message and *@counter* both because being able to instantly see it is far better than having to set up a message block, as well as the necessary logic for it; and because if your code is in a loop, it probably won't update the message anyway.
7. Error Highlighting
         Error highlighting would make it far easier to find simple mistakes in your code, like a misspelling, and should not be hard to implement, as you could just make any variables or other input values that output as *null* highlighted.
8. Reset Processor
         Being able to quickly reset the processor would make it easier to run your code from the top, so that each line of code  that is needed is called.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SheepCommander** [comment]
I think I generally agree with this but it's a lot and I haven't read all of it lol

**Comment by DeltaNedas** [comment]
> Resetting the processor is effectively the same as calling the end function.

only setting @counter to 0 doesn't sound like resetting
