### ISSUE TITLE
Sensors Code Guides Bulit-in

### ISSUE THREAD

**Issue by Armata14** [Anuken/Mindustry-Suggestions#1883]
An List for all the Code and What it does and Example
By Clicking the Pencil And If a New Tab "GUIDE"
by clicking this Shows an Spreadsheet of the Type of codes
to Use in The sensor

**Comment by sample-text-here** [comment]
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/logic/LAccess.java

**Comment by RedstonerKBC** [comment]
I suggested this months ago when logic first came out. I was told to rtfm aka mods, refered the above github link, refered to another github link to the game's source code and told me to figure it out myself like everybody else, told to quit programming since I have questions, told to ask people in the discord, and to read the online wiki which at the time wasn't properly updated with logic.

**Comment by joshuaptfan** [comment]
I plan to update the official wiki's logic guide to be thorough and beginner-friendly. Since a link to the wiki is in the game, IMO that's where the bulk of documentation efforts should go.

**Comment by sample-text-here** [comment]
I feel like a lot of the code in the link describes what it would sense <details><summary>screenshot - code</summary><img src="https://user-images.githubusercontent.com/56274831/106178694-f32ba800-614e-11eb-84f2-3d257f015b2a.png"></details>you can "link" buildings by clicking the processor, then clicking any other building within its range. `result` is a variable that will be set to the result of the sensor reading.
<details><summary>screenshot - logic</summary>
<img src="https://user-images.githubusercontent.com/56274831/106180219-ddb77d80-6150-11eb-9bd7-7c192bf78433.png">
</details><details><summary>screenshot - setup</summary>
<img src="https://user-images.githubusercontent.com/56274831/106180298-f9bb1f00-6150-11eb-9baf-8430edf461d7.png">
</details>

`result` would be set to the amount of copper in the linked container
