### ISSUE TITLE
new World In Game

### ISSUE THREAD

**Issue by Armata14** [Anuken/Mindustry-Suggestions#1884]
New Type of Worlds / planets
Each has unique Enemy's and Base
1st is Bio Planet instead of you Spawn in a Robot planet
you Spawn in the Bio Planet of unknown Life
They have Limbs and Some cant Fly 
2nd is Volcanics Planet full of Energy and Inferno Creatures
3rd Another Type of Bio Planet but this has in a Modernize era
They have Weapons Quite Weak but No really
Like the IRL Unit jets Helicopters Ship boats Tanks Soldiers and Nuclear Weapons
4th is the Robotic Planet the Hardest One As you Accidentally Entered an Enemy Planet of your Home world You Fight for Survival To Leave this Planet

**Comment by Cherriodude** [comment]
Mods

**Comment by Kyllingene** [comment]
Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will automatically filter it out to save him time.

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```
