### ISSUE TITLE
Redundant power beams connecting thing touching other nodes

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry-Suggestions#1886]
**Describe what you would like changed, and why.**
It's annoying to watch game making redundant power links, where you create for example- repair point touching the node.
That's how it looks:

https://user-images.githubusercontent.com/33349024/106029934-eadf5880-60cd-11eb-825c-901ee7866fa0.mp4

**Describe the changes you want to propose. Include possible alternatives.**
Before connecting, mindustry should search, if the structure is already touching other node.

**Comment by itcannotbe** [comment]
More like should check if the building is already part of the powergraph network before trying to connect an in range power node to it.

**Comment by Kubek0212** [comment]
> More like should check if the building is already part of the powergraph network before trying to connect an in range power node to it.

yes, that makes more sense

**Comment by Kubek0212** [comment]
I see it was parched in recent (136) version. Closing
