### ISSUE TITLE
Allow us to change “hold to build” time on mobile.

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry-Suggestions#1887]
**Describe the content or mechanics you are proposing.**
It’s very annoying that you have to hold for a second to build a conveyor on mobile, and you can’t change it. So I suggest an option to change hold to build time.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
QOL, it will help mobile players on pvp servers, campaign.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
Then how will the game know if you want to move or build a line?
