### ISSUE TITLE
player camera

### ISSUE THREAD

**Issue by USMP-lancer** [Anuken/Mindustry-Suggestions#1888]
adds a simple multiplayer feature that allows you to make your camera follow a player

this will allow players to confirm potential griefers in multiplayer, allowing you to see what a player is doing in general
maybe even allow it to follow units for logic debugging.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by bvcbvc** [comment]
by the way, if you read this, good job on the game, good luck anton.

**Comment by userlol2** [comment]
So its something like spector mode

**Comment by bvcbvc** [comment]
yea pretty much
