### ISSUE TITLE
Logic Lists

### ISSUE THREAD

**Issue by Parkman145** [Anuken/Mindustry-Suggestions#1889]
**Describe the content or mechanics you are proposing.**
Logic lists would be a new data type that is able to store several values at once, and you would be able to access each value using its index or id. For example, you could have a list variable called playerCorrdinates, that would contain two values, that would contain two values, the players x position, and the players y position. I have come up with two different ways what lists could be implemented, one simple that should be easier to add, and one that is more complex, but has more features.
Simple Implementation
____________________________________
With the simple implementation, lists would be used nearly identically to variables, the only difference is that the list would have a number defining what stored value to use. lists would be audited using any variable-defining function, like "set" or "operation". For example:

**set myList[1] 2
set myList[2] 5
op add result myList[1] myList[2]
print result
printFlush message1**

Output:
**message1: 7**

The main feature of lists would be that another variable could be used to define the target value. For for example:
(continuing from last example)
**set i 1
print myList[i]
printFlush message2**

Output:
**message2: 2**

Advanced Implementation
____________________________________
In the advanced implementation, lists would be made/edited using the *list* block. The list block will have __ main functions.
*List Create/Edit*
List create/edit will do exactly what it sounds like; create and edit lists. It will have 3 parameters. The list name, the value index, and of course, the value.
*List Insert*
List Insert will be identical to list create/edit, but instead of overwriting the specified index, it will be inserted before it, and any proceeding values will be moved accordingly.
*List Properties*
List Properties will be used to get information about a list. It will also have 3 parameters. Once again the list name, the list property, and the target output variable. Properties that can be accessed are the list length, first empty index (index with a value of **null** and last filled index.
*List Audit*
List audit will contain a couple functions to modify lists. List audit will have 3* parameters, the target list, the audit function, and any possible other values for that function. There will be __ audit functions. "Purge", which will remove any unfilled indexes; Remove Index, which will remove an index, and any following indexes will be moved accordingly; Index Move, which will move a targeted index value and inserted into another index. If there is already a value in the specified index, said value will be moved to the next index, as well as any proceeding values until an empty index is reached. (This one may be hard to implement, so you might want to change the specifics of how this one works); and List search. List search will search for a specified value in all indexes. If it is found in an index the result will be the index number. If multiple are found, it will be a list of all indexes with the value, and if none are found the output will be null. This function will also contain an additional parameter, being the value to search for.
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I feel list will make a great addition to Mindustry's logic system. List will make it far easier to to store values like required materials for something without having 40+ lines of code just for that. A possible concern is that it may be too overpowered, but I feel that sense Mindustry's logic system is fairly limited, opening the door to plenty of possibilities. Another possible concern is that lists may defeat the purpose of memory buildings, but I feel memory buildings are still necessary for communication between processors, and memory buildings can be changed to make them more of a long term/bulk storage solution, like a hard drive compared to ram and provide more of a need for bulk storage (for example storing several enemy positions). This can be done by allowing strings and many lists to be stored in them, or making them necessary to use lists (perhaps each memory modules could be changed so that each one is a list?)
Overall, I believe that lists are a necessary addition to Mindustry's logic system that would help improve it overall.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
first program already works, using variables requires array types or reflection (see anuke-logic)

anuke will not add more types to logic

**Comment by joshuaptfan** [comment]
You're simply asking for too much. I think a more feasible suggestion is to allow memory cells to store data types other than numbers (strings, references).

**Comment by bvcbvc** [comment]
my man, just use memory blocks

**Comment by Parkman145** [comment]
> You're simply asking for too much. I think a more feasible suggestion is to allow memory cells to store data types other than numbers (strings, references) which would allow them to be on par with logic variables.

> my man, just use memory blocks

Look at the second to last line:
"(perhaps each memory modules could be changed so that each one is a list?)"
