### ISSUE TITLE
Match Making feature for Steam Version of Mindustry

### ISSUE THREAD

**Issue by rowennjohn** [Anuken/Mindustry-Suggestions#189]
(Some of details has further been explained in some comments, to correct and try to fill the gaps I didn't realized during the time I was writing the idea. )

The game has a great potential to be a huge e-sports game title. IMO. It has still balancing issues and stuff, but it has the potential to be a niche RTS game.

One of the best feature of the game is Multiplayer, It'll be nice if a matchmaking feature will be added to play with other random players without asking in the discord servers. I know this has a lot to do with networking, server hosting and stuff, I am not professional programmer, but I believe this feature can help the game grow. 

I am aware, that yes this would require funding for server hosting etc. If you would like add additional fees it is okay. For old player who already bought the game I think it is fine if you ask players to buy it as a DLC, 

This will also encourage players to get the Steam Version and will financially help you even further.

I am aware that this feature will require a lot of work, like A LOT, before it will be added, but I would like to know what are the specific resources and efforts are needed for this to happen so we'll be aware and will try to help to make it happen.  

That's all, hope you see this. 
Thank you for the time reading.
Wishing you the best.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
did you know that you can actually host a server, super easy, on mindustry? All you have to do is go into a game (custom or campaign), go to the exit menu, and click host multiplayer server (or some button labelled similarly).

**Comment by rowennjohn** [comment]
Read it multiple times.

Hosting a multiplayer server and match making is different bruh.

Let's say like a CS:GO Match or a TF2 Match. You will be connected with random players other than your friends or connections, and you will finish a match. Let's say a 4v4 match PVP or a "win 100 waves as fast as you can". Match making is different from Hosting a local server and a server.

**Comment by potatoisagender** [comment]
So. You want something like a pvp server yeah? That's called hex, or ECAN PVP, or IO PVP.
If you want it private, I guess you could hop onto a discord and ask for people to join a hosted game.

**Comment by rowennjohn** [comment]
I AM AWARE OF THOSE. I edited some on my previous comment, re-read.

Are you getting it? What I am saying is getting rid of asking or looking for discord servers or asking people. You just queue yourself and wait for a match for your current stats.

What I am saying is a DOTA2, competitive TF2 or Company of Heroes 2 like kind of match making, players can vote for next map official or community made maps.

Do you get the difference?

**Comment by potatoisagender** [comment]
yeah, but then that totally changes the gameplay format. DOTA2 and the other games you listed are primarily for the matches. Mindustry is a little different, in that the multiplayer is more geared toward coop tower defense, not getting in a group and attacking each other. What you need to understand is that the kind of game format you are suggesting will basically require rewriting a whole fuck ton of code, because Mindustry is centered around base building. You are going to change the genre, and the gameplay.

**Comment by rowennjohn** [comment]
Like what you said "Mindustry is centered around base building", basically Factorio + Starcraft 2. It is an RTS game. The emphasis I want to point here is to LIFT IT HIGHER, the PVP part.

**Comment by potatoisagender** [comment]
alright. Let's let anuke decide whether this should go forward or not.

**Comment by rowennjohn** [comment]
It's a very niche game, a very different RTS game, it has an e-sports potential, the PvP element of this game is Starcraft 2 on Steroids, Starcraft 2 is already a mind fuck game in e-sports industry, 

Now  improved Mindustry PvP and add Fog of War, boom you have made probably the next big e-sports game.

There's no need to rewrite a whole fuck ton of code. You just need to improve and add couple of codes in the Multiplayer Feature by adding a Matchmaking feature.

All the Coop & PvP elements of Mindustry doesn't need to be change. The only thing will be changed is how connecting with other players, it will be more convenient and better, because there is no need to look for people to ask to participate in your custom hosted matches. 

For PvP Matches - It will go like this, instead playing PvP in the same kind of map the PvP community servers hosted, players will be given a chance to select a map or map size,  choose a core type, set a starting resource and organize their team before starting the game. Nothing will change in the PvP elements, just how matches will be setup.

For Coop Matches - It will go Like this, same as mentioned in PVP Matches that players will be given a chance to select a map or map size,  choose a core type, set a starting resource and organize their team before starting the game. But Wave Sizes and Enemy difficulty are need to be setup, let's say 100 waves. Nothing will change in the Coop elements as well, it is still the same mindustry tower defense you play, it is just more convenient to start. 

I also like to point out the issue in survival community servers, sometimes it is not anymore fun to join because the whole map were already teraformed and then you are just there  just maintaining turrets and shields and walls. 

I personally like if everytime I play Mindustry and join a match, I start out in a fresh start, ready to show off some skills and then finish only a finite amount of waves and start a new one again on a different map.

I am basically asking Anuken to level up the Multiplayer aspect of the game, by introducing "In-Game Automatic Matchmaking.

**Comment by LeoSko** [comment]
Just found that and want to say that I'm hosting exactly this type of PvP server - with matchmaking. https://ranked.ddns.net
