### ISSUE TITLE
Crawler manual control concerns

### ISSUE THREAD

**Issue by GreyMario** [Anuken/Mindustry-Suggestions#1890]
**Describe what you would like changed, and why.**

Crawlers can be a bit annoying to control manually due to inconsistencies in detonation. Suicide-type units need a handling improvement for quality-of-life.

**Describe the changes you want to propose. Include possible alternatives.**

Crawlers should detonate simultaneously in formation, but they should not detonate immediately upon gaining control if the firing trigger (mouse button, whatever) happens to be held down when control is passed to a new crawler.

**Comment by RedstonerKBC** [comment]
They should detonate on a mouse click rather than a mouse hold. That way you don't accidentally blow through your entire stock of crawlers when you only meant to blow up the ones at the enemy base. I agree.

**Comment by notMEEPoffaith** [comment]
yes.
