### ISSUE TITLE
Desktop: Zoom should be able to at least allow players see the foreshadow

### ISSUE THREAD

**Issue by mayli** [Anuken/Mindustry-Suggestions#1892]
**Describe what you would like changed, and why.**

On desktop, players could get killed without having a direct view of the foreshadow, and even with max zoom, there is no way to see it with default settings. Some phone users were able to see foreshadow due to aspect ratio and that gives extra advantages to them.

**Describe the changes you want to propose. Include possible alternatives.**

Compute the zoom clamp based on the minimal of width/height of display to allow visibility of foreshadow in 100% UI scaling mode.

![java_d40sbjfH4q](https://user-images.githubusercontent.com/822628/106225748-a1a90a80-619a-11eb-9f9c-5de0656eddaa.png)

Alternative:
  - allowing set the UI scale at step of 5, 25% is kind of a big stepping in scaling.

**Comment by notrealn** [comment]
ok but what if you used the pan view button

**Comment by mayli** [comment]
> ok but what if you used the pan view button

is there pan view button for desktop?

**Comment by GreyMario** [comment]
There is for desktop, but _not_ for mobile. You need to take control of something immobile to do it in mobile; on desktop, the default key is Mouse 4.

**Comment by mayli** [comment]
> There is for desktop, but _not_ for mobile. You need to take control of something immobile to do it in mobile; on desktop, the default key is Mouse 4.

![image](https://user-images.githubusercontent.com/822628/106226537-4aa43500-619c-11eb-8f76-69b9897b944f.png)


Ok, I guess my mouse doesn't have mouse 4. Time for shopping, but still it's kind of annoying that the default zoom level doesn't cover the range of foreshadow.

**Comment by mayli** [comment]
btw, feel free to close it if it's not really annoying you.

**Comment by blool22** [comment]
if you dont have mouse 4 you can just set it to another button

**Comment by Kyllingene** [comment]
> btw, feel free to close it if it's not really annoying you.

Only you and Anuken can close the issue; nobody else.

**Comment by catatagun** [comment]
Give mobile the same thing
