### ISSUE TITLE
Have schematics be unlocked upon completing the campaign 

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1893]
**Describe what you would like changed, and why.**
Currently, schematics are very op, and from my personal experience **can** ruin your experience (the first time atleast) so I suggest having the usage of schematics in campaign mode be unlocked when you capture the final story sector.

This would force players to learn how the game works and have a genuinely better time than just copy pasting brain-dead schematics all over and winning.

Idk where the boxes went but here are some xs

**x**
***X***
# X

**Comment by sample-text-here** [comment]
probably not after completing the entire campaign, but maybe make it a researchable thing. after researching silicon smelters, maybe, where schematics can start to become very useful.

**Comment by catatagun** [comment]
Core schematic is murder

**Comment by Legomonster33** [comment]
> probably not after completing the entire campaign, but maybe make it a researchable thing. after researching silicon smelters, maybe, where schematics can start to become very useful.

Scematics are very useful all the time but they take away a large part of the fun and gameplay
Having them be something you unlock by research would also be good, preferably costing like 1k of each resource

**Comment by GreyMario** [comment]
what

okay so you want to take away the copy-paste function and schematics for everyone who plays campaign

just to compensate for... what, exactly?

balancing around dumbasses in multiplayer is not our problem and should never affect campaign

**Comment by sample-text-here** [comment]
also separating core schematics into a different research category would be nice; launching with a pre-built quasar factory isn't as fun as trying to survive.

**Comment by Legomonster33** [comment]
> what
> 
> okay so you want to take away the copy-paste function and schematics for everyone who plays campaign
> 
> just to compensate for... what, exactly?
> 
> balancing around dumbasses in multiplayer is not our problem and should never affect campaign

I only want to limit schematic usage **in campaign**
Balancing for the fact that schematics take away a large amount of the fun you get your first few playthroughs

**Comment by Legomonster33** [comment]
All modes outside of campaign would have free use of schematics

**Comment by GreyMario** [comment]
ok so let me get this straight then

because YOU didn't want to take the time to ask questions or investigate for youself,

YOU downloaded a bunch of schematics

and decided that it ruined YOUR experience


so you want to take that away from everyone else.

**yeah uh.** that's not how this works, that's not how any of this works.

**Comment by Legomonster33** [comment]
> ok so let me get this straight then
> 
> because YOU didn't want to take the time to ask questions or investigate for youself,
> 
> YOU downloaded a bunch of schematics
> 
> and decided that it ruined YOUR experience
> 
> so you want to take that away from everyone else.
> 
> **yeah uh.** that's not how this works, that's not how any of this works.

No actually I didn't download any schematics,
It doesn't matter how you get the schematics 
They didn't ruin my personal experience but they **can** and **have** ruined other peoples experiences
I'm not taking it away from anyone I'm just making it so you have to earn the use of arguably the most op feature in the game
I know how things work and that's why I make these suggestions so if anything **you** don't know how any of this works

**Comment by XyLoRage** [comment]
boi if you remove schematics early game that would make the game more frustrating and repetitive for the sake of efficiency

**Comment by Legomonster33** [comment]
> boi if you remove schematics early game that would make the game more frustrating and repetitive for the sake of efficiency

That is why it would be a 1 time unlock
You beat the campaign without schematics and then you can use them **in campaign** forever
They are arguably one of the most op features in the game and i feel as though they **can** hurt the experience

**Comment by itcannotbe** [comment]
Insert tons of "CaNs Me HaS kIMaNaTeK oOf StAsKrRrRt SiLiCoNe ImPlAnTs and MetaGles FuCkToRy?"

**Comment by TheMrAlbert** [comment]
Not necessary suggestion to me. We have #schematics in Discord.

**Comment by Legomonster33** [comment]
> Not necessary suggestion to me. We have #schematics in Discord.

You seem to have completely missed the point of my suggestion

**Comment by TheMrAlbert** [comment]
> > Not necessary suggestion to me. We have #schematics in Discord.
> 
> You seem to have completely missed the point of my suggestion

My bad. I am sorry that I completely miss the point. I mean my idea is that you can still save-only schematics and copy paste structures but without opening schematics to use it instead.

**Comment by Legomonster33** [comment]
Thats actually a good idea, still allow use of schematics just gate the menu

**Comment by sample-text-here** [comment]
>  just gate the menu

oh, i thought that's what this suggested

**Comment by bendnuts** [comment]
cough. so you said, i dont like schematics in campaign because in campaign schematics are bad. yes? well the thing is, how do you get your schematics if you dont go over to multiplayer and press f a shitton of times, you **design** them. so if people simply dont play multiplayer its the same exact experience. and if they find that tehy can do something in multiplayer but *not* in campaign, i bet people will be rather mad, and there will be a whole ton of mods that allow use of schemati in campaign. the point is; :bonk:

**Comment by itcannotbe** [comment]
> cough. so you said, i dont like schematics in campaign because in campaign schematics are bad. yes? well the thing is, how do you get your schematics if you dont go over to multiplayer and press f a shitton of times, you **design** them. so if people simply dont play multiplayer its the same exact experience. and if they find that tehy can do something in multiplayer but _not_ in campaign, i bet people will be rather mad, and there will be a whole ton of mods that allow use of schemati in campaign. the point is; :bonk:

Now where is that water extractor and steam generator that is not unlocked at the start of campaign?

**Comment by Slava0135** [comment]
> > boi if you remove schematics early game that would make the game more frustrating and repetitive for the sake of efficiency
> 
> That is why it would be a 1 time unlock
> You beat the campaign without schematics and then you can use them **in campaign** forever
> They are arguably one of the most op features in the game and i feel as though they **can** hurt the experience

*Gold old times before schematics were added...*

**Comment by the-red-soul** [comment]
Schematics should be an unlock in this game tbh. Maybe not the end of the campaign but somewhere earlier on to the middle of the tech tree. There are far too many people who play this game and just copy/paste schematics without learning how they work. They have no gamesense with what works where or ratios. They just see something that is "good" and use it. They do not learn any mechanics that this game has to offer. 

Having schematics should just be a convenience and not the sole way you actually ever play the game. If people used schematics less then they would easily realize that there is more than one way to do everything and sometimes based on the situation its actually less efficient to plop that invection sand silicon per say.

**Comment by Avinash12429** [comment]
No one experience is not gone ruin if this suggestion will come try then most of people just not look into this game.And if you thinking about others experience  ruined it is actually wrong the game dont force you to make schematics.it.I liked this game of this fast and perfect option schematics

**Comment by Kyllingene** [comment]
If someone wants to use *premade* schematics, let them. They are only ruining the game for themselves. But I think ruining the fast game for tons of players just so those people don't get to play the game how they see fit is a little ridiculous.

**Comment by Slava0135** [comment]
> Have schematics be unlocked upon completing the campaign
> Have mods be unlocked upon completing the campaign
> Have multiplayer be unlocked upon completing the campaign
*yes*

**Comment by Legomonster33** [comment]
> If someone wants to use _premade_ schematics, let them. They are only ruining the game for themselves. But I think ruining the game for tons of players just so those people don't get to play the game how they see fit is a little ridiculous.

One of the most important things a developer needs to do is protect the player from themselves, it should not be upto the player whether or not they want to (unknowingly) ruin the game for themselves

**Comment by Kyllingene** [comment]
"unknowingly". That is the key word. If you copy/paste a report for school, you *know* you are ruining it for you (getting in trouble, most likely, guilt feels definitely). Likewise, if you copy/paste your game, you will know its worse for you. The only people who won't feel that guilt and stop are those who would like the game better that way, and in that case, let them play it that way. And you keep forgetting: ***normal people use schematics they make***.

One thing I would like to see is an "Allow Schematics" option for custom games. That way, you can play with people that you know download schems without being at an objective disadvantage. As a side bonus, it could help a little with those griefers with the big resource-wasting schems.

**Comment by Legomonster33** [comment]
> "unknowingly". That is the key word. If you copy/paste a report for school, you _know_ you are ruining it for you (getting in trouble, most likely, guilt feels definitely). Likewise, if you copy/paste your game, you will know its worse for you. The only people who won't feel that guilt and stop are those who would like the game better that way, and in that case, let them play it that way. And you keep forgetting: _**normal people use schematics they make**_.
> 
> One thing I would like to see is an "Allow Schematics" option for custom games. That way, you can play with people that you know download schems without being at an objective disadvantage. As a side bonus, it could help a little with those griefers with the big resource-wasting schems.

People use schematics because they are part of the game, and they don't feel guilty about using the for the same reason, they don't know they are ruining the game for themselves, they just know they rae using one of the many features

**Comment by Kyllingene** [comment]
Ever played Mario Kart? Well (at least in the new one), there is an assist mode than keep you from going off the track. Obviously, it's a part of the game, but would it make sense to remove it? No, not at all! It helps people who would otherwise not play. Same with schematics, although slightly different.

**Comment by Legomonster33** [comment]
> Ever played Mario Kart? Well (at least in the new one), there is an assist mode than keep you from going off the track. Obviously, it's a part of the game, but would it make sense to remove it, just so that people don't get it easy? No, not at all! It helps people who would otherwise not play. Same with schematics, although slightly different.

That is a very bad analogy ngl

**Comment by Kyllingene** [comment]
> That is a very bad analogy ngl

If you would show me how, I would gladly agree.

**Comment by Legomonster33** [comment]
> > That is a very bad analogy ngl
> 
> If you would show me how, I would gladly agree.

Assist mode is framed in such a way that it makes it clear its not how the game is supposed to be played

**Comment by Kyllingene** [comment]
Really? It's in the same category as the minimap and the motion control settings, and sometimes it even gets enabled by default for me.
