### ISSUE TITLE
Ad for mobile mindustry

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1894]
**Describe the content or mechanics you are proposing.**get a 1 in 300 chance to get a ad if you press something on the title screen

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**this will get you more money and not be annoying because of how uncommon it is

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [c] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by catatagun** [comment]
99999999 out if 10 idea

**Comment by GreyMario** [comment]
I'm sorry, if I roll a 1 in 300 chance to get an advertisement on the title screen, I'm going to be pissed because I'm not expecting it.

**Comment by BlueWolf3682** [comment]
No.

**Comment by NajimiOsana** [comment]
This would work if it wasn't one of those annoying Block-Your-Entire-Screen-Unless-You're-A-Sniper-That-Can-Click-On-The-X type of Advertisement

**Comment by catatagun** [comment]
> This would work if it wasn't one of those annoying Block-Your-Entire-Screen-Unless-You're-A-Sniper-That-Can-Click-On-The-X type of Advertisement

Anuke buys an add and puts it on mindustry and the add is for mindustry simple

**Comment by Cherriodude** [comment]
thank you

**Comment by ScepterReignPlayz** [comment]
One word...

No

**Comment by catatagun** [comment]
> One word...
> 
> No

ANUKE LIVES IN A GARBAGE BAG SO WATCH THE ADS SO ANUKE GETS THE MONYS

**Comment by itcannotbe** [comment]
It's not even a lot of money to be earned that way, why even bother.

**Comment by catatagun** [comment]
> It's not even a lot of money to be earned that way, why even bother.

Cuz anuke needs money and it basicly does nothing to the game so its fine

**Comment by Legomonster33** [comment]
> > It's not even a lot of money to be earned that way, why even bother.
> 
> Cuz anuke needs money and it basicly does nothing to the game so its fine

Ankeny gets most of his money from steam and itch sales (he might have an actual job too idk)
Mobile ads don't help unless you have a massive f2p playerbase

**Comment by TheMrAlbert** [comment]
This isn't helpful. iOS shouldn't have ads due to paid game. Adding ads will complicate things such as free version of itch.io. I afraid it will become adware. If you meant to be Android only, it's simple but it will mess GitHub contributions which then ruins the other platforms.

**Comment by SheepCommander** [comment]
Although it would be nice if Anuke was able to get some amount more support, this is **not** the way to go about it.

A out of the way "watch an ad to support Anuke" (I don't think there's really any reasonable reward you can give for it) sure, but not this BS

**Comment by Legomonster33** [comment]
wAtCH aN Ad tO lAUncH tO tHe nExt seCToR

**Comment by TheCorruptedKing** [comment]
This is a horrible Idea, for Android and IOS devices. The algorithm is too screwed up to even think twice for game developers in general.
Google's algorithm: $0.02-$0.16 (what the app developer gets) | $2.50 (What Google gets)
Apple's algorithm: unidentified, all I know is that they take about 70% of what you make.

The situation with Apple's algorithm is that besides the 70% that they take, you have to pay them 1,000$ to publish your app:
800$ for their application creator portal (a macbook pro)
and 200$ for a publishing license (allows it to be put onto the app store)

I could seriously go on with saying how bad of an idea this is but i'll let the pros handle this.

**Comment by catatagun** [comment]
> This isn't helpful. iOS shouldn't have ads due to paid game. Adding ads will complicate things such as free version of itch.io. I afraid it will become adware. If you meant to be Android only, it's simple but it will mess GitHub contributions which then ruins the other platforms.

Im talking about playstore

**Comment by catatagun** [comment]
> wAtCH aN Ad tO lAUncH tO tHe nExt seCToR

Im talking about the title screen did you just see the title and did this

**Comment by DeltaNedas** [comment]
@catatagun anuke confirmed that he is a millionaire and probably does not live in a bag (there is proof that he did at one point)
 mindustry should not need 50 spyware sdks to compile for android google play edition

**Comment by Humanoid-X** [comment]
No hes a cat and cant be a millionaire he must live in a garbage can...
Lol don't be offended Anuke, only joking.

**Comment by TheCorruptedKing** [comment]
> > This isn't helpful. iOS shouldn't have ads due to paid game. Adding ads will complicate things such as free version of itch.io. I afraid it will become adware. If you meant to be Android only, it's simple but it will mess GitHub contributions which then ruins the other platforms.
> 
> Im talking about playstore

I was talking about both Android and IOS.

**Comment by Kyllingene** [comment]
> No hes a cat and cant be a millionaire he must live in a garbage can...

***You have offended the Anuken and shall be hung as a heretic and blaspemer.***

Otherwise though, I agree with itcannotbe and LegoMonster; it's not enough money to be worth annoying the playerbase for.

**Comment by WinterCrystal** [comment]
While I do think this might potentially be good way to gain more players into the game, I have to say no, the thing is, the mobile market has a history of terrible ads especially the videogame ones, and I don't want Mindustry to be a part of them, besides, I think Anuke is fine financially well off.

**Comment by Kyllingene** [comment]
> While I do think this might potentially be good way to gain more players into the game,

Actually, the idea is not ads *for* mobile mindustry, but ads *in* mobile mindustry. See the below line from the suggestion.

> get a 1 in 300 chance to get a ad if you press something on the title screen

**Comment by sk7725** [comment]
You know, if this gets added, the first thing I'm gonna make is an ad blocker mod.

~~If this doesn't get added, I'm gonna make an ad mod.~~

**Comment by stuffyAI** [comment]
The title actually suggests that there will be an ad for mindustry, but the content suggests that there will be ads in mindustry.

Not to even judge the value of this suggestion, please change the misleading title.
