### ISSUE TITLE
Ядро "Камешек"

### ISSUE THREAD

**Issue by DrPeeper228** [Anuken/Mindustry-Suggestions#1895]
Это ядро слабее "осколка", размер 1 на 1, персонаж ядра: тонкая палка с двигателем, не может стрелять; ядро вмещает по 500 предметов, делается из 50 меди, его можно сделать из меди в инвентаре персонажа, можно переделать в "осколок", подойдёт для hex pvp (Можно востановится после поражения), уничтожается с нескольких выстрелов, доступно только при галочке в правилах редактора карт, и рецепт "осколка" 500 меди, 500 свинца и 100 графита.

1. - [√] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [√] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [√] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [√] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
Mods.

**Comment by catatagun** [comment]
X

**Comment by itcannotbe** [comment]
> This core is weaker than the "shard", size 1 by 1, core character: thin stick with a motor, cannot shoot;  the core holds 500 items, is made of 50 copper, it can be made of copper in the character's inventory, can be converted into a "shard", suitable for hex pvp (Can be restored after defeat), destroyed with several shots, and the recipe for a "shard" of 500 copper  , 500 lead and 100 graphite.

No. Placable core are OP. End of story.
