### ISSUE TITLE
Space stuff, like space stations and dyson spheres (maybe)

### ISSUE THREAD

**Issue by LFTY-LILFOXTVYT** [Anuken/Mindustry-Suggestions#1896]
**Describe the content or mechanics you are proposing.**
In V7 there might be multiple planets, so there might be an abillity to make space stations. Its like a sector, very small one, but launchable via a structure of some kind. New rocket engines, controllers for space stations, space energy sources, like space sails harvesting energy from vacuum, 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You could send materials there to make a storage, of make an space gun, that will slowly, but strongly will shoot in the enemies in the nearest sector. Dyson spheres will be very late game enrgy source. You send lots of mirror panels to the star in the solar system that will reflect light in collecting stations, giving energy to the player. The more mirrors launched - the more power prodused. In the space stations you can add rocket enqines, that will allow to move the station above a certain sector. There may be space guns/turrets, that will try ti shoot down the station above them. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by notMEEPoffaith** [comment]
pog

**Comment by ScepterReignPlayz** [comment]
this is a really good request no joke

**Comment by itcannotbe** [comment]
I don't know how would this fit mindustry game wise and balance wise.

**Comment by LFTY-LILFOXTVYT** [comment]
> I don't know how would this fit mindustry game wise and balance wise.

Lots of resources, like to make a full dyson sphere you need more than a BILLION mirrors and at least Million solar collectors, so you literally need th mine a planet for this

**Comment by Kyllingene** [comment]
A good idea in general, but idk if it fits the feel of the game, like itcannotbe said.

**Comment by WithersChat** [comment]
Have you played dyson sphere program recently?
joke aside seems cool.

**Comment by firstcreator48** [comment]
cant cant afford computer

**Comment by firstcreator48** [comment]
uwwu

**Comment by numer99** [comment]
YES. we need.

**Comment by firstcreator48** [comment]
hmmmm... okay

**Comment by firstcreator48** [comment]
> cant cant afford computer

not really xd
