### ISSUE TITLE
Purple Air Units

### ISSUE THREAD

**Issue by notMEEPoffaith** [Anuken/Mindustry-Suggestions#1897]
**Describe the content or mechanics you are proposing.**
These would be the Purple variant to air units, like how land has all 3 variants, air should also have all 3. You can feel free to choose what they look like, are called, and how they would act.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think it would make sense to have all 3 colors of units for all types eventually, as i think it's kind of unfair how only Ground gets all 3 types.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Here before the guys who always says "mods" shows up

**Comment by notMEEPoffaith** [comment]
i just think this would be a good idea in vinalla

**Comment by joshuaptfan** [comment]
This suggestion is incredibly vague and not useful. Color is not a compelling reason to create a new line of units.

**Comment by Kyllingene** [comment]
But... the entire point of the purple class is the *legs*... how do you make *legs* on an *air* unit?!?

**Comment by Yell245** [comment]
> But... the entire point of the purple class is the _legs_... how do you make _legs_ on an _air_ unit?!?

No it isn't. They're specialists in chaos. Legs only are instruments in making chaos

**Comment by TheRealIvyX** [comment]
> But... the entire point of the purple class is the legs... how do you make legs on an air unit?!?
if the entire point of specialist units is the ability to walk over walls then explain crawler's existence

**Comment by itcannotbe** [comment]
Simple it needed a base unit and crawlers are the remaining unit without a tree.

**Comment by Kyllingene** [comment]
> No it isn't. They're specialists in chaos. Legs only are instruments in making chaos

Yes, because legs are the best option. They allow ground units (and thus powerful units) to get into enemy bases, which is very good. How do you suggest making a "chaotic" air unit?

**Comment by TheRealIvyX** [comment]
> Because it was made before the rest of the leg units, and no-one wants them removed. Therefore, they made a unit tree off of it

if a unit needs the ability to walk over walls to be considered a specialist unit then why did anuke not give it the ability to do that. congratulations you just contradicted yourself

> And if you would suggest exploding air units

im not going to suggest exploding air units because:
1. they technically already exist in vanilla mindustry in the form of logic controlled flares suiciding above enemy structures while carrying blast compound or pyratite to damage the enemy base
2. i have a mod that adds them so whats the point

**Comment by Kyllingene** [comment]
> if a unit needs the ability to walk over walls to be considered a specialist unit then why did anuke not give it the ability to do that. congratulations you just contradicted yourself

First of all, crawlers were implemented ***way before the purple class***. Look at itcannotbe's comment above, and my own comment.

Secondly, did I say that specialist units *required* lonk legs? No. I simply stated that that was the point *of that tree*. They are often called 'the leg units' because their defining characteristic is their legs. Look at them: even the t2 unit can go over terrain. The Crawler cannot because it would not only be either useless or overpowered with its unique mechanic (suicide), but would also be changing a staple unit just to fit a pattern.

Also, if you would be so kind, please answer these questions:

 - How do you suggest making a "chaotic" air unit?
 - How do you suggest making a "specialist" air unit that isn't just purple support?

**Comment by TheRealIvyX** [comment]
> Did I say that specialist units _required_ lonk legs? No. I simply stated that that was the point _of that tree_.

ah i thought you meant that all specialist units required legs since

> the entire point of the **purple class**

and units with purple decals are specialist units

**Comment by Kyllingene** [comment]
> isnt that kinda what happened to atrax aka purple eruptor with legs

True, true.

> and units with purple decals are specialist units

I'm sorry, I may be unfamiliar with that term. I assumed is was just a term used to refer to units with similar behaviors to the purple class (not generic, but not support). I now know it is a term specifically used to refer to the purple class.

**Comment by notMEEPoffaith** [comment]
> > if a unit needs the ability to walk over walls to be considered a specialist unit then why did anuke not give it the ability to do that. congratulations you just contradicted yourself
> 
> Did I say that specialist units _required_ lonk legs? No. I simply stated that that was the point _of that tree_. They are often called 'the leg units' because their defining characteristic is their legs. Look at them: even the t2 unit can go over terrain. The Crawler cannot because it would not only be either useless or overpowered with its unique mechanic (suicide), but would also be changing a staple unit just to fit a pattern. Why doesn't Anuke make Mono's able to build (slower than core units) so that they fit the pattern? After all, support units are supposed to be able to build.
> 
> Also, if you would be so kind, please answer these questions:
> 
> * How do you suggest making a "chaotic" air unit?
> * How do you suggest making a "specialist" air unit that isn't just purple support?

the chaotic air units would prob involve lots of chaos, such as fire or slag, or bomb spamming. The bombs could also frag into slag or be incinidary

**Comment by notMEEPoffaith** [comment]
oh and also the purple air units would prob involve a lot of chaos, instead of support.

**Comment by Kyllingene** [comment]
> the chaotic air units would prob involve lots of chaos, such as fire or slag, or bomb spamming. The bombs could also frag into slag or be incinidary

NO. ***No-one wants air units dropping lava or tons of bombs.***

**Comment by notMEEPoffaith** [comment]
> NO. _**No-one wants air units dropping lava or tons of bombs.**_

seriously? those are how you make chaos!

**Comment by Kyllingene** [comment]
Then you can deal with (already OP) air units causing insane amounts of unstoppable damage for relatively little cost on the attackers side. ***BALANCING IS A THING***.

**Comment by TheRealIvyX** [comment]
just because an air unit drops bombs doesnt instantly mean that it is overpowered

proof: horizon and the bombardier unit line from my mindustry mod

**Comment by Kyllingene** [comment]
1: a large part of it was the idea of *falling lava*
2: they said bomb *spam* not generic bombing

**Comment by TheRealIvyX** [comment]
> 2: they said bomb *spam* not generic bombing

t3 bombardier from my mod drops bombs that split into many more weaker bombs and it was balanced before build 125 reworked splash damage

**Comment by Kyllingene** [comment]
And how about afterwards? Also, at the point when it isn't OP, bomb dropping is just support units without the healing/building. It is no longer chaotic.

**Comment by Kyllingene** [comment]
If any unit tree is a good fit for a purple unit tree, #2186 seems to be it.

**Comment by Red0Sky** [comment]
i have this idea too why did you take it :(

**Comment by Red0Sky** [comment]
now i have to delete my idea i made :(((((((((((

**Comment by Red0Sky** [comment]
or feature suggestion :'( cus u

**Comment by notMEEPoffaith** [comment]
BRUH

**Comment by notMEEPoffaith** [comment]
do you are have stupid
