### ISSUE TITLE
Asynchronous Logic/Multithreading

### ISSUE THREAD

**Issue by Parkman145** [Anuken/Mindustry-Suggestions#1898]
**Describe the content or mechanics you are proposing.**
Asynchronous logic would be a feature introduced either with a new high-tier processor, or with the hyper processor. Asynchronous code is a rather simple concept, two scripts or "thread" running at the same time, with things like variables and @unit being shared. The only difference is that instead of one variable for the counter, it will have multiple, one for each thread, and each thread can change @counter for other threads. An example of this concept would be: you could have two threads in a processor, one for updating the variables, and one for the main function, that way the variables are constantly updating. If asynchronous Logic is used, the processor will have the same operation speed, and every other operation will be used for each thread. Now if every processor was able to do this, this would probably be way too overpowered, which is why im introducing a new processor type: the multi-threaded processor. The multithreaded processor will be slower than the other processors of the same tier, but will be able to use asynchronous logic. Most likely, the multi-threaded processor will have the speed if the processor tier below it, while costing the same as the processor tier that it is equivalent to. Also, higher tiers for the multi-threaded processor will be able to have more threads running at once. As far as changes to the UI go, in the editor, each thread will either be represented side-by-side, or each thread will have its own separate tab.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I believe it should help make code less messy because you won't have to worry about updating variables multiple times, and with the balancing that i proposed, I feel like it will be more of an alternative to the standard processor, rather than a replacement. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
[async !== multithreading](https://stackoverflow.com/a/34681101)

also, why can't you use multiple processors and memory cells?

**Comment by Humanoid-X** [comment]
@sample-text-here lol i was trying to post that when i noticed your post.

**Comment by Kyllingene** [comment]
> also, why can't you use multiple processors and memory cells?

The only reason I can think of is that you can't put objects (such as units or blocks) into memory cells.

**Comment by Parkman145** [comment]
> [async !== multithreading](https://stackoverflow.com/a/34681101)
> 

Right, my mistake, the phrase I believe i was looking for was parallel processing.
> also, why can't you use multiple processors and memory cells?

Mostly because that has a lot of added complexity and overhead, and that kinda ruins the whole point of what I was getting at, because with that you would have to be constantly reading from the memory cell anyways, so why not just update the variable itself instead? Also, there are other cases where that simply wouldn't work, like when using strings or unit bind.

**Comment by Parkman145** [comment]
> > also, why can't you use multiple processors and memory cells?
> 
> The only reason I can think of is that you can't put objects (such as units or blocks) or strings into memory cells.

^^^
