### ISSUE TITLE
Give reign armor penetration

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1899]
**Describe the content or mechanics you are proposing.**
Make reign ignore armor to make it not as bad of a unit. After some calculations it turns out that the main reason for reign not being that good is its frag bullets simply being stopped by unit armor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Make the reign actually useful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Making frag ignore armor is stupid since that's what armor what armor was supposed to do.

Just change the weapon or make the bullet stronger without making the frag stronger.

**Comment by Ilya246** [comment]
right, you could just severely decresae the firerate but increase the damage even more

**Comment by BlueWolf3682** [comment]
> Making frag ignore armor is stupid since that's what armor what armor was supposed to do. Just change the weapon or make the bullet stronger without making the frag stronger.

"what armor what armor" english.exe

**Comment by RedstonerKBC** [comment]
> > Making frag ignore armor is stupid since that's what armor what armor was supposed to do. Just change the weapon or make the bullet stronger without making the frag stronger.
> 
> "what armor what armor" english.exe

You must feel sooooo good making fun of someone's random insignificant mistake that had little effect on their communication as evidenced by the fact that everyone here except you understood what they meant. You must be so proud to nitpick the tiniest of flaws.

**Comment by Kyllingene** [comment]
All I saw was a little poke of fun at a community member who likes to nitpick people sometimes. Almost makes you wonder if itcannotbe gets away with a lot... no offense meant, they are a great and valuable member, but a lot of what they do only gets criticized when other people do it.

**Comment by itcannotbe** [comment]
> > Making frag ignore armor is stupid since that's what armor what armor was supposed to do. Just change the weapon or make the bullet stronger without making the frag stronger.
> 
> "what armor what armor" english.exe

Nice catch.

**Comment by BlueWolf3682** [comment]
> > > Making frag ignore armor is stupid since that's what armor what armor was supposed to do. Just change the weapon or make the bullet stronger without making the frag stronger.
> > 
> > "what armor what armor" english.exe
> 
> You must feel sooooo good making fun of someone's random insignificant mistake that had little effect on their communication as evidenced by the fact that everyone here except you understood what they meant. You must be so proud to nitpick the tiniest of flaws.

not really, i make the same mistakes in english and i just get a chuckle out of it, when i do it or when someone else does it
