### ISSUE TITLE
Phantom Builder Drones Don't Rebuild Destroyed Buildings Reliably

### ISSUE THREAD

**Issue by deee167** [Anuken/Mindustry-Suggestions#19]
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Phantom Builder Drones Don't Rebuild Destroyed Buildings Reliably.  The best use of the builder drones for me and likely most people is to fix the tedium of manually rebuilding destroyed buildings on the front lines.  This especially becomes an issue on higher waves as buildings frequently get destroyed on the front lines.

What happens typically is that several buildings are left unfinished or not built at all after every wave.  Sometimes one wave is enough to get most buildings to not ever be rebuilt by the drones.  This seems to happen when a drone starts to rebuild a building but then gets destroyed before it finishes it.  The issue is that no builder drone is ever assigned again to finish it.

**Describe the changes you want to propose. Include possible alternatives.**

I would like it so that as long as there is anything unfinished or not even started to be build on the entire map, at least one builder drone will always be assigned to finish it.  If the previous drone is destroyed that was working on it, a new one should be assigned to finish it.

Ie. as long as there is anything unfinished on the map, assign the next free builder drone to finish it, no other conditions.  Always finish building everything on the map.

Thanks.

**Comment by Katsute** [comment]
possible related issue (https://github.com/Anuken/Mindustry/issues/1610)

**Comment by TNT331** [comment]
also there is this weird thing they do....
they build convayor one by one by one and it takes forever... That should relly be changed...

**Comment by deee167** [comment]
Has this been fixed?  There is no status update.

**Comment by itcannotbe** [comment]
And you haven't read this, haven't you?

[Anuken/Mindustry/issues/1610](https://github.com/Anuken/Mindustry/issues/1610)

**Comment by deee167** [comment]
> 
> 
> And you haven't read this.
> 
> [Anuken/Mindustry/issues/1610](https://github.com/Anuken/Mindustry/issues/1610)

No I didn't see that.  thx for the link.  so it might be fixed in 6.0 then?

**Comment by deee167** [comment]
I took a look at the 6.0 features and while there are a lot of good changes and AI changes, there is no mention of this getting fixed.  There is also mention that the 6.0 release might take a year, so I ask again, please fix this in the current version of the game.

**Comment by itcannotbe** [comment]
The AI being pointed out in this issue isn't a part of 6.0
