### ISSUE TITLE
Increase map maximum limit

### ISSUE THREAD

**Issue by LuoYinChuan** [Anuken/Mindustry-Suggestions#1901]
**Describe what you would like changed, and why.**

I want to know if you can increase the maximum size limit of the map, because after playing for some time in the multiplayer game, the largest map has almost no extra space

**Describe the changes you want to propose. Include possible alternatives.**

Increased to 2000 * 2000

**Comment by joshuaptfan** [comment]
The limit likely exists for performance reasons. Just because it might not affect your performance on your device, doesn't mean it won't affect others'.

**Comment by Jammo2000** [comment]
This is mainly meant for multiplayer, where you can have a lame device and
the server does a lot of the work. Maybe not have it in the base game but
allow it for servers, or make it an option of some sort.

**Comment by DeltaNedas** [comment]
1. @Jammo2000 clients still do almost everything the server does
2. phone players be damned
3. you can already do this see epic mod deltanedas/cliff

**Comment by genNAowl** [comment]
^ Shameless self promotion, I see

**Comment by Kyllingene** [comment]
If it fixes the problem...

**Comment by LuoYinChuan** [comment]
> The limit exists for performance reasons. Just because it might not affect performance on your device, doesn't mean it won't affect others'.
> 
> [There was a Discord discussion](https://discord.com/channels/391020510269669376/663853133587546138/796778111332253726) where people tested out a 2000x2000 map, and it caused lag.

Since there will be delay in multiplayer games, can we consider increasing the limit in single player games?

**Comment by joshuaptfan** [comment]
You cannot make something like map size only apply to single player. In any single player custom game, you can click "Host Multiplayer Game" in the menu to convert it to multiplayer.

As others have pointed out, you are already able to bypass the limit with mods or map files saved by someone with a mod.
