### ISSUE TITLE
People are being stupid and are dieing at ground zero

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1902]
**Describe what you would like changed, and why.** nerf ground zero so people dont die there

**Describe the changes you want to propose. Include possible alternatives.** people are being stupid and are dieing at ground zero so you should make ground zero easier

**Comment by itcannotbe** [comment]
Is this a meme suggestion to begin with?

**Comment by BlueWolf3682** [comment]
if people are dying to something you can kill with an alpha thats their fault. close this.

**Comment by catatagun** [comment]
Theres like 2 maces in ground zero do you think an alpha will do that?

**Comment by Cherriodude** [comment]
Yes I do think it's very hard to beat ground zero.
For a start, you don't know anything about the game so it just turns into a top down shooter.
As a solution, remove all the enemies in the game and give the player item sources.

**Comment by QmelZ** [comment]
>  give the player item sources

~~that sounds oddly familiar~~

**Comment by joshuaptfan** [comment]
The point of Ground Zero is to teach players how to use drills and turrets. You need to learn the importance of harvesting ore so you can build and feed turrets, and there needs to be enemies so you learn why turrets are necessary.

The enemies can't be too weak or else the player will just kill them with the alpha, thus not learning the importance of turrets.

The enemies must be able to reach the core, to teach the player that that is what they are defending.

**Comment by itcannotbe** [comment]
> As a solution, remove all the enemies in the game and give the player item sources.

Player be like:
"I hEv A bHuG. i CuNnUt BuIlD iTeM sOuRcEs In CuMpAiN. i Huv TiM iN GrAwn ShErU"

**Comment by itcannotbe** [comment]
Also no matter how easy you make the tutorial level, stupid people will still die.

See tutorial for v3.x complaints about dying.

**Comment by joshuaptfan** [comment]
The only change I would make is to remove the wave timer _only for the first wave_, so that players can take their time reading the hints, fiddling with the interface, etc.

**Comment by Kyllingene** [comment]
Yeah, *no*. I managed to die to water as a ground mech in v5, one of the stupider things possible, and yet even *I* managed to figure out "drill, then conveyor, then turret". Not hard in the least. I'm sorry, but if you die on the tutorial, then *it's doing it's job* by keeping you back. Letting people get further is just going to frustrate them more as they find more blocks to use and more enemies to fight.

**Comment by Yell245** [comment]
The game literally teaches you how to play. It's the player's fault that they die. "but there are maaaaaaaaces(((" - and what? I'll tell you a secret: you can build turrets

**Comment by Kyllingene** [comment]
> Let's kick catatagun

No.

**Comment by WinterCrystal** [comment]
Ground Zero is fine as it is, I don't see why a nerf in difficulty needs to made on that map. If people are dying on that map, it's their fault, let them learn the basics of the game, instead of catering to them.

**Comment by WinterCrystal** [comment]
> Theres like 2 maces in ground zero do you think an alpha will do that?

Maces have terrible range, and deal low damage, a spam of duos and big copper walls is enough to take care a couple of them, both of which I mentioned can be unlocked if the said people you mentioned knows that the campaign has a tech tree.
