### ISSUE TITLE
Option to disable shield tinting/make shields completely transparent

### ISSUE THREAD

**Issue by marky0470** [Anuken/Mindustry-Suggestions#1903]
**Describe what you would like changed, and why.**
An option to disable shield tint completely; shields would only render the outline. This concerns non-animated shields.

FPS drops occur when shields are filling the screen, and multiple are present and overlapping. For me, my FPS capped at 30 (uncapped it is around the 60-70 mark) is reduced to 25 fps.

I'm not sure how shields are rendered so please bear with me, but I believe its caused by all the color-blending. I admittedly don't remember if issues occur when no shields overlap.

**Describe the changes you want to propose. Include possible alternatives.**
So render only the outlines if the option is enabled. Optionally the outlining could follow animated shield outlining, where only outermost lines are drawn. As for alternatives to indication as to which unit is projecting a shield I propose a slight color change on the unit if its shield is still up

**Comment by DeltaNedas** [comment]
1. why do you limit fps to 30
2. how can you only get 70 fps in mindustry, do you have an integrated cpu

**Comment by Kyllingene** [comment]
1. why do his personal choices matter in this particular case
2. why does his cpu matter
3. even if he is being dumb, someone else will have this problem

**Comment by marky0470** [comment]
I limit it to 30 to reduce strain on my potato
70 fps because it's a potato

**Comment by BlueWolf3682** [comment]
one thing i dont understand is how your pc can manage to get strained in mindustry, and also how your pc has a worse gpu than my 8 year old ipad

**Comment by Kyllingene** [comment]
one thing i dont understand is why that matters

**Comment by Yell245** [comment]
> 1. why do you limit fps to 30
> 2. how can you only get 70 fps in mindustry, do you have an integrated cpu

"BUt ITs oNLy YoUR pC iS POtAtO"
Bruh, this person wants to add a possibility for **another** players to optimise their games

**Comment by DeltaNedas** [comment]
if it can run fine on phones perhaps consider installing a cpu and not using a cloud service.
my shitty i3 laptop that blew up got 300 fps, theres really no excuse for lagging.

**Comment by bvcbvc** [comment]
> if it can run fine on phones perhaps consider installing a cpu and not using a cloud service.
> my shitty i3 laptop that blew up got 300 fps, theres really no excuse for lagging.

its generally runs ok on phones, hes talking lategame multiplayer, which will get laggy for potat pc, and even worse for mid to low end phones

**Comment by Kyllingene** [comment]
3 days isn't even any sort of confirmation that Anuken doesn't like this...

**Comment by SheepCommander** [comment]
Exactly

**Comment by bvcbvc** [comment]
anuke no longer comments on these, nor closes wrong ones, he dont have the time nor energy for it

**Comment by Kyllingene** [comment]
Wait, you can't completely turn off shields, but you *can* turn off the animation:
![animatedshields](https://user-images.githubusercontent.com/69094702/106693397-36d94400-658b-11eb-96dd-2516cfa22022.png)
Is this not enough?

**Comment by SheepCommander** [comment]
/shrug for me it's enough but the guy asked to disable shield tint completely so it's not a duplicate

**Comment by SMOLKEYS** [comment]
> /shrug for me it's enough but the guy asked to disable shield tint completely so it's not a duplicate

ah yes, i can see you tried using the discord shrug command on github

**Comment by SheepCommander** [comment]
I'm too lazy to actually use ¯\_(ツ)_/¯

**Comment by marky0470** [comment]
Damn ok, I closed this because it was 24 hours, also because it seemed like this wasn't getting any traction at all with the comments all going to my device instead of the possibility of further optimization.

> Wait, you can't completely turn off shields, but you _can_ turn off the animation:
> Is this not enough?

It would be, however I did some testing and found that the FPS I lost was still significant, and that there wasn't much difference between having the animations turned off or on. This lead me to believe that color blending within the shield was the cause of FPS loss. That despite no longer having animations, color blending and overlapping was significant enough that when stacked would cause FPS drops comparable to having animations on (don't quote me on that though)

**Comment by marky0470** [comment]
> its generally runs ok on phones, hes talking lategame multiplayer, which will get laggy for potat pc, and even worse for mid to low end phones

Exactly, I never even thought about multiplayer, glad you brought that up. There are servers I've been to that like to squeeze maximum potential out of everything, so they even employ quasars for their free shields, most of these servers have higher than normal unit caps so that could very well mean many quasars in one place.

> brUh pc Bad momenTo

I agree my pc is bad. That is all

**Comment by marky0470** [comment]
Even if I did have a decent enough pc, I discovered still that with enough shield overlapping, visibility under these shields becomes very reduced. I had to move my quasar swarm out of the way just so I could make changes to my setup. And no it wasn't the units that obscured visibility, it was the shield tinting itself. I don't know if anyone else has had this shield visibility issue though.

**Comment by marky0470** [comment]
> ![animatedshields](https://user-images.githubusercontent.com/69094702/106693397-36d94400-658b-11eb-96dd-2516cfa22022.png)
> Is this not enough?

A typical mindustry game wouldn't have a bunch of force projectors bunched up in one place, they are usually spaced out which results in less shield stacking and less color blending. However quasars can bunch themselves up into groups due to their small size, which would result in the FPS and visibility problem.
