### ISSUE TITLE
Bridge convenyor changes

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#1905]
**Describe the content or mechanics you are proposing.**

Let bridge convenyor display whats inside and allow players to take them

It will be like this

![Untitled262-1](https://user-images.githubusercontent.com/71065444/106372054-c4a80a00-63a6-11eb-9fe0-9b8943f3c337.jpg)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It might be useless but help players to check if its stucked

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Clicking a bridge conveyor to see its contents would probably a reworking of how block UI works in general, as making it allow you to toggle connections *and* access the inventory is not an action that is currently supported (to my knowledge).

**Comment by joshuaptfan** [comment]
It should be possible, but the block inventory may get in the way. If you are trying to link a bridge block to another bridge block directly to the right, the block inventory would prevent you from clicking on that block except at max zoom with a mouse, similar to the current problem with linking a micro processor with a 1x1 block directly below it.

**Comment by genNAowl** [comment]
Might be better suited for mass drivers

**Comment by RouterChainsSuckk** [comment]
Get foos client. Problem solved

**Comment by Kyllingene** [comment]
"foos client"?

**Comment by RouterChainsSuckk** [comment]
> "foos client"?

yes, it is a client that lets you do what this guy wants and more.

**Comment by Kyllingene** [comment]
But how do you get it? Can it play with non-foo clients?

**Comment by Catchears** [comment]
> But how do you get it? Can it play with non-foo clients?

I had a look at it in v5 (found it on a discord server), and yes, it could play with non-foo clients. It had antigrief and a few other functions, I used it mostly for moderation but here are the ones I remember:

- follow player
- watch player
- patrol path
- automatically go to player / coords
- stop player from building / breaking by doing the exact opposite
- automatic item transfer across the whole map

**Comment by Kyllingene** [comment]
Interesting. Do you have a link, or does it no longer work in v6?

**Comment by Catchears** [comment]
> Interesting. Do you have a link, or does it no longer work in v6?

I think the V6 one isn't done yet (judging by the readme), but I think this is it: https://github.com/blahblahbloopster/mindustry-client-v6
