### ISSUE TITLE
Scale massdriver output with overdrives/domes

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry-Suggestions#1906]
**Describe what you would like changed, and why.**
Massdrivers are limited to 60/s output with or without overdrivers... why?

**Describe the changes you want to propose. Include possible alternatives.**
Scale the mass driver's output with the corresponding overdrive effect.
normal: 60/s
overdrive: 90/s
phase od: 135/s
overdome: 150/s

**Comment by L0615T1C5-216AC-9437** [comment]
if the output is too high make it equal to 1 palstic belt worth of stuff

**Comment by itcannotbe** [comment]
> Massdrivers are limited to 60/s output with or without overdrivers... why?
The same reason why distributors can only do 60/s.
Game limitation.

**Comment by GreyMario** [comment]
Use unloaders.

Case closed.

**Comment by L0615T1C5-216AC-9437** [comment]
Game limitation, understandable but its not like we are talking about a early game item either, i think something should be done about it.
Unloaders? sure they can make em faster but its tedious to implement into a working design
