### ISSUE TITLE
(GRAPHICS OPTION) disable scorch marks from enemies

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1907]
**Describe the content or mechanics you are proposing.**
Add a graphics option to disable scorch marks from enemy units on death. (I tried the existent graphics options and none seem to do this - if there's already a way to do this that i missed, tell me and i'll close the issue)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Scorch marks seem to be quite impactful on performance - they could be toggleable.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheRealIvyX** [comment]
define "scorch mark"

**Comment by Ilya246** [comment]
black spot on the ground that gets left after unit death

**Comment by DeltaNedas** [comment]
good

**Comment by Humanoid-X** [comment]
Enemies won't try to burn the ground when they die. It's blood and not scorch mark.
Also... support!

**Comment by Phinner** [comment]
Oh yes, nice idea!

**Comment by SheepCommander** [comment]
> Enemies won't try to burn the ground when they die. It's blood and not scorch mark.

They're robots, the idea is that they're basically exploding and leaving a scorch mark. 

Although it looks a bit ugly I don't think the scorch marks should be removed, but I guess it'd be fine as a toggleable setting
