### ISSUE TITLE
A Power Generator from Scrap

### ISSUE THREAD

**Issue by WinterCrystal** [Anuken/Mindustry-Suggestions#1908]
**Describe the content or mechanics you are proposing.**

The whole idea of this power generator is that it can produce power by inputting slag from scrap that is produced by melters. How much power it would produce is entirely up to Anuke, but I'm hoping it's between a coal-fed steam generator and a thermal generator working at a 100% efficiency.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will improve the game by adding another option to make power on maps where there's little to no surface slag or hot/lava rocks, or just add another option in making more power. It will also help people playing scrap only maps make power easier

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [XI have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Phinner** [comment]
Don't make scrap more illegal pls.

**Comment by GreyMario** [comment]
I hear there was an enormous fustercluck when Thermal Generators were capable of accepting Slag input.

Let's don't go down that road.

**Comment by WinterCrystal** [comment]
> I hear there was an enormous fustercluck when Thermal Generators were capable of accepting Slag input.
> 
> Let's don't go down that road.

Really? On which version?

**Comment by DeltaNedas** [comment]
.io bullshit

**Comment by Slava0135** [comment]
The short answer is "no"
The long answer is "NO"

**Comment by laok233** [comment]
why should it exists

**Comment by joshuaptfan** [comment]
There is already an entire category of community designs of "scrap to..." power, surge, etc. Plenty of scrap to power options already exist, just indirectly.

**Comment by Kyllingene** [comment]
Looking at it from a realism perspective (which is almost always the wrong one), melting slag should always take more (or in a perfect world, the same amount) power than the slag can produce. From a gameplay perspective, ***why***. Please elaborate on how turning slag (melted basically for free, sometimes actually for free) straight into power sounds like a good idea.

**Comment by itcannotbe** [comment]
So here how it goes. If this pushes through, the next step would be asking for pumps to pump slag, then the generator would be op, since pumps provide in abundance, then it will be nerfed to death, then it will be removed.

Just like last time.

**Comment by genNAowl** [comment]
> pumps to pump slag

We already have slag pumps right? Did you mean extractors?

**Comment by itcannotbe** [comment]
I just forgot that we can pump slag again.

**Comment by XxsuperdeadlysniperxX** [comment]
@WinterCrystal you bacspaced a bracket away

Before: [x]

After:[xI
