### ISSUE TITLE
mono visible

### ISSUE THREAD

**Issue by Wencelsav** [Anuken/Mindustry-Suggestions#1909]
**it can be added resource  visibility switch for mining drones and low clarity  (switch may be added into a core or command center with some radius) or it can be added something like mk2 mono that needs to build 4/6 mono and have mining speed like 1000/1500 and can hold 80/120 . or something like stackable units **

**if one of this ideas will be added it will help with building and visibility under units  **

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What's the suggestion again?

**Comment by Cherriodude** [comment]
> What's the suggestion again?

I don't understand it too but here's my interpretation of it. He proposed two things.

1. Make a slider for unit visibility (he specifically meant mono).
2. Stack the mono's into one to make a mono mk2?

Which uhh... i'm not even sure if i'm right
What's the suggestion again?

**Comment by Kyllingene** [comment]
I agree with your interpretation (but not the validity) of point 2, but I believe they meant something more with point 1. I believe they were asking for a new command center (or a new option in the existing one) which has the ability to toggle the "resource visibility of mining drones", which could either mean "see what they are mining" or "make them unable to mine". I personally think they mean the second.

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry/pull/2034

**Comment by firstcreator48** [comment]
yes
