### ISSUE TITLE
Remove place block feature from processor

### ISSUE THREAD

**Issue by PolishKebab** [Anuken/Mindustry-Suggestions#1910]
**Describe what you would like changed, and why.**

Deleting unit control option to build with processors.

**Describe the changes you want to propose. Include possible alternatives.**
This feature allows people to join a server, place a processor, leave and a couse a lot of mess, that's why i think this feature should not be a thing in processors.

I attacked a link, to show an example of what processor i saw on a server[a guy placed the processor and left]
[place spammer.txt](https://github.com/Anuken/Mindustry-Suggestions/files/5907285/place.spammer.txt)
Kind regards,
PolishKebab

**Comment by PolishKebab** [comment]
Also, place function is too much automation for mindustry [my personal opinion]

**Comment by joshuaptfan** [comment]
It's fine, but its abuse could possibly be prevented by a rule or server plugin.

**Comment by WinterCrystal** [comment]
There's already a server plugin that prevents people from doing exactly that. The CN servers has it, it's only up to the server admins to whether or not implement said plugin, it's fine as it is.

**Comment by GreyMario** [comment]
Balancing around dumbasses in multiplayer isn't really our problem.

**Comment by DeltaNedas** [comment]
> our

**Comment by Yell245** [comment]
Bruh they don't build instantly, just remove the processor and buildings, that's it

**Comment by itcannotbe** [comment]
You forgot looking for that rouge processor isn't exactly a walk in the park.

**Comment by Kyllingene** [comment]
But isn't it better to just make it a server setting instead of *removing the entire command*?

**Comment by antonilol** [comment]
this one is even worse, it builds routers everywere (they can be place on every 1x1 block of the distribution category)
```
ubind @mega
op rand x 20 b
op sub x x 10
op rand y 20 b
op sub y y 10
sensor unitX @unit @x
sensor unitY @unit @y
op add x x unitX
op add y y unitY
ucontrol approach x y 10 0 0
ucontrol flag 0 y 10 0 0
ucontrol build x y @router 0 0

**Comment by stuffyAI** [comment]
I would support the decision for steam-multiplayer hosters to turn of logic for those who join, as when you open your campaign to public you don't really set up the server yourself. Perhaps the host can then whitelist people to use/modify logic blocks if they cannot by default
