### ISSUE TITLE
this is my proposal, hope you add some :)

### ISSUE THREAD

**Issue by Fryto012** [Anuken/Mindustry-Suggestions#1911]
**Describe the content or mechanics you are proposing.**
I have 3 suggestions
First: a folder system in the part of the plans because when you have many it is difficult to find them and even more so when you do not remember the name that you gave for example a folder of energy plans another of silicon production than one You can put whatever name you want.

second: the possibility of putting servers as favorites because you like x server you put it as a favorite and you remove the need to search for it

third and last improvements for factories three types, of consumption production and speed how they would work:
the production one spends more materials but instead gives you more objects,
the consumption that the factories consume less energy and materials,
and the speed that the factories produce faster but will consume more energy
and there may be 2 or 3 levels of these improvements the factories would have 3 holes to put the improvements.
and so that it is not so broken that they are not compatible with each other
or if not in the research part infinite branches of mojora for the character, for the factories, for the units, for the manufacturers of units, energy improvement, or other types of improvements.

Sorry if you don't understand well but I don't know any English and I'm using google translator

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
From my point of view it would give more playability one more reason why to suggest playing games on the planet because most people pass some sectors and unlock the technological tree and leave it I say it because it happens to me that I feel that When unlocking it is a technological tree, I don't know what else to do, it's just my point of view because each head is a world

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1 and 2 are already suggested.

A lot of times already, if only people attempted to actually search before suggesting, we wouldn't have this conversation.

**Comment by itcannotbe** [comment]
For 2, you can just hide the servers that you don't actually join. So that you would only see the servers of your liking.

**Comment by Kyllingene** [comment]
> Additional configuration of blocks, such as I/O side configuration, which has been suggested a million times

This includes *upgrades* (I/O means Input/Output), so don't expect point 3 to be well-received.

**Comment by itcannotbe** [comment]
Not to mention that most production block consume 1 item per item type to make 1 item already rendering Suggestion 3 unfeasible.

The exception are units, phase fabric, surge alloy, silicon, and some item I forgot to mention If I did forget something.

**Comment by Kyllingene** [comment]
Metaglass and graphite?

**Comment by itcannotbe** [comment]
Not to mention block upgrades were shut down multiple times already.

So all in all....... 0 suggestions lived after going through the checks that the template has provided to prevent people from suggesting these things in the first place.

Rating: 10/10
Definitely close this suggestion. It's dead anyway.

**Comment by Kyllingene** [comment]
> It's dead anyway.

It's been here for only 2 hours, 6 comments isn't bad. But I agree, you didn't quite check your suggestions before posting them.

**Comment by Fryto012** [comment]
what happens is that i don't know english
It's already 12 at night and I have to get up early for college classes

**Comment by Fryto012** [comment]
what happens is that i don't know english
It's already 12 at night and I have to get up early for college classes

**Comment by Kyllingene** [comment]
I agree Fryto, your situation is difficult. I would just leave the thread as-is, and do something about it when you have time. Thank you for taking the effort to try and help the community!

**Comment by Fryto012** [comment]
I mean, since they tell me that 1 and 2 are already proposed, there are many ways to implement 3, it wouldn't be like I proposed it, but there are other methods.
If we see in the game creator there is the option to modify the manufacturing time of the units, why not implement an investigation in the same campaign mode, that this also an investigation that the units have a shield, have a life strategy, that the miners produce faster, units do more damage etc.
that one can build or deconstruct faster as things that generate benefits to the player but you are not going to put an investigation that checks you and you spend the campaign easily obvious no

**Comment by Kyllingene** [comment]
Making options for those should be trivial enough, but possibly not necessary.

**Comment by SMOLKEYS** [comment]
> First: a folder system in the part of the plans because > > when you have many it is difficult to find them and even > more so when you do not remember the name that you > > gave for example a folder of energy plans another of > > > silicon production than one You can put whatever name > you want.

This one i _REALLY_ agree with because my _schematics_ are just messy.
Also there should be one for _mods_ . With that i can sort out:
- What mods i use in modded campaign
- Mods for testing
- Random mods
- And a lot more
