### ISSUE TITLE
Maps can be linked to each other

### ISSUE THREAD

**Issue by LuoYinChuan** [Anuken/Mindustry-Suggestions#1912]
**Describe the content or mechanics you are proposing.**

As the size of maps becomes more and more limited, I think it is possible that there will be some association between maps in the future, such as cross map transportation of resources

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

If adopted, I think you should have a resource transfer device and add its identifier. In addition, add the "switch map" option on the map

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
This is already in the game. Late in the campaign, you can unlock the [launchpad](https://mindustrygame.github.io/wiki/blocks/227-launch-pad/) to transfer resources to other sectors.

**Comment by itcannotbe** [comment]
Launch pads be like...

Also. In a multiplayer game, this would be unfeasible.

**Comment by Yell245** [comment]
This guy meant an ability to create such maps bruh
