### ISSUE TITLE
[Android]Right Mouse Button pauses game on some ROMs

### ISSUE THREAD

**Issue by Blue-Beaker** [Anuken/Mindustry-Suggestions#1913]
**Describe what you would like changed, and why.**

On Android there's an option called mouse&keyboard controlls, the right mouse button is used to destroy buildings by default but on some ROMs the right button functions as a back button, which causes the game to pause.

**Describe the changes you want to propose. Include possible alternatives.**
Disable the back action for Right mouse button in game so you can destroy buildings properly.

**Comment by itcannotbe** [comment]
The game can't do shit about it if your android device doesn't allow changing that behavior.

**Comment by DeltaNedas** [comment]
wrong suggestion repo, go pester lineage maintainers

**Comment by Blue-Beaker** [comment]
> The game can't do shit about it if your android device doesn't allow changing that behavior.
> 

Most of the remote desktop apps works well with the right mouse button on my phone however. There must be a way to disable the right-click back feature temporarily

**Comment by joshuaptfan** [comment]
> There must be a way to disable the right-click back feature temporarily

If there is, it won't be in Mindustry. This is not a problem that can be solved in each app you use individually, it's an operating system or driver problem.

**Comment by Blue-Beaker** [comment]
> > There must be a way to disable the right-click back feature temporarily
> 
> If there is, it won't be in Mindustry. This is not a problem that can be solved in each app you use individually, it's an operating system or driver problem. Perhaps there is a setting in the ROM?
> 
> Please close this issue, it's not relevant to Mindustry.

According to those remote desktop apps there IS a way for app to disable right-click back feature temporarily WITHOUT modifying system settings while Mindustry doesn't use. Maybe need to use mouse events like those remote desktop apps does?

**Comment by joshuaptfan** [comment]
> According to those remote desktop apps there IS a way for app to disable right-click back feature temporarily WITHOUT modifying system settings while Mindustry doesn't use. Maybe need to use mouse events like those remote desktop apps does?

App-level fixes may be [possible](https://stackoverflow.com/questions/10041295/android-usb-mouse-right-click-correct-behaviour-ics/29311126#29311126), but I doubt anyone has the stomach to maintain such a fix when right-click may be indistinguishable from normal back button presses depending on the intricacies of each ROM. It would be a nightmare to test, requiring a variety of devices (both Samsung and non-Samsung) and peripherals.

[Quote from Anuke](https://github.com/Anuken/Mindustry/pull/4284#issuecomment-756899495):
> Mindustry's mobile mouse/keyboard support is basically dead. I don't play Mindustry on mobile, and I definitely don't test it with keyboards or mice. It's only functional because libGDX had some code to support it.

**Comment by Blue-Beaker** [comment]
> > According to those remote desktop apps there IS a way for app to disable right-click back feature temporarily WITHOUT modifying system settings while Mindustry doesn't use. Maybe need to use mouse events like those remote desktop apps does?
> 
> App-level fixes may be [possible](https://stackoverflow.com/questions/10041295/android-usb-mouse-right-click-correct-behaviour-ics/29311126#29311126), but I doubt anyone has the stomach to maintain such a fix when right-click may be indistinguishable from normal back button presses depending on the intricacies of each ROM. It would be a nightmare to test, requiring a variety of devices (both Samsung and non-Samsung) and peripherals.
> 
> [Quote from Anuke](https://github.com/Anuken/Mindustry/pull/4284#issuecomment-756899495):
> > Mindustry's mobile mouse/keyboard support is basically dead. I don't play Mindustry on mobile, and I definitely don't test it with keyboards or mice. It's only functional because libGDX had some code to support it.

So according to anuke's comment this most probably not to be fixed?

**Comment by itcannotbe** [comment]
You can't fix what's not broken.

**Comment by Blue-Beaker** [comment]
This may be a fix:
https://stackoverflow.com/questions/10041295/android-usb-mouse-right-click-correct-behaviour-ics/29311126#29311126

> You can also override boolean onKeyDown(int keyCode, final KeyEvent event) and onKeyUp in your activity class, and check if( keyCode == KeyEvent.KEYCODE_BACK && event.GetSource() == InputDevice.SOURCE_MOUSE ) ... to filter keypresses generated by USB mouse, but to process your phone Back key normally. – pelya Jun 4 '15 at 20:10
