### ISSUE TITLE
Opção de inteligência para outras equipes

### ISSUE THREAD

**Issue by AstronautCat380** [Anuken/Mindustry-Suggestions#1914]
**Describe what you would like changed, and why.**
Eu sei que tem a opção de IA para os vermelhos mas eu gostaria de ter uma opção para todos as outras equipes como azul roxo verde.
Seria interessante por que invés de vc só competir com um IA vermelho mais com outros também e AI VS AI.

**Describe the changes you want to propose. Include possible alternatives.**
Mas pra não ficar uma bagunça ter a opção separada. Ex: só o vermelho e também outra opção de todas a equipes.

**Comment by itcannotbe** [comment]
>Describe what you would like changed, and why.
> I know there is an option for AI for reds but I would like to have an option for all other teams like blue purple green.
> It would be interesting because instead of you just competing with a red AI more with others and AI VS AI.

> Describe the changes you want to propose.  Include possible alternatives.
> But not to be a mess to have the separate option.  Ex: only red and also another option for all teams.

How exactly would that make a better game, given the current state of the ai.

**Comment by BlueWolf3682** [comment]
the ai outputs so little offensive power that this wouldnt really be a good idea

**Comment by AstronautCat380** [comment]
Mas e se desse um UP junto com está nova opção?
Deixar um pouco mais difícil?

**Comment by Yell245** [comment]
I think it's an interesting idea. Imagine fighting with several AIs which fight with each others too
