### ISSUE TITLE
js support for ios

### ISSUE THREAD

**Issue by jacklolidk** [Anuken/Mindustry-Suggestions#1915]
**Describe the content or mechanics you are proposing.**

add javascript support for ipad/iphone mindustry

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

let more mods work on mindustry ios version making it actually working with some js mod-needed self hosted servers

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (i think i did)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar r with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
Not happening. iOS doesn't run a JVM.
