### ISSUE TITLE
Tungsten Walls

### ISSUE THREAD

**Issue by Salvonica** [Anuken/Mindustry-Suggestions#1916]
**Describe the content or mechanics you are proposing.**
Strictly defensive. A material primarily used in heat shielding, having an extremely high melting point. Tungsten walls would be similar in strength to titanium, as although tungsten is very strong, it can be shattered and cracked more easily. It would have one special property, it cannot catch on fire, or let fire spread over it.
A idea for making tungsten would be to simply get it from slag, by filling its own 2x2 factory with slag, and mixing copper into it to produce Tungsten Alloy, a conductive, thermal resistance material. Being a good conductor that is heat resistant, field-emitters are also made with tungsten, basically just electromagnetic wave generators, which allow wireless communication. I'm sure there is a more realistic way to make this alloy.
Overall, tungsten alloy can be used realistically in many ways. It is great for constructing wear-resistant electrical appliances, like solar panels, turbines, thermal generators, brighter illuminators, processors, power nodes, and even electromagnetic pulse weapons, which could possibly make small units loose control for a short time.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
A heat resistant wall would allow protecting your production lines from fires, especially those with highly flammable materials, and as well in case it did catch on fire, you could prevent other lines from catching fire as well. Tungsten walls would be especially useful when using the meltdown, as it can accidentally catch your own towers on fire. (unless that is to be fixed/has been fixed already)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
What you want is a hyperspecialized mod with one completely irrelevant material used only for walls that will be, quite simply, outclassed by plastanium, surge, and even thorium walls.

Also, the Meltdown doesn't hit your own buildings and if you have the Meltdown you already have the Wave and a Water Extractor _so you have no excuse not to have either defending your structures against fire._

**Comment by RouterChainsSuckk** [comment]
im pretty sure its a v5 mod

**Comment by Humanoid-X** [comment]
Mods exist

**Comment by itcannotbe** [comment]
How are you going to source tungsten from? Drilling it from the ground?

Oh wait. Wrong version and build.
