### ISSUE TITLE
Items go through routers (and other blocks), it looks like they go under

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry-Suggestions#1917]
https://github.com/Anuken/Mindustry-Suggestions/issues/1821#issuecomment-763770845
![image](https://user-images.githubusercontent.com/49868160/106632062-a5170a00-657d-11eb-8e9a-538455224a92.png)
![image](https://user-images.githubusercontent.com/49868160/106632085-a9dbbe00-657d-11eb-821d-457b84afd7d6.png)

**Comment by DeltaNedas** [comment]
nice you even linked the issue
duplicate of #1821

**Comment by antonilol** [comment]
duplicate author :)

**Comment by Jammo2000** [comment]
Perhaps transparency in the sprite could accomplish this? I don't know how far conveyor blending goes, though. That could be an issue.

**Comment by Humanoid-X** [comment]
maybe junction.png and junction-top.png lol

**Comment by genNAowl** [comment]
I would add that since the item is currently rendered on the conveyor, when it goes into the junction/router, it disappears because it is not on the conveyor anymore. Even if you add a top and bottom sprite, the items will look like before, popping on top of junctions/routers etc. Unless the junction/router renders the item itself, or some extra code is added into the conveyor to support this, I doubt this could be easily implemented (I've tried it myself)

**Comment by Yell245** [comment]
I also would add that items hide under plastanium conveyor when they actually should be at the same level. There's no top of plastanium conveyor so I think it should render items like before

**Comment by itcannotbe** [comment]
> I also would add that items hide under plastanium conveyor when they actually should be at the same level. There's no top of plastanium conveyor so I think it should render items like before

Not anymore.....

**Comment by genNAowl** [comment]
^ https://github.com/Anuken/Mindustry/pull/4446

**Comment by antonilol** [comment]
> Unless the junction/router renders the item itself, or some extra code is added into the conveyor to support this, I doubt this could be easily implemented (I've tried it myself)

Maybe routers, sorters and flowgates should also get the delay junctions have. With the delay you know how far an item is in "passing" the gate.

**Comment by SMOLKEYS** [comment]
I feel like this would be a _vanilla_ version of the Clear Router from Routorio.

**Comment by SMOLKEYS** [comment]
Also think about this, if you made a router cube you would be able to partially see where the item is going.

![Screenshot_20210204-015515_Mindustry BE](https://user-images.githubusercontent.com/75618732/106788559-104f0200-668c-11eb-835b-8b94ae668810.jpg)
Like that for example.

**Comment by antonilol** [comment]
@genNAowl is it possible to code it with this idea? https://github.com/Anuken/Mindustry-Suggestions/issues/1917#issuecomment-772682985
