### ISSUE TITLE
Mlogic is difficult to use

### ISSUE THREAD

**Issue by Ubivashka1998** [Anuken/Mindustry-Suggestions#1918]
**In complex processor circuits, it is extremely difficult to deal with jump blocks, because the jump arrows merge with each other.**

**I suggest that the jump arrows display in different colors and on both sides**
![Screenshot_2021-02-03-18-39-02-389_io anuke mindustry](https://user-images.githubusercontent.com/78484233/106754807-3b673080-664f-11eb-8d3b-9d27637e16c5.jpg)

**Comment by DeltaNedas** [comment]
hover on pc maybe hold on phone to highlight the specific jump's arrow
close this

**Comment by SheepCommander** [comment]
@DeltaNedas although that is true it still would be nicer to visualize if this was added.

Would like it

**Comment by PolloUsami** [comment]
or a option ( maybe texture pack/mod ) that can change the visual aspect of the logic procesors and making it more simple like numbering the commands and the jump comand say that he go to that line

**Comment by Jammo2000** [comment]
> or a option ( maybe texture pack/mod ) that can change the visual aspect of the logic procesors and making it more simple like numbering the commands and the jump comand say that he go to that line

It's called a text editor

**Comment by marky0470** [comment]
maybe instead of having the block's name (set, op, unit control) above the block, put it to left side instead, that way we could cram more actual logic in the screen
