### ISSUE TITLE
Map Making: Core Drops and Enemy Spawns

### ISSUE THREAD

**Issue by potatoisagender** [Anuken/Mindustry-Suggestions#192]
In campaign, there are maps where core drop and/or enemy drop location is varied, such as tar fields and nuclear production plant. If map creators could have an option to select alternate drop zones, I think it would improve maps.

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by nichrosia** [comment]
I agree
