### ISSUE TITLE
Store rotation of repair points

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1920]
**Describe what you would like changed, and why.**

Currently repair points all face upwards by default once you join/load a world, this gives the impression they haven't been used.

**Describe the changes you want to propose. Include possible alternatives.**

Store their rotation in the world stream ❤️ (or not)

**Comment by SheepCommander** [comment]
Don't see any reason not to so I agree, just a little extra detail that makes it somewhat nicer
