### ISSUE TITLE
Enable double multitouch for mobile 

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry-Suggestions#1921]
**Describe the content or mechanics you are proposing.**

Make mobile users be able to use multitouch for moving and building at the same time.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

PC players have a crazy advantage in pvp, because they can move and shoot/build at the same time, while mobile can’t.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SheepCommander** [comment]
This does make sense and sound like a good idea, although admittedly I have no idea how hard/easy that might be to actually setup.

It's done all the time on mobile games (I think) so /shrug

**Comment by itcannotbe** [comment]
Ummmmm. How would multi-touch make mobile's life easier?

**Comment by Axzye** [comment]
> Ummmmm. How would multi-touch make mobile's life easier?
PC players have a crazy advantage in pvp, because they can move and shoot/build at the same time, while mobile can’t.

**Comment by itcannotbe** [comment]
> Ummmmm. How would multi-touch make mobile's life easier?

I mean how, specifically?

**Comment by Sanya2907** [comment]
> > Ummmmm. How would multi-touch make mobile's life easier?
> 
> I mean how, specifically?

You can move your camera and shoot at the same time, atm you can’t.

**Comment by itcannotbe** [comment]
So the game would magically know which touch is for moving the camera and which touch is for shooting?

**Comment by Sanya2907** [comment]
> So the game would magically know which touch is for moving the camera and which touch is for shooting?

Man building on mobile exists. It’s the same thing

**Comment by Kyllingene** [comment]
But does building require two taps at any point in time? Actual question, I never play mobile.

**Comment by XxsuperdeadlysniperxX** [comment]
@itcannotbe 
Multi-touch: a mechanism in game that allows for multiple things on screen to be dragged/tapped without confusing the game and placing a maps length of that block or (if you have a werid phone) somehow managing to crash the game

_if only you could see the power this would give mobile players_

**Comment by XxsuperdeadlysniperxX** [comment]
And the template exists as well boi lets go

**Comment by Kyllingene** [comment]
@XxsuperdeadlysniperxX I believe we all understand how nice it would be. You can get back to us though when you figure out a fool-proof way to disambiguate two touches. Maybe Anuke could develop some fancy gloves that have a different heat (and pressure) output, and then the game could hijack the phones in-built detection system to detect the differences?

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene you don't need a complicated system to it tho i ain't a coder it definitely doesn't need external hardware tho sheesh

**Comment by XxsuperdeadlysniperxX** [comment]
"Handle multi-touch gestures  |  Android Developers" https://developer.android.com/training/gestures/multi

Theres the link to at least the android multitouch gesture support

ios is a different story all together

**Comment by Kyllingene** [comment]
You do realize that is for things like resizing and such? In those cases, differentiating between them is pointless. ***Very*** different from detecting which touch is which.
