### ISSUE TITLE
Restart game

### ISSUE THREAD

**Issue by qingxian555** [Anuken/Mindustry-Suggestions#1923]
can you add restart game in menu?

**Comment by joshuaptfan** [comment]
What would you need that for?

**Comment by itcannotbe** [comment]
Why would did you need to remove the template?

**Comment by itcannotbe** [comment]
What template you ask? This template that would let us know why would you even need that for and what constitutes a "restart"



**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
> What would you need that for?
What do you think? Lol so you don't have to quit, delete the save, recreate the world with all of the same rules.

I do alot of map testing so this would shave off 15 second of my time everytime I have to recreate worlds.

**Comment by RedstonerKBC** [comment]
> What would you need that for?

What do you think? Lol so you don't have to quit, delete the save, recreate the world with all of the same rules.

I do alot of map testing so this would shave off 15 second of my time everytime I have to recreate worlds.

**Comment by Kyllingene** [comment]
> What template you ask? This template that would let us know why would you even need that for and what constitutes a "restart"

You might want to put it in a code block so they can copy/paste without losing formatting:

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by XxsuperdeadlysniperxX** [comment]
Also @qingxian555 let me look for the restart button
**clear research**
**clear campaign saves**
 Done the auto search, heres the the restart button
**_clear game data_**

**Comment by Kyllingene** [comment]
I believe what they meant was restarting a *map*, not the *entire game*.

**Comment by XxsuperdeadlysniperxX** [comment]
There is currently no way to do this and i don't know if this could _kill the game in its entirety because of the capture system_

**Comment by Kyllingene** [comment]
Can literally anyone take two seconds to try to understand what is being suggested? ***They want custom game restart. Not that hard to understand.***

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene 

_no template_
_no mention of it being custom either_
_it just says to add a restart button_
_**being specific helps a whole buch too**_

**Comment by Kyllingene** [comment]
I do not believe this person is an English speaker. If I am not mistaken, they Google Translated it. So can you really expect them to read and fill out the *English* template?

And seriously, "Lol so you don't have to quit, *delete the save*, **recreate the world with all of the same rules.**" Does that *sound* like campaign?

**Comment by itcannotbe** [comment]
> I do not believe this person is an English speaker. If I am not mistaken, they Google Translated it. So can you really expect them to read and fill out the English template?

I do expect them to google translate the template to their own language if they can google translate their response to english, to say the least.

**Comment by RedstonerKBC** [comment]
> I do not believe this person is an English speaker. If I am not mistaken, they Google Translated it. So can you really expect them to read and fill out the _English_ template?

Yes. That's exactly why Translators were invented for this exact purpose.
