### ISSUE TITLE
Fix the Player ID

### ISSUE THREAD

**Issue by TactilElite** [Anuken/Mindustry-Suggestions#1924]
>During when I tried to play in Community server with my friend I couldn't join in (5 times), so I tried to ask for help on the .io Community server in discord as I wonder what does this message mean that kept popping up.
![Screenshot_2021-02-04-14-27-26-92](https://user-images.githubusercontent.com/61498549/106870787-75e2d300-670c-11eb-889f-c4cf3bc14a76.jpg)

As they say that a player with a same I.D. number is on the server, as asked several questions which led me to the conclusion, as the game I.d. is based on the game data in which is my friend and I since before shared the data of our mindustry since V5 ('Tech' is my friend which some people recognize in the Discord community). 

> As I think we need to differentiate mindustry's player data and it's I'd as it's annoying not able to play in a server together due to that data has been shared (exept we didn't share data at this time and on V6) also I'm a beta tester.

**Comment by DeltaNedas** [comment]
ok change your uuid

**Comment by RouterChainsSuckk** [comment]
> ok change your UUID

it is so simple guys

**Comment by SheepCommander** [comment]
well then could you tell op how to change said uuid? .-.

**Comment by XxsuperdeadlysniperxX** [comment]
@DeltaNedas 
Please explain how a person is able to change their uuid because you simply said
>ok then change your uuid

**Comment by itcannotbe** [comment]
multiplayernt basically

**Comment by XxsuperdeadlysniperxX** [comment]
> multiplayernt basically
> 

@itcannotbe multiplayern't doesn't exist anymore

**Comment by itcannotbe** [comment]
That doesn't mean the method used is gone also.

**Comment by XxsuperdeadlysniperxX** [comment]
Can you link it?
