### ISSUE TITLE
Add the -server paramter

### ISSUE THREAD

**Issue by SachaTending** [Anuken/Mindustry-Suggestions#1925]
Add the -server paramter

Example:java -jar Mindustry.jar -server localhost

Open the mindustry and auto connect to localhost

**Comment by itcannotbe** [comment]
What would you need that for?

**Comment by itcannotbe** [comment]
Why would did you need to remove the template?

**Comment by SachaTending** [comment]
This parametr need for my launcher

**Comment by itcannotbe** [comment]
What template you ask? This template that would let us know why would you even need that for.

`**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.`

**Comment by SachaTending** [comment]
1.X 
2.X
3.X
4.X

**Comment by DeltaNedas** [comment]
1. can you please go away with proprietary launchers nobody asked for it
2. rtfsc

**Comment by Kyllingene** [comment]
@itcannotbe, please start putting the template in a code block so they can just copy/paste it and keep the formatting:

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```
