### ISSUE TITLE
We should be able to copy and paste/carry our floor/ore-wall-buildings in Map Maker.

### ISSUE THREAD

**Issue by AntiDrag0n** [Anuken/Mindustry-Suggestions#1928]
**Describe the content or mechanics you are proposing.**

I like to make maps but sometimes I can make mistakes. You might want to carry a part of the map to another place or want to put more of it. Copy and Paste walls, floor/ores and buildings could be nice . We can copy and paste buildings in in-game edit but we can't copy and paste walls and floors/ores. Please put that into game. I saw someone already talked about that before just  a little bit but I just want to remind it this can be exist.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We won't need to rebuild our entire thing instead of carrying it or we can put multiple copies of it. That can save a lot of time and people will love it.

**Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SheepCommander** [comment]
👍

**Comment by itcannotbe** [comment]
We should be able to read, fill up, and not delete the template, especially for feature request.

**Comment by itcannotbe** [comment]
[I have deleted the template and thus did not do a quick search in the list of suggestions to make sure this has not been suggested yet](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+map+copy+paste)

**Comment by itcannotbe** [comment]
What template you ask? THIS ONE.

**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Remember, itcannotbe, you must put it in code blocks so they can copy/paste it directly without losing the formatting:
```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by Humanoid-X** [comment]
Let's ping him/her @itcannotbe

**Comment by AntiDrag0n** [comment]
Sorry for deleting Templates. it was an accident. It won't be happen for sure. I saw someone suggested Copy Paste feature before. But I made an entire post to just for Copy Paste Feature so it would be more effective for adding to the game. I hope you guys will understand.

**Comment by Kyllingene** [comment]
Thank you, AntiDrag0n. As long as you edit it later, I say no harm, no foul.

**Comment by AntiDrag0n** [comment]
Guess it is not effective as I think :D

**Comment by XxsuperdeadlysniperxX** [comment]
Heres something

[X] I have not checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

**Comment by Kyllingene** [comment]
When was that Trello card added?

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene 
This box wasn't checked theirs no box for planned stuff the trello _is for planning so everything thats not in the done box and things that **aren't already implemented** are in the planning stage_ imma try to explain in a moment if you look at this then there should be a edit

**Comment by AntiDrag0n** [comment]
> Heres something
> 
> [X] You have not checked the Trello to make sure your suggestion isn't planned or implemented in a development version.
> Edit: this should be obvious this is telling the guy who is no longer in the mentions box that he didn't check this
> [] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

I checked Trello a little and I didn't see anything about it.

**Comment by Kyllingene** [comment]
Don't worry, there is no such card, and especially with the current state of the world, not doing a deep dive into the Trello is probably a good thing. XxsuperdeadlysniperxX is just being slightly over-aggressive.

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene im not being _aggressive_ like bruh he could check the box regardless if he actually did look at the trello or not _**and what card you talking about**_

**Comment by Kyllingene** [comment]
I'm sorry, I must be getting confused between this issue and a different one. But I was simply saying that they didn't have to worry, there was no Trello card about this.

**Comment by XxsuperdeadlysniperxX** [comment]
._.

**Comment by XxsuperdeadlysniperxX** [comment]
> I'm sorry, I must be getting confused between this issue and a different one. But I was simply saying that they didn't have to worry, there was no Trello card about this.

@Kyllingene its fine 👍

**Comment by AntiDrag0n** [comment]
yay

**Comment by SheepCommander** [comment]
yay

**Comment by AntiDrag0n** [comment]
> [I have deleted the template and thus did not do a quick search in the list of suggestions to make sure this has not been suggested yet](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+map+copy+paste)
> 
> #259

This is from 25 June. What do you expect? Never talk about that feature? Will you insult anybody that has a cool idea but it posted almost 9 months ago and never spoken again?

**Comment by itcannotbe** [comment]
Use the already created thread for discussion. Nothing good is brought about by creating duplicates of already suggested things.

That is what is expected. If you feel offended by facts, please continue acting like a kid. Thanks.

**Comment by AntiDrag0n** [comment]
> Use the already created thread for discussion. Nothing good is brought about by creating duplicates of already suggested things. That is what is expected. If you feel offended by facts, please continue acting like a kid. Thanks.

It is all about supply and demand. If just 1 person wants this feature it won't get taken seriously. If multiple people wants this feature it will taken seriously. I mean your source is 9 months old and youngest post is 3 months ago. There are not many posts about that feature and I saw you redirected almost every one to the *oldest* one. If no one suggest that feature it won't be added. Meanwhile while you are doing this you are lowering people's self-confidence. Now people will be scared when he wants to ask something. Be kind to other people instead of being rude to them.

It won't be world's end when I suggest a feature that posted 9 months ago. So relax, get some water and get hydrated.

**Comment by itcannotbe** [comment]
> It is all about supply and demand. If just 1 person wants this feature it won't get taken seriously. If multiple people wants this feature it will taken seriously.

Reactions exist, you can post your comment on the thread. There is  othing stopping you from doing so.

> I mean your source is 9 months old and youngest post is 3 months ago. There are not many posts about that feature and I saw you redirected almost every one to the oldest one. If no one suggest that feature it won't be added.

That's not how it works here, not every thing is a vote of popularity.
Features don't get added for a number of reasons, including, but not limited to the features isn't a priority to get implemented.

> Meanwhile while you are doing this you are lowering people's self-confidence. Now people will be scared when he wants to ask something. Be kind to other people instead of being rude to them.

If you feel like the fact if the matter is doing this to you, grow up, suck it up and actually what the template/guide requires you to do.

Your really acting like a whiny kid right now.

**Comment by AntiDrag0n** [comment]
> Reactions exist, you can post your comment on the thread. There is nothing stopping you from doing so.
Yeah they do but people don't use them (expect Discord)

> That's not how it works here, not every thing is a vote of popularity.
*Litterally all of them adding because of the popularity*
> Features don't get added for a number of reasons, including, but not limited to the features isn't a priority to get implemented.
If there were any reasons to DO NOT put a feature into the game, a staff must say why it is not possible. I mean they aren't politicians, Are they? :D

> If you feel like the fact if the matter is doing this to you, grow up, suck it up and actually what the template/guide requires you to do.
I am pretty sure Template doesn't let you to insult other peoples and guide. Guide doesn't tell me I can't post Copy-Paste Feature.
 
> You're really acting like a whiny kid right now.
I mean I like whiny kids. They looks very cute when they are angry :D.

> The fact still stands, there is a parameter in the template that makes you do a quick search before making a suggestion so it doesn't get duplicated. If you ignored it once, shame on you, If you still keep pushing it, shame on you more, if you really insist, then there is no hope for you, just grow up and deal with it. It's that simple.

Parameter doesn't work. Especially in detailed matters. If you type just Copy-Paste you must go to the last page to see the future. Other than that I made a *QUICK* Research NOT 50 depth chess analysis. There is in the name. *QUICK* Research. 

But I will close the subject so as not to offend you because you really want to close that pool.

**Comment by AntiDrag0n** [comment]
I realized I completely messed up with text XD.

**Comment by Thankyou69** [comment]
just ignore itcannotbe, all they do is insult and whine and when you tell them to stop they say your the one whining

**Comment by SheepCommander** [comment]
Yep. Ah well
