### ISSUE TITLE
New resources 

### ISSUE THREAD

**Issue by mechanarian** [Anuken/Mindustry-Suggestions#1929]
**Describe the content or mechanics you are proposing.**

I know a lot of people are against these ideas but bear with me here, we have resources produced from just one input, we have resources produced from two inputs and three inputs and even four inputs and we also have resources produced from a liquid input and one solid input. So how about a new resource produced from two solid inputs and one liquid input or two liquid inputs and one solid input, i’m not going to suggest any specific material like other people have because that’s up to Anuke himself but I just think it would be a cool addition to the game

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would add a new difficult thing to get in campaign, I may not speak for everyone put on the majority of maps I don’t end up making surge alloy, I just do it if it’s easy enough to be worth doing. On maps where is not possible or not a viable thing to make it could be a second option to think about

overall just a new interesting thing to think about getting while playing

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
_\*Holds breath...\*_

Mods.

**Comment by mechanarian** [comment]
Ah it would seem that I have the big stupid, I forgot about mods, thanks for reminding me

**Comment by RedstonerKBC** [comment]
Dang. Didn't make it in time to beat out the "mods" comments :disappointed:

I suppose next you "mods" people are going to suggest v7 shouldn't exist either unless someone mods it into the game? You seem to be very happy with pretty much every suggestion of new content being only added via mods.

**Comment by mechanarian** [comment]
> Dang. Didn't make it in time to beat out the "mods" comments 😞
> 
> I suppose next you "mods" people are going to suggest v7 shouldn't exist either unless someone mods it into the game? You seem to be very happy with pretty much every suggestion of new content being only added via mods.

Chances are he just means that as in if I want to use that mechanic now I could use modding

**Comment by sample-text-here** [comment]
mods aren't good for everything, but new resources are what they're made for

**Comment by firstcreator48** [comment]
> mods aren't good for everything, but new resources are what they're made for

yes, true

**Comment by Jammo2000** [comment]
Eventually there should be a new resource or two. Maybe not in v7, that seems to be focused on planets for now, but sometime.

**Comment by Humanoid-X** [comment]
1. Less detail = harder to implement
2. Mods
3. I like this idea
4. Wait, I think there is a reason or bug that Anuke never make a block that can contain two liquids at once...?

**Comment by stuffyAI** [comment]
>     4\. Wait, I think there is a reason or bug that Anuke never make a block that can contain two liquids at once...?

It's not a class in itself but it is possible.

This suggestion is bad. You didn't provide a Use-Case for implementing it, no, you didn't even clearly provide what you want implemented. 
And it's not about new resource types only being supplied by mods, it's about it needing to have a clear, logical purpose in the vanilla game whilst simultaneously matching somewhere in both campaign research and in-map progression. 'So how about a new resource produced from two solid inputs and one liquid input or two liquid inputs and one solid input' is simply not a reason.

**Comment by mechanarian** [comment]
> > ```
> > 4\. Wait, I think there is a reason or bug that Anuke never make a block that can contain two liquids at once...?
> > ```
> 
> 
> It's not a class in itself but it is possible.
> 
> 
> This suggestion is bad. You didn't provide a Use-Case for implementing it, no, you didn't even clearly provide what you want implemented.
> 
> And it's not about new resource types only being supplied by mods, it's about it needing to have a clear, logical purpose in the vanilla game whilst simultaneously matching somewhere in both campaign research and in-map progression. 'So how about a new resource produced from two solid inputs and one liquid input or two liquid inputs and one solid input' is simply not a reason.

I don’t want

**Comment by itcannotbe** [comment]
>     4. Wait, I think there is a reason or bug that Anuke never make a block that can contain two liquids at once...?

There was oncea block that could handle 2 liquids but it was buggy as fuck, It was removed since.

**Comment by Humanoid-X** [comment]
Ah...

**Comment by marky0470** [comment]
> Eventually there should be a new resource or two. Maybe not in v7, that seems to be focused on planets for now, but sometime.

Perhaps a new resource found on only on the new planet?

**Comment by mechanarian** [comment]
> > Eventually there should be a new resource or two. Maybe not in v7, that seems to be focused on planets for now, but sometime.
> 
> Perhaps a new resource found only on the new planet?

I like this idea, like when you use the interplanetary launchpad to move planets for the first time it tells you that a new type of ore deposit has been detected

**Comment by Kyllingene** [comment]
So you want a new resource... just to have a new resource? No actual reason?

**Comment by mechanarian** [comment]
> So you want a new resource... just to have a new resource? No actual reason?

No I wasn’t asking for a new tower or unit or anything like that just suggesting that if and when Anuke adds a new resource it would be cool for it to be made in a different way

**Comment by XxsuperdeadlysniperxX** [comment]
@mechanarian in summary of what people say about reason and being hard to is that being vague with saying you want a resource is not saying
1. Name of resource
2. The statistics of that resource (bound to change slightly)
3. What the resource can be used in i.e units, transport, walls, whatever
4. Explaining the special effects this material may have
5. Answering these questions "would it be early game? (Always the least powerful)", "would it mid game? (The middle ground when it comes to resources)", would be end game? (Most expensive yet most powerful usually)"
6. The resources required to make this resource (for example plastanium is oil and titanium)
7. Finally the damage that the weapons, units, the wall's special abilty, and defense stat of the wall plus answering this how useful is the material to be the new best material

Omg this list is long i hope i didn't miss anything if i did quote this and add whatever i missed cuz this took my an hour to make 🧐

**Comment by mechanarian** [comment]
> @mechanarian in summary of what people say about reason and being hard to is that being vague with saying you want a resource is not saying
> 
> 1. Name of resource
> 2. The statistics of that resource (bound to change slightly)
> 3. What the resource can be used in i.e units, transport, walls, whatever
> 4. Explaining the special effects this material may have
> 5. Answering these questions "would it be early game? (Always the least powerful)", "would it mid game? (The middle ground when it comes to resources)", or "would be end game? (Most expensive yet most powerful usually)"
> 6. The resources required to make this resource (for example plastanium is oil and titanium)
> 7. Finally the damage that the weapons, units, wall's special abilty, and defense stat of the wall will do plus answering this how useful is the material to be the new best material
> 
> Omg this list is long i hope i didn't miss anything if i did quote this and add whatever i missed cuz this took my an hour to make 🧐

My guy, I don’t want to design the whole resource for him, it’s a suggestion not I’m not trying to implement something concrete and all ready thought out, I was only saying it would be fun if when anuke adds a new high tier resource it would be made differently

**Comment by XxsuperdeadlysniperxX** [comment]
Bud what im saying is anuke doesn't have the time or brain power to make a
resource its always better for the community to do that for him so all he
has to do is implement it with the info provided _granted there would be
some tweaks involved_
