### ISSUE TITLE
Google Drive sync

### ISSUE THREAD

**Issue by trix4rix** [Anuken/Mindustry-Suggestions#193]
Adding Google drive sync would allow the game to be cross platform without a file transfer. I currently move the save folder between my windows PC, iPad, and Android phone, all which use the same file, and would allow for Google integration. This would not only allow for backups, but an easy way to move between devices. 

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
I'm not completely sure how feasible this is. It would require gmail account linking, compilers for google and javascript and java and the billion other things involved, and honestly, I'm not sure anuke really wants to deal with all of those things.

**Comment by trix4rix** [comment]
Actually, Google makes it super simple, as it's open source. You only need to integrate Google's Java login, and tell it what files to keep in drive.

Anuke may not be willing to do it, but calling it unfeasible is foolish.

**Comment by potatoisagender** [comment]
Clearly you know more about this than I do. I just noted that a few of these ideas regarding cross platform and multi language were almost always shut down by anuke, and I wasn't sure if this was one of them.

**Comment by trix4rix** [comment]
I'm sure Anuke will shut this down too, but it's worth a shot suggesting it.

**Comment by DeltaNedas** [comment]
you can do this in minutes using git

**Comment by nichrosia** [comment]
It hasn't been shut down yet!

**Comment by phu54321** [comment]
I could push a PR if the dev is willing to merge. I'm new to this repo so maybe I should read some code of conduct or something before doing jobs

**Comment by Anuken** [comment]
This was discussed and rejected.
