### ISSUE TITLE
Make players unable to leave while being vote kicked

### ISSUE THREAD

**Issue by The-incursion** [Anuken/Mindustry-Suggestions#1930]
> **Describe the content or mechanics you are proposing.**
Servers like attanner have been plagued by griefing problems. Every time a griefing player is vote kicked, they leave immediately, rendering mods on site unable to ban him. That's why I request this feature. When vote kicked,player is unable to leave the server before the vote kick ends. If the vote gets below 0,then the vote kick is automatically canceled. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It helps for server admins and moderators to have more time typing in the command. To give greifer greater punishment than just a 1 hour kick or even leaving with no consequences. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. X
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. X
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. X
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category. X

**Comment by itcannotbe** [comment]
[]    <---------- The box.


Kidding aside there are better ways of handling this, like allowing people to still be vote kick even if the said player left the server and/or rejoined afterwards

**Comment by The-incursion** [comment]
The problem is, is that the players id cannot
 Be banned after he left which he'll just return after 1 hour

**Comment by Fipico2** [comment]
And how would you keep them in? How would you prevent them from just using alt+f4 or disconnecting their wifi? Like the other person said, there arebetter ways of doing what you want.

**Comment by TheNightglow** [comment]
Wouldnt a "Recent Players" list for the server admins be a much better solution than to try to force someone to stay in a server? ^^
So the server admins can just select players from a list of recently-connected players and blacklist them, even after they already left the server

**Comment by Slava0135** [comment]
~~just ban them when they leave - problem solved~~

**Comment by DeltaNedas** [comment]
what are ip addresses
what are subnet bans

**Comment by RouterChainsSuckk** [comment]
imagine not being able to ban offline ppl

**Comment by RedstonerKBC** [comment]
Imagine if you couldn't logout of Youtube or another social media app without permanently adding another account to your device OH WAIT you CAN'T logout of Youtube or another social media app without permanently adding another account to your device. If they can get away with it I don't see why Mindustry can't hold people hostage against their will either.

**Comment by SheepCommander** [comment]
Especially since this isn't possible anyways, the best solution would be a "Recent Players" list if you ask me

**Comment by mechanarian** [comment]
Maybe just a feature where the player being vote kicked can’t see the messages in chat that say that it’s happening

**Comment by Fipico2** [comment]
> Maybe just a feature where the player being vote kicked can’t see the messages in chat that say that it’s happening

I dont think this is a good idea, they should be able to defend themselves from what they are beeing accused of

**Comment by mechanarian** [comment]
> > Maybe just a feature where the player being vote kicked can’t see the messages in chat that say that it’s happening
> 
> I dont think this is a good idea, they should be able to defend themselves from what they are beeing accused of

Oh yeah you do have a point

**Comment by The-incursion** [comment]
BTW even if u alt f4 the process is still gonna run back ground for a while meaning ur still there so it gives more time

**Comment by XxsuperdeadlysniperxX** [comment]
@The-incursion 
Heres a possible solution
1. Plugins help
2. Having a permanent list of players that have joined the server therefore the admins would blacklist (ban) them off the server but because if someone alt f4s out all that needs to happen now is to kill the process in the task manager that you can open before even getting in to the game in general or on mobile simply pressing the home button then killing the task through the recent tasks menu or have yoyr phone auto kill all background tasks

**Comment by RedstonerKBC** [comment]
> > Maybe just a feature where the player being vote kicked can’t see the messages in chat that say that it’s happening
> 
> I dont think this is a good idea, they should be able to defend themselves from what they are beeing accused of

I agree but it doesn't matter. The system is so badly broken that anyone can be accused of griefing and get banned while the griefer gets away with it. I know because I get banned from servers almost everyday. Kids can't tell the difference between griefers and someone imporving their design. I can defend all I want but they'll never listen. I can call out the griefer all I want but people don't care.

**Comment by XxsuperdeadlysniperxX** [comment]
Most likely because there's like 10 other greifers that came after them
and/or the other players are young
