### ISSUE TITLE
make UnitType#rotateSpeed actually do something

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1931]
**Describe what you would like changed, and why.**

https://user-images.githubusercontent.com/39013340/107080438-2de5ae00-67e9-11eb-8df4-2042ab9a8948.mp4

Currently rotateSpeed is just used for drawing, it has no influence over moving direction.
A low rotateSpeed turret takes a long time to aim, why don't low rotateSpeed units take a long time to change direction.

**Describe the changes you want to propose. Include possible alternatives.**

Locking change in direction to rotateSpeed.

**Comment by RedstonerKBC** [comment]
Because the engineers of mechs were smart and gave them propellors that can move them in any direction regardless of their current yaw.

**Comment by itcannotbe** [comment]
Hmmmmm. I don't think they're stronk enough to commit tokyo drift.

**Comment by catatagun** [comment]
This idea is bad what about ground units also mobile users when they boost they cant shoot and shooting change direction for mobile so if this is added you will break boosting for mobile

**Comment by Humanoid-X** [comment]
yes

**Comment by itcannotbe** [comment]
> This idea is bad what about ground units also mobile users when they boost they cant shoot and shooting change direction for mobile so if this is added you will break boosting for mobile

Why would it break this behavior?

**Comment by itcannotbe** [comment]
You can always give units a leeway of sorts like, a shooting angle in reference to the direction they are shooting.

Say +/- 7.5° shooting angle where the unit doesn't have to actually rotate to shoot at something?

**Comment by XxsuperdeadlysniperxX** [comment]
It would then make the guns make no sense when firing cuz a guns bullet doesn't shoot south when the gun is pointed north (example of shooting angle leeway making no sense)

**Comment by Kyllingene** [comment]
1: North(0°)-south(180°) `does not equal` 45°-50°

**Comment by XxsuperdeadlysniperxX** [comment]
Did you not read the parentheses?

**Comment by XxsuperdeadlysniperxX** [comment]
Im also mening it wouldn't make sense to give unit anymore leeway than they already have

**Comment by Kyllingene** [comment]
The leeway is so that shooting for mobile users is useable. We are not talking 90° or probably even 45°, just a small leeway. Something more like ***"Say +/- 7.5° shooting angle"
