### ISSUE TITLE
Campaign save

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1932]
**Describe what you would like changed, and why.**the campaign being able to save the game to the save menu because it will allow the saves to be uploaded for bug reports

**Describe the changes you want to propose. Include possible alternatives.**

The campaign having this butten and stuff

![Screenshot_2021-02-05-16-41-50-1](https://user-images.githubusercontent.com/76461235/107097029-a6d90b80-67d1-11eb-9a62-3c5b6d6bc8f7.jpg)

**Comment by catatagun** [comment]
Mobile to be exact

**Comment by DeltaNedas** [comment]
do you think that sectors just arent saved? how can you still play them after reloading mindustry?

close this you egg @catatagun

**Comment by Jammo2000** [comment]
Mindustry/saves/saves

**Comment by catatagun** [comment]
> do you think that sectors just arent saved? how can you still play them after reloading mindustry?
> 
> close this you egg @catatagun

I cant upload them to anywhere

**Comment by itcannotbe** [comment]
You can, you 🥚.

**Comment by catatagun** [comment]
> You can, you 🥚.

Well i dont want to go into the files of mindustry just to find a save only once and some other stuff

**Comment by Kyllingene** [comment]
But then *how do you get saves in the first place*?!?
