### ISSUE TITLE
V5 mindustry classic 2

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1933]
**Describe what you would like changed, and why.** after v7 is released make mindustry classic 2 electric boogaloo witch is v7

**Describe the changes you want to propose. Include possible alternatives.** i dont know what to put here

**Comment by SheepCommander** [comment]
b r u h

**Comment by Kyllingene** [comment]
Catatagun, I really disliked all the comments that wanted you kicked... but now? ***CLOSE***.

**Comment by RouterChainsSuckk** [comment]
you can get v5 quite easily, on pc you can download the old github versions, and on android just download v5 agc
therefore please close this as its pointless

**Comment by WinterCrystal** [comment]
w h a t e v e n i s t h i s ? Think of Anuke before submitting nonsense like this, he reads every suggestion the players make and making him waste time by reading this makes you look really disrespectful.

**Comment by XxsuperdeadlysniperxX** [comment]
B        R          U      H

You are wasting anuke's time by making this suggestion even exist so please **_close this or more people will simply keep saying stop existing on the internet because you are dumb enough to even attempt to suggest this_**
