### ISSUE TITLE
Edit button for processor obstructs block underneath (mobile)

### ISSUE THREAD

**Issue by aaronshenhao** [Anuken/Mindustry-Suggestions#1936]
**Describe the content or mechanics you are proposing.**
The edit button on the microprocessor (and possibly other processors) obstructs the block directly under the processor, which makes it impossible to link/unlink the processor from the block directly below. Trying to link/unlink the processor with the block directly below will only open the code editor. This makes it challenging to create compact designs. My suggestions are:

- Place an "x" button besides the edit button, which will close the edit bar while still allowing us to click blocks around the processor to link/unlink them.
- Place the edit button on the user's UI, rather directly under the processor.
- Allow us to double click the processor to enter linking/editing mode. (Not a good option if processor is under a lot of units)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As mentioned above, modifying the edit button of the processor will make it possible to create more complex designs (mobile). The overlapping edit button is a may be a major hindrance for some players.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
Just zoom in

**Comment by Humanoid-X** [comment]
But good idea tho

**Comment by XxsuperdeadlysniperxX** [comment]
> Just zoom in

@Humanoid-X on mobile you have to both zoom in and preform a near pixil perfect tap on 1×1 blocks when you want to edit the links of that block i can provide an image of the problem at hand
@aaronshenhao your missing the template. (Fun fact: more or less around 50% of people delete the template which anuke doesn't want anyone to do)

**Comment by XxsuperdeadlysniperxX** [comment]
![20210208_205902.jpg](https://user-images.githubusercontent.com/63037076/107309683-85398780-6a50-11eb-927a-5989235485d9.jpg)

![Screenshot_20210208-205727_Mindustry.jpg](https://user-images.githubusercontent.com/63037076/107309695-8c609580-6a50-11eb-8f52-f65a1baded56.jpg)

Both have been taken at max +100 zoom in game and then artificially zoomed in to show the problem closer up in more detail

**Comment by aaronshenhao** [comment]
@XxsuperdeadlysniperxX Thank you for the screenshot. I'll edit the main post according to the template. I didn't have the correct template as I initially used the wrong label, which has a different template apparently.

**Comment by XxsuperdeadlysniperxX** [comment]
No problem

**Comment by Ae-Mc** [comment]
It shouldn't be closed
