### ISSUE TITLE
Option to hide units (mobile)

### ISSUE THREAD

**Issue by aaronshenhao** [Anuken/Mindustry-Suggestions#1937]
**Describe what you would like changed, and why.**

**Describe the content or mechanics you are proposing.**
Allow an easy access to a button on the UI which allows us to hide/show different unit types. Pressing it will open a menu with the icons of all unit types (similar to the button on the code editor which allows us to pick different units in the _bind_ command). By toggling a unit's icon, we can choose whether they are shown or not.

Other possible buttons to include on the menu:
- Select all
- Deselect all
- Always show players
- Always show active units (units that are shooting, taking items, dropping items, but not units in transit)
- Hide all units within a certain radius of the player (build/assessment mode)

Possible hotkey options:
- Toggle hide/unhide all (does not change menu setting, upon unhiding, the menu's setting remains)
- Toggle hide/unhide (from menu)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Trying to view an area with a lot of units decreases the frame rate significantly. Furthermore, having a substantial amount of air units hovering over a location can make editing or damage assessment impossible in that area. 

Due to those two problems, having more units may have a counterproductive effect on the overall gameplay experience. A user may also find it irrelevant to view swarms of lower units such as flares, monos, etc. Allowing the option to hide units will help to provide access to blocks such as the command center, or to enable a clear view of the build area.

I have experienced a bug on multiple occasions on multiplayer, in which I could not see any units at all, nor place any blocks down, but I could still see blocks being placed down and destroyed. The frame rate seemed to be very high, although it was late game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Note (point 1 of declaration)**
Upon further searching (searched for "unit(s)" instead of "hide units"), I found that this idea has been suggested before. I have compiled a list of all relevant posts I could find:

Similar:
#873 Option to make friendly units transparent
#1376  (Closed) Unit transparency toggle, to see buildings/terrain underneath units
#1762 (Closed) Unit Visibility Toggle and Hotkey

Slightly similar:
#1596 Transparent Circle around players when they're building
#1370 Make air units move back when player approaches them
#108 (Closed) Unit Transparency
#1496 (Closed) Make mining units (or any units) mining and in range of the core opaque

**Comment by Humanoid-X** [comment]
AGAIN, RIP TEMPLATE

**Comment by Humanoid-X** [comment]
Just look at some older post and you can find it

**Comment by Kyllingene** [comment]
Duplicate of approx. 237 issues.

**Comment by RouterChainsSuckk** [comment]
why just mobile, also foos cleint allows you to do it

**Comment by aaronshenhao** [comment]
> 
> 
> why just mobile, also foos cleint allows you to do it

I'm posting the suggestion for the mobile (iOS) version of the app, which is what I use exclusively. Foo's client isn't available on iOS.

> 
> 
> Duplicate of approx. 237 issues.

I searched for "is:issue hide units" (both open and closed issues) but there are no issues addressing this problem specifically.

**Comment by marky0470** [comment]
yeah but "hide" and "units" make the search quite narrowed, searching just "units" wouldve allowed you to see most, if not all of them

**Comment by aaronshenhao** [comment]
@marky0470 Thank you, it seems that "transparent units" or "unit transparency" would have been better search terms. I've updated the original post with the correct template (used template from wrong label initially) and a list of all relevant posts.

**Comment by Kyllingene** [comment]
Thank you, aaronshenhao.
