### ISSUE TITLE
New naval branch idea

### ISSUE THREAD

**Issue by AureusStratus** [Anuken/Mindustry-Suggestions#1938]
A class of naval unit that are able to swim through river lakes or oceans of slag

This branch of naval unit will have the ability to cross bodys of slag and they will be able to shoot slag at any enemy structures or units they will be able to travel cross water but they are much slower in water they will be already slower then the current naval branch but they make of for it with there extra health  i also have some ideas for the 5 units of this branch

T1 [pyro] a basic naval unit that has one missile launcher and one slag sprayer

T2 [lava] a medium sized naval unit that has 2 slag sprayers and it can fire explosive long ranged single bullets

T3 [mantle] a big naval unit that has one single slag sprayer that is a little bit stronger then the wave and it has 2 small incendiary bullet guns on the side and in the middle one missile launcher that sets fire to a large area

T4 [fissure] a large naval unit that can give a slight damage buff to nearby friendly units it has one slag sprayer that is more powerful then the wave but less stronger then the tsunami and it has one big cannon that shoot a spread of explosive bullets like the ripple 

T5 [fault line] a massive naval unit that has a high defense and two powerful slag sprayers and it has one large cannon that shoots one single bullets that then burst in to many fragments and lighting everything ablaze dealing alot of aoe damage

If anuke ever sees this and considers doing it you don't have to use the naval branch name and design that i am

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by catatagun** [comment]
Im sad non of them shooted oil @AureusStratus 
You did bad job

**Comment by AureusStratus** [comment]
Okay then

**Comment by mechanarian** [comment]
I would like the new naval unit type as well but if you want anuke actually consider it I would recommend not designing the entire tree for him

**Comment by Kyllingene** [comment]
I actually like this naval suggestion! It's refreshing to see 1: a well thought-out suggestion 2: an *actually good* naval suggestion. +1

**Comment by AureusStratus** [comment]
I don't necessarily want him to use what i suggested for the  naval units its just an idea of what they can be like
