### ISSUE TITLE
endless mode on campaign maps

### ISSUE THREAD

**Issue by dave-the-second** [Anuken/Mindustry-Suggestions#1939]
Add the campaign maps to the custom game menu, or give players some other way to play endless games on them.

One of the main things I miss about V5 is defending maps like tar fields or stained mountains for hundreds of waves, but with the new campaign neither of these can go beyond the initial waves to capture because they aren't next to an attack sector.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
They're not meant to be played endlessly as not all map even have the starting resources to be even played as a custom survival game. And to top it off, the guardian system would look stupid if it can be played endlessly.

**Comment by GreyMario** [comment]
> I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

that's a lie fam

> They're not meant to be played endlessly as not all map even have the starting resources to be even played as a custom survival game.

also not true
maps spawn with a _minimum_ of copper and lead; higher difficulties get titanium and thorium; coal and sand and scrap aren't guaranteed though

**Comment by itcannotbe** [comment]
So how can you progress without coal?

Given that you can't set core loadouts for custom games?

**Comment by Mothership007** [comment]
Just look at the mindustry map discord, where every once in a while somebody reposts all the campaign maps (ground zero, tar fields, etc.)

**Comment by SheepCommander** [comment]
big brain

**Comment by genNAowl** [comment]
Or just download the source code, unzip it, and go to core -> assets -> maps -> boom there's your default campaign maps
