### ISSUE TITLE
Mining Laser Opacity Slider

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#1940]
**Describe the content or mechanics you are proposing.**

Add a slider to turn down mining laser opacity. That's it...

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

So I can see the stuff under my mining drones, similar to power node lasers

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RouterChainsSuckk** [comment]
Why a slider just for that? It should also include stuff like lancers and shit

**Comment by ShadeStrike62** [comment]
> Why a slider just for that? It should also include stuff like lancers and shit

true, but i feel like the most annoying type of laser is the mining one...

**Comment by GreyMario** [comment]
Wow, a suggestion that actually has some thought behind it. Agree, but it can be tricky to deal with partial opacity of multiple stacked things.

**Comment by Kyllingene** [comment]
You say that as if no recent suggestions have had any thought put into them. I have the repo send me notifs on issues, and a lot of those go into junk and I don't bother to root through there, and yet there are plenty of good suggestions.

**Comment by joshuaptfan** [comment]
IMO there should be a single unit opacity toggle (between full opacity and some configurable transparency), and mining laser opacity should be the same as unit opacity.

**Comment by XxsuperdeadlysniperxX** [comment]
> Why a slider just for that? It should also include stuff like lancers and shit

This suggestion affects the mining lazer not the combat lazer @RouterChainsSuckk

**Comment by bvcbvc** [comment]
> Wow, a suggestion that actually has some thought behind it. Agree, but it can be tricky to deal with partial opacity of multiple stacked things.

i pretty sure mining laser uses hex color, so it should be able to have its alpha adjusted
