### ISSUE TITLE
(LOGIC) Move getblock from ucontrol to its own command

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#1941]
**Describe the content or mechanics you are proposing.**
Remove getblock from ucontrol and add it as a separate command

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
There is no reason for getblock to be in ucontrol as it does not depend on a unit, also it not being in ucontrol will allow you to use it even if there is no bound unit

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
1. it does depend on unit
2. i agree that it should be uncoupled from unit range, but it would be really powerful being able to essentially have satellite imagery

**Comment by Jammo2000** [comment]
> 2. i agree that it should be uncoupled from unit range, but it would be really powerful being able to essentially have satellite imagery
We clearly do have satellite imagery, look at planet view or core landing.
