### ISSUE TITLE
Payload Junction

### ISSUE THREAD

**Issue by PurplePikachu** [Anuken/Mindustry-Suggestions#1942]
Payload Junction
In Sandbox it might not matter much, but in Survival, it does
Just make it act like a Junction, except 3x3 and for units
We already have a Payload Router

**Comment by itcannotbe** [comment]
More like a feature request.

**Comment by itcannotbe** [comment]
[This suggestion has already been suggested](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+payload+junction)
