### ISSUE TITLE
logic for units to move onto payload conveyors

### ISSUE THREAD

**Issue by Thankyou69** [Anuken/Mindustry-Suggestions#1943]
**Describe the content or mechanics you are proposing.**
a unit control command that makes units go onto and off of reconstructors and payload conveyors

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this is already accomplishable through unit transport, so i’m just suggesting a way to make it automatic. it would be very helpful to reconstruct units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
More like...

- [X]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by Thankyou69** [comment]
> More like...
> 
> * [x]   I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.

i did

**Comment by itcannotbe** [comment]
Also there isn't a behavior for you to get back into reconstructor yet. How would you even attempt to do that with logic.

**Comment by Thankyou69** [comment]
> Also there isn't a behavior for you to get back into reconstructor yet. How would you even attempt to do that with logic.

you can pick up units with megas/quads/octs and put them on payload conveyors, not reconstructors tho

**Comment by itcannotbe** [comment]
Most units above T3 doesn't even fit onto payload conveyors.

**Comment by Thankyou69** [comment]
> Most units above T3 doesn't even fit onto payload conveyors.

yh im making this suggestion to see if it will be added because i think it will be reasonable. i am well aware of the functions of this game.

**Comment by itcannotbe** [comment]
#553

**Comment by Thankyou69** [comment]
> #553

that does not mention anything about logic controlling units to go onto payload conveyors

**Comment by itcannotbe** [comment]
Also no. The current mechanic is dropping in a unit onto a payload conveyor by using the same mechanics as a unit picking up a block then putting it onto the payload conveyor.

There is no mechanic allowing the unit itself to place itself onto yhe payload conveyor.

**Comment by Thankyou69** [comment]
> Also no. The current mechanic is dropping in a unit onto a payload conveyor by using the same mechanics as a unit picking up a block then putting it onto the payload conveyor.
> 
> There is no mechanic allowing the unit itself to place itself onto yhe payload conveyor.

thats what i meant by it already being possible, now your just restating what i say but in an angry tone

**Comment by Kyllingene** [comment]
^^^

**Comment by Thankyou69** [comment]
im closing this cause its been out for a few days
