### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by Dioo0** [Anuken/Mindustry-Suggestions#1945]
**Describe the content or mechanics you are proposing.**
Improve AI building
AI now sucks- it uses few schems and just ctrl c ctrl v, so whole space near enemy core is just steam gen spam and arc n lancers spam(sometimes it has unit factory, but t2 only)
Also problem, that they use for example phase fabric, but they cant use it cuz they dont have fabric farm

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This can replace real players; can practice on your custom maps

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X]  I am too lazy to do a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
> This can replace real players; can practice on your custom maps

if it was so easy to make AI that resembles humans behavior why not make your own, I'm sure the developer thought of attempting to make one minding the time and resources available st the moment.

If you claim that it's so easy, make one your own.

**Comment by GreyMario** [comment]
Frankly, the AI mimics the average human player pretty well.

**Comment by Kyllingene** [comment]
Making an AI that acts like a human is something Elon Musk is working on. To be fair, a Mindustry-grade good AI would be much simpler than that, but actually good AI's are such complicated things to make, that most (if not all) games with them are based around them in some way.

**Comment by itcannotbe** [comment]
> Frankly, the AI mimics the average human player pretty well.

Well said. 😂😂😂😂😂

**Comment by Humanoid-X** [comment]
1. Anuke is not Elon Musk
2. AI are RAM expensive
3. Try making one yourself if you think it's that easy
Also, Mindustry unit AI are not supposed to be called AI. They are only algorithms. Yeah AI are also algorithms, but AI must consist of learning.

**Comment by Dioo0** [comment]
...
