### ISSUE TITLE
no build radius (not core) 

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#1946]
**Describe the content or mechanics you are proposing.**
a no build radius just like enemy spawn

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
helps map making better

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
So a region where the player can't build... to prevent the player from just plonking down Ripples and attacking the protected item directly to bypass any defenses that are in the no-build zone.

Such as that which you might find around a core.

You haven't proposed a single reason why blocking the player from building in an _arbitrary_ location would be a) beneficial to mapmakers and b) not _immensely confusing/frustrating_ for players.

**Comment by itcannotbe** [comment]
Needs a better title.

**Comment by itcannotbe** [comment]
> So a region where the player can't build... to prevent the player from just plonking down Ripples and attacking the protected item directly to bypass any defenses that are in the no-build zone.
> 
> Such as that which you might find around a core.
> 
> You haven't proposed a single reason why blocking the player from building in an _arbitrary_ location would be a) beneficial to mapmakers and b) not _immensely confusing/frustrating_ for players.

It's a vague suggestion that's implementable in a lot of ways.

**Comment by RouterChainsSuckk** [comment]
There would be needed a way to detsory it otherwise its pointless

**Comment by itcannotbe** [comment]
> There would be needed a way to detsory it otherwise its pointless

So much for giving more tools to the map maker.

Also think of it as some terrain that is walkable but not buildable.

**Comment by SheepCommander** [comment]
The template needs to be updated to include "**Arbitrarily saying it will make something better is not a description**"

**Comment by Kyllingene** [comment]
> The template needs to be updated to include "**Arbitrarily saying it will make something better is not a description**"

You could make a PR. Wouldn't even require any knowledge of programming.

**Comment by XxsuperdeadlysniperxX** [comment]
@unjown you forgot to check the read me box
