### ISSUE TITLE
Units should not replace the conveyor/pipeline when dropping the container!

### ISSUE THREAD

**Issue by Ubivashka1998** [Anuken/Mindustry-Suggestions#1947]
![Screenshot_2021-02-08-10-43-29-097_io anuke mindustry](https://user-images.githubusercontent.com/78484233/107180686-082ff300-69fb-11eb-9b55-1f95b8ad211e.jpg)

[Vault Delivery](https://drive.google.com/file/d/1FokNWzNBqJEY-L6O1pznmsaN5frr_U5K/view?usp=drivesdk)

**Comment by itcannotbe** [comment]
WHAT ARE YOU TRYING TO CONVEY?

**Comment by itcannotbe** [comment]
Also that's a newly added QOL feature. Why do you want to reverse it's addition?

Give your reasons.

**Comment by Ubivashka1998** [comment]
https://user-images.githubusercontent.com/78484233/107184383-47157700-6a02-11eb-80e9-45c4268b4fb2.mp4

**Comment by Ubivashka1998** [comment]
> Также это недавно добавленная функция QOL. Почему вы хотите отменить сложение?
> 
> Назовите свои причины.


https://user-images.githubusercontent.com/78484233/107185610-98bf0100-6a04-11eb-95cc-f68b9dae4a57.mp4

**Comment by Ubivashka1998** [comment]
> Также это недавно добавленная функция QOL. Почему вы хотите отменить сложение?
> 
> Назовите свои причины.

[Vault Delivery](https://drive.google.com/file/d/1FokNWzNBqJEY-L6O1pznmsaN5frr_U5K/view?usp=drivesdk)

**Comment by Ubivashka1998** [comment]
> ЧТО ВЫ ПЫТАЕТЕСЬ ПЕРЕДАТЬ?

[Vault Delivery](https://drive.google.com/file/d/1FokNWzNBqJEY-L6O1pznmsaN5frr_U5K/view?usp=drivesdk)

**Comment by GreyMario** [comment]
Try.

Not misdropping the Vault.

**Comment by SheepCommander** [comment]
this is so confusing

**Comment by genNAowl** [comment]
Or use logic to move yourself (more percise)
