### ISSUE TITLE
Display Production time for tier 1 units in the Core Database

### ISSUE THREAD

**Issue by killsode** [Anuken/Mindustry-Suggestions#1948]
Display production time for Tier 1 units (such as daggers, flares, or rissos) in their description/Core Database

Reconstructors have their production time handily listed in their description, but Factories do not as their production time varies depending on the unit being produced. For example Daggers take 15s, Crawlers take 12s, and Novas take 40s. Listing production time in the units descriptions would provide useful information directly to the player.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by marky0470** [comment]
good, I think displaying production time for all reconstructors directly would be good too

**Comment by SheepCommander** [comment]
👍

**Comment by killsode** [comment]
> good, I think displaying production time for all reconstructors directly would be good too

Reconstructors actually do, tiers 2 through 5 are 10>30>90>240

(for the additive reconstructor)
![Screenshot_32](https://user-images.githubusercontent.com/50812218/107197590-08e27c80-6a2f-11eb-9abb-cdb77d424952.png)

**Comment by Jammo2000** [comment]
Added - https://github.com/Anuken/Mindustry/commit/560914bebe945e297408579a77de72976e52f084
