### ISSUE TITLE
Allow Unit Armor Stats to be seen in a unit's info

### ISSUE THREAD

**Issue by IntervectionX** [Anuken/Mindustry-Suggestions#1949]
**Describe the content or mechanics you are proposing.**
I want to request Anuke on making every unit's armor stats visible to their info so that people can better understand on how tough each units are and what ammo is best for dealing with those especially for new players who are struggling on beating sectors with T4 units in it such as Stained Mountains.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This Unit Armor Stats being seen on a specific unit will help players especially V5 ones who just recently returned back on Mindustry after a long break to realize that metaglass fed scatters, cyclones, or anything they used to use way back before are no longer overpowered now.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
Don't post a suggestion before you ticked the X's.

**Comment by IntervectionX** [comment]
Sorry if i did something wrong, this was just my first suggestion i made in mindustry thats all

**Comment by the-kido** [comment]
He added it!
https://github.com/Anuken/Mindustry/commit/560914bebe945e297408579a77de72976e52f084

**Comment by sample-text-here** [comment]
close this issue (added) and remember to check the boxes next time
