### ISSUE TITLE
water units drag and slowly die on land like a unit in water

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#195]
this would allow water units to move slightly on land and if you have a repair node setup you could slowly move all your water units across the map but it would be expensive

this would create a way for water units to cross land bridges and could add something new to pvp or it could create a niche where players just spam water units and drive them over land

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by walksanatora** [comment]
note they take damage while moving and not just constant damage

**Comment by DAVEtheDuck2287** [comment]
I have reason to believe Anuke will develop this with the coming Naval Units, or he will just make them unable to pass onto land tiles, but it's not a bad idea.
