### ISSUE TITLE
TPS Display

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry-Suggestions#1950]
**Describe the content or mechanics you are proposing.**
It would be nice if clients could see the server's average tps over the last x seconds.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's just something that would be nice to have and would allow us to easily tell when a server is struggling to keep up.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XxsuperdeadlysniperxX** [comment]
This would help a heck of alot when it comes to figuring out whether lag is client side or server side

**Comment by driver1748** [comment]
_It will be helpful.**VERY**_

**Comment by XxsuperdeadlysniperxX** [comment]
Omg would it ever the public client side tps counter would change mindustry
as a whole not literally but multiplayer experience wise like the debug
menu did for minecraft
