### ISSUE TITLE
Logic can't find the unit factories (ulocate in specific)

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1951]
**Describe what you would like changed, and why.**
The unit factories are not considered factories in game and this can be a headache for when you want to target the factories on say pvp or attack

**Describe the changes you want to propose. Include possible alternatives.**
Allow ulocate to find unit factories

Alternative #1 a new logic instruction
Alternative #2 make them classified as a factory

_please look at the tag before you say anything_

**Comment by Kyllingene** [comment]
That doesn't even make sense...

**Comment by Kyllingene** [comment]
```
groundFactory = new UnitFactory("ground-factory"){{
...
airFactory = new UnitFactory("air-factory"){{
...
navalFactory = new UnitFactory("naval-factory"){{
...

additiveReconstructor = new Reconstructor("additive-reconstructor"){{
...
```

It would seem that the game looks for `Reconstructor`s instead of `UnitFactories`. Maybe this could be solved by making them both children of a parent `UnitBlock` class? Oh wait...

```
public class UnitFactory extends UnitBlock{
...

public class Reconstructor extends UnitBlock{
```

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene currently ulocate doesn't have a option for unitblock but i didn't want it to be a "new" feature because its technically not a new feature but more of a balancing thing cuz the instuction to find any of the unit factories doesn't exist and sensors can't "locate" anything they can narrow it down to the specifics but ulocate does the work also radar and uradar currently only find units (i find it some what strange the radar is a slightly different version of uradar but i digress) but thanks for the info

**Comment by XxsuperdeadlysniperxX** [comment]
I hope you understand what im getting at

**Comment by Kyllingene** [comment]
I understand completely and agree.
