### ISSUE TITLE
Mechanic arms

### ISSUE THREAD

**Issue by Onsydeaura22** [Anuken/Mindustry-Suggestions#1952]
**Describe the content or mechanics you are proposing.**

Add mechanic arms like those we have in factorio

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It whoud be very useful for belt-to-belt transportation

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
For plastaninum conveyors, we already have unloaders, and really I don't see the use of this. Also, I don't think Anuke wants mindustry to be compared to factorio any more than it already is.

**Comment by TheRealIvyX** [comment]
just put unloaders next to plastanium conveyors.

**Comment by Onsydeaura22** [comment]
Yo yo, calm down boys, it's just a suggestion, why the thumbs down??

**Comment by Onsydeaura22** [comment]
> For plastaninum conveyors, we already have unloaders, and really I don't see the use of this. Also, I don't think Anuke wants mindustry to be compared to factorio any more than it already is. 

Yeah, i didn't thought about the unloaders, thanks man

**Comment by itcannotbe** [comment]
It "whould" be better if this suggestion didn't existed. There are already things in the game that can mimic the behavior that you want.

AND YOU'RE SUGGESTING TO OUTRIGHT COPY WHAT ANOTHER GAME HAS?

You must be out of your mind, to say the least.

**Comment by Onsydeaura22** [comment]
> It "whould" be better if this suggestion didn't existed. There are already things in the game that can mimic the behavior that you want.
> 
> AND YOU'RE SUGGESTING TO OUTRIGHT COPY WHAT ANOTHER GAME HAS?
> 
> You must be out of your mind, to say the least.
> 

Yo man, no need to be rude, I'm new to the game, gimme a break.

**Comment by TheRealIvyX** [comment]
> Yo yo, calm down boys, it's just a suggestion, why the thumbs down??
because this already technically exists in the form of unloaders right next to plastanium conveyors

**Comment by DeltaNedas** [comment]
conveyor left conveyor router
conveyor                      conveyor

**Comment by bvcbvc** [comment]
> For plastaninum conveyors, we already have unloaders, and really I don't see the use of this. Also, I don't think Anuke wants mindustry to be compared to factorio any more than it already is.

our routers if your a masochist

**Comment by SheepCommander** [comment]
Close.

**Comment by stuffyAI** [comment]
> Yo yo, calm down boys, it's just a suggestion, why the thumbs down??

mate how else u think we can vote on your suggestion? There are even several comments explaining why.
