### ISSUE TITLE
Add New Singularity Reactor

### ISSUE THREAD

**Issue by Tairaptorex** [Anuken/Mindustry-Suggestions#1953]
**Describe the content or mechanics you are proposing.**
The reactor can be placed like any other building and has a unique behavior. When built it must be supplied with 3040/sec power before a little "Stability" bar runs out otherwise it will implode in on itself. after the reactor is stable, any dip in power will cause the reactor to explode if the stability bar runs out. the fuel for the reactor is anything. with a base power output of 3/sec of power.
 It can hold up to thirty of any item. however, more power is outputted for the more different types of items in the reactor. (ex, three copper = 9/sec / one lead, one copper, one sand = 27/sec of power.
however, the more items in the reactor, the faster the stability bar drops, to the point where any loss of power causes the imminent destruction of the reactor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

during most modes you find yourself with a lot of extra resources, so just outputting a little bit of everything into the reactor would provide a great amount of power. As all reactors, explosions are a cool tactic to play with and adds a feeling of hazard long after the enemy's have stopped appearing.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GreyMario** [comment]
There are sixteen item types in the game. You are proposing a maximum itemstack per item of 30. Your example suggests that you are multiplying the number of items by the types of items.

You're proposing a machine which peaks at 7680/s _raw_ power output (with a net power output of 4640/s, assuming the 3040/s upkeep is always required)

That _raw_ power output can be achieved in _net_ power output by roughly five overdriven Differential Generators, six overdriven Thorium Reactors, or outright _outshined_ by a single overdriven Impact Reactor.

**The takeaway:**
You just want something you can build anywhere and go "haha reactor go boom".

**Comment by bvcbvc** [comment]
i kinda want this, and yet i dont because it would just be easier to nuke with it, unless one makes it lategame, and if one uses surge it gets aboce impact in base power perhaps, but it consumes items about 1.5x speed of impact

**Comment by XEN0PHIL** [comment]
I too watch Kurzgesagt videos.
