### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by ricardo1003** [Anuken/Mindustry-Suggestions#1955]
**Describe the content or mechanics you are proposing.**

add an account system where you can save your data such as: your sectors, maps, games, etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Make u need an account for playing multiplayer and this will make griefers after being banned unable to reconnect with vpn or things like that

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X]  I didn't even try making a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by joshuaptfan** [comment]
Hmm, what shows up when you search for "account"?

https://github.com/Anuken/Mindustry-Suggestions/issues?q=account

**Comment by SheepCommander** [comment]
oh god

**Comment by DeltaNedas** [comment]
![Screenshot_12:51:37](https://user-images.githubusercontent.com/39013340/107512432-bc1db380-6b9e-11eb-9fc8-eba1f1922f0a.png)
reading is hard

**Comment by Humanoid-X** [comment]
whiy dident yoiu readf thew reasdme.md it is thee easiesdt thijng to do in the templatre

**Comment by Kyllingene** [comment]
Please close. You evidently didn't bother doing anything the template says.
