### ISSUE TITLE
Nickname for servers

### ISSUE THREAD

**Issue by VajdaSimon** [Anuken/Mindustry-Suggestions#1958]
Hello! My idea would be to give the servers a nickname. This would be good for, say, when you enter an ip, it shouldn't appear but you can enter its name. Of course there would be an info button to see server ip or a settings button to set ip and nickname.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
How would Anuke prevent servers from having duplicate names?

**Comment by VajdaSimon** [comment]
The schematics have already been resolved once.

**Comment by Kyllingene** [comment]
OH, sorry, I was thinking that you were suggesting that the major servers get names. Now I understand and agree.

**Comment by bvcbvc** [comment]
why not just use global list

**Comment by VajdaSimon** [comment]
I mean, why am I making my own server?
