### ISSUE TITLE
the interplanetary launch terminal sends troops all over the planet, because of this, the captured sectors are REGULARLY attacked

### ISSUE THREAD

**Issue by SRBTjej** [Anuken/Mindustry-Suggestions#1959]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fipico2** [comment]
I seriously hope this was made as a joke

**Comment by Kyllingene** [comment]
PLEASE fill out the template. Otherwise, no-one will do anything to this but mock it.

**Comment by SheepCommander** [comment]
c l o s e

**Comment by Newguy-ish** [comment]
n o w

**Comment by GreyMario** [comment]
Bot that detects bad template completions and auto-closes the issue when

**Comment by Newguy-ish** [comment]
now would be very nice

**Comment by WinterCrystal** [comment]
I miss the time when Anuke actually closes threads himself, this maybe one of the reasons why he doesn't do it anymore.
