### ISSUE TITLE
Deepwater Placeables

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#196]
**Describe the content or mechanics you are proposing.**
A new variable for Block.java called `placeDeepWater`

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Allows modders (or vanilla stuff) to be placed in water. One idea could be water equivalents of the Shock Mine to deal with those naval units.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
Would you mean partial and full Deep Water, or full only? or both?

**Comment by DAVEtheDuck2287** [comment]
Would it be neat if instead of a whole 'game rule' if you will, if it was a setting you could turn on or off, or a whole new set of tech that specifically works in water? Not dissing the original idea, it's great.

**Comment by zethnest** [comment]
@DAVEtheDuck2287 Do you mean per map?
