### ISSUE TITLE
Disable automatic sprite generation setting for mods.

### ISSUE THREAD

**Issue by EyeOfDarkness** [Anuken/Mindustry-Suggestions#1961]
In the `mod.json` there should be a setting that disables the `createIcon` function and instead, uses the mods own sprites.

This would allow more customization to sprites without getting overridden, probably decrease loading time if enabled, since it doesn't have to process and change the sprites.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
What would "more customization" entail? createIcons is rather important, as it generates all editor/transition/minified sprites.

**Comment by DeltaNedas** [comment]
99% sure you can override regions in atlas pages after loading
