### ISSUE TITLE
New Discord emojis

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry-Suggestions#1962]
**Describe the content or mechanics you are proposing.**
IMO, these are the most key blocks with the greatest meme potential that have no related representation in the Discord emoji pool:

* Battery
  * You can never have too many of these
* Overdrive Projector
  * For indicating something should be boosted
* Micro Processor
  * For indicating that someone's suggestion can be done with logic

#752 is related, but I'm suggesting much fewer additions.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will increase the range of expression possible with emojis.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Anuke or a moderator has implemented this suggestion.

**Comment by BlueWolf3682** [comment]
that was quick
