### ISSUE TITLE
Better "center" in the editor.

### ISSUE THREAD

**Issue by Xasmedy** [Anuken/Mindustry-Suggestions#1963]
**Describe what you would like changed, and why.**
I want the Center button to be changed because it's still a bit hard to find the center. (It's really a little change so nothing so hard)

**Describe the changes you want to propose. Include possible alternatives.**
This is the normal center button https://prnt.sc/z4ws65, it indicates the center even if it's a bit hard to see expecialy if the terrain it's all the same. This with the change https://prnt.sc/z4wyf9 (Not really a game changer) but could be cool have a little animation for indicate the center and it makes find it easily. I think it will even make look the editor a bit more "made with care".

**Comment by Anuken** [comment]
Enable the grid, and use the location where center lines intersect.

![image](https://user-images.githubusercontent.com/10100000/107700990-442ab880-6c86-11eb-8c6b-c496e8590573.png)

**Comment by Xasmedy** [comment]
I see, thanks.
