### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Skrolex** [Anuken/Mindustry-Suggestions#1964]
Hello! 

Skins to the turrets/drones/alpha/beta/gama/defensive walls etc

Paid/Campagain/Achiemevent skins
Skins would be nice additional content in the game, could be acquired by Achiemevents/Campagain resources/Campagain progres/In game hours/Microtransactions

Theres some things which should be really considedered when adding thoose
-Not P2W or quicker progres mechanics that skins could give, Just pure cosmetic
-Skins should be done in good taste and should be somehow close to the graphic of the game 
-Objects with skins should be easy to recognize 
(like yellow plastanium wall, green surge wall etc) 

Some skin ideas
-multicolor walls
-alpha/beta/gama trials (fade, black, electric etc) 
-other colors of beams, projectiles
-alpha/beta/gama light colour
-core patterns
-adding colour palette to Old skins

Summarizing
-Great way to improve divesitiy od the game 
-Microtransactions will support our lovely dev! 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
But mods....

**Comment by Skrolex** [comment]
> But mods....

Yeah but there will be better way to support dev

**Comment by Kyllingene** [comment]
But people hate microtransactions, and it is impossible for an open-source game to have paid content.

**Comment by itcannotbe** [comment]
This isn't minecraft bud.

Skins won't work because an account system doesn't even exist.

**Comment by Skrolex** [comment]
> But people hate microtransactions, and it is impossible for an open-source game to have paid content.

Anyways i written that it could be achieved via achiemevents campagain etc. too

**Comment by itcannotbe** [comment]
> But people hate microtransactions, and it is impossible for an open-source game to have paid content.

Kids love micro-transaction because it's always their ma or pa's credit card.

**Comment by Skrolex** [comment]
> > But people hate microtransactions, and it is impossible for an open-source game to have paid content.
> 
> Kids love micro-transactions because it's always their ma or pa's credit card.

Its Just idea and i said thoose can be acquired in other ways or Just given all

**Comment by BlueWolf3682** [comment]
ill just use a bunch of the unholy amounts of texturepacks out there

**Comment by sup3r87** [comment]
ea mindustry is generally the most terrifying and worst serious suggestion ive ever come across.
really dont want to come off rude here, but all that stuff is ONLY in first person shooters and should stay that way

**Comment by Skrolex** [comment]
Okay So its closed

**Comment by bvcbvc** [comment]
> Okay So its closed

he gets support through the itch.io im pretty sure

**Comment by DeltaNedas** [comment]
1. anuke is already a millionaire he doesnt need to milk mindustry dry for vbuck money
2. vbuck mod already exist
3. read README.md
4. noob

**Comment by bvcbvc** [comment]
> 1. anuke is already a millionaire he doesnt need to milk mindustry dry for vbuck money
> 2. vbuck mod already exist
> 3. read README.md
> 4. noob

we

**Comment by Skrolex** [comment]
> 1. anuke is already a millionaire he doesnt need to milk mindustry dry for vbuck money
> 2. vbuck mod already exist
> 3. read README.md
> 4. noob

You are pathetic...

**Comment by Kyllingene** [comment]
> You are pathetic...

It was unnecessary (only 1 point was actually helpful), but most of the time, calling someone pathetic makes you look a little... for lack of a better word, pathetic.

**Comment by bvcbvc** [comment]
> > 1. anuke is already a millionaire he doesnt need to milk mindustry dry for vbuck money
> > 2. vbuck mod already exist
> > 3. read README.md
> > 4. noob
> 
> You are pathetic...

my man, you are a joke
