### ISSUE TITLE
Beta unit

### ISSUE THREAD

**Issue by Thankyou69** [Anuken/Mindustry-Suggestions#1965]
**Describe the content or mechanics you are proposing.**
 A fourth base unit. this one would be called the beta, the beta is the stuff that takes control of units but as a separate unit. it cant build, but it can move freely without interacting with anything around it. it would serve as good surveillance and taking control of still alive units past enemy lines. It would be created by pressing c (or any convenient key) while being in control of anything (just not dead) that unit previously being controlled would go back to their ai, if it is a base unit, it dies

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
i think this is already possible with pan mode, so its provably balanced. this would just give it a figure so you can see if they’re there and a cooler presentation.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Thankyou69** [comment]
oh forgot, beta is in the game, i meant omega

**Comment by Cherriodude** [comment]
I'm not gonna lie, I don't exactly understand what you're saying here. What would be the purpose of this?   As far as I understand, you're saying that this "omega" unit can control units and can't build. Actually my brain is hurting a lot just by reading this. Will someone explain it better?

**Comment by Thankyou69** [comment]
> I'm not gonna lie, I don't exactly understand what you're saying here. What would be the purpose of this? As far as I understand, you're saying that this "omega" unit can control units and can't build. The gamma and other core units can already do that. Actually my brain is hurting a lot just by reading this. Will someone explain it better?

its just the stuff that is controlling the units, but as a freely movable unit

**Comment by Thankyou69** [comment]
getting alota hate, closing now

**Comment by DeltaNedas** [comment]
alpha beta gamma omega
yes, the alphabet.

**Comment by Kyllingene** [comment]
Actually, I wouldn't call that "alota hate". It was one person being confused. I personally think this might be a nice QoL feature.

**Comment by Thankyou69** [comment]
> Actually, I wouldn't call that "alota hate". It was one person being confused. I personally think this might be a nice QoL feature.

i was on discord

**Comment by Kyllingene** [comment]
Ah, ok.
