### ISSUE TITLE
Chance slider for Spray tool

### ISSUE THREAD

**Issue by SupremeTurtle** [Anuken/Mindustry-Suggestions#1966]
**Describe the content or mechanics you are proposing.**
A chance slider for the Spray tool, similar to how the Scatter filter has a chance slider.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Makes the spray tool more efficient.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SupremeTurtle** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1492 I just saw this, oops

**Comment by RedstonerKBC** [comment]
It's still a good suggestion though. Hopefully it gets added when copy/paste does too in the next update. It's nice to sprinkle some blocks in an area rather than a whole bunch. Better than spamming them by hand one-by-one.

**Comment by RedstonerKBC** [comment]
Yes I know that's what generation is for but generation applied to the whole map whereas the sprayer only applies where you want it.
