### ISSUE TITLE
hotkey to freeze camera

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1967]
**Describe the content or mechanics you are proposing.**
add a new button, somewhere on the keyboard, that lets you freeze the camera. once the camera is frozen, you can move freely, control other units, or build, except the camera is frozen in place.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it can be used as a handy tool in some situations, for example, pausing the camera in front of the frontlines and timelapsing to see how long it lasts, letting you see the results without risking dying. or, if you want to film units doing things, you can move units around without the camera fixating. it's mostly a community based feature, and can be used as a useful tool for video creators like me and the mindustry youtubers. currently something like this isnt offered on any mods, which is why i suggested it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
good for griefing detection

**Comment by BlueThecno** [comment]
What about possesing a router close to the core and then taking the camera there? Thta would work too.

**Comment by lokyinng** [comment]
good for camping

**Comment by SheepCommander** [comment]
You should probably suggest a hotkey idea tho

**Comment by XxsuperdeadlysniperxX** [comment]
> What about possesing a router close to the core and then taking the camera where you need it to be? That would work too.

The router leaves you vulnerable to a dumba** greifer or some frickin boi that is a a** (im really trying to be kid friendly here like for those like 14 year olds)

**Comment by Kyllingene** [comment]
Why not simply say (if you desire to keep the level of intensity roughly the same) "...to an idiotic greifer... is a dummy..."? Asterisks don't really solve the problem at all.

**Comment by XxsuperdeadlysniperxX** [comment]
They are for censorship tho but if you prefer it the non censored curse word why then ok

**Comment by Kyllingene** [comment]
What I meant is that the censorship does nothing. It's obvious what it is, so it doesn't obscure it. Do you really think any parent will be like "yeah thats fine you can learn cursing as long as you dont read the full words just get them hammered into your head"?

**Comment by BlueThecno** [comment]
> 
> 
> > What about possesing a router close to the core and then taking the camera where you need it to be? That would work too.
> 
> The router leaves you vulnerable to a dumba** greifer or some frickin boi that is a a** (im really trying to be kid friendly here like for those like 14 year olds)
> Edit: and for youtube on the off chance someone looks at the comments while recording a video

I thougt you meant for singleplayer, you know, where THAT DOESN'T MATTER

**Comment by XxsuperdeadlysniperxX** [comment]
@BlueThecno why the hell would this be used in a singleplayer game it could never be used in campaign cuz you have to actively defend and custom games idk why you would want to have freecam anyway but in multiplayer it is useful because it removes the player unit which means you can watch instead of get killed every 2 seconds

**Comment by XxsuperdeadlysniperxX** [comment]
@BlueThecno this is talking mostly about multiplayer and custom games recording a video of something and stuff you can't do in multiplayer like ai wars and that stuff assuming you know how freecam actually works 
_but if you for some reason won't look it up_
Freecam is a hack or game feature (in some cases) that removes the camera from the character to allow only the camera to move around _if_ you have this hack or feature this also (if its a hack) allows you to do illegal moves like place a block on a block you normally can't and this is if you even know what a custom/hacked client even is and you know how (in the case it's a feature) the game feature works @sup3r87 you got the discription backwards

**Comment by XxsuperdeadlysniperxX** [comment]
But it exists and you can't make it stop existing

**Comment by smolkaguya** [comment]
I like this idea.
