### ISSUE TITLE
hjson alternatives

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#1968]
**Describe what you would like changed, and why.**
i know this may be controversial, but because of how much it's hated there needs to be a discussion about this

[hjson](https://hjson.github.io) is [no longer maintained](https://github.com/hjson/hjson/issues/84). (yes i know mindustry uses a custom parser, but the flaws still apply) Although it is community supported, there are still many flaws including
- most features are incompatible with js, making it [more confusing](https://discord.com/channels/391020510269669376/653293028869537843/792626762592026644) for people to switch
- quoteless strings can lead to confusing semantics and/or broken code<sup>[1](#1)</sup>
- ~~[security flaws](https://news.ycombinator.com/item?id=11498077) (though this doesn't apply to mindustry, so i won't count it)~~
- the mindustry community [really](https://discord.com/channels/391020510269669376/653293028869537843/789606987116576839), [really](https://discord.com/channels/391020510269669376/653293028869537843/789485814882238485), [really](https://discord.com/channels/391020510269669376/653293028869537843/689102112793427988), [really](https://discord.com/channels/391020510269669376/631946157496729620/670499402363961345) hates hjson<sup>[2](#2)</sup>

**Describe the changes you want to propose. Include possible alternatives.**
there are two alternatives i could find. both are good, so to whoever's reading this, you can decide which you like better
1. [yaml](https://yaml.org)
2. [json5](https://json5.org)

**yaml**
|pros|cons|
|:-:|:-:|
|more flexible|harder to parse|
|very similar to hjson|not fully js compatable|
|widely adopted||
|has many hjson features, making it easier to switch||

**json5**
|pros|cons|
|:-:|:-:|
|*fully* compatible with js|not as similar to hjson, more work is required to convert mods|
|has a few qol features from js (`NaN`, `Infinity`, hex numbers, etc)||
|json based syntax, easy to switch from/to json5||

simply dropping hjson support for one of the above would be a horrible idea. instead, there could be a grace period, where first modders are notified, then warnings appear for hjson mods, then finally dropping support.

this would be hard, but i think overall the benefits would be better. if there's anything i missed (eg other alternatives, reasons why/why not hjson is good), please tell me. a discussion would be nice, but *please* don't be toxic

---

<p id="1">[1] this does *not* work how you'd think it does and confused me when i first saw it</p>

```
{
  type: ItemTurret,
}
```
<p id="2">[2] including me</p>

**Comment by Humanoid-X** [comment]
hmmm maybe yes

**Comment by BlueWolf3682** [comment]
one problem: imagine converting the entire exotic mod to a new format - it would take weeks or rewriting fields

**Comment by ThirstyBoi** [comment]
@BlueWolf3682 **_This is why you should do js or java :)_**

**Comment by BlueWolf3682** [comment]
no.

**Comment by sample-text-here** [comment]
> one problem: imagine converting the entire exotic mod to a new format - it would take weeks of rewriting fields

hm, good point - i may write a helper script to convert hjson => whatever alternative is most popular

> This is why you should do js or java :)

this isn't about js or java; hjson is popular because it's simple and easier for people to make mods. just saying "use js/java" isn't helping. this issue is about solving how hjson is a mess atm

**Comment by THEGAMER-10n** [comment]
hjson is still used an there's really no point in replacing it with a "higher-level" programming language.

~~how abut python mods?~~

**Comment by sample-text-here** [comment]
neither yaml or json5 are "higher-lever" nor programming language, just configuration files

and ***do not*** the python mod

**Comment by QmelZ** [comment]
i see json5 as a better way to go here instead of yaml, and i fully agree with the suggestion

**Comment by BlueWolf3682** [comment]
> > one problem: imagine converting the entire exotic mod to a new format - it would take weeks of rewriting fields
> 
> hm, good point - i may write a helper script to convert hjson => whatever alternative is most popular
> 
> > This is why you should do js or java :)
> 
> this isn't about js or java; hjson is popular because it's simple and easier for people to make mods. just saying "use js/java" isn't helping. this issue is about solving how hjson is a mess atm

thanks for calling off the "convert/use js/java" for one, its really *word i cant use* annoying 
for two, i hope the converter script keeps indents, or else itll curse any conversions

**Comment by DeltaNedas** [comment]
1. you can just use json
2. flagship parser being abandoned has no influence on the format
3. <something> being abandoned doesnt matter, see rhino and anuken rhino

**Comment by sk7725** [comment]
I think you should write a sample item ammo turret code (which is possibly the most requiring block type in json; featuring color fields(heatColor), list fields(ammo iirc), object fields(assuming you add a consumer because why not), float fields(most of the things), string(name), int(shots), boolean(alternate) itemStack fields(ammo, requirements), mindy class fields(buildVisibility) and more) in all 3(hjson and your 2 alternatives) for comparison.

**Comment by sample-text-here** [comment]
> you can just use json

yes. this isn't about me, this is about new modders using hjson

> flagship parser being abandoned has no influence on the format

one of the first lines i wrote was "yes i know mindustry uses a custom parser, but the flaws still apply"

> being abandoned doesnt matter, see rhino and anuken rhino

same as above. it may be a different parser, but it still uses the same spec

> hjson was used in dec 2019 which is well after 2018, do you think anuke cares now?

that doesn't mean anuke can't switch to a better parser
- yaml is basically the more thought out hjson
- json5 is the default json spec with qol changes
- you could just use plain json, but it gets very annoying

**Comment by sk7725** [comment]
also, hjson is quick, which is yes, trivial at first, but the seconds shaved drastically pile on.

if your alternatives use more than this amount of letters/bytes for an item.hjson (of course without sacrificing readability), I'm against it:
```
color: ffff00
hardness: 3
```

**Comment by sk7725** [comment]
> json5 is the default json spec with qol changes
> you could just use plain json, but it gets very annoying

replace json with json5, and leave hjson be

**Comment by sample-text-here** [comment]
> replace json with json5, and leave hjson be

although many features can be shared, hjson is only partially compatible with json5 (`NaN`, `Infinity`, etc.)

> also, hjson is quick, which is yes, trivial at first, but the seconds shaved drastically pile on.

at first, hjson is quick. but i've seen myself debugging it for dumb reasons (mainly that commas are part of quoteless strings). lenient syntax is great, but to prevent new modders from getting stuck for the same reasons i had, i think there should be a slightly more strict syntax.

<details><summary>here's the comparison between languages</summary> 

json - the original serialization language. very verbose
```json
{
  "color": "fff00",
  "hardness": 3
} 
```

hjson - some improvement on json, but the lenient syntax lets you create hard to catch bugs
```hjson
color: fff00
hardness: 3
```

json5 - hjson while still being js compliant
```json5
{
  color: "fff00",
  hardness: 3
}
```

yaml - looks similar to hjson at first glance, but can yield more complex structures
```yaml
color: "fff00"
hardness: 3
```</details>

**Comment by sk7725** [comment]
I meant sample codes for an ItemTurret, because the ItemTurret type requires almost all field types that exists in mindustry

**Comment by sk7725** [comment]
^ which will make the samples display the differences more clearly

**Comment by sample-text-here** [comment]
updated

**Comment by Anuken** [comment]
> most features are incompatible with js

Mindustry's content json files are already incompatible with JS. Consumer definition, ItemStack definition and many other features cannot be expressed the same way in JS. The two formats are completely unrelated.

> hjson is no longer maintained. (yes i know mindustry uses a custom parser, but the flaws still apply)
> it may be a different parser, but it still uses the same spec

It doesn't use the same spec, actually. I can change it however I want, and have done so in the past.

> commas are part of quoteless strings

That can be changed. There is little good reason to include commas in unquoted strings anyway.

> 1. yaml

YAML is a disaster on all fronts:
- It's difficult to parse
- Spec is massive
- Very easy to screw up indentation and get a broken file with no clear errors
- Can't even use tabs

> 2. json5

Aside from `NaN` and `Infinity` (which have no place in Mindustry mods), json5 is just a stricter subset of hjson. Simply set your editor to `json5` syntax highlighting and use it if you want.

I think the best solution here is to make hjson slightly stricter, ironing out the edge cases.

**Comment by sample-text-here** [comment]
>  ironing out the edge cases

yes, that would be good.

**Comment by Anuken** [comment]
The issue with trailing commas is now fixed. Are there any similar edge cases?

Someone had an issue with
> `color: 7e4242`

parsing as a `float` instead of a `string`, but I'm not sure what can be done about that short of completely disabling exponential notation. *Does* anybody use exponential notation...?

**Comment by BlueWolf3682** [comment]
i dont think anyone uses exponential notation, we all just have the big flat numbers

**Comment by DeltaNedas** [comment]
considering that you can't write expressions like `1/3` in hjson, having exponents is pretty strange.
if they're needed you can always fire up `bc` or something and precalculate it

**Comment by sample-text-here** [comment]
hm, exponential notation is in the official spec, but i don't think anyone uses it.

> The issue with trailing commas is now fixed.

thanks! i'll close this when you decide on whether to keep exponential notation

**Comment by Anuken** [comment]
I'll keep exponential notation for now, as standard JSON + most floating-point parsers support it. It seems extremely unlikely that someone else will define a color with exactly *one* e in the middle and no other letters.

**Comment by sample-text-here** [comment]
ok, makes sense
