### ISSUE TITLE
Easier/smarter Worker/builder drone ai/control

### ISSUE THREAD

**Issue by crownedclown42** [Anuken/Mindustry-Suggestions#1969]
**Describe the content or mechanics you are proposing.**
A better AI/a block which would function like a command center, except for builder drones. As with every playthrough I play, third tier green air units (ones that shoot healing beams) run into the defenses, wanting to heal them, then staying there, either dying or staying there. Second tier ones (builders) rebuild something in the front lines, and stay there again. Basically every unit that heals or builds sits and one place waiting to do something or dies.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Playing single player, where trying to do a lot of things with one brain, is very hard. And when your builders keep dying cause it wants to build some lone conveyor you misplaced in the enemy path and dying in the process is very, very, very, frustrating. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Can be solved with logic. For example, [my mining logic](https://steamcommunity.com/sharedfiles/filedetails/?id=2333571302) allows builder and repair units to rebuild/repair when needed, then resumes mining once there's nothing to repair, moving them away from the front lines.

**Comment by marky0470** [comment]
As for megas dying, logic can be used to make them move towards repair points when below a certain threshold of health

**Comment by Kyllingene** [comment]
In fact, I have written (admittedly pretty poor) logic to do just that.
