### ISSUE TITLE
Mods being able to load as a folder in Mindustry/mods

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry-Suggestions#1970]
**Describe the content or mechanics you are proposing.**

Instead of just a .zip, mods (non-jar) would be able to load in their folder form, making development much easier.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will improve the game by eliminating  the need to compress your mod every single time you want to test it

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sample-text-here** [comment]
this... already exists

**Comment by nichrosia** [comment]
Wait, it does?

**Comment by DeltaNedas** [comment]
jesus christ
