### ISSUE TITLE
anuke first of all i AM your BIGGEST FAN so what i wanted is a distributor block so its like a phase conveyor but what ever goes in will be distributed to what ever is in the middle of it so lets say thers a distributor block on one side and one more on the other and there are spectres in the middle of them and  u input thorium into one side it will distribute it to every spectre........

### ISSUE THREAD

**Issue by Malxhus** [Anuken/Mindustry-Suggestions#1971]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Malxhus** [comment]
please do think of this idea as it will help greatly instead of useing router chains

**Comment by itcannotbe** [comment]
This doesn't make sense even by the slightest.

Even if I did get want you want correctly, it's FREAKING OVERPOWERED.

And yes, router chains are bad because they are made bad, intentionally.

**Comment by itcannotbe** [comment]
Also template be like: I am useless.

**Comment by itcannotbe** [comment]
Basically what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and the read me says something about it...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and the read me says something about not suggesting it...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... I have nothing to say.

**Comment by BlueThecno** [comment]
Ok...

You could put a simple title and then fill the information in the template

On a different note, the idea is good but you could just use router + overflow to solve that (not just routers thats too inefficient)

**Comment by Nexity** [comment]
i dont understand at all. would be useful if you show images since I cant figure out what you are trying to say

**Comment by notrealn** [comment]
h
![image](https://user-images.githubusercontent.com/56411504/107900378-d80eb580-6f0e-11eb-93ea-751df963f5f6.png)

**Comment by Volas171** [comment]
i dont understand what the f that means but all I know it is overpowered

**Comment by Volas171** [comment]
> distributor block so its like a phase conveyor but what ever goes in will be distributed to what ever is in the middle
oh okay I understand now but that's overpowered and actually , a block in the middle bruh , are you going to put a distributor on the center of a weapon or 4x4 block?.

**Comment by hammyofmha** [comment]
> Basically what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and the read me says something about it...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and the read me says something about not suggesting it...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... what you want is considered a teleporter and...... what you want is considered a teleporter and......what you want is considered a teleporter and...... I have nothing to say.

**Comment by Humanoid-X** [comment]
You are not Anuke's biggest fan. You didn't respect him nor his repository nor his template. You treated the template as if nonexistence. I am 100% sure you are not his biggest fan.

**Comment by WinterCrystal** [comment]
Do you even think about the things that you suggest before you actually do it? Because from the looks of it, you don't.

**Comment by Kyllingene** [comment]
Please, *please* think of Anuke.

**Comment by Arkanic** [comment]
lmao this place is a mess

**Comment by driver1748** [comment]
![image](https://user-images.githubusercontent.com/62016462/108174988-23a5a700-713b-11eb-9358-c0af5e242fb6.png)

**Comment by notrealn** [comment]
he hasn't commented or closed this issue yet 

i think this guy doesn't know how to

**Comment by Malxhus** [comment]
> Also template be like: I am useless.

sorry bros jus had an idea

**Comment by python-nerd-3** [comment]
3 year olds.
