### ISSUE TITLE
Anti-grief server options

### ISSUE THREAD

**Issue by oguh43** [Anuken/Mindustry-Suggestions#1973]
**Describe what you would like changed, and why.**
A serverside option to disable unit building/ replacing conveyors via logic.
It's really frustrating whenever someone places a random processor and nukes the map with routers.

**Describe the changes you want to propose. Include possible alternatives.**
Add an option to (one of the following):
disable unit building controlled with logic
disable units replacing blocks via logic
simple fix, change processors colour on the minimap so it can be discovered faster.

**Comment by itcannotbe** [comment]
Altogether now.

Plugins.

**Comment by oguh43** [comment]
> Altogether now. Plugins.

@itcannotbe wow what a nice fix, relying on external sources to fix simple issue

**Comment by SheepCommander** [comment]
the changing processors color on minimap sure, but otherwise I'm just kinda eh

**Comment by itcannotbe** [comment]
> > Altogether now. Plugins.
> 
> @itcannotbe wow what a nice fix, relying on external sources to fix simple issue

If your running a dedicated server, there is literally zero reason why you shouldn't leverage on the ability plugins provide.

**Comment by oguh43** [comment]
> > > Altogether now. Plugins.
> > 
> > 
> > @itcannotbe wow what a nice fix, relying on external sources to fix simple issue
> 
> If you're running a dedicated server, there is literally zero reason why you shouldn't leverage on the ability plugins provide.

If I'm on a dedicated server, its ~ 2-3 people and they're my friends, hence no need for griefing and plugins. Joining any of the popular servers, you can not force them to run plugins. The minimap fix would help this.

**Comment by Kyllingene** [comment]
Joining any of the popular servers, you can not force them to change their settings. The minimap fix would take forever to use effectively, as you would have to root through *every processor on the map*.

**Comment by oguh43** [comment]
> Joining any of the popular servers, you can not force them to change their settings. The minimap fix would take forever to use effectively, as you would have to root through _every processor on the map_.

Imo its a good fix, still better than having to find the actual sprite, sometimes in some weird spot.

**Comment by Kyllingene** [comment]
> Imo its a good fix, still better than having to find the actual sprite, sometimes in some weird spot.

For the life of me I can't find it, but I saw some PR on the game repo with someone implementing a system where you can do something then open the map, and it shows the sprites for all of those blocks. I cannot find it, so I don't know if it was shot down, but it could be a planned feature (it could even exist now without me realizing it).

**Comment by oguh43** [comment]
> > Imo its a good fix, still better than having to find the actual sprite, sometimes in some weird spot.
> 
> For the life of me I can't find it, but I saw some PR on the game repo with someone implementing a system where you can do something then open the map, and it shows the sprites for all of those blocks. I cannot find it, so I don't know if it was shot down, but it could be a planned feature (it could even exist now without me realizing it).
> 
> Also, I just realized that "Server option" is an unhelpful name, could you rename to "Anti-grief server options" or something like that?

renamed

**Comment by unjown** [comment]
just use plugin

**Comment by oguh43** [comment]
> just use plugin

https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779115089

**Comment by itcannotbe** [comment]
> > just use plugin
> 
> [#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779115089)

https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779389520

**Comment by oguh43** [comment]
> > > just use plugin
> > 
> > 
> > [#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779115089)
> 
> [#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779389520)

https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779434507

**Comment by Kyllingene** [comment]
> > > > just use plugin
> > > 
> > > 
> > > [#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779115089)
> > 
> > 
> > [#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779389520)
> 
> [#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779434507)

[#1973 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/1973#issuecomment-779478708)
