### ISSUE TITLE
air pathfind for logic

### ISSUE THREAD

**Issue by lokyinng** [Anuken/Mindustry-Suggestions#1974]
**Describe the content or mechanics you are proposing.**
air pathfind command is for air unit sometimes land unit like making custom air unit pathfinding logic less hard or annoying.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
air pathfind command allows for more custom pathfinding logic or smart unit for PVP also harder map if you are making map with logic. pathfind command use most used for land and navel unit why not an air version of pathfind command.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by lokyinng** [comment]
i used the pathfind command a lot lately

**Comment by Humanoid-X** [comment]
NOOO... STOP MAKING AIR UNITS MORE OVERPOWERED...

**Comment by genNAowl** [comment]
Yeah to be honest, in PVP, air units outclass both ground and naval now because of it's ridiculous mobility.  So much so, in fact, that   games are almost always ended by a rush from the air class (flares, horizons, zeniths, quads)

**Comment by XxsuperdeadlysniperxX** [comment]
Air units in pvp is annoying enough being able to legitimately just b-line it to a block and destroy it so this would just make pvp less enjoyable for newer players just now getting in to pvp

**Comment by lokyinng** [comment]
some server banned logic because it is too op for any unit i don't use it to buff flare it used it for trying to make lich ai

**Comment by lokyinng** [comment]
emp is an hard counter for ai unit but there are not emp turret to shot down any air unit

**Comment by lokyinng** [comment]
> Air units in pvp is annoying enough being able to legitimately just b-line it to a block and destroy it so this would just make pvp less enjoyable for newer players just now getting in to pvp
> EDIT: i barely play pvp but when i do its air units and screaming plus not to mention the shear amount of flippin greifers in the games
> EDIT 2: also hackers are becoming annoying as well like crawler hackers and the such

I also hate hacker or crawler hackers

**Comment by GreyMario** [comment]
Can I have this thread translated to English so I can read it?
