### ISSUE TITLE
Adding separate enemy waves for enemy spawns

### ISSUE THREAD

**Issue by Patryk457** [Anuken/Mindustry-Suggestions#1975]
Eg. first spawn will spawning naval units, second air and land units

**Comment by itcannotbe** [comment]
Apparently you were given the wrong link to make an issue.

**Comment by itcannotbe** [comment]
[The proper one](https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose)

**Comment by itcannotbe** [comment]
And yes, if you went through the checklist the template provides you will realize that this suggestion already exist.

Which means this suggestion should not even exist in the first place.

**Comment by WinterCrystal** [comment]
#1272 a similar suggestion I found.

**Comment by WinterCrystal** [comment]
#325 and another one.

**Comment by Humanoid-X** [comment]
Oh man I suggested this before lol

**Comment by RedstonerKBC** [comment]
me too

**Comment by RedstonerKBC** [comment]
it's a good idea imo though. maybe v7 can add it?
