### ISSUE TITLE
A sorta account system

### ISSUE THREAD

**Issue by Turk3ysandwich** [Anuken/Mindustry-Suggestions#1977]
**Describe the content or mechanics you are proposing.** Make an account system. Can be used for better file syncing between mobile and PC, and improved multiplayer moderation (greifers and whatnot) - can allow friending people you play with so you can play with them again.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** Allows you to sync your progress/schematics between PC and mobile. Improved moderation in multiplayer - we all know a reporting/banning system does already exist. But an account system can keep track of those bans and increase the severity of the bans if needed

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Why did you open this and then close it?

**Comment by itcannotbe** [comment]
Probably he read the read me and found very similar suggestion.

**Comment by Kyllingene** [comment]
It's what I'm assuming too.

**Comment by RedstonerKBC** [comment]
Bruh please no account system! The web has enough accounts as it is. Worse yet more and more are requiring 2-factor authentication and stronger passwords. One day there won't be any words in the dictionary left to even make a password because I'll have used them all already.

**Comment by Turk3ysandwich** [comment]
> Bruh please no account system! The web has enough accounts as it is. Worse yet more and more are requiring 2-factor authentication and stronger passwords. One day there won't be any words in the dictionary left to even make a password because I'll have used them all already.

It was more in the sense to sync campaign progress between platforms
