### ISSUE TITLE
Liquids can enter core, Liquid Launchpad, Liquid Drivers and Liquid unloaders

### ISSUE THREAD

**Issue by NukeToaster** [Anuken/Mindustry-Suggestions#1978]
**Describe the content or mechanics you are proposing.**
Liquids can enter cores
Liquid drivers
Liquid launchpads
Liquid unloaders

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Liquids can enter core: Allowing us to send liquids to our core would let us select it in our loadout and launch into sectors with it(i.e spawning in with 1k water in a no water map for early steam power, yes I know there are water extractors but it's an example) max amount could be  half of whatever core you have (shard core item limit is 4k, liquid could be 2k) 

Liquid unloader: unloads liquid from core and liquid driver

Liquid driver: would be like it's item counterpart for the hard to reach places

Liquid Launchpad: can send liquids to other sector's cores

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Mention how it may add more gameplay options or how it will fill a new niche: Ignored

**Comment by itcannotbe** [comment]
- [X] I have **not** done a quick search in the list of suggestions to make sure this has not been suggested yet.

Liquids can enter cores
Liquid drivers
Liquid unloaders

**Comment by itcannotbe** [comment]
This issue: Time to die now.

**Comment by Kyllingene** [comment]
Yeah, every part of this suggestion has either been suggested and shot down, or is in the README.md (which means you shouldn't suggest it).

Please close.

**Comment by WinterCrystal** [comment]
I support the idea of the Liquid Driver simply because it would save so much space than using conduits, bridges, and routers but someone already mentioned that another user already suggested this. As for everything else, why? It doesn't make any damn sense to put liquid into the core at all, we can already put sand, coal, scrap, and everything else that couldn't be inputted back in v5, what more could you want?

**Comment by Kyllingene** [comment]
Liquid Drivers: #197 #384 #1735

**Comment by Yell245** [comment]
Want to transport liquids between sectors? Scrap is for slag, spore pods are for oil, energy is for water, titanium is for cryo

**Comment by Kyllingene** [comment]
"energy is for water". How does one transport energy cross-sector?

**Comment by itcannotbe** [comment]
> "energy is for water". How does one transport energy cross-sector?

Water extractor.

**Comment by Kyllingene** [comment]
You misread. How does one transport ***energy*** cross-sector so as to *use it in* the water extractors?

**Comment by itcannotbe** [comment]
He meant that you don't need to transport anything since it's just made from power.

Anyways you will need power to change scrap to slag, titanium + water to cryo, and water to spore pods to oil anyways.

**Comment by Humanoid-X** [comment]
Just transfer some pyratite or coal cross sector and plop down energy blocks and that's it.

**Comment by hammyofmha** [comment]
> **Describe the content or mechanics you are proposing.**
> 
> Liquids can enter cores
> 
> Liquid drivers
> 
> Liquid launchpads
> 
> Liquid unloaders
> 
> 
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> 
> 
> 
> Liquids can enter core: Allowing us to send liquids to our core would let us select it in our loadout and launch into sectors with it(i.e spawning in with 1k water in a no water map for early steam power, yes I know there are water extractors but it's an example) max amount could be  half of whatever core you have (shard core item limit is 4k, liquid could be 2k) 
> 
> 
> 
> Liquid unloader: unloads liquid from core and liquid driver
> 
> 
> 
> Liquid driver: would be like it's item counterpart for the hard to reach places
> 
> 
> 
> Liquid Launchpad: can send liquids to other sector's cores
> 
> 
> 
> **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
> 
> 
> 
> 
> 
> 
> 
> 1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> 2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 
> 3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> 4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
>

**Comment by Phinner** [comment]
Watercooled cores...
*Mmmh.... let's make a mod out of it...*

**Comment by Humanoid-X** [comment]
REPORT THAT SPAM BOT

**Comment by ScepterReignPlayz** [comment]
> Want to transport liquids between sectors? Scrap is for slag, spore pods are for oil, energy is for water, titanium is for cryo

Scrap as well for Cyro

Titanium can be produced from separators

**Comment by kapzduke** [comment]
ok i understand liquid mass drivers , liquid unloaders etc but LIQUID LAUNCH PAD??
