### ISSUE TITLE
Imma say this now is ruinous shores supposed to have two active spawn points or nah

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1979]
**Describe what you would like changed, and why.**
If the spawn points are supposed to be random than this needs changing if not then lol

**Describe the changes you want to propose. Include possible alternatives.**
I don't have alternatives cuz its like one small issue that either is unintentional or intentional

**Comment by XxsuperdeadlysniperxX** [comment]
Heres what i know happened
1. The spawns were only one
2. They at one point random
Currently they both now exist together

**Comment by joshuaptfan** [comment]
Yes, Ruinous Shores is supposed to have 2 spawn points active simultaneously.

**Comment by Cherriodude** [comment]
As said, it is supposed to have 2 spawn points. Please close this. Thanks :)

**Comment by XxsuperdeadlysniperxX** [comment]
I know discord exists

**Comment by XxsuperdeadlysniperxX** [comment]
@Cherriodude the only thing i can access with my current internet is github

**Comment by Kyllingene** [comment]
Dude, in v5, I thought Ruinous Shores was *weaksauce*. Seriously, 1 spawn point on that map was *easy*. I love the change!
