### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by Morso8** [Anuken/Mindustry-Suggestions#1981]
**Describe the content or mechanics you are proposing.**
Arabic language for the game

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It'll increase the player base in arabic countries, I've seen the arabic reviews in Play store most of the complaints were because there wasn't arabic language.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
Why don't you make a pr

**Comment by itcannotbe** [comment]
Basically RTL is a pain, so there isn't support to begin with.

**Comment by joshuaptfan** [comment]
Mindustry doesn't support Arabic and other RTL languages, because libGDX doesn't.

https://discord.com/channels/391020510269669376/395414970793459714/789997183494782986
https://github.com/libgdx/libgdx/issues/787

**Comment by Kyllingene** [comment]
A shame. If anyone knows how to weave support for a very complicated system into some very dense programming without breaking ***anything*** in Mindustry (or at the very least, fixing it with the same push), then please do.

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene i can't believe adding support for a complicated system could brick the entire game _this is power and one change could end it all_

**Comment by itcannotbe** [comment]
Did you even read the linked issue from the forked library which mindustry uses?

**Comment by Kyllingene** [comment]
I never indicated it would breack the *entire* game, just a lot of display stuff.
