### ISSUE TITLE
Nerf Mega

### ISSUE THREAD

**Issue by docElement63e** [Anuken/Mindustry-Suggestions#1982]
Set build speed from Mega to 200%

**Comment by Thankyou69** [comment]
no

**Comment by Humanoid-X** [comment]
no thx

**Comment by Kyllingene** [comment]
labels go brrr

**Comment by WinterCrystal** [comment]
No thanks, Mega is fine as it is. No nerfs needed.

**Comment by lokyinng** [comment]
nerf flare not mega

**Comment by XxsuperdeadlysniperxX** [comment]
@docElement63e 

You have this still open here whats wrong
1. Its a normal issue no label no template to apply to the label your suggestion is nonexistent
2. You should reevaluate your life choices if you think mega needs a nerf as it is a t3 support unit
3. Absolutely no one wants the megas build speed nerfed
4. This line is a lie
5. This line is not 4 thus its the truth
6. Suggestions like these trigger me
7. This line is 5 thus it is now 4 which is not a lie

**Comment by catatagun** [comment]
> Set build speed from Mega to 200%

Close you no use the whatever its called
