### ISSUE TITLE
Add different shapes of an active shield or force projector type shields

### ISSUE THREAD

**Issue by IntervectionX** [Anuken/Mindustry-Suggestions#1985]
**Describe the content or mechanics you are proposing.**
I want a request to add different kinds of shapes of force projector type shields so that this can be a good purpose to indicate on how durable the shield is despite the size of it like a Quasar gets a pentagon shaped shield due to having a weaker shield while Oct gets an octagon shaped shield due to its extremely high durable shield.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I know this doesn't look much but im sure this will make shields have a more decorative capabilities rather than just being all hexagon shaped plus it would also be a possible indicator on how tough the shield is. This will also help mod makers to have more bright ideas for them to create units or buildings that has something to do with active shields.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
See:

https://github.com/Anuken/Mindustry/pull/1323#issuecomment-605389478

**Comment by IntervectionX** [comment]
Well unlike the other one, this one doesn't request on rotating shields but rather just change the shapes of all unit's force projector type shields but perhaps it does have some drawbacks...i'll just wait for more comments before i close this.

**Comment by SheepCommander** [comment]
So more sides to the shape indicates it being stronger?

I'd be fine with that but it'll be one of many things where you don't know until you know

**Comment by itcannotbe** [comment]
Add too many sides and you'll get what looks like a circle already.

**Comment by IntervectionX** [comment]
How about only a few shapes would be added like Square,Pentagon, and lasty Octagon. The octagon shape would be the strongest one and it fits to Octs name and shield durability.

**Comment by G0nTar** [comment]
I would also be cool, If like launch pads, you could open a menu on the shield proyector, and choose a size or shape different shapes or sizes have according weakness, the bigger the weaker, but it covers a wider or more specific area

**Comment by firstcreator48** [comment]
noice...
