### ISSUE TITLE
Make overdrive increase paralax range

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1986]
**Describe what you would like changed, and why.**

Currently overdrive only boosts the pulling speed and not damage/range, would be nice if range could be boosted.

**Describe the changes you want to propose. Include possible alternatives.**

The code does reference a liquid boost option but enabling that would break existing saves, or maybe even item based??

**Comment by joshuaptfan** [comment]
Overdrive doesn't boost the range of any other block, nor is that its stated function.

The only thing that somewhat fits current patterns is an item-based boost, but no other turrets can be item boosted for range, only menders and overdrives.

**Comment by SheepCommander** [comment]
.-.

**Comment by Humanoid-X** [comment]
increase  dammage = yes
increase range = no

**Comment by liuxilu** [comment]
We may have two new building: overhurter, overranger.

**Comment by kapzduke** [comment]
it should increase damage instead and drag strength instead
