### ISSUE TITLE
Access to previous versions

### ISSUE THREAD

**Issue by notMEEPoffaith** [Anuken/Mindustry-Suggestions#1989]
**Describe the content or mechanics you are proposing.**
Basically what this would do is it would be a setting in the settings in Game Data that allows you to switch between older versions and the current version. Each different version would have it's own different saves.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think it would be benificial to new players who have only experienced v6.0 and higher, so they can experience more and so that everyone could experience the game's past.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
You (hopefully accidentally) duplicated #1988. I'm pretty sure you're not a spambot...

**Comment by Cherriodude** [comment]
Just download older versions.

**Comment by DeltaNedas** [comment]
just download older versions

**Comment by shugen002** [comment]
maybe we should ask for a start option to specify data location instead of just hardcode to save in user data folder ( or just next to client in steam version)

**Comment by BlueWolf3682** [comment]
it says in the README.md where you can find older builds

**Comment by WinterCrystal** [comment]
Just download the other versions. Making this as feature feels like a waste of time when you just do the former.

**Comment by SheepCommander** [comment]
Close this: You already have access to older versions and it doesn't make sense to add it as an ingame feature.

**Comment by XxsuperdeadlysniperxX** [comment]
And no one boths to look if others said to _"just dowload the older versions"_

**Comment by XxsuperdeadlysniperxX** [comment]
Also older versions are hard to dowload on mobile cuz of the file type of the older files

**Comment by XxsuperdeadlysniperxX** [comment]
> it says in the README.md where you can find older builds

The read.me doesn't tell anyone anything about where to _find_ the older versions just saying

_**please look before you type info that doesn't exist in this repo**_

**Comment by notMEEPoffaith** [comment]
> You (hopefully accidentally) duplicated #1988. I'm pretty sure you're not a spambot, but this is not a good first sign.

i forgot to fill the boxes
