### ISSUE TITLE
Improve Surge Wall

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#199]
**Describe what you would like changed, and why.**
Surge Wall, despite being the strongest wall in the game health-wise, has probably the worst ability of any of the walls. It's current ability is to spawn a 15 damage lightning at a 5% chance when hit.

**Describe the changes you want to propose. Include possible alternatives.**
My idea is to make surge wall very useful for defenses, one of the most powerful things in the game is laser cannons (lancer, meltdown), due to nothing being able to stop the laser due to it's penetration. What I think Surge Walls should be changed to do (or just have this added to them), is the ability to block a laser hitting it and prevent it from hitting anything behind it as well. Despite their current ability also needing a buff, an ability like this would make them interesting to use for reasons other then health, especially in PvP against enemy lancer spam, or for mapmakers developing PvE maps.

**Comment by potatoisagender** [comment]
i think that this functionality is better suited for plast walls

**Comment by ritzip** [comment]
Indeed, *Plastanium walls' high heat resistance rendered lancer laser useless!*.

**Comment by Syncinus** [comment]
It would be interesting on plast walls (I was originally thinking to put it there), but they are already super useful, Surge walls less so.

**Comment by ritzip** [comment]
Surge walls already take forever to destroy.

**Comment by Anuken** [comment]
As mentioned above, surge walls already have the most health, and can deal (lethal) damage to enemies. Absorption isn't really their thing.

Implemented for lancer-type lasers. Meltdowns don't/won't have this yet, as they use a different type of laser. I don't think blocks even *should* shield from meltdown lasers (why would you place a wall near an enemy meltdown at all? block-to-block combat doesn't happen very often)

![2020-06-06 14-33-55](https://user-images.githubusercontent.com/10100000/83951928-2fe31180-a803-11ea-8789-2cb4ad0b0171.gif)

**Comment by Syncinus** [comment]
Nice!
