### ISSUE TITLE
Separator building costs

### ISSUE THREAD

**Issue by MitjaCernko** [Anuken/Mindustry-Suggestions#1990]
**Describe what you would like changed, and why.**
The requirement of titanium to build a Separator - that prevents late-game access to titanium on maps without mineable sources.

**Describe the changes you want to propose. Include possible alternatives.**
Replace titanium as a required building material with a resource available anywhere (e.g. graphite and / or silicon).

**Comment by DeltaNedas** [comment]
or you could use lunchpad to send titanium into a barren sector...

**Comment by MitjaCernko** [comment]
Whoops, already see the open issue :)
I know - forgot to include it again, it's getting annoying...

Will form a habit of including some in the beginning :)
