### ISSUE TITLE
Option to core to not incinerate things in the campaing

### ISSUE THREAD

**Issue by PolloUsami** [Anuken/Mindustry-Suggestions#1991]
**Describe the content or mechanics you are proposing.**
In the game options add a option that the core in campaing do not incinerate the materials

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
For example a sector that i have totaly industrialised when the resourses are full they go with overflow gates to launchpads instead of being incinerated

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
use anuke logic

**Comment by PolloUsami** [comment]
i know that exist logic, but for laziness?

**Comment by joshuaptfan** [comment]
Core incineration was introduced _so that the v6 campaign resource system could function._ It is not optional.

The v6 campaign resource system relies on items input into the core per second (capped by production so you can't just fill vaults and unload into the core to cheat). Without core incineration, when your core is full, items would stop entering the core, dropping your items/sec to zero, thus breaking sector stats.

**Comment by PolloUsami** [comment]
oh
