### ISSUE TITLE
Upgrading processors keeps their code

### ISSUE THREAD

**Issue by marky0470** [Anuken/Mindustry-Suggestions#1992]
**Describe the content or mechanics you are proposing.**
Be able to upgrade processors into higher tiers similar to how drills and cores are upgraded, but the processor that was upgraded keeps the code and links inside of it.

If building over a cluster of processors, keep only the code of the processor being clicked on when constructing.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Small quality of life change, I find myself having to copy code to clipboard, delete the processor, place a new one and input from clipboard. I believe the reason those 2 buttons (copy to, import from) were added was for these situations but I think this is an easier alternative.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why on earth would you even want to run code from a lower tier processor on a higher tier one?

**Comment by Axzye** [comment]
Same reasons high tier processors exist in the first place...

**Comment by marky0470** [comment]
> Why on earth would you even want to run code from a lower tier processor on a higher tier one?

If I wanted to assign more turrets/units to control which I previously opted to control with a small processor because it's cheap

**Comment by marky0470** [comment]
>Same reasons high tier processors exist in the first place...

Second tier processors require thorium, and logic in general is already useful before thorium so I tend to set up processors early in game

**Comment by marky0470** [comment]
Oh sorry Axzye I might have misread your comment, I thought you meant to just use higher tier processors

**Comment by DeltaNedas** [comment]
1. copy code
2. rebuild
3. paste

how hard is this?

**Comment by itcannotbe** [comment]
Also letting processors be "upgraded" is a nuisance, since anything that is still upgrading does not work.

So yeah. unbind everything.

**Comment by Thankyou69** [comment]
how about also saving their code when partially deconstructed sort of like how block keep the damage done to them when partially deconstructed

**Comment by marky0470** [comment]
> So yeah, everything unbinds anyway.

And rebinds right after, the only scenario I believe this would not work is when there is code that is specifically meant to only run once, like flagging units with a player-designated, persistent flag such that if 2 processors did the same thing (which would happen if microprocessor flagged say n units and logic processor did the same after being constructed, leaving you with twice as many units flagged.)

**Comment by marky0470** [comment]
> how about also saving their code when partially deconstructed sort of like how block keep the damage done to them when partially deconstructed

That's a good idea as well, It could be a quick way to reset/disable a processor by deconstructing it but not fully, assuming you are saying that processors only keep the code but don't execute them while being deconstructed.

**Comment by SheepCommander** [comment]
It's a perfectly fine small quality of life change. @DeltaNedas sure you can copy and paste but the entire point as stated was "Small quality of life change"

I also don't understand @itcannotbe it's your decision to upgrade if you want to
