### ISSUE TITLE
Fortresses follow too closely

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1993]
**Describe what you would like changed, and why.**
When you walk up to a bunch of units and press G (or whatever your keybind is) the units form around you in a circle and follow you everywhere. The problem with fortresses is that they follow too tightly. This causes you to constantly bump into them as you walk making travel difficult. This isn't an issue with other units. Some flying units have this issue but it's mitigated because they can fly and have higher speed so it's very easy to stop bumping into them. Fortresses are slow and follow too tightly. Moving with them is tough.

**Describe the changes you want to propose. Include possible alternatives.**
Extend the range at which fortresses form around players that command them.  Expand the radius at which fortresses surround the player.

I have read the trello and the blah blah all of that stuff.

**Comment by SheepCommander** [comment]
I haven't commanded fortresses personally but makes sense, tho you don't have to delete the last part of the template just put in the x'es

**Comment by XxsuperdeadlysniperxX** [comment]
@RedstonerKBC anuke will not look at a suggestion if the template is invaild

Also theres a thing called ucontrol approach

**Comment by Kyllingene** [comment]
I love it when people get mad at other people for not including boxes
***when the template used doesn't have them***
check the tag

and no, uncontrol makes no sense for something this small. Is changing one value for one case really that all-fired hard?

**Comment by XxsuperdeadlysniperxX** [comment]
oH crap didn't check the tag again 🙃

**Comment by XxsuperdeadlysniperxX** [comment]
> I love it when people get mad at other people for not including boxes
> ***when the template used doesn't have them***

I got confused cuz i can't keep track of all the suggestions i look at so it gets easy to mistaken one issue for another oop

**Comment by XxsuperdeadlysniperxX** [comment]
>and no, uncontrol makes no sense for something this small. Is changing one value for one case really that all-fired hard?

@Kyllingene _what do you mean by **uncontrol**_
Ucontrol is unit control which has move and approach instructions 
Move: moves the unit to a specific location with no radius

Approach: units will _approach_ the coordinates aka like move but with a radius

_unless_ @RedstonerKBC you mean like the unit hire function (creates a ring that tells units to follow you in a set radius depending on how many units you have that will shoot where you tap/click and the units will look at the cursor)

**Comment by Kyllingene** [comment]
I meant "ucontrol approach" (your own term for it)

**Comment by XxsuperdeadlysniperxX** [comment]
Its not my _own_ term as it is already formatted this way

ucontrol approach 0 0 0 0 0

**Comment by XxsuperdeadlysniperxX** [comment]
Move is more precise because it puts the unit right on top of the exact coordinates that is set

Approach is the same as move but you can set the radius which will put the units around the exact coordinates

I use these a lot in schematics so i know how they work

Move is better for single units tho

**Comment by Kyllingene** [comment]
What I meant is that ucontrol in any form (although the topic of discussion was indeed ucontrol approach) is not a suitable fix, as it is a huge bit of logic in place of small tweak of a value to make controlling Fortresses actually feasible.

**Comment by XxsuperdeadlysniperxX** [comment]
You have a point but _why use fortresses in logic?_

**Comment by Kyllingene** [comment]
What do you mean? What I am saying is that there are two current options: a workaround and a fix.
The workaround is some large, complicated, unwieldy logic to make an incredibly simple change to current behavior.
The fix is a tiny tweak in the code.
The need for change is that Fortresses are a useful, long-range unit, and thus controlling them is a good strategy.
Therefore, I am concluding that the fix is warranted, as it is a nearly effortless change for a huge benefit to the game.

I have no clue what you mean by using "fortresses in logic".

**Comment by RedstonerKBC** [comment]
Edited the post for clarification

I'm not talking about logic blocks. I'm talking about commanding fortresses, like when you press G (or whatever your keybind is) and 6-10 units form around you in a circle. This formation for fortresses is too tight which means when you move you bump into them.

Sorry about the template. I might've acidentally deleted or something but if it was there I would've checked all of the checkboxes. I did indeed do all of the searches so if I accidentally missed something sorry.
