### ISSUE TITLE
Disable minimap

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#1994]
**Describe the content or mechanics you are proposing.**
option 1: new rule in rules.java option to disable minimap
option2: on map settings

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
:)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by unjown** [comment]
btw sry wrong title 

option to disable

**Comment by GreyMario** [comment]
No.

You didn't even try to begin to defend such a ridiculous suggestion, and nothing will stop people from using the pan view features.

**Comment by itcannotbe** [comment]
FOW is a better suggestion than this.

**Comment by itcannotbe** [comment]
> btw sry wrong title
> 
> option to disable

Y   o   u         c   a   n         e   d   i   t         t   h   e         t   i   t   l   e         i   f         y   o   u         w   a   n   t         t   o   .

**Comment by DeltaNedas** [comment]
why?

**Comment by Yell245** [comment]
> why?

To prevent the player from spying their enemy ig

**Comment by XEN0PHIL** [comment]
> To prevent the player from spying their enemy ig

I was going to ask if you are making a hide&seek game mode but now I see how dumb the suggestion is.
As GreyMario mentioned above, it won't stop people from using the flying camera or just flying into the enemy base for sucide-scouting.
Search for "fog of war" in closed PRs and read the comments

**Comment by WinterCrystal** [comment]
> > why?
> 
> To prevent the player from spying their enemy ig

Pan view exists, and there are people that use it.

**Comment by SheepCommander** [comment]
Close this
