### ISSUE TITLE
Asteroid belts/fields 

### ISSUE THREAD

**Issue by AureusStratus** [Anuken/Mindustry-Suggestions#1996]
As you know v7 will bring in planets and stuff and a cool features would be between some planets or around them would be asteroid fields/belts

In game right now we have the new space titles and they dont generate in the campaign and have to be drawn in the map creator
and sense v7 will add in new planet in to the campaign a fun little side side is that you can explore asteroid belts/fields in between planets the way the asteroids generate could maybe be from big large islands to little island scattered all around 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
#1700 #825

**Comment by XxsuperdeadlysniperxX** [comment]
Also template was killed
