### ISSUE TITLE
Unit opacity setting

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#1997]
it's a simple thing, but it would be very useful.  I think the details will be superfluous

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
P L E A S E I N C L U D E T H E T E M P L A T E

**Comment by Humanoid-X** [comment]
- [x] I treated the template as nonexsistent, and deleted it entirely, and because of that I did not do a quick search in the list of open and closed suggestions and made Anuke and all his contributors angry.

**Comment by unjown** [comment]
https://github.com/blahblahbloopster/mindustry-client-v6

solution

**Comment by liuxilu** [comment]
already exist/release soon (I forget)

**Comment by liuxilu** [comment]
No, it didn't.

**Comment by genNAowl** [comment]
There was a PR for this in the past: https://github.com/Anuken/Mindustry/pull/2034
