### ISSUE TITLE
Allow processors to determine if a player is pressing a certain key

### ISSUE THREAD

**Issue by marky0470** [Anuken/Mindustry-Suggestions#1998]
**Describe the content or mechanics you are proposing.**
It would be nice to be able to check if a player is pressing a certain key, not just keys used by the game's controls but at least all the letters.

A suggestion on how it would work, would be a new code block which returns to a variable either `true` or `false` and has 2 parameters: `unit` dictates which unit to check for a key press and `key` would be the key to check.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would allow for player-controlled systems, I can see this being useful in commanding units since uradar is capable of assigning the player to a variable.  Unit behaviors can be changed easily even if the player is not within range of the processor to toggle switches.
I understand however that this may leave mobile users out and am open to ideas.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
is every client supposed to send key presses to the server?

**Comment by GreyMario** [comment]
Mobile users:

**Comment by itcannotbe** [comment]
> is every client supposed to send key presses to the server?

Mindustry Keyloggers go brrrrrrrrrrr.

**Comment by RedstonerKBC** [comment]
People complain about malware and stuff but when it comes to Google, Facebook, Tiktok and other big tech oh no you can keylog me all you want baby!

**Comment by Kyllingene** [comment]
> Mobile users:

"I understand however that this may leave mobile users out and am open to ideas."

> is every client supposed to send key presses to the server?

mmm fun yummy ping

> People complain about malware and stuff but when it comes to Google, Facebook, Tiktok and other big tech oh no you can keylog me all you want baby!

somewhat off-topic ngl but agreed
