### ISSUE TITLE
New sprite for Poly

### ISSUE THREAD

**Issue by kapzduke** [Anuken/Mindustry-Suggestions#1999]
**Describe the content or mechanics you are proposing.**
update poly's sprite to abide by the unit sprite shading rule. here's a concept by me.
![3857250639395961856](https://user-images.githubusercontent.com/60543005/108527999-9baad300-72db-11eb-8e6a-503fea0cabe8.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
i think it would make poly fit better among the other units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by iLagSoUhax** [comment]
you could have just made a pr adding this, you know.
