### ISSUE TITLE
Mech name

### ISSUE THREAD

**Issue by KK6DOC** [Anuken/Mindustry-Suggestions#2]
**Describe the content or mechanics you are proposing.** 

I was looking through Trello and under 6.0 was new mech roles I took a quick read(as you would do every so often) and noticed that you have a blank under artillery mech. So it though of ideas for a mech but was only able to come up with a name "Hammer"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I don't have a clue how this would improve the game but hopefully you create new mechs in the future as the game is kinda blanking there. 

(This was partially a test for how the new suggestion system will work on github since feathub us dead now)

**Comment by DeltaNedas** [comment]
i like it

**Comment by Falling10fruit** [comment]
Nice name, Hammer.
