### ISSUE TITLE
Messages in message blocks should be saved and restored from blueprints

### ISSUE THREAD

**Issue by deee167** [Anuken/Mindustry-Suggestions#20]
Messages in message blocks should be saved and restored from blueprints because it's useful to store information about a blueprint and read that as a refresher when restoring the blueprint.  Eg. here are the inputs, the following inputs are needed.  This produces x amount of stuff every minute etc.

**Comment by piyushak10** [comment]
Agreed... was about to write this suggestion myself, but it seems you beat me to it hehe...

**Comment by Anuken** [comment]
Implemented in 6.0.
