### ISSUE TITLE
issue 2000

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2000]
yes

**Comment by QmelZ** [comment]
amazing

**Comment by Cherriodude** [comment]
Too late...

**Comment by XEN0PHIL** [comment]
you forgot surgio brijes

**Comment by GreyMario** [comment]
don't forget to claim your Banned From Repo badge on the way out

**Comment by kapzduke** [comment]
at least i made ur day

**Comment by DeltaNedas** [comment]
the idea that ilya244 would be banned before you is ridiculous

**Comment by GreyMario** [comment]
sweetie you have literally no place to talk on that front

**Comment by Bohaska** [comment]
> don't forget to claim your Banned From Repo badge on the way out

As you know, only Anuke can give out Banned From Repo badges, and he doesn't give them out for no reason.
