### ISSUE TITLE
Make oct's item capacity higher than 250.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#2001]
**Describe the content or mechanics you are proposing.**

Increase the oct's item capacity to something close to 1000.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Since the oct is almost like a huge ship for other units to by carried by, I think oct should also be able to hold more items that it already can. 250 seems too small for such a huge ship and it can be useful to carry high amounts of items around the map especially with logic. It also gives oct one more usage because it is a strictly supportive unit rather than offensive.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WinterCrystal** [comment]
> Since the oct is almost like a huge ship for other units to by carried by, I think oct should also be able to hold more items that it already can. 250 seems too small for such a huge ship and it can be useful to carry high amounts of items around the map especially with logic. It also gives oct one more usage because it is a strictly supportive unit rather than offensive..

There is a block called Vault that can store 1k items of any kind. The Oct can transport them easily, try that.

**Comment by itcannotbe** [comment]
More like 1k of each item.....

**Comment by the-kido** [comment]
> There is a block called Vault that can store 1k items of any kind. The Oct can transport them easily via airlift, try that.

Oh, that just destroys this entire suggestion. Thank you and sorry.

**Comment by Thankyou69** [comment]
> > Since the oct is almost like a huge ship for other units to by carried by, I think oct should also be able to hold more items that it already can. 250 seems too small for such a huge ship and it can be useful to carry high amounts of items around the map especially with logic. It also gives oct one more usage because it is a strictly supportive unit rather than offensive..
> 
> There is a block called Vault that can store 1k items of any kind. The Oct can transport them easily via airlift, try that.

hard to automate tho...

**Comment by itcannotbe** [comment]
Well basically your a noob for not even trying to do it. It's actually easy enough.

Especially if you're the person who actually makes logic from scratch.

**Comment by Kyllingene** [comment]
Mmm, two things:
1. fun name calling
2. it is hard for a fair few people, not that that negates this but it is still true

**Comment by itcannotbe** [comment]
You forgot that logic isn't supposed to be for beginners mind you.

Also he mentioned trying to automate it.
So how are tou going to automate it without the use of logic?

**Comment by itcannotbe** [comment]
Also as soon as paytake and paydrop were a thing with mlog, people have already showcased picking up containers and dropping them systematically.

Surely it's not hard to adapt that code.

**Comment by Thankyou69** [comment]
> Also as soon as paytake and paydrop were a thing with mlog, people have already showcased picking up containers and dropping them systematically. Surely it's not hard to adapt that code.

ok dude, first of all, chill, ur on every suggestion and you have never made a nice comment, second, i have tried to automate it, i do believe it is possible, but it only really works with one or two octs to get the placement correct (ie. they bump into eachother and push eachother away. also, yes, i make all my logic and schematics from scratch, i think it will help me improve if i dont spam other peoples designs and make my own.

**Comment by itcannotbe** [comment]
Atleast you're trying.
You could make use of uradar to check if other octs are in the pick up and drop of area before issuing a move command to proceed with the paytake/paydrop.
