### ISSUE TITLE
Increase water extractor energy consumption

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2003]
**Describe what you would like changed, and why.**
90 energy -> 150 energy
Previous nerf wasn't sufficient enough in my opinion. 

**Describe the changes you want to propose. Include possible alternatives.**
This will make steam gen setups with water extractors much less viable. 
Also this will force players to use diffirential generator asap for greater outcome (as it needs only 0.5 water ex).

**Comment by joshuaptfan** [comment]
Duplicate of #1402.

**Comment by itcannotbe** [comment]
> Duplicate of #1402, which was also created by you.

Well no. Previously water extractors used less power then nerfed to 90. Now he'e suggesting to increase it to 150.

**Comment by GreyMario** [comment]
Duplicate of #1402, which we already shit on thoroughly enough that you never should have considered opening another thread about it.

**Comment by itcannotbe** [comment]
> Duplicate of #1402, which we already shit on thoroughly enough that you never should have considered opening another thread about it.

It's not a duplicate since what's currently in the game is different from the time of the previous suggestion.

That's how balancing works.

**Comment by Slava0135** [comment]
> > Duplicate of #1402, which was also created by you.
> 
> Well no. Previously water extractors used 60 power then nerfed to 90. Now he'e suggesting to increase it to 150.

*yes*

**Comment by joshuaptfan** [comment]
> Well no. Previously water extractors used 60 power then nerfed to 90. Now he'e suggesting to increase it to 150.

Quote from Slava in #1402:
> Make water extractor use 150 energy / sec.

**Comment by Slava0135** [comment]
Technically consumption was increased from 60 to 90 and it's almost had no effect on players that's why I propose the change again.

**Comment by itcannotbe** [comment]
> > Well no. Previously water extractors used 60 power then nerfed to 90. Now he'e suggesting to increase it to 150.
> 
> Quote from Slava in #1402:
> 
> > Make water extractor use 150 energy / sec.

But water extractors then were using 60 energy per second.
Now it's using 90 energy per second.

Balancing is not a one time thing when when you change something to nerf or buff something it permanent.

Balancing is where you see how something is used in the current state of the game then change stuff to balance it.

So no. Not a duplicate.

**Comment by Slava0135** [comment]
It's been an ages ago and it's irrelevant

**Comment by Slava0135** [comment]
I want to keep things fresh and try different parameters to find the optimal point. I believe Anuke is neither happy with the current water extractor state.

**Comment by WinterCrystal** [comment]
>I believe Anuke is neither happy with the current water extractor state.

And you nerfing the Water Extractor even further by letting it use more power won't help either. The drill already has an awful water output that is just enough to supply a single drill of any kind with the exception of the Oil Extractor and single Steam Generator. The differential generator is cumbersome to setup without using any schematic, and Anuke intended for the Steam Generator to be an early game way of getting any meaningful power output. At this point, we might as well not have the Water Extractor at all.

**Comment by itcannotbe** [comment]
Water extractors aren't even supposed to be early game accessible.

**Comment by itcannotbe** [comment]
There is a thing called pumps. Use them.

**Comment by nichrosia** [comment]
> Water extractors aren't even supposed to be early game accessible.

Exactly. You need to beat Salt Flats, a sector that lacks water. Water extractors are meant to be used as a last resort, rather than just a more convenient block at the cost of much more power.

**Comment by Kyllingene** [comment]
> At this point, we might as well not have the Water Extractor at all.

Ah yes, the most reasonable argument: eliminate tons of compact schems and invalidate *tons* of low- or no-water maps. Best idea ever.

**Comment by Slava0135** [comment]
> > At this point, we might as well not have the Water Extractor at all.
> 
> Ah yes, the most reasonable argument: eliminate tons of compact schems and invalidate _tons_ of low- or no-water maps so that a few people don't hurt themselves. Best idea ever.

Compact schematics with water extractors and drills should cease to exist

**Comment by Kyllingene** [comment]
Why? Either water extractors are the only option (so don't remove them), or they are inefficient, in which case they are hurting themselves. Also, there are more schems than just drill schems. Ever heard of this magical thing called *cryofluid*? Yeah, it's used in a lot of *compact schems*.

**Comment by Slava0135** [comment]
> Why? Either water extractors are the only option (so don't remove them), or they are inefficient, in which case they are hurting themselves. Also, there are more schems than just drill schems. Ever heard of this magical thing called _cryofluid_? Yeah, it's used in a lot of _compact schems_.

 Why not use conduits and place water extractors out of schematic utself

**Comment by Kyllingene** [comment]
*But you wanted to remove water extractors*

**Comment by Slava0135** [comment]
I just want to make people use conduits and pumps. If water extractors won't be able to be used inside of schematics people would look for water sources.

**Comment by Kyllingene** [comment]
So you propose adding tons of code (which seriously harms tons of actually good players) to avoid people from hindering themselves?

**Comment by Slava0135** [comment]
> So you propose adding tons of code (which seriously harms tons of actually good players) to avoid people from hindering themselves?

What code

**Comment by Kyllingene** [comment]
The code that prevents specific blocks from getting copied...

**Comment by Slava0135** [comment]
I didn't mean "ban water extractors from schematics" but make players prefer conduit systems over them. If you look on schematics like >90% of them contain water extractors as water source.

**Comment by Kyllingene** [comment]
And how would you propose doing that? Your power debuff got shot down:
> And you nerfing the Water Extractor even further by letting it use more power won't help either.

**Comment by TheNightglow** [comment]
I think the problem here is rather that a water extractor is so much more convenient than building a pipeline system, that no matter the power consumption or water output, its always the best option...

a way to help here would be to make water pumps more convenient to use:
- autobuild bridges when dragging a water pipe over a conveyor

a small change like that would make building pumps much more viable.... right now its just too annoying to keep switching between conduit and bridge in the building menu, considering the alternative is building a single structure (extractor) where it is needed

**Comment by itcannotbe** [comment]
> I think the problem here is rather that a water extractor is so much more convenient than building a pipeline system, that no matter the power consumption or water output, its always the best option...
> 
> a way to help here would be to make water pumps more convenient to use:
> 
>     * autobuild bridges when dragging a water pipe over a conveyor (similar to junctions being auto selected)
> 
> 
> a small change like that would make building pumps much more viable.... right now its just too annoying to keep switching between conduit and bridge in the building menu, considering the alternative is building a single structure (extractor) where it is needed

You could try that, but as a matter of fact,  water extractors are extremely convenient to use. Only more restrictive placement conditions would counter this. But a power consumption nerf would affect the worst offenders.

**Comment by Bohaska** [comment]
I have to say, @Slava0135 has a knack of getting tons of replies to his suggestions.

**Comment by WinterCrystal** [comment]
> I have to say, @Slava0135 has a knack of getting tons of replies to his suggestions.

@Bohaska Well, he does make suggestions to change something that doesn't suit to his taste just because of their convenience, and sometimes suggests things that outright shouldn't be suggested at all, and would just result into giving other players an unfair advantage just because some guy isn't happy of what something is capable of. Few infamous examples are: #1541 and #1856

**Comment by itcannotbe** [comment]
TBH, Undeniably the water extrsctor is notoriously overpower because of its portability and ease of use. so it does make sense that it got multiple debuffs since it was introduced.
