### ISSUE TITLE
Make water extractors require metaglass

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2006]
**Describe what you would like changed, and why.**
35 copper, 35 lead, 35 graphite -> 35 metaglass, 35 lead, 35 graphite.
This makes metaglass more valuable.

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by itcannotbe** [comment]
Is this #1712 ?

**Comment by Slava0135** [comment]
> Is this #1712 ?

oh no

**Comment by joshuaptfan** [comment]
Please consolidate your water extractor suggestions into one of your existing water extractor suggestion issues instead of creating new water extractor suggestion issues.

**Comment by itcannotbe** [comment]
> Please consolidate your water extractor suggestions into one of the existing water extractor suggestion issues instead of creating new water extractor suggestion issues.
> 
> Duplicates are bad, m'kay.

But it's not disallowed by the template. XD.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1712#issuecomment-782817639

If anyone disagrees with the balancing suggestion, kindly read the thread in the previous issue, before commenting.

**Comment by Quezler** [comment]
you can close this now, it happened.
