### ISSUE TITLE
Schematics and phantoms

### ISSUE THREAD

**Issue by ritzip** [Anuken/Mindustry-Suggestions#201]
*Schematics, while useful they are too overused.*

Limit schematics to phantoms. This may seem like a bad thing but it would make phantoms more useful.

Early-game would be more tedious, but it really should be slow.

**Comment by zethnest** [comment]
Implementing this would require to most likely recode the Schematic system

**Comment by ritzip** [comment]
Who knows 🤷

**Comment by itcannotbe** [comment]
Maybe if making phanthoms would be also a chore that would be nice.

**Comment by zethnest** [comment]
This suggestion is mostly targeted to combat mass copy-pasting schematics. 
Honestly I don't think schematic copy-pasting is a bad thing.

**Comment by itcannotbe** [comment]
Not when people started pasting schematics during second 0 of the map.

**Comment by itcannotbe** [comment]
Also what if schematics aren't block per block, but it's an area which combines all block requirement and build time?

That would be more challenging.

**Comment by Anuken** [comment]
Nah.
