### ISSUE TITLE
Damage type tutorial

### ISSUE THREAD

**Issue by snakefangz** [Anuken/Mindustry-Suggestions#2010]
Hey man your game is fucking epic, i was wondering if maybe you could teach the player through the hint window perhaps, about guardians and damage types? Died twice to realise i had the wrong type of turrets, also, why do on some maps air units spawn way out in the map instead of the spawn?

**Comment by itcannotbe** [comment]
Tutorial mentioning block info/core database should actually suffice but the thing is, people won't bother checking it out, also I think if this gets implemented it won't have an impact because people who won't bother checking block info, wouldn't be bothered to play read text/hints that the tutorial provides.

Also you murdered the template

Also also this belongs to feature suggestions.

**Comment by Kyllingene** [comment]
Mmm, I disagree. Evidently, this person read the tutorial but not the core database, and I also don't think this is a feature request as it is simply a small change to a preexisting thing.

**Comment by snakefangz** [comment]
I dont understand, what am i supposed to see in the database?

**Comment by Kyllingene** [comment]
Each turrets entry tells you what types of troops (ground, which includes naval, and air)

**Comment by snakefangz** [comment]
Oh yes i know that but what does that have to do with my original post? Im not sure if i understand

**Comment by Kyllingene** [comment]
[#2010 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/2010#issuecomment-782849882)
> Tutorial mentioning block info/core database should actually suffice but the thing is,

**Comment by snakefangz** [comment]
What about flying enemies sometimes spawning way out of the spawn? Is it a bug?

**Comment by Kyllingene** [comment]
To be quite honest, that I have no clue about. It seems like sometimes they spawn relative to the core in some way, but who knows.

**Comment by snakefangz** [comment]
Hmm ty for responding

**Comment by genNAowl** [comment]
> What about flying enemies sometimes spawning way out of the spawn

It's not a bug, it's intentional. By what I can tell, Air Units will always spawn in the closes corner to each spawn. I do not know why Anuke made it this way though.

**Comment by itcannotbe** [comment]
> What about flying enemies sometimes spawning way out of the spawn? Is it a bug?

https://github.com/Anuken/Mindustry/issues/1729
