### ISSUE TITLE
ability to make blueprints of construction blocks

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#2011]
**Describe what you would like changed, and why.**

currently you can only select built blocks for schematics, which makes it impossible to come up with something new and copy/paste it with `F` without having to put every possible combination in a schematic first.

**Describe the changes you want to propose. Include possible alternatives.**

for example, here if you place 4 drills you can't copy paste it beyond the water to form 8, and you also can't copy paste the entire row up or down without waiting for all of them to be constructed to completion:

![Screen Shot 2021-02-21 at 15 57 45](https://user-images.githubusercontent.com/3179271/108628908-9d040900-745d-11eb-9662-b1f951ee5051.png)

**Comment by itcannotbe** [comment]
Griefing potential detected.

**Comment by Quezler** [comment]
security through obscurity.

**Comment by itcannotbe** [comment]
The only way this won't be use like that is for shematics, in general, to be able to be overwritten. Like a blueprint instead of a build queue.

**Comment by Catchears** [comment]
https://github.com/Anuken/Mindustry/commit/61d9dea487f9cd4c1e271528c54c4028bb372682

I'm guessing "Copy-able ConstructBlocks" means this was implemented?

**Comment by Quezler** [comment]
i guess so
