### ISSUE TITLE
Vela balancing solution

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2015]
**Describe what you would like changed, and why.**
As a result of a discussion in #balancing, we figured that this solution would work. ( https://discord.com/channels/391020510269669376/813425645518061678/813429063938736128 )

**Describe the changes you want to propose. Include possible alternatives.**
1. Add an onboard ammo factory to Vela
2. Add unit healing beams to Vela's body
3. Add a shield ability to Vela
4. Make Vela be able to build
5. Nerf Vela's current stats further

**Comment by Humanoid-X** [comment]
mine thorium = good

**Comment by kapzduke** [comment]
>thorium near core
 
vela time
