### ISSUE TITLE
bring back being able to edit unit health in maps

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#2016]
**Describe what you would like changed, and why.**
bring back being able to edit unit health in map editor

**Describe the changes you want to propose. Include possible alternatives.**
i see no alternative expect war

**Comment by CountSudokku** [comment]
As i remember units health in custom game was removed because it wasn't working right. Units still needed to take same amount of dmg.

**Comment by QmelZ** [comment]
it did work though, and i'd like a similar feature in v6.

**Comment by joshuaptfan** [comment]
For reference, it was removed in [this commit](https://github.com/Anuken/Mindustry/commit/75d2b0fb69317ab0197c72fdb137c7d7f1a32f27). I don't know why.

**Comment by itcannotbe** [comment]
#1853 be like.....
