### ISSUE TITLE
Zoom function for mlog script view

### ISSUE THREAD

**Issue by Philosophist** [Anuken/Mindustry-Suggestions#2017]
**Describe the content or mechanics you are proposing.**
In the mlog script editing view that we get when we are giving instructions to a processor, I would like a zoom function so that I can zoom out for a wider view of my overall code

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The current editor is excellent so far in how it helps the user to visualize their code with coloration that is intuitive and jump arrows which are also intuitive. The only trouble is not being able to zoom out far enough to view all of the arrows and their destinations. If we could simply hold ctrl and move the mouse wheel to zoom out, there would be even better user friendliness to that page for scripting.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
#1663 is related, the whole issue is how to see where jump arrows are going when they are going off-screen.

**Comment by Philosophist** [comment]
> 
> 
> #1663 is related, the whole issue is how to see where jump arrows are going when they are pointing off-screen.

Indeed.  Another feature which would help but would be a lot more work would be to make the editor a jigsaw style editor like MIT's scratch. I feel this will be inevitable when this project reaches a Minecraft level explosion in popularity due to these logic features. I can't wait to see competitions of real time strategy games played out as a programming/hacking battle.
