### ISSUE TITLE
Nerf nova, pulsar and quasar, and buff they dagger tree counterparts

### ISSUE THREAD

**Issue by bloool** [Anuken/Mindustry-Suggestions#2018]
**Describe what you would like changed, and why.**
Nerf them. Why? Nova tree is just so much better until T4, so here's a comparison of their pros and cons:

**Nova**:
- Can shoot from incredible ranges using logic;
- Can boost over defenses;
- Has AOE regen ability;
- Has a bit fewer dps than a dagger;
- Costs titanium to 

**Pulsar**:
- More range than mace;
- Can command more units;
- Boost;
- Will regenerate a shield for ANY close unit, even tiers above him;
Shoots electricity arcs that pierce and you have no way of defending against it at that point of the game;
Less overall dps, but when you consider the longer range and more command, all of the units commanded can hit the target, different from mace where only the front ones can actually hit, and you can boost over the defenses and only target things like conveyors or power nodes that have low health and can make a whole defense useless when destroyed;

**Quasar**:
- Less range than fortress by about 7 blocks;
- Can command more units;
- Boost;
- Force field that regen and is also affected by Pulsar's shield regen ability;
- Shoots laser that like Pulsar, you have no way to defend at that point and that also follow a predictable path;
- Fewer dps than Fortress, but the pierce makes up for it because it can hit multiple blocks, Fortress also can but the splash damage the bullets don't seem to deal full damage apart from Quasar. And same deal with Pulsar, can just fly over and focus on weaker more crucial blocks, or just downright ignore everything and just fly through it, the force field has enough health to tank a lot of scatter shots, and will regen after anyway;

And also, Pulsar and Quasar shots can't be hit by segments, I didn't consider that because at that point of the game the enemy wouldn't be able to make them yet, but if you plan to make T3 a bit more later then that's another pro.

**Describe the changes you want to propose. Include possible alternatives.**
I think a possible (or even better) alternative could be to just buff the dagger tree to make it match nova's since people usually prefer and would be happier with a buff to a weak unit, than to a nerf to a strong one;

**Comment by Kyllingene** [comment]
I think that the Dagger line of units is *supposed* to be weaker, sort of swarm-like. They a cheap and easy to produce and you can produce many. Buffing the Dagger line could prove disastrous, and you have also failed to propose any possible nerfs/buffs.

**Comment by bloool** [comment]
> I think that the Dagger line of units is _supposed_ to be weaker, sort of swarm-like. They a cheap and easy to produce and you can produce many. Buffing the Dagger line could prove disastrous, and you have also failed to propose any possible nerfs/buffs.

yeah but novas aren't really that much harder to produce than daggers, only need a bit of titanium, which in itself doesn't need too much work to get

**Comment by Kyllingene** [comment]
10 silicon + 10 lead + 15 seconds
vs.
30 silicon + 20 lead + 10 titanium + **40 seconds**

It is quite clear that Nova's are the more expensive, heavy-duty unit.

**Comment by CountSudokku** [comment]
Actually higher cost is visible mostly at t1, while problem is that upgrade costs the same while pulsar and quasar are much better than mace and fortress. Fortress has been buffed by last changes in explosion dmg, but it's still week unit, it can be outranged by ripples.

**Comment by itcannotbe** [comment]
> Actually higher cost is visible mostly at t1, while problem is that upgrade costs the same

Is this #2021

**Comment by G0nTar** [comment]
I find hilarious how every unit has a "you have no way to defend against it at that point in the game"

Listen, for the amount of res they cost and the rare materials, you HAVE unless you've been playing Sim city the whole game, a way to defend against it, from the point you get silicon (you need that to produce almost every unit) you can defend againat every unit you mentioned, the moment you reached silicon tech..

**Comment by WinterCrystal** [comment]
I really don't see why they have to be nerfed at all since you can defend against them easily. Want to get rid of them from long distances? Use Ripple. Do you want to get rid of them easily and you have a lot of power and a decent amount of silicon? Use lancers. Do you want to avoid them getting your mend projectors and other turrets getting damaged? Use plastanium walls, don't have plastanium? Spam large titanium or thorium blocks. Do you want to shred them in close range? Use Fuse. Do you want to avoid getting attacked by hovering player-controlled, nova/pulsar/quasar? Use Scatters, preferably metaglass or lead Scatters. Do you want to get rid of them but don't have silicon or a lot of power? Use arcs, and so on, and so forth. It really is just a matter of getting good at building defenses, they're fine as they are seeing that they more expensive to make and in the mid to lategame, can easily get countered.

**Comment by theBrainIQ** [comment]
> Fortress has been buffed by last changes in explosion dmg, but it's still week unit, it can be outranged by ripples.

Yeah and it's armed with hails so obviously less range, I don't know what you are getting at
