### ISSUE TITLE
Reconstructor Item Consumption Revamp

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2021]
**Describe the content or mechanics you are proposing.**
Make reconstructors have non-uniform item consumption.

Reconstructors vary item comsumption based on a multiplier.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would increase/decrease item consumption of units depending on the set variable for the unit

It would break up the uniformity of the cost to upgrade units from 1 unit to another while mataining the same items needed for the reconstructors 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
#2019 should be implemented at the same time, with this suggestion having a lesser effect (vary construction time more than resource cost).

**Comment by genNAowl** [comment]
![BuildCosts](https://user-images.githubusercontent.com/68400583/119764558-7c858980-be66-11eb-916a-c2cf8dc370c2.jpg)

Dunno if it's the same for Times though

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
