### ISSUE TITLE
Make Segments ignore frag bullets and fully nullify AOE bullets

### ISSUE THREAD

**Issue by Intervection** [Anuken/Mindustry-Suggestions#2022]
**Describe what you would like changed, and why.**
I want to make segments better by making it ignore frag bullets because they are pretty useless against bullets with frag effect as they get distracted from the frags and make AOE bullets gets fully nullified or doesn't explode if a segment destroys that specific bullet.

**Describe the changes you want to propose. Include possible alternatives.**
Segments are mostly ignored by everybody because of its lack of utility, requiring phase to be built, and a high power consumtion. A segment can stop the bullet by destroying it but once an explosive bullet gets destroyed near the segment, the segment gets damage anyways and bullets with frag effects makes segments pretty much useless because it gets distracted by aiming frag bullets instead of the main bullet

**Comment by sup3r87** [comment]
i think a better idea would just be for segment to target whatever is the strongest projectile is in it's area. the strongest projectile is targeted - similar to foreshadow

**Comment by Intervection** [comment]
If it prioritize the strongest bullet then Antumbra's missle would get into the enemy structures easily because of its large bullets soaking all of the segments shots which would be a very bad idea to do that.

**Comment by sup3r87** [comment]
but you dont want it to target frag bullets? in that case should segment just completely ignore reign shots? im sure reign shots have more HP than antumbra missiles. im confused here.

**Comment by itcannotbe** [comment]
> im sure reign shots have more HP than antumbra missiles.

Bullets don't have hp 🤦🏻‍♂️.

Just ask b ducking remove.

**Comment by sup3r87** [comment]
well still, if it targeted the most damaging/strongest projectiles, why wouldnt antumbra missiles be targeted? im still confused

**Comment by itcannotbe** [comment]
AOE doesn't count as "bullet damage"

**Comment by Bohaska** [comment]
it cannot be that @itcannotbe hasn't said anything about using logic to do this yet

**Comment by itcannotbe** [comment]
> it cannot be that @itcannotbe hasn't said anything about using logic to do this yet

You can't logic segments because segments hit bullets not actual units or blocks.

**Comment by Intervection** [comment]
Instead of segments aiming the strongest bullets, how about segments prioritizing bullets with AOE damage. Its alot better than prioritizing Spectre type bullets

**Comment by itcannotbe** [comment]
Area damage is a combination of 2 things so which is which?

**Comment by Intervection** [comment]
What are the 2 things?
Is it the main bullet and the area damage of the main bullet?

**Comment by itcannotbe** [comment]
The damage dealt to the area and it's radius.

That doesn't get accounted for in computing for bullet "health" as far as I know.

Maybe I'm wrong. Dunno?
