### ISSUE TITLE
Make Parallaxes target different units

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#2023]
**The content or mechanics I am proposing:**
Change the Parallax targeting logic so multiple Parallaxes target different units.

**How this content will improve the game:**
Since their main goal is not to destroy but to control, it would be better to make different Parallaxes target different units to spread their effect.
_This change may reduce the effectiveness against bigger units if your defense is nothing but Parallaxes and Fuses,_ but it won't matter if [disarm effect](https://github.com/Anuken/Mindustry/pull/4762) gets merged.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

It counters the #1281 opinion.

2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by CountSudokku** [comment]
Maybe not exactly paralax, but maybe new turret that could pull ground units. I think its interesting idea.

**Comment by Phinner** [comment]
> Maybe not exactly paralax, but maybe new turret that could pull ground units. I think its interesting idea.

I don't think that pulling ground units would be a good idea... Think about Maces, T4 and T5 grounds units...

**Comment by joshuaptfan** [comment]
This would be implemented by storing on each unit a count of how many parallaxes are targeting it, then making parallaxes target the enemy in range with the fewest other parallaxes targeting it.

**Comment by joshuaptfan** [comment]
I think a better solution to make all parties happy is to enable logic control of parallaxes so players can set up their own targeting priorities as they please.

**Comment by AlvarGD** [comment]
how about for tier ones only up to one parallax targets each, for tier 2s only 2 paralaxes each, tier 3 get 3 parallaxes each, tier 4s get 5 parrallaxes and tier 5s get 8 parallaxes each.

**Comment by WinterCrystal** [comment]
> Maybe not exactly paralax, but maybe new turret that could pull ground units. I think its interesting idea.

Do you want to sabotage your defenses by dragging in Reigns and other t5 units towards them? Just remember, Ground units are scarier than the air ones.

**Comment by Kyllingene** [comment]
> > Maybe not exactly paralax, but maybe new turret that could pull ground units. I think its interesting idea.
> 
> Do you want to sabotage your defenses by dragging in Reigns and other t5 units towards them? Just remember, Ground units are scarier than the air ones.

[Units are now disarmed when pulled by paralaxes,](https://github.com/Anuken/Mindustry/pull/4762), so making ground units targetable would either be useless because you are killing your own defenses, or overpowered because now no units are allowed to attack you.
