### ISSUE TITLE
Give all (or most) bullets knockback

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2026]
**Describe what you would like changed, and why.**
The title. It just doesn't feel right when your giant array of turrets can't knock a flare off of its path - also, this kind of fixes the issue with horizons just falling onto your scatter wall and killing it.

**Describe the changes you want to propose. Include possible alternatives.**
Give all bullets possible at least some knockback - may be done automatically on startup based on bullet damage + splash damage

**Comment by joshuaptfan** [comment]
I support giving all solid projectiles a minimum amount of knockback (the effect would only be noticeable when bullets are hitting a target en masse), but would there be any desync issues since this moves units?

**Comment by Ilya246** [comment]
Unit positions are synced

**Comment by AlvarGD** [comment]
TOO OP

**Comment by Qvertyes** [comment]
Maybe give to spectre plastanium bullets with super strong knockback and average damage?

**Comment by Jammo2000** [comment]
This wouldn't be OP if implemented properly i.e. with knockback divided by mass/hp

**Comment by SheepCommander** [comment]
Agreed

**Comment by Humanoid-X** [comment]
Support. Knockback velocity must be divided by mass btw.

**Comment by TheNightglow** [comment]
This would also make a wider variety of towers in ones defence usefull

no longer would lancer-only spamm be the best early and mid tier defence, since they probably do no knockback

it allows an tradeoff between damage/ convenience and knockback and thus there is no longer just a single right choice in defence^^

**Comment by AlvarGD** [comment]
ok how about the knockback is calculated by dividing (the max health of the unit minus the square root of the max health minus the current health) by the damage of  the bullet and then multiplying it by (the log3 of (the damage of the bullet minus the defense) -3) or something like that

**Comment by Jammo2000** [comment]
Current health shouldn't change it.

**Comment by SheepCommander** [comment]
/shrug well if it's damaged it probably doesn't have the same mass

**Comment by Kyllingene** [comment]
Me: *breaks a bone*
Friend: "You will now take more knockback!"
Me: "Huh?"
Friend: "Well, because your physical structure was rearranged internally, you now have less mass."

**Comment by Bohaska** [comment]
Nice mod idea, to be honest, but I dunno if this will get into vanilla.

**Comment by Red0Sky** [comment]
hm this might be op but whatever
