### ISSUE TITLE
schematics folders

### ISSUE THREAD

**Issue by no-one724** [Anuken/Mindustry-Suggestions#2027]
**Describe the content or mechanics you are proposing.**
add folders/categories (power defence production) in the schem menu

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it will make the menu less messy

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Have you...

>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

[Duplicate of many other suggestions.](https://github.com/Anuken/Mindustry-Suggestions/issues?q=schematic+folder)

**Comment by Humanoid-X** [comment]
The Checkbox Paradox
People always tick the checkbox but did not even consider doing the things in the template. The Checkbox Paradox, also known as the Template Paradox and Github Issue Paradox, is a paradox commonly found in Github issues.
