### ISSUE TITLE
@Hazard with GetBlock for Boost-able units

### ISSUE THREAD

**Issue by Arcafanetiz** [Anuken/Mindustry-Suggestions#2028]
Makes GetBlock returns @ hazard type when the tile inputted is deep water or slag pool or any hazard tile that ground unit can stand in, but will die from it.
like @ solid type when the tile is solid terrain.

When using logic with Nova tree units that uses their boost (mech flying ability), Units above hazard tile can get their boost turned off since there's no way to detect and prevent that before doing it, the unit just follows command, go down and die.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by iLagSoUhax** [comment]
~~format is kil~~
good suggestion

**Comment by Humanoid-X** [comment]
1. Template
2. Goodd
