### ISSUE TITLE
suggestions for the autobridge

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#2029]
**Describe what you would like changed, and why.**
the autobridge bridges over things like this:
![image](https://user-images.githubusercontent.com/57631841/108997755-45a1ab00-76a0-11eb-8700-69e1abce2569.png)

![image](https://user-images.githubusercontent.com/57631841/108997978-92858180-76a0-11eb-9a61-e5d11a06699b.png)

![image](https://user-images.githubusercontent.com/57631841/108997996-974a3580-76a0-11eb-83f4-dc9f412c6d97.png)

that is especially annoying when enemy units break just a few conveyors
**Describe the changes you want to propose. Include possible alternatives.**
autobridge shouldn't build over conveyors going the same direction

**Comment by Sense101** [comment]
I think perhaps belts should not be considered obstructions at all, especially as you can build over any of them.

**Comment by TheNightglow** [comment]
Hang on, is there already an auto bridge feature in the game or am i misunderstanding this balancing feedback?

In anyway, I d say autobridge shouldn t see conveyors as bridgeable obstacles except from plastanium conveyors...

and you probably dont want autobridge to be enabled with plastanium conveyors anyway (since bridges completely kill the conveyor speed and then u might aswell use a titan conveyor in the first place^^) , which also means the problem above wouldnt happen when using plastanium conveyors on plastanium conveyor gaps^^

**Comment by Catchears** [comment]
> Hang on, is there already an auto bridge feature in the game or am i misunderstanding this balancing feedback?

There is.

> In anyway, I d say autobridge shouldn t see conveyors as bridgeable obstacles except from plastanium conveyors...

Yep.

**Comment by TheNightglow** [comment]
I might sound stupid here, but how do I use the current auto-bridge feature?
It does not auto select bridges for me and i cant see a setting to enable it?

I have automatic block suggestions on, but that only allows me to auto-select junctions, not bridges:
![Mindustry_zW3KV0xCg3](https://user-images.githubusercontent.com/22774396/109006503-70453100-76ab-11eb-8d9a-72386d7ab6da.png)

**Comment by joshuaptfan** [comment]
> > Hang on, is there already an auto bridge feature in the game or am i misunderstanding this balancing feedback?
> 
> There is.

There is, but it's on bleeding edge, which means it's not released yet to players who downloaded the stable build of the game.

**Comment by Catchears** [comment]
> > > Hang on, is there already an auto bridge feature in the game or am i misunderstanding this balancing feedback?
> > 
> > 
> > There is.
> 
> There is, but it's on bleeding edge, which means it's not released yet to players who downloaded the stable build of the game.

Ah sorry, wasn't aware it isn't in 125.1.

**Comment by SheepCommander** [comment]
Well I do agree but it's not in a stable version yet

**Comment by liuxilu** [comment]
Seems fixed: https://github.com/Anuken/Mindustry/commit/4b6a83dd82cce8023fb7f66ac65f3f545a52f3cf

**Comment by Catchears** [comment]
Ah, thanks for reminding me.
