### ISSUE TITLE
Add Resourcepack Support

### ISSUE THREAD

**Issue by pyDebugger** [Anuken/Mindustry-Suggestions#2031]
**Describe the content or mechanics you are proposing.**

Add resourcepack support, so you can select resourcepacks that change music and look of the game; You would also be able to create resourcepacks by yourself and share them, kinda like mods

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A possibility could be to add this ability to mods 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
dingus

**Comment by DeltaNedas** [comment]
> kinda like mods

how would this be any different to mods
is there any actual reason to just change the name to what minecraft uses?

**Comment by pyDebugger** [comment]
@DeltaNedas i am relatively sure you can’t do that with mods, and yes, i am thinking of something similar to what minecraft uses

**Comment by itcannotbe** [comment]
> @DeltaNedas i am relatively sure you can’t do that with mods, and yes, i am thinking of something similar to what minecraft uses

How sure even are you?

**Comment by pyDebugger** [comment]
@itcannotbe almost a 100%

**Comment by QmelZ** [comment]
> I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

:doubt:

**Comment by sample-text-here** [comment]
1. install as mod: [deepfriedustry.zip](https://github.com/Anuken/Mindustry-Suggestions/files/6037523/deepfriedustry.zip)
2. clos isue

**Comment by SheepCommander** [comment]
close please

**Comment by Kyllingene** [comment]
> @ itcannotbe almost a 100%

WRONG. Check out [Kyllingene/resource-pack-mod](https://github.com/Kyllingene/resource-pack-mod) to see how to do it.

**Comment by bvcbvc** [comment]
a
