### ISSUE TITLE
Reflection Field

### ISSUE THREAD

**Issue by ChangedRuby** [Anuken/Mindustry-Suggestions#2032]
The **Reflection Field**

_Reaches:_ Air troops
_Functionality:_ It has a range similar to the force  projector, it prevents the air troops from exceed that field, when the enemy troops touch, they are repelled, like when you try to pass into the void.
_Why i want this:_ This is a cool feature, and is a good prevention to random air units destroying your entire conveyors.
_How to unlock:_ After the force projector, in the tech tree
_Works with:_ Fase and Liquids to upgrade
_Extra suggestions:_ Every air troop that join in this field, will get the effect of the liquid upgrade. And slow down every enemy troop.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Or maybe if you add some resources, your force projector will slow air units down to like 50% of their speed. Maybe it'll work you mix cryo and phase or mix phase and silicon?

**Comment by Quick-korkc** [comment]
wave and tsunami can push away dead drone

**Comment by itcannotbe** [comment]
Hmmm I recall there are already suggestions about something like a force projector that repels air unit already.

**Comment by ChangedRuby** [comment]
I updated

**Comment by SheepCommander** [comment]
It's a cool idea

**Comment by Bohaska** [comment]
> Hmmm I recall there are already suggestions about something like a force projector that repels air unit already exist.

yep there was a pr making force projectors repel air units
