### ISSUE TITLE
Use interplanetary accelerator to launch to any secto

### ISSUE THREAD

**Issue by NumericPrime** [Anuken/Mindustry-Suggestions#2033]
It would be cool if you could use the interplanetary accelerator to launch a core to any sector you could otherwise launch a core to but with the resurces of the sector the building stands.
(I hope this is the right thread for suggestions)

**Comment by Yell245** [comment]
1. Template
2. The interplanetary accelerator is a railgun, it can't physically shoot somewhere else, only into the straight way
