### ISSUE TITLE
ulocate sand

### ISSUE THREAD

**Issue by Thankyou69** [Anuken/Mindustry-Suggestions#2034]
**Describe the content or mechanics you are proposing.**

make ulocate locate sand for the mono and nova tree

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
sand is already mineable, but you have to plug in the coordinates of the sand manually

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Nester23** [comment]
Also, the fact that units can mine sand isn't mentioned in the core database.

**Comment by itcannotbe** [comment]
Sand isn't an ore.

**Comment by Thankyou69** [comment]
> Sand isn't an ore.

scrap isnt an ore

**Comment by itcannotbe** [comment]
Scrap is ore. Not a floor tile.

**Comment by Thankyou69** [comment]
floor tiles cannot be mined i agree that sand is labeled as one, i am proposing that it is changed to a detectable ore so that i can automate silicon

**Comment by SheepCommander** [comment]
90% certain it does display sand as "available resources in this sector" anyways so makes sense

**Comment by itcannotbe** [comment]
So basically you want this
![Screenshot_20210226_021129](https://user-images.githubusercontent.com/45280919/109198442-307c6780-77d9-11eb-9d83-e560bffa9a74.jpg)

**Comment by Thankyou69** [comment]
> So basically you want this
> ![Screenshot_20210226_021129](https://user-images.githubusercontent.com/45280919/109198442-307c6780-77d9-11eb-9d83-e560bffa9a74.jpg)

not that exactly but sort of

**Comment by Thankyou69** [comment]
looks like this got passed in another post, ill close this now

**Comment by Nester23** [comment]
The other post was closed by author because of your post. Please re-open this.

**Comment by Thankyou69** [comment]
oh lmao

**Comment by SheepCommander** [comment]
_lol_
