### ISSUE TITLE
Placing cores and other teams buildings in Sandbox

### ISSUE THREAD

**Issue by NumericPrime** [Anuken/Mindustry-Suggestions#2035]
**Describe the content or mechanics you are proposing.**

It should work simular to the map editor's option to edit ingame.
Additionally you should be able to place core shards.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This is great for trying out and new scematics
and test unit attack strategies e.g. using logic.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
There are mods that do this, but it should be a vanilla feature.

**Comment by itcannotbe** [comment]
But why? It just complicates sandbox for no good reason at all.
It's sandbox for pete's sake.

**Comment by Jammo2000** [comment]
Yes, and in sandbox you should be able to do whatever you want. That's like
the point of a sandbox.

**Comment by Kyllingene** [comment]
"It just complicates sandbox for no good reason at all."

[Anuken/Mindustry](https://github.com/Anuken/Mindustry/blob/1bb97cae39bc4a8faa91626053067ddc18fa7a7e/core/src/mindustry/world/blocks/storage/CoreBlock.java#L111)
```
public boolean canPlaceOn(Tile tile, Team team){
        if(tile == null) return false;
        CoreBuild core = team.core();
        //must have all requirements
        if(core == null || (!state.rules.infiniteResources && !core.items.has(requirements, state.rules.buildCostMultiplier))) return false;
        return (tile.block() instanceof CoreBlock && size > tile.block().size) || World.gamemode == "sandbox"; //added the or
    }
```
NOTE: I suck (entirely) at Java programming and have a very minimal idea of how the core game works. My point is that it is as simple as adding a single check to the CoreBlock.canPlaceOn method.

**Comment by itcannotbe** [comment]
You forgot the part of the suggestion allowing for team switching/block team switching.

**Comment by Kyllingene** [comment]
***in Sandbox***.
