### ISSUE TITLE
Add resurce icons to sector icons

### ISSUE THREAD

**Issue by NumericPrime** [Anuken/Mindustry-Suggestions#2037]
**Describe the content or mechanics you are proposing.**

Make resurce icons available to lable a sector.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

You can mark a on a certain resurce spetialized sector using the corrosponding icon making it easier to find on the planet map.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The title could have been clearer.

**Comment by SheepCommander** [comment]
Add resource icons as an option for sector icons?

Sure

**Comment by itcannotbe** [comment]
The better title would be "The option to use Resource Icons to name/identify sectors easily for the purpose of marking sectors that people use to make certain resources in"

**Comment by Humanoid-X** [comment]
yes

**Comment by Kyllingene** [comment]
> The better title would be "The option to use Resource Icons to name/identify sectors easily for the purpose of marking sectors that people use to make certain resources in"

"Ability to use resource icons as sector icons" is much more concise. Seriously, that is *way* to unwieldy.

**Comment by itcannotbe** [comment]
In my defense, my title suggestion is much more consice by providing the main point of the sughestion by merely looking at the title.
