### ISSUE TITLE
Monoresource sectors

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2038]
I suggest add to the new planets (or remake old) sectors with one or two resources. It would be cool to build mining bases and launch it to other sectors to make super productive sectors. This idea motivates people to use launchpad and increase difficult of the game. Also, these sectors can block access to early thorium sectors, because with only, maybe, coal sector you can't do anything if you didn't launch resources with core, but in this case other resources will be limited.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Qvertyes** [comment]
ok its bad

**Comment by Axzye** [comment]
that's too sad

**Comment by iLagSoUhax** [comment]
this is so sad.

**Comment by WinterCrystal** [comment]
> that's too sad
> because your suggestion was bad
> i could show some hate
> for your grammar isn't so great
> but i won't do it
> because you closed it

Sick bars, bro!
