### ISSUE TITLE
Capture the Core Gamemode

### ISSUE THREAD

**Issue by DevonDoesCode** [Anuken/Mindustry-Suggestions#204]
**Describe the content or mechanics you are proposing.**
A new gamemode for both solo (campaign or otherwise) and multiplayer, where there are multiple cores across the map. Each team (AI or human player) gets one (1) core, and the rest are blank/neutral. To capture one, you destroy it, and it is auto replaced by a core aligned to your team. If 2 teams are fighting over a core, last hit gets the new core. Play until all cores are under one alignment.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
There's not many chances for PvP stuff to take place, and this may fill that gap in a fun way. The objective is similar to the maps with "Destroy the Core" objectives, but you can control your battlefield better when you capture a core closer to the front lines, and possibly changing where you respawn. Lots of other games have this sort of CPC type gamemode, and I've seen it be very popular with those players.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ritzip** [comment]
While this may be fun, it may not work well as a tower defence.

**Comment by DeltaNedas** [comment]
plugins

**Comment by HaphLife** [comment]
Maybe instead have that the last 25% has to be from the same team (when another team attacks it, it resets to 25% health) so that it is a bit less random, and so that you can’t kill steal.

**Comment by unjown** [comment]
this is literally hex right?
