### ISSUE TITLE
Unloader don't work with middle parts of bridge conveyors, and i hope it will be change.

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2040]
That's all. 

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Just break the bridge. Then place a bridge directly after it, but don't connect it.

We don't really need this, the throughput alone of bridge conveyors doesn't even support this suggestion's use case, it it even has one, **_since op actually didn't bother to fill that part out_**

**Comment by Qvertyes** [comment]
> Just break the bridge. Then place a bridge directly after it, but don't connect it.
> 
> We don't really need this, the throughput alone of bridge conveyors doesn't even support this suggestion's use case, if it even has one, **_since op actually didn't bother to fill that part out_**

![Screenshot_2021-02-25-11-00-55-961_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/76211803/109121797-c91ed300-7758-11eb-8424-81301fcc3150.jpg)

**Comment by Qvertyes** [comment]
> Just break the bridge. Then place a bridge directly after it, but don't connect it.
> 
> We don't really need this, the throughput alone of bridge conveyors doesn't even support this suggestion's use case, if it even has one, **_since op actually didn't bother to fill that part out_**

It will be helpful in narrow places, but i think a bit and has concluded to next: it can break some schematics, ok, close it
