### ISSUE TITLE
Schematics folders

### ISSUE THREAD

**Issue by ChangedRuby** [Anuken/Mindustry-Suggestions#2041]
**Schematic folders**

I am a very old mindustry player, and it's very sick to have so many schematics, because it's a mess. So, my suggestion is a possibility to separate schematcs in folders with different locations and folder name/color. A search filter would be good with this.

_Pls anuke_

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ChangedRuby** [comment]
O-o

**Comment by QmelZ** [comment]
> I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

aaaaaaaaaaaaaaaaaaaaaaa

**Comment by GreyMario** [comment]
> [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

[_**No you ain't**_](https://github.com/Anuken/Mindustry-Suggestions/issues/2027)

**Comment by GreyMario** [comment]
Also, don't thumbs-up your own suggestion, Ironfist.

**Comment by itcannotbe** [comment]
> > [I have done a quick search in the list of suggestions to make sure this has not been suggested yet.](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+schematics+folders+)
> 
> [aaaaaaaaaaaaaaaaaaaaaaa](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+schematics+folders+)

**Comment by ChangedRuby** [comment]
I looked at the list of suggestions

**Comment by ChangedRuby** [comment]
lol

**Comment by CountSudokku** [comment]
The problem is that schematics folder is actually needed and it looks like its going to be dont added fir no reason. This would really make game much easier.

**Comment by bvcbvc** [comment]
it is true that schematics need more ability to organize

**Comment by Fipico2** [comment]
Just name them Category- Actual name and use the search bar

**Comment by bvcbvc** [comment]
> Just name them Category- Actual name and use the search bar

if your gonna do that why not just search for them directly

**Comment by Kyllingene** [comment]
The idea is that if you named something "Silicon-Medium Logic Controlled Smelter", you can just search "Silicon" and find it, even if you forgot the exact name. Visually, it also makes it easier to understand what category something is in.

**Comment by bvcbvc** [comment]
what if your search that , it dont come up and you remember you named it rubber

**Comment by Kyllingene** [comment]
Well that's your fault for not following your own naming conventions. Folders would not save you there.

**Comment by bvcbvc** [comment]
can you stop responding now?
