### ISSUE TITLE
Allow mining sand when double click to mine is enabled

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry-Suggestions#2042]
**Describe the content or mechanics you are proposing.**
Since double click to mine fixes the issues with accidentally mining sand whenever you click anything, why not allow sand to be mined when double click to mine is enabled.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Being able to mine sand is more of a QoL thing and it just makes sense that you would be able to do so considering how low it's hardness is.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Thankyou69** [comment]
no

**Comment by itcannotbe** [comment]
If Sand cannot be mined by a unit, how the hell would you expect double click would work with it.

**Comment by TheNightglow** [comment]
> 
> If Sand cannot be mined by a unit, how the hell would you expect double click would work with it.

i remember someone saying that units can actually mine sand, if you use a processor to command them to mine at the position of a sand tile, they allegedly are able to gather sand (talking here about the units that can actually mine stuff)

**Comment by buthed010203** [comment]
> If Sand cannot be mined by a unit, how the hell would you expect double click would work with it.

I've done it myself in a client, its super simple. Sand can actually be mined by units because of its low hardness but it has a flag that tells the game specifically not to let it be mined. ![](https://discord-cdn.is-terrible.com/zLZxSq.png)
The way I implemented this was pretty scuffed but would require minor effort to improve ![](https://discord-cdn.is-terrible.com/KuUmnw.png)

**Comment by itcannotbe** [comment]
> > If Sand cannot be mined by a unit, how the hell would you expect double click would work with it.
> 
> I've done it myself in a client, its super simple. Sand can actually be mined by units because of its low hardness but it has a flag that tells the game specifically not to let it be mined. ![](https://camo.githubusercontent.com/499fc67d7749cfe40fe6c4bbb3f97bebc0c7689c197a33ef904f5c14fd9c0ccf/68747470733a2f2f646973636f72642d63646e2e69732d7465727269626c652e636f6d2f7a4c5a7853712e706e67)
> The way I implemented this was pretty scuffed but would require minor effort to improve ![](https://camo.githubusercontent.com/6beb28e1b93e32cdcdb658c1f93baf54e878005aaebae9357bad4c86922e8e60/68747470733a2f2f646973636f72642d63646e2e69732d7465727269626c652e636f6d2f4b75556d6e772e706e67)

As evidenced by that flag that wouldn't allow you, there is a reason behind it because it was intentionally restricted. Duh.

**Comment by itcannotbe** [comment]
This isn't a question of can it, the point is it's actually restricted and just allowing it within an option isn't just balanced to those who didn't enabled that option.

**Comment by itcannotbe** [comment]
if you want that, this suggestion should be about why it's restricted in ths first place.

**Comment by buthed010203** [comment]
> if you want that, this suggestion should be about why it's restricted in ths first place.

As it specifically says its disabled because it is annoying, that issue is solved when double click to mine is enabled.

**Comment by Thankyou69** [comment]
titanium units also cant mine automatically, but same as sand, it can be mined with a processor, if units can mine sand, so should players

**Comment by TheNightglow** [comment]
not sure if double click is the best solution, but i generally find it annoying that single-click mines, since i keep doing it accidently when clicking of a building...

guess taking out sand was just a semi-solution for this problem of accidently mining, reducing the problem to only ores, but not actually solving it...

while double click click would be a solution, i m wondering if there is something better... 
maybe holding down left click for a second to initate mining?

**Comment by buthed010203** [comment]
> not sure if double click is the best solution, but i generally find it annoying that single-click mines, since i keep doing it accidently when clicking of a building...
> 
> guess taking out sand was just a semi-solution for this problem of accidently mining, reducing the problem to only ores, but not actually solving it...
> 
> while double click click would be a solution, i m wondering if there is something better...
> maybe holding down left click for a second to initate mining?

double click is already in the game so im just proposing that sand should be allowed to be mined when it is enabled

**Comment by TheNightglow** [comment]
> 
> 
> > not sure if double click is the best solution, but i generally find it annoying that single-click mines, since i keep doing it accidently when clicking of a building...
> > guess taking out sand was just a semi-solution for this problem of accidently mining, reducing the problem to only ores, but not actually solving it...
> > while double click click would be a solution, i m wondering if there is something better...
> > maybe holding down left click for a second to initate mining?
> 
> double click is already in the game so im just proposing that sand should be allowed to be mined when it is enabled

oooh i didnt know that thats already a thing

**Comment by buthed010203** [comment]
> > > not sure if double click is the best solution, but i generally find it annoying that single-click mines, since i keep doing it accidently when clicking of a building...
> > > guess taking out sand was just a semi-solution for this problem of accidently mining, reducing the problem to only ores, but not actually solving it...
> > > while double click click would be a solution, i m wondering if there is something better...
> > > maybe holding down left click for a second to initate mining?
> > 
> > 
> > double click is already in the game so im just proposing that sand should be allowed to be mined when it is enabled
> 
> oooh i didnt know that thats already a thing

was merged in this morning

**Comment by bvcbvc** [comment]
@buthed010203 close this its done lol

**Comment by buthed010203** [comment]
> @buthed010203 close this its done lol

I made that pr myself :^)
