### ISSUE TITLE
 New Weapon

### ISSUE THREAD

**Issue by Skreeeonk** [Anuken/Mindustry-Suggestions#2043]
My suggestion is a frag mine counterpart to the shock mine.

It would improve the game since out of the 2 resources after graphite, which are silicon and metaglass, silicon has a couple more uses than metaglass. So if we give the shock mine which is made with silicon a metaglass counterpart mine it could be a frag mine since metaglass has the frag effect when used as Scatter ammo.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
Mods.

**Comment by DeltaNedas** [comment]
claymore*

**Comment by RedstonerKBC** [comment]
"Don't suggest new content" should be put in the list of things not to suggest since everytime someone suggests new content people always reply with "mods". Should also put other commonly suggested items that always get closed so people don't suggest them. Seriously, why doesn't that file ever get updated???

**Comment by BlueWolf3682** [comment]
a lot of things get suggested are decent concepts, but they just dont fit into the basegame. thats why i say "Mods."

**Comment by itcannotbe** [comment]
> a lot of things get suggested are decent concepts, but they just dont fit into the basegame. thats why i say "Mods."

On the flip side, a lot of things get suggested are crappy or overpowered concepts that just doesn't fit into the basegame no matter what.

**Comment by Kyllingene** [comment]
I think this falls under the "cool but completely unnecessary" category. Why expend effort on something who's value is dubious?

**Comment by Bohaska** [comment]
Because you love it

**Comment by Kyllingene** [comment]
But does Anuke?
