### ISSUE TITLE
This is getting out of hand

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2044]
**Describe what you would like changed, and why.**
Make this not possible.

![Screenshot_20210226_061211](https://user-images.githubusercontent.com/45280919/109226400-a98bb700-77f9-11eb-8937-da8213cbb764.jpg)

**Describe the changes you want to propose. Include possible alternatives.**

Have no idea.

**Comment by CountSudokku** [comment]
Whats the point of this "suggestion*? It's simple spam, nothing more.

**Comment by Thankyou69** [comment]
ok i understand what this means but it is not possible with one processor, you would need at least 2 processors per smelter if you want a flare to collect the silicon, 3

**Comment by SheepCommander** [comment]
.-.

**Comment by Yell245** [comment]
"Oh no! The players are using system created to automate things... TO AUTOMATE THINGS!!!"

**Comment by Kyllingene** [comment]
"Oh no! The players are making more space efficient but less resource efficient methods with blocks made for automation? ***VETO***"

**Comment by Bohaska** [comment]
it cannot be that @itcannotbe has made his first unpopular post.

**Comment by itcannotbe** [comment]
> it cannot be that @itcannotbe has made his first unpopular post.

Nope. This isn't the first one. Sorry to break it to you.

**Comment by Thankyou69** [comment]
oh u edited it, now it uses 4 processors instead of one, still not possible on that setup

**Comment by sample-text-here** [comment]
> still not possible on that setup

it is. technically you could do it in one processor but the code would be spaghetti

**Comment by WinterCrystal** [comment]
Ah yes, prevent people from automating things on a game that is basically encouraging automation. **Brilliant!**

**Comment by Thankyou69** [comment]
> > still not possible on that setup
> 
> it is. technically you could do it in one processor but the code would be spaghetti

yes, but even if you use a hyper processor, it would lag so badly, only like 4 would run at a time

**Comment by Newguy-ish** [comment]
yeah just close it at this point

**Comment by SMOLKEYS** [comment]
> Ah yes, prevent people from automating things on a game that is basically encouraging automation. **Brilliant!**

![Screenshot_20210227-145923_Mindustry.jpg](https://user-images.githubusercontent.com/75618732/109378308-6706cf00-790c-11eb-9416-49e614f793a1.jpg)
