### ISSUE TITLE
Liquid progression system is bland

### ISSUE THREAD

**Issue by Bobbystevenson** [Anuken/Mindustry-Suggestions#2045]
Anuke, would you ever consider any new liquids? Tbh the liquid progression system is pretty 1 dimensional.

It would help make the liquid progression system more interesting

**Comment by BlueWolf3682** [comment]
Mods.

**Comment by the-kido** [comment]
To an extent I agree but what will this liquid be and what would it do? It's easy to say you want something but having a more detailed suggestion would help.

**Comment by the-kido** [comment]
> Mods.

That doesn't mean there can't be a new liquid(s) for the actual game. Every suggestion can be a mod anyway.

**Comment by RedstonerKBC** [comment]
While you're at it add "any new game content" to the README.md things you shouldn't suggest. That or we all need to chill with the "mods" comments.

**Comment by itcannotbe** [comment]
Anuke: *Reads Suggestion*

Also Anuke:

"Incredible. Nobody has ever even considered suggesting More Liquids before. This is a revelation. I would never have thought of adding More Liquids myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Liquids immediately."

**Comment by itcannotbe** [comment]
Template be like:
"If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche."

OP: Meh.

**Comment by Kyllingene** [comment]
I don't think liquids are supposed to be this big thing in the game. They are either booster or a material to something like cryo or plast. Unnecessary suggestion.

**Comment by Newguy-ish** [comment]
close this please

**Comment by Kyllingene** [comment]
I just realized that you have opened ***three issues*** on the topic of "more liquids".

**Comment by Bobbystevenson** [comment]
> I just realized that you have opened _**three issues**_ on the topic of "more liquids".

One of them was too vague so i did another
The third one was because im new to git and didnt know how to re open it after i accidentally closed it
I closed them all now, At least this way Natalie will shut the F up

**Comment by Kyllingene** [comment]
Fair, but still a lot of issues. Just so you know, you can also edit issues by clicking those three dots on the top-right of the issue, then clicking "edit". You probably didn't know, but that way you could have just edited the vague one.
