### ISSUE TITLE
[logic] Sensor in @type

### ISSUE THREAD

**Issue by Nester23** [Anuken/Mindustry-Suggestions#2047]
**Describe the content or mechanics you are proposing.**

Make sensor be able to sensor values in types of blocks/units.

Example:

```
sensor result @flare @maxHealth
sensor result @mega @itemCapacity
sensor result @corvus @range
sensor result @duo @ammoCapacity
sensor result @container @itemCapacity
sensor result @mechanical-pump @liquidCapacity
sensor result @battery @powerCapacity
sensor router @router @type
```
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Sometimes there's a need for those values before there's a sensible block or unit available.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by PolloUsami** [comment]
there exist descriptions in game, or just blind units and sensor or blocks, its that easy

**Comment by Nester23** [comment]
I want to avoid hardcoding values as much as possible, and I need to do a check before there are blocks/units that can be sensed defined. In my case I want to have all of those sensors stuffed in a place together with configs and then find blocks/units and operate based on the configs. Also the rrquested feature would bring overall quality of life, and also allow for some new ways to do things.

**Comment by liuxilu** [comment]
This needs to add sensor interface to Blocks.
