### ISSUE TITLE
Unit/Turret Kill Counter (Track Turrets / Units Efficiency)

### ISSUE THREAD

**Issue by G0nTar** [Anuken/Mindustry-Suggestions#2048]
**Describe the content or mechanics you are proposing.**

-Basically, adding a track of individual Turrets/Units kill count or damage dealt, to track how efficient they are on the battlefield and give better feedback to players and "creating a sort of bond" to some of their structures n' units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

-It would make players engage in a deeper way with their units n' turrets, being able to know good a turret or unit is doing.

-It can help to improve new players n' veterans defensive and offensive strategies, since you have more data and a better understanding of how well your military units/turrets are doing.

-Plus you can feel more attached to certain units or turrets when you notice how good they're performing, giving players a warm feeling of: 
"Look how many bad guys you helped me take down!! How's a good boy?! You are!"

That is all.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Please edit you suggestion. All I see is the template and the title, otherwise it's empty.

**Comment by G0nTar** [comment]
> Please edit you suggestion. All I see is the template and the title, otherwise it's empty.

i was on it, accidentally sent the template half-finished, and i jumped right away to fill it when i noticed the miss-click :) 

Thanks for noticing it that fast tho <3

**Comment by itcannotbe** [comment]
Need to exclude online and custom games from stats gathering.

Otherwise inflating numbers is easy.

**Comment by G0nTar** [comment]
> Need to exclude online and custom games from stats gathering.
> 
> Otherwise inflating numbers is easy.

So? What's your point, on campaign or even Multiplayer, i see no problem on any showing you a killcount, if your concern is network overload, you can keep it Local to the client, i see no issues yet.

**Comment by itcannotbe** [comment]
Well this can get implemented to seperate online activity too. XD

**Comment by G0nTar** [comment]
And it's not a complex and over complicated feature.
It would be a day or 2 of creating the Script and testing it, adding a label n' integer attached to it on the GUI, and if you don't want to send it over the network to all the clients, then that's what kind of has to be done from a programmer Point of View

**Comment by Bohaska** [comment]
> Need to exclude online and custom games from stats gathering.
> 
> Otherwise inflating numbers is easy.

I think he meant like using this feature to see how efficient the turrets are, not using this feature like a high score sort of thing

**Comment by itcannotbe** [comment]
> > Need to exclude online and custom games from stats gathering.
> > Otherwise inflating numbers is easy.
> 
> I think he meant like using this feature to see how efficient the turrets are, not using this feature like a high score sort of thing

I'm pretty sure people will use this to brag about something.

**Comment by joshuaptfan** [comment]
It would just be an additional "Damage dealt: _X_" in the hover info. (I suggest tracking damage dealt instead of kills, as it would provide a more accurate picture of each turret's effectiveness.)

No long term stat tracking for all turrets of this type is necessary. This would help players optimize their defenses by relocating turrets that have dealt no damage.

**Comment by marky0470** [comment]
So this would be a new variable for the sensor to get like @damageDealt or @unitsKilled?

**Comment by Jammo2000** [comment]
I agree with Joshua, damage dealt is a much better measure. Otherwise foreshadows (which get few kills but good damage) would be on a different scale than crowd control like ripples.

**Comment by SheepCommander** [comment]
Ye damage dealt

**Comment by G0nTar** [comment]
> > > Need to exclude online and custom games from stats gathering.
> > > Otherwise inflating numbers is easy.
> > 
> > 
> > I think he meant like using this feature to see how efficient the turrets are, not using this feature like a high score sort of thing
> 
> I'm pretty sure people will use this to brag about something.

What is this comment? Like, for real.. 

Idk why guessing that maybe someone may brag about something would have something or anything to do with this suggestion at all. 

It's like saying game trophies are bad because people can brag of having those too, it'd not even related to the game itself whatever people do with their time. 

Either way, this feature has nothing to do with highscores, or anything you can brag about, it seems you didn't even take a minute to properly read the suggestion at all.

It's purpose (as some gentlemen pointed you out already) is to have a better feedback of turrets / units effectiveness depending on positioning / ammo / buffs etc.. 

By just adding 1 feature. 

Tracking how they are performing... 

Like their dmg output, etc
