### ISSUE TITLE
Liquid system is bland

### ISSUE THREAD

**Issue by Bobbystevenson** [Anuken/Mindustry-Suggestions#2049]
Im proposing new smart liquids to make the progression system less bland, either that or more uses for liquids.
Half the liquids in this game serve no _**unique**_ purpose other than to make a specific item(s).

The basic concept is that combining certian items with slag would give it a more practical purpose. Eg mixing slag with Silicon plast and phase would make a liquid to speed up factories. Mixing slag with Large amounts of silicon, copper, lead and plastinium would provide a liquid that could boost support buildings.

It would make defenses more intricate, at this point all you have to do is make a line of fuses and parallaxes. I suppose it could also make **_more_** tsunami [insert tower here] combos.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
       **_I have allready suggested this but it was too vague_**
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bobbystevenson** [comment]
Prediction, everyone is gonna spam "mods exist"

**Comment by GreyMario** [comment]
> `3. [x] I am unfamiliar with all the content already in the game, but have checked this checkbox anyway because the template told me to.`

You've never placed liquids inside of a Wave or Tsunami, have you.

**Comment by Bobbystevenson** [comment]
> > `3. [x] I am unfamiliar with all the content already in the game, but have checked this checkbox anyway because the template told me to.`
> 
> You've never placed liquids inside of a Wave or Tsunami, have you.

Learn to read "it could also make _**more**_ tsunami [insert tower here] combos."

**Comment by itcannotbe** [comment]
From #2045 and now this one .....

**Comment by itcannotbe** [comment]
Anuke: Reads Suggestion

Also Anuke:

"Incredible. Nobody has ever even considered suggesting More Liquids/Items before. This is a revelation. I would never have thought of adding More Liquids/Items myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Liquids/Items immediately."

**Comment by itcannotbe** [comment]
> Half the liquids in this game serve no purpose other than to make a specific item(s).

Wave/Tsunami be like: Um. No.

**Comment by Bobbystevenson** [comment]
> From #2045 and now this one .....

Hey, you guys told me to make it more specific so i did. Happy?

**Comment by Bobbystevenson** [comment]
> > Half the liquids in this game serve no purpose other than to make a specific item(s).
> 
> Wave/Tsunami be like: Um. No.

**Comment by Bobbystevenson** [comment]
Wait, how do i re open an issue

**Comment by itcannotbe** [comment]
To be honest, this suggestion just adds unnecessary bulk to the game.

Not to mention better alternative are already in the game.

Say like:

Something that makes buildings faster is already achieved easily with Overdrives.

**Comment by Bobbystevenson** [comment]
> To be honest, this suggestion just adds unnecessary bulk to the game.
> 
> Not to mention better alternative are already in the game.
> 
> Say like:
> 
> Something that makes buildings faster is already achieved easily with Overdrives.

Thats kind of the idea, alternatives.

**Comment by itcannotbe** [comment]
But your alternatives makes use of later game item, more specific usage, and the current method is like

Plop Overdrive, Power it, Feed it with Items and/or Liquids.
Boost Goes Brrrrrrr.

**Comment by itcannotbe** [comment]
Also what other usage does your suggested liquid has?

It's too specific, it feels too wasteful.

**Comment by itcannotbe** [comment]
Also, you can actually editing your post/comment and even the title.

**Comment by itcannotbe** [comment]
@Bobbystevenson 
![Screenshot_20210226_193510](https://user-images.githubusercontent.com/45280919/109295479-c95ac380-7869-11eb-9830-8ee32f391812.jpg) There is the re open button you're looking for.

**Comment by Bobbystevenson** [comment]
Thanks

**Comment by Thankyou69** [comment]
close this please, i suggest using vanilla++ or diamonds mod to add more liquids

**Comment by WinterCrystal** [comment]
> Half the liquids in this game serve no _**unique**_ purpose other than to make a specific item(s).
Cryofluid & water: _are we a joke to you?_

**Comment by SheepCommander** [comment]
if you ask me close

**Comment by Bobbystevenson** [comment]
> > Half the liquids in this game serve no _**unique**_ purpose other than to make a specific item(s).
> > Cryofluid & water: _are we a joke to you?_

...  Half
Learn to read

**Comment by Thankyou69** [comment]
> > > Half the liquids in this game serve no _**unique**_ purpose other than to make a specific item(s).
> > > Cryofluid & water: _are we a joke to you?_
> 
> ... Half
> Learn to read

oil and slag: Are we a joke to you?
