### ISSUE TITLE
Do you plan on bumping the build tools version from 29.0.2 to 29.0.3 anytime soon?

### ISSUE THREAD

**Issue by simdimdim** [Anuken/Mindustry-Suggestions#205]
More of a question than a feature request really and all in all what the title says

**Comment by Anuken** [comment]
Why?

**Comment by simdimdim** [comment]
cant build mindustry-git on arch easily cuz 'android-sdk-build-tools' points to the latest and without some fiddling I just end up having to do `sed -i 's/29.0.2/29.0.3/g' android/build.gradle` in the PKGBUILD every time (got an update script that bugs me just a tad too often when there's a minudstry update :D)

**Comment by Anuken** [comment]
Implemented.

**Comment by simdimdim** [comment]
The same request/suggestion but for 30.0.0? :D
