### ISSUE TITLE
anti piracy for mindustry steam

### ISSUE THREAD

**Issue by firstcreator48** [Anuken/Mindustry-Suggestions#2052]
**Describe what you would like changed, and why.**
the last hour i researched anti piracy, i knew you have to add this to steam version of mindustry.
if YOU do NOT add this, more pirates will pirate this game and more people who is the part of the community will be even MORE angrier. please add this.

**Describe the changes you want to propose. Include possible alternatives.**
add anti piracy for steam mindustry because the community will slowly fall.

**Comment by itcannotbe** [comment]
How do you enforce anti-piracy for an actual free (for the most part) game again?

I am confused, please enlighten us.

**Comment by BlueWolf3682** [comment]
...you cannot enforce anti-piracy on an open source game.

**Comment by firstcreator48** [comment]
> How do you enforce anti-piracy for an actual free (for the most part) game again? I am confused, please enlighten us.

yesyes, but i am talking about the steam version, i AM sure

**Comment by firstcreator48** [comment]
i thought it was a good idea to enforce anti piracy, bad idea

**Comment by firstcreator48** [comment]
sorry but my curiosity made me do this, i am sorry everyone. hope you apologize

**Comment by itcannotbe** [comment]
The steam version is no different from free versions of the game, apart for steam integrations. So how do you enforce anti-piracy again?

The paywall exist for steam, because using steam integrations isn't free.

**Comment by DeltaNedas** [comment]
deltanedas/7-seas

**Comment by ScepterReignPlayz** [comment]
Even tho this is closed

I wanna point out that the game is open sourced
It also has a itch.io version that is basically free so who in the world would pirate the game if it's basically free on Android and PC

**Comment by firstcreator48** [comment]
hmmst okay i forgot to see what is the consequence after that okay, i
apologize

**Comment by itcannotbe** [comment]
Actually there are people who would sell an source game and make it paid, but not the likes of mindustry.

See FGFS.
