### ISSUE TITLE
Remove the vaults next to the core in planetary terminal

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#2054]
**Describe what you would like changed, and why.**remove the vaults next to the core in planetary terminal because i crash landed a qaud to a vault and the core died because its explosive

**Describe the changes you want to propose. Include possible alternatives.** removing the vaults next to planetary terminal to pervent qauds or reducing the explosive compounds in the core its just too easy to get a qaud over there and commit atomic bomb

**Comment by nichrosia** [comment]
Hmm. One alternative to this is simply removing the possibility for cores/vaults to generate with explosive material inside them, unless it is unloaded as ammunition.

**Comment by guncatt** [comment]
> Hmm. One alternative to this is simply removing the possibility for cores/vaults to generate with explosive material inside them, unless it is unloaded as ammunition.

Good enough
