### ISSUE TITLE
Bookmark Fav Server

### ISSUE THREAD

**Issue by zambronix** [Anuken/Mindustry-Suggestions#2055]
It would be nice if I could drag and drop my favorite server from the list in the middle,  on to the side, for easy access.

I sometimes forget the name of the server since they are sometimes  named in a weird way, so using the search function isn't an option. And with an ever growing list of servers, it can take a while to find your favorite server. 

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by marky0470** [comment]
Pretty sure i've seen this one before

**Comment by Humanoid-X** [comment]
I recall this being suggested before.

**Comment by SheepCommander** [comment]
Good but duplicate

**Comment by unjown** [comment]
add server exist :/
just get its ip/domain from its discord done

**Comment by Bohaska** [comment]
> - [X] I have
>### not
>followed the template

>Incredible. **Nobody** has ever even considered suggesting bookmarking servers before. This is a revelation. I would never have thought of adding this myself. This idea is so _revolutionary_, so _clear_, so _simple_ that absolutely no further explanation is necessary. I will now go and implement this _amazing_ suggestion immediately.

**Comment by itcannotbe** [comment]
That's not even close to the original context.
