### ISSUE TITLE
The problem with core extension

### ISSUE THREAD

**Issue by Yell245** [Anuken/Mindustry-Suggestions#2056]
**Describe what you would like changed, and why.**
Today we have a problem when your core extension gets destroyed and then boom, the entire core is gone. It could be seen very good when you're in campaign: all crux cores have maximum of all items thus you just need to destroy the extension block of it to win.

**Describe the changes you want to propose. Include possible alternatives.**
I think the easiest solution is to reduce damage the core gets from ally buildings' explosions / make it completely immune to such threat. It could also solve the problem with griefers nuking a thorium reactor near the core.
Other solution is to make all extensions have the same hp as the core itself / 75% of hp the core has.

**Comment by RedstonerKBC** [comment]
Core: Nucleus's description: "Core of the base. _**Extremely well armored.**_ Stores massive amount of resources."

Core: Nucleus's gameplay: **Dies instantly to nearby cores blowing up**

I don't know what your definition of "well" is but a core blowing up that easy is not "well armored" enough.
