### ISSUE TITLE
*A refinement solutions to increase Users' Experience

### ISSUE THREAD

**Issue by Whatisgitbuh** [Anuken/Mindustry-Suggestions#2057]
*I wish you would read it and adopting this idea would be best for me:D

 Hi. Im a user who is enjoying mindustry.
 I think mindustry is a game of highly great quality so that it has many unexpected details. However, to enhence users' experiencess, I think, not only specific details but overall graphics ormovements should be valued too.
 When drone constructing, A graphic indicates that the construction is being built fron edge to middle. This could be. It is okay. But thinking of other details of graphics in mindustry, This graphic is of comparatively low quality.
 So, I suggest that graphic indicator be remastered. It is REAL BUILDING GRAPHIC that replace the old one.
 Real Building Graphic (RBG) is literally showing the building processes simply. Its easy to understand imagining to build something in COC. But there is some difference with RBG im suggesting.
 First of all, constructions of Mindustry have to inform players how much theyre built. COC's simple graphic cannot notice players by the construction's shape. So, what should we do to get both UX and intuition? The answer is that: dividing constructing graphic three parts-basic construction, rebar construction, finalizing.
 For instance of water extractor, basic construction is digging hole, rebar construstion is making a main pump to pull up water, and finalizing is covering surface with painted cooper plates. Not showing real process but simplified motions.
 Mindustry is building game so building constructions is a huge part of play. So if constructing graphic is refined, users' experiences and recommendation will be much better. 
 I didnt intended, but the writing became too long with a small requirement. I wish you will manage mindustry for a long time, and thx to all of you to make such a awesome game. dd

**Comment by RedstonerKBC** [comment]
Here before anyone says "mods"

**Comment by sample-text-here** [comment]
1. it's not like this could be easily done by mods
2. why did you delete the template?

**Comment by Whatisgitbuh** [comment]
> 1. it's not like this could be easily done by mods
> 2. why did you delete the template?

Im sorry I didnt know that tamplate was not to be deleted. Im a stranger here. XD

**Comment by SheepCommander** [comment]
.... but why?
Anyways template here
```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```
please fill this out by editing your issue

**Comment by Kyllingene** [comment]
Problem 1: how do modded blocks cope with having to make their own construction sequence? Or do thorium reactors have the same internal workings as a tsunami turret, and thus the same animation?

Problem 2: think of how much *effort* would be spent on such a small QoL thing. Definitely not worth it.

Problem 3: *realism is a terrible reason to add things to Mindustry*

**Comment by Bohaska** [comment]
why does this feel like that someone wrote the suggestion in Chinese and used Google Translate to translate it into English?

And also

> but no, just no.

> No
> 
> Just no
> 
> That won't happen at all

> Still, no

>Mindustry is always an unrealistic game. Drills and conveyors run without power. You can infinitely respawn without material loss. You can actually drill for water on magma. Slag pools never solidify or cool down. 

> - [X] I have
>### not
>followed the template

>template be like: I am useless.
