### ISSUE TITLE
Trojan/Virus Processor - Logic

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#2059]
**Describe the content or mechanics you are proposing.**
This unit if could be planted in the enemy's base, it will connect to enemy's building and make harmful behaviors.
The traditional way to apply this is to use poly or higher to carry this processor, then in the right planned moment drop it in the enemy base (using logic or manually).
its features:
* Size: the same as microprocessor.
* Range: more than microprocessor.
* Color: the owner will see it in specific color, but the enemy will see it exactly like microprocessor.
* Superior: if there are two conflicted orders (ex enable/disable) coming from it and from normal enemy pro, its order will be implemented and cant be changed by another pro(s) as long as this unit still alive.
* Only one: The player can only have one of this unit, if destroyed he can build new one.
* Very aggressive: will auto connect to all connectable enemy buildings(exactly like node behaviour).
* Only PvP: it is not allowed in campaign.
* Can't connect to ally's building: can only connect to one memcell or membank, after establishing the connection with memory, it will not be lost if this pro is carried (map scope), it will be lost only if the player disconnects it.
* Can't read info: To prevent being OP, it can only send info to mem, but not read.
* None-detectable: not the turret nor the units can detect it as "enemy" unit, so they will not attack it, they will attack it only if the player does (or maybe using logic).
* Setup period: it will be so OP and silly if the player drops this unit in front-line and disables the turrets, so there should be a setup time until any connection becomes active, i think this could be something between (10-20) seconds.
* Timeout: after destroying this unit, things will not return to its normal state immediately, few seconds will pass before this happens, it could be instant done using logic.
* Default code: there is predefined code inside it which loop through all enemy's building using getlink and disabling them, so even people not good in logic can use it. ofc the player can delete this code and replace it with whatever he wants.
* other features i don't remember now, maybe in comments.

Using it:
1-As a virus: the traditional usage, disabling everything. huge harm, but easily detectable.
2-As a spy/Trojan: spying and gathering info.
3-Mixer of both: ex decrease the speed of conveyor,factory or turret..etc-but not disabling them(to prevent instant detection)+ gathering info. This requires complicated code and advanced knowledge in logic.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

New interesting addition to PvP Logic, without affecting the old stuff.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
I don't quite understand something: Is it a unit or a block? How do I build it if it gets implemented?

**Comment by Sector171** [comment]
Apparently it is a block, within logic group similar to microprocessor, it is clear, but I used "unit" term sometimes to refer to it since "unit" word could be used this way never expected this might mislead someone.
To use it: just build it, write code inside it, then use poly or mega or.. to carry it and drop it in a specific location in enemy's base.

**Comment by GreyMario** [comment]
No.

**Comment by Sector171** [comment]
> No.

Very very very useful comment.
You can just thumb down.

**Comment by Humanoid-X** [comment]
Too OP. No.

**Comment by Thankyou69** [comment]
so you want a processor... that connects to enemy buildings? do you have any idea how much damage this would cause? you could make them thorium bomb themselves, you could kill all their u its do that they cant attack, this would be too overpowered even with limitations. this is a hard no from me

**Comment by Sector171** [comment]
This pro can't control enemy's unit. that's for sure.
OP, maybe that's very possible ofc, but ADJUSTABLE, only tests can draw the limits. We can't judge saying "even with limitations it will fail". Without tests.
But why?! Does this idea deserve? İn my opinion, VERY, it will add a lot of new plans & strategies, and diversity in game play.

**Comment by Thankyou69** [comment]
> This pro can't control enemy's unit. that's for sure.
> OP, maybe that's very possible ofc, but ADJUSTABLE, only tests can draw the limits. We can't judge saying "even with limitations it will fail". Without tests.
> But why?! Does this idea deserve? İn my opinion, VERY, it will add a lot of new plans & strategies, and diversity in game play.

its just not gonna work, so many things could happen, its not worth it

**Comment by Sector171** [comment]
> its just not gonna work, so many things could happen, its not worth it

Thanks for your productive comments, I respect your opinion but disagree with it, at least partially.

Actually the big challenge in this idea is: how to plant this pro successfully without attracting the attention?! Lot of games has such a powerful tool, which is too hard to implement, so you basically should prevent your opponent from doing so, which is easy task.
On the other side, for the attacker, finding tricky and an unexpected plan to plant it is the challenge, also another challenge could be the "correct code" (since the code can't be changed after activation).
You mentioned to thorium Re, there are a lot of possible harmful codes selecting the appropriate one is a thing, do the enemy use reactors or not? Where are these reactors if so, are they easily reachable or not? ..etc
Actually this exactly the point of this suggestion, new tactics and game play.

**Comment by joshuaptfan** [comment]
Building blocks in enemy territory is actively discouraged by the game, by such mechanics as the enemy core no-build radius, and the frailty of blocks under construction.

This suggestion seeks to encourage building in enemy territory, which goes against that.

**Comment by Sector171** [comment]
> Building blocks in enemy territory is actively discouraged by the game, by such mechanics as the enemy core no-build radius, and the frailty of blocks under construction.
> 
> This suggestion seeks to encourage building in enemy territory, which goes against that.

We are talking about only one exceptional 1*1 block, just one, which is part of its nature to cheat the player and pretend as if it is part of his blocks. I don't see any real conflict with "no-build radius" rule.
Anyway ty for mentioning to this point.

**Comment by RedstonerKBC** [comment]
You don't need a new unit/block to pull this off. All you need it a malware program and someone willing to switch teams to build the processor. Don't worry about "last accessed" giving you away (it's not like it ever helps anyways) because you'll destroy the processor right after. This is a complicated way of attacking/griefing but I've seen it done before.

**Comment by Thankyou69** [comment]
^

**Comment by G0nTar** [comment]
People keep asking for these weird things that are just OP o break core game rules and mechanics like the Base no-build radius...

If you rly want to turn the game into bananas Mode, just go get a mod/plug in that bet aka the game, there's many, and if your today's mood for bananas isn't there, learn how to make your own.

Everybody already ady told you, with perfect reasoning and manners that you are taking a dump directly on top of the game, if you are just shouting it doesn't work you have to listen too, close this pls

**Comment by BlackDeluxeCat** [comment]
Virus processor is op than the bug that enables reading & writing enemy cell. 
Also, spy can be done using normal processors.
