### ISSUE TITLE
Map Display Colors

### ISSUE THREAD

**Issue by mocyhomes** [Anuken/Mindustry-Suggestions#206]
**Describe what you would like changed, and why.**
Currently on the map every building or structure placed is the same color. this is strange to look at and difficult to see what buildings are there without going and looking.

**Describe the changes you want to propose. Include possible alternatives.**
if at least in the campaign if the different building types had different colors it would help with the readability of the map screen.

**Comment by Anuken** [comment]
This is necessary to distinguish teams.
