### ISSUE TITLE
Ammo manufactoring

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry-Suggestions#2061]
**Describe the content or mechanics you are proposing.**
What if you need to manufacture the ammo rather than the turrets using it raw. Turrets will still work with raw materials like they used to, but manufactured ammo can have bonuses, such as minor homing, or explosions on hit. the factory to make the ammo will take 50 lead and100 titanium to make. and it'll need a constant stream of either thorium or 50 power units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make the game slightly fun as you can have variations of ammo to use.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
   4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nichrosia** [comment]
> make the game slightly fun

Even in the game wasn't already fun, the reason for a feature should not be "just because it's fun".

In addition, this would add more unnecessary items and liquids, with very little purpose. Also, Mindustry already has "manufactured ammo". Graphite, Silicon, Pyratite, and Blast Compound.

**Comment by itcannotbe** [comment]
If I recall correctly, this idea isn't new and has been shutdown by the dev multiple times already as it just adds unnecessary bulk to the game.

**Comment by Neil2101** [comment]
ok then, i'll shut the issue

**Comment by Kyllingene** [comment]
Look into "Real Life Mindustry", it's a mod that has a bunch of realism bits, such as turret part manufacturing, and yes, ammo manufacturing.
