### ISSUE TITLE
If the unit commanding a group dies being still in controll of the units.

### ISSUE THREAD

**Issue by NumericPrime** [Anuken/Mindustry-Suggestions#2063]
**Describe the content or mechanics you are proposing.**

Currently if you controll a unit and command other units and the unit you controll dies you don't command the other units anymore.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Especially on attack sectors with a high difficulty you'll take heavy loses and losing controll of your group attacking usually results in the attack failing.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by CountSudokku** [comment]
Its especially painful with close range units like quad or arkyid. I would be happy if it will be fixed.
