### ISSUE TITLE
Offensive Support Units

### ISSUE THREAD

**Issue by zyraviz** [Anuken/Mindustry-Suggestions#2065]
**Describe the content or mechanics you are proposing.**
An offensive type of support units, you can acquire them by upgrading(or rebuild?) polys with a special type of reconstructor. There are 3 of them:
- a unit version of repair point. because this might be a bit op I suggest that they must require ammo to be working (to recharge it you must go to a repair point).
- a unit version of parallax. Useful to easily drag those moderate range units. It's also a bit op so I suggest to make the range smaller than regular parallax.
- a "wall" units. It has a moderately high defense but the size is similar to polys. Because it's relatively small, to make it efficient it has to be orbiting the player like the classic draugs(for accurate representation, you can search "titanium armour" from terraria).

**Honourable mention**
- a unit version of segment. Because this is too overpowered i decided to put it in **honourable mention**
- a flying weapon unit. this is supposed to be an extension (basically it's just a flying turrets)

All of these units only working when a player controlled them(I mean like control to surround the player).
There's only T1(or T3 because it's an upgraded polys I guess) for all of these units so you can't upgrade them.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
A better experience for PvP (or even just regular survival in my opinion).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
isnt the entire nova tree already offensive ground support?

**Comment by itcannotbe** [comment]
Now I want Supportive Offense Units.





That doesn't make sense right?
If yes, by extension this suggestion too.

**Comment by zyraviz** [comment]
> isnt the entire nova tree already offensive ground support?

Yes I know that. But they can only heals or making shield  and I'm thinking that a whole new type of support gonna be interesting. I mean like shield isn't effective for continuous damage since they can't regenerate if spammed by many damage or the only way they can heal units is "waves"

**Comment by Bohaska** [comment]
>Incredible. **Nobody** has ever even considered suggesting more units before. This is a revelation. I would never have thought of adding this myself. This idea is so _revolutionary_, so _clear_, so _simple_ that absolutely no further explanation is necessary. I will now go and implement this _amazing_ suggestion immediately.
