### ISSUE TITLE
Seasonal competition - New type of gameplay

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#2066]
**Describe the content or mechanics you are proposing.**

This is more a long-term project than new feature, since it requires 1-huge efforts 2-$$$(maybe) 3-real dev team. I dont know number & effectiveness of volunteers working with you, so i'm not sure if it is doable for now or not, but even if not this idea is something in pocket if changes happen to funds.
Since the topic is too long, i will explain the main idea here, then go a little bit in some details in the comments. let's go(the numbers mentioned below are just examples to explain the idea):
* The idea:The last upgrade in the tech tree to unlock will be lets say "Galaxy teleporter", it will be unlocked exactly after finishing the campaign, the translation of this upgrade is unlocking the seasonal competition, so we garantee that eligible players who may participate: 1-have a good knowledge in mindustry 2-like and have patience to play strategically since they already finished the campaign.
* The seasonal competition is a clan-based strategic game, there are 2 seasons per year, but one season needs one year to end.
* Each 100 players will constitute one server, each 10 players will be in one clan. So each server has 10 clans. Each server is isolated from others.
* The server has 3 tiers of planets: tier1--> 3 planets, tier2--> 2 planets, tier3--> one planet. All players will start at a sectors in tier1 planets(33+33+34)/(3+3+4 each clan).
* How to play: Higher score means higher rank, the main way to gain score is "Domination", the more sectors your clan captures the more score you gain, you will get a specific score per unit of time for every sector you have. There will be 33 players in each t1 planet, so most sectors (85-90%) are empty, not really empty but rather occopied by AI enemy base. First the fight will start against AI, then against other clan's members.
* There is special tech tree for this competition, one at player level another at clan level. After few achievements & gathering points, the player can launch to t2 planets, then t3.
* The competition will end after (5.5) months, the winner (highest score) will get a title "Galaxy Master". 2 weeks later the "Cosmic competition" will begin, the first X clans from each server will be chosen to participate, the X could be only first one, or first 2 or...etc based on the schedule , so new rounds will start, but ofc it is shorter here and maybe only in one planet, and again we take the first X clans and so on, it could be 5-6 rounds in 6 months, the point here is the competition must end after 6 months, the winner will get "Universe Master" title.
* The clans which failed to participate in "cosmic competition", can immediately participate in the new season(as mentioned there are 2 seasons per year, each one needs one year). The clans which get kicked early from the cosmic competition can't participate in the new season since it already started, but what players can do is leaving their clan and look for any available place in any clan and play, this could be temporary(when new competition starts they come back to their orginal clan) or permanent as they wish.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Mindustry is much more strategic game than tower defense, we have campaign but it is single player, PvP is just a fast match.
This idea will give players a chance to play strategic, within a team.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Sector171** [comment]
Planets

Planets: i will talk more about Galaxy competition, as mentioned there are 3 tiers: t1: 3 planets, t2: 2 planets, t3: one planet. Each sector in each tier gives a slightly different score/time unit based on its importance, generally sectors in a higher tier give more score/time, for example if t1 sectors give score vary from (60-75)/time, t2 could be (70-85)/time, t3 (80-95)/time. Time unit could be 4 hours, 3 hours..etc.
* Resources: t1: rich in basics res, and scrap, very rare titanium, no thorium at all, the only source of thorium is scrap.
           t2: rich in titanium & thorium (ofc relatively i.e rich in thorium=low in basics), low to moderate in basics.
	   t3: very poor planet, some sectors has nothing except water, the main source of resources is from t1,t2 planets(interpalentary launchpad). But this planet has everything including thorium.
* Start sectors: it is not good to have identical start sectors for "balancing", it is fine to be distinct and a little bit different, but has similar features, ex for sure the start sectors cant have titanium. These sectors are immune to any attack(whether AI or player).
* AI: i think it is better to be all "enemy base", in t1 medium and higher, t2 high and higher, t3 high and higher lot of them extreme & eradication.

**Comment by nichrosia** [comment]
This does not fit the theme of Mindustry *whatsoever*. You are proposing to add official campaign servers with *clans*, and make the campaign *multiplayer*.

**Comment by Sector171** [comment]
Clans

After fininshing the camapaign, "Galaxy teleporter" upgrade will be unlocked, which unlocks seasonal competition, to participate the player first should be part of a clan, there are 2 ways to do so: 1-random: he just determines the setting such as languages--> then search--> join. 2-planned(better choice): the players in different communities like Discord & Reddit ...etc meets each other and agree to be part of one clan, the minimum number of players required to do so is 6 (6 requests).
As you can see the clans here not like other games where the player can make a clan then add new members..etc, here the clans are predefinied, and no one can own a clan, there is a voting system to solve the problems including kicking members, reports, admins control the clan's problems(not allowed to make a gang, voting is not the final thing). There is chatting system (written & voice, ofc not like PvP, but much better), helping tools for tasks and plans.
There is a clan's leader, it is the player with the highest points(what did he gain from all old competitions), but he has no important permissions, it is more "honorary" position. In voting system it is proportional to player's points (opnions of more experienced players have more impact).
Permissions: one of the most important point in clans, unlike campaign, here the game is ongoing 24/7, you cant prevent the others from attacking you the moment they want which may not ok for you, ofc there is a notification system for mobile & PC, but people have their own life. So the player can give the permissins to other (or all) clan's members to manage his stuff if he is offline(it is something different from "account", no one gives his account to anyone else, but a permissions to control his factories, units, resources..etc). The player can determine the type of permission(s) for each member in his clan. ofc he can disable this feature but this is not a good idea.
For clans which has less than 10 members, actually there is still 10 accounts, the clan's members can manage these missing accounts until someone join.
Inactive players: not necessary the players who havent been online for a while, also if a player plays everyday but not doing important thing is considered "inactive", there is player's pointing system for achievements(attacks, defend, production..etc), if it becomes below a specific level1 per time --> 50% or more votes enough to kick him, if below level2 only one vote(10%) enough to kick him out, so that the clan may get new active player, or at least the clan members can manage his stuff(if he was preventing that).
Exchange resources: between clan's members allowed but at very low rate. it is also possible to exchange sectors(which is better), or even give up a sector.

**Comment by nichrosia** [comment]
And due to that, it has basically 0 chance of being implemented.

**Comment by DeltaNedas** [comment]
> IF YOU DONT LIKE IT, DONT PLAY IT. you can still play everything else as it is.

if anuke doesnt like it, do you think he is going to drop all of his v7 ideas and implement this fortnite/clash of clans/whatever thing?
go make a plugin instead

**Comment by Sector171** [comment]
> And due to that, it has basically 0 chance of being implemented.

Nothing new, i already know it is hard to be implemented and said that at the very beginning of my topic, but don't be so sure about this "0 chance", maybe only for now.
>if anuke doesnt like it, do you think he is going to drop all of his v7 ideas and implement this fortnite/clash of clans/whatever thing?
???ah really? i expected to see it tomorrow in the store!!  did you see any mention or suggestion to remove any of preexisting features?! i said it is a long term project, ofc he shouldn't drop anything but this could be something to think in after that and if a significant changes take place in logistics(funds/team).

This game is very strategic one it has all infra-structures to be one (factories-resources-complicated items production-units-logic...etc) we know this very well from campaign, more than most of real strategic games.
The question is: is there any real reason prevents such addition to this game? taking into account that IT WILL NOT AFFECT THE OLD STUFF, not being so from beginning not a reason.
I'm not familiar with this game history because I've played it since few months only(v6), so i wonder was there PvP since the first release of this game? was there Logic? was there...etc or such a huge ideas got added later?!
Best..

**Comment by G0nTar** [comment]
> > IF YOU DONT LIKE IT, DONT PLAY IT. you can still play everything else as it is.
> 
> if anuke doesnt like it, do you think he is going to drop all of his v7 ideas and implement this fortnite/clash of clans/whatever thing?
> go make a plugin instead

I have to agree with this person. 
You asking to add a clan battle thing, that adds like creating a new Mindustry of work and effort and.. Putting it simple so you understand it:
-it's like asking your parents to give you a Pont and a Stable, and a knight armor so you can battle it out with your friends..

Its not something your fathers are planing for you, not that they can afford it, and if you someday grow up and still want to do that weird stuff, you can go make it happen yourself, or create a team to do it, you can ask ur parents for a pony, but not every parent wants a Pony on Their House.

**Comment by Sector171** [comment]
Thanks God that there are very few people (less than 1%) who can think out of box, otherwise the human being would still live in caves.
"hey why do you ask for this weird thing called "Matches" to set up fire, we are doing so using sticks and stones and we are fine with that, go and do something useful"
If we have a look at any successful thing (windows, google, a lot of games...etc) how did it begin, and how did it become later...

**Comment by Kyllingene** [comment]
Somehow, I don't think that comparing humans getting out of caves to people not liking a new gamemode makes sense.

**Comment by Sector171** [comment]
> Somehow, I don't think that comparing humans getting out of caves to people not liking a new gamemode makes sense.

ofc, that's for sure 100%. except you made the wrong comparison.
The correct comparison is between new good creative idea(yeah it is and i can defend it very well, being applicable or not is a different story) and amount of hate, trolling , jeering against it.
if someone want to jeer, that's fine but should know well what he is doing and use his brain if the other side has well structured idea, otherwise he will find himself in a very bad situation.
I wonder, why people in this community that bad? why they don't use the respected useful manner you use when criticizing?

**Comment by Sector171** [comment]
Haha, it looks that I'm not the only one who has such a "stupid" idea.

https://github.com/Anuken/Mindustry-Suggestions/issues/2072

**Comment by Cherriodude** [comment]
I think you're missing the point here. It does not fit in the vanilla game or campaign whatsoever. Let's compare Minecraft to it, if one person suggested they add a battle royale mode would they add it? No. They have money and real dev team but they still won't add it because it does not fit the game.  You're trying to add seasons, clans and official supported multiplayer. Point is it does not fit the game.

**Comment by Humanoid-X** [comment]
@Cherridude Well said!

**Comment by Humanoid-X** [comment]
That's the reason I dislike most mods. They don't improve the game, they change the game.

**Comment by Sector171** [comment]
> I think you're missing the point here. It does not fit in the vanilla game or campaign whatsoever. Let's compare Minecraft to it, if one person suggested they add a battle royale mode would they add it? No. They have money and real dev team but they still won't add it because it does not fit the game. You're trying to add seasons, clans and official supported multiplayer. Point is it does not fit the game.

Believe me, I do understand this point very very well, it is your opinion and I respect it ofc, but disagree with it, not only I believe it fits it very well, but also I see its future in it( if this game someday would be a big thing for sure there should be great logic stuff + clans). I asked this before, so I repeat - except the logistic obstacle -
> is there any real reason prevents such addition to this game?
İs there any explainable reasons & obstacles ?? Saying it doesn't fit is just an opinion ok I respect it but not supported,  where is the meat? I need meat, something like : if we add this idea this means bla bla bla which requires bla bla bla and leads to this problem.
I'm pretty sure if this idea get implemented someday, those people who criticized it will be the first ones who play & enjoy it.
Why do I feel that the people misunderstood it a little bit, there is no relation between campaign and it, it is just an advanced game mode will unlock only if a player finished the campaign, to guarantee that who will participate has enough exp, noobs not allowed to be in. Also it will not affect any preexisting things like campaign, PvP, sandbox...etc, it is just an advanced extra game mode.

**Comment by Bohaska** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2053 used to suggest a feature similar to it, but it got tons of criticism so I changed it. 

> advanced extra game mode

New revolutionary game modes that aren't urgently needed are better suited to mods that insert them into the game instead of being added to vanilla mindustry.

**Comment by Bohaska** [comment]
>hey why do you ask for this weird thing called "Matches" to set up fire, we are doing so using sticks and stones and we are fine with that

and if you want to use matches to set up a fire then go and get one yourself instead of asking anuke to get them for you.

**Comment by Sector171** [comment]
Oh, wasn't that blockchains thing, tbh I didn't like it at all(partially because I didn't understand it well), also for money and skins issues.

But what I did see now is really nice idea, so don't listen to haters it is good idea in its current format, and your justification for it is exactly what made me do this suggestion
> 2. It's a way of making sure the community sticks to Mindustry and continue to love it.

I finished the campaign (after developing some logic stuff even eradication bases became easy for me), and I am not fan in PvP but I like the concept of this game too much so... -->suggestion.
Even though it is a different enough(clans and so) but swims in the same pool.
I think my idea is better but yours is more practical and much easier to apply and fits mod. Mine doesn't fit mods at all(very hard) because it needs central servers and direct support from Dev rather than client-side servers like yours.

So there are 3 ideas about multiplying in less than one week, hmm the cook being cooked.

**Comment by dheld** [comment]
My main objection is the scale.  I have no idea what Anuke is planning for planets, but just talking about enough servers to support 100 concurrent players is a problem.  I would be happy if the folks currently playing could simply opt to play together on the same planet with sector interactions.  I'm pretty sure a 1-man shop is not going to build out a server farm...
