### ISSUE TITLE
Making drills conduct coolant to nearby drills

### ISSUE THREAD

**Issue by Valentin-Metz** [Anuken/Mindustry-Suggestions#2067]
Cooling resource extraction is currently very tedious to set up.
I propose that mining drills should transfer fluid to nearby drills.
(Similar to how the uranium miners in factorio conduct sulphuric acid)
This avoids unnecessary cluttering, integrates nicely with the fluid system and allows "cool mining drills" to go more in the same direction as "power mining drills".
It encourages cooling without making it annoying to set up.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Use larger drills.

**Comment by itcannotbe** [comment]
Also the minor annoyance of setting up something that occupies a width of 1 tile magically makes drills produce 1.56x more items?

It's kinda balanced if you ask me.

**Comment by Valentin-Metz** [comment]
The bonus could be adjusted. The problem (even with large drills) is that you want to place them adjacently to each other. If you want to cover your entire field optimally you'll only leave one side open for the conveyor. If you want to add water you'll have to wave it in tediously with the resource conveyor.

**Comment by itcannotbe** [comment]
How annoying can a line of 1x1 blocks could even be when your getting more than thrice more items in return?

**Comment by Valentin-Metz** [comment]
This is not an annoying vs reward suggestion. The bonus you actually get can be fine-tuned. The point is that drills are already hard enough to fit onto the resources without leaving spaces blank. Cooling should be rewarding for all drill types, not just the largest. Manually waving conveyor belts and pipes constantly for basic extraction only isn't too much fun either.

**Comment by joshuaptfan** [comment]
This suggestion is simply OP. It's all reward and no risk.

**Comment by RedstonerKBC** [comment]
Just in case conduits needed another reason not to be used ever

**Comment by Slava0135** [comment]
no
