### ISSUE TITLE
Surge Power Reactor

### ISSUE THREAD

**Issue by smolkaguya** [Anuken/Mindustry-Suggestions#2069]
**Describe the content or mechanics you are proposing.**
Since surge generate electric arc when interacted with something (surge walls generate electricity when it being attacked by enemies), we can use it to produce electricity. 
![Screenshot_2021-03-02-00-34-10-03_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/77297413/109528397-9590cf80-7aef-11eb-8840-7fc258831aec.jpg)
This is inside of it. The arc will shoot at the surge and the surge will produce more electric arc. The plastanium wall will bounce the arc back to the surge and the surge generate more electric arc and the cycle continue. As more arc hit the plastanium wall, it get hotter. That's when the cryo comes to place. It will cool down the  plastanium wall. The logic is whenever there is cryo failure. It will command the reactor to release large amount of power straight to the sky in form of a beam similar to meltdown thus shutting down the reactor. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It can create more opportunities for a new endgame turrets that use large amount of power thus enhancing the experience during the endgame. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
Mods.

**Comment by smolkaguya** [comment]
@BlueWolf3682 nah. This will generally be used in multplayer.

**Comment by BlueWolf3682** [comment]
nonetheless, ***Mods.***

**Comment by smolkaguya** [comment]
@BlueWolf3682 i do still think this need to be added because in multplayer people use alot of power.

**Comment by BlueWolf3682** [comment]
make better power.

**Comment by smolkaguya** [comment]
@BlueWolf3682 this can be space efficient you know.

**Comment by smolkaguya** [comment]
@BlueWolf3682 you usually comment "Mod"  because you find something that doesn't fit the basegame. My idea is just a reactor that use surge and cryo as fuel. Why you think it doesn't fit the basegame?

**Comment by BlueWolf3682** [comment]
Because impact reactors are already good enough, and we really don't need more power generating options in the basegame.

**Comment by Sukhoi-s25-sunday** [comment]
a surge reactor would be nice tho

**Comment by smolkaguya** [comment]
@BlueWolf3682 this reactor isn't gonna come by itself. Let's say anuke want to make a major update about turrets and he/she add more electric based turret that use large amount of power in future update. He/she need to balance it out by adding new reactor. Since the update was primarily for turret, Anuke didn't want to bother her/himself to add many power generator so she/he added this reactor. 


Like i said in the post, this Reactor can give opportunity for more turrets/features to be added.

**Comment by BlueWolf3682** [comment]
***which is what mods are for!***

**Comment by smolkaguya** [comment]
@BlueWolf3682 like i said, this can open a new opportunity for a new features that use electricity. This game isnt gonna rely on mod itself. If dev added more features that requires electricity,  they will add more things to produce electricity. This is the thing

Constructive criticism please instead of spamming mods everywhere like a fucking troglodyte

**Comment by BlueWolf3682** [comment]
so you expect anuke to add a half baked idea that doesn't belong in mindustry just because you cannot make more than a few hundred power for the life of you. Get good.

**Comment by smolkaguya** [comment]
@BlueWolf3682 I can make power on my own. *This suggestion is for future updates when anuke want to add new feature that require electricity.* I have said this for the fourth time. I've never said I want it because I can't make power. Anuke already place the hydroelectric idea to the shelve which mean it not gonna happen.*This reactor isn't gonna come by its own*. There i said it again.  

Wdym this doesn't belong in mindustry? superweapons, or orbital bombardment idea belong to Mindustry but this isn't? It's just like the impact reactor but use surge instead.

**Comment by BlueWolf3682** [comment]
I say "mods." to *any* idea that I feel does not belong in mindustry.

**Comment by smolkaguya** [comment]
@BlueWolf3682 your point?

**Comment by BlueWolf3682** [comment]
Mods. For orbital bombardment to surge reactors to nuclear waste. Mods.

**Comment by smolkaguya** [comment]
@BlueWolf3682 what about multiplayer?

**Comment by BlueWolf3682** [comment]
Stop pinging me.

**Comment by Kyllingene** [comment]
I fail to see why the Surge Reactor is a necessary suggestion. "Oh, it's for later" is a bad excuse as Anuken is smart enough to figure out that he could make a bigger reactor if needed.

**Comment by smolkaguya** [comment]
@BlueWolf3682 alright then. The conclusion for this arguement has been decided then

**Comment by BlueWolf3682** [comment]
and as always, you can add it in a mod if you so choose to

**Comment by Kyllingene** [comment]
Also, is the picture shown how you *build* the reactor, or simply an example of how its internals would work? If the latter is the case, is it actually 20x20?

**Comment by smolkaguya** [comment]
@Kyllingene it's how the internal work.

**Comment by smolkaguya** [comment]
It has surge input

**Comment by Kyllingene** [comment]
Is it actually 20x20?

**Comment by smolkaguya** [comment]
Nope. It will be 4×4

**Comment by Kyllingene** [comment]
***4x4***?!? That's tiny for an endgame power production facility!

**Comment by Kyllingene** [comment]
Also, how much cryofluid, power, and surge would this thing take?

**Comment by smolkaguya** [comment]
I think 1 surge to generate 25k, 15 cryo fluid is fair enough

**Comment by smolkaguya** [comment]
The impact need 15 cryofluid persecond so i think it's fair

**Comment by Kyllingene** [comment]
Wait, so 1 surge = 25k power? And it only takes as much cryo as an Impact? *And* it's the same size? ***And*** it doesn't seem to have any power consumption like the Impact does? Reconsider the stats please.

**Comment by smolkaguya** [comment]
Hmm perhaps it need to be bigger. And require more cryofluid. What about 6x6 and need 20 cryofluid persecond

**Comment by smolkaguya** [comment]
And the starting power similar to impact

**Comment by Kyllingene** [comment]
But it still takes 1 surge to create 25k power. How long does that process take, by the way?

**Comment by smolkaguya** [comment]
Per 30 second

**Comment by Kyllingene** [comment]
The Impact Reactor generates 4050 power per blast compound, and takes 1 blast per 2.7 seconds. This, however, generates ***25k*** power, an absurd amount, for just 1 surge, and takes 30 seconds. That is ~833 power per second. The Impact generator makes 1500 per second. This is either overpowered or underpowered, I have no clue which.

**Comment by smolkaguya** [comment]
Hmm i guess 5second? Is that fair?

**Comment by Kyllingene** [comment]
Wait, making 25k power per 5 seconds sounds a little problematic. That is 5k power per second, an absurd amount only remotely necessary for the never-to-exist super-mega-insane weapons. Maybe 6000 power per surge, 3 seconds per surge? That puts it at a more modest 2000 power per second.

**Comment by smolkaguya** [comment]
Yeah 3 second fair

**Comment by Bohaska** [comment]
> but no, just no.

> No
> 
> Just no
> 
> That won't happen at all

> Still, no

>Not everything needs to be turned into electricity

From https://github.com/Anuken/Mindustry-Suggestions/issues/2053

**Comment by BlueWolf3682** [comment]
bohaska, please leave

**Comment by Bohaska** [comment]
> bohaska, please leave

When you did it to my (bad) suggestion you didn't raise a finger

**Comment by BlueWolf3682** [comment]
because your suggestion was worse than this one by for. now, go away.
