### ISSUE TITLE
Improved Silicon Smelter, Upgraded Draug Drone

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry-Suggestions#207]
**Describe the content or mechanics you are proposing.**

A silicon smelter that is faster, but requires more resources and power
A drone that can mine higher tiers of ore, but requires more resources to build, maybe 10 titanium, and some silicon

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

make silicon slightly easier to get, as it is currently very irritating to get silicon by making arrays of silicon smelters.
Having better mining drones would improve the game by allowing autonomous mining of thorium and titanium, without drills.

Anyone who finds a major problem with my request, like the drop pad - launch pad teleporter, please notify me in the comments.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Both of these are already on the Trello.
