### ISSUE TITLE
Overclocking addon (Meltdowns and More)

### ISSUE THREAD

**Issue by Sukhoi-s25-sunday** [Anuken/Mindustry-Suggestions#2070]
i had the idea of having a overclock cap of 1500% but if we were to have that fast of a clock speed generated by Overdrive domes there has to be a debuff right? Yes My idea entails
take a fuse turret max out the clock speed and add 1500% FAST Right 
Now any clock speed over 250% faster than normal clock  (1X clock is the default turret or drill speed without any buffs Eg Cryo Fluid in a foreshadow turret) will begin to heat up and eventually either CEASE FUNCTION or EXPLODE.
This adds challenge to having to balance weapon fire rate with their survival 

Additional notes

1500% is huge i just said it a proposed number

Cease function can be repaired but not by menders the player will have to have to repair the damaged entity 

Explosions release scrap and shrapnel causing area damage up to 10% total health in any entity in a 40 block radius

Additional notes 2
Don't just downvote provide a response i might just make it a mod

**Comment by Sukhoi-s25-sunday** [comment]
i see i have someone confused if you could explain where i messed up @Jammo2000

**Comment by joshuaptfan** [comment]
1. It's OP.
2. Self-harming mechanics (exploding your own turrets) are terrible drawbacks.

So, looking at risk vs reward, the reward is OP, and the risk is just plain bad for players. Overall, this suggestion is tOtaLLy XtrEmE and... just a bit much.

**Comment by Sukhoi-s25-sunday** [comment]
> 1. It's OP.
> 2. Self-harming mechanics (exploding your own turrets) are terrible drawbacks.
> 
> So, looking at risk vs reward, the reward is OP, and the risk is just plain bad for players. Overall, this suggestion is tOtaLLy XtrEmE and... just a bit much.

In additional notes i said 1500% was a number not a defining variable and the explosion would cause damage to defence arrays as a debuff for keeping it at a "unstable" clock for too long.

**Comment by Sukhoi-s25-sunday** [comment]
and the risk reward is you get a HEAVILY BUFFED TURRET(s) when you need them the risk is if players abuse the clock speed it causes turrets to cease function or you know EXPLODE due to heat like shotguns trying to become machine guns firing that fast causes barrel heat and too much barrel heat causes a weapon to cease adds a bit of realism also it doesn't effect the base clock of a overdrive dome 250% only anything above it caping out at 450% i guess.

**Comment by joshuaptfan** [comment]
Also, block upgrading is something that Anuke has said will never happen, and the overdrive projector/dome already exists for boosting block speed. Any other mechanic to boost blocks would just be infringing on overdrive's territory.

**Comment by Sukhoi-s25-sunday** [comment]
i guess that seems correct ill close issue
