### ISSUE TITLE
set drop zones to different teams & pick waves for them

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2071]
**Describe the content or mechanics you are proposing.**
Right now, in a survival setting all you can do is defend against the crux with the sharded team. but would'nt it be cool to play as the green team and fight off the blue team?
my idea is to let us customize individual drop zones. how this would work is, you'd be able to click a spawn in the editor, and if you click the "open menu" button that shows up, it displays the waves and the team it spawns. all of these can be altered individually. this would also mean the removal of the waves button in the map settings.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it would open up lot of creative opportunities for map makers! you could have two teams which spawn waves at each other, play an attack map where you get a small unit boost here and there, etc. there's lots of things you could do with drop zones that are not just crux.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheRealIvyX** [comment]
imo the wave menu shouldn't be removed but instead have the waves set in the wave menu be the default waves for newly placed drop points

**Comment by sup3r87** [comment]
> imo the wave menu shouldn't be removed but instead have the waves set in the wave menu be the default waves for newly placed drop points

that's a good idea too! maybe you could copy + paste drop zone settings between drop zones

**Comment by AtobaAzul** [comment]
I was about to suggest the same thing, I like this!

**Comment by SheepCommander** [comment]
I also like this

**Comment by itcannotbe** [comment]
-[X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
Basically the offspring of #325 and #1436

**Comment by sup3r87** [comment]
> Basically the offspring of #325 and #1436

i'd argue this adds some more things into the idea mix but yes i should have dug deeper before typing my suggestion

**Comment by SheepCommander** [comment]
No you didn't have to. I agree with you
