### ISSUE TITLE
Just An Idea for a new air unit category

### ISSUE THREAD

**Issue by Qwertly-boop** [Anuken/Mindustry-Suggestions#2073]
**Describe the content or mechanics you are proposing.**

A completly new category for the air factory. I present to you, the electronic air units.
 TIER 1
item used to make: 15 silicon, 10 metaglass.
Name: Levi
health:150
Weapon: laser turret
Damage: 15
Bullet: Arc shock thingy
2 turrets on the side.
Shoot speed: 1/0,7s
Armor: 0
Speed: 2
Flying: yes for all
range: 11
Command limit: 4
item capacity: 30
Special: it can store  2k power by connecting it self to a nearest node in reach that has a free space. if the power is positive it will act like a baterry and store it. Incase its negative it gains nothing or loses power like a simple battery. after getting outreach of a node it will have the battery saved but wont gain unless connected again.
TIER 2
Name:Ulkin
health:400
Armor:3
Speed: 1.5
range:21
Command limit: 6
item capacity:40
Weapon:Energy Blaster
Damage:30
Bullet: energy ball
shoot speed 1/1,8s
Weapon:laser turret
Damage:15
Bullet: arc shock
2 turrets.
shoot speed1/ 0,7s
Special: Baterry can now save up 5k power, and you have a solar panel attached to the plane producing 5/s power
TIER 3
Name: Havinda
health:750
Armor: 6
Speed: 1.3
range:18
Command limit: 8
item capacity:45
Weapon: Energy laser
Damage:65
shoot speed 1/2s
Bullet: lancer laser
Weapon: energy ball
Damage:32
Bullet: energy ball
2 turrets on the sides means more fire speed.
shoot speed 1/0,9
Special: Baterry can now save up 10k power, and you have a solar panel attached to the plane producing 10/s power

This is only an example obviously lots of reworks would have to be made. this is only an example of what of an idea i have for the 3rd category air. If Anuke does get intrested we would have to work trough all the units and mechanics.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A small occuring problem where you have a place where it needs power to start the power. and have no silicon to make solar panels. these planes could also help out saving spaces by being emergency batteries. Aswell as

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nichrosia** [comment]
**Mods.**

**Comment by nichrosia** [comment]
Also, just a tip, the core database entry for titanium says it is used in aircraft, so you might want to add that.

**Comment by RedstonerKBC** [comment]
While we're add it let's add "any new game content" to the list of things you shouldn't suggest

**Comment by RedstonerKBC** [comment]
Having a unit that can store some backup power when your batteries get destroyed seems useful actually. It's different than the mega-line's ability to carry payloads since the power is stored in the unit not the block. It's not too op either and can defend itself.

**Comment by Phinner** [comment]
> Having a unit that can store some backup power when your batteries get destroyed seems useful actually. It's different than the mega-line's ability to carry payloads since the power is stored in the unit not the block. It's not too op either and can defend itself.

Best idea I've ever seen in *suggestions* lol, ngl.

**Comment by Thankyou69** [comment]
i have been looking forward to a purple-class air unit, ground has orange, green, and purple, why not air, and ships are there own class

**Comment by Bohaska** [comment]
I have been looking forward to a `<span style="color:blue">*blue*</span>`-class air unit

**Comment by Bobbystevenson** [comment]
This is actually a really cool idea, but the T4 and T5 versions should mabye have an extra ability to go along with the battery things
Also, mabye when these units fall the shoot out bursts of electricity, like a surge wall

**Comment by Qwertly-boop** [comment]
You know, Its not only usefull for storing power in itself. If unit requires ammo is on it could suply itself in combat 👀.
And for the T4 and T5 units i have a intresting idea with the power stored in it. So even without needing ammo. You can still use it in combat 😉

**Comment by Qwertly-boop** [comment]
> **Mods.** ~hmm these stats might be useful~

If you wanna make one hit me up.
