### ISSUE TITLE
Editor, minor QoL upgrade

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2075]
**Describe what you would like changed, and why.**
When you quit the editor, the confirmation message that asks if you want to exit and warning you about unsaved changes should only appear if you have any unsaved changes. Basically, don't show this message and let the user exit the editor instantly if they saved the map and have no unsaved changes.

This is a tiny QoL improvement that saves you 1 second of having to click "confirm" everytime you exit the editor. It's especially useful if you save frequently and don't need to confirm anything because you're a smart user.

**Describe the changes you want to propose. Include possible alternatives.**
Can we also change the wording of this section? I feel like everytime I post an issue this is pretty much the same question as the first section. What more needs to be said at this point lol? Make the confirm exit popup in the editor only appear if you have unsaved changes. Simple as that. :smiley:

**Comment by G0nTar** [comment]
I have to +1 this, easy checks like this are not gars to program and at least this has scared me and made me double check many times if I saved my changes, even if they were already saved.

It makes me exit the editor with a bit of fear since it sends that big warning every time

**Comment by Kyllingene** [comment]
1: +1
2:
> Can we also change the wording of this section? I feel like everytime I post an issue this is pretty much the same question as the first section.

If you feel that way, put the raw change in the first part with no explanation, then explain it in the next section.

**Comment by liuxilu** [comment]
https://github.com/Anuken/Mindustry/pull/4383#issuecomment-763634204
> There is no "saved" check, because many actions like changing rules or waves don't activate it.
