### ISSUE TITLE
Emp device 

### ISSUE THREAD

**Issue by Kman247** [Anuken/Mindustry-Suggestions#2076]
The emp when placed has a area effect and when inside the area of effect it will disrupt processors and not allow you to use the processors to control units to do a action or anything this would be great for pvp but also would allow to slow down flyers and not allow them to move as fast so that it would work for campaign too

**Comment by Kyllingene** [comment]
1: Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will automatically filter it out to save him time.

2: Duplicate of approx. 52 issues.

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by itcannotbe** [comment]
@Kyllingene Actually, like magic, this suggestion magically bypassed even the label, thus there is no template.

**Comment by Kyllingene** [comment]
Two possibilities:
1. Github failed to give them the templates
2. They deliberately got rid of the label

**Comment by Thankyou69** [comment]
dont upvote your own post, it makes u look dumb

**Comment by Thankyou69** [comment]
good idea tho

**Comment by itcannotbe** [comment]
Probably he was given the wrong link.

**Comment by Humanoid-X** [comment]
Search github: emp
