### ISSUE TITLE
Allow you to play maps using a seed and the map generator

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2077]
**Describe the content or mechanics you are proposing.**
I would like for there to be an option in custom games in where instead of selecting a map, you can input a seed and the map will be generated for you. You can choose the computer to generate a random seed. The waves on the generated map would be the default waves. 

I would also like an option to generate a map using a seed and saving the generated map as a .msav file in the map creator

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You can play new maps every day and share great seeds with other people. You can also quickly create a map by using a seed and editing a bit of the map and the waves that appear.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
This suggestion expanded on https://github.com/Anuken/Mindustry-Suggestions/issues/2053

**Comment by BlueWolf3682** [comment]
generating like the sectors? i actually agree with this suggestion

**Comment by joshuaptfan** [comment]
Since it would use the same map generator that the campaign uses, it would allow people to do test runs for numbered campaign maps, but in sandbox.

**Comment by Bohaska** [comment]
> Since it would use the same map generator that the campaign uses, it would allow people to do test runs of numbered campaign maps, but in sandbox.

Correct

**Comment by MEEPofFaith** [comment]
~~_Time to see what the waves on 24 truly are._~~

**Comment by Bohaska** [comment]
> ~_Time to see what the waves on 24 truly are._~

I'm not sure if the seeds also determine the waves on a map. If they do, you can figure it out. If they don't then it will be default waves.

**Comment by Humanoid-X** [comment]
Support, but I remember Anuke stated somewhere that the planet's seeds are carefully chose to provide a good map, and any other seeds will make the map unplayable? Did this happened or did my brain just made up things?

**Comment by Bohaska** [comment]
> Support, but I remember Anuke stated somewhere that the planet's seeds are carefully chose to provide a good map, and any other seeds will make the map unplayable? Did this happened or did my brain just made up things?

Just put a warning when choosing a potential bad seed.

**Comment by Humanoid-X** [comment]
@Bohaska
Ok, but before that let us define what is a "bad seed"?

**Comment by Bohaska** [comment]
> @Bohaska
> Ok, but before that let us define what is a "bad seed"?

Sure. A "bad seed" is a seed that 1. isn't in the campaign and 2. unplayable

**Comment by Humanoid-X** [comment]
Maybe...
1. No path from spawn to core
2. More than 5 spawns
3. Less than three blocks around the core

**Comment by Bohaska** [comment]
1. No path from spawn to core
2. More than 3 spawns
3. Less than three blocks around the core
4. More than 80% of water
5. More than 80% of blocks that have a negative effect on watex and less than 5% of water
6. Less then 5-10% ore

**Comment by BlueWolf3682** [comment]
> more than three spawns

***laughs in sector 24***

**Comment by Bohaska** [comment]
> > more than three spawns
> 
> _**laughs in sector 24**_

Sorry, I have never played that sector. Do my requirements forbid it from being created?

**Comment by BlueWolf3682** [comment]
s24 has 4 spawns
