### ISSUE TITLE
Fix the goddamn template check.

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#2078]
**Describe what you would like changed, and why.**
Fix the template checker. For some reason, it isn't auto-deleting suggestions that do not have the template. I'm tired of seeing suggestions with the entire template deleted and just a paragraph of text.

**Describe the changes you want to propose. Include possible alternatives.**
I have no idea how it works but please **_just fix it already_**.

**Comment by RedstonerKBC** [comment]
I don't want to see anymore mods telling me not to swear in front of the children when the children themselves are swearing and not being punished for it.

**Comment by bloool** [comment]
> I don't want to see anymore mods telling me not to swear in front of the children when the children themselves are swearing and not being punished for it.

meep isn't a mod

**Comment by GreyMario** [comment]
what if i told you there is no template checker

**Comment by Bohaska** [comment]
Clone of https://github.com/Anuken/Mindustry-Suggestions/issues/1438

**Comment by sample-text-here** [comment]
~~how would this even be a mod~~

**Comment by Humanoid-X** [comment]
No such bot exist :/

**Comment by Bohaska** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/new?assignees= Link to skip the template

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/new?notexactlybohaskaIcanblabberrandomshithereandstillprovideaworkingfuckinglinkthatalsoskipsthetemplate

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose

The link everyone should be using.

**Comment by Bohaska** [comment]
> https://github.com/Anuken/Mindustry-Suggestions/issues/new?notexactlybohaskaIcanblabberrandomshithereandstillprovideaworkingfuckinglinkthatalsoskipsthetemplate

That one also works, but its a bit long.

**Comment by Bohaska** [comment]
X - https://github.com/Anuken/Mindustry-Suggestions/issues/new
- [X] https://github.com/Anuken/Mindustry-Suggestions/issues/new?assignees=&labels=balancing%2Ffeedback&template=balancing---feedback.md&title=

**Comment by sample-text-here** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/new?labels=duplicate

also, it seems easy enough to do
![](https://media.discordapp.net/attachments/704355961912950793/813266397744070726/unknown.png)
~~anuke, when?~~
