### ISSUE TITLE
Make it so that we can skip the template

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2079]
As you can see, I have skipped the template and managed to create an issue without any tags or templates involved. Make this possible

**Comment by GreyMario** [comment]
Duplicate of #2078.

**Comment by Bohaska** [comment]
Fixed, now it isn't a duplicate

**Comment by sample-text-here** [comment]
> Make it so that we can skip the template

> As you can see, I have skipped the template 

feic

**Comment by Bohaska** [comment]
I'm hungry
