### ISSUE TITLE
Underground Unit and new stuff

### ISSUE THREAD

**Issue by ZLGaming** [Anuken/Mindustry-Suggestions#208]
Underground Unit is a Unit that moves in Underground. They can pass through Buildings but they wont pass the wall.

They only show up when they're about to attack some of the building. It will make them annoying unit or something.
It also wont go on underground when the underground unit is on fire (thanks MechanicalFish)

Stunner Turret
They target Ground and Underground unit.
They also make Underground unit shown when they hit it. Its bullet has ability to stun in small radius. But they shoot slower.

**Comment by Mechanicalfish** [comment]
It also shouldn't be able to go underground when on fire

**Comment by HaphLife** [comment]
It definitely should have a particle effect above ground, (Like the particles that appear when wet or on fire), to telegraph to the player where it is. Secondly, it shouldn’t be able to go through the terrain you can’t build on. (Excluding shallow water and hot rock as well is a good idea) Finally, it should have 1-2 second “digging in” / “emerging from underground” animations to give the player a chance to see how it works, and to give turrets a small chance to kill it before it can attack them.
