### ISSUE TITLE
the ai sux ass

### ISSUE THREAD

**Issue by catguy1122** [Anuken/Mindustry-Suggestions#2080]
the ai sux at pathfinding

they wont get stuck on a block

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X] I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by Bohaska** [comment]
> they wont get stuck on a block

That's fine to me....

**Comment by GreyMario** [comment]
Go take this shitpost to the Google Play reviews.

**Comment by the-kido** [comment]
this suggestion sucks
 apparently, with all the information given in this PR he can magically fix everything with the ai in its state.

**Comment by RedstonerKBC** [comment]
Check out my discussion in #mapping. I had some issues with units committing suicide via drowning. I'll post the map right now so you guys can play it. That's the only AI issues I've had though.

**Comment by SheepCommander** [comment]
oh god

**Comment by Humanoid-X** [comment]
Are you really that sure that "getting stuck on blocks" is "good ai"?!
