### ISSUE TITLE
Let the water conduct electricity?

### ISSUE THREAD

**Issue by Surviavlist** [Anuken/Mindustry-Suggestions#2081]
**Electricity from power turrets were conducted by water**

**This will be more realistic, because the water should conduct an electricity. Units will take damage while in energized water. The damage will depend on the amount of water. Electriсity will dissipate depending on the amount of water and its pollution. If shock mine ine water, it also will conduct electricity. ( I'm speaking about water like river or lakes)**

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
so if a lancer hits a conduit, it would hit several near it? There already is "conduction" (for lack of a better word) in mindustry. When you spray water on a unit and shock it/use an electric weapon it deals more damage.

**Comment by GreyMario** [comment]
> so if a lancer hits a conduit, it would hit several near it?

Lancer isn't an electric weapon, it's a laser weapon.

**Comment by Surviavlist** [comment]
> so if a lancer hits a conduit, it would hit several near it? There already is "conduction" (for lack of a better word) in mindustry. When you spray water on a unit and shock it/use an electric weapon it deals more damage.

Im speaking about water on map like rivers or lakes

**Comment by itcannotbe** [comment]
- [X] I am not familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

"Wet" Status Effect be like:  😲

**Comment by itcannotbe** [comment]
> > so if a lancer hits a conduit, it would hit several near it? There already is "conduction" (for lack of a better word) in mindustry. When you spray water on a unit and shock it/use an electric weapon it deals more damage.
> 
> Im speaking about water on map like rivers or lakes

So to be clear, If in real life I shove live wires from a power plant into a lake/river, it is guaranteed that the whole lake is electrified?

That's not how electricity even works.

**Comment by the-kido** [comment]
> Lancer isn't an electric weapon, it's a laser weapon.

My bad

**Comment by Surviavlist** [comment]
> > > so if a lancer hits a conduit, it would hit several near it? There already is "conduction" (for lack of a better word) in mindustry. When you spray water on a unit and shock it/use an electric weapon it deals more damage.
> > 
> > 
> > Im speaking about water on map like rivers or lakes
> 
> So to be clear, If in real life I shove live wires from a power plant into a lake/river, it is guaranteed that the whole lake is electrified?
> 
> That's not how electricity even works.

I know, if lake will very big water will not energised

**Comment by Surviavlist** [comment]
> * [x]  I am not familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> "Wet" Status Effect be like: 😲

Again, I'm about water like river or like

**Comment by Surviavlist** [comment]
> > > > so if a lancer hits a conduit, it would hit several near it? There already is "conduction" (for lack of a better word) in mindustry. When you spray water on a unit and shock it/use an electric weapon it deals more damage.
> > > 
> > > 
> > > Im speaking about water on map like rivers or lakes
> > 
> > 
> > So to be clear, If in real life I shove live wires from a power plant into a lake/river, it is guaranteed that the whole lake is electrified?
> > That's not how electricity even works.
> 
> I know, if lake were very big water will not energised. Only in radius of  3-5 blocks

**Comment by RedstonerKBC** [comment]
> > > so if a lancer hits a conduit, it would hit several near it? There already is "conduction" (for lack of a better word) in mindustry. When you spray water on a unit and shock it/use an electric weapon it deals more damage.
> > 
> > 
> > Im speaking about water on map like rivers or lakes
> 
> So to be clear, If in real life I shove live wires from a power plant into a lake/river, it is guaranteed that the whole lake is electrified?
> 
> That's not how electricity even works.

I forgot which but one of you guys was just complaining _yesterday_ about how adding things because of their realism is a bad idea.

Anyways, I think the guy is talking about making it so water tiles conduct electricity, not a "wet" status effect (obviously because we already have that and the dude checked that they're familiar with in-game content, so wtf are you guys pestering him about it? smh!). Like if you shock a water tile any units in that body of water get shocked? Or water tiles amplify the electric arcs? Something like that. I'm pretty sure they're not talking about a status effect that already exists though.

I know this isn't how "real electricity" works, but again what I said in the first paragraph. There are no real life slag pools or impact reactors or flying ships so big they can carry an entire nuclear power plant, pause its state of production, place it somewhere else without so much as scratching it, and then carry on resuming power production from the exact point where it left off, defying the very laws of nuclear decay physics in the process.

**Comment by SheepCommander** [comment]
All connected water tiles are electrocuted? The one's hit? The one's hit and directly connected tiles?

How long does it stay electrocuted?

**Comment by Humanoid-X** [comment]
1. **Why all bold My eyes hurt**
2. Mindustry is not a realistic game
3. Imagine naval units
4. Lancer don't shoot electric, it create laser

**Comment by RedstonerKBC** [comment]
> All connected water tiles (that are hit) are electrocuted? Just the ones hit? The one's hit and directly connected tiles?
> 
> How long does it stay electrocuted?

No. They said an arc hits a tile and electrocutes touching water tiles, each time doing less damage the further the water tile is from the stricken tile. Spore water, mud water, dirty water, etc. has reduced range at which electricity shocks units from the striken tile. So not all water tiles, just ones in a certain radius within the striken tile.
