### ISSUE TITLE
Improved Enemy AI for Solo Campaign

### ISSUE THREAD

**Issue by Doug-Lewis** [Anuken/Mindustry-Suggestions#2083]
**Describe the content or mechanics you are proposing.**

>The introduction of additional spawn points for enemies as the level develops

>Pathing trail UI that approximates how waves will pathfind through your defenses before the wave starts.

>Preset attack routes for groups of enemies with side-stops along the way to the core - sometimes namely on resource deposits that players are liable to set up factories on (most commonly air units that are best-suited for this).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

In its current state, the defense segments of the game are very straightforward. Enemies are a spear that perpetually try to pierce through one specific path you can reliably set up your shield on.

By introducing more multi-point attacks, players will be required to build their defenses outward rather than being able to get away with only concentrating it on one specific zone up to the final wave. Ideally this would test your base's defensive abilities in a wide variety of ways.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X]  I have _**not**_ done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
- [X] I am

### not

familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
- [X] I am
### really
familiar with using markdown

**Comment by Humanoid-X** [comment]
A n U k E   i S   n O t   E l O n   M u S k
