### ISSUE TITLE
Advanced daycycle

### ISSUE THREAD

**Issue by Whatisgitbuh** [Anuken/Mindustry-Suggestions#2084]
**Describe what you would like changed, and why.**
Each locals have days and nights, but they are not relevant to planet's revolving around. Even neighboring areas have different time.

**Describe the changes you want to propose. Include possible alternatives.**
Remake planet's revolution cognitively fast, and make daycycles relevant to revolution.

**Comment by GreyMario** [comment]
..but the day-night cycle is already based on the plabet's revolution

**Comment by MEEPofFaith** [comment]
(Hey Anuke, can you add a template to `balancing/feedback` that people will just delete anyways.)

**Comment by Bohaska** [comment]
PR time?

**Comment by Whatisgitbuh** [comment]
> ..but the day-night cycle is already based on the planet's revolution

zomg really? Are you sure or just your thought? It was always under sunlight when I see Ground Zero.

**Comment by Bohaska** [comment]
>Mindustry is always an unrealistic game. Drills and conveyors run without power. You can infinitely respawn without material loss. You can actually drill for water on magma. Slag pools never solidify or cool down. 

>Mods

**Comment by Humanoid-X** [comment]
What, did someone just said that he never experienced nights on Ground Zero?!

**Comment by GreyMario** [comment]
> > ..but the day-night cycle is already based on the planet's revolution
> 
> zomg really? Are you sure or just your thought? It was always under sunlight when I see Ground Zero.

Is your total playtime in Mindustry approximately two minutes?

**Comment by Catchears** [comment]
> > ..but the day-night cycle is already based on the planet's revolution
> 
> zomg really? Are you sure or just your thought? It was always under sunlight when I see Ground Zero.

Dark ground zero (ignore my spaghetti):

![image](https://user-images.githubusercontent.com/57631841/109768619-6c5c6600-7bf9-11eb-9f1d-6b326bdd3971.png)

**Comment by Humanoid-X** [comment]
@Catchears Nah, you conveyors are good.
If yours is spagetti them mine is <insert-some-very-messy-things-here>
