### ISSUE TITLE
Day and Night cycle for custom maps

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry-Suggestions#2085]
**Describe the content or mechanics you are proposing.**

A toggleable setting in the custom map rules that allow for day and night cycle.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X to doubt]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Humanoid-X** [comment]
@itcannotbe What, it already exist in game? Hiw do I get thatt setting?

**Comment by itcannotbe** [comment]
I swear there was an option. But I can't find it again.

**Comment by Bohaska** [comment]
> I swear there was an option. But I can't find it again.

Yea I think there was an option when **starting** a custom game about day and night cycle.

**Comment by Bohaska** [comment]
<img width="346" alt="Screen Shot 2021-03-03 at 3 46 31 PM" src="https://user-images.githubusercontent.com/73286691/109771608-f7f4e780-7c37-11eb-8d81-4f244356d3b3.png">

**Comment by Bohaska** [comment]
> I swear there was an option. But I can't find it again.

Nope, there isn't an option, but this suggestion has been suggested a gazillion times

**Comment by SMOLKEYS** [comment]
> > I swear there was an option. But I can't find it again.
> 
> Nope, there isn't an option, but this suggestion has been suggested a gazillion times

_a_

**Comment by SheepCommander** [comment]
a?

**Comment by SMOLKEYS** [comment]
> a?

a.

**Comment by RedstonerKBC** [comment]
Lol I was literally about to suggest this. It would be nice if you could not only toggle that option but change the length of the day/night to reflect planets' distances from their star.

**Comment by ThebestkillerTBK** [comment]
[https://github.com/Anuken/Mindustry/pull/5302](https://github.com/Anuken/Mindustry/pull/5302)

**Comment by SheepCommander** [comment]
yoooo

**Comment by SMOLKEYS** [comment]
> [Anuken/Mindustry#5302](https://github.com/Anuken/Mindustry/pull/5302)
> implemented

Aaaand that concludes this suggestion.
