### ISSUE TITLE
test

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#2088]

**Comment by Laggyboi0701** [comment]
no
shut

**Comment by QmelZ** [comment]
@sample-text-here ~~what is happening~~

**Comment by sample-text-here** [comment]
~~tried to get `duplicate` label~~

**Comment by itcannotbe** [comment]
that's manually applied by the cat when he used to close issues.

**Comment by Bohaska** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2087 and https://github.com/Anuken/Mindustry-Suggestions/issues/2086 are duplicates

**Comment by sample-text-here** [comment]
amazing
