### ISSUE TITLE
nuke

### ISSUE THREAD

**Issue by Tomp23CZ** [Anuken/Mindustry-Suggestions#2089]
it will be used for quads and octs counts as payload but on quad it replaces the original bombs

**Comment by WinterCrystal** [comment]
Why do I see more and more people not using the template like they should be doing? Also, you want nukes? Make an overheated thorium reactor, pick it up, and drop it, this only works if the reactor explosion is enabled. There's no need for actual nukes in the game, if you want a unit that nukes a base, make a quad.

**Comment by SMOLKEYS** [comment]
> it will be used for quads and octs counts as payload but on quad it replaces the original bombs

***do not remove the template that was given***

**Comment by WinterCrystal** [comment]
Anuke is planning to add a way to make nukes, apparently, close this since anything that's on Anuke's Mindustry trello should not be suggested. Here's the trello link: https://trello.com/b/aE2tcUwF/mindustry-trello

**Comment by WinterCrystal** [comment]
Also, the template is gone.

**Comment by Bohaska** [comment]
> - [X] I have
>### not
>followed the template

>template be like: I am useless.

 >Incredible. **Nobody** has ever even considered suggesting nukes before. This is a revelation. I would never have thought of adding this myself. This idea is so _revolutionary_, so _clear_, so _simple_ that absolutely no further explanation is necessary. I will now go and implement this _amazing_ suggestion immediately.

**Comment by genNAowl** [comment]
Does no one realize that there is no tag on this Issue?

Does no one realize how stupid they are being because this means that no template was their in the first place?

**Comment by SheepCommander** [comment]
If the developer is named Anuke why isn't there a nuke in the game!?1?!/!1?!?11/!!/!1/!

**Comment by Bohaska** [comment]
> If the developer is named Anuke why isn't there a nuke in the game!?1?!/!1?!?11/!!/!1/!

@SheepCommander The developer is actually named Anton Kramskoi and he lived in Lewis Center, Ohio

**Comment by itcannotbe** [comment]
> > If the developer is named Anuke why isn't there a nuke in the game!?1?!/!1?!?11/!!/!1/!
> 
> @SheepCommander The developer is actually named Anton Kramskoi and he lives in Lewis Center, Ohio

Actually there was a nuke (nuclear reactor) in the game that got converted to a thorium based one.

**Comment by stuffyAI** [comment]
> it will be used for quads and octs counts as payload but on quad it replaces the original bombs

If you would've checked the trello like the template says you would've seen that this is already somewhat planned.
