### ISSUE TITLE
Add hostname for server

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry-Suggestions#209]
**Describe the content or mechanics you are proposing.**
Add host info which tell the server the hostname the client use.  
For example, the server know the player using the host 'mindustry.io' join server or other either. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Had this, the server can rediect player to some subServer not only by port

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [*] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [*] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [*] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
You can press F8 to see the log and what hostname or IP the client is connected to.

**Comment by way-zer** [comment]
> You can press F8 to see the log and what hostname or IP the client is connected to.

I mean the server know. Like http, the server can return different content by the host. Or Minecraft, there are something like in bungee, which can let player join different subServer through the host the player uses.

**Comment by ritzip** [comment]
~~`Call.onConnect()` https://github.com/Anuken/Mindustry/blob/7dff023928413b503be1e19501db0f30253bc7be/core/src/mindustry/core/NetClient.java#L216
have fun~~

**Comment by way-zer** [comment]
> ~`Call.onConnect()` https://github.com/Anuken/Mindustry/blob/7dff023928413b503be1e19501db0f30253bc7be/core/src/mindustry/core/NetClient.java#L216 have fun~

I need to know the host first
