### ISSUE TITLE
Make Vela Less useless

### ISSUE THREAD

**Issue by kuboido** [Anuken/Mindustry-Suggestions#2091]
**Describe what you would like changed, and why.**
Many players frequently complain about the vela being absolutely terrible in literally all aspects
The vela needs a serious revamp to make operating/fighting better

**Describe the changes you want to propose. Include possible alternatives.**
 The Vela's previous tiers had special effects like a force field or shield regen. A suggested ability for the Vela should probably be a potent EMP shockwave. This can be activated during a boost. This shockwave heavily decreases efficiency of power-consuming buildings withing a mid-range radius and could give an edge in PvP and attack maps. Upon death a final shockwave is released, but this time it is slightly larger- it removes all enemy power node connections and prevents and unit or turret with laser technology to work for a short time. However this could mean greater cooldown times and balanced movement speed of the Vela

**Comment by Sky4ce09** [comment]
that power node thing would legit be **op**

**Comment by marky0470** [comment]
just half the efficiency of all blocks

**Comment by THEGAMER-10n** [comment]
> that power node thing would legit be **op**

At least it's not unbalanced. The vela becomes like a T4 emp unit, making ot worth the resources, but for a strong emp, you need to suicide.

**Comment by ScepterReignPlayz** [comment]
First Of All

That's Damn OP

Second

Why No Template?

**Comment by itcannotbe** [comment]
@ScepterReignPlayz HE USED THE TEMPLATE. Now use your brain to exactly find what the template looks like.

You're screaming nonsense.

**Comment by Bohaska** [comment]
> that power node thing would legit be **op**

I think a better alternative would be to make that power node thing only temporary and to change it in to make it so that instead of removing connections, it will render the nodes useless for around 1 minute or so.

**Comment by Hedgr** [comment]
> Why not make vela mine thoiurm also, AND MAKE HIM OUR SLAVE ( well this actually a good idea though)

maybe, but it would have to have a huge cargo bay and really fast mining speed for it to be worth

**Comment by Hedgr** [comment]
> > that power node thing would legit be **op**
> 
> I think a better alternative would be to make that power node thing only temporary and to change it in to make it so that instead of removing connections, it will render the nodes useless for around 1 minute or so.

i think that 1 minute is completely op because you could mass an attack, send in one or two of them, get rid of every meltdown and then attack and win because no power pretty much

**Comment by Bohaska** [comment]
Ok maybe shorter period of time. I don't play PVP so I'm not sure exactly how long it might be.

**Comment by SMOLKEYS** [comment]
> Ok maybe shorter period of time. I don't play PVP so I'm not sure exactly how long it might be.

At least 5-20 seconds. But also if you mass produced velas and sent them one by one to *die* it would be op anyways.
