### ISSUE TITLE
Easy to see schematics

### ISSUE THREAD

**Issue by YoMamaLlama1** [Anuken/Mindustry-Suggestions#2093]
**Describe the content or mechanics you are proposing.**
You should be able to see your list of schematics in the start screen instead of having to join multi or single player.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You will be able to see your schematics without having to go to a server or game and take that much time for it. Making it quicker to share/export, also easier to know what schematics you have currently, what the need to have a just of what to make when you are in-game so you're already prepared or you could import a new one right there. 
Also a good suggestion from Jammo2000.  Perhaps add a tab labeled "Data" in the start screen, which can be expanded into user maps, schematics, and core database.
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Sky4ce09** [comment]
would go well with the ability to view the core database the same way

**Comment by Jammo2000** [comment]
Perhaps add a tab labeled "Data" in the start screen, which can be expanded into user maps, schematics, and core database.
