### ISSUE TITLE
Online play for non-steam builds of the game

### ISSUE THREAD

**Issue by LJLittleman** [Anuken/Mindustry-Suggestions#2094]
**Describe the content or mechanics you are proposing.**
so online is slightly blocked for non-steam builds of the game, when trying to play with friends who arent on your internet, it is quite annoying to play. of course you can just play public servers other people made, but to play on your own world can be quite annoying. i think when you go to click host online game, you should be greeted with "Local game" "private game" or "public game" then you select which one you'd like. if you click Local game it would do the same thing it already does, but if clicking public game your server will be put onto the server list. if clicking private, you will be given an IP address for the server. by giving this IP to people, they can type it in the "add server" option on the join game menu, and can join from there.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it will really make it allot easier to play with friends and would just get alot more people to play online, since they can make their own server, instead of having to join one that your friend with the steam build of the game, or an already existing public one

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - X I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - X I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - X I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - X I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RogueRedHawk** [comment]
The reason Steam builds can do this is because they use Steam servers. That is a feature you pay for when you purchase the Steam build. If you wanted, you could host a game and have people join it via port forwarding, but this means you would have to open your computer up to the internet. This isn't a feature that is just being withheld from you-- it is beyond the technical scope of the game to offer this on the free version.

**Comment by GreyMario** [comment]
> The reason Steam builds can do this is because they use Steam servers.

haha no, Steam is just providing a service for ad-hoc multiplayer connectivity; the player is still the host and all other platforms can connect through the normal pathways

> it is beyond the technical scope of the game to offer this on the free version.

Not _technical_ scope; running a master server and providing an ad-hoc connectivity service costs money.

**Comment by DeltaNedas** [comment]
whats wrong with port forwarding?

**Comment by itcannotbe** [comment]
> > The reason Steam builds can do this is because they use Steam servers.
> 
> haha no, Steam is just providing a service for ad-hoc multiplayer connectivity; the player is still the host and all other platforms can connect through the normal pathways

haha no, Steam provides the API and the servers to help work around CG-NAT and other Restrictions that prevents hosting/being accessible.

But yes, access to their steam servers cost money, setting up your own servers cost money, port forwarding doesn't cost money and isn't that hard to set up.

And yes, someone suggested this already.

**Comment by itcannotbe** [comment]
- [#1153]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by SheepCommander** [comment]
Close
