### ISSUE TITLE
Core perks

### ISSUE THREAD

**Issue by AureusStratus** [Anuken/Mindustry-Suggestions#2095]
little perks for the core

the cores are big part of the game sense there the center of your base and if it dies you die now I wanna suggest some core perks that you can pick and it takes resources and time to for the perk to be added to your core here are some suggestions that I thought off but you can never has more then one perk per core

[surge-alloy]
 Ay surge alloy perk will give your cores and an extra bit a of help and if enemies get close it will start to shoot bolts of lightning in random directions when enemies gets close allowing your core to possibly defend itself against weaker enemies  but this perk will reduce your cores storage this will also give your core unit shock bullets that deal really low damage 

[Phase fabric]
Ay phase fabric perk will give your core a small chance to deflect in coming bullets but this perk will make your core a bit weaker to laser bullets or energy bullets this will make you core unit faster and have more building speed 

[Plastanium]
A Plastanium perk will give your core more protection against laser bullets reducing the damage taken by them and also has a smallmchance of obsorbing the damage turning in to power but your core will take more damage from bullets this will make your core unit better at mining and give it healing bullets at the 

[Thorium]
A thorium perk will give your core more healthy and resistant to explosive but at the cost of less storage capacity this perk will make your core unit have bit of armor and give it more damage but it will be slower 

[Metaglass+titanium]
This perk gives your core extra storage and make it immune to fires at the cost of less health this perk will give your core unit the ability to command more units and it will have some frag bullets

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
That would be either/or

- Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills

- Additional configuration of blocks, such as I/O side configuration, which has been suggested a million times

**Comment by PolloUsami** [comment]
actualy the mindustry logo is a duo on top of a core

**Comment by Hedgr** [comment]
maybe this could be like the core upgrades, so essentially you can put 1x1 turrets on lvl 1 core, 2x2 on lvl 2 3x3 on lvl 3 and so on. they would also have to be like x2 expensive and (maybe) consume power to work, even if it just a duo so they arent op

**Comment by Bohaska** [comment]
> maybe this could be like the core upgrades, so essentially you can put 1x1 turrets on lvl 1 core, 2x2 on lvl 2 3x3 on lvl 3 and so on. they would also have to be like x2 expensive and (maybe) consume power to work, even if it just a duo so they arent op

Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills are not suggestable

**Comment by itcannotbe** [comment]
> That would be either/or
> 
>     * Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills
> 
>     * Additional configuration of blocks, such as I/O side configuration, which has been suggested a million times

I wonder why no one got the reference.....

**Comment by Humanoid-X** [comment]
**READ THE README.MD VERY ATTENTIVELY, PAY ATTENTION TO EVERY WORDS IN THE FILE.**
