### ISSUE TITLE
I already said this but I’m using a template now it would be a emp building with a limited range 

### ISSUE THREAD

**Issue by Kman247** [Anuken/Mindustry-Suggestions#2096]
**Describe the content or mechanics you are proposing.**
So this would be a emp type building that would slow flyers down and it would also disable processed controlled units 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently there is flair rushing in pvp and it’s very annoying when a easily mass produced unit can swarm a base and just destroying the entire thing or is a processed controlled unit and is able to fly straight over your wall to your core also in campaign when a bunch of units fly and are able to fly so fast they kinda dodge your turrets this would slow them down just enough to make them less annoying to be able to kill.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by PolloUsami** [comment]
you have tried parallax and fuse? or parallax and scatter

also i dont think there will be something that disables the controlled units that should be too op in some cases

**Comment by marky0470** [comment]
he mentions pvp and usually if its a flare "rush" the game doesnt get to the point where thorium is harvested to produce either of these turrets

**Comment by Humanoid-X** [comment]
If they rush flare, you rush scatter!
