### ISSUE TITLE
Mindustry-Suggestions Moderation by competent users

### ISSUE THREAD

**Issue by stuffyAI** [Anuken/Mindustry-Suggestions#2098]
**Describe the content or mechanics you are proposing.**
Designate certain individuals who regularly check up on suggestions posted here and allow them to moderate suggestions.

This can be achieved either by simply giving them straight up perms to this directory (risky),
or in a 2-way verification progress where another public directory gets added, from which those moderators then
forward valid suggestions onto the private branch/directory where Anuken reads them.

I am in favor of the 2nd one, since this allows moderators to modify suggestions to match the requirements easier,
giving chance to 'rough diamonds'.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will surely improve the Suggestion git at low expense since those people already do this in comments.
Naturally, one must watch over the mods to be neutral and not simply discard suggestions they don't agree with,
but this can be sorted out easily thanks to git features should escalation occur.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (mostly unrelated)
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ScepterReignPlayz** [comment]
As a Person With Common Sense, I highly agree with this

**Comment by iLagSoUhax** [comment]
hmm good

**Comment by Bohaska** [comment]
..... the trillion dollar question: Who?

**Comment by stuffyAI** [comment]
> Who?

Easy to determine via application system in discord or alike, it obviously can't be those who are plain toxic or subjective towards the matter, but anyone with enough dedication and maturity works otherwise

**Comment by bendnuts** [comment]
the moderators of the official discord server already have the power

**Comment by itcannotbe** [comment]
Nope.

**Comment by Kyllingene** [comment]
Please elaborate, itcannotbe.

**Comment by itcannotbe** [comment]
Moderators of the discord server doesn't have any power here.

Hence nope.

**Comment by Kyllingene** [comment]
Ah, ok. I thought you were discrediting the suggestion.

**Comment by Phinner** [comment]
> Moderators of the discord server doesn't have any power here.

Looks like something replaced them...
