### ISSUE TITLE
Buff cultivators

### ISSUE THREAD

**Issue by magikcello** [Anuken/Mindustry-Suggestions#2099]
Cultivators need a buff because two water extractors needed to operate properly and 1spore/3s is a little too much time. I mean, you need at least 6 cultivators = 12 water extractors and all of that is needed to have constant oil flow from spore press. Lots of space, lots of energy and lots of waiting time. I mean, just for making schematics more compact, 

So, i propose a thing, 1 cultivator needs 1 water extractor, or buff spore production to atleast 1.5 seconds.

**Comment by GreyMario** [comment]
I propose you pump real water instead of using water extractors.

**Comment by notrealn** [comment]
if the water needed for spores were to be decreased, then powercuubes come back.

**Comment by itcannotbe** [comment]
Wasn't this already suggested before?

**Comment by magikcello** [comment]
> I propose you pump real water instead of using water extractors.
I know, tho sometimes there is no lake, thus if it is, i dont like all the pipe mess. I mean, specially on multiplayer servers, there is no water at all, no sand, etc.

**Comment by Fipico2** [comment]
Use an actual power source instead of trying to get power from nothing

**Comment by the-kido** [comment]
> Wasn't this already suggested before?

no, it hasn't been suggested at least 3 times and mentioned more than what you'd think would start to be annoying...

**Comment by Slava0135** [comment]
Use pumps nerd.

**Comment by magikcello** [comment]
> Use pumps nerd.

uhh no water around?

**Comment by itcannotbe** [comment]
You shouldn't even be using cultivators when there is no water around. The only real use for spore pods is making blast.

**Comment by CountSudokku** [comment]
Want gaster spores production? Just build cultivator on spores tiles, u can get even 220% of efficiency. If u use as addition surface water from pumps instead of extractors u can even use spores as good power source.

Cultivator need surface water or at least spore tiles to be reasonable to use.
