### ISSUE TITLE
Mods turn off when joining a multiplayer game without mods

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#210]
Mods should turn off while in a multiplayer game without the mods selected. They will turn back on after leaving.

This would help if you want to join a multiplayer game without going back to turn off mods.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
This has the wrong label

**Comment by DeltaNedas** [comment]
`// epic memory leak TODO: make it less epic`

**Comment by Anuken** [comment]
This is not possible anymore.
