### ISSUE TITLE
Easy to see schematics (updated)

### ISSUE THREAD

**Issue by YoMamaLlama1** [Anuken/Mindustry-Suggestions#2101]
Describe the content or mechanics you are proposing.
You should be able to see your list of schematics in the start screen instead of having to join multi or single player.

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
You will be able to see your schematics without having to go to a server or game and take that much time for it. Making it quicker to share/export, also easier to know what schematics you have currently, what the need to have a just of what to make when you are in-game so you're already prepared or you could import a new one right there.
Also a good suggestion from Jammo2000. Perhaps add a tab labeled "Data" in the start screen, which can be expanded into user maps, schematics, and core database.
Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

[x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
[x] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
[x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
 [x]I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What's wrong with editing the original suggestion?

**Comment by SheepCommander** [comment]
huh

**Comment by GreyMario** [comment]
Duplicate of #2093

**Comment by Bohaska** [comment]
He duplicated his own suggestion

**Comment by Fipico2** [comment]
This is really unnecessary. Is that hard to load into a sandbox world? takes less than 10 seconds to do.

**Comment by liuxilu** [comment]
You just install `DeltaNedas/dev-mode` and press `F8` and type `Vars.ui.schematics.show()`.

**Comment by YoMamaLlama1** [comment]
uh pretty impossible on mobile

**Comment by stoneRdev** [comment]
Just saying, on my POS phone, loading the game takes about 3 times as long as loading a sandbox map. I have a sandbox map I do all my survival programming in that's just littered with processors. I rather think having to edit processors in-game is better, as how are you gonna test a processor that's not in-game?

**Comment by YoMamaLlama1** [comment]
It's for the ability to see what schematics you have.

**Comment by liuxilu** [comment]
There is a button for mobile as well.
