### ISSUE TITLE
Allow custom attributes and hints for modding.

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#2102]
**Describe the content or mechanics you are proposing.**

Allow access to creating custom attributes and hints.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Add an extendable class with a name similar to `Attribute`, as well as being able to extend `Hint`, or something along those lines. Currently you cannot do this.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
How are you even going to use attribute outside of json mods?

Also hints.

**Comment by nichrosia** [comment]
Attribute would be used for a custom thermal generator, or other custom things, like a AttributeSmelter boosted by cold.

**Comment by nichrosia** [comment]
Hints would be nice in the case of having a dangerous block, that only states its danger in the description, which some people might not read.
