### ISSUE TITLE
Remove graphite from ripple ammo list

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2103]
**Describe what you would like changed, and why.**
The problem: hail is underused, if someone builds a ripple one will likely feed it with graphite and not blast for example.

**Describe the changes you want to propose. Include possible alternatives.**
This will make hail more popular and make players produce other types of ammo other than graphite.

**Comment by GreyMario** [comment]
Hail is "underused" because it's a goddamn copper-tier turret. Same reason nobody uses Duo.

Thread over.

**Comment by Slava0135** [comment]
> Hail is "underused" because it's a goddamn copper-tier turret. Same reason nobody uses Duo.
> 
> Thread over.

It's a "copper-tier" turret that is more effective than ripple wow. And little see it advantages.

**Comment by itcannotbe** [comment]
![Screenshot_20210306_154214_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110199257-97adb200-7e92-11eb-984b-7914cb9b1039.jpg)
![Screenshot_20210306_154209_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110199260-9aa8a280-7e92-11eb-8890-efd5dcd823e7.jpg)

**Comment by itcannotbe** [comment]
The ripple is too versatile and also removing graphite from it's ammo list won't hurt it.

**Comment by Slava0135** [comment]
5 ammo types is overkill

**Comment by itcannotbe** [comment]
Aside from that, silicon is basically graphite with homing and a reload boost anywat.

**Comment by itcannotbe** [comment]
It won't hurt a turret that can be useful around early endgame.

**Comment by Bohaska** [comment]
After reading @Slava0135 and his posts, I think I'm starting to get the skill of getting tons of replies on my suggestions

**Comment by WinterCrystal** [comment]
> The problem: hail is underused, if someone builds a ripple one will likely feed it with graphite and not blast for example.

Because blast compound is hard to mass produce, you would need a large, efficient schematic to be able to pull that off, why would most of the people do that when there's a more easy way to feed it ammo? It doesn't really matter if the blast compound does the most damage for Ripple when it is difficult to mass produce.

**Comment by Slava0135** [comment]
> > The problem: hail is underused, if someone builds a ripple one will likely feed it with graphite and not blast for example.
> 
> Because blast compound is hard to mass produce, you would need a large, efficient schematic to be able to pull that off, why would most of the people do that when there's a more easy way to feed it ammo? It doesn't really matter if the blast compound does the most damage for Ripple when it is difficult to mass produce.

There is a silicon/pyratite

**Comment by Slava0135** [comment]
Btw you get more silicon per coal than graphite per coal. Why don't people use it...

**Comment by WinterCrystal** [comment]
> > > The problem: hail is underused, if someone builds a ripple one will likely feed it with graphite and not blast for example.
> > 
> > 
> > Because blast compound is hard to mass produce, you would need a large, efficient schematic to be able to pull that off, why would most of the people do that when there's a more easy way to feed it ammo? It doesn't really matter if the blast compound does the most damage for Ripple when it is difficult to mass produce.
> 
> There is a silicon/pyratite

And why would someone use pyratite when it is better used in silicon crucibles, and impact reactors? Letting Ripple use silicon is a waste when again there's better uses for it.

**Comment by Slava0135** [comment]
> > > > The problem: hail is underused, if someone builds a ripple one will likely feed it with graphite and not blast for example.
> > > 
> > > 
> > > Because blast compound is hard to mass produce, you would need a large, efficient schematic to be able to pull that off, why would most of the people do that when there's a more easy way to feed it ammo? It doesn't really matter if the blast compound does the most damage for Ripple when it is difficult to mass produce.
> > 
> > 
> > There is a silicon/pyratite
> 
> And why would someone use pyratite when it is better used in silicon crucibles, and impact reactors? Letting Ripple use silicon is a waste when again there's better uses for it.

Using graphite as ammo is even more a waste

**Comment by WinterCrystal** [comment]
> > > > > The problem: hail is underused, if someone builds a ripple one will likely feed it with graphite and not blast for example.
> > > > 
> > > > 
> > > > Because blast compound is hard to mass produce, you would need a large, efficient schematic to be able to pull that off, why would most of the people do that when there's a more easy way to feed it ammo? It doesn't really matter if the blast compound does the most damage for Ripple when it is difficult to mass produce.
> > > 
> > > 
> > > There is a silicon/pyratite
> > 
> > 
> > And why would someone use pyratite when it is better used in silicon crucibles, and impact reactors? Letting Ripple use silicon is a waste when again there's better uses for it.
> 
> Using graphite as ammo is even more a waste

Not really since you can mass produce it, the other ammos with the exception of silicon are hard to mass produce. Silicon are mostly used in making units, pyratite is better off getting used in silicon crucibles, and impact reactors, blast is also better off getting used for the impact reactor since its production time is slow. Also, the reason why Hail is underused is because there are better turrets out there and that includes the Ripple that is the second longest ranged turret in the game, and is good at dealing swarms of ground units, Ripple can cover a wide area with its projectiles  while Hail can only target one unit at time. You can't blame people for choosing Ripple more since it's clearly more superior than Hail. And no, I don't think removing graphite in the list of Ripple's ammo will make Hail more popular since it is objectively outclassed by most turrets in the game especially the lategame ones. Even if this suggestion gets a pass, people will still choose the Ripple more than the Hail since it can outrange most ground units. In a game where you have units like the Reign or the Toxopid as one of the two possible enemies, RANGE is one of things that matters the most.

**Comment by Slava0135** [comment]
About coal usage:
3 coal is 1 graphite -> 2 * 1/3 ammo = 2/3 shots per coal.
1 coal is 1 silicon -> 3 * 1 = 3 shots per coal.
Silicon is ***4*** (3 if using multipress) times more effective than graphite. So you can get more silicon by using silicon instead of graphite....

**Comment by Slava0135** [comment]
You can't kill Reign/Toxopod using ripples. They barely can do anything with AOE damage to these.

**Comment by WinterCrystal** [comment]
> About coal usage:
> 3 coal is 1 graphite -> 2 * 1/3 ammo = 2/3 shots per coal.
> 1 coal is 1 silicon -> 3 * 1 = 3 shots per coal.
> Silicon is _**4**_ (3 if using multipress) times more effective than graphite. So you can get more silicon by using silicon instead of graphite....

Again, why would people use silicon as ammo when it could be better off getting used in making units, it really does not matter what calculations you pull off, it's about a material's purpose, silicon was not originally meant to be used ammo, and using it as one is such a waste when you can spend it more on things that is far more rewarding.

**Comment by Slava0135** [comment]
> > About coal usage:
> > 3 coal is 1 graphite -> 2 * 1/3 ammo = 2/3 shots per coal.
> > 1 coal is 1 silicon -> 3 * 1 = 3 shots per coal.
> > Silicon is _**4**_ (3 if using multipress) times more effective than graphite. So you can get more silicon by using silicon instead of graphite....
> 
> Again, why would people use silicon as ammo when it could be better off getting used in making units, it really does not matter what calculations you pull off, it's about a material's purpose, silicon was not originally meant to be used ammo, and using it as one is such a waste when you can spend it more on things that is far more rewarding.

But the paradox is... if you use graphite you waste coal

**Comment by Slava0135** [comment]
If you switch to silicon you save 3/4 (2/3) coal that you can use to make units and stuff

**Comment by WinterCrystal** [comment]
> You can't kill Reign/Toxopod using ripples. They barely can do anything with AOE damage to these.

But can Hail do it? Ripple can chip off Reign and Toxopid's health from far away before they getting close to your defenses.

**Comment by WinterCrystal** [comment]
> > > About coal usage:
> > > 3 coal is 1 graphite -> 2 * 1/3 ammo = 2/3 shots per coal.
> > > 1 coal is 1 silicon -> 3 * 1 = 3 shots per coal.
> > > Silicon is _**4**_ (3 if using multipress) times more effective than graphite. So you can get more silicon by using silicon instead of graphite....
> > 
> > 
> > Again, why would people use silicon as ammo when it could be better off getting used in making units, it really does not matter what calculations you pull off, it's about a material's purpose, silicon was not originally meant to be used ammo, and using it as one is such a waste when you can spend it more on things that is far more rewarding.
> 
> But the paradox is... if you use graphite you waste coal

But if you use silicon, you're wasting silicon.

**Comment by Slava0135** [comment]
> > > > About coal usage:
> > > > 3 coal is 1 graphite -> 2 * 1/3 ammo = 2/3 shots per coal.
> > > > 1 coal is 1 silicon -> 3 * 1 = 3 shots per coal.
> > > > Silicon is _**4**_ (3 if using multipress) times more effective than graphite. So you can get more silicon by using silicon instead of graphite....
> > > 
> > > 
> > > Again, why would people use silicon as ammo when it could be better off getting used in making units, it really does not matter what calculations you pull off, it's about a material's purpose, silicon was not originally meant to be used ammo, and using it as one is such a waste when you can spend it more on things that is far more rewarding.
> > 
> > 
> > But the paradox is... if you use graphite you waste coal
> 
> But if you use silicon, you're wasting silicon.

Do you know how does math works?

**Comment by Slava0135** [comment]
By using silicon (instead of graphite) you ***save*** silicon.

**Comment by WinterCrystal** [comment]
Bottom line is, making Ripple not use graphite will not make Hail anymore popular than it already is, even if someone uses Hail, they will likely just switch it with Ripple or something else.

**Comment by Slava0135** [comment]
Let's change it and see

**Comment by WinterCrystal** [comment]
But if this gets approved, Anuke should also remove the graphite in its ammo list since you're stubborn enough to make an argument that using graphite wastes silicon. instead of the other way around.

**Comment by Slava0135** [comment]
Using graphite is a waste - but it is not really related to the subject. People ***will*** use hails because they ***have to*** either make a pyratite (which is complex enough) or use silicon (which is kinda "expensive" except it is not)

**Comment by WinterCrystal** [comment]
> Using graphite is a waste - but it is not really related to the subject. People _**will**_ use hails because they _**have to**_ either make a pyratite (which is complex enough) or use silicon (which is kinda "expensive" except it is not)

But you see, that goes against your argument of using graphite as ammo as wasteful, whether it is related to the topic at hand or not does not matter, it still is the argument you've made here.

**Comment by WinterCrystal** [comment]
> Using graphite is a waste - but it is not really related to the subject. People _**will**_ use hails because they _**have to**_ either make a pyratite (which is complex enough) or use silicon (which is kinda "expensive" except it is not as I figured out above) in order to utilise ripple.

Your statement here just sounds like you just  want people to be deliberately given a disadvantage over for what? Because a turret is underused because use common sense?

**Comment by itcannotbe** [comment]
Ah yes, I remember the time when fuse used graphite good thing it got replaced. And I ain't whining either, unlike someone is apparently.

**Comment by GreyMario** [comment]
So the only thing of value this entire shitpost of a thread ("nObOdY uSeS cOpPeR tIeR tUrReTs") has revealed is that silicon's ammo multiplier needs to be reduced.

**Comment by GreyMario** [comment]
Oh, and that Slava still needs to install Multiplayern't.
