### ISSUE TITLE
Repair Point effectiveness for high HP units

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#2105]
**Describe what you would like changed, and why.**
I suggest increasing Repair Point's effectiveness when healing high HP units. Currently you have to build absurd amount of them if you want to heal a Corvus or an Oct in less than 5 seconds.

**Describe the changes you want to propose. Include possible alternatives.**
 Currently I've come up to two options:
1. Heal percentage/sec instead of value/sec.
2. Exponential healing value growth, increasing each tick or second when healing the same unit. Reset to base value if unit takes damage.

Energy usage could also be adjusted to the healing rate.

**Comment by GreyMario** [comment]
This is part of balancing high-tier units. They're going to take longer to heal, so they're going to be out of the fight for longer if you pull them back.

Consider a suggestion that _won't_ completely upset what little balance consideration this game has.

**Comment by TheNightglow** [comment]
the problem with this suggestion is, what if you build an eclipse, fly it to the edge of the enemy no build zone and simply build a repair point with a solar panel below it....

even if the enemy has foreshadows, the eclipse would still be immortal as long as it is above the repair point....

i ve seen it a couple times in multiplayer pvp or attack maps that ppl do repair-point-creep with atumbras (spamm repair points, destroy defense with units, spamm repair points where the defense was before and so on) to slowly destroy the enemy

would repair points heal a percentage of the health, this method of attack would be uncounterable.... there would be nothing you can do against it
no defense could ever take down even just an atumbra....

**Comment by RedstonerKBC** [comment]
Easy fix: Build lots of repair points and lots of batteries.

**Comment by kaiduck** [comment]
My suggestion would to make it sort of like TF2's crit heals, where healing starts at the current base rate and increases up to a reasonable cap depending on how long it's been since the unit has taken damage.
