### ISSUE TITLE
Client sided movement for units in a formation

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#2106]
**Describe the content or mechanics you are proposing.**
Make unit formation controlled by the player to be client sided.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Doing so will prevent units bumping into the commander or vice versa. Right now it's very painful to command a squad of Megas if you want to build something on a laggy server (ping 200ms or higher), they keep pushing you around and if you get infront of them you can get stuck in a movement loop where they keep pushing you nonstop.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
Won't work. The location of units has to be server side.
