### ISSUE TITLE
(Mobile) An option to make auto-boost for ground units more manual. 

### ISSUE THREAD

**Issue by ThibPlume** [Anuken/Mindustry-Suggestions#2107]
**Describe the content or mechanics you are proposing.**

(Mobile version) 

Two ideas that solve the same problem : 
- an option to disable auto-boost for ground units, so add a button to manually boost
- a slider to adjust the maximal distance between the unit and the center of the screen until the unit decides to boost

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Ground units that can fly have such a sneaky potential when controlled because they can dogge anti air when walking, and dogge ground only defenses when flying. 
But, when you move the camera to quickly, or encounter an obstacle, the unit boost automatically and is targeted by aa. So an option to disable this, (as it already exist for auto-aim), or the possibility to control when the unit consider itself as too far from the center of the screen and start boosting would be nice. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Maybe a button above the placement menu, "Autoboost on/off", that appears whenever you are controlling a boostable unit on mobile. When autoboost is off, another button will appear next to the autoboost toggle button to manually toggle boost.

This way, there's no need dive into settings to toggle autoboost.
