### ISSUE TITLE
pls buff steam generator because of water extractor require metaglass

### ISSUE THREAD

**Issue by lokyinng** [Anuken/Mindustry-Suggestions#2108]
**Describe what you would like changed, and why.**
pls make the steam generator to generate more power like moving it to 9/10 or something and allow it to generate without water but the generate 50% of the power even tho create an endless power loop it allows for it to use in the early game also the steam generator is in F tier and completely useless in any situation unless thermal generator was banned or there is no lava tile in map sometime sacrifice some balance was needed realism is not the way of balancing

**Describe the changes you want to propose. Include possible alternatives.**
make water extractor not require metaglass or make it require silicon instead of metaglass
make silicon factory require metaglass and make steam generator require metaglass instead of silicon
nerf thermal generator

**Comment by lokyinng** [comment]
stop putting the steam generator in the chapping broad of nerfing pls that not the way of balancing

**Comment by itcannotbe** [comment]
> stop putting the steam generator in the chapping broad of nerfing pls that not the way of balancing

What's your idea of balancing? Buffing everything?

**Comment by GreyMario** [comment]
What the hell is this "suggestion"? You can't make steam without water. Steam Generators will _never_ be allowed to run without fluid.

Build a goddamn Kiln and stop whining about TVTropes/TheyChangedItNowItSucks. By the way, now that water extractors cost metaglass _just like all other pumps_, why don't you just build a real pump and pump some real water out of a real water lake?

**Comment by itcannotbe** [comment]
> **Describe the changes you want to propose. Include possible alternatives.**

> make water extractor not require metaglass or make it require silicon instead of metaglass

Making metaglass is extremely easy, I don't really get it why people are appalled of the idea of producing metaglass early on, like you should have.

> make silicon factory require metaglass and make steam generator require metaglass instead of silicon

And that would accomplish nothing.

> nerf thermal generator

What does it have to do with anything?

**Comment by itcannotbe** [comment]
And yes this suggestion is another one of those "I want my power cubes back".

**Comment by itcannotbe** [comment]
> pls make the steam generator to generate more power like moving it to 9/10 or something and allow it to generate without water but the generate 50% of the power even tho create an endless power loop it allows for it to use in the early game also the steam generator is in F tier and completely useless in any situation

> stop putting the steam generator in the chapping broad of nerfing pls that not the way of balancing

Stop contradicting yourself. Stop contradicting yourselfm

**Comment by TheNightglow** [comment]
i feel like water extractors needing glass is more of a symbolic change than a nerf... since glass is anyway one of the easiest resources to get...

also, this makes no sense what so ever:
>make water extractor not require metaglass or make it require silicon instead of metaglass
make silicon factory require metaglass and make steam generator require metaglass instead of silicon

with that logic you would still need to get a metaglass production befor you can make water extractors... so.... what exactly is it you are trying to achive?

**Comment by Humanoid-X** [comment]
Another "I am too lazy to make metaglass and also lazy to build real pump" suggestion.

**Comment by SMOLKEYS** [comment]
> make silicon factory require metaglass

*bruh*
![images (1).jpeg](https://user-images.githubusercontent.com/75618732/110228825-37c11500-7f3f-11eb-85c2-ca14cb617c56.jpeg)

**Comment by SurgeAlloy** [comment]
uhhhh

**Comment by Bohaska** [comment]
Rewritten version: Please make the steam generator generate more power and/or allow it to generate without water but only generate 50% of its base power generation when doing so. Even though it creates an endless power loop, it allows for it to be used in early-game. Also, the steam generator is completely useless in any situation unless thermal generator is banned or unusable.

**Comment by lokyinng** [comment]
> And yes this suggestion is another one of those "I want my power cubes back".

i don't god damn asking for power cubes
also thremo gen is can outpower steam gen

**Comment by lokyinng** [comment]
> Another "I am too lazy to make metaglass and also lazy to build real pump" suggestion.

another "another xxx" comment

**Comment by lokyinng** [comment]
this issue has:
75% steam gen murdering supporter (steam gen can't be used at blocking enemy also realism not = balancing)
24% another "xxx" gag
1% rewritten

**Comment by lokyinng** [comment]
> this issue has:
> 75% steam gen murdering supporter (steam gen can't be used at blocking enemy also realism not = balancing)
> 24% another "xxx" gag
> 1% rewritten

look like steam gen will be nerfed again in build 127

**Comment by itcannotbe** [comment]
> And yes this suggestion is another one of those "I want my power cubes back".

OP be like:

> i don't god damn asking for power cubes
> also thremo gen is can outpower steam gen

OP be also like:

> pls make the steam generator to generate more power like moving it to 9/10 or something and allow it to generate without water but the generate 50% of the power even tho create an endless power loop it allows for it to use in the early game also the steam generator is in F tier

**Comment by Kyllingene** [comment]
> i don't god damn asking for power cubes

Asking for waterless/buffed power production from steam gen is not only ridiculous, but quite plainly asking for power cubes.

And as about 99% of Anukens will tell you, *you are supposed to make metaglass early game that is its intended build period why are you mad it was rectified*

**Comment by SMOLKEYS** [comment]
> make steam generator require metaglass instead of silicon

Silicon is used for *power* and why would you need to look inside a Steam Generator?

> allow it to generate without water but the generate 50% of the power

Do you not know how Steam Generators work?

> nerf thermal generator

What is the purpose of that?

**Comment by SMOLKEYS** [comment]
> pls make the steam generator to generate more power like moving it to 9/10 or something and allow it to generate without water but the generate 50% of the power even tho create an endless power loop it allows for it to use in the early game also the steam generator is in F tier and completely useless in any situation unless thermal generator was banned or there is no lava tile in map sometime sacrifice some balance was needed realism is not the way of balancing

*i cant even understand majority of this*

**Comment by SMOLKEYS** [comment]
> also thremo gen is can outpower steam gen

Obviously because thermal gens use lava which is *MORE* hotter than burning coal.

Meaning it wouldn't make any sense if steam gens produced more power than thermal gens.

**Comment by SpaceSceptralReignPlayz** [comment]
so you want factories need metaglass


what a very funny joke but no

**Comment by SMOLKEYS** [comment]
![SmartSelect_20210310-145738_Discord.jpg](https://user-images.githubusercontent.com/75618732/110589219-0d768e00-81b1-11eb-9901-3c32d908e43b.jpg)
barely anyone agrees

**Comment by XxsuperdeadlysniperxX** [comment]
>generate without water

A steam generator without water is like a pillow with no stuffing

And like a keyboard without keys

You get the point already this suggestion is not good and clearly was thoroughly thought out before you actually posted the suggestion @lokyinng

**Comment by G0nTar** [comment]
After reading the whole conversation I think this is already clear enough, close this pls, the author of this topic is clearly trolling or just really under aged

**Comment by SMOLKEYS** [comment]
finally, the agony of this suggestion ends
