### ISSUE TITLE
Hardness stat of drillable items

### ISSUE THREAD

**Issue by FreakinMagic** [Anuken/Mindustry-Suggestions#211]
**Describe what you would like changed, and why.**

I noticed that drills only show the base drill speed when it completely covers one type of resource with no hardness, being scrap and sand only. I'm asking if it's possible to add a 'hardness' stat on drillable items in the core database for calculations and efficiency, similar to how the flammability of an item affects the energy output if fed to a combustion/steam generator. pretty please.

**Describe the changes you want to propose. Include possible alternatives.**

Adding a 'hardness' stat on drillable items in the core database to determine the efficiency of a drill.

**Comment by potatoisagender** [comment]
What? I'm pretty sure that as you place drills they display the material they are drilling and the speed at which they are drilling...

**Comment by FreakinMagic** [comment]
It would still be handy to have this information at hand, you know? I mean, why even list the explosiveness, flammability and radioactivity of items in the first place if not including hardness as well?

**Comment by potatoisagender** [comment]
The problem with that is that the hardness stat doesn't actually tell you how fast you can mine the material, and if it did, you would have a problem with which drill you use and how much material it covers. Still a good idea though,.

**Comment by jaygamer81** [comment]
Depends whether Anuke would like to add new resources as this would be usefull if there were more resources. Maybe also add a reminder for copper + pnuematic drills saying **Can't mine Titanium or Thorium**, for pneumatic: **cant mine thorium**

**Comment by potatoisagender** [comment]
If you can't remember that, maybe you need to play the game a little more before you start suggesting things.

**Comment by itcannotbe** [comment]
@jaygamer81 You did look at the block info of the blocks in-game right?
