### ISSUE TITLE
Reduse Nova bullet range

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2110]
I think Nova bullets fly too far and it allow destroy all campaign bases very easy up to extreme difficult. 

Maybe change it to 18 blocks, because artillery bullets can be dodged by boost (shift) and scatter range is 20. In bundle artillery + scatters can destroy Nova. Don't forget, this is support unit, it's wrong what they can easy destroy any base, also, it's T1.

**Comment by GreyMario** [comment]
Waaait.

Is this a suggestion that has some relative amount of thought put into it?

_THERE'S HOPE_

Anyway, Novas just really shouldn't be better at ground combat than Daggers. Ever. But getting into the details of that isn't something I want to do.

**Comment by MEEPofFaith** [comment]
Fun fact: If you shoot at a 45-degree angle, Nova can outrange Cyclone.

**Comment by CountSudokku** [comment]
Pulsar are also much stronger than mace, mostly because shield, ability to fly and penetrating shoots. Only thing mace is stronger is single target dmg which us kinda worthless due to range.

**Comment by buthed010203** [comment]
@Qvertyes he added this, should probably close this https://github.com/Anuken/Mindustry/commit/a2c7c38a3ec30503ce902606c29b4e8e98b31234
