### ISSUE TITLE
Add building damage to alpha, beta, gamma

### ISSUE THREAD

**Issue by SurgeAlloy** [Anuken/Mindustry-Suggestions#2112]
This would help some people I'm not saying that to everyone but it would be good

Life in the game would be better if you could sabotage an enemy base, such as destroying power lines or helping units such as destroying the production of ammunition for ground targets.

**Comment by buthed010203** [comment]
I think the idea here was to prevent people from just rushing at the start of pvp matches

**Comment by CountSudokku** [comment]
Imagine how team pvp would look like if beta and gamma had full building dmg, no reason to make t1 units

**Comment by buthed010203** [comment]
> Imagine how team pvp would look like if beta and gamma had full building dmg, no reason to make t1 units

And this is exactly why they don't, pvp in v5 was a terrible experience half the time as people would just rush every single game and it sucked. The advantage of having it so you need to actually make units is that you need to spend time making resources and building units which gives the enemies a chance to defend

**Comment by itcannotbe** [comment]
Why is this the most stupid suggestion I encountered all week?

**Comment by itcannotbe** [comment]
And yes. Damage to building by core units are significantly, intentionally reduced for a reason. And the reason being is for people to not use them to attack building on any stage of the game. For people to be forced to build units.

**Comment by itcannotbe** [comment]
If want to attack building, commandeer any other unit besides core units.

**Comment by itcannotbe** [comment]
> > Imagine how team pvp would look like if beta and gamma had full building dmg, no reason to make t1 units
> 
> And this is exactly why they don't, pvp in v5 was a terrible experience half the time as people would just rush every single game and it sucked. The advantage of having it so you need to actually make units is that you need to spend time making resources and building units which gives the enemies a chance to defend

No. v5 pvp sucked because people can't be bother to properly defend with scatter.

**Comment by Ilya246** [comment]
Building damage on core units is disabled for a reason - they actually deal insane damage per second and allowing them to damage buildings would just mean instant death to everything in the enemy base that is exposed

**Comment by Ilya246** [comment]
Every time i set player ship damage to 100% on .pl using /js, most relatively badly defended parts of the enemy base quickly stopped existing

**Comment by SurgeAlloy** [comment]
> > > Představte si, jak by týmový pvp vypadal, kdyby beta a gama měly plnou budovu dmg, není důvod vyrábět jednotky t1
> > 
> > 
> > A to je přesně důvod, proč ne, pvp ve v5 byl v polovině času hrozný zážitek, protože lidé prostě spěchali každou hru a bylo to na hovno. Výhodou toho, že jej máte, takže musíte skutečně vytvářet jednotky, je, že musíte trávit čas výrobou zdrojů a budováním jednotek, což dává nepřátelům šanci se bránit
> 
> Ne. V5 pvp nasáván, protože lidé se nemohou obtěžovat, aby se správně bránili pomocí rozptylu.

can you stop writing too much

**Comment by RedstonerKBC** [comment]
Can we do something about this??? Players keep complaining that the game is bugged because the wiki says one thing but the actual damage they do is way less.

**Comment by buthed010203** [comment]
> Can we do something about this??? Players keep complaining that the game is bugged because the wiki says one thing but the actual damage they do is way less.

Completely agree, this should really be documented better
![](https://aethex.is-a.fail/QRZRlr.png)

**Comment by Fipico2** [comment]
> > > > Představte si, jak by týmový pvp vypadal, kdyby beta a gama měly plnou budovu dmg, není důvod vyrábět jednotky t1
> > > 
> > > 
> > > A to je přesně důvod, proč ne, pvp ve v5 byl v polovině času hrozný zážitek, protože lidé prostě spěchali každou hru a bylo to na hovno. Výhodou toho, že jej máte, takže musíte skutečně vytvářet jednotky, je, že musíte trávit čas výrobou zdrojů a budováním jednotek, což dává nepřátelům šanci se bránit
> > 
> > 
> > Ne. V5 pvp nasáván, protože lidé se nemohou obtěžovat, aby se správně bránili pomocí rozptylu.
> 
> can you stop writing too much

Really? Dont make any more suggestions if this is how you will respond. This suggestion doesnt follow the template, is a bad idea and now you say this.

**Comment by itcannotbe** [comment]
> > > > > Představte si, jak by týmový pvp vypadal, kdyby beta a gama měly plnou budovu dmg, není důvod vyrábět jednotky t1
> > > > 
> > > > 
> > > > A to je přesně důvod, proč ne, pvp ve v5 byl v polovině času hrozný zážitek, protože lidé prostě spěchali každou hru a bylo to na hovno. Výhodou toho, že jej máte, takže musíte skutečně vytvářet jednotky, je, že musíte trávit čas výrobou zdrojů a budováním jednotek, což dává nepřátelům šanci se bránit
> > > 
> > > 
> > > Ne. V5 pvp nasáván, protože lidé se nemohou obtěžovat, aby se správně bránili pomocí rozptylu.
> > 
> > 
> > can you stop writing too much
> 
> Really? Dont make any more suggestions if this is how you will respond. This suggestion doesnt follow the template, is a bad idea and now you say this.

Actually he followed the template but didn't leave it in for some reason.

Probably because he's translating things as he goes.

**Comment by NajimiOsana** [comment]
-You'd be Unstoppable on Multiplayer Servers, since your team would have like, 7 Players
-No Reason to build T1 units anymore
-the nerf was literally made to prevent Core Rushing
-Just make a fucking Unit instead

**Comment by SurgeAlloy** [comment]
> > Můžeme s tím něco udělat ??? Hráči si stále stěžují, že je hra odposlouchávaná, protože wiki říká jednu věc, ale skutečná škoda, kterou způsobí, je mnohem menší.
> 
> ~Úplně souhlasím, toto by mělo být skutečně zdokumentováno lépe~
> 
> Nvm je to už tady lol
> ![](https://camo.githubusercontent.com/7296abb76252e191ad424d361976b48cd87e1cca7ce60e59af3e5a19e6335f93/68747470733a2f2f7961677064622e69732d6e652e61742f4a44477354662e706e67)

there isnt thats only 1%

i want 3%

**Comment by buthed010203** [comment]
> there isnt thats only 1%
> 
> i want 3%

That would increase damage by 3x, the entire point here is that it does **as little as possible**, you arent supposed to use these units to attack. Make some flares, it takes like 30s

**Comment by GitHubUser-B** [comment]
I think it should be optional.
