### ISSUE TITLE
Remove @this from logic

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#2113]
**Describe what you would like changed, and why.**
The title says it all

**Describe the changes you want to propose. Include possible alternatives.**
It should be removed as I have yet to see a use for it other then to logic greif and make it impossible to catch the orgainal owner unless the server has a plugin that prevents that

**Comment by DeltaNedas** [comment]
`ucontrol getblock @thisx @thisy`

**Comment by buthed010203** [comment]
I think the better way to do this would just be to restrict the placement/configuration of logic blocks via logic, I dont see that being useful in like 99.9% of cases

**Comment by joshuaptfan** [comment]
`@this` is extremely useful good logic too. You would know this if you were familiar enough with logic to make a sensible logic suggestion.

**Comment by TheNightglow** [comment]
i usually use @this to get the position of the processor

removing it because of griefer is a stupid idea
