### ISSUE TITLE
Make unloaders unload a full belt worth of items

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry-Suggestions#2114]
**Describe what you would like changed, and why.**
Unloaders should unload 12.5 items per second to fill a full titanium belt, certain compact designs are broken by this and it would just be more intuitive.

**Describe the changes you want to propose. Include possible alternatives.**
I get that it's not as simple as changing the unload speed because then its jank when unloading directly onto conveyors but it would be really nice.

**Comment by HTMLPhoton** [comment]
it also makes more sense as well, every other transportation-related block can handle a full titanium belt, but not unloaders.

**Comment by Kyllingene** [comment]
> I get that it's not as simple as changing the unload speed because then its jank when unloading directly onto conveyors but it would be really nice.

If it would have some difficulty to it, please, explain a potential method of implementing this.

**Comment by itcannotbe** [comment]
Unloaders used to be able to unload a full titanium belt speed, but it was nerfed long ago because it proved to be overpowered.
