### ISSUE TITLE
Two core unit balance ideas

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#2116]
**Describe what you would like changed, and why.**
Decrease speed when shooting further, just to make core vs. core unit fights a bit more reliable.
Core unit building damage to zero, and add a hint for it. Core units already deal minuscule damage, but this doesn't stop people from trying when they see a single dent after shooting for ages.

**Describe the changes you want to propose. Include possible alternatives.**
Decrease core unit speed when shooting.
Zero core unit building damage.

(look at the tag before saying something about the template)

**Comment by RedstonerKBC** [comment]
If you're going to implement this at the very least fix the wiki so that players stop accusing me of hacking. I know Anuke already told me no but it gets very annoying when I can't show these accusers and when they try to kick me from the server.

**Comment by itcannotbe** [comment]
> If you're going to implement this at the very least fix the wiki so that players stop accusing me of hacking. I know Anuke already told me no but it gets very annoying when I can't show these accusers and when they try to kick me from the server.

Core unit damage against buildings are now listed in the core database/info
