### ISSUE TITLE
Velocity Induced Bullet Inaccuracy.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2117]
**Describe the content or mechanics you are proposing.**
The faster you go the more terrible your shot are.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make PvP more interesting as there will be a drawback to moving shots.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
This "feature" used to be in the game until it was patched because it made it impossible to hit targets without being a complete sitting duck.

**Comment by itcannotbe** [comment]
> This "feature" used to be in the game until it was patched out because it made it impossible to hit targets without being a complete sitting duck.

What if it only make it inaccurate when your moving along the y axis relative to the unit or plainly rotating?

**Comment by Humanoid-X** [comment]
Good idea, but what about fast units (such as the Javelin class in MeepofFaith's mod) ?

**Comment by Jammo2000** [comment]
> Good idea, but what about fast units (such as the Javelin class in MeepofFaith's mod) ?
Those are modded units, the vanilla game doesn't have units that are that fast (I think flare is the fastest).

**Comment by Humanoid-X** [comment]
Oh, ok. I will just stick to vanillaa a :D

**Comment by Coolhandluke348** [comment]
> > This "feature" used to be in the game until it was patched out because it made it impossible to hit targets without being a complete sitting duck.
> 
> What if it only make it inaccurate when your moving along the y axis relative to the unit or plainly rotating?

Have you thought that maybe making changes that make the game more tedious are not in the best interest of the game?

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by Kyllingene** [comment]
Please, stop bumping every issue that you think is half-worth a look. They are stale. *You are spamming everyone with a useless bump thousands of times.* You must have better things to do.

**Comment by itcannotbe** [comment]
> Please, stop bumping every issue that you think is half-worth a look. They are stale. _You are spamming everyone with a useless bump thousands of times._ You must have better things to do.

It's not my fault that you even watch the repository.
So it's technically not everyone.

So if endless bumps pisses you off, then it's not my fault anymore.

**Comment by Kyllingene** [comment]
Ok. Fine. Maybe I'm an jerk imposing artificial restraints on others by watching this repo. ***How about Anuke?***

**Comment by itcannotbe** [comment]
If he thinks this is unacceptable, he would have done something about it.
Since you are watching the repo. You know that anuke responded fairly quickly when the form was assigning issues to him directly right. Made a statement, deleted, the statement, and changed something to the forms.

**Comment by Kyllingene** [comment]
Still, spamming anyone for the reason "I still personally think that this issue has merit despite everyone else disagreeing and thus refuse to let the bot that Anuke made clear up dead issues" is bad, because the reason is bad. You achieve nothing by bumping the issues, because these issues are just dead. There is nothing more to be said about them, or if there is, no-one wants to say it. If you have something to say, do so; don't expect others to because you bumped a post to counteract the *very helpful* bot and keep it from doing its job.

**Comment by itcannotbe** [comment]
Currently I have less than 20 issues open. And I only do one massive bump every 19 days, That's basically less than 20 email notifications. Not even a bother.

Plus it's not even prohibited. I don't get the point you're making here.
A lot of sites have auto clear on their forums but allows people to bump on topic they don't want to get auto closed.

It's fair game, it's not prohibited. I guess the discussion ends here because your opinion is as good as mine since a rule prohibiting bumping does not exist not is preventing the bot from auto closing issues.
