### ISSUE TITLE
WEX

### ISSUE THREAD

**Issue by SurgeAlloy** [Anuken/Mindustry-Suggestions#2118]
**Describe what you would like changed, and why.**
REMOVE METAGLASS FROM WATER EXTRACTOR PLSSSSSSSSSS

**Comment by GreyMario** [comment]
Duplicate of the entire Mindustry Discord server the day the update was released.

Allow me to supply you with the Canned Answer:

> If you can't make Metaglass, you literally have no use for water anyway, because the only things you can water which don't require Sand to create/operate are the Mechanical and Pneumatic Drill. Ergo, your tech level is locked low enough that you won't have access to Thorium or Plastanium; your tech peaks at low-power Titanium level, and just _barely_.
> 
> So you truly have no reason to complain about a Metaglass cost being added to the Water Extractor. Maybe now you people will build _real_ pumps.

**Comment by Fipico2** [comment]
Please stop making suggestions

**Comment by GreyMario** [comment]
> Please stop making suggestions

Finally, a smart suggestion.

I was almost beginning to think we should invite XxsuperdeadlysniperxX back.

**Comment by Bohaska** [comment]
> REMOVE METAGLASS FROM WATER EXTRACTOR PLSSSSSSSSSS

Sure, if you add 1 surge alloy to the water extractor.

**Comment by Bohaska** [comment]
>it's FREAKING OVERPOWERED

> - [X] I have
>### not
>followed the template

>template be like: I am useless.

> but no, just no.

> No
> 
> Just no
> 
> That won't happen at all

> Still, no

**Comment by routerstack** [comment]
yes

**Comment by genNAowl** [comment]
^ What's with all the quote-response thingy's?

**Comment by Bohaska** [comment]
> ^ What's with all the quote-response thingy's?

I gathered a list of all of the responses that fit this suggestion and inserted them.

**Comment by SpaceSceptralReignPlayz** [comment]
![Screenshot (535)](https://user-images.githubusercontent.com/78523222/110586605-6fcd8f80-81ad-11eb-8ee7-2443dabc325a.png)

ehm ehm

**Comment by itcannotbe** [comment]
@SpaceSceptralReignPlayz This was suggested before that change to the readme was made.
