### ISSUE TITLE
Do not remove metaglass from water extractors

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2119]
**Describe what you would like changed, and why.**
Nothing at all.

**Describe the changes you want to propose. Include possible alternatives.**
Nothing at all.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
Why are a lot of people whining about this change? Metaglass is fucking easy to produce anyway.

**Comment by TheNightglow** [comment]
this does not help either, you dont fight spamming with even more spamming

**Comment by Bohaska** [comment]
>Incredible. **Nobody** has ever even considered suggesting nothing before. This is a revelation. I would never have thought of adding this myself. This idea is so _revolutionary_, so _clear_, so _simple_ that absolutely no further explanation is necessary. I will now go and implement this _amazing_ suggestion immediately.

**Comment by itcannotbe** [comment]
You're so fond of using that out of context.

**Comment by Bohaska** [comment]
> You're so fond of using that out of context.

I tried, but 

>Not everything needs to be turned into nothing

doesn't really work here.
