### ISSUE TITLE
Leaderboard score system

### ISSUE THREAD

**Issue by Angramme** [Anuken/Mindustry-Suggestions#212]
Add a feature so the server can associate a score to a player, thus when Tab is pressed all players are ranked from best to worst. In addition display the score next to the player.

It will be especially useful for pvp servers like hexed for example.

**Comment by itcannotbe** [comment]
You do realize that Hexed is a Plugin not part of the vanilla game.

**Comment by Angramme** [comment]
oh, ok :) but the player list that pops up when you hold tab is part of vanilla isn't it? I should probably change my request to: allow plugins to associate scores to players or how they are order in the list.
