### ISSUE TITLE
Pls remove metaglass from extractors

### ISSUE THREAD

**Issue by ThatGamerDude2937** [Anuken/Mindustry-Suggestions#2120]
**Describe what you would like changed, and why.**
Remove the metaglass from water extractors.

**Describe the changes you want to propose. Include possible alternatives.**
Just do it

**Comment by CountSudokku** [comment]
Just make metaglass, it's not that hard. Also with metaglass in extractor noobs will no longer place them instead of pumps.

**Comment by ThatGamerDude2937** [comment]
Too lazy

**Comment by CountSudokku** [comment]
It's metaglass, not surge alloy, it's actually pretty easy to produce it in huge amounts, 3-4 smelters should be enough
