### ISSUE TITLE
Make inserting phase fabric into RTG generators a cool option.

### ISSUE THREAD

**Issue by DrizztDo-Urden** [Anuken/Mindustry-Suggestions#2123]
**Describe what you would like changed, and why.**

I would like to have putting phase fabric in the RTG generators as an interesting way to generate electricity.
This is because it currently makes no sense to generate energy this way, when 1 phase fabric requires 4 thorium + energy, sand and a weaver to produce, then generates 40% less energy than 1 thorium in the RTG.

**Describe the changes you want to propose. Include possible alternatives.**

The fiber should generate at least 4.5 times more energy than thorium in the RTG generator, so producing it specifically for power plants would be an interesting new way to generate electricity.
Way 1: change the radioactivity statistics of thorium and phase, so that fiber has a significantly higher radioactivity than thorium, thus producing more energy in x-ray machines.
Way 2: make the radioactivity statistic represent the decay time instead of the amount of energy produced, so the phase fabric having lower radioactivity would power the generator for longer. In addition, the radioactivity of the fibre should be lowered, as 60% is still too high for phase power plant to make sense.

**Comment by TheRealIvyX** [comment]
this is not how radioactivity works. you dont just add non-radioactive stuff to radioactive stuff and have the result of what you just made be more radioactive than what you started with

**Comment by itcannotbe** [comment]
The only reason why you.can use phase in an RTG is beacuse it kinda radioactive.

Same reason why you can use blast in a steam generator since it's kinda flammable.

**Comment by RedstonerKBC** [comment]
> this is not how radioactivity works. you dont just add non-radioactive stuff to radioactive stuff and have the result of what you just made be more radioactive than what you started with

*Laughs in Period 7 elements* Oh really?

**Comment by RedstonerKBC** [comment]
I'm going to have to agree more with itcannotbe's reasoning than with TheReallvyX's. Phase just isn't as radioactive as Thorium and that's all there is to it.

**Comment by Humanoid-X** [comment]
I have to disagree with this suggestion.
Take uranium, U3O8 and U2O5 have more uraniums in them than single uranium atom, yet they are more stable than uranium.
I agree with itcannotbe. That's how the game work :p

**Comment by TheRealIvyX** [comment]
> *Laughs in Period 7 elements* Oh really?

ok so i know that this suggestion is closed now but (the following is an example of what i meant) if you were to like take 1 gram of any radioactive element, and take 9 grams of literally anything that isnt radioactive, mix them together and remove 1/10th of the mess that you just made, would that 1/10th of your radioactive mess be more radioactive than all of the radioactive material that you started with? according to the comment i quoted, that 1/10th of what you just made would be more radioactive than the radioactive material you started with but only if the radioactive material you started with was a period 7 element

**Comment by Kyllingene** [comment]
> I have to disagree with this suggestion.
Take uranium, U3O8 and U2O5 have more uraniums in them than single uranium atom, yet they are more stable than uranium.

> this is not how radioactivity works. you dont just add non-radioactive stuff to radioactive stuff and have the result of what you just made be more radioactive than what you started with

Both of these are horrible reasons to downvote. "Oh, realism needs to be maximal" defeats the purpose of how many things? Mass drivers either shoot raw, varying resources through air with 100% accuracy (including sand) or fabricate containers out of thin air. Pneumatic and mechanical drills are perpetual motion machines, along with the three basic conveyors, bridge conveyors, routers, etc. Draug miner drones used to exist, and they only got removed because there were new miner drones introduced. They cost power only. And please explain how all the drones in the map have infinite fuel, power, and ammo (unless that *balancing* setting is turned on)? Balancing a game like Mindustry around realism is a terrible idea. 
![realism](https://user-images.githubusercontent.com/69094702/110516702-cad48900-80be-11eb-8b00-b629865cfe80.png)

> The only reason why you.can use phase in an RTG is beacuse it kinda radioactive.
>
> Same reason why you can use blast in a steam generator since it's kinda flammable.

Ah, but in the given example, blast compound is *less flammable* (but more explosive) than pyratite, one of its constituent components. However, it still outputs the same amount of power. At the very least, make phase fabric just as effective as thorium.

I think this should be reopened, as it makes perfect sense.

**Comment by itcannotbe** [comment]
> > The only reason why you.can use phase in an RTG is beacuse it kinda radioactive.
> > Same reason why you can use blast in a steam generator since it's kinda flammable.
>
> Ah, but in the given example, blast compound is less flammable (but more explosive) than pyratite, one of its constituent components. However, it still outputs the same amount of power. At the very least, make phase fabric just as effective as thorium.

Ah, but in the given example, phase fabric is less radioactive than thorium, one of its constituent components.

**Comment by itcannotbe** [comment]
![Screenshot_20210310_022437_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110518998-cb653200-8147-11eb-8e68-5d184c5f6b48.jpg)
![Screenshot_20210310_022402_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110519012-ce602280-8147-11eb-9ed1-597daaed45da.jpg)
![Screenshot_20210310_022356_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110519019-d0c27c80-8147-11eb-88ae-363bd2c879c2.jpg)
![Screenshot_20210310_022601_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110519212-010a1b00-8148-11eb-9f10-e1dac536c2a4.jpg)
![Screenshot_20210310_022554_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110519218-04050b80-8148-11eb-84cd-474616e14393.jpg)

**Comment by Kyllingene** [comment]
All you did with those pictures was prove my point. Blast compound is less flammable than its constituents, phase fabric is less radioactive than thorium. Your point?

**Comment by Kyllingene** [comment]
Ah, but in the given example, blast compound is less flammable than pyratite, one of its constituent components.
