### ISSUE TITLE
Make game rules visible to people playing the map

### ISSUE THREAD

**Issue by kaiduck** [Anuken/Mindustry-Suggestions#2124]
**Describe the content or mechanics you are proposing.**
Make it possible for players in a map to be able to view the game rules that you can currently only see by downloading the map and opening the map editor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's a minor QOL change that would make it easier for players on maps they haven't played before to know things like unit build speed or damage/health buffs.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
Maybe add this to core database

**Comment by Humanoid-X** [comment]
Yes, agree. Must add maps to core database. But what about multiplayer maps?

**Comment by itcannotbe** [comment]
> Yes, agree. Must add maps to core database. But what about multiplayer maps?

That can be easily added by a plugin. Then probably do !maprules

**Comment by Kyllingene** [comment]
> That can be easily added by a plugin. Then probably do !maprules

But then the host has to go out of their way to slightly de-disadvantage (words) his opponents. Phrased better, there are three possibilites:

1. The host wants to advantage everyone as much as possible and goes way out of their way to do so.
2. The host wants to advantage everyone as much as possible, but does not think it's that big a deal.
3. The host is toxic and wants the biggest advantage possible.
4. The host does not have the time/resources/knowledge to implement a plugin.

How many hosts will agree that seeing the stats is *that* big of a deal, when no plugin seems readily available for an easy fix? I think not many. However, many people will fall into numbers 2 and 4.

**Comment by itcannotbe** [comment]
> > That can be easily added by a plugin. Then probably do !maprules
> 
> But then the host has to go out of their way to slightly de-disadvantage (words) his opponents. Phrased better, there are three possibilites:
> 
>     1. The host wants to advantage everyone as much as possible and goes way out of their way to do so.
> 
>     2. The host wants to advantage everyone as much as possible, but does not think it's that big a deal.
> 
>     3. The host is toxic and wants the biggest advantage possible.
> 
>     4. The host does not have the time/resources/knowledge to implement a plugin.
> 
> 
> How many hosts will agree that seeing the stats is _that_ big of a deal, when no plugin seems readily available for an easy fix? I think not many. However, many people will fall into numbers 2 and 4.

Well..... Outside from steam and listed community servers, people who host games are in contact with each other in some manner. Surely they would agree on the map setting before hand or can easily ask it.

And believe me, community servers are do what ever they can to add more features than the others.

**Comment by Kyllingene** [comment]
> Throwing in a plugin is easy.

Ok then, what plugin is it? And once you find one (if you do), how long did it take to find? Did you use resources many people might not know about? Therefore, they might not have the time, resources or knowledge to find the plugin.

> There is minimal advantage you can have even in PvP if you know the map rules

MMM. How about the case where you build a bunch of walls, only to find the game rules were geared towards independent defenses? Or how about your heavily optimized schematics that suddenly are not very good? And as you said, it lowers the aggravation players could possibly feel towards each-other based on rules.

And even if you think those are edge cases, is it not fairly easy to implement a simple menu which simply echoes the map rules at you? For all I care, you could practically copy-paste the rule menu for creating a map, edit it a little (change inputs to text, make all the text input values come from game rules, and turn image buttons into simply images), and voila! an easy patch to the game. Granted, I could be grossly mistaking how complicated the menu display process is, there may be no good framework for map rules (although there probably is), etc. etc. However, from my little bit of digging through the source code, it seems remarkably easy to implement.

**Comment by itcannotbe** [comment]
![Screenshot_20210310_025640_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110522915-6b24bf00-814c-11eb-8ad0-e918fcded3cb.jpg)
![Screenshot_20210310_025646_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110522929-6f50dc80-814c-11eb-99af-10f834004cf2.jpg)
![Screenshot_20210310_025706_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110522939-71b33680-814c-11eb-9d6c-6a280ce81474.jpg)
![Screenshot_20210310_025714_io anuke mindustry](https://user-images.githubusercontent.com/45280919/110522941-72e46380-814c-11eb-85aa-a7bebbb9caef.jpg)

This is why it's easier to implement this for multiplayer than singleplayer.
Since you can utilize the chat feature to make the server send a reply of the game rules in a form of a list.

Also
> How about the case where you build a bunch of walls, only to find the game rules were geared towards independent defenses? Or how about your heavily optimized schematics that suddenly are not very good?

Where does this come in?

**Comment by Kyllingene** [comment]
> Since you can utilize the chat feature to make the server send a reply of the game rules in a form of a list.

Then do that, but global. If it is so easy, I see no reason not to add it, as it would increase QoL for some people.

> Where does this come in?

In those cases. Both of them could be avoided by a simple check of the map rules (although, to be fair, the first one is quite specific, I was rushing).

**Comment by itcannotbe** [comment]
> > Also
> > 
> > > How about the case where you build a bunch of walls, only to find the game rules were geared towards independent defenses? Or how about your heavily optimized schematics that suddenly are not very good?
> > 
> > Where does this come in?
>
> In those cases. Both of them could be avoided by a simple check of the map rules (although, to be fair, the first one is quite specific, I was rushing).

I mean specifically. Since you mentioned it. How does the game rules affect those you have stated.

**Comment by Kyllingene** [comment]
Block health/unit damage both affect if big, wall defenses or dispersed small defenses are best, and build cost/speed, deconstruct refund, banned blocks, and schematics allowed all affect schematics.
