### ISSUE TITLE
Hunter Ai

### ISSUE THREAD

**Issue by simulation3** [Anuken/Mindustry-Suggestions#2126]
**Describe the content or mechanics you are proposing.**
I would like it if logic had a way to set drone Ai to make it so that drones go out and search for enemy units to attack them instead of hanging out near the spawn ring. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As it is now units enemy and player made alike dont really do much against each other. There is a high likelihood that they may walk past each other if they both have a lot of health and then when they reach the ring if it's a flying unit it will sit off to the side while land units walk off to the side clear of their range sometimes. So I propose a way for logic to make units hunt down enemy units so they dont just camp the ring and let them go by. It might encourage players to use a variety of units for enemy speed and it might be fun to actually have oct follow an enemy with a piercing laser so that it doesn't do too much damage to the back lines until the cleanup crew arrives. Plus in maps with multiple spawn points, it might encourage players to use flares and horizons instead of the higher-end units so they can fly from one ring to another for help. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
What if boost on desktop was changed to be a toggle, without an option to make it a hold? (I may PR this.) Does anyone prefer boost to be a hold? Why?

**Comment by joshuaptfan** [comment]
This can be done with logic, and was one of the purposes for which logic was made.

**Comment by Bohaska** [comment]
maybe add a simple "change AI" feature to logic processors that can swap a unit's existing AI to AI's that are in the code. Add an AI similar to this one. (For example, swapping poly's build ai to mega's heal ai)

**Comment by C4nc3ER** [comment]
I think it should be more of an AI pathfind setting, as otherwise most logic uses a hand-made target system similar to this idea, and using this Hunter AI, if implemented as an AI setting, could easily slim down processing power.

I think it's a good idea, if put in properly.
