### ISSUE TITLE
Toggle Boost option

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#2127]
**Describe the content or mechanics you are proposing.**

Add a setting to make the boost movement key a toggle, not a hold.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

My pinkie hurts ._.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
What if boost on desktop was changed to be a toggle, without an option to make it a hold? (I may PR this.) Does anyone prefer boost to be a hold? Why?

**Comment by Humanoid-X** [comment]
Agree, my pinkie hurts too

**Comment by itcannotbe** [comment]
I thought you can't build or shoot while boosting?

**Comment by the-kido** [comment]
> What if boost on desktop was changed to be a toggle, without an option to make it a hold? (I may PR this.) Does anyone prefer boost to be a hold? Why?

I don't see anything wrong with it being toggled rather than held. But, perhaps if you press shift twice it toggles it rather than another button? It's the best of both worlds i think.

**Comment by Jammo2000** [comment]
So double press to toggle on, then single to unboost. Sounds good to me. 
I think once it's toggled on, only one press should be needed to stop, since what other possible action could someone want to take?

**Comment by joshuaptfan** [comment]
> So double press to toggle on, then single to unboost. Sounds good to me.

This can be a fallback solution, but I prefer to implement a single press toggle as double press will still hurt your pinkie. Are there any specific situations where boost hold is preferable?

**Comment by Humanoid-X** [comment]
Why need double press? Just assign a variable, change it everytime you press shift
