### ISSUE TITLE
Buff Shale

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#2129]
**What?**

Buff shale; Note that I never said nerf sand (I don't want the schematic community after my head)

**Why?**

Shale is a bit ignored right now; Everyone prefers white/dark sand, despite how valuable it is. 
Maybe a buff to make it produce more oil than dark sand will make it a bit more attractive for players?

**Comment by itcannotbe** [comment]
The only reason that people should choose shale over dark sand is when you don't have enough sand tiles to suffice your needs, that said. Map makers should actually use dark sand less -_-.

**Comment by genNAowl** [comment]
True, but people really like their sand to silicon/sand to plastinum schematics; Which is why as long as there is any sort of sand basically no one will ever use shale.

**Comment by itcannotbe** [comment]
> True, but people really like their sand to silicon/sand to plastanium schematics; Which is why as long as there is any sort of sand basically no one will ever use shale.

Maybe make dark sand produce less sand than regular sand, this way there is less sand to go around.

**Comment by joshuaptfan** [comment]
Maybe swap oil extractor affinities on shale and dark sand: 150% on shale, 100% on dark sand. That way shale is best at the thing it specializes at, providing oil.

**Comment by itcannotbe** [comment]
That would kinda be nice.

But the confusion it brings. LOL.

**Comment by itcannotbe** [comment]
Also schematics:
Dies.

**Comment by Humanoid-X** [comment]
YES PLEASE BUFF SHALE

**Comment by XxsuperdeadlysniperxX** [comment]
It wouldn't make no sense that dark sand gets a buff 100% cuz dark is infused with a f ton of oil, shale needs to 200% if it specializes in oil cuz shale it probably straight up a underground pouch of oil

**Comment by stoneRdev** [comment]
I like this idea, but I agree with @XxsuperdeadlysniperxX. Generally, this is not a realistic game, but for realism improvements like this I think a little more realism is needed. Adjusting shale would need other sand and dark sand adjusted. And maybe oil as well (can't have shale give more than an actual pool of oil)

**Comment by XxsuperdeadlysniperxX** [comment]
Well oil extractors need a affinity to be placed on but sand to operate how would giving us less sand help us and it needs water which you need either a water extractor or pump (depending on the situation) the main reason why the is not used more is _because_ it has been nerfed thermal pump needs a buff cuz it should be the best pump in the entire game cuz 4 rotary pumps EASILY beat a thermal pump

**Comment by XxsuperdeadlysniperxX** [comment]
Also @stoneRdev im going off of logic not realism if sand is dark and has a 150% oil extraction efficiency then the sand is 75-80% oil with the rest being sand also the drilling dropoff goes with it logically _because_ the oil in the sand slows down the drill because of its high viscosity


Game mechanics win

**Comment by XxsuperdeadlysniperxX** [comment]
And shale is ignored by most

**Comment by Bohaska** [comment]
> I was beginning to think that we should invite XxsuperdeadlysniperxX back

...

**Comment by itcannotbe** [comment]
The alternate is swapping the buff of dark sand and shale since it's nuch easier to place the oil extractor on dank sand since...... sand.

**Comment by XxsuperdeadlysniperxX** [comment]
A oil extractor could give coal as a byproduct of oil extraction, although this could be a bit over powered, if it's on shale cuz its a hard surface and the positioning of the oil would be pressurized, thus coal would be in suspended animation in the oil cuz the viscosity of oil is so high

**Comment by itcannotbe** [comment]
Frakking, read about it.

**Comment by XxsuperdeadlysniperxX** [comment]
Read about what?

**Comment by XxsuperdeadlysniperxX** [comment]
Coal in the oil make sense cuz the extraction of oil can make coal overtime and coal in the oil would make sense to why oil extraction on shale in slow

**Comment by genNAowl** [comment]
I don't think any buildings currently return both items and liquids, so this would be a weird mechanic.

**Comment by Kyllingene** [comment]
Wasn't it super buggy and aggravatingly hard to work with code-side?

**Comment by itcannotbe** [comment]
> Wasn't it super buggy and aggravatingly hard to work with code-side?

Which one?

**Comment by Kyllingene** [comment]
It was something that had to do with slag, but I might be thinking of an archaic two-liquid-input block.

**Comment by itcannotbe** [comment]
> It was something that had to do with slag

Nope.

> but I might be thinking of an archaic two-liquid-input block.

Yes it was.

**Comment by Kyllingene** [comment]
Ah, ok. Pardon my faulty memory.
