### ISSUE TITLE
Mapmaker requests 

### ISSUE THREAD

**Issue by modern500** [Anuken/Mindustry-Suggestions#213]
1: add a case in editor  that, if checked,  the random  generation  will  not  overlap the player placed tiles. This would help make attack and survival maps that can both use random  generation  and not ruin  the esthetic  of the maps. As a map creator myself,  I run  into  this  problem  pretty often,  and it would  help a lot to make maps that are new at each playthrough,  and that use drills that work as intended by the  creator. I would call  it "random overlap"

2. Add something similar to ignore,  as a filter.  It would ignore  completely a specific tile/wall, making  that tile unaffected  by all terrain  generators.  This  would make  it so that maps could only  make a part of the terrain  random,  or make rivers not go through  prebuilt  structures.  Another  plus of this filter  would be of being able  to  make ores more present  in one area  than  another,  as you could  add the filter, add an ore spawn, delete  the  filters, and add another  ore spawn.  This is another one I would  greatly  appreciate  if added.  I would  call it "ignore element".

3. An addition,  a modification of the mirror  design  maybe,  that may mirror  the map multiple  times. I was thinking  maybe of a kaleidoscope-line effect. Similarly to the  mirror,  it may help  make maps quicker  and easier  than  before.  It would  maybe  be called Kaleidoscope. 

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Zenith-LY** [comment]
So you are not happy with random ore gemeration? Go to map info > generation. There you will see a page same as gemerate tab except it is a random generator. If you don't want any ores to randkmly generated then delete all ore related things. There is also random blocks like rock and if it stays there it will randomly generate rock on any stone tile because that it is configured like that (you can change it). If you also want some randomness you can also add something.
