### ISSUE TITLE
Buff steam

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#2130]
**Describe what you would like changed, and why.**

since steam gen now requires metaglass why not buff little

**Describe the changes you want to propose. Include possible alternatives.**
buff it to 360 power

**Comment by Anuken** [comment]
hmmm

**Comment by Coolhandluke348** [comment]
Well, the issue for ground maps now is you need to get through sili and meta on just combusts so don’t immediately write it off

**Comment by Coolhandluke348** [comment]
> Well, the issue for ground maps now is you need to get through sili and meta on just combusts so don’t immediately write it off

This can be even tougher when you have limited coal and sand

**Comment by unjown** [comment]
1, is if you have metaglass and sili of coarse you will get thermals it produces more power 

so hence steam very useless now
2. also its just slight buffing

**Comment by itcannotbe** [comment]
> 1, is if you have metaglass and sili of coarse you will get thermals it produces more power
>
> so hence steam very useless now

If there are no blocks with heat attributes, you can't even use thermal generators.
Your point?

> 2. also its just slight buffing

So how does a slight buff help with it's supposed "uselessness"?

**Comment by Slava0135** [comment]
> so hence steam very useless now

And that's why everyone spam them ok
Steam is fine as it is. Just use pumps or differential gen if no water is present

**Comment by Coolhandluke348** [comment]
> > so hence steam very useless now
> 
> And that's why everyone spam them ok
> Steam is fine as it is. Just use pumps or differential gen if no water is present

Everyone spams because they’re useless? wtf
Everyone spams them because no one wants to deal with using combusts until you get to diff gens, which takes power and eco to get

**Comment by Kyllingene** [comment]
> Everyone spams because they’re useless? wtf

ah yes the rare literary masterpiece: *sarcasm*

> Everyone spams them because no one wants to deal with using combusts until you get to diff gens, which takes power and eco to get

The diff gen is really not that hard to make and sustain, so you wouldn't have to resort to spamming steam gens. Yes, you would use them. Depending on your situation, you may use them a lot. But a diff gen would not take long to make.

**Comment by G0nTar** [comment]
Gens are perfectly fine as they are right now, in fact I would add metal glass to steam gens too.
