### ISSUE TITLE
1x1 Drill

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2132]
**Describe the content or mechanics you are proposing.**
This is a 1x1 drill that drills for ores. There are a couple of options.

1. Be like pretty much every mod and add 1x1 versions of the mechanic and pneumatic drills. They're clones of the 2x2 versions in every way except that they drill at 1/4th the efficiency. This is the easiest option.

2. Add only 1 drill that is cheap and is about the same drilling ability as 1/4th pneumatic drill.

3. Add an expensive version which is meant for mid-late game. This option gives it maximum utility.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1. I've played with this via mods and the mini drills don't replace any other drills. They're main use is to get a tiny bit of extra efficiency while saving a ton of space. They can fit in corners where larger drills (expecially 4x4) can't. Some maps have tight corners where these 1x1 drills would especially come in handy because placing a 4x4 blast drill in lean ore regions wastes a lot of space. They're cheap and can be used early game or even late game.

2. Same as 1 but this option reduces the redundancy a bit. People already don't use mechanical drills for anything except as a game-starter, so having a 1x1 mechanical drill seems even more pointless. Instead just add the 1x1 pneumatic drill.

3. The point of this option is that it can mine any ore, even thorium. This gives it maximum utility but doesn't make it OP. I've also played with this option via mods and it (sometimes, depending on the mod) doesn't outclass 4x4 or 3x3 drills but rather accompanies them. To make it balanced, this drill must be slower than 3x3 and must cost a mid-game item (Thorium? So that players have to use a 3x3 before having access to a 1x1).

Every single category of mining/production has a 1x1 version except drills. I feel 1x1 drills would be appreciated for their utility. I can't believe no one has suggested this yet. Did I miss an earlier suggestion? I swear I checked.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X ] I have checked the [Trello](https://trello.com/b/c82tMFl1/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [ X ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Nobody say "mods". I know mods exist. I've made my own. I've played with mods that add this exact suggestion. The whole point of me suggesting this is to add it to the vanilla game.

**Comment by itcannotbe** [comment]
When you realize that the no longer has 1x1 drills and there's a reason for that.

If you really want to, try classic and early v4.

All in all, 1x1 doesn't make sense in the game anymore.

**Comment by Slava0135** [comment]
no

**Comment by Bohaska** [comment]
> no longer has 1x1 drills and there's a reason for that.

Small question: What is the reason? Just interested

**Comment by Bohaska** [comment]
@itcannotbe

**Comment by itcannotbe** [comment]
It was tedious to place 1x1 drills as evidenced by v3 and early v4
