### ISSUE TITLE
Ability to use logic to swap out a unit's AI into another one.

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2133]
**Describe the content or mechanics you are proposing.**
I would like for there to be an option to change the AI that the unit is using, in case it needs to do something else. You can swap between existing AI's already in the code, and change the roles of a unit easily. For example, you can swap mega's heal AI for poly's build AI, making a mega that automatically repairs buildings instead.

Also, add an AI like https://github.com/Anuken/Mindustry-Suggestions/issues/2126 in the code.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You don't need to be an expert Java programmer in order to make units do other stuff, and I don't see anything bad about making this. 

I don't have much time now, I would write a nicer suggestion later

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
i like this a lot

and i mean _A_ lot

**Comment by Kyllingene** [comment]
very agree
much good
yes plz

**Comment by iLagSoUhax** [comment]
really good suggestion, 10/10 approve

**Comment by OnyxFinger** [comment]
I very much approve too
