### ISSUE TITLE
Forcefield shape and color on unitforcefield ability and force projector

### ISSUE THREAD

**Issue by Joshwelyt** [Anuken/Mindustry-Suggestions#2134]
**Describe the content or mechanics you are proposing.**
Modded unit forcefield ability and force projector
Should have color: and shape:
Eg color: a2a2a2 and shape: circle
This would make some mods feel more unique than others with different force proj colors and shapes
BTW this is hjson/json
This might be already done on js

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Unique unit forcefield ability and forceproj

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [#1985] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.-

**Comment by Joshwelyt** [comment]
Bru

**Comment by Bohaska** [comment]
More of a nice to have than an important suggestion....

**Comment by Joshwelyt** [comment]
#228 is team colored this is manualy colored by modding and cannot be changed by team changing
#1985 eh well its just for force proj as ive seen there
While this is for force field ability for unit and force rpoj
This is also able to be modded with shape:
