### ISSUE TITLE
New late game unit who dig the indestructible wall

### ISSUE THREAD

**Issue by Taxxxi** [Anuken/Mindustry-Suggestions#2136]
**Describe the content or mechanics you are proposing.**
A simple unit who dig the indestructible wall to expend the terrain (with a limit)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Im not in the multiplayer community but maybe some of them will find a way to use it well for some pvp/multiplayer scenario.
For the campaign i dont think it will be use as a winning stategy but it will add some possibilty for the player who like to optimize their production by revealing more ressource/new late game ressources (ex: digging sandstone wall to reveal sand under it.) or to give acces to inaccessible spot.
The unit can have upgrade too (ex: first dig only dirt wall, second can dig salt(white) and ice wall, third can dig sandstone wall, etc..)
to conclude i dont think it will change the difficulty of the game it can only add "possibility" and i hope you like the idea !!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ShadeStrike62** [comment]
i get the idea, but the game really isn't built for the background blocks to be moved or broken, so this suggestion would take a LOT more coding than you think it would to implement. Perhaps in v7 map design will change to accommodate this, and I'm not against your idea, I just don't see it happening soon :(

**Comment by joshuaptfan** [comment]
Currently, solid tiles do not have ground underneath them. What you see is what you get.

Also, if you give players any ability at all to destroy solid tiles, rest assured that many players will abuse that to destroy _every_ solid tile on the map, eventually paving every map into a boring parking lot.

So not only would this suggestion take a lot of work to implement, and break compatibility with every existing map, but it would also ruin gameplay.

**Comment by Bohaska** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/854

> - [X] I have
>### not
>followed the template

**Comment by joshuaptfan** [comment]
Ok, so I tested in the map editor, and walls built on top of ground and ore do not replace that ground and ore, but are on top of it. So technically you can have a mechanic that destroys terrain walls to reveal ground/ore underneath... but none of the thousands of existing maps were designed with wall destruction in mind, with thoughtfully placed hidden ore underneath. So this is still not a viable suggestion.

Also, walls exist to restrict player building and make maps unique. From a game design perspective, you have to understand that some restrictions on player freedom are intentional and should not be bypassable.
