### ISSUE TITLE
keyboard zoom control in editor

### ISSUE THREAD

**Issue by PolloUsami** [Anuken/Mindustry-Suggestions#2138]
**Describe the content or mechanics you are proposing.**
actualy the editor only has zoom with the mouse, but allow to zoom in and out with the keys + / -

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it would be nice for laptop users, or ppl that have a really bad mouse

( i tested with every key and no one do that funtion )

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
or make this setting able to be changed....

**Comment by joshuaptfan** [comment]
On laptops, you are able to zoom using whatever scroll functionality the touchpad offers (2-finger scroll, or swiping along the edge of the touchpad for very old laptops).

**Comment by PolloUsami** [comment]
> On laptops, you are able to zoom using whatever scroll functionality the touchpad offers (2-finger scroll, or swiping along the edge of the touchpad for very old laptops).

tried and not working
