### ISSUE TITLE
negative coordenates on the display

### ISSUE THREAD

**Issue by Alstin112** [Anuken/Mindustry-Suggestions#2139]
**Describe what you would like changed, and why.**

currently, when a player tries to draw an object in a negative coordinate, instead of the object appearing in the left / bottom, it is created off the screen on the right / top.

**Describe the changes you want to propose. Include possible alternatives.**

I would like the object to be created in the place where it was requested, so that drawing triangles with negative coordinates would not be extremely complicated and you would not need to draw multiple triangles to represent just 1.

**Comment by Newguy-ish** [comment]
Fuck yes

**Comment by liuxilu** [comment]
I would describe it more technical: negative coordinates flipped. And I think it's a bug.
It turns out negative int coordinates are cutted into their lower 9 bits. So -20 becomes 492.

**Comment by liuxilu** [comment]
Implemented by https://github.com/Anuken/Mindustry/commit/d545dc0d027204af270f2205ca99966e51897a3c, please close this issue.
