### ISSUE TITLE
Permanent dashboard to display the content of the core

### ISSUE THREAD

**Issue by Adirelle** [Anuken/Mindustry-Suggestions#214]
**Describe the content or mechanics you are proposing.**

Simply display the current content of your core in a little dashboard in the top left corner of the screen.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Right now, you have to scroll to find your core and click on it to see what it contains. A permanent dashboard would allow to check it in a glimpse.

Optional enhancements could be : 
* display topped resources in red,
* switch the displayed values between core content, orbital resources, and/or launched resources since the start of the game.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
It is planned. [relevant trello](https://trello.com/c/37Bbw8oK/177-better-inventory-ui)

**Comment by DeltaNedas** [comment]
possible in 5.0 ||hint-hint use deltanedss/ui-lib best mod||
