### ISSUE TITLE
Add to airblast drill recipe surge alloy

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2140]
Airblast drill very powerful drill and it's late-game building, but in game (mainly custom game) i see no reason to use laser drills after getting thorium. This drill got buffed in 6.0, but recipe so cheap, also, surge alloy rarely used to buildings and one surge factory enough on whole game with the exception of bullets

**Comment by WinterCrystal** [comment]
> surge alloy rarely used to buildings and one serge factory enough on whole game with the exception of bullets
Surge alloy is meant to be a lategame material, it is used for building t5 units, foreshadow, spectre, meltdown and other lategame buildings, and advance tech. This material is very, very much used if you want to survive in the lategame, adding surge alloy to the recipe of the airblast drill messes up the entire game as people would almost always build alloy smelters in maybe in the early or midgame just to make airblast drills which in turn would mess up their economy as surge alloy requires 4 materials to be inputted into an alloy smelter. This material is a hard thing to produce, let alone mass produce to any meaningful amount. The niche of the laser drill is to get thorium and to get other resources that it can drill at faster rate than both pneumatic and mechanical drills, it was never meant to to be used until in the lategame. Lastly, the template is nowhere to be found.

**Comment by itcannotbe** [comment]
@WinterCrystal you dunce. He has answered what the template asked not get off your high chair and get on a high chair meant for toddlers.

Surely it would mess up the meta like what happened with water extractors, but this chang is just minor and wouldn't affect late game progression. You'll have to deal with the minor inconvenience of swapping drill out later in the game. And yes laser drills are as good as airblast, except when watered.

The fact that people are breezing over the third tier drill is something that bothered me for a long time and this change is welcome. And surge is just annoying to make, but that that hard.

**Comment by Slava0135** [comment]
> @WinterCrystal you dunce. He has answered what the template asked not get off your high chair and get on a high chair meant for toddlers.
> 
> Surely it would mess up the meta like what happened with water extractors, but this chang is just minor and wouldn't affect late game progression. You'll have to deal with the minor inconvenience of swapping drill out later in the game. And yes laser drills are as good as airblast, except when watered.
> 
> The fact that people are breezing over the third tier drill is something that bothered me for a long time and this change is welcome. And surge is just annoying to make, but that that hard.

same

**Comment by TheNightglow** [comment]
i never understood why ppl keep using airblast drills for everything... am I missing something?
the airblast is only just as fast as a laser drill... and costs vastly more power

I always thought the airblast would be only for the very specific scenario that you have a 4x4 ore field... otherwise usually building multiple laser drills is better than a single airblast right? (less power for the same resource production)

**Comment by itcannotbe** [comment]
@TheNightglow

**Comment by TheNightglow** [comment]
oooooh i see

it has a vastly higher water multiplier, thats what makes it better

**Comment by BlueWolf3682** [comment]
This is not necessary. Dtills are supposed to be easy and cheap, and airblast does not have enough speed even with water to warrant surge. Also, this would lead to massive surge defecits on multiplayet due to all the noobs spamming airblasts. Plastanium at most could be added to build cost, no higher.

**Comment by itcannotbe** [comment]
> This is not necessary. Drills are supposed to be easy and cheap, and airblast does not have enough speed even with water to warrant surge.

Wasn't that the same thinking people used with water extractors?

**Comment by Coolhandluke348** [comment]
> The fact that people are breezing over the third tier drill is something that bothered me for a long time and this change is welcome. And surge is just annoying to make, but that that hard.

Changes that intentionally make the game tedious or annoying are not great. The benefits of surge are meant to be for late-game purposes because of the required inputs. Airblast drills are for mid-game purposes and it doesn't make sense to require you to make surge if you don't need it until late-game.

**Comment by itcannotbe** [comment]
So what tier are laser's the never used in the game tier? or the only used to get some thorium tier?

**Comment by Coolhandluke348** [comment]
Laser drills have their purpose in games without access to thorium, and the whole point of the game is to upgrade your eco, so why are you suggesting changes to limit eco growth?

**Comment by itcannotbe** [comment]
And face the facts. The only advantage airblast gives is a measly +.67% and that's only when you use water. Otherwise you could use laser.

**Comment by Coolhandluke348** [comment]
You're tunneling on the argument that lasers aren't used much and you're acting like that's the player's fault. Maybe there should be more incentive for it.

**Comment by itcannotbe** [comment]
> Laser drills have their purpose in games without access to thorium, and the whole point of the game is to upgrade your eco, so why are you suggesting changes to limit eco growth?

Oh wow. Nice use case. And freaking edge case.

**Comment by Coolhandluke348** [comment]
> And face the facts. The only advantage airblast gives is a measly +.67% and that's only when you use water. Otherwise you could use laser.

So why for a .67% boost do you have to make surge?

**Comment by Coolhandluke348** [comment]
Are we going to have a respectful discussion or are you going to continue to be a child. Grow tf up dude

**Comment by Coolhandluke348** [comment]
> Historically people have been breezing over laser. like it's not even a option.

Because there isn't any benefit to using it.

**Comment by itcannotbe** [comment]
> You're tunneling on the argument that lasers aren't used much and you're acting like that's the player's fault. Maybe there should be more incentive for it.

FOR ALL I CARE REMOVE LASERS FROM EXISTENCE IF THE DEV DOESN'T MAKE PEOPLE USE THEM ONE WAY OR THE OTHER.

PEOPLE HAVE BEEN OBSESSED WITH BUFF LATELY, even I can't wrap my head around it.

**Comment by Coolhandluke348** [comment]
> FOR ALL I CARE REMOVE LASERS FROM EXISTENCE IF THE DEV DOESN'T MAKE PEOPLE USE THEM ONE WAY OR THE OTHER.


It still takes thorium to make airblasts and there's almost no point in using an airblast on a 3x3 ore chunk.

**Comment by itcannotbe** [comment]
> > Historically people have been breezing over laser. like it's not even a option.
> 
> Because there isn't any benefit to using it.

There is, lower power consumption.

**Comment by itcannotbe** [comment]
> > And face the facts. The only advantage airblast gives is a measly +.67% and that's only when you use water. Otherwise you could use laser.
> 
> So why for a .67% boost do you have to make surge?

You could always bring the boost up.

**Comment by Coolhandluke348** [comment]
> There is, lower power consumption.

Alright, but why would you use a laser on a 4x4 ore chunk?

**Comment by itcannotbe** [comment]
> > FOR ALL I CARE REMOVE LASERS FROM EXISTENCE IF THE DEV DOESN'T MAKE PEOPLE USE THEM ONE WAY OR THE OTHER.
> 
> It still takes thorium to make airblasts and there's almost no point in using an airblast on a 3x3 ore chunk.

Ask the community. They would even choose to put an airblast on a 1x1 chunk.

**Comment by Coolhandluke348** [comment]
> You could always bring the boost up.

But why would you do that if the whole point is that people use airblasts too much? This would just make people rush airblasts more.

**Comment by Coolhandluke348** [comment]
> Ask the community. They would even choose to put an airblast on a 1x1 chunk.

The community is very against adding surge to it, I'm not opposed to having a reason to use lasers, but I don't think this is a good solution.

**Comment by itcannotbe** [comment]
Well rushing. No. The amount of time required to make surge is a pain already and it justify the point of bring airblast to the last tier.

**Comment by itcannotbe** [comment]
> > Ask the community. They would even choose to put an airblast on a 1x1 chunk.
> 
> The community is very against adding surge to it, I'm not opposed to having a reason to use lasers, but I don't think this is a good solution.

Define community? The same bunch who were against metaglass on water extractor?

**Comment by Coolhandluke348** [comment]
Like I said, making the game more tedious is not the way to make a game more enjoyable

**Comment by itcannotbe** [comment]
What's so tedious about it?

**Comment by Coolhandluke348** [comment]
> And surge is just annoying to make, but that that hard.

It takes 4 inputs...

**Comment by itcannotbe** [comment]
Which are 3 are raw materials ans only 1 needs to made out from a crafting block.

**Comment by itcannotbe** [comment]
> Like I said, making the game more tedious is not the way to make a game more enjoyable

Was so tedious about it anyway?

**Comment by Coolhandluke348** [comment]
> Which are 3 are raw materials ans only 1 needs to made out from a crafting block.

5 inputs then, how is that not tedious?

**Comment by itcannotbe** [comment]
the abundance of raw materials doesn't make it tedious.

**Comment by Coolhandluke348** [comment]
Surge takes space, power, time, and resources to make. 
Tedious - too long, slow, or dull; tiresome or monotonous.
I play over 3-4 hours a day, making surge every time I just want to make an airblast drill even if I'm not going to late-game and I'm not planning on using late-game units or defenses makes it tedious.

**Comment by itcannotbe** [comment]
Plus you have a ton of schematics to choose from to make surge.

**Comment by itcannotbe** [comment]
> Surge takes space, power, time, and resources to make.
> Tedious - too long, slow, or dull; tiresome or monotonous.
> I play over 3-4 hours a day, making surge every time I just want to make an airblast drill even if I'm not going to late-game and I'm not planning on using late-game units or defenses makes it tedious.

You don't even have to make airblast to even to endgame.

**Comment by itcannotbe** [comment]
The resources that an airblast can mine is the same resources a laser can mine.

**Comment by Coolhandluke348** [comment]
> You don't even have to make airblast to even to endgame.

So what about pvp modes, or other servers? Have you ever tried to get people to stop using resources so you can rush surge?

**Comment by Coolhandluke348** [comment]
> The resources that an airblast can mine is the same resources a laser can mine.

That doesn't mean that using lasers is as quick or as effective

**Comment by itcannotbe** [comment]
So that's your only concern? Player behavior on servers and lasers which are just as effective as airblast.

**Comment by Coolhandluke348** [comment]
> So that's your only concern? Player behavior on servers and lasers which are just as effective as airblast.

Yes, I've played through the campaign already and a large portion of the community is purely on servers. The enjoyment I get from this game is actually playing with other people. You already said that the water boost on airblasts is better, and they are able to cover larger amounts of ore. My concern is that changes like this will make servers less enjoyable to play because rationing resources and careful planning on a team is near impossible.

**Comment by BlueWolf3682** [comment]
> > This is not necessary. Drills are supposed to be easy and cheap, and airblast does not have enough speed even with water to warrant surge.
> 
> Wasn't that the same thinking people used with water extractors?

Water extractors were not meant to be used as your main water source. Drill are meant to be used as your main item sources.

**Comment by Coolhandluke348** [comment]
> Water extractors were not meant to be used as your main water source. Drills are meant to be used as your main item sources.

But they are the only source on ground only maps

**Comment by BlueWolf3682** [comment]
They are a *last resort* if no pumpable water is available. Treat them as such.

**Comment by Coolhandluke348** [comment]
> They are a _last resort_ if no pumpable water is available. Treat them as such.

A large number of servers don't include water and they are quite necessary for any efficient designs

**Comment by acoaco** [comment]
If anuken agree change it,something like laser drill need plastanium ,scatter need titanium will be implemented pretty soon lol

I can accept metaglass change but this one not,cuz it's pretty fair and simple you should produce metaglass before you get water
I don't want redesign all schematic use AB ,and it's just give griefer a good reason to spam lot alloy smelter destroy a game

**Comment by BlueWolf3682** [comment]
> > They are a _last resort_ if no pumpable water is available. Treat them as such.
> 
> A large number of servers don't include water and they are quite necessary for any efficient designs

Water extractor isn't efficient.
Wether server maps have water or not isnt a balancing concern.

**Comment by Coolhandluke348** [comment]
But maps without water should still be playable

**Comment by Bohaska** [comment]
> If anuken agree change it,something like laser drill need plastanium ,scatter need titanium will be implemented pretty soon lol

Stop slippery sloping stuff, its a bad logical fallacy and makes your argument invalid.

It's like not adding metaglass to watex because duos later will require thorium.

**Comment by Bohaska** [comment]
If mindustry had 0 realism requirement, I would add 10 pyratite to the recipe for airblast drill, as balancing

**Comment by TheNightglow** [comment]
well this thread kinda spiraled out of control lol

just my small opinion to that:
i didnt even know that airblast and laser drill can do anything differently, thought the one was a 4x4 version of the other (didnt see the water multiplier)

i think there should be some larger differentiation between the drills than that... (again they have literally the same speed if you dont hook them up to water)
like make airblast drills better than laser by default (without water multiplier) but let them cost some additional requirement (like it needs to be hooked up to cryofluid to work or needs some more expensive resource to be build (like surge))

right now airblast and laser drills are the same tier, neither beeing endgame...

seems the only reason to build laser are:
- you havent realized that airblast gets a larger boost from water than laser
- you are trying to save some power

**Comment by BlueThecno** [comment]
Isn't the airblast unlocked after you complete Nuclear Production Complex? Also, the airblast is not faster by just 0.67% compared to the laser drill

>All calculations without taking in account Overdrive Proyector or Dome Boosts
>>>

The Lasers Drill mine speed (Asuming 3x3 scrap patch) is 1.92 items/s with a max water boost speed of 4.9152 items/s (rounded up to 4.92)

The Airblasts Drill mine speed (Asuming 4x4 scrap patch) is 3.42 items/s with a max water boost speed of 11.0466 items/s (rounded up to 11.05)

That is a diference of 6.1314 items/s (rounded up to 6.13) Thats 55.49% diference! And yes, I made the math (I accept corrections tho, I might be wrong on something)

**Comment by TheNightglow** [comment]
> 
> 
> Isn't the airblast unlocked after you complete Nuclear Production Complex? Also, the airblast is not faster by just 0.67% compared to the laser drill
> 
> > All calculations without taking in account Overdrive Proyector or Dome Boosts
> > > >
> 
> The Lasers Drill mine speed (Asuming 3x3 scrap patch) is 1.92 items/s with a max water boost speed of 4.9152 items/s (rounded up to 4.92)
> 
> The Airblasts Drill mine speed (Asuming 4x4 scrap patch) is 3.42 items/s with a max water boost speed of 11.0466 items/s (rounded up to 11.05)
> 
> That is a diference of 6.1314 items/s (rounded up to 6.13) Thats 55.5% diference! And yes, I made the math (I accept corrections tho, I might be wrong on something)

no no no, you misunderstand, its about speed per ore, with your calculation it would be impossible to tell which drill is more efficient with different drill sizes, since the largest drill would always get the highest speed^^

Laser Speed per scrap ore: 0.21 per second
Airblast Speed per scrap ore: 0.21 per second

Watered Laser Speed per scrap ore: 0.54 per second
Watered Airblast Speed per scrap ore:  0.69 per second

so the Airblast is just 27% faster than the Laser drill (per ore)

the reason why your calculation is misleading is because you could very well just build more laser drills (and thus drill size doesnt really matter since you can simply build more of a smaller one^^)

**Comment by Bohaska** [comment]
I checked, in the code, the mineSpeed variables for laser and airblast drills are the same

**Comment by BlueThecno** [comment]
Oh I didn't take that into account, thanks for the correction, although 27%
is still higher than 0.67% so yeah.

**Comment by Bohaska** [comment]
Airblast needs to be buffed and nerfed (increased performance, more expensive recipe)

**Comment by Bohaska** [comment]
@Coolhandluke348 forgot to ping you

**Comment by G0nTar** [comment]
I like the add plastanium to the airblast drill construction materials
