### ISSUE TITLE
Teleportation?

### ISSUE THREAD

**Issue by welliguess** [Anuken/Mindustry-Suggestions#2142]
Firstly, I love the game. But I have a few ideas for how to improve this already amazing game.. 

I am aware that there's ground, air, and naval units, but ever think of having some enemy units teleport and destroy the core? Might be very hard to adjust this game to this, but make it a boss or have a force field block (not the projector) that prevents it from teleporting in a specific area?

Thank you for reading, that was all I had. Keep up the great work :)

**Comment by Kyllingene** [comment]
![image](https://user-images.githubusercontent.com/69094702/110808644-0b581200-8239-11eb-8163-e189a36bb3ff.png)

**Comment by the-kido** [comment]
yeah no you're going to be in for a treat in this comment section

**Comment by TheRealIvyX** [comment]
where is the template

**Comment by Kyllingene** [comment]
poor guy

**Comment by joshuaptfan** [comment]
Also obviously OP and needlessly frustrating for players. Have you seen the amount of complaining about difficulty?

**Comment by RedstonerKBC** [comment]
> image

I don't think the dude is talking about block teleporters. I think they're talking about unit teleporters. If teleporting units or teleportation of any kind shouldn't be suggested, maybe someone should update the README to make it more clear. I also was under the impression that that line only meant teleporter blocks like in Mindustry Classic.

**Comment by stoneRdev** [comment]
I rather don't like the idea of teleporting units (or resources, but we all know tellying resources is a no no).

First off, not only does this give an extreme advantage to enemies, but also to players on enemy base maps. Imagine tellying your units to the side of an enemy base, where there's little to no defense. Either the maps would need updated to include more side defense, or the game's logic would need to prevent this (somehow).

Secondly, imagine the headaches this will cause. Where do these units get teleported. What are the teleporting rules? Do ground units need open ground to teleport to? If so, then you would need to check the destination area for room. Meaning you can encase your base in walls, but small units will teleport to your conveyors , while large units can't be. Unless teleporting on conveyors is not allowed, in which case you could just enclose your base in walls, but then that becomes pretty much the only way to play against teleporting enemies. It could get very messy trying to implement this (it's not like a 3d game where you can just spawn above everything)

**Comment by ScepterReignPlayz** [comment]
Obviously op also have you read Read.md?

**Comment by YoMamaLlama1** [comment]
If you want at least resources to be teleported use the itch classic [https://anuke.itch.io/mindustry-classic](url)

**Comment by vooxal** [comment]
![image](https://user-images.githubusercontent.com/58456527/112729355-e75b2880-8ee8-11eb-9a6e-77f921750c9b.png)
