### ISSUE TITLE
Overdrive Affect Phase Bridge or Phase Conveyor

### ISSUE THREAD

**Issue by Vincast26** [Anuken/Mindustry-Suggestions#2143]
**Describe what you would like changed, and why.**
Make Overdrive affect bridge or phase conveyor, sometimes when i make a big schem with lots of bridge and phase conveyor, i can't really use overdrive on it since it will make factory produce too fast than the bridge can transport.

**Describe the changes you want to propose. Include possible alternatives.**
Overdrive affect Bridge Conveyor/Phase Conveyor speed.

**Comment by BlueWolf3682** [comment]
it does.

**Comment by G0nTar** [comment]
Is this a joke?

 Phase has instant transport speed, you can't buff "instant" to a faster "instant" last time I checked my basic math, it's a fact you will never change that.

Wait I have an idea:
 Hey, cheer up, your suggestion was already implemented, they just told me phase now transports items 99999% faster, it's like it teleports them or "phases" them from 1 point to another

**Comment by Vincast26** [comment]
If it where instant, why is it only 25/s?
An instant should be like those item sorter or overflow.

Pada tanggal Sab, 13 Mar 2021 01.07, GonTar ***@***.***>
menulis:

**Comment by itcannotbe** [comment]
Instant != Infinite throughput you dunce.

**Comment by BlueWolf3682** [comment]
So I checked the source code and Phase Conveyor is indeed unable to be overdriven, though bridge definitely is overdriveable.
