### ISSUE TITLE
Bluetooth multiplayer

### ISSUE THREAD

**Issue by Swagwagon** [Anuken/Mindustry-Suggestions#2144]
**Describe the content or mechanics you are proposing.**
I think it would be awesome if I could play with someone over bluetooth. I've seen this done in a few other games. It would just make it easier to play multiplayer in most situations, and make multiplayer possible offline.
Thanks for reading.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Cherriodude** [comment]
But you already can? Haven't tested but pretty sure using a hotspot or similar will let you play.

**Comment by RedstonerKBC** [comment]
If you go to **join game** there's a section called **local servers**. This shows all of the multiplayer servers on the same network as you. I'm not sure if it will work via bluetooth though. Maybe someone else can comment further?

**Comment by stoneRdev** [comment]
I will say a no to bluetooth (as laggy as I see lan games get, I'd hate to see it on bluetooth). @Cherriodude has the right idea tho, make a hotspot on your phone and have everyone connect to it, or if you have a spare router you dont event need internet. 

As for hotspot tho, some phones don't have them (or try to charge you for it), so if this is the case for you, try using [foxfi](http://foxfi.com/) or [pdanet](http://pdanet.co/)
