### ISSUE TITLE
CAMPAIGN: Allow core schematic placement upon landing 

### ISSUE THREAD

**Issue by lammaer** [Anuken/Mindustry-Suggestions#2145]
**Describe the content or mechanics you are proposing.**

When launched to a new region, instead of just dropping the selected core schematic to a predefined place, allow the players to place the schematic within a landing area circle  (this includes rotating, flipping moving around the schematic as the normal schematic placement behavior). 
Upon placing, the schematic created instantly, and the battle starts. 
The game is paused until the player places the core schematic. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

In campaign, when we start to use Core schematics, it's very disturbing that upon landing it may happen that half of the core is missing because of terrain features. This basically invalidates / negates the Core Schema feature (which is great and a must for the extreme/eradication level regions). 
Lots of us uses "scouting" as a workaround: landing with an basic core to the new region, check which schematic might fit (maybe it needs to be rotated, so in creative just create a new core schematic with a rotated version of the existing one) what is really cumbersome and tedious. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stoneRdev** [comment]
I'm down for this. It would definitely allow for a better tactical start, and maybe give players a chance to see the area before they give a whack at it.

But I do see some possible issues in implementing this.
For example, if a player uses this feature, goes to choose a core placement, sees the map, then what if they close the game?  If the game doesn't save that state, players could abuse this feature by using it to see a map then closing the game out if they don't like that map, thereby seeing the sector for free. There would need to be a way for the campaign to save that state and launch straight back into core placement to avoid this.

**Comment by Bohaska** [comment]
only allow you to see in a 40x40 radius?

**Comment by itcannotbe** [comment]
Is this another #1839.

**Comment by lammaer** [comment]
> Is this another #1839.
Almost. Just with a bit more brave dreaming :)

**Comment by lammaer** [comment]
> For example, if a player uses this feature, goes to choose a core placement, sees the map, then what if they close the game? If the game doesn't save that state, players could abuse this feature by using it to see a map then closing the game out if they don't like that map, thereby seeing the sector for free. There would need to be a way for the campaign to save that state and launch straight back into core placement to avoid this.

So honestly, what is the difference compared to dropping a bare basic core for scouting (what is the current meta)? 
I don't think scouting itself, seeing the map is something what should be forbidden.

**Comment by Coolhandluke348** [comment]
Alright so just give a 21x21 view or something so ppl can see how it gets placed

**Comment by bruhmoment271** [comment]
To solve the problem of the player seeing the map for free, the map shown could be very basic. Eg. only indicate whether a tile is a wall, floor, or enemy spawn zone.

**Comment by OnyxFinger** [comment]
Just yes, I would love that
