### ISSUE TITLE
Speed Senseable

### ISSUE THREAD

**Issue by FlippingPotatoes** [Anuken/Mindustry-Suggestions#2146]
**Describe the content or mechanics you are proposing.**

Added sensor @speed that returns the core database speed for units (possibly blocks as well in regards to conveyor move speed)

(Although conduit speed isn’t listed, possibly returning that as well?)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Will allow for unit control to determine better approximates for time to complete activities, without requiring the user to hardcore these values (similarly to the purpose of @range).

Another simple use case would be in conjunction with within commands, to start up processes only when the unit is within a range relative to how long it’ll take for them to arrive somewhere. ie. Speed based timers/gates

For blocks, it could likely be used to approximate throughput, though likely this use case is more limited.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
*Pleeeease* make sure to seperate things like @ range doesn't ping a poor, random person. I mean, imagine if someone implemented a sensor in a different game, and the sensor was @FlippingPotatoes. You don't even know what the game is, you just got pinged randomly.

Otherwise, +1.

Actually, I might make a (poorly done) PR for this. Don't expect my fix to go through.

**Comment by FlippingPotatoes** [comment]
My apologies, hadn’t known @ served to ping a user (I’m not particularly familiar with GitHub), won’t happen again :0
