### ISSUE TITLE
Option to change music

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#2147]
**Describe the content or mechanics you are proposing.**
an button to change music / override the current music

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

better music :)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GlennFolker** [comment]
Mods.

**Comment by Lele567** [comment]
mute the game's music then play your own track

**Comment by RedstonerKBC** [comment]
> Mods.

The dude wants it in the main game, not mods. That's why they made the suggestion in the first place :upside_down_face:

**Comment by Kyllingene** [comment]
> mute the game's music then play your own track

**Comment by itcannotbe** [comment]
> > Mods.
> 
> The dude wants it in the main game, not mods. That's why they made the suggestion in the first place 🙃

Dude. letting users choose their own music is like asking for mods. Unless users want to choose from some pre-selected tracks

**Comment by stuffyAI** [comment]
> The dude wants it in the main game, not mods. That's why they made the suggestion in the first place upside_down_face

This is a mods thing 100%, it's absolutely not the norm to let the user play their music as part of the game, heck if one would actually try they could recompile Mindustry with their tracks replacing original ones.

**Comment by Kyllingene** [comment]
Not that recompiling is the best thing to suggest for the layman, but seriously, we don't need this. Not only can you just *play your own music*, you can download mods easily which replace the music. It would be sooooo easy to just make a script which takes an audio file and makes a mod replacing the music in the game with that file. Assuming Mindustry would like that, of course.
