### ISSUE TITLE
Unit Self-Destruct

### ISSUE THREAD

**Issue by 348joey** [Anuken/Mindustry-Suggestions#2148]
Sorry in advance if I've messed this up. I'm not very good with forums.

**Description of the content or mechanics I am proposing:**
The ability for the player's units to self-destruct on command.

**Description of how I think this content will improve the game:**
When working Reconstructor schematics in sandbox, I currently have to have some enemy turrets around for them to rally to to not hit the build limit. In the campaign and other maps, it's also kind of annoying moving units I no longer need out of the way when I'm trying to build somewhere they're standing or see what's under them. If the map has deep enough water and my unit can't stand on it or float, I can use that to kill them, but I then have to manually select and control them in groups to get them to the deep end and sink. An easy-to-not-accidentally-use self-destruct option would be a nice convivence to have. It'd also help for when you need to clear out a reconstructor or builder that's trying to make something you already have the maximum amount of. I'd like to be able to just select one of the maxed units and kill it to clear up space rather than having to partially deconstruct the building and rebuild it to clear its contents, not to mention having to empty it of resources if I don't want them wasted.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.* (The preview shows that they've turned into checkmarks instead of x's. I'm assuming this is intentional.)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (I searched "Self destruct", "self-destruct", "Destroy own units", and "sucide". There was a comment on one of the closed threads that suggested this, but the thread itself was "Trying to control a disabled unit(over the unit limit with a red warning sign) should kill it #530", and that's more about auto destroying a unit that's trying to be built. That idea would help in some ways, but it'd also create its own problems. I'm not sure if comments made in other threads or threads with distinct but somewhat similar ideas count as being suggested. If they do and I've just wasted your time, or if I've somehow missed a thread with this suggestion, I'm really, really sorry, and you can close this without reply or just ignore it.)
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. (I looked at all the "cards", including the ones you have to drag the screen to see. None matched any of my suggestions.)
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. (I have 717 hours in this game, and I've posted 25 distinct schematics to the workshop, not counting the updates to existing ones. I checked the wiki just in case anyway though.)
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category. (Yes I read it.)

**Comment by Lele567** [comment]
if you're in sandbox, connect a thorium reactor to an item source with thorium **without cryofluid**
this will blow up the reactor and can kill T3 and below quickly

**Comment by RedstonerKBC** [comment]
Do you mean self-destruct active units or only the ones in reconstructors? The former would add significant griefing potential.

**Comment by Kyllingene** [comment]
The suggestion seems to be targeting sandbox, and I agree tbh. Filling up your favorite testing map (I use it mainly for logic) with units is aggravating

**Comment by itcannotbe** [comment]
Why not just add a command via the command center that is sandbox only?

**Comment by Kyllingene** [comment]
Because then you are forced to kill *all* your units, something you often do not want to do. My immediate thought is a deconstruct square but for units, the problem being that it would be harder to implement.

**Comment by THEGAMER-10n** [comment]
Big problem if a griefer will do this to mees things up in a server...

**Comment by KyllTA** [comment]
> The suggestion seems to be targeting sandbox, and I agree tbh. Filling up your favorite testing map (I use it mainly for logic) with units is aggravating

**Comment by Bohaska** [comment]
> Big problem if a griefer will do this to mees things up in a server...

Only make this available in sandbox?

**Comment by Kyllingene** [comment]
> The suggestion seems to be targeting sandbox, and I agree tbh. Filling up your favorite testing map (I use it mainly for logic) with units is aggravating

**Comment by bruhmoment271** [comment]
> > Big problem if a griefer will do this to mees things up in a server...
> 
> Only make this available in sandbox?

or just make it a option in rules like "reactor explosions"

**Comment by G0nTar** [comment]
Grieffers would love this implemented.

You can just make a pipe of melted scrap (yes, it is that easy) that spits hot metal into any unit you don't want anymore.

Don't want to bother doing that simple task you say? Just send ur unit to any deep enough water/petroleum tile and watch as it goes extinct just like our old friends the dinosaurs.

What about maps that don't have water/oil you said? Just throw 1 blast compound to a hydro Gen or combustion Gen and pack ur units close to it so they all explode together, rly cheap.

No? Then just burn a coal line and put ur units on top of it, possibilities are endless....

**Comment by itcannotbe** [comment]
Someone missed that point that this is targeting sandbox. Not survival or PvP.

**Comment by abrasmag3** [comment]
if this is for sandbox singleplayer, why not use testing utilities mod?
