### ISSUE TITLE
Visible Junction Inventory

### ISSUE THREAD

**Issue by 348joey** [Anuken/Mindustry-Suggestions#2149]
**Describe the content or mechanics you are proposing.**
The ability to see the contents of junctions like you can for most other buildings.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It'd be much easier to find item clogs it you could see what's inside a junction. From what I can tell, a junction can hold up to 6 items in each direction, provided that _any_ block (including walls) was opposite the input side. If there's not another block on the other side, the junction won't accept items from that direction. It can also be hard for players to figure out that the contents of the junction will always try to output their opposite side. This is really hard for me to explain in words. Here's an example:
Say you have a filled conveyor line from your core with a junction in the middle that goes from left to right. There will be six items in the junction trying to output to the right but can't because that belt is full. If you reverse the direction of the belts to now go right to left, the junction will still have six items in it even after the belt has cleared, as the belt is no longer full, but it is now facing toward the junction and cannot receive those items. If, after clearing the line, you then turn the conveyor belt that is immediately right of the junction to face right, up, or down, the junction will spit out up to six items onto that belt now that it is no longer facing directly towards the junction.
I hope I explained that well enough. Anyway, it'd be useful to see what items are inside a junction not only to unclog them, but also to retrieve the few extra items that remain after reversing a belt's direction. It's a real hassle to delete a junction that was next to a processing building just because an item the factory can't accept got inside the junction.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (I searched "junction inventory" and "junction contents".)
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
You did not search for similar suggestions, but let me explain:

This is extremely hard and annoying to do, since Junctions can hold multiple items for all 4 directions, netting you an up to 4x6 item grid just to show the contents.
Not that it matters, since even in your case a simple rebuild will help with debugging, there should not be a hassle if you didn't mess up previously with rare plastanium-conveyor contraptions.

Its both to much effort and to mobile-unfriendly (size and data of overview) to implement for what you actually fulfill on the use-cases.

**Comment by 348joey** [comment]
> You did not search for similar suggestions, but let me explain:
> 
> This is extremely hard and annoying to do, since Junctions can hold multiple items for all 4 directions, netting you an up to 4x6 item grid just to show the contents.
> Not that it matters, since even in your case a simple rebuild will help with debugging, there should not be a hassle if you didn't mess up previously with rare plastanium-conveyor contraptions.
> 
> Its both to much effort and to mobile-unfriendly (size and data of overview) to implement for what you actually fulfill on the use-cases.

Just knowing that there's anything in it at all would help honestly. Like a single dot for each cardinal direction to let you know there's something trying to go that way. Just a big "X" with a dot on each side. It would also help keep trach of which way items are flowing, kind of like how conveyors show their direction now. I'm aware I'm not a dev and know nothing about coding, so all I can advise on would be how a UI could _look_ without cluttering things up. If it's an intense use of resources to run or very complicated to code, then I understand.

Okay, I didn't search for similar suggestions? What other than "junction inventory" and "junction contents" should I have searched for? I don't like wasting dev's time, so if you could tell me what would've yielded results, I can improve my searches in the future and hopefully avoid making redundant suggestions.

What exactly do you mean by "rare plastanium-conveyor contraptions"? I didn't mention plastanium. Plastanium conveyors can't even use junctions anyway, unless you count unloading into them. This happens all the time when moving a conveyor line to a new direction if there's a junction involved, which there usually is. If a stray item gets into a feed that ends with a junction connected to any building, it will clog up the whole thing. If I was using imported items to fill a tetrative reconstructor while defeating the local enemy and win, I want to return the items to the core.

Yes, I know I could delete the junctions to debug, but I have no way of knowing which one has items in it and needs to be deleted.

"for what you actually fulfill on the use-cases." Just trying to make sure I understand what you mean here; by "use-cases" do you mean times when it would be used or useful? So, rephrased, it'd be "it's not worth implementing for the times it would come up"? It might be the autism, so sorry if I misinterpreted that.
