### ISSUE TITLE
silicon sorters look exactly like blank sorters

### ISSUE THREAD

**Issue by k3y3** [Anuken/Mindustry-Suggestions#215]
**Describe what you would like changed, and why.**
sorters set to blank look extremely similar to sorters set to silicon and it causes issues when I am using many kinds of sorters in order to create a schematic or setup

**Describe the changes you want to propose. Include possible alternatives.**
just make the silicon color on sorters/inverted sorters lighter so that it is a more noticable difference between blank/silicon

**Comment by ritzip** [comment]
It has already been changed in the upcoming update.

![78379118-302c1a00-75d2-11ea-93e3-a3b0253f69f9](https://user-images.githubusercontent.com/49394064/83371735-e73bea80-a3f5-11ea-928c-9a257b98cd18.png)
