### ISSUE TITLE
Cache the server list.

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2150]
**Describe the content or mechanics you are proposing.**
Cache the server list, as a backup in case you can't obtain it.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This thing probably only benefits a small number of people, but the CDN that the server list is hosted is blocked in my country, so I can't download it. This suggestion will fix that problem.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have not checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am not familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have not read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
nice, a dead chat

**Comment by Kyllingene** [comment]
You need to actually *connect* to the server list to cache it. What are you suggesting?
