### ISSUE TITLE
thermal extractor

### ISSUE THREAD

**Issue by reddrims** [Anuken/Mindustry-Suggestions#2151]
water extractor 2.0 produce absurd amont of water(60/sec) by consuming some power (300/sec), 3x3 or 4x4 build, can consume titanium, 

this can compact some design, some time, I have a lot of power but not that much space and I need water,so this build can be use full

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
This suggestion should be renamed "watex 2.0". Also,

> but no, just no.

> No
> 
> Just no
> 
> That won't happen at all

> Still, no

>it's FREAKING OVERPOWERED

**Comment by itcannotbe** [comment]
So you're the same person who suggested shematic folders.

**Comment by itcannotbe** [comment]
Incase people say I'm wrong. See for yourself. #2152

**Comment by joshuaptfan** [comment]
Water acquisition without pumping from water tiles is supposed to be difficult, to encourage players to seek water tiles for water.

**Comment by Humanoid-X** [comment]
Sure, just make it require, like, 100k surge alloys to build.

**Comment by YoMamaLlama1** [comment]
> Sure, just make it require, like, 100k surge alloys to build.

Since meta is now in make it... 500k?

**Comment by SheepCommander** [comment]
the surge alloy it requires should change in real time based on the world population of sheeps humans and goats combined
