### ISSUE TITLE
shematic folder

### ISSUE THREAD

**Issue by reddrims** [Anuken/Mindustry-Suggestions#2152]
**Describe the content or mechanics you are proposing.**
add folder to the schematic window, and tag to schematic:
-you can choose to add tag to schematic
-on the left there is a list of all tag ,clic on tag to only view schematic that have this tag

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I have a lot of schematic, so i need a way to organise this, so my schematic named "Ox_Silicon" can have the tag "silicon", "oil extractor", "middle game ", the schematic "micro factory" have "silicon", "early game", "graphite"
if I clic on "silicon", i can see this two schematic but not "core_def1" because core_def1 don't have the tag

[Sans titre (1).pdf](https://github.com/Anuken/Mindustry-Suggestions/files/6129149/Sans.titre.1.pdf)

[Sans titre.pdf](https://github.com/Anuken/Mindustry-Suggestions/files/6129150/Sans.titre.pdf)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X] I am to lazy to make a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
I also demand for a hematic folder.

**Comment by itcannotbe** [comment]
and also an apache attack helicopter folder.

**Comment by itcannotbe** [comment]
[https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+schematic+folder](This is what it would look like if you actually made a quick search in the list of suggestions to make sure this has not been suggested yet.)
