### ISSUE TITLE
Replacing ore

### ISSUE THREAD

**Issue by Sezame-14** [Anuken/Mindustry-Suggestions#2154]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

You should make update that if i want to mine sand, but theres ore, to choose sand but not ore. Also, if theres more copper than titanium from specific place, it will mine copper, but i want to drill titanium.

**Comment by Lele567** [comment]
how will you replace ore exactly?
and you didn't follow the template at all.

**Comment by Kyllingene** [comment]
Not only is this the strangest misuse of the template I've ever seen, it's also not new. And no,
![noio](https://user-images.githubusercontent.com/69094702/110971217-6f4d0a00-830f-11eb-8de5-f61bf15817e6.png)

**Comment by Kyllingene** [comment]
close plz

**Comment by Bohaska** [comment]
<img width="826" alt="Screen Shot 2021-03-13 at 12 59 23 PM" src="https://user-images.githubusercontent.com/73286691/111019783-4787a000-83fc-11eb-8fe9-d0128ca19e1e.png">
Close issue button next to comment button.
