### ISSUE TITLE
Replacing ores

### ISSUE THREAD

**Issue by Sezame-14** [Anuken/Mindustry-Suggestions#2155]
**Describe the content or mechanics you are proposing.**
Replacing ore

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Make and update that whenever i place drill on sand, but theres ore, it will drill ore, but i want to drill sand. Also I want to drill titanium, but theres much more copper than titanium in specific place, so it will mine copper, but i want titanium.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Send help. Botched sentence constriction detected.

It's botched beyond comprehension.

**Comment by the-kido** [comment]
So you want to be able to choose what's being mined, correct?

**Comment by Kyllingene** [comment]
Thanks for fixing the template I guess, but [my comment](https://github.com/Anuken/Mindustry-Suggestions/issues/2154#issuecomment-797613460) on the previous one still stands.

**Comment by Kyllingene** [comment]
> tho.... you could just allow to do this by processor and then it is no longer against that rule^^

That is still against the rule.

> same way as turret-targets is not a config of the turret but something you tell them using processors

Actually, they are not the same. Without things like that, all logic would be good for would be visible sensors and unit controlling. This is adding *new* functionality to a block, the existing scenario is just disabling an AI for a turret.

**Comment by wellsilver** [comment]
> > tho.... you could just allow to do this by processor and then it is no longer against that rule^^
> 
> That is still against the rule.
> 
> > same way as turret-targets is not a config of the turret but something you tell them using processors
> 
> Actually, they are not the same. Without things like that, all logic would be good for would be visible sensors and unit controlling. This is adding _new_ functionality to a block, the existing scenario is just disabling an AI for a turret.

by that logic proccessors themsevles are against the rules

**Comment by Kyllingene** [comment]
What they do to any given block is not added functionality, and even when that is dubious, it is just that: *dubious*. This is quite obviously block I/O that is unnecessary, whos sole purpose is to make you have to think less about what you do. The other features are either necessary, or bring some large amount of variety to the game.
