### ISSUE TITLE
need more attractive vote system

### ISSUE THREAD

**Issue by djdisodo** [Anuken/Mindustry-Suggestions#2157]
I see griefers everytime i play public server

and often fail to kick griefer in indifference

1. I hope it show a big vote button on the center of the screen which makes it hard to ignore

2. it should make a full backup when vote is started so we're able to roll back after kicking him

3.there should be a small window that shows what he is doing now. so other's players doesn't need to go and see what's happening(they usually ignore because they are pressed for time)

4.vote time should be extended when someone votes

**Comment by itcannotbe** [comment]
So nice to grief the template bud. You just made yourself a griefer also.

**Comment by KyllTA** [comment]
> 1. I hope it show a big vote button on the center of the screen which makes it hard to ignore

Ah yes, make everyone unable to do stuff when a votekick is going on. Bad.

> 2. it should make a full backup when vote is started so we're able to roll back after kicking him

Can be resource-intensive (problematic when there are a bunch of players on a large, busy map), and it's too late anyway.

> 3.there should be a small window that shows what he is doing now. so other's players doesn't need to go and see what's happening(they usually ignore because they are pressed for time)

Actually, that's nice. I support this one.

**Comment by Kyllingene** [comment]
> 1. I hope it show a big vote button on the center of the screen which makes it hard to ignore

Ah yes, make everyone unable to do stuff when a votekick is going on. Bad.

> 2.	it should make a full backup when vote is started so we're able to roll back after kicking him

Can be resource-intensive (problematic when there are a bunch of players on a large, busy map), and it's too late anyway.

> 3.there should be a small window that shows what he is doing now. so other's players doesn't need to go and see what's happening(they usually ignore because they are pressed for time)

Actually, that's nice. I support this one.

**Comment by Coolhandluke348** [comment]
I like the suggestion for part three, that’s actually really nice. I don’t think people should be stopped though. I would like to see a change made so that a person under a vote kick can’t interact with anything, because sometimes if they see they’re getting kicked they will just mass delete things.

**Comment by Bohaska** [comment]
sadly, I can't give suggestions for multiplayer stuff, since I don't play it. Seems nice though.

**Comment by Bohaska** [comment]
> 1. I hope it show a big vote button on the center of the screen which makes it hard to ignore

I know you didn't mean this, but this will add another way to grief the game by spamming votekicks

**Comment by CountSudokku** [comment]
I have many times seen situations when griefer is abusing votekick system to get rid of good player, they are somehow able to convince everyone. Part 3 if suggestion could prevent this.

**Comment by ShadeStrike62** [comment]
> I see griefers everytime i play public server
> 
> and often fail to kick griefer in indifference
> 
> 1. I hope it show a big vote button on the center of the screen which makes it hard to ignore
> 2. it should make a full backup when vote is started so we're able to roll back after kicking him
> 
> 3.there should be a small window that shows what he is doing now. so other's players doesn't need to go and see what's happening(they usually ignore because they are pressed for time)
> 
> 4.vote time should be extended when someone votes

that isn't how it works, the kicking feature is a plugin

**Comment by RedstonerKBC** [comment]
> So nice to grief the template bud. You just made yourself a griefer also.

I don't know man. The template looks fine to me. Are you sure he just didn't ignore it?

**Comment by djdisodo** [comment]
@Kyllingene 
I see, vote should not disturb gameplay
how about playing a sound or blinking the edge of screen?

I'm expecting that backup won't require more resource than a single player joining in(which sends a save file to new player)

**Comment by itcannotbe** [comment]
What is the goal of this again?

> I see griefers everytime i play public server
>
> and often fail to kick griefer in indifference

To be frank most players on larger servers just don't care if the map gets griefed because someone will just carry them to endgame again once the next map gets loaded. And the whole cycle repeats.

**Comment by itcannotbe** [comment]
Heck most of the bulk of 40+ player servers are AFKers and have 0 contribution to progression.

**Comment by itcannotbe** [comment]
and yes, this should be a feature request since most server implement their own implementation of vote kick anyways.

**Comment by Kyllingene** [comment]
> I see, vote should not disturb gameplay
how about playing a sound or blinking the edge of screen?

Yeah, that seems like it should work fine. Alerts people without being disruptive.

> I'm expecting that backup won't require more resource than a single player joining in(which sends a save file to new player)

Actually, when a player joins a server, it does not send an entire save file. It sends it much more efficiently.

**Comment by Jammo2000** [comment]
Saving data from RAM does take resources, but it's resources that the server isn't using.

**Comment by Kyllingene** [comment]
How do you know that?

**Comment by Humanoid-X** [comment]
1. Again, Template
2. YES I TOTALLY SUPPORT THIS SUGGESTION!!!(Except 1, big overlay on screen) I once got kicked because I destroyed a griefer's logic processor, which control all units in its range to waste ammo and resource. Okay and he convinced everyone to believe that I destroy a very good thing. What.

**Comment by SheepCommander** [comment]
Same as Huumanoid
