### ISSUE TITLE
Sectors we have to attack

### ISSUE THREAD

**Issue by Dioo0** [Anuken/Mindustry-Suggestions#2158]
**Describe what you would like changed, and why.**
Change few sectors we have to attack: salt flats, fugnal pass, overgrowth
Why I think they should be changed:
Every of sector i mentioned has structure, that allows to approach enemy core by border of map without any damage. And then we can easily break core with poly or mega. Ive spent aprox 5 mins on each of sectors and I dont think that was planned

**Describe the changes you want to propose. Include possible alternatives.**
Maybe add minor defences that will def air units?

Good example is extraction outpost, where it has paralaxx behind core, so it drags air units
**Upd: extraction outpost also has same problem, i just turned off power and broke core**

**Comment by PolloUsami** [comment]
adding more defense to that maps only will contribute to a retro positive thing. 

the harder the sector is the harder will be the first drop to the sector 
( i am bad explaining so, tha dificulty=unit spam )

**Comment by BlueThecno** [comment]
Fungal Pass, Overgrowth and Saltflats can be completed only with Horizons, And in the first two you only need one six of them (One that you control and five comanded) and in this case you have to be right above the core AND moving for it to work but yea, Fungal Pass and Overgrowth require a rebalance in that sense, SaltFlats doesn't.

**Comment by THEGAMER-10n** [comment]
> Fungal Pass, Overgrowth and Saltflats can be completed only with Horizons, And in the first two you only need one six of them (One that you control and five comanded) and in this case you have to be right above the core AND moving for it to work but yea, Fungal Pass and Overgrowth require a rebalance in that sense, SaltFlats doesn't.

I shredded the place with novas by cutting supply lines and power then sniping the core...
~~Just add a ripple near the core to prevent this~~

**Comment by Dioo0** [comment]
well, probably this is just bad idea to improve(not that big response), so ill close it
