### ISSUE TITLE
Replacing Ores

### ISSUE THREAD

**Issue by Sezame-14** [Anuken/Mindustry-Suggestions#2159]
**Describe the content or mechanics you are proposing.**
Whenever I place a drill on sand, but theres ore, it will mine ore instead sand.
Also when i place drill on titanium and copper, it will mine copper beacuse is it more of it, but i want titanium.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would be great to put on new update that we can select what can mine

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
When #2154 and #2155 ain't enough you get this

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2155#issuecomment-797644852

**Comment by TheNightglow** [comment]
you can edit your suggestions using that "..." button in the top right
![firefox_s5vcYhWUsV](https://user-images.githubusercontent.com/22774396/111030628-a56bb600-8403-11eb-956f-13cb1a81457c.png)

pls dont open a new suggestion whenever you want to edit an old one

**Comment by Kyllingene** [comment]
#### Must you really see this again?
![noio](https://user-images.githubusercontent.com/69094702/111038163-624a1c80-83dc-11eb-8d9a-9d6d0bee9cca.png)

**Comment by RedstonerKBC** [comment]
(Probably not a good idea but it doesn't hurt to throw it out there.) Why not have the drill mine everything that is under it? Sure it would cause difficulty but we have sorters and incinerators and routers and junctions for a reason. I've ran into this problem a few times too. By the way this would be another reason to add a 1x1 drill that I suggested earlier.

**Comment by Kyllingene** [comment]
Nooooooo. That would introduce unnecessary complexity just to reduce the amount of thinking necessary.

**Comment by SheepCommander** [comment]
Although I definitely abuse 1x1 drill with mods, IMO 1x1 drill bad. Anyways despite the fact that choosing what it mines might be nice I also am against it in the base game.

However I think a drill mining everything under it would be interesting actually

**Comment by vooxal** [comment]
*Please* stop clogging this repo. Its real annoying.
![image](https://user-images.githubusercontent.com/58456527/112729270-8f242680-8ee8-11eb-99f0-2fbe00cf8d26.png)
This button will fix everything.
