### ISSUE TITLE
Sniper like naval unit

### ISSUE THREAD

**Issue by Dryehm** [Anuken/Mindustry-Suggestions#2160]
**Describe the content or mechanics you are proposing.**
Naval units need more variety, it would be cool if a long ranged naval unit was created to make water maps harder.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will give more variety to the naval factory and since its in water it could sometimes not reach enemy blocks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by CountSudokku** [comment]
So you are completely unfamiliar with already existing content. Have u ever used omura? It's t5 naval unit with railgun. You are suggesting content that already exist.

**Comment by TheNightglow** [comment]
yea the tier 5 naval unit is pretty much just a mobile version of the foreshadow (high damage sniper) with infinite ammo^^

**Comment by Dryehm** [comment]
what im saying is a new unit tree, naval factory feels empty.

**Comment by unjown** [comment]
hmm i get your point 
but i prefer the support type naval 
(this)[https://github.com/Anuken/Mindustry/pull/4911]

**Comment by unjown** [comment]
> So you are completely unfamiliar with already existing content. Have u ever used omura? It's t5 naval unit with railgun. You are suggesting content that already exist.

his trying to say 

from T1 - T5 its omura like

**Comment by Fipico2** [comment]
How is making a new tree going to make Maps harder?
I think support tree would be better, since many units already have long range

**Comment by Dryehm** [comment]
> hmm i get your point
> but i prefer the support type naval
> [this](https://github.com/Anuken/Mindustry/pull/4911)

so its like a nova that can heal blocks but longer range and in water?

**Comment by unjown** [comment]
> > hmm i get your point
> > but i prefer the support type naval
> > [this](https://github.com/Anuken/Mindustry/pull/4911)
> 
> so its like a nova that can heal blocks but longer range and in water?

have no specification on range but yes heal blocks

**Comment by MEEPofFaith** [comment]
Phy my pr.
Why not just mention `MEEPofFaith/missing-category-units` instead.
