### ISSUE TITLE
Oil

### ISSUE THREAD

**Issue by Sezame-14** [Anuken/Mindustry-Suggestions#2161]
**Describe what you would like changed, and why.**
I would like that oil drill will mine whenever we put, but salt,sand,shore, black sand will be like "booster", but it will need more power or other elements.

**Describe the changes you want to propose. Include possible alternatives.**
I already said.

**Comment by unjown** [comment]
V5 times

**Comment by bendnuts** [comment]
v5.jar

**Comment by Kyllingene** [comment]
So literally an oil extractor but useable in more places

yeah no it doesnt exist anymore for a reason

**Comment by Humanoid-X** [comment]
The olden times of V5

**Comment by stuffyAI** [comment]
Very conclusive caption, really gives the reader an idea about what to expect.

Please make the job easier for the sole developer...
