### ISSUE TITLE
resource/s input to core(/s)

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry-Suggestions#2162]
**Describe the content or mechanics you are proposing.**
an display/thing like map thing that will show the number of resources coming in to the core, with the mention of the number of resources going out, with the difference also shown.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
good to check eco

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by bendnuts** [comment]
feetur go burrr, this will definetly also  be usefull to find core incinerater griefs

**Comment by joshuaptfan** [comment]
This can be done with logic, and is one of the purposes for which logic was made.

**Comment by Bohaska** [comment]
It's on trello already

> - [X] I have
>### not
>followed the template

**Comment by bendnuts** [comment]
> This can be done with logic, and is one of the purposes for which logic was made.

this is completly besides the point, logic can be banned, and requires a logic display, and a logic processor to be researched, for what should be a basic ability.

**Comment by bendnuts** [comment]
or PERHAPS, it got added because of my suggestion -.-
________________________________

**Comment by bendnuts** [comment]
closing coz anuke def read it
