### ISSUE TITLE
Loading game data from symbolic linked folder

### ISSUE THREAD

**Issue by celentanos** [Anuken/Mindustry-Suggestions#2163]
Hello, you wrote a great game. Now my feature request:

I synchronize game saves in a cloud. This enables me to play the game on multiple devices (depending on which one is now in use). If I put the game data directory (flatpak installation) in the cloud, create a symbolic link e.g.

    ln -s path/Cloud/Mindustry path/com.github.Anuken.Mindustry/data/Mindustry

then the game dont starts (current game version) or the saved states are not loaded (earlier game versions). Is it possible to realize loading of the game data from the symbolic linked folder?

My system: Ubuntu 20.04, flatpak installation of the game

Greetings

**Comment by Fipico2** [comment]
1 Wheres the template dude
2 If you had followed the template, you would have known that "A few thing you shouldnt suggest: (...) Built in cloud sync.
3 you can export game data and then import it

**Comment by DeltaNedas** [comment]
are you sure this occurs with normal mindustry and not flatpak version which causes soooooo many issues?

**Comment by Akaricchi** [comment]
Did you make sure the link is not broken in the first place? Check:
```
$ file path/com.github.Anuken.Mindustry/data/Mindustry
```
It's a common mistake to pass a cwd-relative path to `ln` and expect it to work.

**Comment by celentanos** [comment]
> 1 Wheres the template dude
> 2 If you had followed the template, you would have known that "A few thing you shouldnt suggest: (...) Built in cloud sync.
> 3 you can export game data and then import it

I did not mean to suggest a direct cloud-sync feature. I thought that the game or the used engine has some problems with the symbolic linked folders.

> are you sure this occurs with normal mindustry and not flatpak version which causes soooooo many issues?

You are right, it was due to the flatpak installation. With the Mindustry.jar it works without problems.

> Did you make sure the link is not broken in the first place? Check:
> 
> ```
> $ file path/com.github.Anuken.Mindustry/data/Mindustry
> ```
> 
> It's a common mistake to pass a cwd-relative path to `ln` and expect it to work.

You are also right, you should always specify the absolute paths when creating symbolic links.

Thanks for your help. I will now close the issue.
