### ISSUE TITLE
Oilex

### ISSUE THREAD

**Issue by JosherIsFun** [Anuken/Mindustry-Suggestions#2164]
**Describe the content or mechanics you are proposing.**

Id like oilex to have metaglass as a recipe, it does act like watex but pumps oil and it doesnt make sense where the oil goes to, but if you see this, thank you! 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will complete the reason the same with watex before

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
seems unneeded tbh

**Comment by Coolhandluke348** [comment]
Oil ex is already expensive and you’re using wexes anyway if you’re on a no water map

**Comment by TheNightglow** [comment]
I see no reason not to do this, just a symbolic change because glass is the liquid transportation material

**Comment by Coolhandluke348** [comment]
> I see no reason not to do this, just a symbolic change because glass is the liquid transportation material

Try playing on a team server and then recommend this change lol

**Comment by TheNightglow** [comment]
> 
> 
> > I see no reason not to do this, just a symbolic change because glass is the liquid transportation material
> 
> Try playing on a team server and then recommend this change lol

What do you mean?
