### ISSUE TITLE
Color coded jump arrows

### ISSUE THREAD

**Issue by Delta303** [Anuken/Mindustry-Suggestions#2165]
**Describe the content or mechanics you are proposing.**

An option for the user to change the color of the jump arrows in the logics ui.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

When constructing programs via a processor that require multiple jump sections, it can get confusing finding the destination of an arrow if it intersects with other jump arrows. Having the ability to change the color of each arrow would speed up programing in game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheNightglow** [comment]
yes, or maybe even initialize jump arrows with a random color or a color from a predifined sequence of colors to ensure that not every jump arrow looks the same

**Comment by SMOLKEYS** [comment]
~~rainbow jump arrows when~~
