### ISSUE TITLE
Make processors able to get blocks within their own range

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2166]
**Describe the content or mechanics you are proposing.**
Make getblock be able to get blocks not only within unit range, but also within processor range

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More possibilities for logic without having to bring a unit all the way over to the processor, provided a spare one is even available

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by buthed010203** [comment]
You clearly haven't read the trello. [This is already on there](https://trello.com/c/R5UQ7V7z/776-logic-building-radar)

**Comment by itcannotbe** [comment]
> You clearly haven't read the trello. [This is already on there](https://trello.com/c/R5UQ7V7z/776-logic-building-radar)

This isn't building radar. Just telling buildings to getblock.

**Comment by buthed010203** [comment]
> This isn't building radar. Just telling buildings to getblock.

You are right, that was a real small brain moment

**Comment by YoMamaLlama1** [comment]
Although this could be bad as it would be greatly used in griefs.

**Comment by YoMamaLlama1** [comment]
If processors could get a block. Then this would very likely be used in grief attacks.

**Comment by FlippingPotatoes** [comment]
> If processors could get a block. Then this would very likely be used in grief attacks.

There are much easier ways to grief. 

Also, having additional convenience and uses for getBlock doesn’t make it more useful in griefing, if they want to use it for changing configurations, finding things to nuke, etc., they can already do this pretty simply.

Real use cases of this would be to have a slightly more configurable version of the links, in more complex designs. For griefing purposes, this complexity is completely redundant and unnecessary.

Don’t let your fear of griefing blind your judgment on this.
