### ISSUE TITLE
Endgame launch pad with QOL improvements 

### ISSUE THREAD

**Issue by Bananycus** [Anuken/Mindustry-Suggestions#2167]
An endgame version of a launchpad unlocked after the Interplanetary Accelerator (nearly unusable, overkill, and pointless before completing the main game) which is able to transport items directly from the core overflow. Instead of the resourced burning in your core they will enter the launchpad if it is connected to the core ( similar to vaults). These launch pads can be configured to launch specific resources, so they don't get flooded with copper and lead, etc. These launch pads are very expensive to build and need an output near a different core to function, and also require cryofluid. They are able to transport infinite resources per second but require more and more power to function.

Right now, the launch pads are incredibly inaccurate when transporting different types of items at the same time and they rarely are able to transport the correct amount of items. And if you decide to use logic for it(which would have been the only way of transporting massive amounts of items without it being so annoying that you don't want to do it) - it's even worse. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
There is a reason launch pads are so inaccurate, and it is due to how the passive income code works. 

Why should one develop a second, more accurate launchpad, instead of working on fixing the first. 

It's like saying: "Let's add more content instead of fixing existing problems"

I think this suggestion is entirely focused in the wrong direction.

**Comment by Bananycus** [comment]
> Why should one develop a second, more accurate launchpad, instead of working on fixing the first?
Because it would still be unbearably annoying to use the old launch pads even if they are fixed, since the only way to use them that is not annoying is logic, and logic doesn’t work correctly when you are not in the sector. Fixing the current launch pads won’t help with item overflow.
Its not just a more accurate launch pad, its a much simpler launch pad to make. its a launch pad that literally just needs to know how much you are adding to 1 core (instead of tens of launch pads) and how much resources you already have to function accurately.

> It's like saying: "Let's add more content instead of fixing existing problems"

No, its not. The actual problem is the concept of the launch pad. It both too hard for the players to use, too hard for the developer(s) to make, and cant even work with systems that are in the game(logic)
