### ISSUE TITLE
Guardian Boss Bar

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2168]
**Describe what you would like changed, and why.**
The guardian boss bar keeps track of one guardian at a time. This can lead to the bar jumping from 0 to 100 if there are multiple guardians and one dies. This can be confusing to newbies and make it hard to know the total guardian health and how close you were to defeating them.
**Describe the changes you want to propose. Include possible alternatives.**
Make the bar track every guardian at once, or have several smaller bars. If you stick with the one big bar, make segments showing the amount of health, relative to the bar, one guardian has.

**Comment by genNAowl** [comment]
I'm pretty sure there was an issue somewhere suggesting something like this, here's a comment that should be relevant: https://github.com/Anuken/Mindustry-Suggestions/issues/1838#issuecomment-763905536

**Comment by joshuaptfan** [comment]
Individual health bars for each guardian doesn't scale. As unsatisfactory as it is, the only feasible solution right now is for the single health bar to track all guardians' health combined.

**Comment by itcannotbe** [comment]
Or show the health of the guardian nearest you. then the avarage health of the rest behind the health bar of the nearest guardian.

**Comment by joshuaptfan** [comment]
> Or show the health of the guardian nearest you

That solution doesn't scale either. If there is a mass of guardians clustered together, and they are moving and you are moving, the health bar will be spazzing out from switching between guardians rapidly.

**Comment by Bohaska** [comment]
Or split up the health bar into different parts, one for each guardian, and the size proportional to the health of the guardian

**Comment by joshuaptfan** [comment]
> Or split up the health bar into different parts, one for each guardian

Also doesn't scale. There needs to be a fixed size gap between each separate health bar, and with a large number of guardians, the space allocated for guardian health bars would be mostly empty gaps with tiny, unreadable slivers of health bars in between.

**Comment by Bohaska** [comment]
Looks like we have no way of implementing this suggestion! What should we do!

**Comment by joshuaptfan** [comment]
As I said, the single health bar for all guardians combined will work. The number of guardians can also be put in that bar.

**Comment by YoMamaLlama1** [comment]
Like I said in the linked duplicate,  maybe limit it to X amount of bars that won't fill the whole screen/that side of the screen. If there are more guardians, show only the guardians with the lowest health

**Comment by Humanoid-X** [comment]
Large healthed guardians, if having low enough health, will also not really be shown.

**Comment by vooxal** [comment]
Another solution is to give each bar a different color, once one of the guardians dies, it changes color so you can tell.
