### ISSUE TITLE
Water should flow through open door

### ISSUE THREAD

**Issue by YoMamaLlama1** [Anuken/Mindustry-Suggestions#2169]
**Describe what you would like changed, and why.**
Right now, if a door is placed in front of a flowing pipe, it would stop the flow but when the door is opened it is still stopped

**Describe the changes you want to propose. Include possible alternatives.**
When the door is opened it would let the water flow through it until the door is closed.

**Comment by Kyllingene** [comment]
So you mean rework the block-vs-tile difference just for a small, visual, QoL difference.

**Comment by here-be-username** [comment]
> 
> 
> So you mean rework the block-vs-tile difference just for a small, visual, QoL difference.

Well this has fringe uses also, such as a logic-controlled tank drainer (for mixed fluid lines or something?).

**Comment by Kyllingene** [comment]
And there is no other way?

**Comment by Humanoid-X** [comment]
Agree with Kyllingene. If you want to havee a logic tank drainer you can directly enable/disable the conduit or incinerator. Any other uses?

**Comment by YoMamaLlama1** [comment]
> Agree with Kyllingene. If you want to have a logic tank drainer you can directly enable/disable the conduit or incinerator. Any other uses?
Actually, now that you have mentioned it, it would be nice to be able to toggle a drain. But this was mostly just for water to be teen flowing through a door when it's openedd

**Comment by Kyllingene** [comment]
So again, you want to have Anuke spend time changing some of the fundamentals of blocks, just so that water looks nicer in the EDGE, EDGE case that a conduit empties it by an open door? That shouldn't exist anyway?

**Comment by Humanoid-X** [comment]
Hey dear Anuke, I think it will be good to rework the whole bock-vs-tile system so that fluids can leak into open doors. It is only a small, small change so I think it will be very easy to implement.

**Comment by itcannotbe** [comment]
> > Agree with Kyllingene. If you want to have a logic tank drainer you can directly enable/disable the conduit or incinerator. Any other uses?
> 
> Actually, now that you have mentioned it, it would be nice to be able to toggle a drain. But this was mostly just for water to be seen flowing through a door when it's opened

Toggle a drain be like: Logic.
