### ISSUE TITLE
boxes

### ISSUE THREAD

**Issue by evornell08** [Anuken/Mindustry-Suggestions#217]
**Describe the content or mechanics you are proposing.**

when I play the game on my iphone 11 pro max there are huge black boxes at the top and bottom of the screen I would love to have that’s fixed please

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
Give screenshot, save file

**Comment by evornell08** [comment]
![4F0206F3-E609-43D3-84DE-1A59993FBC1C](https://user-images.githubusercontent.com/61436103/83582263-b0092e80-a506-11ea-87e9-233a3ad7676d.jpeg)

**Comment by evornell08** [comment]
they are there why I play the game too

**Comment by potatoisagender** [comment]
probably just formatting problems.

**Comment by DeltaNedas** [comment]
would you rather have notches cut holes into the game and potentially break features?

**Comment by Anuken** [comment]
I won't be supporting notched phones; mobile UI is already a bit of a mess to maintain, and this makes it much harder.
