### ISSUE TITLE
Rotation affecting config for unit building

### ISSUE THREAD

**Issue by FlippingPotatoes** [Anuken/Mindustry-Suggestions#2170]
**Describe the content or mechanics you are proposing.**

For schematics, rotating the design will adjust where things like processors and bridges are linked to. However, with the new unit building config, while one can now use a block to copy paste it elsewhere, rotation of these setups is much more limited as compared to other systems in place.

I suggest that the rotation variable should rotate its links and not just the block, as already occurs with schematics.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will improve consistency and the utility of the unit building mechanic. As is, the rotation mechanic has no use when working with blocks that can accept the configuration copying, but this would improve the utility of the overarching config copying, without breaking any of the set standards. (Although I do imagine this to by no means be a particularly easy change)

If we compare this to schematics, it would be undesirable to require the player save 4 separate schematics per build. The same idea should apply to the unit building logic.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
You can integrate schematic orientation detection into your logic yourself. You only need to link 1 other block in the schematic whose position can be detected relative to the processor. See my [unit parking](https://steamcommunity.com/sharedfiles/filedetails/?id=2344611802) logic.

**Comment by FlippingPotatoes** [comment]
> You can integrate schematic orientation detection into your logic yourself, then have your logic adjust as desired

Perhaps I was unclear, but this is specifically in regard to unit control build’s new ability to use a block as a config (allowing processor replication and bridge link retention), but inability to be rotatable. 

Using another object for deciding rotation is all well and good (and would likely be used in conjunction with this mechanic), but it’s not what this is referring to.
