### ISSUE TITLE
Please allow us to power on / off blocks

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2171]
**Describe the content or mechanics you are proposing.**

- Some blocks need power / energy to work.
- Most blocks are not needed all the time during a game.

Therefore: please allow us to power on / off blocks, so that they don't use energy if there is nothing useful to do :-) 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

- The game-flow makes more sense: it is very tedious and pointless to destroy blocks so that they no longer waste energy that is needed elsewhere. 
- Of course, one can also destroy blocks when they are not needed for a while - but this is also tedious.
- Or one can try to place the energy distributors in such a way that only desired blocks get energy - but this is also no fun.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by XEN0PHIL** [comment]
If only you could disconnect blocks from power nodes

**Comment by Jammo2000** [comment]
Click on a power node. Click on buildings to connect/disconnect (connected ones have a purple diamond on them)

**Comment by Humanoid-X** [comment]
Ah yes this will help so much. We can't disconnect power node nor use logic right now. This will DEFINITELY help, please add thid feature.

**Comment by itcannotbe** [comment]
Ah yes. As if blocks doesn't not consume power a.k.a. turn themselves off when they can't output already.

This feature would dEfInItElY hElP.

**Comment by Fipico2** [comment]
Completely unnecessary

**Comment by YoMamaLlama1** [comment]
Well, we can definitely manually do it because it's just toooo hard. But logic pff to lazy.
