### ISSUE TITLE
Could you please add Tooltips for the ressources?

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2172]
**Describe what you would like changed, and why.**

I played about 4 Days and and I still keep wondering which resource is behind which icon. And because it is tedious to maintain a legend outside of the game itself, I ask for your help:

Can you please add a tooltip on the resources? Maybe they could be enabled / disabled in the settings, e.g. "Display beginners Tooltips".

**Describe the changes you want to propose. Include possible alternatives.**

- **(1)** A tooltip on the top of the window
- **(2)** Maybe you could add the resource name (or an abbreviation) if the Mouse is above a conveyor belt, when the game displays the speed, e.g.: `<Icon> 2.4 / sec: Copper`

![image](https://user-images.githubusercontent.com/8282673/111680444-836a9d00-8822-11eb-9077-cc74e8ba8e40.png)

**Comment by Jammo2000** [comment]
Good idea, could be hard to implement.

**Comment by RedstonerKBC** [comment]
You won't believe how convenient this would be for mods that add like 20+ new resources.

**Comment by THEGAMER-10n** [comment]
> Good idea, could be hard to implement.

Logic already has tooltips. So this could be easy to implement.

**Comment by genNAowl** [comment]
> Logic already has tooltips. So this could be easy to implement.

I have not checked the code for resource display UI yet, but this wouldn't be as easy as you would think - logic tooltips are over buttons, while these are just icons; However, this is just my first thoughts on implementation; Take what I say with a grain of salt.

**Comment by Humanoid-X** [comment]
Good but might be hard...

**Comment by itcannotbe** [comment]
Aside from mods. This doesn't give anymore help to the vanilla game aside from some edge cases. For the most part most resources doesn't look alike for the most part.

**Comment by numer99** [comment]
I thought the title mean it would _tell_ you about resources
maybe if you clicked on the resource it would tell you what it was and tell you about it.

**Comment by itcannotbe** [comment]
You mean clicking on the resource shows your the ~block~ Item info?

**Comment by schittli** [comment]
> You mean like clicking on the resource shows you the ~block~ Item info?

**Tooltips are great because** one only has to wait a very short time - and then one knows what one needs 😍

**If one has to click to get hints**, then the game ist interrupted: click - read - click again to return to the game.
We already have this tedious usability with the block information: One hast to click the **?** to quickly get required information:
![image](https://user-images.githubusercontent.com/8282673/111678544-b4e26900-8820-11eb-9f45-53b778d21b0a.png)

#### I click on this question mark very often, therefore I just wanted to expand this suggestion:
As soon as one is above an object and holds down e.g. the Alt key, additional information is displayed as a tooltip 😊🙄
![image](https://user-images.githubusercontent.com/8282673/111679993-08a18200-8822-11eb-84ca-11658066e12b.png)

**Comment by numer99** [comment]
Exactly, we need tooltips for items

**Comment by joshuaptfan** [comment]
It's not necessary to learn the names, as resources are referred to by their icons everywhere in the GUI.

**Comment by schittli** [comment]
Hei @joshuaptfan 

> It's not necessary to learn the names, as resources are referred to by their icons everywhere in the GUI, while the names are only used in a couple of places.

Unfortunately, this is not true/useful:
While playing the game, even if a beginner played 30 hours, he still must break the game all the time:
- If one would like to "build the Block which is able to generate Graphite", one must click the buildings and even click the `?` button to find the right Building. To just distinguish Ressources, Buildings or Factories just by their icons is a nightmare because one has to spend a lot of time to see the difference in the small icons.
- If one would like to build the Flare Units, the Game does not tell which resources must be transported to the factory. Do you really propose to google for the Flare Unit icon to get the answer?


No, 99.9% of all Games use Text and Tooltips, so that Users can quickly start, don't have to ask obvious questions like "What das this Icon mean?" and play without many interruptions.

The only difference is probably Chess :-)

**Comment by schittli** [comment]
## I've just noted that the missing Tooltips are fatal for the gameplay / gameflow in general:


- If one wants to produce a unit in a factory and the mouse is above the unit-icons, the unit name is *not* displayed. Which icon is the unit one needs?? Additional most useful/important information is missing, too: Which resources are needed to produce it? Can it attack ground and/or air units? One has to break the game and ask google for the answers :-(

- If one has found the needed Unit and one wants to produce it, the factory does not show which resource it needs to produce the unit. Solution? One has to leave the game and ask google for the answer. :-(

- If one tries to build the Block which can generate Graphite, one has to search for it: Click to each Block, click to the `?` Icon, read the description, close the Dialog. Repeat until you've found your block.

- If one knows that the Multi Press must be built, we've got the next question: Where do I have to place it, so that the Block is next to the resources it needs to work? Once more, one has to move to the `?` icon, click it and afterwards have to close the dialog. A (useful) tooltip would be great...

As we already know:
- The game shows all the resource-icons and their stock. But there is no Tooltip with its name. Names are great because we're tuned to recognize text very fast. We gan google for it. But it's hard to google for "the light pink icon which has a cross line". Additionally, each 20th has color blindness - it is really a pity that these users are not supported with a trivial function like the tooltips. It's not rocket science.

Conclusion:
We have to constantly research outside the game what resources and units we need or we're working with.

**Comment by schittli** [comment]
Good evening @Anuken 

I'm always amazed at how clean your code is and I can't believe how productive you are... truly remarkable.

### Wouldn't it be possible for you to display the resource tooltips like this on-liner?

It would be a very big help for the gameplay and would be more fun. Please note the `//New:` part.

File: `.\core\src\mindustry\ui\CoreItemsDisplay.java`
```
        for(Item item : content.items()){
            if(usedItems.contains(item)){
                image(item.icon(Cicon.small)).padRight(3);
                //TODO leaks garbage
                //Old:
                // label(() -> core == null ? "0" : UI.formatAmount(core.items.get(item))).padRight(3).left();
                //New:
                label(() -> core == null ? "0" : UI.formatAmount(core.items.get(item))).padRight(3).left().tooltip(item.name);
                // …
            }
        }

```

Thanks a lot, kind regards,
Thomas

**Comment by Anuken** [comment]
7.0 already does something similar to that.
