### ISSUE TITLE
Underwater spore tile. 

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2174]
Underwater spore tile, maybe make cultivator (idk how it in eng version, this thing create spores) dont need water if placed on this tile, only energy

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Is that what I think it is? A butchered template?

**Comment by iLagSoUhax** [comment]
nope, bad suggestion, go back to your place in #mindustry

**Comment by Humanoid-X** [comment]
no.

**Comment by Qvertyes** [comment]
> no.

yes.

**Comment by itcannotbe** [comment]
> > no.
> 
> yes.

No.

**Comment by Qvertyes** [comment]
> 
> 
> > > no.
> > 
> > 
> > yes.
> 
> No.

Yes.
