### ISSUE TITLE
Foreshadow Targetting

### ISSUE THREAD

**Issue by 02Oxygen** [Anuken/Mindustry-Suggestions#2175]
**Describe what you would like changed, and why.**
Foreshadows target system seems a a little off, since when there is 2 players 1 in a oct and a tox it would target the closest player near it and it would be the oct not the tox that can destroy it in mere seconds

**Describe the changes you want to propose. Include possible alternatives.**
I propose that you change the target system for the shadow. Instead it would target the player in the unit that can do lots of damage to it instead of the units that do less damage and basic defenses that can kill easily

**Comment by joshuaptfan** [comment]
This can be done with logic, and is one of the purposes for which logic was made.

**Comment by Thankyou69** [comment]
a foreshadow targets units with highest health priority

**Comment by MauritanianMapping** [comment]
The foreshadow is working perfectly as it was meant to, if you want it to be smarter you need to chip in the extra work and attach some logic to it
