### ISSUE TITLE
Procedural map generation line to core

### ISSUE THREAD

**Issue by numer99** [Anuken/Mindustry-Suggestions#2176]
**Describe what you would like changed, and why.**
I was looking at all the sectors and I noticed that all of the non-campaign sectors have an abrupt line through them
![image](https://user-images.githubusercontent.com/65624340/111549008-bf293800-8738-11eb-988d-354c234a16b9.png)
It seems like it can be _really_ unnatural

**Describe the changes you want to propose. Include possible alternatives.**
It seems like the generation can be _really_ weird and it would be really interesting and fun if you changed the straigt line right through the middle of the map

**Comment by Fipico2** [comment]
I dont see anything, are you talking about the floor tiles? Im pretty sure those are intentional and were already in v5

**Comment by Jammo2000** [comment]
Do you mean the black area in the middle?

**Comment by numer99** [comment]
in the terrain

**Comment by numer99** [comment]
![3c1a0de1-7796-483a-85a9-c6d0e816522f](https://user-images.githubusercontent.com/65624340/111567011-7d5db900-875b-11eb-85bb-5c52b7d9481c.png)

**Comment by genNAowl** [comment]
Well, without it, there's a chance that enemy units will *neve* be able to make it to the core, and that's not a risk Anuke want's to take

**Comment by numer99** [comment]
but if Anuke did this
![sketch1616036744733](https://user-images.githubusercontent.com/65624340/111567461-43d97d80-875c-11eb-819b-e3d019546925.png)
It would be more interesting

**Comment by itcannotbe** [comment]
Well no.... Multiple paths to core is more interesting.

**Comment by numer99** [comment]
but it's not interesting if there is a straight line _directly_ to the core.

**Comment by itcannotbe** [comment]
That's not even a straight line to begin with.

**Comment by numer99** [comment]
what is you definition of "straight"
![3c1a0de1-7796-483a-85a9-c6d0e816522f](https://user-images.githubusercontent.com/65624340/111573230-5a390680-8767-11eb-8a56-0e1fe37737df.png)

**Comment by itcannotbe** [comment]
And you handpick that didn't you?

Now show me the countless other sectors that doesn't have a straight path cut into it.

**Comment by itcannotbe** [comment]
Also if that straight cut wasn't placed their that sector wouldn't be playable to begin with.

**Comment by itcannotbe** [comment]
> Well, without it, there's a chance that enemy units will _never_ be able to make it to the core

OP seem to be ignoring that fact even if someone mentioned it a while back.

**Comment by numer99** [comment]
**They ALL have abrupt lines**
![image](https://user-images.githubusercontent.com/65624340/111573488-ddf2f300-8767-11eb-93fd-571313710438.png)
![image](https://user-images.githubusercontent.com/65624340/111573502-e3e8d400-8767-11eb-9dab-6077ca8ae83a.png)
![image](https://user-images.githubusercontent.com/65624340/111573515-ea774b80-8767-11eb-88ce-0339af2ad6dc.png)
![image](https://user-images.githubusercontent.com/65624340/111573550-fb27c180-8767-11eb-8506-6df25373d777.png)
![image](https://user-images.githubusercontent.com/65624340/111573564-02e76600-8768-11eb-8166-87255edc6cf7.png)
![image](https://user-images.githubusercontent.com/65624340/111573594-0e3a9180-8768-11eb-97c6-a065776fb838.png)
![image](https://user-images.githubusercontent.com/65624340/111573610-1692cc80-8768-11eb-829b-e2bf06a3163e.png)
![image](https://user-images.githubusercontent.com/65624340/111573648-26121580-8768-11eb-800f-f8d197107220.png)
![image](https://user-images.githubusercontent.com/65624340/111573658-2c07f680-8768-11eb-8cc7-d8a85255c55c.png)
![image](https://user-images.githubusercontent.com/65624340/111573689-3b873f80-8768-11eb-94ba-d0d4c44a05e3.png)
![image](https://user-images.githubusercontent.com/65624340/111573711-4641d480-8768-11eb-991a-42f3f066dafa.png)

**Comment by numer99** [comment]
If anuken edited a different path it would be **a lot** better

**Comment by Bohaska** [comment]
> If anuken edited a different path it would be **a lot** better

Anuke doesn't spend his 8 hours a day editing his seed map generator just to make the maps look better in your eyes.

**Comment by itcannotbe** [comment]
Making manual edits undermines why you made it procedurally in the first place.

**Comment by numer99** [comment]
I give up trying to make mindustry _strategical_ like it's supposed to be

**Comment by itcannotbe** [comment]
How would this suggestion would make the game more strategical?

**Comment by numer99** [comment]
because the same thing would happen in each sector:
Step 1: block off enemy defenses with walls and turrets
Step 2: build factories
Step 3: leave

**Comment by itcannotbe** [comment]
How does your suggestion prevent/change that?

**Comment by Bohaska** [comment]
If the line wasn't added then there would be sectors where the enemy troops can't reach the base

**Comment by Bohaska** [comment]
> Step 1: block off enemy defenses with walls and turrets

Your suggestion drastically reduces the amount of paths to the core, therefore making this even more generic

**Comment by Bohaska** [comment]
Ok, deal. We would allow this suggestion, **as long** as you use your programming knowledge to edit the seed map generator in order to achieve this.

**Comment by numer99** [comment]
I have no programming knowledge

**Comment by numer99** [comment]
if there was a **different and more interesting **path**
it would be better

**Comment by Bohaska** [comment]
> I have no programming knowledge
> […](#)

Well, Anuke has more important things to take care of, like making Tantros and fixing bugs, so this suggestion is stuck on the nice to have list for eternity

**Comment by itcannotbe** [comment]
How exactly would it be better/different from what you describe as it is currently?

**Comment by Bohaska** [comment]
> if there was a **different and more interesting path**
> it would be better

It's not like you would die if this wasn't implemented

**Comment by Bohaska** [comment]
> but if Anuke did this
> ![sketch1616036744733](https://user-images.githubusercontent.com/65624340/111567461-43d97d80-875c-11eb-819b-e3d019546925.png)
> It would be more interesting, _and_ it will work

you do know that the map would be absurdly small when doing that, do you?

**Comment by Bohaska** [comment]
@numer99 Where did you go?

**Comment by MauritanianMapping** [comment]
You can't make a suggestion based off of opinions that almost nobody agree with

**Comment by numer99** [comment]
Anuken literally put this in the v7 beta
My ideas are good
https://github.com/Anuken/Mindustry/releases/tag/v128.1
"Campaign: Improved planet generation; paths between core and spawns should now be less straight"

**Comment by numer99** [comment]
why did you criticize my idea so much if it was a good one?
(good enough for **anuken** to add it in)
