### ISSUE TITLE
Allow logic processors to switch between different command center 'mode'

### ISSUE THREAD

**Issue by kdvolder** [Anuken/Mindustry-Suggestions#2177]
**Describe the content or mechanics you are proposing.**

Provide a means to let processors/logic switch command center modes. I.e. like when you have a command center, in the ui, you can switch between 'idle', 'rally' and 'attack'. It would be nice if we could have a processor control command to change this state.  e.g. create a logic processor program that sets the state to 'rally' or 'attack depending on some conditions being detected.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would allow processors to control units for more coordinated attack / retreat strategies without actually controlling all individual units in detail. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Such "convenience instructions" would only be a few instructions shorter than, or the same length as, the current ways to implement them in logic, so they're not worth adding.

#### Idle
Have a command center set to "idle" on the map, and unbind units by not giving them commands
#### Rally
```
ucontrol move @thisx @thisy 0 0 0
```
It would be pretty useless to have a `move` command that only allows you to move units to the processor's location, reducing instruction count by 0 while offering less functionality.
#### Attack
```
ulocate spawn core true 0 spawnx spawny 0 0
uradar enemy any any maxHealth 0 1 enemy
ucontrol move spawnx spawny 0 0 0
ucontrol targetp enemy enemy 0 0 0
```

**Comment by kdvolder** [comment]
@joshuaptfan I would agree with you if it were true (and maybe it is, and I just don't understand something). But, I think,  when a unit is following 'command center' mode behavior, it has more complex 'smart' behavior than you can easily (or even at all) achieve using simpler instructions such as move.

Most notably, when ground units are 'pathfinding' they actually walk around obstructions to reach their target. When using 'move' instructions on the other hand they instead just make a bee line to the target and get stuck on any obstacles in the path. Perhaps it is somehow possible to implement a 'smart' pathfinder that walks around objects using simpler instructions, but if so, I think it will be a very complex program to write.

That being said, I agree, if only had some slightly smarter pathfind or move commands, then I probably wouldn't need/want a way to programatically change command center mode. That's why I raised this other suggestion issue as well (https://github.com/Anuken/Mindustry-Suggestions/issues/2181).

**Comment by Kyllingene** [comment]
Something like `control configure center1 <1 to 3> 0 0 0` would be easy enough, right?
