### ISSUE TITLE
The old game4?

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#2178]
**Describe the content or mechanics you are proposing.**
Bring back the old game4 song as music that only plays at night and when there are no enemies present.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It might fit the mood if it was adjusted a little or its tempo slowed.
(LMMS shows it's in major key so changing it to minor would help it to fit in as well)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MauritanianMapping** [comment]
That is, if the music will even play during gameplay

**Comment by numer99** [comment]
I really liked the old game4

**Comment by Humanoid-X** [comment]
game4 is my favourite soundtrack in Mindustry

**Comment by Catchears** [comment]
do you mean [this one](https://github.com/Anuken/Mindustry/blob/89589c32586a04699c03843fbd82b31d256606a6/core/assets/music/game4.mp3)? I'm guessing so do tell me if I'm wrong.

**Comment by OnyxFinger** [comment]
Yes, the propositio for the environement in which it would play is good, it would fit well and I loved the song too, good idea.
