### ISSUE TITLE
Support drone enemy targeting prevention

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#218]
**Describe the content or mechanics you are proposing.**
Make repair drones, and, possibly, other types of base support drones, be not targeted (but capable to be hit) by enemies. Would possibly require to nerf the stats of the drones to compensate.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Base support drones frequently die, being targeted. Lorewise it, possibly, would be logical for them to have some kind of radar jammer. Also, miner drones flying into enemy Scatters would no longer be an issue. This could also be seen as an indirect buff to shock mines, which could also be possibly nerfed as a consequence.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
'Make repair drones, and, possibly, other types of base support drones, be not targeted (but capable to be hit) by enemies. Would possibly require to nerf the stats of the drones to compensate.'
This is already implemented. Then you go on a bit, to things I don't understand, because of clarity issues.
'Base support drones frequently die, being targeted. Lorewise it, possibly, would be logical for them to have some kind of radar jammer. Also, miner drones flying into enemy Scatters would no longer be an issue.'
They don't often get targeted. The detection range is really small, and often they move too fast. The only times they get hit is when they sit in the area enemies are shooting. Miner drones flying into enemy scatters means that you need to have resource either closer to their factories, or closer to core.

**Comment by Ilya246** [comment]
'Miner drones flying into enemy scatters means that you need to have resource either closer to their factories, or closer to core.'
Not like you can move resources, or, if it's hexPvP, draug factories.
And no, they get targeted frequently, wraiths like to kill them. There is no such thing as unit-specific detection range, if you meant that, also. Plus, the addition would allow them to actually repair shock mines without killing both themselves and the mines.

**Comment by potatoisagender** [comment]
you can cover copper and lead nodes. 
'Wraiths like to kill them.' Then build AA. The fact that wraiths like to kill them is like complaining about the fact that wraiths will chase wraiths.
Why would you use shock mines, and if the shock mines need repairing, they aren't working as planned. Also, just use mend projectors.

**Comment by Ilya246** [comment]
Building AA will not help - the drones will fly to undefended areas - due to the exact reason that they are undefended and need repairs due to the attacks of those wraiths. And also, shock mines get damaged from getting stepped on. Plus mend projectors will get targeted too, killing nearby shock mines.

**Comment by potatoisagender** [comment]
Okay. I still don't understand why you use shock mines. Clearly, you have a problem with them, so why use them? If the drones are flying to  undefended areas, where enemies are getting through, maybe you might just need a better defense. The enemies should not be getting through your aa.

**Comment by Ilya246** [comment]
I mean, some enemies just go around the anti-air (To clarify, i'm talking about generic multiplayer)

**Comment by Ilya246** [comment]
But well, this certainly should be done at least for draugs, so they don't get sniped by enemy scatters in hexpvp, essentially locking your progress

**Comment by itcannotbe** [comment]
Draugs love killing themselves in the tight space hex pvp initially provides.
