### ISSUE TITLE
Mobile turrets

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#2180]
**Describe the content or mechanics you are proposing.**
Basically units that cant attack till deployed and can be undeployed, and maybe mobile support that suppports units on the battle field?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Placing turrets on an empty battle field with lots of units can be painful because of ammo or power, mobile turrets would have infinite ammo (unless unit ammo on a map is true) and can be deployed faster than gamma building a hail

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
[Payload Cannon](https://trello.com/c/eYmSkIDI/813-payload-cannon) in v7

**Comment by nichrosia** [comment]
Quite a few units act like turrets in this. A list would be:

Pulsar -> Arc
Quasar -> Lancer
Vela -> Meltdown
Dagger -> Duo
Mace -> Scorch
Fortress -> Hail
Omura -> Foreshadow
