### ISSUE TITLE
pathfind command parameters (or alternatively make move command 'smarter')

### ISSUE THREAD

**Issue by kdvolder** [Anuken/Mindustry-Suggestions#2181]
**Describe what you would like changed, and why.**

The pathfind command (from processor/logic) could take some additional parameters to make it more versatile / useful. 
 

**Describe the changes you want to propose. Include possible alternatives.**

Possible extra useful arguments: 
- add a coordinate x and y. This makes that coordinate the 'target' to pathfind to 
- add a paramer that specifies 'attack' or 'rally' which serves to override the command center mode.

Main reason for proposing this is that the 'move' and 'approach' commands do not work well for ground-based units. These units tend to get 'stuck' on obstacles as they move in a straight-line towards the target. (These commands do work fine for air-based units as they fly over obstacles).

pathfind command doesn't have this issue. Units pathfind around obstacles 'smartly'. But since it has no parameters its impossible to actually direct the unit to do anything specific using pathfind. Moreover, I don't think there is even a way to programatically control the command center mode (see related suggestion: https://github.com/Anuken/Mindustry-Suggestions/issues/2177)

Most useful to me I think would be if we have a way to instruct units to 'rally to' or 'attack' a specific point on the map chosen somehow by processor logic. 

This could be accomplished in different ways:

- make move/approach commands smarter and navigate around obstacles or...
- add more parameters to pathfind to control target and 'attack/rally' behavior or ...
- a new type of command entirely that is like a smarter version combining pathfind/move/approach behaviors

**Comment by Jammo2000** [comment]
I think a pathfind to x,y would be useful, the rest would be easy & fast enough to do with logic if pathfind to coords was a thing.

**Comment by OnyxFinger** [comment]
For that reply just up, ^^ this suggestion is different, allowing logic to pathfind coordinates isn't having every CC option in pathfind instead of the one CCs are actually on
