### ISSUE TITLE
Mindustry should warn or block the sector, if the user is unable to conquer it

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2182]
**Describe what you would like changed, and why.**

Yesterday, I tried to conquer Sector 36 just with Tier 1 Units (Dagger, Crawler, Nova, Flare and Mono) and I'm pretty sure that it is impossible to conquer this sector with this kind of units: Although also the sector was full of protective towers and walls, I was killed within about one minute. After 5 hours fighting...

**Describe the changes you want to propose. Include possible alternatives.**

If I am right, then it would be great if Mindustry:
- either blocks sectors if the available technology is not at all sufficient to defeat the opponent
- or the user receives a warning, for example in the sense: _Your technology is massively inferior to the opponent's - try to attack it later_

**Comment by itcannotbe** [comment]
Ah yes. Another player who doesn't like to lose, as if you have nothing to learn when you lose.

**Comment by schittli** [comment]
> Ah yes. Another player who doesn't like to lose, as if you have nothing to learn when you lose.

No, I don't have any problem losing a fight - when there is a real chance to win.
But if I have a lot of my available strongest weapons and units and I failed to overcome the opponent for 5 hours and then he wipes me out within a minute, I suspect that I am indeed without a chance with my options.

#### I tried to find a strategy for 5 hours, but could not find a solution…
**Except this: first conquer other sectors to research stronger units.**
**But if this is indeed the solution, then the game should really warn the users**, because the game should be a little fun in the end. 
Hours of battles with no chance of success are just pointless in a game.

**Comment by itcannotbe** [comment]
How on earth did you manage to stretch your gameplay to 5 hours? Either you pausing every step of the way or you must have slow hardware.

But I digress, the game encourages you to research blocks/units, the only persom who would force themselves to conquers a procedurally generated sectors are those seeking the challenge of limited capabilities. plus sectors already come with a danger level sorts.

**Comment by G0nTar** [comment]
Sectors come with a Enemy presence level (call it difficulty warning if you like it that way)

Just watch the sector difficulty before launching to capture it again and again.

Also the ones labeled in red "Enemy Base" should be avoided since, it's where big groups of units and big guys come from, so if you don't have your own big guys, it's a big no no

**Comment by Ilya246** [comment]
the problem about this is that you can't really know if the player can't beat the sector - some sectors are easier, and some are harder, and you don't even know the player's experience level

**Comment by joshuaptfan** [comment]
> then it would be great if... the user receives a warning

When you click on a sector that you can launch to, it tells you the threat level and enemy base presence.

**Comment by Fipico2** [comment]
Campaign sectors already have you do this, it is your fault you chose to ignore the difficulty level and jump into a procedelly generated sector. Learn from your mistakes, dont ask to change the game

**Comment by MauritanianMapping** [comment]
A core principle of making suggestions is that "I'm mad butthurt" isn't a good principle for making suggestions, make sure to learn what you are doing wrong before asking to change the game and possibly embarrass yourself
