### ISSUE TITLE
Please allow us to assign the F1-Key to the "?" Butten

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2185]
**Describe what you would like changed, and why.**

It's great that Mindustry has a lot of keyboard shortcuts - but because beginners very often have to click to the ```?``` Button, it would be great if we could assign e.g. F1 to it, so that we can quickly open it by one keypress and close it with ```Esc``` :-)

**Describe the changes you want to propose. Include possible alternatives.**

![image](https://user-images.githubusercontent.com/8282673/111877324-1d595380-89a3-11eb-8fd1-cfb67dd4f0fa.png)

**Comment by joshuaptfan** [comment]
[There is a preexisting PR for this already.](https://github.com/Anuken/Mindustry/pull/4284)

**Comment by joshuaptfan** [comment]
Please close, the PR for this has been merged.
