### ISSUE TITLE
Adding a setting to adjust long-tap duration in mobile

### ISSUE THREAD

**Issue by Salty-Salmon** [Anuken/Mindustry-Suggestions#2187]
**Describe the content or mechanics you are proposing.**
Theres a threshold for a still tap duration so game can determine whether to switch to place-in-a-row mode. This threshold is a bit too long which always annoys if one tries to build fast. The suggestion is to allow player to change this this threshold.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make mobile players less annoyed, i guess. Also this must not be a difficult feature to implement, so it could be added rn, in v6.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
This seems like one of those things that would get implemented due to sheer simplicity, however Anuken might have some reasons not to implement it. Be warned.

**Comment by itcannotbe** [comment]
Isn't it fast enough for fast building but slow enough that it couldn't be mistaken for a move camera input?

Anyway, what it is even set to currently?

**Comment by itcannotbe** [comment]
Apparently it's set to 1.1 seconds? Dunno if abides FPS but if so, you're screwed when FPS becomes low enough.
