### ISSUE TITLE
add key bind options for mouse 3 and 4 buttons

### ISSUE THREAD

**Issue by SirQuacker** [Anuken/Mindustry-Suggestions#2189]
I think it would be good to add the mouse button 3 and 4 controls to the keybind menu as people use them for Push To Talk( PTT) buttons or other macros.

I am suggesting this as I use mouse 3 for PTT and whenever I try to talk it moves the camera.

**Comment by SirQuacker** [comment]
under different names

**Comment by itcannotbe** [comment]
OP realized it and closed the issue before you comment. Have a nice day.
