### ISSUE TITLE
Downloadable version of the Mindustry Wiki

### ISSUE THREAD

**Issue by dba2k15** [Anuken/Mindustry-Suggestions#2190]
**Describe the content or mechanics you are proposing.**
Just a downloadble version of the mindustry wiki, either be it on a website or the stores for mobile devices

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Although it is not going to change anything for experienced players, i think it can help a lot for new players that can't have internet all the times and also making the use of the wiki more confortable to use

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Have you considered insulting yourself after seeing that core database/block (unit) info exist in-game?

**Comment by itcannotbe** [comment]
Wiki Page:
![Screenshot_20210322_231223](https://user-images.githubusercontent.com/45280919/112012481-32311500-8b64-11eb-902d-6e273a3a0b97.jpg)
In-Game Core Database/Block Info Entry:
![Screenshot_20210322_231251_io anuke mindustry](https://user-images.githubusercontent.com/45280919/112012496-352c0580-8b64-11eb-973b-43ba8f87aaed.jpg)

**Comment by Fipico2** [comment]
Core Database > Wiki

**Comment by TheRealIvyX** [comment]
>  [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

are you sure about that

**Comment by PolloUsami** [comment]
go to your favorite navegator > ... > download page

no need to thanks!

**Comment by Kyllingene** [comment]
[Github for wiki](https://github.com/MindustryGame/wiki). You can download it from there to have access to things like logic tutorials, etc.

> Core Database > Wiki

I see no wiki button there... is that mobile/itch.io only?

**Comment by Catchears** [comment]
> [Github for wiki](https://github.com/MindustryGame/wiki). You can download it from there to have access to things like logic tutorials, etc.
> 
> > Core Database > Wiki
> 
> I see no wiki button there... is that mobile/itch.io only?

They mean that the database is better than the wiki.

**Comment by Kyllingene** [comment]
> They mean that the database is better than the wiki.

Ah. I disagree.
