### ISSUE TITLE
[v7] Various planet sizes

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry-Suggestions#2191]
**Describe the content or mechanics you are proposing.**

This is probably obvious, but, especially for mod planet support, there should be a range of possible sizes for planets, which should affect the number of sectors on a planet.

Some possible planet sizes - sector layout geometry:
* 12 sectors - [dodecahedron](https://en.wikipedia.org/wiki/Regular_dodecahedron) - suitable for a moon
* 32 sectors - [truncated icosahedron](https://en.wikipedia.org/wiki/Truncated_icosahedron)
* Various sector counts based on other [Goldberg polyhedra](https://en.wikipedia.org/wiki/List_of_geodesic_polyhedra_and_Goldberg_polyhedra)

The diameter of any size planet should be adjusted so that the size of a sector on that planet is roughly the same size as a sector on Serpulo.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

More, smaller planets with more extreme variation of biomes on each planet (lava planet, ice/water planet, etc) would be more interesting than fewer larger planets for the campaign moving forward. I doubt that most players would have the stomach to conquer yet another planet with 272 sectors.

For modders who want to handcraft maps for every sector on a custom planet, being able to make smaller planets with fewer sectors means less work for them to do.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
very yes
very very yes

**Comment by genNAowl** [comment]
++

Although because of my lack of experience with the code for planets, I don't know how hard this will be to implement.

**Comment by QmelZ** [comment]
you can already change sector sizes/count, but as far as i know the planet's size can't be changed for some reason.

i agree with this suggestion

**Comment by Bobbystevenson** [comment]
Yes yes yes

**Comment by firstcreator48** [comment]
yes noice

**Comment by Humanoid-X** [comment]
yes
yes yes
yes yes yes
yes yes yes yes

**Comment by MauritanianMapping** [comment]
That is aggressively correct

**Comment by THEGAMER-10n** [comment]
I wonder what mods can do with this...

**Comment by Bohaska** [comment]
maybe also allow you to adjust planet diameter

**Comment by joshuaptfan** [comment]
> maybe also allow you to adjust planet diameter

Not separately of sector count. I want planet size to be mathematically related to sector count, so you can compare planets at a glance.
