### ISSUE TITLE
Random Sector Generation

### ISSUE THREAD

**Issue by firstcreator48** [Anuken/Mindustry-Suggestions#2192]
**Describe the content or mechanics you are proposing.**
Make a sector from the generation type of the planet chosen (default Serpulo). If mods with interactable planets like Wrek (dimension shard mod) can be chosen based on generation type.
It can be also be an enemy base where rare structures that can be found on the source code as schematic format. Classical game modes can be used like sandbox (universal game mode), survival (unavailable if enemy base is true), attack (available if enemy base is true) and pvp (same as attack).
Edit: Campaign maps that need some requirements does NOT count

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This can make planet generation by mod makers "better" that is why i am making this issue.
Note: Make custom planets that have their own generation type, already added planet generation types can be customized in another simulation.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Wasn't there a discussion regarding this?

**Comment by firstcreator48** [comment]
> Wasn't there a discussion regarding this?

H

**Comment by firstcreator48** [comment]
¯\_(ツ)_/¯
it has been a plenty of days and i think...
i guess there are some
i dunno... ¯\_(ツ)_/¯
*sent on gmail*
