### ISSUE TITLE
Camera Anchoring

### ISSUE THREAD

**Issue by PhoenixRising060** [Anuken/Mindustry-Suggestions#2193]
**Describe the content or mechanics you are proposing.**

In the mobile version of the game, when you pause, move the camera, and unpause, the camera moves and, if possible, the current unit moves to where the camera is.  I'd like to suggest a Camera Anchoring option for those that wish either the desktop versions to not jerk to the current unit, or for it to shift on the mobile versions, or just for people who don't want motion sickness

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Really mostly a QoL update than anything, however, I do know that many people get motion sick from events such as that, and for those on desktop versions, it could help retain players, before they uninstall it for making them sick with camera jerks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueThecno** [comment]
You could just put a router near the core and then move the camera there, you not even need to unpause.
