### ISSUE TITLE
Processors: Please add a Title for the Processors itself and Comment-Blocks

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2195]
**Describe what you would like changed, and why.**

Processors are a great feature of Mindustry, but unfortunately, the overview gets lost very quickly and one loses a lot of time debugging.

Therefore one simple thing would be very helpful: Two kind of descriptive texts

**Describe the changes you want to propose. Include possible alternatives.**

## 1) Please allow us to add a title / one comment to each process block. 
- The title describes what the process block does.
- The title is displayed in the tooltip when the mouse is over the process block during the game

**This helps a lot to:** 
- find the right blocks: No need to remember: _The third block from the top right detects targets._
- and no need to open each block and look inside if one wants to know what it does or if one is looking for a block.

## 2) Please add a *Comment Block* to the programming language

The **comment block**:
- allows writing comments as longer text (several lines)
- can then be inserted and moved into the code like any usual code-block. It has no function itself. It only displays the Comment :-)

**This helps a lot to:** 
- understand code
- find the right position even after months
- ...

Thanks a lot, kind regards,
Thomas

**Comment by Kyllingene** [comment]
The ambiguous usage of the word "block" here is a little confusing, but if you mean what I think you mean (titles for the block you build, comments as in the blocks inside the blocks you build), then yes, this makes sense.

**Comment by DeltaNedas** [comment]
```
# i am a comment
print "egg" # why not
```
you can already do this

**Comment by Kyllingene** [comment]
bruh
thats only in the text editor
