### ISSUE TITLE
Make steamcloud saving also save mods

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2196]
**Describe the content or mechanics you are proposing.**
Make steam cloud saving also save installed mods.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently, the steam cloud saving is a useful tool, but it could be better.
It's always a hassle to have to download mods when travelling between 2 computers

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
There is a limit to Steam cloud save capacity per account (2 GB), while there is no limit to the size of each mod or the number of mods you can have installed.

For that reason, this suggestion is not feasible.

**Comment by PolloUsami** [comment]
I am prety shure this could break some form if EUA

**Comment by Johnystar** [comment]
As long as the mods are downloaded via Mindustry's built-in mod installer, you could just save the mod links in a config file and redownload them if they're missing.
