### ISSUE TITLE
Public server list for mindustry 3.5

### ISSUE THREAD

**Issue by Somka000** [Anuken/Mindustry-Suggestions#2197]
**Describe the content or mechanics you are proposing.** Public server list for 3.5

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** Version 3.5 still has a lot of fans, a lot of players play it every day. However, many of these players dream of playing with other players on server, not only on singleplayer. Therefore, I propose to add a public server list to which anyone can add a server on 3.5. I am currently the owner of four servers on 6.0 version and I can host one on 3.5 version. The 3.5 server list would work the same as the 6.0 server list, anyone who clicks the "multiplayer" tab will see the public servers.
I would like to make players happy and make this server for fans where everyone could meet and play together like in the old days, three years ago. 
Maybe even a new wave record will be created...

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Well considering 3.5 is unmaintained at this point. This has a minimal chance of being added in, however if server owners are considering supporting this, I guess why not. LOL.

**Comment by Anuken** [comment]
I don't have the right tools for deploying a new build of 3.5 anymore, and the Android build scripts are so outdated that I wouldn't even be able to upload a new APK to Google Play.

**Comment by Kyllingene** [comment]
In this case, I would say the best option is to make a simple repo for it, similar to the 6.0 one, and just point people to it in a few places. Eventually, word of mouth would do the work for you, and an in-game button probably wouldn't be necessary.
