### ISSUE TITLE
New propose mechanical and tactical game Mindindustry

### ISSUE THREAD

**Issue by MasterDiablo** [Anuken/Mindustry-Suggestions#22]
1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

- Give the possibility to choose the inputs and outputs on the pieces such as filters and distributors, also give the possibility to choose whether to close some outputs if necessary ..
because especially in the intersections with many parallel pipes they do not know how to automatically recognize the input and output of the material and often move material on nearby conveyor belts that have nothing to do with it.
When you have 3 parallel pipes and place a block in the middle, it would be convenient therefore to have the possibility of using, for example, filters and reverse separators or distributors that make the material come out only on one side.
Same goes for the overhead conveyor belt, because if it ends near 2 belts it divides the load instead of sending it in the desired direction, which can be forward or on one side or two sides etc.
- Avoid unwanted materials passing through the filter if it is placed near the automatic exit of factories or mines (it must be like a wall, the material must stop before entering the filter.)
- Also add an x1 line to be placed on any side of the conveyor belt as if it were a wall so that it can pass near the augers without being polluted by other materials.
- We need to better manage the transport of resources for the turrets ...
if I want to have a wall of turrets next to each other and I have to make a single row of "distributors" to fill them with material .. I can't put different turrets because I can only transport one type of material and above all I can't bring liquids.
it would be better if the turrets directly absorb what they need from the conveyor belt that passes nearby so that different materials can be sent on the same belt.
Then give the possibility through a panel to choose for each turret (with multiple selection option) which materials to take in order to have different projectiles with the same towers and then also to have a more generic panel where you can assign the material and liquids for all the turrets of that type.
At this point, a conveyor belt must be created that transports both liquids and material, or else create factories that perhaps with sand and silicon or only silicon (without the use of energy) close the liquids in containers which are then transported by the normal conveyor belt.
Or automatically collect all the resources that pass up to stock fill, so as to have a mix of everything (random or chosen by us) in each turret. (Which will fire different bullets as it empties.)
- another variant, add for each turret a 1x1 teleporter that automatically collects the necessary materials by spending a tot of energy for a tot of quantity transported by special warehouses made for teleportation (the teleporter can connect to more warehouses and can serve different turrets to the same time) [more warehouses will be connected and slightly more energy will be needed to transfer the same amount of resources]
-Give the energy nodes a maximum flow rate per second in order to study a strategy also to displace the generators and factories well as well as the nodes themselves.
- In this regard, air or underground energy ducts with different flow capacities could be created so as to have a more logical transport with small and large pipes to which to connect the various input and output nodes.
- Or also create other nodes with a greater flow rate of both energy and distance than those that already exist, and which require less materials than the aforementioned transport pipes ... but at the same time they waste a very small part of energy to keep active .
In that case, 1x1 solar panels located along the way would also become much more useful.
- It is very important to create a statistics panel that in real time reports the average of all the positive and negative productivity data, constants and maximum peaks ... for example ... how much energy I produce, and how much is needed .. and which gives you advice on quantity of generators to have and storage batteries to have to withstand high consumption peaks.
-Having a panel when I click on any point on the conveyor belt that illustrates the maximum material flow rate and the current flow rate based on the amount of flow coming from the other intersections (if any) and from the augers.
In this regard, have a special screen panel that colors all the 1x1 points of the conveyor belts in green yellow and red according to the average flow quantity, so as to better position excess separators and filters.
- Give the possibility with the game schematics to choose the pieces with multiple selection sequence and add the option of clicking the single piece as well as dragging.
- try to always improve the graphics and simplify some actions with the use of some already active functions such as moving quickly on the map using the minimap (me his Android smartphone with pen)
i have only been playing for three days and this game is amazing. and surely he can improve more and more.

I am Italian and I apologize for my English because I use the google translator and I don't know if it translates all right.
Good job

**Comment by CaribbeanMax** [comment]
no offense but the entire list of logistic changes you suggest are all things that make designs fun for this game, because you can do most of these things already, figuring out how is the challenge

**Comment by KK6DOC** [comment]
What the guy above said

**Comment by micoplasma** [comment]
yeah what ↑ said
