### ISSUE TITLE
Folder System For Schematics

### ISSUE THREAD

**Issue by Fabbe70** [Anuken/Mindustry-Suggestions#220]
A folder system in which you can name and sort folders in the same way folders are structured on windows.

A folder system for schematics makes life easier when trying to find a specific kind of schematics. For example, when I’m playing single player I want a specific kind of schematics, but when I play pvp I want a different type of schematics. This feature will spare players like me a lot of time searching for the right schematic.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
I think it's better to have schematics with tabs instead of a folder system

**Comment by Fabbe70** [comment]
Yeah, you’re probably right about a tab system. But this was just to try and inform and maybe spark an idea in Anukens head. It is after all his game and it’s up to him to decide.

**Comment by zethnest** [comment]
I can implement this and do a PR. But I don't have the time currently.

**Comment by DeltaNedas** [comment]
when

**Comment by rodrigolitzius** [comment]
Why is this taking so long?
