### ISSUE TITLE
Universal input and output menu section

### ISSUE THREAD

**Issue by roaringwriter13** [Anuken/Mindustry-Suggestions#2200]
What I want to implement is hard to describe so I'll do my best. 
So, the Feature Request is a Universal input and output menu section. 
Basically, a search bar of what can be crafted/given of a specific item. 
For example, I type "lead" it will start to search blocks that can be crafted/given for that exact item like a copper drill can give lead or a lead drill can be crafted using that item. 
Obviously, there would be two subsections for crafted and given.

The reason i think this content will improve the game is that I play with too many mods and with that too many items I don't need when playing the game, so with that feature I'm more able to get easier access to the content i need.
thank you.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
So a recipe book?

**Comment by roaringwriter13** [comment]
yes

**Comment by genNAowl** [comment]
Feels like something inspired from minecraft

**Comment by roaringwriter13** [comment]
it is not it just not I play with too many mods, and problem get more noticeable.

**Comment by joshuaptfan** [comment]
Best done as a search bar in the core database.

**Comment by roaringwriter13** [comment]
yeah but its all the blocks and items at your face

**Comment by Kyllingene** [comment]
What is the alternative?

**Comment by roaringwriter13** [comment]
what i request

**Comment by itcannotbe** [comment]
The other alternative is not playing with lots of mods. It kinda gets pointless past some point and you're just giving yourself unnecessary bloat to play around with.

**Comment by Kyllingene** [comment]
Not even close to a solution.

**Comment by itcannotbe** [comment]
Why not make a mod that addresses his problem, cause we know that his problem is caused by him playing with a large number of mods in the first place?

It's fair game since mods cause his niche need, make a mod that would address the problem made by mods.

**Comment by roaringwriter13** [comment]
well, i like to play with lots of mods, I think it fun. Although it can still be useful

**Comment by Bohaska** [comment]
I think that a graph which connects all of the items to their inputs and outputs would be better, something like this
<img width="713" alt="Screen Shot 2021-03-26 at 3 20 58 PM" src="https://user-images.githubusercontent.com/73286691/112596541-ee315f00-8e46-11eb-9817-2ca57e749fdb.png">

**Comment by itcannotbe** [comment]
Do that in the context of why OP originally suggested the feature and you'll get a large pile of shit. Pointing to each other.

**Comment by Bohaska** [comment]
> Do that in the context of why OP originally suggested the feature and you'll get a large pile of shit. Pointing to each other.
Recently adjusted my above comment

> A cleaner version would be for Mindustry to only show you the connections for 1 object at a time

**Comment by roaringwriter13** [comment]
> I think that a graph which connects all of the items to their inputs and outputs would be better, something like this (Made with Powerpoint)
> <img alt="Screen Shot 2021-03-26 at 3 20 58 PM" width="713" src="https://user-images.githubusercontent.com/73286691/112596541-ee315f00-8e46-11eb-9817-2ca57e749fdb.png">
> 
> A cleaner version would be for Mindustry to only show you the connections for 1 object at a time

me like that

**Comment by roaringwriter13** [comment]
so will my request be closed?

**Comment by Kyllingene** [comment]
If you close it. Anuke no longer closes issues; it took too much time.

**Comment by OnyxFinger** [comment]
I think it would be neat to have this in the data base, especially for mods.
