### ISSUE TITLE
Automatic bridge conveyors work even if you haven't unlocked bridges

### ISSUE THREAD

**Issue by chris-ac-malone** [Anuken/Mindustry-Suggestions#2201]
This is a small thing and one you probably wouldn't even notice if you've been playing for more than ten minutes, but the automatically placed bridge conveyors will be placed even if you haven't unlocked them in the research section yet.

**Comment by joshuaptfan** [comment]
1. Fill out the template, don't delete it, if you want your suggestion to be taken seriously
2. Duplicate of #2156
3. [It's already been fixed](https://github.com/Anuken/Mindustry/issues/4875)
