### ISSUE TITLE
More logic

### ISSUE THREAD

**Issue by Gamer123-games** [Anuken/Mindustry-Suggestions#2202]
**Describe the content or mechanics you are proposing.**
A logic block called a radar block will create a radar and it has to be connected to a radar connected rocket launcher

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will improve the confidence of the player making them feel more powerful so they will take on more harder terratory making them go threw the game faster

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Gamer123-games** [comment]
Cool huh

**Comment by joshuaptfan** [comment]
Logic can radar units within any turret's range through the turret. A separate "radar block" is not needed.

**Comment by Kyllingene** [comment]
> making them go threw the game faster

No game ever should try to reduce its effective "fun time."
