### ISSUE TITLE
Planet based wave team

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#2203]
**Describe the content or mechanics you are proposing.**

Add a variable in `PlanetGenerator` that changes the wave team on that specific planet.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

For modders, this can allow custom planets to feel like the enemy is not the Crux, but instead some other color because every sector on that planet would have the same non-Crux team as the enemy.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
good
