### ISSUE TITLE
An idea for sector superweapons (from trello)

### ISSUE THREAD

**Issue by DireWolf575** [Anuken/Mindustry-Suggestions#2204]
My idea is more of a rough than a full idea, i thought suggestions like this might help you tie them in with V7 with less work on your part to come up with 100% new ideas by yourself :)

- a 10x10 (roughly.. just very difficult to fit to necessitate construction after sector capture, or only in very large sectors) needs massive amounts of ammo, power, and perhaps cryofluid) you can only build 2 or 3 per planet
        - cannot fire within a certain radius of the core on attack/multiplayer
        - alternate idea is that a few are scattered around the planet, capturing the sector allows you to use them.
        - ammo type determines effect
               - thorium or surge for massive impact and huge radius damage (less against buildings and cores)
                        - 60-70 tiles? {~5-10% building damage}
               - titanium is a massive healing burst to all friendly buildings and units in a huge area
               - graphite is .7 fire speed, similar damage to thorium, much smaller radius, {~20-25% building damage)
                       - best for destroying sections of walls or sniping some production just before attack
               - plastinium fires a wide spread of medium damage mini bullets, shotgun style
                       - 30% bulding damage, but each fragment/mini bullet does ~400 damage
                       -  for clearing out lots of t1-t3 units
 - unlocking the gun opens a new hud space, "orbital weapons"? and a button corresponding to a specific gun in a specific sector
         - for every sector that the round must travel over, it gains an extra second or two of time until arrival
         - each gun can only be fired every 10-15 minutes (or longer for balance)
- for multiplayer, it can fire faster, but has a limited range, cannot fire within a certain radius of the core
         - maybe even smaller/cheaper

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I was looking through the trello page and saw an idea for superweapons, and that there was currently no information

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
This does not fill a niche, nor fulfill a need, nor bring more diversity to the game, nor bring more strategy to the game. What is the purpose?

**Comment by MrDuck557** [comment]
I agree with above
It's kind of like a sidequest that gives you the ability to call in an airstrike whenever you want one

**Comment by Kyllingene** [comment]
The thing is that this game is not made for sidequests.

**Comment by DireWolf575** [comment]
As stated above, while this does not directly fill a **current** niche, On the official mindustry trello page there is a card for " 1-2 sector superweapons" this card's information is only "TBD" so i shared a possible idea for what a sector superweapon might look like.

While I do not inted to be toxic or agressive, I feel you should read _all_ included details.

**Comment by Kyllingene** [comment]
No, this is the right place. My only concern is that, since this fills no need nor niche, it is probably not what Anuke meant when he made that card.

**Comment by OnyxFinger** [comment]
I kinda like this idea, it would not be very useful but v6 campaign is already kinda bad at some point, good at the begining but the end is just horrible, adding some fun to it by being able to blow stuff up along with having an objective for capturing ressource sectors and not "preset sectors" (idk why Anuke called them that every sector is preset), would add a little more to do afterwards.
I think being able to clear out sectors with a button is fun and just lets you gain time in general, so I would like it.
However, it should not have a multiplayer counterpart.
