### ISSUE TITLE
Megasectors

### ISSUE THREAD

**Issue by MrSkyBlue1020** [Anuken/Mindustry-Suggestions#2205]
Please close this issue

**Comment by genNAowl** [comment]
The largest map you can create is a 999x999 map, and this is for good reason, too - any map bigger than that will severely impact performance on good computers and completely kill phones running them, so how do you propose to run a 5000x5000 megasector?

**Comment by itcannotbe** [comment]
Heck phones already suffer on custom 2k x 2k maps.

And 5k x 5k has 625% more more tiles compared to a 2k x 2k map.

**Comment by NajimiOsana** [comment]
tl;dr **Lag** Exists.

**Comment by Bohaska** [comment]
> tl;dr **Lag** Exists.

hes not talking about multiplayer....

**Comment by itcannotbe** [comment]
Heck playing below 15 FPS is already deemed unplayable/unsupported.

**Comment by Kyllingene** [comment]
> hes not talking about multiplayer....

Lag has two meanings. The correct one, which is basically ping, and the wrong one (unfortunately also the accepted one), which is frame drops.

**Comment by numer99** [comment]
I like your idea, but I want mindustry to run at 60+ fps please.

**Comment by wellsilver** [comment]
> > hes not talking about multiplayer....
> 
> Lag has two meanings. The correct one, which is basically ping, and the wrong one (unfortunately also the accepted one), which is frame drops.

I've learned my entire life that lag is when your FPS drops below a commonly accepted number (like 60fps) While I have no idea what the word for high ping is its probably IHAS (Internet having a stroke)

**Comment by wellsilver** [comment]
> > hes not talking about multiplayer....
> 
> Lag has two meanings. The correct one, which is basically ping, and the wrong one (unfortunately also the accepted one), which is frame drops.

Its ok for a word to have 2 meanings

**Comment by sample-text-here** [comment]
i'd like to interject for a moment. what you're referring to as "lag"  is, in fact, also known as "latency" or "ping". all three terms refer to the same thing - the amount of time for a response to travel from a client to a server and back. however, according to the english dictionary, a definition of lag is "to stay or fall behind". this could be misinterpreted as the alternative (and incorrect) meaning, where the number of frames drops.

**Comment by Kyllingene** [comment]
> Lag has two meanings. The correct one, which is basically ping, and the wrong one (unfortunately also the accepted one), which is frame drops.

**Comment by G0nTar** [comment]
> > hes not talking about multiplayer....
> 
> Lag has two meanings. The correct (original) one, which is basically ping, and the wrong one (unfortunately also the accepted one), which is frame drops.

Actually you can't have Lag on single player, since you are not connected to anything that can make you feel lag (latency).

You can experience "Bad game Performance" and studdering

**Comment by Kyllingene** [comment]
Hence this part of the sentence (emphasis added):

> and ***the wrong one***, which is frame drops.

**Comment by wellsilver** [comment]
this is actually a semi good suggestion and now i know why alot of people dont have a automatic stale bot.
