### ISSUE TITLE
Mindustry Processor: Please provide a command: sensor missingRsc @factoryX @awaitingRessource / @awaitingRessourceItems

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2206]
## Describe what you would like changed, and why.

Hello

we have a great community writing scripts for Mindustry and they very, very often replicate the game mechanics (Pseudocode):
``` Pseudocode
if factory builds a Mono
  if (15 - factory.silicon) > 0
    get silicon for Mono

  if (10 - factory.lead) > 0
    get lead for Mono
end 
```

#### 1) After an update of Mindustry it could happen that…
the game balance is adjusted and one suddenly needs 15 Lead (instead of 10) for the Mono.

- The scripts still work, but most don't work as described. 
- Mindustry Players will be unhappy because they don't understand the context. 
- The user has to figure out which script works with which version. 
- This then, unfortunately, falls back on the game itself: _"It would be great! but many extensions don't work."_

#### 2) It's also troublesome because the factory already knows the usual answer: 
what resources does it need to do its current task?

## Describe the changes you want to propose. Include possible alternatives.

With just two small additional `sensor` attributes to the Mindustry Logic syntax, most existing Scripts would get much, much more simple and **robust** :-)

- **Addition 1: Is there any resource missing?**, e.g.
```
// is factoryX waiting for a resource to do it's current job?
// Important: 
// • it just reports the first missing resource
// • after it is refilled, then the command reports the next missing resource (if there is any)
sensor missingRsc @factoryX @awaitingRessource
```
- **Addition 2: How many items of the missing resource do we need?**, e.g.
```
// how many items does the factoryX needs to do it's job?
sensor missingRscItems @factoryX @awaitingRessourceItems
```

**Comment by itcannotbe** [comment]
this should be a feature request to be honest as you are requesting things (in this case logic related things)


> Mindustry Players will be unhappy because they don't understand the context.
Most users of mindustry logic don't even understand logic to begin with.

**Comment by schittli** [comment]
Hello @itcannotbe 

thank you for your feedback!,

> Most users of mindustry logic don't even understand logic to begin with.

Yes, that's true, but most steam users know how to use workshop items: there are easy to find guidelines on how to quickly add logic/schematics from the steam workshop or other sources.

Therefore, we have for sure users which do not understand the scripting concepts but know how to use shared components. And that's great, because it makes the game more flexible :-)

**Comment by stuffyAI** [comment]
Logic is overpowered as it is, but if we wanna balance it by general availability this should happen, that way even lesser experienced users can keep using such schematics to compete with those who'd keep them updated.
