### ISSUE TITLE
General Improvements to Sector Icons

### ISSUE THREAD

**Issue by vooxal** [Anuken/Mindustry-Suggestions#2207]
**Describe the content or mechanics you are proposing.**
Currently, all sector icons are just random stuff. There are so many random icons such as the github icon(s) or the itch.io icon.
![image](https://user-images.githubusercontent.com/58456527/112684667-94be3580-8e30-11eb-8c8b-5ba36d5eea40.png)
Here is what I propose.
* Unique icon for each non-numbered sector
* More relevant icons like material icons or a pickaxe to show resources
* Remove all non-relevant icons like the github icons or stuff
* Group the icons better. They are so unorganized 
![image](https://user-images.githubusercontent.com/58456527/112685186-7147ba80-8e31-11eb-84f5-31e99ced62bb.png)
* Give the ability to change the color of the sectors.
![2021-03-26_12-48](https://user-images.githubusercontent.com/58456527/112685420-c388db80-8e31-11eb-97ab-5aa925ab7ef5.png) - Default
![2021-03-26_12-48](https://user-images.githubusercontent.com/58456527/112685561-0054d280-8e32-11eb-95ea-d4ffca87c207.png) - Colored Red

This will help with orgainzing your sectors and give a more a personalized experience.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by numer99** [comment]
Yes, please organize them anuken.

**Comment by Humanoid-X** [comment]
good

**Comment by Jammo2000** [comment]
Organization would be super helpful. You wouldn't even need to remove many icons if they were sorted so that the more useful ones came first.
