### ISSUE TITLE
[v7] Tar-themed naval units

### ISSUE THREAD

**Issue by numer99** [Anuken/Mindustry-Suggestions#2208]
**Describe the content or mechanics you are proposing.**
New Tar-themed naval units
t1. naval unit that explodes with tar (like crawler)
t2. naval unit shoots tar on buildings, making them slowly take damage and get slower
t3. naval unit that pollutes the water with tar and shoots sparks
t4.
t5.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will balance out the lack of oil/dry/tar theme

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

sorry if I did anything wrong

**Comment by Humanoid-X** [comment]
good idea

**Comment by stuffyAI** [comment]
Why do you exactly feel the need to "balance out the lack of oil/dry/tar theme"?

**Comment by numer99** [comment]
idk it just has a lack of desert-theme stuff

**Comment by OnyxFinger** [comment]
I like the tar themed idea, I think it would be cool on tar maps, if there are ever any \:

**Comment by Kyllingene** [comment]
I would love for alternate-liquid units to be a thing, but they just don't seem viable. Who in their right mind would make a unit limited to a small tar pool? And no, adding units solely for the few tar-themed maps that would end up being made for them is not going to happen. That is too much work for so little gain. Again, I would personally love for slag/tar units to exist, it just seems unrealistic to expect them.

**Comment by Kyllingene** [comment]
Ah, ok. That sounds great too!
