### ISSUE TITLE
Multiplicative Reconstructor

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2209]
**Describe what you would like changed, and why.**
In game we have 3 stage of game: low, mid, late game. Titanium unlock unlock laser drill and some turrets. Thorium unlock all game content. But units are different. Even if you have titanium, you still have only T1, T2 unit's. For T3 you need thorium, end game ore. I think units should be spread on 3 groups: low T1/T2, mid T3, late T4/T5

**Describe the changes you want to propose. Include possible alternatives.**
Change build cost for Multiplicative Reconstructor. Thorium -->Plastanium.

**Comment by joshuaptfan** [comment]
I agree, removing titanium and/or thorium from maps is how you restrict the available tech on custom maps. There currently is no unit tier that is made available when you have titanium but no thorium.

**Comment by Kyllingene** [comment]
I find the concept of thorium being late-game and plastanium being early-game funny, but logical. +1

**Comment by genNAowl** [comment]
> I find the concept of thorium being late-game and plastanium being mid-game funny, but logical. +1

Same. But this is generally because plastanium on most map is generally made from either thermal pumped tar or oil extractors, which both require thorium, which is why you see thorium being made before plastanium. 

Also, thorium is extremely easy to get, as all you need to do is place a laser drill on some ore, while one needs to actually setup an elaborate factory to make plastanium.

**Comment by Kryvytsky** [comment]
> > I find the concept of thorium being late-game and plastanium being mid-game funny, but logical. +1
> 
> Same. But this is generally because plastanium on most map is generally made from either thermal pumped tar or oil extractors, which both require thorium, which is why you see thorium being made before plastanium.
> 
> Also, thorium is extremely easy to get, as all you need to do is place a laser drill on some ore, while one needs to actually setup an elaborate factory to make plastanium.

Rotary Pump and Spore Press not require torium, so I related plastanium to mid game resource and I suggest change thorium to plastanium.

**Comment by itcannotbe** [comment]
The only reason why people farm thorium earlier than plast because people can't be bothered not using oilex based plast comp schematics.

**Comment by Kryvytsky** [comment]
This change will not affect strong bases where you only need T5 units. Perhaps not everyone will be able to understand then why this change is needed? I'll try to explain this again.
I think a lot of people skip low level sectors. Me too, but once I decided to play them without resources. I liked it. I've spent so much time with endgame technology that it feels like a different game to play on a sector without thorium or titanium. But, the problem is in the sectors with the enemy base. You can build T1/T2 units even without titanium, but to build T3 you already need thorium. But what's the point of building T3, if with the discovery of thorium you have access to T4/T5? It's possible on campaign to destroy enemy core due to horrible builded deffence, but it also does not let possible to create custom maps for attack with mid game technologies, since only T1/T2 will be available for attack.

**Comment by PickAPlayerNameFirst** [comment]
Yes that's right, but that raises the question: If T3 reconstructor removes thorium from build cost,  will players won't abuse it? In pvp multiplayer Zeniths are already considered OP due to its firepower when released in hordes, thats when you offer zeniths to be easier to unlock.

**Comment by PickAPlayerNameFirst** [comment]
> considered

And also, I think thorium serves as a "guide" to make more resources,  bcuz thorium unlocks Airblast Drills, and those bad bois drill more efficiently, giving you more resources to build T3 units. That way you can easily get thewin that you want.

**Comment by Kyllingene** [comment]
>  Zeniths are already considered OP due to its firepower when released in hordes

Then balance *them*, don't unbalance the *rest* of the game around them.

**Comment by Kryvytsky** [comment]
> Yes that's right, but that raises the question: If T3 reconstructor removes thorium from build cost, will players won't abuse it? In pvp multiplayer Zeniths are already considered OP due to its firepower when released in hordes, thats when you offer zeniths to be easier to unlock.

They are OP, cuz most players don't care about defence. Also we have good mid game turrets like Salvo, Swarmer, Cyclone. Also, produce a 650 plastanium is more problematic, cuz you need a whole factory and for 650 thorium you need just a drill. So thorium require less resourses and less power. So I guess this change actually nerf a T3 unit's by making them more problematic to build. 
The main point, why I want this change is to make possible a no thorium attack maps.
