### ISSUE TITLE
Force projector to defend from lasers

### ISSUE THREAD

**Issue by KBOPYM** [Anuken/Mindustry-Suggestions#221]
**Describe the content or mechanics you are proposing.**
Make force projector consume the damage from those Laser and "laser bolt" (e.g. tau) projectiles.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Due to introduction of "Point defense turrets" we need a way to protect from Laser and "laser bolt" (e.g. tau) projectiles, since there is none yet.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by gen-NA-owl** [comment]
Plastanium walls will do that in 6.0, I think.

**Comment by KBOPYM** [comment]
> Plastanium walls will do that in 6.0, I think.

yea, that was added after I posted this.
