### ISSUE TITLE
If an air unit is killed too hard, make it explode instantly

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2210]
**Describe the content or mechanics you are proposing.**
If the shot that kills an air unit has significant damage compared to the unit's health, explode the unit instantly without it falling - for example, a foreshadow hitting a horizon or a flare

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Units exploding instantly on very hard hits makes more sense

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
An elegant solution to the [crashing units debate](https://discord.com/channels/391020510269669376/663853133587546138/811745574386139146) that requires player initiative.

**Comment by MauritanianMapping** [comment]
"Is killed too hard" is one hell of a title

**Comment by RedstonerKBC** [comment]
> "Is killed too hard" is one hell of a title

Ikr.

This also reduces lag in some cases.

**Comment by Ilya246** [comment]
Air units could just explode if the absolute value of their health while it's negative exceeds their max health

**Comment by Kyllingene** [comment]
> An elegant solution to the crashing units debate that requires player initiative.

Wait a minute... if only very high-damage turrets would deal enough to do this, then the majority of air units would still crash and explode... am I missing something?

**Comment by joshuaptfan** [comment]
> Wait a minute... if only very high-damage turrets would deal enough to do this, then the majority of air units would still crash and explode... am I missing something?

Right, fuse and spectre would only be able to overkill flares, and only foreshadows would be able to overkill flares, horizons, and zeniths.

If necessary, the overkill threshold could be lowered to 150% of unit HP.

**Comment by Kyllingene** [comment]
Ok. I forgot that fuse and spectre shoot fast enough to take a few units down (I was thinking about foreshadow).

**Comment by Jammo2000** [comment]
Maybe falling units should still take damage towards the explosion threshold. Turrets wouldn't target them, but they could still take damage and absorb bullets. To balance this, the threshold could be raised to about 3x. This would keep cyclone and similar good against flares.

**Comment by Kyllingene** [comment]
But then what about the small air defenses, perfectly sized for their sector? For example, a small 5-scatter cluster on Ground Zero. They would get their bullets absorbed by already-dying units, in a scenario where people already expect to have to manually repair blocks after each attack. Then, the other flares would be free to deal plenty of damage.

**Comment by itcannotbe** [comment]
> Maybe falling units should still take damage towards the explosion threshold. Turrets wouldn't target them, but they could still take damage and absorb bullets. To balance this, the threshold could be raised to about 3x. This would keep cyclone and similar good against flares.

The suggestion is already balanced. There isn't a need for this.

**Comment by itcannotbe** [comment]
awhat about if you check the last x number of frames (step scaled with delta-time) and see if the damage received exceeds a certain amount compared to HP?

**Comment by MEEPofFaith** [comment]
"killed to death"

**Comment by Bohaska** [comment]
1. This suggestion is good
2. If you ever happen across this, why are you using foreshadows to kill flares???

**Comment by Ilya246** [comment]
When a unit is dead bullets could still damage it but penetrate through it so you don't get the bullet absorption problem

**Comment by stuffyAI** [comment]
> When a unit is dead bullets could still damage it but penetrate through it so you don't get the bullet absorption problem

But it is balanced around it

**Comment by BlueThecno** [comment]
> 2. If you ever happen across this, why are you using foreshadows to kill flares???
>>>

Just a random flare that *just so happens* to pass close enough to the foreshadow to shot it down.

**Comment by Zarcana-The-Hypermech** [comment]
In other words, its like "Gibbing" from doom
