### ISSUE TITLE
Toggle for auto exit of game upon launching with modified ui scale

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry-Suggestions#2211]
**Describe the content or mechanics you are proposing.**

Currently whenever you relaunch the game with a new UI scale, it'll ask you whether this was intentional. If you wait 10 seconds, it'll automatically close. I am asking for a toggle in settings to disable this, as I know what I'm doing, and would prefer to not have it on. The default would be set to true.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will make it so I don't need to worry about my game closing automatically because I left it for 10 seconds.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
what if it glitches and you are unable to do/see anything after you turn this option off and change ui scale? you are now stuck and you have to delete your settings.bin

i disagree with this suggestion

**Comment by nichrosia** [comment]
If you have to delete your settings.bin, then you lose a few toggles. You can easily change them back within less than 2 minutes.

**Comment by nichrosia** [comment]
Also, this would be a toggle, so if something like that happened, you could turn it off to make sure it doesn't happen again.

**Comment by joshuaptfan** [comment]
Not only is the setting dangerous as mentioned above, but even if it wasn't dangerous, all it does is save the user 1 click in very specific (and for most players, rare) situations which involve many other clicks, so it still wouldn't be worth adding.

You must be suggesting this because you change UI scale frequently. Why do you need to? And does Mindustry really take so long to restart that you need to do other things while waiting?

**Comment by QmelZ** [comment]
> you lose a few toggles.

it's more than "a few", and you lose your uuid.

**Comment by nichrosia** [comment]
> You must be suggesting this because you change UI scale frequently

Due to a bug with adding a custom setting, it says that I change my UI scale every other time I launch Mindustry, and if you are a modder, you need to restart frequently for changes to take effect. 

> all it does is save the user 1 click in very specific (and for most players, rare) situations which involve many other clicks

Good point. If anything I should be making a bug report about this odd bug, and try to find a sure way to reproduce it.
