### ISSUE TITLE
Automatic updating!!!!!!!

### ISSUE THREAD

**Issue by wellsilver** [Anuken/Mindustry-Suggestions#2212]
**Describe the content or mechanics you are proposing.**

Automatic updating

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I've allways found it annying to haved to delete mindustry then go to the page, download it, and etc. It takes like 4 minutes and I haved to do it every. single. time. I play because you release updates so fast.

i think it might be easy for you to integrate as it is literally just downloading data and implementing it. I think alot of people who come back after a while would love auto updating because it just updates the second they turn it on, or in the background. Wich is alot faster then figuring out you cant play most servers because you haved to wait like 5 minutes to play. Imagine a 5 minute loading screen except you haved to manually do everything.

Im very surprised I didnt find any opened or closed requests on this 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
It would remove a little value from the paid Steam version, but that might not be the main concern for Anuke, given that it's mostly free already outside of Steam.

Meanwhile, if you want auto-update now, just buy the Steam version.

**Comment by QmelZ** [comment]
1. there is a mod for this
2. you can use the standalone jar with a batch/shell script to autoupdate for you
3. use bleeding edge which has an auto updater built in
4. use steam

**Comment by Kyllingene** [comment]
> use bleeding edge which has an auto updater built in

**Comment by Bohaska** [comment]
> 1. there is a mod for this
> 2. you can use the standalone jar with a batch/shell script to autoupdate for you
> 3. use bleeding edge which has an auto updater built in
> 4. use steam

5. use itch.io launcher

**Comment by Fipico2** [comment]
You should have asked before making this you know

**Comment by DeltaNedas** [comment]
@wellsilver close this noob

**Comment by RedstonerKBC** [comment]
> 1. there is a mod for this
> 2. you can use the standalone jar with a batch/shell script to autoupdate for you
> 3. use bleeding edge which has an auto updater built in
> 4. use steam

Every application except Mindustry has support for at least an in-app update button so you don't have to do anything complicated. Like just take a moment and imagine how ticked people would be if everytime Discord had a new update you either had to code your own mod, write a script, enable bleeding-edge mode, get Discord from Steam, or manually drag the files into the proper place.

**Comment by Kyllingene** [comment]
Ever heard of Bitwig? It's professional audio software. When it needs an update, you need to ask. Explain how you can make a release system on itch.io that doesn't involve bleeding-edge releases.

**Comment by Bohaska** [comment]
> Ever heard of Bitwig? It's professional audio software. When it needs an update, you need to download it manually. Explain how you can make a release system on itch.io that doesn't involve bleeding-edge releases.

The itch.io launcher periodically checks if anuke has updated the game. If it has, it updates it automatically in the background

**Comment by Kyllingene** [comment]
So all that would theoretically be required is for Anuke to implement it? How hard would that be?

**Comment by itcannotbe** [comment]
The game is already compliant to itch.io's policy so that users can already use the itch.io launcher to automatically update the game.

**Comment by Kyllingene** [comment]
So close then?

**Comment by itcannotbe** [comment]
> Im very surprised I didnt find any opened or closed requests on this

Because people already know about the itch.io app.

> So close then?

Exactly.

**Comment by itcannotbe** [comment]
> Every application except Mindustry has support for at least an in-app update button so you don't have to do anything complicated.

Ah yes you forgot that feature required you to have a server handling file request and that would be a lot of request come update day. It's basically a waste of IRL money.

**Comment by wellsilver** [comment]
Doesnt the server has auto updateing? lol but I guess there are too many third party solutions to make a 1st party solution
