### ISSUE TITLE
Discord: Western Moderator

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2214]
**Describe what you would like changed, and why.**
  Currently on the discord, we don't have an active western timezone based moderator, leading to as much as a 9 hour gap (about 15:00 to midnight, my time) where the channels go unmoderated while the eastern mods are asleep.
  I am suggesting that someone be promoted to moderate this time gap. *Choose wisely, I do **not** mean another Natalie type moderator!*

**Describe the changes you want to propose. Include possible alternatives.**
  I don't think there's any alternative, short of literally not caring.

**Comment by itcannotbe** [comment]
A slowdown might help. Since no one lazy enough would talk nonsense while a 1 minute slowdown is in effect.

**Comment by BlueWolf3682** [comment]
That won't help the behaviour. The discord simply needs active moderation.

**Comment by Axzye** [comment]
I'm guessing this suggestion was made due to multiple incidents with mods being offline :/

**Comment by BlueWolf3682** [comment]
That is correct.

**Comment by itcannotbe** [comment]
> I'm guessing this suggestion was made due to multiple incidents with mods being offline :/

The mods need to sleep, it's not like they're robots or something.

**Comment by Kyllingene** [comment]
> The mods need to sleep, it's not like they're robots or something.

That is the precise reason they are suggesting *new* mods in the western timezone. Or would you exclude half of america from constructive conversation just because finding a few decent people is too hard?

**Comment by Bohaska** [comment]
alternative: have a bot mod some of the server, like auto deleting links and censoring profanity

**Comment by Bohaska** [comment]
> A slowdown might help. Since no one lazy enough would talk nonsense while a 1 minute slowdown is in effect. Though unless discord implements this suggestion (https://support.discord.com/hc/en-us/community/posts/360055512052-Role-specific-slow-mode). I think entire server slowmode when mods are away is the way to go.

If mods have the Administrator permission, they get to skip every slowmode in place in the server

**Comment by itcannotbe** [comment]
> > A slowdown might help. Since no one lazy enough would talk nonsense while a 1 minute slowdown is in effect. Though unless discord implements this suggestion (https://support.discord.com/hc/en-us/community/posts/360055512052-Role-specific-slow-mode). I think entire server slowmode when mods are away is the way to go.
> 
> If mods have the Administrator permission, they get to skip every slowmode in place in the server

Actually they only need manage message permission to by-pass slowmide

**Comment by SpaceSceptralReignPlayz** [comment]
I think we should get the discord server's own suggestion channel

**Comment by itcannotbe** [comment]
> I think we should get the discord server's own suggestion channel

No that was a mess. That's why we move where we suggested stuff twice already. It was on discord in the beginning.

**Comment by BlueWolf3682** [comment]
> alternative: have a bot mod in the server, like auto deleting links and censoring profanity

The problem with that is that profanity isn't against the rules, as well as the modders send links to mods all the time.

**Comment by Bohaska** [comment]
so maybe make a bot that deletes every message that contains http or https, except if these messages include github.com in them

**Comment by Bohaska** [comment]
And also for profanity maybe only censor the extremely racist and vulgar ones

**Comment by itcannotbe** [comment]
> so maybe make a bot that deletes every message that contains http or https, except if these messages include github.com in them

The current bot already delete invite links

> And also for profanity maybe only censor the extremely racist and vulgar ones

That would be hell. As there are multiple ways to circumvent censors.

**Comment by itcannotbe** [comment]
> And also for profanity maybe only censor the extremely racist and vulgar ones

[Ah yes, a profanity censor.....](https://www.reddit.com/r/apexlegends/comments/mdggh6/a_japanese_player_got_suspended_because_he_said/)
