### ISSUE TITLE
Unit deconstructor

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#2215]
**Describe the content or mechanics you are proposing.**
Basically opposite of unit reconstructors, there would be 5 different deconstructors: tetrative deconstructor, exponential deconstructor, multiplicative deconstructor, additive deconstfuctor and <insert name you want> deconstructor for T1 units, they would output 75% of silicon consumed and downgrade units to thier lower tier (T1 die instead), they would still use power and still have production time

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would correct unit mistakes (example: noob accidentally makes vela on multiplayer or you mistakenly made a unit and regrets it)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

~~its currently 2 am on where i live and theres probably grammatical/spelling errors~~

**Comment by Bobbystevenson** [comment]
There is just no reason for it tho

**Comment by Kyllingene** [comment]
So you get a little bit of your silicon back, nothing else, just so that you can downgrade a unit?

**Comment by MauritanianMapping** [comment]
Couldn't there just be one building that essentially allows you to basically sell units instead of making 5 unnecessary buildings?

**Comment by RedstonerKBC** [comment]
Recycling isn't really something that is supported by the Mindustry community. I've made a few of related suggestions but they all had negative reactions.

**Comment by SpaceSceptralReignPlayz** [comment]
Mods, Specifically BetaMindy (if thats even the name of the damn mod)

**Comment by Humanoid-X** [comment]
No. There are no reason to add these blocks, and you get no benefit from it. Alsso, why are you discriminating against velas?

**Comment by itcannotbe** [comment]
This block would only makes sense if the unit limit system is something like starcraft's.

**Comment by stuffyAI** [comment]
>  noob accidentally makes vela on multiplayer or you mistakenly made a unit and regrets it)

Control them into the enemy, or even better, let them be blown up by a thorium reactor?

**Comment by G0nTar** [comment]
> Couldn't there just be one building that essentially allows you to sell units instead of making 5 unnecessary buildings?

This, please, need, just make it an expense building, that sucks a lot of power, and it let's you dispatch units back into Resources, instead of wasting it all
