### ISSUE TITLE
Powerful "Editor/Sandbox"-only variants of Logic Processors. (NOT more instructions/seconds)

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry-Suggestions#2216]
**Describe the content or mechanics you are proposing.**

Just like there are "Infinite Power" blocks in the Editor/Sandbox", there could be variants of Logic Processor to allow to do anything that is considered overpowered or game-breaking for normal Logic processors.

These variants could do all a normal Logic processor can do but additionally:
- Create Units out of thin air for a certain player (optional: with "Guardian Health Bar") (This will need some limit to prevent spawning way too many units in case of infinite loop bugs.)
- Send messages to the chat (Handy for debugging + sending messages to the player; for example for warning them that they are about to be attacked or for special scenarios)
- Can bind to enemy blocks (Handy when having multiple bases of different teams; or for example when binding to a player Logic Display but you don't want to give players this powerful Logic Processor)
- Can control enemy blocks (See above)
- Can control enemy units (See above)
- (Near) Infinite Link range (Handy for attack maps with large bases/linking to player blocks while trying to stay far away from it)
- Ask which block is at a given x and y coordinate. (Especially handy if linking to enemy blocks is not possible)
- Detect units near a given location (Handy to see if a base gets attacked)
- Set or Add Resources to a Core or Vault (Example: Quest rewards)
- Force player into a unit of a certain type (and lock him in there; can allow new type of "RPG style" maps)
- Teleport a unit (can be used to keep players within certain bounds; or allow for checkpoints)
... and much more (or less if you only like a couple of them).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
- It will help with map makers and schematics experts to make new things that are currently not possible.
- It will make new genres of maps possible. (Twin Stick shooter / RPG / Parkour / ...)
- It will help to make attack maps more easily
- It will allow for people to mess around in Sandbox mode.
Example: Want to simulate a fight of 100 Quasers vs 100 Spirocts?

Other games such as Starcraft 2 have "Trigger Editors" which allow map makers to make maps with a lot of interactivity. This isn't quite at the same level but it might be all people need to make new and better maps.

Feel free to drop your ideas what you would do with this new logic processor in the comments :).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
So they are basically command blocks from Minecraft

**Comment by NoExit4U** [comment]
Never heard of them, but after a quick google search they do seem to be quite similar, especially in purpose. So if that analogy helps then yes sure.
Of course the suggestion I'm making here is an upgraded version of the existing logic blocks and not an entirely new thing. It would just have more commands than a regular logic block and less restrictions.

**Comment by the-red-soul** [comment]
im against this idea because it can easily lead to overabuse, and if one of these was on a playable team then it would be editable and cause all sorts of issues, not to mention i bet it would be a bitch to code since its all these new logic applications for ONE block

**Comment by TranquillyUnpleasant** [comment]
> im against this idea because it can easily lead to overabuse, and if one of these was on a playable team then it would be editable and cause all sorts of issues, not to mention i bet it would be a bitch to code since its all these new logic applications for ONE block

Well the issue of it being abusable is the entire point of the block, its essentially dev mode in block form, of course if you give players access to it within a normal map its going to be a train wreck.
As far as being a lot of effort to code for one block, yes it would be, but from the different amount applications it has it could be worth the effort.

**Comment by NoExit4U** [comment]
> im against this idea because it can easily lead to overabuse, and if one of these was on a playable team then it would be editable and cause all sorts of issues, not to mention i bet it would be a bitch to code since its all these new logic applications for ONE block

Good map makers will be capable to make maps where this new block can not be abused. Or at least be warned that people are abusing this block and then fix it.

I agree that it's a relative big chunk of code, but the Logic Processors are already here so a large portion to make this work already exists.

Also it's possible that an initial version comes out with only a couple of new commands. Then if it is popular and people ask for more then more commands can be implemented.

And as TranquillyUnpleasant already said, it has a lot of potential.

**Comment by Weathercold** [comment]
> im against this idea because it can easily lead to overabuse, and if one of these was on a playable team then it would be editable and cause all sorts of issues

Servers of course have the option to ban this block. And if a server needs to use it, I imagine there will be a command that can lock the modifiability of a block.

> not to mention i bet it would be a bitch to code since its all these new logic applications for ONE block

I think it’s worth it because it’s useful.
