### ISSUE TITLE
Purple logic beams like energy network

### ISSUE THREAD

**Issue by Polpo002** [Anuken/Mindustry-Suggestions#2217]
I'd like to have some kind of logic network beams, same as energy beams. they could connect the processors to the blocks they are linked with and you could have an opacity slider exactly like for the energy ones. there might be also a way to include units in this but I don't know how useful it would be.

this would look nice and help to organise.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nichrosia** [comment]
Having a setting for this would definitely look cool, however due to it being a graphical only feature it would probably have a low priority

**Comment by nichrosia** [comment]
![image](https://user-images.githubusercontent.com/57579569/112867925-14dada00-9081-11eb-9e23-fd4d4954b23b.png)
In game screenshot

**Comment by nichrosia** [comment]
```js
function logicLasers() {
	Groups.build.each(b => {
		if (b.block.class.getSuperclass() == LogicBlock) {
			b.links.each(l => {
				let linkBuild = Vars.world.tile(l.x, l.y).build;
				
				if (linkBuild != null) {
					let linkAngle = b.angleTo(linkBuild);
					let blockAngle = linkBuild.angleTo(b);
					
					let blockOffset = new Vec2;
					blockOffset.trns(linkAngle, 3 * b.block.size);
					let linkOffset = new Vec2;
					linkOffset.trns(blockAngle, 3 * linkBuild.block.size);
					
					Draw.z(Layer.power);
					Draw.color(Color.valueOf("a794e3"));
					Lines.stroke(1);
					Drawf.laser(b.team, Core.atlas.find("laser"), Core.atlas.find("laser-end"), b.x + blockOffset.x, b.y + blockOffset.y, linkBuild.x + linkOffset.x, linkBuild.y + linkOffset.y, linkAngle, 0.3);
				}
			});
		}
	});
};

logicLaserEffect = new Effect(10, e => {
	logicLasers();
});

Events.run(Trigger.update, () => {logicLaserEffect.at(Vars.player.x, Vars.player.y)});
```
Updated code.

**Comment by nichrosia** [comment]
![Uploading image.png…]()

**Comment by nichrosia** [comment]
![image](https://user-images.githubusercontent.com/57579569/112870952-65076b80-9084-11eb-874e-3e7ec6a6f108.png)

**Comment by nichrosia** [comment]
If you want this @Polpo002, here's [the mod](https://github.com/nichrosia/logic-block-lasers)

**Comment by nichrosia** [comment]
Hmm. For some reason it isn't multiplayer compatible.

**Comment by nichrosia** [comment]
Commiting a fix to the repo now.

**Comment by Polpo002** [comment]
wow thanks
that was fast

**Comment by nichrosia** [comment]
It has been updated further, now has settings for it. Also has a fix for displaying inactive links, which is now disabled by default.

**Comment by Humanoid-X** [comment]
Wow...

**Comment by Humanoid-X** [comment]
Good work @nichrosia !

**Comment by Bohaska** [comment]
Maybe try to PR it. If it gets rejected then we stick to the mod...

**Comment by stuffyAI** [comment]
PR it with the option to toggle it off, I don't want to get autism looking at my base

**Comment by Bohaska** [comment]
I usually would put a link to an article saying about why you can't get autism, but I'm lazy

**Comment by stuffyAI** [comment]
> I usually would put a link to an article saying why you can't get autism, but I'm lazy

I know, I already have autism and just wanted to point out that it would get better
