### ISSUE TITLE
Option to display production rates instead of production times for all buildings

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2218]
I'd like an option to display production rates (Ex: 1.5 items/sec) instead of production times (Ex: 0.66 sec) in the information windows for all buildings. It would make it easier to determine how many of the building is needed to produce a full belt of a resource. Drills already display their production rates, so I don't see any reason why other buildings shouldn't do the same.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Something like this: https://github.com/Anuken/Mindustry/pull/3213

**Comment by BenMan95** [comment]
Yeah, pretty much

**Comment by Jammo2000** [comment]
I had the idea of putting a toggle in the info screen that changes between the 2 views. It would be a lot cleaner displaying one at a time. IMO the default should be rates, but that's debatable.
