### ISSUE TITLE
Better Attack Map Design

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#2219]
**Describe what you would like changed, and why.**
The current state of attack maps isn't great right now, as all the strategies to beat them have one thing in common: Completely disregard any of the buildings in the middle of the map, and focus on the core(s). I propose that the core should be slightly less defended, but a lot of the strength of the base should be in between the cores, so the base feels like you are fighting through it, instead of going around it.

**Describe the changes you want to propose. Include possible alternatives.**
Buff the buildings in between the cores to have better turrets and to span the map better, forcing the player to go through them. Also, nerf the enemy cores to compensate. Additionally, use swarmers and hails. I can't remember the last time an attack map had a swarmer in it. same goes for cyclones. Zenith bombing is much harder if you have to fly over a cyclone...

**Comment by itcannotbe** [comment]
Wasn't already a suggestion regarding attack maps?

**Comment by ShadeStrike62** [comment]
> Wasn't already a suggestion regarding attack maps?

not specifically to the content in them, i believe it was to improve the schematic quality. I'm talking about a generic buff the the difficulty of the buildings so they are relevant...

**Comment by itcannotbe** [comment]
Artificially making enemy stronger or weaker than what the player has even if they're the same block is a shitty game design.

Plus the fact that attack maps aren't supposed to behave like real players doing PvP because that kind of behavior is unattainable.
