### ISSUE TITLE
Day/Night sycle | Solar panel buff

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#222]
**Describe the content or mechanics you are proposing.**
•Perhaps a **day/night** cycle which may already be added soon
•a balancing feature for it

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Will make the game more cinematic and give you the feeling your all alone and the classic mindustry feeling with night. Also night would make solar panels useless as they wont generate power but when its day they will generate **3×** what they generate now

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
If you say that it may be implemented, why don't you just check the god damn trello?

**Comment by Anuken** [comment]
This was already implemented.
