### ISSUE TITLE
slightly nicer tooltip for factories

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#2220]
**Describe the content or mechanics you are proposing.**
Currently:
![image](https://user-images.githubusercontent.com/45698812/112932601-09b09a00-90d3-11eb-8897-a95a109e704d.png)
Suggestion:
![Screenshot 2021-03-29 211012](https://user-images.githubusercontent.com/45698812/112932668-2a78ef80-90d3-11eb-9035-3887eab15e4e.jpg)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Maybe it's a little bloaty but I think it would be nice.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. *(maybe it falls under complete ui redesign?)*
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

?

**Comment by Fipico2** [comment]
Kinda useless tbh. You already have to have the unit unlocked so you know whats coming out no matter your skill level
