### ISSUE TITLE
Hard mode

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2222]
**Describe the content or mechanics you are proposing.**
Harder campaign mode. Compeltely optional, you dont need to play like that.
It changes:
2x enemy damage
Core ships cant shoot
-10s wave timer
Attacks happen more often
Enemy weapons apply deadly status effects (those that already do have x2 power)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I have beaten the campaign quite easily, I am for more of a challenge. This should do it. If you dont want to add any of the said features, dont, just add what you think will make the game reasonably hard.

**Alternative**
Settings for camp just like for custom maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I am starting to doubt if people actually read before putting in the X in

>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
