### ISSUE TITLE
Mods breaking in new update, including RTFM.

### ISSUE THREAD

**Issue by IVV-NCX** [Anuken/Mindustry-Suggestions#2224]
**Describe what you would like changed, and why.**

Fix the new update, it appears to have a bug that causes the last mod you have downloaded to break. This includes RTFM, a mod which adds a set of manuals. 

**Describe the changes you want to propose. Include possible alternatives.**

Fix the bugs.

**Comment by DeltaNedas** [comment]
1. do you think this the bug tracker
2. "the bugs"?

**Comment by BlueWolf3682** [comment]
![Screenshot_20210330-115457](https://user-images.githubusercontent.com/61173114/113033946-cac02a00-914e-11eb-9fae-a61f62f37fa2.png)
\*visible confusion*

**Comment by the-kido** [comment]
I'd like to know how you thought this place is where you report bugs rather than the channel that's called "bugs". Honestly, I'm curious.

**Comment by BlueWolf3682** [comment]
afaik the mods do not break, they are entirely functional to me

**Comment by IVV-NCX** [comment]
> I'd like to know how you thought this place is where you report bugs rather than the channel that's called "bugs". Honestly, I'm curious.
> 
> RTFM also works for me on 126.2 so idk what you're talking about

I didn't know.

**Comment by IVV-NCX** [comment]
> afaik the mods do not break, they are entirely functional to me

I've been testing for over an hour now, seems that Vanilla Enhanced works, but not Routerio and RTFM now.

**Comment by BlueWolf3682** [comment]
Whats your device?

**Comment by IVV-NCX** [comment]
> Whats your device?

Windows.

**Comment by IVV-NCX** [comment]
Please close this. I think I can close by commenting.

**Comment by DeltaNedas** [comment]
https://github.com/deltanedas/rtfm/issues
https://github.com/deltanedas/routorio/issues

this is not the bug tracker for either mod or mindustry

**Comment by BlueWolf3682** [comment]
VanillaEnhanced is a JSON only mod by the way
