### ISSUE TITLE
Sharing resources 

### ISSUE THREAD

**Issue by AzamatUmirzakov** [Anuken/Mindustry-Suggestions#2225]
**Describe the content or mechanics you are proposing.**

I would like to be able to share resources between sectors 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

In previous versions, you couldn't save your sectors, and they were erased when you launched the core. So I could leave sector without titanium, and then launch there again, with some titanium to create titanium farm. But in this version sectors are kept, so I can't re-enter sector with needed resources. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [, ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented  in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
You are not:

> ...familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

The [launchpad](https://mindustrygame.github.io/wiki/blocks/227-launch-pad/) is unlocked by capturing Extraction Outpost.

**Comment by AzamatUmirzakov** [comment]
> You are not:
> 
> > ...familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 
> The [launchpad](https://mindustrygame.github.io/wiki/blocks/227-launch-pad/) is unlocked by capturing Extraction Outpost.
> 
> Please close this suggestion as the content you are suggesting is already in the game.

It's not what I meant, I meant like when you are in sector without titanium, and you could take some titanium from near sectors that you have already captured.

**Comment by itcannotbe** [comment]
> > You are not:
> > > ...familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> > 
> > 
> > The [launchpad](https://mindustrygame.github.io/wiki/blocks/227-launch-pad/) is unlocked by capturing Extraction Outpost.
> > Please close this suggestion as the content you are suggesting is already in the game.
> 
> It's not what I meant, I meant like when you are in sector without titanium, and you could take some titanium from near sectors that you have already captured.

And the launch pad does that.

There is a reason the mechanic is locked behind extraction outpost.

BECAUSE YOUR NOT MEANT TO HAVE IT EARLY IN THE GAME.

If you're struggling to finish some sectors, think your way through it, not ask to make it easier for you. A lot of people already completed the tech tree and you're just making excuses for yourself.

**Comment by itcannotbe** [comment]
You can always die and re-launch to the sector, but.why would you launch in the first place if you haven't bought im what you needed.

**Comment by AzamatUmirzakov** [comment]
> > > You are not:
> > > > ...familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> > > 
> > > 
> > > The [launchpad](https://mindustrygame.github.io/wiki/blocks/227-launch-pad/) is unlocked by capturing Extraction Outpost.
> > > Please close this suggestion as the content you are suggesting is already in the game.
> > 
> > It's not what I meant, I meant like when you are in sector without titanium, and you could take some titanium from near sectors that you have already captured.
> 
> And the launch pad does that.
> 
> There is a reason the mechanic is locked behind extraction outpost.
> 
> ### BECAUSE YOU'RE NOT MEANT TO HAVE IT EARLY IN THE GAME.
> 
> If you're struggling to finish some sectors, think your way through it, not ask to make it easier for you. A lot of people already completed the tech tree and you're just making excuses for yourself.

Ok, closing
