### ISSUE TITLE
weather does not cover the full screen with low UI scale

### ISSUE THREAD

**Issue by Polpo002** [Anuken/Mindustry-Suggestions#2226]
![WhatsApp Image 2021-03-31 at 10 05 09](https://user-images.githubusercontent.com/81574707/113112105-1f27e000-9209-11eb-8d7e-12f694bd9513.jpeg)
**Describe what you would like changed, and why.**
(This is with UI scale 75%) idk i thought that could be fixed

**Comment by itcannotbe** [comment]
But this isn't the place where you report bugs.

**Comment by Polpo002** [comment]
this is not a bug

**Comment by Newguy-ish** [comment]
nah it does count as one, go to the bug report issues
