### ISSUE TITLE
Manual Labor

### ISSUE THREAD

**Issue by 02Oxygen** [Anuken/Mindustry-Suggestions#2227]
**Describe the content or mechanics you are proposing.**

Controlling units into constructors

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes when you finish building something with your unit like a T3 Constructor you need to repeat a process of building the unit again i would like to make so that there is a button for us to slide our current unit in the constructor and upgrade it so we don't waste too much resources

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
* Horribly irrelevant title
* Duplicate of #620

**Comment by the-kido** [comment]
sad "[]" noises

**Comment by octopuscaat** [comment]
use conveyors and/or unloaders. EZ
