### ISSUE TITLE
insecure js mods

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry-Suggestions#2228]
**Describe the content or mechanics you are proposing.**

An option in the mod.json that removes the js blacklist for that mod and warns the user before installing, just like the "jar mods are insecure" dialog.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

More modding abilities in js modding

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sk7725** [comment]
~~Just do java~~

**Comment by sk7725** [comment]
Also, the majority of mods are js mods, and that the majority of mods are secure is always a good thing.
Not to add that stuff in the blacklist are not necessary to make mods, according to Qmelz.
![Screenshot_20210401-064843_Discord](https://user-images.githubusercontent.com/58885089/113215932-92d3f680-92b6-11eb-898f-86ba5d90f8af.jpg)

**Comment by Kyllingene** [comment]
So allow mod makers to make potential viruses, the only warning about which is an obscure screen that many people will simply skip, with relative ease? Even the installation process for jar mods is harder, so evidently Anuke did not think it wise to make insecure mods easy to download. Also, why exactly do you need access to such things?

**Comment by QmelZ** [comment]
> ~Just do java~

yes, actually. i did

> stuff in the blacklist are not necessary

yes, i dont see anyone saying "they are necessary" anywhere

> installation process for jar mods is harder

no, it's the same one click install from the mod browser, no difference in difficulty

> why exactly do you need access to such things?

i dont *need* them, this is a suggestion, it's not about "need", it's about "want"

**Comment by Kyllingene** [comment]
> i dont need them, this is a suggestion, it's not about "need", it's about "want"

For what reason, though? Is there anything that you are trying to do, but unable? Is there any reason to make JS mods less safe? A slight increase in convenience does not qualify in my opinion, so what else could there be?

**Comment by QmelZ** [comment]
yes the slight increase in the possibilities really isn't my exact point here, it would be more fun and testing would be easier this way. also no mods become less safe here unless the modder specifies it and there is no reason to only stick with a basic "yes i understand that it's dangerous let me install it" dialog.

**Comment by Kyllingene** [comment]
Then what other dialog? Either you make testing harder by making it harder to install a mod, or you make js viruses possible just so that you can have "more fun".

**Comment by sk7725** [comment]
Having an extra step - the "blacklisn't" java mod as a dependency - sounds good enough so naive users would not be affected by malware.
1. It uses mod.json - just as you requested - for removal of the blacklist
2. It is significantly harder for the client - but just downloading another mod, users who do not understand what dependencys are should not have access into blacklisn't js mods anyways (since they may not know what they are getting themselves into, making it easy prey for potential malware mods)

**Comment by sk7725** [comment]
So yeah, you already have what you want.

**Comment by QmelZ** [comment]
> you make testing harder by making it harder to install a mod

you dont install testing mods

> you make js viruses possible

js viruses already are possible

> Having an extra step - the "blacklisn't" java mod as a dependency - sounds good enough

if only the mod was good enough to work

> It uses mod.json 

that's not the point

> It is significantly harder for the client

i don't see how installing 2 mods instead of 1 is "significantly harder"

> you already have what you want

not really

**Comment by sample-text-here** [comment]
>  the only warning about which is an obscure screen that many people will simply skip? 

keep in mind java mods use the same method

**Comment by G0nTar** [comment]
I don't know Why someone would argue against making it safer for everybody who supports Anuken's game Mindustry, without even adding any decent excuse on their response.

Its about making kyt safer for the mayority of the users who supported by buying and downloading his game.

Literally, in essence it's like making a toy for people, and letting nasty middleman tamper with your product in a "harmful way" at the expense of the poor people who support your creation in the first place.

 Calling to common sence here, if there's a way for people to use Anuken's work to do harm, it would be enough of a reason to protect who supports anuken in the first place, no excuses

**Comment by DeltaNedas** [comment]
largest problem with this is that a mod can click the ok button in the insecure dialog, thus removing any security whatsoever.
if you really want to make a virus write it in java.

**Comment by QmelZ** [comment]
> largest problem with this is that a mod can click the ok button in the insecure dialog

yes these are all existing problems with java mods, i dont see any valid point why js mods shouldnt be insecure optionally. though making that dialog inaccessible is a good idea

> if you really want to make a virus write it in java.

this isn't related to making viruses and i dont like java

**Comment by sk7725** [comment]
> i don't see how installing 2 mods instead of 1 is "significantly harder"

I shall summon @MEEPofFaith to testify how adding the multi-lib as a dependency gave him pain because people are not as intelligent as you would expect

**Comment by QmelZ** [comment]
i can still make one mod install the other, the user doesn't need to do anything

**Comment by G0nTar** [comment]
Any kind of protection for users and supporters, should be built-in into Mindustry itself, or self installing/activated, since there's a huge population of players who won't bother with that kind of stuff since they just have no clue how to do anything but "Play the game".

**Comment by sample-text-here** [comment]
this would add basically no extra vulnerabilities to the game
this just lets js mods use java features
both java and (insecure) js mods would have a warning before installing
if people choose to ignore java mod warnings they're putting themselves in danger anyway
i don't see any problem with this, i think this is a great idea

**Comment by itcannotbe** [comment]
Why not just make Java mods instead of trying to use Java features in JS?

**Comment by QmelZ** [comment]
> Why not just make Java mods instead of trying to use Java features in JS?

i already answered this. i don't like writing java, and this is not "trying to use java features in js"
