### ISSUE TITLE
Nerf foreshadow because op

### ISSUE THREAD

**Issue by ujebc** [Anuken/Mindustry-Suggestions#2231]
**Describe what you would like changed, and why.**
Foreshadow too op, T4 expensive but get hit by foreshadow 5 times and fucking dies, it's unfair, you need like only 5 surge to kill T4 and 20 surge to kill T5, foreshadow is broken, need fix

**Describe the changes you want to propose. Include possible alternatives.**
Make foreshadow take 4% unit health

**Comment by MrDuck557** [comment]
1. it takes 4 surge per shot, and power as well. (20 surge for T4 and 80 surge for T5)
2. foreshadow gets overwhelmed by groups, it's single target and slow reload. One shot per 3 seconds
3. a nerf to unit damage would break the design of the foreshadow

**Comment by ujebc** [comment]
Didn't look at the 4 surge/shot but

> 2. foreshadow gets overwhelmed by groups, it's single target and slow reload. One shot per 3 seconds

Easily patched by just placing some cyclone

> 3. a nerf to unit damage would break the design of the foreshadow

1% building health could replace it

**Comment by stoneRdev** [comment]
@ujebc 

> Easily patched by just placing some cyclone
So, then wouldn't cyclone be op then? I mean this whole foreshadow thing can easily be avoided if you send units on one side of it then command some other units to the other side, where its just sitting until it cools off.

> 1% building health could replace it
1% of the foreshadows health is 24. which is 3 shots from a duo fed by copper. Not much.

I honestly think that the foreshadow is fine. There's strategies around them and ways to deal with things protecting them. It is a strategy game after all. 

Also, 1 shot every 3 1/2 seconds is pretty slow. Zerg that f***er

**Comment by ujebc** [comment]
> So, then wouldn't cyclone be op then? I mean this whole foreshadow thing can easily be avoided if you send units on one side of it then command some other units to the other side, where its just sitting until it cools off.

4% unit damage would make foreshadow actually has a weakness against low tier units, foreshadow can easily one shot a zenith with 4 surge, zenith needs 130 silicon, 80 titanium, and 40 metaglass

But if the 4% unit damage applied, foreshadow would take 100 surge, which is quite balanced because it's efficient against high tier units and actually useless against low tier units

> 1% of the foreshadows health is 24. which is 3 shots from a duo fed by copper. Not much.

That's the point, you should use foreshadow to attack buildings

**Comment by stoneRdev** [comment]
I'm a little confused by what your saying

I understand that a foreshadow can one hit most things, but I do not understand how changing the damage against units would balance anything. 4% unit damage means high tier units as well, meaning it would be pretty much useless unless you feel like running a line of surge and putting an expensive turret right up to your enemy's door.

I personally don't use any turrets for attacking bases, I have units for that. So an adjustment like you suggest would ruin foreshadows for me (and presumably anyone else using them in the same fashion). Especially when there's balanced ways of taking out foreshadows already in place. 
Grab an oct, pick up a reign, command some horizons. Send in a bunch of flares, and take your little Oct Squad to the other side, drop your reign while the foreshadow is cooling off, and use your oct to protect your reign. Foreshadows gone in seconds, and you will still have enough units/momentum to take a sizable chunk of the base with it. 
Idk man, to each their own strategy, but this suggestion would negatively affect my gameplay and I'm against it.

**Comment by HTMLPhoton** [comment]
currently the MP big-server meta seems to be build a ton of zeniths and rush the enemy base. in this situation foreshadow is useless. t4 or t5 units are almost never built in pvp due to the amount of coordination needed to build one (and if they do get built, they are never actually a threat due to the coordination needed to use one)

**Comment by XenonLog01** [comment]
Foreshadows are fine the way they are. Their power is limited to one target at a time, and once ~ every 3 seconds. This is more than an effective debuff, and this shows in the way they are used. Also, methods for dealing with them are pretty easy, so attack maps while attacking with turrets is easy. No change is needed to them.
