### ISSUE TITLE
units, and interesting gameplay and more

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#2233]
**Describe the content or mechanics you are proposing.**

the entire planet has 1 (and a half?) main water levels, and so you should make another planet mainly about water levels. also, there is only 1 water unit tree. i think you should put a unit that can go in water and on land. also, a unit with a phisical sheild with lots and lots of health that blocks all attacks would be cool. altho when it breaks it breaks. mighe be cool if there was a way to get it back. it would be nice if on each planet you have to place a planet launcher on specific places on the planet.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

the place has few water levels and water levels are fun. the fact that there are few water make the gameplay less engaging. a unit that could go in water and on land wold be uniqe and cool. is cool. haveing  launch point that is requared on a zone would make it so players that unlockd the planet launcher cant simply capture the first area then build a new one, pretty much skiping thr planet. it would be cool if there were small optianl planets.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

hey, by the way, what did you use to make the graphics for this game? i really like it.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Here before anyone says "mods" >:D

**Comment by octopuscaat** [comment]
what?

**Comment by PickAPlayerNameFirst** [comment]
Lol just download MODS. It will unlock more planets and resources. And about planets, just wait for the interplanetary colonization (v7) update. Check it out on Trello.

**Comment by PickAPlayerNameFirst** [comment]
Also,  you commented here without checking Trello (future updates for mindustry) (basically what Anuke is doing rn)?

**Comment by Kyllingene** [comment]
> also, there is only 1 water unit tree. i think you should put a unit that can go in water and on land. also, a unit with a phisical sheild with lots and lots of health that blocks all attacks would be cool. altho when it breaks it breaks

> a unit that could go in water and on land wold be uniqe and cool

1. please keep your ideas to 1 idea per issue
2. more water units are already planned
3. a water and land unit would just become the new spam unit
3. more water levels have already been suggested
4. look at [the repo for mindustry](https://github.com/Anuken/Mindustry) to see what he used

**Comment by octopuscaat** [comment]
i see. thank you.
