### ISSUE TITLE
a bug happend that lost almost all my data :(

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#2234]
**Describe what you would like changed, and why.**
i got on one day and ALL of my sectors that i captured were under attack! EVEN GROUND ZERO. also my _entire_ tech tree was reset and all of the resources i had were gone.

i have screenshots but i dont know how to submit them with this
**Describe the changes you want to propose. Include possible alternatives.**
fix it!

**Comment by itcannotbe** [comment]
### THIS ISN'T THE BUG TRACKER -_-

### THERE IS A LINK IN GAME FOR THE PLACE WHERE YOU REPORT BUGS. USE THAT INSTEAD.

**Comment by itcannotbe** [comment]
### THIS ISN'T THE BUG TRACKER -_-

### THERE IS A LINK IN GAME FOR THE PLACE WHERE YOU REPORT BUGS. USE THAT INSTEAD.

**Comment by IVV-NCX** [comment]
This is suggestions, not bugs. BTW, stable or unstable build, and check your save files.

**Comment by octopuscaat** [comment]
i did not know that... 
oops.

**Comment by itcannotbe** [comment]
Care to close this issue?
