### ISSUE TITLE
Buildable floors in modes other than the Editor

### ISSUE THREAD

**Issue by SuperHappyPenguin** [Anuken/Mindustry-Suggestions#2235]
**Describe the content or mechanics you are proposing.**
       I would like to suggest the ability to build floors, such as the metal floors and dark panels found in the editor. 
       These floors will function the same way mostly as they currently do in-game, with the exception of being able to dismantle them. 
       Dismantling any floor will refund 50% of the floors cost, and revert the floor back to whatever 'natural' floor it was prior to being built on top. (Unfortunately, this would require the manufactured floors that are in the ruins that are present on arrival of some sectors, as well as manufactured floors placed in the editor, require two layers of floor: one manufactured, one natural.) 
       Floors will not be able to be placed on liquid tiles (i.e. water, oil, slag).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
       I believe that this content will improve the game by allowing many more options for decoration, as well as allowing players to mark areas for strategic uses (such as building a line of striped floors to show where the orbital drop kill zone is to prevent yourself from accidently building there between attacks, or building floors to mark the range of a turret so that you know precisely when an enemy walks into your range when controlling said turret.)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why do even need to mark them?
Just leave a message block or plop a schematic even if it's unfinished.

**Comment by octopuscaat** [comment]
that cant be. it would be op. some building get a bonus if there are placed on certan floors. it would mean basicly infinate power with thermal generator. its also not a good idea because you would have to put it in the tech tree and that would look weird and there is the issue of what is needed to build it. i doesent benifit the gameplay or anything. plus, you can do that in editor anyway.

**Comment by genNAowl** [comment]
Depending on what floors can be built, this can easily be almost useless or completely broken. 

And the powers to modify the map In-game is not even in the editor, so support for this would be interesting, to say the least.

**Comment by SuperHappyPenguin** [comment]
Sorry, I must have explained it poorly. 
To iterate, this would allow the player to build the floors that are labeled as "dark panel" or "metal floor" in the editor, as to not provide any tile-based bonuses to buildings. I mainly intend it to be used as a tool to mark certain areas on the map in a way that would not be targeted by enemies (such as message blocks) or require the player to turn off building when near (such as schematics.) As for it's place in the tech tree, I believe that placing it either next to (or perhaps above) copper walls would work best.

**Comment by Kyllingene** [comment]
But... but... multiple tile layers though... why? And think of the maps this would break, both campaign and custom! Such a pain to code for so little benefit!
