### ISSUE TITLE
Planet map: have the "i" information for a sector displayed on the side with a mouse hover over the sector.

### ISSUE THREAD

**Issue by Shagsright** [Anuken/Mindustry-Suggestions#2236]
**Describe the content or mechanics you are proposing.**

Planet map: have the "i" information for a sector displayed on the side with a mouse hover over the sector. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would reduce the number of clicks to find sectors that have a good amount of export and could possibly tell you which sector the export is going to so you do not have to go into the sector to see. It would be nice to be able to assign the sector for the export from the planet map also. I'm not a game designer, I don't know if this is one of those things that adds to the game but it is very frustrating when you take over half the planet and all the sectors look alike and you have to go into them, to see where the export is going and change it.

Like this or something: 
![tempsnip](https://user-images.githubusercontent.com/81374927/113376604-171e8c00-9340-11eb-9529-2e7e489bb1dc.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Something tells me this wouldn't work very well for phones

**Comment by Humanoid-X** [comment]
:angry_mobile_users_noise:

**Comment by Kyllingene** [comment]
> all the sectors look alike

That particular sub-problem is fixable with sector icons.

**Comment by G0nTar** [comment]
+1 helpful info display, when playing Multiplayer with friends, it's really a pain in the arse to drag them all from their actual projects, stop everyone of what they are doing, just to check if a sector is exporting, or just to make a bunch of Sector export to your location 1 by 1.

An "export to actual sector" kind of button would be amazing to re-route everything to where you ar actually located! :)
