### ISSUE TITLE
Shield v 1.1

### ISSUE THREAD

**Issue by Ghoust-antibug** [Anuken/Mindustry-Suggestions#2237]
1.0 Draw on all units with shields, a shield generator (in the middle of the unit)

1.1visual

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dioo0** [comment]
what if they have this generator inside?

**Comment by Ghoust-antibug** [comment]
> what if they have this generator inside?

So not interesting

**Comment by Kyllingene** [comment]
So just add an insignificant detail that would either be nothing or a pain to code, for what reason again?

**Comment by Bohaska** [comment]
In the nice to have but super hard to code list
