### ISSUE TITLE
corvus

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry-Suggestions#2238]
**Describe what you would like changed, and why.**

i would appreciate a ability to stick plastanium in shields, in a method that acts like a normal shield but resists green lasers currently theres no way to counter 7 corvuses, besides spamming plast walls, even if you have a 2 layer mender wall, corvus can outrange foreshadows, hence you either need to decrease corvus range, or add plastanium shields for further resistance to corvus beams.

**Describe the changes you want to propose. Include possible alternatives.**
plastanium shield/ corvus range nerf

**Comment by BlueWolf3682** [comment]
youre not supposed to survive 7 of any t5.

**Comment by bendnuts** [comment]
> youre not supposed to survive 7 of any t5.

why the fuck not.

**Comment by BlueWolf3682** [comment]
because no. If you have issues with corvuses, get multiple layers of plastanium walls

**Comment by bendnuts** [comment]
the problem is, even this
![Uploading Screenshot_20210212_090425.png…]() 
cant withstand a few corvusses,....

**Comment by itcannotbe** [comment]
But I can survive 20 octs, what's the problem?

Provided that it's just octs...

**Comment by bendnuts** [comment]
> because no. If you have issues with corvuses, get multiple layers of plastanium walls

as i said, corvuses outrange foreshadow with plast walls...

**Comment by bendnuts** [comment]
> because no. If you have issues with corvuses, get multiple layers of plastanium walls

foreshadow can not kill corvus when corvus is long range-sniping, and being carefull

**Comment by bendnuts** [comment]
annnd mends

**Comment by Catchears** [comment]
> because no. If you have issues with corvuses, get multiple layers of plastanium walls

but isn't is called corvi?

**Comment by BlueWolf3682** [comment]
dingus

**Comment by sample-text-here** [comment]
~~spam more plast~~

**Comment by ShadeStrike62** [comment]
> > because no. If you have issues with corvuses, get multiple layers of plastanium walls
> 
> as i said, corvuses outrange foreshadow with plast walls...

This is untrue:
![image](https://user-images.githubusercontent.com/54792255/113628454-43236f80-96a8-11eb-8e33-6e85fb6a1434.png)
![image](https://user-images.githubusercontent.com/54792255/113628494-4fa7c800-96a8-11eb-9e32-e9ecddd92706.png)

**Comment by G0nTar** [comment]
There's a current chain of issues opened asking to nerf all units and to boost a bunch of resources in ways that don't make any sence that I can't kite comprehend till now.

People, if you want to play base building Sim city like, go for campaign / coop.

PvP is not about being a turtle with turrets, it's about destroying the enemy core.

If you want a PvP game that plays for 3+hs where you Just win by making the other players bed time come first so they quit, then I think we disagree in the meaning of Having "FUN" playing games...

**Comment by itcannotbe** [comment]
> There's a current chain of issues opened asking to nerf all units and to boost a bunch of resources in ways that don't make any sence that I can't kite comprehend till now.
> 
> People, if you want to play base building Sim city like, go for campaign / coop.
> 
> PvP is not about being a turtle with turrets, it's about destroying the enemy core.
> 
> If you want a PvP game that plays for 3+ hours sitting building a wall, where you Just win by making the other players bed time come first so they quit, then I think we disagree in the meaning of Having "FUN" playing games...

We could probably make games quicker if we bring back dag rush by changing the unit limit from a per unit type to a starcraft like unit cap.
Games we're your playing for 3 hours could be down to less than 10 minutes if we bring it back.

Also T3 should already be game ending TBH. But people want turtles apparently.

**Comment by stuffyAI** [comment]
So let's talk about how the caption says corvus,
the first paragraph is about sticking plastanium to shields to make them resilient to pierce,
the second paragraph includes corvus nerf.

If you really wanted to have your suggestion implemented, wouldn't you try to write a coherent text with key points leading up to the change?

**Comment by ShadeStrike62** [comment]
> So let's talk about how the caption says corvus,
> the first paragraph is about sticking plastanium to shields to make them resilient to pierce,
> the second paragraph includes corvus nerf.
> 
> If you really wanted to have your suggestion implemented, wouldn't you try to write a coherent text with key points leading up to the change?

I agree, in my personal opinion corvus needs a damage nerf, but then a fire rate buff, and a removal of the slow effect when it fires. That way, it isn't the most cheesy T5 when you factor in alpha/beta/gamma baiting (flying in circles to abuse its target priority), and will make it better at shooting in general, but with a small damage nerf to compensate...

**Comment by HTMLPhoton** [comment]
Corvus is a T5, which means you're worring less about the enemy using advanced tricks to sabotage it and more about Mr NoobMcNoob camping at the tetrative reconstructor, getting in the thing first, then walking headfirst into the enemy Mr NoobMcNoob's foreshadow spam.

There's almost always going to be somebody controlling the corvus, since you can control 9 t5s per player and it doesn't hurt to get in a bit closer to have the corvuses at the back of the formation in range.

**Comment by 00001H** [comment]
Get 7 corvuses yourself!!!

**Comment by 00001H** [comment]
> Get 7 corvuses yourself!!!

or corvi, whatever

**Comment by bend-n** [comment]
> > > because no. If you have issues with corvuses, get multiple layers of plastanium walls
> > 
> > 
> > as i said, corvuses outrange foreshadow with plast walls...
> 
> This is untrue (see overly large images, thanks github), and also, I would direct you towards this arguement. Not many things in mindustry can survive 7 cluster munitions from 7 toxpids at the same times, nor can maybe things tanks shots from 7 reigns. I think you are also overlooking the ability for polys to rebuild the walls quickly between shots, as well as the fact that if for some reason you are fighting 7 corvi, then you can probably afford 20-30 foreshadows... ![image](https://user-images.githubusercontent.com/54792255/113628454-43236f80-96a8-11eb-8e33-6e85fb6a1434.png) ![image](https://user-images.githubusercontent.com/54792255/113628494-4fa7c800-96a8-11eb-9e32-e9ecddd92706.png)

62.5 - 3.5 = 59

Thats not even 2 big walls.. or one big wall and a mender.
