### ISSUE TITLE
Cryofluid Processor

### ISSUE THREAD

**Issue by PickAPlayerNameFirst** [Anuken/Mindustry-Suggestions#2239]
**Describe the content or mechanics you are proposing.**
A T2 Cryoflluid Mixer
Health: 650
Dimensions: 4x4
Build Time: 9.50 seconds
Build Cost: Titanium x300, Metaglass x200, Surge Alloy x100
Power Use: 300 power units/s
Liquid Capacity: 20 liquid units
Input: 6 Titanium, 60/s Water
Output: 50/s Cryofluid 
Production Time: 2 seconds

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think this would improve how T4 and T5 factories will spend less space to cover and build units. This could help the cryofluid recover from the nerf that it's the only one liquid that has no corresponding tile to extract.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
When you realized that someone already suggested a Tier 2 cryofluid mixer.

So basically this is actually a duplicate.

**Comment by itcannotbe** [comment]
#1097 be like......

**Comment by PickAPlayerNameFirst** [comment]
Welp mine is detailed...

**Comment by PickAPlayerNameFirst** [comment]
And sorry I don't have the time to do issue debunk... I am completely new to this, but mindustry discord teached me how to do it

**Comment by PickAPlayerNameFirst** [comment]
And see duplicate means a 'real copy of the idea' and not a 'similarity of ideas, have a better and faster cryomixer but needs more resources.

**Comment by itcannotbe** [comment]
Don't look at me, I'm not the guy who placed x in

>  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
This has been already suggested. It doesn't matter if the implementation is different, but the idea is the same.

**Comment by Kyllingene** [comment]
Can someone please explain why this issue got reopened so many times?

**Comment by RedstonerKBC** [comment]
I don't think this is necessary (yet. If v7 adds more things that are cryo-hungry then maybe.). The only reason why T2 graphite and silicon makers exist is because those are used in almost everything. Cryofluid is only used for cooling weapons (even then it's optional) and for units. I know the reconstructors drink it like a teenager addicted to soda but you can easily build lots of T1 cryos and store them in tons of tanks.

**Comment by joshuaptfan** [comment]
T4/T5 units are _supposed to be_ difficult/painful to produce. A new block that makes it easy would defeat the purpose of such balancing.

**Comment by PickAPlayerNameFirst** [comment]
Ok, closing. Thanks for the APPROPRIATE information.
