### ISSUE TITLE
Some interresting features

### ISSUE THREAD

**Issue by sova-kostyan** [Anuken/Mindustry-Suggestions#224]
• Mechs can turn into buildings and with little efficiency mine or produce something, consuming the energy generated by the Allied ships (other players), which, if they are connected to the network and give energy to it, cannot move and shoot. Mech in building mode is an electrical node that supports up to 10 connections.
• Buildings producing the same item located nearby increase their efficiency (the more buildings producing the same thing, the greater the bonus)
• Energy cells (new item) and energy converters (building) - converts energy cells into energy; used to transmit energy over long distances using electric catapults. Energy cells have a shell that collapses over time (the color changes from light yellow to red). If the shell breaks, then an explosion occurs, setting fire to everything within a radius of e.g. 5 cells. It is safest to transport energy cells in closed systems (catapults, bridge conveyors, kinetic conveyors) or on armored conveyors, otherwise after 1 or 2 hits on the cell, the shell is destroyed, the cell explodes. The life of one cell can be extended with the help of the buildings that these cells create (by launching cells and additional material to restore the shell in such building). The effect of amplifiers on the building e.g. increases the life of the cell. Buildings that convert cells back to energy require cooling. The efficiency of transforming buildings is not 100%, for example: to create a cell with a capacity of 100, you need to spend 110 energy and 1 kinetic alloy or phase fabric (cells made of kinetic alloy will be stronger, but less capacious, cells made of phase fabric will be more capacious, but less durable).
• barrel (a new type of item) into which liquid will be poured in special buildings. The liquid will become an item suitable for dispatch by conveyors and catapults, and upon arrival at its destination will be converted back into liquid through special buildings
• When a drill covers deposits of several materials, each of them produces at a certain rate. If the drill captures the stone, it will produce some sand and water. If water is not removed, the drill will gradually break. The water will be polluted, which means that it will be possible to obtain sand and, with some probability, any metal or other resource. The cleansing building for water will take place in a large 6x6 cell building.
• Oil power plants
• Drones delivery. Used to deliver goods over an unlimited distance. They can deliver cargo only between special air ports, which can be expanded using landing platforms. Such ports will require energy and items to produce containers with which drones will deliver items. There will be two types of containers - simple (e.g. require lead and titanium) and armored (e.g. require the same as armored conveyors). Drones will be divided into dashes. Drones of the first shooting range will be able to transport up to 10 items of one of any type at a time without consuming fuel. Drones of the last shooting range will be able to transport 100 items of any four types, consuming fuel (kerosene produced from oil) => they will have a range limit, but they can be refueled in the air using special flying stations or on the ground using ordinary gas stations. All drones require containers for delivering items. Containers wear out over time and require replacement with new ones. The health of each container can be seen by pointing to the unit using this container.
• The storage can be upgraded to a splinter core if you fill it with all resources to the maximum and give 10,000 energy during the rebuild, which lasts e.g. 12 seconds.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Just some critique from me,
• Buildings producing the same item located nearby increase their efficiency (the more buildings producing the same thing, the greater the bonus)
This doesn't make sense. Think of when you have a super large factory... When you put more production, the other machines don't speed up. If anything, they slow down, because it lowers the average input of resources into the factory.
• Oil power plants
Oil -> coal -> steam... Or you can make blast/pyratite for impacts/diff gens.
• barrel
have you heard of conduits?
• Drones delivery. 
Mass drivers. Drone delivery would probably be way too broken.
• Energy cells (new item) and energy converters (building)
Surge towers. What you suggest is basically a pack of batteries that can be shipped. I can't see myself using a really large station to convert some batteries into energy, when I can just use surge towers...

**Comment by TheQuietSky** [comment]
thats a lot of ideas, im almost certain drone delivery is going to be added

**Comment by zethnest** [comment]
I feel like this should be in seperate issue posts instead of compiled into one. Hard to discuss about everything in a single issue.

**Comment by sova-kostyan** [comment]
> Just some critique from me,
> • Buildings producing the same item located nearby increase their efficiency (the more buildings producing the same thing, the greater the bonus)
> This doesn't make sense. Think of when you have a super large factory... When you put more production, the other machines don't speed up. If anything, they slow down, because it lowers the average input of resources into the factory.
> • Oil power plants
> Oil -> coal -> steam... Or you can make blast/pyratite for impacts/diff gens.
> • barrel
> have you heard of conduits?
> • Drones delivery.
> Mass drivers. Drone delivery would probably be way too broken.
> • Energy cells (new item) and energy converters (building)
> Surge towers. What you suggest is basically a pack of batteries that can be shipped. I can't see myself using a really large station to convert some batteries into energy, when I can just use surge towers...

thanks alot for your critique. 

About buildings... yes, may be you right.

Oil Power Plants... no, becouse oil have very large importance in our live, but in the game coal more powerful then oil. its attempt to do oil more importance in the game.

barrel... i think, its more convient to transport liquids for longer ranges.  

drones... i invented this becouse... at one day i played on map which had 2 main continents and many small islands beetwen them. these islands was very important for us, BUT we cant take over  even one first island, only becouse we cant transfer enough energy to it (surge towers have limited range, they just did not reach). even catapult hardly got out this island. that's when this idea came to me. energy cells came to mind as another solution to this problem.

**Comment by potatoisagender** [comment]
I think the way oil power currently works is somewhat more versatile than a pure oil plant. Coal centrifuges create a redundancy with the oil power.

Also, itcannotbe, how long have you been playing the game?

**Comment by itcannotbe** [comment]
Around 2.x @potatoisagender 

Early v4 has Steam Generators (previously called Turbines Generators) that are able to use oil directly but was scrapped because no one really used then and then some bug.

**Comment by Anuken** [comment]
Most of these don't make sense.
