### ISSUE TITLE
Add a key/scrollwheel to zoom in editor for pc

### ISSUE THREAD

**Issue by PickAPlayerNameFirst** [Anuken/Mindustry-Suggestions#2241]
**Describe the content or mechanics you are proposing.**
Have a scrollwheel to zoom in and out in editor. Only for PC. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Very useful for pc users who don't have a mouse.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
two fingers up and down for touchpad to scroll

**Comment by PickAPlayerNameFirst** [comment]
Don't have a touchpad. PC user.

**Comment by PickAPlayerNameFirst** [comment]
Pls have like The ZOOM feature still working on editor, why the asdf controls working but the zoom feature not?

**Comment by joshuaptfan** [comment]
Editor zoom is currently hardcoded to mouse scroll. IMO it should be bound to the in-game zoom bindings (which also default to mouse scroll), so that they can be rebound.

**Comment by PolloUsami** [comment]
i believe i has seen this in other place....

**Comment by PickAPlayerNameFirst** [comment]
> i believe i has seen this in other place....

Its been 23 days since you posted that issue,  but no one cares : \
