### ISSUE TITLE
Cryofluid mixer affinities

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2242]
**Describe the content or mechanics you are proposing.**
Add the water affinity to cryofluid mixers

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1. it makes more sense
2. realism
3. you finally can feed your ~~teenagers with soda~~ reconstructors with cryofluid
3. if this is bad please tell me why

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X]I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If it has positive affinities, it should have negative ones too. XD

**Comment by BlueWolf3682** [comment]
1. no
2. no
3. yes

**Comment by itcannotbe** [comment]
>     1. no

It doesn't actually makes sense.

>     2. no

Screw realism, embrace game balance.

>     3. you can already

It's one of the reasons T4 reconstructors are even T4s
Excessive resources consumption. Fit for the units they reconstruct.

>     4. yes

Ask yourself before asking others.

**Comment by BlueWolf3682** [comment]
i cannot tell if youre agreeing with me or making points for an argument

**Comment by itcannotbe** [comment]
> i cannot tell if youre agreeing with me or making points for an argument

I basically added context to your comment.

**Comment by BlueWolf3682** [comment]
ah, fair enough

**Comment by Bohaska** [comment]
water is nice

**Comment by Bohaska** [comment]
anyway

**Comment by Bohaska** [comment]
is

**Comment by Bohaska** [comment]
spamming

**Comment by Bohaska** [comment]
against

**Comment by Bohaska** [comment]
the

**Comment by Bohaska** [comment]
rules?

**Comment by itcannotbe** [comment]
Why did you change the topic after you closedbthe issue?

**Comment by Bohaska** [comment]
So that if someone repeats the idea he wouldn't be marked as a duplicate :P

**Comment by BlueWolf3682** [comment]
@Anuken I apologize for the ping, but would you mind banning Bohaska from making any further issues in this repository? It really would be appreciated.

**Comment by RedstonerKBC** [comment]
> @Anuken I apologize for the ping, but would you mind banning Bohaska from making any further issues in this repository? It really would be appreciated.

I don't get why people apologize for pings? It's not like you stabbed him or something lol. Also the ping is literally for getting someone's attention. I don't get why a minor annoyance caused by using a tool in the way it was designed is warrant for an apology. XD

**Comment by Kyllingene** [comment]
> I don't get why people apologize for pings? It's not like you stabbed him or something lol. Also the ping is literally for getting someone's attention. I don't get why a minor annoyance caused by using a tool in the way it was designed is warrant for an apology. XD

Because it is quite annoying when someone pings you unnecessarily, or unrelatedly, or whatever. So, out of courtesy, people often apologize for pinging someone else.

**Comment by Bohaska** [comment]
i'm planning on reopening this issue, using a different topic

**Comment by BlueWolf3682** [comment]
Don't.

**Comment by PickAPlayerNameFirst** [comment]
Logic:
Silicon Crucibles has hot tile affinities. 

Now Silicon smelters have wet affinity?
