### ISSUE TITLE
Buff thermal pump

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2246]
**Describe what you would like changed, and why.**
Thermal pump is only slightly better than rotary pump. Rotary pump pumps 12 liquid units/sec/tile but thermal pump only pumps 13.19 liquid units/sec/tile. This is not worth the building cost. (the electricity cost is around the same per tile)

**Describe the changes you want to propose. Include possible alternatives.**
Thermal pump needs to be buffed in comparison to rotary pump. I think 160 units/sec would be more balanced. Of course this is just my opinion. If you have any other ideas, please comment

**Comment by itcannotbe** [comment]
3 words.

Deep liquid tiles.

**Comment by itcannotbe** [comment]
![Screenshot_20210403_172448_io anuke mindustry](https://user-images.githubusercontent.com/45280919/113474246-895ab200-94a1-11eb-95c4-736d1f85f121.jpg)
![Screenshot_20210403_172403_io anuke mindustry](https://user-images.githubusercontent.com/45280919/113474253-8b247580-94a1-11eb-8e7a-adb70ce5b889.jpg)

A larger pump is always worth it.

**Comment by Bohaska** [comment]
thx
