### ISSUE TITLE
Volcanic Sectors

### ISSUE THREAD

**Issue by MrSkyBlue1020** [Anuken/Mindustry-Suggestions#2247]
**Describe the content or mechanics you are proposing.**

Volcanic eruptions are imminent. Hell reigns from above, and your core is in danger. Rev up your menders, because it is sure firey.

Resources are plentiful in volcanic sectors, likely rich in scrap. Building larger buildings or using heavier attacks could trigger eruptions earlier, causing players to think more conservative with defenses and drilling.

A natural form of slag is present here and can be collected and refined as normal, or used for power in thermal generators.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Adding a more "risk-reward" scenario in some maps would be beneficial to players that are up for the challenge

A map with a volcano nearby could be interesting, and present numerous challenges.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
That's not how mindustry tiles work.

**Comment by PickAPlayerNameFirst** [comment]
Everyone bow and praise: MODS!

**Comment by Bohaska** [comment]
> MODS!

I would love to know which mods you are specifically referring to
