### ISSUE TITLE
Spore Buff

### ISSUE THREAD

**Issue by PickAPlayerNameFirst** [Anuken/Mindustry-Suggestions#2248]
**Describe what you would like changed, and why.**
We all know spores. But wait, who used them? Its a very underrated item and too expensive to mass produce **for other things**. Well, try making oil. Yoy would only need 84/sec water and 420 power units/s. Well,  if you have no water source, then good luck making oil with this technique. Just to fuel one single plastanium compressor. Check discord #balancing to see the full details of my issue. 

**Describe the changes you want to propose. Include possible alternatives.**
Buff the cultivator's production time. To produce oil using the prod time 2.33/s, it would need 7 cultivators to produce in max efficiency. But if the production time is prob. 1.33/s, you would only need 4 cults to produce the spore oil in max efficiency. 

**Again, this is basically a duplicate idea, but if you fix the time variable, it could probably make the spores back to the norm.**

**Comment by PickAPlayerNameFirst** [comment]
I would've wanted to complete the maths, but the 1.33/s prod time could make it accessible for both the steam generator and the oil extractor. The water requirements is okay for me btw, nothing to tweak there.

**Comment by PickAPlayerNameFirst** [comment]
> I would've wanted to complete the maths, but the 1.33/s prod time could make it accessible for both the steam generator and the spore press. The water requirements is okay for me btw, nothing to tweak there.

**Comment by itcannotbe** [comment]
Is this a duplicate of something?

**Comment by itcannotbe** [comment]
Yes, yes it has been.

#1780 #2099

**Comment by PickAPlayerNameFirst** [comment]
Was it implemented before? And was it the same solution with those issues? 

No, it wasn't. 

Please, understand the concept and the solution. This is a lot better than those other two.

**Comment by PickAPlayerNameFirst** [comment]
What they wanted to tweak was the ingredients of the cultivator, but I'm completely okay with it. The prod time should be tweaked.

**Comment by Bohaska** [comment]
I think prod time can be tweaked, but keep the same proportion (28 water units for 1 pod)

**Comment by PickAPlayerNameFirst** [comment]
Why 28? Its 12/s previously... So its 24/s

**Comment by PickAPlayerNameFirst** [comment]
Not 24... 

12/s, 2.33s = 28 water/sec. Then x1.33

**Its 37.33/s**
Welp,that's high tho

**Comment by itcannotbe** [comment]
Don't forget to increase it's power usage.

**Comment by itcannotbe** [comment]
And nerf the tile affinity.

**Comment by itcannotbe** [comment]
And nerf the tile affinity or make the cult be a 3x3 from a 2x2 to balance the boost that tile affinities provide.

**Comment by itcannotbe** [comment]
Also.

> Well, if you have no water source.

Then don't. Use oil extractors.

**Comment by PickAPlayerNameFirst** [comment]
> Also.
> 
> > Well, if you have no water source.
> 
> Then don't. Use oil extractors. 

What if there are low to no sand tiles in the map? That's where the spore press comes, it should be an option, not a no-choice needs.

**Comment by PickAPlayerNameFirst** [comment]
> Don't forget to increase it's power usage.
> 
> From 54/s to 94.5/s

Wait, we need to reduce the power usage, compare the amount of power to the power consumption of oil extractor.

**Water per second:**
Our buffed partner: Basically the same. 
84/s. 
Oil extractor: 
9/s.

See the big difference? 

**Power per second:**
Buffed Cultivator: Also the same. 
420 units/s
Oil extractor: 
180 units /s

We just made the cultivator save space. Not the power difference.

**Comment by PickAPlayerNameFirst** [comment]
Also the tile affinity is our only chance to make a cultivator better in certain places.

**Comment by itcannotbe** [comment]
You forgot 1 important thing. Oil extractors can only used on certain tiles.

**Comment by itcannotbe** [comment]
> > Also.
> > > Well, if you have no water source.
> > 
> > 
> > Then don't. Use oil extractors.
> 
> What if there are low to no sand tiles in the map? That's where the spore press comes, it should be an option, not a no-choice needs.

First of all, please don't blame the game if the map maker sucks at knowing how difficult can that be.

Second, buffing a block based on a edge, edge use case is stupid.

**Comment by itcannotbe** [comment]
Also spore pods are ingredient for making blast. Buffing cultivators based on spore making oil only is a stupid balancing basis.

**Comment by PickAPlayerNameFirst** [comment]
> > Don't forget to increase it's power usage.
> > 
> > From 54/s to 94.5/s
> 
> Wait, we need to reduce the power usage, compare the amount of power to the power consumption of oil extractor.
> 
> **Water per second:**
> Our buffed partner: Basically the same. 
> 84/s. 
> Oil extractor: 
> 9/s.
> 
> See the big difference? 
> 
> **Power per second:**
> Buffed Cultivator: Also the same. 
> 420 units/s
> Oil extractor: 
> 180 units /s
> 
> We just made the cultivator save space. Not the power difference. 

  Also the problem is, there are too little things to do with the spores, changing the way it is from the oil perspective is a lot more visual. The point in the blast compound is it will get now a 1:1 ratio (1.33-1.33). Well, I'm annoyed when I see 2 cultivators in a blast mixer. And besides, blast compound is rarely used because of the stupid spore requirements.

**Comment by PickAPlayerNameFirst** [comment]
> First of all, please don't blame the game if the map maker sucks at knowing how difficult can that be.

Campaign? 

I just used those useless things to make a plast compressor because almost all of the sand tiles are already occupied by silicon, meta and phase fab.

**Comment by PickAPlayerNameFirst** [comment]
> First of all, please don't blame the game if the map maker sucks at knowing how difficult can that be.

Also, I'm not blaming the game here. **This is a choice**. Not a blame. We're giving spores an opportunity to get inside the industry section and not from their weedy, dusty shelves.

**Comment by PickAPlayerNameFirst** [comment]
> You forgot 1 important thing. Oil extractors can only used on certain tiles.
> 

That's why we should buff the ingredients slightly. It shouldn't be too much buffed, so much that it can out pass the oil extractors, the oil presses should compensate for that. 

Like,  new power consumption in between 300-350 power units/s. 
And new water consumption should be in between 70-75 water units/s.

**Comment by Sense101** [comment]
I really wouldn't increase water consumption past 12/s. That would just be ridiculous, you would have to surround it with water extractors on a map with no water. I would say it should be ok to buff it but to then leave the input requirements the same. And you can't make the power as high as 300/s, I think that is much too high.

**Comment by PickAPlayerNameFirst** [comment]
> I really wouldn't increase water consumption past 12/s. That would just be ridiculous, you would have to surround it with water extractors on a map with no water. I would say it should be ok to buff it but to then leave the input requirements the same. And you can't make the power as high as 300/s, I think that is much too high.

Its worth building Cultivators near a water source. And the one thing I wanted was to decrease the power consumption, from 94.5 units /s to 60-75 units /s per cultivator. The input remains okay to me. Its just optional to reduce it.

**Comment by PickAPlayerNameFirst** [comment]
> > I really wouldn't increase water consumption past 12/s. That would just be ridiculous, you would have to surround it with water extractors on a map with no water. I would say it should be ok to buff it but to then leave the input requirements the same. And you can't make the power as high as 300/s, I think that is much too high.
> 
> Its worth building Cultivators near a water source. And the one thing I wanted was to decrease the power consumption, **from 94.5 units /s to 60-75 units /s per cultivator**. The input remains okay to me. Its just optional to reduce it.

**Comment by Humanoid-X** [comment]
Ah, this repo, again, recalled my memory of my sector that used somthing like 30 spore presses and 15 cultivators to make oil.

**Comment by PickAPlayerNameFirst** [comment]
> Ah, this repo, again, recalled my memory of my sector that used somthing like 30 spore presses and 15 cultivators to make oil. 
>
Wut, the current cultivator to spore press ratio was 7:1, yours was 1:2, which was a complete was of power if you ask me.

Try modifying it, 15 cultivators could process 2 spore presses, 28 more presses are all acting idle.

**Comment by shadoxxhd** [comment]
Maybe he had 15 cultivators and 30 water extractors?

**Comment by PickAPlayerNameFirst** [comment]
Well, this issue is now closing. 
This issue has been now passed in PR, and is closed.

**Comment by PickAPlayerNameFirst** [comment]
It could be implemented, so stay tuned.
