### ISSUE TITLE
new feature please!

### ISSUE THREAD

**Issue by Dingroupcr** [Anuken/Mindustry-Suggestions#2249]
I want 2 thing : 
1. crash handler
because it crash many time.
2. 3D mindustry!!
because it interesting everyone!

**Comment by PickAPlayerNameFirst** [comment]
Basically those 2 things are out of context. 
The crash handler is very unspecified. Especially that crashes are fixed by diagnosing what's the problem. 

And you're requesting 3D mindustry while your device is crashing. Didn't you think it would make the game crash more by making it 3D?

**Comment by genNAowl** [comment]
^

**Comment by QmelZ** [comment]
* [X] i am capable of removing the template completely, but not actually filling it

**Comment by itcannotbe** [comment]
>     * [x]  i am capable of removing the template completely, but not actually filling it

Hmmmm. I think it goes like....

- [X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
> I want 2 thing :
> 
>     1. crash handler
>        because it crash many time.

A crash handler already exist and it is the one that generates a crash log for the developer to know what roughly where in the code was last run until the crash.

>     2. 3D mindustry!!
>        because it interesting everyone!

Do you mean everyone except you is interesting?

Also no. One does not make a top down game into a 3D game easily. It involves rewriting everything about the game, you ||REDACTED||

**Comment by IVV-NCX** [comment]
Agreeing with the above. Report the bug here, and follow the format or, quote Anuke, "Reap your soul". https://github.com/Anuken/Mindustry/issues

**Comment by PickAPlayerNameFirst** [comment]
> >     * [x]  i am capable of removing the template completely, but not actually filling it
> 
> Hmmmm. I think it goes like....
> 
> - [X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.
> 
> 

That's a literal ambomination, oof that really hurt lol, maybe he's from other countries that don't speak english



Or an infant using github

**Comment by Catchears** [comment]
> 3D mindustry!!

have you heard of satisfactory? it even supports conveyor spaghetti

**Comment by Kyllingene** [comment]
I love issues like this that have so little effort put into them you wonder if this is a complete troll or a 6-year-old. If you do happen to be six, stop, follow the GitHub guidelines please. If you at least 13, stop, don't be a troll, or you will have unhappy repercussions. If you are just too lazy to put any thought into this, stop, don't be like that, it's a bad mentality.

**Comment by PickAPlayerNameFirst** [comment]
> Issues like this that have so little effort put into them that they make you wonder if this is a complete troll or a 6-year-old. If you do happen to be six, stop, follow the GitHub guidelines please. If you at least 13, stop, don't be a troll, or you will have unhappy repercussions. If you are just too lazy to put any thought into this, stop, don't be like that, it's a bad mentality.

That's right. Please close this issue. The decision has been unanimous.

**Comment by QmelZ** [comment]
> > ```
> > * [x]  i am capable of removing the template completely, but not actually filling it
> > ```
> 
> Hmmmm. I think it goes like....
> 
> * [x]  I am incapable of reading, comprehending, and completely filling out the template, but capable of removing its entirety.

*yeah it's just me being lazy and not searching for it, and i just wrote something that would explain the point*

**Comment by sample-text-here** [comment]
close this

**Comment by PickAPlayerNameFirst** [comment]
I knew the only ones that can close this was the author... Not completely sure tho

**Comment by itcannotbe** [comment]
And the owner or a maintainer.

**Comment by PickAPlayerNameFirst** [comment]
Oh... Thx for the info

**Comment by Humanoid-X** [comment]
Mindustry crashes a lot. Ok.
You want 3D Mindustry? Did you eveer coded before bro?
Mindustry crashhes a lot, and you want it to be 3d. WUT WUT WUT?!?
Even the sector selection screen can reap your phone's soul...

**Comment by PickAPlayerNameFirst** [comment]
> Mindustry crashes a lot. Ok.
> You want 3D Mindustry? Did you eveer coded before bro?
> Mindustry crashhes a lot, and you want it to be 3d. WUT WUT WUT?!?
> Even the sector selection screen can reap your phone's soul...

Already said that... 
This man just a toddler lol

He doesn't even know how to close the issue.
