### ISSUE TITLE
The two superweapons.

### ISSUE THREAD

**Issue by potatoisagender** [Anuken/Mindustry-Suggestions#225]
**Describe the content or mechanics you are proposing.**
The air only and ground only mechanic of certain weapons is interesting. Perhaps the ideas could be implemented when designing the two superweapons. Something like a super powerful, albeit air only turret, and perhaps a laser, or another weapon that targets ground, but can accidentally hit air targets.

Or, you could use some other ideas list here, such as upgraded scorch, or something.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I don't think you understood what these "superweapons" are - they're not intended to be used against units, or even individual blocks. They exist solely to wipe out enemy sectors.

**Comment by potatoisagender** [comment]
Oh. Sorry, I haven't been checking the discord for information on trello tabs.

**Comment by Anuken** [comment]
There wasn't really any discussion about that card; I just haven't added details for it yet.
