### ISSUE TITLE
USE CORWDIN

### ISSUE THREAD

**Issue by driver1748** [Anuken/Mindustry-Suggestions#2250]
**Describe the content or mechanics you are proposing.**

Use [Crowdin](https://crowdin.com/) in order to improve the efficiency of translating

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The translators are now submitting 10000 PRs for the same language.We need a more _pro_  way to do these translating things. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The reasom why translators are submitting multiple PRs for 1 translation is lines are added or modified fr the base translation and the developer doesn't wait for translators before compiling the game and thus translators needs to be up to date close to release day to that fall back english text isn't used.


And auto translation software, most of the time produce sub obtimal results.

**Comment by liuxilu** [comment]
NO, Crowdin is a bad CI, I'd rather use WEBLATE.
Better make one myself, like [EhTagTranslation/Editor](https://github.com/EhTagTranslation/Editor) (在做了在做了)

**Comment by Bohaska** [comment]
> (在做了在做了)

Doing it, doing it.

**Comment by Anuken** [comment]
Crowdin is expensive, and their open-source plans don't apply to commercial products.

**Comment by DeltaNedas** [comment]
anuke translate by anuke for anuke and most importantly anuke

**Comment by Bohaska** [comment]
I checked, many translation platforms have free plans for open source software. However, Mindustry would usually not qualify for them because of the price on steam and the app store. Hmm..... crowdfund money to buy a plan for a translation platform?

**Comment by stuffyAI** [comment]
> crowdfund money

crowdfund money to buy a translation platform plan to translate a game and make more money....
