### ISSUE TITLE
Loading mods from folders

### ISSUE THREAD

**Issue by Xasmedy** [Anuken/Mindustry-Suggestions#2251]
## Describe what you would like changed, and why.**

As the tittle says, be able to **load mods inside folders**. This because a lots of mods/plugin uses one or more **.json** file as settings or places to save information (I do this as well), but if every mod does this, the `mods` folder will get very messy.

## Describe the changes you want to propose. Include possible alternatives.**

The change is easy, just make able to load all the mods inside folders (naturally these folders need to be inside the `config/mods` folder). If this change is added, [these mods](https://prnt.sc/113ys4o) should be able to load without problems. Would even be awesome have a variable that says where the mod is loaded, example something like this:
```java
Vars.modDirectory.currentMod.path();

or

Vars.currentMod.path();
```

*This does not be prefectly as I wrote, is just an example.*

**Comment by DeltaNedas** [comment]
the better solution is for mods to not save settings in the mods folder in the first place

**Comment by Xasmedy** [comment]
> the better solution is for mods to not save settings in the mods folder in the first place

So for a single file I should make a folder for make it more clear inside the mods folder? And saving it somewhere else is a bit annoying till you always need to change folder for change the settings.
