### ISSUE TITLE
Campagin Suggestion

### ISSUE THREAD

**Issue by Kadir-Can** [Anuken/Mindustry-Suggestions#2252]
Well this isnt an issue its just a suggestion, a suggestion to make campagin better. Its to make it like an online/offline gamemode, like if your online you can travel to other planets and see whos planet it is above the planet (a name should be there) and then you can enter theyre zone (offcourse travelyng should cost resources, and if you dont want anyone disturbing you there will be a accept/decline request to choose who can enter who cannot enter, oh and make it so you can trade with others).

This would make campagin a much better gamemode to play and i think it could make your game popular quick, and players would like playing mindustry (i already like playing mindustry), and others can play with theyre friends much easier.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
You realize that in order to do that, Anuke would have to have huge, No Mans Sky-like servers for a free game? That is simply way out of Anuke's budget by a few million dollars. Remember that Anuke is a solo dev relying on the $5 price tag for Steams version, and that you can download the game anyway on itch.io, Github, and mobile. Not feasible.

**Comment by Kadir-Can** [comment]
oh, then i am sorry. :(

**Comment by IVV-NCX** [comment]
So, multiplayer "interplanetary" travels? That is possible by hosting a multiplayer game. If you're saying use a server, then the above is quite true. You can host a server yourself (VPS is about $5 each month). Also, interplanetary travel is a WIP for a later version, and there are mods (Gold, PixelCraft), with new planets.

**Comment by PickAPlayerNameFirst** [comment]
First, Interplanetary Travel will be in v7, and it won't be online. Its always offline. The online ones are only the multiplayer servers.

**Comment by PickAPlayerNameFirst** [comment]
You did not:
> ... checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
Check the trello, you can see what Anuke has been doing and will be doing right now. You'll see the planets that you're talking.

**Comment by Kadir-Can** [comment]
yes i did chek trello

**Comment by Kadir-Can** [comment]
i looked at campagin and i didnt see this suggestion i made

**Comment by Kyllingene** [comment]
To be fair, this suggestion is almost certainly not on the trello.

**Comment by PickAPlayerNameFirst** [comment]
Its on trello, Interplanetary travel.

**Comment by PickAPlayerNameFirst** [comment]
Did you see the planet #1?
And the planet #2?

Or am I blind?
