### ISSUE TITLE
logic: changing jumps from curves to polylines for better visability

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry-Suggestions#2253]
**Describe the content or mechanics you are proposing.**
Changing jumps from jump blocks from being curves to polylines for better visability.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The jumps will be easier to follow, therefore making code easier to debug and correcting block placement. Especialy handy with making large code chunks by hand.
![mindustry logic updc](https://user-images.githubusercontent.com/33349024/113521375-68758800-9599-11eb-8ac1-78ff4180a157.png)
![mindustry logic updl](https://user-images.githubusercontent.com/33349024/113521376-690e1e80-9599-11eb-8076-e3e33cbc4031.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stoneRdev** [comment]
I do agree that the curves are pretty bad on the eyes, but my main issue is that the edge of the code blocks is so close to the edge of the screen that I can't see much of a line anyway.
So maybe this plus moving the right margin on the code container over a bit to make room for the jump arrows

**Comment by RedstonerKBC** [comment]
What if when you right-click a jump it takes you to the line of code that it jumps to? Or it highlights that arrow?

**Comment by TranquillyUnpleasant** [comment]
> What if when you right-click a jump it takes you to the line of code that it jumps to? Or it highlights that arrow?

The arrow gets highlighted when you hover over it. The jumps aren't really the issue, its the fact that the logic ui is super bulky in how its laid out.

**Comment by RedstonerKBC** [comment]
> > What if when you right-click a jump it takes you to the line of code that it jumps to? Or it highlights that arrow?
> 
> The arrow gets highlighted when you hover over it. The jumps aren't really the issue, its the fact that the logic ui is super bulky in how its laid out.

I know but I meant permenently until you click something else, because yes the UI is bulky and if your jump is far you can't tell where it jumps to sometimes. Also the UI for making custom waves in the editor has a similar issue. It's bulky and hard to organize. But that's off topic lol.

**Comment by stoneRdev** [comment]
Honestly, I would prefer having line numbers and jumping to a line number directly. Moreso, I would actually prefer to be able to edit the script directly without the ui. Like an in-game script editor. Would help for mobile since (atleast on my phone) switching to my text editor app usually closes the game
