### ISSUE TITLE
D-pad Movement control for mobile version

### ISSUE THREAD

**Issue by charlesmema** [Anuken/Mindustry-Suggestions#2254]
**Describe the content or mechanics you are proposing.**

>a customizable D-pad movement control for mobile version of mindustry

>a small "camera lock" toggle button that can lock the camera on the player  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

>enabled by default, can be disabled in settings, can be customise the  size and placement in settings, great for manuverability in PvE and for balancing cross-platform play in multi-player since moving and sniping can not be utilized on full extent in mobile version

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
#687
