### ISSUE TITLE
Water Reservoir Tile

### ISSUE THREAD

**Issue by Saice-o** [Anuken/Mindustry-Suggestions#2255]
**Describe the content or mechanics you are proposing.**

A block that can be filled with a liquid (say, 200 units per tile) which would have an open top that naval units can be placed on, allowing them to be used in stages without many pools. Cryofluid pools could also potentially increase efficiency of naval units within

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would allow naval units to have a certain amount of use in locations that dont have many or any pools of water, along with potential decorative uses (not like people care about that...)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by bvcbvc** [comment]
thats why it could be limited to tier 3

**Comment by Bohaska** [comment]
basically a portable pool from the btd games...

**Comment by PickAPlayerNameFirst** [comment]
A bit good, especially that naval units aren't usually used, due to its tile requirement. Also,  make it two for the units to move pool-by-pool. Idt that its a tile, its a building.

**Comment by PickAPlayerNameFirst** [comment]
Far too expensive for a 3x3 omura turret that can pop if enemies are near. Think of it, deleting one added pool, use the spare pool to add it in a specific location, then pop it and all thw liquid is gone. 

Still can't be implemented to the game.

**Comment by Bohaska** [comment]
hmm..... make naval units instantly die when they aren't in water?

**Comment by PickAPlayerNameFirst** [comment]
One feature Can Fix It All. 

Everyone Bow and say... 
MODS!

**Comment by bvcbvc** [comment]
They do this anyways

**Comment by bvcbvc** [comment]
A bot put of water is a dagger in a wall, so to speak

**Comment by Saice-o** [comment]
if the tile was really fragile would that fix any of the issues?

**Comment by bvcbvc** [comment]
it would mostly make it vunerable to anything that has pierce or aoe, which most everything does, so maybe

**Comment by USMP-lancer** [comment]
get stalr
