### ISSUE TITLE
The ability to change the name of processor linked blocks or have them changed automatically

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry-Suggestions#2256]
**Describe the content or mechanics you are proposing.**

I struggle when using processors because I have to re-copy and re-paste any processor if I misclick or wrongly tag a block. Say there are 4 nodes, if I click a wrong node, I have to reset the processor or the node because it has been assigned the wrong tag. If you could manually change the tag of the processor linked blocks or have the tags reset automatically when you no longer have then linked then that would make linking multiple blocks much easier

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

 I hate doing repeated tasks and I often do this many times when I’m using processors so...
 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
This would be useful

**Comment by Humanoid-X** [comment]
It's a bug that unlinked buildings are not "actually" unlinked.
