### ISSUE TITLE
The dagger tree needs to be given a passive ability

### ISSUE THREAD

**Issue by wlndows10** [Anuken/Mindustry-Suggestions#2257]
**Describe what you would like changed, and why.**
The dagger tree needs to be given a passive ability to compensate for their low mobility and lackluster survivability.
1) The dagger tree is the only unit tree that cannot avoid choke points.
2) Fortress and mace are both horribly slow but do not have the bulk to compensate.
3) Though more of a pvp issue, both Ripple and Fuse are available early on in the game and are extremely effective at shredding ground units like paper. 
4)I am aware of the pulsar's ability to shield buff. I believe this change is still valid.

The dagger itself is not weak by any means but both mace and fortress are outclassed by each of their air, ground and naval counterparts. My reasoning for this change is simple; **all other unit trees do not have to adhere to chokepoints.** 

How are they outclassed? Minke has the passive ability to buff fire rate, zenith has both bulk and can kite structures from a distance, horizon is weak but agile, attrax can avoid walls, and spricot has the ability to leech. Pulsar and quasar have the ability to boost, build, and shield.

**Describe the changes you want to propose. Include possible alternatives.**
Tier 2-3 should all be given the passive ability to increase the health/armor of the units of its own type, within its vicinity,

-This would be restricted to units of its own type to prevent daggers becoming support units.
-The percentage margin would be between 2% and 10%. I am not asking for mace to become a tank.
-This would be restricted to tiers 2-3. Scepter/Reign are powerful enough as is, and this change is intended mainly for fortress/mace.
-This is not a damage buff. There are other units that can do damage.
-This change was not suggested for support units as the crawler and nova tree do not need the buff and can function as standalone units.

**Comment by joshuaptfan** [comment]
[Anuke would say](https://discord.com/channels/391020510269669376/663853133587546138/813804423628455936)

> if it's not useful, simply buff stats until it is

And I agree. The dagger tree is meant to be dead simple brute force. Leave passive abilities to specialist trees.

**Comment by Bohaska** [comment]
agree with joshuaptfan for this

**Comment by G0nTar** [comment]
> [Anuke would probably say](https://discord.com/channels/391020510269669376/663853133587546138/813804423628455936)
> 
> > if it's not useful, simply buff stats until it is
> 
> And I agree. The dagger tree is meant to be dead simple brute force. Leave passive abilities for specialist trees.
> 
> [More Dakka](https://tvtropes.org/pmwiki/pmwiki.php/Main/MoreDakka) - don't mind this link, it's just a [TV Tropes trap](https://tvtropes.org/pmwiki/pmwiki.php/Main/TVTropesWillRuinYourLife).

This man speaks the truth, and the dagger tree already has a passive, they have the power of spam, you can make 3 dagger in the time it takes to build 1 nova

**Comment by wlndows10** [comment]
> > [Anuke would probably say](https://discord.com/channels/391020510269669376/663853133587546138/813804423628455936)
> > > if it's not useful, simply buff stats until it is
> > 
> > 
> > And I agree. The dagger tree is meant to be dead simple brute force. Leave passive abilities for specialist trees.
> > [More Dakka](https://tvtropes.org/pmwiki/pmwiki.php/Main/MoreDakka) - don't mind this link, it's just a [TV Tropes trap](https://tvtropes.org/pmwiki/pmwiki.php/Main/TVTropesWillRuinYourLife).
> 
> This man speaks the truth, and the dagger tree already has a passive, they have the power of spam, you can make 3 dagger in the time it takes to build 1 nova

I was mainly talking about t2 and t3 but yeah good point.

**Comment by G0nTar** [comment]
If anything, I would buff their HP a bit, T2 and T3, they are supposed to be the Grunts n Meaty units of the army after all

**Comment by wlndows10** [comment]
closed because I forgot most people dont even play attack and pvp lol
