### ISSUE TITLE
Permanent changes to turret stats made by decisions in campaign

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2258]
**Describe the content or mechanics you are proposing.**
I would like to add a way to change the stats of turrets through the tech tree. All of these are optional but cannot be changed after obtaining them
1. Modern foundations: Increases all building's health by 15%, but increases building time by 20%. Unlocked after you create your first plastanium. You cannot research "Cut corners" after doing this.
2. Cut corners: Decreases all building time by 20%, but decreases all building health by 15%. Unlocked after you create your first plastanium. You cannot research "Modern foundations" after doing this.
3. Aerodynamic wings: Increases all aerial unit's speed by 20%. You cannot research Titanium Legs after this. Unlocked after you create your first plastanium.
4. Titanium Legs: Increases all ground unit's speed by 20%. You cannot research Aerodynamic wings after this. Unlocked after you create your first plastanium.
5. i would write some more later

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More replay-ability for campaign. Every time you restart the game, you can try different types of upgrades.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion is planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion does exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
![noio](https://user-images.githubusercontent.com/69094702/113644606-fbfe9580-9639-11eb-975b-948f2164d39e.png)
***"Additional configuration of blocks"***

**Comment by BlueWolf3682** [comment]
I stand by [https://github.com/Anuken/Mindustry-Suggestions/issues/2242#issuecomment-812825818][this.]

**Comment by Bohaska** [comment]
To be on the record, I wasn't lying
> I have read README.md to make sure my idea is listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
this issue is bad yay

**Comment by Bohaska** [comment]
the author was an idiot anyway
