### ISSUE TITLE
remove copper from conveyor recipe

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2259]
**Describe what you would like changed, and why.**

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by Bohaska** [comment]
@Bohaska Dude.... what the heck are you doing

**Comment by Bohaska** [comment]
Sorry

**Comment by DeltaNedas** [comment]
then conveyors would be free

**Comment by BlueWolf3682** [comment]
[.](https://github.com/Anuken/Mindustry-Suggestions/issues/2242#issuecomment-812825818)

**Comment by MauritanianMapping** [comment]
Why

**Comment by MauritanianMapping** [comment]
April Fools was four days ago man
