### ISSUE TITLE
ripple

### ISSUE THREAD

**Issue by HauntedSwipes** [Anuken/Mindustry-Suggestions#226]
make ripple shoot flying units cause scatter is pretty trash ngl

just an upgraded version of scatter whats there more to say?

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
I don't think an artillery is the best choice at aiming and supposedly hitting an airborne target.

**Comment by potatoisagender** [comment]
lmao. Have you heard of a thing called cyclones?

**Comment by Anuken** [comment]
Yeah, no.
