### ISSUE TITLE
Allow writing plaintext code in-game

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2260]
**Describe the content or mechanics you are proposing.**
In the editing code menu, I would like an option to see the plaintext code and to edit the code in plaintext. Maybe have an option to type code in plaintext, and turn it into block code by pressing the Enter key? It should also have an in-game syntax error finder.
<img width="999" alt="Screen Shot 2021-04-06 at 9 25 40 AM" src="https://user-images.githubusercontent.com/73286691/113645921-5ccdb280-96ba-11eb-924d-85888db477e7.png">

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Easier to write code and you can check your code easily

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion is planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion does exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
(the code above is just trash code)

**Comment by DeltaNedas** [comment]
why create an entire text editor inside mindustry when you can just use a text editor

**Comment by Bohaska** [comment]
for newbies

**Comment by joshuaptfan** [comment]
The whole point of a Graphical User Interface is to abstract away the code. Plain text code exists only to be a generic method of storage.
