### ISSUE TITLE
Allow sneks in sandbox

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2261]
**Describe the content or mechanics you are proposing.**
I would like to have the ability to create (working) sneks in sandbox

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In sandbox, you should be able to do anything. If sneks are allowed, for instance you can make underflow/overflow chains to prioritize certain turrets.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Would it ever really be useful though?

Sandbox is there to allow one to test designs for actual play; What's the use of building designs that only work in sandbox?

**Comment by Bohaska** [comment]
> Would it ever really be useful though?

Why shouldn't you be able to test anything?

**Comment by BlueWolf3682** [comment]
Sources.

**Comment by Bohaska** [comment]
killing my darlings
