### ISSUE TITLE
Please Ban

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2262]
**Describe what you would like changed, and why.**

[Please Ban](https://github.com/Bohaska)

**Describe the changes you want to propose. Include possible alternatives.**

Ban Hammer time.

**Comment by Bohaska** [comment]
Why, exactly?

**Comment by itcannotbe** [comment]
![Uploading Screenshot_20210406_112836.jpg…]()

**Comment by itcannotbe** [comment]
![Screenshot_20210406_112836](https://user-images.githubusercontent.com/45280919/113654864-614e9700-96cb-11eb-8312-90ddc2b8fa47.jpg)

**Comment by Bohaska** [comment]
I closed them.

**Comment by RedstonerKBC** [comment]
> **Describe what you would like changed, and why.**
> 
> [Please Ban](https://github.com/Bohaska)
> 
> **Describe the changes you want to propose. Include possible alternatives.**
> 
> Ban Hammer time.

What does that even mean? You gave no reasons for banning this dude other than it is time. Time for what? Where in the rules does it say after a certain amount of time it warrants a ban? Or is it a certain number of posts? Did he break a certain number of rules? What exactly is cause for this dude's ban?

**Comment by DeltaNedas** [comment]
spamming nonsense suggestions and immediately closing them

**Comment by itcannotbe** [comment]
Closing, because I can. But continue the discussion.

**Comment by itcannotbe** [comment]
> spamming nonsense suggestions and immediately closing them

Not to mention needlessly changing the title so that people be mislead about what the suggestion is about.

**Comment by BlueWolf3682** [comment]
> > **Describe what you would like changed, and why.**
> > [Please Ban](https://github.com/Bohaska)
> > **Describe the changes you want to propose. Include possible alternatives.**
> > Ban Hammer time.
> 
> What does that even mean? You gave no reasons for banning this dude other than it is time. Time for what? Where in the rules does it say after a certain amount of time it warrants a ban? Or is it a certain number of posts? Did he break a certain number of rules? What exactly is cause for this dude's ban?

Bohaska is like that one company that keeps emailing you junk - making useless, nonsensical issues that should be removed.

**Comment by Anuken** [comment]
![Screenshot from 2021-04-06 09-38-41](https://user-images.githubusercontent.com/10100000/113719804-019cbf80-96bc-11eb-9942-2c29e8771b66.png)

Done. I would like to use the `#suggestions` channel to look for real suggestions, not search through meaningless spam.

**Comment by GitHubUser-B** [comment]
> ![Screenshot from 2021-04-06 09-38-41](https://user-images.githubusercontent.com/10100000/113719804-019cbf80-96bc-11eb-9942-2c29e8771b66.png)
> 
> Done. I would like to use the `#suggestions` channel to look for real suggestions, not search through meaningless spam.

YOU!?

**Comment by GitHubUser-B** [comment]
> ![Screenshot from 2021-04-06 09-38-41](https://user-images.githubusercontent.com/10100000/113719804-019cbf80-96bc-11eb-9942-2c29e8771b66.png)
> 
> Done. I would like to use the `#suggestions` channel to look for real suggestions, not search through meaningless spam.

OH MY GOD
