### ISSUE TITLE
Have a way to implement Anuken/MindustryMods as a list in Mindustry

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2263]
**Describe the content or mechanics you are proposing.**
Have a way to implement Anuken/MindustryMods as a list in Mindustry, similar to the server list.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
For example, if someone has a suggestion for Mindustry, they can find a mod for it instead.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [Please nerf OP already] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- 
![Screenshot_20210406_113113_io anuke mindustry](https://user-images.githubusercontent.com/45280919/113655025-abd01380-96cb-11eb-9140-500b35a49837.jpg)

**Comment by Bohaska** [comment]
Thx!
