### ISSUE TITLE
Make a way to donate money to Mindustry periodically

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2265]
**Describe what you would like changed, and why.**
Make a way to donate money to Mindustry periodically.

**Describe the changes you want to propose. Include possible alternatives.**
This would encourage more people to support Anuke and it would be easier to set up recurring payments. Not terribly important but would be nice to have

**Comment by MauritanianMapping** [comment]
You can buy the game off of Itch.io multiple times if you really want to support that badly and don't know any other way

**Comment by Bohaska** [comment]
True, and it's a nice to have thing, but it would be better if you can **periodically and automatically** donate money

**Comment by MauritanianMapping** [comment]
> True, and it's a nice to have thing, but it would be better if you can **periodically and automatically** donate money

There really isn't any good reason to add an automatic subscription system

**Comment by Kyllingene** [comment]
> There really isn't any good reason to add an automatic subscription system

> This would encourage more people to support Anuke and it would be easier to set up recurring payments. Not terribly important but would be nice to have

My concern is the fact that you could set this up, say $10/month, then forget you made it and wonder where on earth those $10 charges are coming from when you become a struggling college student.

**Comment by NajimiOsana** [comment]
In other words: make it look like Anuke is begging for money

**Comment by stuffyAI** [comment]
> In other words: make it look like Anuke is begging for money

It does seem like Mindustry can gradually be classified as 'product as a service', continuously evolving for user experience with vague final goal. It is not unusual for developers to have Patreons when using this dynamic, bonus points here for being open source.

But then again this is a sole-ops (assuming none of the other contributes will get paid full), so the actual fee would be extremely low, lower than I know of sites that support such payment.
