### ISSUE TITLE
display status effects & shields on health bars for players and guardians

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2267]
**Describe the content or mechanics you are proposing.**
for better clarity, any status effects and shields should be displayed on guardian health bars, and somewhere on the player status display. i'll go through the concepts one by one.
shields on you:

![Screenshot 2021-04-06 115047](https://user-images.githubusercontent.com/47570570/113749359-d23f8000-96c6-11eb-9e28-3588e346a50b.png)

i am bad at drawing but this is my concept drawing for the shields on the player. the important thing to note is that it only decreases when your shield is below the count of your unit's max health, and there will also be a percentage counter somewhere (not sure about that one). so, if you control a unit that has 200 max health and 300 shields, the shields bar will be full with the percentage "150%" next to it. its very important to know the percentage will disappear if shields are not 100% or more over your unit's health value.

shields on guardian:

![download (9)](https://user-images.githubusercontent.com/47570570/113750445-05364380-96c8-11eb-9a8b-e340ed220dce.png)

for guardians, my idea is to display the yellow bar on top of the red one. once shields fall below 100% of the unit's health it falls down, revealing the red bar behind it. and just like before, percentage vanishes if its under 100%. 

status effects on you

i think it'd be best to put your status effects on the right of your unit health visualizer. you can mouse over them, and click them, to open the core database's menu of the status effect (closing this wouldnt bring you to the core database menu). 

status effects on guardian

this one might be unecessary, but i think the best way to display status effects on the guardian is to show the icons directly below the health bar. this would cause very minimal clutter, since there's only ever 1 guardian bar displayed anyway.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

when playing it'd be nice to know what you're up against. if you face a shielded eclipse, you have no idea when the shields will break, which makes facing any shielded guardian a bit of a "hold your breath" moment.

or say, you're playing a multiplayer game and grab some air units to attack the other team. if your units have shields, it'd be nice to know that, and how much, so you can plan accordingly.

or, say you're a new player and discover a new effect. it'd be a nice QOL feature to see and just click on the status effect, for ease of access.

bottom line, this would make status effects and shields a bit more transparent. it would make learning the game a bit easier, add visual appeal, bring transparency, and help people discover ways to use turrets well. not everything in this suggestion has to be implemented, but i strongly reccomend the shields part of the suggestion.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 1ARC1** [comment]
I think not being able to know when the shield breaks is intentional, for tension. but the colors and indicators would be nice.

**Comment by RedstonerKBC** [comment]
Status effect indicators would be nice though. Status effects are an underappreciated game mechanic.

**Comment by 1ARC1** [comment]
yes, and with the new status effect icons it would be a good addition

**Comment by Humanoid-X** [comment]
yes
