### ISSUE TITLE
Gaurdian locator

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#2268]
*Basically, an option on the settings that can be turned on and off*, if on; gaurdian units will appear to have a special effect on the minimap (maybe glowing?) And an arrow that points out where the gaurdian is while playing

It would be nice to locate bosses because gaurdian units dont have special effects on them so players can't locate the gaurdian without damaging units one by one

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DoctorFuchs** [comment]
@N4B3R1USNT do you have an idea for a color using the locator?

**Comment by DoctorFuchs** [comment]
close.exe
