### ISSUE TITLE
Power map

### ISSUE THREAD

**Issue by pyronie** [Anuken/Mindustry-Suggestions#2269]
**Describe the content or mechanics you are proposing.**
a map that shows power usage, it could either A. display a whole new map, or B. an option you can enable on the current map. implementation could either change the intensity of your team's color for the magnitude of the tile's net power usage/generation. Or turn your team's coloration on the map to be two different colors, where one color would be the tile's net generated power, and the other would be the tile's net usage of power, and the intensity is its magnitude. of course, another novel method could be used to display this.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I believe adding a power map will make it improve the player's ability to notice areas of high power usage and generation, which would make finding the areas where power is used and generated much easier, allowing for better power management and distribution.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
So to do this clean one would need to use stochastics in order to give an actual effective information display...

Which by itself is not the easiest of feats to code in the first place, but can also get expensive on FPS very fast if recalculations have to repeat a multitude of times for accuracy.
Would it be sufficient to display a power statistic, e,g top (power-)Users and Producers by building and net amount,
and then also provide a map overlay similar to your suggestion but instead it just let's you toggle highlighting for previously mentioned Users and Producers?

**Comment by pyronie** [comment]
Any method that allows you to quickly grasp where the power is being used and produced is fine, I just suggested these specific methods because they allowed the entire power map of both users and producers to be on the same map so that you can tell if the generation of an area is being offset by its production easily. while having two pages is also good, at that point I do not see a significant reason to not use the two-color power usage/generation scheme at that point beyond team confusion.

**Comment by pyronie** [comment]
the peak a block could generate would be an overdriven impact at 250% speed while the peak a block could use would be the Overdriven Tetrative Reconstructor at 250% speed, and the magnitudes could be found from those numbers
