### ISSUE TITLE
S h i e l d s

### ISSUE THREAD

**Issue by Pogreu** [Anuken/Mindustry-Suggestions#227]
**Describe the content or mechanics you are proposing.**

the color of the shields should be according to the color of the walls. meaning that brown(copper) color shield is the weakest and the bright yellow(surge) color will be the strongest. the same as the orange(phase) which can deflect a type of bullet too.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

units will be strongker which makes some maps that spawn camps(small wave drop) harder

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I don't like the idea of using the same color scheme for shields as walls.
