### ISSUE TITLE
Air units and payload conveyors

### ISSUE THREAD

**Issue by numer99** [Anuken/Mindustry-Suggestions#2270]
**Describe the content or mechanics you are proposing.**
Imagine you have and air factory making flares onto a payload conveyor system, and you have a reconstructor somewhere else, you want the flares to land on the payload conveyor, so you can upgrade them, but the flares cannot go back down onto the payload conveyor

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Basically if an air unit is above a payload conveyor allow them to land

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
1. ground units don't work either
2. what about water units?
3. just upgrade them in the first place

**Comment by Slava0135** [comment]
logic: am I a joke to you

**Comment by Humanoid-X** [comment]
@MrDuck557
1, 2. Payload units
3. true

**Comment by numer99** [comment]
I know ground units can just walk onto a payload conveyor and walk of,
but naval and air units cannot go back on

**Comment by mkaatman** [comment]
I wish we could tell air units to fly to the next factory.
