### ISSUE TITLE
A feature which allows you to download a mod from a different branch

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry-Suggestions#2271]
**Describe the content or mechanics you are proposing.**
A feature that allows you to download a mod on a different branch instead of only downloading the `main`/`master` branch.

Here's my example:

If you download a mod, a prompt will appear asking you which branch you want to use.

Select a branch:
`main`
`testing`
`unused`

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will help with importing mods from different branches.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Since this has a niche use, can't this be done manually? Like through import github mod or something?

**Comment by 1ARC1** [comment]
> Since this has a niche use, can't this be done manually? Like through import github mod or something?

so your saying mod browser is useless with this logic. its just to make modder's jobs easier. its not super complicated, and its useful.

**Comment by itcannotbe** [comment]
Why would you even use multiple branches aside for testing/experimental development purposes?

Also why would need this if you are locally developing your mod then pushing it to GitHub for version control?

Just make a symlink and you don't even need to copy paste your files.

**Comment by abrasmag3** [comment]
Some modders also have seperate java/js versions of a mod, would it help to combine them?

**Comment by 1ARC1** [comment]
> Why would you even use multiple branches aside for testing/experimental development purposes? Also why would need this if you are locally developing your mod then pushing it to GitHub for version control? Just make a symlink and you don't even need to copy paste your files.

same reason peopled played 6.0 when it was in alpha/beta. to see whats coming in the mod.

**Comment by SMOLKEYS** [comment]
meh, might as well close
