### ISSUE TITLE
Increase ammo multiplier surge alloy in Swarmer

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2272]
Now its x2, but high fire rate consume huge count of surge, and conveyors do not have time to deliver resource to turret. Suggest increase it to x4/x5. Cyclone now have x4, but have lower fire rate. Or make more ammo storage inside turret.

**Comment by MrDuck557** [comment]
1. template
2. copper or titanium conveyor

**Comment by PickAPlayerNameFirst** [comment]
#1790 and #1880 be like... 

This has already been suggested, please close this issue and support #1880 instead. 

It could help the devs work more efficiently as less duplicate issues were passed.

**Comment by PickAPlayerNameFirst** [comment]
For those who don't know, 

Anuke will NOT prioritize any issues that are most duplicated, all creative issues are all the same. And duplicate issues are not counted.

**Comment by itcannotbe** [comment]
Swarmers waste less bullets than cyclone because swarmers bullets homing. Cyclones aren't.

**Comment by genNAowl** [comment]
Considering ammo usage, DPS, and space efficiency, blast compound Swarmers are way better than blast compound Cyclones. 

The niche Swarmers currently fill is as the best turret with blast compound; It feels like Surge alloy was never supposed to be a valid ammo in the first place.

**Comment by Qvertyes** [comment]
> 
> 
> #1790 and #1880 be like...
> 
> This has already been suggested, please close this issue and support #1880 instead.
> 
> It could help the devs work more efficiently as less duplicate issues were passed.

 "Or make more ammo storage inside turret."

**Comment by PickAPlayerNameFirst** [comment]
> Swarmers waste less bullets than cyclone because swarmers bullets homing. Cyclones aren't.

Tbh, a swarmer can waste 2 surge alloys as one enemy entity get in its detection range. 

I agree with you, but the problem here is that swarmers are mainly used to take down enemies in long range, but for a 2x2 turret, it's too expensive to feed ammo. Not about wasting it.

**Comment by B00M3000** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1880#issuecomment-815817840

**Comment by PickAPlayerNameFirst** [comment]
Ok, can we please close this issue? 
The PR has been submitted on Mindustry, and is now closed. 

Anuke said he will implement it himself.
