### ISSUE TITLE
Turret variants

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2273]
**Describe the content or mechanics you are proposing.**
Turrets have more specialised variants. Accessible on F1, F2 and F3 when the turret is selected. In case F1 is already taken, move all binds 1 ahead.
Essentially:
Duo has:
-Duo — your standard Duo. What did you expect?
-Trio — range is 25% shorter. Accuracy is 25% lower. Fire rate is 50% higher. Ammo multiplier is reduced by 1
-Quadra — range is 45% shorter, accuracy 45% lower. Double firerate, same ammo multiplier as Trio

Hail has:
-Hail — standard
-Blizzard — takes cryofluid with silicon to shoot slowing rounds. Damage is reduced by 20%, but applies freezing effect
-Thunderstorm — inflicts shock upon targets. Only uses silicon. Shoots 50% slower, with same damage, but shock effect.

Lancer has:
-Lancer — standard
-Pike — smaller Corvus beam. Inflicts 0% damage to structures. Damage of the standard Lancer, but beam is 2 times longer and it takes 2 times longer to charge.
-Glaive — charges beam for 4 seconds, then aims 15 degrees to the right of the target. Activates beam and swipes 30 degrees to the left. Accuracy is potentially low, since targets can escape the beam. It deals lancer damage every second, but takes two times more power.

Salvo has:
-Salvo — standard
-Volley — shoots graph and thorium,  has 5 tiles more range, and salvos of 6. Slower reload time and necessary cooland usage.
-Barrage — shoots any munition, in innacurate barrages of 8. Lower damage, but higher area covering. Reload is 30% slower.

Cyclone:
-Cyclone — standard
-Tornado — shoots more bullets, but higher spread and lower damage.
-No need for third variant.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

More turrets, but not so different than standard ones. Adds more options for specialisation and generally makes the gameplay more diverse.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrSkyBlue1020** [comment]
I like the idea

**Comment by itcannotbe** [comment]
It doesn't matter if it allegedly "makes gameplay more diverse" If the said turrets don't even gets used.

Here's some facts:

Range is already a balancing issue as the game doesn't even have that much distance to play with.

Also here are some ranges of some select turrets:
Scorch: 7.5
Duo: 12.5
Cyclone: 25
Ripple 36.25
Foreshadow: 62.5

People would always choose the longest version of the available turrets because fire rate doesn't mean anything if the turret can't even reach the target.

**Comment by BorisA11** [comment]
@itcannotbe These arent meant to be OP. They are meant to be different. Duos are essentially CIWSs, hails are supports, and beams are just different beams.

**Comment by itcannotbe** [comment]
I never said OP.

**Comment by itcannotbe** [comment]
Duo -> Cyclone
Hail -> Ripple
Lancer -> Meltdown

**Comment by BorisA11** [comment]
@itcannotbe Turrets for defence, not necesserily offence

**Comment by the-kido** [comment]
no one here has to fight about this because we all know he won't be implementing it anyway. He has already planned two new weapons as well. 

Also, a lot of these contradict turrets already in the game. For example wave --> tsunami. Scatter --> Cyclone etc.

**Comment by BorisA11** [comment]
@the-kiddo Some turrets do have the tiering. Some dont. And I cant see why not

**Comment by the-kido** [comment]
More weapons is not the answer. Some of them are truly pointless too, such as trio and quad, which have a direct upgrade, fuse. Glaive doesn't need to exist, two lancers are already better than it and it would have no use anyway.

**Comment by 1ARC1** [comment]
some of these are just modded content ripped out and changed a little

**Comment by itcannotbe** [comment]
> some of these are just modded content ripped out and changed a little

Basically....

### MODS!

**Comment by 1ARC1** [comment]
> > some of these are just modded content ripped out and changed a little
> 
> Basically....
> 
> ### MODS!

don't suggest adding modding content to the game unless its technically planned on the trello, see betamindy's payload cannons for an example.

**Comment by genNAowl** [comment]
I have to say that this kinda feels like a variant of turret upgrades and upgradable blocks has been suggested (and rejected) many times before.

**Comment by 1ARC1** [comment]
thats because they have, and then some modders added them into the game.

**Comment by Kyllingene** [comment]
So add tons of turrets (imagine the spriting work!), most of which will never get used, crowding up the turret section, because diversity is invariably a good thing everywhere no matter what the consequences. Seems legit.

**Comment by PickAPlayerNameFirst** [comment]
Pls close the issue. 

Conclusion: 
**MODS are the answer.** Like what @the-kido said,
>Anuke won't implement it anyways. 
>
And like what @itcannotbe said, you can make a mod, or just download a turret expansion pack.
