### ISSUE TITLE
Green naval units (support)

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2274]
**Describe the content or mechanics you are proposing.**
Support naval units. Each one in the tree fires green lasers and/or bolts. All of them can build. All have HP similar to their offensive counterpars. Tier 1 costs 25 silicon, 15 titanium and 20 glass.

TIER 1:
Volta — Fires repair beams at long ranges.
Weapon: Same as Mega's armanent, just longer ranged, has 4 beams, maybe with faster fire.

TIER 2:
Ampere — Fires electric cluster shells, projects shield around themselves.
Weapon: Hail-like artillery, upon contact releases bolts which del damage and chain.
Shield type: Hexagonal forcefield
Shield max health: 200
Shield restoration rate: 20
Shield active above 40 power.

TIER 3:
Watt — Projects strong forcefield around itself, automatically shoots nearby projectiles.
Weapon: Slower Segment-class point defence. **Would really love to see a CIWS in Mindustry, if possible.**
Shield type: Hexagonal forcefield
Shield max health: 600
Shield regen rate: 50
Shield active above: 120

TIER 4:
Resistor — Slows down nearby projectiles, with change of destroying them. Increases nearby units speed. Projects planar shield pointed at the enemy.
Weapon: Temporal field (slows down all projectiles by 10% every second. Max slowdown is 75%
Status effect projection: Overclock II 
Planar shield repulse chance: 20%

TIER 5:
Conduit — Nearby units do not fire projectile, instead half of thier damage is given to the ship's beam weapon, which activates every 5 seconds.
Weapon: Burst beam. Can inflict up to 5000 damage. Range of the beam: 50 tiles. Beam can not pierce, functions like a railgun
Status effect: Overdrive
Shield max heath: 1200
Shield regen rate: 200/s
Shield active above: 400

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I know this is large. And it adds more new features. So was the whole v6 update, and I would really like to see proper fleets, consisting of various ships. These are supports, virtually useless on their own, but combined with others of the class form a formidable force.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 1ARC1** [comment]
a cost for the t1 would be nice.

**Comment by BorisA11** [comment]
@1ARC1 Done!

**Comment by the-kido** [comment]
there have not been like, 10 suggestions for support naval units.

**Comment by itcannotbe** [comment]
Why is this it's own suggestion. There are multiple request for naval support.

Also..... You can't name a unit conduit for obvious reasons.

**Comment by RedstonerKBC** [comment]
If you do add a new naval branch (which you should because everybody wants one) balance it so that Risso's branch doesn't become op. Currently Risso's branches are insanely powerful but balanced by their water-only mobility. Any more buffs and they'll become op.

**Comment by Kyllingene** [comment]
![image](https://user-images.githubusercontent.com/69094702/113914528-80642c00-9792-11eb-8b04-024927e7908a.png)

[this is a duplicate](https://github.com/Anuken/Mindustry-Suggestions/issues/1730#issuecomment-754576829)

**Comment by Kyllingene** [comment]
please close everyone has suggested these and everyone (including anuke) agrees they should exist

**Comment by genNAowl** [comment]
Support Naval will probably be added by Anuke himself, but there is a mod implementing them (MEEPofFaith/missing-category-units)
