### ISSUE TITLE
Make ground attack branch units passively regenerate health

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2275]
**Describe what you would like changed, and why.**
Atm ground attack branch (dagger -> mace etc.) sucks.

**Describe the changes you want to propose. Include possible alternatives.**
nerf quasars

**Comment by 1ARC1** [comment]
you know you could be smart and say how you would like them to be changed and how much.

**Comment by itcannotbe** [comment]
> **Describe what you would like changed, and why.**
> Atm ground attack branch (dagger -> mace etc.) sucks.
> 
> **Describe the changes you want to propose. Include possible alternatives.**
> nerf quasars

Ground attack sucks because you can't spam them.

**Comment by 1ARC1** [comment]
> > **Describe what you would like changed, and why.**
> > Atm ground attack branch (dagger -> mace etc.) sucks.
> > **Describe the changes you want to propose. Include possible alternatives.**
> > nerf quasars
> 
> Ground attack sucks because you can't spam them.

wrong, crawler and dagger have the lowest construct speed, aside from flares.

**Comment by itcannotbe** [comment]
> > > **Describe what you would like changed, and why.**
> > > Atm ground attack branch (dagger -> mace etc.) sucks.
> > > **Describe the changes you want to propose. Include possible alternatives.**
> > > nerf quasars
> > 
> > 
> > Ground attack sucks because you can't spam them.
> 
> wrong, crawler and dagger have the lowest construct speed, aside from flares.

I am not wrong, you're basically limited to unit cap.
If this was starcraft T1s are already a threat.

**Comment by 1ARC1** [comment]
> > > > **Describe what you would like changed, and why.**
> > > > Atm ground attack branch (dagger -> mace etc.) sucks.
> > > > **Describe the changes you want to propose. Include possible alternatives.**
> > > > nerf quasars
> > > 
> > > 
> > > Ground attack sucks because you can't spam them.
> > 
> > 
> > wrong, crawler and dagger have the lowest construct speed, aside from flares.
> 
> I am not wrong, you're basically limited to unit cap.
> If this was starcraft T1s are already a threat.

which means you can send 8 daggers a lot sooner than 8 novas.
you could send 16 units by the time 8 novas are done.

**Comment by genNAowl** [comment]
Well the thing is, a T1 unit in groups of 1s or 2s aren't ever really a threat

The Gamma can take out a T1 in 2 or 3 secs.

**Comment by wlndows10** [comment]
Health regen is kinda pointless if they cant survive long enough to utilize it

**Comment by itcannotbe** [comment]
How about more armor if there are the same of it's kind near it up to a certain extent.
