### ISSUE TITLE
Water platforms

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2276]
**Describe the content or mechanics you are proposing.**
(Sorry if this has been suggested and I didn't see it. I saw similar ideas but they were different enough that I felt I could suggest this.)

A platform block that can only be placed on liquids. It is solid so naval units get blocked and ground units can safely walk on it.

Cost: Expensive, like it requires surge or something. This makes them hard to spam and prevents players from overcoming bodies of liquid too quickly which were meant to be obstacles in the first place.
Size: 1x1. You can customize platforms into whatever shape you need. Also helps with balance since you need a lot to make decent bridges for ground units to walk on.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Ground unit trees can safely traverse bodies of liquids with some exceptions: low tier crawler-branch units and the dagger-branch. There is no easy way to safely transport them without either going around or using mono-branch units to carry them across. If map-makers don't like it they easily can either ban the platform block or ban the ground unit factory.

The community seems to agree, we need another naval unit branch. The majority of suggestions I've seen were for naval support units and most of those have the ability to transport units across water. The ability to transport units across bodies of water.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I think the suggestion that this duplicates is titled floating platforms but the blocking naval wasn't mentioned.

Though it kinda defeats the purpose, naval units has the most stupid fire power among unit types.

Also this should be expensive not cheap.

**Comment by Kyllingene** [comment]
> The community seems to agree, we need another naval unit branch. The majority of suggestions I've seen were for naval support units and most of those have the ability to transport units across water.

So if Anuke is highly likely to implement that (see [this](https://i.imgur.com/40ckgJN.png) picture), then what is the point of bridges existing? Sure, they add a tiny bit of extra functionality, but since when was that ever a good reason to add things?

> Also this should be expensive not cheap.

That is why it is, if you actually read the post:

> Cost: Expensive, like it requires surge or something.

**Comment by RedstonerKBC** [comment]
> So if Anuke is highly likely to implement that (see [this](https://i.imgur.com/40ckgJN.png) picture), then what is the point of bridges existing? Sure, they add a tiny bit of extra functionality, but since when was that ever a good reason to add things?
I know. This suggestion is best if he doesn't add them. Probably doesn't mean certainly. It means likelier than not. Maybe you can add both? Servers can still choose to ban one or the other.

**Comment by Kyllingene** [comment]
Both of those seem like reaches. Yeah, servers could ban either, but why add two redundant things just because one or the other can be banned? Seems a little desperate.
