### ISSUE TITLE
Cross play if it isn't already. 

### ISSUE THREAD

**Issue by Noorly** [Anuken/Mindustry-Suggestions#2277]
I think when making an online game, there should be an option for cross play servers (toggleable)
I would go into more depth about this, but I think it's pretty self explained.

**Comment by Catchears** [comment]
If you mean allowing people from different platforms to connect to one server, that already exists.

**Comment by itcannotbe** [comment]
You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
Also, please go in depth about this because if your suggestion is different from what Catchears meant. I don't really get it how you're going to pull that off.

**Comment by Noorly** [comment]
I've noticed that the game is cross play, I just wish I checked sooner. I feel like an idiot and knew this would happen. I love minedustry. ❤️

**Comment by stuffyAI** [comment]
> I've noticed that the game is cross play, I just wish I checked sooner. I feel like an idiot and knew this would happen. I love minedustry. heart

close this suggestion now that it is solved :D

**Comment by B00M3000** [comment]
Bruh, I wonder what the point of using Java is? psst. For cross play.

**Comment by itcannotbe** [comment]
> Bruh, I wonder what the point of using Java is? psst. For cross play.

No, no it's not.

**Comment by B00M3000** [comment]
> > Bruh, I wonder what the point of using Java is? psst. For cross play.
> 
> No, no it's not.

one of the points
