### ISSUE TITLE
Possible changes to Poly rebuild AI

### ISSUE THREAD

**Issue by 19lamanna** [Anuken/Mindustry-Suggestions#2279]
**Describe what you would like changed, and why.**

Currently, the Poly auto-rebuild AI has some flaw that reduce its effectiveness in maintaining a base/sector.

**Describe the changes you want to propose. Include possible alternatives.**

The following list are some features that could make the Poly auto-rebuild AI better, this list may expand depending on what people say in #development:

1) If a player is currently deconstructing a building, but it is destroyed, do not bother rebuilding it
2) If a structure is destroyed many times in quick succession, before the rebuild process finishes, the poly should not bother rebuilding it again

**Comment by 19lamanna** [comment]
Note for suggestion 2:
if critical defense infrastructure is being destroyed, it may take many attempts before it gets fully rebuilt. The player would not want to the polys to give up in that situation

**Comment by 19lamanna** [comment]
General note:
One alternative to "giving up" would be for the poly to focus on a different block to rebuild, and perhaps come back to the troublesome block later

**Comment by Kyllingene** [comment]
So, if the block keeps getting destroyed (say, 3 times in a row) before the poly finishes rebuilding, it simply puts it at the end of the list?

**Comment by 19lamanna** [comment]
> So, if the block keeps getting destroyed (say, 3 times in a row) before the poly finishes rebuilding, it simply puts it at the end of the list?

Yes

**Comment by Weathercold** [comment]
Another suggestion:

If a poly can't rebuild a block due to insufficient resources, it will try to rebuild other blocks first. Currently they just get stuck.

**Comment by octopuscaat** [comment]
i agree. however, they should not rebuild structures that were destroyed due to being in the enemy dropzone. it wastes resources when they rebuild something that keeps getting destroyed. furthermore, when they build stuff near the dropzone or enemys they basicly walk right into their own deaths. they dont even try to avoid it. they just die and it annoys me.

**Comment by 19lamanna** [comment]
> Another suggestion:
> 
> If a poly can't rebuild a block due to insufficient resources, it will try to rebuild other blocks first. Currently they just get stuck.

Anuke said this is not desirable behavior: Polys often rebuild things that are interrupted by lack of resources.

**Comment by Mothership007** [comment]
you can solve a lot of these problems just using logic processors

**Comment by 19lamanna** [comment]
Logic can solve almost every problem, but that doesn't mean it should substitute a proper fix. Logic is not a resource easily accessible by everyone, and it will almost certainly be less reliable that a proper, hard coded fix.
