### ISSUE TITLE
Team Colored Force Projectors

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#228]
**Describe the content or mechanics you are proposing.**

Have force projector shields be the color of the team.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would help identify shield ranges if multiple teams have force projectors in close proximity. (also it would look cool)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Ah yes, the new form of art. Colour mixing by team.

**Comment by itcannotbe** [comment]
Wait. Why does this suggestion even exist. Someone is already active developing the code for this.

**Comment by Katsute** [comment]
There is no active pull request involving colored force projector shields

**Comment by potatoisagender** [comment]
wdym pull request?

**Comment by Katsute** [comment]
There isn't a pull for this on the main repo, so it's difficult to determine if this feature is currently being implemented

**Comment by potatoisagender** [comment]
Apparently I'm an idiot. What's a pull, and what's a repo?

**Comment by Katsute** [comment]
A pull request
https://github.com/Anuken/Mindustry/pulls

**Comment by potatoisagender** [comment]
whats the diff between an issue and pull rq?
This is going down the rabbit hole.

**Comment by Katsute** [comment]
An issue is just an issue,

A pull request is code separate from the main game that will later be put in when it's complete.
https://help.github.com/en/github/getting-started-with-github/github-glossary#pull-request

**Comment by Summet-V** [comment]
I'm trying to implement that.

**Comment by itcannotbe** [comment]
Exactly my point.

**Comment by Katsute** [comment]
Implemented in https://github.com/Anuken/Mindustry/commit/7401c16ded22e2b5e02dcd52649618ddcde3eaeb
