### ISSUE TITLE
Need client-side ability to destroy building "ghosts"

### ISSUE THREAD

**Issue by 19lamanna** [Anuken/Mindustry-Suggestions#2280]
**Describe what you would like changed, and why.**

Currently, clients in a server have no way to remove "building ghosts", only a client that is running the server can do this right now. These ghosts allow polys to attempt to rebuild them, with no effective way for players to stop them from doing so.

**Describe the changes you want to propose. Include possible alternatives.**

allow any client to remove "building ghosts", not just the client that is running the server

**Comment by PickAPlayerNameFirst** [comment]
It's not really a ghost building, its when enemies have succeeded to crush the building, poly units will rebuild them for you. Its an intentional feat, but the problem is when the ghost building wants the player to demolish it completely, it could be a problem.

**Comment by PickAPlayerNameFirst** [comment]
e.g. When a surge wall is built inside the enemy drop zone, the surge wall will be immediately destroyed, and when poly units go and rebuild it, it would be destroyed... Again. Now when you try to disassemble the building, the poly units are still tasked to rebuild the building. 
And if you succeeded to remove the building by yourself and your binded units, the poly swarm will come back later to attempt to rebuild it again.

**Comment by PickAPlayerNameFirst** [comment]
The same also happens with turrets. When, let's say, a thorium reactor is built inside the range of four enemy swarmer turrets, the cycle goes back again.

**Comment by PickAPlayerNameFirst** [comment]
Well, the issue is great, but the mechanics could be a pain to code. 

Maybe like this:
If the poly unit's target building gets destroyed (or removed) in less than 5 seconds, thetarget ghost building will not be characterized as a ghost. And it will be removed to the queue.

**Comment by OnyxFinger** [comment]
> Well, the issue is great, but the mechanics could be a pain to code.
No, just make ghosts appear client-side and tell the server you want to delete it like any building, of course there can be complications but it isn't too hard to make I think.
