### ISSUE TITLE
Ease of coding

### ISSUE THREAD

**Issue by Bassem-Const** [Anuken/Mindustry-Suggestions#2281]
**Describe the content or mechanics you are proposing.**
Make inputs for code support +*/^()// in their inputs.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think when you have a long program of code in a processor it takes too long to make an operator line then move it to it's place, and just feels unnatural,
and may help in easier understanding of the code.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [I'm on mobile] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
1. being on mobile doesnt mean you cant read README
2. this would require every argument to be parsed for expressions, no
3. if you want a higher level language use one, last i heard https://github.com/Vilsol/go-mlog is nearly feature complete.
