### ISSUE TITLE
Restart map or delete all structures

### ISSUE THREAD

**Issue by sneyed** [Anuken/Mindustry-Suggestions#2283]
**Describe the content or mechanics you are proposing.**

As a player, I would like the ability to restart a campaign map (*not the entire campaign*) from scratch without old buildings from the previous attempt

Current workarounds are:
- manually delete the save file
- intentionally die repeatedly until all your structures are gone (takes me over 5 repetitions to fully eliminate old buildings)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

When I fail the mission, I feel that my previous strategy was faulty in some way and would like to try a different approach from a clean slate.

Not providing an easy way to do this to players like me encourages us to just stop playing entirely rather than try to fix the previous failed attempt or use one of the painful workarounds above.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Related issues:
- [1031](https://github.com/Anuken/Mindustry-Suggestions/issues/1031) This issue talks about resetting the map seed, I am simply asking for the ability to delete all of the previous attempts buildings
- [1923](https://github.com/Anuken/Mindustry-Suggestions/issues/1923) This issue was not submitted correctly and has unconstructive discussion

2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mothership007** [comment]
I 100% agree with you. Once i played fungal pass during the v6 beta when the crux ai could build some op schematics right beside the core. These structures built by the ai were practically indestructible as with infinite recources the enemy gamma and polys spawned during waves rebuilt it almost instantly. It was not possible to build anything as the crux has built several self-sufficient ripple turrets the could reach the core

**Comment by itcannotbe** [comment]
Maybe delete all structures should be the behavior when dealing with attack maps.

**Comment by joshuaptfan** [comment]
> intentionally die repeatedly until all your structures are gone (takes me over 5 repetitions to fully eliminate old buildings)

Do you know you can delete the ghosts of your destroyed structures with right-click, same as if you are deconstructing buildings?

**Comment by SMOLKEYS** [comment]
So basically, this is like the "Abandon" feature from V5 but instead of leaving remnants, it just resets the whole map, am i right?

**Comment by PickAPlayerNameFirst** [comment]
Oh well, we have the delete button, it both deletes the abandoned buildings constructed by you, and the ghost blueprints. 

If you delete the abandoned buildings, you basically have more items in your inventory. Don't you like a headstart?
