### ISSUE TITLE
extra sector on serpulo

### ISSUE THREAD

**Issue by iwantmods82** [Anuken/Mindustry-Suggestions#2287]
**Describe the content or mechanics you are proposing.**
maybe add an extra campaign sector on serpulo?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** i think that it will improve the game by giving players an extra sector for slightly more gameplay. it might be useful because it would bring the sector count of handrawn maps to 17 (just like how it was before the removal of desert wastes).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by PickAPlayerNameFirst** [comment]
Custom game is an extra sector. 

Just make your own map by using the generate option. The ores are already pre generated once you play the game. 

Use noise, the target floor will change to another floor, and river noise, to generate rivers. 
There are more options out there (generate walls, etc.) try it out and experiment. 

Its up to you on where will you add the core and the enemy core/spawn.

**Comment by PickAPlayerNameFirst** [comment]
Also try the built-in custom games, they are just campaign like, but its more intense cuz ITS ENDLESS. You can also try the community maps, search it on discord and you'll see. 

And also, in V7 you'll see more sectors, cuz there will be more planets. 

Please close this issue, the steps for you are already given.

**Comment by genNAowl** [comment]
I wouldn't say custom games = a campaign sector; Campaign sectors are passively simulated even when you are not in the sector, and the fact that it can interact with other sectors through launch pads and such marks it as something different from a custom game.
