### ISSUE TITLE
Copy-pasting in the map editor

### ISSUE THREAD

**Issue by XenonLog01** [Anuken/Mindustry-Suggestions#2288]
I am proposing that a simple copy paste function be added to the map editor.

This will make creating maps less tedious and faster. 

I'm not quite sure how to implement this. My first thought is to just copy paste ores and blocks if a toggle is off, and just ground tiles if turned on.

Thanks for taking the time to read this!

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [NO, YOU DID NOT] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
Duplicate as fuck of #259

**Comment by Dioo0** [comment]
> Duplicate as fuck of #259 and many others, list below:
> 
> #339
> #890
> #1492
> #1928

i know, its kinda off topic, but how you make this search?

**Comment by PickAPlayerNameFirst** [comment]
Its in the PR in mindustry rn. 
Already closed PR. 

Please close the issue before continuing the discussion. 

Thank you.

**Comment by PickAPlayerNameFirst** [comment]
> > Duplicate as fuck of #259 and many others, list below:
> > 
> > #339
> > #890
> > #1492
> > #1928
> 
> i know, its kinda off topic, but how you make this search? 

Also @Dioo0 go to the repository (Mindustry-Suggestions) and go to issues. 
Then tou see the search button. 
Now the button is self explanatory.

**Comment by Dioo0** [comment]
> > > Duplicate as fuck of #259 and many others, list below:
> > > 
> > > #339
> > > #890
> > > #1492
> > > #1928
> > 
> > i know, its kinda off topic, but how you make this search? 
> 
> Also @Dioo0 go to the repository (Mindustry-Suggestions) and go to issues. 
> Then tou see the search button. 
> Now the button is self explanatory. 

thanks
