### ISSUE TITLE
Logistics Naval Unit Branch & Companion Blocks

### ISSUE THREAD

**Issue by Pers-Pluto** [Anuken/Mindustry-Suggestions#2289]
**Describe the content or mechanics you are proposing.**
A naval unit branch that focuses almost solely on logistics, with only very minor support traits. This suggestion is more to provoke new ideas rather than actually get implemented, it's probably unbalanced.

**Units**
All of the ships move faster in deep water. Possibly they can have companion naval units, which protect them from enemy units. Cores might support less cargo ships compared to other units. (I didn't consider liquid storage, feel free to recommend new ideas about that & other stuff.)

T1/Boat:
Can contain 100 items and 10k units of energy. Has no defenses.

T2/Cargo Ship:
Can contain 500 items and 50k units of energy. Moves faster than the T1 cargo ship. Has very weak air & naval defenses (Maybe can not hit ground units?).

T3/Better Cargo Ship:
Can contain 1k items and 100k units of energy. Has traded the air defenses for a small force field that protects itself. Can use silicon (or another material in its storage) to heal itself.

T4/Even Better Cargo Ship:
Can contain 5k items and 500k units of energy. Has an even more powerful force field and has defenses.

T5.1/The Best Cargo Ship:
Can contain 10k items and 1mil units of energy. Has the best defenses in this branch, maybe the unit with the best defenses across all units. Moves slowly.

T5.2/
There are more ideas about this. Maybe the ship can contain 100k or even 1mil items, 100mil energy & can cross through sectors to reach other docks (For docks see below.) and input or output items from them. As this might be hard to simulate, passing through a sector might take x seconds with the sector fully covered with deep water. Shallow water and land slows the ship. If a deep water tile has 1 unit of efficiency, shallow water might have 0.5 and land 0.25. So a sector with only shallow water takes 2x seconds to travel. If the sector doesn't have any water in it, it can not be traversed. Alternatively, it needs to have a certain amount of water to be traversed, like %20 only- water efficiency (Which is %20 deep water or %40 shallow water, land doesn't count for this calculation) for example. This way there is no need to simulate the sectors. Moves very very slowly. If T6 is ever implemented, this might be the T6 version.

The maximum amount of this unit can be a worldwide limit.

This would be so cool, especially if there are ocean worlds or just worlds with huge oceans on them in the future. Modifying the supply lines and creating huge water reliant world-wide supply chains. 
"Where is this silicon producing sector getting its sand from?"
"Oh, that? There's this huge desert sector 6 sectors away, and I got a ship moving a million sand from there and distributing it around the planet every hour."

**Companion Blocks**
Dock/
Can maybe partially be placed on deep water? Units from this branch can retrieve energy and items from this. Classic dock concept.

Wireless dock/
For the sector crossing T5 ship idea. Since it might be hard to simulate a normal dock, this dock can directly connect to the core, capable of directly inserting and extracting items from it. This makes simulating it similar to simulating a launchpad launching items from the core directly. For balance issues, might only work with T5 ships. Needs energy to work.

**Logic and Unit AI**

The unit can manually be selected to retrieve items from certain docks and send them to other docks. If the unit is below a certain percentage of health, it might retreat to safer waters, alternatively it might retreat to a docking station or a different specific block. It avoids enemy turrets & units unless specifically controlled.

Logic can be used to make the unit pickup a certain amount of items from certain docks if a condition is triggered. Maybe the ship can be used to tank damage while other high dps units destroy the defenses.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

First off, the cons are the AI might be hard to program and simulating sector crossing units is probably a pain in the backside.

The pros: 

It makes huge ocean worlds a possibility. It opens up new possibilities to map makers, like making mostly deep water maps where even surge towers and mass drivers can't connect the islands on the map, so cargo ships are necessary.

Creates an alternative to launch pads, which is the only way to move items between sectors except launching. Creates an alternative to conveyors & air cargo, and makes water tiles more useful. If, in the future, there will be world-wide wars necessary to overtake certain places, sector crossing ships would be very useful.

Creates an alternative to power nodes and surge towers, and makes batteries more useful.

Adds a previously almost nonexistent unit type with many uses. (Flares are weak, cargo ships for the win. Also there's cargo ships IRL so...)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
This is kinda support naval. Also, can't mapmakers just make sure that all islands are in range of surge towers and mass drivers?

**Comment by Dioo0** [comment]
> This is kinda support naval. Also, can't mapmakers just make sure that all islands are in range of surge towers and mass drivers?

he said that mapmakers will be possible to make bigger maps with ocean

**Comment by Pers-Pluto** [comment]
> 
> 
> This is kinda support naval. Also, can't mapmakers just make sure that all islands are in range of surge towers and mass drivers?

It isn't support naval (in the RPG support way) because it doesn't support the combat units; and it opens up new possibilities for map makers, I'm not saying they can't put all the islands closer together.

**Comment by PickAPlayerNameFirst** [comment]
The idea is decent, but the cargo part is... Well. A bit useless.

**Check the bottom most part on how to deal with your problem.**

It says a t1 boat can carry 100 items, 
But 4 flares can deal with it easily. And it has faster speed.

Oh! See? Mobile batteries! I can't believe it we have a moving charger while we have the stationary 3x3 that **Stores the same amount of power than the T2 unit! **

The dock idea is real overpowered. Imagine it to be a second core. And is purely no technology needed, your items will just *bloop* out of nowhere to the core. 

And the real idea that makes it a literal abomination:
The t5 ship that distributes items to many sectors. Well, we have launch pads, why won't you use them? 

Also a huge ocean map is very possible in v6. **Go download mods.** It unlocks planets, water worlds and such tech and units.

**Comment by numer99** [comment]
I like your idea of cargo units!
it would be fun using them

**Comment by Pers-Pluto** [comment]
>It says a t1 boat can carry 100 items,
But 4 flares can deal with it easily. And it has faster speed.

Yes, but to match 24 boats, there needs to be 96 flares, which is worth 4 nucleuses. Also, flares need logic, boats wouldn't. Then again, that's only T1 boats, what about the higher tiers? (I didn't outline at which speed boats would move. How do you know flares would be faster?)

Boats would also have AI that is specialized on logistics almost purely. And that would be much more efficient that 90% of player-generated flare code.

Also again, this idea isn't _meant_ to be balanced, it's meant to just provide new ideas.

>Oh! See? Mobile batteries! I can't believe it we have a moving charger while we have the stationary 3x3 that Stores the same amount of power than the T2 unit!

And what about higher tier units? Do you have enough space to place large batteries on the islands in ocean-heavy maps? What if in the future one of the planets had huge ocean sectors? There being mods like this doesn't mean it won't happen in the base version as well.

>The dock idea is real overpowered. Imagine it to be a second core. And is purely no technology needed, your items will just bloop out of nowhere to the core.
>And the real idea that makes it a literal abomination:
The t5 ship that distributes items to many sectors. Well, we have launch pads, why won't you use them?

The normal dock needs to be connected to the core using conveyors and power nodes. The wireless one still needs energy & I only proposed it to make simulating that sector easier with the sector-hopping cargo ship, rather than simulating how much throughtput a normal dock can get to a core. It was only supposed to be used with that specific ship.

"Items blooping out of nowhere" into your core is _already_ what happens with launch pads, and launch pads are pretty much the only way to sync resources between sectors. Sector-hopping cargo ships can add some diversity to that, so launch pads wouldn't always be the necessary one solution that must fit all.

**Comment by numer99** [comment]
Why.
It's just a cargo unit

plus you need materials in the specific sector you are in to make a
launch pad.
the cargo unit can go between sectors.

**Comment by PickAPlayerNameFirst** [comment]
Well, this is still an idea btw, don't know if anuke approves that. 

We already have launch pads, and that's the only way to transfer resources. Don't add more ways. 

This is an idea that could be present in v7, so it could be implemented in the "Ocean-Ice world". Welp, its a good idea, but the flaws of it changes the technology of the present one that we have.

Maybe, an ocean tech specifically researched only for ocean world? 

If you want your idea come true, then download mods.
