### ISSUE TITLE
Processor input

### ISSUE THREAD

**Issue by Wh4tev3r** [Anuken/Mindustry-Suggestions#2290]
**Describe the content or mechanics you are proposing.**
Adding more input to logic processor so logic processor can get more useful information to show or process

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Make logic more complicated and useful

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
"More input" is vague and not helpful. This suggestion doesn't inspire any ideas for what other information processors could be made to sensor. We surely weren't considering going in the other direction with "less", so this suggestion didn't need to exist.

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More Processor Inputs before. This is a revelation. I would never have thought of adding More Processor Inputs myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Processor Inputs immediately."

**Comment by SMOLKEYS** [comment]
> Adding more input to logic processor so logic processor can get more useful information to show or process

i cant even understand what you mean

**Comment by PickAPlayerNameFirst** [comment]
> Make logic more complicated and useful
>
Nice issue. Make logic procs make more complicated. Complicating things that are already complicated are very creative. 
Make logic procs more useful. It's already useful as it is. 

Template is really NOT SO misleading. 

All I want to say is not the logic procs are the one who's complicating things, it's you. 


Please close this issue. This is real nonsense.

**Comment by Humanoid-X** [comment]
Okay. More processor input. such a clear explanation. Not vague at all. Let's make a PR for it. No further explanation, just more input.

**Comment by DeltaNedas** [comment]
more processor input like:
- /dev/random
- webcam raw video stream
- mouse movement deltas
- gui button
- anuke generator

**Comment by Kyllingene** [comment]
yes plz must make video steem in minsty plz

**Comment by PickAPlayerNameFirst** [comment]
> more processor input like:
> - /dev/random
> - webcam raw video stream
> - mouse movement deltas
> - gui button
> - anuke generator

This is the most clear and detailed comment I've ever seen in my life. 

It makes sense. I'm enlightened with your motivational speech.

**Comment by stoneRdev** [comment]
@DeltaNedas Don't forget file access, gps and http connections

**Comment by Humanoid-X** [comment]
@stoneRdev Don't forget IP tracking, microphone access, and arduino connection. >:-D

**Comment by Kyllingene** [comment]
@Humanoid-X Don't forget desktop shortcuts

**Comment by SMOLKEYS** [comment]
> Make logic more complicated and useful

Hmm, yes, people will use logic more because its more _harder_ to use. Smart.

> Adding more input to logic processor

...seriously? No specifications?

> logic processor can get more useful information to show or process

Logic can already show you about everything you need. What else do you still need anyways?

**Comment by ML-10** [comment]
@Kyllingene Don't forget discord messages and github inbox

**Comment by Kyllingene** [comment]
@ML-10 Don't forget the android / apple app stores

**Comment by PickAPlayerNameFirst** [comment]
Hey, please, anuke. Can we have these features? 

Computer Trash Bin. 
Android Built-in apps. 
350x400 screen resolution. 
Automatic 12 hour schematic deleter. 
3FPS graphics. 

To make the game USEFUL!

**Comment by ML-10** [comment]
@Kyllingene Don't forget the elevated terminal and full internet access

**Comment by Kyllingene** [comment]
@ML-10 Don't forget internal SQL databases with HTML/PHP frontends

**Comment by ML-10** [comment]
@Kyllingene Don't forget graphics adapter and printer ports

**Comment by Kyllingene** [comment]
@ML-10 I also need some Linux package integration

**Comment by ML-10** [comment]
@Kyllingene How about bluetooth and ssh integration

**Comment by SMOLKEYS** [comment]
Suggestor reading this going: ***why, what have i started***
