### ISSUE TITLE
Changing names of block for logic

### ISSUE THREAD

**Issue by An0yim0us666** [Anuken/Mindustry-Suggestions#2291]
**Describe the content or mechanics you are proposing.**
I think it was in the early v6 where you could change a block name (for example : "wall1 = w" or something) basicly changing the (logic) name of the blocks

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

it will help with large logic stuff if you have to connect 50 things to do all one function. 
It would make it a lot easier (another example:" your making a wall with a ton of turrets that take away a lot of power and you disable them untill an enemy is near (with use of logic))

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
suggeested before

**Comment by An0yim0us666** [comment]
> suggeested before

When

**Comment by MrDuck557** [comment]
you can use getlink to control multiple blocks

**Comment by An0yim0us666** [comment]
Ok...



But I'm asking for a feature to change the block name not to get a getlink tutorial

**Comment by DeltaNedas** [comment]
`set coolblock router1`
are you slow

**Comment by An0yim0us666** [comment]
Is it rlly that hard to explain something?
