### ISSUE TITLE
New Buff/Support Unit Category

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#2292]
**Describe the content or mechanics you are proposing.**
A new unit tree idea, doesn't have to be used, just a suggestion. I made a fully fleshed out tree from T1 to T5 based around buffing, supporting, or commanding other units.

**Tier one: The Bolster**
_The bolster is a small ground unit that assists other units in their assaults, a role which the entire tree shares. It can heal all units within a small radius of itself, and provides a tiny damage buff that can stack up to 5 times. It also as a tiny shield around itself to protect it and its allies from damage, but due to the units low HP shield bypassing weapons will quickly take these out._

HP: 75
Weapon(s): None
Abilities: Heal Aura (5 hp/s, range 2 blocks)-Shield (75 hp, range 3 blocks)

**Tier 2: The Rally**
_The rally is a solution to the T2 units health problem, serving as a way from them to reach their goals, but not without counters or risks. It provides a unique buff that adds up to 5 T1-2 units health to its own, and renders those units un-killable. However, it takes damage whenever one of its units takes damage, and if killed all of its controlled units die. Units under its control from a formation similar to player induced unit control._

HP: 100 + (5 x T1-2 units max HP, if applicable)
Weapon(s): None
Abilities: Protective command (Adds to HP of 5 nearby T1-2 units, holds them in formation, range 5 blocks {N/A once cast})

**Tier 3: The Shaman**
_The Shaman is a defensive unit with a large shield and a damage buff affecting nearby units._

HP: 250
Weapon(s): 4x Duo
Abilities: Shield (750 hp, Range 10 blocks)Damage Boost (15% damage boost, Range 5 blocks, Doesn't stack)

**Tier 4: The Skald**
_The Skald is a mobile unit, weak on its own, but strong with its buff effects. It has fast speed, two Fuses, but its strength comes from its buffs that it gives to other units. It gives a speed buff to all units nearby, allowing them to keep up with it._

HP: 7000
Weapon(s): 2x Titanium Fuse
Abilities: Speed boost (Boosts all units nearby up to its speed, range 15 blocks)

**Tier 5: The Warlord**
_The warlord is a slow, medium HP unit that can command up to 5 of the highest tier units it can find, forcing them into formation around itself, and making them shoot at its target. The Warlord also gives a passive shield regeneration buff to all units within 25 blocks of it, letting them recover their shielding at a fast rate._

HP: 20000
Weapon(s): 4x Thorium salvo, 1x graphite Spectre
Abilities: Passive Shield Regen (Passively regenerates 100 health or 50 shields for all unit nearby, cannot go over shield HP maximum, range 25 blocks)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Adding more unit trees is a given in my opinion, but I just wanted to put an idea out there to make things easier, whether it actually gets used, is inspiration, or just ignored.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Too much overlap with the Nova line, and ground units already have 3 trees.

**Comment by Kyllingene** [comment]
So you want more ground support? How about you just get creative with currently available means?

[A very good Extra Credits video](https://www.youtube.com/watch?v=jVL4st0blGU) on depth vs. complexity. Please watch.

**Comment by ShadeStrike62** [comment]
> So you want more ground support? How about you just get creative with currently available means?
> 
> [A very good Extra Credits video](https://www.youtube.com/watch?v=jVL4st0blGU) on depth vs. complexity. Please watch.

wow, I am fully aware of the difference, it is just an idea. The community doesn't have to shoot down everything with flaws in it, do they?

**Comment by ShadeStrike62** [comment]
> Too much overlap with the Nova line, and ground units already have 3 trees. However, anyone is free to make mods.
> 
> * T1 Nova already heals allied units
> * T2 Quasar regens unit shields
> * T3 Pulsar already provides a mobile force field

true, any suggestions as to how to change it?

**Comment by Kyllingene** [comment]
> wow, I am fully aware of the difference, it is just an idea. The community doesn't have to shoot down everything with flaws in it, do they?

My point is that this is unnecessary. All this would do is make players do more deciding and less thinking. The idea itself is not flawed, but the thought process leading to the addition of this would be. Sure, the unit tree would be cool, but to reiterate: it brings nothing (or very little) to the game. This idea is cool, but would not bring new gameplay, especially as it is so close in features to the existing support units.

**Comment by ShadeStrike62** [comment]
> > wow, I am fully aware of the difference, it is just an idea. The community doesn't have to shoot down everything with flaws in it, do they?
> 
> My point is that this is unnecessary. All this would do is make players do more deciding and less thinking. The idea itself is not flawed, but the thought process leading to the addition of this would be. Sure, the unit tree would be cool, but to reiterate: it brings nothing (or very little) to the game. This idea is cool, but would not bring new gameplay, especially as it is so close in features to the existing support units.

i think the problem isn't that the game doesn't need new units, but more another ground tree isn't needed at the moment

**Comment by Kyllingene** [comment]
I never said that the game had all the units it needed, but simply that this particular tree is simply extraneous.

**Comment by ShadeStrike62** [comment]
> I never said that the game had all the units it needed, but simply that this particular tree is simply extraneous.

true, I see the overlap

**Comment by Kyllingene** [comment]
Long-range units for Naval exist, and naval assist in capturing strongpoints on the map.
