### ISSUE TITLE
Export tech tree info to automatically generate visual representation of the tech tree?

### ISSUE THREAD

**Issue by MikeTheGreat** [Anuken/Mindustry-Suggestions#2293]
Currently the official Wiki is generated from the source code.  It would be great to easily translate the tech tree into a different format (XML? JSON?) so that we could automatically transform it into other, useful visual representations (such as a nice graph app).  I'm hoping that since the Wiki is already auto-generated it wouldn't be too hard to generate a list of all the things in the game, including the pre-requisite for building each one.

As a new-ish player there's a pretty overwhelming number of options in the tech tree.  It would be nice to be able to import that into something like [GraphViz](http://graphviz.org/) to generate easier to use UIs for figuring out what I'd like to make in the game

Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.  **Done!**

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.  (Specifically, I search all issues, open or not, for 'tech tree')
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3.1 - [] I am familiar with all the content already in the game - hahahahaha.  *cough* sorry, I'm trying as best I can but it's going to be a while before I can truthfully check this off :)
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Regardless, thank you for an awesome game!  Mindustry rocks!

**Comment by stoneRdev** [comment]
If your looking for a way to export your current tech tree, I can't really help. Buuuut, if your looking for just like a JSON of all the techs, I can probably make you one.

**Comment by stoneRdev** [comment]
Ha, actually, I found a spreadsheet of the tech tree. I'm not sure how up to date it is, but a quick glance says it's all there. [It was on the wiki entry for tech tree](https://docs.google.com/spreadsheets/d/1F6FrK9uqxhfcfvGHXcq3wGOyyHxzOPlp2U1Nxz7YrA4/edit#gid=1680377512)

[If you need it as JSON](http://blog.pamelafox.org/2013/06/exporting-google-spreadsheet-as-json.html)
[If you want some other format, use export](https://sites.google.com/a/temple.edu/googleapps1/tip-of-the-day/april28-exportagooglespreadsheetintovariousformats)

Hope that helped

**Comment by Kyllingene** [comment]
Here is the [Tech Tree source code], I'll try to make some sort of parser. That way you can have up-to-date tech trees. By the way, did you need resource costs? That would be a little tricky, but doable.

**Comment by MikeTheGreat** [comment]
First up - I'm very sorry about dropping this.  I thought I set up my notifications correctly so that GitHub would tell me when comments are made, but apparently I didn't.

So on that note - thank you very much @stoneRdev and @Kyllingene for your super quick replies!  

I think what I'm actually looking to do is to create a dependency graph of what one needs to build in order to construct and supply various blocks.

I was thinking of using something like GraphViz to create the graph, which might visually resemble this: https://www.graphviz.org/Gallery/directed/psg.html (this is for a state graph, but the idea of left-to-right arrows showing details of each block, and the arrows showing what you have to make first, is what I'm going for).

I started manually doing this with Diagram.net:  https://drive.google.com/file/d/1dTuqGCHHa7q5DwTYgU6mmA6j5-4mrHak/view?usp=sharing

It looks like the Tech Tree source code defines the tech tree as a graph (which could be used to go through all the blocks, units, etc), and then if the full info for each block was available one could generate the dependency graph of what order things would get built in.

Does this all make sense?
