### ISSUE TITLE
Mechanical Pump Block Status

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2294]
**Describe the content or mechanics you are proposing.**

Add a block status indicator to mechanical pumps. Green when producing, yellow when not producing due to full pipes.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

especially in large early-game water networks, makes it easier to tell when it is possible to add more liquid consumption. Also matches the trend set by mechanical and pneumatic drills, which use the same conditions for their status indicators.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
This feature is already in the game.

Press F6 on desktop, or enable the game setting on mobile.

**Comment by oinkymoo** [comment]
I am referring to mechanical pumps, and no they do not
<img width="201" alt="Screen Shot 2021-04-12 at 10 10 26 PM" src="https://user-images.githubusercontent.com/75851043/114485747-7602c180-9bda-11eb-88ea-b24fc68f9415.png">

**Comment by joshuaptfan** [comment]
Hmm, that is an odd omission.

**Comment by itcannotbe** [comment]
Probably a bug.

**Comment by MEEPofFaith** [comment]
> Hmm, that is an odd omission.

it might be because mechanical pumps don't consume anything, while the others consume power.

**Comment by oinkymoo** [comment]
> > Hmm, that is an odd omission.
> 
> it might be because mechanical pumps don't consume anything, while the others consume power.

but the mechanical and pneumatic drills don't consume anything either, and yet they still have indicators

**Comment by MEEPofFaith** [comment]
they do consume something
power

**Comment by MEEPofFaith** [comment]
drill != pump

**Comment by itcannotbe** [comment]
Probably an indicator on a 1x1 would look stupid.

**Comment by itcannotbe** [comment]
> > > Hmm, that is an odd omission.
> > 
> > 
> > it might be because mechanical pumps don't consume anything, while the others consume power.
> 
> but the mechanical and pneumatic drills don't consume anything either, and yet they still have indicators

They do, just optionally.

**Comment by joshuaptfan** [comment]
> Probably an indicator on a 1x1 would look stupid.

Block status indicator on 1x1 blocks is already supported, just look at batteries, pulverizer, etc. It is shrunk down to be less obtrusive.

This comment makes me wonder if you actually play the game...

**Comment by itcannotbe** [comment]
Ooof. Forgot about those.

**Comment by itcannotbe** [comment]
But still weird why mechanical pump is still left out.
