### ISSUE TITLE
Disassembler revamp (buff) 

### ISSUE THREAD

**Issue by PickAPlayerNameFirst** [Anuken/Mindustry-Suggestions#2295]
**Describe what you would like changed, and why.**

All I'm focused on making issues and pull requests right now are block buffs and nerfs. 

Disassembler. A very expensive building almost made by the same ingredients as a foreshadow (**250 surge alloy build cost**) and poops trash onto your face. 

I would like to give it a revamp. Since its a late game building, the outputted items are also late game and rare. 

Since scrap is a piece of a ruined ancient building, and can contain anything, this could be the alternative items for the disassembler. 
- Thorium, probability, 4.
- Metaglass, probability, 3.
- Silicon, probability, 2.
- And Plastanium, probability, 1.

I've seen and read the code probability of the disassembler, and it outputs nonsense items. 

- Sand (probability, 4). Well, what's the use of the pulverizer? 
- Graphite (probability, 2). It's a stolen item that is already produced by separators. 
- Titanium (probability, 2). Already produced by separators. 
- Thorium (probability of 2). Oh come on, you could just make a laser drill and _you will surely get more items_.

**Calculation**

This balance issue has been carefully **and painfully** been calculated. 

The effects that's made here is shown below. Remember, the first statistics shown here is the old technique to get the desired items using scrap. And uses are at maximum efficiency. **For the conversion rate mechanic explanation, its basically how much scrap will turn into the desired item, eg. 75:1,_75 scrap will turn to 1 phase fabric_**.

- Thorium. 0.8/s, conversion rate is 3:1.
- Metaglass. 0.3/s, conversion rate is 22:1.
- Silicon. 0.75/s, conversion rate is 8:1.
- Plastanium. 0.2/s, conversion rate is 38:1.

**New rates (if the revamp is approved)**

-Thorium. 1.6/s, conversion rate is 2:1.
- Metaglass. 1.2/s, conversion rate is 6:1.
- Silicon. 0.8/s, conversion rate is 8:1.
- Plastanium. 0.4/s, conversion rate is 20:1.

Now this revamp became a math class, but this adjustment could make the disassembler **prove that its a late game building.**

I could say that the build cost is okay, the input liquid and input item is good, and the power consumption is decent. 

If there are any flaws in the data provided, feel free to comment it down below. 

This balancing idea has NOT been suggested before. I need your suggestion and your opinion, if everyone agrees with this issue, then I'll make a pull request for it.

**Comment by itcannotbe** [comment]
Scrap to anything else but sand isn't meant to be practical nor efficient.

**Comment by joshuaptfan** [comment]
Scrap is ruined ancient buildings, not player buildings. It doesn't have to be made of the same resources as player buildings.

**Comment by PickAPlayerNameFirst** [comment]
> Scrap to anything else but sand isn't meant to be practical nor efficient.
> 
> Also why on earth would scrap yield items crafted from multiple items/liquids? Graphite, I can understand (You just feed coal through a block, Graphite! Magic!). Anything is stupid.

I just meant THIS specific building to give SPECIFIC and USABLE items.

And also, its **so inefficient for a late game building.**

**Comment by PickAPlayerNameFirst** [comment]
> Scrap is ruined ancient buildings, not player buildings. It doesn't have to be made of the same resources as player buildings.

Thanks. I'll edit it.

**Comment by BlueWolf3682** [comment]
> Scrap is ruined ancient buildings, not player buildings. It doesn't have to be made of the same resources as player buildings.

Yes, they actually are due to things like doors in ruins being made of the same materials as the doors you place.

**Comment by itcannotbe** [comment]
The only difference between a separator and a disassembler is the ability to make thorium and it runs faster. That's it. It wasn't meant to be a magic building that can be a game changer in the late game.

**Comment by itcannotbe** [comment]
> > Scrap is ruined ancient buildings, not player buildings. It doesn't have to be made of the same resources as player buildings.
> 
> Yes, they actually are due to things like doors in ruins being made of the same materials as the doors you place.

This isn't the place to be discussing lore.

**Comment by joshuaptfan** [comment]
The disassembler's purpose is to allow players access to a trace amount of thorium in maps where thorium is otherwise unavailable. That's it, everything else it outputs is _supposed to be_ basically trash.

It requires acquiring thorium by some other means beforehand, either by launching with it or deconstructing derelict blocks.

**Comment by PickAPlayerNameFirst** [comment]
> The disassembler's purpose is to allow players access to a trace amount of thorium in maps where thorium is otherwise unavailable. That's it, everything else it outputs is _supposed to be_ basically trash.
> 
> It requires acquiring thorium by some other means beforehand, either by launching with it or deconstructing derelict blocks, so that you can't get thorium from nothing.

250 surge alloys is a big problem cuz if you haven't captured the sector, then you would be doomed due to the lack of time gathering that resource.

**Comment by itcannotbe** [comment]
The disassembler is not a requisite block to finish the campaign.

**Comment by PickAPlayerNameFirst** [comment]
> The disassembler's purpose is to allow players access to a trace amount of thorium in maps where thorium is otherwise unavailable. That's it, everything else it outputs is _supposed to be_ basically trash.
> 
> It requires acquiring thorium by some other means beforehand, either by launching with it or deconstructing derelict blocks, so that you can't get thorium from nothing.

I would love to gather thorium using an airblast drill and add a watex in it even if its just a one vein of thorium. 
Still produces more items than that building.

**Comment by PickAPlayerNameFirst** [comment]
> The disassembler is not a requisite block to finish the campaign nor needed to capture every sector.
> 

Its still a building that's never used.

**Comment by RedstonerKBC** [comment]
> > The disassembler is not a requisite block to finish the campaign nor needed to capture every sector.
> 
> Its still a building that's never used.

For real.

**Comment by PickAPlayerNameFirst** [comment]
I'll just make it go boom, trash phase fabric maker. (0.15/s) 
![Screenshot_2021-04-13-11-14-38-527_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/79730516/114491668-8e5df500-9c49-11eb-8ec3-f646e6c4ab4c.jpg)

**Comment by itcannotbe** [comment]
> > The disassembler is not a requisite block to finish the campaign nor needed to capture every sector.
> 
> Its still a building that's never used.

It is used in custom maps.

Scrap challenge maps.

**Comment by PickAPlayerNameFirst** [comment]
> > > The disassembler is not a requisite block to finish the campaign nor needed to capture every sector.
> > 
> > Its still a building that's never used.
> 
> It is used in custom maps.
> Scrap challenge maps.

But in real gameplay?

**Comment by itcannotbe** [comment]
Are separators used in real gameplay?

**Comment by Awesomespore** [comment]
This would be way too overpowered, and besides, it creates "trace amounts of exotic MINERAL COMPONENTS" - i.e. raw materials.
Something like plastanium wouldn't make any sense since it's literally titanium with oil, and oil would burn away in the process of turning scrap into slag anyway. Silicon? It's a refined material, and it wouldn't really make much sense to pull something like that out of molten goo. And metaglass?... well I can't imagine pulling leaded glass out of a glob of mixed molten materials.

**Comment by PickAPlayerNameFirst** [comment]
Is sand exotic? 

Irl metaglass (glass) comes from molten materials. 

Silicon (silica) is present in lava or magma. 

In a highly advanced technology, it's very possible to recover items that were surged on extreme temperatures. 

Plastanium (plastic) came from oil, a natural occurring resource. The only difference in it to the game is it needs titanium to produce that resource. 

Heat up a plastic in a candle. It still has the components of a plastic. Cool down plastic, it will return to its original shape. 

Also, plastanium is not "wrapped" in oil,  
Did you see plastic burn, engulf thru flames, and spread farther? 

Raw materials are misleading once you talk about graphite. It's a processed material (in the game).

**Comment by PickAPlayerNameFirst** [comment]
> This would be way too overpowered, and besides, it creates "trace amounts of exotic MINERAL COMPONENTS" - i.e. raw materials.
> Something like plastanium wouldn't make any sense since it's literally titanium with oil, and oil would burn away in the process of turning scrap into slag anyway. Silicon? It's a refined material, and it wouldn't really make much sense to pull something like that out of molten goo. And metaglass?... well I can't imagine pulling leaded glass out of a glob of mixed molten materials.

Its just right, it should compensate from its late game cost. 

Imagine building a foreshadow, and building a disassembler. They have surge alloy build costs. 

A foreshadow kills and obliterates units and buildings from afar. 

A disassembler drains your power (by a bit) and eats some slag and outputs some more sht that most of it will be incinerated anyways.

**Comment by PickAPlayerNameFirst** [comment]
> Are separators used in real gameplay?
> 

Yes, in midgame. Many are making scrap-to-surge alloy schems and are super useful. 

Yes, in late game. Wanna impact reactor? But not much available resources? Ay! Try this schem and your life will be easier with this underrated machine that some people say its not used in real gameplays!

**Comment by PickAPlayerNameFirst** [comment]
Okay this issue will be closed in 3 hrs. due to it's OP ness. 

And also due to the faulty lunatic author who made this issue.
