### ISSUE TITLE
Cores are WAY too easy to research

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2296]
**Describe what you would like changed, and why.**
  *Currently, you can get the Core: Foundation in 4 sectors and the Core: Nucleus in 6. This is ridiculous. Cores are supposed to be milestones in your journey, not one of the earliest and easiest things to research.*

**Describe the changes you want to propose. Include possible alternatives.**
  ***Massively** increase the core research costs (maybe to 50% of the default research cost multiplier instead of the current 0.05% they are right now), and/or lock the cores behind sectors.*

**Comment by joshuaptfan** [comment]
Definitely, cores should be locked behind sectors.

**Comment by N4B3R1USNT** [comment]
Researching foundation with 100k copper and needs fungal pass captured?

~~then researching nucleus should cost 1M copper and 400k thorium to and npc captured?~~

**Comment by oinkymoo** [comment]
couldn't you get foundation in 3? do ground zero and frozen forest as normal, then unlock silicon smelter in craters, where there is sand and coal

**Comment by BlueWolf3682** [comment]
True, but 175 is great for getting it faster. I used a less tryhard example.

**Comment by joshuaptfan** [comment]
Foundation should stay as a moderately early unlock. Nucleus should take real effort.

**Comment by oinkymoo** [comment]
i don't think fungal should be the lock on foundation, it's an attack map, which are, in my limited experience, very difficult, which defeats the purpose of having them still be relatively early-game. I'd say lock it behind either stained mountains or windswept islands

**Comment by BlueWolf3682** [comment]
Fungal Pass sounds like an amazing idea for sector lockout, though a bit easy.

**Comment by oinkymoo** [comment]
fungal pass was, for me, the first map that felt like throwing myself at a brick wall. I've done about half a dozen attempts at it so far, and haven't even gotten close to the second core, when every other sector I've attempted has fallen within half that many

**Comment by BlueWolf3682** [comment]
That's why its a good idea
Beating attack maps requires a more rush based strategy, which helps you learn how to play the game a bit better.

**Comment by oinkymoo** [comment]
the problem I have is that, to me at least, attack maps feel like a mid-game thing. the early game is up until you get titanium, during the time where as long as you just, like, try, you will beat the map. after WI, you're dealing with high-threat maps if you want to progress in the campaign, and after SM, you have fungal pass, which requires a significant amount of strategy to complete. granting the first core after SM and/or WI would, in my opinion, be an excellent way to cap off the early game.

**Comment by octopuscaat** [comment]
if you cant get past a main secto then try capturing other lesser sectors and make them into a factory so you can research new things and then you probibly can beat it.
