### ISSUE TITLE
Add more campaign slots

### ISSUE THREAD

**Issue by supermegaOriginal** [Anuken/Mindustry-Suggestions#2297]
**Describe the content or mechanics you are proposing.**

add more campaign slots so that you can chose witch to play and have more campaigns to play (normal, modded, anything else like from your friend or when you do a speedrun or that kind of stuff)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Well... Modding is a thing and many players want to make a modded campaign, and if you (the player) want to do that you have to del the current campaign and start from zero and when new planets come out (v7) (or want to continue) it will take longer to complete the campaign and come to the point where you can continue. (hope you understand)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheRealIvyX** [comment]
settings > game data > import and export data

**Comment by Fipico2** [comment]
Only a small minority would use this, just export data

**Comment by Kyllingene** [comment]
> Well... Modding is a thing

Even if exporting data is too hard for you, if you are already modding, then just get a mod that makes it easier.

**Comment by SMOLKEYS** [comment]
Import/Export Data: Am i a joke to you?

**Comment by supermegaOriginal** [comment]
> settings > game data > import and export data

Wow...Why havent I thought about that...(im dumb XD)

**Comment by supermegaOriginal** [comment]
thx for solution :)
