### ISSUE TITLE
Waste Byproduct material, Recycler Building (v7)

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2298]
**Describe the content or mechanics you are proposing.**
A new material: production waste. Some buildings will now produce this as a byproduct. It doesn't always have to be factories that produce this. Maybe some power generation buildings produce this. Perhaps even certain weapons produce this, or maybe only if they take certain ammo? It's mainly meant for production factories.

A new building, the Recycler plant. Inputs waste products and outputs scrap metal. Slow, like the graphite press. Requires a decent amount of waste to produce 1 scrap metal.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Waste byproduct has little use other than to be a bit annoying. It makes the game a bit more challenging. You can always use the incinerator to get rid of waste. This material gives the incinerator block much more use, a block which currently is only ever used to burn unwanted separator/disassembler output. It isn't hard to setup incinerators.

The recycler's only purpose is to give a use to waste. Before you complain that this makes the game unbalanced, remember that the disassembler requires surge which requires thorium in order to build in order to get thorium from scrap. So you'd still need a source of thorium before getting the disassembler. The same goes for the separator but with titanium. So adding waste which can be converted into scrap doesn't break anything. It's not like the incinerator is an expensive block anyways. On top of that it outputs scrap slowly so it's not like you can easily farm thorium from waste byproducts.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
By the way, I did see a similar issue but it was specific to the thorium reactor: nuclear waste. Mine is a more generic idea applicable to potentially all buildings.

**Comment by MrDuck557** [comment]
You just made buildings harder to understand and everything more complicated.

**Comment by Kyllingene** [comment]
I'm sorry, but Mindustry is *not* the game for this. There are games (*cough cough* factorio *cough cough*) that are made for this sort of complication, but Mindustry is designed to be simpler.

**Comment by itcannotbe** [comment]
Actually nuclear waste from reactors was once on the trello at somepoint which would be supposed to be useful. But waste because waste is just annoying.

**Comment by Kyllingene** [comment]
I agree that nuclear waste would be fine, because those blocks have no other outputs. However, adding waste outputs to factories would require a new block type, and would also just be a general pain to deal with in-game. *Maybe* if Mindustry had designated output points, but that's just not happening.

**Comment by itcannotbe** [comment]
It's actually to deal with, sorters and incinerators should do the trick.

But it's unnecessary to be honest. Better not add it if it does not bring depth.

**Comment by Kyllingene** [comment]
Imagine having to put sorters on every factory you make. They aren't underused (they even have had to be nerfed), so it's not like they need more use cases. Sure, incinerators aren't used much, but should it really be a large game mechanic to destroy large amounts of resources? It seems wasteful (no pun intended) to add a new item that will be produced in large, just to delete it.

**Comment by itcannotbe** [comment]
If anyone is thinking of suggesting "an anything to scrap converter block". Please stop. It was already suggested and has been deemed overpowered/balancing issue.

**Comment by RedstonerKBC** [comment]
> Imagine having to put sorters on every factory you make. They aren't underused (they even have had to be nerfed), so it's not like they need more use cases. Sure, incinerators aren't used much, but should it really be a large game mechanic to destroy large amounts of resources? It seems wasteful (no pun intended) to add a new item that will be produced in large, just to delete it.

**Comment by RedstonerKBC** [comment]
Oops. Misclick. Sorry guys.

**Comment by RedstonerKBC** [comment]
> I'm sorry, but Mindustry is _not_ the game for this. There are games (_cough cough_ factorio _cough cough_) that are made for this sort of complication, but Mindustry is designed to be simpler.
> 
> [Great video you should watch in any situation](https://www.youtube.com/watch?v=jVL4st0blGU)

Anyways, like I was about to say before that happened :man_facepalming: No I haven't played factor.io yet and I definitely didn't intend Mindustry to be like it.
