### ISSUE TITLE
forshadow

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#2299]
**Describe what you would like changed, and why.**
when controling Forshadow or other units/turrets the screen should zoom out to the border of the unit/turrets range if it is larger than the max zoomed out screen.
.
**Describe the changes you want to propose. Include possible alternatives.**
the player can see more of what they are aiming for, maximizing the untapped potential that could be used, insted of fireing blindly, using surge alloy that could be used elsewhere.

**Comment by genNAowl** [comment]
Screen pan?

**Comment by Axzye** [comment]
Screen pan.

**Comment by octopuscaat** [comment]
as long as i can see what i am aiming at

**Comment by Mothership007** [comment]
This is already i  the game, you just need to bind it in the controls. The name of the action is screen pan. you can close this issue as it is useless because the content is already in-game
