### ISSUE TITLE
Steam multiplayer server using password

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry-Suggestions#23]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the underscores in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

- - -
Many players are need for this feature.
This could solve the indiscriminate ban of steam multiplayer.

**Comment by Katsute** [comment]
That's what the friend setting is for

**Comment by Kieaer** [comment]
@Katsute But many users still know that the server won't open unless you press Yes unconditionally.
