### ISSUE TITLE
Map editor feature to activate blocks

### ISSUE THREAD

**Issue by Ajan123** [Anuken/Mindustry-Suggestions#230]
**Describe the content or mechanics you are proposing.**
A feature in the map editor to turn on all the blocks. (eg. drills, generators, production blocks, etc.)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

When making attack or pvp maps, if a side is starting with generators or weapons, they often need to be tested to see if all production units are working as intended.  This would be helpful when building up teams other than yellow, since they cannot be tested by starting a custom game.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Wait. You know you can edit the map in game right? There, you can check on everything. I think.

**Comment by Ajan123** [comment]
You can, but it does not turn on factories.  The editor is only for you to place blocks.

**Comment by Remint32** [comment]
@Ajan123 You can enable console on F8 in any singleplayer session and run command `Vars.player.team(Team.crux)` (See the https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/game/Team.java class - all game teams are described there).
