### ISSUE TITLE
basalt/dark sand texture similarity

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2300]
**Describe what you would like changed, and why.**
It is very difficult to tell dark sand from basalt at a glance. changing the textures to be more visually distinct would improve readability, especially when you need it most when first arriving in a sector

**Describe the changes you want to propose. Include possible alternatives.**
use more distinct colors for basalt and dark sand. this could possibly be as simple as lightening the light gray accents on one tile and darkening them on the other. for a more extreme option, replace one with something else that differs significantly in texture, as well as possibly having a different name

**Comment by itcannotbe** [comment]
Duplicate of #1658

**Comment by joshuaptfan** [comment]
Please use the search function.

**Comment by Kyllingene** [comment]
> as well as possibly having a different name

What would the point of that even be?

**Comment by oinkymoo** [comment]
> > as well as possibly having a different name
> 
> What would the point of that even be?

in the event that the texture change makes the name "basalt" no longer make sense

**Comment by oinkymoo** [comment]
> Please use the search function before posting a new suggestion.

in my defense, I didn't try searching for dark sand because I assumed it would be too common, and that other person didn't know what basalt is

**Comment by Humanoid-X** [comment]
I'm crushed. You shouldn't assume us to be so stupid that we don't even know what basalt is. :-(

**Comment by oinkymoo** [comment]
> I'm crushed. You shouldn't assume us to be so stupid that we don't even know what basalt is. :-(

I didn't say that you don't know what basalt is. I said that @swenkeratmicrosoft, who opened issue 1658, did not know what basalt is called, and instead called it "dark 'not' sand".

**Comment by Humanoid-X** [comment]
Ok. Sorry I misunderstood. :-)

(It was supposed to be a joke;-) )
