### ISSUE TITLE
Bring back the 5.0 tutorial 

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2301]
**Describe what you would like changed, and why.**
This has already been suggested but I'm approaching this with clear and (hopefully) understandable points.

  Bring back the 5.0 method of tutorial instead of these *in-game hints*. The hints are not obvious enough or clear enough to help newer players, which leads to a lot of issues with the (sometimes toxic) community and the new players when the new players inevitably come to ask how the game works.

**Describe the changes you want to propose. Include possible alternatives.**
  Re-introduction of the full 5.0 in-game tutorial, with optional extra tutorials for:
1. Power: Activated when the power node is researched.
2. Liquids: Activated when the conduit is researched.
3. Units and commanding: Activated when the ground factory is researched.

  Possibly consider making the tutorial more idiot-proof than it was in 5.0 as well.

*Don't even bother mentioning how time-consuming re-implementing this would be, I already know.*

**Comment by oinkymoo** [comment]
I only got the game recently. how different is the 5.0 tutorial to the classic tutorial?

**Comment by BlueWolf3682** [comment]
The 5.0 tutorial is a full map that makes you do tasks before letting you proceed. That way, you are forced to learn how to play before you get into the real game.

**Comment by oinkymoo** [comment]
aight so pretty much the same general idea as the classic tutorial but less missable
