### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by theBrainIQ** [Anuken/Mindustry-Suggestions#2302]
**Describe what you would like changed, and why.**
Please update trello so that we can tell what is v4/v5/v6/etc.
This way when searching to see if these suggestions are implemented, or if they are not to be considered. 

**Describe the changes you want to propose. Include possible alternatives.**
Have multiple boards linked together so to use [Cosmoteer Trello](https://trello.com/cosmoteer) as an example where they have a suggestions board, a roadmap board, and a coming soon board. 
If you have hit your board limit can you partition the sections instead so we can see what versions they were for?

**Comment by Kyllingene** [comment]
This seems rather useless imo. You can see what is on the roadmap/coming soon by simply looking at the Trello, and the "suggestions" part is this repo, which you have made a suggestion on. So, please explain why we MUST know what is planned for v7 as opposed to v8? Why do you assume that this solo dev even has a specific version he intends to implement everything in?

**Comment by itcannotbe** [comment]
Plus the trello is updated every now and then.

**Comment by XenonLog01** [comment]
It's updated as Anuke works, in order for him to know what needs to get done, and what is done. It's made for his convenience, not ours.
