### ISSUE TITLE
improved sector numbering

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2303]
**Describe what you would like changed, and why.**
it is currently very difficult to find sectors by number. while there are currently some sets of consecutive numbers that are connected, there are frequently large jumps between one sector and the next. my suggestion is to change the numbering of sectors so that every sector directly neighbors the sectors with numbers 1 above and 1 below itself.

**Describe the changes you want to propose. Include possible alternatives.**
the simplest solution would probably be to just redo the numbering of existing sectors, pretty much from scratch, though that would require a lot of work on behalf of the community to deal with the new numbering. a more extreme alternative would be to move the existing sectors into numerical order, though that would probably have to wait until after some sort of campaign reset, because of sector neighbors being completely different.

**Comment by itcannotbe** [comment]
I think you forgot that the shape are HEXAGONS not SQUARES.

**Comment by Polpo002** [comment]
also just a name search bar would be ok I think

**Comment by Kyllingene** [comment]
If you could find a mathematical formula to make every numbered tile on a hexagonal polyhedron adjacent to its neighbors on the number line, you would win a Nobel Peace Prize.

**Comment by Humanoid-X** [comment]
Wow. Your math is so good.

**Comment by Humanoid-X** [comment]
Let's take 13 as an example, now you are telling me that there are six numbers that is +-1 number to 13.

**Comment by Humanoid-X** [comment]
Not even imaginary numbers can do this job...

**Comment by Polpo002** [comment]
best I (and maths) can do is to do a spiral thing with numbers so that as long as you know where 0 is you can kind of try to search the sector, but a search bar would be easier

**Comment by Kyllingene** [comment]
Yeah, at that point it doesn't help much.

**Comment by oinkymoo** [comment]
> I think you forgot that the shape are HEXAGONS not SQUARES.

how??? is that relevant?

**Comment by oinkymoo** [comment]
> If you could find a mathematical formula to make every numbered tile on a hexagonal polyhedron adjacent to its neighbors on the number line, and no others, you would win a Nobel Peace Prize.

i only said that everything should be adjacent to its numerical neighbors, not that it shouldn't be adjacent to other numbers, where did you get that idea

**Comment by itcannotbe** [comment]
> > I think you forgot that the shape are HEXAGONS not SQUARES.
> 
> how??? is that relevant?

How is that irrelevant?

**Comment by oinkymoo** [comment]
> also just a name search bar would be ok I think

I agree that a way to just search for sectors by number or the name the player gave to them would also be helpful

**Comment by oinkymoo** [comment]
> > > I think you forgot that the shape are HEXAGONS not SQUARES.
> > 
> > 
> > how??? is that relevant?
> 
> How is that irrelevant?

how is the number of sides sectors have in any way relevant to my suggestion, as i have said, sectors only have to border the number above and below, and the other sides can have any numbers

**Comment by oinkymoo** [comment]
> best I (and maths) can do is to do a spiral thing with numbers so that as long as you know where 0 is you can kind of try to search the sector, but a search bar would be easier

yes, that's what i was thinking. it would at the very least be an improvement over the current layout

**Comment by Kyllingene** [comment]
Can you make an algorithm to number them so in-game?

**Comment by oinkymoo** [comment]
no but I can badly edit the map on the unofficial wiki. this will take me well into tomorrow though

**Comment by oinkymoo** [comment]
![better serpulo](https://user-images.githubusercontent.com/75851043/115162019-f4de7b00-a06e-11eb-9d55-0062482532f4.png)
this took far too long

**Comment by Polpo002** [comment]
wow gg
