### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#2305]
**Describe what you would like changed, and why.**

when placing the same block on a block with a different team it should update the team

**Describe the changes you want to propose. Include possible alternatives.**
for convenence

**Comment by MHeMoTexHuK** [comment]
There's already a "draw teams" mode which allows you to change the team of the blocks
![IMG_20210415_224113](https://user-images.githubusercontent.com/69920617/114929232-34715100-9e3c-11eb-9ed5-6446f754da08.jpg)

**Comment by Kyllingene** [comment]
Close?

**Comment by itcannotbe** [comment]
If only this was made using feature request instead of balancing/feedback......
