### ISSUE TITLE
Satellites, Asteroids, and Spacecraft

### ISSUE THREAD

**Issue by ASlightlyOvergrownCactus** [Anuken/Mindustry-Suggestions#2306]
**Describe the content or mechanics you are proposing.**
With the 7.0 update planning to have a solar system, I think it would be pretty neat to have a few things to make it more interesting and add some new challenges. 
1. Satellites: Quite like sending a new core to a new sector, once researched and the proper advanced materials are acquired one could build different satellites at different points of interest like the planet as a transport station or maybe even a super weapon, or an asteroid with some rare/possibly new materials to collect.
2. Asteroids would be smaller than planets, with only a few sectors to explore. They could have new environmental challenges such as low gravity, where you would need special transportation systems and drills, and they could have rare or new materials needed to progress to another planet or building. There could also be enemy bases on asteroids, with their own mining operations or special super weapons that the player needs to take out.
3. Spacecraft: A new factory, the spacecraft factory, could build special units that excel in space, where they could do various things, such as a freighter to take resources between worlds, an assault ship to assault an asteroid or enemy satellite, or a mining vessel that can mine ore extremely well.  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think all of this would add a nice in between to learn before taking off to another planet, with possible new prosperous turrets or machinery using new space materials. This could also be combined with Cmonster820’s idea on Space battles and space units, to give a really neat experience in space.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by funkychicken493** [comment]
very good quite swell

**Comment by XenonLog01** [comment]
I like the idea. I think the devs have made a point of being hesitant to add new resources, though and it would be an enormous overhaul to and enormous overhaul to an enormous overhaul, so if it's added, it will likely be in v8.

**Comment by XenonLog01** [comment]
I like the idea. I think the devs have made a point of being hesitant to add new resources, though and it would be an enormous overhaul to and enormous overhaul to an enormous overhaul, so if it's added, it will likely be in v8.

**Comment by ShadeStrike62** [comment]
> I like the idea. I think the devs have made a point of being hesitant to add new resources, though and it would be an enormous overhaul to and enormous overhaul to an enormous overhaul, so if it's added, it will likely be in v8.

think there is onky one dev, anuke

**Comment by theBrainIQ** [comment]
> think there is only one dev, anuke

Kinda true but he also has contributors so like yes but no

**Comment by itcannotbe** [comment]
> > think there is only one dev, anuke
> 
> Kinda true but he also has contributors so like yes but no

Actually, no.
Anuke is the only dev.
Contributors aren't developers.

**Comment by AureusStratus** [comment]
i have suggested this already

**Comment by ASlightlyOvergrownCactus** [comment]
Oh shoot, sorry AureusStratus! I hadn’t seen your suggestion for asteroids. But adding on to the spacecraft unit idea up above, maybe there could also be different types of spacecraft, such as instead of just flying ones, there could be special low-g environment walking ones that are held to the ground by magnetic attraction with like magnets (and maybe each time they step a cloud of dust is propelled into the air as a neat particle effect or something cuz of the low-gravity)

**Comment by ASlightlyOvergrownCactus** [comment]
Adding on to the ground low-g unit idea, this could lead to like them having a second ability than just being assault units, with them having equipped special low-g drills that are very efficient. They could then automatically connect to like a low g-conveyor near where they are drilling and send the resources to the conveyor when they get drilled. I imagine like a big drilling unit would look kinda like a toxopid or another insect-like unit

**Comment by AureusStratus** [comment]
i mean they could work like the nivw were they can fly over the space titles

**Comment by ASlightlyOvergrownCactus** [comment]
That could work as well, the main reason i said it could be like a toxopid is because i think the dust flying off the ground would be really neat lmao

**Comment by ASlightlyOvergrownCactus** [comment]
Although then again that would give another reason for the nova being much better than the dagger
