### ISSUE TITLE
Payload bridge/tunnels and payload junction

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [Anuken/Mindustry-Suggestions#2307]
**Describe the content or mechanics you are proposing.**

Payload bridge/tunnels
A 3x3 payload bridge/tunnel that can transport units over building and terrain

Payload junction
A 3x3 payload junction that act as a bridge for two crossing payload units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Payload bridge/tunnel
I know that quad/octs can transport units/blocks
And the new payload mass driver can deliver to other payload mass driver

But payload bridge/tunnel can be an early block that can transport units over buildings and terrains and can be useful to factory blockage, walls blockage, cheaper than payload mass drivers (i know this payload mass driver will be expensive like massdriver), and small building such single line of coveyer/conduits.

Payload junction
This can be helpful when you seperated blocks and different type of units cause i don't like to be clogged with blocks in my units reconstructor with payload router.

If you can't add a payload junction i guess ill be fine with payload bridge/tunnel.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
An "early block" that is only useful once one can carry blocks via units? Which happens to only be very helpful mid- to late-game?

**Comment by joshuaptfan** [comment]
> A few things you shouldn't suggest:
> * Underground map layers
So tunnels are a definite no-go.

**Comment by itcannotbe** [comment]
Do we really even need to cross-over payload conveyors?

Plus payload conveyors are slower than units moving on their own.

**Comment by AdvintasAHAT86420** [comment]
But Mindustry Classic
The Tunnel Block is a Bridge of conveyer

**Comment by itcannotbe** [comment]
Tunnels in Mindustry classic works like magic.

**Comment by AdvintasAHAT86420** [comment]
That's what Payload bridge looks like in sprite but unfortunatly it will
never added
Thanks for appreciate to reply me

**Comment by AdvintasAHAT86420** [comment]
Can i Re-suggest This one i feel kinda lose hope when there is three
problems that i can answer
