### ISSUE TITLE
Dynamic shadows for units

### ISSUE THREAD

**Issue by NightOmega** [Anuken/Mindustry-Suggestions#2309]
**Describe the content or mechanics you are proposing.**

since the game got planets and day and night then why not adding dynamic shadows for units 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

two words: more realistic

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Would be cool if the shadows appeared in different places based on where on the planet the map is.

**Comment by Kyllingene** [comment]
Not only did you fail to fulfill the basic requirements of the template, but you also failed to think about this. Calculating a shadow for *every single unit on the map* would be ridiculous, and it would be impossible for mobile even on a small scale. Infeasible.

**Comment by itcannotbe** [comment]
> since the game got planets and day and night then why not adding dynamic shadows for units

Let me install an appropriate desktop grade graphics card on my mobile device first.

> Would be cool if the shadows appeared in different places based on where on the planet the map is.

But the planet size and shadow casting position has 0 correlation with each other.

**Comment by NightOmega** [comment]
> Not only did you fail to fulfill the basic requirements of the template, but you also failed to think about this. Calculating a shadow for _every single unit on the map_ would be ridiculous, and it would be impossible for mobile even on a small scale. Infeasible.

okay i did fail the basic requirements of the template bec. i would n't lie...second thing is a graphic option for those who have a low quality computer or phones that cannot handle the lag

**Comment by Kyllingene** [comment]
So why didn't you bother to check? You don't seem to be too busy, as you are responding. Thus, why didn't you check? And again, this is still a humongous amount of work relative to the actual gain. It would be nice if it could exist, but it is simply unreasonable.

**Comment by NightOmega** [comment]
> So why didn't you bother to check? You don't seem to be too busy, as you are responding. Thus, why didn't you check? And again, this is still a humongous amount of work relative to the actual gain. It would be nice if it could exist, but it is simply unreasonable.

maybe it will not exist because anuke seems to be busy already

**Comment by RedstonerKBC** [comment]
> Not only did you fail to fulfill the basic requirements of the template, but you also failed to think about this. Calculating a shadow for _every single unit on the map_ would be ridiculous, and it would be impossible for mobile even on a small scale. Infeasible.

Dude chill. Not everyone is a programmer.

**Comment by Kyllingene** [comment]
I recognize this, but just think about how many units you can have with just one core. You can imagine that calculating a shadow for each one could be problematic, even without any programming experience.

**Comment by Akaricchi** [comment]
That depends on how you implement it. A simple fake shadow can be as inexpensive as drawing the sprite itself.
