### ISSUE TITLE
Mod incompatibility checker

### ISSUE THREAD

**Issue by Lucas559-noob** [Anuken/Mindustry-Suggestions#231]
Some mods may crash when starting the game

With the checker, it will start the game with mods disabled, and when you start the game on the menu, it will show incompatible mods and will disable incompatible and activate compatible mods, and show what is the problem with the incompatible mod

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
The game already shows issues that occur during mod loading, *when the error can be handled*. In many cases, it can't, and that's usually not a problem of compatibility.
