### ISSUE TITLE
Isometric Lines

### ISSUE THREAD

**Issue by Doublecoininfinity** [Anuken/Mindustry-Suggestions#2310]
**Describe the content or mechanics you are proposing.**
In the editor, for the line feature, an isometric line feature would be nice, instead of just orthogonal. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Will make building maps SO MUCH EASIER. I'm on mobile, and with these thumbs, it's hard to build a precise line for diagonal walls or such. I have to place each tile myself.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I just don't get any points of the suggestion nor the suggestion itself

**Comment by Doublecoininfinity** [comment]
> I just don't get any points of the suggestion nor the suggestion itself

Well, orthogonal lines can only really form squares with 2 orientations or angles, but isometric lines can have, I think... 8 orientations allowing for more complex structures, but not complex enough to make you struggle to align it exactly how you want to.

**Comment by itcannotbe** [comment]
That doesn't even make sense.

Tiles don't even have height and the game is played top down, I don't see the benefit of changing the perspective you use in editing a map.

**Comment by Kyllingene** [comment]
> I just don't get any points of the suggestion nor the suggestion itself

Well, that's because there are more than 2. In fact, there are 16.

**Comment by Doublecoininfinity** [comment]
> > I just don't get any points of the suggestion nor the suggestion itself
> 
> Well, that's because there are more than 4. In fact, there are 16. Anyway, I believe they meant more angles, such as 45 degrees, but phrased it incorrectly.

Thx for explaining

**Comment by itcannotbe** [comment]
Oh, that's what you mean, you want a helping hand in drawing diagonal lines.........

**Comment by Kyllingene** [comment]
For future reference: [Isometric (Wikipedia)](https://en.wikipedia.org/wiki/Isometric)

Duplicates:
#1695 #807 #495
