### ISSUE TITLE
Same use for different mod items

### ISSUE THREAD

**Issue by NightOmega** [Anuken/Mindustry-Suggestions#2311]
**Describe the content or mechanics you are proposing.**
 Same use for different mod items

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

 It will make the same use of the same item/material in vanilla or other mods example of that if i got Mod A and Mod B and A,B adds new content A,B.. A add iron forge and both add iron ore so if we made the modded iron forge read and understand that both is iron ore the result would be great

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
That is up to the mod authors, not Anuke.

**Comment by Kyllingene** [comment]
Yeah, it is already possible for a mod to use another mods resources. And if you want to use two mods, neither of which support the other, then you can download a "bridge" mod which would make them acknowledge each-other.

**Comment by IVV-NCX** [comment]
So, what you're saying is, "Mod A adds iron, and so does mod B. Make both items be read as a iron, instead of iron [mod A] and iron [mod B]". 

Anuke can't do that, it involves altering the source code. Get a bridge mod.

**Comment by NightOmega** [comment]
ok ok its bridge mod then
