### ISSUE TITLE
[v7] Control scheme for moving units into payload blocks

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry-Suggestions#2312]
**Describe the content or mechanics you are proposing.**

[The currently tested control scheme](https://discord.com/channels/391020510269669376/513178557653188609/832747008678297600), Ctrl-click, requires players to know that the unit must be positioned over the payload block. Even players who know how to do it correctly will sometimes fail because the unit's center is not within the bounds of the payload block they clicked on.

I propose a more intuitive, self-teaching method requiring less precision: When the player unit is over a payload block, a context-sensitive prompt will appear, and they can press a key to enter the payload block they are over.

# Desktop control scheme
In this mockup, I am using the same "Control Units" keybind as is being tested. The action should be triggered on key up, so that the keybind can still be held to perform its normal functions.

![Payload block enter desktop](https://user-images.githubusercontent.com/15149002/115100581-6644ef00-9ef2-11eb-8f3d-a27453b0d5e0.png)

# Mobile control scheme
On mobile, when the player unit is over a payload block, a button will appear somewhere on screen (in this mockup, above the placement menu) that they can tap to enter.

![Payload block enter mobile](https://user-images.githubusercontent.com/15149002/115100662-e53a2780-9ef2-11eb-9a9f-bbe39b103cc3.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This control scheme is easier to learn, easier to use, and avoids assigning yet another functionality to mobile double-tap.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
How about long press?

Cause mobile UI is already cramped enough.

**Comment by SMOLKEYS** [comment]
> How about long press?
> 
> Cause mobile UI is already cramped enough.
> 

Or how about shrinking the button and adding a sprite on it which replicates the payload conveyor?

It could look like this:
![button.png](https://user-images.githubusercontent.com/75618732/115101777-81a70d00-9f79-11eb-9351-54b2d787e10f.png)
