### ISSUE TITLE
Picking up air units with payload ships

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2314]
**Describe what you would like changed, and why.**
Pressing pickup key while the air unit is in range, and if your cursor is on it, will transport it in the hold. There can be an animation of the ship going lower and flying under the payload vessel.

*I am on mobile right now, so Xs wont load up, and I checked everything on other suggestions lists*

**Comment by Kyllingene** [comment]
> I am on mobile right now, so Xs wont load up

Actually, this template doesn't have X's.

Anyway, why do you need to pick up air units? That seems quite redundant.

**Comment by Polpo002** [comment]
I don't understand why though. do you have an example in which it would be useful? I have never felt the need of this feature tbh

**Comment by BorisA11** [comment]
@Polpo002 Carrying Zeniths through heavy fire with an Oct. Carrying Antumbras with Oct. Carryinf things in general wuith Oct.

**Comment by Kyllingene** [comment]
Have the units fly within the shield of the Oct.

**Comment by Humanoid-X** [comment]
Oct... is used to shield units.
Option 1. Press G
Option 2. Use logic.
