### ISSUE TITLE
Power System Revamp

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2315]
**Describe the content or mechanics you are proposing.**
Change how power is handled, produced, and maybe used.

Smarter power generators

• Power Generator auto shut-off
• Power Generator spool up and spool down time

When power produced is > 5% than power consumed. And starts back again if power produced is <  5% than power consumed. Determine per power grid

Spool up/down time and power produced is considered which generators to turn on/off.

Also gives batteries a constant use.

• Power negative mechanics
Certain types of blocks will stop working completely if power a power negative occures and will not start back up unless power negative is resolved.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Adds depth to power management.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
It took me a minute of re-reading to even understand this.

**Comment by Kyllingene** [comment]
Wait a minute, this seems familiar... almost as if there was a highly-anticipated feature, recently added, which allows controlling blocks, including power generators, in a sort of chain, automatically... an I think it was added so that overly complicated stuff like this can be left to the users... unfortunately, I cannot remember the name, so I guess I'll have to let it slide.

Incredible. Nobody has ever even considered suggesting More Easy before. This is a revelation. I would never have thought of adding More Easy myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Easy immediately.

**Comment by Humanoid-X** [comment]
@itcannotba That's one of the reason logic is added.
@Kyllingene What's "More Easy"?

**Comment by itcannotbe** [comment]
> @itcannotba That's one of the reason logic is added.

https://trello.com/c/lyeHJ7Y1

Clearly not done.

**Comment by itcannotbe** [comment]
> Wait a minute, this seems familiar... almost as if there was a highly-anticipated feature, recently added, which allows controlling blocks, including power generators, in a sort of chain, automatically... an I think it was added so that overly complicated stuff like this can be left to the users... unfortunately, I cannot remember the name, so I guess I'll have to let it slide.
> 
> Incredible. Nobody has ever even considered suggesting More Easy before. This is a revelation. I would never have thought of adding More Easy myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Easy immediately.

If fully implemented, this would add power management to the game as additional power wouldn't be instantly available. This would also lead to batteries being used more just a back up storage, as dips and spike of the power grid will be absorbed by batteries.

Please do not pick separate points of the suggestion as the suggestion is pointless if one point isn't implemented.

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by RealYeet** [comment]
Bump, not letting you die

**Comment by stuffyAI** [comment]
Just a reminder that the README got updated, bumping is no longer needed as Anuken would mark any suggestions he deems worthy not to be deleted.

**Comment by RealYeet** [comment]
Kk
