### ISSUE TITLE
core/launch pad arrival time

### ISSUE THREAD

**Issue by NightOmega** [Anuken/Mindustry-Suggestions#2316]
**Describe what you would like changed, and why.**
the time from launching point to the selected point (the time from point A to point B)

**Comment by Noob17** [comment]
I think what this guy meant to say was: 'The further away a launch pad is to another sector, the launch time increases or decreases.'
Not sure why this should be implemented.

**Comment by NightOmega** [comment]
noob17 that's what i should have said

**Comment by NightOmega** [comment]
> I think what this guy meant to say was: 'The further away a launch pad is to another sector, the launch time increases or decreases.'
> Not sure why this should be implemented.

if it implemented i would say it will add more realistic-y to the game
it doesn't make sense when you launching from top of the planet to bottom of it in seconds

**Comment by itcannotbe** [comment]
> **Describe what you would like changed, and why.**
> the time from launching point to the selected point (the time from point A to point B)

I don't understand the suggestion. And why this would be a good change to the game.

**Comment by NightOmega** [comment]
> > **Describe what you would like changed, and why.**
> > the time from launching point to the selected point (the time from point A to point B)
> 
> I don't understand the suggestion. And why this would be a good change to the game.

more realistic

**Comment by itcannotbe** [comment]
Here's something you didn't consider. If your sending out resources at a fixed rate, distance won't affect your resources delivery over time.

**Comment by joshuaptfan** [comment]
This suggestion makes no sense because:

1. For core launch, there is only a cutscene of the core landing. There only way to "show" the core launch taking time is to display a black screen, which doesn't show the player anything.
2. For launch pad delivery, see itcannotbe's above comment.

This suggestion attempts to apply realism to the game with zero consideration for, or benefit to, gameplay. Gameplay considerations should **always** come first, with realism added where possible for immersion only.

**Comment by NightOmega** [comment]
> This suggestion makes no sense because:
> 
> 1. For core launch, there is only a cutscene of the core landing. There only way to "show" the core launch taking time is to display a black screen, which doesn't show the player anything.
> 2. For launch pad delivery, see itcannotbe's above comment.
> 
> This suggestion attempts to apply realism to the game with zero consideration for, or benefit to, gameplay. Gameplay considerations should **always** come first, with realism added where possible for immersion only. I hope this style of poorly-thought out suggestion is not a pattern for you going forward, NightOmega.

since there is day and night cycle and core upgrades what i mean here how fast the core will arrive at the sector and it rendered on the planetery map
_imagine have your core flying in the planet map_
