### ISSUE TITLE
change ground units pathfind 

### ISSUE THREAD

**Issue by UnionofSovietSocialistRepublics** [Anuken/Mindustry-Suggestions#2317]
**Describe what you would like changed, and why.**
units always go to the shadow that was unbuildable which is annoying in custom map,, it need to be changed 

**Describe the changes you want to propose. Include possible alternatives.**
![unknown](https://user-images.githubusercontent.com/71920146/115144519-4985f400-a077-11eb-94a4-8faf8751e023.png)

**Comment by itcannotbe** [comment]
Reason being that's the softest part of every defense. Even PvP ers knows that's the weakest point.

**Comment by oinkymoo** [comment]
if you don't want them to do that build a wall around the map

**Comment by MEEPofFaith** [comment]
~~2 small walls is clearly weaker than 1 big wall~~

**Comment by itcannotbe** [comment]
> ~2 small walls is clearly weaker than 1 big wall~

~why didn't I noticed that~

**Comment by oinkymoo** [comment]
> ~2 small walls is clearly weaker than 1 big wall~

it is actually weaker, a large wall has as much health as 4 small walls, and also must be broken through all in 1 go, whereas you can break through 4 smalls a quarter at a time

**Comment by MEEPofFaith** [comment]
but if a single hit deals more damage than a single wall's health, then the large wall become stronger

**Comment by MEEPofFaith** [comment]
but those are complex calculations that the game can't take into account

**Comment by oinkymoo** [comment]
> but if a single hit deals more damage than a single wall's health, then the large wall become stronger

no i was saying that itcannotbe was right, the 2 smalls are in fact weaker
