### ISSUE TITLE
Planet contamination mechanic. 

### ISSUE THREAD

**Issue by kalviskalis** [Anuken/Mindustry-Suggestions#2318]
**Describe the content or mechanics you are proposing.**
Planet contamination mechanic, where one, if not careful enough, could contaminate V7 planets with spores. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This mechanic could come with new resources/materials exclusive only to uncontaminated planets that become unaccessible after contamination. One must follow certain procedures /spend extra resources upon interplanetary launches, or manually stop the spread on another planet. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
why would you need it
also, I don't think Anuke is adding new resources any time soon

**Comment by kalviskalis** [comment]
> why would you need it
> also, I don't think Anuke is adding new resources any time soon
It would be a new feature that could add extra things. 
Isn't V7 a relatively big update? I'm sure there are going to be at least a few new resources/final products added.

**Comment by Kyllingene** [comment]
> It would be a new feature that could add extra things.

That isn't a reason why, that's just a fact.

Anyway, the concept of having to be super careful or else you lose absolutely all access to certain materials, a mechanic that would aggravate more than a few people, is an odd one and one that Anuke is not likely at all to implement.

**Comment by numer99** [comment]
spores can't survive in those conditions (I think)
