### ISSUE TITLE
An idea for an improved campaign or campaign-style gamemode

### ISSUE THREAD

**Issue by robtech21** [Anuken/Mindustry-Suggestions#2319]
**Describe the content or mechanics you are proposing.**

This is kind of a campaign redesign/new gamemode idea that seems really fun for me. The idea might need a bit of polish but here's the whole gist of this idea:

* The entire campaign planet is on one map
* The planet is divided up into "chunks"
* Every sector fits inside of a chunk
* Every sector has an enemy base (or maybe on occasion be empty, bases will probably vary in size based on difficulty) and a set amount of enemy waves you have to defeat (just assume they come from adjacent sectors with bases in them)
* Each chunk would be the size of a standard map (or maybe less)
* You can't go into adjacent chunks until you've conquered the one you're in (by completing waves and maybe destroying the enemy base in the current chunk)
* You can build a core within a sector, which starts the invasion of the sector, when you're in another sector, it will make resources based on the sector production statistics at the time of you leaving (the lag would gradually increase if you just kept the chunk loaded for every sector with a core) 
* You can make "flying cores" so you can fly to farther away sectors (e.g. frozen forest, stained mountains, etc.)
* (unsure of this) units can be dropped off at other sectors via "dropship" units
* Cargo ships which will transport materials from one sector to another

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This type of gamemode would make the game seem less grindy (not having to make so many resources in one sector)
This would also appeal to me and possibly other people because it allows for a more open-world experience.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
How many incarnations of hosting/loading the whole planet do we need to see?

**Comment by IVV-NCX** [comment]
I see cargo ship, I hear launch pad.

**Comment by ASlightlyOvergrownCactus** [comment]
I like this as like a new game mode or even in v7, multiple of these for multiple planets, the only thing I'm worrying about is how much would be loaded in at once, so the game could be able to handle it (If not a lot of work might be needed to fix the issue)

**Comment by Mothership007** [comment]
When Anuke was developing v6, he considered adding supermassive sectors, that would be divided into chunks to save performance. That idea got shelved (not happening) on trello. Simulating an entire planet would be outright impossible on any reasonable phone or even 
on desktop.

**Comment by numer99** [comment]
Just play the 4.0 beta

**Comment by robtech21** [comment]
> When Anuke was developing v6, he considered adding supermassive sectors, that would be divided into chunks to save performance. That idea got shelved (not happening) on trello. Simulating an entire planet would be outright impossible on any reasonable phone or even
> on desktop. You can close this issue as your idea was shelved on trello.

Okay, thanks. Closing now.
