### ISSUE TITLE
Rework RTGs to be like a T3 Solar Panel

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#232]
**Describe what you would like changed, and why.**

Th-232 has a half life of **18 billion** years. Having to constantly resupply RTGs like a breeder reactor is silly.

They also make about **half** of what a thorium reactor makes in-game which is far too much. They're severely underused as each RTG requires its own fuel line and they make little power compared to an impact or even a few thorium reactors.

**Describe the changes you want to propose. Include possible alternatives.**

I propose lowering the output to about 80 p/s, removing the fuel requirement.
Additionally to make it less like a solar panel, over some time, maybe an hour, the fuel decays and it has to be rebuilt or efficiency suffers. Drones should be able to do this en-masse.

**Comment by itcannotbe** [comment]
I think a block that reduces it's power generation over time isn't a good fit for the game. Even if it's how it works IRL.

**Comment by potatoisagender** [comment]
Hmm. I think there is a simpler way of doing this, and that is to just make the needed input per second a lot less. Additionally, Anuke has stated multiple times that this game is not an accurate reflection of real world principles. Hence impact reactors.

**Comment by DeltaNedas** [comment]
Having it be a literal solar panel would be fine, decay is 1. very very short compared to the age of the universe and 2. just my shot at making it less bland

**Comment by jaygamer81** [comment]
a rtg takes **very** long to decay so no sry

**Comment by Anuken** [comment]
> Having to constantly resupply RTGs like a breeder reactor is silly.

Not any sillier than some of the other mechanics the game has.

> removing the fuel requirement.
> it has to be rebuilt or efficiency suffers

This seems like a bizzare mechanic to me; it uses no fuel, but the ""fuel"" can decay and you can't replace it? Why?

> far too much

If your goal is to make people use it more, I don't think lower power production is the way to go.

I'm all for making the RTG generator more interesting, but this isn't a good way to do it.
