### ISSUE TITLE
Ice units! [v7]

### ISSUE THREAD

**Issue by numer99** [Anuken/Mindustry-Suggestions#2320]
**Describe the content or mechanics you are proposing.**

A unit that can:
1. slide on ice
2. is naval unit and melts ice to go on top of it
3. is ground unit and freezes water to go on top of it
4. Shoots ice; freezing things temporarily

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This unit will be a unique part of the game
It will also probably be unlocked on this planet
(the blue one) **↓**
![screenshot 2021-04-18 at 5 04 25 PM](https://user-images.githubusercontent.com/65624340/115166467-2e5fb800-a068-11eb-9d2d-2643c147f761.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
There are currently no mechanics that can alter terrain during a game, and likely never will be due to resulting performance issues.

**Comment by numer99** [comment]
the unit makes a temporary particle that it can walk on
