### ISSUE TITLE
outdated material descriptions

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2321]
**Describe what you would like changed, and why.**
certain materials' descriptions in the research tree have become outdated, or are incorrect. update them to remove inaccuracies
**Describe the changes you want to propose. Include possible alternatives.**
The outdated things I've found so far:
Metaglass - "used in liquid distribution/storage structures" - it's also used in liquid generation now. distribution could refer to that but is rather vague
Titanium - "used in... aircraft" - titanium is used to produce exactly 1 t1 unit, the nova, which is a ground unit (it's also used in the multiplicative and exponential reconstructions, which can be used to create aircraft, but by that logic, silicon, metaglass, plastanium, and cryofluid are also used in aircraft)
phase fabric - "used in... self-repairing structures" - the only buildings that could be described as self-repairing are the mender and mend projector, and that is generally not what they are known for. 
water - "used for... waste processing" - the only waste processing structure is the incinerator, which does not use water

**Comment by Kyllingene** [comment]
Couldn't you make a PR?

**Comment by BlueWolf3682** [comment]
~~It's called a nova, not a mono.~~

**Comment by Kyllingene** [comment]
~Nova is a ground unit, not an air unit.~

**Comment by BlueWolf3682** [comment]
titanium is used to produce exactly 1 t1 unit, the mono, which is a ground unit

***ground unit***

**Comment by Kyllingene** [comment]
I am very good at ~mis~reading.

**Comment by itcannotbe** [comment]
Why can't I hit the mono with a lancer?

**Comment by Axzye** [comment]
Point still stands that the titanium description is inaccurate.

**Comment by SMOLKEYS** [comment]
> titanium is used to produce exactly 1 t1 unit, the mono, which is a ground unit
> 
> ***ground unit***

_inconsistent laughing in the bacoground_

**Comment by oinkymoo** [comment]
im sorry i was half-asleep when i wrote that will fix

**Comment by oinkymoo** [comment]
> Couldn't you make a PR?

i'm relatively new to github and don't know how. also even if I did I don't know what I'd actually change it to
