### ISSUE TITLE
Keybinds Customization!

### ISSUE THREAD

**Issue by ML-10** [Anuken/Mindustry-Suggestions#2322]
**Describe the content or mechanics you are proposing.**

A section in the settings menu that lets you customize keybinds (pause building, clear plan, planet map) and save / load keymaps.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think it will improve the game for people who rely on keyboard shortcuts and even people who have mouse side buttons (which I don't), they can bind those to useful functions.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
keybinds customization is already in the game? settings > controls

**Comment by Kyllingene** [comment]
They are asking for some more keybinds.

**Comment by ML-10** [comment]
> keybinds customization is already in the game? settings > controls

I did forget that existed but save / load keymaps would be cool
