### ISSUE TITLE
Add sector descriptions to tech tree

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#2323]
**Describe what you would like changed, and why.**
Add the descriptions of the sectors on hover in the tech tree to be consistent with all other items.
This might cover the screen on mobile, so a "read more" button, or something similar.

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by SMOLKEYS** [comment]
_Core Database_ > Sectors > Select a sector you need info with

**Comment by MEEPofFaith** [comment]
> _Core Database_ > Sectors > Select a sector you need info with

True, but tech tree also can give you item/block/unit descriptions, so why not sectors as well.
~~More places to cursed bundles to destroy~~

**Comment by Humanoid-X** [comment]
yes

**Comment by SMOLKEYS** [comment]
> ~~More places to cursed bundles to destroy~~

Now that i've seen this, i now agree with this suggestion.

**Comment by MEEPofFaith** [comment]
![image](https://user-images.githubusercontent.com/54301439/115466884-8a038000-a1e5-11eb-8674-74908c8ff6d6.png)
wait they already are

**Comment by MEEPofFaith** [comment]
![image](https://user-images.githubusercontent.com/54301439/115466929-98ea3280-a1e5-11eb-8105-92a9e0309be4.png)
unless you're talking about actually displaying it underneath the name

**Comment by Axzye** [comment]
yes, i am talking about that

**Comment by MEEPofFaith** [comment]
_I completely forgot about this._
