### ISSUE TITLE
Payload Drivers Shoot Like Turrets

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2324]
**Describe the content or mechanics you are proposing.**
Payload drivers be able to shoot like turrets, shooting either units or blocks at enemies, at the end of the payloads "bullet time" it will be placed into the world

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this would allow for strategic block launching and faster unit movement

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Payload driver ≠ BetaMindy's payload cannon.

**Comment by MEEPofFaith** [comment]
~~I feel like they'd just crash and explode instantly with the amount of velocity stuff is yeeted at~~

**Comment by itcannotbe** [comment]
Wouldn't this feel kinda OP, imagine launching units past the enemy defenses?

**Comment by MEEPofFaith** [comment]
surprise toxopid ++

**Comment by itcannotbe** [comment]
So if that's the case, the payload is destroyed upon hitting an enemy block?

**Comment by Kyllingene** [comment]
On top? How would that work?

**Comment by MEEPofFaith** [comment]
Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.

**Comment by Legomonster33** [comment]
> Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.

I presume that they are packed into payload packages, which can withstand high speed and impact

**Comment by Legomonster33** [comment]
> On top? How would that work?

On top would be for flying/walking units

**Comment by MEEPofFaith** [comment]
> > Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.
> 
> I presume that they are packed into payload packages, which can withstand high speed and impact

~~Have you not watched the gif?~~
![mach 5](https://user-images.githubusercontent.com/54301439/115340277-38161800-a15b-11eb-9ca4-fed96d422eab.gif)

**Comment by MEEPofFaith** [comment]
> > Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.
> 
> I presume that they are packed into payload packages, which can withstand high speed and impact

~~Have you not watched the gif?~~
![mach 5](https://user-images.githubusercontent.com/54301439/115340371-63006c00-a15b-11eb-9507-a3e43fec148d.gif)

**Comment by Legomonster33** [comment]
> > > Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.
> > 
> > 
> > I presume that they are packed into payload packages, which can withstand high speed and impact
> 
> ~Have you not watched the gif?~
> ![mach 5](https://user-images.githubusercontent.com/54301439/115340371-63006c00-a15b-11eb-9507-a3e43fec148d.gif)

yes but they get coated in nanotech protection so they don't disintegrate while flying

**Comment by Legomonster33** [comment]
or something it doesn't have to make perfect sense

**Comment by joshuaptfan** [comment]
You have an overactive imagination.

**Comment by itcannotbe** [comment]
> > > Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.
> > 
> > 
> > I presume that they are packed into payload packages, which can withstand high speed and impact
> 
> ~Have you not watched the gif?~
> ![mach 5](https://user-images.githubusercontent.com/54301439/115340371-63006c00-a15b-11eb-9507-a3e43fec148d.gif)

You forgot the caption of the GIF. 

> Effects are WIP

**Comment by MEEPofFaith** [comment]
I don't think changing effects would be related to the speed of it...

**Comment by itcannotbe** [comment]
I replied to the wrong message, let me fix that.

**Comment by darmaangelo** [comment]
> > > Anuke's gif made it look like those blocks/units are being yeeted at mach 5. Hitting the ground to destroy it.
> > 
> > 
> > I presume that they are packed into payload packages, which can withstand high speed and impact
> 
> ~Have you not watched the gif?~
> ![mach 5](https://user-images.githubusercontent.com/54301439/115340371-63006c00-a15b-11eb-9507-a3e43fec148d.gif)

damn it looks good
