### ISSUE TITLE
Make map editor 'Edit in game' be able to edit terrain

### ISSUE THREAD

**Issue by Liftyee** [Anuken/Mindustry-Suggestions#2325]
**Describe the content or mechanics you are proposing.**
Edit terrain in the 'Edit in-game' mode of the map editor

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Right now you can only edit terrain in the non-live map editor (not with the "edit in-game" mode). This makes making non-cheating (no sources) designs for Attack maps very inconvenient, as you have to do this:
build part of design --> think of what you need where --> leave in game editing --> place ores (hope you have a good memory!) --> build more of design
and repeat... (Bonus points for pain if you need to paste a schematic) 

We should be able to edit the terrain in the "Edit in-game" option as well as in the normal map editor, so it is less frustrating and time consuming to make compact designs in the editor for things like attack maps as you can place ores, water etc as you go. Could be done with an extra tab in the build menu, or a separate selector entirely. 

Thanks for reading!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
[It's being worked on.](https://discord.com/channels/391020510269669376/396416151032299521/822467990502113350)

**Comment by Liftyee** [comment]
nice
