### ISSUE TITLE
Launch Pad Arrival Timer

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#2326]
**Describe the content or mechanics you are proposing.**
A timer, probably displayed over the core, that displays when resources will arrive.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Just some way to tell _when_ I get my launchpad shipment stuff.

With some crude editing I created this image to demonstrate what I'm thinking.
![timer](https://user-images.githubusercontent.com/54301439/115302184-ffece600-a116-11eb-9db2-e0f47dba5193.png)

When it hits 00:00 I get my stuff and then it resets to however long it takes for launchpad stuff to arrive, which I think is 1 minute.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MEEPofFaith** [comment]
wait if it's just a minute then the minutes in the timer wouldn't be necessary.

**Comment by joshuaptfan** [comment]
Probably unacceptable as a permanently visible display. Should instead pop up when the core is clicked on, appearing below the core to not overlap with core inventory.

**Comment by MEEPofFaith** [comment]
or something in graphics settings

**Comment by joshuaptfan** [comment]
No, I'm saying that even if there is a graphics setting toggle for it, a permanently visible display is probably still not acceptable.
