### ISSUE TITLE
Item Landing Pads

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#2327]
**Describe the content or mechanics you are proposing.**
a landing pad that catches the incoming launches. or maybe able to specify which sectors launches to catch when they come in by picking a sector just like normal launchpads, outputting resources instead of recieving them when they arrive. an alternate way to link launchpads would be by an interger value(just a number or name) to further direct the launchpads. if the linked landing pad is still full of items and cant receive any, then the launchpad will not be able to launch items to it and so on.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
ive seen a lot of distribution bases that rely on the smol core, with this they could make everything much less spaghett and even some use on attack sectors n such because you could use landing pads for remote turret batteries. could also be usefull for making factory sectors that have large amounts of scrap imported for a large slag refinery to send to a distribution center sector. this further eases the ability to make sectors into bases with a purpose.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
#588

**Comment by itcannotbe** [comment]
@Kyllingene It's not the same.

in v5 there is some called launched resources so the suggestion made some sense back then.

but this suggestions is asking for a launch pad receiver because OP can't use Vaults/Containers to expand their core.

**Comment by Kyllingene** [comment]
@itcannotbe Are you telling me that in v6, the launchpads are useless? If they don't launch resources to other sectors (exactly what this suggestion pertains to) for those sectors to use, then what do they do?

**Comment by itcannotbe** [comment]
The issue you mention is not similar to this one.

**Comment by Kyllingene** [comment]
Both ask for pads which receive items launched via launch pad, and then output them. The only difference is that #588 says that the landing pads request the materials, and then they are sent.

**Comment by itcannotbe** [comment]
#588 request that resources are pulled from a resource pool that doesn't exist anymore

**Comment by Kyllingene** [comment]
Oh, my bad. I was forgetting that launch pads didn't target sectors in those days.

**Comment by stuffyAI** [comment]
> Oh, my bad. I was forgetting that launch pads didn't target sectors in those days.

Back then there were no sectors really, you just played different maps, no vision of them being the same planet or even system.
You launched resources to, what most assumed to be, main bases like starships or headquarters. Afterwards Items could not be used anymore on any of the maps, which was suggested there.
