### ISSUE TITLE
Anonymous Y/N voting

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#233]
**Describe what you would like changed, and why.**

Make voting Y/N anonymous on kicks. _(only the person starting the kick would not be anonymous)_

In some cases people will not vote against because of potential retaliation if the vote fails (as the person who voted to kick is clearly identified).
Many games today also have anonymous voting.

**Describe the changes you want to propose. Include possible alternatives.**

Make the Y/N vote stage for vote kicking anonymous.

**Comment by Summet-V** [comment]
Good Idea.

**Comment by jaygamer81** [comment]
This would help **alot**
