### ISSUE TITLE
reclaim preivous abilities of Mech (i think Tau was one of them who could do this)

### ISSUE THREAD

**Issue by KRN-8** [Anuken/Mindustry-Suggestions#2330]
with the move from v5 to v6 we lost the ability to manually mine thorium
it would be nice if one of the hight tier ground mechs could mine it again :-)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
(The whole dagger tree is not supposed to be used for mining aaaaaaaaaaaa)

**Comment by itcannotbe** [comment]
Actually no unit has mining level 4

**Comment by KRN-8** [comment]
v5 mechs had it ;-(

**Comment by KRN-8** [comment]
what about the huge T5 lazor crawlers mining thorium at like just 200% speeds

**Comment by KRN-8** [comment]
imho the ground only units should (and already do) mine faster then flyers XD

**Comment by itcannotbe** [comment]
![Screenshot_20210423_211617](https://user-images.githubusercontent.com/45280919/115876782-504aa780-a479-11eb-853a-99fe234bb464.jpg)

**Comment by KRN-8** [comment]
;-(
well atleast we can make it from scrap now soo :-)

**Comment by KRN-8** [comment]
Wait actually
if its like T5 (or T4) unit then it should be a OK right ?
(since if u build those u kinda won and just tryin to get lotsa resources AFK)

**Comment by joshuaptfan** [comment]
Do you not comprehend Anuke's statement above?

**Comment by Legomonster33** [comment]
units mining thorium would be very op

the game is not balanced around having infinite thorium in the blink of an eye

**Comment by KRN-8** [comment]
the game has infinite resources RN ...

**Comment by joshuaptfan** [comment]
You know what I mean. Don't be a troll.

**Comment by KRN-8** [comment]
who sayed it has to be fast ???
lets say its about as fast as todays v6 T1 miners
but costs u T5 unit? i dont see how that would be OP

**Comment by Legomonster33** [comment]
> the game has infinite resources RN ...

Yes but you cant get them instantly

**Comment by KRN-8** [comment]
there are unit limits as well, u cannot get copper and lead instantly with 5 monos
why should it be instant for thorium with lets say 5 Corvuses ?

**Comment by KRN-8** [comment]
1 T5 corvus costs 1400 thorium
if it mines 1 thorium/s then u start getting thorium after 25 minutes (or half hour if u using it for powering the base too)

**Comment by KRN-8** [comment]
not to mention thorium has mining hardness of 4, soo it takes longer to mine to begin with ;-)
