### ISSUE TITLE
An option for borderless fullscreen/windowed fullscreen

### ISSUE THREAD

**Issue by Ciliane** [Anuken/Mindustry-Suggestions#2333]
**Describe the content or mechanics you are proposing.**
Add borderless fullscreen as an option (basically borderless window that covers the entire screen looking like fullscreen)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Fullscreen is nice to play with , but windowed allows you to take screenshots easily (snipping tool or some other software) making you press F11 every time you want to take a screenshot. It's not a big deal but if you didn't have to and alt+tabs were nicer it would be convenient

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Have you... looked in graphics settings?

**Comment by KRN-8** [comment]
yee, there is a bug currently where if u have both ON and u OFF fullscreen then u will get windowed instead of borderless windowed
workaround for this is to toggle borderless OFF ON ;-)

**Comment by Ciliane** [comment]
> Have you... looked in graphics settings?
> 
> Enable "borderless window" and disable "fullscreen". (There is a graphics setting menu design flaw where both can be enabled simultaneously, which results in a weird hybrid mode that isn't true borderless fullscreen.)

Yes, but it's not really occupying the entire screen and doesn't cover the bottom bar, doesn't feel like proper borderless fullscreen

**Comment by joshuaptfan** [comment]
If the borderless window isn't covering the taskbar, just press the Windows key twice.
