### ISSUE TITLE
Respawn cost

### ISSUE THREAD

**Issue by Biggocl123** [Anuken/Mindustry-Suggestions#2335]
I think it would be cool (and realistic) for it to cost to respawn, a small cost tho. Like 5-10 copper to respawn as alpha, 10-15 copper and 5-10 lead to respawn as beta and 15-20 copper, 10-15 lead, and 5-10 titanium to respawn as gamma

This would add a bit of realism and make it to require the select resource, and a bit of a punishment for dying constantly.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
What would happen if you don't have enough resources?
Are you just crippled until you get enough?

**Comment by nichrosia** [comment]
Also, it should probably be added to the guidelines that "it would be more realistic" is not a good reason to implement something.

**Comment by itcannotbe** [comment]
[Lazy enough not to check that #1778 is the same thing] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
Jinx

**Comment by SheepCommander** [comment]
Close suggestion
