### ISSUE TITLE
#suggestion-discussion

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2337]
**Describe the content or mechanics you are proposing.**

Channel where users can talk about and get feedback on thier ideas before they post them here

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

it will allow for better, higher quality, suggestions that have the feedback usually found in the comments already included within.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has been suggested.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion is planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the discord or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you should suggest" category.

**Comment by 19lamanna** [comment]
also see https://github.com/Anuken/Mindustry-Suggestions/issues/1627
