### ISSUE TITLE
Spaced conveyors

### ISSUE THREAD

**Issue by awawawawg** [Anuken/Mindustry-Suggestions#2338]
**Describe the content or mechanics you are proposing.**

you could have an option to make the line feature where you can make a line of conveyors by holding your finger and moving it across the screen have a gap between every conveyor

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would improve the game because when you’re distributing items using let’s say a router and conveyor instead of dotting in between the router/conveyor you could just make a line of conveyors and a line of routers filling in each other's gaps

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This suggestion has virtually 0 application outside making those cursed dark router highways

So it's a **no** for me.

**Comment by Legomonster33** [comment]
But why would you need this, ever???

**Comment by oinkymoo** [comment]
inverted sorters and underflow gates can't pass forward into others of their own kind so it could be useful if you are putting a lot of them back-to-back. that being said just place them over the belts

**Comment by Humanoid-X** [comment]
router highways are useless

**Comment by notrealn** [comment]
maybe its for supplying 2x2 towers with ammo? not router highway

anyways close issue you can just use schematics to do this

**Comment by numer99** [comment]
Why would you want to specifically space conveyors
Why???
just distribute them normally
