### ISSUE TITLE
Make boosting units and falling air units fade in and out of void

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2339]
**Describe the content or mechanics you are proposing.**
![image](https://user-images.githubusercontent.com/61173114/115584206-d6070100-a287-11eb-9902-0776d8000b4c.png)

![image](https://user-images.githubusercontent.com/61173114/115583511-2fbafb80-a287-11eb-9585-a5b9a4ca32f5.png)

It's just kinda *pop*, you're out of the void. Make this a sort of fade in and out (maybe have it apply an alpha depending on draw layer?) to appear more natural.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It won't be one of those "you cannot unsee this" things anymore.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Edit: for some reason it sent the wrong image for the first one.

**Comment by Humanoid-X** [comment]
What mod is that...
