### ISSUE TITLE
tags, links and headers for mods

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2340]
**Describe what you would like changed, and why.**
more and more people are modding mindustry, and as the modding community grows it's probably a good idea to make mods easier to browse. in my opinion, the best way to do this is to make a system of modders making tags and headers for their mods.

**Describe the changes you want to propose. Include possible alternatives.**
my idea is that all modders can now add "tags" to their mods. this means, when searching for mods, you can select a tag, say "turrets", and find all the mods that have turrets included. you could do this with "texture pack", "planet", etc.

additionally, i think it'd also be a good idea to let mods have headers in the mod browser and ingame mod folder (like servers do), instead of just the mod description. in the header, you could put "v1.3.5", "out now!" "in development!" or anything else a modder would want to put.

finally, i also think clickable links to the mod descriptions. if a mod wants you to read the github page, or join the server, it's much easier to make links clickable there instead of having to tediously type it all out.

all of these changes, in my opinion, would help polish and really complete the game's mod system. having these abilities makes mods easier to browse, modders more able to display information, and more.

**Comment by itcannotbe** [comment]
This would be a hell to implement. Coding such is doable, asking people to update their repositories to include such text is hard as fuck.

**Comment by sup3r87** [comment]
> This would be a hell to implement. Coding such is doable, asking people to update their repositories to include such text is hard as fuck.

what about servers though? cant the same be done to the mod browser? aside from clickable links?

**Comment by MrDuck557** [comment]
should be easy to do, just have a description.hjson containing tags and descripton

**Comment by itcannotbe** [comment]
Does the mod browser even load the hjson files of each mod in the mod browser?

I don't think so.

**Comment by abrasmag3** [comment]
> Does the mod browser even load the mod.hjson files  
It does, because it uses the display names
