### ISSUE TITLE
Change the 0,0 coordinate to be the core.

### ISSUE THREAD

**Issue by 4Dharvish4** [Anuken/Mindustry-Suggestions#2342]
**Describe what you would like changed, and why.**

I think making the core 0,0 would be better than the bottom left corner which, when a sensor reading x/y gives null, is always out of bounds for ground and naval units. If the core is 0,0 then you will have negative coordinates which can be run through some code to give messages like 'flare approaching core from South-West'.

Describe the changes you want to propose. Include possible alternatives.**
If core cannot be 0,0 , make the centre of the map 0,0 then.

**Comment by Kyllingene** [comment]
> Change the 0,0 coordinate to be the core

You realize that moving the coordinate system on a map-by-map basis wouldn't even be possible due to multiple-core maps? That is completely without touching the fact that this breaks numerous systems and would be a pain to code for so little usefulness.

> If core cannot be 0,0 , make the centre of the map 0,0 then.

Not only is this impossible on even-sized maps (which block is 0,0?), it would also require the refactoring of tons of base-game stuff, as well as player-made logic. This also goes against the cross-platform, cross-language, 
cross-engine convention of 0,0 being bottom-left.

**Comment by Slava0135** [comment]
Maps with multiple cores - m U l T i V e R s E

**Comment by MrDuck557** [comment]
1. Use subtraction for your purpose. You don't need the core to be 0,0 to detect flare in South-West
2. The 0,0 dash is one of the best ways of detecting null.

**Comment by RedstonerKBC** [comment]
You don't need the core to be at [0, 0] to figure out where a unit is relative to it. If you do UnitPos - CorePos the result is the unit's position relative to the core and it works for any core.

**Comment by Kyllingene** [comment]
Close?

**Comment by RedstonerKBC** [comment]
Make sure you don't get the formula backwards otherwise you'll get the core's position relative to that unit lol. A common mistake people make when doing subtraction.

**Comment by numer99** [comment]
how about 0,0 is the middle of the map

**Comment by Kyllingene** [comment]
> > If core cannot be 0,0 , make the centre of the map 0,0 then.
>
> Not only is this impossible on even-sized maps (which block is the middle?), it would also require the refactoring of tons of base-game stuff, as well as player-made logic. This also goes against the cross-platform, cross-language,
cross-engine convention of 0,0 being bottom-left.

[#2342 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/2342#issuecomment-824358090)

**Comment by SheepCommander** [comment]
close

**Comment by sample-text-here** [comment]
close
