### ISSUE TITLE
Move drawer field from GenericCrafter to Block

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#2343]
**What do I want?**

Move the `drawer` field from `GenericCrafter` to `Block`. 

**Why should you care?**

It would be nice for mods to be able to change how non-crafter vanilla blocks are drawn. 

**Fill the boxes please.**

1. - [h] Not copyright. 
2. - [h] Not planned.
3. - [h] Not ~~implemented~~ in the main branch.
4. - [h] Death.

**Comment by SMOLKEYS** [comment]
Template: _**background screaming**_

**Comment by Anuken** [comment]
All of the drawer implementations use fields that are specific to `GenericCrafter`, like progress, crafting time or warmup.

**Comment by genNAowl** [comment]
True, but it would be nice to use it for things other than `GenericCrafter`s

**Comment by genNAowl** [comment]
bonk

**Comment by Dioo0** [comment]
bonk

**Comment by genNAowl** [comment]
I bonk whatever suggestions don't have a chance of being implemented

**Comment by SMOLKEYS** [comment]
bonk

and that concludes this suggestion
