### ISSUE TITLE
Visual Indicator Of Where Your Build Plan Is

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2344]
**Describe the content or mechanics you are proposing.**

Some sort of visual indicator pointing to the center of your building plan.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

this would be useful for when you start to build something but then have to go attend other matters, and come back but don't remember what you were building.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
wdym by building plan?

**Comment by SheepCommander** [comment]
I would like this, and building plan just refers to blocks you haven't built yet

**Comment by oinkymoo** [comment]
ah ok

**Comment by KRN-8** [comment]
what about rebuilding plan?
the blocks that got destroyed have no "click me to build again" feature

**Comment by SheepCommander** [comment]
That would probably branch off into it's own suggestion
