### ISSUE TITLE
An option to make moving while freecamming not snap your camera back to your unit

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2345]
**Describe the content or mechanics you are proposing.**
Add a setting to gameplay settings that stops the camera from snapping back to your unit when you're freecamming, though maybe it should still move as your unit moves

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Allows you to move while using freecam

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sup3r87** [comment]
i already suggested this
https://github.com/Anuken/Mindustry-Suggestions/issues/1967

i still agree with the suggestion though.
