### ISSUE TITLE
Stealing 

### ISSUE THREAD

**Issue by parkuristt** [Anuken/Mindustry-Suggestions#2346]
### What?
This is a generic gameplay request, but adding stealing blocks and units to the game would be good and pretty fun. I saw some requests about stealing **items**, but I think that's not a good idea because it doesn't fit the game too much. My idea is adding units that deploy smaller thief robots. They can enter a turret or unit and capture it, like the boarding mechanic from Airships: Conquer The Skies.
**I know it's not something new, or easy to make. But it being a hard request doesn't mean it's completely impossible or shouldn't be in the game. I wish I had the knowledge of Java programming so I could make it a pull request.**

### Why?
- It can sometimes give another chance of winning in PvP, as the improved powerful opponent also needs to think of the possibility of their units getting stolen.
- It can make the Attack mode pretty different. Think about it, using some of the enemy units. It can't be all of them since some should be able to defend the _stealable_ units.

### More explanation, because it seriously wasn't enough
_(?)_ = Not sure if appropriate for the game's balance system

## **The Deployer**
- The maximum level is 2 or 3.
- Doesn't cost **too** much and has good health, but doesn't have too powerful cannons.
- Every time you upgrade it, it can steal bigger units.

## **The.. Small Thief Robots?**
- Can't steal resources, only blocks and units (or only units, I'm not sure at all). So it doesn't actually steal, but it takes control.
- Are pretty small. Almost half the size of Crawler. _(?)_

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why steal a turret when your unit is already a better turret?

**Comment by parkuristt** [comment]
> Why steal a turret when your unit is already a better turret?
> 

The deployer isn't meant to attack directly, but it might have some cannons for self-defense

**Comment by PickAPlayerNameFirst** [comment]
Welp, you know the solution for your problem:

MODS. 

Its so unclear why you want to rig the game with stealing system... In multiplayer griefers are already a pain to kick... 

Plus if the stealing system is designed for enemies, **then you'll have a hard time dealing with the frontline defense of the enemies**. So you're probably wasting your time and 15 silicon for them to kamikaze like crawlers and flares. Upgrading it to t3-5 would be a bigger problem, as cyclones and crap are mixed to the frontline.

**Comment by parkuristt** [comment]
> Welp, you know the solution for your problem:
> 
> MODS. 
> 
> Its so unclear why you want to rig the game with stealing system... In multiplayer griefers are already a pain to kick... 
> 
> Plus if the stealing system is designed for enemies, **then you'll have a hard time dealing with the frontline defense of the enemies**. So you're probably wasting your time and 15 silicon for them to kamikaze like crawlers and flares. Upgrading it to t3-5 would be a bigger problem, as cyclones and crap are mixed to the frontline.

Well, you're right at some point but here's what I think about the deployer:
- It isn't able to upgrade or the maximum level is 2 or 3.
- It costs a lot and doesn't have too powerful cannons, though it has good health.
- It can't steal resources, only blocks and units (or only units, I'm not sure at all). So it doesn't actually _steal_, but it _takes control_.

So it's not too OP and it requires skills and patience.

Also, I recommend not telling people to use mods in feature requests.

**Comment by Kyllingene** [comment]
> Also, I recommend not telling people to use mods in feature requests.

Why not? The majority of requests are unfit for the game, and mods are a highly convenient way to get what you want without compromising the game.

**Comment by parkuristt** [comment]
> > Also, I recommend not telling people to use mods in feature requests.
> 
> Why not? The majority of requests are unfit for the game, and mods are a highly convenient way to get what you want without compromising the game.

Yeah, I remembered that later.

So what do **you** think of the plan? I think it can be fit into Mindustry by changing my idea a little, and of course balancing.

**Comment by stuffyAI** [comment]
> new mechanics are ᵃˡᵐᵒˢᵗ always good

Really?
Don't you feel like the learning curve gets only steeper in the beginning as you attempt to introduce more mechanics?

From performance, aka speed and memory, over user experience, like UI and usability, and programming cost there are a bunch of things to evaluate the feature against.
Let's not even discuss your lack of perspective, seeing the mediocre description for what might as well be another unit tree(?), do you believe that your feature has a tight fit in either current or future (observing Trello) Mindustry?

That's also why mods were suggested, they don't have to be balanced and don't drag the entire game down, still giving you your feature of wish.

You should update your initial post regarding what you actually want, I also suggest to update **WHY?** as your reasoning is generic and thus useless;
you are supposed to write down why and how your feature contributes to the greater of Mindustry, not give a copy-pasta response that doesn't give anyone an idea as to what scenario your suggestion improves.

**Comment by parkuristt** [comment]
ᵃˡᵐᵒˢᵗ

**Comment by parkuristt** [comment]
> EDIT: Please specifically update your feature suggestion, don't provide that content in comments.
Thanks, I will.

**Comment by parkuristt** [comment]
I edited almost the entire request, comment again like you're seeing it for the first time.

**Comment by sample-text-here** [comment]
imagine building a meltdown then someone steals it and makes it blowtorch your own defense
it seems like a good idea but it would be very annoying

**Comment by parkuristt** [comment]
> imagine building a meltdown then someone steals it and makes it blowtorch your own defense
> it seems like a good idea but it would be very annoying
> 

You're right, that's why I mentioned changing the idea a little.

I'm closing this issue, it's inactive now.
