### ISSUE TITLE
Submarines

### ISSUE THREAD

**Issue by Creepdolp** [Anuken/Mindustry-Suggestions#2347]
**Describe the content or mechanics you are proposing.**

Submarines can be added as the third naval unit: 
1. They can dive in deep water. 
2. Under water, they move more slowly than normal naval units. 
3. While underwater, they are invisible and cannot attack, giving opponents a surprise attack from the water. 
4. As they rise to the surface, they damage, push back, apply the wet effect, and slow the units above them. 
5. As they dive into the water, they create a vortex depending on the size of the unit and draw in nearby enemies, dealing damage, applying the wet effect. If the submarine that creates the vortex is large, it sinks perishable units such as risso, minke, and atrax on its target. This gives normal naval units a counterplay despite their strength. 
6. Submarine mines (mines that cause damage and reveal the positions of naval units) or anything else that can reveal their positions can be added for counter-submarine play. 
7. As a weapon, there should be arc type electric weapons or hybrid weapons. Electric weapons can combine their wet effect. T5 or T4 submarines use the conductivity of the water to send a current through the water, damaging enemies on the road and exploding at the seashore where they hit, dealing area damage in a cone-shaped area. 
8. Maybe high-level submarines can drop mines into the water. For example, as artificial intelligence, there may be artificial intelligence that leaves mines in the surrounding area and thus protects the region.

Bukalemun#9597

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

They will be nice.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[You liar] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

#477

**Comment by NightOmega** [comment]
**### anuke said he didn't implent the underwater env. can you ppl stop suggeting something that will not be done in the next version?like wait to V8 or V9**

**Comment by Legomonster33** [comment]
> [You liar] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> #477

also the other 10 submarine suggests

**Comment by RedstonerKBC** [comment]
> **### anuke said he didn't implent the underwater env. can you ppl stop suggeting something that will not be done in the next version?like wait to V8 or V9**

How hard is it to change the graphics (to show it being underwater) and temporarily remove a ship's collision box?

**Comment by SheepCommander** [comment]
close

**Comment by marky0470** [comment]
How making it just another naval unit and when it submerges its actually just becoming intangible to most turrets? No need to make an underwater environment layer.

**Comment by darmaangelo** [comment]
> > **### anuke said he didn't implent the underwater env. can you ppl stop suggeting something that will not be done in the next version?like wait to V8 or V9**
> 
> How hard is it to change the graphics (to show it being underwater) and temporarily remove a ship's collision box?

just make it hidden just like darktemplar in starcraft and submarine in cc
coliision is not hidden just make it unselectable
detect it with illuminator #2474
