### ISSUE TITLE
team colored launch pads

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2348]
**Describe what you would like changed, and why.**
right now launch pads are yellow no matter what team you're on. i propose the launch pad be team colored, like cores containers and the accelerator are.

launch pads are pretty team based, they launch items to other sectors, and in some custom gamemodes do other team based things. so why not make them team colored? it's distorting seeing a crux accelerator and launch pad next to each other with the launch pad staying yellow.

**Describe the changes you want to propose. Include possible alternatives.**
again i propose to change the launch pad's texture to be modifiable by team color. if large launch pad gets re-added, change it's texture to change colors too.

**Comment by SMOLKEYS** [comment]
well, i could make a texture mod which adds an overlay to the colored parts of the launch pad
that overlay shows the team

**Comment by Humanoid-X** [comment]
good, never noticed this before
