### ISSUE TITLE
Logic editor buttons near the top/bottom of the screen should not also scroll

### ISSUE THREAD

**Issue by Lightforger** [Anuken/Mindustry-Suggestions#2349]
**Describe what you would like changed, and why.**
If you click to move/duplicate a logic block near the top/bottom (red lines on the image) of the screen it also instantly scrolls up which is often not what i wanted to do
Same for the bottom buttons, clicking back/edit/add should definitely should not scroll the ui down.

Edge case: the user grabs a logic block that is already in the "drag here to scroll up" zone and does want to move it up, in this case require going to within 10 ~ 0 pixels of the screen border to start scrolling.

![image](https://user-images.githubusercontent.com/1289353/115807212-75dba080-a3e8-11eb-8171-84f1e8870b6a.png)

**Comment by Humanoid-X** [comment]
yes, the area is too big :(

**Comment by TheMaither** [comment]
frog
