### ISSUE TITLE
Reaper death&damage animation

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#235]
**Describe the content or mechanics you are proposing.**
a animation for the damage and death for the reaper

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would add a really cool way for the boss too die and make the players feel more accomplished!
•when the reaper takes damage add some details like cracks, holes, buzzing & flashing, fires, sparks, sounds, etc. For when it takes damage
•Make the reaper fall and blow up when on death it would be cool for it too fall and deal 250 dmg too all things it falls on maybe or perhaps it doesent, it would be cool for it too fall and crash though

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
what about when you play something like boxfort. Where it spams reapers. What about that poor, sad, cpu that has to compute all of that?

**Comment by jaygamer81** [comment]
Add a setting to turn it off in editor.
Also maybe a setting in settings too for it.

**Comment by Remint32** [comment]
> 
> 
> what about when you play something like boxfort. Where it spams reapers. What about that poor, sad, cpu that has to compute all of that?

This is the problem of the cartographer who made such a map.
Such effects will not cause huge drawdowns in fps, and you can always add a checkbox to the settings (which is already available for effects)

**Comment by Remint32** [comment]
Given that in 6.0 Anuke is trying to make the game "cool", this is an offer that fits perfectly into the update.
