### ISSUE TITLE
Upgradable miner units to mine more types of ores etc.

### ISSUE THREAD

**Issue by i-Ac1D-i** [Anuken/Mindustry-Suggestions#2350]
**Describe the content or mechanics you are proposing.**

Ability to upgrade the miner unit in order to make it mine a wider variety of ores, increase it's movement speed, mining speed and capacity.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This could make it easier in case the core is in a small place in which not many conveyors can reach it and/or ore veins are far away and it would be a bad idea to waste space by placing long conveyor lines. In this way, for example, at mid-late game there will be no need to use titanium-carrying coveyors anymore, as the upgraded miner unit can mine some titanium. Maybe in a very late game there could be maxed miner units that mine up to 70-100 thorium at once and that can be really useful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Define a wide variety of ores.

**Comment by RedstonerKBC** [comment]
You can mine any ore (except sand of course :() using quasars (and I think another unit) plus logic. They might be slow but monos are slow miners. You can have just as many quasars as monos and you can use logic to limit the number of quasars mining in case you also need them for attacking. If you're bad with logic there are lots of logic schems that do this exact thing and it takes minimal effort to change the amount/type of unit mining.

**Comment by itcannotbe** [comment]
There is no unit that can mine tier 4

**Comment by joshuaptfan** [comment]
Units can already mine copper, lead, scrap, coal, titanium, and sand. The only ore they can't mine is thorium.

Plus, the unit tier system is already a unit upgrade system.

I suspect OP is not familiar with the game.

**Comment by RedstonerKBC** [comment]
> Units can already mine copper, lead, scrap, coal, titanium, and sand. The only ore they can't mine is thorium.
> 
> Plus, the unit tier system is already a unit upgrade system.
> 
> > upgraded miner unit can mine some titanium
> 
> Megas (T3 air support) and quasars (T3 ground support) can already mine titanium.
> 
> I suspect OP is not familiar with the game.

Oops yes I forgot about thorium.

**Comment by Humanoid-X** [comment]
Wow, quasar can mine thorium! Never  known this before! 

**No sarcasm, in case it sounds like sarcasm

**Comment by oinkymoo** [comment]
quasar can't mine thorium, nor can any other unit, you misread

**Comment by itcannotbe** [comment]
![Screenshot_20210423_211617](https://user-images.githubusercontent.com/45280919/115876713-3dd06e00-a479-11eb-9cc7-f25d0e3c842e.jpg)

**Comment by Humanoid-X** [comment]
Ahhh. ok ok I misread :( My fault

**Comment by 1ARC1** [comment]
mods

**Comment by KRN-8** [comment]
yee T5 mining thorium = a OK

**Comment by the-red-soul** [comment]
no its not. its overpowered and is not happening.

**Comment by GitHubUser-B** [comment]
> **Describe the content or mechanics you are proposing.**
> 
> Ability to upgrade the miner unit in order to make it mine a wider variety of ores, increase it's movement speed, mining speed and capacity.
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> 
> This could make it easier in case the core is in a small place in which not many conveyors can reach it and/or ore veins are far away and it would be a bad idea to waste space by placing long conveyor lines. In this way, for example, at mid-late game there will be no need to use titanium-carrying coveyors anymore, as the upgraded miner unit can mine some titanium. Maybe in a very late game there could be maxed miner units that mine up to 70-100 thorium at once and that can be really useful.
> 
> **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 2. * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 4. * [x]  I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

I already thought about it too, good idea.

**Comment by Kyllingene** [comment]
No, not actually. For one, adding upgrades to units without physically changing them is probably never going to happen; that's just not a Mindustry-esc thing to add. That's without mentioning that most of the community considers those forms of upgrades against the README, although there is nothing explicitly stating it. Maybe someone could make a PR for that, but the fact still stands: this was not a good idea for Mindustry.
