### ISSUE TITLE
Locked Items in Research Tree Reference Other Locked Items

### ISSUE THREAD

**Issue by Hypoon** [Anuken/Mindustry-Suggestions#2351]
In the research tree, locked items are indicated with a padlock icon and a red border. Hovering over the item reveals "???" for the title and a list of requirements needed to unlock it. The obscured titles are fun, because they create a sense of mystery. The problem is that other locked items spoil the mystery.

For example, in my current game, I have a locked item below "Multiplicative Reconstructor", and all I can see is that I need to capture Overgrowth to unlock it. The locked item below "Bryde" says that I need to research "Exponential Reconstructor" to unlock it. So much for the mystery. :-(

If a locked item depends on another locked item, I think the second item's name should be obscured in the requirements of the first item (e.g. "> Research ???"). An even better solution would be to obscure the requirement entirely (e.g. "> ??????") so the player doesn't even know whether it's a researching task or a capturing task.

It just seems very strange to me that names are obscured in one place but not in the other.

EDIT: I just noticed that the same issue is present in the world view. At the moment, the research tree obscures the name of whatever sector is unlocked by capturing Impact 0078. There's only one locked sector on my globe, though, and it readily reveals its name: Desolate Rift. The name should probably be obscured here too. EDIT 2: The objectives lists in the world view (for locked sectors) should also obscure the names of locked tech tree items, although I'm not sure if there are any situations where a locked sector is shown before all of its objectives are revealed in the tech tree anyway.

**Comment by Humanoid-X** [comment]
Good thoughts, but haard to code. :(

**Comment by 4Dharvish4** [comment]
> Good thoughts, but haard to code. :(

Not really. It can be an edited string that you just change what is says. Unlock condition remains the same, just different message when clicked on.

**Comment by Hypoon** [comment]
No, it's definitely not too hard to code. I just did it, tested and working. I broke the first rule of the contributions guidelines (I don't use an IDE when I code), so I'll be respectful and I won't submit a pull request. This probably isn't the best way to implement it, anyway. I kept my change as minimal and self-contained as possible, which meant being a little inelegant. Here's the diff:
```diff
diff --git a/core/src/mindustry/ui/dialogs/ResearchDialog.java b/core/src/mindustry/ui/dialogs/ResearchDialog.java
index f78d98e77..be3cb0d6d 100644
--- a/core/src/mindustry/ui/dialogs/ResearchDialog.java
+++ b/core/src/mindustry/ui/dialogs/ResearchDialog.java
@@ -553,7 +553,20 @@ public class ResearchDialog extends BaseDialog{
                                     for(Objective o : node.objectives){
                                         if(o.complete()) continue;
 
-                                        r.add("> " + o.display()).color(Color.lightGray).left();
+                                        TechNode objNode = null;
+                                        if(o instanceof Research){
+                                            objNode = ((Research) o).content.node();
+                                        }else if(o instanceof Produce){
+                                            objNode = ((Produce) o).content.node();
+                                        }else if(o instanceof SectorComplete){
+                                            objNode = ((SectorComplete) o).preset.node();
+                                        }
+
+                                        if(objNode == null || selectable(objNode)) {
+                                            r.add("> " + o.display()).color(Color.lightGray).left();
+                                        } else {
+                                            r.add("> ?????").color(Color.lightGray).left();
+                                        }
                                         r.image(o.complete() ? Icon.ok : Icon.cancel, o.complete() ? Color.lightGray : Color.scarlet).padLeft(3);
                                         r.row();
                                     }
```
I think a better approach might be to modify the Objective interface to add a node() or techNode() method which returns the content.node() or preset.node() as appropriate. That way if someone adds a new type of Objective, they'll be automatically reminded to implement the required method. That's less error-prone than needing them to remember to update ResearchDialog.java with the new test case. By returning the TechNode instead of a selectable() boolean, a feature could be added in the future which might let the user click on the objective to pan the Research window over to the node that would resolve that Objective.

**Comment by Humanoid-X** [comment]
Ah nvm ignore my comment. Forgot how tech tree string worrk.

**Comment by Hypoon** [comment]
I just noticed the same issue is present in the world view. Hovering over a locked sector reveals its name, even though it's deliberately obscured in the research tree. I'll edit my initial post to mention that, too.

**Comment by Hypoon** [comment]
So how do these suggestions work? This suggestion is pretty easily implemented, but it's not going to get a lot of attention because it's not "exciting". Is this where simple-but-boring improvement suggestions go to die? I don't imagine Anuke reviews 1500 suggestions regularly.

I'm not trying to be critical, I'm just wondering if there's something else I should be doing to get this fix implemented.
