### ISSUE TITLE
4 things to change

### ISSUE THREAD

**Issue by 4Dharvish4** [Anuken/Mindustry-Suggestions#2352]
**Describe the content or mechanics you are proposing.**
1. Make a unit locate code that can find oil and water.
2. Make it so that when you drop 10 sand into a deep water block it changes to shallow water. 
3. Make naval units able to pick up and store liquids. 
4. make a new block that naval units can pass liquids on to.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

1. Some maps have oil but it's 2 to 4 blocks and surrounded by dark sand making it hard to find them.
2. On the map "windswept islands" there is a lot of space, but little building areas. Making it possible to turn deep water to shallow water also makes it possible to get units past a  barrier to attack enemy cores from unexpected places.
3. It can help with saving space or the unit itself can put out fires if necessary. 
4. for transfer of oil and water without pipes or bridges.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
1. do it yourself
2. why
3. pumps
4. pumps

**Comment by itcannotbe** [comment]
[Liar, Liar, Pants on Fire] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
>     1. do it yourself
> 
>     2. why
> 
>     3. pumps
> 
>     4. pumps

Which one?
This one?
>Describe the content or mechanics you are proposing.

Or this one?
>Describe how you think this content will improve the game.

**Comment by Kyllingene** [comment]
> Make it so that when you drop 10 sand into a deep water block it changes to shallow water.

Would you like to be the one programming in the ability to change the map by dropping items? That requires not only changing how items work, but how the map works.

**Comment by Legomonster33** [comment]
1. yes is good
2. no wtf
3. yes but why??
4. yes but why??

**Comment by itcannotbe** [comment]
Actually none of the suggestion's use case makes sense.

**Comment by Legomonster33** [comment]
> Actually none of the suggestion's use case makes sense.

finding liquids would be useful if you are trying to have units make pumps

**Comment by notrealn** [comment]
IMO the only good one here is the first
you shouldnt be able to change the map with blocks/items, and having units store water doesnt seem very useful

if you make boats carry water, then why cant you just place a pump on the water instead of the boat???

**Comment by 4Dharvish4** [comment]
> > Make it so that when you drop 10 sand into a deep water block it changes to shallow water.
> 
> Would you like to be the one programming in the ability to change the map by dropping items? That requires not only changing how items work, but how the map works.

If I knew how to code I would make each deep water block have the properties of a container but 1x1 and max 10 with input being sand only. Check if sand =10 and if true then change block visuals and properties to that of shallow water block.

**Comment by Legomonster33** [comment]
> > > Make it so that when you drop 10 sand into a deep water block it changes to shallow water.
> > 
> > 
> > Would you like to be the one programming in the ability to change the map by dropping items? That requires not only changing how items work, but how the map works.
> 
> If I knew how to code I would make each deep water block have the properties of a container but 1x1 and max 10 with input being sand only. Check if sand =10 and if true then change block visuals and properties to that of shallow water block.

Do you realize how laggy that would be

**Comment by Kyllingene** [comment]
> If I knew how to code I would make each deep water block have the properties of a container

***What.*** You *do* realize that tiles and blocks are completely different, and it would take an obscene amount of effort to make a container-tile?

**Comment by genNAowl** [comment]
Here's a suggestion. Why don't you check out the source code or review current mechanics before deciding if something is easy to implement or not?

**Comment by notrealn** [comment]
> Why don't you check out the source code or review current mechanics before deciding if something is easy to implement or not?

i doubt people suggesting things here are literate in java or any programming language

**Comment by Legomonster33** [comment]
> > If I knew how to code I would make each deep water block have the properties of a container
> 
> _**What.**_ You _do_ realize that tiles and blocks are completely different, and it would take an obscene amount of effort to make a container-tile?

and on top of that, deep water being container tiles that check if they have 10 sand in them, would be extremely laggy

**Comment by genNAowl** [comment]
> i doubt people suggesting things here are literate in java or any programming language

They could at least review current mechanics and based on that, decide if what they are suggesting introduces a totally new mechanic or one that can be built off of previous ones.

**Comment by oinkymoo** [comment]
these should be 3 separate suggestions. the last 2 could probably be in 1 suggestion tho
