### ISSUE TITLE
Flip UI  / Edit UI placement option

### ISSUE THREAD

**Issue by DayatXD** [Anuken/Mindustry-Suggestions#2354]
**Describe the content or mechanics you are proposing.**

make a option to be able flip the ui like this image below
![Untitled103_20210424205951](https://user-images.githubusercontent.com/47524544/115959812-a59dbc00-a540-11eb-94a7-0ab736dd457e.png)
or make a option to be able edit UI placement maybe?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

i think its more comfortable if the ui like that for me in mobile device

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
[Quote from Anuke](https://discord.com/channels/391020510269669376/396416151032299521/821067069872275466):

> optional UI layout is not happening

Every UI option multiplies UI coding complexity by creating multiple situations to account for.

**Comment by DayatXD** [comment]
> [Quote from Anuke](https://discord.com/channels/391020510269669376/396416151032299521/821067069872275466):
> 
> > optional UI layout is not happening
> 
> Every UI option multiplies UI code complexity by creating multiple possibilities to account for.

just to flip the ui is that so hard...

**Comment by joshuaptfan** [comment]
Ok, if it's as easy as you say, then you should be able to figure out how to make this "small tweak" in no time, eh?

The code for the wave UI on the top of the screen is [here](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/fragments/HudFragment.java#L49), the block placement UI below is [here](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/fragments/PlacementFragment.java#L204). Create a new graphics setting [here](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/dialogs/SettingsMenuDialog.java#L407), and name the setting [here](https://github.com/Anuken/Mindustry/blob/master/core/assets/bundles/bundle.properties#L96). Check the status of the setting like this:
```java
Core.settings.getBool("flipui")
```

**Comment by Kyllingene** [comment]
I just tried it by doing the obvious (change things like `t.top().left()` to be conditionally flipped), and it didn't work out so well... I got a wave counter smack-dab in the middle of the screen, and nothing else. Seriously, take *nothing* for granted when working with UI.
