### ISSUE TITLE
[Cancelled]

### ISSUE THREAD

**Issue by SMC-Monarch** [Anuken/Mindustry-Suggestions#2355]

**Comment by numer99** [comment]
I have actually thinking about stuff like this. _risso and nova spawn here, and in another spawn area crawlers_

**Comment by Humanoid-X** [comment]
I already suggested this :-(

**Comment by itcannotbe** [comment]
[Another liar] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by itcannotbe** [comment]
I just stated that you didn't exerted any effort to check previous suggestions.

If you don't know how to you can just use a search engine to know how to do a quick search.

And yes. You still lied when you mark that checkbox.
Also pointing out a fact is not an insult.

**Comment by SMC-Monarch** [comment]
Alright then, i take the full blame on that.

**Comment by SheepCommander** [comment]
_how soon is soon btw?_

**Comment by Kyllingene** [comment]
You could... close it?

**Comment by SheepCommander** [comment]
Someone get a tutorial on how to close an issue ~~cause I'm too lazy to do it myself~~
