### ISSUE TITLE
Logic update

### ISSUE THREAD

**Issue by ASVIEST** [Anuken/Mindustry-Suggestions#2356]
**Describe the content or mechanics you are proposing.**

# Instructions

1. Add a eval instruction which receive 1 argument and can execute code in string
2. Add a delay instruction which receive 1 int argument and allows to set a delay until the next command is executed
3. Add type as first arg of op(operation) which  return type of arg
4. Add a comment instruction which a not executable text

```diff
!5. Add a song instruction which receive 1 argument of float type and can play the frequency in hz sound duration while this command is running
```
6. Add array type of variables which syntax is [arg1, arg2, arg3] and you can refer to the index(Arr[1])
7. Add a  map instruction  which receive 1 arg of instruction, 2 arg is Array and 3 is instruction arg and performs an instruction for each element of the array
9. Add a clamp in op(opperation) which takes 3 args: value, min, max and sets a value in the range between the specified lower and upper bounds.
10. Add a link sort instruction which takes 2 args with type of blocks(turret, wall...) and var to write a indexes as array

# Blocks
8. Add a radar block with a radius larger than the turrets, and when you click on it, a menu similar to the message block will appear where you can use the slider to decrease the radius (default is maximum radius) and the radar instruction works like this
```diff
+Parameters: block size 2, maximum radius 64 blocks
```
All of this code example:
```py
1. eval "print "frog"" #it doesn't work as a function because it only takes 1 argument
2. delay 13 #tick
3. op type result a #get type of a
4. # "it is comment"
5. song 146
6. set result ["frog", "fish", "cat"] # set Arr[1] 5
7. map set Arr 3
8. radar enemy any any distance radar1 1 result
9. op clamp x -90 90
10. Link of type
```

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1. you can run eval with random values and get inputs in raw form
2. Example:
```py
op rand rand 100 b
op noise noise rand rand
op mul result noise 30
drawflush display1
draw clear 0 0 0 0 0 0
draw color 255 255 255 255 0 0
draw rect result result 30 30 0 0
delay 24
```

3. In sort on type
4. code readability
5. e.g. notifications
6. beautiful representation of a large number of values
7. e.g. add a 8 in all elements of the array
8. instead of using turrets
9. Example:
```py
radar player any any distance @this 1 result
sensor shootx result @shootX
sensor shooty result @shootY
sensor displayx display1 @x
sensor displayy display1 @y
op sub tx shootx displayx
op sub ty shooty displayy
op mul tx tx 29.33
op mul ty ty 29.33
op add tx tx 88
op add ty ty 88
draw clear 0 0 0 0 0 0
draw poly tx ty 48 2 0 0
drawflush display1
op clamp tx 0 196
op clamp ty 0 196
```
10.Sort to get link

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
> Add a eval instruction which receive 1 argument and can execute code in string

Half the world already hates Java for its insecurity. This, no matter how you interpret it, could be disastrous. Also, Anuke has already shot down the idea of string ops in any form a million times.

> Add a delay instruction which receive 1 int argument and allows to set a delay until the next command is executed

You can use `@time` to make your own delay you lazy egg

> Add type as first arg of op(operation) which return type of arg

How is this helpful?

> Add a comment instruction which a not executable text

Use a text editor, then import it into Mindustry.

> Add a song instruction which receive 1 argument of float type and can play the frequency in hz sound duration while this command is running

Please bother to look at existing suggestions to see that this has already been suggested.

> Add array type of variables which syntax is [arg1, arg2, arg3] and you can refer to the index(Arr[1])

Mlog is designed to be as minimalist as possible. Also, there are higher-level languages that compile down to mlog that people have made. Finally, ***use a memory cell you egg***

> Add a map instruction which receive 1 arg of instruction, 2 arg is Array and 3 is instruction arg and performs an instruction for each element of the array

[GO to Mlog compiler](https://vilsol.github.io/go-mlog-web/)

> Add a clamp in op(opperation) which takes 3 args: value, min, max and sets a value in the range between the specified lower and upper bounds.

Do it yourself, it's not hard.

> Add a link sort instruction which takes 2 args with type of blocks(turret, wall...) and var to write a indexes as array

1. I cannot understand what it is you want, but it is way too complex.
2. ***no arrays you egg***

---

The underlying problem here is that you want to do things, but don't want to do the work. You didn't check for duplicates, you didn't check the Trello, you don't bother to use pre-existing functionality, and you don't bother to get a feeling for Mindustry and what fits.

**Comment by SheepCommander** [comment]
close
