### ISSUE TITLE
restart button?

### ISSUE THREAD

**Issue by swipeoutfucks** [Anuken/Mindustry-Suggestions#2358]
**Describe what you would like changed, and why.**

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by Legomonster33** [comment]
did you forget to put anything??

**Comment by BlueWolf3682** [comment]
i love it when    is suggested and there are     possible alternatives

**Comment by Kyllingene** [comment]
Close please. Not only is this a duplicate, and not only did you blatantly put absolutely no effort into this, but you also chose the wrong label and thus template.

**Comment by SheepCommander** [comment]
judging by the name, and the `(their first ever!)`, and the `Joined github this month` it's a troll/alt/bot that will not close their issue by themselves
