### ISSUE TITLE
Mobile function

### ISSUE THREAD

**Issue by N0odleLeg** [Anuken/Mindustry-Suggestions#2359]
**Describe the content or mechanics you are proposing.**
A way to move the camera without moving the player on mobile, this way, we could continue building while planing our next build elsewhere.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It could allow multitasking on mobile and would help a lot if you want to mine while planing a building somewhere.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
1. This suggestion should have a more descriptive title, such as "Mobile move camera" (you can edit the title by clicking the "Edit" button next to "New issue")
2. If you could have the player unit do things independently of what you are doing, then it's not really a _player_ unit, is it? You can build AI units to mine for you. T1 air support, mono, mines automatically, and T2/3 air support and T2/3 ground support can be controlled with logic to mine.

**Comment by Legomonster33** [comment]
this is a feature on pc, and would be nice for mobile users.

**Comment by itcannotbe** [comment]
Is this even possible without adding in another button in the gui for mobile?

Also is this the same behavior if one is to use mouse+keyboard?

**Comment by itcannotbe** [comment]
Also #506

**Comment by N0odleLeg** [comment]
> Is this even possible without adding in another button in the gui for mobile?
> 
> Also is this the same behavior if one is to use mouse+keyboard?

It would work like mouse and keyboard but for mobile, which would probably mean a new buttons yes...

**Comment by stoneRdev** [comment]
I mean, this would be nice, but i already kind of do this by pausing while i build

**Comment by N0odleLeg** [comment]
> I mean, this would be nice, but i already kind of do this by pausing while i build

Yes but then you couldn’t get resources while paused. My exemple where it could be helpful is in campaign at the start of a sector when you collect copper and start building stuff it could be nice to start placing stuff while mining copper near the base so that when you are ready to build you don’t miss copper.

**Comment by SheepCommander** [comment]
> 2. If you could have the player unit do things independently of what you are doing, then it's not really a _player_ unit, is it? You can build AI units to mine for you. T1 air support (mono) mines automatically, and T2/3 air support and T2/3 ground support can be controlled with logic to mine.

he means planning builds somewhere else, but otherwise yes
