### ISSUE TITLE
Way Better Tutorial

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#236]
**Describe what you would like changed, and why.**
My friend has began playing mindustry and he's really confused so it would help for new players to have a better path if they want too, like a **optional** tutorial for all new resources and buildings when they unlock them (through tech tree).

**Describe the changes you want to propose. Include possible alternatives.**
•when you get coal maybe tell them how to use it and if it doesent go in the core also maybe bring up the CORE DATABASE as that would help introuduce them too it. 
•When they unlock a building teach them what it does, the inputs, the outputs, power, and/or show them the CORE DATABASE

**Comment by itcannotbe** [comment]
Apparently using the question mark while playing a game or clicking on the block in the tech tree isn't obvious to many.

**Comment by Rybadour** [comment]
Agreed, I wasted some time early in learning how to play when I piped scrap into the core and wondered why it wasn't going in. Seems like a few more dialog boxes explaining these new materials would go a long way.
