### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by BitorBit1357** [Anuken/Mindustry-Suggestions#2360]

**Comment by joshuaptfan** [comment]
Duplicate of #810, #868, and it's [already planned](https://trello.com/c/yij5RfGc/734-logic-sound).

Please close.

**Comment by the-kido** [comment]
Have you seen trello. Have you not searched if someone else suggested this. Did you keep the template.

**Comment by itcannotbe** [comment]
He actually bypassed the template.
It's kinda obvious because this issue doesn't have a tag.

**Comment by BitorBit1357** [comment]
Ok, sec.Ii need time to close it, i have some internet problems right now

**Comment by joshuaptfan** [comment]
Close the issue by clicking "Close issue" next to the "Comment" button.
