### ISSUE TITLE
Boost while standing

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2361]
**Describe what you would like changed, and why.**
Currently, you have to move while boosting to actually fly. What I'm suggesting is removing the moving part and only need boosting. Also, logic doesn't have to move to boost.

**Describe the changes you want to propose. Include possible alternatives.**
Remove the movement check for boosting and fly whenever the keybind is pressed

Tell me if this breaks anything, such as balancing or controlling

**Comment by joshuaptfan** [comment]
Seems fine to me. This would allow players to dodge turret fire with more certainty.

**Comment by BlueThecno** [comment]
**How would this work for __mobile__ tho?**

**Comment by SheepCommander** [comment]
I agree but do not know about mobile

**Comment by MrDuck557** [comment]
I have no idea how mobile controls work ¯\_(ツ)_/¯

**Comment by joshuaptfan** [comment]
> How would this work for mobile tho?

It wouldn't. On mobile, you have no manual control of boosting; you automatically boost when there is an obstruction or you are moving at top speed.

**Comment by BlueThecno** [comment]
That's why I said it, Boosting in mobile is automatic, which mean that to make **this** possible you would have to add a button to the UI in mobile.

**Comment by MrDuck557** [comment]
Done in 7.0, closing now
