### ISSUE TITLE
More Sector Icons

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2362]
**Describe the content or mechanics you are proposing.**

All ingame sprites able to be used to mark sectors on the map

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

while marking sectors is useful, the symbols available aren't usually very well suited for marking specific things, ie: phase fabric factory.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
very similar to #2207

**Comment by SheepCommander** [comment]
I'm pretty sure I've seen this exact suggestion before (add all ingame sprites as icon options) but can't find one, other than 2207 another close one would be #2037

But since my memory's apparently wrong anyways I agree with this suggestion :+1:
