### ISSUE TITLE
bannable unit trees

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2363]
**Describe the content or mechanics you are proposing.**
i propose being able to ban unit trees in map making, for example banning crawlers and making the crawler tree unbuildable.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
currently while map making you cannot make an all ground map. the nova tree will always be able to fly, and this creates problems for maps that want to be solely ground focused. banning unit trees solves this issue and allows mapmakers to specialize. wasnt only spider units? sure. how about only flares? go for it. its like banning unit factories, but more specific, and why not?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
It would be better if each unit can be banned so if zenith is banned it wont come out in the Reconstructor or in a payload Conveyor but can still be upgraded.

**Comment by sup3r87** [comment]
> It would be better if each unit can be banned so if zenith is banned it wont come out in the Reconstructor or in a payload Conveyor but can still be upgraded.

while this is true, how would you be able to do this and effectively warn players before they accidentally build an antumbra only to realise eclipse is banned?

**Comment by joshuaptfan** [comment]
Duplicate of #2328. Though given the incredibly undescriptive title, I can forgive missing this duplicate. Please put some effort into naming suggestions!

**Comment by itcannotbe** [comment]
> Duplicate of #2328. Though given the incredibly undescriptive title ("Editor upgrade"), I can forgive missing this duplicate. Please put some effort into naming suggestions!

Same thoughts.

**Comment by SheepCommander** [comment]
> > It would be better if each unit can be banned so if zenith is banned it wont come out in the Reconstructor or in a payload Conveyor but can still be upgraded.
> 
> while this is true, how would you be able to do this and effectively warn players before they accidentally build an antumbra only to realise eclipse is banned?

That would be mentioned `#2328` this is asking for the removal of trees instead

**Comment by SheepCommander** [comment]
( @itcannotbe and @joshuaptfan IMO this is not really a duplicate and has better wording + naming anyways )

**Comment by itcannotbe** [comment]
The discussion in #2328 was actualy leaning on banning unit trees anyways.

**Comment by SheepCommander** [comment]
*Yes but the suggestion itself is still fricked*
