### ISSUE TITLE
can be in different sector when hosting multiplayer in campaign

### ISSUE THREAD

**Issue by Kenzie3581** [Anuken/Mindustry-Suggestions#2364]
Able to be in different sectors when hosting multiplayer.
Example: The host is an Tar fields while the second player is in salt flats 
This would make multiplayer campaign more fun and no need to always follow host around

**Comment by itcannotbe** [comment]
You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
Why do you need to fill out the template you ask?

See the first checbox?
This suggestion failed that check already.

**Comment by itcannotbe** [comment]
`**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
`

**Comment by itcannotbe** [comment]
How many incarnations of hosting/loading the whole planet or allowing hostong mutiple campaign sectors do we need to see?

**Comment by bsjohnson20** [comment]
As many as there are people thinking the template is a supplementary thing
