### ISSUE TITLE
Game type where the world is infinitely generated, with enemy bases trying to expand.

### ISSUE THREAD

**Issue by EPICGUPPY44** [Anuken/Mindustry-Suggestions#2365]

**Comment by Legomonster33** [comment]
while yes this would be cool, it would require substantial changes to the way maps work

**Comment by itcannotbe** [comment]
While this would be cool, I don't think anybody has an infinite amount of ram and processing power.

**Comment by SheepCommander** [comment]
While this would be cool, it would be cooler if you filled out the template probably

**Comment by marky0470** [comment]
Anuke would need to implement chunks for this to work which is hard.

**Comment by itcannotbe** [comment]
While this would be cool, wish you haven't broke the chain.

**Comment by XenonLog01** [comment]
While this would be cool, he did.

**Comment by SheepCommander** [comment]
While he did, that wouldn't be cool

**Comment by PickAPlayerNameFirst** [comment]
> Anuke would need to implement chunks for this to work which is hard.

That idea will be similar to minecraft... 

Title has:
No and desc... Lazy boi

**Comment by SheepCommander** [comment]
> > Anuke would need to implement chunks for this to work which is hard.
> 
> That idea will be similar to minecraft...
> 
> Title has:
> No description ... Lazy boi

That's obviously a general thing programmers can do to optimize just that the minecraft community references chunks a lot more, but yes the suggest itself is bad and who knows about the concept the suggestion is proposing

**Comment by PickAPlayerNameFirst** [comment]
If that no description idea would be added... 
Then we'll have a superflat serpulo 
With infinite miles of area
And with infinite diameter
And will have the famous unknown world borders
~~and will be similar to flat eather conspiracy~~

**Comment by kapzduke** [comment]
1. you did not define size, but an infinite world would hardly be possible, i'm not sure about chunk generation. there are already some RNG maps in the #maps channel of the Mindustry discord that could be a possible alternative to what you had suggested.
1.1. template
