### ISSUE TITLE
[CoreBot] Ability to copy schematic codes

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2366]
**Describe the content or mechanics you are proposing.**

Some way of copying schematic codes to clipboard as its far easier to import via clipboard then it is via file

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

makes importing schematics from the discord much easier

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Try asking discord, cause a bot can only do so much.

Plus as long schematics are fairly common now a days, I really doubt that anyone sane enough would even consider putting in a text version ready for copying.

**Comment by joshuaptfan** [comment]
If there was a way to force Discord to display text without wrapping, sure. The text would display in 1 line with a long horizontal scrollbar, and you could do a select all on that line to copy the text. But even code-formatted text wraps.

**Comment by Legomonster33** [comment]
you could write the scheme code to a txt file, then users can click to view the preview and copy paste from that

**Comment by SheepCommander** [comment]
> If there was a way to force Discord to display text without wrapping, sure. The text would display in 1 line with a long horizontal scrollbar, and you could do a select all on that line to copy the text. But even code-formatted text wraps.

As said if you upload certain file types, such as .txt, discord will display the contents and I'm pretty sure it does have a built-in button to copy
