### ISSUE TITLE
New game mode

### ISSUE THREAD

**Issue by NightOmega** [Anuken/Mindustry-Suggestions#2367]
**Describe the content or mechanics you are proposing.**

a new game mode called interplantery rockt dash _IRD for short_ 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

New gameplay that revolves around conducting core launch _with interplantlery terminal_ in the fastest time possible  

**Before making this issue, place an `h` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [h] I haven't done a quick search in the list of suggestions to make sure this has been suggested yet.
2. - [h] I haven't checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion is planned or implemented in a development version.
3. - [h] I am not familiar with all the content already in the game or haven't glanced at the wiki to make sure my suggestion does exist in the game yet.
4. - [h] I haven't read `DONOTREADME.md` to make sure my idea is listed under the "A few things you shouldn't suggest" category.
5. - [X] I will not ping @Anuken

**Comment by Legomonster33** [comment]
thats just v7 tho

**Comment by NightOmega** [comment]
> thats just v7 tho

what you mean?

**Comment by NightOmega** [comment]
everyone bored with the old gamemodes

**Comment by MrDuck557** [comment]
so basically speedrun but a gamemode

**Comment by Legomonster33** [comment]
> > thats just v7 tho
> 
> what you mean?

v7 will have more planets, you will use the accelerator to get to them, so its just v7 speedrun

**Comment by Anuken** [comment]
pinging me with your obtuse suggestions for no particular reason while mocking the checklist is a sure way to get you blocked from this repository.

**Comment by Kyllingene** [comment]
Goodbye, NightOmega. You thought you were funny, but now you're just blocked.

**Comment by PolloUsami** [comment]
it sounded like wonders race but in mindustry

**Comment by SheepCommander** [comment]
wow
