### ISSUE TITLE
Force Projector Stacking

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2369]
**Describe the content or mechanics you are proposing.**

Adjacent projectors combine their health

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

it ill make force projectors more useful, as instead of each one making its own force shield, they would all work together, kind of like power networks where everything works together instead of each things being completely independent.
this would provide a much needed buff to force projectors and allow for more creative uses of them.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [Y] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [E] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [E] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [T] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
just for clarification, do you mean that the projectors themselves must touch or the shields

**Comment by Legomonster33** [comment]
> just for clarification, do you mean that the projectors themselves must touch or the shields

doesn't matter, both make sense.
having it just require the shield touching would be much more op

**Comment by sup3r87** [comment]
This sounds like a very very bad idea in the extreme. You could extend force projectors back and create super walls that are nearly impenetrable. Endgame bases with lots of power budget would become invincible as you ca just place down this hex shield and extend it anywhere and boom nearly invincible shield.

unless it becomes super expensive to link these together I don’t see how this wouldn’t break the game. Not sure what the people on the discord are thinking either.

**Comment by itcannotbe** [comment]
> This sounds like a very very bad idea in the extreme. You could extend force projectors back and create super walls that are nearly impenetrable. Endgame bases with lots of power budget would become invincible as you ca just place down this hex shield and extend it anywhere and boom nearly invincible shield.
> 
> unless it becomes super expensive to link these together I don’t see how this wouldn’t break the game. Not sure what the people on the discord are thinking either.

Nice catch honestly.

I would be extremely broken if that happened.

**Comment by oinkymoo** [comment]
there should probably be a cap on number of shields that can be connected in such a way then

**Comment by Kyllingene** [comment]
This seems like a little clunky way to make a wall. One huge force field would be OP, and a bunch of medium sized ones just sounds weird, and could also have some unintended consequences (you can't stop players from making a bunch of force-projector chains with only 1 exposed projector). I think that small, individual force

**Comment by PickAPlayerNameFirst** [comment]
It's a good idea tho, but the "combining shields" could be OP. 

Maybe this:

The idea is to *remove the overlaying animations and borders* of the shields cuz at some point it would be pretty annoying to deal. You know, 

FPS drops.

**Comment by SheepCommander** [comment]
Agreed with above comment

**Comment by sup3r87** [comment]
> It's a good idea tho, but the "combining shields" could be OP.
> 
> Maybe this:
> 
> The idea is to _remove the overlaying animations and borders_ of the shields cuz at some point it would be pretty annoying to deal. You know,
> 
> FPS drops.

this is already a thing for players with animated textures on, however i support the same effect going for the low detail textures too

**Comment by PickAPlayerNameFirst** [comment]
Bcuz when there's the thing in Castle Wars when shields of Quasars go too overlapped that you can't see the core

Same for the PvP maps that has premade force projector spam buildings

**Comment by PickAPlayerNameFirst** [comment]
The HP is still divided to the shields but its borders do not overlap, for performance improvements

**Comment by darmaangelo** [comment]
> This sounds like a very very bad idea in the extreme. You could extend force projectors back and create super walls that are nearly impenetrable. Endgame bases with lots of power budget would become invincible as you ca just place down this hex shield and extend it anywhere and boom nearly invincible shield.
> 
> unless it becomes super expensive to link these together I don’t see how this wouldn’t break the game. Not sure what the people on the discord are thinking either.

just make enemy stronger

**Comment by oinkymoo** [comment]
> > This sounds like a very very bad idea in the extreme. You could extend force projectors back and create super walls that are nearly impenetrable. Endgame bases with lots of power budget would become invincible as you ca just place down this hex shield and extend it anywhere and boom nearly invincible shield.
> > unless it becomes super expensive to link these together I don’t see how this wouldn’t break the game. Not sure what the people on the discord are thinking either.
> 
> just make enemy stronger

you do know that this isn't how balancing works at all? there is one specific strat that is overpowered. your solution is not to nerf the strat, but to make all enemies, which may not even encounter the strat, stronger.
