### ISSUE TITLE
Bind hotkeys permenantly (regardless of tech unlocks)

### ISSUE THREAD

**Issue by ztomlord** [Anuken/Mindustry-Suggestions#237]
**Describe what you would like changed, and why.**
Permanent hotkey binding, ie make router be hotkey (3,3) from the start, regardless of if it is unlocked.  It is jarring as you are progressing through the campaign to have the hotkeys constantly changing.  This is compounded by the fact that this is an rts and so being able to hit hotkeys quickly is critical to efficiently build.  I also think that when doing this, give thought to most commonly used items and bind them accordingly to make it easier on a standard keyboard for common things (like router).

**Describe the changes you want to propose. Include possible alternatives.**
I think the ideal solution is to just assign hotkeys to structures regardless of unlock.  This may result in a *dead* hotkey ie if u unlock 5 before 4 on conveyors for a short while, but I think that would be greatly superior to the current flux.  I would update the ui so that locked items are shadowed probably (since your hotkeying order lines up with object order in the ui), and therefore in a permanent grid representative of their hotkey.  Another option would be to allow players to adjust hotkeys... but this feels way less user friendly and would likely be missed by new players.

**Comment by Katsute** [comment]
#6
#11
#14

**Comment by zethnest** [comment]
This is implemented and can now be closed.
