### ISSUE TITLE
multi-material plastanium belt improvement

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2370]
**Describe what you would like changed, and why.**

there are 2 ways to remove items from plastanium belts. you can use extractors, taking a few items at a time. this works. however, it takes up a ton of space in comparison to routers and the like. unfortunately, the small solution tends to break on multi-resource belts because some of a resource will be sent to the side, but not all. when the next stack arrives, it will get stuck, because it can't pass forward, and the whole system breaks. i propose a fix to this.

**Describe the changes you want to propose. Include possible alternatives.**

if a stack is partially created, and a second source tries to put a different item into the start of the belt, the in-progress stack is released prematurely.

**Comment by IVV-NCX** [comment]
Format? I'd say it's good, since it adds some difficulty to using plastanium conveyers.

**Comment by itcannotbe** [comment]
Just use different loading points for every resources you want to go on plastanium conveyors.

**Comment by oinkymoo** [comment]
i'm trying to use over/underflow gates on plastanium belts that have multiple materials already on them, which aren't exactly compatible with extra loading points

**Comment by itcannotbe** [comment]
Why would you even make a mixed use plastanium conveyor, if you can't handle the output properly.

The only thing I can see this useful on is a convoluted small factory designs that would actually waste material anyway.

**Comment by PickAPlayerNameFirst** [comment]
Better solution:

If you have a titanium belt that has mixed items, make a sorter and connect to a new loading point. 

Example:
Titanium and plastanium mixed belt:

Add a sorter on the head of the main loading point, configure it to titanium, the sides should be connected to a forked loading point. 

If something happens like "accidental" clogs, then you should de-clog it manually. For these cases tho, it could be useful. But it's rare to have accident clogs.

**Comment by oinkymoo** [comment]
the problem is that i have a full belt of titanium and a full belt of thorium and an almost full belt of silicon and i want to run them to the same set of launchpads, just for convenience, so i merge all of them but as soon as gates start getting involved everything breaks
