### ISSUE TITLE
 Small Force projector modification

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2372]
**Describe the content or mechanics you are proposing.**
The force projector has 6 sides, but this makes it so that the east to west sides are easier to attack and generally don't look good when packed together compared to the north to south sides. In my opinion there are 2 fixes to this, 1, make it so that you can rotate force projectors, or 2, make them an octagon.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As described before, attacking east to west is easier that attacking north to south because of how the force projectors are made. A simple rotation option or making them an octagon will fix this supper easy.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
No one can guess that by "pot", you mean "projector". Please edit the suggestion title to be more accurate.

**Comment by Ineedause** [comment]
I edited it but it does not show anything on the discord

**Comment by itcannotbe** [comment]
This has already been discussed in a PR in the main repo. It's not gonna happen.

**Comment by OnyxFinger** [comment]
> No one can guess that by "pot", you mean "projector". 

I did

>And what is "update"? Please edit the suggestion title to be more accurate.

Well of course a change for it, and that's the point of reading the commit : knowing what it's about.
