### ISSUE TITLE
demonstration for guns!

### ISSUE THREAD

**Issue by Melado41** [Anuken/Mindustry-Suggestions#2373]
When clicking in "info" on a gun , show a tiny GIF of how the gun works

It helps to new players know what wich gun do, whitout having to test it and spend materials

1. - [ X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [  ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Sandbox does exist right?

**Comment by Kyllingene** [comment]
1. The README.md is the easiest thing to check, do it please
2. The Trello is also really easy to check - it has a search bar - so do that please
3. Adding gifs to an in-game menu wouldn't be impossible, but it would be extraneous (see above comment) and mess with the layout (especially on mobile).

**Comment by SMOLKEYS** [comment]
close
now
