### ISSUE TITLE
Complex Expression Support

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2374]
**Describe the content or mechanics you are proposing.**

Logic Function to support complex expressions with multiple operators, variables, and parentheses.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

improve the usability of logic to perform mathematic functions.

```
set x1 10
print x1
print "=x1\n"
set y1 10
print y1
print "=y1\n"
set x2 166
print x2
print "=x2\n"
set y2 166
print y2
print "=y2\n"
set x3 84
print x3
print "=x3\n"
set y3 84
print y3
print "=y3\n"
set r 7
print r
print "=r\n"
op sub (x1-x2) x1 x2
op sub (y2-y1) y2 y1
op div (x1-x2)/(y2-y1) (x1-x2) (y2-y1)
print (x1-x2)/(y2-y1)
print "=k0\n"
op mul y2y3 y2 y3
op mul y1y3 y1 y3
op sub y2y3-y1y3 y2y3 y1y3
op mul x1x3 x1 x3
op sub y2y3-y1y3-x1x3 y2y3-y1y3 x1x3
op mul x2x3 x2 x3
op add (y2y3-y1y3-x1x3+x2x3) y2y3-y1y3-x1x3 x2x3
op div (y2y3-y1y3-x1x3+x2x3)/(y2-y1) (y2y3-y1y3-x1x3+x2x3) (y2-y1)
print (y2y3-y1y3-x1x3+x2x3)/(y2-y1)
print "=b\n"
op pow k0^2 (x1-x2)/(y2-y1) 2
op add 1+k0^2 1 k0^2
print 1+k0^2
print "=a\n"
op mul k0b0 (x1-x2)/(y2-y1) (y2y3-y1y3-x1x3+x2x3)/(y2-y1)
op mul 2k0b0 2 k0b0
op mul -2x3 -2 x3
op add -2x3+2k0b0 -2x3 2k0b0
op mul y3k0 y3 (x1-x2)/(y2-y1)
op mul 2y3k0 2 y3k0
op sub -2x3+2k0b0-2y3k0 -2x3+2k0b0 2y3k0
print -2x3+2k0b0-2y3k0
print "=b\n"
op pow b0^2 -2x3+2k0b0-2y3k0 2
op pow x3^2 x3 2
op add x3^2+b0^2 x3^2 b0^2
op mul 2y3 2 y3
op mul 2y3b0 2y3 -2x3+2k0b0-2y3k0
op sub x3^2+b0^2-2y3b0 x3^2+b0^2 2y3b0
op pow y3^2 y3 2
op add x3^2+b0^2-2y3b0+y3^2 x3^2+b0^2-2y3b0 y3^2
op pow r^2 r 2
op sub x3^2+b0^2-2y3b0+y3^2-r^2 x3^2+b0^2-2y3b0+y3^2 r^2
print x3^2+b0^2-2y3b0+y3^2-r^2
print "=c\n"
op mul ac a x3^2+b0^2-2y3b0+y3^2-r^2
op mul 4ac 4 ac
op pow b^2 -2x3+2k0b0-2y3k0 2
op sub (b^2-4ac) b^2 4ac
op sqrt sqrt(b^2-4ac) (b^2-4ac) b
op mul -b -2x3+2k0b0-2y3k0 -1
op add (-b+-sqrt(b^2-4ac)) -b sqrt(b^2-4ac)
op mul 2a 2 1+k0^2
op div (-b+-sqrt(b^2-4ac))/2a (-b+-sqrt(b^2-4ac)) 2a
print (-b+-sqrt(b^2-4ac))/2a
print "=x4\n"
op mul k0x4 (x1-x2)/(y2-y1) x4
op add k0x4+b0 k0x4 -2x3+2k0b0-2y3k0
print k0x4+b0
print "=y4\n"
set x4 (-b+-sqrt(b^2-4ac))/2a
set y4 k0x4+b0
draw color 255 255 255 255 0 0
draw linePoly x3 x3 12 r 0 0
draw line x1 y1 x2 y2 0 0
draw line x1 y1 x4 y4 0 0
draw line x2 y2 x4 y4 0 0
draw line x4 y4 x3 y3 0 0
draw linePoly x4 y4 8 5 0 0
draw clear 0 0 0 0 0 0
drawflush display1
printflush message1
```

this gets confusing and hard to understand very quickly

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [Y] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [E] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [S] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
Logic is based on mlog, which is supposed to be as close to basic computer language as possible. Inline math would defeat that purpose.

**Comment by MrDuck557** [comment]
Also, this is a duplicate of another suggestion, which was turned down

**Comment by itcannotbe** [comment]
Kindly throw this suggestion to the growing pile of add functions to mindustry logic.

Sincerely,
Everyone who hates duplicates issues.

**Comment by Legomonster33** [comment]
ok i looked but i didnt find any simmilar suggestions sooo...
link plox

**Comment by itcannotbe** [comment]
Just search functions and a lot of them refers to adding functions into logic.

**Comment by itcannotbe** [comment]
Found one, basically a more complicated version of #1922

**Comment by oinkymoo** [comment]
logic is based on assembly code, which means that you can do at most one thing on each line. one math operation, or one print statement, or one condition check
