### ISSUE TITLE
Display mining speed with water

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#2375]
**Describe the content or mechanics you are proposing.**
When placing a drill, display the drill speed with liquid under the normal drill speed.
![Mindustry_wKHCYht5WY](https://user-images.githubusercontent.com/54301439/116604769-69bd7a80-a8e3-11eb-8d39-8bf02890cc04.png)
(Top-notch editing work right there)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You don't need to worry about multiplying to see how much it makes if the game does it for you.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Instead of "Liquid Drill Speed:", just say "With Water:" (shorter text).

**Comment by XenonLog01** [comment]
Good idea. Would make my life easier.

**Comment by MEEPofFaith** [comment]
\*Puts down calculator\*

**Comment by itcannotbe** [comment]
Doesn't the drill speed displayed increases when you add optional boosters (Yes, I'm not singling out water, because mods are a thing) to the drill?

**Comment by MEEPofFaith** [comment]
It does, but not when placing it.

**Comment by itcannotbe** [comment]
Oh. But it still would look shit (UI wise), if you displayed multiples if a mod supports add a suitable liquid for drill boosting.

**Comment by itcannotbe** [comment]
Wait is it even possible for drills to have boost options?

**Comment by MEEPofFaith** [comment]
It's called water

**Comment by itcannotbe** [comment]
> It's called water

It's not hard coded to only use water.

**Comment by buthed010203** [comment]
Something like this could also work, it wouldn't require anything to be localized. The problem with this is that it is pretty unclear what that number means by just looking at it. ![](https://i-dont.go-outsi.de/S1pxz2.png)

**Comment by MEEPofFaith** [comment]
How about this:
[target item icon] Drill Speed: 3.42/s ([boost liquid icon] 11.10/2)

**Comment by buthed010203** [comment]
> How about this:
> [target item icon] Drill Speed: 3.42/s ([boost liquid icon] 11.1/sec)

I was thinking about that but didnt want to figure out how to add the correct icon without just hardcoding it

**Comment by joshuaptfan** [comment]
> how to add the correct icon without just hardcoding it

Can it be done the same way item icons are typed in chat?

**Comment by buthed010203** [comment]
> Can it be done the same way item icons are typed in chat?

Yes but as others have pointed out, the boost isn't restricted to just water when using mods, I don't really know how you would get the correct icon for that. Hardcoding it is as simple as copy pasting the character for water or using `Liquids.water.emoji()`

**Comment by darmaangelo** [comment]
good idea up up up
