### ISSUE TITLE
Have Enemies have different coloured attacks than player

### ISSUE THREAD

**Issue by animeisesl** [Anuken/Mindustry-Suggestions#2376]
**Describe what you would like changed, and why.**

I'd like to see enemies have different coloured attacks than the player to better differentiate their attacks from our own.

**Describe the changes you want to propose. Include possible alternatives.**

Red attacks for enemies, yellow can stay for the player

**Comment by itcannotbe** [comment]
Basically you're saying that attacks/bullets/lasers/beams should be colored as what the team color is?

**Comment by itcannotbe** [comment]
Honestly this should be a feature request.

**Comment by RedstonerKBC** [comment]
> Basically you're saying that attacks/bullets/lasers/beams should be colored as what the team color is?

No, or maybe. Could be. I don't know. They didn't mention teams. All I know is they want a different bullet color for enemies.

**Comment by RedstonerKBC** [comment]
I don't think this is a good idea since different classes have different color bullets anyways, unless you propose we do some sort of outline around the bullet. Like a Corvus shoots a green laser blast with a black outline?

**Comment by itcannotbe** [comment]
> > Basically you're saying that attacks/bullets/lasers/beams should be colored as what the team color is?
> 
> No, or maybe. Could be. I don't know. They didn't mention teams. All I know is they want a different bullet color for enemies.

I made the assumption to factor in multiple teams in custom/ multiplayer maps.

**Comment by itcannotbe** [comment]
> I don't think this is a good idea since different classes have different color bullets anyways, unless you propose we do some sort of outline around the bullet. Like a Corvus shoots a green laser blast with a black outline?

-10/10 for visuals.

**Comment by joshuaptfan** [comment]
It would look terrible, and the information isn't all that necessary. Use some common sense; the direction bullets are traveling indicates whether they are friendly.

[To quote the movie Black Hawk Down, "[if they're shooting at you,] shoot back."](https://www.youtube.com/watch?v=Nk5DcZ-rDNI)

**Comment by OnyxFinger** [comment]
>some sort of outline around the bullet.

I think this would be a good idea, for people that want it. I would also like to add to this that the outline should be toggable on-off just as any other outline should be is isn't right now, which is kinda dumb, the outlines for bridges, for example, are bulky in my opinion and should be toggable, this feature could get added with team-colored bullets.

**Comment by animeisesl** [comment]
I have never played with teams, I'm talking with the experience as a new player playing the campaign.

**Comment by Axzye** [comment]
checklist: if it kills you, it's the enemy

**Comment by OnyxFinger** [comment]
as I said it's not so simple.. sometimes the battlefield is a mess and we can consider the amount of useless visuals that were added in v6 and just say that one more doesn't really matter anyway, I think it's better to add it as a togglable as I said.
