### ISSUE TITLE
Launch Pad Destination Sync Option

### ISSUE THREAD

**Issue by Darkmann12** [Anuken/Mindustry-Suggestions#2378]
I would like to see either a menu or a block or something that allows you to sync launch pad destinations across sectors.

Where resources are being produced and exported from multiple sectors, having to manually go into sectors and fiddle with the destinations of launch pads each time you want to focus all your resources on something becomes tedious after a few repetitions. Having this option to sync launchpads would mean only one sector would have to be entered to change the destination for all the launchpads in player-selected sectors. This helps especially under time pressure when you need extra resources in the middle of a capture.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [  ] (this has been suggested once, a long time ago, but I feel I have elaborated on the idea)
2. - [x]
3. - [x]
4. - [x]

**Comment by oinkymoo** [comment]
it is generally more effective to direct all your resources to a single launch hub (salt flats is a popular one for this) and from there launch items to wherever they need to go

**Comment by Darkmann12** [comment]
I have done this but it has crippled my transfer speeds from around 1200/transfer to about 150/transfer hence why I suggest this.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Darkmann12** [comment]
![20210430222621_1](https://user-images.githubusercontent.com/83469818/116755934-21957980-aa03-11eb-98a2-7e5801839dd2.jpg)
This is the current setup I am using.

**Comment by Darkmann12** [comment]
And that appears to have done the job. Thanks!

**Comment by oinkymoo** [comment]
extractors normally only run about 10 items/sec, which is enough to run 2 pads. this is another reason why tacking storages/vaults onto your hub is a good idea, because they give it more surface area, which means you can fit more extractors
