### ISSUE TITLE
"Fixed in 7.0"

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2379]
Technically not a Mindustry suggestion, but IDK where else

**Describe the content or mechanics you are proposing.**
Add a list of stuff fixed or added in 7.0

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Instead of people reporting a bug and getting turned down 5 seconds later with "Fixed in 7.0," they can just check the list

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. (Not exactly detailed though)
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
> Instead of people reporting a bug and getting turned down 5 seconds later with "Fixed in 7.0,"

That means I fixed it *now*, not before the issue was reported.
