### ISSUE TITLE
Buff Phase walls

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#238]
**Describe what you would like changed, and why.**
Phase fabric is highly unused and the walld have no damage

**Describe the changes you want to propose. Include possible alternatives.**
•increase health
•or make the walls regenerate themselves or when they die they become transparentish and they regenerate back later. Since phase fabric is like holographic technology
•Makes phase walls **actually** usefull
•also maybe the bullets that bounce off the walls dont damage the walls themselves when bounced (if not implemented)

**Comment by potatoisagender** [comment]
Actually, I was going to post something similar. Why not let them reflect SOME erad and reaper bullets?

**Comment by itcannotbe** [comment]
Basically it's above the damage limit for reflection for such bullets. Why would it reflect those types of bullets.

**Comment by potatoisagender** [comment]
I was thinking more of like, higher damage bullet = less likely to reflect. So for example daggers would almost always reflect, eruptors occasionally, and erad very rarely.

**Comment by gen-NA-owl** [comment]
Merged a PR, I think this can be closed now? (unsure)

**Comment by 50275** [comment]
I don't know about you but the ability for a single large phase wall to destroy 3000 fortresses (V5) seems a little unfair to me

**Comment by genNAowl** [comment]
Pretty sure it's been changed now so instead of negating damage when phase walls reflect a bullet they take damage too (Unconfirmed).

**Comment by genNAowl** [comment]
Not as op as in 5.0
![not-as-op](https://user-images.githubusercontent.com/68400583/96962097-f9a8e480-14ba-11eb-9d3e-ff237ba88ca5.gif)
