### ISSUE TITLE
'dead zone' tile

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2380]
**Describe the content or mechanics you are proposing.**

The space tile is unique as it does not allow buildings to be built on it, I recommend a similar tile but it prevents units from going on it as well. Like the border on the edge of a map, this tile will stop all units in their tracks and make them find a different route. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A tile like this will allow map creators to make a 'dead zone' on the map where no units can go. Immagine a bridge map where all your units have to go through a bridge. Flares will always be able to just bypass that, a tile with these capabilities will allow map creators to have more freedom while creating maps with less headache.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
they mean also for air units

**Comment by itcannotbe** [comment]
Add this suggestion to the pile of suggestions that basically request for terrain block/s that are not passable by flying units.

**Comment by SMOLKEYS** [comment]
Wouldn't this completely topple air units?
They mostly just ***go*** straight for the core, not really pathfinding there.
(Unless you use logic to give them pathfinding capabilities)

**Comment by SMOLKEYS** [comment]
Quezler actually tried this, but that did not go *anywhere* near well.

**Comment by SMOLKEYS** [comment]
![Screenshot_20210501-102954_Discord.jpg](https://user-images.githubusercontent.com/75618732/116768315-3d7f3680-aa68-11eb-9b75-01ecc0110f0e.jpg)
