### ISSUE TITLE
Naval Support Abilities

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#2381]
![2021-04-30_20-43-39](https://user-images.githubusercontent.com/54417042/116767306-61596280-a9fd-11eb-968a-e38706fd895d.gif)

tug boating: (all)
     Naval support units command other units but don't un-command them when the player exits the unit, can be chained for a convoy of boats

gunboat(t1 or t5)
    can be loaded with a 1x1/2x2 payload, if the payload is a turret, it can use the turret to attack (idk how the ammo would work)
    
torpedo: (t4)
     slow moving bullet that can only travel in water tiles, ignores shields and cannot be hit by segments, deals massive aoe damage when hitting a non-water tile or an enemy boat
     
overclock: (t3 or t5)
     overdrive nearby allies, has a 1 man shield, which only protects itself and acts as bonus hp

rip template ikr

**Comment by Yell245** [comment]
Already in Trello

**Comment by Legomonster33** [comment]
> Already in Trello

yes but the trello dont say what they will do

**Comment by itcannotbe** [comment]
How many naval support unit ideas do we even need to see?

**Comment by Legomonster33** [comment]
> How many naval support unit ideas do we even need to see?

n+1

let n = how many there are

**Comment by OnyxFinger** [comment]
> > How many naval support unit ideas do we even need to see?
> 
> n+1
> 
> let n = how many there are

that's just about what we need nice

**Comment by Humanoid-X** [comment]
Torpedo is suggested before. 

For gunboat I think use items in your inventory (I dunno what must I call that, hope you understand what I mean
