### ISSUE TITLE
R to Rotate, QOL improvement

### ISSUE THREAD

**Issue by KRN-8** [Anuken/Mindustry-Suggestions#2382]
**Describe the content or mechanics you are proposing.**
Hold R key to rotate existing building (like conveyor)
now only works on already built buildings

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
what about allowing this to work on not built buildings (the paused building layout ones)
currently u can do this only by:
1) clear your hand
2) hold the layouted building
3) scrollwheel (which will also zoom XD)
or alternatively
3) hold R (now holding mouse button and R and paused auto builing)
4) scrollwheel to rotate

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by KRN-8** [comment]
btw. this already holds true for Pick Block action ;-)

**Comment by itcannotbe** [comment]
What again is the suggestion again? I think you already can rotate block before placement and rotate already constructed building. So I don't even know what the suggestion is all about.

Apparently OP doesn't get what the template is asking.

**Comment by itcannotbe** [comment]
**Describe the content or mechanics you are proposing.**
The actual suggestion.


**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
How does the suggestion affect gameplay.

**Comment by joshuaptfan** [comment]
In the past, scroll only rotated things, and you had to hold Ctrl to zoom, even though zoom is used much more frequently than rotation. [I changed it to be contextual](https://github.com/Anuken/Mindustry/pull/1206), to greatly reduce the frequency of when you need to hold a key down.

Note that you can still hold Ctrl to zoom while holding something rotatable.

**Comment by KRN-8** [comment]
for ppl that didnt go thru General keybinds in Controls, im talking about this key
![obrazek](https://user-images.githubusercontent.com/67783847/116792473-1012a700-aac1-11eb-8f02-0c4d51282035.png)

**Comment by SheepCommander** [comment]
@KRN-8 what @itcannotbe and @joshuaptfan is asking is what you're even suggesting. What I think you're suggesting is the ability to rotate partially constructed blocks, which would be nive.

**Comment by KRN-8** [comment]
@SheepCommander partially constructed blocks were not on my mind
i meant when u do
1) pause building stuff
2) build stuff
-) now it is like if u placed blueprint and u can move the pieces
and u can rotate them too but u cannot do it with R unless u hold them in hand (=mouse)
