### ISSUE TITLE
T2 Payload Conveyors

### ISSUE THREAD

**Issue by notMEEPoffaith** [Anuken/Mindustry-Suggestions#2383]
**Describe the content or mechanics you are proposing.**
These would be payload conveyors that can move T4 and T5 units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
These would be useful for those unit factories that make T5 and T4 units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Have you even thought why you would even need a payload conveyor for a T4 they only output around once every minute, and that number gets larger with T5s. I really doubt it's usefulness.

**Comment by sup3r87** [comment]
ive asked about this to anuke before and he said no, so unfortunately i dont think this suggestion will be happening

**Comment by itcannotbe** [comment]
[Looks like I found another liar]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Duplicate of #533 and #767

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/553#issuecomment-695827442

> > a higher tier payload conveyor for tier 4/5 units

> Yeah, no, I'm not adding 7x7 / 5x5 conveyors, that would be ridiculous. 3x3 conveyors are already pushing the limits as is.

**Comment by buthed010203** [comment]
Hell he even said no today ![](https://discord-cdn.is-terrible.com/NVPwUu.png)

**Comment by SMOLKEYS** [comment]
close
now
or you dropkicked by a "no" from anuke

**Comment by SheepCommander** [comment]
when not closed 👎

**Comment by OnyxFinger** [comment]
payload conveyors almost all of the time useless anyway.
