### ISSUE TITLE
Fluid flow.

### ISSUE THREAD

**Issue by dwluke** [Anuken/Mindustry-Suggestions#2384]
**Describe what you would like changed, and why.**

Hi, water Fleming throught elements is very unclean.
For example, throught normal pipe you can move max 550 l/s. But with certain elements its much lower. The fact, not every element have described the maximum flow causing confusion in planning fluid supply on huge scale.
**Describe the changes you want to propose. Include possible alternatives.**

**Comment by joshuaptfan** [comment]
[The fluid system is already being reworked.](https://github.com/Anuken/Mindustry/tree/fluid-networks)

**Comment by buthed010203** [comment]
> The fluid system is already being reworked.

[More info can also be found on the trello](https://trello.com/c/CPr6XKm3/823-fluid-networks)

**Comment by SheepCommander** [comment]
close
