### ISSUE TITLE
make resource display available on mobile

### ISSUE THREAD

**Issue by djdisodo** [Anuken/Mindustry-Suggestions#2386]
**Describe the content or mechanics you are proposing.**

make an option to unable resource display as same as pc on mobile

i found that there's no resource display on mobile

pc users won't understand why mobile users use resource without regarding how much resource is left

and mobile users, they don't know how much is left until it's gone

**Comment by SMOLKEYS** [comment]
do not
the ui is already full

**Comment by itcannotbe** [comment]
Murdered Template Detected.

**Comment by Humanoid-X** [comment]
Emergency meeting, dead template detected!

**Comment by Kyllingene** [comment]
djdisodo was the Impostor.

**Comment by SheepCommander** [comment]
close
