### ISSUE TITLE
New command, allows downloadable multiplayer maps

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2387]
**Describe the content or mechanics you are proposing.**
A new command: "/downloadmap (savestate:t/f)". When executed, downloads the map the user is currently playing to their maps directory.

Has an optional parameter that defaults to false. When true, also saves the current state of the map as a loadable save file. When false, only saves the map to the user's maps. This may require some reworking of the code since you also have to not save other player's states. We can just pretend they don't exist and only save the user's state.

It doesn't have to be called "/downloadmap". I just wanted a command that save the current map as a map (and optionally as a saved game file). In campaign mode, does not save campaign maps to campaign saves, only as separate loadable saves, preventing the command from breaking campaign mode.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Extremely useful for multiplayer.

No longer will users have to hunt down their favorite map somewhere on discord. No longer will users have to contact the server owner to give them a map. No longer will they have to wonder what the map is called so they can look it up. Simply execute the command and the map will save to the user's device.

The optional save state parameter allows users to save the current state of the game as a save file. This can be useful for testing strategies in certain situations without relying on other players to help get you to that spot.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
It wouldn't be a rework because the command would have to fetch and serve the original file because MSAV isn't a map format perse, it's just a glorified save file that so happens to be convenient enough to be a map format.

So, no you can't ignore what happens to the map because there isn't a convenient way to do it, it has to serve the actual original file, either fetched with every command from storage or the map is already loaded to memory.

**Comment by Surdok** [comment]
I can't express enough how I wanted to download a map I played on a server. This would come very handy to download map, or even to give out the option to automatically download the map whenever you join a server.

**Comment by itcannotbe** [comment]
> give out the option to automatically download the map whenever you join a server.

*skips map 10x noises*

**Comment by RedstonerKBC** [comment]
> It wouldn't be a rework because the command would have to fetch and serve the original file because MSAV isn't a map format perse, it's just a glorified save file that so happens to be convenient enough to be a map format. So, no you can't ignore what happens to the map because there isn't a convenient way to do it, it has to serve the actual original file, either fetched with every command from storage or the map is already loaded to memory.

What happens if it saves all player's states on the user's device and the user loads the saved game? Will the game crash or will it dump the other players who it realises aren't online to play?

**Comment by itcannotbe** [comment]
Does MSAV even store player states to begin with?

**Comment by OnyxFinger** [comment]
Guys just make a save of the map then export it and re-import it in your editor.
