### ISSUE TITLE
Guardian mark for the possible to distinguish who the guardian is

### ISSUE THREAD

**Issue by SpaceEarthEX** [Anuken/Mindustry-Suggestions#2388]
**Describe the content or mechanics you are proposing.**
These days, it is difficult to distinguish who is the guardian because the guardian has the same tier as the normal enemy sometimes.
boss status have x1.5 health and x1.3 damage
So, i though idea to add a guardian mark for the possible to distinguish who the guardian is.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Maybe, displays mark on the guardian and some red glowing..
*(it can subtract some of it or add some of it)*

***Like this:***
![guardian mark](https://user-images.githubusercontent.com/68502246/116904580-d97f8c80-ac78-11eb-86ed-ef7589fc675d.png)
(Yes i think it needs red outline.)

![guardian mark 2](https://user-images.githubusercontent.com/68502246/116905706-4cd5ce00-ac7a-11eb-9acd-e97a8b23f74c.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mothership007** [comment]
since anuke is working on dynamic outlines, maybe a special red outline?

**Comment by SheepCommander** [comment]
👍

**Comment by DarkBrick** [comment]
![image](https://user-images.githubusercontent.com/63005558/117137573-2fa01d00-adaa-11eb-9557-88482e46ec75.png)
Seems like this is a highly received issue

**Comment by GitHubUser-B** [comment]
> ![imagem](https://user-images.githubusercontent.com/63005558/117137573-2fa01d00-adaa-11eb-9557-88482e46ec75.png)
> Parece que este é um problema muito bem recebido



> ![image](https://user-images.githubusercontent.com/63005558/117137573-2fa01d00-adaa-11eb-9557-88482e46ec75.png)
> Seems like this is a highly received issue

Where is the egg?

**Comment by GitHubUser-B** [comment]
> ![image](https://user-images.githubusercontent.com/63005558/117137573-2fa01d00-adaa-11eb-9557-88482e46ec75.png)
> Seems like this is a highly received issue

Where is the egg?
