### ISSUE TITLE
default keybind improvements

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2389]
**Describe what you would like changed, and why.**
the default keybinds for pan view and follow mouse are the left and right arrow keys, which are also used for switching buildings. this also causes a building to become selected into your hand, which can be annoying if you are trying to shoot while you move. the chat history keys (up/down) may have the same issue but i haven't checked, and i can't think of a situation where such a thing would cause problems either

**Describe the changes you want to propose. Include possible alternatives.**
change the default binds for those controls to unclaimed keys. for the chat controls maybe make up and down not select blocks when chat is open.

**Comment by Anuken** [comment]
> the default keybinds for pan view and follow mouse are the left and right arrow keys

[They are not.](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/input/Binding.java#L11)

**Comment by oinkymoo** [comment]
right i forgot that i changed them because i don't even know where those buttons are, which is a whole separate issue

**Comment by Mothership007** [comment]
lmao, suggesting default keybind overhaul is the literal peak of stupidity. Custom keybinding exists for very this reason

**Comment by oinkymoo** [comment]
i still think that keys shouldnt be reused if it would cause problems, and putting such a duplicate in the default keybinds means that many players will experience issues when attempting to take the action
