### ISSUE TITLE
[Arc] Touchable.childrenDisabled

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#239]
**Describe the content or mechanics you are proposing.**

A new enum that would still check children like `childrenOnly`, but ignore events, by default, like with `disabled`.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Simplify UI code.
Before: 
```
parent.fill(t -> {
    t.touchable(Touchable.childrenOnly);
    t.label(() -> "eggs").touchable(Touchable.disabled);
    t.label(() -> "foo " + Time.time()).touchable(Touchable.disabled);
    // We only need this guy to be touchable, the rest is bloat
    t.button(Icon.terminal, () -> {});
});
```

After:
```
parent.fill(t -> {
    t.touchable(Touchable.childrenDisabled);
    t.label(() -> "eggs");
    t.label(() -> "foo " + Time.time());
    // Button is touchable by default, but if needed it can be touchable(Touchable.enabled);
    t.button(Icon.terminal, () -> {});
});
```

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
shouldn't this be in a pull request?

**Comment by DeltaNedas** [comment]
If I knew how and where I would've tried it already.

**Comment by Anuken** [comment]
This is practically useless. I don't see any place in my UI code where I would want to disable the touchable state of all the children except a few.

> Before:

Instead of creating weird touchable states, you should just place the children that should be untouchable in a table with disabled touchability.
