### ISSUE TITLE
3D rendering for logic

### ISSUE THREAD

**Issue by Bassem-Const** [Anuken/Mindustry-Suggestions#2391]
**Describe the content or mechanics you are proposing.**

With logic, you can add 3D elements to some sort of simulated "3D space" And a render function that renders all the objects from a position at a set rotation with a setting for orthographic.

Executing render takes 25x the time, of a normal instruction.

A new value has to be added: vector, so the UI doesn't get too cluttered.

Blocks:

Reigon emulator 
 Is where the "3D space" exists.

Logic:

( Place flush  ( reigonemulator(n) ) )
  Sets where the objects are stored.

( Render ( reigonemulator(n) )  Position (x,y,z)  Rotation (x,y,z)  Orthographic (<a>)  FOV (n) )
  Renders what's stored in the block memory.

( Create object (cuboid/ellipsoid/polygon/extrudedpolygon/polytope/line)  Position (x,y,z)  Size  Rotation (x,y,z)  Color (r,g,b)  ID (n)  Central skew (x,y,z)  Skew (x,y,z)  Curved skew  (1/0)  Central skew pos (<a>,<b>,<c>)  Sides  (n) )
  Creates an object with the properties above.

( Edit object (cuboid/ellipsoid/polygon/extrudedpolygon/polytope/line)  Position (x,y,z)  Size  Rotation (x,y,z)  Color (r,g,b)  ID (n)  Central skew (x,y,z)  Skew (x,y,z)  Curved skew  (1/0)  Central skew pos (0-1,0-1,0-1)  Sides  (n) )
  Changes an object by ID to the properties above.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Will make 3D art easier, and maybe the game will have models of the blocks made and players will love it!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 1ARC1** [comment]
this isn't blender, don't try to make 3d objects/models/animations in mindustry, just use blender

**Comment by Kyllingene** [comment]
Why on earth are you expecting Anuke to add 3D rendering to a machine-code emulating logic language controlling a maximum of 176x176 pixels in a display in a video game?

**Comment by OnyxFinger** [comment]
also why 3d in a 2d game ?

**Comment by oinkymoo** [comment]
if you want 3d do it yourself

**Comment by OnyxFinger** [comment]
> if you want 3d do it yourself

I don't think he can with the current game, due to modding restrictions.

**Comment by Kyllingene** [comment]
1. The person is asking for 3D *in logic displays*
2. You could definitely make a mod that displays 3D either with blocks or logic displays.

**Comment by itcannotbe** [comment]
This is the most stupidest logic related suggestion I ever seen. It's even worse than asking for more processor inputs.

**Comment by SMOLKEYS** [comment]
Close.

***NOW.***

**Comment by SMOLKEYS** [comment]
This could make low-end phones *struggle* to load mindustry even more.

**Comment by Humanoid-X** [comment]
close. Now. ASAP.

**Comment by 1ARC1** [comment]
close this, don't try making 3d things in mindustry, just use blender for that

**Comment by Legomonster33** [comment]
![image](https://user-images.githubusercontent.com/54417042/117151208-da9edf80-ad86-11eb-874c-fb20acd933f7.png)
you sure about that?

**Comment by SMOLKEYS** [comment]
> also why 3d in a 2d game ?

![images (5)](https://user-images.githubusercontent.com/75618732/117309909-7595d780-aeb5-11eb-96c0-6774809fe547.jpeg)

**Comment by Bassem-Const** [comment]
You only store the data of the objects in the reigon emulator, then they get rendered by a command with the rotation, position, and an orthographic setting.

**Comment by Bassem-Const** [comment]
> ![image](https://user-images.githubusercontent.com/54417042/117151208-da9edf80-ad86-11eb-874c-fb20acd933f7.png)
> you sure about that?

Yes, it's not in game, and can save the processor limits with raycasting.

**Comment by Bassem-Const** [comment]
> close this, don't try making 3d things in mindustry, just use blender for that

It isn't constant rendering.

**Comment by Bassem-Const** [comment]
> This could make low-end phones _struggle_ to load mindustry even more.

It doesn't render all the time if the code is executed once, and processors have a limited speed.

**Comment by Bassem-Const** [comment]
> Why on earth are you expecting Anuke, a solo, nearly unpaid dev, to add 3D rendering to a machine-code emulating logic language controlling a maximum of 176x176 pixels in a display in a video game?

Maybe update v10?

**Comment by 1ARC1** [comment]
> > close this, don't try making 3d things in mindustry, just use blender for that
> 
> It isn't constant rendering.

ye but your trying to use a non 3d game and program to render 3d stuff, thats the issue

**Comment by 1ARC1** [comment]
> > > > close this, don't try making 3d things in mindustry, just use blender for that
> > > 
> > > 
> > > It isn't constant rendering.
> > 
> > 
> > ye but your trying to use a non 3d game and program to render 3d stuff, thats the issue
> 
> 3D games always do that, they render a 3D world on a 2D screen, and at 150 i/s it only renders 6/s.

stop trying to render 3d models in mindustry, it isnt and wont ever be a 3d rending/modeling tool

**Comment by Kyllingene** [comment]
> > Why on earth are you expecting Anuke, a solo, nearly unpaid dev, to add 3D rendering to a machine-code emulating logic language controlling a maximum of 176x176 pixels in a display in a video game?
> 
> Maybe update v10?

You never answered the question. Why do you expect an unpaid dev whose only game development assistance is through contributions of various skill levels (and the bad ones often take up more time to sift through than the good ones save), who gets no payment, and is making a tower-defense game to add 3D rendering to screens with a maximum size of 176x176 pixels, a size limit surpassed by many *pixel-art images*?

**Comment by Bassem-Const** [comment]
> > > Why on earth are you expecting Anuke, a solo, nearly unpaid dev, to add 3D rendering to a machine-code emulating logic language controlling a maximum of 176x176 pixels in a display in a video game?
> > 
> > 
> > Maybe update v10?
> 
> You never answered the question. Why do you expect an unpaid dev whose only game development assistance is through contributions of various skill levels (and the bad ones often take up more time to sift through than the good ones save), who gets no payment, whose game's genre tower-defense, to add 3D rendering to screens with a maximum size of 176x176 pixels, a size limit surpassed by many _pixel-art images_?

Idea: what if my suggestion is a contribution between game devs on github?

**Comment by stuffyAI** [comment]
> Idea: what if my suggestion is a contribution between game devs on github?

Pay them.

Anyway, what gameplay aspects does your suggestion improve? 
Is a 3d pie-chart of my power statistics a desired advantage?
Is playing ping pong with shaders a straight improvement to user experience?

You didn't really give any examples on why this should be worked on, like... 'players will love it' is a bold statement for an unconfirmed fact.
I don't see why we should sacrifice development time and frames for this, however feel free to inquire me on actual, useful applications that may change my mind.

**Comment by oinkymoo** [comment]
> > > > Why on earth are you expecting Anuke, a solo, nearly unpaid dev, to add 3D rendering to a machine-code emulating logic language controlling a maximum of 176x176 pixels in a display in a video game?
> > > 
> > > 
> > > Maybe update v10?
> > 
> > 
> > You never answered the question. Why do you expect an unpaid dev whose only game development assistance is through contributions of various skill levels (and the bad ones often take up more time to sift through than the good ones save), who gets no payment, whose game's genre tower-defense, to add 3D rendering to screens with a maximum size of 176x176 pixels, a size limit surpassed by many _pixel-art images_?
> 
> Idea: what if my suggestion is a contribution between game devs on github?

if you want it done by github people, you either need to do it yourself, as you are a github person, or personally convince someone to do it, possibly with money, as well as a reason why it would improve the game

**Comment by SMOLKEYS** [comment]
> > Why on earth are you expecting Anuke, a solo, nearly unpaid dev, to add 3D rendering to a machine-code emulating logic language controlling a maximum of 176x176 pixels in a display in a video game?
> 
> Maybe update v10?

Wow.

W.
O.
W.

Everyone give this man a clap for expecting a solo dev to implement something like this.

**Comment by Bassem-Const** [comment]
> You only store the data of the objects in the reigon emulator, then they get rendered by a command with the rotation, position, and an orthographic setting. 

To clarify that is a seperate block
