### ISSUE TITLE
Power station: the ultimate power node

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#2392]
**Describe the content or mechanics you are proposing.**

A huge advanced block belongs to power category, can receive the power from power sources and distributes them to power-consuming blocks (exactly like nodes), its features:

- Range: Extreme, it is really huge maybe x2 of surge tower.

- Size: huge: maybe 6*6 or more.

- HP: tough(maybe 3000), with weak auto-heal ability(even without power source)

- Cost: so expensive, maybe the third most expensive block (after exponential and tetra), definitely it needs at least good amount of these 4 items: 1-Phase-fabric 2-Surge-Alloy 3-Plastanium 4-Silicon

- Input connections: unlimited, it can connect to any power source within it range.

- Output connections: unlimited, it can connect to any power-consuming block within its range.

- Its behavior: Like nodes, double click to connect to everything within its range(like nodes, with priority to nodes first,which means it will not connect "Directly" to a building if it is already connected to a node within its range, this is important for isolation purposes(for using diode for examples or when the power collapses to isolate some schemes..etc, disconnecting every block in that scheme so annoying)).

Unlike nodes, it is not recommended to show active links because it will be a lot and confusing, better to show Disconnected blocks within its range in red line if click.

- Maybe limited numbers: is allowed to build, only 2 of it.

- Usage: In advanced stage of the game, to clean the area. So you remove all the nodes which its purpose only transport the power and not connected to any scheme, whereas you keep the nodes that belong to a schemes, and lalaaam you have a clean area.

As you can see this block will not replace the nodes or surge tower, even in advanced stage of the the game and after building this block, there will still be a real need for normal nodes.
The only thing which i am not sure about is PvP, and how this will affect it since targeting the power node is not available or at least not easy at all now, which could be problematic. But anyway it is not an issue since banning any block is an option in any server.

-Over Powered: Surge Tower has only 2 connections because of its large range, attacking power nodes to disable the blocks(like projectors and menders..) is traditional strategy, and this block will ruins these.
Actually i thought well about this before posting this suggestion, it is like comparing Nove with Corvus, i dont see Corvus as "Sooo op" unit because it fits the last stage of the game, and this block as well, if you want to attack in this late stage of a game where you (and also your opponent) rich enough to spend few hundreds of surge and phase to build this block, you shouldn't depend on attacking on a silly power node here or there, go make a real army of t4 , t5, and make blast-compound and start zenith bombing , or any other tough strategies, and use a plan not just attacking. Then this block will not be as a real obstacle, and if you can destroy it you will make a real trouble to your opponent. So no i don't see it as OP.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This block exactly fits the last stage of a game, when the player starts using similar blocks like mass drive (vs normal conveyors), and where the player produced not bad amount of the valuable items and preparing for re-establishing his base for even more advanced big schemes :crucible, impacts, T4,T5...etc, so he needs clean area, also it helps to support the defenses if it was close to the frontline(all block will get power from far away distance).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
Mods.

**Comment by MrDuck557** [comment]
Hehe, big number funne

**Comment by OnyxFinger** [comment]
tough, (3k) hp, auto heal, probably not as good as surge walls since it's bigger and will get shot more, but since it is hard to make units not focus fire on a block you basically asked for a new wall as good / better than surge.

 If it's endgame it wont really affect PvP much I think, but just.. why healing and this much HP ?

**Comment by sup3r87** [comment]
There’s really no need for an “intimate power node” what you’re describing is something that already exists and can be done with a few hundred normally sized nodes. It would be far cheaper anyway so why build this node?
The only reason there are 7x7 and 9x9 buildings are to build boss units, the built incredibly strong units and thus require a lot of resources and space to build. But the game at it’s core is based on 3x3 maximum size for most things. It’s like how, not even most mods add 5x5 walls. There’s just no point.

**Comment by numer99** [comment]
why would someone build that?
It's too expensive for a POWER NODE
Just use regular power nodes instead

**Comment by OnyxFinger** [comment]
> why would someone build that?
> It's too expensive for a POWER NODE
> Just use regular power nodes instead

^^^ Know how most players use small 1x1 nodes every time ? Yeah that guy is essentially saying, "we use small nodes every time cuz they're more practical, and very rearely the other types, why'd we use something pushed to such extreme when we want the opposite ?"

**Comment by 1ARC1** [comment]
> tough, (3k) hp, auto heal, probably not as good as surge walls since it's bigger and so will get shot more, but since it is hard to make units not focus fire on a block you basically asked for a new wall as good / better than surge.
> 
> If it's endgame it wont really affect PvP much I think, but just.. why healing and this much HP ?
> 
> > Mods.
> 
> Mods aren't an awnser. you can't just say "mods" to anything, if an object deserves to be in the game but exists in mods, then it has to get added EVEN if there is a mod for it, for the sake of mindustry.
> If the object doesn't deserve to be added, just say at least also why, in your opinion.

this doesnt deserve to exist so yeah mods make sense in this context

**Comment by Sector171** [comment]
>  probably not as good as surge walls since it's bigger and so will get shot more, but since it is hard to make units not focus fire on a block you basically asked for a new wall as good / better than surge.

It looks that you misunderstood the point of this block, no relation at all between walls and this super power node. and this block will be so vital and important that you should put it deep in your base close to your core and well protected like your core, except you can surround it with walls.

> why healing and this much HP ?

Healing because it is a power station, and having auto heal as weak as small mender makes sense, also it is a very vital and important block (it receive & gives the power to **everything** within huge area)

> ^^^ Know how most players use small 1x1 nodes every time ? Yeah that guy is essentially saying, "we use small nodes every time cuz they're more practical, and very rearely the other types, why'd we use something pushed to such extreme when we want the opposite ?"

Haha man the answer is in your comment, and now all you need to do is just to build one of this, only one and it will cover huge area, and now you will not need to use even these small node(except the ones related to a scheme, the pro player will keep it), all you need to do is just spam any factory or turrets you want and they will get the power.

**Comment by Sector171** [comment]
> Mods.

Haha, aside from the point that mods is not an answer, so you want me to use a mods for a feature will not change anything in units, resources, factories...ect, it just will make the things easier and more organized.
lets assume that the plastanium conveyors wasn't in the game, and someone wanted a faster way to transport the items so he suggested plastanium conveyors , then you come and say: use mods, so he should use the mod just to be able to "enjoy" using this fast conveyor, hahaha, guys that's not smart at all.

The "Mods" could be a solution when someone wants a feature will make a "**DRASTIC**" change in the game, such a change will affect a lot of game aspects like new resources units factories ..etc.

I will not make a mode just to use  plastanium conveyor, or mass drive, or super node, no sense at all.

> Mods aren't an awnser. you can't just say "mods" to anything, if an object deserves to be in the game but exists in mods, then it has to get added EVEN if there is a mod for it, for the sake of mindustry.
If the object doesn't deserve to be added, just say at least also why, in your opinion.

That is exactly the thing.

**Comment by Sector171** [comment]
> There’s really no need for an “intimate power node” what you’re describing is something that already exists and can be done with a few hundred normally sized nodes. It would be far cheaper anyway so why build this node?

> why would someone build that?
It's too expensive for a POWER NODE
Just use regular power nodes instead

> this doesnt deserve to exist

And why to use this impact it is so expensive and use surge just spam more reactors, and why to use reactors it is expensive and may explode just spam more differential, and why to use differential it needs pyratite and cryo just spam more generators...etc.
and why to use mass drive it is expensive and eats power, just spam the free cheap normal conveyors, it makes no sense and it doesn't deserve to be in the game.

Guys, before i made this suggestion i expected to get attacked because it is over powered, so i thought well if it is so or not then i got a conclusion that it is powered but not op, it fits T5, Foreshadow and impact, ..etc

I never expected to see people think it is not important and doesn't deserve to be in the game, ever!!!
I don't want to be toxic, but if you couldn't see the latent power in this block....

**Comment by Kyllingene** [comment]
> And why to use this impact it is so expensive and use surge just spam more reactors, and why to use reactors it is expensive and may explode just spam more differential, and why to use differential it needs pyratite and cryo just spam more generators...etc.

Ah, the trusty [slippery slope fallacy](https://wikipedia.com/Slippery_slope). They are correct here; spending a ton of expensive materials, and taking up a ton of space, to replace cheap power nodes that can be slotted in just about everywhere, is a really bad idea. The only way to counteract this would be to reduce either the size of the block, or the build cost; but neither of those would fit with the game, nor would they be fun to play with.

**Comment by MrDuck557** [comment]
Also, what niche will it fill? Power nodes are power nodes, large power nodes are better titanium power nodes, and surge towers are long distance transport nodes. This is what?
Even if you have, I dunno, 100 small power nodes, they have exactly the same efficiency as this one power node. So no point in replacing. Health is irrelevant because you can just put the power nodes behind your walls.

**Comment by OnyxFinger** [comment]
> this doesnt deserve to exist so yeah mods make sense in this context

yes, and he didn't develop so you can't say I'm dumb, I even said it myself.




> > Mods.
> 
> Haha, aside from the point that mods is not an answer, so you want me to use a mods for a feature will not change anything in units, resources, factories...ect, it just will make the things easier and more organized.
> lets assume that the plastanium conveyors wasn't in the game, and someone wanted a faster way to transport the items so he suggested plastanium conveyors , then you come and say: use mods, so he should use the mod just to be able to "enjoy" using this fast conveyor, hahaha, guys that's not smart at all.
> 
> The "Mods" could be a solution when someone wants a feature will make a "**DRASTIC**" change in the game, such a change will affect a lot of game aspects like new resources units factories ..etc.
> 
> I will not make a mode just to use plastanium conveyor, or mass drive, or super node, no sense at all.
> 
> > Mods aren't an awnser. you can't just say "mods" to anything, if an object deserves to be in the game but exists in mods, then it has to get added EVEN if there is a mod for it, for the sake of mindustry.
> > If the object doesn't deserve to be added, just say at least also why, in your opinion.
> 
> That is exactly the thing.

yes but no, it's not because one part of my argument is a tiny bit in your favor that the other isn't just saying that what you made is stupid.
And there are a few things to make this node less vital : multiple of them, smaller, more replaceable and more easily double layerable nodes, that is saying that aircraft will ever go through your defenses since you can just place the node out of ground's path, which is very unlikely.

>And why to use this impact it is so expensive and use surge just spam more reactors, and why to use reactors it is expensive >and may explode just spam more differential, and why to use differential it needs pyratite and cryo just spam more >generators...etc.
>and why to use mass drive it is expensive and eats power, just spam the free cheap normal conveyors, it makes no sense and it >doesn't deserve to be in the game.

You can get much cheaper power with impacts, and surge is proably never gonna be a problem when you play, just balance your economy for optimal production.
UNits such as T5 fit because they have properties such as massive damage and pierce for omuras, or they're just unbalanced so they exist for no reason, so if the node gets added it will be bad (unbalancement like reigns and other bad units), cuz you can't spam T1 to remake the strength of a T5, but you can with smaller nodes. same for foreshadows, only one thing can outrange it : omura. Even logic range increase can't reach as far. There is then a point, also it's more space efficient whihc you need in defenses, but not really in your main base usually. That's why the node doesn't fit like T5/foreshadows

**Comment by Sector171** [comment]
> With the impact reactor, it takes less space to make more power; with this node, it takes more space and materials for the same output.

Totally wrong comparison
It looks you didnt read well the main purpose of it, it is to clean the area and save space! 6*6 maybe i exaggerated a little but even so it is still smaller than the smallest graphite scheme i use. you put one and that's it. where are the "tons" of space you are talking about here??!!
Now what is the output of power producing block? it is the power, so yeah the more expensive ones the more power, less space.
So what is the output of a power node? it is 2 things: the connections , the range. lets see in this block: connections : unlimited, range: huge. see??

> but neither of those would fit with the game

why? justifications??

> nor would they be fun to play with

i would like to ask you but i want an honest answer, imagine that you are playing (campaign, PvP, attack, Survival...) and you start producing the valuable items, and you have a chance to make this station which cost about(100-200 phase, 100-200 surge, 300 plastanium, 500 silicon, 700 lead) will you waste them to build this block which cover a huge area and makes the power available without any need to spam power nodes or not, provided that you have enough resources? just put yourself in this situation and give me an honest answer, and will it be fun or not seeing the area clean from these wires.

> what niche will it fill?

and can you give me what "niche" did the large power node added to the game? nothing , you can play without it using small ones, but yeah i see it important cuz it has more connections, longer range, stronger(important in frontline)
ofc if you cant see cleaning the area and save space, the ability to spam menders projectors turrets which get the power from a long distance and the attacker cant cut off the power source from them as a "niche" nothing i can say.

**Comment by oinkymoo** [comment]
this is a long-distance power-transfer block. surge towers already fill that niche. you rarely have such a large area filled with power consumption that: a) has a low enough density of power consumption that the whole thing cannot be connected with individual nodes between structures and b) has enough such disjointed power consumption over such a large space that 9 surge towers, which have the same footprint as your proposed "power station", would not be able to connect everything

**Comment by Kyllingene** [comment]
> i would like to ask you but i want an honest answer, imagine that you are playing (campaign, PvP, attack, Survival...) and you start producing the valuable items, and you have a chance to make this station which cost about(100-200 phase, 100-200 surge, 300 plastanium, 500 silicon, 700 lead) will you waste them to build this block which cover a huge area and makes the power available without any need to spam power nodes or not, provided that you have enough resources? just put yourself in this situation and give me an honest answer, and will it be fun or not seeing the area clean from these wires.

I would rather have to skillfully weave my power nodes into my factories than simply place down a large, expensive  tower and forget about it. It would be quite boring.

> ofc if you cant see cleaning the area and save space, the ability to spam menders projectors turrets which get the power from a long distance and the attacker cant cut off the power source from them as a "niche" nothing i can say.

Surge towers exist, and so do walls. Use them, don't ask for more bloat. And no, I don't think that making the game more mindless is a fun mechanic.

> So what is the output of a power node? it is 2 things: the connections , the range. lets see in this block: connections : unlimited, range: huge. see??

You misunderstand me; if you simply use your brain a little, you can easily connect most factories and defenses with power nodes. If it is impossible, then you can use surge towers. You overstate the necessity for this. By your logic, you might as well only use the impact reactor as soon as possible; however, you often don't need the extra power, especially at the added risk. So, you often just use a thorium or even a differential. The entire use case for this block is sheer laziness.

**Comment by Sector171** [comment]
> I would rather have to skillfully weave my power nodes into my factories than simply place down a large, expensive tower

OK first i asked for honest answer and that's was yours nothing to say, second apparently you don't want to use your brain to understand the point of it (or maybe you used 200% but that what you could get). so no point to repeat and repeat to make you understand that it is advanced thing, dont compare Nova with Corvus or combustion with impact saying yeah i can spam more of these tiny combustion no need for impact wasting "tons" of space(4*4) and tons of valuable resources including 250 surge,

Why all these power producing blocks in the game??were they in the game from beginning or got added as needed to make the player life easier?? why there is silicon smelter and crucible? why there is graphite press and multipress? cant you using the normal press to produce your need of graphite even for commercial purpose to make T5?? why there is large node, what "niche" did this large node add to the game? cant you finish your game without using them? why did the designer add all these "bloat" to the game, go and make suggestion to remove all these extra unneeded stuff.

How boring is it to use impact, such a huge amount 7800, and if boosted up to 15000, only "lazy" "brainless" people use it.
Overflow and Underflow and these bullshit, go use some tricks with routers or use logic you brainless lazy boring people, you want everything ready to use, so boring.

>  you can easily connect most factories and defenses with power nodes. If it is impossible, then you can use surge towers.

I will quote some of things i already said just to show that you dont want to understand

> like nodes, with priority to nodes first,which means it will not connect "Directly" to a building if it is already connected to a node within its range

> As you can see this block will not replace the nodes or surge tower, even in advanced stage of the the game and after building this block, there will still be a real need for normal nodes

> you will not need to use even these small node(except the ones related to a scheme, the pro player will keep it)

About its importance
>  You overstate the necessity for this

yeah maybe, we already playing without it, but it is the case with every new thing before gets added you will not feel its importance until you get used to it, but i felt it fits the last stages of the game after establishing a good base , that's it, maybe i am wrong, but i just don't like non sense comments.

> By your logic, you might as well only use the impact reactor as soon as possible

That's exactly what i do, if it is in my hand cuz i will solve the power issue so i can move freely to start using the big schemes, if it is not an easy choice i will see what it is the best for this situation.

**Comment by itcannotbe** [comment]
Did no one mention that surge tower can be easily made to connect to multiple blocks. Just throw in power nodes exactly beside the surge tower.

This suggestion doesn't even deserve to exist. Period.

**Comment by Sector171** [comment]
> imma take this idea and slap it into Mindustry+
please dont kill me

Nice, I can see now the practical usage of it, I will advice you to take the feedback into account, maybe the only useful feedback in the whole trash above was the size, make it smaller maybe 5 * 5, or 4 * 4 I don't know. Also give it the ability to store power, how did I forget this,ofc it is power station, maybe 300k or more.

> Just throw in power nodes exactly literally the surge tower.

> This suggestion doesn't even deserve to exist

I didn't want to reply to you Mr.No because you don't deserve really,  everything No for you, for show off, even if you make a suggestion I will not be surprised to see you making comment saying "No" it is bad suggestion. But since I had to comment...
So you smart want to sourround a surge tower with nodes, now you got a lot of connections, but what is the range? What about the blocks around?  You need again to spam nodes haha see how smart are you, killed the first and most important point of this station. Again in front line you need nodes which could be easily targeted, killed the second point of it.
But I know why people can't understand it, because only few people can deal with abstract things, because you can't touch the output here, for power production blocks there is the power, for multipress there is the graphite, for drills there is items(more items).
By the way, why even the air blast drill exist? What niche or specific feature did it add? Nothing nothing at all, it is just quantity nothing more. Laser drill can do everything well. But yeah people wait the moment to be able to replace all drills with airblast one, so..
Airblast drill= power station. Period

**Comment by itcannotbe** [comment]
You do realize that if anuke actually wants us to have a power transfer block

**Comment by itcannotbe** [comment]
Also I am not all "no" there are suggestions out there that are good suggestions, and I don't bother to comment on them if I have nothing to add on.

But obviously this isn't one of the good ones.

**Comment by itcannotbe** [comment]
> By the way, why even the air blast drill exist? What niche or specific feature did it add? Nothing nothing at all, it is just quantity nothing more. Laser drill can do everything well. But yeah people wait the moment to be able to replace all drills with airblast one, so..
> Airblast drill= power station. Period

P.S. Airblast boost better than Laser.

**Comment by itcannotbe** [comment]
Let's break this down.

> why there is silicon smelter and crucible?

Because past midgame you'll be eating through a lot of silicon, thus a T2 production block.

Also if you compare the 2, aside from reduced coal item usage per silicon made and faster production per silicon made, the crucible also requires pyratite to be provided, aside from being being larger from the silicon smelter.

Thus, it's not a drop in replacement. Plus the additional burden to operate a T2

> why there is graphite press and multipress?

The graphite press only requires coal to produce graphite, while the multipress press, despite reduced coal usage per graphite produced also requires power and water.

Again, it's not a drop in replacement. Plus the additional burden to operate a T2 again.

> cant you using the normal press to produce your need of graphite even for commercial purpose to make T5?? 

See above.

> why there is large node, what "niche" did this large node add to the game?

The larger node has a slightly higher range and slight more connections compared to a power node. And these block are just carry overs from previous versions of the game. Also while you can progress the game with just a large power node, it isn't accessible early on. Thus the need to retain the smaller version.

**Comment by Sector171** [comment]
Lets start from the last, first don't fish in the muddy water. In which context did i use plastanium conveyor as example? not to support my suggestion(even though i can), but just to reply to the "Mods" word.
And yeah it is still a conveyor, can we play without it ? of course we can, so why does it exist?? because it makes the player's life better, and improves the playing quality, also it fits another blocks like multipress and .crucible.

Third, your justifications about multipress and .crucible and large node is literally bullshit, ofc they are more expensive and need power or more power and input, that's doesn't matter at all, what they do is just more graphite and more silicon, nothing else, can we play without them, yes we can without any problem, but the game maybe harder that's it. no niche , but yeah they are useful, the game needs pushed to add them, and now, is there such a need for this power station? in my opinion yeah ofc there is, got bored from this wires here and there, better and comfortable visual view and more organized space...etc in addition to give a thing to defenses(you can just spam lancer, or meltdown with water extractor and they immediately will get the power) that's the output, i hope if you can understand it.
Also stop comparing surge tower with it is bad comparison just because it has high range, surge tower task only to connect tow networks, two nodes, that's it, so please never compare again, but you can compare it with nodes.

**Comment by 1ARC1** [comment]
just stop fighting over a single stupid suggestion and add it with mods,  this is getting ridiculous

**Comment by OnyxFinger** [comment]
> just stop fighting over a single stupid suggestion and add it with mods, this is getting ridiculous. not like it deserves to exist anyways

M O D S   B O O H
he's kinda right tho

**Comment by Kyllingene** [comment]
I fail to understand how you fail to see that *every late-game upgrade has a drawback*. Silicon crucible, multipress, phase conveyor, disassembler, *insert turret here*, overdrive dome, mend projector, plastanium and armored conveyors, thermal pump, plated conduit, surge tower, every level of generator after combustion (including solar panels), laser and airblast drills, hyper processor, and probably more that I missed.

You see the pattern here? Even many early-game blocks have drawbacks compared to their predecessors, but this would be a drop-in replacement so you never have to think strategically again. Why on earth do you think that removing depth from the game by adding a bit of complexity is a *good* thing?

**Comment by Kyllingene** [comment]
True, very true.

**Comment by OnyxFinger** [comment]
> I fail to understand how you fail to see that _every late-game upgrade has a drawback_. Silicon crucible, multipress, phase conveyor, disassembler, _insert turret here_, overdrive dome, mend projector, plastanium and armored conveyors, thermal pump, plated conduit, surge tower, every level of generator after combustion (including solar panels), laser and airblast drills, hyper processor, and probably more that I missed.
> 
> You see the pattern here? Even many early-game blocks have drawbacks compared to their predecessors, but this would be a drop-in replacement so you never have to think strategically again. Why on earth do you think that removing depth from the game by adding a bit of complexity is a _good_ thing?
> 
> Note: Yes, I am aware of some drop-in replacements (like large power node or titanium conveyor). Those are because it is a pain to wait for slow item transport, or to have to completely redesign your base or schematic to transfer power with small power nodes. The difference between the large power node and this power node is that there is already a surge tower.
> 
> Anyway, thank you for closing, and I apologize for any toxicity incurred during this discussion, whether it be mine or someone elses.

yes but the drawback is worth going for anyway.

also pplleeaassee don't say that the node would need more things to operate, this would also be bad.
anyway. well other than that I'm tired of this 50-ish messages so bye I'm sick of life (exageration of course !)

**Comment by SMOLKEYS** [comment]
> Nice, I can see now the practical usage of it, I will advice you to take the feedback into account, maybe the only useful feedback in the whole trash above was the size, make it smaller maybe 5 * 5, or 4 * 4 I don't know. Also give it the ability to store power, how did I forget this,ofc it is power station, maybe 300k or more.

*im still tryna understand this*
