### ISSUE TITLE
Balancing: Doubling of maxInstructions per processor level?

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2393]
**Describe what you would like changed, and why.**
With somewhat more complicated scripts I very often have more than 1000 instructions, mainly also because of the debug code, e.g. to output the status. 

**Describe the changes you want to propose. Include possible alternatives.**
Therefore it would be great if maxInstructions could be set to 2000 in general.
2000 instructions do not mean that so many instructions are executed in each iteration 😄 

An alternative would be to double maxInstructions for each processor level.

**Comment by OnyxFinger** [comment]
how would you need to use over 1k instructions ? even complicated code doesn't take this much, logic wasn't made for people to play around with it's nonsense, and if you have this many instructions the processors will be slow af, so you better get multiple processors anyway.

**Comment by RedstonerKBC** [comment]
1000 lines of code is a lot for a single processor. You might wanna consider using functions and getting into multi-processing.

**Comment by joshuaptfan** [comment]
If anything, Anuke is [inclined to _reduce_ max instruction count](https://discord.com/channels/391020510269669376/742769933926269069/752163331153985537):

> instructions are limited to 1000 because values larger than that cause significant lag when opening, closing or scrolling the instruction UI on mobile devices

**Comment by Legomonster33** [comment]
> If anything, Anuke is [inclined to _reduce_ max instruction count](https://discord.com/channels/391020510269669376/742769933926269069/752163331153985537):
> 
> > instructions are limited to 1000 because values larger than that cause significant lag when opening, closing or scrolling the instruction UI on mobile devices

and you can cause crashes + memory leaks with large amounts of instructions

**Comment by Bergiu** [comment]
an easy way to support this is to remove the final keyword. then it's easy to write a mod that increases this value. i would find that great.
