### ISSUE TITLE
Logic option for sensing the unit item transfer timer

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2394]
**Describe the content or mechanics you are proposing.**
Whenever the `itemDrop` or `itemTake` commands are used, there seems to be a 2 second timer until either of those commands can be used again on that unit. I'd like to be able to use the `sensor` command to check the time remaining until this timer expires. It could use a name like `@itemDelay` or `@itemTransferDelay`.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would greatly simplify item transport systems that use logic. Currently, if I want to wait until the item transfer timer has expired, I can do something like this:
```
op sub tdiff @time t0
jump 0 lessThanEq tdiff 2000
```
However, this is only possible if I know exactly when the `itemDrop` or `itemTake` commands were used, which would be nearly impossible in situations involving multiple processors. With the suggested changes, the following would be possible:
```
sensor delay @unit @itemDelay
jump 0 greaterThan delay 0
```
Which would eliminate the need to track the original time when the `itemDrop` or `itemTake` commands were used.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Stronger processor?

**Comment by BenMan95** [comment]
> Stronger processor?

I don't see how this would help. This isn't an issue of not having enough processing speed, this is something that is completely impossible with the current sensor parameters.

**Comment by IVV-NCX** [comment]
I mean, you said you used multiple processors, so why can't you use a more powerful one that holds more instructions?

**Comment by BenMan95** [comment]
Unfortunately, what I'm working on uses multiple processors spread out over a large area, so it won't be possible to use a single more powerful processor. Besides, even if using a more powerful processor was an option, it would still be helpful to have the suggested changes implemented.

**Comment by IVV-NCX** [comment]
What about link pins?

**Comment by BenMan95** [comment]
What do you mean?

**Comment by IVV-NCX** [comment]
Nevermind, it's a modded item that allows you to "pin" more things together, so multiple logic blocks can work in sync.
