### ISSUE TITLE
Damaged walls can be replaced with a new one.

### ISSUE THREAD

**Issue by Andraez** [Anuken/Mindustry-Suggestions#2395]
You can build new copper walls over a damaged copper wall, and the same with other types of walls.

**Comment by MrDuck557** [comment]
\*butchers template*
but why though, just use mender

**Comment by the-kido** [comment]
> but why though, just use mender

Being able to replace the wall fixes the wall faster. Even breaking and replacing the wall is faster than letting the mender do it. The only downside is that it is manual (but not if you use logic)

**Comment by SMOLKEYS** [comment]
yes
add this
i have been suffering for too long

also

template: ***WHY WHY WHY WHY WHY WHY***

**Comment by 1ARC1** [comment]
> *butchers template*
> but why though, just use mender

requires power and more resources, so building a new wall or repairing it with the same resources is a good idea. this would be a nice QOL feature, you don't always have menders, and you don't always add them to every part of your base.

**Comment by 1ARC1** [comment]
> i feel like wall repair in this manner might be cheaper in the short-term but will rapidly become more and more expesive if used frequently

it'd be handy when you want to repair one or two things in your base, not as an actual way to repair entire defences, just small sections.

**Comment by itcannotbe** [comment]
Let me ruin this suggestion by saying this has been suggested before.

**Comment by itcannotbe** [comment]
Who even gives these people a butchered link to allow them to skip the freaking template? It's just idiotic to be frank.

**Comment by OnyxFinger** [comment]
it's just dumb : you are supposed to need a healer to heal your walls, it shouldn't be made even easier to reapir without them, no matter how easy it already is.

**Comment by oinkymoo** [comment]
> > but why though, just use mender
> 
> Being able to replace the wall fixes the wall faster. Even breaking and replacing the wall is faster than letting the mender do it. The only downside is that it is manual (but not if you use logic)

1. you can't actually destroy buildings with logic, except for explosions
2. if you have a unit that can build things, it can also repair things, for free. the only units that can build but not repair are spiroct and up, and why are you using those to build, and the player units, which kinda defeats the whole purpose of using logic to automatically replace things

**Comment by itcannotbe** [comment]
If by anything, it kinda defeata the purpose of being repaired if under fire, as this isn't v3/classic.

Blocks aren't instanly replaced, but has a build time that varies by block cost and some other factors.

And we all know how blocks under construction handles enemy fire. (*Hint* not good at all.)

**Comment by itcannotbe** [comment]
Also the only reason you don't have access to menders in the first place in the early game is in campaign when you still haven't unlocked it.

**Comment by oinkymoo** [comment]
though at the time this suggestion was made they still were not

**Comment by Humanoid-X** [comment]
Why are duplicaates allowed now??? *utter confusion*
