### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2398]
**Describe the content or mechanics you are proposing.**
Scenarios could be a separate game mode, not related to campaign or the story.
Essentially:
You start at a certain position and try to reach a goal. Different missions can be configured, like in build63.
For instance:
You start with a well developed factory, with a large fleet. Guardian comes in 2 waves. Yours is to defend the core.

You have control over 4 Quasar mechs. Mission is to defend your core from enemy swarms.

You have control over a Quad ship. Haul the cargo from Core 1 to Core 2. Path is attacked and you have 5 minutes to pass. Building is permited.

These are meant to be a challenge, with potential of sharing scenarios between players

*Creating scenarios*
Could use a logic-like graphical editor with:
*Triggers* activate something when a certain goal is reached, can detect anythig logic can.
*Enemies* spawn hostiles when triggered
*Help* brings materials and/or buildings at a specific location
*Weather* changes map weather
*Modifiers* affect any game rule
*Goal* indicates win conditions.
*Timer* can be a part of trigger, affects something once some time passes from a certain point.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Adding what to do once you finish campaign. Adds posibilities to create scenarios.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
So basically player created challenges

**Comment by IVV-NCX** [comment]
So basically, custom maps, but add logic to it. I would love to see there be a way to have invisible logic, but otherwise, meh.

**Comment by OnyxFinger** [comment]
> So basically, custom maps, but add logic to it. I would love to see there be a way to have invisible logic, but otherwise, meh.

logic is very limited as of now and is untouched by many people, maybe not so much for scenarios.
Other than that, I agree.
I don't really know what to think about this one

**Comment by BorisA11** [comment]
> So basically, custom maps, but add logic to it. I would love to see there be a way to have invisible logic, but otherwise, meh.

Sorta, but with better logic system

**Comment by SheepCommander** [comment]
kind of interesting but dunno
