### ISSUE TITLE
Fit sprites on block size

### ISSUE THREAD

**Issue by bestGaming1320** [Anuken/Mindustry-Suggestions#240]
**Describe what you would like changed, and why.**

Currently when sprites are bigger or smaller than a block it is displayed wrong and I think that should be changed because it would be easier to make sprites and higher quality sprites on smaller blocks would be possibile

**Describe the changes you want to propose. Include possible alternatives.**

Sprites should fit the block size instead of just displaying them how they are

**Comment by Anuken** [comment]
This is fundamentally unsupported and will break *all* block rendering code if implemented.
