### ISSUE TITLE
Nitpick Visual: The input bridge conveyor connects and displays like it can output

### ISSUE THREAD

**Issue by SheepCommander** [Anuken/Mindustry-Suggestions#2401]
**Describe the content or mechanics you are proposing.**
The input bridge conveyor connects to conveyors as if it was an output, and that doesn't make sense.
![image](https://user-images.githubusercontent.com/66646514/117611030-99f0ee80-b117-11eb-82ba-d09e03e24222.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Blocks that only accept input, such as turrets, do not connect to conveyors. This is a very minor visual inconsistency that does not impact anything, nor does it bug me, but it doesn't make sense when I think about it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
https://github.com/Anuken/Mindustry/issues/5162

**Comment by SheepCommander** [comment]
FU-

**Comment by SheepCommander** [comment]
_I swear_
