### ISSUE TITLE
Flying Support Naval Units

### ISSUE THREAD

**Issue by kapzduke** [Anuken/Mindustry-Suggestions#2402]
**Describe the content or mechanics you are proposing.**
Support naval units will be able to fly over terrain or not water. Just like any other ground unit, they won't be able to fire while in the air. Naval units will only be able to carefully land over water.
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will allow for a simpler transportation of naval units, without requiring a ride from advanced air units (such as Mega).
(note: they won't be able to transport other units)
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
"Oh it's cool" is not a good reason for a suggestion
That's what I think your reasoning is

**Comment by SMOLKEYS** [comment]
***DO NOT. THAT IS TOO UNBALANCED.
CLOSE
NOW
OR ELSE***
![images (8).jpeg](https://user-images.githubusercontent.com/75618732/117682435-a0e63280-b1e5-11eb-8e55-5b8e67087ffa.jpeg)

**Comment by IVV-NCX** [comment]
Use a mega like you said. More balanced.

**Comment by numer99** [comment]
why are you suggesting something that already exists in the game:
air support units

**Comment by kapzduke** [comment]
> why are you suggesting something that already exists in the game:
> air support units

because they don't exist in the game yet

**Comment by Humanoid-X** [comment]
...Do you truly understand what "naval" means

**Comment by SheepCommander** [comment]
oh my

**Comment by kapzduke** [comment]
> Maybe the next suggestion would be swimming ground units or swimming flying units.

that would be cool too

**Comment by SheepCommander** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH
