### ISSUE TITLE
жъжжжъь

### ISSUE THREAD

**Issue by dragonMau** [Anuken/Mindustry-Suggestions#2404]
**Describe the content or mechanics you are proposing.**
добавить новый чат в дискорд "жъжжжъь" для выяснения отношений табуретки и воздуха

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
меньше спама в #руский больше в #жъжжжъь

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Google Translate:
'add a new chat to the "U" string for displaying the new tabs and covers'

Are you asking for emoji that represent the icons for the building tabs?

**Comment by Yell245** [comment]
They're suggesting a "zhhhhhh" channel especially for spam so there won't be that much spam in #russian. Tf lol

**Comment by Yell245** [comment]
Anuke is slowly going insane when such suggestions appear

**Comment by dragonMau** [comment]
i tried to find rule that prohibits suggestions like this, but not found

**Comment by MHeMoTexHuK** [comment]
> They're suggesting a "zhhhhhh" channel especially for spam so there won't be that much spam in #russian. Tf lol

No, especially for VozDuh and Taburetka. Btw he's kidding

**Comment by SheepCommander** [comment]
b r u h lmfao
