### ISSUE TITLE
Area effect indication

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#2405]
**Describe the content or mechanics you are proposing.**
When placing a mender or overdrive, activate the range indication (circle) of all buildings of the same type or effect.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will help with placing the building in a nice spot, with less overlapping area effects when you don't want that.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
One question
Where should the radius be shown?
If every overdrive projector on the map gets shown at once, it's going to cause a bit of lag

**Comment by oinkymoo** [comment]
i mean it should at least be limited to what's on screen
