### ISSUE TITLE
Automatic Tile Edge Blending

### ISSUE THREAD

**Issue by SlavaCat118** [Anuken/Mindustry-Suggestions#2406]
**Describe the content or mechanics you are proposing.**
Automatically set the color of edges to either the average color of the sprite, or what ever is on the very edge. 
![image](https://user-images.githubusercontent.com/71950453/117758766-74c3b500-b1d7-11eb-8f8b-84ee0fbe376a.png) 

-----------------------------------------------------------------------------------------------------------------------------------------
**Describe how you think this content will improve the game.**

It will make it much easier for people who just want to make simple texture packs to have a good looking result, without having to learn a whole bunch of scripting for a small thing. It would be a boolean option in the 'mod.json' file under the tag 'auto-blend-edges'.

There could alternatively be an option in the base game to enable/disable this.

---------------------------------------------------------------------------------------------------------------------------------------------

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by abrasmag3** [comment]
instead of in mod.hjson, this should be a boolean per tile
