### ISSUE TITLE
TD Features

### ISSUE THREAD

**Issue by ItsBUESCTime** [Anuken/Mindustry-Suggestions#2407]
**Describe the content or mechanics you are proposing.**

W (Walkable such as units) Blocks can Transparent from ground blocks such as grass (ground) , water and ores. It can be also replaceable of solid blocks such as dirt block.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will make your units and Enemy Units walks perfectly and it stragety form such as reference of TD. It will perfectly make a TD Maps.
This is example 
![Untitled3_20210511165041](https://user-images.githubusercontent.com/84010229/117787814-629a5300-b279-11eb-8c16-574beb2f28fb.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

I comfirm that reference to TD. I should make TD Maps when the updates out.

**Comment by Dioo0** [comment]
> i like this idea
> but
> why though
> 
> mindustry is already a TD game

probably he means server's TD, like when enemies follow certain path

**Comment by Kyllingene** [comment]
But the entire gimmick that makes Mindustry different from most TD maps is that it's *not* a set path. If you want a traditional TD game, go play one.

**Comment by Humanoid-X** [comment]
@Dioo0 Lol true... He's probably drawing basic turret in Infinitode 2? I dunno...

@Kyllingene Agree!

**Comment by SheepCommander** [comment]
that turret looks like something I'd s-

But hmm if you want to create tower defense mini-games inside the game that's entire purpose is to not just be tower defense, it'd be more interesting to see this done with logic or mods than as an ingame feature.

**Comment by ItsBUESCTime** [comment]
It look like this I made of maps
![Screenshot_2021-05-10-07-51-52](https://user-images.githubusercontent.com/84010229/117953080-60eb9080-b348-11eb-9a1c-29d237aaa3d7.jpg)

**Comment by ItsBUESCTime** [comment]
About this, I tried to make that map. It contain AI Water units has small chance to reverse back.

**Comment by ItsBUESCTime** [comment]
And... I made a difference of that map. Many waves has different enemy units, not the same from default. I Configured a block health into 2 and attack was default one. Also units into 0.4 too.

**Comment by ItsBUESCTime** [comment]
Same from TDS in Roblox

**Comment by ItsBUESCTime** [comment]
I worked alot of waves, I hope I submit my map.
