### ISSUE TITLE
Soundtrack selector

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2408]
**Describe the content or mechanics you are proposing.**

I dont think this will be too hard to implement, essentially:
Once game is downloaded, have a file in which you add music you want to play in game. By default it's Mindustry tracks.
There are certain tags, default would have: #space, which is the space track, old tech tree one, #boss, which are boss1 and 2, #game, which are game tracks that play in game, #menu which are menu tracks. Each tag has its own file. 

In game, add a setting wich allows you to play specific tracks from a specific file, eg, #game, "game4". This results in game 4 being played once. 

Ability add new files, which allows for more diversity when modding. Eg, #building, tracks that are played when you build X blocks, or #spores, which plays in spore maps. 

If player wants to, he/she can add own tracks to the list, and game will recognise them based on the tag file it is in.

Maps can have included tracks and excluded tracks, for example you dont want a happy game4 in a spore ridden map, you want something to fit the atmosphere better.

Overall, it should be simple enough to do, and will become extremly useful in v7, and for people who for some reason want old game4, or some excluded tracks.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> *mods are already able to do everything you listed here*

provide some mods please
i wanna use those

**Comment by QmelZ** [comment]
> > _mods are already able to do everything you listed here_
> 
> provide some mods please
> i wanna use those

i mean nobody has a complicated music mod, yet

**Comment by SMOLKEYS** [comment]
> > > _mods are already able to do everything you listed here_
> > 
> > provide some mods please
> > i wanna use those
> 
> i mean nobody has a complicated music mod, yet

soontm go brr

**Comment by SheepCommander** [comment]
_mods and close_

**Comment by BorisA11** [comment]
@SheepCommander not closing, as it is still not in vanilla game. Mods can do everything that gets suggested here, but can you play multi with mods? Nope. Share campaign saves? Nope. And mods never come with just the feature you need. Once you make the mod that does that, I'll close right away

**Comment by itcannotbe** [comment]
Mods and close.

Why? Because can be easily be done by mods and this suggestion doesn't even have any implications on gameplay.

Also maps with sound included? You kidding me? You just turned something that's supposed be a few KB into something more and it doesn't even have a good enough impact to gameplay.

**Comment by QmelZ** [comment]
> `@SheepCommander` not closing, as it is still not in vanilla game. Mods can do everything that gets suggested here, but can you play multi with mods? Nope. Share campaign saves? Nope. And mods never come with just the feature you need. Once you make the mod that does that, I'll close right away

if you make the mod compatible, yes multiplayer with mods is possible.

share campaign saves that include mods? if the mod doesn't add *content*, you can

"mods never come with just the feature you need" this is why they are "mods", if you want a feature, you make a mod to add that. nobody is going to make a mod that does exactly what you want just for you.

go make your own mod, and close this suggestion.

**Comment by SheepCommander** [comment]
> @SheepCommander not closing, as it is still not in vanilla game. Mods can do everything that gets suggested here, but can you play multi with mods? Nope. Share campaign saves? Nope. And mods never come with just the feature you need. Once you make the mod that does that, I'll close right away

This is not something that deserves to be in the base game in the first place. **Close it.** When you want it but it doesn't deserve vanilla, the answer is mods.

Yes ofc you can play multi with mods tf you on. Client side mods are client side mods. Mods that add new content whoever joins just needs to have the mod installed too. "Share campaign saves" ???

No I'm not making a mod for you. If you're too lazy to do it yourself and no one else sees any merit in adding user-friendly edit the soundtracks, then just mute the game and play your own music .-.

**Comment by Kyllingene** [comment]
The part of this suggestion that is mods adding more sounds is already possible, and the part that is allowing users to play custom music through Mindustry is pointless as long as you use an OS that supports audio playback. If you don't, it's pointless anyway.
