### ISSUE TITLE
Upgrade system

### ISSUE THREAD

**Issue by RetroGaming2077** [Anuken/Mindustry-Suggestions#241]
putting an improvement system in turrets, units and mechs would make the resources more useful.

**Comment by RogueRedHawk** [comment]
Upgrade systems for drones are currently being worked on for the 6.0 update.

**Comment by RogueRedHawk** [comment]
https://cdn.discordapp.com/attachments/513178557653188609/721548117044101171/2020-06-13_22-12-57.gif

**Comment by itcannotbe** [comment]
Sort of duplicate of #157 but in general.
