### ISSUE TITLE
Mention jump labels in the wiki

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2411]
**Describe what you would like changed, and why.**
In the wiki pages for logic, there is no mention of jump labels. If you only look at official resources, it is impossible for a player to ever know that jump labels exist, or the correct syntax to use them. Even if someone knows that jump labels exist, it can be difficult for them to find out the correct syntax to use them. I was only able to learn the correct syntax by checking the syntax in assembly. One of the biggest barriers to writing logic with a text editor is handling jumps, so this is a pretty big oversight.

**Describe the changes you want to propose. Include possible alternatives.**
Add a section in the wiki to explain jump labels and the correct syntax to use them.

**Comment by oinkymoo** [comment]
the only thing i'm missing that i'd need to do this myself is knowledge of jump label syntax

**Comment by BenMan95** [comment]
> the only thing i'm missing that i'd need to do this myself is knowledge of jump label syntax

To write the label, add a line with the name of the label and a colon like so:
`myLabel:`

Then in the jump instruction, replace the line number with the name of your label: 
`jump myLabel notEqual x false`

Note that this only works in 126.2.

**Comment by Kyllingene** [comment]
> Note that this only works in 126.2.

And later?

**Comment by BenMan95** [comment]
> > Note that this only works in 126.2.
> 
> And later?

126.2 is the currently the latest release.

**Comment by oinkymoo** [comment]
126.3 exists on steam and android i think?

**Comment by Kyllingene** [comment]
On steam at least. Also, beta builds are a thing.
