### ISSUE TITLE
Exoskeleton / Outposts

### ISSUE THREAD

**Issue by LeoVen** [Anuken/Mindustry-Suggestions#2412]
**Describe the content or mechanics you are proposing.**

- 3 new mechs, 1 mech for each type (land, water, air)
- Player's unit (alpha, beta, gamma) enters the mech
- These mechs don't move or attack by themselves
- If the player exits, it gets spit out of the mech instead of respawning at base
- Can control units of their type (land, water, air)
- The group control remains even after the player exits the mech
- Possibly T4 or T5 strong

Possibly very slow unit, like a walking/swimming/flying castle where its only purpose is to station units somewhere far off from your base, but that can also attack and defend itself.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Lets say you are playing in a big map and you have a detachment of very slow units very far from your base. You might want to be able to exit the mech, do repairs, build stuff and go back at controlling the units. These exoskeletons can be used as outposts and players can quickly got back and forth from action/building.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Massive flaw with making units that you can exit without going back to core: combining them with the pan feature results in instantaneous travel that ignores enemy defenses.

**Comment by SheepCommander** [comment]
It's kinda a cool idea but also kinda flawed and would need to be flushed out more

**Comment by Humanoid-X** [comment]
Btw @Kyllingene, how do we pan in PC????

**Comment by oinkymoo** [comment]
mouse forward or mouse back, by default

**Comment by Kyllingene** [comment]
@Humanoid-X, Look in the keybinds.

**Comment by Humanoid-X** [comment]
Yeah I looked in the keybinds but can't find it... Eyesight problem? Nvm I try again today

**Comment by oinkymoo** [comment]
they're the 3rd and 4th on the list, right below movement. a lot higher than you probably thought to look
