### ISSUE TITLE
T5 naval support naming

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#2413]
**Describe the content or mechanics you are proposing.**
Name the t5 support boats after elementary particles.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Avoidance of repetition. We've had:

* types of radiation (core)
* types of stars, constellations (ground support)
* medieval terms (ground neutral)
* spiders (ground sapping)
* types/regions of star occlusion (flying neutral)
* counts and latin prefixes (flying support)
* whales (naval neutral)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
All support boats then, please edit title to clarify

**Comment by oinkymoo** [comment]
correct me if i'm wrong, but aren't alpha beta and gamma just the first 3 letters of the greek alphabet

**Comment by Anuken** [comment]
All the support navals were named even before I made the first tier. I am not in need of names.

**Comment by BasedUser** [comment]
excellent

**Comment by IVV-NCX** [comment]
Dang, would've been epic to see one named Neutrino.

**Comment by RedstonerKBC** [comment]
If we get anymore new units (which we should), can we name them after particles. That would be epic!

**Comment by Anuken** [comment]
No. Most well-known particles make for extremely generic names, and the more obscure ones don't sound very interesting.

**Comment by Humanoid-X** [comment]
@IVV-NCX I would be more excited to see one named wimp, lol

**Comment by MEEPofFaith** [comment]
> No. Most well-known particles make for extremely generic names, and the more obscure ones don't sound very interesting.

~~Say that to Advance Content~~
