### ISSUE TITLE
Sand not ore

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2415]
**Describe what you would like changed, and why.**
In logic ulocate, sand isn't detectable as an ore. Auto mining sand can't be done.

**Describe the changes you want to propose. Include possible alternatives.**
Make sand and dark sand detectable as ores.

**Comment by Newguy-ish** [comment]
Sand can't be mined by units.

**Comment by itcannotbe** [comment]
> Sand can't be mined by units.

A lie but not really.

**Comment by MrDuck557** [comment]
> Sand can't be mined by units.

Manual control, no
Logic control:
![image](https://user-images.githubusercontent.com/48808663/118010861-68497480-b31d-11eb-8836-2a782eea07ff.png)

**Comment by Slava0135** [comment]
> > Sand can't be mined by units.
> 
> Manual control, no
> Logic control:
> ![image](https://user-images.githubusercontent.com/48808663/118010861-68497480-b31d-11eb-8836-2a782eea07ff.png)

then it's abug

**Comment by MrDuck557** [comment]
![image](https://user-images.githubusercontent.com/48808663/118032951-35f84100-b336-11eb-8dca-978ea973d3f0.png)
Straight proof that only players can't mine sand ([link](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/Blocks.java))

**Comment by Newguy-ish** [comment]
Okay, counter suggestion to make all units unable to mine sand. /s

**Comment by RedstonerKBC** [comment]
The fact that units can mine hard mineral ores but they can't carry soft sand always blew my mind. Even kids can mine sand with their bare hands.

**Comment by Humanoid-X** [comment]
@RedstonerKBC true lol xD

**Comment by Bassem-Const** [comment]
You can mine sand with monos, but only if you know the pos of a tile of sand.

**Comment by SheepCommander** [comment]
I'm pretty sure this is a duplicate but that's not against the template anymore so still a good suggestion I think
