### ISSUE TITLE
Silicon as a weaker boost for projectors

### ISSUE THREAD

**Issue by DestroyerXL44** [Anuken/Mindustry-Suggestions#2416]
**Describe the content or mechanics you are proposing.**
Silicon should function as a weaker alternative to Phase Fabric for improving Mend Projectors and Overdrive Projectors (and possibly Force Projectors as well). It could simply be a weaker boost/range buff, or a weaker buff to only the range or effectiveness. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
There are a few reasons this would make sense based on other game elements:
-Right now, silicon is usable with Menders, which are essentially weaker Mend Projectors. So silicon would understandably be weaker than phase.
-The Overdrive Dome requires silicon as an input, but there's no use for silicon in the overdrive projector. It makes more sense to require silicon (for the sake of consistency) if its somehow involved with the smaller version. 
-Similarly, silicon is involved in Menders, but is absent entirely from Mend Projectors. 
As far as other things, this would serve as a useful alternative to phase fabric in earlier game situations, more so when playing the campaign without phase fabric unlocked yet.  

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 1ARC1** [comment]
not everything should be added to everything. it breaks balance

mender has silicon boost because its very earlygame and uses an early game resource to boost
mend projector has phase boost because its midgame and uses a lategame resource to boost

overdrive projector having a silicon boost would be a bit imbalanced.

**Comment by ThermoNuclearSquid** [comment]
To be honest, I think this could be a good idea if it was balanced correctly. Mabye the boost it gave could have a different effect to phaze so Its not just a lower ranking version, for example it could increase the health of the force projector sheild a fair bit, but reduce it's range and make it take longer to recharge
