### ISSUE TITLE
The edge of map

### ISSUE THREAD

**Issue by SAMBUYYA** [Anuken/Mindustry-Suggestions#2419]
**Describe the content or mechanics you are proposing.**

This is a limit for anything can't cross it ( building, player, unit, bullet gun and more). And have a line for knowing player know the edge of map and this line can have line opacity in settings. 

This edge can draw in map editor with name edge of map(maybe) and draw by block to block. If there make a new map the edge is default by the size of map and player can change the edge of map for small or bigger or same like their shape map because change from block to block. And maybe this will make fair for air, ground unit, water unit and also campaign too.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Maybe this is can make more fair for air, ground unit, water unit and also campaign too. And make player easy to know the edge of map and for map editor can make the more unique map with the new edge of map.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
Checkboxes: Not checked

You know the rules, and so do i...

Say goodbye!

![download (1).jpeg](https://user-images.githubusercontent.com/75618732/118127982-e6e10780-b42c-11eb-8c7d-e5244c01eff5.jpeg)

**Comment by Humanoid-X** [comment]
~~Please do not abandon a template. Every template should be treated with kindness and requires attention.~~

**Comment by OnyxFinger** [comment]
^^^ be aware of this next time ^_^
I also find a new way of making a map border interesting, as right now in many maps it is possible to cheese a bit on the sides, because if there is something around the borders that creates void space, then this area is cheesable with aircraft.
Here is what I mean
![Capture d’écran de 2021-05-13 19-41-26](https://user-images.githubusercontent.com/68511236/118164384-58b45380-b423-11eb-9a9f-b452eb2fe397.png)
Here someone can just stay with air units and camp right over here, because there is no way to make guns reach the area, so someone can perfectly go there and start being annoying while you can't really push him back.

**Comment by Humanoid-X** [comment]
Yeah I actually doesn't disagree this suggestion

**Comment by SAMBUYYA** [comment]
I just want make more fair for every map (pvp and campaign). Because if there have the mighty def, just ignore it and drive in the black spot. After this if on near core have more def. Lets suicide and win the game.

**Comment by SAMBUYYA** [comment]
> Checkboxes: Not checked
> 
> You know the rules, and so do i...
> 
> SAY GOODBYE
> 
> ![download (1).jpeg](https://user-images.githubusercontent.com/75618732/118127982-e6e10780-b42c-11eb-8c7d-e5244c01eff5.jpeg)

I see in trelo. Nothing update about the edge of map.

**Comment by itcannotbe** [comment]
> I just want make more fair for every map (pvp and campaign). Because if there have the mighty def, just ignore it and drive in the black spot. After this if on near core have more def. Lets suicide and win the game.

Ummmm. Because the edge of the map obviously has less defenses because you can't even put anything beyond it.

But your definition of edge of the map isn't even appropriate.

The edge of the map you're talking about is just merely solid wall where in you can't place anything on it, same applies with deep water.

**Comment by itcannotbe** [comment]
The best possible solution is probably an environmental tile that would be able to block all forms of attack/explosions/area effects and is impassable by all means.

Or the alternative which is just an impassable block also.

**Comment by itcannotbe** [comment]
If it's against naval units, probably a tile that would essentially "ground" naval units.

**Comment by SAMBUYYA** [comment]
> The best possible solution is probably an environmental tile that would be able to block all forms of attack/explosions/area effects and is impassable by all means.
> 
> Or the alternative which is just an impassable block also.

i say this "This is a limit for anything can't cross it ( building, player, unit, bullet gun and more). And have a line for knowing player know the edge of map and this line can have line opacity in settings."

THE LINE. This same like other game for make the limit of map. the map is bigger but player cant cross it.

**Comment by OnyxFinger** [comment]
Having to rely on a tile to do that is bad. Now you'll have a dumb tile in your world, or, in the case of a terrain wall, you can't put more terrain walls there.
>THE LINE. This same like other game for make the limit of map. The map is bigger but player cant cross it.

I think that an uncrossable line would fit, because the map limit currently pushes you stronger and stronger, same for enemy spawns, and having a totally uncrossable line looks unnatural.

**Comment by SAMBUYYA** [comment]
> Having to rely on a tile to do that is bad. Now you'll have a dumb tile in your world, or, in the case of a terrain wall, you can't put more terrain walls there.
> 
> > THE LINE. This same like other game for make the limit of map. The map is bigger but player cant cross it.
> 
> I think that an uncrossable line would fit, because the map limit currently pushes you stronger and stronger, same for enemy spawns, and having a totally uncrossable line looks unnatural.

Read my "Describe the content or mechanics you are proposing for the second paragraph". Unnatural? only the map editor determines that.

**Comment by OnyxFinger** [comment]
> > Having to rely on a tile to do that is bad. Now you'll have a dumb tile in your world, or, in the case of a terrain wall, you can't put more terrain walls there.
> > > THE LINE. This same like other game for make the limit of map. The map is bigger but player cant cross it.
> > 
> > 
> > I think that an uncrossable line would fit, because the map limit currently pushes you stronger and stronger, same for enemy spawns, and having a totally uncrossable line looks unnatural.
> 
> Read my "Describe the content or mechanics you are proposing for the second paragraph". Unnatural? only the map editor determines that.

I did read it and I even re-read it since you asked me too and I don't understand what you mean. I wasn't even replying to your original commit, but to the command suggesting an uncrossable line.
And I don't think the editor will decide wether or not it is unnatural. There is noreason that

**Comment by SheepCommander** [comment]
_now I'm confused_

**Comment by SAMBUYYA** [comment]
> > > Having to rely on a tile to do that is bad. Now you'll have a dumb tile in your world, or, in the case of a terrain wall, you can't put more terrain walls there.
> > > > THE LINE. This same like other game for make the limit of map. The map is bigger but player cant cross it.
> > > 
> > > 
> > > I think that an uncrossable line would fit, because the map limit currently pushes you stronger and stronger, same for enemy spawns, and having a totally uncrossable line looks unnatural.
> > 
> > 
> > Read my "Describe the content or mechanics you are proposing for the second paragraph". Unnatural? only the map editor determines that.
> 
> I did read it and I even re-read it since you asked me too and I don't understand what you mean. I wasn't even replying to your original commit, but to the command suggesting an uncrossable line.
> And I don't think the editor will decide wether or not it is unnatural. There is noreason that
> Wait sorry I did reply to you.

Yeah, you not understand that. Let i give an example.

The edge of map this is like a enemy spawn can draw in map editor for block to block. And if we play on the game. The edge showing like a line. If there new map, the edge default by map size. And player can change in map editor like enemy spawn delete and redraw again for his limit map. This good for telling the limit of map. So we can prepare for the annoying air unit.

**Comment by OnyxFinger** [comment]
ah so you're saying that there should be an "edge of the map" kind of indication ? IDK it can be useful on some maps I've never really needed it.

**Comment by SAMBUYYA** [comment]
> ah so you're saying that there should be an "edge of the map" kind of indication ? IDK it can be useful on some maps I've never really needed it.

You not needed it, but im need it and maybe other people same like me or some people same like you. This can help more when i make the def for stop rushing enemy like air unit.

**Comment by OnyxFinger** [comment]
I'm pretty sure it's easy enough to know where to put your defenses for aircraft.
