### ISSUE TITLE
Potential names for purple air units

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2420]
**Describe the content or mechanics you are proposing.**
If they ever get added.
Tier 1: Volta
Tier 2: Ampere
Tier 3: Watt
Tier 4: Lumen
Tier 5: Candela
Now, this will probably get rejected, but can be used for modded unit names :D

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
We already have basicly all things for namings covered, so why not power and light units?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Newguy-ish** [comment]
Let me just... _*bookmark succesfully created!*_ ...thank you very much.

**Comment by OnyxFinger** [comment]
Wouldn't that fit more with a blue route ?
I guess it also fits with purple since purple is the "special units" route.

**Comment by MrDuck557** [comment]
Anuke didn't ask yet, he also doesn't have plans for another air path

**Comment by BorisA11** [comment]
@MrDuck557 I didnt say _yet_, just whenever they are incorporated, if they are

**Comment by BorisA11** [comment]
@OnyxFinger It might fit more with green electric units, or a new, blue branch, though Anuken can use it for whatever he likes :D

**Comment by OnyxFinger** [comment]
^^^ both these top messages are right in my opinion.
It would allow anuke to ot have to think all day long about whatever name could be used.

**Comment by Ineedause** [comment]
I feel like these names suit the new support naval quite well, just my opinion

**Comment by IVV-NCX** [comment]
Quoting #2413:
> All the support navals were named even before I made the first tier. I am not in need of names.

[Link to comment by Anuken](https://github.com/Anuken/Mindustry-Suggestions/issues/2413#issuecomment-839810036)
