### ISSUE TITLE
Ability to spawn units in sandbox editor

### ISSUE THREAD

**Issue by ThermoNuclearSquid** [Anuken/Mindustry-Suggestions#2421]
**Describe the content or mechanics you are proposing.**
The ability to spawn in units from the sandbox editor

**EDIT** Apologies, I just noticed 24 mins after posting that the Trello page mentions the ability to set teams in sandbox. The spawning units still stands

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
If players could spawn in units in sandbox mode, it would allow them to test the unit's power without having to build factories and reconstructors for the units. This combined with the ability to set the team they are mimicing would allow them to simulate real PVP or PVE situations by spawning in enemy units to test their defences (or just have fun making the t5 units 1v1)

This would allow them to strategize and test their designs for defences, or test combinations of units in an army

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Nikolay-Sitnikov** [comment]
Spawning units is also already planned using the payload source.

https://discord.com/channels/391020510269669376/513178557653188609/838079411760398346

**Comment by SMOLKEYS** [comment]
> Spawning units is also already planned using the payload source.
> 
> https://discord.com/channels/391020510269669376/513178557653188609/838079411760398346

I think he mean't spawning units on a different *team*.

**Comment by SMOLKEYS** [comment]
Also, you could just use [Unit Factory](github.com/DeltaNedas/unit-factory) and [UI Lib](github.com/DeltaNedas/ui-lib)(required for mobile).

**Comment by Humanoid-X** [comment]
Yes, the mod Unit Factory works. Also, sk7725/Testers works too.

**Comment by BorisA11** [comment]
Now you can. Notice the unit spawners and deleters. You also can use mods

**Comment by Humanoid-X** [comment]
Now close.
