### ISSUE TITLE
Allow servers to run campaign

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#2422]
**Describe the content or mechanics you are proposing.**

Allows servers to run the campaign, with admins being able to change the sector.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would make multiplayer campaign far easier to do, and would allow a potential campaign speedrun gamemode.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> This would make multiplayer campaign far easier to do, and would allow a potential campaign speedrun gamemode.

Griefers: as if we'd allow that

**Comment by SheepCommander** [comment]
Would still be alright with servers being able to run the campaign, I just don't run a server and don't know for sure myself wether or not a server can already do that

**Comment by SAMBUYYA** [comment]
You mean you want to play campaign with some people?

That's it can with the third-party applications.

**Comment by thw0rted** [comment]
@SAMBUYYA I'm having trouble finding a way to play the campaign together on a server, it seems only possible peer-to-peer.  Do you have a name or link for the third-party application you're talking about?

**Comment by Phinner** [comment]
Mmmmmmh, multiplayer campaign is cool, imma look at that.
