### ISSUE TITLE
Stop the auto incineration of the base

### ISSUE THREAD

**Issue by lonyinlo** [Anuken/Mindustry-Suggestions#2423]
**Describe what you would like changed, and why.**

Stop the auto incineration of the base, it waste the resources, eg. The base is full of graphite and i want to take the excess coal the generate electricity.

**Describe the changes you want to propose. Include possible alternatives.**
I want to stop it, or let me choose which resources to incinerate

**Comment by Yell245** [comment]
It's not just a feature made for fun. It's used to calculate how much resources you'll gain when out of sector

**Comment by lonyinlo** [comment]
Ok understand. Is it a new feature? I remember i don't have it before.

**Comment by SMOLKEYS** [comment]
my guy, just use logic

**Comment by SheepCommander** [comment]
It's a v6 thing yep

**Comment by oinkymoo** [comment]
you can turn it off in custom maps, for all materials, but to do it in the campaign requires logic
