### ISSUE TITLE
Make crawler deals 2x damage to walls

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#2424]
Epic clash of clans wall breaker moment

**Comment by IIINSTINCT** [comment]
Great you removed the whole template

**Comment by SMOLKEYS** [comment]
Yeah... no.

Template or no template, Anuke isn't gonna add this in.

**Comment by itcannotbe** [comment]
Won't this make crawler a bigger pain to deal with, and it's not that op if you think about it.

**Comment by itcannotbe** [comment]
Also I REALLY WISH OP ACTUALLY FILLED IN THE TEMPLATE.

**Comment by SheepCommander** [comment]
w h y

**Comment by MauritanianMapping** [comment]
Safe to say a top-down third person tower defense strategy game is not the same as an online multiplayer commander-style strategy game. Damage multipliers specific to certain things do not exist unless you are the player mech or a modder.

**Comment by Humanoid-X** [comment]
W~H~Y~~~

**Comment by SheepCommander** [comment]
close 

please

**Comment by itcannotbe** [comment]
> Safe to say a top-down third person tower defense strategy game is not the same as an online multiplayer commander-style strategy game. Damage multipliers specific to certain things do not exist unless you are the player mech or a modder.

Foreshawdow Damage multiplier vs Blocks be like: Am I a joke to you?

**Comment by BiggerBrainYT** [comment]
I'm going to learn how to mod and mod this in just to prove that it is a bad idea.

**Comment by Kyllingene** [comment]
Good luck; you will have to do a heck of a lot of boilerplate to do that.
