### ISSUE TITLE
Logic core reference

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2425]
**Describe what you would like changed, and why.**

currently, each core tier has a different internal name ending (shard/foundation/nucleus), requiring you to edit all link-based references to the core. This is inconvenient

**Describe the changes you want to propose. Include possible alternatives.**
i came up with a few ideas
- change the internal names of all cores so that core is the final word and therefore processor links will always refer to them as core
- a hardcoded exception to the normal system so that cores use core instead of their tier name
- the ability to just use core when referencing the core in code instead of shard/foundation/nucleus
- a processor hardcoded variable called @core that references the nearest core (optionally requires said core to be in range of the processor)

**Comment by Humanoid-X** [comment]
Yes. just like processors, displays, reconstructors, etc.

**Comment by genNAowl** [comment]
You can use getLink plus a little bit of smart jumps?

**Comment by oinkymoo** [comment]
no clue what "smart" jumps are. but half a dozen lines or so seem really inconvenient if i'm going to run them every time through the script
