### ISSUE TITLE
place cores in sandbox

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2426]
**Describe the content or mechanics you are proposing.**

allow players in sandbox games to place new cores

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

many people, myself included, who use sandbox mode, do so in a specific world. however, I sometimes want to move my core. doing so, however, is currently impossible. sure, you can place extra cores in the editor, but It is inconvenient to do so, especially in the middle of a game

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
Well, mods can do this, but in vanilla?


I like this suggestion.

**Comment by SheepCommander** [comment]
I like this suggestion too

**Comment by Humanoid-X** [comment]
I like this suggestion too

**Comment by BorisA11** [comment]
Can't see why not. It's sandbox afterall.

**Comment by SheepCommander** [comment]
wah
