### ISSUE TITLE
Building schematics / cloning by the `f` key: please always construct processors as the last elements

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2427]
Hello
I am very sorry, I apparently reported this as an error, maybe it's worth it as a balancing/feedback issue:

**Describe what you would like changed, and why.**

1. If a schematic is cloned using the `f` key or constructed from the schematics list, then it happens that processors are constructed before other blocks.
2. Then it happens that the script starts before blocks exist, which are referenced in the script
3. Then, scripts can behave strange or even are blocked.

Because it is very tedious to handle this behavior in every script with a workaround:

**Describe the changes you want to propose. Include possible alternatives.**
Can you please construct processors always as the last elements if they are built from schematics?

Thanks a lot, kind regards,
Thomas

**Comment by Anuken** [comment]
[Other users have the opposite opinion.](https://github.com/Anuken/Mindustry/pull/4836)

**Comment by schittli** [comment]
Ou!, **thank you very much!, it's great, you have the overview** 😃 

A couple of ideas came to mind in my brainstorming. The problem would probably only be solved in general by a somewhat elaborate feature: if one could change the build order for schematics. Something like this:

**Build order** (The User can click the ▲ / ▼ arrows)
```
▲ ▼ conveyor1
▲ ▼ processor1
▲ ▼ router1
▲ ▼ container1
```

But that seems to me to be quite difficult to program.

Thanks a lot, kind regards,
Thomas

**Comment by oinkymoo** [comment]
if i may ask, under what circumstances would it be an issue for the processor to be placed first?

**Comment by Bottinator22** [comment]
Modular thorium reactor schematics with processors as failsafes, if the thorium reaches before the cryo does, or the cryo production is not complete yet, the processor will need to prevent the thorium reactor from exploding, but if the processor doesn't have priority, the reactor will explode, which obviously isn't a good thing

**Comment by Humanoid-X** [comment]
Rub your two brain cells and think about it

**Comment by Humanoid-X** [comment]
Processor last : thorium reaches reactor before processor gain conrrol, thus explode
Processor first : reactor get controlled immediately after it is built, thus stopping chernobyl
