### ISSUE TITLE
Better error messages for unit factories

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#2428]
**Describe what you would like changed, and why.**

- It should be immediately clear where / why the unit cap in factories comes from (yes there's the core database but its pretty obscure)
- Trying to build a >T1 unit you haven't researched yet doesn't give any kind of error

(suggesting because something along these lines gets asked in #help about once every week)

**Describe the changes you want to propose. Include possible alternatives.**

- Instead / in addition of the red triangle when the unit cap is reached, bring up a popup or tip to upgrade the core for a higher unit cap
- Add a visual indicator when trying to build a unit you haven't researched yet

**Comment by OnyxFinger** [comment]
Agreed. It would help beginners.
