### ISSUE TITLE
Frequency Sensors and Message updates (LOGIC)

### ISSUE THREAD

**Issue by WackyWakiX** [Anuken/Mindustry-Suggestions#2429]
**Describe the content or mechanics you are proposing.**
Frequency Sensors
  - when clicked, it has a customizable frequency
  - logic CAN execute a command to locate a frequency sensor with the same frequency. (It gives the frequency sensor a message)
  - logic can also read a frequency sensor for the latest message it received.
 Message updates
  - make it so that you can read them using logic

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This could increase creativity in logic, maybe in a sector in Campaign to create a "Base of Operations" so that you can activate factories and read the factories output without having to see the terrible designs! And if both are added, maybe a real internet discord.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
If we could read logic, there would be people who replace memory cells with messages

**Comment by itcannotbe** [comment]
> If we could read messages, there would be people who replace memory cells with messages

Exactly why this would be a bad idea in the first place.

**Comment by WackyWakiX** [comment]
how is that a bad idea? memory cells cannot store words anyway

**Comment by Kyllingene** [comment]
> If we could read messages, there would be people who replace memory cells with messages

One-value memory cells?

**Comment by WackyWakiX** [comment]
> > If we could read messages, there would be people who replace memory cells with messages
> 
> Exactly why this would be a bad idea in the first place.

messages only have one value to store and plus memory cells can't store texts

**Comment by itcannotbe** [comment]
> > > If we could read messages, there would be people who replace memory cells with messages
> > 
> > 
> > Exactly why this would be a bad idea in the first place.
> 
> messages only have one value to store and plus memory cells can't store texts, how is that a bad thing?

Um. You can store numbers in a message block and ..... You can just say store numbers on it in a way that would resemble how we store data in memory, like for example binary and a "cell" consists of 8 bits. Then to read the other parts just offset it but some bits to read it.

**Comment by WackyWakiX** [comment]
> > > > If we could read messages, there would be people who replace memory cells with messages
> > > 
> > > 
> > > Exactly why this would be a bad idea in the first place.
> > 
> > 
> > messages only have one value to store and plus memory cells can't store texts, how is that a bad thing?
> 
> Um. You can store numbers in a message block and ..... You can just say store numbers on it in a way that would resemble how we store data in memory, like for example binary and a "cell" consists of 8 bits. Then to read the other parts just offset it but some bits to read it.

I would never lose an opportunity to make code more compact; and you haven't even said anything that makes it a bad thing, other than memory cells being replaced.

**Comment by itcannotbe** [comment]
It does not even need to be bad directly, just adding a way to bypass a limitation using another mechanic is bad enough.

**Comment by WackyWakiX** [comment]
unless the limitation is intended, i dont see a problem

**Comment by MrDuck557** [comment]
use switches and edit mem cells
or use shootx, shooty and shooting on a bound arc
