### ISSUE TITLE
Add scripting to vanilla blocks

### ISSUE THREAD

**Issue by ThePythonGuy3** [Anuken/Mindustry-Suggestions#243]
**Describe the content or mechanics you are proposing.**

Right now it is impossible to add any scripts to vanilla blocks, which makes scripting more limited than it should. I think that if you can edit vanilla blocks via hjson/json, it shouldn't be too difficult to implement this.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This could improve a lot the mods and make them more interesting, by adding special mechanics to vanilla block without the need of source code modification.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
You can already change behavior of vanilla blocks. Reassign the entity constructor to one with a custom logic implementation.

For complete block rewrites, you should create a new block and make the old one `hidden`.

**Comment by DeltaNedas** [comment]
that will not affect saves though
