### ISSUE TITLE
Re-suggest Payload Bridge(tunnels for sprite) and Payload junction

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [Anuken/Mindustry-Suggestions#2430]
**Describe the content or mechanics you are proposing.**

Payload bridge(tunnels for sprite)
A 3x3 payload bridge that can transport units over building and terrains Cost: 30 Copper 20 graphite

Payload junction
A 3x3 payload junction that act as a bridge for two crossing payload units Cost:25 Copper 15 graphite

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Payload Bridge
This is useful when there's is a small obstruction like there is one conveyer or conduits blocking the way and useful when you ran out and/or there is no titanium nor thorium in the sector or can't drill titanium just yet. Unlike payload mass driver which is expensive and cost either titanium or thorium (like mass driver) also Quad/Oct can be useful but it's too long to make to crosspath and i'm very noob for logics for auto pickup crosspathing. And i'm not asking "Ungerground Map Layers" (Rule that you should NEVER suggest) also you said it worng (underground tunnels) because of the word "Tunnels" it is for sprite idea from mindustry classic for payload bridge

Payload junction
This can very useful for seperating units/blocks transferring from another sector or without crosspathing cloging using payload router and without using complicated logic also cheaper than payload mass driver

Even it is slow than walking on their own it can be useful when you need to crosspath without spending expensive resources to transfer to another sector or putting in the units/blocks launchpads

I'm sorry that i re-suggest this because i find some errors and dumb details when there is three problems i quickly loss some hope and give up

I can answer Any of the question that you want to ask for me

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Meanwhile in a distant land called "it is not yet finalized but it's going to be in v7"

A wild **payload driver** appears.

**Comment by itcannotbe** [comment]
Honestly speaking how will this be anymore useful than a payload driver?

**Comment by AdvintasAHAT86420** [comment]
Like I said it's cheaper than payload driver useful for crosspathing small
obstruction without spending some expensive material or when there is no
titanium nor thorium in the sector.

Like when you are in sector without titanium nor thorium and you want to
transfer units via payloads in another sector but there is an obstruction
of conveyer/conduits/terrains, this can be very useful when crosspathing or
seperate some units that you want to transfer to another sector when in
this situation like this.

**Comment by itcannotbe** [comment]
Why do you even need to cross path?

**Comment by AdvintasAHAT86420** [comment]
Because Obstruction is somewhat annoying like when you want it to deliver
units to it's destination is being blocked by some conveyer/conduits or
other that you don't want to deconstruct because it is inputted to
factories,core or your defenses

**Comment by itcannotbe** [comment]
You do know that using payload conveyors is a heck of a lot slower than making them actually walk right?

**Comment by AdvintasAHAT86420** [comment]
Then how can I transfer unit from another sector without using payload
conveyer and how can you input a unit from unit launchpad with only just
walking

Also i'm very noob for logics

**Comment by AdvintasAHAT86420** [comment]
Also even if it's slower it CAN transfer units/blocks to another sector

**Comment by AdvintasAHAT86420** [comment]
Another any question that this will become closed

**Comment by IIINSTINCT** [comment]
As far as I can remember anuke said that this wont happen in #development and you already suggested this before....

**Comment by AdvintasAHAT86420** [comment]
Maybe he will change his mind when he see this

And also suggestion is not #development

**Comment by OnyxFinger** [comment]
I don't think the junctions will be very useful, but the bridges might be.

**Comment by Humanoid-X** [comment]
ISN'T LOGIC SIMPLE ENOUGH?! EVEN THE OLD 8 YEARS OLD ME CAN UNDERSTAND JAVA

**Comment by oinkymoo** [comment]
wait, you can walk units into reconstructors?
