### ISSUE TITLE
I am a noob

### ISSUE THREAD

**Issue by idksomethingfuny** [Anuken/Mindustry-Suggestions#2431]
Maybe add like a pant tool to help me organize 

For example I am looking for a factory like a press I don't know what goes where I pant the place I want and boom I can easily find my stuff for my factory ps *I'm ma not a noob anymore but my friend is

**Comment by idksomethingfuny** [comment]
Same (I know I am the same person

**Comment by idksomethingfuny** [comment]
> Same (I know I am the same person

Epic

**Comment by Humanoid-X** [comment]
Umm whats pant tool

**Comment by Yell245** [comment]
The template died

**Comment by MrDuck557** [comment]
The current build menu is organized well enough, I don't have this problem

**Comment by SMOLKEYS** [comment]
> Maybe add like a pant tool to help me organize 
> 
> For example I am looking for a factory like a press I don't know what goes where I pant the place I want and boom I can easily find my stuff for my factory ps *I'm ma not a noob anymore but my friend is 
> 


***very, very visible confusion***

**Comment by MauritanianMapping** [comment]
Eat pant in Mindustry

In all seriousness how old are you?

**Comment by Humanoid-X** [comment]
This is probably what Anuke means by "spgashfetiti" and "extreme confusion".

**Comment by the-kido** [comment]
o k

**Comment by SheepCommander** [comment]
_what the hell_
