### ISSUE TITLE
[Modding] Some JSON things

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2432]
I honestly don't know where to request this so I will put it here.
I have asked the modders but they got no time and I don't know enough java to implement this myself.
Some shouldn't take too much time to make, though overall it may take a while so feel free to ignore this if you have no time.

**Describe the content or mechanics you are proposing.**
As the title says, just a few JSON things, some minor, some not so minor.
1. Draw layer field for bullets, allowing us to change which layer bullets are drawn at, for things like low flying bullets.
2. (not really important and maybe difficult) Boolean bloom field for making things out of the bloom layer actually bloom, or don't bloom while in the layer. See my Rainstorm turret for more details on *that*.
3. X offset, Y offset, spin (not the entire effect, just the particles in it, though making the entire effect spin for WaveEffects would also help), effect spawn delay, light generation, and drag fields for JSON effects, which would allow me to create much more versatile effects.
4. Ability to change the flame circle effect on GenericSmelters, or at least the size of the flame circles.
5. Make the trailEffect on bullets obey the rotation of the bullet, I absolutely *need* that for making more advanced trails.
6. (Optional) Ability to override sectors. I'd like to be able to put my mod's campaign *somewhere*, even if its not on it's own planet.
7. Capture/production research fix on modded content. As far as I know I cannot assign production research to any item/liquids.

I think that's my current list of things I'd like to be able to do that I currently can't. I hope to see at least a few of these things in 7.0.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
 JSON modders could polish a lot better, though I am currently the only one who polishes to such an extent that I need more things to polish. 
The visual effects and bullets are my main focus - visual effects are how I usually pull of my "json dark magic" and I want to make my bombers actually drop the bombs instead of yeet them into the air above the units. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have for once checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
4. - [X] I have made sure this has not been suggested before. ~~simply by being the only one masochistic enough to work with JSON this much.~~

**Comment by QmelZ** [comment]
~~i'll do the tradition~~

*mods.*

**Comment by MEEPofFaith** [comment]
The issue with the trail rotation thing is that  the `rotation` section is filled in with `trailParam`, since a lot of effects use rotation for size scaling.

**Comment by BlueWolf3682** [comment]
> ~i'll do the tradition~
> 
> _mods._

cool
now make one that adds these that works on ios
thanks have fun

**Comment by MEEPofFaith** [comment]
Bloom is set in `Renderer.java` on startup, so there is no way to make it commit boolean, however,  just lowering the bullet's layer by like 0.01 could make it not bloom.

**Comment by MEEPofFaith** [comment]
*slams table* time to do shit

**Comment by BlueWolf3682** [comment]
Yes, bullet draw layer is basically the priority there. Bloom is an *if* that can be addressed later.

**Comment by Anuken** [comment]
The units shown in `#dev-previews` already use custom layers & rotated trails, as can be seen in the mines and EMP projectile.

**Comment by MEEPofFaith** [comment]
ok, but what about the Smelter Flame thing

**Comment by BlueWolf3682** [comment]
Just how many of the things I'm asking will be implemented/are already imemented?

**Comment by MEEPofFaith** [comment]
### **_A l r e a d y   i n   7 . 0_**

**Comment by Anuken** [comment]
> Just how many of the things I'm asking will be implemented/are already implemented?

The JSON-related ones aren't implemented, because I don't use it myself. Sector objectives/presets in JSON were already half-done, so I'll probably do those, but effect modifiers that even *vanilla* particle effects don't have are unlikely to be added.

If you want particles to slow down as they move toward the end of their lifetime, that may already be supported by setting `interp` to `pow5Out` [(see the list of interpolations)](https://github.com/libgdx/libgdx/wiki/Interpolation). This is untested.

**Comment by BlueWolf3682** [comment]
Will try, though X and Y offset would be extremely useful because I can use that in tandem with effect-generating stuff (e.g. a StatusFieldAbility like wildfire's orb ability) to spawn effects anywhere and anywhen i wish.

**Comment by Anuken** [comment]
I'm not sure what you mean by X and Y offset. Is that in absolute terms? Relative to the rotation? For every particle?

**Comment by BlueWolf3682** [comment]
The X and Y would be fields based on the center of the unit or block, which would determine how offset the entire effect is from the center. This would not apply to individual particles, but to the entire ParticleEffect. Wave is kinda obvious from there.
