### ISSUE TITLE
Just a silly thing

### ISSUE THREAD

**Issue by Cloudrbx** [Anuken/Mindustry-Suggestions#2433]
I would like it if everytime you destroy a building you made you get half of the things you spent, and when you break a building you didn't build you get a quarter of the stuff

**Comment by Cloudrbx** [comment]
One quarter I mean.

**Comment by MrDuck557** [comment]
the first part is implemented, the second part is why

**Comment by Noob17** [comment]
wouldn't this practically enforce griefing?
