### ISSUE TITLE
Re-suggest that is worded better I hope-space stuff

### ISSUE THREAD

**Issue by Cmonster820** [Anuken/Mindustry-Suggestions#2434]
**Describe the content or mechanics you are proposing.**
a space unit constructor where the tetrative reconstructor would launch a specialized core into space that you could build from, any lower upgrade would be a unit(like a satellite) with semi-low power for space.
Space attacks- infiltrating a multi-sector crux cruiser, at least three sectors, at most five, you would start at the front area, move to the reactor, insert filler sectors there and here, then the bridge, like my "enemy ship" series of maps(which is not yet complete) after defeating 2-5 ships (depending on their size) sharded would be able to build their own (fairly weak) one (which could go through advanced reconstructors on the space core base to get stronger) and would be able to directly attack the crux cruisers
I imagine the cruisers looking like this (the fuse on the back is mirrored to the other three sides of the box it's on
![image](https://user-images.githubusercontent.com/72608260/118711423-9501fe00-b7ed-11eb-8e85-3a2b38b2f8af.jpeg)
![image](https://user-images.githubusercontent.com/72608260/118711469-a3501a00-b7ed-11eb-9e84-dbf6ba76c9a0.jpeg)
Two images because it took both sides of the paper
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
￼This would give a lot of new gameplay options as well as time for anuke to finish features without(hopefully) being yelled at for new features this would also provide more stuff for the community to attempt to add on to after they're done with playing the new content

Note:this would work with the satellites on the Trello list if they're still there, I checked but didn't see them but this could be because my eyes suck(kind of)
Note 2;the second part:sorry if this breaks the rules, I have not checked if they have changed since I was last here but I assume they haven't changed 
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> where the tetrative reconstructor would launch a specialized core into space that you could build fro

excuse me but how does a *reconstructor* launch anything into space

**Comment by Cmonster820** [comment]
> > where the tetrative reconstructor would launch a specialized core into space that you could build fro
> 
> excuse me but how does a *reconstructor* launch anything into space

I meant a specialized reconstructor that has a railgun tower attached

**Comment by Humanoid-X** [comment]
Totally confounded :p

**Comment by Cmonster820** [comment]
> Totally confounded :p

Where are you confounded?

**Comment by Cmonster820** [comment]
My "enemy ship" series is done now, I might make more, or have one where you blow up the engines

**Comment by Phinner** [comment]
How unfortunate...

**Comment by BiggerBrainYT** [comment]
So much effort in such a stupid idea... what a shame.
