### ISSUE TITLE
Core Placement Spots

### ISSUE THREAD

**Issue by BiggerBrainYT** [Anuken/Mindustry-Suggestions#2435]
This would be a floor/zone that could be placed in editor mode that could allow for the construction of a core on top of during gameplay. Probably not to be used in attack or campaign maps, would definatly give more reason to expand in PVP and allow recovery while being a completely optional part that map makers can use.

A large problem with larger PVP maps is the empty space (most of the time at least) for there is no reason to expand if all resources are localized. This would also give a fun aspect of holding key points on the map for more than just an offensive purpose. Overall, if someone ended up not liking this feature, it would be a completely optional feature of PVP maps and would definatly evolve the game for those who choose to use it.

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Another idea that could be used : When a core gets destroy, someone can place one of his own team there. (if the core is in the place where another core just died, then it's for sure accessible).
I think getting a new core is an addable mechanic and many would like it.
However the idea of a specific tile has an issue as always with these special tile ideas, you'll need to sprite them VERY well because else they wont fit with everything and it will be ouch to look at.

**Comment by Anuken** [comment]
There was a similar proposal that involved replacing cores with the opposing team's color when destroyed, essentially acting as capture points. This would be less "dynamic" in nature, but lead to a more straightforward implementation & intuitive mechanics. It would also solve the potential issue of cores being constructed instantly immediately after destruction.

Maps could start out with neutral cores scattered across the playing field.

**Comment by bvcbvc** [comment]
i like this idea

**Comment by itcannotbe** [comment]
> There was a similar proposal that involved replacing cores with the opposing team's color when destroyed, essentially acting as capture points. This would be less "dynamic" in nature, but lead to a more straightforward implementation & intuitive mechanics. It would also solve the potential issue of cores being constructed instantly immediately after destruction.
> 
> Maps could start out with neutral cores scattered across the playing field.

Though, what happens to materials that exceeds the storage limit if the core gets destroyed or if possible "captured"

**Comment by bvcbvc** [comment]
probably what happens now, where if the cap is overflowed, it will automatically lower to max cap after awhile

**Comment by BiggerBrainYT** [comment]
> Its a good idea but i worry about core nobuild radius since most pvp maps have them set really high to cross the neutral zone. also unit cap.

Unit caps increasing would only give more reason to take cores spots and destroy enemy core placements to lower their cap. If the cap overflowed, units from newest to oldest could start getting destroyed until there was no more overflow. Maps with core placement spots would defeat the purpose of having high no-build radius' for you could just create one with expanding. This feature wouldn't just be able to be slapped into maps with no thought, thought would have to go into building maps with these.

**Comment by BiggerBrainYT** [comment]
> > There was a similar proposal that involved replacing cores with the opposing team's color when destroyed, essentially acting as capture points. This would be less "dynamic" in nature, but lead to a more straightforward implementation & intuitive mechanics. It would also solve the potential issue of cores being constructed instantly immediately after destruction.
> > Maps could start out with neutral cores scattered across the playing field.
> 
> Though, what happens to materials that exceeds the storage limit if the core gets destroyed or if possible "captured"

All overflowed materials would be lost and maybe there could even be a set customizable multiplier in the settings to how much the player gets from the destroyed overflow if any.

**Comment by BiggerBrainYT** [comment]
> There was a similar proposal that involved replacing cores with the opposing team's color when destroyed, essentially acting as capture points. This would be less "dynamic" in nature, but lead to a more straightforward implementation & intuitive mechanics. It would also solve the potential issue of cores being constructed instantly immediately after destruction.
> 
> Maps could start out with neutral cores scattered across the playing field.

The problem with cores already being on the map is whoever claims them first will be the only ones who ever get to have those cores and gives an advantage to that player while giving less motivation to push from the other players. Although the high prices of cores may not be enough to stop the best players from just placing down a core, if these cores had a cool down on placements that would work.

Another good idea pigging off of what you said in your second paragraph is maybe you have to build to these neutral cores and power them/etc which would prevent people from just rushing all the cores. These cores could take a lot of power and if the demand is not met, they would be turned neutral again. To solve the issue of permenant destruction, there could be a customizable respawn timer for just these cores. A form of special neutral cores like these could even be incorporated into attack maps which could add for attack maps much greater in size where you try to take enemy cores out, wait for them to respawn, and then power them to claim them as your own.

**Comment by OnyxFinger** [comment]
> > There was a similar proposal that involved replacing cores with the opposing team's color when destroyed, essentially acting as capture points. This would be less "dynamic" in nature, but lead to a more straightforward implementation & intuitive mechanics. It would also solve the potential issue of cores being constructed instantly immediately after destruction.
> > Maps could start out with neutral cores scattered across the playing field.
> 
> The problem with cores already being on the map is whoever claims them first will be the only ones who ever get to have those cores and gives an advantage to that player while giving less motivation to push from the other players. Although the high prices of cores may not be enough to stop the best players from just placing down a core, if these cores had a cool down on placements that would work.

That's.. the point... PvP is mainly about your build order, which is kind of your pace + what you do with it.
So it's about reaching the max possible speed at doing something. Yes it is possible on mobile too. Being fast isn't very hard and so, players should quickly be able to go at the same pace, or about the same, after which wether or not you take another core is...
strategical. It is also many times possible to blame maps for not having enough cores (so getting more cores is much better than it should be in a balanced map), or to have not enough cores to start with, where then the same thing happens.
