### ISSUE TITLE
New logic

### ISSUE THREAD

**Issue by Buffoonogg** [Anuken/Mindustry-Suggestions#2436]
__Yeah this includes kinda lots of mechanics which could make the game more interesting and makes more content making possibilities.__
**-There** should be a block which works as a wall if activated or floor if deactivated.
**-And** the mechanic which allows to move a group of objects in 4 ways, of course the speed and the distance can be set.
**-There** should be mechanic that allows liquids to heighten or also lowen making the area 'dry'.
-Space holes are kinda illogical, they should be changed to gaps or atleast adding the feature.
**-Yes** there should be a particle system added for more details for the game.
**-Geysers**, blowing steam which could damage mostly ground units, for air units the damage is lower.
**-Thats** all the ideas i got for now
But i beleive i come back with bigger stuff

**Comment by BlueWolf3682** [comment]
1. doors
2. unit control
3. terrain editing isnt allowed in survival for many, many, many reasons
4. what are space holes
5. what is a particle system in this context
6. mods

**Comment by Ruichka** [comment]
1. rip template
2. thats called a door, you can build it from walls tab
3. do you realize how much work that will require, and what even that could be used for
4. this is called terraformation, and it was already suggested (see #285)
5. space holes are just space, and i don't know where have you seen them "illogical"
6. particle system already exists (or atleast existed), and it would be laggy to handle a huge amount of particles
7. ok

**Comment by QmelZ** [comment]
tbh mods, mods, mods, use the template, mods, mods and mods

**Comment by RedstonerKBC** [comment]
Ignore them^. They're just giving you :hankey: because you didn't follow the template. I don't even know why we have suggestions in the first place if people are going to reply to them all with "mods".

**Comment by oinkymoo** [comment]
how does this have anything to do with logic

**Comment by BlueWolf3682** [comment]
> tbh mods, mods, mods, use the template, mods, mods and mods

the first should be "doors", otherwise yes

**Comment by OnyxFinger** [comment]
Geysers...
idk maybe they would work.
For the rest I find it kinda stupid too

**Comment by Humanoid-X** [comment]
What has all these dumb things got to do with logic

**Comment by PickAPlayerNameFirst** [comment]
One thing's for sure these ppl didn't say, the mechanic to make the liquids won't leak was Armored Conduits. 
And all you've said was basically implemented in the game or the mods will do it for you.

**Comment by Kyllingene** [comment]
> Ignore them^. They're just giving you 💩 because you didn't follow the template.

If you don't follow the template, Anuke won't even *look* at the issue, especially with such a negative reaction as this. If you want any hope of getting this noticed and implemented, use the template below. (also the suggestions are either already a thing, would require huge amounts of work, don't fit with Mindustry, or some combination of them)

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by Random-internet-person** [comment]
> 4. what are space holes
>
I think he means space _floors_
