### ISSUE TITLE
prevention of circling around units

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2437]
**Describe the content or mechanics you are proposing.**
Simple suggestion, but prevent circling around slow units in general. To make this, make it so T4+ units won't target the player and T2 and below units. Something that could be made too is making it so an unit won't target another units at all if the target's speed is greater then the unit's angular speed, but the previous suggestion is probably a better way to do it and would already solve huge part of the problem.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Since you're meant to build actually good defense and not just circle units while having a crappy defense, this would solve huge part of it already, since T4+ are the ones who tend to be circled most of the times.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I totally agree. Right now you can circle around the enemy units in survival, as long as you have a wall / enough guns to take it out.

**Comment by oinkymoo** [comment]
units do pose a non-zero threat, why wouldn't they be targeted?

**Comment by Humanoid-X** [comment]
Because t4+ units rotate too slow. Blame their mass.

**Comment by MEEPofFaith** [comment]
~~So basically buff flare~~
