### ISSUE TITLE
Unit commanding 

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2438]
**Describe what you would like changed, and why.**
Unit commanding is arguably the most important thing in the game behind copper. It allows a human pilot to control something otherwise useless. How ever it has its flaws, the flaw it has is that it mixes units. I would like a way to filter this.
It is annoying when you want to bring only Toxopids and you bring a Vela with you. Or you want to control some Quads, but you end up bringing 5 Megas along as well. A filter like this would fix these inconveninces and make people more happy.  

**Describe the changes you want to propose. Include possible alternatives.**
The filter does not have to be complicated. Make it so that when you press G you only control units of your type, and when you press Ctrl + G it grabs all available units. Another possible alternative is make you be able to press H or something to control only your type on unit. Or the last alternative, just get rid of unit mixing all together.

**Comment by Facosa99** [comment]
Yeah, also sometimes i want the Support unites behind the attack ones for obvius reasons

**Comment by Humanoid-X** [comment]
i prefer the ability to select manually which unit to command

**Comment by OnyxFinger** [comment]
controlling polies and getting monos instead, or some other dumb stuff like having 4 quasars but there are pulsars in the way so you can't commant one of them without letting go of another one...

**Comment by oinkymoo** [comment]
i'm pretty sure G already prioritizes higher-tier units so if you're getting monos when you press G as a poly, you either don't have enough polys to form a full group or are too far from the other polys for them to join your group

**Comment by PickAPlayerNameFirst** [comment]
> i prefer the ability to select manually which unit to command

Good idea, like holding G while tapping the preferred unit so that unit will be included to your fleet.
