### ISSUE TITLE
Allow the player to respawn from the core with hotkey at anytime

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2439]
**Describe what you would like changed, and why.**
Currently, the player is only able to respawn at the core if they controlling a unit/block. This restriction is pointless, as the player can just pan over the nearest unit/block to take control of it, and then respawn at the core.

**Describe the changes you want to propose. Include possible alternatives.**
Allow the player to respawn at the core even if they are not controlling a unit or block.

**Comment by BlueWolf3682** [comment]
Why? You're already controlling a core unit.

**Comment by oinkymoo** [comment]
to warp to the core

**Comment by MrDuck557** [comment]
Pointless, ctrl click the core

**Comment by oinkymoo** [comment]
that requires you to pan all the way over first which is exactly what benman was complaining about

**Comment by RedstonerKBC** [comment]
What if everytime you press V (or whatever the key is) it respawns you at the core even if you're in a player unit? This has little effect on the game balance since the player units so jack diddly :hankey: damage anyways. It's won't make any difference to balancing. Players can grab a unit and press V to teleport to the core if they need to so might as well allow teleporting to the core at anytime.

**Comment by OnyxFinger** [comment]
just pan view and control core or place a router and control it to respawn in core :/

**Comment by Humanoid-X** [comment]
Is router really that expensive

**Comment by PickAPlayerNameFirst** [comment]
Close this issue as this feature is already been implemented in the game.

**Comment by BenMan95** [comment]
> just pan view and control core or place a router and control it to respawn in core :/

Thats the entire point. Preventing the player from respawning is completely pointless if something like this is possible. Removing this restriction would be a quality-of-life feature, like automatic junction/bridge placement.
