### ISSUE TITLE
SRV Record Support

### ISSUE THREAD

**Issue by devlaq** [Anuken/Mindustry-Suggestions#2441]
**Describe the content or mechanics you are proposing.**
Mindustry SRV Record Support

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
easy connect for non default port server

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
what

**Comment by Kyllingene** [comment]
[My stupid issue](https://github.com/Anuken/Mindustry-Suggestions/issues/1034)
