### ISSUE TITLE
Arachnid constructor

### ISSUE THREAD

**Issue by SimplyTav** [Anuken/Mindustry-Suggestions#2442]
**Describe the content or mechanics you are proposing.**
A forth, **purple** constructor
**Arachnid constructor**, a constructor for spiders ONLY
Possibly including
1. Normal spiders
2. Support spiders
3. Sapping spiders(current)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
spiders don't really fit with the other ground units, while they are unique and interesting more types of them would fill more roles and make gameplay more interesting

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> spiders don't really fit with the other ground units


...

**Comment by RedstonerKBC** [comment]
Here before anyone says "mods"

**Comment by itcannotbe** [comment]
> **Describe the content or mechanics you are proposing.**
> A forth, **purple** constructor
> **Arachnid constructor**, a constructor for spiders ONLY
> Possibly including
> 
>     1. Normal spiders
> 
>     2. Support spiders
> 
>     3. Sapping spiders(current)
> 
> 

Do you want flying spiders and swimming spiders with that? (This is sarcasm, this notice is added in added in just in case, some brain dead individual comes across this and mistakes this for an actual suggestion)

**Comment by OnyxFinger** [comment]
The problem is that spiders aren't a unit type but a unit type vraiant (e.g support route, spiders are in the "purple/sapping" route according to the trello)
Also adding route only reconstructors isn't a good idea in my opinion, adds way too many blocks, and would means more units here, except that wait you suggested none.

**Comment by konstantys** [comment]
> The problem is that spiders aren't a unit type but a unit type vraiant (e.g support route, spiders are in the "purple/sapping" route according to the trello)
> Also adding route only reconstructors isn't a good idea in my opinion, adds way too many blocks, and would means more units here, except that wait you suggested none.
> bruh how did this and #2439 get so many likes :/

I absolutely agree. Actually, i would be fine with non-linear unit progression; the problem is, if you make a reconstructor for spiders, then why not make reconstructors for boats etc. ? That would be a lot of units and work.

**Comment by MauritanianMapping** [comment]
What gonna happen with corvuses?

**Comment by SMOLKEYS** [comment]
Not only did this suggestion partially ruin my brain, it also made me realize there won't be any good suggestions later on.

**Comment by SMOLKEYS** [comment]
Close please.

**Comment by SheepCommander** [comment]
> Here before anyone says "mods"

_please stop_ and yes, seriously, mods. Spiders are ground units. Even if spiders "don't fit in with ground units" how do you propose going about this? Is anuke just going to rip the existing spiders out, put them in their own branch, and then create what 6 new units on the spot to fill in the gaps
