### ISSUE TITLE
Make Lancers have titanium on its building requiremtents

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2443]
**Describe what you would like changed, and why.**
For something that doesn't require Titanium (and Thorium) Lancers outclasses many other early-game turrets for its DPS and pierce, so for this reason I want Lancers to cost Titanium. Making this would make other (anti-ground) turrets have more use in sectors without Titanium, since you can basically use Lancers in every sector with sand and coal (which becomes super common after very early-game) to win at least in the part of ground units (since Lancers doesn't hit air).

**Describe the changes you want to propose. Include possible alternatives.**
As I said, to fix how out-classed Lancer is to something that doesn't require titanium, making it cost titanium would already solve that problem. The Lancer itself will still be the same as before, it will just be locked behind needing titanium for more use of other early-game turrets when there isn't titanium or thorium. I can't really think of any other possible alternatives for this, since Titanium and Thorium are the main progress-changing ores in the game because of how wide the array of things that can be done become by just having one of those two, so there shouldn't be many ways to make Lancer not out-class other early-game turrets other then making it also cost a not so early-game ore.

**Comment by D-player1** [comment]
Haha yes, let's make people in stained mountains suffer realllllly bad because they don't have a strong turret to beat scepter

**Comment by MrDuck557** [comment]
stained mountains has titanium

**Comment by SaltyBeggarBR** [comment]
> Haha yes, let's make people in stained mountains suffer realllllly bad because they don't have a strong turret to beat scepter

You don't need to end a sector to research stuff anymore, and launch pads have been reworked, plus Windswept Islands where Lancers are not needed and not practical to use and has titanium, so you could go there for researching Lancer instead in case you're having troubles with researching Lancer in Stained Mountains.
Also Lancers wouldn't need to cost like 1k titanium to be researched, it would only need to cost like 400 or 300 titanium to be researched so you'd still be able to do Stained Mountains with no problems I believe.
Unless I'm being dumb, the fact Stained Mountains is the first place many players will see titanium first shouldn't really be much of a problem.

**Comment by D-player1** [comment]
> stained mountains has titanium

Lancer unlock resaerch speedrun any% or I will get wrecked by scepter

**Comment by SaltyBeggarBR** [comment]
simply making stained mountains require the player unlocking Lancer before going there should solve that too

**Comment by MrDuck557** [comment]
> Lancer unlock research speedrun any% or I will get wrecked by scepter

you have 20 waves at least to gather enough titanium

**Comment by SheepCommander** [comment]
either way no

**Comment by MEEPofFaith** [comment]
> Haha yes, let's make people in stained mountains suffer realllllly bad because they don't have a strong turret to beat scepter

~~I killed the scepter with just hails~~

**Comment by Humanoid-X** [comment]
~i killed it with only hails, duos and scorches~

**Comment by numer99** [comment]
_Why?_
**NO**

**Comment by MEEPofFaith** [comment]
i mean, in terms of laser, we have arc which is just copper and lead, lancer adds silicon, and then we jump to fuse which adds graphite and thorium, skipping titanium entirely

**Comment by Random-internet-person** [comment]
3 WORDS: Biomass. Synthesis. Facility.

**Comment by MEEPofFaith** [comment]
I... I didn't use lancers on Biomass

**Comment by MEEPofFaith** [comment]
Just Hails, Scatters, and Waves

**Comment by MEEPofFaith** [comment]
> 3 WORDS: Biomass. Synthesis. Facility. It would be HELL if you couldn't use lancers there.

I... I didn't use any lancers and it wasn't hell.

![How bad are your defences?](https://media.discordapp.net/attachments/391020510269669378/845165985135722506/unknown.png)
