### ISSUE TITLE
Night mode/soft sound mode

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2444]
**Describe the content or mechanics you are proposing.**
Mindustry has very loud and sharp noises. Sometimes, these things can be suprising, and are not good for night-time playing. Now, there are headphones, and some external programs for that, but it would be neat.
This would dampen and soften:
Shots
Explosions
Burst beams
Certain parts of soundtracks (beats at the start of game9 can be heard from miles away, game 4 has very high pitched parts)
Phase weawers

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Useful when you want to be quiet, and why would you want to hear a million ripples ripplin'?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
simply turn down the sfx and/or music volume

**Comment by SMOLKEYS** [comment]
volume sliders in settings

close please

**Comment by SheepCommander** [comment]
^ yes there are volume sliders for sound effects and music volume in the sliders, please close your suggestion

**Comment by Humanoid-X** [comment]
volume sliders exist right?
~also, why do you play games at night~

**Comment by Humanoid-X** [comment]
~it is  baad for your eyes~ 

now  close

**Comment by MEEPofFaith** [comment]
~~You do realize that not only are there volume sliders in-game, but also your device itself has a volume adjuster~~

**Comment by SheepCommander** [comment]
~~y e p~~

**Comment by Humanoid-X** [comment]
^^^ so true
~how old are you~

**Comment by SMOLKEYS** [comment]
~~im just gonna make a mod that removes sounds entirely in mindustry~~

@BorisA11 @BorisA11 @BorisA11 close please

**Comment by Humanoid-X** [comment]
@BorisA11 @BorisA11 @BorisA11 @BorisA11 @BorisA11
@BorisA11 @BorisA11 @BorisA11 @BorisA11 @BorisA11
@BorisA11 @BorisA11 @BorisA11 @BorisA11 @BorisA11
CLOSE
