### ISSUE TITLE
Logic Priority

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2445]
**Describe what you would like changed, and why.**

A few days ago there was a post asking logic blocks to be built last from schematics in order to prevent buggy behavior. But as Anuke said" some other people have other opinions" and others want the logic to be build first. This argument can simply be fixed by adding a "switch" in the information section of a schematic that controls whether the logic gets built first or last. This will calm down both sides of the argument while allowing safe reactor schematics not to blow up, but also allowing for non buggy logic in rc schems.

**Describe the changes you want to propose. Include possible alternatives.**

Quite simple. In the information section of the schematic it shows total resources taken, power output, and input.Maybe under the resource and power counter there could be a switch saying that logic is prioritized or built last. For me personally, this is the best way to add something like this and there are little to no alternatives.

**Comment by Ineedause** [comment]
Didn't know weather to put this in balancing/feedback or feature request because it fits both.

**Comment by Humanoid-X** [comment]
I really dont understand why shouldd logic be built lase in reactor schematics :/

**Comment by Ineedause** [comment]
It should not, but it should be built last in rc schems, hence what I said.

**Comment by oinkymoo** [comment]
what is an "rc" schem and why does placing a processor early cause problems?

**Comment by Ineedause** [comment]
remote control, a schematic that uses units to deliver resources. Often seen in pvp. Placing the logic first causes issues because the logic MUST be bound before the processor is built. Other wise you have to delete the processors and replace them because the units don't follow the processor's instructions properly.

**Comment by Humanoid-X** [comment]
oh ok. understandable.

**Comment by SMOLKEYS** [comment]
> I really dont understand why shouldd logic be built lase in reactor schematics :/

So that the code in them doesn't mess up.


> this message has no association to the reply above

One thing: Try *building* the reactor schematic first before inputting the stuff needed for the reactors in the schematic.
