### ISSUE TITLE
Diode in its current format practically almost useless

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#2446]
**Describe what you would like changed, and why.**

It is not useless because the idea is bad, the idea is great but in practice it is almost useless because:

1-In single player: pro player will always make enough power, noobs will never use diode
2-In multiplayer: there is always some idiot who will connect power-producing network with the main network, and you will know that after power collapse takes place.
3-It could happen spontaneously when someone make a scheme close to power-producing network, then one of the scheme nodes will auto connect both networks.

**Describe the changes you want to propose. Include possible alternatives.**

1-Change the behavior of nodes so that when adding new node and when checking the surrounding buildings and nodes there will be 3 states instead of 2: 1-belonging to the same network(so it will not auto connect to it) 2-belonging to a different network(so it will auto connect to it) 3-belonging to a network connected to its network via diode, and here is the suggested change, the node **_will not_** auto connect to it.

2-Actually i want more strict and tough solution, but this could be a little bit hard to be implemented: the node not only will not auto-connect, but also even if the player tried to connect both networks connected already via diode manually, the connection will not be established, which means the player cant connect them, to do so he should to break the diode first(which is clear griefing if there is no real reason for that)

3-what will happen if the player added diode between two batteries already belong to the same network? the diode will not work, so i suggest 3 color to the diode(to the center sign): 1-yellow: it is not functional yet but there is no problem(it doesn't connect two different networks yet) 2-green: it works and functional(connects between two different networks) 3-red: not working and there is a problem(connects two batteries belong to the same network)

**Comment by oinkymoo** [comment]
i think 3 would work well with no autoconnect across dioded networks as well, though i don't support entirely blocking connection between halves of a dioded network

**Comment by Yell245** [comment]
"but there are stupid people!" - lol these stupid people also don't know how to generate energy properly and don't even know how to use crafters. Let's build energy generation and crafter schemes automatically because of that

**Comment by Sector171** [comment]
> though i don't support entirely blocking connection between halves of a dioded network

Ok, I don't see any point or need of having the ability to connect both network directly if they are already connected via diode.
However it is not totally "blocked" you can still do that (if there is a temporary need) simply by breaking the diode (it is cheap if you already made plastanium) or the simpler way by disconnecting the node which is connected to the battery, so easy.

**Comment by itcannotbe** [comment]
Let's break this down:

> 1-In single player: pro player will always make enough power, noobs will never use diode

Not the diode's problem, it's just that while doing balancing, the diode's use case was totally ignored.

> 2-In multiplayer: there is always some idiot who will connect power-producing network with the main network, and you will know that after power collapse takes place.

There are certain instances where the behavior is useful, but noobs still do it because they don't understand the how the diode works because the use case of the diode rarely occurs.

3-It could happen spontaneously when someone make a scheme close to power-producing network, then one of the scheme nodes will auto connect both networks.

Blame the schematic/schematic placement or probably the better reason is blame the power system mechanics.

**Comment by oinkymoo** [comment]
> blame the power system mechanics.

yes that is exactly what this suggestion is trying to fix
