### ISSUE TITLE
Add the ability to delay the connection for Servers

### ISSUE THREAD

**Issue by romanin-rf** [Anuken/Mindustry-Suggestions#2447]
Add the ability to delay the connection. That is, when users log on to the server, they are placed in a queue and each one logs on to the server with the delay specified in config. Well, this is not a mandatory function (you can not enable it, that is, it is disabled by default). 

More detailed:
This function is needed to ban bots, since bots enter the server in __large numbers and very quickly__ (you do not have time to ban, so a new one comes in immediately), and this function will allow you to ban bots one by one, and if the bots will fill the queue, then you need to add the command `view queue` and `delete from the queue`.

And yes, I know you will have to add it in the client, something like:
__Player__, goes to the server and he __appears a window__ where you write his `number in the queue` and `waiting time`, and the time will be calculated according to the principle: `number in the queue` * `waiting time specified in the config (in seconds)`

This will help to get rid of the fast connection of bots (Slows down the server)

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
but to put is simply. Why?

**Comment by romanin-rf** [comment]
We have a problem on the server with bots that come in very quickly and in large numbers, that the admins do not have time to ban them, and with the queue, the admins will be able to ban the bots one by one. And the one who runs these bots, just soon stop doing it, but if these bots decide to fill the queue, then you need to add a delete command from the queue.

**Comment by the-red-soul** [comment]
Surely you could just create a hub server or a queue server yourself? I know other servers have created them like Nydus with their puzzle.

**Comment by romanin-rf** [comment]
Well, yes, but just offered a good replacement. Since plugins are a crutch (I think so)

**Comment by BiggerBrainYT** [comment]
Ah yes, worsen the experience so bots would stop bothering.
