### ISSUE TITLE
Actually helpful icons for sectors

### ISSUE THREAD

**Issue by oneilmw** [Anuken/Mindustry-Suggestions#2448]
**Describe what you would like changed, and why.**
What purpose is there in making a sector's logo the GitHub logo or the Steam logo? hardly any.  If there is, then I haven't found it.
So, the current logo options aren't ideal.

**Describe the changes you want to propose. Include possible alternatives.**
To make this feature (picking an icon for a sector) flow more with other features already in the game, it could use a different set of images as choices instead:
The resource icons, and possibly the other terrain textures as well.
That way, I can mark sectors as having an abundance of a resource, instead of relying on the planet hud which displays all resources in the selected sector, but not their relative quantities.
Furthermore, when the player gets launchpads, these icons get the natural feature of being able to show what a sector is exporting.  The player would be able to pick an icon which matches the sector's export.

**Comment by Humanoid-X** [comment]
plzzz anuke

**Comment by itcannotbe** [comment]
Reason being, those are the icons the game already uses. So it makes sense that they're in the choices.

Anuke didn't made icons specifically for this purpose. And why would he? Maybe the compromise is maybe make a way for you to easily add in more icons via import or maybe a simple drop in image files into a specific folder.

Cause honestly, making the dev add more icons for this purpose is a waste of time.

**Comment by oneilmw** [comment]
> 
> 
> Reason being, those are the icons the game already uses. So it makes sense that they're in the choices.
> 
> Anuke didn't made icons specifically for this purpose. And why would he? Maybe the compromise is maybe make a way for you to easily add in more icons via import or maybe a simple drop in image files into a specific folder.
> 
> Cause honestly, making the dev add more icons for this purpose is a waste of time.

Just to clarify, I'm not asking for _new_ icons to be made; I'm just asking for the already existing resource textures to be in the list.
