### ISSUE TITLE
Make turrets prioritize buildings from different teams equally

### ISSUE THREAD

**Issue by notrealn** [Anuken/Mindustry-Suggestions#2449]
**Describe what you would like changed, and why.**
Currently, turrets have a weird priority system for teams. Here, my lancer will always prioritize the purple wall over the red salvo. It will always target any purple building over any red building.

![image](https://user-images.githubusercontent.com/56411504/119243685-1b447a00-bb37-11eb-851d-5ab47dc071a9.png)

**Describe the changes you want to propose. Include possible alternatives.**
I think turrets shouldn't target walls over turrets because that makes no sense. They are supposed to shoot at turrets first, then walls.

I can open a PR for this if people are interested.

**Comment by MrDuck557** [comment]
Good

**Comment by Humanoid-X** [comment]
Good

**Comment by itcannotbe** [comment]
Define equally from a programming perspective.

**Comment by notrealn** [comment]
> Define equally from a programming perspective.

Turrets will still prioritize buildings by their teams (like purple walls over red walls), but will try following their priority list first (so shooting red salvo over purple wall).

**Comment by SheepCommander** [comment]
_Good_

**Comment by notrealn** [comment]
im "working on it"

**Comment by notrealn** [comment]
making pr
