### ISSUE TITLE
Liquid unloaders

### ISSUE THREAD

**Issue by simulation3** [Anuken/Mindustry-Suggestions#245]
Ok so for drone factories like the revenant ones unloaders can take silicon and titanium from one of them and pass it on to conveyors and lead them to other revenant factories for easy compact lines for multiple ones. In 6.0 higher-end hop up factories are gonna need coolant to produce higher-end units.

If the liquid unloader is made we could make reaper hop up factories nice and symmetrical and in higher numbers too. Plus if we could make the liquid unloaders take coolant from one turret to another that might make it so specters could be made en mass in smaller spaces without having to snake in a bunch of pipes and liquid routers everywhere.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
The high amount of liquid required for your use case. Would necessitate high amount of fluids being produced. This would make liquid unloaders be worthless in that regard.

**Comment by Anuken** [comment]
This would either make liquid transport too easy or wouldn't work very well.
