### ISSUE TITLE
Ability to hold leftclick to build schematics faster like you can do with walls, guns etc.

### ISSUE THREAD

**Issue by ErikoX** [Anuken/Mindustry-Suggestions#2451]
Describe the content or mechanics you are proposing.

I downloaded new schematics today that are stackable, (see image) and I noticed that I need to build all the segments manually.
My suggestion is to be able to build schematics in a huge line by holding leftclick (like you can do with conveyors in the example)

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This could make building huge farms way faster.

Example:
![example](https://user-images.githubusercontent.com/54033728/119249372-4ad79e80-bb98-11eb-9587-cd67d7b669b1.png)

Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

        [X] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
        [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
        [X] I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
I can't believe no one has suggested this yet

**Comment by Humanoid-X** [comment]
@RedstonerKBC I think I saw one about this before

**Comment by ErikoX** [comment]
how do I add a label to this

**Comment by oinkymoo** [comment]
> how do I add a label to this

you use the template :)

**Comment by the-red-soul** [comment]
or you could just resave the schematic as a larger segment........

and then place a ton of the larger segments and then lag your game to shit

**Comment by itcannotbe** [comment]
> or you could just resave the schematic as a larger segment........
> 
> and then place a ton of the larger segments and then lag your game to shit

This is exactly what I do of I want to tile something. Except the saving part.
