### ISSUE TITLE
Player respawns in android

### ISSUE THREAD

**Issue by lavnishhh** [Anuken/Mindustry-Suggestions#2452]
Ok

**Comment by Yell245** [comment]
You can click on a unit icon and respawn from Core

**Comment by oinkymoo** [comment]
R.I.P. Template

**Comment by IIINSTINCT** [comment]
RiP template anyways close this issue

**Comment by SheepCommander** [comment]
close

**Comment by BorisA11** [comment]
Just tap the HP bar, where your unit name is displayed. I think this should be closed.
