### ISSUE TITLE
Wind power generation 

### ISSUE THREAD

**Issue by Dustbin-mindustry** [Anuken/Mindustry-Suggestions#2453]
**Describe the content or mechanics you are proposing.**
i want to use wind to generate electricity 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it can let us make the power easily

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
So basically solar panel 2.0

**Comment by Dustbin-mindustry** [comment]
yes

**Comment by abdallah362** [comment]
it will be stronger in some sector and weaker in some Right??

**Comment by Dustbin-mindustry** [comment]
maybe

**Comment by Dustbin-mindustry** [comment]
for Example when the wind is strong,power will be strong too

> 在某些领域会更强，在某些领域会更弱，对吗？

**Comment by Slava0135** [comment]
> So basically solar panel 2.0

~~check out reVision wind turbine~~

**Comment by Dustbin-mindustry** [comment]
how can make anuken see this

**Comment by Humanoid-X** [comment]
he can already see this, just not responding to

maybe, like, generate more power during sporestorm & sandstorms?

**Comment by itcannotbe** [comment]
Ah yes, why did anuke actually allowed duplicates again?

At least the earlier suggestion actually took time to actually fill in the template properly.

Specifically this part.
> If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**Comment by SMOLKEYS** [comment]
~~h, this suggestion is too underspecific~~

**Comment by oinkymoo** [comment]
this doesn't add anything new. you're asking for power sources that generate power with no input, which already exist in the form of solar panels. close this

**Comment by Ineedause** [comment]
It is a good idea
A power source that is more powerful in storms. It picks up the lack of power from solar panels. I enjoy this type of power generation.

**Comment by genNAowl** [comment]
I remember I made a suggestion of this sort quite a while ago. 

If you are interested to see the discussion there, https://github.com/Anuken/Mindustry-Suggestions/issues/472

**Comment by BiggerBrainYT** [comment]
This is not a good idea, winds already boost cultivators which can be used for power and if they were big, they would be worse than solar panels, and if they were the same size they would be pointless.

This idea would also prevent new players from looking into actual good sources of power like RTG, Thorium, Differiental, and Impact as the game design would be putting them staring into weaker sources of power like solar panels and wind turbines.

**Comment by Random-internet-person** [comment]
s  o  l  a  r    p  a  n  e  l  s
