### ISSUE TITLE
[QoL] Mod Browser language support"

### ISSUE THREAD

**Issue by Prosta4okua** [Anuken/Mindustry-Suggestions#2454]
**Describe the content or mechanics you are proposing.**
Add inscription in mod blocks
![unknown (1)](https://user-images.githubusercontent.com/31485341/119252428-db23dc80-bbb4-11eb-94db-104af640d09a.png)
![unknown (2)](https://user-images.githubusercontent.com/31485341/119252472-22aa6880-bbb5-11eb-8d6a-fe0a4f912598.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It may not be very useful for players playing the English version, but it is useful for others. I think mindustry should check bundle_code.properties

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dustbin-mindustry** [comment]
good

**Comment by Humanoid-X** [comment]
good

**Comment by itcannotbe** [comment]
Can you change the title to:

"Mod Browser language support"

I almost commented that mods already support language bundles lol.
