### ISSUE TITLE
Feedback: Please allow to show `F1` / Block Info for the Item under the Cursor on the Map

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2455]
**Describe what you would like changed, and why.**

Not only beginners regularly have questions about blocks on the map: What is it for? Which resources can it use? etc. 

Unfortunately, in Mindustry, the way to the help / Block Info is then very cumbersome:
1. Read the Block-Name from the Menu block
2. Search the block in the Building-Menu & Categories by moving over the Icons and search for the right Name
3. Select the Block
4. Select / press F1

**Describe the changes you want to propose. Include possible alternatives.**

Please allow us to open the Block Info by pressing `F1` while the Cursor is above a Block **on the Map**.
This would be very useful.

**Comment by OnyxFinger** [comment]
it's not a big problem. Blocks are all classified in a specific layout so it's easy to know where will be what, you then after it's easy to find them.
There is also a control to select the block your mouse hovers on PC.

**Comment by SheepCommander** [comment]
^ middle mouse button/the scroll wheel/mouse3, as well as 1-9 followed by another 1-9 to select blocks
