### ISSUE TITLE
A NG+ cycle to Mindustry

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2456]
**Describe the content or mechanics you are proposing.**

Everytime you end the game (as for right now, build and fill the inputs of the Interplanetary Accellerator), you'll be able to restart campaign while still still keeping all the previously unlocked stuff and the progress of stuff that wasn't unlocked yet, but the campaign would be harder then before by making enemies become stronger in health, damage, and in their special abilities (better life-steal (Spirocts and beyond), projected shields with more health (Quasars and Octs), more effective healing (As for most support units, both in building heal and in unit heal) and etc) and have more shields, have more enemies and harder enemies (By that I mean higher tier enemies then usual. That doesn't mean everytime you start another NG+ all enemies will have one more tier then they'd naturally have, only some enemies with the frequency of enemies having higher tiers increasing each NG+ tier for making it have a smooth difficulty curve) per wave, there be more base sectors, vulnerable sectors get invaded more often and with harder waves and etc, similar to the NG+ cycle of games like Dead Cells, Dark Souls and others.
Once restarting the game, you'd be able to choose a load-out for launching in Ground Zero to be able to get titanium and other stuff earlier.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The campaign starts getting boring to replay at some point without modding it since it will always be the same difficulty which means that if you ended the campaign once you can end it as many times as you want. This would add a lot more replayability and fun to the campaign and would also encourage the use launching at some point since the game would get more and more harder with this system (which is already possible, but since the game was not designed around capturing sectors with launching, the campaign gets way too easy with it). 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
unfortunately this won't work so well in v7 due to the fact that the interplanetary accelerator will actually be given a use in reaching new planets. maybe interstellar accelerator could do this?

**Comment by itcannotbe** [comment]
Ah yes, prestige mechanic, nothing else but a cheap mechanic to force replayability. That's a **no** for me.

**Comment by SheepCommander** [comment]
I mean tbf prestige _does_ work to an extent, but at the same times meh

**Comment by Humanoid-X** [comment]
no.
