### ISSUE TITLE
v7 campaign ender

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2457]
**Describe the content or mechanics you are proposing.**

a new block to take over interplanetary accelerator's current role once v7 happens

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The interplanetary accelerator will presumably, in v7, have an actual function, beyond bringing the game to an end. however, that opens up the slot to be filled by a new item. it could an interstellar accelerator, literally just a higher-tier interplanetary. alternatively, if the game will only ever be contained to within a single star system, it could perhaps be a planetary-scale force projector, to permanently defend the system from enemy invasion

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
The point of the interplanetary accelerator was never to bring the campaign to an end; why do you think the campaign needs one?

**Comment by SheepCommander** [comment]
I died a little when I read this

**Comment by oinkymoo** [comment]
currently, that is all it does though
