### ISSUE TITLE
New Unit class

### ISSUE THREAD

**Issue by Random-internet-person** [Anuken/Mindustry-Suggestions#2458]
**Describe the content or mechanics you are proposing.**

A new type of unit. Not a tree, a class, like support or assault. The new class I'm proposing would be the Heavy class. They have high health and firepower but are slow and expensive to produce. I'll add the ground Heavy tree here, and more when I think of them.

T1: Barrier. It has one machine gun, faster firing, and with slightly higher damage than the Dagger's. It is the slowest T1 in the game and has higher health than a Crawler. Production cost is 30 silicon, 20 lead, and 25 graphite.

T2: Bulwark. It has two quick-firing, relatively weak shotguns(NOT fuses), and a force projector that is smaller and weaker than the Quasar's. It is still slower than any other T2, and production cost is same as usual.

T3: Rampart. It has 4 laser-bullet cannons that are like the mega's, but are more powerful and don't heal structures. It also has a very strong shield, and a shield pulse ability like the Bryde's. Same theme of slow but high health. Production cost is the same as usual.

T4: Bulkhead. It has two blast ripple cannons, and two segment turrets similar to those on the support navals. Same theme as normal, same production cost.

T5: Stormshield. It has a VERY strong force projector, stronger even than the Oct's, and 2 Vela turrets as well. It also has a healing pulse ability and 4 segment turrets. Same theme as normal, same production cost.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I just think it would be cool to have a new unit class, and adding a heavy unit class would fill that "tank" role that is currently empty.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. sorry trello is blocked on my school computer :(((((
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
Currently, attack ground fills the tank role. Also this feels like extra bloat

**Comment by BiggerBrainYT** [comment]
This feels like a mess of all the different already existing ground units poorly mixed with the intention of which is already forfilled by the basic ground units.

**Comment by DarkBrick** [comment]
1. Mods 2. Feels unneccesary

**Comment by OnyxFinger** [comment]
>     1. Mods 2. Feels unneccesary

1. That's not an awnser. 2. Agreed

This class could be interesting because it would actually be tanky and so may be useful for PvP (where as many other classes suck except for support and attack air currently, cuz it's too hard to kill, and maybe support ground if you don't really have good defense logic / your enemy doesn't). However I feel like in order to fix this issue, other units should get balanced first.

**Comment by itcannotbe** [comment]
> but are slow and expensive to produce

You do know how reconstructors work right?

**Comment by Random-internet-person** [comment]
> You do know how reconstructors work right?
Unit production speeds can be varied, and I meant that the initial 1st tier unit is expensive.

**Comment by DarkBrick** [comment]
> > You do know how reconstructors work right?
> 
> Unit production speeds can be varied, and I meant that the initial 1st tier unit is expensive.

That wouldn't work well, as a small change wouldn't impact much and a big change (like adding plastanium or any higher tier resource) would ruin the difference between the first couple tiers of units. 
Also, unit production speed doesn't affect pretty much anything (other then maybe early game pvp or whatever)

**Comment by RedstonerKBC** [comment]
Octs are already OP and you want to add another T5 that has a stronger shield? To be fair I guess it's not that OP since it's slower and and can only walk on land, but the fact that it has freaking segments is what makes this things unkillable.

**Comment by Humanoid-X** [comment]
No unless #2019 and #2021 get implemented

**Comment by itcannotbe** [comment]
> No unless #2019 and #2021 get implemented

~~You forgot #2020~~

**Comment by oinkymoo** [comment]
> a class, like support or assault

support units exist, but the red unit trees are general and tend to already be quite heavy, and most certainly not "assault"

**Comment by oinkymoo** [comment]
the dagger tree is already plenty tanky. this niche is already filled
