### ISSUE TITLE
Setting to Remove the Camera RubberBanding Effect

### ISSUE THREAD

**Issue by hansonry** [Anuken/Mindustry-Suggestions#246]
**Describe the content or mechanics you are proposing.**
Have an option in the settings menu to add the ship camera rubber banding effect. Have it enabled by default. When on, the camera will track the player ship like it currently does. When off, the camera will directly track the ship without any effects. I would like this for at least Windows and Linux.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will help players who get motion sick easily. Specifically my wife. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. 
    * You have a card here indicating you have implemented a similar feature for mobile: https://trello.com/c/c0aHwPT7. This would be an option for PC
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Implemented in latest commit.
