### ISSUE TITLE
Way to encourage Crucible on heat tile use

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#2460]
**Describe the content or mechanics you are proposing.**
When pyratite is put into a Silicon Crucible, it fills a fuel bar (similarly to ammo on turrets). Maybe one pyratite adds 5 fuel and then it takes 5 fuel to craft silicon. (Hypothetical values) Placing on heat tiles reduces fuel usage, maybe enough heat affinity could completely remove fuel usage and make it not need pyratite.
(Should it still make it run faster, or only have this reduced fuel usage bonus?)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, there's basically no reason to place it on heat tiles. Sure, it increases speed but that just makes feeding in resources more difficult, and getting free power out of thermals is always better.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may cause Anuke to reap your soul and kill you to death.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

(Yes I did edit the notice above.)

**Comment by SMOLKEYS** [comment]
> *kill you to death.*

these 4 words are recipe for confusion lmao

**Comment by MEEPofFaith** [comment]
> > _kill you to death._
> 
> these 4 words are recipe for confusion lmao

~~How else do I convey(er) imminent death~~

**Comment by itcannotbe** [comment]
There is an alternate, rescale power consumption across the board. It solves the use case for using hot tiles with crucibles and an increase difficulty im progressing to end game by means of higher power consumption in line with progression.

**Comment by MrDuck557** [comment]
Actually good way to encourage cruci

**Comment by MEEPofFaith** [comment]
~~I'm fully capable of making a pr for this, but I want to hear some opinions first.~~

**Comment by MEEPofFaith** [comment]
_I'm gonna do what's called a pro gamer move. **Implements this suggestion myself.**_
