### ISSUE TITLE
Units named after Moons

### ISSUE THREAD

**Issue by Hyrotrioskjan** [Anuken/Mindustry-Suggestions#2462]
**Describe the content or mechanics you are proposing.**
Units named after famous planetary moons, such as **Deimos, Phobos, Enceladus, Ganymede, and Europa.**
For example, lets say the new support navals are going to have these names.

T1 - Deimos
T2 - Enceladus
T3 - Europa
T4 - Ganymede
T5 - Phobos

In my opinion this is just a suggestion that would most likely not get added, but it would be cool to see it actually being added. Since the Nova tree is named after stars and constellations, maybe the support navals are going to have names from moons too, It just makes a little bit of sense in my opinion.

Names ranked/tiered from the moon's diameters, for example the smallest moon (Deimos) being tier 1 and the largest moon (Phobos) being tier 5.

I know some people are probably gonna dislike this suggestion, but it would still be cool to see them being added, either via new units or the current support navals (if Anuke hasn't already decided on the navals names)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
Nice names but too bad anuke already planned names for naval support even before he showed the units it to us

**Comment by OnyxFinger** [comment]
> Nice names but too bad anuke already planned names for naval support even before he showed the units it to us

actually there could be a special/purple route for air and naval later, but I don't see this done any soon.

**Comment by oinkymoo** [comment]
stop making f*cking name suggestions

**Comment by BorisA11** [comment]
Mindustry seemingly has no connections to Solar system, none of the planets exist in game. So how can they name units after moons they dont even know exist?

**Comment by DarkBrick** [comment]
> stop making f*cking name suggestions

Yes, there's too many of these and they serve no purpose other then clog up the suggestions chat and waste everyone's time. Names are the easiest thing to come up with when adding units.

**Comment by MrDuck557** [comment]
Anuke is going to stuff this in a box for later, if he doesn't ignore it

**Comment by RedstonerKBC** [comment]
> stop making f*cking name suggestions

Tell Anuke to put it in the README.md list of things not to suggest. It's what it's there for.

**Comment by Hyrotrioskjan** [comment]
> Mindustry seemingly has no connections to Solar system, none of the planets exist in game. So how can they name units after moons they dont even know exist?

the Nova tree is named after famous constellations. Vela and Corvus. These aren't found in the game either, so it would **kind **of** make sense to me for units to have names from moons too, but it is a very unlikely possibility.

**Comment by Humanoid-X** [comment]
Wow if i have a computer with me right now i will definitely pr update readme.md to stop suggesting names

**Comment by itcannotbe** [comment]
> Wow if i have a computer with me right now i will definitely pr update readme.md to stop suggesting names

Aren't you half a day late for that?

**Comment by SMOLKEYS** [comment]
> Mindustry seemingly has no connections to Solar system

Campaign: ***is solar system based***

**Comment by OnyxFinger** [comment]
> Mindustry seemingly has no connections to Solar system, none of the planets exist in game. So how can they name units after moons they dont even know exist?

It does since there are planets.

>stop making f*cking name suggestions

f*cking yes

**Comment by BiggerBrainYT** [comment]
Please stop being part of the problem, Anuke does not need more names, stop spamming suggestions with these stupid posts!

**Comment by BiggerBrainYT** [comment]
Please stop being part of the problem, Anuke does not need more names, stop spamming suggestions with these stupid posts!

**Comment by RedstonerKBC** [comment]
README.md <- Tell Anuke to add it to the list of things not to suggest

**Comment by SheepCommander** [comment]
Shut up mate we already know Anuke doesn't want to moderate this pit for the most part

**Comment by SMOLKEYS** [comment]
> Mindustry seemingly has no connections to Solar system, none of the planets exist in game. So how can they name units after moons they dont even know exist?

...do you not know you can name something anything you want?
