### ISSUE TITLE
Tier 2, 3 and 4 Parts

### ISSUE THREAD

**Issue by Cbao04** [Anuken/Mindustry-Suggestions#2463]
Adding T2, T3 and T4 factories, turret, defence 
and drills.

**Comment by Yell245** [comment]
what
Please, follow the template. Also, there are already some t2 crafters and adding more tiers for all crafters isn't really necessary: how much do you use metaglass, for example? But people have a deficit of graphite and silicon, that's why t2 crafters were added for them. I also want t2 cryo crafter to be added tbh, it'd be nice because t4 and 5 reconstructors need to have a load of cryomixers, which isn't space-efficient

**Comment by IIINSTINCT** [comment]
What kind of sorcery is this? Most of this things you mentioned already exist and the current ones already good.... why you need more? Besides you yeeted the whole template please dont remove it 
And CLOSE THIS ISSUE

**Comment by itcannotbe** [comment]
### I got this.

Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More T2, T3 and T4 factories, turret, defence
and drills before. This is a revelation. I would never have thought of adding More T2, T3 and T4 factories, turret, defence
and drills myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More T2, T3 and T4 factories, turret, defence
and drills immediately."

**Comment by DarkBrick** [comment]
Taking everything into consideraton
1 Close this issue
2 Mods

**Comment by MEEPofFaith** [comment]
Welp I guess Anuke will reap your soul now.

**Comment by Humanoid-X** [comment]
Go reap, I support.

**Comment by MEEPofFaith** [comment]
![Your soul Hand it over ](https://user-images.githubusercontent.com/54301439/119603445-0f102500-bda2-11eb-9e42-28a75edf56c6.png)

**Comment by SMOLKEYS** [comment]
> ![Your soul Hand it over ](https://user-images.githubusercontent.com/54301439/119603445-0f102500-bda2-11eb-9e42-28a75edf56c6.png)

~~give me the pr/issue containing this message~~

**Comment by itcannotbe** [comment]
> > ![Your soul Hand it over ](https://user-images.githubusercontent.com/54301439/119603445-0f102500-bda2-11eb-9e42-28a75edf56c6.png)
> 
> ~give me the pr/issue containing this message~

~Original~
~https://github.com/Anuken/Mindustry/issues/3684#issuecomment-736539263~

**Comment by Random-internet-person** [comment]
rip template 
also @DarkBrick "Mods" isn't an answer. We're talking about **_vanilla content._**

**Comment by MEEPofFaith** [comment]
~~Well yes, but I wonder how many mods add higher tier versions of stuff~~
