### ISSUE TITLE
Interplanetary Launch Terminal / Planetary Launch Terminal

### ISSUE THREAD

**Issue by ReallyBasicGames** [Anuken/Mindustry-Suggestions#2465]
**Describe the content or mechanics you are proposing.**
Make it possible to jump to any sector once the ILT (or some other thing) is built. You would be able to launch a core (but nothing else) to any sector on the current planet, as well as any resources put in the core build on the ILT.  You would be able to select a core to be built on the ILT, then be able to load additional resources into it before launching. Once ready to launch, all you need to do is select a destination sector.  HOWEVER, you would not be able to use this to launch to different planets. When launching to different planets, you have a pre-determined destination. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think this would be a good idea because it would be nice to be able to jump around the planet to specific maps versus conquering each sector just to get to one. However, this should be penalized by not having a base configuration, as well as having to manually load and build the core you want to launch.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
> I think that just like normal launching it doesn't necessarily need a cooldown, but other than that I'm in, since campaign doesn't really need it but it is funee and idk why anyone would play past tar fields and extraction outpost, other than for funee / They're new so they don't yet know the game is about to become launch pad spam (which means there is a low of extensively pointless stuff to do, so an ILT could get a niche).

what

**Comment by OnyxFinger** [comment]
"what' what ?
I understand this was proably hard to read but you could read #2467

**Comment by ReallyBasicGames** [comment]
> I think that just like normal launching it doesn't necessarily need a cooldown, but other than that I'm in, since campaign doesn't really need it but it is funee and idk why anyone would play past tar fields and extraction outpost, other than for funee / They're new so they don't yet know the game is about to become launch pad spam (which means there is a low of extensively pointless stuff to do, so an ILT could get a niche).

I never said there should be a cooldown, I only am saying the core that is to be launched must be built, and the resources must be manually loaded (by conveyor or other means) and launched.

**Comment by OnyxFinger** [comment]
> > I think that just like normal launching it doesn't necessarily need a cooldown, but other than that I'm in, since campaign doesn't really need it but it is funee and idk why anyone would play past tar fields and extraction outpost, other than for funee / They're new so they don't yet know the game is about to become launch pad spam (which means there is a low of extensively pointless stuff to do, so an ILT could get a niche).
> 
> I never said there should be a cooldown, I only am saying the core that is to be launched must be built, and the resources must be manually loaded (by conveyor or other means) and launched.

oh ok I see. So it's just like a large scale core launching.

**Comment by oinkymoo** [comment]
> "what' what ?
> I understand this was proably hard to read but you could read #2467

what you said is completely valid but i just could not follow what you were saying, unlike in the issue you linked

**Comment by OnyxFinger** [comment]
> > "what' what ?
> > I understand this was proably hard to read but you could read #2467
> 
> what you said is completely valid but i just could not follow what you were saying, unlike in the issue you linked

Ah. I was basically saying that it would fit well.

**Comment by ReallyBasicGames** [comment]
> > > I think that just like normal launching it doesn't necessarily need a cooldown, but other than that I'm in, since campaign doesn't really need it but it is funee and idk why anyone would play past tar fields and extraction outpost, other than for funee / They're new so they don't yet know the game is about to become launch pad spam (which means there is a low of extensively pointless stuff to do, so an ILT could get a niche).
> > 
> > 
> > I never said there should be a cooldown, I only am saying the core that is to be launched must be built, and the resources must be manually loaded (by conveyor or other means) and launched.
> 
> oh ok I see. So it's just like a large scale core launching.

Somewhat, but only if you are trying to launch to a sector you are not connected to. If you are connected to the sector or the sector is part of the campaign, you may still choose to launch normally. Launching from the modified ILT would allow you to launch to any sector you are NOT connected to but ONLY on the planet the ILT is on. Hope that makes more sense.

**Comment by oinkymoo** [comment]
> Ah. I was basically saying that it would fit well.

what would fit well with what

**Comment by OnyxFinger** [comment]
> > Ah. I was basically saying that it would fit well.
> 
> what would fit well with what

...... The game maybe ? idk we're suggesting stuff for a game lol

**Comment by darmaangelo** [comment]
> **Describe the content or mechanics you are proposing.**
> Make it possible to jump to any sector once the ILT (or some other thing) is built. You would be able to launch a core (but nothing else) to any sector on the current planet, as well as any resources put in the core build on the ILT. You would be able to select a core to be built on the ILT, then be able to load additional resources into it before launching. Once ready to launch, all you need to do is select a destination sector. HOWEVER, you would not be able to use this to launch to different planets. When launching to different planets, you have a pre-determined destination.
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> I think this would be a good idea because it would be nice to be able to jump around the planet to specific maps versus conquering each sector just to get to one. However, this should be penalized by not having a base configuration, as well as having to manually load and build the core you want to launch.
> 
> **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 2. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 3. * [x]  I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

in my campaign i collectively launch resources to certain safe sector and from that start point i spam launcher to the target  sector i need

**Comment by oinkymoo** [comment]
> > **Describe the content or mechanics you are proposing.**
> > Make it possible to jump to any sector once the ILT (or some other thing) is built. You would be able to launch a core (but nothing else) to any sector on the current planet, as well as any resources put in the core build on the ILT. You would be able to select a core to be built on the ILT, then be able to load additional resources into it before launching. Once ready to launch, all you need to do is select a destination sector. HOWEVER, you would not be able to use this to launch to different planets. When launching to different planets, you have a pre-determined destination.
> > **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> > I think this would be a good idea because it would be nice to be able to jump around the planet to specific maps versus conquering each sector just to get to one. However, this should be penalized by not having a base configuration, as well as having to manually load and build the core you want to launch.
> > **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> > 
> > 1. * [x]   I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> > 2. * [x]   I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> > 3. * [x]   I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
> in my campaign i collectively launch resources to certain safe sector and from that start point i spam launcher to the target sector i need

you completely misread the suggestion. ReallyBasicGames wants to launch cores to everywhere, not materials

**Comment by itcannotbe** [comment]
Is it me or only letting you conquer adjacent tile is actually a conscious decision of the dev.

Also what happens when you launch your core? Does one magically appears p

**Comment by itcannotbe** [comment]
Is it me or only letting you conquer adjacent tile is actually a conscious decision of the dev.
