### ISSUE TITLE
Its a nice fix or addition 

### ISSUE THREAD

**Issue by Kman247** [Anuken/Mindustry-Suggestions#2467]
Describe the content or mechanics you are proposing.
Its not really a new thing but currently i play on a crome book yea ik not my first choice but it was a gift so I use it but currently and idk if this is on pc as well but i end up having to use the middle mouse button like clicking the scroll wheel to see where the block i am going to be placing will place because they block or item im placing dose not follow the pointer. it you could some how allow you to enable it to follow the pointer that would be great because its also hard to find and locate where to put a schematic because it dose not follow the pointer unless i hold left click or hold down the scroll wheel.

**Comment by oinkymoo** [comment]
1. this is a "bug" that has already been reported. anuke's response was that google play version does not now have mouse support nor will it ever because it is primarily the android version
2. idk what y'all are doing to bypass the template but it needs to stop

in conclusion: close this
