### ISSUE TITLE
Larger illuminators

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2468]
**Describe the content or mechanics you are proposing.**

Quite simply, a larger illuminator. With the new lighting you have recently added (which btw looks awesome) I feel like this would be an appropriate time to address how annoying the current illuminator is. The new T4 naval is able to light up a HUGE area according to your dev preview. I know that it is not a final product, but, a large illuminator and a x-tra large illuminator won't hurt. I feel like the large one should have anywhere from double to triple the current illuminator's radius. And the XL one  should have a range similar to the one we saw on the boat.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The current illuminator is very small and it does not light up a lot of area. It is very spammy and it is hard to get power to all your illuminators. A bigger illuminator would get rid of some of the spammy-ness and make it less of a headache to fully light up a sector.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I think you forgot that naval illumination needs to be cover a large area because, you can't place down anything in middle of deep liquids, by extension, illuminators.

**Comment by Ineedause** [comment]
im sorry, but I just don't see how what you said is related

**Comment by numer99** [comment]
this is a very good idea
