### ISSUE TITLE
logic editor: instruction blocks display address & jump block display target address

### ISSUE THREAD

**Issue by BlackDeluxeCat** [Anuken/Mindustry-Suggestions#2470]
**Describe the content or mechanics you are proposing.**
Jump curves are mixed up and sometimes disappeared. And @ counter is nonvisual. 
So,
1. Every instruction block displays its instruction address.
2. Add additional texts to jump block to show its target address.

would help a lot.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's convenient for built-in editor users. Jump target can be accurately followed. @ counter get improved, too. 

For example: 
I add address text by the side of copy button, and jump target after last variable
![image](https://user-images.githubusercontent.com/65377021/119626842-30beea00-be3e-11eb-87d9-42368ff6fd34.png)
![image](https://user-images.githubusercontent.com/65377021/119631088-243c9080-be42-11eb-832a-b1565d7359a3.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
this looks really good i support this

**Comment by SMOLKEYS** [comment]
yes please

a lot of jump lines intersect, causing a lot of confusion on where they jump to

**Comment by SMOLKEYS** [comment]
if this is a "Added in 7.0" i will cri

**Comment by oinkymoo** [comment]
"Added in 126.4"
