### ISSUE TITLE
Spawns points

### ISSUE THREAD

**Issue by dude404** [Anuken/Mindustry-Suggestions#2471]
**Describe the content or mechanics you are proposing.**
On the map vs. cpu create "NPC Spawn points" , these building send periodically some NPC that attack your base. 
NPC Spawns points are located on different places and can be destroyed, if destroyed no more spawns

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Make the vs. cpu more fun and challenging 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Can't you just place an enemy core

**Comment by oinkymoo** [comment]
this already exists. some enemy bases have unit factories, which produce units until destroyed

**Comment by OnyxFinger** [comment]
Wat. Just add buildings

**Comment by dude404** [comment]
I was more thinking of a NPC building that would add more ennemies batch to the next wave (not factories that produces units that get killed one by one)

**Comment by SMOLKEYS** [comment]
> On the map vs. cpu create "NPC Spawn points"

***you are basically asking anuke to give bots the ability to build EDITOR ONLY BUILDABLE BLOCKS***

**Comment by SMOLKEYS** [comment]
***this suggestion is a combination of unbalanced and cursed***

**Comment by SMOLKEYS** [comment]
***close NOW***

**Comment by DarkBrick** [comment]
this sucks close it

**Comment by Random-internet-person** [comment]
It's a cool idea but it could've been worded better.
