### ISSUE TITLE
jump arrow highlighting change

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2472]
**Describe what you would like changed, and why.**

currently, when you hover over the start of the arrow for a jump instruction in logic, the arrow is highlighted in purple. this isn't very useful when the arrow disappears into the void that is the edge of the screen.

**Describe the changes you want to propose. Include possible alternatives.**

a way to keep the highlight active while you continue to scroll. possibly by clicking the base of the arrow but not dragging it anywhere. alternatively, do what is suggested in #2470 to make finding the ends of arrows easier

**Comment by abdallah362** [comment]
i am with you in this point
