### ISSUE TITLE
Illuminator wider range and true sight function

### ISSUE THREAD

**Issue by darmaangelo** [Anuken/Mindustry-Suggestions#2474]
**Describe the content or mechanics you are proposing.**

Since illuminator dont have a good use in the game beside cosmetic i suggesting to make illuminator have a true sight to see invisible unit such as sand worm (future suggestion) or submarine (future suggestion)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Beside mining experience war strategic experience will increased since sand worm is from dune and submarine is from Red Alert
make mindustry the best RTS ever

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

sand worm 
![image](https://user-images.githubusercontent.com/60910786/119793250-9c698b80-bf00-11eb-8b84-a41ae1b04c2c.png)

submarine
![image](https://user-images.githubusercontent.com/60910786/119793457-d0dd4780-bf00-11eb-861b-dc2a018bdbc0.png)

**Comment by SMOLKEYS** [comment]
> submarine

do you not know that this will never be added

> sand worm

um what

**Comment by D-player1** [comment]
Illuminator doesn't need a buff, it's relatively cheap anyway

**Comment by darmaangelo** [comment]
> Illuminator doesn't need a buff, it's relatively cheap anyway

so its kindda useless

**Comment by D-player1** [comment]
You can say the same thing to solar panels

**Comment by genNAowl** [comment]
There were a few illuminator buff-related things before, however all were rejected due to the fact that if the illuminator range was made any bigger, it's light would flash-on/off as it moved in and out of the screen. (Like the current thermal generator lighting)

In any case, this is not a problem in 7.0, which probably means buffs to the illuminator or even a T2 one will probably be in sight.

**Comment by darmaangelo** [comment]
> There were a few illuminator buff-related things before, however all were rejected due to the fact that if the illuminator range was made any bigger, it's light would flash-on/off as it moved in and out of the screen. (Like the current thermal generator lighting)
> 
> In any case, this is not a problem in 7.0, which probably means buffs to the illuminator or even a T2 one will probably be in sight.

ok agree close this 

but.... the radar or thermal detector should be needed in some cases
