### ISSUE TITLE
new transport unit Omnithopter

### ISSUE THREAD

**Issue by darmaangelo** [Anuken/Mindustry-Suggestions#2475]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

mass driver is good but we need drone to pickups that have unlimited range

it called omnithopter from dune the idea is some ompithopter will pickup sum item in lounchpad and drop it to target drop pad
if the animation bothering you the omnithopter could fly away and disappear while it moves and shown again whenever it drop the load

spec:
structure: skybay: this is the landing pad for omnithopter
unit: omnithopter: can be produce in factory that automaticly looking for skybay to land

positive:  have wider range than mass driver
negative: have slower speed than mass driver (half of the speed)
positive:  have cheaper cost 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

![image](https://user-images.githubusercontent.com/60910786/119792780-2e24c900-bf00-11eb-8a16-9646e1ce18eb.png)
![image](https://user-images.githubusercontent.com/60910786/119792979-62988500-bf00-11eb-93e9-d9ace314471c.png)

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Looks like someone can't use logic

**Comment by darmaangelo** [comment]
> carry payloads

it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either

**Comment by darmaangelo** [comment]
> Looks like someone can't use logic

Looks like some one doesn't understand English.

**Comment by oinkymoo** [comment]
> > Looks like someone can't use logic
> 
> Looks like some one doesn't understand English.

someone is correct there

**Comment by oinkymoo** [comment]
you can already do this with logic. close this

**Comment by itcannotbe** [comment]
> > carry payloads
> 
> it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either

Oh, didn't you know? Payload drivers are like mass drivers but can hurl payloads into a receiving payload driver.

And you know what payloads it can hurl? Units and other blocks that fits it, like I don't know, containers? You know what containers can contain? Items? What items? Everything, at 200 per item. Yeah, I don't really think we need this suggestion get implemented.

**Comment by Random-internet-person** [comment]
Logic. Close

**Comment by WilloIzCitron** [comment]
but the user doesnt know logic this unit is needed

**Comment by the-red-soul** [comment]
its called stealing the logic from someone else just like every other noob in this game does. 

Close the issue as this is already in the game.

**Comment by darmaangelo** [comment]
> but the user doesnt know/experienced about logic this unit is needed

thanks for the response
this unit is especially for long transport unit
and due the crowd of multiplayer game the usage of flare by logic is too immense
not even 24 flare satisfy 15 player in same faction
the result is the production speed is very limited

**Comment by darmaangelo** [comment]
> Logic. Close

**Comment by darmaangelo** [comment]
> you can already do this with logic. close this

doesn't work well in multiplayer that consist at least 20 players that have the same logic and using flare over and over and over

**Comment by darmaangelo** [comment]
> > > carry payloads
> > 
> > 
> > it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either
> 
> Oh, didn't you know? Payload drivers are like mass drivers but can hurl payloads into a receiving payload driver.
> 
> And you know what payloads it can hurl? Units and other blocks that fits it, like I don't know, containers? You know what containers can contain? Items? What items? Everything, at 200 per item. Yeah, I don't really think we need this suggestion get implemented.

are you explaining some mod feature? because loaded container cannot be transported via payload

**Comment by itcannotbe** [comment]
> > > > carry payloads
> > > 
> > > 
> > > it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either
> > 
> > 
> > Oh, didn't you know? Payload drivers are like mass drivers but can hurl payloads into a receiving payload driver.
> > And you know what payloads it can hurl? Units and other blocks that fits it, like I don't know, containers? You know what containers can contain? Items? What items? Everything, at 200 per item. Yeah, I don't really think we need this suggestion get implemented.
> 
> are you explaining some mod feature? because loaded container cannot be transported via payload

It's called implemented in the the next version of the game.

**Comment by darmaangelo** [comment]
> > > > > carry payloads
> > > > 
> > > > 
> > > > it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either
> > > 
> > > 
> > > Oh, didn't you know? Payload drivers are like mass drivers but can hurl payloads into a receiving payload driver.
> > > And you know what payloads it can hurl? Units and other blocks that fits it, like I don't know, containers? You know what containers can contain? Items? What items? Everything, at 200 per item. Yeah, I don't really think we need this suggestion get implemented.
> > 
> > 
> > are you explaining some mod feature? because loaded container cannot be transported via payload
> 
> It's called implemented in the the next version of the game.
> 
> You know, the one in development as of the writing of this comment.

aaah i see thats a good news

**Comment by darmaangelo** [comment]
> > > > > carry payloads
> > > > 
> > > > 
> > > > it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either
> > > 
> > > 
> > > Oh, didn't you know? Payload drivers are like mass drivers but can hurl payloads into a receiving payload driver.
> > > And you know what payloads it can hurl? Units and other blocks that fits it, like I don't know, containers? You know what containers can contain? Items? What items? Everything, at 200 per item. Yeah, I don't really think we need this suggestion get implemented.
> > 
> > 
> > are you explaining some mod feature? because loaded container cannot be transported via payload
> 
> It's called implemented in the the next version of the game.
> 
> You know, the one in development as of the writing of this comment.

give me the reference link btw to make sure what you saw is not mod from tower defense mini game blockloader

**Comment by oinkymoo** [comment]
> > > > > > carry payloads
> > > > > 
> > > > > 
> > > > > it flies just like mass driver but not loaded and shoot but it flies to the space and dropped in target area ints not teleportation either
> > > > 
> > > > 
> > > > Oh, didn't you know? Payload drivers are like mass drivers but can hurl payloads into a receiving payload driver.
> > > > And you know what payloads it can hurl? Units and other blocks that fits it, like I don't know, containers? You know what containers can contain? Items? What items? Everything, at 200 per item. Yeah, I don't really think we need this suggestion get implemented.
> > > 
> > > 
> > > are you explaining some mod feature? because loaded container cannot be transported via payload
> > 
> > 
> > It's called implemented in the the next version of the game.
> > You know, the one in development as of the writing of this comment.
> 
> give me the reference link btw to make sure what you saw is not mod from tower defense mini game blockloader

#dev-previews
