### ISSUE TITLE
Fog of war

### ISSUE THREAD

**Issue by darmaangelo** [Anuken/Mindustry-Suggestions#2476]
**Describe the content or mechanics you are proposing.**

the map is dark already especially in the night
but I suggesting some option to activate fog of war
Fog or war type:
1. [unexplored] total darkness and opened when explored (lore: explore the new planet that satellites cannot scan pass trough)
2. [disruptor fog] fog shade any non allied activities is hidden (lore: magnetic waves disturbance make any movement of enemy is not detected on radar)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

[positive] It increase the feeling of adventure and challenge for the new player, again its for the good use of illuminator
[negative] map hack every where. but dont worry since it will enjoyed in campaigns too
[positive] in multiplayer ATTACK there is some user role to explore the map

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

![image](https://user-images.githubusercontent.com/60910786/119794742-fe76c080-bf01-11eb-951e-41bc360568ab.png)

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Stop suggesting something from other games

**Comment by D-player1** [comment]
Also fog of war already exists

**Comment by darmaangelo** [comment]
> Also fog of war already exists

nope it isn't 
darkness is different from blindness of FoW

**Comment by D-player1** [comment]
> > Also fog of war already exists
> 
> nope it isn't
> darkness is different from blindness of FoW

Already. Exists.
![IMG_20210527_180311](https://user-images.githubusercontent.com/70744599/119815594-ea3cbe80-bf15-11eb-9bdd-1e76bb6e3a67.jpg)

**Comment by skipydog** [comment]
> > > Also fog of war already exists
> > 
> > 
> > nope it isn't
> > darkness is different from blindness of FoW
> 
> Already. Exists.
> ![IMG_20210527_180311](https://user-images.githubusercontent.com/70744599/119815594-ea3cbe80-bf15-11eb-9bdd-1e76bb6e3a67.jpg)

This isn't fog of war, this is lighting. You can still see the enemy base and their parts that light up from just moving the screen over to them from anywhere.

**Comment by Random-internet-person** [comment]
This has been suggested before. It was in the game for a time, but was removed, which I'm sure was for a reason. Close.

**Comment by IIINSTINCT** [comment]
> > > > Also fog of war already exists
> > > 
> > > 
> > > nope it isn't
> > > darkness is different from blindness of FoW
> > 
> > 
> > Already. Exists.
> > ![IMG_20210527_180311](https://user-images.githubusercontent.com/70744599/119815594-ea3cbe80-bf15-11eb-9bdd-1e76bb6e3a67.jpg)
> 
> This isn't fog of war, this is lighting. You can still see the enemy base and their parts that light up from just moving the screen over to them from anywhere.

Just turn off enemy lights rule..... but of course you can still see them on the mini map then make a suggestion to hide all enemy and buildings on the mini map when enemy lights are off

**Comment by genNAowl** [comment]
A few relative messages
https://discord.com/channels/391020510269669376/396416151032299521/780918929706319893
https://discord.com/channels/391020510269669376/663854113418641429/773374258147098684
https://discord.com/channels/391020510269669376/396416151032299521/695738114492072023

**Comment by OnyxFinger** [comment]
> > > > > Also fog of war already exists
> > > > 
> > > > 
> > > > nope it isn't
> > > > darkness is different from blindness of FoW
> > > 
> > > 
> > > Already. Exists.
> > > ![IMG_20210527_180311](https://user-images.githubusercontent.com/70744599/119815594-ea3cbe80-bf15-11eb-9bdd-1e76bb6e3a67.jpg)
> > 
> > 
> > This isn't fog of war, this is lighting. You can still see the enemy base and their parts that light up from just moving the screen over to them from anywhere.
> 
> Just turn off enemy lights rule..... but of course you can still see them on the mini map then make a suggestion to hide all enemy and buildings on the mini map when enemy lights are off

FoW means you have to scout too. There isn't just turning off buildings on the map, but preventing pan viewing too. By turning off so many of these things, FoW should be added as it's own gamemode, not just different dark mode.

**Comment by OnyxFinger** [comment]
> A few relative messages
> https://discord.com/channels/391020510269669376/396416151032299521/780918929706319893
> https://discord.com/channels/391020510269669376/663854113418641429/773374258147098684
> https://discord.com/channels/391020510269669376/396416151032299521/695738114492072023

For anyone who doesn't understand a thing of this man(s intentions (like many may) og of war isn't planned, but has even been experimentally done. This means that not only this is viable because making a suggestion that was already planned isn't good (it's a good thing if it's not planned, because you know, that's what suggestions are :D), but also it was starting to get coded, so it is gonna be easier to implement it. This FoW is even more favored. I would love this to be added for PvP, more interest into scouting and trying to not let enemies attack you then chase them with scatters and instead having to place these very scatters.
