### ISSUE TITLE
F*kin polies

### ISSUE THREAD

**Issue by Random-internet-person** [Anuken/Mindustry-Suggestions#2478]
**Describe the content or mechanics you are proposing.**

It's really annoying whenever polies rebuild stuff without having the proper resources in the core, causing massive waste of resources. I think that if there are insufficient resources in the core to rebuild a structure, the polies shouldn't rebuild it.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

REALLY helpful QOL change and I think a lot of players would appreciate it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
Well, it could cause sudden resource downfall once theres enough resources to rebuild the destroyed block, causing confusion.

So maybe do this?

Example:

Micro Processor costs 80 copper, 50 lead and 30 silicon

80 × 1.5 = 120 - 80 = 40
50 × 1.5 = 75 - 50 = 25
30 × 1.5 = 45 - 30 = 15

Maybe make it start rebuilding when there's 1.5x more than enough resources?

**Comment by OnyxFinger** [comment]
I think that the blocks destroyed queue thingy should be clearable, it would fix this issue and the one of losing a core and having the builders rebuild everything around it.

**Comment by Random-internet-person** [comment]
@SMOLKEYS That's a good point.

**Comment by kapzduke** [comment]
> Well, it could cause sudden resource downfall once theres enough resources to rebuild the destroyed block, causing confusion.
> 
> So maybe do this?
> 
> Example:
> 
> Micro Processor costs 80 copper, 50 lead and 30 silicon
> 
> 80 × 1.5 = 120 - 80 = 40
> 50 × 1.5 = 75 - 50 = 25
> 30 × 1.5 = 45 - 30 = 15
> 
> Maybe make it start rebuilding when there's 1.5x more than enough resources?

what about really expensive blocks? should these not be rebuilt at all?

**Comment by oinkymoo** [comment]
> I think that the blocks destroyed queue thingy should be clearable, it would fix this issue and the one of losing a core and having the builders rebuild everything around it.

if destroyed blocks are in an area selected for deletion, their ghost will disappear as well, and they will be removed from the rebuild queue

**Comment by buthed010203** [comment]
The plural of poly is polys, it drives me mad when people get this wrong or say `silicone` they are not the same material smh.

**Comment by buthed010203** [comment]
> > I think that the blocks destroyed queue thingy should be clearable, it would fix this issue and the one of losing a core and having the builders rebuild everything around it.
> 
> if destroyed blocks are in an area selected for deletion, their ghost will disappear as well, and they will be removed from the rebuild queue

Note that this only applies in single player or when hosting a game, in order to prevent rebuilding in multiplayer you will have to track down the tiles where they are building and place a belt or something over those tiles then remove them again to cancel the ghosts.

**Comment by SMOLKEYS** [comment]
> > Well, it could cause sudden resource downfall once theres enough resources to rebuild the destroyed block, causing confusion.
> > So maybe do this?
> > Example:
> > Micro Processor costs 80 copper, 50 lead and 30 silicon
> > 80 × 1.5 = 120 - 80 = 40
> > 50 × 1.5 = 75 - 50 = 25
> > 30 × 1.5 = 45 - 30 = 15
> > Maybe make it start rebuilding when there's 1.5x more than enough resources?
> 
> what about really expensive blocks? should these not be rebuilt at all?

Rebuild when there's 2×/2.5× more than enough resources?

**Comment by Humanoid-X** [comment]
~How are we supposed to fuck them when they don't have the required reproductive organ?~

**Comment by Random-internet-person** [comment]
@Humanoid-X _**no that is cursed**_

**Comment by Sector171** [comment]
The traditional way to deal with this is using logic to control polys, but this kills their ability of helping players in building.

A good solution for this issue is to add a feature in logic for poly like "Aoturebuild" if true poly can build destroyed stuff if false it can't, default value is true.

 and then if the player doesn't want them to rebuild, in a processor he can use sensor to check "Autorebuild" if true--> use unit control to change it to false, if false do nothing, and those he will not control polys so they can do their job(helping the player).

**Comment by SMOLKEYS** [comment]
> ~How are we supposed to fuck them when they don't have the required reproductive organ?~

die

**Comment by BorisA11** [comment]
It can probably be stopped by logic. All game AIs are rather basic, purposely.
