### ISSUE TITLE
Modular storage for containers and vaults

### ISSUE THREAD

**Issue by Random-internet-person** [Anuken/Mindustry-Suggestions#2479]
**Describe the content or mechanics you are proposing.**

Containers and Vaults should link together and share storage even when they're connected to just each other, not just when they're attached to the core.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Eh, I just think it'd be convenient.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
100k storage go

**Comment by D-player1** [comment]
Absolutely no
![IMG_20210527_212908](https://user-images.githubusercontent.com/70744599/119844442-a1473300-bf32-11eb-9bce-26b05f7b52d0.jpg)

**Comment by Random-internet-person** [comment]
@D-player1 I realize this could be used for infinite transport, but it would be HELLA expensive, which sort of defeats the purpose. Just use phase bridges.

**Comment by Random-internet-person** [comment]
@MrDuck557 instantly dead in pvp go

**Comment by OnyxFinger** [comment]
It is very expensive and thus not too OP, however very good still. I think there should be a limit of like 5, or 10 idk.

**Comment by Random-internet-person** [comment]
@OnyxFinger yea

**Comment by genNAowl** [comment]
300 titanium isn't even close to being expensive in any sort of large map. 
But it doesn't matter anyway, as no sort of cost balancing is enough to justify infinite throughput and speed.

If you want to create a limit of amount of containers that can be joined together than I'll ask: 
Have you even given any thought to how something like this would be even implemented?

Finally, imagine what cores would look like, encased with vaults 4-5 layers thick. 
Yeah, it would be pretty ridiculous. It doesn't belong in the game at all.

**Comment by oinkymoo** [comment]
maybe they are capped at 10 items/sec (unloader speed) through the whole system? so 10 items can be moved from any container to any other container per second. if you prefill them it'll work fairly well but if you try to throw 20 items/sec in at one end you're not going to be able to pull anywhere near as much out. also core storage still is true sharing

**Comment by itcannotbe** [comment]
There is a reason why it doesn't exist in the game anymore. 🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄😑😤😩

**Comment by Humanoid-X** [comment]
@itcannotbe By "anymore" you mean?

**Comment by itcannotbe** [comment]
> @itcannotbe By "anymore" you mean?

Heard the term core snek? That was it's orgin.
Which basically made your core part of a map wide teleporter if you knew what were you doing.

**Comment by itcannotbe** [comment]
> Absolutely no
> ![IMG_20210527_212908](https://user-images.githubusercontent.com/70744599/119844442-a1473300-bf32-11eb-9bce-26b05f7b52d0.jpg)

Essentially this ^

**Comment by darmaangelo** [comment]
> > @itcannotbe By "anymore" you mean?
> 
> Heard the term core snek? That was it's orgin.
> Which basically made your core part of a map wide teleporter if you knew what were you doing.

ok how about container and vault can be shared item with maximum cap 4 or 2 linked together
the purpose of this suggestion is to make practical factory that need more than one container
