### ISSUE TITLE
Cargo Transport Units

### ISSUE THREAD

**Issue by CurrentlyGaming** [Anuken/Mindustry-Suggestions#248]
**Describe the content or mechanics you are proposing.**
Large slow walker based Units that can transport possibly an entire vault worth of materials in a fashion similar to that of a convoy of sorts. I feel like it would add more options for Material Transport than just Mass Drivers and Conveyer Belts.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by jaygamer81** [comment]
Already being added smh
