### ISSUE TITLE
More Heavy class units

### ISSUE THREAD

**Issue by Random-internet-person** [Anuken/Mindustry-Suggestions#2481]
**Describe the content or mechanics you are proposing.**

I'm proposing an air branch of my earlier Heavy unit concept. If you have no idea what I'm on about, read [#2549](https://github.com/Anuken/Mindustry-Suggestions/issues/2459). 

Tier 1: Shaft
Production Cost: 20 Silicon, 5 Pyratite
Weapons: 1 Pyratite launcher. Fires chunks of Pyratite that cause fires on impact, and has a 0.5/sec rate of fire.
AI: Hangs just in range of its weapons, like the Zenith, and fires at enemy structures and units.
Speed: Medium

Tier 2: Spear
Production Cost: 40 Silicon, 40 Graphite
Weapons: 2x Pyratite Scorch
AI: Like a souped-up Flare. Repeatedly comes in for bombing runs, torching anything it flies over
Speed: Slow, to balance with Horizon

Tier 3: Polearm
Production Cost: 130 Silicon, 80 Titanium, 40 Metaglass
Weapons: 2x Sticky Bomb Launcher. Fires sticky bombs that attach to enemy structures and units before exploding, inflicting Burning and Blasted as well as dealing a small amount of damage for a range of 1.5 tiles.
AI: Acts like a ground unit, just going straight in and destroying whatever it can.
Speed: Slow

Tier 4: Trident
Production Cost: 850 Silicon, 750 Titanium, 650 Plastanium, Cryofluid
Weapons: 2x Thermium Canister Launcher. Fires canisters that explode into a constant fire that lasts about 10 seconds, inflicting 
                 Melting on anything that touches it.
                 2x Thermium Lance. Like an Eclipse laser, but it does less damage and sets stuff on fire.
AI: Same as Polearm, goes all in.
Speed: REALLY slow, like, Reign-level slow.

Tier 5: Halberd
Production cost: 1050 Silicon, 850 Plastanium, 350 Surge Alloy, 250 Phase Fabric, Cryofluid
Weapons: 2x Pyratite Spectre
                 2x Firebomb launcher. Fires powerful explosive fireballs that do major damage and inflict Burning and Blasted on 
                 targets.

I do recognize that these are OP, and I would appreciate it if you gave me advice on how to correct that.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Well, can't have a ground unit branch without a corresponding air unit branch, because that would bug the hell out of me.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
we litterally already said it was unnecessary to add a route like this.
I think you should keep these for later, when units are actually balanced.

**Comment by MrDuck557** [comment]
I love how T3 and T4 have the same name
and that burning can be easily countered if you have wave/tsunami

**Comment by genNAowl** [comment]
Mmm yes fire I love fire and yes pyratite but

I don't think anyone needs more Unit class ideas, yaknow?

**Comment by oinkymoo** [comment]
did you link the wrong issue? 2549 was your terrible t6 unit suggestion

**Comment by oinkymoo** [comment]
aight i dug up the original heavy unit suggestion you made it is #2458

**Comment by oinkymoo** [comment]
the flare tree already fills this role. also if you're going to complain about a tree existing on the ground but not the air, add air special

**Comment by the-red-soul** [comment]
Could try modding and make the units yourself yknow

**Comment by ShadeStrike62** [comment]
That one constructive comment you were looking for:

Alternative names: (you had two called polearm which sounds meh, same with shaft)
-Guisarme
-Glaive
-Ranseur
-Partizan
-Lucern (hammer)

**Comment by Random-internet-person** [comment]
> I love how T3 and T4 have the same name
> 
oof I fixed that

**Comment by Random-internet-person** [comment]
> Could try modding and make the units yourself yknow
>
I would but I HAVE NO IDEA HOW.

**Comment by the-red-soul** [comment]
> > Could try modding and make the units yourself yknow
> 
> I would but I HAVE NO IDEA HOW.

you going to learn any younger? there is a whole #modding-general in discord and a whole guide with a list of all thr types and attributes for blocks, units, weapons, etc
