### ISSUE TITLE
Any way to stop parallax spamming

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2482]
**Describe what you would like changed, and why.**

Many, many PvP battles end when one side gets a swarm of any fast-building unit, since then parallax spam begins. Due to their low power usage, a scrap-to-impact generator can power alarmingly many of these. They are now what arcs were in v5, a cheap and disposable spam weapon, just much better since it shoots at air.

Not sure how you would handle this issue, but probably same as you did to arc, increased power usage and reduced range. In campaign, its pretty fine, but on multiplayer it's hell. The thing is also very sturdy, so you cant counter a wall of these, since they are always encompanied by lancers.

Maybe just reduce their health points. I think that would do 640 to, say it, 420 or even less. In this case, they won't be shooting walls.

If one side acquires 50 of these turrets, air is completly blocked, unlike any other turret. This means no unit can pass, tier 5 units included. Battles that look like this are very boring and end with a stalemate.

I know there is a good reason why there isn't an air arc, but this is waaay too similar. Just shrink that thick HP bar of its.

**Comment by OnyxFinger** [comment]
Parallaxes suck already. If people spam them, and make them efficient, then there is something wrong. Parallaxes are pricy and innefficient, if you can't find a way to stop them being spammed and ridiculize you, then you should look at how you play first. If anything, parallaxes need a buff.

**Comment by D-player1** [comment]
> increased power usage and reduced range

It has the second largest range for an AA turret (without logic). nerfing it's range just means more fuckery for air units

**Comment by MrDuck557** [comment]
Parallax is very very very low dps. Only real reason to use them is counter logic zenith, but they are expensive and ineffective

**Comment by the-red-soul** [comment]
Parallax is a TRACTOR BEAM. NOT AN ANTI AIR TURRET.

you use the example of a scrap impact to power a parralax. 

If a team is using impacts for power in pvp, then that is on you for allowing them to get impacts. This is pvp. 
Get better at pvp and prevent your enemy from gaining the resources to use parallax. Alternatively get stronger units or use ground based units. A swarm of revs with or without blast can easily defeat a wall of garbage weaponry. 


18 dps. turret. Scatters are better.

**Comment by Humanoid-X** [comment]
It's multiplayer right? 
1. If they can use scrap to impact then you can use it too.
2. If they can spam parallax you can too.
3. Parallax had a small range before. Anuke buffed it for a reason.
4. 120 silicon. "ChEaP".
5. Store more units! Stop trying to attack with only 1 unit!
6. If you still lose when you use their own technique then its you being weak, not they being spammers.

**Comment by Humanoid-X** [comment]
Did you said "50 of these turrrets"? Do the math, 120 silicons * 50 = 6000 silicons. you call that cheap.

**Comment by BorisA11** [comment]
@Humanoid-X In late game, 6k sili is almost nothing. You can easily get it, and use 8 Megas to build a ton of these turrets. If I attacked with, say it, 3 Eclipses, which would be silicon equivalent, I wouldn't be able to pass. These will leech some HP and support turrets will annihilate the units. Even better when shielded. Anyway, the dev has probably already seen this, so to end the discussion this is now closed.

**Comment by BorisA11** [comment]
@the-red-soul 18 dps that isn't reduced by armor as far as I know. This means that it deals consistent damage, regardless of what is it shooting. Quads are immune to scatters, not these beams

**Comment by OnyxFinger** [comment]
> @the-red-soul 18 dps that isn't reduced by armor as far as I know. This means that it deals consistent damage, regardless of what is it shooting. Quads are immune to scatters, not these beams

18 dps for this much price is utterly nothing. Even if armor doesn't reduce it it is fine, and if you wait for a quad to attack, then you will consistently die except in team pvp (But I've seen the horrors of it and don't accept it as genuine pvp anymore), because 98% of the players there are either idiots or unable to go find a good server. Normally T4s aren't needed to end a match, and by using the right and very obvious strategy, you can catch the enemy whe he doesn't have the ressources to spam parallaxes.

Also scatters cost only copper and lead, while parallaxes are muhc pricier idk why quads being immune to scatters and not parallaxes is bad.

**Comment by itcannotbe** [comment]
> Immune to scatters

You kidding me? That's not how armor work you dumdum.
All you have to do is check the code -_-
