### ISSUE TITLE
“Storms” being planet based

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2483]
**Describe what you would like changed, and why.**
The trello mentions a “storm system” added to the game. I think it would be really cool if, while looking at the planet view, you could see thunder/sandstorm clouds, maybe even auroras, things like that.

**Describe the changes you want to propose. Include possible alternatives.**
Essentially, storm clouds and other events caused in the sky would be rendered as these simple moving clouds slightly above the planet surface (so when looking around with the planet map you see the clouds not stuck to the surface).
These clouds and events move around the planets fairly slowly, so that they pass over a hex over the timespan of 10-30 minutes.
Which brings me to the mechanics part: the hexes could check for cloud density above them and change storm intensity to whatever it reads. So, if you see a storm cloud above a hex, you know there are storms happening there at the moment.
That’s the end of my general idea, it’s probably a lot but I think it’d be a great way of introducing the mechanic

**Comment by OnyxFinger** [comment]
yeah idk, we don't have enough intel to decide if yes or no yet.
Maybe in mindustry's lore storms just happen to be created all at once in one short period of time and quickly stop idk

**Comment by MCKHOAHONG** [comment]
@sup3r87 uhmm

**Comment by SMOLKEYS** [comment]
i like it

but

lowend devices

**Comment by sup3r87** [comment]
> i like it
> 
> but
> 
> lowend devices

yeah, but, it'd just be maybe 5 or 6 patches of hexes floating over the surface. it wouldnt need a ton of computer power to render.

**Comment by OnyxFinger** [comment]
> > i like it
> > but
> > lowend devices
> 
> yeah, but, it'd just be maybe 5 or 6 patches of hexes floating over the surface. it wouldnt need a ton of computer power to render.

probably, yes

Unless Anuke likes complicated things a lot
