### ISSUE TITLE
Make Thorium Reactors still be able to warm up and explode even when turned off by logic

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2484]
**Describe what you would like changed, and why.**
With logic and all it's features, the fact Thorium Reactors explode is basically pointless now because you can just make a logic to make them turn off when there's not enough cryofluid being fed to it.

**Describe the changes you want to propose. Include possible alternatives.**
What I want it to be changed is simply make Thorium Reactors explode even when off and also make the heat continuously increase until cryofluid is fed to it again for preventing units to pick thorium in Thorium Reactors for decreasing heat. I can't really think of any possible alternatives for solving that other then these.

**Comment by MrDuck557** [comment]
\*breaks almost every thorium reactor failsafe out there*
Also, IRL nuclear power plants can stop a runaway reaction if they have to

**Comment by OnyxFinger** [comment]
1) No, that's why logic looks like it was made at first, small details / useful functionnalities (and not having zeniths shoot you down and never get shot down then oh no they went boom on the core with a bit of blast, welp, I guess I died !).
2) Why would your reactor even explode in the first place ?

**Comment by ToasterLLC** [comment]
1.no

2. this
> Also, IRL nuclear power plants can stop a runaway reaction if they have to

**Comment by SMOLKEYS** [comment]
Amazing, everyone keeps trashing the purpose of logic blocks.

**Comment by itcannotbe** [comment]
> *breaks almost every thorium reactor failsafe out there*
> Also, IRL nuclear power plants can stop a runaway reaction if they have to

IRL nuclear power plants still need constant cooling even if it is not making any power/ control rods are at 100% insertion.
