### ISSUE TITLE
Increase hp for vaults and storages near cores

### ISSUE THREAD

**Issue by Bananycus** [Anuken/Mindustry-Suggestions#2485]
Increase hp of vaults and storages, because in PVP when storage breaks near a core the core explodes too, and both vaults and storages have abysmal health, so it's not worth it to use it due to blast powder bombing

**Comment by Kyllingene** [comment]
1: Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will automatically filter it out to save him time.

2: If people are destroying the structures directly around your cores, that's a problem. Don't let that happen; increasing the health of storage containers will do nothing.

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*


1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by Bananycus** [comment]
> 2: If people are destroying the structures directly around your cores, that's a problem. Don't let that happen; increasing the health of storage containers will do nothing.

Have you played any pvp at all? Increasing the health of storage containers will make them viable. Suiciding with some blast powder is cheap and the horizon itself will deal some damage when crashing.

>1: Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will automatically filter it out to save him time.

How would you fit this issue in this template?

**Comment by Kyllingene** [comment]
> How would you fit this issue in this template?

Try this:

```
**Describe what you would like changed, and why.**
Container health. in PVP when storage breaks near a core the core explodes too, and both vaults and storages have abysmal health, so it's not worth it to use it due to blast powder bombing


**Describe the changes you want to propose. Include possible alternatives.**
Increase the health of containers by X%
```

> Increasing the health of storage containers will make them viable

Well, we should probably increase the health of conveyors, too, because they are even more important, more succeptible, but have lower health. Try ***defending your base.***

**Comment by ToasterLLC** [comment]
If they're getting to your core, then your defence isn't strong enough.
**Increasing health would do nothing because they can just send more attackers.**

**Comment by Bananycus** [comment]
> Well, we should probably increase the health of conveyors, too, because they are even more important, more succeptible, but have lower health. Try _**defending your base.**_

I think you are missing the point. Breaking a container near a core explodes the core instantly. Defending it is near impossible because its not the unit itself that deals _**enough**_ damage, its the fact that it just existed and it died. Getting more units wont make it much harder to defend because splash damage exists. Cores don’t die to just bombing if you get some defenses.

**Comment by Kyllingene** [comment]
If there is a problem, it is that containers explode cores, and it should be fixed (if you meant that blast-filled containers are blowing up your cores, I have to ask: ***why are you storing blast in your core?***). Otherwise, the problem is your defenses.

**Comment by Bananycus** [comment]
> If they're getting to your core, then your defence isn't strong enough.
> **Increasing health would do nothing because they can just send more attackers.**

They dont have to get to the core though, just close enough to it and die. But thats only the case with storages, because they destroy the core if it breaks. Sending more attackers is both impossible (people rush with 24 units ) and wont help because of splash damage

**Comment by Kyllingene** [comment]
> They dont have to get to the core though, just close enough to it and die

They have to get super, duper close.

**Comment by Bananycus** [comment]
> If there is a problem, it is that containers explode cores, and it should be fixed (if you meant that blast-filled containers are blowing up your cores, I have to ask: _**why are you storing blast in your core?**_). Otherwise, the problem is your defenses.

Thorium and plastanium also explode.

**Comment by Bananycus** [comment]
> > They dont have to get to the core though, just close enough to it and die
> 
> They have to get super, duper close.

Which is practically impossible to defend since you will waste your time and resources on it early and get overrun later.

**Comment by Kyllingene** [comment]
> Which is practically impossible to defend

If you can't defend the core, that is *your* problem, and Anuke will not ruin the balance of the game for that.

> Thorium and plastanium also explode.

Not so much so as to make containers deadly to the core.

Seriously, ***defend the core.***

**Comment by Bananycus** [comment]
> > Which is practically impossible to defend
> 
> If you can't defend the core, that is _your_ problem, and Anuke will not ruin the balance of the game for that.
Any experienced player would tell you that attack is far stronger than defence early game. Its not that I cant defend it, its that no one can defend it. How would increasing health of containers near cores change anything in balance but make them viable? 
> 
> > Thorium and plastanium also explode.
> 
> Not so much so as to make containers deadly to the core.

You are actually just completely wrong here.

**Comment by Kyllingene** [comment]
> Any experienced player would tell you that attack is far stronger than defence early game.

Even though silicon is in short supply? And silicon is not even close to necessary for a good early-game defense?

> You are actually just completely wrong here.

As long as you ***keep enemies away from the core***, then a bit of plastanium and thorium should not kill you. Also, why do you try to argue that early-game defense is worse than attack if your qualms are with plastanium and thorium, both distinctly late-game resources?

**Comment by Bananycus** [comment]
> > Any experienced player would tell you that attack is far stronger than defence early game.
> 
> Even though silicon is in short supply? And silicon is not even close to necessary for a good early-game defense?
> 
Silicon is not in short supply if people know what the hell they are doing 
> > You are actually just completely wrong here.
> 
> As long as you _**keep enemies away from the core**_, then a bit of plastanium and thorium should not kill you. Also, why do you try to argue that early-game defense is worse than attack if your qualms are with plastanium and thorium, both distinctly late-game resources?

You cant keep enemies away from the core because getting 24 horizons is easier then making defences strong enough to defend it.
Thorium is early game, you only need to get laser drills, and you need it to both attack and defend decently . Plastanium  is late game.

**Comment by Kyllingene** [comment]
> getting 24 horizons is easier then making defences strong enough to defend it.

Is this early game or late game? Choose! Either way, though, 24 horizons is an absurd amount of silicon, and takes a while.

**Comment by Bananycus** [comment]
> > getting 24 horizons is easier then making defences strong enough to defend it.
> 
> Is this early game or late game? Choose! Either way, though, 24 horizons is an absurd amount of silicon, and takes a while.

It would take 2 min for a single titanium conveyor of silicon to make 24 horizons, which is not absurd and very early game.

**Comment by D-player1** [comment]
Then just don't use it, isn't that how we deal with solar panels.

**Comment by Bananycus** [comment]
> Then just don't use it, isn't that how we deal with solar panels.

Im not using them, but I would like to use them, and there is no reason for them to be so underpowered

**Comment by itcannotbe** [comment]
> Plastanium is late game.

You're a funny guy.

**Comment by Bananycus** [comment]
> > Plastanium is late game.
> 
> You're a funny guy.

Plastanium requires oil, which requires quite a lot of power (comparatively to other resources), and thorium in most of the situations. Late and endgame are different things.

**Comment by itcannotbe** [comment]
> > > Plastanium is late game.
> > 
> > 
> > You're a funny guy.
> 
> Plastanium requires oil, which requires quite a lot of power (comparatively to other resources), and thorium in most of the situations. Late and endgame are different things.

Oil is easy especially if there is a oil pool in the map. Even if there is none, the power and resources used by an oil extractor is a joke. Plast isn't late game, more like mid game.

**Comment by Kyllingene** [comment]
> It would take 2 min for a single titanium conveyor of silicon to make 24 horizons

Excluding the power, cryofluid, and construction resources required.

**Comment by Bananycus** [comment]
> > It would take 2 min for a single titanium conveyor of silicon to make 24 horizons
> 
> Excluding the power, cryofluid, and construction resources required.

They dont need cryofluid, they need little power, and constructing the factories barely increases the time needed

**Comment by Sector171** [comment]
Kyllingene, itcannotbe 

When was the last time you played mindustry, a serious game I mean? Because the owner of this thread looks experienced and he knows exactly what he is saying and his info is accurate, whereas you are saying whatever.

I don't support or deny his suggestion since it will affect the balance and don't know how will this affect the game.

**Comment by SheepCommander** [comment]
> Kyllingene, itcannotbe
> 
> When was the last time you played mindustry, a serious game I mean? Because the owner of this thread looks experienced and he knows exactly what he is saying and his info is accurate, whereas you are saying whatever.
> 
> I don't support or deny his suggestion since it will affect the balance and don't know how will this affect the game.

False. I see both of these members around the mindustry community very often, while this guy seems like a virtual new comer to the community aspect (I'm not active on the discord or rest of the github stuff tho) and nobody knows how often he plays Mindustry. If itcannotbe and Kyllingene are just saying whatever, he is equally just saying whatever.

That aside, let me just highlight my main takeaways from this thread
- Person did not fill out the template, automatically reducing credibility in the mind of most people who use these threads
- Person demonstrates he does not know how to use the template, complaining that you can fit his entire suggestion into one prompt (1. If that's the case that obviously means you need to spend more time and rethink your suggestion as it cannot meet two simple requirements  2. Kyllingene provides what it would look like if you __actually took 10 seconds to fill it out__, which he proceeded to completely ignore)

> "`If people are destroying the structures directly around your cores, that's a problem. Don't let that happen; increasing the health of storage containers will do nothing.`" - Very valid point

> "`Have you played any pvp at all? Increasing the health of storage containers will make them viable. Suiciding with some blast powder is cheap and the horizon itself will deal some damage when crashing`" 
- Not a fully fleshed out response, immediately resorting to questioning Kyllingene's experience and as it's not a complete thought, with lot's of loose ends, I myself cannot fathom how this is supposed to dispute the fact that you are **not supposed to let the enemy get to the core**.

***

Looking back at what I typed, I think I got carried away so I will not continue this comment.

**Comment by Bananycus** [comment]
> * Person demonstrates he does not know how to use the template, complaining that you can fit his entire suggestion into one prompt (1. If that's the case that obviously means you need to spend more time and rethink your suggestion as it cannot meet two simple requirements  2. Kyllingene provides what it would look like if you **actually took 10 seconds to fill it out**, which he proceeded to completely ignore)

That wasn’t a complaint and I didn’t ignore it, if I didn’t respond to something then i most likely agree with it. 

> > "`If people are destroying the structures directly around your cores, that's a problem. Don't let that happen; increasing the health of storage containers will do nothing.`" - Very valid point
> 
> > "`Have you played any pvp at all? Increasing the health of storage containers will make them viable. Suiciding with some blast powder is cheap and the horizon itself will deal some damage when crashing`"
> 
> * Not a fully fleshed out response, immediately resorting to questioning Kyllingene's experience and as it's not a complete thought, with lot's of loose ends, I myself cannot fathom how this is supposed to dispute the fact that you are **not supposed to let the enemy get to the core**.

The issue is that you cant not let the enemy get to your core without wasting so many resources, space and time that you fall behind so much that you basically already lost. But the core has enough health so you survive if you have some defenses and no storages.

**Comment by itcannotbe** [comment]
> The issue is that you cant not let the enemy get to your core without wasting so many

> resources

Wait so you mean having defenses is a waste of it? I thought the point of the game is to fend of attacks with defenses. 🙄🙄🙄🙄🙄

> space

So why are you encasing your core then?

> Time

If you think building defenses is a waste of time, why are you even playing the game?

**Comment by itcannotbe** [comment]
Also on suicide bombing:

Use waves/tsunamis to knock them away from your structures. 

### Duh

**Comment by OnyxFinger** [comment]
I entirely agree. The fact that they explode makes them almost useless for PvP.



> Also on suicide bombing:
> 
> Use waves/tsunamis to knock them away from your structures.
> ### Duh

tsunami spam rush vs bomber rush..
(bomber rush wins easily)
Also tsunamis are single target weapons, so they can't do much at some point.

>If you think building defenses is a waste of time, why are you even playing the game?

That's litterally pvp..
Placing defenses is very important in PvP, but what he meant is that pre emptively placing them is bad : you lose time for your rush. You would prefer to use your own units as they're mobile and server other purposes, or place manually fed defenses as the enemies come. Right now it is easy to defend T2 rushes and while group attacks  of bombers to work, they will take some time to come too. Defenses are a thing you only want to get when you need to, same goes for every gamemode, the pacing is just different.

**Comment by Sector171** [comment]
>  I see both of these members around the mindustry community very often.

I know this very well, but being active in github  is a thing and being experienced and playing mindustry is different thing, you dont get better in the game without playing even if you know every small feature and detail, more playing means more experience.

I don't want to mention to examples which are many but it is obvious, also the replays confirm that, OnyxFinger looks good as well and knows how things go.

**Comment by OnyxFinger** [comment]
> > I see both of these members around the mindustry community very often.
> 
> I know this very well, but being active in github is a thing and being experienced and playing mindustry is different thing, you dont get better in the game without playing even if you know every small feature and detail, more playing means more experience.
> 
> I don't want to mention to examples which are many but it is obvious, also the replays confirm that, OnyxFinger looks good as well and knows how things go.

Yes. Also why are they mad at vaults made usable in pvp when it doesn't really affect survival and attack much ?

**Comment by itcannotbe** [comment]
> but what he meant is that pre emptively placing them is bad

Um. Just to be clear, you place your defenses before you get attacked, not during nor after.

**Comment by itcannotbe** [comment]
Also on increasing storage during pvp.

The goal of pvp is annihilating one another not amassing a larger quantity of resources, thus rushing to win it is a valid strategy.

If you want to win, rush faster.

Thus early on, rush first before they rush you.

Not turtling before they rush you, it's stupid and does and will not work in mindustry, offense will always win vs defense in PvP in mindustry.

**Comment by itcannotbe** [comment]
Also if you don't want your vault and containers to not burn nor explode when under attack or destroyed just don't place explosive or flammable items within them.

**Comment by Bananycus** [comment]
> Also if you don't want your vault and containers to not burn nor explode when under attack or when destroyed, just don't place explosive or flammable items within them.

Thorium

**Comment by itcannotbe** [comment]
> > Also if you don't want your vault and containers to not burn nor explode when under attack or when destroyed, just don't place explosive or flammable items within them.
> 
> Thorium

I'm sorry it seems that **you didn't know that thorium is explosive 😩😩😩😩😩😤😤😤😤😤🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄**

**Comment by Bananycus** [comment]
> Also on increasing storage during pvp.
> 
> The goal of pvp is annihilating one another not amassing a larger quantity of resources, thus rushing to win it is a valid strategy.
> 
> If you want to win, rush faster.
> 
> Thus early on, rush first before they rush you.
> 
> Not turtling before they rush you, it's stupid and does not and will not work in mindustry, offense will always win vs defense in PvP in mindustry.

 Early rushes can be easily defended but not if you have storages.

**Comment by itcannotbe** [comment]
Thorium is mined using a laser drill or higher, thus is not a early game item, which is past the point where you can even say that they rushed you.

Kindly proceed to the nearest palm tree and it will know what to do with your face.

**Comment by Bananycus** [comment]
> > > Also if you don't want your vault and containers to not burn nor explode when under attack or when destroyed, just don't place explosive or flammable items within them.
> > 
> > 
> > Thorium
> 
> I'm sorry it seems that **you didn't know that thorium is explosive 😩😩😩😩😩😤😤😤😤😤🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄**

Fuses are the best way to defend early game.

**Comment by itcannotbe** [comment]
Fuse is not even early game.

Remember Thorium?

**Comment by Bananycus** [comment]
> Fuse is not even early game.
> 
> Remember Thorium?
> It cannot be mined except by laser drill and higher.

If you dont focus on getting laser drills early game the

**Comment by OnyxFinger** [comment]
@itcannotbe  you clearly have litterally no idea that what you're saying is dumb.
You seem to haven't played PvP enough, or to not have ever got experieced at it at all. Stop it.

**Comment by oinkymoo** [comment]
the issue seems to be the difference between what is considered early game in the campaign vs what is considered early game on custom maps. on custom maps you start with nothing but can speedrun your way to thorium in minutes if it isn't straight-up given to you. in the campaign you have to beat about half a dozen sectors before you even see thorium, which will take several hours.
