### ISSUE TITLE
Map Editor Logic

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2486]
**Describe the content or mechanics you are proposing.**
A map-editor based logic system, able to do what logic does without the restriction of the logic blocks, with some added features.
Some extra features ideas:

Area Triggers
A tool to draw squares, that when X happens in it(Example: Unit enters in it), trigger Y (Example: Spawn units)

General Triggers
A more simple way for an area trigger, acts globally, example: Core is filled with 1000 silicon, do X

Tile Modification
This is based off the WIP feature anuke showed here: https://discord.com/channels/391020510269669376/396416151032299521/822467990502113350
When triggered by a trigger, it changes tiles, being it walls, cliffs, floors, blocks, etc.

Unit Spawning
Force a wave to start, or spawn a unit at X,Y

Block/Unit stat change
Change the stat of a block/unit, like health, when triggered.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It lets map-makers be more creative, expanding endlessly the map editor's abillity to do more intresting and unique things 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

These are just a couple examples of what could be added, the possibilities are really endless. 
Inspired by Clone Drone in the Danger Zone

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I would like this as a better way to get triggers, while not being limited by space for logic and range

**Comment by oinkymoo** [comment]
core destruction-based triggers would also probably be helpful
