### ISSUE TITLE
Add comments tag on logic

### ISSUE THREAD

**Issue by 5lood237** [Anuken/Mindustry-Suggestions#2487]
Sometimes, I just want a comment tag without using print. It serves as a reminder and a way to separate sets of logic that operate as functions.
Perhaps even better, implement grouping with titles for sets of instructions.

**Comment by itcannotbe** [comment]
Why are people suggesting thing that are in the game already?

#413

**Comment by oinkymoo** [comment]
comments aren't very useful if they can't be seen in game

**Comment by 5lood237** [comment]
oinkymoo got it.
I can add `# comment` in my code manually, but it will be gone once I put it in game.
It will make the code look much cleaner if the comments are preserved.
