### ISSUE TITLE
new Material

### ISSUE THREAD

**Issue by darmaangelo** [Anuken/Mindustry-Suggestions#2488]
**Describe the content or mechanics you are proposing.**

soil the brown material soil that gathered in grass

![image](https://user-images.githubusercontent.com/60910786/120061343-03b14800-c087-11eb-9858-8649cfcdc166.png)

soil is gathered from grass tile and this soil can be processed into spore pod (biomass) and scrap
grass > soil > sporepod+scrap
5 soil = 1 sporepod + 1 scrap (balance needed on the process)

![image](https://user-images.githubusercontent.com/60910786/120061645-63f4b980-c088-11eb-80ca-ef0ebb6832f2.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

since a lot of schemas depends on sand because of oil extractor
i suggesting this to make map maker have option to make complexity and challanging terrain. Earth like map can be usefullto develop cilization from a scratch

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MauritanianMapping** [comment]
There is no reason to add a resource that only has a single use, that and also.... why is this nessecary?

**Comment by SaltyBeggarBR** [comment]
There's no reason to make a material made just for making Spore Pods, you can already make them with cultivators and the way you make them should already be good enough, also since Scrap is an amalgamation of many materials (Thorium, Titanium, Copper, etc) this makes no sense both lore-wise and gameplay-wise. You're meant do deal with the limitations the game gives you sometimes and not just be able to use everything everywhere, like you'll only have free energy when there's hot tiles, you'll only get oil easily when there's surface tar, you'll only have scrap when there's surface scrap and it goes on.

**Comment by PickAPlayerNameFirst** [comment]
Oh my, just... Make your own mod to make your dream come true.

**Comment by darmaangelo** [comment]
> There is no reason to add a resource that only has a single use, that and also.... why is this nessecary?

because sand is more usefull than grass
in fact grass have more material than sand
if from water they can get spore pod
grass have much more carbon based material

it doesnt make any sense if sand can be manage into power but grass cant

dillema of this forum
1. suggesting complicated thing = this is bull shit and never happened or you can use logic instead
2. suggesting simple fact thing = this is useless and use mod instead

**Comment by itcannotbe** [comment]
> dillema of this forum

>   suggesting complicated thing = this is bull shit and never happened or you can use logic instead

Logic was created to address a lot of the suggestions in the game that require granular control of blocks and unit control in general.

>   suggesting simple fact thing = this is useless and use mod instead

Most people saya mods because either it's more bloat to the game or doesn't fit the theme of the base game in general.

**Comment by darmaangelo** [comment]
> > dillema of this forum
> 
> > suggesting complicated thing = this is bull shit and never happened or you can use logic instead
> 
> Logic was created to address a lot of the suggestions in the game that require granular control of blocks and unit control in general.
> 
> > suggesting simple fact thing = this is useless and use mod instead
> 
> Most people saya mods because either it's more bloat to the game or doesn't fit the theme of the base game in general.

in fact logic controling unit doesnt worn in open multiplayer game
but still good in tournament if exist

**Comment by darmaangelo** [comment]
> There is no reason to add a resource that only has a single use, that and also.... why is this nessecary?

one more thing that every body must know

in real world we can convert grass into bio gas
fossil fuel such as oil is from simple organism such worm that lay in the soil
coal is from tree fossil 
and grass in the universe is much more rare than material such as sand that contains silicon or carbon 

if sand in this game can be that usefull why isnt grass the most rich material in the universe 

im not gong there but FYI
Uranium and Thorium in the EnvironmentUranium and ... In general, soils and plants contain all naturally occurring radioactive
research by yourself

gras>soil>sporepod+scrap is a generous nerfed version of the real world already

**Comment by stuffyAI** [comment]
> Uranium and Thorium in the EnvironmentUranium and ... In general, soils and plants contain all naturally occurring radioactive
> research by yourself
> 
> gras>soil>sporepod+scrap is a generous nerfed version of the real world already

Who claimed that this game is realistic, and why do you believe it should be.
If 'It exists in the real world' is a reason for suggestions to be implemented we would be playing a game clustered with useless garbage by now.

Unless you come up with a bunch of other uses for this resource I don't see any hope for this suggestion, right now this is too specific and one-dimensional.
