### ISSUE TITLE
ideas for making hydropower possible

### ISSUE THREAD

**Issue by caracauna** [Anuken/Mindustry-Suggestions#2489]
**Describe the content or mechanics you are proposing.** 

waterfall tiles and hydraulic turbines (also some ambiental effects)

making hydropower possible thanks to watefall tiles, maybe give them a little animation. you could place hydraulic turbines on top of the waterfall tiles (¿¿¿if that makes sense???) and that would generate energy over time, just like termic generators, but hydro.

i first saw this idea on the trello, on the "shelved category" so anuke probably has put some thought on this, but wanted to try anyway, some time after i saw the trello i saw screenshots of the cliff mod with water cliff tiles and i thought "what if hydroelectric power got to be a thing with water cliffs???" it made complete sense back then.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

i think waterfalls would give mindustry a little more life, adding effects like waterfall sounds and mist would make the ambient feel more "alive" and "atmospheric", if that makes sense? also it would mean another source of free energy and would give mappers a way to create more interesting maps, like dams for example. (sorry if i had any typo)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
See https://github.com/Anuken/Mindustry-Suggestions/issues/335#issuecomment-663609082

Has been suggested before and killed by the cat.

**Comment by SMOLKEYS** [comment]
You got your reason, now close.

**Comment by caracauna** [comment]
darn didn't see that sorry

**Comment by GitHubUser-B** [comment]
Good idea, I already thought of it as turbines too.
