### ISSUE TITLE
Change OP Miner Drones

### ISSUE THREAD

**Issue by Zephrnos** [Anuken/Mindustry-Suggestions#249]
**Describe what you would like changed, and why.**
Draug miner drones. they should have a silicon cost to build factory. Makes early game too easy.

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by Anuken** [comment]
Not relevant in 6.0, as these drones don't exist.

**Comment by kingb74** [comment]
So ure saying that drug miner drones aren't available anymore u can't do this to us anuke drug miner drones carry us up u can even need them by making them cost something but u can get rid of the without them online mindustry would **collapse** we use so much resources that drag miner drone are the only thing that can keep us productive in early game and their so useful I know u don't see much of them but we the mindustry community do please reconsider

**Comment by itcannotbe** [comment]
We don't even have draugs in the previous versions and we did fine. That areguement is not even remotely true.

**Comment by kingb74** [comment]
Really I see I only started like 3mounth ago so most of the time we use draug miner drones but when u think about it we could survive without them I guess
