### ISSUE TITLE
Improve shock mines

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2491]
**Describe what you would like changed, and why.**
Make the shock mines be actually useful by letting the do their job.

**Describe the changes you want to propose. Include possible alternatives.**
Create a mechanic that helps them not get sniped from a distance to disarm them.

**Comment by BlueWolf3682** [comment]
Basically just make them not hittable by normal bullets? (Shock mines are low to the ground and realistically would only take damage from splash)

**Comment by itcannotbe** [comment]
> Basically just make them not hittable by normal bullets? (Shock mines are low to the ground and realistically would only take damage from splash)

That might work.

Why not also add to that armor to the shock mines so that it would need a decent amount of shots for them to get disarmed.
By armor, make it that 1 shot will just reduce 1 hp. XD

**Comment by oinkymoo** [comment]
units will not actually attack shock mines on their own. they will, however, attack buildings/units behind the mines, and the bullets will hit the intervening mine(s)

**Comment by itcannotbe** [comment]
> units will not actually attack shock mines on their own. they will, however, attack buildings/units behind the mines, and the bullets will hit the intervening mine(s)

Yes, while that's true, nothing is stopping you to just let your units fire forward and make shockmines irrelevant.

**Comment by darmaangelo** [comment]
> Basically just make them not hittable by normal bullets? (Shock mines are low to the ground and realistically would only take damage from splash)

agree static shock have a very low use in the game even for campaign and the building time is immense

**Comment by oinkymoo** [comment]
> > units will not actually attack shock mines on their own. they will, however, attack buildings/units behind the mines, and the bullets will hit the intervening mine(s)
> 
> Yes, while that's true, nothing is stopping you to just let your units fire forward and make shockmines irrelevant.

are we talking about campaign or pvp here

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
