### ISSUE TITLE
cryofluid-based factory

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2494]
**Describe the content or mechanics you are proposing.**

An item factory block that requires cryo. possibly t2 kiln (to combat the intense heat) or t2 plastanium (because titanium)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

currently, all liquids are used in factories (water in multi-press, oil in plastanium, and slag in separators/disassemblers), except for cryo. i suggest that cryo not be left out.

i mean there are the unit factories, but i'm thinking something like at most what is required to run an impact, not the 5 full mixers like are required for the big units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
Hmm yes, let's forget about turrets

**Comment by Bottinator22** [comment]
Current uses for every liquid far as I know of (besides wave and tsunami, everything works for those turrets):
Water:
- Cryofluid Mixer
- Steam Generator
- Multi-Press
- Cultivator
- Oil Extractor
- Force Projector health boost
- A boost for drills and turrets
Oil:
- Plastanium Compressor
- Coal Centrifuge
Slag:
- Separator
- Disassembler
Cryofluid:
- A stronger boost for turrets
- Thorium Reactor
- Impact Reactor
- Differential Generator
- Exponential and Tetrative Reconstructors
- Force Projector health boost
- Hyper Processor

**Comment by PickAPlayerNameFirst** [comment]
Adding another input use on the cryofluid will make its demand higher. We should make t2 cryofluid first to balance everything, since cryo doesn't have an infinite resource type plus it's expensive production and demand for building units or cooling reactors. 

Plus why t2 kiln, meta is perfectly balanced rn..

**Comment by genNAowl** [comment]
Definently reminds me of the T2 factory bandwagon from a long time ago. 
I'll see if I can link a few PRs here: 
https://github.com/Anuken/Mindustry/pull/2836
https://github.com/Anuken/Mindustry/pull/2828
https://github.com/Anuken/Mindustry/pull/2800

~~In any case, Imma do some shameless self promotion and say go check out genNAowl/Upgraded-Factories for many T2 factories~~
