### ISSUE TITLE
Allow user to specify directory to save game data

### ISSUE THREAD

**Issue by i-like-trains72** [Anuken/Mindustry-Suggestions#2495]
**Describe the content or mechanics you are proposing.**
Allow the user to specify the directory to save all game data and add an option to copy all game data to the specified directory automatically. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I feel this will make backing up game data easier, and it is easy to move the data to somewhere else if you want to move the game to a different storage device.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Try copy-pasting the game data? It really isn't hard.

**Comment by i-like-trains72** [comment]
The game still saves data in a different directory, moving the entire game is a pain if you have things in `appdata`. It's easier for the user to find save files and copy them.

**Comment by i-like-trains72** [comment]
Same applies for schematics. I have my schematics in a folder in the `mindustry-windows-64-bit` root folder. 
Makes it much easier especially considering I download files from other websites and navigating back to appdata is a pain.
How's this relate to save files? Well, making backups is a good thing to do especially if you are on a hard sector. Much easier to make backups when you can navigate right to the other game files to store backups

**Comment by i-like-trains72** [comment]
I realize this does not affect everyone but most games let you store the game data in a different directory (this does not apply to Steam AFAIK but you *can* make Steam portable so you can technically store game data in a different directory)
