### ISSUE TITLE
Logic sense mend charge, producing progress, reload progress etc.

### ISSUE THREAD

**Issue by BlackDeluxeCat** [Anuken/Mindustry-Suggestions#2496]
**Describe the content or mechanics you are proposing.**

Add a senseable type @ progress. Let it sense charge of a mender, reload progress of a turret, producing progress of a factory, or other similar attributes. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This new senseable type will bring more potential to building control.

You can use this feature to: 
* order a lot of menders to launch one by one. This helps to survive deadly burst of enemy damage. 
* know reload state of turrets. (turrets with liquid will auto pre-reload)
* calculate remaining time of a T4 or T5 unit reconstructior, or other factories.

_It exists... If it can be observed, it can be controlled._
![image](https://user-images.githubusercontent.com/65377021/120097667-780de900-c164-11eb-92a2-2e310d2abda9.png)![image](https://user-images.githubusercontent.com/65377021/120096973-c3be9380-c160-11eb-8a04-1f9af0592229.png)![image](https://user-images.githubusercontent.com/65377021/120096906-7b9f7100-c160-11eb-928f-470b84446ff5.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Iloveidea** [comment]
I like this.

**Comment by Humanoid-X** [comment]
I like this too.

**Comment by Weathercold** [comment]
good idea

**Comment by BlackDeluxeCat** [comment]
> I like this.
> 你明明完成了为什么不尝试直接提交代码，就像MEEPofFaith他一样，他实现他自己的建议

我只写了用来看的信息栏，没改逻辑
