### ISSUE TITLE
Drill options

### ISSUE THREAD

**Issue by Dryehm** [Anuken/Mindustry-Suggestions#2497]
**Describe the content or mechanics you are proposing.**
an option on what ore to mine when 2 or more ores are covered by the drill

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it will be more convenient because when a single ore is covered when you are gonna mine sand, sand is ignored and that one ore is mined, so I don't want this to happen again.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [ ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
ThIs Is WhAt We CaLl Io SiDe CoNfIgUrAtIoN
rEaDmE.mD
nOw ClOsE

**Comment by itcannotbe** [comment]
[You lied]I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
I'm pretty sure this has already been suggested

**Comment by itcannotbe** [comment]
@Humanoid-X wrong one, it's actually

AdDiTiOnAl CoNfIgUrAtIoN oF bLoCkS

**Comment by itcannotbe** [comment]
> I'm pretty sure this has already been suggested

Check the template, it doesn't matter.

**Comment by Dryehm** [comment]
dammit

**Comment by OnyxFinger** [comment]
rip
