### ISSUE TITLE
Achievement System

### ISSUE THREAD

**Issue by Nigen-Wolf** [Anuken/Mindustry-Suggestions#2498]
**Describe the content or mechanics you are proposing.**
A feature of Achievements will be more interested for player to enjoy playing campaign maps

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Some players experience boredom when it come to playing campaign maps, because all you do is mine, upgrade, capture, and repeat or players who fully reasearched the tech tree. By adding achievements, it will be more interesting and also very challenging for players playing in campaign maps, example of achievement I think of are:

***This is the Beginning*** - land on your first sector
***First Material*** - discover your first material
***First Capture*** - capture your first sector
***Time to move on*** - go to an another sector
***Intruders!*** - discover an enemy base
***Takedown*** - destroy and capture an enemy base
***I have the Power!*** - destroy and capture 10 enemy bases
***Expansion*** - capture 10 sectors
***Thorium power!*** - make a Thorium Reactor explode
***Was that a Nuke?*** - explode an Impact Reactor
***I lost a Base...*** - loose a sector
***Not again...*** - loose the same sector twice
***I survived...*** - survived a whole wave of enemies in a captured sector
***Core upgrade*** - Upgrade the core to Foundation
***Fully maxed Core*** - Upgrade a core to Nucleus
**That was close...** - capture a sector with the core in low health.
***Defeated Troops*** - Loose atleast 50 units
***Core is Full*** - Fill the core to maximum of every material in the game
***This is my World*** - Capture all the sectors

...and many more, as you complete some achivements you get materials as rewards in return. The most easiest achivements will be common materials (Copper, Lead, .etc) while the hardest once are some advance materials (Phase, Surge Alloy, etc.) **OR** a specific sector that requires a specific achievement. And also a counter system where the player knows how many achievements they have completed.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Steam version be like

**Comment by Ruichka** [comment]
- [X] I didn't bother to check if my suggestion was already implemented in the game

**Comment by Nigen-Wolf** [comment]
> * [x]  I didn't bother to check if my suggestion was already implemented in the game

Lol

**Comment by Humanoid-X** [comment]
How are you lol'ing when he's actually refering to you???
Sometimes I actually wonder how human brain work

**Comment by IIINSTINCT** [comment]
Dont suggeste things that is already planned /implemented now close this issue

**Comment by DarkBrick** [comment]
> * [x]  I didn't bother to check if my suggestion was already implemented in the game

lmao

**Comment by WilloIzCitron** [comment]
but in itch version isnt implemented but only steam

**Comment by RedstonerKBC** [comment]
If this ever becomes a thing let's not grant achievements for doing as many dumb little things as possible, like starting a new game, getting killed, placing a processor, blowing up a reactor, etc. Make them useful and worthwhile like creating your first T5 unit, doing a certain amount of damage to enemies over your career, and maybe some things for new players like making surge alloy, maybe some harder achievements like collecting a crud-load of surge alloy.

**Comment by itcannotbe** [comment]
> but in itch version isnt implemented but only steam

So you basically want to remove the few pieces of  exclusivity from a paid version of the game?

**Comment by WilloIzCitron** [comment]
Close this issue, T H I S  H A S  B E E N  I M P L E M E N T E D

**Comment by Humanoid-X** [comment]
True, I agree with RedstonerKBC although this is implemented in steam

So now close @Nigen-Wolf @Nigen-Wolf @Nigen-Wolf @Nigen-Wolf @Nigen-Wolf

**Comment by WilloIzCitron** [comment]
nice
