### ISSUE TITLE
Hidden unit

### ISSUE THREAD

**Issue by darmaangelo** [Anuken/Mindustry-Suggestions#2499]
**Describe the content or mechanics you are proposing.**

An ability that hidden from normal eye 
for the example 
1. Submarine from CC could be New naval class that hidden from the deep
2. Shock mine could be hidden line normal mine would be
3. Wraith from Starcraft could become a new air class stealth flight

is it op NO

because all hidden unit can be detected by player in small radius and radar structure that will be needed in some defensive strategy and homming ability (mostly from sillicon ammo) will be usefull agaisnt this stealth

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

NEW STRATEGY NEW STRATEGY NEW STRATEGY NEW STRATEGY 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

![image](https://user-images.githubusercontent.com/60910786/120137158-e3f06000-c1fd-11eb-9ac7-5a5f895f4085.png)

![image](https://user-images.githubusercontent.com/60910786/120137220-071b0f80-c1fe-11eb-821a-28b4318bc7cd.png)

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
Ahh yes Duplicate suggestion

**Comment by Hyrotrioskjan** [comment]
wasn't this already suggested before?

**Comment by darmaangelo** [comment]
> wasn't this already suggested before?

upgraded with simpler explanation and explain that player is able to detect invisible unit in some range
and silicon will be used more as bullets

**Comment by itcannotbe** [comment]
@IIINSTINCT @Hyrotrioskjan It doesn't matter. Have you actually seen the template?

**Comment by itcannotbe** [comment]
The alternative would actually be implementing Fog of War properly.

**Comment by SMOLKEYS** [comment]
My guy, submarines are never getting added.

**Comment by itcannotbe** [comment]
> My guy, submarines are never getting added.

The cat killed the suggestion for it. Heck even pr that would add functionality for it was killed to.

**Comment by darmaangelo** [comment]
> My guy, submarines are never getting added.

yeah i know but if #releasezacksynder happen #releasesubmarine could too

**Comment by OnyxFinger** [comment]
This will easily be OPier than anything in PvP. Now people will have to place radars everywhere and get jump scared 24/7 by missiles and flying machinegunners making a fire and switching to another coal patch / core while you need to place a radar for them (that's pretty much how wariths would work in 1v1s).

**Comment by Humanoid-X** [comment]
What if we add this as a status effect
Probably sandbox only
Also, I want the ability to have the spawn point spawn with status effect! :D

**Comment by darmaangelo** [comment]
> This will easily be OPier than anything in PvP. Now people will have to place radars everywhere and get jump scared 24/7 by missiles and flying machinegunners making a fire and switching to another coal patch / core while you need to place a radar for them (that's pretty much how wariths would work in 1v1s).

or silicon ammo that always with homming atribute
player actually can detect in in small range

**Comment by darmaangelo** [comment]
> What if we add this as a status effect
> Probably sandbox only
> Also, I want the ability to have the spawn point spawn with status effect! :D

good idea
like test beta unit
this unit cannot be created in factory (yet) and only for campaign / sandbox first and we balancing along the way
