### ISSUE TITLE
graphical option to disable enemy death residue 

### ISSUE THREAD

**Issue by Aelerity** [Anuken/Mindustry-Suggestions#2500]
**Describe the content or mechanics you are proposing.**

A graphical option to disable the unit destroyed residue effect as it would improve perfomance

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

the black explosion trail stuff that's left behind after a unit is destroyed is responsible for a significant amount of the late-game lag. On online servers where there are many enemies each round that black residue accumulates quickly and creates a bunch of lag, since it takes a long time to despawn. This lag goes away once the black residue has despawned (tested in sandbox)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
@Aelerity use the template.

Also this counts as a balancing/feedback.

**Comment by itcannotbe** [comment]
The alternative would be stop decals from stacking in excess of a certain number.

**Comment by SMOLKEYS** [comment]
Basically add a option on Settings > Graphics that configures whether dead unit debris/residue should be shown.

I like the idea.

**Comment by oh-no-sphere** [comment]
noting that the damage that air units deal when they crash on land shall not be removed with that option

**Comment by Humanoid-X** [comment]
I like this actually...
bUt WhErE iS tHe TeMpLaTe

**Comment by PickAPlayerNameFirst** [comment]
T

**Comment by PickAPlayerNameFirst** [comment]
Ah finally, a very good issue. 
This app needs performance improvements for smoother animation and execution.
