### ISSUE TITLE
Sound and Updates

### ISSUE THREAD

**Issue by IvanDem2009** [Anuken/Mindustry-Suggestions#2501]
**Describe the content or mechanics you are proposing.**
I want to add some sounds in Mindustry. First, settings of soundtracks in the map maker. Also, two blocks: microphone and dynamic. Logic commands: Record and Play. Example: 
Record
Var = @sound from microphone1
Play
Var to dynamic1
We can do a phone with this blocks, or make sound effects/music.
Also, i want to see updates like Minecraft Snaphsots. You'll send us files with update data. We can trest new blocks and report you about bugs, we found. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
[X] I have not filled out the template
And split this into two suggestions

**Comment by itcannotbe** [comment]
How on earth would you think record would work?

Also a sound block is already planned on trello.

So yes. 

- [X] I am too lazy to check the Trello to make sure my suggestion isn't planned or implemented in a development version.

**Comment by OnyxFinger** [comment]
logic sound was in the trello

>Also, i want to see updates like Minecraft Snaphsots. You'll send us files with update data. We can trest new blocks and report you >about bugs, we found.

That's litterally a thing

**Comment by Humanoid-X** [comment]
1. Trello.
2. What, did I saw record? I... I...... 
3. Snapshot is a thing. ~I bet you never won ground zero~ Just kidding
