### ISSUE TITLE
Allow players to inhabit and control distributors

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2503]
**Describe the content or mechanics you are proposing.**
Allow players to inhabit and control distributors just like they can control units, turrets, and routers. Similar to routers, clicking any of the 8 sides will cause items to flow in that direction only.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
No reason really. I just think the distributor needs more love. If we can do it with the router why not the distributor? A couple of things: Nobody better say "mods" because if I wanted to make a mod I would've made a mod. I want this in the vanilla game. Yes I know this is a dumb suggestion but it isn't really. No one else has suggested it. It makes sense because it makes things more consistent.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
If anuke wants this kind of thing this suggestion should have been in v6 already but welp not.... anyways jokes on you I can control a distributor with out any mod that modifies player control

**Comment by Phinner** [comment]
Lmao

**Comment by Humanoid-X** [comment]
Distributor is underrated.
I still love you, router.

**Comment by oh-no-sphere** [comment]
i thought it was a bug but why not

**Comment by itcannotbe** [comment]
I though controling a router is a meme. Considering routers are the running joke for for april fools for many years straight already.

**Comment by genNAowl** [comment]
Kind of irrelevant, but you can in servers, by building a router, controlling it and building a distributor over it at the same time (Which is a bug, btw)

**Comment by the-red-soul** [comment]
just use the foo client. you can control a distributor in it since a distributor is just a router it was easy to impliment.

**Comment by Humanoid-X** [comment]
It is a meme, router always is a meme~, but its bad to show racism toward distributor just because it is not a meme~
