### ISSUE TITLE
A button to show all hints

### ISSUE THREAD

**Issue by IIINSTINCT** [Anuken/Mindustry-Suggestions#2504]
**Describe the content or mechanics you are proposing.**
Just A small button with( hints/help ? )that has pages  with all hints (possibly add more hints? Cause some new players are just to dumb to figure out basic things)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will help new players who accidentally closed the hint on their screen since hints will most likely will not comeback leading the player clueless what to do. with this is a thing players can now check the hints every time

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Hyrotrioskjan** [comment]
please
this would mean no more noob survival servers

**Comment by MrDuck557** [comment]
Contributes to a better tutorial
Given that the tutorial is bad, this change is good

**Comment by genNAowl** [comment]
A better tutorial would definently be nice. I kinda want the v5.0 one back.

**Comment by IIINSTINCT** [comment]
Imma close this since anuke may have read this already
