### ISSUE TITLE
Adding i18n in mindustry wiki

### ISSUE THREAD

**Issue by simba-fs** [Anuken/Mindustry-Suggestions#2506]
**Describe the content or mechanics you are proposing.**
Adding i18n to mindustry wiki. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I18n can make more people willing to play this game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
what is "I18n"

**Comment by simba-fs** [comment]
i18n is the abbreviation of internationalization. It means you can add another language to the wiki.

**Comment by oinkymoo** [comment]
i've never seen that abbreviation, but yeah that's a good idea

**Comment by itcannotbe** [comment]
The wiki just pulls information out of bundles in the games source code. Adding this would do virtually nothing.

Though I don't see anything preventing the wiki to be displayed in another language.

**Comment by Humanoid-X** [comment]
True, Anuke said this in the repo of wiki.
