### ISSUE TITLE
Global list sorting

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry-Suggestions#2507]
The global list of servers is sorted by position in file "servers.json". It is a very bad feature. Please make server sorting only ping-based. It will help players to find a server they really like.

**Comment by MrDuck557** [comment]
\*butchers template*

**Comment by Phinner** [comment]
> The global list of servers is sorted by position in file "servers.json". It is a very bad feature. Please make server sorting only ping-based. It will help players to find a server they really like.

Its already ping based i think.

**Comment by Phinner** [comment]
I rembember Anuke talking about that while the .ru thing.

**Comment by Phinner** [comment]
![Screenshot_2021-06-01-16-58-51](https://user-images.githubusercontent.com/62483793/120345449-c5bc5a00-c2fa-11eb-980e-96e9022ee164.png)

As you can see @Darkness6030 , ddns is at the top of my list cauz the ping is low (this is an european server and I live in Belgium)

You have no screenshots to show the server ranking and not filled the template. How shameful you are...
