### ISSUE TITLE
Buff Salvo

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#2508]
**Describe what you would like changed, and why.**

Buff salvo, it's currently doesn't have any use, you can just use ripples that only costs more copper and graphite while a ripple has double the range of a salvo. 

Lancers are also better than salvo since it can pierce infinitely and only uses power which is easy to setup. 

Salvos can't rotate quick enough to fight against fast air unit like flare and horizon, it's better to use scatters instead. 

Thorium salvo is good, but by the time you have thorium, fuse combined with parallax can outclass thorium salvo in any way possible. And lastly, ammo multiplier on salvo is a joke, since you need 1 thorium every bullet, and because a thorium has 4x ammo multiplier, that means salvo can only shoot once with a single thorium, which makes it ammo inefficient

**Describe the changes you want to propose. Include possible alternatives.**
Buff Salvo's ammo damage by 1.5x, or fix the ammo multiplier to make it consume an ammo every shot

**Comment by GitHubUser-B** [comment]
Be careful with harsh people

**Comment by itcannotbe** [comment]
Salvos are bad because of how it groups it's shots. That's pretty much it.

Why not make the shots fly faster?

**Comment by genNAowl** [comment]
Fun fact: Copper flavored salvos actually do less DPS than 3 duos. 

Try it out. It's true. 

And it uses the same amount of copper too. 

**However** Copper is not the only ammo type; Thorium salvos are actually pretty balanced. 

With that said, I would say buff certain ammo types, and nerf lancer damage.

**Comment by MrDuck557** [comment]
> Fun fact: Copper flavored salvos actually do less DPS than 3 duos.

The what

**Comment by genNAowl** [comment]
![DPS](https://user-images.githubusercontent.com/68400583/120375198-5c732180-c2cf-11eb-982c-a3b0be34c8e0.gif)

**Comment by genNAowl** [comment]
Oops ignore that last gif

![DPS](https://user-images.githubusercontent.com/68400583/120375306-7f9dd100-c2cf-11eb-8f80-69d4cf0455ed.gif)

**Comment by Ineedause** [comment]
I used to like salvo, then I started using lancer and oh boy

**Comment by OnyxFinger** [comment]
Basically, salvos are a good AA against zeniths in 1v1s, but it utterly stops there.
I use them sometimes when I don't need much def and there is defense nearby, but salvos tend to suck in my opinion. They have good damage, but no good crowd control. against a small bunch of units they work, but usually a small bunch of healthy units will go past.

**Comment by BorisA11** [comment]
Salvo has large range whem controlled by logic. No buffs needed at all. If you feed it thorium, it becomes really good.

**Comment by PickAPlayerNameFirst** [comment]
> Why not make the shots fly faster?
>

Ah yes, this is what I've been looking for. 
Anyone who likes a salvo bullet speed buff, like the comment. 

But the drawback of a faster bullet speed is a longer belt range (just like what happens in a spectre). 

That would make it a lot useful than other turrets. 

Plus for a 2x2 turret that costs 100 copper and tons of graphite and titanium, this turret should be worthy of its use.

**Comment by itcannotbe** [comment]
> > Why not make the shots fly faster?
> 
> Ah yes, this is what I've been looking for.
> Anyone who likes a salvo bullet speed buff, like the comment.
> 
> But the drawback of a faster bullet speed is a longer belt range (just like what happens in a spectre).
> 
> That would make it a lot useful than other turrets.
> 
> Plus for a 2x2 turret that costs 100 copper and tons of graphite and titanium, this turret should be worthy of its use.

By faster bullet speed I mean you also decrease bullet lifetime  to balance it out.

**Comment by the-red-soul** [comment]
Salvos range has been changed in 7.0 along with some other turrets due to the rangeboosting/overshooting nature of the turret. The turret no longer overshoots but its new range is the average of its current detection range and the bullets overshoot range.

As for a buff to salvo potenitally giving it one pierce could be a good option since spectre has piercing bullets as well. Make it more useful overall against minor crowds.

**Comment by itcannotbe** [comment]
> Salvos range has been changed in 7.0 along with some other turrets due to the rangeboosting/overshooting nature of the turret. The turret no longer overshoots but its new range is the average of its current detection range and the bullets overshoot range.

I think anuke simplified the variables that affect bullet flight, 'cause let's face it, have 3 variables to work with is a pain when you're trying to change something about it.

> As for a buff to salvo potenitally giving it one pierce could be a good option since spectre has piercing bullets as well. Make it more useful overall against minor crowds.

That could be handy also.

**Comment by the-red-soul** [comment]
The overall range of any turret that could be rangeboosted has still been increased.

**Comment by itcannotbe** [comment]
> Fun fact: Copper flavored salvos actually do less DPS than 3 duos.
> 
> Try it out. It's true.
> 
> And it uses the same amount of copper too.
> 
> **However** Copper is not the only ammo type; Thorium salvos are actually pretty balanced.
> 
> With that said, I would say buff certain ammo types, and nerf lancer damage.

You could also increase the number of shots per volley from 3 to 4 to increase it's damage over time aside from the other buff ideas 

Though tbh, lancers are handicapped already. Outside using logic, they have a narrower use case. And that's a topic for another thread.

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry/commit/685adeee9d82ed933e57bec3403328516ac9391d
