### ISSUE TITLE
Allow usage of "Block Info" hotkey to view the stats of a selected region

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2509]
**Describe the content or mechanics you are proposing.**
When a region is selected, using the "Block Info" hotkey should display the stats for that region, similarly to the stats screen displayed when saving or viewing a schematic.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would help streamline the process of creating and comparing designs. With the current system, the fastest way to check the size/power info of a design is to highlight the region, save the schematic, and then type in a placeholder name. Then, you have to delete the placeholder schematic afterward. With the suggested change, checking this information would be as simple as highlighting the region and pressing a single key.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I thought you don't have to save the schematic to find the size and power stats for it?

**Comment by abrasmag3** [comment]
On mobile you do, it may be different on pc

**Comment by genNAowl** [comment]
Even on PC, I believe that you still have to save the schematic to find the stats.

**Comment by MrDuck557** [comment]
you do
you can figure it out manually, but saving is the only way to see explicit info

**Comment by itcannotbe** [comment]
So basically it's a case of make PC more like Mobile then?
