### ISSUE TITLE
When going to schematic menu, automatically add focus to the search bar

### ISSUE THREAD

**Issue by pallas** [Anuken/Mindustry-Suggestions#251]
When I hit T to go to the schematic window, I almost always want to start typing the name of the schematic I want. The search box does not have focus, so I have to then use my mouse to click on it. If it automatically had focus, it would be much quicker.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [S] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
This is implemented in 6.0 from PR https://github.com/Anuken/Mindustry/pull/2089

**Comment by pallas** [comment]
Thanks, sorry for the noise.

**Comment by RogueRedHawk** [comment]
Close the issue, thanks.
