### ISSUE TITLE
Death By Beam

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#2511]
**Describe the content or mechanics you are proposing.**
Air units that are killed by beam weaponry (Quasar, Vela, Corvus, Lancer, Fuse, Meltdown) should just straight-up evaporate. None of this "falling out of the sky" stuff, you just got hit with a laser beam bigger than your entire hitbox. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make the game look a little cleaner, and would make respawns a little faster for players using an air unit that just died because they strayed too close to the enemy defense line.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
not sure about any of the samller lasers (quasar, lancer, fuse), but it would be an interesting counter to blast crashing

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry/pull/5055

**Comment by itcannotbe** [comment]
> [Anuken/Mindustry#5055](https://github.com/Anuken/Mindustry/pull/5055)
> 
> If this PR is merged, than the crashing units debate is solved and this suggestion is (basically) implemented

Does that also work with laser type damage?

**Comment by the-red-soul** [comment]
Damage is damage after all. I dont see why it would not work

**Comment by Violet-Scarelli** [comment]
> not sure about any of the samller lasers (quasar, lancer, fuse), but it would be an interesting counter to blast crashing

Perhaps swapping the skewering lasers for the Foreshadow beam? That seems to deal similar instantaneous explosive damage on a level that seems like it would instantaneously disintegrate a unit.

**Comment by OnyxFinger** [comment]
good idea. It would help with zeniths blast bombing and make sense.

**Comment by EclipsePlays** [comment]
Finally I could get rid of blast bombers.
