### ISSUE TITLE
Where healing

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2513]
**Describe what you would like changed, and why.**
RepairBeamWeapon does not show the healing rate, and instead uses Weapon's setStats method. It doesn't show the healing per second.

**Describe the changes you want to propose. Include possible alternatives.**
Override the setStats to include the healing stat in RepairBeamWeapon.

**Comment by Phinner** [comment]
Shouldn't it be a pr instead of a suggestion ?

**Comment by IIINSTINCT** [comment]
Uhhh since it is still a be anuke has still other things to do maybe thats the reason it is not there

**Comment by MrDuck557** [comment]
> Shouldn't it be a pr instead of a suggestion ?

Can't find the Weapon setStats method, don't know what to override

**Comment by Phinner** [comment]
MMMMMMMH, maybe you can wait a little, the cat is pretty active since the v7 preview...

**Comment by MrDuck557** [comment]
Implemented
