### ISSUE TITLE
[Discord] github-actions and #suggestions

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2514]
**Describe what you would like changed, and why.**

currently, all of the suggestions being closed by @github-actions are creating a lot of clutter in the #suggestions channel, it was especially bad when the bot was first activated and closed 2000 issues over the course of a few hours.

**Describe the changes you want to propose. Include possible alternatives.**

If possible, it would be cool if the webhook bot would simply not post closures by github-actions. however, i have no idea how the thing works or if it would be possible. a much less elegant solution would be to make another bot specifically to delete closure messages from github-actions, or even less elegant, have a human manually do so. if none of these are feasible, uh, ignore this suggestion i guess?

**Comment by Anuken** [comment]
If I could, I would make the webhook only post issue open events. Github doesn't let me do that, and Discord does not provide any configuration.

![image](https://user-images.githubusercontent.com/10100000/120678176-d5a47d00-c465-11eb-9d49-d62142b6b97c.png)

**Comment by oinkymoo** [comment]
ah oh well

**Comment by the-kido** [comment]
oh, a shame
