### ISSUE TITLE
glowing command center indicator(s)

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2515]
**Describe what you would like changed, and why.**
if you have a lot of units surrounding a command center, it is REALLY hard to interact with it, since the units cover it. this has been a critical problem ever since version 5.
so i propose adding glowing arrows, or a glowing icon, or any sort of indicator that always hovers "over" the center that is also displayed on top of units, so you can actually see where a center is when theres a huge crowd of units.

**Describe the changes you want to propose. Include possible alternatives.**
i think the best approach would be making something like the accelerator's glowy effects, but less large and detailed (since it's just a small center). things like moving/still arrows, outlines of the building, even the icon the command center is set to in the middle, all could be done to get rid of this annoying little problem. it would make rallying lots of units, and multiplayer especially, easier to deal with. i dont see a reason why not to add a feature like this, it just makes everyone's time managing units easier.

**Comment by OnyxFinger** [comment]
yup, agreed
It's just too hard to see CCs when units are massed up over them.

**Comment by PickAPlayerNameFirst** [comment]
Also works with megas piling over the core.

**Comment by RedstonerKBC** [comment]
This is similar to 2 other suggestions (one of which I made) where too many flying units in one area causes visual blocking of anything underneath. This isn't just an issue with command centers but other blocks too. Monos mining can make it impoossible to build, too many polys helping you build can get in the way, and now more than ever people are using logic to make flying units do their dirty work which also causes visual obstructions.
