### ISSUE TITLE
Vaporizing Vaporizing1 Vaporizing2 Vaporizing3

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2516]
**Describe what you would like changed, and why.**
Allow status effects to be defined in a separate folder for hjson mods to prevent this
![image](https://user-images.githubusercontent.com/48808663/120726758-e0333680-c4a6-11eb-908e-efc0a0b95d01.png)
**Describe the changes you want to propose. Include possible alternatives.**
Add a new folder in content for status effects and allow other classes to reference them

**Comment by genNAowl** [comment]
Quack?

**Comment by Kyllingene** [comment]
This title... is... odd.

**Comment by the-red-soul** [comment]
title is accurate as so many status effects get duplicated when used for multiple units with mods.

**Comment by Anuken** [comment]
7.0 should support this already, although I haven't tested.
