### ISSUE TITLE
Different death effects

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2517]
**Describe the content or mechanics you are proposing.**
Different death effects depending on what killed the unit. This makes it better looking and I hope it isnt too hard to implement.
(Some of these were probably suggested already, although a bit differently)
-Critical damage — this is the standard death effect. Unit's systems fail and it falls down or blows up. This happens if damage is taken via bullets or pulse lasers. 
-Cutting — if an energy beam deals more than 50% of the max HP and kills the unit, it gets split in pieces and falls down.
-Blasting — if hit by a blast weapon or a pulse bomb, like Quad's with less than 25% HP, and the blow kills it, unit falls apart and the pieces get knocked back in the way of the blast.
-Sinking — critically damaged ships sink.
-Evaporation — if hit by a massive burst beam, like Corvus's, and the beam deals 100% or more of HP of the given unit, it just evaporates. Tier 1 and 2 units should fall in this category.
-Melting — if killed by a high temperature weapon, or killed by a beam that deals under 50% of the unit's HP, it melts in a small puddle of slag and/or some parts explode.
-Ionisation — if killed by an EMP weapon or an electric arc, parts of the unit fall in rancom directions, dealing electric damage in the impact area.
-Slow falling — if a heavy air unit dies from a weaker weapon, it loses weapon and thruster power, slowly gliding down, and in n some direction until it hits terrain and explodes, or ground and breaks apart.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

Gives more variety to the death effects. Since v7 already adds many better effects, why not add this one? If some are hard to implement, or you dont like it, dont add.

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
This will take a lot of time to implement. And if you want  nice looking sinking effect u will have to make a heightmap for every units.

**Comment by EclipsePlays** [comment]
Sinking may be implemented just like how fortresses drown. 
Slow falling, ionization, melting, and cutting would take some time debug. 

Critical damage is implemented. 

Blasting animation already works on t4s and t5s on v7. 
Evaporation is yet to be implemented. 

This feature all relies on anuke btw, so stay tuned.

**Comment by BorisA11** [comment]
@EclipsePlays Critical damage is the death effect that is currently in-game, yes. Blasting looks more like a massive explosion, I meant a blast with actual unit parts, or something like that. And yes, some of them will take a long time to do, but hey, so we thought for v6 back in the day :D

**Comment by Kyllingene** [comment]
> And yes, some of them will take a long time to do, but hey, so we thought for v6 back in the day :D

The difference being that v6 added actual *content*.

**Comment by ShadeStrike62** [comment]
> > And yes, some of them will take a long time to do, but hey, so we thought for v6 back in the day :D
> 
> The difference being that v6 added actual _content_, not just visual fluff.

This is actual stuff, it effects zenith bombing and most attack map meta strats, as well as being a good idea

**Comment by Kyllingene** [comment]
> This is actual stuff, it effects zenith bombing and most attack map meta strats

What? All the suggestion is is more *visual* death effects. Where did you get *that* idea?

> as well as being a good idea

Prove it.

**Comment by genNAowl** [comment]
I'm sure most people get the point but,

This seems annoying to implement. 

With emphasis on annoying

**Comment by BorisA11** [comment]
@genNAowl some probably are. But if unit system goes under changes, maybe add space for custom death effects?

**Comment by numer99** [comment]
all of this seems good.
I like it.
