### ISSUE TITLE
Yet another Lancer nerf (Increase the delay of the shot but also increase damage)

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2518]
**Describe what you would like changed, and why.**
Lancers are super spammable because they only use energy to work, and their energy cost can simply be solved by putting batteries. Lancers can also be built very early in the game but can kill many, but many (ground) enemies, both in crowds and single targets.

**Describe the changes you want to propose. Include possible alternatives.**
Make Lancers deal more damage but increase the amount of time it takes to charge the shot. They'll still be good, but putting them slightly off the center of choke points will make them much less effective because they'll miss most of their shots, automatically making spamming less effective. This will also open use for other turrets like Salvos on the sides of a defense, since putting Lancers there will start not being too useful. Making a powerful turret but that can only be placed on a choke point will also be an interesting concept to have, which is actually already what Lancer tries to be but the charge time currently is too small for that.

**Comment by Noob17** [comment]
Cooling and overdrives exist, but considering those are usually commodities and not commonly used for most basic turrets, it sure would bring their use into light.

(For context, only certain late game turrets are actually used with coolant. Using coolants to offset the lancer's weakness could really bring the use of those coolants early game, as more of a risky move, and would allow the use of it more frequent.)

**Comment by Noob17** [comment]
> > Cooling and overdrives exist, but considering those are usually commodities and not commonly used for most basic turrets, it sure would bring their use into light.
> > (For context, only certain late game turrets are actually used with coolant. Using coolants to offset the lancer's weakness could really bring the use of those coolants early game, as more of a risky move, and would allow the use of it more frequently.)
> 
> Cooling only increases the firerate, but the amount of time the Lancer will still immobile while charging the shot is the same without or with coolant. Same for overdriving them, probably for balance.
> 
> My suggestion is to increase the time of charging of the shot, I just noticed the way I worded this was weird.

Makes sense, since cooling only resets the time between shots faster, and not the charge time. My original comment makes no sense in this context.

**Comment by D-player1** [comment]
Finally a suggestion about actually balancing it rather than a plain nerf

**Comment by OnyxFinger** [comment]
> My suggestion is to increase the time of charging of the shot, I just noticed the way I worded this was weird.

I guess this is a good idea.. I think lancers should definitely get nerfed anyway

**Comment by BorisA11** [comment]
I doubt lancers need anything major. They serve a purpose, anti-ground low tier killers.

**Comment by Noob17** [comment]
> I doubt lancers need anything major. They serve a purpose, anti-ground low tier killers.

Actually, I agree with you to an extent. They are balanced in this purpose, which is to destroy weaker units, but the issue is that since they overkill at their job, they also become excellent options for other situations where a different turret should've been used otherwise. 
Their overall 'op-ness' doesn't really correlate with their price, which leads to many players abusing the living hell out of it, especially in Free-For-All modes where building pushes are common.
In the campaign however, they are balanced for their use as many factors are generally considered in both survival and attack sectors, and many other turrets perform better than lancers in that aspect.
