### ISSUE TITLE
a few buffs to Payload Propulsion Towers

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2519]
(Yes, I know this is a WIP version of the game and the current values of the new blocks are probably not final, but I'll still suggest balances for V7 stuff, maybe for saving the cat's time, a little)

**Describe what you would like changed, and why.**
Prop Towers are just too bad right now. You spend 100 phase, 1200 energy and a lot of space just to send units (it can't even send all) 30 blocks away, this is just bad.

**Describe the changes you want to propose. Include possible alternatives.**
Make them cost only 300 energy, have longer range (something like 60 or 50 blocks), decrease phase cost to something like 30 and maybe also increase payload capacity to 4 blocks². An interesting change would also make it so a Prop Tower can still prepare it's shot even when the target Prop Tower is busy receiving a payload from another Prop Tower so launching multiple payloads to the same spot becomes more viable.

**Comment by OnyxFinger** [comment]
agreed. weak and pricy, the propulsion towers need a lot of tech and and are relatively pricy on these tech ressources, meaning they can only be chained late game, but they have very low range and can't transport big stuff.

**Comment by Anuken** [comment]
Even with buffs, most payload distribution systems aren't going to be useful until there's a good reason to move payloads around. There's little incentive to shoot units, as they can just be reconstructed on-site. Block-payload-based production and crafting hasn't been implemented yet.

**Comment by genNAowl** [comment]
> Block-payload-based crafting 

Hmm yes one container + two mechanical drills = a mono

**Comment by Humanoid-X** [comment]
Hmm thats good
smelt one container, some copper and two duos to get a dagger
smelt two scorch, some coal nd a container to get a mace
smet... hail? to get fortress
~ Wait thats not right monos use laser instead of drills ~

**Comment by OnyxFinger** [comment]
> Block-payload-based production and crafting

Well now we know payload transport will be useful at some point
But if the blocks are done like this

**Comment by genNAowl** [comment]
~~Well I kinda said it as a joke but it definently would be interesting to see other ways of creating certain blocks/units~~

**Comment by Humanoid-X** [comment]
implemented (if i dont suffer some memory loss or vision distorting illusion)

**Comment by SMOLKEYS** [comment]
unbelivable

this balancing/feedback request was already 23 days old

hmm

time flies, i guess
