### ISSUE TITLE
Add a noteblock like in minecraft 

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#2521]
**Describe the content or mechanics you are proposing.**
Basically a noteblock like in minecraft, it will only produce certain tones (with a decent range of tones), and will be activated by logic 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Well people can create music, it will allow music to logic games, maybe be used in logic for defensive purposes

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
I know it was removed from the template, but ***please*** check for duplicates before posting.

Either way though, you lied. The Trello clearly says "logic sound", which implies noteblocks. So, please close this, or [else.](https://github.com/Anuken/Mindustry/issues/3684#issuecomment-736539263)

**Comment by Phinner** [comment]
1. Duplicate of #810 #868 #1108 #1860 #2360
2. [Trello](https://trello.com/c/yij5RfGc)

Even if you checked the boxes, you did not checked Trello nor checked for duplicates.
Lying is bad...

**Comment by Kyllingene** [comment]
Just for fun, here is a partial list of duplicates:

#2501
#1108
#1505
#810
#429 (similar)

**Comment by Phinner** [comment]
"It's evolving, just backwards..."

**Comment by genNAowl** [comment]
Aren't duplicates allowed now?
https://github.com/Anuken/Mindustry-Suggestions/commit/b550bea89817abee7a062f0b73e2b33ad9ce05bd

**Comment by itcannotbe** [comment]
Doesn't change the fact that OP lied about actually checking the damn trello.

And the long list of duplicates this noteblock/soundblock/block that makes sound/logic sound has.

**Comment by itcannotbe** [comment]
Also "... Like in minecraft" suggestion should really stop.

Unless people want to redo the implementation of logic like redstone. Imagine that.

**Comment by IIINSTINCT** [comment]
Duplicate suggestions are allowed now but by seing those other same suggestions ideas this is not gonna happen close this issue

**Comment by vinhsad** [comment]
@RouterChainsSuckk this is already on the trello, did you even read it?

**Comment by Phinner** [comment]
@vinhsad  You should have remain silent, now we have to wait another 20 days... He clearly won't close his pull...

**Comment by itcannotbe** [comment]
^ What he said

Also this isn't a pull.

**Comment by Phinner** [comment]
> Also this isn't a pull.

¯\\_(ツ)\_/¯
