### ISSUE TITLE
duct bridge visualize inputs

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#2522]
**Describe what you would like changed, and why.**

Currently when you hover a duct bridge in range of 1-3 unlinked ones there is no line between them, only outward facing:

![Screen Shot 2021-06-06 at 21 43 48](https://user-images.githubusercontent.com/3179271/120937901-7c13ab00-c710-11eb-8284-eb940c5d1e76.png)

**Describe the changes you want to propose. Include possible alternatives.**

For the ducts that could/would connect if the duct were to be placed to also render a line with or without square 🤔

**Comment by numer99** [comment]
like the power lines in mindustry classic?

**Comment by Quezler** [comment]
no idea what that is, but on the screenshot you can see a dotted line that extends from the duct bridge, ideally it should also have one for each valid possible input

**Comment by Humanoid-X** [comment]
Dotted line show valid output points. 
~All you need to do is calculate lol~
I like this suggestion
