### ISSUE TITLE
Shield Health Bar on Controlled Unit

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry-Suggestions#2523]
**Describe the content or mechanics you are proposing.**
As the tittle says, would be good if, when you controlled a units that has a force shield, you could see him shield health with the health of the unit.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Well, it would be good if you are begin attacking and you would like to know how much health has your shield.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggestions".

**Comment by notMEEPoffaith** [comment]
YES PLEASE

**Comment by genNAowl** [comment]
Like a bar that appears under the unit or a bar that appears on the unit display on the bottom left?

**Comment by Kaviaki** [comment]
> Like a bar that appears under the unit or a bar that appears on the unit display on the bottom left?

Uhhh, I was thinking in a bar that could appear with the health bar, you know, when you are controlling a unit, there's a health bar, wich is good. But, if you are controlling a unit that has a force shield, would be good to see a Shield Health Bar beside the Player Health Bar (I play in mobile, so maybe

**Comment by OnyxFinger** [comment]
wait why was this closed ?
especially to re open it afterwards ?

good suggestion btw, it would be really cool not to need the unit information mod for this

**Comment by Kaviaki** [comment]
> wait why was this closed ?
> especially to re open it afterwards ?
> 
> good suggestion btw, it would be really cool not to need the unit information mod for this

Sorry, it was me, I misclicked the "comment" button

**Comment by OnyxFinger** [comment]
> > wait why was this closed ?
> > especially to re open it afterwards ?
> > good suggestion btw, it would be really cool not to need the unit information mod for this
> 
> Sorry, it was me, I misclicked the "comment" button

o

**Comment by SMOLKEYS** [comment]
> > > wait why was this closed ?
> > > especially to re open it afterwards ?
> > > good suggestion btw, it would be really cool not to need the unit information mod for this
> > 
> > Sorry, it was me, I misclicked the "comment" button
> 
> o

o?

o.

**Comment by Humanoid-X** [comment]
o? 
o. 
o!
o?
o!!
o?!?
o. o. o!

**Comment by SMOLKEYS** [comment]
Lmao, going back into topic, i like this idea.

**Comment by genNAowl** [comment]
> o.

...

Facts.

**Comment by OnyxFinger** [comment]
> o?
> o.
> o!
> o?
> o!!
> o?!?
> o. o. o!

stop
