### ISSUE TITLE
nerf mono1!1!!1!!

### ISSUE THREAD

**Issue by Hyrotrioskjan** [Anuken/Mindustry-Suggestions#2524]
**Describe what you would like changed, and why.**
mono has too much dps!!11!! pls nERf!11

here in this clear image we can see that a mono has defted a regn!1!
<img width="349" alt="mono" src="https://user-images.githubusercontent.com/84776228/120971526-ee2ed300-c796-11eb-95c6-2305fa6b4a57.png">
proof of low helth regign!1!!1
<img width="167" alt="reigndedd" src="https://user-images.githubusercontent.com/84776228/120971534-f129c380-c796-11eb-9bfc-ca22a29ede86.png">

plEAse nerf mono anuke its too op!11 1>:(((((((((((((((((((((((((((((((

**Describe the changes you want to propose. Include possible alternatives.**
nerf mono dps by 69420, it will maek it balanced111!1. becaus mono op1!!1 also deduce the helth by 34, pls anuke it op giVe it neRf1!!!!1!!

**Comment by IIINSTINCT** [comment]
I know you are trolling but stop it get some help it is not funny

**Comment by USMP-lancer** [comment]
ik you trolling but dont do this man, these suggestions are too bloated by garbage

**Comment by SheepCommander** [comment]
I know these are funny but close them gun🔫

**Comment by Humanoid-X** [comment]
Go away troll

**Comment by Humanoid-X** [comment]
Xcus me what exactly happen in june 7 why you all troll

**Comment by BorisA11** [comment]
Some people really like to get banned... *sigh*
