### ISSUE TITLE
"... like in minecraft"

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2525]
**Describe what you would like changed, and why.**
Make mindustry logic like minecraft redstone

**Describe the changes you want to propose. Include possible alternatives.**
Replace processors with multiple blocks/wires like in minecraft

**Comment by SheepCommander** [comment]
BTW Anuke can you add logicpacks? Based on the DataPacks from Minecraft that were added in 1.13 the aquatic update

**Comment by SheepCommander** [comment]
In Mindustry you have logic blocks

**Comment by SheepCommander** [comment]
In minecraft you have command blocks

**Comment by SheepCommander** [comment]
But command blocks cause lag so Mojang added DataPacks which are like Command Blocks but in text files and with more power

**Comment by USMP-lancer** [comment]
ew no, you want this kidna stuff look at mods, this simply dont belong in normal mindustry

**Comment by SheepCommander** [comment]
So maybe Mindustry can do something similar and make Logic Packs

**Comment by SheepCommander** [comment]
> ew no, you want this kidna stuff look at mods, this simply dont belong in normal mindustry

Why not? Minecfraft is a successful block game

**Comment by itcannotbe** [comment]
> > ew no, you want this kidna stuff look at mods, this simply dont belong in normal mindustry
> 
> Why not? Minecfraft is a successful block game

Simply put it,
mindustry != minecraft
It's a different game altogether.

**Comment by USMP-lancer** [comment]
there is no good reason for redstone like mechanics, you want them, commision a mod creator or something

**Comment by itcannotbe** [comment]
PS. This is a meme suggestion.
Kindly store your torches and pitch forks for another time.

**Comment by USMP-lancer** [comment]
oh ok lmao

**Comment by notMEEPoffaith** [comment]
no please

**Comment by Kryvytsky** [comment]
As far as I know. Anuke tried to make something like that, but then schemes become too big, so he choose more compact way and create a processor.
Also, why even Mindustry need redstone logic? Processor and displays is enough to manipulate game and create some mini games. Some guy even create a raycasting prototypе so in theory it's possible to make a 3D game on displays.

**Comment by abdallah362** [comment]
dude if you bad in logic why you want to destroy it?

**Comment by Kyllingene** [comment]
This is a satirical issue.

**Comment by itcannotbe** [comment]
> This is a satirical issue.

You're one smort boi

**Comment by USMP-lancer** [comment]
> > This is a satirical issue.
> 
> You're one smort boi

smarter then me lmao

**Comment by SheepCommander** [comment]
lesgo

**Comment by USMP-lancer** [comment]
a

**Comment by SheepCommander** [comment]
a

**Comment by USMP-lancer** [comment]
why the hell is this issue still alive, torch it

**Comment by Kyllingene** [comment]
i really hope this is a joke

> So maybe Mindustry can do something similar and make Logic Packs

because mods are basically logicpacks but more powerful (and use js instead of mlog)

**Comment by USMP-lancer** [comment]
stop talkin on this issue aeawwsdfxgfafsda

**Comment by abdallah362** [comment]
if you want something like Redstone there is something called mindustry logic logic

**Comment by SheepCommander** [comment]
okay but weadtaapackas??!?
