### ISSUE TITLE
Bridges storage balance

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry-Suggestions#2527]
**Describe what you would like changed, and why.**

Bridges having 34 storage instead of the 20 they should
Bridges endings

**Describe the changes you want to propose. Include possible alternatives.**

Bridge endings to be storageless, first to nerf their storage capacity, and secondly to allow multiple bridges to output in the same bridge ending without clog
Nerf (fix?) the bridge middle (whats neither the output nor the input) to have no storage instead of the 14 it has right now. If that creates instant transport issues, make it one or something, but 14 is too much

**Comment by MrDuck557** [comment]
why is the capacity important

**Comment by BlueWolf3682** [comment]
but why though

**Comment by hortiSquash** [comment]
Well, about storage itself, mostly because it is different that the description says about bridges. Change the description to be 10+14 if you want but i feel like they were intended to be 10.

And as for the ending, I would like to be able to have multiple bridges output into one (at the end) without it clogging because it is full of one ressource. This is pure QoL

**Comment by genNAowl** [comment]
Just use logic for multiple bridges outputing into one (Sirius has already been doing this since logic was released)

And storage of bridges is inconsequential, change it if you want, but I believe that a majority of the player base don't really care.

**Comment by OnyxFinger** [comment]
?

> Just use logic for multiple bridges outputing into one (Sirius has already been doing this since logic was released)

you don't need logic for that hum hum
bonk

**Comment by genNAowl** [comment]
Yes you do. Or else it will just clog. 

If you have two bridges going into one, and one is carrying coal, the other lead, what will happen if the coal bridge is connected first and the lead one later?

The end bridge will fill with coal, and using it as a lead output is rendered impossible

**Comment by hortiSquash** [comment]
Well you can do pretty much everything with logic, but thats not a reason

**Comment by oinkymoo** [comment]
if you have 2 bridge endings with different materials going into one bridge you're doing it wrong you don't mix lines unless they're going to your core

**Comment by hortiSquash** [comment]
> if you have 2 bridge endings with different materials going into one bridge you're doing it wrong you don't mix lines unless they're going to your core

Smallest schem wins, even sacrificing a block for antijam logic is often worth it
