### ISSUE TITLE
Add @buildX, @buildY and @buidling to Logic sensor

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2528]
**Describe the content or mechanics you are proposing.**
like the title , please add @buildX, @buildY and @buidling to Logic sensor command, also add another "@" to check what the unit is building
-make UnitControl: idle can still working when the unit is doing other command( like move x y, but not "stop")

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it will help in making logic builder supporter, also checking for player status

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SheepCommander** [comment]
~~Add Bob the Builder? 😳~~ makes sense

**Comment by oinkymoo** [comment]
idle specifically says that it makes the unit stop moving why would commands be an exception
