### ISSUE TITLE
Beacon

### ISSUE THREAD

**Issue by TacticalAlpha** [Anuken/Mindustry-Suggestions#253]
**Describe the content or mechanics you are proposing.**
A beacon, need large amount of surge and power to make, gives the ability for the player to call a backup, Friendly eradicator or more strong units. And takes up to 10-20mins for the backup to arrive. One usage only, if the backup unit died. You can request again.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
An cool idea, for an player to call a backup if he needs help.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by xiang2007** [comment]
WOW! this idea is cool
