### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by Delourians** [Anuken/Mindustry-Suggestions#2530]
**Describe the content or mechanics you are proposing.**

The player can see if he can build his schematics examplle its colored dark when its unable to build and light color if its able to build

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will make the use of schematics easier like I didnt need to check on info to see if I have enough resources or not 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
X

1. - [zx] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i think a much better way to do this would be to have x/y for each of the materials when looking at the info in the schematics menu

**Comment by Kaviaki** [comment]
This sounds very useful, especially when you're far away from your Core and want to put a schematic fast

**Comment by Hyrotrioskjan** [comment]
Isn't there already a way to check if you have enough items to build the schematics in the Schematics Menu?.
This wouldn't to much since it's basically already implented in the game.
<img width="960" alt="schematic" src="https://user-images.githubusercontent.com/84776228/121274123-023c1700-c8f4-11eb-8719-0359caf4ce64.png">

**Comment by simba-fs** [comment]
It looks useful

**Comment by Humanoid-X** [comment]
yes
e
s

**Comment by Ciliane** [comment]
I support this, but I think red blend would be better
