### ISSUE TITLE
Make T4 units go through payload conveyors

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry-Suggestions#2531]
**Describe what you would like changed, and why.**
Would be good to make the T4 units to go through payload conveyors cause, well, it is, just because.
(I know that they can't go through that because they're big, but, if the Scepter can, why not all the others T4 units? Also, the purpose of the payload conveyor is move units (and some blocks), so they can reach any reconstructor).

**Describe the changes you want to propose. Include possible alternatives.**

The change, is that. Alternatives?, Maybe, make the Scepter can't go through the payload anymore (pls don't do that).

**Comment by itcannotbe** [comment]
No.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/553#issuecomment-695827442

> > a higher tier payload conveyor for tier 4/5 units

> Yeah, no, I'm not adding 7x7 / 5x5 conveyors, that would be ridiculous. 3x3 conveyors are already pushing the limits as is.

**Comment by itcannotbe** [comment]
![just no](https://camo.githubusercontent.com/6fa4d5989147a9eafd83e74784e2f8f37354d4c8e76fe42ddeb1e19f775bdcd0/68747470733a2f2f646973636f72642d63646e2e69732d7465727269626c652e636f6d2f4e56507755752e706e67)

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/553#issuecomment-695827442

> > a higher tier payload conveyor for tier 4/5 units

> Yeah, no, I'm not adding 7x7 / 5x5 conveyors, that would be ridiculous. 3x3 conveyors are already pushing the limits as is.

**Comment by RedstonerKBC** [comment]
I think the reason why they aren't added is because then you could transport slot T4-5 units around very quickly

**Comment by OnyxFinger** [comment]
> I think the reason why they aren't added is because then you could transport slot T4-5 units around very quickly

the conveyors could just be made slow
it's not like if you needed a lot of throughput lol, they take 4 mins to build

also wth is this suggestion, normal payload conveyors are basically useless, why would you add more
close please.
