### ISSUE TITLE
A R C

### ISSUE THREAD

**Issue by mndstry-duo** [Anuken/Mindustry-Suggestions#2532]
Do I want to nerf the arc? Do I want to buff the arc? Come to github and read the rest to find out, people of discord. 

Today I want to compare the arc to the meltdown. 

**Let the Stat Rundown Begin:**

**Size**
First of all, an Arc is 1x1. A Meltdown is a 4x4. I will compare a 4x4 block of Arcs to 1 Meltdown

**Power Use**
Arc: 198 power/sec x 16 Arcs = 3168 power/sec
Meltdown: 1020 power/sec

Those Arcs do be eating power. 

**DPS**
Arc: 20 lightning damage x 1.71 shots/sec x 16 Arcs = 547.2 damage/sec
I think it would be fair to say a cryo-cooled meltdown is up ~1/2 of the time. 
Meltdown: 840 laser damage/sec x 0.5 shots/sec = 420 damage/sec

That DPS is higher than a meltdown yikes. 

**Pierce**
Both Meltdowns and Arcs are known to be great crowd control towers. I think it's relatively tied in this case. 

**Ammo Distribution**
Usually, smaller turrets are a lot worse than their bigger variants because it takes more space to distribute ammo. However, the fact that Arcs use *power* nullifies this argument entirely, as power is ridiculously easy to distribute. 

**Everything Else**
Let's say Range, Shot Type, etc. are balanced by the fact that Meltdowns require coolant and are ridiculously more expensive than Arcs. 

**The Point Is:**
For the ridiculous energy cost, Arcs can actually do more DPS than their more powerful variant. 

**Are Arcs balanced?**
Yes, I would say that Arcs are balanced. 

However this rundown shows that they use too much power and do too much damage. 

So I propose to **reduce both power cost and DPS**

*Numbers taken from bleeding-edge build 21211*

**Comment by BlueWolf3682** [comment]
~~buff meltdown~~

**Comment by SMOLKEYS** [comment]
> ~~buff meltdown~~

Complicated questions require simple answers.
- No one, probably.

**Comment by iLagSoUhax** [comment]
remove arcs :trollface:

**Comment by itcannotbe** [comment]
ARCS DON'T PIERCE -_-

**Comment by itcannotbe** [comment]
Also, meltdown damage is 840 per second or 70 * 60 / 5 damage per second.

**Comment by Humanoid-X** [comment]
arc dont pierce but it can shoot multiple things at once
~best solution being remove both arc and meltdown~

**Comment by itcannotbe** [comment]
> arc dont pierce but it can shoot multiple things at once
> ~best solution being remove both arc and meltdown~

The only thing that arcs can reliably shoot is the first thing it hits.
The rest is just RNG.

**Comment by stuffyAI** [comment]
You could use a better caption to convey your message right?

Anyway, meltdown has more range, which in defense (not tower defense) scenarios is plenty useful as they:

- shoot the enemy earlier
- can be placed behind other defenses, like another one, basically doubling dps
- cover a wider area to the sides, allowing singular heavy units to be target by more meltdowns/space than arcs/space

Additionally you have the bundled targeting; Meltdowns guarantee you that they constantly damage in their beam, arcs guarantee you damage against their initial target, everything else may just stray into walls.

Drawing balancing decisions based on a comparison of very much different towers doesn't seem conclusive to me, you didn't factor most important influences like acquisition time, match-up probability and niche, all of which are way more determining factors to consider an objects stats which has to align with plenty other such objects.

**Comment by MrDuck557** [comment]
Compare to lancer plz
lancer is also really powerful
and range

**Comment by USMP-lancer** [comment]
the reason arc was nerfed is because of the sheer amount of dps spamming arcs gave

**Comment by vinhsad** [comment]
nerf/buff target be like:
water ex
arc
lancer
meltdown
segment
pumps
u n i t s

**Comment by USMP-lancer** [comment]
i think meltdown needs a buff but thats probably it
