### ISSUE TITLE
Improve Unit Logic Controlling

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2533]
**Describe the content or mechanics you are proposing.**
Improve the Unit Controlling PathFinding, normaly the PathFind command will go to Enemy Core or Spawn Point, But if i used "Move" or "appoach" and use the PathFind command it won't go to the Point, so i want it to PathFind to the Move Point and not the Spawn
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Logik improve .-.
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
i think better use

pathfing xPos yPos radius

so less lines of code

**Comment by stuffyAI** [comment]
As mentioned above, this kind of path-finding is currently not supported.

As of right now, ground units may only find the best path to points declared on (usually) map generation, aka player cores.

It is possible to make low-tier obstacle pseudo-pathfinding to at least walk around small parts of walls without impacting the performance too much, but remember that we still attempt to preserve mobile-availability.

**Comment by OnyxFinger** [comment]
> Duplicate.
> 
> Also, you need to bruteforce every path on the map. Currently, enemy pathfinding only uses _one_ point to go to and still takes 1-5 seconds to update. Now imagine if you want to calculate _every_ path from _every_ point to _every_ point. If you're on the 250x250 map, it'll take >60 seconds to calculate it when you start the game

that's basically everything to say about it
You can just set your own path with guns pointing at different places btw

**Comment by oinkymoo** [comment]
> Duplicate.

duplicates are no longer prohibited

**Comment by stuffyAI** [comment]
> duplicates are no longer prohibited

The user should still reasonable deduce on why another suggestion with same intent failed, this here isn't different enough to be useful.

**Comment by oinkymoo** [comment]
> > duplicates are no longer prohibited
> 
> The user should still reasonable deduce on why another suggestion with same intent failed, this here isn't different enough to be useful.

they were under no obligation to know that the duplicate failed, let alone even existed
