### ISSUE TITLE
Crux building

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2535]
**Describe what you would like changed, and why.**
Currently, crux is using moderately outdated schems (like powercubes). Can more updated schems be made?

**Describe the changes you want to propose. Include possible alternatives.**
Same thing you did with Base Schematic Designer, except for v7

**Comment by Ineedause** [comment]
noice idea

**Comment by OnyxFinger** [comment]
Well I thought Anuke already knew this ?
anyway please yes.

**Comment by SheepCommander** [comment]
Crux?

**Comment by thedimas3007** [comment]
@SheepCommander 
Red team
