### ISSUE TITLE
Two-finger panning option for mobile

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2536]
**Describe the content or mechanics you are proposing.**
On mobile, I would like an option in the settings for panning to require a two-finger drag instead of a one-finger drag. This would also allow dragging a line of buildings without first having to hold.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, in order create a line of buildings, you have to hold down your finger before dragging. This can take a lot of time, especially when you need to do something like making a long line of conveyors. With the suggested option, it would allow the player to just drag in order to create a line of buildings, which would allow players to build more quickly.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
Hmm... interesting idea there.
