### ISSUE TITLE
Crawlers in survival

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2537]
**Describe what you would like changed, and why.**

Currently, crawlers created in survival situations will do nothing and just sit idly

**Describe the changes you want to propose. Include possible alternatives.**

Crawlers automatically pathfind to the enemy spawn, and move toward and explode against nearby enemies

**Comment by Noob17** [comment]
2 Questions: 

Is their path obstructed?

Is there a command center that asked units to stand still or gather around?

If you answered yes to these two questions, you may try to either add doors to walls, and change cc settings.

**Comment by OnyxFinger** [comment]
wat
they do work

**Comment by oinkymoo** [comment]
no command center, and daggers spawned in the same area do still pathfind

**Comment by darmaangelo** [comment]
> **Describe what you would like changed, and why.**
> 
> Currently, crawlers created in survival situations will do nothing and just sit idly
> 
> **Describe the changes you want to propose. Include possible alternatives.**
> 
> Crawlers automatically pathfind to the enemy spawn, and move toward and explode against nearby enemies

im so sorry i thing we can use logic to control crawler

**Comment by oinkymoo** [comment]
> > **Describe what you would like changed, and why.**
> > Currently, crawlers created in survival situations will do nothing and just sit idly
> > **Describe the changes you want to propose. Include possible alternatives.**
> > Crawlers automatically pathfind to the enemy spawn, and move toward and explode against nearby enemies
> 
> im so sorry i thing we can use logic to control crawler

yea we can but why should it be necessary when _every single other unit_ does not need logic to function in survival

**Comment by SaltyBeggarBR** [comment]
they have a very small radar, this is why they only explode on a unit if they're super near it

maybe their detection range should be increased instead

**Comment by oinkymoo** [comment]
> they have a very small radar, this is why they only explode on a unit if they're super near it
> 
> maybe their detection range should be increased instead

this would certainly help, but they don't even move from the factory that produced them, unlike all other units
