### ISSUE TITLE
Make a rebuild feature on players and not only on repair air units.

### ISSUE THREAD

**Issue by dyussss** [Anuken/Mindustry-Suggestions#2538]
**Describe the content or mechanics you are proposing.**
An auto-repair mechanic on players with a hotkey that will start to rebuild any blocks that are broken as its a pain in the ass to look at the transparent blocks and not have any air units. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will be much more easier to rebuild broken stuff like if a thorium reactor explodes and causes part of the map to go kaboom, players can press the hotkey to start rebuilding immediately, depending if the resources is available or not. Alternatively, it can be always on or always off, so if something is destroyed the player will immediately pathfind to the location and rebuild, then go back to its original spot.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LeoSko** [comment]
Could be an unlockable ability as well or an ability only for higher tier core ship (e.g. gamma only), but in general - yes, that would be great.

**Comment by dyussss** [comment]
> > Could be an unlockable ability as well or an ability only for higher tier core ship (e.g. gamma only), but in general - yes, that would be great.
> 
> I think this is a horrible idea
> The point of this would be to allow players to rebuild more easily, if is limited, then there isn't really a point, since you still need to change mechs etc..
> rebuilding by hand is still possible, which means this is only QoL, so it would be dumb to limit it. If it was a special capacity like rebuilding stuff for free, I would understand it, but I don't see how this would be better than having it pre-unlocked/not limited

Some clients already have this feature, like Foo's client made by foo and buthed. It's basically an AI that repairs stuff around the map for you that is super helpful and works on all units. Imagine building a schem with bridge conveyors everywhere, that would be a nightmare unless you have it.

**Comment by OnyxFinger** [comment]
>Some clients already have this feature, like Foo's client made by foo and buthed. It's basically an AI that repairs stuff around the >map for you that is super helpful and works on all units. Imagine building a schem with bridge conveyors everywhere, that would >be a nightmare unless you have it.

and it's a client...
so we still kinda need it, because everyone won't bother getting a client/has his own already, but without the auto rebuild

**Comment by RouterChainsSuckk** [comment]
> > Some clients already have this feature, like Foo's client made by foo and buthed. It's basically an AI that repairs stuff around the >map for you that is super helpful and works on all units. Imagine building a schem with bridge conveyors everywhere, that would >be a nightmare unless you have it.
> 
> and it's a client...
> so we still kinda need it, because everyone won't bother getting a client/has his own already, but without the auto rebuild

well then its their fault and they shouldn't complain

**Comment by numer99** [comment]
It's so annoying when you have to rebuild an ENTIRE thing from SCRATCH.
Yes. Make a rebuild feature on players and not only on repair air units.
Nobody can reject.

**Comment by darmaangelo** [comment]
> **Describe the content or mechanics you are proposing.**
> An auto-repair mechanic on players with a hotkey that will start to rebuild any blocks that are broken as its a pain in the ass to look at the transparent blocks and not have any air units.
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> It will be much more easier to rebuild broken stuff like if a thorium reactor explodes and causes part of the map to go kaboom, players can press the hotkey to start rebuilding immediately, depending if the resources is available or not. Alternatively, it can be always on or always off, so if something is destroyed the player will immediately pathfind to the location and rebuild, then go back to its original spot.
> 
> **Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 2. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> 3. * [x]  I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

horrible idea

instead of player i suggesting to make a building than can rebuild nearby so we can choose which part of the map we want to rebuild
