### ISSUE TITLE
Beacon (long range mender / unit booster)

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#254]
**Describe the content or mechanics you are proposing.**
The Beacon is a large and expensive building, which can be toggled between 3 modes. When in Mender mode, it mends buildings within a large radius and no limit as to how many blocks it can heal at a time. However, it is very slow (60+ seconds mend time). It can also be toggled into Mech Boost mode or Unit Boost mode. In Mech boost mode, all mechs receive a small (not more than +25%) boost to build speed, a small speed boost and very slow natural regeneration. In Unit Boost mode, all friendly units (not including mechs) are given a very slight damage boost (not more than 10%) and a slight movement boost. There could also be a natural regeneration, but I think that this would make heal point obsolete and that is not what I'm trying to do. There is a cooldown on changing the beacon mode to prevent what command centres are doing now on servers (spamming). A unit, mech or block can only be affected by ONE beacon at a time. To balance this, it should be a relatively expensive building, and have a high, variable power draw. It should have a base power draw (maybe 500ish power) and then draw more power depending per block it is healing at the same time (in mend mode), per mech are in range (mech mode), or per friendly unit in range (unit mode).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In mend mode: The Beacon repairs lots of blocks slowly, so after a breach you can easily prevent blocks from remaining damaged.
In mech mode: The Beacon will provide a little bit of extra power towards the end of the game, as currently once you have glaive, you can't get any better in terms of mechs. 
In unit mode: The Beacon provides a new way to improve defence: upgrading units (revenants, in most late-game games). It won't be a big boost, but should help to provide a bit more safety. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ILiekMelons** [comment]
I feel like this should instead be separated into 3 different blocks

**Comment by Catchears** [comment]
Hmm, also a nice idea.

**Comment by Catchears** [comment]
Closing because Anuke has probably seen it and decided not to implement it.
