### ISSUE TITLE
Small Feedback: Please provide a simple panel with the game messages / events

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2540]
**Describe what you would like changed, and why.**

While I get coffee, it often happens that Mindustry notifies me about some important event and I just hear the event notification sound. When I get back to the computer, I have no idea what happened.

**Describe the changes you want to propose. Include possible alternatives.**

It would be great if one could open a panel that displays those events.

**Comment by oinkymoo** [comment]
yes please. i want to be able to easily find where i am under attack also i can quickly check if i have been attacked
