### ISSUE TITLE
Small Feedback for the "Sector Lost" message: Please tell the sector name :-)

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2541]
**Describe what you would like changed, and why.**

Probably all Users have one question if they get this message:

![image](https://user-images.githubusercontent.com/8282673/121545951-3d7d3980-ca0b-11eb-901f-d9e34b91c1bc.png)

_"Which sector have I lost?"_

**Describe the changes you want to propose. Include possible alternatives.**

Please tell which Sector was lost :-)

**Comment by oinkymoo** [comment]
i would assume you know where you are when you lose a sector

**Comment by SMOLKEYS** [comment]
Uhh... doesn't the camera point to the sector you lost?

**Comment by schittli** [comment]
Because the enemy can attack all my sectors, isn't it possible that the user can lose any sector he owns?

**Comment by stuffyAI** [comment]
> Because the enemy can attack all my sectors, isn't it possible that the user can lose any sector he owns?

No. The enemy cannot attack all your sectors.

**Comment by oinkymoo** [comment]
the enemy can only attack sectors that are next to enemy bases

**Comment by Kyllingene** [comment]
Imagine naming your sector something like "Silicon, pyratite, phase fabric and surge alloy production" on mobile, then getting this popup.

**Comment by oinkymoo** [comment]
i'm pretty sure there's a character limit

**Comment by Kyllingene** [comment]
Yes, but what is the character limit?

**Comment by oinkymoo** [comment]
i made it to the p in phase which is the 20th character

**Comment by Kyllingene** [comment]
Mmm, it would seem I drastically overestimated the capacity. Either way, it could still be a potential issue, albeit an easily avoidable one (font size).
