### ISSUE TITLE
Unit Fueling Overhaul (please read fully)

### ISSUE THREAD

**Issue by ShadeStrike62** [Anuken/Mindustry-Suggestions#2542]
**Describe what you would like changed, and why.**

Please open this on github, and do me the courtesy of reading my suggestion before downvoting it into oblivion...
What I am suggesting gets added to Mindustry is a system where units require power to function. The system the is ALREADY IN PLACE (I know it exists) is clunky and unused, because it is rather limiting, and quite shallow. Instead of using a resupply point to refresh ammo/power, which is annoying, I propose that all units require ONLY power to function, at least initially, but can draw it directly from the grid. This is how it would work:

-A unit can store a certain amount of power in its battery. This amount is based on its tier. Tier one units may only be able to go 20 second or so without power, but T5's could go for several minutes.

-Whenever a unit is within a reasonable distance of a power node that has power, its uses it to recharge, consuming power from the grid. The higher Tier the unit is, the longer it takes to recharge, as it can store more power, but it will charge at a faster rate to compensate (This means it will use more energy at a time while charging).

-A unit has a full battery when created, and consumes far less power to stay on full battery, so units that are rather passive (Standing around in your base, mining nearby ores) will use less power than roaming units that need a refill.

-If a unit runs out of power, it doesn't die, it just functionally shuts down, remaining in place. The unit can be turned back on if power is brought near it via a node/battery ect. However, flying units will crash if they run out of power. (Edit) Units that run out of power can still move, but very slowly (33% maybe), and can't shoot. In addition, when a new unit is created, it will kill a unit of its type with no power if the unit cap is reached.

-(Edit) A setting in custom games should be added called 'Unit Power Consumption', which would modify how much power a unit uses, similar to build speed of unit construction speed.

Additionally, some changes to existing units can be put into place to help balance this change to unit functionallity.

-The Naval Support Tree will gain a new passive, recharging. They can store extra power, and distribute it to naval units nearby as if they were a battery. Additionally, the Navanax can lower a units battery levels with its EMP attack (Potentially crippling T1 units, draining higher tiers, and tickling T4-5's). A support unit will share its power by default with units nearby, and will prioritize units being commanded by it (Mixed Tree formations!)

-The Minke, in addition to its buff to other stats, can reduce power usage of nearby boats.

-The Oct can storage extra power and distribute it like the Naval Support Line, providing a needed boost to the Octs functionality (especially in campaign).

The Benefits to this system:
-Using units to mine resources is no longer free, a good nerf, even if it is cheap...
-Only higher Tier units can 'roam' effectively, as lower tier ones will need a refuel more often
-Cheesing attack maps via outranging defenses or sneaking around the sides of the map no longer works so well, as the refuel adds a soft time limit to how long a unit can spend doing this tactic.
-It adds depth to unit strategy and PvP, and supports making a mixed fleet of boats/fliers to go further.
-It adds support for a more interesting RTS style PvP game, in conjunction with Fog of War. This will make PvP significantly more interesting. (Another small change to go with this is making logic only detect blocks that are visible while Fog of War is active, so units can't just home in on a core).

Downsides to this system:
-It is a lot more complex than what is currently in place, although I would say it is fairly reasonable in complexity.
-It will be a meta change, which will affect many peoples playstyle, which might cause some outcry. (No YoU CaNt MaKe WaTeR ExTrAcToR CoSt MeTaGlAsS!!)
-It makes power more important, so a small buff to power generators might be required.

If you have made it this far, thanks for reading, and I hope you can understand my thought train behind this. I honestly think this is good for the game, so if you hate it PLEASE SAY WHY, as this is a suggestion not a final copy of what will be added to the game, so it can be improved. Thank you for attending my T.E.D Talk!

**Comment by HaphLife** [comment]
I like it! I think that some of the higher teir units should maybe use more expensive fuel than just electricity, but overall a good idea.

**Comment by RouterChainsSuckk** [comment]
maybe increase time, like a minute or more for t1 and 10+ for t5

**Comment by ShadeStrike62** [comment]
> maybe increase time, like a minute or more for t1 and 10+ for t5

I think a slider should be added to custom games, like a 'Power Consumption' modifier

**Comment by Ineedause** [comment]
I think the one thing you forgot to add is that support units, monos, polys, etc... should automatically seek out and recharge themselves

**Comment by Element-29** [comment]
Great Idea, this is a simple change that will add many layers of depth to PvP. 
A few notes:
20 seconds for a T1 is probably to short for them to be effective in most cases.
Units just stopping could be an issue, for example a boat far enough out to sea that you can not get power to it but it still counts towards your unit cap. 

One way to address these issues would be to make it so that a unit dose not need power to move, just to shoot. This would allow T1 units to still be effective on large maps, and keep units from getting stranded in inaccessible locations.

The way units path find will need to be looked at, perhaps change default mode from attacking to idling.

**Comment by Ineedause** [comment]
I agree with element-29, but I think if this is the case maybe shooting should not completely shut down. Maybe it just slows down by 80% or something. For energy based units like quasar and pulsar I think them completely not being able to fire is a reasonable thing. Movement speed should be impaired but not fully shut down, like they move at 75% speed. What I am getting at is something in the lines of passive regeneration of the battery, via wind turbine or solar panel. While idle the battery gets charged, while the internal power grid is being overloaded it takes from the battery, like a normal power grid, and when it is overloaded and the battery is out functions shut off or slow down, again, like a normal power grid

**Comment by ShadeStrike62** [comment]
> Great Idea, this is a simple change that will add many layers of depth to PvP.
> A few notes:
> 20 seconds for a T1 is probably to short for them to be effective in most cases.
> Units just stopping could be an issue, for example a boat far enough out to sea that you can not get power to it but it still counts towards your unit cap.
> 
> One way to address these issues would be to make it so that a unit dose not need power to move, just to shoot. This would allow T1 units to still be effective on large maps, and keep units from getting stranded in inaccessible locations.
> 
> The way units path find will need to be looked at, perhaps change default mode from attacking to idling.
Only using power to shoot defeats the idea, but I agree about the Unit cap problem. Maybe you can have the option to kill a unit that is out of charge while controlling it or something, but remember that support naval exists so you could always make one of them. I might add the power sharing things to mega's to compensate for non naval units having this issue.

**Comment by ShadeStrike62** [comment]
> I agree with element-29, but I think if this is the case maybe shooting should not completely shut down. Maybe it just slows down by 80% or something. For energy based units like quasar and pulsar I think them completely not being able to fire is a reasonable thing. Movement speed should be impaired but not fully shut down, like they move at 75% speed. What I am getting at is something in the lines of passive regeneration of the battery, via wind turbine or solar panel. While idle the battery gets charged, while the internal power grid is being overloaded it takes from the battery, like a normal power grid, and when it is overloaded and the battery is out functions shut off or slow down, again, like a normal power grid

I like this solution, though again, I would add that the units still shooting sort of goes against the idea...

**Comment by Element-29** [comment]
Combining a few ideas here, Units could have 2 phases to their power, while above half(or so) power, they work at 100%. As power drops below 50%, they slow down, can't use their specials(force fields and such) and shoot slower. As power gets lower and lower these effects get more and more crippling, then at 0% power, the units would shutdown and die.
Perhaps only energy based units should shoot slower, with others only moving slower.
Air units might need to stay above 20% power or so to keep from grounding.
Units may have different power/second needs depending on what they are doing. 
Example, ground units use power 50% faster when moving, Air units use power 50% faster all the time(to stay in the air), and navel units do not need extra power when moving.

**Comment by oinkymoo** [comment]
might i suggest that the batteries on units function like regular batteries? if you are producing 1000 extra power/sec, all units on the network share the 1000 power, so if units consume, say, 60 power/sec on the move, then a single dagger would fill up in a little over a second. if you drain a full command group of daggers at once, it'll take just under 11 for all 9 of them to be refilled. if instead you have 10k power, the full squad can be back up in just over a second.

**Comment by itcannotbe** [comment]
My gripes with this suggestion is the amount of micro management this means to the player.

**Comment by ShadeStrike62** [comment]
> My gripe with this suggestion is the amount of micro management this means for the player.
> 
> PvP is already messy as it is. If you want to add another aspect to the game you might look into other things aside from units.

I agree, but my idea was that Mindustry PvP should be streamlined towards an RTS style game, as that would be fun, relatively easy to make with the current features such as fog of war, and less of a mess than what the multiplayer is like now.

**Comment by RzBuddy** [comment]
i like the idea! what if t4/t5 units also come with a built in reactor (uses coal/pyratite/blast/thorium)  and can produce energy on the go (provided that they have combustible material stored in some sort of secondary inventory)

**Comment by OnyxFinger** [comment]
I pretty much have no opinion on wether or not this should be a thing.
it would make sense, but be hard to play on. maybe as a survival feature. Also many people seem to like the idea or turning ammo on in pvp maps (spoiler alert : why would you do that ?), so I guess they wouldn't mind ???

**Comment by MrDuck557** [comment]
Just curious
are you aware that "units require ammo" is a setting?

**Comment by OnyxFinger** [comment]
> Just curious
> are you aware that "units require ammo" is a setting?

and fueling isn't ?

**Comment by OnyxFinger** [comment]
> -It makes power more important, so a small buff to power generators might be required.

I didn't see that. power is quite important already

**Comment by oinkymoo** [comment]
> Just curious
> are you aware that "units require ammo" is a setting?

aren't there plans for it to become non-optional in v7?

**Comment by OnyxFinger** [comment]
> > Just curious
> > are you aware that "units require ammo" is a setting?
> 
> aren't there plans for it to become non-optional in v7?

nope

**Comment by oinkymoo** [comment]
yeah my brain probably made that up then

**Comment by Element-29** [comment]
> My gripe with this suggestion is the amount of micro management this means for the player.
> 
> PvP is already messy as it is. If you want to add another aspect to the game you might look into other things aside from units.

My understanding is that this would make attacking harder/require more micro, and defending easier. Overall it should lead to less micro as it is harder for your opponents to send a small force to light your coal on fire(and we all know what a mess that becomes), so you have to spend less time in damage control. 

This is a good thing in my mind, as in my experience right now, It is far easier to attack then defend simply because you can decide to attack where ever defenses are not built, and there are a lot of locations that need to be defended. Requiring a little more planning for attacking will slow the pace of the game a little, and hopefully give t4/5 units a chance to show there worth.

**Comment by genNAowl** [comment]
Is Fog Of War implemented in v7.0? As far as I know it was removed in 3.5 and never made a reappearance ever since.

**Comment by ShadeStrike62** [comment]
> Just curious
> are you aware that "units require ammo" is a setting?

yes, but this is different, and that feature doesn't work well and no one uses it

**Comment by ShadeStrike62** [comment]
> Is Fog Of War implemented in v7.0? As far as I know it was removed in 3.5 and never made a reappearance ever since.

You can do it through the lighting settings, and if you turn of enemy lights you get fog of war

**Comment by itcannotbe** [comment]
> > Is Fog Of War implemented in v7.0? As far as I know it was removed in 3.5 and never made a reappearance ever since.
> 
> You can do it through the lighting settings, and if you turn of enemy lights you get fog of war

The minimap disagrees

**Comment by itcannotbe** [comment]
> > Just curious
> > are you aware that "units require ammo" is a setting?
> 
> yes, but this is different, and that feature doesn't work well and no one uses it

It works well TBH, the only reason why many doesn't use it, it the added management that it brings and the number of logic schematics that exist for that game play. Which is basically from minimal to none.

**Comment by EclipsePlays** [comment]
I do like the fog of war and things, but this suggestion, I don't know what to react because 
Power would be much of a problem (considering that a borderline power is super vulnerable to attacks and
If you are not near to a power node, and your unit moves like a turtle, there's a certain chance it won't reach the core. 
Air-logic spam units will be more often bcuz they will be the meta, faster units = more property damage. 

But yeah I agree with the defending terms, its taking so hard and so long to build turrets, your units could be used as a temporary defense arsenal. 
I like the use of the support units as an additional purpose to the game, 

But this issue is unclear if it will be implemented, the mechanics drastically changes the units and PvP, in general.
