### ISSUE TITLE
Adjustments & Passive Target Settings

### ISSUE THREAD

**Issue by ItsBUESCTime** [Anuken/Mindustry-Suggestions#2543]
**Describe the content or mechanics you are proposing.**
There will be new feature called "Adjustment" Button are available on custom map menu

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This feature can manage whether the Turrets (& Blocks) and Units for their health, damage point, and passive target. It can be also for core (Health only)
For example, Using mecha on enemy spawn point and targeting core during turret defend the core may follow the path onto core without damaging any turrets. Turret hits 1 damage to mecha but mecha had 10 health. Just like Tower Defense Version.
Otherwise, you can manage what your turrets can target 2 type of units. Example: Fuse can target ground but not included fly units can target.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
template please. everything you put into "describe how your content will improve the game" belongs in "describe the content or mechanics you are proposing" also ignoring the checkboxes will just get people, and especially anuke, to ignore your suggestion.

**Comment by oinkymoo** [comment]
> There will be new feature called "Adjustment" Button are available on custom map menu

where, it's a large area

> This feature can manage whether the Turrets (& Blocks) and Units for their health, damage point, and passive target. It can be also for core (Health only)

being able to control health of things seems useful. by passive target do you mean targeting priority? this can be done with logic, but if you want it to apply to player buildings too then i suppose it could be useful. 0 clue what damage point means though.

> For example, Using mecha on enemy spawn point and targeting core during turret defend the core may follow the path onto core without damaging any turrets.

turrets always defend the core, what are you suggesting this would do? not defend? how would that be useful?

> Turret hits 1 damage to mecha but mecha had 10 health.

what do you mean by "mecha" and why does it have 10 health. the entity with the least health in the game is the junction, with 30. all units, with 1 exception (the flare, with 75), have 100+ health. also no turrets do 1 damage. there is 1 that does .2 and is nearly impossible to get hit exactly 5 times by. 

> Just like Tower Defense Version.

wdym by tower defense version? the game is a tower defense and factory-building game. at no point did it stop being a tower defense game. this makes no sense

> Otherwise, you can manage what your turrets can target 2 type of units. Example: Fuse can target ground but not included fly units can target.

this is right on the border between understandable english and word salad. I would not have been able to figure out what the first sentence is even saying without the example.

**Comment by ItsBUESCTime** [comment]
That is the example one. You better get that lol

**Comment by oinkymoo** [comment]
the example what?

**Comment by ItsBUESCTime** [comment]
Wdym you talking about, I'm suggesting some features

**Comment by Kyllingene** [comment]
> Wdym you're talking about, I'm suggesting some features

1. Gotta love "What do you mean you're talking about"

2. Yes, you are suggesting features. The problem is that you never say why they could be helpful, or why they fit into the game. From what little I could gather, they seem overly nitpicky and probably wouldn't fit.

**Comment by ItsBUESCTime** [comment]
Feel bad to my suggestion... sorry
