### ISSUE TITLE
3 x 1 Payload Conveyer

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2544]
**Describe the content or mechanics you are proposing.**
I am proposing a 3 x 1 payload conveyer for precision placing of payload conveyers

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This simple addition is nothing more than a quality of life addition. More often then not people are suck not being able to place payload conveyers because they need a 3 x 3 block in a 2 x 3 space, a simple 3 x 1 payload conveyer would allow for less headache when placing payload conveyers. 

Also, the descriptions of blocks contain their size like 1 x 1 or 2 x 2, but we still don't have something that is lop-sided in size.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
This thing will get downvoted to oblivion

**Comment by SMOLKEYS** [comment]
How do you not know that 3 x 1 blocks (or any of the sorts) are impossible?

**Comment by itcannotbe** [comment]
Blocks are square not rectangular.

**Comment by Ineedause** [comment]
Soooo, I prepose a rectangle conveyer

**Comment by OnyxFinger** [comment]
> How do you not know that 3 x 1 blocks (or any of the sorts) are impossible?

isn't it..; possible-able ?

> Blocks are square not rectangular.

~~ty Mr smort.~~
this idea would need rectangle block support to be implemented, but I think it is good. payload conveyors a pain, and this would make the much easier to use, simply when connecting two lines (in case you made boats and want to drop them off somewhere, I do that sometimes for safety or my factories, since they're not that cheap)

**Comment by genNAowl** [comment]
Geez the effort and time needed to implement this would far overrule the benefits this would have.

**Comment by notrealn** [comment]
arent payload conveyors supposed to be clunky and hard to use
