### ISSUE TITLE
Allied teams as a gamerule

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2545]
**Describe the content or mechanics you are proposing.**
Allied teams - in game rules, you would be able to make groups of allied teams. Those teams wouldn't be able to hurt each other and their core no build radiuses wouldn't apply to each other. Otherwise, all restrictions that are imposed on different teams apply - no controlling units of another team, no tampering with blocks, etc.
There can possibly also be a way to make players on a survival map be able to spawn not just on sharded, but on a selection of teams?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would be very useful for custom gamemodes and otherwise useful for some interesting map concepts.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
Cursed and amazing.

**Comment by oinkymoo** [comment]
i feel like this would be really good for smaller multiplayer pvp/attack servers for preventing logic from stealing units that other players are using

**Comment by EclipsePlays** [comment]
I do like the gamerule, it helps the maps have variations of gameplay. But one problem is, the building and deconstructing feature.  People will go race the ores bcuz when you build it, the allied team can't remove it, which makes a spite of conflict between these two teams.

**Comment by itcannotbe** [comment]
> I do like the gamerule, it helps the maps have variations of gameplay. But one problem is, the building and deconstructing feature. People will go race the ores bcuz when you build it, the allied team can't remove it, which makes a spite of conflict between these two teams.

That's not even a game problem. PvP Coop always have that problem. It's an added complexity of the game mode itself and can be resolved by proper communication and proper map making.

**Comment by OnyxFinger** [comment]
I wonder how in hell itcannotbe thinks  this game is complex ?
Anyway I like this idea, currently teamates can kinda just eat every ressource and not allow actual developppement, alliances would fix this issue, since both aren't on the same team so don't use the same space / ressources

**Comment by oinkymoo** [comment]
they aren't stealing resources, but they are stealing space with this suggestion. as eclipse pointed out

**Comment by itcannotbe** [comment]
> I wonder how in hell itcannotbe thinks this game is complex ?

Because a lot of interactions between players will be different.

For example:
Strategy and Coordination with regards to attack and defense, sharing of resources (since resource pools are separate).

And the minor details that comes with what is said above.

**Comment by itcannotbe** [comment]
> I wonder how in hell itcannotbe thinks this game is complex ?

So the game is simple then?

**Comment by OnyxFinger** [comment]
> they aren't stealing resources, but they are stealing space with this suggestion. as eclipse pointed out

but space is nearly illimited in some places ~~and you can also be space efficient in your map~~
also the super late reply goes brr
