### ISSUE TITLE
Processors need coolant

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2546]
**Describe what you would like changed, and why.**
Add consumption to processors. Currently, logic processors are far too cheap for their utility. As soon as you get silicon, you can probably put down a micro processor without any inputs, just a lot of functionality. (Partial duplicate of #1065, but the problem is far more serious now)
**Describe the changes you want to propose. Include possible alternatives.**
Make micro processor consume power and optional coolant. No coolant would make the processor weaker than now, while water would be the same and cryo would be better. Make logic processor consume at least water coolant and power, but don't nerf speed. And make hyper consume power as well as cryo. 
While you can nerf the processing speed directly, this is probably the best way to nerf logic while keeping it useable.

**Comment by EclipsePlays** [comment]
Good nerf, now logic will die if there's negative power supply, which makes it a mini switch mechanic. 
But what could be annoying is if you connect it to a power node, the procs will be blocked with power lines. 
Extra suggestion: make the logic processors conduct electricity onto its adjacent tiles, same on what happens with power nodes directly beside a factory.

**Comment by oinkymoo** [comment]
> make the logic processors conduct electricity onto its adjacent tiles, same on what happens with power nodes directly beside a factory.

how power conduction works is through: node/tower connections, a shared edge between a power tab block and a power user, a shared edge between 2 blocks in the power tab. are you suggesting that processors join the power tab blocks in being able to transfer power to a consumer that it touches?

**Comment by EclipsePlays** [comment]
> how power conduction works is through: node/tower connections, a shared edge between a power tab block and a power user, a shared edge between 2 blocks in the power tab. are you suggesting that processors join the power tab blocks in being able to transfer power to a consumer that it touches?
>
Yes

**Comment by itcannotbe** [comment]
> Extra suggestion: make the logic processors conduct electricity onto its adjacent tiles, same on what happens with power nodes directly beside a factory.
That's just a coincidence. The behavior isn't written in the code just for this.

Power nodes do not carry power, they just link producers and consumers. Power magically used by a consumer nothing actually transfer power.
Side note: battery power is a different thing altogether.

**Comment by itcannotbe** [comment]
Also processor speed? You mean how many instructions can it run per second?

I think you don't know some logic is dependent on the fact that processor speed is a constant. And they just spam no op instrictions to make a block run in direct proportion to game ticks.

**Comment by itcannotbe** [comment]
Why not just make an block that is both expensive to run and to make that would essentially cap simultaneous logic instructions per second.

Since nerfing individual processors doesn't do anything meaningfully

**Comment by OnyxFinger** [comment]
generally, cooling is easy enough to get that it doesn't really matter, except early on.
I thought it was made clear in #balancing that adding cooling requirements for everything that can ever be an issue is dumb when talking about ABs.

**Comment by oinkymoo** [comment]
> Also processor speed? You mean how many instructions can it run per second?
> 
> I think you don't know some logic is dependent on the fact that processor speed is a constant. And they just spam no op instrictions to make a block run in direct proportion to game ticks.

ok? code can be rewritten to function at different processor speeds
