### ISSUE TITLE
Cultivator Buff v2

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2547]
**Describe what you would like changed, and why.**
Improve the cultivator's water and power consumption. 

Let the data show what's happening with the spores.

The current consumption of cultivators in v6 [(n)/spore pod] was stated below: 
-Water: 28/pod
-Power: 126/pod

But now, with it's current state on v7 BE, 

-Water: 33.3/pod
-Power: 133.3/pod

I am proposing the past version of my alt (#2248, PickAPlayerNameFirst), but with tweaked features. 
Now the cultivators will consume 24 water/s and will use 90 power/s, while making the processing time to 1.33/s.

With that being said, the data will change to:

-Water: 32/pod
-Power: 120/pod

Additional Data: I know if we do drastic buffs to the cultivator, the **powercubes** will resurrect. So I prepared an extra data if powercubes will resurrect. 

Only Land: 
-Current v7: ~ -70 power/s
-Proposed : ~ -54 power/s

WaterCube: 
-Current v7: ~432 power/s
-Proposed: ~486 power/s

Advantages: 
1. The proposed change will now fully use 4 watexes that's connected to it. 
2. Cultivator-blast mixer ratio will now be set to 1:1. 
3. Still maintains the powercubes from resurrecting from the dead
4. Oil Press to Cultivators will now be 4:1 instead of the ugly 5:1 ratio

And yes, this was suggested before, I was thinking of a PR but discord mods said that balance PRs are not accepted.
~~sad~~

**Comment by Humanoid-X** [comment]
~why would u use an alt~
~that will just waste github server data~

this is good, as long as you dont resurrect power cubes

**Comment by EclipsePlays** [comment]
> ~why would u use an alt~
> ~that will just waste github server data~
> 
My old account was linjed to my old email and a forgotten password 

I have no ways to recover it since the Forgot Password isn't working that well. 

~sad x2~
