### ISSUE TITLE
Better Boosting

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2548]
**Describe the content or mechanics you are proposing.**
1x1 turret use up to 12 liquid/sec, maybe that too many
so i want to make 1x1 turret consume less water/cryo (make it use 6 liquid/sec)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
save some resource and space
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
no, just imagine, you need 2 pumps and 1 cryofluid mixer to double the turret's attack speed. 

Cyclone need 200 copper, 125 titanium, and 80 plastanium to build, but 2 pumps and 1 cryofluid mixer only costs 30 copper, 30 metaglass, 65 lead, 60 titanium, and 60 silicon. It's literally obvious that boosting is cheaper

**Comment by D-player1** [comment]
but why do you need to boost 1x1 turret? By the time you can boost them you can already have better turrets.

**Comment by itcannotbe** [comment]
How on earth is this even a feature request?

**Comment by Humanoid-X** [comment]
lol, wrong label

**Comment by Kryvytsky** [comment]
Only 1x1 turret I ever boost was scorch.
