### ISSUE TITLE
Logic improve

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2549]
**Describe the content or mechanics you are proposing.**
Logic draw command: 
1.add status effect image @ (ex.@burning)
2.seperate turret image into @turret and @turret-base (ex.@duo and @duo-base)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it can be used to displaying more & better things
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
1. yes
2. no, all bases are actually just 4 sprites of 1*1, 2*2, 3*3 and 4*4 bases

**Comment by Kyllingene** [comment]
> 1. yes
> 2. no, all bases are actually just 4 sprites of 1_1, 2_2, 3_3 and 4_4 bases

~get gud~ use backslashes

**Comment by Humanoid-X** [comment]
AaaaAaAAAAAAaaAaaaaaaaAaaaaaAaAAAaaAaaaaAaAaaa I forgot it
