### ISSUE TITLE
Additional collateral damage

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#255]
**Describe the content or mechanics you are proposing.**
Dying units, especially flyers, should deal damage to things nearby.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently units just going *pop* when they explode feels a bit off. The explosions should be there for a reason.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Implemented.
