### ISSUE TITLE
Transparency KeyPress for Flying Things.

### ISSUE THREAD

**Issue by GitBobCat** [Anuken/Mindustry-Suggestions#2550]
**Describe the content or mechanics you are proposing.**

Transparency keypress for flying things.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Flying things tend to accumulate over ground things especially ground defence around the launch point during attacks. If you want to repair/upgrade the ground things especially after the attack/event then you can't see them unless you move the flying things out of the way which is a bit of a pain.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
what do you mean by transparent keypress

**Comment by GitBobCat** [comment]
A key on your keyboard that you press that makes flying things transparent so you can see what is underneath them. I am hoping it would be as simple as setting the transparency bit on the code that renders the graphics for a particular object to true.

**Comment by oinkymoo** [comment]
use more specific language. "things" is incredibly vague. they are called units.

**Comment by GitBobCat** [comment]
Sorry. If it's that precious to you then don't bother. I'll CTRL right click then G and move the 168 Flying things out of the way by hand in groups of 5.

**Comment by EclipsePlays** [comment]
It's even harder if those are  logic controlled megas plumbing the core.

**Comment by oinkymoo** [comment]
> Sorry. If it's that precious to you then don't bother. I'll CTRL right click then G and move the 168 Flying things out of the way by hand in groups of 5.

i'm not asking that they be called units. "mechs" or anything else that makes it clear what things you're talking about is all i want, because things is unclear. i do still support this suggestion tho

**Comment by GitBobCat** [comment]
Apologies for being precious myself, mid message I got attacked. I did figure out a workaround. If you set your command  centres to rally then your 168 Flying Units congregate above them thus moving them away from the defences around the launch point so you can tidy/strengthen things up. Then when the next attack begins you just set your command centres back to  attack. Just in case you forgot where you placed your command centres they will easy to locate as they will be inaccessible underneath multiple Flying Units. I suppose that having thought that one through I should also point out/request that as well as making the Flying Units transparent the function should also give you access/control to the underlying Units.

**Comment by oinkymoo** [comment]
also, while flares can only command 4 others and horizons 5, most other flying units can command a full 8 units, except for oct which for some reason can only command 6.

**Comment by sk7725** [comment]
Transparency for (flying) units have been suggested and denied before.

**Comment by sk7725** [comment]
Similar:
#873 Option to make friendly units transparent
#1376 (Closed) Unit transparency toggle, to see buildings/terrain underneath units
#1762 (Closed) Unit Visibility Toggle and Hotkey

Slightly similar:
#1596 Transparent Circle around players when they're building
#1370 Make air units move back when player approaches them
#108 (Closed) Unit Transparency
#1496 (Closed) Make mining units (or any units) mining and in range of the core opaque
