### ISSUE TITLE
explosionDamageMultiplier as a gamerule

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2551]
**Describe the content or mechanics you are proposing.**
An explosionDamageMultiplier which does what it says - multiplies damage from item explosions and air unit fall damage.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Will allow PvP maps and survival maps to use different explosion damage values, so survival maps can offer blast bombing as a tactic while PvP maps leave blast bombing unable to take down cores, but able to deal at least some damage.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by USMP-lancer** [comment]
agreed, blast bombing is annoying when its not pvp

**Comment by Humanoid-X** [comment]
yes
