### ISSUE TITLE
Crawler Buff

### ISSUE THREAD

**Issue by SimplyTav** [Anuken/Mindustry-Suggestions#2554]
**Describe the content or mechanics you are proposing.**

Giving a buff to crawler, by changing the explosion color to purple and making it inflict sapping to units damaged by the blast
but also probably changing the coal cost to spores since nobody really uses those anymore.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Since v6 added more cost to crawler, i don't think better AI and better explosion was enough so buffing crawler could be a smart move as its currently almost pretty much the most underused unit in the game, and nobody cares about it other than for upgrading it to spricot and above

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
Whilst I agree with the crawler being a plain useless unit that only gets abused as logic placeholder, why make it cost spore?

**Comment by oinkymoo** [comment]
this is balancing/feedback but ok

**Comment by Kyllingene** [comment]
What use would crawlers, a *self-destructive unit*, have for sapping?

**Comment by Noob17** [comment]
> What use would crawlers, a _self-destructive unit_, have for sapping?

Something tells me this guy meant that only the slow-down part of the sapped debuff should be included in the explosion. Very strange mechanic however.

**Comment by Kyllingene** [comment]
> only the slow-down part of the sapped debuff

But crawlers are nearly useless in unit-vs-unit combat, and still would be, rendering the slow debuff useless (you can't slow blocks).

**Comment by itcannotbe** [comment]
Um. If you actually want better balance, make short range units actually viable in the first place.

**Comment by oinkymoo** [comment]
^
yes this
