### ISSUE TITLE
Atrax rework

### ISSUE THREAD

**Issue by SimplyTav** [Anuken/Mindustry-Suggestions#2555]
**Describe the content or mechanics you are proposing.**

Nobody ever cared about eruptor that much did they? so maybe atrax getting a rework could be what it needs, what if it shot explosive star-like (inspired by Naxanax#5116) bullets that inflicts sapped effect

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Again, spiders before spricot are underused and not good and deserve to be better than just filler content, a good idea could be to rework/buff both of them

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by vinhsad** [comment]
@SimplyTav ya mean this?
https://imgur.com/a/umxmPbD
it's me Nava :D

**Comment by SMOLKEYS** [comment]
> @SimplyTav ya mean this?
> https://imgur.com/a/umxmPbD
> it's me Nava :D
> 

why is the spiroct releasing so much bullets
~~and also why is there a random slag crater~~

**Comment by vinhsad** [comment]
> > @SimplyTav ya mean this?
> > https://imgur.com/a/umxmPbD
> > it's me Nava :D
> 
> why is the spiroct releasing so much bullets
> ~and also why is there a random slag crater~

it's just a rando slag pool, also the picture just a ton of js, it just for testing...

**Comment by USMP-lancer** [comment]
true, atrax is kinda sad, but maybe we could have slag mortor, which is just a half ranged fortress with its bullets fragging into slag bullets

**Comment by numer99** [comment]
just change the color of the slag to purple

**Comment by USMP-lancer** [comment]
perhap instead of my previous idea, have its range be doubled, but its dps cut to 2/3 original
