### ISSUE TITLE
Rework for t1-t3 combat ground

### ISSUE THREAD

**Issue by SimplyTav** [Anuken/Mindustry-Suggestions#2556]
**Describe the content or mechanics you are proposing.**

Stronger T1-T3 combat ground
(Dagger) Duo's bullets --> Flak barrage
(Mace) Improved range, constant firing of both weapons
(Fortress) Artillery --> Mini-artillery Shotgun

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

T1-T3 combat ground units are underpowered, they need a buff and unlike their air and naval counterparts, their cost is not worth it compared to their strength

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by D-player1** [comment]
> constant firing of both weapons 

This is cursed

**Comment by SimplyTav** [comment]
> This is cursed
Why?
Basically, i want it to have 2 normal scorches, not 2 under-powered under-ranged scorches

**Comment by itcannotbe** [comment]
Can we just stop extending the range of short range units. If anything, find a way to make short range units viable. Like making them not die before getting the chance to shoot?

Like I dunno something like distance armor?

**Comment by Kryvytsky** [comment]
Fortress is Ok right now. It have long range, good damage and hp. Only problem it can't target air units.

**Comment by Kryvytsky** [comment]
About mace. Maybe speed buff would be better?
