### ISSUE TITLE
Smorter poly

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2557]
**Describe the content or mechanics you are proposing.**
Improve poly AI:
-make poly find the nearest enemy air turret and avoid moving into the turret range
-make poly when they aren't doing anything (normaly they stay at core) go mine (i know logik exist but it'll be better)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
make poly stop dying when moving also mine ore when they're not doing anything
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
~what about *smorter* human being~
jk jk

**Comment by oinkymoo** [comment]
if you're building close enough to enemy lines that the first part is necessary, you are doing something wrong. also they do not mine ore when allowed to idle, they simply don't move and flee from nearby enemies
