### ISSUE TITLE
Make force fields block air unit corpses

### ISSUE THREAD

**Issue by Yell245** [Anuken/Mindustry-Suggestions#2558]
**Describe the content or mechanics you are proposing.**
Force projectors block bombs falling from the sky, right? So maybe they should also block air units falling from the sky?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, there's no counter to units falling.
It theoretically could may be a counter to blast bombing (cancer) or just fat units falling and destroying your entire defences. I don't think force projectors should just go and "*pop*" and consume unit falling like if it was a single bomb. I think they should heat from heavy units falling on them.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
yes

**Comment by itcannotbe** [comment]
Didn't the PR that allows you to kill corpses got merge a while back?

**Comment by Humanoid-X** [comment]
ooh

**Comment by EclipsePlays** [comment]
> Didn't the PR that allows you to kill corpses got merge a while back?

PR number?

**Comment by Yell245** [comment]
> Didn't the PR that allows you to kill corpses got merge a while back?

Oh, it merged? Hold up, I'm gonna check...

**Comment by Yell245** [comment]
Alternative solution found: air units are fully destroyed when there's enough damage
