### ISSUE TITLE
fix support units

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2559]
**Describe what you would like changed, and why.**
Let me start off this suggestion by listing all the support units that dont have any support abilities, other than their weapons doubling as building healers.
they include vela and corvus on the ground side, and mega and quad on the air side.
and even the ones that do have abilities sometimes hardly use them. all units except mega deliberately use their weapons that can heal buildings, to heal buildings.
corvus, quad, and others are really just alternate assault units that have some building ability. the "healing" trait added to the weapons can only be utilized by logic and seems like an excuse to call it a "support" unit.
so i propose some changes to the support tree, to actually make it the support tree. so mega is more than zenith's weird cousin. so vela and corvus arent just alternate assault units.

**Describe the changes you want to propose. Include possible alternatives.**
- i would propose adding point defense and/or unit healing guns to vela, corvus quad and mega. and maybe nerfing their existing attacks to balance it out.
- i would propose the units that can use their weapons to heal, like nova and quad, actually heal buildings like mega does, but only when enemies arent present or are unreachable.
- i would propose navanax shoots EMP blasts at allied GUNS, and allow navanax to choose when its projectile blows up like fortress can. i would not let it shoot anything since it could shoot at factories and powerplants and cause issues with generators needing resources.
- i would propose changing pulsar's support ability, as the current one can often be completely useless.

**Comment by ShadeStrike62** [comment]
This is very true. Buff needed. Also buff Oct please its trash in campaign rn...

**Comment by JrTRinny** [comment]
I like your idea of changing "support" units. but those units are really 'supporting' you know? they just support in other way:

Well, They 'support' other units in battle. look at Quasar, they have shield to protect allies (no-one uses it though) or maybe Corvus, they have laser to assault enemy turrets, then Reign finishes the battle. See the pattern? they don't need to 'support' you to be support unit.

(I know that phrased badly, I don't have time to write lol)

**Comment by ShadeStrike62** [comment]
> I like your idea of changing "support" units. but those units are really 'supporting' you know? they just support in other way:
> 
> Well, They 'support' other units in battle. look at Quasar, they have shield to protect allies (no-one uses it though) or maybe Corvus, they have laser to assault enemy turrets, then Reign finishes the battle. See the pattern? they don't need to 'support' you to be support unit.
> 
> (I know that phrased badly, I don't have time to write lol)

yeah but they don't do this actively, which is a big issue, as they are just damage units otherwise

**Comment by TranquillyUnpleasant** [comment]
I feel like the major "support" factor quad has is from the fact that it can pick up buildings and move them around, giving it a utility that no unit other than oct can match. The air support line is generally meant as player control upgrades, so it makes sense that it would need logic to actually be useful since that can simulate player control somewhat, although i do agree that quad should have defending ai rather than offensive ai.

As far as corvus and vela, i think they are meant to be offensive units and not "support". The entire ground lazer line is offensive backliners to a certain extent. They just also happen to heal if needed.

**Comment by sup3r87** [comment]
> This is very true. Buff needed. Also buff Oct please its trash in campaign rn...

Less of a buff. I would call it a change in unit “style”



> I like your idea of changing "support" units. but those units are really 'supporting' you know? they just support in other way:
> 
> Well, They 'support' other units in battle. look at Quasar, they have shield to protect allies (no-one uses it though) or maybe Corvus, they have laser to assault enemy turrets, then Reign finishes the battle. See the pattern? they don't need to 'support' you to be support unit.
> 
> (I know that phrased badly, I don't have time to write lol)

I know what you mean. But in my eyes, support units should be able to support their fellow units while attacking. For example quad’s building moving ability has no use when attacking a base.
