### ISSUE TITLE
2x2 crossover junction block 

### ISSUE THREAD

**Issue by pallas** [Anuken/Mindustry-Suggestions#256]
This 2x2 block would take inputs just like a regular junction block, but swap conveyor tracks as they pass through. That is,

```
track C -----v  v----- track D
track A --> |\\//| --> track B
track B --> |//\\| --> track A
track D <----/  \----> track C
```

This allows cleaner swap-overs of resource tracks with the trade-off that it takes more space.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
again with other blocks, seems like a pretty niche idea that you wouldn't use much. Additionally, I'm pretty sure this is possible with some sorter jank.

**Comment by Anuken** [comment]
Yeah, this is far too specific to ever be added.
