### ISSUE TITLE
[Modding] 7.0: Since everything is unsafe, add a warning + verified list?

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2560]
**Describe what you would like changed, and why.**
Add a dialogue thing upon opening the Mods thing that warns people that mods may be unsafe, I'm not sure if this has already done because I didn't check fully for it, only the commit removing the warning from Java mods.
Possibly also a verified mod list? Verified mods being confirmed safe mods by trusted people or the discord moderators.

**Describe the changes you want to propose. Include possible alternatives.**
(this is already explained above)

**Comment by Humanoid-X** [comment]
yes
