### ISSUE TITLE
Terrain generator seeds

### ISSUE THREAD

**Issue by danil275487** [Anuken/Mindustry-Suggestions#2561]
**Describe the content or mechanics you are proposing.**
man you know what would be nice? if you could input a custom seed manually into each terrain generator.
in each terrain generator thingie, there would be a text box to enter your seed and make a randomly generated one.
lets say you want to have 2 generators have identical shapes (for example, easier generator for rivers with sand) you could randomly generate a seed wich you like, copy it and paste into the 2nd generator to get the identical shape (but different contents)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
easier map making, i guess?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipsePlays** [comment]
It's a lot better if you just did make the map using the Generate tab in the map editor, it could help you determine the terrain and looks that you want. 
Plus random seed generation is too complex and will surely have lots of bugs to fix.

**Comment by oinkymoo** [comment]
random seed generation is currently the only option

**Comment by SMOLKEYS** [comment]
> Plus random seed generation is too complex and will surely have lots of bugs to fix. 
> 

Well, thats how it goes in most WIP games, the generation is very buggy at first but gets fixed eventually.

**Comment by danil275487** [comment]
> It's a lot better if you just did make the map using the Generate tab in the map editor, it could help you determine the terrain and looks that you want.
> Plus random seed generation is too complex and will surely have lots of bugs to fix.

...that is what i was talking about.


> random seed generation is currently the only option

no shit

**Comment by SMOLKEYS** [comment]
> > It's a lot better if you just did make the map using the Generate tab in the map editor, it could help you determine the terrain and looks that you want.
> > Plus random seed generation is too complex and will surely have lots of bugs to fix.
> 
> ...that is what i was talking about.

lmao

> > random seed generation is currently the only option
> 
> no shit

lmao²
