### ISSUE TITLE
New PvP system

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2562]
!!!Machine translate!!! Hello everyone, I will ask in advance those who can read Russian to read this in the original. In general, at the moment, PvP at high ranks is tied mainly to the rush of the core, that is, if you destroy the core, you win. There are many rush tactics for this, such as pushing more pyrotite into flares, detonating them on the core, etc. I think that this is too easy and powerful t4-t5 units become almost useless. I suppose this problem can be solved not by balancing units, items loaded into units or so, but more radically and, I think, more correctly. Rejection of the cores. I propose to introduce the ability to disable the cores in pvp, that is, at startup, you will start with a box of 1k capacity, instead of the core. Resources will be accumulated and used in boxes already supplied by the player, the resurrection of your ship will take place in the same boxes, the closest one from the place of death will be the place of spawn, and the number of units available for construction will be determined in the settings before the start of the game. In fact, I propose to distribute the role of the cores to boxes, but this would be more correct. The battle will be aimed at attrition, not defense of the center. And yes, I will not forgive completely abandoning the concentration of cores, you need to give the players a choice of exactly how they want to play, because there will be fans of the existing pvp. 

Всем привет, заранее попрошу тех, кто может читать по русски прочитать это в оригинале. В общем, в данный момент ПвП на высоких рангах завязано в основном на раш ядра, то есть уничтожил ядро - победил. Для этого существует очень много раш-тактик, по типу затолкать во вспышки побольше пиротита, взорвав их на ядре и т.д. Я думаю, что это слишком просто и мощные т4-т5 юниты становятся практически бесполезными. Полагаю, эту проблему можно решить не балансом юнитов, предметов, нагруженных в юниты или около того, а более радикально и, как я думаю, правильней. Отказ от ядра. Я предлагаю ввести возможность отключить ядро в пвп, то есть при старте вы будете начинать с ящиком на 1к вместимости, вместо ядра. Ресурсы будут копиться и использоваться в ящиках уже поставленных игроком, воскрешение вашего корабля будет происходить в этих же ящиках, самый ближний от места смерти и будет местом воскрешения, а количество юнитов, доступных для постройки, будет определяться в настройках до начала игры. По сути я предлагаю распределить роль ядра на ящики, но так будет правильней. Битва будет идти на истощение, а не защиту центра. И да, я не прощу полностью отказываться от концпеции ядер, нужно дать игрокам выбор как именно они хотят играть, ведь найдутся фанаты и существующего пвп.
1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipsePlays** [comment]
How can we win if the no-core gamerule is enabled

**Comment by Noob17** [comment]
I believe he wants pvp in Mindustry to turn more StarCraft esque. You only win if all enemy buildings (maybe units in this guy's idea) are destroyed.

**Comment by Qvertyes** [comment]
> 
> 
> I believe he wants pvp in Mindustry to turn more StarCraft esque. You only win if all enemy buildings (maybe units in this guy's idea) are destroyed.

I dont play StarCraft, but i know about what you say. You think its bad?

**Comment by Kyllingene** [comment]
What do you use as a substitute for the core storage?

**Comment by Qvertyes** [comment]
> 
> 
> What do you use as a substitute for the core storage?

Storage and vault placed by player

**Comment by Kyllingene** [comment]
The problem being that you must have core storage to have the materials to place storage.

**Comment by Qvertyes** [comment]
> 
> 
> The problem being that you must have core storage to have the materials to place storage.
> 
> Note that I really do like this suggestion, it just seems that there are a few things that would need to be ironed out first.

idk how it translate by machine, but i say in original what you spawn with vault instead core

**Comment by Kyllingene** [comment]
Ah, ok. Sorry, I missed that.

**Comment by oinkymoo** [comment]
> > The problem being that you must have core storage to have the materials to place storage.
> > Note that I really do like this suggestion, it just seems that there are a few things that would need to be ironed out first.
> 
> idk how it translate by machine, but i say in original what you spawn with vault instead core

yeah in got translated to box(es)
