### ISSUE TITLE
optionally base-centered planet(s)

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2563]
**Describe the content or mechanics you are proposing.**

when launching to the next planet in v7, give players a choice between 2 planet options: a planet with mostly attack sectors, or a planet with mostly survival sectors (like serpulo, which is about 78.3% survival)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I personally do not enjoy survival sectors very much. I find them incredibly boring. However, I realize that this is not a viewpoint shared by all. Thus, a choice: for those who enjoy them, there are more attack sectors. for those who enjoy them, there are more survival sectors.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
thonc
