### ISSUE TITLE
Easier conveyor upgrades

### ISSUE THREAD

**Issue by MistahStealYoGril** [Anuken/Mindustry-Suggestions#2564]
**Describe the content or mechanics you are proposing.**
Maybe a console command or something that upgrades all of the conveyors you control.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It helps keep the flow of materials smoother.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
how will this work when you have insufficient materials to do so? also i'm pretty sure the console is not available in vanilla

**Comment by Kyllingene** [comment]
This seems like a lazy suggestion... there are already things implemented to increase the ease of replacing conveyors.

**Comment by Humanoid-X** [comment]
eg. lOgIc
