### ISSUE TITLE
Blast/PyraMixer craft effect

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2565]
**Describe the content or mechanics you are proposing.**
add blast/pyramixer a crafting effect 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it make the factory less confusing to look at
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Hyrotrioskjan** [comment]
wh-
what?

**Comment by Humanoid-X** [comment]
...wh...wwhhhaaaaatt?????

**Comment by Humanoid-X** [comment]
do u mean a silicon smelter/kiln like effect?

**Comment by konstantys** [comment]
A simple and short one, yet noone suggested IT yet. I love it.
For the confused ones; a lot of błocks have those effects, like drills, different gens, and kilns, silicon smelters, etc. Its usually a particle every time it "does one action"

**Comment by SMOLKEYS** [comment]
Do you mean the *r o t a e t* effect?
