### ISSUE TITLE
Show core no-build radius/zones on the map

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2566]
**Describe the content or mechanics you are proposing.**
Make the core no-build radius or zones from the poligonal version show on the map

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It's a nice QoL, plus would probably look cool

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
I like this idea.
Could do well as a toggleable setting.

**Comment by Humanoid-X** [comment]
Yes and make it toggleable
