### ISSUE TITLE
plasma walls

### ISSUE THREAD

**Issue by firstcreator48** [Anuken/Mindustry-Suggestions#2567]
**Describe the content or mechanics you are proposing.**
piercing bullets are halved, include pierce damage
hp: 1145 {(•4 for large version, "•" is equivalent to multply)i bolstered the hp proportional by them people}
pierce weakening: 50%
pierce halving: 50%
cost: 2 surge 3 plast 6 titanium 9 lead
include large version •4

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
since reign bullets pierce and its dps is deadly this may help people tank and destroy waves of reign or for having protection on your critical sources of resources 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
So it's used to counter piercing bullets that can't normally be countered any other way?

**Comment by Kryvytsky** [comment]
Hp you propose is too low. Walls would be destroyed fast. I think this wall should have Hp on same lvl as plastanium wall. Also in should stop piercing shots. This would be usefull to counter Omura rather Raign.

**Comment by Kryvytsky** [comment]
Also. Doesn't Segment destroy Raign projectiles?

**Comment by OnyxFinger** [comment]
>  since reign bullets pierce and its dps is deadly this may help people tank and destroy waves of reign or for having protection 
> on  your critical sources of resources

> Also. Doesn't Segment destroy Raign projectiles?

yes, but it cqn't do it efficiently, unless it is spammed (bad idea, space and power will go brr and die)

just.. add more walls.
there is no use for a plasma wall

> Hp you propose is too low. Walls will be destroyed fast. I think this wall should have Hp on same lvl as plastanium wall. Also in should stop piercing shots. This would be usefull to counter Omura rather Raign.

no because if it has low hp, Omuras will go through it like butter
~~Omuras go through anything like butter, that's the point~~

**Comment by Kryvytsky** [comment]
> ~Omuras go through anything like butter, that's the point~
Yep and that is a problem, cuz unlike Corvus there no way to be safe from Omura shots.

**Comment by oinkymoo** [comment]
that is very expensive. all other walls are 6 of the same item (24 for large walls), except for plast walls which are 5 plast 2 metaglass. this is 20 items for a small wall

**Comment by EclipsePlays** [comment]
I am here to say the magic word that solves this thread. 

M O D S

**Comment by MrDuck557** [comment]
> Yep and that is a problem, cuz unlike Corvus there no way to be safe from Omura shots.

Note: Omura doesn't pierce the whole way through, the bullet takes damage proportional to the damage dealt to blocks

**Comment by itcannotbe** [comment]
Note:

> > Yep and that is a problem, cuz unlike Corvus there no way to be safe from Omura shots.
> 
> Note: Omura doesn't pierce the whole way through, the bullet takes damage proportional to the damage dealt to blocks

Note: Bullets that pierce can only pierce a limited amout of times depending on what amount is the bullet set to.

**Comment by RoboRogue** [comment]
raiegn doesnt pierce it frags
