### ISSUE TITLE
mute music/sounds/ambient noises buttons

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2568]
**Describe the content or mechanics you are proposing.**

3 mute buttons for music, sound, and ambient noise, respectively, or just 1 to mute all sound

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

these buttons existed in classic but have since been removed for no apparent reason. it's really inconvenient having to switch back to 50% volume when i'm done listening to other music.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
~You lazy~
