### ISSUE TITLE
add item slot for incinerator

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2569]
**Describe the content or mechanics you are proposing.**
Currently, we can't drop any item into an incinerator even with logik, we can only do that with conveyor (or other transport block) so make we can drop item directly into an incinerator 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
improve logic unit system
to avoiding griefing by using logic, i suggest to when we touch a unit, we'll see what's the name of who placed the logic
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
make sense, but how many? 10? 20? 50? 100? cant be infinite.

wait, what if we make units able to drop their inventories out of thin air, like controlled unitts?

**Comment by oinkymoo** [comment]
drop to delete with logic has been suggested before, i think itemDrop to null was one of the options proposed

**Comment by vinhsad** [comment]
> drop to delete with logic has been suggested before, i think itemDrop to null was one of the options proposed
Drop things to thin air will make the thing better at griefing...
