### ISSUE TITLE
Message that informs you that you have reached the unit limit (6.0)

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#257]
**Describe the content or mechanics you are proposing.**
A simple message that appears when you hover over a unit factory which is not producing units due to you having already reached the unit cap.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will simple make it more obvious to players why no new units are being produced. Of course, if you plan to add this in the description or in a tutorial, then it can always be removed again.

EDIT: This is for 6.0, not current.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
uhhhhh.... You know that already exists right? when you hover/click on a block, a space in the bottom right appears that shows you the specifics of that block, like how many units it has built... smh

**Comment by zethnest** [comment]
This may be a feature request for 6.0 as 6.0 have a shared general limit of units

**Comment by itcannotbe** [comment]
Why don't we not make suggestions for unfinished v6 game mechanics.

**Comment by Catchears** [comment]
Sure.
