### ISSUE TITLE
AI Building changes: Schematic Difficulty 

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2571]
**Describe the content or mechanics you are proposing.**
On the campaign, make it so the AI building builds different schematics based off the sector's dificulty, to match the pre-built buildings on the map.
On custom maps, add a slider that lets you change the dificulty.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will make the AI builder a little bit more challenging on higher-dificulty sectors, aswell as giving more opportunities to level makers.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
doesn't that already exist

**Comment by AtobaAzul** [comment]
> doesn't that already exist

On custom games, ofc not, but on the campaign I'm actually unsure.
On custom games, it's seemingly random, example:

![image](https://user-images.githubusercontent.com/75080541/122625356-24affc00-d07b-11eb-9597-9e3681014508.png)
Thorium wall structure using airblast drills meanwhile simple scatters and duos are besides it.

**Comment by LeoSko** [comment]
Internally it uses calculation based on the amount of resources needed to build schematic, which is very basic approach.

When I implemented AI for ranked PvP server, I intentionally removed that logic and labeled each and every schematic manually according difficultly, which seem to work much better.
