### ISSUE TITLE
Add a cooldown to the AI Builder's rebuilding

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2572]
**Describe what you would like changed, and why.**

Add a cooldown to the rebuilding of enemy AI
WIth many AI builders, it's near impossible to destroy any enemy buildings without them instantly getting rebuilt.

**Describe the changes you want to propose. Include possible alternatives.**

A cooldown to rebuilding, or a behaviour similar to Poly's where it retreats if enemies are nearby.

**Comment by MrDuck557** [comment]
1. Poly, alpha, beta and gamma share the same default ai
2. Do you mean it builds right after you destroy something?

**Comment by AtobaAzul** [comment]
> 1. Poly, alpha, beta and gamma share the same default ai
Alpha, beta and gamma do not retreat when there's enemy units nearby WHILE they're building, and they go to build/rebuild mid-retreat.
> 2. Do you mean it builds right after you destroy something?
With many builders, yes, well, not exactly but really fast
I'll show a vid on discord with the builders fastly re-building

**Comment by AtobaAzul** [comment]
https://cdn.discordapp.com/attachments/623672591957229578/855605474895200326/Mindustry_2021-06-18_21-17-06.mp4
Here

**Comment by Humanoid-X** [comment]
~That is a good feature, poly are supposed to be used like this~
Jk jk
