### ISSUE TITLE
Schematics in the level editor

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2573]
**Describe the content or mechanics you are proposing.**
Schematics for the level editor, similarly to the schematics for in-game buildings, allowing you to quickly build a map off preset terrain and buildings.
Maybe add a filter to ground, walls, and buildings when saving the schematics, so saving ore clusters, for example, is a possibility.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Faster creation of levels, new design possibilities

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
I think in somewhere I saw someone drawing terrains in game, although I cant recreate that video

**Comment by itcannotbe** [comment]
Isn't this suggestion literally the second most suggested suggestion next to folder schematics?
