### ISSUE TITLE
addition to multiplayer mode

### ISSUE THREAD

**Issue by Gustavo996** [Anuken/Mindustry-Suggestions#2574]
*Describe the content or mechanics you are proposing.**

Adds some kind of player ip or some kind of key, that each player would have one, making it possible to add to friends, and being able to enter his host when activated.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would make the remote server issue much easier, removing many of the difficulties and the fact that you have to somehow create a server for your friend to host on you

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2357#issuecomment-826160788

**Comment by Humanoid-X** [comment]
*Sigh* Why everybody, including my mom, is like that?! DO YOU ALL THINK SERVER HOSTING IS VERY CHEAP?!!?!?!!!?!?!???!?!
