### ISSUE TITLE
Building cooldown

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2575]
**Describe the content or mechanics you are proposing.**
An optional setting, which does this:
If a block on a tile got destroyed, next (X) seconds you or AI may not build there.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In PvP, if one team has like 30 Polys, if anything is destroyed, they rebuild it right away. You can also do the same manually. So this setting will stop that.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WilloIzCitron** [comment]
noi didnt accept this pull

**Comment by OnyxFinger** [comment]
generally, this isn't an issue.
In fact, in pvp it isn't, unless you are managing your attack really bad
