### ISSUE TITLE
Stop notifying about "issue closed"

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry-Suggestions#2577]
stop it

P.s Discord #suggetions

**Comment by Humanoid-X** [comment]
~Probably because all of you issues keep getting closed~

**Comment by itcannotbe** [comment]
Github doesn't have the option to customize which actions corresponds a webhook. So it's basically no.

**Comment by oinkymoo** [comment]
i already suggested this, but the webhook doesn't give configuration options. anuke said so himself https://github.com/Anuken/Mindustry-Suggestions/issues/2514#issuecomment-853999854

**Comment by Qvertyes** [comment]
Печально

**Comment by WilloIzCitron** [comment]
anuke added stale system because most useless suggestion can be closed
