### ISSUE TITLE
Water Jets for the Mega?

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#2578]
**Describe the content or mechanics you are proposing.**
Water jets for the mega would essentially be two jets on either side of the mega which would fire at fires with a consistent and constant stream of water like a wave, but much less efficient. If a player is controlling a mega, the mega will automatically control the water jets while the player controls the healing lasers.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We don't have a fire-stopping unit yet and I think the mega would fit the requirements. Its not as small as a poly or as big as a quad. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
what ?
:eyes: whatever I guess it wouldn't affect the gameplay much.
but be loud.
and we'd have fountain units :/

**Comment by Humanoid-X** [comment]
Whats the point, will probably even be used to make noise machines
Mega is already OP imo

**Comment by itcannotbe** [comment]
Also fighting fires is already too easy, why do you even need a unit for that?

**Comment by Kryvytsky** [comment]
We already have Tsunami.

**Comment by Kryvytsky** [comment]
Also this Mega probably would be bad if you use pyratite/fire/oil synergy.

**Comment by Axzye** [comment]
> Also fighting fires is already too easy, why do you even need a unit for that?

gotta have a solution for people that don't understand that a few watexs won't supply a tsunami, i suppose
