### ISSUE TITLE
Pixelate

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2579]
**Describe the content or mechanics you are proposing.**
make Logic Displayer won't get pixelated also use 3x5 (or 5x5?) pixel front for logic messages 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
for a few people useing pixelate (like me) can do logik better
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
none of the text is pixelated, why would message blocks be any different?

**Comment by vinhsad** [comment]
the message text didn't even display .-.

**Comment by oinkymoo** [comment]
oh well that's a different problem and you should probably clarify that you want the resolution increased from 0 by 0
