### ISSUE TITLE
mindustry discord development suggestions

### ISSUE THREAD

**Issue by J-VdS** [Anuken/Mindustry-Suggestions#258]
A way to prevent the suggestions in #development is to block/lock the channel unless you have a certain role.

In #rules at the bottom you could a line: I don't post suggestions in #development and will read the description.
After they pressed an emoji they get the role (no-suggestions) and the development channel will be unlocked.
(Maybe make the role colour white)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by J-VdS** [comment]
I am willing to make a change to corebot or deploy my own discord bot which will only have this purpose.

**Comment by itcannotbe** [comment]
But how would you know if the text contains a suggestion?

It can't be helped that people just don't bother to make an effort to read.

**Comment by J-VdS** [comment]
eh they just need to read #rules more carefully and get a role to access #development. I am not going to filter messages bc that will result in a mess.

**Comment by itcannotbe** [comment]
But people will just press the reaction without reading anything.

**Comment by J-VdS** [comment]
that is true but you could make it clever, I might make a bot and send you a dm with an example
