### ISSUE TITLE
uhhh...Radar problem?

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2581]
**Describe the content or mechanics you are proposing.**
Currently, the Logic Radar (or the unit Radar) command has a part called "order" it's can only be 0 or 1 (for first -> last and last -> first)
how about change it so it can check the 1st then the 2nd...then the 3rd...?, it could be better
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Imrpove logic radar

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
what about last?

**Comment by Humanoid-X** [comment]
My idea is
-1 for last
-2 for last 2nd
etc

**Comment by abdallah362** [comment]
for last should be 0
if you want the last just type 0
that will be better
