### ISSUE TITLE
Player ship is in the way of info text

### ISSUE THREAD

**Issue by Zaflis** [Anuken/Mindustry-Suggestions#2582]
**Describe the content or mechanics you are proposing.**

Text should be rendered in front of ships. Currently this affects pumps and miners at least.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently to solve that you have to unpause game, move ship and then go back to what you were doing. All because i can't see some statistics.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [ !Not exist in Steam version! ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

![intheway](https://user-images.githubusercontent.com/1862429/122673956-b20a6200-d1db-11eb-8244-05eed0a555e0.jpg)

**Comment by OnyxFinger** [comment]
ah, it has never really been a problem for me, though I guess it would be some nice QoL improvements
