### ISSUE TITLE
Unit Building

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2583]
**Describe the content or mechanics you are proposing.**
1.Add a logic command called "Remove" (x,y) so it make a unit remove the block, to avoid griefing, i suggest to make it can **Only** remove block that placed by the processor or other processor building
2.add a new group in locate command, called Block (@block) so it make a unit locate a certain block (ex:@conveyor, @copper-wall......)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
improve lofic building
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
I love how you type lofic every time you make a suggestion

**Comment by oinkymoo** [comment]
if i remember correctly, the inability to deconstruct with logic was intentional, to prevent griefing

**Comment by Humanoid-X** [comment]
@oinkymoo
he said, "to prevent griefing, blaah blah"

**Comment by Nhimanss** [comment]
> if i remember correctly, the inability to deconstruct with logic was intentional, to prevent griefing

you can already grief by placing blocks, adding limits sounds reasonable
