### ISSUE TITLE
MELTdown

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2584]
**Describe what you would like changed, and why.**
Make meltdown inflict melting
It would fit the name

**Describe the changes you want to propose. Include possible alternatives.**
Blocks.meltdown.shootType.status = StatusEffects.melting;

**Comment by EclipsePlays** [comment]
Also to make a meltdown have a use: 

Any air unit that dies from meltdown damage shouldn't give a critical damage (fall damage effect)

**Comment by Humanoid-X** [comment]
When you see weird titles from this duck you know it is something good

**Comment by Quezler** [comment]
i think this would be neat, i haven't seen meltdowns used at all vs foreshadows & specters lately, this would be a nice buff to make it more viable 🤔

**Comment by MrDuck557** [comment]
PR already implemented, closing
