### ISSUE TITLE
Fix translations for the Czech language

### ISSUE THREAD

**Issue by EnderquakeYT** [Anuken/Mindustry-Suggestions#2586]
When the game says "1 enemy remaining" then it says "1 zbývající nepřátel" in Czech. That is an inaccurate translation and it should be changed to "1 zbývající **nepřítel**". Change this only for 1 enemy, not more enemies.

**Comment by itcannotbe** [comment]
Go fix it yourself.

**Comment by itcannotbe** [comment]
Go fix it yourself.

[Translations Read Me](https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md)

**Comment by Humanoid-X** [comment]
Go translate it yourself, then close this
