### ISSUE TITLE
Advanced Command Center

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2587]
**Describe the content or mechanics you are proposing.**
(Before someone just comes here and say "You can just use logic", not everyone has the skill needed, and there are other structures in-game that can be replicated using logic already.)

An improved version of the command center, with more functionality.
Cost idea:
Plast/Surge and silicon, needs 200 units/s of power.

Functionality:
It lets you choose what units will be bound to it, and still has the rest of the functionality of the normal command center.
You can control it to be able to issue a "Move here" Command, to make the assigned units go the the desired place (maybe through clicking on the desired spot?) 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A nice QoL, essentially a move "newbie friendly" version of some logic things I've seen already.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Doesn't that fall under additional configuration of blocks?

**Comment by AtobaAzul** [comment]
> Doesn't that fall under additional configuration of blocks?

On second though, that kinda is like that.

**Comment by Kyllingene** [comment]
> Doesn't that fall under additional configuration of blocks?

No? This is requesting a new block with new functionality; additional config would be something like disabling certain router directions, which is modifying existing functionality in an existing block. Whether or not this is a good suggestion (I don't play enough PvP to judge), it is definitely allowed by the readme.

**Comment by itcannotbe** [comment]
I think you for got that OP said the use case was to set a move command or a rally point using that block. Which add configuration to the block.

**Comment by Kyllingene** [comment]
You add configuration to a *new block*. They are asking for a *new block*. They are not asking for an upgrade to an existing block. They are asking for a *new block*.

**Comment by Yell245** [comment]
> I think you for got that OP said the use case was to set a move command or a rally point using that block. Which add configuration to the block.

Ok, delete all sorters, unloader, unit factories and command center from the game then

**Comment by itcannotbe** [comment]
> You add configuration to a new block. They are asking for a new block. They are not asking for an upgrade to an existing block. They are asking for a new block.

By extention I can ask a better block of any block in game and add in io configuration functionality to them.

**Comment by oinkymoo** [comment]
i understand that to mean the ability to configure blocks more in general, not a new option for a specific block

**Comment by OnyxFinger** [comment]
I like the idea, but CCs are already way to pricy, and I'd assume you need one "special CC" for every unit, ssoo making one pricier isn't a good idea at all
