### ISSUE TITLE
Idle polys go to command centers

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2588]
**Describe the content or mechanics you are proposing.**

Make idle polys and megas go to command centers set on "Rally"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Sometimes, with many polys they tend to cover a lot of the screen, having control on where they'll stay without having to use logic or manually moving them would be nice,

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
~lofic~
that will be a good feature tho
