### ISSUE TITLE
Landscape update

### ISSUE THREAD

**Issue by IvanDem2009** [Anuken/Mindustry-Suggestions#2589]
**Describe the content or mechanics you are proposing.**

I propose to diversify the landscape of the game. For example, add a current for water tiles that can be set up in the editor, with different directions of flow and speed of flow. You can add forest sectors (with grass tiles and pine trees). Also, I noticed that there are no slag tiles in any sector. You can make a sector in the ide slag lake.
If am bad in English. If you dont understand me, i can write this suggestion on Russian.
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The game will be more like real life =)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kryvytsky** [comment]
New type of sectors would probably added in V7 update together with new planets.
