### ISSUE TITLE
Copy/Paste Map Editor

### ISSUE THREAD

**Issue by DavePie** [Anuken/Mindustry-Suggestions#259]
**Describe the content or mechanics you are proposing.**
Similar to how you can save schematics and place, the mechanic is to be able to save, copy, and paste terrain and tiles. This would work with f-drag, and you can save a specific piece of terrain/tiles for later.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be a massive time saver for map makers, especially in cases with angled pathways.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SheepCommander** [comment]
I like how it's constantly mentioned but nothing ever actually happens here

**Comment by sample-text-here** [comment]
that's good. it means nobody can find anything wrong with this

**Comment by djradnad** [comment]
i need this tbh

**Comment by SheepCommander** [comment]
copy and paste re-create lmao
