### ISSUE TITLE
2×2 Scorch

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2590]
**Describe the content or mechanics you are proposing.** 

In V6 we got a Tsunami, it's just 3×3 Wave.
In V7 we would get 2×2 Repair point.
So why not add 2×2 flamethrowers too?
I just like flamethrowers.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Template: Gone

**Comment by Humanoid-X** [comment]
Template be like: What is the meaning of life

**Comment by Kryvytsky** [comment]
Okay, okay. Next time I will be more respectful to Template.

**Comment by OnyxFinger** [comment]
> Okay, okay. Next time I will be more respectful to Template.

can't you edit ?

anyway, I have pretty much no opinion on a 2×2 scorch, but it makes sense, ~~though 50% of the community is stuck on the scorch OP thing, when it wasn't even the case in every situation, also scorches are kinda underpowered rn, my point is though, that many would find that op for no reason **D:<**~~

**Comment by genNAowl** [comment]
15 days late but gonna put this here: https://github.com/Anuken/Mindustry/pull/2782
