### ISSUE TITLE
Quad Mine

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2591]
**Describe the content or mechanics you are proposing.**
Make the "ShockMine" class into a "Mine" class with a customizable bullet.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It won't affect regular gameplay, but modders can have mines with quad bombs for example. It will allow for more creativity than only lightning.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
yes
