### ISSUE TITLE
make payload conveyors placeable on deep water/oil/slag edges

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#2592]
**Describe the content or mechanics you are proposing.**
see title

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
![image](https://user-images.githubusercontent.com/45698812/122945999-d8401700-d32d-11eb-83cf-631e4f4faeec.png)
:(

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BorisA11** [comment]
True, we need that

**Comment by Noob17** [comment]
I have a bad feeling this would be abused, but the odds of that happening are unlikely. (Abused as in PvP one side breaks the wall, and starts pushing units through the water in the middle with ease. However I'm sure building zones would keep this in check.)

**Comment by Highfire1** [comment]
for posterity I did specify just edges (like how pumps are), but payload conveyors have less health than units anyways so that shouldn't be a problem

**Comment by oinkymoo** [comment]
you can literally point that conveyor up and it will be pointing into the oil, but i get your point

**Comment by OnyxFinger** [comment]
this should be done

**Comment by Quezler** [comment]
iirc `floating = true` might be enough 🤔 (or at least part of the solution)
