### ISSUE TITLE
PvP with survival mode

### ISSUE THREAD

**Issue by LawrenceLin2333** [Anuken/Mindustry-Suggestions#2593]
**Describe the content or mechanics you are proposing.**
A new multi-team competition mode, to see which team can survive the longest and the most wave. 
* It likes the normal PvP mode. Players are equally distributed into different teams.
* It likes the normal survive mode. Each team should survive from enemies attack in each wave.
* The players, units and turrets in different teams can not attack each other.
* Each team faces the same number and types of the enemies in each wave.
* The enemies only attack on their corespponding target team. For example, the enemies who are going to attack Yellow team will not attack other things which are not belong to Yellow team.
* When a team is lost (the core has been destroyed), the enemies targeting this team will not be generated.
* The only goal is to protect the core and be the last survivor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
A new mode for player competion. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BorisA11** [comment]
Already achievable — make player teams, say it, blue and green and attacking enemies red. IIRC you can have enemies in PvP maps, all you need are multiple cores

**Comment by RouterChainsSuckk** [comment]
you should suggest that in some servers, i doubt anuke will make a vanilla plugin for this however

**Comment by LeoSko** [comment]
How is that different to just running two separate attack servers?

**Comment by OnyxFinger** [comment]
so like btd battles, *
**it's already doable anyway**
