### ISSUE TITLE
split command points

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2594]
**Describe the content or mechanics you are proposing.**

Currently in the game there is one and only one command center. This allows for the gathering of units but it is hard to use. On most to all maps there isn't a place that provides a good rally point for naval, ground, and air units together. My suggestion is the split the command center into 3 parts, one for ground, one for air, and one for naval. 3 different command centers will not only allow for more strategic rallying, but it would also allow air units to be sent without ground, naval without air and so on. Each command center should require 1/3 or the current command center's resources.  And one final thing, the naval command center should be able to "float", so it can be placed on deep water.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I kinda didn't read ahead so everything is explained up top.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
> [No you have not] I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

This counts as additional configuration

**Comment by Ineedause** [comment]
This is not additional configuration, this is asking 1 block to be split in three, additional configuration would be asking 1 block be able to do 3 things.

**Comment by Yell245** [comment]
> > [No you have not] I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
> This counts as additional configuration

Explain why it's an additional configuration then

**Comment by itcannotbe** [comment]
> > > [No you have not] I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> > 
> > 
> > This counts as additional configuration
> 
> Explain why it's an additional configuration then

Yes, explain why it's an additional configuration then

**Comment by itcannotbe** [comment]
It's not an additional configuration because OP was suggesting to have separate blocks for air, ground, and naval units while retaining the functionality of the current command center.

**Comment by Ineedause** [comment]
thank you itcannotbe, that is what I am trying to say

**Comment by OnyxFinger** [comment]
I'm pretty sure this is not needed ?

**Comment by Ineedause** [comment]
needed: no
If it was added: no more headaches

**Comment by itcannotbe** [comment]
> I'm pretty sure this is not needed ?

In the same logic:

QOL changes are not needed.
