### ISSUE TITLE
Wave 1 of 330? - this is really very, very boring. Will the next one be 1000 Waves?

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2596]
**Describe what you would like changed, and why.**

Good evening

I've just started to catch a new Sector and I've got: **Wave 1 of 330**

Fortunately, there are still many sectors in the game that I could conquer, but now I actually have to wait out 330 waves until I can get back to a more exciting task?

Of course, I don't want to risk losing the sector at wave 327 after all, so I'm forced to hold out.

**Describe the changes you want to propose. Include possible alternatives.**

30, 50 or maybe even 70 upcoming waves are ok, but the game has much more exciting tasks, so the game doesn't need to force the player to be trapped 'forever' in one sector :-)
It would be a nightmare to lose a sector with 330 waves and then have to suffer 500 or maybe even more waves.

**Comment by oinkymoo** [comment]
this is a bug not a suggestion, also what sector

**Comment by schittli** [comment]
:-), that's great to hear 😅, it is sector 162.

I had already captured it once, then the AI recaptured it. 
When I attacked the Sector again, I've got wave 1 of 330.

**Comment by oinkymoo** [comment]
you still should submit a bug report about this tho

**Comment by OnyxFinger** [comment]
1.probably a bug
2.is "truer" to the way the game was made, while kinda keeping the idea of current campaign (somewhat)
