### ISSUE TITLE
Buff Segment

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2597]
**Describe the content or mechanics you are proposing.**
make bullet destroyed by segment  also kill the frag bullet (so the destroyed bullet won't frag into smaller piece)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
make frag bullet easier to be destroyed (like plast ripple)
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
wouldnt this make segment op

**Comment by itcannotbe** [comment]
Well no. Segments are fixed buildings they don't even fire if there is no power lol.

**Comment by OnyxFinger** [comment]
done in v7 already.
