### ISSUE TITLE
introduce new unit types throughout solar system exploration

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2599]
**Describe what you would like changed, and why.**
(this suggestion assumes there will be purple air and naval units in the future)
since there are some new units coming in V7, i think many of them should only be found/unlockable via going to the other planets. this way, it gives the game a better sense of exploration, and other planets feel less like a serpulo adventure with different colors on the ground.

**Describe the changes you want to propose. Include possible alternatives.**
my ideas are that green and purple naval units are only found/unlocked on the second planet, since it appears to be watery and would be a good fit to introduce them. then, introduce and unlock purple flying, and whatever [REDACTED] units are )mindustry trello) in the desert planet (since it seems to be the final planet)

this suggestion is a very fluid general idea, the point being is to not show the player all the units at once, but introduce more kinds as you go to new planets.

**Comment by MrDuck557** [comment]
So lengthen the research progression by locking new units behind other planets

**Comment by sup3r87** [comment]
> So lengthen the research progression by locking new units behind other planets

yep. again, it's the idea of keeping mindustry interesting; the next planets shouldnt feel like serpulo 2 and serpulo 3. new content keeps things interesting and drives players to explore and discover.

**Comment by Humanoid-X** [comment]
yezs i wamt purpke aire, pueplre naevel, slahg planret ane wtaer pkanetz aniouke plz

**Comment by OnyxFinger** [comment]
remember that unit balance should be done first. I think that something that should be taken into consideration is that even with the current V7 changes, units are still not very balanced. Thus I think this should wait until units are balanced, however, it does make sense and should be added, **but this is in the trello (kinda, I recognize it's not very easy to say wether or not it will be like this suggestion or not)** 
also where did the template go ? Did anything change ?
t e m p l a t e ? ? ?

**Comment by EclipsePlays** [comment]
Another thing that helps the trello card was the [Factions Tab], since we have
- Red units (Reign, Eclipse and Omura),
- Green  Units(CarBus, Oct and Navanax), 
- and Purple Units(currently Toxopid).

**Comment by EclipsePlays** [comment]
Another thing that helps the trello card was the [Factions Tab], since we have
- Red units (Reign, Eclipse and Omura),
- Green  Units(CarBus, Oct and Navanax), 
- and Purple Units(currently Toxopid).

**Comment by EclipsePlays** [comment]
> Another thing that helps the trello card was the [Factions Tab], since we have
> - Red units (Reign, Eclipse and Omura),
> - Green  Units (CarBus, Oct and Navanax), 
> - and Purple Units (currently Toxopid).
