### ISSUE TITLE
Mindustry on Steam

### ISSUE THREAD

**Issue by MMT007** [Anuken/Mindustry-Suggestions#260]
**Make The game Cheaper or free on Steam**

**Comment by itcannotbe** [comment]
Why don't you just download the game on [itch.io](https://anuke.itch.io/mindustry)?

**Comment by potatoisagender** [comment]
you know that it is free on steam (I think). The option to support anuke is OPTIONAL.

**Comment by RogueRedHawk** [comment]
The steam version is i.e. the premium version afaik. If you want a free version download on itch.io. This is quite frankly a ridiculous and entitled thing to complain about.

**Comment by zethnest** [comment]
Steam is not free. That's because Steam has a feature where you can start a server for your Steam friends and others outside Steam can't join.

Close this.

**Comment by Anuken** [comment]
No.
