### ISSUE TITLE
Thermal pump rebalance

### ISSUE THREAD

**Issue by AzhurniyBaklan** [Anuken/Mindustry-Suggestions#2600]
In it's current state, plastanium production can be done in 3 ways:
- Tar pits
- Oil pumps
- Spore presses
The two later options are way harder to do as they require huge power input and they give barely a 1% of what tar pits can do. What's weird for me is the fact that thermal pumps can be obtained before plastanium itself, making both spore and tar options way more viable. So, to make it somewhat even, I suggest rebalancing thermal pumps to be more of a high-end technology.

New Thermal pump requirements:
- Copper - 80
- Metaglass - 90
- Silicon - 30
- Plastanium - 40
- Thorium 35
New Pump amount (in float):
-0.25 f

What will this rework achieve?
This rework will make both rotary pumps and oil extractors a more common block in most of the game modes, additionally making thermal pumps stronger.

**Comment by BorisA11** [comment]
Not all maps have tar though. Or usable water. If map creator adds a ton of tar, he/she probably wants to ease plast making. I mean, it should get more expensive, just no need to reduce pumping rate

**Comment by AzhurniyBaklan** [comment]
>just no need to reduce pumping rate
I actually buffed it, it's 0.23 F at the moment. Check source code.

**Comment by buthed010203** [comment]
The entire purpose of oil is to make plast production efficient, nerfing this just because the other plast methods suck would kinda defeat the purpose of having oil at all..

**Comment by itcannotbe** [comment]
Why are we changing pumps based on it pumping one liquid?

What happened about pumping water and slag/lava?

But in any case, the reaaon why someone would suggest this is stupid.

**Comment by itcannotbe** [comment]
Also, oil extractors are already stupid convenient apart from it's tile requirements.

Why do you think it has tile requirements in the first place?

So no, we don't need to see more oil extractors in the late game.
