### ISSUE TITLE
Different crash effects on air unit's death

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2601]
**Describe the content or mechanics you are proposing.**

Make air unit's death explosion change a bit depending on where they crash, for example, on deep water they just sink, on sand it makes a big puff of smoke, on rock it's as it is now, etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Nice little visual efects.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Hyrotrioskjan** [comment]
wasn't this already suggested many times before-?.

**Comment by SMOLKEYS** [comment]
> wasn't this already suggested many times before-?.

Yeah, but those were either:
1. Closed by Github Actions due to being inactive for 20 days.
2. Buried in the wave of closed suggestions.

**Comment by oinkymoo** [comment]
> wasn't this already suggested many times before-?.

i think those were based on what killed it, not where it landed
