### ISSUE TITLE
Low tech Restricted (Armored) conveyor

### ISSUE THREAD

**Issue by Prolbo** [Anuken/Mindustry-Suggestions#2603]
**Describe the content or mechanics you are proposing.**
Restricted - or whatever you want to call it - conveyor wich does not accept inputs from the sides. But without absurd cost/tier requirments of "Armored" one. 

**Describe how you think this content will improve the game.**
The same way other, accessible practically from the begining, logistic blocks do it. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Am I the only one sick of seeing suggestions that have already been suggested?

### And yes I know that duplicates are allowed.

**Comment by BorisA11** [comment]
You can use some other things, like sorters sometimes or just dont make belts intersect. If you really have to, use a junction. It has same speed as titan conveyor.

**Comment by AzhurniyBaklan** [comment]
Junctions exist

**Comment by Prolbo** [comment]
> Junctions exist

Does junctions prevert miners and crafters from dumping production on conveyors/into those junctions? Also, what is the point in Armored conveyors then? With the same logic you can turf AC out of the game and use junctions instead.

**Comment by Humanoid-X** [comment]
use junctions you noob
~~Also, v7 duct, if in zero gravity environments~~
