### ISSUE TITLE
new wall block air

### ISSUE THREAD

**Issue by purofle** [Anuken/Mindustry-Suggestions#2604]
At present, the Mindustry has no walls to prevent air units.
If you add such a wall, then you can implement many ways to play, such as the Wall Wars.

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
If you are saying that walls that prevent air units to pass over it well Honestly its pretty dumb

**Comment by itcannotbe** [comment]
Ah yes, the I want this in the vanilla game so that I can use this in my game mode.

Do you know how stupid that sounds?

**Comment by itcannotbe** [comment]
> If you are saying that walls that prevent air units to pass over it well Honestly its pretty dumb and mods/plugin might can do that anyway so no need to implement it on the game itself

Fun fact. That was the same argument that had been pointed out the last time this was suggested.

**Comment by Yell245** [comment]
**No.** What will be the differences between air units and grounds units then if you just can place the "all-impenetretable"™ wall? What's the point of parallax that holds only one of these units at a time, eats many energy and is very expensive to build if you can place this wall and don't expect any air unit breaching the defences? You literally can put such wall everywhere around your base and that's it, your air unit is now like ground. Also, you will need to rewrite air unit pathfinding

**Comment by Humanoid-X** [comment]
Time to update readme.md!!!

**Comment by OnyxFinger** [comment]
dude that's the point of air units.
also T1 and T2 attack air units aren't as tanky as ground units, so they kinda die, and the other tiers stay in place.
support air will shoot at you if it can, but not pathfind to you, so this route isn't an issue.

**Comment by OnyxFinger** [comment]
> If you are saying that walls that prevent air units to pass over it well Honestly its pretty dumb and mods/plugin might can do that anyway so no need to implement it on the game itself

if you are saying we can use mods or plugin then get out and never come back. Yeah I know I'm kinda rough, BUT :

 *there are so many people who just say "mods" or some other kind of bullcrap while it's NOT a good awnser : It's not vanilla. Same for plugins, it's not vanilla. We are talking about adding content to the game, that everyone is supposed to use, as normally mods/plugins aren't used by everyone, also plugins recquire multiplayer if I recall correctly.*

**Comment by oinkymoo** [comment]
> > If you are saying that walls that prevent air units to pass over it well Honestly its pretty dumb and mods/plugin might can do that anyway so no need to implement it on the game itself
> 
> if you are saying we can use mods or plugin then get out and never come back. Yeah I know I'm kinda rough, BUT :
> 
> _there are so many people who just say "mods" or some other kind of bullcrap while it's NOT a good awnser : It's not vanilla. Same for plugins, it's not vanilla. We are talking about adding content to the game, that everyone is supposed to use, as normally mods/plugins aren't used by everyone, also plugins recquire multiplayer if I recall correctly._

when people say "mods", they are saying that if this gets added at all, it should be added by a mod, and not to the base game, if it gets added at all

**Comment by Humanoid-X** [comment]
yes
it is not like we should not add conveyor, it can be added by mod because EVERYONE IS SUPPOSED TO USE IT. But Wall that block air? no, it is the point of vanilla air unit, not  just "being fast".
