### ISSUE TITLE
New type of air units

### ISSUE THREAD

**Issue by Ksawi999** [Anuken/Mindustry-Suggestions#2605]
**Describe the content or mechanics you are proposing.**
In other td games there are units that are spawning smaller units... So why not add such units to Mindustry?

**First stage**
First stage unit should be very cheap, small, do very low damage and have very small amount of hp. It should cost about 10 silicon and some coal. I suggest to it have very small, fast shooting, electrical weapon with very low range (about 1) and damage. That unit should be worse than flare.

**Second stage**
Second stage should be equipped with a "spawners" that will spawn the first stage units. It must have also any weapon (for example missile launcher).

**Third stage**
Third stage should have second stage spawners and some weapons.

**Next stages**
Every next stage should have one spawner of lower stage unit and some weapons.

**Spawners**
Spawners should have limited launches (for example first stage spawner should have only two launches) and very low reload speed.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Adding it will improve variety of units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
1. That sprite looks quite bad.
2. Mods.

**Comment by Ksawi999** [comment]
> 1. That sprite looks quite bad.
> 2. Mods.

1. That was example.
2. Vanilla Mindustry have only 2 types of air units...

**Comment by OnyxFinger** [comment]
>     1. That sprite looks quite bad.
> 
>     2. Mods.

what sprite ??? also "mods" is not the awnser.
this can actually be a good idea, however in pvp (more than in survival, though it also kinda matters in survival too, if the map is hard, which it usually isn't sad), since making units takes time blablabla, you want to make sure you lose no unit, to not lose the time and ressources you spent in them [insert more blablabla here]
However, a unit creating unit adds something else to the equation : f r e e   u n i t s
keeping them is still good, however you do not spend ressources on them, except for their creator, but this one will create even more behind. Thus, you can make a cheap strong army, or just make the enemy units clash on the free units, kill some while not losing ressources, and get a winning trade which will put you ahead in terms of macro [yade yade yada].
These units can be balanced, and hopefuly will be, but this issue is to count.
Because however this issue is only about balancing, and Anuke didn't add unit making naval units as it was said probable on Trello, I am pretty much all in favor of these units, except for the same thing I said in #2599 , pre existing units will have to be well balanced first, in order not to get a game with a ton of units that are all imba.

**Comment by AzhurniyBaklan** [comment]
> what sprite ???

![image](https://user-images.githubusercontent.com/70016211/123309208-101da900-d53e-11eb-93a4-e02a0de014cc.png)

**Comment by BlueWolf3682** [comment]
> "mods" is not the answer

idk man it worked for me, i *am* a mod dev

**Comment by OnyxFinger** [comment]
> > what sprite ???
> 
> ![image](https://user-images.githubusercontent.com/70016211/123309208-101da900-d53e-11eb-93a4-e02a0de014cc.png)

what I'm not seeing this :eyes:

**Comment by OnyxFinger** [comment]
> > what sprite ???
> 
> learn to check commit history before answering
> ![image](https://user-images.githubusercontent.com/70016211/123309208-101da900-d53e-11eb-93a4-e02a0de014cc.png)

you should not have to check it.
if it isn't shown, then I'm not looking at it

**Comment by AzhurniyBaklan** [comment]
> you should not have to check it.
> if it isn't shown, then I'm not looking at it

then don't assume there is/was no sprite, we aren't answering for nothing

**Comment by BlueWolf3682** [comment]
Each of my messages are accurate in the time they were posted - I cannot account for editing and such. Please make sure to check the comment editing.

**Comment by Kryvytsky** [comment]
> > "mods" is not the answer
> 
> idk man it worked for me, i _am_ a mod dev

I think that's stupid. Then why Anuke add New naval unit or new planets for campaign if we have MODS? Why even Anuke update game, if we have MODS? Maybe he should drop development at V5?
I have no idea what mod you developed and maybe you talented person. But, I think "mods" is most dumbest answer ever someone can say.

**Comment by Humanoid-X** [comment]
~Omura~ I somewhat feel like this is OP, I mean, free units, free distraction?

**Comment by BlueWolf3682** [comment]
> > > "mods" is not the answer
> > 
> > idk man it worked for me, i _am_ a mod dev
> 
> I think that's stupid. Then why Anuke add New naval unit or new planets for campaign if we have MODS? Why even Anuke update game, if we have MODS? Maybe he should drop development at V5?
> I have no idea what mod you developed and maybe you talented person. But, I think "mods" is most dumbest answer ever someone can say. 

Anuke adds content because he feels like it. Literally why we have this stuff.

Mods are easy to make, and if you can't make one you probably shouldn't be suggesting new content anyways.

"Mods" is an easy answer to concepts and sprites that ***won't*** be added to the basegame, and at least someone is pleased anyways.

Now, if you want to *continue* being angry at this subject I suggest you check the likelihood of such bad sprites to be added to the game and come back to me later.

**Comment by Kryvytsky** [comment]
> 
> 
> Anuke adds content because he feels like it. Literally why we have this stuff.
> 
> Mods are easy to make, and if you can't make one you probably shouldn't be suggesting new content anyways.
> 
> "Mods" is an easy answer to concepts and sprites that _**won't**_ be added to the basegame, and at least someone is pleased anyways.
> 
> Now, if you want to _continue_ being angry at this subject I suggest you check the likelihood of such bad sprites to be added to the game and come back to me later.

I'm not arguing about quality of this sprites. This is "suggestion" page. Any person can suggest something to be in vanilla game. So I don't like your "mod" answer. Most mods are awfull. Most of them be like "let's take surge wall (or any other turret, unit, ect), change texture and make it deal more damage and more hp". So mod dealers not much better rather than players at suggesting content.

**Comment by itcannotbe** [comment]
Most mods are awful bacause most mod makers are bad.

And most suggestion especially unit suggestion don't make it to the base game. Because funny enough most unit suggestion are overpowered, mixtures of something already in the game, or extremely hard to balance.

So yes. Mods.

**Comment by Kryvytsky** [comment]
About curent suggestion. Summoner type unit's often used in Tower defence genre. But this would be OP in Mindustry. It's like free resourses and energy walking factory. We have already Omura, but it's T5 unit that built a T1 units.

**Comment by notMEEPoffaith** [comment]
you do know that resources are infinite, right?

**Comment by notMEEPoffaith** [comment]
but also this is too OP

**Comment by Ksawi999** [comment]
> but also this is too OP

If every spawned unit will have just few hp and do very small damage at very close range - it will be balanced.

**Comment by Kryvytsky** [comment]
> > but also this is too OP
> 
> If every spawned unit will have just few hp and do very small damage at very close range - it will be balanced.

No. If T2 units would spawn T1 units like crawlers and T3->T2 this would be too OP spam. Especially at PVP.

**Comment by Ksawi999** [comment]
> > > but also this is too OP
> > 
> > 
> > If every spawned unit will have just few hp and do very small damage at very close range - it will be balanced.
> 
> No. If T2 units would spawn T1 units like crawlers and T3->T2 this would be too OP spam. Especially at PVP.

Ok, let's count...
T5 -> T4 -> T3 -> T2 -> 2xT1
So we have 5 spawned units per T5, 4 per T4, 3 per T3, 2 per T2. That's number of spawned units per round (when chosen optimal number of spawners). I don't think that's OP spam.

**Comment by MauritanianMapping** [comment]
When you make a t5, spawning a free t4 is just ridiculous as a concept, also small and fast units tend to distract turrets, which means they can distract turrets enough to get troops like Reigns up close without taking much damage. Even then, T2s spawning t1s is simply OP since you have an infinitely regenerating source of units at no cost to you that you can keep back in the base with logic and now they are just nothing but free units, basically adds a unit source at very little cost that lasts the entire rest of the game. No thanks.

**Comment by Ksawi999** [comment]
> When you make a t5, spawning a free t4 is just ridiculous as a concept, also small and fast units tend to distract turrets, which means they can distract turrets enough to get troops like Reigns up close without taking much damage. Even then, T2s spawning t1s is simply OP since you have an infinitely regenerating source of units at no cost to you that you can keep back in the base with logic and now they are just nothing but free units, basically adds a unit source at very little cost that lasts the entire rest of the game. No thanks.

I think you still don't understand one thing. I don't mean an "infinitely regenerating source of units". Just few spawns per unit with very low reload speed.

`Spawners should have limited launches (for example first stage spawner should have only two launches) and very low reload speed.`

**Comment by MauritanianMapping** [comment]
> > When you make a t5, spawning a free t4 is just ridiculous as a concept, also small and fast units tend to distract turrets, which means they can distract turrets enough to get troops like Reigns up close without taking much damage. Even then, T2s spawning t1s is simply OP since you have an infinitely regenerating source of units at no cost to you that you can keep back in the base with logic and now they are just nothing but free units, basically adds a unit source at very little cost that lasts the entire rest of the game. No thanks.
> 
> I think you still don't understand one thing. I don't mean an "infinitely regenerating source of units". Just few spawns per unit with very low reload speed.
> 
> `Spawners should have limited launches (for example first stage spawner should have only two launches) and very low reload speed.`

Oh, even then there's the problem of still being able to completely puke low tier units at very little cost of both time and resources and also allowing you to have three times the t1s as unit cap is irrelevant, also this makes low tier flare units mostly irrelevant if you can just puke an immense number of units as flares and horizons would be much more expensive than the unit spam unit.

**Comment by OnyxFinger** [comment]
> > > When you make a t5, spawning a free t4 is just ridiculous as a concept, also small and fast units tend to distract turrets, which means they can distract turrets enough to get troops like Reigns up close without taking much damage. Even then, T2s spawning t1s is simply OP since you have an infinitely regenerating source of units at no cost to you that you can keep back in the base with logic and now they are just nothing but free units, basically adds a unit source at very little cost that lasts the entire rest of the game. No thanks.
> > 
> > 
> > I think you still don't understand one thing. I don't mean an "infinitely regenerating source of units". Just few spawns per unit with very low reload speed.
> > `Spawners should have limited launches (for example first stage spawner should have only two launches) and very low reload speed.`
> 
> Oh, even then there's the problem of still being able to completely puke low tier units at very little cost of both time and resources and also allowing you to have three times the t1s as unit cap is irrelevant, also this makes low tier flare units mostly irrelevant if you can just puke an immense number of units as flares and horizons would be much more expensive than the unit spam unit.

yes but these will easily get capped and also don't necessarily deal good damage

**Comment by MauritanianMapping** [comment]
Neither do flares, however these units can potentially spawn 48 flare equivalents (which by the simple fact of existing they distract turrets from more important targets) not counting the additional 24 you get with spawning the t1s the regular way. The balancing required for such a thing to be both viable and not eradicate the usage of flares would take so much work and tweaking that honestly it isn't worth putting in the game. Also this makes flare spam in the earlygame 30x more frustrating to deal with if you are not an experienced player, flares are annoying to deal with when you are unprepared, now multiply the problem times three and you have more unnecessary frustration.

**Comment by Ksawi999** [comment]
> Neither do flares, however these units can potentially spawn 48 flare equivalents (which by the simple fact of existing they distract turrets from more important targets) not counting the additional 24 you get with spawning the t1s the regular way. The balancing required for such a thing to be both viable and not eradicate the usage of flares would take so much work and tweaking that honestly it isn't worth putting in the game. Also this makes flare spam in the earlygame 30x more frustrating to deal with if you are not an experienced player, flares are annoying to deal with when you are unprepared, now multiply the problem times three and you have more unnecessary frustration.

`That unit should be worse than flare` (added to description)
We aren't writing about unit balancing, we are writing about new content. I can't provide 100% guarantee that content will be added to the game and I can't provide 100% guarantee that the unit will have the same stats that I want. Everything is in hands of Anuken. If you want, I will write indicative statistics or make in 100% balanced mod that will add these units.

**Comment by MauritanianMapping** [comment]
Honestly the spawning attribute that you have suggested just seems rather pointless to include in the game if all it does is the Russian Doll thing, can you please give a proper reason to why this should even exist in the first place?

**Comment by Kryvytsky** [comment]
> Honestly the spawning attribute that you have suggested just seems rather pointless to include in the game if all it does is the Russian Doll thing, can you please give a proper reason to why this should even exist in the first place?

This would be a Russian Doll thing if units would spawn smaller units after death.
But he suggest a summoner thing. Even if you make spawn time quite long. This would still be OP  units spam at PVP. While in survival that units would be useless cuz they would die very fast.
He suggest this as new content, but at my perspective this is broken at state of concept.

**Comment by Sh1penfire** [comment]
ok let me make this clear
Free units is not something you might want to give the player, mods or not. Omura is a t5. At that point, producing flares is practicaly free, so it isn't detrimental to the game in any way.

Everything has it's uses somewhere, and I'm sure you can and will see those usages by playing around with Omura's flares for a bit.

Mods are an answer. Most mod makers try their hardest to make content, and who can blame them if you think their content sucks. We're striving for improvement, and we're learning new things sometimes even every day. I myself am a mod maker, and I put effort into my work, so if it is bad you can feel free to say so. Same with other mods, be proactive in your want for better content.

As for why we are getting Support navals, one does not simply answer with their own interpritation. If it is directly asking about why and only why a person added it, and you have no comfimred answer, then maybe considder asking, or getting help from others.

One more thing, Quantity is not greater tahn Quality in mindustry's design. Most if not all units have been rebalanced, and polished off and theres still some blemishes with vanilla units. Learn to deal with it. Learn to use what is already present. Mindustry is not just another Tower Defense game, and thus it's difrent from others in varius ways, including it's balancing. If Anuke were to add new units, he should do so when he has time, and when he feels like it. Adding these new unpolished units wuld only delay future releases and present more confusing clutter in the database.

Please excuse my grammer.

**Comment by OnyxFinger** [comment]
> Neither do flares, however these units can potentially spawn 48 flare equivalents (which by the simple fact of existing they distract turrets from more important targets) not counting the additional 24 you get with spawning the t1s the regular way. The balancing required for such a thing to be both viable and not eradicate the usage of flares would take so much work and tweaking that honestly it isn't worth putting in the game. Also this makes flare spam in the earlygame 30x more frustrating to deal with if you are not an experienced player, flares are annoying to deal with when you are unprepared, now multiply the problem times three and you have more unnecessary frustration.

flares are weak af, if you need high-ish tier units to get a lot of them, they won't have much effect. However I agree spawning a T5 is a quite ridiculous concept, maybe the T5 should spawn like a 3.5ish kind of unit.
As I said, units making units of the same tree should be avoided, because else everything will become laggy af, unless the unit limit is capped very low, like 24, where players can just counter anything with conveyor spam anyway, so it would be shit gameplay still.

> Honestly the spawning attribute that you have suggested just seems rather pointless to include in the game if all it does is the 
> Russian Doll thing, can you please give a proper reason to why this should even exist in the first place?

Making units more diverse, he has given a reason, which is proper, since this is generally very good if well balanced, as in very cool, which is basically what a game needs : coolness, good gameplay (balance+concepts).
It would also help diversify gameplay. I have no idea why this idea has no reason to exist.
