### ISSUE TITLE
add a bigger message block

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2606]
**Describe the content or mechanics you are proposing.**
add a block called announce, which is just a bigger message (with more text limit)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
a
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
"a" is a terrible reason. That section is there for a purpose. Use it correctly. On Jun 24, 2021 9:47 PM, vinhsad ***@***.***> wrote:
Describe the content or mechanics you are proposing.
add a block called announce, which is just a bigger message (with more text limit)
Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
a
Before making this issue, place an X in the boxes below to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

 I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

 I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

 I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> a

***Boi if ya dont use that correctly anuke gonna reap your soul***

**Comment by Humanoid-X** [comment]
Why lol.. I think massage store infinite text isnt it?
Also there is something sus about Kylingene's post lol...

**Comment by vinhsad** [comment]
> Why lol.. I think massage store infinite text isnt it?
> Also there is something sus about Kylingene's post lol...

a message has a limited text amount .-. 
(limit -> texts: 220, lines: 24)

**Comment by Ksawi999** [comment]
> (limit -> texts: 220, lines: 24)

Is it not enough for you? If you want to write more just build more messages... Bigger message block would be useless and no one would spend resources for it.

**Comment by parkuristt** [comment]
> a
