### ISSUE TITLE
big enemy base 

### ISSUE THREAD

**Issue by Farras-Fadhil** [Anuken/Mindustry-Suggestions#2607]
A large enemy base protected by a large wall as seen from the planetary map. And there are several entrance gates (North, South, West, East entrances) which are guarded by the enemy base. 

After defeating a large gatekeeper enemy base ... There are many enemies and various unique resources.

And for expansion/control of the planetary area it is necessary to control one sector (NETWORK TOWER SECTOR) Which can increase the maximum range to dominate sectors in other parts of the planet. 

And 1 planet full of enemies ...so if there is 1 planet near the planet where the enemy is can be attacked massively

**Comment by Hyrotrioskjan** [comment]
template please

**Comment by oinkymoo** [comment]
cool idea but it kinda already exists in the form of serpulo's north pole

**Comment by notMEEPoffaith** [comment]
use level editor to make this.

**Comment by oinkymoo** [comment]
> use level editor to make this.

they are suggesting something of a planetary scale, not the scale of a single sector
