### ISSUE TITLE
ducts on space tiles

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#2608]
**Describe what you would like changed, and why.**

it would be neat if duct pipes/bridges/routers could be placed on space tiles (e.g. debris fields)

**Describe the changes you want to propose. Include possible alternatives.**

the enviroment mechanic is still fairly unknown in this pre release state of 7.0, and it would simply be neat for them to work in space themed maps like that since from what i understand that is the sort of environment they're supposed to function in 🤔

**Comment by USMP-lancer** [comment]
i agree in "space" maps the tiles will mainly be the tile of the same name, so unless you use mass drivers it would be hard to get a transport line without using any sort of unit logic, maybe there should also be aquatic conveyors for aquatic environments?

**Comment by itcannotbe** [comment]
Let's probably wait 'till the environment it meant to be use actually exist.

**Comment by Anuken** [comment]
It seems strange to have ducts be floating around in space with a shadow and nothing supporting them.

**Comment by USMP-lancer** [comment]
true

**Comment by hribik100** [comment]
> It seems strange to have ducts be floating around in space with a shadow and nothing supporting them.

they're are levitating with some future technology

**Comment by USMP-lancer** [comment]
> > It seems strange to have ducts be floating around in space with a shadow and nothing supporting them.
> 
> they're are levitating with some future technology

or, you know, the lack of gravity

**Comment by Humanoid-X** [comment]
hmmm need to somehow disable shadows in on spaceetiles which is hard
