### ISSUE TITLE
Unit Command Change

### ISSUE THREAD

**Issue by PASyther** [Anuken/Mindustry-Suggestions#2609]
I think command buildings should be linked to factories so you can independently tell certain units to rally, idle or attack. Have the default behavoir be the normal pathfind and if they are not hooked up to a command centre they'll just be on default attack behaviour. Otherwise, have it so you can determine which units are affected by command centres.

This is mostly to help with logic based setups.

**Comment by oinkymoo** [comment]
1. template please
2. how do factories relate to which unit you are commanding?

**Comment by itcannotbe** [comment]
I'm pretty sure this would add additional configuration to factories.
