### ISSUE TITLE
Pause while hosting

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#261]
**Describe what you would like changed, and why.**
Now don´t misunderstand me-
I´m not asking for you to make it possible to pause while in multiplayer,
that being removed is a great idea. I´m asking for the ability to
pause the game until player two joins. This will help with the maps with waves and things happening
from the beginning. While you wait, it could already be too late when somebody joins because for steam players
it can take ages for someone to join. Having the ability to pause the game until you want to actually start it would be awesome!

**Describe the changes you want to propose. Include possible alternatives.**
Another method would be integrating a game pause while in **"WAITING FOR PLAYERS"** mode for PvP matches.
another thing on the side, it would be cool to have the ability to select what team you join when intering a match with even players.

**Comment by xamgore** [comment]
The issue still matters though.
