### ISSUE TITLE
Vehicle Units

### ISSUE THREAD

**Issue by PASyther** [Anuken/Mindustry-Suggestions#2611]
**Describe the content or mechanics you are proposing.**

A set of vehicular units to be added to the ground factory designed around quick movement/long range combat and general beef. Would probably use Plastanium as their T1 resource
Examples:

T1 - [Nail] Jeep. Fast moving with a weak weapon and build capabilities

T2 - [Spanner] Missile Car. Either anti air only or long range anti-all (Similar range to the hail)

T3 [Hammer] - Tank. Heavily armoured with Mid range cannon and little to no anti-air

T4 [Anvil] - Artillery. Long range artillery (possibly like the foreshadow) with a long cooldown and no anti-air

T5 [Blacksmith/Forge] - Landship. Heavily armoured with multiple mid to long range cannons and short range forward-facing fuse-like shotguns. Could possibly have a scatter near it's rear. Very very slow.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think the idea of a vehicle factory in general would fill an aesthetic niche, and that the units themselves could fill pre-existing holes in unit formation. We lack long range units or anti air units as well as having a true tank to penetrate super heavy fortifications with. I think having a slothlike T5 would be a good unit to rally behind as it sponges all the shots from gunwalls. It would also be a really fun boss to fight against. I noticed that the general vibe for units tends to be that each of the first 3 upgrades are entirely different, and then the 4th and 5th tier units and improvements on the 3rd. Also their naming schemes tend to be based on a theme without being super strict about what those names could be.

A fast moving land builder would serve as a quick alternative to the poly (for players to control) early on and would allow them to be more flexible. (In general Player characters only need to worry about scatters in the early game. This also applies to PVP where scatter bubbles kinda just kill PVP early on. This is a good thing in some cases but tends to stifle combat until much later).
This same Land unit would also serve as a skirmisher to harass undefended or weakly defended areas in a similar way to the flare.
IT would not be overpowered because it's weapon would be weaker than it's dagger counterpart and would therefore only be used in conscious attacks - not as a default rush unit.

A long range land unit is seriously needed, but that role could be filled by the T4 (in my example). Having an anti-air unit seems like a simple choice, and while I understand that a lot of units serve as anti-air by simply shooting everything, I think a Surface to Air vehicle would be a nice addition to the game - serving as a mobile area denial tool for more flexibility in combat. It would also give you reason to make multiple command centres, since they essentially tell units to guard an area.

A big ol' beefcake unit would be nice, though I understand this is roughly the Fortress. I feel like a set of vehicles needs to have a tank unit, but I'm not sure how to make it not the Fortress. You could give it longer range and lower firing time on its main gun, or could give it a weak Duo for AA and close range support. I'll admit this is the weakest link in the chain

Artillery is powerful, but with the addition of the segment I'd say it is no longer king in Mindustry. A mobile artillery unit would be a very nice fit to the game, allowing players to poke and prod at areas to test defences - increasing the validity of segments. I feel as though this unit should be very weak in close range or surface to air combat to compensate for the power in having a mobile artillery, further incentivising synergy with the previous tiers of unit, which I again think would add a lot more complexity to combat. With this in mind, I know the foreshadow is the current go to long range gun, but I really think a super-long range artillery Turret would fit really well in game. The existence of the segment again means it won't dominate, but it would really allow you to put pressure on enemies who turtle up into little impenetrable baseforts. I don't know how easy it would be to do, but I like the idea of it needing Blast Compound or Pyratite to fire much like how the Meltdown needs some form of Liquid to fire.

Lastly, I think we just need some sort of moving wall unit. Something to give you that sense of awe as it slowly makes it's way through. It doesn't even need to be very offensively powerful. I think this would not only be a fantastic boss to fight against in the campaign or in regular custom games, but would serve as a frontline shield for your own units as well. You could give it a forcefield instead of the scatter to really hammer in the idea of it being a supportive wall to help your other units move in.
In a lot of ways the oct does a similar job, but nothing really conveys this idea of a true titan yet, and the Landship would be a ground based head-to-head unit where the oct is instead an avoidance unit. Slap a unit factory on it for extra credit.

All in all I just think it would be neat to have some cars to go beep beep.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

(I was going to suggest a unit cannon like in PAT but then I saw this last part and knew it would never be)

**Comment by itcannotbe** [comment]
Making the T1 use a later game resources won't properly gate making the units early.

Also do you even know how reconstructors work?

**Comment by itcannotbe** [comment]
> I think we just need some sort of moving wall unit.

Where's my oct?

**Comment by itcannotbe** [comment]
> A long range land unit is seriously needed

No. This is extremely hard to balance.

**Comment by oinkymoo** [comment]
>  as well as having a true tank to penetrate super heavy fortifications with

we already have this. its called a reign. eclipse can also do it.

**Comment by oinkymoo** [comment]
your description of blacksmith just seems like a combination of reign and oct

**Comment by itcannotbe** [comment]
> > as well as having a true tank to penetrate super heavy fortifications with
> 
> we already have this. its called a reign. eclipse can also do it.

You forgot corvus.

**Comment by MauritanianMapping** [comment]
This sounds like little more than adding generic shit for the sake of adding generic shit, Mindustry has mechs, it might be good with mechs on treads with certain advantages and disadvantages, but they wouldn't be like irl vehicles because this game is not about generic Earth stuff.

**Comment by oinkymoo** [comment]
> > > as well as having a true tank to penetrate super heavy fortifications with
> > 
> > 
> > we already have this. its called a reign. eclipse can also do it.
> 
> You forgot corvus.

corvus has not great health compared to other t5s and is pretty much completely countered by plast walls. eclipse is too, but not as much

**Comment by itcannotbe** [comment]
> > > > as well as having a true tank to penetrate super heavy fortifications with
> > > 
> > > 
> > > we already have this. its called a reign. eclipse can also do it.
> > 
> > 
> > You forgot corvus.
> 
> corvus has not great health compared to other t5s and is pretty much completely countered by plast walls. eclipse is too, but not as much

I mean it does penetrate defenses easily some exceptions, but it's health is one way of making it kinda balanced.

**Comment by PASyther** [comment]
"Making the T1 use a later game resources won't properly gate making the units early."

Fair argument. I came up with the idea to use Oil instead since you can get that earlier and it'd probably be more fitting, but the resource used can be easily adjusted.

"Also do you even know how reconstructors work?"

Not sure what you mean.

"Where's my Oct?"

Fair argument but the Oct does nothing in survival mode.

"we already have this. its called a reign. eclipse can also do it."

Both those units get turned into swiss-cheese by a pair of spectres.

"your description of blacksmith just seems like a combination of reign and oct"

You forgot Omura

"This sounds like little more than adding generic shit for the sake of adding generic shit, Mindustry has mechs, it might be good with mechs on treads with certain advantages and disadvantages, but they wouldn't be like irl vehicles because this game is not about generic Earth stuff."

Just because it's generic doesn't mean it's bad. Also as I mentioned in my suggestion those were just examples of what vehicular units COULD be - not what they SHOULD be. If anyone has better ideas for what they'd be and look like feel free to suggest them.

"I mean it does penetrate defences easily with some exceptions, but it's health is one way of making it kinda balanced.

So no, thick health and massive firepower won't be balanced if put in the same unit."

Did you forget about movement speed and range? If you've played some other games you'd know that those factors are often more important than damage and durability.

**Comment by Humanoid-X** [comment]
no unless #2019 #2020 #2021

**Comment by itcannotbe** [comment]
especially #2020

**Comment by Toxopid82** [comment]
huh this is cool
