### ISSUE TITLE
Show core no-build zones in the level editor and in map previews

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2612]
**Describe the content or mechanics you are proposing.**

Add a way to view the core no-build zones without having to go in the in-game editor, maybe as a toggleable option, as well ason the level preview, though I'm not sure about that one because it may cause clutter

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Makes map making quicker.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
you can't even see no build zone in the ingame editor, so yeah I'd like this
