### ISSUE TITLE
Allow Logic to see where units are currently building or to ULocate specific blocks

### ISSUE THREAD

**Issue by WHITED4WN** [Anuken/Mindustry-Suggestions#2613]
**Describe the content or mechanics you are proposing.**
Currently polys can help the player build, but in an attempt to get my megas to do the same via logic, i found out that the game lacks any way to see where a unit is currently building, and ulocate doesnt allow me to instead search for @build1 @build2 etc, as it cant search for “under construction” 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will allow us to create logic to replicate polys, but with better faster builders

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by USMP-lancer** [comment]
basically, allow logic to ulocate build1-16, so we can have other units have mega like ai, along with a way to better specify what they locate

**Comment by USMP-lancer** [comment]
maybe even let us define a list of tiles they locate

**Comment by USMP-lancer** [comment]
too crusty lmao
