### ISSUE TITLE
Solid Colour Floor

### ISSUE THREAD

**Issue by PASyther** [Anuken/Mindustry-Suggestions#2615]
**Describe the content or mechanics you are proposing.**

A floor that is just a single grey colour or possibly could have an RGB system attached

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I recently tried making a space station map and found the metal tiles to be too garish to use as a floor. The stone floors don't really make much sense, so I'd like to have a flat single colour floor to use in that type of situation.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
The RGB idea might be a little much, but a solid color tile would be really easy to do; however, this is a perfect "mods" thing.

**Comment by itcannotbe** [comment]
Map tiles that have nothing else but a plain color is bland and painful to look at in the long run.

**Comment by Humanoid-X** [comment]
i dont feel like this fit in vanilla so mods
