### ISSUE TITLE
Belt Upgrader tool

### ISSUE THREAD

**Issue by Dwal32s** [Anuken/Mindustry-Suggestions#2616]
Basically just the upgrade planner from factorio to reduce time replacing belts.
Currently when you unlock titanium belts, you need to spend a good 30 minutes upgrading standard belts to titanium ones, and this would dramatically reduce the time.
It could function similarly to the selection/delete tool where you press a key and it makes a box outline

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Already added. Enable diagonal placement and drag from conveyor belt

**Comment by itcannotbe** [comment]
Well no. The use case is just stupid.

Who even makes that many regular conveyors to for you to justify spending 30 minutes to upgrade them all in the first place?

And if you properly use regular conveyor (no bottlenecks) upgrading them is basically pointless.

**Comment by itcannotbe** [comment]
> Already added. Enable diagonal placement and drag from conveyor belt

That's a different one that OP requested but also. A tool solely made to upgrade regular conveyors to titanium conveyors? Seriously?

Also see comment above.

**Comment by Dwal32s** [comment]
itcannotbe: The main use would be for the campaign when you have a couple sectors with nothing but titanium belts, instead of multiplayer servers.

Yell: thanks for making that clear as currently the game doesnt tell you that directly.

**Comment by Dwal32s** [comment]
Going to close this as I did not realize that belt pathfinding has a very similar feature.

**Comment by itcannotbe** [comment]
> The main use would be for the campaign when you have a couple sectors with nothing but titanium belts, instead of multiplayer servers.

Well no. The use case is just stupid. Who even makes that many regular conveyors to for you to justify spending 30 minutes to upgrade them all in the first place? And if you properly use regular conveyor (no bottlenecks), upgrading them is basically pointless.
