### ISSUE TITLE
[Discord] Stop posting stupid things on schematics channel

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2617]
**Describe what you would like changed, and why.**

All have seen the schematics channel. 1 of 10 is an actual schematic, all rest are some jokes, or just really bad designs. I propose someone to delete such things, as is done on art channel. If I want to find an actually working schematic, I gotta scroll for miles or search and then scroll for miles.

**Describe the changes you want to propose. Include possible alternatives.**
Essentially: add a warning not to post jokes and memes. Mute people who post that after a warning.

**Comment by OnyxFinger** [comment]
problem : players might put a schem they find good and in reality isn't, then not understand why it got removed

**Comment by genNAowl** [comment]
In my opinion the problem with the schematics channel is the community of people that use it, clearly shown through the horrible schematics and toxic reactions.

There is no one willing to moderate this channel, and there is no written rule saying all schematics in that channel have to be **good** schematics, and I don't think there is a clean way to fix the problem currently. 

My advice? Don't look in there for good schematics. Instead, go to #designs, find a few good schematic creators, and look up the schematics they have posted. (I would suggest Sirius, 🍿, and maybe a few others)

**Comment by DestroyerXL44** [comment]
Has something like a starboard ever been suggested before to solve this issue? This could be a possible alternative to just cutting out bad stuff - starred schematics (and any other sort of player-made stuff, if it were implemented in other channels like maps) would be chosen by the community, and would easily create a "best of" channel highlighting what people think is good while not causing the issue of manually clearing out what isn't.
