### ISSUE TITLE
Anti air artillery

### ISSUE THREAD

**Issue by BoultonPaulDef** [Anuken/Mindustry-Suggestions#2619]
**Describe the content or mechanics you are proposing.**
I think that it would be cool, if there will be cannon, that can only attack flying and shoots not so fast/slow dealing big damage and on big area.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will add more only anti air cannons, not only two, and add more strategic option to attack enemy from different directions not to make splash damage destroy your army.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
there is already the scatter, however, I do believe that we need more anti air cannons

**Comment by BoultonPaulDef** [comment]
> there is already the scatter, however, I do believe that we need more anti air cannons

Yes, but scatter is a mashine gun, and i am talking about something more artillery like

**Comment by Ineedause** [comment]
I see, something like the foreshadow but for air

**Comment by BoultonPaulDef** [comment]
More like hail with bigger splash damage

**Comment by MrDuck557** [comment]
Single-projectile AA defeats the purpose

**Comment by Kyllingene** [comment]
Why on earth would you like a single-shot turret to try and counter swarms of flares? Air units are inherently either smaller, or have heavy-damage-resistance shields. Scatters and parallax' work fine.

**Comment by BoultonPaulDef** [comment]
> Why on earth would you like a single-shot turret to try and counter swarms of flares? Air units are inherently either smaller, or have heavy-damage-resistance shields. Scatters and parallax' work fine.

That why i want spash damage

**Comment by RouterChainsSuckk** [comment]
think about how unrealstic that would be,  if you want aoe then plast cyclone or meta scatters

**Comment by BoultonPaulDef** [comment]
> think about how unrealstic that would be, if you want aoe then plast cyclone or meta scatters

Are you talking about realism in game where you build planes from lead

**Comment by RouterChainsSuckk** [comment]
> > think about how unrealstic that would be, if you want aoe then plast cyclone or meta scatters
> 
> Are you talking about realism in game where you build planes from lead

sure why not with advanced enough engines, 30 lead isn't very specific to real world weight, what if its 30 tons of lead

**Comment by itcannotbe** [comment]
> > Why on earth would you like a single-shot turret to try and counter swarms of flares? Air units are inherently either smaller, or have heavy-damage-resistance shields. Scatters and parallax' work fine.
> 
> That why i want spash damage

Hold my swarmers.
