### ISSUE TITLE
Introducing: the Enforcer 1x1 tower

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#262]
**Describe the content or mechanics you are proposing.**
I suggest a teleporting train.
Jk, that would be awfull. I would like to see a new small tower in mindustry, called the enforcer.
Here are the stats, purpose will be discussed in the next section.
----------------Enforcer
A essential mech defense usefull for small amounts of targets with even the best pilot.
General
Health: 300
Size: 1x1
Build Time: 1.1 seconds
Build Cost: 15(copper) 60(lead)
Power
Power Use: 175 power units/second (1400 per shot that is, shot is fired instandly, power is drained while loading)
Shooting
Range: 40 blocks (below 50, the range of omega)
Inaccuracy: 0 degrees (it´s a sniper turret shooting a lancer like projectile, blocked by shields and not penetrative to plast walls)
Shots: 1
Shots/Second: 0.125 (it´s purpose is to eliminate a single target, not many units)
Targets Air: Yes
Targets Ground: Moving (Making it only target moving units/mech will balance the range, it won´t attack structures)
Damage: 400 (Enough to kill any mech, except for the Omega in damage reduction mode) (dps=50)
Optional Enhancements:
Booster: 1 Surge Alloy (per shot)
Surge Alloy: +50% Range, -100% firing cost (will outrange anything, change the beam colour to yellow and not need power lines)
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Every tower has it´s own purpose in mindustry ranging from close range titan/ghoul slayer to far ranged artillery gun,
There is one part that is barely covered by the turrets: player defense. I guess that is because PvP wasn´t the main concern of the tower balancing. While mech aren´t all too powerfull, they can be very annoying to deal with and cripple your economy. As a mech, you can easily dodge artillery in ground mode and with ships you can outrange the wonderfull scatter turret by using your speed to launch bullets faster. Dealing with attacking players is frustrating, there aren´t enough options to defeat them with large coverage, the cyclone or spectre would be your best bet but it is very expensive to build, big and needs ammo.
The only affortable things really protecting from players right now are scatters and lancers wich both aren´t too reliable.
This suggestion doesn´t just bring something cool and interesting, it helps with balancing and would have a good place in the game. Thank you for reading my suggestion. I love mindustry and would love seing it improve even further :D

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

I hope you can see how this would benefit the game dear anuken, your game is wonderfull and I´m glad if I can help improve it.
Sincerely, Dark_slayer3000
if used, credit is optional but much apprechiated. If you are a player making a mod out of this, that would be nice too :D
Here are some dumb screenshots of me attemting to dodge towers xD It can be reliable in most cases :D 
![D 20200626202042_1](https://user-images.githubusercontent.com/60404347/85889135-2a1d9200-b7eb-11ea-85b6-7615ad4307f6.jpg)
![D 20200626202214_1](https://user-images.githubusercontent.com/60404347/85889139-2b4ebf00-b7eb-11ea-9372-cdf3543dfd7d.jpg)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
I hope this seems reasonable and fair eventhough it is a bit unusual due to the new targeting, amunition and projectile.

**Comment by Violet-Scarelli** [comment]
I would suggest:

-  That surge drops its power drain by 75% but doesn't remove it entirely. 

- That it should take some silicon and titanium to build instead of just copper and lead, so that it's not entirely accessible. 

- That it shouldn't instantly kill players, only deal large amounts of damage (100 damage/shot instead of 400).

**Comment by itcannotbe** [comment]
You do realize that that's almost like an arc turret and the fact that players will have no distinction between units in terms of what is a unit and what are player since mechs are no more and players can be a unit/control a unit.

Also not many units have their HP about 100. In short the damage you propose will still one shot units.

**Comment by Anuken** [comment]
This is *insanely* overpowered. It's basically a 1x1 lancer with **three times the damage** and practically no build cost.

**Comment by DS-3K** [comment]
At the time I didnt have a clue how to game design
