### ISSUE TITLE
nerf repair turret

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#2620]
**Describe what you would like changed, and why.**
it is simply too good for how cheep it is, especially when combined with water (witch is easy to get)

**Describe the changes you want to propose. Include possible alternatives.**
make it repair things 10-25% more slowly or nerf range by the 25%

**Comment by RouterChainsSuckk** [comment]
![image](https://user-images.githubusercontent.com/73048252/123526969-613db200-d690-11eb-845e-6ef71ac7f7b1.png)
 2 repair turrets with water solo keeping this naval unit alive when getting shot at by 2 foreshadows and a few plast ripples (all cryo overdomed)

**Comment by Humanoid-X** [comment]
Whoa.. forshadow...

**Comment by GruveXp2** [comment]
Don't make it slower if its gonna be nerfed make it more expensive
