### ISSUE TITLE
Potential RTG rebalance

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2621]
**Describe what you would like changed, and why.**
RTG's buildcost (and, as a counterbalance, the power generation) - RTG is pretty much useless right now, mostly due to the build cost

**Describe the changes you want to propose. Include possible alternatives.**
Make RTGs not cost phase fabric and cost less plastanium, perhaps also lower their power generation 270->240 as a counterbalance?
Alternative: remove the phase cost *as well as* the plastanium cost, but counterbalance the power generation even further: 270 -> 180?

**Comment by BorisA11** [comment]
RTG is almost free power. It takes 15s for one thorium and no cryo. That makes it ultra efficient. I personally always use them, ans that cost aint so bad in late game.

**Comment by RouterChainsSuckk** [comment]
I already suggested this minus the No plast cost and everyone said it was stupid....

**Comment by Humanoid-X** [comment]
NOOOOOO RTG IS ALREADY SO BALANCED NOW

**Comment by Ilya246** [comment]
> 
> 
> RTG is almost free power. It takes 15s for one thorium and no cryo. That makes it ultra efficient. I personally always use them, ans that cost aint so bad in late game.

Not quite - right now RTG is actually less efficient that thorium reactors, which are way easier to spam and take up WAY less space

**Comment by oinkymoo** [comment]
they're way easier to use tho

**Comment by genNAowl** [comment]
It's true, compared to thorium reactors, RTGs are worse; I still use them though as a way to turn thorium to power because I still haven't gotten used to using thorium reactors (They explode too much)

Yes, I know there is logic now, but I developed this fear in v5

**Comment by oinkymoo** [comment]
i picked the game up in like, march, and i also don't use reactors, just cuz of the convenience
