### ISSUE TITLE
Armor Ability 

### ISSUE THREAD

**Issue by AureusStratus** [Anuken/Mindustry-Suggestions#2622]
An ability that can be used on mechs, leg, air and naval

looking back at v5 the omega had armor which was kinda cool but has now been replaced with things like shields or force fields but i want this to come back possibly in v7 

so the ability will only active when ever the unit is in combat so when ever it is firing its weapons and the ability will add an amount of extra armor points to the unit whenever it is active and the armor could have a chance at deflecting bullets or absorbing energy bullets and the armor itself would have a set amount of health and when the armor is killed the unit will lose the protection of the armor unit it get replenished i think this would be great for modding and also close ranged units and as for what could be edited 

armorHealth: The armors health
armorCooldownTime: The time it takes for the armor to come back
armorRegenration:  How much of health it recovers
armorRegenraionTime: The time it take for the armor to recover lost health
armorAmount: The armor that is add to to unit when the armor ability is active
canDeflect: Whither the armor can deflect bullets or not
deflectChance: The chance that the armor has of deflecting a bullet
deflectSound: The sound the armor makes when a bullet is deflected
deflectEffect: The effect the armor makes when a bullet is deflected
canAbsorb: whither or not the armor can absorb energy bullets
armorBreakEffect: the effect of the armor being broken
armorActiveEffect: the effect the armor makes when it is activated

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Maybe make it activate when unit isn't moving? It would be more balanced, I think

**Comment by itcannotbe** [comment]
Do we even really need this? Some Higher tier units already some form of damage reduction already.

**Comment by AureusStratus** [comment]
the ability isnt just ment to make units a bit more tank you could for example make unit specialized with in dealings with energy heavy defenses or bullet heavy defense and yes units do have an armor value but this isn't like that

**Comment by MrDuck557** [comment]
I can't see any shortcomings, but I can't see a niche either
I don't think anyone differentiates between energy or bullet turrets (unless mod factions)
And apart from that, you can simply make a tiny force field to simulate this
