### ISSUE TITLE
units clogging the core

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry-Suggestions#2624]
**Describe the problem**
units are causing lots of collisions and are running into one another at the core blocks 
They are all programmed to gather resources at the core

**Describe the changes you want to propose. Include possible alternatives.**
1. add transport type unit designed to take large amounts of items from a single block
2. allow logic to disable collisions (maybe denied under some conditions)
3. disable collisions when in radius of core and/or high traffic blocks
4. include anti crowding in logic commands

**Comment by MrDuck557** [comment]
Not the dev's business, if you overused unit transport logic it's your problem

**Comment by oinkymoo** [comment]
in my experience at least its much more of an issue on servers. also use approach so they aren't all going to the exact same spot

**Comment by Nhimanss** [comment]
> Not the dev's business, if you overused unit transport logic it's your problem

I would love to solve the problem with logic but... logic cannot communicate with other logic across the map to a central unit manager logic. forcing logic devs to make logic that can only think about its own unit

**Comment by MrDuck557** [comment]
> forcing logic devs to make logic that can only think about its own unit

And does that stop them from being able to be compatible with other code? No it does not

**Comment by Nhimanss** [comment]
your right
better idea in my opinion is to add AI to the travel commands

**Comment by MrDuck557** [comment]
> add AI to the travel commands

Like how
