### ISSUE TITLE
Make Reign walk over routers and power nodes

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2625]
**Describe what you would like changed, and why.**
It's annoying when you control Reign and get stop by router, liquid router, power node. Also this looks stupid that such big mech could be stoped by little obstacle. 

**Describe the changes you want to propose. Include possible alternatives.**

I have 2 solutions.
1) make router and node walkable like conveyor and conduit. Than any unit will be able walk over them. 
2) make Reign walk over any 1×1 block (like walls, turrets, terrain block). This would make him depend less on environment.

Also maybe Scepter need such change too? This unit is quite big too.

**Comment by Humanoid-X** [comment]
What about router chains or very solid but one block terrains

**Comment by OnyxFinger** [comment]
also junctions
