### ISSUE TITLE
non combat units wander into danger zones

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry-Suggestions#2626]
**Describe what you would like changed, and why.**
non combat units (such as the poly) will wander into areas that guarantee destruction, even in low health causing units to be wasted.

**Describe the changes you want to propose. Include possible alternatives.**

1. for non combat units add turret avoidance system
2. for non combat units add enemy avoidance system

**Comment by MrDuck557** [comment]
what version are you on
BuilderAI already has retreating, but MinerAI doesn't

**Comment by Kryvytsky** [comment]
Poly and Mega already can retreat to core if enemy is nearby

**Comment by oinkymoo** [comment]
enemy monos, however, will gladly wander into range of a foreshadow running off my core
