### ISSUE TITLE
Colourblind accessible option

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#2628]
**Describe the content or mechanics you are proposing.**
Option to show the team icon (when that's a thing for all teams) next to the player's name.
Alternatively, an option to shift the team colours to fit a colourblind pallete.

Probably not worth the effort for game modes with more than 5 teams.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Accessibility.

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JrTRinny** [comment]
maybe a shape like triangle for crux and diamond for green. that would be great
