### ISSUE TITLE
Sector production and export resetting when entered

### ISSUE THREAD

**Issue by yesthemass** [Anuken/Mindustry-Suggestions#2629]
**Describe what you would like changed, and why.**
A sector's production/export in the Stats screen reset when you enter it. This is very annoying when you're trying to capture Eradication level attack maps, eg. the silicon needed won't be importing from a silicon export sector.

**Describe the changes you want to propose. Include possible alternatives.**
1. Implement an x-second period that keeps the previous production/export stats
2) Don't calculate the production/export per second

**Comment by itcannotbe** [comment]
Launch pad exports don't work like that.

**Comment by oinkymoo** [comment]
its per minute anyways? per second would be dumb when you only launch once every 20 seconds

**Comment by Kyllingene** [comment]
What do you mean? Honestly, I am struggling to figure out your intentions, as I am sure merely entering a sector does not stop its exports, nor does entering its stats screen.

**Comment by yesthemass** [comment]
Well it stops the exports for me and some other people when entering.
