### ISSUE TITLE
Alarm structure

### ISSUE THREAD

**Issue by Gaizka39** [Anuken/Mindustry-Suggestions#263]
the block ( which I will call "the observer ) sends a notification shown on the top of your screen ( similar to the " your core is under attack " notification ), when a block in the observer's range takes damage or is destroyed.

**Comment by zethnest** [comment]
I guess this "Block" should be named something like outpost.

**Comment by Remint32** [comment]
> 
> 
> I guess this "Block" should be named something like outpost.

how about "observer"?

**Comment by Gaizka39** [comment]
observer sounds great!

**Comment by jaygamer81** [comment]
Ngl not bad. Maybe it would call all units on patrol to its location when block is broken.

**Comment by vsmelov** [comment]
Maybe it's possible to place a lot of ligh lamps all over the map and change their color using the processor block somehow?
