### ISSUE TITLE
Surge Wall Buff

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2630]
**Describe what you would like changed, and why.**

We all know surge walls. Pretty tough, and it has a unique ability to zap enemies in close range. But why wasn't it frequently used? Because of its lame supporting function.

Surge walls repels neither laser beams, nor bullets. So the walls still remain standing (due to its sturdiness) while everything behind it was already destroyed. 

20 damage is too weak, it can just deduct 1/7 health of a dagger. Plus it's rarity of spawning arcs is pretty much useless since it was supposed to be useful in close range. 

I'm proposing a revamped surge wall, that has the ability to spawn electric arcs with 200 damage (its okay since surge alloys are hard to mass produce, 200 damage is rewarding due to its cost) 
But has a 20% chance of spawning one when triggered. 

Lightning length will also be increased to 15 (almost half the range of arc's lightning range) 

**Why?**

- Currently, surge walls are a waste of resource to build, very ironic due to its expeniveness. 
- It's just an upgraded (+400 HP) thorium wall, while the lower end ones were cheaper to build. 
- Surge walls should also be functioning the same as how plastanium walls and phase walls work, because those are late game walls for defense.

**Comment by RouterChainsSuckk** [comment]
It has the most hp also it's used a shit ton in multiplayer (look at cn lategane runs if you cant find em anywhere else)

**Comment by BorisA11** [comment]
I mostly agree. Plast is always used instead

**Comment by RouterChainsSuckk** [comment]
well then clearly nobody knows how to play the game, usually for any good defense there's 1 layer of plast walls and 1-2 layers of surge and possibly a phase wall layer in front

**Comment by EclipsePlays** [comment]
> usually for any good defense there's 1 layer of plast walls and 1-2 layers of surge 
> 

What's the importance of adding a layer of surge wall if it doesn't even do anything to help the defense except for having chonky health

And you're wrong the real good wall layers was 2 layers of plastanium, 1 layer of phase fabric, and 1-2 layers of thorium (you can change it to surge but it's not worth it if it's destroyed)

**Comment by EclipsePlays** [comment]
Just, think of it by yourself. You are wasting **24 surge alloys** (72 silicon) just to create that one, useless, wall. I mean, do you see in mid to late game, a surge wall has been built immediately after getting surge alloys or getting a handful (3k) of it? 

Surge alloys are pretty expensive, and surge walls aren't worth it to **invest**.

**Comment by EclipsePlays** [comment]
> > usually for any good defense there's 1 layer of plast walls and 1-2 layers of surge 
> > 
> 
> What's the importance of adding a layer of surge wall if it doesn't even do anything to help the defense except for having chonky health
> 
> And you're wrong the real good wall layer was 2 layers of plastanium, 1 layer of phase fabric, and 1-2 layers of thorium (you can change it to surge but it's not worth it if it's destroyed) 
>

**Comment by RouterChainsSuckk** [comment]
> > usually for any good defense there's 1 layer of plast walls and 1-2 layers of surge
> 
> What's the importance of adding a layer of surge wall if it doesn't even do anything to help the defense except for having chonky health
> 
> And you're wrong the real good wall layer was 2 layers of plastanium, 1 layer of phase fabric, and 1-2 layers of thorium (you can change it to surge but it's not worth it if it's destroyed)

Clearly not a good wall if it has 2 layers of plast

> Just, think of it by yourself. You are wasting **24 surge alloys** (72 silicon) just to create that one, useless, wall. I mean, do you see in mid to late game, a surge wall has been built immediately after getting surge alloys or getting a handful (3k) of it?
> 
> Surge alloys are pretty expensive, and surge walls aren't worth it to **invest** them.
When you have 72 silicon being added to the core every secound it doesn't matter

**Comment by itcannotbe** [comment]
> I mostly agree. Plast is always used instead

Why? Because Corvus.

**Comment by Humanoid-X** [comment]
isnt corvus supposed to be a support uint, why is its damagee so hoghh

**Comment by EclipsePlays** [comment]
Final question before closing the issue: 

Does everyone agree with the Surge Wall Buff?

- Like and Dislike to vote.

**Comment by itcannotbe** [comment]
> Final question before closing the issue:
> 
> Does everyone agree with the Surge Wall Buff?
> 
>     * Like and Dislike to vote.

It doesn't work that way in this community.

**Comment by itcannotbe** [comment]
While I agree with buffing the surge wall the proposed buff so far doesn't make the surge wall worth the surge it costs.

**Comment by EclipsePlays** [comment]
> > Final question before closing the issue:
> > 
> > Does everyone agree with the Surge Wall Buff?
> > 
> >     * Like and Dislike to vote.
> 
> It doesn't work that way in this community.
>
If everyone seems to agree, I'll make a PR. I can't right now because #balancing has split opinions, and I don't have a leverage to use.

**Comment by EclipsePlays** [comment]
> While I agree with buffing the surge wall the proposed buff so far doesn't make the surge wall worth the surge it costs.
> 
> Also while increasing it's HP seems to be the obvious buff to give it. 🍑🧸 in 🧠 menders/mend projectors heal a block with a percentage of it's max HP.

Still, it's no use if some bullets can pierce through the wall, although it's very effective when used as an outer wall if it has 4000-4200 HP.

**Comment by itcannotbe** [comment]
> > > Final question before closing the issue:
> > > Does everyone agree with the Surge Wall Buff?
> > > ```
> > > * Like and Dislike to vote.
> > > ```
> > 
> > 
> > It doesn't work that way in this community.
> 
> If everyone seems to agree, I'll make a PR. I can't right now because #balancing has split opinions, and I don't have a leverage to use.

Does anuke even merge balance PRs?

**Comment by itcannotbe** [comment]
> > While I agree with buffing the surge wall the proposed buff so far doesn't make the surge wall worth the surge it costs.
> > Also while increasing it's HP seems to be the obvious buff to give it. 🍑🧸 in 🧠 menders/mend projectors heal a block with a percentage of it's max HP.
> 
> Still, it's no use if some bullets can pierce through the wall, although it's very effective when used as an outer wall if it has 4000-4200 HP.

Not every pierce is the same bruh.

Also if you're worried with the corvus. Don't balance a wall based of one unit, rework the unit itself.

**Comment by EclipsePlays** [comment]
> > > > Final question before closing the issue:
> > > > Does everyone agree with the Surge Wall Buff?
> > > > ```
> > > > * Like and Dislike to vote.
> > > > ```
> > > 
> > > 
> > > It doesn't work that way in this community.
> > 
> > If everyone seems to agree, I'll make a PR. I can't right now because #balancing has split opinions, and I don't have a leverage to use.
> 
> Does anuke even merge balance PRs?

At least he knows that we produce results. Yes he wasn't merging it, but he's changing it by himself (which is a bit annoying)
