### ISSUE TITLE
Improved tutorial/hints for V7

### ISSUE THREAD

**Issue by littelcat456** [Anuken/Mindustry-Suggestions#2631]
**Describe the content or mechanics you are proposing.**
The ingame hints that pop up to help guide you through the campaign (especially on mobile) should be more helpful and descriptive, especially in the first few sectors (e.g. Ground Zero, Frozen Forest, The Craters). When i showed my father about the game, he had trouble in Ground Zero with the “Destroy blocks” hint, and the hint about how to rotate conveyors with the arrow button, plus the Research Tree’s instructions.

For example, the destroy blocks hint should highlight the derilict structures in GZ + have an arrow that leads to said structures, and for the Research Tree, it should point out things to unlock or tell you what to unlock, such as the router, a requirement for unlocking Frozen Forest.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In my father’s words: “The first few levels of a game should basically hold your hand with everything, show you how to accomplish stuff.”
It would be a huge help to get new players used to the basic mechanics of the game, like destroying derelict blocks to obtain some extra resources, how to rotate conveyors before & after placing, and learning how exactly the Research tree works.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [❌] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [❌] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [❌] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by littelcat456** [comment]
Update: Ctrl+F and “hint” on the trello brought it up

**Comment by JrTRinny** [comment]
tutorial used to be better in v5 actually. sadly, it got replaced by hints in v6

**Comment by oinkymoo** [comment]
i also tried Ctrl+f for hint on the trello and the only one i found was the addition of hints in the first place, which was from last october. probably not what you're lokking for

**Comment by littelcat456** [comment]
> i also tried Ctrl+f for hint on the trello and the only one i found was the addition of hints in the first place, which was from last october. probably not what you're lokking for

Huh, okay. I’ll reopen then.
