### ISSUE TITLE
Hide nametags of enemies in pvp at high ambient light alphas and disabled enemyLights

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2633]
**Describe the content or mechanics you are proposing.**
When enemy lights are off and the alpha of the ambient light is, say, above 0.98, blacken all enemy player nametags, and maybe do something with the minimap so it does not reveal enemy unit locations?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Makes PvP gameplay with enemy lights off more stealthy

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
power node spam
makes lights, and if they're shot down, reveals the enemy's location
though it does take some time which is usually important in pvp, so I guess that' a cool idea still
I just think the game could end fast with one army jumping ontop of the enemy by surprise repetedly, or just games with only base trades/races
