### ISSUE TITLE
All units seeking and attacking derelict cores

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry-Suggestions#2634]
**Describe the content or mechanics you are proposing.**
Units should seek and attack derelict cores similarly to other cores in core capture.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, most units will ignore derelict cores in core capture mode, requiring you to manually control them to capture the core. This will make things easier and also makes more sense.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
This might actually be a bug, but I'm not sure

**Comment by MrDuck557** [comment]
Derelict is untargetable

**Comment by Bottinator22** [comment]
And does that mean it can't ever be? Just make exclusively derelict cores targetable in core capture mode, so that you don't have derelict cores lying around being useless as much.

**Comment by Bottinator22** [comment]
*accidentally closes issue*

**Comment by Bottinator22** [comment]
Closing issue since this seems to be in the game now
