### ISSUE TITLE
Adding to that stealth suggestion

### ISSUE THREAD

**Issue by MistahStealYoGril** [Anuken/Mindustry-Suggestions#2636]
**Describe the content or mechanics you are proposing.**
Radars to know what is going on in it's range. Have different levels of radars that extend farther than the previous

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Prevents the stealth tactic from being overused or  overpowered. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
a link to the suggestion you are referring to would be helpful. also this probably should have just been a comment on said suggestion
