### ISSUE TITLE
Call enemy invasion to sector & infinite waves like in v5

### ISSUE THREAD

**Issue by imTheSupremeOne** [Anuken/Mindustry-Suggestions#2637]
**Describe the content or mechanics you are proposing.**

Option to call enemy to invade sector with some bait. Maybe even with some "bait-core-block" that would allow for infinite progressive in difficulty waves, like in v5, but enemies aiming not to destroy core, but the "bait-core-block", and disappear if they manage to break and destroy it. This way you could play infinite thing without losing sector. (mb even make regular core invulnerable).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

... just for fun. I mean mb you have built a really cool defenses and captured a sector, and then like "whats' now"?.. This devalues purpose of building really cool and thicc defense because you only need to defend once. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You do know captured sectors can still be invaded right?

Provided that it's not surrounded by allied sectors right?

**Comment by imTheSupremeOne** [comment]
> 
> You do know captured sectors can still be invaded right? Provided that it's not surrounded by allied sectors right?

Yeas, but I'm waiting like for 3-5 hours and still nothing is happening, and if I remember correctly it's not a big invasion either... I was only invaded once back in v6, while capturing another sector... and yea, as I was capturing sector I checked only once and then forgot until notification that it was over... This why I'm suggesting not only the way to force invasion, but also how infinite defence could be brought back (because if you are at a point when you want enemies invasion it's sure you are going to destroy anything easily that isn't infinite...)

**Comment by Humanoid-X** [comment]
play custom games survival mode then (not campain)

**Comment by imTheSupremeOne** [comment]
> 
> 
> play custom games survival mode then (not campain)

uuhm... no?.. 

I mean I could, but I see this good thing if it was added to campaign, because, as I said, I think it devalues the value of building thicc wall of defense with many units... because you'll just defend it once and that's all... Mb you could leave some nearby enemy sectors so they could attack you once in eternity, but for good defense static unscaling attacks wont do anything and wouldn't be interesting, so I guess it would be also better if there were possibility for infinite waves too...

**Comment by oinkymoo** [comment]
custom games do have infinite waves which by default scale infinitely

**Comment by itcannotbe** [comment]
> custom games do have infinite waves which by default scale infinitely

They don't.

**Comment by Dwal32s** [comment]
> You do know captured sectors can still be invaded right? Provided that it's not surrounded by allied sectors right?

Only if you have an enemy sector nearby, otherwise your sector is completely safe.
