### ISSUE TITLE
Buff Eclipse

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2639]
**Describe what you would like changed, and why.**
Buff Eclipse, because it have short range, weak, slow, low dps and it's currently the worst T5
**Describe the changes you want to propose. Include possible alternatives.**
buff Eclipse stats

**Comment by BorisA11** [comment]
Not needed. Eclipse is already good. It has 4x55 DPS guns, and two very good beams. It aint the best T5, but far from worst.

**Comment by JrTRinny** [comment]
You didn't detail it so I will,

Eclipse (v7) stats:

Blast Ammo Gun: 5 Damage 50 Area Damage

Laser Gun: 100 Damage

Lancer even have more dps than the Laser gun, let alone cryo Lancer.

The blast ammo is just weak and short range, no need to talk about it.

Eclipse can't outrange spectre, cyclone or even scatter (v7)
My solution is to increase the lase gun's range and damage, to 120 DMG and increase the blast gun to 10 dmg, and area dmg to 55, also increase the dmg area from 3.1 to 3.6

Eclipse is now terrifying, _as it used to be_

**Comment by EclipsePlays** [comment]
> 4x55 DPS guns
>
Which can be healed easily by a mender and a phase wall can absorb the fragments. 

>Far from worst
>
Currently the worst t5 that I can think of was Eclipse, second to reign. 

wElP oCt sTiLl hAs PaYloAd...

**Comment by JrTRinny** [comment]
> second to reign.

Reign is good for penetrating defenses, with its piercing ammo, combined with its enormous health, makes it a very terrifying killer robot.
Its only cons is maneuverability

**Comment by EclipsePlays** [comment]
> My solution is to increase the laser gun's range and damage, to 120 DMG and increase the blast gun to 10 dmg, and area dmg to 55, also increase the dmg area from 3.1 to 3.6
> 
> Eclipse is now terrifying, _as it used to be._
>

Still not that terrifying, because like what you said, it can't outrange a scatter, and obviously, tsunami. It will be easily pushed back, doing absolutely no scars on a late game defense.

**Comment by JrTRinny** [comment]
congrats man! Eclipse got buffed!

**Comment by notMEEPoffaith** [comment]
actually corvus is worst T5
sure it has best range
but it's bad in damage stuff

**Comment by Xuvl** [comment]
at least they all have advantages and disadvantages either in close range or long range
