### ISSUE TITLE
Best maps channel on discord. 

### ISSUE THREAD

**Issue by Cupowski** [Anuken/Mindustry-Suggestions#264]
I want to be there an another channel for maps on discord because on this Exhisting is some kind of shitpost and its rlly annoying. So i would suggest to make channel for best maps that player created and posted on maps to Separate art works from shitpost.

**Comment by itcannotbe** [comment]
I would like to point out that best is subjective thus would not be easily maintained.

**Comment by Anuken** [comment]
This is a lot of work to curate, and if you want some sort of rating system, use the Steam workshop.
