### ISSUE TITLE
Overdrived Liquid Transportation

### ISSUE THREAD

**Issue by nilederg** [Anuken/Mindustry-Suggestions#2640]
**Describe the content or mechanics you are proposing.**
Overdrives/domes should speed up transport rates of all liquid blocks. Many schematics have all factories running constantly when not boosted, but with an overdome applied that encompasses the schematic and all input to it, some factories start shutting down due to lack of liquids.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would allow for more consistency in schematic making, and would make far more sense than the current system.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
people seem to really dislike this suggestion and if i had to guess, its because they don't realize that there is a limit. for reference, pulse conduits carry at most 550 water or cryo per sec and routers about 400. a domed tetrative reconstructor is going to be pulling 450, and an exponential another 150, so i sure hope you weren't using that water for anything else

**Comment by itcannotbe** [comment]
> people seem to really dislike this suggestion and if i had to guess, its because they don't realize that there is a limit. for reference, pulse conduits carry at most 550 water or cryo per sec and routers about 400. a domed tetrative reconstructor is going to be pulling 450, and an exponential another 150, so i sure hope you weren't using that water for anything else

Well as it stands, the liquid system has its problems, and running it faster will aggravate the problems even more.
Just search the bug tracker.

**Comment by genNAowl** [comment]
Until then, just try tanks and junctions - those have a ridiculous throughput.

**Comment by RouterChainsSuckk** [comment]
dude, juntions (even at low fps/tps) is 2k liquid a sec, tanks slowly get worse the more they are chained but its still stupid. stop using pipes like a noob

**Comment by itcannotbe** [comment]
> dude, juntions (even at low fps/tps) is 2k liquid a sec.

Junctions don't even transfer liquids. They're magic.

> tanks slowly get worse the more they are chained but its still stupid.

Whut? While that is true but it's actually pointless to point that out.

**Comment by nilederg** [comment]
It's ridiculous that this isn't already implemented. Overdrives are supposed to make a factory, schematic, anything in range, faster. I don't understand why people hate that I'm suggesting that they should do that.

**Comment by Humanoid-X** [comment]
seriously why isnt this in the game

**Comment by nilederg** [comment]
> people seem to really dislike this suggestion
I don't think it's people overall, it seems to be that itcannotbe spammed reactions so that no positive reactions can be made.

**Comment by oinkymoo** [comment]
oh well that's just stupid
