### ISSUE TITLE
Mod settings

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#2641]
**Describe the content or mechanics you are proposing.**

An additional button that appears in settings, named "Mod Settings". It could possibly generate additional buttons for each mod, or that could just be done manually.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Allow mods to have a dedicated place for settings, rather than using a hotkey to open one, adding a button to settings, or putting modded settings by the vanilla settings.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
maybe instead of being in settings, it will appear in mod list as gear button near "delete" button?

**Comment by NiChrosia** [comment]
> maybe instead of being in settings, it will appear in mod list as gear button near "delete" button?
Those settings can only be accessed from the menu, whereas being in settings they can be changed in-game.
