### ISSUE TITLE
Automatic dependency suggestion

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#2642]
**Describe the content or mechanics you are proposing.**

A dialog that shows up when the mod class loader cannot find a class that a mod needs and a mod in [MindustryMods](https://github.com/Anuken/MindustryMods) has a class that matches the missing one. The dialog would have a button to install the missing mod dependency. (Either this or a dialog that prevents the mod classes from loading when a dependency is missing and has a button to download that dependency if it exists on GitHub.)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would allow less technical people to know the reason why a mod failed to load, and how to fix it, saving the mod developer time telling people how to solve it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by QmelZ** [comment]
if you have a dependency you should either make it a dependency in your mod.json or you should use `implementation` and not `compileOnly`

**Comment by NiChrosia** [comment]
> if you have a dependency you should either make it a dependency in your mod.json or you should use `implementation` and not `compileOnly`

It would be listed as a dependency, and using implementation duplicates the mod rather than accessing the pre-existing classes.

**Comment by QmelZ** [comment]
i know how gradle works, but it technically is a way and is a good way for certain stuff

**Comment by NiChrosia** [comment]
Another solution to this would be to simply disable mods if they're missing dependencies
