### ISSUE TITLE
Fix rallied units from snagging against walls

### ISSUE THREAD

**Issue by Neuroburst** [Anuken/Mindustry-Suggestions#2643]
(this is my first suggestion, so please keep that in mind)

**Describe what you would like changed, and why.**
When you rally units, they can get snagged against walls if you go behind them, because they just point towards where they want to go and move there, which can be a problem with a map with a lot of walls or in an area with a lot of blocks. This can get very frustrating when you are trying to launch attacks.

**Describe the changes you want to propose. Include possible alternatives.**
instead of moving towards the desired position, units should pathfind there so they can't get snagged

I have checked readme.md and haven't found any issues reporting this

**Comment by Neuroburst** [comment]
sorry! i found out i am supposed to post this in bugs reporting,

**Comment by Kyllingene** [comment]
This is not a bug, but neither will it be fixed. See [Anuken/Mindustry/pull/4324](https://github.com/Anuken/Mindustry/pull/4324)

**Comment by Neuroburst** [comment]
![image](https://user-images.githubusercontent.com/69093127/124038535-1e444d00-d9b6-11eb-8540-16a1d6eb2e9e.png)
they don't pathfind around terrain (this is the altest bleeding-edge)
