### ISSUE TITLE
Turret ammo maxes at 28/30 for certain turret/ammo combinations, according to Logic Sensor opcode

### ISSUE THREAD

**Issue by owenmaule** [Anuken/Mindustry-Suggestions#2644]
In Steam build 126.3
Turret ammo maxes at 28/30 for certain turret/ammo combinations, according to Logic Sensor opcode.

Examples:
scatter : lead
ripple : blast-compound
swarmer : pyrite or blast-compound
duo : graphite
salvo : graphite

Other ammo types in these fill up to ammoCapacity of 30.

**What I would like to see instead:
To avoid unnecessary complication, the turret should max out at ammoCapacity to make (ammo == ammoCapacity) checks simple.**

Logic script I used for this is attached. To use, link a Message for display, and turret(s) to be checked. Apply the ammo in the examples listed above to see 28/30 or other ammo to see 30/30.
[AmmoCounter.txt](https://github.com/Anuken/Mindustry-Suggestions/files/6744907/AmmoCounter.txt)

(In testing using this logic script, be aware there is an issue caused by deleting linked turrets, which can be easily worked around by editing the script, e.g. adding an extra end opcode,  which gets it working again - or avoided by unlinking turrets before deleting them.)

**Comment by itcannotbe** [comment]
Just make ammo multiplier sensable tbh.

**Comment by oinkymoo** [comment]
the problem is that ammo items will not enter a turret unless they can receive full use. if you were to manually fire that scatter twice, it would fill the rest of the way

**Comment by itcannotbe** [comment]
Scatter | Lead = 4x
Ripple | Blast = 4x
Swarmer | Blast = 4x
Duo | Graphite = 4x
Salvo | Graphite = 4x
Salvo | Thorium = 4x

See pattern?

30 % 4 != 0
