### ISSUE TITLE
Multiplicative Reconstructor rebalance 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2645]
**Describe what you would like changed, and why.**
In game we have 3 stage of game: low, mid, late game. Titanium unlock mid game: laser drill and some turrets. Thorium unlock all game content. But units are different. T1/2 units are used for pre titanium stage and after. For T3/4/5 you already need thorium, end game ore. I think units should be spread on 3 groups: low T1/T2, mid T3, late T4/T5
**Describe the changes you want to propose. Include possible alternatives.**
Change thorium to plastanium. This would be nice change for castom attack maps without thorium or maps when you need recapture thorium ore by rushing base by units.
Also this would make T3 units to build a little more problematic in PVP. And as I know cultivators got a buff in V7, so producing plastanium would be little easier. 

I propose 450 plastanium (or less) because Exponential Reconstructor have this much plastanium too.
And increase titanium 350 -> 550 to compensate 750 thorium.

**Comment by JrTRinny** [comment]
Plastanium is hard to produce, if you want to mass-produce, you would need enormous amount of oil, which can be extract by tar or oilex, but oilex isn't efficient and tar is rare in campaign or in custom maps.

This would make Plastanium Polypress (PR by someone sometimes ago, got rejected by Anuke beacause Plastanium has less use back then) actually gets implemented to the game.

**Comment by Kryvytsky** [comment]
In V7 cultivators would get buff, so spore to oil schematics would be more compact.
Except oil I have problem to a titanium. Plastanium need 2 titanium, so it can be actually problem if you low amount of titanium ore on map.
So plastanium

**Comment by Kryvytsky** [comment]
In V7 cultivators would get buff, so spore to oil schematics would be more compact.
Except oil I have problem to a titanium. Plastanium need 2 titanium, so it can be actually problem if you low amount of titanium ore on map.
So plastanium multipress could be good, to make in more efficient like 3 titanium to 2 plastanium.

**Comment by IIINSTINCT** [comment]
> In V7 cultivators would get buff, so spore to oil schematics would be more compact.
> Except oil I have problem to a titanium. Plastanium need 2 titanium, so it can be actually problem if you low amount of titanium ore on map.
> So plastanium 

Actually they got nerfed

**Comment by Kryvytsky** [comment]
> Actually they got nerfed
They consume more water, but production time is less.

**Comment by MostForgettablePerson** [comment]
> And as I know cultivators got a buff in V7

Wrong, cultivators are nerfed, even though their production speed is buffed, but water consumption is also higher AND their tile affinity is pointless, because it's also going to make the water consumption even higher.

> so producing plastanium would be little easier.

No one would use cultivators to make plastanium, even worse if there are no water pools, you have to use 3 water extractor just to fill a cultivator, and you need 5 cultivator to fill a spore press. Cultivator is highly inefficient and using them to mass produce T4 is dumb, except if you just want to get some overdrive

> I propose 450 plastanium (or less) because Exponential Reconstructor have this much plastanium too.

Having the same cost to a bigger reconstructor wouldn't make sense

**Comment by EclipsePlays** [comment]
> > And as I know cultivators got a buff in V7
> 
> Wrong, cultivators are nerfed, even though their production speed is buffed, but water consumption is also higher AND their tile affinity is pointless, because it's also going to make the water consumption even higher.
> 
> > so producing plastanium would be little easier.
> 
> No one would use cultivators to make plastanium, even worse if there are no water pools, you have to use 3 water extractor just to fill a cultivator, and you need 5 cultivator to fill a spore press. Cultivator is highly inefficient and using them to mass produce T4 is dumb, except if you just want to get some overdrive
> 
> > I propose 450 plastanium (or less) because Exponential Reconstructor have this much plastanium too.
> 
> Having the same cost to a bigger reconstructor wouldn't make sense

~~Saving this comment as a leverage to my next PR~~

**Comment by oinkymoo** [comment]
> > so producing plastanium would be little easier.
> 
> No one would use cultivators to make plastanium, even worse if there are no water pools, you have to use 3 water extractor just to fill a cultivator, and you need 5 cultivator to fill a spore press. Cultivator is highly inefficient and using them to mass produce T4 is dumb, except if you just want to get some overdrive
> 
i don't use spore for plastanium anyway cuz the ratios are bad. 5 spore presses make enough oil for 6 plast compressors
> > I propose 450 plastanium (or less) because Exponential Reconstructor have this much plastanium too.
> 
> Having the same cost to a bigger reconstructor wouldn't make sense
both exponential and tetrative reconstructors take 600 phase to build
