### ISSUE TITLE
Repair turret

### ISSUE THREAD

**Issue by MostForgettablePerson** [Anuken/Mindustry-Suggestions#2646]
**Describe what you would like changed, and why.**
*What's the point of building them if 6 repair points are better than a single repair turret*

**Describe the changes you want to propose. Include possible alternatives.**
Make it costs 25 additional phase but buff the healing speed to 450 health/s and scale up the energy consumption to 480 energy/s, this will prevent them from being spammed and makes them more efficient at healing because it takes less space than spamming repair points

**Comment by itcannotbe** [comment]
Why not make the repair turret heal not with a flat health value, but by a certain percentage of health per second?

**Comment by EclipsePlays** [comment]
Anuke just nerfed repair turrets, buffing them again would be a roller coaster ride for this topic. 

>What's the point of building them
>

R a n g e

And also you can add 2 watexes to it so it'd run 1.5x faster
