### ISSUE TITLE
Allow lowering the base unit cap.

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2648]
**Describe what you would like changed, and why.**
As it stands, the base unit cap setting doesn't let you _lower_ the unit cap

**Describe the changes you want to propose. Include possible alternatives.**
Set the default base unit cap to 1, so you can use decimals to lower it, alternitively, make it so negatives work towards lowering the unit cap.

**Comment by Humanoid-X** [comment]
yes

**Comment by oinkymoo** [comment]
i think the negatives option would probably be better

**Comment by Anuken** [comment]
> As it stands, the base unit cap setting doesn't let you lower the unit cap

![image](https://user-images.githubusercontent.com/10100000/124179410-d3dbd280-da80-11eb-9f36-d729131ca5c4.png)

![image](https://user-images.githubusercontent.com/10100000/124179462-e48c4880-da80-11eb-9ea9-c0f597d317a2.png)

This has always been possible.

**Comment by MauritanianMapping** [comment]
> > As it stands, the base unit cap setting doesn't let you lower the unit cap
> 
> ![image](https://user-images.githubusercontent.com/10100000/124179410-d3dbd280-da80-11eb-9f36-d729131ca5c4.png)
> 
> ![image](https://user-images.githubusercontent.com/10100000/124179462-e48c4880-da80-11eb-9ea9-c0f597d317a2.png)
> 
> This has always been possible.

Good to know, I could use that personally

**Comment by genNAowl** [comment]
Close now?

**Comment by Anuken** [comment]
It's strange to see a suggestion here that *was always in the game*, but regardless of the opener's response this is no longer necessary.
