### ISSUE TITLE
a logic command for string modification

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2649]
**Describe the content or mechanics you are proposing.**
add a logic command "string" to modifies string (ex. a = b add "blabla")
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
because sometime i (or some other people) need to make string and modifies it, or making new Different String infinitely (and we can't do that)
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
yes please i want string processing so bad

**Comment by Kyllingene** [comment]
You, @oinkymoo, should already know that Anuke has *heavily* laid the *nope* on this idea many, many times.

**Comment by oinkymoo** [comment]
not that i can think of. certainly doesn't help that i've only been around for about 3 months, and have pretty much only paid attention to the github in that time

**Comment by Kyllingene** [comment]
I'm not on Discord, although I have been around for a few more months than that (but less than a year); so maybe it was longer ago than I remember. Anyways, the point is that it isn't happening; sorry.

**Comment by genNAowl** [comment]
Hmm; I don't remember anything about String processing mentioned before, but I can see why Anuke would dislike the idea. 

And I don't think this really has a good use case - I've never needed to to modify a string ever before.

**Comment by Kyllingene** [comment]
The reason Anuke doesn't want string ops is because it allows for theoretically infinite storage space; in other words, he wants people to still use memory blocks.
