### ISSUE TITLE
[QOL] Resource indicator for copy/paste schematics

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#265]
**Describe the content or mechanics you are proposing.**
An indicator for how many resources are required for a schematic.
Similar to https://github.com/Anuken/Mindustry-Suggestions/issues/95 but for when you copy a schematic with **`F`**.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Helps users see when a copying and pasting a schematic would be too expensive.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
How would you picture it to look like?

**Comment by Katsute** [comment]
![ui](https://user-images.githubusercontent.com/58778985/86283168-7fbcba80-bbae-11ea-9e14-4fc263724d5d.PNG)
Something like this at the bottom of the screen

**Comment by zethnest** [comment]
What if the selection uses a lot of ingredients?

**Comment by Katsute** [comment]
Maybe have the resources listed in two or more rows (so it also works on smaller screens)

**Comment by zethnest** [comment]
It won't work when you have a lot of mods with a lot of ingredients though

**Comment by SupremeTurtle** [comment]
The **resource indicator** could be small (but big enough to clearly see) and at the side of the screen

**Comment by itcannotbe** [comment]
You underestimate how much free space there is for that on mobile ui.

**Comment by Catchears** [comment]
> You underestimate how much space that will take on mobile ui.

But maybe there will be an option in the setting to turn it off.

**Comment by RandomMangaFan** [comment]
You could do it so that there is a "..." after a small number of materials and the materials appear in a popup once you hover/click/tap on it.

Or you could make all of the materials under a material button, and when you click it you get a scrollable screen of all the materials required.
