### ISSUE TITLE
Stop Discrimination

### ISSUE THREAD

**Issue by Humanoid-X** [Anuken/Mindustry-Suggestions#2652]
**Describe the content or mechanics you are proposing.**
We should be able to control distributors and liquid routers.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Consistency.
![image](https://user-images.githubusercontent.com/60562028/124209318-e9eaa100-db1b-11eb-9f8c-35b708c14a5b.png)
This issue is gonna be nerfed into oblivion.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
#2503 is stale anyway

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
what de faq

**Comment by Humanoid-X** [comment]
Sorry
I was struggling with whether I should close or open this issue

**Comment by itcannotbe** [comment]
Now I am struggling whether to suggest nerfing you like bohaska.

**Comment by Humanoid-X** [comment]
> Now I am struggling whether to suggest nerfing you like bohaska.

Probably yes.

**Comment by IIINSTINCT** [comment]
First you repeatedly closed and reopened this issue and bombarded #suggestion channel on discord with this please dont do that again :/

Anyways think first....
This Should be in the game now if anuke want this kind of stuff right? But no It is still not in the game which means anuke dont like it. Basically you kinda wasting your time for this  suggestion but yea he might change his mind

**Comment by Humanoid-X** [comment]
> First you repeatedly closed and reopened this issue and bombarded #suggestion channel on discord with this please dont do that again :/

Oops, I forgot that channel existed. :p

> This Should be in the game now if anuke want this kind of stuff right? But no It is still not in the game which means anuke dont like it. Basically you kinda wasting your time for this suggestion but yea he might change his mind

Nah I don't care I just want controllable distributors

**Comment by IIINSTINCT** [comment]
> > First you repeatedly closed and reopened this issue and bombarded #suggestion channel on discord with this please dont do that again :/
> 
> Oops, I forgot that channel existed. :p
> 
> > This Should be in the game now if anuke want this kind of stuff right? But no It is still not in the game which means anuke dont like it. Basically you kinda wasting your time for this suggestion but yea he might change his mind
> 
> Nah I don't care I just want controllable distributors


Well you can do it on servers but it doesn't function properly

**Comment by Humanoid-X** [comment]
> > > First you repeatedly closed and reopened this issue and bombarded #suggestion channel on discord with this please dont do that again :/
> > 
> > 
> > Oops, I forgot that channel existed. :p
> > > This Should be in the game now if anuke want this kind of stuff right? But no It is still not in the game which means anuke dont like it. Basically you kinda wasting your time for this suggestion but yea he might change his mind
> > 
> > 
> > Nah I don't care I just want controllable distributors
> 
> Well you can do it on servers but it doesn't function properly

Yeah so I want functional one

**Comment by RouterChainsSuckk** [comment]
It already exists, get foos client to posses distributor ya bum, controlling liquid routers wouldn't work (and if your on mobile so you can't get foos then quit wasting money and buy a decent laptop)

**Comment by RouterChainsSuckk** [comment]
Oh and they deserve to be discriminated against, routers distributor and liquid routers are horrible

**Comment by Humanoid-X** [comment]
explain why are  they horrible o_O

**Comment by Humanoid-X** [comment]
question: does foo client work in multiblayer?

**Comment by Humanoid-X** [comment]
misclick. sorry for bombing discord again. 
:sadgery:

**Comment by abdallah362** [comment]
dude

**Comment by EclipsePlays** [comment]
I've always been seeing ppl riding distributors in io survival ._. 

Also wtf open and reopen was annoying af

**Comment by SMOLKEYS** [comment]
Ah, the times where i could destroy a player controlled distributor in 2r2t, and make their game crash by doing that.

**Comment by RouterChainsSuckk** [comment]
> explain why are they horrible o_O

router has backflow, liquid router is dog ass because tanks exist, and distributor is almost pointless

**Comment by RouterChainsSuckk** [comment]
> question: does foo client work in multiblayer?

yes ofc it does

**Comment by Humanoid-X** [comment]
okie thankx

**Comment by abdallah362** [comment]
wait all this after it you close it

**Comment by Humanoid-X** [comment]
yes

**Comment by OnyxFinger** [comment]
what the hell

makes sense I guess, lol

**Comment by Humanoid-X** [comment]
but what about liquid router lol
