### ISSUE TITLE
Balance RTG

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2654]
**Describe what you would like changed, and why.**
currently, RTG generator kinda expensive, and nearly every just go for thorium reactor
**Describe the changes you want to propose. Include possible alternatives.**
1.remove phase fab. from RTG build cost then make it produce less power (210) ?
2.make it produce more power? (320)

**Comment by itcannotbe** [comment]
Do you actually realize how cheap is it to run an RTG?

Though I agree that the build cost isn't helping it become an option to make power.

**Comment by Ineedause** [comment]
running an rig is not the issue with it, the issue is it's cost. I feel like phase should be removed from the cost but it be nerfed heavily. something along the lines of that

**Comment by itcannotbe** [comment]
> running an rig is not the issue with it, the issue is it's cost. I feel like phase should be removed from the cost but it be nerfed heavily. something along the lines of that

Nah. That would put RTGs further down the shit tier.
Just change phase to something more easily produced but make it painful to spam it.

**Comment by oinkymoo** [comment]
rtgs are the best easy-to-run power generation. a full unboosted laser drill can already run 15 rtgs. anything better requires 3 different resources to run (water, titanium, and either thorium or sand lead and coal

**Comment by Humanoid-X** [comment]
Hmmmm i n t e r e s t i n g I think ii will start using rtgs in my planet domination

**Comment by EclipsePlays** [comment]
> Hmmmm i n t e r e s t i n g I think ii will start using rtgs in my planet domination

Many ppl already did
You just plop 6 rtgs on your core schematic and it can already run a zenith production complex

Phase fabric isn't that of a problem in campaign so it's more spammable but in multiplayer, its a nah. 

This gives another inspiration to play campaign since rtgs are currently specialized and spammed on campaign.

**Comment by itcannotbe** [comment]
> rtgs are the best easy-to-run power generation. a full unboosted laser drill can already run 15 rtgs. anything better requires 3 different resources to run (water, titanium, and either thorium or sand lead and coal

The major drawback to spamming them is that phase is painful to produce for use in building a lot.

**Comment by Humanoid-X** [comment]
> > rtgs are the best easy-to-run power generation. a full unboosted laser drill can already run 15 rtgs. anything better requires 3 different resources to run (water, titanium, and either thorium or sand lead and coal
> 
> The major drawback to spamming them is that phase is painful to produce for use in building a lot.

I know, I am a noob, as always.
