### ISSUE TITLE
Control Repair Point/Turret

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry-Suggestions#2656]
**Describe the content or mechanics you are proposing.**
Make so that we can control repair point/turret like other turrets, and select units to heal
In phone, there is auto-target, so that's good, but what about computer? maybe the heal beam doesn't appear unless you directly click on the unit

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
So we can select what unit we want to heal it first, so we can heal the most important unit quickly.

Situation like there are several damaged zeniths, but we want to heal Quad first.
The only solution now is to get those zeniths away from repair point/turrets
which can be hard when there are more than one type of unit

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. Read the freaking `README.md`
Specifically the part where it says:
`Additional configuration of blocks`
2. Have you considered using Logic?

**Comment by JrTRinny** [comment]
1. I read it, and yes, that part is so vague, like *what kind of of specific configuration?*

2.Yes I tried, but "logic", like "mod", is not an answer, when something should be in the game, then it should.
look at command center, we have logic, why doesn't Anuke remove it, because not everyone knows logic

**Comment by itcannotbe** [comment]
>     1. I read it, and yes, that part is so vague, like _what kind of of specific configuration?_

Exactly. It is vague because it should cover a lot of stuff.

> 2.Yes I tried, but "logic", like "mod", is not an answer, when something should be in the game, then it should.
> look at command center, we have logic, why doesn't Anuke remove it? because not everyone knows logic

And in the same way every block/unit can run without logic.
So if you want to do something advance, like specifically telling a block to do certain things to certain thing when certain things happen, use logic. It's that simple.

**Comment by MrDuck557** [comment]
note: I don't think you can control what repair point heals

**Comment by Humanoid-X** [comment]
can you even control repair points with lofic lol

**Comment by itcannotbe** [comment]
If it's not then let's change that.

**Comment by RouterChainsSuckk** [comment]
why the fuck would you need to control them, its as useless as controlling segment or paralx

**Comment by JrTRinny** [comment]
uhh, did you read the post?
