### ISSUE TITLE
Neutral cores

### ISSUE THREAD

**Issue by StoneMcYT** [Anuken/Mindustry-Suggestions#2657]
**Describe the content or mechanics you are proposing.**
The ability to have some cross on the map set as neutral and players can capture the cores.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This can increase multiplayer competitiveness. 
The new gameplay options could be requiring capturing X number of cores (Multiplayer)
For PvP, it can be till ALL enemy cores are destroyed. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [You lied] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

- [You lied again] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by StoneMcYT** [comment]
>     * [You lied] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
> 
>     * [You lied again] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Appologies i am sorry bout that. i didnt double check the wiki and the trello

**Comment by SMOLKEYS** [comment]
Can't you just

> derelict cores
