### ISSUE TITLE
Neutral teams

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2658]
**Describe the content or mechanics you are proposing.**
Right now in pvp there must be an anti-rush wall in order to prevent an instant win. This wall is usually made with turrets and resource sources like the power source. The issue is that once this power source is broken it can not be rebuilt ever again. I propose that there should be a way to set a "neutral team" that has sandbox mode enabled.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This content will allow units to be used in a divider "team". Having polys be able to rebuild power sources would allow a "shut down" area that is impassable by air units. Let me elaborate, say I want a part of the map to be shut down to air units, I would place down a few meltdowns, but the issue is that at any time any team can just foreshadow the power or liquid sources, this brakes the entire section of the wall. Now, if the divider team had sandbox I would be able to put down a poly factory and have the polys rebuild the broken sources. As of right now this is impossible.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MostForgettablePerson** [comment]
Antirush is meant to be broken as fast as possible, if you want it to be invincible, making defense would be useless, because people would just rush a lot of units. Plus, it makes the game longer and laggier, which is bad for low end devices, and no one wants to join a game where everything is already set up and have nothing to do at all.

**Comment by Ineedause** [comment]
That is not what I am asking for, I am asking for a way to block a certain part of the map from air units, this is the best way I could think of, please re-read it.

**Comment by Yell245** [comment]
Maybe alternatively make this team's things be working without input like in v5?

**Comment by Ineedause** [comment]
not a bad idea

**Comment by itcannotbe** [comment]
So what issues are you having with air units again?

You do know that killable wrecks are a thing now, falling units are not as a problem as they used to be

**Comment by Ineedause** [comment]
My issue is that I have a map with a huge open space that can be crossed by air units but I don't want it to be. Setting up early game defenses is not an option because you can make 10 flares faster than you can make the 10 scatters to kill those flares

**Comment by Anuken** [comment]
It really sounds like what you're asking for is blocks with infinite health.

**Comment by Ineedause** [comment]
Actually that is something in the lines of what I had in mind.

**Comment by OnyxFinger** [comment]
There does not need to be an anti rush
there needs to be a better introduction to pvp and countering flare rushes in general. Other than that, it's all about wether or not you suck when you get to not pause.
