### ISSUE TITLE
sandbox logic proccsesor 

### ISSUE THREAD

**Issue by oh-no-sphere** [Anuken/Mindustry-Suggestions#2659]
**Describe the content or mechanics you are proposing.**
sandbox logic processor 

a processor with so many instructions available (sandbox only)|
sorry my bad I meant a very fast processor cause normal ones are limited
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

would improve the quality of using and testing logic processors 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Please tell me this is a joke.

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting a processor with so many commands available before. This is a revelation. I would never have thought of adding a processor with so many commands available myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement a processor with so many commands available  immediately."

**Comment by JrTRinny** [comment]
that's called "console" to be precise, you just need some js knowledge to do that, which I doubt you don't have

**Comment by SMOLKEYS** [comment]
Just let this suggestion rot to hell and get closed by @github-actions.

**Comment by Phinner** [comment]
You guys don't need to be that rude.

**Comment by oh-no-sphere** [comment]
bruh i meant instructions
i meant a cheat logic processor 
a very fast one 
normal ones are limited 

> Anuke be like:
> 
> "Incredible. Nobody has ever even considered suggesting a processor with so many commands available before. This is a revelation. I would never have thought of adding a processor with so many commands available myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement a processor with so many commands available immediately."

**Comment by JrTRinny** [comment]
you can use console to edit processor speed

**Comment by notMEEPoffaith** [comment]
mod please

**Comment by Humanoid-X** [comment]
sure, use the console and close.

**Comment by SMOLKEYS** [comment]
***Close please.
You can just use the GODDAMN CONSOLE.***

**Comment by oh-no-sphere** [comment]
then why we have units sources 
We CaN UsE ThE GoDDaMn ConSolE

**Comment by itcannotbe** [comment]
It's not even called a unit source -_-

**Comment by itcannotbe** [comment]
It's purpose is to spawn thing on a payload conveyor, not purely meant to spawn units -_-

**Comment by oh-no-sphere** [comment]
it's mostly used for spawning units

**Comment by itcannotbe** [comment]
> it's mostly used for spawning units

It doesn't mean you only use it for that purpose only, it's the only use of that block.

**Comment by itcannotbe** [comment]
Also you can console edit with ease the instruction per tick value of any processor -_-

**Comment by itcannotbe** [comment]
Also unlike other things in mindustry, you can't exceed your physical hardware's limit in excuting instructions.
