### ISSUE TITLE
Filter (Anti-sorter)

### ISSUE THREAD

**Issue by fragmints** [Anuken/Mindustry-Suggestions#266]
I am proposing that there should be an anti-sorter, or in more descriptive terms a block that prevents the one specific item from entering or spits that specific item out to the side.

//

The sorter does the basic logic of "If <item>, spit it out opposite of entrance point. If !<item>, then don't accept it.
The inverted sorter basically does the same thing but to the sides instead of opposite of entrance point.

The "anti-sorter" as I have nicknamed it reverses the logic. "If <item>, then don't accept it. If !<item>, spit it out opposite of entrance point.
An "inverted anti-sorter" does the same but yknow, to the sides instead of "opposite of entrance point."
I hope I got my point across.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
This is achievable with sorter and inverted sorter. What's the significance of this? Use cases? Images?  Why would you want a conveyor to halt?

**Comment by DS-3K** [comment]
That is leterally the definition of the inverted sorter... You are suggesting implemented contend!

**Comment by jaygamer81** [comment]
Change the name of the inverted sorter to filter. That would be realllyy noice.

**Comment by fragmints** [comment]
i didnt realize this is what the inverted sorter did. sorry lads
