### ISSUE TITLE
.gif's for modding sprites

### ISSUE THREAD

**Issue by notMEEPoffaith** [Anuken/Mindustry-Suggestions#2660]
**Describe the content or mechanics you are proposing.**

Support for .gif's for animated sprites while modding.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would open up animated sprites for non scripted mods. It would make animating certan things much easier.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. (i experienced this head on when trying to add a gif as a sprite for a unit.)
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slava0135** [comment]
Change which sprite to draw every X ticks problem solved

**Comment by MrDuck557** [comment]
.gif has horrible file size, and the atlas is a .png.
This isn't easy, and it's not necessarily a good idea

**Comment by notMEEPoffaith** [comment]
oh pain

**Comment by Kyllingene** [comment]
plz no save the atlas
