### ISSUE TITLE
Multi-unit payloading

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2661]
**Describe the content or mechanics you are proposing.**
Make payload unit can multi-payload, meaning we can use 2~3 mega (or other unit) to pick up bigger block (like 3x3)
to do this by the player, picking up a bigger block will use controlled mega in player foundation
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
for picking up biger block and transport with smaller units
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
It is a good idea but the only issue I can see here is balancing, having 9 mega be able to replace an oct is a little too much imo.

**Comment by DestroyerXL44** [comment]
Yeah, while this sounds good on paper there's a lot of balancing stuff to think about. Since lower tier units are much easier to mass produce you'd be able to make enough to pick up the biggest payloads probably a bit too easily

**Comment by Kyllingene** [comment]
This seems like something that would require a nearly total rework of the payload carriage system.

**Comment by itcannotbe** [comment]
You know certain units could already pick up blocks bigger than 3x3 right.

And yes.
Consider ...

> Yeah, while this sounds good on paper there's a lot of balancing stuff to think about. Since lower tier units are much easier to mass produce you'd be able to make enough to pick up the biggest payloads probably a bit too easily
