### ISSUE TITLE
improve memory(?)

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2662]
**Describe the content or mechanics you are proposing.**
sinply just make memory bank/cells able to store object, because there's still a few problem with it...

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
improving logic storing (?)
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
and what purpose will this serve

**Comment by vinhsad** [comment]
saving things and it will make a string generator, which is the thing that everyone needed for inf exstend string without making a new1 without spaming adding new string...

> and what purpose will this serve

**Comment by Kyllingene** [comment]
You can use flags, you know; pseudocode:
```
set X 0
bind @poly
flag 0
write cell0 X X
op add X 1
jump 2
```
Of course, you would have make sure that you don't accidentally reflag a unit (just check if it already has a flag), and also would have to check that you indeed found a unit to bind to; but I left that out to give a general idea.

So, please, close this. Use the perfectly reasonable amount of power given by logic as it stands.

**Comment by vinhsad** [comment]
> You can use flags, you know; pseudocode:
> 
> ```
> set X 0
> bind @poly
> flag 0
> write cell0 X X
> op add X 1
> jump 2
> ```
> 
> Of course, you would have make sure that you don't accidentally reflag a unit (just check if it already has a flag), and also would have to check that you indeed found a unit to bind to; but I left that out to give a general idea.
> 
> So, please, close this. Use the perfectly reasonable amount of power given by logic as it stands.

with this commands, the spped/effective is based on the current units

**Comment by Luhrel** [comment]
I support this.
Currently, we are unable to do things like this (pseudocode) :
```
set result @copper
write cell1 result 0
read res cell1 0
control configure unloader1 res
```
`res` is equal to `1` instead of `@copper`.
I want to write every material in a cell, and then depending on some values/numbers/whatever , read the correct index in the cell and set the unloader to the corresponding material (0 -> `@copper`, 1 -> `@lead`, ..., 15 -> `@pyratite`).
At the moment, the only solution is to do some ugly copy/pasta; which also makes changes annoying.
