### ISSUE TITLE
Disassembler buff

### ISSUE THREAD

**Issue by Nils101** [Anuken/Mindustry-Suggestions#2663]
**Describe what you would like changed, and why.**
A disassembler buff. We had a little talk about the disassembler in #balancing and it was universally agreed that it's bad. It's rarely used in designs/the game itself. The problem with it is its ridiculously high price (including 70 surge), combined with the fact that it consumes enormous amounts of scrap and outputs either trash that could be made much more efficiently with separators/pulverizers or thorium in way too small amounts. (keep in mind that you need thorium to even build them - alloy smelter.)
This change would make it way more useful, both for people who make designs and to people just play pvp/attack.

**Describe the changes you want to propose. Include possible alternatives.**
 There are many ways to make it more useful, but I like the following: (just randomly thrown together, I don't expect all of them to be applied)
**-Increase thorium drop rate by a bit: ⅑->⅛**
**-Remove surge cost.** This would be a big change, so to counter balance other cost may have to be increased.
**-Maybe remove its need for raw scrap?** I don't really understand why that's in the game in the first place but its removal would simplify things.
To counterbalance those buffs power/slag consumption could be increased.

**Comment by EclipsePlays** [comment]
I was also in #balancing when this topic opened, so this were the steps to make it useful again: 

- Remove Surge Alloy cost, but will now need 100 thorium and 50 plastanium in order to be built. 
- Remove the scrap usage, instead make it use 8 slag/s
- Increase the rng of thorium, from 1/9 to 2/9 and titanium from 2/9 to 1/9.

**Comment by EclipsePlays** [comment]
> - Increase the rng of thorium, from 1/9 to 2/9 and titanium from 2/9 to 1/9.
>
So the actual rng values of disassemblers was:
- Thorium = 1
- Titanium = 2
- Graphite = 2
- Sand = 4

Why does titanium need to be nerfed in disassemblers? 

Separators can already do it.

**Comment by EclipsePlays** [comment]
> > - Increase the rng of thorium, from 1/9 to 2/9 and titanium from 2/9 to 1/9.
> >
> So the current rng values of disassemblers was:
> - Thorium = 1
> - Titanium = 2
> - Graphite = 2
> - Sand = 4
> 
> Why does titanium need to be nerfed in disassemblers? 
> 
> Separators can already do it. 
> 
>

**Comment by itcannotbe** [comment]
If anyone needs a reality check.
Here is it:

DISASSEMBLER IS NOT A DIRECT UPGRADE OF SEPARATORS.

**Comment by oinkymoo** [comment]
what is it if not that

**Comment by Nils101** [comment]
Suggestion got implemented, closing this now
