### ISSUE TITLE
Something about Navanax's main gun.

### ISSUE THREAD

**Issue by SoMall-dumpling** [Anuken/Mindustry-Suggestions#2664]
As we all known, Navanax is the 5 tier of the Navy Support Units which is added by Anuken in v126.
It has 5 turrents. Four of them are mini-meltdowns which are great. (great but short)
And the last one is a powerful electromagnetic gun which bullet will explose and give the things in the range of its explosion a positive/negative effect. ( the explosion effect is SOOOOOOO cool)

But the bullet's explosion isn't controlled by the player. It only exploses when it hits the enemy or reaches its maximum range.
Given its ability to provide speeding bonuses to allied buildings, this makes the control somewhat more difficult.

My suggestion is that, make the bullet explose at the position of the mouse when it's not out of the maximum range, and if it's out of the maximum range, just explose at the maximum range. (When it hits the enemy, just explose)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Given its ability to provide speeding bonuses to allied buildings, this makes the control somewhat more difficult.

![https://c.tenor.com/WFn3Az5yKa0AAAAM/yoda-sad.gif](Confused I Am)

**Comment by IIINSTINCT** [comment]
Firstly its is released on 127 pre alpha
Second you yeeted the half of the suggestion format
Third if you are trying to say that you what to 100% control EMP cannons then no. Every units have its own mechanic to do and it will make the game more interesting

**Comment by Ineedause** [comment]
The Navanax already has it's own feature. I support the control of the detonation point on the EMPs because they are a pain in the a__ to work with.

**Comment by oinkymoo** [comment]
what if i just want to shoot off into the distnace in the same direction. for example if im rushing to meet an enemy on the minimap
