### ISSUE TITLE
Fortress

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2665]
**Describe what you would like changed, and why.**

Today not to long ago there was a talk in #balancing about the fortress and how bad it is. The general conclusion that we came up with is the following. 

Bullet: graph ----> pira
Damage: 60 ----> 75
Aoe affect: 3.7 tiles -----> 5 tiles 
Health: 810 ----> 900

We feel like these changes should be made in order to make fortress useful again. The pita bullet will be used to wreak havoc on your defenses. The damage will increase it's usability on the field. The aoe gets a buff to help it hit more things in general. And the health is there to make it more durable in make it live up to it's name, the Fortress.

**Describe the changes you want to propose. Include possible alternatives.**

These are the changes that we feel are needed to make it good, please play around with the numbers a bit but these various buffs are needed to at least make it viable in some situations.

**Comment by Yell245** [comment]
We should somehow balance them so they're stronger than supports, but weaker than specialists, I think

**Comment by Ineedause** [comment]
yes, that is what we hope to achieve here

**Comment by JrTRinny** [comment]
support this balance <3 I'm in the the conversation about buffing it, now It would actually useable

Some buffs maybe need to think about Ruinous Shores, where the Fortress are Guardian there, this would make fortress in ruinous shore fun and challenging :)

**Comment by SMOLKEYS** [comment]
Acceptable, have a nice day.

**Comment by Humanoid-X** [comment]
support are too sstrong right now

**Comment by OnyxFinger** [comment]
not just the fortress, but it's whole route
also I like these changes, that was a nice idea.

**Comment by JrTRinny** [comment]
well, partially,
The fortress' ammo is still the same, no pyra (haven't tested, will look into it tomorrow)

**Comment by Ineedause** [comment]
FORTRESS GOT THE BUFF. LETS GOOOOOOO!!!!!
