### ISSUE TITLE
V to re spawn

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2668]
**Describe what you would like changed, and why.**

Make it a setting that you have to double tap v in order to re spawn. Let me explain why with a sequence of events

1. Plays pvp
2. Makes Quads
3. Starts using Quads to win game
4. Is destroying enemy base
5. Finger slips and presses v accedentally
6. Enemy survives
7. Rage quits

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by oinkymoo** [comment]
template but honestly the balancing/feedback template is weird and the second half is kinda a duplicate of the first part and you are valid

**Comment by itcannotbe** [comment]
Not necessarily.

The first part is what, the second part is how.

**Comment by Hyrotrioskjan** [comment]
can't you just re-bind the respawn key so it doesn't interfere with the main controls?.

**Comment by Ineedause** [comment]
Asking someone to rebind a key is like asking a preschooler to do algebra. It can not be done

**Comment by itcannotbe** [comment]
> Asking someone to rebind a key is like asking a preschooler to do algebra. It can not be done

You can. Why you ask? Becasue it can not be said so.

**Comment by OnyxFinger** [comment]
how on earth do you press v on accident
~~also your description of PvP wasn't as accurate as I wish it would be, well kind of, but not really, well in reality yes but it highly depends on the server and oponents, but I guess that's not supposed to matter~~
and just rebind your keys, even know barely anyone does it, you should know it ?
I mean c'mon, it doesn't take a lot IQ to think about it (or at least it *shouldn't*)
