### ISSUE TITLE
Team Colours for Some Blocks

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry-Suggestions#2669]
**Describe the content or mechanics you are proposing.**
Make Force Projectors (the block itself) and Reconstructors be team-coloured. Also, have the "waves" that pass over constructing units be team coloured as well.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It makes a bit more sense, since Sharded Force Projectors are the same colour as their shields, so why not have every other team have that? Also, there isn't very many team-coloured blocks, only Cores and Containers/Vaults

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
YES, THANK YOU

**Comment by Humanoid-X** [comment]
yes

**Comment by OnyxFinger** [comment]
agreeds
