### ISSUE TITLE
2v2 group multiplayer

### ISSUE THREAD

**Issue by RogelioAyus** [Anuken/Mindustry-Suggestions#267]
**Describe the content or mechanics you are proposing.**

- A 2 player vs 2 player mechanic for multiplayer or maybe even more at max of 3 vs 3. Example “red and blue vs the green and purple”. Two team with seperated resources, but they don’t attack each other and can help hand by hand. Both team won’t able to delete each other’s builds as well. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

- It will improved challenges and fun for all the multiplayer games that describe teamwork in different color. They won’t share materials but transfer materials by a new block or something. Very challenging

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Syncinus** [comment]
Mindustry already has the ability for multiple teams to exist in multiplayer

**Comment by itcannotbe** [comment]
Mindustry doesn't have support for making another team another team's ally.

**Comment by kingb74** [comment]
Dude u just have to have multiple cores like one side of the map has two red cores and the other half has two yellow cores and there a core on each corner that's basically 2v2 but the only problem is that both sides will share resources
