### ISSUE TITLE
mode function 

### ISSUE THREAD

**Issue by Nonnon2** [Anuken/Mindustry-Suggestions#2670]
Show if you can use the mode and enter the server before downloading the mode

**Comment by JrTRinny** [comment]
Template.

**Comment by Hyrotrioskjan** [comment]
> Template.
> Also your suggestions is very confusing, What _Mode_ and _why_ to change them and _how_ how what to change them if it got in the game.
> 
> Please close this.

I think he meant "mode" as in mods, but isn't there already a notifier when you enter a modded server without the needed mods?.

**Comment by LeoSko** [comment]
@JrTRinny, I can describe it properly, you don't have to be so toxic requesting to close suggestions which actually make sense.

When you connect to a server which uses any set of mods, game should provide you with a message prompt suggesting to download, install and instantly apply mods. This is how it works in every single game I tried so far, except Mindustry.

Regardless, answering suggestion - Anuken previously said that for some reason he doesn't want to add this into the game.

**Comment by JrTRinny** [comment]
Well, I'm not toxic man, I just asked for context, and what should be changed, how will be changed, and why.

That's why template exists

**Comment by OnyxFinger** [comment]
> Well, I'm not toxic man, I just asked for context, and what should be changed, how will be changed, and why.
> 
> That's why template exists

you kind of was being toxic >-<, though it was almost deserved, if at least template was something you had to manually type, I'd get it, but this going overkill
it's like "oh I have to fill a template for my suggestion not to get closed ? Let me remove the template and not even do things that end up being similar to filling the template !!!"

**Comment by oinkymoo** [comment]
to be fair the suggestion is incomprehensible
