### ISSUE TITLE
[Modding] `base:` field for turrets

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2671]
**Describe the content or mechanics you are proposing.**
  A `base:` field for turrets, allowing us to set the baseRegion without sprites-override/ or [thing]-base. Fallback to, of course, block-[size].png

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
  This would remove much sprite bloat in modded spritesheets, as currently to reliably override the baseRegion you have to use [thing]-base, for every *single turret that is larger than 4 tiles in size*.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
4. - [X] I have about 80 turrets that I have to make and I don't want to bloat the spritesheet like hell with bases.

**Comment by notMEEPoffaith** [comment]
y e s p l e a s

**Comment by Humanoid-X** [comment]
Y E S P L E A S E
