### ISSUE TITLE
Exponential Armor

### ISSUE THREAD

**Issue by SimplyTav** [Anuken/Mindustry-Suggestions#2672]
***Base idea by GusGusTheSavage#8481***

A Tier 5 exclusive feature to protect T5 units from turrets like the foreshadow.

**Describe the changes you want to propose. Include possible alternatives.**

Adding a defense mechanism for T5 units which **Exponentially** reduces the effectiveness of damage if unit's HP reach critical levels (below 45%) and gradually disappears after a period of time without receiving damage.

**Comment by Ineedause** [comment]
I was part of the conversation that made this suggestion, A few things to add:
1. The amount of damage reduction is directly tied into the units base armor
2. The multiplier should be somewhere in the 3x range
3. The effect should "tank" damage but not negate it
4. The effect should naturally decay after 30 secs
5. For every 100 damage tanked by this effect the durration should decrease by 1 second
6. As the timer starts to run out the effect should be less powerful

**Comment by MrDuck557** [comment]
Foreshadow is supposed to counter T5

**Comment by SimplyTav** [comment]
> I was part of the conversation that made this suggestion, A few things to add:
> 
> 1. The amount of damage reduction is directly tied into the units base armor
> 2. The multiplier should be somewhere in the 3x range
> 3. The effect should "tank" damage but not negate it
> 4. The effect should naturally decay after 30 secs
> 5. For every 100 damage tanked by this effect the durration should decrease by 1 second
> 6. As the timer starts to run out the effect should be less powerful

Note : this

**Comment by Ineedause** [comment]
right now it does that too efficiently because of spam, this hopes to give larger units such a reign an actual chance to do something and not get one shot

**Comment by itcannotbe** [comment]
So how are you supposed to defend against T5 then?
