### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Mechanicalenhancement1** [Anuken/Mindustry-Suggestions#2673]
**Describe the content or mechanics you are proposing.**
Being able to choose our color at the start of the campain

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It ads more customisation to this already epic game

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JrTRinny** [comment]
there's some lore behing this, and Anuke is gonna get it to use in v7

**Comment by EclipsePlays** [comment]
> there's some lore behind this, and Anuke is gonna get it to use in v7

Hmm, factions, right?

**Comment by Ruichka** [comment]
*casually selects red*

**Comment by Geogamer2019** [comment]
I am certain that it won't happen for the campaign, as it will mess with the lore. It could be added for customs though

**Comment by JrTRinny** [comment]
> this idea could come with a feature to allow players to pick a team you start in for custom maps too

yeah, this would be good for custom maps, but campaign NONO

**Comment by OnyxFinger** [comment]
> I am certain that it won't happen for the campaign, as it will mess with the lore. It could be added for customs though

good point.
