### ISSUE TITLE
we need more T2 Production equipment！

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Anuken/Mindustry-Suggestions#2674]
For example, more advanced silicon manufacturing equipment, high-speed sulfur production equipment

**Comment by JrTRinny** [comment]
uhhh, Template

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More T2 Production equipment before. This is a revelation. I would never have thought of adding More T2 Production equipment myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More T2 Production equipment immediately."

**Comment by itcannotbe** [comment]
> advanced silicon manufacturing equipment

You're kidding me right?

> high-speed sulfur production equipment

Is this some item that's in the game that I am not aware of?

**Comment by OnyxFinger** [comment]
bruh xD

idk template :\ lol

**Comment by Humanoid-X** [comment]
no
