### ISSUE TITLE
shield applier

### ISSUE THREAD

**Issue by Octilon** [Anuken/Mindustry-Suggestions#2678]
**Describe the content or mechanics you are proposing.**

I'm proposing a shield applier for units but only minimum t3 (or it will be kind of op), it works like a reconstructor, unit without shield go's in en exit with a shield, there will be 3 tiers of shield applier, tier 1 for t3 units, t2 for t4 units and t3 for t5 units, the amount of shield applied deppend's on the tier of the applier and the number of shield point that the units already has.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will allow friendly units to have shield to and make them stronger but always at a fair price.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
I mean, pulsars already have it, but it would be nice if we could give it to them manually

**Comment by Octilon** [comment]
> 
> 
> I mean, pulsars already have it, but it would be nice if we could give it to them manually

yeah, but I was thinking about actually reducing the shield of the quasar and making the shield applier the main source of shield, because we all know quasar are op and it will make the gameplay with units different and battle will be more interesting to see wich player or team was the most strategic with shield and units tiers and type, etc...

**Comment by OnyxFinger** [comment]
well, it makes sense since repair points are kinda like the shield applier but for the healing of novas
also I feel like pulsars shouldn't have a weaker shielding ability, because this very ability is kinda weak rn, though maybe the ability should have a higher shield cap than the one of pulsars

if that means anything to you ?

**Comment by Octilon** [comment]
> 
> 
> well, it makes sense since repair points are kinda like the shield applier but for the healing of novas
> also I feel like pulsars shouldn't have a weaker shielding ability, because this very ability is kinda weak rn, though maybe the ability should have a higher shield cap than the one of pulsars
> 
> if that means anything to you ?

yeah I understand what you mean, but my idea is of course experimental, I was just thinking of a way to appli shield to units with being it to op, so I just came up with this, of course Anuke and the dev team has to balance it if they choose to keep the idea:
