### ISSUE TITLE
mass driver bullets should do more damage to enemies

### ISSUE THREAD

**Issue by RoboRogue** [Anuken/Mindustry-Suggestions#2679]
increase damage

currently, it feels a bit weak, perhaps it could more or less damage depending on what it's carrying, and an even more out-there idea could be that the materials commonly used in ammunition (eg: pyratite, surge, thorium, etc) could have the effect they normally do when shot using a turret

**Comment by oh-no-sphere** [comment]
i know segment can grief mass drivers 
but where did you get that idea

**Comment by RoboRogue** [comment]
> i know segment can grief mass drivers
> but where did you get that idea

saw a video showing that mass drivers can damage enemies and it was hardly any

**Comment by OnyxFinger** [comment]
wat

Anuke said this feature was here cuz it made sense, it wasn't supposed to be usable :facepalm:

**Comment by vinhsad** [comment]
image mass driver blast bomin'
T5's be like:
p a i n

**Comment by Kyllingene** [comment]
Payload driver:
![image](https://user-images.githubusercontent.com/69094702/125146184-6ad80880-e0d9-11eb-8c2d-7eeed5db5a9c.png)

**Comment by vinhsad** [comment]
> Payload driver:
> ![image](https://user-images.githubusercontent.com/69094702/125146184-6ad80880-e0d9-11eb-8c2d-7eeed5db5a9c.png)

**image using blast in unit/block then shoot them away into the enemy**

**Comment by Dinistor** [comment]
It wasn't an intended feature to do dmg with this thing because you need to made units walk ~~the plank~~ between 2 of constantly working mass drivers. Its just makes sense that compressed pack of items is basically a bullet, but no one said that it's powerful.
