### ISSUE TITLE
Surge Creation Nerf

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#268]
**Describe what you would like changed, and why.**
I would like surge allow factories to require 1000 power because right now surge allow is a electrical component and i feel it should have a feeling of intense power

**Describe the changes you want to propose. Include possible alternatives.**
Make surge alloy cost 1000 power when created so the cost is heavy, maybe make the surge smelter have a additional slag input also, since they have almost the same ingredients

**Comment by Syncinus** [comment]
Surge is already a pain to make.

**Comment by ILiekMelons** [comment]
no
