### ISSUE TITLE
Item Loadout Sliders

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2680]
**Describe the content or mechanics you are proposing.**

Add sliders for each item type to allow players to adjust the amounts of items in their loadout to some fraction of the maximum possible amount. This should replace the - / + buttons for each item type. In addition, there should also be an extra slider which adjusts the amounts of every item at once. This would replace the Max / Reset to Default buttons.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would allow players to adjust item loadouts more easily. Currently, to adjust item amounts, players need to click the - / + buttons multiple times, or manually type in an amount. This change would allow item amounts to be adjusted with a single click per item type.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JrTRinny** [comment]
I mean the idea is ok, but you can just click the *pencil* icon to adjust it

**Comment by oinkymoo** [comment]
the existing buttons are fine, if you need more specific values use the pencil

**Comment by oinkymoo** [comment]
also silders are much harder to get a precise value with. if i want to bring 500 of an item, especially on mobile, its going to be nearly impossible to bring exactly 500, when with +/- i can get there in a few clicks
