### ISSUE TITLE
Capture Blocks on core capture

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2681]
**Describe the content or mechanics you are proposing.**

A new option that becomes avaiable once core capture is on, on the rules.
When a core is captured, any blocks within the core's no build radius/zone turns into the core's team

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Adds more options for attack/pvp maps
Should you risk the damage with functioning turrets to get some more resources or should you clear the whole place for a safer aproach?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jumps-are-op** [comment]
yeah this is big brain time

**Comment by Humanoid-X** [comment]
yes
