### ISSUE TITLE
Defeated teams turn derelict on PvP

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2682]
**Describe the content or mechanics you are proposing.**
Make it so when a team loses all it's cores, all it's buildings turn derelict, probably use the same logic as campaign attack maps.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Consistency, gets rid of a team once it's no longer in the game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jumps-are-op** [comment]
no it's bad 
what if there is a team with no core from the start

**Comment by Kyllingene** [comment]
> what if there is a team with no core from the start

And how exactly would the map know there is supposed to be a, say, green team, if there is no green core? *It is impossible to have a team with no core.*

**Comment by Humanoid-X** [comment]
@jumps-are-op do u even know how mindustry work

**Comment by AtobaAzul** [comment]
> no it's bad
> what if there is a team with no core from the start

It could just happen when the core is _destroyed_, not because it doesn't exist.

**Comment by genNAowl** [comment]
Free resources from deconstructing enemy team blocks 👀
