### ISSUE TITLE
small things foundation mining

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2683]
**Describe the content or mechanics you are proposing.**
Currently, when you're controlling a foundation when you mine near core, your unit will drop items directly to core, but other units in foundation didn't and store the items in their inventory, so make it drop directly into core then?
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
just make the units foundation a lil' better, also less hand-working
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
units will mine until their inventory fills and then drop all items at once. if you see, for example, monos, mining a single tile forever, they are going to dump a stream of items every few seconds

**Comment by Ineedause** [comment]
That is not true when controlling alternate units such a monos. When their inventory fills up it stays full forever until you unbind them or manually release all their resources.

**Comment by oinkymoo** [comment]
that is logic only tho i think

**Comment by vinhsad** [comment]
Vào Th 7, 10 thg 7, 2021 vào lúc 22:24 oinkymoo ***@***.***>
đã viết:
