### ISSUE TITLE
Free moving camera and mobile like controls for PC?

### ISSUE THREAD

**Issue by Not-So-Lazy-Programmer** [Anuken/Mindustry-Suggestions#2684]
I played Mindustry on mobile for a long time, and today I decided to buy it and try it out on Steam (PC). I am so used to freely moving around the map and having my drone auto fire on mobile. But moving around with the camera fixed on the drone and manually firing is something that bothers me. I was hoping to click and drag the camera around with the auto fire (just like the mobile version). I notice I couldn't find options to adjust it as close to the mobile version at all. Is it possible that there will be more variety options for controls in the future?

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RouterChainsSuckk** [comment]
You can do it on pc, with the = key I think, however it's very shit so I recommend foos client

**Comment by oinkymoo** [comment]
you can already freecam on pc, though the default bind for it is mouse3 or mouse4, one of the extra buttons on the side of like, gaming mice. you can also pause with space and then move the camera with wasd. that being said, i do agree that an autotarget like on mobile would be nice.

with that out of the way, this is an unfriendly reminder that you are supposed to use the template. also, you lied on the second checkbox

**Comment by Ineedause** [comment]
On top of that, rebind the key to something accessible like y, my favorite key to do so.

**Comment by oinkymoo** [comment]
i use h personally
