### ISSUE TITLE
Master Volume Slider

### ISSUE THREAD

**Issue by uhhhhwhat** [Anuken/Mindustry-Suggestions#2685]
**Describe what you would like changed, and why.**

i want to have the audio menu changed to have a "Master Volume" slider, so that if youre listening to a podcast while playing, you dont have to remember your sound controls or write them down before you turn them to zero

**Describe the changes you want to propose. Include possible alternatives.**

Master volume slider so you can control the overall playback volume of the game without individually changing every setting.

**Comment by SMOLKEYS** [comment]
this is supposed to be a feature request but ok

**Comment by oinkymoo** [comment]
honesstly just a master mute button would be fine with me
