### ISSUE TITLE
Naval Defenses

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2686]
**Describe the content or mechanics you are proposing.**

Defense block that only be place on water that can only target air/naval

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Making the shore a viable building space in large ocean maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
> Defense block

do you mean turret?

**Comment by itcannotbe** [comment]
> > Defense block
> 
> do you mean turret?

Do use a turret alone?
Of course you also need a wall to cover it.

**Comment by itcannotbe** [comment]
Also on the subject of anti-naval naval turret.

Basically Torpedo Launcher. The bullet dies when it's not in water aanymore/hits other tiles except water.

**Comment by OnyxFinger** [comment]
I find this a cool idea
ca defenitely feel right and make sense since boats are stronk in this game

**Comment by Humanoid-X** [comment]
~You can actually use units to create a wall + turret band~

**Comment by oinkymoo** [comment]
> > > Defense block
> > 
> > 
> > do you mean turret?
> 
> Do use a turret alone?
> Of course you also need a wall to cover it.

Are you seriously proposing a wall that obstructs naval and air but not ground

**Comment by itcannotbe** [comment]
> > > > Defense block
> > > 
> > > 
> > > do you mean turret?
> > 
> > 
> > Do use a turret alone?
> > Of course you also need a wall to cover it.
> 
> Are you seriously proposing a wall that obstructs naval and air but not ground

I think you have reading comprehension issues.

**Comment by itcannotbe** [comment]
Does a wall even target blocks? No.

So how on earth would a statement about something that shoots something suddenly applies to walls?

**Comment by oinkymoo** [comment]
> Does a wall even target blocks? No.
> 
> So how on earth would a statement about something that shoots something suddenly applies to walls?

you said "you also need a wall to cover it" also targeting is not necessarily shooting. also that comment implied to me at least that you were suggesting other defenses in addition to turret, which i could only assume would be wall

**Comment by vinhsad** [comment]
or a turret that placed at the liquids-side that launch sub-merge rocket that tracking by 8-way moving?

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by OnyxFinger** [comment]
yeet
so

> or a turret that placed at the liquids-side that launch sub-merge rocket that tracking by 8-way moving?

8 way movements wouldn't be very good in my opinion. They'd feel unnatural

**Comment by OnyxFinger** [comment]
I think this is going to be a stale isn't it
