### ISSUE TITLE
Core Loadout QOL

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#2687]
**Describe what you would like changed, and why.**
More control on the increments made in using +/- buttons.

Basically an alternative suggestion to #2680 

**Describe the changes you want to propose. Include possible alternatives.**
Add 10 100 1000 buttons for finer control outside of actually typing in the value you want and allow the button to be held instead of just clicking on it multiple times.

**Comment by genNAowl** [comment]
Won't this just cause extra bloat to the loadout screen?

**Comment by Humanoid-X** [comment]
i say yes to helding button

**Comment by itcannotbe** [comment]
> Won't this just cause extra bloat to the loadout screen?

Not exactly. You can either put the increment change button per item (more bloated) or as something that controls everything increment (like if I set it as 100, every +/- will now be +/- 100. Preferably it should be near the max button.)

**Comment by SMOLKEYS** [comment]
> Won't this just cause extra bloat to the loadout screen?

Loadout screen is kinda empty, so not really?

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
