### ISSUE TITLE
New logic instruction

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#2688]
**Describe the content or mechanics you are proposing.**

A logic instruction that looks at total friendly units on the map

(Could be used fights)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will make binding single units more convenient and it will shorten code substantially. This is also useful for when a schematic requires units to work for example as a means to carry items to ths core when space is limited

Heres more detained because this is being misunderstood

1. This also includes the ability to display available units to bind and not be used for combat unless absolutely necessary (this mostly meant for production but has uses in combat)

2. This will also include a new option in the sensor to look at the unbound units

3. This will be useing a set to set the amount of units you want

This list may grow if i can think of any more details for this to help reduce code size and *hopefully* reduce code lag which is a huge problem with single processor builds

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by vinhsad** [comment]
you can make a logic counter
stop trying to add more useless instruction, just use your brain

**Comment by XxsuperdeadlysniperxX** [comment]
This takes a lot of code and its a nightmare to troubleshoot if it breaks because your having to use a counter i tried useing a counter and for some unknown reason my code exploded and i couldn't figure out why

**Comment by XxsuperdeadlysniperxX** [comment]
> you can make a logic counter
> stop trying to add more useless instruction, just use your brain

Remember the longer the code the bigger the processor once the code exceeds the biggest processor then it slows massively or explodes in to a billion errors

I reason why this feature request exists is to cut down the size of the code and eliminate the slow code issue

Btw useing multiple processors are buggy and lead to my code also not working so this is not going to work

**Comment by XxsuperdeadlysniperxX** [comment]
Oh yeah i forgot to mention that a counter will break if even the slightest chamge is made to the logic system or the game in general this is why this exists as well so people can their code more stable

**Comment by Kyllingene** [comment]
What tiny, nearly nonexistent usecase does this have? And, how do you counter the fact that you can easily use it to determine how many units the enemy has automatically?

**Comment by XxsuperdeadlysniperxX** [comment]
This is not used for the enemy its used for schematics for production

**Comment by Kyllingene** [comment]
Just because that is what it is *meant* for (not that that seems super useful), doesn't mean it won't be used, or abused, elsewhere.

**Comment by XxsuperdeadlysniperxX** [comment]
Yes i understand this i include a little more details but this would mostly be useful in schematics combat might prove useful too

**Comment by XxsuperdeadlysniperxX** [comment]
@Kyllingene im trying to make it useful but plz if you can proved more info im all ears
