### ISSUE TITLE
Some sort of long distance liquid transport

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2689]
**Describe the content or mechanics you are proposing.**
A new flying unit line that can carry liquids. The following is a suggestion. Feel free to change the actual attributes/behaviors.

All units can take liquids out of and deposit them into liquid tanks and conduits. All units' weapons apply the effects respective of their carried liquids (burning for slag, wet for water, etc.)

T1 - Carrys a small amount of liquid, no weapons, fast flying speed.
T2 - Carrys a small amount of liquid, no weapons, can mine liquids (very slowly, we don't want to put pumps out of business).
T3 - More liquid capacity and faster liquid mining speed (still slow). Carries a Wave Turret-like gun that fires whatever liquid it is carrying. If it is empty, it can't fire at all. (Should this mechanic be affected by "units require ammo"?) (Requires balancing and working of exact weapons so as to not make Turret buildings obsolete.)
T4 - More capacity, decent liquid mining speed, and carries a tsunami turret with the same mechanics as a T3.
T5 - Extremely high capacity. Weapon is a single liquid "bomb". It dumps its entire payload of liquid on the spot creating a AOE attack who's range and damage is affected by how much liquid it carries. A full dump can do quite a bit of damage (after all, water itself might not be harmful to anything but it's very heavy and you've seen the damage that floods can do :P).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
There is no good way to get liquids across the map when obstacles exist (space tiles, walls, etc.). For items we have dozens of units available for item transport, logic to control them, phase bridges, and mass drivers. If the distance is greater than a liquid phase bridge's range then it becomes impossible to transport liquids at all across those kinds of gaps in terrain.

I think people would appreciate a flying unit that can carry liquids. If you're not going to add a liquid mass driver this seems like the next best option.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
This is off-topic but yay I got access to my GitHub again :smile:

**Comment by MrDuck557** [comment]
Liquid mass driver seems easier than making a new class with totally different mechanics ngl

**Comment by vinhsad** [comment]
> Liquid mass driver seems easier than making a new class with totally different mechanics ngl

it not gotta be added :3

**Comment by vinhsad** [comment]
> This is off-topic but yay I got access to my GitHub again

it's not "mine" liquid, PUMP liquid
why we need a tree just for liquids unit, why not for "industtry unit" like item/liquid transport, boosting build, bla bla it's better than **a whole tree just for transporting liquids**

**Comment by itcannotbe** [comment]
> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> There is no good way to get liquids across the map when obstacles exist (space tiles, walls, etc.). For items we have dozens of units available for item transport, logic to control them, phase bridges, and mass drivers. If the distance is greater than a liquid phase bridge's range then it becomes impossible to transport liquids at all across those kinds of gaps in terrain.

Um. Your use case is all over the place
If your only goal is longer range liquid transport why not just pick up the freaking tank.

**Comment by oinkymoo** [comment]
while i will admit that itcannotbe's solutions are probably much more efficient, i will say that i'd rather see a more complicated long-range liquid transport system other than _yet another_ mass driver

**Comment by SMOLKEYS** [comment]
> can mine liquids
funny cursed words magic man
