### ISSUE TITLE
Logic: lookup returns content ID when input a type constant

### ISSUE THREAD

**Issue by BlackDeluxeCat** [Anuken/Mindustry-Suggestions#2691]
**Describe the content or mechanics you are proposing.**

Let lookup instruction returns content ID when input a type constant
An example: run "lookup item result @ copper", and result should equals 0. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently lookup can convert a numerical id to a type. 
However, it can't convert type to id. I still need a terrible for-block to make it, which is stupid and costs time. I think lookup is liable. 

This new feature will solve the problem in **1** instruction. 
.
.
.
A similar question: how to transmit contenttype(currently choosen in a spinner)? I think contenttype should has its content id. 
(It seems much less useful right now and doesn't value a new issue.)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NiChrosia** [comment]
Why not just a `id` property that could be accessed from it?
