### ISSUE TITLE
affinity/required tile display

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2692]
**Describe what you would like changed, and why.**

it was recently changed so that blocks that function better on different tiles will only display tiles on their info pages that actually exist in the map, however, when none of the tiles are present, the list of affinities will instead say \<none found>. this looks like a glitch, and [i reported it as such](https://github.com/Anuken/Mindustry/issues/5571)

**Describe the changes you want to propose. Include possible alternatives.**

make it more clear that there are no tiles being found by the in-game entity writing the info, rather than by the game, for example by changing the message to something along the lines of \<none found in local area>.

**Comment by Anuken** [comment]
I already changed it to "none in map".
