### ISSUE TITLE
Add multiple maps at once and make launch pads useful in custom game like in campaign

### ISSUE THREAD

**Issue by Antonin-duda** [Anuken/Mindustry-Suggestions#2693]
A useful feature that lets you have multiple maps in one game and use launch pads to launch resources between maps in a custom game.
I am not sure if this is a good idea though...

**Comment by Ineedause** [comment]
First, Template is where?
Second, You need to elaborate more, I can't make out what you are trying to say

**Comment by Kyllingene** [comment]
This is close enough to other suggestions to be most likely ignored, but far enough that the same arguments don't quite apply.

**Comment by Antonin-duda** [comment]
> First, Template is where?
> Second, You need to elaborate more, I can't make out what you are trying to say

I am sorry for bad grammar and no template. this is my first post.

**Comment by oinkymoo** [comment]
> > First, Template is where?
> > Second, You need to elaborate more, I can't make out what you are trying to say
> 
> I am sorry for bad grammar and no template. this is my first post.

there is a reason that there's not an option for "no template"

**Comment by uujuju1** [comment]
launchpads can be userful without the even resource distribuition in cores.
Example: make a launchpad launch to another core in the map that doesnt have enought items to make things and add a core radius for use items from specific cores
