### ISSUE TITLE
Do something with Laser Drill because it sucks

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2694]
![Screenshot from 2021-07-14 17-39-26](https://user-images.githubusercontent.com/40753025/125642126-2a5032e2-ad4d-4217-9eb2-3e508a15c627.png)
![Screenshot from 2021-07-14 17-42-42](https://user-images.githubusercontent.com/40753025/125642137-06f62f65-c8b4-4d67-96dc-220aa19c07e0.png)
***the problem***
There is no reason to use laser drills (unless you don't have thorium or the space is tight)
Well, if you don't use water extractors (or you do pump water) Airblast Drill is using 20% more energy than Laser Drill.
But, if you do use them Laser Drill is using 9% more energy with more space required (if it's sand e.g.)

*why do laser drill even exist*

**Comment by Slava0135** [comment]
P.S. I forgot Airblast uses 6 water/s and pump generates 6.6 so actually the power consumption is 1080 - 360 * 10% = 1054, the difference is 11%
Spore press presents 1/2 of watex energy consumption

**Comment by IIINSTINCT** [comment]
They exist to mine thorium 
And unlock airblast


Well the main problem is laser drill is more useful on campaign because it would take longer to unlock the airblast but in normal maps you would just need to get few thorium to open airblast

**Comment by Slava0135** [comment]
> They exist to mine thorium
> And unlock airblast
> 
> Well the main problem is laser drill is more useful on campaign because it would take longer to unlock the airblast (tech tree thing) but in normal maps you would just need to get few thorium to open airblast
> 
> The only way to make laser drill have uses is nerf airblast?

if you make Airblast consume cryo it would make a difference but liquid used in drills is not for cooling purposes

**Comment by oinkymoo** [comment]
that's like, the point of upgrades. by the same logic, graphite presses and silicon smelters also suck

**Comment by Slava0135** [comment]
> that's like, the point of upgrades. by the same logic, graphite presses and silicon smelters also suck

no, because for Multipress you need water and for Silicon Crucible you need lead

**Comment by oinkymoo** [comment]
ya and for airblast you need water or you're just wasting power they are less power-efficient unless boosted

**Comment by BlueWolf3682** [comment]
Laser drill is fine, I widely use it before campaign endgame because of airblast's power cost. It doesn't really need a buff or nerf.

**Comment by Bottinator22** [comment]
Airblast is a direct upgrade to laser drills. And look at poor old Mechanical Drill, how useless it is, only existing to get replaced with Pneumatic Drills later on after you get graphite.

**Comment by Slava0135** [comment]
> Airblast is a direct upgrade to laser drills. And look at poor old Mechanical Drill, how useless it is, only existing to get replaced with Pneumatic Drills later on after you get graphite.

But Pneumatic Drills are more expensive while Airblast cost less for more (considering that thorium is easier to produce than graphite)

**Comment by Sector171** [comment]
Indeed
Except for getting thorium, I don't use them, even when updating the drills I don't pass through the intermediate stage, I wait until getting enough power & thorium then replace all pneumatic drills with airblast.
Forget about cryo issue, it is very very bad idea and will make the game much worse and less flexible, cryo for drills no way!!
The solution in my opinion is : reducing the water needed to 3 so that one water extractor can support 2 laser drills, this may make them a practical choice in some ceses( ofc reducing as well the water needed for pneumatic drill as well)

**Comment by itcannotbe** [comment]
Here's a stupid idea:

Make airblast drill use blast

**Comment by vinhsad** [comment]
> Here's a stupid idea:
> 
> Make airblast drill use blast

n o

**Comment by Slava0135** [comment]
> Here's a stupid idea:
> 
> Make airblast drill use blast

y e s

**Comment by Bottinator22** [comment]
Look at the name of the thing. I believe it's meant to blast stuff with air. It's an airblast drill, not a blastblast drill.

**Comment by Humanoid-X** [comment]
yes blast

**Comment by Bottinator22** [comment]
no blast

**Comment by oinkymoo** [comment]
maybe blast

**Comment by genNAowl** [comment]
To be honest making airblast drills use blast would be an instant turn off for basically all players that use them.

**Comment by Slava0135** [comment]
> To be honest making airblast drills use blast would be an instant turn off for basically all players that use them.

Would be fun to see

**Comment by vinhsad** [comment]
> Airblast is a direct upgrade to laser drills. And look at poor old Mechanical Drill, how useless it is, only existing to get replaced with Pneumatic Drills later on after you get graphite.

you need mechanical drill to get coal, then you can get graphite
it's a progression, you need to **progress**

**Comment by itcannotbe** [comment]
> > Airblast is a direct upgrade to laser drills. And look at poor old Mechanical Drill, how useless it is, only existing to get replaced with Pneumatic Drills later on after you get graphite.
> 
> you need mechanical drill to get coal, then you can get graphite
> it's a progression, you need to **progress**
> it exist to mine ore

It's not even progression if it's only purpose is mine thorium for a insignificant amount of time and gets immediately replaced by an airblast drill.

Plus the ores the airblast and the laser can drill is just the same. What's the point then?
