### ISSUE TITLE
Deadly space

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry-Suggestions#2695]
**Describe the content or mechanics you are proposing.**
In environments with gravity (ground units shouldn't work at all in environments without gravity) change space tiles so that, instead of blocking units from passing, the units can go in, and will "fall" and silently (and smoothly) disappear, effectively dying. Leg units won't immediately fall, instead they will fall at the point they'd normally be blocked by normal walls. If water happens to be adjacent to space, allow naval units to fall as well.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently, for some reason units can go onto slag, tar, and deep water, things that will kill them, but they can't pass over space. This will also make some more sense and make leg units more useful in maps with space.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
"If water happens to be adjacent to water"

**Comment by oinkymoo** [comment]
space is an endless void, what do you propose leg units are standing on?

**Comment by Bottinator22** [comment]
"If water happens to be adjacent to water" oop
"space is an endless void, what do you propose leg units are standing on?" the ground? yk with normal walls, where a leg unit can go into a wall a little? That's what I'm thinking here might keep the leg unit from falling immediately

**Comment by RedstonerKBC** [comment]
Good idea. I like it. Irl units can't just walk off the edge to their space doom, nor can water flow into space. That would imply the Earth is flat O.o Luckily Mindustry is a 2D game not a 3D game.

**Comment by vinhsad** [comment]
how they fall when **there's no gravity?**

**Comment by Bottinator22** [comment]
Ground units shouldn't work at all in actual no-gravity environments. I'm proposing this for environments with gravity that contain space tiles.

**Comment by Bottinator22** [comment]
Even if ground units do work in no-gravity environments, if they go off the edge they'd probably just float off uncontrollably until they either encounter ground, or they encounter the edge of the map, which would delete them.

**Comment by oinkymoo** [comment]
> "space is an endless void, what do you propose leg units are standing on?" the ground? yk with normal walls, where a leg unit can go into a wall a little? That's what I'm thinking here might keep the leg unit from falling immediately

i understand it to be them going up the wall, you know, like spiders. that doesnt explain how they would avoid falling to their death if they walked all the way of a cliff
