### ISSUE TITLE
Alternative t3 reconstructor

### ISSUE THREAD

**Issue by B1bABobA** [Anuken/Mindustry-Suggestions#2696]
Alternative version of t3 recontructor, which can make a ununpradable units, such as javelin from v5 (upgrades from horizon) or new types of units (t3 unit whith repairing cannons, upgrades from atrax).
This would let to add new units and not to add new branches of them.

**Comment by oinkymoo** [comment]
fairly certain this is doable with mods already. also template exists for a reason. what would this add to the game

**Comment by B1bABobA** [comment]
> 
> 
> fairly certain this is doable with mods already.
You can say it about a lot of feathures such as silicon tigel or new v7 units.

**Comment by oinkymoo** [comment]
> silicon tigel

what

you also didn't explain what it would add to the game.

also, 

> This would let to add new units and not to add new branches of them.

this is what i was referring to when i said doable with mods. i'm fairly certain reconstructors literally just have a list of units that they take in and what each of those units come out as
