### ISSUE TITLE
Multi platform for mod

### ISSUE THREAD

**Issue by GGG1414** [Anuken/Mindustry-Suggestions#2697]
Dear Anuken, I recently realized that I was not satisfied with the game content in the morning, and I decided to install a couple of modifications. But they also soon got tired, and I decided to make my own mod, but I am the owner of the android platform, and it is IMPOSSIBLE to install a custom mod on it. And for this I would like to find out whether the introduction of the mod installation function on android will be, and if so, when exactly. P.S. in any case, thank you for the answer.

**Comment by Ruichka** [comment]
1. template
2. i'm pretty sure this is already implemented

**Comment by NiChrosia** [comment]
You can already create multi-platform mods.
