### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#2698]
some ideas.

a block which allows you (the player) to turn into a ground unit and back into an air unit, also a water unit because why not...

thermal / water powered drill.

wind power.

nuclear power.

tier 6 units with shields.

a way to make your tsunami / wave turrent only put out fires without logic (idk if it exists but if not i beg you i lost in impact 0078 2 times because of this)

electric conveyors (faster conveyors)

ill post if i have more ideas.
mkay thanks for reading this.

**Comment by Kryvytsky** [comment]
> a block which allows you (the player) to turn into a ground unit and back into an air unit, also a water unit because why not...

Why? We already can control units. Double touch on mobile / L Crtl on PC. 

> thermal / water powered drill.

What is that mean? 

> wind power.

Ok
> nuclear power.

Doesn't Thorium Reactor is same thing? 

> tier 6 units with shields.

Probably any tier 6 not gonna happen

> a way to make your tsunami / wave turrent only put out fires without logic

Why? Just use processor to control Tsunami if you want. 

> electric conveyors (faster conveyors)

Probably not gonna happen.

**Comment by itcannotbe** [comment]
Author be like: 
-
[X] I am incapable of completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
Author be like:

> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
> 
> Yes

**Comment by idontknowhwhattoputhere** [comment]
it will add more variety. plus i just realized i can scroll in trello lol

**Comment by idontknowhwhattoputhere** [comment]
@Kryvytsky 
-a block which allows you (the player) to turn into a ground unit and back into an air unit, also a water unit because why not...
but you cant turn into a ground unit it will be useful if you want to defend your base yourself.
-thermal / water powered drill.
as in you drill using water or heat, like thermal generator or spin the drill with water pumps.
-wind power.
ok
-nuclear power. put in uranium and leave it and like real life it generates a decent amount of electricity, plus i hate wasting thorium
-tier 6 units with shields.
i dunno dont ask me
-a way to make your tsunami / wave turrent only put out fires without logic
idk how to use processer plus its beter for new players
-electric conveyors (faster conveyors)
just realized phase conveyor is a thing...

**Comment by itcannotbe** [comment]
You don't re-suggest things already listed anywhere in the trelli.

**Comment by IIINSTINCT** [comment]
1. Why u need a block to turn control a unit? double tap or press a key to control  a unit already exists 

2. Wdym by this? Thermal power drill is just like Thermal generator producing power to power laser drill is basically the same thing 

3. Nuclear tech is coming and thorium reactor is basically the same thing

4. No It will never happen (Mods alternative response)

5. Water wave or tsunami automatically targets fire wdym

6. No


7. Lastly You YEETED THE GOD DAMN TEMPLATE

**Comment by SMOLKEYS** [comment]
> Crtl

Ah, i guess im not the only one who misspells CTRL.

**Comment by itcannotbe** [comment]
1. YOU CAN ALREADY POSSESS ANY UNIT.
Also. Have you played the game a considerable amount before even making a suggestion beforehand?

2. You realize how dumb that sounds? Higher tier drills use power already. Pumping water uses power*, Heat? You can make power out of them, so it would be nothing more than useless bloat.
Also. Have you played the game a considerable amount before even making a suggestion beforehand?

3. Wind isn't a thing in mindustry. So basically what you are suggesting is making wind a thing, then making wind power generation.
Also. Have you played the game a considerable amount before even making a suggestion beforehand?

4. YOU DON'T SUGGEST THINGS LISTED IN THE TRELLO. -_-.

5. The Dev be like: "Incredible. Nobody has ever even considered suggesting More Units before. This is a revelation. I would never have thought of adding More Units myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Units immediately."
Adding in more units isn't a trivial thing to do. If you have played the game a considerable amount before even making a suggestion beforehand, you would notice that most units have something other units doesn't have.

6. Have you considered controlling the wave turret in the first place?
Also. Have you played the game a considerable amount before even making a suggestion beforehand?

7. An even faster conveyor?
Have you played the game a considerable amount before even making a suggestion beforehand, you would realize there are a conveyor that can already exceed 100+ items/second that exists in the game already -_-

**Comment by idontknowhwhattoputhere** [comment]
1) turn into a ground unit yourself not control one

2) it takes less space and water powered is a decent idea if u ask me

3) yes and kinda

4) good to know

5) it pushes away enemies(thats also how i lost to impact 0078 again)  and turrents like fuse cant hit it

6) again dont ask me

7) good for you

im closing this

**Comment by Bottinator22** [comment]
btw itcannotbe wind is technically a thing in Mindustry, look at the spore storms and such.

**Comment by idontknowhwhattoputhere** [comment]
yes

**Comment by notrealn** [comment]
maybe he wants turbines like the ones in rimworld: there is no wind direction, wind doesnt affect anything other than turbines, and weather events can change the wind speed

i think this is redundant, solar already exists if you want power from nothing and unlike in rimworld you can just infinitely mine coal/thorium for fuel.
