### ISSUE TITLE
Levels for towers

### ISSUE THREAD

**Issue by Lo118** [Anuken/Mindustry-Suggestions#270]
Towers can level up for doing what they do... the higher the level the more efficient it is. Example: when I place a drill it only has 90% of efficiency but when it survives 1/2/3 rounds it gets a lvl up and goes up to maybe 95% efficiency and that repeats until the drill is at 110% efficiency so you get rewarded for keeping them alive and you think twice before rebuilding because you lose that bonus so you thy to build as efficient as possible in the first place.

**Comment by itcannotbe** [comment]
#157 Might be related to this.

**Comment by Anuken** [comment]
This has been suggested to death.
