### ISSUE TITLE
Planetary driver README.md

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#2700]
Planetary driver.

can transport materials liquids electricity units and units (tier 1 and 2)  

Basically its like a mass driver but it can send resources From sector to sector, for example if you are low on metaglass but have alot of metaglass on another sector you can send it using planetary driver and linking. A simmillar mechanic could be used From planet 1 to planet 2. 

As for driver linking you go on the world map and for example Press a "link button" the click on sectors that are shaded green (that means it has atleast 1 mass driver) and The you choose which planetary driver to link then you pick the other sector to link it to, pick another planetary driver to Collect it, the it Goes out on an output conveyor on the other sector.

This Would allow to make a sector a silicon farm based on only silicon for example, and if you need phase fabric you can send it with the planetary driver.

Or when you start attacking a base you can make a base a planetary driver (for example it sends blast compound) and full the turrents with it.

Another fun idea would be linking enemy bases that might a challenge. Or an enemy planet thats linked...

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JrTRinny** [comment]
I don't think you know that Launch Pad exists

**Comment by IIINSTINCT** [comment]
Launch Pads BRUHHHHHHHHHHHH

**Comment by TheRealIvyX** [comment]
> [check] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

you clearly arent

**Comment by idontknowhwhattoputhere** [comment]
A launch pad can be loaded with only 100 items. and has a time invertal. this is an alternative which can transport more

Once 100 items have been put into a launch pad it will not accept any more input until it launches its contents

and it has a 20 second time invertal. doesnt it pay off to have 1 planetary driver?

**Comment by idontknowhwhattoputhere** [comment]
plus it might not be able to launch to other planets. this might be good for interplanetary item transport

**Comment by JrTRinny** [comment]
so you suggest bigger Launch Pad?
damn, regular Launch Pads are already OP, especially when launch in groups

**Comment by TheRealIvyX** [comment]
> A launch pad can be loaded with only 100 items. and has a time invertal. this is an alternative which can transport more
> Once 100 items have been put into a launch pad it will not accept any more input until it launches its contents

then just use several launch pads

**Comment by idontknowhwhattoputhere** [comment]
im suggesting an alternative for faster transport plus you would need 3 thorium reactors to power 10.

plus idea. make it send electricity i guess

**Comment by idontknowhwhattoputhere** [comment]
ngl im kinda new but i did my research plus you could make it transport liquids

**Comment by idontknowhwhattoputhere** [comment]
it doesnt have to be only materials

**Comment by idontknowhwhattoputhere** [comment]
or even better make it launch (so its not to op) tier 1 and 2 units

**Comment by Hyrotrioskjan** [comment]
> ngl im kinda new but i did my research plus you could make it transport liquids

transport liquids???? how would that even work??

**Comment by idontknowhwhattoputhere** [comment]
uhh connect it to liquid pipes i guess

**Comment by idontknowhwhattoputhere** [comment]
tbh this game is fictional

**Comment by idontknowhwhattoputhere** [comment]
just an idea...

**Comment by TheRealIvyX** [comment]
> plus idea. make it send electricity i guess

just launch the materials required to make power

> ngl im kinda new but i did my research plus you could make it transport liquids

just make the liquids in the sector you want to use them none of the liquids in the game are hard to make (cryofluid is the hardest to make and you only need water and titanium to make it)

> or even better make it launch (so its not to op) tier 1 and 2 units

just launch the materials required to make the units

**Comment by idontknowhwhattoputhere** [comment]
you can make an energy production complex to power like 20 sectors isnt that easier

might be low liquid needing you to use energy

make a gigafactory, again

**Comment by idontknowhwhattoputhere** [comment]
okay im going to put it like this, if you make 16 ground factories which each make units. it will be fairly easy to supply units (like building units to a new base) to make bases faster.

**Comment by TheRealIvyX** [comment]
> you can make an energy production complex to power like 20 sectors isnt that easier

unloading thorium from the core into like 30 rtgs isnt the hardest thing in the world

**Comment by itcannotbe** [comment]
Players have been pointing almost everything into one sector then from there with the help of a lot of launch pads, points every one into one sector that they're trying to conquer.

I don't get it why do you want more.

**Comment by idontknowhwhattoputhere** [comment]
you dont get my point do you...

**Comment by itcannotbe** [comment]
You don't get our point do you?

**Comment by idontknowhwhattoputhere** [comment]
i do...

**Comment by itcannotbe** [comment]
You don't.

**Comment by idontknowhwhattoputhere** [comment]
if  you want hard mode assume that there is an energy shield in areas with waves so you cant  send stuff

**Comment by idontknowhwhattoputhere** [comment]
i dunno i aint the dev

**Comment by itcannotbe** [comment]
Why does this and your previous suggestion struggle to be coherent.

Also this block you are suggesting does too much things, plus it doesn't address the fact that your suggesting a block that has functions already existent in the game which is overpowered in the first place.

**Comment by Hyrotrioskjan** [comment]
Please just close this and use Launch pads.

**Comment by idontknowhwhattoputhere** [comment]
im not saying it has to be like this. you can make it send only energy. or be an endgame block like the interplanetary accelerator.

im done here.

**Comment by SMOLKEYS** [comment]
> im done here.

then close it

**Comment by USMP-lancer** [comment]
> im not saying it has to be like this. you can make it send only energy. or be an endgame block like the interplanetary accelerator.
> 
> im done here.

idea would be both potentially too powerful, and unrealistic, not to mention useless, worried about launch pads not launching fast enough? just build more launch pads

**Comment by idontknowhwhattoputhere** [comment]
.

**Comment by JrTRinny** [comment]
finally closed
