### ISSUE TITLE
New Level Editor Wave Presets

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2701]
**Describe the content or mechanics you are proposing.**
Presets for waves for custom maps based off the campaign difficulties, like Easy, Medium, Hard, Extreme, Eradication

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A Nice QoL for mappers, greatly reducing time spending more intricate maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/ahttps://trello.com/b/aE2tcUwF/mindustry-trello)E2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JrTRinny** [comment]
maybe some display like "Threat: High" like that?

anyways great suggestions, I support this

**Comment by oinkymoo** [comment]
the approximate threat level of your waves would definitely be good

**Comment by Hyrotrioskjan** [comment]
yes
