### ISSUE TITLE
Snow

### ISSUE THREAD

**Issue by MostForgettablePerson** [Anuken/Mindustry-Suggestions#2703]
**Describe the content or mechanics you are proposing.**
Make snow weather cause freezing effect

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1) Rain cause wet effect so why not
2) Makes blast compound ammo useful
3) Makes units slow at retreating so you don't have to beat it for the 37th time

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WilloIzCitron** [comment]
y e s

**Comment by JrTRinny** [comment]
y e s

**Comment by idontknowhwhattoputhere** [comment]
y e s

**Comment by oinkymoo** [comment]
maybe not freezing, but a lesser version of the same effect. still support tho

**Comment by Humanoid-X** [comment]
yes lol
