### ISSUE TITLE
Give all (or most) bullets knockback

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2704]
**Describe what you would like changed, and why.**
It seems reasonable that all bullets, for which it's reasonable to have knockback, should actually have knockback - why would a wall of high-speed bullets not knock enemy units back?

**Describe the changes you want to propose. Include possible alternatives.**
Give duo, scatter, swarmer (?), salvo, fuse, cyclone, foreshadow knockback - perhaps also give units knockback as well?

**Comment by idontknowhwhattoputhere** [comment]
for some units, i think it works with tsunami

**Comment by idontknowhwhattoputhere** [comment]
on air units

**Comment by Ilya246** [comment]
By "knockback" i did not mean a lot of knockback, just some amount so at least, say, flares can get pushed back, larger units would get pushed back only by an entire defensive array

**Comment by idontknowhwhattoputhere** [comment]
agreed

**Comment by oinkymoo** [comment]
i agree that it should be non-0 but significantly less than any turret that currently has knockback

**Comment by genNAowl** [comment]
Would be pretty easy to just write one line in `init()` that would give bullets knockback proportional to their size/damage.
