### ISSUE TITLE
Allow to zoom further

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2705]
**Describe what you would like changed, and why.**
The problem is that you can't see far enough upwards or downwards on PC. You can't see foreshadows because of this for example.

**Comment by LeoSko** [comment]
Use pan view?

**Comment by BorisA11** [comment]
You can use pan view, see the controls in settings. And I am pretty sure there are multiplayer compatible zoom mods

**Comment by BlueWolf3682** [comment]
alrighty lemme just take a quick sip of my soda before i comment
\*soda explodes in face\*
yeah cool
*anyways*
[h.](https://github.com/MEEPofFaith/testing-utilities)

**Comment by Sector171** [comment]
Extended zoom mod, I don't play without it, it is compatible with multiplayer.

**Comment by Humanoid-X** [comment]
Zoom mods, for example sk7725/testing-utilities
