### ISSUE TITLE
Blocks liquid loader/unloader

### ISSUE THREAD

**Issue by Dinistor** [Anuken/Mindustry-Suggestions#2706]
**Describe the content or mechanics you are proposing.**

There is now a mechanic, that allows to transport blocks via payload mass drivers, like vaults or containers, and put 3x3 blocks on payload conveyor. Also there are blocks, wich are not in game yet (block loader/unloader), that can unload containers from conveyor belt. So I  propose make "block liquid unloader" and "block liquid loader" - blocks, that unloads/loads liquid tanks on the payload conveyor, like blocks unloader/loader does with vaults/containers. Of course this blocks will be needed if blocks 'block-loader' and 'block-unloader' will get into a game.

*Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

For now, in game there's no way to transport liquids via mass drivers, and phase bridges sometimes are too short. Just some form of liquid mass driver transfer, like with items, but for liquids.

~~p.s. Payload conveyor, vaults and blocks loader/unloader technically leads us to "any transportation system that uses something analogous to rails" in "A few things you shouldn't suggest" category, so i think *maybe* this will never get into  a game~~

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BorisA11** [comment]
Alternatively, make the same loaders and unloaders be conduit compatible.

**Comment by Dinistor** [comment]
Yes, this will be better alternative

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/245#issuecomment-674445442

**Comment by IIINSTINCT** [comment]
Too bad not gonna happen

**Comment by Dinistor** [comment]
> [#245 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/245#issuecomment-674445442)

Oh well gg then
