### ISSUE TITLE
Make processors able to link

### ISSUE THREAD

**Issue by TNTima** [Anuken/Mindustry-Suggestions#2707]
Processors can do everything that a player can do: control units, build using them and now even break blocks (Payload Deconstructor). But there is one thing that processors cannot do: connecting other processors, power nodes, bridges and phase pipes / pipelines. IMHO in order to increase the automation capabilities of automatic building by units, this needs to be fixed. To do this, you need to teach processors to detect connections between objects and, in fact, connect.
There are two ways to teach processors to detect connections:

> Designation: (parameter), [output, output].

- New parameter Sensor: `[True / false] @linked in (object, from block) to (object, to block)`
   But then it turns out that Sensor will have two arguments.

Or

- Change Get Link command: `[object] = link # (integer, index) in (object, from block)`
  The new Control command will connect and disconnect blocks:
Control `Set link of (object, from block) to (object, to block) link (true / false; connect / disconnect)`

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
the first one could maybe be changed to 2 separate sensable properties. `@linked` says if it is linked to something, while `@link` returns the block to which it is linked, though it would probably work better for bridges and such which have exactly 1 link. the control option you have in the second option is what i was thinking as well. checking if 2 blocks are linked to one another i think should be in sensor still but i don't know how how it would work within the current constraints of the command
