### ISSUE TITLE
[Discord] Please end #schematics spam

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2708]
**Describe what you would like changed, and why.**

People spam incredibly in #schematics. End it
Warn and later ban the spammers, delete their spam. I am really tired of scrolling for miles to find a decent schematic.

**Describe the changes you want to propose. Include possible alternatives.**

-6h slowmode on the channel
-needed some form of verification to post
-post limit per month/week

**Comment by funkychicken493** [comment]
Boooooooo you’re boring

**Comment by RedstonerKBC** [comment]
No, no verification and no post limits! The world has enough verification as it is and post limits are annoying. The solution to all of your Discord problems is very simple actually: Hire more mods. But since that isn't happening...well here we are.

It would be nice if a user could edit their broken schematics post with a new file instead of reposting the same fixed schematic as that can get spammy.

**Comment by EclipsePlays** [comment]
6h slowmode is kinda harsh, make it 3h.

Some form of verification is kinda vague, no further actions stated

Post limit is just 168h slowmode 


Mods on the other hand... There isn't a rule/guideline stated in #rules that shitposting in #schematics is prohibited

**Comment by BorisA11** [comment]
@RedstonerKBC If repost a schematic, delete all previous ones. Simple.

**Comment by BorisA11** [comment]
@EclipsePlays 6
6h slowmode is optimal imo. That way you gotta be 100% sure do you wanna actually post it.

Verification isnt the best way to end this issue, especially with over 50k members.

Post limit is not one per X but some amount of them in that time period.

Posting all kinds of walls and broken 'zipped' schematics is perfectly useless. Then some 'people of exceptional intelect' start cursing each other, ofc with schematics. And them if I wanna find a normal design, I am forced to scoll to shit.

**Comment by BorisA11** [comment]
@funkychicken493 do you prefer having a million shitty and retarded designs there?

**Comment by funkychicken493** [comment]
> @funkychicken493 do you prefer having a million shitty and retarded designs there?

Yes sir. Do you prefer to have no fun?

**Comment by genNAowl** [comment]
I would prefer a schematic starboard channel that only good schematic designers are allowed to post in.

**Comment by genNAowl** [comment]
I would prefer a schematics starboard channel where only good schematics from #schematics are saved

**Comment by RouterChainsSuckk** [comment]
#designs esxists go there if you need good designs that badly jesus

**Comment by XxsuperdeadlysniperxX** [comment]
> Boooooooo you’re boring

Hes got a point here mate

**Comment by XxsuperdeadlysniperxX** [comment]
> > @funkychicken493 do you prefer having a million shitty and retarded designs there?
> 
> Yes sir. Do you prefer to have no fun?

Boi you have a problem if you *want stupid and retarded stuff posted

**Comment by itcannotbe** [comment]
SON OF A FREAKING ~REDACTED~ you can't even shut your mouth for 11 more days can't you? Now we have to wait for an additional 9 more days again for this issue to be marked as stale. 😑

**Comment by XxsuperdeadlysniperxX** [comment]
> SON OF A FREAKING ~REDACTED~ you can't even shut your mouth for 11 more days can't you? Now we have to wait for an additional 9 more days again for this issue to be marked as stale. 😑

Your basterd for blocking me
