### ISSUE TITLE
Provide a way to alter the building queue pattern to optimize build speed/survivability 

### ISSUE THREAD

**Issue by Jaz-Jackson-1225** [Anuken/Mindustry-Suggestions#2709]
**Describe the content or mechanics you are proposing.**

Whenever a player has a large heap of structures to build, some parts construct fsster than others. In a heated battle, little time can be spent focusing on the large wall being built because there are enemies actively engaging. having a feature to pause construction (in mobile) and change the construction behavior (on all platforms) would help. 
Perhaps providing a few build modes like a "proximity" mode, a "smart" mode, and a "budget" mode.
for proximity, the construction will start from the closest to the player first, then go in a spiral around until all is built. It would revert to the default mode if none is within range
For the smart mode, the recievers of fluids and items get built before the supply lines, then lastly the suppliers (if in queue). 
As for the budget mode, the player's constructor will not start building a structure until there is enough resources to complete. (it will restart the search for ready builds or the closest to ready if in deficit)

This would apply to only the commander ship (the core flyer) and won't be inherited by other construction drones. only when the player is actively piloting the drone would the drone contain that ability.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

By adding a feature to prioritize builds the player can optimize their budget to prevent incomplete structures or lines of materials going to nowhere, even prevent a messy spillage of highly flammable oil that could destroy the base from the inside out.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by strugee** [comment]
I've wished for this myself. However, this:

> For the smart mode, the recievers of fluids and items get built before the supply lines, then lastly the suppliers (if in queue).

is backwards from how I like to do it. Generally I build supply sources first, followed by supply lines, followed by supply sinks, because while I'm building the sinks (weapons, factories, etc.) the supplies are coming down the supply lines.
