### ISSUE TITLE
Better Editor

### ISSUE THREAD

**Issue by InfernoSuperNova** [Anuken/Mindustry-Suggestions#271]
**Describe the content or mechanics you are proposing.**

More editing options: 
being able to fill solid blocks onto a ground tile
schematics inside the (non in-game) editor
the ability to apply "area damage" with a click to simulate damage to a structure
allow us to duplicate our own workshop maps without having both instances tied to the workshop item
area selection for buildables, IE to change the team or to rotate it all at once
multiplayer within the non-ingame editor

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
as of right now, the editor is a pain to use. these are only scratching the surface of the issues with the editor, but these would certainly make it less excruciating

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Syncinus** [comment]
I do have the say the current editor is awful, another change I would like to see is to have the camera not be able to go off of the map, currently if I hit a movement key too hard the sensitivity is super high and it will move my camera off of the map, and I can't find my way back and I have to restart the game to fix camera position. The editor needs a lot of work to be less painful to use.
