### ISSUE TITLE
Separator Adjustment

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2711]
**Describe what you would like to be changed.**
- Make separators consume **4/s** slag  instead of **4.1/s**, 
- Production time from **0.58 seconds** to **0.6 seconds**, 
- And melter's liquid output from **12/s slag** to **12.6/s slag**.

**State why do you want to apply these changes.**

- Separators' liquid capacity can now be full when using a 1 melter to 3 separator ratio. 

- The ugly production time will now be precise.

**Comment by RedstonerKBC** [comment]
A tank will give you perfect distribution everytime

**Comment by oinkymoo** [comment]
what

**Comment by RouterChainsSuckk** [comment]
> A liquid tank will give you perfect distribution everytime

holy shit your right, but the thing is the space

**Comment by EclipsePlays** [comment]
> > A liquid tank will give you perfect distribution everytime
> 
> holy shit your right, but the thing is the space 

No it doesn't. 

If you mean "perfect distribution" then it always happens with the generic 1:3 melter-separator setup, but does the separators get full over time? 
**No it doesn't**

That's because melters only generate 12/s slag, while 3 separators need 12.3/s slag, and it will always drain out and flicker whatever you do.
