### ISSUE TITLE
Bridge blocks for units and to build on

### ISSUE THREAD

**Issue by HJCDstudios** [Anuken/Mindustry-Suggestions#2712]
**Describe the content or mechanics you are proposing.**
The bridge block is a 1x1 block that can be putted in deep water soo units can walk on it and can be build on.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This can improve the game by making it possible to cross deep waters.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
>  I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
I think someone is lyiiiing~ :)

**Comment by HJCDstudios** [comment]
How? I did not see anything about bridges are not allowed only tunnels

**Comment by oinkymoo** [comment]
you could do this with conveyors or conduits back in classic, but not anymore

**Comment by RedstonerKBC** [comment]
#2276 I suggested this a long time ago

**Comment by oinkymoo** [comment]
ok? duplicates are allowed and that one got bonked
