### ISSUE TITLE
#Bug Server core bug report

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Anuken/Mindustry-Suggestions#2714]
#Bug
**Problem Description**

  When I try to add more than two mods, it crashes.

**mod list**

  [ScriptAgent4MindustryExt](https://github.com/way-zer/ScriptAgent4MindustryExt)
[Yuria-Shikibe/NewHorizonMod](https://github.com/Yuria-Shikibe/NewHorizonMod)
[pixaxeofpixie/Braindustry-Mod](https://github.com/pixaxeofpixie/Braindustry-Mod)
[mindustry-Extra-Utilities-mod](https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod)

**How to reproduce the problem**

1 lanunch server, then stop it.
2 downlod [this jar](https://github.com/way-zer/ScriptAgent4MindustryExt/releases/download/v2.7.1./ScriptAgent4Mindustry-2.7.jar) in config/mods.
3 [download](https://github.com/way-zer/ScriptAgent4MindustryExt/releases/download/v2.7.1/ScriptAgent4Mindustry-2.7.1-scripts.zip) & unzip files in config/scripts.
4 Install any two mods to the server.
5 lunch server.

**[server crash log](https://paste.opensuse.org/46111355)**

**Comment by Hyrotrioskjan** [comment]
This is a bug. post in #Bugs.
Also, you cannot use Braindustry with _some_ js mods, and you can't use Braindustry with all java mods.

**Comment by itcannotbe** [comment]
> lunch server.

Have you tried eating the server as breakfast or dinner?

**Comment by JrTRinny** [comment]
gonna tell you that this is **_not_** a bug report, please close this

**Comment by IIINSTINCT** [comment]
Bruh #bugs... ._.

**Comment by Mr-Ao-Dragon** [comment]
> This is a bug. post in #Bugs.
> Also, you cannot use Braindustry with _some_ js mods, and you can't use Braindustry with all java mods.

It has nothing to do with this error. This problem occurs after I load any two mods. Besides, I don’t know how to post to #bug

**Comment by itcannotbe** [comment]
You don't make this a bug report by putting #bugs in your issue title. YOU DOING IN THE THE WRONG BLOODY REPOSITORY.

Also the crash log, indicates that it stops loading mods upon trying to load braindustry.

Speaking of brain... Breaking news:
Using braindustry doesn't give more brain power to the people using it.

**Comment by SMOLKEYS** [comment]
Braindustry just outright cannot be used with other java mods and the mod itself does not work on v7 versions.

![SmartSelect_20210718-192627_Chrome.jpg](https://user-images.githubusercontent.com/75618732/126065264-916e0ad9-a911-4002-bc94-e00844dfb201.jpg)
God, can you even read?

**Comment by SMOLKEYS** [comment]
***It was already in front of you and you missed it?***

**Comment by SMOLKEYS** [comment]
And also, ***NEVER DELETE THE TEMPLATE.***

**Comment by Mr-Ao-Dragon** [comment]
> And also, ***NEVER DELETE THE TEMPLATE.***

No, I did not delete

**Comment by Mr-Ao-Dragon** [comment]
> Braindustry just outright cannot be used with other java mods and the mod itself does not work on v7 versions.
> 
> >I don’t know how to post to #bug
> 
> ![SmartSelect_20210718-192627_Chrome.jpg](https://user-images.githubusercontent.com/75618732/126065264-916e0ad9-a911-4002-bc94-e00844dfb201.jpg)
> God, can you even read?

tks, I will delete this topic later
FXXK github phone client :（

**Comment by Bottinator22** [comment]
https://github.com/Anuken/Mindustry/issues/new?template=bug_report.md
