### ISSUE TITLE
Add a button for whether to display the unit.

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Anuken/Mindustry-Suggestions#2715]
**Describe the content or mechanics you are proposing.**

In the game, if a large number of units are concentrated, the blocks below will be blocked, making it very difficult to operate.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Obviously, the t5 unit will no longer block the block and cause difficulty in operation, and accurately picking the 1*1 block below is no longer a matter of luck.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [✅] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [✅] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [✅] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
I don't even know what you're trying to say.

**Comment by itcannotbe** [comment]
Clearly OP doesn't have enough braincells to even be playong this game.

Template ask to put `X` ..... anyways.....

**Comment by itcannotbe** [comment]
Also if your having trouble selecting blocks because your units are in the way....

Then BLOODY MOVE THEM.

**Comment by Mr-Ao-Dragon** [comment]
> Also if your having trouble selecting blocks because your units are in the way....
> 
> THEN BLOODY MOVE THEM.

You will find this button necessary when you find that a large number of T5 flying units are piled up because of the wrong set of instructions from other people on the server.

**Comment by Mr-Ao-Dragon** [comment]
> Also if your having trouble selecting blocks because your units are in the way....
> 
> THEN BLOODY MOVE THEM.

Picking up/dropping small squares on your phone is a very painful experience. You are not sure that you have picked up the squares you need. The touch itself is unreliable. You can try it yourself with a T5 unit.

**Comment by Mr-Ao-Dragon** [comment]
> I don't even know what you're trying to say.

Picking up/dropping small squares on your phone is a very painful experience. You are not sure that you have picked up the squares you need. The touch itself is unreliable. You can try it yourself with a T5 unit.

**Comment by Mr-Ao-Dragon** [comment]
> I don't even know what you're trying to say.

I'm really sorry, English is not my mother tongue, I can only rely on Google Translate to communicate with you.

**Comment by RedstonerKBC** [comment]
> Also if your having trouble selecting blocks because your units are in the way....
> 
> THEN BLOODY MOVE THEM.

Holy crap dude no need to yell. Calm down!

**Comment by RedstonerKBC** [comment]
This has already been suggested multiple times by me and other people. Even if you can "BLOODY MOVE THEM" other people are controlling them via logic or stockpiling them around command centers for battle. There's no good place to move them sometimes so they are out of the way.

**Comment by Mr-Ao-Dragon** [comment]
> This has already been suggested multiple times by me and other people. Even if you can "BLOODY MOVE THEM" other people are controlling them via logic or stockpiling them around command centers for battle. There's no good place to move them sometimes so they are out of the way.

yep, I am troubled by the server.
