### ISSUE TITLE
New Settings for Maps

### ISSUE THREAD

**Issue by GamerMoment69** [Anuken/Mindustry-Suggestions#2717]
**Describe the content or mechanics you are proposing.**

1. Unjoinable Teams
2. Turret Building Damage Multiplier
    
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

1. I've made a PvP-intended map using the Core Capture rule. It has neutral defenses guarding the two cores to make it a little harder to capture. The problem is, turning the cores derelict still allows the turrets to shoot the core. It still works in a 1v1 scenario but it will not work in a PvP server scenario due to the fact that latecomers can join the blue team. Have a screenshot: 
![screenshot-1626609721640](https://user-images.githubusercontent.com/87551951/126066316-f9b3aab4-6562-484b-9175-adaca11fe0db.png)
2. To encourage, or even force players to use units to attack and brute force the turrets instead of Ripple spam to take out a defense with ease. Also reduces turret bombing. If set below 0.4, turret AI will not target blocks. When set higher than the default, it means the map maker is encouraging turret sieging and bombing.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
Block Damage Multiplier is a thing why u still need Turret Damage Multiplier

**Comment by GamerMoment69** [comment]
@IIINSTINCT what I mean when I say _Turret Building Damage Multiplier_ is turret damage against blocks ONLY. _Block Damage Multiplier_ is turret damage against units AND blocks
