### ISSUE TITLE
Manual Unit Command Changes

### ISSUE THREAD

**Issue by notrealn** [Anuken/Mindustry-Suggestions#2718]
**Describe what you would like changed, and why.**
The current manual player unit control has a couple problems. (some of the ones listed below are already issues)

![image](https://user-images.githubusercontent.com/56411504/126078051-90e085fe-9d2f-4382-ae8c-b38fe39804ed.png)
the formation of the units is way too big and can lead to problems with moving around narrower rivers
![image](https://user-images.githubusercontent.com/56411504/126078159-9b4e22db-c561-4ce9-9be8-f0c8baa00cb2.png)
they are spaced so far apart that if you double tap g, you wont even recontrol the units. 

![image](https://user-images.githubusercontent.com/56411504/126078271-32d43cb6-f039-441e-8916-922d810549a8.png)
another problem with this ring of units thing is that i will rarely get the units shooting where i want them to. in this image i want to shoot this line of copper walls (pretend they are daggers or something), but most only shoot like 1 or 2 walls.
with some units like eclipse, your back units wont be in range most of the time and a ton of damage/pierce is wasted.

i just want to get 2 omuras, but thats literally impossible. you will always pick up a few brydes or whatever.
![image](https://user-images.githubusercontent.com/56411504/126078207-178b4a6f-6004-473c-afaf-4b3e2ad839b4.png)

i dont have an image for this one, but you can just hop onto a server and see it for yourself. if you control a group of polies, you will bump into them and get slowed down. duplicate of #2106 (and maybe a few more).

some might say "lmao just use logic", but this isnt a good solution. i encounter these problems in pvp a lot, and noobs might not always have access to schems that can precisely control 50 quasars and make them all shoot in the right way or logic schems that give units a new ai which is 100x smarter than the current one. a way to do this without using schems would make it way more accessible and easy to use. plus the alternative unit command system listed below would allow you to precisely control which units you want. 

**Describe the changes you want to propose. Include possible alternatives.**
instead of just pressing g to control 8 units that are close to you, what if you could control units by holding a button and clicking on a unit and it will be added to your controlled units?
something like this, but instead of just controlling it you add it to your command list
![image](https://user-images.githubusercontent.com/56411504/126079141-0e51898c-792f-49b6-8d22-8b9d327f708f.png)
this could either replace the current system or just be an extra button you have alongside pressing g

after you control a unit, they should still be in rings, but like this:
![image](https://user-images.githubusercontent.com/56411504/126079228-0e2ac99a-77ab-42df-a110-d0e9a425d126.png)
the number of units in each ring and the size of it is determined by unit size, and the size/number shown in my crappy drawing isnt final.
the size of the rings should be way smaller for t5s than it is now, so you dont get the stuff that comes with big rings (terrible accuracy and range)
if you dont have enough units to fill a ring, the units should still be spaced evenly apart (no empty holes in the formation if you dont have enough)
i saw this before in a suggestion (#1285), thought it was cool

maybe if enough people agree, il make a PR

**Comment by LeoSko** [comment]
I have 2 questions:
What are the options for such controls on mobile?
How new formation scheme makes accuracy any better?

**Comment by notrealn** [comment]
> What are the options for such controls on mobile?

maybe a button that you click, and then you click the unit you want to command

> How new formation scheme makes accuracy any better?

instead of 9 units in one big ring, they will be split up into 2 smaller rings.

**Comment by RedstonerKBC** [comment]
I thought I already suggested something similar to this but a quick search reveals I did not. A lot of these issues have been suggested already:

-Units follow too closely.
-Units follow too far away.
-Can't control individual units.
-Can't control unit formations.

All of these can be done with logic but not everyone has the schems to make this happen. Pretty much all of these problems can be controlled with logic (but are you smart enough to make it happen? Challenge accepted!).

I really love the idea of button + clicking to add an individual unit to your group. Sometimes smaller units fly away while you change units and you have to fly to them because you are slow.

**Comment by RedstonerKBC** [comment]
Actually yes I did suggest the units follow too close and it makes you bump into them. The problem with this specific issue is that it scales with unit tier and number of units controlled, so if you control a smaller unit you're basically guaranteed to bump into your group unless you control a full command limit number of units, except for flares which are guaranteed to bump even at the limit.
