### ISSUE TITLE
[Modding]Statuses.

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2719]
**Describe the content or mechanics you are proposing.**
Currently I cannot JSON reactive or combination statuses - transitionDamage does not function. (I have tried.)
Reactive statuses have an issue with init.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Add the abilities to make JSON statuses react and combo with other, even vanilla, statuses. Since apparently 7.0 supports having statuses in their own files (that is what I've heard, I need to check), maybe even react with other modded statuses.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
  (*I actually did this time.*)
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. (Haven't tested much with 7.0, but I haven't noticed any status changes.)
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
I think this could be implemented with:
`ObjectMap<String, StatusEffect> reacts`
where the string is the effect name that the effect reacts with and applying the StatusEffect when they react (all current reactions can be implemented this way with 1 frame duration effects)

**Comment by Anuken** [comment]
All status reactions of interest are implemented with [arbitrary code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/StatusEffects.java#L30-L34), so making them "JSON-able" is not an easy matter. They can't be written to variables.

**Comment by BlueWolf3682** [comment]
Yes, I know. I was basically suggesting that be rewritten, *if possible*, to be a little more JSONable.
I currently have so many statuses that are awaiting ability to react or combo, such as Permafrost, Charged, and Vapourizing.

**Comment by itcannotbe** [comment]
> Yes, I know. I was basically suggesting that be rewritten, _if possible_, to be a little more JSONable.
> I currently have so many statuses that are awaiting ability to react or combo, such as Permafrost, Charged, and Vapourizing.

I think it's better to pr it yourself as by the look of it, anuke won't be touching that in the foreseeable future.
