### ISSUE TITLE
Please let Lancer spin when they are attacking

### ISSUE THREAD

**Issue by driver1748** [Anuken/Mindustry-Suggestions#272]
**Describe the content or mechanics you are proposing.**

![1E8121EA-F8B7-4A9A-BE7C-E79C4A65C810](https://user-images.githubusercontent.com/62016462/86098493-c516b480-bae8-11ea-8f05-32ec8380c7b9.jpeg)

Please let Lancers spin when they are ready to attack.They often flood their damage to air.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Lancer sucks without this.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
This doesn't make sense what so ever.

The lancer's attack isn't a sustained beam. It's just a pulse.

**Comment by driver1748** [comment]
I means when it is heating for the attack,please let it spin

**Comment by Syncinus** [comment]
Lancer is already incredibly overpowered, it doesn't need to be buffed.

**Comment by Anuken** [comment]
I agree with the comment above; it doesn't need another buff.
