### ISSUE TITLE
I should condense my modding ideas.

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2721]
**Describe the content or mechanics you are proposing.**
  Girl's back with yet *another* modding thing: unit ammo.
  Add JSON support for adding unit ammos, for different item and power ammos. Useful for Exotic because I have a lot of larger units that probably should require more lategame ammo.
  Also, maybe consider having ammos as a stack instead of a single ammo, for multiple weapons of various types. Useful for things like Eclipse, Toxopid, and modded units such as Exotic's Pandemic, Demon, and upcoming Inferno units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
~~***I MUST HAVE THE POLISHING POWAAAAAAAAH***~~
More features, allows for more advanced ammo support. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have not checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
In the unit type, define "ammoType" to anything in [AmmoTypes.java](https://github.com/Anuken/Mindustry/blob/fde23ceea06ce4041ca94d7bf64a90f5f9f2cccd/core/src/mindustry/type/AmmoTypes.java#L11)
It may be possible to make custom ammo types by instead of defining as `ammoType: <ingame ammo type>` do
```
ammoType: {
  type: ItemAmmoType
  item: <insert item here>
}
``` 
or
 ```
ammoType: {
  type: PowerAmmoType
  totalPower: <insert integer here>
}
```
but I have no idea if custom ammo types work and I'm too lazy to check

**Comment by MrDuck557** [comment]
> Also, maybe consider having ammos as a stack instead of a single ammo, for multiple weapons of various types

If you mean multiple ammos for different weapons, that's going to require some recoding
as well as UI changes
how are you going to represent that

**Comment by BlueWolf3682** [comment]
> In the unit type, define "ammoType" to anything in [AmmoTypes.java](https://github.com/Anuken/Mindustry/blob/fde23ceea06ce4041ca94d7bf64a90f5f9f2cccd/core/src/mindustry/type/AmmoTypes.java#L11)
> It may be possible to make custom ammo types by instead of defining as `ammoType: <ingame ammo type>` do

I didn't say applying ammo types, I said making them.

> 
> ```
> ammoType: {
>   type: ItemAmmoType
>   item: <insert item here>
> }
> ```
> 
> or
> 
> ```
> ammoType: {
>  type: PowerAmmoType
>  totalPower: <insert integer here>
> }
> ```

ContentParser doesn't parse ammo as of right now.

> 
> but I have no idea if custom ammo types work and I'm too lazy to check

They don't.

**Comment by BlueWolf3682** [comment]
> > Also, maybe consider having ammos as a stack instead of a single ammo, for multiple weapons of various types
> 
> If you mean multiple ammos for different weapons, that's going to require some recoding
> as well as UI changes
> how are you going to represent that

Optionally applying ammo consumption to the weapons instead of the unit.

**Comment by AzhurniyBaklan** [comment]
>  Add JSON support for adding unit ammos, for different item and power ammos. Useful for Exotic because I have a lot of larger units that probably should require more lategame ammo.

What's funnier is that it's not much simpler to add it via javascript, so no custom unit ammo support is just a problem in general. On the other hand, *barely anybody uses unit ammo feature anyway.
So the question comes down to if custom unit ammos templates are worth implementing _at all_ ¯\_(ツ)_/¯

* - sure, some people do use it, but the percentage is quite a small number.

**Comment by Anuken** [comment]
> for different item and power ammos

Even the base game doesn't allow this yet. Ammo still hasn't been "figured out" as a mechanic; it's far too early to implement modding support for it.

**Comment by BlueWolf3682** [comment]
uwu
