### ISSUE TITLE
controller

### ISSUE THREAD

**Issue by maurocrak18** [Anuken/Mindustry-Suggestions#2722]
add controller support  Thank you

**Comment by MrDuck557** [comment]
please make your idea more specific and follow the template Thank you

**Comment by GamerMoment69** [comment]
<img width="651" alt="README" src="https://user-images.githubusercontent.com/87551951/126244491-1f7d0393-5593-4175-a594-f53de41599ff.png">
ahem
if you were not to <s>absoulutely murder</s>delete the template you would've seen this

**Comment by itcannotbe** [comment]
OP be like

![I cant read] (https://c.tenor.com/qgH6DP_T99oAAAAM/reading-sign.gif)

**Comment by Humanoid-X** [comment]
close this Thank you
