### ISSUE TITLE
Rocket Silos

### ISSUE THREAD

**Issue by DeadFoxTails** [Anuken/Mindustry-Suggestions#2723]
**Describe the content or mechanics you are proposing.**
A placed Rocket Launch Silo that when set and loaded will have near full map range. could be loaded with two sets of stages, a fuel (used to determine range/velocity of rocket) and a warhead loading phase, (used to determine damage/effect of warhead) Oil could be a warhead intended to set strike zones ablaze, throium for high explosive, surge alloys for striking batteries. etc)  Rocket launch pad could require a coolant for each launch (much like how Rockets in real life have pools of water below them and sprayed onto them during take off). And additionally the launchpad could take damage with each launch, or even be one time use, Making launching a missile a expensive or end game weapons system. This would build upon already existing "launch pad" mechanics within the game of loading rockets for delivery to other sectors, but in this case, much more offensively.

Additionally, Anti air systems like Segments, (when used in clusters) could shoot a rocket down, given theirs enough of them

Maybe, fired rockets could change the landscape of a map, say for example. a rocket filled with Surge alloy could have the blast zone mined of said warhead and provide a potential bonus to any surviving rocket victims. (Although this would be a niche, and rare use case)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently most placeable turrets are defensive, while ripples and hails can be placed at the edge of enemy territory to bombard forward operating bases, no true offensive turrets exist as is. For pvp/pve the discovery of a enemy rocket being loaded/prepared would create tense and dire situations that call for action A.S.A.P, or call for extreme divergence to Anti air systems to protect important or vulnerable buildings. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Btw, Segments aren't anti-air, they're anti-projectile. I believe by anti-air you meant anti-projectile.

**Comment by DeadFoxTails** [comment]
> Btw, Segments aren't anti-air, they're anti-projectile. I believe by anti-air you meant anti-projectile.
> To keep it from being too useless, the projectile should pass through force projectors and be able to take multiple segment hits before going down.

Your right, Anti-projectile. Thank you!

as for taking multiple hits, perhaps the more damage a rocket takes, the less powerful the final warhead will be, so that any amount of anti-projectile will be better than none.

**Comment by itcannotbe** [comment]
> Additionally, Anti air systems like Segments, (when used in clusters) could shoot a rocket down, given theirs enough of them

They probably can't, given the time in range of the segments, there would be an unrealistic chance that they can zero out the damage that projectile in this suggestion has.

~Seriously, people really need to check how the mechanics in the game actually works before suggesting anything extremely specific~

**Comment by itcannotbe** [comment]
> This would build upon already existing "launch pad" mechanics within the game of loading rockets for delivery to other sectors.

Basically effortless sector clearing? That a hard no. Conquering the whole planet is tedious for a reason.

**Comment by Bottinator22** [comment]
He didn't mean cross-sector rockets, cause those won't be stopped by
segments

**Comment by oinkymoo** [comment]
disagree about the range. this seems like it would allow you to ignore almost all defenses entirely, which defeats their purpose

**Comment by BoultonPaulDef** [comment]
For me it's great, i always wanted to bombard my enemies from distance

**Comment by itcannotbe** [comment]
> For me it's great, i always wanted to bombard my enemies from distance

Is that basically blast bombing?

**Comment by oinkymoo** [comment]
> > For me it's great, i always wanted to bombard my enemies from distance
> 
> Is that basically blast bombing?
> At least with that you can defend from it. Unlike this block....

Might I add that foreshadows, which deal over a thousand damage per hit, with a 42 block range, deal only 25% damage to buildings, which is still more building damage than every other turret except meltdown, and the next closest is a thorium-fed fuse, which still does less damage per hit  when all 3 shots hit the same target than a foreshadow. You are proposing a foreshadow with 5-10 times the range and without the building damage penalty. Unless this thing has a comparable cost and ammo requirement to the fricking interplanetary accelerator, this isn’t happening

**Comment by DeadFoxTails** [comment]
> > > For me it's great, i always wanted to bombard my enemies from distance
> > 
> > 
> > Is that basically blast bombing?
> > At least with that you can defend from it. Unlike this block....
> 
> Might I add that foreshadows, which deal over a thousand damage per hit, with a 42 block range, deal only 25% damage to buildings, which is still more building damage than every other turret except meltdown, and the next closest is a thorium-fed fuse, which still does less damage per hit when all 3 shots hit the same target than a foreshadow. You are proposing a foreshadow with 5-10 times the range and without the building damage penalty. Unless this thing has a comparable cost and ammo requirement to the fricking interplanetary accelerator, this isn’t happening

Theres no reason it cant have a Core/building damage nerf. or have steep or even one time use structure to launch. the rocket itself already requires, or would require immense amounts of oil, or even a new fuel. PLUS, materials for the warhead. balance can be implemented.

**Comment by Kyllingene** [comment]
> Theres no reason it cant have a Core/building damage nerf. or have steep or even one time use structure to launch.

So you want a buffed foreshadow? Not happening.

**Comment by Bottinator22** [comment]
Has nobody here ever played RTS games? This suggestion is basically the nukes from those, not just some special turret

**Comment by Bottinator22** [comment]
Furthermore, this thing's easily interceptable by segments, so it'd rarely even be able to hit things with its payload

**Comment by itcannotbe** [comment]
> Furthermore, this thing's easily interceptable by segments, so it'd rarely even be able to hit things with its payload

Do you even know how segments work?

**Comment by itcannotbe** [comment]
> Has nobody here ever played RTS games? This suggestion is basically the nukes from those, not just some special turret

Every RTS game has it's own thing, and most of the time you can't plop anything from any other game to any other game. Since balancing mechanics differ between the games.

**Comment by Bottinator22** [comment]
> > Furthermore, this thing's easily interceptable by segments, so it'd rarely even be able to hit things with its payload
> 
> Do you even know how segments work?

Yes, they shoot at projectiles, usually destroying them.

**Comment by itcannotbe** [comment]
> > > Furthermore, this thing's easily interceptable by segments, so it'd rarely even be able to hit things with its payload
> > 
> > 
> > Do you even know how segments work?
> 
> Yes, they shoot at projectiles, usually destroying them.

Can you expound on your extremely shallow answer?

**Comment by Bottinator22** [comment]
> > > > Furthermore, this thing's easily interceptable by segments, so it'd rarely even be able to hit things with its payload
> > > 
> > > 
> > > Do you even know how segments work?
> > 
> > 
> > Yes, they shoot at projectiles, usually destroying them.
> 
> Can you expound on your extremely shallow answer?
> 
> I'll give you a hint.
> 
> b.~fucking~ remove

What says segments can't attack this rocket?

**Comment by oinkymoo** [comment]
> > > > For me it's great, i always wanted to bombard my enemies from distance
> > > 
> > > 
> > > Is that basically blast bombing?
> > > At least with that you can defend from it. Unlike this block....
> > 
> > 
> > Might I add that foreshadows, which deal over a thousand damage per hit, with a 42 block range, deal only 25% damage to buildings, which is still more building damage than every other turret except meltdown, and the next closest is a thorium-fed fuse, which still does less damage per hit when all 3 shots hit the same target than a foreshadow. You are proposing a foreshadow with 5-10 times the range and without the building damage penalty. Unless this thing has a comparable cost and ammo requirement to the fricking interplanetary accelerator, this isn’t happening
> 
> Theres no reason it cant have a Core/building damage nerf. or have steep or even one time use structure to launch. the rocket itself already requires, or would require immense amounts of oil, or even a new fuel. PLUS, materials for the warhead. balance can be implemented.

keeping similar building damage to the foreshadow would pretty much defeat what seems to be the intended purpose, because foreshadow damage is already absurd
