### ISSUE TITLE
Ambient heat having effect on reactor

### ISSUE THREAD

**Issue by Ksawi999** [Anuken/Mindustry-Suggestions#2724]
**Describe what you would like changed, and why.**
Reactor efficiency and heat should be dependent on heat of tiles it's placed on. 

It's weird that turned off reactor doesn't lose its heat even if it's placed on ice or that the reactor doesn't heat up faster on magma. 

I've made reactor manager so you can see the reactor heat and overuse of cyrofluid. There you have graphs for current version:

https://user-images.githubusercontent.com/66205430/126302359-129a2240-7fd3-481c-9a42-89077fa062a8.mp4

**Describe the changes you want to propose. Include possible alternatives.**
Make floor heat can have effect on reactor efficiency and heat. I think it should be in description like in thermal gen. On cold blocks reactor efficiency should be decreased but heating time without cryofluid increased. On hot blocks efficiency should be increased, but it should cool down for longer time, use more cryofluid and heat up faster. Also normal cooling time should be increased because it's for now almost instant.

**Comment by itcannotbe** [comment]
This is kinda easy except for .....

> It's weird that turned off reactor doesn't lose its heat

Disabling blocks with logic basically suspends them not turn them off.

**Comment by itcannotbe** [comment]
> Also normal cooling time should be increased because it's for now instant.

Have you checked it with a thorium reactor near max heat?

**Comment by Ksawi999** [comment]
> > Also normal cooling time should be increased because it's for now instant.
> 
> Have you checked it with a thorium reactor near max heat?
> 
> Your video even demonstrates that it's not instant.

It's not instant only when there isn't needed amount of cryofluid in reactor (see upper display).

**Comment by Ksawi999** [comment]
> > Also normal cooling time should be increased because it's for now instant.
> 
> Have you checked it with a thorium reactor near max heat?

Reactor manager I made is heating it to 96% and I think it's enough.

**Comment by Ksawi999** [comment]
> This is kinda easy to implement except for .....

Yeah, I know, I will make pull request myself but I think I should discuss it.

**Comment by itcannotbe** [comment]
> > > Also normal cooling time should be increased because it's for now instant.
> > 
> > 
> > Have you checked it with a thorium reactor near max heat?
> > Your video even demonstrates that it's not instant.
> 
> It's not instant only when there isn't needed amount of cryofluid in reactor (see upper display).

Do you understand how the heat mechanic of the thorium reactor works?

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry/blob/b58f202e9e1ef11dc58098c2d4132e4093bbc4cf/core/src/mindustry/world/blocks/power/NuclearReactor.java#L118

The code that make Thorium Reactors destroy itself.

**Comment by itcannotbe** [comment]
If your wondering why I didn't say explode.
Because it's a different piece of code XD.

https://github.com/Anuken/Mindustry/blob/b58f202e9e1ef11dc58098c2d4132e4093bbc4cf/core/src/mindustry/world/blocks/power/NuclearReactor.java#L128

**Comment by itcannotbe** [comment]
~It would be a fun mechanic if you can't cool your thorium reactor if you placed it on enough tiles with heat attributes.~

**Comment by Ksawi999** [comment]
> ~It would be a fun mechanic if you can't cool your thorium reactor if you placed it on enough tiles with heat attributes.~

~It would be a fun mechanic if you can't heat up your thorium reactor if you placed it on enough tiles with chill attributes.~

**Comment by Ksawi999** [comment]
> > > > Also normal cooling time should be increased because it's for now instant.
> > > 
> > > 
> > > Have you checked it with a thorium reactor near max heat?
> > > Your video even demonstrates that it's not instant.
> > 
> > 
> > It's not instant only when there isn't needed amount of cryofluid in reactor (see upper display).
> 
> Do you understand how the heat mechanic of the thorium reactor works?

Yes, it's not instantly cooling, but if something takes less than half of second you can say that's "instant".

**Comment by itcannotbe** [comment]
> > > > > Also normal cooling time should be increased because it's for now instant.
> > > > 
> > > > 
> > > > Have you checked it with a thorium reactor near max heat?
> > > > Your video even demonstrates that it's not instant.
> > > 
> > > 
> > > It's not instant only when there isn't needed amount of cryofluid in reactor (see upper display).
> > 
> > 
> > Do you understand how the heat mechanic of the thorium reactor works?
> 
> Yes, it's not instantly cooling, but if something takes less than half of second you can say that's "instant".

Kindly blame the small Max Heat of the Thorium Reactor.

Also, the fastest you can explode it is 1.6666666667 seconds.
While you can "cool" it down in about 1/30 second (0 thorium and from near max heat)

**Comment by Ksawi999** [comment]
What do you think about version with such graph?

https://user-images.githubusercontent.com/66205430/126644875-aa24c40f-812f-4e2b-8ce5-9f23bfd643a9.mp4

**Comment by itcannotbe** [comment]
what did you change exactly?

**Comment by Ksawi999** [comment]
> 
> 
> what did you change exactly?

You can see all changes here: https://github.com/Ksawi999/Mindustry/commits/reactor-heat-system

**Comment by Ksawi999** [comment]
...

**Comment by itcannotbe** [comment]
Also you fucked up the item duration. That doesn't work.

**Comment by itcannotbe** [comment]
Also you don't actually need to create a new attribute. Just use the heat attribute.

**Comment by itcannotbe** [comment]
also why put an attribute on slag? You cannot even build most block om it.

**Comment by Ksawi999** [comment]
> 
> 
> Also you fucked up the item duration. That doesn't work.

Really?


> 
> 
> Also you don't actually need to create a new attribute. Just use the heat attribute.

Yes, I know but that discussion is about reactor, so I don't want to change attribute that other blocks use.

> 
> 
> Also why put an attribute on slag? You cannot even build most block on it.

It already had heat attribute.

**Comment by itcannotbe** [comment]
> > Also why put an attribute on slag? You cannot even build most block on it.
> 
> It already had heat attribute.

Well it gets shown in the block info, So it would get confusing why you can't place it down there.

**Comment by Ksawi999** [comment]
> 
> 
> > > Also why put an attribute on slag? You cannot even build most block on it.
> > 
> > 
> > It already had heat attribute.
> 
> Well it gets shown in the block info, So it would get confusing why you can't place it down there.

It don't show.

**Comment by Ksawi999** [comment]
> 
> 
> Also you fucked up the item duration. That doesn't work.
> 
> It's the wrong place to put that in.

So where should I put that?
