### ISSUE TITLE
Valcano sector

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#2725]
**Describe the content or mechanics you are proposing.**I think one of these planets should include a huge volcano (possibly spanning multiple tiles)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** it will add more biome diversity, make for a interesting map, possibly include a enemy base that is based on thermal power

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The _Valcano_ might be rekt by the clear line from spawn to mechanic of procedural sector generation.

**Comment by RouterChainsSuckk** [comment]
> The _Valcano_ might be rekt by the clear line from spawn to mechanic of procedural sector generation.

Make it one of those important sectors then?

**Comment by IIINSTINCT** [comment]
This kind of things would eventually come on v7 planets why still bother to suggest xD

**Comment by Hyrotrioskjan** [comment]
This would probably be added in the desert part of _Hymaea_, or the tidally locked planet.
Either way, this means that it would either add a new block in the editor, the volcano, or just use walls surrounding a small slag lake. 

As said before in the comment above, 
> This kind of things would eventually come on v7 planets why still bother to suggest
