### ISSUE TITLE
Play Launch more

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry-Suggestions#2727]
**Describe the content or mechanics you are proposing.**
Play Launch more, like on the campaign planet map when no other music is already playing.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I feel Launch doesn't really play very much. It's a nice track, yet it only ever plays when you enter the campaign, and stops playing when you enter a sector. It never starts again until you exit the campaign and come back.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
And bring back old game4

**Comment by BorisA11** [comment]
> And bring back old game4

There is a new one, as you may know, new "9" is just re-done game4

**Comment by Axzye** [comment]
> > And bring back old game4
> 
> There is a new one, as you may know, new "9" is just re-done game4

i had a suggestion to make it only play at night but it was closed for being stale
