### ISSUE TITLE
Update the images on google play store

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2728]
**Describe the content or mechanics you are proposing.**

Google play store still has old v5 screenshots as images. Consider re-doing them for v6/v7? Visuals have improved a lot since then, and maybe add a few more screenshots for new units?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Cant see an alternative, really. Maybe do it once it moves to a new (potentially paid) app, since I've heard that this might change.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why though? It won't even get updated anyways.

**Comment by itcannotbe** [comment]
And of course a new listing means a new set of images. Duh.
