### ISSUE TITLE
Hello, I have an idea for the processor code, specifically unit code.

### ISSUE THREAD

**Issue by AzurthArray** [Anuken/Mindustry-Suggestions#2729]
My idea is a unit code system that allows a unit to be told to target buildings, like how a unit can be coded with shoot unit, because if you can tell a unit to shoot at units in three lines of code, such as "Bind, locating unit, target predict, and set both of the boxes to the target" is efficient due to saving code and resources in the processor. Targetting at buildings however, is hard due to how many pieces of code it can take or being complicated, like a target building, target closest, lowest, and so on, also this is not a rant on how it's bad units can't see walls with processors, I actually like that. I just had an idea and thought I would submit it.

I think this would allow many players to code with units without harming their own team or themselves, and getting called bad just for trying to learn. I also think this would open up more ways to use units, being potential frontline units that can break buildings like turret crawls. And such as weak damage units being told to break low hp blocks, and high damage breaking high hp, if in range. So essentially, a target predict for units, but instead it works on blocks, also, Anuken you are a great person I wish you have a nice day, love the game, I have been playing it since I was 5, it's so well made and one of my favorites, wish you luck.
Also I am not sure if this is considered fast forwarding the game, really. Because if you think about it, it does make the game easier, but also harder, being coding for movement of units is needed, and you can't just use it alone because then, how are you going to find enemy structures if you aren't moving. Just an idea, this is my first time submitting one of these, I have read the readme, I hope you like the idea. I am not submitting this because I succeed best at unit coding mostly, I just like using variables and making unique unit processors that do things others don't, such as a controller, that has two extra features instead of just controlling, really love your game, wish you more luck on it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Caution: it is really easy to determine your age from simply adding how long Mindustry has been around to how old you were when you started to determine your current age, which could lead to the removal of your Github account for being too young.

Either way, this really isn't terribly necessary; you can `ulocate` a wall, then attack it.

**Comment by MrDuck557** [comment]
so very long rant about how you want shootp to be able to use buildings
and how it will make logiced units better

**Comment by oinkymoo** [comment]
if you already have a variable containing the wall, it is not hard to simply sensor its `@x` and `@y` and simply shoot those coordinates
