### ISSUE TITLE
EASY mod maker in mindustry

### ISSUE THREAD

**Issue by DeadFenix05** [Anuken/Mindustry-Suggestions#273]
Add in the mindustry the easy mod creator. Example: In game have a button with icon of mods and you can create a mod without other apps. You can draw a building or combine someone to make a new building. You can select what is this: weapon, wall, drill, mech station, energy generator and other.

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Why does making mods need to be easy again?

JSON is a relatively easy way of making mods already as suppose to JS or otherwise source-modding the game.

**Comment by DeltaNedas** [comment]
if monkeys can destroy a website with js, there's no reason for why you, a human being in 2020 with 4 limbs, can't use it or even json to make a mod

**Comment by ILiekMelons** [comment]
json is so simple block coders could do it

**Comment by Joshwelyt** [comment]
Scripting tho we need to do scripting for custom weapons

**Comment by Vaid701** [comment]
Muchas personas no saben nada de programación. Y muchos niños juegan Mindustry creo que esta idea la da posibilidades a esas persona de crear mod para divertirse
