### ISSUE TITLE
Grant enemies brief invincibility when they are spawned via drop point

### ISSUE THREAD

**Issue by GamerMoment69** [Anuken/Mindustry-Suggestions#2730]
**Describe what you would like changed, and why.**
Currently, you can cheese your way through any ground units by placing a liquid tank of oil in the middle of a drop point, shown here on Desolate Rift.
Before:
<img width="956" alt="OilTanks" src="https://user-images.githubusercontent.com/87551951/126626117-aae37848-6da3-420e-bff3-e57941ccf86e.png">
After:
<img width="960" alt="EzKill" src="https://user-images.githubusercontent.com/87551951/126626127-8d4514a3-1b9f-45a8-9c6c-6cf78e0c2646.png">
Yeah this is just dumb as the enemies have to rely on their air units.
**Describe the changes you want to propose. Include possible alternatives.**
Giving enemies brief invincibility would circumvent that effortless kill I showed you.
Alternatively, disallow building in the drop point, which I remember was in 3.5.

**Comment by itcannotbe** [comment]
The alternative is #949

**Comment by SMOLKEYS** [comment]
Using oil tanks on drop points is literally a tip on the wiki.

**Comment by itcannotbe** [comment]
> Using oil tanks on drop points is literally a tip on a mindustry wiki.

Proof please. Also which wiki, if it's an unofficial one. It doesn't count.

**Comment by SMOLKEYS** [comment]
> > Using oil tanks on drop points is literally a tip on a mindustry wiki.
> 
> Proof please. Also which wiki? if it's an unofficial one. It doesn't count.

![SmartSelect_20210722-201148_Chrome.jpg](https://user-images.githubusercontent.com/75618732/126637152-c238ce25-8314-4e25-b273-7968b059e200.jpg)
https://mindustry-unofficial.fandom.com/wiki/Desolate_Rift

unofficial, so probably does not count to your standards

**Comment by oinkymoo** [comment]
> Using oil tanks on drop points is literally a tip on a mindustry wiki.

your point being?

**Comment by GamerMoment69** [comment]
Implemented.
