### ISSUE TITLE
Special air unit for delivered

### ISSUE THREAD

**Issue by DHz06** [Anuken/Mindustry-Suggestions#2732]
**Describe the content or mechanics you are proposing.**

I would like not to see Flares / horizon / poly / mega in delivery jobs.  It takes away the function that these units fulfill within the game and they are not used as they should be, since they are the only units available to make some schemes work.  I propose a new special air unit (T1, T2, T3) and ONLY to deliver.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

1-It would improve the game experience for those who want to take advantage of the flare units in another strategy, since it is normally always used in logic de deliver.
2-When no flares / horizon / ... are available, other units (Also, Land Unit ) are used for delivery work.  This makes fewer units visible attacking the enemy team.
3-These 3 new units could prevent players from turning to ground units to use in deliver. 
4-They also keep the Poly / mega units free if they are to be used in mining jobs. 
 
The main idea is to avoid the use of attack units to do delivery work, I would like to see these new air units that fill that gap.  They obviously won't have the ability to defend themselves.

*The technical statistics of the new units can be discussed in community.
*They will be units that will only work with Logic

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - X I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - X I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - X I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
>
> _leaves blank_

Oh neat, does it mean it basically doesn't?

**Comment by Bottinator22** [comment]
Not a bad suggestion, but you forgot to finish filling in the template

**Comment by DHz06** [comment]
He did not know what to say in the second point, he had already said everything he had in mind at the beginning.. Sorry

**Comment by DHz06** [comment]
updated

**Comment by oinkymoo** [comment]
the reason that those units are used is that they won't even be able to damage most defenses on custom maps, and a decently competent defense makes polys pretty much useless
