### ISSUE TITLE
Moddable solar systems

### ISSUE THREAD

**Issue by NiChrosia** [Anuken/Mindustry-Suggestions#2733]
**Describe the content or mechanics you are proposing.**

Make `Universe#updatePlanet` not modify the position of the planet, to allow custom solar systems, as well as a new variable in `Planet` to denote it being the root of a solar system. `Universe#updateGlobal` would also use `Vars.content.planets().copy().filter(p -> p.isRoot).forEach(p -> updatePlanet(p));`, rather than just `updatePlanet(Planets.sun)`

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would allow modders to separate their content from vanilla's in a more distinct way.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
did you seriously-

**Comment by QmelZ** [comment]
~~*mods*~~

**Comment by Bottinator22** [comment]
No, don't disable orbits, but allow having planets orbit other planets, including themselves if needed to be static

**Comment by NiChrosia** [comment]
I never said disable orbits

**Comment by Bottinator22** [comment]
I don't know the source code that well, but I think preventing updatePlanet from modifying the position of the planets (which is what moving is) would break orbits

**Comment by NiChrosia** [comment]
`updatePlanet` is only called for the sun at the moment, and not any children of it.
