### ISSUE TITLE
Co-op campaign needs to be improved

### ISSUE THREAD

**Issue by SpoonPotato** [Anuken/Mindustry-Suggestions#2736]
### Describe what you would like changed, and why.

One of the only incentives to buy the game on steam is to play multi-player with steam friends. While PvP works just fine, the co-op campaign can be really annoying. Recently I decided to gift a friend Mindustry on steam, only to discover that it was frustratingly unintuative for the non-hosting player. The specific mechanics can be seen in the [build 121 log](https://store.steampowered.com/news/app/1127400/view/2901970757302390919)  from last year, which are playable, but have issues with sharing progress, especially research. 

I don't know much about programming, but judging by the fact that Anuke didn't fix everything outright, it isn't an easy task. However, I think a change is necessary if Mindustry is to remain a paid steam game. 

### Describe the changes you want to propose. Include possible alternatives.

A co-op system that fully syncs the research and resources of the host with the client during the campaign.

**Comment by Anuken** [comment]
Do not assign issues to me. Any further unnecessary pings will get you blocked from this repository.
