### ISSUE TITLE
Make Unit Logic can locate "ghost block"

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2737]
### Describe the content or mechanics you are proposing.

add a new tag to the Unit Locate logic command: "Destroyed" output: x; y; building
it'll detect the nearest ghost block

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

improve logic rebuilding, currently is impossible(?) to rebuild buildings

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
Do not assign issues to me. Any further unnecessary pings will get you blocked from this repository.

**Comment by vinhsad** [comment]
Wait, I didn’t even know how to assign

**Comment by BlueTheCube** [comment]
this is good actually
