### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2738]
A way to see, modify, add or remove screenshots inside the app. 

Currently, you can only modify and remove screenshots when your data is exported. Also allow a new feature in the game data called **Remove Screenshots** to clear all the pictures on the game, creating a significant decrease of storage used when exporting.

**Comment by EclipsePlays** [comment]
Where did the the flair go?

**Comment by Humanoid-X** [comment]
Hmm... Template

**Comment by itcannotbe** [comment]
> Hmm... Template

Github oversight.  The app wasn't updated to read issue forms.

**Comment by EclipsePlays** [comment]
> Hmm... Template

This issue was made while the beta issue making PR is implemented, which is unavailable for GitHub mobile.
