### ISSUE TITLE
allow payload units to pick up derelict blocks

### ISSUE THREAD

**Issue by AureusStratus** [Anuken/Mindustry-Suggestions#2739]
### Describe the content or mechanics you are proposing.

allow payload units to pick up derelict blocks so they can put in deconstructors

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

So the recent dev post show the new deconstruct that will turn blocks back in too items and sense when your playing campaign and when you kill an enemy core all blocks turns to derelict blocks if they weren't destroyed already and they don't do much and are manual deconstructed by the player normally but this doesn't give you the full amount of resources that where used to make the blocks so why not allow payload units to pick them up and carry them and take them to deconstructors or payload conveyors so you could get the full amount of resources from the enemy base blocks i say this would be pretty cool to have and this might make player more careful about what they destroy so that they can recycle it later when the enemy core is gone this could even be paired with new ai for the payload units where they will seek out derelict blocks and take them to the nearest deconstructor to be recycled as long as there isn't any crux cores or other enemy cores around on the map

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This makes 0 sense. You can just deconstruct them outright bruh.

**Comment by itcannotbe** [comment]
Close this, Implemented.

**Comment by AureusStratus** [comment]
it is?

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry/commit/9160ee546ceb3684bfc61e47eb914c7ec1a1a51b

**Comment by itcannotbe** [comment]
Still concerned that you might be able to use the block to basically make a defense. Especially on maps that use delerict with sandbox blocks.

**Comment by AureusStratus** [comment]
so payload units can already pick up derelict blocks?

**Comment by itcannotbe** [comment]
Try checking with the latest BE, but in theory they should.

**Comment by AureusStratus** [comment]
derelict blocks dont attack and all them attack like walls basically
