### ISSUE TITLE
the editor`s spawns

### ISSUE THREAD

**Issue by JuanCamiloGTH05** [Anuken/Mindustry-Suggestions#274]
i`d like to change that you cant simply delete the spawn block in the editor it is an IMPORTANT problem

**that can delete spawn blocka**

**Comment by itcannotbe** [comment]
Here to inform you that ...:
1. You are not following the template
2. **YOU CAN ACTUALLY REMOVE PLACED SPAWN TILES IN-GAME**

**Comment by Anuken** [comment]
Spawn blocks are treated as an ore, so just place a tile over them.
