### ISSUE TITLE
Eclipse and Antnumbra - AI rebalance

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2740]
### Describe what you would like changed, and why.

Right now, even with Eclipse's rebalanced state, people still states them as "meatbags" when used by enemies in Survival and Attack gamemodes. 

That's because they were just menacingly looking at those walls and firing their weapons like a braindead unit. 

Maybe not just the weaponry needs to be rebalanced, but also the AI. 

### Describe the changes you want to propose. Include possible alternatives.

Changes:
A new AI which makes Eclipses and Antnumbras ram the defense and explode, dealing massive amounts of fall damage and explosion damage in the time being. (Pretty similar to v5 lich AI but their target is the back of the defenses and not the core) 

Opinion: 
For crux units that'd be completely okay since their only task is to destroy the sharded cores but if used by the allies, that could be completely devastating since they are deploying a 1000 silicon t5 to just eliminate a portion of their defence. But this opens a new counter against them: Tsunamis and Waves. 

Alternative:

Antnumbras and Eclipses' first objective is to pathfind to the core, and it's second objective is to **survive**. And if there are no other choices left, that's where it dives and goes suicide. 

**This issue is still in an open discussion. Feel free to state on what will happen if the changes gets passed or if you want to state another solution.**

**Comment by itcannotbe** [comment]
> Antnumbras and Eclipses' first objective is to pathfind to the core, and it's second objective is to survive. And if there are no other choices left, that's where it dives and goes suicide.

That's not how AI works, It can't learn on the fly.

**Comment by itcannotbe** [comment]
> Make the Eclipse's laser beam become passable through plastanium walls, and boosts the base speed of the units to 9 blocks/s. It probably helps them raid the inner defense.

Try keeping up with consistency. Not making random exception to anything.

If something can block laser type weapons then it blocks them all.

**Comment by SupremeTurtle** [comment]
...you don't just make a laser pierce Plastanium Walls, it's not how it
works

**Comment by EclipsePlays** [comment]
> If something can block laser type weapons then it blocks them all.
> 
~~Maybe remove it from the laser type weaponry and go to point attack mode, similar to foreshadows?~~

**Comment by JrTRinny** [comment]
> Antnumbra

typo

**Comment by itcannotbe** [comment]
@SupremeTurtle Try not sending the original message when sending an email reply.

**Comment by JrTRinny** [comment]
This is my alternative version, your version is kinda like suggesting new mechanic, not balancing:

I think only "**Lich AI**" is perfect for this, no need for a new AI

Lich AI would make Impact 0078 harder, and it's great, since Impact are supposed to be harder than Tar Fields, and it'd make people learn and finally beat those hard surrounding sectors, and North Pole, it will poses as a gateway to *hell*, if you can't beat this, you probably won't beat North Pole

and Antumbra(+Eclipse) in v5 are much more scarier, in v6 it's just flying garbage, with the usage of *Lich AI* I think it'd make them unique and usable, with some speed buff and it's set

**Comment by BorisA11** [comment]
Make them just go straight to the Core, evading as many turrets as possible.

**Comment by Kyllingene** [comment]
Ah yes, because doing A\* while also checking every single turrets range and determining if it is possible to evade it, then doing *more* A\* if that doesn't work is a simple thing. Remember that A\* takes even longer to do if there is no available path.

**Comment by EclipsePlays** [comment]
Ok so Alternative Balance 2 removed from the list...

**Comment by EclipsePlays** [comment]
Closing.

**Comment by OnyxFinger** [comment]
> This is my alternative version, your version is kinda like suggesting new mechanic, not balancing:
> 
> I think only "**Lich AI**" is perfect for this, no need for a new AI
> 
> Lich AI would make Impact 0078 harder, and it's great, since Impact are supposed to be harder than Tar Fields, and it'd make people learn and finally beat those hard surrounding sectors, and North Pole, it will poses as a gateway to _hell_, if you can't beat this, you probably won't beat North Pole
> 
> and Antumbra(+Eclipse) in v5 are much more scarier, in v6 it's just flying garbage, with the usage of _Lich AI_ I think it'd make them unique and usable, with some speed buff and it's set

ok but in v5 they weren't scarier, they'd die too fast in order for their AIs to be annoying, unless you suck really hard against air and you don't take it as quite as big of a threat, which is probably what happened to most
but with more hp, I definitely see them work better
