### ISSUE TITLE
Split "Attack" command into 2

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2741]
### Describe the content or mechanics you are proposing.

As of now, the Attack command from the command center makes units go to Enemy cores (or whatever is their preferred target.) or enemy spawn points. This creates problems with attack maps with both cores and enemy spawn points.

My proposal is splitting the attack command into 2: **Defend** and **Attack**
Defend makes units go to spawn points, Attack makes them go for cores.

Alternative:
Make it so in maps flagged with "Attack mode" in rules, the units go for cores, and not spawn points. This may cause issues as some people may want units to go to spawn points.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More control over units, fixes some annoyances in some maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I think the alternative is better since the first proposal entails actually adding more lines to the current ai to accomplish it

**Comment by RouterChainsSuckk** [comment]
i made a very similar suggestion but sure
