### ISSUE TITLE
New operators

### ISSUE THREAD

**Issue by TripleToxic** [Anuken/Mindustry-Suggestions#2742]
### Describe the content or mechanics you are proposing.

For now, make a mean, median. mode, range calculator is not hard but long and cannot choose 
Mean don't need arrays but it can look like normal +,-,×,÷ operation with little bit different 
Median, mode and range can separate by commas

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It can make some logic calculators almost in dead end or some calculators need them for working

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Describe how you think this content will improve the game

But how?

**Comment by TripleToxic** [comment]
> > Describe how you think this content will improve the game
> 
> But how?
How what

**Comment by TripleToxic** [comment]
How what

**Comment by oinkymoo** [comment]
operator commands work on at most 2 numbers, and logic currently has no support for lists or arrays of any kind. until that support gets added this suggestion is pointless

**Comment by TripleToxic** [comment]
k
