### ISSUE TITLE
Add hint related to core units not doing damage to buildings.

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2744]
### Describe the content or mechanics you are proposing.

Kinda self explanatory.
Add a hint for when you try to attack enemy buildings with the core units, detailing about the use of units and turrets to destroy buildings.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While most players realize it fairly quickly, I've seen countless players trying to attack enemy bases with their mere core units.
Clears up confusion.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ah yes. People can't be arsed to check the unit info of their unit in the database. Yes.

**Comment by oinkymoo** [comment]
i mean, if you see that you can do combat with units, you would have no reason to assume that it wouldn't work on buildings unless you get suspicious of how long its taking. i approve
