### ISSUE TITLE
Make a more organized tech tree

### ISSUE THREAD

**Issue by CrowOfJudgement47** [Anuken/Mindustry-Suggestions#2745]
### Describe the content or mechanics you are proposing.

Individual sections for different categories of blocks on the tech tree 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

What if the tech tree was split into individual  sections like one for turrets. One for defense, ect. This would help keep the tech tree more organized

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
And this would achieve what?

Most blocks are locked behind the capture of certain sectors anyways.

And the branching is almost like what the suggestion suggests anyways.

**Comment by oinkymoo** [comment]
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> *

really?
<img width="1280" alt="Screen Shot 2021-07-25 at 9 57 13 PM" src="https://user-images.githubusercontent.com/75851043/126924275-e0c4d45a-a46f-43b3-8e8f-c07842596da1.png">
red: transport (for both items and units)
orange: liquids
yellow: sectors
lime: materials
green: power (and some things that use it)
cyan: factories
blue: units
purple: logic
pink: drills
white: walls
gray: turrets
misc is, you know, misc, and is mixed in everywhere

if this isnt a section for each category, i dont know what is

**Comment by Kyllingene** [comment]
The problem with this (besides the fact that it already exists) is that any more segregation and it would no longer be a tree, which would be a huge effort for nearly no gain, if any.

**Comment by Humanoid-X** [comment]
................  ISNT IT ALREADY SPLITTED DO YOU HAVE BAD EYESIGHT OR WHAT
