### ISSUE TITLE
[Logic] Overhaul the pathfind command

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry-Suggestions#2747]
### Describe the content or mechanics you are proposing.

Add a unit parameter to the pathfind command to load the AI of the unit you select

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow logic-bound units to act normally when not being actively commanded instead of sitting in place like a lobotomy patient, and users could utilize multiple unit types for the same task (like megas helping out with construction, for example)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> I am familiar with all the content already in the game

I'm pretty sure you can already use a different ai for units.....

**Comment by oinkymoo** [comment]
> > I am familiar with all the content already in the game
> 
> I'm pretty sure you can already use a different ai for units.....

i would love to know how to do so without writing an entire logic for one

**Comment by vinhsad** [comment]
this was suggested by many people ago (include me) but i still want it to be in-game :<
