### ISSUE TITLE
Cultivator

### ISSUE THREAD

**Issue by LmaoPosto** [Anuken/Mindustry-Suggestions#2748]
### Describe the content or mechanics you are proposing.

cultivator will work without need water when placed on the water surface

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

cultivator will work and don't need water when placed on fully water surface, when placed on one water surface tile is 25%, when placed on non-water tile half water surface tile is 50%, when placed on fully tile water surface is 100%. also water surface tile each per 25%

25% - very slowly automatically output
50% - slowly automatically output
75% - bit slow automatically output
100% - automatically output

(Edit:i mean if cultivator placed on non water tiles and still need water to work by pump water and something, Also if cultivator has 75% or 25% you can make them to 100% by pump water or something)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MostForgettablePerson** [comment]
Cultivator doesn't have a pump, it's just a grower, you still have to pump water near the cultivator

**Comment by itcannotbe** [comment]
Is that hard to place a pump beside a cultivator?

**Comment by LmaoPosto** [comment]
I mean if cultivator placed on non water tiles its 0% and still need water to work by pump water and something (i hat3 auto correct)

**Comment by JrTRinny** [comment]
I cannot understand what you're trying to say

**Comment by EdgeOfDestiny** [comment]
this is a terrible idea

**Comment by Humanoid-X** [comment]
Tihs sugegstoin is very teribrle you lazy and spioled brat
Is it so hrad to plcae some pmups
