### ISSUE TITLE
throw away the load if needed

### ISSUE THREAD

**Issue by Einoll** [Anuken/Mindustry-Suggestions#2749]
### Describe what you would like changed, and why.

i'd like to change the feature of the units that makes impossible for them to drop things to the ground on their own
why?
because when the core is full and there isn't any building available to them to get empty, they just can't mine another ore

### Describe the changes you want to propose. Include possible alternatives.

the 'dropItem' command can be used to throw items to the ground like the main character does, but with a processor 
an alternative to this would be that when an unit mines something and changes to mine other thing, like, a mono mining copper, and with copper in it, when for whatever reason it gets the instruction to go to mine lead, the copper in it just disappear to make it capable of mining lead

**Comment by itcannotbe** [comment]
Automated Item Greifing via Logic Drop Command in 3, 2, 1........

**Comment by itcannotbe** [comment]
Take a container, put some unloaders, and some incinerators. Done.

**Comment by Einoll** [comment]
it's for not letting the wrong people have that power?
still would be funny and logic tho

**Comment by Humanoid-X** [comment]
use logic bruh

**Comment by Yell245** [comment]
> Automated Item Greifing via Logic Drop Command in 3, 2, 1........

Make it so you can disable it in the server config :/

**Comment by OnyxFinger** [comment]
> Automated Item Greifing via Logic Drop Command in 3, 2, 1........

? I think logic itself was made with the perfect conciousness it would have been grief land forever

**Comment by Humanoid-X** [comment]
~~Not a problem, afaik griefers are all noobs and logic is *very confusing*~~

**Comment by itcannotbe** [comment]
> ~Not a problem, afaik griefers are all noobs and logic is _very confusing_~

~Logic is not for the stupid, but schematics is a free fall all including those that contain logic.~

**Comment by stuffyAI** [comment]
> Automated Item Greifing via Logic Drop Command in 3, 2, 1........

To be fair, with the amount of griefing already available due to logic I don't see this making it worse, it will just get disabled anyway
