### ISSUE TITLE
Tech tree in custom maps/Custom campaigns/Custom tech tree

### ISSUE THREAD

**Issue by Azudaah** [Anuken/Mindustry-Suggestions#275]
I don't know how this fits within the new update under development, but I would like to propose a few way to implement the tech tree into custom maps :
-When creating a map, an option to create/activate a tech tree system (like in the campaign but on single map)
-Possiblity of creating custom campaigns : map linked to each other (with conditions, choices, etc..), tech tree activation/creation to fit the campaign
-Possibility of modifying the tech tree to fit the map : change the order of technologies, resources needed, etc..

The reason I think this would be a great addition to the game and improve its potential is that I loved the campaign and the fact that you have to accumulate resources while defending yourself in order to develop new techs to unlock new blocks/towers/mechanics : it gaves another objective, another reason to stay/survive longer on the map, as well as some risky choice : staying longer to get more ressources but risking to loose everything if destroyed before the next checkpoint.
But once I finished it and went to the custom maps I felt it missed something : there is no point in stacking resources in your core anymore (besides of course for the sake of using it on the map) : and so there's little need for a big factory : you just need the bare minimum to continue building and feeding your towers.

I believe that adding the option for a tech tree to customs maps and/or custom campaigns creation would fill that gap, create a new objective, a new reason to build bigger/more optimized processing factory, and thus greatly improve the depth of the game, as well as adding new challenges/replayability.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
mods
