### ISSUE TITLE
Dynamic music

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2751]
### Describe the content or mechanics you are proposing.

Music that plays when doing specific tasks.
A few examples:
Attacking
Being Attacked
Player boss (attacking with a t4-t5 unit)
defeat
victory

(Yes I know trello has something similar, but I wanted to expand upon it.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's neat, I guess.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
boss was done
also I think game4 is dynamic too ?
but I would definitely agree that the game needs mor-- what's that I hear you guys say ? THE TEMPLATE WAS BLINDLY FILLED WITHOUT BEING RESPECTED ? THERE IS MORE NEW/NEW MUSIC IN THE TRELLO ?

ok I'll give this the benefice of the doubt and say that "dynamic was specifi---
> weather specific music
ok how about specific to other stuff than weather ? Is it too much doubt benefice ? TBH I'd like some more PvP-fitting tracks

https://trello.com/c/mKr4DGPJ/787-more-new-music

**Comment by OAtobaAzul** [comment]
**"(Yes I know trello has something similar, but I wanted to expand upon it.)"**
As per the boss, I know it exists, but afaik it only plays with guardian waves.

**Comment by OnyxFinger** [comment]
ok
kinda sus tho
but definitely some more music, especially gamemode specific music would be fun

**Comment by Ksawi999** [comment]
> gamemode specific music would be fun

Sandbox music...

**Comment by OnyxFinger** [comment]
happy stale noises

**Comment by OnyxFinger** [comment]
sad, this one was good
