### ISSUE TITLE
Buff Vela

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry-Suggestions#2752]
### Describe what you would like changed, and why.

Vela is a (kinda) short-range t4 unit, unlike Quad, its health, speed, range and damage is too bad for it to be usable, and it makes Tar Fields super easy, with the fact that Plastanium wall can block the laser completely.
We’ve discussed about this in discord `#balancing`, everyone (that joined the discussion) have no objection.
I’d like to buff it, so it’s usable as attack mech, and makes Tar Fields harder (in a good way)

### Describe the changes you want to propose. Include possible alternatives.

(initial stats based on auto-generated wiki)
Health 7500 -> 8000
Damage 360 -> 390
Speed 2.92 -> 3 (in tiles/second)
Range 21 -> 23 (basically reverting change from v6)

if this is too much, tell me

I have no Possible alternatives

**Comment by OnyxFinger** [comment]
do it.
Velas are generally kinda trash, except maybe in survival (or attack) in an early wave, but then it wouldn't be stacked enough on stats in other gamemodes, like PvP and attack where making velas doesn't make a whole lot of sense

**Comment by joshuaptfan** [comment]
The vela just got some buffs in [this commit](https://github.com/Anuken/Mindustry/commit/c19a7e8452618043d7adf02680f7da095ca04d6b#diff-b3eda7727012924823c3857256911ee0220bc628c1b72d5757758f264b34e471).

**Comment by JrTRinny** [comment]
wow, seems like Anuke like this one, another balancing **successful**!
