### ISSUE TITLE
Buildings

### ISSUE THREAD

**Issue by bosko2** [Anuken/Mindustry-Suggestions#2753]
### Describe the content or mechanics you are proposing.

I would recommend a building with floors and a roof. Each floor would have its mass limit before it collapses depending on its material. Each floor should be placed on walls(big walls would support 2 by 2 buildings underneath, small only 1 by 1 etc.). I think floors should be near end of research tree because it is a very premium feature. It would be nice to also have vertical conveyors.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make giant contraptions which would usually take the whole map into small ones. It would be easier to find space on small maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
it would be hard to see what's under every floor/roof

**Comment by Kyllingene** [comment]
Even besides the horrendous amount of work, the niche usage, and the overcomplication, this is either useless or nearly so because of one critical flaw: *how do you get the resources into/out of factories that are in the buildings?*

**Comment by oinkymoo** [comment]
why do you expect a third dimension to be added to a 2d game because that is what this would require

**Comment by Humanoid-X** [comment]
No.
