### ISSUE TITLE
Load structures with unit inventory items

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2755]
### Describe the content or mechanics you are proposing.

When you pick up a block, make it use the unit's item inventory to load itself with materials needed to operate
Example: Oct that has 280 blast compound picks up a Swarmer, the Oct some of the blast compound to give it to the swarmer that has been picked, so when dropped back into the world, it'll be ready to shoot.

Not sure if I worded this properly, it's midnight atm.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Opens possibilities for a payload-turret based playstyle with payload-capeable units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i feel like there could be a case where you specifically want this to not happen but i cant think of any

**Comment by itcannotbe** [comment]
Well you can already construct turrets for pickup via constructor and can have ammo already in them via block loader.

So this suggestions would be redundant in that manner. Though this isn't a bad suggestion. Maybe just implemented in a different, more user friendly way.
