### ISSUE TITLE
[Logic] Allow RequestConfig to be set using item's ID

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry-Suggestions#2756]
### Describe the content or mechanics you are proposing.

Allow logic processors to set a block's [request config](https://github.com/Anuken/Mindustry/blob/f5222674ff820fab215d3205c6eaad5fa5713e63/core/src/mindustry/world/blocks/distribution/Sorter.java#L35) by entering the item's ID number

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Exposing this integer ID to logic will allow people to easily create an index of all items that can be utilized in smart crafting systems by iterating over all the registered items without 32+ lines of bloated instructions

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
can you explain what request config is because i do not understand
