### ISSUE TITLE
3rd air and naval branch

### ISSUE THREAD

**Issue by canadianjoker** [Anuken/Mindustry-Suggestions#2758]
### Describe the content or mechanics you are proposing.

like the crawler branch, where it is able to interfere with the enemies attacking, like life steal and slag pools, but based on their unit build, air would be more of a fly by attack with trails that slow and can be ignited like oil, and naval that pollute the water to corrode the enemy ships, and slow the enemy.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think this would be a great addition to the game, as it would provide an offensive way to play that relies on debuffs, and would have greater crowd control methods. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
I love the idea of debuff-based combat; I hate the fact that all unit-related suggestions have to be "make all the unit trees the same".

**Comment by OnyxFinger** [comment]
this is cool, but right now debuff based combat has been proven just as innefficient as melee units (*I'm looking at you crawler tree*), and as Kyllingene pointed out, this idea is very similar to the existung crawler route
also, we do not need more crowd control methods.

However, I think having a purple/special route for air and naval makes sense

**Comment by itcannotbe** [comment]
More units != More Better.

**Comment by itcannotbe** [comment]
If anything more units just allows you to have more units on the map, which most you don't even need. Considering Unit Cap.

**Comment by OnyxFinger** [comment]
> More units != More Better.

depends on wether or not they are copies of pre existing units ~~this this suggestion~~

> If anything more units just allows you to have more units on the map, which most you don't even need. Considering Unit Cap.

well it makes more sense, and tbh unit cap is more of something in the way that only makes T3+ units good by making -T4 units not very scalable, which is running away from a problem

**Comment by itcannotbe** [comment]
> > If anything more units just allows you to have more units on the map, which most you don't even need. Considering Unit Cap.
> 
> well it makes more sense, and tbh unit cap is more of something in the way that only makes T3+ units good by making -T4 units not very scalable, which is running away from a problem

What if someone was to suggest to make the unit cap something like StarCraft's unit cap?

**Comment by OnyxFinger** [comment]
> > > If anything more units just allows you to have more units on the map, which most you don't even need. Considering Unit Cap.
> > 
> > 
> > well it makes more sense, and tbh unit cap is more of something in the way that only makes T3+ units good by making -T4 units not very scalable, which is running away from a problem
> 
> What if someone was to suggest to make the unit cap something like StarCraft's unit cap?

huh? WHy do you bring this up ?

**Comment by Kyllingene** [comment]
> I think having a purple/special route for air and naval makes sense

I actually think that even such a thing as that should be left alone; think about it. It is the only special thing about ground units; they simply aren't as useful as the other classes. I want to see each class branch out separately, not see each class get each tree in similar ways.

**Comment by OnyxFinger** [comment]
> > I think having a purple/special route for air and naval makes sense
> 
> I actually think that even such a thing as that should be left alone; think about it. It is the only special thing about ground units; they simply aren't as useful as the other classes. I want to see each class branch out separately, not see each class get each tree in similar ways.

?????
What the fuck did you smoke ? Seriously, ground' only quirk isn't being useless, right now it IS, but it isn't necessarily supposed to be
If you base any balance/new content around unbalanced, the result won't be pretty
