### ISSUE TITLE
Async loading screen

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2759]
### Describe what you would like changed, and why.

Currently the loading screen freezes as the game loads content. Would like that to be changed so the fps and animations stay at 60 fps (or whatever you are at) while loading.

### Describe the changes you want to propose. Include possible alternatives.

Have the loading screen asynchronous from the content loading itself (though of course still displaying full loading progress), so that the full animations play. Hopefully not that difficult, but it'd be a nice QOL change.
*yes, i know much of mindustry doesnt do stuff like that but **visuals***

**Comment by itcannotbe** [comment]
Isn't dedicating the available system resources to actually loading the game rather than making the loading screen better the way to go?

**Comment by joshuaptfan** [comment]
Dedicating an entire thread to just... 2D animations on a loading screen?

**Comment by Kyllingene** [comment]
I have no problems with the current loading screen. Perfect accuracy is not even close to a concern on on such as the one Mindustry has.

**Comment by BlueWolf3682** [comment]
> Isn't dedicating the available system resources to actually loading the game rather than making the loading screen better the way to go?

Async loading means it would use different threads for loading and the animation - any CPU should be able to handle doing this, especially since all CPUs nowadays are dual or better core. The RAM usage will probably be insignificantly higher, not a problem.

**Comment by BlueWolf3682** [comment]
fuck mistapping

**Comment by itcannotbe** [comment]
> > Isn't dedicating the available system resources to actually loading the game rather than making the loading screen better the way to go?
> 
> Async loading means it would use different threads for loading and the animation - any CPU should be able to handle doing this, especially since all CPUs nowadays are dual or better core. The RAM usage will probably be insignificantly higher, not a problem.

I just remembered someone suggesting this already with an anuken reply but I can't remember where.

**Comment by Anuken** [comment]
- Loading in a different thread instead of blocking would increase loading times.
- Significant portions of the loading time need to be on the main thread due to OpenGL operations.
- Rewriting everything to load in a different thread would be a colossal effort with very little benefit.
