### ISSUE TITLE
Addition to Amazon Appstore

### ISSUE THREAD

**Issue by goodevilgenius** [Anuken/Mindustry-Suggestions#276]
**Describe the content or mechanics you are proposing.**

The Android game should be available on the Amazon Appstore.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Folks who have a Kindle Fire would be able to play the game without sideloading.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
`snapd install mindustry`
