### ISSUE TITLE
easier campaign modding

### ISSUE THREAD

**Issue by iguxakak** [Anuken/Mindustry-Suggestions#2760]
### Describe the content or mechanics you are proposing.

make planets via json or hjson.
For example, in the mod folder there will be a "campaign" section with nameplanet.hjson and nameasteroid.hjson,
and in nameplanet.hjson it will be like this:
`name:

generator:

mesh:

orbitradius:

orbittime:

rotatetime:

bloom:

accessible:

hasAtmosphere:

armosphereColour:

atmosphereRadIn:

atmosphereRadOut:

startsector:

alwaysUnlocked:

textureplanet:

zones:`

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this can increase the ability to accommodate even more content

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Look mom! I made a planet with **NOTHING** in it. -_-

**Comment by JrTRinny** [comment]
I mean, the hard part is planet sprite (idk how Serpulo planet works) and sectors

**Comment by Kyllingene** [comment]
This sounds nice and simple; now you just have to explain how that `generator` tag works.
