### ISSUE TITLE
Animation for loadout blocks

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2761]
### Describe the content or mechanics you are proposing.

Upon landing, core has its thrusters and lands using them.

The drills that are deployed at start are just there. Noone puts them, noone builds them.

There are several options to fix this:
1 - Upon landing, Core releases a few small drones which build the structures
2- Blocks land as well, falling after the Core, filling up the loadout. Makes sense for some larger things, but not, let's say, conveyors or turrets, which have no change of surviving reentry.
 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Makes sense to me.

Purely a visual thing, but I think many players would like it to be added.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I like this idea too, and it makes sense

**Comment by itcannotbe** [comment]
> 1 - Upon landing, Core releases a few small drones which build the structures

Probably the better alternative is for the core unit to build the structures as releasing drones you don't own isn't ideal.

~Bug Report: Drones disappear after launching into a sector~

**Comment by Anuken** [comment]
I'm aware of the lack of logic concerning loadouts upon landing, but neither of these solutions seem all that appealing. I may or may not try to incorporate the new block constructors into the loadouts, so the system makes a little more sense.

**Comment by BorisA11** [comment]
> I'm aware of the lack of logic concerning loadouts upon landing, but neither of these solutions seem all that appealing. I may or may not try to incorporate the new block constructors into the loadouts, so the system makes a little more sense.

That would make sense. Or Core somehow building them, I dont know if that is possible though.

**Comment by OnyxFinger** [comment]
> I'm aware of the lack of logic concerning loadouts upon landing, but neither of these solutions seem all that appealing. I may or may not try to incorporate the new block constructors into the loadouts, so the system makes a little more sense.

this definitely looks appealing to me
