### ISSUE TITLE
More Core mechanics

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2762]
### Describe the content or mechanics you are proposing.

Now that Cores got updated visually, I'd really love for them to get some more functionalities, like:
-Core building drones - emerges out of the Core and assists in building for X time, then returns back, or at later tiers, stays until destroyed
-Core defence drones - emerges out of Core if enemies are nearby, fires with sap weapons and knockback beams, mostly designed for repelling the enemy. These have a cooldown, once they return they can not activate for 10 minutes or so
-Overdrive fields - upon landing, an overdrive effect is applied 20, 30, or 40 blocks away from the core, depending on the type. This accelerates buildings by 15, 25 or 40% and applies the overclock effect to units. Wears off over time.
-Shields - applies shields for first X after landing to units and blocks nearby

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Makes starting easier on hard sectors, and probably is a lot more useful on other planets. Potentially add more functionalities for other planets.

Adds room for various upgrades, and unlocking of the bonuses, a nice way to dump excess resources in research.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ah yes.

![Screenshot_20210725_201304](https://user-images.githubusercontent.com/45280919/127326996-f9cffab0-14f5-40c5-9140-560f68832122.jpg)
![Screenshot_20210728_210427](https://user-images.githubusercontent.com/45280919/127327046-a64a49b4-1734-432e-b16c-f2468b996de3.jpg)

**Comment by Yell245** [comment]
Defence drones won't make sense from the point of lore because core units are made to defend it. Maybe buff core unit after landing instead?

**Comment by Yell245** [comment]
> Ah yes.
> 
> ![Screenshot_20210725_201304](https://user-images.githubusercontent.com/45280919/127326996-f9cffab0-14f5-40c5-9140-560f68832122.jpg)
> ![Screenshot_20210728_210427](https://user-images.githubusercontent.com/45280919/127327046-a64a49b4-1734-432e-b16c-f2468b996de3.jpg)

And now tell me where is your "merged behaviour blocks like turrets on top of cores"?

**Comment by itcannotbe** [comment]
> > Ah yes.
> > ![Screenshot_20210725_201304](https://user-images.githubusercontent.com/45280919/127326996-f9cffab0-14f5-40c5-9140-560f68832122.jpg)
> > ![Screenshot_20210728_210427](https://user-images.githubusercontent.com/45280919/127327046-a64a49b4-1734-432e-b16c-f2468b996de3.jpg)
> 
> And now tell me where is your "merged behaviour blocks like turrets on top of cores"?

-Overdrive fields - upon landing, an overdrive effect is applied 20, 30, or 40 blocks away from the core, depending on the type. This accelerates buildings by 15, 25 or 40% and applies the overclock effect to units. Wears off over time.
-Shields - applies shields for first X after landing to units and blocks nearby

Basically, cores merged with overdrives and cores merged with force projectors.

**Comment by BorisA11** [comment]
This is not merged behaviour by any means - its a core specific thing. Just as Bryde having overdrive field isnt a "merged behaviour"

**Comment by BorisA11** [comment]
> Defence drones won't make sense from the point of lore because core units are made to defend it. Maybe buff core unit after landing instead?

Yeah, or do that. And, why not have multiple core ships? Of course, the one made on landing are much smaller and weaker.

**Comment by itcannotbe** [comment]
> This is not merged behaviour by any means - its a core specific thing. Just as Bryde having overdrive field isnt a "merged behaviour"

You see how the example given is a core and a turret right?

Also since when is a bryde a block?

**Comment by OnyxFinger** [comment]
interesting but the Overdrive field and shield is doesn't bring much
the idea of defense and building drones can be cool though
the starter drones can be useful a "deployement" phase

**Comment by itcannotbe** [comment]
> the starter drones can be useful a "deployement" phase

Why was the free drone removed again?

**Comment by oinkymoo** [comment]
> > > Ah yes.
> > > ![Screenshot_20210725_201304](https://user-images.githubusercontent.com/45280919/127326996-f9cffab0-14f5-40c5-9140-560f68832122.jpg)
> > > ![Screenshot_20210728_210427](https://user-images.githubusercontent.com/45280919/127327046-a64a49b4-1734-432e-b16c-f2468b996de3.jpg)
> > 
> > 
> > And now tell me where is your "merged behaviour blocks like turrets on top of cores"?
> 
> -Overdrive fields - upon landing, an overdrive effect is applied 20, 30, or 40 blocks away from the core, depending on the type. This accelerates buildings by 15, 25 or 40% and applies the overclock effect to units. Wears off over time.
> -Shields - applies shields for first X after landing to units and blocks nearby
> 
> Basically, cores merged with overdrives and cores merged with force projectors.

It’s not a force projector, unless I’m reading it wrong. It gives armor to units, it doesn’t protect the nearby buildings at all

**Comment by BorisA11** [comment]
> It would be normal shield as armor operates differenttly, though why do you need to place a shield on your blocks?

To increase their healthpoints. Or just apply a "barrier" around the core, which works like T4 support naval's field, but longer range and more slowness to enemies is applied. Also applies -X% damage to blocks, increasing their HP.

**Comment by Kyllingene** [comment]
We have more than enough ways to defend the core as it is. ***Use them.*** If they are at your core, you made many mistakes.
