### ISSUE TITLE
New drills Well look at the details before you say this and that.

### ISSUE THREAD

**Issue by ImNotVeryGoodAtThought** [Anuken/Mindustry-Suggestions#2763]
### Describe the content or mechanics you are proposing.

1, Hydraulic drill of course better than air-pressure drill, but the difference is its not larger all round its wider about 2 blocks in both directions, as it says it's Hydraulic, Yep requires water as its base for production, Oil can do the same effect but better.
(Recommended resources: Titanium, Silicone, Phase fabric. Other resources can be included.

2, Phase Catalyzer, a silly name for a drill right? though this is as large as a laser drill instead of using liquids for drills this uses the phase fabric as a fuel source though make matters worse this uses a lot more power than most drills combined.
its basically the saying "It breaks the fabric of reality" though requires 3 phase fabric just for resources to appear.
"That's one greedy drill"

***Yes I checked the Trello, but if this is someone to add-in to your heads so don't say cool that's a repost and deleted me. take consideration, I might surprise you.***

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

These will expand the drills other than just simply convivence based machines and adds more complicated versions at most.
Bigger isn't always better, But more variety more the fun. if you have thoughts of expanding please add more suggestions like this don't credit me or hate me of course. 
I'm here like this "Hey nice suggestion you got there, You've inspire me." 
and not this "Cool and what else?"
**Now lets go back to this "  Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche."**
These drills will expand the factories and tech the game already has and it will fill new niches for the community to use as if because sometimes less limits powers the mind of many, I love your work ***Anuken*** You never disappoint me.

***Yes i checked the Trello, but if this is someone to add-in to your heads so don't say cool that's a repost and delete me. take consideration, I might surprise you.***

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ImNotVeryGoodAtThought** [comment]
***Yes I checked the Trello, but if this is someone to add-in to your heads so don't say cool that's a repost and delete me. take consideration, I might surprise you.***

**Comment by itcannotbe** [comment]
Also airblast: Anyone who uses me without water is an idiot.

**Comment by ImNotVeryGoodAtThought** [comment]
i don't check mods so i don't have most ideas what this and is

**Comment by ImNotVeryGoodAtThought** [comment]
> Also airblast: Anyone who uses me without water is an idiot. 
me: continues no water

**Comment by MrDuck557** [comment]
drop a single water extractor right next to the airblast

**Comment by itcannotbe** [comment]
Or use a block unloader to unload water to it. XD

**Comment by OnyxFinger** [comment]
but if you checked the trello, you should've seen this https://trello.com/c/hV2fzCib/859-new-drills right ?
ohno

**Comment by oinkymoo** [comment]
airblast with water already drills more sand than can fit on a single tita belt, so anything better is pretty much never happening

**Comment by ImNotVeryGoodAtThought** [comment]
Rip

**Comment by Humanoid-X** [comment]
You;, rest in piss
