### ISSUE TITLE
Developer mode for logic

### ISSUE THREAD

**Issue by datlongboi** [Anuken/Mindustry-Suggestions#2765]
### Describe the content or mechanics you are proposing.

There should be a "developer mode" in settings that essentially allows you to open memory cells/banks and edit or even just view what each variable is.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make it easier to debug logic creations so you don't need to have a whole extra processor reading a variable from a memory cell and printing to a message. That would make it much faster and easier to test each part and variable in your logic.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Or just allow memory cells/banks to be "viewed", as in you can select them, click an eye button where the edit button would be, and see the values inside without being able to modify them.

No need for a special "mode" or privileges, there's no harm in just looking.

**Comment by stuffyAI** [comment]
Well this is actually one of those scenarios where I believe mods, or even better custom builds, are in order, I don't want to load the UI-Elements when starting Mindustry on my phone, this should only apply to people specifically wanting this feature in their game.

**Comment by datlongboi** [comment]
> Well this is actually one of those scenarios where I believe mods, or even better custom builds, are in order, I don't want to load the UI-Elements when starting Mindustry on my phone, this should only apply to people specifically wanting this feature in their game.

I was thinking of this being more of a thing you can enable in settings. It wouldn't be on by default.

**Comment by datlongboi** [comment]
> Or just allow memory cells/banks to be "viewed", as in you can select them, click an eye button where the edit button would be, and see the values inside without being able to modify them. No need for a special "mode" or privileges, there's no harm in just looking.
> 
> However, if you're already familiar with logic, you can already create a logic schematic that outputs the contents to a message or display block.

Maybe you would be able to edit the values in single-player but in multiplayer, you can't edit them and only view them.

**Comment by stuffyAI** [comment]
> I was thinking of this being more of a thing you can enable in settings. It wouldn't be on by default.

So a game restart to refresh what is loaded... It might as well be a mod?
If we only keep it visual for a client you also cannot easily modify entries for debugging and/or testing, but with mods you would be able to do that. Therefore I believe it would be more suiting to be a mod or custom build of Mindustry, it could be so much more than just visuals.
