### ISSUE TITLE
VoteKick limitations and griefers

### ISSUE THREAD

**Issue by Delta190** [Anuken/Mindustry-Suggestions#2766]
### Describe what you would like changed, and why.

The votekicking system, and banning multi-offense griefers, its too much of a problem for servers with few admins and 4/5 matches are ruined completely because one person griefs and one person wont vote

### Describe the changes you want to propose. Include possible alternatives.

It would be great If when somone is kicked/temp banned from multiple servers within a day they should be blocked from joining any server.

But mainly, please lower the vote requirement to 2 people, ive had 40odd matches today and 35 if not all of them had a griefer at some point, atleast 20 of those matches were unplayable bc only me and one other would vote the other teammate wouldnt do anything at all, this is a huge issue for multiplayer users as this has occured thousands of times a day to almost everyone i talk to, please fix cat

**Comment by Kyllingene** [comment]
Explain how a ton of disparate servers are supposed to be forced to cooperate in a very involved fashion. It's like trying to get *every Tesla supercharger* to pull from the same power supply; impossible.

**Comment by itcannotbe** [comment]
DOES ANYONE EVEN READ THE FREAKING DISCLAIMER?

**Comment by itcannotbe** [comment]
Also votekick can be customized by each server owner.

**Comment by OnyxFinger** [comment]
what ? How would you control players in io kicking random players they haven't seen before because there is maybe a griefer while 50% of the time it's either a bad player or a better player ?

**Comment by Kyllingene** [comment]
I'm sorry, but @Delta190, you didn't do the research requisite to open an informed issue; please close this.
