### ISSUE TITLE
wierd idea for the use of constructors

### ISSUE THREAD

**Issue by xenomorphgourmet** [Anuken/Mindustry-Suggestions#2767]
### Describe the content or mechanics you are proposing.

A special launchpad for payloads/ships

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This allows for the creation of extremely high difficulty attack maps and.. yeah i dunno it was just a random thought

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
> yeah i dunno it was just a random thought

It's definitely extremely random and not thought out at all.

**Comment by Kyllingene** [comment]
We appreciate your attempt to contribute to the community, but please, if at any point during the composition process you feel compelled to write "yeah i dunno" or "it was just a random thought," then either stop, think it through, and evaluate your path from there, or if you fail to think of any else, scrap the issue.

**Comment by Bottinator22** [comment]
There's already a payload launchpad sprite in the game images, so it's definitely been planned, not sure if it's actually gonna be added like a typical launchpad tho

**Comment by OnyxFinger** [comment]
other than that, I think that I can't decide myself since I don't correctly understand what you are proposing
