### ISSUE TITLE
Buff shale tile

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2768]
### Describe what you would like changed, and why.

Why shale efficiency for Oil extractor is 100% while dark sand is 150%? Dark sand tiles is much more usefull, cuz 150% and you just build 2x2 drill for sand it's very comfortable. Shale have no sense to use on maps. 

### Describe the changes you want to propose. Include possible alternatives.

Maybe 200% for shale would be too much. Or maybe nerf dark sand to 100% and make shale at 150%? White sand was 100% too before nerf and now 66%, so maybe nerfing dark sand would good too.

**Comment by BlueWolf3682** [comment]
Update to 7.0 build 129. Shale has already been buffed.

**Comment by Kryvytsky** [comment]
Oh. I didn't notice that. It's 160% now.

**Comment by oinkymoo** [comment]
wait it got buffed that much?!

**Comment by Kryvytsky** [comment]
> wait it got buffed that much?!

160%
