### ISSUE TITLE
Drills should accept cryofluid as well as water

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#277]
**Describe the content or mechanics you are proposing.**
I think that all drill types should accept cryofluid, currently drills just accept water, and it gives a really big speed buff. I thinl that water in drills should also be nerfed, and cryofluid in drills should make the drill just a little bit slower then what water currently gives. My idea is water gives something around x1.67, and cryofluid will give the drill x2.56 (this can be whatever, but water should be significantly less powerful)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make drills correspond more properly to everything else that takes in water, all turrets take in water as well as cryofluid, so why shouldn't drills do the same? this should also give cryofluid a bit more of a use. Water in drills is also very powerful right now, and it takes up so little water to cool the drill off, I think cryofluid in drills will make it a bit more difficult to maximize drills, and give an incentive to do it for tasks like making phase fabric.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by KonradGA** [comment]
I think you are thinking wrong, water is not really a coolant to the drill but the drillhead. Therefor you could argue that what you want is another liquid, like a lubricant. Made of say plastic and silicone. Really expensive. But you would not need that much of it. So say a ⅛ of water or something and 1.5 x better than water.

**Comment by ILiekMelons** [comment]
Why would we make another liquid for this one purpose

**Comment by DeltaNedas** [comment]
mix water and oil for cutting fluids
or use cryofluid which already exists

**Comment by TheSliverNickel** [comment]
We could make only laser drills accept cryo as the lasers would need cooling.
