### ISSUE TITLE
Lavanet (the hardest one planet in campaign)

### ISSUE THREAD

**Issue by LmaoPosto** [Anuken/Mindustry-Suggestions#2770]
### Describe the content or mechanics you are proposing.

Lavanet have lava pits and lava rivers
Lavanet have small less water
Lavanet have much titaruim and Thor's, coal,dark sand,oil lakes but copper and lead less
more strong Enemy base in Lavanet
Maybe Lavanet have new resource to research something new
Lavanet is an black planet with many lava
If each sector doesnt have enemy base it's Only 40-70 or 80 waves to successfully caught

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New planet ever hardest one in campaign called Lavanet

if is already planet like this I don't know I didn't see (sorry for bad Grammer)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Is this a story or a bad suggestion, I can't tell the difference.

**Comment by IIINSTINCT** [comment]
This can go into mods kewl but not on vannila 

remember this dude anuke can easily add new planets so people dont need to suggest one

**Comment by Humanoid-X** [comment]
Lavaanet... bad name, sound like an entirely different language frrom "Serpulo" and "Tantros"
Anyway, this is a bad idea..

**Comment by GruveXp2** [comment]
Is this a troll?

**Comment by JrTRinny** [comment]
bruh
you know that we have slag tile, equivalent to the lava
and you can make the map yourself, it isn't hard

and please see Trello.

**Comment by Humanoid-X** [comment]
Doesnt sound like troll, but no.
