### ISSUE TITLE
Fly Toggle Button for Mobile

### ISSUE THREAD

**Issue by Sch1st** [Anuken/Mindustry-Suggestions#2772]
### Describe the content or mechanics you are proposing.

Im suggesting if we can have a toggle button(or any mechanism) in mobile for 'can fly"' units for them to fly... since sometimes I dont want my unit to be flying around, and being blown up by scatters, it can be also toggle off and on in settings if u dont want a button.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Will help mobile players to play more safely...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ChivalricMender** [comment]
There's a mod that does that, and it's multiplayer compatible. I don't think this is very necessary.

**Comment by oinkymoo** [comment]
just because a feature exists in mods doesnt mean it shouldnt be added to the base game. i support this suggestion

**Comment by itcannotbe** [comment]
Here before anyone would say that the ui for mobile is cluttered enough.

**Comment by SMOLKEYS** [comment]
> Here before anyone would say that the ui for mobile is cluttered enough.

how is the mobile ui cluttered

for me its like








































empty

**Comment by itcannotbe** [comment]
> > Here before anyone would say that the ui for mobile is cluttered enough.
> 
> how is the mobile ui cluttered
> 
> for me its like
> 
> empty

Of course, most of the screen for mobile needs to be empty of ui elements, cause  you are reliant on touch controls to move around and place down blocks, select and target certain things.
