### ISSUE TITLE
Outposter unit

### ISSUE THREAD

**Issue by ChivalricMender** [Anuken/Mindustry-Suggestions#2778]
Outposters would be incredibly tanky units that couldn't shoot until deployed on a block. They would walk over blocks (every tier) and deploy itself into an outpost. Each tier would be able to deploy on an enemy block, depending on the block's (or blocks') health. The outpost would, at minimum, repair itself and have a turret on each side. If the unit is commanded to attack, it would deploy near the enemy core.

**Comment by oinkymoo** [comment]
template. what would this add to the game

**Comment by itcannotbe** [comment]
@oinkymoo Blame the gitnub app.

**Comment by JrTRinny** [comment]
that sounds ~~like an impostor~~ not so Mindustry-styled

**Comment by Humanoid-X** [comment]
~~Here before anyone says "Here before anyone says mods"~~

**Comment by ChivalricMender** [comment]
> template. what would this add to the game

It would add a unit for invading parts of enemy territory. Higher tier outposts might have repair points/turrets.

**Comment by OnyxFinger** [comment]
looks interesting, though it's more fitting for a ground route, which there are too many of (to me)
though, the current purple route could become and air route (it's low range makes it unfitting for naval units) and there would be a new purple route for ground.
I like the defensive unit kind of idea

**Comment by oinkymoo** [comment]
> > template. what would this add to the game
> 
> It would add a unit for invading parts of enemy territory. Higher tier outposts might have repair points/turrets.

I have played on io’s attack servers enough that I know you can just build the things, you don’t need a whole unit for this, unless you’re deep behind uncleared enemy lines in which case why are you building back there in the first place

**Comment by OnyxFinger** [comment]
> > > template. what would this add to the game
> > 
> > 
> > It would add a unit for invading parts of enemy territory. Higher tier outposts might have repair points/turrets.
> 
> I have played on io’s attack servers enough that I know you can just build the things, you don’t need a whole unit for this, unless you’re deep behind uncleared enemy lines in which case why are you building back there in the first place

it is way too difficult to place defenses at an efficient speed for a beginner and mostly requires logic for unit transport unless you want want it to be harder
I can see it bring good stuff to PvP, though your point is still right

**Comment by OnyxFinger** [comment]
Also, the T4s and T5s will need something else than this, else it's not even worth spending time on creating them, if not for the game to look slightly more complete

**Comment by GitHubUser-B** [comment]
> Outposters would be incredibly tanky units that couldn't shoot until deployed on a block. They would walk over blocks (every tier) and deploy itself into an outpost. Each tier would be able to deploy on an enemy block, depending on the block's (or blocks') health. The outpost would, at minimum, repair itself and have a turret on each side. If the unit is commanded to attack, it would deploy near the enemy core.

- [x] I'm not gonna roast you with this
