### ISSUE TITLE
Plan block/foundation block

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#2779]
### Describe the content or mechanics you are proposing.

This block you could place to plan out structures and defenses ahead of time, rather than waiting and seeing that it fails WITHOUT having to go into sandbox every few minutes to look at something

**EDIT:** The thing about this ( might not have made that clear) is that you could put these down without the material cost for building it so you can plan ahead

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would help later levels for planning defenses against enemy cores, and it would help for factories with massive production

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
what do you mean by you structure or defense "failing".

also you can just pause building (e by default) to plan out your construction without building it

**Comment by Humanoid-X** [comment]
huh??? pause and e exist??

**Comment by itcannotbe** [comment]
OP: Brain is barely functioning.

**Comment by Real-person1783** [comment]
> what do you mean by you structure or defense "failing".
> 
> also you can just pause building (e by default) to plan out your construction without building it

The thing about this ( might not have made that clear) is that you could put these down without the material cost for building it so you can plan ahead

**Comment by OnyxFinger** [comment]
I guess there could be a simulation system for **paused building queues** ?

**Comment by abrasmag3** [comment]
On PC you can press E to pause building, and on mobile it is paused until you press the check mark. This isn't needed

**Comment by OnyxFinger** [comment]
> On PC you can press E to pause building, and on mobile it is paused until you press the check mark. This isn't needed

but there is no simulation during this moment
