### ISSUE TITLE
Buff crawlers

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#278]
**Describe what you would like changed, and why.**
Currently Crawler spam is practical along with fortress spam, but in general it's very weak and doesn't do much damage, crawlers are too weak to get near the wall most of the time, and they never reach a "critical mass" like other units do when the amount is totally overhwhelming. I've played with over 2000 crawlers in PvP and still lost to lancer defenses due to lancer instakilling them.

**Describe the changes you want to propose. Include possible alternatives.**
Crawlers just need an overall buff, primarily towards it's health, currently lancer instantly kills a crawler, and a 3 cyclones can keep any number away, crawler should be buffed to have a health that is above a Dagger, though less then a Titan or a Fortress. Especially with the new 6.0 unit system, and them losing 2x2 block size they should get a definite health buff. The other thing is damage buff, crawler should do a bit more damage then it currently does, maybe around 150-250, and do it in a bigger radius, this will make them much more effective at overwhelming enemies. Another big thing is that I think crawler should avoid enemy conveyors and instead go over them, one of the problems in PvP right now is Crawler walks straight into enemy conveyors, and it can basically stop any number of crawlers dead in their tracks on larger maps, due to the whole army hitting all conveyors. With all of this it should make them a more practical unit to use in general for it's proper purpose.

**Comment by itcannotbe** [comment]
If you are keeping up with updates in discord.

Crawlers have different priorities now. It's not just the core/obstructions.

It's not something like the nearest block along the paths or something.

**Comment by Syncinus** [comment]
That's not the only thing I said, I showed what they needed to be generally buffed, even with that I bet they are still very weak.

**Comment by itcannotbe** [comment]
Of course. What do you thinkk suicide units are? Tanks?

**Comment by Syncinus** [comment]
Yes, but they should be able to get to their destination. They are stopped too easy right now, and a swarm of them is really ineffective against anything. There is no way to get enough crawlers to garuntee overrunning the enemy.

**Comment by stuffyAI** [comment]
If you are eager you can test the current 6.0 build how they fair, you can build them early and cheap and later one they will get upgraded anyway, you're not using duos after wave 50 either so let's keep them early game.

**Comment by Syncinus** [comment]
Okay so crawler spam doesn't matter in 6.0
