### ISSUE TITLE
More blocks that utilize direct player control

### ISSUE THREAD

**Issue by BenMan95** [Anuken/Mindustry-Suggestions#2780]
### Describe the content or mechanics you are proposing.

Add more blocks that make use of the direct player control mechanic.

Some ideas:
1) Construction point
    - A block that when directly controlled, would allow the player to build slowly in a region around it
    - Might be an interesting way to allow players to quickly perform emergency maintenance on key areas
2) Stronger turrets that would only be usable when directly player controlled
    - Might be interesting on maps with multiple enemy spawn locations

Feel free to come up with other ideas

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, direct block control is an extremely under-utilized mechanic. Unless there are some that I'm missing, the only blocks that can currently be directly controlled are routers and turrets. There is almost no reason to directly control either, as unlike with units, it is almost always more useful to let them be controlled by the AI. In its current state, the mechanic might as well be nonexistent.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
router control is mostly just a meme that was never meant to be actually useful. also many turrets can shoot farther than their range would suggest (spectres in v6 being one of the more notable ones) which means that you can actually outrange a foreshadow with a player-controlled foreshadow

**Comment by MrDuck557** [comment]
Fact: turrets will pause for a bit when their target is destroyed
Player control doesn't have this
But it's only notable when the turret is god-boosted

**Comment by Real-person1783** [comment]
This would be cool in some missions, like you have a super weapon that is defending your core that only you can control

**Comment by OnyxFinger** [comment]
very very weird in an automation based game, but can be let's say an unnecessary building that would have useful micro potential when you're in a hard map ?

**Comment by OnyxFinger** [comment]
> router control is mostly just a meme that was never meant to be actually useful. also many turrets can shoot farther than their range would suggest (spectres in v6 being one of the more notable ones) which means that you can actually outrange a foreshadow with a player-controlled foreshadow

but with logic too
I think he means player only control, also overshoot is getting removed

**Comment by OnyxFinger** [comment]
maybe a sort of shard thrower, that would act like a bloons TD tack shooter but only when interact with it ? (like the scrap using thingy in the example mod in v5) ?
or some better mender that would have a cool ability that you activate yourself when you really need it ?

**Comment by oinkymoo** [comment]
> > router control is mostly just a meme that was never meant to be actually useful. also many turrets can shoot farther than their range would suggest (spectres in v6 being one of the more notable ones) which means that you can actually outrange a foreshadow with a player-controlled foreshadow
> 
> but with logic too
> I think he means player only control, also overshoot is getting removed

Ik specter overshoot is getting bonked but just about every turret has at least a block or 2

**Comment by OnyxFinger** [comment]
> > > router control is mostly just a meme that was never meant to be actually useful. also many turrets can shoot farther than their range would suggest (spectres in v6 being one of the more notable ones) which means that you can actually outrange a foreshadow with a player-controlled foreshadow
> > 
> > 
> > but with logic too
> > I think he means player only control, also overshoot is getting removed
> 
> Ik specter overshoot is getting bonked but just about every turret has at least a block or 2

yes, I see what you mean
