### ISSUE TITLE
[logic] more logic command

### ISSUE THREAD

**Issue by lokyinng** [Anuken/Mindustry-Suggestions#2784]
### Describe the content or mechanics you are proposing.

sensor:
@kills; the amount of enemies defeated by that unit/turret
@print read the massage in massage block
@speed how fast of the unit
radar:
target block; target any blocks [target any can't target block]
target core; only target core
target turret; only target turret
target dead; only target dead unit
u radar:
target dead; only target dead unit
u locate:
group logic; locate any logic-based block

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

give the logic programmers more things to do
@print in sensor can make password door
target dead in radar will make turret/unit shoot at dead unit
Etc.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> @kills; the amount of enemies defeated by that unit/turret

this actually sounds interesting but

how do you do that

> @print the massage in massage block

sounds very unnecessary

> @speed how fast of the unit

~~speed proximity thorract mines~~
~~move too fast and you get blown to shreds~~

**Comment by Humanoid-X** [comment]
for speed i think you can already calculate yourself with a timer...

**Comment by lokyinng** [comment]
> > @kills; the amount of enemies defeated by that unit/turret
> 
> this actually sounds interesting but
> 
> how do you do that
> 

use with the massage

> > @speed how fast of the unit
> 
> ~speed proximity thorract mines~
> ~move too fast and you get blown to shreds~

that never gonna work in most case

**Comment by itcannotbe** [comment]
> massage in massage block

Can mindustry massage people in real life?

**Comment by lokyinng** [comment]
> > massage in massage block
> 
> Can mindustry massage people in real life?

no mindustry is not discord or massager

**Comment by oinkymoo** [comment]
is the speed sensor detecting the current speed or the top speed?

**Comment by lokyinng** [comment]
> is the speed sensor detecting the current speed or the top speed?

current speed
