### ISSUE TITLE
Biological threats and a new unit branch and/or more turrets

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#2785]
### Describe the content or mechanics you are proposing.

You could add a new faction/group of enemies that will show up on certain levels. They would pose additional threat and would have their own strengths and weaknesses. Such as (for example) they are extremely vulnerable to fire and explosives, but they don’t take as much damage from bullets. Something like this could completely change player strategies. 
im thinking that they could spawn in a certain radius around like a plant hive or a central cluster, and have more erratic spawns, from around 1.25-2.5 minutes for a wave. You could also have have the hive things spread over time, meaning you would have yo balance production, defense, pruning the plants

For the new unit, There should be something similar to the mace or crawler. In my experience, flamethrowers get overshadowed by later turrets and units, and I feel they should get more love because they are awesome. You could do Splash weapons, more flamethrower types, mabye even like a fireball  blaster. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would add a whole new side to the game. While managing the enemies that come from a single spot, you could have these things which have far more variability which would add chaos to some of the later levels. The new units should be practically required to take them out, needing you to produce pyrite, oil, and blast compound to make them, and having while also giving some of the more obscure items more use

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Real-person1783** [comment]
There are lots of possibilities for this. You could harvest the plants for organic matter, grow them in a greenhouse, and use them for many things, meaning that you don’t want to destroy them, so it becomes a balancing act to harvest them, keep them at bay, and also get valuable resources

**Comment by Humanoid-X** [comment]
for @speed i think you can already calculate it yourself... with a timer...

**Comment by Humanoid-X** [comment]
Also, the guy named @speed got a lot of ping here

**Comment by Humanoid-X** [comment]
Wait shit wrong issue :p

**Comment by Real-person1783** [comment]
No problem

**Comment by Real-person1783** [comment]
I just got so confused though

**Comment by Humanoid-X** [comment]
I dunno but I feel like this doent suit the game's theme...

**Comment by Real-person1783** [comment]
> I dunno but I feel like this doent suit the game's theme...

I know, this was one of the main problems I was having when I was trying to flesh out the idea, which is why there is a random  comment. I think this is a good idea but mabye it shouldn’t be implemented in campaign or it might be a planet, but yeah… I feel you

**Comment by OnyxFinger** [comment]
maybe maces/scorches could deal more damage to biological units ?

**Comment by 50275** [comment]
whatever poor person that has to fight these has to either get more guns or more menders; mindustry is all about keeping the enemy away from you as you plink it to death, not force a short range encounter and die (also, you can't afford to do this given that units like the reign have pierce)

**Comment by OnyxFinger** [comment]
> whatever poor person that has to fight these has to either get more guns or more menders; mindustry is all about keeping the enemy away from you as you plink it to death, not force a short range encounter and die (also, you can't afford to do this given that units like the reign have pierce)

what
defense does not work that way, and melee is only desadvantaged because of bad balance
