### ISSUE TITLE
See trade routes on planet map

### ISSUE THREAD

**Issue by Awol-x** [Anuken/Mindustry-Suggestions#2787]
### Describe the content or mechanics you are proposing.

I think it would be very helpful during the campaign to see at-a-glance which sectors are trading with which sectors. I now see that this is in the Trello under Campaign>Display Export Lines. Below are markups for my suggestions. 

There could be a list under the sector name when you select a sector:
![Export3](https://user-images.githubusercontent.com/88296493/127884367-eba95e90-78db-4285-8864-7131c281e478.PNG)
I think this would be the easiest to implement and looks the best.

There could be animated lines that come up when you select a sector, perhaps with the icons of each resource being transferred:
![Export2](https://user-images.githubusercontent.com/88296493/127886404-4b2b4f3f-f25c-443d-b06a-b75477c15fa2.PNG)

It could also be under the stats tab :
![Export1](https://user-images.githubusercontent.com/88296493/127791670-7df6ca77-f2d2-449a-99fe-f15abde59a50.PNG)

Please excuse my sub-par MSPaint skills.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be easier to see how your exports are running without having to go to each sector.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Awol-x** [comment]
> ### Describe the content or mechanics you are proposing.
> I think it would be very helpful during the campaign to see at-a-glance the trade routes to and from other sectors.
> 
> It could be under the stats tab
> ![Export1](https://user-images.githubusercontent.com/88296493/127791670-7df6ca77-f2d2-449a-99fe-f15abde59a50.PNG)
> It could be an animated line, perhaps with the icons of each resource being exported
> ![Export2](https://user-images.githubusercontent.com/88296493/127791668-9ccd16a9-cad0-4fd8-9f19-c3a9a6c90dd9.PNG)
> It could be a small box when you select the planet
> ![Export3](https://user-images.githubusercontent.com/88296493/127791743-cbd34471-ad70-4818-bc8c-aba3448c4052.PNG)
> 
> I feel the third screenshot is the best and simplest. 
>
>Please excuse my MSPaint skills.
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> It would be easier to see trade routes without having to go to each sector.
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
the export lines on the world map could be always active, like the vulnerability indicator lines, or only active when a relevant sector is selected

**Comment by JrTRinny** [comment]
see latest BE, Anuke just implemented it :D
