### ISSUE TITLE
Meltdown and Foreshadow are the worst 4x4 turrets in game and I will use mathematics and processors to prove it 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2788]
### Describe what you would like changed, and why.

!!!Attention!!!There will be a lot of text!!!

At first I wanted to prove, why Meltdown need a buff, but in process of testing 4x4 turrets I find out unexpected things about Foreshadow.
Let's starts at simple: liquid consumption.
Spectre consume 60/sec while shooting as it say description. Meltdown use 30/sec, but it consume liquid after shooting period. It consume 225 water for 7,5 sec while cooldown period and 100 cryofluid for 3,3 sec. And Foreshadow here is very weird. It consume 60 liquid per second, same as Spectre. If you will try to use processor to make them shooting at same time they'll empty the liquid tanks at the same time. So what is wrong? Guess, how much it consume per one shot? About 1100-500 water for 16-8 sec or 500-220 cryofluid for 8-4 sec! For some reason Foreshadow continue to consume liquids even after reload time 3 sec. Amount and time of consumption depends on turret rotation angle. Yep, if turret move for 90° it will consume 700 water or if it 180° then 1000. And this consumption tested on turrets controlled by processor, but if turrets will be controlled by player, than it always would consume 1000 water and 500 cryo.
So, next one talk about turrets damage. All 3 turrets was tested on Reign. All turrets work on cryofluid and boosted by overdrive 225%.
What I find out first time. Time required to destroy Raign: Spectre 12 sec, Meltdown 90~100 sec and Foreshadow 30 sec. At first look we can see, that Meltdown is weakest turrets for single target damage. Time to calculate theoretical damage. Reign have 24000 hp / 12 = 2000 Spectre's damage. Now use description and make calculation 8,57×1,45×2,25×80≈2200 dps. Spectre seems okay. 
Let's go to Meltdown. Remember that shooting period is only half of cycle. 3,5+3,3=6,8. 3,5/6,8=0,5147 so true shooting time is 90×0,5147≈46. And it's damage should be 24000/46≈522 dps. And things went weird here. What is true damage of Meltdown? I use processor to count a damage and this what I got. Meltdown deal ~1700 damage per 3,5 sec of shooting period. It's just 485 dps instead of 840 in description. It should be around 2900 damage, not 1700. And I also testing Meltdown together with Tsunami. Water have no effect. Cryofluid boost damage to 2000 for some reason. Slag just do some damage. Oil is do massive damage, if use 1 Oil Tsunami, than Meltdown destroy Raign for 24 sec, if 2 Tsunami - 14 sec. Oil for some reason do abnormal amount of damage, you can just spam Slag + Oil Tsunamis and watch how world is burning.
And finaly Foreshadow. It take 30 sec to Reign, so 24000/30=800 dps. Damn. I was confused by this, suz it's fire rate is 0,3x1,36x2,25=0,918 and dps = 1350*0,918=1239. And so I use processor to understand damage and you know what is true damage of Foreshadow? 890!!! It need a 27 shots to get Reign. I didn't believe it the first time, so I tested this on different units, it's still 890 damage. Tired of tests I went on Youtube for Foreshadow footage. I find  D.A.R.K video. 
https://youtu.be/vORLNQNqzGQ
On 25 sec we see that Foreshadow need 8 shots to destroy Atumbra 890×8=7120 and Atumbra have 7000 hp. On 1:15 we can see footage of Reign vs 3 Foreshadows and they did 26 shots but not destroy Reign because 26×890=23140. This turret was broken since release.

### Describe the changes you want to propose. Include possible alternatives.

This suggestion should be a list of possible buffs for Meltdown, like: increase shooting time by 1-2 sec if it work on cryofluid, increase range to 28, just like Eclipse. Spectre just outstand in every way, it have more range, more damage, you can say that Melt is good at huge number of enemies, but it's not V5 where Spectre was a single target turret, now in V7 it can deal 2000 dps and penetrate multiple targets. I think this Meltdown is really in poor state right now. But it seems I find out more important issues that need to be resolved

**Comment by Kryvytsky** [comment]
This is MeltdownDamageTest schematic
bXNjaAF4nGNgYeBgZmDJS8xNZeD3Tc0pSckvz3PJTQ9JLS5h4E5JLU4uyiwoyczPY2BgYMtJTErNKWZgio5lZeDPqCxILdItKMpPTi0uzi9i4CnILwcKFOeXFiWnMnDkQs1i4M3JLCzNTIFJsOcClSempwLNY2VgYGRg5AOyFlfM8e035DtkwOMafITBstW/4cWFvc78Bw6wBl31dewUPtopEP4kRIU3RFbnp/3v+pu9Ao8Oe7xhunNgUefk6kDuvfx+7CnTHH21GIRumWus2rrAqPDm2u0GJ9I3yVkZ3CyJF3m64/XSyfvfHDzEUPvVc0nm46rjc9n9ktPK7l5nPXNsbdneR4G/PiyIKHmbNnmHzKE1JtuM6osFlu8X8Q17/vaUjU0dY0GK9z1mRqBDmTkYmJmArmZlYGYGUsysLEAGCwMTAzML0CsGzAC7t3Zy

**Comment by Kryvytsky** [comment]
This is ForeshadowDamageTest schem
bXNjaAF4nGNgYeBgZmDJS8xNZRB0yy9KLc5ITMkvd8lND0ktLmHgTkktTi7KLCjJzM9jYGBgy0lMSs0pZmCKjmVn4CnIL08t0i3OLy1KTmXgzixJzYVxuNLgJjHwZ1QWAJUVFOUnpxYX5xcx8OZkFpZmpsA15qbm5hdV6ian5uQwsOcC1SSmpwLtYgdiBiYORgZGBmZmRiCbmZWBgYeZCchnBYowABl8QNE1FXNS+xm5mg14XBffTiiZfoLTTdv6wLpJZ3dwbZ26TWn327xHi4xE2Dhb9vyv92BkmO9h6ppy/q70yfW5M2O23Wg5cTJI1q2ZLVUuJkx5q+TXqytOhCzeaGt307K5SrmzlkuQda3cnvWNWl9u7FDoaPEMNV9bvs9w20zxb+Ka50xsNgiZFVuu/nXjl02+2dVNWXcm6JTNEdp7Q+PnR4bpd7Uvs7hb6Iq3TC3457mw4RP32YWhAcwsIN+wsgDdzwr0ADMDMxuIYAF60oAZAOxMgqM=

**Comment by itcannotbe** [comment]
Armor be like:
![Faceplate](https://c.tenor.com/eaWfi0NkOIIAAAAM/harry-potter-daniel-radcliffe.gif)

**Comment by JrTRinny** [comment]
it's still 1350.
in the picture, damage is displayed as 1336, as Reign has 14 armor, 1336 + 14 = 1350 
debunked, still the same, never changed

![debunk](https://user-images.githubusercontent.com/85090668/127888657-313f9cf1-fae7-489b-aab2-2818770cc0dc.jpg)

**Comment by Kryvytsky** [comment]
I get it. Guardians have damage reduction

**Comment by itcannotbe** [comment]
> Guardians have damage reduction

They don't, what they have is [redacted](https://github.com/Anuken/Mindustry/blob/41964cd13080ef45db5165f45a3a503e1cf67e98/core/src/mindustry/content/StatusEffects.java#L169)

**Comment by oinkymoo** [comment]
there's also range to consider. how much damage will a foreshadow do to an eclipse that starts 100 blocks above the foreshadow then charges straight down without firing until outside the foreshadow's range or dead. what about a meltdown? or a spectre? also the reason that meltdown synergizes with oil and not water is because meltdown lasers are burning lasers, not electric arcs

**Comment by OnyxFinger** [comment]
meltdowns are bad but not foreshadows.
