### ISSUE TITLE
Map Browser 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2789]
### Describe the content or mechanics you are proposing.

Same as Mod Browser.
Also maybe it should have filters: survival, sandbox, attack. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's dificult to find a worth map to play. Especially in Discord. Only place where rating map system exist is Steam workshop.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Discord isn't as customizable as something you actually bloody code for.

So a system that filters files on demand won't be feasible for discord.

**Comment by Kryvytsky** [comment]
Ok. Even without filters it would be nice to gradation maps somehow. Most of them are bad designed or just a joke.

**Comment by 50275** [comment]
find one map creator like Sharlotte and start from there
