### ISSUE TITLE
I want Mindustry to have counter-part of Pyratite

### ISSUE THREAD

**Issue by Quan-Billy** [Anuken/Mindustry-Suggestions#279]
**Describe what you would like changed, and why.**
I want Pyratite to have a "cold" counter-part(Maybe it should be named Cyratite or Cryotite)

**Describe the changes you want to propose. Include possible alternatives.**
It will add more variety to the game, just like Slag and Cryofluid work with Waves.
I have notice that we have Surge Alloy added lightning ability and Blast Compound added explosive ability so, add another resources to add ice ability is very cool!

**Before making this issue, replace the spaces in the following boxes with an X to confirm that you have acknowledged them. Fai0lure to do so may result in your request being closed automatically.**
1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
cryofluid.

**Comment by Quan-Billy** [comment]
> cryofluid.

Have you read the whole thing?

**Comment by potatoisagender** [comment]
seriously. I don't know what is different between your idea and cryofluid. Sure, there are special effects like shock and explosive, but  the 'ice ability' is literally the same thing as a cryo wave spraying enemies.

**Comment by itcannotbe** [comment]
So you want an item version of cryofluid?

**Comment by potatoisagender** [comment]
that seems really redundant...

**Comment by Violet-Scarelli** [comment]
I would agree that it seems a little redundant, but I can see where it would be useful. Ice shells for the Ripple, freeze bullets for the Spectre, etc. It makes sense to me. Maybe feeding this hypothetical "cryothite" to separators would increase their efficiency?

**Comment by l-Luna** [comment]
have a factory that consumes cryofluid and graphite to produce a stable, solid cryofluid compound, I guess? though I don't see how necessary this is overall.
