### ISSUE TITLE
1x1 Container for ammo.

### ISSUE THREAD

**Issue by kcat36** [Anuken/Mindustry-Suggestions#2790]
### Describe the content or mechanics you are proposing.

**A smaller 1x1 container for ammo**

maybe _50_ _titanium_ and hold _100_ items or so?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

lets say i have a backup For one turret or a small group that i want to keep closer to the core and compact but still stocked with a bit of ammo, 300 items is a bit much for small group of turrets since most dont allow holding much ammo anyway.

a smaller version would be easier to protect and would be useful for a compact system for units that get past a main defense.

Could also be a pre titanium item if you want.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ah yes, something that cost so cheap and  can hold 100* x items.

You can literally fit 1200 items in it considering there are 12 items in the base game.

Also 4 of them already exceed a container.

Plus can't you make room for a bloody 2x2 container?

**Comment by kcat36** [comment]
> Ah yes, something that cost so cheap and can hold 100* x items.
> 
> You can literally fit 1200 items in it considering there are 12 items in the base game.
> 
> Also 4 of them already exceed a container.
> 
> Plus can't you make room for a bloody 2x2 container?

Cheap yes but the normal container is only 100 titanium

Also fit 1.2k in what the normal container? it holds 300.

4 of theme exceed a container but would also cost 2x the amount and would have to be unloaded from each one.

I could make room but the whole point is to be compact.

**Comment by IIINSTINCT** [comment]
Basically Junction/bridge Conveyor but improved version

**Comment by Bottinator22** [comment]
> > Ah yes, something that cost so cheap and can hold 100* x items.
> > You can literally fit 1200 items in it considering there are 12 items in the base game.
> > Also 4 of them already exceed a container.
> > Plus can't you make room for a bloody 2x2 container?
> 
> Cheap yes but the normal container is only 100 titanium
> 
> Also fit 1.2k in what the normal container? it holds 300.
> 
> 4 of theme exceed a container but would also cost 2x the amount and would have to be unloaded from each one.
> 
> I could make room but the whole point is to be compact.

You completely misunderstood what he meant with 1.2k. The item capacity of a container is per-item, so you can have 300 copper and 300 lead in a single normal container.

**Comment by SMOLKEYS** [comment]
Vaults hold 1000 of each item.

Cores hold 4000(T1)/9000(T2)/13000(T3) of each item.

Containers hold 300 of each item.

**Comment by itcannotbe** [comment]
LOL 4 items slipped past my mind when writing that reply. LOL

**Comment by 50275** [comment]
All the other blocks that can be unloaded from are at least 2x2. Why should this be different?
