### ISSUE TITLE
old stuff

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2791]
### Describe the content or mechanics you are proposing.

Graphic setting to turn off outline of unit
game4 sound track(?)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

nothing new, but a few v5 player still want to having old stuff

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheRealIvyX** [comment]
> a few v5 player still want to having old stuff

then just play v5

**Comment by Humanoid-X** [comment]
play v5 lmao
simple question requires simple solution

**Comment by Bottinator22** [comment]
but how do you play v5
explain, isn't obvious to me

**Comment by TheRealIvyX** [comment]
> but how do you play v5

by downloading it

**Comment by Bottinator22** [comment]
And where do you download it

**Comment by Humanoid-X** [comment]
github.com/Anuken/Mindustry/releases

**Comment by Humanoid-X** [comment]
@Bottinator22
[HERE, Latest v5](github.com/Anuken/Mindustry/releases/tag/v104.6)

**Comment by Humanoid-X** [comment]
Hmm somehow the link wont work

github.com/Anuken/Mindustry/releases/tag/v104.6

**Comment by Humanoid-X** [comment]
@Bottinator22 

> And where do you download it

[HERE](github.com/Anuken/Mindustry/releases/tag/v104.6)

**Comment by OnyxFinger** [comment]
> > a few v5 player still want to having old stuff
> 
> then just play v5

yes but no
because v5 has much different mechanics, here he only asked for the old game4 (fair, it was good) and a way of removing the unit borderline (also fair, it annoys me sometimes)

**Comment by GitHubUser-B** [comment]
> @Bottinator22
> 
> > And where do you download it
> 
> [HERE](https://www.github.com/Anuken/Mindustry/releases/tag/v104.6)

Hey humanoid, please, can you send me the beta test of mindustry mobile?
