### ISSUE TITLE
Ban specific units (map setting)

### ISSUE THREAD

**Issue by MisterTwist828** [Anuken/Mindustry-Suggestions#2792]
### Describe the content or mechanics you are proposing.

Add a way to ban specific units on a map.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be nice because you could for example: ban all air units except mono (for resources) but you dont want people to use other air units so you can ban them. that would be cool

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by wdmvv** [comment]
wasn't there same pr?

**Comment by wdmvv** [comment]
yes, there were 2: #2363 and #2328
