### ISSUE TITLE
Better Builder and repair unit AI

### ISSUE THREAD

**Issue by NovaStar123** [Anuken/Mindustry-Suggestions#2794]
### Describe the content or mechanics you are proposing.

When Repair/Builder units are damaged and  idle, then they should approach the closest repair point and wait for them to be fully healed (this shouldn't be too hard to immplement)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It is very irritating for repair and rebuilder units to die because they never repaired themselves, and it causes resources to be wasted

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
This would do well for megas, since polys have a healing field already.

Also, other alternative is logic.

**Comment by NovaStar123** [comment]
maybe polies and megas could also mine materials that are low in the core when idle too

**Comment by OnyxFinger** [comment]
wow noone said "logic" ?
the reactions on discord said it tho
I agree with your idea, the current support AIs are dumb lol

**Comment by CoalRock8642** [comment]
Mega - heals buildings, so better in swarms. Right now there building speed is slow, can ask for buff for making it major building bot.

Poly - can be used as alternative for monos under low unit cap. Poly can do there job. This can be more like logic instead of changes from source code.

Quad - IDK, but who uses payloads. but the boi can drop a 3x3 turret in case of emergency. Should have ability to mine thorium.
