### ISSUE TITLE
Oct Repair Turrets

### ISSUE THREAD

**Issue by NovaStar123** [Anuken/Mindustry-Suggestions#2795]
### Describe the content or mechanics you are proposing.

Instead of oct's repair field ability, It should have mounted repair turrets similar to support naval units, which look better and maybe oct could have segment turrets too

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make the oct look more like a support unit, instead of a flying shielder

somethung similar to this:
![image](https://user-images.githubusercontent.com/88464067/128369624-ddd8649f-6fff-4231-a916-7c563d0119be.png)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RouterChainsSuckk** [comment]
what about polys

**Comment by OnyxFinger** [comment]
the repairing of units will be different (a single unit is targeted, but probably repaired faster to make up for it, vs the current AOE heal)
tbh I'm fine with both

**Comment by Hexrotor** [comment]
but how it self-repair?

**Comment by RealYeet** [comment]
*Get another Oct*

**Comment by Hexrotor** [comment]
> _Get another Oct_

Oh no... I dont wanna this
