### ISSUE TITLE
Units easier killing procedure

### ISSUE THREAD

**Issue by IAmFeder** [Anuken/Mindustry-Suggestions#2797]
### Describe the content or mechanics you are proposing.

An easier way to kill your units when you don't need them (single player only, cause in multi-player could cause major griefing) 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Whenever i test units in sandbox, i always end up with a stack of units somewhere that ruins my FPS and what i try to do.
It takes a lot of time to push units into the termination area near enemy spawn.
So maybe a way to kill your units faster should come in handy in such situations. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i've found thorium nukes to be highly effective

**Comment by NovaStar123** [comment]
anuken will add payload dissasemblers which you can use

**Comment by Humanoid-X** [comment]
Single player only right? Mod.

**Comment by 50275** [comment]
drown all of your land units, explode all of your air units with oil tanks + slag combinations; it's slow, but it worked in v5

**Comment by GitHubUser-B** [comment]
> Single player only right? Mod.

My new photo is relatable to you
