### ISSUE TITLE
Team Identification 

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#2799]
### Describe what you would like changed, and why.

Use the new sharded, derelict, and crux team symbols to identify what team a block is on instead of that small strip of color at the bottom right corner of a block. (Yes, I do know that this will also require the creation of blue, purple, and green team symbols)

### Describe the changes you want to propose. Include possible alternatives.

It only makes sense.

**Comment by itcannotbe** [comment]
It doesn't. A triangle of color is more noticable than an icon that most of the time you need to zoom in on to know what it is.

**Comment by RealYeet** [comment]
Hmmm
Maybe it can be a setting or something?

**Comment by J-VdS** [comment]
Nope stuff as a setting isn't a good idea. Anuke had mentioned that he isn't a fan of "settings" or optional stuff.

**Comment by RealYeet** [comment]
No point keeping this open, Anuke didn’t implement it
