### ISSUE TITLE
Custom win conditions in the map editor

### ISSUE THREAD

**Issue by SupremeTurtle** [Anuken/Mindustry-Suggestions#280]
### Custom win conditions in the map editor
Example:

- Reach Wave 75 to win
- Get 10k copper to win
- Destroy Vault to win
- Kill 3 Fortresses to win

This can add more variety to maps, give way to map ideas limited to current features, and survival doesn't have to be endless now. 

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
plugin

**Comment by NoobsDudes20** [comment]
It's probably a plugin but it's cool for the main game.

**Comment by SupremeTurtle** [comment]
Even if there is a plugin I still think it would be nice to have this included in future updates.

**Comment by Evanevoyo** [comment]
@Gwapowo just make custom wave conditions by using world processors to detect once a condition is completed, set the wave to the last wave and if it doesn't auto complete then make it start the wave and spawn hundreds of thorium reactors
