### ISSUE TITLE
About banned units

### ISSUE THREAD

**Issue by FreezeCactus** [Anuken/Mindustry-Suggestions#2800]
### Describe what you would like changed, and why.

Recently we saw a preview of banning certain units on maps, but i noticed one problem. The preview shows that you can't upgrade Crawler to Atrax. But can't we see this before making reconstructors? It would be just a waste of resourses if you build ground factory just to see that all ground units are banned. Or if you build tetrative reconstructor and put, for example, Vela there, but Corvus is banned and you just have Vela now which you don't actually need.

### Describe the changes you want to propose. Include possible alternatives.

We need a way to see which units are banned on a certain map without building factories and reconstructors. Honestly i don't know how can it be done. Maybe you should press some button, maybe it will be shown in pause menu.

**Comment by BorisA11** [comment]
Agreed. Maybe have a screen showing all rules after landing? Like, banned blocks, units, and general speed and multiplier rules.

**Comment by Nils101** [comment]
Putting it in the core database doesn't sound like a bad idea, just like how you can see what affinities are on a map for a specific factory building.

**Comment by IIINSTINCT** [comment]
Time to close this issue

**Comment by RealYeet** [comment]
Let me get one thing straight, we can ban individual units and not ban the entire tree, for example, we can make it so that we have flares but no horizons and then we can have zenith?

**Comment by FreezeCactus** [comment]
> Let me get one thing straight, we can ban individual units and not ban the entire tree, for example, we can make it so that we have flares but no horizons and then we can have zenith?

technically yes, but how are you going to get zenith without making horizons? if you ban one unit, you can't move on to the next one.

**Comment by Yell245** [comment]
> > Let me get one thing straight, we can ban individual units and not ban the entire tree, for example, we can make it so that we have flares but no horizons and then we can have zenith?
> 
> technically yes, but how are you going to get zenith without making horizons? if you ban one unit, you can't move on to the next one.

Maybe it could be reconstructed, but not come out?

**Comment by RealYeet** [comment]
That is what I was thinking
