### ISSUE TITLE
More "dramatic" deaths

### ISSUE THREAD

**Issue by FreezeCactus** [Anuken/Mindustry-Suggestions#2801]
### Describe the content or mechanics you are proposing.

When high tier units die, they just go BOOM. Big explosions are cool, but what if we make big bois' deaths look better? For example, Toxopid. Look at his long legs, he should be really tall, so what if he'll fall on the ground like air units when he dies? And then, of course, big explosion. Corvus. He must hold a lot of energy inside himself, so on death it all can be released with big green explosion? Maybe some lightnings, similar to Arc's shooting but also green. I don't actually have ideas for other units, but maybe others will come up with something.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will just look nice i guess.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
⋅⋅⋅ is my statement

**Comment by Red0Sky** [comment]
maybe sence the omura is on water the death of omura can splash water all around
id like it to be the same for all naval units, but smaller depending on the size, same for retusa, oxynoe, cyernce, agires, and navanax

**Comment by RzBuddy** [comment]
Oct: explosion with dust particles, alongside explosions of whatever it is carrying
Omura: slowly sinks and occasionally spews out a flare or two
Reign: ?
Corvus: same as proposed
Toxo: purple lazer explosions radiating from the main body (same projectile as the "fuse" mounted on the unit)
Eclipse: ?
t5 support naval: slowly sinks, a single large (but less effective) emp projectile radiating from the ship.
just a suggestion

**Comment by Yell245** [comment]
How about reign just falls like an elephant?

**Comment by SaltyBeggar** [comment]
cool idea

would be a nice touch
