### ISSUE TITLE
Spectre ammo rebalance

### ISSUE THREAD

**Issue by Nils101** [Anuken/Mindustry-Suggestions#2803]
### Describe what you would like changed, and why.

A change to non-thorium ammo types for the spectre. (Pyratite and graphite)

I should start of by explaining the current ammo situation for the spectre:
-Thorium dominates everything
-theres little to no reason to use the other options, only in very specific situations like a pre-built spectre on the map with no thorium in miles, not even in the core.
-Graphite is just way to weak and pyra is hard to produce. You need a factory building and 3 different materials, for poor ammo multiplier and damage.

This has been known for a while, but instead of just buffing the damage I put a lot of thought into how you could make the different ammo types more interesting.

So here are my goals with this suggestion: Thorium ammo should remain the "standart" ammo by having the highest dps *but* other options shouldn't be awful and should be useful substitute ammo in some situations by not being worse than thorium in every possible way.

Graphite: 
cheap, low dps
slow firerate but high damage
Good ammo efficiency
Knockback

Pyratite:
Good combination of dps and ammo multiplier, but pricey to make.

Thorium:
Highest dps

Graph: generally worse than other 2 options, but with some attributes that could make it useful in some situations
Pyra: should perform similar to thorium, as it's hard to produce. You can't just slap down a drill  and call it a day.
Thor: the highest dps makes sure that it will remain the "standart" ammo, thus the balance of the spectre as a whole will barely change.

A bit more information as to why:

Graphite has an interesting attribute when shot by duo and salvo, it has slow fire rate but the bullets hit hard. I would love to see this attribute also applying to spectre, as it adds strategic depth to the game.
They do a better job against armored enemies, and point defences work well against the heavy hitting graph bullets when they struggle against normal spectres.
Will this put them on the defensive side?
What about Oxynoe?
It's not hard to see that this change adds a lot of depth to the spectre and that's good for a strategy game like mindustry.

Unlike thor and pyra ammo the graph doesn't pierce, the kinetic energy of the bullet gets fully transfered to the unit. This and the low firerrate but high damage of graph bullets makes some knockback not unreasonable.

Pyratite as mentioned is much harder to obtain, that's why it's not ok for it to be this weak, tho it shouldn't deal more damage than thor either. A combo of higher ammo mult and dmg is a nice solution here.

Imagine a map gave you a spectre, a little thorium ore, a decent sized coal ore patch and the resources for pyratite.
Right now, players would always go for the thorium, the other options are invisible to the playerbase, for the reasons stated above.
In an ideal world, all options could be used, depending on the situation. Maybe you desperately need thorium, the other two ammo types are a useful option.
Coal and thor is low, why not use the coal for pyra?
Maybe all you care about is keeping a blast loaded antumbra as far away as possible, well, those graph bullets got some knockback now
This only works when you get the numbers right.

### Describe the changes you want to propose. Include possible alternatives.

Graphite:
Damage:  55 -> 100
Attack speed: x0.6
Knockback: 1.5

Pyratite: 
Damage 60 -> 70
Ammo multiplier: x2 -> x3

If anyones interested, here is a .docx document with calculations
[SpectreAmmoRework.docx](https://github.com/Anuken/Mindustry-Suggestions/files/6946779/SpectreAmmoRework.docx)
These numbers go well with my goals.

Alternative: 
graphite damage 70
Pyratite damage 75

*Some counterarguments I’ve seen or thought of:*

„The other options are supposed to be weak. They’re substitute ammos“
I kinda agree with this, whitch is why thorium should remain the „default ammo“ by having the highest dps. I argue that pyratite is at least of equal value, whitch is why I decided to go for a combo of ammo mult + dmg.
Graph will still be weak but now has some advantages over thorium.

„Graphite ammo should be weak, because it can be made everywhere/ is „cheap“ ammo.
1.	Graphite will still be the weakest of the bunch, just not terrible.
2.	Yes, graphite has the least value of all the ammo tyes of the spectre. While graph should be weaker than say thor or pyra in *early game* towers, this difference in strengh should slowly fade towards the end game towers, as building said towers requires you to have a whole bunch of partly valuable resources available.

„Such a drastic change shouldn’t be made“
It’s just touching some basic stats, and not by a lot.
In case Anuke doesn’t like this, I added alternative changes that just touch the damage.

**Comment by OnyxFinger** [comment]
it's pretty much like most ammos in guns
1 dominates and the other are useless because of whenever you get them and stuff and blablabla and turret timings
> The other options are supposed to be weak.

problem : thorium is easily mined, even though it can be very limited on some maps
I agree with the changes tho

**Comment by Nils101** [comment]
> 1 dominates and the other are useless because of whenever you get them and stuff and blablabla and turret timings. 

I don't have a problem with 1 ammo type being the standart bullet. I just don't think it's alright for 1 thing to dominate *everything* to the point where you could literally delete the other options and the game wouldn't be different.

> problem : thorium is easily mined, even though it can be very limited on some maps

Thorium being easily mind isn't a problem to me either. Problem is if it's very limited or not there at all, players rather go for other towers entirely, whitch there are plenty of.
Other options are invisible here, as I said.

**Comment by RealYeet** [comment]
Text galore, however, I do fully agree with the graph knock back change, I think personally that maybe the pita change on the damage is a little powerful because it already has FlAmE. (Although let’s be honest, fire does not do that much)

**Comment by OnyxFinger** [comment]
> > 1 dominates and the other are useless because of whenever you get them and stuff and blablabla and turret timings.
> 
> I don't have a problem with 1 ammo type being the standart bullet. I just don't think it's alright for 1 thing to dominate _everything_ to the point where you could literally delete the other options and the game wouldn't be different.

huh ? I don't understand what you mean by that. I literally just told you it's the case with many other turrets
you will never put pyratite intio a scorch (using scorches lol), never put plast into ripples and cyclones, never put pyratite into any gun, actually and shouldn't put titanium into fuses even know 40% of the community still does it while it is a purely negative choice (if you ever use fuses that is :vomiting_face: )

**Comment by RealYeet** [comment]
Actually onyxfingers, with other turrets there is an upside to putting other materials in the gun, pire scorches deal almost 2x damage. Plast Cyclones and Ripples have an aoe that deals insane damage. Titanium Fuses shoot 33% faster, with nearly the same dps as a Thorium Fuss. Specter is the only gun where alternative ammo types don’t have their own advantages.

**Comment by RealYeet** [comment]
Friking auto correct, rip

**Comment by Nils101** [comment]
@OnyxFinger sorry, I misunderstood your comment. I thought you meant that it's ok for 1 or 2 ammo types to be far stronger than other options.
Seems to be Anuke's stance on this however, as a few days have past and this suggestion hasn't been implemented. Doubt it will still be added, but it was fun brainstorming about this idea.

B̶t̶w̶ ̶f̶u̶s̶e̶s̶ ̶a̶r̶e̶n̶'̶t̶ ̶b̶a̶d̶

**Comment by Nils101** [comment]
Implemented! :)

**Comment by OnyxFinger** [comment]
> Implemented! :)

happy boy :)
