### ISSUE TITLE
Yellow air

### ISSUE THREAD

**Issue by Red0Sky** [Anuken/Mindustry-Suggestions#2804]
### Describe the content or mechanics you are proposing.

basically wind units
let me show you the units (note its more effective at air then at ground in knockback reasons for obvious reasons)
t1 blow: fires small winds at enemies.
t2 breeze: fires small bullets and small winds at enemies.
t3 wind: fires piercing lasers and winds at enemies.
t4 gust: fires strong winds and small wind bombs at enemies.
t5 tornado: fires swirling air bombs that suck in anything and large wind bombs at enemies.
also can litteraly SUCK IN non-laser enemy bulleyts

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

how it can improve  it is how it can push units away from others or away from cores or important stuff, or like push it into crawlers or push units like zenith or  into short ranges turrets like fuse or scorch
not very great for attack maps but can push away short ranged units like an enemy oxynoe away from a bryde witch can help
also sence the t5/titan sucks in enemy-non-lasers its kinda like a geneticaly-modified-moving-segment (Gmms)
also its costs 40 silicon, 10 lead and 20 copper.
and takes 30 sec to make in air factory (unless boosted by an overdrive projector or dome

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
### Some extra info i decided to add
swirling wind bombs are the inverse of wind bombs. they suck in units instead of blasting them away. thus they are inverses of wind bombs
Falling dead units (primaraly falling dead air units) Tend to not die when being sucked by a tornado. thus it can help prevent blast bombing
also the heavier the air unit, the less knockback
## eclipse: 0.2x knockback

**Comment by Red0Sky** [comment]
it takes 35 sec to create in air factory

**Comment by Red0Sky** [comment]
grrr i have to delete this bc theres already a sugegstion but i want dis pls

😢

**Comment by Red0Sky** [comment]
why u dislike

**Comment by Red0Sky** [comment]
it isnt going to be added i know it bc theres already a purple air so ig il think of something else

**Comment by Red0Sky** [comment]
yellow air

**Comment by SMOLKEYS** [comment]
> grrr i have to delete this bc theres already a sugegstion but i want dis pls
> 
> 😢 
> 

Anuke probably won't add this anywhere in the game.

**Comment by OnyxFinger** [comment]
if there is already a purple air suggestion but that doesn't propose the same units, then everything's fine
also yellow would be the core route and there are only three units
I think the idea of a knockback oriented route is kinda cool, but I am not sure it would have a use

**Comment by Red0Sky** [comment]
> 
> 
> > grrr i have to delete this bc theres already a sugegstion but i want dis pls
> > 😢
> 
> Anuke probably won't add this anywhere in the game.

shut up

**Comment by Red0Sky** [comment]
> 
> 
> > grrr i have to delete this bc theres already a sugegstion but i want dis pls
> > 😢
> 
> Anuke probably won't add this anywhere in the game.

also if you keep disliking im going to report i dont want anyone reacting with ANY emojis or other stuff like that or else

**Comment by Red0Sky** [comment]
> 
> 
> > grrr i have to delete this bc theres already a sugegstion but i want dis pls
> > 😢
> 
> Anuke probably won't add this anywhere in the game.

OR ELSE

**Comment by Red0Sky** [comment]
> 
> 
> if there is already a purple air suggestion but that doesn't propose the same units, then everything's fine
> also yellow would be the core route and there are only three units
> I think the idea of a knockback oriented route is kinda cool, but I am not sure it would have a use

Maybe just think like for any uses you can possible imagine just think
the core route has 3 units but the blow tree has 5
but theres already suggestions for purple air units

**Comment by Red0Sky** [comment]
maybe ill just do blue air

**Comment by Red0Sky** [comment]
> 
> 
> if there is already a purple air suggestion but that doesn't propose the same units, then everything's fine
> also yellow would be the core route and there are only three units
> I think the idea of a knockback oriented route is kinda cool, but I am not sure it would have a use

the swirling air bombs from the t5/titan tornado unit can keep falling dead air units from hitting the ground, thus preventing blast bombing, wind bombs and wind also reflect AWAY falling dea air so even <t5 can be used to "kind of" prevent blast bombing

**Comment by 50275** [comment]
gameplay-wise, I'm pretty sure that the parallax, segment, toxopoid projectiles, and quad replace every existing mechanic of these units.

the parallax pulls units, the segment nullifies non-lazer projectiles, the toxopoid uses some kind of artillery shell, and the quad is a large bomber.

**Comment by Kyllingene** [comment]
1. *People are allowed to use reactions. Deal with it.* Fun fact, one of those who exercised their freedom of speech via emoji happened to be not only a very smart, cool-headed contributor to this repo, but also a contributor to the Mindustry repo itself.

2. Chill out. People are allowed to voice opinions, but you seem unaware of that fact.

3. Yellow is already a used color (the basic unit tree on yellow team), and either way, while wind units *might* be cool, they wouldn't ultimately see much use; definitely more of a mod thing.

4. Next time, check for other issues of the same kind before posting.

5. Close this already; as you said, "i have to delete this".

6. ***Never, ever do #2812 again. You will almost certainly be banned, and nobody will take you seriously.***

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2812#issuecomment-894683140

**Comment by WilloIzCitron** [comment]
yes @ghost dont do this again
