### ISSUE TITLE
Superweapon ideas (Trello)

### ISSUE THREAD

**Issue by Jaysoon80** [Anuken/Mindustry-Suggestions#2806]
I recently was looking through the Trello and saw that superweapons were under future. This sparked my curiosity as I had never thought of superweapons in Mindustry and I started brainstorming what superweapons could be like. 

I thought of an idea.

 An interesting super weapon in a size of maybe 20×20 to 25×25 (Massive.) It would be unbuildable by the player and would be described as "unknown and undiscovered technology" which the player can not procure nor manifest. This  super weapon could be powered by perhaps mass amounts of power or could be supplied with large sums of resources or extremely hard to obtain resources. This super weapon would not fire at all if not fully powered (if it uses power) unlike turrets we have now that use power which instead of ceasing fire in power deficiency instead fire slower and less frequently. This weapon would also be indestructible and would not be targetted by enemies and would also not be destructible. This superweapon wouldn't even be a traditional weapon and would instead destroy perhaps a large barrier, ** disable an impermeable force projector** or **destroy an enemy mothership or planet.**

_This weapon would be similar to the quarantine enforcement platform in Subnautica (the cannon which shot down the sunbeam)_

(sorry i cant use format because for some reason on the mobile app it does not bring up the format idk)

**Comment by vinhsad** [comment]
the limit of block is 16x16 .-.

**Comment by OnyxFinger** [comment]
> the limit of block is 16x16 .-.

can be changed.
