### ISSUE TITLE
Custom Rules for Specific Teams

### ISSUE THREAD

**Issue by Jackson11500** [Anuken/Mindustry-Suggestions#2807]
### Describe the content or mechanics you are proposing.

Currently the custom rules in **[Resource & Building]** and **[Units]** category like unit damage, unit production speed, infinite resources... are made for all teams. Here I would like to propose the mechanism that separate overall game rule into different teams game rule. That is, different team has different game rules, like the crux has infinite resource but sharded plays normal games, or made crux has larger build speed multiplier to improve AI building but players in sharded plays normal..

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Becauses different teams shared the same proporties in game code, it's nearly impossible to achieved this even by using mod or js. For simplify, just sperated these proporties for each team in code and made them modifiable by js command or mod. And if possible, add options **[custom rules for each team]** in custom rules.
Being able to design custom rules for specify team could greatly expand game experience
for survival mode, team specified custom rules could made enemy unit do more/less damage to players unit, to encourage/discourage players using unit to defend enemy,
for attack mode, team specified custom rules could made crux has infinite resources, different layout, rebuild building, and produced unit which is banned for sharded
for pvp,  team specified custom rules could be used to made asymmetric pvp, like some team has higher building speed, while the other has lower building cost...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I could've sworn this used to be on the trello but I'm not finding it even in the Shelved section so I guess you're allowed ? idk
I like the sound of that a lot for survival and attack, but asymmetric PvP is generally to avoid trying, just like asymmetrical PvP maps.

**Comment by 50275** [comment]
Custom gamemodes become much more flexible with such an implementation. Take what used to be AA hub plague, for example. It will be easy to discourage survivors from considering attacking (they're supposed to defend with only turrets) by just multiplying their unit damage by 0.
