### ISSUE TITLE
"Block Placement Suggestions" Modification

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#2809]
### Describe what you would like changed, and why.

Automatic Block Suggestions makes placing a horizontal line of conveyors facing up or down impossible if there are obstructions, as they automatically default to bridge conveyors if this setting is on. 

![image](https://user-images.githubusercontent.com/68676339/128605571-83a31436-28a8-4092-acf3-ad3719fabb87.png)
In this image, I attempt to place a line of conveyors facing down. However, this is not possible as they automatically default to bridge conveyors. When I turn off Automatic Block Suggestions in Settings -> Game, I get the desired result (image below) but I miss out on features such as [this dev-preview].(https://discord.com/channels/391020510269669376/513178557653188609/813432546905555005)
![image](https://user-images.githubusercontent.com/68676339/128605685-4708a3c8-40e8-4aa6-8b15-f1a4effc0cef.png)

### Describe the changes you want to propose. Include possible alternatives.

When creating a line of conveyors facing a certain direction, it should only automatically become a bridge conveyor if the user doesn't rotate the conveyor to face a different direction. For example, in the first image, I click and drag from the left side to the right side; ideally, the conveyors are supposed to be downward-facing titanium conveyors because I rotated the conveyors to face that direction.

**Comment by Kyllingene** [comment]
I don't know how Anuke implemented block suggestions, but the simplest form of this suggestion is a two-liner; check if it has been rotated, then revert back to conveyors. Ideally, it would also return to suggesting blocks once rotated back to its original orientation.

The complicated bit is when you make conveyors with bends in one swipe, then try to rotate them; however, the use case for trying to rotate a bent conveyor track is so niche that it could probably be left out entirely (if it's even possible to rotate quick-placed conveyors). Checking if it has been rotated might be more difficult than I think it will be, but worst-case (I think) you can just declare a variable when you start planning a conveyor build that stores which direction is was originally facing, then check that later. Reverting back to the conveyors might also be a little tricky, I am not familiar enough with the codebase to tell; but the ideal case could take a bit of doing. This is one of those things you can end up sinking hours into while trying to bugfix and only realizing you did after the fact; so, maybe a contributor task.

**Comment by 50275** [comment]
The idea behind this suggestion assumes that the line of conveyors was placed by pressing left mouse button

**Comment by 50275** [comment]
The idea behind this suggestion assumes that the line of conveyors was placed by selecting the titanium conveyor, holding left mouse button down, and moving the mouse strictly to the right side, then rotating the conveyor selection downward. I had not thought of the idea that a player would try to do this with a diagonal conveyor; I see no practical usage for this unlike the original example.
