### ISSUE TITLE
A hotkey for item spacing 

### ISSUE THREAD

**Issue by winters791** [Anuken/Mindustry-Suggestions#281]
in my 2+ years of playing the new mindustry one of the most annoying things is placing a router after every one block in medium-sized turrets and also for using to build mechs. 
A hotkey which we can use by holding a specific key while dragging the mouse will leave space of one block(spacing can be customized) and place it in the next one. I think that would save a lot of effort for the builders out there

**Comment by Anuken** [comment]
This is extremely specific and unnecessarily complicates the building system; if you need a tile-able pattern, make a schematic with the pattern and place it down several times instead.
