### ISSUE TITLE
vela/quad balancing

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2811]
### Describe what you would like changed, and why.

vela and quad stats - 
vela bad because:
can be easily backstabbed, with surge swarmers as well
can not attack while flying and is not that fast, so you can just build a foreshadow and murder the vela while it's flying
not enough damage
dies to plast wall, if it tries to try fly over the wall the enemy can just build more right under the vela
barely moves and barely rotates when firing, amplifying the backstab part even further, you can even build shock mines under it
quad is powerful because:
hardly backstabbed, will just bomb whatever you try backstab it with (including 4x4 turrets)
if it goes into your base, say bye to your entire industry - the other t4s don't have the speed to escape the constant backstabs
is flying
does a lot of damage all around itself
unlike vela (which can be backstabbed on the way), can just rush to a core and destroy it with superior DPS and no weakness to plast walls

### Describe the changes you want to propose. Include possible alternatives.

nerf quad's speed and buff vela's, plus either remove the slowed down debuff while firing or make it less severe

**Comment by OnyxFinger** [comment]
quads are poweful but inconsistent
both vela and quad have a counter that is cheaper : 
 vela : plast walls, relying on pierce for balance is a bbbaaadddd idea
 quad : force projectors : even though quads can breach them, it takes a while. Quads are still able to get some damage though, if they have support, compared to velas, but they're weaker from it and can't stay away from it's suporting units

So in theory, a good way of balancing for starters (more modifications should be done, but at least this) : 
1) makes velas actually good by buffing smth like their speed (I think this is the best value to increase, cuz scepters are already the brute force unit)
2) make it clear that force projectors block AOE damage pppllleeeaaassseee not only is that THE thing that makes them good, but it's also a thing that would help balancing many things better, such as bombers (now players would stop whining about them lol)

**Comment by konstantys** [comment]
Vela's turning speed could it be increased imo, while it makes sense for it to be a slow heavy weaponry thing, it just makes it extremely vulnerable to backstabs, as ilya stated.

**Comment by CoalRock8642** [comment]
As a PvP point of view, all servers are happy with current unit stats, if you mean for single player. I leave it to you.

**Comment by konstantys** [comment]
> As a PvP point of view, all servers are happy with current unit stats, if you mean for single player. I leave it to you.
> 
> Vela is cheat, it start attacks and fly.

The fact that they are happy doesn't mean that they could be happier. The current unit stats may be unbalanced, but no unit is OP to an extent that'd ruin games (some people would say that about zenith blast rush, but that may be a matter of change in v7 and this thread isn't about it). Vela doesn't quite have a use.
- Against defenses, plast walls go brrrr. Sure, vela could fly, but at the point of the enemy having plast walls, they'd have good anti air that'd shred vela's health behind them.
- Against single target, vela's single target dps is bad.
- Against multi smaller units, they are fast enough to backstab vela.
- Bruh

**Comment by Jaysoon80** [comment]
Dont nerf the quad but yeah definetly vela should be buffed. Maybe increase its damage slightly and make it so it has a higher turret turning rate.

**Comment by itcannotbe** [comment]
Why not just give vela something like thicker armor when hit from the "side".
