### ISSUE TITLE
> grrr i have to delete this bc theres already a sugegstion but i want dis pls

### ISSUE THREAD

**Issue by Red0Sky** [Anuken/Mindustry-Suggestions#2812]
> grrr i have to delete this bc theres already a sugegstion but i want dis pls
> 
> 😢 
> 

Anuke probably won't add this anywhere in the game.

_Originally posted by @SMOLKEYS in https://github.com/Anuken/Mindustry-Suggestions/issues/2804#issuecomment-894612154_
STOP IT

**Comment by JrTRinny** [comment]
this is the peak of humanity
why do you have to make a new issue just to expose someone?
you deserved to be banned from this repo.

**Comment by Kyllingene** [comment]
1. This is against the repositories purpose. Delete immediately.
2. This is a perfectly reasonable response. Is it a crime to voice ones opinion?
3. This is the worst way to seek recourse. Take it up with them, or leave it.

This is what gets people banned from repositories.

**Comment by Anuken** [comment]
Blocked for spammy/immature behavior.

**Comment by WilloIzCitron** [comment]
conclusion:

do not harras anyone about your suggestion or people's suggestion
