### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Dryehm** [Anuken/Mindustry-Suggestions#2814]
### Describe the content or mechanics you are proposing.

The ability to change the resolution.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I was recording using game bar recorder and a black border was there, some reasons was that the game was low resolution and i was recording in higher resolution.
![payn](https://user-images.githubusercontent.com/79123285/128617729-0949b863-968a-4663-ade7-51ce76bf21d4.png)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
It would be monumentally easier to either record at lower res or just edit the video than it would be to completely overhaul the graphics engine.

**Comment by CoalRock8642** [comment]
May I know your recording software, the screen/monitor resolution, and also screenshot your graphic settings.

**Comment by SMOLKEYS** [comment]
~~y tho @ghost~~
