### ISSUE TITLE
Upgrade Zone

### ISSUE THREAD

**Issue by Yakuzet** [Anuken/Mindustry-Suggestions#2815]
### Describe the content or mechanics you are proposing.

I have an idea for conveyors. like, upgrade zone if there are classic conveyors and I want to upgrade it to titanium con. and I don't want to upgrade them one by one...

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I will choose this "upgrade zone" stuff and choose which conveyor (or other upgradable things like walls or drills...) I want to upgrade and choose like zone which is used for copy schematic

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
I believe this is doable with logic, but don’t take my word for it, I can’t get it to work

**Comment by IIINSTINCT** [comment]
Haha logic gooo brrrrrrrrrrrrr

**Comment by Humanoid-X** [comment]
Use lofic lol

**Comment by OnyxFinger** [comment]
stop saying logic please
but I believe this is additionnal UI config right ?
if not, well **no you nerd, because using the "diagonal placement automatically places the conveyors in the same way than the old ones, for easier upgrading**
I for some reason cannot get a screenshot of this event whatsoever, so I can't provide an example

**Comment by Bottinator22** [comment]
stop saying logic
for one some people don't even know how to do this with logic, I don't know how to do this with logic
for another, some servers disable logic building

**Comment by Kyllingene** [comment]
Oh, if only there was a merged PR that already added conveyor upgrades to the game, like say, [Mindustry#3912](https://github.com/Anuken/Mindustry/pull/3912) - oh wait. I guess you lied on that second checkmark. Well, you might want to close this since it already mostly exists.

**Comment by SMOLKEYS** [comment]
> and I don't want to upgrade them one by one...

Bro, do you not know how to hold and slide?

**Comment by Yakuzet** [comment]
> Oh, if only there was a merged PR that already added conveyor upgrades to the game, like say, [Mindustry#3912](https://github.com/Anuken/Mindustry/pull/3912) - oh wait. I guess you lied on that second checkmark. Well, you might want to close this since it already mostly exists.

I didnt mean it

**Comment by Yakuzet** [comment]
> > and I don't want to upgrade them one by one...
> 
> Bro, do you not know how to hold and slide?

bro I DIDNT MEAN IT man there is anyone who understand me

**Comment by Bottinator22** [comment]
Then close this
