### ISSUE TITLE
[Edited] Some new blocks cannot be rotated after building in the mobile game version.

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2816]
### Describe what you would like changed, and why.

I'm playing android version game and I can't change the output direction of payload propulsion tower and payload source block after builded.
![GIF-210810_084014](https://user-images.githubusercontent.com/45112661/128791540-b34401a2-46c5-4751-8135-fc9f8ebd4ba5.gif)

### Describe the changes you want to propose. Include possible alternatives.

Pls make it changeable, most mobile phones have no physical keyboard so we cant press "r" key to rotate it.😂

**Comment by Humanoid-X** [comment]
.... You change it like mass driver...??

**Comment by Hexrotor** [comment]
> .... You change it like mass driver...??

Just change it in rebuilding and can without deconstruction. Mass driver has no direction... isn't it?

**Comment by Hexrotor** [comment]
Sorry I’m not an English speaker, maybe my meaning is not clear.

**Comment by RealYeet** [comment]
He means the direction of the output on the payload mass driver. Unfortunately, as of right now, it can not be rotated with the “r” key

**Comment by Hexrotor** [comment]
> He means the direction of the output on the payload mass driver. Unfortunately, as of right now, it can not be rotated with the “r” key

Yeah that's my idea, thank u bro.
@Anuken You may need to see this :)

**Comment by Kyllingene** [comment]
Never, ***ever*** mention Anuken. He is a busy man. If he thinks your idea is worth it, he will implement it; 9 times out of 10, he won't, but he almost always sees it. ***Never*** mention him.

**Comment by Anuken** [comment]
> Unfortunately, as of right now, it can not be rotated with the “r” key

Have you not tried?

![2021-08-09-20-02-19](https://user-images.githubusercontent.com/10100000/128789027-4298773c-fd2c-48b1-881a-8f9ad1a88d95.gif)

**Comment by Hexrotor** [comment]
> Never, _**ever**_ mention Anuken. He is a busy man. If he thinks your idea is worth it, he will implement it; 9 times out of 10, he won't, but he almost always sees it. _**Never**_ @ him.

okey

**Comment by Hexrotor** [comment]
> > Unfortunately, as of right now, it can not be rotated with the “r” key
> 
> Have you not tried?
> 
> ![2021-08-09-20-02-19](https://user-images.githubusercontent.com/10100000/128789027-4298773c-fd2c-48b1-881a-8f9ad1a88d95.gif)

But I cant do this in build 21641 android version by swipe screen, I didnt try this in PC version, Im sorry

**Comment by Hexrotor** [comment]
> > Unfortunately, as of right now, it can not be rotated with the “r” key
> 
> Have you not tried?
> 
> ![2021-08-09-20-02-19](https://user-images.githubusercontent.com/10100000/128789027-4298773c-fd2c-48b1-881a-8f9ad1a88d95.gif)

![Uploading GIF-210810_084014.gif…]()
Like this...

**Comment by Hexrotor** [comment]
![GIF-210810_084014](https://user-images.githubusercontent.com/45112661/128791468-b629df01-c16f-475e-8677-06dc91d4e386.gif)
Like this...

**Comment by Hexrotor** [comment]
oh no... Anuke may won't read this post again.

**Comment by Hexrotor** [comment]
fixed in the latest build
