### ISSUE TITLE
New chat system. New schematic mechanics.

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#2819]
### Describe the content or mechanics you are proposing.

I want to copy/paste from in-game chat. Some maps have banned micro processors. So there is no way to copy code from schemes.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

(1) I don't want ability like to copy codes from in-game chat. One liners also work. This can be achieved probably through console.

(2) Like foo's client ability to copy player name from press Tab>player-list.

(3) Ability to copy code from schemes. This can be achieved by opening scheme info and probably hovering around the process to which you want to copy.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by KinneticSlammer** [comment]
Seems like a good idea to me. I also have wanted this feature for a while.

**Comment by OnyxFinger** [comment]
I never needed any of this, but it can be useful

**Comment by GameGoon** [comment]
I was about to make a new suggestion on 3 but had to see of anyone did it and here it is. I would absolutely love to see this in-game
