### ISSUE TITLE
Allow the new support naval units to hold unit payload

### ISSUE THREAD

**Issue by Jaysoon80** [Anuken/Mindustry-Suggestions#2821]
I always loved the idea of an aircraft carrier and I think that with the support naval tree this could be implemented. I think that both the t4 and t5 support naval units should be able to hold a large amount of either naval or air units. The naval units would depart from the sides of the ships as if they came out from docks on the ship and the air units would come out from the middle as if they came from a run way. The amount of naval units and air units would be seperated amounts (you can have a amount of naval and b amount of air) and also the air/naval units held can only be t1 or t2 (to make the mega/quad/oct still viable.)

**Comment by OnyxFinger** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2808
duplicate lol
I think air units could be carried by T2-T3, but only air so that you can't just stack boats ontop of each other
I like this idea

**Comment by SMOLKEYS** [comment]
Where's the template?

**Comment by itcannotbe** [comment]
> Where's the template?

Blame the gitnub app.

**Comment by itcannotbe** [comment]
See https://github.com/Anuken/Mindustry-Suggestions/issues/2808#issuecomment-894831480
