### ISSUE TITLE
Unlimited ressources to purchase new technologies

### ISSUE THREAD

**Issue by ClaraWieckSchumann** [Anuken/Mindustry-Suggestions#2822]
### Describe what you would like changed, and why.

I'm playing on the last Android version from f-droid: 6-fdroid-107.

In the campaign, after having successfully launched at least one core and while developping another  new sector, ressources from other sectors are at their maximum each time I click on the tree to see the technology tree. That mean I can simply click on the tree, purchase technologies (with, say, 4k Copper and 4k Lead from my first successfully conquered sector), press "Back" and immediately click on the tree again, and I'll be able to spend another 4k Copper and 4k Lead.

Obviously this is a major gamebreaker since one can purchase whatever technology one wants in no time, provided one is gathering every needed material in at least one sector.

### Describe the changes you want to propose. Include possible alternatives.

The so-called "Global items" should be loaded again at the expected production rate rather than instantly.

**Comment by joshuaptfan** [comment]
This is not the place to report bugs. Report bugs here: https://github.com/Anuken/Mindustry/issues/new?template=bug_report.md

**Comment by Anuken** [comment]
Build **107** is an *Alpha* version that was released nearly a year ago; you really shouldn't be playing it. The F-Droid build is broken until further notice, download from itch.io.

**Comment by ClaraWieckSchumann** [comment]
Thank you for your quick answers!

**Comment by ClaraWieckSchumann** [comment]
By the way, I read the README before posting and the most appropriate place seemed to be here. You may want to add the right place to report a bug to it for clearer instructions?

About the alpha version, you may want to display the right way to download the game on the Mindustry's f-droid page? I can't see that on it and I know many people using f-droid and downloading apps from it without further researches how to download the app another way. There is a pop up when one opens the app, warning that it is an alpha version, but nothing about how one is supposed to get a newer version.

**Comment by MrDuck557** [comment]
> The F-Droid build is broken until further notice, **download from itch.io**.

https://anuke.itch.io/mindustry, there is an apk version

**Comment by Anuken** [comment]
> About the alpha version, you may want to display the right way to download the game on the Mindustry's f-droid page?

I didn't set up Mindustry's F-Droid listing, and I never really considered mentioning other sources, as (ideally) fixing the build would be a better solution. I don't know if that's likely to happen.

**Comment by SMOLKEYS** [comment]
~~Uh... why is this still open?~~

**Comment by Humanoid-X** [comment]
~~Um excus me please close and what make you think this is the *most appropriate* place to report bug~~
