### ISSUE TITLE
Water-based item transportation

### ISSUE THREAD

**Issue by Kyllingene** [Anuken/Mindustry-Suggestions#2823]
### Describe the content or mechanics you are proposing.

I make this issue with extreme trepidation; I understand that there are several issues of similar substance, but I wish to suggest something a little different. What I want is not necessarily a line of water units dedicated to item transport, but any sort of water-based item transportation that is at least marginally faster than land- or air-based methods, probably through an existing tree.

Of course, this would probably come in the form of naval units, as everyone is clamoring for; but I think that simply reworking the one of the existing naval trees to act double duty would be sufficient. For example, support naval also taking on item transport, similar to support air's duties; or, maybe the Risso can transport small amounts of items; it is a fast, small, low-damage, and low-cost ship, making it a perfect candidate.

The problem to be solved is how to load the ships with items, a problem most issues seem to ignore. I see a few options; one is to add a block dedicated to this, like a port (my least favorite plan). Another is to allow air units to unload onto water units; but then, the problem becomes the fact that you need air units to make this new avenue of water usage possible, which I want to avoid. My personal opinion is that naval units should be able to take and deposit in a way almost identical to how air units do it, except it interacts with the nearest storage within 5 or so blocks as opposed to the block directly beneath it.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I have always been a fan of accomplishing more gameplay with fewer mechanics, and keeping naval simpler while expanding its utility sounds like a great way to do that. It encourages not only water-central attacks but also water-central bases, which comes with the added benefit of encouraging pumps over water extractors. I am aware that maps would almost certainly need more water to make this a useful feature (beating the urge to make your base as small as possible is hard), but there are already maps that existed long before naval even existed that are perfect for this, and with support naval coming too I think it is already time to add more water into randomly generated sectors. I feel that making water even more useful than land is critical to both encouraging more spread-out bases (which allow for more varied and clever tactics, instead of a race for the biggest units) and turning an obstacle into a resource, creating "highways" in the middle of those newly spread-out bases.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
So you say you tried not to make yet another "[container ships](https://en.wikipedia.org/wiki/Container_ship), but in Mindustry", but ended up suggesting exactly that anyway...

Since no one else is connecting the dots, container ship suggestions are just as doomed as train suggestions. Both require dedicated blocks to load/unload, increasing complexity; on top of that, since container ships don't sail on tracks, there are additional complexities involved.

* What would these transport units' default behavior be?
* How would you bind units to particular origin/destination ports?
* Would players be able to take direct control of transport units?
* How would units figure out how to get to their destination? (Pathfinding to arbitrary coordinates that aren't a core isn't supported.)

All previous suggestions on this topic have failed because they didn't consider how this new mechanic would function in-game beyond "just like in real life, duh".

**Comment by Kyllingene** [comment]
> Both require dedicated blocks to load/unload, increasing complexity

Actually, I suggested a method of loading/unloading that added no blocks and thus no complexity.

> What would these transport units' default behavior be?
> How would you bind units to particular origin/destination ports?
> Would players be able to take direct control of transport units?
> How would units figure out how to get to their destination?

Most of those questions are answered by reminding you that these are pre-existing ships that have already answered those questions. Besides that, though, I would like these ships to be used for transport via logic. However, going from point A to point B is a deceptively tricky problem.

You could argue that pathfinding to arbitrary coordinates is ok here, since the coordinates aren't moving and could be set to only change every 5 seconds or so; but I would like to avoid that. Logic would work, except that they don't have the free movement that makes logic-based air transport work.

My suggestion to overcoming naval ships getting stuck on blocks in general is simple. You raycast one blocks length in front of the unit in the direction it is trying to go when it is trying to move but its speed is 1/10 (negotiable, obviously) or less of its max. Then, you simply snap the units movement direction to `direction % 90` (four cardinal directions) until its previous intended direction is no longer obstructed. Very simple to program, very quick to run, but still mostly circumvents the first problem (the other problem is large bends in the river, but you can simply make a rudimentary waypoint system in your logic). If people get as crafty as they do with air unit logic, they can do the same with naval unit logic.

> All previous suggestions on this topic have failed because they didn't consider how this new mechanic would function in-game beyond "just like in real life, duh".

I have tried my best to avoid that; after all, how realistic is it to have small attack ships handling large amounts of cargo? How realistic is it to magic items out of a nearby container? I have not consulted realism a single time during making this issue, thinking only of the actual uses. Could it be that you read the title and first paragraph and then wrote the issue off as a duplicate with nothing new to bring to the table?

**Comment by Anuken** [comment]
This is not going to happen.

- **Most maps do not have water between points of interest, if at all**. This, by itself, is enough to cripple water-based transportation. Air-based transport doesn't have this problem. Even large-scale changes to campaign generation (*not easy, by the way!*) will not fix this.
- There are already plenty of easier long-range transportation options (mass drivers, air units), with more (payload propulsion towers + unloaders + containers) on the way.
- Pathfinding to special load/unload points that change dynamically with configuration is very difficult to set up.
- Implementing this would involve adding & maintaining 2-ish new blocks with complex logic just for an extremely niche mechanic.

*Even* if I bend over backwards and make naval units store absurd amounts of cargo while significantly increasing the amount of campaign water maps, this still won't be viable. Mass drivers chains (& perhaps copy-pasted air transport) are far more general solutions that are easier for players to set up, and most servers just don't have the right amount of water in their maps.

This mechanic just isn't worth implementing in the game, both in terms of effort needed and in-game viability.
