### ISSUE TITLE
Parallax and Segment as defense blocks

### ISSUE THREAD

**Issue by KayWasTaken** [Anuken/Mindustry-Suggestions#2824]
### Describe what you would like changed, and why.

I've noticed that parallax and segment are considered defense blocks in the sprites, so maybe they should be put in the defense category. They could also have a different base to differentiate between the turret blocks in the game.

### Describe the changes you want to propose. Include possible alternatives.

Put parallax and segment in the defense category or effects category, and maybe add a different base sprite.

**Comment by itcannotbe** [comment]
They are still turrets nonetheless.

**Comment by Bottinator22** [comment]
They're probably considered defense blocks because of how differently they work

**Comment by IIINSTINCT** [comment]
This is not necessary Turrets are technically a defense from enemy units and this would just confuse players if the segment and parralax would be moved
