### ISSUE TITLE
mineral display

### ISSUE THREAD

**Issue by ShidoKunG** [Anuken/Mindustry-Suggestions#2825]
### Describe the content or mechanics you are proposing.

I want you to make a hotkey for hiding the mineral display or can minimize the mineral display. Because it's very problematic when playing with different mineral mods. Please hurry to add this feature in the future.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make a hotkey for hiding the mineral display or can minimize the mineral display.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
...what

**Comment by wdmvv** [comment]
> ...what

He tells about resources list in middle of screen (resources in core)

**Comment by itcannotbe** [comment]
How about not playing with a lot of mods or mods that add a lot of resources for starters?

**Comment by ShidoKunG** [comment]
![Screenshot_156](https://user-images.githubusercontent.com/72859212/128662287-21b9b5d3-0b66-4576-a29a-0ff88062b3a4.png)

**Comment by JrTRinny** [comment]
that a lot of mod, try disable it
also update your game :D

**Comment by joshuaptfan** [comment]
In graphics settings, there is already a toggle for "Display Core Items". Turn that off, and your problem is solved.

> Please hurry to add this feature in the future.

Please be polite.

**Comment by IIINSTINCT** [comment]
Bruh

**Comment by Humanoid-X** [comment]
Bruh did you actually check settings before creating suggestion huh kiddo

**Comment by ShidoKunG** [comment]
> Bruh did you actually check settings before creating suggestion huh kiddo

I know We can hide the mineral show. But I want it to be able to shrink the mineral show.

**Comment by ShidoKunG** [comment]
> In graphics settings, there is already a toggle for "Display Core Items". Turn that off, and your problem is solved.
> 
> > Please hurry to add this feature in the future.
> 
> Please be polite in how you ask for things.

I'm sorry to ask for something that's not possible right now, but I'll be looking forward to seeing this feature in the future at any time.

**Comment by joshuaptfan** [comment]
> But I want it to be able to shrink the mineral show.

There is no "shrinking" the core items display. It is either hidden or shown. What would "shrinking" even mean?

**Comment by ShidoKunG** [comment]
> > But I want it to be able to shrink the mineral show.
> 
> There is no "shrinking" the core items display. It is either hidden or shown. What would "shrinking" even mean?

I want the window to show the minerals are scalable as needed. 
(Sorry I'm not very good at English because I'm not from your country.)

**Comment by itcannotbe** [comment]
How about using a lower ui scaling?
