### ISSUE TITLE
unit weapon rotation cone and the the to draw a unit weapons under the unit

### ISSUE THREAD

**Issue by AureusStratus** [Anuken/Mindustry-Suggestions#2826]
### Describe the content or mechanics you are proposing.

these things are more for modding purposes then anything else and it would help out a lot with modding especially for json mods 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

alright first with the one that will allow unit weapons to be drawn under a unit it just something that allows modders to draw 
unit weapons under the unit this would be helpful with things like ground units this can simply be a true or false example its can like drawUnder: true this could be use on the current units or even future ones

now for the unit weapon rotation restrictions this one will simply add the ability to restrict how much a units weapon can rotate this one can be possibly used on some current units but this would be quite helpful in modding this one will work like any type of cone you could make the weapon only be able to rotate 30 degrees 45 or 90 they way this would look would probably be rotateCone: maybe

pu had done this and i thought it would be nice to possibly have those two things in the game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Holy cow, please edit your title and suggestion to include proper capitalization and punctuation. It's in your interest to make your suggestion easy to read if you want it to be taken seriously.

At least you have paragraphs.

**Comment by itcannotbe** [comment]
> Holy cow

👼🐮

This suggestion should be 2 separate ones TBH.

**Comment by AureusStratus** [comment]
i do not care for capitalization or punctuation well at least here but i have em i my own mod tho

**Comment by itcannotbe** [comment]
> If weapons are restricted to rotation within specific angles, they may look more "correct", but they will not be able to fire sometimes, as units' AI do not care about properly facing their targets. So, it's not feasible, because it's not worth the effort to rework unit AI to make units face targets for only an aesthetic benefit.

Actually it's not. This actually can nerf units when coupled with slow rotate speed. Which means you have more balancing options.

Say speedy units are restricted to a narrow shoot cone and slow moving until have a wide shoot cone.

**Comment by AureusStratus** [comment]
to be honest i just really wanted to suggest these two things because they would be so helpful when modding units rlly

**Comment by itcannotbe** [comment]
> to be honest i just really wanted to suggest these two things because they would be so helpful when modding units rlly

No new mechanic actually gets added into the game just so that a mod maker can use it, rather new mechanics are added because the base game actually uses it.

**Comment by GamerMoment69** [comment]
length of a single sentence: _yes_

**Comment by BlueWolf3682** [comment]
> > to be honest i just really wanted to suggest these two things because they would be so helpful when modding units rlly
> 
> No new mechanic actually gets added into the game just so that a mod maker can use it, rather new mechanics are added because the base game actually uses it.

water only placement
jsonable ammo
lightning ability x axis offset (pending)
block destruction effects
any block can have variants
custom unit death explosions
*do you **want** me to continue?*

**Comment by itcannotbe** [comment]
Um you do know those are effects not mechanics right, except for the variant one.

**Comment by BlueWolf3682** [comment]
You are entirely incorrect. 
though many only are visuals, MoveLightningAbility is an entire *Ability* class
jsonable ammo is the entire AmmoTypes class, aka "Unit Ammo"
requiresWater is a field *only* used in modding that makes blocks only placeable on water
theres also custom bullets for mass drivers, which is an entire bullet class.
again, back down. you will lose.

**Comment by itcannotbe** [comment]
If you refactoring a class to make it modabble is a side effect of just making the class easier to work with.

But I must admit, requireswater is not used in the base game.
