### ISSUE TITLE
Randomly generated maps

### ISSUE THREAD

**Issue by random-guy1285** [Anuken/Mindustry-Suggestions#2827]
### Describe the content or mechanics you are proposing.

Randomly generated maps.
There should be a option to randomly generate maps in the custom game screen.
Featuring a difficulty slider or selection and options either for it to be survival or a attack map. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would make it possible for players who do not want to play user made maps and/or have completed the campaign to play more maps. This will also provide a way for players to "de-rust" and play new content without the need for a internet connection.
Generating maps at will seems hard to make but due to the fact that numbered sectors already appear to be randomly generated you might already have the base for this. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Already suggested previously #2077 #773

**Comment by Bottinator22** [comment]
You can already do this in-game by messing around with editor.

**Comment by random-guy1285** [comment]
> You can already do this in-game with certain custom maps.

Elaborate.

**Comment by oinkymoo** [comment]
> Already suggested previously #2077 #773

your point being? duplicates are allowed

**Comment by random-guy1285** [comment]
> > Already suggested previously #2077 #773
> 
> your point being? duplicates are allowed

Plus,  more than 750 issues ago.

**Comment by joshuaptfan** [comment]
> Plus, more than 750 issues ago.

Not asking you to look at every previous issue, because there is a **search bar**. Even if duplicates are allowed, you should still do a **brief search** of past suggestions to see if the thing you're asking for is either 1)already implemented or 2) not feasible.

**Comment by OnyxFinger** [comment]
> > Plus, more than 750 issues ago.
> 
> Not asking you to look at every previous issue, because there is a **search bar**. Even if duplicates are allowed, you should still do a **brief search** of past suggestions to see if the thing you're asking for is either 1)already implemented or 2) not feasible.

the srearch bar is kind of innacurate if you want my opinion
