### ISSUE TITLE
three seperate "space" tiles

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2828]
### Describe the content or mechanics you are proposing.

The idea is to have three different kinds of "space" tiles that are both placeable in the editor, and appear in campaign.

the first kind is the existing space tile, except there is a small "star" in the center. the star has parallax, and moves around slightly based on where you are on the map, but not by much. for example, if you move to the bottom left of the map, the star would be further towards the top right of your screen.

the second kind is the same as the first, but the star is bigger, moves a little more (parallax), and the nebulas in the sky are a little brighter. this is to make it appear and feel like you are "closer" to the star than with the first kind of space tile.

the third kind has the star even bigger, more parallax movement, nebula a little brighter, as well as a slight orange "glow" across the tile. this tile is supposed to feel like you're very close to the star.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can both be used in map making and the campaign.

Based on what i've seen in "dev previews", the asteroids seem to be in the same orbit as planets. and if there's three planets, then the "asteroid sectors" the game generates can have the different space tile types depending on how close they are to the star. this provides more immersion, and will make space sectors in general feel more "alive" and dynamic.

For custom maps, people can innovate with the new blocks and make space maps more unique. also, without a star nearby, anything in space will go extremely cold. so the added "star" to custom space maps makes more sense, not just to the game, but also real life physics (even though, based on suggestions responses in the past, thats not a priority)

so yeah, immersion, added effects, and added depth to both the campaign and map editor. thats why these three space tiles should be implemented.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
> the first kind is the existing space tile, except there is a small "star" in the center. the star has parallax, and moves around slightly based on where you are on the map, but not by much. for example, if you move to the bottom left of the map, the star would be further towards the top right of your screen.
> 
> the second kind is the same as the first, but the star is bigger, moves a little more (parallax), and the nebulas in the sky are a little brighter. this is to make it appear and feel like you are "closer" to the star than with the first kind of space tile.
> 
> the third kind has the star even bigger, more parallax movement, nebula a little brighter, as well as a slight orange "glow" across the tile. this tile is supposed to feel like you're very close to the star.

This additionally should be toggle-able so not everyone has to deal with the fps loss, otherwise this is just a question of implementation.

**Comment by sup3r87** [comment]
> This additionally should be toggle-able so not everyone has to deal with the fps loss, otherwise this is just a question of implementation.

it doesnt need any fancy rendering techniques. it could quite literally just be a gif in the background. just adding a single image to the background wont do anything to the FPS

**Comment by stuffyAI** [comment]
> it doesnt need any fancy rendering techniques. it could quite literally just be a gif in the background. just adding a single image to the background wont do anything to the FPS

Parallax in a game where you relative element movement could be in all 360 degrees is indeed rendering, even if minor.

To move the star(s) in space tiles I will calculate relative camera movement and apply some fraction of it to the stars as well.


On another node, I would recommend that any parallax background effects are instanced as map layers, not tiles, similar to Terraria, Geometry Dash or various Website designs. This way we save some performance  (having to only move a few layers at once) whilst also providing consistency should a tile end but you keeping moving.
The only disadvantage here is that we lose non-linear parallax options based on absolute distance from the player, which theoretically could look more beautiful.

**Comment by OnyxFinger** [comment]
cool idea, I guess it would make space backgrounds a little more detailed

**Comment by Kyllingene** [comment]
> immersion, added effects, and added depth

 - `Immersion = realism` which is *never* a good reason to do something in Mindustry;
 - the added affects would be very minimal for the amount of effort to implement them,
 - and there is a significant difference between depth and graphical realism.

On that second point: how do the tiles interact? To look even half decent, they must be able to parallax into each other; but implementing graphical complexities like parallax that are distinct but cooperative between different types of tiles would be no cakewalk, and thus *wayyy* to much effort for such a small detail; also, it increases the amount of effort mapmakers would be *required* to put into their maps, just because you want a tiny bit more detail.

**Comment by sup3r87** [comment]
>On that second point: how do the tiles interact? To look even half decent, they must be able to parallax into each other; but implementing graphical complexities like parallax that are distinct but cooperative between different types of tiles would be no cakewalk
the idea is, the star just exists as a second background "layer". the space background already has parallax of it's own; it wouldnt need any rewrite of anything.
>also, it increases the amount of effort mapmakers would be required to put into their maps, just because you want a tiny bit more detail.
if you read my suggestion, there would just be 2 other tiles. no new effort for map makers, unless you count the 30 second timespan of choosing a tile a significant addition to map making.

also, i do know realism bad (literally stated in the suggestion) but imo it would make more sense for the space background to have a big star in it. all it is is a second layer. there doesnt need to be any sort of fancy graphical things. this is literally the same load on a computer that giving a dagger unit "wet" is.

this change is just a request to expand space tile diversity. that's it. and frankly, these words:
>just because you want a tiny bit more detail.
are quite harsh.

**Comment by Kyllingene** [comment]
> if you read my suggestion, there would just be 2 other tiles. no new effort for map makers, unless you count the 30 second timespan of choosing a tile a significant addition to map making.

You added a detail to each and every tile. Therefore, anybody wishing to use those tiles must vary them to avoid a horrendously ugly aesthetic of identical, tiled stars, which takes a significant amount of time, especially on maps with more space.

> this change is just a request to expand space tile diversity. that's it. and frankly, these words:
>>    just because you want a tiny bit more detail.
>
> are quite harsh.

Are they? Is the miniature amount of added realism (or diminished, if you fail to use the new tiles in a realistic fashion) worth it? I think not.

**Comment by sup3r87** [comment]
>You added a detail to each and every tile. Therefore, anybody wishing to use those tiles must vary them to avoid a horrendously ugly aesthetic of identical, tiled stars, which takes a significant amount of time, especially on maps with more space.

I think there might be misunderstanding here. the idea is that, the 2 new and existing space tile all display a star as a "background layer", and similar to the real space tiles, star density does not increase if you place more tiles. there is no "star" tile, and the more tiles you place wont change the amount of (big) stars. I know this isnt really a very matured feature in mindustry, but the space background already has parallax of it's own. it just renders a new "star" in the space background.

>Are they? Is the miniature amount of added realism (or diminished, if you fail to use the new tiles in a realistic fashion) worth it? I think not.

it's not just about realism, its about beauty too. I've played games with a star in the background, and i believe a change like this will make the game a lot more beautiful. also, the different vibrancies from the three blocks, plus the already existing "fog" mechanic make for more interesting looking map designs.

considering the effort is just adding a new "background layer" to space tiles, making new space tiles with recolors, and making three differently sized star gifs (or some other way to render them), makes not only custom maps but the campaign's space maps feel more alive, i believe it's worth it, yes.

**Comment by Kyllingene** [comment]
> I think there might be misunderstanding here.

Ah, pardon; you were correct. However, that would still be tricky to implement, as now you render different parts of the same background to different tiles; and wouldn't it look janky if there is a big star shown in one tile, but the next tile over doesn't render that star and thus it disappears via parallax?

> it's not just about realism, its about beauty too.

Beauty is a good goal, but I fail to see how adding a few stars to a particular tile only used in even more particular maps would look beautiful enough to warrant the solving of so many semantic issues.

**Comment by Humanoid-X** [comment]
I dunno but i think it will create a very ugly grid like star map.

**Comment by GitHubUser-B** [comment]
>just because you want a tiny bit more detail.

My new picture is relatable for almost everyone here

**Comment by Kyllingene** [comment]
Oh no, am I saying that something that adds almost nothing tangible to the game while taking more effort than they realize would be a *bad idea?* Sorry, I'll keep my silly opinions to myself, then.
