### ISSUE TITLE
Buff Meltdown

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry-Suggestions#2829]
### Describe what you would like changed, and why.

Meltdown *was* a good turret in v5, now it's very weak, and used to kill swarms of small t3 units instead, which is not good considering it's one of the end-game 4x4 turret and it even cost a ton of surge to make, it's supposed to be great and strong, even if it didn't cost surge, people will still choose Spectre, with around the same price, but with more power and versatility.
(yes, discussed in **`#balancing`**, I don't know if it's too much, but I'll try to make it not too OP)

### Describe the changes you want to propose. Include possible alternatives.

Firing Rate: 0.66 -> 0.7 (DPS 840 -> 882)
Effect: Incendiary -> Melting
Range: 24.37 -> 26
Cost: 325 Surge Alloy -> 300

if this is too much, tell me

I have no possible alternatives.

**Comment by itcannotbe** [comment]
Meltdowns are weak because armor is a bitch.

**Comment by EclipsePlays** [comment]
> Armor is a bitch.

What

Meltdown's weakness is the improper dps to cooldown balancing. 
A meltdown cools for *idk 4 seconds, (0 dps), while it shoots a beam for 4 seconds, (840 dps), which means a meltdown has an average dps of 420.

**Comment by itcannotbe** [comment]
> > Armor is a bitch.
> 
> What
> 
> Meltdown's weakness is the improper dps to cooldown balancing.
> A meltdown cools for *idk 4 seconds, (0 dps), while it shoots a beam for 4 seconds, (840 dps), which means a meltdown has an average dps of 420.

It doesn't shoot a beam for 4 seconds, pulse of 70 damage 60 / 5 times per second. So each pulse is reduced by armor.

I know it's dumb.

**Comment by itcannotbe** [comment]
Actually the average dps without liquids is ~600 factoring damage done while shooting and reload time.

**Comment by Kryvytsky** [comment]
> > Armor is a bitch.
> 
> What
> 
> Meltdown's weakness is the improper dps to cooldown balancing.
> A meltdown cools for *idk 4 seconds, (0 dps), while it shoots a beam for 4 seconds, (840 dps), which means a meltdown has an average dps of 420.
> 
> Note:
> Spectre's dps (according to Ilya's dps counter) was 680.

Shoot period of Meltdown is 3,5 sec. Cools period is 3,3 sec for cryofluid and 7,5 for water. Maybe also increase a beam time for cryofluid for 1-2 sec?
And about range is 26 would be enough? As I know Eclipse now shoot at 28. Maybe this would be good? It's would be less than Spectre's 32 range and it would outrange Reign end Eclipse.
And about dps. Spectre have a 680 dps and boosted by cryofluid 1,45 will be 980 dps. But, Spectre also could be boosted by overdrive while Meltdown can't be boosted. So Spectre's dps is above 2000. Even 1 Lancer boosted by overdrive and cryo have 450 dps.
Meltdown need a buff. As downside after buff I propose to increase liquid consumption 30 -> 60.

**Comment by OnyxFinger** [comment]
meltdowns aren't bad because of armor, they're bad because of the surge ammo buffs, specter buff, and FS being a thing, which are all more proper things to use than a meltdown, as they do the same job a meltdown could, but better

**Comment by JrTRinny** [comment]
Anuke buffed the Meltdown partially (half of the list above) in the last commit, so I count as a success, great work everyone!

**Comment by notMEEPoffaith** [comment]
>a meltdown has an average dps of 420.

haha funni number
