### ISSUE TITLE
equipable weapons for your mech

### ISSUE THREAD

**Issue by thompson8964** [Anuken/Mindustry-Suggestions#283]
**Describe the content or mechanics you are proposing.**

your personal mech should be able to pick up and use weapons other than it's defualt without swicthing to a different mech

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

it will provide more options for killing enemies in the early game. i think you should be able to make theses weapons with a personal crafting station, since you wont be needing lots of them, unless perhaps you would need them to build more mechs

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
No. Mechs had equippable weapons in Classic, and it was a mess.
