### ISSUE TITLE
Stats bonus

### ISSUE THREAD

**Issue by ImproperZ** [Anuken/Mindustry-Suggestions#2830]
### Describe the content or mechanics you are proposing.

Stats bonus on multiple cores should be an option in map creation and sandbox at least.The stats should be configurable like; flat dmg+ ,build speed , unit speed, core hp, unit cap
Additional stats added should be inversely proportional to the number of players.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Having additional stats will balance maps that should be played in multiplayer vs single player.
It will hasten game-play procedures with core capture option,(noticeable in massive maps with multiple enemy core).
Will greatly impact pvp; core capturing vs poly, quality units vs quantity units

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Better suited for a server plugin TBH.

Though can the game handle changing map settings on the fly + the sheer confusion that changing stat multiplers with player count brings.

**Comment by OnyxFinger** [comment]
I doubt the PvP impact would be this great...
