### ISSUE TITLE
Builder Units In Formation Can Allow the Commander Unit to "Build"

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#2831]
### Describe the content or mechanics you are proposing.

For Example, an Eclipse cant build but a nearby quad is near, presses G to get the unit in formation and alows the eclipse to build (but the quad is actually building and must be near)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To help with units that cant build (Dagger, Flare, and Risso Trees) while at battle able to build with its surrounding builder units, and you dont have to switch to another unit and distrupt formation, nor get your unit killed while doing so

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SomeonesShade** [comment]
Im willing to hear counterarguments since idk if there is something deeply wrong with it

**Comment by Sector171** [comment]
Indeed, 
It is sooo annoying, if you control a unit has the build ability like mega, and make a mixed-formation of units(can build and can't like horizon) you can build, and all units which can build will participate in any building process, but in the reverse case you can't (ex if you control zenith and make a formation has megas you can't build) which is really annoying.
If your formation has any unit that can build, you should be able to build, and all units in your formation that has this ability should participate.

**Comment by Humanoid-X** [comment]
Yes please
