### ISSUE TITLE
Configurable launching point

### ISSUE THREAD

**Issue by r4isen1920** [Anuken/Mindustry-Suggestions#2832]
### Describe the content or mechanics you are proposing.

It'd be nice if it's possible to configure where the loadout items are coming from, instead of choosing the nearest sector as the launching point of items.

**How it could be done:**
- a dropdown could be added or it would open the planet map to choose a sector from which item loadouts could come from; 
- choosing the current sector the player is in by default as a launching point; or
- launching to new sectors could be made so that the loadout will be based from all the stored resources across all sectors.

![screenshot](https://user-images.githubusercontent.com/43404913/128874943-687b16bc-2313-4f4a-b65b-b6b565f5da62.jpg)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

With this feature, it gives players more control on their loadout configurations and be able to take resources from sectors that has greatly more abundant with resources.

It doesn't necessarily give reason not to use **Launch Pads** but instead acts a way of being able to additionally configure loadouts when launching on new sectors, and not transporting resources on a *regular basis*.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
> choosing the current sector the player is in by default as a launching point

done already
only named sectors can be launched to from anywhere, numbered sectors can only be launched to from neighboring sectors

**Comment by OnyxFinger** [comment]
can confirm, this was done
you launch from the sector you are in, assuming that it fits the proximity requirements for launching

**Comment by r4isen1920** [comment]
Can you please tell which version specifically this feature works?

**Comment by r4isen1920** [comment]
> only named sectors can be launched to from anywhere, numbered sectors can only be launched to from neighboring sectors
Yes, I think this is the current way of how it's done by default. But the thing about this is that while, for example, you are in the **Desolate Rift** sector, have the **sector 124** (to the right of it) unlocked, and try to attack the right of that, you can only launch from **sector 124**. Unless you manually use **Launch Pads** and take items from the default launching point, instead of launching from where resources is not very limited, it is fairly compromising. Take into account that you have to be wary of being vulnerable against these sectors, it would be pretty challenging on its own to manage resources and, as soon as possible, attack.
