### ISSUE TITLE
More info on global situation

### ISSUE THREAD

**Issue by noncom** [Anuken/Mindustry-Suggestions#2834]
### Describe the content or mechanics you are proposing.

When other sectors are under attack while you are on a mission, add a separate UI that clearly indicates the situation and attracts the proper amount of attention taking into account the threat level and other factors, like:
- Display a list of sectors currently being attacked
- Display the alert level like green/yellow/red/red-blinking depending on the level/amount of threat/damage the current enemy wave is bringing,
- Show the progress of the enemy advance to the core, the amount of units and/or the rating of the units to be able to make some judgement about what is going on
- Have a button on each item of the list to quickly move to that sector
- Have the launchpads dropdown list the attacked sectors for quick assignment
- Have your "current" mission be displayed in the list as well since technically it's just another sector under attack and you might want to navigate/redirect to it in a quicker fashion
- Exclude the sector you are in from the list (so that if you're on a mission and nothing else is under attack there is no list visible)
- When more planets are added, also show the planet icon/name in the list item
- The list should be small and non-intrusive, maybe also having a minimized form with only planet/sector name and current threat level indicator
- Additional features like current resource production might also be added for display if this idea ever gets going at all idk

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

One big problem that I constantly encounter in the game is that there's not enough info on what's going on at the planetry scale while I'm on a mission:

- The notification of the fact that a sector is under attack is very weak and fleeting. If I was looking away at the moment it came and didn't hear the sound, I've lost it.
- Even if I know that there's a situation in another sector and check there periodically, it's very hard to judge what is actually going on. Like, I had a sector under attack and I checked it up there a few times, the defenses were strong, the waves were being destroyed before they even nimbled a block off the wall. At that point I had another threat on my current mission so I focused on that, leaving the other sector be because I saw it was ok. So, the next time I went to that sector, some minutes after that, there was only devastation. It was Fungal Pass, so it suffered an especially tragic fate: the passage of the enemy wiped out almost everything on the map.
- Similar situations keep repeating over and over: I keep finding myself being underinformed/having to track too much stuff that's hard to track operatively.
- On the planetary map itself the indication of events is also a bit weak, not too easy to spot, sometimes you have to roll the planet for a few seconds just to see where's that bell coming from.

The improvement of the UI on that part would allow to always be informed of the current situation, to measure and estimate the risks correctly, to not suffer the lack of information on current critical events.

It would also allow for tackling more interesting and complex situations in the future, effectively serving as a start for research into more sophisticated and coordinated player(s) operations and activity.

There **is** a mention of "Better UI" in Trello but it doesn't say anything specific so I thought I'd give some input on this one vector of UI. Like, more tools for managing/comprehending the macro situation.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Yes
