### ISSUE TITLE
Show illuminator colors on the map

### ISSUE THREAD

**Issue by OctoRocket** [Anuken/Mindustry-Suggestions#2835]
### Describe the content or mechanics you are proposing.

The illuminator's rgb values would control its color on the map screen.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Showing illuminator colors on the map would be a great idea because it would allow for more creativity to be able to be shown, as it would give an alternative to sorters for map screen art.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
I honestly don't know, is this feasible with the current system for map display?

**Comment by Bottinator22** [comment]
Does it have to be? If sorters work, this will probably work too

**Comment by Kyllingene** [comment]
The difference is that sorters have a set amount of colors (16), whereas an RGB light has 16777216 possible different colors, making it plainly impossible to account for each one; I may be wrong, and the map may already be capable of drawing arbitrary colors (checking with a mod that adds new items with new colors would be effective), but I think not.

**Comment by Bottinator22** [comment]
Changing the minimap to allow for this to work is a pretty simple thing I'd think

**Comment by itcannotbe** [comment]
But why would you change it just so that this would work?
