### ISSUE TITLE
Foreshadow’s unmitigated damage

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#2836]
### Describe what you would like changed, and why.

As of right now there is no way to stop foreshadow’s damage. Every other turret in the game has some sort of hard counter but the foreshadow does not. Right off the bat I would like to say I do not want a way to prevent foreshadow’s damage to units, but only to blocks. Unstoppable damage results in op turrets that need to be changed. (Look at V5 lancer for an example)

### Describe the changes you want to propose. Include possible alternatives.

There was a small (very large) argument in #Balancing on whether or not foreshadow should have a non unit counter. To keep with consistency and prevent unstoppable damage my personal opinion is that it should have a block counter. Here are some of the ideas thrown around:

1. Force projectors should block the foreshadow shot because it is a physical bullet ( it shoots surge)
2. Plast walls should block the damage ( it shoots a highly charged unstable element which results in a energetic shoot)
3. Remove its damage to buildings all together ( this will require a buff it’s damage to units to make up for this loss) ( it is designed to target units anyway)

These ideas are meant to be singular, not taken as one huge change, but as 3 ideas for 1 smaller change

**Comment by itcannotbe** [comment]
Foreshadows are meant to T5 killers, stop trying nerfing it.

**Comment by RealYeet** [comment]
Exactly, so I am trying to get rid of its ability to deal damage to buildings because that is its main purpose right now

**Comment by itcannotbe** [comment]
Also I think you really don't know how force projectors work, and what plastanium walls do.

And why would you make block damage 0? Heck even armor doesn't 0 out bullet damage.

**Comment by RealYeet** [comment]
I do know what force projectors do, I do know what plast about walls do. There is no way to stop the damage, that is my issue

**Comment by itcannotbe** [comment]
Also if you let your enemy build a foreshadow near your base, you  deserve to lose.

**Comment by RealYeet** [comment]
That is not the point, there is no counter. Remember how people kept on complaining how there was no way to stop lancer in v5, well now we have a v5 lancer except it deals more damage and has more range

**Comment by itcannotbe** [comment]
> That is not the point, there is no counter. Remember how people kept on complaining how there was no way to stop lancer in v5, well now we have a v5 lancer except it deals more damage and has more range

Plast walls blocks the piercing of the laser but the wall is still damaged by the laser.

**Comment by RealYeet** [comment]
Exactly, so what is the problem?

**Comment by Humanoid-X** [comment]
Foreshadow is an endgame turret bruh

**Comment by RealYeet** [comment]
And that gives it the reason to be game breaking how?

**Comment by OnyxFinger** [comment]
I think his idea is right
even though FS is an endgame turret, it wasn't made to be the great I-place-it-there-now-you-can't-go-there turret

**Comment by Kyllingene** [comment]
Is no-one going to mention how Foreshadow already deals less damage to blocks? Or was that removed?

**Comment by Kyllingene** [comment]
Hey, here's a thought: *counter their attacks*. The Foreshadow is expensive both during and after the build process, and it takes a long time both to build and to cool down between attacks; if you don't like their Foreshadow, shoot at it with your own. Sometimes, making something that forces you to strategize beyond "build big walls hahaha" is a good thing.

**Comment by OnyxFinger** [comment]
yeah I guess
but if FS was blocked by things like forcefields, it would help, since with many builders foreshadows are easily built, at least you get to tank 1-2 shots before starting to lose stuff

**Comment by RealYeet** [comment]
Here is a thought, how about a non unit counter to this turret, the issue is that once it is there, it is there, it will automatically target the highest health block, prioritizing turrets after units, then walls and other things

**Comment by RealYeet** [comment]
Also logic does not help

**Comment by oinkymoo** [comment]
a lot of people are failing to consider that foreshadows have use against buildings outside of pvp. foreshadows are really good at late-game turret push, especially when player-controlled, because you can simply delete enemy power, shields, coolant, and ammo. and you can do it from 30+ blocks away from the enemy frontline, where you won't be shot.

**Comment by Highfire1** [comment]
Specifically, in my experience in the .io attack server, you can cheese a lot of defences by getting a few megas and spamming menders then building a foreshadow (or even a surge wall w/ more hp and then a foreshadow) within enemy foreshadow range; 
 you can snipe all the enemy sources at will since the enemy foreshadows aren't able to kill the single mended foreshadow.

You could argue its a case of player control being overpowered but I still think its kinda cheesy when the alternative is to build a bunch of t5 and all the infrastructure that costs

(id support option 1 because shields look super cool and giving people more incentive to use em would be neat)

**Comment by OnyxFinger** [comment]
> Specifically, in my experience in the .io attack server, you can cheese a lot of defences by getting a few megas and spamming menders then building a foreshadow (or even a surge wall w/ more hp and then a foreshadow) within enemy foreshadow range;
> you can snipe all the enemy sources at will since the enemy foreshadows aren't able to kill the single mended foreshadow.
> 
> You could argue its a case of player control being overpowered but I still think its kinda cheesy when the alternative is to build a bunch of t5 and all the infrastructure that costs
> 
> (id support option 1 because shields look super cool and giving people more incentive to use em would be neat)

somewhat yes
