### ISSUE TITLE
Vaults and containers affect unit cap

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2838]
### Describe the content or mechanics you are proposing.

I am proposing that Vaults/containers connected directly to the core affect the unit cap. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

As of right now in the campaign there is no way to get your units above 24, while this is fine for larger units, there are often times where I wish I could get maybe 30-35 flares or daggers. I believe this should only affect T3 and below because of the size of the vaults/containers. The vaults/containers already increase the core's size and its item capacity.  Why not make it affect the last thing the core is used for, unit caps. This will allow for more smaller units which can be used for purposes either for non logic like increasing the effectiveness of an attack with daggers and maces, or logic proposes like having extra flares for wireless schems.  

The only reason I am making this suggestion is because the unit cap as of right now is to harsh. This seemed the best solution (maybe solution). The increase should not be that much, I am thinking that containers increase the cap by 1, and vaults by 2.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Maybe you should re-read the suggestion, the vaults and containers have to be connected to the core

**Comment by RealYeet** [comment]
And last time I checked, there is only so much space around a core

**Comment by RealYeet** [comment]
I fully support this suggestion, the unit cap is a bit harsh right now

**Comment by Bottinator22** [comment]
> That would require rebalancing the unit cap, meaning reducing the base unit cap so that vaults/containers can artificially increase it (to at or slightly above the original base unit cap). Vaults/containers are not hard to build, so this new mechanic doesn't actually challenge players in any way.
> 
> In the end, unit cap is determined by what's feasible for **performance and balance**, so just wishing for larger numbers is the wrong way to approach feature requests.

The game works just fine with a slightly higher unit cap. Late survival waves cause more performance problems than just a small increase in the unit cap.

**Comment by RealYeet** [comment]
From what I can tell, this is supposed to be an easy thing to do, the first challenge is finding the resources, like everything else in this game, so I really don’t see how this is different from anything else

**Comment by OnyxFinger** [comment]
> That would require rebalancing the unit cap, meaning reducing the base unit cap so that vaults/containers can artificially increase it (to at or slightly above the original base unit cap). Vaults/containers are not hard to build, so this new mechanic doesn't actually challenge players in any way.
> 
> In the end, unit cap is determined by what's feasible for **performance and balance**, so just wishing for larger numbers is the wrong way to approach feature requests.

what ? How is that bad ? just make higher tier units like T4s and T5s either stronger or easier to get to ~~by at least removing the phase cost on T4 recon~~
I don't see where this would even be difficult, to be honest

**Comment by RealYeet** [comment]
Maybe you should re-read the suggestion, it obviously is talking about the nucleus core

**Comment by RealYeet** [comment]
It never specified being only available to the nucleus core, but it does say that the max is 24. And this guy wants a way to increase that number. 24 is the number of the nucleus, and it is impossible to get over that number right now. (In camPAIN ofc)

**Comment by OnyxFinger** [comment]
> Um. You did forget that it's easier to vault/container the core than to freaking upgrade it in the first place. Bad idea.

actually, upgrading cores has more perks, like your core unit and storage capacity, and it's also not really worth doing in the first place.

**Comment by RealYeet** [comment]
And before Anuke reads this once and never again, the unit cap has no effect on performance, most attack sectors tend to spawn hundreds of units by round 35, a few extra flares won’t do much

**Comment by RealYeet** [comment]
The war zone is calm, the fate of the world is still uncertain
