### ISSUE TITLE
Make guardian HP bar show sum HP of all guardians

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry-Suggestions#2839]
### Describe what you would like changed, and why.

Currently, the guardian HP bar shows the health of whichever guardian has the lowest health. It's jarring when you see the HP bar decrease to nothing, then jump back up when that guardian dies and the bar displays the HP for a different guardian.

Over the course of a boss wave, the HP bar can jump back and forth many times; sometimes it looks gradual only because all the guardians are clustered together and are taking damage at approximately the same rate, but that is only an illusion of how it should actually function.

### Describe the changes you want to propose. Include possible alternatives.

It should show the sum of the health of all guardians, to be a more accurate and gradual display of your progress in defeating the guardians.

While this is not an ideal solution that shows you the health of every individual guardian simultaneously, it's better than the current implementation which hides a lot of info from the player. Individual HP bars for each guardian do not scale, as discussed in #2168.

**Comment by sup3r87** [comment]
correct me if i'm wrong, but this is already a thing in the v7 testing branch. the guardian bar shares the health of all guardians and even includes the units.

maybe make sure to check v7 first before you make suggestions

**Comment by Ineedause** [comment]
This is because once a guardian dies it no longer takes that guardian into the calculation, causing the jumping you see, it still takes the average however

**Comment by sup3r87** [comment]
> This is because once a guardian dies it no longer takes that guardian into the calculation, causing the jumping you see, it still takes the average however. _(Again, make sure to check patch notes and latest releases before making suggestions)_

aditionally, if it didnt take all units into calculation, the bar would drop to the bottom and jump back up, instead of jumping up before dropping.

**Comment by joshuaptfan** [comment]
> This is because once a guardian dies it no longer takes that guardian into the calculation, causing the jumping you see, it still takes the average however

If that's the case, that's also a bad way to display HP. It should be "sum of all guardian HP divided by sum of all possible guardian HP (including dead ones)", so that the bar will continue to decrease when a guardian dies.

**Comment by itcannotbe** [comment]
What if for some stupid reason in a custom game, wave timer is set to something stupid short and "boss" units are present in consecutive waves?

**Comment by joshuaptfan** [comment]
> What if for some stupid reason in a custom game, wave timer is set to something stupid short and "boss" units are present in consecutive waves?

I'm going to poke around the source to see if I can PR a change. (It's been a while!) But that's a great edge case to account for. The solution should be simple: when calculating the max HP of all guardians at the beginning of the boss wave, include the max HP of any remaining guardians from previous waves.

**Comment by Anuken** [comment]
> that's also a flawed way to display HP

I disagree. If you have a single boss left after several die, a health bar that is *nearly empty* is very deceptive.

**Comment by sup3r87** [comment]
> > that's also a flawed way to display HP
> 
> I disagree. If you have a single boss left after several die, a health bar that is _nearly empty_ is very deceptive.

(this has been suggested before) maybe it's just a good idea to show the amount of health left of all guardian enemies (or something like that) on the bar. that way you can see how much health stuff actually has, and when the bar goes back to full (or jumps back up) it's less deceptive.

**Comment by Anuken** [comment]
> maybe it's just a good idea to show the amount of health left of all guardian enemies

and that's already what it does...?

**Comment by joshuaptfan** [comment]
> maybe it's just a good idea to show the amount of health left of all guardian enemies (or something like that) on the bar. that way you can see how much health stuff actually has, and when the bar goes back to full (or jumps back up) it's less deceptive.

A large, constantly-changing number is hard to read, and not the ideal way to convey this info.

However, I have a new idea that didn't occur to me in #2168's discussion, is to show individual health bars for every guardian, concatenated together same as the current combined health bar. Previously, I said that there needs to be a fixed size gap between the health bars, but there doesn't. They can be gapless, and just alternate between 2 or 3 shades of red to indicate that each segment is for a different guardian.

This way, when the health bar jumps when a guardian dies, all the remaining color-coded? shade-coded? health bars will expand a little, conveying that the bar is displaying health only for remaining guardians.

**Comment by sup3r87** [comment]
> > maybe it's just a good idea to show the amount of health left of all guardian enemies
> 
> and that's already what it does...?

no, i mean the actual numerical value of the health remaining. for example, if two units spawn that both have 32000 health, there would be "64000" under "guardian" on the bar.

>A large, constantly-changing number is hard to read, and not the ideal way to convey this info.

well, plenty of other games show enemies's health in numeric value, and there is no issue reading it. even if the number "constantly changes" you can still tell there's around 30,000 health left, because the 3 at the start is still. countless games show numbers and have no issues with them.

>However, I have a new idea that didn't occur to me in #2168's discussion, is to show individual health bars for every guardian, concatenated together same as the current combined health bar. Previously, I said that there needs to be a fixed size gap between the health bars, but there doesn't. They can be gapless, and just alternate between 2 or 3 shades of red to indicate that each segment is for a different guardian.

this is interesting, but it might be hard to make the bar make sense if you have lots of units crammed on the same health bar.

**Comment by itcannotbe** [comment]
An alternate would to make the bar countable. Like put some marking that would indicate 1k and 5k?

~but mods you say? Sush now, I don't care about your 1M modded unit health~

**Comment by sup3r87** [comment]
> An alternate would to make the bar countable. Like put some marking that would indicate 1k and 5k?
> 
> ###### ~but mods you say? Sush now, I don't care about your 1M modded unit health~

i feel like theres just no need. countless games display number bars, and no matter how high the health or how fast the number is changing you can always read it. because its not the first three digits that count, its the 4th and 5th ones, which move a lot slower. to say a number on the bar would be hard to read is denying normal game design practice since the invention of the health bar

**Comment by MrDuck557** [comment]
If you want a pr tell me where's the boss bar code

**Comment by joshuaptfan** [comment]
[core/src/mindustry/ui/fragments/HudFragment.java](https://github.com/Anuken/Mindustry/blob/9111860fcec9af1309548f91fbfeeb04cbeb73b7/core/src/mindustry/ui/fragments/HudFragment.java#L306)
[core/src/mindustry/ui/Bar.java](https://github.com/Anuken/Mindustry/blob/9111860fcec9af1309548f91fbfeeb04cbeb73b7/core/src/mindustry/ui/Bar.java)

It's gonna take some serious digging into how the bevels and shadow are drawn, I'll look more carefully soon and update this comment with my findings.

**Comment by MrDuck557** [comment]
as expected, only one color is supported per element

**Comment by OnyxFinger** [comment]
> A large, constantly-changing number is hard to read, and not the ideal way to convey this info.

this is why people don't read the precise number, but an approximation based on the amount of thousands or hundreds that are in it

**Comment by joshuaptfan** [comment]
After investigation, the multicolored health bar solution looks very difficult.

Something more feasible would be to overlay thin vertical lines on the health bar (I'm thinking in a slightly darker shade of red to not interfere with text readability) as "borders" between each guardian's individual bar segment. Challenges:

* Rendering the lines under the bar text
* Truncating the lines so they don't go outside the bar at the corner bevels

**Comment by GitHubUser-B** [comment]
> > that's also a flawed way to display HP
> 
> I disagree. If you have a single boss left after several die, a health bar that is _nearly empty_ is very deceptive.

You are showing up more often!

**Comment by hello-hello-there** [comment]
Maybe each time there are 0 guardian units, it should reset the 'total health var' of all guardians present, dead or alive. Then, it should take the remaining health of all said guardian units, and divide by the 'total health var'
Or, it should keep an index of all guardian units present since the last time there were 0, and find the 'total health var' since then from that index, and find the 'remaining health var' from the index, and divide 'remaining health var' / 'total health var' = fraction of bar filled
