### ISSUE TITLE
satalites

### ISSUE THREAD

**Issue by thompson8964** [Anuken/Mindustry-Suggestions#284]
**Describe the content or mechanics you are proposing.**

add VERY expensive satalites that can provide free power or resources. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

good for late game power and resource generation

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
Free power and resource? No.

**Comment by thompson8964** [comment]
but its REALLY expensive...

**Comment by KonradGA** [comment]
This should then be a part of a mod instead. Because it could be nice to have for some gameplay. But should not be a part of the main game.

**Comment by Anuken** [comment]
Satellites are already on the Trello, although they won't work as described here.
