### ISSUE TITLE
Constructable payload cores

### ISSUE THREAD

**Issue by Sh1penfire** [Anuken/Mindustry-Suggestions#2840]
### Describe the content or mechanics you are proposing.

Buildable payload cores that take longer than they would normaly to be built inside a special payoad constructor, which could then be carried with a t4/t5 to another location on the map with a rule to enable and disable core building, and a core cap. Posibly adding a block reconstructor to help with the core upgrades.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This new feature would help gives players something to do mid game with their excess resources, allow for the game to get harder and open up new strategies around remote core placement, as well as fast travel without teleporters or mods. It could even interact with core capture in interesting ways.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
In short:
buildable core
that you need at least quad for

**Comment by itcannotbe** [comment]
If I correctly, buildable cores was a scrapped Idea some time ago.

**Comment by OnyxFinger** [comment]
>  fast travel without teleporters or mods.

that's litterally a mass driver's job
