### ISSUE TITLE
Customiseable spawngroup items and effects

### ISSUE THREAD

**Issue by Sh1penfire** [Anuken/Mindustry-Suggestions#2841]
### Describe the content or mechanics you are proposing.

I'd like to ask that we get a way to customize the effect or items that units can spawn with using the map editor, without any mods.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would open up new possibilities for map makers, and generally allow those who know what they're doing to implement more interesting waves. A few examples I had were units pre-frozen on ice maps, units that spawn in waves, and carry ammo to a super weapon via logic(This is getting more into modded, but I think a ripple or a foreshadow could achieve the same effect for newer players), pre-loaded flammables or explosives on flares/crawlers, or just disarming the unit so they're friendly :D

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GitHubUser-B** [comment]
Congratulations! You are a very rare example of suggestions that were accepted by Anuken!
