### ISSUE TITLE
Unit Unbind

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#2843]
### Describe the content or mechanics you are proposing.

Add a unit unbind in logic which is the opposite of unit bind

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I know unbundling a unit is simple with a single jump parameter and a switch, but it often takes 30 seconds to 3 minutes( my personal record) for units to unbind, adding this will force said unbind so we don’t have to wait extended periods of time. 

A good example of this is when you call polys to a processor with a switch, this logic is made to prevent polys from suiciding themselves, but now you need the polys to defend the next wave in 15 seconds. Flipping the switch is not fast enough because the polys take way to much time to realize they are un bound, and your wall is torn to shreds and you lose the sector.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
units continue to do nothing for 6 seconds after recieving a command, if they remain inactive for longer you should submit a bug report

**Comment by RealYeet** [comment]
Thanks for the info, I will have to file a report once I am up to it

**Comment by Hexrotor** [comment]
Good idea, it's useful for me and may make logic running better.
