### ISSUE TITLE
Ice tile

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2844]
### Describe the content or mechanics you are proposing.

Ice, which is essentially the same ice from snow and ice tile, but in the ore layer, so you can add it in any type of tile.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More liberty in maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OAtobaAzul** [comment]
> Why would we need ice on the ore layer? Is it transparent so you can see the stuff underneath? Would it prevent ores from being placed there?

To be able to do this, but with any tile.
![image](https://user-images.githubusercontent.com/85000121/129266384-d887bfad-8a65-4a32-8a92-c361a5136e5e.png)

**Comment by OnyxFinger** [comment]
> > Why would we need ice on the ore layer? Is it transparent so you can see the stuff underneath? Would it prevent ores from being placed there?
> 
> To be able to do this, but with any tile.
> ![image](https://user-images.githubusercontent.com/85000121/129266384-d887bfad-8a65-4a32-8a92-c361a5136e5e.png)

so, more like cracked ice

**Comment by OAtobaAzul** [comment]
Yeah I worded it poorly.
