### ISSUE TITLE
Search bar for maps

### ISSUE THREAD

**Issue by LtMZ1** [Anuken/Mindustry-Suggestions#2847]
### Describe the content or mechanics you are proposing.

A search bar for the editor and maybe even one for custom games

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Some players have pages and pages of maps, and sometimes it's hard to find a specific map.
A search bar would make searching for a specific map easier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I agree

**Comment by JrTRinny** [comment]
there's a pull that add this feature found as earliest as May 2020
