### ISSUE TITLE
logic: get current wave num

### ISSUE THREAD

**Issue by BlackDeluxeCat** [Anuken/Mindustry-Suggestions#2848]
### Describe the content or mechanics you are proposing.

Add a method to get map's **current wave number** in logic coding. 
May it be "sense @.wave" or an op?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Current wave can be an important trigger as power void, item source etc. It should provide more functions for Crux in survive map, especially survive-pvp maps. 

_Also, will sense @.shield be available?_

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
maybe `@wave` as an internal variable like `@thisx`
