### ISSUE TITLE
How can I open this without cmd windows?

### ISSUE THREAD

**Issue by dayo05** [Anuken/Mindustry-Suggestions#2849]
### Describe the content or mechanics you are proposing.

Now version make output on console and I cannot found way to hide it.
Is able to make hide console? I want to see only game GUI, not console CLI
For example, Minecraft which is made with Java is not launching console

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Less window to execute

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
If English is not your first language, that's understandable, but this is somewhat hard to read.

However, I don't see why the console is opening; are you using the Steam version, or the [itch.io](https://anuke.itch.io/mindustry) version? Or, are you using a completely different version? If you aren't using either the Steam or itch.io versions, then we can't help you.

**Comment by Bottinator22** [comment]
You also should've posted this as a bug, not a suggestion.

**Comment by LeoSko** [comment]
If you start the game from `.bat` file then you need to use `javaw` instead of `java` to be able to hide CLI.
Your bat file would look like this:
`start javaw -jar Mindustry.jar`

**Comment by Phinner** [comment]
> 
> 
> If you start the game from `.bat` file then you need to use `javaw` instead of `java` to be able to hide CLI.
> Your bat file would look like this:
> `start javaw -jar Mindustry.jar`

Oh, I was looking for something like that too, thanks. :^)
