### ISSUE TITLE
Terraforming tech

### ISSUE THREAD

**Issue by KonradGA** [Anuken/Mindustry-Suggestions#285]
**Describe the content or mechanics you are proposing.**
I would really want to be able to terraform the map i am playing on. example spredding more spore on the map or clean out shale

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Being able to move where water flows and what is under your buildings makes it possible to build more optimized structures. And gives the player the option to turn a map build to be chaotic to follow the users demands.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This is already on the Trello.
