### ISSUE TITLE
segmented unit destruction 

### ISSUE THREAD

**Issue by spongeman2** [Anuken/Mindustry-Suggestions#2850]
### Describe the content or mechanics you are proposing.

the ability for peices of units to be destroyed individually and for damaged modules to have decreasing efficiency, such as the right cannon of the reign, or the leg of a arkyid, to allow for more flexible strategy and combat

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this will allow people to specificly destroy parts of units that give them trouble and will add a bit more realism to the way battles are fought

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
realism in not an excuse to add something in an unrealistic game. though this would definitely require such significant restructuring of the current combat system that its most likely infeasible

**Comment by oinkymoo** [comment]
would be cool tho

**Comment by itcannotbe** [comment]
Let's start it of by saying, More real =! More better.

Also since unit repair is a thing, the concept of unit parts getting destroyed and gets reattached is going to be stupid.

Again, More real =! More better.

**Comment by spongeman2** [comment]
ok sorry
