### ISSUE TITLE
Always respawn from the best core possible

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2851]
### Describe the content or mechanics you are proposing.

I've played a bit of multiplayer, and noticed that on multi core maps I keep respawning at a Shard near me, but not at a Nucleus just a few blocks further. It makes sense to respawn with the best ship possible, not the nearest.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Saves time to manually find and ctrl click the higher tier core. Makes the player always spawn with the best availeable ship.

If this is already added, then it must be a bug, I played on the CN attack server at the time, so it might just be something they had.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Probably a bug. I usually spawn at the core with the highest tier ship whenever I respawn, at least in v129.2

**Comment by EclipsePlays** [comment]
Same, idk for you though

**Comment by IIINSTINCT** [comment]
Huh strange this have been implemented already

**Comment by BorisA11** [comment]
> Huh strange this have been implemented already

Then it is likely just a bug with the server. Anyway, Anuke must've noticed by now, so I'll close it.
