### ISSUE TITLE
Some blocks' animations

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2852]
### Describe what you would like changed, and why.

I remember that in previous versions, when the power is not enough, animations of some blocks like projector, water extractor will be slower, but now they aren't. I dont know whether my game has the bug or Anuke made this.
![GIF-210814_221241](https://user-images.githubusercontent.com/45112661/129449122-1756c143-9258-463d-bd94-4ea62fbc0dc5.gif)

### Describe the changes you want to propose. Include possible alternatives.

It's not bad to show this small change, why not?

**Comment by Hexrotor** [comment]
And this, if the "pump speed" progress bar is always full, it makes no sense.
![2021-08-14 23 23 24](https://user-images.githubusercontent.com/45112661/129451264-f346f046-e5d8-4f83-9934-3c07f5d7ff32.jpg)

**Comment by itcannotbe** [comment]
> And this, if the "pump speed" progress bar is always full, it makes no sense.
> ![2021-08-14 23 23 24](https://user-images.githubusercontent.com/45112661/129451264-f346f046-e5d8-4f83-9934-3c07f5d7ff32.jpg)

Because it's outputting approximately 1.3/s

And so what will happen when it's overdriven? The pump speed exceeds it's display bar?

**Comment by Hexrotor** [comment]
> Because it's outputting approximately 1.3/s
> 
> And so what will happen when it's overdriven? The pump speed exceeds it's display bar?

I think it should display like the drill speed:
![2021-08-15 00 27 50](https://user-images.githubusercontent.com/45112661/129453265-0c5c46ad-a811-4b15-abe4-c9ac1fff2bc8.jpg)

You will find that the max value of drill's speed bar is dynamic, also when it's overdriven.

**Comment by itcannotbe** [comment]
Ah yes. I think you forgot that liquids are outputed once per tick, unlike items.

**Comment by Kyllingene** [comment]
Can we please get back on track? Look at the actual issue.

**Comment by itcannotbe** [comment]
> Can we please get back on track? Look at the actual issue.

LOL. I actually thought that was the issue. LOL

**Comment by Hexrotor** [comment]
Fixed in the latest build
