### ISSUE TITLE
Color code improvements using common existing systems

### ISSUE THREAD

**Issue by hiltonjanfield** [Anuken/Mindustry-Suggestions#2854]
### Describe the content or mechanics you are proposing.

Reduce the number of characters it takes to change colors on message blocks, etc.:

**Preferred: Recognize short-hand RGB colors, as is done in CSS.**
- When the game finds a 3-character color code (e.g. [#E80] ), this should be recognized as a shorthand RGB and expanded to #EE8800. Currently the game just takes it as the first part of a full 6-character code: [#E80] is equivalent to [#E80000].
- This same mechanic exists in CSS and numerous other places where RGB color codes are used, so is familiar to many.
- Even better if we can drop the # and just recognize any 3-character code that has valid HEX characters, like [E80].

**Another way: Add short-hand color codes**
A fixed list of single-character codes that equate to all the standard colors currently available. The downside to this is the more obscure colors will be harder to remember. A..Z, 1..0 will cover all existing standard colors:
- Use first letters for common colours, [r]ed, [g]reen, [w]hite, [c]yan, etc.
- Use second letters for conflicts, e.g. g[o]ld, gr[e]y, and so on. 
- The only one I would break this rule for is blac[k] as K is often used to refer to black. 
- Some colors will end up being numbered, for example the letters in SKY would all be used by scarlet, black, yellow, so could be [1].

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More colors can be used in limited space, for advanced processor scripts which use message blocks to display status could make better use of color, as message blocks have a somewhat limited maximum length.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I would like to know why ItCannotBe reacted with thumbs down, I assume it's because of how the game is designed, but I'm kinda dumb
He did not participate so I can't ping him

**Comment by GitHubUser-B** [comment]
> I would like to know why ItCannotBe reacted with thumbs down, I assume it's because of how the game is designed, but I'm kinda dumb
> He did not participate so I can't ping him

True, this guy is salty as the pile of salt in my photo

**Comment by GitHubUser-B** [comment]
> I would like to know why ItCannotBe reacted with thumbs down, I assume it's because of how the game is designed, but I'm kinda dumb
> He did not participate so I can't ping him

Dislike neutralized, but how do you know he's the one who disliked that?

**Comment by OnyxFinger** [comment]
> True, this guy is salty as the pile of salt in my photo

I don't find him very salty
