### ISSUE TITLE
Unit Shield Limit Multiplier 

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2855]
### Describe the content or mechanics you are proposing.

Shields in survival goes insane as the game continues to progress. At wave 200, a flare that's set to increase shields by 10 will have a total amount of shield of 2000 hp. Too irrational for a 75 hp unit. At least make a shield limit multiplier in the map editor that's always set to either 25x the hp of the unit, or infinity by default. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This could help the long term survival games "cope up" with the enemies, because the longer the game progresses, the harder they become. This can avoid flares having to be shot by foreshadows **2 times** before dying. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
But it's survival, the game's goal is for you to lose. Not for you to survive endlessly.

If you want to limit shield, what are you proposing instead to force game over?

**Comment by EclipsePlays** [comment]
It's a mapmaker's choice.  You can limit shields but spam stronger and bigger units. It's just irrational that Flare from wave 1 to infinity with +10 shields also stack up to infinity.

**Comment by random-guy1285** [comment]
Technically you could make it a new set of flares that don't increase shield, but this is just for QOL so I agree

**Comment by itcannotbe** [comment]
> Technically you could make it a new set of flares that don't increase shield, but this is just for QOL so I agree

And set the shield value and not increase it.

Also who's sane enough to spawn flares at late game.

**Comment by OnyxFinger** [comment]
> This could help the long term survival games "cope up" with the enemies, because the longer the game progresses, the harder they become. This can avoid flares having to be shot by foreshadows 2 times before dying.

Also PvP... Shield is pretty much useless in PvP, if there are modifiers for it I would love to use them and make shield actually worth-while
