### ISSUE TITLE
About schematic

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2856]
### Describe the content or mechanics you are proposing.

Now schematic files are named by unix time like `1629089033130.msch` and saved in game's data folder. If you import a schematic from a file or clipboard that one already in the game(or same name), it will not have any notice like "A schematic by that name is already exists".
It causes a problem: if you export your game data to a file and import it to another game client, which already has some same schematics but have different file names in data folder, all of them will be display at the schematic list, though some of them are the same.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I have two ideas:

1. Add name check for importing schematic, when conflicting, show a notice and overview with three button: "replace", "rename" and "cancel"(or add a number after the name directly).
2. Save hash infos of schematic files to game data(or named files with hash directly). When importing the data, verify file hashes so that can skip to copy the same schematic files.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Honestly unrelated, but it would be cool if it was possible that the files on the computer were named the same way they were in the game.

**Comment by Hexrotor** [comment]
> Honestly unrelated, but it would be cool if it was possible that the files on the computer were named the same way they were in the game.

I didn't mean change file name, I mean the name data in game.

**Comment by RealYeet** [comment]
I know, but it would still be nice

**Comment by Hexrotor** [comment]
> I know, but it would still be nice

Well, actually some specific character in file name may make the list not work or even cause the game crash.

**Comment by OnyxFinger** [comment]
You used the suggestion template like an issue template lol (kinda funny, I'm not an angry dude trying to close this for only the template like over half the people here lmao)
I guess I like this idea

**Comment by Humanoid-X** [comment]
Hmm yes
