### ISSUE TITLE
UI modding

### ISSUE THREAD

**Issue by supermegaOriginal** [Anuken/Mindustry-Suggestions#2857]
### Describe the content or mechanics you are proposing.

I know it is hard. But if you have time and want this to happen, make UI modding a thing. I know you want to make a new UI. Some want the old one some want to make their own and you want another one.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You can make your own UI or use the old one, make it simple, complex, or in a way that fits your needs.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
a lot of people have left a thumbs down but none of them have explained why

**Comment by Kyllingene** [comment]
This sounds great, except for the huge amount of effort (even making hardcoded small changes to the UI is a pain); but what happens when two mods conflict, and both need a custom UI to function? Or how about when two mods both add a button to the default UI?

**Comment by itcannotbe** [comment]
Can't mods already modify the UI?

Also a JSON-able approach to UI modification is out of the question.

**Comment by Anuken** [comment]
> Can't mods already modify the UI?

Yes, mods already can (and do) modify the UI. It's not hard. I don't really understand this suggestion.
