### ISSUE TITLE
Tank

### ISSUE THREAD

**Issue by Enzo54623** [Anuken/Mindustry-Suggestions#2859]
### Describe the content or mechanics you are proposing.

I want a new unit chart. The Tank.
Its an ground unit.
I propose the new mechanic of a new button: the Mine Layer Button to tier 5 tank. And when the tank is too close to the enemy will pierce the enemy doing CRITICAL damage.
Ps: critical damage is not chance, just an type of "buff" when close to the enemy.
And when its far, from tier 3 to 5, the bullet of the tank that did not pierce the enemy will "explode" doing a little more damage to close enemies.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would add new cool things:
A new "leg", the conveyor-like leg.
New effects: dirt trail, new shoot effects, like the fire from the shooting animation represented, 
And 3 new unit guns: Missles, Tank Barrels, And Energy Tank Barrel.
+1 new unit ability: the Mine Layer Ability. Lays mines down, doing high damage.
Ps: the fourth and fifth tier are bigger than that in the art.
Good day.
Ps2: i would like if you add their names as said:
1 tier tank: Duot
2 tier tank: Monosion
3 tier tank: Explosive
4 tier tank: Smasion
5 tier tank: Minemash
![2021-08-16_22 09 00](https://user-images.githubusercontent.com/75813704/129658379-fc451ae8-1d79-4fd7-957c-0f4ac3bb91b7.png)
![2021-08-16_22 09 37](https://user-images.githubusercontent.com/75813704/129658382-3b4c298a-6beb-4ee9-b2c5-4cf624e16d4c.png)
![2021-08-16_22 09 30](https://user-images.githubusercontent.com/75813704/129658385-947824b5-5fca-4c14-9cbd-084ad0ab97e7.png)
![2021-08-16_22 09 51](https://user-images.githubusercontent.com/75813704/129658387-c4170bab-893a-461e-a64e-4e749b9e915c.png)
![2021-08-16_22 09 44](https://user-images.githubusercontent.com/75813704/129658388-1076ab1b-8b8b-4896-a527-976233503037.png)
Thank you. Have a good day.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What niche does this fill again?

**Comment by itcannotbe** [comment]
Template:
### If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

OP: _proceeds to not mention any_

**Comment by Bottinator22** [comment]
Mindustry doesn't need tanks or cars. I believe these kinds of vehicles have already been suggested multiple times before...

**Comment by Enzo54623** [comment]
Okay. Have a good day.

Em ter, 17 de ago de 2021 00:42, Bottinator22 ***@***.***>
escreveu:

**Comment by RealYeet** [comment]
Anuke be like: Oh wow, no one has ever suggested cars before, such a revelation, let me add cars right now

**Comment by Enzo54623** [comment]
I already got it

Em ter, 17 de ago de 2021 01:43, RealYeet ***@***.***>
escreveu:

**Comment by IIINSTINCT** [comment]
Man honestly people better stop not suggesting new units 
(because the community will just dislike the idea and anuke would less likely to add it since it is not his own idea stated on #development)

**Comment by GitHubUser-B** [comment]
> Man honestly people better stop suggesting new units
> (because the community will just dislike the idea and anuke would less likely to add it since it is not his own idea stated on #development)

The community doesn't like the idea? I'm the one who doesn't like the community! A guy called XxxsniperxxX or similar name was "lynched virtualy" and humiliated just for complaining about a level! It takes away my desire to play this game!

**Comment by Enzo54623** [comment]
Thank you. A think that dont do much sense to me, is that ships are in the
game but not a tank, or a car. L

Em ter, 17 de ago de 2021 11:13, GitHubUser-B ***@***.***>
escreveu:

**Comment by Bottinator22** [comment]
What else would you have for navy?

**Comment by Humanoid-X** [comment]
@GitHubUser-B ~~Stop playing then nobody forced you~~

**Comment by Kyllingene** [comment]
> A guy called XxxsniperxxX or similar name was "lynched virtualy" and humiliated just for complaining about a level!

Correction: A guy called XxxsniperxxX or similar name was "lynched virtualy" and humiliated for complaining in a highly childish way (not saying they are childish, simply that the particular complaint was childish) about a level, then went on to destroy any hopes of redeeming themself in the issue by insulting everyone who commented personally in yet more childish ways, even after several people had shown proof (including a YT video) that the level was not as hard as they were making it out to be. Note that everything that they said is only known to me through other peoples' quotes; they proceeded to delete every single comment they made on the issue. Whether or not the level was hard is not at question; it's that they seemed to have a sudden and temporary lack of mental faculties.

**Comment by buthed010203** [comment]
Instead of suggesting that anuke add a new unit tree then being surprised when ppl dont like that idea, why not just make a mod that does this?

**Comment by Enzo54623** [comment]
I mean, i dont know how to code, i don't know who to code, i don't know
what program i use to code..

Em ter, 17 de ago de 2021 13:51, buthed010203 ***@***.***>
escreveu:

**Comment by GitHubUser-B** [comment]
> @GitHubUser-B ~Stop playing then nobody forced you~

~No~

**Comment by GitHubUser-B** [comment]
> > A guy called XxxsniperxxX or similar name was "lynched virtualy" and humiliated just for complaining about a level!
> 
> Correction: A guy called XxxsniperxxX or similar name was "lynched virtualy" and humiliated for complaining in a highly childish way (not saying they are childish, simply that the particular complaint was childish) about a level, then went on to destroy any hopes of redeeming themself in the issue by insulting everyone who commented personally in yet more childish ways, even after several people had shown proof (including a YT video) that the level was not as hard as they were making it out to be. Note that everything that they said is only known to me through other peoples' quotes; they proceeded to delete every single comment they made on the issue. Whether or not the level was hard is not at question; it's that they seemed to have a sudden and temporary lack of mental faculties.

Seriously? OK then

**Comment by GitHubUser-B** [comment]
> Why not just make a mod that does this?

I knew it! I talked about this in another request!

**Comment by Kyllingene** [comment]
> > Why not just make a mod that does this?
> 
> I knew it! I talked about this in another request!

Wow! It's almost as if we don't need new chaotic ground units, but they would still be cool to have! If only Anuke had spent tons of time to implement a system making it easy to make and share changes to only those who want them!

**Comment by Enzo54623** [comment]
Thanks

Em ter, 17 de ago de 2021 17:05, Kyllingene ***@***.***>
escreveu:

**Comment by GitHubUser-B** [comment]
> > > Why not just make a mod that does this?
> > 
> > 
> > I knew it! I talked about this in another request!
> 
> Wow! It's almost as if we don't need new chaotic ground units, but they would still be cool to have! If only Anuke had spent tons of time to implement a system making it easy to make and share changes to only those who want them!

That's not it, I was trying to say that this group (which also has a lot of mod creators) all the time they use mod as an excuse to not add anything to the game, looking like a conspiracy to get people to download their mods!

**Comment by buthed010203** [comment]
??? Tanks arent at all suited for vanilla so it makes sense to put them in a mod, its not like people get anything from you downloading their mods lol

**Comment by GitHubUser-B** [comment]
> ??? Tanks arent at all suited for vanilla so it makes sense to put them in a mod, its not like people get anything from you downloading their mods lol

It's not just that suggestion.

**Comment by Bottinator22** [comment]
People suggest mods because they believe your suggestion doesn't fit in vanilla, and is better off as part of a mod

**Comment by EclipsePlays** [comment]
> I want a new unit. 

tf?

**Comment by GitHubUser-B** [comment]
> People suggest mods because they believe your suggestion doesn't fit in vanilla, and is better off as part of a mod

Always?

**Comment by Kyllingene** [comment]
> Always?

Exceptions arise, as *always.*

**Comment by GitHubUser-B** [comment]
> > Always?
> 
> Exceptions arise, as _always._

What?
