### ISSUE TITLE
Skins in the game

### ISSUE THREAD

**Issue by TimurMindustry** [Anuken/Mindustry-Suggestions#286]
**Describe the content or mechanics you are proposing.**

I would like to add skins to the main fur in the game.
Regular skins could be obtained for free or for certain resources in the company (resources in the company began to depreciate) Animated skins will cost a lot of money.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** 

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
install **deltanedas/vbucks**
`Mechs.dart.region = Core.atlas.find("john-wick")`

**Comment by Anuken** [comment]
Nah.
