### ISSUE TITLE
A New.. Gamemode? Mechanic? Content?

### ISSUE THREAD

**Issue by MGamer170** [Anuken/Mindustry-Suggestions#2860]
### Describe the content or mechanics you are proposing.

Gamemode is called Charge the Core (CTC)

(Note: Can't think of a better name for that.)

Victory Conditions: 
>Charge The Core to fire shots on the Opponents Cores/Core in PvP or Attack if Griefing is Banned.

>Launch the Core in Survival via filling it with Power to the Max.

>Destroy the Enemy's Core in PvP or Attack If Griefing is Allowed.

Concept: So, the concept was you landing in a custom core that functions as a battery and a core (I will name it Core: Capacitor, but it could be named differently.)

-Suggestion: May wanna Increase the Cost of Reactors, because they might spam a lot of cheap reactors.

-=Features=-

-Max power capacity can be edited in the custom game settings.

-There is a setting that allow or ban you from destroying your enemy's buildings.

-You could make it so that you try to survive waves similar to survival while charging up the core and once you charge it up, an animation occurs where your core flies off (Think of it like a core launching).

-And there's another version of CTC that has you charging up another core that also functions as a weapon that targets all the enemy cores in Attack

-A Big No Build Zone around each Player's Core in PvP

-The Core acts like a One-Way Battery, Basically, If the Power is at a Deficit, it wil not give any Power, at all. (But it can be changed in a setting that allows the Core to work like a Normal Battery)

-I call this one "Core: Annihilation" or "Core: Eradication" to fit since Eradication seems to be used a lot in this game

-The beams are like Foreshadow Shots.

-During the charge-up period you could fire the beam via Controlling the Core and Clicking 3 Times on a Unit.
 -But it drains a good amount of power and has limited range.  (Range can be Edited.)
  -But it can kill a T4 in a in a shot, however, it can only target one unit.

-You can disable the beam in the charge-up period via custom game settings.

-Also, There needs to be 2 Core: Annihilation/Eradication that are different teams to be PvP (There can be more than 2 Teams having a Core: Annihilation/Eradication) and 1 to be Attack.

-Batteries are Allowed, but they can only Store Power if their power lines are not connected to the Core. When Powered Batteries are Connected to the Core, They will start giving their stored power to the Core, Anuke, Decide if them giving power to core is instant or slowly draining

-And make it so that the power capacity is very high that several Impact Reactors will take a long time charging up the Core if the Late-Endgame Reactors are allowed.

I know you can make something similar in Mindustry except for that Special Core in Attack and PvP,
but it would require a big space for those Large Batteries and that depends on the power capacity you want to choose,
and also needed to be protected from stray bullets.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Power in Mindustry is basically, goes like this, You put down a generator, you give no mind to power except when it's in deficit or you putting some batteries down and you connect them to Factories, Turrets, and Other Stuff. This Gamemode, (I like to call it that) is basically, to give it a gamemode centered around Power.

I think, that this gamenode would make them careful at using it,

Do they want more resources for other stuff they want to build? But that would slow their progress down a bit when building Power Consuming Buildings. Especially Schmatics That require a LOT of Power. Do they want to focus on Defenses when facing another player in PvP or trying to Survive in Survival? That's fine but that's giving their opponent more time to upgrade their Reactors or Advance their Tech in PvP.

Build More Reactors? That might speed up their Progress, but that will waste Time, Resources, and Space, might even be wasting Resource Deposits that could be used for more precious stuff.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kryvytsky** [comment]
Doesn't it all possible already in multiplayer? I play on servers and they alternative game modes, they just not implemented on single.

**Comment by OnyxFinger** [comment]
> Doesn't it all possible already in multiplayer? I play on servers and they alternative game modes, they just not implemented on single.

yup, but with plugins, which sucks since that means you can't play them with friends quite as easily

I think any ressource should contribute to core maxing, it would require a bunch of balancing but look more correct, because
> Power in Mindustry is basically, goes like this, You put down a generator, you give no mind to power except when it's in deficit or you putting some batteries down and you connect them to Factories, Turrets, and Other Stuff

is mostly wrong (in my opinion), since a ton of things in the game requires power to work

> -A Big No Build Zone around each Player's Core in PvP

this sounds horrible to me, players will just spam arcs and destroy you

**Comment by Kyllingene** [comment]
> Power in Mindustry is basically, goes like this, You put down a generator, you give no mind to power except when it's in deficit

This is a good point, but we should really try and fix that for all gamemodes, instead of implementing a new one.

I don't feel like nitpicking this issue, so I'll just bring up the main argument against this: why would people bother to play, for example, "survival but it ends" or "attack/pvp but with big gun"? Survival is more fun when it *doesn't* end, and attack/pvp both already have superguns; the problem is simply that it takes too much effort to play the new gamemode for how little it adds, regardless of if what it adds is terrible or the greatest thing ever thought of by mankind.

**Comment by OnyxFinger** [comment]
> Survival is more fun when it doesn't end

campaign.. but I agree with your point, though I think it is an interesting mechanic in PvP, or more like a not PvP, not attack, not survival but "harvest" or "economy-rush" gamemode, against a player ~~which makes it PvP but you see what I mean~~
