### ISSUE TITLE
Unit additional health cap

### ISSUE THREAD

**Issue by Mechanicalfish** [Anuken/Mindustry-Suggestions#2861]
### Describe the content or mechanics you are proposing.

There should be an option in map settings to change how much max health can units get from shields. It can be either applied to specific units or unit tiers.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It can help with preventing t1 units like flares from having more than 1000 health in lategame waves.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Duplicate of #2855. Did you see the other issue and decide that we needed another? Honestly, we need that 4th checkbox back.

**Comment by RealYeet** [comment]
I miss the 4th check box, so many duplicates today

**Comment by Kyllingene** [comment]
If this is where we make suggestions for Anuken/Mindustry, do we go to Anuken/Mindustry to make suggestions for this?

**Comment by OnyxFinger** [comment]
> If this is where we make suggestions for Anuken/Mindustry, do we go to Anuken/Mindustry to make suggestions for this?

we can just suggest to re-add the fourth checkbox here right ?

**Comment by Kyllingene** [comment]
We could, but it probably wouldn't work.

**Comment by Mechanicalfish** [comment]
> Duplicate of #2855. Did you see the other issue and decide that we needed another? Honestly, we need that 4th checkbox back.

I didn't but I quess this one can be closed then
