### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by Enzo54623** [Anuken/Mindustry-Suggestions#2862]
### Describe the content or mechanics you are proposing.

I dont care if this is not accepted but its really cool.
I appresent you the "Modificator".
Its like an unit upgrader, but with a little less things. Example: you build an dagger factory. You put the modificator on the front of the factory. When the dagger is done, you select the upgrade you want to use. you will have some options, like: "extra gun" or "mini shield" or "extra health" and etc. When you selected the upgrade, the dagger will come with that upgrade. AND when upgrade complete, you can put an addictive reconstructor to make the dagger become an tier 2 dagger. But the upgrade will stay there, but better. Example:
"Upgrade of mini force field to dagger" when dagger upgraded to tier 2, the upgrade will become better too. A better force field.
And the modificator will do same thing to other types of units, no matter flying or not.
But there is an tier 2, 3, 4, and 5 modificator.
It Will not work using an modificator tier 3 on a tier 2 unit. Every modificator will have an different upgrade than the other tier.
Example: tier 1 modificator: "extra gun" "force field" "extra health"
And the tier 2 modificator will be like: "command more units" "more speed" "unit factory"
And the same unit CANNOT be upgraded more than two times. One upgrade per unit.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I don't know how it would really be better for the game, just a little buff. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by random-guy1285** [comment]
We already have unit upgrading, this is not something we need.

**Comment by Kyllingene** [comment]
The big problem here (the other bits could be considered opinion-based): "I don't know how it would really be better for the game, just a little buff." If you yourself can't think of a way that it would benefit the game, Anuke will not add it. Sorry!

**Comment by the-red-soul** [comment]
The sole purpose of how the units are designed are to fill niches. Being able to put a force projector shield on a dagger unit would be stupidly overpowered and completely negate the niche that quasars have. Units are designed with a reason and adding "modification X" would completely destroy the whole concept of the trees.

**Comment by Humanoid-X** [comment]
~~Add 1000 surge alloys to build material then yes~~
