### ISSUE TITLE
Biochemicals or materials

### ISSUE THREAD

**Issue by MistahStealYoGril** [Anuken/Mindustry-Suggestions#2863]
### Describe the content or mechanics you are proposing.

I think it would be very amusing if the game had bio waste and **brown** stuff. There would be lakes or sewer tiles. The liquid could be used by tsunamis or waves to slow bots down way more than oil would bc who tf would wanna wreak havoc while there is poo sloshing in their socks. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Imo, it would make the game so much funnier and amusing. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Imagine suggesting something for a multiplayer tactical game with the justification "haha lolz"

**Comment by Anuken** [comment]
poop...

**Comment by joshuaptfan** [comment]
In Mindustry, your units are robots. Your enemies are robots. There is nothing alive anywhere, except for spores (only on Serpulo for now) and grass. There is nothing that produces fecal matter, and robots would not feel "grossed out" by it anyway.

**Comment by MistahStealYoGril** [comment]
Wouldn't it get stuck in gears and whatnot?

**Comment by MistahStealYoGril** [comment]
(⌐■-■)

**Comment by MistahStealYoGril** [comment]
Btw I'm sorry guys

**Comment by GitHubUser-B** [comment]
> poop...

Oh, you! Hello Anuken, it's a rarity to see you here!

**Comment by OnyxFinger** [comment]
> poop...
well well well what the fuck did I step on ?
suggestion poop poop suggestion ?
xD

**Comment by OnyxFinger** [comment]
> In Mindustry, your units are robots. Your enemies are robots. There is nothing alive anywhere, except for spores (only on Serpulo for now) and grass. There is nothing to produce fecal matter, and robots would not feel "grossed out" by it anyway.

actually, on serpulo life is gone because of spore, so it would make sense if other planets had more life forms

**Comment by MistahStealYoGril** [comment]
Is my suggestion actually getting considered? O_O

**Comment by itcannotbe** [comment]
> Is my suggestion actually getting considered? O_O

Kindly refer to https://github.com/Anuken/Mindustry-Suggestions/issues/2863#issuecomment-900683410

**Comment by MistahStealYoGril** [comment]
I'll take that as a yes

**Comment by OnyxFinger** [comment]
> Is my suggestion actually getting considered? O_O

nope, it' just a fun thing

**Comment by MistahStealYoGril** [comment]
Aww mannn

**Comment by Humanoid-X** [comment]
Aw no but yes
