### ISSUE TITLE
More team-especific rules

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2865]
### Describe the content or mechanics you are proposing.

Add some more team especific rules, such as banned blocks/units and loadout.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More options.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
also unit health, since now it can make some difference

**Comment by oinkymoo** [comment]
more options aren't necessarily a good thing, but i support both of the ones you suggested

**Comment by OnyxFinger** [comment]
> more options aren't necessarily a good thing

why tho

**Comment by oinkymoo** [comment]
> > more options aren't necessarily a good thing
> 
> why tho

more options make it much more confusing for newer players. adding options just for the sake of having options is not a good idea

**Comment by OnyxFinger** [comment]
> > > more options aren't necessarily a good thing
> > 
> > 
> > why tho
> 
> more options make it much more confusing for newer players. adding options just for the sake of having options is not a good idea

tbh that's not gonna make it more confusing than it already is, because the info is already sorted in cathegories
