### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by zly222mindustry** [Anuken/Mindustry-Suggestions#2866]
### Describe the content or mechanics you are proposing.

I suggest anuken add surge-plastanium

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

nothing

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I think OP would  have deleted the template if we haven't switched to  forms.

**Comment by Kyllingene** [comment]
satire

[![image](https://user-images.githubusercontent.com/69094702/130010348-94d63e17-1293-4a60-aef0-bd00b8967dcd.png)](https://github.com/Anuken/Mindustry/issues/3684#issuecomment-736539263)

**Comment by IIINSTINCT** [comment]
__Oh wow No bodyelse suggested like this game changing Anuke would definitely add this__

**Comment by SMOLKEYS** [comment]
~~At least you know how to keep the template, others just delete it completely~~

**Comment by itcannotbe** [comment]
###### ~you can't even delete it if you wanted to.~

**Comment by Humanoid-X** [comment]
Go die

**Comment by OnyxFinger** [comment]
> Go die

no u

**Comment by Humanoid-X** [comment]
yes u

**Comment by zly222mindustry** [comment]
I'm sorry. Maybe I did something wrong.

**Comment by macimas** [comment]
:clap:
