### ISSUE TITLE
Add a more dramatic core destroy sound

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#2868]
### Describe the content or mechanics you are proposing.

Make a new sound for when a core is destroyed. A punchy or cool sound that lasts for a bit to really let the player know they destroyed a core and to feel satisfied about it. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

At the moment I don't find too much satisfaction when I destroy a core. Sure, I will capture the sector or win the PvP match, but it could really help emphasize that with a "you've won" kind of sound. I think it should be able to be heard from quite far to signify someone has destroyed one which would help especially in multiplayer.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
\(°-°)/ the god has spoken /(°-°)\
this is the change everyone awaited-- actualy I like this one let's not mock it too much
