### ISSUE TITLE
Core Destruction Animation

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#2869]
### Describe the content or mechanics you are proposing.

A new core destruction animation, because losing on a custom game and single player campaign looks boring. 

When the core gets destroyed, the scoreboard immediately shows up and stops you from seeing the progress you have done. **plus animation points maybe?**

https://user-images.githubusercontent.com/85320516/130070894-988714a8-d996-41a2-b5b9-44762ac3c04b.mp4

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The video shows a new layout when the core gets destroyed. 

- Immediately the game will pause for 3 seconds, or continue the game for 5 more seconds to see the shockwave spanning 10 blocks from the core. 
- 2-4 seconds after that, the scoreboard will show up. 
- Additional: The "New Highscore!" dialog should only show only in custom games. In campaign, the dialog will be replaced with "Sector Lost". 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
#2868 what is luck!?

**Comment by EclipsePlays** [comment]
I guess... We're thinking the same mechanic then...

**Comment by EclipsePlays** [comment]
Also added an extra video to demonstrate what should be added. 

**No we didn't plan to duplicate ideas, pure coincidence.**

**Comment by OnyxFinger** [comment]
I guess there can be an "end of the game thing" for this one and "on every core destroyed (if there are multiple cores) one ?
that other one sounded more like you want to know when a core gets destroyed than when you win :)

**Comment by EclipsePlays** [comment]
> that other one sounded more like you want to know when a core gets destroyed than when you win :)

In survival custom games, you'll always lose. In attack gamemodes, you'll win. And in campaign, there could be many times you'll lose soo...

**Comment by staticalliam7** [comment]
This would be really cool and probably easy to implement
