### ISSUE TITLE
Logic Synths (for Logic Sound because nothing is stated there)

### ISSUE THREAD

**Issue by FarmerThanos** [Anuken/Mindustry-Suggestions#2871]
### Describe the content or mechanics you are proposing.

(I am aware that Logic Sound is stated on the Trello but it doesn't have a description or anything)
Logic Synths could be 3 oscillator synths, with basic waves as saw, triangle, pulse waves with full width modulation, and noise. A 64/32bit synth would obviously be too heavy for the game, so a 16/8bit one would most likely be better, additionally to them having a distinct sound. 

The control of Logic Synths could be via writing memory addresses to a positions, so bit 1 could for example be triangle, and bit 10 be the Attack of the first oscillator. Additionally to the basic waveforms, being able to combine them (on the same oscillator) would add a few more interesting waves, however that depends on how the mixing is done. 

The Synths could also have a global filter with lowpass, bandpass, and highpass, which can be applied to an oscillator by turning a filter bit to 1. These filters could be combined just like the waveforms to produce uncommon sounds.

For how the setup would work, it is basically that a logic processor controls the Synth, and the Synth plays a frequency when "asked". This means that Synths would be instruments, while processors would be the songs or patterns. I assume the bare minimum setup requires 2 processors (one for control and the other for playing by adjusting the frequency) and of course a Synth to actually play those instructions. However the sounds produced by the Logic Synths should not be global.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

For beginners, it would allow for an alarm system, to for example monitor if enemies have gotten past a point or if a part of the base has stopped working due to a power loss or other malfunction. 
For people who are more into logic and are comfortable with it, it would allow for them to make in-game music and sound effects, for example for logic games.
In the end this would somewhat work like a logic notification system, but instead of displays you got audio.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by FarmerThanos** [comment]
If something is already planned, but isn't mentioned, about Logic Sounds I'm gonna close this.

**Comment by RealYeet** [comment]
I have no idea why it needs to be this complex, in my opinion, there needs to be one new logic parameter that says the following
Pitch: E flat (example)
Noise: 55%
Type of sound: Piano

**Comment by Humanoid-X** [comment]
why do we need noise

**Comment by FarmerThanos** [comment]
> why do we need noise

noise isnt used _that_ much in modern music, but in the past it was basically responsible for percussion and some some sound effects

**Comment by RealYeet** [comment]
> why do we need noise

It is sound, such as ambient volume, this will dull down the sound so you can have a background

**Comment by Ksawi999** [comment]
> I have no idea why it needs to be this complex, in my opinion, there needs to be one new logic parameter that says the following
> Pitch: E flat (example)
> Noise: 55%
> Type of sound: Piano

I think adding that as a logic param would be too OP (you can play 1500 sounds per second on hyperprocessor). I prefer if it will be played by separate block (speaker), that you would be able to control using processor. Speaker should play only one sound at the same time, so sure, you still can play 1500 sounds per second but you need to build 1500 speakers. There should be also 2x2 speaker that can play more sounds at the same time and has bigger sound range.

**Comment by RealYeet** [comment]
That is my idea, then you would have a sound flush type of thing

**Comment by Kyllingene** [comment]
I don't think we need that complex of sound; however, I have to assume that Notch thought the same when creating Minecraft. But, RealYeet, why would you need a "sound flush" if each speaker can only play one note at a time?

**Comment by Ksawi999** [comment]
~~Add control flush~~

**Comment by RealYeet** [comment]
You program a sequence of notes using a logic prosesor then you flush like how for have print flush or draw flush

**Comment by Ksawi999** [comment]
> You program a sequence of notes using a logic prosesor then you flush like how for have print flush or draw flush

That haven't got sense. On draw flush and print flush you don't make sequence, you just combine all remaining params at a time... So for sounds you must use "sound flush" after every sound (because speakers can't process more). It would be quite annoying...
