### ISSUE TITLE
new sound

### ISSUE THREAD

**Issue by King-Silicon** [Anuken/Mindustry-Suggestions#2872]
### Describe the content or mechanics you are proposing.

new sound landing- https://drive.google.com/drive/my-drive. the sound is taken from my modification.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

nice to listen to

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by King-Silicon** [comment]
> ### Describe the content or mechanics you are proposing.
> new sound landing- https://drive.google.com/file/d/1QkSPi-Mq6E6LrTonZF4szWt298j4aOX9/view?usp=sharing. the sound is taken from my modification.
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> nice to listen to
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by King-Silicon** [comment]
> ### Describe the content or mechanics you are proposing.
> new sound landing- https://drive.google.com/drive/my-drive. the sound is taken from my modification.
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> nice to listen to
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
wat u doing lmao?
