### ISSUE TITLE
More climate effects

### ISSUE THREAD

**Issue by Jaysoon80** [Anuken/Mindustry-Suggestions#2873]
I think that for the v7/v8 update, we should have various effects on our efficiency, stats and other factors to add more unique niches and awesome gameplay for these new planets and biomes.

Firstly, I think that the cultivator should work less efficiently in hot biomes and even less efficiently in cold biomes due to the inhospitable temperatures therefore diminishing spore amounts. I also think water in both the cold and hot biome should be effected (it seems water in the hot biome already is!), with the hot biomes having their water evaporated and the cold biome's frozen.

These are just some ideas and obviously there could be more, I hope these do get implemented because otherwise I think the new planets will get dull quite fast.

**Comment by Humanoid-X** [comment]
Watch your template.

**Comment by OnyxFinger** [comment]
https://trello.com/c/8mqko6QL/29-environmental-effects
yeet
