### ISSUE TITLE
QoL during building 

### ISSUE THREAD

**Issue by Claude0012** [Anuken/Mindustry-Suggestions#2874]
### Describe the content or mechanics you are proposing.

Make it possible so that players can construct alternating buildings such as conveyor-underflow. Its basically done by drag and click but this time, with two or more buildings alternating.

Other uses: junction-underflow, junction-junction-underflow. All of them can be used along side factories and turret ammo reloading. Maybe it can be also added to map making as well? 

The copypaste almost does this feature but I think this is unique enough. 

Also, is the cut a considered option? The player will basically destroy then rebuilt whatever is "cut" 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will be an improvement for fast paced oriented style of multiplayer, and to an extent single player as well. 

It is good enough for basic factory setups but will not be as efficient as certain prebuilt schematics.

Personally speaking, I really want the cut option and find it very useful. I can't see how it will be game breaking besides being able to move factories a little for space management. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
https://trello.com/c/dQVwyskS/872-schematic-lines might be enough already,

**Comment by RealYeet** [comment]
Unrelated but I hate the idea of schematic lines, how hard it is to click a second time?

**Comment by Humanoid-X** [comment]
@RealYeet

How easy it is to open schematic menu, search for the keyword "stackable silicon" and then click on the screen, then repeat for 10 times? Or sometimes when testing in sandbox u will need it.

**Comment by RealYeet** [comment]
I don’t know what you mean, you don’t have to open the schematic window again after placing a schematic, you can place, move you cursor 10 blocks, and place again. Really not that hard. @Humanoid-X
