### ISSUE TITLE
A likely good vela revamp

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2875]
### Describe what you would like changed, and why.

*(TL:DR: Basically, make vela a combat medic)*
After some discussion in #balancing, we basically proved that vela wouldn't *ever* become useful unless it actually gets a specified purpose (or is made OP off the charts)
Due to that, we decided to think up a purpose for vela, and that is, a combat medic - as in, make its beam heal units - i think of this as a very useful tactical utility for vela
Currently, no other unit does specifically that - even though oct can do that, it's not really for that purpose - it's more of a protector than a medic

### Describe the changes you want to propose. Include possible alternatives.

Make vela's beam heal units, perhaps nerf the damage to compensate?

**Comment by Ineedause** [comment]
Slightly different idea, maybe make Vela give units the overclock status buff because as of right now only the Minike can give it and the Vela needs a "support" atribute to it because it is support

**Comment by Kyllingene** [comment]
> Slightly different idea, maybe make Vela give units the overclock status buff because as of right now only the Minike can give it and the Vela needs a "support" atribute to it because it is support

But that would ruin the unique bit about Minke.

**Comment by RealYeet** [comment]
Ik but still, ofc it is still just another idea

**Comment by notrealn** [comment]
> But that would ruin the unique bit about Minke.

why does minke even have that? its part of the "damage" boat tree, not "support"

**Comment by Kyllingene** [comment]
> why does minke still have that? its part of the "damage" boat tree, not "support"

I'm not actually sure it does; I haven't found any reason to believe so. However, it may be in a beta build.

**Comment by RealYeet** [comment]
It’s status effect is overdrive, this is the only unit that has this specific status effect and is the only unit able to boost units by 15% in nearly all aspects

**Comment by RzBuddy** [comment]
(adding on to the idea)
what if on top of healing vela also gave units some sort of "overdrive" buff

**Comment by OnyxFinger** [comment]
> > Slightly different idea, maybe make Vela give units the overclock status buff because as of right now only the Minike can give it and the Vela needs a "support" atribute to it because it is support
> 
> But that would ruin the unique bit about Minke.

there is still a huge time window where minke is useful, though only time will really tell

**Comment by OnyxFinger** [comment]
I kinda like this idea. Like, relying on a laser's pierce in order to make a unit other than T3 actually good is kind of a bad idea anyway, so this is already better
> > But that would ruin the unique bit about Minke.
> 
> why does minke still have that? its part of the "damage" boat tree, not "support"

~~and it gives a lot more damage, also it's an actually good support unit for once so I'm no gonna cry about it~~
You're still kind of right, this is suspicous and maybe oxynoe should get the overclock effect instead of minke (imposing a moinke buff lol), because that's the better idea

**Comment by Kyllingene** [comment]
> there is still a huge time window where minke is useful

Explain why a unit which is *bound to water* would see more use that a unit that is *bound to ground*, allowing it to assist air *and* ground *and* naval (if they are close to the edge) units, which the Minke could only do if the air/ground units were near the edge; the ground unit would be superior in every way, including other stats. No, we need a more unique buff for Vela.

**Comment by OnyxFinger** [comment]
> > there is still a huge time window where minke is useful
> 
> Explain why a unit which is _bound to water_ would see more use that a unit that is _bound to ground_, allowing it to assist air _and_ ground _and_ naval (if they are close to the edge) units, which the Minke could only do if the air/ground units were near the edge; the ground unit would be superior in every way, including other stats. No, we need a more unique buff for Vela.

well because it buffs stuff
It can be used combined to other naval units. It seems that many players forget that although naval units are restricted to water, and thus map-dependant, they are stronk

**Comment by sup3r87** [comment]
this is similar to my suggestion( https://github.com/Anuken/Mindustry-Suggestions/issues/2559 ) i made a bit ago, that suggests vela be given support turrets, among other things.
