### ISSUE TITLE
What about give a Segment turret to Oct? 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2877]
### Describe what you would like changed, and why.

Since we got a new naval units with build in Segment turret I ask myself: why? I find it's not fair that T2 have built in Segment, while T5 that is focused as support unit do not. 

### Describe the changes you want to propose. Include possible alternatives.

You may say that Oct is already good as big shield, but I think added segment would make unit more interesting to use.

**Comment by OnyxFinger** [comment]
please keep the  boxes next time.

**Comment by Kyllingene** [comment]
The boxes are not present on `balancing/feedback` issues, which this is.

**Comment by Mechanicalfish** [comment]
would the segment be identical or have slower/faster attack rate

**Comment by Marchosaur** [comment]
This is an actual good idea, I have never seen or used an Oct because it is lacking as a T5 unit and is hella expensive. This would make it worthwhile as an excellent supporting unit.

**Comment by XenonLog01** [comment]
I would like to see this. Definitely would not be as op as regular, but would be very useful.

**Comment by GitHubUser-B** [comment]
> ### Describe what you would like changed, and why.
> Since we got a new naval units with build in Segment turret I ask myself: why? I find it's not fair that T2 have built in Segment, while T5 that is focused as support unit do not.
> 
> ### Describe the changes you want to propose. Include possible alternatives.
> You may say that Oct is already good as big shield, but I think added segment would make unit more interesting to use.

- [ ]  I'll roast you with this

**Comment by GitHubUser-B** [comment]
- [ ]  I'll roast you with this
