### ISSUE TITLE
Steel, reinforcing and water units!

### ISSUE THREAD

**Issue by MBXMBX** [Anuken/Mindustry-Suggestions#288]
I was thinking about good old steel for a long time, and knowing about the upcoming anti-AFK balance changes, I thought that we must fight back against the ever-growing horde of robots with a little extra protective technology... (Note that the shown values are subject to your balancing acts)

• **New resource – Steel!**
— **A combination of Lead and Coal, Steel is used for reinforcing structures and constructing a naval force.**
— **Resource properties**: Storable in Core: Yes     Explosiveness: 0%     Flammability: 0%     Radioactivity: 0%
— **Production station** – **Steel Factory** - This 2x2 structure with 60 hp and a build time of 0.98 seconds is (obviously) used to manufacture Steel.
The resource requirements for construction are:
- 50x Copper,
- 60x Lead,
- 25x Graphite.
The requirements for production are: 2x Lead + 2x Coal + 45 power units per second = 1 Steel / 0.67 seconds.
• **Now it's time for the exciting part! What can you do with your hard earned steel?**
— **Reinforcing!** - when you unlock Steel Protection, in the wall menu you can now place side reinforcements. Steel is just as strong as titanium (although the latter is superior thanks to its weight), however reinforcements cover only half of a building, making the protection value 25% (balance issues I noticed), while cost and build speed half of a similarly sized titanium wall, i.e:
- 1x1 protection = 110 hp, 3 steel;
- 2x2 protection = 440 hp, 12 steel;
- 3x3 protection = 990 hp, 27 steel;
- 4x4 protection = 1760 hp, 48 steel.
You cannot reinforce Cores, movement related blocks and walls.
— **Navy creation!** - ever got bored of the only unintresting usage of water? Now it's time for something straight out of the military! Using a bunch of resources and power, you can create ships and tower carriers!
- Ships can either be defenses (attack nearby enemies), carriers (allows placement of land-based structures on the water) or both, although those are gonna be expensive.
- I was thinking about having ships be units - created from their own factories, while carriers and defensive-carrier fusions would be placed like normal structures.

And that's it! I wanted to get this out quickly so I don't have to type all of this over again (that's why there are no stats for navy factories and other related items). I hope you will be able to continue with Mindustry and keep on adding amazing content! Btw, the Fuse is super op against Reapers, so I'd recommend giving it a 20% damage reduction against laser-type towers or something like that.

Support and good luck from the Winged Husar homeland,
- MBXMBX

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> Steel

This was around in Classic, but intentionally removed from the game. I don't want a resource tree with resources identical to every other crafting game out there; steel is about as generic as it gets.

> Reinforcement

This would be very complex to implement without breaking things (as another block layer is needed), and I honestly don't see the need for a mechanic like this.

> Navy

This is already planned on the Trello.
