### ISSUE TITLE
Improved Japanese language support

### ISSUE THREAD

**Issue by XenonLog01** [Anuken/Mindustry-Suggestions#2880]
### Describe the content or mechanics you are proposing.

Currently, mindustry has good language translation for Japanese, however, due to the nature of Japanese writing, the current 'type and hope you tabbed correctly' method is less than desirable. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I would like an IME style box that shows up like on windows to display the possible kanji choices, that could even emulate the results of the os(might be a lot of work, and annoying to implement for several operating systems), that way, typing with Japanese is significantly easier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
[Has already been discussed previously.](https://github.com/Anuken/Mindustry/issues/1043)

**Comment by XenonLog01** [comment]
@joshuaptfan ok, sorry.
