### ISSUE TITLE
Campaign Leaderboards

### ISSUE THREAD

**Issue by SuperficialIntelligence** [Anuken/Mindustry-Suggestions#2881]
### Describe the content or mechanics you are proposing.

A leaderboard that displays the resource production per minute of every player in campaign mode with the players with the most resource production on top. There could be many different separate leaderboards for who makes the most copper, silicon, surge alloy, etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will give players an incentive to keep playing the campaign after it's finished and to show off "highscores" in the form of resource production per minute. And gives more incentive to maximize efficiency and take over every tile on every planet.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
![20210417_172946.jpg](https://user-images.githubusercontent.com/83259488/130341772-c6257779-e715-4da1-825c-465e1482debf.jpg)

Well i guess i have a reason now to keep this thing xD Well i like this idea but if this implemented well it will go on steam Google play and ios (added feature for people payed mindustry)

**Comment by Anuken** [comment]
The main issue here would be preventing cheating.

**Comment by itcannotbe** [comment]
> The main issue here would be preventing cheating.

Which you basically can't.

**Comment by Marchosaur** [comment]
> > The main issue here would be preventing cheating.
> 
> Which you basically can't.

Would cheating in this instance be hacking or what?

**Comment by SuperficialIntelligence** [comment]
> The main issue here would be preventing cheating.

Good point, I don't really know how cheating to get ridiculous scores could be prevented. This probably shouldn't be a thing till that's solved. And if it isn't solved, it would still be nice to see everyone's resource production and having people show off their production capacity even if there's very obvious cheaters on the leaderboards.

**Comment by OnyxFinger** [comment]
> The main issue here would be preventing cheating.

eh it's still just nice to have the thing, even if you don't wanna show it off to people
the suggestion showed up the idea as a sort of "competitive", if I may say so, way of playing and trying to get to the greatest heights, while it can just be a sort of cool QoL

**Comment by Kryvytsky** [comment]
I saw leaderbord in Infinitode 2. But Infinitode have 50 Level and a lot of grind. Mindustry have about 200 sectors (I'm not sure how exactly much). Also we would get more planets in future. So I see no point in leaderbord, cuz Mindustry have enough content unlike Infinitode.

**Comment by genNAowl** [comment]
> Would cheating in this instance be hacking or what?

Campaign Item Sources (Theres like 30 ways to do this)

**Comment by GitHubUser-B** [comment]
> The main issue here would be preventing cheating.

You again!? Great!

**Comment by Humanoid-X** [comment]
Theres like cheat mods that add item/power/liguid sources for campaign... And cheat engine...

GithubUser-B had absolutely gone crazy

**Comment by GitHubUser-B** [comment]
> Theres like cheat mods that add item/power/liguid sources for campaign... And cheat engine...
> 
> GithubUser-B had absolutely gone crazy

What? Why?

**Comment by genNAowl** [comment]
There might be a few ways to make it harder to cheat, like: 

1. Making any score achieved with mods on invalid. 
 - Prevents DevMode and just typing into the console
 - Prevents modded item sources
 
2. Making any scores achieved without an official build invalid
 - Prevents people without an in-depth knowledge of the code from modifying src for item sources/other cheats

However, If you can modify and compile the source code, you can remove the restrictions anyway. You could probably even compile modified source code as an official build, rendering the second restriction useless. I haven't even touched on the issue of save file modifications, and there are probably many other cases I haven't even thought of. 

Okay, nevermind. The bottom line is, I think there is no viable to prevent cheating at the moment. Even if there was, I doubt it would be worth coding just for a custom leaderboard. As such, I don't think campaign leaderboards are gonna be added anytime soon.

**Comment by Dinistor** [comment]
This would be better named "campaign have too much sectors for this little amount of content, that we need to make something to encorage people capture useless sectors" (bc you need ~10 good setup sectors to non-stop core spamming, why would you even waste time on resource import increase that will just burn)

**Comment by osp54** [comment]
@Anuken , why not prohibit entering the compaign with mods?

**Comment by itcannotbe** [comment]
1. You shouldn't have pinged anuke
 
2. There are a lot of ways of by-passing such restriction. And being an open source game. It's essentially stupid to even consider.

**Comment by osp54** [comment]
> 1. You shouldn't have pinged anuke
> 2. There are a lot of ways of by-passing such restriction. And being an open source game. It's essentially stupid to even consider.

1. show me where it says that it is forbidden to ping?
2. you know, it will at least remove 75% + of under-cheaters

**Comment by Kyllingene** [comment]
> why not prohibit entering the compaign with mods?

Ah yes, prohibiting players from playing an *open-source game,* centered around making it as easy as possible to tailor it to your liking, how they would like to play it, all for the sake of stopping a few people from cheating on a meaningless leaderboard.

> show me where it says that it is forbidden to ping?

Show me where it says that it is forbidden to sneeze on someone. What, you can't? That would be because it is *common etiquette*. Don't ping Anuke, especially on such trivial issues, because he is very busy.

> you know, it will at least remove 75% + of under-cheaters

Heavily restricting players to prevent 75%+ of "under-cheaters" from showing off blatantly false scores on a leaderboard that means nothing is a *very* steep price.
