### ISSUE TITLE
Thorium ammo should glow slightly pink

### ISSUE THREAD

**Issue by Nils101** [Anuken/Mindustry-Suggestions#2882]
### Describe the content or mechanics you are proposing.

Thorium bullets should glow in a light pink, just like pyratite ammo glows orange.
Fuse already has this.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

 This would differentiate the strong thorium bullets from other, cheap ammo visibly and it would look very nice in my opinion.

It would also allow you to immediately see what ammo is being shot from a tower, which improves quality of life.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Nils101** [comment]
Title fail

**Comment by OnyxFinger** [comment]
yeah I guess

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry/pull/3098

**Comment by Nils101** [comment]
> [Anuken/Mindustry#3098](https://github.com/Anuken/Mindustry/pull/3098)

It's a pretty old pull, gonna leave this suggestion open for a little longer.

**Comment by Kyllingene** [comment]
I wouldn't say that 10 months is long enough for Anuke to change his mind about something like this.
