### ISSUE TITLE
Spore ammo for scorch 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2883]
### Describe the content or mechanics you are proposing.

Spore is another flammable material so why not make it useable as coal and pyratite. Also, there is spore slowed status that is used only in spore storm and nowhere else, so spore ammo should apply a spore status to enemy.
![Screenshot_20210821_123652_io anuke mindustry](https://user-images.githubusercontent.com/81460407/130368221-6283a574-26af-4363-8003-31677ea9e3f3.jpg)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More variability to Scorch. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
I would say not every item needs to be an ammo, however, this is an interesting concept. 

The `spore-slowed` status part doesn't make too much sense (burned spores wouldn't really slow enemies), but it would add more uses for spores, which I like.

**Comment by oinkymoo** [comment]
spores are cool when you unlock them in the early game, until you actually look and see that they're pretty much useless until you get titanium. they can be used to make power, though not much more effectively than coal. the only other thing you can do with them until you have titanium is make oil, which isn't all that useful either because all it can do in the early game is tar enemies through wave turrets

**Comment by OnyxFinger** [comment]
spore is pretty useless in survival to me, and I barely make any, except in weird cases/for impacts, and I'm a scorch fanboy so I like it :P
