### ISSUE TITLE
new feature for polys

### ISSUE THREAD

**Issue by yowereto** [Anuken/Mindustry-Suggestions#2884]
### Describe what you would like changed, and why.

the polys don't switch from something it cant build to something that can

### Describe the changes you want to propose. Include possible alternatives.

if the polys cant fully build something or rebuild something it should switch to something it can

**Comment by RealYeet** [comment]
Yes

**Comment by oinkymoo** [comment]
like when players try to do so? i support

**Comment by Humanoid-X** [comment]
Yeas

**Comment by OnyxFinger** [comment]
yeessss

**Comment by Dinistor** [comment]
+1
