### ISSUE TITLE
Make Player Launch Loadout Rotatable

### ISSUE THREAD

**Issue by Odin580** [Anuken/Mindustry-Suggestions#2885]
### Describe the content or mechanics you are proposing.

I'm referring to this screen

![Screenshot_20210822-151859](https://user-images.githubusercontent.com/88634312/130373409-d7cd3829-f96c-4e48-a4c6-c730919c0356.png)

I made this schematic for launching into sectors..

![Screenshot_20210822-151543](https://user-images.githubusercontent.com/88634312/130373420-5d163731-f8a9-4af3-8859-c0e400549b7e.png)

I like to send empty T1 cores to scout adjacent sectors, as seen here

![Screenshot_20210822-151711](https://user-images.githubusercontent.com/88634312/130373443-c20bab44-b84c-414b-8477-bd69a8638a56.png)

However, my loadout wouldn't fit since T4 and T3 unit buildings cut off

![Screenshot_20210821-220910](https://user-images.githubusercontent.com/88634312/130373461-3b6675cc-c963-4452-8368-7be113c6ccd7.png)

However, if I could build it like this it would fit

![Screenshot_20210821-220922](https://user-images.githubusercontent.com/88634312/130373472-bc56cb63-ea5c-4a9b-8649-d2dd72cf0282.png)

All I have to do is rotate 180°.  The simplest solution would be allowing me to rotate the launch schematic from the loadout screen [I don't think it matters if the default ones can do this].  Alternatively, I could make 3 extra versions that are each rotated at a different 90° angle to cover all 4 usage cases.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allows players to fit their loadout schematics in any given sector.  Since the placement of core relative to the walls are different in each sector, a single schematic will end up being cut off in certain sectors.  Rotating would allow a player to adjust to this fact.  Likewise, they could just make 4 versions of each schematic to deal with how walls might disrupt the schematics.  But being able to rotate (just like other schematics), would seem useful.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Also on a similar note, it would be nice to be able to preview your landing area so some of your buildings don’t get blocked

**Comment by RealYeet** [comment]
(This is so that you can rotate your building accordingly if you couldn’t tell)

**Comment by OnyxFinger** [comment]
yeah, I guess
