### ISSUE TITLE
A little tweak in optional enhancements naming

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2886]
### Describe what you would like changed, and why.

This was briefly discussed in #development.
The idea is to make "optional enhancements" a bit more accurate, so that it is mentioned what it increases. For oilex, cruc and watex it is speed, but for spores it is higher output with same input. Then have *more speed* or *more output* said later, so confusion is avoided.

### Describe the changes you want to propose. Include possible alternatives.

That is it. No special tricks, just say whether speed or yield is increased.

**Comment by OnyxFinger** [comment]
ok ? That was confusingly written but I think I understood
