### ISSUE TITLE
Save data in a custom directory

### ISSUE THREAD

**Issue by Badboy2061** [Anuken/Mindustry-Suggestions#2887]
### Describe the content or mechanics you are proposing.

Let users save the save data in a custom directory to sync across platforms with something like syncthing.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be very helpful for people who want to play on multiple platforms but don't want to ex- and import the save data all the time to switch platforms without losing their progress. Take me as an example. I primarly play Mindustry on my computer but I also want to play on my phone on the go without to think about ex- and importing my data before I go somewhere.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Pretty sure this was suggested many times before: 
https://github.com/Anuken/Mindustry-Suggestions/issues/2163
https://github.com/Anuken/Mindustry-Suggestions/issues/1765

Eh, there's probably even more similar suggestions but I'm too lazy to search for more.

**Comment by Badboy2061** [comment]
Ohh, didn't find these suggestions.

**Comment by Badboy2061** [comment]
Reopened this issue again because I closed this issue before reading through #1765. The save files on android are saved under the `/Android/data/io.anuke.mindustry/` directory and to my knowledge the directory `/Android/data/` isn't accessible without root access (I also tried it now). So it's not possible without a function to save the data somewhere else.

**Comment by itcannotbe** [comment]
> Reopened this issue again because I closed this issue before reading through #1765. The save files on android are saved under the `/Android/data/io.anuke.mindustry/` directory and to my knowledge the directory `/Android/data/` isn't accessible without root access (I also tried it now). So it's not possible without a function to save the data somewhere else.

It's accessible. it's not in `/android` ,it's in (depending on your os) basically internal storage /android/data/io.anuke.mindustry

**Comment by Badboy2061** [comment]
It isn't accessible on my android phone.

**Comment by Badboy2061** [comment]
I found out that the `/storage/emulated/0/android/data/io.anuke.mindustry` directory is only accessible with the standard file manager. That explains why couldn't see any folders in `Android/data` but my syncing tool doesn't seem to be able to even see the `data` directory so I and probably many more people would still want and need this feature.

**Comment by itcannotbe** [comment]
Sound like an android 11 problem.

Which if it is, then there is 0 chance of this happening. As google is very strict on which apps they allow with such functionality on the playstore.
