### ISSUE TITLE
Crawler cost decrease

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2888]
### Describe what you would like changed, and why.

Crawler is not really viable not due to low stats, but due to the cost - for a unit that can only fire once, the current cost is too much

### Describe the changes you want to propose. Include possible alternatives.

10 silicon + 20 coal + 12 seconds to
8 silicon + 10 coal + 10 seconds
The coal cost of 20 is the worst thing about crawler's manufacturing cost, especially considering that most maps lack coal, so a decrease from 20 to 10 is actually reasonable

**Comment by Ineedause** [comment]
I was a part of the conversation that took place in #balancing and I support the change for the reasons stated above.

**Comment by EclipsePlays** [comment]
n i c e

**Comment by itcannotbe** [comment]
Wow. Implemented as suggested.

But would the change make it viable?

**Comment by OnyxFinger** [comment]
> Wow. Implemented as suggested.
> 
> But would the change make it viable?

awnsser : crawlers would still not be viable.
the price decrease is just ot enough, it's gonna blow up harmlessly on something like a wall that's gonna get healed up, and your ressources are wasted + you didn't deal damage
