### ISSUE TITLE
Remove logic itemDrop to @air

### ISSUE THREAD

**Issue by Dinistor** [Anuken/Mindustry-Suggestions#2889]
### Describe what you would like changed, and why.

The new feature of dropping items "to the ground" is added in v130.1, allowing not to worry about getting units for delivery schems drop items thats not needed when core is full with items of that type, since flares can't drop items to filled core (if rule "core incinerates overflow" is false".
But this is double-bladed sword feature, because it opens  WAY TOO EASY grief strategy when you can just unload entire core to the ground in few seconds. I think that griefing potential of this feature is way higher than benefit it gives to logic delivery systems.
This issue is only about multiplayer tho, why would you grief yourself in single player :eyes:

### Describe the changes you want to propose. Include possible alternatives.

I would suggest make "core incinerates overflow" rule always true, or (*better*) making "core incinerate overflow" *always true for logic itemDrop*.  Increasing itemDrop/itemTake cooldown time (2 seconds is ok) won't do nothing since a lot of units can do bad job.

**Comment by Bottinator22** [comment]
Alternatively, allow simply disabling this in servers

**Comment by Bottinator22** [comment]
Also, itemdropping to core is nowhere near as fast as itemdropping to @air, since you have to approach the core first

**Comment by Dinistor** [comment]
> Alternatively, allow simply disabling this in servers
Problem with this is on servers with this rule disabled: schematics with itemDrop to @air would not work.
On the other side - schematics without itemDrop to @air will be the same (and even worse) on servers with this rule enabled.
This can cause missunderstanding when placing a schematic

**Comment by Anuken** [comment]
This is very easy to remove if it ends up becoming a problem.

**Comment by Bottinator22** [comment]
Also, why remove itemDrop to air just because of servers? Logic Building can be disabled on servers, and it works fine on singleplayer.

**Comment by BlackDeluxeCat** [comment]
What if flares can drop to a filled core, and just remove overflowed items.

**Comment by Humanoid-X** [comment]
No anuken dont remove

**Comment by Yell245** [comment]
"BUT THERE ARE GRIEFERS!!!!!!!"

Remove enemies! Griefers can control units and make them kill themselves to enemies! Remove deep water! Units may be controlled by griefers and made to drown themselves! Remove unbuilding feature, it allows griefers to unbuild defences!

Griefers may *easily* go and just unload the core themself. Why is no one removing an ability for players to drop items?!

**Comment by itcannotbe** [comment]
> "BUT THERE ARE GRIEFERS!!!!!!!"
> 
> Remove enemies! Griefers can control units and make them kill themselves to enemies! Remove deep water! Units may be controlled by griefers and made to drown themselves! Remove unbuilding feature, it allows griefers to unbuild defences!
> 
> Griefers may _easily_ go and just unload the core themself. Why is no one removing an ability for players to drop items?!

This is an issue and those aren't because of the easiness of doing itemdrop to air undetected and unfettered.

**Comment by Dinistor** [comment]
ItemDrop to air has two uses: when you have unit delivery and units take too much items or unit have wrong items in it you can drop them to air, but also you can drop it to core that will incinerate thoose items, as i suggested, if they are overflow.
Second is switching ore that units mine, can be also solved with overflow incineration. 
You may also say "it increases the speed of delivery, cuz you don't need to move to core to drop useless items", but it's not - you need to move to the core anyway, to take needed items, if core will incinerate overflow items this problem will be solved just fine.

**Comment by Dinistor** [comment]
> "BUT THERE ARE GRIEFERS!!!!!!!"
> 
> Remove enemies! Griefers can control units and make them kill themselves to enemies! Remove deep water! Units may be controlled by griefers and made to drown themselves! Remove unbuilding feature, it allows griefers to unbuild defences!
> 
> Griefers may _easily_ go and just unload the core themself. Why is no one removing an ability for players to drop items?!
1) there is thing as "you are interacting with blocks too quickly" - you will be autokicked if you manually unload ~1k of res
2) everything that you mentioned can be easily detected visually. What if i make a schem that "makes surge", but cycle has 25% of it units actually deliver items to schem and 75% of it units just fly to schem and drop items to ground. No one will suspect it - flare surge schems uses alotta units, work like 50% of the time bc of bad logic and use a lot of resourses. You cant say that this is grief if you don't understand code for 100%
