### ISSUE TITLE
AI Fixes or Overhaul

### ISSUE THREAD

**Issue by Desiii** [Anuken/Mindustry-Suggestions#289]
The enemy AIs are very dumb and instead of spreading out over multiple paths choose to go to the path with the least amount of walls. This can allow for cheese by creating a large wall on one path without any turrets.

Change the AI to be smarter and spread out over multiple paths unless there is a clear difference in defense. Base it on walls, support tech, and turrets rather than just walls.
<img width="1254" alt="mind" src="https://user-images.githubusercontent.com/67931769/86662547-cea58e00-bfba-11ea-8435-5f82c723de35.PNG">

**Comment by itcannotbe** [comment]
AI Pathfinding is already based on multiple variables not just walls.

**Comment by Anuken** [comment]
> This can allow for cheese by creating a large wall on one path without any turrets

I don't see why this is a problem. Picking the path of least *terrain resistance* makes sense; in your picture, breaking through all those walls would take much longer than breaking through the turrets. A super-intelligent AI that picks the path of least turret coverage isn't a fun mechanic.
