### ISSUE TITLE
[Modding]Optionally disable random effect length

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#2890]
### Describe what you would like changed, and why.

I can do this

https://user-images.githubusercontent.com/61173114/130522174-175b2701-b73b-4fbe-a121-d13b07a3fae7.mp4

but not move it

https://user-images.githubusercontent.com/61173114/130522191-e1d25837-4090-45e4-b06b-ef091159e713.mp4

### Describe the changes you want to propose. Include possible alternatives.

Add a field for disabling the random length. I was going to add something else about allowing the particles to spawn with an (angle) interval instead of being randomly placed, but that's more just for funsies. 
These will allow for more "synthetic" style effects to be created, since wierder JSON *anything* is a complicated mess of effects.
(also, should I make further requests on the discord? this probably bloats the suggestions page)

**Comment by BlueWolf3682** [comment]
dingus

**Comment by Kyllingene** [comment]
What?
