### ISSUE TITLE
Music Boxes

### ISSUE THREAD

**Issue by JajkoSwinka** [Anuken/Mindustry-Suggestions#2891]
### Describe the content or mechanics you are proposing.

Possibility to build music box - the object, which allows you to change currently playing music or even order of playing tracks. Music box would also include legacy (Mindustry classic) tracks.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It might be good cosmetic feature to add. Player would be able to make more customized maps. It will also allow "new Mindustry" players to listen their favorite old tracks. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Something similar to the jukebox system in BTD6?

**Comment by JajkoSwinka** [comment]
I did not play it, but I know, what you mean. I think about something, like Infinitode 2 jukebox outside of the map, or Terraria music boxes. However, this feature would include one object, in which you are able to set now-playing track, track order, which tracks can play, and possibility to play old tracks.

**Comment by random-guy1285** [comment]
I do like this idea but it does not feel like it fits as a block. If it was made as a part of the ui I would understand that

**Comment by JajkoSwinka** [comment]
> I do like this idea but it does not feel like it fits as a block. If it was made as a part of the ui I would understand that 

In the future game might have more tracks, than now, maybe even more unused (just as legacy tracks) and you could use logic to manipulate them. However, logic does not affect any ui feature, I think.

**Comment by itcannotbe** [comment]
Is this another minecraft based suggestion? Reeeeeeeeeeeee.

**Comment by Humanoid-X** [comment]
No, not minecraft based

~~But infinitode based i think~~

**Comment by itcannotbe** [comment]
Look up Minecraft Juke box.

**Comment by OnyxFinger** [comment]
I guess why not ?
