### ISSUE TITLE
No idea here

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2892]

**Comment by sup3r87** [comment]
please read README.md before posting. it clearly states there that anuke will not bother with suggestions in languages he cannot understand

**Comment by Kyllingene** [comment]
This game is about resource management. If you cannot handle managing resources, stop playing Mindustry.

Questo gioco riguarda la gestione delle risorse. Se non riesci a gestire le risorse, smetti di giocare a Mindustry.

**Comment by Humanoid-X** [comment]
No

**Comment by OnyxFinger** [comment]
> This game is about resource management. If you cannot handle managing resources, stop playing Mindustry.
> 
> Questo gioco riguarda la gestione delle risorse. Se non riesci a gestire le risorse, smetti di giocare a Mindustry.

what did he actually say ?

**Comment by oinkymoo** [comment]
advanced buildings should not trivialize what was previously incredibly complex

**Comment by Kyllingene** [comment]
> what did he actually say ?

  They asked for a robot that spawns with your core; what it does is take completed resources from a maximum of X factories within X radius of the core, and deliver them to the core. Their reasoning was that they don't like using conveyors.

**Comment by IVV-NCX** [comment]
Let's see...
You want a robot that brings stuff to base. That's literally just Flares + logic. 
You want a farm that produces everything. That's against the whole point of resource management games like Factorio, Mindustry... They're meant to need complex series of factories... If you want a "build everything factory", that's supposed to be like a massive schematic with sorters, bridges, logic...

And honestly, you're supposed to be the one using the translator, it's literally an EN based game with an EN community with an EN developer. Hell, this isn't "helping", it's oversimplifying the game.

**Comment by Ymabert** [comment]
@IVV-NCX I just want to give some ideas, but you have commented so much just to break me, it is seen, what do you put in the middle of the fact that I use the translator? do you feel it helps to judge? then since you know all the things I wrote how do you do not having read that the idea of ​​the robot and the universal factory were just ideas, which I recommended only to see if they could be feasible or in any case both to point out that you win only thanks to the schemes, which is an annoying thing in my opinion, not it's nice to see people who don't even know about the Farm win they don't go when you change a Filter in plain sight by selecting another material, it's right that it becomes a game for everyone, but because people have to understand what it does, otherwise what sense Does it have the little micro-economy that there is on this game? understand, so I rather ask you to give me  some advice, or tell me why my idea would not make sense (I want to emphasize the fact that I would just like a slightly faster mindustry so that when one starts a game he builds Farms calmly and does not have to see every time if everything works and so he can already think about how to develop the village).

**Comment by IVV-NCX** [comment]
@Ymabert I'm not judging you. I'm saying we're EN based, and thus, EN is the language you shall use. It's in the rules.

It doesn't make sense since the game is made to be complex, as many similar games such as Satisfactory, Factorio, etc are. By making it a game for "everybody", it makes it a game that no longer caters to the people it was meant to cater to. Do you want games like "Apex Legends" to have aim assist? This is the same thing.

Oh, by the way, you don't need to double check too much, just plan it out and make sure nothing weird is in there. Unless you're building a super massive project (storage sectors, schematics, etc), you should be fine to play casually, if you don't want to play "slowly", you can install the "timewarp" mod.

**Comment by Ymabert** [comment]
@IVV-NCX your comment is respectful to me as much as possible, so I answer you by simply saying thank you for the advice.
Actually I just want more simplicity in the game, but not that it becomes another game, in fact mine was just an idea, but if it doesn't go well because it changes the game into bad I can understand it, however I always hope for an update that improves things so that it is simpler, obviously not too much to completely upset mindustry.

**Comment by IVV-NCX** [comment]
@Ymabert I don't check github much, but you can just download a cheats mod. I did that simply because it was too slow and annoying to make factories in every sector. And honestly, games which cater to noobs aren't as fun as ones that cater to pros. Complexity is fun in moderation. Skill up, and move up.

**Comment by Ymabert** [comment]
@IVV-NCX it must also be said that you did not understand, too difficult is not fun in the least, even if you know how to play and I know how to play, so you can say that it is a subjective thing, but one person in 1000000 likes more the real difficulty, of the few resources type and many enemies, I say that if something is difficult but not impossible then every now and then there is doing it, but if it becomes so difficult that it is impossible or very long in time I think it is not fun.

**Comment by IVV-NCX** [comment]
Impossible or highly difficult? From my understanding, it is possible to cheese mindustry with just some unit spam. I beat salt flats by spamming t3 units over and over, along with a few thorium/titanium walls, along with a few lower cost defenses. I'm pretty sure you just need some strategy and such to beat the hardest difficulties.

**Comment by Ymabert** [comment]
@IVV-NCX no, don't worry that I have learned to play well too and I know how to invent perfect strategies when the situation is not the usual but it is more complicated, I have finished some levels by advancing only with many T1 / T2 / T3 in levels that also required T4 , in fact, if I complain about the difficulties I am referring only to the fact that some maps are not difficult or complicated but only boring, but fortunately they only exist online and are created by players and not by Anuke.

**Comment by IVV-NCX** [comment]
Online =/= Anuke. Simple.

**Comment by Ymabert** [comment]
@IVV-NCX I know, that's what I said.
