### ISSUE TITLE
Uranium 

### ISSUE THREAD

**Issue by Progamer0909** [Anuken/Mindustry-Suggestions#2893]
### Describe the content or mechanics you are proposing.

New ores and stuff

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

So the game has more ores 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
Check the "Mods" section of the game.

**Comment by Bottinator22** [comment]
fun fact, the game already had uranium in the past

and yes, we already have Thorium, we don't need uranium. If you want more resources, install some mods

**Comment by Bottinator22** [comment]
More ores does not necessarily make the game better, it just makes the game a bit more complicated

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More ores before. This is a revelation. I would never have thought of adding More ores myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More ores immediately."

**Comment by genNAowl** [comment]
Does the game need more ores? If anything, I think it needs more liquids. Although that's a discussion for another thread.

**Comment by IIINSTINCT** [comment]
No

**Comment by Humanoid-X** [comment]
WTF NO FUCK U CLOSE THIS

**Comment by SoMall-dumpling** [comment]
routerium

**Comment by OnyxFinger** [comment]
> New ores and stuff

like ? At least give examples

> So the game has more ores

yeah but would they be useful, or just here because of having more ores ?

**Comment by oinkymoo** [comment]
what niche would this fill? if it doesn't do anything the answer is "none"
