### ISSUE TITLE
add automatic save backups

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2894]
### Describe the content or mechanics you are proposing.

The idea is to have an openable list in the main menu or planet map that lists backups the game has made. when the game autosaves, a backup is created in the list, so when you reopen the game, if the campaign gets corrupted, you can just click one of the saves the game has made and load back to a fixed save. around 5-50 backups would be stored, and the oldest ones would be deleted automatically. each clickable backup would display a little information, like sectors captured, total elapsed time, etc etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

for the third time, i have lost a lot of progress due to the game corrupting my campaign save. if this feature were in place, me and others suffering from corruptions wouldnt have to manually create backups in the file explorer.

i know some people may say "just create a backup" but almost no videogame in existence expects you to micromanage files just to keep your files safe from (frequent) corruption. you should not need to be savvy with the file explorer to play mindustry without risk. even though it technically is a QoL feature, it is very important to anyone who plays campaign. and unlike a bug fix, this feature will prevent save corruption from being a problem ever again.

All i ask for is a list of past saves, so i can play campaign without needing to play around in the file explorer every time i close the game. again, you should not need to be savvy with file explorer to play mindustry without risk. Plus, this also benefits others on mobile who have a lot harder time with files than anyone else.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
If your game is corrupted frequently, there's probably something wrong with whatever you're playing on.

**Comment by sup3r87** [comment]
> If your game is corrupted frequently, there's probably something wrong with whatever you're playing on.

frequent is kind of a weird word. I think corruptions should be very rare, and for me they happen around once per three months. still, this is enough to make it annoying.
also things like using task manager to close mindustry, unplugging your PC, and a few others can help corrupt saves, which i have had to do before for various reasons. if the power goes out and youre playing mindustry.. good luck

**Comment by itcannotbe** [comment]
Just exist the game properly

**Comment by sup3r87** [comment]
> Just exit the game properly

sometimes even this corrupts the game. last time i closed mindustry, i didnt exit it in any weird way, but it still corrupted

the fact is, basically anything can cause corruption. thats why i ask for a solution.
