### ISSUE TITLE
Add some simple regular expression syntax support for logic "op" and "jump"

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2895]
### Describe the content or mechanics you are proposing.

The title has said.

### Describe how you think this content will improve the game. 

In fact Im not very sure about it now, but if add it, we can achieve more operations in logic(if it is added in a good way.)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
first problem is that isn't even what * does in regex

**Comment by Hexrotor** [comment]
> first problem is that isn't even what * does in regex

I misunderstood it... really embarrassing
