### ISSUE TITLE
Make the construction and reconstruction cost changeable

### ISSUE THREAD

**Issue by SoMall-dumpling** [Anuken/Mindustry-Suggestions#2896]
### Describe the content or mechanics you are proposing.

It's weird that there's a 'Unit production speed multiplier' but no 'Unit production cost multiplier'. 
For example, if you change it to 2.0, then the tier 2 reconstructor will use 80 silicon and 80 graphite to reconstruct instead of 40/40.
It will work on all the unit factories.
Maybe the item capacity need to be multiplied by this multiplier too.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You can make it easier or harder to construct units.
**Why not?**

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SoMall-dumpling** [comment]
And also there's a more complicated version.
That is, you can custom every single (re)construction cost, from ground, air, navy factories to all the 4 reconstructors. But maybe it's not what everyone want, just in case.

**Comment by SoMall-dumpling** [comment]
~~What's more, you will be able to custom health/damage/build cost/build speed/(or size,idk)/etc. of any block or unit~~
~~now you're making mod~~

**Comment by OnyxFinger** [comment]
eh makes sense, and I like it

I could see a use for that, and although it may seem a little bit too complicated, it probably isn't
