### ISSUE TITLE
Battery/surge lightning does practically nothing

### ISSUE THREAD

**Issue by axion014** [Anuken/Mindustry-Suggestions#2897]
Disclaimer: I'm a pretty new player. I have recently completed the campaign, but haven't played PvP or participated in the community before.

### Describe what you would like changed, and why.

Batteries and surge alloys produce lightning when destroyed. I expect this to be a liability for bases involving them, but when tested in sandbox, shooting down a large battery does not even destroy an adjacent router(or any 40hp block, but why not router?), let alone causing a chain reaction.

Since then I've looked at the source code. The hell? It says a destroyed thing spawns up to 8 lightnings – each with **literally 3 damage**. That's a third of a copper duo bullet. Even if the target is wet, and all 8 lightnings hit, it's 136 damage tops. Note that blocks cannot be wet. Also for reference, swarmer and cyclone with surge ammo does 10 and 13 lightning damage respectively.

Making them do something would result in more decisions:
- Do I keep charged stuff far from each other, put plast walls between them, or take the risk and save space?
- Bombing with explosives would do more damage to one target, but struggle to pierce through tankier blocks. Using lightnings, opposites could be the case, though it is probably never worth spending surge for that. There is a case for increasing per-item charge, but that's kinda out of scope.

### Describe the changes you want to propose. Include possible alternatives.

Make the lightning damage scale with charge amount. Something like `sqrt(charge)` should be reasonably balanced, but whatever; I'm nobody to decide. It's fine if you decide to keep it larger but still constant damage.

If the lightnings are never meant to do damage, then the whole mechanism may as well be not there, but since it's still around I would assume otherwise.

**Comment by RealYeet** [comment]
Agreed, as a seasoned player I would say that lightnings needs to be buffed a lot. If I had to guess, the best possible solution is the make it scale with charge. (Although lag and ping might go through the roof)
