### ISSUE TITLE
All idiot commenti here pls

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2898]

**Comment by joshuaptfan** [comment]
TLDR: "Resource management is hard, please add new OP production blocks so I can cheat."

If you are lazy, just install one of the many cheat mods that already exist.

**Comment by OnyxFinger** [comment]
bruh

**Comment by genNAowl** [comment]
Literally though. Git gud.

**Comment by Bottinator22** [comment]
also barely understandable

**Comment by oinkymoo** [comment]
same thing i said on the other one. a more advanced building should not trivialize things that were previously somewhat complex

**Comment by MHeMoTexHuK** [comment]
"everything you need" in the title already marks this suggestion as a complete shitpost.
Like, seriously, why would you want to have OP blocks that do everything for you and nivilate the point of the game?

**Comment by SMOLKEYS** [comment]
An overly serious s**tpost huh?

**Comment by EclipsePlays** [comment]
> So basically: Git gud?

Yes, git gud. 

If you are experienced enough at the game, you'll see that advancing in campaign or some sort is easy, if you know what you are doing.

**Comment by Bottinator22** [comment]
wow he changed the title

**Comment by Ymabert** [comment]
@Bottinator22 so what?  just by doing so I replied to all the nice guys who came and started insulting my ideas, so sorry is it but what do you want from me? next time they learn to respect others and the thoughts of others.

**Comment by Bottinator22** [comment]
Maybe just... don't suggest things if people disagreeing seems to hurt you so much

**Comment by Ymabert** [comment]
@Bottinator22 yes, I just try to enforce my suggestion, I would not like to make suggestions and then maybe try to convince people even if they do not approve, I simply try to give all the pros and cons about my idea.

**Comment by joshuaptfan** [comment]
The whole point of this place of discussion is to allow for *debate* on each suggestion. That means there may be arguments either in favor of or *against* each suggestion.

It may take some thick skin to make suggestions here. Don't expect to be coddled.

**Comment by Ymabert** [comment]
@joshuaptfan yes but I respect everyone's opinion and thought when I read the other suggestions, I thought it was a mutual thing, instead I just feel useless criticism, since when I give a suggestion I just want people to help me improve as much as possible my idea, not that you criticize me unnecessarily, that's why I think many here are just poor balls, but I understand what you mean and you were right to say it.
