### ISSUE TITLE
Conveyor Anchors

### ISSUE THREAD

**Issue by obligax** [Anuken/Mindustry-Suggestions#2899]
### Describe the content or mechanics you are proposing.

Conveyor anchors. Just place then on a conveyor and rotate it and the side in which the anchor is rotated will prevent machines from outputting from said conveyor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Just a QOL change that simplifies schematics and makes it cheaper instead of using armored conveyors or junctions.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
Armored conveyors and junctions work just fine, this would add unnecessary complexity to the game that we don't need

**Comment by genNAowl** [comment]
Definitely feels similar to the suggestions about IO configurations before.

**Comment by oinkymoo** [comment]
^
