### ISSUE TITLE
Please allow downloading Steam workshop mods without owning the steam version of the game

### ISSUE THREAD

**Issue by deee167** [Anuken/Mindustry-Suggestions#29]
**Describe the content or mechanics you are proposing.**

Please allow downloading Steam workshop mods without owning the steam version of the game.
I read that it's a checkbox on steam that you enable downloading mods through the API that is off by default unless you enable it.

**Describe how you think this content will improve the game. If you're proposing new content, 

It will allow getting popular maps as an example that are not available on discord and also it's a lot easier to get the maps from a maps site instead of scrolling through pages and pages of discord to find a map.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Katsute** [comment]
The uploading of schematics could autofill the schematic code into the workshop description as a potential solution.

**Comment by deee167** [comment]
I want this for maps most importantly right now, but also for all workshop content.  As a workaround this would only work for blueprints but that would be better then how blueprints work now.  Thanks for the suggestion.

**Comment by Victorsueca** [comment]
IIRC Steam Workshop has a feature to dowload files manually instead of using the "Subscribe" button which requieres you to own the game. The feature is just disabled by default and needs to be enabled by the game developer.

**Comment by DeltaNedas** [comment]
no

**Comment by Victorsueca** [comment]
> no

That's not very... explanatory 😅
Why though?
If I'm not wrong about how steam workshop works, people who bought the game still get the one-click-does-it-all "Subscribe" button while people who are playing the open-source version would get the chance to manually download and place map and mod files that may have been uploaded only to the workshop and are not available elsewhere.
I think the reason why most games don't allow manual downloads is because, depending on each game's modding system, mods may include or link against copyrighted game assets, and in any case, if the game is only available on steam, they would just make modding pirated copies easier.
None of that feels like it applies to this game, so I think manual downloads on the workshop should be allowed.

Of course, @Anuken should have the final say on this.

**Comment by DeltaNedas** [comment]
steam version is still open source

**Comment by deee167** [comment]
This still isn't working.  @Anuken can you please change the steam option to allow downloading mods.  It's just one checkbox from what people say.

**Comment by itcannotbe** [comment]
I have a hard time to wrap my head around the purpose of this request. The game is paid on steam. While remaing free through other means. Isn't the purpose of steam is for steam features?

**Comment by deee167** [comment]
it's impossible to get good new maps outside the workshop for non-steam owners.  it's a nice gesture to allow others to get updated maps, mods etc too

**Comment by Victorsueca** [comment]
> I have a hard time to wrap my head around the purpose of this request. The game is paid on steam. While remaing free through other means. Isn't the purpose of steam is for steam features?

The advertised features for the steam version are:

> [...]seamless multiplayer and map browsing/Workshop support.

([source](https://anuke.itch.io/mindustry))
This would suggest that the selling point is being able to just one-click-install any mods or maps
However, exclusive access to maps uploaded by the community to the workshop is never mentioned AFAIK.
Lots of creators are uploading their creations to other places such as the Mindustry Discord server so they are accessible to people who don't own the game, but many others aren't.
Allowing manual downloads from the Steam Workshop would allow people who don't own the game to manually download and place map and mod files in a process that's not much different from downloading mods/maps from other places, while people who bought the game are still the only ones that get the Subscribe button in the Steam Workshop.
I think effortless installation of mods and maps plus Steam networking for easy multiplayer is the selling point of the Steam version.

**Comment by deee167** [comment]
> 
> 
> > I have a hard time to wrap my head around the purpose of this request. The game is paid on steam. While remaing free through other means. Isn't the purpose of steam is for steam features?
> 
> The advertised features for the steam version are:
> 
> > [...]seamless multiplayer and map browsing/Workshop support.
> 
> ([source](https://anuke.itch.io/mindustry))
> 
> This would suggest that the selling point is being able to just one-click-install any mods or maps
> However, exclusive access to maps uploaded by the community to the workshop is never mentioned AFAIK.
> Lots of creators are uploading their creations to other places such as the Mindustry Discord server so they are accessible to people who don't own the game, but many others aren't.
> Allowing manual downloads from the Steam Workshop would allow people who don't own the game to manually download and place map and mod files in a process that's not much different from downloading mods/maps from other places, while people who bought the game are still the only ones that get the Subscribe button in the Steam Workshop.
> I may be wrong, but I think effortless installation of mods and maps plus Steam networking for easy multiplayer plus achievements are the selling point of the Steam version.

You can buy the game by donating outside of steam as well.  Are you aware of this?

Also maps on discord can't even be counted as a valid source of maps as they are far behind the versions on steam and are extremely hard to find and download.  Scrolling through hundreds of older "pages" of the discord map page takes forever and it's hard to use and navigate.

Enabling steam workshop downloads for non-steam users is a nice gesture and doesn't detract from the benefits of getting it on steam.  Ie. such benefits as easy mod installation with the subscribe button, easy multiplayer etc.

**Comment by Victorsueca** [comment]
@deee167 My point exactly, as I said, exclusive access to maps uploaded by the community to the workshop was never an advertised selling point, many maps are not available on the discord server, and as you said (and I forgot to mention), the discord server is a pain to browse for updated maps.

**Comment by deee167** [comment]
> 
> 
> @deee167 My point exactly, as I said, exclusive access to maps uploaded by the community to the workshop was never an advertised selling point, only effortless installation was, many maps are not available on the discord server, and as you said (and I forgot to mention), the discord server is a pain to browse for updated maps.

Does Anuken check these bug posts much as there are no status changes or comments on the issues even though they were open for a long time now.

**Comment by itcannotbe** [comment]
Actually downloading mods/maps on not steam is also easy. The significant disadvantage is stuff uploaded on the steam workshop isn't accessible to people not on steam.


Critical point though. Maps and Mods often break with updates which making digging for a long buried Maps or Mods pointless.

**Comment by deee167** [comment]
> 
> 
> Actually downloading mods/maps on not steam is also easy. The significant disadvantage is stuff uploaded on the steam workshop isn't accessible to people not on steam.
> 
> Critical point though. Maps and Mods often break with updates which making digging for a long buried Maps or Mods pointless.

Also discord doesn't have as many maps and the ones that are there are not as up to date as steam.  So really discord is not a good source of maps.

**Comment by steamworkshopdownloader** [comment]
We've manually added support for this to our site. Hope this will help.

**Comment by deee167** [comment]
> 
> 
> We've manually added support for this to our site. Hope this will help. 100 v

What do you mean, to your site?  I don't see any links on your itch.io site to download maps and mods and this doesn't seem to work to download maps from steam workshop.

Thanks

**Comment by maurits150** [comment]
We run a download service to retrieve files from the steam workshop, and support hundreds of games. We saw demand for this game and added support for it. Please try at steamworkshopdownloader.io. We are independent and not affiliated with steam or the developer of the game.

**Comment by steamworkshopdownloader** [comment]
> > We've manually added support for this to our site. Hope this will help. 100 v
> 
> What do you mean, to your site? I don't see any links on your itch.io site to download maps and mods and this doesn't seem to work to download maps from steam workshop.
> 
> Thanks

We run a download service to retrieve files from the steam workshop, and support hundreds of games. We saw demand for this game and added support for it. Please try at steamworkshopdownloader.io. We are independent and not affiliated with steam or the developer of the game.

**Comment by DeltaNedas** [comment]
issue can be closed @deee167 @Anuken

**Comment by Bohaska** [comment]
> issue can be closed @deee167 @Anuken

@DeltaNedas Did you read that big file saying why Anuken doesn’t close issues

**Comment by Kyllingene** [comment]
And now Anuken has been pinged twice. Please remember to put spaces between the @'s and the names when you do not desire to ping them. Also, @deee167, please close.
