### ISSUE TITLE
Upgraded Versions of more Factories

### ISSUE THREAD

**Issue by mnrsU** [Anuken/Mindustry-Suggestions#290]
**Describe the content or mechanics you are proposing.**

I think that Mindustry could include some upgraded versions of built in factories. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We have a upgraded graphite press and an upgraded silicon smelter, but we don't have any other upgraded versions for factories. How about a 3x3 plastanium compressor or a better pulverizer? 
I know that these silicon smelters and graphite press's only have upgraded versions because the resource they create are valued in both multiplayer and campaign, but I think that other upgraded factories would be nice too. 

To avoid cluttering the crafting section up, you could add another category just for upgraded factories.

Here is a sprite of what an upgraded plastanium compressor might look like: 

![plastanium-condenser](https://user-images.githubusercontent.com/62972692/86671895-f3920500-bfaa-11ea-8ac2-5495c4668ee9.png)

I am completely fine with having this suggestion rejected, and I am already pretty content with how Mindustry is now, so its fine if nobody thinks this is a good idea. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SupremeTurtle** [comment]
These upgraded blocks will probably only be useful for super late game, so not really agreeing with this.

**Comment by mnrsU** [comment]
> These upgraded blocks will probably only be useful for super late game, so not really agreeing with this.

Hmm. I kind of get what your saying, but I did a poll in reddit, and the community there seemed to like it. Some people like going super late game, and I believe that late game itself is going to get reworked, with the supposedly better boss fights. What I'm saying is that more people will probably start trying to go late game, and these blocks MIGHT (only might) have a use. 
(It also might be of use to those people who are trying grind resources and optimize their base)

**Comment by Syncinus** [comment]
Multiplayer servers can get to the level this would be useful in 20-30 minutes, so in singleplayer mode they may be a bit useful, but in multiplayer they would be awesome.

**Comment by SupremeTurtle** [comment]
That is, if Multiplayer isn't full of newbies that clogs everything and waste resources..

**Comment by mnrsU** [comment]
> That is, if Multiplayer isn't full of newbies that clogs everything and waste resources..

True, but the same goes for sneks, and people still use them (I know sneks are super useful, but still...)

**Comment by DeltaNedas** [comment]
siiclon pres
mitaglis pres
grafit smiltar

**Comment by stuffyAI** [comment]
This would sure make the game easier, but what I think would be more interesting is more efficient factories.

Basically part of the challenge is making compact crafts and production arrays, if you compress all that you end up with so much freedom you dont have to think how to build something anymore. I like how the game is still called _Mind_ustry.

**Comment by mnrsU** [comment]
Bonk
