### ISSUE TITLE
Add "follow" for unitcontrol

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2900]
### Describe the content or mechanics you are proposing.

Now we have unit targetp, it helps unit aim the target unit automatically.
If you used to make some unit attack logic, you may know that if you have too many units(about 15 or more) and sometimes they find some enemies by "unitrader", it's hard to decrease latency of "unitapproach", esp for some fast moving enemies. Because the logic processor need to do this:

`unitrader to result`
`sensor x of result`
`sensor y of result`
`approach to x y`
`targetp result`

Well, actually it doesn't look very complicated, but remember, enemy coordinates are dynamic but what the coordinates we have sensed won't be changed until the next sense. That's why there's no one uses "unit target x y" to shoot units, it can barely hit the enemy.
"Targetp" is a better "Target" for hit units, so I would like to have a better "approach" for tracking unit, it works similarly to targetp, only for tracking units, and can be set a radius value like "approach".
With this, processor just need to do this:

`unitrader to result`
`follow result`
`targetp result`

And even if the processor is already controlling the next unit, the previous unit will still keep "targetp" and "follow" for a while.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Compared with "approach", the delay of "follow" will be decreased greatly and logic will work better. 
In fact, a similar operation already exist: When you are controlling a air unit to take a ground unit, your unit will "follow" the ground unit automatically until can take it.
Or a more intuitive example: Oct

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
Kinda feels like it will add bloat, but I can see where this is coming from. Maybe just approachp for consistency?

**Comment by Hexrotor** [comment]
> Kinda feels like it will add bloat, but I can see where this is coming from. Maybe just approachp for consistency?

"targetp" means "pre-target", but follow a unit needn't "pre", maybe?

**Comment by Rex-Hm** [comment]
target prediction*
