### ISSUE TITLE
Add a description of all logic commands in game or wiki

### ISSUE THREAD

**Issue by VladBlad3** [Anuken/Mindustry-Suggestions#2901]
### Describe the content or mechanics you are proposing.

A lot of logic commands arguments  and keywords used in them don't have any description in game or wiki, and it is strange that to get a manual you have to download a separate mod. Adding a tutorial and all descriptions in game would be nice, but if there would be at least their description in games wiki it would already be a big improvement.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make the game much more friendly to new players

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> It will make the game much more friendly to new players

Logic is never friendly to new players.

**Comment by genNAowl** [comment]
I think of it as the geometry dash editor or minecraft redstone. Confusing to use, and while there are tutorials online, the best way you can learn it is by doing it yourself.

**Comment by V-I-L** [comment]
It is GOOD IDEA!
