### ISSUE TITLE
Add more hitboxes for laser attacks

### ISSUE THREAD

**Issue by Dryehm** [Anuken/Mindustry-Suggestions#2903]
### Describe the content or mechanics you are proposing.

add more hitboxes for laser attacks because things like this looks wrong and the part where the laser isn't even blocked by the wall is a bit disappointing
![0](https://user-images.githubusercontent.com/79123285/130822821-9b9d1cbf-27bd-467c-8d4a-96d488fa336c.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it makes vela not be bad.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
I don't think there's any efficient way to implement this (as all require just extra raycasting)
