### ISSUE TITLE
Quad rebalance

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2904]
### Describe what you would like changed, and why.

Make quad be slowed down when reloading, just like vela - would stop it from just running around bases aimlessly and causing massive damage to every factory at once - with a slowdown, quad will actually be vulnerable while bombing something and will have to choose its targets carefully

### Describe the changes you want to propose. Include possible alternatives.

Make quad apply slowed on itself when reloading (perhaps for several times the reload time?), but revert its base speed to 1.3

**Comment by OnyxFinger** [comment]
> > I'll say it is
> 
> Really depends on map size tbh

many people make gigantic 500×500 maps for no reason. Currently, the "best" map size I know is 350×350 : not too hard to defend, not too small either.
