### ISSUE TITLE
Moons

### ISSUE THREAD

**Issue by staticalliam7** [Anuken/Mindustry-Suggestions#2906]
### Describe the content or mechanics you are proposing.

I am proposing that planets get moons (hence the title). This would be a small planet near the main planet, mostly as a side mission. It might have, idk, like, 20 sectors or something, just a little side quest

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it would be a nice quick thing,  as like a break from the main planet. It could possibly add some lore..

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by firstcreator48** [comment]
i think its fine with the side quests such as:
the moon being accessible with a said requirements such as thorium walls and cyclones.
this is perfectly fine, as long as it doesn't interfere withe the player progression

**Comment by OnyxFinger** [comment]
btw I like this one

**Comment by firstcreator48** [comment]
> btw I like this one, it would just be a bit of work simply for the sake of logic

yes
