### ISSUE TITLE
This is the real problem for me (the rest is perfect as well).

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2909]
### Describe what you would like changed, and why.

it is a good game and can become a game and for everyone, nabbi and pro, with the right updates, I have exposed a problem, which in my opinion is very important, and in addition to having exposed the problem of slowness I have given some ideas, from which you can take a cue, you don't have to take everything I recommend adding as if it were the only way, you simply listen to me and based on what I tell you / advice you tell me yours, always with mutual respect, which I do not have received since some have already started with the prejudice of "this guy is just an ordinary jerk, a nabbo who does not want to learn to play probably" but no, I finished the campaign, I do almost everything online, I solve the problems of the Farm that do not work obviously placed by the nabbi and the errors that I see I also understand that the game must be simplified, as good as it is, it would be better if it were more, simple, I am not saying that you have to create a universal fucking factory or a r  obot that manages Farms, these are just two ideas that I had, I know that they are not the best, they would change the game too much and it would become just an attack-defend and not an attack-defend and create a village, full of farms, from which they arrive at the core many types of materials, so if I can give you a real advice this time, create 2X2 material conveyors for example, which according to how you want to divide the types of incoming materials at the exit, this would make Farming much faster and it would also give the possibility to those who do not have schematics to evolve quickly.  Lastly, I would like the tapes (even if they are superfluous when you have overhead tapes) when you activate the "angle" the computer automatically generates them diagonally according to how you want, from one point to another by simply clicking with the mouse, the rest of the game is perfect, all that is missing is that it makes the boom like Among Us did and that it is a game to take also on Twich, it would be a great thing, however you know that I am never wrong about beautiful games, I was playing Among Us about a year before it became famous and very popular with youtubers / streamers.  I hope that at least you will listen to me and understand that the only problem of mindustry is slowness, it is obvious that if one does not want to create the tapes, he does not even play with them ... otherwise where is the beauty of Farming?  Thanks for reading this far I only hope for constructive comments and not useless Flam.

### Describe the changes you want to propose. Include possible alternatives.

Thx, I hope I have at least clarified what I think makes the game boring and my intentions regarding the changes I hope you make.

**Comment by oinkymoo** [comment]
> an object that functions as a distributor and divider

we already have this. it's called a router. you can unlock them within minutes of starting

> I thought it would be nice to have the possibility to build the ribbons diagonally by activating the angle setting

do you mean like, individual pieces of conveyor that go diagonally, or just following the diagonal more closely like other blocks do? because one of those is much more viable than the other

**Comment by Ymabert** [comment]
@oinkymoo I would like that when I select the tapes, overhead tapes ... and draw diagonally, clicking from one point to another, the computer automatically generates the path of the tape in the best way.

**Comment by oinkymoo** [comment]
it tries, as far as i can guess, to do it in the minimum number of belts, but if you go too far or past too many obstacles, it just gives up
