### ISSUE TITLE
Silicon masterwork core

### ISSUE THREAD

**Issue by MrkaDotJpg** [Anuken/Mindustry-Suggestions#291]
Like a silicon Smelter, but faster and bigger, like with the graphite press

I think this would be good because it saves space, and makes silicon production way easier. And with the name, you could make it really big and powerful, but requires a lot of water (14.0) and energy

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by mnrsU** [comment]
There's already an upgraded silicone smelter, called "silicone crucible", in Mindustry 6.0

**Comment by MrkaDotJpg** [comment]
Okay, didn't know that, thanks

**Comment by SupremeTurtle** [comment]
Can you close this
