### ISSUE TITLE
Sectors under attack

### ISSUE THREAD

**Issue by dfbsfdth** [Anuken/Mindustry-Suggestions#2910]
### Describe what you would like changed, and why.

In the campaign, when the sector is under attack there is no proper simulation, and all of the player buildings are completly shut

### Describe the changes you want to propose. Include possible alternatives.

I would realy aprtciate if You would make a proper simulation 
_ps. english is not my first language_

**Comment by Ksawi999** [comment]
> Yeah, but practically when I was playing campaign never felt there is a lag or my battery was draining fast, but this became clear and problematic when started playing online.
> Apparently online games much heavier than campaign, at least for me.

On my phone everything works at 60 FPS, so I don't have much comparison...
