### ISSUE TITLE
Remember Last Server, Sort by Ping, Sort by Players, filter by Name/Search and other QoL features

### ISSUE THREAD

**Issue by katastic** [Anuken/Mindustry-Suggestions#2913]
### Describe the content or mechanics you are proposing.

Please add the usual QoL features for browsing, finding servers.

 - Sort by Ping
 - Filter by Ping [less than X ping]
 - Sort by Players
 - Hide empty servers
 - Hide full servers
 - Rejoin last server [or a list of last 3 most recent used servers]
 - Filter by language requirement (ala German, English, Korean, etc)
 - Also since everyone uses Discords for their servers, it'd be great if you could click the link and load it in your browser instead of memorizing the link and typing it manually
 - Larger description box for servers in UI since it appears most just cut off in the UI [perhaps scrolling ticker if its too long?]

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Any time I play multiplayer, I basically have to scan the entire list, read every player count, and ping, to select a server. And even if I know which server I played on, if it crashes or go down for some reason, I have to traverse the full list again.

This issue will become greater and greater the larger the amount of servers / game popularity increases.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ymabert** [comment]
@katastic yours would be a nice idea, if the developers aimed only to improve the game and not to evolve it by adding more and more things, it would be better, at least for now, because it is better to solve these basic problems rather than leave them to continue to evolve the game, I think your idea is to be followed, from top to bottom.  Then a future, when it is balanced and perfect this game can evolve, but now some things have to be fixed.

**Comment by katastic** [comment]
> this is because the Discord link is simply a bit of text in the description, this would require it to be a special data point, and the language requirement is the same way, except it isn't even in the description a lot of the time.

This is actually really easy to accomplish. It's a simple regex match for a discord link which has a known signature, that fires off a  call to the OS default browser. For example, in Windows to use the default browser [for proper portability] its:

`rundll32` url.dll,FileProtocolHandler https://www.google.com

Prior art examples:

 - Using Python to match Discord links: https://gist.github.com/drakantas/ec2c524b95a688b1618d7cc810d490c4

 - A regex matcher:  https://www.regextester.com/99527
 
I don't have any Java experience but I could probably take a moment and submit a pull if need be. But I would imagine Anuke would be able to do it in about ten minutes vs hours for me to familiarize myself with the toolchain and source.
