### ISSUE TITLE
stop omura bullet "trail" if the projectile gets destroyed/is stopped

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2914]
### Describe the content or mechanics you are proposing.

right now, omura's gun shoots a projectile and small "diamonds" appear as effects. the "diamonds" go as long as omura's bullet range is. however, these diamonds seem to ignore when projectiles are destroyed. so omura can shoot at a wall, and even if it doesnt break through it, the "diamonds" effect goes through the walls anyway. which is a bit distorting in my opinion.
here's a picture of what i'm describing in action:
![Screenshot 2021-08-26 222351](https://user-images.githubusercontent.com/47570570/131067058-c079f9c1-7ebd-4cd6-8e3c-65387a96badc.png)

my suggestion is to simply remove these "diamonds" that exist where the projectile isnt, in some way. the diamonds are a little distorting and just dont make sense.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it makes the game make a little more sense. this is a small, visual request, and nothing more.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
This is actually just a bug. https://github.com/Anuken/Mindustry/commit/6ca28553651486bb32466fea81c26c3403a3de26
