### ISSUE TITLE
(Discord) Add #mods channel

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2915]
### Describe what you would like changed, and why.

It would be nice to have a channel where all newly released mods are posted, so people can actually know when mods are out and what are they about. We already have maps, schematics, plugins, etc, why not have this?

### Describe the changes you want to propose. Include possible alternatives.

That is pretty much it. A #mods channel that automatically posts all mods released, like the github bot does for new PRs and issues.

**Comment by firstcreator48** [comment]
> > Well, the #mods channel exists, or atleast it _did_ before Anuke closed it off.
> > I do like the idea of #mods being brought back to the public though, but i also think that the #mods channel is slightly useless because the **Mod Browser** exists.
> 
> Oh, so it _did_ exist? But I still prefer seeing them nicely listed on discord as they come out

it DID exist but for a short time since the mod browser now exists.
