### ISSUE TITLE
Double click to edit logic

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2917]
### Describe what you would like changed, and why.

How about double click to edit logic block?
You know, it's hard to link a 1x1 block which under a micro processor. I tried this for more than 20 times but finally failed.😭
![184decd3721346b988dac4b4b48b181f](https://user-images.githubusercontent.com/45112661/131208389-d1380885-92f8-4818-b4cd-4c2056a7048e.jpg)

### Describe the changes you want to propose. Include possible alternatives.

Double click to edit logic, it will make the game easier, I hope.

**Comment by oinkymoo** [comment]
might be harder for new players to figure out. maybe move the edit button onto the processor?

**Comment by Ymabert** [comment]
@Hexrotor @oinkymoo simply the key must not be under the processor but above and must be a minimum transparent, perhaps it is better.

**Comment by Hexrotor** [comment]
> might be harder for new players to figure out. maybe move the edit button onto the processor?

Nice idea, to some extent, this is also double-click

**Comment by Ymabert** [comment]
@Hexrotor with a double click you go to remove all the selection things, so in my opinion it would be better if the edit button comes out somewhere in the screen as a setting, so doing the double click will always have the usual function of connecting to everything in range / remove link

**Comment by Hexrotor** [comment]
> @Hexrotor with a double click you go to remove all the selection things, so in my opinion it would be better if the edit button comes out somewhere in the screen as a setting, so doing the double click will always have the usual function of connecting to everything in range / remove link

I know that. Btw logic can't and shouldn't links by double click, it will cause some problems such as `getlink`.

**Comment by Humanoid-X** [comment]
@Ymabert omg u make me feel smart

**Comment by Humanoid-X** [comment]
@Ymabert Ok sorry, I saw your secong comment. but ur first comment so dumb lol

**Comment by SMOLKEYS** [comment]
> 20 times but finally failed.😭

*visible confusion*

**Comment by Ymabert** [comment]
@Humanoid-X apart from the fact that I do not know English, so my comments are even more stupid, but rather than having the processors that give these problems, I think it is better not to be able to select all / remove all selections with the double click, but it has more It makes sense to make the edit button appear in static places on the screen.

**Comment by Humanoid-X** [comment]
@Ymabert ok, I understand if you do not know egnilsh. that make sense, my bad
