### ISSUE TITLE
extra info for unit control target

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2918]
### Describe the content or mechanics you are proposing.

make the UnitControl: target can select which weapon to shot start at 0, put -1 to select all weapon

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

seperating weapon shooting for better targeting

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i don't think this is necessary. in the rare event that a unit has multiple weapons, why would you not want them all to focus down a single target

**Comment by MrDuck557** [comment]
The very rare event that you're using minke to attack
Both weapons can't hit the same enemy (artillery and anti-air)

**Comment by vinhsad** [comment]
1. because yes
2. there's modded unit
3. normal proc thing can't do this

**Comment by Humanoid-X** [comment]
hm yes i think

**Comment by Hexrotor** [comment]
But some units have repair weapons, how can u control them if u selected?

**Comment by Kyllingene** [comment]
> 1. because yes
> 2. there's modded unit
> 3. normal proc thing can't do this

1. Because you have no better reasons
2. We're not adding a feature to processors only useful for modded units
3. How about super processor drill then since normal proc can't

**Comment by oinkymoo** [comment]
> 2\. there's modded unit

ok so? the only case i'm aware of where such a feature would even be useful is if a modded unit has both AA and artillery weapons, like minke. mods don't change the fact that attacking multiple targets is pointless unless some of your weapons can't hit the first target
