### ISSUE TITLE
A new conveyor

### ISSUE THREAD

**Issue by TotalFoc** [Anuken/Mindustry-Suggestions#292]
A conveyor belt that will changes position(like <--<--,<--^) that will change if a certain amount of time or items pass through it i thought about a new silicon factory that will need something like this and it will be great even for others factories or defense it can be 1x1 or 2x2 but it can make stuff faster
1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by TotalFoc** [comment]
First i didn't know if i could delete the other text but i did it because the "rule" didn't say something about it

**Comment by Anuken** [comment]
This is too complex and specific to be added as a separate block.

**Comment by ILiekMelons** [comment]
this is just a router

**Comment by TotalFoc** [comment]
> this is just a router

A router can't be controlled to separet in a direction until a certain amount of time or items pass it so it can change the direction

**Comment by itcannotbe** [comment]
it is just a glorified router.

Do you know that routers aren't even random?

They round robin all possible outputs. It is easy to make a 1: upto 8 spliter using router or the larger block distributor.

**Comment by TotalFoc** [comment]
> it is just a glorified router.
> 
> Do you know that routers aren't even random?
> 
> They round robin all possible outputs. It is easy to make a 1: upto 8 spliter using router or the larger block distributor.

Do you even understand english(i don't think because i am not the best writer in english), something that can move items to a single direction until a certain amount of time or items pass it,  do you understand, <---<---(straight(is in line) conveyor belt) can be changed to <---^(is not in line) without the player influence

**Comment by itcannotbe** [comment]
`A conveyor belt that will changes position(like <--<--,<--^) that will change if a certain amount ~~of time or ~~ items pass through it`
A glorified splitter.

Do you have anything to say?

**Comment by TotalFoc** [comment]
> [A conveyor belt that will changes position(like <--<--,<--^) that will change if a certain amount items pass through it](https://github.com/Anuken/Mindustry-Suggestions/issues/292#issue-653694087)
> = A glorified splitter.
> 
> Do you have anything to say?

A mechanical part that will allows the items to go in a single SINGLE direction DIRECTION until UNTIL a certain amount of time TIME or items ITEMS pass it PASS IT and then it will CHANGE THE DIRECTION OF THE FLOW not a router nor a splitter a mechanical part with logic
