### ISSUE TITLE
Map Editor QoL

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2921]
### Describe the content or mechanics you are proposing.

A few tools to make map editor's lives easier.

**Line tool shows how long it is**
This allows for using it as a ruler.

**Live mirror mode**
Works essentially like the 'mirror' generation tool, except it happens as you're painting the map.
Might be a bit unnecessary.

**Map grid**
Shows a grid, that splits the map into x*x, purely visual for measuring

**Highlight map center**
Once you click in center, highlight the center block(s) for a few seconds.

**Diagonal line tool**
Similar to the orthogonal line tool setting, a setting to make it draw (perfect) diagonal lines.

 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'll help with mapper's struggles, QoL in general.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ineedause** [comment]
idk what you are trying to say exactly, but a ruler sounds really good.

**Comment by OnyxFinger** [comment]
yup, I pretty much want all of this, but the mirror might be a bit unnecessary just like you said. Other than that, every QoL sounds good to me, and will avoid pain

**Comment by oinkymoo** [comment]
i dont quite get highlight map center but i support all of this

**Comment by sup3r87** [comment]
there have been so many suggestions to improve the map editor i wont even try to link them all.

however i do wish anuke would get the memo about all them. or maybe he has but its a second hand priority.

**Comment by OnyxFinger** [comment]
> there have been so many suggestions to improve the map editor i wont even try to link them all.
> 
> however i do wish anuke would get the memo about all them. or maybe he has but its a second hand priority.

duplicates are allowed.
