### ISSUE TITLE
A tweak in cultivator/impact ratios

### ISSUE THREAD

**Issue by seung882** [Anuken/Mindustry-Suggestions#2924]
### Describe what you would like changed, and why.

When I am referring to impact ratios here, I am assuming that we are using internal coal (via spore presses and coal centrifuges), as that is the most common in impact schematics.

The ratio of the cultivator is currently very bad with impacts/scrapacts, one of its most common use cases (possibly the most common). Scrapacts/impacts use 1.07 cultivators, which is very bad ratios. Even if the intention was to make the ratios of bigger impact schematics better, and 1 impact ratios worse, I feel that this is a bit overkill. For example, in order to get a good ratio usage out of each cultivator, you currently have to build 14 impacts, which is a very high number that no one has attempted because of its size, the biggest we currently have built is 5.

### Describe the changes you want to propose. Include possible alternatives.

Tune the ratios of cultivators up/down a notch so the ratios are more even. Depending on what you want people to do with impacts and cultivators, if you want to make the ratios overall better, you could increase cultivator output to 1 spore per 1.5 second, with 20 water input (this is the most ideal in my biased opinion, this means 1 cultivator per impact). If you do not want the ratios of 1 impact to be good, you could make so the needed amount of cultivator per impact is more even (such as 1.2, 1.5 culti per impact), rather than such an odd number.

**Comment by Kryvytsky** [comment]
I don't get idea of this suggestion.
Doesn't already Impact Reactor use 1 cultivator to run?

**Comment by seung882** [comment]
> I don't get idea of this suggestion.
> Doesn't already Impact Reactor use 1 cultivator to run?

> When I am referring to impact ratios here, I am assuming that we are using internal coal (via spore presses and coal centrifuge)

**Comment by genNAowl** [comment]
As always, don't forget what an annoyance it will be for players to have to update all their impact schematics. v7.0 is a bit too far in development for a change like this to be made, in my opinion.
