### ISSUE TITLE
With bot Number shown 

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#2925]
**Describe what you would like changed, and why.**

What I wanted to change is that there need to be all the number of different types of bots shown in the command center. Because it is really hard to show the bot number. They only can be shown in the factory when they are under constructing.
When finished some attacking maps, I do not even know how many droids I still have left, and so that made me count them all but when they are stuck together, there is no way how to even count them properly. 

 **Describe the changes you want to propose. Include Describe the changes you want to propose** 

What I wanted to change is to add the bot kind and numbers when clicked to the command center, and so that can make people's brain clear but not messed up with how  many there are in the field attacking...

**Comment by GuestUser25** [comment]
I can not find the template of the idea text.

**Comment by GuestUser25** [comment]
Also, this is not in trello yet
Not in the "no making list"
Also I knew mindustry pretty well...

**Comment by NemesisTheory** [comment]
Well, there are several logic schematics to show the number of specific units you currently have, this is a good suggestion yes, but if there's already something similar to it existing, why should you add it?. Not to be rude but you can just download the schematic type i mentioned earlier, ask in #help or other channels to find the schematic. It's much easier than adding a new QoL feature.

**Comment by OnyxFinger** [comment]
> Well, there are several logic schematics to show the number of specific units you currently have, this is a good suggestion yes, but if there's already something similar to it existing, why should you add it?. Not to be rude but you can just download the schematic type i mentioned earlier, ask in #help or other channels to find the schematic. It's much easier than adding a new QoL feature.

oh boy, I'm not here before someone says logic

I am getting tired of saying it, so I'm gonna be clear : this argument doesn't hold the line, ask for other people to know why

**Comment by Ymabert** [comment]
@GuestUser25 yes, it is not an essential thing but it is for completeness for the game
