### ISSUE TITLE
Adding a new logic feature.

### ISSUE THREAD

**Issue by fl215** [Anuken/Mindustry-Suggestions#2926]
### Describe the content or mechanics you are proposing.

I want logic processors to be able to create functions that will run outside the logic processor, something like return & require. I want the "return" block to send the code after it to "require" blocks. "Require" blocks will also need a "get link".

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Helps beautify code. We will also be able to re-use these functions instead of copy pasting code and whenever we want to change it we always have to change it in all the processors instead of the one with the function.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 50275** [comment]
build a new processor

**Comment by Bassem-Const** [comment]
UNSTALIFY

**Comment by Kyllingene** [comment]
No, this would require an immense amount of work on Anukes end and ruin the point of mlog. Functions have been suggested numerous times before and never implemented.

As a side note, I hate it when people try to revive dead issues. If nobody comments on it, it's because there is no new discussion; all you have done is waste your time and space in other peoples' inboxes.

**Comment by Bassem-Const** [comment]
> No, this would require an immense amount of work on Anukes end and ruin the point of mlog. Functions have been suggested numerous times before and never implemented.
> 
> As a side note, I hate it when people try to revive dead issues. If nobody comments on it, it's because there is no new discussion; all you have done is waste your time and space in other peoples' inboxes.

Now that I think about it, just make a compiler or use @counter manipulation for functions. (And what is mlog?)

**Comment by fl215** [comment]
"mlog" stands for mindustry logic. Now, I know that you can use @counter, but what's the point when multiple processors use that same function, we need a processor to return it's own code to a require block, that's why I asked for `return & require` blocks.

How it'll work, is exactly as I explained: 1 processor could run a `return` block and then all of it's code can be required in multiple processors. The `require` block automatically runs the code when it gets the code.
