### ISSUE TITLE
Make getblock can output liquid tiles

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2928]
### Describe the content or mechanics you are proposing.

The reason is simple: There is no way can we prevent ground units auto-controlled by processor getting stuck in the liquid(pathfind can't be used in most situations).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Make getblock can output liquid tiles, such as `@water`, `@deep-water` or using `@liquid` instead.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ymabert** [comment]
@Hexrotor this is why processors are not OP in all situations but are ineffective.

**Comment by OnyxFinger** [comment]
> @Hexrotor this is why processors are not OP in all situations but are ineffective.

no.
no because air units don't have that flaw, and well controlled ground/naval units don't either.
they're not OP, but because logic has a huge distribution/skill distribution issue, it's a bad mechanic.
In fact, removing/nerfin logic would be a terrible idea : units are extremely price innefficient without it.
My point is, logic isn't OP nor inneffective, and this change wouldn't affect it, other than for it's QoL stuff

**Comment by genNAowl** [comment]
So basically, Logic is only as good as the person who makes and uses it?

**Comment by Nils101** [comment]
Yeah, If we can't pathfind units to a specific location, at least give us this pls

**Comment by OnyxFinger** [comment]
> So basically, Logic is only as good as the person who makes and uses it?

no. That's what the distribution problem is about
