### ISSUE TITLE
Sectors should warn of nearby enemy bases

### ISSUE THREAD

**Issue by Conga0** [Anuken/Mindustry-Suggestions#2931]
### Describe what you would like changed, and why.

Hello, i've played the main campaign planet for a while and consistently ran into an issue where I would take a sector just to discover it has enemy bases surrounding it.
Enemy bases as a concept i'm completely fine with and actively enjoy but it's frustrating to have to pick and guess which sectors have enemy bases nearby them and which don't.

Sometimes I just want to progress slowly or get off for the day just to find the sector I worked so hard for is surrounded by enemy bases I had no way of knowing were there.

### Describe the changes you want to propose. Include possible alternatives.

To fix this, i'd like to know if a sector has enemy bases next to it, perhaps when you mouse over it there could be a small display warning you there's nearby enemy bases and how many.

Alternatively you could see the red arrow attacking the sector when you click on it.

Ultimately, some way to know if an enemy base is nearby a sector is what i'm looking for so I don't plan to fight one sector just to end up needing to fight 2, 3 or more before my territory is truly captured.

Thankyou

**Comment by oinkymoo** [comment]
its not a perfect solution, but you could just look at the [world map](https://mindustry-unofficial.fandom.com/wiki/File:World_map.png). that being said you shouldnt need external resources to solve this, i support

**Comment by OnyxFinger** [comment]
so, you tried taking NPC many times and didn't realise it was the same sector all along
I cannot find anything other than NPC and the surrounding bases that do that, and it was quite expected from my experience

**Comment by genNAowl** [comment]
It might be annoying, but tbh I don't think it really is a problem. Just build an overkill defense strong enough to survive any sort of attack that happens on that sector.

**Comment by Ymabert** [comment]
@Conga0 it is enough that as soon as you start a sector you go out and look at the map, however if you have conquered the nuclear production complex without having first conquered the territories around I can understand the annoyance hahaha, it also happened to me, but I used the T3 retreaders and after 1 week I had all the territories with the bases and the nuclear production complex under my control, it was tough but I did not lose anything, however I support your idea, it is better to be warned first of the dangers, they will probably put that the sectors not displayed close those that can be attacked if they are dangerous will be marked red in advance, but you must have an unexplored sector that divides the conquered sector from what can be dangerous.

**Comment by 50275** [comment]
that moment when you enter an eradication difficulty sector with horizons tanking hits better than V5 liches
