### ISSUE TITLE
First idea.

### ISSUE THREAD

**Issue by V-I-L** [Anuken/Mindustry-Suggestions#2932]
### Describe the content or mechanics you are proposing.

Add the ability to view the content of the mod before downloading it to the device.
Plus, add the ability to view the description of the mod WITHOUT CLICKING on its title in the mod browser.
These thoughts arose immediately after I first installed and downloaded the mod.
I play on an Android device.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will add convenience in terms of familiarization with new modifiers and improve the usability of the interface.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> Add the ability to view the content of the mod before downloading it to the device.

That sounds about impossible, as mods need to be *loaded* in order for you to be able to view its contents.

**Comment by genNAowl** [comment]
Might be possible to display the description though? Dunno, I've never checked out the framework for the mod browser.

**Comment by Kyllingene** [comment]
> Add the ability to view the content of the mod before downloading it to the device.

How would that even work? Would it simply tell you how many of each class was implemented? That wouldn't be very useful, but that's pretty much all you could do without requiring a detailed description for every single modded feature.

**Comment by oinkymoo** [comment]
best you're going to get in terms of viewing the content is going to the repository via the button after clicking the mod in the browser
