### ISSUE TITLE
Building shutdown

### ISSUE THREAD

**Issue by Bruhpolio** [Anuken/Mindustry-Suggestions#2933]
### Describe the content or mechanics you are proposing.

Put a button when clicking on a building near the building info button that temporarily shuts it down

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make it easier to shut down buildings you aren’t using without the need to destroy it or close the input, overall a small change

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
But why? Buildiing that cannot produce anything except power, doesn't consume it's inputss already. This is just redundant.

**Comment by IIINSTINCT** [comment]
Do logic xD

**Comment by oinkymoo** [comment]
under what conditions would this be necessary or useful

**Comment by RealYeet** [comment]
Anyone going to mention how this is under the read me on things not to suggest?

**Comment by RealYeet** [comment]
Or how you can disconnect the power nodes?

**Comment by Bruhpolio** [comment]
Yeah, you’re right it was a dumb thing to post

**Comment by OnyxFinger** [comment]
for once I agree with people saying "logic", this is easily done with prcoessors, no need for galaxybraincells
