### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2934]

**Comment by the-red-soul** [comment]
Im assuming you mean conveyors and want to build them diagonally.....


Hold ctrl and drag diagonally.

**Comment by Ymabert** [comment]
@the-red-soul

**Comment by SMOLKEYS** [comment]
@Ymabert ***hhh*** that isnt how you close these suggestions

**Comment by Ymabert** [comment]
@SMOLKEYS your comment is useless, I write "closed" so people do not even waste time reading a useless thing, it simply serves to make order, but people like you who do not understand must come and tell me that to close it does not work like that, thanks really very useful your comment, you said something I did not know, you can not get there by doing 2 + 2 that I write like this to highlight the fact that mine is not a valid suggestion?  it's so difficult?

**Comment by itcannotbe** [comment]
Just press close with comment or close for heavens sake. Your making a big deal of something that should be obvious enough.

**Comment by SMOLKEYS** [comment]
> @SMOLKEYS your comment is useless, I write "closed" so people do not even waste time reading a useless thing, it simply serves to make order, but people like you who do not understand must come and tell me that to close it does not work like that, thanks really very useful your comment, you said something I did not know, you can not get there by doing 2 + 2 that I write like this to highlight the fact that mine is not a valid suggestion?  it's so difficult?

A 40-word essay for a 7-word comment. Unbelivable.

**Comment by SMOLKEYS** [comment]
Seriously, i just told you that isn't how to close it, and you assume i'm calling you a dumbass?

**Comment by Ymabert** [comment]
@SMOLKEYS no, however, commenting just to say something obvious bothers me, why do you care so much to point out that a comment does not end like this?  It is also obvious that I wrote this to say that it was not useful advice, in fact I redid the comment and took back the necessary things that can in my opinion be added.

**Comment by Ymabert** [comment]
@itcannotbe if people break me without telling me how to do it it is obvious that I answer, what it costs to comment and say like this (which then I looked at how to do it, I thought that to delete the comment you had to have the possibility, in the sense that I as a random person on the site randomly I have no power, anyway thanks for telling me how)? I would not answer if people did not continue to comment unnecessarily without logic.

**Comment by OnyxFinger** [comment]
you guys went on to make an even bigger deal of his comment by saying he made it a big deal for no reason, and this for no reaosn either :clap:

**Comment by Ymabert** [comment]
@OnyxFinger it was enough to say immediately that to close an unattainable or useless comment / idea, just go to the comments section and close the red button.
