### ISSUE TITLE
Improvement of tapes.

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2935]
### Describe what you would like changed, and why.

When I have to replace the tapes with other types of tapes it is inconvenient because I always have to go over the whole path, so I always have to waste time recreating the path.

### Describe the changes you want to propose. Include possible alternatives.

For the replacement problem you should put a request to confirm or reject that says "Replace all with this piece 'Image of piece' Accept - Reject", which comes out when someone puts the first piece of tape, for example, on the tape they want to go replacing and choosing "Accept" the tape will change everything, from the beginning to the end of the path (obviously it will have to be built).

**Comment by Ymabert** [comment]
if you do not want this setting as I recommended it I give some ideas thanks, in my opinion something like this can be very useful, because at least in this way you can think more about the Farm than the tapes, imagine playing mindustry but with the right settings for Do the dullest things, wouldn't it be more fun?  in my opinion yes, it would be a game for more people and not just for those who want to do even these more boring things.

**Comment by BlueTechnoCat** [comment]
Uh... Correct me if I'm wrong but, by \*tapes* you mean conveyors or what exactly?

**Comment by Ymabert** [comment]
I mean belt conveyors, but if you already get there why are you asking me?

**Comment by oinkymoo** [comment]
hold control starting at one end and drag over to the other end

**Comment by Humanoid-X** [comment]
1. Use ctrl
2. Use polys

**Comment by Ymabert** [comment]
@Humanoid-X ok thx, I do not know if this thing is said in the tutorial, because I, who have been playing Mindustry for 2/3 years, have never seen anyone build diagonally with ribbons and I have not even seen any tutorials, then it is very easy that I do not even have it fact since many times the advice that comes out are things I already know, but if I know how to control the droids because I don't know this thing that would be very useful to me? this setting, they should highlight the functions of all the keys and therefore also the combinations through a screen located in the settings.

**Comment by 50275** [comment]
It's inconvenient, but you'll never need to replace many conveyors to begin with.

**Comment by Ymabert** [comment]
@50275 in my opinion it can be very useful when you want to replace an entire tape and it would also be useful if clicking from one point to another even diagonally, obviously holding down, the selected tape would be automatically generated, so the best path based on how I clicked;  this approach already exists, but it cannot be built diagonally yet.

**Comment by oinkymoo** [comment]
it can pathfind diagonally, but if you go too far it will just give up
