### ISSUE TITLE
3x3 Glass block.

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2936]
### Describe the content or mechanics you are proposing.

Many times the problem lies in the glass, once it was not very useful, instead now it is much more used, especially for the droids, so instead of always creating 2/3 glass Farms I would prefer to have a very efficient one, so I ask you to add, like this as you did with Graphhite and Silicon, the 3x3 Block for Glass.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

a 3x3 block also for glass in which sand and lead always enter but in greater quantities and therefore even more glass is produced is a bad idea or were you already thinking about it?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-kido** [comment]
This was already suggested but wasn't added because it was thought it wasn't necessary.

**Comment by Ymabert** [comment]
@the-kido it is not necessary but it can be very useful in certain situations, because then not even the scraps are really useful, but in some cases they are fundamental, so I think that adding this object is good, so one creates only a glass Farm and it is all right for the whole game.

**Comment by oinkymoo** [comment]
i would be amazed if your unit production requires more than a single kiln's worth of metaglass. the only reconstruction that requires metaglass uses it slower than a fully fed and powered kiln produces. if you need more, just build some more kilns

**Comment by Bottinator22** [comment]
A single kiln already produces quite a bit of metaglass. You don't need a bigger one, just make more

**Comment by Ymabert** [comment]
@Bottinator22 I do not complain about the production of glass, even if sometimes it is for what I hope they add the 3x3 oven, because creating so many Farms for a material that does not take much, usually, bothers me, since I see it as a waste of spaces.

**Comment by SoMall-dumpling** [comment]
I'd like it with 7 holes on it.

**Comment by OnyxFinger** [comment]
eh
glass is still not needed in high amounts

**Comment by Ymabert** [comment]
@OnyxFinger in fact mine is just an idea, which in any case would be useful in some cases, but I also know that it's okay.

**Comment by Ymabert** [comment]
@SoMall-dumpling what?

**Comment by Humanoid-X** [comment]
@Ymabert no wtf 4 kilns already produce full conveyor of metaglass why would you even need it? If you really want then use mods. ~~Also ur so rude at people that support your idea lmao~~

**Comment by Ymabert** [comment]
@Humanoid-X am I rude?  you probably don't understand how I answer because it is not a voice chat and so I can seem angry with the world even if I am not hahaha, however this idea is not necessary for how the game is, but it would help in many cases, I stress only helpful, not as essential as the 3x3 blocks of Grafhite and Silicon.

**Comment by Bottinator22** [comment]
@Humanoid-X He just doesn't know what he's saying, he's using a translator

**Comment by Ymabert** [comment]
@Bottinator22 the translator just doesn't translate perfectly and it's normal that you don't always understand me, but I know what I'm saying ...and then because they are all stalkers and they know that I use the translator, I wrote it once because if it happened that you did not understand me (since I had written a very long message) you at least knew that I was using the translator, but on that page, in those comments, I didn't think everyone would know, much less I thought I'd believe people would keep pointing this out.

**Comment by 50275** [comment]
Graphite is necessary everywhere. Your economy, drills, piping, defenses, T2 units, and other various useful buildings require it.
Silicon is necessary everywhere. It's the key to get out of combustion generator land and into late-game drills. 

Nobody produces anything else so cheap in such great quantities. Nobody needs a 3x3 kiln.

**Comment by Ymabert** [comment]
@50275 in fact people would use this 3x3 oven just to be sure of always having glass, it would only be useful, but I don't need to know this too, then glass is the material I hate most of all, at the beginning when I didn't know how to play I always forgot to produce it, because it is an unnecessary material, as you said, so many times I rather say ok, I have Grafhite and Silicon I evolve and produce thorium, then Plastanium, ah right I can't because I have to have glass, it is a mistake that I see everyone making in the multi, but it is a habit, so yes, it is not necessary to have a 3x3 oven but it would be nice not to have to think about the production of glass at some point in the game.

**Comment by SoMall-dumpling** [comment]
Support this.
Maybe 3x3 plastanium factory is more useful than 3x3 kiln for it costs a lot of plastanium to construct high tier units.
In my opinion, people use 3x3 graphite/silicon just because they use less materials. You may say also they’re much more quicker than 2x2 ones, but not really, for they cost more power, and huge amount of 2x2 factories can do this too. But metaglass isn’t that useful, and kiln has an amazing speed of 2 metaglass per second, and also lead/sand isn’t hard to find, so maybe it’s not as useful as the existing two 3x3 factories.
But bigger is stronger. During the development of this game, Anuken will absolutely make high-level factories, including 3x3 kiln.
**I’d like 4x4 alloy smelter**

**Comment by Bottinator22** [comment]
Pretty sure Anuke has already rejected 3x3 plastanium before

**Comment by Ymabert** [comment]
@SoMall-dumpling I approve of everything you wrote, in fact I gave this idea precisely because I know that in the future even large quantities of glass will be needed and therefore being a very secondary material I thought that once someone produces it in large quantities, they don't think about it anymore ( the game is fine as I see it and all very balanced).

**Comment by Ymabert** [comment]
@Bottinator22 means that the 3x3 block of Plastanium would be an idea, but only if the game needs it ...

**Comment by 50275** [comment]
from https://mindustry-unofficial.fandom.com/wiki/

I counted these myself from their list, so I could have made an error

37 buildings require graphite to build. It's also used in T2 reconstructors and is good early game ammo. 
64 buildings require silicon to build. Every unit factory uses silicon. 
25 buildings require metaglass to build. It's good scatter ammo, but the ammo multiplier is very high for scatters (metaglass cyclones are useless) so you don't need much. 11 of these 25 cost less than 10 metaglass each, so you really don't have to worry about high spendings. 

If you have 4 kilns, you make 8 metaglass per second. You'll be fine, focus on another material. It's not like you're going to live using so much metaglass as ammo anyway, at least get lancers.

**Comment by Ymabert** [comment]
@50275 but I know, thanks for reporting all the data here, but I have already said that a 3x3 oven would only be useful on some occasions, but not essential or very useful as Silicon and Grafhite 3x3 Farm.

**Comment by Humanoid-X** [comment]
@Ymabert k, translaatorr again, my bad xP

**Comment by 50275** [comment]
there's also another thing. usually, these 3x3 alternative buildings have some requirement to be less convenient, so you'll probably actually be better off spamming 2x2 kilns anyway.
