### ISSUE TITLE
Add sense to MessageBlock

### ISSUE THREAD

**Issue by Draco18s** [Anuken/Mindustry-Suggestions#2938]
### Describe the content or mechanics you are proposing.

Add the ability for logic blocks to read the current message in a message block.

I found myself wanting to tweak the values in a logic system I had designed (numerical thresholds) and went "hold on, surely I could write into a message block and the logic could read that" and found that nope, MessageBlock doesn't implement Senseable. My program was small and easily adjusted to move those variables to the top, but I thought it would have been nifty.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow for easily editable configuration values for logic systems.

Notably this would turn a message block into a type of memory cell due to the read/write nature of messages, but as memory cells aren't editable/viewable by the player and store multiple values to the message block's one, I don't see this as something that would overshadow the memory block.

This would also make shared logic programs easier for other users to fiddle with, such as altering the type of unit, resource, or power value without requiring the user to parse and understand the logic flow of someone else's design.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Honestly a good idea, I would not mind for the memory block to be replaced with this kind of function an make a 2 x 2 message block.

**Comment by itcannotbe** [comment]
Basically #666.

And no this isn't a coincidence.

###### ~but it is~

**Comment by itcannotbe** [comment]
![Screenshot_20210905_081840](https://user-images.githubusercontent.com/45280919/132110999-87fc41a9-13c8-4835-bb17-0748e10fee45.jpg)

**Comment by Draco18s** [comment]
> Basically #666.
> 
> And no this isn't a coincidence.

Huh, I did a search and didn't find it.
