### ISSUE TITLE
Fps - Mobile

### ISSUE THREAD

**Issue by Z0MB1E101** [Anuken/Mindustry-Suggestions#2939]
### Describe what you would like changed, and why.

I would like changed for mobile players is in settings to have a few options for graphics and particles and etc. Would like more options in settings for better fps in servers. I know for me being a mobile player it can get really laggy and about 1-4 fps a ton of times in servers. Pc people can also have this but mainly mobile players have this issue.

### Describe the changes you want to propose. Include possible alternatives.

More options in settings for graphics, particles, and things to make it a little bit less laggy in servers.

**Comment by itcannotbe** [comment]
How about you disable the game play, that would surely increase your FPS.

**Comment by Ymabert** [comment]
@Z0MB1E101 @itcannotbe In what sense? the fact that there are settings to remove graphic effects and want to put everything to pixels, but I didn't understand what you mean with disabling the game. @itcannotbe

**Comment by 50275** [comment]
Generally you'll be fine if you stay out of Castle Wars and maps greater than 500x500.

**Comment by Bottinator22** [comment]
There already are quite a few settings for improving FPS.

**Comment by itcannotbe** [comment]
@Ymabert Most of the lag that mobile experience is due to gameplay itself.

**Comment by Ymabert** [comment]
@itcannotbe yes in fact playing from mobile is bad, I played it the first period, then I tried it on PC and I learned to play well when I was from PC, from mobile even if you learn everything and you know how everything works you will never learn to play well, much less will you enjoy it like a PC, even with maximum performance.

**Comment by Z0MB1E101** [comment]
Yes there is ways to improve fps but not

**Comment by Z0MB1E101** [comment]
Dont mind the reopening...new to github lol

**Comment by Z0MB1E101** [comment]
> @Z0MB1E101 @itcannotbe In what sense? the fact that there are settings to remove graphic effects and want to put everything to pixels, but I didn't understand what you mean with disabling the game. @itcannotbe

I mean by like how other games have different/more options for graphics. Like how fps is in-game. Also yes there are some things that helps fps but nothing makes a big impact on big servers. I was in the vc for discord yesterday and even some pc players sometimes would lag like crazy.

**Comment by Z0MB1E101** [comment]
I am a mobile player only at the moment. In order to understand better u need to play on some high pop servers on mobile. Then you can see what I really mean

**Comment by 50275** [comment]
> Would like more options in settings for better fps in servers. 

Give an example of a server that lags your device. I will take my phone and try to get 100 FPS in there.

**Comment by Z0MB1E101** [comment]
> > Would like more options in settings for better fps in servers.
> 
> Give an example of a server that lags your device. I will take my phone and try to get 100 FPS in there.

CN, attack or survival is the main server I play

**Comment by genNAowl** [comment]
Is no one gonna mention how this would bloat the settings even further?

**Comment by Z0MB1E101** [comment]
> Is no one gonna mention how this would bloat the settings even further?

Bloat as in making settings even harder to setup then what it already is. Well its a pc and mobile game. I'm sure with adding/adjusting settings they would organize it to make it work. Thats the least of the issue

**Comment by Z0MB1E101** [comment]
I just want it to be less laggy. There can be multiple ways of doing this. I just said settings could be better basically.

**Comment by Z0MB1E101** [comment]
Also if you want. You can try to get some mods and people higher up to look at this. Bet they have some opinions.

**Comment by 50275** [comment]
> > > Would like more options in settings for better fps in servers.
> > 
> > 
> > Give an example of a server that lags your device. I will take my phone and try to get 100 FPS in there.
> 
> CN, attack or survival is the main server I play

CN is a server where they like playing on massive maps, throwing waves of T5s where skilled players use schematics of lines and lines of spectres, meltdowns and foreshadows with phase menders, overdrive domes, and hundreds of every kind of unit moving constantly. You are *never* going to get a good FPS on Chaotic Neutral with your mobile device lategame.
