### ISSUE TITLE
Invisible light sources

### ISSUE THREAD

**Issue by ado1928** [Anuken/Mindustry-Suggestions#294]
**Describe the content or mechanics you are proposing.**

Invisible light sources that can be interacted only by editor. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Useful in map making, making different parts of the map have different light levels.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Wasn't this already implement even before this suggestion was made?

I mean for the next release v6 , not the current one v5.
