### ISSUE TITLE
[Editor] Generation tab filter to convert blocks to cliffs

### ISSUE THREAD

**Issue by Schmucklefuck** [Anuken/Mindustry-Suggestions#2940]
### Describe what you would like changed, and why.

Add a filter in both of the generation tabs to convert blocks into cliffs. I primarily want this added to  generate random cliff terrain, just like you can create random normal terrain. I've been wanting to create random cliff maps for ages, and now that you have officially supported cliffs in some way, I hope you will consider this as well.

### Describe the changes you want to propose. Include possible alternatives.

Add a filter for both the map filter tabs that lets you turn all the blocks to cliffs. Also consider adding block filters, as this would allow for more complex terrain layering.

**Comment by genNAowl** [comment]
I assume you know DeltaNedas/Cliff is a thing right?
