### ISSUE TITLE
(Campaign) Sector (##)% Damage Tweaking and Warnings

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#2941]
### Describe what you would like changed, and why.

Based off of Campaign gameplay in Pre-Alpha Build 130

**Warn players when sectors have taken or will take high amounts of damage**. The game doesn't tell you when your sector is dying while you're in another one. I lost my Impact 0078 while polishing my Nuclear Production Complex base. 

**Recheck the code that predicts the survivability of sectors under attack.** Even if a sector says it can survive 40+/40 waves, such as my Nuclear Production Complex, it often takes damage regardless which seems to make it have a risk of dying that changes the prediction - when I revisit it only a few outer walls are gone. 

**Make the damage taken system destroy more existing buildings, especially if the sector is lost.** In the first image, you can see a sector that was lost recently. Unfortunately, I did not think of taking a screenshot immediately after revisiting the sector. The defenses were just about completely intact, so I didn't need to spend much effort repairing it. The second image depicts a sector with 10% damage. 46% damage, for example, is just a couple of more walls. 

![sectorrepair](https://user-images.githubusercontent.com/68676339/132149087-35186090-7ef0-4baa-816d-5e3a79561111.png)

![damagetaken](https://user-images.githubusercontent.com/68676339/132149252-21b21a6b-706a-4435-a29f-cc642d7aee5f.png)

I've also noticed this. (The last wave was in progress, just another handful of fortresses.)

![image](https://user-images.githubusercontent.com/68676339/132149613-2caddabc-9a25-4064-b153-48b0e84e5ef1.png)

### Describe the changes you want to propose. Include possible alternatives.

Warn the player when their sectors have taken damage, or if they will take damage using the same (pop-ups?) that appear at the top of your screen that show when you lose a sector. 

Give more meaning to sectors having received a high amount of damage other than just the loss of a handful of walls.

**Comment by itcannotbe** [comment]
I think there is some confusion with regards to off-sector damage  prediction.
