### ISSUE TITLE
Make it possible for the player to preview the schematic which is about to be overwritten

### ISSUE THREAD

**Issue by cigarmemr** [Anuken/Mindustry-Suggestions#2943]
### Describe the content or mechanics you are proposing.

Upgrade the existing schematic overwrite dialog below:
![image](https://user-images.githubusercontent.com/26317456/132209271-d4252a45-0303-4bf2-be4a-a62328ddf7ce.png)
Add a preview of the existing schematic (the one which is gonna be overwritten).
Alternative1: Add a dialog to display both the new one and the old one for comparison.
Alternative2: Add an auto rename mechanism, namely, a new button reads "Auto Rename", which saves the schematic by padding a serial number. Then pops up a dialog shows "The schematic is saved as XXX (1)" to inform the player.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Consider the scenes below:
1. The player has two existing schematic named "design1" and "design2". Once he got an idea about an improvement of "design1". He made the new design and is about to save it (overwriting the "design1"), but he is so causious that he'd like to confirm again that "design1" rather than "design2" is exactly the one ready to be discarded.
2. The player made a new design. He'd like to save it by the name "design5", which he thought to be a name that does not exist. Unfortunately, the name belongs to an existing schematic, which the player himself does not remember. So the overwritting confirm dialog pops up when he clicks OK. He would like to see wtf "design5" is that stops his mighty saving motion.

Guessing that the scenes are not rare to most players. In the current build of the game the player will have to do the following:
1. Exit the dialog by clicking "Cancel".
2. Enter the schematic dialog by pressing the hotkey or clicking the icon.
3. Locate the existing schematc by scrolling or searching by tags or keywords.
4. Confirmed. Rollback and try to save the schematic again.
All the operations are redundant and might be saved by the proposion above.

Due to the issue mentioned by another suggestion [2856](https://github.com/Anuken/Mindustry-Suggestions/issues/2856), there is a chance for a player to have more than one schematics with the same name. So the scene below is also considerable:
- The player accidently got two schematics named "Alloy". Now he wish to overwrite one of them by a new design while leaving the other one unchanged.

If the issue still exists or is decided not to be solved, the proposion here would be more or less prerequisite.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Yes

**Comment by RealYeet** [comment]
And possibly the one that will be replacing it

**Comment by oinkymoo** [comment]
^
