### ISSUE TITLE
More Alert Messages

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [Anuken/Mindustry-Suggestions#2945]
### Describe the content or mechanics you are proposing.

I often end up with some things occuring while I'm not there, which can lead to catastrophic results when the defence line suddenly gets
breached and you get warned when a horde rips the Core apart. Therefore I suggest adding more alert messages (or just an icon warning) for: Structures destroyed, fires, unstable Thorium Reactors, units lost. These would not show if the event occurs on-screen. More triggers and their respective alerts can be added as you see fit, the list is not set in stone after all.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Being aware of events occuring outside your display range can save a run, and alerts for various important events are a staple in RTS games, to which Mindustry partially belongs.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
Bruh use minimap ._.

**Comment by TheHopelessThrumbo** [comment]
Minimap doesn't show everything though...

**Comment by SoMall-dumpling** [comment]
If every single destruction is reported, maybe it’ll be easy to crash the game by placing liquid routers with oil everywhere and detonate them.
So there must be a screening system… idk how to do it.
Now we have ‘core is under attack’, but where to show more warning lines? Do we need more indicators?

**Comment by TheHopelessThrumbo** [comment]
Either the same way as for the Core alert, icons on the side akin to Factorio, or use the minimap. VOs related to them are probably out of Anuke's reach, but would work aswell.

**Comment by OnyxFinger** [comment]
> Minimap doesn't show everything though...

clearly it show enough for your issue to be a "you guys" problem
note that it doesn't only happen to you, BUT taking a look at what is going on using the minimap is generally a good habit, that everyone should have

**Comment by jumps-are-op** [comment]
> 
> 
> > Minimap doesn't show everything though...
> 
> clearly it show enough for your issue to be a "you guys" problem

you guys problem is not enough for a 400*400 map
