### ISSUE TITLE
enemy kill count on the turret 

### ISSUE THREAD

**Issue by DaynerKurdi** [Anuken/Mindustry-Suggestions#2946]
### Describe the content or mechanics you are proposing.

the basic idea is, show how many enemy units a turret has kill thus far, the count will be reset when the turret is removed, the info will be shown on the block info HUD.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

more info and feedback for the player

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
This could be useful for attack maps with preset turrets. Once the turrets have killed 100 enemies for example they will shut off because of logic. Just thinking out loud.

**Comment by the-kido** [comment]
How about instead, a damage count rather than a kill count? I think that could prove to be more utilized

**Comment by OnyxFinger** [comment]
huh
yeah actually that could be a thing

**Comment by oinkymoo** [comment]
looking at the suggestion on its own, i don't see how this info would be all that useful. only thing i can think of is checking whether a section of your defense is getting used, which you can see just by like, looking

**Comment by OnyxFinger** [comment]
> looking at the suggestion on its own, i don't see how this info would be all that useful. only thing i can think of is checking whether a section of your defense is getting used, which you can see just by like, looking

it also tells you what turret is doing better

**Comment by NemesisTheory** [comment]
>  it also tells you what turret is doing better

which can be used to upgrade the parts of your defense that is lacking in firepower
