### ISSUE TITLE
It can only rain in Serpulo if the clouds are above the sector

### ISSUE THREAD

**Issue by Jaysoon80** [Anuken/Mindustry-Suggestions#2947]
With this implemented, it could give players an idea of when it will *maybe* rain and when it will definitely not. This implementation would require Serpulo clouds to move MUCH slower in order to accommodate the length of a raining (atleast make it so it stays over a sector for more than five to ten minutes.)

Also make the clouds move at different speeds to simulate rain randomness.

**Comment by IIINSTINCT** [comment]
You...... Do not yeet the template next time

**Comment by itcannotbe** [comment]
> You...... Do not yeet the template next time

Blame the gitnub app.

**Comment by itcannotbe** [comment]
> With this implemented, it could give players an idea of when it will _maybe_ rain and when it will definitely not. This implementation would require Serpulo clouds to move MUCH slower in order to accommodate the length of a raining (atleast make it so it stays over a sector for more than five to ten minutes.)
> 
> Also make the clouds move at different speeds to simulate rain randomness.

No it won't happen as there is no interaction with how the planet itself is displayed to anything happening in any sector.

**Comment by RealYeet** [comment]
> > With this implemented, it could give players an idea of when it will _maybe_ rain and when it will definitely not. This implementation would require Serpulo clouds to move MUCH slower in order to accommodate the length of a raining (atleast make it so it stays over a sector for more than five to ten minutes.)
> > Also make the clouds move at different speeds to simulate rain randomness.
> 
> No it won't happen as there is no interaction with how the planet itself is displayed to anything happening in any sector.

Actually, the day night cycle is directly tied to the planets orientation, so you are wrong with this.

**Comment by RealYeet** [comment]
Although, this would take a lot of effort to implement for something a little more than a convenience

**Comment by genNAowl** [comment]
You guys have seen this right?
https://discord.com/channels/391020510269669376/396416151032299521/884901055748505653
