### ISSUE TITLE
Battering Ram and Bladed Ram

### ISSUE THREAD

**Issue by KnightGabriel** [Anuken/Mindustry-Suggestions#2948]
### Describe the content or mechanics you are proposing.

The Battering Ramwould automatically start out in your inventory along with the duo. It costs 20 copper, and does not require ammunition or power. It would of course have very short range(1-2 blocks), but would have high damage(50 damage) and a light knockback ability. It would damage enemies by propelling a short piston with spikes on the end of it outwards in the direction of the opponent. It has roughly twice the health of a large copper wall. It can be upgraded to a bladed ram, which keeps the spiked piston of the base tower but also gains spinning blades that do damage over time to any enemies that are touching the tower. It'd also have the ability to hit multiple enemies as long as they are bunched up in a small area. Takes 50% less damage from units and immune to fire. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's a simple suggestion, but I think it would improve the game by adding an entirely new and unique type of defensive building/tower. It would also add in 1 extra early game tower alongside the duo. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RzBuddy** [comment]
a 20 copper "free ammo" tower that had twice the health as a large copper wall is way too overpowered, it puts the copper wall (aswell as tita wall) out of use by being tankier as well as being useable on defence. Also no ammo cost on a turret is just gonna lead to spam tactics.

maybe reduce the tankiness to around 4/5 of a normal copper wall and make it cost a bit more copper to build (so it cant be spammed)

**Comment by NemesisTheory** [comment]
Maybe also increase the block cost to again, reduce the chances of everyone spamming it. 

50% less damage from units?, immune to fire?, No, this is just going to make walls absolutely useless, unless this is discussed in further balancing, it's extremely overpowered, makes a lot of blocks useless, and i also don't think it should be unlocked by default.

**Comment by KnightGabriel** [comment]
@RzBuddy Well I originally was gonna give it the same health as a large copper wall. I supposed maybe half the health, the damage reduction from units reduced to 25%, and the fire immunity changed to 50% reduced fire damage would be more balanced. I also thought of making it so they have to be 1 block apart

**Comment by Ymabert** [comment]
@KnightGabriel I like to read these tips, because I just want to have more and more strategies on this game, so it is right in my opinion to see more and more news, be it troops or turrets, I think yours is not a bad idea, just as it is not the idea to create T1 / T2 / T3 robots that remain guard in the limits of the base and resist attacks in the non-defended points, the more things there are the better for this game, I would like to read more tips like yours and less criticism, if not constructive criticism.

**Comment by Bottinator22** [comment]
Mindustry is not a typical tower defense game. Walls are the dominant strategy here, not elaborate paths that whittle down enemies. This would be pretty overpowered.

**Comment by 50275** [comment]
this is going to be a cheap scorch early game, and a better thorium wall lategame
