### ISSUE TITLE
Data synchronization

### ISSUE THREAD

**Issue by JustGekto** [Anuken/Mindustry-Suggestions#295]
I am active mindustry player i like to play on pc because it's more comfortable with mouse and keyboard. But a lot of times i am away from my pc and i play on mobile. It couses inconvenience of having to always export data from mobile upload it over usb to pc and import it there and wise verse.
I am asking to implement some kind of automatic synchronization system.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This has been suggested many times before.
