### ISSUE TITLE
Mass Schematics Select

### ISSUE THREAD

**Issue by JCahoon789** [Anuken/Mindustry-Suggestions#2950]
### Describe the content or mechanics you are proposing.

You will be able to multi-select files that you want to be downloaded into mindustry

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will prevent multiple downloads of the file, as well as kill the long time it takes to download scehmatics

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Is this a steam feature thing?

**Comment by joshuaptfan** [comment]
No, he's asking for the PC file import UI to be improved to support choosing multiple files at once, instead of importing one file, then importing another file, and so on.

**Comment by EclipsePlays** [comment]
I like this suggestion, in my experience as a Mindustry Schematic YouTuber I feel that painful, importing process that takes place when a viewer downloads the zip file that contains more than **30 msch files**, mass importing would greatly take that process to ease but it could probably cause lag or even crash.

**Comment by itcannotbe** [comment]
Why not a folder approach? Like throw everything into a folder and detect duplicates in-game?

**Comment by joshuaptfan** [comment]
Sometimes you don't want the entire folder, so if folder select is implemented, it should only be in conjunction with file multi-select support.

**Comment by esteemator** [comment]
I registered just to support this feature!
Multi-select would be great and folder-import (with integrated check for duplicates) could help making curated packages a thing.
