### ISSUE TITLE
Friendly fire

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#2951]
### Describe the content or mechanics you are proposing.

An option that allows players/player-controlled units to damage players/units on the same team. Does NOT allow them to damage friendly buildings, only players and units. Turned off by default.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More fun :)
More map options
Allows players to phyisically beat griefers instead of waiting for a votekick which may or may not come.
Forces teams to work together or die.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by random-guy1285** [comment]
> More fun :)

Reinforce that claim.

> more map options

Not all options are good options.

> Allows players to phyisically beat griefers instead of waiting for a votekick which may or may not come.
Forces teams to work together or die.

What's the point? Explain.

**Comment by RealYeet** [comment]
Crawler griefing go brrrrrrrrrrrrrrrrrrrr

**Comment by IIINSTINCT** [comment]
No

**Comment by SMOLKEYS** [comment]
> Allows players to phyisically beat griefers

And vice versa.

**Comment by itcannotbe** [comment]
> > More fun :)
> 
> Reinforce that claim.
> 
> > more map options
> 
> Not all options are good options.
> 
> > Allows players to phyisically beat griefers instead of waiting for a votekick which may or may not come.
> > Forces teams to work together or die.
> 
> What's the point? Explain.

You do that classic has this same option right?

**Comment by itcannotbe** [comment]
But can you get killed by your own turrets though?

**Comment by oinkymoo** [comment]
> But can you get killed by your own turrets though?

the turrets' canonical AI would probably be smart enough to not target allied units, but i think it could work if allied units could get caught in the crossfire

**Comment by the-red-soul** [comment]
You cant be serious..... 

Clearly you have not ever had an army ready made and then hit the ATTACK mode on the command center. massive clump of units that goes all at once, and then when said clump starts firing their dps will be drastically reduced since they are firing on themselves, killing themselves, and no matches will EVER finish period.

How about when commanding 8 poly as a poly, you are going to be shot from behind, your other commanded poly will shoot eachother as you shoot forwards. This is a utterly stupid idea that has had ZERO actual thought put into it other than "haha dis is funny yes impliment"

**Comment by itcannotbe** [comment]
Actually if you want this on, you probably have to use logic all the way.

**Comment by vinhsad** [comment]
classic moment.

**Comment by lokyinng** [comment]
> More fun :)
unfriendly fire logic goes brrrrrrr
> More map options
not all options are good options
> Allows players to phyisically beat griefers instead of waiting for a votekick which may or may not come.
1. miss spell
2. unless the griefer is a t4, t5 or t6
> Forces teams to work together or die.
1. one drama can ruin everything for the entire team
2. explain how the commanding work without shooting your own unit
