### ISSUE TITLE
An actual flak type turret

### ISSUE THREAD

**Issue by MistahStealYoGril** [Anuken/Mindustry-Suggestions#2952]
### Describe the content or mechanics you are proposing.

I would love to see a turret resembling the flak guns in WWI and WWII. It is not like it would be useless; in both campaign and multiplayer, air units would be in clusters and a flak turret would be quite good for that. It doesn't even need to have range. Maybe as far as duos.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It is a counter to those logic controlled zeniths that get used on us and will be appreciated. It is also a change from the false advertising of plastanium flak in cyclones. >:(

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i think the thing you are thinking of is called "cyclone"

**Comment by MistahStealYoGril** [comment]
It doesn't really do that tho. The explosions are very small if there is an explosion at all

**Comment by joshuaptfan** [comment]
Mods.

**Comment by itcannotbe** [comment]
You know how flak guns work right?
