### ISSUE TITLE
Rearrange Units in the tech-tree

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry-Suggestions#2955]
### Describe what you would like changed, and why.

In the tech tree, it's not very easy to see which tier the units belong to and which building is required to build it.

### Describe the changes you want to propose. Include possible alternatives.

I did some bad paint hack (which is in no case accurate) to show a possible way.
![2](https://user-images.githubusercontent.com/57239116/132885319-8b8be54d-568b-47ee-9c56-7749181920a8.png)

**Comment by OnyxFinger** [comment]
I guess that would be nice ?
the UI is sure slightly confusing

**Comment by RealYeet** [comment]
I would have it so that all the T1, T2, etc… would be flush with each other
