### ISSUE TITLE
Perfeição do modo online

### ISSUE THREAD

**Issue by lorransalberici** [Anuken/Mindustry-Suggestions#2957]
### Describe the content or mechanics you are proposing.

Um tipo de mapa aberto para o modo online, mas limitado para que os jogadores mobiles possam aproveitar. Onde cada um pode construí sua própria indústria, sem necessariamente jogarmos juntos, mas só no mesmo mapa.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Um jogo mais imersivo, onde podemos jogar com várias pessoas, mas sem precisarmos mexermos em suas construções e construirmos nossas próprias indústrias.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2357#issuecomment-826160788

**Comment by itcannotbe** [comment]
Translated

### Title: Perfection of online mode

### Describe the content or mechanics you are proposing.

An open map type for online mode, but limited for mobile players to enjoy.  Where each one can build their own industry, without necessarily playing together, but only on the same map

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A more immersive game, where we can play with several people, but without having to mess with their buildings and build our own industries.

**Comment by itcannotbe** [comment]
When you realize that the suggestion and the reason for the suggestion doesn't really makes sense when taken together or separately.

**Comment by Bottinator22** [comment]
also suggestions need to be in English so

**Comment by OnyxFinger** [comment]
> also suggestions need to be in English so

actually, it is recommend but not needed, if I'm not mistaking

**Comment by Humanoid-X** [comment]
Recommended, but not necassary (Anuke might ignore)
