### ISSUE TITLE
Planet system

### ISSUE THREAD

**Issue by sansisgay1** [Anuken/Mindustry-Suggestions#2958]
### Describe the content or mechanics you are proposing.

Like solar system(if you have enough planets)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

nothing

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Hexrotor** [comment]
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [ ]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [ ]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
I dont want say this but

Can you pls READ that thing above God damn bruhhhh You are wasting your time suggesting this

**Comment by sansisgay1** [comment]
@IIINSTINCT  I checked and there is nothing like what you said

**Comment by itcannotbe** [comment]
When you realize that the game's code already support the suggestion. 🤦‍♂️🤦‍♀️🤦‍♂️🤦‍♀️🤦‍♂️🤦‍♀️🤦‍♂️🤦‍♀️🤦‍♂️🤦‍♀️

**Comment by sansisgay1** [comment]
I just realize,sorry guys

**Comment by buthed010203** [comment]
Then close the issue...

**Comment by jumps-are-op** [comment]
JUST CLOSE THE ISSUE

**Comment by buthed010203** [comment]
Just dont comment for a month and it will auto close
