### ISSUE TITLE
More detailed blocks info

### ISSUE THREAD

**Issue by wdmvv** [Anuken/Mindustry-Suggestions#2959]
### Describe the content or mechanics you are proposing.

Since we have information, if any tile on map can boost/nerf certain block, there might also be same but with weather
I see this in 2 ways: first one will constantly show nerfs and buffs in blocks info, while second one will show only during specific weather

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will explain and show why some blocks work faster/slower during certain events

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Honestly a good idea

**Comment by Kryvytsky** [comment]
> I see this in 2 ways: first one will constantly show nerfs and buffs in blocks info, while second one will show only during specific weather

About second one. Show not only during specific weather time, but also if weather is turned on in map setting

**Comment by wdmvv** [comment]
waah

**Comment by jumps-are-op** [comment]
why did you  closed  it?

**Comment by wdmvv** [comment]
> why did you  closed  it?

iirc, anuke looks through all suggestions, and if he didn't reply that means he didnt like
