### ISSUE TITLE
Show core no build zones in editor

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2960]
### Describe the content or mechanics you are proposing.

Show core no build zones in editor, based on the rules
If it's the default, show the circle, but if it's polygonal, show the polygons

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Mapping QoL

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Yus

**Comment by OnyxFinger** [comment]
YES
it works with polygonal core proteection, but also prevents you from building everywhere which isn't nice, I wish to have the best of both worlds : in both core protection modes, you can see the limit but still build over it
