### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by 703337** [Anuken/Mindustry-Suggestions#2962]
### Describe what you would like changed, and why.

I personally think the current loader should be changed, as I feel that it does not fit in with the rest of the game's visuals.

### Describe the changes you want to propose. Include possible alternatives.

I would like to see the original loading screen come back, as it feels much calmer and fits with the rest of the game’s visuals.

**Comment by itcannotbe** [comment]
"I personally think....."

The worst thing you could base a suggestion on.

**Comment by joshuaptfan** [comment]
I think it's fair to criticize the loading screen for being too busy. It's perfectly valid feedback. Sometimes, with VFX, more is not better.

**Comment by OnyxFinger** [comment]
I think an inbetween is better
the old one was very plain (why the fuck is there are guy that parked himself infront of where I live with music so high I can hear it through headphones and while being 3 floors farther up ? It's annoying as fuck), but the current one is overactive

**Comment by itcannotbe** [comment]
Contrary to popular belief, the loading screen isn't displaying gibberish.

**Comment by 703337** [comment]
> Contrary to popular belief, the loading screen isn't displaying gibberish.

We know, it’s really not that hard to read, and if you have nothing helpful to say please be quiet.

**Comment by itcannotbe** [comment]
> > Contrary to popular belief, the loading screen isn't displaying gibberish.
> 
> We know, it’s really not that hard to read, and if you have nothing helpful to say please be quiet.

Define we? You and some select group of people?
But changing it to what it previous was is also bad. (Have you seen how plain and dull it was?
Also I am under the impression that the reason why it's not good looking for most people who have interest in this discussion is that the loading screen uses bloom. (I myself play with that option turned off.)

**Comment by 703337** [comment]
> > > Contrary to popular belief, the loading screen isn't displaying gibberish.
> > 
> > 
> > We know, it’s really not that hard to read, and if you have nothing helpful to say please be quiet.
> 
> Define we? You and some select group of people?
> But changing it to what it previous was is also bad. (Have you seen how plain and dull it was?
> Also I am under the impression that the reason why it's not good looking for most people who have interest in this discussion is that the loading screen uses bloom. (I myself play with that option turned off.)
> 
> ~Also you think someone wouldn't notice that someone just randomly starred forks of the repositories for no reason?~

Have you read nothing anybody else has commented on this? They are all saying a middle ground would be better. Also, it seems you didn’t even read the reasoning for why I think it should be changed. Read that and the comments and come back afterwards. Read the label while you’re there too.

**Comment by SoMall-dumpling** [comment]
But the typeface is soooooooo cool.
If the loading interface is changed, I hope Anuken will keep the typeface.

**Comment by OnyxFinger** [comment]
> > > Contrary to popular belief, the loading screen isn't displaying gibberish.
> > 
> > 
> > We know, it’s really not that hard to read, and if you have nothing helpful to say please be quiet.
> 
> Define we? You and some select group of people?
> But changing it to what it previous was is also bad. (Have you seen how plain and dull it was?
> Also I am under the impression that the reason why it's not good looking for most people who have interest in this discussion is that the loading screen uses bloom. (I myself play with that option turned off.)
> 
> ~Also you think someone wouldn't notice that someone just randomly starred forks of the repositories for no reason?~

yes, but the problem isn't necessarily the brightness, it's the flood and the fact that it "doesnt fit with the game's visuals" which is right to a certain degree only
your other point is right though

**Comment by OnyxFinger** [comment]
also, many players use bloom, you can't just give them an L because of it

**Comment by Theoneflop** [comment]
Atmost let people choose which loading screen they want
