### ISSUE TITLE
factory payload collision

### ISSUE THREAD

**Issue by lokyinng** [Anuken/Mindustry-Suggestions#2964]
### Describe what you would like changed, and why.

just make the payload does not move outside of the factory because not to block your own unit when exceeding unit limit

### Describe the changes you want to propose. Include possible alternatives.

make the unit in unit factory stay at the unit factory

**Comment by OnyxFinger** [comment]
this was done already in BE, but removed because if you're maxed on daggers and want to make a fortress mech you can't lol n00b (basically)
the current system doesn't hurt anyway, I don't see why you would ever mix in units in payload conveyors

**Comment by itcannotbe** [comment]
How about a limit on how many is produced in excess of the limit? Probably 2 is enough.

**Comment by RealYeet** [comment]
What we really need is for extra daggers to get *incinerated*
