### ISSUE TITLE
I have an idea for a feature to be able to mine through walls

### ISSUE THREAD

**Issue by karpada2** [Anuken/Mindustry-Suggestions#2965]
### Describe the content or mechanics you are proposing.

So, my idea is to have different tiers of bombs, for different types of bombs will have different power ( what blocks they can break) and range, for example the first bomb might need coal powder ( a coal that went through the pulverizer) and will barely break any blocks, the next tier might use blast compound, stuff like that, the way it will work is you will drag stuff into the bomb, for the first tier, you will drag maybe 50 coal powder, and after 10 seconds, it will destroy everything in a 1 block radius.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think this will be a nice addition to the game, beacuase late game it will be an easier option to move conveyor belts and will generally give you a lot more room to play with, for early game and mid game you will be able to use natural cover and place turrets behind the natural cover.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
> give you a lot more room to play with

Balance aside, it should also be only allowed to work on blocks designed to be breakable, everything else would just be stupid.

**Comment by oinkymoo** [comment]
there is also the consideration that you probably don't want to break too much anyway, to prevent wide hallways that are nearly impossible to hold because you can't keep the turret infrastructure safe

**Comment by MrDuck557** [comment]
terraforming but b o m b
also why do you need coal powder instead of coal

**Comment by itcannotbe** [comment]
You do know you can already move a lot of item over a long distance with payload propulsion towers right?
