### ISSUE TITLE
Improve content stats 

### ISSUE THREAD

**Issue by Sharlottes** [Anuken/Mindustry-Suggestions#2966]
### Describe what you would like changed, and why.

As long as the UI becomes promiscuous and readability is not lowered, more information needs to be displayed.
Even some information differs from other similar information. (unit speed in general: displayed, unit speed when boost: not displayed)

* block: separtor/disassembler ratio, unit factory consume, block explosive damage(reactor, impact too), shock mine damage, message input limit, core spawn unit.
* unit: each abilities, boost speed.

and add filter/sorter on database dialog, make content icon clickable to show its info dialog.

### Describe the changes you want to propose. Include possible alternatives.

1. display Separator and Disassembler output ratio
![image](https://user-images.githubusercontent.com/60801210/133093726-eee25f6a-9b0a-43e4-ad38-c8e09874bc8d.png)

2. make content icon clickable(linked to its content info)
![image](https://user-images.githubusercontent.com/60801210/133094017-6e233c14-7ab1-401f-b540-76c1779059d5.png)

3. display more info of abilities
* repair rate, amount, range
![image](https://user-images.githubusercontent.com/60801210/133094263-603bf015-4b25-48ec-921c-793e477462da.png)

* shield regen rate, amount, range
![image](https://user-images.githubusercontent.com/60801210/133094458-51014028-5e4a-4664-939d-5075b733d784.png)

* force shield regen rate, health, range
![image](https://user-images.githubusercontent.com/60801210/133094664-0223dfcd-6b8a-4b6a-b4c4-9d71e7c1d219.png)

* status effect duration, not only for ability but also any other status effect like bullet's.
![image](https://user-images.githubusercontent.com/60801210/133094747-43cf0bad-33d9-4ae3-a7c7-3ec6e0b1ee0a.png)

4. Shock Mine damage
![image](https://user-images.githubusercontent.com/60801210/133095040-35108166-41f8-4b79-a079-bf98e2a86252.png)
![image](https://user-images.githubusercontent.com/60801210/133095165-00d72e05-afaa-4b91-8572-3c2b6bdef4d2.png)

5. Core spawn unit
![image](https://user-images.githubusercontent.com/60801210/133095278-c6d4edc6-6329-46e9-b200-b464fd0d2a13.png)

6. Boost speed of boostable unit instead of "Can Boost" value.
![image](https://user-images.githubusercontent.com/60801210/133101279-8d78713e-cebf-4a0c-b862-218f95e3ca95.png)

7. Message input limit
![image](https://user-images.githubusercontent.com/60801210/133095703-bd73a865-f688-49b3-a106-8a00805b2a4e.png)
![image](https://user-images.githubusercontent.com/60801210/133095730-2c4a314d-a901-43e7-b0c7-06019eff5aac.png)

8. Reactor/Impactor and any other explosive-able block explosion damage
![image](https://user-images.githubusercontent.com/60801210/133096001-cb4f0927-0e47-4eb4-9115-c73b330db2bb.png)

9. unit factory consume items
![image](https://user-images.githubusercontent.com/60801210/133099934-5220f406-fa0f-4743-a1dc-3a89ca77c3e2.png)

10. Core Database filtering and sorting view option
![image](https://user-images.githubusercontent.com/60801210/133096328-8df4c9d9-d16f-4a06-8b71-c889032e3995.png)

**Comment by OnyxFinger** [comment]
yeah this makes sense

**Comment by RealYeet** [comment]
100% agree with everything here.

**Comment by SMOLKEYS** [comment]
I approve with literally everything here
