### ISSUE TITLE
Remove duplicate rules on map editor.

### ISSUE THREAD

**Issue by Sharlottes** [Anuken/Mindustry-Suggestions#2967]
### Describe what you would like changed, and why.

![image](https://user-images.githubusercontent.com/60801210/133103115-3981e09d-f508-483a-806e-1fbc515ba12a.png)

+ add unit caps rule on teams rule.

### Describe the changes you want to propose. Include possible alternatives.

* remove "Unit Damage Multiplier" and "Unit Production Speed Multiplier" on units rule.
* move "Units Require Ammo", "Cores Contribute To Unit Cap" and "Base Unit Cap" to Teams rule.

**Comment by OnyxFinger** [comment]
also, add unit health multiplier in the team rules, it has a use now
