### ISSUE TITLE
Add Tiles drag-select tool, Improve line&grid tool

### ISSUE THREAD

**Issue by Sharlottes** [Anuken/Mindustry-Suggestions#2969]
### add tiles drag-select tool
Tile select tool can make various features such as fill, copy, paste, rotate, remove, convert to cliffs, and partial generation(ore, terrain etc.)

![image](https://user-images.githubusercontent.com/60801210/133233542-d6dbe9cc-16c9-48b5-9994-acefc742cdb2.png)
there is already forked mindustry repository but it's not updated to v7.
As you can see in the picture above, the "Tiles Selection" tool makes other tools to partially work by selecting all that exist in the tile coordinates, such as minerals, blocks, and tiles.

for copy-paste tool, it's good news for making boxed map. this also increases productivity. with rotate tool, it would increases more productivity.
for cliff tool, it's good news for making cliff map. if it's exist, we couldn't need to convert every walls to cliffs.

In addition, the existence of tiles selection tools alone is sufficient to improve the functionality of other new or existed tools.
Even the code already exists to prove its feasibility as forked repository, so there is no reason not to!

### improve line&grid tool
line tool doesn't show preview. if possible, showing line angle is also nice.
![image](https://user-images.githubusercontent.com/60801210/133236535-ac66f939-5066-4c0a-9ec7-4b9ad2ceb374.png)

grid tool doesn't show position (x, y) as tile or world. It is often cumbersome to check when entering the in-game editor.
![image](https://user-images.githubusercontent.com/60801210/133236655-fd86b3b9-705a-47f4-9691-0cd79f512015.png)

## Describe the changes you want to propose. Include possible alternatives.

![image](https://user-images.githubusercontent.com/60801210/133234841-f4d76f13-2615-49a4-aea5-5469cc28291b.png)
* add tiles selection tool. 
* add partial copy, paste, rotate, remove tools. if tiles are not selected, they won't work.
* make fill, convert to cliffs, generation partially works when tiles are selected.
* show preview&angle on line tool
* show position (x, y) on grid tool

**Comment by OnyxFinger** [comment]
here before players say that cliffs are experimental and that their artstyle isn't fitting
I mean they are experimental but still not bad

**Comment by OnyxFinger** [comment]
> show position (x, y) on grid tool

in my opinion having a grid would be actually good if it had "splits", as in it's grid shows different sections instead of each tile individually

**Comment by 50275** [comment]
slow down camera movement, add support for navigating the floor/tile/building selection with the arrow keys

**Comment by OnyxFinger** [comment]
cmaera movement shouldn't be slowed down, it's fine as it is. Just zoom or dezoom to change it's speed

**Comment by 50275** [comment]
whenever I dare to press any of the 4 keys WASD not a single tile on the map is visible. I don't know what it is like for others though.
