### ISSUE TITLE
Add search bar, filter/sorter view option on map list too

### ISSUE THREAD

**Issue by Sharlottes** [Anuken/Mindustry-Suggestions#2970]
### Describe what you would like changed, and why.

![image](https://user-images.githubusercontent.com/60801210/133237801-237f5ab4-03c4-467c-9254-0d0571a59757.png)
as we know, schematic list has search bar and tag. this has sufficiently reduced unnecessary scrolling and passive navigation.

![image](https://user-images.githubusercontent.com/60801210/133237696-8d121d89-f171-4141-83bb-746153b7506c.png)
![image](https://user-images.githubusercontent.com/60801210/133237729-cfc6446d-d071-41e0-bec8-667d149be68f.png)
but map list doesn't have it, even search bar.
In situations with many maps, it would be terrible to have to scroll and search long every time.

### Describe the changes you want to propose. Include possible alternatives.

* add search bar on custom game map list and editor map list dialogs.
* add filtering/sorting view option too. fields are "modded, custom, built-in type", "map size", "possible game-mode"
* if possible, tag system would be good.

**Comment by LeoSko** [comment]
https://github.com/Anuken/Mindustry/pull/2080

**Comment by Sharlottes** [comment]
> [Anuken/Mindustry#2080](https://github.com/Anuken/Mindustry/pull/2080)

i was blind. thanks for reply
