### ISSUE TITLE
Anuke/n plz fix

### ISSUE THREAD

**Issue by firstcreator48** [Anuken/Mindustry-Suggestions#2972]
### Describe what you would like changed, and why.

fix extraction outpost titanium output into launch pad (crux team) 
![Uploading Screenshot_20210914-100347.png…]()
it is annoying (for me) and i want it fixed before other ppl gets annoyed

### Describe the changes you want to propose. Include possible alternatives.

add conveyors leading into the launch pad (titanium is the input) so i don't get pissed and need to become crux and fix the said issue

**Comment by RealYeet** [comment]
Bugs belong somewhere else

**Comment by oinkymoo** [comment]
[you mean here?](https://github.com/Anuken/Mindustry/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by firstcreator48** [comment]
> Bugs belong somewhere else

ok i will resend it in the mindustry issues page
