### ISSUE TITLE
Better leg unit drowning

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry-Suggestions#2974]
### Describe the content or mechanics you are proposing.

Instead of relying on whether or not any legs are touching ground, have the legs simulate the deeper water by effectively shortening the legs depending on how deep the water is (which should be calculated depending on how many deep water blocks exist in a certain range), to simulate the legs going deeper into the water. Drown the leg unit when the legs become too short.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Makes more sense than drowning if no legs are touching ground. That's some seriously good balancing if a toxopid can somehow keep upright and above the water with a single leg touching ground.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-red-soul** [comment]
https://discord.com/channels/391020510269669376/396416151032299521/878808746720120832
