### ISSUE TITLE
Synchronise @tick on server join

### ISSUE THREAD

**Issue by end-me-please** [Anuken/Mindustry-Suggestions#2976]
### Describe the content or mechanics you are proposing.

@tick should be the same for the server and all clients.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Both @tick and @time are not synchronised. Synchronising at least @tick would make timed logic possible in multiplayer, without the use of doors. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jumps-are-op** [comment]
this gonna end some of the desync logic if done
