### ISSUE TITLE
Add gass collector

### ISSUE THREAD

**Issue by HW12345** [Anuken/Mindustry-Suggestions#2977]
### Describe the content or mechanics you are proposing.

Ass some machine that collect gas from the atmosphere. These gas can be use by different machines to produce new material or speed the building up.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will add a new from of material that people can use. This will add more resources to work on and more pipping opportunity for the player.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
yes but what's the point of the new resources ? What is their spot is what I wonder
We don't really know what new resource(s)

**Comment by MrDuck557** [comment]
hm
check water extractor

**Comment by SMOLKEYS** [comment]
> Ass

_**~~wheeze~~**_

**Comment by OnyxFinger** [comment]
> hm
> check water extractor

uh why tho

**Comment by jumps-are-op** [comment]
why not
