### ISSUE TITLE
Make the logic "Jump" command have colored lines

### ISSUE THREAD

**Issue by ETANA812** [Anuken/Mindustry-Suggestions#2979]
### Describe the content or mechanics you are proposing.

It would be cool if the lines for the "Jump" command were colored because I have a complicated processor and went to go back to working on it and all of the jump lines just merged and I have no clue which one is which.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I would totally make the logic easier to go back to and work on it quickly without having to determine where the lines go.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Yus
