### ISSUE TITLE
U.I. Improvements

### ISSUE THREAD

**Issue by alexHunter854** [Anuken/Mindustry-Suggestions#298]
I think an improved U.I. could drastically better Q.O.L. at least for modded players, one thing that would really help is  a search system that can help you find what makes what E.G. if you search for graphite you can find the graphite press, the multi press, the separator and all the drills. If you search for oil, you find the spore compressor, the oil extractor and all of the pumps. Also, a name search option would also help out a ton, and if people want the old U.I.
make it toggleable.

**Comment by itcannotbe** [comment]
That's the most unintuitive thing I ever heard in recent times.

If players just actually played the campaign. This wouldn't be an issue.

**Comment by maxshowarth** [comment]
I second this - there should be a filter or search function that narrows down tools/utilities that are either producers or consumers of certain materials/units/etc.

This does not have the be the main pattern for selecting objects, but would certainly be useful. 

A good start might be a community supported project that maps this out on the Wiki. The bones of it are already there - you can see what units are made by what factories. @alexHunter854 is this something you are interested in taking on?

**Comment by alexHunter854** [comment]
@maxshowarth I'm not really sure that I could help with coding anything, I'm not really good at coding, especially not java, I would have to learn a **LOT** more java to even start helping, I really would love to help but I'm not good enough to do anything that couldn't be done by someone more skilled than me could do in minutes...
