### ISSUE TITLE
Make "path to spawn" generation create ground tiles to ensure units can get to core.

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#2980]
### Describe the content or mechanics you are proposing.

With the addition of rives to Serpulo generation, they can sometimes make it so enemies can't reach core. At least ground ones.
My idea is to make the path to core have a optional tile option that adds tiles if the path is obstructed by, for example, deep water.
Additionally, to help it look more natural, add size, octaves and the other shenanigans to make it look more 'natural'.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Better Serpulo campaign generation, mapping QoL

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
yee

**Comment by genNAowl** [comment]
Maybe also try and make it a curve instead of a straight line every time?

**Comment by Anuken** [comment]
> With the addition of rives to Serpulo generation, they can sometimes make it so enemies can't reach core.

That's not possible. Rivers never place deep water. If you have examples of this occurring, please provide a save or sector name.

> Better Serpulo campaign generation

Serpulo does not use any map filters. It is not related to the editor's generation system.

**Comment by OAtobaAzul** [comment]
> That's not possible. Rivers never place deep water. If you have examples of this occurring, please provide a save or sector name.

I saw an image in discord where the units would not cross a river, odd. Must've been a pathing bug. 
I would go fetch it but it's probably burried under hundreds of messages.

> Serpulo does not use any map filters. It is not related to the editor's generation system.

I didn't knew that, well this suggestion falls flat with it so I will close it.
