### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by bugreporterboris445** [Anuken/Mindustry-Suggestions#2983]
### Describe the content or mechanics you are proposing.

Logic: labels for conditional branch commands

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If your programm contain >100 srings of code jumps (branches) become hell. In assembler enviroment jumps to the labels are used. Label only marks point in code list, compilator parce labels and convert them to the addresses of programm memory. Something similar can be useful in Mindustry logic. It will make life much easier when updating old code and writing large programs.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
jump labels actually already exist. however, they can only be created through manual code editing outside of the game. though i agree that it should be doable in-game

**Comment by bugreporterboris445** [comment]
To be honest, I'm surprised) Please, tell me, where can I find out about them? I'll add information to the fandom/ru wiki

**Comment by bugreporterboris445** [comment]
> jump labels actually already exist. however, they can only be created through manual code editing outside of the game. though i agree that it should be doable in-game

To be honest, I'm surprised) Please, tell me, where can I find out about them? I'll add information to the fandom/ru wiki

**Comment by Ruichka** [comment]
> > jump labels actually already exist. however, they can only be created through manual code editing outside of the game. though i agree that it should be doable in-game
> 
> To be honest, I'm surprised) Please, tell me, where can I find out about them? I'll add information to the fandom/ru wiki

```batch
jump label
<insert some code here>
label:
printflush message1
<insert some other code here>
```

**Comment by bugreporterboris445** [comment]
Thank you, kindly regards!

**Comment by buthed010203** [comment]
~~close this?~~
