### ISSUE TITLE
salvo with cryofluid and thorium is too op

### ISSUE THREAD

**Issue by begginerr** [Anuken/Mindustry-Suggestions#2984]
### Describe what you would like changed, and why.

salvo with cryofluid and thorium is very op, it can sweep t4s if you have like 6 or more of them

### Describe the changes you want to propose. Include possible alternatives.

* nerf the damage dealt by thor salvo

**Comment by Ineedause** [comment]
ok, can we just talk about how stupid this idea is.

1. Salvo is a ammo EATER, the damage of Thor is the only thing that keeps it good.
2. Cryo is hard to mass produce for turrets, so if you have enough cryo you should be spending it on other turrets like sceptre at that point or you should use water for salvo, still inefficient.
3. Thor is a hard resource to get, it should be powerful.

Close this feedback suggestion, it is pointless and you have not thought things through.

**Comment by Bottinator22** [comment]
cryo for turrets is actually balanced, because cryo is harder to produce

thorium for turrets isn't actually that hard to get (since you can stockpile ammo)
but it's obviously gonna be better than copper or graphite

**Comment by begginerr** [comment]
> 1. Salvo is a ammo EATER, the damage of Thor is the only thing that keeps it good.
valid point, but container/vaults can fix that, i will close it anyway

**Comment by OnyxFinger** [comment]
> Salvo is a ammo EATER, the damage of Thor is the only thing that keeps it good.

is it ? I never had that problem

> cryo for turrets is actually balanced, because cryo is harder to produce

actually it's quite easy to make

Still tho, salvos aren't all that great, and I think a nerf isn't necessary

**Comment by the-red-soul** [comment]
If anything salvos need a buff since they are only ever good with thor ammo, which at times is still not enough damage. it used to be the case that 3 copper duos had more dps than a copper salvo and that has been changed. Personally i feel like salvo should have one pierce to give it a bit more use. It is a single target weapon that gets decimated by swarms of units
