### ISSUE TITLE
Coin Factory

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#2987]
### Describe the content or mechanics you are proposing.

Make coins that can buy some special maps. Some resources and many other special things... 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make the maps more challenging and coins can be another ore that can effect the game. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GuestUser25** [comment]
This is only a opinion.
I think the game might need this.

**Comment by NemesisTheory** [comment]
well, i sort of agree on the "special maps" part, it sounds interesting and quite cool seeing maps that can only be unlocked via getting these coins. 

Although, the resources part i don't think sounds much necessary because Mindustry is a factory game, if you want to add coins that can buy resources or units, try sk7725/BetaMindy

**Comment by GuestUser25** [comment]
May be there could even for some exchange rate between each kind of resources...
Like 100 Coins can be exchange to one Thorium.

**Comment by oinkymoo** [comment]
honestly, I feel like this doesn't fit the game very well, though it could work in a mod. also, "more ores" is not something you can suggest without explaining what niche it would fill, and "more challenging" is not, on its own, an improvement to the game

**Comment by RealYeet** [comment]
Sounds like micro transactions

**Comment by Rex-Hm** [comment]
no

**Comment by SMOLKEYS** [comment]
> Sounds like micro transactions

Daily dose of EADustry

**Comment by the-red-soul** [comment]
robots have no concept of money. bad suggestion to gate progression behind one specific item. There is no functional purpose for this *ore*

locking maps behind it, what are we just paying crux toll booths to be allowed into their territory or are we invading like we are suppost to be?


close this suggestion now

**Comment by GuestUser25** [comment]
> robots have no concept of money. bad suggestion to gate progression behind one specific item. There is no functional purpose for this *ore*
> 
> locking maps behind it, what are we just paying crux toll booths to be allowed into their territory or are we invading like we are suppost to be?
> 
> 
> close this suggestion now

I think you misunderstand what I actually mean. I was thinking using the coins in campaign to buy the map that is in custom game.

**Comment by OnyxFinger** [comment]
> > robots have no concept of money. bad suggestion to gate progression behind one specific item. There is no functional purpose for this _ore_
> > locking maps behind it, what are we just paying crux toll booths to be allowed into their territory or are we invading like we are suppost to be?
> > close this suggestion now
> 
> I think you misunderstand what I actually mean. I was thinking using the coins in campaign to buy the map that is in custom game.

that is... even worse ? There isn't really a point

**Comment by Humanoid-X** [comment]
No just no

**Comment by SMOLKEYS** [comment]
> > robots have no concept of money. bad suggestion to gate progression behind one specific item. There is no functional purpose for this *ore*
> > 
> > locking maps behind it, what are we just paying crux toll booths to be allowed into their territory or are we invading like we are suppost to be?
> > 
> > 
> > close this suggestion now
> 
> I think you misunderstand what I actually mean. I was thinking using the coins in campaign to buy the map that is in custom game. 

_...what?_

Just, ***shut***. Don't bother asking anuke to lock some maps behind a paywall. The editor exists.

**Comment by Kyllingene** [comment]
Anucoins? Is that you?

**Comment by numer99** [comment]
What even is this idea?
Why?
