### ISSUE TITLE
Allow seeing map settings from in game

### ISSUE THREAD

**Issue by InfiniZeph** [Anuken/Mindustry-Suggestions#2989]
### Describe the content or mechanics you are proposing.

Be able to see the map settings from in-game, this is taken directly from "Map Info" that exists from within the map editor

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would for example help players plan ahead, knowing what waves will be sent without having to save the map, then manually moving the save, import it into back mindustry map pool to be able to use editor and seeing the waves settings of the map

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
you know that you don't need to do the importing stuff right ?
you can just open in the editor already
and the point is that you're supposed to plan ahead anyway, else it's kind of stupid if you think about it

**Comment by InfiniZeph** [comment]
Correct me if i'm wrong, but as far as i am aware you need to import the save into the editor first if you don't have it already before you can see the map settings, which won't be needed if we can see it in-game

And for planning ahead, i kind of both agree and disagree, it is stupid, but the point of the suggestion i am making is to at least guide the players towards prioritization of what to do first, for example one can see if the next wave is easy/hard, depending on it, one might want to improve their defenses before focusing on their production, another thing is that being able to see the  settings that existed in map editor means that players can kind of get the gist of how easy/hard the map is without having to open editor for that map

**Comment by itcannotbe** [comment]
if we follow the same logic why there is no easy way to see where the spawn point/drop zone is, this suggestion would also get rejected.

**Comment by InfiniZeph** [comment]
i see, i'll be closing this suggestion
