### ISSUE TITLE
Remove color display from minimap

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#299]
Pixil art is abusive of the main premise of the game and a anti pixilart feature should be added or something similar

It'll improve wellbeing.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Mass pixel art has only been conveniently possible through the use of schematics

**Comment by Anuken** [comment]
No. I don't see how it's "against the main premise of the game", and I don't see how it will "improve wellbeing".
