### ISSUE TITLE
Unit capture energy tower

### ISSUE THREAD

**Issue by lawdipsheet** [Anuken/Mindustry-Suggestions#2991]
### Describe the content or mechanics you are proposing.

Posibly make a new 2 x 2 energy tower that can capture enemy units maybe after 10, or more secconds, depending on the class of a unit, of susstained fire like the Parallax tower, and either limit the life span of the unit, or just add them to the team unit limit, it would also be a good idea to have them use more power the longer they're active so that its more costly to take out a larger unit, and possibly make it not target boss class enemys.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allows for extra options for more passive base deffense and offense, of instance if you would have a few of theese towers setup and a few walls with repair nodes you could not only deffend your base but would also have a passive form of attack, now the towers would eventualy be have to be replaced but by then you would have more materials because you wouldent be entirely connserned by the safty of the wall and could upgrade the deffense to a higher degree or attack more violently than your enemy.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slava0135** [comment]
~~totally not Hacker tower from reVision~~

**Comment by OnyxFinger** [comment]
yeah but
it's not passive offense since units start attacking

**Comment by Dwal32s** [comment]
Could be a game modifier in custom matches, like Core Capture.
Basically you kill a unit, and it turns into your own unit. Maybe to avoid lag there's a customizable unit capture limit?
