### ISSUE TITLE
Satellite Launchers

### ISSUE THREAD

**Issue by HW12345** [Anuken/Mindustry-Suggestions#2992]
### Describe the content or mechanics you are proposing.

So I am thinking of some sectiors contain resources to research satellite launchers and when the launchers are supplied by enough resources, it launches a satellite and it do orbit around the planet. Then you can control the satellite to shoot moving giant laser beam from the sky and damage enemy and may damage friendly building. People can recharge the satellite by sending resources (cryo and surge?) to the launcher and the launcher will shoot the supply to the satellite and it will recharge the beam. Also to stop mess beaming, I think the satellite amount should be limited.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content may serve as a clutch to save the core from enemy which breach your defence. And this is pretty balanced since it will not just kill off enemy but will damage friendly building including the silicon plant and the impact generators. Also as I say in the upper text the ammout of satellite should be limited.

(personaly I think laser beams are cool)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
not a fan of trivializing content. I think it should probably be a sector-wide unit wipe (or to prevent guardian skips, either a limited amount of damage or heavily reduced by guardian armor), or if it has any building damage, it should not be enough to destroy anything much stronger than a copper wall

**Comment by RealYeet** [comment]
And we need this because…….?
