### ISSUE TITLE
Core's spare storage: the deep core

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#2997]
### Describe the content or mechanics you are proposing.

VIRTUAL and deep part of the core intended for construction purpose only:

1-Can't be unloaded using unloaders
2-The items CAN'T be taken by units(using logic). The only exception is the player itself(and maybe the commanded units )
3-Consist 5% of the highest core capacity, it doesn't matter how many cores there are, this will not change this part's capacity, what matters is the highest core, so if it is Shard-->200 items each, Foundation-->450 items, Nucleus-->650 items.
4-Only applied to constructive items such as silicon, graphite, thorium, lead, plastanium...and NOT applied to non-constructive items such as coal, spore, pyratite, blast....etc
5-For surge-alloy and Phase-fabric, 5% is too much, so either reduce it to 2% if it is easy to do so(this enough for phase conveyors and surge tower and so..) or make them part of non-constructive items. it is not a big issue if run out of them from construction point of view.
6-TOP PRIORITY, FILO(First in last out): this means when the items go to the core the first part to be filled will be this deep virtual part, and after getting filled, the remaining normal part of the core will be filled, also this part will be the last part to be used while making building.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Definitely this will lead to massive improvement in online "gaming experience" therefore the game will be more funny , now we don't need to beg everyone to stop using silicon or to grief their building or to leave the server cus we need silicon to make more silicon, the people who spam core-attached or wireless schemes for surge or units or other things killing all resources, if this principle gets applied we know there will be always something in the core to use it to build our base.
Also in single player, sometimes we forget ourself or miscalculate things leading to run out of some items.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
So basiclly a buffer so that logic units don’t eat resources out of cores

**Comment by acoaco** [comment]
should be a optional,if it's default I against it.
In multi player game if it's 5% and your've many core 200k capacity that means if your teammate keep build less than 10k resources your all wireless def system/T3~T5 wirelessfactory all doesn't work that a huge debuff for in pvp game
Same even in 1v1 pvp if a backup core storage implemented,you don't know your wireless def work or not cuz system always try protect your resources you need take care about your resources over 5% or not that's a hassle
In basiclly if you stay at a team doesn't have enough resources allow you build thing I doesn't think it will change anything(ban logic/unloader take it),so many people still spawn stupid building
 (like 16 alloy smelter with mass driver at early game ),the reason why lack resources is they only know how to spend resources they create nothing,and all players can use backup resources so still easily 0 resources,the best way still play solo game/1v1 pvp or with good teammate

**Comment by itcannotbe** [comment]
I think everybody missed the point.

Basically it's storage allocated so that you have building materials for building almost always. This prevent your core emptying out and not have materials for building (Unless of course you empty out your core due to actually building stuff).

**Comment by Neba-MD** [comment]
I foresee the UI will be more confusing if it is the case. Either a toggling option at the core “disallow unloading/withdrawal” or a logic to disable this seems easier.

**Comment by Sector171** [comment]
> Basically it's storage allocated so that you have building materials for building almost always

Exactly

@acoaco Apparently you didn't read well what i did write, number of cores  will not increase its capacity.
@Neba-MD Nothing will change in UI, maybe the only thing is color of quantity of items when you check the core, if it is less than 5% the number will be colored with maybe read or so, thats it.

**Comment by OnyxFinger** [comment]
> > Basically it's storage allocated so that you have building materials for building almost always
> 
> Exactly
> 
> @acoaco Apparently you didn't read well what i did write, number of cores will not increase its capacity.
> @Neba-MD Nothing will change in UI, maybe the only thing is color of quantity of items when you check the core, if it is less than 5% the number will be colored with maybe read or so, thats it.

still actually, 650 is somewhat too much for PvP, since you really want to optimize as-in eat as much as you can, so, if you have ressources banked up, you're not doing a good job at all

**Comment by Sector171** [comment]
@OnyxFinger take the items from the source using routers or so as needed not from the core, easy.

**Comment by OnyxFinger** [comment]
> @OnyxFinger take the items from the source using routers or so as needed not from the core, easy.

but it's not so simple, see, the reason why you want to be tight is time, and time just so happens to be why it's not so simple : having to re-distribute ressources is a long and generally annoying process, which is ok for a few times, but isn't nearly as fast as units taking from core.
Not only that, but many units just mine ressources and drop them off at core. In v7, it has become easier to make units mine and get to a factory instead of core, but units still have to put all of the ressources made in those factories.... back in the core.
doing it otherwhise would simply be too innefficient anyway

**Comment by Sector171** [comment]
@OnyxFinger 
Sorry but I didn't get convinced at all about your PvP issue:
1- what apply to you apply to your opponent as well, so??
2- you see 650 too much, so you talk about the very beginning of the game, what type of units are we talking about?! İt is only T1 and T2, making specialized factories for them is more professional, their requirements are too low, silicon graphite maybe few other things lead or tit, what is the complicated in this!!
3- non-noobs player will always have positive balance of every item (what produce > what consume), in this case your core will have more than 650 which means no problems at all logic units and unloaders will work fine. And if you have negative balance it is just a time matter to run out of item and this feature will slightly faster this but keeping in your core some items for construction which much more important than making units, got the point?

**Comment by OnyxFinger** [comment]
> @OnyxFinger
> Sorry but I didn't get convinced at all about your PvP issue:
> 1- what apply to you apply to your opponent as well, so??

so that's still annoying for both. You can't just say "what applies to you applies to your oponent" and call that balance

> 2- you see 650 too much, so you talk about the very beginning of the game, what type of units are we talking about?! İt is only T1 and T2, making specialized factories for them is more professional, their requirements are too low, silicon graphite maybe few other things lead or tit, what is the complicated in this!!

T3, mainly, but a lot. Where I play, some players may get 1 quasar factory and 2 overdriven zenith factories, which is a lot of consumption
> 3- non-noobs player will always have positive balance of every item (what produce > what consume), in this case your core will have more than 650 which means no problems at all logic units and unloaders will work fine. And if you have negative balance it is just a time matter to run out of item and this feature will slightly faster this but keeping in your core some items for construction which much more important than making units, got the point?

yes, but in videogames, balancing is generally done around the higher levels : that's why you're expected to learn, eg what is the counter to this or this, or what's more efficient between this and this... Even if it was supposed to be balanced around every level, then it's still annoying for the higher level.

**Comment by SMOLKEYS** [comment]
I have something to bring up: Wouldn't this break using `sensor` on cores entirely?

Since if you use `sensor` for items on cores, it would also scan the deep part, making nearly all "take items from core" logic schematics break.

**Comment by itcannotbe** [comment]
The fix won't take a few more lines.

**Comment by Sector171** [comment]
> I have something to bring up: Wouldn't this break using sensor on cores entirely?

Actually no, I don't think so, most of transportation logic just order the unit to take max from the core without checking, and even for most of logic which checks the result is the same: the units will be stuck with the core trying to take items, and it will take few items from time to time untill gets filled.
Anyway even if this will affect few logic, I see this feature will increase the quality of this game practically that it deserves.
