### ISSUE TITLE
Improved Oct AI when on crux team

### ISSUE THREAD

**Issue by CheesyMeatball** [Anuken/Mindustry-Suggestions#2998]
### Describe the content or mechanics you are proposing.

I think that crux Octs should come pre-loaded with units and buildings then drop these off while close to your defence. It would bring things such as crawlers and (pre-loaded) fuses to the front line.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe this will add more variety to vs crux gamemodes, as it will cause the player's defences to be attacked strongly at close range. This would mean that players would need to consider short-range defences, such as scorchers and fuses, along with long-range and anti-air defences.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
more like being able to set a building payload in the wave editor, but I kinda like it
