### ISSUE TITLE
Reaper weapon buff

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#30]
**Describe what you would like changed, and why.**
After the Reaper AI was made better, I think it needs a buff to it's weaponry, which are currently weak compared to other enemies

**Describe the changes you want to propose. Include possible alternatives.**
I think one of the coolest things it could do would be to have weapons similar to the meltdown laser, but if not I think a buff of it's current weapons to be similar to the Eradicator would be good. Reapers right now are very weak and I think a buff like this would make them scarier and no longer really weak.

**Comment by KK6DOC** [comment]
In 6.0 anuke reworked units so the ai may change and also he is re-spriting the reaper so it probably is going to become different very soon

**Comment by kapzduke** [comment]
> he is re-spriting the reaper

no he isn't, the new sprite was experimental

**Comment by Syncinus** [comment]
Eclipse
