### ISSUE TITLE
Make mods able to add new categories

### ISSUE THREAD

**Issue by ThePythonGuy3** [Anuken/Mindustry-Suggestions#300]
**Describe the content or mechanics you are proposing.**
Make Category.java use an array or something else that isnt an enum, because you just cant modify those, making mods able to add new categories to the game without needing to remake the entire block placement UI. I know this would break all the calls to Category.java, but it is worth it in my oppinion.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think a lot of mods (mine included) want to have custom categories, and remaking the entire UI just to add a category is completely unnecessary.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Sanity Check: You realize that this suggestion would break UI usability and UI Layout if you install too many mods that uses more categories?

**Comment by ThePythonGuy3** [comment]
it _could_ add too much categories, but i dont see that as a problem. keep in mind it woud be scrollable

**Comment by Katsute** [comment]
Couldn't this also break hotkeys for categories and items?

**Comment by zethnest** [comment]
> Couldn't this also break hotkeys for categories and items?

Probably if it exceeds more than 10 categories. They're actually dynamic

**Comment by sk7725** [comment]
Hotkeys just would ignore the new categories if I'm reading the code right.

**Comment by sk7725** [comment]
Also why dont you PR it?

**Comment by zethnest** [comment]
> Hotkeys just would ignore the new categories if I'm reading the code right.

Oh right because the categories are hardcoded there. The items inside the categories are dynamic. Combining key combos for both blocks and categories is illogical. They can get confused which is which

**Comment by ThePythonGuy3** [comment]
@sk7725 i really dont know what could happen if i make Category.java a list instead of an enum, or what else i need to change to make it possible
