### ISSUE TITLE
Not an issue at all.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3000]
### Describe what you would like changed, and why.

Look mom, issue 3000!

### Describe the changes you want to propose. Include possible alternatives.

~Plot twist mom doesn't care~

**Comment by OnyxFinger** [comment]
YYYEEEAHHH MOM IT'S #3000

**Comment by Phinner** [comment]
Congrats

**Comment by vinhsad** [comment]
nice

**Comment by Kokice5** [comment]
thre kay

**Comment by SMOLKEYS** [comment]
amazing

**Comment by RealYeet** [comment]
*3000 suggestions of Anuke pain*
