### ISSUE TITLE
Easier wars

### ISSUE THREAD

**Issue by Chaos2341** [Anuken/Mindustry-Suggestions#3002]
### Describe the content or mechanics you are proposing.

Make it where you can mind swap the enemy so you can you use them to fight for you.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I personally think you'll get higher ratings if you make this a feature.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NemesisTheory** [comment]
> I personally think you'll get higher ratings if you make this a feature.

that's not an explanation on *why* this should actually exist.
1. how, how in anuken do you even "mind swap" with enemy units
2. this would ruin balancing like a tank shell to the knee, imagine you having 10 quads and suddenly the enemy just takes them from you.

Besides, this just sounds *waaay* too overpowered, if you want easier fights, it's better off to (do not take this offensively) just get good at the game and prioritize strategies and such.

**Comment by RealYeet** [comment]
The idea is nice, however like stated above, it does not preform well in practice

**Comment by OnyxFinger** [comment]
> Besides, this just sounds waaay too overpowered, if you want easier fights, it's better off to (do not take this offensively) just get good at the game and prioritize strategies and such.

actually, it's not like if we should bee able to mind control everyone for an unlimited duration ; I think this idea is clearly balanceable, but doesn't bring much to the game anyway.

**Comment by RedstonerKBC** [comment]
This is already in the game. All you need to do is switch teams and start griefing.

**Comment by Humanoid-X** [comment]
Basically a feature that make you overpowered? Are you like 5 years old

**Comment by OnyxFinger** [comment]
> This is already in the game. All you need to do is switch teams and start griefing.

no it's not, and even if it was it would be griefing, and not an intended feature

**Comment by OnyxFinger** [comment]
> Basically a feature that make you overpowered? Are you like 5 years old

https://github.com/Anuken/Mindustry-Suggestions/issues/3002#issuecomment-926785782
