### ISSUE TITLE
Water Collector

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3003]
### Describe the content or mechanics you are proposing.

Using a Water Collector can Collect when it is Raining in the map. Collect Water when you cannot reach the water resources and when you cannot have water extractor. Especially when it is in some trash sectors where there is no coal. 

Water maybe insufficient because not raining continuously. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Getting water more easily and especially for the starter people to get water when they did not unlock water extractor.

**This is only a opinion, if we can get water underground, why cant we get water from high up in the sky?** 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Pumps be iike: ![What](https://c.tenor.com/jEMCboxsIDQAAAAM/theres-no-good-reason-for-it-derek-muller.gif)

**Comment by Ineedause** [comment]
well, this could have a very specific use in Salt Flats

**Comment by Feilong-Mindustry** [comment]
Consistency is the core principle of Mindustry. Once created, mining, production and distribution systems can work without any additional player's input. Adding any inconsistent type of system would throw a wrench in the game design.
How would a player react of impacts stopping due to lack of rain? Power blackout due to lack of wind for windmills? 
Without a way to store water and power in larger quantities as for now, this type of resource production will bring only frustration.
Also, on desert maps without water I wouldn't expect frequent rains anyway. So this won't be a solution for alternative source of water.

**Comment by begginerr** [comment]
it is cool, but not sustainable

**Comment by Sector171** [comment]
Actually not bad idea,
Few liquid containers attached together, surounded by water collectors placed in an appropriate position, we can pump from them. Could be useful in some cases.
Need balancing for campaign(when this will be unlocked?), also its efficiency should be very low but no need for anything else(no input no power).
Could be a temporary solution or permanent in some case(to boost turrets for example).

But it needs players to know how to use it, then it will be useful for sure.
Also in online games, it gives map's designer more choices to make the weather so rainy or not rainy which affects its efficiency.

**Comment by SMOLKEYS** [comment]
> But it needs players to know how to use it

~~I think that's already self-explanatory.~~

**Comment by OnyxFinger** [comment]
> Actually not bad idea,
> Few liquid containers attached together, surounded by water collectors placed in an appropriate position, we can pump from them. Could be useful in some cases.
> Need balancing for campaign(when this will be unlocked?), also its efficiency should be very low but no need for anything else(no input no power).
> Could be a temporary solution or permanent in some case(to boost turrets for example).
> 
> But it needs players to know how to use it, then it will be useful for sure.
> Also in online games, it gives map's designer more choices to make the weather so rainy or not rainy which affects its efficiency.

I think it can be good on maps with frequent rain

**Comment by begginerr** [comment]
> > Actually not bad idea,
> > Few liquid containers attached together, surounded by water collectors placed in an appropriate position, we can pump from them. Could be useful in some cases.
> > Need balancing for campaign(when this will be unlocked?), also its efficiency should be very low but no need for anything else(no input no power).
> > Could be a temporary solution or permanent in some case(to boost turrets for example).
> > But it needs players to know how to use it, then it will be useful for sure.
> > Also in online games, it gives map's designer more choices to make the weather so rainy or not rainy which affects its efficiency.
> 
> I think it can be good on maps with frequent rain

yeah but you will need storage to have constant water

**Comment by OnyxFinger** [comment]
> need storage to have constant water

yes.
