### ISSUE TITLE
Stasis Feild Generator

### ISSUE THREAD

**Issue by Killersreturn** [Anuken/Mindustry-Suggestions#3007]
Describe the content or mechanics you are proposing.

A turret-ish structure that would use extraordinary amounts of power to create a stasis feild that disable all units in a large radius. It would take minute to rev up and only have the feild active for so long.

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would give turrets extra time to destroy enemies and menders a chance to heal. If would probably be too powerful for enemy bases, so it could just not be allowed in them. Bosses would definitely be immune, and T3+ units would try to avoid the feild.

Before making this issue, check the boxes below to confirm that you have acknowledged them.

 ✔I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

 ✔I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

✔ I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
In a way this is already in the game with waves and tsunamis, completely shutting down units has never fitted in the game, while it is a nice idea, in practice we already have alternatives and it does not suit the game.

**Comment by OnyxFinger** [comment]
> A turret-ish structure that would use extraordinary amounts of power to create a stasis feild that disable all units in a large radius. It would take minute to rev up and only have the feild active for so long.

Oracle vibes...
