### ISSUE TITLE
Spotlight turret

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#3011]
### Describe the content or mechanics you are proposing.

A turret that casts a light on top of an enemy, revealing it's position in the dark.
2x2, consumes 75 power/s when active, 50 block range*

*Numbers up to Anuke

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Helps with making darkness a more interesting game mechanic.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
I think something to make it hidden when not allowed by the map creator would be useful

**Comment by Dangleos** [comment]
Regular "controle" comand needs getblock option.

**Comment by itcannotbe** [comment]
Minimap be like:

![Screw GIF](https://c.tenor.com/BTHCZFcjpBkAAAAM/screw-you-guys-eric-cartman.gif)
