### ISSUE TITLE
Control all units

### ISSUE THREAD

**Issue by Theoneflop** [Anuken/Mindustry-Suggestions#3019]
### Describe what you would like changed, and why.

My suggestion would be to allow solo users to be able to control all nearby units (instead of just like 6 max) by tapping 3 times on their robot. 
Why? well because sometimes, players like me need their whole troops to support them against an army. This would alleviate some need of logic-knowledge for some players.

### Describe the changes you want to propose. Include possible alternatives.

Simply 3 taps to controll all nearby units and 2 taps (the current one) for limited units control.

**Comment by RealYeet** [comment]
Maybe only in sandbox, otherwise I feel like this fits better in a mod

**Comment by Theoneflop** [comment]
> Maybe only in sandbox, otherwise I feel like this fits better in a mod. _Also balancing goes outside the roof, immagine controlling 24 Reigns, Toxos, corveus, etc… wtf is the base supposed to do?_

This is more valid for offline maps where you're alone against the computer.

**Comment by OnyxFinger** [comment]
I actually find this correct, my only concern is that units would have a hard time gathering themselves around you

**Comment by OnyxFinger** [comment]
> Maybe only in sandbox, otherwise I feel like this fits better in a mod. _Also balancing goes outside the roof, immagine controlling 24 Reigns, Toxos, corveus, etc… wtf is the base supposed to do?_

hmm.. logic can do that already, and there is no reason for you to have no you to have no defenses/units to defend yourself

**Comment by Theoneflop** [comment]
> I actually find this correct, my only concern is that units would have a hard time gathering themselves around you

You could gather them by using one command center.

**Comment by Theoneflop** [comment]
> > Maybe only in sandbox, otherwise I feel like this fits better in a mod. _Also balancing goes outside the roof, immagine controlling 24 Reigns, Toxos, corveus, etc… wtf is the base supposed to do?_
> 
> hmm.. logic can do that already, and there is no reason for you to have no you to have no defenses/units to defend yourself

Lmfao I was gonna post a comment like that one but you did it before me xD

**Comment by OnyxFinger** [comment]
> > I actually find this correct, my only concern is that units would have a hard time gathering themselves around you
> 
> You could gather them by using one command center.

no, I was talking about how commanding many units may create a big nonsense ball around you, and not all units will be in position/you just can't move anymore

**Comment by Theoneflop** [comment]
> > > I actually find this correct, my only concern is that units would have a hard time gathering themselves around you
> > 
> > 
> > You could gather them by using one command center.
> 
> no, I was talking about how commanding many units may create a big nonsense ball around you, and not all units will be in position/you just can't move anymore

There are many solutions:
1. Make it so that most of the units are behind the player while 3 units guard the player.
2. Space them using some algorithm that makes sure the top-health units always stay the last so to shield the other units
3. Center them around the player in circle.

**Comment by itcannotbe** [comment]
Isn't the limit imposed because different units allows players to control more units?

**Comment by itcannotbe** [comment]
> > no, I was talking about how commanding many units may create a big nonsense ball around you, and not all units will be in position/you just can't move anymore
> 
> There are many solutions:
> 
> 1. Make it so that most of the units are behind the player while 3 units guard the player.
> 2. Space them using some algorithm that makes sure the top-health units always stay the last so to shield the other units
> 3. Center them around the player in circle.

Why do you want to have a meat ball of units in the first place, they're incredibly ineffective for offense, if you want defense, just use turrets.

**Comment by Theoneflop** [comment]
> > > no, I was talking about how commanding many units may create a big nonsense ball around you, and not all units will be in position/you just can't move anymore
> > 
> > 
> > There are many solutions:
> > 
> > 1. Make it so that most of the units are behind the player while 3 units guard the player.
> > 2. Space them using some algorithm that makes sure the top-health units always stay the last so to shield the other units
> > 3. Center them around the player in circle.
> 
> Why do you want to have a meat ball of units in the first place, they're incredibly ineffective for offense, if you want defense, just use turrets.

While my suggestion makes it very clear that this is a feature that could be used by single-player mode cases, I'd like to remind you that the enemy, most of the time, in powerful waves, already attacks you with a "meat ball" of units and many units are very powerful and are very far from being "incredibly ineffective" but surely we all have our own opinion.

**Comment by OnyxFinger** [comment]
> Isn't the limit imposed because different units allows players to control more units?

yes but it sucks that way, say hello to logic which makes more units smarter
