### ISSUE TITLE
Patrol Pod

### ISSUE THREAD

**Issue by NoobsDudes20** [Anuken/Mindustry-Suggestions#302]
You set where your Mechs will patrol. When they see an enemy they will attack it. It would be like a guard mechanic for the Mechs.

**Comment by itcannotbe** [comment]
We don't even have mechs/ships for the next version.

**Comment by SupremeTurtle** [comment]
This is basically just rally mode on the command center.

**Comment by itcannotbe** [comment]
Not exactly.

Also command center.is gone.

**Comment by Anuken** [comment]
1. Use the template.
2. This is not relevant for 6.0.
