### ISSUE TITLE
Increase control options and unit control methods

### ISSUE THREAD

**Issue by hyx3179** [Anuken/Mindustry-Suggestions#3021]
### Describe the content or mechanics you are proposing.

使用处理器直接控制方块的方向
使用变量绑定单位（而不是处理器），之后使用这个变量去控制单位
Use the processor to directly control the direction of the block
Use the variable to bind the unit (not the processor), and then use this variable to control the unit

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

大多数服务器会禁止处理器控制单位进行建造操作，这是目前使用处理器改变建筑方向的唯一方法？
改变建筑方向应该不是一个建造操作，而是一种修改操作，就像修改分类器的```config```
现有的单位控制方法，在有大量单位时无法很好的执行。
当我想控制200个单位中的10个时，循环遍历每个单位的```flag```是一种很蠢的方式。
目前使用```set Mark @unit```记录单位，可以在之后非绑定时使用```Mark```获取单位状态，但是我想对```Mark```进行控制就必须执行```ubind```直到再次遇到```Mark```，而有大量单位时这会是一个非常漫长的过程，效率非常低
应该在```ucontrol```中添加类似```control```的```of```选项
我无法理解你在wiki将这种机制称为“core part”，他让单位控制变的更加复杂。
虽然我承认在思考其中逻辑时我获得了很多乐趣。

以下是机器翻译
Most servers will prohibit processor control units from building operations. Is this the only way to use processors to change the direction of buildings?
Changing the building direction should not be a construction operation, but a modification operation, just like modifying the ```config``` of the classifier
The existing unit control method cannot be implemented well when there are a large number of units.
When I want to control 10 of the 200 units, looping through the ```flag``` of each unit is a stupid way.
Currently, ```set Mark @unit``` is used to record the unit. You can use ```Mark``` to get the unit status when it is not bound later, but if I want to control ```Mark```, it must be executed ```ubind``` until you encounter ```Mark``` again, and when there are a large number of units, it will be a very long process, and the efficiency is very low
The option of  ```of``` similar to ```control``` should be added to ```ucontrol```
I can't understand that you call this mechanism "core part" in the wiki. It makes unit control more complicated.
Although I admit that I had a lot of fun thinking about the logic.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Yes

**Comment by genNAowl** [comment]
Relevant? https://github.com/Anuken/Mindustry-Suggestions/issues/1123#issuecomment-724366468

**Comment by RealYeet** [comment]
Awww man, it’s relevant

**Comment by hyx3179** [comment]
我不知道在当时，服务器是否会禁止处理器控制单位进行建造操作，而现在在服务器中我们无法使用处理器控制建筑方向。禁止的原因好像是因为有人使用单位建筑功能在服务器中捣乱？这不应该成为单人游戏和多人游戏不同的原因。或者添加新的```ucontrol```选项，以绕过使用```build```命令。
I don't know whether the server would prohibit the processor control unit from building operations at that time, but now we can't use the processor to control the direction of the building in the server.  The reason for the prohibition seems to be because someone used the unit building function to make trouble in the server?  This should not be the reason why single player games are different from multiplayer games.  Or add a new ```ucontrol``` option to bypass using the ```build``` command.

**Comment by itcannotbe** [comment]
You do realize that people want stuff that they could do on singleplayer on multiplayer right?

**Comment by hyx3179** [comment]
> 相关的？[第1123章（评论）](https://github.com/Anuken/Mindustry-Suggestions/issues/1123#issuecomment-724366468)

在这个 issue 中 Anuken 提到块随逻辑自发地旋转的问题，我不太了解通过单位间接控制和使用处理器直接控制有什么区别，但通过```build```我们可以完成这样的的操作。

**Comment by hyx3179** [comment]
就像这样
```
getlink l 0
sensor x l @x
sensor y l @y
sensor t l @type
set i 0
ubind @poly
ucontrol build x y t i 0
wait 1
op add i i 1
jump 6 lessThan i 4
```

**Comment by acoaco** [comment]
有一陣子很多人在玩病毒邏輯 很多server ban了build 可以輕鬆毀滅一個遊戲 抓poly/mega隨便一定範圍複製一樣的邏輯
現在如何不太清楚
我有一個poly自動對陸軍下地雷+挖礦二合一的邏輯在那陣子蓋下去瞬間我就被某個server自動踢了
