### ISSUE TITLE
Make voting fast, safer, easier & smarter.

### ISSUE THREAD

**Issue by Theoneflop** [Anuken/Mindustry-Suggestions#3024]
### Describe what you would like changed, and why.

Voting is meant to help players cope with griefers. But what's the point of voting after everything is gone?

My suggestion is meant to make the voting system much simpler and obvious. Also, implementing everything in this suggestion should in theory encourage players to vote as you make it very easy for people to vote, with just one tireless click on their screen.

Sidenote: _**my suggestion is not meant to eradicate liars/mudsluggers as nothing can eradicate them and it's not the purpose of my suggestion.**_

### Describe the changes you want to propose. Include possible alternatives.

1. Once a person is voted, building and destroying ability should be frozen, both for the person who initiated the vote and the person who is voted so to prevent abuse and to combat the casuality that griefers initiate a vote against an innocent person so that no one can vote them before waiting 60 seconds.
2. People who are near you should be on the top of the players list to make it easier to vote out griefers, as often griefers are near you.
3. People that are currently being voted should be on the top of the players list with a tag "UNDER VOTE".
EXAMPLE UI:
![Adobe_20210927_012255](https://user-images.githubusercontent.com/91429098/134826154-300e3472-72fd-49e1-a697-f5212b16a8c5.jpg)
4. A player should be able to directly add a vote by hitting the hammer on the players list rather than having to type "/vote" in the chat.
5. When you hit a player's hammer, a pop-up should appear with two buttons "Vote yes / Vote no" and the hammer in the players list should turn RED if you vote yes, and GREEN if you vote no.
EXAMPLE UI:
![Adobe_20210927_010623](https://user-images.githubusercontent.com/91429098/134825812-6138e9a6-f79c-412a-9162-866d0f0cf6de.jpg)
6. If a player isn't being voted on and you hit their hammer, the vote will be initiated, and then a box demanding a reason should appear so that the player who initiated the vote enters a reasonable reason to why they voted them, if "griefing" is the reason and the player gets kicked, undo the last 20 deletes/builds the kicked player made.
7. When a player is voted on, there should be a header on the top of the screen warning that a player is being voted on with the player's name, reason of why he is being voted, and how many counts till he gets kicked. And if you want to make it even easier to kick a player, put the red and green hammers together in the header so that players don't even have to enter the player list to make their choice.

EXAMPLE VOTING UI: 
![Adobe_20210927_004904](https://user-images.githubusercontent.com/91429098/134825358-5b979cae-ac7f-43f6-aa85-a7934b45cd5e.jpg)

**Comment by Feilong-Mindustry** [comment]
Sound good, hopefully this one can get through.

**Comment by the-red-soul** [comment]
>People who are near you should be on the top of the players list to make it easier to vote out griefers, as often griefers are near you.

no it should not. This could easily lead to you clicking on the wrong name as they come near you or move away and the list updating AS you click the button to votekick. Also just unnecessary and can lead to confusion. Constantly moving list. And what about if you are in freecam looking at someone far away? People would be flipping even faster on the list.

**Comment by Theoneflop** [comment]
> no it should not. This could easily lead to you clicking on the wrong name as they come near you or move away and the list updating AS you click the button to votekick. Also just unnecessary and can lead to confusion. Constantly moving list. 

I have thought about that and it could be adressed with the following:
1. Refresh list every 3 seconds rather than instantly.
2. If same players keep staying above the player, freeze their position on the list until they get very much farther.

>And what about if you are in freecam looking at someone far away? People would be flipping even faster on the list.
It depends on the case:
1. If the player is spawned, then show the players depending on the position of the player rather than his cam.
2. If player is not spawned, the player list will be catergorized by team rather than by distance.

**Comment by Kyllingene** [comment]
> Refresh list every 3 seconds rather than instantly.

That doesn't address the problem, simply restrains it to a 3-second timer.

> If same players keep staying above the player, freeze their position on the list until they get very much farther.

Griefers attempting to maximize damage would be moving rapidly.

**Comment by itcannotbe** [comment]
You should realize your suggested "protections" can also be used maliciously with more damage than it can protect against.

Definitely not worth it.

**Comment by Feilong-Mindustry** [comment]
> You should realize your suggested "protections" can also be used maliciously with more damage than it can protect against.
> 
> Definitely not worth it.

Really? I thought that was the whole point of the suggestion. On maps with small online count and a couple of AFK players griefers are a serious issue. I'd like to take their ability to build/delete frozen as soon as the vote starts. To avoid abuse, this should happen only for the first couple votes every day. Could you elaborate on malicious part?


>  if "griefing" is the reason and the player gets kicked, undo the last 20 deletes/builds the kicked player made.

This is probably too hard to implement in the game. 


>People who are near you should be on the top of the players list to make it easier to vote out griefers, as often griefers are near you.
Doesn't sound good. Maybe allow Ctrl+Alt+Left Click on a player to initiate a vote instead of creating epileptic name list?

**Comment by itcannotbe** [comment]
I don't know maybe premptively making a vote based an a false narrative while actually griefing comes into mind.

**Comment by Feilong-Mindustry** [comment]
Good point. Maybe allow second player to be on the freezing then and every player can initiate only one vote at a time? This way we can avoid scenario of "start vote and delete everything in the meantime". 
However even if griefer starts vote to dodge own quick ban, it's creates attention for their own actions, which is better than silent mass deleting as it happens now.

**Comment by itcannotbe** [comment]
But you haven't address mudslinging. Like accuse someone that would accuse someone else. Then the actual grief will have free reign.

**Comment by Feilong-Mindustry** [comment]
I've thought about scenario when a griefer avoids quick ban by initiating a vote themselves and suggested a fix for that.
What to do when there are several griefers and first one is getting voted out, while the second one is deleting buildings in peace? Nothing, it's not an issue on smaller servers, while bigger ones are not affected by griefers that badly. 
You can also think about situation when a flock of griefers 5 members strongs joins 4 players server. They could ban everyone else and delete everything they want. It's fine.

**Comment by Theoneflop** [comment]
> > Refresh list every 3 seconds rather than instantly.
> 
> That doesn't address the problem, simply restrains it to a 3-second timer.
> 
> > If same players keep staying above the player, freeze their position on the list until they get very much farther.
> 
> Griefers attempting to maximize damage would be moving rapidly.

Most griefers can be caught in the act and kicked right away. But you stroke a particular point.
Here is my solution for this:
We could implement another variable to position which would be the building/destroying variable. Think about it, a griefer will go on to grief everything at the same moment. So this variable will put the highest player on the list depending on:
1. How nearby they are
2. If they suddently began destroying everything

**Comment by Theoneflop** [comment]
> You should realize your suggested "protections" can also be used maliciously with more damage than it can protect against.
> 
> Definitely not worth it.

> I don't know maybe premptively making a vote based an a false narrative while actually griefing comes into mind.

Well, thing is, my suggestion does **not** say it will eradicate liars. There was and there will always be liars. But what my suggestion proposes is to encourage players to vote and to discourage liars by punishing them with a 60 seconds interaction freeze.

**Comment by Theoneflop** [comment]
> I've thought about scenario when a griefer avoids quick ban by initiating a vote themselves and suggested a fix for that.
> What to do when there are several griefers and first one is getting voted out, while the second one is deleting buildings in peace? Nothing, it's not an issue on smaller servers, while bigger ones are not affected by griefers that badly.
> You can also think about situation when a flock of griefers 5 members strongs joins 4 players server. They could ban everyone else and delete everything they want. It's fine.

When there is a flock of griefers 5+ then there is literally no reason for you to even play on that server. My suggestion aims to slam down every-day-griefers. It's not meant to eradicate griefers/liars/mudslugging.

**Comment by itcannotbe** [comment]
Griefers aren't a stupid group of people, they can and they will make a way to cause mayhem.

Stop imposing restrictions that will impact innocent people. Cause the only thing that would result is frustration. Just actively moderate servers if you want to or implement save states where trusted members of the server can initiate.

**Comment by itcannotbe** [comment]
> > I've thought about scenario when a griefer avoids quick ban by initiating a vote themselves and suggested a fix for that.
> > What to do when there are several griefers and first one is getting voted out, while the second one is deleting buildings in peace? Nothing, it's not an issue on smaller servers, while bigger ones are not affected by griefers that badly.
> > You can also think about situation when a flock of griefers 5 members strongs joins 4 players server. They could ban everyone else and delete everything they want. It's fine.
> 
> When there is a flock of griefers 5+ then there is literally no reason for you to even play on that server. My suggestion aims to slam down every-day-griefers. It's not meant to eradicate griefers/liars/mudslugging.

Those are few and in between.

**Comment by Theoneflop** [comment]
> Griefers aren't a stupid group of people, they can and they will make a way to cause mayhem. Often time using the way meant to prevent them in their favor
> 
Just because a group is not stupid that you should not fight them. Give me a scenario where one griefer(which my suggestion covers) could use my system and abuse it. Forget lies/Mudslugging as these two are already present and will always be and players themselves are responsible to discern between the two.

> Stop imposing restrictions that will impact Innocent people. Cause the only thing that would result is frustration. Just actively moderate servers if you want to or implement save states where trusted members of the server can initiate.

Anything will impact innocent players, while my system impacts them lesser than the current implemented system.

**Comment by Feilong-Mindustry** [comment]
The idea is fine, why so much fighting? We need better system to disconnect griefers and minimize the damage done by them. I don't see any negatives as a result of getting actual fast tools able to remove bad apples from a server. 
What are you afraid of? Not being able to build for 60 seconds in case someone clicked on you?
Right now small servers with inexperienced players suffer the most from griefers, because players are more concerned with their cryo mixers not accepting lead rather than looking at the chat and voting out trolls. 
A simple pop-up window with vote and the reason for kick is enough to solve the most cases. And freezing will allow to keep players base intact.

**Comment by Theoneflop** [comment]
> The idea is fine, why so much fighting? We need better system to disconnect griefers and minimize the damage done by them. I don't see any negatives as a result of getting actual fast tools able to remove bad apples from a server.
> What are you afraid of? Not being able to build for 60 seconds in case someone clicked on you?
> Right now small servers with inexperienced players suffer the most from griefers, because players are more concerned with their cryo mixers not accepting lead rather than looking at the chat and voting out trolls.
> A simple pop-up window with vote and the reason for kick is enough to solve the most cases. And freezing will allow to keep players base intact.

Very well said.

**Comment by FitmoF** [comment]
Honestly,the freezing would be fine if you could only vote teammates,if you can vote everyone then you can just vote enemies in  PvP

**Comment by Theoneflop** [comment]
> Honestly,the freezing would be fine if you could only vote teammates,if you can vote everyone then you can just vote enemies in PvP

For sure, you can only vote teammates. There is not point in voting enemies.
