### ISSUE TITLE
resume the game

### ISSUE THREAD

**Issue by Victoirepointthree** [Anuken/Mindustry-Suggestions#3025]
### Describe what you would like changed, and why.

the resumption of play

### Describe the changes you want to propose. Include possible alternatives.

I'd just like to add a little button in the corner of the campaign so that you can replay the last map you were on before you left or returned to the map. Or make a history of the maps you've visited. Because it's extremely annoying to search through all the areas you've already done to finally find your backup.

**Comment by Theoneflop** [comment]
Why isn't this already implemented in mindustry???!

**Comment by RealYeet** [comment]
He means a button to fast travel to the last sector you were in on camPAIN

**Comment by oinkymoo** [comment]
when opening the map, the back button in the bottom left serves this function. also the first sector that will be highlighted when returning from the menu is the last sector played

**Comment by SMOLKEYS** [comment]
> the resumption of play

sounds like some sort of spinoff game

**Comment by RealYeet** [comment]
> when opening the map, the back button in the bottom left serves this function. also the first sector that will be highlighted when returning from the menu is the last sector played

But he mean when you are in another sector

**Comment by oinkymoo** [comment]
> > when opening the map, the back button in the bottom left serves this function. also the first sector that will be highlighted when returning from the menu is the last sector played
> 
> But he mean when you are in another sector

If that’s the case, then why did they only mention being able to backtrack to before returning to map, and not to before entering a new map
