### ISSUE TITLE
Retusa rebalance

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3026]
### Describe the content or mechanics you are proposing.

Currently, retusa is kind of boring and is completely unused - generally, for a unit, range is everything, *much especially so for a boat*, but retusa has no range at all, which makes it completely useless. What could be done is: resprite the mines into torpedoes; give the torpedoes low direct damage but a significant amount of splash damage (so they are countered by segments and force projectors); give the torpedoes a low amount of velocity but a lot of lifetime, resulting in a lot of range; make the bullets be a TorpedoBulletType of sorts that explodes when in contact with a non-liquid floor or block and also give the torpedoes slight homing so it's actually possible to aim them
Regarding balancing of this, look at risso - risso would be just as good as retusa, not even taking into consideration that retusa still wouldn't be able to attack non-coastal targets, and if retusa would turn out too good anyway, one solution is to just remove or weaken the repair beam

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Make retusa actually interesting and useful

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Yes

**Comment by RealYeet** [comment]
Also make torpedo deal 2x damage to boats *Retusa torpedo boat lol*
