### ISSUE TITLE
Bring back item vaccums.

### ISSUE THREAD

**Issue by Theoneflop** [Anuken/Mindustry-Suggestions#3028]
### Describe the content or mechanics you are proposing.

Long before v6 ever was, item vaccums existed.
They satisfied the very need of moving items fast, efficiently & clutterlessly.

But after v6, item vaccums were dismissed as of a change in ways item gates, item sorters & conveyors work.

**BEFORE V6** (ITEM VACCUMS)
![Screenshot_20210927-172407_Mindustry](https://user-images.githubusercontent.com/91429098/134935779-0bdac5aa-098f-4ac3-9283-67544be48b01.jpg)

**AFTER V6** (Plastinium Conveyors)
![Screenshot_20210927-172337_Mindustry](https://user-images.githubusercontent.com/91429098/134935871-19365741-ef45-46fa-b0a0-296331683bd5.jpg)

Now don't get me wrong, plastinium conveyors are great, but they take time, space and precious resources to make.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would simply make most bases cleaner, while making it easier to move items.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
And basically make every other transportation method useless.

So: 

![No](https://c.tenor.com/10i4quIbVEoAAAAM/absolutely-not-nope.gif)

**Comment by Theoneflop** [comment]
> And basically make every other transportation method useless.
> 
> So:
> 
> ![No](https://camo.githubusercontent.com/a6d06684653f927cfef80af1f7c00641e6a9703fa765991f4cc9a37f317fd5f9/68747470733a2f2f632e74656e6f722e636f6d2f313069347175496256456f414141414d2f6162736f6c7574656c792d6e6f742d6e6f70652e676966)

Most transportation methods are usless anyways infront of plastinium conveyors.

**Comment by itcannotbe** [comment]
> > And basically make every other transportation method useless.
> > So:
> > ![No](https://camo.githubusercontent.com/a6d06684653f927cfef80af1f7c00641e6a9703fa765991f4cc9a37f317fd5f9/68747470733a2f2f632e74656e6f722e636f6d2f313069347175496256456f414141414d2f6162736f6c7574656c792d6e6f742d6e6f70652e676966)
> 
> Most transportation methods are usless anyways infront of plastinium conveyors.

Plastanium Conveyors have drawbacks compared to other transportation methods.

**Comment by Theoneflop** [comment]
> > > And basically make every other transportation method useless.
> > > So:
> > > No (GIF Redacted)
> > 
> > 
> > Most transportation methods are usless anyways infront of plastinium conveyors.
> 
> Plastanium Conveyors have drawbacks compared to other transportation methods.

And so do item vaccums.

**Comment by BlueWolf3682** [comment]
![Screenshot_20210927-093620](https://user-images.githubusercontent.com/61173114/134940142-67fd58ff-e4b8-4602-b96a-d25011b3f925.png)

**Comment by itcannotbe** [comment]
> > > > And basically make every other transportation method useless.
> > > > So:
> > > > No (GIF Redacted)
> > > 
> > > 
> > > Most transportation methods are usless anyways infront of plastinium conveyors.
> > 
> > 
> > Plastanium Conveyors have drawbacks compared to other transportation methods.
> 
> And so do item vaccums.

No they don't actually do have one. Unless you're lazy enough.

**Comment by OnyxFinger** [comment]
> > And basically make every other transportation method useless.
> > So:
> > ![No](https://camo.githubusercontent.com/a6d06684653f927cfef80af1f7c00641e6a9703fa765991f4cc9a37f317fd5f9/68747470733a2f2f632e74656e6f722e636f6d2f313069347175496256456f414141414d2f6162736f6c7574656c792d6e6f742d6e6f70652e676966)
> 
> Most transportation methods are usless anyways infront of plastinium conveyors.
> ![SmartSelect_20210927-183105_Chrome](https://user-images.githubusercontent.com/91429098/134939188-0fbd147b-59b8-475a-8875-1f76e5824ded.gif)

but plast convs need plast

**Comment by wdmvv** [comment]
~~so, if you are talking about sneks, what about teleporters then~~

**Comment by oinkymoo** [comment]
instant unlimited item transportation is never coming back

**Comment by vinhsad** [comment]
> Now don't get me wrong, plastinium conveyors are great, but they take time, space and precious resources to make.
actually, plastanium conv is good because it's mid-game
>  item vaccums were dismissed...
actually it's called "snek" and also that's a glitch it _**should**_ be fixed

**Comment by vinhsad** [comment]
> ~so, if you are talking about sneks, what about teleporters then~

"a few thing you shouldn't sugggest"

**Comment by wdmvv** [comment]
> > ~so, if you are talking about sneks, what about teleporters then~
> 
> "a few thing you shouldn't sugggest"

yes, that was a joke

**Comment by begginerr** [comment]
> > your plastanium conveyor setup look like cancer.
> > Thats the point. Plastinium conveyors look like cancer when compared to item vaccums.
> 
> Thats the point. To show how bad they are compared to the item vaccums.

look. plas convs are indeed bad compared to vaccums. but i dont have to quote myself. close this NOW. they are not getting re added. they are convenient, but just break the game's balance.

**Comment by Kyllingene** [comment]
All that should have needed to be said here is this: *you are trying to remove resource management from a resource management game.*

**Comment by begginerr** [comment]
> All that should have needed to be said here is this: _you are trying to remove resource management from a resource management game._

never thought of it that way, but in a way its true

**Comment by numer99** [comment]
item duct.
bam, done.

**Comment by EclipseTheOldOne** [comment]
~~you litterally make the stale longer~~

**Comment by RFAC-Productions-Reborn** [comment]
Can't a mod just, forcibly close this? We really don't need the vacuum back. We literally are going to have ducts in the game and they're probably just going to work in space on astroroid sectors.

**Comment by begginerr** [comment]
> Can't a mod just, forcibly close this? We really don't need the vacuum back. We literally are going to have ducts in the game and they're probably just going to work in space on astroroid sectors.

just stop commenting please you are extending the stale death
