### ISSUE TITLE
Retusa counterbalance

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3029]
### Describe what you would like changed, and why.

Change retusa's weapon damage to somewhere lower, the current damage stat is just overkill
Results of various tests:
9 retusa VS 3 surge wall: 5 seconds
9 retusa VS 9 risso: consistent retusa win
Retusa swarm VS one unboosted force projector: stalemate
Retusa swarm VS most pre-4x4 defenses: retusa swarm wins
Retusa swarm + risso swarm VS a lot of various defenses (with force projectors): swarm usually wins
9 retusa VS 9 oxynoe: retusa win
9 retusa VS 9 minke: minke win
9 retusa VS 5 bryde/cyerce: t3 wins
Retusa swarm VS any t4/5: t4/5 win

### Describe the changes you want to propose. Include possible alternatives.

Change retusa damage to around 28

**Comment by OnyxFinger** [comment]
actually, it's whole weapon needs a change in my opinion
it's just useless, since it has a lot of damage but low range, so it's like a glass cannon that doesn't work

**Comment by RealYeet** [comment]
Well 0 range make it kinda useless to anything not a boat

**Comment by RealYeet** [comment]
Frik, I didn’t see that Anuke made old suggestion a thing, *ignore previous comment*
