### ISSUE TITLE
Display current inventory on "Configure Loadout" screen

### ISSUE THREAD

**Issue by maxshowarth** [Anuken/Mindustry-Suggestions#303]
**Describe what you would like changed, and why.**
In the configure loadout screen - it would be nice to see the current inventory available so that I know if I am exceeding the available materials.

Currently, I can select as many of any item as I like, regardless of how much I have, and the process to determine which item(s) is preventing me from launching is tedious since it requires me to go back out of the launch screen to the main map where I can select levels. 

**Describe the changes you want to propose. Include possible alternatives.**
Possible solutions:
1. Do not let people select a greater quantity of material than they have available (there should be a warning/dialogue/tool-tip that explains why they can't add any more)
2. Show the current inventory window on all screens including the loadout and selection screens.
3. Append the current inventory to the selection in configure loadout as in <<Selected Amount>>/<<Current Inventory>> (e.g. 500/1000) 

I would suggest a combination of 1 and 3 since it will likely be the most streamlined.

**Comment by potatoisagender** [comment]
I mean... Unless you are very early game, you shouldn't have a problem with loadout problems... my inventory far exceeds the maximum core storage, and you really shouldn't need much more than what is suggested to play the maps.

at least you are actually trying to play campaign.

**Comment by zethnest** [comment]
I second this idea. Might do PR if its not implemented when 6.0 is ready.

**Comment by maxshowarth** [comment]
> I mean... Unless you are very early game, you shouldn't have a problem with loadout problems... my inventory far exceeds the maximum core storage, and you really shouldn't need much more than what is suggested to play the maps.
> 
> at least you are actually trying to play campaign.

I agree with this in sentiment - but for new players, this is extremely confusing and there is no easy way to determine what the issue is since you can't see your current inventory on the configure loadout screen, or on the screen to actually launch the map.
