### ISSUE TITLE
Auto-Add Teams

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#3030]
### Describe the content or mechanics you are proposing.

A rule for PvP maps that automatically adds teams based on demand.
It turns derelict cores into a different team when a player joins.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More PvP map options

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
ohyes

**Comment by oinkymoo** [comment]
might i suggest that it instead turns player cores to derelict when demand is lacking at the start of the game but turns them back when demand rises, so that specific cores can be set to specific teams
