### ISSUE TITLE
Destoring blocks visible on serverd

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3032]
### Describe the content or mechanics you are proposing.

Why can't we see destoyed blocks on servers?
We should be able to see them. And also, if you select block for deconstruction and it has been broken before you deconstruct it if you press confirm button this block should be deleted from the memory

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

When somebody on server has build a lot of blocks in enemy atack range you can't deconstruct them because they are instantly destroyed and rebuild by polies. This has to be stoped!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
> ### Describe the content or mechanics you are proposing.
> Why can't we see destoyed blocks on servers?
> We should be able to see them. And also, if you select block for deconstruction and it has been broken before you deconstruct it if you press confirm button this block should be deleted from the memory
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> When somebody on server has build a lot of blocks in enemy atack range you can't deconstruct them because they are instantly destroyed and rebuild by polies. This has to be stoped!
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Yo, you might want to check the latest release before making a suggestion. This is already fixed
