### ISSUE TITLE
Unit locate broken blocks

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3033]
### Describe the content or mechanics you are proposing.

Unit locate should have ab option to locate broken blocks

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Only polies default ai can rebuild base. And you can't processor-control polies because they will lose this ability then

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by numer99** [comment]
"add logic function to locate broken blocks" makes more sense
With this you could detect where an enemy is attacking or something exploded and have the units flock to there
It is a very good idea you have
