### ISSUE TITLE
Expose processor state to logic

### ISSUE THREAD

**Issue by pitust** [Anuken/Mindustry-Suggestions#3034]
### Describe the content or mechanics you are proposing.

Processor state (variables, counter, links) should be available for other processors to see, so that debuggers (and other introspection-based tools) can be made in logic, for logic

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Meta-logic sounds cool AF, and it would be really cool to have like gdb, but in logic, and also debugging logic is a pain rn, and that could be improved.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
memory cell...?

**Comment by acoaco** [comment]
a mod can do that,that why most pro logic player doesn't have the question

https://github.com/DeltaNedas/ldb
https://github.com/DeltaNedas/override-lib
![擷取](https://user-images.githubusercontent.com/12513676/135082192-dd194325-a0fd-4ede-9968-588224c2ab6d.JPG)
![擷取2](https://user-images.githubusercontent.com/12513676/135082202-15dff4d8-0d73-4410-9e03-ff53d26e46ea.JPG)

**Comment by pitust** [comment]
i know about ldb, and i have it, but this is a completly different question. You can't read @counter from _another proc_, or change it, or anything else.

**Comment by acoaco** [comment]
I guess that why memory cell exist if you want see multi proc's variable at same time,though output it to cell is hassle
anuke even not design a UI like ldb,even he add it in future I don't think it's will have a good user friendly UI or api.

or try improve ldb make it can show multi logic stat UI in same time so you can see multi proc's stat at same time

most of my logic done in single proc,they don't need communication each other so ldb is enough for me,I can see all variable at same time

**Comment by pitust** [comment]
a virus would be part of the fun! and yeah, what? if you modify the code everyone will know that there is new code.
