### ISSUE TITLE
An "upgrade & rebuild" button.

### ISSUE THREAD

**Issue by Theoneflop** [Anuken/Mindustry-Suggestions#3039]
### Describe the content or mechanics you are proposing.

I'd like to propose a button(similar to the destroy & copy buttons), that would upgrade current infrastructure and builds (ex: upgrades conveyors to titanium conveyors) and that would reconstruct recently-broken infrastructure when there is no units that are able to do it already.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would just make upgrading & rebuilding equipment easier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NemesisTheory** [comment]
~~https://github.com/Anuken/Mindustry/pull/3912~~

**Comment by Theoneflop** [comment]
> ~[Anuken/Mindustry#3912](https://github.com/Anuken/Mindustry/pull/3912)~
> although i'm still confused on how this button would work for buildings

For example, it could upgrade 4 mechanical drills into an airblast one.

**Comment by Theoneflop** [comment]
> ~[Anuken/Mindustry#3912](https://github.com/Anuken/Mindustry/pull/3912)~
> although i'm still confused on how this button would work for buildings

Also, my version of the button would act like the destroy button, just a big box that upgrades whatever is inside it.

**Comment by Feilong-Mindustry** [comment]
Belts upgrade - yes please. Mechanical to pneumatic drills - maybe. Anything else - how exactly? 
As a simplest example. You have 8 graphite press working on a coal line. A logical way to upgrade the setup would be making 3 multi-presses and adding water. Do you expect the game to delete the current setup and generate new blueprint based on space geometry limitations with a press of a button? This is one of the easiest upgrade and it's already a major codding issue.

Programming is not a magic, it's requires going through **every** possible situation and finding solutions for it. @Theoneflop you constantly asking for extremely difficult additions to the game without understanding even basics of programming. You've suggested to add noob oriented mlog#2, making the game to check for every possible mistake a player can make, upgrading setups with a button press. All of those could take weeks to month to make happen and in the end would take away from the game experience.

**Comment by itcannotbe** [comment]
You already have an easier way to upgrade conveyors already.

**Comment by Theoneflop** [comment]
> Belts upgrade - yes please. Mechanical to pneumatic drills - maybe. Anything else - how exactly?
> As a simplest example. You have 8 graphite press working on a coal line. A logical way to upgrade the setup would be making 3 multi-presses and adding water. Do you expect the game to delete the current setup and generate new blueprint based on space geometry limitations with a press of a button? This is one of the easiest upgrade and it's already a major codding issue.
> 
> Programming is not a magic, it's requires going through **every** possible situation and finding solutions for it. @Theoneflop you constantly asking for extremely difficult additions to the game without understanding even basics of programming. You've suggested to add noob oriented mlog#2, making the game to check for every possible mistake a player can make, upgrading setups with a button press. All of those could take weeks to month to make happen and in the end would take away from the game experience.

I do understand the basics of programming (I'm a python dev) I just don't get mlog. 

Something being difficult doesn't mean it's not possible to do.

Here is the algorithm I suggest:
1. Once a player selects an area, detect all resources that are being used (from power to items)
2. Detect which are the inputs (coal) and which are the outputs (graphite)
3. Detect upgradable material (drills, factories etc.)
4. Upgrade them to the best possible equipment.

**Comment by RealYeet** [comment]
You can already place upgraded versions of blocks above lower tiers, like a salvo over a duo.
