### ISSUE TITLE
Getblock

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3041]
### Describe the content or mechanics you are proposing.

If getblock finds a building wariable "type" should display is it solid or non-colidable building instead if copying wariable "building". Or make sensor option to check if building has colision

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

So units could see where they could walk.
For pathfinding, radar or auto-boost

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Hexrotor** [comment]
No. `type` is the `@type` of `building`, it shouldn't be `@soild`. If you want to make units auto-boost, just check `build === null` and `type === @air`
