### ISSUE TITLE
Mudblock

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3042]
### Describe the content or mechanics you are proposing.

Add mud block to generator or compaign maps

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Mud status effect is mow unobtainable

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
You should probably note that the current generator for Serpulo is entirely temporary, and will be reworked or even removed when more planets come out.

**Comment by Anuken** [comment]
> the current generator for Serpulo is entirely temporary

I don't recall saying this.

**Comment by RealYeet** [comment]
Will the terrain generator be changed or edited in the future tho?

**Comment by Anuken** [comment]
It already underwent significant changes in v7.

**Comment by OnyxFinger** [comment]
that's nice, hopefully ore generation got improved with it

**Comment by Anuken** [comment]
It didn't.
