### ISSUE TITLE
Scheme update

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3044]
### Describe the content or mechanics you are proposing.

When you name new scheme with name what have already been taken you should have the third option "renew scheme". It will replase the scheme but save tags and description of the old scheme

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Usefull for people who frequently update their schemes. Like processors

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
Oops, my bad

**Comment by oinkymoo** [comment]
you can reopen it btw. also this should maybe not even be an option and just always happen
