### ISSUE TITLE
Millitary Base

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3045]
### Describe the content or mechanics you are proposing.

I can say That After there is a limited number of bots, it is harder to take out some base and it alsl ruined fun.
I think There should be a Millitary Base That can Let a Squad of bots to go inside and expand the bot number.
It may also act like a squad command center, maybe. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

They may control the bots more specifically but not like command center. Because it only control about 8 bots. This might be only activiated when the command center is in idle mode. 

In my opinion, 8 bots for a squad would be the Best, because sharded is 8, secondary core is 16 and necleus is 24.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You do know that the unit limit is per unit type, right?

Also the unit limit is in place to force players to use better units.

**Comment by GuestUser25** [comment]
> You do know that the unit limit is per unit type, right?
> 
> Also the unit limit is in place to force players to use better/higher tier units.

I know that, but with me 24 units are not enough for me, and when you got all your zeniths killed, with out the millitary base you will just feel doomed because you have wasted all your time for nothing but when you have a few millitary bases you can just save a few squads to stay with the core and get better attacks and all that...

**Comment by random-guy1285** [comment]
You missed the whole point man. You have to get higher tiers not resort to unit spam

**Comment by Dangleos** [comment]
> when you got all your zeniths killed, without the millitary base you will just feel doomed 

Ta-da
#
![Uploading IMG_20210929_161931.png…]()

**Comment by Dangleos** [comment]
> when you got all your zeniths killed, without the millitary base you will just feel doomed

Use payload conveyors

**Comment by OnyxFinger** [comment]
> You do know that the unit limit is per unit type, right?
> 
> Also the unit limit is in place to force players to use better/higher tier units.

I agree for that in survival, not so much in PvP

**Comment by itcannotbe** [comment]
> > You do know that the unit limit is per unit type, right?
> > Also the unit limit is in place to force players to use better/higher tier units.
> 
> I agree for that in survival, not so much in PvP

The pvp argument is irrelevant, as you can set the unit limit with custom map or just with custome rules before starting the map.

**Comment by OnyxFinger** [comment]
> > > You do know that the unit limit is per unit type, right?
> > > Also the unit limit is in place to force players to use better/higher tier units.
> > 
> > 
> > I agree for that in survival, not so much in PvP
> 
> The pvp argument is irrelevant, as you can set the unit limit with custom map or just with custom rules before starting the map.

no ? I mean it's not like if rule exist for no reason.. they're not meant to be changed,even there is a way to (as-in who ever did it ?)

**Comment by itcannotbe** [comment]
> > > > You do know that the unit limit is per unit type, right?
> > > > Also the unit limit is in place to force players to use better/higher tier units.
> > > 
> > > 
> > > I agree for that in survival, not so much in PvP
> > 
> > 
> > The pvp argument is irrelevant, as you can set the unit limit with custom map or just with custom rules before starting the map.
> 
> no ? I mean it's not like if rule exist for no reason.. they're not meant to be changed,even there is a way to (as-in who ever did it ?)

A number of servers and a significant portion of players do.

**Comment by acoaco** [comment]
I like this one but should be optional,not every map creator happy to see player can expand unit limit

**Comment by OnyxFinger** [comment]
> > > > > You do know that the unit limit is per unit type, right?
> > > > > Also the unit limit is in place to force players to use better/higher tier units.
> > > > 
> > > > 
> > > > I agree for that in survival, not so much in PvP
> > > 
> > > 
> > > The pvp argument is irrelevant, as you can set the unit limit with custom map or just with custom rules before starting the map.
> > 
> > 
> > no ? I mean it's not like if rule exist for no reason.. they're not meant to be changed,even there is a way to (as-in who ever did it ?)
> 
> A number of servers and a significant portion of players do.

so, you're not talking about modifying rules when starting the game, but when making the map ?
unless you are stupid, that's not how it works, even extending your amount of maximum units is good in PvP with ranked maps, that each have ~50-80 max unit limit (per type).
you may not realise it, but the amount of units means a lot : 
 the amount of eco, many units can mine and thus make eco
the amount of flares, to transport ressources
 the max amount of x combat unit, which is good because if you can get more then you can win (this argument is only theory though, as right now even in v7 blast bombing is just too good, and actually good players would rarely get more than 15 zeniths)
