### ISSUE TITLE
Getwater

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3046]
### Describe the content or mechanics you are proposing.

When you use getblock on water and deep water "type" should be water and deepwater instead of air

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To make getblock better

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Feilong-Mindustry** [comment]
Yes, this feature is essential for mlog path finding algorithm. Please.

**Comment by oinkymoo** [comment]
honestly i can't think of a condition where you would just need to know if a tile is empty but not that there is water there

**Comment by begginerr** [comment]
maybe for ground units? they can drown

**Comment by buthed010203** [comment]
Wouldnt it make more sense to just add a getFloor?
