### ISSUE TITLE
Sort community server list by ping

### ISSUE THREAD

**Issue by King-BR** [Anuken/Mindustry-Suggestions#3047]
### Describe the content or mechanics you are proposing.

Sort servers group in the community server list by the server with lowest ping in the group

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This way players can find better servers to play with lower lag

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
Unless you're referring to v6, it's already sorted by ping. The first group to respond to the ping will be first on the list.

**Comment by King-BR** [comment]
Yeah, i was talking about v6.  As i didnt see anything about it in the trello and the servers groups followed the order of the v6 server list file so i thought nobody had given the suggestion yet. I will be closing the issue since this feature is already done in v7
