### ISSUE TITLE
High Pressure Cannon

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#305]
**Describe the content or mechanics you are proposing.**
A more powerful wave turret that consumes significantly more fluid for more range and more knock back.

Preferably it would need

60 Power per Second
60 Liquids per second
30 Sight Range
32 Tile Range (bullet life time)
10 per second Damage

Range is high so that you can place it in the back of your defenses.
And it should have a Limited Rotation Range (+/- 60° from initial placement direction) and slow rotation speed.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make it liquid turrets more viable in applying status effects to enemy units.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
agreed. Currently, waves are a niche subject, which are only used when defenses cannot be modular and there is empty space. Additionally, putting out large oil fires with waves is impossible, due to the fact that the waves cannot get to the middle of the oil.
