### ISSUE TITLE
Logic line number display

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#3050]
### Describe the content or mechanics you are proposing.

Display the line number on the box. I drew a picture to show my idea.
![suggestion](https://user-images.githubusercontent.com/45112661/135446519-fe0d0534-f4d5-45a6-8b05-dea8cd6537e1.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It can be edited more conveniently, especially when there are too many `Jump` lines mixed together. And we can also use `@counter` more conveniently in some situations.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ETANA812** [comment]
This would be much better than my idea with the jump lines being different colors. Great Idea.

**Comment by Hexrotor** [comment]
Oh thank you Anuke !
