### ISSUE TITLE
Show all controling processors

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3054]
### Describe the content or mechanics you are proposing.

If unit is controlled by multiple processors when you look at it ui show you only one of them and if you look at unshown processors ui wouldn't tell you that it controls some units even thought it does

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To see all processors that control this unit

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
And then sensor @controlled should show how much processors control this unit

**Comment by Hexrotor** [comment]
Unit can only be controlled by one processor at a time.

**Comment by Dangleos** [comment]
> Unit can only be controlled by one processor at a time.

No. Unit can be controlled by unlimited amount of processors. Many processors based on it

**Comment by Hexrotor** [comment]
> No. Unit can be controlled by unlimited amount of processors. Many processors based on it

This is a representation, the controlling is in the order. For example, the unit cannot execute two `move` commands that have different destination.
