### ISSUE TITLE
Scrap Presser

### ISSUE THREAD

**Issue by Crowned2** [Anuken/Mindustry-Suggestions#3055]
### Describe the content or mechanics you are proposing.

It would take 3 Copper and 2 Lead as inputs, as well as power (40 / sec) and would produce scrap metal. (Pressing them together to do so)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow for the creation of any material on any map, because some don't have scrap repositories.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-red-soul** [comment]
First off that makes absolutely zero sense. How can copper and lead combine to make scrap that can turn into thorium? 

Second that is overpowered as shit. Why should you be able to make any resource you want on any map??? that completely negates the point of having materials in the first place

Thirdly stop using scrap for everything and use the actual ores you are given

Fourth: NO

**Comment by oinkymoo** [comment]
Has been rejected before. https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779

**Comment by begginerr** [comment]
the same thing has been requested in #2995 and i dont even need to explain how that went

**Comment by itcannotbe** [comment]
> Has been rejected before. [#535 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779)

That's my line 😂 https://github.com/Anuken/Mindustry-Suggestions/issues/2995#issuecomment-924978558

**Comment by begginerr** [comment]
cool

**Comment by begginerr** [comment]
> > Has been rejected before. [#535 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779)
> 
> That's my line 😂 [#2995 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/2995#issuecomment-924978558)

cool

**Comment by Crowned2** [comment]
> First off that makes absolutely zero sense. How can copper and lead combine to make scrap that can turn into thorium?
> 
> Second that is overpowered as shit. Why should you be able to make any resource you want on any map??? that completely negates the point of having materials in the first place
> 
> Thirdly stop using scrap for everything and use the actual ores you are given
> 
> Fourth: NO

*Makes copper, lead, graphite, titanium, thorium, sand from scrap ... sense!

*Makes Scrap METAL from METALS (copper and lead) ... no sense (notice the lack of reverse logic? If scrap metal can make copper and lead, then why can't copper and lead make scrap metal?)

Like ??? Little to no sense went into this game, only fun, the whole reason they added scrap is to allow you to make *any* material you want as long as scrap exists in the area, and literally all scrap metal is is ... scrap metals, and copper and lead are both metals, so it would make sense that either of those would result in scrap.

**Comment by itcannotbe** [comment]
> Has been rejected before. [#535 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779)

What the point in arguing the merits of this suggestion when it's already rejected?

**Comment by Crowned2** [comment]
> > Has been rejected before. [#535 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779)
> 
> What the point in arguing the merits of this suggestion when it's already rejected?

> > First off that makes absolutely zero sense. How can copper and lead combine to make scrap that can turn into thorium?
> > Second that is overpowered as shit. Why should you be able to make any resource you want on any map??? that completely negates the point of having materials in the first place
> > Thirdly stop using scrap for everything and use the actual ores you are given
> > Fourth: NO
> 
> *Makes copper, lead, graphite, titanium, thorium, sand from scrap ... sense!
> 
> *Makes Scrap METAL from METALS (copper and lead) ... no sense (notice the lack of reverse logic? If scrap metal can make copper and lead, then why can't copper and lead make scrap metal?)
> 
> Like ??? Little to no sense went into this game, only fun, the whole reason they added scrap is to allow you to make _any_ material you want as long as scrap exists in the area, and literally all scrap metal is is ... scrap metals, and copper and lead are both metals, so it would make sense that either of those would result in scrap.

I would say that I should increase the amounts of required copper and lead, let's say 10 copper and 8 lead for 1 scrap, that way its not too op.

**Comment by itcannotbe** [comment]
![Screenshot_20211003_233543](https://user-images.githubusercontent.com/45280919/135761132-03d3693a-3e3a-479b-8a8e-5507e48e2089.jpg)

The amount doesn't matter if the mechanic itself is the problem.

**Comment by Crowned2** [comment]
> ![Screenshot_20211003_233543](https://user-images.githubusercontent.com/45280919/135761132-03d3693a-3e3a-479b-8a8e-5507e48e2089.jpg)
> 
> The amount doesn't matter if the mechanic itself is the problem.

the whole point of changing the amount is balancing it, so that it roughly equates what materials you would need to make to harvest the scrap normally.

**Comment by itcannotbe** [comment]
> > ![Screenshot_20211003_233543](https://user-images.githubusercontent.com/45280919/135761132-03d3693a-3e3a-479b-8a8e-5507e48e2089.jpg)
> > The amount doesn't matter if the mechanic itself is the problem.
> 
> the whole point of changing the amount is balancing it, so that it roughly equates what materials you would need to make to harvest the scrap normally.

You can't "balance" a horribly broken mechanic, there isn't a way around it.

**Comment by Crowned2** [comment]
> > > ![Screenshot_20211003_233543](https://user-images.githubusercontent.com/45280919/135761132-03d3693a-3e3a-479b-8a8e-5507e48e2089.jpg)
> > > The amount doesn't matter if the mechanic itself is the problem.
> > 
> > 
> > the whole point of changing the amount is balancing it, so that it roughly equates what materials you would need to make to harvest the scrap normally.
> 
> You can't "balance" a horribly broken mechanic, there isn't a way around it.

Ok but it was never implemented, so its not broken, think about the process it takes to mine scrap, all you need to do is set up drills and conveyor belts, which only uses copper, this method would use both copper and lead, and large amounts of them as well, so it wouldn't be practical to use except in places with literally no scrap available, its probably not a perfect idea yet, but its something to base off of, and i'd be willing to help "balance it" more if need be.

**Comment by the-red-soul** [comment]
You seriously have no idea what this game is about and what the mere concept of balance and resources is. 

This suggestion has already been rejected THREE TIMES. #190 #535 #2995 

>Ok but it was neverimplemented, so its not broken

The dev himself said it is horribly broken in terms of balance. It is NOT BEING IMPLEMENTED.

just reading that one sentence gave me a migrain.......

scrap is not meant to be and never will be viable.

CLOSE THIS SUGGESTION

**Comment by Crowned2** [comment]
> You seriously have no idea what this game is about and what the mere concept of balance and resources is.
> 
> This suggestion has already been rejected THREE TIMES. #190 #535 #2995
> 
> > Ok but it was neverimplemented, so its not broken
> 
> The dev himself said it is horribly broken in terms of balance. It is NOT BEING IMPLEMENTED.
> 
> just reading that one sentence gave me a migrain.......
> 
> scrap is not meant to be and never will be viable.
> 
> CLOSE THIS SUGGESTION

Quit getting pissy over a block game suggestion man, so what if its been rejected 3 times? Dr. Seuss was rejected almost 30 times. Let the dev (or anyone really) respond why exactly he thinks its a broken mechanic (even including my ammendment of "10 copper and 8 lead for 1 scrap") and i'll drop it, but I genuinely think the whole point of the game is to creatively and logically make every material as effeciently as possible, this would only improve on that point. You are incredibly annoying with your caps man, it doesn't add any emphesis to your message nor does it help anyone. Be more civil like itcannotbe bro, its not that hard.

**Comment by begginerr** [comment]
look.... i think you are missing the point. scrap CAN make copper and lead and it can be reversed. but lead and copper to thorium??????? to titanium????? to LITTERALY ANYTHING?? it just dosent make sense. the best way to implement this in my opinion is to make some sort of semi-scrap out of this that can make some things by itself but needs added materials to make everything else

**Comment by begginerr** [comment]
> Ok but it was never implemented, so its not broken
i understand what you mean but he meant if it IS added without my suggestion for balancing it out it will be extremely broken

**Comment by Killersreturn** [comment]
Ah yes, scrap to scrap.
