### ISSUE TITLE
better modded tech tree

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3056]
### Describe the content or mechanics you are proposing.

when you use lots of mods in campian, the tech tree is very  w i d e  and make it very hard to research stuffs
(ex: i want to research the [h]Core then want to research the [h]t1.2dagger)
instead, i want to sort the tech tree in categorys
like
item
crafting
drill
...
and the tech tree have a small pannel at the top right* that can teleport you to the cetagory box
if there's extra thing requirements
there'll be a dim box connected to the research (showing the thing that require you to research)
clicking on the dim box will teleport you to the required research

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make tech tree a lot easier to use
(sorry my english wasn't that good)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
It is already organized in such a fashion, you would know this if you actually cared about the second box
