### ISSUE TITLE
Unloader unload resources from Bridge Conveyor 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#3058]
### Describe the content or mechanics you are proposing.

Make unloader take out resourses from bridge conveyor just like from plastanium conveyor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Maybe this can give more ideas for schematics.
![Screenshot_20211001_125034](https://user-images.githubusercontent.com/81460407/135706172-a174b247-9b03-4b53-90da-4a6a12176c24.jpg)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by haltalt** [comment]
Too OP tbh.

**Comment by Hexrotor** [comment]
I remember that the item duct bridge support this.

**Comment by begginerr** [comment]
> I remember that the item duct bridge has this feature.

you need hack or something to use it right now tho

**Comment by Killersreturn** [comment]
Yes
