### ISSUE TITLE
Platforms/ Foundations

### ISSUE THREAD

**Issue by SuperficialIntelligence** [Anuken/Mindustry-Suggestions#306]
**Describe the content or mechanics you are proposing.**
A platform structure that can be built on oil or deep water to allow building on said liquid. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This could allow gameplay on ocean-like maps and can make naval warfare (if there will be any) more interesting

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by jaygamer81** [comment]
Ehhh it should only work for shallow water and if it works for deep water there should be a choice to or not

**Comment by SuperficialIntelligence** [comment]
> Ehhh it should only work for shallow water and if it works for deep water there should be a choice to or not

Yeah I have thought about that. Platforms on oil and deep water should be more expensive.

**Comment by itcannotbe** [comment]
Won't remove the point of deep water, tar, and lava being unbuildable on.

It actually gives map makers more control on were players can actually build on.

**Comment by stuffyAI** [comment]
Quite sure that this is on the Trello under "Naval Core", When your Core is under deep water you probably will be given the blocks to build there, I mean, In the current git build there are full water campaign maps.
