### ISSUE TITLE
Unit Disassembler

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3061]
### Describe the content or mechanics you are proposing.

A Kind of block that can Disassemble Units and give the cost back or half.
Such as a flare can be disassembled as 7 silicon or stuff like that.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

What should I say about adding this option? Most of the time after conquer the attack maps, the units that still survived is a cost of space, and I have no idea how to get ride of them.
I know there is a thing to delete payload but it is only in sand box... You cant open sandbox in campaign can you? So I used the thorium reactor, but they are expensive.

Afterall, this is only a idea, to make units to be disassembled quickly and without any heavy costs. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Ngl, sounds like someone played beta mindy recently

**Comment by GuestUser25** [comment]
> Ngl, sounds like someone played beta mindy recently 

I never did. I just keep thinking that the unit after destroying attack map is a waste of space and they do nothing.

**Comment by VikKever** [comment]
This block is already planned ([https://trello.com/c/qIFprowT/882-payload-deconstructor](url), [https://discordapp.com/channels/391020510269669376/513178557653188609/868144916566540339](url))

**Comment by GuestUser25** [comment]
It is different. The current one is only available in sandbox. It is not for campaign.

**Comment by GuestUser25** [comment]
> This block is already planned ([trello](https://trello.com/c/qIFprowT/882-payload-deconstructor), [discord](https://discordapp.com/channels/391020510269669376/513178557653188609/868144916566540339))

It is different. The current one is only available in sandbox. It is not for campaign.

**Comment by GuestUser25** [comment]
> This block is already planned ([trello](https://trello.com/c/qIFprowT/882-payload-deconstructor), [discord](https://discordapp.com/channels/391020510269669376/513178557653188609/868144916566540339))

Also, it is in the list that said DONE.
And the only payload deconstructer is only can be used in sandbox, so that is not actually what i am suggesting.

**Comment by VikKever** [comment]
The payload void (which is available in the alpha versions) is a different block than the payload deconstructor. The payload void is sandbox-only, takes no time to destroy units and doesn't give back the resources, while the deconstructors will also be available in campaign, will return resources and take a little bit of time to destroy a unit.

**Comment by VikKever** [comment]
> Also, it is in the list that said DONE. And the only payload deconstructer is only can be used in sandbox, so that is not actually what i am suggesting.

It's finished, but not yet in the alpha versions

**Comment by the-red-soul** [comment]
i have an issue with this: omura and its flare generation

**Comment by GuestUser25** [comment]
Ok thanks
