### ISSUE TITLE
Production énergétique et armes

### ISSUE THREAD

**Issue by Cycy1** [Anuken/Mindustry-Suggestions#3062]
### Describe the content or mechanics you are proposing.

Bonjour, dans mindustry après vérification de tous ce qui été proposé, j'ai eu l'idée de proposer à rajouter des centrales qui demande du pétrole (en conduit) et/ou une autre centrales qui demande de la lave (en conduit) et qui pourrait produire des déchets.
Dans un autre domaine j'ai pensé à deux cannons, un qui ferait de gros dégâts de zonne, et un cannon cryogénique.
Pour le moment c'est tout j'espère que les idées sont plaisantes et réalisable.
Je tiens à préciser que je suis sur mindustry tablette sur la version 126.2

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Je pense que l'ajout des ces armes aussi haut "level" soit elle et consommatrices en ressources peuvent améliorer le jeu de part une plus grosse puissance de feu mais mais aussi de nouveaux atouts comme par exemple le cannon cryogénique qui pourrait refroidir automatiquement les autres tourelles déjà en place ou les usines. Pour les centrales c'est juste produire plus d'énergie et plus rapidement avec la facilité d'accès des ressources dont il est question d'utiliser.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
### Translated

###### Describe the content or mechanics you are proposing.

 Hello, in mindustry after checking all that has been proposed, I had the idea of ​​proposing to add power plants that require oil (in duct) and / or another power plant that requires lava (in duct) and  that could produce waste.
 In another area I thought of two cannons, one that would do great area damage, and a cryogenic cannon.
 For now that's all I hope the ideas are fun and achievable.
 I want to clarify that I am on mindustry tablet on version 126.2

###### Describe how you think this content will improve the game.  If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

 I think that the addition of these weapons as high "level" is it and consuming in resources can improve the game by a greater firepower but also new advantages such as for example the cryogenic cannon which could automatically cool the others.  turrets already in place or factories.  For the power stations, it is just producing more energy and more quickly with the ease of access of the resources which it is question of using.

**Comment by itcannotbe** [comment]
> add power plants that require oil (in duct) and / or another power plant that requires lava (in duct) and that could produce waste.

Oil Power Plants -> Oil into coal centrifuge then into steam generator

Lava/Slag Power Plant -> Put the Thermal Generator on Lava Pools
Because they were in the game at one point but were hard to balance hence a replacement mechanic was in place.

> That would do great area damage
What's a Ripple again?

> cryogenic cannon
Ah yes, conduits exist.

**Comment by OnyxFinger** [comment]
>  What's a Ripple again?

even if ripple didn't exist, there would've been no need for this gun. There is a lot for AOE in this game
