### ISSUE TITLE
Logic can read state of command center (attack/rally/idle) by using the "@config" property in the sensor command

### ISSUE THREAD

**Issue by tarath** [Anuken/Mindustry-Suggestions#3064]
### Describe the content or mechanics you are proposing.

I'd like code like this: 

```
sensor result center1 @config
print result
printflush message1
```

To print "attack", "rally" or "idle" or alternatively 0,1,2.  Right now it just prints "null" regardless of the state of the command center

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would make it easier to employ logic that only takes effect when you are having your units attack, or alternatively you could have your units help around your base (mine/build/transport resources) only when the command center is idle.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
I'm not sure if this is already implemented, I see code that might be
