### ISSUE TITLE
Phase Conveyor Rework

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3068]
### Describe the content or mechanics you are proposing.

Single Point Powering

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To make phase conveyors a more viable transportation method when used for long range transport.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
what?

**Comment by the-red-soul** [comment]
He wants to make it so that for a phase conveyor to transfer items you just need to power one end of it. Not sure what this means for chaining them together however....

**Comment by begginerr** [comment]
> He wants to make it so that for a phase conveyor to transfer items you just need to power one end of it. Not sure what this means for chaining them together however....

it already does that....

**Comment by RealYeet** [comment]
He means when chaining 3 or more phase conveyors together, you only need to power the first of the first.

**Comment by Humanoid-X** [comment]
yes

**Comment by OnyxFinger** [comment]
tbh that wouldn't change much.
I think that since they're a bridge, they're probably supposed to be used as a bridge, else plast conv wouldn't exist in the first place

**Comment by itcannotbe** [comment]
> But the reach phase conveyors are already perfect length for small nodes, if terrain or buildings are in the way just use large nodes.

QOL ever heard of it?

**Comment by COALROCK8642orCR8642** [comment]
No. surge towers exist and try to make surge as one of the important allow in ur games.
