### ISSUE TITLE
Automated launch pad setting

### ISSUE THREAD

**Issue by Player0504** [Anuken/Mindustry-Suggestions#3069]
### Describe the content or mechanics you are proposing.

Option to make all launch pad automatically aim at the sector where player is inside

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Option to make all launch pad automatically aim at the sector where player is inside

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by random-guy1285** [comment]
That just sounds plain annoying. Why would you want that

**Comment by MistahStealYoGril** [comment]
You could make it an option on individual launch pads. It doesn't have to be all

**Comment by Player0504** [comment]
That's right
