### ISSUE TITLE
PeaceTHXD

### ISSUE THREAD

**Issue by PeaceTHXD** [Anuken/Mindustry-Suggestions#307]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SupremeTurtle** [comment]
What even is this?

**Comment by itcannotbe** [comment]
> What even is this?

It's already closed immediately after creation. Why would you even bother pointing that out.
