### ISSUE TITLE
Progression Suggestion

### ISSUE THREAD

**Issue by DrChestpain** [Anuken/Mindustry-Suggestions#3072]
### Describe the content or mechanics you are proposing.

I had an idea that basically when we beat a level it unlocks the survival mode for it. Back in v5 I used to try to beat records and whatnot for most amount of waves. For example say if I beat the required 10 waved of "Ground Zero", then I think it would be a good idea to have access elsewhere to just continually play waves. And for each new beaten level. The "unlimited survival" part of it opens. Just a thought

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe that it will give some of us the opportunity to do what was possible in V5 to play 100s even 1000s of waves to beat a world record or personal record. I found it pretty fun to see myself at wave 300 with conveyors EVERYWHERE. Barely passing each wave whilst refusing to launch. Stayed up for unhealthy lengths of time doing it.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
> I think this is incompatible with how the current campaign works. This isn't V5

then make it compatible with it.
maybe not even as a campaign thing.

**Comment by Killersreturn** [comment]
Yes I would love this as an option
