### ISSUE TITLE
Битвы игроков 2 на 2 и 3 на 3

### ISSUE THREAD

**Issue by OverDayto** [Anuken/Mindustry-Suggestions#3074]
### Describe the content or mechanics you are proposing.

Добавить в редакторе карт возможность союзных команд. Союзные команды не могут ломать постройки друг друга, а также уничтожать юнитов друг друга, стройка у ядер союзника разрешена. это даст возможность создать бои 3на3, 2на2, а также бои вместе с ии как союзника. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Много, много минирежимов. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Neryknock** [comment]
add improvement chips for units and buildings, such as additional protection, acceleration, setting fire, freezing and so on. The chips can be stored as ordinary items, different designs will require different amounts of chips.

this will add new tactics and interest to existing content
