### ISSUE TITLE
crawler

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#3075]
### Describe what you would like changed, and why.

Discussed in #balancing.
Currently crawler is an alright unit, pretty cool and all.
But it doesn't feel too logical.
Kinda tanky for a bunch of explosives and has some wierd logic to it. 

### Describe the changes you want to propose. Include possible alternatives.

#balancing agreed:
- slightly nerf crawlers explosion.
- make crawler explode on death, instead of only exploding when the weapon is fired.
- make crawler's AI only target priority blocks. (turrets, core, etc.) unless the path is blocked, which then explode on the enemy team block in the way.

Personal opinion: (these didn't get any true approval)
- reduce crawler health. (why is it 200 hp? its meant to be an explosive ball)
- increase crawler speed to account for the less hits required to kill it, allowing it to still survive running up to defenses.

Possible alternatives:
- idk

**Comment by oinkymoo** [comment]
make crawlers able to target units in survival cuz they don't

**Comment by Ilya246** [comment]
Actually a damage nerf isn't really needed, it's ok right now

**Comment by itcannotbe** [comment]
They already shoot themselves to death right? Why not blow up upon death too, what's the worst that could happen?

**Comment by numer99** [comment]
why would you want to kill them if they just explode?
