### ISSUE TITLE
Uranium

### ISSUE THREAD

**Issue by MegaInk** [Anuken/Mindustry-Suggestions#3079]
### Describe the content or mechanics you are proposing.

It could be used and used to make energy, very strong weapons and something else that you want to add 
It is so to speak like thorium but it is more powerful and more difficult to obtain

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I would improve it in that the players are perhaps very attentive since many make their farms and let them continue alone, instead this one would have to be aware that it does not explode since it would be great if it had a manual machine so that the generator does not explode.
It could be found in a ** New planet ** (I am not saying that ajuro has to have another planet, it could also be found in the current one but it is done through a set of machines towards a creator but not an extractor, if it is the case that there is no new world)
A suggestion for the name of the world would be: Uraniorus

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Killersreturn** [comment]
Uranium was already in classic. If Anuken wanted uranium in the game, there would be uranium in the game. Also, mods.
