### ISSUE TITLE
Dirt Tile and Wall

### ISSUE THREAD

**Issue by SupremeTurtle** [Anuken/Mindustry-Suggestions#308]
**Describe the content or mechanics you are proposing.**
Since there is grass and stone, dirt should be added too.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Completes the "Grass-Dirt-Stone" combo.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ILiekMelons** [comment]
add dirt

**Comment by RebornTrack970** [comment]
Dirt needs to be a tile...

**Comment by Anuken** [comment]
Implemented.
