### ISSUE TITLE
Boss/guardian adds

### ISSUE THREAD

**Issue by notrealn** [Anuken/Mindustry-Suggestions#3081]
### Describe the content or mechanics you are proposing.

While any guardian is alive, spawn increasing amounts of t1 units (or higher) every 10-30 seconds. This ends once the guardian dies and resets once the next guardian appears.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Some t4 units dont have the power to destroy cores and end the game, which can lead to a stalemate. For example, the new t4 support boat does very little building damage and can be outhealed by a single nova or mender. Most other t4s also have some method of outhealing or blocking all damage. Having boss adds (the additional units that are spawned) will eventually break the stalemate (the player also might be able to break it themselves with enough time and no interruptions). This will also slightly help preventing players from cheesing out bosses by stalling them almost indefinitely, like placing tons of walls in front of an antumbruh. I am aware that omura technically already has this since it builds flares, but omuras do enough damage to never reach a stalemate.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
In 7.0, antumbras no longer stop at random walls, so that's not an issue for them anymore.
I do agree about this with t4+s that can be easily stopped.

**Comment by notrealn** [comment]
> In 7.0, antumbras no longer stop at random walls

Yes, they won't stop at just walls, but air units can be baited with certain blocks. Antumbruh prioritizes generators and will stop moving once in range of one. Once it stops, you can start spamming walls/conveyors/whatever garbage you want.

**Comment by GuestUser25** [comment]
Agreed

**Comment by RealYeet** [comment]
Give bosses the ability to produce its T1 counterpart it T4 and T2 if T5. Like omura flares but specter daggers

**Comment by notrealn** [comment]
nah, dont think that t4s should have t1 factories. 
it wouldnt make sense for some units and would make the omura's ability useless
also with the payload deconstructors that might be added, you could farm t1s for resources

**Comment by oinkymoo** [comment]
Also enemy units can’t get into your deconstructors?

**Comment by RealYeet** [comment]
> Also enemy units can’t get into your deconstructors?

No, they cannot

**Comment by notrealn** [comment]
> Boss/Guardian ability not just T4/T5 Ability.

makes much more sense, but then does every t4/5 need another sprite or something to fit the new factory?

> Also enemy units can’t get into your deconstructors?

I thought itcannobe wanted all t4s to have the ability to make units, meaning that your units can make them too and farm resources with it.

**Comment by OnyxFinger** [comment]
> I thought itcannobe wanted all t4s to have the ability to make units, meaning that your units can make them too and farm resources with it.

actually you can't, because drops seemingly only work if you are near the core, which means you are taking a huge risk

**Comment by OnyxFinger** [comment]
> > actually you can't, because drops seemingly only work if you are near the core, which means you are taking a huge risk
> 
>     1. item drops from enemy units was removed in v7 (?)

wasn't it removed in v6 ?

**Comment by notrealn** [comment]
yeah i think that’s what i meant

**Comment by notMEEPoffaith** [comment]
> > actually you can't, because drops seemingly only work if you are near the core, which means you are taking a huge risk
> 
> 1. item drops from enemy units was removed in v7 (?)
> 2. im talking about your own units and putting them through a deconstructor
> 3. why does everybody keep misinterpreting what people say aaaaaaa
> 4. i misread what itcannotbe said, he means that only guardians will spawn adds not all t4s

my mod has deconstructors (not dumb dump, but unit emporium) but sadly due to how mindustry works, it cant give items.
