### ISSUE TITLE
Dagger needs to be Stronger

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3082]
### Describe what you would like changed, and why.

Until now, dagger have been the weakest unit in tier one. Why would I say that? Because it is so bad in every way.

1. Daggers are not cheapest
They are not the cheapest, flares are cheaper than daggers, daggers only can destract the towers in frontline but flares can even go through frontline by speeding up into the enemy defences.
2. Daggers have low speed
In mindustry, speed is a very important thing because they can get faster than enemy bullet. Normally people do not worry about novas but crawler and flares,why? Like always, the speed make them more difficult to kill.
3. Daggers have low damage
In my opinion, daggers are mobile duos. If the enemy defence are tough enough, with this tough i mean only 5 duos... Daggers cant even go though them. With crawler, at the same numbers can make a big hole through the enemy defence.
4. The whole dagger tree is bad
I can say that most of the units in dagger tree is just bad. Except for reign because it is a moving spectre. Most users rather would use flare or flare tree instead for dagger tree. Shouldnt you all admit? 

### Describe the changes you want to propose. Include possible alternatives.

Make Daggers and dagger tree better pls! At least  please make daggers damage rate higher.

**Comment by itcannotbe** [comment]
Turrets should be stonger than units, Because they're stationary.

So why would a dagger be made better than a duo?

**Comment by GuestUser25** [comment]
> Turrets should be stonger than units, Because they're stationary.
> 
> So why would a dagger be made better than a duo?
> 

So, one nova can outrange duo so it is better than a duo, novas can destory duos by outrange.
And one crawler can smash one duo (or multiple) by bombing itself.
Flares are cheap and can destroy stuff that cannot target air, like lancers( daggers could never destroy them) and arcs(this one too).
And monos can mine coppers and that mean that it can make more duos than one duo.

Overalls, in my opinion, daggers are the only one that is equal to a duo(except for flare which js real cheap).

This is only a Personal opinion afterall.

**Comment by OnyxFinger** [comment]
I think that dagger's strength shouldn't be in straight firepower or health buffs, but just spammability

> The whole dagger tree is bad
I can say that most of the units in dagger tree is just bad. Except for reign because it is a moving spectre. Most users rather would use flare or flare tree instead for dagger tree. Shouldnt you all admit?

I can say that I agree.
