### ISSUE TITLE
Radarbreaking bug

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3085]
### Describe what you would like changed, and why.

When you control many units with the same processor this chad controls multiple units in one cycle using the same variables. This results in units receiving instructions that are meant for other units and breaks their ai

### Describe the changes you want to propose. Include possible alternatives.

Fix

**Comment by oinkymoo** [comment]
1. This is not the place for bug reports, this go in the main Anuken/Mindustry repository
2. This is almost certainly not a bug with the game, but with your program. Ask for debugging help in #logic in the discord

**Comment by haltalt** [comment]
Sir. Processors don't bind multiple units at once. It's most surely a
> a bug ... with your program

**Comment by Hexrotor** [comment]
Stop making bug report here, didn't u see what we said last time?
#3059
