### ISSUE TITLE
Metaglass Walls v2

### ISSUE THREAD

**Issue by THEGAMER-10n** [Anuken/Mindustry-Suggestions#3086]
### Describe the content or mechanics you are proposing.

A wall that reflects laser bullets.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1.) Phase wall, but for lasers.
2.) We need more anti-laser defence.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-red-soul** [comment]
Why should a lesser material have more power than a later game material? Plast walls could use a bit of a health buff but do their job extremely well. Making them able to reflect would become rather overpowered no? And how would the laser reflect? Full reflection or to the laser limit of unit X? How easy would that be to program for anuke?

**Comment by begginerr** [comment]
> Why should a lesser material have more power than a later game material? Plast walls could use a bit of a health buff but do their job extremely well. Making them able to reflect would become rather overpowered no? And how would the laser reflect? Full reflection or to the laser limit of unit X? How easy would that be to program for anuke?

hmm, you have a point. but its the only thing that makes sense (with my knowledge). i mean, metaGLASS reflecting lazers just makes sense, but there is no other glass object in the game, so either 1. add another glass-like material, 2. just dont add at all, or 3. make it take the hit like phase wall and have low hp, maybe like ~1.8k for the big wall and buff big plastanium wall to ~2.7k so that plastanium is still superior

**Comment by COALROCK8642orCR8642** [comment]
Time to get 3x3 walls?
