### ISSUE TITLE
4 Logic Features request at once.

### ISSUE THREAD

**Issue by COALROCK8642orCR8642** [Anuken/Mindustry-Suggestions#3088]
### Describe the content or mechanics you are proposing.

1) Ability to see @link#___ of a processor if connected to any building (I mean while hovering mouse over it.)

2) Ability to see reconstructors which unit it is producing in @config

3) Ability to see open and see memory bank stored values. (Also when we hover mouse over it.) Maybe we can directly edit it instead of making it set from a processor.

4) I saw the BE, but did not see logic to payload deployed units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Feature 1) can reduce lot of un-nesscary steps of logic and promotes players to use getlink command more. Also make it easier to debug if player make connections wrong.

Feature 4) well i will add to it more. i cannot see ships using it. I expect ships to be on edge of the payload conveyor to get loaded instead of being on top of center. there are not so big shallow waters that map makers make u know.

PS: Also make a payload onveyor that can load all the units that you/default/un-modded have.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
3. `DeltaNedas/ldb`

**Comment by COALROCK8642orCR8642** [comment]
With Pre-Alpha v132 release. This thread is end.

End Of Discussion.
