### ISSUE TITLE
Add new defense units and a possible hard material (steel) that is used to create armor / robots.

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3089]
### Describe the content or mechanics you are proposing.

Add:
- New Farms for defense units (which generate robots T1 - T2 - T3 in the same way that was used in V.5, so for each type of robot to be generated there will be a generator block and therefore you will not have to use multiplier blocks ).
-  These defense robots will defend the entire perimeter of the village (their radius will cover the external part of the village facing the enemy, then they will go to defend up to where we have built, to do this the computer will have to generate an area that will delimit the village boundaries).  These robots will go, always remaining within the limits of the village (apart from for example when you have a secondary defense / base further away from the village and in the middle there are no buildings of their own, in this case the robots can, if someone wants, go to the defense / secondary base), as close as possible to the enemy, but they will have to cover the entire perimeter with their range, so a large group will not form at the point of the village closest to the enemies.
- Add a new resistant material (I would recommend steel) useful for: 
1 - Use it instead of Silicon only in the creation of units;
2 - this material will give the possibility to add a new block that will be used to build and then add armor to the robots (possible both for all types of robots, whether they are flying, land or going by sea).
The armors are created and stored automatically by the appropriate Farm (obviously if there are the necessary materials at the entrance) if there are no robots in the surroundings on which to glue the armor (attaches armor to various units thanks to mechanical arms).

In order to have this material you can use an auger to extract it or you can produce it by melting the scrap and then cooling it with water (or with criofuid if possible, since the water would evaporate after a while and therefore you should have the extraction of water equal to the production of the slag), this will give out random waste material, in minimal quantities, 0 or 1, and a quantity usually of 3 if 1 of material is discarded, therefore the quantity produced in the end is given by the quantity of discarded material (the production process will have to be rather slow but it will have to generate a right random quantity between 2/4 of the desired material; the slowness of production will be given by the cooling phase of the slag and by the division of waste materials from the material produced ).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

these ideas will change the most basic strategies and revolutionize the game a little since for now scrap is the least used material and with these additions it will become much more important.  The defense robots will be useful both at the beginning of the game in case of immediate attacks and a hard material, useful for producing more resistant units and additional armor for the units, will serve to fill the empty moments at the beginning of the game (when you will get to unlock the Silicon, which you will have to choose whether to produce the Silicon first or the new material) in the second part of the game (when the most advanced robots are produced and once the production of useful materials has stabilized instead of creating other Farms, it will aim to improve the units, the cost to armor the units will depend on the level of the unit chosen to be upgraded and the process will take a few seconds, for example for a T1 it will take 3 seconds, while for a T5 it will take about 21 seconds).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Ok 1, the idea to have independent factories for robots has been scraped so NO

**Comment by RealYeet** [comment]
2, how do you define a perimeter?

**Comment by RealYeet** [comment]
> ### Describe the content or mechanics you are proposing.
> Add:
> 
> * New Farms for defense units (which generate robots T1 - T2 - T3 in the same way that was used in V.5, so for each type of robot to be generated there will be a generator block and therefore you will not have to use multiplier blocks ).
> * These defense robots will defend the entire perimeter of the village (their radius will cover the external part of the village facing the enemy, then they will go to defend up to where we have built, to do this the computer will have to generate an area that will delimit the village boundaries).  These robots will go, always remaining within the limits of the village (apart from for example when you have a secondary defense / base further away from the village and in the middle there are no buildings of their own, in this case the robots can, if someone wants, go to the defense / secondary base), as close as possible to the enemy, but they will have to cover the entire perimeter with their range, so a large group will not form at the point of the village closest to the enemies.
> * Add a new resistant material (I would recommend steel) useful for:
>   1 - Use it instead of Silicon only in the creation of units;
>   2 - this material will give the possibility to add a new block that will be used to build and then add armor to the robots (possible both for all types of robots, whether they are flying, land or going by sea).
>   The armors are created and stored automatically by the appropriate Farm (obviously if there are the necessary materials at the entrance) if there are no robots in the surroundings on which to glue the armor (attaches armor to various units thanks to mechanical arms).
> 
> In order to have this material you can use an auger to extract it or you can produce it by melting the scrap and then cooling it with water (or with criofuid if possible, since the water would evaporate after a while and therefore you should have the extraction of water equal to the production of the slag), this will give out random waste material, in minimal quantities, 0 or 1, and a quantity usually of 3 if 1 of material is discarded, therefore the quantity produced in the end is given by the quantity of discarded material (the production process will have to be rather slow but it will have to generate a right random quantity between 2/4 of the desired material; the slowness of production will be given by the cooling phase of the slag and by the division of waste materials from the material produced ).
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> these ideas will change the most basic strategies and revolutionize the game a little since for now scrap is the least used material and with these additions it will become much more important. The defense robots will be useful both at the beginning of the game in case of immediate attacks and a hard material, useful for producing more resistant units and additional armor for the units, will serve to fill the empty moments at the beginning of the game (when you will get to unlock the Silicon, which you will have to choose whether to produce the Silicon first or the new material) in the second part of the game (when the most advanced robots are produced and once the production of useful materials has stabilized instead of creating other Farms, it will aim to improve the units, the cost to armor the units will depend on the level of the unit chosen to be upgraded and the process will take a few seconds, for example for a T1 it will take 3 seconds, while for a T5 it will take about 21 seconds).
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Bruh no

**Comment by Ymabert** [comment]
@RealYeet

**Comment by Ymabert** [comment]
@RealYeet I didn't say that you can't do anything with waste, I said that nobody uses it, then even if steel were added what would it change? it would change that it would be a useful material for the most important things and in any case a fair amount would remain to be to be able to continue to do that! 1! 1! 1! 1!

**Comment by Ymabert** [comment]
@RealYeet and then what good is it to say no to everything even if you have read some things but you have not even mentioned them, not even to say that they could be done or not, rather let's talk about it, help me to balance my idea and if it is really impossible to delete it, otherwise I'll redo the comment, shorten it a bit and just hope that what I wrote will be added, but no ... let's just say no to everything, let's not even consider each idea individually, then bha let's stop at the first one useless problem that only gives us the opportunity to discredit this idea, so it makes sense, yes, really constructive.
quick to comment, negatively, but obviously not to answer...
