### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#3090]
### Describe what you would like changed, and why.

When replacing a logic block with a bigger one, keep the code so you don't have to copy paste it everytime you replace it

### Describe the changes you want to propose. Include possible alternatives.

no

**Comment by Kyllingene** [comment]
A fine suggestion, but I would like to ask you: why do you profane the template so? It exists for a reason, along with the title; if you are too lazy to use them properly, don't make an issue.
