### ISSUE TITLE
Signal tower

### ISSUE THREAD

**Issue by Killersreturn** [Anuken/Mindustry-Suggestions#3091]
Describe the content or mechanics you are proposing.

 A long-range processor that can only have 4 max instructions, acting as a signal tower.

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would solve the issue of fast data travel being expensive.

Before making this issue, check the boxes below to confirm that you have acknowledged them. I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version. I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Yes
Yes
Yes

**Comment by itcannotbe** [comment]
Also see:
Memory Cells

**Comment by Bottinator22** [comment]
> Also see: Memory Cells

That's probably what he means

Using a really long-ranged tower to copy memory between two cells with a very long range

**Comment by itcannotbe** [comment]
> `Accessing Memory Cells has no range limit.`
> 
> Just not to look like a moron, I've checked accessing range despite doing it many times before. Yep, no global access to memory cells still. What the hell are you talking about?

#3016

**Comment by Feilong-Mindustry** [comment]
@itcannotbe  Ah, thank you. It actually does work for both reading and writing. Not sure how this feature got past me.
Absolutely broken, love it. •o•
Issue can be closed.

**Comment by COALROCK8642orCR8642** [comment]
You can easily make a radar through catching the correct values. or just make memory cell and microprocessor pairs.
