### ISSUE TITLE
More transparency over production/export statistics

### ISSUE THREAD

**Issue by BaseModMaker** [Anuken/Mindustry-Suggestions#3092]
### Describe what you would like changed, and why.

I think i'm not the only one who is saying that the porduction and export statistics are wonky. Say you have a mega silicon factory and want to export all your silicon to your main launch base via launch pads. Very well but this is a death sentence. The export statistics keep miscalculating or not even showing at all your production of a certain item. I have to keep going back to where a certain item is produced, wait a few minutes for the statistics to balance out. 

### Describe the changes you want to propose. Include possible alternatives.

I would like to propose a more transparent method for calculating the statistics. My idea is to add a button "calculate statistics". When you press this button you won't be able to build anything anymore and the game will calculate your production and export statistics for 3 min. When it's done calculating you are kicked out of the world and the statistics are fixed for as long as you don't reenter that sector. This would make people understand what the statistics mean and why they are like that. The current system tries to be adaptive and be flexible but its wonky and keeps changing the statistics to a way lower value than it actually is.

**Comment by OnyxFinger** [comment]
well, generally I don't think I ever needed it, because launch pads are so strong already, but to be honest, this should be improved, launch pads are kind of broken, in both ways.
