### ISSUE TITLE
naval platforms and other naval building

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#3093]
### Describe the content or mechanics you are proposing.

Naval platform: Some kind of platform that can be constructed on top of water. Any building can be built on the platform but the platform will sink when being attacked by any naval or land unit (building and lagged unit will drown and get destroyed on it).

Sea drill: Drill that can only be placed on water, will dill ores underwater. (also add underwater ores.)

Floating converyor: Conveyor that floats on water. Is slower.

Sea walls: All types of walls that can be placed on water. Has lower health, require metaglass and they don't sink.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content will add new ways to play the game since building on top of deep water is impossible.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
Conduits and belts could both be place on water and be walked on back in classic, but not anymore

**Comment by HW12345** [comment]
> I've already suggested water platforms #2276 and the ability to have drills mine underwater ores #1707. I think for balance reasons anything that floats on water would have to be fairly expensive otherwise what is the point of deep water?

I try to balance it by making them sink after getting attacked by ground and naval unit, which will destroy stuff on the platform
