### ISSUE TITLE
Make the `rotation` value of routers change when controlled by a player 

### ISSUE THREAD

**Issue by end-me-please** [Anuken/Mindustry-Suggestions#3094]
### Describe the content or mechanics you are proposing.

Change `rotation` according to the direction a player in the router is sending items to.
The value does currently not change when player controlled, but i'm not sure if this is worth a bug report.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make distribution slightly more even, and it would allow using routers as alternative input devices for logic. 
one router could replace a 4-switch setup, while being easier to control than switches (switches easy to "miss", and press/hold doesnt work with them. not optimal for faster input devices)

also, most importantly:   <summary>router router router</summary>

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by HW12345** [comment]
router

**Comment by esteemator** [comment]
router
