### ISSUE TITLE
Add ඞ to the font

### ISSUE THREAD

**Issue by luihum** [Anuken/Mindustry-Suggestions#3095]
cause why not

**Comment by Ilya246** [comment]
Dryehm is hacer he haced the votes!!!

**Comment by BlueWolf3682** [comment]
~~uh shit rt i just did too~~
**BlueWolf has voted. -1 remaining.**

**Comment by Zebryy** [comment]
amogsus
10/10 comedy

**Comment by SMOLKEYS** [comment]
**SMOLKEYS has voted. -2 remaining.**

**Comment by RealYeet** [comment]
**RealYeet has voted. -5 remaining**

**Comment by kapzduke** [comment]
**kapzduke has voted. -7 remaining.**

**Comment by the-red-soul** [comment]
No format. Rejected.

believe anuke is on vacation duck.

**Comment by Rex-Hm** [comment]
**RexHm has voted. -8 remaining.**

**Comment by numer99** [comment]
Corvus-on-water has voted,
no we do not need this
amougus is dead
we already have the repair point

**Comment by Kyllingene** [comment]
**Kyllingene has voted. -14 remaining.**

**Comment by begginerr** [comment]
we jumped from -9 to -12 sooo
**begginerr has voted. -13 remaining**

**Comment by RealYeet** [comment]
We hated on this so hard

**Comment by the-red-soul** [comment]
lets keep hating on it even harder.

**Comment by begginerr** [comment]
> Thie issue is like 3 days and 30+ people

yes because its among us

**Comment by COALROCK8642orCR8642** [comment]
mindustry is not a hype yet. maybe in future.

**Comment by USMP-lancer** [comment]
the fact this was ever a suggestion is an issue

**Comment by EclipseTheOldOne** [comment]
finally
