### ISSUE TITLE
New Map

### ISSUE THREAD

**Issue by Kokice5** [Anuken/Mindustry-Suggestions#3096]
### Describe the content or mechanics you are proposing.

Add a 2D planet map in the campaign

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Its just helpful

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
No

**Comment by TranquillyUnpleasant** [comment]
If you mean planet as in a map that is a mass of rocks, then asteroid maps will very likely be a thing in the future.

If you mean entire actual *serpulo* sized planets in one map that makes no sense.
~If you dont know what serpulo is its uh... the current planet in the campaign~

If you mean earth on the map in game that somehow makes even less sense.

Regardless, the suggestion isn't particularly well thought out.
