### ISSUE TITLE
Make crawler explode on death

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3097]
### Describe what you would like changed, and why.

Making use of my recent shootOnDeath PR, make crawler explode on death (which was actually its intended usecase) - would make crawler more reliable in a good-for-balance way

### Describe the changes you want to propose. Include possible alternatives.

Make crawler explode on death, not only on shoot

**Comment by itcannotbe** [comment]
Why suggest when you can PR it instead. LOL

**Comment by genNAowl** [comment]
I don't think there is friendly fire for crawler explosions.

**Comment by esteemator** [comment]
you are right, there is no friendly fire.
and if i get this right it's already cosidered worthy, just reduced the spashradius a bit
https://github.com/Anuken/Mindustry/compare/e06640935d93...01a8a8bb4df9

**Comment by Ilya246** [comment]
has been implemented
