### ISSUE TITLE
Make Researching Cost a small time

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3098]
### Describe the content or mechanics you are proposing.

make tech tree researching cost a little time
this is my own opinion, sorry is it doesn't fit a few people
so it sound kinda weird when you just throw a bunch of item into the tech tree and research it with no time
so what i want is
-make the researching progress cost time based of the amount of the item, also add researchTimeMultiplier (for modding)
-you can do multiple researching based on category (meaning that you can research a content of each category at a time)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make the researching progress a little more realistic
i know that mindustry doesn't need to be realistic, i just want it to be a little "better"

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by PaintheLame** [comment]
Probably one of the most useless and unneccesary things to suggest for a game like Mindustry

**Comment by COALROCK8642orCR8642** [comment]
Just use a sandbox building mod. And ask anuke, to let the throughputs affect of these sandbox in game.

When ever i do such stuff, i see game like in cheat-alert mode causing it to stop logistical calculations.
