### ISSUE TITLE
Negative HealPercent damages team

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#3099]
### Describe the content or mechanics you are proposing.

The rest of the games values will have opposite effects in negative, except for HealPercent where it simply does nothing. This would make negative values of HealPercent damage the players team instead of heal.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would open a good bit of use with modding such as neutral explosives without having to do some code fuckery to set the block to neutral team and still work. It would also allow short duration units, or units that self destruct after a certain time via a very small ranged, negative HealPercent field. Overall would be very appreciated to make objects that damage own team as well.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by begginerr** [comment]
i feel bad that this didnt get noticed
