### ISSUE TITLE
unify item/liquid/powerstacks for everything

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#31]
**Describe what you would like changed, and why.**

currently in master at least:
- there is only ConsumeLiquid, no liquid**s**
- output is split into multiple variables
this is bad and not flexible

**Describe the changes you want to propose. Include possible alternatives.**

all inputs/outputs support item/liquid/powerstacks
outputItem, outputLiquid, etc. are removed in favour of `output`
example of a json crafter block's output in suggested format
```json
"output": {
	"items": ["coal/1", "sand/1"],
	"liquids": ["oil/1", "slag/1"],
	"power": 0.25
}
```
and input
```json
"consumes": {
	"items": ["sand/3"],
	"liquids": ["oil/1", "water/1"],
	"power": 1.5
}
```

instead of "itemorliquid/amount" an object of {itemorliquid: str, amount: int, required: boolean, booster: boolean} may be used

**Comment by QmelZ** [comment]
Yeah upvote or whatever, i agree
