### ISSUE TITLE
Incremental builds?

### ISSUE THREAD

**Issue by avelican** [Anuken/Mindustry-Suggestions#310]
Hello, I just built Mindustry with `./gradlew desktop:run` on Linux.

The first build took ten minutes (mostly downloading dependencies), which is fine, but running it again with no changes took five minutes.

Shouldn't gradle detect that nothing has changed and just relaunch it? If I just want to change one variable, does the whole project get recompiled?

Sorry if this was already answered, or if the answer is obvious, I'm fairly new to Java development.

Thank you.

P.S. My friends and I really enjoy playing this game :)

**Comment by Anuken** [comment]
The builds *are* somewhat incremental; rebuilding for me takes about 12 seconds. Five minutes is a ridiculous build time; there's either something wrong with Gradle on your system or your CPU is very weak. Consider using Java 14 for builds if you aren't already, it's faster at compilation.

**Comment by DeltaNedas** [comment]
it takes me 7 minutes **on a phone** and 40 seconds on a laptop that blew up
