### ISSUE TITLE
Make units work with payload loaders

### ISSUE THREAD

**Issue by OAtobaAzul** [Anuken/Mindustry-Suggestions#3100]
### Describe the content or mechanics you are proposing.

Allow units to go in the payload loader, filling their 'inventory' (Is that how you call it?) with the item.
 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Gives more utility to payload loaders

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
*Automated flare bombing setup* I love the idea

**Comment by COALROCK8642orCR8642** [comment]
I think you mean like flares that goes into payload loader to load them with 20 blast compounds (which is there limit.)

Noice, but you can just logic it.

**Comment by COALROCK8642orCR8642** [comment]
I more like to see payload loader loading crawlers/blast vaults inside a quad.
