### ISSUE TITLE
Import Tab

### ISSUE THREAD

**Issue by SterlingRGoolsby** [Anuken/Mindustry-Suggestions#3102]
### Describe the content or mechanics you are proposing.

Tab showing imports in each sector in the campaign similar to the exports tab

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this would make it a little more clear where the all your resources are going

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TranquillyUnpleasant** [comment]
You mean the thing thats already in the latest version of the game?
![image](https://user-images.githubusercontent.com/62061444/137613205-316c59e6-1a5d-4724-a251-4f1339f48622.png)

> I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

Seems this wasn't done properly...
