### ISSUE TITLE
Nodes

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3104]
### Describe what you would like changed, and why.

Why when I have a defense powered by two nodes when one of the two nodes is destroyed the other does not automatically connect to the defenses left without energy (obviously without disconnecting from the blocks to which it is already connected or if it has already reached the limit of the connections it can also cover the structures under beam that were previously powered by another node; if instead it has connections on directly attached structures it can automatically disconnect and reconnect with those that do not receive energy, only when a nearby node is destroyed)?

### Describe the changes you want to propose. Include possible alternatives.

Why no?

**Comment by TheRealIvyX** [comment]
just make a few polys and batteries

**Comment by Ymabert** [comment]
@itcannotbe I explained why, so tell me why not? ah I also explained why it makes sense and why they would not be considered smart nodes.

**Comment by COALROCK8642orCR8642** [comment]
This is a problem of PVP, players first kill the power lines to foreshadows to make there weaker units strike.

Maybe adding somekind of backup of 2-3 shots in turrets.
Or,
Improving your own ways to build a wall. I always make sure i have sheilds up or making nodes connections manually.

**Comment by Ymabert** [comment]
@COALROCK8642orCR8642 in my opinion it would be a good addition, but you have to really look at all the cases and then understand if it would be right to add this setting to the nodes or not, I think it would only simplify the way to defend yourself, so that once my defense is over I don't have to more thinking about the arrival of energy in the defenses, but I can finally say that I don't have to think about the defense at least for a while.

**Comment by RealYeet** [comment]
How would the node even be destroyed if it behind a wall and 2 layers of turrets? If it got destroyed it means your defense fell in the first place

**Comment by Ymabert** [comment]
@RealYeet 2 + 2 = why maybe I can't afford a powerful and resistant defense maybe not?

**Comment by RealYeet** [comment]
I am pretty sure 2+2=4. Also, if your defense is not strong enough, you were not meant to capture the sector. Any way you look, it is a dumb suggestion asking to fix something that will not happen unless of stupidity.

**Comment by Ymabert** [comment]
@RealYeet read the #suggestion chat you will understand better the advantages and disadvantages of my suggestion

**Comment by itcannotbe** [comment]
> @RealYeet read the #suggestion chat you will understand better the advantages and disadvantages of my suggestion.

No.

Because there really isn't.
If your defenses starts failing. There's nothing a reconnected node can help stop that
