### ISSUE TITLE
Satellite system for "communication" between sectors!

### ISSUE THREAD

**Issue by renan823** [Anuken/Mindustry-Suggestions#3105]
### Describe the content or mechanics you are proposing.

Satellites would be used to pass logical information between sectors. Example: the player is in sector 141 and wants to receive resources from the tar fields sector, he can do this using a logical command sent from the sector he is in, which will be transmitted by the satellite to the destination (tar fields), making the automation process easier.
A satellite ONLY serves to transmit logical information between sectors.
Satellites would be made with logic processors and solar panels.
If using the smallest processor, the satellite will have a small range (an area of ​​7 x 7 sectors).
If using the medium processor the area will be 11 x 11.
And if you use the big processor we will have an area of ​​20 x 20.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would save the player time and allow for greater automation of logical processes, automating actions such as: launching items between sectors, turning on/off production of resources, sending warnings and alerts.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
...Processors don't work when you're out of the sector

**Comment by begginerr** [comment]
> ...Processors don't work when you're out of the sector

yes, then they would have to load the sector/s sending/receiving info for the logic to work properly 100% of the time and next thing you know, your computer blows up.
