### ISSUE TITLE
Map editor schematics system

### ISSUE THREAD

**Issue by Royalgummyworm** [Anuken/Mindustry-Suggestions#3108]
### Describe what you would like changed, and why.

A schematic system for use in the map editor. You can copy a pattern of tiles and save it and use it later on. Use for art, repeating elements in the(bunch of cars on a road, tanks, boats idk).
Also useful for measured ore patches and specific schems.
Basically the usual schematic system but with map tiles.

### Describe the changes you want to propose. Include possible alternatives.

Yes that.

**Comment by itcannotbe** [comment]
> @Royalgummyworm finally someone suggested this, thanks.

Actually this has been suggested too many times already.
