### ISSUE TITLE
Retusa Topedos 

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#3109]
### Describe what you would like changed, and why.

After some minor testing with the release of v.133 one thing very quickly came to my attention. Retusa torpedos don't take into account the boats velocity. This causes the torpedo to be *slower* than the Retusa, making the Retusa unable to deal damage. 

### Describe the changes you want to propose. Include possible alternatives.

Make the torpedos take into account the velocity of the Retusa so that it can actually hit something without dying.

Alternative: Make it so that it has max speed instantly instead of it gradually speeding up

*Also the waviness of the torpedo makes it hard to aim, it also may look cooler if it traveled in a straight line*

**Comment by COALROCK8642orCR8642** [comment]
Yeah this happens with gamma, but IDK about brydes or any other units. Guess i never bothered me to see how much extra range i can get through movements.

Sorry, that makes like a bryde ~30 unit range to ~40ish.

**Comment by COALROCK8642orCR8642** [comment]
IDK what my man is thinking. He removed large units ability to walk on deep water and gave these torpedos.
