### ISSUE TITLE
Bigger maps

### ISSUE THREAD

**Issue by kn00pers** [Anuken/Mindustry-Suggestions#311]
I'd like to see bigger maps in mindustry cause after few hours of playing i have everything and i have nothing to do.

**Comment by itcannotbe** [comment]
It's actually normal to get to end game in less that 2 hours.

**Comment by kn00pers** [comment]
Yep but maybe an option in editor...? 1000x1000 or bigger :D i love to play
with my friends and i think that this is the best mobile game ever created
so plase give me chance to play more and more <3

**Comment by SupremeTurtle** [comment]
If you want, play a hard map so it won't be boring.

**Comment by Mardekoya** [comment]
the maps are alredy big enough it would just be annoying to have to travel that far and to get materials
