### ISSUE TITLE
Payload drop/carry button

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3110]
### Describe the content or mechanics you are proposing.

When you are carrying payload, 
For some units that can carry payloads(like megas) , there should be a button to choose which one you are going to take or drop.
Its like the copy button but it only can choose the payload to drop/carry. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Normally I cannot get them right on mobile, when people clicked the right spot to drop the payload, the Payload did not drop it in the zone where it should be in.
If we use the button, we could drop the payload more sufficiently using less time and more accurate.

This button will only work if you are using a flying unit that can carry payload(like oct). 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by COALROCK8642orCR8642** [comment]
You are trying to say, "Selective drops". Must be feature. 

I also like to add that i sometimes just wanted command controls, instead of current command mechanics we can just hover over what unit we wanted in group and press the command button. Do vice-versa to kick a unit out of group.
