### ISSUE TITLE
Transform Mindustry into NFT game 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#3111]
### Describe the content or mechanics you are proposing.

Make it possible to actually own a game content like maps, schematics ... and so I can sell it to make a cash out this game. Blockchain games are future! Delete your game from Steam and be free from unhealthy 30% taxes and join a bright future of NFT games at Epic Game Store!
**This is a joke made in term of EGS-Steam drama. NFT shouldn't be implemented in games.**

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Go bankrupt Tim Sweeney. Sooner it will happen, better will be. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NemesisTheory** [comment]
They had us in the first half, not gonna lie.

**Comment by Phinner** [comment]
> Honestly it will be interesting if people could sell what they make.

It may sounds good on paper but if it somehow gets implemented, we might see abuse, stealing and other funny stuff.

**Comment by StoneMcYT** [comment]
> > Honestly it will be interesting if people could sell what they make.
> 
> It may sounds good on paper but if it somehow gets implemented, we might see abuse, stealing and other funny stuff.

True but the idea itself is interesting though.
