### ISSUE TITLE
Increase the plastanium conveyor throughput to 60

### ISSUE THREAD

**Issue by COALROCK8642orCR8642** [Anuken/Mindustry-Suggestions#3112]
### Describe the content or mechanics you are proposing.

Why? Since I'm PvP only.

So, I use knitted bridges more. Make it 60 or more than 200 since I will resubmit due to phase conveyor knitting.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Causing me to get a throughput of 42/sec. Also the fact now game ticks makes game time, so there is no change in throughput even on low TPS.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by COALROCK8642orCR8642** [comment]
To be thoughtful, the animation of that one stack moving causes throughput dips.

**Comment by OnyxFinger** [comment]
> God NO, no one discuss such economics. No one even play for economy, they ply for speeds.
Simple rule, More speed, Make it.

What you just said is extremely suspicious considering that PvP in this game is, for now, just a not-so-good RTS.

**Comment by Kyllingene** [comment]
Is bridge-knitting not a lot more complicated, space-consuming, time-consuming, and resource-consuming?

**Comment by OnyxFinger** [comment]
> Is bridge-knitting not a lot more complicated, space-consuming, time-consuming, and resource-consuming?

no.
