### ISSUE TITLE
EpicBattleUpdate

### ISSUE THREAD

**Issue by Cat-Mk2** [Anuken/Mindustry-Suggestions#3114]
### Describe the content or mechanics you are proposing.

battle on space leviathan factories hung with omen machine guns, thorium torpedoes, death ray and landing hangars with drones.And the assembly shop of the airborne bases with the prog data center.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Wow

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
And how will this improve the game again? I can’t really understand.

**Comment by MrDuck557** [comment]
I don't
what?

**Comment by NemesisTheory** [comment]
no

**Comment by Kyllingene** [comment]
As reference, this issue is what I think this is sarcasm directed against (unless it's serious): #3115

**Comment by Kyllingene** [comment]
And people doubted me.
