### ISSUE TITLE
Command Controls Rework

### ISSUE THREAD

**Issue by COALROCK8642orCR8642** [Anuken/Mindustry-Suggestions#3118]
### Describe the content or mechanics you are proposing.

Just hover over the mouse to indicate which unit u are trying to point (maybe use the glowup from morphing.)

Then, pressing "G" on that unit makes it under our command. Do vice-versa to kick.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Make players to cringe less on seeing eclipse escorted with quads instead of antumbras.

PS: I have just recently started to keep eye on these suggestion on daily basis. If this is a repeat of someone else, please do tell me.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
> PS: I have just recently started to keep eye on these suggestion on daily basis. If this is a repeat of someone else, please do tell me.

duplicates are allowed, you're good
