### ISSUE TITLE
Consistency in payload updating. No its not turret payloads on units

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#3120]
### Describe what you would like changed, and why.

While it completely makes sense to disable turret updates on unit payloads, the factories don't. Consistency would also be very nice and things like graphite factories should work on units. Other things that would keep consistency would be below.
explanation for each:
-payload units getting ammo from payload blocks updating makes sense, as they are supposed to update like they would in the world
-simply put, to charge payload batteries. if you ever finish payload launchpads, they can be used for sending both power and resources
-the units have the items like right there, why no use
-since a payload healing station doesn't seem to make too much sense, this one is pretty simple
-would be very nice for player transport such as for custom maps of managing two bases are once. should be made for output of tower directly if core unit to avoid people tricking them, as currently they soft-kill the players control if entering a payload conveyor
-since you cant power node a payload, this could be used for, say, mega swapping out silicon furnaces faster than what can be healed in a weaker defense or more remote defense. also useful for giving payload constructed things a head start. would very much use units ammo because unlimited energy would be severely broken.
-because these things drill, they need ground, and they don't have that while up inside a mega or on a conveyor
-things like the aegirses energy field heal blocks, and i've heard if a navanax bullet hits friendly structures it gives them power, or at least from my testing so would make sense for them to do it to payloads too
-would allow people to make refueling stations, such as for ships where they come in, get ammo from the protected inner base, heal and whatnot, and then go back out in the water on a single, simple payload line
-turrets will not move on in payload line if they can accept liquid currently, even if filled with ammo. simply d o n t if there is no liquid flow coming in.
-there is currently no way to see what has gone into a payload without unloading it, such as containers, along with health of payloads from, say, enemy fire. would be a very nice QOL thing

### Describe the changes you want to propose. Include possible alternatives.

-Power ammo types sharing power from payload batteries
-Payload loaders charging power blocks and unloaders putting out power stored in blocks
-Units taking ammo from payload containers(e.g. oct with vault with ammo items giving ammo from the vault to units), same with batteries
-Units using items they carry if ammo items instead of ammo clip, such as spirocts using coal they mined(or at least replenishing ammo)
-Healing turrets healing units in payload
-Entering payload towers as core units to go to places across the map that may not be able to go to because of AA, not taking control from the player or soft-killing it like it normally does but still not allowing core units in payload conveyors. that last bit is important to not allow core unit duplication glitches.
-Power ammo type units powering their payloads, like a mega powering a silicon smelter
-Water extractors not working on any sort of payload, along with drills and oil extractors for very obvious reasons
-EMP hits can hit payloads to disable them normally along with heal or give a power burst to friendly payloads
-Units in payload getting ammo from nearby containers and batteries
-if no liquid is present and turret is filled, move onto next payload to load
-seeing stats of blocks in payload
--payload loaders loading units with ammo, IF not already a thing

**Comment by OnyxFinger** [comment]
so uh... payload stuff is fun and all, but you know it's not gonna get much use anyway right ?

**Comment by Ribbons0121R121** [comment]
payload drivers have much more range than mass drivers
also you can cram more turrets in a payload space than normal block spaces, along with reducing conveyor ratio mess with long defense walls
