### ISSUE TITLE
Oct drop payload upon death

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3122]
### Describe what you would like changed, and why.

Oct should drop all its payload when it die, and the payload need to have a survival percentage of 20 or 30. For example, 20 dagger inside an oct, but it died, there should be at least around 4 or 5 still alive and got successfully drop down.

It should be available in campaign and also make it a option for multiplayer. 

### Describe the changes you want to propose. Include possible alternatives.

This can make the game more cautious because you never will know how many enemies it will appear when the oct died.

**Comment by COALROCK8642orCR8642** [comment]
It won't make it like drop within enemy core build radius.

**Comment by idontknowhwhattoputhere** [comment]
it would ruin the aspect of "crashing"

**Comment by GuestUser25** [comment]
> This will be interesting but could this be applied to all troops that can drop troops but for the higher tier the rate of survival is higher and the lower the tier the lower chance of survival. 

It is the same percentage. For example we can be like this:

Covus(can carry two in oct): 25 percent

Daggers(can carry 25 in oct): 25 percent

Hint: what I mean by this is that there is only half of the chance that a covus would appear(which ispretty small). And there would be about 6 daggers appear to survive the drop.

(It should depend on the game balancing.)

**Comment by GuestUser25** [comment]
> it would ruin the aspect of "crashing"

Most crashes have survivers, like plane crash.

**Comment by GuestUser25** [comment]
> Not exactly.
> 
> Planes that gets destroyed midflight never gets any survivors.*
> 

They are even safer than car travels. The death rate is smaller than you think.

**Comment by GuestUser25** [comment]
> > let me crash an oct with some primed thorium reactors.......
> 
> That will need one thorium reactor to break its shield, and it got 22000 health... Also A damage of thorium reactor is about 5000...

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry/pull/4839
