### ISSUE TITLE
Variable for modded units having payloads they carry act like they do on conveyors

### ISSUE THREAD

**Issue by notMEEPoffaith** [Anuken/Mindustry-Suggestions#3127]
### Describe the content or mechanics you are proposing.

So basically this would be a true/false variable that lets modded units have payloads they carry work. This would be set to false by default to not mess up stuff for vinalla. For turrets they could act as additional weapons for the unit.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make it so HJSON mod creators, such as myself to make special units that can carry payloads and can use the payloads as guns of some kind.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
me when dead suggestion
