### ISSUE TITLE
V6 unit prices

### ISSUE THREAD

**Issue by OnyxFinger** [Anuken/Mindustry-Suggestions#313]
**Describe what you would like changed, and why.**
After taking a few looks at the snapshots of v6 , I quickly realized that the prices are too high , for example,daggers need lead , and mynkes need glass (?)it's just adding prices that will complicate your designs more than changing the affordability,it takes lots of space to do high tier units , and "bosses"actually need 240 surge alloy , which nobody will ever reasonably afford (I'm only talking about 1st tier boss , not second tier ahah), but it's NOT over yet!basically the fact that core has a limit for every body , you can't say :I'm putting a few helper drone factories , then I'll do some revenants , because... THE DRONES WILL FILL THE GODDAMN LIMIT BEFORE THE REVENANTS CAN BE DONE BUILDING AAAAAAAAAAAAAHHH hum hum , I lost my calm did I ? 

**Describe the changes you want to propose. Include possible alternatives.**
Simply need to lower the build cost on higher tier units and make the basic small factories (not the upgraders)have a limit instead of core , none of the prices nor the core limit has been revealed in the devblog yet , so there is a "f*ck go back"button ready and the price lower is just deleting some lines and changing some numbers , it's not too hard (is it ?)

**Comment by itcannotbe** [comment]
Payload routers: Exist

Also Unit limits is basically haven't worked on yet.

Also also. Stop making suggestions based on underdevelopment features of the game.

**Comment by itcannotbe** [comment]
To further rub my point in.
![Screenshot_20200720_011824](https://user-images.githubusercontent.com/45280919/87880772-008d0a80-ca27-11ea-8e45-ab419423971d.jpg)

That's literally the first card under the first caterory in the trello board as of the date and time of this comment.

**Comment by ritzip** [comment]
![Screenshot_20200720-012347~2](https://user-images.githubusercontent.com/49394064/87880875-ca9c5600-ca27-11ea-9262-05ab007b166c.png)

**Comment by Anuken** [comment]
As others have said, don't look at stats or mechanics that are still in early development. The unit cap is clearly broken, and you're talking about high costs of units that don't even exist. "nobody will ever reasonably afford it" is *the point* of boss units.
