### ISSUE TITLE
New Player Units

### ISSUE THREAD

**Issue by gregorynikif** [Anuken/Mindustry-Suggestions#3134]
### Describe the content or mechanics you are proposing.

Different types of units a player can play with, without having to build them.

I have some examples but you can change or add whatever you want.
All these are multipliers compared to the original whatever the tier may be, if some stats are missing, then, it means that I suggest they should stay as they already are. The list and order is directly taken from the Core Database

Content:

a) Fighter

Health: x2 + X per Wave Completed
Armor: + 1 + 1 x Tier
Build Speed: x0.2
Mine Speed: x0.125
Item Capacity: x0.5
Weapons:  
                  Inaccuracy + 1 or 2 degrees
                  Rate of fire 2x10
                  Damage: 2 + X x Waves Completed
                  Building damage x1 +1% x Waves Completed
                  Always homing regardless of tier
                  Range: +2 or 3 blocks
b) Builder

Health: x 0.5
Build Speed: x 2
Mine Speed: x 0.25
Command Limit: x 0.5 rounded down
Weapons:
                 Everything x0.5
                 No homing at tier 3
                 Range: - 2 blocks
c) Miner

Health x0.75
Speed:  3 + 0.5 x tier
Build Speed: x0.2
Mine Speed: x2
Water Extracting Speed: T1: 6/sec, T2: 12/sec and T3: 24/sec
Mine Tier:  Tier 1: Copper, Lead, Coal, Scrap, Titanium, Water
                  Tier 2: The above + Thorium
                  Tier 3: The above + Oil
Command Limit: x0.5 rounded up
Item capacity: x1 + x0.5 x Waves Completed
Liquid capacity: 50 + x0.5 x Waves Completed
Weapons: Everything x0.5
                 No homing at tier 3
                 Range: - 2 blocks

Balancing:
The selection of the ship is done before entering the map and stays that way if logged out and trying to re-enter.
Cannot change ship type during playing a map, unless it's during campaign
Cannot enter other Units. Turrets are ok.
All bonuses to stats that are increased per Wave Completed means the waves of the map in general, not the waves completed while the player is playing the map. For example in a multiplayer game, a player playing from wave 1 will have the same stats as the player that joined the game at Wave 30 of the same type of ship.

All the stats are placed as a reference to make my point.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Adding these will allow to think various approaches to increase their chances of survival. Using different strategies to improve their efficiency using the features each type of ship has, compared to the original as well as players learning to play as a specific role during online games. 

I am not sure if it is improving the game or not, but I feel like this will break the standard way everyone plays and do something different.

Finally, if someone knows how to edit the game or make mods that can allow this, it's possible to learn easily if this is worth doing or not.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
> what does "x" represent in this? because it says X represents waves completed (which is a bad idea in itself to scale based on waves completed) but small x has no context behind it.

the small x stands for "times"
2 damage times waves completed
