### ISSUE TITLE
Three new Teams: Hydra, Biosa, and Specron

### ISSUE THREAD

**Issue by RFAC-Productions-Reborn** [Anuken/Mindustry-Suggestions#3137]
### Describe the content or mechanics you are proposing.

If there's Sharded, Crux, and Direlict, who's to say that there shouldn't be names for Blue, Green and Purple? But this isn't just about names or variety, it can also add to Campaign in terms of story and worldbuilding. There is a lot of potential with the lore of Spores being an invasive species. And I have an idea. And I just can't help it, my brain is on full drive.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Each planet could have a different team. What if Direlict was Sharded before Crux invaded the planet and destroyed Sharded? That could explain why Sharded starts at Ground Zero, and Direlict is in most of the sectors, while all of the bases are Crux.

In the volcano planet, it could be where the Crux came from. 

The water planet could have Hydra/Blue team, a Naval based team with naval bases and sectors. Hydra is actually in an alliance with Specron to fight against a common enemy: Biosa, the team that wants to spread Spores. Since the goal of Mindustry is to take over all important sectors and move to the next planet, I highly doubt that Specron would be your friend. But more on that later.

Biosa, the team of green on the planet of green and purple. Here they worship spores, and use them as oil or fuel. Here they are in a war against Hydra and Specron, so there can be a few Specron and Hydra bases, while a little amount of Crux bases, and a most of the bases being Biosa. This could be the planet of origin, since Sharded was destroyed, and then reformed, so most of the data is lost, and therefore most data prior to Biosa is unknown.

Specron, the last and the toughest team on a thorium based planet. Here the challenges get harsher. You're gonna have to think big and think harsh with units. The Specron knows that you'll invade their planet, and therefore plans to wipe you out before you could even step foot on the first sector. However, each sector is rich in resources, and new technology could be researched from the planet, and you can use it to fight against Specron. The Crux has attempted to invade the homeplanet of Specron, but they never did, reducing each invading to scrap. Specron, Spec, Spectre. This is further reasoning why Specron should be the endgame team, and not Crux when you get on the final planet.

Each planet could have new branches of research based on their characteristics. Underwater Conveyors can be conveyors that travel on deep water, being originally built by Hydra. Spore based weaponry and utility could be based on technology made by Biosa. And endgame technology different compared to Serpulo or the first planet could be based by Specron and its material-rich planet.

However, this is the choice of the people of Mindustry. You can disagree, you can agree, you can improve my decision. One thing for sure. Mindustry has a lot of potential in terms of lore connected between planets, the teams, and Spore.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
The other teams will see use, inter future in the trello it says there will be more factions with eve  combat
