### ISSUE TITLE
Suggestions About Units

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#314]
Here is a quick explanation of somethings you may not understand:
Lvl. 1 units : Units that are made from any factory
Lvl. 2 units : Units that are upgraded at additive reconstructor
Lvl. 3 units : Units that are upgraded at multiplicative reconstructor
and so on...

Main Idea Is: 60 Units - 3 Factories (Ground, Air, Naval) And 4 Units For Each Factory - All Units Can Be: Upgraded To Max Level/Upgraded 4 Times/Upgraded At Tetrative Reconstructor

Some factories have less units, for example, naval factory has only 1 unit which can be upgraded 2 times, an air factory has 2 units; 1 that can be upgraded 4 times and 1 that can be upgraded 2 times. I think that all factories should behave same and every factory should have 4 units that can be upgraded 4 times. That way we would have so many units and so many options for making units. Every factories starting units should be 1 basic unit (dagger, wraith, etc.) , 1 advanced unit (crawler, ghoul bomber, etc.) , 1 special unit (a unit with unique abilities like spiroct that can pull enemies and heal from attack but since we are talking about lvl. 1 units and spiroct is a lvl. 3 unit it should be a worse version of it like worse stats.) and 1 builder unit (dart ship, tau mech and etc.) when we upgrade these units their stats should be better and maybe the unit completely changes into a different unit with different attacks and/or abilities. Though units upgraded in factories should have different models, maybe multiple legs (for high lvl. units) and size. The new unit "Spiroct" is good against other units and its an unique unit compared to other units i guess but what about enemy structures? When it attacks an enemy structure it completely lacks its "pulling" ability and maybe the "healing from attack" ability (i didnt test it but this unit should be the "advanced" or "unique/special" unit type and its previous/further levels maybe should have the same ability with better/worse stats or as I mentioned before a completely different attacks/abilities.

Here is all units:

Ground

(Basic) Dagger > New Unit > Fortress > Chaos Array > Eradicator
(Advanced) Crawler > Eruptor > New Unit > New Unit > New Unit
(Unique/Special) Titan > New Unit > New Unit > New Unit > New Unit
(Builder) Alpha > Delta > Tau > New Unit > Omega

Air

(Basic) Wraith > New Unit > Revenant > Lich > Reaper
(Advanced) Ghoul Bomber > New Unit > New Unit > New Unit > New Unit
(Unique/Special) Draug Miner Drone > New Unit > Spirit Repair Drone > New Unit > Phantom Builder Drone
(Builder) Javelin > New Unit > Trident > New Unit > Glaive

Naval

Since navals are new types of units, there are no previous naval units so all of them will be new units

Note: Instead of a new unit, I mentioned that there can be the same unit with better stats, like for draug but upgraded version can mine other resources and/or is faster and/or has more item capacity. Or for eruptkr the upgraded version would be faster and/or  have more range and/or damage. By the way this is just a suggestion so you can implement the same thing with some changes.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
60 different types of units is a ridiculous amount. There's no need to have so many similar units; not only is it a lot of work to implement, but these types simply won't end up being different enough from each other to be useful. It's just artificial padding and won't add much to the game - quality over quantity.
