### ISSUE TITLE
Options for dedicated campaign server with additional server settings

### ISSUE THREAD

**Issue by DenisLT** [Anuken/Mindustry-Suggestions#3140]
### Describe the content or mechanics you are proposing.

Ability to host dedicated mindustry campaign server with additional config options like:

Server-side or client-side saves - ability to decide whether players could be able to bring their own research trees or all progress should be server-side.

Ability to decide to have single research tree or for every player to have seperate research tree that he should upgrade seperately.

Whether everyone should be in sector dedicated by host or people could freely move between sectors and be on different sectors at once (for example when attack is happening).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

At this time mindustry campaign servers are quite clunky and limited in terms of research and playability, my proposed solutions should affect game in this way:

A mindustry won't have to be launched seperately for private campaigns with friends, a server-jar file will be enough to be hosted in a basement pc for 24/7.

More freedom since people will be able to join or leave any time without the hoster being present.

Server-Client side saves option would give freedom to decide whether people want the progress they made in server to sync with their local save. For example for everyone to start fair with starting research trees without people needing to manage their local saves.

Different research trees would bring an interesting concept because they would allow specialization. For example one player specializes in military while other in reseources etc... and would make game more interesting because since resources must be spend for n number of players, players would have to be more thoughtful.

Ability to be in multiple sectors would bring even more freedom because instead of being locked in a single sector players would be able to do progress in different places of the planet independant of the host.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Serdnaley** [comment]
I really want to serve dedicated server with campaign multiplayer for my friends
Is there any updates about?
