### ISSUE TITLE
nuclear tech (but not just missiles)

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#3143]
### Describe the content or mechanics you are proposing.

Nnuclear waste:
waste from a nuclear reactor (probably not thorium), can be used as a tsunami ammunition (4.35 dps) to give a radioactive effect.

Radioactive effect:
slowly damages units and can contaminate nearby structures, can be healed by repair turrets.

Xorrosion effect:
reduces enemu defences by 20%

Uranium:
either mined like normal (i guess) or use special uranium extractors that "extract" uranium?

Plutonium:    
1: combine thorium and uranium together
2: combine uranium and neutreons

Uranium metal: 
1 uranium + 12/s water (to cool it but keep the density i guess) + 2 titanium (possibly surge alloy or plastanium
im not a dev anuken is) also non-radioactive and possibly used as a better foreshadow ammo (if surge alloy is instead of titanium).

(possibly used as a better nuke)

Radioactive material accelerator (probably not the bast name lol): shoots radioactive materials (thorium, uranium, plutonium) at high speeds dealing alot of damage (maybe a better foreshadow))
power: -850/s
HP: 4600
firerate: 0.33/s
range: 80 tiles
water: required (15/s)
cryofluid: 1.35x boost (15/s)
cost: foreshadow + 500 surge alloy, 200 lead, 500 thorium, 300 uranium metal, 7000 copper.
size: 5x5
target: air, ground
liquid cap: 20
research cost: foreshadow + 1500 surge alloy, 2000 lead, 3400 thorium, 2375 uranium metal, 3000 silicon. 
ammo 1) thorium | 500 damage (per bullet) | x3 ammo multiplier (due to the icon).
ammo 2) uranium | 1650 damage | pierce | gives "radioactive" effect.
ammo 3) plutonium | 1900 | explodes on impact (3 tile range) | gives "radioactive" effect.
ammo 4) uranium metal | 2100 damage | pierce | gives "radioactive" effect.

Radioactive slugger: like a scepter mixed with a fuse that fires radioactive materials.
HP: 3400
firerate: 3.19/s
range: 30 tiles
acccuracy: 4.5 degrees
water: required (10/s)
cryofluid: 1.5x boost (10/s)
cost: scepter + 200 graphite, 200 plastanium, 300 lead, 400 thorium, 100 uranium metal.
size: 5x5
target: air, ground
liquid cap: 20
research cost: scepter + 3000 surge alloy, 3500 thorium, 2000 lead, 1250 uranium metal, 750 plastanium, 5400 graphite.
note: fires 3 bullets per shot (10 degrees side shots)
ammo 1) thorium | 110 damage | x1.2 firerate 
ammo 2) uranium | 170 damage | pierce | gives "radioactive" effect
ammo 3) plutonium | 210 damage | "corrodes" enemy defences | gives "radioactive" effect

Corroder (meltdown but better):
power: -1700/s
HP: 4400
range: 30 tiles
cryofluid: required (30/s)
cost: meltdown + 300 silicon, 250 graphite, 400 lead, 500 thorium, 200 uranium metal.
size: 5x5
target, air, ground
liquid cap: 20
research cost: meltdown + 6000 silicon, 4000 surge alloy, 2500 graphite, 2000 uranium metal, lead 3000, 5000 copper.
ammo 1) uranium (1 per activation) | 1200 dps | "corrodes" enemy defences.
ammo 2) plutonium (1 per activation) | 1450 dps | "corrodes" enemy defences | gives "radioactive" effect
(imagine someone setting the control center to rally and nobody noticed that radioactive units are coming)

Nuclear core (singularity is the best name i could think of):
max active units + 34
item cap + 17000
hp: 10k
cost: nucleus + 2500 uranium metal, 2000 copper, 2000 lead, 3000 silicon, 4000 thorium, 500 phase fabric.
size: 6x6 (hopefully not 6x7, that would be painful...)
research cost: Nucleus + 7000 uranium metal, 8000 copper, 8000 lead, 6000 silicon, 2000 phase fabric.

Nuclear reactor:
(power:
when using uranium: +7500/s)
when using plutonium: +12500/s)
HP: 1000
cryofluid: required (4.30/s)
cost: x2 cost of thorium reactor + 50 uranium metal
size: 4x4
research cost: x3 of a thorium reactor + 700 uranium metal
(explosion:
uranium: x2 size (radiates)
plutonium x4 size (radiates) )

Uranium metal wall (small):
HP: 1200
cost: 7 uranium metal
damages nearby enemy units (40/s)
range: 20
research cost: 500 uranium metal
size: 1x1

Uranium metal wall (large):
HP:4800
cost: 28
damages nearby enemy units (160/s)
range: 20
research cost:  2500 uranium metal
size: 2x2

Neutreon generator:
power: -1000/s
input: uranium (5/s)
output: neutreons (2.5/s) (can only be transported by phase conveyors or plastanium conveyors)
HP: 2350
cost: 350 titanium, 200 silicon, 300 surge alloy, 500 copper, 200 lead.
research cost: 5500 titanium, 3000 silicon, 2000 surge alloy, 4000 copper, 3000 lead.
size: 3x3

Missile Silo:
(power:
when building -500/s
launch -5000
size: 5x5
production speed: 900s
cost: 5000 titanium, 2500 silicon, 1000 surge alloy, 4000 plastanium, 3000 copper, 2000 lead, 2000 uranium metal
research cost: 100000 titanium, 75000 silicon, 20000 surge alloy, 40000 plastanium, 60000 copper, 40000 lead, 50000 uranium metal

available missiles:
(all research costs simply x10 production cost)

explosive missile
explodes on impact like a thorium reactor
cost: 150 blast compund, 500 titanium, 200 lead, 200 copper, 150 silicon.

fire missile
burnd buildings like pyranite purning (range 10 tiles)
cost: 150 pyranite, 500 titanium, 200 lead, 200 copper, 150 silicon, 100 coal.

electric missile
shocks nearby buildings dealing 5000 damage (5 tile range)
cost: 150 surge alloy, 500 titanium, 300 lead, 200 copper, 350 silicon.

healing missile
healst 5000 hp on buildings and units (15 tile range)
cost: 150 phase fabric, 500 titanium, 200 lead, 200 copper, 150 silicon.

fast missile
x3 speed
cost: 10 pyranite, 300 titanium, 200 lead, 200 copper, 450 silicon.

frag missile
before impact splts into 10 bombs (1000 damage each)
cost: 150 plastanium, 50 metaglass, 500 titanium, 200 lead, 200 copper, 150 silicon.

nuclear missile
radiates the ground for 15 seconds (20 tile range) deals 15000 damage
cost: 150 blast compund, 100 uranium, 500 titanium, 200 lead, 200 copper, 150 silicon.

powerful nuclear bomb
radiates the ground for 60 seconds (35 tile range) deals 30000 damage 
cost: 250 blast compund, 50 plutonium, 800 titanium, 200 lead, 200 copper, 150 silicon.

freeze missile
freezes units for 10 seconds stopping them instantly (5000 damage)
cost: 50 blast compund, 3 large tanks of cryofluid, 500 titanium, 300 lead, 300 copper, 200 silicon.

Plutonium force projector
power: -2000/s
water: required
cryofluid: 50% boost
1.5x range of a force projector
3x health of a force projector
size: 4x4
cost: force projector + 1000 copper, 500 lead, 100 surge alloy, 250 metaglass, 500 plastanium, 250 silicon, 100 uranium metal, 10 plutonium
research cost: force projector + 12000 lead, 15000 copper, 5000 surge alloy, 10000 metagkass, 15000 plastanium, 15000 silicon, 1000 uranium metal, 10 plutonium

maybe a nuclear beam drill which uses nuclear explosions to mine things?

NOTE: wave cant use radioactive water, if you try... whell

GOOD LUCK :)

---T6 UNITS---

reinforcer reconstructer
power: -2000/s
input: 1500 lead, 2600 silicon, 1500 thorium, 1300 plastanium, 900 phase fabric, 1400 surge alloy, 550 uranium metal.
output: T6 units
HP:4530
cost: 3500 lead, 4500 silicon, 3000 thorium, 4300 plastanium, 1800 phase fabric, 2400 surge alloy, 1400 uranium metal.
research cost: tetrative reconstructer + 7000 plastanium, 50000 lead, 14000 phase fabric, 14000 thorium, 23000 surge alloy, 75000 silicon, 5000 uranium metal.
size: 11x11 (NO I COMPLETLY DISAGREE WITH 10x10!).

Eclipse -> Shade

Toxopid -> Rust

Reign -> Castle

Omura -> Aurora

Oct -> Agonis

Corvus -> Radian

ill let you guys decide what they do :)

Before you comment, think about it. dont assume its bad instantly. considering a new planet is coming, there might by harder challanges to complete. maybe t6 radioactive units like aa reinforced toxopid.

I dont know, its up to anuken, these are just ideas.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would be useful for the 2nd planet, and add more content to the game ,
plus current defences might not last long considering the other planit will probably spam toxopids, and in my opinion its pretty balanced.

the core is fore more cap and units,

the turrets are so you can go further in survival and survive longer in campain

and the reactors for power problems

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Cleanup-Crew-From-Discord** [comment]
i know its generally looked down upon to just say "mods lol" but a suggestion like this could only function as a mod. It would mess up too much of the game's balance and uranium isnt needed as thorium essentially serves the same function.
