### ISSUE TITLE
new beginner power generator

### ISSUE THREAD

**Issue by crazygamer2424** [Anuken/Mindustry-Suggestions#3144]
### Describe the content or mechanics you are proposing.

it is a new block to generate power.
it generate 10 power per second and 1 item lasts for 2 sec of power.
how it makes power is by burning items or letting items pass through it.
it also needs very little materials to build.
e.g. 15 copper 10 lead 5 coal/graphite.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this could help new players to get power quickly and good for early game to get basic materials like silicon.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Imanoob14** [comment]
combustion generator exists

**Comment by itcannotbe** [comment]
Here lies another suggestion that deserves a stale death and got a lease on life because someone can't keep their fingers off their keyboard by basically repeated what is already pointed out.

**Comment by begginerr** [comment]
> Here lies another suggestion that deserves a stale death and got a lease on life because someone can't keep their fingers off their keyboard by basically repeated what is already pointed out.

how about we stop commenting so this gets its deserved stale death

**Comment by itcannotbe** [comment]
You actually extended it's life another day. You fool.

**Comment by EclipseTheOldOne** [comment]
you and i actually extended another day, we're fool

**Comment by itcannotbe** [comment]
Not exactly. I commented after the last comment within the hour though.

Let's all blame noob guy

**Comment by EclipseTheOldOne** [comment]
~~yeah~~

**Comment by Imanoob14** [comment]
combustion generator is much better than what you are purposing
