### ISSUE TITLE
"Better" research for hjson/json modding?

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3145]
### Describe the content or mechanics you are proposing.

currently, you can only do research: <techtree content>, *for me*, it's pretty boring
so what i want is:
multiple requirements techtree content
or maybe map requirements (complete a map to research)
hideResearch (hide the techtree research until meet the requirements)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

making tech tree research less boring?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Cleanup-Crew-From-Discord** [comment]
i believe this can be done with scripts which you could probably reverse engineer if you didn't know how they work, but I definitely would like the multiple requirements / map requirement to be in Hjson. maybe something like
```
research: {
  research: [
    something
    something
  ]
  capture: [
    base1
    base2
  ]
}
```

**Comment by EclipseTheOldOne** [comment]
ah yes, i meant that

**Comment by MEEPofFaith** [comment]
check exotic:tm:
