### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by Lenuto** [Anuken/Mindustry-Suggestions#3148]
It would be awesome to have controller support on mobile and pc.

I've you don't have ideas, for the button bindings. I have some. Just ask me. And I can give you a layout I made.

(sry for no feature request label, it's not showing it)

**Comment by EclipseTheOldOne** [comment]
read the README.md

**Comment by Lenuto** [comment]
thats why i said, my bad. and closed it myself.
you dont need to react on closed threads.

**Comment by EclipseTheOldOne** [comment]
ah yes...my bad :)
