### ISSUE TITLE
My Suggestion Haul - Unit Editor, Betamindy, Logic, Core Fragments, and 2x2 Unit Factories

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3149]
### Describe the content or mechanics you are proposing.

So, here are my ideas for new content:

**1: Ingame Unit Editor**
This allows players to develop custom units through simple rigging, and you can use existing parts or make your own for your units. When a map's waves contain a custom unit from your custom units, the custom unit's configuration data is put into the map when saved or exported. You can also rig up weapons onto the unit and configure the weapons to your liking. Much like the unit parts, you can also get preset Weapons from existing units.

**2: Mindustry × Betamindy**
Considering how additive Betamindy is that can improve Mindustry, I think that at least a good chunk of content from Betamindy should be crossed over, such as the Anubank (plus other Anucoin blocks). Betamindy already has a lot to offer, and implementing the unique data that is Betamindy would be something that would perfect the game's loadout almost entirely. You of course want to maintain the simple structure of Mindustry, so simple features like Anucoin would be perfect for mindustry. Of course, you'll likely need permission of the mod creator, but besides that there doesn't seem to be any issues with crossing over some of the mod content to Mindustry's vanilla gameplay.

**3: New Logic Instructions**
*3.1: Javascript Execute*
A instruction that is sent directly to the game's dev console input. May also define a variable if it returns a value.
*3.2: Function Define & Recall*
This instruction allows you to define OR recall a function. When a function instruction is defining a function, a adjustable arrow will appear, much like the arrow that the Jump instruction has, and where ever the arrow lands is the last instruction of the function before returning to a recall function instruction. Unlike jump instructions, the arrow cannot bend backwards, and the arrow lines from defining functions are tinted orange. Recalling function instructions don't have an arrow, and instead sets the instruction counter to a function that was previously defined and returns to the instruction right after the function, but if no function exists, the instruction is skipped.

**4: Placeable Core Fragments**
It's about time we start being able to make cores on our own accord. This enables players to make core seeds that also includes a lower grade core unit, item capacity, and unit capacity. By default, core fragments can only be placed within your core's No-Build Radius, and core fragments emit 50% No-Build Radius than normal, and doesn't take effect when polygonal No-Build Radius is enabled, but this limitation can be disabled in the map settings. Core fragments even when upgraded can be deconstructed, but it requires five or all players to deconstruct the core completely. Deconstructing core fragments is allowed by default, and a countdown during deconstructing an upgraded core fragment can be enabled and how long it goes for can also be configured, and is set to 3 by default.

**5: 2x2 Unit Factories**
Now, this may seem a bit dumb to ask for something that was removed before, but it's for nostalgia, and can be used as a cheap alternative to actual unit factories, as these 2x2 factories can use two types of materials for custom attributes and functionality. Basically, it shares the same unit for every configuration, but it can be constructed with any materials, and as long as the factories are powered, they can construct. Previously, the unit cap of the units were relative to how many unit factories there are. These basic units will be cap at twice the normal Unit Cap. Here are some of the modifiers with their respective materials *(Also, a missed detail; There will be multiple factory grades which increases the material type and material capacity):*

Copper: Crumbly
Lead: Sturdy
Titanium: Airtight (Allows unit to walk in water without decaying)
Thorium: Tough, Heavy (Slower)
Coal: Combustive (Explodes into flames when killed)
Silicon: Flying
Phase Fabric: Deflective, Booster (Buffs all modifiers in unit by x2.25)
Plastanium: Mender (Heals nearby units), Builder (Allows unit to build and deconstruct with 50% build speed)
Surge Alloy: Arc Bullets, Electrical Plating (Basically Surge Wall properties)
Pyratite: Pyrotechnic (Burns anything it hits)
Blast Compound: Kamikaze (Deals 200% damage when unit falls from death, explodes violently when killed if grounded)

These 2x2 unit factories have three grades as well:

**Basic**
- Max Material Types: 2
- Material Cap: 60
- Material Requirement: 30
- Production Speed: 140%

**Advanced**
- Max Material Types: 3
- Material Cap: 110
- Material Requirement: 55
- Production Speed: 100%

**Master**
- Max Material Types: 4
- Material Cap: 240
- Material Requirement: 120
- Production Speed: 60%

That is all.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1: This content would be for making special guardians and enemies, since having to see guardians that look the same as vanilla would be boring, and in general having custom units for waves would bring in some spice to the gameplay.

2: This is mostly just a want, but Betamindy has a lot of features Mindustry is for sure lacking, so adding some features from Betamindy to Mindustry would be great.

3: Having some more leeway for logic would do really good, makes creating functions easier, and calling them back easier too. JS Exec Instructions are mostly going to be used in Singleplayer/Player Hosted Servers (if allowed), and allows full customization over the base content of the game.

4: Core Fragments are also a pretty good addition, but of course with every benefit you need something to make it not OP. Core Fragments likely will be used for teleporting materials, so if needed, you could configure it and its upgrades to be a seperate but contributive core for the item count, and if that core is destroyed, all the items in that core is gone forever. Core Fragments would help in making games a tad easier, and make it more interesting, but any maps not made the the day after Core Fragments are added, *will* have Core Fragments banned by default to prevent unintended gameplay.

5: Reason I request this is because it's not only for nastolgia purposes, but it enables you to create your own unit whilst still staying on the base structure of one unit. You could make a Strong Kamikaze, or a Flying Burner, or a Crumbly Mender, the sky's the limit with how many combinations you can form. This is especially useful in terms of early game PVP, as your units would be extremely flexible for your needs.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Sector171** [comment]
Tbh, i don't see any place to it in Vanilla at all.
It is a stand alone game literally, and could be even better than Vanilla if well designed. Actually he should delete all T1-->T5 factories in his mod, no need for them in this mod. Each item give one or more features including ability to mine and what to mine, the strongness of these features will increase with rarity(surge-phase) and with hardness of production(blast-plastanium).

**Comment by IxGamerXL** [comment]
> Tbh, i don't see any place to it in Vanilla at all. It is a stand alone game literally, and could be even better than Vanilla if well designed. Actually he should delete all T1-->T5 factories in his mod, no need for them in this mod. Each item give one or more features including ability to mine and what to mine, the strongness of these features will increase with rarity(surge-phase) and with hardness of production(blast-plastanium).

Removing the vanilla unit factories would actually encourage the use of these new unit production blocks. I don't know if I can outright delete the unit factories so I'll just change their BuildVisibility to hidden so that maps that contain these factories are guaranteed to still be safe to play on.
