### ISSUE TITLE
Invincibility frames for Scorch and other things.

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#315]
Invincibility frames: as in the name, the unit becomes invincible for a short amount of time after getting hit.

If we implement this, nothing would get mass damage from anything (Turrets (especially scorch) or so many units or i guess one Titan unit since its attacks are like scorch) this way scorch wouldnt be op but may need a buff.

By the way scorch's actual damage is its damage multiplied by FPS so higher fps = more damage

**Comment by Anuken** [comment]
This isn't necessary. Scorches were overpowered because their projectiles could pierce any unit an infinite amount of times; this no longer happens.
