### ISSUE TITLE
The Logic Miss-Commiting Crisis and my Solution

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3150]
### Describe what you would like changed, and why.

What I want to change: The way how logic processors have changes commited.

Reason: Picture this scenario: you're checking out another person's processor logic, and once you finished checking it out, you end up accidentally undoing their hard work as you exit the logic menu because whilst you were checking it out, they finished editing the logic and you exited which caused it to revert back.

Basically, The reason why is because it helps people not accidentally undo hard work, and helps with forgoing logic that doesn't lead anywhere useful for you.

### Describe the changes you want to propose. Include possible alternatives.

Here are the changes that'll likely work (not all of these changes have to be added):

1. Add a commit button to the logic menu, and make the back button discard your changes.
2. Add a Lock button to the processor (visible to the person who built it) that makes the processor read-only and prevents links from being removed or added.
3. Processors you place will have a Commit board. Each time a player commits a change, it will send that to the board for that processor. Only the person who built the processor can accept and deny these commits. The processor owner may make the processor public to any edits if they wish.

**Comment by buthed010203** [comment]
I propose another solution, if the player hasnt changed anything in a block then "changes" shouldnt be applied at all. This fixes the problem of someone overwriting changes when trying to look at blocks without any new ui. This would work best if implemented alongside solution 1. Another solution would be to somehow warn a user that the logic block has been updated while they are viewing it with options to overwrite, copy to clipboard or discard your changes.
