### ISSUE TITLE
Change how solar system renders

### ISSUE THREAD

**Issue by Jarglo33** [Anuken/Mindustry-Suggestions#3151]
### Describe what you would like changed, and why.

change the planet renderer to show enter solar system based on what planet is selected. for example, selecting a modded planet called Kepler-186C  would show the entire system with a red star but Serpulo is not rendered.

### Describe the changes you want to propose. Include possible alternatives.

Change  "public final Vec3 camPos = new Vec3();" in PlanetRender.java to "public Planet solarSystem = Planets.sun;" and add "solarSystem = planet.solarSystem;" . I tested it using custom builds.

**Comment by Cleanup-Crew-From-Discord** [comment]
if you have the code for this figured out id suggest making a PR instead

**Comment by Jarglo33** [comment]
where do I put PRs after one is completed?
