### ISSUE TITLE
In-game reset campaign levels

### ISSUE THREAD

**Issue by cannonball95** [Anuken/Mindustry-Suggestions#3152]
### Describe the content or mechanics you are proposing.

I'm aware this can be done by deleting the level data, but could be streamlined as an in-game feature. Simply adding a button on the UI when you have selected the level but not entered yet to "reset level map?" would do.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While I understand this may be seen as a change in game balance and design (plus I'm a noob at this), I think it would be a good **anti frustration feature**. After a game over and coming back for a new attempt, the scraps can make the new building process cluttered and confusing, and cleaning up wastes some valuable preparation time. Plus, **in levels where you get a starting base**, it prevents from adding a new layer of difficulty after failing the first try.
If we count the option to delete level data files, it's still more **user friendly** to add a button on the level selection interface, specially on mobile devices.

Edit: @IxGamerXL states this would add **replayability**, allowing to replay a single level without resetting all progress. https://github.com/Anuken/Mindustry-Suggestions/issues/3152#issuecomment-958170959

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I think it is an intended mechanic for scraps of your old base to still be lying around.

**Comment by Kyllingene** [comment]
It is indeed intended; it also applies the same destruction algorithm applied to enemy bases when you destroy *their* core.

**Comment by cannonball95** [comment]
I see. I considered it could be intentional, but didn't see it adressed as such, only people asking how to do it on the discord server, so I felt like posting the suggestion. Feedback could make Anuke change his mind but I know it's up to him in the end.

**Comment by OnyxFinger** [comment]
> I think it is an intended mechanic for scraps of your old base to still be lying around.
> 
> Because it is far more easier to just regenerate the map you know.

yes. But he is saying that it is really annoying.

**Comment by Cleanup-Crew-From-Discord** [comment]
its much better if you come back to somewhere like Nuclear Production Complex, which you WILL lose a lot, and be able to just release some polies to fix your base. Plus, the remnants of your defenses can fight off the first few waves. In addition, have you tried storing polies on maps you know you will lose? you can make a loop of payload conveyors and on V7 you can land the polies there, trapping them in a loop. If you place them far from core, when you come back they will still be waiting in the conveyors so you can break one to let them free and begin rebuilding. Keeping the old base's remains around is quite a useful feature and idk why you would ever want to start from scratch on what is likely a difficult level.

**Comment by cannonball95** [comment]
I don't disagree, I like it when I have a couple polys around to fix the mess and several times I prefer it, but sometimes I feel like the overall base wasn't going in the right direction and it's better to start from scratch with a new approach instead of recovering it. But I see the point that there's also a loss in resources.

**Comment by IxGamerXL** [comment]
I actually support this issue for one reason: **Replayability**

As someone who loves games with an endless aspect, this issue would be _very_ helpful with the endless aspect. You'd be able to replay areas without needing to revert to a previous backup or delete your campaign progress entirely.

It basically revives the V5 Campaign attribute of replaying sectors whenever you like.

**Comment by cannonball95** [comment]
Good point, I'll add it to the request

**Comment by itcannotbe** [comment]
Replayability doesn't make sense since you have a lot of sectors to actually play on and captured sectors actually serve a purpose.

Passive item income and the other mechanic which is chance invasion of sectors that are bordering uncaptured sectors, especially ones that are close to an enemy base.

**Comment by IxGamerXL** [comment]
> Replayability doesn't make sense since you have a lot of sectors to actually play on and captured sectors actually serve a purpose.
> 
> Passive item income and the other mechanic which is chance invasion of sectors that are bordering uncaptured sectors, especially ones that are close to an enemy base.

What do I do then when I capture every sector? Just build efficent machinery and eventually get bored because there's no more action?

There is a _finite_ number of sectors you can capture. Once all sectors are captured, all factors of your sectors getting attacked becomes nullified as you sit there with no more things to do besides utilize your other sectors for materials and obtain research, and even that becomes irrelevant once you've 100% finished your research tree (but this of course can be fixed by game updates adding new content).

Sorry, but the point still stands. Being able to delete individual sector data (or how I like to say: _Derelictify them_) as an in-game feature would still provide sufficient replayability unlike any existing feature we have right now.
