### ISSUE TITLE
Search in file choose popups

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry-Suggestions#3153]
### Describe the content or mechanics you are proposing.

It gets annoying having to manually scroll down for that one file that you keep missing, and wouldnt be too hard to implement, i think.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Quality of life

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by bendnuts** [comment]
i wonder when this is going to get closed

**Comment by Kyllingene** [comment]
If nobody comments, then 20 days.
