### ISSUE TITLE
Bound units will not shoot if the target is not inside their range

### ISSUE THREAD

**Issue by Waffle3z** [Anuken/Mindustry-Suggestions#3156]
### Describe what you would like changed, and why.

ucontrol target x y true 0 0 fails to make the bound unit shoot when x, y is outside the unit's radius. The shooting argument is true, so the unit should shoot. Player-controlled units are able to shoot if you're aiming outside your radius, bound units can't.

### Describe the changes you want to propose. Include possible alternatives.

ucontrol target x y true 0 0 should make the unit shoot in the direction of x, y even when x, y isn't inside their range. Player ships do it, controlled units do it, bound units should do it too.

It's technically possible to take the vector from the unit to the coordinate and normalize it and project it onto the perimeter of the unit's radius, but that's a dozen extra instructions that will massively slow down something that should be achieved by a single instruction.

**Comment by IxGamerXL** [comment]
Don't forget Turrets too. They try to shoot at a unit even if the unit is out of their range if you perma bind the turret's target to one unit.

I agree that this should be fixed. Often times when my special commander schem's logic is making the units fire at a target, the units only attack when in range, which makes it really difficult to use the schematic.
