### ISSUE TITLE
In-game Planet Editor

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3157]
### Describe the content or mechanics you are proposing.

This is a kind of feature that actually opens up to something I like to call: Custom Campaign.

The ingame Planet Editor will allow you to specify the planet's mass (size), the quantity in sectors (Past a certain amount will have a large planet warn prompt upon importing), and each sector's type.

Research requirement: _Captured Sector x_ is ignored in Custom Campaign.

### Sector Types:

- Start (Where the player starts at)
- Normal (Basic sector with limited waves)
- Base (Attack mode sectors with infinite waves)

### Planet Settings:

- Name (string)
- Creator (string)
- Sector Count (int)
- Mass (float)
- Structure (table incasing structural generation settings)
- All Research Starts Unlocked (bool)
- Win Criteria (table: SectorsCaptured (int), BasesDestroyed (int))
- Unlocked after planets (tuple: Planet) (Leave blank for this planet to be accessible at the start, other planets can be kept in this tuple even if said planets are non-existent)

### Sector Settings:

- Name (string)
- Description (string) (optional)
- Unlocked after (tuple: Sector) (Leave blank to be accessible from the start. Starting sector has this setting always blank)
- Type (Start, Normal, Base)
- Map Type (Generated, Custom)
- Map (map) (Disabled if map type is Generated)
- Generation (table incasing map generation settings) (Disabled if map type is Custom)
- Wave Count (int) (Disabled in Base sectors)
- Threat Level
- Unlocked after research (tuple: Research) (Optional)

When you setup a new Custom Campaign, you can select any planets you made or imported for your custom campaign. When you add planets without their accendants, the game will warn you about it. Proceeding without the accendants will make the requiring planets become their own root during the session to compensate. 

During Custom Campaign setup: You may also link planets into other planets to make a specific order of how you want the planets to be beaten. You have the ability to make your Custom Campaign either linear or an explorable spacescape. Your campaign, your rules.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Adding an ingame Planet Editor and Custom Campaign gamemode would allow players to create a unique environment, thus creating a unique experience. One could make our Earth's solar system where Earth is automatically captured, but you must unveil the secrets of nearby planets and further. Another could make an entire space station that extends all over the planet and you'd have to infiltrate the space station to get top secret files from the base. People can even create Challenge Planets, a larger scale version of challenge maps.

These additions are the kind of additions that veterans will likely love, and especially those who want to make their own campaigns.

(Side note: Despite checking the trello, I still don't know if "Full In-game Editor" includes this kind of editor or not. You can say that it is or not, but besides that I think we can look at other spectrums besides that. Who knows, anuke might have not previously considered specifically what I said about the Custom Campaign or Planet Editor into development despite that.)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MissAmity** [comment]
h

**Comment by oinkymoo** [comment]
while I agree that this would be really cool, this won't be added to the base game. any sort of modding tools will be at best an external unofficial software

**Comment by Cleanup-Crew-From-Discord** [comment]
I believe this is already a thing possible through mods but there is no in-game editor. i agree with oinkymoo that this would likely be best off as an external unofficial program

**Comment by OnyxFinger** [comment]
I like this idea, but it sounds like a lot of work, while you can somewhat (with a slight lack of accuracy) roleplay it.

**Comment by numer99** [comment]
That would take A LOT of work for Anuken to do while he's still making the campaign planets and other features

I would really like this if it was a mod or a sandbox planet mode or something

**Comment by IxGamerXL** [comment]
> That would take A LOT of work for Anuken to do while he's still making the campaign planets and other features
> 
> I would really like this if it was a mod or a sandbox planet mode or something

Now that you mention it, a sandbox planet mode (with multiple saves) would be fun. You could probably have it where you can choose how many sectors exist in the planet, and then when going into a new sector you can decide if you want a randomly generated one or a custom map. Nothing too complex, really. You could also preload sectors, and if you determined a sector to be an enemy base, it can start reigning your world (if you allow it to). You can delete sector data at will, and since it's a sandbox planet, all research is by default unlocked for the planet.

For those who really like to have a world of their own. Kinda almost sounds like minecraft, except it's a top-down view game and it's more engineered into managing production and defense.


Making a mod that could do this would be fairly difficult, since it would require an advanced GUI, world file saving (and deleting) and would require saved games for planets. If someone can do all of the following, then they likely have what it takes to make this addition.
