### ISSUE TITLE
ulocate should be able to detect any type of structure

### ISSUE THREAD

**Issue by Waffle3z** [Anuken/Mindustry-Suggestions#3158]
### Describe the content or mechanics you are proposing.

ulocate is only able to detect structures in a specific group, and that group can only be one of core, storage, generator, turret, factory, repair, rally, battery, resupply or reactor. This means units are unable to see conveyors, power nodes, walls, anything else that isn't in that list, or any more than one of those things at a time.

ulocate should be able to detect any and all types of structures.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Bound units are currently limited in that they cannot see all structure types in their range. Technically getblock can be used to poll one coordinate at a time, but there are thousands of coordinate points to check in a unit's range that this is impractical to use for this purpose. If any structure type can be detected then it will be possible to guide where units go and also have them target any structure type.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Anuke has previously said that this would be technically very challenging to do. (Also, check trello before suggesting)

**Comment by Waffle3z** [comment]
> Anuke has previously said that this would be technically very challenging to do. (Also, check trello before suggesting)

I saw a task in trello about radar detecting buildings, but ulocate already can detect buildings, just not all of them, or more than one type at a time.

**Comment by end-me-please** [comment]
also, see previous suggestions:

#974
#1242
#1641

just to name a few
