### ISSUE TITLE
Add Split Sceen View Support

### ISSUE THREAD

**Issue by TheDemonKingRaz1** [Anuken/Mindustry-Suggestions#3159]
### Describe the content or mechanics you are proposing.

On Android, apps & games can use split sceen to muilt-tasks, but while testing I found that Mindustry cant do it.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Could help player get griefer reported faster when the game minimize to open Discord, help others work on their design, and ect.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by USMP-lancer** [comment]
android phones are super cheap, like actually stupid amounts of cheap

**Comment by Kyllingene** [comment]
Resizing the Mindustry window on mobile would render the game unplayable due to the already cramped UI.

**Comment by TheDemonKingRaz1** [comment]
On some devices, like table and Z Fold that isn't a problem because in split sceen it would be the same as a regular phone screen, and you can adjust the game to more screen veiw space then other apps. Ill add an example 
![Screenshot_20211103-215503_Samsung Notes](https://user-images.githubusercontent.com/68443385/140250555-1020e6dd-ef1b-46a8-9eb4-a909a744139f.jpg)

**Comment by USMP-lancer** [comment]
the only reason this is not a thing, as mindustry is not able to be resized on android

**Comment by itcannotbe** [comment]
Actually Mindustry on Android doesn't support running in the background.
