### ISSUE TITLE
highest tier naval unit should be a carrier

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#316]
**Describe what you would like changed, and why.**
Not exactly changed, but the final/boss tier naval unit should, rather than have a turret, spawn wraith fighters. It just makes sense, the most expensive ships in the world today are military aircraft carriers, and a unit that spawns smaller ones instead of shooting would make gameplay more interesting.

**Describe the changes you want to propose. Include possible alternatives.**
The final tier naval unit should include a few construction bays on it that look similar to those that spawn wraith fighters. ideally it may chug out one wraith every two seconds.
One alternative is the predecessor to the final one spawns wraiths, but the final one spawns revenants (at a slightly slower pace) instead.
Maybe the carrier units would have turrets, if they're not strong enough. But this, in my opinion, is the only way a naval unit could be a real threat to a base that's not on the shoreline.

**Comment by stuffyAI** [comment]
The carrier should have a spawncap so you can't abuse them, also they should spawn with their full escort.
Evidentely, I suggest the spawnlings to escort the carrier and attack within a certain radius until the carrier reached the shoreline, after wich the spawnlings are free.

**Comment by sup3r87** [comment]
> You can probably also add feature request since you want a new mechanic.
true, will prolly do that
> The carrier should have a spawncap so you can't abuse them, also they should spawn with their full escort.
> Evidentely, I suggest the spawnlings to escort the carrier and attack within a certain radius until the carrier reached the shoreline, after wich the spawnlings are free.
i agree with those points, i was just thinking about attack maps and not a situation where you could put the unit into water and construct a revcloud that never ends.

**Comment by sup3r87** [comment]
just realised - i am unable to change the label myself.

**Comment by LJMSU** [comment]
good suggestion, this can really improve the gameplay.

**Comment by Violet-Scarelli** [comment]
Instead of making units that can be manufactured by the player, perhaps a couple of unique, smaller units that require you to have the carrier in order to use them?

**Comment by LJMSU** [comment]
> Instead of making units that can be manufactured by the player, perhaps a couple of unique, smaller units that require you to have the carrier in order to use them?

Wouldn't that requires Anuke to make another unit type?
