### ISSUE TITLE
Nerf atrax and buff mace

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3160]
### Describe what you would like changed, and why.

Compared to mace, atrax has a way higher range, has more health, inflicts and is immune to melting, is considerably faster, and can go over blocks
Meanwhile, mace has the problem of never actually getting to the enemy defenses - way too slow, the range is too small, and is not tanky enough, which is very bad, since past t2 the importance of range already becomes extremely high - even if mace actually gets to the enemy defenses, it often just gets instantly incinerated by close-range turrets

### Describe the changes you want to propose. Include possible alternatives.

Nerf atrax health and maybe range/speed
Buff mace (in order of most important to least important) range, health, and speed

**Comment by EclipseTheOldOne** [comment]
~~Eputor and TItans~~

**Comment by OnyxFinger** [comment]
ATRAX DOESN'T NEED A NERF AAAAHH
just because atrax is stronger than mace doesn't mean it's too powerful.

**Comment by Somka000** [comment]
Desktopone hate maces

**Comment by BlueWolf3682** [comment]
This would make mace even more painful to deal with earlygame - we don't need another crawler caused by PvP balancing.

**Comment by Ilya246** [comment]
Mace is too weak earlygame too, unlike atrax - also, speaking of crawler, yeah it may need a damage(/speed?) nerf

**Comment by OnyxFinger** [comment]
> This would make mace even more painful to deal with earlygame - we don't need another crawler caused by PvP balancing.

whaaahh-- so you seriously think that this would be a problem ?
The only two sectors that would need a bare nerf would be Stained Mounatins and Frozen Forest
As for custom maps, I do not think that this change would affect their difficulty by much.

**Comment by MEEPofFaith** [comment]
yes range short
![image](https://user-images.githubusercontent.com/54301439/140393786-ba292881-52db-4f40-bf09-5a45c90b4212.png)

**Comment by OnyxFinger** [comment]
> yes range short ![image](https://user-images.githubusercontent.com/54301439/140393786-ba292881-52db-4f40-bf09-5a45c90b4212.png)

lmao I didn't know

**Comment by IxGamerXL** [comment]
Since I know quite a bit of Javascript, I'll try to make a mod that adds these balance changes as much as I know I can. I'll comment again with the mod rep when I have it ready.

**Comment by the-red-soul** [comment]
atrax cannot hit air

**Comment by IxGamerXL** [comment]
After some testing: Yes, Atrax _does_ walk over defenses and deal more damage overall, and during a test I found out that Atrax does more property damage than Mace ever will. This was founded out by making a test map and spawning three sets of 100 units of the type needed.

Mace went through copper and touched titanium after 3 sets, but after a separate test with the Atraxes, DEAR JESUS CHRIST ALMIGHTY THESE WENT FAR. The atraxes went past copper AND titanium, and dented thorium, the very last stage before plastanium.

It is certainly true that Atraxes bypass defenses, and in one Attack map in particular (DDNS) Atraxes are a common enemy in the waves. One pack of them and an improper defense leads suffering and suffering only. To make it worse (as you said before), these Atraxes are immune to Melting, and guess what that map's selection of turrets are? Tsunamis and Waves.

Thats right, the map only allowed four ammo variants, the four liquids.


Anyways, enough of my partially-irrelevant rant. The mod I suggested before is not doable without some confusing work arounds, so leave that to Anuke to handle the balances. Also, Mace got buffed in V7 BE, so your balance issue is already partially finished.

**Comment by notrealn** [comment]
Just changing health and damage will not fix the fundamental problem with mace *and* atrax. They will still be used much less compared to air units or the nova tree in pvp. The problem with them is horrible mobility and range (even 8 tiles is not enough). Horizons are infinitely more useful because they can actually go to their target in a decent amount of time. Additionally, mace/atrax are both hilariously counterable with very cheap turrets. A few hails make both of them relatively useless. Unless they get some insane hp and damage buffs, other units will generally be preferred. 

However, this is only for 1v1 pvp. Campaign/attack are very different, and having maces and atraxes be that strong would be too difficult to deal with. You encounter maces when you barely have any graphite, meaning maces must be able to be beaten with copper walls and duos. There is really no easy solution that involves only changing a few numbers.

**Comment by acoaco** [comment]
atrax>mace no matter in v6 or v7 and no matter pvp or survive(pve) mode,both can cause fire
600HP>540HP, moving speed 4.27>3.37 and can cross wall and building,range 13>6
armor okay..mace win 1 but HP lost so it's can't called advantage
mace has pierce but range is 6 and slower moving speed when mace pierce/touch building atrax already walk stand on core
or they both got killed lol

the only reason why this happened is ground unit is out of meta in most server,only work in assimilation(no logic no unit control),but still need attack range so people spawn dagger,and it's obvious anuken know it that why when he design a similar short range unit in v6 he give atrax better ability,but poor mace got forgotten

fortress already got buff in v7 it's a okay unit now,but mace..at least give him faster moving speed 4.5 and fair 600HP
