### ISSUE TITLE
New information for Core Database: weather and shield hp

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry-Suggestions#3163]
### Describe the content or mechanics you are proposing.

Current Core DB includes status effects, but it would be helpful (especially for new players) where those effects come from. Weather description can be simplified to: which status does it give to units and which buildings does it have effect on.
Second thing I find missing is unit force field strenght. Force projector has information about that, but units simply lack this description.
Third thing, the least important, is ammount of shield units like pulsar can generate.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New data can be helpful in improving effectiveness of some contraptions and combat (rain can increase shock damage). (Does spore rain makes units more flammable?)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Cleanup-Crew-From-Discord** [comment]
I second this. Digging through the source code to find exactly how much sandstorm affected water extractor (-10%) wasn't a great way to have to find this info.

**Comment by oinkymoo** [comment]
wait sandstorms affect watex

**Comment by OnyxFinger** [comment]
> wait sandstorms affect watex

I didn't know either lol

**Comment by begginerr** [comment]
> > wait sandstorms affect watex
> 
> I didn't know either lol

me neither xd

**Comment by Kubek0212** [comment]
> > > wait sandstorms affect watex
> > 
> > 
> > I didn't know either lol
> 
> me neither xd
Me neither, but since we don't have anything more interesting to add, I'm closing this thread
