### ISSUE TITLE
Co-host option in local multiplayer games

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3164]
### Describe the content or mechanics you are proposing.

This would be a button that turns any players you want into co-hosts (represented as a server icon next to the admin button in the player list)

Co-hosts can influence the game's behaviors along side the Host, which means they can use the dev console and spawn things in and have them appear in other clients.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It allows multiple players to use utility mods like Testing Utilities and Unit Factory without any hassle. It's useful for many things that often would otherwise desync the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
skill issue

**Comment by buthed010203** [comment]
~~This is literally what headless servers exist for~~

**Comment by begginerr** [comment]
> ~This is literally what headless servers exist for~

never heard of them

**Comment by Kyllingene** [comment]
What on earth do you mean by local multiplayer? Do you mean LAN? In that case, then buthed010203 probably meant dedicated servers, command-line applications that host a (mostly) fully-featured server (though you have to handle port-forwarding, but that's not an issue on LAN). There is a wiki page on them [here](https://mindustrygame.github.io/wiki/servers/).

**Comment by IxGamerXL** [comment]
> What on earth do you mean by local multiplayer? Do you mean LAN? In that case, then buthed010203 probably meant dedicated servers, command-line applications that host a (mostly) fully-featured server (though you have to handle port-forwarding, but that's not an issue on LAN). There is a wiki page on them [here](https://mindustrygame.github.io/wiki/servers/).

Yeah I meant LAN. I also would like Co-hosts to be a thing for the Steam (PC) version if it's possible.

**Comment by itcannotbe** [comment]
> It allows multiple players to use utility mods like Testing Utilities and Unit Factory without any hassle. It's useful for many things that often would otherwise desync the game.

It won't.

**Comment by buthed010203** [comment]
Yes, headless means without a GUI or more specifically the actual server jar

**Comment by Anuken** [comment]
> It allows multiple players to use utility mods like Testing Utilities and Unit Factory without any hassle.
> dev console

Mindustry doesn't *have* an interactive dev console - "I can install a mod to use it" doesn't count. You're asking for features to be added **to third-party mods**, which have nothing to do with the base game - I am quite literally unable to do anything about this.

**Comment by MEEPofFaith** [comment]
> > It allows multiple players to use utility mods like Testing Utilities and Unit Factory without any hassle.
> > dev console
> 
> Mindustry doesn't _have_ an interactive dev console - "I can install a mod to use it" doesn't count. You're asking for features to be added **to third-party mods**, which have nothing to do with the base game - I am quite literally unable to do anything about this.

~~Testing Utilities works on servers by sending a `/js` message through `Call.sendMessage()`, and is entirely based on whether you have the perms to use `/js`.~~
