### ISSUE TITLE
Reign Needs Buffs

### ISSUE THREAD

**Issue by Imanoob14** [Anuken/Mindustry-Suggestions#3165]
### Describe what you would like changed, and why.

Reign needs buffs.
He needs to get STRONGER!!!

### Describe the changes you want to propose. Include possible alternatives.

*Make it so that he can cross over any friendly buildings. when i mean any, i mean ALL! including interplanetary accelerator!!!! and terrative reconstructor!!!! 
*Additionally, make it so that he can cross over up to 2x2 non-friendly buildings. 
*His bullets does high enough damage for a t5, but make his attacks 4 or 5 shots per second
Make some minor nerfs to compensate
*For example, make it so that his bullets get reflected by large phase walls
Seriously, reign is a super tough unit, but he falls behind other t5 units
*The tier-5 units each must have equal amount of power
I dont think you are going to accept my requests, since they might be asking for too much, but atleast buff reign a little

**Comment by itcannotbe** [comment]
The user name says it all.

**Comment by Imanoob14** [comment]
i just dunno man

**Comment by EclipseTheOldOne** [comment]
Describe what you would like changed, and why.
not
Describe what you would like changed

**Comment by itcannotbe** [comment]
> The tier-5 units each must have equal amount of power

### Oct:

![awkward_monkey_puuppet_meme](https://tenor.com/bcegt.gif)

**Comment by itcannotbe** [comment]
> The tier-5 units each must have equal amount of power

### Oct:

![awkward_monkey_puppet_meme](https://c.tenor.com/gaEpIfzxzPEAAAAC/pedro-monkey-puppet.gif)

**Comment by Imanoob14** [comment]
i dont know

**Comment by Imanoob14** [comment]
.

**Comment by Imanoob14** [comment]
am i doing this just because i fell sympathy for reign when i gets dominated by toxopid and i insulted him too?
probably

**Comment by Cleanup-Crew-From-Discord** [comment]
please tell me this is satire

**Comment by Imanoob14** [comment]
maybe

**Comment by OnyxFinger** [comment]
> > > The tier-5 units each must have equal amount of power
> > 
> > 
> > ### Oct:
> > ![awkward_monkey_puppet_meme](https://camo.githubusercontent.com/f0a274d6a9fbbffbd6e314fe831ffd998796c23445a2a286c353363675613c32/68747470733a2f2f632e74656e6f722e636f6d2f6761457049667a787a504541414141432f706564726f2d6d6f6e6b65792d7075707065742e676966)
> 
> Blast Octs and other explosive Octs

Price

**Comment by OnyxFinger** [comment]
I think that reign doesn't really need a buff :
 Eclipse is still bad duh
 Toxopid isn't that good against bases
 Corvus is good in high numbers, but other T5s are better in low numbers (compared to other units, there is a long window of time where T5s aren't in high numbers, due to their long build time)
 Omura is naval, and thus supposed to be the strongest (maybe by too much, considering how it's range overcomes the fact that it is limited to water, and the high dps shreds everything)
 Oct is good at doing support stuff for once. I don't believe that carrying explosives with oct as others are proposing a good idea, because of it's high price (I would much rather put it on something cheaper that still goes through).

**Comment by Imanoob14** [comment]
_"Eclipse is still bad duh"_
its going to get a buff in v7. from what i saw, it can tie with toxopid on a 1v1. this might be fake news but like, what are the chances of that?

**Comment by EclipseTheOldOne** [comment]
> _"Eclipse is still bad duh"_ its going to get a buff in v7. from what i saw, it can tie with toxopid on a 1v1. this might be fake news but like, what are the chances of that?

yeah, unit gain opportunity based on factors

**Comment by MEEPofFaith** [comment]
> > The tier-5 units each must have equal amount of power
> 
> ### Oct:
> ![awkward_monkey_puppet_meme](https://camo.githubusercontent.com/f0a274d6a9fbbffbd6e314fe831ffd998796c23445a2a286c353363675613c32/68747470733a2f2f632e74656e6f722e636f6d2f6761457049667a787a504541414141432f706564726f2d6d6f6e6b65792d7075707065742e676966)

~~Now increase oct's payload capacity so it can fly in and drop 17 toxopids on your core.~~

**Comment by OnyxFinger** [comment]
> _"Eclipse is still bad duh"_ its going to get a buff in v7. from what i saw, it can tie with toxopid on a 1v1. this might be fake news but like, what are the chances of that?

oh wow it "will"
from what I know, it got buffed a bit, but it wasn't enough, and got a new AI, which is kind of stupid, then uh.. idk if it got buffed more, but right now, I'm pretty much sure that's currently bad
