### ISSUE TITLE
Modding block category sorting

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3167]
### Describe the content or mechanics you are proposing.

currently, modding blocks will be show in categories after all vanilla blocks
it seem a bit off when like i added a 4x4 tank but it showed up after tank and lots of other stuffs
so i wanted to making the category sorting blocks by type
ex:
(distribution: conveyor -> titanium conveyor -> (modded one that faster then tita conv) -> (modded stack conveyor that weaker than plast conv) -> plastanium conveyor (stack conveyor))

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make mindustry block content sorting make more sense, i guess
also this should be an option of normal sorting and modified sorting

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
How do you suggest this is implemented? How would multiple modded items of the same caliber be sorted relative to each other? How would you tell what type each item is - would it be a required field for modded and vanilla items?

**Comment by MEEPofFaith** [comment]
The order of blocks is the order in which they are loaded. There's no easy way to reorder `Vars.content.blocks()`, and doing so would mess up IDs and stuff. Even if it were implemented, it would likely break old saves.
