### ISSUE TITLE
Package for chocolatey

### ISSUE THREAD

**Issue by xeruf** [Anuken/Mindustry-Suggestions#3168]
### Describe the content or mechanics you are proposing.

https://community.chocolatey.org makes installing software on Windows a lot less painful :)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make installing easier

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
I'm sorry, but how does this relate to mindustry?

**Comment by esteemator** [comment]
The suggestion is to create (and keep up to date) a package for this windows package manager?
Nice for those who use this thing...
Then again, why not push it to the ms store directly? ;-)

**Comment by itcannotbe** [comment]
When you realize that the itch.io app already supports auto updating the game.

**Comment by xeruf** [comment]
> The suggestion is to create (and keep up to date) a package for this windows package manager? Nice for those who use this thing... Then again, why not push it to the ms store directly? ;-)

The nice thing about chocolatey is that you can batch install packages from the commandline, highly time-saving when setting up a new machine

**Comment by itcannotbe** [comment]
> > The suggestion is to create (and keep up to date) a package for this windows package manager? Nice for those who use this thing... Then again, why not push it to the ms store directly? ;-)
> 
> The nice thing about chocolatey is that you can batch install packages from the commandline, highly time-saving when setting up a new machine

And that info adds to your point by... how exactly?

**Comment by notrealn** [comment]
Hes saying that it is more convenient. It is already in the aur, except I think that is being maintained by some random person. Not sure if you can do the same with chocolatey.

**Comment by xeruf** [comment]
You can indeed, Choco is quite similar to the AUR if you look at it like that, except that there seems to be some vetting of the packages.

**Comment by xeruf** [comment]
that is quite an eager stale-bot :/

**Comment by GreenMan36** [comment]
I'd love this.
I've got a better experience with Chocolatey than the Windows store. All my programs auto update on boot, never had an error with it in my life and it makes managing my PC insanely easy.
Its the best "package manager" for Windows.

But I'm quite sure anyone can start a Chocolatey package as per the [Chocolatey Package rules](https://docs.chocolatey.org/en-us/create/create-packages#rules-to-be-observed-before-publishing-packages) since the game is licensed with GNU v3.
So you could do it yourself?
