### ISSUE TITLE
Atomic semantics for `ucontrol flag`

### ISSUE THREAD

**Issue by calmofthestorm** [Anuken/Mindustry-Suggestions#3169]
### Describe the content or mechanics you are proposing.

It would be convenient to have a way to update a unit's flag atomically, such as by taking an optional second parameter, `oldValue`. If `oldValue` is specified, the flag should be updated to `newValue` only if the unit's flag currently matches `oldValue.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow multiple logic processors to manipulate a unit's flag without data races. The use case is essentially the same as for [compare and swap](https://en.wikipedia.org/wiki/Compare-and-swap).

Specifically, two CPUs could update flag at the same time and ensure that only one of the updates goes through. Even if both of them are writing the same new value, exactly one would see its write as having succeeded.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kubek0212** [comment]
You can use *sensor* block to search for unit's flag. Then you compare it to your earlier declared `oldValue`. Then you can use *jump* to tell unit what to do, depending on flag it uses.

**Comment by calmofthestorm** [comment]
That approach can run into problems when more than one processor is interacting with the same unit. Consider this case, where two CPUs attempt to coordinate using the flag to "lock" a unit, such that only one of them uses it. (I know @controlled can handle that simple case, but it's a simple example).

Suppose each of two CPUs runs the following snippet, which checks if the flag is zero to identify a "free" unit, then "locks" it by setting the flag to 1:

```
sensor flag @unit @flag
jump <tryAnotherUnit> notEqual flag 0
ucontrol flag 1
```

One possible interleaving of two CPUs is as follows:

```
cpu1: sensor flag @unit @flag
cpu1: jump <tryAnotherUnit> notEqual flag 0

// cpu1 has run enough instructions for now and needs to wait to continue.

cpu2: sensor flag @unit @flag
cpu2: jump <tryAnotherUnit> notEqual flag 0
cpu2: ucontrol flag 1

// Now CPU 2 thinks it has exclusive access to the unit.

cpu1: ucontrol flag 1

// Both CPU 1 and CPU 2 now think they have exclusive access to the unit.
```

Refinements are possible, such as having cpu1 write 1 and cpu2 write 2, but these still have the problem that the flag can change between when a CPU checks it and uses it, unless we provide a way to change the flag atomically.

**Comment by Sector171** [comment]
Yeah, I remember this "fighting" between processors to control the same unit problem when I started using logic about more than year ago.
Nothing worked, checking the flag, controlled...etc.
The solution was in "Be gentleman" as I remember.
This means my logic checks the flag continuously everytime the code restarts from beginning, not only when "@unit" is null in the first time it starts, but always, to be sure that the unit flag match this processor's flag, and if not leave and free this unit and find another one to bind. This solved the problem.
Try it

**Comment by calmofthestorm** [comment]
I ended up using the flag as a lock with expiration, which is set to @tick + <some constant>, and then refreshed regularly. It doesn't actually provide mutual exclusion, but it does mean that race conditions are rare enough that as long as your logic can handle them (incinerate unknown cargo, return to known state, etc) it works. IME it's been quite stable even with many CPUs and units. I guess I'd call it "always eventual consistency":-)

I see how your design works (there is still a potential race on that first check, but it should be quite rare). The problem I'm trying to solve is allowing processors to share units, where each processor implements a PID controller that adjusts the unit count dynamically.

If test-and-set is easy to implement, it would be a sufficient synchronization primitive to permit many interesting uses of units beyond the typical "bind a group of units to a processor forever" case.

I think it could be fun, but it's not exactly "needed" -- it is a game, after all, and idk what the vision is for units exactly.

One other idea I had is to have one processor dedicated to assigning each unit a UUID, and then encode both unit id and cpu id in the flag.
