### ISSUE TITLE
nerf grass

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry-Suggestions#317]
**Describe what you would like changed, and why.**
grass is way too op

**Describe the changes you want to propose. Include possible alternatives.**
nerf grass

**Comment by jaygamer81** [comment]
I- I- Dont- I dont ev- *sighs* nevermind i guess

**Comment by Mdbgamer** [comment]
Wha...
Wh....
What?

**Comment by ILiekMelons** [comment]
yes

**Comment by Anuken** [comment]
nerfed
