### ISSUE TITLE
Zombie Attack Mode

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3171]
### Describe the content or mechanics you are proposing.

There should be a zombie attack mode. Every time at night the zombie would appear randomly if there are no enough lights.
The zombies could infect units but not turrets. The zombies will die in the daytime.
This can also be in attack mode because it can make more fun and more possibilities to the game.
Games can be turn on and off by rules. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More fun, more like survival game.
Can add zombies a possibilities to the game.

Also, I think that the units can also get infected by spores if people need them.
The virus are the spores. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
There isn't really any instance of "humanoids" and there's barely any instance of life in Mindustry.

**Comment by KayWasTaken** [comment]
can't this be a plugin on servers?

**Comment by end-me-please** [comment]
I don’t think the Game itself needs more gamemodes. Especially if they could be implemented in a few lines of code as a server plugin

**Comment by oinkymoo** [comment]
This just sounds like survival with extra steps

**Comment by begginerr** [comment]
> This just sounds like survival with extra steps

yes, also the lead description proves that there is little to no life on serpulo, so zombies dont make sense. the only thing i can think of that can work is like a computer virus that turns units rogue.

**Comment by Kyllingene** [comment]
How on earth would "survival but if you don't have enough lights your ground units can become bad" be any fun? Even if you incorporate ground units into your defense, and even if you fail to light up said defense, your turrets would be more than capable of destroying them easily.

**Comment by USMP-lancer** [comment]
i think he just means survival but bad

**Comment by USMP-lancer** [comment]
however a better idea would be the dark restricting where you can build, since it would actually change the metagame rather then, survival but dorkness spawned enemies

**Comment by Kyllingene** [comment]
If you think that would be a worthwhile issue, make it.

**Comment by notMEEPoffaith** [comment]
use bm converion turrets lol

**Comment by begginerr** [comment]
> use bm converion turrets lol

wut
