### ISSUE TITLE
Logic deconstruction

### ISSUE THREAD

**Issue by Miirpat-Gaalsien** [Anuken/Mindustry-Suggestions#3173]
### Describe the content or mechanics you are proposing.

Add a deconstruction equivalent of ucontrol build, or make uncontrol build 0 0 @ air deconstruct a building at 0 0, or another way to deconstructing from logic

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Deconstruction is the last major unit action that is not logic controllable, and since we have construction and pick-up it seems strange to me that deconstruction is not there.
It increases possibilities for automation and automatic upgrades even more.
Current usefulness of ucontrol build is being limited by the inability to deconstruct; a processor can't build over derelicts, can't replace it's own buildings, may have to use a lot of area even if the previous buildings are useless, and can't even clean up after itself.

### Griefers are the only objection I could find:

-  ucontrol build is disabled on every public server I tested it in, so those won't be affected or will quickly disable it
- The "last accessed by player" means it may not be hard to make a server distinguish between logic destroying a players or non-players buildings
- Construction griefs are about as annoying
- Deconstructing units can be seen deconstructing and will be pointing towards a processor which has a "last accessed by player" mark
- Automated griefs using block control or clogging lines with items, can be harder to notice and trace back, and may still force the player to complete deconstruction and construction of anything affected
- Despite the possibility, I only saw one griefer go as far as above

### "mention how it may add more gameplay options" 

- I started experimenting with logic construction to make a 16x16 cube/playground for logic, with storage to stockpile on resources, automatically (re)place factory buildings for resources I run low on, fuel the factories using extractors or units, make polys/megas mine the require materials directly to it's storage, and place more vaults over factories if everything is stockpiled, dump the resources into core when required, etc etc. During that I noticed that servers disable logic construction, and deconstruction doesn't even exist.
- Upgrading pneumatic drills to larger drills automatically, the exact positions of ores in an area can already be found in multiple ways if things are deconstructed first.
- Temporary wave turrets around fires
- Compact alternative to payload deconstructors for buildings by picking those up from conveyor belts
- A relatively easy method to make buildings and walls disappear on custom maps on conditions, like time passed

### "how it will fill a new niche."

Extreme automation

Grey goo wars: Making self replicating logic is easy, but if self replicating logic can target and deconstruct other logic from your team, what if you make a competition or game mode of that?

It's not possible to do otherwise
- Blast compound in generators may not be possible with megas in the team, unpdredictable, very slow, causes fires
- Nuclear is either too coarse grained or turned off
- Unit pick up and drop at a payload deconstructor is slow, expensive, and doesn't work with large buildings or logic

Anyone disagree?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
I think the main reason this is not currently allowed is because it would make griefing really easy, damaging, and swift.

**Comment by Miirpat-Gaalsien** [comment]
Unit logic construction can rotate conveyor belts, create self replicating processors, but how many people complain about that griefers using that? 

Or just place a reactor with thorium near a core, a much easier way to straight up destroy cores within, what, 40 seconds? Why haven't we removed reactor explosions?

**Comment by Kyllingene** [comment]
Ah, but you miss my point; it is easy to *quickly,* not just easily, do a lot of damage via deconstruction. You could easily destroy your defenses in a subtle (or not-so-subtle) way, dooming your team; thorium bombing your core takes, as you said, a full 40 seconds and is easily noticeable.

However, your original premise is faulty; I have seen many people complain about such things in several issues, and have had effect (less effect because again, allowing building is less dangerous than allowing direct destruction).

Your idea regarding banning griefers retroactively is just that; *retroactive*. It doesn't keep them from ruining the game, and you could easily bypass a ban with Tor or a VPN and possibly a couple modifications to the source code.

**Comment by Miirpat-Gaalsien** [comment]
I am aware of such complaints, and your comment on https://github.com/Anuken/Mindustry-Suggestions/issues/1910 
However, those complaints are from before the end of march, where a fix was released that could be applied here from the start

> Build 126.2 Released
> Disabled logic unit building for servers by default

Construction was disabled by default, why not do the same for deconstruction? make it straight up the same setting?

Banning, grief detection or prevention, things like this only become relevant if a server admin decides to enable it in a public server. Which means it would only become relevant in the future if this is a feature that people actually like.

The "retroactive" part I was writing about how integrating this feature into public multiplayer may be possible to do in the future without the majority of rounds ruined and without requiring large modifications to the game or memory usage.
However, the above scenarios can only happen once a lot of people see and play with good logic using this feature for a _while_, which only becomes possible if this feature exists, hence a first step has to be made. And while construction has been around for some time, I believe it's non-grief uses are limited by the lack of deconstruction.

While I could make detailed comparasion about the specifics of the griefing methods using logic, I think it's a bad idea to spread lots of implementation details and effectiveness of those.

**Comment by Kyllingene** [comment]
Fair enough about the setting; that slipped my mind. However, if this were to be introduced, I think it might be wise to only allow higher-level support units (possibly T3/4 and up) to deconstruct, just to make it a bit harder to grief; by the point you need deconstruction, you probably have a few extra Megas anyway.
