### ISSUE TITLE
Wipe Unused Logic Vars

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#3174]
### Describe what you would like changed, and why.

Instructions frequently have a variable number of fields that you can input into, e.g jump == having two fields while jump always has none
I suggest setting all unused fields to 0 e.g jump == x 2 to jump always 0 0
Weird undefined behaviour may happen if this isn't done
e.g `ulocate ore core false @lead ox oy of core` sets core to null whenever the line is called because there is no building on the ore, so core gets set to null even though it is unseen

### Describe the changes you want to propose. Include possible alternatives.

When done editing a processor's code, wipe unused fields
An alternative is including checks to make sure that an unseen field isn't being modified or used

**Comment by Kubek0212** [comment]
Logical and helpful

**Comment by Bottinator22** [comment]
F
