### ISSUE TITLE
Table of sector stats

### ISSUE THREAD

**Issue by dandiez** [Anuken/Mindustry-Suggestions#3175]
### Describe the content or mechanics you are proposing.

Each sector has a very useful stats button to show available resources, production, exports, etc.
The proposed feature is to have a table that has one sector per row and shows those stats in sortable columns.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The new feature will allow to see the stats of all sectors at a glance.
This allows to easily identify which sectors can be improved.
The table could also be used as a planet dashboard to help locate sectors or show additional information (like sectors being attacked, etc.)...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
That's a thing that I would love to have, if I ever play campaign again.

**Comment by oinkymoo** [comment]
should probably go in the recently added sidebar i think
