### ISSUE TITLE
Heat power.

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#3177]
### Describe the content or mechanics you are proposing.

putting slag into a thermal generator makes it work like if it was on slag.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

its simple and something i would love.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by begginerr** [comment]
would be weird but would be cool

**Comment by Kyllingene** [comment]
"I want it" is not a valid reason.

**Comment by oinkymoo** [comment]
honestly i support slag having more uses

**Comment by idontknowhwhattoputhere** [comment]
if you want another reason, you could carry scrap as a cheap power source when launching to new sectors. unlike thorium which is harder to get rtg gens are expensive and generates less energy.

**Comment by itcannotbe** [comment]
You do realize that was the mechanic before hand that was extremely broken and it had to be redone to what we have current.

**Comment by oinkymoo** [comment]
please tell me where in campaign i can find a lava pool to put my thermal generator on

**Comment by idontknowhwhattoputhere** [comment]
im pretty sure some places only have scrap (biomass synthesys faciclity), and once again im saying. its a good power source for launching. idk maybe it would have less efficiency? also it would give scrap a better use than just sitting there and being used in tsunamis... i only used it for a few schematics and when i couldnt place turrets. also as i said, there are allways problems when it comes to finding slag. considering what the 2x2 drill mines and the therman gen being a 2x2 building it would need 24/sec slag. easy power source while requiring a decent farm in larger ammounts.

**Comment by idontknowhwhattoputhere** [comment]
oh and im pretty sure ground zero has hot rocks.

**Comment by itcannotbe** [comment]
If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.

And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.

**Comment by idontknowhwhattoputhere** [comment]
1st of all, dont be rude. im not "stupid". 2nd 24/sec is a decent amount. 3rd: slag has practically no use really, its a good idea to give it a better use. i think anuken placed so much scrap because he was planning something...

**Comment by itcannotbe** [comment]
Actually. If this was an alternative to actually putting thermals on slag, not making pumping slag from lava pools, you at least need match it.

For reference. A thermal pump, pumps 13.2 slag per tile.

**Comment by idontknowhwhattoputhere** [comment]
id say that only t2 or t3 pumps can do it (due to heat shields) at a lower rate. or simply make it generate less energy. the real problem is that slag has no good use, if a thermal pump has thermal pumping using heat. than slag should boost it.
and the thermal generator idea was just an idea. generally this post is saying give slag a better use.

**Comment by idontknowhwhattoputhere** [comment]
oh, and a silicon crucible should be able to use pyranite as an alternative fuel.

**Comment by itcannotbe** [comment]
It would need to be at least 80/second to be not better than placing a thermal generator on lava.

**Comment by idontknowhwhattoputhere** [comment]
... idk im just throwing the base idea.

**Comment by itcannotbe** [comment]
> oh, and a silicon crucible should be able to use pyranite as an alternative fuel.

Funny. Have you check the block? Putting it on hot tiles including lava boosts the block already.

**Comment by idontknowhwhattoputhere** [comment]
slag as alternative fuel* my bad.

**Comment by itcannotbe** [comment]
How would that work you already use lava/hot tiles, but adding lava would work somehow?

**Comment by idontknowhwhattoputhere** [comment]
i guess

**Comment by idontknowhwhattoputhere** [comment]
lol i just found out how to make a bigger core than normal

**Comment by idontknowhwhattoputhere** [comment]
core with 80 inputs...

**Comment by idontknowhwhattoputhere** [comment]
infinite extensions by what i see

**Comment by oinkymoo** [comment]
Itcannotbe the idea of this suggestion is that melter slag would go into the thermals, not slag pulled from pools

**Comment by EclipseTheOldOne** [comment]
> please tell me where in campaign i can find a lava pool to put my thermal generator on

~~image put power to melt scrap then make more power out of it~~
~~thermodynamics rules~~

**Comment by itcannotbe** [comment]
> Itcannotbe the idea of this suggestion is that melter slag would go into the thermals, not slag pulled from pools

I was pointing out the balance problem.

**Comment by EclipseTheOldOne** [comment]
actually, the thermal gen actually does consume lava back in b63 instead of direct placing on heat block (heat block didn't exist back then)
which can only be pump or melt rock
but melting rock to get lava didn't make more power than it input
also, the only uses of lava back then was to put into a thermal gen for power.
so, the ability to melt rock into lava was removed.

**Comment by idontknowhwhattoputhere** [comment]
> 

this is a suggestion to add / bring back, so i dont know why this is relevant.

**Comment by itcannotbe** [comment]
Because it's the freaking reason it got removed and got the mechanic changed in the first place.

**Comment by GitHubUser-B** [comment]
> If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> 
> And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.

Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!

**Comment by GitHubUser-B** [comment]
> > If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> > Which turning so scrap to slag for use in one, stupid.
> 
> Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!



> > If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> > And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.
> 
> Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!



> 1st of all, dont be rude. im not "stupid". 2nd 24/sec is a decent amount. 3rd: slag has practically no use really, its a good idea to give it a better use. i think anuken placed so much scrap because he was planning something...

This is just the beginning, beware of his "bros" like mr duck, a guy who also responds to suggestions (but less often) just to criticize them!

**Comment by GitHubUser-B** [comment]
> > please tell me where in campaign i can find a lava pool to put my thermal generator on
> 
> ~image put power to melt scrap then make more power out of it~ ~thermodynamics rules~ it pretty useless since: the only way to get slag (expext slag pool) is melting scrap but: scrap didn't hot itself, and in a melter you melt it using power, _and then put it into a generator_ to get power the power in won't be more than the power out, so it's no power generated and why would you pump slag just to put it into the thermal gen while you can already place thermal gen on slag ~using thermodynamics rules to shut this suggestion down~

~I'll also put strikethrough text for attention!~

**Comment by itcannotbe** [comment]
> > If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> > And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.
> 
> Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!

Is that you! You only find bad parts of suggestion that are criticized appalling. And the fact that a few other people would jump in and add their own critic means that my critic is enough to express their own view on the topic, else other people would have jumped in to counter my argument/s.

**Comment by GitHubUser-B** [comment]
> > > If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> > > And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.
> > 
> > 
> > Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!
> 
> Is that you! You only find bad parts of suggestion that are criticized appalling. And the fact that a few other people would jump in and add their own critic, means that my critic is enough to express their own view on the topic, else other people would have jumped in to counter my argument/s.

That's not it, you always try to find something bad to point out in the suggestions!

**Comment by itcannotbe** [comment]
> 

And what's your problem with that? If there's isn't anything bad, then there's nothing for me to say.

**Comment by itcannotbe** [comment]
> > > > If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> > > > And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.
> > > 
> > > 
> > > Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!
> > 
> > 
> > Is that you! You only find bad parts of suggestion that are criticized appalling. And the fact that a few other people would jump in and add their own critic, means that my critic is enough to express their own view on the topic, else other people would have jumped in to counter my argument/s.
> 
> That's not it, you always try to find something bad to point out in the suggestions!

And what's your problem with that? If there's isn't anything bad, then there's nothing for me to say.

**Comment by GitHubUser-B** [comment]
> > > > > If you think about using scrap other than to produce slag for use in turrets, you really must be desperate for materials.
> > > > > And if you made slag be usable in thermals it should be using a lot of it for balancing reasons. Which turning so scrap to slag for use in one, stupid.
> > > > 
> > > > 
> > > > Is that you! You only find bad parts of suggestions to critisize them, even your "colleagues" give an exception, but you still offend the people who posted them!
> > > 
> > > 
> > > Is that you! You only find bad parts of suggestion that are criticized appalling. And the fact that a few other people would jump in and add their own critic, means that my critic is enough to express their own view on the topic, else other people would have jumped in to counter my argument/s.
> > 
> > 
> > That's not it, you always try to find something bad to point out in the suggestions!
> 
> And what's your problem with that? If there's isn't anything bad, then there's nothing for me to say.

You look like a troll doing this.

**Comment by RickAstly** [comment]
What the heck happened here
This is not a bad idea, but we have enough power gen options, and I like that the thermal gen can only be used in specific places.

**Comment by COALROCK8642orCR8642** [comment]
First of all bring feature to dump solid things in slag. Since slag operated thermal genes will output "hot" scrap as output. May be time for a new building fluid-thermal genes.

**Comment by itcannotbe** [comment]
> First of all bring feature to dump solid things in slag. Since slag operated thermal genes will output "hot" scrap as output. May be time for a new building fluid-thermal genes.
> 
> Edit: PS: Well thermal power is already good and no changes need. But i get spasms to see that a thermal gene placed over slag outputs not +720% or +1280%

https://github.com/Anuken/Mindustry-Suggestions/issues/3177#issuecomment-968251156
