### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3178]
### Describe what you would like changed, and why.

if I copy by pressing "f" a single construction I would also like to have the possibility of being able to build it several times by holding down the key to confirm the construction instead of having to click every time I want to build it, in a nutshell when I copy a single structure I would like to have the possibility of build the same way as when I select it directly from the inventory.

### Describe the changes you want to propose. Include possible alternatives.

End.

**Comment by Kubek0212** [comment]
Something similar exist in trello
https://trello.com/c/dQVwyskS

**Comment by itcannotbe** [comment]
> Something similar exist in trello https://trello.com/c/dQVwyskS

THAT'S NOT SIMILAR. IT'S EXACTLY THE SAME.

**Comment by molecules1** [comment]
You can do "Pick block" with (default) middle mouse button, which will act exactly as if you had selected it from the block list.

**Comment by Ymabert** [comment]
@Kubek0212 @itcannotbe @molecules1 I did not know...thx

**Comment by OnyxFinger** [comment]
https://trello.com/c/dQVwyskS/872-schematic-lines
