### ISSUE TITLE
Automatic campaign save backups

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#3179]
### Describe the content or mechanics you are proposing.

I propose a new section in the main menu which displays save backups of your campaign runs.

The idea is that every 5/10/20 minutes what have you, the game will autosave the game as a loadable "backup". It is then stored in the new section in the main menu. Once a certain autosave limit is reached, the oldest autosaves are automatically deleted when new autosaves show up.

In this new section of the main menu, players can choose to load autosaves back onto the main campaign save. Additionally, players will be able to choose if they want the game to autosave at all or not.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I hardly play campaign, and I have gotten my campaign fucked up three times due to errors. Mindustry is error-prone as any game is, and an auto-backup save is crucial to keeping campaign runs secure. The game can accidentally corrupt your current save but cant corrupt autosaves it's not doing anything with.

At the moment I hardly play campaign and play on servers instead solely because I no longer trust the single save mindustry has to keep my campaign secure. I wish I could build tons of factories and play more, but I lose the motivation to do so when it's constantly in jeopardy.

I know I crash more than others, and I know campaign save corrupting is a small problem. but it really isnt. the more mindustry is made, the more stuff can go wrong, the bigger the chance the campaign save gets corrupted. and once it gets corrupted there is no going back.

Some members have told me "just create backups" but never have I ever needed to create copies of game files to store somewhere else just to keep my save secure. No game, especially not one available on mobile, should ever need you to poke around in files - that is NOT good game design.

So, I urge anuke to include autosaving in the upcoming V7 update. V7 is already a base platform to be used as the foundation for V8's massive campaign expansion. So let's make the V7 foundation much stronger by essentially corrupt proofing the game. We can continue to patch bug after bug or we can make an autosave mechanic so that those that lose their saves to corruption never have to worry again. Thank you very much for reading.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
How do save files gets corrupt again?

**Comment by itcannotbe** [comment]
> single save mindustry has to keep my campaign secure. 

Ah yes. Actually it isn't a single file.

**Comment by sup3r87** [comment]
> How do save files gets corrupt again?

to be honest i'm not even sure. just sometimes happens. but it seems to be if the computer is force-shutdown'd during a campaign run (my pc has freezed before). there are other ways it can happen too.

**Comment by Anuken** [comment]
As of v7, the game already makes two backups at various times. Save corruptions are a solved problem in games; the user shouldn't have to deal with them. Creating an entire system just to work around a technical issue is not the way to go.

> three times due to errors.

Was this in v7?

**Comment by Ymabert** [comment]
@Anuken the problem is that a player cannot go to search in the files for the save that he wants to load, so I think it is a good idea to add a setting in the main screen where you go to select the file of the automatically saved campaign that you want to go to play;  if I select a file from the bottom (so an old one, where I probably started a level or unlocked something in the tree) it becomes the first save, so it is put as the first.  It is a good idea, because if someone (especially a newb) starts a level but does not know how to best manage resources, or does not know exactly which defenses to build and for these errors he loses 1 or 2 hours of play with the possibility of resuming from where he lost everything he can better manage everything again and instead of repeating the level by rebuilding most of the things he only has to load the file he prefers to start from a good point of the game.

**Comment by Anuken** [comment]
> the problem is that a player cannot go to search in the files for the save that he wants to load

That is not *the* problem. Players should never lose their progress randomly, period. Read my message again.

**Comment by sup3r87** [comment]
> As of v7, the game already makes two backups at various times. Save corruptions are a solved problem in games; the user shouldn't have to deal with them. Creating an entire system just to work around a technical issue is not the way to go.
> 
> > three times due to errors.
> 
> Was this in v7?

twice in v6 and once in the beta v7 so far.
If the game actually does make backups, I'd like to know where they are in the game files. but if the game makes its own backups already, then this suggestion should be closed.

**Comment by Anuken** [comment]
> once in the beta v7 so far.

When was this? Which game version, approximately?

> I'd like to know where they are in the game files

Next to `settings.bin`.

**Comment by sup3r87** [comment]
> When was this? Which game version, approximately? The changes mentioned were only added after ~build 128.

honestly? I forget, but it's been a few months. This suggestion came to my mind when I was thinking about playing the game again.

> next to settings.bin.

Alright. I didn't realise there were backups for the pc version. in that case i'm gonna close the suggestion as it now means nothing.

**Comment by Ymabert** [comment]
@Anuken I took it for granted that a player must not lose data, the methods to follow to solve problems I don't know what they are, I try to help by fixing (if that's the right word) some ideas I read, as in this case.  If the problem with the given solution has already been solved then I understand that it makes no sense to continue to suggest things about it (as in this case)

**Comment by itcannotbe** [comment]
You don't even have to ping the repository owner. He always get notified.

**Comment by BlueWolf3682** [comment]
There are save backups for all platforms - they are not used as much on mobile because mobile operating systems shut down differently and are generally more reliable.

**Comment by Ymabert** [comment]
@itcannotbe I know, but I was referring to him and only him, so I indicated him with an '@'

**Comment by itcannotbe** [comment]
IT STILL MENTIONS AND NOTIFIES WHO YOU DID THAT TO. COUNTLESS PEOPLE HAVE ALREADY TOLD YOU THAT.

And yet you still continue on doing so. Are you sure you don't need to talk to a medical professional at this point?

**Comment by Anuken** [comment]
It doesn't really matter whether someone explicitly pings me here or not, the result is the same - please calm down, there's no need to get so worked up about this.

**Comment by itcannotbe** [comment]
He actually mentions everyone who he talks to. It's not necessarily limited to you.

~mostly it is~

**Comment by Ymabert** [comment]
@itcannotbe ok sorry, just wanted to highlight some things about how I think more than anything else 😅

**Comment by Kyllingene** [comment]
Blowing a gasket about a simple mention seems the more dangerous behavior compared to mentioning people unnecessarily.

**Comment by itcannotbe** [comment]
Nah. It's just a bad way to emphasis the point anyways.

**Comment by Kyllingene** [comment]
So you think unnecessary mentions are more dangerous than a bad temper? Have you ever heard of Agamnenon?

**Comment by itcannotbe** [comment]
It's not, per se, except when you keep doing it despite multiple people telling you to stop doing it unnecessarily.

And not everyone using all caps is essentially shouting, you kno that?

**Comment by Kyllingene** [comment]
I understand you were not necessarily shouting, but you were still utilizing full caps in a very antagonistic way without good cause. And no, getting overly angry at people for doing something so small (that is a good habit in many cases) is *not* reasonable, and is indeed more dangerous than a harmless habit.

**Comment by sup3r87** [comment]
oh my god guys can you please take this elsewhere? this is an abandoned suggestion not a chatroom

**Comment by SMOLKEYS** [comment]
> oh my god guys can you please take this elsewhere? this is an abandoned suggestion not a chatroom

**humanity**
