### ISSUE TITLE
Waves should prioritize enemies without it's status effect

### ISSUE THREAD

**Issue by gen-NA-owl** [Anuken/Mindustry-Suggestions#318]
**Describe what you would like changed, and why.**

Waves are mainly used to apply status effects (debuffs) on enemies, so it makes sense that they should try and target enemies without the debuff they give. (instead of locking onto just one target and continuously debuffing that)

**Describe the changes you want to propose. Include possible alternatives.**
Change the targeting.

**Comment by SupremeTurtle** [comment]
yes

**Comment by Anuken** [comment]
See my comment on a similar suggestion: https://github.com/Anuken/Mindustry-Suggestions/issues/348#issuecomment-674440771
