### ISSUE TITLE
Inverse Lookup Command

### ISSUE THREAD

**Issue by molecules1** [Anuken/Mindustry-Suggestions#3180]
### Describe the content or mechanics you are proposing.

I think this is a simple request, given the introduction of the Lookup command in Build 127.

The Lookup command converts a number to an unit/item/liquid/block type.

I'm requesting an "Inverse lookup" (or maybe a subcommand of the Lookup) that does the opposite, converting a type into a number.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I have tried to store an item type in a memory cell many times, so I could save the state of a sorter and use it later.  I specifically want to use this kind of function to store many item types, while using 2 switches and a single sorter to select all of them.

I think the Lookup command could fill this niche, but it kind of requires an inverse to go with it, since there would need to be a way to go from a type to a number for the memory cell.  This can obviously be done with a bunch of jumps, but that would take too long, especially with a microprocessor, or it can supposedly be done with some counter manipulation black magic.  Still, this extra command would make life much easier for storing types, by condensing 17 commands into 2.

Edit:  Also, if the new item types shown in the #dev-previews Discord channel are fully added, then this would make even more sense to increase the speed of processing.

Thanks!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
adding a sensor like `@id` could also work, without adding more instructions to the game

**Comment by molecules1** [comment]
Do you mean that it would be like the `config` sensor, but output a number instead of a type?

**Comment by end-me-please** [comment]
`sensor result @flare @id`

would return the ID of flares

**Comment by molecules1** [comment]
I feel like that doesn't really make sense, since sensor is for getting data from a unit or building, while the lookup command and my proposed inverse lookup command simply converts between data types.  

Anyways, if Anuke added the Lookup command instead of making it a sensor, it stands to reason that an inverse lookup should not be in sensor as well.

**Comment by Kyllingene** [comment]
How on earth would you make an id-to-type sensor? *Sensors can only get values from blocks or units.*

**Comment by end-me-please** [comment]
https://github.com/Anuken/Mindustry/blob/90d1770b3e3c129591224351821310b972f5c22e/core/src/mindustry/logic/GlobalConstants.java#L115

possibly relevant

**Comment by cdelog** [comment]
I'll second this. An inverse lookup command would be extremely helpful. Currently, if I have a variable with the value @coal, I can't find an easy way to convert this to the number 5.
