### ISSUE TITLE
Waypoint movement for command ships.

### ISSUE THREAD

**Issue by DanTheTerrible** [Anuken/Mindustry-Suggestions#3181]
### Describe the content or mechanics you are proposing.

I suggest a system to implement waypoints for moving the command ship.  The point is to allow moving the command ship quickly around the map without manually using the asdw keys to move, which I find way tedious.

As an advanced option, perhaps allow bits of this system to be built into a system for guiding attacking friendly units to go where you want them.  But KISS, start with just the command ship and get that working before doing complicated stuff with units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To implement this I suggest there be a new building called "Navigation center".  When you build this and click on it it opens a numbered list of Destinations and Waypoints.  The basic list might be fairly short, but expandable by adding memory Logic modules [I haven't played with logic so I am vague on the memory modules].   Clicking on the navigation center a second time closes the list so it doesn't obstruct the game map.
------
Each entry in the list is either a destination or a waypoint.  A destination is simply a place you want to repeatedly move your player ship to without having to worry about asdw controlling it.  Optionally the player can give the destination a name.  Clicking on a Destination in the list simply sends your ship from wherever it is straight to the Destination.  Not a releport, but a straight as the crow flies move.  A destination name would be something like "ground defense point", "air unit trap", "unit factory area", Coal mine 1, etc.
------ 
Waypoints would allow programming circuitous routes.  Each waypoint would simply send the player to a destination on the list or another waypoint, once units get close to it.  The text on a waypoint entry is simply the next waypoint or destination the waypoint sends you to.  The player may enter the next waypoint's 1-2 digit auto-generated designator code [see next paragraph] instead of a name if he wants.  That would make for quicker entries but be less readable
-------
I think each destination or waypoint created ought to be given an Identifier automatically, so the player can skip typing in a name if he wants -- the list would be less readable, but quicker to enter.   I suggest alphabetic characters, A through Z and then if the list gets insanely long go to two digits:  Aa to Az, Ba to Bz, etc.  After the automatic identifier is a code describing waypoint string length.  A destination simply has a length of 0, indicating your ship stops there on arrival.  A intermediate waypoint is a numeral, 1 to 9 or maybe less.  The numeral simply indicates how many waypoints you have to go through before you get to the final destination.  That would limit the function to 9 intermediate waypoints which is surely plenty.  List spots with nothing in them should be clearly vacant, perhaps with odd color text saying "none".
-----
It is debatable if unending circular rings of waypoints should be allowed.  If so, any waypoint leading to the ring should display the infinity symbol.  By default the code should probably assume any waypoint length that reaches 10 is infinite.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> I suggest a system to implement waypoints for moving the command ship. The point is to allow moving the command ship quickly around the map without manually using the asdw keys to move, which I find way tedious.

Why do you even want this? You are in control a unit or router directly, there is 0 sense in adding this.

> As an advanced option, perhaps allow bits of this system to be built into a system for guiding attacking friendly units to go where you want them. But KISS, start with just the command ship and get that working before doing complicated stuff with units.

Lack of ability to use logic detected.

**Comment by DanTheTerrible** [comment]
Anuke feels my suggestion is nonsensical and I expect if I understood the game better I would agree.
