### ISSUE TITLE
Campaign Mode on dedicated server

### ISSUE THREAD

**Issue by Sebdomsan** [Anuken/Mindustry-Suggestions#3182]
### Describe the content or mechanics you are proposing.

Campaign Mode on dedicated server.
I would like to able to play the Campaign on the my dedicated server for the game so that me and my friends can make progress even when main host is not available to play.
Presumably the game processing would pause when no one is online.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
It would be nice to have where multiple people(Preferably only the server admins) could select the the next sector on the planet that we are going to while keeping the progress on last sector we are leaving. Like how it works in Campaign now.
(long shot) - It would be nice to be able to split up our team to separate sectors to deal with incoming invasions. But this could be game breaking.
I understand my wants are not the games needs

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
The problem with this is selecting a sector to play. With Steam hosting, the host invited players once they are already on a sector; with dedicated hosting, there is no good way to select a sector, and absolutely no way to nicely handle *changing* sectors.

**Comment by Sebdomsan** [comment]
Very valid. I would assume it would just load the last map that was loaded/or that that player was on. and should a player have never joined the server to the first sector they go.
or if the sector they were last in is since no longer available to the first sector they go.

**Comment by Kyllingene** [comment]
That is assuming that sectors are being simulated constantly. This is not true (that would totally wreck mobile). The income calculations are done simply by seeing how many resources per minute it produces when you are on the sector, then sustaining that output (that's why incineration was implemented; so that an accurate prediction can be made).

Therefore, hosting multiple sectors would require a total rework of how campaign works, and be highly intensive (even more so than large multiplayer games with enough people).

**Comment by Sebdomsan** [comment]
okay so would just one sector at a time but just where "Host" controls go to an admin(like the first one to join the server until they leaves) and then still play on one sector at a time. 

my main ask here is just being able to move "host" status around with out having every one have to play separate campaigns going. 

my groups particular issue is that we all play on Player1s  campaign save.

but if every one is on but player1 is at work we pretty much dont play because we cant get back on the same save file

**Comment by Kyllingene** [comment]
Ok, that sounds reasonable to me; however, it might be more work than Anuke is willing to put in while working on v7.

**Comment by Sebdomsan** [comment]
For sure. Its a want not a need I would love to see it but the game is still well worth playing and paying for like I said at the start of the thread "I understand my wants are not the games needs" hopefully this is something Anuke would like to add to the roadmap but at the end of the day their game their plans their call.

**Comment by itcannotbe** [comment]
For now you may consider running a client version and a VNC to control it.
