### ISSUE TITLE
Poly

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3183]
### Describe what you would like changed, and why.

when I build using a scheme many times it happens that my spacecraft and the poles continue to build even the blocks that temporarily cannot be built (because I do not have the necessary materials), neglecting instead all the others that can be built safely since the materials I have them, so if I don't have the necessary material to build certain blocks why don't the poly activate automatically to build all the rest?

### Describe the changes you want to propose. Include possible alternatives.

for example if I have to build something with a material that enters the core in very small quantities and therefore I am at constant 0 of this material, I would prefer that when it enters all the poles they stop building the rest of the scheme and help my spacecraft to build the chosen block, only when I have the material, so if for 0.1 seconds I receive the material the poly automatically come to my rescue in the construction.

**Comment by end-me-please** [comment]
Are you on V7?

**Comment by Ymabert** [comment]
No, why?

**Comment by end-me-please** [comment]
iirc build order mechanics are different in V7, to prevent construction of buildings that can’t be finished

you should, if possible, switch to v7

**Comment by Ymabert** [comment]
Ok thx

**Comment by Kyllingene** [comment]
So close this (since it's already a thing)?

**Comment by Ymabert** [comment]
@Kyllingene I don't understand if in V7 the poly is different, because many times to build small things you don't need to have poles, so if in V7 I don't automatically build the schemes I think this advice is still useful.

**Comment by Kyllingene** [comment]
The poly should use the same build priority as the player; any other way would be extra, unnecessary work on Anuke's part.

**Comment by oinkymoo** [comment]
the polys will always build whatever block the player is building?

**Comment by Ymabert** [comment]
@oinkymoo yes, but if they cannot continue to build it due to the absent but necessary materials they simply continue to build all the rest of the chosen scheme and when the core receives the materials all the poles return to build the block left under construction by the player's ship, it would be so a convenient idea, since many times I want to build with schematics that have blocks that take little time to build, because in this way the work of building the schematic would be distributed over more constructor rays and therefore I would waste much less time.

**Comment by Ymabert** [comment]
@Kyllingene in what way?  poles are the only intelligent drone, so why not add in their program some sort of distribution of the scheme you want to go to build, ok a poly serves as a support, but if I have no materials why my shuttle has to stop building a block that cannot build? or because if I have many small blocks the poly do not automatically understand to complete the scheme by themselves? since otherwise they remain stationary and no longer serve as a support to the player.

**Comment by Kyllingene** [comment]
The poly has it's own AI, but it would still use the same build method. I'm saying that fixing it for players should fix it for polys as well; if it didn't, it would mean that Anuke had taken a really odd path to take for an experienced game dev.

**Comment by itcannotbe** [comment]
Actually poly s is the only unit who can shoot bullet order to repair buildings.

**Comment by Kyllingene** [comment]
That has absolutely nothing to do with build AI.

**Comment by itcannotbe** [comment]
It doesn't  but I was replying to this

> since otherwise they remain stationary and no longer serve as a support to the player.

**Comment by itcannotbe** [comment]
Also it seems that he still didn't tried out v7 for himself to see the changes

**Comment by Kyllingene** [comment]
That is besides the point anyway. Their point was that they do not fulfill their purpose fully.

**Comment by Ymabert** [comment]
now they are only a support to the player for the construction of longer blocks, instead if the poly also had these other qualities they would be really useful for the generation of all kinds of schemes and for saving time.

**Comment by itcannotbe** [comment]
Also there is still a use case for poly s to actually continue making someone it can't. Even if it means using the trickle of resources coming into the core especially in the early game. 

The only real issue this poses though is on multiplayer.
