### ISSUE TITLE
Material Consumed

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3184]
### Describe what you would like changed, and why.

I find it senseless that if a material when it enters a block and begins to be consumed if I let it go out through an unloader, the material even if it is in consumption leaves the block (for example if an impact reactor has 1 blast to its internal and begins to consume it I can very well let it out even if the blast is in consumption).

### Describe the changes you want to propose. Include possible alternatives.

you can create a material disposal time for each single material or simply when a material is in consumption it can no longer get out of the block.

**Comment by RealYeet** [comment]
Should I start explaining that the blast is consumed before the impact starts and not the other way around? This also applies to every other block in the game.

**Comment by itcannotbe** [comment]
I find it senseless that someone has issues grasping that mechanic.

1. Put connect the impact to a power network with excess production/reserve battery power
2. Feed cryofluid.
3. Put in one blast
4. Take it out using an unloader
5. Realize that you can't
6. Go into a corner and wear a dunce hat.

**Comment by begginerr** [comment]
> I find it senseless that someone has issues grasping that mechanic.
> 
> 1. Put connect the impact to a power network with excess production/reserve battery power
> 2. Feed cryofluid.
> 3. Put in one blast
> 4. Take it out using an unloader
> 5. Realize that you can't
> 6. Go into a corner and wear a dunce hat.

yeah, the item starts to get used IMMEDIATELY, making that item impossible to unload unless there is already an item being used

**Comment by Kyllingene** [comment]
@itcannotbe, I find it senseless that someone could be so pointlessly rude.

**Comment by begginerr** [comment]
> when a material is in consumption it can no longer get out of the block

that is already happening???

**Comment by itcannotbe** [comment]
> @itcannotbe, I find it senseless that someone could be so pointlessly rude.

I just copied his intro.

And yes, I clearly understand the didn't satisfied the the resource requirements to start up an impact reactor, even if block info exist....

**Comment by Kyllingene** [comment]
I was referring to indirectly calling them a dunce.

**Comment by itcannotbe** [comment]
It seems you need a background for that.

<https://en.m.wikipedia.org/wiki/Dunce>

**Comment by Kyllingene** [comment]
What's your point? The dunce cap was given for bad behavior, but was also labeled "dunce." As the article so helpfully pointed out, that term is indeed an insult. Therefore, if you would like to "punish bad behavior," you may choose your words more carefully.

**Comment by itcannotbe** [comment]
You missed the part where it is also given to those who failed to demonstrate that they had properly performed their studies.

**Comment by Kyllingene** [comment]
You missed the part where I said that if you would like to "punish bad behavior," you may choose your words more carefully.

**Comment by itcannotbe** [comment]
Actually I and other people tried reporting myself. Nothing happened.

It seems this isn't considered breaking the code of conduct.

**Comment by Kyllingene** [comment]
Did I even imply I was reporting you?

**Comment by Ymabert** [comment]
wow wow wow, I give an example on the impact reactor taking into consideration only the fact that when the material starts to wear out it can still be taken out of the reactor without losing it and you understand that I don't know how to use statistics and information to make it go, I guess it's not me going to the corner with the donkey hat here, then fuck ... at least a minimum of kindness and respect, after a while people get tired of being criticized and insulted by a lifeless asshole on the other side of the world, just really enough the cringe level has been exceeded too much this time, every suggestion I read there is always the USUAL jerk who disapproves and comments depreciating the suggested idea, every time, please instead of doing notice to the world that you have a useless shitty life because you don't try to improve at least in something?

**Comment by Ymabert** [comment]
@RealYeet if the material was sucked in and a sort of bar appeared in the reactor like the turrets indicating how much blast is still needed, it would be a good idea, because so the material once inside and once the whole process has started could no longer exit

**Comment by itcannotbe** [comment]
Production buildings only consume what they need, if you are suggesting to make all building turret like in terms of how they handle resources. Just use unloaders not set to null or logic, depending onn your use casde.

**Comment by itcannotbe** [comment]
Also @Ymabert, if you think deleting something quickly will prevent people from having a copy of what you said online.

You are dead wrong.

**Comment by Kyllingene** [comment]
They don't seem to have deleted anything...?

**Comment by itcannotbe** [comment]
![Screenshot_20211115_080415](https://user-images.githubusercontent.com/45280919/141704357-2cf80919-81e7-4320-a2af-40875bd109b6.jpg)

**Comment by Ymabert** [comment]
did you feel called into question?  next time, respond with more courtesy and avoid unnecessary problems with people.

**Comment by Kyllingene** [comment]
Ah, ok.

**Comment by Ymabert** [comment]
I'm just saying that I just got tired of finding the usual always saying the usual things against the usual innocent comment published just to help, I would say that sooner or later someone said this, I'm not proud, I don't really think everything, but fuck. .. getting to do this to a person is really bad, you have to work hard to be such a pain in the ass and you did it congratulations itcannotbe

**Comment by itcannotbe** [comment]
Respect isn't give out right of the bat, it is earned. And given [your suggestions to date](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+author%3Aymabert)

I certainly say you haven't earned it.

**Comment by Kyllingene** [comment]
They *not once* mentioned respect. They did, however, request common courtesy, something that is *by definition* reasonable to expect and something which you rarely give.

**Comment by itcannotbe** [comment]
See image.

**Comment by Ymabert** [comment]
yet I have always tried to respect everyone and everything, instead you demand respect but you do not give it, but community is not only a matter of respect, but of kindness and respect towards the ideas of others, whether they are right or wrong, because how do you do you seem that all ideas are wrong and with this excuse all you do is write the most provocative comments possible, so I ask you can you make speeches about what respect to others is or is the opposite better?

**Comment by begginerr** [comment]
its weird how this went from a dunce hat to discussing respect
