### ISSUE TITLE
Player Launcher

### ISSUE THREAD

**Issue by Pajamaman2020** [Anuken/Mindustry-Suggestions#3185]
### Describe the content or mechanics you are proposing.

Make a gun that shoots players around like the gun that shoots blocks or factorys around but just with the players so for fast travel

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will be help full for players with slow bots that will be launched in a few seconds to there desiring place like if I'm in the other side I can be launched to the battle field with in like 3 seconds or less but it will cost a lot of power to launch one player like just 300 power units
Also (if you add this content) could you just put a cooldown on shooting other wise the players will start making traps

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Pajamaman2020** [comment]
Would be use full in my mind

**Comment by random-guy1285** [comment]
The player can already posses any unit [on their team] instantly from anywhere. This would be redundant

**Comment by oinkymoo** [comment]
the problem seems to be that the alpha/beta/gamma itself is needed in 2 places at once and neither of the solutions you presented would perfectly complete that objective

**Comment by Darkness6030** [comment]
Uh. I could make a plugin to launch players if anuke added a possibility to move player's camera on mobile

**Comment by InventionIO** [comment]
Nah, i think its cool

**Comment by InventionIO** [comment]
it would be also useful like as teleporters, or not ?

**Comment by InventionIO** [comment]
like buildings, (the guns) but buildings that will teleports you.

**Comment by InventionIO** [comment]
Both ideas and alternatives are cool.

**Comment by InventionIO** [comment]
i maybe could help with this

**Comment by SMOLKEYS** [comment]
> that will teleports you.


~~uh, anuke wont add teleporters~~

**Comment by itcannotbe** [comment]
> > that will teleports you.
> 
> ~uh, anuke wont add teleporters~

~[The source](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)

**Comment by idontknowhwhattoputhere** [comment]
you can make a router highway by placing routers, using logic to make a poly on each side, then spam clicking to get from place to place (you can be one with the router, and make the router the one with you).

**Comment by oinkymoo** [comment]
exiting router will kick you back to the core tho

**Comment by Kyllingene** [comment]
That would be the purpose of the idle poly's.

**Comment by notMEEPoffaith** [comment]
use betamindy lmao

**Comment by Pajamaman2020** [comment]
yes but It will need a weird effect then like a explosion of dust not a
explosion that's going to break stuff like how i would say it is like a
cool effect

**Comment by GitHubUser-B** [comment]
> > that will teleports you.
> 
> ~uh, anuke wont add teleporters~

~I want attention!~
