### ISSUE TITLE
Made meltdown can be overdrived

### ISSUE THREAD

**Issue by Jackson11500** [Anuken/Mindustry-Suggestions#3186]
### Describe what you would like changed, and why.

Currently, meltdown cannot be overdrived, which made it is relative weak in late game play, especially when every other turrent, factory and defense blocks can be overdrived to 250% effeciency. 
For late game dps, consider that 4 lancer does 1050 DPS in overdrive dome, while no liquid needed, much more cheaper and does more damage to high armor enemies and only 4 range shorter than meltdown, and no need to say the other stronger turrent. While flying units are larger, which means meltdown's AOE abilities is much more weaker can be easily replaced by the other overdriveable turrent. 
For build cost, 325 surge alloy used by 2 overdrived cyclone can easily take down hundreds of T3, multiple T4 and even wet T5 units for many waves.

### Describe the changes you want to propose. Include possible alternatives.

Made Meltdown canOverdrive, which can be achieved by:
1. made meltdown does more damage linear to overdrive boost
2. made meltdown cooldown speed can be overdrived. Ex. meltdown fires  30% of all time and in overdrive dome it fires 75% of all time, and increase its basic damage

**Comment by itcannotbe** [comment]
I think with how the meltdown currently works, I think it's better to increase the rate it damages when ovwr driven, but keep the same shoot duration.

**Comment by OnyxFinger** [comment]
yes. Meltdowns are really bad when compared to, well, anything that uses surge.
