### ISSUE TITLE
Logic unit

### ISSUE THREAD

**Issue by InventionIO** [Anuken/Mindustry-Suggestions#3187]
### Describe the content or mechanics you are proposing.

Logic unit (flying), basically. Unit for logic processors.
Could be built infinetely for the purpose of logic.

who ?: Logic unit
where ?: in game
what ?: Logic unit
why ?: its a good idea
when ?; now
with what ?: nothing

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You could make infinite logic unit schems (automatic unit generators and production cells). It wont be limited

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by InventionIO** [comment]
Like i havent seen all the content but i trully know that it isnt there. I feel it in my bones

**Comment by InventionIO** [comment]
Cus i am now new for this version.

**Comment by InventionIO** [comment]
I havent played this game for a long time cus the content was for me a little bit boring (like schematic building and speedrunning matherials basically) but im back now.

**Comment by InventionIO** [comment]
should i draw it ?

**Comment by InventionIO** [comment]
It would be better for me.

**Comment by end-me-please** [comment]
I’m pretty sure that this has been suggested before

**Comment by InventionIO** [comment]
wait really ?

**Comment by InventionIO** [comment]
where ?

**Comment by InventionIO** [comment]
Some people think about my ideas too (that they exist already too), lol

**Comment by InventionIO** [comment]
dont actually know why tho.

**Comment by InventionIO** [comment]
why so much hate ?

**Comment by RFAC-Productions-Reborn** [comment]
> I’m pretty sure that this has been suggested before

So someone suggested a mobile logic processor before?

**Comment by end-me-please** [comment]
so you mean a mobile logic processor? That wasn’t really clear in the original suggestion.

but still, i don’t see how it would fill a niche. is there anything it could do that any other unit bound to a micro processor couldn’t?

and how would it be useful? Even simple tasks like item transport would become overly complicated because a mobile processor couldn’t have fixed links, you’d have to hard-code coordinates for every application.

**Comment by oinkymoo** [comment]
nowhere does the original suggestion or its poster imply that there should be mobile logic processor. also with how common polys and flares are in logic scripts, i don't think this is necessary

**Comment by InventionIO** [comment]
It wasnt supposed to be a mobile logic processor, actually, it was supposed to be like a unit that will be used for logic components like a classic unit but with the thing that it could have been built by infinite numbers, that was all. But thats a kinda cool idea too.

**Comment by RFAC-Productions-Reborn** [comment]
> nowhere does the original suggestion or its poster imply that there should be mobile logic processor. also with how common polys and flares are in logic scripts, i don't think this is necessary

Ahhh I see, got it.

**Comment by InventionIO** [comment]
ok, nicec
