### ISSUE TITLE
Multiple campaigns

### ISSUE THREAD

**Issue by InventionIO** [Anuken/Mindustry-Suggestions#3188]
### Describe the content or mechanics you are proposing.

You could have multiple created campaigns in one mindustry.
like new worlds in minecraft.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It may add more possibilities and fun. Also it can help alot with modded campaign (like you will have the mods in one campaign and in the other not). It will basically work like modpacks in minecraft curseforge. You could even also name your campaigns

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by InventionIO** [comment]
Is it a cool idea ?

**Comment by InventionIO** [comment]
I could help with the programming.

**Comment by itcannotbe** [comment]
I mean a significant amount of functionally to make this a reality sorta already exist.

Except that pesky setting being included in the campaign data

**Comment by InventionIO** [comment]
ok

**Comment by InventionIO** [comment]
nice, so it will be added ?

**Comment by itcannotbe** [comment]
> nice, so it will be added ?

Why did you conclude to that?

**Comment by InventionIO** [comment]
Whats the setting ?

**Comment by InventionIO** [comment]
I mean, its a nice idea.

**Comment by InventionIO** [comment]
at least it looked like that

**Comment by InventionIO** [comment]
Did i didnt understand the question ?

**Comment by InventionIO** [comment]
I havent noticed you edited that.

**Comment by InventionIO** [comment]
> I mean a significant amount of functionally to make this a reality sorta already exist.
> 
> Except that pesky setting being included in the campaign data Or better understood as the campaign data saved in the settings.bin file.

Well it could be solved like that it will be a folder instead of a file, at least thats how i got it.

**Comment by InventionIO** [comment]
For every campaign it will be otherwise

**Comment by InventionIO** [comment]
It also could be called: Campaign settings

**Comment by InventionIO** [comment]
Are you here ?

**Comment by InventionIO** [comment]
You here ?

**Comment by RealYeet** [comment]
Ok, first, the spam is really hard to read lol. Second, this is a good idea which I support but it has been suggested before so I don’t think Anuke will add it soon. Maybe in V7

**Comment by RealYeet** [comment]
Doubt it tho

**Comment by InventionIO** [comment]
ah, ok, wait, this was suggested before ?

**Comment by InventionIO** [comment]
where ?

**Comment by InventionIO** [comment]
Wait, in whitch v7 ?

**Comment by InventionIO** [comment]
The one now, or the one later ?

**Comment by RealYeet** [comment]
> Wait, in whitch v7 ?

I dunno if it will be a feature, if it is it will probably be released with the full release of V7. Then again, I am not the most attentive so it probably not be a feature.

**Comment by end-me-please** [comment]
cant you just export your game data? and import it again when needed

**Comment by InventionIO** [comment]
But this is the cooler way.

**Comment by InventionIO** [comment]
to do that and more accesible for others.

**Comment by InventionIO** [comment]
I've searched it and there was no other suggestion than mine whitch suggested more campaigns.

**Comment by end-me-please** [comment]
discussion/chatting should be done in the official discord, not here

**Comment by InventionIO** [comment]
You are just wasting my time.

**Comment by InventionIO** [comment]
go do things somewhere else @#^&#.

**Comment by InventionIO** [comment]
Rather make your own suggestion and dislike yours.

**Comment by InventionIO** [comment]
Nobody cares what you think here.

**Comment by InventionIO** [comment]
you disliking kiddo.

**Comment by Nils101** [comment]
@InventionIO please stop this childish spammy behavior. Anuke will read your suggestion and implement it if it can be implemented and he likes it. No need to open/close like a madman

**Comment by itcannotbe** [comment]
> @InventionIO please stop this childish spammy behavior. Anuke will read your suggestion and implement it if it can be implemented and he likes it. No need to open/close like a madman

![I agree](https://c.tenor.com/r_lhoj0yS6AAAAAM/iagree-storks.gif)

**Comment by Ymabert** [comment]
if it is possible, I think it would be better to find other smaller planets with other types of terrains and with other enemies and that the levels are not created by the developer but generated by the computer (so planets with few levels created by the developer while all the others are generated by the computer and the levels created by the developer are only secondary sectors compared to the important sectors that are currently on the planet; they only serve to make sense of the planet since in those sectors there are the main bases of the enemies).

**Comment by Kyllingene** [comment]
To clarify what others were talking about with the spam thing, you seem to treat Github as if it were Discord. It is not. Many of us (including myself) get an email for *every single comment*. Treat it like email.

**Comment by IxGamerXL** [comment]
> To clarify what others were talking about with the spam thing, you seem to treat Github as if it were Discord. It is not. Many of us (including myself) get an email for *every single comment*. Treat it like email.

At first I thought I was just seeing things with the repetition.

To add along with this, when you are spamming the thread, it is tremendously difficult to reach the most relevant post, and is annoying as all hell ( I'm looking at you @itcannotbe and @InventionIO ).

**Comment by itcannotbe** [comment]
> > To clarify what others were talking about with the spam thing, you seem to treat Github as if it were Discord. It is not. Many of us (including myself) get an email for _every single comment_. Treat it like email.
> 
> At first I thought I was just seeing things with the repetition.
> 
> To add along with this, when you are spamming the thread, it is tremendously difficult to reach the most relevant post, and is annoying as all hell ( I'm looking at you @itcannotbe and @InventionIO ).

I just made 3 comment in this entire issue (now 4). Why me?
It's not me that treated this like discord and expected a reply when someone wants to.

**Comment by IxGamerXL** [comment]
> > > To clarify what others were talking about with the spam thing, you seem to treat Github as if it were Discord. It is not. Many of us (including myself) get an email for _every single comment_. Treat it like email.
> > 
> > At first I thought I was just seeing things with the repetition.
> > 
> > To add along with this, when you are spamming the thread, it is tremendously difficult to reach the most relevant post, and is annoying as all hell ( I'm looking at you @itcannotbe and @InventionIO ).
> 
> I just made 3 comment in this entire issue (now 4). Why me?
> It's not me that treated this like discord and expected a reply when someone wants to.

Last time I checked before the spam was cleared, you had the same message sent several times, and in the same formation as two other people. Could be an error, but I reloaded a few times and results were the same.

If you _didn't_ send the same messages over and over again, then sorry.

Although that, the latter mention is most definitely just.

**Comment by InventionIO** [comment]
> @InventionIO please stop this childish spammy behavior. Anuke will read your suggestion and implement it if it can be implemented and he likes it. No need to open/close like a madman

It wasnt supposed to just make an anuke look into my idea, it was just like i had more to talkabout.

**Comment by InventionIO** [comment]
but i had only idea then later.

**Comment by InventionIO** [comment]
> if it is possible, I think it would be better to find other smaller planets with other types of terrains and with other enemies and that the levels are not created by the developer but generated by the computer (so planets with few levels created by the developer while all the others are generated by the computer and the levels created by the developer are only secondary sectors compared to the important sectors that are currently on the planet; they only serve to make sense of the planet since in those sectors there are the main bases of the enemies).

Thats a cool thing too.

**Comment by InventionIO** [comment]
anybody here ?

**Comment by Kyllingene** [comment]
Again, treat this like email; people usually don't reply very fast. *This is not Discord.*

**Comment by RFAC-Productions-Reborn** [comment]
> > if it is possible, I think it would be better to find other smaller planets with other types of terrains and with other enemies and that the levels are not created by the developer but generated by the computer (so planets with few levels created by the developer while all the others are generated by the computer and the levels created by the developer are only secondary sectors compared to the important sectors that are currently on the planet; they only serve to make sense of the planet since in those sectors there are the main bases of the enemies).
> 
> Thats a cool thing too. I think both should be implemented. and you could choose from that. or even seeds. so you could generate these, or even more generatable worlds / or presets. Cool things Do you have any other ideas ? @Ymabert
> 
> Did i got it wrong ?



> anybody here ?

Go to Discord. This is Email.

**Comment by InventionIO** [comment]
ok

**Comment by InventionIO** [comment]
But where ?

**Comment by InventionIO** [comment]
Oh, in pu... weait, is it in, wait, actually, where ?
(i wanted to ask if its in pulls but then i realised it is a completely other thing)
