### ISSUE TITLE
Cuentas

### ISSUE THREAD

**Issue by 3lgonzalez** [Anuken/Mindustry-Suggestions#3189]
### Describe the content or mechanics you are proposing.

Me gustaria que existiera una mecanica de cuentas llevo mucho pero mucho tiempo jugando mindustry y por cuestiones y problemas e tenido que desintalarmelo y cuando lo vuelvo a instalar no tengo nada se pierde creo que ya existe algo para recuperar tu progreso pero es medio complicado mas para un jugador de celular como yo y mi idea que allan cuentas dentro de mindustry y en el que inician cesion y cuando alguien se desintala el juego y vuelve a entrar solo incian sesion y listo tienes tu progreso y esa es mi idea me llamo sebastian gonzalez tengo 14 años y gracias por leer

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

No perder tu progreso y recuperarlo

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Rex-Hm** [comment]
Esta mecánica nunca será agregada, por razones obvias en lo costoso que sería y por el hecho de que ya hay una forma de recuperar el progreso que es exportando tus datos.

Le recomiendo cerrar su pr.

**Comment by itcannotbe** [comment]
- [x] I have **not** read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by begginerr** [comment]
> * [x]  I have **not** read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> * Built-in cloud sync

traducelo

**Comment by itcannotbe** [comment]
> > * [x]   I have **not** read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> > * Built-in cloud sync
> 
> traducelo

- No ha leído [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) para asegurarse de que mi idea no esté incluida en la categoría "Algunas cosas que no debería sugerir".

- Sincronización en la nube incorporada

**Comment by begginerr** [comment]
> > > * [x]    I have **not** read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> > > * Built-in cloud sync
> > 
> > 
> > traducelo
> 
> * No ha leído [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) para asegurarse de que mi idea no esté incluida en la categoría "Algunas cosas que no debería sugerir".
> * Sincronización en la nube incorporada

lo estaba pidiendo a el pero eso funciona
