### ISSUE TITLE
New Unit Class: Guard Units

### ISSUE THREAD

**Issue by Novoidconstell** [Anuken/Mindustry-Suggestions#319]
Broadly, as how I view it, there are 5 unit classes planned for 6.0: Mechs(Dagger, Fortress), Walkers(Crawler, Spiroct), Aircraft(Flare, Zenith), Support units(Nova, Quasar, Mono, Mega) and Naval units(Risso, Bryde).

**Describe the content or mechanics you are proposing.**

This is an idea for a new unit class specialising in base defence. Meaning their basic AI is programmed such that, by default, they don't leave the base's perimeter (like the no build zone in Attack and PVP), however they can be manually controlled by the player to move beyond said perimeter. These units are, in the long run, cheaper to field than Mechs, but are not very effective when attacking structures and bases due to their low range and, at higher tiers, low speed. Also, unlike any other unit, they can't shoot while moving; they can either move or shoot, they can't do both.

Guard units start off, in tier one I mean, as fast moving, high damage per shot units that strafe enemy units much like how Wraiths do. Going up the tiers they trade their speed and damage per shot for a lot of health and damage per minute, turning from harassers into line defence units. So the tier tree will start with something like an armoured car with a cannon, and end with a tank with an automatic shotgun, kind of like Fuse.

Unit Names:
I. Sentry
II. Paladin
III. Gatekeeper

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Attacking in Mindustry requires setting a defence first. Having units that specialise in defence can give a player more options in that first phase. He can play static by bolstering defence by adding more turrets and upgrading his guard units, or he can be dynamic using them to constantly break past layers of enemy defences and set an outpost while he builds the main strike force.

Note: I'm not good with numbers so I haven't suggested stats, but general comparisons and features have been made clear.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
The title could have been better....

Like Base/Core Sentry Units.

**Comment by Novoidconstell** [comment]
> The title could have been better....
> 
> Base/Core Sentry Units.
> 
> Would be a better choice.

Well that's kind of a place holder name, and plus in my mind this class' visual defining feature would be their wheels or tracks

**Comment by potatoisagender** [comment]
Itcannotbe is asking for some specificity in the titles. You wouldn't believe the number of suggestions here that are: new block, new troop, new this, new that.

**Comment by Novoidconstell** [comment]
> Itcannotbe is asking for some specificity in the titles. You wouldn't believe the number of suggestions here that are: new block, new troop, new this, new that.

Well if that's what he meant then the class' name is "vehicles". Sorry if that wasn't clear😛

**Comment by stuffyAI** [comment]
This title still stings... Aircraft, Mechs and Naval units are all vehicles, people can interpret ways into this.
Something like new defensive unit class or so would be spicier.

**Comment by SupremeTurtle** [comment]
I got clickbaited even here in github :(

**Comment by Novoidconstell** [comment]
> I got clickbaited even here in github :(

Sorry about that 😬😛

**Comment by jaygamer81** [comment]
I honestly like this idea. I hate it when my units just leave the defense and become walls. I want them to fight behind walls and only get them selves shot at when there is a breech through the defense, not so they can die and waste 80 silicon. Its honestly dumb and i dont understand it.

**Comment by RedstonerKBC** [comment]
This isn't a bad idea. If an enemy so much as makes contact with your core it's basically dead even when you use shields, force projectors, and defensive turrets. Units are just so op in v6 that adding a defensive option would make people rethink their attack strategy. Currently the only way to keep units near the core is via a command center, but it controls every unit, or by processors, but again controls every unit and you have to keep track of them. These defensive units should be better for defense rather than offense and shouldn't be so strong that cores are now impossible to destroy.
