### ISSUE TITLE
Easy way to switch teams

### ISSUE THREAD

**Issue by aushafer06** [Anuken/Mindustry-Suggestions#3190]
### Describe the content or mechanics you are proposing.

An easy way to switch teams when playing the pvp mode with friends. It would probably be best if this was controlled before the game started to prevent people constantly switching to the winning team. As an example, you could adjust the amount of people allowed for each team in the "customize rules" screen before loading into the world.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This mechanic would make it far easier if, for example, you wanted to 1v3 your noob friends, or even 1v4 for that matter. At the moment, you would have to join the game on multiple devices in a specific order to achieve this, and for certain people this method is unreliable if not completely impossible. This mechanic also would be easy to implement because of how small of a thing it is.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Plugins?

**Comment by itcannotbe** [comment]
Also, what's stopping people from logging off then re-joining to force team switch?

**Comment by Kyllingene** [comment]
It may already exist, but I believe this issue was directed more towards Steam servers than dedicated ones; that would be very helpful, as getting even teams (or worse, orchestrated teams) as it is is nearly impossible.

**Comment by aushafer06** [comment]
> Also, what's stopping people from logging off then re-joining to force team switch?

When you log off it disconnects the player, they would join back in the same team they were in when they left.

**Comment by IxGamerXL** [comment]
The best way to approach this (especially when hosting LAN servers) is to make the host device run code that listens for commands (via event: PlayerChatEvent), and if it is allowed, the host auto teams the player that sent the custom command.

Just takes some javascript, and it doesn't take much resources or RAM, so you could play on the host device just fine.

Although I am an average javascripter, I am quite busy doing something else, so you should learn some Javascript and solve the problem that way.

**Comment by aushafer06** [comment]
You could do that, but for the common Mindustry player, it would be nice to have an easy in-game way to control teams.
