### ISSUE TITLE
Oct shield as building.

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#3191]
### Describe the content or mechanics you are proposing.

i would like to see the oct shield used as a building (or something simmalar) expensive, but hass alot of hp (around 5k possibly) even though oct shield has 21k and normal shield has 750.
and the cooldown is wayyy slower than octs shield.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would become crucial to stronger defences, because shields are pathetic against toxopids, corvus, eclipse, vela, oct shield, reign, arkyid, antumbra, omura, sei, scepter, the new v7 units, foreshadow, meltdown, spectre, swarmer, fuse, im pretty sure ny kind of laser (exept if using plastanium wall).

just a better shield, u want another excuse why cant we use atleast a bit of octs technology...... 
and im also saying DONT MAKE IT CHEAP.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
Wasn't this suggested before?

**Comment by idontknowhwhattoputhere** [comment]
where?

**Comment by idontknowhwhattoputhere** [comment]
oh, i see, but by what i see it was a long time ago.

**Comment by end-me-please** [comment]
Normal force projectors offer nearly 100% protection against quads and horizons

**Comment by idontknowhwhattoputhere** [comment]
ok, 10 toxopids come, what do you do?
your dead if u dont have other units, imagine in fungal pass or maze map.

**Comment by end-me-please** [comment]
force projectors against toxopids sounds like using scatter against daggers

**Comment by idontknowhwhattoputhere** [comment]
ik. thats my point.

**Comment by idontknowhwhattoputhere** [comment]
its why better shields are something we need.

**Comment by begginerr** [comment]
> its why better shields are something we need.

yep, 750 hp is basically nothing late-game. 5k is something, not much but more than 750

**Comment by idontknowhwhattoputhere** [comment]
im sayign better shields.

**Comment by Kyllingene** [comment]
> ik. thats my point.

I believe their point was that you shouldn't be using force projectors against toxopids, just like you would never use scatters against daggers.

**Comment by idontknowhwhattoputhere** [comment]
toxopids shred walls, shields, if with an oct are kind of unstoppable unless using lasers, but they can build plastanium walls.
and why cant i use oct technology? it doesnt make sense...

**Comment by RealYeet** [comment]
Bigger force projectors are in the not happening section of the trello. I guess the 3 checks you have to do just don’t apply to you.

**Comment by IxGamerXL** [comment]
Better off making this element part of a mod rather than a wishlist item. Any further dragging is just going to be dead stop towards a let down via Anuke's denial.

**Comment by the-red-soul** [comment]
> ok, 10 toxopids come, what do you do? your dead if u dont have other units, imagine in fungal pass or maze map.

you kill them with foreshadow before they reach the wall. if they do reach the wall you better have max boost fuses and segments on their howitzers.


Shields completely neutralize certain units like quads likewise where plast neutralizes corvus. most units have some form of counter to them other than just pure damage. as for creating strong defences you should be using MENDERS. Menders have ALWAYS outclassed force projectors for ages until quads existed. As for actually having better shields, why not just make quads and have them overtop of your defences, using their shield as the force projector if its really that much of a concern for you?

**Comment by idontknowhwhattoputhere** [comment]
> > ok, 10 toxopids come, what do you do? your dead if u dont have other units, imagine in fungal pass or maze map.
> 
> you kill them with foreshadow before they reach the wall. if they do reach the wall you better have max boost fuses and segments on their howitzers.
> 
> Shields completely neutralize certain units like quads likewise where plast neutralizes corvus. most units have some form of counter to them other than just pure damage. as for creating strong defences you should be using MENDERS. Menders have ALWAYS outclassed force projectors for ages until quads existed. As for actually having better shields, why not just make quads and have them overtop of your defences, using their shield as the force projector if its really that much of a concern for you?

i dunno that didnt work for me...

**Comment by OnyxFinger** [comment]
> 

not just nearly 100%, they ARE 100%
Also this suggestion doesn't make a lot of sense, you can just position an oct where you want the force projector to be.
https://trello.com/c/isxateyq/549-larger-force-projector
I believe it won't get added due to the section that it is in

**Comment by begginerr** [comment]
> > Normal force projectors offer nearly 100% protection against quads and horizons
> 
> not just nearly 100%, they ARE 100% (hopefully it won't change, force projectors are balanced as they are) Also this suggestion doesn't make a lot of sense, you can just position an oct where you want the force projector to be. https://trello.com/c/isxateyq/549-larger-force-projector I believe it won't get added due to the section that it is in

but octs are expensive as heck

**Comment by Kyllingene** [comment]
Oh no, cost balancing! What ever shall we do?
