### ISSUE TITLE
transparent units when building

### ISSUE THREAD

**Issue by user233233** [Anuken/Mindustry-Suggestions#3192]
### Describe the content or mechanics you are proposing.

Units can be transparent while you are building something beneath them

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Big units can always cover everything beneath them so it hard to build or remove buildings around them.With transparent unit,the building can be more convenient and easier without the loss of balance

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ymabert** [comment]
all right, but it would be better if the units become transparent only when the mouse is over them or when a block or even a scheme has selected them all the units become transparent, even the land and marine units, since they too cover the buildings.

**Comment by Kyllingene** [comment]
Hasn't this suggestion been made a hundred times in the recent past, only to be shot down just as many times?

**Comment by EclipseTheOldOne** [comment]
Hasn't this suggestion been made a hundred times in the recent past, only to be shot down just as many times?

**Comment by idontknowhwhattoputhere** [comment]
Y E S
i think this is a great idea!

**Comment by Ymabert** [comment]
this is my first time reading this tip, why is it not implemented yet?  where is the problem I don't understand?

**Comment by itcannotbe** [comment]
> Hasn't this suggestion been made a hundred times in the recent past, only to be shot down just as many times?

Hasn't this suggestion been made a hundred times in the recent past, only to be shot down just as many times?

**Comment by Ymabert** [comment]
ok, now I understand, if it is really a lot of work it makes more sense to move the swarms of units to other parts or you try not to put all the units in one place, especially in the middle of the village.

**Comment by Kyllingene** [comment]
It also raised problems with modded units drawing; I can't remember what exactly, but it would require mod-makers to put in extra effort for compatibility with the feature.

**Comment by 3lgonzalez** [comment]
> Está bien, pero sería mejor si las unidades se vuelven transparentes solo cuando el mouse está sobre ellas o cuando un bloque o incluso un esquema las ha seleccionado, todas las unidades se vuelven transparentes, incluso las terrestres y marinas, ya que también cubren los edificios. .

Y los jugadores de celu?
