### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by elmatii** [Anuken/Mindustry-Suggestions#3194]
### Describe the content or mechanics you are proposing.

Add an easier way to create an online server 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Could increase the number of players online 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1153#issuecomment-725813205

**Comment by Kyllingene** [comment]
1. @itcannotbe, that might not be the most convincing of comments.
2. However, they are right; you already have the dedicated server, if you need a free server just use that (assuming you don't own the Steam version, because that comes with Steam servers that you can easily host and let friends join).

**Comment by itcannotbe** [comment]
Actually games on steam aren't actually dedicated servers. Most of them are games that are hosted by another user that is using the steam version as well, since the steam version has the capability to be helped ouut by steam servers in order to make it others who use the steam version to connect to each other.

**Comment by Kyllingene** [comment]
Sorry, I guess I wasn't clear; I was saying to use the provided dedicated servers, unless they have it on Steam, in which case they should use the Steam server hosting.

**Comment by Den2045** [comment]
Можноли чтоб в процессоре был на русский или английский зависимости от выбранных в  настроеках языка

**Comment by itcannotbe** [comment]
> > Можноли чтоб в процессоре был на русский или английский зависимости от выбранных в настроеках языка

> Translated:

> You can have the processor in Russian or English depending on the language selected in the settings

What?

**Comment by Den2045** [comment]
> 

Чтоб процесор был нарусом (весь роцесор)

**Comment by Den2045** [comment]
> > > Можноли чтоб в процессоре был на русский или английский зависимости от выбранных в настроеках языка
> 
> > Переведено:
> 
> > У вас может быть процессор на английском или английском в зависимости от языка, выбранного в настройках
> 
> Какие?

Че какие /чтоб проц был переведен на русский или англ зависемости выпрованый вами языка в настройках игры

**Comment by itcannotbe** [comment]
> > > > Можноли чтоб в процессоре был на русский или английский зависимости от выбранных в настроеках языка
> > 
> > 
> > > Переведено:
> > 
> > 
> > > У вас может быть процессор на английском или английском в зависимости от языка, выбранного в настройках
> > 
> > 
> > Какие?
> 
> Че какие /чтоб проц был переведен на русский или англ зависемости выпрованый вами языка в настройках игры

What does this have to do with the topic? If you are suggesting something unrelated to the original suggestion, it is better to create your own issue/thread. [New issue](https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose)

**Comment by Den2045** [comment]
> > > > > Можноли чтоб в процессоре был на русский или английский зависимости от выбранных в настроеках языка
> > > 
> > > 
> > > > Переведено:
> > > 
> > > 
> > > > У вас может быть процессор на английском или английском в зависимости от языка, выбранного в настройках
> > > 
> > > 
> > > Какие?
> > 
> > 
> > Че какие / чтоб проц был переведен на русский или англ зависимости выпрованый вами язык в настройках игры
> 
> При чем здесь тема? Если вы предлагаете что-то, не связанное с исходным предложением, лучше создать свою собственную тему / ветку. [Новый выпуск](https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose)

Спасибо я просто нишарю за праграмирование/я зашол сюда чтоб знать что могут дабавить в игру извините за причиненые не удобства
