### ISSUE TITLE
Overdrive unit

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#3195]
### Describe the content or mechanics you are proposing.

units can heal, they can attack, they have shields, they can rebuild...

why isnt there an overdrive unit?
something like this:

t1: 25% boost
t2: 50% boost
t3: 100% boost
t4: 150 boost
t5: 250% boost

possibly named after gond of time.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would add more possibilities, become essential, and would become an extra unit requirement when attacking enemy bases on the 2nd planet.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Overdrive what exactly?

**Comment by Ymabert** [comment]
do you mean a troop that has an overdrive field or do you mean that the overdrive block must have the function of speeding up the troops too?  because in my opinion it is not a good idea to speed up the units, in terms of walk / rate of fire, but if the boost is not 100% but like 25% / 50% I think it can be done.  If you want overdrive troops only increase the range, because otherwise, if you increase the boost it would be too much OP.  So you're asking for overdrive troops, an overdrive block for troops, or does the existing overdrive block affect troops as well?

**Comment by MrDuck557** [comment]
Minke does this to units, but it isn't really expanded on further
If you're talking about doing this to blocks, then probably decently balanced

**Comment by begginerr** [comment]
> do you mean a troop that has an overdrive field or do you mean that the overdrive block must have the function of speeding up the troops too? because in my opinion it is not a good idea to speed up the units, in terms of walk / rate of fire, but if the boost is not 100% but like 25% / 50% I think it can be done. If you want overdrive troops only increase the range, because otherwise, if you increase the boost it would be too much OP. So you're asking for overdrive troops, an overdrive block for troops, or does the existing overdrive block affect troops as well?

he is asking for overdrive troops. he says "why isnt there an overdrive unit?"

**Comment by idontknowhwhattoputhere** [comment]
> Minke does this to units, but it isn't really expanded on further If you're talking about doing this to blocks, then probably decently balanced

minke is my 3nd fav unit now.

**Comment by esteemator** [comment]
A OD field from a unit that works like a mobile OD block may be nice, progression in size and % boost from T1-5, but T5 should not exceed the ODD

**Comment by begginerr** [comment]
> > Minke does this to units, but it isn't really expanded on further If you're talking about doing this to blocks, then probably decently balanced
> 
> minke is my 3nd fav unit now.

actually minke USED to do this to units, but now the effect has been given to oxynoe.
