### ISSUE TITLE
A map rating and labeling system

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry-Suggestions#3198]
### Describe the content or mechanics you are proposing.

Similar to how schematics can be tagged, maps would also benefit from a labelling and rating system. This comprises of two things:

A rating system that the map creator can choose to add, this will be similar to the difficulty rating system campaign maps have, where you can rate a map to be more difficult/easy to play, making it easier for players to know what to expect from a map.

The other thing would be map tags, so you can put tags on the map to indicate playstyles, like schematics have tags for sorting. Things like `resource starve` or `boss rush` to sort of indicate what the map playstyle is. The tags would just be text so anyone can make a tag.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would just help with sorting maps in the map list, as well as making it so finding maps based on difficulty and playstyle becomes a lot easier if you happen to have a lot of maps. 

Along with that, tags are just nice for organising things (as is evident with schematic tags).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Darkness6030** [comment]
It can easy be implemented
