### ISSUE TITLE
Mass Forwarder

### ISSUE THREAD

**Issue by Fabizocker456** [Anuken/Mindustry-Suggestions#3199]
### Describe the content or mechanics you are proposing.

A 2x2 Mass Driver, without accessible inventory (even via unloader), cheaper and more energy efficient, only for forwarding mass driver packets.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would greatly improve the usefulness of Mass Drivers over long distances.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Mass drivers are already useful, why would you need to buff them ?

**Comment by begginerr** [comment]
> Mass drivers are already useful, why would you need to buff them ?

not a buff, just a smaller version of them

**Comment by RFAC-Productions-Reborn** [comment]
So, in the tech tree, this would be before the Mass Driver is unlocked? Small inventory but fast transport?

**Comment by itcannotbe** [comment]
> It would greatly improve the usefulness of Mass Drivers over long distances

How on earth would another block **greatly improve the usefulness** of another block without changing the stats of the already existing block, when the proposed block PERFORMS THE SAME FUNCTIONALITY as the already existing block.

Care to shed some light on the matter?

**Comment by Fabizocker456** [comment]
The block should be able to recieve and send mass driver packets. It should just forward them. It shouldn't act a an endpoint, as mass drivers do. That way, they do not replace mass drivers, they are only used for forwarding. That way, they can be cheaper without throwing off the balance. (Sorry I just realized I didn't write that in the original post)

**Comment by OnyxFinger** [comment]
> not a buff, just a smaller version of them

that looks like a buff

**Comment by itcannotbe** [comment]
OnyxFinger try reading the comments above yours.

**Comment by OnyxFinger** [comment]
> OnyxFinger try reading the comments above yours.

Yeah I did, and I still don't understand the problem. Having a new block, essentially a mass driver, but cheaper, is pretty much a mass driver buff.

**Comment by Fabizocker456** [comment]
Ok. It is a buff, because it increases utility of mass drivers. The forwarder would come after the mass driver in the tech tree and it would require endgame resources, e.g. phase and surge, but in small quantities (5-10). It has no use on its own, and only works with mass driver. It has no accessible inventory, but high turn speed. It works as a proxy, taking mass driver bullets and sending them to other mass drivers or mass forwarders. It cannot be used as mass drivers to in/output items. Any useful setup will have at least 2 mass drivers.

**Comment by itcannotbe** [comment]
> > OnyxFinger try reading the comments above yours.
> 
> Yeah I did, and I still don't understand the problem. Having a new block, essentially a mass driver, but cheaper, is pretty much a mass driver buff.

It only serves to "forward" the mass driver "bullet".
