### ISSUE TITLE
New unit, NOVA.

### ISSUE THREAD

**Issue by TacticalAlpha** [Anuken/Mindustry-Suggestions#320]
**Describe the content or mechanics you are proposing.**
A new unit which upgrades drills to pneumatic and conveyors to titanium automatically and walls as well.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
With this unit, a player will not lose time upgrading the conveyors, walls, and the drills as the unit itself will help him.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Novoidconstell** [comment]
Wouldn't the constant drain on resources become a nuisance? Plus it isn't particularly hard to make the upgrades yourself.

**Comment by TacticalAlpha** [comment]
> Wouldn't the constant drain on resources become a nuisance? Plus it isn't particularly hard to make the upgrades yourself.

**Comment by TacticalAlpha** [comment]
> Wouldn't the constant drain on resources become a nuisance? Plus it isn't particularly hard to make the upgrades yourself.

Fine then, remember, you're not the only guy playing mindustry.

**Comment by Novoidconstell** [comment]
> > Wouldn't the constant drain on resources become a nuisance? Plus it isn't particularly hard to make the upgrades yourself.
> 
> Fine then, remember, you're not the only guy playing mindustry.

To be fair, I only upgrade my drills and conveyors at new sites or if the old sites get destroyed and I almost never upgrade my walls, I build them as titanium. So yes, that was mostly personal opinion.

**Comment by itcannotbe** [comment]
I only upgrade stuff when I actually need them upgraded.

**Comment by Anuken** [comment]
1. There already is a unit called nova in v6.
2. I really don't think always upgrading blocks *automatically* is a good idea. This could be done with logic and existing builder units; there's no need for a special unit to do it.
