### ISSUE TITLE
Add In-game Calculator

### ISSUE THREAD

**Issue by ReshaSD** [Anuken/Mindustry-Suggestions#3200]
### Describe the content or mechanics you are proposing.

It would be nice if the game had an in-game calculator for quick calculations. 

A good example of a PC game is Satisfactory. It has a regular text field for entering commands / messages. You can also enter simple formulas into it and see the result below. Here is screenshots from it:
![image](https://user-images.githubusercontent.com/35744846/142780379-5922f579-9c66-4da7-965b-18d272c2680e.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The presence of such a calculator will allow you not to switch between applications to perform calculations, such as the number of pumps for miners (on Android in my case).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
And how would this be added? You can already do this with logic really easily. There is also little need for a calculator due to the fact that everything is easy enough to calculate.

**Comment by Ymabert** [comment]
The calcolator in the chat?

**Comment by Phinner** [comment]
Doable in Mods or Plugins...

**Comment by ReshaSD** [comment]
Okay, maybe I don't play as much as you do, but I don't remember all the numbers. Right now I'm just going through the campaign and only completed ~ 15 polygons on the planet.

Perhaps people who play a lot already remember "how much sugar is needed per kilogram of yeast", but as for me, I quite often use a calculator, for example: multiply by 2.5, 4.79, 3.6 or to divide by 6.6.

I pictured it as a separate button somewhere in the UI. By clicking on it, a field opens where you can enter something like: `4.79*5/6.6` or `(4.79*3+3.6*2)/6.6` or `8*2.39/6.6`, etc. and see the result right away (yes 6.6 is used quite often :-)). I think that the numbers are familiar to many here and you understand what I'm talking about.

It seemed to me that it would be useful not only for me.

>You can already do this with logic really easily.
If you're talking about the in-game logic processor and what you can calculate with it - that's not what I'm suggesting here. The logical processor is not useful at all in this situation. It's too hard.

**Comment by itcannotbe** [comment]
You forgot you can already eyeball ratios.

Green, add more.
Orange, too much.

**Comment by ReshaSD** [comment]
> You forgot you can already eyeball ratios.
> Green, add more. Orange, too much.

Thanks for this. A good option, I will try.

But it's more like an activity monitor. In my case, it often happens that after the construction of everything on some area. There is nowhere to put anything else. Therefore, I plan and count everything in advance.

**Comment by BlueManedHawk** [comment]
I can see this being useful to mobile players.  Might I add that perhaps the calculator could have some way to quickly type values from the game into the calculator, e.g. throughput of a particular conveyor, output of a material from a block, amount of something necessary for another thing, etc.?
