### ISSUE TITLE
To facilitate switching between modified and vanilla profiles.

### ISSUE THREAD

**Issue by Cyferyn** [Anuken/Mindustry-Suggestions#3201]
### Describe the content or mechanics you are proposing.

Saves slots :D

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's self-explanatory... But this will simply make it easier to switch profiles.
For example:
You are playing alone with many mods, and playing online on servers or friends.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This needs a lot of work though.
