### ISSUE TITLE
BE payload loader not working properly

### ISSUE THREAD

**Issue by BaseModMaker** [Anuken/Mindustry-Suggestions#3202]
### Describe what you would like changed, and why.

The payload loader only loads 200 items, not 300. Before launching the payload, it calculates if it is full. But the calculation also includes the payload loader's inventory (100). 
![Screenshot_20211122_134635_io anuke mindustry be](https://user-images.githubusercontent.com/59204882/142864312-3f702a58-89be-467f-990e-270a6ad8d417.jpg)
The image shows that the container only contains 200 titanium (6 from when the payload was leaving). The version is the BE. 

### Describe the changes you want to propose. Include possible alternatives.

I would propose that the payload loader only lets the payload go if it's truly full (300 instead of 200)

**Comment by RealYeet** [comment]
Bugs is where this should be, not suggestions

**Comment by MrDuck557** [comment]
the explanation is probably backflow
the payload unloader outputs titanium to the payload loader, taking out 100 items from the payload
you're left with 200, which goes into the external container

try spacing out the payload loader and unloader and see what happens

**Comment by itcannotbe** [comment]
> the explanation is probably backflow the payload unloader outputs titanium to the payload loader, taking out 100 items from the payload you're left with 200, which goes into the external container
> 
> try spacing out the payload loader and unloader and see what happens

Explanation checks out. the block unloader filled the block loader because they're directly touching one another.
