### ISSUE TITLE
Effects of being on new planets and asteroids

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry-Suggestions#3203]
### Describe the content or mechanics you are proposing.

There is no way of me knowing if this is already the way things are planned to be, so I'm gonna pretend it's not planned or added.

For new planets, instead of maybe banning things outright, make them work less efficiently, and only ban things if they don't work at all.

For example, if a planet has high gravity, have mass drivers require more energy to fire. If a planet has low gravity, have mass drivers require less energy to fire. If a planet has too low gravity, have mass drivers fail entirely or ban them.

Also, decrease range of weapons that fire bullets in planets with thick atmospheres, and increase the range in thin atmospheres. Slow down air units in thick atmospheres, increase their max speed in thin atmospheres.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It makes more sense, and also encourages the new technologies.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ymabert** [comment]
it would be really complete, but I don't understand what you mean when you say that this would encourage new technologies, I don't understand if you mean it would change everything in a positive way or in a negative way or both.

**Comment by OnyxFinger** [comment]
Makes sense
