### ISSUE TITLE
Allow terrain editing within the editor's "edit-in-game"

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry-Suggestions#3204]
### Describe the content or mechanics you are proposing.

Allow terrain editing **only within the editor's edit-in-game mode.** Basically as an example look at L0615T1C5-216AC-9437/WorldEdit except without the baking part and works only in editor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Map making is an insanely tedious process especially with the design of fort maps because the only real way to copy paste a map with the current editor is the mirror tool. Also could lead to interesting styles of attack map such as the map being designed for enemy structures which currently requires lots of switching between in-game and editor.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
If I'm not mistaking, an editor redesign is planned that will allow you to do that.
This was however not on the trello when I checked, so I am not sure
