### ISSUE TITLE
More logic things

### ISSUE THREAD

**Issue by Rex-Hm** [Anuken/Mindustry-Suggestions#3205]
### Describe the content or mechanics you are proposing.

1. A new type of operation called "int"/"toint" that converts floating to integers.
![image](https://user-images.githubusercontent.com/77251557/143447824-c0cb109f-0f26-4342-b6d5-261560e17cbf.png)
2. Better pathfinding function
A new pathfinding that works by giving you the x and y coordinates.
3. getBlock function
a function that could obtain a block using the coordinates.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. It will be very useful to round numbers and show a better output in the messages.
2. bringing units to a certain location will be much easier this way.
3. to link blocks automatically regardless of the location of the logic block, it would be very useful for certain types of schemes, although it can be very "op", since it breaks the range limit.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
3. getBlock exists
2. Better pathfinding would be nice, but is technically challenging (without costing too much cpu time)
1. the floor function does literally that. It converts floats to ints
