### ISSUE TITLE
icloud sync or save file sharing feature

### ISSUE THREAD

**Issue by dw0216** [Anuken/Mindustry-Suggestions#3206]
### Describe the content or mechanics you are proposing.

Please add icloud sync or save file sharing feature (maually upload and download saves on icloud).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will bring huge improvement on user gameplay experience.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [You lied]  I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by InventionIO** [comment]
i mean its cool but...

**Comment by InventionIO** [comment]
dont actually know why its in the section

**Comment by Rex-Hm** [comment]
bruh

**Comment by Anuken** [comment]
> save file sharing feature (maually upload and download saves on icloud).

You can already do this; I've done it on a real device.

**Comment by dw0216** [comment]
@Anuken where can I find that function on ios?

**Comment by Anuken** [comment]
Export/share the save to Files, transfer it where you want, then open it through Files with Mindustry.

**Comment by dw0216** [comment]
Can you share 'Campaign' save files too?
I cannot find saves for campaign..

**Comment by dw0216** [comment]
Ahh 
While playing campaign, go setting, game data, export?
I couldn't find saves on the main menu so I was confused..
Thank you so much Anuken!!
