### ISSUE TITLE
research laboratory

### ISSUE THREAD

**Issue by PhysicDev** [Anuken/Mindustry-Suggestions#3207]
### Describe the content or mechanics you are proposing.

to research technology the player have to build a research lab then select the coresponding technology and put the ressources in it.
I imagine this block as an optional block like ressuply point. 
there could be multiple research lab for the different level of tech (lab Tier 1 for the copper to the silicon then lab Tier 2 for the titanium to thorium then lab Tier 3 for plastanium to supercharge alloy  etc ...)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this would be very usefull for implementing the tech tree on server because with the actual research system any player can waste ton of ressources in one simple click.
With this building the player will have to build a research lab then put conveyor to it and it will be more manageable for other players in the case of a bad use of it.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Cleanup-Crew-From-Discord** [comment]
why would you need tech tree on a server? that would just slow down the game too much

**Comment by EclipseTheOldOne** [comment]
1. this is a removed in-dev 'feature' (the data processor)
2. suggested many times
3. image lab in multiplayer
4. too many lab sh** it's 3 blocks with only ose uses
> supercharge alloy
*you're
