### ISSUE TITLE
Hidden schematic tags

### ISSUE THREAD

**Issue by MHeMoTexHuK** [Anuken/Mindustry-Suggestions#3208]
### Describe the content or mechanics you are proposing.

A new type of schematic tags — hidden tags. If a schematic has at least one such tag, it's hidden from the list. In order to see such a schematic, you have to select all hidden tags assigned to this schematic (in the search bar)

I.e. if a schematic has a hidden tag named "mod", it remains hidden unless you search for the tag "mod".

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Would allow for better schematic sorting. You wouldn't want to see modden schematics if you're playing vanilla right now, would you?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The better way to go is make it so that exclude: (tag here) is supported

**Comment by oinkymoo** [comment]
ok? the reason mhemotexhuk suggested this is because they had no idea such a feature existed. there should be some indication in-game that such a thing is possible, or a way to do it automatically in-game

**Comment by MHeMoTexHuK** [comment]
> ok? the reason mhemotexhuk suggested this is because they had no idea such a feature existed. there should be some indication in-game that such a thing is possible, or a way to do it automatically in-game

there __is no such feature__. I've checked the "[X] I'm familiar with all the content currently present i the game" for a reason

**Comment by oinkymoo** [comment]
By “such a feature” I was referring to tag exclusion as itcannotbe described it
