### ISSUE TITLE
Payload sorter

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#3209]
### Describe the content or mechanics you are proposing.

In game was added more payload stuff, so I think a sorter is necessary.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Also what about payload junction and bridge? Does it nessesary? We have already Payload Propulsion Tower that can replace them. 
Or maybe we need payload junction and bridge because PPT is expensive to use?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
> payload junction and bridge

payload transporting is pretty late-game, so use payload mass driver

**Comment by IxGamerXL** [comment]
Honestly, having Payload sorters, overflow gates (and their inverted versions), junction and bridge would make things a lot better. Hell, we could even have a payload variant of phase bridges.

In no bias: this is a very good addition of Mindustry.
