### ISSUE TITLE
Uranium

### ISSUE THREAD

**Issue by LightningEngine** [Anuken/Mindustry-Suggestions#3210]
### Describe the content or mechanics you are proposing.

Uranium can be used in making units and weapons that gives acid effect which decreases max health and lowers hp over time.
Uranium is rare and you need a specific drill to have it because if you use any other drill the drill will have the acid effect.
It produces large amount of power if used in a power plant.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think having units that give a acid effect will be great.
I don't have anything else to say.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Uranium can be used in making units and weapons that gives toxic effect which decreases max health and lowers hp over time.

But units and block are machines right?

**Comment by LightningEngine** [comment]
@itcannotbe those are special units and blocks that is made from a metal that doesn't get affected by the toxic effect.
I don't have any idea if what this metal is but I think the creator will think of something if they accepted the idea..

**Comment by OnyxFinger** [comment]
Where as uranium itself has been suggested many times before, this mechanic seemingly hasn't.
Basically, you're asking for an even angrier and stronker version of melting, which may be good. I believe that any burning ammo right now isn't worth it blablabla, but a stronger version of them may be.

**Comment by TheRealIvyX** [comment]
1. thorium exists
2. uranium is overused

something that uses the corroded effect in the vanilla game would be kinda nice tho

**Comment by OnyxFinger** [comment]
> 1. thorium exists
> 
>     2. uranium is overused
> 
> 
> something that uses the corroded effect in the vanilla game would be kinda nice tho

yeah, the name needs to be changed, but the idea isn't necessarily baaddd

**Comment by OnyxFinger** [comment]
Last thing I need to add : There should be a way to buff it's attack damage (like shocked attacks, blasted attack etc..) or to make it buff other attacks, else it's just not good.

**Comment by LightningEngine** [comment]
I didn't know uranium was suggested so many times...sorry.

**Comment by TheRealIvyX** [comment]
i meant "uranium is generally overused in industry-type games and mods for other games" not as in it has been suggested alot but that its generally extremely overused in industry-types games like mindustry, factorio, etc. and even industry-type mods for other games such as immersivengineering for minecraft, making mindustry kinda unique by having thorium instead of uranium

**Comment by itcannotbe** [comment]
> Where as uranium itself has been suggested many times before, this mechanic seemingly hasn't. 

#2757

**Comment by LightningEngine** [comment]
> 

Oh

**Comment by Cleanup-Crew-From-Discord** [comment]
isnt acid just the melting affect? reduces max health and deals damage while also slowing
also do not suggest uranium or your suggestion is already bad. we have thorium bc uranium is too generic

**Comment by SMOLKEYS** [comment]
> I didn't know uranium was suggested so many times...sorry.
> And there is 3 dislikes. Why.

~~41 in the main discord.~~

**Comment by Bassem-Const** [comment]
> uranium is too generic

Same reason we have copper instead of iron.

**Comment by GitHubUser-B** [comment]
> I didn't know uranium was suggested so many times...sorry. And there is 3 dislikes. Why.

Because a good part of the people who respond to suggestions are harsh and arrogant, sorry...

**Comment by itcannotbe** [comment]
> > I didn't know uranium was suggested so many times...sorry. And there is 3 dislikes. Why.
> 
> Because a good part of the people who respond to suggestions are harsh and arrogant, sorry...

Joke is on you. He got what we meant and modified his suggestion via edits on comments and the original post.

**Comment by GitHubUser-B** [comment]
> > > I didn't know uranium was suggested so many times...sorry. And there is 3 dislikes. Why.
> > 
> > 
> > Because a good part of the people who respond to suggestions are harsh and arrogant, sorry...
> 
> Joke is on you. He got what we meant and modified his suggestion via edits on comments and the original post and expressed his understanding via reacts.

 I would just like you to explain why the suggestion is bad with more "gentleness"

**Comment by itcannotbe** [comment]
> > > > I didn't know uranium was suggested so many times...sorry. And there is 3 dislikes. Why.
> > > 
> > > 
> > > Because a good part of the people who respond to suggestions are harsh and arrogant, sorry...
> > 
> > 
> > Joke is on you. He got what we meant and modified his suggestion via edits on comments and the original post and expressed his understanding via reacts.
> 
> I would just like you to explain why the suggestion is bad with more "gentleness"

Point out who and what comment on this issue thread became offensive for you.

**Comment by GitHubUser-B** [comment]
> > > > > I didn't know uranium was suggested so many times...sorry. And there is 3 dislikes. Why.
> > > > 
> > > > 
> > > > Because a good part of the people who respond to suggestions are harsh and arrogant, sorry...
> > > 
> > > 
> > > Joke is on you. He got what we meant and modified his suggestion via edits on comments and the original post and expressed his understanding via reacts.
> > 
> > 
> > I would just like you to explain why the suggestion is bad with more "gentleness"
> 
> Point out who and what comment on this issue thread became offensive for you.

Passive aggressive comments, indirect offenses,  directly "criticize" the person etc, I don't know who are the people that have done this kind of thing, there are many.

**Comment by LightningEngine** [comment]
What happened here.

**Comment by itcannotbe** [comment]
> What happened here.

Typical GitHubUser-B behavior.

> > Point out who and what comment **on this issue thread** became offensive for you.

> Passive aggressive comments, indirect offenses, directly "criticize" the person etc, I don't know who are the people that have done this kind of thing, there are many.

Where exactly?

**Comment by GitHubUser-B** [comment]
> > What happened here.
> 
> Typical GitHubUser-B behavior.
> 
> > > Point out who and what comment **on this issue thread** became offensive for you.
> 
> > Passive aggressive comments, indirect offenses, directly "criticize" the person etc, I don't know who are the people that have done this kind of thing, there are many.
> 
> Where exactly?

Almost all suggestions

**Comment by RickAstly** [comment]
Pretty much every issue on this github ends the same way: a quote fight between GithubUser-B and itcannotbe that takes the discussion off topic.

I do not support the adding of uranium per se, and I think we have enough status effects, but an "acid effect" would be cool.

**Comment by GitHubUser-B** [comment]
> Pretty much every issue on this github ends the same way: a quote fight between GithubUser-B and itcannotbe that takes the discussion off topic.
> 
> I do not support the adding of uranium per se, and I think we have enough status effects, but an "acid effect" would be cool.

Lol, never gonna give you up.
