### ISSUE TITLE
Logic Warfare (Viruses, Hijacking, DDOS...)

### ISSUE THREAD

**Issue by CreebotTheGreat** [Anuken/Mindustry-Suggestions#3212]
### Describe the content or mechanics you are proposing.

The idea is to make a branch of logic that focuses on digital warfare to expand the way the game can be played. 

Let's say there is an enemy base with logic, and it is ordering Monos to mine copper and deposit it to a vault that will distribute it to whatever. 

Now, you can use the "Virus Injector", a custom unit that is stored in the "Virus Writer" block when it is built. 
When you control the Virus Writer block, you can get out of it as the Virus Injector. Be careful, this unit cannot build or fight and can be shot down! It sports a weak shield. When close to a logic block able to receive signals, it will begin transmitting whatever Virus you chose to the enemy processor. As a result (for example), instead of delivering copper to the enemy vault, the enemy monos join your side and begin delivering copper to your core.

It has a limit though. The Virus Injector has a limited time use, as the hack will have a default duration of 1 minute, and can last even less if the enemy has built an antivirus system in their logic contraption.

firewalls and antiviruses are two other blocks, the Firewall is good at preventing large attacks while Antiviruses are better at stopping more vicious and targeted attacks with dire consequences.

Types of hacks, consequences and counters:

Hijack - This is the example i've given before. You can hijack temporarily the enemy units and turrets. Attention, it sounds OP but has a lot of downsides, for example, limited hijack depending on your current level of Virus Writer (i think Level 1 should have around 8 hijack slots), Tier 4 and upper units have resistance to hacks, Enemy turrets will shoot at the hijacked troops...

DDOS - As simple as it sounds. Unleash so many code requests to the enemy that the units go haywire. They will not count as hijacked, and wimply will do random bullcrap.

MITM - See what is planned and read the enemy code for a limited time.

Trojan - Do some wacky stuff in the enemy's networking, such as negating hacks or even commanding troops to attack (via the enemy's command station) unprepared (e.g. Avoid gathering), or have them get recalled/go idle. 

I ran out of ideas, but there's probably more that could be mentioned.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content request could add an interesting aspect of multiplayer or even campaign experience, without forcing it, as you could totally avoid logic stuff in your base. There are very interesting and tide-turning shenanigans to be done! Communities of players who are more prone to do some crazy stuff with hacks may form and develop new playstyles, and overall it might be an interesting addition.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Just make a legitimately useful/cool logic program with some hidden trigger or backdoor, and hope that people on the enemy team mindlessly copy it

could be as simple as disabling turret ammo delivery, or something as evil as clogging conveyors

**Comment by itcannotbe** [comment]
Isn't this too powerful no matter how you nerf it?

**Comment by CreebotTheGreat** [comment]
> Just make a legitimately useful/cool logic program with some hidden trigger or backdoor, and hope that people on the enemy team mindlessly copy it
> 
> could be as simple as disabling turret ammo delivery, or something as evil as clogging conveyors

Judging by your logic, might as well assume everyone is an idiot and play the game using only baiting techniques.

**Comment by CreebotTheGreat** [comment]
> Isn't this too powerful no matter how you nerf it?

Firewalls and Antiviruses negate direct effects and narrow down the duration of indirect effects

for example, hijacking can be totally avoided if the antivirus is up to date and same level as the enemy's virus, and reading into the enemy code remotely can be brought down to a duration of just a few seconds. Not enough to go through the whole functioning, and if it is enough, then the coding probably isn't so important.

**Comment by random-guy1285** [comment]
The game is focused on physical combat, and I believe most of the community wishes it to stay that way.
Either way, if implemented, this would need to be **HEAVILY** refined as at its current state, it's not the best.

**Comment by itcannotbe** [comment]
> > Isn't this too powerful no matter how you nerf it?
> 
> Firewalls and Antiviruses negate direct effects and narrow down the duration of indirect effects
> 
> for example, hijacking can be totally avoided if the antivirus is up to date and same level as the enemy's virus, and reading into the enemy code remotely can be brought down to a duration of just a few seconds. Not enough to go through the whole functioning, and if it is enough, then the coding probably isn't so important.

It only takes a few seconds to decimate a base.

**Comment by Bottinator22** [comment]
This is Mindustry, a combat-oriented factory game, with barely any ways for processors to communicate

**Comment by Kyllingene** [comment]
This really doesn't fit in. If you want virus-based warfare, go find such a game or make it yourself (clearly you like programming).

If you think this fits in, notice that this introduces direct control over enemy units and buildings, something that has been decided against time and time again (not to mention that your suggestions are horrendously overpowered). It would also render non-logic users at a huge disadvantage, because they would have to rely on pricier user-friendly schematics instead of bare-bones custom-made logic.

**Comment by Bottinator22** [comment]
Logic was added as a feature to the game. It is not the game.

**Comment by CreebotTheGreat** [comment]
> The game is focused on physical combat, and I believe most of the community wishes it to stay that way. Either way, if implemented, this would need to be **HEAVILY** refined as at its current state, it's not the best.

After all i'm not the game creator.

Also, if people want it to stay it that way, that's simple cause as said, you can totally avoid it.

**Comment by CreebotTheGreat** [comment]
> This really doesn't fit in. If you want virus-based warfare, go find such a game or make it yourself (clearly you like programming).
> 
> If you think this fits in, notice that this introduces direct control over enemy units and buildings, something that has been decided against time and time again (not to mention that your suggestions are horrendously overpowered). It would also render non-logic users at a huge disadvantage, because they would have to rely on pricier user-friendly schematics instead of bare-bones custom-made logic.

I've thought of a logic block that "closes your network", making you 100% immune to the enemy's attempts but as a counterpart not letting you hack them either.

**Comment by itcannotbe** [comment]
> > This really doesn't fit in. If you want virus-based warfare, go find such a game or make it yourself (clearly you like programming).
> > If you think this fits in, notice that this introduces direct control over enemy units and buildings, something that has been decided against time and time again (not to mention that your suggestions are horrendously overpowered). It would also render non-logic users at a huge disadvantage, because they would have to rely on pricier user-friendly schematics instead of bare-bones custom-made logic.
> 
> I've thought of a logic block that "closes your network", making you 100% immune to the enemy's attempts but as a counterpart not letting you hack them either.

So thren both sides just constructs the block making this suggestions even pointless to begin with

**Comment by CreebotTheGreat** [comment]
> > > This really doesn't fit in. If you want virus-based warfare, go find such a game or make it yourself (clearly you like programming).
> > > If you think this fits in, notice that this introduces direct control over enemy units and buildings, something that has been decided against time and time again (not to mention that your suggestions are horrendously overpowered). It would also render non-logic users at a huge disadvantage, because they would have to rely on pricier user-friendly schematics instead of bare-bones custom-made logic.
> > 
> > 
> > I've thought of a logic block that "closes your network", making you 100% immune to the enemy's attempts but as a counterpart not letting you hack them either.
> 
> So thren both sides just constructs the block making this suggestions even pointless to begin with

Except for people who want it.

Going by your logic, mindustry itself is pointless then, since most people in the world wouldn't want to play it.

**Comment by Darkness6030** [comment]
👀

**Comment by Bottinator22** [comment]
> > > > This really doesn't fit in. If you want virus-based warfare, go find such a game or make it yourself (clearly you like programming).
> > > > If you think this fits in, notice that this introduces direct control over enemy units and buildings, something that has been decided against time and time again (not to mention that your suggestions are horrendously overpowered). It would also render non-logic users at a huge disadvantage, because they would have to rely on pricier user-friendly schematics instead of bare-bones custom-made logic.
> > > 
> > > 
> > > I've thought of a logic block that "closes your network", making you 100% immune to the enemy's attempts but as a counterpart not letting you hack them either.
> > 
> > 
> > So thren both sides just constructs the block making this suggestions even pointless to begin with
> 
> Except for people who want it.
> 
> Going by your logic, mindustry itself is pointless then, since most people in the world wouldn't want to play it.

"Except for the people who want it"
You said the block was a hard counter to this, and also blocks your own team from hacking. Either team placing it makes the entire suggestion pointless.

**Comment by SMOLKEYS** [comment]
~~Add up the fact that there isn't any instance of enemy bases using any form of logic procs.~~

**Comment by GitHubUser-B** [comment]
~I'll put marked text just to draw attention~

**Comment by GitHubUser-B** [comment]
> ~Add up the fact that there isn't any instance of enemy bases using any form of logic procs.~

~I'll put marked text just to draw attention~

**Comment by Bottinator22** [comment]
Someone really posted some messages here to stop it from being closed or something

**Comment by itcannotbe** [comment]
Should that someone need to get nerfed like what happened to bohaska?

**Comment by Bottinator22** [comment]
Yes , they likely a troll
