### ISSUE TITLE
Ground Unit Movement Improvement

### ISSUE THREAD

**Issue by FlankMD** [Anuken/Mindustry-Suggestions#3213]
### Describe what you would like changed, and why.

Ground units like Fortress are too difficult to guide (on close quarters maps, like Overgrowth) when you control a group of them manually, they stuck on whatever they got in front of them.

### Describe the changes you want to propose. Include possible alternatives.

Maybe if those units follow your controlled unit the same way they move when attacking, this problem would be resolved

**Comment by MrDuck557** [comment]
do you mean pathfinding?
This has been suggested many times before, it is impossible to implement without running an expensive pathfinding calculation every time the player moves

**Comment by Kyllingene** [comment]
See [Anuke/Mindustry#4324](https://github.com/Anuken/Mindustry/pull/4324).

**Comment by ChronusBoogaloo1** [comment]
Could a formation changer be implemented? One formation could be the current circle of units around the player, and the second could just be a game of following the leader, a conga line if you will. It would not be defensively viable, but it could/would make unit transportation easier to manage.

**Comment by ChronusBoogaloo1** [comment]
if foo's client can make and ground units pathfind from point a-b and avoid turrets without almost any delay, couldn't it just be coded similarly for ground units to avoid terrain like the plague similar to how air units avoid anti-air turret's ranges?

**Comment by Kyllingene** [comment]
1. Does foo's client run on mobile?
2. Making air units avoid turrets is much simpler than pathfinding around terrain, but I'm not familiar enough with the client to comment.

**Comment by ChronusBoogaloo1** [comment]
it appears to be on android, ios, and desktop

**Comment by Kyllingene** [comment]
Have you tried it on mobile? My bet is that it either doesn't use full pathfinding, or it's super slow on mobile.
