### ISSUE TITLE
More water tile variants 

### ISSUE THREAD

**Issue by ChronusBoogaloo1** [Anuken/Mindustry-Suggestions#3214]
### Describe the content or mechanics you are proposing.

I am proposing the addition of more water tiles such as Metal Floor 1-4, Dark Panel 1-6, Dacite/Holostone, Shale, Snow, IceSnow, and Ice to either all have varients that are submerged. similar to Sand Water and Dark Sand Water. This could work on the ore-layer, or be it separate tile entirely. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While it may not be a groundbreaking change such as v5-v6, I could see it opening up smoother transitions and higher quality map design with textures that blend and do not sharply change from tile to tile. This could open new opportunities and ideas to map designs too. For example, the city I live in has a large concrete flume going through the center of it that prevents the river from eroding away from the middle of the town. Submerged variants could open possibilities of flooded areas and some other neat ideas that I am not creative enough to think of on the spot. Even if these tiles only worked at 50% efficiency of a regular Water or Deep Water tile, I believe that the aesthetic would help bring the immersion or enjoyment of maps up drastically. 
These tiles could be their separate tiles such as Dark Sand and Dark Sand Water. or it could be a transparent sprite that acts somewhat like an ore tile, and can be put over already existing tiles. 
The idea of how the water would work on the ore-layer is courtesy of Discord user Atoba Azul#8394
Thank you for your time, and I hope that this may help you in your endeavors. :)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Rex-Hm** [comment]
yes please

**Comment by LightningEngine** [comment]
Great idea

**Comment by IxGamerXL** [comment]
This would definitely work. It'll likely be less complicated if water became an ore-layer tile (since you can't really place ores on top of water tiles to begin with last time I checked). it'll definitely be more versatile, thats for sure.

**Comment by OnyxFinger** [comment]
yeess pleeeaaaassseeee

**Comment by ChronusBoogaloo1** [comment]
you actually can put ores on water, or water underneath ores using the scatter or blend generation tool.
