### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Cieteu** [Anuken/Mindustry-Suggestions#3215]
### Describe the content or mechanics you are proposing.

After the first planet in mindustry, I propose first, for example. then I suggest you make a whole planetary system, about 2-4 planets, you will do as many as you want Unfortunately, I did not manage to make as many maps that would be for each sector, but I suggest to simply make large sectors on each planet that could generate themselves, but according to a specific pattern. Only bigger ones would be planned. A little bit more about planets, in general my vision of planets is this: they would be divided into planets of a given biome, jungle, temperate zone, spore zone, etc.

all the planets would look something like this:
-winter (the easiest one, we will do it first),
- moderate zone (something similar to the planet from previous updates, more difficult planet, unlocked after conquering the entire winter)
-jungle,
-spore planet (dead planet, very difficult to traverse),
-water planet (covered with almost all water and pen, a lot of carbon on the surface),
- enemy planet (planet completely conquered by the enemy, one of the most difficult, unlocks after conquering all other planets).

Other update ideas include:
- even larger dividers,
-better mass catapults (for items),
- better conveyors,
-pipe sorters,
- the possibility of mixing liquids,
-multiplayer development,
-larger map sizes,
- the ability to make larger diagrams.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think my ideas will help to diversify the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
isn't Anuke alreadly planning on adding new planets and astroids to the game

not the exact way you explained though

**Comment by OnyxFinger** [comment]
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> 
>     * [ ]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

Yup, you have definitely not read it.

**Comment by Cieteu** [comment]
OnyxFinger i think you dont see i change this, now is says i dont read trello

**Comment by Cieteu** [comment]
and for a reason i planned this other way

**Comment by Kyllingene** [comment]
The checkboxes are to tell you that you *should not open this issue if you haven't done one of them.* Therefore, you shouldn't have opened this issue, and you should close it.
