### ISSUE TITLE
More "Unit Locate" Options for Buildings

### ISSUE THREAD

**Issue by BovineShaman** [Anuken/Mindustry-Suggestions#3216]
### Describe the content or mechanics you are proposing.

Allow bound units to locate more buildings via "Unit Locate" such as walls, processors, distribution blocks (conveyors, routers). 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add more possible functions for processor-controlled units in-game, which I imagine players that use logic a lot would appreciate. 

One thing I wanted to try to make was a schematic that, when placed down, would bind to the poly unit, and then try to build titanium conveyors anywhere they locate a normal conveyor. A similar thing could potentially be done with walls.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
You didn’t check trello and you didn’t check previous suggestions (has been suggested a few times already)

I’m not against your suggestion, it’s just quite unlikely to be accepted

(you can use getBlock as a workaround sometimes)

**Comment by BovineShaman** [comment]
I did check the Trello, I may have missed something. I forgot closed issues exist therefore I did not see #1260 or #1242 or #974.
I see them now, and after seeing why #1242 was closed, I'm gonna close this one too.

**Comment by oinkymoo** [comment]
duplicates are allowed
