### ISSUE TITLE
A new possible unit for asteroids 

### ISSUE THREAD

**Issue by Sumodo** [Anuken/Mindustry-Suggestions#3217]
### Describe the content or mechanics you are proposing.

Flying units such as the flare may not work in space so why not add a new 3 legged unit that could not be lifted by air units and break down blocks to get sand or coal. If conveyers do not work on asteroids they could have a higher cargo capacity like that of a vault.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A new unit that could only be used on exo planets as they are to heavy to move on the main planet , a portable vault  with limited defence capabilities until t3

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
When you realize that it's already planned.

**Comment by end-me-please** [comment]
I thought flying units can still operate in low gravity?
