### ISSUE TITLE
Haptic feedback iOS

### ISSUE THREAD

**Issue by thedimas3007** [Anuken/Mindustry-Suggestions#3218]
### Describe the content or mechanics you are proposing.

Add different haptic feedbacks when shooting from turrets/units on iOS

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be more realistic to shoot from turrets/units

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by fadedmax** [comment]
obv this should be on a setting but i see no problem with it otherwise.
