### ISSUE TITLE
Configurable Power, Liquid, and Item Sources

### ISSUE THREAD

**Issue by Cleanup-Crew-From-Discord** [Anuken/Mindustry-Suggestions#3219]
### Describe the content or mechanics you are proposing.

Either add a new power source or change the existing one so power output can be edited in the source itself as a value from 0 to 1 million.

In addition, add these changes to item sources and liquid sources, but not scaled to 1 million. I'm not sure how much more complicated it would be 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It allows for more versatility and will make it easier to test power saving schematics / logic, and it's more precise and simple than setting up generators to make a certain amount of power.
Also configurable item sources could allow for better testing with ratios and liquid sources could be used for slowing inputs to stress test liquid based designs.
### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
same for power void? would be even better tbh

**Comment by itcannotbe** [comment]
There are a lot of Mods already can do this.

**Comment by Cleanup-Crew-From-Discord** [comment]
> A lot of Mods can already do this.

Should still be a vanilla feature. If it's so simple to implement and very helpful it should be added. EG: plast belts

**Comment by IxGamerXL** [comment]
> A lot of Mods can already do this.

Only issue is that mods cannot be used in multiplayer unless they are Multiplayer supported. Unless you like playing alone alot, it won't effectively work. This being a great feature for vanilla shouldn't be left out.


I think we should also have configurable Item Sources and Liquid Sources so you can change how fast they can output items (good for instantly filling vaults and tanks in sandbox)

**Comment by Cleanup-Crew-From-Discord** [comment]
> I think we should also have configurable Item Sources and Liquid Sources so you can change how fast they can output items (good for instantly filling vaults and tanks in sandbox)

Yeah same here

**Comment by Cleanup-Crew-From-Discord** [comment]
Updated it

**Comment by Cleanup-Crew-From-Discord** [comment]
>so you like testing in multiplayer?
This could also be used for things like enemy bases on multiplayer servers, same with configurable liquid and item sources

**Comment by itcannotbe** [comment]
> > so you like testing in multiplayer?
> 
> This could also be used for things like enemy bases on multiplayer servers, same with configurable liquid and item sources

How? To make them weaker?

**Comment by IxGamerXL** [comment]
> > > A lot of Mods can already do this.
> > 
> > Should still be a vanilla feature. If it's so simple to implement and very helpful it should be added. EG: plast belts
> 
> That wasn't even a mod in the first place.
> 
> > > > It allows for more versatility and will make it easier to test power saving schematics / logic, and it's more precise and simple than setting up generators to make a certain amount of power.
> Also configurable item sources could allow for better testing with ratios and liquid sources could be used for slowing inputs to stress test liquid based designs.
> > >
> > > A lot of Mods can already do this.
> >
> > Only issue is that mods cannot be used in multiplayer unless they are Multiplayer supported. Unless you like playing alone alot, it won't effectively work. This being a great feature for vanilla shouldn't be left out.
> 
> So you like testing in multiplayer?

If we have customizable sources we can make custom machines that produce power, pretend drills, and even machines that actually consumes power to run (something i wished for right out of the bag), and often that'll be useful for RPs. So no, not just testing, but if you wanted to test schems in multiplayer, you can do that too.

I myself play sandbox multiplayer, and people will often roleplay as something fun to do. This feature will definitely pack a plethora of new capabilities, especially since sources and voids can already be toggled on and off with logic processors.

**Comment by IxGamerXL** [comment]
> same for power void? would be even better tbh

@Cleanup-Crew-From-Discord You should also add this to the root thread.

Power voids would constantly consume infinitely, or you can modify them from a scale of 0 to 1 million.

Item voids would play differently. They would have a consumption rate, set to INF by default. Any value below would change it to count/s. So by defining the count variable, this is how many items it'll be able to consume per second. If it reaches the threshold, it will essentially disable itself until it can continue consuming items. Liquid voids would act just about the same way.

For people who want to make custom machines and such, this would also be nice.

**Comment by seung882** [comment]
> > > A lot of Mods can already do this.
> > 
> > 
> > Should still be a vanilla feature. If it's so simple to implement and very helpful it should be added. EG: plast belts
> 
> That wasn't even a mod in the first place.
> 
> > > > It allows for more versatility and will make it easier to test power saving schematics / logic, and it's more precise and simple than setting up generators to make a certain amount of power.
> > > > Also configurable item sources could allow for better testing with ratios and liquid sources could be used for slowing inputs to stress test liquid based designs.
> > > 
> > > 
> > > A lot of Mods can already do this.
> > 
> > 
> > Only issue is that mods cannot be used in multiplayer unless they are Multiplayer supported. Unless you like playing alone alot, it won't effectively work. This being a great feature for vanilla shouldn't be left out.
> 
> So you like testing in multiplayer?

I don't see why it shouldn't be implemented because its already a mod.
It's useful when you're testing schematics, and how much power they need to startup. Impacts, thors etc. Having to purposefully startup generators in sandbox for the sake of testing I think is unnecessary, and even then you can't get really specific values.
