### ISSUE TITLE
[QOL] Allow selected schematics to be queqed for building multiple times.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#322]
**Describe what you would like changed, and why.**
Currently once you have quequed a schematic it clears it immediately. What am I proposing is the ability to place it down multiple times and let the player clear the selection manually.

**Describe the changes you want to propose. Include possible alternatives.**

See above.
And I understand there are players who would like to clear the selection immediately so a keybind for desktop and a button for mobile should be added as well as a toggle option in the setttings.

**Comment by potatoisagender** [comment]
hm? I'm a little confused.

**Comment by Katsute** [comment]
On mobile when you copy a schematic it clears after the first place; unlike desktop where once you copy a schematic you can paste it unlimited times

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
