### ISSUE TITLE
Power Connections Across Adjacent Sector Borders

### ISSUE THREAD

**Issue by BlofeldReturns** [Anuken/Mindustry-Suggestions#3220]
### Describe the content or mechanics you are proposing.

Hey Anuken!
Terribly sorry to bother you if someone already suggested this. One time I suggested cross-sector conveyor belts, and that got shot down, and this is in a similar vein.
So, I know Mindustry doesn't have a _huge_ amount of parallels to real life, but one thing is (sort of) the same: Power. It gets manufactured at one location (preferably close to a fossil fuel source), and then gets transported over distances.

Then you might not be able to produce enough power from the coal/thorium patches you have available. You can easily import whatever raw materials you need from a central storage sector, but power? Nope.

Here is where cross-sector power connections would help.
How I envision it:
1.) The sector must be captured and not be adjacent to an enemy base
2.) You have to construct a certain amount of 'pylons' between one sector and another, these are immaterial and off-screen.
3.) You must have built that unit which is the 1st upgrade of the basic mining unit. They will be the ones to fly off-screen and construct the pylons.
4.) You only see the one on the border of your sector, with its power connection leading off in the compass direction of the target sector. This is the only pylon which you build yourself.  The 'immaterial' pylons are built by the drone unit. It picks up materials for the pylons from the core, then flies off the map border and disappears. 
5.) Once the progress bar gets to 100%, the 'end' pylon is automatically constructed in the target sector.

In this version of the proposal, there is only 1 new building and 1 new functionality;
1.) The start pylon (which has an interaction menu to select which sector to make the pylons to and to assign a unit to build them), able to handle up to ~20 power connections
2.) The functionality of support units to pick up materials automatically + fly off-screen 

I have no idea how expensive each 'pylon' would be; somewhere in the region of 200 - 300 Titanium/100 Silicon/500 Copper 50 Plastanium per? That part is absolutely not my decision to make.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The whole real-world power dynamic is represented on the small scale in-game. Single drill > belt > small combustion generator > power network.
And, as always with a limited map size, there is a limit to how much power you can generate.
This, in turn, limits the scale of whatever industry you are trying to build, without really cramming things in.
People have worked around this since the game's launch, but, in the future, if any of these things were to be added:

- Launchable cores / turrets
- Even bigger units / turrets
- Factories which have higher output but more material/power demand
- Things which simply need a lot of power (I know you're never going to add something like a maglev train, but hypothetically, its electromagnets would need a ton of consistent power)

In conclusion, though this is not something which is strictly necessary to add to the game, _if_ some of the above things were added, it might expand the scale of what you can build in each sector. I'm thinking of truly massive factory complexes, but maybe that's beyond the scale of this game.

Thanks, 
Blofeld_Returns
aka Jeb T. Firefly

p.s. You're doing an amazing job with this game, Anuken :) Make sure not to tire yourself out.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
you do know how much power impact reactors make
you don't feasibly need more than that

**Comment by Ruichka** [comment]
> Then you might not be able to produce enough power from the coal/thorium patches you have available. You can easily import whatever raw materials you need from a central storage sector, but power? Nope.

what does prevent you from launching fuel items into the target sector and placing power production here

**Comment by BlofeldReturns** [comment]
> 

Probably not. I've never gotten to the point of an impact reactor yet. That's exactly why I'm saying this is not an immediate suggestion. Were the game to expand in scope, and mineral patches didn't follow suit or simply couldn't provide enough power, then this might find some niche.

Heck, in 7.0, we'll be able to use Mass Drivers to shoot around blocks - maybe we could do the same for Launchpads & Batteries.

**Comment by BlofeldReturns** [comment]
> > Then you might not be able to produce enough power from the coal/thorium patches you have available. You can easily import whatever raw materials you need from a central storage sector, but power? Nope.
> 
> what does prevent you from launching fuel items into the target sector and placing power production here

Absolutely nothing.
Y'know, I'm starting to see your points... 
This whole thing was a waste of time.
Closing.

**Comment by EclipseTheOldOne** [comment]
he realize, how amazing

**Comment by Bottinator22** [comment]
also you don't need to write it like a whole official legal letter

this isn't that professional

**Comment by Falling10fruit** [comment]
This sounded like a cool idea

**Comment by BlofeldReturns** [comment]
> also you don't need to write it like a whole official legal letter
> 
> this isn't that professional

Sure, it may not be that professional a topic, but I prefer to be professional anyways. Makes it easier to read, at least.
What's the alternative - sentences without any page breaks, bullet points, capitalization, punctuation... without any character at all? I'm of the opinion that you should write how you talk, and generally, most people have _inflection_, they have _tone_, they have varying power in their voices. They don't vomit out sentences in tonelessly flat and dull.

That's just my opinion, though - this GitHub isn't a place to discuss online typography. 
Have a nice day.
