### ISSUE TITLE
Core units in asteroid sectors

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3221]
### Describe the content or mechanics you are proposing.

The core units in the asteroid area should be a crawler-like unit but cannot explode. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There are little to no gravity in space sectors. If the core unit is crawler-like unit then it can be tightly onto the ground.
Spiders usually can stick on items, that means the crawlers wont get blown away. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
How would you travel between asteroids?

**Comment by GuestUser25** [comment]
> How would you travel between asteroids?

Little booster from behind to boost it to other asteroids(like quasar or pulsar)

**Comment by Bottinator22** [comment]
But if you're using a booster, what's the whole point of not using normal
core ships?
