### ISSUE TITLE
Ideas for possible insectoid air and naval units.

### ISSUE THREAD

**Issue by CreebotTheGreat** [Anuken/Mindustry-Suggestions#3222]
### Describe the content or mechanics you are proposing.

Before i go, i want to point out that i am aware of the following factors :

- Unit requests are often refused/closed.
- The trello says that V7 has units planned. However, it is a secret, so apologies if these are already planned. 
- There are things that can't be done with units.
- This idea might get downvoted to hell.

Note that this is more of an interpretation of what could be, but i also posted it as a suggestion should you like the idea, or get inspired by it.

Hello Anuke, i would like to give you the ideas i have had for potential air and naval units that follow the same "insectoid" line as ground does this far. These are more aggressive, and for example, while the regular air units rather attack the electricity network, the insectoid will rather attack defenses first.

First off, let's start with air insectoid.

Tier 1 - Buzzer - A relatively fast, small aircraft unable to directly attack. Upon encountering an enemy or an obstacle, it will let itself fall on it like a suicide bomber. Has less damage than a crawler to compensate for it's great mobility. Will target the closest enemy-built object as to not rush directly to the core. Upon being shot down, the resulting explosion does damage to enemy buildings and troops that are in the falling zone. Great decoys as well. Their building cost is 5 silicon and 15 coal. To discourage players to rush to the enemy core by controlling multiple Buzzers, their explosion trigger off that of nearby buzzers upon being shot down, and very little damage to the enemy structures will be done.

Tier 2 - Swarmer - A bit slower but featuring a slag bomber. It doesn't do a lot of damage alone but it comes with the fire hazard. These troops will attack turrets first. Might need support from regular air units.

Tier 3 - Soldier - A bigger, pretty slow but sturdy attacker. It drops larger slag bombs but at a slower rate and shoots little oil bullets that form a short lasting oil puddle on impact. they will attack defenses first, and are not very potent when they are alone or when the enemy has great defense. The oil puddles make it easier to start fires, but since they are blocked by walls, these must be taken care of before the soldier can even begin lighting the enemy defenses ablaze. 

Tier 4 - Queen - This unit is rather peculiar as it cannot attack. It boasts a shield, but unlike the oct, it can also produce buzzers. It will produce 1 buzzer every 6, 7 or 8 seconds, might need testing to see if it's balanced. By default, the produced Buzzers will go attack, but obviously you can press g to rally them around you. The Queen can have 4 other aircrafts around it, but if it's swarmers, up to 7 can be together. When 7 buzzers are alive, production will stop. When not player-controlled, they'll stay away. 

Tier 5 - Hive Mind - This unit is pretty big, i'd say corvus sized. It's main weapon fires successive spews of slag that land randomly in a spread manner, though they are stopped by anything on the way. it has two secondary weapons that cyclically fire smaller AOE shells that are about half or a quarter of a toxopid's in terms of size and damage. The hive mind produces 1 buzzer every 5 seconds and can control up to 5 regular or support air units, or up to 10 if they are insectoid ! Warning, it cannot have more than one queen and cannot have another Hive Mind following it around. It can pick up and drop ONE ground unit of any tier. just one, even if it's a crawler. it cannot carry naval units.

Phew ! Still here ? Now onto the naval insectoid units ! These focus on erratic and unconventional tactics to confuse the enemy.

Tier 1 - Spawn - This is yet another non-attacking suicide. They look like naval mines, and they are pretty fast and do enough damage to take 3/4 of a small copper wall's health at once. They are pretty efficient against low tier enemy laval units but aren't potent for tier 3 and above enemies. They cost 5 lead, 5 metaglass and 10 coal to build. They target anything close.

Tier 2 - Tadpole - This unit is really fast, and uses a focusing ray that gradually drains enemy life for themselves. Alone, they are pretty impotent. But more of them might be a problem for unprotected walls or productions. they're pretty fragile, though. They target troops first, if none are around they target walls then defenses.

Tier 3 - Strider - This unit is fast enough and boasts a very fast firing gun that fires small bullets that do about 1/5 the damage of 
a regular one. As you can guess it's some kind of DPM weapon that fires a lot of bullets in a short amount of time without the projectiles alone dealing a lot of damage. They target walls first, and if a wide passage is open, they'll get in. If no more walls are to be seen, they'll target defenses.

Tier 4 - Whirligig - This unit is bigger and has a slag mortar with two little gatlings like the strider's. Targets turrets first, and if no passage is open, they'll begin attackign walls. The gatlings can shoot down air units and will target these as a priority.

Tier 5 - Lethocerus - This unit produces a small-range damaging shockwave every so often around it, about every 5 seconds. They feature 4 gatlings and the mortar fires a bit of slag and oil together, albeit slower. They produce a spawn every 7 seconds. They can be rallied around it like a queen rallies buzzers, and yes, it also has more room for spawns than for other units.

And that's it for my ideas of insectoid air and naval units ! Feel free to tell what you all think about their abilities, if you have ideas to make them better or more unique, or if you feel there is a balance problem.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think the versatility of one's playstyle is an important aspect of Mindustry, and as such, more unconventional units  make a lot of sense if it's the direction the game wants to take. Taking some of the insectoid line abilities and giving them more options is a concept that could greatly enhance the spirit of what mindustry is, and makes even more sense because if there are support lines for everyone, everyone should also have unconventional ones. Note that air and naval troops have different abilities so that Naval units aren't rendered useless simply because Air overshadows them by doing what they do both on land and water.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by CreebotTheGreat** [comment]
I forgot to add that the Spawn explodes on enemy contact even when idle, thus really serving as a sea mine

**Comment by oinkymoo** [comment]
both t1s and and air t2 : why are these just clones of crawler and atrax

air t3: how is this blocked by walls. it flies

air t4: I don't think this is enough to be a unit on its own, it should probably still have weapons, unless you want to give it comparable shield health to an oct. also are you aware that most units can have a squad of 8 others? also i don't think the command system would allow such a thing to exist

air t5: same command issues as before, but that is also not how payload works. all units have a size and each unit capable of holding payloads can hold a certain area of payload. megas, for example, have 4 blocks of payload space, which could be used to hold 4 1x1 blocks, a 2x2 block, 4 novas, 2 pulsars, an oxynoe, 3 polys, 7 monos, or 5 flares (or other units of similar size). just pick a size and go with it

naval t3: define "regular" gun

naval t5: same command issues again

other than this stuff i support

**Comment by CreebotTheGreat** [comment]
> both t1s and and air t2 : why are these just clones of crawler and atrax
> 
> air t3: how is this blocked by walls. it flies
> 
> air t4: I don't think this is enough to be a unit on its own, it should probably still have weapons, unless you want to give it comparable shield health to an oct. also are you aware that most units can have a squad of 8 others? also i don't think the command system would allow such a thing to exist
> 
> air t5: same command issues as before, but that is also not how payload works. all units have a size and each unit capable of holding payloads can hold a certain area of payload. megas, for example, have 4 blocks of payload space, which could be used to hold 4 1x1 blocks, a 2x2 block, 4 novas, 2 pulsars, an oxynoe, 3 polys, 7 monos, or 5 flares (or other units of similar size). just pick a size and go with it
> 
> naval t3: define "regular" gun
> 
> naval t5: same command issues again
> 
> other than this stuff i support

I understand your criticism. Let me give some answers!

First question : I... Felt like it.

Air t3 : The shots are blocked by the walls not the thing itself, sorry if it was unclear

air t4 : Must've forgotten to add it but yeah it does have shields. As for the command system, i guess some programming could make that happen, but hey I'm still studying. I can't tell

air t5 : i think telling the game that it can hold one unit is simple enough. Idk tho

Naval t3 : yeah pretty dumb, I meant the dagger gun. The thing fires so fast that the dps is the same

Naval t5 : see air t4.

**Comment by oinkymoo** [comment]
Thanks for the clarification. At the very minimum I think all of these should be able to command more than 8 of their own kind but a lot less of others

**Comment by CreebotTheGreat** [comment]
> Thanks for the clarification. At the very minimum I think all of these should be able to command more than 8 of their own kind but a lot less of others

i agree

**Comment by GuestUser25** [comment]
Not bad, not bad at all.
Still, I do not think anuke will accept this.
Just a feeling...

**Comment by CreebotTheGreat** [comment]
> Not bad, not bad at all. Still, I do not think anuke will accept this. Just a feeling...

Are there any things that anuke accepted that weren't practical changes and adjustments ?
