### ISSUE TITLE
Wave-Based Weather

### ISSUE THREAD

**Issue by PowerPotassium** [Anuken/Mindustry-Suggestions#3224]
### Describe the content or mechanics you are proposing.

Allow mapmakers to set weather to occur during specific waves instead of only with timers.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Waves could be made to feel more thematic with this feature, for example a sandstorm one wave before and during the boss waves could make them feel more intense, especially on maps where solar power is very important. Currently weather just feels like a random occurrence, which is cool on its own, but I think giving more control over weather for custom maps would definitely improve the mapmaking experience.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Rex-Hm** [comment]
I think it is a great idea, to complement it, I would recommend adding frenzied soundtracks to the game, which would be heard when a guardian came, or something similar.

**Comment by OnyxFinger** [comment]
I like this idea too
