### ISSUE TITLE
not let octs trap you in a cuddlezone

### ISSUE THREAD

**Issue by jacklolidk** [Anuken/Mindustry-Suggestions#3225]
### Describe what you would like changed, and why.

as title says. reason: cant move

### Describe the changes you want to propose. Include possible alternatives.

change the ai for the octs to only let one or two octs be near you for the shield

**Comment by itcannotbe** [comment]
Why not somehow just make so that you can push octs away instead, since there other ways of controlling units.

**Comment by SMOLKEYS** [comment]
> cuddlezone

😳

**Comment by BlueWolf3682** [comment]
but cuddles ^^

**Comment by AMindustryPlayer** [comment]
It is hard it push octs away :(
