### ISSUE TITLE
Add auto-update if it isn't buggy

### ISSUE THREAD

**Issue by AMindustryPlayer** [Anuken/Mindustry-Suggestions#3226]
### Describe the content or mechanics you are proposing.

You add the code that commands the game to check Mindustry github and if there's any new update, let user decide whether to update or not. If the newest update is pre-alpha, let the user decide. This mechanic has been existed in bleeding edge build.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

![image](https://user-images.githubusercontent.com/88170950/144700001-553e864f-6ef0-4602-8a64-e0fe6b9cc092.png)
One player has been coded a mod and this mod will help the user to install the latest version of Mindustry(Maybe). This greatly helps the user to update Mindustry even he/she don't visit the download website, of course he/she don't need it if Mindustry is downloaded from steam bc  steam has auto-update function. That mod's mechanic is similar to my idea.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You already can use the itch.io app to auto update your game...

**Comment by AMindustryPlayer** [comment]
> You already can use the itch.io app to auto update your game...

but how?

**Comment by Bottinator22** [comment]
~~Steam version auto-updates, try buying that~~

**Comment by end-me-please** [comment]
It has been talked about before, this is likely not going to happen

**Comment by Cleanup-Crew-From-Discord** [comment]
Just buy steam, use the itch.io app to do it, or use BE releases

**Comment by end-me-please** [comment]
Or use foo's client :p

**Comment by Bottinator22** [comment]
> Or use foo's client :p

no
~~we don't need more people misusing foo's client in servers~~
