### ISSUE TITLE
Ground unit formations

### ISSUE THREAD

**Issue by myutin** [Anuken/Mindustry-Suggestions#3227]
### Describe what you would like changed, and why.

If the player controls a ground unit, and commands other ground units in formation, when the player walks through a tight corridor, the commanded units will get stuck on terrain. Based on previous suggestions, there's no way to prevent this. The result is that units move very slowly (according to the cosine of the angle between path and wall), and may drown before restoring position (if in water).

### Describe the changes you want to propose. Include possible alternatives.

Whenever a unit is straight-line-pathing towards some coordinates, and that unit is blocked by terrain, the unit turns parallel to the wall, and moves at full speed (its direction is the direction of its target, projected onto the direction of the wall). If blocked by a corner, the unit's behavior is unchanged, i.e., no movement.

In most situations, this would much reduce the amount of time a unit spends stuck out of formation, and much reduce the jiggling a player has to perform to get the units un-stuck. This could still leave units stuck in some situations (e.g. sharp turns around an obstacle), but would nonetheless be an improvement.

**Comment by end-me-please** [comment]
Anuke is already working on a new formation system that will hopefully solve some of these problems

**Comment by MistahStealYoGril** [comment]
Lol I can already imagine them walking in a soccer formation. Frickin 433 or 352

**Comment by RickAstly** [comment]
And naval unit commanding is 100x worse... literally any place where the river/water is not completely open, commanding units is totally unfeasible. Glad to hear its being improved.

**Comment by itcannotbe** [comment]
~Do you really have to extend the life of this open issue?~

**Comment by end-me-please** [comment]
...and the formation system will be changed anyways
