### ISSUE TITLE
transport drone mechanic you shown on the dev-preview

### ISSUE THREAD

**Issue by Fishylord** [Anuken/Mindustry-Suggestions#3229]
### Describe the content or mechanics you are proposing.

Allows a feature where Instead I can use logic to control the amounts Inside the storage container for the unit to carry. assuming the unit container can store 300items using logic I can control the amount of certain items in the container, like having a mix of 200sand and 100coal. Instead of having receiving containers being locked to one material it can simply be a destination point if material is not selected.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

By having this optional/side mechanic, I can have schemes that use the receiver fully and doesn't overflow of either materials. This way I do not need to have 2 recievers but just one.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
You can probably just bind the unit created by the factory to do that already.
