### ISSUE TITLE
Shock Mine Rework

### ISSUE THREAD

**Issue by gen-NA-owl** [Anuken/Mindustry-Suggestions#323]
**Describe what you would like changed, and why.**

Shock Mines are almost never used. They should be buffed. 

**Describe the changes you want to propose. Include possible alternatives.**

I think they should be less spammable, but should deal more damage. Also, they shouldn't be able to be "accidentally" hit by bullets. How does a bullet hit something underground?
Explosions and fires should still be able to damage shock mines

**Comment by potatoisagender** [comment]
they are already really expensive, for a kamikaze weapon that is disarmed easily. enemies can't target the mines, but may hit them by accident. Other than that, I think its an okay idea, assuming they remain in 6.0.

**Comment by itcannotbe** [comment]
shock mines are already extremely effective as a trap not as a front line defense.

As a trap they should be placed far away from your front line.

**Comment by Anuken** [comment]
Shock mines have been slightly buffed.
