### ISSUE TITLE
Replacing the flash on a new planet.

### ISSUE THREAD

**Issue by Spawnstar1** [Anuken/Mindustry-Suggestions#3230]
### Describe the content or mechanics you are proposing.

Greetings Anuke
After reading the post about the new transport drone, I was very surprised by the fact that a whole branch of air units will be completely cut out on another planet. But is there a chance of the return of the previously cut-out Javelin unit in the form of a new branch of air units?
The idea of this unit with a unique movement dynamics and the ability based on speed retention for damage should be brought to the branch with the transition to electric weapons for air at the cost of speed when switching to higher tiers.
I apologize if you could not understand something from what was written, a translator was used to write this text.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This idea will allow you to return previously cut content and give it a new look and capabilities, in addition, almost all the old robots from the alpha replacement platforms were transferred in one form or another to subsequent versions, with the exception of javelin. In addition, there was no full-fledged branch that is completely based on electrical discharges

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Rex-Hm** [comment]
yes pls

**Comment by OnyxFinger** [comment]
I like this idea, and I like it a lot : 
I believe that this route can be interesting, ~~or way too overpowered~~ but the speed of the javelin should be lower than the V5 version of it.
This unit can have interesting dynamics :
      ⋅ Maybe later-ish game runbys in PvP ?
      ⋅ It could affect the defense placement in survival. Maybe there is a very good defense spot away from the air spawn, and there aren't many ores that enemies would block you from accessing with this position. However, the javelin, with its mechanic that makes it gain speed, and make lightnings at high speed, can be interesting. You see, it gets strong by going fast, gets fast by traveling, so if your defense is close to the enemy spawn, javelins won't do much, but if you're far, they will deal much more damage. This would affect the way that defenses are built, and leave multiple different ways for the player to build his walls and weapons, which I think is great.

**Comment by Anuken** [comment]
> But is there a chance of the return of the previously cut-out Javelin unit in the form of a new branch of air units?

No. When I say "no flare equivalent", I really mean it. There will be nothing remotely similar.

**Comment by OnyxFinger** [comment]
> No. When I say "no flare equivalent", I really mean it. There will be nothing remotely similar.

So **no** air units are all, except for support ones ?
Javelin isn't much like a flare in my opinion

**Comment by Anuken** [comment]
> So no air units are all, except for support one(s) ?

No, that's not what I said. You will see once the update is out.
