### ISSUE TITLE
Make boosting cheaper/more effective

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#3231]
### Describe what you would like changed, and why.

Currently, mend projectors and overdrive projectors take phase fabric to boost. I would like to see this changed to plastanium, as phase fabric is too expensive. At that point, we just build overdrive domes and use mass unit healing. Or just spam mend projectors. 

### Describe the changes you want to propose. Include possible alternatives.

Change the boost cost to plastanium, but reduce it to 200%. Give the boosting something of an actual use.

**Comment by Rex-Hm** [comment]
or make phase-fabric production to 1.5s

**Comment by OnyxFinger** [comment]
what dah heeeelllll
who told you overpowered menders have to be cheeap
they don't even consume that much, and phase is really not that useful.
Also, mend proj has 200% efficiency with boost, it would need to be nerfed slightly more.

**Comment by Cleanup-Crew-From-Discord** [comment]
So what do we use phase for now? Now it's only used for some end game buildings and phase conveyors/conduits. Phase should stay because the phase boost is meant to be endgame.

(Also it barely eats phase just make like 2 factories and you're set for 9 or 10 blocks boosted)
