### ISSUE TITLE
Extra sector accuracy

### ISSUE THREAD

**Issue by Bassem-Const** [Anuken/Mindustry-Suggestions#3233]
### Describe the content or mechanics you are proposing.

My idea is to render sectors within the render distance with fullstrum culling, darkening locked sectors with a yellow border between those and unlocked sectors and an ability to travel between the unlocked sectors, since there are sectors made to fit in the hexagon and the day-night cycle is planet dependent, why not have other sectors rendered alongside the current sector? (or if it doesn't fit the original game implement the feature in the sequel.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Such a feature will add a bit of realism to the game and would make sense since sectors are made in a hexagon and events are based on the planet.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
RIP mobile/low specs users

**Comment by THEGAMER-10n** [comment]
> RIP mobile/low specs users
This should have a setting to turn this off/on

**Comment by OnyxFinger** [comment]
THTR;DR
bruh

**Comment by BalaM314** [comment]
I like this a lot, it would make the planet feel more whole, instead of a bunch of completely separated sectors.
