### ISSUE TITLE
Implement achievements for all versions of the game

### ISSUE THREAD

**Issue by throwaway1037** [Anuken/Mindustry-Suggestions#3234]
### Describe the content or mechanics you are proposing.

Achievements which work for all versions of the game and do not require proprietary software such as Steam to work.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would stop forcing players to install proprietary software in order to gain access to features. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by throwaway1037** [comment]
@itcannotbe I'd happily pay for the game; the issue here is freedom, not price; players should not need proprietary software to have the best experience.

**Comment by itcannotbe** [comment]
> @itcannotbe I'd happily pay for the game; the issue here is freedom, not price; players should not need proprietary software to have the best experience.

Steam wouldn't be happy if you're offering everything the steam version offers on another platform for a lesser price. (In this case for free.)

**Comment by MrDuck557** [comment]
achievements is a Steam/console thing
I see PlayStation and Steam achievements
inside the games? not so much
if you want achievements, get Steam

**Comment by Bottinator22** [comment]
Steam doesn't even cost money, it's Mindustry that costs the money
also, achievements are just a nice thing to have, they aren't the game

**Comment by end-me-please** [comment]
forcing players to install proprietary software if they want to get access to features of said proprietary software
literally 1984

**Comment by OnyxFinger** [comment]
I completely agree with the point of view of ItCannotBe, MrDuck and Bottinator.
Not only achievements are basically unimpactful on the game and never actually looked at, they are supposed to be for steam, that way the steam version has an actual advantage (even though it seemingly doesn't from what I know)

**Comment by Anuken** [comment]
[User was either trolling or wildly out of touch; blocked](https://github.com/Anuken/Mindustry/issues/6418#issuecomment-989370038)
