### ISSUE TITLE
Waves

### ISSUE THREAD

**Issue by MatteoPlay** [Anuken/Mindustry-Suggestions#3235]
### Describe the content or mechanics you are proposing.

No hablo inglés, así que utilizo un traductor.
Por tanto, no se excluye la revisión incorrecta de algunas de las propuestas.
Torreta con dos, una o ninguna mecánica de inyección de fluidos. Dispararle es parecido al ADN, requiere energía, el arma no es auxiliar, aunque si solo hay agua apagará el fuego.
### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Esto agregará variedad:
Llevando más de una munición.
Esta será la tercera torreta que usa fluidos.
### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Facosa99** [comment]
De pura casualidad hablas español? porque al chile no se entiende tu idea en inglés xd

**Comment by MatteoPlay** [comment]
Lo siento, pensé que hablabas inglés, utilizo un traductor y, por lo tanto,
algo podría estar torcido. Sugiero una torreta 4 × 4, disparar es como si
el ADN requiriera energía y dos fluidos.

чт, 9 дек. 2021 г., 23:46 Facosa99 ***@***.***>:

**Comment by MatteoPlay** [comment]
También sería genial si pudieras agregar amigos y jugar con ellos a
distancia, pero probablemente muchas personas sugirieron.

сб, 11 дек. 2021 г., 18:33 Matteo Mar ***@***.***>:
