### ISSUE TITLE
Liquid Overflow/Underflow Gates

### ISSUE THREAD

**Issue by XenonZe** [Anuken/Mindustry-Suggestions#3236]
### Describe the content or mechanics you are proposing.

Much like the overflow and underflow gates that exist already with items, this is something that I have always been wondering about, and I never understood why it isn't something that already exists in mindustry. This would be a block that only works with a single liquid, sure, but rather than having a liquid network all leak out of the same liquid tanks to supply units liquids, why not have a controlled overflow gate, so when the liquid delivered to the building is full and the pipes get backed up, it feeds this out to a different pipe? Respectably forwards/backwards/right/left respectively. I am aware this has been requested before but it deserves attention.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Massive opportunities for the simplification of liquid networks, and large opportunities to reduce the unnecessary waste and separation of liquid networks. 

I have always hated how I have had to make several separate tank and pump networks because a liquid guzzling building prevents the dispersion of liquid to another unit/building efficiently. I am not talking about the mixing or filtration of liquid, as that is not something that would reasonably be expected, nor would it be pretty or sightly. This is all suggestion for one liquid type at a time 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I am at a loss on how would one use such.

**Comment by XenonZe** [comment]
> I am at a loss on how would one use such.

Lmao are you serious? I literally just told you. When a unit or building is full of water, pipes back up. Adding these in would allow for water to fill in a sequential order rather than all at once, since the current way to do so involves either making separate liquid networks, or having them all tap into the same one and same number of tanks. This leads to either an inefficient system where liquid drains too quickly, or where it fills up too slowly, due to pumps being dispersed to too many tanks at once. Use your brain.

**Comment by XenonZe** [comment]
Nobody makes the trouble of opening a suggestion to have the displeasure of someone not bothering to read it.

**Comment by itcannotbe** [comment]
I was asking for a real world in game example of a setup of the needed intricacies you are asking.

**Comment by XenonZe** [comment]
If you cannot understand by my comment, I do not know how to help you. I reset my campaign process and I am not going to waste my time either making a drawing or making a build and posting a screenshot for you. 

You're not even an official participant for mindustry suggestions so you're challenging me for absolutely zero reason. 
You're trying to talk smart but you don't make grammatical sense. I've met people like you on Linux forums.

**Comment by GitHubUser-B** [comment]
He's not the only one like that...

**Comment by GitHubUser-B** [comment]
For some reason the community of this game is full of arrogant and rude people who put down others... I was so outraged by the brazenness of this "suggestion group" that I decided to create a github account to interfere with it!

**Comment by GitHubUser-B** [comment]
And one more thing, I'm not one of them :)

**Comment by itcannotbe** [comment]
> He's not the only one like that...

> For some reason the community of this game is full of arrogant and rude people who put down others... I was so outraged by the brazenness of this "suggestion group" that I decided to create a github account to interfere with it!

> And one more thing, I'm not one of them :)

And this helps the discussion... How exactly?

**Comment by GitHubUser-B** [comment]
> > He's not the only one like that...
> 
> > For some reason the community of this game is full of arrogant and rude people who put down others... I was so outraged by the brazenness of this "suggestion group" that I decided to create a github account to interfere with it!
> 
> > And one more thing, I'm not one of them :)
> 
> And this helps the discussion... How exactly?
> 
> Also FYI, most of the experienced/"verified" designers in the discord community cannot see how this can help making their designs/schematic better, based on the discussion on discord.

It doesn't even have to do with the discussion, and shematics suck! One of the fun of the game was to brainstorm to make the factory eficient!

**Comment by XenonZe** [comment]
Can you both just. Stop. Especially you, @itcannotbe, you haven't done anything to help this conversation either and I would like to not have to prematurely close this because you all can't keep your emotions in check.

**Comment by GitHubUser-B** [comment]
> Can you both just. Stop. Especially you, @itcannotbe, you haven't done anything to help this conversation either and I would like to not have to prematurely close this because you all can't keep your emotions in check.

Ok

**Comment by XenonZe** [comment]
> > Can you both just. Stop. Especially you, @itcannotbe, you haven't done anything to help this conversation either and I would like to not have to prematurely close this because you all can't keep your emotions in check.
> 
> Ok

I do want to say tho, thank you for sticking up for me :) <3

**Comment by GitHubUser-B** [comment]
> > > Can you both just. Stop. Especially you, @itcannotbe, you haven't done anything to help this conversation either and I would like to not have to prematurely close this because you all can't keep your emotions in check.
> > 
> > 
> > Ok
> 
> I do want to say tho, thank you for sticking up for me :) <3

You're welcome
