### ISSUE TITLE
@ speed for logic

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#3237]
### Describe the content or mechanics you are proposing.

sensor that returns speed value for a unit 

(#2146 #2784)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

applications
- so i dont have to hardcode speed values for the ultimate dome loader 5.0 :d

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
has been added to the dev branch

**Comment by Highfire1** [comment]
pog
