### ISSUE TITLE
New Turret

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#324]
Breakdown/Takedown (Both names are good for me): A turret that fires one bullet over a long time that deals very high damage to a single enemy.

• Requirements: Similar to Meltdown and Spectre
• HP: Similar to Meltdown and Spectre
• Damage: (Something similar to total damage of a Meltdown in one shot)
• Reload: (A value that makes the turret balanced (something long but not too long))
• Range:  30-50
• Inaccuracy: 0
• Build Time: (High enough but not too much (30-45).)
• Size: 5x5 or 4x4
• Ammo: Thorium (For Highest Damage), Plastanium (For Frag), Surge Alloy (For Shock), Pyratite (For Incendiary), Blast Compound (Make it so Blast Compound will have a new special thing like how silicon ammo is always homing or a pyratite is always incendiary. If you don't/can't , blast compound shouldnt be an ammo.)
• Targets both Air and Ground Units.
• Requires Power: 1000-2000 per second/fire
• Requires Liquid (For use, not booster): Cryofluid (80 per second)

This turret will make it easy to beat very high HP Units (Bosses) and add a new turret to the Meltdown and Spectre duo. It has both advantages and disadvantages to make the turret balanced.

Advantages:
• Kill bosses easily.
• High range so you can place it behind your turrets that are behind the wall so all turrets can hit.
• Targets air so it will be easier to takedown Lich/Reaper because they escape but this turret hits anyways because of range, damage, no inaccuracy and etc. (If placed on sides)
• 0 Inaccuracy guarantees the hit (Make the bullet fast enough (Make it so we can also the bullet for a short time and it leaves a trail.) so its definitely not dodgeable)

Disadvantages:
• Slow reload
• Long build time
• Big size makes it hard to place somewhere in your defense. (That's why I prefer 5x5 but since if we make it 5x5 it will be the only turret with 5x5 size if we dont add another 5x5 turret and this *may*  (not definitely) be annoying for some people.
• Requires much power and liquid, no coolant/booster.
• Turret can hit something like Dagger or Wraith Fighter (Low HP - Basic Unit) if its in the way instead of something like Chaos Array or Lich (High HP - Boss Unit ). Maybe make it so it only hits bosses (Bullet wont contact/collide with non-bosses) (Bosses are units that show up the "Boss Health" bar not high HP units but since all high HP units are also bosses it doesnt matter for them but if you implement the "only target bosses" and make a Dagger unit a boss and make a Eradicator unit not a boss it will target the Dagger.) or make it so it only hits units with a HP higher than a specific value (Bullet won't contact/collide with enemies with a HP below specified value) or leave it as is so it will be a big disadvantage and makes the turret worse than other turrets or makes it balanced or its still OP with this idk im not sure about this one.

What I typed there may not make it into the game but the main thing is the concept: A turret that fires one bullet over a long time that deals very high damage to a single enemy. Values may be different (maybe its unbalanced)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SupremeTurtle** [comment]
This could be good, since we only have one burst turret which is the Salvo.

**Comment by TranquillyUnpleasant** [comment]
> This could be good, since we only have one burst turret which is the Salvo.

Well ripples are also a burst turret, albeit artillery.

**Comment by itcannotbe** [comment]
Ripples aren't burst. Also a long range turret will be rendered useless with out insane bullet speed or bullet honing since your targets actually move.

**Comment by RoyalFunnyDude** [comment]
Tho silicon's homing would be kinda useless if the bullet speed is fast and impossible to dodge though

**Comment by Zenith-LY** [comment]
> Tho silicon's homing would be kinda useless if the bullet speed is fast and impossible to dodge

oh i forget about that, silicon shouldnt be an ammo for that turret then

**Comment by Zenith-LY** [comment]
> Ripples aren't burst. Also a long range turret will be rendered useless with out insane bullet speed or bullet honing since your targets actually move.

its bullet speed will be insanely fast.

**Comment by Zenith-LY** [comment]
> This could be good, since we only have one burst turret which is the Salvo.

concept is more like hail but times better

**Comment by RoyalFunnyDude** [comment]
Also, you mentioned that it would take water (100 per second/fire) and cyro (100 per second/fire), so...what's the difference?

**Comment by RoyalFunnyDude** [comment]
why take the trouble to get cyro when it does the same thing as water lmao

**Comment by RoyalFunnyDude** [comment]
Maybe make it so only cyro can boost

**Comment by stuffyAI** [comment]
Water makes it work, Cryo boosts it to 1,3 times speed.
Anyway, the Trello is talking about 2 new Superweapons, perhaps something along your lines is already underway.

**Comment by grimsoul10** [comment]
I think the second new turret is like Inferno (from clash of clan if you not know), I think it will good is when this turret shoot an laser, the laser will follow the enemy and this turret will be add more damage along a time. The first stage of the laser will damage 50 and the end stage will deal damage 1100 so it will more strong  to kill Lich/reaper

**Comment by Zenith-LY** [comment]
> Water makes it work, Cryo boosts it to 1,3 times speed.
> Anyway, the Trello is talking about 2 new Superweapons, perhaps something along your lines is already underway.

I mentioned that there isnt any booster/coolant for the turret. To make it work you put either water or cryofluid.

**Comment by Zenith-LY** [comment]
> Also, you mentioned that it would take water (100 per second/fire) and cyro (100 per second/fire), so...what's the difference?

I changedit now

**Comment by Zenith-LY** [comment]
> Maybe make it so only cyro can boost

you cant put 2 liquids to the same block. But if anuke makes it possible, then this is good.
