### ISSUE TITLE
Return to previous step when pasting for logic function

### ISSUE THREAD

**Issue by klhg48937** [Anuken/Mindustry-Suggestions#3241]
### Describe the content or mechanics you are proposing.

Return to previous step when pasting for logic function

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I was trying to write the logic of the control unit and accidentally copied a letter "w", two hours of effort all gone!
I tried Ctrl+Z, but it didn't work.

Do not need too complicated, just record a step when posting, you can use Ctrl + Z.
Thank you guys, this game is fun!.
![image](https://user-images.githubusercontent.com/14118783/145871651-d45617a5-627a-49c1-943d-fb7f33209a94.png)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MHeMoTexHuK** [comment]
that's why should always use an external text/code editor instead of the in-game one

**Comment by skipydog** [comment]
If it helps, windows has a feature for copy and paste clipboard history
given how easily entire works of logic can be deleted, I support this
