### ISSUE TITLE
Add Search Function to everything (that needs one)

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3243]
### Describe the content or mechanics you are proposing.

Search function in the following not exhaustive list (basically everything...):
Custom Game Map Selection
Sector Picker (Campaign) (Also Icon Filter, cause why not)
Settings? (for extremely lazy people)
Multiplayer server list.
Payload picker

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

~Be a pain to anuke~ Quality of life.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AMindustryPlayer** [comment]
> Settings? (for extremely lazy people)

lol

**Comment by itcannotbe** [comment]
Added payload picker

**Comment by COALROCK8642orCR8642** [comment]
Just add seach everywhere. Also try to have fuzzy search similar to factorio.
