### ISSUE TITLE
Planet resource info screen correction

### ISSUE THREAD

**Issue by soccersetter643** [Anuken/Mindustry-Suggestions#3244]
### Describe the content or mechanics you are proposing.

Hopefully this would be pretty easy, but can you make it so when you go to the sector info screen, it shows the resources for produced, exported and stored in the same order? It makes it easier to verify that you are producing all the resources that you are storing, as well as offsetting (when trying to max out a sector). I.e. copper, lead, silicon, graphite, etc. all in the same order, perhaps by order they are typically unlocked, i.e. natural resources first, then simple refinements, then complex.
![A0E397DF-C1E6-4BFD-83F2-7A51512121B1](https://user-images.githubusercontent.com/96320231/146619439-bb5a3320-d619-4146-9a0d-1929700d435c.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

User interface simplification

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
the order as they appear in storage is the standard order of materials, i would expect that to be the order everywhere

**Comment by Anuken** [comment]
Items are already displayed in order in v7.
