### ISSUE TITLE
make derelict less confusing

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#3245]
### Describe the content or mechanics you are proposing.

deleting + reconstructing to rebuild derelict structures is not intuitive 
![image](https://user-images.githubusercontent.com/45698812/146626850-b103c4cc-7416-495f-91a3-319d179770f5.png)
![image](https://user-images.githubusercontent.com/45698812/146626853-465ed990-900d-4ac6-b08d-3930df8e606c.png)
![image](https://user-images.githubusercontent.com/45698812/146626858-5c59301f-e1e8-4bab-91ca-e33a9cc9c3f1.png)
![image](https://user-images.githubusercontent.com/45698812/146626871-f658cda6-a0f0-4ecb-b193-5e72cb87df0f.png)

suggestions:
- one click to rebuild/claim derelict blocks
- make derelict blocks useable by default
- make derelict blocks unreconstructable

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

edition number 2 of questions that reoccur in help :d

~~also i want some derelict lore~~

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Highfire1** [comment]
wait im actually blind how did i only see it on the trello until after i submit it

**Comment by wdmvv** [comment]
ohno
