### ISSUE TITLE
Add the "info button [?]" to the block panel when the block is selected on the map (Android version)

### ISSUE THREAD

**Issue by Ouaz** [Anuken/Mindustry-Suggestions#3246]
### Describe what you would like changed, and why.

Hi, 

I'm a new player of Mindustry on Android. As a beginner, I find the UI very convenient except for one thing.

The **[?]** button in the block panel (which is very useful to newbies like me) is only available from the build menu:

![selected_block_on_build_menu](https://user-images.githubusercontent.com/11946570/146691550-d424d617-0ab0-44c4-b36d-68e0ea31a19e.gif)

When selecting an already built block directly on the map, this **[?]** button is not available:

![selected_block_on_map1](https://user-images.githubusercontent.com/11946570/146656884-97ca23a8-8146-4624-8093-1fc910ac7d9b.gif)

The player has to open the build menu and search this particular block to access the question mark button, or has to open each time the core database to search the block and its info.
This is very unconvenient, when a (new) player needs (often) to quickly check the block requirements, what it does,  which type of ammo can be used, etc.

 

### Describe the changes you want to propose. Include possible alternatives.

Could it be possible to add the **[?]** button in the block panel, when the block is selected directly on the map?

![selected_block_on_map2](https://user-images.githubusercontent.com/11946570/146656930-9750893c-ca81-4b2e-9f05-3aaeee6b9142.gif)

I suppose there's a hotkey for that on the PC version, but on Android version, there's no such thing, AFAIK, making the quick display of a block info screen a bit tedious, especially for new players needing it very often.

Thanks for reading (and thanks for this excellent game).

**Comment by Phinner** [comment]
Sir, lemme say this is a good idea. I wonder why no one thought about it before...
