### ISSUE TITLE
Launch pad power usage

### ISSUE THREAD

**Issue by BalaM314** [Anuken/Mindustry-Suggestions#3247]
### Describe what you would like changed, and why.

Currently, the Launch Pad uses a constant 240 power per second, even when it is not charging to launch.
Players end up disabling the launch pad except when it is about to launch with logic, causing it to consume almost no power, which doesn't make sense.

### Describe the changes you want to propose. Include possible alternatives.

I propose to make the launch pad use less power(120?), but only consume power while charging.
This would force it to consume some power while charging, and also stop players from needing to manually disconnect it from their power grid.
(edit) The launch pad would only charge if powered.

**Comment by itcannotbe** [comment]
Or to just use the same amount of total power but only during charge to launch.

**Comment by oinkymoo** [comment]
i agree with itcannotbe's second suggestion

**Comment by BalaM314** [comment]
oops didnt make myself clear enough

**Comment by AMindustryPlayer** [comment]
> Or to just use the same amount of total power but only during charge to launch.
> 
> Or stop the launch timer when it doesn't receive enough power.
> 
> (The second one is more doable)

The first one and the second one are doable, but I think the first one is more doable than the second one
