### ISSUE TITLE
Containers in redactor

### ISSUE THREAD

**Issue by IvanDem2009** [Anuken/Mindustry-Suggestions#3248]
### Describe the content or mechanics you are proposing.

If you put some items in the container/vault in redactor, this items disappear. I think, it will be good, if you can put some items in redactor and use them in the game.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This thing will be useful for map makers that make RPG maps e.t.c.
![зображення_2021-12-20_100729](https://user-images.githubusercontent.com/84869683/146733531-ff56faa1-3ade-4864-bbc4-a63f73f883fb.png)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
do you mean unloaders?

**Comment by itcannotbe** [comment]
What on earth is a redactor?

**Comment by SwitchLikesMlog** [comment]
redactor? this sounds like a thing that exist in mods only

**Comment by thedimas3007** [comment]
Redactor maybe is editor (rus: редактор)

**Comment by notMEEPoffaith** [comment]
tf is a fucking reactor

**Comment by notMEEPoffaith** [comment]
the fuck's a redactor
