### ISSUE TITLE
Asteroid Collisions/Collision Detector/Collision Prevention

### ISSUE THREAD

**Issue by MasterNo2** [Anuken/Mindustry-Suggestions#3249]
### Describe the content or mechanics you are proposing.

While there was "Meteor Showers" listed on the Trello, I think there should be Asteroid Collisions when on asteroid sectors, with more frequent collisions when on larger asteroids. They will occasionally rain down and damage buildings and units throughout the map. You can detect these with a new technology; Asteroid Detector. It would be unlocked between Thorium and Surge Alloy. It will give more warnings for when asteroids will hit as well as predicted locations for where they will land. This is then required for the next level; Collision Prevention. You unlock a more accurate Asteroid Detector as well as compatibility with logic systems. You also unlock an Asteroid Railgun. You can load various ammos into it, having different effects. Scrap will cause the asteroid to break into much smaller fragments. Graphite will do the same, but with less fragments. Silicon will redirect it to the enemy core/drop zone. Titanium completely destroys an asteroid, but not all the time. Thorium will completely destroy the asteroid in a massive explosion

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe this will improve the game by adding new challenges to being in a zero-g enviornment. It can also add to the ambience of the game and help impose the threat interstellar travel has.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RFAC-Productions** [comment]
I see this as a good idea! Adds challenges and makes Zero-G sectors special in their own right.
