### ISSUE TITLE
Is keyboard or a mouse not a controller device?

### ISSUE THREAD

**Issue by Neolactic** [Anuken/Mindustry-Suggestions#3250]
### Describe the content or mechanics you are proposing.

As I’m going to say I’m not to sure if keyboard or mouse will be compatible with iOS mobile devices nor android mobile devices (unless you have Bluetooth or a usb adopter to plug exactly both of these into iOS mobile devices nor android devices)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

As if both are connected, they are will be using computer controls. This suggestion will be taken down as I’m posting it on suggestion because it is also not on list of controllers

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
this is borderline unintelligible, but neither android nor ios have mouse support
