### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Aleksghr** [Anuken/Mindustry-Suggestions#3251]
### Describe the content or mechanics you are proposing.

Можно добавить атомный реактор и новый ресурс атом, атом можно получить из фазовой ткани, чтобы получить атом нужен фазовый прес, атомный реактор выдаёт 10000 энергии, охлаждается криогенной жидкостью, без криогеной жидкости очень сильно взрывается. И ещё можно добавить ядерный реактор, выдаёт 15000 энергии. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Можно добавить атомный реактор и новый ресурс атом, атом можно получить из фазовой ткани, чтобы получить атом нужен фазовый прес, атомный реактор выдаёт 10000 энергии, охлаждается криогенной жидкостью, без криогеной жидкости очень сильно взрывается. И ещё можно добавить ядерный реактор, выдаёт 15000 энергии. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Translated:

You can add an atomic reactor and a new resource atom, an atom can be obtained from a phase fabric, to obtain an atom, a phase press is needed, an atomic reactor gives out 10,000 energy, it is cooled by a cryogenic liquid, it explodes very strongly without a cryogenic liquid.  And you can also add a nuclear reactor, it gives out 15,000 energy.

**Comment by itcannotbe** [comment]
Isn't this basically an impact reactor?

**Comment by RickAstly** [comment]
This is basically a cross between the impact and thorium reactors that runs on phase fabric and thus outputs more power.
I don't think its necessary, a few impacts can power basically anything you'd need and we have enough generators.

**Comment by AMindustryPlayer** [comment]
Why this feature request creator used Russian language to propose the feature bruh
