### ISSUE TITLE
Filter and eccesso separator

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3252]
### Describe what you would like changed, and why.

if the reverse filter and the reverse excess separator did not exist as additional blocks but as a second way?  for example I place the filter, I see that there are defects in the factory, then I click on it and change it to reverse filter, without going to select another block with the same function but reverse, it would be more convenient in my opinion, it would not change a lot of things but at least the filter would have all the functions in one block, as well as the excess separator.

### Describe the changes you want to propose. Include possible alternatives.

I know it's not something necessary, but if it doesn't take too long to fix this little thing I just hope it gets added.

**Comment by itcannotbe** [comment]
Is this a butchered new block suggestion?

If it is, then this is the wrong template/label for it. They go in "Feature Requests"

>  Balancing & Feedback
> Provide balance suggestions or feedback on existing features
> Feature Request
> Suggest new content or mechanics for Mindustry

**Comment by Ymabert** [comment]
I was and am still undecided on which label is best to use, but maybe you are right

**Comment by SwitchLikesMlog** [comment]
i think they are just asking for the two types of sorters/gates (normal and inverted) to be merged together into a single block

**Comment by Ymabert** [comment]
@SwitchLikesMlog yes
