### ISSUE TITLE
[UI] Standardized settings category for mod options

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry-Suggestions#3254]
### Describe the content or mechanics you are proposing.

Just an extra entry in the settings menu for mod options
Fucking hell, this suggestions format makes me feel the need to type up entire paragraphs and I can't do that

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would just give modders a standard place for options so the first menu doesn't get bloated (or worse, mod options being put into existing categories)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
1. Plz no disrespect to the guy that provides quality video games for free.
2. Needs some clarification
3. Whatever it is, it sounds useless

**Comment by RickAstly** [comment]
What he means is:
When you're playing modded, every mod has its own settings menu in a different place, which is confusing, and causes the main settings menu to get bloated. He wants a dedicated "Mod Options" submenu, presumably which would only be active if you had mods loaded.
This is a reasonable suggestion, but really needs clarification, and the comment made people dislike it.

**Comment by itcannotbe** [comment]
Can you just mod a mod menu in the first place?
