### ISSUE TITLE
Save slots

### ISSUE THREAD

**Issue by DenisLT** [Anuken/Mindustry-Suggestions#3255]
### Describe the content or mechanics you are proposing.

It gets kinda tedious importing, exporting and keeping track of different data saves for playing with different people.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will take much less time and thought switching between different saves.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BalaM314** [comment]
Very much yes, I am about 90% of the way through campaign and would like to start making YT videos starting from ground zero, while being able to continue my advanced campaign save. Juggling save files is quite annoying and this would be awesome!

**Comment by IxGamerXL** [comment]
Save files would be better than having to mess with exported data. If this was especially applied to Campaign, things would be more convenient.
