### ISSUE TITLE
Make FLabel less finicky to animate (V7)

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3256]
### Describe what you would like changed, and why.

This more so adds something than changes something, but the deal here is FLabel and the fact that animating FLabels is damn near impossible to do.

I want a method for FLabel that pre-animates the specified FLabel, and branches off from any FLabel instances made.

### Describe the changes you want to propose. Include possible alternatives.

Add a function that branches off of FLabel instances. That function handles the necessary process that makes the FLabel animated.

Either that or properly document the use for it in the framework of Mindustry, so people like me don't have to suffer trying to figure out, W*HAT* *T*HE H**E**CK WE DO WITH *F***LABELS**- *cough*

**Comment by Anuken** [comment]
You've written some words here, but frankly I don't understood a single thing you've asked for.

**Comment by IxGamerXL** [comment]
> You've written some words here, but frankly I don't understood a single thing you've asked for.

Basically, I'm asking for a function that extends from FLabel (a V7-exclusive instance). This function pre-animates the FLabel instead of you contemplating for several weeks trying to figure out how it works.

**Comment by Anuken** [comment]
> a function that extends from FLabel

Functions can't extend classes, I don't know what this means.

> This function pre-animates the FLabel

I don't know what "pre-animates" means or how it will solve a problem.

**Comment by IxGamerXL** [comment]
> > a function that extends from FLabel
> 
> Functions can't extend classes, I don't know what this means.
> 
> > This function pre-animates the FLabel
> 
> I don't know what "pre-animates" means or how implementing this will solve a problem.

They are moreso methods. Regardless, I'm talking about when you use **new FLabel("test")**, as that will create an Object variable that may contain a function/method.

Also pre-animates, that's just my overcomplicated way of saying 'animates'. It's really just animating the FLabel so that I don't spend weeks up till years trying to figure out how to animate just one. Implementing this new method/function enables FLabel use for more people who can't figure out how to manually animate FLabels.

**Comment by Anuken** [comment]
> new FLabel("test"), as that will create an Object variable

That's called a constructor.

> that may contain a function/method.

That's not how Java works, all instances of an object have the same methods.

> Also pre-animates, that's just my overcomplicated way of saying 'animates'.

Why do you need access to the way it animates at all?

> I don't spend weeks up till years trying to figure out how to animate just one.

If you don't understand how it works at all, why are you asking for a new constructor? How will that make it any easier to use?

> Implementing this new method/function enables FLabel use for more people

What is this function, exactly, and what does it do, **in exact terms**?

**Comment by IxGamerXL** [comment]
> That's called a constructor.

I know.

> Why do you need access to the way it animates at all?

Because everytime I call it, it's not using the format I specified and instead returning the unformated version with *FLabel:* tagged on the left.

> If you don't understand how it works at all, why are you asking for a new constructor? How will that make it any easier to use?

I'm not asking for a new constructor, I'm asking for a method (or whatever that'll actually work in java) and that method is part of a constructed FLabel's directory. How much more simplified must I make this?

> What is this function, exactly, and what does it do, **in exact terms**?

var m = new FLabel("{shake}wew");
m.**animate()** *// Does whatever's neccessary to animate this object.*

I quite literally cannot specify *exactly* what it does if I don't know how to animate it manually in the first place.

**Comment by Anuken** [comment]
> Because everytime I call it

Call *what*? 

> returning the unformated version

From where?

> with FLabel: tagged on the left.

You're calling toString() on it? What kind of result do you expect?

> and that method is part of a constructed FLabel's directory. How much more simplified must I make this?

How can a method be part of a "constructed directory"? Are you using a translator? These terms don't make any sense.

> `m.animate()`

This fundamentally makes no sense; I am struggling to imagine what you expect this to *do*. Just like any other UI element, labels are part of a *scene*, they are *drawn* when you add them to a *group*. I don't understand what calling `animate()` is supposed to accomplish in the slightest.

**Comment by IxGamerXL** [comment]
> > Because everytime I call it
> 
> Call *what*? 

The FLabel instance I made using the constructor.

> > returning the unformated version
> 
> From where?

When I use it in place of an item's stats (e.g: Blocks.duo.stats), when I use it in place of the text for Vars.ui.showLabel, and even inside of a dialog that I made with UI Lib.

> > with FLabel: tagged on the left.
> 
> You're calling toString() on it? What kind of result do you expect?

I'm not even using toString. If I was, how do I make it *not* use toString?

> > and that method is part of a constructed FLabel's directory. How much more simplified must I make this?
> 
> How can a method be part of a "constructed directory"? Are you using a translator? These terms don't make any sense.

Not using a translator, although me communicating in a way that makes sense to you seems to be struggling. The instance contains sub variables, or better off yet; just methods. These methods are inside FLabels, especially when the FLabels were constructed. I want an FLabel method inside of FLabels you create that animates the FLabel.

> > `m.animate()`
> 
> This fundamentally makes no sense; I am struggling to imagine what you expect this to *do*. Just like any other UI element, labels are part of a *scene*, they are *drawn* when you add them to a *group*. I don't understand what calling `animate()` is supposed to accomplish in the slightest.

**Before we approach this any further before it inevitably kills both of our brains simultaneously,** can you just sum up how to use FLabels and have them animated and all?

Making a basic tutorial on how to use FLabels in mindustry and making them animated would help a lot at this point, and I'm surprised nobody has bothered doing so this whole time.

**Comment by Anuken** [comment]
> The FLabel instance I made using the constructor.

You cannot "call" an object. You can only call *methods.*

You seem to have a fundamental misunderstanding of Java types and strings; a `FLabel` is **not a string**, all those locations you mentioned either accept strings **or convert the input to a string**. Operations like ` + ` *implicitly convert objects to strings with toString()*. 

Please learn proper Java first; if you had glanced at the method signature for `showLabel`, you would see that the text parameter is a `String`; you can't just shove random objects in there and expect it to work. Frankly, I'm not sure how you got this far without knowing this information.

FLabel is a **UI element**, and works like any other UI element - `table.add(new FLabel("{wave}your text"));`.

**Comment by KayWasTaken** [comment]
what happened here

**Comment by KayWasTaken** [comment]
also isnt FLabel an arc class, not a mindustry class?

**Comment by GlennFolker** [comment]
> what happened here

Guy complaining about stuff he doesn't comprehend. I had no issue using FLabel at all.

**Comment by IxGamerXL** [comment]
> also isnt FLabel an arc class, not a mindustry class?
> 

I dunno how it being an arc class has a difference. FLabel is different compared to the original work, known as typing-label. Is there a drastic difference because it's an arc class?
