### ISSUE TITLE
Add 'mirror buildings' filter into map editor's generate

### ISSUE THREAD

**Issue by AMindustryPlayer** [Anuken/Mindustry-Suggestions#3257]
### Describe the content or mechanics you are proposing.

Same as 'mirror' filter, but mirrors buildings instead of tiles/terrains. Mirroring all teams' buildings is default of the filter, mirroring only a specific team's/teams' buildings is optional. You can make this feature as a setting of 'mirror', while 'mirror cores only' can be toggled only if 'mirror buildings only' setting is enabled. Or simply separate 'mirror buildings' from 'mirror', with 'mirror cores only' be the optional setting of 'mirror buildings'.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make the map making process faster, easier and less frustrating. You know, you definitely don't want to waste time for mirroring loads of buildings, will you?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
I think it's better if we make the Mirror filter have an optional field that affects a single group of blocks instead of every block/multiple filters that do the same thing, just to different kinds of elements.

Example: Walls selected, so mirror all walls on one side to the other. Floors selected, mirror all floors from one side to the other.

**Comment by AMindustryPlayer** [comment]
> I think it's better if we make the Mirror filter have an optional field that affects a single group of blocks instead of every block/multiple filters that do the same thing, just to different kinds of elements.
> 
> Example: Walls selected, so mirror all walls on one side to the other. Floors selected, mirror all floors from one side to the other.

This idea is good, but if it's too buggy then this thing won't be added into the game

**Comment by AMindustryPlayer** [comment]
> > I think it's better if we make the Mirror filter have an optional field that affects a single group of blocks instead of every block/multiple filters that do the same thing, just to different kinds of elements.
> > Example: Walls selected, so mirror all walls on one side to the other. Floors selected, mirror all floors from one side to the other.
> 
> This idea is good, but if it's too buggy then this thing won't be added into the game

So, I would only mention the base of this feature

**Comment by RealYeet** [comment]
The thing this would be useful for us mirroring cores

**Comment by AMindustryPlayer** [comment]
> I think it's better if we make the Mirror filter have an optional field that affects a single group of blocks instead of every block/multiple filters that do the same thing, just to different kinds of elements.
> 
> Example: Walls selected, so mirror all walls on one side to the other. Floors selected, mirror all floors from one side to the other.

Actually, I think it isn't a very useful idea. Instead, I would like to make 'mirror buildings' feature inside 'mirror' to make it as a optional setting in 'mirror', while 'mirror cores only' setting should be able to toggled only if 'mirror buildings' setting is enabled. I'll update this feature request as soon as possible

**Comment by AMindustryPlayer** [comment]
can someone comment here?
