### ISSUE TITLE
Starting up the game after a crash

### ISSUE THREAD

**Issue by SuperThunder958** [Anuken/Mindustry-Suggestions#3259]
### Describe the content or mechanics you are proposing.

The way the game gives us options on start up after a crash. (If your in discord open it in your browser it might make more sense)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

instead of disableding all of the mods ( even the ones that are not even active) have a option on the crash screen (start up screen after you pull up the game and it says that they disabled the mods) to where we choose to disable all of them or run a mod diagnosis to find out witch mod is responsible for the crash and disable them there. And here's 2 reasons for a diagnosis option 1). we know what is affected in the mod 2). we can tell the mod creator's that there's a bug and then they fix it.

Note to the developer: If need so remove some things from My text above if it's too much of a pain for you. hopefully you fix that so that I don't bash my fist into my screen after 5 driffent crashes and opening the game 11 times in a row.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by random-guy1285** [comment]
Mate what are you saying

**Comment by random-guy1285** [comment]
We already have crash logs.
You can also disable mod disabling after a crash.

**Comment by SuperThunder958** [comment]
> We already have crash logs. You can also disable mod disabling after a crash.

Yes but it disables all of the mods you have here is a picture of just half of the amount of mods I use
![Uploading Screenshot_20211225-204500.png…]()
