### ISSUE TITLE
click on jump line to highlight it

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#3260]
### Describe the content or mechanics you are proposing.

in the logic editor, click on a jump line for the line itself to be highlighted

(current highlighting only activates on mouse over, at the origin of the jump)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

![image](https://user-images.githubusercontent.com/45698812/147396111-ebe05352-20ca-4bf5-a52d-3c5ff5e0eb76.png)
pain and suffering i can't figure out where this jump is going

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LeoSko** [comment]
Or just scroll the screen to the place where it jumps/originates from when I click on a jump line.
