### ISSUE TITLE
Minerals to slag/scrap, again

### ISSUE THREAD

**Issue by regymm** [Anuken/Mindustry-Suggestions#3261]
### Describe the content or mechanics you are proposing.

Be able to produce slag from titanium, or scrap from thorium/deconstructor, while keeping balance. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, if there's no scrap on a sector, there's no way to produce slag(lava doesn't exist in Campaign so no direct pumping), even after having all other advanced materials -- this is kinda annoying. And slag tsunami may have late-game use. 

It'll be interesting if there's a way to somehow produce slag from other materials. 
Direct conversion from, like, lead+copper to scrap will cause a huge imbalance as discussed before, but seems titanium+graphite(or copper, or sand) to slag(slag only, so no separator to thorium), or thorium+titanium to scrap is plausible. 

And since now we have constructor/deconstructor, having another special deconstructor to turn any building into scrap is also fine(and more like the procedure that scrap ores came from). This won't cause imbalance because thorium is already required to build deconstructor. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Balance might be kept if you can just turn something to slag but never anything to scrap.

**Comment by itcannotbe** [comment]
~Or maybe a slag extractor?~

**Comment by regymm** [comment]
So if I understood correctly, on a map without scrap, to produce slag, the source must contain titanium. And to produce scrap the source should contain titanium.

**Comment by regymm** [comment]
And to make sure even if you launched with some titanium to a scrap-less titanium-less map, there's no way to produce infinite titanium. So is thorium.

**Comment by itcannotbe** [comment]
> And to make sure even if you launched with some titanium to a scrap-less titanium-less map, there's no way to produce infinite titanium. So is thorium.

Launch Pads Exist.

**Comment by regymm** [comment]
Then why there's the original argument about balancing? I don't understand. Now to build separator you already need thorium. Then allowing easy metals to turn into scrap won't allow having thorium from nothing anyways.

**Comment by oinkymoo** [comment]
this is not happening https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083 https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779

**Comment by regymm** [comment]
I've read this two before. Yet I'm not sure what the mentioned balance? Could you explain a little bit? If a constant input containing thorium is required to produce scrap, how is the balance broken? 
For me being able to produce scrap/slag using late-game mechanics(thorium, for example) would be completing the cycle of elements.

**Comment by itcannotbe** [comment]
Because you're turning thorium into scrap into thorium into scrap into thorium into scrap into thorium into (should I be continuing this?)

**Comment by regymm** [comment]
Is this especially bad? Now we can already turn power into spore then power again.

**Comment by itcannotbe** [comment]
Spore to power has been made unviable except when pumps as it's water source, that how nerfed that got.

**Comment by SuperThunder958** [comment]
How about  a who new type of production block called the resource Crafter where you can turn certain resources into other resources. And you unlock it by capturing at least 3 sectors and 1 enemy base. I'm going to list a couple examples below with some symbols ([ * = could be extremely useful ] [ ? = Maybe not useful] [ ^ = useful depending on little to none of a certain resource] [•• = optional] )
Graphite= spore pod + sand
? Copper = lead + pryrite 
^ Titanium =  copper + graphite + lead + and/or spore pod
^ Scrap = sand + lead
Spore pod = coal + pryrite +  bit of water
? ^ Lead = scrap + spore pod + slag  -or- oil 
Surge alloy =  silicon + plasiamn 
Plasiamn = Titanium + spore pod
Silicon = sand + coal -or- pryrite
* ^ ? Thorem = lead + spore pod + sand + Titanium
Phase frabic = sand + thorem + silicon
And so on but that's just a little idea so that away the separator and disassember has a rival but so it truly is they rival there should be a teir 2 of it Where you are able to craft thorem, phase frabic, plasiamn, surge alloy.

I hope you guys like my idea and sorry bout my typos I was trying as hard as I can to spell while rushing at the same time cause my phone was under 10% while typing this.

**Comment by itcannotbe** [comment]
> How about a who new type of production block called the resource Crafter where you can turn certain resources into other resources. And you unlock it by capturing at least 3 sectors and 1 enemy base. I'm going to list a couple examples below with some symbols ([ * = could be extremely useful ] [ ? = Maybe not useful] [ ^ = useful depending on little to none of a certain resource] [•• = optional] )
> 
> Graphite= spore pod + sand ? Copper = lead + pryrite ^ Titanium = copper + graphite + lead + and/or spore pod ^ Scrap = sand + lead Spore pod = coal + pryrite + bit of water ? ^ Lead = scrap + spore pod + slag -or- oil Surge alloy = silicon + plasiamn Plasiamn = Titanium + spore pod Silicon = sand + coal -or- pryrite
> 
>     * ^ ? Thorem = lead + spore pod + sand + Titanium
>       Phase frabic = sand + thorem + silicon
> 
> 
> And so on but that's just a little idea so that away the separator and disassember has a rival but so it truly is they rival there should be a teir 2 of it Where you are able to craft thorem, phase frabic, plasiamn, surge alloy.
> 
> I hope you guys like my idea and sorry bout my typos I was trying as hard as I can to spell while rushing at the same time cause my phone was under 10% while typing this.

Basically a separator, but has a convoluted mechanic.

**Comment by EclipseTheOldOne** [comment]
> ~Or maybe a slag extractor?~

~~''natural building'' scrap underground~~

**Comment by EclipseTheOldOne** [comment]
> 

ackemist

**Comment by regymm** [comment]
Actually what I'm thinking about is, scrap is somehow overlooked. When making custom maps, default ore mapping doesn't contain scrap, while it may be as important as everything else. 

I mean, on a decent map, you should be able to own every resources. Yet if there's no scrap, which is often the case, there won't be scrap. It's a little bit unfair.

**Comment by EclipseTheOldOne** [comment]
> Actually what I'm thinking about is, scrap is somehow overlooked. When making custom maps, default ore mapping doesn't contain scrap, while it may be as important as everything else.
> 
> I mean, on a decent map, you should be able to own every resources. Yet if there's no scrap, which is often the case, there won't be scrap. It's a little bit unfair.

you can literally add it in generation, idiot

**Comment by EclipseTheOldOne** [comment]
> How about a who new type of production block called the resource Crafter where you can turn certain resources into other resources. And you unlock it by capturing at least 3 sectors and 1 enemy base. I'm going to list a couple examples below with some symbols ([ * = could be extremely useful ] [ ? = Maybe not useful] [ ^ = useful depending on little to none of a certain resource] [•• = optional] )
> 
> Graphite= spore pod + sand ? Copper = lead + pryrite ^ Titanium = copper + graphite + lead + and/or spore pod ^ Scrap = sand + lead Spore pod = coal + pryrite + bit of water ? ^ Lead = scrap + spore pod + slag -or- oil Surge alloy = silicon + plasiamn Plasiamn = Titanium + spore pod Silicon = sand + coal -or- pryrite
> 
> * ^ ? Thorem = lead + spore pod + sand + Titanium
>   Phase frabic = sand + thorem + silicon
> 
> And so on but that's just a little idea so that away the separator and disassember has a rival but so it truly is they rival there should be a teir 2 of it Where you are able to craft thorem, phase frabic, plasiamn, surge alloy.
> 
> I hope you guys like my idea and sorry bout my typos I was trying as hard as I can to spell while rushing at the same time cause my phone was under 10% while typing this.

is that akchemist?

**Comment by COALROCK8642orCR8642** [comment]
Do like to dump materials even silicon or surge-alloy to slag instead of a incenrator.

**Comment by regymm** [comment]
> > Actually what I'm thinking about is, scrap is somehow overlooked. When making custom maps, default ore mapping doesn't contain scrap, while it may be as important as everything else.
> > I mean, on a decent map, you should be able to own every resources. Yet if there's no scrap, which is often the case, there won't be scrap. It's a little bit unfair.
> 
> you can literally add it in generation, idiot

Yeah, but no-scrap is the default behavior, and is more common in public server maps(as in my experience).

**Comment by itcannotbe** [comment]
Then it's a mapper issue?

**Comment by regymm** [comment]
Depends on what the dev team wants scrap to become. If it serves more a game-backstory/auxiliary/make-game-complete purpose, the current design is good. If it is going to be more serious(it is already serious now I think, as ammo for scatter and slag for wave/tsunami), it may be good to add it to default ore generation on custom maps.

**Comment by ChivalricMender** [comment]
How about a sifter you place on sand to sift and look for scrap?

**Comment by EclipseTheOldOne** [comment]
go make a mod


bottom text

> How about a sifter you place on sand to sift and look for scrap?
