### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Bulletj** [Anuken/Mindustry-Suggestions#3262]
### Describe the content or mechanics you are proposing.

New resourse: Lithium, lithium batteries and other lithium electronics. Another new resourse: gold and golden wire which will conduct more energy per second than copper wiring.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

in real life, high voltage can overload the cable and cause a short circuit, so other types of wiring are used: more conductive and resistant to higher voltages. Lithium stores energy well, so adding lithium batteries to the game will make it more realistic. about wiring... Another new resource: gold! gold has good carrying capacity and can be used for cables that carry more electricity per second. I believe that these things will make the game more realistic and interesting.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
your suggestion requests new resources, and it talks about making the game more realistic

expect your suggestion to be rejected heavily

**Comment by oinkymoo** [comment]
existing power systems have an unlimited power transfer rate, and existing power storage devices are more than sufficient. this is just plain unnecessary

**Comment by buthed010203** [comment]
Not to mention that v7 already adds a varied power system
