### ISSUE TITLE
Tar, drench, and heavy compressors

### ISSUE THREAD

**Issue by ChivalricMender** [Anuken/Mindustry-Suggestions#3263]
### Describe the content or mechanics you are proposing.

Three concepts for T2 plastanium compressors. The tar compressor is placed on tar. It functions by submerging titanium in oil/tar and compressing it while submerged.
The other two compressors create an oil pool to compress titanium.
The drench compressor drills a pool in the ground and lets oil leak in. (I'm thinking it only works in dark sand)
The heavy compressor makes an artificial pool from inputted oil.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since plastanium has  several uses, especially for reconstructors, they would be necessary for faster production.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
the only reason that graphite and silicon have t2 factories is because you need amounts of them that far exceed what the t1s can supply. graphite and silicon are used to build 38 and 65 buildings, respectively. plastanium is only used for 16. i don't have exact numbers but silicon and graphite are used in larger amounts than plastanium. exponential uses more than twice as much silicon as plastanium and tetrative 5 times as much.

**Comment by ChivalricMender** [comment]
> the only reason that graphite and silicon have t2 factories is because you need amounts of them that far exceed what the t1s can supply. graphite and silicon are used to build 38 and 65 buildings, respectively. plastanium is only used for 16. i don't have exact numbers but silicon and graphite are used in larger amounts than plastanium. exponential uses more than twice as much silicon as plastanium and tetrative 5 times as much.

Just because they're used much more often doesn't mean a t2 compressor isn't nessecary. That's like saying you don't need improved gold extraction because iron is used much more often.

**Comment by itcannotbe** [comment]
Also T2 buildings aren't direct upgrades of their T1 counterparts. They use additional resources. (As more resources not just in terms of quantity)

**Comment by SuperThunder958** [comment]
Hey cut the man some slack he's trying to create a good idea what  he is trying to say is why the silicone and graphite have a tier or two but plastanuim doesn't have one and heck not only did he give only one example of how the refineries going to work he gave us three different ways of three different refineries and how they could work he came up with three different variants most of the things I want to tell the Creator to make I can't even make up three different variants I can only make up one so at least he has a good plan.  if it does get added and not only is it adding the ability to make more plastanuim and it also makes oil a whole lot more useful other than being turned into coal or being used for just a tier 1 plastanuim which barely gives you enough stuff heck I've gotten tired of the slow wait time that I have added a couple mods that added a tier two plastanuim

**Comment by regymm** [comment]
If there were to be another T2 factory, I hope it is cryofluid mixer.

**Comment by ChivalricMender** [comment]
> Also T2 buildings aren't direct upgrades of their T1 counterparts. They use additional resources. (As in more resources, not just in terms of quantity)

I understand this. Maybe they would use water for hydraulic cylinders, pyratite to melt the titanium and compress while melted, or blast compound to push the pistons.

**Comment by ChivalricMender** [comment]
> Hey cut the man some slack he's trying to create a good idea what  he is trying to say is why the silicone and graphite have a tier or two but plastanuim doesn't have one and heck not only did he give only one example of how the refineries going to work he gave us three different ways of three different refineries and how they could work he came up with three different variants most of the things I want to tell the Creator to make I can't even make up three different variants I can only make up one so at least he has a good plan.  if it does get added and not only is it adding the ability to make more plastanuim and it also makes oil a whole lot more useful other than being turned into coal or being used for just a tier 1 plastanuim which barely gives you enough stuff heck I've gotten tired of the slow wait time that I have added a couple mods that added a tier two plastanuim 

More uses for oil? Sounds like another suggestion (if it isn't planned already)
