### ISSUE TITLE
Payload Overflow

### ISSUE THREAD

**Issue by PizzaBurgz** [Anuken/Mindustry-Suggestions#3264]
### Describe the content or mechanics you are proposing.

Payload Overflow (or Payload Overflow Gates) will output to the sides when the front output is blocked (just like a normal overflow gate).

_Potential setup for a T1, T2 and T3 unit constructor (Generates T1 units first, then T2, then T3.)_
_Payload routers represent Payload Overflow below_
![image](https://user-images.githubusercontent.com/95842176/147447439-dd878354-a900-4d97-8cbc-f4e0466128b6.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Payload Overflow can make payload-related content more efficient and less logic reliable.

For example,

**More efficient unit constructors** - Payload Overflow can be used to check if a unit cap is passed, for example; if a T1 unit cap is passed then reconstruct said T1 unit to T2, if the T2 unit cap is passed then reconstruct said T2 unit to T3, and so on and so on.

**More efficient payload transportation using payload propulsion towers** - If a payload propulsion tower is loading its contents to another payload propulsion tower, load the queued contents to another payload propulsion tower for more faster payload transportation.

OUTPUT PRIORITIES:

If there is nothing blocking the front output, output to the front output.

If there is something blocking the front output;
    if there are no direct payload-based blocks in the left and right sided output, drop payload (if it can be dropped) to either 
sides equally
    if there is a single direct payload-based block in the left or right side output, direct payload to that output.
    if there are direct payload-based blocks in either side outputs, direct payload to either sides equally

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by PizzaBurgz** [comment]
Typo:
(Just like a normal router)
Correction:
(Just like a normal overflow gate)

**Comment by oinkymoo** [comment]
could also be used to continue making units while higher-tier ones are in progress

**Comment by SuperThunder958** [comment]
Damn that's a freaking great idea and I wouldn't have even though of that. 
Sorry bout my language I just thought dang wasn't a good enough word for how smart this idea is

**Comment by SuperThunder958** [comment]
> 
When you say "payload propulsion tower" do you mean like a long range conveyor bridge but for payloads

**Comment by PizzaBurgz** [comment]
> > 
> 
> When you say "payload propulsion tower" do you mean like a long range conveyor bridge but for payloads

I meant the new feature in v7 where you can transport items in over long distances but for payloads

**Comment by RealYeet** [comment]
On a similar topic, make it so that payload routers work without a payload conveyor next to them to allow direct unloading to reconstructers and PPTS.

**Comment by COALROCK8642orCR8642** [comment]
No no and no. Rates already like 3:1 at each stage things will work automatically. Or try using logic.

**Comment by shangjiaxuan** [comment]
> No no and no. Rates already like 3:1 at each stage things will work automatically. Or try using logic.

Logic doesn't seem to have commands for determining if block can receive payload, and set output direction for a payload router and such. Seems more like a mod thing.

**Comment by shangjiaxuan** [comment]
Turns out, you can control a conveyor from contents of the next factory, but there are two problems with this approach:

Code:
```
sensor has_payload reconstructor1 @payloadCount
jump 4 equal has_payload true
control enabled conveyor1 0 0 0 0
jump 5 always x false
control enabled conveyor1 1 0 0 0
end
```
* If maximum number of lower level unit is reached, the conveyor will be stuck with a unit, and cannot disable
* For unknown reason, this does not work for horizontally placed last level `tetrative reconstructor`. The router contains no payload, conveyors are disabled, router is enabled, but the `exponential reconstructor` does not unload into the router.
