### ISSUE TITLE
Mindustry on raspberry pi

### ISSUE THREAD

**Issue by electretboy** [Anuken/Mindustry-Suggestions#3265]
### Describe the content or mechanics you are proposing.

First of all, thank you very much for all the great job you are doing.
I love your game, it is very easy to learn and very attractive.
I really would like to enjoy this game on my raspberry pi because I made a fully working laptop. I am using this laptop daily so I will enjoy playing Mindustry on it.

Any way, thank you for reading my request and doing a great job,

Electretboy

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will improve the number of users of Mindustry because we (raspberry pi users) are a growing and huge community.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
i think raspberry pi compatibility is mentioned in the FAQ (see discord)

**Comment by oinkymoo** [comment]
> i think raspberry pi compatibility is mentioned in the FAQ (see discord)

for reference: 

> **Does Mindustry run on a Raspberry Pi?**
> While the game itself could theoretically support it, no, it does not support the Raspberry Pi. However, the dedicated server will run on a Pi as long as you have the right version of Java installed. Note that the 3.5/Classic dedicated server will not run on a Pi; only 4.0 and above is supported.

**Comment by tigercoding56** [comment]
why does mindustry not run on the raspberry pi ?  the pi 4 is able to run minetest (even going into fairly convoluted locations ) with framerates of up to 20 with  undersapling enabled    ( 2 )
