### ISSUE TITLE
Materials broke

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3266]
### Describe the content or mechanics you are proposing.

A setting that searches for the materials we want on a whole path of a belt, so as to let us identify the materials that block the system.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

when we select the material / materials, a small icon appears on the belt (like the one when you want to take the materials from the belt) which indicates where each material is indicated.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If this isn't this peak laziness, then I don't know what is.

**Comment by Ymabert** [comment]
@itcannotbe if the tape has a long path and you realize you have made a mistake late it would be convenient to be able to just click a few times to be able to fix a system bug, because then it is anti noob such a setting and especially if you are in a game online, in a map where you need to be quick and make mistakes you can't waste / waste a lot of time just to fix a miserable mistake that you haven't noticed at all, (example not true :) it's like putting a tape full of compound explosive next to a turbine (it is clear next to and not entering the turbine) the belt catches fire and explodes everything, even the factory from which the explosive compound is produced, it would be embarrassing to lose for "mistakes" they shouldn't even make part of the game / any game, however, even if fortunately few, exist and if we can correct them I don't understand where the problem is (and I don't even understand what sense it makes to have 3/4, of which only one writes, against, also to the ideas disc  usable / acceptable).

**Comment by itcannotbe** [comment]
The real problem is you don't even understand how complex the problem are trying to solve can get.

But for the same of certain people without foresight and is quick to point out that I always complain and just diss most suggestions right of the bat. Here is a list of questions (by extension problem you will face if wish to implement such functionally)

A non-exhaustive list:
1. What is a blockage, and how can I translate that definition in programming code?
2. How to determine if the item that matches the item that causes the blockage will cause blockage in the entirety of the conveyor "system"?
3. How can I make the functionality "responsive" (Doesn't make the game lag and produce results in one game tick)?
4. How do I map the entire continuous converyor "system"?
5. Will it solve the main problem that causes this problem in the first place?

**Comment by Ymabert** [comment]
did it take long to say it before?  anyway I know that adding pieces of code is a long job in fact if it is not absolutely essential to correct something I think it is right to leave it like this, if it requires a lot of work what I asked for, or in any case additional work not necessary for the game I understand if Anuke does not want to add some things, more than anything else I did not believe it would take so long to implement what I asked for, the code to make the material appear already exists and therefore I thought it was also convenient for the developers to add this thing, however it is (even if I know that it is just something additional) I hope it will be implemented in the game sooner or later, because I hate too much the noobs that mess up the materials in the tape, of course it doesn't always happen to have a messed up base, but when it happens a little bored, especially because it is never my fault but I always have to solve the problem.
