### ISSUE TITLE
Sandbox Menu Unit Summoning

### ISSUE THREAD

**Issue by Connorwer454** [Anuken/Mindustry-Suggestions#3268]
### Describe the content or mechanics you are proposing.

In the proposed sandbox menu, make it be possible to summon enemy and normal entities or units. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would vastly help for testing unit logic in sandbox as well as summon enemies to test defenses.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
there's already payload sources which can do this

**Comment by Connorwer454** [comment]
Can it create enemy units though? Also the main idea of the suggestion is to have it be in a menu form, not a building.

**Comment by itcannotbe** [comment]
> Can it create enemy units though? Also the main idea of the suggestion is to have it be in a menu form, not a building.

So you want for units to be spawn in while not leaving your team?
Won't you die on the spot if you do that?

**Comment by Connorwer454** [comment]
> > Can it create enemy units though? Also the main idea of the suggestion is to have it be in a menu form, not a building.
> 
> So you want for units to be spawn in while not leaving your team? Won't you die on the spot if you do that?

No I don’t mean spawning them right on top of you. It should allow you to “place” them down somewhere on the map.
