### ISSUE TITLE
loops in logic

### ISSUE THREAD

**Issue by Ethanedc** [Anuken/Mindustry-Suggestions#3269]
### Describe the content or mechanics you are proposing.

Loops like these in the logic of mindustry: for, while. Its very difficult programe a code without loops.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The will work more fast and its efficiently in the code.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
you can use jump statements for this purpose

**Comment by end-me-please** [comment]
The jump instruction can be used for everything you suggested with less total instructions than I have fingers on my hand

**Comment by COALROCK8642orCR8642** [comment]
I do like to see more like coding interface similar to scratch. Do like those blocks to put together at cost of more RAM and performance. Can this be optional and can be toggle through settings?

**Comment by SMOLKEYS** [comment]
> Can this be optional and can be toggle through settings?

Cannot be optional/toggleable. Saves using this will shit themselves.
Multiplayer will also completely shit itself.
