### ISSUE TITLE
Replacing map waves preview with a graph.

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry-Suggestions#327]
Currently making waves in Mindustry is very tedious and you have to test a map nearly every time to see whether or not the waves are viable. That can be 2 hours of work just to slightly fine tune waves, and without doing the work map makers risk having untested and unbalanced waves because the numbers are not very easy to see at a glance. Further more for the survival game mode wave balancing is legitimately half the deciding factor in a maps balancing.

The wave preview that currently shows very restricted information, could be replaced with a line graph that shows the trend of units over time in the waves, giving map makes a much easier to understand and clearer idea of how many enemies the waves would have. 

The line graph would essentially just have a line representing each different enemy type showing how many appear on each wave, Potentially also allowing players to scale up and down the number of waves displayed, along with panning the waves, as well as toggling which units are displayed.

This would definitely result in maps being more fun to play because there would be an intuitive display of how difficult/easy waves are for players at a glance rather than having a tiny window that shows only a few waves at a time, making balancing easier.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Partially implemented.
