### ISSUE TITLE
Request to put a search button and bar everywhere.

### ISSUE THREAD

**Issue by COALROCK8642orCR8642** [Anuken/Mindustry-Suggestions#3271]
### Describe what you would like changed, and why.

I would like to see my payload sources to have search bar to type in for quicker access.

Why? I suppose more speed and productivity.

### Describe the changes you want to propose. Include possible alternatives.

Probably a full screen menu interface.

**Comment by itcannotbe** [comment]
But that wasn't my idea...

~~Who cares duplicates are allowed~~

**Comment by COALROCK8642orCR8642** [comment]
You right. I stupid.

https://github.com/Anuken/Mindustry-Suggestions/issues/3243

here. closing this thread now.

**Comment by AMindustryPlayer** [comment]
> You right. I stupid.
> 
> #3243
> 
> here. closing this thread now.

What a thread
