### ISSUE TITLE
Bind unit by ID

### ISSUE THREAD

**Issue by WitlessWonder** [Anuken/Mindustry-Suggestions#3272]
### Describe the content or mechanics you are proposing.

Issue every unit a unique ID number when created as a field like type or name in the logic properties of the unit. Allow units be bound from an ID number instead of just a variable or a type.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I am trying to create some scripts that pass units between different processors to balance units working on different tasks, and currently this is a complicated process of sending a flag through memory cells, physically moving a unit over to another processor, and then using turrets to search through nearby units to find the one with a matching flag. This takes a lot of commands and extra complexity and would be much simpler if i could just pass a number instead. 
Binding units by a number that can be saved in memory would also make it easier for a processors to control a dynamic number of units. I have seen two different ways of implementing processors controlling multiple units; the first is by looping through all units to find the ones with matching flags, and the second is by specifically saving each unit as a variable. This first method works alright until you end up playing on larger maps, where looping through hundreds of units creates a lot of delay. The second method works alright, but you need to add specific variables and instructions to handle each new unit you want to add, which makes scripts confusing and complicated for larger groups. It would make writing group controller scripts easier if you could save a list of IDs in a memory cell and iterate through it in loops.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
🏴🏳️🏁🚩🎌⛳

**Comment by Sector171** [comment]
Yeah sure there should be a unique id for each units.
This will free the "flag" to use it for another purposes much easier.
Also this should be added as well(in addition to Ubind utype):
Ubind id
instead of binding a general type then looping to find the required unit(s).
If needed with some "delay" between 2 orders of this type to prevent this binding process to be over powered.

**Comment by itcannotbe** [comment]
Or just implement a faster way to look up flags...
