### ISSUE TITLE
Liquid flamethrower

### ISSUE THREAD

**Issue by T11235** [Anuken/Mindustry-Suggestions#3273]
### Describe the content or mechanics you are proposing.

A 2x2 turret with high range and precision and damage that uses petroleum and therefore has a minor angle of spreading of the fire.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will add a niche for more powerful flamethrower and adding another way of defending a medium base

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Isn't this basically slag tsunami and an oil tsunami?

**Comment by T11235** [comment]
Yes, but smaller, easier to handle and needeing less resources

**Comment by OnyxFinger** [comment]
> Yes, but smaller, easier to handle and needeing less resources

So a wave ?
but with less options...

Why ?

**Comment by Ymabert** [comment]
I like it

**Comment by RealYeet** [comment]
Literally no reason to have this, the end, end of story, period. *This already exist lol.*

**Comment by RFAC-Productions** [comment]
So a tier 2 Scorch. Aight Scorch definitely needs a Tier 2, considering How the Ripple is the Tier 2 of Hail, or how the Salvo is a Tier 2 of Duo. Seriously Anuke give Scorch more love, anything's fine tbh.

**Comment by T11235** [comment]
Exactly and maybe changing the fuel to petroleum and changing two things: a high range but minor angle of spread of the fire

**Comment by T11235** [comment]
Yes a tier 2 scorch for base defense

**Comment by EclipseTheOldOne** [comment]
burn my fellow jews

**Comment by Falling10fruit** [comment]
Scorch is awesome
