### ISSUE TITLE
menu/highlight to select which payload you want dropped

### ISSUE THREAD

**Issue by RealHackeroonies** [Anuken/Mindustry-Suggestions#3274]
### Describe the content or mechanics you are proposing.

a small highlight of a unit/block that you currently have picked up with a unit, and the ability to select which payload you would like to drop whenever you press the hotkey.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would allow for quicker deploy of buildings and units, and will allow you to actually drop what you want, rather than the last thing you picked up.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Hmmmmmmmmm, slows placing things but you can choose, I am slightly against this, but wouldn’t be inconvenienced if it were added
