### ISSUE TITLE
Split waves between spawners

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#3275]
### Describe the content or mechanics you are proposing.

A new option for maps that splits the wave's enemies evenly between multiple spawn points, instead of adding more enemies per spawn point.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It gives mapmakers more options for making maps, for example, attack maps with multiple cores without overwhelming the player.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. This should be under balancing/feedback
2. Can't you already achieve this in the current way it's implemented?

Say you want to spawn in 30 enemies in this wave and 33 in the next one with 3 spawn points.

Set spawn 10 enemies, +1 per wave.

**Comment by RealYeet** [comment]
I think what he is asking for is an ability to specify which spawn points a wave should be spawned on, instead of the units being spawned between all spawn points very wave with no variance in where they spawn

**Comment by itcannotbe** [comment]
> I think what he is asking for is an ability to specify which spawn points a wave should be spawned on, instead of the units being spawned between all spawn points very wave with no variance in where they spawn

Nope....

> > A new option for maps that splits the wave's enemies _**evenly**_ between multiple spawn points, instead of adding more enemies per spawn point.
