### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by NrkSed** [Anuken/Mindustry-Suggestions#3278]
### Describe the content or mechanics you are proposing.

Ports(or Naval Ports, whichever name will fit the game most) will be a sort of water- Mass Driver. It will be a 4x4 structure. Building it will require the same types of materials as the Mass Driver. 
It will also require significant power.

Here is how it will work:
It can only be built on water. There is no range limitation on it, however there must be water in between two ports.
Unlike the mass driver, one Port can send AND recieve items at the same time (with a maximum of 2 inputs and 2 outputs), and instead of clicking two of them you have to click and drag across them. Each port will also require 20 Silicon and 10 Titanium to build small naval drones which will transport the items (With a maximum of 3 for each port. Port drones can be shot down by enemies and do not have any weapons. When creating a custom game there will be two options: *Port drones can be shot down*, *Port drones require materials to make*)
Each port will hold a maximum of 1k items. Port drones will unload for 5 seconds.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Ports will add a new way of item transportation which will work across water and make transporting materials to weapons easy. Ports will be most usefull when used in seas/lakes.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2823#issuecomment-894874320
