### ISSUE TITLE
Input for Water Extractors

### ISSUE THREAD

**Issue by TanteOctopus** [Anuken/Mindustry-Suggestions#3279]
### Describe what you would like changed, and why.

I've seen a couple different requests to either buff or nerf water extractors.  My understanding is that Water Extractors exist to make high level production possible on water-poor maps, but water extractors get used everywhere, even on water-rich maps.  Nerfing them doesn't help - they still get used, and they become unusable for their primary purpose.  The issue isn't that water extractors are too good - it's that they're too _convenient_.  Even if water extractors were half as effective and twice as costly in energy, it would still be easier to drop two of them next to a Airblast Drill than it would be to pump water in from a handful of blocks away.

### Describe the changes you want to propose. Include possible alternatives.

If Water Extractors require input to function, all that convenience goes away.  It doesn't even have to be much.  1 copper every 10 seconds is enough to require supporting infrastructure, which will make players reevaluate using water extractors based on whether they are the right tool for the job, rather than just the lowest effort one.

Input could be anything cheap, probably copper, lead, or metaglass.  Probably would have a very low consumption rate - the intent here is not to make it difficult to procure the resources, just to require any infrastructure at all.

This change will of course break a whole ton of schematics that rely on extractors being free water, but so would any other change.

I imagine that it might be possible to buff the output of water extractors with this change, but that would be a separate/secondary balancing issue.

**Before making this issue, check the boxes below to confirm that you have acknowledged them.**
 I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
 I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
 I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Facosa99** [comment]
Makes sense. On this regard, i would need to choose between feeding water to the drill via conduicts, or feed copper to the extractor via conveyors. either way the convnience disappear yet they are still usable. Nice

**Comment by itcannotbe** [comment]
But then again unloaders exist, I'm sure some schematic designer would work around this minor inconvenience in record breaking time.

**Comment by RealYeet** [comment]
Flers also exist, if I had to guess, container + a few logic units = water time implementing this.

**Comment by TanteOctopus** [comment]
The point isn't really to disrupt schematic designers, it's more for those of us (like me) who will drop a water extractor next to an airblast drill 15 squares from a lake.

**Comment by IxGamerXL** [comment]
There isn't much doubt that someone's going to make a logic processor that drops copper to all existing water extractors using units, so I'm not sure if this would be useful to decrease the convenience apart from requiring people to invent/have something that makes water extractors do exactly the same thing as they did before the inconvenience update.

Also, some of us (like me) are going to be using Dev Mode or our own crazy javascript mods that automatically fuel extractors, turning the user into the gamma equivalent of a mono. Hell, one of us may already have a flow-based mod that makes you do things depending on the events that come.

When you combine processors and Dev Mode with people who are willing to create huge processes of machinery out of their intellect, resources, and wits, the inconvenience essentially drops to nil. Sure, campaign doesn't offer much leeway in terms of early-game tech, meaning you don't really have logic in general until you've reached mid-game.

Unless we can retain the inconvenience without heavily nerfing the water reactor (as if V6 nerf wasn't bad enough), this might not be possible.

**Comment by TanteOctopus** [comment]
Couldn't the same argument be made for any factory, though?  

I don't really know.  I'm still a mid-level mindustry player - not a total noob, but I'm not really familiar with high level play.  It's possible this entire suggestion was totally off base.  But the point of my suggestion was that attempts to nerf water extractors by dropping water production or increasing energy usage or production cost are missing the heart of why extractors are overused, which is that they're just extremely convenient.  Requiring input was my attempt to try and fix that, but I fully acknowledge that it might not be the best way, or might not work at all.

And don't necessarily discount a solution which only works on lower level players.  Not everyone who plays mindustry uses mods or logic.  And there's a certain joy to picking up logic for the first time, and realizing that you can use it to solve irritating problems you haven't been able to deal with easily before, and that's not a bad thing to have in the game.

**Comment by itcannotbe** [comment]
The previous nerfs was meant to kill power cubes in favor of more sensible ways to make power.

**Comment by OnyxFinger** [comment]
It's not because they get used too much that they're too good : the players that use them too much are bad.

**Comment by RealYeet** [comment]
*A simple yet effective solution to the water extractor problem is just to remove it from the game.*

**Comment by IxGamerXL** [comment]
> *A simple yet effective solution to the water extractor problem is just to remove it from the game.*

**Insert thousands of schematics getting broken**

**Comment by BlueWolf3682** [comment]
I entirely agree with the suggestion... even if you set up a wext feeding mechanism via logic, that is still more work than placing conduits a few tiles. I would say one metaglass every 6 - 9 seconds, explainable by the piping needed for underground drilling.
~~not to mention, it would be hilarious to see the communitys reaction to literally all """curated""" and most regular schematics being obsolete.~~

**Comment by IxGamerXL** [comment]
> I entirely agree with the suggestion... even if you set up a wext feeding mechanism via logic, that is still more work than placing conduits a few tiles.

How so? We can literally make a schematic that searches out for every water extractor and fuel them as so. And like I said, there are some mad lads out thee that'll spend their time making mods that completely nullify this requirement through some sorcery combined with JS.

> I would say one metaglass every 6 - 9 seconds, explainable by the piping needed for underground drilling.

If you want this to be more of a requirement, you might need to make it every 1 - 2 seconds.

> Meta also remains largely unused and bulks quickly, so more use of it would be cool.

Unless you're in Attack/PvP games, then that metaglass runs out fast if you don't have a constant supply of metaglass. All of that metaglass will likely be drained for T3 units.

> ~~not to mention, it would be hilarious to see the communitys reaction to literally all """curated""" and most regular schematics being obsolete.~~

## laugh.mp3

**Comment by IxGamerXL** [comment]
![20220105_091615.jpg](https://user-images.githubusercontent.com/90928500/148241702-ac999bdf-a52a-4557-8918-bc502081ac59.jpg)

Meanwhile a couple of DDNS members reacting to this suggestion as a whole.

**Comment by itcannotbe** [comment]
> I entirely agree with the suggestion... even if you set up a wext feeding mechanism via logic, that is still more work than placing conduits a few tiles. I would say one metaglass every 6 - 9 seconds, explainable by the piping needed for underground drilling. Meta also remains largely unused and bulks quickly, so more use of it would be cool. ~not to mention, it would be hilarious to see the communitys reaction to literally all """curated""" and most regular schematics being obsolete.~

You forgot the part where in those same designers whose schematics got broken also works around the problem and we're back where we started.

**Comment by RealYeet** [comment]
Maybe a potential fix it to make the water extractor a 3x3 block but buff output by 50%? Makes it harder to use but doesn’t make it obsolete. At least people will consider using them in groups like pumps unlike right now where everything has its own water extractor

**Comment by BlueWolf3682** [comment]
> How so? We can literally make a schematic that searches out for every water extractor and fuel them as so. And like I said, there are some mad lads out there that'll spend their time making mods that completely nullify this requirement through some sorcery combined with JS.

That is only for single player - the community dedicated servers cannot have mods.

> If you want this to be more of a requirement, you might need to make it every 1 - 2 seconds.

For a hundred water extractors, that easily gets to be a lot of metaglass. It should be reasonable, and force players to build extra infrastructure but not ridiculous amounts of it.

> Unless you're in Attack/PvP games, then that metaglass runs out fast if you don't have a constant supply of metaglass. All of that metaglass will likely be drained for T3 units.

![image](https://user-images.githubusercontent.com/61173114/148303401-0cace455-a14a-4138-affe-5051bfa5adfb.png)
...one kiln produces 2 metaglass per second. Build something actually respectable, not some half-assery.

**Comment by BlueWolf3682** [comment]
The last, extra concern i must address - logic may solve this issue, but not without a lot of units enslaved. A flare simply doesnt have the item capacity to deal with suuplying more than about 20 wexts, and nonetheless that is still extra effort as it requires supporting stuff.

**Comment by IxGamerXL** [comment]
> > How so? We can literally make a schematic that searches out for every water extractor and fuel them as so. And like I said, there are some mad lads out there that'll spend their time making mods that completely nullify this requirement through some sorcery combined with JS.
> 
> That is only for single player - the community dedicated servers cannot have mods.

*cough cough* Multiplayer Supported mods *cough cough* Dev mode *cough cough cOUGH*

> > If you want this to be more of a requirement, you might need to make it every 1 - 2 seconds.
> 
> For a hundred water extractors, that easily gets to be a lot of metaglass. It should be reasonable, and force players to build extra infrastructure but not ridiculous amounts of it.

And someone who organizes a javascript right is a man who can fuel almost hundreds in very little time. Units can pick up items and drop them from very far away, so that's out of the question.

> > Unless you're in Attack/PvP games, then that metaglass runs out fast if you don't have a constant supply of metaglass. All of that metaglass will likely be drained for T3 units.
> 
> ![image](https://user-images.githubusercontent.com/61173114/148303401-0cace455-a14a-4138-affe-5051bfa5adfb.png)
> ...one kiln produces 2 metaglass per second. Build something actually respectable, not some half-assery.

20 Kilns = 40/s Meta, T3 Reconstructors takes more than double of that, and even if it didn't, you are gonna need quite a bit of T3s to make a difference. Like I said, you need more than just a supply, you need a constant supply. You can't tell me that T2 units are going to work in a PvP match unless the other team is a sitting duck.

**Comment by BlueWolf3682** [comment]
Note that that kind of JS mod ***REQUIRES*** it to be enabled on a server. Unit behaviour and reaource costs are handled serverside.

**Comment by BlueWolf3682** [comment]
If you do not like the suggestion, just say it. Do not waste our time with irrelevant comments.

**Comment by IxGamerXL** [comment]
> Note that that kind of JS mod ***REQUIRES*** it to be enabled on a server. Unit behaviour and resource costs are handled serverside.

Mods can manipulate your unit to do things automatically. They don't need access to the server console, they only need to tell the unit to do certain things and then the server accepts it as player inputs.

Maybe before you start making such claims, you should learn what the game's Javascript can do first.

**Comment by BlueWolf3682** [comment]
I know what it can do, as I am one of the more known modders. However, it would be even less efficient to use that strategy, as it would incapacitate the player in question. 
Logic would be far more preferable, as it automates the process without using the players.

**Comment by IxGamerXL** [comment]
> I know what it can do, as I am one of the more known modders. However, it would be even less efficient to use that strategy, as it would incapacitate the player in question. 

That is true, but it doesn't stop the modder from making a switch to toggle between serving metaglass and normal behavior. If even one player is deticated into becoming one with the Mono, then the nerf can end up practically invisible.

> Logic would be far more preferable, as it automates the process without using the players.

Add that up with some Hyper Processors carrying the unit process OR Overdrive Projectors + Logic Processors and here we are again, with the nerf being cured from existence.

Any idea how else we could make the Water Extractor less convenient and not impaired from normal use?

**Comment by itcannotbe** [comment]
> Maybe a potential fix it to make the water extractor a 3x3 block but buff output by 50%? Makes it harder to use but doesn’t make it obsolete. At least people will consider using them in groups like pumps unlike right now where everything has its own water extractor

This is what may break most compacts chematics, which would be a great start. Now we would need to address slapping a water extractor on, INSTEAD OF ACTUALLY GETTING WATER FROM THE WATER POOL THAT LITERALLY NEXT TO THE BLOCK.

**Comment by hortiSquash** [comment]
i'd suggest coal instead of copper because coal filtering of water (like 1 coal every 30? seconds)

keep in mind there is also the other way around, output:
make them output dirty water that you need a new filter block to make into clean usable water
or make them output mud (item) that you need to take out to avoid clogging

in both cases its extremely simple to implement in the game

**Comment by Facosa99** [comment]
> ... make them output mud (item) that you need to take out to avoid clogging (item totally useless, to add a much needed use to the incinerator)

i would like that for the thor reactor. but not being able to incinerate it tho. some sort of nuclear waste you need to get rid of. To mirror real life, you could just toos it into a vault and forget about it. once the vault is filled, you gotta build more. If you destruy them, nuclear waste will basically make a zone unable to hold complex electronics.

**Comment by itcannotbe** [comment]
> i'd suggest coal instead of copper because coal filtering of water (like 1 coal every 30? seconds)
> 
> keep in mind there is also the other way around, output: make them output dirty water that you need a new filter block to make into clean usable water or make them output mud (item) that you need to take out to avoid clogging (item totally useless, to add a much needed use to the incinerator)
> 
> in both cases its extremely simple to implement in the game

I think "dirty" water maybe a good option, though for it to be even be considered it needs to have other uses.

**Comment by IxGamerXL** [comment]
> i'd suggest coal instead of copper because coal filtering of water (like 1 coal every 30? seconds)
> 
> keep in mind there is also the other way around, output:
> make them output dirty water that you need a new filter block to make into clean usable water
> or make them output mud (item) that you need to take out to avoid clogging (item totally useless, to add a much needed use to the incinerator)
> 
> in both cases its extremely simple to implement in the game

Having some form of Hydroneer aspect of having to process water that was extracted from a power taxing device, sounds a bit too complicated. Also agreed with the comment already saying this: For it to be considered it needs to have other uses.

In general, if someone hated the nerf so bad, they'll likely create work arounds of any kind, often leading the development of the nerf to the point of unfruitfulness.

**Comment by TanteOctopus** [comment]
I'm confused by the argument that people will make mods to solve this.  I don't know much about mods - is there any problem that mods _can't_ solve?  Couldn't someone make a mod that adds a building that produces infinite water for free?  Or are there limitations to what mods can do that I'm unaware of?

**Comment by TanteOctopus** [comment]
Regarding breaking of existing schematics - if water extractors need fixing, then there's no fix that's not going to break schematics right and left.  That's the cost of doing business.  Whether water extractors need fixing enough to be worth that cost (or even need fixing at all) is not a judgement call I'm even pretending I'm qualified to make.

**Comment by itcannotbe** [comment]
> Regarding breaking of existing schematics - if water extractors need fixing, then there's no fix that's not going to break schematics right and left. That's the cost of doing business. Whether water extractors need fixing enough to be worth that cost (or even need fixing at all) is not a judgement call I'm even pretending I'm qualified to make.

Any change you make to a block in terms of it's input, outputs, and size breaks schematics. There isn't a way around it*.

**Comment by Facosa99** [comment]
> Although that, the nuclear waste idea does sound cool @Facosa99, you should submit it as a suggestion if you haven't already.

Thanks. I´ve never uploaded a sugestion before, but i might try @IxGamerXL

**Comment by itcannotbe** [comment]
> > Although that, the nuclear waste idea does sound cool Facosa99, you should submit it as a suggestion if you haven't already.
> 
> Thanks. I´ve never uploaded a sugestion before, but i might try IxGamerXL

Didn't someone suggested that before?

**Comment by RealYeet** [comment]
We need a solution that will fix water extractors but not make them obsolete. That is why I feel like making it bigger but out put more water is a decent idea. Anything else like making it emit a toxic waste or water that needs to filtered would make it fall out of favor as there would be no reason to use it, due to the fact that you would need to build a whole new factory to use it anywhere. In all reality and play testing with the game. The thing that would help pumps a lot is making through out of conduits a lot higher.

**Comment by Bassem-Const** [comment]
> > _A simple yet effective solution to the water extractor problem is just to remove it from the game._
> 
> **Insert thousands of schematics getting broken**
> 
> It might be effective but maps that have very few water points would be likely impossible/tedious without water extractors. The meta would alter too much for players to handle, and we are already going to have a change in unit AI for V7.

Ok, then every schematic designer will take saying that external water schematics are bad back.

**Comment by Bassem-Const** [comment]
> We need a solution that will fix water extractors but not make them obsolete. That is why I feel like making it bigger but out put more water is a decent idea. Anything else like making it emit a toxic waste or water that needs to filtered would make it fall out of favor as there would be no reason to use it, due to the fact that you would need to build a whole new factory to use it anywhere. In all reality and play testing with the game. The thing that would help pumps a lot is making through out of conduits a lot higher.

Umm, anuke is planning to limit the throughput.

Also, J U N C T I O N
