### ISSUE TITLE
More options for wave timers

### ISSUE THREAD

**Issue by djradnad** [Anuken/Mindustry-Suggestions#3280]
### Describe the content or mechanics you are proposing.

for example being able to set it so that waves become increasingly faster, or groups of waves have different timers. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Normally, it is nice to have time between waves to reload weapons and such, but with this mechanic we could make maps that have various new obstacles to overcome :)

p.s. sorry i didnt actually look if it was sugged before. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Another idea : Make the time before the first wave customizable (Right now it's something like 2-3× the "normal" wave spacing)
