### ISSUE TITLE
Lava, Furnace, Thermoresistant Pump, Tsunami changes

### ISSUE THREAD

**Issue by NrkSed** [Anuken/Mindustry-Suggestions#3282]
### Describe the content or mechanics you are proposing.

**Lava**: Lava will be a liquid transportable with conduits. It can be obtained either by a **Thermoresistant Pump** or a **Furnace**. It can work like a weapon or a replacemnt for pyrite in some cases.

**Thermoresistant Pump**: This is a pump that can pull out lava from lava lakes/rivers. It will be a 3x3 block and building it will require Silicon, Titanium, Metalglass, and a bit of Thorium to build. It will also require small amounts of power to run, Its basically a pump for lava.

**Furnace**: This is the second way of obtaining lava. The furnace will be a 3x3 block which will require a significant amount of power to run. It can be placed anywhere, but placing it on hot rocks will make it more efficient. To make lava, it will require Sand, Copper, Lead, Pyrite, and as already mentioned, a significant amount of power. In order to build the Furnace you will need Metalglass, Titanium, Plastanium, Silicon. It will output lava just like a water extractor outputs water.

**Changes to Tsunami**: Tsunami will now be able to shoot lava. Lava will add the melting status to enemies and do extreme damage to enemies and add a bright orange glow in the dark. However, to compromise the extreme damage of lava, the Tsunami will need 10s to cool down. (Maybe, if you also feeded water alongside lava, the cooldown would drop to 7s, and if you feeded cryofluid, it would be 5s) 

**Other Lava uses**: Lava could be used as a replacement for Pyrite or BC And if this gets added, Anuke might find different uses such as a lava seperator or such.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Lava would add more ways to defend your base without adding a new weapon or structure. It will also add 2 new factory blocks, and making another liquid which can be used as a weapon. It will also add exotism to the game and give a use to lava lakes alongside them being barriers for land units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Slag moment...

**Comment by IIINSTINCT** [comment]
Bruh

**Comment by SMOLKEYS** [comment]
Slag:

Mechanical (T1) pumps extracting slag:

(Scrap) Melter:

...

(Slag) Seperator:

**Comment by SMOLKEYS** [comment]
I'm gonna assume this is a shitpost, since ***you can't be that stupid and blind*** to not know Slag exists.

**Comment by SwitchLikesMlog** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
i can totally see that

**Comment by Bottinator22** [comment]
The amount of people who don't understand a thing about the game...

**Comment by Falling10fruit** [comment]
Stop it, get some help

**Comment by itcannotbe** [comment]
![Stop it. Get some help.](https://c.tenor.com/mlbw-RHwclEAAAAM/stop-it-get-some-help.gif)

**Comment by NrkSed** [comment]
@Bottinator22 I have played the game for a few months, and yes I did know about slag when writing this post. If added, Lava would do more damage than slag, so do please understand before commenting.

**Comment by itcannotbe** [comment]
> @Bottinator22 I have played the game for a few months, and yes I did know about slag when writing this post. If added, Lava would do more damage than slag, so do please understand before commenting.

@NrkSed I have played the game for years already, and yes you don't know that lava was changed to slag years ago, plus the developer said ...

![https://discord.com/channels/391020510269669376/396416151032299521/698182464320831498](https://user-images.githubusercontent.com/45280919/148095562-6393f411-8aa8-4091-a40a-334f80c2b83d.jpg)

**Comment by NrkSed** [comment]
@itcannotbe I never said I knew that lava got changed to slag, due to me not playing the game for a while.

**Comment by Bottinator22** [comment]
> @itcannotbe I never said I knew that lava got changed to slag, due to me not playing the game for a while.

Maybe you should've understood before suggesting

**Comment by NrkSed** [comment]
@Bottinator22 What do you mean understood? If I missed the update/development of update then I missed it.

**Comment by Falling10fruit** [comment]
> @Bottinator22 What do you mean understood? If I missed the update/development of update then I missed it.

Then that means that you had broken the second term and condition:

>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by NrkSed** [comment]
@Falling10fruit I am familiar with the content in game, and I do know that SLAG exists but because i did not play for a bit I didn't know that SLAG was originally LAVA. I wanted to suggest something similar to SLAG and in my mind LAVA would do more damage than SLAG.
