### ISSUE TITLE
Mindustry Logic some sort of (memory) stack

### ISSUE THREAD

**Issue by DasBabyPixel** [Anuken/Mindustry-Suggestions#3283]
### Describe the content or mechanics you are proposing.

Some stack behavior in logic to do operations like push or pop.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be useful for recursive functions and generally making it easier to implement some features. I do know that everything a stack feature would add is already achievable by being a mad man with the memory- cell/banks but doing it that way costs a lot of operations and is slow. As I said, its possible without adding a new feature but it would be very convenient to add a stack feature. If you like the idea but do not have the time to implement it, I would be willing to implement it and create a pull request.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Phinner** [comment]
You sure it's absolutely necessary ? I mean `mlog` is meant to be simple so I don't think the average Mindustry player could take advantage of these advanced features such as functions and recursion. Also, there's Anuke saying:

> my response is the same as the messages linked at https://discord.com/channels/391020510269669376/396416151032299521/926448819758043136: logic must not allocate, it must be easy to learn, parse and understand, and it must not encourage complex O(n) operations like string manipulation. I've never used basic or scratch.

**Comment by DasBabyPixel** [comment]
I guess if the goal of logic is to keep it simple, then its not absolutely necessary. As I said, it is achievable by using the memory-cells and memory-banks, but every push/pop would take about 10 operations (If we're talking about a scalable system) and the initialization process of such system would be looping through every link twice, doing a bunch of operations for every link (twice) and as such would be very slow. My suggestion is making something that can already be done a very hard way more simple with some easy to implement operations.

**Comment by itcannotbe** [comment]
> You sure it's absolutely necessary ? I mean `mlog` is meant to be simple, and I don't think the average Mindustry player could take advantage of these advanced features such as functions and recursion. Also, there's Anuke saying:
> 
> > my response is the same as the messages linked at https://discord.com/channels/391020510269669376/396416151032299521/926448819758043136: logic must not allocate, it must be easy to learn, parse and understand, and it must not encourage complex O(n) operations like string manipulation. I've never used basic or scratch.

~This is the reason I actually insisted anuke to be the one who will answer my query, to be used in cases like this~

**Comment by Phinner** [comment]
> > sure it's absolutely necessary ? I mean `mlog` is meant to be simple, and I don't think the average Mindustry player could take advantage of these advanced features such as functions and recursion. Also, there's Anuke saying:
> > > my response is the same as the messages linked at https://discord.com/channels/391020510269669376/396416151032299521/926448819758043136: logic must not allocate, it must be easy to learn, parse and understand, and it must not encourage complex O(n) operations like string manipulation. I've never used basic or scratch.
> 
> ~This is the reason I actually insisted anuke to be the one who will answer my query, to be used in cases like this~

What query ?

**Comment by DasBabyPixel** [comment]
I guess this is not going to happen. Sad but okay
