### ISSUE TITLE
build blocks

### ISSUE THREAD

**Issue by Kartongbit** [Anuken/Mindustry-Suggestions#3284]
### Describe the content or mechanics you are proposing.

build blocks will automatticly rebuild destroyed blocks in its range.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

what does niche mean? anyways i think it will improve the game by being an option for polys.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
wh

**Comment by itcannotbe** [comment]
Can someone make the suggestion not confusing to understand?

**Comment by itcannotbe** [comment]
Also polys already can rebuilds destroyed blocks.

**Comment by EclipseTheOldOne** [comment]
anuke already leak a turret cappable of doing that

**Comment by NrkSed** [comment]
In that case you would never go to your defences and focus on your infrastructure because even if some blocks are destroyed

**Comment by Ymabert** [comment]
it is necessary to have something that rebuilds, the point is that for now we can only use the "poly" so I don't find it a bad idea to have a tower that rebuilds everything that is destroyed in its radius, maybe it would be right that it is slow to rebuild, however it would be very useful when at the moment you do not have the possibility to create / have poly in that particular place.

**Comment by Falling10fruit** [comment]
My entire army of Polys at the Nuclear Production Complex died because of this.

**Comment by PizzaBurgz** [comment]
that would be useful as it will automatically rebuild destroyed blocks, but, where does it take resources from to rebuild? Core? Input?

**Comment by EclipseTheOldOne** [comment]
it's planned, wait and see

**Comment by end-me-please** [comment]
The turrets were talked about in #development a while ago, but without many details

 A building turret that can build with conveyor input would be really cool tho.
Unit building is pretty powerful but disabled on servers because of griefing. Constructors make build logic possible in multiplayer, but that still relies on (unit-cap limited) payload units.

**Comment by Ymabert** [comment]
@PizzaBurgz and where do the "poly" get the resources from?  core or entrance?  it is better to leave the system thus, the same as that of poly

**Comment by Ymabert** [comment]
@end-me-please In my opinion the logic is very useful, but having to use units with many other functions other than that of material transport I think it is a waste of units, in fact if robots based solely and exclusively on transport are added (therefore rapid units with high capacity of transport) the game will take a huge step forward (not that it is now behind, but it would be good to have as many things available as possible, so as to also have many more strategies)

**Comment by end-me-please** [comment]
Item transport drones without logic have been shown in the development channel

**Comment by itcannotbe** [comment]
> >  in fact if robots based solely and exclusively on transport are added (therefore rapid units with high capacity of transport) the game will take a huge step forward (not that it is now behind, but it would be good to have as many things available as possible, so as to also have many more strategies)
> 
> Item transport drones without logic have been shown in the development channel

Not exactly.....

**Comment by Kartongbit** [comment]
peopel are saying that anuke alredy planned this. srry for not knowing.

**Comment by Ymabert** [comment]
Top
