### ISSUE TITLE
Improving the AI ​​that builds

### ISSUE THREAD

**Issue by RedMatrix1** [Anuken/Mindustry-Suggestions#3285]
### Describe the content or mechanics you are proposing.

I would like the AI ​​not to have an infinite number of resources, but to extract everything on its own, this could be configured in the rules settings, I would also like the AI ​​to be in my team I would also like to be able to give him a nickname, sorry for "I would like to", but my English vocabulary is small.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would help a lonely player who is bored and there is no network, or if the servers have FPS = 5

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Falling10fruit** [comment]
Great idea! Because of the AIs at the 1v1 lobby spam and it's so irritating.

**Comment by RedMatrix1** [comment]
males?

**Comment by Nils101** [comment]
Sorry to disappoint you but this is unlikely to happen. If I remember correctly when anuke added AI autobuilding he stated that it was Impossible or too hard to make it play like an actual human. It would take way to much time to code something like this. 
You might have some success with a neural network but I'm not experienced in that field

**Comment by Falling10fruit** [comment]
> males?

You said **him**

> I would also like to be able to give **him** a nickname

**Comment by OnyxFinger** [comment]
> Great idea! Because of the AIs at the 1v1 lobby spam and it's so irritating. Also, when were AIs males?

> You said **him**

In many languages, there is no neutral/object genre, so it's either him or her.

>  Sorry to disappoint you but this is unlikely to happen. If I remember correctly when anuke added AI autobuilding he stated that it was Impossible or too hard to make it play like an actual human. It would take way to much time to code something like this.
You might have some success with a neural network but I'm not experienced in that field

This is exact. Anuke stated that the AI are too hard to code in a way that they can handle ressource management. However I belive that there could be a sort of gathering system to make it look more "real" (where it would try to gather X ressource and in doing so can unlock some buildings, but not necessarily having to connect the harvested ressources to the core or having to gather enough of them to build). This brings another problem with the AI, which is that now there probably needs to be a build order for the AI, that way it doesn't stay at low tech for too long. A single build would be too repetitive, so multiple have to be made and it takes a long time.

**Comment by RealYeet** [comment]
The ai is more of an i right now, it does not learn, it just builds.

**Comment by RedMatrix1** [comment]
I'll try to trick something with the logic of mods, and the standard AI, if possible, will be GREAT

**Comment by RedMatrix1** [comment]
> Отличная идея! Из-за АИС в лобби 1 на 1 спам, и это так раздражает. Кроме того, когда ИИ были мужчинами?

Translator from one Russian company) translated as follows
