### ISSUE TITLE
Android version V7

### ISSUE THREAD

**Issue by GuVi171819** [Anuken/Mindustry-Suggestions#3286]
### Describe the content or mechanics you are proposing.

I'd Like to have V7 in my Handy fromm Google Play.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Just add it!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
That's not how that work.

Also v7 is planned to be a paid app on the google play store.

Downloads from Itch.io will still be updated though.

**Comment by IIINSTINCT** [comment]
Be patient.....
V7 on playstore will be added once it is finished but its not free anymore and perhaps you dont have money buy it.

**Comment by end-me-please** [comment]
Just download the v7 APK from https://anuke.itch.io/mindustry
