### ISSUE TITLE
Project MSGA (Make scrap great again)

### ISSUE THREAD

**Issue by GuVi171819** [Anuken/Mindustry-Suggestions#3287]
### Describe the content or mechanics you are proposing.

Add more usages Form scrap and/or slag

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Scrap woud bei used mich more.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Scrap was and is still not great.

The premise of this suggestion is clearly lacking brain cells.

**Comment by GuVi171819** [comment]
Maybe

**Comment by GuVi171819** [comment]
maybe a

**Comment by GuVi171819** [comment]
> 

Maybe a Kind of washer or Something Like that.

**Comment by IIINSTINCT** [comment]
Dont spam close and reopen bruh

**Comment by itcannotbe** [comment]
> Dont spam close and reopen bruh

Based on what happened. I think OP is using a shitty internet connection.

**Comment by itcannotbe** [comment]
> > 
> 
> Maybe a Kind of washer or Something Like that.

What? This is even more confusing.

**Comment by random-guy1285** [comment]
There are actual playable maps where the goal is to survive with only scrap. If that's possible there is no buff needed.

**Comment by SMOLKEYS** [comment]
@GuVi171819 can you not fucking spam the #github channel?
