### ISSUE TITLE
Enemy Artillery

### ISSUE THREAD

**Issue by NrkSed** [Anuken/Mindustry-Suggestions#3288]
### Describe the content or mechanics you are proposing.

On high threat sectors, on the last wave a Guardian appears. My suggestion is that on some sectors, every 5 waves (Except the last wave) there is an Artillery strike. It wont do much, just three random locations are chosen and striked with Artillery. It shouldn't do very much damage or be game-changing. Locations on the map where Artillery has hit will be marked on the minimap, making finding damaged infrastructure easy.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be a detail that will make every 5th wave a bit harder, so players dont make defences near the drop zone and then completely forget about it because they know that it will hold up to the attack. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
This does not sound like a good idea, artillery strikes (or things similar to them) have been suggested before and the overall feeling is that they are un-needed.

**Comment by Ymabert** [comment]
why do I have to go from the 5th wave already?  I prefer to play quietly until I have a lot of resources and a small base.
