### ISSUE TITLE
Ability to add notes in Logic Proccesor code (via dedicated NOTE code block)

### ISSUE THREAD

**Issue by rawsewage38** [Anuken/Mindustry-Suggestions#3289]
### Describe the content or mechanics you are proposing.

 What I'm suggesting is a new logic proccesor code block called _NOTE_ which allows you to put strings of text inside of your code, and have them easily viewable when editing inside of the logic proccesor instead of a variable with the _SET_ or a string using _PRINT_. These strings of text will not be able to be used in any other part of the code, and can only be viewed when editing logic proccesor code. Thus, making them perfect for describing functions of your code when viewed in the editor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I've seen alot of people (myself included) using _PRINT_ commands to add notes in their code. The problem with this, is that it's only effective if your logic doesn't use _PRINT_ statements as the main part of its code, and becomes annoying to _PRINT FLUSH_ a statement to a message block you are never going to use, just for the sake of having a note.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
So it's basically a Comment block, like //

Having a deticated comment block that doesn't have processing time wasted on it would be good. Kinda like a text area instead of just a text field would be very nice.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry/pull/6459
