### ISSUE TITLE
Fast forward

### ISSUE THREAD

**Issue by Niepsho** [Anuken/Mindustry-Suggestions#329]
Fast forwarding would be super nice especially when building big things

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This is the first thing mentioned in the "do not suggest" list.
