### ISSUE TITLE
Indestructable walls for map editor

### ISSUE THREAD

**Issue by Qusika2** [Anuken/Mindustry-Suggestions#3290]
### Describe the content or mechanics you are proposing.

try making a wall that can't be destroyed

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

giving the map designers more freedom

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
### Laughs in actual environment walls

**Comment by NrkSed** [comment]
wow

**Comment by OnyxFinger** [comment]
> ### Laughs in actual environment walls

actually they don't block shots/too many of them wjll make spiders unable to go over them

**Comment by itcannotbe** [comment]
> > ### Laughs in actual environment walls
> 
> actually they don't block shots/too many of them wjll make spiders unable to go over them

So why do you want this in the first place? (Maybe third place, I think this is the third suggestion of this)
