### ISSUE TITLE
Some Item Name, Some Factory Name, Some Block Name

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3292]
### Describe the content or mechanics you are proposing.

(Some Factory Name): A (Size Here) Structure that can be built with (Items Here).
When provided with power, a little amount of (Input Item) and (Liquid Here) will create (Some Item Name).

(Some Item Name): If added, (Some Item Name) could be used for some crafting recepies, or perhaps as ammo for turrets.

(Some Item Name) walls: Walls that are made out of (Some Item Name) (duh). Has large and small variants like other types.
Large variant has;(HP Value Here) HP. I couldn't decide which Unique property it should have and adding both would make it OP so I think you should decide:

    Takes little or none damage from (Status)
    Or
    (Effect Here) its (Block Stats Here) over time on its own

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will give another use for (Liquid Here), add some more complexity to crafting and add a new set of walls that could be useful in some cases (Dependant on which property is chosen), Or a new type of ammunition

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Is this supposed to be a sort of sarcastic suggestion ?

**Comment by Ruichka** [comment]
> Is this supposed to be a sort of sarcastic suggestion ?

yes #3291

**Comment by NrkSed** [comment]
Ok, But why?
