### ISSUE TITLE
Add team frienship for custom maps/games

### ISSUE THREAD

**Issue by CalibriLight** [Anuken/Mindustry-Suggestions#3293]
### Describe the content or mechanics you are proposing.

Add team friendship setting in Custom rules/customize rules. Using "team friendship" you can enable from 2 to 5 teams, after enabling team friendship picked commands will not able to damage each other. Example: if you picked "green - red - grey" and "blue - yellow" Green and grey teams can not damage red, blue can't damage yellow but red can damage blue

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will be cool for attack/pvp modes

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/3242#issuecomment-997044124

**Comment by CalibriLight** [comment]
> [#3242 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/3242#issuecomment-997044124)

_sad ending_

**Comment by itcannotbe** [comment]
Also...

- [X] You have not read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.-

**Comment by CalibriLight** [comment]
Oh no I am blind
