### ISSUE TITLE
Player shield bar.

### ISSUE THREAD

**Issue by Andraez** [Anuken/Mindustry-Suggestions#3294]
### Describe the content or mechanics you are proposing.

basically something [like this](https://imgur.com/a/DYmlAvd), two bars that represent your shield's integrity by how full they are.

[and when the shield is disabled, the bars would turn a dim red.](https://imgur.com/omzqj46)

so it would look something [like this](https://imgur.com/eZHR7qy) at ~40% health.

im sure you get the idea.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

really there is no reason to not implement it in one way or another.
if you can view the shield health of other units by hovering over them, you should at least be able to see your own shield's health.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by random-guy1285** [comment]
I thought this already existed

**Comment by OnyxFinger** [comment]
> I thought this already existed

There is a counter for health and ammo, but not shield

**Comment by SMOLKEYS** [comment]
> I thought this already existed 

It does exist, but you can't see the shield health of the unit you're controlling.
