### ISSUE TITLE
Item name on hover

### ISSUE THREAD

**Issue by SomeFamousPerson** [Anuken/Mindustry-Suggestions#3295]
### Describe the content or mechanics you are proposing.

Hovering over an item- i.e. Titanium, in a menu or popup- i.e. the required resources on the sidebar will tell you it's name, so people ho aren't as experienced and can't recognise items by name don't need to find the building in the build menu and click on the information menu. It would also help distinguish similarly skinned items such as Graphite and Titanium.
https://imgur.com/a/OfWJ9xW (image upload to the textbox didnt work)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will add slight ease of access and prevent annoying mistakes such as bringing in conveyers of the wrong resource, which is just plain annoying. There is literally zero possible negative side effects, so there's no real reason not to have it, and it's the sort of basic feature many people are surprised isn't already in the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This can be helpful for people who play with mods

But this is just a nuisance for mostly everyone who played the vanilla campaign, since items in campaign are gradually researched, thus letting players slowly familiarize themselves with the items.

**Comment by NrkSed** [comment]
I agree that this could be useful in rare cases, especially for mods, but you differ two things not only from their colours, but their shapes also. Players will easily differ the lightly coloured Graphite which is a big square and the darker coloured Titanium in the shape of an ingot

**Comment by oinkymoo** [comment]
plastanium and surge are very similar shapes and are also colors that could be easily confused with color blindness. also blast and pyra are identical except for color

**Comment by Ymabert** [comment]
it is not better that by typing a certain key on a material, whether it is already in the core or on a tape, the functions that it can have come out, both in the construction and in the creation of other materials, for example if I press the key for information on a material from the core / from the conveyor belt / from the bar at the top indicating the materials I have stored is shown to me, through a window located in the middle right of the screen (so above the usual inventory window of all buildings and above the info dates from the block selected in the inventory), everything related to the material, then what can be built (everything is listed in order from the things that only require this material to be created, to the things that require both this material and many others) and which material / liquid can be created, through the particular block and if there is the specific material with which it must be mixed.

**Comment by Ouaz** [comment]
> Hovering over an item- i.e. Titanium, in a menu or popup- i.e. the required resources on the sidebar will tell you it's name, so people ho aren't as experienced and can't recognise items by name don't need to find the building in the build menu

Agree with you, but actually, it would be much simpler to add the info button on an already built block sidepanel, like suggested here: https://github.com/Anuken/Mindustry-Suggestions/issues/3246

![add_info_button](https://user-images.githubusercontent.com/11946570/148654860-4b878b6c-685b-492d-8581-32e655c748cb.png)

Not being able to access quickly the block info screen (outside of the build menu) is an annoyance **only** on Android, as there is a hotkey for that on PC version (hover a block on the map, then press F1, opens the block info screen).
On Android, the player has to search the block in the build menu each time he needs to display its info screen, and it's really tedious.
