### ISSUE TITLE
Riceiver

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3297]
### Describe the content or mechanics you are proposing.

I would like to propose a resource receiver that placing it next to a core / deposit causes the launchers to shoot the materials at the receiver and arrive directly in the core, before I start talking about how to develop the idea I first want to know if it is a good idea (so if it can allow you to make other developments to the game).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Size 3x2

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You could just slap the mass driver next to the extended core.

**Comment by Ymabert** [comment]
you could be more helpful by giving advice consistent with what is suggested, such as saying how this idea could be spread, what could therefore bring a future, just from the fact that the usefulness of this thing is only one, that is receive and carry the materials directly into the core / deposit, so if you do not want to place too many conveyor belts but you want the materials to arrive directly in the core (just as a material launcher receives all the materials in one shot I believe that an object with the same function is useful), possibly with a maximum number of receptions, given by an instant disposable capacity, simply place a "receiver" (it works that the launchers throw the materials at him alternating one at a time, then it all depends on how much it is the receiver is full, otherwise even more than one launcher can fire the materials).

**Comment by itcannotbe** [comment]
So what does this do that a mass driver can not?

**Comment by itcannotbe** [comment]
Things a Mass Driver can do* when placed next to the core/extended core:

- [X] simply place a "receiver" (it works that the launchers throw the materials at him alternating one at a time, then it all depends on how much it is the receiver is full, otherwise even more than one launcher can fire the materials).
- [X]  that is receive and carry the materials directly into the core / deposit, so if you do not want to place too many conveyor belts but you want the materials to arrive directly in the core

**Comment by NrkSed** [comment]
Mass drivers already exist in the game, and it is basically the same thing that you just suggested.

**"I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet."**

^ And that is why this exists ^

**Comment by Ymabert** [comment]
...

**Comment by SMOLKEYS** [comment]
> Size 3x2
