### ISSUE TITLE
Easier way to localate coordinates

### ISSUE THREAD

**Issue by NrkSed** [Anuken/Mindustry-Suggestions#3298]
### Describe the content or mechanics you are proposing.

Currently, the only way to know coordinates in game is to either use mods or turn on a setting in settings.

It would be nice to add a small "pen" icon in a processors menu, that when clicked will pause the game and let you click any tile and copy that tiles information to the boxes where coordinates are inputed (Similarly to a colour picker picks a colour)

Now i know that mods can already do that but it would be nice to have it in game

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will add a ton of convenience to the game, and it will also make getting the coordinates of an unreachable area ( like an area guarded by 50 thousand Specteres ) possible to find out

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
that's:
* hard to implement: anuke would probably have to create a new input handler just for this feature
* useless as you can and should use relative coordinates or a turret for specifying a target location. hardcoding such variables is a bad practice
