### ISSUE TITLE
Feedback: phantom drones

### ISSUE THREAD

**Issue by ClockeNessMnstr** [Anuken/Mindustry-Suggestions#33]
For the love of god! Leave me alone!!
Phantom drones are incredibly annoying following around.
1. They get in the way just planning builds.
2. They follow me to the spawn circle and die when I want to see a wave. 

Possibly could have a command center-like block to choose: return to home, rally, follow

They still seem to need to be able to follow and help build but really I use them to rebuild so I'd prefer if they could wait by a base or rally point away from the defenses so the wave is over by the time they go to rebuild. 

(On Android)

**Comment by KSean222** [comment]
Note that command centers may not exist for very long anyways, Anuken said he doesn't think they should be done that way.

**Comment by ClockeNessMnstr** [comment]
Fixed in 6
