### ISSUE TITLE
Secondary Mech

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3300]
### Describe the content or mechanics you are proposing.

A mech can give unit additional health and armor, also for weapons, but with a cost of speed. 

There must be a unit to power the mech if player want it to move.

The unit must be in the same tier (or one tier higher) with the mech if powering up
* if the unit tier is too low--- do not have enough power to power the mech
* if unit tier is too high--- the unit will not fit into the mech

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

summary:
* It could be hard to control
* hard to understand at first
* make the game harder

But:
* it can make pvp for fun than just making t5 units
* make more solutions for attack maps
* have even more fire power than t5s
* can use at eradication sectors in campaign

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Isn't this basically #157 but instead if blocks, it's units this time around?

**Comment by GuestUser25** [comment]
> Isn't this basically #157 but instead if blocks, it's units this time around?

It is different to upgrade.
It is kind of like adding a SD card into a mobile phone.
The unit is like The Internal space of the phone, and the mech is like the part where you can add additional stuff to it.

I hope this helps to understand

**Comment by itcannotbe** [comment]
Basically an upgrade suit for a mech of the same tier?

**Comment by GuestUser25** [comment]
> Basically an upgrade suit for a mech of the same tier?

Yep.

**Comment by OnyxFinger** [comment]
>   it can make pvp for fun than just making t5 units
    make more solutions for attack maps
    have even more fire power than t5s
    can use at eradication sectors in campaign

⋅ Game isn't just T5 units (as-in stop playing servers where the gameplay sucks and find something better, because there is)
⋅ it wouldn't add much to unit creation, considering that units are supposed to be upgraded in reconstructors already
It's kinda like adding two ways of turning a T4 into a T5.
