### ISSUE TITLE
Add 'number lines' in logic

### ISSUE THREAD

**Issue by NMarlon** [Anuken/Mindustry-Suggestions#3301]
### Describe what you would like changed, and why.

There is no easy way to find a long jump path with lots of jumps around them. So I want the NUMBERS IN THE LINES on the left (or right) of each process, to find the process, so when I mouse over the jump arrow, then it shows the line, then shows the line where it came from and which line the jump goes to 

### Describe the changes you want to propose. Include possible alternatives.

- Number numering from 1 in left (or rigth) of each process in processor logic
- When I put the mouse over a jump, he shows with the purple arrow the number of line what is going
- Some way (a button or a shortcut key) I can go to a line by number
- In the finish of arrow, have a number of where the jump this arrow come from

Details:
- Change any process position, DON'T change the numeric sequence (starts in 1 and finish in last process)
- When some process is changed his position, the respective number pointer of his jump is changed to
- Also if I put a new process before the jump, the jump is now a line below, then 1 line more, then update the jump arrow automatically with new line of jump
- This will not affect any in the logic programming, it is just for easier the identification for programmer in the logic.
- It is a similar thing in various editors text what have numerical sequence numbers in left of the lines.

**Comment by SwitchLikesMlog** [comment]
thats alreadly a thing in the pre-alpha V7 version (135 iirc)

**Comment by NMarlon** [comment]
Cool! Thank You!

**Comment by NMarlon** [comment]
Nice! Thanks! I thought about closing the topic, but it will be great if you have the number in the jumps too

**Comment by SwitchLikesMlog** [comment]
thats available in v7 too

**Comment by end-me-please** [comment]
that exists
