### ISSUE TITLE
Rework of "Unit Bind / Control / Radar / Locate" functions

### ISSUE THREAD

**Issue by CaptianOfTheCorporation** [Anuken/Mindustry-Suggestions#3302]
### Describe the content or mechanics you are proposing.

Дорогой разработчик! 
Использование вышеупомянутых функций процессоров в текущем виде сильно ограниченно, потому предлагаю их переработать, чтобы функционал был такой же, как и у соответствующих команд для зданий (например, "Radar"). 

То есть:
Вместо "Unit Bind @type" хотелось бы видеть "[имя переменной] = Unit Bind @type", где записываемая переменная - ссылка/указатель на подключаемого юнита, соответственно вместо "Unit Control [действие]" - "Unit [имя переменной] [действие]. Например, "Unit myUnit move x mX y mY". Также прошу дать возможность записывать ссылку/указатель на юнита в ячейку памяти, чтобы можно было считывать данные одного юнита (либо контролировать его) с при помощи разных процессоров. 

(Необязательно) 
У юнитов в игре много разных пушек, но, к сожалению, при использовании команды юнита shoot/shootp нет возможности выбрать, какой конкретно стрелять, есть только вариант по-умолчанию - огонь из всех орудий! Тоже важный вариант, но выбор, порой, необходим. Функционал выбора можно реализовать просто по номерам пушек на юните, при удержании на кнопке доступного номера будет высвечиваться соответствующая ему информация об орудии, как та, что отображена в базе данных ядра. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Визуальный редактор кода крайне неудобен для мобильных устройств, потому удобно разбивать большую программу на несколько небольших, для каждая из которых помещается в отдельный процессор. 

Кроме того, это позволит оптимизировать программу и выполнять некоторые инструкции параллельно. 

Например, один процессор считывает все данные о состоянии юнита, другой на основании того, что записано в ячейке памяти, строит графики на дисплее, третий отвечает за передвижение, четвёртый - за стрельбу, пятый рисует на другом дисплее подобие радара, а шестой решает, отправлять ли квад на базу, чтобы потом выгрузить у стен противника полностью заправленный ториевый реактор:) 

То есть, это сильно облегчит написание программ для управления юнитами <s>и ускорит появление Скайнета.</s>

(О необязательном) 

Управление отдельными орудиями можно будет также реализовать отдельными процессорами, что, в свою очередь, позволит выборочно либо распределять огневую мощь по толпе юнитов с малым количеством хп (а не стрелять из двух пушек Т5 кинжала в одного ползуна), либо концентрировать их на более крепком противнике. 

P. S. А ещё ИИ воздушных юнитов в 7.0 отупел: они просто летят к вражескому ядро через всю карту, игнорируя всё вокруг. Квады не сбрасывают бомбы на вражеские постройки прямо под ними, как это было в 6.0. Только на ядро. Скажи, пожалуйста, это баг или так задуманно, чтобы игроки изучали процессоры, а не по-старинке отправляли толпу Т5 нажатием кнопки "в атаку"?  :)  Если второе, то хитрый план сработал ;) 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
> Вместо "Unit Bind @type" хотелось бы видеть "[имя переменной] = Unit Bind @type", где записываемая переменная - ссылка/указатель на подключаемого юнита, <...>

This can already be done:
```py
ubind @flarogus
set instance @unit
```

IMO:

> Также прошу дать возможность записывать ссылку/указатель на юнита в ячейку памяти, <...>

Memory cells are intended to be limited: they can only store numbers, not objects. It would make no sense if a cell will be able to store info about a unit but not about a string / block / any other object

> Визуальный редактор кода крайне неудобен для мобильных устройств, <...>

The in-game code editor is useless for anything larger than a "hello world", but you can use an external code editor. In addiction to usability, you will also get access to formatting, comments and jump labels.

About split control... You can flag a unit with a coordinate-based number, share this number with other processors and make them bind to the unit with that flag

**Comment by CaptianOfTheCorporation** [comment]
Спасибо за ответ! Помогли все ответы, кроме крайнего: два процессора не могут одновременно командовать юнитом. 

Вернее, они попытаются, но результат будет нулевой. Дело в том, что юнит не может выполнять две команды одновременно от двух  разных процессоров, пусть даже эти команды не противоречат друг другу. Ниже несколько видео. Во всех случаях один процессор я использовал для передвижения, другой - для стрельбы. 

В первом видео хорошо видно причину: процессоры отбирают друг у друга управление над вспышкой, не желая управлять ей одновременно. 
Из за этого команда стрельбы прерывается командой висения в одной точке. 

https://user-images.githubusercontent.com/88437476/148928094-01f212b5-cb23-40af-9753-1e6d779f95b4.mp4

**Comment by CaptianOfTheCorporation** [comment]
Во втором видео в лучшем случае происходит два выстрела между перемещениями вместо стрельбы и перемещения одновременно. В этот раз вместо статических данных для стрельбы я использовал вычисляемые: прибавлял к x и y координатам юнита треть радиуса его атаки, shoot всегда было true. 

https://user-images.githubusercontent.com/88437476/148928910-957c947f-4fce-475e-a7be-f611567ed7f9.mp4

**Comment by CaptianOfTheCorporation** [comment]
Таким образом, несмотря на решение первой части проблемы (ещё раз спасибо!), управление юнитом несколькими процессорами по-прежнему не является возможным. Очень прошу исправить это!

**Comment by CaptianOfTheCorporation** [comment]
На всякий случай, вот схема из второго видео:

bXNjaAF4nAHnARj+AAMAAgMABG5hbWUABFRlc3QAC2Rlc2NyaXB0aW9uAAAABmxhYmVscwACW10CAA9taWNyby1wcm9jZXNzb3IAC21lbW9yeS1jZWxsAAAABAAAAAABDgAAAIR4nEWOMQ6DMAxFw9Alp/AR8NaRpQdxialAJmmTuIXD9K61IlDlxU//P9mdc+6r9zkGGCahzL5wLCmDsca5whCYgl90fUIPMdXbS0ks7b2OKdacBMx7ACJaoY3PpsAGI4vgifuB+PfW9GarXU+tHUEg+dBeLJhICnt7sHOXJtvifvXoM6UAAAABAAAOAAAApXicZY9BEsIgDEXpwg2nyBHKeIFuvEL3saGdOgg1gJa7uxDUuHGX//P+5KdTSj3zefUEw+yQrY7Wx8Aww5D9mt7uoi/5ukEPPqTTLaOrW2OMoCQoWaQ/lKAXkAVk9Mvv0i7uLk4Rp+iwAa134LGGj00hEexjDfEosnxlnoJPHBwk5MWmhtVV4mxrn/5TzAC6B5ZYEzO6aHX9v1OHyTpn2vgCuMRWdwABAAEAAQAAAAACAAEOAAAAR3icY2RgYIgqTi1RqFAwM+ACMSoVLAy4yosyS1KBYsmpOTmGCjB+JYKfmFmiYMoF0WhsgEUDRAHQdEYGVrDg//8MDACpTh8QALO+zLY=

**Comment by CaptianOfTheCorporation** [comment]
Кстати, быть может, это и есть причина странного поведения ИИ по-умолчанию? Юниты не проверяют, есть ли рядом противник, потому что, во-первых, команды блокируют друг друга, а, во-вторых, цикл блокирует команды непрерывно! А это значит, что до тех пор, пока Quad / любой другой атакующий воздушный юнит летит к вражескому ядру, он не может приступить к выполнению других команд.
