### ISSUE TITLE
Send various orders to groups of units (move to, attack location, etc...) 

### ISSUE THREAD

**Issue by quantumsheep** [Anuken/Mindustry-Suggestions#3303]
### Describe the content or mechanics you are proposing.

It would be very interesting to be able to control units like you do in RTS games. Sending different fleets with different orders toward different location would look like real wars.

This feature could also be an entry point to developing the enemy's strategy AI in the future.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It could greatly improve the strategical side of the game. Right now we only have the option to let units attack but we can't target specific areas. If we want to target an area we need to take control of a fleet by ourselves.

While I really like attacking the enemy's base by manually controlling the units, I would also love to send big fleets of units toward specific locations or even just move fleets for orchestrated attacks.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
you can command the units tho, if you smart you can also make a logic

**Comment by quantumsheep** [comment]
Commanding the units is limited to the player's actions, we can't say "attack this particular location" or "move here" to our units without controlling them manually.

Logic is very cool for complex behaviors and repeating tasks but my proposal is to add very simple commands, giving more control to already existing orders like the "Attack" mode from the Command Center which currently mindlessly attacks the enemy spawn point or core.

**Comment by OnyxFinger** [comment]
Personnally, I thought that it would suck on mobile because of the UI, but the more I think about it, I realize that this isn't true.
However, I believe that Anuke has probably thought about this already, and has a reason not to add it.

**Comment by itcannotbe** [comment]
> Personnally, I thought that it would suck on mobile because of the UI, but the more I think about it, I realize that this isn't true. However, I believe that Anuke has probably thought about this already, and has a reason not to add it.

Because logic was made for this.

**Comment by SwitchLikesMlog** [comment]
yeah but not everyone know how to do logic, espescially unit logic

**Comment by OnyxFinger** [comment]
>  Because logic was made for this.

Yes but : 

>  Logic should be an optional part of the game

https://discord.com/channels/391020510269669376/513178557653188609/915261988609851422

**Comment by itcannotbe** [comment]
> > Because logic was made for this.
> 
> Yes but :
> 
> > Logic should be an optional part of the game
> 
> https://discord.com/channels/391020510269669376/513178557653188609/915261988609851422

And you somehow forgot that the game is still playable without this, so it is still optional though.

**Comment by OnyxFinger** [comment]
> And you somehow forgot that the game is still playable without this, so it is still optional though.

Ok how about this : Logic doesn't do that. In fact, it's not as good. And it may sound like a argument against this feature, which it is. But the reason why I like it, is that logic is a broken system that will definitely not be un-awful-ized
