### ISSUE TITLE
Nearest Unit/Building Radar and Unit/Building Locate Logic

### ISSUE THREAD

**Issue by PizzaBurgz** [Anuken/Mindustry-Suggestions#3304]
### Describe the content or mechanics you are proposing.

When using Radar and Locate Logic, make an input variable where it defines whether to find the nearest, 2nd nearest, 3rd nearest, and so on and so on unit/building.

For example (There are 3 cores the unit must check, but the unit must not move.):
When inputting "1", the unit would look for the nearest core.
When inputting "3", the unit would look for the farthest core.
When inputting "2", the unit would look for the 2nd nearest core.
When inputting "4", the unit would look for the nearest core, this would loop infinitely.
When inputting "10", the unit would look for the 2nd nearest core.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will be kind of useless as I do not see many useful uses for it. But it can add a few fun things to logic and not limit Radar/Locate logic to only search for the nearest or farthest unit/building.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
stuff like that might actually a gives more freedom/capabilites in unit logic, i can see a few uses for it

**Comment by oinkymoo** [comment]
3 should find the third closest core in a general case, while -1 would find the farthest

**Comment by Ymabert** [comment]
@oinkymoo 👍👍
