### ISSUE TITLE
Mindustry 7.0 itch.io not working

### ISSUE THREAD

**Issue by qwertyuiop762594** [Anuken/Mindustry-Suggestions#3306]
### Describe what you would like changed, and why.

Mindustry 7.0  (downloaded from itch.io) on linux does not launch at all. 
OS: Kubuntu (whatever version of kubuntu comes from a KDE crosh)
hardware: HP Chromebook (2 GB RAM, 32 GB storage)
Software: Mindustry 7.0 from itch.io

### Describe the changes you want to propose. Include possible alternatives.

i do not know why it does not launch.

**Comment by MrDuck557** [comment]
close this and
https://github.com/Anuken/Mindustry/issues/new?template=bug_report.md
