### ISSUE TITLE
Water and Criofluid

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3307]
### Describe the content or mechanics you are proposing.

why can we only use Criofluid to cool?  In my opinion, water can also have the same utility, except that, compared to the Criofluid, it heats up faster, therefore it cools less and a larger quantity is needed to be able to cool as the Criofluid does.  Therefore, I would like the water to be used as a cooler (just to be clear, to cool something with water, much more quantity must be needed than using the Criofluid, also because otherwise it would become unused).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would change that many times, not having Titanium available, I cannot generate T4 / T5 or manufacture energy, since the little material I have serves me mainly for defense (not that it happens very often to play a map with limited resources, however not always having to create a factory specifically for the Criofluid would make everything more comfortable, it would be enough for me to place a few more pumps and pipes, but at least I would not waste necessary resources for anything else).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. Launch pads exist.
2. If the map actually was built with resource scarcity in mind and you don't know how to deal with it. Then don't play on that map.

**Comment by SwitchLikesMlog** [comment]
Cryofluid is much colder than Water, so of course you would need it. 
> not having Titanium available
Launch Pads. 
> much more quantity must be needed than using the Criofluid
No.

**Comment by Ymabert** [comment]
there is always a way to deal with any map, the point is that sometimes it would be convenient to have that something the most without having to lose other things, do you understand?

**Comment by myutin** [comment]
The T4 and T5 reconstructors require phase fabric and surge alloy to build. If you're making those on the map, it's assumed you have plenty of titanium (laser drills for thorium require titanium; you won't get far without titanium conveyors). If you have these advanced resources on a map through other means (launching a full core, or importing with launch pads), you should be able to have titanium through those means as well. Lastly, if you're limited by the quantity of titanium in your core / on a map, there's usually some scrap you can use to make more.

A key aspect of balance is that T4/T5 units are very expensive. At that stage of the game, it is trivial to produce huge amounts of water. Cryofluid instead keeps the resource cost high.

In PvP, both players have the same resources available to them. If you're struggling to produce cryofluid, your opponent will be as well. If you don't know how to win on a map without T4/T5 units, learn some alternative strategies.

**Comment by Ymabert** [comment]
@end-me-please ah ok thx, for me Is not a real problem.

**Comment by itcannotbe** [comment]
~but I pointed out resource scarcity also~

And yes having alternatives will always making the other liquid as a "use this incase x isn't available", as evidenced by the time we used to be able to use cryo in thorium reactors.

**Comment by Ymabert** [comment]
Yes 🙃

**Comment by SwitchLikesMlog** [comment]
close the issue?

**Comment by Ymabert** [comment]
Idk...

**Comment by RFAC-Productions** [comment]
Perhaps close it.

**Comment by Ymabert** [comment]
@RFAC-Productions Yes...

**Comment by SwitchLikesMlog** [comment]
bruh

**Comment by Bottinator22** [comment]
No

**Comment by Bottinator22** [comment]
Cryofluid is far cooler than water

This is also going to make building reactors too easy
