### ISSUE TITLE
New turret idea: Repulse

### ISSUE THREAD

**Issue by Salty-Potato133** [Anuken/Mindustry-Suggestions#3308]
### Describe the content or mechanics you are proposing.

Suggestion: A new late-game turret: Repulse, a unique support anti-air turret

unique anti-air turret for making advancing with air units on a base a little bit harder. It could use phases fabric and power to shoot large, long-range projectiles (like similar range to a foreshadow). When that projectile hits an air unit, it could (to a single unit) apply a large knockback, deal a relatively small damage, and stun (devs decide what this does and how long) to the unit (devs decide the fire rate, it should have significantly slower fire rate then the stun duration however). This could be effective on slow air units because they may struggle to advance towards the base with the knockback and stun. The projectiles and hit effect should have very bright effects because the projectile is infused with energy to stun the enemy air units.

To counter this, you could use ground or naval units (It cannot target ground), faster air units, Fleeting (It has low fire rate, and it only targets single units so coordinated attacks would work well), Running the turrets out of ammo (phase is slow to make) or power (power consumption should be higher but up to devs) with continued attacks. Alongside this the turret should cost a lot of materials to build, so it is a late game turret (size and looks up to devs).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

My idea could fill a unique place as a support anti-air turret due to the stun and knockback. Due to the long range, stun, and knockback this turret could be strong at helping keep air units from dealing damage your base. This is different than the tsunami or wave because the knockback on this turret would be effective on the largest air units (T5) and the stun (whatever it looks like) could help you defend your base from high-tier units. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I think with the stats you have provided, most air units can flank the bullets your proposed turret shoots. Also the foreshadow is an any target turret (well v.s. building it has reduced damage for balancing reasons), this does, which reduces this proposals usefulness.

**Comment by Salty-Potato133** [comment]
The stats are up to devs and yes using a different non-direct course can allow you to dodge, but if you get close enough flanking won't work, and I think this is a good idea for countering constant pushes with air units and bombers. It also gives a unique new high tier weapon for use against air raids.

**Comment by RealYeet** [comment]
This is just a reverse parallax. All (turrets that use non energy ammo) turrets provide a small amount of knock back making it harder to impossible for air units to get through that area. Also, this already exists in the game in the form of tsunami and wave. Close the suggestion, you clearly did not care about the second box.

**Comment by Salty-Potato133** [comment]
No, I explained how this is different than the tsunami or wave. This is different in that people how have actually read it would know it stuns them and applies a large knockback effective against high tier units (T5) which no other turret does. And yes, it is sort of like a "reverse parallax", but this is different. Unlike the tsunami it has high range, stun, and very large knockback with the stun make it actually effective on high tier unit unlike the tsunami.
