### ISSUE TITLE
Server side changes seen on the client side

### ISSUE THREAD

**Issue by FitmoF** [Anuken/Mindustry-Suggestions#3310]
### Describe the content or mechanics you are proposing.

Allow things such as unit changes(things such as extended bullet lifetime and range on weapons or boosting being disabled),block changes etc to be seen client side.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will allow servers to have much more things without the players having to download mods or anything, just join and play, makes it easier both for players and server owners.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ilya246** [comment]
there's not really any proper way to implement this, so almost certainly not happening
