### ISSUE TITLE
Español: Crear mods desde dentro del juego inglés:Create mods from within the game

### ISSUE THREAD

**Issue by Maxter1282** [Anuken/Mindustry-Suggestions#3311]
### Describe the content or mechanics you are proposing.

Inglés:I would love that from the app you can create mods with an easy to use interface so that anyone can publish or play their mods and the game lacks a little more content but the game seems great 100 🌟

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

🤚

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
unfortunately, making mods is mostly just coding. you're much better off just using an external IDE for that

**Comment by Mnemotechnician** [comment]
they're probably talking about json mods. that's actually possible but useless.

**Comment by itcannotbe** [comment]
I smell #1645
