### ISSUE TITLE
Consistency in Color-Schemes for Production Structures.

### ISSUE THREAD

**Issue by myutin** [Anuken/Mindustry-Suggestions#3312]
### Describe what you would like changed, and why.

Oil Extractors and Plastanium Compressors are hard to tell apart in the block selection menu, since they're scaled to the same size, and you can't zoom in to inspect the textures in detail. This is especially a problem for novice players, who haven't yet memorized the order of the menu. Spore Presses and Cultivators have the same issue, although to a lesser extent, since they're in different sections of the block selection menu.

I really like the design aspect of mindustry wherein production structures have the same colorscheme as the resource they produce. Since the resources' colorschemes are easy to differentiate at-a-glance, this make the structures easy to differentiate too. I guess Pyratite and Copper look kinda similar, but that's a separate issue.

Here's a list of structures that follow this principle:
- phase weaver
- pyratite mixer
- blast mixer
- plastanium compressor
- melter
- water extractor
- cultivator

Here's a list of structures that don't follow this principle:
- oil extractor, spore press
- coal centrifuge
- silicon smelter, silicon crucible
- graphite press, multi-press
- kiln
- pulverizer
- cryofluid mixer

The Silicon- / Graphite-producing structures get a pass, because if they adhered to this principle, they'd be too gray.

Kilns are ok because they're the only beige structure. Pulverizers are ok because they're the only 1x1 production structure (although it can be hard to tell them apart from conveyor variants). Cryofluid mixers are ok because it's not too hard to tell them apart from water extractors. But it'd be nice if all of these followed the same design principle.

But why are Oil- / Coal-producing structures green / purple? Oil and Coal are black.

The alloy smelter was previously orange, in v6. The devs / community didn't like this, so in v7 they made it yellow, to match the colorscheme of surge alloy. There is precedent for re-coloring a structure.

### Describe the changes you want to propose. Include possible alternatives.

Oil Extractors, Spore Presses, and Coal Centrifuges should have a black colorscheme. To give veteran players an easier time adjusting, some green / pruple can still be included in the texture. Of course, this should be put up to a community vote, same as any change to existing content.

Optionally, Kilns could have a white colorscheme, Cryofluid Mixers could have a sky-blue colorscheme, and Pulverizers could have a sandy colorscheme.

Here's some mock-ups of what I think these could look like:
![preview-oil-extractor](https://user-images.githubusercontent.com/60725262/149391083-22e5a6d1-37f8-4957-b4fa-8c40ce8979b0.png) ![preview-spore-press](https://user-images.githubusercontent.com/60725262/149399465-ce01a375-a873-4d0e-a034-ceaab99d0c62.png) ![preview-coal-centrifuge](https://user-images.githubusercontent.com/60725262/149399299-9c7f3f9d-d38a-4a1b-a80e-8ed627ad1246.png) ![preview-kiln](https://user-images.githubusercontent.com/60725262/149391319-c0294a23-b4b7-47ca-8a88-07d0abaf247a.png) ![preview-cryofluid-mixer](https://user-images.githubusercontent.com/60725262/149391323-e4611780-7cbf-4827-a5b5-debe8ed6fb2d.png) ![preview-pulverizer](https://user-images.githubusercontent.com/60725262/149391108-c8e73787-7211-4fdb-a72d-14c4255c0856.png)
Contrast these with the current textures:
![old-oil-extractor](https://user-images.githubusercontent.com/60725262/149392486-78039901-7a54-4cb8-9b3a-ab52787e16a7.png) ![old-spore-press](https://user-images.githubusercontent.com/60725262/149392495-341feed6-071c-4c56-9205-0f618587f4de.png) ![old-coal-centrifuge](https://user-images.githubusercontent.com/60725262/149395806-3b3b124e-458f-4d4d-9c1b-957e167a9ec5.png) ![old-kiln](https://user-images.githubusercontent.com/60725262/149392518-abc8d12e-9cf2-4782-b039-9c578e69fbf5.png) ![old-cryofluid-mixer](https://user-images.githubusercontent.com/60725262/149392537-21935702-d68e-4554-82f0-29edc4f68b42.png) ![old-pulverizer](https://user-images.githubusercontent.com/60725262/149392553-20aea68f-4bd9-45e4-a27e-99c3cfb477bb.png)
And here's just the layers i've changed:
![new-oil-extractor](https://user-images.githubusercontent.com/60725262/149391582-6ad05ddc-1675-4bd7-b86e-7b1b5a432df1.png) ![new-spore-press](https://user-images.githubusercontent.com/60725262/149391614-de22cb24-bbb8-4902-abf0-6ec215699489.png) ![new-coal-centrifuge](https://user-images.githubusercontent.com/60725262/149399319-14599d12-b962-4a82-be2a-fdbf9fd843fe.png) ![new-kiln](https://user-images.githubusercontent.com/60725262/149391647-f67e6bb1-36f8-4148-a582-d82cd7f17eec.png) ![new-cryofluid-mixer-bottom](https://user-images.githubusercontent.com/60725262/149391657-78c1c4dc-6b27-4f3e-8612-3283a70c9d21.png) ![new-pulverizer-rotator](https://user-images.githubusercontent.com/60725262/149391713-7d14fa4f-3af5-4b38-b09f-214edc8f645a.png)
Don't think I'm proposing these exact textures. I'm definitely not the best artist in the community; I just think that pictures help communicate what I'm describing.

**Comment by myutin** [comment]
here's a nicer-looking kiln
![alternate-kiln](https://user-images.githubusercontent.com/60725262/149408078-6abffbcb-af2e-449d-8d90-9402e158a037.png)

**Comment by oinkymoo** [comment]
did you mean coal centrifuge? oilex and plastanium compressor, like spore press and cultivator, are in different tabs, but coal centrifuge and plastanium compressor are both factories. 

also, the green is used by all the oil-related buildings. oilex outputs oil and centrifuge and compressor both have oil as an input.

**Comment by myutin** [comment]
I included coal centrifuge in my list. Oilex, cultivator, and water extractor are in a different tab, but they still produce one specific resource, so the consistent color-schemes still apply.

spore press is an oil-related building, but it does not use green. Therefore, green is not a color associated with oil.

**Comment by myutin** [comment]
here's a nicer-looking coal centrifuge
![alternate-coal-centrifuge](https://user-images.githubusercontent.com/60725262/149409222-d45dc69d-9522-4cb8-bc5b-1a148bc36b1a.png)

**Comment by OnyxFinger** [comment]
Eh.. I think that the difference between every block is blatant, even for similar ones like centrifuge and compressor.

**Comment by myutin** [comment]
That's subjective. I can't tell you how many times i've built a coal centrifuge when I meant to build a plast compressor, or vice verse. (and don't tell me to "git gud")

**Comment by RealYeet** [comment]
I fully support this, while this suggestion can be mitigated by “getting gud”, there is some merit to having a noticeable visual difference. Especially for the newer/younger people in the community.

**Comment by itcannotbe** [comment]
> That's subjective. I can't tell you how many times i've built a coal centrifuge when I meant to build a plast compressor, or vice verse. (and don't tell me to "git gud")

You do realize that people who would play campaign won't have this problem, since blocks are gradually introduced into gameplay via the research system.

**Comment by myutin** [comment]
Ok, maybe it really is an issue only I've encountered. (I was playing the campaign though)

**Comment by OnyxFinger** [comment]
What I meant is that barely anyone at all has this problem
and by barely I mean  **b a r e l y**

**Comment by Sector171** [comment]
This is very obvious problem in this game, or at least for me as a mobile user.
definitely the block's icons need to be more distinct.
Not to mention to how annoying to see if this was a vault or a core, these also need to be more clear.
There are only few factories distinct enough to recognize them from the first look, like phase weaver.
If you are using a big screen with high resolution, majority of people don't.
Practically this issue is real, the icons design lacks creativity and need to be re-designed.

**Comment by itcannotbe** [comment]
> spore press is an oil-related building, but it does not use green. Therefore, green is not a color associated with oil.

Spore press is a spore related building and violet is an associated with spores.

**Comment by oinkymoo** [comment]
> I included coal centrifuge in my list. Oilex, cultivator, and water extractor are in a different tab, but they still produce one specific resource, so the consistent color-schemes still apply.
> 
> spore press is an oil-related building, but it does not use green. Therefore, green is not a color associated with oil.

i meant at the start of the post. 

> Oil Extractors and Plastanium Compressors are hard to tell apart in the block selection menu
