### ISSUE TITLE
togglable "approach" option for command center

### ISSUE THREAD

**Issue by Nils101** [Anuken/Mindustry-Suggestions#3313]
### Describe the content or mechanics you are proposing.

A togglable "approach" setting for the command center, where units will stop moving when theres an enemy in their range, so they will always stay at max range.

Right now, this is (only) doable with logic. This brings problems like with other things only doable with logic. It brings a logic reliance with it, where if you don't have certain logic you're at a severe disadvantage.
It's especially bad with fortress, because fortress is only good when you keep it at max range.

(Overshoot had this problem too, where you could drastically increase the range without having to manually control a turret, and it got (rightfully) removed so why not add this and make it easier for the players)

One more thing: should it ignore walls? I would say yes because it's generally better. Maybe that would be too strong? Not sure.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

-Removes the logic reliance aspect
-Logic free games have an easier time with fortress
-I'm imagening this opens a door for a few skillful interactions, especially in games with logic ban

_Very curious about the community reactions on this one_

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by myutin** [comment]
The default pathing that units use when controlled by a command center is supposed to be the same as the pathing that enemies use in the campaign.
- this lets new players learn how the pathing works
- the pathing algorithm is already rather complicated, so adding to it would be difficult.
See #3228.

**Comment by OnyxFinger** [comment]
>  this lets new players learn how the pathing works

![No](https://user-images.githubusercontent.com/68511236/149410088-f2518ac1-e103-40db-a2ed-0aa82725b7b8.png)

Because they already can, and easily.
However I don't know enough about the second point to say anything. If coding this is too hard, Anuke won't add it.
