### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Stepan54823189432165431** [Anuken/Mindustry-Suggestions#3315]
### Describe the content or mechanics you are proposing.

Please add intelligence to bots so that they not only build schemes, but also develop themselves, attack, etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This is to diversify the game for those who have some problems with servers
### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
octogon
hexagon
pentagon
englishorbegon

**Comment by itcannotbe** [comment]
Ah yes. #3285.

**Comment by itcannotbe** [comment]
Translated:

> ### Describe the content or mechanics you are proposing.
>
> Please add intelligence to bots so that they not only build schemes, but also develop themselves, attack, etc.
>
> ### Describe how you think this content will improve the game.  If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
>
> This is to diversify the game for those who have some problems with servers
