### ISSUE TITLE
Block destroying realism

### ISSUE THREAD

**Issue by Arcanilius** [Anuken/Mindustry-Suggestions#3316]
### Describe what you would like changed, and why.

It would be more realistic and will make more sense if a damaged building gives less resources back when destroyed. If a building with 50 health is destroyed it gives back the sale amount of resourses as a building with 100 health, this isn't very realistic.

### Describe the changes you want to propose. Include possible alternatives.

For example 25% of the building's health is gone, for destroying the building you get 25% less resourses back.

**Comment by TheRealIvyX** [comment]
realistic game machanics ≠ good/fun game mechanics

this game has conveyors and drills that move and mine perpetually without using any power, liquids that cannot ever evaporate or freeze, titanium coated with oil that somehow stops lasers, thorium reactors that cs explode,

**Comment by TheRealIvyX** [comment]
realistic game mechanics ≠ good/fun game mechanics

making the game more "realistic" isnt an excuse for wanting your suggestions to be added. mindustry has conveyors and drills that move and mine perpetually without using any power, liquids that cannot ever evaporate or freeze, titanium coated with oil that somehow stops lasers, thorium reactors that can explode, and many, **MANY** other unrealistic mechanics. do you also want all of that to be changed to make the game more "realistic"

sorry if this sounded rude btw, this is just my opinion on suggestions that would make the game more "realistic"

**Comment by SwitchLikesMlog** [comment]
who cares about the game being realistic, as long as its fun

please close the issue

**Comment by Arcanilius** [comment]
Sure
