### ISSUE TITLE
Under ground Unit

### ISSUE THREAD

**Issue by Nitan337** [Anuken/Mindustry-Suggestions#3317]
### Describe the content or mechanics you are proposing.

New Unit: Under ground Unit (no need under ground layer) The Unit Will Attack By Digging Under ground And Go To Enemy Base To Attack, It Will Need A Special Device To Track Under ground Unit

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It Will Bring A New Experience About The Game Play Most Is PvP And Attack

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
new units suggestion: no
thats literally the last thing we need

**Comment by oinkymoo** [comment]
how will new units change the fact that most of the gameplay being pvp and attacK?

**Comment by SwitchLikesMlog** [comment]
> how will new units change the fact that most of the gameplay being pvp and attacK?

hint: they wont
