### ISSUE TITLE
Add Life For Next Plannet

### ISSUE THREAD

**Issue by Nitan337** [Anuken/Mindustry-Suggestions#3318]
### Describe the content or mechanics you are proposing.

Imagine A Plannet Have Life
Like Monster, Tree And Other Living Thing

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Not Like Serpulo Still Have Water In Liquid Form But Serpulo Don't Have Life (except spore and frozen tree) Most Place In Serpulo Are Been Frozen , The Next Plannet Maybe In Habitable Zone And It Will Be Possible To Have Complex Life, It Will Bring A New Experience For Player Can See Life On A Plannet, Not Always Have To See Complicated Machines.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
what new experience will lifeforms give, new enemy-only units, that's not even remotely interesting

**Comment by IIINSTINCT** [comment]
_Ah yes definitely add lifeforms on a purely robot gam3_

**Comment by SwitchLikesMlog** [comment]
do i have to remind you that the next planet is hell-ish hot?

**Comment by Eldeston** [comment]
> _Ah yes definitely adding more lifeforms on a purely based robot game is a good idea_

Honestly having only robots fighting each other in the game feels...dead. This could be a good idea honestly having living beings either as enemies or entities that roam the planet that can be used to farm potential resources. This might as well connect with the game's lore with the current existing lifeform: the spores.
