### ISSUE TITLE
Giant Battery/Quantum Battery

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#332]
**Describe the content or mechanics you are proposing.**
I am asking for a 5×5 battery capable of holding half a million power, as batteries right now are very useless and in a power outtage they hold no efficency at keeping power. So i think it would be smart to add a new superior battery to fill this desire of battery insurance.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The battery would be made with 175 lead, 100 copper, 125 silicon, 75 surge alloy, 150 plastanium and 135 titanium. 
The battery would half a million power as said and would blow up in a impact reactor explosion, making a type-of Blackhole explosion on destruction, and can be contained by plastanium walls. The battery would also have 3000 health.
This battery cant be that op as the thing costs surge alloy and is only 3.6× better then the big battery storage wise.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Batteries are very much unused except for using with battery diodes and pulse energy users (arcs, lancers, meltdowns)

They are actually unused due to how power is consumed and/or produced.
There are few use cases for them and frankly speaking they are use as gap fillers between builds.
