### ISSUE TITLE
a unique powerful unit

### ISSUE THREAD

**Issue by goodsofa** [Anuken/Mindustry-Suggestions#3320]
### Describe the content or mechanics you are proposing.

i think there should be a tier post everything else(whatever will be the last tier) that you would be very powerful but would be extremely expensive and you can only have one of per map/sector 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the current final 5th tier is very cool but they all stop feeling as cool and as unique after you get more than two or three of them and apart from being very badass and cool it would fix this issue imo

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
*inhales*

WE DONT NEED MORE UNITS

**Comment by SwitchLikesMlog** [comment]
might as well close the issue

**Comment by NrkSed** [comment]
iT wIlL hAvE 80 bIlLiOn heAlTh aNd dO 5k dAmAgE AnD hAVE 999 RPM

**Comment by RFAC-Productions** [comment]
Close it down boys.

**Comment by Ander292** [comment]
Why?

**Comment by williams104** [comment]
> iT wIlL hAvE 80 bIlLiOn heAlTh aNd dO 5k dAmAgE AnD hAVE 999 RPM

999 rpm is slow.
Kriss vector shoots faster.
It should have 2500 rpm.
Much more reasonable

**Comment by rawsewage38** [comment]
T6 should just be every T5 Unit Combined into one monstrosity. Factory takes up 10x10 tiles of space, and directs free T5s into it. I doubt this will be added into vanilla though, T5 Units are designed specifically to be the best of the bunch, the ultimatium.
