### ISSUE TITLE
Using diffrent keys for different unit weapons

### ISSUE THREAD

**Issue by Suwodowo9651** [Anuken/Mindustry-Suggestions#3321]
### Describe the content or mechanics you are proposing.

For example if you wanted to fire the toxopids cluster rocket instead of the laser you could right click.  Having a button to separating the weapons into left click or right click attack function would be good for PvP.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The ability to control each weapon groups would be nice to have as filling the screen with bullets is annoying 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ymabert** [comment]
the only problem is that the direction of all weapons will always be one, even if some turrets are only slower in turning than others (I'm talking about the turrets that the units have).

**Comment by Ander292** [comment]
I want this, just don't touch right click, you deconstruct there
