### ISSUE TITLE
Menù Blocks

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3323]
### Describe the content or mechanics you are proposing.

a new screen with all the blocks, but divided as they are now and to get as soon as possible to some blocks located in sections far from the one you are at, simply click on the icon that directs us to that section.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

so I ask for a single page with all the blocks in which the blocks are divided by the type (so how it is now) and if I need to quickly access a specific type, I click on its symbol (so in addition I would like a single page, where there is everything I need to build).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-red-soul** [comment]
yet again here you post a suggestion for something already implemented in the game.

**Comment by oinkymoo** [comment]
do you want to be able to scroll between sections without having to manually select the new section? i guess you could do it even if it would be slower

**Comment by Ymabert** [comment]
@the-red-soul ??? Wt

**Comment by Ymabert** [comment]
however there is not yet a unique "block menu to select" in the game, it only exists when you go to see all the blocks, but that is the block tree, I cannot select and build from there, I have suggested something that can come in handy, but it's just not essential although I'd like to have it as a setting to put on or take off.

**Comment by oinkymoo** [comment]
Ymabert how is this different from the selection panel that already exists in the bottom right

**Comment by Ymabert** [comment]
@oinkymoo yes, in fact, if you know how to read I have recommended something else ... if you can read.
