### ISSUE TITLE
more one-off blocks :)

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#3324]
### Describe the content or mechanics you are proposing.

More one off blocks, similar to the interplanetary accelerator, that can only be placed once per world

suggestions:
a sector resetter
a cross-sector unit launcher
superweapons

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that having some special blocks with higher costs would give the game some more mid game milestones

(it also means more opportunities for lore drops :D)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
superweapons - no, a same suggestion got rejected before
a cross-sector unit launcher - also shit
a sector resetter - go to setting game data

**Comment by SwitchLikesMlog** [comment]
a sector resetter is not that bad imo

**Comment by Ander292** [comment]
Anuke said importing units will work
