### ISSUE TITLE
Campain-like planet for PvP

### ISSUE THREAD

**Issue by FireDefender** [Anuken/Mindustry-Suggestions#3325]
### Describe the content or mechanics you are proposing.

A planet like the campain map but for pvp. With the enemy bases you have to face being your friends bases. All the players start on a simple map like ground zero, and have to try and expand out from there, with research being optional. Eventually the players will find each other as an enemy base tile, with the tile having the respective team color. Defeating your opponent would be done by creating units and sending them over to the other base allowing players to send out waves of enemies to the other base. If the player is getting attacked by someone else they should get a notification of who is attacking them and where so they can react properly should they decide to do so. A player may send themselves with a wave to the other base without items (to prevent core rushing using blast compound for example, or a modded explosive). The player can scout out the other base to see what units would be useful to build in order to defeat it. The moment you defeat an enemy base, all the blocks still standing become yours so that you can quickly set up defenses for any possible retaliation from the other player. 

If a base has been taken over, that base should have a raid cooldown, meaning that the newly taken over base cannot be attacked and cannot attack other bases for a set amount of time, decided upon creation of the planet. 

A team is considered taken out when the last core of said team has been destroyed. The team that is the last one standing wins.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this will improve the PvP aspect of the game, and give options for fun community (or even official) servers where 4 teams face off against each other in an attempt for total planetary domination. This will be good for long-duration PvP content for anyone that likes to do such a thing. 

A feature like this would work best on community or official servers, or with a couple friends to see who really is the best at the game. This will open up oppertunities for new strategies as well, needing players to find new methods of defeating their enemy's who will be stronger than usual, having an entire map at their proposal and resources from other sectors.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Sector171** [comment]
See my suggestion here
#2066
It is different but the core idea is the same.

**Comment by Ander292** [comment]
To do this you need to host whole planet first, and Anuke said he wont be doing it so...

**Comment by rawsewage38** [comment]
This is an awesome idea. However, for this to work, there would have to be a considerbale amount of lag prevention introduced. Mechanics to max out the amount of captured sectors, and only letting the sevrer run sectors that are loaded by players. Also there would most likely be alot of bugs to iron out, considering there has never been mutliple maps loaded at once in Mindustry. Perhaps a server cap of 4, to make sure only 4 players can load a sector at one time?
