### ISSUE TITLE
More auto-gen options in the "generation" tab in map editor

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry-Suggestions#3326]
### Describe the content or mechanics you are proposing.

Have more "blocks" to help generate more complex proc genned maps [e.g. **randomize waves** or **create random map walls** or **make rivers for naval pathing** or **generate enemy base**]

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There are already some very unique auto-genned maps in the maps channel in discord [check out Novi V1, its seriously cool and it's what inspired me to type this], and adding more blocks for auto genning can create a whole new line of maps, "proc genned maps" they will never get boring and each one is unique depending on the choice of auto-gen blocks used

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ander292** [comment]
Yes, this is good
