### ISSUE TITLE
Challenge Sectors

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3328]
### Describe the content or mechanics you are proposing.

Sectors specifically designed to have a handicap as meant to become a challenge. Something like #2956

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To break up the repetitiveness of procedurally generated sectors.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ander292** [comment]
Good idea, but I have a better idea. Instead of challenge sectors those would be challenge maps organized in a way that V5 maps were. You cannot launch with recources and you cannot export them. Some advanced tech could be hidden behind them.
