### ISSUE TITLE
Teritorial Control Core

### ISSUE THREAD

**Issue by EdragonProGab** [Anuken/Mindustry-Suggestions#333]
The idea is to create core who is placed in world before game start, with your and enemy core (for pvp mode) . This core will be in none team but contain some defence on it who will attack anyone ... After one of the player destroy's that core, core and defence building around will become his core and winner is player who captore all core.

Whit this block, we could make 2 more gamemode: 

King Of The Hill - there is 3 core on map: your, enemy and hill (core in middle of map), after someone capture "hill core" he will start getting points (1pt every minute, this can be edited in map info) person who got 100 point first will win

Control Point - there is 4 - 8 cores on the map: your, enemy, and others are "core control points" (CCP) . Every CCP come with defences and factories who are in none team and will attack anyone who get close, idea is to capture all ccp and enemy cores to win
 

(Idea is from game Tf2 like control points, or 5cp)

Optional ideas: 

-after core is captured all defence building around will be repaired and destroyed building will be builded again
- every captured core will multiple x0.5 your ressurce

**Comment by ILiekMelons** [comment]
🤔

**Comment by DeltaNedas** [comment]
plugins

**Comment by Anuken** [comment]
This is best implemented with plugins.
