### ISSUE TITLE
sand extractor

### ISSUE THREAD

**Issue by Enderman664** [Anuken/Mindustry-Suggestions#3330]
### Describe the content or mechanics you are proposing.

A sand extractor that can only extract sand in the stone/basalt

-Requires electricity
-160 energy units per second
-Its extraction can be improved with water
-4/s of sand
-6/s sand with water upgrade
-It will measure 3x3 blocks
-Can be investigated after the oil extractor

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

On some maps it is very difficult to get sand, Sometimes there is no scrap and very few sand blocks, the extractor would not change the game too much since it is achieved in the final stage

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
wait for the stone wall extractor in v7 release, p l e a s e

**Comment by Enderman664** [comment]
That's why I'm asking, it probably can't be used on planets

**Comment by EclipseTheOldOne** [comment]
wait and see, stone wall extrator has no reason to be unusable on planets


> That's why I'm asking, it probably can't be used on planets

**Comment by oinkymoo** [comment]
just use airblast it makes 11/sec when boosted

**Comment by EclipseTheOldOne** [comment]
> just use airblast it makes 11/sec when boosted

we're talking about place with no sand/scrap

**Comment by itcannotbe** [comment]
> > just use airblast it makes 11/sec when boosted
> 
> we're talking about place with no sand/scrap

Why would you make such map though?

**Comment by EclipseTheOldOne** [comment]
> > > just use airblast it makes 11/sec when boosted
> > 
> > 
> > we're talking about place with no sand/scrap
> 
> Why would you make such map though?
> 
> ~Where is my copper/lead extractor at?~

~~there aren't that much ores in a stone to be extracted~~

**Comment by PizzaBurgz** [comment]
> wait for the stone wall extractor in v7 release, p l e a s e *Anuke said it the only way to get sand on space, but he doesn't said it can be used in planets

> wait and see, stone wall extrator has no reason to be unusable on planets
> 
> > That's why I'm asking, it probably can't be used on planets

The suggestion says on stone tiles, not stone walls
