### ISSUE TITLE
Folders in the schemes menu.

### ISSUE THREAD

**Issue by AntiTrio** [Anuken/Mindustry-Suggestions#3332]
### Describe the content or mechanics you are proposing.

Create folders in the schemes menu.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Have you ever had over 500 schemas and tags don't help anymore. It would be nice to have the creation of folders, since in the same explorer you create folders to store files of different subjects in them. It would be convenient to store different types of circuits: for example, arts or processors. Tags for schemes are also convenient, but folders would look better, especially if they were not a list, but showed what was stored in them.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IIINSTINCT** [comment]
most likely this will not happen sadly I myself suggested this way before 

Schematics Tags are added by anuke to address the suggestions like this about 6 months ago

**Comment by Darkness6030** [comment]
👍
