### ISSUE TITLE
Ground Unit

### ISSUE THREAD

**Issue by williams104** [Anuken/Mindustry-Suggestions#3333]
### Describe the content or mechanics you are proposing.

Tier 1: Basic 4 wheeled vehicle with a duo-like turret on top.
Tier 2: Slightly slower car with a basic rocket launcher. (not homing, but decent range. around 18 blocks)
Tier 3: Same as level 1, but with a salvo and even slower.
Tier 4: Same as level 2, but with many rockets that fire in large bursts. Longer range.
Tier 5: A tank with treads. very slow, but has a massive canon that ejects large shells. Very long-range, High damage. Like a Hail but slower firing

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Just some ideas for some wheeled/treaded vehicles.
I don't care if you change the order or if they have treads or not.

Ones with wheels will be for hit and run tactics, and treaded ones will be for longer-range artillery. Those will be ground only just as a downside to the range.

I will be giving some ideas for underwater ones, and am thinking up ideas for some air ones.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by williams104** [comment]
Just to clarify, the Tier 1 isn't merged behavior, just that I thought that the duo would be a good example of how it fires.

**Comment by oinkymoo** [comment]
both of the niches you suggested are alreaady filled. we have hit&run units in the form of flares and horizons, and quads. fortress is artillery unit. this isn't necessary

**Comment by williams104** [comment]
Okay, I forgot about the fortress.
I thought that it would add to variety.

**Comment by SwitchLikesMlog** [comment]
please close the issue now thanks
