### ISSUE TITLE
Water Unit/New ability

### ISSUE THREAD

**Issue by williams104** [Anuken/Mindustry-Suggestions#3334]
### Describe the content or mechanics you are proposing.

Tier 1: A submarine that explodes on contact. Can submerge.
Tier 2: A submarine that shoots two missiles at a time. Also can submerge.
Tier 3: A submarine with 3 missiles, but has a radar that will reveal submerged units. Can submerge.
Tier 4: A larger submarine, that fires larger missiles and has smaller anti-air turrets or a radar. Can submerge.
Tier 5: The largest one. Fires four large missiles and has 1-4 salvo (or scatter) like turrets. Can submerge and has a radar.

The submerge ability will hide a ship for a certain amount of time. It will make the ship the same color as deep water.
Only submarines will be able to submerge and will be the same button to fly on some ground units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Just another idea.
I liked the idea of a submarine, and if you have any ideas for changes please tell me.
All projectiles will be able to hit submerged units, but enemy units will not be able to detect submerged units that aren't found by radar (the ability, not logic radar).

Would add another unique type of water unit.
There are only two, including the new one coming out.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
to quote what anuke said when revealing the automatic drone transport system in #dev-previews: "Logic should be an optional part of the game; this system is much simpler to set up and configure.". radar, which only exists in logic, should therefore also be optional

**Comment by williams104** [comment]
No, not like that.
I meant a radar to counter the submerging ability and reveal enemies submerged.

**Comment by williams104** [comment]
> this suggestion is as bad as the previous one

And?
I'm just putting out ideas, hope to add variety to the game.
If you have a problem with it, just tell me it and i could change/fix it.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/477#issuecomment-689262235

**Comment by williams104** [comment]
> [#477 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/477#issuecomment-689262235)

I see what you're saying, but I feel that the quote is outdated. There are enough water maps to have more units.
