### ISSUE TITLE
Large Payload Conveyor

### ISSUE THREAD

**Issue by Salty-Potato133** [Anuken/Mindustry-Suggestions#3335]
### Describe the content or mechanics you are proposing.

A 7*7 payload conveyor only for moving T4 or T5 units. It can look and behave like a regular payload conveyor, except It only connects T4 and T5 reconstructors and accepts T4 and T5 units due to its size. Description Idea: "Moves very large payloads, such as high tier units from factories". It can be unlocked after you unlock payload conveyors and T4 reconstructors. It should cost more materials and take longer to build compared to the payload conveyor. Due to its larger size, it should also have more health.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it would be useful for moving T4 units to T5 reconstructors and for moving high tier naval units to the water. this would make high tier naval units more convenient to build, as this allows you to build them closer to where you have resources (typically the core) without having to build long conveyors or use logic.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/553#issuecomment-695827442

**Comment by oinkymoo** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2531#issuecomment-857330161

**Comment by oinkymoo** [comment]
in conclusion, this is not happening and never will. close this

**Comment by Bottinator22** [comment]
If this does get added, blocks that are 3x3, 4x4, 5x5, and 6x6 would be movable by these too

**Comment by Bottinator22** [comment]
> [#553 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/553#issuecomment-695827442)

now that the large Constructor exists, there's actually a reason for this now, but it'd probably be 5x5 payload conveyors

currently large Constructor isn't very useful

**Comment by itcannotbe** [comment]
> > [#553 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/553#issuecomment-695827442)
> 
> now that the large Constructor exists, there's actually a reason for this now, but it'd probably be 5x5 payload conveyors
> 
> currently large Constructor isn't very useful

You can still use a 3x3 on a payload conveyor.

**Comment by Salty-Potato133** [comment]
Anuken himself said logic should be optional and my idea is for using this to transport T4 or T5 units and maybe one day very large blocks

**Comment by Salty-Potato133** [comment]
Also I do think this would be useful for T4 or T5 naval units so you don't have to build them right next to the water.
