### ISSUE TITLE
Player Machine Gun

### ISSUE THREAD

**Issue by TurkeyTray** [Anuken/Mindustry-Suggestions#3336]
### Describe the content or mechanics you are proposing.

A block that you can place down and it fires really rapidly but the player has to control it. It isn’t automatic at all (unless someone uses the processing blocks). It requires lead at a rate of 3 lead/s and has a storage of 10 lead. It will do a balanced amount of damage but fires faster than any current towers. Building costs will be something like 100 titanium, 50 thorium, 250 surge alloy, and 30 plastanium. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will add more gameplay options by increasing a way the player can affect the game. It’ll give the player a sense of thrill to destroy the enemies themselves in their own dedicated gun (and not the automated towers). However, it will be a space waster when it’s not being used. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
![Screenshot_20220124_082049](https://user-images.githubusercontent.com/45280919/150704347-50f5c187-b6f7-4b07-9d96-07421d0553b3.jpg)

**Comment by itcannotbe** [comment]
What's that I hear?

You can possess turrets?

That's already in the game?

Oh fuck, I wonder why did OP even think to suggest this?

Probably OP isn't familiar with all the content already in the game or have glanced at the wiki to make sure the suggestion doesn't exist in the game yet.

**Comment by TurkeyTray** [comment]
I’m not going to defend it but I hoped I could’ve been more clear about what I was saying.

**Comment by BiggerBrainYT** [comment]
From what I'm understanding, this is a turret that is only player controlled which would make it very unique. I don't understand the replys because yes, you can control turrets and you can use micro processors, but I don't think that's the point.
