### ISSUE TITLE
Color of surge and plastanium

### ISSUE THREAD

**Issue by williams104** [Anuken/Mindustry-Suggestions#3337]
### Describe what you would like changed, and why.

The colors and shapes of plastanium are too similar, and I cannot tell them apart, being colorblind.

### Describe the changes you want to propose. Include possible alternatives.

Either change or add a colorblind mode that will make them more distinct, or add a chemical formula type symbol at the bottom, when turned on.

**Comment by itcannotbe** [comment]
Let's play a game, identify which is which:

Item A:
![Surge-Alloy](https://user-images.githubusercontent.com/45280919/150824214-7aad15cc-af2d-4568-82e9-244d84591627.png)

- [ ] Plastanium
- [ ] Surge Alloy

![Plastanium](https://user-images.githubusercontent.com/45280919/150824222-da51f770-5c83-491d-ad27-c1d88039ea0e.png)

- [ ] Plastanium
- [ ] Surge Alloy

**Comment by itcannotbe** [comment]
![image](https://user-images.githubusercontent.com/45280919/150827896-30057503-499c-45c8-9da4-f7fff29c4eda.png)

Yeah I can still identify the difference. One is a rectangle, the other is a square.

**Comment by oinkymoo** [comment]
ok but this isn't a good comparison. suppose your surge and plastanium lines are getting mixed, and now you need to locate every piece of one when they're partially covered by adjacent materials. your only option at this point if you are colorblind is to check every single tile of belt one by one until you have extracted every last offending item

**Comment by williams104** [comment]
_shivers_

**Comment by itcannotbe** [comment]
> ok but this isn't a good comparison. suppose your surge and plastanium lines are getting mixed, and now you need to locate every piece of one when they're partially covered by adjacent materials. your only option at this point if you are colorblind is to check every single tile of belt one by one until you have extracted every last offending item

Or separate them with a sorter.

**Comment by Cleanup-Crew-From-Discord** [comment]
for the time being, what colors *can* you see @williams104 ? I'm sure someone who knows how to make a texture pack mod could whip one up for these items in specific rather quickly, in fact I probably could (if I didnt have stuff to study / prepare for)

**Comment by williams104** [comment]
I can see all of the materials, except for those 2.

**Comment by myutin** [comment]
I'll work on this with a friend of mine. Might have a PR in a week or so. Since v7's full release is a ways off, the mod would also be a good idea.

Until either of the above happens, your best bet is the sorter. (Somewhat unfortunate that the sorter runs into the same color conflict.)

**Comment by BiggerBrainYT** [comment]
I don't understand why people are so against changing these icons, they are just squares and rectangles. Seeing them far away without color would be hard. A redeisgn could be taken advantage of to make a very cool new look.

**Comment by itcannotbe** [comment]
> ![image](https://user-images.githubusercontent.com/45280919/150827896-30057503-499c-45c8-9da4-f7fff29c4eda.png)
> 
> Yeah I can still identify the difference. One is a rectangle, the other is a square.

Not that hard.

**Comment by williams104** [comment]
itcannotbe, it CAN be.

**Comment by lizzyd710** [comment]
The comments on this issue are very disheartening. You want people to play your game, but when someone says they need a slight modification to be able to play, you decide it's not worth the effort, that the player is not worth the effort. 

@williams104 I'm working on this with @myutin. Is there a certain type of sprite that tend to be more difficult?

**Comment by williams104** [comment]
Everyone is different, but I mainly have trouble with the two resources plastanium and surge.
Some blocks I have trouble with, but I can hover my mouse over them and see what it is.

**Comment by williams104** [comment]
Also just to add, I am mildly colorblind and can see most colors.
Other people may not be able to see as well as I can (people who are colorblind) and this probably wouldn't help.
