### ISSUE TITLE
Drop pods

### ISSUE THREAD

**Issue by williams104** [Anuken/Mindustry-Suggestions#3338]
### Describe the content or mechanics you are proposing.

A purely visual effect for when enemies spawn.
Blocks will fall down (like a core), spawn 1 to 4 enemies, cause a shockwave, and destroy themselves. Larger enemies will spawn in larger blocks and will spawn less per block. This would be good for enemies that are to large to be in a dropship, or to remote for a dropship to fly there.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will solve the problem of very large enemies in a dropship, and give variety to spawning.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
you did NOT check the trello

**Comment by williams104** [comment]
yes i did
this is just an alternative to dropship
both can happen
I will turn you off

**Comment by itcannotbe** [comment]
https://trello.com/c/bqKwLdqU/899-enemy-wave-dropship

**Comment by itcannotbe** [comment]
Also:

> Blocks will fall down (like a core), spawn 1 to 4 enemies, cause a shockwave, and destroy themselves.

~Yay! No more enemies! Oh wait, no more enemies?~

**Comment by williams104** [comment]
I see what you're saying, but it would be cool if a 5x5 block dropped, and a toxipod slowly crawled out.
