### ISSUE TITLE
VCPUs

### ISSUE THREAD

**Issue by nilederg** [Anuken/Mindustry-Suggestions#3339]
### Describe the content or mechanics you are proposing.

Hyper processors should support CPU virtualization

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

windustry

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
lol

**Comment by itcannotbe** [comment]
Did I miss the meme that was supposed to inform me that this is a joke?

**Comment by Ruichka** [comment]
mindustry in jvm in os in hyperprocessors in mindustry :sunglasses:

**Comment by SwitchLikesMlog** [comment]
... print and printflush...

**Comment by SwitchLikesMlog** [comment]
can you please close the issue

**Comment by nilederg** [comment]
yeah ill close it lol
