### ISSUE TITLE
A new achievement I thought of

### ISSUE THREAD

**Issue by Funny132** [Anuken/Mindustry-Suggestions#3341]
### Describe the content or mechanics you are proposing.

Basically, an achievement labeled as "How did that even happen?" or something. It would be earned by being destroyed by your own projectile reflected off a Phase Wall.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This is more of a silly little achievement, I don't think it needs to add much. It's just a fun little thing for people who don't realize that they deal 1% damage to buildings. This would only count for player ships, not other units controlled by the player.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by williams104** [comment]
I like it.

**Comment by OnyxFinger** [comment]
Yeah I like it too

**Comment by williams104** [comment]
Also, there should be one called "Pain", when the wrong item goes into a smelter, press, etc.

**Comment by Arcanilius** [comment]
Someone already said this achievement in a discution in trovo, or u are the same guy, or u just took he's idea

**Comment by Funny132** [comment]
> Someone already said this achievement in a discution in Trello, or u are the same guy, or u just took he's idea

I just want to point out, and I don't want to come off rude here, just because two people thought of the same idea doesn't mean that one copied the other. I didn't even know there was a Trello discussion thing.

**Comment by itcannotbe** [comment]
You should have. After all you're supposed to freaking check it before making a suggestion here.

ALSO YOU MAKE THE CHECKBOX.

THIS CHECK BOX

- [X]  I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

**Comment by Funny132** [comment]
> * [x]   I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

I knew about the Trello, I just didn't know that you could comment or discuss things on there, okay? I did check the Trello list, don't worry,
