### ISSUE TITLE
The color of illuminators

### ISSUE THREAD

**Issue by regymm** [Anuken/Mindustry-Suggestions#3342]
### Describe what you would like changed, and why.

I don't know if anyone takes illuminators seriously, but seems currently in v135 the color is quite dim -- in the picture I placed a lot and only in the border of lights I can see the magenta color. 
![image](https://user-images.githubusercontent.com/31496626/151100440-ef7e7a74-2ee4-4cf8-b405-176d7f0d2e43.png)

### Describe the changes you want to propose. Include possible alternatives.

It'll be nice to make the whole range of illuminators have a color, instead of just the borders. It'll make the night much more attractive.

**Comment by Ruichka** [comment]
Illuminator already does that: it's just that other buildings/units produce lighting too. If you place a lone illuminator, you'll see it lights up the entire area.

**Comment by SuperThunder958** [comment]
> Illuminator already does that: it's just that other buildings/units produce lighting too. If you place a lone illuminator, you'll see it lights up the entire area.
> 
> Also, it looks like you have another illuminator near ripple which is set to white.

Yeah there is your illuminated there but it's not white it's like a yellowish green

**Comment by numer99** [comment]
I do agree that illuminators should have more intensely colored lighting, but there are also other things making light in that area
