### ISSUE TITLE
Campaign enemy "resource-producing" maps

### ISSUE THREAD

**Issue by regymm** [Anuken/Mindustry-Suggestions#3343]
### Describe the content or mechanics you are proposing.

There are a lot of not-named attack sectors with enemy bases, but these seem too similar to each other, and enemy seems to have infinite resources from nowhere. 

So I suggest changing some medium or low difficulty attack sectors into the form that enemies have low attack/defense but a whole bunch of recourse mass-producing facilities. Maybe even a sector with many vaults and launchpads just like our salt flat base. And developers can select some curated schematics from Discord to show up in enemies' resource-farming sectors -- maybe as a bonus to devoted Mindustry players. 

I guess it won't require fundamental changes to the game and is relatively easy to implement? 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This makes enemies' bases more complete. And it may promote more players to do global domination, and promote schematics usage. It'll certainly be a lot of fun to raid these sectors, too. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SuperThunder958** [comment]
This is not a good idea it's an extremely good idea
