### ISSUE TITLE
Logic sensor "blockstatus"

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#3344]
### Describe the content or mechanics you are proposing.

A new sensor for blocks, returns a number to represent the working state of the block.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Return 0 means not working, such as no power, no resources, or been disabled.
1 means working well
2 means waiting for working, probably the items/payloads inside are full
3 means ... I can't think of anything else, does anyone have other ideas?

And these status should be same with the in-game block status
![Screenshot_20220127-102216209_1](https://user-images.githubusercontent.com/45112661/151282457-c716fed9-0449-4e23-b643-d6c2240ba115.jpg)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Can't you already check for these things without creating a new sensor specifically for it?

**Comment by SwitchLikesMlog** [comment]
i actually like this suggestion


> Can't you already check for these things without creating a new sensor specifically for it?

yeah kind of, but its not really easy
