### ISSUE TITLE
Friendship feature 

### ISSUE THREAD

**Issue by Ashmaster11** [Anuken/Mindustry-Suggestions#3345]
### Describe the content or mechanics you are proposing.

Features that can make friends with other players.
We can also multiplayer in camping mode or other mode without waiting for other players to enter. If it's pvp mode but multiplayer mode, our friends will become enemies. we can also invite friends to play server together. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

- New menu (Friends menu) 
- New button on server (Add friends) 
- New menu in menu resume (call friends) 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ashmaster11** [comment]
Are you going to add it

**Comment by itcannotbe** [comment]
Isn't this basically steam version stuff?

**Comment by NrkSed** [comment]
*"New menu in menu resume (call friends)"* Call friends? is this Discord or Mindustry? 

*"Are you going to add it?"* Thats why you were supposed to read https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md before posting.

Multiplayer on campaign..... Campaign (aka Singleplayer) is not supposed to be multiplayer. Just make a custom game.

In any case if you want to play with friends in itch.io version just connect to the same wifi or hotspot or port-forward.

**Comment by Ashmaster11** [comment]
Mindustry Android and Ios

**Comment by Ashmaster11** [comment]
You can change the name of the menu
