### ISSUE TITLE
(V7) Option to limit block groups based on availability on planets 

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3346]
### Describe the content or mechanics you are proposing.

QOL for map makers + ease of migration of maps to the newer version.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since erikir blocks are vastly different from serpulo blocks, it is prudent to prevent the use of them on maps made for a specific set of blocks.

Though map makers has still the option to individually ban blocks.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
From what I've seen in the #dev-previews, Erekir stuff mostly relies on special ores which are only present on the Erikir. So, you can simply exclude those ores from your map.
