### ISSUE TITLE
More resource

### ISSUE THREAD

**Issue by kershi** [Anuken/Mindustry-Suggestions#3348]
### Describe the content or mechanics you are proposing.

wat if we can make it so that different units require can be modified with a piece like maybe the daggers could get  a gun to be input it will make the dagger more stronger. and maybe same with fluid maybe there can be new type of fluid that can make the unit faster or slower.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this will improve the game since theres more stuff to experiment with. it can add options for player to enhance there units or not to enhance it, they can also think of a better strategy

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Balancing hell.

**Comment by NrkSed** [comment]
what else do you need when you have T5 units lol

**Comment by RFAC-Productions** [comment]
And besides, we're already getting new resources, judging on those previews.
