### ISSUE TITLE
Hydroelectric power

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#335]
**Describe the content or mechanics you are proposing.**

A block (`hydroelectric-turbine`) that will reside on liquid blocks (possibly water only?) with elevation over them.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Filling the gap between combustion generators and steam generators where fuel is not as abundant.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This won't be added for several reasons:
1. Elevation is not going to become a mainstream feature (even if it is kept in v6)
2. Even if elevation were made mainstream, this requires extremely specific conditions that will not be present in most maps.
3. There was a long discussion in #development about this, and the conclusion was that hydroelectric power just isn't very interesting, and would just be a slightly different version of solar/thermal generators.

**Comment by BasedUser** [comment]
that last one doesn't account for lighting or the mapper in question
