### ISSUE TITLE
Strategic bombers

### ISSUE THREAD

**Issue by Randomcapitalist** [Anuken/Mindustry-Suggestions#3350]
### Describe the content or mechanics you are proposing.

A flying unit that would be great to see in the game would be a  B29 style bomber. It would basically be a horizon bomber but stronger and with machine guns on it. It would also be very good against buildings. If you add the machine guns, make sure they are fast with low damage. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I know you have the big green aircraft, but I would not count that because it is really slow and not a plane. It also lacks defense against aircraft. A strategic bomber would be a very interesting addition to the rather wide selection of units. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
there is a few problem
the offensive (attacker) tree are filled from t1-5, mean there's no place for your unit
horizon unit is a bomber type, just no machine gun on it

**Comment by 50275** [comment]
take a horizon, two flares and a zenith, and somehow use logic parts to make them all move in a formation

bomber acquired lmao
