### ISSUE TITLE
remove auto-generated drills when landing on a sector.

### ISSUE THREAD

**Issue by Nicky-Pixel** [Anuken/Mindustry-Suggestions#3351]
### Describe what you would like changed, and why.

when cloning a core and landing on a random sector, drills and conveyors will be there waiting for the player even if they were not actually built, which breaks some of the reality and sense of cloning only the core.

### Describe the changes you want to propose. Include possible alternatives.

removing them would make more sense, give more value to the manual mining learned in the Ground Zero tutorial (if only for a few seconds, until you can build drills on your own), and encourage players to configure their loadout before going down their route of dominate the world.
![Screenshot_20220129-140724](https://user-images.githubusercontent.com/85355379/151670837-6aad5bb2-3ce9-4087-8c96-f3e674183a63.png)

**Comment by Facosa99** [comment]
Fella, those drills supposedly came from space with you. Now, the thing is, you can already delete those drills. 

Before deploying to a new secotr, it lets you choose an schematic from a list of possibilties so you dont start emtpy handed. Now, thing is, you can save your own schematics, including lone cores ones.

**Comment by Anuken** [comment]
I'd *like* to remove those drills, but you have to consider the effects of not providing starter copper to players.

**Comment by SwitchLikesMlog** [comment]
i think the purpose of this is to show players the ability to launch with schematics

**Comment by Anuken** [comment]
No, it doesn't really show players anything - there is no indication that you can select an area around your core and save it as a schematic for use in launching. You can probably come to that conclusion through experimentation, but it's a massive leap.

**Comment by SwitchLikesMlog** [comment]
so it just.. exists, then

**Comment by Anuken** [comment]
On the new planet, there are no starting drills or schematic loadouts. Depending on feedback, I may implement the same for Serpulo as well.

**Comment by LeoSko** [comment]
> the effects of not providing starter copper to players

 https://github.com/Anuken/Mindustry/issues/4094

**Comment by nilederg** [comment]
idk why this has so many downvotes on discord, it makes sense, and i really hate how much it breaks immersion that the core spawns ore underneath it, also the ore is just annoying and ocd inducing

**Comment by Anuken** [comment]
> `Anuken/Mindustry#4094`

I don't see what that has to do with what I said - that's *one* optional procedurally generated sector, and it already has copper around the core anyway. Many maps don't.

> idk why this has so many downvotes on discord

You could try asking the downvoters.

(Re-opening due to active discussion.)

**Comment by SwitchLikesMlog** [comment]
> the effects of not providing starter copper to players.


cant players just mine copper manually?

**Comment by Anuken** [comment]
Yes, but now there's no guarantee that there's some next to your core... or in the map at all, as far as custom games are concerned.

(I may be overestimating the importance of this.)

**Comment by code-explorer786** [comment]
There's already a method to remove the drills : **core schematics.**
You can make a schematic with only 1 shard core, and select it while you are going to launch to a sector.
![Screenshot_2022-02-01-12-33-24-91_13f989b68d7412e5a177fb13b36ac66f.jpg](https://user-images.githubusercontent.com/68312688/151917757-0cf8682e-d5d0-4a4b-bd39-a8dc20702657.jpg)
If you're extremely lazy to make one yourself, here's the schematic:
```
bXNjaAF4nGNgZmBmZmDJS8xNZeBMzi9KLc5ILEph4E5JLU4uyiwoyczPY2BgYMtJTErNKWZgio5lZOACKdOFqGNgYAQhIAEAr+cRSw==
```

**Comment by Facosa99** [comment]
> idk why this has so many downvotes on discord, it makes sense, and i really hate how much it breaks immersion that the core spawns ore underneath it, also the ore is just annoying and ocd inducing

You realize that the ore was already there and the core landed next to it? At least on campaign maps thats the case. Why would shard launch a core in the middle of nowhere when a couple meters south you have a situable location with the materials to start conquest of the sector

**Comment by NrkSed** [comment]
Well, the drills really "drown" the ability to mine. Mining is mostly used in PvP duels when you just start off, but in general I think those drills should be removed, as its just a waste of a mechanic. And if there is no copper node nearby, just bring some copper when with you when you launch.

**Comment by SwitchLikesMlog** [comment]
> Yes, but now there's no guarantee that there's some next to your core... or in the map at all, as far as custom games are concerned.

but you cant use (or launch with) core schematics in custom games, can you?

**Comment by Anuken** [comment]
~~I forgot that custom games don't place the starter shard drill schematic.~~
