### ISSUE TITLE
new building system

### ISSUE THREAD

**Issue by Radio-Silence-1** [Anuken/Mindustry-Suggestions#3352]
### Describe the content or mechanics you are proposing.

A new building system.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

(i did not come up with this, somebody on discord did, but i wanted to suggest it, so i am here.)
Imagine Mindustry gets a new dimension: design of the functional elements themselves. Imagine you have the same game mechanics as always but now add the dimension of designing the mechanical pumps. mines, etc. in a new part of the game. I'm actually talking about being able to modify the parameters of the functional elements in the game (pumping speed, flow rate, etc.) by designing better parts. As you progress through the tech tree, new materials allow you to design more and more efficient elements. Think about it this way: every 1x1 block in Mindustry is actually a coarse-grained (say, macro scale) version that has the familiar parameters. But 'zooming into' the 1x1 block and changing the way it works on a smaller length scale (finer grain / microscale) can improve its functionality on a larger length scale. So I am talking about some 'design' menu. Indeed it will probably end up as a mod, but imagine that it would not. Think about the basic pump having some pumping element made out of metaglass, that you can turn into surge or plastanium. Imagine being able to 'lace' your buildings with plastanium so they don't auto-connect to the grid if you dont want it. Note that the 'design interface' doesn't have to be real-time: all it needs is to calculate the building's parameters from the design in the fine grid / microscale , and just spit out a new building in the coarse grid /macroscale which has those new parameters. And yes, it would need a physics interface. But luckily Scindustry community knows a lot about that.
![image](https://user-images.githubusercontent.com/98431859/151678478-738f14be-f131-40d7-a655-28f2eaeecd93.png)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ducheng0** [comment]
This would be awesome

**Comment by itcannotbe** [comment]
Mindustry is not supposed to be a complicated game to play.

**Comment by itcannotbe** [comment]
Also try reading the read me...
