### ISSUE TITLE
units with freezing abilities

### ISSUE THREAD

**Issue by AstronautCat380** [Anuken/Mindustry-Suggestions#3353]
### Describe the content or mechanics you are proposing.

I'm not saying to add simple units that deal damage but that. In the game we already have units that shoot bullets, lasers and even fire and lava. Less ice, it would be no a unit that deals damage But that made all the difference when used together with other drones in an attack. Just as waves and tsunamis when using cryogenic fluid can be lethal to spacecraft, these drones could be a mobile threat to spacecraft. Also they could have the ability to put out fires. It would be very useful since you can't always make waves and tsunamis in time to put out the fire before it destroys something.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The benefits are described along with the suggestion.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Sure. Maybe it could slow down the gameplay in PvP, but this is rather unlikely to happen

**Comment by AstronautCat380** [comment]
maybe it happens because it's something new and it would make sense to be in the game. as it has many uses like putting out fires and taking down drones like the flare easily. and to be balanced  the unit could have a slightly more expensive construction cost thus preventing drones of this type from being mass-built easily.

**Comment by AstronautCat380** [comment]
Another thing I almost mentioned but didn't do because it would make the drone too strong was that it could weaken blocks with ice but then it would lose its balance in PvP

**Comment by NrkSed** [comment]
"*taking down drones like the flare easily*" Umm, scatters work perfectly fine against flares. Also, if you are making units with "more expensive construction cost" flares are the absolute least of your worries.

Also, units are good against T4-T5 Aircraft, because lower tiers are much faster and can go around you faster than you can turn.

In any case, it *could* be an interesting idea for a unit, possibly some of the higher tiers

**Comment by nilederg** [comment]
i like this, would definitely need a lot of balance, but i think we do need more variety in the ways units do damage, and the effects they give.
