### ISSUE TITLE
Blacklist for pathfinder

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry-Suggestions#3354]
### Describe the content or mechanics you are proposing.

Add a blacklist Seq in every UnitType. Adding a tile to this Seq means that every unit of this type can't move to this tile. And this should be customisable.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will really help plugin-developers and map-makers.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Darkness6030** [comment]
For example:

`UnitTypes.crawler.blacklistTiles.addAll(Blocks.grass, Blocks.snow);`

And crawlers won't walk on snow and grass

**Comment by genNAowl** [comment]
Is this another attempt at creating anti-air walls?

Why do I feel like this will destroy pathfinding (especially for air units, which don't have any at the moment)?

And finally, wouldn't it be hard to implement a way to prevent units from moving onto certain tiles (like when commanded by a player or logic)?
