### ISSUE TITLE
Surge Collider 

### ISSUE THREAD

**Issue by NrkSed** [Anuken/Mindustry-Suggestions#3355]
### Describe the content or mechanics you are proposing.

Surge collider will be a 4x4 block that will generate power by launching surge alloy into each other

Description:
*Generates a massive amount of power from colliding and discharging surge alloy. Requires a large amount of power to kickstart the process*

Base power generation: 9500 Units/Sec
Power needed to kickstart: 1800 Units

Unlike the Impact reactor, the Surge collider instantly starts up, but if it takes damage, there is a possibility of it exploding when it launches surge alloy, releasing shocks everywhere around it

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This might not be useful currently, but might give Anuke ideas on a future power source, possibly on Erekir.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
This sounds like a wish version of the impact reactor, no matter how much sugar coating you put on it.

**Comment by NrkSed** [comment]
@RealYeet The idea is vague, its most likely to be different in game (If it gets added)

**Comment by Facosa99** [comment]
idk, the similarities with impact reactor make it kinda lame. You gotta add some more aspects to make it more unique. Almost every power source in game has unique quirks to promote different strategies depending on current necesities and resources or simply to add variety. For example, Impacts are hella complex to set up, steam requires water, thorium reactors go boom boom, etc.

**Comment by NrkSed** [comment]
It could have a combination of specialities. And again, the idea isn't finished, so in the future it could have a speciality of its own

**Comment by 50275** [comment]
Mod the game

**Comment by stuffyAI** [comment]
> It could have a combination of specialities. And again, the idea isn't finished, so in the future it could have a speciality of its own

Why did you not finish your idea before posting it here?
