### ISSUE TITLE
Only new, but I think it'd be nice to add :)

### ISSUE THREAD

**Issue by FooSarr** [Anuken/Mindustry-Suggestions#3356]
### Describe the content or mechanics you are proposing.

It's only really simple and I think it'd help with the early learning process. When hovering over towers in the build menu, I think it would really help to see a preview of the lowest tier requirements as you hover over it with your mouse, similar to other RTS games. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it'd help with the learning process again and quickly making decisions. Again, it's not hard to open the hint menu but I think this would help the flow just a bit more.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NrkSed** [comment]
Uhh, I didn't quite understand what you said.. What do you mean with "lowest tier requirements"?

**Comment by FooSarr** [comment]
> Uhh, I didn't quite understand what you said.. What do you mean with "lowest tier requirements"?

So you know how the Duo turret fires copper, but it can also fire out Graphite, Pyratite, etc? Having it show up in a little text box as you hover your mouse over it detailing that 'copper is the minimum required ammo source' for example. Or with the Mines having it say as you hover over that it can 'Mine Thorium' or 'Can mine Titanium' for example? Not sure if that helps display my idea better, I could try and mock up an image?

**Comment by NrkSed** [comment]
Ok i got what you mean, but after looking it up like 2 times you already know it by heat, so spending effort for only that is useless.. Maybe something similar might get added to the future though

**Comment by oinkymoo** [comment]
you can hit the info button to see that, and also tiers are poorly defined. what comes first out of graphite, silicon, and pyratite? water, oil, and slag?

**Comment by NrkSed** [comment]
Literately the FIRST thing you are supposed to do in campaign is to mine the Most basic resource - Copper, and by logic it would also be the most basic type of ammo (If you cant decide which is the least complex ammo between water oil and slag, then I dont know what to say). And why would you want to know the "minimum requirements" for a turret? Just use the ammo you want.

**Comment by oinkymoo** [comment]
Water and oil become obtainable at the exact same time, and depending on which tech you unlock when, you could very well access slag before the other two. Also what about lead and scrap? They can both be used by scatters, and are both mineable with the first drill, and may be unlocked in either order.

**Comment by Ander292** [comment]
> you can hit the info button to see that, and also tiers are poorly defined. what comes first out of graphite, silicon, and pyratite? water, oil, and slag?

Graphite, silicon and pyratite (this order)
Water, Slag, Oil, Cryofluid (this order)

**Comment by Ander292** [comment]
I would give resources 3 tiers:
-Tier 1 (Raw Resources, Graphite)
-Tier 2 (Resources being made using raw resources, thorium is here)
-Tier 3 (Resources being made using fluids and other resoruces or its recipie contains one T2 resource)

**Comment by oinkymoo** [comment]
> > you can hit the info button to see that, and also tiers are poorly defined. what comes first out of graphite, silicon, and pyratite? water, oil, and slag?
> 
> Graphite, silicon and pyratite (this order) Water, Slag, Oil, Cryofluid (this order)

By the logic you provided, slag is tier 2, as it is made only from scrap. Oil and water both require metaglass. 

> I would give resources 3 tiers:
> -Tier 1 (Raw Resources, Graphite)
> -Tier 2 (Resources being made using raw resources, thorium is here)
> -Tier 3 (Resources being made using fluids and other resoruces or its recipie contains one T2 resource)
> This would be surge, plastanium, Phase...

Ok then what about a duo. Its ammo options include both copper and graphite, both in tier 1. Which of those comes first?
