### ISSUE TITLE
Where boulder on main menu background

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3357]
### Describe the content or mechanics you are proposing.

need boulder on main menu background

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

bottom text

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
this is not a place for jokes. if you're not going to take this seriously, don't make a suggestion

**Comment by Bottinator22** [comment]
~~wdym this isn't serious this is totally the most essential suggestion of them all~~

**Comment by Ander292** [comment]
This is as important as the skin resolution. Anuke shouldn't waste his time reading this

**Comment by Ander292** [comment]
Also скат

**Comment by itcannotbe** [comment]
This suggestion doesn't even that that much time to implement actually...

**Comment by OnyxFinger** [comment]
> this is not a place for jokes. if you're not going to take this seriously, don't make a suggestion

lmaooooo
https://github.com/Anuken/Mindustry-Suggestions/issues/3292
https://github.com/Anuken/Mindustry-Suggestions/issues/3000
https://github.com/Anuken/Mindustry-Suggestions/issues/3111
https://github.com/Anuken/Mindustry-Suggestions/issues/3114

**Comment by oinkymoo** [comment]
yeah none of those suggestions should have been made, what's your point

**Comment by OnyxFinger** [comment]
> yeah none of those suggestions should have been made, what's your point

My point is that between joke suggestions and thoughtless suggestions, this place is an absolute clown-fiesta

**Comment by SMOLKEYS** [comment]
> This is as important as the skin resolution. Anuke shouldn't waste his time reading this

> Also скат

Can y'all ***JUST SHUT THE FUCK UP WITH BOULDER AND СКАТ?***

**Comment by EclipseTheOldOne** [comment]
> ckat? war? what?

i just want some boulder
