### ISSUE TITLE
Unit Skin system

### ISSUE THREAD

**Issue by GrapheneStar** [Anuken/Mindustry-Suggestions#3358]
### Describe the content or mechanics you are proposing.

I'm suggesting to make gamma/alpha/beta skin system, maybe other units too. So a player will be able to attach a certain image which game will use for his units skin

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make certain players more recognizable also make it easier to catch griefers and more fun for sandbox roleplayers

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LeoSko** [comment]
While this might be actually harder than it looks to implement, feature would definitely find it's use among most of multiplayer community.

**Comment by NrkSed** [comment]
This feature is useless and *even* unhealty for servers because"
1) It would be very hard to implement properly.
2) Would not fit the low-poly game style.
3) Would be a hell to moderate.
4) Nicknames exist, if you can't read them, or remember them then thats a "you" problem. And what do you mean by "catch griefers"? If they grief, you ban them, no need to fly after them.

**Comment by EclipseTheOldOne** [comment]
> While this might be actually harder than it looks to implement, feature would definitely find it's use among most of multiplayer community.

this gonna make the game bad itself
1. the game itself has it own style for each sprite (like try to give me a "type" of vela skin, it's very time-wasting to add skin for nothing ~~no do not suggest maid vela~~)
2. no use at all, skin are shitty flex that add the game more useless space
3. mod exist, sprite-override moment
> So a player will be able to attach a certain image which game will use for his units skin
client-side issue lmao, learn how a server work.

**Comment by LeoSko** [comment]
> Would not fit the low-poly game style.

>the game itself has it own style for each sprite (like try to give me a "type" of vela skin, it's very time-wasting to add skin for nothing no do not suggest maid vela)

Own images *always* don't fit some style, obviously. Alternative solution is to make skins predetermined, or add color-grading to existing units.

> Would be a hell to moderate.

Same degree of moderation as building displays or even chat, no different.

> Nicknames exist, if you can't read them, or remember them then thats a "you" problem. And what do you mean by "catch griefers"? If they grief, you ban them, no need to fly after them.

We all can *read* in every game you find, but player-customization of ***only*** nickname is too limited and has been there for ages, things need to change as similar features found success in every other game you can find.

> no use at all, skin are shitty flex that add the game more useless space

Straightforward solutions performance-wise: limit the space, disable-able skins.

> mod exist, sprite-override moment

Did even understand the difference between native support and mods? :(

**Comment by EclipseTheOldOne** [comment]
> Did even understand the difference between native support and mods? :(
you know fucking understand that texture mod is multiplayer compatible
> Straightforward solutions performance-wise: limit the space, disable-able skins.
explain what the fuck are you saying
> We all can read in every game you find, but player-customization of only nickname is too limited and has been there for ages, things need to change as similar features found success in every other game you can find.
mindustry is a tower defend game with a multiplayer system just to play together, not for flexing shit
> similar features found success in every other game you can find.
gimme a hammer, a pan or a knife
**the fuck do you mean skins = good, so content doesn't matter at all you shit?**

**Comment by LeoSko** [comment]
@EclipseTheOldOne, your agressiveness doesn't make your arguments stronger. In fact, they do opposite.

To make it more clear, if you want to stay without any customization, I proposed a setting that would simply replace skinned entities back with default textures, like it was done in Quake.

**Comment by BorisA11** [comment]
It is a nice feature, but people can already make themselves look different, via a simple json mod which adds an image in sprite override folder. For multiplayer, that would be painful to implement, and will definitely cause more lag.

**Comment by itcannotbe** [comment]
You do realize that resources are loaded in as you start the game right?

How do you do that while playing a game on a multiplayer server?

**Comment by genNAowl** [comment]
Yeah, unless these are predetermined textures or every client has these loaded, I don't think you'll be able to attach images to a specific player and have others see the same thing on their screen. 

I mean, based on my extremely basic understanding of multiplayer, to attach an image to a specific player and have every other player see the same thing would require a way for other players to receive this image, and then you would need to regenerate the sprites-atlas to make it in any way plausibly efficient. 

You could do something like logic displays, but those only work because the system used to render any graphic on them already exists on every Mindustry client; Despite the fact that I haven't looked into the code for logic displays - I would bet that it would be at least (extremely) difficult to do the same for players. 
 
 Of course, you can use a mod (like said before), but unless everyone has the same mod loaded, other people won't see the same thing your seeing (which I assume is the idea of this suggestion; Also, *mods* is not an acceptable response for a discussion here).

**Comment by EclipseTheOldOne** [comment]
> @EclipseTheOldOne, your agressiveness doesn't make your arguments stronger. In fact, they do opposite.
To make it more clear, if you want to stay without any customization, I proposed a setting that would simply replace skinned entities back with default textures, like it was done in Quake.

learn how actual syncing work before talking about related thing

>  your agressiveness doesn't make your arguments stronger. In fact, they do opposite.

i don't use agressiveness to make my arguments stronger, thank.

**Comment by LeoSko** [comment]
> learn how actual syncing work before talking about related thing

I know how it works, and in-code solution is simple **sync-wise**: don't. Pass the data related to skin on connect. Could be inserted into ConnectPacket (https://github.com/Anuken/Mindustry/blob/462a64bf21710fa0738f9526697dab62466e0a00/core/src/mindustry/net/Packets.java#L111), like it is already done for locale/uuid/mobile flag/color.

**Comment by EclipseTheOldOne** [comment]
> I know how it works, and in-code solution is simple sync-wise: don't. Pass the data related to skin on connect. Could be inserted into ConnectPacket (https://github.com/Anuken/Mindustry/blob/462a64bf21710fa0738f9526697dab62466e0a00/core/src/mindustry/net/Packets.java#L111), like it is already done for locale/uuid/mobile flag/color.

okay and, after all
the game itself has it own style for each sprite like try to give me a "type" of quad skin

**Comment by Ander292** [comment]
Haha, skins

**Comment by EclipseTheOldOne** [comment]
> Haha, skins

Haha, skins
Seriously, what?

**Comment by NrkSed** [comment]
>Same degree of moderation as building displays or even chat, no different.

Not really, and even if it is the same degree of moderation, then it just piles up on the already existing issues

In any case, there is simply not a strong enough reason to compromise the mound of issues this proposes.

**Comment by notMEEPoffaith** [comment]
nsfw

**Comment by LeoSko** [comment]
Anyone can draw NSFW stuff using only (*ta-da*) blocks. Why are you so concerned about this then? Do **you** completely block building on your servers for everyone? No. Do **you** block inappropriate nicknames on the server? No - there is no stable way to do this. But we still have building and nicknames on the server. According to this logic, game itself shouldn't exist as it can bring NSFW through chat/pixel art/etc.

This suggestion *does* need the same amount of moderation as anything else in multiplayer right now.

If you are ***so*** concerned about moderation **or styling**, look at or play some Quake and see how it is approached there - same can be applied in Mindustry.

**Comment by EclipseTheOldOne** [comment]
> game itself shouldn't exist as it can bring NSFW through chat/pixel art/etc.

1. understand why: community
2. get out
3. logic displayer cost time to build and process drawing, also not portable
4. and player skin of course are portable to everywhere, also imaging a (shitton) of player with non-mindustry image and nsfw flying around

**Comment by genNAowl** [comment]
Look, you all are arguing about moderating issues of uploaded images, but I think that's not even possible with the current rendering system (because it requires regenerating sprites-atlas?).

**Comment by EclipseTheOldOne** [comment]
> Look, you all are arguing about moderating issues of uploaded images, but I think that's not even possible with the current rendering system (because it requires regenerating sprites-atlas?).

and yes, also that

**Comment by itcannotbe** [comment]
> Look, you all are arguing about moderating issues of uploaded images, but I think that's not even possible with the current rendering system (because it requires regenerating sprites-atlas?).

That's what I said. LOL.

https://github.com/Anuken/Mindustry-Suggestions/issues/3358#issuecomment-1026916580
