### ISSUE TITLE
Power transfer between sectors

### ISSUE THREAD

**Issue by killkoll** [Anuken/Mindustry-Suggestions#3359]
### Describe the content or mechanics you are proposing.

A building that transfers power to adjacent sectors that also have that building. It would be big, expensive, take long to build and you'd lose some power from transferring. This would definitely be more of a late-game thing.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow you to dedicate entire sectors to energy production and use that power elsewhere, similar to sectors dedicated to one resource, i.e. silicon. It would also make things like impact reactors more useful, especially having lots of them, because if you car run one, you can probably run multiple.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
What's the problem with making power on-site? You can just supply its fuel from other sectors if it's too hard for you to mine it there.

**Comment by Ander292** [comment]
The idea is interesting, but it would be importable only to nearby sectors.

**Comment by NrkSed** [comment]
You can fuel 15 thorium reactors by using 2 water cooled drills.... In the worst case just use a launch pad and unload thorium into a thorium reactor/rtg gen

**Comment by 50275** [comment]
no... that's... not how it works... (you need about 1:5 reactors)
