### ISSUE TITLE
Packing fluids into canister items

### ISSUE THREAD

**Issue by Alpha1641** [Anuken/Mindustry-Suggestions#3360]
### Describe the content or mechanics you are proposing.

Not all maps contain fluids that you would like to use in that map; Cryofluid is necessary for higher level unit construction, oil can be sprayed to apply tarred status effects or transformed into coal from a centrifuge, etc.

A potential solution to this problem is the ability to itemize fluids into small containers that can be transported over the item logistics system, such as conveyor belts and more importantly launch pads.
Fluid canisters would introduce 4 new items: water canister, cryofluid canister, oil canister, and slag canister.

A new block would be introduced that receives a fluid as well as a material such as titanium or metaglass and outputs an item that represents X amount of units of liquid. The fluid canisters could be deposited directly into fluid receiving blocks to fill their internal reservoir, or perhaps the canisters would have to be emptied into an existing fluid logistics system to be able to use it; Either way the benefit of transporting fluids from one sector to another through launch pads still stands.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Fluid canisters would allow for more alternatives to water extractors and oil extractors; Sizeable cryofluid production facilities could be compartmentalized into sectors that then launch the fluid where needed.

Loading fluid canisters into kamikaze units could allow players to apply fluid status effects to enemy units and structures, similar to loading pyratite or blast compound into a unit.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Alpha1641** [comment]
I will probably close the suggestion at the end of the week to clear it from the issue board.

**Comment by Bottinator22** [comment]
Block loaders/unloaders, containers/liquid containers, payload transport blocks?

**Comment by oinkymoo** [comment]
it is possible to access water in every sector. it is possible to access cryofluid using imported tita in any sector. slag is literally only useful for the oil synergy which isn't good enough to be worth relying on, and if you're that desperate import scrap

**Comment by itcannotbe** [comment]
And we're back at re suggesting things that have been already suggested years ago.

**Comment by Alpha1641** [comment]
Actually I'll just do this community a favor and close the suggestion now. Worthless comments.

**Comment by Ander292** [comment]
Anuke won't accept this

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/152191914-0a6eb9b9-721a-4d1a-97f3-98d2bfd53855.png)
This already exists in #dev-previews

**Comment by williams104** [comment]
There is a image in the source code called payload launch pad and you might be able to launch liquid containers in the future.
