### ISSUE TITLE
Buff Reign's bullet peirce against structures

### ISSUE THREAD

**Issue by Intervection** [Anuken/Mindustry-Suggestions#3362]
### Describe what you would like changed, and why.

Reign as a unit is pretty decent, although as a T5, the unit have certain problems in some cases, especially Reign's 10x peirce. Its bullet peirce only works for units, not buildings, so i would like to suggest on changing this to compensate from Reign's highly poor mobility and its low rotation that causes a Quad to singlehandedly beat up the unit in a one on one match, if used wisely.

### Describe the changes you want to propose. Include possible alternatives.

Making Reign's bullet peirce to work against structures is one way to cause reign to become more valuable to be built, especially on an attack based map/sector or pvp maps, although, this could potentially make Reign exceedingly broken due to its 10x pierce. Nerfing the peirce to 4x or 3x will make the unit balanced while not being underwhelming at the same time. Reign is basically a mediocre ranged seige unit, so this will definitely perk the unit up.

**Comment by SMOLKEYS** [comment]
*pierce

**Comment by Intervection** [comment]
Bear with me here, lmao.

**Comment by genNAowl** [comment]
Here's how deep 10 pierce would go: 
![H](https://user-images.githubusercontent.com/68400583/152108643-ea9b7f5d-746a-4b7e-b765-387b3718f88a.jpg)

Here's 10 reigns spawned in front of a thick defense: 
![10pierce](https://user-images.githubusercontent.com/68400583/152108852-8bf2630c-f248-4a2a-8bbd-902544cb4985.gif)

Yeah I think we need nerfed pierce for buildings

**Comment by Intervection** [comment]
> Here's how deep 10 pierce would go: ![H](https://user-images.githubusercontent.com/68400583/152108643-ea9b7f5d-746a-4b7e-b765-387b3718f88a.jpg)
> 
> Here's 10 reigns spawned in front of a thick defense: ![10pierce](https://user-images.githubusercontent.com/68400583/152108852-8bf2630c-f248-4a2a-8bbd-902544cb4985.gif) 10 of any other T5 (including naval) don't even touch this wall, but reigns with unnerfed building pierce can destroy a third of it
> 
> If reign gets building pierce, it will definitely need a value other than 10.

Like i said.
"Nerfing the pierce to 4x or 3x will make the unit balanced while not being underwhelming at the same time."

I know that 10x pierce while being able to pierce structures will end up Reign being an inevitable base annihalator, lmao.

**Comment by itcannotbe** [comment]
Why not just use the already existing building damage modifier?

**Comment by Intervection** [comment]
Increasing it will indeed be ok although, it would be nice for a change to see a unit that damages your base internally.

**Comment by itcannotbe** [comment]
Try corvus.

**Comment by Intervection** [comment]
Well, its laser can be countered though.

**Comment by Intervection** [comment]
Well, bullets it may be countered by walls with menders but it wont if the bullet can penetrate right through the wall itself. Im trying to suggest to make Reign become an anti-wall type unit where trying to stop its attacks using walls is not efficient with minimum effect unless you sacrifice alot of space for a 5+ thick wall linings, unlike some other units like Corvus which can be countered with plast walls.

**Comment by 50275** [comment]
that sounds like foreshadow only meta

**Comment by OnyxFinger** [comment]
ACTUAL 10× building pierce for the reign is waaaayyyy too strong. It has less for buildings, and it is better that way (else reigns would just break everything)
