### ISSUE TITLE
More support units

### ISSUE THREAD

**Issue by Tema0** [Anuken/Mindustry-Suggestions#3363]
### Describe the content or mechanics you are proposing.

Make different units that can produce silicon/glass/surge and etc, other units that can produce power, also units that can produce units and unit-cores, so a core will be movable.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The game with stuff like these will be more dynamic and different. So gameplay will be more interesting, funnier also not just boring zenith speedrun anymore. (btw, it will produce more fun for mlog makers) So it will make more different ways to win or lose

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why make a unit that only a fraction of the player will able to even use without knowledge or a schematic downloa**dead** / taken of some random server?

**Comment by NrkSed** [comment]
>also units that can produce units

 I guess you DON'T know the content already in game or haven't glanced at the wiki either.
 
 >other units that can produce power
 
 Make a poly mine coal and deposit it into a combustion/steam gen using logic.
 
 >Make different units that can produce silicon/glass/surge
 
 what the fuck is glass? I guess you meant metalglass...
 
 Silicon and metalglass are so easy to make, cmon its not that hard. Also it would make such units extremely op
 
 Surge from units??? I dont think i need to say why this is utterly unbalanced garbage
 
 >unit-cores, so a core will be movable.
 
 unit-cores. like... why? why do you need to move your core??
 
 >The game with stuff like these will be more dynamic and different
 
 wow so dynamic that i can make absolutely op units 
 
 >So gameplay will be more interesting, funnier also not just boring zenith speedrun anymore.
 
 You know nothing about the game. And the opposite is true, there wont be the satisfaction of making a surge schem/ surge factory, you will just use surge units like you said
 
>So it will make more different ways to win or lose

none of these units are combat units from what you said, so how tf is it supposed to change how you win/lose

**Comment by EclipseTheOldOne** [comment]
fucking, build a factory, that the thing a fucking factory does
core aren't meant to be moved
like playing capture the flag or hail but you moving your flag/base

bottom text

**Comment by Tema0** [comment]
:с

**Comment by OnyxFinger** [comment]
> The game with stuff like these will be more dynamic and different. So gameplay will be more interesting, funnier also not just boring zenith speedrun anymore. (btw, it will produce more fun for mlog makers) So it will make more different ways to win or lose

How this **improve** the game though ??? What you suggest needs to fill a hole or add a whole new mechanic (good luck with that), none of both have been done ;
                     ⋅ No need or particulari usefulness in situations that may have lacked
                     ⋅ No new mechanic (you just combined two of them together).
I'm not gonna lie though, it could work in a "new" planet that forces you to live in a nomad way, but the game isn't able to "support" this gameplay (it is mainly about settling your factory, so why would you make a whole planet where it can't stay in one spot) and be part of a really big update/expansion.

**Comment by OnyxFinger** [comment]
> >  also units that can produce units
>
> I guess you DON'T know the content already in game or haven't glanced at the wiki either.

Currently, only Omura does that and it's almost like a "filler" ability. Also the suggestion isn't about units making units, but about units having different kinds of factories. If you want to debunk the concept, you should debunk it as a whole.

**Comment by genNAowl** [comment]
> metalglass

**Comment by NrkSed** [comment]
>If you want to debunk the concept, you should debunk it as a whole.

What do you mean? I debunked the whole concept https://github.com/Anuken/Mindustry-Suggestions/issues/3363#issuecomment-1027794006

**Comment by OnyxFinger** [comment]
> What do you mean? I debunked the whole concept

Yes but in separate pieces

**Comment by NrkSed** [comment]
>Yes but in separate pieces

Does it make a difference?

**Comment by GrapheneStar** [comment]
> You know nothing about the game/pvp. 
ok come ranked 1v1

**Comment by EclipseTheOldOne** [comment]
if there's unit factory, then why does factories exist

**Comment by Tema0** [comment]
> You know nothing about the game/pvp.

ok go 1v1 me
