### ISSUE TITLE
Display Schematic Build Time

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#3364]
### Describe the content or mechanics you are proposing.

![Reactors10Sirius](https://user-images.githubusercontent.com/68676339/152189032-c3d58823-ec74-4314-8723-3c19f6108b97.png)
Show the time it takes to build a schematic at 100% build speed here. This one takes 149.68 seconds. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

QOL feature. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
I think it would perhaps be better to put it near the materials and power info, but i support

**Comment by MistahStealYoGril** [comment]
Me 2

**Comment by itcannotbe** [comment]
This us something nice to have, but it's not useful in actual gameplay.
