### ISSUE TITLE
when dirium 

### ISSUE THREAD

**Issue by NrkSed** [Anuken/Mindustry-Suggestions#3365]
### Describe the content or mechanics you are proposing.

dirium

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

dirium 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
when

**Comment by SMOLKEYS** [comment]
dirium

**Comment by oinkymoo** [comment]
I asked about this in #development some time ago, because of the card on the trello that mentions a replacement for dirium, in the "done" column. anuke said it doesn't exist, so I assume it never will

also please take the suggestion box seriously

**Comment by notMEEPoffaith** [comment]
dirium

**Comment by SwitchLikesMlog** [comment]
please close the issue

**Comment by EclipseTheOldOne** [comment]
dirium is like your dad, he's gone

**Comment by end-me-please** [comment]
no dirium then I guess
