### ISSUE TITLE
Color in logic

### ISSUE THREAD

**Issue by Bassem-Const** [Anuken/Mindustry-Suggestions#3366]
### Describe the content or mechanics you are proposing.

A way to get colors from things like teams or resources.
![Preview](https://user-images.githubusercontent.com/72419529/152195061-66e4baa0-3b90-4701-8ef4-972ab12b2659.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

In terms of visual code, it's given above, in terms of written code, it's:

getcolor @copper @resource

Can make logic concise, or act as a replacement to sorter art, dunno much else.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
its only resources and teams that have colors associated with them, but this seems useful

**Comment by Bassem-Const** [comment]
> its only resources and teams that have colors associated with them, but this seems useful

All 256 teams have colors.

I suggested units, but now that I think about it all unit colors are desaturated or uses their type color, assault is red, support is green, and specialist is purple. Probably the same with blocks.
