### ISSUE TITLE
Mass driver's that move functioning blocks should be able to move charged batteries over gaps

### ISSUE THREAD

**Issue by mlgisawsome02** [Anuken/Mindustry-Suggestions#3367]
### Describe the content or mechanics you are proposing.

Batteries should keep their charge when being moved by conveyer or mass driver

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Because mass driver's will soon be able to move fluid tanks I think it should also be able to move charged batteries in order to add a new way to move power over gaps which you can't use wires through

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
(Batteries don't lose their charge when picked up in the private branch, that was pretty much just a bug.)
