### ISSUE TITLE
Make monetization system

### ISSUE THREAD

**Issue by GrapheneStar** [Anuken/Mindustry-Suggestions#3368]
### Describe the content or mechanics you are proposing.

Make this game produce money for developers

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This thing will motivate ppl to think abt improving the game, not just trashtalk on suggestions git

PS: mindustry will die with the anukes inspiration, so money will make it alive a bit longer cuz another ppl, who wants money, will be motivated to make this a bit better or not, but keep alive

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
the game costs money on ios and steam, and will on android as well once v7 drops

**Comment by Bassem-Const** [comment]
> the game costs money on ios and steam, and will on android as well once v7 drops

Android? Well... Anuke said probably not.

**Comment by IxGamerXL** [comment]
> > the game costs money on ios and steam, and will on android as well once v7 drops
> 
> Android? Well... Anuke said probably not.

As shown here:

![20220203_152407.jpg](https://user-images.githubusercontent.com/90928500/152433614-ee058544-714e-41fe-8115-88221a5135b8.jpg)

**Comment by oinkymoo** [comment]
ah my info appears to be outdated

**Comment by EclipseTheOldOne** [comment]
> This thing will motivate ppl to think abt improving the game, not just trashtalk on suggestions git

1. no it won't
2. donating exist

**Comment by genNAowl** [comment]
I won't deny the trash talk on github suggestions but I'm pretty sure this game does produce (however much or little) money for the developers. 

Could you please elaborate on how increasing cost of this game would motivate the community to become less toxic?

**Comment by NrkSed** [comment]
>not just trashtalk on suggestions git

Ironic.
