### ISSUE TITLE
Powered Conveyor Belts

### ISSUE THREAD

**Issue by RoyalFunnyDude** [Anuken/Mindustry-Suggestions#337]
**Describe the content or mechanics you are proposing.**
A conveyor belt that uses power in order to function faster. It would have the speed of a regular titanium belt if it doesn't have power, and when "plugged in" would speed up to maybe like 1.3x faster. It would maybe require one belt to be connected to power and the whole belt would be powered. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would act as a transition between mass drivers and titanium belts, since there isn't really anything in between them except for armored conveyer belts, which isn't really a boost to carrying capacity.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Plastanium conveyors already fill this niche.
