### ISSUE TITLE
Weather effects

### ISSUE THREAD

**Issue by fearstricker** [Anuken/Mindustry-Suggestions#3371]
### Describe the content or mechanics you are proposing.

As far as I can tell there is only one weather effect (rain, inflicts wet on units).
In the trello, there is development on enviromental effects affecting terrain from what I can tell. This is only supposed to affect units/buildings.

Other biomes can also have weather effects that inflicts status effects.

Snow biomes: Blizzard, names rather self explanatory, inflicts freezing on units.

> Can potentially also inflict freezing on blocks like turrets and generators too, and slows down their attack speed, turning speed, and production speed etc. Not sure how well it will fit in the game though.

Fungal areas: Spore storm. Wind picks up and blows the spore all over the place, inflicting spore slowed on units.

General hot areas/new planet(it looks really hot): Heat wave. Inflicts melting on all buildings and units for a period of time. It could be a weaker version of melting like 5 damage a second but its just constant DOT everywhere for an extended amount of time.

In general perhaps: Thunderstorm. Acts just like rain, but occasional lightning can inflict shocked on units. (might be too dangerous and rng due to how shocked and wet deals 14 damage)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New weather effects will either allow the players to take advantage of it, or have to build their base around it.
For example, a player can time a wave to start when there is a blizzard occuring, and use weapons that fire blast compound (cyclone for example) to have higher effective damage against the enemies since they will have the frozen effect.

Heatwave will force the players to have a protection for their whole base due to the dot effect, or at least some form of healing (mega/mend projectors).

Thunderstorm can easily shut down pushes on both sides so if the player is attacking an enemy core they may want to put off the attack temporarily if an thunderstorm is occuring.

Alot of the weather from what i can tell is mainly just visual, so giving them effects could make the gameplay alot more varied.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 50275** [comment]
This sounds like the perfect way to force all schematic designers into accommodating menders and somehow preventing fires from exploding coal-inventory parts.

**Comment by NrkSed** [comment]
> I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

wow, either this is a troll post, or you have played the game for 8 minutes before posting here, most of the things you suggested already exist.

**Comment by fearstricker** [comment]
Apparently all of these (or most) are already in game and I just couldn't find it on the wiki, thats my bad.

**Comment by EclipseTheOldOne** [comment]
fucking

> I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

lies
