### ISSUE TITLE
Liquid routing improvements

### ISSUE THREAD

**Issue by Mcmiko05** [Anuken/Mindustry-Suggestions#3372]
### Describe the content or mechanics you are proposing.

A liquid overflow/underflow gate. It would function like a normal gate but with liquids. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would just make sense. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
It doesn't make sense.

**Comment by EclipseTheOldOne** [comment]
~~fun fact: there's a liquid overflow gate in game file since v5~~

**Comment by oinkymoo** [comment]
while I agree with you, "it would just make sense" is unfortunately not a sufficient reason to add something

**Comment by end-me-please** [comment]
The conduit system is being reworked entirely

**Comment by EclipseTheOldOne** [comment]
read.the.fucking.trello

**Comment by BlueWolf3682** [comment]
The problem: it doesn't make sense.
There is no use for it other than *slightly* more complex liquid schematics.
I doubt it would make much more sense than a liquid sorter.
