### ISSUE TITLE
Epilepsy hazards ON/OFF options

### ISSUE THREAD

**Issue by AzhurniyBaklan** [Anuken/Mindustry-Suggestions#3373]
### Describe the content or mechanics you are proposing.

My suggestion is to add a special field for effects. Let's name it "hazardous" and make it a boolean.
Now we need a main menu setting, let's name it "Turn off epilepsy hazards". When this option is set to true, all effects with "hazardous" boolean set to true would just be disabled.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this new option will improve the game acessibility. Not only in vanilla department, if the content in vanilla is ever going to be hazardous, but also it would help some modifications that utilize flashy effects.
Example of a turret that has such a property:
![effects](https://user-images.githubusercontent.com/70016211/152490320-23d00c94-fd5e-4507-a109-7ba61349b0b1.gif)
:

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AzhurniyBaklan** [comment]
![image](https://user-images.githubusercontent.com/70016211/152491024-e63b0503-164b-411c-ab8a-f2e587f7d90a.png)

**Comment by NrkSed** [comment]
Its a good idea, dont know how hard it would be to implement though

**Comment by itcannotbe** [comment]
Hard to implement in code? No.
Hard to implement in terms if visuals? Kinda.

**Comment by EclipseTheOldOne** [comment]
> Hard to implement in code? No. Hard to implement in terms if visuals? Kinda.

actually, it pretty simple

**Comment by end-me-please** [comment]
Such a setting should also disable logic displays.
