### ISSUE TITLE
Remote construction

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3375]
### Describe the content or mechanics you are proposing.

Add a button, possibly to the build menu, or a hotkey which switches building normally to *requesting* the block to be placed  by BuilderAI units instead - as far as i'm aware, this could be doable by just making it put the request as a destroyed block into the team data (also highlights it for allies in multiplayer) so that BuilderAI units build it
Could be a good idea to make it also affect schematics
This also potentially allows units without a build beam to actually "build", since it could be a good idea to enable building in request mode on those units

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Massive QoL improvement, additionally allowing players in no-build-beam units to avoid situations such as having to abandon a t5 and respawn from a core 200 blocks away to build a single repair point

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LeoSko** [comment]
That would allow players to simply stay at the back of their base and spam blocks/schematics around the map while waiting for poly to build them. Additionally, this adds an obvious security/grief danger as this will make it incredibly easy to simply screw **everything** on the map for the whole team. Not sure how this corresponds with QoL, I thought people hate griefers.

**Comment by genNAowl** [comment]
It could help if one could only plan build requests in the build range (or a range even smaller) of the unit you are controlling. While this does not fully solve the problem, it does guarantee the griefer will be in the vicinity of the area that he is greifing. However, there still has to be a way to link remote build requests to the person who requested them, which (could be?) an issue.

**Comment by SMOLKEYS** [comment]
> That would allow players to simply stay at the back of their base and spam blocks/schematics around the map while waiting for poly to build them. Additionally, this adds an obvious security/grief danger as this will make it incredibly easy to simply screw **everything** on the map for the whole team. Not sure how this corresponds with QoL, I thought people hate griefers.

Could be made a rule setting. Also, ghost blocks are weird in multiplayer.

**Comment by NrkSed** [comment]
> That would allow players to simply stay at the back of their base and spam blocks/schematics around the map while waiting for poly to build them. Additionally, this adds an obvious security/grief danger as this will make it incredibly easy to simply screw **everything** on the map for the whole team. Not sure how this corresponds with QoL, I thought people hate griefers.

I agree, and thats why it should be toggle able in multiplayer. In any case this is a good idea for campaign

**Comment by Ilya246** [comment]
yeah it could just be made toggleable just like logic unit building

**Comment by LeoSko** [comment]
IMO too dangerous to make it available in multiplayer, might be *only local* option for campaign or local play though.

Don't forget current building plans sync over UDP and actually don't reach other clients from serverside as they are kept in local team's plans whereas for suggested functionality it will require TCP sync, which would additionally produce hell of a trafic if someone decides to build pixel art/display art on the other side of the map, say, x15 times. I did mention not only griefers but ___security___. You can't simply validate TCP packet spam in that case.
