### ISSUE TITLE
Cryofluid Liquid Tile for Map Editor

### ISSUE THREAD

**Issue by Salty-Potato133** [Anuken/Mindustry-Suggestions#3376]
### Describe the content or mechanics you are proposing.

A new liquid cryofluid tile that can be placed in the map editor. Similar to all the current forms of liquid tiles, you can place pumps on it and extract cryfofluid. It could look similar to water but maybe more turquoise. 

**Take note**: I am **NOT** asking for this to be put in the campaign, I am asking for a new cryofluid tile to be added to the map editor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Reasons why I think it should be added

1. Unique gameplay possibilities in custom maps
2. all other liquids have a corresponding tile, so why not cryofluid?
3. More block variety in custom maps
4. Better alternative to Liquid sources 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I am not against this idea, but its usage in the map editor will definitely be abused (too much cryo in too many maps, that's a community issue that can't really be balanced). However, I am otherwhise not against this suggestion

**Comment by end-me-please** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

bruh

**Comment by end-me-please** [comment]
it has been in the game for months

**Comment by IxGamerXL** [comment]
Cryofluid tiles have already been added to V7. Also, the abuse of cryofluid tiles depends on the people making the maps.

**Comment by Salty-Potato133** [comment]
Alr

**Comment by SMOLKEYS** [comment]
> I am not against this idea, but its usage in the map editor will definitely be abused (too much cryo in too many maps, that's a community issue that can't really be balanced). However, I am otherwhise not against this suggestion

mfw someone doesnt know about cryo tiles already existing (@OnyxFinger

**Comment by SwitchLikesMlog** [comment]
reminds me of that slag suggestion

**Comment by itcannotbe** [comment]
> reminds me of that slag suggestion

Don't remind us of that.

**Comment by OnyxFinger** [comment]
> mfw someone doesnt know about cryo tiles already existing (@OnyxFinger)

Hello ? It would've been nice if non-V7 players had actual knowledge that something other than tanks for fun and planets for fun was happenning in v7
nobody even said a single word about it. ever.

**Comment by SMOLKEYS** [comment]
> > mfw someone doesnt know about cryo tiles already existing (@OnyxFinger)
> 
> Hello ? It would've been nice if non-V7 players had actual knowledge that something other than tanks for fun and planets for fun was happenning in v7 nobody even said a single word about it. ever.

what

![](https://cdn.discordapp.com/emojis/380919596103761920.png?size=2048)
