### ISSUE TITLE
Sector searching by icon

### ISSUE THREAD

**Issue by fearstricker** [Anuken/Mindustry-Suggestions#3378]
### Describe the content or mechanics you are proposing.

Currently you can search for sectors, and you can also change the icons of the sectors.
The icons can also act like tags in the schematic menu and in the search bar for the sectors, there will be an icons option and it'll show you all of the icons you have and you can click on the icon to filter. (Can be basically the same as the tags system in the schematics menu)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

QOL

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by meatball-sus** [comment]
>  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

So THAT was a goddam lie.
