### ISSUE TITLE
Mindustry community is sick with grief

### ISSUE THREAD

**Issue by Tema0** [Anuken/Mindustry-Suggestions#3380]
### Describe what you would like changed, and why.

Not gonna lie that griefing is one of the biggest diseases of mindustry community. Every new player can easely ruin a game just by removing/messing stuff, killing units, placing cursed logic, lag machines and etc.
So here are solutions:

1. Improve ban system
Its not a secret, that its so easy to evade mindustry ban, u can just change ip by using vpn (vpn blockers dont work, u cant list all vpn servers) and uuid by some modifications.
How to improve? You can get more information abt users system and authenticate users by it.

2. Make permission system
Yes, its sounds weirdly, but what abt to cut map into different zones whith different permissions: 1)Puplic area, everyone can build here 2)Zone for experienced players 3)Personal sectors for each player. So this system will decrease amount of conflicts and make the game less toxic.

3. Make history of banns/complaints or reputation system of each player. Yes it may eat big resources, but this will be a huge help for the community so ppl will be motivated to be a bit better and dont trashtalk/grief, cuz ppl will know who is who.

PS: A few words abt 3.:
Lets do some calculations, so what do i want to store? Store issues that happen with users, so issue id is just integer so - 1 byte, data/time - 4 bytes, servers ip where it happens - 4 bytes and users id who sent this issue 4 bytes.
Therefore eath issue will contain **13 bytes** is it a lot? For example: we have 1000000 users each user got 1000 issues, so we need 13 * 10^9 bytes of information which is less than **13gb**. Is it huge? is it expensive? I dont think so. My 20GB host costs less than 10$ per month.

But where to get that huge amount of money? Make game monetized - ads, payable dlc, skins and etc. (Yes i k that great leader Anuke doesnt want to make money from the game, but if he wants to **keep game alive**, he has to monetize it, cuz we live in capitalism lmao)

### Describe the changes you want to propose. Include possible alternatives.

Not gonna lie, mindustry community is stagnating rn, but these changes will make it grow again.

**Comment by itcannotbe** [comment]
1. Not gonna work, have you seen competitive shooting games? Their ban system is still getting circumvented even additional information gathered from the user's device.

2. Plugins that do this already exist and is being used by servers.

3. Identifiers used by a server, is not the same as identifiers used by a different server.

**Comment by rawsewage38** [comment]
This is the responsibility of the people who run the servers, not the dev's. Plugins already exist on some servers to prevent griefing, and there's really not much you can do about VPN changing, other than force people to log into the server, have player votekicks and report commands.

**Comment by NrkSed** [comment]
>But where to get that huge amount of money? Make game monetized - ads, payable dlc, skins and etc. (Yes i k that great leader Anuke doesnt want to make money from the game, but if he wants to keep game alive, he has to monetize it, cuz we live in capitalism lmao)

You say this like Anuke is the owner of all servers, and in any case, the game already makes profit.

>2)Zone for experienced players

And how to determine which player is experienced?

>Improve ban system
Its not a secret, that its so easy to evade mindustry ban, u can just change ip by using vpn (vpn blockers dont work, u cant list all vpn servers) and uuid by some modifications.
How to improve? You can get more information abt users system and authenticate users by it.

Even AAA games cannot completly keep the game ban-evasion free, and you want Anuke to develop such a system. Ban evasion can be much more than just vpn's.

In any case. plugins exist.

**Comment by buthed010203** [comment]
Ah yes, linking the wrong suggestion as per usual... Seriously how do i manage to do this every time?

**Comment by SMOLKEYS** [comment]
> ads, payable dlc, skins

see below:

> ads

Anuke is fundementally against any ads.

> payable dlc

Practically useless, mods can just add payable dlc content for free.

> skins

- No one is gonna pay for a unit texture that no one will probably even give a shit about.
- Increases game filesize.

**Comment by Bassem-Const** [comment]
> > ads, payable dlc, skins
> 
> see below:
> 
> > ads
> 
> Anuke is fundementally against any ads.
> 
> > payable dlc
> 
> Practically useless, mods can just add payable dlc content for free.
> 
> > skins
> 
> * No one is gonna pay for a unit texture that no one will probably even give a shit about.
> * Increases game filesize.

Everything here is possible with mods except for ads.

**Comment by AMindustryPlayer** [comment]
>ads
Anuke won't advertise but except for others who think this game is good
because:
>I am fundamentally against any ads.
by Anuke

**Comment by buthed010203** [comment]
Thank you for necroposting things that have already been said and preventing this suggestion from being closed for another month 👍
