### ISSUE TITLE
Sandblaster Turret (Impel) for the V7 Desert Planet

### ISSUE THREAD

**Issue by rawsewage38** [Anuken/Mindustry-Suggestions#3381]
### Describe the content or mechanics you are proposing.

A 2x2 sandblaster gun for the new desert planet in V7.
Here's the core database entry for it:

### Impel

**Purpose:** Fires a constant, powerful stream of sand at ground units, pushing them back. Automatically shoots at fires to extinguish them, when supplied with sand. Can use powdered metal instead of sand for greater knockback. Prioritizes more powerful units.

**General**
Health: 325
Size: 2x2
Build Time: 6.2 seconds
Build Cost: 80 lead, 65 graphite, 15 titanium

**Liquids**
Liquid Capacity: 20 Liquid Units

**Function**
Range: 22.5 Blocks
Inaccuracy: 5.25 degrees
Shots Per Second: 34
Targets Air: No
Targets Ground: Yes

_Ammo:_
Sand: 0.1 damage, 1.4 knockback
Copper: 0.3 damage, 1.5 knockback, 0.9x fire rate
Titanium: 0.5 damage, 1.9 knockback, 0.85x fire rate

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The _Impel_ gun will provide a great new support turret to the defense line, pushing back ground enemies, and targeting the enemy with the most HP first. This will be a useful turret mid to early late game. It also can be used as fire suppresion in areas without water, making it useful technology for a desert planet.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RFAC-Productions** [comment]
> Can use powdered metal instead of sand for greater knockback. Prioritizes more powerful units.
While I do like the idea of a sandblaster, I mean every other material except spores can be used as ammo, what could the powdered metal be used for other than ammo? Scrap basically makes everything, Titanium can be used to build stuff and make materials such as cryofluid or plast, Blast can be used to fuel impact reactors, Spores can be made into oil and blast, etc. But maybe I'm just overanalyzing and the Sandblaster has a built-in grinder.

>This will be a useful turret mid to early late game. It also can be used as fire suppresion in areas without water
I was about to say water extractors but, electricity is limited. I'd say this is a good way to save electricity

Overall, good idea!

**Comment by RFAC-Productions** [comment]
Surprised no one else replied yet

**Comment by rawsewage38** [comment]
> But maybe I'm just overanalyzing and the Sandblaster has a built-in grinder.
The Cryofluid Mixer says that it "Mixes water and fine titanium powder to produce cryofluid.", and you put whole titanium chunks in there, so the mixer also has its own built in grinder, which is why I didn't make a special building for it.

**Comment by MistahStealYoGril** [comment]
Well that sucks. It is a great idea.

**Comment by BlueWolf3682** [comment]
I like it - note that water extractors **will not** be available on erekir, meaning any fire go-
\*distant nuclear exposion sounds*
