### ISSUE TITLE
Building priority

### ISSUE THREAD

**Issue by fearstricker** [Anuken/Mindustry-Suggestions#3382]
### Describe the content or mechanics you are proposing.

While building, ctrl click on a building to start building on it instead of whatever you are currently doing.
By extension, you can ctrl right click on a building to start deconstructing instead.

After you finished the action on the clicked building, the old priority system takes over until the player decides to prioritize another building.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This makes it easier to build defenses/structures as you dont have to worry what you placed first (as far as i can tell thats how the current priority system works).

Won't work well with tracks due to the sheer quantity of them but other then that it should be a pretty good qol.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You forgot how would this not work with multiplayer.

**Comment by RealYeet** [comment]
Launch pads don’t work in multiplayer, yet they are still in the game. I support this. There is no specific reason why something should not be added because it does not work in multiplayer.

**Comment by genNAowl** [comment]
I'm pretty sure launch pads in multiplayer don't cause desync while this does.
