### ISSUE TITLE
v7 

### ISSUE THREAD

**Issue by BBrspin** [Anuken/Mindustry-Suggestions#3383]
### Describe what you would like changed, and why.

That sound of buildingn v7 , is make my ears broken lol
also can add are think of units in passive if u not in sector also calc a forsce 

### Describe the changes you want to propose. Include possible alternatives.

just add new sound but not are discomfortable

**Comment by Arcanilius** [comment]
They are kinda annoying, but i can live with it, just turn the sounds off
