### ISSUE TITLE
Copper new content

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3384]
### Describe what you would like changed, and why.

what would it be like if they cost copper instead of silicon for T1s?

### Describe the changes you want to propose. Include possible alternatives.

Imagine all start game whit this setting

**Comment by oinkymoo** [comment]
you only explained what you wanted changed, not why, and you not only completely ignored the second prompt and made up a new word while you were at it.

**Comment by end-me-please** [comment]
Copper is a material for building, not units. it has been that way since v5 (probably earlier too)

**Comment by Ymabert** [comment]
@oinkymoo wow you really argued well, I wrote this suggestion to see what came out of it if someone started a discussion, read the second sentence well (then what word did I invent?), but apparently it is more interesting to discredit a possible one right away good idea...
@end-me-please you said something that in my opinion is right, in fact it is the only problem that this advice has, now I will explain to you what I would like precisely by changing the cost of generating T1 from Silicon to Copper (then the silicon will be used only for reconstruction, I'm asking to change the cards on the table), since the construction and spawn system of the units has changed, silicon does not have to be the base material for the CONSTRUCTION, but it could only be used for the REBUILD (upgrade), therefore this will result in having the drones immediately to pick up the basic materials (copper and lead), while the core is automatically filled with these materials, the player begins to produce Grafhite, which will then be used to extract the titanium, so far everything is quietly given that the primary resources will not be a problem, then the player will use the silicon only to upgrade the drills by replacing them with others in the extraction points, so we will evolve a little faster  mind and wanting even with some troops to defend everything in case you are attacked right at the beginning of the game, we are talking about T1, but at least we are not defenseless and then even the attacker will use T1 so the useless attacks that every now and then I see all he start of some games will be excluded regardless (I say they are useless for two reasons 1-what is the taste of the whole game griefing?  even if you get the better of your opponents by winning immediately ... it happened, mine was a team of people who knew nothing about the game and therefore we lost immediately, 2-many times I see people who keep attacking and wasting resources in vain to attack and turn the game into a kind of sweaty game where the player who creates the most defenses wins, even though I've never really finished a game like this, they're not playable, so they're not fun).  The game can be developed also going beyond the creation of the T5 to be clear, since the basic evolution speed will increase and then I hope for an improvement in the command strategies of the units, for example having a command center that is set with the appropriate settings an area (circle or rectangle, or semicircle or half rectangle) in which the troops turn at random / stand still (it depends on what you want, it already is) or look at the border (this idea I don't even know if it can be useful to improve the command center, however, more strategies are needed in the control of the troops, but without necessarily having to use logic, otherwise what is the command center for?).

**Comment by Ymabert** [comment]
note that nobody has real ideas, they read and dislike, nice people here in the area """"""""suggestions""""""""all very collaborative.

**Comment by itcannotbe** [comment]
What the fuck did I just can't read?

Learn to use **PARAGRAPHS**

**Comment by oinkymoo** [comment]
> what word did I invent?

your original post said "Imagine all game start whit this impostation", but an hour ago you changed "impostation", the word you have already realized was a mistake, to "setting"

**Comment by oinkymoo** [comment]
> I wrote this suggestion to see what came out of it if someone started a discussion

you didn't give us enough to discuss. you posted a possible change, but you gave us no other points on which to critique the suggestion.

**Comment by Ymabert** [comment]
@itcannotbe @oinkymoo I read better and later I understood the mistake, because in my language, Italian, it is not like English, so I was wrong to write ... anyway yes ... continue to answer by saying that my way of writing is wrong, give some real help to Anuke (and we are in the suggestion area, which I find if I ask something in some chat on the discord server?) rather write 2/3 lines where you explain to me in a few words why it would not be good to put this suggestion in the game, but you haven't said anything at all, I don't even know if it's not a good idea for you, but the way you behave you don't seem very happy with what I suggested.

**Comment by Ymabert** [comment]
you didn't give us enough to discuss. you posted a possible "change, but you gave us no other points on which to critique the suggestion."
Ah no?

**Comment by Ymabert** [comment]
@itcannotbe tell me how what the fuck ... I would like to learn better, I know, but tell me how without criticizing unnecessarily.
