### ISSUE TITLE
if ARMOR is a good idea then I recommend this.

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3385]
### Describe the content or mechanics you are proposing.

I don't know if additional armor / armor for robots is a good idea, but I believe that if a block capable of fusing armor is not added to the units it is because no one thinks about how this can be done, in the past I have proposed a new material (steel, but then why not create the robots directly with the latter? or why not create the armor with silicon?), but thinking about it would not have been a solution, so it came to mind that a rebuilding block that works with Slag and Criofluid to cool would have been a good solution, so the troops enter the block and leave with armor, if obviously everything is powered properly, then each level of unit has its own consumption of Armor slag.  I thought of this block more as a kind of room where units just have to go in between, even more than one at a time, and come out with armor (generated with the usual builder beam), if there are too many units and you fail. to enhance them all, due to the resources that run out or due to the fact that being too many robots to pass the rays they are unable to build armor on everyone (because it will take a few seconds to build armor on the units, obviously T1 / T2 is a matter of 3/6 seconds maximum, per ray, otherwise even less if there are more rays to build), the robots will simply pass without having an armor on them.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New block = new Evolution and more completeness for Mindustry (best game :D).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Armor is already in the game as a damage reduction mechanic.

Also how does this suggestion differ from actually healing units through a repair point/turret?

**Comment by SwitchLikesMlog** [comment]
> Armor is already in the game as a damage reduction mechanic.

i think they meant that armor adds a bonus to the armor stat

> Also how does this suggestion differ from actually healing units through a repair point/turret?

well you cant always build repair points in enemy territory

**Comment by itcannotbe** [comment]
> > Armor is already in the game as a damage reduction mechanic.
> 
> i think they meant that armor building adds a bonus to the armor stat

How would even a bonus to the armor stat even work?

> > Also how does this suggestion differ from actually healing units through a repair point/turret?
> 
> well you cant always build repair points in enemy territory

You did read the suggestion's mechanic right?

**Comment by end-me-please** [comment]
Adding additional armour to units sort of exists, in a slightly obscure way. Units with the shield Regen field ability (pulsar, bryde) are ironically not really able to regenerate force field units, but they do add a shield to units that otherwise wouldn’t have one. (similar to the shield some crux units have on attack maps)
