### ISSUE TITLE
Different bullets for units

### ISSUE THREAD

**Issue by Arcanilius** [Anuken/Mindustry-Suggestions#3386]
### Describe the content or mechanics you are proposing.

Turrets have more ammo types,If units need ammo, why we can't give them different types of ammo.
Silicone for homing
Pyratite for flame 
...
This should be an option, for thoose who doesn't want it

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be fun, fun is good, just imagine an army of daggers with explosive bullets l, and it could be good for pvp aspect, somebody wants to have an army of flaming units, but somebody else wants more precision in he's units shots.
This doesn't apply for electric units(nova,pulsar...)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
different units have vastly different attacks (fortress artillery, mace flame, atrax lava, quasar lasers, etc.) I don't think this is necessary

**Comment by Ymabert** [comment]
👍👍👍👍🕶️🤏

**Comment by Arcanilius** [comment]
> different units have vastly different attacks (fortress artillery, mace flame, atrax lava, quasar lasers, etc.) I don't think this is necessary
Yeah but, mace îs short range, fortress expensive for early game, atrax is atrax actually don't think there are any materials that give melting,quasar is electricity based like i said, no need to changed that.
