### ISSUE TITLE
What if something or someone offende you?

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#3387]
### Describe what you would like changed, and why.

Read the GitHub Community Guidelines
it makes you laugh as no one respects the ideas of others, no one here knows what respect or education is from what I could understand ... those who answer are almost all arrogant, as if they were superior🤡

### Describe the changes you want to propose. Include possible alternatives.

I'm sorry for Anuke who has people so sad to give him advice, or rather to select advisors and suggestions, because in reality these people do nothing, criticize and criticize, as if there was nothing better to do in life.  I gave all my ideas, good and bad, I never heard anyone say "good idea", even when many approved, there were the usual failures who still criticized what I suggested, despite the fact that some people approved fully, to make themselves heard were always and only the usual ones, who never discuss or never what is suggested, but criticize, in short they never manage to be helpful, not to mention those who disapproved of my ideas and kept silent , that made me nervous.  If I give so many suggestions it is not because I want them to be taken 100% seriously but I just want to give some ideas on some paths that Anuke can take, so my idea can arouse other ideas, so I wanted to try to suggest ideas too. more foolish ... to help as much as possible, but right away I saw that at least 5 idiots were against me in any suggestion, so I got banned from the server because I know that at least 10% of people are like that here ( I'm talking about the people in chat), all 0 ideas but with 1000 (useless) criticisms.  The most annoying thing is the fact that no one ever says a good idea to those who have really good ideas, practically those 3 comments of approval that are there I wrote them, then obviously the ideas to be discarded for valid reasons (sometimes I happened to wrong suggestion, but many times I was able to clarify almost immediately, obviously because I was trying to understand the problem and not because someone was telling me where the problem was in the suggestion) it was fair to say that they were wrong ideas, but at least fuck you could explain the reason no?  I am disappointed by the community, or at least by a small part, which is still too big ... otherwise Anuke is doing a good job I hope I have given some sources to take inspiration from by suggesting.

**Comment by markozajc** [comment]
what

**Comment by DeltaNedas** [comment]
among us
closed this
reopened this
closed this
reopened this
closed this
reopened this

**Comment by Anuken** [comment]
Blocked for close/reopen spam.
