### ISSUE TITLE
Ability to autoload latest autosave on dedicated servers

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3389]
### Describe the content or mechanics you are proposing.

Make a config option for dedicated servers which automatically loads the latest autosave on startup, because you can't really do that with startCommands (without knowing js)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Could be useful in many cases

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
gigafort3 moment
