### ISSUE TITLE
Liquid Faucet

### ISSUE THREAD

**Issue by williams104** [Anuken/Mindustry-Suggestions#3390]
### Describe the content or mechanics you are proposing.

A 1x1 block that will let a set amount of water through.
(Not only by logic, but can be)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will stop certain areas from eating up all your water.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
there are already liquid over/underflow gates in development versions

**Comment by SwitchLikesMlog** [comment]
what

**Comment by williams104** [comment]
No
it was Accidental

**Comment by RFAC-Productions** [comment]
Oeuf
