### ISSUE TITLE
Translations for commands (in processors)

### ISSUE THREAD

**Issue by Cieteu** [Anuken/Mindustry-Suggestions#3391]
### Describe what you would like changed, and why.

I'd like to translate commands in processors.

### Describe the changes you want to propose. Include possible alternatives.

Translations for commands in processors (english to polish):
Read-Czytaj,
Write-Napisz,
Draw-Narysuj,
Print-Wydrukuj,
Draw Flush-?,
Print Flush-?,
Get Link-Dostań linka/odnośnik,
Control-Kontrola,
Radar-Radar,
Sensor-Sensor,
Set-Ustaw,
Operation-Operacja,
End-Koniec,
Jump-skok,
Unit Bind-weź jednostkę,
Unit control-Kontrola nad jednostką,
Unit radar-Radar jednostki,
Unit locate- zlokalizuj jednostkę.

**Comment by Phinner** [comment]
@Cieteu Translations aren't handled here, you better go to the [mindustry repo](https://github.com/Anuken/Mindustry), read [TRANSLATING.md](https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md) and then create a pull request with your translations.
