### ISSUE TITLE
feedback: mouse and keyboard controls for mobile(bug?)

### ISSUE THREAD

**Issue by IM-ikeamans** [Anuken/Mindustry-Suggestions#3393]
### Describe what you would like changed, and why.

i would like the mouse on mobile to chow you the statistics of items when you hover over them, give you a preview of how schematics will be placed based on where your cursor is, and all the other things it does normally on pc that it doesent do on mobile. its really really hard to use schematics when your guestimating where theyll be when you click.(this might even be a bug)

### Describe the changes you want to propose. Include possible alternatives.

either fix the controls for mouse and keyboard on mobile or dont let people use them in the first place, or pull it from the mobile versions until you get a chance to fix it if your too bust on v7

**Comment by Jammo2000** [comment]
Sad, chromebook mindustry will be devastated

**Comment by TheGamer1002** [comment]
This is probably totally unviable for iOS, but Android can handle it.
