### ISSUE TITLE
Transportation units

### ISSUE THREAD

**Issue by Oceardelta** [Anuken/Mindustry-Suggestions#3394]
### Describe the content or mechanics you are proposing.

I would like to propose a new type of unit to add to all of the other new implementations. I feel that a unit that can not only carry a large amount of resources but carry multiple types could and would be extremely useful.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that this unit could greatly increase the amount of creativity in designs for things such as unit production and defences, aswell as making other production using units for its resources much larger and satisfying. It can hold a larger amount and hold more types of resources the higher teir. It doesn't even have to be able to shoot. I also think it should have the ability to pick up units like the oct can but more at a teir 5 level.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
i think this will be too OP? otherwise i like this idea, will surely make mlog easier a bit

**Comment by oinkymoo** [comment]
just use a mega. can carry 300 of everything using payloads. if that's not enough, quad can carry 1000, and oct can fit 3000, with enough spare space for a single t1 air or ground unit and nothing larger
