### ISSUE TITLE
PowerTurrets with 0 powerConsumption to work without needing to be connected to a power source

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#3395]
### Describe what you would like changed, and why.

Power turret types with a powerUse of 0 currently need to be connected to a positive generation network to work despite not using power, not only does it not make sense but it also gets very buggy when the power use of the network exceeds generation

### Describe the changes you want to propose. Include possible alternatives.

Simple, detect 0 powerUse turrets as either no consumption turrets, make them actually work outside networks, or make them generate an absolutely miniscule amount to function. Mainly for modding purposes.

**Comment by itcannotbe** [comment]
Power Turrets have been rework for v7, wait for merge and check again.

**Comment by Anuken** [comment]
To elaborate on the above, `powerUse` as a field has been deprecated and will (eventually) be removed entirely - you can just `consume.power` instead, or not do it at all.

**Comment by Ribbons0121R121** [comment]
thanks, will try
