### ISSUE TITLE
Dynamic Music

### ISSUE THREAD

**Issue by williams104** [Anuken/Mindustry-Suggestions#3396]
### Describe the content or mechanics you are proposing.

Dynamic music would help the variety of music.

In the songs, there could be two layers changed/added

The intensity layer would change based on the power of all units in the map. Higher power units could have different layers and more priority to play their layers.

Say a bunch of daggers would play at a different intensity than a Toxipod.
The Toxipod would have a different song(or instrument) than a Corvus or a Reign;
Or there could be different instruments for different trees like if you were attacked by a bunch of novas, there would be a certain instrument playing for them, and it plays at more intensity for some Quasars.

The other layer would be dependent on the type of map in happening, Like tar fields or overgrowth.
A layer would be the same for Fungal pass and overgrowth, but not for tar fields.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would help the music problem.

I know that something similar is in the Trello, and it would solve that problem.

Also, I was playing Mindustry and some intense music started playing when there were no enemies and I was just working on my factory. I feel like that music was out of place.

Adding more music wouldn't help the problem, but adding layers to the music would

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

did you?

**Comment by williams104** [comment]
Yeah read the entire comment.

**Comment by SwitchLikesMlog** [comment]
okay fair, that suggestion is kinda nice
but i doubt if Anuke is going to add that into the game at some point

the "Better music timing" in the trello doesnt really suggest making new songs for a specifc unit, its more like getting rid of stuff like your situation with the intense music while building factories

**Comment by williams104** [comment]
That would help.
What I think is that with layers of music, it could lead to only having to make one layer for an area and having WAY more variety per map. Think about ground zero. There are many sectors around it. One of them has the difficulty of high and might only play higher intensity layer, and would have the same area layer ground zero.
Anuken would only have to add a layer for the area if he wanted to add more sectors.

**Comment by williams104** [comment]
Intense Music while slowly building a command center

**Comment by numer99** [comment]
like how in portal 2 there are different song for test chambers, and part of the music will get louder if you go faster, and another part of the music will get louder if you are closer to something
