### ISSUE TITLE
Hide information until it gets unlocked

### ISSUE THREAD

**Issue by SaltyBeggar** [Anuken/Mindustry-Suggestions#3398]
### Describe the content or mechanics you are proposing.

Hide information of things you haven't unlocked yet, for example hiding fluids/materials you haven't unlocked yet from factories'/turrets' descriptions or hiding information of ammo types you haven't tested yet.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

That wouldn't really change much gameplay-wise, but would probably be nice to get new players excited to keep unlocking new materials and also encourage the use of new ammo types.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
> hiding fluids/materials you haven't unlocked yet from factories' ... descriptions

this is pointless. factories are often locked behind the very materials required to use them, and when they aren't you often have to go out of your way to avoid unlocking those items

> hiding information of ammo types you haven't tested yet.

there are 2 interpretations of this: untested ammo is not shown at all, or untested ammo just has ??? for stats. in the former scenario, this would be incredibly tedious. you have to test every item and liquid as ammo for each turret you unlock, and you have to test every turret with each new item and liquid you unlock to see its stats. even if its just ??? for untested items, you still have to go through the tedium of putting in 1 of each item into each new turret as you unlock them

**Comment by SaltyBeggar** [comment]
> there are 2 interpretations of this: untested ammo is not shown at all, or untested ammo just has ??? for stats. in the former scenario, this would be incredibly tedious. you have to test every item and liquid as ammo for each turret you unlock, and you have to test every turret with each new item and liquid you unlock to see its stats. even if its just ??? for untested items, you still have to go through the tedium of putting in 1 of each item into each new turret as you unlock them

oh that makes sense

> Even in sandbox? If so..... bruh

no, there wouldn't be reason to put that on sandbox
