### ISSUE TITLE
Command Center's config in logic

### ISSUE THREAD

**Issue by SwitchLikesMlog** [Anuken/Mindustry-Suggestions#3399]
### Describe what you would like changed, and why.

As of now, the Command Center's config is uncontrollable with processors, as there is no `@rally` or `@attack` or `@idle`.

However, you can sensor the Command Center's config, save it to a variable, and then use that variable to control the Command Center's config.

That method can be used to do something like this:

https://user-images.githubusercontent.com/95284426/153744458-a8dfc3fe-64a8-412e-8fd6-232092c055d4.mp4

The saved config is "enum", according to the `var` tab.

### Describe the changes you want to propose. Include possible alternatives.

Two things:
1- Command Center should be controllable by numbers (0 for idle, 1 for rally, 2 for attack), as simple as that.
2- If it felt too OP (example in that video above), perhaps add a cooldown for controlling the Command Center, pretty much like `ucontrol itemTake`'s and `itemDrop`'s cooldown.

**Comment by LeoSko** [comment]
It was said numerous times, use search.

For short, use `@commandRally`, `@commandAttack`, `@commandIdle`

**Comment by SwitchLikesMlog** [comment]
Oh...
Well, another useless suggestion in the sea of Github.
Sorry for the mess.

**Comment by SwitchLikesMlog** [comment]
Though, perhaps we still need a cooldown for it, right?
