### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Summet-V** [Anuken/Mindustry-Suggestions#34]
**Describe the content or mechanics you are proposing.**
When the game window is minimized, stop playing music

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
For example, when you make mods and don’t want to close the game, the music continues to play, sometimes it bothers

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Katsute** [comment]
Maybe just mute music when developing? Most games today don't stop the audio engine when minimized.

**Comment by MEEPofFaith** [comment]
*Just go into the settings, it's not that difficult*

**Comment by Summet-V** [comment]
Ok
