### ISSUE TITLE
[mods] reading a mod's files

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#340]
**Describe the content or mechanics you are proposing.**

A class for reading files in a mod's zip/folder.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

JS mods currently can't read local files into a string. I think this is harmless and would help for shaders, config files, docs, etc.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Implemented as `readString(path)` / `readBytes(path)`, although some important conditions apply (will be documented later).
