### ISSUE TITLE
Configurable data location

### ISSUE THREAD

**Issue by Fabizocker456** [Anuken/Mindustry-Suggestions#3400]
### Describe the content or mechanics you are proposing.

It would be great to allow the player to run mindustry with configurable save location, e.g. run `java -jar mindustry.jar --save %appdata%\mindustry2`  to prevent `%appdata%\mindustry` from being used. If possible, the current session's save location should also be configurable in the gui, possibly having to reload data
Also, maybe things like uuid can either be specified directly (`--uuid "AAAAAAAAAAA="`) or loaded from a specified settings file (`--settings %appdata%\mindustry\settings.bin`)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature would not only allow the player to easily switch between stable and bleeding edge or unstable alpha, it would also greatly simplify having e.g. a modded and a vanilla or a default and a challenge save file. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What good is it even to even make it easier to change the UUID?

**Comment by Fabizocker456** [comment]
it does add an option. but not necessarily an easier one. If a player is smort enough to start up the game with java cli arguments, he is certainly smart enough to do 
![image](https://user-images.githubusercontent.com/79974417/154126625-4ecb8397-4fe5-479b-9118-aceeadbe9102.png)
