### ISSUE TITLE
TractorBeamTurret base region texture

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#3401]
### Describe what you would like changed, and why.

The code that loads the tractor beam turret type, current set to block-@size

### Describe the changes you want to propose. Include possible alternatives.

change block-@size to fallback and instead look for @-base like the rest of the turrets. honestly no idea why its like this to begin with

**Comment by oinkymoo** [comment]
make a PR

**Comment by Ribbons0121R121** [comment]
o right

**Comment by itcannotbe** [comment]
Close?

https://github.com/Anuken/Mindustry/pull/6577

**Comment by Ribbons0121R121** [comment]
i made it after i made this because i didnt know if randos could make pull requests but yes close
