### ISSUE TITLE
New Energy Field "Turret"

### ISSUE THREAD

**Issue by Salty-Potato133** [Anuken/Mindustry-Suggestions#3402]
### Describe the content or mechanics you are proposing.

A new 3x3 similar to the T4 naval support's energy field.

My concept:
A low damage turret designed for damaging many enemies. Similar to the T4 naval support energy field, it shocks a large number of enemies on a hit tick.  

Possible description: "Shocks a large number of enemies that enter its electric field."

- Its damage could be very low and inflict "shocked" onto them. It should have a cap on how many units it can shock at once.
- Range is up to devs, I was thinking of it having decent range

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Why it should be added:

- Add a new kind of splash damage, different from any other existing turret. Other splash-damage turrets are good when enemies are close or in a line, while this is good against a large group of enemies anywhere in its range.
- Add a new power-only splash damage weapon that is effective against large groups of both air and ground units. 
- Add a new 3x3 power weapon (there are not currently any that are 3x3)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Maybe make it air only, so it is a flare and horizon clean up turret.

**Comment by Salty-Potato133** [comment]
Nah it can be both air and ground
