### ISSUE TITLE
sync games

### ISSUE THREAD

**Issue by NullRien** [Anuken/Mindustry-Suggestions#3403]
### Describe the content or mechanics you are proposing.

A feature or server you can connect to to sync your game with computer, phone, laptop, etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would allow people to sync games without exporting their game file onto another device when they want to use that device and save more time.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
when the readme is SUS

**Comment by Phinner** [comment]
Sry mate, as written in the README, it won't happen anytime soon, use an external tool.

**Comment by Phinner** [comment]
Personally, I would go the git way since its possible to run `git` with termux...

**Comment by itcannotbe** [comment]
> i know steam does that but i mean between phone and computer too

I know you can read, why can't you.

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest

######These have been proposed many times already, and I won't be adding them.

- Built-in cloud sync

**Comment by meatball-sus** [comment]
Lol you can just put your campaign data on to google drive, dropbox, etc
