### ISSUE TITLE
Logic thingies

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry-Suggestions#3404]
### Describe the content or mechanics you are proposing.

Logic command to save the Draw buffer into a texture variable. I expect it to pose a problem with memory cells so you can just forbid them from being stored into memory cells, or even have special memory banks

Logic block "selector", with the same UI context menu as a sorter, except you can replace (with logic) the choices by textures already available by using DrawImage
It would look more or less like this
![image](https://user-images.githubusercontent.com/45213805/154569491-41f48fc4-73c1-433a-a6a1-5773bd446df6.png)
Also being able to configure how many choices there are could be cool but thats a bonus

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Save the Draw buffer as a variable -> saves a LOT of computing performance if you have to draw something multiple times, like an UI for power graphs, minigames, etc

Logic Selector -> more gameplay and logic options
ive seen many people use sorters as selectors for their logic, would be wayyy easier to understand what each item does in their logic

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
im pretty sure memory cells are already restricted to numbers

**Comment by end-me-please** [comment]
logic must not allocate *any* garbage. however this wouldn’t actually use that much memory

**Comment by oinkymoo** [comment]
I briefly considered suggesting that the print buffer be storable as well, but then I realized that it would allow for string concatenation which is no.

**Comment by end-me-please** [comment]
Alternatively, allow using an existing display as a source for draw Image? that wouldn’t require adding a new block for a niche use case.

Smaller displays (1x1 or 2x2) could be used to store textures.

Allowing processors to disable displays in order to hide their contents could also be a nice touch.
