### ISSUE TITLE
More map decor

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#3406]
### Describe the content or mechanics you are proposing.

More map decor to give maps a little bit more life:

Explosion marks
- Permanent version of the unit explosion marks for the map editor

Inactive/Destroyed units
- A boulder-like decoration of deactivated/crashed units in the derelict team.

Stuff like this are just initial concepts, but can be expanded on into more things.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Gives maps more oportunity to be more lively and decorated without having to make something more abstract.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 64-Tesseract** [comment]
I think permanent marks would get laggy pretty quick, imagine thousands of marks having to render. They're annoying enough for me anyway, they hide ores & other stuff.
Crashed units could be ok but would obstruct visibility/pathfinding. Maybe scrap units, like scrap walls & old buildings, could be part of the map and not spawn every time a unit dies

**Comment by AtobaAzul** [comment]
> I think permanent marks would get laggy pretty quick, imagine thousands of marks having to render. They're annoying enough for me anyway, they hide ores & other stuff. 
Like I said, it's _map editor exclusive_- Normal marks would behave as normal, and it's too annoying, could just make it be able to be removed.
