### ISSUE TITLE
Priority system for research ressource cost

### ISSUE THREAD

**Issue by AntimatterHD** [Anuken/Mindustry-Suggestions#3408]
### Describe the content or mechanics you are proposing.

Adding priorities to cores/sectors to priorize the removal of research ressources in the campaign

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

At the moment, the research cost is divided equally over all captured sectors.
This makes refilling of these resources more tedious, the more sectors you have captured, as you have to point your launchpads to every single sector to refill the cores.
With a priority system, the whole process of researching end game content would be less annoying

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 64-Tesseract** [comment]
Could be useful for early-game, but once you ramp up your production I don't think it would be...

How would you assign priority/resource allocation? Slider maybe? Then you'd need to go into every single sector and set it to what you want which would be overly tedious to be useful.
Making sector groups would be way too complicated for something you don't do all that often.
Maybe it could allocate more resources if a sector has finished all the waves and isn't vulnerable, which should be easy to code...
