### ISSUE TITLE
Ice should increase land unit movement speed

### ISSUE THREAD

**Issue by SuperficialIntelligence** [Anuken/Mindustry-Suggestions#341]
**Describe the content or mechanics you are proposing.**
Land units moving on ice will have increased movement speed. Or maybe make units movement accelerate whilst on ice.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This can make for some interesting maps where the units slip around or move faster adding a unique challenge into maps that are dominated by ice. Also it make's sense for ice to be slippery.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
That's actually not how it works.

Ice reduces friction not increases movement speed.

As you see, they have feet.

Probably would make more sense land units have a harder time to change direction/speed.

**Comment by Anuken** [comment]
This doesn't make any sense.

**Comment by SuperficialIntelligence** [comment]
> That's actually not how it works.
> 
> Ice reduces friction not increases movement speed.
> 
> As you see, they have feet.
> 
> Probably would make more sense land units have a harder time to change direction/speed.

Yeah, that's what I actually meant though I can't seem to find the words to phrase it.
