### ISSUE TITLE
Payload router manipulation via logic

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#3411]
### Describe the content or mechanics you are proposing.

I would like to request the feature mentioned [here](https://github.com/Anuken/Mindustry-Suggestions/issues/1123#issuecomment-724366468) - Being able to turn routers with logic.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

My goal is to build a small core unit-factory in which specific upgrades can be disabled. The only way to do this is by forcing the router into a specific direction, which doesn't seem to be possible yet without the use of other units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet. (Forgive me if this already exists, I could't figure out how)
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by UltraBlackLinux** [comment]
well shit. It exists, but it's scuffed to understand. Seems like it was `control` after all

**Comment by SMOLKEYS** [comment]
> well shit. It exists, but it's scuffed to understand. Seems like it was `control` after all

+ logic is potentially gonna get removed from campaign

**Comment by UltraBlackLinux** [comment]
Oh noo. 

Are you trying to troll me?
