### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by Dei123mar** [Anuken/Mindustry-Suggestions#3412]
### Describe the content or mechanics you are proposing.

Eu sugiro adicionar a tradução na configuração dos processadores, em vários idiomas.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Ajudará pessoas que não falam inglês a avançar mas evolução do jogo

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
Translation (according to Google):

> I suggest adding the translation in the processors configuration, in multiple languages.


> It will help people who don't speak English to advance the game's evolution

**Comment by SwitchLikesMlog** [comment]
Lembro-me de Anuke dizendo que isso não é possível.

(I recall Anuke saying that's not possible.)
