### ISSUE TITLE
command center display change, chat improvement, mod browser improvement

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#3413]
### Describe the content or mechanics you are proposing.

many different ideas collected in 2 months of playing on beta version 7
minor visual improvements, rebalance of some blocks, global changes in mechanics

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

hi anuke, i've been playing minddustry for quite some time, and i'm playing on beta v7
I have been creating this list of what the game is missing for a couple of months, my English skills are bad, the text is translated using google translator, if you have any questions, write to me on the ZIS # 4100 discord

small ideas:

A hologram appears above the command center. on top of all unit layers

add the ability to change the design of the darkness around the map to “texture block space”

add the ability to save the server address from the list of public servers

make it so: catapults can be put on conveyors, a pulsed reactor on a differentiated generator.

fix Cargo Conveyors, Unit Factories and Cargo Catapults can put onto slightly misaligned Cargo Conveyors, but Conveyors can't put on Conveyors that are even slightly misaligned, making it very difficult to deliver items.

Allow the vault and all 3X3 blocks to enter the cargo loader via the cargo conveyor. if 3X3 blocks can ride on cargo conveyors, why can't they enter the loader? or enter into the game “large cargo loader”.

complex ideas:

global chat improvement:
 add the ability to copy messages from the chat, add the ability to mask commands into words (to create interactive features from the chat for servers)

drill fix:
 the drills are selective to resources if the drill is on the sand but one cell is on the thorium, then it will dig thorium ignoring. make the drills dig all the blocks under them and not selectively

more speed:
 allow the Boers to consume cryogen, factories t1 t2 t3 to consume liquids for a slight acceleration

multi food productions:
in normal mode, all production works according to the standard mode, but if an ingredient is added to the required resources, then production improves many times over, such as a silicon smelter and a silicon crucible, why does the game need another block if this recipe could execute the original block?

mod browser improvements:
make tags for the browser mods inside the game, give a division into texture packs, shaders, mods; add the ability to leave descriptions for mods so that users can understand the content of the mod.

hints when entering the server:
give the opportunity to specify the used mod in the mod browser when creating a server with a mod, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser

super complex ideas:

modification of units: now each unit consists of 3 parts: legs, base; with the usual improvement of a unit by reenactors, he will receive standard weapons, but for t3 t4 t5 reenactors you can put: legs, weapons. crafted in a large constructor that is used when creating a unit, so you can create a tokopid on small legs with a nwanax weapon or even weirder. yes, it will probably create extreme difficulties in implementation and balance, but this will give the game not 10 types of units, but 100 types of units from the recombination of these 10 (actually less due to the incompatibility of some elements)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

изменение отображения командного центра ,улучшение чата ,улучшение браузера модов
много разных идей собранных за 2 месяца игры на бете версии 7
мелкие визуальные улучшения,ребаланс некоторых блоков ,глобальные изменения механик

привет ануке , я довольно давно играю в миндустри , и играю на бете в7
я пару месяцев создавал этот список того чего не хватает игре ,мои навыки английского плохи текст переведен с помощью гугл переводчика ,если возникнут вопросы напиши мне в дискорде ZIS#4100

небольшие идеи:

над командным центром появляется голограмма. поверх всех слоев юнитов

добавить возможность менять менять оформление тьмы вокруг карты на “текстуру блока космос”

добавить возможность сохранить адрес сервера из списка публичных серверов

сделайте чтобы : катапульты можно ставить на конвейеры,импульсный реактор на дифференцированный генератор.

исправить грузовые конвейеры , фабрики юнитов и грузовые катапульты могут выкладывать на немного смещенные грузовые конвейеры ,но конвейеры не могут положить на конвееры что хоть немного смещены ,это очень утруждает доставку предметов.

Позвольте хранилищу и все блокам 3Х3 ,войти в грузовой загрузчик по гр
узовому конвейеру . если блоки 3Х3 могут ездить по грузовым конвейерам почему не могут войти в загрузчик? либо введи в игру “большой грузовой загрузчик” .

сложные идеи:

глобальное улучшение чата:
 добавить возможность копировать сообщения из чата ,добавить возможность маскировать команды в слова (для создания интерактивных возможностей из чата для серверов)

фикс буров:
 буры избирательны к ресурсам если бур стоит на песке но одной клеткой стоит на тории то он будет копать торий игнорируя .сделать чтобы буры копали все блоки под собой а не избирательно

больше скорости:
 дать возможность бурам потреблять криоген , фабрикам т1 т2 т3 потреблять жидкости для незначительного ускорения

мульти питание производств:
в обычном режиме ,все производства работают ,по стандартном режиму ,но если к требуемым ресурсам добавить ингридиент то производство многократно улучшается ,как пример кремниевая плавильня и кремниевый тигель , зачем игре еще один блок ,если этот  рецепт мог исполнять ,изначальный блок?

улучшение браузера модов:
сделать теги для браузера модов внутри игры , дать разделение на текстур паки , шейдеры , моды ; добавить возможность оставлять модам описание чтобы пользователи могли понять содержание мода.

подсказки при заходе на сервер:
дать возможность при создании сервера с модом указать использованный мод в браузере модов , при заходе пользователя без мода ему выходит предупреждение что нужно установить мод показанный в браузере модов

супер сложные идеи:

модификация юнитов: теперь каждый юнит состоит из 3 частей : ноги ,основа ; при обычном улучшении юнита по реконструкторам он получит стандартное вооружение ,но к т3 т4 т5 реконструкторам можно поставить: ноги , вооружение. создаваемое в большом конструкторе ,которые используются при создании юнита , таким образом можно создать токопида на маленьких ножках с оружием нванакса или что еще страннее . да возможно это создаст крайние трудности в реализации и балансе но это даст игре не 10 видов юнитов а 100 видов юнитов из рекомбинации этих 10 (на самом деле меньше из за несовместимости некоторых элементов)

**Comment by itcannotbe** [comment]
It's good practice to make one suggestion one issue, not cramming everything to one issue, it makes discussing anything a nightmare.

**Comment by itcannotbe** [comment]
> drill fix:
the drills are selective to resources if the drill is on the sand but one cell is on the thorium, then it will dig thorium ignoring. make the drills dig all the blocks under them and not selectively

This is intended

**Comment by itcannotbe** [comment]
> Allow the vault and all 3X3 blocks to enter the cargo loader via the cargo conveyor. if 3X3 blocks can ride on cargo conveyors, why can't they enter the loader? or enter into the game “large cargo loader”.

Already rejected.

**Comment by itcannotbe** [comment]
> super complex ideas:

modification of units: now each unit consists of 3 parts: legs, base; with the usual improvement of a unit by reenactors, he will receive standard weapons, but for t3 t4 t5 reenactors you can put: legs, weapons. crafted in a large constructor that is used when creating a unit, so you can create a tokopid on small legs with a nwanax weapon or even weirder. yes, it will probably create extreme difficulties in implementation and balance, but this will give the game not 10 types of units, but 100 types of units from the recombination of these 10 (actually less due to the incompatibility of some elements)

It's a balancing nightmare.

**Comment by ziszlo** [comment]
why? I demand an answer!

**Comment by ziszlo** [comment]
autobalance : exists
all developers in the world: not for me!

**Comment by ziszlo** [comment]
question: global chat improvement, mod browser improvement. good ideas or not?

**Comment by itcannotbe** [comment]
> Allow the vault and all 3X3 blocks to enter the cargo loader via the cargo conveyor.NOT? why? I demand an answer!

Because...

1.) It wouldn't look good (the 3x3 block won't fit inside the space provided by the block loader/unloader

2.) Dev on making larger block loader/unloader:

"Making two new 5x5 blocks just for an underused mechanics just seems redundant"

**Comment by ziszlo** [comment]
question: global chat improvement, mod browser improvement. good ideas or not?

**Comment by oinkymoo** [comment]
1. make this like, 10 separate suggestions. 
2. what is this autobalance you speak of? cuz i've never heard of it
3. you didn't fill out the template correctly. it exists for a reason. you didn't explain how any of these would improve the game. 
4. mod browser is a good idea but it would require a lot of work from mod developers, many of whom no longer are updating their mods, and likely would never be implemented

**Comment by ziszlo** [comment]
thanks for the advice, the ideas will be finalized and sent separately.
the template is described in broad terms, translators translate it distorting the meaning (game: we have 20 languages
acceptance of bugs and suggestions: 1 language, take it or leave it, good luck getting lost in the github interface.)
dev trello: destroy old mods
;devs in public: we're worried about old mods!!

**Comment by meatball-sus** [comment]
> multi food productions

Google translate moment
