### ISSUE TITLE
thing

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#3414]
### Describe the content or mechanics you are proposing.

I'll keep this brief. Patience is thin when clicking the Trello link deletes what you were writing for 20 minutes.

Internal achievement handling:
  Achievements that are handled in-game, basically messages that appear on [event].
  
Tutorial (Part 2):
  I've already ranted about this, but I'm doing it again. Bring back the tutorial, but allow manual saving and give clearer exit instructions. Consider infinite waves as well, with research mechanic included for a small return to the old days if you so wish.
  Also, instead of one big one, do sort of guideline tutorials when you (for example) launch to Erekir - upon landing, the game prompts you to take a optional tutorial to learn the basics of the new planet. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Achievements: 
  Steam is so basegame limited and proprietary. Internal achievements would allow mods to have their own and make them far easier to use overall.
  
Tutorial:
  The answer to retarded players isn't removing and forgetting your mistakes, it's fixing them. Hints suck beyond ass, and if you want to argue why they exist, hit me up in DMs and I'll stand my ground. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
should maybe be 2 separate suggestions. i support tutorial but achievements are a paid-version-only feature so probably not

**Comment by OnyxFinger** [comment]
Basically, asking for a bit of the old campaign. I definitely want it, but I don't think that it will be easy to properly add.

**Comment by Falling10fruit** [comment]
Yes, the tutorial in Mindustry Classic is so much better than the one now, almost died trying to understand manual drilling.

**Comment by itcannotbe** [comment]
Adding in a spoon fed tutorial won't solve people having have of the brain to understand the game.

**Comment by BlueWolf3682** [comment]
Having a real tutorial would help a lot with newer players, much like having an actually helpful community of older players would help too.
