### ISSUE TITLE
Better Campaign Experience

### ISSUE THREAD

**Issue by BiggerBrainYT** [Anuken/Mindustry-Suggestions#3415]
### Describe the content or mechanics you are proposing.

I avoided the campaign for a while because I didn't like the concept, but recently when another one of my friends got the game I tried out the campaign with him and a couple of other buddies and got really hooked. As fun as everything is, there are major issues that we are encountering. I will be listed them off and explain solutions (sorry if this should have been broken into multiple posts but I don't want to spam out suggestions).

1. The notification for an area getting attacked should NOT auto close and rather have a dismiss button.
2. You should be able to change where a sector is launching resources from the globe view.
3. You should be able to (at least in the campaign) send multiple waves of enemies at once (even two waves at once would be great).
4. There needs to be a way to stop enemy drones from rebuilding in a certain area permanently, perhaps a block or just placing a block on the old building should cancel the enemy ghost blocks out.
5. Globe views indication/visualization of a base's damage.
6. Notifications for major damage in a sector.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. I will go to the bathroom or alt-tab, etc while the message pops up and by the time I come back I will never have known I have been attacked there and I will most likely lose the sector. If players do not like this change, it could be a toggle in a menu.
2. After reaching a certain point, the only way to take out certain sectors is through imports from other sectors. When you have multiple exporting sectors, it is annoying to go to each one and set the launch pads to go to the place where you want them to go. Rather than going through the loading screen after the loading screen, imagine how great it would be to handle all of this through the globe view.
3. Lossing a base is sometimes inevitable, whether it be you didn't realize or you had multiple bases attacked at once and you just couldn't multi-task hard enough, it's part of the game and I'm fine with that. What I am not fine with is going through all of the waves again, it gets REALLY annoying especially if it is a sector that is frequently attacked. Going through 90 or so waves when you have set up a defense strong enough for all of the waves is annoying and a massive waste of my time, but the simulated attacks don't always work and I don't trust it enough where I can just leave a base. This could also be risky and could end up killing the cockiest players while giving those who want to blast through the first 50 or so waves quickly an easier time.
4. Attack maps are very fun but start to suffer in the end game when the opponent has multiple rebuilding drones as any progress you make will instantly be rebuilt, and any land you are attempting to take over is constantly bugged by drones. Whether this is intended or not, this is not fun and there needs to be a better way to stop them rather than a bunch of turrets because some of the higher tier drones rebuild faster than your turrets can take them down or faster before you can get turrets down. If there was some sort of block, unit, or just simply placing a block on the enemy ghost to cancel out their constant annoyance, that would be so great.
5. When multiple bases are being attacked at once, it would be nice to have a visual of their damage on the map (maybe the sector on the map would be shaded based on how badly it got damaged), clicking through every sector is a lot more annoying and something like this would be great.
6. If all else fails, this could be a final attempt at the game trying to get a player who might have missed any notification.

I understand there are things like simulated attacks and the lack of an ability to have multiple people work on one campaign yet across multiple sectors that cannot be improved/implemented without heavy changes to the game, and I believe that these features could be a nice substituted for big changes like those.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i think if the destroyed structure is part of an undefended area you can plop down some conveyors and distract the enemy for some time. other than that i support all of this

**Comment by itcannotbe** [comment]
Impossible. Since most the things you are complaining is basically when you're not playing in a sector.

The other sectors that are running aren't running as the same as you were inside of a sectors, it's "simulated based on certain variables, and changes in the sector is reflected once you enter the sector.

**Comment by BiggerBrainYT** [comment]
> Impossible. Since most the things you are complaining is basically when you're not playing in a sector.
> 
> The other sectors that are running aren't running as the same as you were inside of a sectors, it's "simulated" based on certain variables, and changes in the sector is reflected once you enter the sector.

These are all changes based on simulations. I understand the limitations, and I don't think that these bypass them.

**Comment by oinkymoo** [comment]
> Impossible. Since most the things you are complaining is basically when you're not playing in a sector.
> 
> The other sectors that are running aren't running as the same as you were inside of a sectors, it's "simulated" based on certain variables, and changes in the sector is reflected once you enter the sector.

I went through and
1. This is a change to an existing feature and would require no changes to simulation.
2. This would allow the player to change a single variable. I don’t think it would affect simulation significantly.
3. This has nothing to do with remote simulation. 
4. This has nothing to do with remote simulation. 
5. This does not change the simulation itself, it only moves an already visible statistic (the % damaged, visible by clicking the sector) to a more visible location. 
6. This doesn’t change the simulation, it adds another alert for when a certain simulated condition (which is already calculated) is reached
