### ISSUE TITLE
Conversor para chatarra 

### ISSUE THREAD

**Issue by Pro435mine** [Anuken/Mindustry-Suggestions#3416]
### Describe the content or mechanics you are proposing.

Una máquina que use 80 unidades de energía y para operar nesecite cobre y ese cobre lo transforme en chatarra 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Esta máquina sería para el modo libre ya que en algunos mapas no apare arena ni chatarra y ni permite avanzar y con esta máquina se podrá avanzar 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
previamente negado porque está dominado (google translated, i don't speak spanish)

previously denied because it is overpowered.

https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083, https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779
