### ISSUE TITLE
click on minimap to pan view

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#3417]
### Describe the content or mechanics you are proposing.

title :)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

lets mobile people pan view and lets desktop people move at the speed of light

also lets minimap be a little more useful 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
currently doing so opens the fullscreen minimap on desktop, so that control would have to be changed but otherwise I support

**Comment by LeoSko** [comment]
I feel like fullscreen minimap will become obsolete if we get instapanview, but generally idea makes sense.

**Comment by OnyxFinger** [comment]
> currently doing so opens the fullscreen minimap on desktop, so that control would have to be changed but otherwise I support

but maybe not if it's a different key ?

**Comment by oinkymoo** [comment]
> > currently doing so opens the fullscreen minimap on desktop, so that control would have to be changed but otherwise I support
> 
> but maybe not if it's a different key ?

As in, you press K or something to lock the view instead of clicking the minimap? That could work

**Comment by oinkymoo** [comment]
> I feel like fullscreen minimap will become obsolete if we get instapanview, but generally idea makes sense.

Fullscreen minimap is the most detailed way to see the whole map. I don’t think so
