### ISSUE TITLE
Add tag categories to prevent confusion

### ISSUE THREAD

**Issue by AMindustryPlayer** [Anuken/Mindustry-Suggestions#3418]
### Describe what you would like changed, and why.

When there are too many tags exists, we can hardly find a tag and hence schematics. If there is a way for us to find a tag, we can find schematics more easily.

### Describe the changes you want to propose. Include possible alternatives.

Add tag categories to schematics and tag categories should be able to be customized by players, so that the schematics can be indicated easily.

**Comment by itcannotbe** [comment]
It's this the same suggestion as schematic folders in essence?

**Comment by ziszlo** [comment]
я согласен с идеей что нужно добавить поиск в базе схем ,по параметрам : имя ,тег , блоки в составе

**Comment by oinkymoo** [comment]
how do you have so many tags that this is necessary?

**Comment by AMindustryPlayer** [comment]
> It's this the same suggestion as schematic folders in essence?

similar, but quite different.

**Comment by AMindustryPlayer** [comment]
> how do you have so many tags that this is necessary?

I don't know. Some players are just so dumb to add so many tags xd.

**Comment by itcannotbe** [comment]
> > It's this the same suggestion as schematic folders in essence?
> 
> similar, but quite different.

It's not. Let me explain.

Schematic folders were suggested to organize and thus to make it easier to find schematics. A search function already exist back then.

Anuke's anwser? Tags.

And now here we are. People wanting to organize tags into categories which has the same aim as before.

So what's next?

Categories of categories?

**Comment by AMindustryPlayer** [comment]
> > > It's this the same suggestion as schematic folders in essence?
> > 
> > 
> > similar, but quite different.
> 
> It's not. Let me explain.
> 
> Schematic folders were suggested to organize and thus to make it easier to find schematics. A search function already exist back then.
> 
> Anuke's anwser? Tags.
> 
> And now here we are. People wanting to organize tags into categories which has the same aim as before.
> 
> So what's next?
> 
> Categories of categories?

oh no...
