### ISSUE TITLE
A New Gamemode Idea (promise its a good one) 

### ISSUE THREAD

**Issue by VStarPlayer** [Anuken/Mindustry-Suggestions#3419]
### Describe the content or mechanics you are proposing.

I have the greatest idea for a new gamemode, its like multiplayer but not, my idea is a gamemode that is unlocked after achieving planetary travel, in the menu of games, you unlock a gamemode called „Planetary Conquest“ in which a host is presented with different planets to choose from, or design himself one, varying in size and number of sectors, and what the sectors contain, with 2-3 available by default(One of them being Serpulo and the other Erekeer and another Earth-like) the gamemode is played by multiple people with an IP code to be able to join, and can only be played while everyone that is participating is online, the game puts everyone in a random location on the new planet, the rules are simple, defeat every sector that your enemy owns, and the Crux can be enabeld or disabled when the world is created, if capture you opponents base, they may or may not build defenses for it, easier or harder to get them, the Tech Tree is deafault and must be completed but the interplanetary accelerator is not accesable and you can't lauch to places like to the Craters from the other part of the planet, only lauching to places next to an owned sector, all things in the Tech Tree do not require a scepific sector completed but a number of sectors owned, if all the other opponents's cores are destroyed, you win, the game can have 2-8 players. How does this sound like?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It doesnt sound like much coding to do, and many people would enjoy it, a longer game of multiplayer in which people are more active, a war that can last a long, long time between 2 or more people that all play at the same time just seems like a great idea to me and I think that my Idea is very good.
                                                         - with all respect, 
                                                           NikoCrafting

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
all servers are hosted and run by community members, not anuke. if you want this get a server owner to implement it

**Comment by AMindustryPlayer** [comment]
> all servers are hosted and run by community members, not anuke. if you want this get a server owner to implement it

I don't think it is simple to get a server and implement it.

First, you create a mod, which takes a lot of time on developing and debugging.

Second, you are trying to get a server, which has decent storage and CPU.

Third, the server needs to be popular or else it would be dead.

I suggest that this gamemode should be team pvp based, not solo pvp based, so that there will be a winning team.
By the way, planet generation would be too harsh and I think it is not so necessary so adding planet generation into the game is not recommended. The game has sector generation already.

**Comment by itcannotbe** [comment]
You do know that this is obscenely resources expensive to even consider developing for?

**Comment by williams104** [comment]
I like it but also agree with what itcannotbe said.
Maybe it could only run the maps with players on it?
Also, the planet could be held on the server.

**Comment by oinkymoo** [comment]
Btw this already kinda exists in hex pvp

**Comment by Sector171** [comment]
> seems like a great idea to me and I think that my Idea is very good.

Definitely it is good idea, and will take Mindustry to a different level.
See my suggestion here which I think it is even better #2066
The problem with such ideas is it requires huge efforts and resources.
But it will be great to see something similar in Mindustry.
