### ISSUE TITLE
Explosives as an exception for placement in core build radius

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#342]
**Describe what you would like changed, and why.**

With the new block carrying mechanic, it's very intuitive for a player or any other unit AI to drop highly-damaging blocks, such as thorium reactors, impact reactors, containers and vaults into enemy territory; however the current commit of Mindustry doesn't allow that.

**Describe the changes you want to propose. Include possible alternatives.**

Since the wave team is allowed to place anywhere, a check here is performed as the wave team to test whether the dropped block is a `NuclearReactor` or an `ImpactReactor`, and then attempt to place it.
```diff
diff --git a/core/src/mindustry/entities/comp/PayloadComp.java b/core/src/mindustry/entities/comp/PayloadComp.java
index 09e978ced..4a007991b 100644
--- a/core/src/mindustry/entities/comp/PayloadComp.java
+++ b/core/src/mindustry/entities/comp/PayloadComp.java
@@ -9,6 +9,8 @@ import mindustry.content.*;
 import mindustry.gen.*;
 import mindustry.world.*;
 import mindustry.world.blocks.payloads.*;
+import mindustry.world.blocks.power.NuclearReactor;
+import mindustry.world.blocks.power.ImpactReactor;
 
 /** An entity that holds a payload. */
 @Component
@@ -89,7 +91,14 @@ abstract class PayloadComp implements Posc, Rotc{
         Building tile = payload.entity;
         int tx = Vars.world.toTile(x - tile.block().offset()), ty = Vars.world.toTile(y - tile.block().offset());
         Tile on = Vars.world.tile(tx, ty);
-        if(on != null && Build.validPlace(tile.block(), tile.team(), tx, ty, tile.rotation())){
+        if(on != null && 
+            (Build.validPlace(tile.block(), tile.team(), tx, ty, tile.rotation()) ||
+                (Build.validPlace(tile.block(), Vars.state.rules.waveTeam, tx, ty, tile.rotation()) && (
+                    tile.block() instanceof NuclearReactor ||
+                    tile.block() instanceof ImpactReactor
+                ))
+            )
+        ){
             int rot = (int)((rotation + 45f) / 90f) % 4;
             payload.place(on, rot);
 
```

The only alternatives I found are dirtier, and involve direct modification of the `Build.validPlace` method; probably causing bugs like being able to directly place reactors inside of no build zones.

**Comment by ritzip** [comment]
***GLOBAL THERMONUCLEAR WAR***

**Comment by Anuken** [comment]
I'm not going to be adding special cases to the placement system just so reactor bombing can become a valid tactic. Firebombing is already enough.
