### ISSUE TITLE
New Conduit types + new unit control command

### ISSUE THREAD

**Issue by Funny132** [Anuken/Mindustry-Suggestions#3420]
### Describe the content or mechanics you are proposing.

Let's start with the basics. The new Conduit types. I'll go through them one-by-one.

-Overflow Conduit - Outputs liquids through the front unless the front path is blocked, at which point it will output to the sides
-Underflow Conduit - Basically just the opposite of an Overflow Conduit.

Here's where we get a little bit complicated.

-Multi-Conduit - A type of Conduit that transports two liquid types at a time. If two liquid types are in a Multi-Conduit, it cannot directly connect to a regular Conduit. If there's only one type of liquid currently in it, though, that's fine.
-Conduit Sorter - Simple enough. Receives input from a Multi-Conduit and outputs the first type of liquid to the left and the second type of liquid to the right. These outputs can connect up to both regular Conduits and Multi-Conduits as well.

Next up, the new Logic command I thought of.

Basically, a "release control" unit control command - pretty self-explanatory. The unit returns to its original behaviour and will do what its AI is set to do, but will not unbind itself from the Logic Processor. This would be overridden by all other unit commands, but it would be useful for simple commands that tell damaged units to go to repair points until they're at max health, for example. This would also be useful for most Logic instructions involving Poly and Mega drones as well, as you could make it so that they do their usual job when Logic isn't telling them what to do (rebuilding destroyed buildings and repairing damaged buildings respectively)

Extra note, I think Nova or Mono units should have a weak Repair Point-like turret on them that slowly repairs nearby damaged units at about a third of the rate of a regular Repair Point. This way, you have a source of healing inbetween quick surprise-attack assaults without having to stick power and repair points down and waiting to repair your units or going in highly damaged. Instead, just throwing a few Novas in will make a small impact. It also means that you won't have have spam fifty billion repair points around Command Centers to repair units during the Rally command.

Oh, and I thought of one other thing just now, remember my "How did that even happen?" achievement suggestion regarding dying to your own bullet due to a Phase Wall? Yeah, I thought of a new one named "How did that even happen again?" - Basically, the same conditions as How Did That Even Happen? except you have to die to a Surge Wall bolt directly triggered by your bullets in particular

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Overflow and Underflow Conduits - pretty much the same reason Overflow and Underflow gates exist for solid items

Multi-Conduits - These would exist for when you need to save that one column of space to fit something else, possibly important, in without having to disrupt a potentially major part of a supply line.

As for the Logic command and Repair Point Nova/Mono fusions, I explained what would be useful about those already. Although, without needing to directly change anything about the pre-existing unit, a sort of Payload Loader block could potentially be able to load a small selection of buildings onto certain T1s, which are then stuck there permanently

As for the achievement, it's yet another fun little achievement that would, in my opinion, be cool to have in the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
No for two reasons.

Multi liquid conduits are rejected

Logic is hanging by a thread.

**Comment by SMOLKEYS** [comment]
> Logic is hanging by a thread.

To lengthen: Anuke is considering removing logic from campaign.

**Comment by meatball-sus** [comment]
Be cooler if they were called overflow/overflow sluices instead of just conduits

**Comment by williams104** [comment]
Just use router junction blocks
