### ISSUE TITLE
New Logic Blocks

### ISSUE THREAD

**Issue by Def-Try** [Anuken/Mindustry-Suggestions#3421]
### Describe the content or mechanics you are proposing.

Hello. I just wanted a few new blocks and one command:

Keyboard: Several redims - capture and receive. They change through the processor (config 0 - receive, 1 - capture). The RECEIVE mode works like a message, but it does not show the text, but sends the entered string to the processor after pressing OK. CONQUER mode takes control and every time the player presses a button, the keyboard sends the letter or character that the player pressed to the processor. To "release" the control you need to press ALT. Everything is read through the sensor command: sensor VAR = @string in keyboard1. You may need something to specify a specific unit (flag?), or to easily write text and pass it to the processor.

String block: Works like a data block, but can store strings. 1 letter = 1 byte. Size - 128 bytes. Useful for storing strings, "phone numbers", etc.

Processor command: TEXT - displays text on the screen at X and Y coordinates. Useful for maps with a plot where you need to display noticeable text

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

/\

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
> I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

so that was a lie

**Comment by oinkymoo** [comment]
string manipulation is not happening, because it allows for large amounts of data storage, so string storage definitely isn't happening either.
