### ISSUE TITLE
Minimize amount of technologies locked by main sectors

### ISSUE THREAD

**Issue by Alex-1000** [Anuken/Mindustry-Suggestions#3422]
### Describe what you would like changed, and why.

Techs locked by main _(named instead of numbered)_ sectors are limiting player's freedom, and things unlocked by those techs are othen very useful on the very sectors they are unlocked by. Placing blocks in sector that unlocks them is practically not a showcase of how to use them but a giant middle finger to player (unless they know that you can dissassebmle block and then instantly reassemble it back to gain control over it, but game doesn't tell you that it is possible).

### Describe the changes you want to propose. Include possible alternatives.

It would be better if there would be more freedom to do additional sectors without having to complete a lot of main sectors in order to get neccesary technologies, so I suggest to either

a) remove most of tech locks completely, allowing players to research a lot of important things on early sectors (con: it would make late game a bit less intresting as you unlock most of things in first sectors)

b) make techs more costful, reducing price to normal when sector that previously was locking it is captured, making it possible but harder to research things on additional sectors (late game doesn't suffer from all techs unlocked in early game, and players have more freedom of selecting which sector to capture)

**Comment by oinkymoo** [comment]
research costs are based on the construction costs of the item. also this is an incentive to actually play the (usually better) campaign maps.

**Comment by AMindustryPlayer** [comment]
> ### Describe what you would like changed, and why.
> Techs locked by main _(named instead of numbered)_ sectors are limiting player's freedom, and things unlocked by those techs are othen very useful on the very sectors they are unlocked by. Placing blocks in sector that unlocks them is practically not a showcase of how to use them but a giant middle finger to player (unless they know that you can dissassebmle block and then instantly reassemble it back to gain control over it, but game doesn't tell you that it is possible).
> 
> ### Describe the changes you want to propose. Include possible alternatives.
> It would be better if there would be more freedom to do additional sectors without having to complete a lot of main sectors in order to get neccesary technologies, so I suggest to either
> 
> a) remove most of tech locks completely, allowing players to research a lot of important things on early sectors (con: it would make late game a bit less intresting as you unlock most of things in first sectors)
> 
> b) make techs more costful, reducing price to normal when sector that previously was locking it is captured, making it possible but harder to research things on additional sectors (late game doesn't suffer from all techs unlocked in early game, and players have more freedom of selecting which sector to capture)

I think the campaign would be too easy if the game reduced amount of technologies locked by main sectors. Thus, there is less fun overall when the game is not challenging.

**Comment by meatball-sus** [comment]
surge on ground zero go brrrrrrrrrrrr
