### ISSUE TITLE
Blocking displays for enemies

### ISSUE THREAD

**Issue by FreezeCactus** [Anuken/Mindustry-Suggestions#3423]
### Describe the content or mechanics you are proposing.

Displays are a nice thing, i often use them to gather information about my resources, units, etc. But i don't want players from enemy teams to see it. My suggestion is to make players unable to see displays of enemy teams. It can also be optional for each map, like banning blocks and units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It won't allow enemies to have more information about your team than they should.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Minimap be like: I see everything.

**Comment by OnyxFinger** [comment]
the re isn't really a reason why you would use a display over normal means of kowing how many resources you have either

**Comment by BlueWolf3682** [comment]
did Crux build furry porn for the 300th time?
