### ISSUE TITLE
Suggestions for Erekir(hot planet)

### ISSUE THREAD

**Issue by meatball-sus** [Anuken/Mindustry-Suggestions#3425]
### Describe the content or mechanics you are proposing.

So I had some ideas for the new hot planet (pretty sure it's Erekir, correct me if I'm wrong).

We could just go for the normal, plain Jane explanation for why it's hot, such as volcanic activity, proximity to the star, etc. Or we could do the cool guy thing and go with the fun option.

_**Radiation.**_

A new radiation mechanic could be added, maybe an Erekir-exclusive rad-storm weather event. Rad-storms could damage units and buildings not protected by force projectors, or maybe even a whole new block. It could also be constant around a new ore type, one perhaps necessary to harness the radiation for power generation, shielding, or even weaponry. A new reconstructor could exist for plating units with this new material, providing immunity or temporary resistance to the radiation.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add another way to differentiate Erekir from the other planets, and perhaps be a good excuse to add a new material to the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by meatball-sus** [comment]
*crickets*

**Comment by Bottinator22** [comment]
no

your car isn't going to be killed by radiation, _you_ are

**Comment by meatball-sus** [comment]
Machines can be damaged by radiation.
For example, cosmic rays are responsible for a lot of bitflips in supercomputers.
Don't believe me? [https://www.youtube.com/watch?v=AaZ_RSt0KP8](url)

**Comment by meatball-sus** [comment]
Ig you're right. What would be a better way to explain radiation severely damaging units and structures?

**Comment by Bottinator22** [comment]
It not being radiation

**Comment by itcannotbe** [comment]
> It not being radiation

Well said.

**Comment by meatball-sus** [comment]
Well, I can't exactly argue with that.

Counterpoint: The heat itself deals damage, and the material that it's constant around is extremely hot until refined?

**Comment by guncatt** [comment]
I'm imagining a solarpanel type block that just takes radiation and gets stronger or doesn't do anything depending on where it's located.

**Comment by 64-Tesseract** [comment]
> The heat itself deals damage

Cryofluid.

**Comment by meatball-sus** [comment]
> > The heat itself deals damage
> 
> Cryofluid.

Bruh I want to argue but I really can’t. Maybe a “Cryofluid Mister” block that disperses cryofluid to cool stuff down?
