### ISSUE TITLE
Double tap unit

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#3428]
### Describe the content or mechanics you are proposing.

When there lots of units stuck together, double tap the unit you want to get and control the unit which is the same type. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Its good for unit vs unit because it can have more attack options and the player can have more Precise attack plans. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
i'm confused. what does this mean

**Comment by paopao840** [comment]
You do know they are removing unit formations right?
