### ISSUE TITLE
Visible JS Commands 

### ISSUE THREAD

**Issue by twos98** [Anuken/Mindustry-Suggestions#3429]
### Describe the content or mechanics you are proposing.

Add the ability to have a list of JS commands in game so people don't have to search for the github JS command archive thing and so it makes it faster to find commands you want and with this the ability to do pretty much what Minecraft does with commands on java where you pick the command it gives you the available values and/or blocks to put in that area of the command making it easier for people that dont know much JS to use it "easily" considering they would need to know what the things ment 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

can help alot when making mods and/or when making small one page scripts for say your campaign world (using modding tool box of course to imput the code) 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
mindustry console is only for debugging, dum
mostly implementing this will only watse game file size

**Comment by SMOLKEYS** [comment]
go read the javadocs instead lazy ass

**Comment by SMOLKEYS** [comment]
aaand console is not supposed to be an everyday thing casual players use

**Comment by EclipseTheOldOne** [comment]
~~and also this is not minecraft command~~

**Comment by WilloIzCitron** [comment]
and also this is not for cheating
