### ISSUE TITLE
Add own player nametag to map screen

### ISSUE THREAD

**Issue by DabestbroAgain** [Anuken/Mindustry-Suggestions#343]
**Describe what you would like changed, and why.**
Currently, when going onto the map screen in a multiplayer game, all other players' nametags are visible but your own is not. In developed bases with lots of yellow on the map screen, it can become difficult to pinpoint your ship due to it being the same color as all of the other construction on the map screen. While not a huge deal, it would be a great QOL change to save a few seconds flying in circles to pinpoint my location.

**Describe the changes you want to propose. Include possible alternatives.**

Include your own nametag above your head in multiplayer matches so you can see yourself against yellow backgrounds. Preferably your own name would be in a different color to indicate that it's yourself. 

Possible alternatives include having your ship icon be a different, contrasting color, thus eliminating the need for a nametag altogether. This would also mean the change would be useful in singleplayer where there are normally no nametags.

**Comment by Anuken** [comment]
This was already suggested and implemented.
