### ISSUE TITLE
Missile launcher turret

### ISSUE THREAD

**Issue by MAY0UL** [Anuken/Mindustry-Suggestions#3430]
### Describe the content or mechanics you are proposing.

This should be a new long ranged turret that we can configure to shot huge missiles which deals massive damage in a big area. The missile should need oil to fly. Depending on the distance the missile will have to travel, it should cost more oil to fill the tank.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It should be a good last game defence againts new units (some t1 units seems op imagine t5)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What's that?

Long range?
Huge missiles?
Massive damage?
Big area?

Ah yes, THAT'S CALLED OVER POWERED!

**Comment by MAY0UL** [comment]
It should cost a lot of ressources to launch and hard to get with a long cooldown to launch missile and used to defend from t6 units. Foreshadow deal 1350 dmg, the turret i propose should deal around 3k dmg. Damage will depend of the distance of the explode point. The explosion deal damage 12 blocs in diameter.

**Comment by oinkymoo** [comment]
yeah that's OP

**Comment by MAY0UL** [comment]
Announced T6 unit are op too and foreshadow was found op at the start of v6 @oinkymoo

**Comment by guncatt** [comment]
> Announced T6 unit are op too and foreshadow was found op at the start of v6 @oinkymoo . And the suggested stats aren't definitive

Wait what tier 6 units there aren't tier 6 units.

**Comment by the-red-soul** [comment]
This sounds like a foreshadow that upon firing creates a thor reactor explosion.... considering how op foreshadows already are in base game, why does this need to exist

**Comment by stuffyAI** [comment]
I am sure you did not really check the Trello, as [this card](https://trello.com/c/Brw9Y1ai/315-nuclear-tech) somewhat sounds like what you want.
