### ISSUE TITLE
"Unit Locate" improvement

### ISSUE THREAD

**Issue by weres0lenny** [Anuken/Mindustry-Suggestions#3431]
### Describe the content or mechanics you are proposing.

It would be great if the processors could get the coordinates of stones and other obstacles that can be broken manually, so that in the future units could automatically break them.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This could be a cool feature that allows perfectionists to play this game without getting annoyed.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why not make a mod that removes pebbles from world generation instead?

**Comment by end-me-please** [comment]
> in the Future

in the dark Future where logic might be disabled in campaign
