### ISSUE TITLE
Command center overhaul

### ISSUE THREAD

**Issue by meatball-sus** [Anuken/Mindustry-Suggestions#3433]
### Describe the content or mechanics you are proposing.

Since command centers as we know it are going away with V7, I suggest that they are overhauled instead of completely removed. You should be able to select squads of units and a leader (e.g 6 Quasars with Vela leader), and formations (Wedge, Column, Spearhead, etc.) You should also be able to select specific targets (Area select or Power, Production, Storage/Core, Units, etc). 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Pros:
1. _Extremely_ versatile unit control options
2. User-friendly alternative to probably-axed unit control logic
3. Would help establish a more RTS-like angle

Cons:
1. Probably difficult to program
2. May have some unneeded bloat

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 64-Tesseract** [comment]
...since when are they getting removed???

**Comment by RFAC-Productions** [comment]
Surprised no one has commented here yet.

Okay, I like it.

**Comment by Sector171** [comment]
No one did comment because it is good idea.
Just give the command center and formation more rich options instead of removing & replacing them.
