### ISSUE TITLE
block wrap placement and block brush

### ISSUE THREAD

**Issue by chaiki5topo** [Anuken/Mindustry-Suggestions#3435]
### Describe the content or mechanics you are proposing.

You can wrap blocks around walls and other blocks placed, so if I placed a few mines, I would want to wrap routers around it, it stretch and whatever way I swipe my finger around left or right it will collide/create layer of blocks. 

Or if I wanted to manually do it I just brush the blocks without grid placement and locked to straight line, so then i don't need to tap and hold many times just to change direction. 

This should be added to campaign and other modes as well. 

I don't want it to guess where I want the blocks. As the one we have already made straight lines creating square it goes red and through blocks, its not useful for what I'm trying to do.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Makes it easier to place blocks without pressing so many times, beable to make more complex decisions. Better strategy and tactical thinking 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
English soup.

**Comment by chaiki5topo** [comment]
> English soup.

Well just because I have disadvantages, doesn't mean I will give up, I there's no mod for this, so that'd why we need improvement in block placement.

**Comment by itcannotbe** [comment]
Wrapping blocks around other blocks is seriously frowned upon. I doubt something like that will be added anytime soon.
