### ISSUE TITLE
Other Logic Systems Changed into Blocks/Ui

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#3436]
### Describe the content or mechanics you are proposing.

There are multiple logic systems that would go to waste if it isn't unlogiced in the new planet.

Unit Transport and Attack Ai/Command - already implemented with the new block and new rts like control : D
Unit Mining - Sugesting that dragging over units and clicking on the core puts them in mining mode.
Unit Healing Blocks - theoretically possible with the new way to command units, maybe making them valid for friendly damaged blocks can enable healing ai (shoot clicked block, if out of range shoot other damaged blocks)
Unit Payload, Payenter etc - Erekir might be payload based, so new blocks enabling units to go in payload mode in megas - octs and payload conveyor would be great.
Unit Building - Command Units on Building by clicking on any not completely constructed block.
Block Item Config - Using nullloaders usually allows for multiitem in one line, although limited by sorter like blocks haing a 2 block range, implementing either some 2x2 sorter with a new ui for multi item sorting like the distributer, or a 1by1 storage block since it cant clog other items when one overfills.
Block Enable - I dont really think it needs to be implemented since deconstructing always disables, and reactor setups only need it if the player isnt careful, although maybe a switch ui on the block info at the menu if it would be implemented.
Block Turret Priority/Aim - To enable multi turret control, maybe some ctrl + drag, or click turret then drag giving the player the ability to retarget, only stop the overide when the player is out of range or enemy units are near

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

With Erekir having no logic (the bandaid needed in serpulo and some of the depth), recovering some of the logic interactions or behavior in the new planet will add in familiar depth to those experienced in similar like designs in Serpulo (albeit without automation in this case) while giving access to new players on these systems without using logic.

On elaboration, Unit Beheavior unlogiced will add some easy acess way to assign certain units on certain duties
Unit Payload, making Payload and Seperated designs possible in Unit (Re)Constructors
Unit Build making builds faster, and with some help.
Block Item Config allowing multi item transport without clogging can be intresting and can give certain structures
Block Turret can be more smoother than place logic block and bind.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> There are multiple logic systems that would go to waste if it isn't unlogiced in the new planet.

Along with all other block aside from payload related blocks and previously available units.

Erikir is a totally new planet and game mechanics that come with it. Deal with it.

**Comment by SomeonesShade** [comment]
> Erikir is a totally new planet and game mechanics that come with it. Deal with it.

Im keeping Serpulo in mind as well, since Anuke had some thoughts on rermoving logic from there, although may be revised

> Steam v7 Progress Report - No logic blocks are available on Erekir. EDIT: Based on feedback, I will definitely be keeping it on Serpulo.

So to ease the Serbulo block set, adding replacements can give some options for players to access to certain mechanics without the use of logic, since as much as I like playing withe system to create certain behaviors for units or blocks, it shouldn't be necessary to access them.

Also Erekir would most likely have some fundamentals here, but can't really gurantee that payload or any other mechanic may be in Erekir, so putting some ideas out that if Anuke has still some of the external mechanics said here, although there are some confirmed:
Healing Exists - New Core Unit 
Shooting Exists - Units shooting
Item Config Exists - Sorter + New Unit Transport Block

and some just need to be/fundamental:
Building
