### ISSUE TITLE
Spore turret (Outbreak)

### ISSUE THREAD

**Issue by meatball-sus** [Anuken/Mindustry-Suggestions#3437]
### Describe the content or mechanics you are proposing.

A Plastanium-tier turret that uses spore pods as ammo. It does low base damage, but when it hits a target it inflicts an “infected” status effect that does DoT damage. When an infected unit dies, it creates a spore cloud that infects nearby units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

No turrets in the game currently use spore pods as ammo, and they currently have no use outside of oil production when no thorium is available. As they say, the best way to make something not useless is to give it a use.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
i don't think that'd make sense
spore are moss that slowly spead
also spore don't eat metal, though
this won't provide much fire power or support power

**Comment by oinkymoo** [comment]
it could perhaps give the same spore slowed effect that spore storms give. also it is also better combustion/steam generator fuel than coal, and is used in blast compount
