### ISSUE TITLE
Optional Fog of War

### ISSUE THREAD

**Issue by THEGAMER-10n** [Anuken/Mindustry-Suggestions#3438]
### Describe the content or mechanics you are proposing.

Make enemy units invisible when out of range (by radar, or by light). It will make unit locate command for logic stop working if the enemy building (e.g. Core, battery, or node) cannot be seen.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. This can add more uses for lighting (currently just a waste of space), and it forces pvp to be more defensive and strategic.
2. A need for scouting and makes blind rushes unreliable.
3. This will also remove core bombing, both logic and manual.
4. Forces players to build micro bases in order to get map vision.

Cons:
- The logic part would probably be hard to implement.
- This can become very complex.

Alternative:
- Make lighting do this
- Don't add this at all

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
..enable lighting and disable enemy lights? this already exists

**Comment by itcannotbe** [comment]
> ..enable lighting and disable enemy lights? this already exists

It doesn't. Proper Fog of war isn't achievable with just lighting rules.

**Comment by THEGAMER-10n** [comment]
> ..enable lighting and disable enemy lights? this already exists

If you set the alpha values of lighting to less than 255, you can still see the enemies

**Comment by EclipseTheOldOne** [comment]
the idea is planned, but never been added
'fog' exist back in b63, then

**Comment by EclipsePlays** [comment]
Fog of war should also make the map look very dark if the tiles are still not explored btw.

**Comment by itcannotbe** [comment]
> The limited camera pan speed is already functionally fog of war.

The minimap disagrees.

**Comment by Larofeticus** [comment]
It still costs player attention to go into the map and zoom/pan enough to be able to resolve unit outlines.

And all buildings are just solid color so the minimap doesn't substitute.

**Comment by itcannotbe** [comment]
> It still costs player attention to go into the map and zoom/pan enough to be able to resolve unit outlines.
> 
> And all buildings are just solid color so the minimap doesn't substitute.

Actually panning on the map is one of thing you are constantly doing in games where proper fog of war exists.

**Comment by Larofeticus** [comment]
Pretend every player gets a free scanner sweep, but instead of costing energy to use, it's the time it takes to pan to the location you want to gain information about.

There is the equivalent of fog of war, already, on every map location that the camera isn't viewing.

**Comment by itcannotbe** [comment]
Difference being in games with proper fog of war, panning your camera doesn't give you anything you don't know yet.

**Comment by end-me-please** [comment]
Another big problem is that a graphical/clientside-only handicap in multiplayer is equal to no handicap at all.

It takes like 5 seconds to type Vars.state.rules.lighting=false into the console to circumvent it.
Those who know how to do it will do it, and gain an advantage over those who don’t.
