### ISSUE TITLE
Loadouts and Core Schematics

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#3440]
### Describe what you would like changed, and why.

When new players play campaign, they sometimes try to launch on every sector with little to no loadouts. And as you progress, maps get harder. That's fine, but as soon as they notice that loadouts exist... That's where things start to get easier when conquering. With max loadouts and strong core designs, you can make eradication sectors look like medium threat ones. 

If possible, we should limit players launching too much items, and also teach some players the importance of loadouts and core designs. Why? Because people keep complaining that campaign is BS, one factor was them not launching most, if not all their items into a new sector.

### Describe the changes you want to propose. Include possible alternatives.

Here are the things I could think of right now:

1. Tech based loadout count
Either increase their max loadout by a certain amount when they research a new item, or allocate loadout specific tech to increase their loadout (note that max core capacity still counts), though this remedy can be easily fixed by just researching and AFK'ing for as much as possible. 

2. Multiply items required to launch
Items that are launched require twice as much (though the core requirements won't be affected) and core designs require thrice as much items than usual, more like the others used as the "transport fee" or something. You can reduce the penalty by a certain amount by researching allocated tech.

**Comment by RealYeet** [comment]
Honestly this hurts as a core schematic user but I fully agree with this. Maybe 3x the amount is a little excessive but some sort of penalty would go a long way.

**Comment by oinkymoo** [comment]
this doesn't help with the problem that new players don't understand loadouts or core schematics

**Comment by EclipsePlays** [comment]
Tthe new tech might make them look out for those loadouts
But also, the upcoming tutorial will teach new players how to use loadouts

**Comment by Anuken** [comment]
Core schematics are a broken mechanic. Mechanically, they are useful on Serpulo as a method of reducing grind with its countless enemy bases, but overall, they make no sense (where are the blocks coming from?), break the map/loadout (what if there's no space?) and provide a massive advantage to players who happen to know how they work.

Erekir does not have core schematics. I'm keeping them around on Serpulo for now, but I don't think it's worth explaining a mechanic that is inherently flawed and may be replaced with something better in the future.

Launch items were nerfed by capping the maximum amount to 1/4th of the core's item capacity.

**Comment by AMindustryPlayer** [comment]
> Core schematics are a broken mechanic. Mechanically, they are useful on Serpulo as a method of reducing grind with its countless enemy bases, but overall, they make no sense (where are the blocks coming from?), break the map/loadout (what if there's no space?) and provide a massive advantage to players who happen to know how they work.

Yeah, where do the blocks come from? Are they launched together with the core? No one knows...

By the way, if Surpulo is level 1 of Mindustry campaign, then Erekir should be level 2, there is no way to make Erekir sectors easier to capture if players have already beaten Surpulo part of the campaign.
