### ISSUE TITLE
Factory-made units lack

### ISSUE THREAD

**Issue by floglass** [Anuken/Mindustry-Suggestions#3441]
### Describe what you would like changed, and why.

The factories don't show which resources are required to build units. It is possible to find what resources are needed for which units in-game, but it requires going to the research screen. It would be very useful to be able to see what each units cost in a glance.

### Describe the changes you want to propose. Include possible alternatives.

When selecting which unit to build, maybe a mouse-over type pop-up could show which resources are required. It could be colour coded; the number of resources would be grey (normal) if the resource is in the factory, and red otherwise.

**Comment by RealYeet** [comment]
This has already been corrected in the latest release where you can see building requirements in the info section of the builder.

**Comment by floglass** [comment]
Amazing work, then! =)
Sorry for the useless issue, and the poor title.
