### ISSUE TITLE
Block constructors

### ISSUE THREAD

**Issue by TheAnnoyingIdot** [Anuken/Mindustry-Suggestions#3442]
### Describe what you would like changed, and why.

The can be walked over by ground units. This would not make sense as even if the design for it is built into the ground the output blocks should be walkable on as well.

### Describe the changes you want to propose. Include possible alternatives.

Make the block constructor work like a normal block, else, make the output block uncollidable until it is off the constructor.

**Comment by oinkymoo** [comment]
i'm confused, the block constructor is non-solid but the block within is not?

**Comment by SuperThunder958** [comment]
I'm also confused he said the ground units can walk over the walls the only units I know of that can walk over the wall is the upgraded versions of the crawler 

And other thing that makes me confused is he said the output block should be walkable on as well what do they mean by output blocks. 
a wall does not output blocks......it doesn't even produce anything it's just a wall that blocks some enemy fire and blocks passage to some enemy ground units and water units (only if placed in shallow water and [ correct me if I am wrong] water but not deep water)

**Comment by 64-Tesseract** [comment]
...Do you mean block payloads?

**Comment by oinkymoo** [comment]
I believe they are referring to the block constructor, the currently sandbox-only v7 block
