### ISSUE TITLE
add a wave variable to the world processors

### ISSUE THREAD

**Issue by Rusomati** [Anuken/Mindustry-Suggestions#3443]
### Describe the content or mechanics you are proposing.

if you haven't added them already please add @wave variable to the world logic processors

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the @wave variable can make cutseens when a boss appears. because waves are skippable, using the time variable is almost useless

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why not just allow world processors to spawn in waves?

Say like in response to certain triggers or conditions
