### ISSUE TITLE
Map view-only timelapse replay system

### ISSUE THREAD

**Issue by Tamren** [Anuken/Mindustry-Suggestions#3445]
### Describe the content or mechanics you are proposing.

Note, this is NOT a request for a full game replay system. I have seen those suggestions before, one of them was specifically denied on github earlier because it would be too hard to record all of the game's parameters. And even if you could do that, playing them back might create a different result because the game isn't deterministic.

What I am proposing here is something a lot simpler than that. Basically this feature would allow you to view a recording of a game, but ONLY from the map view. The only parameters recorded are what you can view from the map screen, meaning the position of buildings and units. Buildings are represented by coloured dots and the only important metric so far as the map view is concerned is whether or not a building exists. Units and players are slightly more complicated but still boil down to sprites that follow a series of waypoints until they are killed and the sprite disappears. This is a much smaller dataset compared to stuff like tracking the position of items on belts, the contents of buildings and projectiles from weapon fire. So I believe it should be possible to record very long games in this fashion without using too much memory.

Playing a replay back could be done from the victory/defeat screens in campaign. Perhaps this could even be done automatically and the replay is integrated into the results screen itself. You can watch the map change in realtime starting from the beginning of the recording, or speed it up in order to see a time lapse of events.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While this replay system wouldn't let you see down to the nuts and bolts of a match, it would still give you a birds eye picture of everything going on. For instance if you are suddenly defeated in a hectic campaign mission you could rewind the tape and see exactly where and when the enemy managed to breach your defences. You could also use this feature to practice and verify speedruns because it provides a timestamp that doesn't require you to use third party tools.

Another feature which would make catching griefers in multiplayer a lot easier is that if you recorded a multiplayer game in this way, the sprites that represent player ships would be tagged with that player's name. So if one player is going around and deleting single belt tiles here and there, or deconstructing large parts of the factory when no one is looking. Such sabotage can easily be seen in realtime and presented as photographic evidence after the fact because recordings can be sent to the server admin.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
So this is, to simplify, recording the minimap?

**Comment by Tamren** [comment]
Yes, the full zoom of the minimap you can view by pressing M is what you see in the recording.
