### ISSUE TITLE
Fault checker blocks for detecting throughput and bottleneck issues in belt networks

### ISSUE THREAD

**Issue by Tamren** [Anuken/Mindustry-Suggestions#3447]
### Describe the content or mechanics you are proposing.

This idea is an update and further simplification of  #3444. When I wrote that first post I forgot that logic blocks generally won't be supported going forward from v6. So this version removes all references to logic blocks and simplifies the tools into self contained blocks that do not require anything else to function.

There are two types of Fault Checker blocks, both are 1x1 clickable button type objects and look like the existing Switch block with a capital letter printed on top, "T" is for throughput whereas "C" is for compression. Fault checkers can accept incoming belt connections from any side and function like an inverted sorter set to "none", that is to say any item belted into it can only exit from the opposite side. It is possible to route two belts through in perpendicular directions but generally speaking you'd want to give each belt it's own.

To use a fault checker all you have to do is feed a belt of any colour into it and out the other side, items will then flow through the block without losing any speed. When the speed and compression of items on the belt reach the maximum for that belt colour, the button will turn green. What happens next depends on the type that you use:

- A Throughput fault checker measures the movement of items through the block and out the other side. If at any point items on the belt stop moving the button will "pop up" and turn red to indicate a fault, in this case a bottleneck that prevents the full throughput from flowing through the belt. The flow of items through the fault checker will not be impeded even if the button is red.

- A Compression fault checker works much the same way, the triggering fault condition is if items on the belt lose full compression. When a compression fault checker is placed within the radius of an overdrive module it will account for the boosted belt speed in it's calculation to ensure that the belt will remain fully compressed even if it loses overdrive before reaching it's final destination.

Once a fault checker turns red you can simply click on it to reset the button, which will first go back to grey and then green when full throughput returns. Essentially it works like an undervoltage circuit breaker, but instead of cutting the circuit it just throws up a warning flag.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Fault checkers have two main uses. You can place them at the input and output of any given factory to determine if:

1. A factory is consuming 100% of it's inputs and thus not wasting any throughput
2. A factory designed to output a full belt is properly achieving full compression.

Is is difficult to do this by eye because gaps on the belt and momentary pauses in the flow might be so slight that you can't make them out. This is especially true with belt corners or overdrive fields that accelerate items on the belt and create gaps between them. There are also instances of graphical glitches where fully compressed belts will display gaps that "stretch" open and then disappear further down the line which are even harder to diagnose. 

So having a specific tool block to handle this sort of testing for us would eliminate the possibility of user error because being blocks themselves they can measure game data directly. This also lets you test an expansive system and find faults without having to actively be there staring at the belts.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by gregorynikif** [comment]
So, correct me if I am misunderstanding your request, you want a feature to remove all the clunky things that make most players strive for perfection?

**Comment by Tamren** [comment]
Huh? I don't get what you mean.

What "clunky things" are you referring to here? The inability for players to accurately measure if a belt is performing at 100% of capacity is "clunk"? The inability to do this is what drives players to strive for perfection?
