### ISSUE TITLE
Add tutorial and story

### ISSUE THREAD

**Issue by Nunting** [Anuken/Mindustry-Suggestions#3449]
### Describe the content or mechanics you are proposing.

1. add Tutorial
2. add story-line

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**<tutorial>**
1) arousing interest in games
2) adaptation of new users

Tutorials are needed for those who are new to this field. It is one of the simplest ways to show what the game's characteristics are and how interesting it is in a short time. 
Description of the basic ui, goal of this game, simple story, how to operate, building type, etc.

Currently, v6 is very unfriendly to new users. There's a tip on the left side of the screen? This is not enough explanation for the game. Holding cores, drills, and very basic buildings does not motivate them to play this game for a long time. 

We need a very intuitive explanation. Whether it's a new player, old or young, at least there should be something that people who are new to this field can feel the charm of "mindustry."

At the very least, few people will be able to feel the great attraction of Mindustry by looking at the current Ground zero.

**<storyline>**
1) Return of old users who are not interested in the game
2) Added to the charm of Mindustry

Of course, the story still exists today. like a scrawling note. 

The story is very important. This is because it is a very important factor that makes you feel its charm regardless of its completeness. If the tutorial is a device to attract new users, the story is the driving force behind all users to stay in the game. Like insects gathering in bright light.

The elements required for the story are as follows :
_- Why did we arrive here? 
- Who is the enemy?
- What is the background of this game? (A device to increase immersion. Whether it's the future or the distant past. It doesn't matter if it's not related to reality)
- What happened before we lost all our skills?_

We can regain lost technology by occupying the map named in the campaign. If you explain it well in combination with the story, I think you can increase the user's immersion. (In more detail than now!)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LeoSko** [comment]
It was discussed before with no response from Anuke iirc.
Yes and yes, please let's explore the way to make learning curve more user-friendly.

**Comment by gregorynikif** [comment]
I kinda like it the way it is. Tutorials are sometimes forcing you to do things that you don't want to do like that, when YOU play, and somebody can easily be annoyed by it. Whether it's a different order or different ways of doing things. If you leave it up to the user to do whatever he/she wants then trial and error can be a positive factor. "Learning things the hard way". Also known as "freedom to make mistakes".

**Comment by oinkymoo** [comment]
a better tutorial has been suggested many times before, and story does already exist, primarily in the form of campaign sector descriptions

**Comment by nonatee** [comment]
one thing i like about mindustry is the ambiguity. You do not know how or why you are there, the only thing you do know is you must survive.

**Comment by Sector171** [comment]
Yeah sure, he went for V7 with new units and mechanics before developing these two components: 1- real story 2-real tutorial, it is better for sure if he made them first.

> and story does already exist, primarily in the form of campaign sector descriptions

Are you serious?? do you consider this "description" as a story!! by the way i have just finished the campaign again and i almost  noticed it, it is not a story but more info about the sector.
Till this moment i don't know who is the enemy, is it alien? is it illegal company? what is Serpulo? ...etc
By the way, there is no need for movie and designing picture when developing the first version of the story since it requires designers and huge effort, all needed is consistent text explaining the story and only in focal(named) sectors, so it is simple task. for example:
When the player start playing the campaign, before launching to Ground zero, showing a text above appropriate background image and sound effects with 2 buttons : skip and next:
"Time : 2099
place: xxxx
the Crux's company lost the competition against xxx company which gained the exclusive mining rights in Serpulo, the rich planet in "Alpha Centauri" solar system.
Crux's owners didn't believe or accept their lose, and began to make their evil plan and...."etc
And in each named sector the same, describing what happened there, its importance...etc.

**Comment by oinkymoo** [comment]
There’s certainly enough story for people who are interested to try and fill in the gaps

**Comment by LeoSko** [comment]
> There’s certainly enough story for people who are interested to try and fill in the gaps

More like a single huge gap which is absence of a story as a whole.

**Comment by Nunting** [comment]
> 있는 그대로가 마음에 듭니다. 튜토리얼은 때때로 당신이 플레이할 때 그렇게 하고 싶지 않은 일을 하도록 강요하고 누군가는 그것에 쉽게 짜증을 낼 수 있습니다. 그것이 다른 순서이든 다른 일을 하는 방법이든. 사용자가 원하는 대로 하게 하면 시행착오가 긍정적인 요인이 될 수 있습니다. "힘들게 배운다". "실수할 자유"라고도 합니다.
> 
> 편집: 이야기에 관해서는... 행운을 빕니다. 저는 스토리를 잘 만드는 편은 아니지만 아무리 노력해도 바닐라 민더스트리 캠페인에 맞는 스토리는 상상조차 되지 않습니다. 다시 말하지만, 그것은 당신이 자신의 속도로 일을 할 수 있는 자유에서 멀어지게 합니다.

We can solve it in the sandbox. However, tutorials are for "new" people. Advice and minimal rules allow you to adapt quickly to all areas. Think of a game without a tutorial. You have to ask and look for it yourself. There will be more people leaving than . 

> I kinda like it the way it is. Tutorials are sometimes forcing you to do things that you don't want to do like that, when YOU play, and somebody can easily be annoyed by it. Whether it's a different order or different ways of doing things. If you leave it up to the user to do whatever he/she wants then trial and error can be a positive factor. "Learning things the hard way". Also known as "freedom to make mistakes".
> 
> Edit: As for the story...good luck. I am not one to make good stories but, no matter how much I try, I cannot even imagine a properly fit story to the vanilla Mindustry campaign. Again, it strays you away from freedom to do things at your own pace.

However, tutorials are for "new" people. Advice and minimal rules allow you to adapt quickly to all areas. Think of a game without a tutorial. You have to ask and look for it yourself. There will be more people leaving than adjusting.

Story is an additional device. It's not essential, but if you have it, it can have a more positive effect. 

Many people are attracted to the "Mindustry" they are today. But that's not a lot. In order to attract more people, various devices should be provided for newly introduced players. I don't think it's enough now. I think this game is attractive enough, but there are more people who quit right away without knowing the value of it. I don't want this game to become a frog that lives only in a well.

**Comment by Nunting** [comment]
Oops

**Comment by EclipseTheOldOne** [comment]
> > I kinda like it the way it is. Tutorials are sometimes forcing you to do things that you don't want to do like that, when YOU play, and somebody can easily be annoyed by it. Whether it's a different order or different ways of doing things. If you leave it up to the user to do whatever he/she wants then trial and error can be a positive factor. "Learning things the hard way". Also known as "freedom to make mistakes".
> > Edit: As for the story...good luck. I am not one to make good stories but, no matter how much I try, I cannot even imagine a properly fit story to the vanilla Mindustry campaign. Again, it strays you away from freedom to do things at your own pace.
> 
> However, tutorials are for "new" people. Advice and minimal rules allow you to adapt quickly to all areas. Think of a game without a tutorial. You have to ask and look for it yourself. There will be more people leaving than adjusting.
> 
> Story is an additional device. It's not essential, but if you have it, it can have a more positive effect.
> 
> Many people are attracted to the "Mindustry" they are today. But that's not a lot. In order to attract more people, various devices should be provided for newly introduced players. I don't think it's enough now. I think this game is attractive enough, but there are more people who quit right away without knowing the value of it. I don't want this game to become a frog that lives only in a well.

lore aren't getting worked on *yet*
and also, the tutorial is removed before, replace with in-gameplay tips
