### ISSUE TITLE
Fungal Pass vs Salt Flats play order

### ISSUE THREAD

**Issue by dvrabel** [Anuken/Mindustry-Suggestions#345]
The current campaign tree suggests that Salt Flats is easier than Fungal Pass because:

1. It's lower down the tree.
2. It requires the destruction of only 1 enemy core instead of 2.

However, having played Salt Flats and then Fungal Pass, Fungal Pass is considerably simpler. Fungal Pass's easier defense, weaker enemy base and linear progress through the map makes for an easier map to learn about building/managing bot swarms to attack. Fungal Pass seems designed to be the introductory level to base attack missions (and I think it works well at this).

I would suggest:

1. Moving Fungal Pass to between Ruinous Shores and The Craters (and depending on completing these to some wave).
2. Keep Overgrowth dependant on Fungal Pass and Stained Mountains.
3. Remove Titanium resource from Fungal Pass (so player can focus on building bots and not learning about titanium or technology unlocked with titanium).
4. Move Salt Flats next to Tar Fields/Overgrowth.
5. Make Salt Flats depend on defeating the core in Fungal Flats.

**Comment by DeltaNedas** [comment]
won't apply for 6.0
