### ISSUE TITLE
Blast Bombing Nerf

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#3450]
### Describe what you would like changed, and why.

How fair was it, to just skip attacking all the enemy defenses and just workaround and suicide to destroy the core? Surely Anuke didn't design blast bombing for this purpose. 

It also, kind of makes PvP rigged, because of its power to eliminate cores easily, with the help of ubind logic.

I suggest nerfing blast compound/explosive bombing, because in an instant, you can kill almost every attack base you encounter in campaign. 

### Describe the changes you want to propose. Include possible alternatives.

Maybe we can:
1. Add additional counters for blast bombing, like for example, waves and tsunamis can remove item abilities to wreak havoc, etc. 
2. Making unit destruction hitbox weaker, especially for zeniths, because zenith blast raids can tank most of the hits, and will not explode even with plastanium defense. Making the host unit explode faster is a good nerf. 
3. Nerf explosive bombing by reducing its effective damage by 30-50%. It might seem a lot, but trust me, it can still keep up with the meta.

What do you think? Does any of these solutions help cancelling the meta?

**Comment by LeoSko** [comment]
Ranked PvP (v6) has several counters which seem to be efficient so far, might be a good idea to transfer then into vanilla game:
- wet/freezing effect significantly reduce explosiveness of carried items
- if you shoot the killed mid-falling for additional 1/4 of initial HP, unit it doesn't do *any* damage (no falling nor items)
- bombing has reduced cap damage (basically v7 code)
- force projectors reduce bombing damage x5 times
- all bullets have x5 knockback - especially visible in wave/tsunami

**Comment by EclipsePlays** [comment]
Yes, and still, it can fight with meta strats and emerge victorious at times...

**Comment by oinkymoo** [comment]
it has already been nerfed by making core vaults less volatile

**Comment by OnyxFinger** [comment]
> it has already been nerfed by making core vaults less volatile

and it's not nearly enough
In fact, since placing vaults near core was a bad idea before the "nerf", noone with a brain did it, but hold on, blast bombing was too strong. So if I connect the pieces, I can suddenly tell that the nerf didn't nerf anything
In fact, it's more like a vault buff, because they're actually usable now, without the constant threat of one unit falling on it, destroy your entire core

**Comment by EclipsePlays** [comment]
Rememer the fact that nearly 5 zentiths loaded with blast compound can eliminate a nucleus in a point black range upon death

**Comment by EclipsePlays** [comment]
And having a small group of blast bomb air raiders could mean death.

**Comment by mvrak** [comment]
Are you recommending this solely for PVP game length?  Is it unrealistic to prevent the bombers from getting to your core?

**Comment by EclipsePlays** [comment]
> Are you recommending this solely for PVP game length?  

No, have you tried using blast bombing in campaign? Takes out the fun and thrill. Instead of finishing the map manually, you just workaround the defenses and kill the core easily. Is it fair?

**Comment by end-me-please** [comment]
v7 blast bombing feels different somehow
not as effective as it used to be
