### ISSUE TITLE
Disassembler Slag Input

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry-Suggestions#3451]
### Describe what you would like changed, and why.

Make disassembler input look better.
Why 7.1/s instead of 8/s or 7.5/s?
![IMG_20220320_133359](https://user-images.githubusercontent.com/85320516/159149748-60c4cdd2-31fb-4625-a3a0-6a195aa28840.jpg)

### Describe the changes you want to propose. Include possible alternatives.

Turn disassembler slag input to;
- 8/s, to make it pair with separators, in multiples of 4,
- or 7.5/s, ir you need more slag storage.

**Comment by stuffyAI** [comment]
> Make disassembler input look better.
> Why 7.1/s instead of 8/s or 7.5/s?

That is no real reason for a change.

Also, remember that you get latency issues especially with liquids during multiplayer, having 8 slag/second and consuming 8 slag/second likely doesn't result in 100% efficiency.

**Comment by EclipsePlays** [comment]
> > Make disassembler input look better.
> > Why 7.1/s instead of 8/s or 7.5/s?
> 
> That is no real reason for a change.
> 
Then why was separators adjusted to 4/s if there's no real reason?

> Also, remember that you get latency issues especially with liquids during multiplayer, having 8 slag/second and consuming 8 slag/second likely doesn't result in 100% efficiency.

And that also applies to separators at 4/s you know...

**Comment by stuffyAI** [comment]
>Then why was separators adjusted to 4/s if there's no real reason?

If I recall correctly that was to make scrap to impact schematics more desync-tolerant (as it gives more titanium per scrap).


> And that also applies to separators at 4/s you know...

That is cool, but there is no reason to nerf Disassemblers though?
