### ISSUE TITLE
Less Useful Logic equivalent for the V7 Planet

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3453]
### Describe the content or mechanics you are proposing.

The addition of V7 Planet equivalent logic blocks, either in an alternative use or mainly for decorative/fun purposes.

These blocks use different materials for use, and run faster (×1.5 Instructions/sec). They can detect units only if they have a specific block for it, and they cannot control turrets or other combat-related utilities (force projector, mending, unit factory & reconstructor).

V7 logic memory cells would contain less spaces (×0.5), while also enabling use of more value types (such as Strings), making this type of memory cell more reliable in terms of data. The type of memory cell however cannot hold Floats.

V7 logic displays have less pixels (×0.5) but they are also smaller than normal logic panels. Good for usually tight spaces.

V7 logic messages get more space... and thats it.

In exchange, this set of V7 logic blocks will have one or all of these traits:

- A much more Assembly-like interface
- Not paste-compatible with V6 logic blocks
- Can be accessible outside of campaign so long as you happen to have the materials for it
- Can be linked to V6 logic blocks to make use of the new benefits (especially in Sandbox mode)
- Processors have a bad reaction to being overclocked by Overdrives (depending if Reactor Explosions is enabled)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It allows players who previously used logic blocks in the first planet to continue using Logic, while also making logic unreliable for cases that often resulted in Logic paving the way for almost every scenario, to the point of making everything wireless. Heck, I bet someone even made an automatic AI that builds the conveyor belts for you and optimally place drills.

Disabling unit control, or every unit-related instruction, will likely fix the predicament of logic blocks taking the scene everywhere.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Why add a system that has for only difference a few stats the UI ? If Anuke didn't add logic, he won't add this?.

**Comment by Bassem-Const** [comment]
We already have non-logic based unit transport in v7.

**Comment by Bassem-Const** [comment]
> We already have non-logic based unit transport in v7.

The private branch.
