### ISSUE TITLE
Folders in schematics

### ISSUE THREAD

**Issue by Juanchoperezlol** [Anuken/Mindustry-Suggestions#3456]
### Describe the content or mechanics you are proposing.

Be able to create folders in schematics. While using the search bar is very useful when having lots of schematics, I belive that being able to organize it in folders could facilitate the order and quickly finding that one schematic that you dont remember its name.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Could be useful when advanced players have lots of schematics and would like to organize them arbitrarely within its function, stage of the sector, etc

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Tags exists. Use them.

**Comment by PrintGlue** [comment]
You can do the same actually in the game. Just different way.
