### ISSUE TITLE
Siege mech?

### ISSUE THREAD

**Issue by Mechanicalenhancement1** [Anuken/Mindustry-Suggestions#3457]
### Describe the content or mechanics you are proposing.

I dont know If you know of the game starcraft, within that game there is a unit known as the siege tank. Whilst mobile it has a relatively weak cannon attack, however when in siege mode, it is immobile but with a frighteningly dangerous aoe artillery cannon. 

My sugestion is of a simmilar unit. A mech that can "siege up" and fire dangerous shots far away, but vounrable whilst in this mode. It could also bennifit from the new more animated weapon systems that you all wish to impliment. And whilst mobile it can shoot moderitely damaging wepons like a small gatling gun.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It can provide a uniqe stratagy that even the AI could bennifit from. Showing players that even though short range turrets like the arc are good, they may need a long range turret to ensure safty. The unit could even target lesser defended walls to make players think on their toes when suddenly one sieges up near an undefended wall.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
sounds similar to corvus, corvus cant move while shooting

or vela, which is unable to fly when firing

**Comment by Mechanicalenhancement1** [comment]
That is true however, I wouldnt realy say the corvus sieges up

**Comment by OnyxFinger** [comment]
I think that if it isn't a high tier unit, a similarity with corvus isn't a big deal. However, Anuke generally prefers to add his own content for understandable reasons
