### ISSUE TITLE
Underground system, new ores

### ISSUE THREAD

**Issue by OrangoMango** [Anuken/Mindustry-Suggestions#3458]
### Describe the content or mechanics you are proposing.

I suggest to add a new "world" underground (maybe a second layer that you can access via some open canves on the surface) where you can find new ores and you can bring them to the core with minecarts.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content addition, may give more space to build and a better way to play. Maybe you could add new underground biomes and drills.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OrangoMango** [comment]
I didn't read the README sorry

**Comment by RealYeet** [comment]
Honesty is a great trait to have.

**Comment by OrangoMango** [comment]
Yes, idk why @Anuken does not want to add this
