### ISSUE TITLE
Flare Targeting

### ISSUE THREAD

**Issue by Dat-Guy** [Anuken/Mindustry-Suggestions#3459]
### Describe what you would like changed, and why.

Currently, flares target whatever power generator is closest to their spawn. This allows for building a single steam generator in the middle of my air defenses, which causes them to route directly into them.

### Describe the changes you want to propose. Include possible alternatives.

Have flares target the closest active power generator. Optionally also have them select for the most valuable target (i.e. Impact -> Differential -> Thorium...), in order to either have defenses incorporate power generation, have players strategically position power generation, or build additional defenses to counter flares.

**Comment by PrintGlue** [comment]
Actually, combustions are better for this function ;)

**Comment by RealYeet** [comment]
I want to support this but I will end up uninstalling the game due to pure rage from flares.
