### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by LequartzV5** [Anuken/Mindustry-Suggestions#3460]
### Describe the content or mechanics you are proposing.

I suggest a new conveyor item : surge rails. It's like a mix between the titanium rail and the plastanium rail. You will be able to choose which item do you want for the rail to conpact (like the plastanium conveyor). The rest of the items will act normal (like the titanium rail). If you choose nothing, everything will act normal.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

For exemple, you have phase fabric, plastanium and silicon from silicon crucible (so it output 8), and all goes in one conveyor to the core. The silicon block the phase fabric and the plastanium 'cause there is too much silicon. You add surge rails and you select silicon and the silicon will not block the rest anymore. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
> For exemple, you have phase fabric, plastanium and silicon from silicon crucible (so it output 8), and all goes in one conveyor to the core. The silicon block the phase fabric and the plastanium 'cause there is too much silicon. You add surge rails and you select silicon and the silicon will not block the rest anymore.

you can kind of just use multiple different conveyor lines right ?

**Comment by PrintGlue** [comment]
I think this can be solved just by this.
![incinerator](https://user-images.githubusercontent.com/102457574/160271717-3de828ba-43bc-4b19-ac5e-b7dae7cfda6f.png)
