### ISSUE TITLE
Remake of the Atribute

### ISSUE THREAD

**Issue by PrintGlue** [Anuken/Mindustry-Suggestions#3461]
### Describe what you would like changed, and why.

The idea is that attribute system will be remaked. Its just too complex right now and it can be really easy done.

### Describe the changes you want to propose. Include possible alternatives.

Instead of making attributes in here: https://github.com/Anuken/Mindustry/blob/2167a3d7fe4fc6b78c3b63c57669f36dc89b8035/core/src/mindustry/world/meta/Attribute.java

and writing them into floors.

You would make them into blocks.

for example like this:

        waterExtractor = new SolidPump("water-extractor"){{
            requirements(Category.production, with(Items.metaglass, 30, Items.graphite, 30, Items.lead, 30, Items.copper, 30));
            result = Liquids.water;
            pumpAmount = 0.11f;
            size = 2;
            liquidCapacity = 30f;
            rotateSpeed = 1.4f;
            attributes = [ice, 25, snow, 12]
            envRequired |= Env.groundWater;

            consumes.power(1.5f);
        }};
        
Alternatively you could do this in scripts and then inputting this into hjson, but its really too complex if you can just do it like this. Yes i want this feature for modding.

**Comment by itcannotbe** [comment]
But why? The why part hasn't been answered.

**Comment by PrintGlue** [comment]
oh, didnt notice that that was here.

**Comment by BlueWolf3682** [comment]
why not just make attributes JSONable? seems like a mildly complicated thing to use

**Comment by PrintGlue** [comment]
I agree.
