### ISSUE TITLE
Yeni bir blok önerisi

### ISSUE THREAD

**Issue by yenilmes** [Anuken/Mindustry-Suggestions#3462]
### Describe the content or mechanics you are proposing.

blokları veya birimleri görünmezleştiren bir blok. Eğer görünmez blok canı %90 dan az ise görünüre yakın olabilir.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Bu blok türü oyuna eklendikten sonra oyuncular neyin nerde nasıl olduğunu anlamaz bu yüzden herhangi bir birlik göndermek veya oraya zarar göndermek zorunda kalırlar öğrendiklerinde nasıl saldırı yapıcaklarını düşünürken karşı rakip oradaki silah ve birimlerin yerlerini değiştirir normal takım ise saldırır ve belki bu yer değiştirmeden dolayı yenilgiye uğrarlar.

Aslında nasıl açıklayacağımı bulamadım ama oyuna nasıl bir etki değişim olduğunu anlattım okuduğunuz için sağolun.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Translated:

> Describe the content or mechanics you are proposing.
>
> a block that makes blocks or units invisible.  If he has less than 90% invisible block health, he can be close to visible.
>
> Describe how you think this content will improve the game.  If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

> After this type of block is added to the game, the players do not understand what is where, so they have to send any troops or send damage there.
>
> Actually, I couldn't find how to explain it, but I explained how the game has an effect and change, thank you for reading.

No.
