### ISSUE TITLE
Mücadele de harita görebilme

### ISSUE THREAD

**Issue by yenilmes** [Anuken/Mindustry-Suggestions#3463]
### Describe what you would like changed, and why.

Arkadaşlarımla veya başkaları ile mücadele modunda oynarken o kişinin mücadele modundaki hangi sektörleri açık hangileri açık değil görebilmek böylece onlara öneride bulunabilirim .

### Describe the changes you want to propose. Include possible alternatives.

Kişilerin mücadele modunda hangi sektörlerinin açık ve hangilerinin açık olmadığını görebilmek isterim böylece onlara eğer şu sektörü ele geçirirsek iyi olur çünkü orada değerli materyaller var diyebilirim böylece onlara yardım etmiş olurum okuduğunuz için sağolun

**Comment by itcannotbe** [comment]
Translated:

> Describe what you would like changed, and why.
>
> While playing with my friends or others in combat mode, I can see which sectors in that person's combat mode are open and which are not, so I can make suggestions to them.
> Describe the changes you want to propose.  Include possible alternatives.
>
> I'd like to be able to see which sectors of people are open and which are not in combat mode so I can tell them if we take that sector it's good because there's valuable material there so I can help them thanks for reading

This isn't even supported as the sector that aren't opened are just being "calculating chances", not running an actual sector.
