### ISSUE TITLE
Wind turbines

### ISSUE THREAD

**Issue by Digstructer** [Anuken/Mindustry-Suggestions#3466]
### Describe the content or mechanics you are proposing.

You know what a wind turbine is

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Produces more power and more compact than large solar panel but you can only build within a certain radius from other wind t. Good for a fast power source when coal is not in inventory or ore is in an inconvenient location. Be useful for jump starting water extractors and cryofluid mixers, be also useful for powering isolated drills without taking too much space :)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
See discussion:

https://github.com/Anuken/Mindustry-Suggestions/issues/472

**Comment by OnyxFinger** [comment]
You know what a solar panel is.
