### ISSUE TITLE
Evaluations for sector loss for a brand new sector should be suspended at least until the wave 1 timer completes

### ISSUE THREAD

**Issue by mvrak** [Anuken/Mindustry-Suggestions#3467]
Might be considered more balancing/feedback, your call.

**Evaluations for sector loss for a brand new sector should be suspended at least until the wave 1 timer completes**

In conquering Serpulo, the game encourages, or even mandates, that you set up a distribution network to launch resources around.  
When conquering a new territory, it is logical to start launching resources to that new territory.
Multiple times this happened:
I will land, spend 60 seconds setting up basic defenses, then switch to a base to launch resources back to the new sector.
I take no more than 30 seconds at that base, yet often the sector I just launched to will be gone.  No notice and no message.  

Before I left the sector, it said I had at least minutes before wave 1.  

So the feature request is that evaluations for sector loss should be suspended at least until the wave starts.  At least the wave 1 timer should be respected.

Now that I realize how it works I realize three things: 
1) This will happen to many players, and probably multiple times.  Few have the background to figure out how the system is evaluating sector loss.

2) I can cheese holding a sector by abusing the units that contribute to sector defense, regardless of how the defenses actually look on a map.  The random sector loss is the problem that made me realize this, not the fact that an estimate is used.

3) There is no mechanism that feels good to safely redirect my "main base" or other sectors to your current location.  If I do it with time stopped the resource income does not seem to be calculated correctly.  If I do it with time active, I run the risk of complete sector loss.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Solution would make the game feel more fair, and align the out of sector estimates with the player's perception of reality.
Solution would not increase performance overhead, as tracking the wave 1 timer is only tracking a single time concept.

I looked through the bugs, and while this seems to be reported as a bug, the reply was often "Duplicate" and I could not find what it was referring to.  Instant sector loss seems to come from the same thing, an evaluation of the threat level vs an estimate of the players defenses.  I am not proposing a change to that mechanism, just a suspension during the initial setup phase timer.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
I must mention that launch pads **do not** make the game feel fair, as they are too powerful. The correct method of balancing launches is to remove them and rethink how resources generate on Serpulo.

**Comment by mvrak** [comment]
There are a number of sectors that are just empty and lifeless. Launching resources back to sectors and building them up is.. to me... an interesting mechanic that breathes life into Serpulo.  Some extreme threat maps rely on a large influx of resources.

**Comment by Sector171** [comment]
I have rushed the campaign again few weeks ago just to see how it will look, actually good things we already suggested got added, like "from sectors" and "to sectors", so you know what's going on(which sectors export to which sectors without entering any of them, from planet's view).
But I was disappointed that the ability to change launchpad's target sector without entering that sector but from info page haven't added yet! That was so annoying.

**Comment by Neil2101** [comment]
> I must mention that launch pads **do not** make the game feel fair, as they are too powerful. The correct method of balancing launches is to remove them and rethink how resources generate on Serpulo.
> 
> As much as I agree with the sector attacks being jank as hell, I feel like that's more "you should be spending the first few waves on-site".

personally, some sectors will be missing reasources, and you would like to send reasources to supply your needs for stuff...

**Comment by kc7zzv** [comment]
> I must mention that launch pads **do not** make the game feel fair, as they are too powerful. The correct method of balancing launches is to remove them and rethink how resources generate on Serpulo.
> 
> As much as I agree with the sector attacks being jank as hell, I feel like that's more "you should be spending the first few waves on-site".

I somewhat disagree.  I think you really mean that launching resources into a contested zone is too powerful.  Even if they're removed for contested zones, I think they should be allowed for uncontested zones, so you can send in that little bit of phase alloy to create a disassembler.
