### ISSUE TITLE
New Small 3.5/Classic Planet

### ISSUE THREAD

**Issue by KukkelIkuU-00** [Anuken/Mindustry-Suggestions#3468]
### Describe the content or mechanics you are proposing.

Mindustry 3.5/Classic is an amazing game. That's why it would be cool to see 3.5 mechanics (resources, buildings, maps, units) in new Mindustry. Here are some ideas of the planet:
-Small planet (All the buildings are small and thereore maps can also be small. Also because 3.5 doesn't have that much content compared to new Mindustry, there are also less sectors. Kind of side quest.)
-3.5 mechanics, materials and buildings (I read from the README.md about suggestions. There is a section "No Teleporters". 3.5 Includes them :|)
-Attack maps (3.5 with new attack mode is very cool and it would be magnificent to attack classic style)
-Units can be the old 3.5 units and made with old v6 style or with the new style.
-Player still can be flying unit, so building is easier

Overall the idea is new **small** planet, where you can play modern 3.5 Mindustry

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

3.5 is **magnificent** and it would be very sad to leave it. Mixing modern Mindustry with old one would be an amazing experience. And if somebody doesn't like Classic Mindustry but still wants to 100 % the game, worry not. Because of all the smallness, it's not that big of the deal to complete it. But everybody loves 3.5 so that will never happen :)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> There is a section "No Teleporters". 3.5 Includes them :|

Teleporters are unbelivably overpowered and unbalanced, hence their removal.

If they weren't removed, multiplayer would be completely fucked over. And singleplayer would practically become boring, since the motivation pain-filled suffering would be nonexistent.
