### ISSUE TITLE
activity "throttling" for damaged blocks 

### ISSUE THREAD

**Issue by Remint32** [Anuken/Mindustry-Suggestions#347]
I suggest slowing down the speed of the block's activity in direct proportion to its damage.
This will add a greater need for repairs and introduce new mechanics for damaged, but over-drived buildings. In the end, it's just logical that a damaged building is malfunctioning.

Activity doesn't have to fall to zero, but it should decrease significantly.

**Comment by ILiekMelons** [comment]
turrets start losing accuracy the more they are damaged maybe 👁️

**Comment by SupremeTurtle** [comment]
Menders are incredibly useful, especially with multiple of them. This indirectly makes them even more essential than it is, so in addition maybe nerf the menders.

**Comment by Remint32** [comment]
> 
> 
> Menders are incredibly useful, especially with multiple of them. This indirectly makes them even more essential than it is, so in addition maybe nerf the menders.

Conversely

**Comment by Anuken** [comment]
Rejected, see PR.
