### ISSUE TITLE
Logic rebalance rather than tossout

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#3470]
### Describe what you would like changed, and why.

Noticed you were trying to get rid of it, been thinking hard about it for a while now and came up with 2 alternatives that take away or nerf the op parts(flare rush, poly viruses) but leave the general contraptions(logic games, displays) pretty much unaffected

### Describe the changes you want to propose. Include possible alternatives.

The two methods are a limit on instructions per tick and a range based limit. Which you choose, if both even, is up to you

First method is a limit to instructions per tick based on processor, such as the small one being only 1 a tick and large being 3 a tick. this INCLUDES individual instructions per unit rather than all unit instructions at once. this will limit versatility in mass unit swarms or absurd complex unit item networks in favor of more traditional ones via resource cost and general usability. this will not affect simple things like displays but may lead to semi slower logic game creations.

The second method is a range based limit on units, unbinding the unit if out of range. Either range from processor, or range of processor from any allied building. This will completely halt any sort of suicide flare logic and require item networks to have serious infrastructure that can be countered in a multiplayer or attacked sector setting. While this should not have any affect on display or games in logic, it will have quite the impact on unit controllers or custom unit AI. A structure based one instead of a processor based one seems a bit more lenient than an outright cap.

**Comment by itcannotbe** [comment]
You haven't read the edit in the steam announcement hsve you?

**Comment by itcannotbe** [comment]
> First method is a limit to instructions per tick based on processor, such as the small one being only 1 a tick and large being 3 a tick. this INCLUDES individual instructions per unit rather than all unit instructions at once. this will limit versatility in mass unit swarms or absurd complex unit item networks in favor of more traditional ones via resource cost and general usability. this will not affect simple things like displays but may lead to semi slower logic game creations.

There is already a limit.

**Comment by itcannotbe** [comment]
> The second method is a range based limit on units, unbinding the unit if out of range. Either range from processor, or range of processor from any allied building. This will completely halt any sort of suicide flare logic and require item networks to have serious infrastructure that can be countered in a multiplayer or attacked sector setting. While this should not have any affect on display or games in logic, it will have quite the impact on unit controllers or custom unit AI. A structure based one instead of a processor based one seems a bit more lenient than an outright cap.

This will just not work.

**Comment by end-me-please** [comment]
if you don’t know how to defend against flare rush
you deserve to lose against it

**Comment by Anuken** [comment]
Erekir doesn't have logic because it's a flawed concept, not because it's necessarily overpowered.

**Comment by Ribbons0121R121** [comment]
i feel like something should be done about it rather than tossed out because its flawed. if its flawed why not try to fix it somehow?

**Comment by itcannotbe** [comment]
You can't fix a flawed concept.
