### ISSUE TITLE
The more the better

### ISSUE THREAD

**Issue by Bludstonian** [Anuken/Mindustry-Suggestions#3471]
### Describe the content or mechanics you are proposing.

Sat, April 2 2022
8:32 am

ALright I'm a super fan of mindustry and I have some suggestions like adding a few miner ores along with some  technology. So I'm thinking a great thing for the community is the addition of one of the stronger metal like iron, texhnium especially,or tungsten. Also I've notice some major wait time on updates on mobile even when it's already been released for about a week on average, what I mean is I can't get the 129 update. Now the buildings of which I'm thinking are a coal to oil machine and or a slag to scrap. Along with a larger ranged mass driver or more conveyors and make it to where the impact REACTOR can over heat and explode which could make it a bit hard to keep functioning. Now this is a superb idea 2 more naval troops like a ship like crawler line and a ship like corvus line. Also the addition of a kamikaze plane line would suffice grandly as well. 

                                                                                   Sincerely,
                                                                               Bludstonian

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content will most indefinitely bring some harder(fun) mechanics as well as revitalizing some old ones. The units will bring some spice to battle ground along with having to different materials like the new ores I talked about. The new buildings and conveyors can give a massive amount plausibilities to the factory aspect of the game. Thank you for your time, bludstonian.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
iron and tungsten existed in Mindustry classic
Naval support units exist in v7

and why would you need coal to oil, you can literally make oil out of thin air

**Comment by Bludstonian** [comment]
Well what I meant was with naval units there's only one line of them. And materials I wish could be added in to the regular mindustry the classic is fun yes but bring the classic stuff into regular mindustry would be epic and fun.
