### ISSUE TITLE
Shielded/Armored Walls

### ISSUE THREAD

**Issue by Markty07** [Anuken/Mindustry-Suggestions#3473]
### Describe the content or mechanics you are proposing.

Do you remember the armored wall in mindustry classic ? It was an expensive 1by1 titanium wall that had a personal shield. It would be nice to see it comeback, maybe on serpulo, since there is an unit that also have a special shield.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Armored walls could block splash damage, like regular shields. It could also block shots that usually pass over walls (like ripple shots) but with an expensive energy price when spammed. Since splash damage is really annoying sometimes, i think it could be a better option than an energy shield in some situations. It could also replace energy shields on serpulo.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RFAC-Productions** [comment]
I think you meant the new planet. But yeah, I'd like to see it make a return.
