### ISSUE TITLE
plastanium router, junction, bridge, etc

### ISSUE THREAD

**Issue by tuopi27** [Anuken/Mindustry-Suggestions#3475]
### Describe the content or mechanics you are proposing.

versions of the junction, bridge, phase conveyor, sorter, inverter sorter, overflow gate, underflow gate, and possibly distributer that move entire batches from plastanium conveyors at once instead of breaking them down first. the router/distributer variants would move an entire batch instead of splitting it. everything will stay in its batches when traveling around. the plastanium junction could optionally allow both regular throughput and batched throughput at once, but i understand that may be dificult to code.

everything will cost small amounts of plastanium in addition to their regular build cost, and have some green bits (e.g. green corners) in order to visually differentiate them.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

As of current, plastanium conveyors are awkward and not all too useful. Since their throughput is alot higher than the routers, junction, sorters and bridge, a large akward schematic is required just to do this stuff with conveyors. Adding plastanium variants of these transport blocks that play with batches instead of individual items would greatly increase their ease of use.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
See discussion https://github.com/Anuken/Mindustry-Suggestions/issues/1809
