### ISSUE TITLE
tainted water (new liquid)

### ISSUE THREAD

**Issue by tuopi27** [Anuken/Mindustry-Suggestions#3477]
### Describe the content or mechanics you are proposing.

tainted water is a purplish liquid that is gotten from pumping tainted water or dark sand tainted water. it is very similar to water, and is used in the same things
it can be used to replace water:
as coolant, although it is worse than water
in multi-presses, cryofluid mixers and steam generators, but it requires more liquid per second than water
in the cutivator and oil extractor, in which it increases the efficiency
in the tsunami and wave, where it gives the spore slowed effect instead of wet

it can be put into a purifier, where, when powered, it will be turned 1:1 into regular water

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i just think it would be interesting that if pumping tainted water gave you actual tainted water instead of just normal water. having it be increase the efficiency of cultivator and oil extractor felt fitting for the spores too. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
Well, I believe the pumps and drills have filters. Otherwise, we would pump sandy water from sandy water tiles, we would drill stone/sand too when minimg copper etc.

**Comment by Tamren** [comment]
I suppose this idea could fit in. We already have scrap which has a multitude of uses, you can use it as cheap ammo, grind it up into sand and refine it into more useful resources. So dirty water is sort of "scrap water". You can spend energy to purify it into clean water, which is like grinding scrap into sand. This could be very useful and/or present a challenge on maps that lack good sources of water. You could then go further and refine the filtered impurities to get a mix of useful side products like oil.

Currently there's no easy way to have a building output more than one liquid, so I'd recommend making this a several step process. You pump or drill for dirty water as normal. Then you combine the water with a filtration material like sand, or maybe metaglass, which outputs clean water and dirty filter material. You can then incinerate the dirty filters or further refine them into useful materials like oil or spores, as well recycle some of the filter material.
