### ISSUE TITLE
more mines

### ISSUE THREAD

**Issue by tuopi27** [Anuken/Mindustry-Suggestions#3478]
### Describe the content or mechanics you are proposing.

the shock mine is somewhat of a useless block. its usefulness falls off very quickly. so, i propose more versions of the mine. here are some concepts:
frag mine: launches clusters of frag upon detonation, dealing extra damage. costs metalglass
incendiary mine: sets units that step on it aflame. costs pyrite

blast mine: 2x2, big damage in a large area. costs blast compound
surge mine: 2x2, expensive, and stuns units for a few seconds. costs surge alloy

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the shock mine really drops off in usability in later waves, and i think that stronger, more expensive mines could very much make up for this drop off in utility.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by numer99** [comment]
+1 aprove
