### ISSUE TITLE
Turret targeting

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#348]
**Describe the content or mechanics you are proposing.**
Armor in the new 6.0 unit system will make some turrets like Spectre have a more proper use, but the problem will be that it will still target the closest unit to it, ideally stuff like Spectre should target the strongest unit, and Cyclone should target crowds of units, that way they make the most out of their usage. The two methods I would think to add this would be each turret has a set targeting system, or each turret would have configurable targeting, but would have a default, though the latter would definitely be better (maybe even having different turrets have different options for targeting types, like Spectre has different options then Fuse).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This sort of system would make gameplay a lot easier and make it more practical to use something like Spectre over Fuse, turrets could be more specialized and it would define the turrets purpose better. Something like this would be great and probably not too hard to implement either.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
If you want better targeting, use a logic system or control turrets manually. I don't think turrets should be this smart by default.

**Comment by Syncinus** [comment]
I don't think they should be as smart as shown here, I just believe things like Spectre should target more armored enemies which is what it is specifically good at. I don't think turrets shoukd have targeting selections I think they should just have different targeting modes, and it will be annoying to use a logic system every time you want to use a turret like Spectre for it's intended purpose.

**Comment by itcannotbe** [comment]
The logic system can make them smarter.

**Comment by Anuken** [comment]
> I think they should just have different targeting modes

This is too complex. Blocks should not have configuration or UI unless there is absolutely no other good alternative. Again, if you want smarter behavior, you should implement that yourself with logic. It's only one block.
