### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Paradox0r** [Anuken/Mindustry-Suggestions#3480]
### Describe the content or mechanics you are proposing.

A tutorial featuring a PNGCharacter of sorts (Specifically Alpha-Chan) that directs you through a simple tutorial with explanations for how drills work, how the core works, how weapons work, how buffs/de-buffs work, how weather works, how the drop zone works, how the Tech Tree works, etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

For One, it may offer new players a more viable method to understanding the premise of the game.
For Two, It may offer the game a mascot opportunity. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by THEGAMER-10n** [comment]
As cursed as it may seem, this might work.

**Comment by littelcat456** [comment]
This.. Might actually be a viable choice.

But then, you’ve got the anti-weebs to deal with though.

**Comment by Bassem-Const** [comment]
Here's a like.

Also it feels a bit overwhelming for new players.

Bit-by-bit?

**Comment by Falling10fruit** [comment]
Many people will avoid anime. Maybe use a more normal mascot instead. But then that won't make any sense with the lore.

**Comment by TheGamer1002** [comment]
then, perhaps, we use the mega?

**Comment by Falling10fruit** [comment]
The anime or the real mega?

**Comment by TheGamer1002** [comment]
Real mega. Sorry, should have specified. The *real* mega’s the most helpful ship in the game. I didn’t even know that Mega-chan existed.

**Comment by Falling10fruit** [comment]
Oh.
Does lore also get included in this idea?

**Comment by TheGamer1002** [comment]
> Oh.
> Does lore also get included in this idea?

Anuke says he doesn’t want lore as of now, so perhaps just a basic tutorial.
