### ISSUE TITLE
Modify units command

### ISSUE THREAD

**Issue by Frozefront** [Anuken/Mindustry-Suggestions#3481]
### Describe the content or mechanics you are proposing.

Modify command: Adding new features like: Trace Route, Trace Patrol Route, Defend "X" point, Slightly modify the texture as the AI ​​route is quite obsolete....

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Due to the fact that the automatic unit mapping is not entirely reliable, especially when it comes to going through key points to destroy the enemy base

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
hol' up, how do you know this isn't a thing yet ?

also "defend X position" is already possible by telling units to go one place and never giving them commands again

**Comment by OnyxFinger** [comment]
> but that is by logic

No ? https://discord.com/channels/391020510269669376/513178557653188609/951587122253533224

> ...not to mention that several of those who also play are from another country....

What ? How is that relevant ???

**Comment by Frozefront** [comment]
> > but that is by logic
> 
> No ? https://discord.com/channels/391020510269669376/513178557653188609/951587122253533224
> 
> > ...not to mention that several of those who also play are from another country....
> 
> What ? How is that relevant ???

Yes, because so far the logic works only in English, I doubt that all the players from other countries will bother to thoroughly learn the English language in order to program the logic, I say. For example, I'm Mexican and I don't understand how to program logic, it's frustrating.
