### ISSUE TITLE
Logic: In-Game Text Editor

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3485]
### Describe the content or mechanics you are proposing.

An extension to Logic Editing where you can write in instructions, have proper syntax, and auto-correct in terms of getting instruction prefixes and variables. Unlike text editors, changes are applied immediately, and the editor shows any errors that are found.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allows players to have more control over sophisticated code and allows faster insertion of new code. People who can't work with lego blocks can instead use the text editor, which increases the speed of programming logic depending on the user.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I really have doubts that anuke will still be developing anything related to logic

**Comment by end-me-please** [comment]
this would be nice, but has some technical problems.
when importing code from clipboard it is parsed. all comments are removed and all jump labels converted to line numbers, making further editing only really possible with the in game editor.

not deleting comments/labels would increase processor memory use a lot. for multiplayer, the "source code" would have to be cached client side only. this sounds more like something a mod should do

(besides that, check out antigrief client, it allows you to paste code in the middle of other code without messing up the jumps, doesnt have a logic text editor though)
