### ISSUE TITLE
Auto Translation on Chat

### ISSUE THREAD

**Issue by Ruyeex** [Anuken/Mindustry-Suggestions#3488]
### Describe the content or mechanics you are proposing.

A feature that converts different languages (like russian) into your proposed languange in your UI (like english).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It could make communication more easier with other people from different countries.
Mostly for people who don't speak English or Russian.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
I think this should be a mod, rather than part of the base game.

**Comment by RealYeet** [comment]
_Just learn Russian_

**Comment by yozozchomutova** [comment]
Google has Java API for that, But issue is, that API is paid service....

**Comment by jacklolidk** [comment]
or just use any other translation service

**Comment by Pointifix** [comment]
https://github.com/Pointifix/AutoTranslate

**Comment by Ruyeex** [comment]
> https://github.com/Pointifix/AutoTranslate

Thank god for this mod
