### ISSUE TITLE
Specialist Air

### ISSUE THREAD

**Issue by blaster77145** [Anuken/Mindustry-Suggestions#3489]
### Describe the content or mechanics you are proposing.

List of proposed units, and their weaponry.

Perhaps sand as the additive constructive material this time?

t1 magma bomber, which is smart enough to try to avoid guns and basically be a more annoying flare,
a t2 firebomber, 
a t3 leecher with triple such lasers and a shield regen field,
a t4 dual goo launcher like you would find on an arkyid with dual sapping lasers, 
and the t5 a massive carrier craft with 4 segments and a shield.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe these will add interesting ways to play the game and more content. 
For example, using the magma/firebomber to light unstoppable fires under your enemies, the T3 like a slightly more powerful zenith, the t4 to take out a defense and the T5+T3 to create an unstoppable force of units. 

Note: this will probably need nerfing of some sort.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Massive carrier craft sounds a lot like a powerful oct ? Maybe the shield should get removed. I've been testing with oxynoes, and their segments are really bad, so I think that having 4 of them + strong offensive weaponry is justified for a t5 (I assume that "carrier" means that it doesn't pick-up air units, but produces them kinda like an omura or the drone swarm ability from early 4.0 builds, since actual aircraft carriers are blacklisted)

The t4 though is just an aerial arkyid.
Same problem for the 2 bomers, especially the t2 one : we already have a t2 bomber, even though it's different.

**Comment by blaster77145** [comment]
> Massive carrier craft sounds a lot like a powerful oct ? Maybe the shield should get removed. I've been testing with oxynoes, and their segments are really bad, so I think that having 4 of them + strong offensive weaponry is justified for a t5 (I assume that "carrier" means that it doesn't pick-up air units, but produces them kinda like an omura or the drone swarm ability from early 4.0 builds, since actual aircraft carriers are blacklisted)
> 
> The t4 though is just an aerial arkyid. Same problem for the 2 bomers, especially the t2 one : we already have a t2 bomber, even though it's different.

I believe these should take a lot longer to make and take more resources. However, your being up a good point, and I figure offensive equipment might be more appropriate. Maybe purple goo nukes, every once in a while?
