### ISSUE TITLE
Usefull hotkeys to choose blocks

### ISSUE THREAD

**Issue by salo2016** [Anuken/Mindustry-Suggestions#3490]
### Describe the content or mechanics you are proposing.

U has an weird defoult hotkeys at 1-9 key. Wouldnt they be much more usefull if u would make them be at 2 types
Category choosen by mouse (in what category of blocks player in) ---> 1-9 key choose a specific choosen block
Or
1-9 just choose specific block
Also if u do like u can make an "prefer" by clicking 1 key 2 times its select second (less priority like from titanium to copper conveyor,like drills graphite silicon fabrics and piratite).
Or other mechanic - fast choosing. Pressing choosen key open a menu where u just move ur mouse to top/bottom/right/left wich automatically choose a block. An operation wich allow choose on 1 hotkey 4 blocks. And takes less than a second.
Please... Do something with hotkeys :)
P.s. everywhere anygame social site named salo2016

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Building speed, keyboard become more usefull for speed building.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
> U has an weird defoult hotkeys at 1-9 key. Wouldnt they be much more usefull if u would make them be at 2 types
> Category choosen by mouse (in what category of blocks player in) ---> 1-9 key choose a specific choosen block

Pretty sure rebinds and adaption exists. Also; this makes no sense from my understanding.

> Or
> 1-9 just choose specific block
> Also if u do like u can make an "prefer" by clicking 1 key 2 times its select second (less priority like from titanium to copper conveyor,like drills graphite silicon fabrics and piratite).

?..

> Or other mechanic - fast choosing. Pressing choosen key open a menu where u just move ur mouse to top/bottom/right/left wich automatically choose a block. An operation wich allow choose on 1 hotkey 4 blocks. And takes less than a second.

??.

> Please... Do something with hotkeys :)
> P.s. everywhere anygame social site named salo2016

???

> Building speed, keyboard become more usefull for speed building.

It'll become just as fast with experience, albeit time consuming.

**Comment by salo2016** [comment]
Im playing mindustry from 2016 pixel relise, and was beta tester in play market.
If u played doom eternal u has a key Q what let u choose gun by moving mouse to left/top/right/bottom or more at 45 digrees. Why cant make it in mindustry? like press button and u make fast mouse move to select needed block.
![image](https://user-images.githubusercontent.com/62756314/162573635-33974709-05be-46e8-bbd1-2afa9779eff9.png)
weird wrote but try to understand that, its fast block choose. drag mouse takes less than second
