### ISSUE TITLE
Enable Steam Remote Play Together flag

### ISSUE THREAD

**Issue by kc7zzv** [Anuken/Mindustry-Suggestions#3492]
### Describe the content or mechanics you are proposing.

This is a Steam-only suggestion.

Please flag this game as allowing Remote Play Together (See the second section):
https://partner.steamgames.com/doc/features/remoteplay

My understanding is that this is a flag that can be set for the game, and it doesn't require any coding, but I could be wrong.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It allows someone to play with a friend, "mentoring" them when they want help.  I've had a friend who's learning the game ask for help several times.  Mostly because a pipe is leaking and he didn't notice, or a problem with Mindustry Logic (mlog).

This does have the disadvantage of allowing people to "share" a copy of the game with a friend, but since the game is already available for free, this doesn't seem like much of a problem to me.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
That seems like somewhat of a confusing choice, considering Mindustry doesn't actually have local mulitplayer. Do any other games do this, despite not having local functionality?

**Comment by RickAstly** [comment]
"Mindustry doesn't actually have local mulitplayer."
what about locally hosted pvp games

**Comment by Anuken** [comment]
The term "local multiplayer" refers to multiplayer *on the same computer*. It does not refer to local *networks*.
