### ISSUE TITLE
Cave levels or Cave level type or Dark levels

### ISSUE THREAD

**Issue by Goopey** [Anuken/Mindustry-Suggestions#3494]
### Describe the content or mechanics you are proposing.

The main mechanic would basically be a permanently dark level. There would be no light in the level except for natural sources such as lava or player-made sources such as light. And this light would also limit the players vision. They cannot see very well where to build or where units are invading.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this would be interesting since it adds a new playstyle to the game in a way. These levels have to be played differently since light becomes a resource the player has to worry about instead of their regular materials.
Plus, it would make the Illuminator more useful.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Night is already a pain, and you want more of it.

**Comment by Ruyeex** [comment]
Hey!
This is already a feature here.
You just don't know how to get it.
![image](https://user-images.githubusercontent.com/99507424/162637351-c028a452-40b2-4a81-bea4-1b0d6bd3a30d.png)

**Comment by OnyxFinger** [comment]
> Hey! This is already a feature here. You just don't know how to get it.

Actually, he also wants discount fog of war with it
which is even more painful

**Comment by guncatt** [comment]
I like it.

**Comment by numer99** [comment]
maybe, like floor blocks, ceiling blocks will cast a shadow?
and there can be completely underground maps, but also caves in some maps.
