### ISSUE TITLE
Derelict buildings destroyed by player give back crafting ingredient

### ISSUE THREAD

**Issue by SaltyBeggar** [Anuken/Mindustry-Suggestions#3495]
### Describe the content or mechanics you are proposing.

Derelict buildings destroyed by the player will give back as much resources as it would have been given if the player deconstructed the building. Preferably make that only possible after capturing a sector so you'll still have to wait to deconstruct derelict buildings when you haven't won yet.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It wouldn't actually improve the game but completely destroying bases with your units is pretty fun but it's not a good move because you won't get the resources of the destroyed buildings. With this, you'd be able to do that with no deadvantages whatsoever.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
isnt that already a thing

**Comment by oinkymoo** [comment]
Destroying by force, not dismantling

**Comment by numer99** [comment]
In Mindustry v7, there will be a repair option of derelict buildings, which will also mark them as your own. 
You can then deconstruct them for resources, or use them.

Also, if you destroy a building, you destroy a building. It's been destroyed, you won't get anything from it because it has been destroyed.

**Comment by SaltyBeggar** [comment]
> In Mindustry v7, there will be a repair option of derelict buildings, which will also mark them as your own. You can then deconstruct them for resources, or use them.
> 
> Also, if you destroy a building, you destroy a building. It's been destroyed, you won't get anything from it because it has been destroyed.

I mean destroying it would give back resources only after capturing a sector for the sake of fun. That wouldn't affect gameplay at all.
