### ISSUE TITLE
Liquid Conduit Valves

### ISSUE THREAD

**Issue by Jirachi6774** [Anuken/Mindustry-Suggestions#3496]
### Liquid Conduit Valves
A **Liquid Valve** to close of a part or section of a conduit pipe system to control the flow of the liquid flowing inside of it.

### Usage
A liquid conduit valve could be used to stop liquid from flowing into a section of a conduit system.
For example: You have a machine that uses a lot of a liquid type but because it uses a lot of the liquid it makes it so that other machines which are also connected to the same conduit system lack the liquid that is flowing through the conduit, by using a valve you could close off the way to the machine which uses a lot of the liquid and making the other machines get more liquid than they had before closing the valve, instead of having to delete the conduit `(but losing liquid because the conduit is open ended)` or having to replace it with a conduit that doesn't leak and deleting a part of the conduit to the machine which uses a lot of water.

### Why?
It can make the Liquid System a bit more controllable and you can close off pipes that don't need liquid at that time or are starting to cause trouble by consuming way to much water for the conduit system and because it sounds and looks like a neat thing that could be in the game.

### How it would work
I thought of makikng it work just like the Switch does by clicking on it and it'd switch from being open (on) to being closed (off) so the liquid could go through or be blocked from passing through.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Isn't this basically I/O side configuration?

**Comment by guncatt** [comment]
Liquid Valve should update tf2 as well.

**Comment by guncatt** [comment]
Liquid Valve should update tf2 as well.

**Comment by Sahrea** [comment]
You can disable a pipe with logic to stop the flow of liquid.

**Comment by OnyxFinger** [comment]
Can't you just not put a conduit there if liquid isn't supposed to go in it ?

**Comment by Jirachi6774** [comment]
> You can just manually change the orientation of the conduit

Kinda lame if ya ask me. =/
Changing the orientation may even make you get confused about why the liquid doesn't travel through the conduits.
