### ISSUE TITLE
QoL Feature: Re-route bridges with drag and drop

### ISSUE THREAD

**Issue by Ayuma-cell** [Anuken/Mindustry-Suggestions#3497]
### Describe the content or mechanics you are proposing.

Drag and Drop Bridge routing.
(like the one if you build new bridges, but for already placed ones)
I often times feel as bridges have to many clicks and this could speed up some things!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it'd be a quite nice feature to be able to route already places bridges by simply dragging one to another!
This way it heavily reduces missclicks and overall clicks.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
This would be a great help, especially with making schematics.

**Comment by rylid-umil** [comment]
the problem is, what if you're building bridge conveyors or overlapped bridges, how would you find a way to not link all of them?
