### ISSUE TITLE
Clickable links when joinging a server.

### ISSUE THREAD

**Issue by LargePrime** [Anuken/Mindustry-Suggestions#3498]
### Describe the content or mechanics you are proposing.

join a random server. most want you to join their discord to activate/play.

I suggest those links should be clickable.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Right now you have a few moments to memorize the random discord and type it in before the link disappears.

A clickable link makes joining fast and simple.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by guncatt** [comment]
Yes ( added so github actions bot isn't bad.)

**Comment by RealYeet** [comment]
*joinging*

**Comment by itcannotbe** [comment]
The better alternative is a copy "link" feature.

**Comment by Phinner** [comment]
Oh no, this awesome feature has been closed...

**Comment by LargePrime** [comment]
reopen, and correct spelling error?

**Comment by IxGamerXL** [comment]
> reopen, and correct spelling error?

Yeah, I think the thread should be reopened imo. Sounds like a great feature! It's pain copying a link by hand, and games like Minecraft automatically have clickable links for convenience. How about text that copy/opens it's internal link data? Heck, we could even have clickable text that executes Java/JS per click relative to the source of the text, with the Player instance as callback args.

**Comment by LargePrime** [comment]
I will remind

>Right now you have a few moments to memorize the random discord and type it in before the link disappears.

So you cannot even copy paste. you have to memorize or <GASP> use a writing utensil

This barbarism cannot stand.

**Comment by itcannotbe** [comment]
> I think the thread should be reopened

That's not how it works. Once a bot closes only anuke can reopen it.

Also this:
![Huh](https://user-images.githubusercontent.com/45280919/172233056-c0aca9f0-b600-486d-8008-8881a38c60d8.jpg)
