### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by WilloIzCitron** [Anuken/Mindustry-Suggestions#3499]
### Describe the content or mechanics you are proposing.

I believe this feature to make players (ex: Color Blind, Deaf, etc.) help to play the game

here a list of new feature:
- Narator
- Subtitle
- Colorblind Effects (Protanopia, Deuteranopia, Tritanopia)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Narator:
it help to player who have difficulty hearing

Subtitle:
it help to player who have Deaf 

Colorblind Effects:
it help to player who have Colorblind it replace a visual color 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jammo2000** [comment]
When would subtitles be needed? There's no voices in-game.

**Comment by WilloIzCitron** [comment]
oh also that feature looks like ugh oh minecraft feature
