### ISSUE TITLE
2 new types of walls (avalible only in level editor, and not as buildable block for player)

### ISSUE THREAD

**Issue by Thesussy** [Anuken/Mindustry-Suggestions#3500]
### Describe the content or mechanics you are proposing.

These walls were be, from basalt and normal metal, what aren't exist in game, but they should be in game too, cuz other terrain plates are avalible in game

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think there is no walls of normal metal (not this dark version) and basalt wall, but they would be good elements for level editor

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by numer99** [comment]
rephrase, please

**Comment by itcannotbe** [comment]
Basically, he wants environment walls that's similar to other available floor tiles.

**Comment by Rex-Hm** [comment]
good

**Comment by numer99** [comment]
it's most likely for the same reason that we don't have tree floors, or water tile walls (they don't make sense)

**Comment by Thesussy** [comment]
yes i mean envinronment blocks
