### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by ilikepie04** [Anuken/Mindustry-Suggestions#3501]
### Describe the content or mechanics you are proposing.

Allow for music download on Spotify or pandora or some other streaming service.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I love the game soundtrack but can listen to it except while in game, I would like to listen to it in more portable circumstances an open source mp3 or Spotify download would allow for such.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> open source

Let it sink in for a while...........

**Comment by TheRealIvyX** [comment]
https://github.com/Anuken/Mindustry/tree/master/core/assets/music enjoy

**Comment by numer99** [comment]
I would like the mindustry soundtrack to be on spotify, or on amazon music
we already have download though

**Comment by THEGAMER-10n** [comment]
Do you even know how posting on streaming services works?
You need to pay the said service.

Either way, if you want to listen to them, rtsc.

**Comment by ilikepie04** [comment]
Thanks ya'll I figured out a way to get it on Spotify, if your interested in the same go [Here](https://www.businessinsider.com/how-to-upload-music-to-spotify). the music files have to be in .mp3 format instead of .ogg as they are in now, I used a previous version found [Here](https://github.com/Anuken/Mindustry/tree/d43157fd22f0d3c9ee7d6d315ab2526b0e9b2642/core/assets/music). Hope this helps!
