### ISSUE TITLE
Update description of overdrive dome/projector to include that it increases speed of turrets

### ISSUE THREAD

**Issue by GaretWebster** [Anuken/Mindustry-Suggestions#3502]
### Describe what you would like changed, and why.

Update description of overdrive dome/projector to include that it increases speed of turrets

It's not immediately obvious.

### Describe the changes you want to propose. Include possible alternatives.

Just modify the description text to make it more clear.

Also might be worth having:
Status to indicate something is working at a boosted rate. Maybe a blue light instead of a green one?

I also think statuses should be on by default, it really helps players diagnose potential issues with buildings and early on it really helps to know when you get something working properly for the first time.

**Comment by oinkymoo** [comment]
does "Increases the speed of nearby buildings" not already make that clear

**Comment by THEGAMER-10n** [comment]
> does "Increases the speed of nearby buildings" not already make that clear

I think he means indicators.

**Comment by itcannotbe** [comment]
> > does "Increases the speed of nearby buildings" not already make that clear
> 
> I think he means indicators.

He didn't.

To recap:

>  ### Describe what you would like changed, and why.

> Update description of overdrive dome/projector to include that it increases speed of turrets
>
> It's not immediately obvious.

**Comment by OnyxFinger** [comment]
> does "Increases the speed of nearby buildings" not already make that clear

Surprisingly not. Of course, an extreme majority of players would understand, but it is misleading enough that many players don't.

**Comment by itcannotbe** [comment]
> > does "Increases the speed of nearby buildings" not already make that clear
> 
> Surprisingly not. Of course, an extreme majority of players would understand, but it is misleading enough that many players don't.

TuRrEtS aRe BuIlDiNgS? WhAt A rEveLaTiOn!

**Comment by MistahStealYoGril** [comment]
Wait, since when did they boost turrets?

**Comment by GaretWebster** [comment]
No.

Being explicit helps.
