### ISSUE TITLE
Merge the existing T1 factories into one factory

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#3503]
### Describe what you would like changed, and why.

Before downvoting this to oblivion, please fully read suggestion.

I am suggesting here that the T1 factories should be merged into one singular factory. While this would cause some confusion initially as to why thee ground, air, and naval units are not separated, it shows a little benefit in the long run. Before we had the ability to ban certain units, or even unit trees, I can only assume the reason these unit types were separated was so map creators could ban unit types which they didn’t want on their map. Now that this functionality is in place however, it would be nice to have the unit contained in the same factory for the following reasons:

- De-clutters the unit tab slightly
- Allows logic to change the type of unit being made while not being restricted to the type of unit factory, for example, this factory could now be switched between flares and rissos, as before this would not be possible. 

### Describe the changes you want to propose. Include possible alternatives.

The change was already described above so I will list a few pros and cons.

Pros:

- unit tab would be slightly easier to navigate
- The type of unit being mad could be theoretically hidden for a longer period of time from enemy teams keeping players on edge 
- Logic having the ability to change in between all units without having to build a different T1 factory
- More straight forward as all unit could be built from the same factory without the need to interchange buildings

Cons:

- People used to navigating unit factories via color will need time to adapt
- It would be easier to accidentally make the wrong unit, like trying to make a dagger and accidentally clicking on a risso
- Pre-existing schematics would need to have their factories replaced with this new one
- Without prior knowledge or experience playing the game, it would be impossible to tell if a unit is air, ground, or naval based unless a new UI to show the differences is made

Alternatives: 

Don’t put this in the game

**Comment by end-me-please** [comment]
In v5 every unit had it's own factory

**Comment by RealYeet** [comment]
Yes, but we are moving on from V5. Players can already play stable versions of V6 and unstable versions of V7.

**Comment by oinkymoo** [comment]
there aren't enough buildings in the units tab for decluttering to be necessary, and logic is going to be largely disappearing from v7, and also there are no places where you can put both a ground unit and a naval unit

**Comment by RealYeet** [comment]
> there aren't enough buildings in the units tab for decluttering to be necessary, and logic is going to be largely disappearing from v7, and also there are no places where you can put both a ground unit and a naval unit

The first comment is fair, there is no real reason for decluttering, but it is always wlecome

Logic will be non-existent on Erekir, however, I have never seen anything stating logic will be outright removed from Surplo, and regarding multiplayer, there will always be games played in a Surplo setting. 

The third comment is wrong (Shallow water)

**Comment by itcannotbe** [comment]
Actually, factories blocks are used as a research lock in campaign.

Also, it is beneficial for mods to have separate T1 factory blocks as the T1 won't be as cluttered as it would be it it wasn't.

**Comment by itcannotbe** [comment]
Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?

**Comment by RealYeet** [comment]
> Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?

Switching unit types with logic could be used to diversify the units made without having to manually change the factory.

**Comment by itcannotbe** [comment]
> > Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?
> 
> Switching unit types with logic could be used to diversify the units made without having to manually change the factory.

Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?

**Comment by RealYeet** [comment]
> > > Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?
> > 
> > 
> > Switching unit types with logic could be used to diversify the units made without having to manually change the factory.
> 
> Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?

Logic processors can detect what type of unit a T1 factory is making. I use this to bring coal to crawlers and lead to my monos in almost all of my schematics. Thus, a processor could detect what resources are needed. There is no need to input every resource into a factory, and if you did I would have to question your skill at the game.

**Comment by itcannotbe** [comment]
> > > > Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?
> > > 
> > > 
> > > Switching unit types with logic could be used to diversify the units made without having to manually change the factory.
> > 
> > 
> > Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?
> 
> Logic processors can detect what type of unit a T1 factory is making. I use this to bring coal to crawlers and lead to my monos in almost all of my schematics. Thus, a processor could detect what resources are needed. There is no need to input every resource into a factory at any given time, and if you did I would have to question your skill at the game. Plus, even in existing schematics, it is common to see a container or vault containing every resource which is inputted into a factory via an unco figured unloaded. So yes, people besides me will input every resource into a factory.

What is that thing I said?

>  ... what are going to use? Unit slavery to fetch the required items ...

Clearly someone isn't reading enough.

**Comment by RealYeet** [comment]
> > > > > Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?
> > > > 
> > > > 
> > > > Switching unit types with logic could be used to diversify the units made without having to manually change the factory.
> > > 
> > > 
> > > Also using logic to change what T1 you would be making not even that practical with logic, what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need?
> > 
> > 
> > Logic processors can detect what type of unit a T1 factory is making. I use this to bring coal to crawlers and lead to my monos in almost all of my schematics. Thus, a processor could detect what resources are needed. There is no need to input every resource into a factory at any given time, and if you did I would have to question your skill at the game. Plus, even in existing schematics, it is common to see a container or vault containing every resource which is inputted into a factory via an unco figured unloaded. So yes, people besides me will input every resource into a factory.
> 
> What is that thing I said?
> 
> > ... what are going to use? Unit slavery to fetch the required items or plug in every material T1s would need (into the schematic)?
> 
> Clearly someone isn't reading enough.

*What do you expect people to do? Only input silicon into a factory?* It does not work that way, you are also going to need lead, titanium, coal, and other resources in greater tiers. Make a unit builder that only uses silicon to get me a dagger and I will believe you when you say I shouldn't be inputting every resource into a factory.

Also, I clearly said that processors can detect the type of unit being made and input the needed resources, so something is clearly not reading through.

**Comment by itcannotbe** [comment]
> Also, I clearly said that processors can detect the type of unit being made and input the needed resources, so something is clearly not reading through.

How do you expect unit slavery to work without using processors in the first place?

**Comment by RealYeet** [comment]
> > Also, I clearly said that processors can detect the type of unit being made and input the needed resources, so something is clearly not reading through.
> 
> How do you expect unit slavery to work without using processors in the first place? It's implied.

Its a little funny how I said logic would still be used in my first reply. 

"Logic will be non-existent on Erekir, however, I have never seen anything stating logic will be outright removed from Surplo, and regarding multiplayer, there will always be games played in a Surplo setting."

**Comment by Sector171** [comment]
Honestly I don't understand why all that down voting this suggestion!

> In v5 every unit had it's own factory

I can't imagine how much annoying was this, I started with V6.
Apparently making T1 factories less and based on the branch became much better.
But ,will doing so again that all units could be produced by one factory necessarily be better?!
What determines this is if this process makes the things better and easier.
Ok we have 3 branches of units(Flying, Naval, Ground) and the total 8 units.
Ok till now it is nothing, can easily be in one factory without any problem. And this gives more flexibility.
But if the branches exceed 8 or 9, this will make it harder. But I think this may take years.
So making all T1 in one factory could be better(needs test), but theoretically should be better & more flexible.

**Comment by Rex-Hm** [comment]
good suggestion

For mappers who add logic to their maps and pvp players this is quite useful.
