### ISSUE TITLE
BE: am i stupid

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#3505]
### Describe what you would like changed, and why.

is it just me or does the BE build update notification have no disable setting

### Describe the changes you want to propose. Include possible alternatives.

me when i reload BE every 3 minutes to test changes and
![image](https://user-images.githubusercontent.com/61173114/163726035-d2386cdb-f87c-40d6-b3c6-15e38f85d6a7.png)

**Comment by Anuken** [comment]
Not using the latest BE build is a pretty weird use case, so I never thought anyone would need it.

~~but there is an option, it's called "turn off your internet".~~

**Comment by BlueWolf3682** [comment]
well updating the BE more or less daily does get tedious, especially since doing so doesnt change anything yet
