### ISSUE TITLE
enemy spawn different enemy

### ISSUE THREAD

**Issue by killerspike01** [Anuken/Mindustry-Suggestions#3506]
### Describe the content or mechanics you are proposing.

i hope enemy spawn can spawn different enemy
example if i place 2 spawn on the left and the right
then i can choose these enemy spawn at where
like i can the left one spawn daggers and the right one spawn regin
that will be very cool

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

just do it:)
it can change the intire game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
on one hand, i agree, but on the other you did not respect the sanctity of the template

**Comment by Bottinator22** [comment]
World processors can probably achieve this in the future

**Comment by SaltyBeggar** [comment]
that'd be interesting to make the game more dynamic

**Comment by Anuken** [comment]
This was implemented in the private branch some time ago:

![image](https://user-images.githubusercontent.com/10100000/163732485-3fc7fa32-33ad-41b6-b513-b2b64d9988a1.png)

**Comment by guncatt** [comment]
> This was implemented in the private branch some time ago:
> 
> ![image](https://user-images.githubusercontent.com/10100000/163732485-3fc7fa32-33ad-41b6-b513-b2b64d9988a1.png)
> 

Eh how tf
