### ISSUE TITLE
Geometry Dash X Animindustry

### ISSUE THREAD

**Issue by Slawmee** [Anuken/Mindustry-Suggestions#3507]
### Describe the content or mechanics you are proposing.

Idk if someone already made a suggestion like this but 

Make us able to make our own levels and music or just find non copyright music source like in Geometry dash

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The devs will not need to work hard for their own levels

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Delourians** [comment]
Ur pfp lol

**Comment by end-me-please** [comment]
A level editor was discussed extensively, but Anuke is probably busy enough with Mindustry v7 rn

also perhaps you should go to https://github.com/anuken/animdustry

**Comment by STRAY-blup** [comment]
**Unit editor.** With it, you can create your own unit (logically). Details are revealed as technology is explored. The required resources are calculated based on the parts used. Some details require passing the unit through certain reconstructors (for example, Omura's railgun requires passing through all 5  reconstructors)
