### ISSUE TITLE
**Unit editor**

### ISSUE THREAD

**Issue by STRAY-blup** [Anuken/Mindustry-Suggestions#3508]
### Describe the content or mechanics you are proposing.

Unit editor. With it, you can create your own unit (logically). Details are revealed as technology is explored. The required resources are calculated based on the parts used. Some details require passing the unit through certain reconstructors (for example, Omura's railgun requires passing through all 5 reconstructors). It would also be useful to be able to prescribe AI to them (as with processors). And for those who do not know how to program, you can create templates such as "Support", "Healing", "War", "Mining".

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will give a lot of new opportunities and increase the number of winning strategies. I think most players will like it, because it's as big a change as the processors, but not everyone understands programming, and the visual unit editor will be clear to everyone.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Impractical to implement properly.

**Comment by end-me-please** [comment]
Custom units and custom AI would require a lot more CPU juice I think

**Comment by TheRealIvyX** [comment]
you can already make your own units with a thing called "modding"

**Comment by STRAY-blup** [comment]
> Custom units and custom AI would require a lot more CPU juice I think

In this case, you can save units in the same files as now, calculating the speed in advance, creating a sprite, etc.

**Comment by STRAY-blup** [comment]
> you can already make your own units with a thing called "modding"

If you want to play on a server with mods, this is unlikely to work

**Comment by TheRealIvyX** [comment]
> If you want to play on a server with mods, this is unlikely to work

then play on a server that has the mods you have (or better yet, play with your friends to minimize whatever the heck goes on in most multiplayer servers with the constant lack of silicon and stuff)

**Comment by WilloIzCitron** [comment]
he want WYSIWYG mindustry modding without coding and generates codes

**Comment by STRAY-blup** [comment]
> > Если вы хотите играть на сервере с модами, это вряд ли сработает
> 
> затем играйте на сервере, на котором есть моды, которые у вас есть (или, еще лучше, играйте со своими друзьями, чтобы свести к минимуму все, что происходит на большинстве многопользовательских серверов с постоянным отсутствием кремния и прочего)

And if you want to create your own unit, this mod will be added to any server. And yes, I have too few friends)

**Comment by WilloIzCitron** [comment]
multiplayer support mod are:
- UI Mods
- Script Mod what not added a new content
-

**Comment by STRAY-blup** [comment]
> multiplayer support mod are:
> 
> * UI Mods
> * Script Mod doesn't add any new content
I'm talking about mods for units

**Comment by itcannotbe** [comment]
> he want WYSIWYG mindustry modding without coding and generates codes from visual modding

Ah yes, even programmers dream that, Programming something without actually programming something.

**Comment by Sector171** [comment]
Not practical, not only from implementation perspective, but also from balancing angle.
Ok as you know all t2->t5 cost the same, only the difference is in T1 which nothing at all, now make a flying unit like eclipse but with omura's railgun & range, ok I don't need the armour or any other features, what will you get? Overpowered unit ( if I understood your idea correctly).

See the 5th suggestion here, I liked it too much hope if someone makes this mod #3149
It is different idea ofc, but the common thing is the ability to make custom units.

**Comment by Bottinator22** [comment]
> > he want WYSIWYG mindustry modding without coding and generates codes from visual modding
> 
> Ah yes, even programmers dream that, Programming something without actually programming something.

*meanwhile me and wanting to learn to do things closer and closer to being from scratch*

**Comment by WilloIzCitron** [comment]
\*fard sfx*
