### ISSUE TITLE
Unit One click Commands (could probably have a pop-up logic command that's already set and just need numbers)

### ISSUE THREAD

**Issue by SydeathVx** [Anuken/Mindustry-Suggestions#3509]
### Describe the content or mechanics you are proposing.

Battle Command Assignments, Commands that can affect how a unit acts: Patrolling: [Point Based Patrolling],[Area Based Patrolling]  ._    

[Attack On Sight], Attacking enemies if they enter range, _   [Hunt]: Will chase enemies to attack enemies either until they die or the enemy dies._    

[Safe Hunt]: Will attack enemies but will retreat if they become low on health;[make it so that you can edit at which percentage at health they should retreat]. Either they have to enter a certain range and they can start attacking or are they able to run straight to the enemy and attack them because the enemies don't have to enter a certain range to just be scanned for attack, idk you decide if you wanna implement this its your game anyway <3._     

 Attack at max range: units will attack at max range. Attack at any range: Units will attack at any range, for example a dagger can attack for 19 range if they get pushed they will still attack and not move back.

Support Based Commands:
 [Mine]Units that are able to mine either specific ores, or anything that's low on resources {if you want them to mine sand that is, which is fine..}. 

[Building] You can assign units to build, put down a schematic and you can assign like 1 unit to build so that others are free for use {idk if it still builds without you putting the schematic down so I just talked about it}. 

[Support] Will assist in either units and builds, if they have healing capabilities like polies and novas they can be either set to heal units like run to them and run back after they healed those units,

 [Grouping] Group units to other units, 

[Conditional Grouping], Groups Units for example you want to group a dagger and a nova because you are lazy to just build a healing turret for them to retreat to, or make it so that 

[Safe Hunt] & [Support] can affect each other; Unit retreats finds a healing source, Healer searches for damaged Unit, Unit gets fully healed they go back to battle, and Healer's job is done they go back to a command you could assign them to, 

or you could set multiple commands that's set on a priority like 
[Support] units is 1. and [Building] is 2. they will run the [Support] command first before building.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I saw a game named Siege up! and saw a command where its a sword and when you click it, it will make units attack on sight. It is a command that sets units so that they don't run up to enemies on their own and trigger the enemy unit's self-defense (such as where they notice your unit and says "aight you wanna fight then lets fight"), I'm really hyped for what you will do for comeplete v7 love your game will wait for it like a loyal fan to the game of yours, How I think it will affect the game might be positive because units can be smarter without logic, while logic will be deleted from the new planet these could be good remedies [probably], and it could be convenient for players in serpulo

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SydeathVx** [comment]
if any of you have a much better idea for this suggestion let me know so i could edit or not idk how this works can't wait for the update this mid 2022 or late 2022

**Comment by Sector171** [comment]
Great suggestion for sure.

**Comment by oinkymoo** [comment]
please use paragraph breaks this is actually unreadable
