### ISSUE TITLE
Logic Processor Modification Modules

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3512]
### Describe the content or mechanics you are proposing.

Optional modifications for processors that enhance the speed of certain operation types at the expense of slowing down other certain operation types. You can change a processor to a new modification after using some materials to create it, and you can change modifications whilst configuring a processor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It encourages the use of multiple processors and also memory cells to make sure the processors can share the data. Processors creating logic art can also get optimized to handle drawing faster as well. It practically buffs processors, but it also nerfs it in exchange for additional speed.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by numer99** [comment]
keep in mind that anuken is not going to add logic to Erekir; he's not going to work on logic for a while
