### ISSUE TITLE
Unit Recipe

### ISSUE THREAD

**Issue by N23L** [Anuken/Mindustry-Suggestions#3513]
### Describe what you would like changed, and why.

The addition of information to units in Tech Tree will be helpful

### Describe the changes you want to propose. Include possible alternatives.

I would like to see the units recipe in the Tech Tree instead of building the factories to know the recipe.

**Comment by end-me-please** [comment]
Every unit of a tier has almost the same resource requirements.
Only the T1 units have different recipes.

**Comment by itcannotbe** [comment]
Each reconstructor uses a recipe of it's own regardless of which acceptable lower tier unit you feed into it.

**Comment by numer99** [comment]
isn't the recipe available in the core database?
