### ISSUE TITLE
How do I add new sectors or edit existing sectors by a mod?

### ISSUE THREAD

**Issue by 18001767679** [Anuken/Mindustry-Suggestions#3514]
### Describe the content or mechanics you are proposing.

how?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I want to make a mod that changes a number of boring sectors to a pile of ores aligned for laser drills and has a bunch of derilict auto impact reactors (and a new type of hardness:super ez for these mining sectors,derelict auto thorium cyclones near enemy spawn)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
the place to get help with this is #modding-general in the discord

**Comment by bendnuts** [comment]
the place to get help for this is to read the fucking sauce code

**Comment by numer99** [comment]
how on earth is this a feature request

**Comment by guncatt** [comment]
Man really just died here

**Comment by THEGAMER-10n** [comment]
RTFSC moment
