### ISSUE TITLE
Unit launch pad

### ISSUE THREAD

**Issue by 18001767679** [Anuken/Mindustry-Suggestions#3515]
### Describe the content or mechanics you are proposing.

A new launch pad that launches units for attack sectors that needs to be shooted down rilly quick.
Cooldown 20 secs,one unit one launch.
Consumes 10/40/100/500/1250 blast compound for each launch of T1/T2/T3/T4/T5.
Accepts inputs from payload conveyors or carrier units but not accepting units that walk/fly/swim to the pad by its self instead of getting carried.
Tech tree:Above launch pad.Needs unlocking launch pad and payload conveyors and blast compound and phase fabric.
All of the launch pads and unit launch pads can only aim at one sector.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

bringing 9k of stuff just for making 2 Quads isn't happy to do.
Neither is having to build Exponential reconstructers and cryofluid mixers everytime doing quad bombing.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 18001767679** [comment]
I have a different idea than https://trello.com/c/TogJg9CP/612-sector-transfer
so not redendant

**Comment by itcannotbe** [comment]
It's the same concept honestly. So no, this suggestion deserves to die now.

**Comment by OnyxFinger** [comment]
Launch pads are already too strong, why add unit launch pads ?

**Comment by numer99** [comment]
unit launch pads would be way too overpowered
it would make capturing sectors way to easy, and make the game boring
