### ISSUE TITLE
Logic: Lua Mode

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3516]
### Describe the content or mechanics you are proposing.

An optional mode for processors that uses Lua programming in text instead of instruction stacks. This *hopefully* also adds syntax and auto correct (for built-in functions like logic.readCell()). Errors are handled using `error()` by default, and `print()`, `warn()`, and `error()` will report to the processor's logs. All errors will cause the processor to skip the lines where the errors occurred.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Adding Lua Mode makes optimizing your programming in processors much more possible, reduces the constant redefinition of variables, and will likely cause processing to skyrocket in speed. Map settings can include whether or not Lua Processors are enabled (any maps before this addition automatically disable Lua Mode), and for every runnable line of code, it will delay by the amount of time specified by the processor type.

On a final note: Yes, I do understand Anuken's focus is on the new planet and he isn't worried about Logic very much. This would work best as a for-later feature after the production of V7 is finalized outside of BE and pre-releases.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Not going to happen.

Since Lua scripting has already been considered when logic is being planned to be added.

**Comment by itcannotbe** [comment]
Furthermore, Logic is probably not going to be actively be developed anymore.

**Comment by end-me-please** [comment]
Main problem with lua is probably that it can allocate garbage/cause lag, mlog was specifically developed to not do this

**Comment by itcannotbe** [comment]
![Screenshot_20220423_162154](https://user-images.githubusercontent.com/45280919/164886739-c90a5d14-d835-4c17-837c-4221accb1fe9.jpg)
