### ISSUE TITLE
Liquids + Units (All or some)

### ISSUE THREAD

**Issue by yozozchomutova** [Anuken/Mindustry-Suggestions#3517]
### Describe the content or mechanics you are proposing.

Compatible liquids: Water, Cryofluid
Incompatible liquids: Slag, Oil
New block: Liquid ressuply (Inspired by: Ressuply point)

Units can hold small amount of coolant. Coolant can be loaded with *Liquid ressuply*, which works simillary as *Ressuply point*, but instead of copper, you give it water/cryofluid. And surely, cryofluid has better effect than water.

**How does it will affect units?**
**Combat units:** Better fire rate + coolant only decreasing when shooting.
**Mining units:** Faster mining + coolant only decreasing when mining.
**Building units:** Faster building + coolant only decreasing when building.
**Shielded units:** Reducing incoming shield damage + coolant only decreasing when taking shield damage.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Optionally allows to let players improve their units a bit by giving them coolant.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by numer99** [comment]
yes
