### ISSUE TITLE
Sword reconstructor

### ISSUE THREAD

**Issue by freshscreen4** [Anuken/Mindustry-Suggestions#3519]
### Describe the content or mechanics you are proposing.

This 3 by 3 building can replace a dagger's/nova's weapons for a slow but powerful sword! Sword units can still go through other reconstructors as if they were a normal unit, the sword will also receive effects like the mace's "burning" effect or the pulsar's "shocked" effect. If the unit gets shot 3 times the 3rd shot will be blocked by the sword, sending it where it came from like a phase wall, energy projectiles will still be reflected but the unit will take 50% of the damage and the reflected laser will also deal 50% of the damage it would usually deal

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This small thing technically and 8 "NEW" UNITS which  allows for some... interesting strategies to say the least. It counters some turrets/units that the unit would normally not be able to even get remotely close to. Aaand I've officially ran out of ideas... great! But you get the point, guns are bad in some situations and swords are better in some other, of course the opposite applies in some other situations.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by THEGAMER-10n** [comment]
Why though?

**Comment by itcannotbe** [comment]
Oh look mom, a robot picks up a sword instead of every weapon there is in the game.

**Comment by numer99** [comment]
this would be catastrophic to the game's balance
and why would a tier 1 unit be wielding a "powerful weapon"
tier 1 units are not supposed to be powerful
