### ISSUE TITLE
Base-patrolling units

### ISSUE THREAD

**Issue by ThatOneBepis** [Anuken/Mindustry-Suggestions#352]
Units that go around your base. Term "base" refers to all functional blocks (ie. drills, factories, turrets, etc.) in your team. These units will randomly select base blocks to which it will travel, and upon reaching it (or 10 seconds passes since the target is destroyed), it will go to another base block, ad infinitum. Any units caught within it's range/engagement radius will be engaged by this unit type, and it will return to normal behavior upon killing all units within it's range/engagement radius.

This unit type may add a more defensive approach to units, and allow the player to construct a production facility without the need for larger defenses or acting as a second line of defense for units that breach your defensive lines. Of course, they may be used in an offensive manner (somehow), and generally be effective against units rather than buildings. But even then, what they could do is mimic the player when some stray units pass your defenses.

**I have acknowledged all bolded/italic text, and open for criticism.**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. 
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Isn't this kinda similar to #319
