### ISSUE TITLE
Глобальная доработка серверов в миндустри

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#3520]
### Describe what you would like changed, and why.

Улучшение меню выбора сервера, Доработка чата,  Добавление подсказок на сервера с модами , фикс некорректной 
 скорости юнита с измененными характеристиками

### Describe the changes you want to propose. Include possible alternatives.

Улучшение серверов:

Улучшение меню выбора сервера:
добавить возможность сохранить адрес сервера из списка публичных серверов.
Почему: это делает намного удобней заход на нужный сервер без метания по списку серверов.

Доработка чата:
Добавить возможность копировать сообщения из чата (пкм по нужному сообщению и выбрать копировать).
Зачем: для улучшения взаимодействия комьюнити и перехода на иные ресурсы и сообщества сервера, а не ручной поиск.

Добавить возможность интерактивного использования команд написанных в чате.
(вы можете сразу выбрать команду из чата, а не вводить ее вручную).

Добавить возможность маскировать команды в слова (для создания интерактивных меню из чата для серверов с плагинами).

Подсказки при заходе на сервер:
Дать возможность при создании сервера с модом указать использованный мод в браузере модов, при заходе пользователя без мода ему выходит предупреждение, что нужно установить мод показанный в браузере модов.
Зачем: это сделает возможным существование серверов с модами.

Улучшение взаимодействия с эффектами:
Добавить возможность модифицировать эффекты плагинами ,возможность накладывать плагином эффекты на юнитов и снимать их.
Зачем: больше возможностей плагинам делают сервера лучше.

Фикс: При изменении сервером изначальной скорости конкретного типа юнитов, эти юниты, управляемые ИИ, движутся с этой самой скоростью, но под управлением игроков "дергаются" и вызывают рассинхроны.
Мое предложение - синхронизировать эту скорость между игроками и сервером, чтобы устранить проблему.

**Comment by RealYeet** [comment]
Translated:

Describere quid velis mutatum, quidve.

  Improvement of the server selection menu
  nit speed with modified characteristics

  Mutationes describere vis proponere.  Possibile including utrumque.

  server improvements;

  Server selection menu improvements:
  add the ability to save the server address from the list of public servers.
  why: it makes it much more convenient to enter the desired server without throwing through the list of servers.

  Refinement of ata:
  Add the ability to copy messages from the mailbox (right-click on the desired message and select copy).
  .

  Add the possibility of interactive use of commands written in ata.
  (you can immediately select a command from the ata, instead of entering it manually).

  Add the ability to masquerade masquerade commands into words (to create interactive Seata menus for servers with

  Hints when entering the server;
  To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
  why: it will make possible the existence of servers with mods.

  improved interaction with effects;
  .
  why: more plugin options make servers better.

  Fix: When the server changes the initial speed of a particular type of unit, these AI-controlled units move at this very speed, but under the control of the players they "twitch" and cause desynchronization.
  The second suggestion is to synchronize this speed between the players and the server to fix the problem.

**Comment by ziszlo** [comment]
> Translated:
> 
> Describere quid velis mutatum, quidve.
> 
> Improvement of the server selection menu nit speed with modified characteristics
> 
> Mutationes describere vis proponere. Possibile including utrumque.
> 
> server improvements;
> 
> Server selection menu improvements: add the ability to save the server address from the list of public servers. why: it makes it much more convenient to enter the desired server without throwing through the list of servers.
> 
> Refinement of ata: Add the ability to copy messages from the mailbox (right-click on the desired message and select copy). .
> 
> Add the possibility of interactive use of commands written in ata. (you can immediately select a command from the ata, instead of entering it manually).
> 
> Add the ability to masquerade masquerade commands into words (to create interactive Seata menus for servers with
> 
> Hints when entering the server; To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser. why: it will make possible the existence of servers with mods.
> 
> improved interaction with effects; . why: more plugin options make servers better.
> 
> Fix: When the server changes the initial speed of a particular type of unit, these AI-controlled units move at this very speed, but under the control of the players they "twitch" and cause desynchronization. The second suggestion is to synchronize this speed between the players and the server to fix the problem.

wery bad translate
чата translated chat , u translate it to "ata" wtf man it cringe

**Comment by oinkymoo** [comment]
its google translated and solely for the convenience of other commenters because most of us don't know russian.

**Comment by ziszlo** [comment]
> its google translated and solely for the convenience of other commenters because most of us don't know russian

why don't you leave an opinion on ideas whether they are good or bad?

**Comment by itcannotbe** [comment]
> > its google translated and solely for the convenience of other commenters because most of us don't know russian
> 
> why don't you leave an opinion on ideas whether they are good or bad?

Translating a non English suggestion to english is common practice here.

**Comment by itcannotbe** [comment]
Translated but better:

### Describe what you would like changed, and why.

 Improvement of the server selection menu, Improvement of the chat, Adding hints to servers with mods, fixing an incorrect
 speed of a unit with modified characteristics

### Describe the changes you want to propose.  Includes possible alternatives.

 Server upgrades:

 Server selection menu improvements:
 add the ability to save the server address from the list of public servers.
 Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.

 Chat improvements:
 Add the ability to copy messages from the chat (right-click on the desired message and select copy).
 Why: to improve community interaction and transition to other resources and server communities, rather than manual search.

 Add the ability to interactively use commands written in the chat.
 (you can immediately select a command from the chat instead of entering it manually).

 Add the ability to mask commands into words (to create interactive menus from chat for servers with plugins).

 Hints when entering the server:
 To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
 Why: This will make it possible for servers with mods to exist.

 Improved interaction with effects:
 Add the ability to modify effects with plugins, the ability to apply plugin effects to units and remove them.
 Why: More plugin options make servers better.

 Fix: When the server changes the initial speed of a particular type of unit, these AI-controlled units move at this very speed, but under the control of the players they "twitch" and cause desynchronization.
 My suggestion is to sync this speed between the players and the server to fix the issue.

**Comment by itcannotbe** [comment]
Server upgrades:

Server selection menu improvements:
add the ability to save the server address from the list of public servers.
Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.

Use the eye icon to to hide/unhide servers.

**Comment by itcannotbe** [comment]
> Chat improvements:
>
> Add the ability to interactively use commands written in the chat.
(you can immediately select a command from the chat instead of entering it manually).
> 
> Add the ability to mask commands into words (to create interactive menus from chat for servers with plugins).

The game client can't tell commands typed in chat because most of then are defined by a server plugin that reads chat messages.

**Comment by itcannotbe** [comment]
> Hints when entering the server:
> 
> To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
> Why: This will make it possible for servers with mods to exist.

There are already multiple ways to implement this. And it's just up to the server owner to actually do it.

**Comment by itcannotbe** [comment]
> Improved interaction with effects:
> Add the ability to modify effects with plugins, the ability to apply plugin effects to units and remove them.
> Why: More plugin options make servers better.

Plugins can't do that. Since they're just running on the server. So anything that needs custom assets are required to be a mod instead.

**Comment by itcannotbe** [comment]
> Fix: When the server changes the initial speed of a particular type of unit, these AI-controlled units move at this very speed, but under the control of the players they "twitch" and cause desynchronization.
> My suggestion is to sync this speed between the players and the server to fix the issue.

If this is bug, this is the wrong place to report it.

**Comment by itcannotbe** [comment]
Furthermore, it is better to give unrelated suggestion it's own thread.

**Comment by ziszlo** [comment]
> > Server upgrades:
> > Server selection menu improvements:
> > add the ability to save the server address from the list of public servers.
> > Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.
> 
> Use the eye icon to to hide/unhide servers.

loading a list of servers is a very fickle thing, your idea is hidden interfering servers to see only the ones you need, very stupid

**Comment by ziszlo** [comment]
> > Chat improvements:
> > Add the ability to interactively use commands written in the chat.
> > (you can immediately select a command from the chat instead of entering it manually).
> > Add the ability to mask commands into words (to create interactive menus from chat for servers with plugins).
> 
> The game client can't tell commands typed in chat because most of them are defined by a server plugin that reads chat messages.

this can be implemented by separating commands with special characters example: {/help}
this way it would be possible to convene inactive menus from the chat for specific servers

**Comment by ziszlo** [comment]
> > Hints when entering the server:
> > To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
> > Why: This will make it possible for servers with mods to exist.
> 
> There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.

at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players
simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible.
we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience

**Comment by ziszlo** [comment]
> > Improved interaction with effects:
> > Add the ability to modify effects with plugins, the ability to apply plugin effects to units and remove them.
> > Why: More plugin options make servers better.
> 
> Plugins can't do that. Since they're just running on the server. So anything that needs custom assets are required to be a mod instead.

again, remember the problem for entering servers with mods for ordinary users

**Comment by ziszlo** [comment]
> Furthermore, it is better to give unrelated suggestions their own separate threads.

this is already a shortened list of changes to one category!

**Comment by itcannotbe** [comment]
> > > Server upgrades:
> > > Server selection menu improvements:
> > > add the ability to save the server address from the list of public servers.
> > > Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.
> > 
> > 
> > Use the eye icon to to hide/unhide servers.
> 
> loading a list of servers is a very fickle thing, your idea is hidden interfering servers to see only the ones you need, very stupid

It's not my idea, It's what implemented already.

**Comment by itcannotbe** [comment]
> > > Chat improvements:
> > > Add the ability to interactively use commands written in the chat.
> > > (you can immediately select a command from the chat instead of entering it manually).
> > > Add the ability to mask commands into words (to create interactive menus from chat for servers with plugins).
> > 
> > 
> > The game client can't tell commands typed in chat because most of them are defined by a server plugin that reads chat messages.
> 
> this can be implemented by separating commands with special characters example: {/help} this way it would be possible to convene inactive menus from the chat for specific servers

You sure about that, why don't you make a pull request to implement just that?

**Comment by itcannotbe** [comment]
> > > Hints when entering the server:
> > > To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
> > > Why: This will make it possible for servers with mods to exist.
> > 
> > 
> > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> 
> at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible. we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience

There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.

**Comment by ziszlo** [comment]
> > > > Server upgrades:
> > > > Server selection menu improvements:
> > > > add the ability to save the server address from the list of public servers.
> > > > Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.
> > > 
> > > 
> > > Use the eye icon to to hide/unhide servers.
> > 
> > 
> > loading a list of servers is a very fickle thing, your idea is hidden interfering servers to see only the ones you need, very stupid
> 
> It's not my idea, It's what implemented already.

this is a feature request for convenience

**Comment by ziszlo** [comment]
> > > > Hints when entering the server:
> > > > To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
> > > > Why: This will make it possible for servers with mods to exist.
> > > 
> > > 
> > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > 
> > 
> > at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible. we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience
> 
> There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.

these methods are terrible and difficult, the game needs a new user friendly way to enter the mod server

**Comment by itcannotbe** [comment]
> > > > > Hints when entering the server:
> > > > > To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser.
> > > > > Why: This will make it possible for servers with mods to exist.
> > > > 
> > > > 
> > > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > > 
> > > 
> > > at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible. we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience
> > 
> > 
> > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> 
> these methods are terrible and difficult, the game needs a new user friendly way to enter the mod server

From a security standpoint, forcing people to download mods themselves is a better option than an automatic download.

**Comment by itcannotbe** [comment]
> > > > > Server upgrades:
> > > > > Server selection menu improvements:
> > > > > add the ability to save the server address from the list of public servers.
> > > > > Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.
> > > > 
> > > > 
> > > > Use the eye icon to to hide/unhide servers.
> > > 
> > > 
> > > loading a list of servers is a very fickle thing, your idea is hidden interfering servers to see only the ones you need, very stupid
> > 
> > 
> > It's not my idea, It's what implemented already.
> 
> this is a feature request for convenience

Your suggestions is less convenient for people tbh.

**Comment by ziszlo** [comment]
> > > > > > Server upgrades: Server selection menu improvements: add the ability to save the server address from the list of public servers. Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.
> > > > > 
> > > > > 
> > > > > Use the eye icon to to hide/unhide servers.
> > > > 
> > > > 
> > > > loading a list of servers is a very fickle thing, your idea is hidden interfering servers to see only the ones you need, very stupid
> > > 
> > > 
> > > It's not my idea, It's what implemented already.
> > 
> > 
> > this is a feature request for convenience
> 
> Your suggestions is less convenient for people tbh.
> 
> Also if you can't load the list of servers, there a large chance that you can't even play online.

1 winding the list of serers back and forth to find the right one is not very convenient
2 loading the list of servers very often lags, which is why some active servers are not shown

**Comment by ziszlo** [comment]
> > > > > > Hints when entering the server: To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser. Why: This will make it possible for servers with mods to exist.
> > > > > 
> > > > > 
> > > > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > > > 
> > > > 
> > > > at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible. we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience
> > > 
> > > 
> > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > 
> > 
> > these methods are terrible and difficult, the game needs a new user friendly way to enter the mod server
> 
> From a security standpoint, forcing people to download mods themselves is a better option than an automatic download.

you absolutely do not understand me
I offer tips on what mods to download so you can enter this server
now it is very difficult to understand and find the right mod
hints would make this much easier

**Comment by itcannotbe** [comment]
> > > > > > > Hints when entering the server: To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser. Why: This will make it possible for servers with mods to exist.
> > > > > > 
> > > > > > 
> > > > > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > > > > 
> > > > > 
> > > > > at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible. we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience
> > > > 
> > > > 
> > > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > > 
> > > 
> > > these methods are terrible and difficult, the game needs a new user friendly way to enter the mod server
> > 
> > 
> > From a security standpoint, forcing people to download mods themselves is a better option than an automatic download.
> 
> you absolutely do not understand me I offer tips on what mods to download so you can enter this server now it is very difficult to understand and find the right mod hints would make this much easier

The server can just mention the repository of the mod then you can just use the built in way to download mods from github. How hard can that be realistically?

**Comment by itcannotbe** [comment]
> > > > > > > Server upgrades: Server selection menu improvements: add the ability to save the server address from the list of public servers. Why: this makes it much more convenient to enter the desired server without throwing through the list of servers.
> > > > > > 
> > > > > > 
> > > > > > Use the eye icon to to hide/unhide servers.
> > > > > 
> > > > > 
> > > > > loading a list of servers is a very fickle thing, your idea is hidden interfering servers to see only the ones you need, very stupid
> > > > 
> > > > 
> > > > It's not my idea, It's what implemented already.
> > > 
> > > 
> > > this is a feature request for convenience
> > 
> > 
> > Your suggestions is less convenient for people tbh.
> > Also if you can't load the list of servers, there a large chance that you can't even play online.
> 
> 1 winding the list of serers back and forth to find the right one is not very convenient 2 loading the list of servers very often lags, which is why some active servers are not shown

If you hide the servers you don't use then you can't see them, meaning it won't load them.

**Comment by ziszlo** [comment]
> 

I propose a way to save the server address and not close all the others

**Comment by itcannotbe** [comment]
That is less convenient because the server owners can at any moment change the server address.

**Comment by ziszlo** [comment]
> 

hard to believe show evidence

**Comment by ziszlo** [comment]
> 



> Это менее удобно, потому что владельцы серверов могут в любой момент изменить адрес сервера.

okay convinced

**Comment by ziszlo** [comment]
> That is less convenient because the server owners can at any moment change the server address.

okay convinced

**Comment by itcannotbe** [comment]
> > That is less convenient because the server owners can at any moment change the server address.
> 
> okay convinced

https://github.com/Anuken/Mindustry/commits/master/servers_v7.json

**Comment by ziszlo** [comment]
> > > > > > > > Hints when entering the server: To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser. Why: This will make it possible for servers with mods to exist.
> > > > > > > 
> > > > > > > 
> > > > > > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > > > > > 
> > > > > > 
> > > > > > at the moment, accessing any server with mods seems to be an incredibly complicated way for which each of the desired players needs to manually find the required mod and install it in the client, which is why servers with mods usually have 0-1 players simplifying the way to access such servers would help them exist, there are a huge number of chic mods, but because of the difficulty of joining a server with such mods, everything is terrible. we need a new tool that is understandable to a large audience for entering the server with mods, the current tools in the game are too complicated for a large audience
> > > > > 
> > > > > 
> > > > > There are already multiple ways a server owner can implement this. And it's just up to the server owner to actually do it.
> > > > 
> > > > 
> > > > these methods are terrible and difficult, the game needs a new user friendly way to enter the mod server
> > > 
> > > 
> > > From a security standpoint, forcing people to download mods themselves is a better option than an automatic download.
> > 
> > 
> > you absolutely do not understand me I offer tips on what mods to download so you can enter this server now it is very difficult to understand and find the right mod hints would make this much easier
> 
> The server can just mention the repository of the mod then you can just use the built in way to download mods from github. How hard can that be realistically?

hard to believe show evidence

**Comment by ziszlo** [comment]
> > > That is less convenient because the server owners can at any moment change the server address.
> > 
> > 
> > okay convinced
> 
> https://github.com/Anuken/Mindustry/commits/master/servers_v7.json

what is that

**Comment by ziszlo** [comment]
I understood the pointlessness of saving the server address, answer the mods on the servers, show the guide how to simply enter the server with mods

**Comment by itcannotbe** [comment]
The server just needs to send you a message someway that you need to install some mod, for example

Exotic-Mod by Bluewolf

Which can be downloaded from https://github.com/BlueWolf3682/Exotic-Mod

So you can just do the following: 

![Screenshot_20220427_181449_io anuke mindustry](https://user-images.githubusercontent.com/45280919/165496895-06e74d12-b7cd-4b63-9e64-6438a1496bfb.jpg)

![Screenshot_20220427_181454_io anuke mindustry](https://user-images.githubusercontent.com/45280919/165496945-d54850bb-24bc-42db-af25-1dd7cb4fc3dd.jpg)

![Screenshot_20220427_181504_io anuke mindustry](https://user-images.githubusercontent.com/45280919/165496986-b0ce2f71-d472-455a-b2bb-dcb9ad332223.jpg)

![Screenshot_20220427_181509_io anuke mindustry](https://user-images.githubusercontent.com/45280919/165497027-34983de4-f327-4be3-8bed-93c405c83a7d.jpg)

![Screenshot_20220427_181521_io anuke mindustry](https://user-images.githubusercontent.com/45280919/165497051-40d6764d-2036-45ad-943c-3038c96e7c53.jpg)

Then restart the game and go try to join the server again.

**Comment by ziszlo** [comment]
wonderful
but again, you yourself said the most important problem
"The server just needs to send you a message someway" !!!!!someway!!!!! somehow the serer needs to be conveyed to you
which mod to download.
this is my idea of ​​unifying for all servers a hint of what mods to download, do you understand?

**Comment by itcannotbe** [comment]
> wonderful but again, you yourself said the most important problem "The server just needs to send you a message someway" !!!!!someway!!!!! somehow the serer needs to be conveyed to you which mod to download. this is my idea of ​​unifying for all servers a hint of what mods to download, do you understand?

You don't even need to do that, you can just kick the person who doesn't have the mod on join with the message that the person need to download the mod first or just straight up display it on the server listing.

**Comment by itcannotbe** [comment]
There is already a line provided for a message a server owner can set.
![Uploading Screenshot_20220427_184137_io.anuke.mindustry.jpg…]()

**Comment by ziszlo** [comment]
why don't you understand?
there are almost no servers with mods due to the high chance of an error at the time of some way of messaging him and searching for the right mod.
I suggest adding mod links to the game, something like
( /modbrowser:exotickmod ) in one click on which you can immediately start downloading the mod and after completion go to the server, simplifying the number of actions to 1

**Comment by ziszlo** [comment]
or add the ability to copy text from the hint window which mod you need to install

**Comment by ziszlo** [comment]
mmm

**Comment by AMindustryPlayer** [comment]
So many long comments that frustrates the mobile phone users like me bruh

**Comment by AMindustryPlayer** [comment]
> > wonderful but again, you yourself said the most important problem "The server just needs to send you a message someway" !!!!!someway!!!!! somehow the serer needs to be conveyed to you which mod to download. this is my idea of ​​unifying for all servers a hint of what mods to download, do you understand?
> 
> You don't even need to do that, you can just kick the person who doesn't have the mod on join with the message that the person need to download the mod first or just straight up display it on the server listing.

Basically, the server usually automatically kicks the people without the proper mods, and then sends them a special "disconnected" message which tells them what mods are unnecessary and what mods are missing. However, the message do not neither ask them to download the mods which are missing nor configure the mods. To do so, it just need to be modified a bit

**Comment by AMindustryPlayer** [comment]
> Hints when entering the server: To give the opportunity, when creating a server with a mod, to specify the used mod in the mod browser, when a user logs in without a mod, he gets a warning that he needs to install the mod shown in the mod browser. Why: This will make it possible for servers with mods to exist.

Why not directly to ask the person to download the missing mods and configure the mods instead of giving a warning to remind the person what mods are missing or excessive?
