### ISSUE TITLE
Improve File save format and steam cloud (backup)

### ISSUE THREAD

**Issue by Nunting** [Anuken/Mindustry-Suggestions#3521]
### Describe what you would like changed, and why.

First, I'm using auto save. I found it while organizing a few things.

Too many files are uploaded to steam cloud.

![steam2](https://user-images.githubusercontent.com/77824588/165458190-3e8a282e-89a0-48f1-a353-162189072bfc.PNG)

As you can see from above.

![steamcloud](https://user-images.githubusercontent.com/77824588/165458122-1251d0a3-6cd7-4fc8-9179-74f0a02d5d7f.PNG)

Many files are uploaded there.

**1. maps.** custom map file. It is entered in the order of storage, not name, as in schemetics.

**2. campaign-sector**. I don't know why, but there are two sector and sector-backup files. My data file also has two files on one map. Why is it divided into two? I don't know if it's necessary. 

**3. schemetics.** This is stored as a number, not the name of the schemetics. This seems to be the reason why there are so many files in the schemetics. Even if it's the same file, it seems that the number varies depending on the storage method, so the files are stored in duplicate, isn't it?

**4. settings.** uuid, research, and various information are stored.

As such, storing maps and schemetics in numerical form is very difficult to distinguish which file I want. It's also affecting other places.

### Describe the changes you want to propose. Include possible alternatives.

**First, file save format.**

When you make it in the game, or you bring it up from the outside. Save by their name, not in order or in a special way.

This makes it easy to tell what users want, and it's also very easy to manage files out of the game.

Of course, the campaign sector is excluded. What I want is a change in maps and schemetics.

**second. steam cloud.**

1. Save only settings. Settings only store very important information such as research and uuid. Saving only this does not interfere with campaign or server participation.

2. Upload files in zipdata format. There is already zipdata in the steam-mindustry folder. Upload all the data at once by marking the date and time of saving in front of this file. (By the way, will the zip file be uploaded to the steam cloud?)

3. If the zip file cannot be uploaded. Compression of maps and schemetics files is required. It doesn't mean zip. It also doesn't mean that we should get rid of msch and msav. We need a means to retrieve their information into one file. The size of the file will increase, but it will be very easy for users to load multiple files. 

Of course I know that there is a separate way to store data within the game. I only use it, too.

But is there a reason to move files by hand uncomfortably with a simple method called steam cloud? Steam cloud exists to save me the trouble of saving files to usb or email. But now... There is considerable discomfort.

**Comment by end-me-please** [comment]
It’s one file per schematic. Why would it have to be less? Every time you edit one schematic, the game would have to re-upload all other schematics.
19 MB of cloud Storage Space is next to nothing. 

and i don’t think that there are duplicates among the schematic files, it’s just that you have that many schematics

**Comment by Nunting** [comment]
> It’s one file per schematic. Why would it have to be less? Every time you edit one schematic, the game would have to re-upload all other schematics. 19 MB of cloud Storage Space is next to nothing.
> 
> and i don’t think that there are duplicates among the schematic files, it’s just that you have that many schematics

1. Unless you and I are playing different games, the storage capacity cannot be different. Mindustry has a capacity of 2GB.
2. No matter how few files you have, you should download at least dozens or hundreds of them yourself. You also need to modify the name of the file, move it... It takes a very long time.

**Comment by itcannotbe** [comment]
> This is stored as a number, not the name of the schemetics. This seems to be the reason why there are so many files in the schemetics.
> Even if it's the same file, it seems that the number varies depending on the storage method, so the files are stored in duplicate, isn't it?

It's not even just numerical, it's basically unix time.

**Comment by Nunting** [comment]
> 

Yes, this is the proposal, and this is where the direction of change is presented. 
Is it technically impossible?

**Comment by Nunting** [comment]
> > This is stored as a number, not the name of the schemetics. This seems to be the reason why there are so many files in the schemetics.
> > Even if it's the same file, it seems that the number varies depending on the storage method, so the files are stored in duplicate, isn't it?
> 
> It's not even just numerical, it's basically unix time.

It was simply said.

**Comment by itcannotbe** [comment]
Saving schematics by name has more challenges:

Duplicates and how to handle them.
How to actually identify duplicates.
How to present similarities of "duplicate" files.

**Comment by itcannotbe** [comment]
> maps. custom map file. It is entered in the order of storage, not name, as in schemetics.

'Cause autosaves are a thing.

> Campaign-sector. I don't know why, but there are two sector and sector-backup files. My data file also has two files on one map. Why is it divided into two? I don't know if it's necessary.

Those are called back-ups.

> schemetics. This is stored as a number, not the name of the schemetics. This seems to be the reason why there are so many files in the schemetics. Even if it's the same file, it seems that the number varies depending on the storage method, so the files are stored in duplicate, isn't it?

It's saved with a suffix of unix time.

**Comment by numer99** [comment]
I personally don't see any problem of this when I use the steam cloud
