### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by M00Dz** [Anuken/Mindustry-Suggestions#3522]

**Comment by end-me-please** [comment]
Built-in cloud sync is literally in the "do not suggest" list

**Comment by itcannotbe** [comment]
i think it would be a good idea if people actually read and understand the readme before ticking the box that says "I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category."

**Comment by guncatt** [comment]
> i think it would be a good idea if people actually read and understand the [readme](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) before ticking the box that says "I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category."

Bruh I didn't even know what cloud sync was until now lol.

**Comment by numer99** [comment]
why on earth did you check the boxes when none of them are true

**Comment by THEGAMER-10n** [comment]
Cloud saves need servers.
Servers need money to operate.
Therefore anuke doesn’t want to have cloud saves at other platforms.

If you want them, just ~pay~ play at steam.

**Comment by Just-a-Unity-Dev** [comment]
just export/import manually. not that hard imo

**Comment by AMindustryPlayer** [comment]
> just export/import manually. not that hard imo

Yes, you can already do it yourself through tutorials. And built-in cloud sync is in the "do not suggest" list bruh

**Comment by OnyxFinger** [comment]
Bruh I never even noticed this one
