### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by aimancreator3** [Anuken/Mindustry-Suggestions#3523]
### Describe what you would like changed, and why.

It is a cool game bug really wish you updated the app onto google play
Like i am a fan of the game but not smart enough to do sdk for Android
So it really appreciate you update the google play version 

### Describe the changes you want to propose. Include possible alternatives.

-

**Comment by itcannotbe** [comment]
There is no update yet, so why you expect the GooglePlay Version to get an update?

**Comment by end-me-please** [comment]
You can download the V7 alpha for Android on the itch.io page.

No one knows when the full V7 release (or even a new pre-alpha release) will happen. (I don’t think anuke knows either)

**Comment by itcannotbe** [comment]
> Anyways, you shouldn't have posted the feedback here bruh, post it somewhere(e.g. Reddit) except here.

Actually ...
![Screenshot_20220428_211002](https://user-images.githubusercontent.com/45280919/165759615-95d72d86-3252-4b53-b171-8e1be11977c7.jpg)

**Comment by numer99** [comment]
the suggestions are mostly for the game _mindustry_, not for google play
