### ISSUE TITLE
Schematic's Tiles Tag

### ISSUE THREAD

**Issue by NPGSIX** [Anuken/Mindustry-Suggestions#3524]
### Describe what you would like changed, and why.

*_Not really changing anything, just improving on what's already there_. 

In the `Schematic`'s menu, there's a `tag` menu where we can tag a schematic based on it's output or input. Now, what if we can tag a schematic based on it's tile requirements. Wouldn't it be great if we can just filter out our schematic mess based on our map's environment?

`(eg.)` 
> **• Easy Search** 
We're on a sector "**Windswept Island**" (lots of water and sand) we can filter out & just select the schematics that take advantage of sand and/or water. 

### Describe the changes you want to propose. Include possible alternatives.

How I imagine it would be:
![Picsart_22-04-29_00-04-15-858](https://user-images.githubusercontent.com/104565976/165808710-6ce1451e-10f3-463f-a96b-c9cb637c4ed9.jpg)
![Picsart_22-04-29_00-51-44-958](https://user-images.githubusercontent.com/104565976/165808739-16159a85-0dca-4ac6-826f-63a9f9b72e39.jpg)
![Picsart_22-04-29_01-21-01-045](https://user-images.githubusercontent.com/104565976/165811402-ccd60ed5-94a4-4ab9-a7db-5e1377eb7da9.jpg)

**Comment by numer99** [comment]
can't we just replicate this with keywords of "sil" or "sand" etc. etc.
