### ISSUE TITLE
Friendly fire

### ISSUE THREAD

**Issue by THEGAMER-10n** [Anuken/Mindustry-Suggestions#3526]
### Describe the content or mechanics you are proposing.

Give lasers and (artillery?) the ability to damage friendly units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

pros:
1. Buffs and Nerfs certain units.

cons:
1. Griefing made easier
2. Why add this in the first place...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by guncatt** [comment]
Game rule maybe?

**Comment by WilloIzCitron** [comment]
yes and its abusive to toxic players who use this feature

**Comment by THEGAMER-10n** [comment]
Why did I make this suggestion…
