### ISSUE TITLE
Build feature

### ISSUE THREAD

**Issue by SydeathVx** [Anuken/Mindustry-Suggestions#3527]
### Describe the content or mechanics you are proposing.

When being in a unit that can't build you are able to use units such as Polies to build for you, you can build on long distances and these units will go there and build. Something everyone has noticed that Polies or Megas will build when a building is in construction, units should be able to build in schematic form

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Will help players from inconvenience of going out of unit form and onto a unit that can build, and also you can build in places without running back and forth, or being inconvenienced by finding a logic where units such as Polies that won't go back home on their own when you spawn back in base

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
This suggestion is legit better than 99.9% of the other stuff on here
