### ISSUE TITLE
Seamless Logic Displays

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3528]
### Describe what you would like changed, and why.

The way how Logic Displays render, so that the displays look more clean for vanilla clients. Also would make large Logic Art seamless and perfect, and allows for abnormally shaped displays.

### Describe the changes you want to propose. Include possible alternatives.

Make the Logic Displays visually connect side-by-side. Connected displays are still individual displays, but render as if they are one, and drawing is still relative to the specified display, not all displays combined with the given display.

Connecting displays are either done manually as if you were linking two together, or automatically via setting. Clicking a display activates the linking process, but clicking again WON'T unlink all sides in the case the display is an interface by logic.

Display Connection Nets can only have up to 25 connections by default, 16 for Large Logic Displays.

**Comment by oinkymoo** [comment]
this would likely require a significant rework to logic displays. 0,0 on displays is not the corner of the block it is located in, but the corner of the screen itself. that's why large displays have an extra 16 pixels over double the dimensions of a small

**Comment by IxGamerXL** [comment]
> this would likely require a significant rework to logic displays. 0,0 on displays is not the corner of the block it is located in, but the corner of the screen itself. that's why large displays have an extra 16 pixels over double the dimensions of a small

Perhaps displays can be scaled by the screen's size.
