### ISSUE TITLE
New Buildings

### ISSUE THREAD

**Issue by SydeathVx** [Anuken/Mindustry-Suggestions#3529]
### Describe the content or mechanics you are proposing.

Shield Generator: Units around the generator will gain a shield. There's quasars but this would be better than building seeing it die and waiting for it to be near one. Only advantage of a quasar against this is that they can always give units shields inside enemy territory, give shields while following units or you don't have to retreat to generators if you want a shield, a quasar is just more convenient.

Enhancer: Building that can enhance units. Increase Hp, Shield Capacity, Armor, Damage.

Modifier: Modify unit weapons, like lower attack speed for more damage. Add parts to units that can enhance weapon performance.

New mode:
[No turrets, Only Units: Post v7 update]: no turrets are allowed, use units to defend units

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Survival units have the option to get stronger, players should also have the option to have this. To be able to counter the rising difficulty to fight enemies with units.
The v7 update with the new unit controls this new mode will help players develop tactics and strategy

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Enhancers and modifiers sound like #583 but units.

**Comment by SydeathVx** [comment]
> Enhancers and modifiers sound like #583 but units.

i legit didn't know

**Comment by SydeathVx** [comment]
for real, i only did this when i was at a high difficulty sector and crawlers were hard to kill they had such a high shield capacity and hp capacity so i did that

**Comment by BalaM314** [comment]
Sounds like it would fit well with the new payload tech in v7.
