### ISSUE TITLE
Unit launcher for 6.0

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry-Suggestions#353]
**Describe the content or mechanics you are proposing.**

Add a turret that shoots units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would allow players to launch units over defences without having to build intentional weaknesses into your front line defense.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ILiekMelons** [comment]
(i also think it would be absolutely hilarious seeing units flying into enemy bases)

**Comment by ILiekMelons** [comment]
![Screenshot_20200729-163326_Discord.jpg](https://user-images.githubusercontent.com/49169907/88820481-45e4d100-d1b9-11ea-8e76-1e6823e8ff7c.jpg)

**Comment by Anuken** [comment]
> It would allow players to launch units over defences without having to build intentional weaknesses into your front line defense.

v6 will use unit transports for this.
