### ISSUE TITLE
Deconstruction Refund

### ISSUE THREAD

**Issue by Stefanidze-Kotik** [Anuken/Mindustry-Suggestions#3531]
### Describe what you would like changed, and why.

Please, return 100% deconstruction refund. I think it makes game not more hard but definitely more stressful. With this penalty there is no motivation for rebuld and optimisation, one of the things that i think this game is about. Thanks.

### Describe the changes you want to propose. Include possible alternatives.

I am proposing 100% deconstruction refund. Propably it can be 90% or 80%.

**Comment by yozozchomutova** [comment]
Singleplayer: You can rebuild/optimise once you get more resources, so there's no need 100% dec. refund.
Multiplayer(PVP, Attack, Survival): This won't motivate people either. People are more likely to speedrun stuff in these mode. Most likely, they won't spend time with rebuilding/optimising...
