### ISSUE TITLE
Armor system of units

### ISSUE THREAD

**Issue by WilloIzCitron** [Anuken/Mindustry-Suggestions#3532]
### Describe the content or mechanics you are proposing.

armor system of units are the defence how the armor got breached and the unit explodes

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

example reign had thick front armor but the back armor is thin also if thorium projectile hit on back armor its destroyed

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BalaM314** [comment]
I think he's trying to propose directional armor.

**Comment by itcannotbe** [comment]
> I think he's trying to propose directional armor.

More likely he's suggesting weak spots that can be use to oneshot.

**Comment by WilloIzCitron** [comment]
wot/wt style
