### ISSUE TITLE
Directional lighting?

### ISSUE THREAD

**Issue by Eldeston** [Anuken/Mindustry-Suggestions#3533]
### Describe the content or mechanics you are proposing.

The shading of blocks change as the light changes direction giving a sense of time and making the game feel more dynamic.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

With 2D normal maps, directional lighting can be applied to the game giving a dynamic feeling and a sense of time passing by as you play the game.

Example Image:
![R](https://user-images.githubusercontent.com/59617287/166219983-3a369856-8d16-4de6-a028-e3d228866d94.jpg)

Not sure about adding specular and the others though which might be too much, but I'd like to see the directional lighting in the game from 2D normal maps.

Source:
https://theartsquirrel.com/31/lighting-2d-art-with-normal-maps/

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WilloIzCitron** [comment]
its quite going lag on low end devices

**Comment by blaster77145** [comment]
maybe it can be disabled, like shield graphics can? otherwise I think this would be awesome

**Comment by Eldeston** [comment]
> its quite going lag on low end devices

Not really actually if it's just the diffuse lighting.

**Comment by WilloIzCitron** [comment]
shader

**Comment by Eldeston** [comment]
> shader

> Not really actually if it's just the diffuse lighting.

**Comment by WilloIzCitron** [comment]
post processing

**Comment by Eldeston** [comment]
> post processing

Bloom, which already is in Mindustry, is a post processing shader. What point are you trying to make? Diffuse lighting or directional lighting is much more simpler than bloom. In implementation it would look like this:
```glsl
uniform vec3 lightDir; // Normalized light dir
uniform vec4 lightCol; // For day and night color tint

uniform sampler2D texture; // Main albedo texture
uniform sampler2D normalMap; // Normal map in 0:1 range

varying vec2 texCoord; // Texture coordinates

void main(){
    vec4 albedo = texture2D(texture, texCoord);
    vec4 normalMap = texture2D(normalMap, texCoord);

    // Convert the 2D normal map from 0:1 range to -1:1
    // Only the first 3 channels are used but the 4th channel can be utilized for other maps such as emissive maps.
    // We can also make the normalMap use only 2 channels for the normals and spare the other 2 channels for emissive maps and other things, but I doubt Mindustry would need it.
    vec3 normal = normalMap.xyz * 2.0 - 1.0;

    // Get the clamped dot product of the lightVec and normal and multiply it with lightCol
    vec3 diffuseCol = lightCol * max(0.5, dot(normal, lightVec));

    // Multiply albedo with the diffuse col and output final color to gl_FragColor
    gl_FragColor = vec4(albedo.rgb * diffuseCol, albedo.a);
}
```
Compared to bloom, it's much more simpler and fast in implementation.
