### ISSUE TITLE
add proxy function for mod browser

### ISSUE THREAD

**Issue by Ah-Bo** [Anuken/Mindustry-Suggestions#3536]
### Describe what you would like changed, and why.

sorry for my poor English,hope you guys could understand me.
I'm a mindustry player in china,and I'm not able to download mods using mod browser because GFW banned `raw.githubusercontent.com`
Though I enable a global proxy, it seems that it doesn't work for mindustry(btw i use linux).

### Describe the changes you want to propose. Include possible alternatives.

another solution is to allow players to change the mod list link.
For example `https://github-do.panbaidu.cn/https://raw.githubusercontent.com/Anuken/MindustryMods/master/mods.json`does work for me

**Comment by itcannotbe** [comment]
The problem with this approach is that those web servers aren't "directly" controlled by the dev.
