### ISSUE TITLE
Adding a new stat for StatusEffect "mineSpeedMultiplier".

### ISSUE THREAD

**Issue by 3Snake3** [Anuken/Mindustry-Suggestions#3537]
### Describe the content or mechanics you are proposing.

This stat will allow mining units to mine ores faster.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If there is a stat in the game that increases the build speed of unit, then I think adding a stat that increases the mining speed would be a good solution.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by guncatt** [comment]
But isn't there already one?

**Comment by 3Snake3** [comment]
No.

**Comment by RFAC-Productions** [comment]
Doesn't Overclock work though?

**Comment by 3Snake3** [comment]
> Doesn't Overclock work though?

Overclock increases movement speed, reload speed and damage.
