### ISSUE TITLE
Fix retusa's torpedoes

### ISSUE THREAD

**Issue by rylid-umil** [Anuken/Mindustry-Suggestions#3539]
### Describe the content or mechanics you are proposing.

Fix retusa's torpedo lighting, the trail and bullet of retusa's torpedoes **doesnt** have any glow but it should have
instructions:
make a world and spawn retusa and rthen shoot retusa torpedoes after turning bloom on if not on already. then you see that there is no glow

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this is just some kind of bug fix and would make it fit a bit more with the game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
this is not a repo for bug reports, go to https://anuken/mindustry/issues
