### ISSUE TITLE
Unit teleporter.

### ISSUE THREAD

**Issue by TacticalAlpha** [Anuken/Mindustry-Suggestions#354]
**Describe the content or mechanics you are proposing.**
A large pad? which teleports units over long distance. And it's drop animation is the same as the enemy wave drop point is. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
If your base is large and the units can't make a route to get out or you want to make a full defense without exit and entrance, this teleporter will do the work.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Not a fan of teleporters; for transporting small groups, you can use unit carrier(s), and for large ones you'll be forced to set up doors.
