### ISSUE TITLE
Improve campaign mode

### ISSUE THREAD

**Issue by dude404** [Anuken/Mindustry-Suggestions#3540]
### Describe the content or mechanics you are proposing.

Hello Anuke, 
First I'd like to thank you for this game I love it and I play a lot (mostly solo) on Laptop and mobile. 

I was thinking about the campaign and the way you aquire new technologies. Right now in v7 it is too easy, once you have a map that produce everything you can unlock the whole tech tree very fast.. and that "breaks" the challenge. 

Here is what I suggest :
- you earn points (let's call it Prestige Points = PP ) by completing maps of the campaign
- for each map you can consider playing it "normal" (some PP to earn)  or "hardcore" (some more PP to earn), this would make you go back to map you already played once
- Hardcore = more threat from ennemies, no starting ressources (it's to easy to win if you start with 4k of everything) 
- to unlock Technologies you need to spend PP, this make you play lots of maps
- when you have unlocked the whole tree you could consider acquiring "Skins" or "Badges" or other stuff that do not impact game balance 

More ideas 
- World Ranking could be based on PP 
- PVP battle matching can be setup based on PP, this would open PVP to newbies 
- PVP Free mode with all technologies unlocked could also be available 

And even more ideas 
- more than "survive 50 waves" or "destroy ennemy base" you could have scenarios like "get 5'000 thorium"  surviving ennemies waves 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Gameplay is not really changed 
You spend more time with less technologies and this makes a better challenge 
You have to spend wisely your PP to choose the technology you need 
Technology tree makes more sense 
The campaign mode would be more interesting IMO 

Thanks for reading :) 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
So what does PP do? A harder research system?

So why create PP when you can modify the research system?

**Comment by dude404** [comment]
Yes basically the research is harder and longer, it forces you to play with "low technologies"  and this make the game more challenging & fun

**Comment by itcannotbe** [comment]
Long and Hard? PP doesn't actually achieve that.

It's more of a nuisance. Both to the player and the developer.

**Comment by dude404** [comment]
it is just a different way to unlock technos (spending PP instead of ressources) and make the tech tree more interesting because you don't unlock it entirely in 3 games. 
I don't see the nuisance for developper ^^ and for player it allows more scenarios different than "rush cyclone" or "rush T3 units" to win almost every maps

**Comment by genNAowl** [comment]
> allows more scenarios different than rush cyclone or rush T3 units

Why not just disable launchpads to uncaptured sectors and launch loadout instead?

Then you'll be limited to the technology achievable with the ores on the map itself, providing a challenge as well.

**Comment by AMindustryPlayer** [comment]
It is a good idea, but it'd be better if we put this to later versions or even to the sequel of Mindustry(this idea would be a revamp to the game)

**Comment by kapzduke** [comment]
the worst suggestion so far

**Comment by kapzduke** [comment]
also you'll never get a lot of pp in real life HAHAHAHAHAHAHAHAH
