### ISSUE TITLE
Geradores de energia

### ISSUE THREAD

**Issue by Blspf** [Anuken/Mindustry-Suggestions#3541]
### Describe the content or mechanics you are proposing.

Poderia ter um gerador de energia que gera com agua, igual a uma hidroelétrica

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Eu acho que ficaria legal .
Não tenho muitas ideias dessa hidroelétrica

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BalaM314** [comment]
Would need to add flowing water also.

**Comment by RFAC-Productions** [comment]
Using Translate, he said that he wants to have more power generators in the game, specifically ones that do Hydroelectricity.
