### ISSUE TITLE
equation operation

### ISSUE THREAD

**Issue by twos98** [Anuken/Mindustry-Suggestions#3542]
### Describe the content or mechanics you are proposing.

make it so you can do multi-equation operations using the operation "command" in a processor like 2+3*5-8 as an example of what it would do and to add another equation there will be a + symbol after the equation you selected, when pressing it you will get a new equation selection drop down and another text box to put the number are variable in

im sorry if some of this dosent make sense i tried my best to explain it 

also refer to the screenshot to see what logic command im talking about
![image](https://user-images.githubusercontent.com/98290299/167041331-888c4678-11d9-42ce-a3d5-f5b86e8fd997.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this will make say sin waves and other complex logic math things easier to do with less code and plus it will let you put in more code...this might need a limit of say 5 equations per operation "command" so you cant overload a processor using only 1 "command" 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
it's intended to be like this. irl processors don't understand stuff like `a / d + b * c`, they only understand this (just an example, not real assembly code):
```
e = a / d
f = c * b
result = e + f
```
```
