### ISSUE TITLE
Water extractor and floors

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#3543]
### Describe what you would like changed, and why.

We all know people use water extractor too often due to its convenience.
So remove the convenience. But not too much so it is still an option if needed.

### Describe the changes you want to propose. Include possible alternatives.

Add a floor softness attribute that water extractor uses.
This takes a percent off the total output of the wext by how "hard" the floor is - for example, placing it on stone would yield ridiculously bad efficiencies (maybe even 0%) but placing it on dirt yields full efficiency.
This would severely limit the conveniency of wexts on many regular maps while making this little low power weak drill act more like it should.

**Comment by end-me-please** [comment]
Doesn’t this literally already exist (salt has 25% efficiency for example, I think)

**Comment by OnyxFinger** [comment]
> Doesn’t this literally already exist (salt has 25% efficiency for example, I think)

yes, however he seems to propose this to a greater extent. However, I am against it, since water extractors aren't OP currently. The reason why so many use - to an abusive extent - is that's it's convenient. In fact, it being a convenient way to get water is its whole purpose. If you remove it's conveniency, then it's just a weaker pump.

**Comment by end-me-please** [comment]
Some say that they are too convenient, maybe it is, but I certainly don’t want to see the mess players would create without them

**Comment by BlueWolf3682** [comment]
> yes, however he seems to propose this to a greater extent. However, I am against it, since water extractors aren't OP currently. The reason why so many use - to an abusive extent - is that's it's convenient. In fact, it being a convenient way to get water is its whole purpose. If you remove it's conveniency, then it's just a weaker pump.

I do not propose this to a greater extent. It would be much worse *on many floor tiles*, but would work with no drawbacks on the aforementioned softer floors. 
If you have a better designed map, you will either have water to pump or plentiful soft tiles.

**Comment by end-me-please** [comment]
nothing short of 0% efficiency will stop people from just spamming more to compensate

**Comment by BlueWolf3682** [comment]
Metal floors would have zero efficiency. Hard floors such as stone and slate would have 0 or 10% efficiency.

**Comment by BlueWolf3682** [comment]
~~actually why the heck can you pump groundwater out of a fucking slab of metal~~

**Comment by Rex-Hm** [comment]
No more nerfs needed

**Comment by Anuken** [comment]
> actually why the heck can you pump groundwater out of a fucking slab of metal

I don't know if you've seen this, but I did make them have 0% efficiency on metal at some point. People complained. A lot. At this point I'd rather just leave people alone with their horrible water extractor spam schematics, I'm tired of arguing about it.

**Comment by BlueWolf3682** [comment]
yikes

**Comment by itcannotbe** [comment]
Good things there's no water extractor like block on erikir.

Right?

**Comment by guncatt** [comment]
Water extracter was murdered enough please stop.

**Comment by itcannotbe** [comment]
> Water extracter was murdered enough please stop.

It's not even murdered.
