### ISSUE TITLE
way too early Tantros mechanic suggestion that i am afraid to forget so im suggesting now

### ISSUE THREAD

**Issue by FungusVendor** [Anuken/Mindustry-Suggestions#3544]
### Describe the content or mechanics you are proposing.

the life on Tantros could be more than just aesthetic. i imagine that some natural resources available would not be in the form of ores, but instead invisible ground chemicals. how would you detect these ground chemicals? life. certain mixes and densities of species will thrive on different ground chemicals, acting as telltale signs for you. this could also be used to introduce a new obstacle of certain species being a nuisance which needs to be removed before the resources can be extracted, however that may be done.
for example, if you see a patch of visibly denser blue starfish with a few orange corals (i dont know their names) you can be sure that there is something valuable in the earth, and you have to build the appropriate extractors.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think its quite self-explanatory how this would improve the experience. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by guncatt** [comment]
I like it.
