### ISSUE TITLE
Water Defense Walls

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry-Suggestions#3545]
### Describe the content or mechanics you are proposing.

A type of walls that can be build in water (any type of water tile).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be good to prevent the naval units to go directly to the core.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SlavicProgrammer2137** [comment]
Isn't that the point of naval units that they can bypass walls trough water?

**Comment by Kaviaki** [comment]
> Isn't that the point of naval units that they can bypass walls trough water?

Well, yes, but, what about water levels, I mean, would be usefull to have a block that can be placed in any water tile. Which can be good to change the path of the units.
