### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by squi2rel** [Anuken/Mindustry-Suggestions#3548]
### Describe what you would like changed, and why.

![image](https://user-images.githubusercontent.com/102400902/167295847-7254e3ea-6b0b-4199-9f2a-b6425e1317ab.png)
This tutorial cannot be translated into other languages.

### Describe the changes you want to propose. Include possible alternatives.

move it to .properties

**Comment by xem8k5** [comment]
Yes they are not in bundles
