### ISSUE TITLE
(Keyboard-only) "Ignorant" shooting mode

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#355]
**Describe the content or mechanics you are proposing.**
If the player holds a certain button (Alt?) while starting shooting, the player shoots, even if there was a mineable ore or an interactable block underneath the cursor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In case if players are fighting above a base or a large ore patch, makes the accidental mining/block select not happen and not hamper the battle.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Kyllingene** [comment]
I like it. I personally find it quite annoying when I'm building and I start mining accidentally, and have to either move far enough away to break the mining, or try to break nonexistent blocks.
