### ISSUE TITLE
Disable FoW on sector capture

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#3552]
### Describe the content or mechanics you are proposing.

Once you capture a sector, the FoW mechanic should be disabled on the sector.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

FoW only serves to be a minor annoyance when the sector is done and has no pourpose.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ilikepie04** [comment]
Ok I might be stupid, what is FoW?

**Comment by Bottinator22** [comment]
Fog of War

the thing that limits your vision to what's near your things

**Comment by itcannotbe** [comment]
But that's kinda weird for FOW to just vanish just because you conquered the sector.

**Comment by GitHubUser-B** [comment]
> But that's kinda weird for FOW to just vanish just because you conquered the sector.

You are definetly a troll, you try to find the smallest thing to complain about a sugestion, dude, even REAL RTS games have this mechanic, stop being like this! The same thing aplies to other people like you

**Comment by itcannotbe** [comment]
Does those RTS games have enemy recapture mechanics?

**Comment by GitHubUser-B** [comment]
> Does those RTS games you referr to have enemy recapture mechanics?

RTS in general

**Comment by itcannotbe** [comment]
Most RTS doesn't have enemy recapture mechanics as map used are most of the time, standalone (Doesn't affect other map).

**Comment by itcannotbe** [comment]
And that's somehow relevant because....?

This isn't your standard RTS game, where one map doesn't affect the next one.

**Comment by GitHubUser-B** [comment]
@itcannotbe  Honestly, i'm not totaly against you, there are some sugestions that deserve those kind of answers, and you also made a sugestion that got a pile of dislikes but i agree with it, people only complained about your sugestion because they get EZ minerals from this broken mechanic, this should be fixed, also those miner units are the biggest cause of lag in the multiplayer servers of the game!

**Comment by GitHubUser-B** [comment]
> And that's somehow relevant because....?
> 
> This isn't your standard RTS game, where one map doesn't affect the next one.

And how fog of war affects the other maps in this "non-stardard"  RTS game, pal?

**Comment by GitHubUser-B** [comment]
> And that's somehow relevant because....?
I'm tired of you acting like a jerk for almost everyone

**Comment by GitHubUser-B** [comment]
@itcannotbe I plan to do the same with gray mario furry but I'll wait for her to change into her pure demon form again first

**Comment by Bottinator22** [comment]
> Does those RTS games you referr to have enemy recapture mechanics?

Sectors are only attacked again if they're vulnerable
