### ISSUE TITLE
Add Erekir Beta to Steam

### ISSUE THREAD

**Issue by blaster77145** [Anuken/Mindustry-Suggestions#3553]
### Describe the content or mechanics you are proposing.

The Erekir Beta be moved to Steam's beta menu.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would make it much easier for modders to try this beta in a realistic environment, plus much easier to tweak

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> This would make it much easier for modders to try this beta in a realistic environment, plus much easier to tweak

It's not. Also not everyone enjoys the game crashing on them everynow and then.

**Comment by Anuken** [comment]
Erekir is not a beta, it is not even a proper alpha. There are not builds available for it *anywhere.*

![image](https://user-images.githubusercontent.com/10100000/167321755-1b2bd853-e39c-4a09-bd80-4a0666964cf6.png)

**Comment by WilloIzCitron** [comment]
dumb people want get erekir on steam
