### ISSUE TITLE
Barrier block

### ISSUE THREAD

**Issue by Lkk9** [Anuken/Mindustry-Suggestions#3555]
### Describe the content or mechanics you are proposing.

new block, can only be placed from the map editor. invisible and unbreakable, stops any type of unit (ground or air) from crossing it

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

new opportunities for mapping

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2380

**Comment by guncatt** [comment]
Enemy gaming

**Comment by EclipseTheOldOne** [comment]
Just use shield projector

**Comment by WilloIzCitron** [comment]
its hidden for erekir version of that

**Comment by EclipseTheOldOne** [comment]
> its hidden for erekir version of that

1. wdym
2. it's only placable in editor

**Comment by WilloIzCitron** [comment]
1- yes erekir version of sield is different than serpulo one
2- its placeable on editor but enemy base can aplicable not ally one

**Comment by buthed010203** [comment]
Minecraft moment
