### ISSUE TITLE
Custom formations?

### ISSUE THREAD

**Issue by Mechanicalenhancement1** [Anuken/Mindustry-Suggestions#3556]
### Describe the content or mechanics you are proposing.

In v7 the unit controll feature is overhauled. What if, just like custom scematics, we could create custom formations for units?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow for better unit configuration (for example mace units at the front for tanking hits and novas at the back to provide healing). This can also improve the current rts AI and allow them to use units more effectively

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SlavicProgrammer2137** [comment]
very good idea, one question though: ghow woudl you arrange the units into a formation?
