### ISSUE TITLE
Hippity Hoppity your Meta is now my Property

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#3557]
### Describe what you would like changed, and why.

All your meta are belong to us. 

Erekir have no chance to survive make your nerf. 

Anyone who doesn't have my scheme will be chronically disadvantaged. It is the endgame power production in all of Erekir. 
![image](https://user-images.githubusercontent.com/68676339/167721280-aafb8c09-eab5-44a5-a263-4c228ba1d03f.png)

### Describe the changes you want to propose. Include possible alternatives.

no seriously though this is even worse than water extractor spam meta from v6 please don't let this kind of crap be the entire power generation meta for erekir

**Comment by EclipsePlays** [comment]
powercubes but in Erekir, huh?

**Comment by 50275** [comment]
powercubes but immune to your carpet
