### ISSUE TITLE
Ability to change multipliers

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#356]
**Describe the content or mechanics you are proposing.**
The ability to change multipliers in Custom Rules or World Editer

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will make it so map makers can make their maps feel more realistic and alive, like hot barren maps can have lower water extractor output and lushious rich maps can have more water extractor output, maybe even a mutliplier to change all or certain factory output multipliers and maybe making it so Overdrive projecters do worse.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
But servers can change them anyway.

**Comment by SupremeTurtle** [comment]
I feel like a plugin would be better suited for this

**Comment by itcannotbe** [comment]
That's not the point of this suggestions. He meant that multiplier may be included in the msav instead on setting them before play on clients and servers.

**Comment by MapleWheels** [comment]
I do agree that per-map customizations such as this _could_ be very good for creativity. Care must be taken though so that the user is fully awake that the custom map uses non-standard values. Remember, subtle changes can cause a lot of things to completely fail, including Schematics. If the user is not aware of this, it may cause them to have a poor view of the game instead and create unneeded confusion.

**Comment by itcannotbe** [comment]
This doesn't affect the vanilla campaign. That wouldn't be an issue. Since the values mostly doesn't affect blocks in  significant way except a few, namely banning blocks and solar multiplier.

**Comment by MapleWheels** [comment]
> This doesn't affect the vanilla campaign. That wouldn't be an issue.
> 
> Also since the values mostly doesn't affect blocks in a significant way except a few, namely banning blocks and solar multiplier. It really doesn't affect their use.

People don't make a large distinction between multiplayer and campaign. Sure, cost multipliers can be changed but it's a very apparent and simple to grasp change. Something on this level is not immediately apparent and the amount of changes can end up being so complex that users can't immediately, mentally absorb the changes. Something like banning blocks is also quick to grasp.

Again, you can do this change but communication and user understanding is vey important here and has to be accounted for.
