### ISSUE TITLE
Advantage improves the game

### ISSUE THREAD

**Issue by KHALILRDX** [Anuken/Mindustry-Suggestions#3562]
### Describe the content or mechanics you are proposing.

1 Add new Solar system
2 Add Satellite And it is a sector but its size is big and very hard
3 Add cold planet

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

IncreasWill increase the hours of play and the number of players

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More planets before. This is a revelation. I would never have thought of adding More planets myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More planets immediately."

**Comment by itcannotbe** [comment]
> IncreasWill increase the hours of play and the number of players

It doesn't.

**Comment by itcannotbe** [comment]
> 1 Add new Solar system

Do you really think just adding more planets without any additional content aside from the planet itself is going to be enjoyable for the player?

> 2 Add Satellite And it is a sector but its size is big and very hard

There are reasons why even servers have almost the same size of their largest maps, hardware limitations.

3 Add cold planet

That's it?

**Comment by KHALILRDX** [comment]
I mean, satellites in a campaign and it's ver difficult

في الأربعاء، ١١ أيار، ٢٠٢٢ ١٢:١٨ م itcannotbe ***@***.***>
كتب:

**Comment by EclipseTheOldOne** [comment]
you're talking like adding thing was that easy

**Comment by SMOLKEYS** [comment]
> size is big and very hard

goddamn 😳

**Comment by itcannotbe** [comment]
> > size is big and very hard
> 
> goddamn 😳

![sus](https://c.tenor.com/u4DTDP287_kAAAAM/sus-suspect.gif)
