### ISSUE TITLE
Heat Source

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry-Suggestions#3564]
### Describe the content or mechanics you are proposing.

A single 1by1 block that produces infinite heat. For sandbox use.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make it easier to use heat related factorys in sandbox.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RebornTrack970** [comment]
I pred this instead.

**Comment by luxDuck** [comment]
I was going to suggest this as well!
