### ISSUE TITLE
Erekir early game balance.

### ISSUE THREAD

**Issue by Halt-alt** [Anuken/Mindustry-Suggestions#3569]
### Describe what you would like changed, and why.

I know that everything on erekir is yet to be finally balanced, but i'd like to propose more of a specific balance change.
Right now, early pvp game on erekir almost always involves eludes (mosquitoes, as some players have learnt to call them). Not particularly suprising - the unit is swift and has homing projectiles. They are very hard to counter early game - thanks to their decent range, you'll either need to wall off the area, or use breaches (no other turret with sufficient range until disperse). This, however, is a poor solution, as breaches have a slow turning speed and aren't particularly fast firing. It's needless to say that the first player to get this t1 units gains quite an advantage as they can slow their enemy's progress down to a crawl.

### Describe the changes you want to propose. Include possible alternatives.

As already mentioned, i do realise that erekir is yet to be fully balanced. That's why I'm not writing this suggestion to ask for a direct stat nerf, as also I believe it wouldn't adress the core of the problem properly. Instead, I'd like to ask for the range of elude's projectiles to be nerf, and for the breach to have increased rotation speed.

**Comment by OnyxFinger** [comment]
Eh... I think it's possible to see it moving out actually
even in FoW, you can hear it shooting walls, so  if you were to place weak structures like nodes, you hear them get shot/ they'd disappear on the map.

**Comment by Halt-alt** [comment]
> Actually, I'm almost sure there can be workarounds ? Like starting with guns on the map (on the player's side for God's sake, antirush walls are disgusting).

I have seen map with antirush walls already (and they aren't that disgusting on erekir), but most maps use the world processor to make a shield that collapses after 5 minutes. There are ways to go around this. But yeah I'd be better if it just got rebalanced.

**Comment by THEGAMER-10n** [comment]
Oh god you forgor the template

**Comment by Halt-alt** [comment]
> Oh god you forgor the template
Balancing and feedback hasn't got three checkable boxes at the bottom. I was also suprised, and I don't know whether this was  a recent change.

**Comment by Halt-alt** [comment]
> > > Actually, I'm almost sure there can be workarounds ? Like starting with guns on the map (on the player's side for God's sake, antirush walls are disgusting).
> > 
> > 
> > I have seen map with antirush walls already (and they aren't that disgusting on erekir), but most maps use the world processor to make a shield that collapses after 5 minutes. There are ways to go around this. But yeah I'd be better if it just got rebalanced.
> 
> Nooo antirush walls bad need like 40 tier 4s to beat them.
Have you ever heard of the story of the titan cannon? I thought not. It's not a story a non-classic player would tell you...
Titan cannons have extreme range. If the antirush wall doesn't have any (which is the way it should be imo), then as soon as you get these long range artillery boys, you can crush the wall. They cost thorium though, so it's like a technological race between the two teams.

**Comment by itcannotbe** [comment]
> Oh god you forgor the template

Actually, you can't delete the template anymore.
![Screenshot_20220516_143440](https://user-images.githubusercontent.com/45280919/168533032-bc54f897-0baf-4dfe-bdef-9d0e03eb6c8e.jpg)
