### ISSUE TITLE
Exploding Permanent Terrain blocks

### ISSUE THREAD

**Issue by TheDemonKingRaz1** [Anuken/Mindustry-Suggestions#357]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by TheDemonKingRaz1** [comment]
Hello Anuke, if you see this thank for your time. 
I was thinking if permanent could be destroyed in a way by nuking it with the Thorium Reactor?

**Comment by Anuken** [comment]
Use the template. This has been suggested many times.
