### ISSUE TITLE
Rework conditional branches/jumps in mlog

### ISSUE THREAD

**Issue by Shidoengie** [Anuken/Mindustry-Suggestions#3571]
### Describe the content or mechanics you are proposing.

I'm proposing that jumps be split into ifs and loops.
And on the visual side instead of having arrows that point to the conditional code i say that we wrap it around a container of sorts and that whatever is inside the container will be the commands for the if or loop (maybe in the future functions!).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would massively help make mlog more intuitive and easier to use and turn it more away from a assembly like language into a higher level one.
It would also make it easier for newer players to understand it!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by random-guy1285** [comment]
Now what would be the point if you can already do that and more with normal jumps

**Comment by Shidoengie** [comment]
> Now what would be the point if you can already do that and more with normal jumps 

As i said it would make it massively more intuitive and easier to use and would make the instructions more readable

**Comment by itcannotbe** [comment]
> turn it more away from a assembly like language into a higher level one.

Denied.
