### ISSUE TITLE
Rename liquids to fluids in v7

### ISSUE THREAD

**Issue by Choobyshroom** [Anuken/Mindustry-Suggestions#3573]
### Describe what you would like changed, and why.

I think it would make sense if most references to liquids should say fluids instead. With the addition to gasses in v7 it would make more sense to call them fluids (a way of saying either a liquid or a gas).

### Describe the changes you want to propose. Include possible alternatives.

I don't think this needs further explanation.

**Comment by Ruichka** [comment]
https://github.com/Anuken/Mindustry/blob/07ff2de2a225b09d6e68d2f88b93ebd36bcde523/core/assets/bundles/bundle.properties#L1140

**Comment by jacklolidk** [comment]
you could just get someone to whip up a small mod like the bundles mod (but without the englih)
