### ISSUE TITLE
A large oil extractor?

### ISSUE THREAD

**Issue by TacticalAlpha** [Anuken/Mindustry-Suggestions#358]
**Describe the content or mechanics you are proposing.**
• a large oil extractor that is used on deep water.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
• a large and tall oil extractor that has massive power consumption and can drill a 60/sec oil

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
**Describe how you think this content will improve the game.**

Go on then.

**Comment by itcannotbe** [comment]
Oil extractors, as they are currently, are stupidly insanely efficient blocks. They don't need a buff or a better block.

What of block requires 180 power, needs 9 liquid inputs per second to make 15 liquid outputs per second that consumes 0.6 of an item per second that can be boosted by 15% more when placed on a specific tile up an additional 135% with out the need for more inputs.

**Comment by Anuken** [comment]
I agree with the comments above.
