### ISSUE TITLE
Uranium

### ISSUE THREAD

**Issue by Cbao04** [Anuken/Mindustry-Suggestions#3581]
### Describe the content or mechanics you are proposing.

Since there is thorium, why not also add uranium as a higher tier radioactive material, it can be a material to the planned feature, nuclear tech.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can be used as fuel for reactors, a ammunition for turrets, a new status effect called "radiated" and finally, nukes which I think is already planned. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Thorium is actually the replacement for Uranium.

**Comment by end-me-please** [comment]
> why not also add uranium

Uranium was removed a while ago.

**Comment by Ruyeex** [comment]
There's already something called fissile matter which could be used in nukes. (Yes uranium is a fissile matter)

**Comment by MEEPofFaith** [comment]
[thorium is objectively better than uranium](https://youtu.be/jjM9E6d42-M)
