### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ykzdyh** [Anuken/Mindustry-Suggestions#3583]
### Describe the content or mechanics you are proposing.

建议增加战斗回放功能，pvp玩家学习起来会更加容易些，回放功能建议是实时演算的且不要消耗太多性能

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

建议增加战斗回放功能，pvp玩家学习起来会更加容易些，回放功能建议是实时演算的且不要消耗太多性能

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Translated through Google Translate:

> Describe the content or mechanics you are proposing.
> It is recommended to add the battle playback function, it will be easier for pvp players to learn, the playback function is recommended to be calculated in real time and not consume too much performance

> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> It is recommended to add the battle playback function, it will be easier for pvp players to learn, the playback function is recommended to be calculated in real time and not consume too much performance


What do you mean about playback function?
