### ISSUE TITLE
Multiplayer Update

### ISSUE THREAD

**Issue by 101BlackWidow** [Anuken/Mindustry-Suggestions#3585]
### Describe the content or mechanics you are proposing.

Say I want to make a private server with a campaign level for my friends to join. And say they don't live in my area. I say the multiplayer system is updated so when starting a game, hosting gives just two options; public or private, and I can tell my friends a randomly provided code that they can input in the "join" menu to join me.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This method for multiplayer is easier and more simple than the current methods, which have like "address" and "port forwarding" or whatever.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
If it was that easy, it would’ve been done like that. It’s just how the internet works; connecting to another computer *without* port forwarding or a third-party server is really difficult.


if you want these features, use the steam version. The steam version costs money because steam provides a hand full of services, including less complicated multiplayer.

**Comment by THEGAMER-10n** [comment]
Steam does that. It is meant to be paid to do that.

Servers **ARE NOT** free, they require power, resources and maintenance.
