### ISSUE TITLE
Buff ALL silicon homing projectiles

### ISSUE THREAD

**Issue by THEGAMER-10n** [Anuken/Mindustry-Suggestions#3587]
### Describe what you would like changed, and why.

1. Buff the turn speed, the detection range, and bullet speed (Except for artillery).
2. Either increase damage (doesn’t have to be much) or decrease bullet usage.

### Describe the changes you want to propose. Include possible alternatives.

Currently, silicon ammo is just useless because it is often used for unit production. So, in order to actually give it use for ammunition (silicon ammo for salvos, duos, and hails are just glorified graphite ammunition) it’s homing and damage needs to be buffed

**Comment by itcannotbe** [comment]
> decrease bullet usage.

Increase item multiplier.

**Comment by OnyxFinger** [comment]
I'd appreciate some more damage. Same goes for graphite, it barely has more dps than copper but is much pricier

**Comment by THEGAMER-10n** [comment]
It’s been four days without activity…

**Comment by end-me-please** [comment]
Maybe PR it, balancing changes don’t require much programming knowledge

**Comment by Somka000** [comment]
real
