### ISSUE TITLE
Defensa del núcleo 

### ISSUE THREAD

**Issue by XxSnootychairxX** [Anuken/Mindustry-Suggestions#3588]
### Describe the content or mechanics you are proposing.

Que el núcleo cuando este bajo ataque se puede defender con un láser o con torretas,pero que esas defensas este alimentados por los recursos almacenados del mismo núcleo,también que esas mejoras que puedan investigar en el árbol tecnológico 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Facilitaría la dificultad para jugadores que apenas empiezan y también cuando el enemigo haya destruido o pasado tus defensas el mismo núcleo se pueda defender 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Translated by Google:

> ### Describe the content or mechanics you are proposing.
> That the core when it is under attack can be defended with a laser or with turrets, but that those defenses are fed by the resources stored in the core itself, also that those improvements that can be researched in the technology tree

> ### Describe how you think this content will improve the game.  If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> It would ease the difficulty for players who are just starting out and also when the enemy has destroyed or passed your defenses, the same core can defend itself

You didn't even bother reading the readme.

**Comment by itcannotbe** [comment]
### These have been proposed many times already, and I won't be adding them.
###### These have been proposed many times already, and I won't be adding them.
- Turrets on top of cores

**Comment by itcannotbe** [comment]
How could you even miss that?

**Comment by XxSnootychairxX** [comment]
> convertido por Google:
> 
> > ### Describe el contenido o la mecánica que propone.
> > Que el núcleo cuando está bajo ataque se puede defender con un láser o con torretas, pero que esas defensas se alimentan de los recursos almacenados en el propio núcleo, también que aquellas mejoras que se pueden investigar en el árbol tecnológico
> 
> > ### Describe cómo crees que este contenido mejorará el juego. Si está proponiendo contenido nuevo, mencione cómo puede agregar más opciones de juego o cómo llenará un nuevo nicho.
> > Facilitaría la dificultad para los jugadores que recién comienzan y también cuando el enemigo ha destruido o superado tus defensas, el mismo núcleo puede defenderse.
> 
> Ni siquiera te molestaste en leer el archivo Léame.

Sorry :(
