### ISSUE TITLE
REPAIR PAYLOAD CONVEYORS

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#3589]
### Describe what you would like changed, and why.

clearly shown in the attached screenshot.
the factory can lay out on the conveyor standing exactly in front of it
can also lay out on the conveyor stands unevenly in front of it
the conveyor can lay out on the conveyor standing exactly in front of it
WHY can a conveyor lay out on a conveyor that is not level in front of it REPAIR THIS, I CAN'T BUILD THE WAY FROM POINT A TO POINT B WITH THE SMALLEST MIXING FOR WHICH I HAVE TO BUILD A CARGO CATAPLATE TO SIMPLY TRANSFER THE OBJECT FROM ONE CONVEYOR TO A LITTLE OFFSET RELATIVELY TO IT

ПОЧИНИТЕ PAYLOAD КОНВЕЙЕРЫ
фабрика может выкладывать на конвейер стоящий ровно перед ним
также может выкладывать на конвейер стоит неровно перед ним
конвейер может выкладывать на  конвейер стоящий ровно перед ним
ПОЧЕМУ конвейер может выкладывать на конвейер стоящий неровно перед ним ПОЧИНИТЕ ЭТО , Я НЕ МОГУ ПОСТРОИТЬ ПУТЬ ИЗ ПУНКТА А В ПУНКТ Б С МАЛЕЙШИМ СМЕШЕНИЕМ ИЗ ЗА ЧЕГО Я ВЫНУЖДЕН СТРОИТЬ ГРУЗОВУЮ КАТАПУЛЬТУ ЧТОБЫ ПРОСТО ПЕРЕЛОЖИТЬ ПРЕДМЕТ С ОДНОГО КОНВЕЙЕРА НА НЕМНОГО СМЕЩЕН ОТНОСИТЕЛЬНО ЕГО
### Describe the changes you want to propose. Include possible alternatives.

![2022-05-23_11-57-12](https://user-images.githubusercontent.com/71027210/169746840-e53663d1-949c-4619-a659-960f5ec21ae9.png)

**Comment by ziszlo** [comment]
почему оно работает так как работает

**Comment by SMOLKEYS** [comment]
skill issue

**Comment by itcannotbe** [comment]
skill issue (2)

**Comment by ziszlo** [comment]
> skill issue (2)
> 
> Because you're dealing with blocks that are 3x3 not 1x1 you should have known better.

I want items to be able to be transferred from a conveyor to a mixed conveyor, this is not a matter of skill, but the problem of inconsistencies between these conveyors

**Comment by buthed010203** [comment]
In theory this should be a trivial fix, all that needs to be done is checking whether the two tiles adjacent to the output are payload conveyors or not
