### ISSUE TITLE
better prediction

### ISSUE THREAD

**Issue by jakubDoka** [Anuken/Mindustry-Suggestions#359]
If you are adding players velocity to his bullets why not subtract it from targets velocity when calculating where to shoot, on mobile? it would improve accuracy while moving.

**Comment by itcannotbe** [comment]
Template: I wasn't use again.

**Comment by PhilipPurwoko** [comment]
I don't think so. The player may be more overpowered. Except if you create a mech upgrade that have that accuracy, this would be fair
