### ISSUE TITLE
Upgraded Factory

### ISSUE THREAD

**Issue by Cbao04** [Anuken/Mindustry-Suggestions#3590]
### Describe the content or mechanics you are proposing.

Factories like Plastanium Compressor, Phase Weaver and Kiln should have upgraded factories like the multi press and silicon crucible.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Late game players can create plastanium, phase fabric and metaglass can be created faster.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by laok233** [comment]
for tier-2 factories, additional material is required, silicon crucible requires pyrite, multi press requires water.
also i don't think tier-2 for plastanium, phase or glass is needed.

**Comment by rylid-umil** [comment]
plastanium's extra item would be coal, phase's extra item would be pyratite and glass's extra item would be titanium.
