### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by rylid-umil** [Anuken/Mindustry-Suggestions#3591]
### Describe the content or mechanics you are proposing.

https://github.com/rylid-umil/New-Units add it to modlist

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

adding another mod to mod browser

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
1. mods are automatically added to the list of mods
2. nice stolen assets, nobody would add this if it was a choice anyways

**Comment by AureusStratus** [comment]
Ayo nice sprites of mine you got there
