### ISSUE TITLE
Unit Opacity

### ISSUE THREAD

**Issue by ara1106** [Anuken/Mindustry-Suggestions#3592]
### Describe the content or mechanics you are proposing.

Add an option that lets you toggle see through units in a radius around the player.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Case 1: Command centers are hard to use as is, when units are all clumped up around it, it can be near impossible to select it or destroy it. 

Case 2: When commanding a bunch of build-capable units, they can make it hard to see and click where you want to build. 

Allowing units near you to become a tad see-through should help with both of these cases.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SMOLKEYS** [comment]
> Case 1: Command centers are hard to use as is, when units are all clumped up around it, it can be near impossible to select it or destroy it.

> Case 2: When commanding a bunch of build-capable units, they can make it hard to see and click where you want to build.


So uh, unit commanding and command centers were removed.

**Comment by AMindustryPlayer** [comment]
This feature is already implemented on foo's client

**Comment by ara1106** [comment]
Oh man, guess I should have tried the BE builds before suggesting this. My bad!

I had a look at the Trello and swear I couldn't find it but I must have missed it.
