### ISSUE TITLE
Fusion Reactor

### ISSUE THREAD

**Issue by SlavicProgrammer2137** [Anuken/Mindustry-Suggestions#3593]
### Describe the content or mechanics you are proposing.

Since v7 introduces an electrolyzer and hydrogen, there could maybe be a fusion reactor that uses hydrogen to produce vast amounts of power. the cons would be that it is big, it requires a lot of hydrogen and needs some sort of cooling or it explodes (maybe the new heat system)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently Erekir has only 2 ways of making power: thermal vents and chemical burners. none EXPLODE so far, but Serpuleo has 2 exploding reactors. I also think the concept of fusion fits very well with hydrogen

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
There's probably a very good reason why Erekir power is so scarce.
