### ISSUE TITLE
Follow Command

### ISSUE THREAD

**Issue by HappyWolfy10** [Anuken/Mindustry-Suggestions#3595]
### Describe the content or mechanics you are proposing.

Basically: Somehow you can command units (using command mode) to follow a selected unit. How this works is up to devs (it should be a different command than selecting units). While the units are following, they will attack enemies within their range.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Uses
1. Have support units follow attack units so they can heal/buff them
2. Formations around a player (that work better than the original formations)
3. Make it easier to command units
4. etc

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by buthed010203** [comment]
> that work better than the original formations

Good luck with that one

**Comment by RealYeet** [comment]
Maybe formations for polys and Megan’s would be nice, but besides that they are not needed.
