### ISSUE TITLE
(More) Utilitiesed Mass Driver and conveyor/pipe floating version ideas.

### ISSUE THREAD

**Issue by Bludstonian** [Anuken/Mindustry-Suggestions#3596]
### Describe the content or mechanics you are proposing.

Dear anuke,                                                     4:45 thur,may 26

     Mass drivers great for broken up Maps and long distances, but do they have more potential 🤔 ? Yes they have a lot of potential. Imagine if they could be offensive aswell persay, that could be told to aim by using 1 of the processors and/or needing fluid to fire to cool it down. Another idea would be that it cause different damage with different amounts of different materials, just like a utility railgun.This concept should be looked into and at least tested and balanced before naysaying.

        What if we could build certain conveyors and pipes on water, slag, and oil it would revolutionize factory building on multiple maps aswell as custom maps. The floating conveyors and pipes could use a new material like rubber or plastic(probably just plastinium instead) so that they would be harder to get [end game].

        I sincerely hope you look this over anuke and not just turn it down but test the concepts out.
                                                                     
                                                                    Sincerely,Bludstone

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would put more mechanics and base building possibilities into the game aswell as being able to keep mass drivers more safe.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by THEGAMER-10n** [comment]
Why tho?

Cons:
1. The mass drivers are balanced enough.
2. Mass drivers don’t even exist in Erekir.
3. Floating conveyors. They pose some balancing issues. Either way, the main purpose of mass drivers are sending resources over vast areas or over unbuildable places. Mass drivers are cheap enough, why bother making a slower form of item transportation when their mechanics exist.
4. Logic exists. (In the case of Erekir, loading pads and unloading pads.)

Pros:
1. New (albeit sketchy) game mechanics.
2. Weaponized mass drivers sounds cool.

**Comment by itcannotbe** [comment]
###### ~but mass driver "bullets" already deal damage~

**Comment by itcannotbe** [comment]
Do you think the dev basically made it harder for himself to prevent things being built on top of liquids?

**Comment by OnyxFinger** [comment]
Why did you write it this way it's a pain to read..

Mass drivers have no reason to be an offensive weapon though

**Comment by Bludstonian** [comment]
Sorry I tend to type or word stuff wrong.
