### ISSUE TITLE
Better understanding of transport blocks

### ISSUE THREAD

**Issue by AxrzZ** [Anuken/Mindustry-Suggestions#3598]
### Describe the content or mechanics you are proposing.

An option in the settings that adds an arrow etc. on certain transport blocks such as routers, junctions, bridges, sorters and overflow barriers.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Better understanding of transport blocks which will help beginners

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
That won't help.

Routers, junctions, sorters, underflow, and overflow have outputs dependent on their inputs and available outputs.
