### ISSUE TITLE
Change Android Icon

### ISSUE THREAD

**Issue by PriyanthaFer** [Anuken/Mindustry-Suggestions#3599]
### Describe what you would like changed, and why.

Honestly I've had this game suggested to me on playstore for Aeons, but when looking the icon I thought that it was a boring idle tycoon game. I only tried this game after a friend described and suggested the game. And I absolutely love it. Brings old State-Of-War memories. 

### Describe the changes you want to propose. Include possible alternatives.

I suggest that the icon to be changed... into a unit? Or a high tier fancy turret. Any thing that obviously shows the game.

**Comment by itcannotbe** [comment]
It's literally the core with a duo on top.
