### ISSUE TITLE
Conveyor placement

### ISSUE THREAD

**Issue by mindustrialist** [Anuken/Mindustry-Suggestions#36]
A way to lay conveyer easily like tap two point in a line and it would be built useful  when you have to transfer item from long distance in map early on.

**Comment by Katsute** [comment]
Just drag and hold Ctrl when building a conveyors and it does this

**Comment by mindustrialist** [comment]
I play on mobile

**Comment by KK6DOC** [comment]
It is still enabled on mobile 
Hold a point then drag @mindustrialist

**Comment by Katsute** [comment]
I don't think it works for diagonal on mobile dragging, just linear.

**Comment by TNT331** [comment]
yep...

**Comment by ZkyLB** [comment]
i remember doing diagonal conveyors on mobile, but i forgot how to do it since i really don't use mobile for gaming.
it may be on settings.

**Comment by ifritdiezel** [comment]
There's that diagonal arrow button near to deconstruct button
It allows diagonal placement just like in PC.

**Comment by Anuken** [comment]
Follow the issue template. This already exists.
