### ISSUE TITLE
2x2 Liquid Tank, Category Changes and UI Improvements

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#360]
1 - A 2x2 Liquid Tank, everything same except size and capacity
2 - Moving some items to different categories
3 - UI can be improved by implementing the 2nd suggestion

2x2 Liquid Tank: Items and liquids are different things and items have 2 types of containers (2x2 and 3x3) and liquids only has one (3x3 liquid tank) so I think adding one more liquid tank would be the counterpart of the 2x2 container whilst the 3x3 liquid tank is already the counterpart of item vault (3x3).

Category Changes: I think all liquid transportation things should be moved to transportarion category (Also change the icon of them from conveyor to something that would represent both items and liquids, my idea is adding a conduit icon behind the conveyor icon so it does represent both items (conveyor icon) and liquids (conduit icon)). Also all liquid pumps should be moved to drills category (Also change the icon of drills category too to something that would represent both items and liquids, my idea is adding a pump icon behind the drill icon so it does represent both items (drill icon) and liquids (pump icon)). About liquid Tank (and the 2x2 one if you add it), they should be moved to the "misc" category (that one with shock mines, vaults, menders, etc.) (A suggestion by me is to change the icon of misc category to something like 3 dots or 9 (3x3) or just something else because it seems like a big dot inside a square which is weird.) By doing this the liquid category would be empty and probably would be removed.

UI Improvements: Currently in the 6.0 there seems to be only 7 categories and it doesnt look good since out of 8 one category seems to be missing (That will be a huge peoblem for those with OCD because it looks disturbing and annoying). And by implementing the 2nd suggestion there will be 6 categories left (by the removal of the liquid category) and if we make the category buttons a bit bigger (increase their height and maybe width too to keep them a square) they will fit perfectly and the problem would be solved. If you plan or planned an 8th category for 6.0 (I hope you didn't or don't) already then it would be 7 categories again which will be a problem as told but if you dont this is the solution.

If in some way we end up with only 7 categories then the 2 (Width) x 4 (Height) menu needs to be changed into something else, like a 7x1 menu (which would be in the middle) , a circular menu or a 1x7 menu with smaller buttons keeping the same height or a bit higher but not so high but i guess the buttons would be too small so I suggest the 7x1 one. Same things should/would apply if the amount of categories would be an odd number.

I now realized that the transportation category would be long (not too much) and this is why there has to be an UI improvement again. Maybe add a search bar, or a filter?

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
> Moving some items to different categories

I am against this as pumps draw out liquids while water/oil extractors drill out liquids in some way.

**Comment by Zenith-LY** [comment]
> > Moving some items to different categories
> 
> I am against this as pumps draw out liquids while water/oil extractors drill out liquids in some way.

Well they are a kindd of production blocks, you place them somewhere else and they start producing materials. Like for example a drills produces items while a pump produces liquid, water extractor also does the same as liquid and putting all those to a category would be better since their mechanics are similar to each other

**Comment by Anuken** [comment]
> A 2x2 Liquid Tank

Use 2x2 liquid routers instead.

> Currently in the 6.0 there seems to be only 7 categories

It won't stay that way, and I don't think moving all the liquid distribution blocks to other categories is the best way to clean it up.

**Comment by Zenith-LY** [comment]
>  Use 2x2 liquid routers instead.

This is how much a 2x2 router fills a liquid tank (1500 capacity) :
![Screenshot_20200801-033647](https://user-images.githubusercontent.com/68538765/89089963-a2f2a980-d3a8-11ea-9340-dadd3a4acc32.jpg)
We need a normal 2x2 tank with stable capacity not a rip off from transportation blocks.

**Comment by Anuken** [comment]
> We need a normal 2x2 tank

No, we don't. In what scenario would you need *exactly* a 2x2 block that can store large amounts of liquid, with no room for compromise?

**Comment by Zenith-LY** [comment]
>  In what scenario would you need _exactly_ a 2x2 block that can store large amounts of liquid?

1 - When making compact schematics
2 - When there is no room for 3x3 one
3 - When you need a tank with lower storage because when you connect a conduit to a tank it literally absorbs it until its full and 3x3 tank takes a lot of time though if the conduit was also connected to impact/thorium reactor they will stop/explode since they lack cryofluid because the tank absorbs it for a long time. A smaller storage wouldn't be a problem since it wouldn't take a lot of time to fill and until its filled nowhere would probably lack and liquids.
4 - Increasing liquid router's capacity would fix but it would be weird since it would work like a tank but its a transportation block and it shouldn't have storage capacity so I don't thnk increasing the capacity of liquid routers would be good.
5 - If we have 2x2 item container for a reason there also should be 2x2 liquid tank like how there is both 3x3 containers/tanks for items and liquids. This way both types would have 2x2 and 3x3 containers/tanks and it would be like, balanced for both types.

**Comment by itcannotbe** [comment]
All your points are actually just 1 point.

For making things compact.

You can actually make compromises. You just don't want to.

Conduits are directional and tanks/routers round robin all possible outputs.
