### ISSUE TITLE
Java Mods should be "directly" playable!

### ISSUE THREAD

**Issue by Evo04Taser** [Anuken/Mindustry-Suggestions#3600]
### Describe what you would like changed, and why.

I would like to change how moding the game works.

### Describe the changes you want to propose. Include possible alternatives.

Pls allow the game to "directly" use java Mods instead of having to convert them into jar files before playing/importing. It will intensely help me and others because I struggle converting it to jar files, especially if you update the mod often. But allow jar files to be still used for balance.
 
### How this works.

(I'm bad at English)

If the system detects a "src", "assets", and/or "assets-raw", they'll look what's inside that file, anything, except for invalid files/file type, example: "content.html"

**Comment by end-me-please** [comment]
...This is just not possible

also, most Java mods offer pre-built jar files, you almost never have to build from source yourself

**Comment by Evo04Taser** [comment]
> most Java mods

How then? My java mod doesn't even have a JAR file.

**Comment by end-me-please** [comment]
not sure if I understand you correctly, you made a Java mod without knowing how to build a Java project?
If you need help with that, ask in #modding-general

**Comment by Evo04Taser** [comment]
> you made a Java mod without knowing how to build a Java project?

Yeah ITS my first java mod, no hate.

**Comment by Mnemotechnician** [comment]
so, basically, you are suggesting anuke to ***embed the whole jdk 8, which is 80 mb in size, into mindustry***? and considering that almost all mods use gradle (7.3), he will also have to embed it as well, so another 120 mb (iirc). 

Gradle takes 40 seconds to start up from the fresh state on an average mobile device, and an average java mod (not even talking about kotlin, groovy and other languages, since they require their own compilers) takes from 10 to 40 seconds to compile.

So, what do we get in the end:
- The size of mindustry executable rises from 58 mb to 220 mb
- The average loading time with some java mods installed rises from 5-15 seconds to 1 / 2 / 3 / 10 / infinity minutes
- The average network load during the loading of mindustry rises from 0 to some undefined number, since gradle will have to fetch dependencies before compiling

What are the benefits of these sacrifices:
- Your lazy self will not have to run `gradle deploy` to compile your mod

**Comment by Mnemotechnician** [comment]
- Is it possible? Yes.
- Does it worth it? No, no and no.

**Comment by Evo04Taser** [comment]
>  Your lazy self 

Look, I don't wanna start a chaos here, BUT DONT BLAME ME JUST FOR THAT, it's my first time creating a Java mod, and it will take me a lot of time just to understand jdk, and Gradle deploy.

**Comment by Mnemotechnician** [comment]
Ok? Everything above still applies. If you don't know how to do something, either read the README.md files or google it.

**Comment by Evo04Taser** [comment]
> README.md files attached to most "sane" things

What do you mean with "sane"?

**Comment by Mnemotechnician** [comment]
mods templates, for example. almost all mindustry mod templates (of which there's not many) have instructions on how to compile them.

btw, #modding-general is a channel on the official mindustry discord sevrer.

**Comment by Evo04Taser** [comment]
>  have instructions on how to compile them.

Yes it's true, I've seen a few of them, but as I said, I don't understand it.

> btw, #modding-general is a channel on the official mindustry discord sevrer.

I can't join the Mindustry discord, and the community just calls it "you're banned", "you're IP banned" when the screenshot clearly shows that it's invalid or expired.

**Comment by BasedUser** [comment]
> > btw, #modding-general is a channel on the official mindustry discord sevrer.
> 
> I can't join the Mindustry discord, and the community just calls it "you're banned", "you're IP banned" when the screenshot clearly shows that it's invalid or expired.

I'll look into this. Expect an email shortly.

**Comment by Bottinator22** [comment]
> > have instructions on how to compile them.
> 
> Yes it's true, I've seen a few of them, but as I said, I don't understand it.
> 
> > btw, #modding-general is a channel on the official mindustry discord sevrer.
> 
> I can't join the Mindustry discord, and the community just calls it "you're banned", "you're IP banned" when the screenshot clearly shows that it's invalid or expired.

Discord says that when you're banned. It's odd, but that is what it says when you are banned from a server and you have an invite.

**Comment by BlueWolf3682** [comment]
> I can't join the Mindustry discord, and the community just calls it "you're banned", "you're IP banned" when the screenshot clearly shows that it's invalid or expired.

The main invite (https://discord.gg/mindustry) CANNOT expire pr become invalid. Mindustry is a partnered discord server, and this is a permanent link.

If you want faster editing of simple stuff in a Java mod, make the basic content in a JSON mod first. ~~considering you are likely doing stuff more or less in the realm of JSON, this shouldn't be hard.~~

**Comment by SMOLKEYS** [comment]
Honestly, don't even fucking try to make java mods if you don't even know how to compile them.

**Comment by SMOLKEYS** [comment]
If you want java mods, learn how to compile them, not ask for a built-in compiler.

**Comment by Bottinator22** [comment]
~~they DID say they're just grade 5, maybe tone down the rudeness a bit~~

Probably shouldn't start with Mindustry mods if you're starting with Java. If you want to make mods, try a JSON/JS mod first, assuming you haven't already made one.

(assuming you know nothing about Java here)
Personally I learned Java from something called Robocode, although something else may or may not teach you better.
Javascript is interpreted, so it needs no compilation to run code. (as compiling happens on run)
Java, however, is not, so you must compile your code first before you can run it.

**Comment by MEEPofFaith** [comment]
~~do not the js, it's a mess~~

**Comment by code-explorer786** [comment]
# for real
I have **never** expected this issue.

## why java mods should be compiled

As you can see, Java is a compiled programming language, which means you should actually compile it.
And yes, you can do `java a.java`, but I have never seen that in the source code, or anything similar If Mindustry does that, it'll be very slow at loading the mods.

### how to easily make a java mod

First off, you should generate a repository from [this template](https://github.com/Anuken/MindustryJavaModTemplate)

Second, you have to modify some values on `build.gradle` according to the comments.

And then, make your content.

You can see the wiki about JVM and Plugin mods on https://mindustrygame.github.io/wiki/modding/2-plugins/

**Comment by Evo04Taser** [comment]
Pls Read the **How this works**

**Comment by Bottinator22** [comment]
No

**Comment by Bottinator22** [comment]
We have told you enough, Java doesn't work like this

**Comment by itcannotbe** [comment]
> Pls Read the **How this works**

It doesn't work that way.

**Comment by itcannotbe** [comment]
> so, basically, you are suggesting anuke to _**embed the whole jdk 8, which is 80 mb in size, into mindustry**_? and considering that almost all mods use gradle (7.3), he will also have to embed it as well, so another 120 mb (iirc).
> 
> Gradle takes 40 seconds to start up from the fresh state on an average mobile device, and an average java mod (not even talking about kotlin, groovy and other languages, since they require their own compilers) takes from 10 to 40 seconds to compile.
> 
> So, what do we get in the end:
> 
>     * The size of mindustry executable rises from 58 mb to 250 mb
> 
>     * The average loading time with some java mods installed rises from 5-15 seconds to 1 / 2 / 3 / 10 / infinity minutes
> 
>     * The average network load during the loading of mindustry rises from 0 to some undefined number, since gradle will have to fetch dependencies before compiling.
> 
> 
> What are the benefits of these sacrifices:
> 
>     * Your lazy self will not have to run `gradle deploy` to compile your mod

This is how it would work it this would be a thing.

**Comment by Evo04Taser** [comment]
> > so, basically, you are suggesting anuke to _**embed the whole jdk 8, which is 80 mb in size, into mindustry**_? and considering that almost all mods use gradle (7.3), he will also have to embed it as well, so another 120 mb (iirc).
> > Gradle takes 40 seconds to start up from the fresh state on an average mobile device, and an average java mod (not even talking about kotlin, groovy and other languages, since they require their own compilers) takes from 10 to 40 seconds to compile.
> > So, what do we get in the end:
> > ```
> > * The size of mindustry executable rises from 58 mb to 250 mb
> > 
> > * The average loading time with some java mods installed rises from 5-15 seconds to 1 / 2 / 3 / 10 / infinity minutes
> > 
> > * The average network load during the loading of mindustry rises from 0 to some undefined number, since gradle will have to fetch dependencies before compiling.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What are the benefits of these sacrifices:
> > ```
> > * Your lazy self will not have to run `gradle deploy` to compile your mod
> > ```
> 
> This is how it would work it this would be a thing.

Everyone is rude 🙃🙃

**Comment by itcannotbe** [comment]
More like

"EvErY oNe Is RuDe."

Since this suggestion is technical in nature we already explain how would this impact the game and the user experiece quite concisely already.

**Comment by Evo04Taser** [comment]
> > Pls Read the **How this works**
> 
> It doesn't work that way.

This is hard then?!

**Comment by itcannotbe** [comment]
It doable, **BUT IT'S IMPRACTICAL.""

**Comment by Evo04Taser** [comment]
> It's doable,
> 
> ### **BUT IT'S IMPRACTICAL.**
> There cons severely outweighs the pros of this suggestions for mostly everyone. Except an extremely niche group of people.

I OPENED THIS BCUZ ITS HARD AND GRADLE THINKS THIS "}" IS AN ILLEGAL START OF EXPRESSION WHEN IT'S THE CLOSING BRACKET OF MY CODE

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by SMOLKEYS** [comment]
> > It's doable,
> > 
> > ### **BUT IT'S IMPRACTICAL.**
> > There cons severely outweighs the pros of this suggestions for mostly everyone. Except an extremely niche group of people.
> 
> I OPENED THIS BCUZ ITS HARD AND GRADLE THINKS THIS "}" IS AN ILLEGAL START OF EXPRESSION WHEN IT'S THE CLOSING BRACKET OF MY CODE
> 

thats a problem with your own fucking code stop bringing shit here

**Comment by SMOLKEYS** [comment]
close this fucking issue and cope

**Comment by Evo04Taser** [comment]
> > > It's doable,
> > > ### **BUT IT'S IMPRACTICAL.**
> > > There cons severely outweighs the pros of this suggestions for mostly everyone. Except an extremely niche group of people.
> > 
> > 
> > I OPENED THIS BCUZ ITS HARD AND GRADLE THINKS THIS "}" IS AN ILLEGAL START OF EXPRESSION WHEN IT'S THE CLOSING BRACKET OF MY CODE
> 
> thats a problem with your own fucking code stop bringing shit here

If I can send a picture THEN YOU CAN UNDERSTAND

**Comment by SMOLKEYS** [comment]
i do not fucking care anymore


close this issue, leave this fucking repo, learn to code and cope, and fucking LEARN TO USE THE TERMINAL

**Comment by SMOLKEYS** [comment]
god

**Comment by Phinner** [comment]
Smolkeys, stay kalm

**Comment by Evo04Taser** [comment]
> i do not fucking care anymore
> 
> close this issue, leave this fucking repo, learn to code and cope, and fucking LEARN TO USE THE TERMINAL

SHUT UP BTCH

**Comment by SMOLKEYS** [comment]
gradle and java are already enough of a storagefuck

**Comment by SMOLKEYS** [comment]
> Smolkeys, stay kalm
> 

i tried

not anymore

**Comment by Phinner** [comment]
> > It's doable,
> > ### **BUT IT'S IMPRACTICAL.**
> > There cons severely outweighs the pros of this suggestions for mostly everyone. Except an extremely niche group of people.
> 
> I OPENED THIS BCUZ ITS HARD AND GRADLE THINKS THIS "}" IS AN ILLEGAL START OF EXPRESSION WHEN IT'S THE CLOSING BRACKET OF MY CODE

Maybe because you have a missing parenthesis like there ->
https://github.com/Evo04Taser/Frozen-Wasteland/blob/6701733836a68586df2f8a33526a09d1fda78c10/src/frozen/world/blocks/power/DoubleCoolantReactor.java#L94

Complaining about the difficulty is not the way to go my friend, everything is not easy in the first try. Like others said, you can ask help in the discord server or if you still can't join the mindustry discord, join a mindustry community discord. If you want modding, I recommend :

- Modding central: https://discord.gg/246pKUgt
- de_server: https://discord.gg/xturWcaz

**Comment by SMOLKEYS** [comment]
man

once in a while i lose my fucking temper

**Comment by Phinner** [comment]
> man
> 
> once in a while i lose my fucking temper

You just look cringe right now...

**Comment by SMOLKEYS** [comment]
![hell](https://cdn.discordapp.com/emojis/740836045192560680.png?size=64)

**Comment by Phinner** [comment]
@Evo04Taser The invitations I sent will only last for 7 days so...

**Comment by Evo04Taser** [comment]
> @Evo04Taser The invitations I sent will only last for 7 days so...

Yes I did it

**Comment by SMOLKEYS** [comment]
> > man
> > 
> > once in a while i lose my fucking temper
> 
> You just look cringe right now...

could no longer care any less about that

**Comment by Phinner** [comment]
> > @Evo04Taser The invitations I sent will only last for 7 days so...
> 
> Yes I did it

Very nice, See you there...

**Comment by TheEt1234** [comment]
What kind of shitfuckery happened here

**Comment by RFAC-Productions** [comment]
Jesus what did I just read?

**Comment by code-explorer786** [comment]
> I OPENED THIS BCUZ ITS HARD AND GRADLE THINKS THIS "}" IS AN ILLEGAL START OF EXPRESSION WHEN IT'S THE CLOSING BRACKET OF MY CODE
> 

It's a syntax error. You might need to fix your code a bit.
This also happens with almost all languages.

**Comment by code-explorer786** [comment]
> What kind of shitfuckery happened here

Chaos.

**Comment by code-explorer786** [comment]
@Evo04Taser 
Please close this issue, since your problem has been resolved.

**Comment by uujuju1** [comment]
havent seen this kind of chaos in a while

**Comment by EclipseTheOldOne** [comment]
amogus

**Comment by Mnemotechnician** [comment]
every time y'all comment on this issue, it's funeral gets postponed by 20 days.

let it die already

**Comment by Evanevoyo** [comment]
@Evo04Taser I know I'm reading this 4 years late but what if you just searched everywhere you could for an automatic fast compiler
