### ISSUE TITLE
Title?

### ISSUE THREAD

**Issue by fghjk455rg** [Anuken/Mindustry-Suggestions#3601]
### Describe the content or mechanics you are proposing.

Oil engines.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New application of oil.
Oil is poorly developed.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Falling10fruit** [comment]
What does it do? Produce power?

**Comment by itcannotbe** [comment]
Meanwhile...

Oil  - > Coal Centrifuge + Power = Coal

and you figure out the rest.

**Comment by Falling10fruit** [comment]
Maybe he meant a more direct way of producing power. Also, does that end up in the differetional generator?

**Comment by itcannotbe** [comment]
Using oil to produce power directly is a has a very small niche, because apart from using oil from tar pools directly, it's alternatives yields oil way less.

This would also make balancing it extremely hard to do.
