### ISSUE TITLE
SERVIDORES Y MODS DE MINDUSTRY

### ISSUE THREAD

**Issue by IKALPRODOyt** [Anuken/Mindustry-Suggestions#3602]
### Describe the content or mechanics you are proposing.

Me gustaria que añadieran para android o celulares:

Para que la comunidad de telefonos tambien pueda crear sus servers o sus propios mods para el juego por que no todos tienen pc para lograrlo.

una funcion de apartado para crear el mod donde nosotros configuremos, analizemos pruebas, escribamos codigo y hasta poder publicarlos y que la gente pueda utilizarlos.

Para los servers lo mismo un apartado para que nosotros coloquemos nuestro server, podamos jugarlo, personalizarlo y publicarlo.

Todo esto, es por mi experiencia de casi 1 año jugando este genial juego y viendo como podria ser mejorado.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Siento que esto de creador de server y creador de mods ayudara a que mas gente pueda ver lo genial que es la creatividad y para que los de telefono no se sientan tan excluidos por que literal no podemos crear mods y tampoco un servidor para jugar con mas gente de los amigos o los solos que estamos.

Espero vean este contenido que podrian colocar al juego y que se que les encantara a todas las personas que juegen minedustry.  😁

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
..if you want people to understand your suggestion, you should probably write it in English

**Comment by IKALPRODOyt** [comment]
Thank you @end-me-please
