### ISSUE TITLE
SERVERS AND MODS OF THE MINDUSTRY

### ISSUE THREAD

**Issue by IKALPRODOyt** [Anuken/Mindustry-Suggestions#3603]
### Describe the content or mechanics you are proposing.

I would like them to add for android or cell phones: So that the phone community can also create their servers or their own mods for the game because not everyone has a pc to achieve it. a section function to create the mod where we configure, analyze tests, write code and even be able to publish them and that people can use them. For servers, the same is a section for us to place our server, we can play it, customize it and publish it. All this is from my experience of almost 1 year playing this great game and seeing how it could be improved.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I feel that this server creator and mod creator thing will help more people to see how great creativity is and so that those on the phone don't feel so excluded because we literally can't create mods and neither can a server to play with more people of friends or the lonely ones that we are. I hope you see this content that you could put in the game and that I know all the people who play minedustry will love it.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
the steps for creating mods on mobile are the same as on PC, for JSON and JS mods you only need a good text editor.

making java mods is probably also possible using a terminal emulator.
publishing mods is done via github, again something that isnt impossible on mobile.

for creating servers, the problem is that the server needs a device to run on 24/7. Mobile devices also tend to change IPs often, which would be a big problem.

you can use tools like yggdrasil to play with friends temporarily (see discord -> #multiplayer)

**Comment by BlueWolf3682** [comment]
Mod content has already been created on mobile - see [Exotic Mod](https://github.com/BlueWolf3682/Exotic-Mod), a mod I initially made entirely on mobile.

All you need is a good file manager such as Total Commander, and a spriting tool such as Novix.

**Comment by RouterChainsSuckk** [comment]
Please code this and actually learn how to make a mod, as stated if you have android it’s completely possible already
