### ISSUE TITLE
I dislike the new Command feature.

### ISSUE THREAD

**Issue by DkurowithA** [Anuken/Mindustry-Suggestions#3605]
### Describe what you would like changed, and why.

I and some other people dislike the command feature, it's annoying trying to control a unit to go somewhere and it wants to go through an impossible or harder route, sometimes units when crowded together can push each other to death if there's a liquid nearby. The old system was good, you can control the group of units better. sometimes you want units to target something out of a turrets range when the units can attack it but the units usually creep into the range of the turret and die. 
Assuming both planet blocks are being used or logic blocks get added to Erikir You cannot command logic possessed units now, if you're in danger you can't control units to help. 

### Describe the changes you want to propose. Include possible alternatives.

Include 2 command modes 1 for the new one and 1 for the old one. possibly also adding command center back to the game.

**Comment by end-me-please** [comment]
With the old system units were literally uncontrollable without logic

**Comment by MEEPofFaith** [comment]
and even with logic, there was no pathfinding for ground units, while the new system actually works with ground units.
