### ISSUE TITLE
New turrets and idea to make Attack gamemode better

### ISSUE THREAD

**Issue by SuperTinyDeskEngineer** [Anuken/Mindustry-Suggestions#3607]
### Upgrading turrets armor
In game we can upgrade turret damage and effect with different types of ammo (example: we can put in Ripples Silicon to shoot homing bullets or Pyratite to make bullets flammable), now how about adding the ability to spend some materials to upgrade their hp (armor). 

1 Duo costs 35 copper, when placed it will be shown as "level 1 Duo" with 250hp, you can click on it and window ill pop-up showing materials needed for next upgrade (example: for level 2 you need 200 Copper, 100 Lead and 25 graphite) when you bring all the materials and you can upgrade the turret (upgrading effect can be like you are building that turret but x0.5 slower for each upgrade). When the upgrade is finished that Duo turret will have +150 more hp.
The idea for Duo upgrades: Lv1=250 hp, Lv2=400hp, Lv3=600hp, Lv4= 750hp (max level will be lv4 for small turrets like Scorch or Hail, lv5 for medium turrets like Salvo or Ripple, lv7 for big turrets like Spectre or Meltdown)
The bigger and more expensive the turret is more expensive will be to upgrade it to the next level.

My idea at first was upgrading only HP of that turret, but maybe we can also upgrade Shooting per second or Accuracy or how much can hold ammo/liquid inside but ill rather stick with only upgrading their HP for balance reasons.

### New turrets

**1. Musketeer Tower (it does not contain Musketeer)**
The idea for this turret is a "small" tank buster. While hordes of enemy attacks Musketeer tower will take care of tanky units. Or in 
attack maps, it will shoot units who are shooting other turrets while they were out of their range. Verry good against most units, weak when fighting alone. 

   - HP: 1050
   - size: 2x2 
   - turret range: 25 blocks (like Cyclone) (i was thinking making it 36 blocks like ripple but that would be too strong)
   - shoots 1 bullet every 1.5 seconds
   - can target air, ground and naval units
   - damage type: single target
   - Inaccuracy: 0 degree
   - Cost: 25 Copper , 45 Graphite and 25 Lead
   - Liquids does not boost it

   Ammo and damage:
   - Graphite: 30 damage
   - Silicon: 40 damage, can pierce tharget
   - Titanium: 55 damage
   - Plastanium: 75 damage
   - Surge Alloy: 120 damage

**Cannon**
Turret fires powerful, large-caliber shells towards enemy units, its slower but stronger version of  Musketeer Tower. The turret is effective against tank units but weak when swarmed.

   - HP: 1380
   - size 3x3
   - turret range: 19 blocks (like Salvo)
   - shoots 1 bullet every 3 seconds
   - can target air,ground and naval units 
   - damage type: single target
   - Inaccuracy: 0 degree
   - Cost: 200 copper, 150 Titanium, 100 Graphite
   
   Ammo and damage
   - Silicon: 65 damage
   - Blast: 80 damage, explosive shot
   - Plastanium: 120 damage
   - Surge Alloy: 175 damage
   
**Mortar**
Mortar shoots a massive explosive bullet up in the air, when the bullet falls it explodes. Verry effective against swarms of units, less effective with tank-like units. Cannot shoot at units who stand near him. 

 - HP: 1100
 - size: 3x3
 - turret range: from 40 to 13 block 
 - shoots 1 shell every 5 seconds
 - can only target ground and naval units
 - damage type: Splash
 - inaccuracy: 15 degree
 - Cost: 250 copper, 150 titanium, 175 thorium

Ammo and damage
 - Thorium: 20 damage, 45 blast damage, 2x Ammo Multiplier (blast radius 2x2)
 - Blast: 50 damage, 90 blast damage, 3x Ammo Multiplier (blast radius 4x4)  
 - Surge Alloy: 100 damage, 130 blast damage, 4x Ammo Multiplier (blast radius 3x3)
 

**Tesla Coil**
When the enemy enters the range of tesla coil, it will send electric bolts hitting up to four targets. (electric energy will spread thro 4 targets stunning them and damaging them)
- HP: 750
- size: 2x2
- turret range:20 blocks
- shoots 1 electric bold every 7 seconds
- can target ground, naval and air unit
- damage type: single target then multitarget 
- inaccuracy: 0 degree
- cost: 120 Copper, 100 Silicon, 150 Titanium

Ammo and damage
- turret uses electric energy: 594 power per sec (like 3x arc), dealing 75 damage with 0.5 sec of stun

**Liquid catapult**
The idea for this turret is like a mortar that shoots shells of specific liquid. When liquid falls on the ground it creates a small explosion and leaves liquid behind for a few seconds. When the shell touches the enemy it will have that liquid effect for 5 sec, if the enemy touches liquid on the ground they will have that effect until they leave the liquid.

- HP: 1860
- size 3x3
- turret range: from 10 to 30 blocks
- shoots 1 mortar shell 
- only targets ground units, when a shell fell and explodes, flying enemy around explosion will get the effect
- damage type: Splash
- inaccuracy: 12 degree
- cost 400 Lead, 200 Metaglass, 500 Titanium, 200 Graphite

Ammo and damage
- for any liquid turret needs to have: 5 silicon and 7 metaglass

Liquids:
- Water: deals 10 damage on explosion, when an enemy touches they become wet for 15 seconds, wet enemy gets 3x electric damage
- CrytoFluid: deals 20 damage on explosion, when an enemy touches they walk slow 1.5x times, on explosion freeze enemy for 2.5 second
- Oil: deals 10 damage on explosion, when an enemy touches they become tarred and walk slow 0.7x, on explosion they were covered in oil, they get 3x damage from flame turrets
- Slag: deal 30 damage on explosion, when an enemy touches they start burning, on explosion they burn for 15 seconds

From this point on all ideas are for improving attack gamemode
=================================================================

### Command Centar changes and some factory changes

First Command Centar should have a level system that shows how many units can come around it, level 1 should have 50 housing spaces, each level will rise 50+ housing spaces up to lv10 (500 housing spaces). Units should be ranked by how big they are that much housing space they take:
You can only build max 10 of them on a map.
Units direct from the factory will have 2 housing spaces, from Additive R.: 5 housing space, from Multiplicative R.: 10 housing space, from Exponential R.: 25 Housing space and for Tetrative R.: 50 Housing space
With "unit spaces", CC should have its color (you can choose up to 7 different colors to be that command center) and the ability to request units, when you click on that command center, a window will appear and you can select what units you want in your command center from available factories.

If you want to have Maces (ground unit from Additive Reconstructor[lv2]) in your Centar, but the factory is connected to Exponential Reconstructor (lv4), that mace unit will just pass thro other reconstructors and walk near your center.

In a multiplayer server, each player will have their own Command Center, if they were more than 10 players they will be sharing a command center with a max of 3 players for 1 center (that's 30 players on one map). If they don't like their teammate they could leave his command center in case they were sharing it.

With Command Centar there should be Rally Centar that works as a place for units to gather around who are not requested by C.C. these units will not actively go and attack other buildings but they can defend that area, also they can be invited to other C.C.-s

Unit spaces should be used to force the player to think about strategy, how will they make a successful attack widought just spamming units and hope they will achieve something, also will make server less laggy because some people love to spam units
Colors on  command center should be used to build points where should units attack, first, you activate Red Command center to send tanks to break a wall and expose the base, then you activate Yellow C.C. to send Damage dealers, and at the end, you activate green C.C. to send support units.

### New unit type: Spy>Commander>General, unit control and battle support

**New "Control" Unit Type**

To create these units they have their factory colored Black, they spawn flying and they will wait in front of the factory for a player to control them (with CTRL)
First unit that the factory gives you is a spy, spy does cannot attack, cannot build or enemy buildings/units will attack him (he acts as their unit). He is used to scouting enemy bases and collecting intel.

Adding Additive R. near that factory it gives Commander, Commander works same as a spy but can store up to 15 "support tools" (i will talk about them later)."
Adding Multiplicative R. near that factory it gives General, General works same as spy or commander but can store up to 30 "support tools"

**Weapon Factory and support tools**

A weapon factory is a massive building (with size of 8x8) who is the main function is to produce "support tools". On top of the weapon factory, it has massive cannons and massive artillery, that cannon and artillery have a range of the entire map but it cannot shoot alone.
Support tools are items that can Commander or General use to control and help army in battle. At first, all of them were cheap to make, but for each next of that tool price goes up. (1 mortar shell at first costs 100 copper, 50 silicon, 20 blast, second will cost 150 copper, 100 silicon and 50 blast, third will cost 300 copper, 200 silicon and 100 blast) this will stop others for spamming support tools.
If you are buying a lot of Heal, only price of Heal will go up, price for Barrage or Shock bomb will stay the same.
When late on game prices can be very expensive for some tools, destroying enemy turrets and enemy base will make the price go down, stronger/expensive the turrets is less materials you need to pay.
The area around the enemy core (enemy no build core radius) will have 70% resistance to Mortar shells and Barrage and shock bomb will fall to 3.5 seconds.
Enemy core will be immune to all damage from Weapon Factory.  

List of support tools:
- 1xMortar shell and its flare - When Control unit throws a mortar shell flare on an enemy building, cannon from weapon lab will shoot one mortar shell to that location, effective for destroying key defenses
- 1xFlare of specific color - when thrown on the floor all units from that command center will go to that spot them they will continue to attack, if flare touched the building all units will first attack that building ignoring others,
                              , Commander or General can change in their inventory color of that flare so they don't need to fill up their inv. bunch of flares of different colors
- 1xBarrage and its flare - When thrown artillery from weapon lab will start shooting barrage of rockets to that spot, all that rockets will appear randomly and they will be weaker than mortar shot
- 1xHeal - When thrown on a floor it will make area that will heal your units, which will disappear after 10 sec
- 1xShock Bomb - When thrown on an enemy turret or other building it will disable it for 7 second
- 1xPack of units and its flare - for this you need to place conveyor from unit factories to Weapon factory, W.F. will only accept small units like Dagger, Crawler, Flare... and it will compact 5 of them into a shell.
                                  When commander shoots that flare on the building or the floor, a massive mortar shell will fall but it won't deal any damage, on explosion, it will release 5x of compact units, very good when distracting defenses
- 1xSmoke Granade - When General/Commander thrown it makes area full of smoke for 30 sec, all enemy turret or units cannot see thro smoke (except general, spy or commander) so they cannot shoot you or you cannot shoot them, very good for sending high damage troops in the hearth of the base (don't forget to shock other turrets when smoke runs off)

### Upgrading turrets armor
On late game, i end up with tens of tousands of materials on core but with no space to place down more turrets or new factories, to spend up all these resurce it would be good to upgrade HP of the turrets or maybe other buildings. 

### New turrets:

**Musketeer Tower** - a stronger version of Salvo for both Air and Ground units. Verry good for small tank busting or picking up weak enemies. Mustek tower should work like verry weak ForeShadow mixed with Salvo. If swarmed by small ground it can survive but its best to put him near machene gun turrets.

**Cannon** - stronger version of Musketeer tower but weaker version of ForeShadow.  This turret has improved tank busting ability but with a price of slower shooting speed. Small groups can destory him if left with no support.

I would like to see musketeer tower and cannon into the game because we dont have turret who shoots one accurate bullet on early-game and mid-game.

**Mortar** - artillery who targets groups of ground units. It shoots massive mortar shell up in the air, when mortar shell fell it damages all units around. Weak against air units and tanks.

**Tesla Coil** -  Idea for this turret is that electirc energy should be used to support other turrets. Yes we have Arc who is ok in lower levels and Lancer who has been nerfed and saw people rarely using it. So i created that turret to slow down enemy`s. When the enemy enters the range of tesla coil, it will send electric bolts hitting up to four targets. Electric energy will spread thro 4 targets stunning them and damaging them. 

** Liquid Catapult** - The idea for this turret is like a mortar that shoots shells of specific liquid. When liquid falls on the ground it creates a small explosion and leaves liquid behind for a few seconds. When the shell touches the enemy it will have that liquid effect for 5 sec, if the enemy touches liquid on the ground they will have that effect until they leave the liquid.
I created this turret to turn liquid into a weapon.

Making attack gamemode better
==============================================

### Command center and factory changes

In game we have one Command Center, in command center we can order troops to rally, attack or to be idle. 
Problem is you cant do much from it, when you order them to attack you can only hope that they will destory that part of enemy base with wasting tons of silicon and other resurces.  

For this problem i have some solution:
1. Each Command Center will gets its own color, so you can order only yellow command center to attack while others wait
2. On each Command Center you can request what troop you whant in them, if factory is making troops you dont whant they will stand idle near "Rally Center" (like command center but you cant order troops)
3. Each Command Center will have Housing unit space and level system from lv1 to lv10, this will force players to think what units they whant to attack instead of spamming Flares or Daggers and lagging the server. Command center starts with 50 Housing space, each level adds 50 housing space more up to 500 housing space. 
4. You can put maximum of 10 Command Centers on a map, on multiplayer if they were more that 10 players some players will share a command center, this will make each player give a contribution for attacking the base.

For factory change i would like to see, if someone requested a 10 Mace units in their CC (Ground factory+Additive R.) and at the Ground Factory there were connected with Additive R+Multiplicative R.+Explonential R. , factory will only create Mace and mace will just pass thro Multiplicative R. and Exponential R.

###  New unit type: Spy>Commander>General, unit control and battle support

With better command center we have ability to make better  way to attack. But we still have a problem how to control mass amount of units in battle. For that i created new unit and new "factory/turret" who can control how units would attack and to support them in fight.
Biggest problem for attack maps are that most of them goes the same way: Upgrade your base so you can make Ripple, Build wall of ripple around enemy base, feed them with Cryo Liquid and Plastanium and wait until they break the base. 
When you send a units in early game you are wasting a lot of silicon knowing they would not destroy anything. With this you can control them how you whant them to attack or support other turrers in fight. 
Yes in late game you have acces to stronger units like Antrumbra or Regin so its easyer to attack the base.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why can't people just make one issue per suggestion. 😑

**Comment by itcannotbe** [comment]
> Upgrading turrets armor

Denied

**Comment by itcannotbe** [comment]
> Tesla Coil

What is arc again?

**Comment by RFAC-Productions** [comment]
Jesus no one's gonna read a massive wall of text. I may be a binge reader but even this is too much.
