### ISSUE TITLE
Cores rebalance

### ISSUE THREAD

**Issue by josucoimbra** [Anuken/Mindustry-Suggestions#3608]
I would think it would be cool if the cores were more important they only is used to store resources and be your main base in the game we have 3 different cores on each planet but on erikir we will barely improve the cores because the load capacity is already high only by building more cores

 ### Describe the changes you want to propose.  Include alternatives possible.

 The change itself would be requirements for builds such as to build a foreshadow or specter or even a toxopid in serpulo you would need level 3 core i know a lot of people will hate this idea for making the game longer

**Comment by itcannotbe** [comment]
###### Translated via google

> ### Describe what you would like changed, and why.

> I would think it would be cool if the cores were more important they only serve to store resources and be your main base in the game we have 3 different cores on each planet but on erikir we will barely improve the cores because the load capacity is already high only by building more cores
 
> ### Describe the changes you want to propose.  Include alternatives possible.

> The change itself would be requirements for builds such as to build a foreshadow or specter or even a toxopid in serpulo you would need level 3 core i know a lot of people will hate this idea for making the game longer

**Comment by itcannotbe** [comment]
The sugestion doesn't even make sense.

**Comment by josucoimbra** [comment]
I know he is also used for unit cap and is his main base but that's it for a base in an rts game and little what I mean would be to leave technology levels for each core

**Comment by itcannotbe** [comment]
So basically you want to force people to upgrade the core to access more stuff in the game.

This is very painful for campaign and maybe doable using other things if you're on a server.

**Comment by josucoimbra** [comment]
Exatamente isso

**Comment by josucoimbra** [comment]
exactly

**Comment by josucoimbra** [comment]
with the world processors it would even be better because not only could it take longer but you can also make a list for each block for example to build a swarm you need 2 pira factories that with other towers also with other resources or factories
