### ISSUE TITLE
Do normal logick modul

### ISSUE THREAD

**Issue by Carry228** [Anuken/Mindustry-Suggestions#3609]
### Describe the content or mechanics you are proposing.

Many people's not know how to programming

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Izzyful moduls

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by deltanedas** [comment]
Kocine zgodovine
      Marko Zajc

**Comment by markozajc** [comment]
when the issue is![ajc](https://files.zajc.eu.org/public/face.png)low effort

**Comment by code-explorer786** [comment]
Mindustry Logic is designed to be like Assembly, and not like a normal programming language, therefore hard [1].

There exists many mlog [2] compilers out there, so I suggest you use mlog compilers [3].

*[1] mlog is easier than real world assembly*
*[2] mlog stands for Mindustry Logic*
*[3] an example is [go-mlog](https://github.com/Vilsol/go-mlog), there exists plenty out there*
