### ISSUE TITLE
farming/money? (mod idea)

### ISSUE THREAD

**Issue by thompson8964** [Anuken/Mindustry-Suggestions#361]
**Describe the content or mechanics you are proposing.**

1. farming. i dn't know what it could be used for, except maybe it could be compressed into coal or just fuel. 
2. currency. not really expecting to make into the game but maybe as a mod. used to just buy resources, earned by selling resources/doing missions or quests or something like that 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

i know money probs  will be for late game; buying 1000 plastinium after idling on the first map for the night is too good; perhaps unlocked after certain map. idk

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
This isn't the place to place ideas for mods as the developer do not make mods.
