### ISSUE TITLE
Ability to see area's guardian

### ISSUE THREAD

**Issue by LAMMAZ222** [Anuken/Mindustry-Suggestions#3611]
### Describe what you would like changed, and why.

So, I just had 2 and a half hours of work lost to the nuclear power plant guardian because I had no idea it'd end up not only being flying, but also be several times more tanky than any other guardian I've faced prior. In a case like this where the guardian ends up being the effective final thing to beat, it's really disheartening to basically have to create an entire factory, and then lose it all just so you know what you're going up against.

### Describe the changes you want to propose. Include possible alternatives.

Perhaps, in the info tab or somewhere else, during waves of an area, you would be able to view the type and stats of the guardian unit(s). Maybe something else to help would be more sensitive threat warnings, because just low, medium, and high don't give a lot of information. Maybe some indicator of things that'd be good to have researched beforehand, or a hint as to what enemies and how many enemies you'll be facing.

**Comment by RealYeet** [comment]
And you have clearly not read the read me

**Comment by 50275** [comment]
solution: build an actual defence. you can kill this boss on ground zero. get better.

**Comment by LAMMAZ222** [comment]
> And you have clearly not read the read me
Oh, sorry, I just jumped to this page from the normal github page and it didn't show me the readme until after I made the post, I'll get rid of it.

**Comment by itcannotbe** [comment]
If only you used the proper category/label....

**Comment by LAMMAZ222** [comment]
> If only you used the proper category/label....

I thought this wouldn't have applied to a whole new feature as it would just be the ability to see an area's guardian, it wasn't any sort of new content or a new mechanic, but rather just a tweak to make the game easier, so I thought it would've gone under balancing and feedback.
