### ISSUE TITLE
Command Center Sorting

### ISSUE THREAD

**Issue by HujunChan** [Anuken/Mindustry-Suggestions#3612]
### Describe the content or mechanics you are proposing.

So, After Tapping clicking on the Command Center a new GUI will pop out that you will select a Unit For, like Separating Some Units when Mixed, The Cost of the Command Center will not Change.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

In Campaign it can be a very use, Like if you don't want to use ur Toxopid on the attack or Corvus you can Select it on the Command Center it self, so it will stay there, or in Multiplayer in Hex Fights Or Orange vs Blue, you can Prepare an Army, And Make them go in Random intervels like Campaign Waves, This can be also use to Sort Units so they don't get mixed like if you don't want a Flare on a Army of Crawlers, You can Select Them out of There, Tho it can be Expensive I'm Sure it's Worth it.

> 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Command Centers are already removed entirely from the game, and replaced with a new mechanic
