### ISSUE TITLE
Extra productional information

### ISSUE THREAD

**Issue by xAzazeilie** [Anuken/Mindustry-Suggestions#3613]
### Describe the content or mechanics you are proposing.

A probable a feature which can be enabled and will show item input/output per second, material produced/second (not the top production speed) and probably amount of resource/energy produced by a certain schematic/construction (which can be acessed via selecting a structure)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this addition may help with deciding, which type of conveyor is more effective, which construction is producing more resources and takes less space

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This is close to impossible to implement.

You basically you want something to automagically what the end product of the schematic based on non existent inputs (cause it's a schematic) and it's actual throughput considering bottlenecks.

**Comment by xAzazeilie** [comment]
> ### This is close to impossible to implement.
> You are basically you want something to **automagically** (Yes, magic.) what the end product of the schematic based on non existent inputs (cause it's a schematic) and it's actual throughput and resource requirements to support it with consideration to bottlenecks with in the schematic.

I see, i may have thought of it being possible, but i got this suggestion idea when i was counting maximal item input to optimise my production. Even tho some of those may be impossible, i still suggest something like "peak item input and output" so people may be able to see if their new conveyor lines were worth building

**Comment by buthed010203** [comment]
https://github.com/L0615T1C5-216AC-9437/MaxRateCalculator Exists
