### ISSUE TITLE
Processors

### ISSUE THREAD

**Issue by Slavekrit** [Anuken/Mindustry-Suggestions#3614]
### Describe the content or mechanics you are proposing.

For processors, I would like to create nodes.In them, you can save a sequence of ordinary commands, configure inputs and outputs. You can also add a separate window with the ability to manually write code.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it easier to understand the algorithm, coding is sorely lacking in games for more advanced people.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by buthed010203** [comment]
You can create custom instructions via mods, you can write code in an external text editor and then import it, inputs and outputs are already a thing with sensors and memory banks...

**Comment by buthed010203** [comment]
They really arent though, exporting and importing them takes a few clicks...

**Comment by buthed010203** [comment]
> If Mindustry has their own text editor embedded in Processor, it would likely have Syntax and other nifty shortcuts, and at the same time it can be closed to immediately have effects take place.

I'm almost positive that no one would be willing to put in the work required for syntax highlighting lol

**Comment by itcannotbe** [comment]
You don't need to have fancy features like syntax highlight for one to code.

**Comment by IxGamerXL** [comment]
> You don't need to have fancy features like syntax highlight for one to code.

True, but syntax just makes the code look less boring and more understandable, which is why many programmers prefer syntax. Just cause you don't need syntax doesn't mean it doesn't make coding more convenient to look at.

> > If Mindustry has their own text editor embedded in Processor, it would likely have Syntax and other nifty shortcuts, and at the same time it can be closed to immediately have effects take place.
> 
> I'm almost positive that no one would be willing to put in the work required for syntax highlighting lol

If that was so, many editors wouldn't have syntax. We already have color tags that even players can utilize. I'm pretty sure someone is going to slap on the necessary material to make syntax possible.
