### ISSUE TITLE
PvP with Waves

### ISSUE THREAD

**Issue by MysticalSquirrel** [Anuken/Mindustry-Suggestions#3616]
### Describe the content or mechanics you are proposing.

Would it be possible to either have a game mode or allow waves on PvP/Attack?
I was trying to make a two lanes map sort of like a "who can survive the longest" kind of map to play with my brother and sadly when I got to try it there weren't waves or if I did pick a mode where waves are enabled, I wouldn't be able to join the other team.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow for competitive maps between players who want to discover who can survive the longest against waves.
It's not a new thing necessarily in gaming, but it was never done with a good map editor like Mindustry has.

I know it's most likely not a feature all would use, but regular PvP or Survival with no Split Resource is a little too boring for people like me who like to play with others, but still want to build/plan out their own little part of factory without having to wait for the other to be done building their part.
I don't mean allied teams per say, but just an option to split the resources gained between the team's builders.

Thank you in advance for your time and consideration!
I'm hoping such feature might be interesting enough to maybe make it through a game mode or a simple option in the game's editor when making PvP maps. :)
I would even be happy with a simple "Enable Waves" option when changing the map's settings.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Here is the map image/layout in question I am trying to make if that can give a better explanation of what I would like to do:
![image](https://user-images.githubusercontent.com/1347446/171746626-cedd41fe-cf95-453e-b5b5-e462d16da800.png)

**Comment by 50275** [comment]
This was already possible in V5. Just turn on the wave timer. 90% sure that's all you need.

**Comment by MysticalSquirrel** [comment]
> This was already possible in V5. Just turn on the wave timer. 90% sure that's all you need.

It worked indeed! Just had to turn on both Waves and Waves Timer apparently. Huge thank you! Will close the suggestion right away! :)

I really need to be better at looking / testing through the features available haha
