### ISSUE TITLE
Attack mode without infinite resources

### ISSUE THREAD

**Issue by UmbraResistis** [Anuken/Mindustry-Suggestions#3617]
### Describe what you would like changed, and why.

I'd like the opposing AI to build drills and need to import resources into their core to build more things so that it feels like it's a player versus player while it's against an AI (I don't have friends.)

### Describe the changes you want to propose. Include possible alternatives.

See written above.

**Comment by itcannotbe** [comment]
Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

**Comment by buthed010203** [comment]
> Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

It's possible in a non slow language though its still expensive

**Comment by josucoimbra** [comment]
Me: a nice day to look bad sugestions for mindustry
This guy: ai thats build drills and connect he on the blocks 
Me: this is a bad i . . . . FUCKING GOD THIS SUGGESTION IS A GOD GIFT

**Comment by 50275** [comment]
this sounds like the perfect time for someone to advertise sectorized/eviction/hex pvp/ranked pvp (community servers). no seriously though just go play against humans. these servers allow you to play solo, so no griefers for you.
