### ISSUE TITLE
Bringing back the old command system in tandem with the new one.

### ISSUE THREAD

**Issue by LampbuIb** [Anuken/Mindustry-Suggestions#3618]
### Describe the content or mechanics you are proposing.

     Currently in BE builds, you can only control units which you have selected. While miles better than the old command system, it is a huge hassle to pause, then pan the camera all the way to wherever other units are, then select and go all the way back to whatever you want to attack. Furthermore, if you want to attack multiple locations at once, you will have to select all the units and their destination and constantly micromanage; this takes time, even with time control mods, and is not ideal as while you do this, your base can get neglected and destroyed while you aren't looking (more of a skill issue but the point stands.), and units that you are too busy to select just stand idle. 
**A solution I have to this problem is to bring back the old command system to work in tandem with the new one.**

     If the old command system is brought back, units that would previously sit idle without command can automatically attack enemy defences. This also makes it easier to manually command them as they are (most likely) moving closer to the area that you're in. Also, since the AI will most likely attack a different part of the defence than you, it allows you to strike the enemy at two+ places at once, with all your units.

     Bringing back the command system also brings back the group command (G), which allows me to bring polys/megas/whatever with me.

     Below are also some ways to improve the current command system:
-Make us able to command support units such as polys(polies?), as they usually block out a part of the base and if there are a lot of them I can't see what's underneath and I have to move them all, one by one, into another area.
-A "Select all units" button to avoid said back and forth action.
-Heck, instead of bringing back the old system just put a selection in that allows idle units to attack automatically.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Reduces the amount of micromanaging with the attack of units; can help you use all your resources (in this case, units) instead of what you can allocate in the area. 

"rally" command in command center block helps to bring available units to a specific area for easier selection.
This _is_ my first suggestion, so tell stupid me about anything i'm oblivious to, or if I'm not supposed to suggest this fsr.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LampbuIb** [comment]
wow, the format is crap.

thing I forgot to add:
-Omura's flares don't work good anymore.

**Comment by itcannotbe** [comment]
Micromanaging is what an RTS game is.

**Comment by RealYeet** [comment]
Solution: Increase pan speed.
