### ISSUE TITLE
Nickname change delay

### ISSUE THREAD

**Issue by theonenob** [Anuken/Mindustry-Suggestions#3619]
### Describe the content or mechanics you are proposing.

Make it so there is at least a 1 day delay when you want to change nick 
So that grieffers cant just change names and join back to the server

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Less griefing

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. There are a lot of ways to circumven this.
2. Ban enforcement isn't even based on player name
3. Ask the server owner on the server you play on to do something about it.
4. NO COMMUNITY SERVER IS BEING MANAGED BY THE DEVELOPER.
