### ISSUE TITLE
UUID Check for easier anti-grief

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#362]
**Describe the content or mechanics you are proposing.**
When started, each instance of the Mindustry client generates a UUID for itself and checks to see if Mindustry has been launched on the current computer before by looking for a hidden file in the AppData folder. If it has, it assumes the UUID that's posted there. If not, it creates a file with its UUID. When connecting to any server, the player is identified in two ways: their IGN, which they can change, and their UUID, which is invisible to players but is broadcast to the server. The server only checks for the UUID when comparing against a blacklist, bypassing attempts to spoof the system by changing your IGN. Additionally, the game client caches the UUID when playing, and writes it back to the file when closed, as well as saving it to the game settings itself. This would prevent trolls and griefers from simply deleting the file or downloading multiple clients. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think this would provide an extremely effective way to ban hackers and cheaters, as it removes the normal way of bypassing kicks and bans by changing your username. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> each instance of the Mindustry client generates a UUID for itself and checks to see if Mindustry has been launched on the current computer before by looking for a hidden file in the AppData folder

Mindustry already does this.

> The server only checks for the UUID when comparing against a blacklist, bypassing attempts to spoof the system by changing your IGN.

Mindustry *never* used names to identify banned players, it was always UUID+IP-based. I'm not sure what gave you that idea.


> Additionally, the game client caches the UUID when playing, and writes it back to the file when closed, as well as saving it to the game settings itself. This would prevent trolls and griefers from simply deleting the file or downloading multiple clients.

If you have a hacked client that sends a different UUID, it doesn't matter what's cached or not. You could send whatever you like to the server, since you have full control of its actions.
