### ISSUE TITLE
Handle corrupted save file differently

### ISSUE THREAD

**Issue by TheAirBlow** [Anuken/Mindustry-Suggestions#3621]
### Describe the content or mechanics you are proposing.

When Mindustry cannot load a sector, it immediately resets it as it is corrupted.
Instead, it should be a Yes/No dialog, that states this:
```
Your save file seems to be corrupted.
It may happen due to mods being deleted or save file being incompatible with this version.
Do you want to reset this sector (you would have to recapture it)?

[Yes] [No]
```

Basically a small feature to make the game more foolproof.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Would be life changing for dumbasses like me who updated from v125 to BE with incompatible mods lol

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
That's actually more annoying for the end user.

**Comment by itcannotbe** [comment]
ALSO THIS IS WHY PEOPLE WHO DON'T KNOW WHAT THEY'RE DOING SHOULDN'T WILLY-NILLY RUN THE BLEEDING EDGE.

**Comment by itcannotbe** [comment]
Furthermore, having a dialog like that doesn't prevent that sector from being "corrupted", the only thing the game knows is when it encounters unexpected errors on the save file, it will try to load the back up, then if that doesn't work, consider the save file unreadable.

**Comment by TheAirBlow** [comment]
a settings to disable it shfjahkfljaklbyeryov

**Comment by TheAirBlow** [comment]
> Furthermore, having a dialog like that doesn't prevent that sector from being "corrupted", the only thing the game knows is when it encounters unexpected errors on the save file, it will try to load the back up, then if that doesn't work, consider the save file unreadable.

it does prevent it from being "corrupted", until the sector is loaded it is untouched and left alone, unmodified.

**Comment by TheAirBlow** [comment]
> That's actually more annoying for the end user.

How? Even amount of clicks wouldn't change. There is a notification that states "The save file is corrupted", with an OK button.
Replace it with the one I said above, and if the player really wants to reset it, he would just click yes instead of OK.

**Comment by TheAirBlow** [comment]
> ALSO THIS IS WHY PEOPLE WHO DON'T KNOW WHAT THEY'RE DOING SHOULDN'T WILLY-NILLY RUN THE BLEEDING EDGE.

We're all sometimes fools, and this may happen in other scenarios that this.

**Comment by TheAirBlow** [comment]
@itcannotbe

**Comment by itcannotbe** [comment]
> > That's actually more annoying for the end user.
> 
> How? Even amount of clicks wouldn't change. There is a notification that states "The save file is corrupted", with an OK button. Replace it with the one I said above, and if the player really wants to reset it, he would just click yes instead of OK.

And you have to do it with every sector on your save.....

**Comment by itcannotbe** [comment]
> > ALSO THIS IS WHY PEOPLE WHO DON'T KNOW WHAT THEY'RE DOING SHOULDN'T WILLY-NILLY RUN THE BLEEDING EDGE.
> 
> We're all sometimes fools, and this may happen in other scenarios.

Not an excuse. You could have avoided this if you have manually back uped you game before running a **testing** build in the first place.

**Comment by itcannotbe** [comment]
> > Furthermore, having a dialog like that doesn't prevent that sector from being "corrupted", the only thing the game knows is when it encounters unexpected errors on the save file, it will try to load the back up, then if that doesn't work, consider the save file unreadable.
> 
> it does prevent it from being "corrupted", until the sector is loaded it is untouched and left alone, unmodified.

And your campaign save?

**Comment by Mnemotechnician** [comment]
why is a quality-of-life improvement that's obviously useful bothering you so bad? 
the fact that the user is a dumbass doesn't mean that you shouldn't try to minimise the amount of harm they can cause to themselves.

**Comment by itcannotbe** [comment]
> Basically you're telling me that it is better to make the user stfu and leave them with their problems and depression because of non-cancellable reset (which is a big loss).

![Not my problem](https://c.tenor.com/VaIXoTeg3fwAAAAM/bike-fall-meme-bike-fall.gif)

**Comment by TheAirBlow** [comment]
> > Basically you're telling me that it is better to make the user stfu and leave them with their problems and depression because of non-cancellable reset (which is a big loss).
> 
> ![Not my problem](https://camo.githubusercontent.com/2d8d0c44a0855423cb10ffdcf773c1d6213e7f9da3a44b9ceb5a2bd4a259e37e/68747470733a2f2f632e74656e6f722e636f6d2f566149586f546567336677414141414d2f62696b652d66616c6c2d6d656d652d62696b652d66616c6c2e676966) [ ](https://camo.githubusercontent.com/2d8d0c44a0855423cb10ffdcf773c1d6213e7f9da3a44b9ceb5a2bd4a259e37e/68747470733a2f2f632e74656e6f722e636f6d2f566149586f546567336677414141414d2f62696b652d66616c6c2d6d656d652d62696b652d66616c6c2e676966) ![Not my problem](https://camo.githubusercontent.com/2d8d0c44a0855423cb10ffdcf773c1d6213e7f9da3a44b9ceb5a2bd4a259e37e/68747470733a2f2f632e74656e6f722e636f6d2f566149586f546567336677414141414d2f62696b652d66616c6c2d6d656d652d62696b652d66616c6c2e676966) [ ](https://camo.githubusercontent.com/2d8d0c44a0855423cb10ffdcf773c1d6213e7f9da3a44b9ceb5a2bd4a259e37e/68747470733a2f2f632e74656e6f722e636f6d2f566149586f546567336677414141414d2f62696b652d66616c6c2d6d656d652d62696b652d66616c6c2e676966)

There is a "not my problem" hidden, fuck you. What if it was you? You would probably do the same thing as you weren't even warned (there is no warning yet, only immediate action)

**Comment by Mnemotechnician** [comment]
> Because it's a bad way to handle things.
> 
> If you truly wish to warn them, just give a warning as soon as the user runs the testing version, of them possibly breaking their own saves if the wish to continue using the testing version. Not warn them every time they choose to open a sector thay has issues.
> 
> Plus a way for people who know what they are doing to hide the warningb by having a specific file present somewhere in their saves forlder (like a key of sorts).
> 
> It's not an artificial block, just a big "Didn't I tell you? Now stop complaining"

this is straight up gatekeeping, your arguments are just "EVERYTHING SHOULD BE BRUTAL" and they don't make any sense.

There is __a lot__ of dialogs like the one that's being suggested, yet you aren't complaining about their existence.

**Comment by itcannotbe** [comment]
Disclaimers aren't there to prevent people from doing stupid things, it to prevent blaming the creator/manufacturer for stupid things people do.

**Comment by TheAirBlow** [comment]
> > Because it's a bad way to handle things.
> > If you truly wish to warn them, just give a warning as soon as the user runs the testing version, of them possibly breaking their own saves if the wish to continue using the testing version. Not warn them every time they choose to open a sector thay has issues.
> > Plus a way for people who know what they are doing to hide the warningb by having a specific file present somewhere in their saves forlder (like a key of sorts).
> > It's not an artificial block, just a big "Didn't I tell you? Now stop complaining"
> 
> this is straight up gatekeeping, your arguments are just "EVERYTHING SHOULD BE BRUTAL" and they don't make any sense.
> 
> There is **a lot** of dialogs like the one that's being suggested, yet you aren't complaining about their existence.

I'll agree with that I am beginning to gatekeep stuff, but still, would you choose a "phew, I can just downgrade back and play safely" or "fuck off, I just lost my main sector"? This is what we're arguing about rn.

**Comment by Mnemotechnician** [comment]
what's the point of this gatekeeping? the suggested feature:
- does not affect performance in any way
- improves the UX (user experience, ever heard of this thing?)
- requires 10 minutes to implement

**Comment by TheAirBlow** [comment]
> Disclaimers aren't there to prevent people from doing stupid things, it to prevent blaming the creator/manufacturer for stupid things people do.

I'll translate once again "shut the fuck up, it's your problem"

**Comment by itcannotbe** [comment]
> > Disclaimers aren't there to prevent people from doing stupid things, it to prevent blaming the creator/manufacturer for stupid things people do.
> 
> I'll translate your words once again - "shut the fuck up, it's your problem"

Good translation.

**Comment by itcannotbe** [comment]
> what's the point of this gatekeeping? the suggested feature:
> 
>     * does not affect performance in any way
> 
>     * improves the UX (user experience, ever heard of this thing?)
> 
>     * requires 10 minutes to implement

It's not gatekeeping.

Did it prevent you from testing the testing build?

**Comment by Mnemotechnician** [comment]
if it is not gatekeeping, then what is this
your whole argument base is just "SHUT UP", "IT'S YOUR PROBLEM", "DON'T PLAY BE"

**Comment by itcannotbe** [comment]
If you aren't prepared to deal with errors when using the testing version, don't use the testing version.

**Comment by Mnemotechnician** [comment]
> If you aren't prepared to deal with errors when using the testing version, don't use the testing version.

another "shut up, don't play BE". no constructivism.

**Comment by TheAirBlow** [comment]
> If you aren't prepared to deal with errors when using the testing version, don't use the testing version.

Basically any usual player:
> The version has Erekir? Why not download latest build!
> BE? Idk what does that mean, let's continue
> \*Launches the game*
> Ah, that meant bleeding-edge!
> \*Continues as normal*

There is NO WARNING AT ALL, and the name doesn't even have "testing" in it, so the user just ignores the name of the version. Now what would you respond with? The same arguments again?

**Comment by itcannotbe** [comment]
Exactly, just stick one warning upon loading the BE, everytime you load the BE, wherein the disable for said warning cannot be found inside the game.

**Comment by itcannotbe** [comment]
Seriously whose idea was it to tell people to get BE without telling them the risks of using BE.

**Comment by TheAirBlow** [comment]
> Exactly, just stick one warning upon loading the BE, everytime you load the BE, wherein the disable for said warning cannot be found inside the game.

Yes, it should be there. But this still makes user's experience a lot better. It would've probably still happened with the finished v7 - it mostly caused by incompatible mods.

**Comment by itcannotbe** [comment]
The situation will be better by them. Most likely min version will probably catch those issues.

**Comment by IxGamerXL** [comment]
This kind of feature would definitely be good as caution tape incase the player screws up one of their sectors. It would be crushing if you lost your hard work over corruption just cause a prompt wasn't there to tell you that it might not be the best idea to load it. Saving a backup of the "corrupted" instance could probably make it so that you can optionally recover it after the wipe.

Better yet, there should actually be a prompt that tells you that the save has been played on a different version, and asks you if you are willing to risk playing the saves on the new version at the expense of potential corruption. Plus, it shows you a list of saves that have been played on different versions. If you want to dismiss the prompt for all saves, there would be a button for that, and if you only want the save you're loading to have the prompt dismissed, click Continue. If you don't want to mess with it at all, just Cancel.

> > I'll agree with that I am beginning to gatekeep stuff, but still, would you choose a "phew, I can just downgrade back and play safely" or "fuck off, I just lost my main sector"? This is what we're arguing about rn.
> 
> no, @itcannotbe is the one who's gatekeeping. I'm agreeing with you.

> ...tbh that's how you react to most suggestions, i feel like you're venting in this repository instead of giving constructive critique.

He's the kind of kid that always complains about the worst parts in suggestions just because he's got a tight as hell niche requirement. I'm pretty sure he even agreed on the idea of something in a past thread that would obviously be a terrible idea. I think it's time we start ignoring him considering how redundant every argument he starts is.

**Comment by TheAirBlow** [comment]
> Better yet, there should actually be a prompt that tells you that the save has been played on a different version

@IxGamerXL, tried to search for game's version (not save format version) in the code. It seems like it is not a thing yet. 
Save file format is not something Anuken would probably like us to touch, so it is out of my scope.

**Comment by IxGamerXL** [comment]
> > Better yet, there should actually be a prompt that tells you that the save has been played on a different version
> 
> @IxGamerXL, tried to search for game's version (not save format version) in the code. It seems like it is not a thing yet. 
> Save file format is not something Anuken would probably like us to touch, so it is out of my scope.

You might be able to create a custom file that handles the version data for each save. It would have to find out which version snippet is going where, but if you know how the format functions, you could just reverse the format and index each version to it. However, my brain tends to implode on contact with confusing scenarios, and I can't tell if this would be possible.

**Comment by IxGamerXL** [comment]
> > 'm pretty sure he even agreed on the idea of something in a past thread that would obviously be a terrible idea and could probably ruin the game in it's entirety.
> 
> @IxGamerXL, #3434, yeah xD

It's way worse than you think lmao #3279
