### ISSUE TITLE
Allow 'Set Flag' instruction to be able to store both strings and numbers.

### ISSUE THREAD

**Issue by Intervection** [Anuken/Mindustry-Suggestions#3622]
### Describe the content or mechanics you are proposing.

World processors really are changing the mapping community, people now who wants to make maps usually desires to learn mlog to further enchance their mapping features. 

The 'Set Flag' instruction is a very nice way to transport data across other world processors especially on different teams, however it can only store boolean values or true and false. I would request to modify 'Set Flag' instruction to be able to store both strings and numbers that opens up new doors for many unique map gamemodes that the community can possibly make.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This request can increase the community mapper's possibility of making new and unique map gamemodes due to a more dynamic way of transporting data across multiple world processors with different teams. This in term can help add more gameplay option for people who desires unique map gamemodes made from the mindustry community itself.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
I agree. Having only zeros and ones just limits the possibilities, and after all, Memory Cells do just fine having a float value per slot, so why not here? String values could be used as a way to set special blocks to a certain message or mode, like a Broadcast panel that sends a message to all existing message blocks.

**Comment by Intervection** [comment]
Same here, if 'Set Flag' was able to set strings, we could store built-in variables like @copper, @conveyor, @silicon-crucible, and alot more. We could even store a player's name in it. At this way, we could have more ideas on making unique map gamemodes and causes 'Set Flag' and 'Get Flag' to gain more purpose and becomes less underrated.

At this moment, 'Set Flag' is just the same as linking a sharded and crux world processor on one malis world cell but more useless.

**Comment by Bassem-Const** [comment]
AAAAAAAAAAAAAAAAAA STRING MEMORY CELLS

**Comment by Intervection** [comment]
Damn bro i also wanted that too.
