### ISSUE TITLE
Cryofluid mixer description clarification

### ISSUE THREAD

**Issue by LAMMAZ222** [Anuken/Mindustry-Suggestions#3624]
### Describe what you would like changed, and why.

remove the "fine titanium powder" bit from the description of the cryofluid mixer. It's probably just a skill issue, but I am now several hours into the campaign, to the point of creating surge alloys and whatnot, and I only JUST learned that cryofluid takes normal titanium. It's not insane to think that the game might have you end up using a stronger pulverizer on titanium to make powder, and so I went quite a while without cryofluid.

### Describe the changes you want to propose. Include possible alternatives.

Change the description of the cryofluid mixer to not have "fine titanium powder" so that idiots like me have a bit of a smoother time playing. It could be changed to just "titanium" or to "Crushes titanium into a fine powder to mix with water to create cryofluid" or something.

**Comment by 50275** [comment]
so you read the description but not the 'input' section?

**Comment by LAMMAZ222** [comment]
yup
again, I am an idiot, and I believe I'm not the only idiot
