### ISSUE TITLE
Ekrir Command Center

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry-Suggestions#3627]
### Describe the content or mechanics you are proposing.

I would like for the command center to be brought back and have the current way of commanding units still exist as well because sometimes, I want the unit AI to take over and I can just wait patiently, rather than right-clicking left click to select and doing it again.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe that this will make a lot of people's lives easier, as you can just wait and finish the map, and also build up defenses while your units attack for you.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Micromanaging is required in RTS games.

**Comment by McJoe21** [comment]
I click attack with it and they still mine ores

**Comment by Bottinator22** [comment]
> I click attack with it and the drones still mine ores

Monos don't even have weapons, what do you expect them to do, get themselves killed?
Some units have utility purposes and can be commanded by neither the new method nor the old method.

More specifically: Mono, Poly, Mega, all Erekir core units, Serpulo core units pre-Erekir

**Comment by Neil2101** [comment]
> And Mindustry is finishing the transition to one
> Micromanaging is required in RTS games.

Ahhh, I see Thanks!
