### ISSUE TITLE
some suggest for content to serpulo

### ISSUE THREAD

**Issue by sealheart12** [Anuken/Mindustry-Suggestions#3631]
### Describe the content or mechanics you are proposing.

ı think more energy generator is great, ı have some idea about it;
Particle Accelerating=1200 copper,600 titanium,150 phase fabric,300 plastanium,500 thorium,40/s slug    1 minute to build                                    
8x5 
3000 energy need to starting
22500 energy output

advanced Battery=200 lead,75 titanium,40 thorium,25 surge alloy          have 225k energy storage
and last one ı suggest, 4x4

Dark matter fusion's=1000 thorium,450 surge alloy,600 phase fabric,2250 lead,1500 titanium,150/s cryofluid,25/s slug     
3 minute to build             12500 energy need to starting,45000 energy output,this can have 100k energy storage itself
if in not enough have cryofluid it will be create a blackhole to eat everything in map basically wipe your map
12x12

this can be bullshit all ı say,i just want to suggest 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i want them in the game because ı want more target to create in electrocity.
like ı say in up it is diffucult to proceed i think and it can be risky not particle acc. but dark matter fusion's is very dangerous to use lead to ı say,my suggest it is
it is bad or good ı dont know but if you think 'this is bullshit' you are right.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I am right.

**Comment by sealheart12** [comment]
Sorry for disturb man

8 Haz 2022 Çar 14:38 tarihinde itcannotbe ***@***.***> şunu
yazdı:
