### ISSUE TITLE
add /js on hosted servers

### ISSUE THREAD

**Issue by yesC48** [Anuken/Mindustry-Suggestions#3635]
### Describe the content or mechanics you are proposing.

add /js so that anybody who has the following can do stuff /js chads are supposed to do (not that I've no friends who play mindustry…)
- Testing Utilities mod (or /js knowledge)
- Administrator permissions (in hosted server)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

adding /js is torture, everyone else with common sense knows damn well, but if you can pull it of, not only will i praise you (anuke) as a good developer but also **admins can now either turn the tide, depending on how evil they are, or settle the dust for both enemy teams (pvp or pve)**.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Skill issue.

**Comment by end-me-please** [comment]
Mindustry is not exactly a secure Protocol and /js is not far from root access to the machine the server is running on.

right now the vanilla server should be mostly bullet proof, even if someone manages to spoof admin status.

adding vulnerabilities is best done with plugins and not the normal server.

**Comment by code-explorer786** [comment]
There is a plugin for that, called JSEval.

**Comment by yesC48** [comment]
hmm, okay
