### ISSUE TITLE
The multicraft block (on JSON/HJSON)

### ISSUE THREAD

**Issue by EdwardBrok** [Anuken/Mindustry-Suggestions#3637]
### Describe the content or mechanics you are proposing.

As you know, Mindustry hasn't class of block named multicraft. Instead of that, modmakers needs to make such blocks on Java or JS. It is discomfort to guys who didn't learned Java and JS. I offer to create new JSON/HJSON class named Multicraft: in this class, modmakers can create different recipes easily as if they will do it in UnitFactory but only with items and/or liquids

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Maybe this thing won't improve game but it hundred-percently improve developing Mindustry mods. We need more comfortable way to create multicraft blocks. Do it at least for modmakers

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
there's no "Multicraft". you may have confused it with Minecraft™.

**Comment by IVV-NCX** [comment]
Why would a factory to craft multiple items with the same factory work?
It's an RTS game. 

The whole reason schematics exist is because those blocks don't exist. If you add it, it becomes too easy, it begins to lack the whole "build and design" factor in the game. It ruins the game's identity by doing so.

Maybe we could have an item that could make silicon or graphite in a single factory (hard maybe, I wouldn't want it though), but overall, it just hurts the game's identity.

**Comment by EdwardBrok** [comment]
Guys, some mods must be obliged to include multicraft blocks. It is very difficult to do this on Java or JS.

**Comment by Mnemotechnician** [comment]
> must be obliged

what obliges you lmao
is there some shady subcommunitential organisation that forces poor prople to make mods???

**Comment by EclipseTheOldOne** [comment]
> It is very difficult to do this on Java or JS

no, get real
also adding unused class just make the game file itself heavier
