### ISSUE TITLE
email

### ISSUE THREAD

**Issue by ImongUs1021** [Anuken/Mindustry-Suggestions#3638]
### Describe the content or mechanics you are proposing.

I wish there is an email system so that I could play the same world on different devices. I play Mindustry on my phone and computer but they are on different progress, I wish I can play the progress that is on my computer on my phone.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will help me a lot.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest
###### These have been proposed many times already, and I won't be adding them.
- Built-in cloud sync

**Comment by itcannotbe** [comment]
How could you have missed that?

**Comment by itcannotbe** [comment]
As an alternative, use the built in game data import/export feature.

**Comment by stuffyAI** [comment]
It would've helped greatly if the heading was a little more... descriptive.

Just "email" has nothing to do with what you actually want



> As an alternative, use the built in game data import/export feature.

My man, can you start using the edit function?
Why make people get 3 mails for something you clearly could've put in a singular message.
And don't bother with integrity, github grants full edit history view even for comments.

**Comment by stuffyAI** [comment]
That doesn't answer anything I asked of you, there is a reason you might want to be subscribed to a suggestion, especially if you don't want to look though all alerts to find changes.

It is simply annoying to get 3 messages of the same guy that might as well just use one.

Just use edits
