### ISSUE TITLE
cell and banks get saved in schematic

### ISSUE THREAD

**Issue by AMPW-german** [Anuken/Mindustry-Suggestions#3639]
### Describe the content or mechanics you are proposing.

as the title say, I want that the var stats of cells and banks are saved in schematics or at least that there is another easy way to copy the entire var stats to another cell/bank

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would help to share complex logic that requires very many vars that cant saved in a processor (like my current try to build mindustry in mindustry with logic displays)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
You can make a single micro processor that writes the values you want to the membank

**Comment by AMPW-german** [comment]
> You can make a single micro processor that writes the values you want to the membank

then tell me how I should do this to get the values to another map?

**Comment by itcannotbe** [comment]
Just write your logic in a way that it can do it after you placed down the schematic.

**Comment by AMPW-german** [comment]
> Just write your logic in a way that it can do it after you placed down the schematic.

.............................................................................
dont you think its a little bit too much for at least 350 vars

**Comment by AMPW-german** [comment]
and there will be much more vars later

**Comment by AMPW-german** [comment]
> Just write your logic in a way that it can do it after you placed down the schematic.

I'm using a fixed map for my mindustry and you really wanna tell me that I should write at least 350+ vars into a processor

**Comment by IxGamerXL** [comment]
> You can make a single micro processor that writes the values you want to the membank

> Just write your logic in a way that it can do it after you placed down the schematic.

@itcannotbe @end-me-please Can you detail both @AMPW-german and I on how you can intuitively save each individual cell value? There are 64 slots for cells and a whopping 512 slots for banks. To save each individual slot by hand or by mod would be a pain to execute, and might not even work fast enough if the memory saved exceeds the the speed of processors. Even if it did work, it's a waste of materials if you don't have Sandbox mode enabled, and it's a waste of space for schematics.

Of course, importing large quantities of data should be optionally prevented by the server if you're on multiplayer.

(I'm starting to think end-me-please is just itcannotbe's alt so he has extra leverage)

**Comment by itcannotbe** [comment]
> > Just write your logic in a way that it can do it after you placed down the schematic.
> 
> I'm using a fixed map for my mindustry and you really wanna tell me that I should write at least 350+ vars into a processor

What was the use case again? You never mentioned it.

**Comment by AMPW-german** [comment]
> > > Just write your logic in a way that it can do it after you placed down the schematic.
> > 
> > 
> > I'm using a fixed map for my mindustry and you really wanna tell me that I should write at least 350+ vars into a processor
> 
> What was the use case again? You never mentioned it.
I written in my feature request that I'm building mindustry in mindustry with logic displays and nearly everything is saved in banks.

**Comment by AMPW-german** [comment]
I'm also expanding the map later because its currently only 44x44, later it'll at least 88x88 so this means at least 1400 vars if I would use a 7 digit save.

**Comment by Sector171** [comment]
Hmm, you can use sorters(or inverted sorters), each one represents I think (4 bits), for 24 bit long number you need 6 sorters, the max scheme area I think it is 37*37 = 1369 tiles, you need few of them for hyper processor and cryo and wax and micropro and other stuff..etc, divide the remaining on 6 the result is 224.
So using this logic you can save a scheme encoding 224 number each of them 24 bits long.
Not bad!

**Comment by AMPW-german** [comment]
> Hmm, you can use sorters(or inverted sorters), each one represents I think (4 bits), for 24 bit long number you need 6 sorters, the max scheme area I think it is 37*37 = 1369 tiles, you need few of them for hyper processor and cryo and wax and micropro and other stuff..etc, divide the remaining on 6 the result is 224. So using this logic you can save a scheme encoding 224 number each of them 24 bits long. Not bad!

not a very nice idea. and i already knew that. problem: where the heck should I place all needed sorters.

**Comment by AMPW-german** [comment]
found another (better) way to do it: simplex noise
