### ISSUE TITLE
Please add some dedicated units for transporting.

### ISSUE THREAD

**Issue by Qiu233** [Anuken/Mindustry-Suggestions#3640]
### Describe the content or mechanics you are proposing.

The units dedicated for transporting should have larger item capacity, faster velocity and larger(or infinite) command limit but cannot attack or repair any other units or buildings.
Additionally there should be units that can carry liquids instead of items.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Units should be a common way of transporting but so far we have no dedicated units for it. Mono and its descendants serve multiple purposes but don't do well in transporting.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Sounds OP.

**Comment by IVV-NCX** [comment]
Is OP. 

Takes away the "make a stable and fixable infrastructure and create a powerful defense" part of an RTS game. Also, that's the Flare's job. Liquid is also really OP, it can pretty much double your defense's strength.

**Comment by Qiu233** [comment]
> Is OP.
> 
> Takes away the "make a stable and fixable infrastructure and create a powerful defense" part of an RTS game. Also, that's the Flare's job. Liquid is also really OP, it can pretty much double your defense's strength.

Flare has only 4 command limit and 20 item capacity. Well, forget about the liquids'. I think we need at least one type of units that can carry items and has an infinite command limit.

**Comment by itcannotbe** [comment]
Ah yes, payload launcher doesn't exist.

**Comment by itcannotbe** [comment]
To be honest, if you're planning never to use conveyors.

Mindustry might not be the game for you.

https://github.com/Anuken/Mindustry/blob/7ac2645a634f8311e14faf53b7af7815d5aa4e04/fastlane/metadata/android/en-US/full_description.txt#L1

**Comment by Qiu233** [comment]
> To be honest, if you're planning never to use conveyors.
> 
> Mindustry might not be the game for you.
> 
> Game Description: [Create elaborate supply chains of conveyor belts ...](https://github.com/Anuken/Mindustry/blob/7ac2645a634f8311e14faf53b7af7815d5aa4e04/fastlane/metadata/android/en-US/full_description.txt#L1)

No, I don't mean to get rid of conveyors. Actually I would prefer using units instead of conveyors inside some `complex` and `compact` structure where conveyors does not fit.
BTW, the logic processors could play a more important role in transporting with units.

**Comment by IVV-NCX** [comment]
> Flare has only 4 command limit and 20 item capacity. Well, forget about the liquids'. I think we need at least one type of units that can carry items and has an infinite command limit, no matter how many it can carry or it's flying or ground unit.

That's the point. You can also command with logic for automatic control.
Remember, having an unlimited carry capacity and command limit completely nullifies conveyers (overall throughput, maximum build capacity, etc), and it doubles your base's defensive power with liquid. Which is extremely powerful.

The complex and compact structures, a skill issue. The schematic system exists and works because there isn't a way to easily mass-port resources across distances. 

It literally destroys the purpose of a lot of things in the game.

**Comment by Qiu233** [comment]
> > Flare has only 4 command limit and 20 item capacity. Well, forget about the liquids'. I think we need at least one type of units that can carry items and has an infinite command limit, no matter how many it can carry or it's flying or ground unit.
> 
> That's the point. You can also command with logic for automatic control. Remember, having an unlimited carry capacity and command limit completely nullifies conveyers (overall throughput, maximum build capacity, etc), and it doubles your base's defensive power with liquid. Which is extremely powerful.
> 
> The complex and compact structures, a skill issue. The schematic system exists and works because there isn't a way to easily mass-port resources across distances.
> 
> It literally destroys the purpose of a lot of things in the game.

OK, forget about all the unlimited stuffs. We still need the units for transporting.
For example, supplying the overdrive dome with phase-fabric and silicon using only conveyors would be annoying because the domes are often scattered throughout the map. It's not easy to alter the existing complete transporting/routing system only to acquire some bonus.

**Comment by IVV-NCX** [comment]
> OK, forget about all the unlimited stuffs. We still need the units for transporting. For example, supplying the overdrive dome with phase-fabric and silicon using only conveyors would be annoying because the domes are often scattered throughout the map. It's not easy to alter the existing complete transporting/routing system only to acquire some bonus.

Flare. Also, a 250% boost in production is very powerful, arguably broken if not for its extremely high cost. Even then, a projector gets 50% boost in strength to 225% boost with just phase fabric. The answer here, and always is, “git good”, we can’t remove the struggle and challenge because someone doesn’t like it, it’s what makes a game fun.

**Comment by Falling10fruit** [comment]
Flare, and git good.
Maybe don't make so much spaghetti then.

**Comment by RouterChainsSuckk** [comment]
There are other units then flares if you really need item transportation, I believe t4 air unit has the fastest item transportation speed in the game

**Comment by RouterChainsSuckk** [comment]
> To be honest, if you're planning never to use conveyors.
> 
> Mindustry might not be the game for you.
> 
> Game Description: [Create elaborate supply chains of conveyor belts ...](https://github.com/Anuken/Mindustry/blob/7ac2645a634f8311e14faf53b7af7815d5aa4e04/fastlane/metadata/android/en-US/full_description.txt#L1)

Uhhh your forgetting flow gates, bridges, and junctions already make conveyors useless however I agree more units for item slavery is cancer

**Comment by Falling10fruit** [comment]
> > To be honest, if you're planning never to use conveyors.
> > Mindustry might not be the game for you.
> > Game Description: [Create elaborate supply chains of conveyor belts ...](https://github.com/Anuken/Mindustry/blob/7ac2645a634f8311e14faf53b7af7815d5aa4e04/fastlane/metadata/android/en-US/full_description.txt#L1)
> 
> Uhhh your forgetting flow gates, bridges, and junctions already make conveyors useless however I agree more units for item slavery is cancer

Those are a lot more confusing than conveyor belts, plus relying on those makes it harder to use plastanium belts. Also it looks worse.
