### ISSUE TITLE
Better Editing.

### ISSUE THREAD

**Issue by LegendZen** [Anuken/Mindustry-Suggestions#3642]
### Describe the content or mechanics you are proposing.

1.Having a copy + paste terrain for pasting terrain like a schematic.
2.Have new types of brushes like terrain eraser, curve brush, and shaped brushes.
3.Having real time editing is also viable due to the unpredictable nature some designs. 
4.Have the blocks and terrain section be cut into sections. Sure the search is also a good option,
but having the blocks sorted out to find it much more easily.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I would think this would be great for people for editing, as map editing takes fairly long and would end up pretty bad for paused mistake an editor could've had. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Now let's add this to the list of suggestions that basically suggest copy+ paste operation in editor.

**Comment by itcannotbe** [comment]
> Having real time editing is also viable due to the unpredictable nature some designs.

What do you mean by this?

**Comment by itcannotbe** [comment]
> terrain eraser

Pointless as there isn't any underlying tiles underneath "terrain"

> shaped brushes

I don't see a good use case for this. Honestly if copy+paste/schematics for editor is a thing, this is kinda redundant.

Also current there isn't a way to auto layout shapes in the game. Certainly adding it in for the some purpose of this being a thing isn't something one would spend time on.

**Comment by numer99** [comment]
anuke has time and time before tried to make copy-paste in editor, and he has explained that it was a buggy mess

**Comment by numer99** [comment]
but. shaped brushes and terrain-only erasers is a very good idea, and would be much easier to implement
And I think it is a good idea
