### ISSUE TITLE
Polys should rebuild the base instead of attacking the sharded core mindlessly.

### ISSUE THREAD

**Issue by LampbuIb** [Anuken/Mindustry-Suggestions#3643]
### Describe the content or mechanics you are proposing.

I have noticed that in attack maps of the latest BE version (22658), Polies don't actually repair the enemy base; instead, they just go straight to sharded base and attack. i suggest that polies should just do their original job and repair since their weapons do minimal damage.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

attack maps will be harder (or returned to their original... hardness) since enemy bases will be repaired again.

wait a second is this even intentional?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Neil2101** [comment]
well, on maps where ai building is off, polies do have the ai of a zenith...
![image](https://user-images.githubusercontent.com/66876298/173666068-cd474b75-8232-4ffe-a370-180111d7c527.png)

**Comment by OnyxFinger** [comment]
yes but that was hurrendous. I dunno though, it still makes sense because there is no reason for a ploy to attack, it'd just be another albeit annoying way to make attack maps harder.

**Comment by buthed010203** [comment]
Polys.

**Comment by LampbuIb** [comment]
Turns out having AI building off turns on this behaviour. However, the option to turn AI building on seems to be missing from the menus in the latest BE...
