### ISSUE TITLE
RTS: Patrol Mode + Turret Detection Cone

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry-Suggestions#3644]
### Describe the content or mechanics you are proposing.

The gist of this is simple: Rusted Warfare's patrol mode, where you can select units and make them move to different points of the map in a loop, but in Mindustry.

About the other one: Basically, a `Turret` field that makes turrets have a limited detection cone, essentially making the turret's "vision" limited.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I know that logic already can do this in it's own way, but it's a bit confusing (and probably impossible for new players) + Erekir is a thing.

It also allows mapmakers to create about damn near infinite patrol points for units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
What's the use of the detection cone? Just curious.

**Comment by THEGAMER-10n** [comment]
> What's the use of the detection cone? Just curious.

Modified turrets.
