### ISSUE TITLE
Illuminators and Radar balancing

### ISSUE THREAD

**Issue by THEGAMER-10n** [Anuken/Mindustry-Suggestions#3647]
### Describe what you would like changed, and why.

1.) Increase light range for illuminators. They are useless in FoW maps and people prefer radar blocks instead. Increasing the range (and making the radar block tad a bit more expensive in terms of power consumption) will give use to this block.

2.) Make turrets and units have separate values for radarRange (for FoW) and range (the actual shooting range). If the unit/turret has a target within range but not on radarRange, it won’t shoot. The radarRange will affect FoW, but range will not. It forces players to actually use radars and illuminators to unlock the full range of the turret. No more ripple pushing.

3.) Make the radar block’s “vision expansion speed” slower. The vision is fine enough. This is also for balancing with illuminators.

4.) Make radar blocks available in all planets (or probably a version of one for each planet). It provides good utility. (Note that: Serpulo’s version of the radar block is technically the illuminator)

### Describe the changes you want to propose. Include possible alternatives.

# Illuminator Balancing Alternatives:

* Remove the illuminator altogether.
    - It’s range is too short to be utilized

* Create a Large illuminator block that has a significantly larger range.
    - The situation’s flex tape.

* Implement a version of the radar block in Serpulo that replaces the illuminator.

**Comment by itcannotbe** [comment]
The primary purpose of the illuminator is illumination, not making stuff appear through FOW.

**Comment by OnyxFinger** [comment]
I do believe that radars and illuminators can be merged, but only if the power consumtion is proportional to the hidden terrain that is being revealed (else illuminating your base would be too expensive).

**Comment by RealYeet** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2468

A suggestion for larger illuminators has been made here, I do believe however that the current illuminator and radar block should be merged in a similar Cassino to what OnyxFinger said.

**Comment by THEGAMER-10n** [comment]
> The primary purpose of the illuminator is illumination, not making stuff appear through FOW.

That’s actually a fair explanation.
