### ISSUE TITLE
Payload source selection order

### ISSUE THREAD

**Issue by a-letter** [Anuken/Mindustry-Suggestions#3648]
### Describe what you would like changed, and why.

This is just a minor thing, but can the dev move the units to the top of payload source selection? Not sure about anyone else but whenever I use payload source I always choose the units.

### Describe the changes you want to propose. Include possible alternatives.

E.

**Comment by itcannotbe** [comment]
Whenever I chose to use the payload source I choose blocks.

Maybe it's just preference. Also it just displays units/blocks it can output. It's not manually coded in.

**Comment by IVV-NCX** [comment]
Preference honestly. Also, forgot the format?

**Comment by IxGamerXL** [comment]
How about a setting that influences which group appears over the other? That way, everyone can choose which group they want to see first as they use it most. Win-win-win!
