### ISSUE TITLE
Game shouldn't kill itself when backgrounded

### ISSUE THREAD

**Issue by yesC48** [Anuken/Mindustry-Suggestions#3649]
### Describe the content or mechanics you are proposing.

Mindustry isn't supposed to kill itself within mere seconds (Core.app.exit()) especially in other android UIs. Make it impossible to do such a thing and it'll be a big relief, especially when dealing with large schematics or maps.
![Screenshot_2022-06-16-20-18-08-723_com discord](https://user-images.githubusercontent.com/74853156/174071843-a65cd9cd-a99f-44c3-aa36-b8f204d7bdc1.jpg)
I hope you can relate. Just kidding.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I really want to post a schematic I want others to see but can't because of the kind of phone I'm using, so "making Mindustry jump when backgrounded a relic of the past" the highest social credit boost ever.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Have you tried uploading the schematic as a file instead of clipboard text

**Comment by Weathercold** [comment]
Have you tried learning how to form coherent sentences

**Comment by itcannotbe** [comment]
This screams get a better phone with more RAM that can actually handle multi tasking without without requiring to kill background apps by just open to discord.

**Comment by itcannotbe** [comment]
Remember, it's not the **game** that handles memory management for your device.

**Comment by IVV-NCX** [comment]
So, when you background the app, the game crashes?

**Comment by IxGamerXL** [comment]
> So, when you background the app, the game crashes?

I had this issue before. Usually it happens on devices with lesser hardware, and some spit job of *"get a better phone with more RAM"* isn't cutting it @itcannotbe, as that quite obviously is more expensive than optimizing the game to not restart after going back in the minute after.

If the game heavily optimizes and reserves your point in time after suspending the game, that should fix it unless you are playing on a 90/80's nokia.

**Comment by itcannotbe** [comment]
It doesn't matter how well you manage the memery of your app, if the other app you are trying to open uses a lot of memory, memory management will effectively kill the other running processes.

And discord is one of those applications that use a lot.

**Comment by IxGamerXL** [comment]
> It doesn't matter how well you manage the memery of your app, if the other app you are trying to open uses a lot of memory, memory management will effectively kill the other running processes.
> 
> And discord is one of those applications that use a lot.

Doesn't happen to Minecraft PE, which has some kind of internal feature that enables session recovery when suspended for a long duration of time.

If Mindustry caches the session data, it might actually prevent the game from fully restarting, thus allowing us to continue the gameplay from where we left off without any data loss.

This will likely be difficult for low storage, which is why a setting for enabling session cache should be implemented in that case.
