### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ykzdyh** [Anuken/Mindustry-Suggestions#3652]
### Describe what you would like changed, and why.

在中国服务器上无法投票的bug建议修复一下，还有自动建造模式里自动替换传送带和钻头建议取消

### Describe the changes you want to propose. Include possible alternatives.

（

**Comment by IxGamerXL** [comment]
Translation:

> Bugs that can't vote on Chinese servers are suggested to be fixed, and automatic replacement of conveyor belts and drill bits in auto-build mode is proposed to be canceled

**Comment by OnyxFinger** [comment]
Google translate boo

~~Also, illuminaughty~~

**Comment by AMindustryPlayer** [comment]
Better translation:
> On Chinese servers, a bug that makes you can't vote is recommended to be fixed. By the way, in the auto-build mode, removing "automatically replace conveyors and drills" function is also recommended.

**Comment by Fabizocker456** [comment]
An american't person, I see
