### ISSUE TITLE
Suppression Turret/Unit

### ISSUE THREAD

**Issue by piemonk99** [Anuken/Mindustry-Suggestions#3655]
### Describe the content or mechanics you are proposing.

I think some sort of turret or unit/unit tree that is focused on suppression would be a good addition. For the turret, something similar to the Parallax, where it locks on to a single unit. The effects could either be movement-halting or suppress the victim's ability to fire or otherwise limit damage dealing. 

Vs Guardians or general T5 this would be very powerful, but some ways to balance it could be to make it take more turrets or drastically more power (ammo?) vs higher tier units.

The unit idea I have is a unit being able to stun or suppress a single turret with, similarly, a focused single-target beam. Again, larger turrets could take lots of beams to fully disable, and plastanium could prevent the effects (this may make it prudent to surround centerpiece turrets with an additional layer of plastainium).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The foreshadow is currently the only single-target specialized turret, and is only good at that because of it's range. Rather than having a DPS test vs waves, providing the player the option to delay the damage of key enemies could lead to some satisfying stratagies. I realize there are debuffs and utility provided by things like tsunamis, these tend to just slow down enemies, making them stack up and deal even more damage to your defenses. The bottom line is that the player essentially has to kill the enemies before the enemies cause problems, and this would provide the players the means to ensure that their defenses stay intact even if enemies are living longer.

Additionally, for AI bases, this could be a means of preventing a player from cheesing a base, similar to how the foreshadow forces players to fully commit to a rush vs being able to stand back and chip. I don't know all the cheese strategies, but suppression turrets would likely deter mindless early unit rushes.

The units might likely be hard to balance. On one hand, making them unable to suppress over platanium walls makes plastanium, which I personally use in all my defenses, even more powerful. If I am to assume that other people do or would do the same, the unit might be too weak. Suppressing turrets is very powerful, though, so there must be some risk or high cost involved. My suggestion would be to have the lower tier units, if they had this ability, to take multiple for large turrets and be close range, so they must take risk. If the unit were T4 or T5, then the range could be increased to a serviceable level.

However, the addition of such units would likely encourage a more tactical style of attacking where, rather than rushing enemies down with masses of units or commanding units and avoiding enemy defenses altogether, players could plan ahead and include suppression in their forces, paired with AoE barriers, and keep their smaller forces much safer.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Segment?

**Comment by piemonk99** [comment]
> Segment?

I'm thinking of having something a little more consistent to lock down a single target, whereas the segment can only target general incoming projectiles and gets overwhelmed by fast-firing enemies. I admit there is some redundancy there, though, and my support would mostly go toward the proposed units, which I don't believe have any equivalent.
