### ISSUE TITLE
Unit Generator

### ISSUE THREAD

**Issue by BigBrainz2047** [Anuken/Mindustry-Suggestions#3656]
### Describe the content or mechanics you are proposing.

When I say unit generator I mean sacrificing units for insane amounts of power!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think many people would like this a lot.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
A question: When would this be useful (or even remotely make sense?)

I'm a bit confused; Why would anyone ever want to convert a unit into (albeit) large amounts of power?

Don't forget that if the power given is large enough, I can see sand -> silicon -> flare -> power generators becoming a thing (like powercubes in v5).

**Comment by Fabizocker456** [comment]
*puts alpha into unit generator* problem, anuke?

**Comment by SMOLKEYS** [comment]
sorry but i have to

---

httphttps://cdn.discordapp.com/attachments/962161662079692810/988954404042444911/988727005623234571.webp

MMMMMM CULT

**Comment by BigBrainz2047** [comment]
Well, Units Are Robots Right? Then They Have Some Kind Of Power Source.

**Comment by BigBrainz2047** [comment]
They are robots, Robots use Power, Simple.
