### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by Cbao04** [Anuken/Mindustry-Suggestions#3657]
### Describe the content or mechanics you are proposing.

Be able to sync 2 or more device using accounts.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Be able to continue your campaign or whatever on any device.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Have you read the god-damn "do not suggest" list?

**Comment by itcannotbe** [comment]
To recap.

### A few things you shouldn't suggest
###### These have been proposed many times already, and I won't be adding them.
- Built-in cloud sync

**Comment by itcannotbe** [comment]
HOW COULD YOU HAVE POSSIBLY MISSED THAT.

I honestly have doubt that you actually read the [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) that you claim you did.

**Comment by Cbao04** [comment]
Ok then, I'll do it myself.

**Comment by Fabizocker456** [comment]
1. Mindustry doesn't have an account system, as there is no central server
2. "Syncing" requires two things:
  - a central server
  - a way to verify if the "sync" comes from a legitimate owner (aka account system)
3. Adding syncing also creates a lot of new problems
  - what if there's no internet connection?
  - what if the user beats a sector on one device and another one on another device?
  - what if you reconfigure launch pads and log in with another device?

This idea is bad. An aaa game could do something like this, but not an indie game like Mindustry.
