### ISSUE TITLE
Upgraded Draug

### ISSUE THREAD

**Issue by foxy85391** [Anuken/Mindustry-Suggestions#366]
Make it possible to upgrade draugs so they can mine better resources

This will make it easier to mine better resources lategame

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
1. That is over powered
2. This is not even relevant in 6.0, as draugs are not a part of it nor it's ai.

**Comment by Remint32** [comment]
>     2. This is not even relevant in 6.0, as draugs are not a part of it nor it's ai.

They just don't have AI yet
