### ISSUE TITLE
Bridge placement feature add also to Phase Conveyor

### ISSUE THREAD

**Issue by Hot-Sausage07** [Anuken/Mindustry-Suggestions#3662]
### Describe the content or mechanics you are proposing.

Bridge drag placement feature add to phase too
![image](https://user-images.githubusercontent.com/78838382/174630540-573c38b9-c331-42b6-9590-d88849828c69.png)
like this but also phase when 4 blocks apart

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Better and easy way to place conveyor pass through by bridge feature

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
Bravo! This is one of the only good ideas I have seen here for a while. Pls add, Anuke

**Comment by yesC48** [comment]
there must be a limitation depending on the player's current research so that only the players who have the phase conveyor will have the new bridge placement feature with phase conveyors

**Comment by Fabizocker456** [comment]
Of courseas that also goes for "normal" bridges
