### ISSUE TITLE
Storing energy and liquids like items

### ISSUE THREAD

**Issue by Whyhwhy** [Anuken/Mindustry-Suggestions#3663]
### Describe the content or mechanics you are proposing.

Batteries and liquid tanks would be a good addition to the game, with these liquid tanks you can now store and transport liquids like items, and with batteries you can store energy like items. There will be new six buildings, a Battery Factory (makes batteries), Charging Station, (charges batteries), Energy Extractor (extracts energy from batteries), Liquid Tanks Factory (makes liquid tanks), Liquid Packer (packs liquids to liquid tanks), and Liquid Extractor (extracts liquids from liquid tanks).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be useful in different situations, for example: You can't, or not willing to build generators, so you just using batteries. And with liquid tanks, for example: You can have slag to section with no scrap metal, or you can have cryo fluid at the start of the map.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ruichka** [comment]
> [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Are you sure about that?

**Comment by SMOLKEYS** [comment]
> Batteries and liquid tanks

https://tenor.com/view/mario-smg4-mario-laughing-gif-23706331

**Comment by Mythril382** [comment]
how to laugh for ages:
1. look at this suggestion

**Comment by TheAirBlow** [comment]
> * [x]  I am not familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

he probably wants to store power and liquids in the core

**Comment by Fabizocker456** [comment]
And he wants to use launch pads with them
