### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by TheAirBlow** [Anuken/Mindustry-Suggestions#3664]
### Describe what you would like changed, and why.

Mindustry should be rewritten in rust, because rust is a [multi-paradigm](https://en.wikipedia.org/wiki/Programming_paradigm), [general-purpose programming language](https://en.wikipedia.org/wiki/General-purpose_programming_language). Rust emphasizes [performance](https://en.wikipedia.org/wiki/Computer_performance), [type safety](https://en.wikipedia.org/wiki/Type_safety), and [concurrency](https://en.wikipedia.org/wiki/Concurrency_(computer_science)). Rust is the first language to enforce [memory safety](https://en.wikipedia.org/wiki/Memory_safety) — that is, that all [references](https://en.wikipedia.org/wiki/Reference_(computer_science)) point to valid memory — without requiring the use of a [garbage collector](https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)) or [reference counting](https://en.wikipedia.org/wiki/Reference_counting) like other memory-safe languages. To simultaneously enforce memory safety and prevent concurrent [data races](https://en.wikipedia.org/wiki/Race_condition), Rust's borrow checker tracks the [object lifetime](https://en.wikipedia.org/wiki/Object_lifetime) and [variable scope](https://en.wikipedia.org/wiki/Scope_(computer_science)) of all [references](https://en.wikipedia.org/wiki/Reference_(computer_science)) in a program during [compilation](https://en.wikipedia.org/wiki/Compilation_(computing)). Rust is popular for [systems programming](https://en.wikipedia.org/wiki/Systems_programming) and [low-level](https://en.wikipedia.org/wiki/Low-level_programming_language) [memory management](https://en.wikipedia.org/wiki/Memory_management), but also offers high-level features including [functional programming](https://en.wikipedia.org/wiki/Functional_programming) constructs.

### Describe the changes you want to propose. Include possible alternatives.

![image](https://user-images.githubusercontent.com/68467762/175065047-fdd6c301-89f1-4271-83cf-16bb3ec6078e.png)

**Comment by deltanedas** [comment]
marko zajc

**Comment by Anuken** [comment]
PRs accepted

**Comment by IVV-NCX** [comment]
Honestly, Rust is pretty much universally better in terms of performance...

But... it's another very, very long project to rewrite a whole game.

**Comment by TheAirBlow** [comment]
> PRs accepted

![ok](https://media.discordapp.net/attachments/815977607413497866/989065158691262464/IMG_9245.gif)

**Comment by markozajc** [comment]
wrong,

**Comment by markozajc** [comment]
https://docs.rs/jni/latest/jni/

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/175165599-5420ff29-ed64-494e-9f2f-5e9546d7c7ef.png)

completely unacceptable

**Comment by Arkanic** [comment]
https://github.com/mTvare6/hello-world.rs

this is an excellent project if you want reference on how 2 rust!!!!

pls use rust :rocket:

**Comment by IxGamerXL** [comment]
I might be asking a stupid question or something, but **does Rust have any Javascript/Java support, or will there be support coming from other file types?** If there is no support for Javascript or Java, lots, and lots, AND LOTS of mods will be hardlocked as unsupported.

If there is legacy support for older mods and in general, that might be fine then.

**Comment by Arkanic** [comment]
yesyes its already confirmed mindustry will be 100% rust in the next 6 hours

now go back to your slave camp and transpile some code

**Comment by markozajc** [comment]
done
https://github.com/Anuken/Mindustry/pull/7062

**Comment by Arkanic** [comment]
@IxGamerXL we already finished
too late

**Comment by markozajc** [comment]
@IxGamerXL ok but have you heard about Fearless Concurrency? Rust🚀 programs are Blazing Fast and Memory-Safe, so you can take your mind off dealing with pesky bugs

**Comment by Arkanic** [comment]
> If there is no support, this has got to be the biggest middle finger in the history of Mindustry Modding.

modding is just a containment area for all of the preteens who don't know how to socially interact yet
sauce: modding-general right now
![image](https://user-images.githubusercontent.com/50847107/175169926-c45efb8c-4f74-43fb-a389-038b82cbff01.png)

**Comment by markozajc** [comment]
if java is so good why do we need java the script

**Comment by code-explorer786** [comment]
> I'm not saying I disagree or anything, but I am saying that javascript and java support is heavily required if you don't want thousands of mod developers (and mod users) to get furious. Conversion to Rust in terms of everything including external sources is like kicking out most of the people who make mods and barely leaving any to make mods, and they might not even be good at making mods or they might've even stopped making mods altogether.
> 
> If there is no support, this has got to be the biggest middle finger in the history of Mindustry Modding.

sourcemodding exists

**Comment by SMOLKEYS** [comment]
> ![image](https://user-images.githubusercontent.com/10100000/175165599-5420ff29-ed64-494e-9f2f-5e9546d7c7ef.png)
> 
> completely unacceptable 

this is why i love this fucking community ![topogus](https://tenor.com/view/mario-smg4-mario-laughing-gif-23706331)

**Comment by TheAirBlow** [comment]
> > https://github.com/mTvare6/hello-world.rs
> > this is an excellent project if you want reference on how 2 rust!!!!
> > pls use rust rocket
> 
> that has >300 lines for just saying hello what in the name of trigonometry and algebra-
> 
> > yesyes its already confirmed mindustry will be 100% rust in the next 6 hours
> > now go back to your slave camp and transpile some code
> 
> I'm not saying I disagree or anything, but I am saying that javascript and java support is heavily required if you don't want thousands of mod developers (and mod users) to get furious. Conversion to Rust in terms of everything including external sources is like kicking out most of the people who make mods and barely leaving any to make mods, and they might not even be good at making mods or they might've even stopped making mods altogether.
> 
> If there is no support, this has got to be the biggest middle finger in the history of Mindustry Modding.

Why you're taking this too seriously lol

**Comment by SMOLKEYS** [comment]
> > https://github.com/mTvare6/hello-world.rs
> > 
> > this is an excellent project if you want reference on how 2 rust!!!!
> > 
> > pls use rust rocket
> 
> that has >300 lines for just saying hello what in the name of trigonometry and algebra-
> 
> > yesyes its already confirmed mindustry will be 100% rust in the next 6 hours
> > 
> > now go back to your slave camp and transpile some code
> 
> I'm not saying I disagree or anything, but I am saying that javascript and java support is heavily required if you don't want thousands of mod developers (and mod users) to get furious. Conversion to Rust in terms of everything including external sources is like kicking out most of the people who make mods and barely leaving any to make mods, and they might not even be good at making mods or they might've even stopped making mods altogether.
> 
> If there is no support, this has got to be the biggest middle finger in the history of Mindustry Modding.

stop taking this seriously you fu-

**Comment by itcannotbe** [comment]
> > https://github.com/mTvare6/hello-world.rs
> > this is an excellent project if you want reference on how 2 rust!!!!
> > pls use rust rocket
> 
> that has >300 lines for just saying hello what in the name of trigonometry and algebra-
> 
> > yesyes its already confirmed mindustry will be 100% rust in the next 6 hours
> > now go back to your slave camp and transpile some code
> 
> I'm not saying I disagree or anything, but I am saying that javascript and java support is heavily required if you don't want thousands of mod developers (and mod users) to get furious. Conversion to Rust in terms of everything including external sources is like kicking out most of the people who make mods and barely leaving any to make mods, and they might not even be good at making mods or they might've even stopped making mods altogether.
> 
> If there is no support, this has got to be the biggest middle finger in the history of Mindustry Modding.

![Why so serious?](https://c.tenor.com/u1QV68D5A3wAAAAM/why-so-serious-joker.gif)

**Comment by code-explorer786** [comment]
> stop taking this seriously you fu-

wait this reminded me that i'm learning Rust

**Comment by markozajc** [comment]
ok.

**Comment by TheAirBlow** [comment]
♂300 bucks♂ and I'll open this issue again

**Comment by markozajc** [comment]
he switched to the dark side

**Comment by TheAirBlow** [comment]
@markozajc I am a C# fanboy

**Comment by TheAirBlow** [comment]
@markozajc guys issue aliv

**Comment by TheAirBlow** [comment]
@Anuken do it NOW

**Comment by SecondNewtonLaw** [comment]
> he switched to the dark side

Blazingly fast code is hard to write, he wanted a compensation, remember, we are off for like half year onto the Mindustry (Ja🤮)-> into Rust 🚀🚀🚀🚀

**Comment by BlueWolf3682** [comment]
> > If there is no support, this has got to be the biggest middle finger in the history of Mindustry Modding.
> 
> modding is just a containment area for all of the preteens who don't know how to socially interact yet sauce: modding-general ![image](https://user-images.githubusercontent.com/50847107/175170135-f4b92c43-8b26-4ea3-85ef-e5428b0bba6c.png)

many of us are intelligent and older - glenn is probably the youngest one of us while i am 18.
your "sauce" here is about a community built over years of people you cant even think to understand, leading you to assume we are just preteens. just to rub *that* in your face, ill mention that i have two (biologically) female frens in real life and several online, while you have none and no bitches.

on the topic of how much it would be a middle finger to modding, it would indeed be - mods are build with JSON, rhino JS, or JVM compatible languages.
only JSON would be remotely easy to support through a Rust port, the other ones would simply stop working nicely. good luck getting a 100% feature perfect Rust port while still having to support JS and Java mods.

**Comment by SecondNewtonLaw** [comment]
we will just implement mods with Json. 100% possible.

**Comment by BlueWolf3682** [comment]
JSON modding is... limited. although you can create fun stuff with it, it can be hard to work with.
its better to maintain a better system as well as JSON for ease of simple mods and for advanced modding.

**Comment by SecondNewtonLaw** [comment]
at this point it seems this is actually *not* a joke anymore and a Mindustry (Rust) wants to exist

**Comment by Arkanic** [comment]
@BlueWolf3682 
![image](https://user-images.githubusercontent.com/50847107/200223129-f8c289d9-280d-4139-93b6-4defd2b02acd.png)

will add new pr!! remove angry npc and add more rust crate!

**Comment by 00001H** [comment]
-1
Rewrite it in Mindustry Logic instead

**Comment by markozajc** [comment]
rus is gone

**Comment by Arkanic** [comment]
government AI shill bot cia honeypot killing the truth deep state ending future ideas rust too dangerous for the authorities fbi investigation illuminati

**Comment by markozajc** [comment]
your 8chan moderation application has been accepted, welcome to the team

**Comment by SecondNewtonLaw** [comment]
rust 🚀 rust 🚀rust 🚀 rust 🚀rust 🚀 rust 🚀rust 🚀 rust 🚀rust 🚀 rust 🚀rust 🚀 rust 🚀rust 🚀 rust 🚀rust 🚀 rust 🚀
