### ISSUE TITLE
New lookup, but reversed

### ISSUE THREAD

**Issue by Def-Try** [Anuken/Mindustry-Suggestions#3665]
### Describe the content or mechanics you are proposing.

we have command to get @content by ID, but why not to create command to get ID by @content.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

idk, it can be used for dupeable logic storages based on sorters, or for remote conveyor item flow control, or something like this

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by code-explorer786** [comment]
Good suggestion! Even though you can use funny methods, this'll be a nice feature to add.
