### ISSUE TITLE
Reuse Large Launch Pads

### ISSUE THREAD

**Issue by yesC48** [Anuken/Mindustry-Suggestions#3668]
### Describe the content or mechanics you are proposing.

Since Large Launch Pads are a relic of the past, re-add them with a new feature:
- They launch more resources.
- They survive re-entry, aka they can be used for interplanetary resource transport.
- They require more power, obviously.

Additionally, add an atmosphere boolean to determine if the planet can receive resources from normal launch pads. Large launch pads ignore this boolean.
There should also be a limitation, for example Erekir cannot receive resources only available for Serpulo and vice versa.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since there's limitations for the new launch pad, they can be used to launch resources on the new planets, for example, Tantros and the 4 asteroid sectors. They can also be used to transport resources to other modded planets, if the player so chooses.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
TBH, launch pads are already too broken.
