### ISSUE TITLE
More Realistic Shadows and Graphics

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#367]
1 - More Realistic Shadows

To make the game more realistic shadows of all types of blocks should be moved a bit to the southwest direction, making it look like sun is coming from the northeast direction.

2 - More Realistic Graphics

If you implement the 1st suggestion, we may also should retexture all types of blocks to make it look like sun is coming from northeast direction. To do that, the part that is closer to the northeast direction should be brighter than the part that is closer to the southwest direction. Below there is a retextured alloy smelter showing how it should be : 

![alloy-smelter](https://user-images.githubusercontent.com/68538765/89108838-8441f080-d444-11ea-93f9-27a8f5106b2f.png)

With that some environment blocks should combine their shadows and most importantly, their sprite. Just like solar panels in the #pull-requests channel in discord, whereas when they are placed next to each other they combine their sprites. Same thing should apply on environment blocks, imagine a big rock (not square) made from 1x1 environment blocks, blocks closer to the southwest direction should have shadows while the blocks that are closer to the northeast direction shouldn't, they also should combine their sprite somehow to make a big rock that isnt a square look realistic with correct shadows and combined sprites. Below there is an example of how it should work (poorly edited) : 

![20200801_215728](https://user-images.githubusercontent.com/68538765/89108551-244a4a80-d442-11ea-8404-6178a7f5a48c.jpg)

(Text color is matching with pen color)

If you can't do this. at least make the mixed sprites (hard), retexturing (mediocre) and slide the shadows to the southwest direction a bit (idk how hard this is but i guess its easy).

By the way, i know it is a lot of work to do but it's a big QOL change but you're not forced to to this, but if you work hard it would be great to see more realistic mindustry, maybe if needed you can hire some people to help you. And if you're interested i have more things to tell about retexturing, shadows and mixed sprites.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> 1 - More Realistic Shadows

This is difficult to implement with the current shadow system, and even if it weren't, the result would look terrible with soft shadows.

> 2 - More Realistic Graphics
> we may also should retexture all types of blocks to make it look like sun is coming from northeast direction.

All the blocks (except) turrets already have shading representing light coming from the northeast. I don't understand how your sprite is supposed to look more realistic - it has the same exact shading patterns as the existing allow smelter, except at higher saturation and without the inner cavity slopes.

> Just like solar panels in the #pull-requests channel in discord, whereas when they are placed next to each other they combine their sprites

Those were removed, because they looked like a snakey mess. I don't see other blocks looking much better.

> Same thing should apply on environment blocks

I've tested out merging blocks back before Classic, and the result looked flat and uninteresting. I won't be implementing it.

**Comment by Zenith-LY** [comment]
> All the blocks (except) turrets already have shading representing light coming from the northeast. I don't understand how your sprite is supposed to look more realistic - it has the same exact shading patterns as the existing allow smelter, except at higher saturation and without the inner cavity slopes.

Making them a bit darker would represent shadows better but i know its a lot of work but as said you can hire people (most probably the current contributors)
