### ISSUE TITLE
Multiplayer Research Sync option

### ISSUE THREAD

**Issue by MaxdamageAF** [Anuken/Mindustry-Suggestions#3670]
### Describe the content or mechanics you are proposing.

Add an option to automatically sync your research with the host when playing Campaign mode in multiplayer
Example of now: I join my friend and have all things research, being able to break the tech tree early
Example of idea: my friend has the choice when hosting for the first time in campaign mode to turn on "Research Sync" with a little description "Players joining with only be able to create items you the host have researched, this can be changed later in the Options Menu"
(as discribed, you can change this later in options)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow players to have greater control on how they wish to tackle hosting the campaign via steam, weither if its freestyle or synced for all players with the host.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
Hosting campaign is still very buggy, this is only a "tip of the iceberg"-thing.
