### ISSUE TITLE
Arkycite in Waves/Tsunamis

### ISSUE THREAD

**Issue by Aiden910** [Anuken/Mindustry-Suggestions#3671]
### Describe the content or mechanics you are proposing.

Add in the use of Arkycite being usable by Waves and Tsunamis as ammunition. I am unsure if this is planned already or not, I did not see it in the Trello.

Arkycite in a Wave could have 4 damage, 0.55 Knockback, 0.75 Fire rate, and inflict Corroded.
Arkycite in a Tsunami could have 4.75 Damage, 1.3 Knockback, 0.75 Fire rate, and inflict Corroded.
Corroded would be an effect that does 4 damage/second and 80% HP.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe this would add some interesting scenarios in custom games/maps that people make, that is all.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by josucoimbra** [comment]
Dont have arkycite on serpulo bro
