### ISSUE TITLE
rebalanced meltdown

### ISSUE THREAD

**Issue by Corsh** [Anuken/Mindustry-Suggestions#3672]
### Describe what you would like changed, and why.

just rebalanced it cuz it's too expensive and people don't like using it. also weaker than some combinations such as cyclone(blast powders) + tsunami/ wave (cryo fluid) 

### Describe the changes you want to propose. Include possible alternatives.

reduce the cost of both building and research. make it better than scorch

**Comment by itcannotbe** [comment]
Meltdown is weak because of how it actually deals damage.
