### ISSUE TITLE
hey a-nuke-n make wave caller less rng

### ISSUE THREAD

**Issue by Corsh** [Anuken/Mindustry-Suggestions#3674]
### Describe what you would like changed, and why.

some waves are just too easy. some are just too hard cuz of randomness

### Describe the changes you want to propose. Include possible alternatives.

thread: low
-base max unit spawn: 1
wave 1-5: 100% t1
wave 5-10: 90%t1 10%t2
wave 10-20: 80%t1 20%t2
wave 20-30: 60%t1 40%t2  
wave 30+: 30%t1  70%t2 
thread: medium
-base max unit spawn: 3
wave 1-5: 100% t1
wave 5-10: 80%t1 20%t2
wave 10-20: 70%t1 30%t2
wave 20-30: 35%t1 65%t2  
wave 30+: 20%t1  80%t2 
thread: high
-base max unit spawn: 6
thread: extreme:
-base max unit spawn: 9
thread: eradication:
wave 1-5: 100% t1
wave 5-10: 60%t1 40%t2
wave 10-20: 30%t1 60%t2  10%t3 
wave 20-30: 10%t1 60%t2  30%t3 
wave 3+: 40%t2  60%t3 
-base max unit spawn: 12
+5 max unit every 5-10 wave
wave 1-5: 100% t1
wave 5-10: 60%t1 40%t2
wave 10-20: 30%t1 60%t2  10%t3 
wave 20-30: 10%t1 60%t2  30%t3 
wave 30+: 30%t2 50%t3 20%t4
im too lazy too think more.

**Comment by itcannotbe** [comment]
That would make the game extremely bland.

**Comment by Corsh** [comment]
maybe this should be added as alternative choice
