### ISSUE TITLE
Very cute defense tower idea 

### ISSUE THREAD

**Issue by WhoIsWallio** [Anuken/Mindustry-Suggestions#3675]
### Describe the content or mechanics you are proposing.

A Defense Tower which shoots a focused laser which bounces from target to target while also loosing damage after each bounce. The bouncing damage drop off could be used with coolant to reduce the damage drop off after each bounce. This tower would require power as its main ammo source however without coolant the tower would loose a lot of its potential.

These are some of the stats I think would fit this tower;

6000 Health
200 - Damage to the first enemy hit
40% - Damage drop after each bounce 
 - Decreased to 35% with water 
 - Decreased to 25% with Cryofluid
5,000-10,000 Power use each shot
0.25 Attacks per second (4s)
20 Liquid units for cooling
5 Bounces between enemies each
 - Increased to 6 with water
 - Increased to 7 with Cryofluid
Optional - If there are any allied buildings there is a 2-10% chance that a shot may bounce on it inflicting the damage to the structure in which case the shot will end after that bounce.
Optional - If the above optional behaviour is implemented then the shot that is absorbed into the structure will make the structure inoperable for X amount of time and be unable to healed by any means for X amount of time.
Optional - This tower will only see enemies in direct line of sight, if the tower shoots at an enemy that, the shot will continue until it hits a structure which will do the same damage to the structure or if it flies out of the map which then it will evaporate into thin air.
Optional -  Cannot be healed by Mend Projector or Mender however it can be healed by other means.
Optional -  Using Overdrive Projector or Overdrive Dome will significantly increase power usage;
 - Overdrive Projector - +50% Attack Speed and fluid usage,, +100% Power usage
 - Overdrive Dome - +150% Attack Speed and fluid usage, +300% Power usage
 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This tower is unique in a way that the shots that are produced by it actually have a different effect/use. The Optional features of the tower make it less viable to be Spammed and abused due to being able to destroy allied structures if handled wrongly.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
>  a 2-10% chance that a shot may bounce on it inflicting the damage to the structure

First thing that's coming to mind right now is griefing; Although to be honest thorium reactors would probably still be much more effective.

**Comment by WhoIsWallio** [comment]
Could be true but any sort of the bouncing into structures would only apply to allied not enemy structures, that is of course if the shot doesn't reach and or target the enemy structure, however if the shot would hit an enemy structure the shot would end there and not bounce between like if it hits the allied structure.

**Comment by OnyxFinger** [comment]
That is a cool idea, however I don't think there really is a reason for the optionals (they more like a pain than anything) ? Anyway, the problem I have with your suggestion (just like with most) is : What would it's purpose ? As in how would it make the game more complete ? What spot does it occupy that no other turret does ?
What you describe sounds like a late-game AOE turret, which is just cyclone or swarmer. It's interesting how they both fall in the same "spot" but one is just superior to the other, which is exactly what I called out for you. Notice how there were multiple suggestions to change swarmers/cyclones in order to make them different ? Same thing would happen with this idea...
