### ISSUE TITLE
sugerencia 

### ISSUE THREAD

**Issue by squert13** [Anuken/Mindustry-Suggestions#3676]
### Describe what you would like changed, and why.

solo sería traducir el tema de la lógica,
para comprender mejor.

### Describe the changes you want to propose. Include possible alternatives.

traducir al Español todo el tema de la lógica? me ayudaría mucho a entenderla mejor y a otros jugadores como a mi, muchas gracias por  leer y espero tomen mi sugerencia me encanta su juego <3

**Comment by IVV-NCX** [comment]
English please.

> would only be to translate the subject of logic,
to understand better.

> I hope you can translate into Spanish the whole theme of the logic? it would help me a lot to understand it better and other players like me, thank you very much for reading and I hope you take my suggestion I love your game <3
