### ISSUE TITLE
need more language support

### ISSUE THREAD

**Issue by Corsh** [Anuken/Mindustry-Suggestions#3679]
### Describe what you would like changed, and why.

I am a python programmer but I really want to become a modder. can you add more language support?

### Describe the changes you want to propose. Include possible alternatives.

more language support = easier access to people who want to become modders

**Comment by IVV-NCX** [comment]
Sir, programming languages don’t work like that. Either rebuild Mindustry in PY, or learn Java.

Computer languages are one of a kind. Python might be good at AI, while C doesn’t need to compile, etc. Each one has its own purpose and design, like you can’t expect to just put a Chinese person into America and have them understand English, politics, and law perfectly, the only difference being that code can’t learn and adapt, you just have to make a clone that does the same job.

**Comment by TheRealIvyX** [comment]
> I am a python programmer but I really want to become a modder
then learn java

**Comment by code-explorer786** [comment]
There's a plugin for that, I guess?
https://github.com/SachaTending/PyForMindustry

Also Jython exists.
