### ISSUE TITLE
Meteor shower event

### ISSUE THREAD

**Issue by Willatar** [Anuken/Mindustry-Suggestions#3680]
### Describe the content or mechanics you are proposing.

I think a meteor shower would be cool. Maybe it can break blocks if a meteor hits something? Perhaps it only happens in certain sectors or on asteroids. It may even be able to strike the player out of the sky if they aren't careful.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A meteor shower could create a need for constant upkeep, instead of for example building your silicon factory and just leaving it there to keep on making silicon forever, you now have to make sure that it wasn't damaged when a meteor shower occurred. This also makes for a good reason to have polies on an old materials sector.

s.githubusercontent.com/108216646/175808216-300a295a-6433-4b61-9f79-a5858e0e3b86.mp4

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by virat2010** [comment]
scrap meteors are on the trello board
