### ISSUE TITLE
Company but its player vs player with global map

### ISSUE THREAD

**Issue by Hper120** [Anuken/Mindustry-Suggestions#3683]
### Describe the content or mechanics you are proposing.

Game mode similar to company but its player vs player with global map, without online mode, steam friend invite request (I really dont know how it will works on phone users)
1. Game will be played solo (1 player per a team) because its not the only one map, it will be a whole planet with random spawned core players. Players count depends on current ingame player colors (it should not overload the game)
2. Players will expand at this planet with droping their new core like in campaign.
3. Players cant drop the core when other team already in (droping core have delay and script that checking is the both players trying to do this)
4. Players can do the atack to each other bases with this good idea https://trello.com/c/bqKwLdqU also need to add the player access for moving it (only on the current mode that im suggesting) at enemy launching zone, that will look like a line, not a circle.
5. That ship can be builded at additional unit factory, that is big like T5.
6. And additional factory for the wave dropship.
7. Players can only atack each other when they have an a claimed sector near their enemy trough 1 sector or closer.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. It will grow the activity.
2. It will show new game mechanics.
3. New and long time gameplay.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This goes to the pile of suggestions that basically suggest to host the whole planet.

**Comment by itcannotbe** [comment]
The current pile:

#6356 
#3419
#3325
#2364
#2319
#2072
#2066
#2053
#1146
#1111
#1046
#916
#459
