### ISSUE TITLE
Rts payloading

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3685]
### Describe the content or mechanics you are proposing.

add a button above the Rts ui, that is switchable to 3 mode: Load, Unload and none

When in loading mode, select commanding units will mark them as "payload target", the currently controlled unit (that can payload) will come and pick up the units marked.

When in unloading mode, controlled unit will drop the payload at the selected place.

"None" mode will disable the payload system.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It could be useful for payload air units, such as Quell and Disrupt to load/unload a mass amount of units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genNAowl** [comment]
> a button above the Rts ui

Probably only clickable/visible when one is controlling a unit with the ability to payload, right?
