### ISSUE TITLE
Copper & Lead walls

### ISSUE THREAD

**Issue by Cbao04** [Anuken/Mindustry-Suggestions#3686]
### Describe the content or mechanics you are proposing.

Copper & Lead walls is similar to Plastanium walls but can be connected to a battery or whatever, can only take arc-like attacks and lancer-like attacks.

Warning: not original idea

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Dunno

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RouterChainsSuckk** [comment]
No effort on why this should be added so I won’t put effort in explaining why you should close this and make it urself with a mod
