### ISSUE TITLE
Idea to balance new missile turret

### ISSUE THREAD

**Issue by nak-attak** [Anuken/Mindustry-Suggestions#3687]
This feature is already implemented.

**Comment by AtobaAzul** [comment]
This already appears to be the case, at the end of the video, a turret tries to shoot at the missile.
![image](https://user-images.githubusercontent.com/94794129/176554216-2599443f-8838-4856-b830-f9df155d83b1.png)

**Comment by EclipseTheOldOne** [comment]
isn't they already targetable?
