### ISSUE TITLE
Additional turrets that uses Lead as ammo

### ISSUE THREAD

**Issue by Nigen-Wolf** [Anuken/Mindustry-Suggestions#3688]
### Describe the content or mechanics you are proposing.

As what I have noticed, the only turret that uses Lead as ammo is the **Scatter turret**. It would be cool if additional turrets or making some existed turrets use 
Lead as ammo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can be helpful and useful especially when a sector has an abundance of Lead and scarce in other resources.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
Serpulo is already full of turret option

**Comment by BlueWolf3682** [comment]
\*sad phase fabric noises*
