### ISSUE TITLE
Add measurements to source blocks & schematics

### ISSUE THREAD

**Issue by ChristianKurz** [Anuken/Mindustry-Suggestions#369]
Source blocks could be used to measure the throughput of items. The measured rate would be the average number of items produced per second by the source in a certain time period (e.g. 30s).

This would allow easier judging of schematic efficiencies.

The rate information for each source could be displayed in the schematics menu as well. The rate could either be the last rate reported when saving the schematic or the value after a certain stabilization period, calculated by simulation. 

It might also be a good idea to exclude source blocks when showing area and block count in the schematics menu.  

-[x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

-[x] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
- [PR #1305](https://github.com/Anuken/Mindustry/pull/1305) is similar but impacts performance

-[x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This is unnecessary; v6 already measures throughput on all hovered blocks.
