### ISSUE TITLE
Deconstructor for SERPULO 

### ISSUE THREAD

**Issue by Enderman664** [Anuken/Mindustry-Suggestions#3693]
### Describe the content or mechanics you are proposing.

serpulo has no deconstructors, it is very annoying to have attack units in sectors that have already been captured, with the deconstructors we can turn the units that are already useless into valuable resources

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Deconstructing units is much better than having them lying around in a corner. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Denied. No Serpulo equivalent blocks of erekir blocks.

**Comment by Enderman664** [comment]
> Denegado. No hay bloques equivalentes de Serpulo de bloques de carga útil de erekir.

It is mainly for units
