### ISSUE TITLE
Controller Support on iOS

### ISSUE THREAD

**Issue by applejoe04** [Anuken/Mindustry-Suggestions#3694]
### Describe the content or mechanics you are proposing.

Pretty please! 🙏🏼🥹🥲

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

But I thought the Steam version of the game supported controller inputs… ok then 🥹🥲😢

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If you actually check the change logs, said support said actually removed some time ago.

**Comment by IVV-NCX** [comment]
I mean, you could if you wanted, but the game will be pretty difficult with controller…
