### ISSUE TITLE
About translating mods

### ISSUE THREAD

**Issue by Luka108** [Anuken/Mindustry-Suggestions#37]
**I don't know if this is the right place for this request, but I'll try.**

**I want to know if there's a way to translating a mod repository, similar to the way translations are provided for the "main" game.**

**I think an easy way is to create a mod called "the_name_of_the_mod_ita" and copying the mod with all names and description translated, but I don't know if there's another way.**

*Maybe you've already understood it, I'm talking about the Italian translation, that is already provided for the "normal" game.*

**Thanks for your time and your game,
Luca**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I watched in the TRANSLATING GitHub page and there's nothing about this

**Comment by DeltaNedas** [comment]
yes
make a pull request for the mods repository
bundle_it.properties for italian same as mindustry itself

**Comment by Luka108** [comment]
Yes, but for the mindustry game there's the [English translation bundle](https://raw.githubusercontent.com/Anuken/Mindustry/master/core/assets/bundles/bundle.properties) and you can edit that, but it there isn't for the mods, you should create it by yourself, but it's a lot of work and it could be uncomplete.

**Comment by Anuken** [comment]
The example mod has bundles with alternate translations, which were submitted by other people, exactly how "translations are provided for the "main" game".

**Comment by ethan904** [comment]
is there one for v6
