### ISSUE TITLE
Turrets should only hit what they can target

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#370]
Turrets's projectiles/bullets shouldn't hit enemies they cant target

Lancer and Scatter turrets are going to be example.

Currently, turrets can hit enemies they cant target with their bullets, for example, a lancer turret cant target air units but if an air unit gets in its laser's way, it gets hit, which makes Lancer able to hit air units. Another example is Scatter (vice-versa example of Lancer), it can't target ground but if its projectile/bullet hits a ground unit/block, it gets hit, which makes Scatter able to hit ground. This may not be a huge problem but in 6.0 since we can control turrets it will be like any turret we control can hit both air units and ground regardless of their stats. This will be a huge problem because a person can control a lancer turret to shoot a specified direction and in that direction there may be air units since they can use it to attack air units. Or an another person can use scatter to attack ground because of the same reasons. This will be an even bigger problem if we can control multiple turrets (controlling multiple turrets should be a thing but only if this is fixed) like units.

**Comment by Anuken** [comment]
v6 already has this implemented.
