### ISSUE TITLE
Unit-based missile denotate on everything

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry-Suggestions#3700]
### Describe what you would like changed, and why.

Missile such as Quell missile, scathe missile, anthicus missile denotate on everything, even duct.

### Describe the changes you want to propose. Include possible alternatives.

alternatives: 
- make them explode on target.
- stop them from denotate on duct/transport block,...

**Comment by Anuken** [comment]
You're running an older version, I fixed this yesterday, before this issue was made (https://github.com/Anuken/Mindustry/commit/5b1d1a2ce4b1d6d3c32d71985f490ffdbd5baf06).
