### ISSUE TITLE
The behavior of enemies.

### ISSUE THREAD

**Issue by Dark-Umbrella** [Anuken/Mindustry-Suggestions#3701]
### Describe what you would like changed, and why.

![IMG_20220705_133130](https://user-images.githubusercontent.com/105446446/177309419-fcd0e767-346d-4bb0-81c0-3c1187c1af7e.jpg)
The game becomes quite simple, from the rather stupid behavior of the enemies, namely, because of their predilection to attack the least fortified places. There is always a fork next to the spawn of enemies. If one of the passages of this very fork is built up even with copper walls in 5-10 layers, and make it smaller on the second passage, then all the enemies will go there. I've been using this technique for a long time.

### Describe the changes you want to propose. Include possible alternatives.

I think the game would become much more difficult if two groups of enemies would go on different routes. 
or. 
If waves of enemies had not constant trajectories of movement.

**Comment by itcannotbe** [comment]
If you want more of a challenge, try battling with actual people.
