### ISSUE TITLE
Constriction sound

### ISSUE THREAD

**Issue by Crux5802** [Anuken/Mindustry-Suggestions#3703]
### Describe what you would like changed, and why.

simply being able to disable the new construction sound, it's not that I didn't like it but when it's in multiplayer with everyone building this sound starts to annoy me

### Describe the changes you want to propose. Include possible alternatives.

maybe a slider to choose the volume of this new sound

**Comment by Anuken** [comment]
If most people are annoyed by this sound, I can just remove it altogether.

**Comment by TheElan** [comment]
Any updates on this? Whenever I get low on the resource I am building with - it is being looped and gets quite annoying fast. Also not the most pleasant sound. (might be persona)

Toggle to switch it on/off would be nice.

**Comment by jp-x-g** [comment]
I think the problem could be fixed by just making the sound a little longer -- right now, it's only a couple seconds, and hearing it loop over and over and over and over gets irritating. If it weren't so repetitive, it would be better to listen to.
