### ISSUE TITLE
make the force projectors (and the shield on the T4 mech i forgot what its called) behave like plast walls

### ISSUE THREAD

**Issue by Cmonster820** [Anuken/Mindustry-Suggestions#3706]
### Describe what you would like changed, and why.

I would like the fields projected by force projectors behave like plastanium walls when hit by a laser, because it seems like it would make sense to have an energy field be able to disperse energy weaponry (maybe even add some charge to the power grid that could overload and break the projector, but this parenthetic note is for the other feature request catagory)

### Describe the changes you want to propose. Include possible alternatives.

I can't think of any alternatives, this request is so small that the first half of the question is answered in the previous answer

**Comment by 50275** [comment]
The Oct is a tier 5 unit. Anyway, plastanium walls are a big enough counter already.
