### ISSUE TITLE
 Schematic Visualization

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry-Suggestions#3707]
### Describe the content or mechanics you are proposing.

Have a visualization of the schematic file when importing a schematic file, like in the schematic menu

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be a quality of life choice, as some people don't rename their schematic files when uploading them and sending them via discord or other ways.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 50275** [comment]
Doesn't Mindustry already do this when you import a schematic using the schematic menu? If you drag it directly into the game data folder then you can just open the game and see it for yourself. You're not getting a picture without opening Mindustry though.
