### ISSUE TITLE
Find space command for processors

### ISSUE THREAD

**Issue by 24110802** [Anuken/Mindustry-Suggestions#3709]
### Describe the content or mechanics you are proposing.

A command under the unit control section that tells the unit to look for any space with configurable width, height and floor tile. The command would then return the x and y coordinates of the lower left corner of the first found area (no sorting needed?).

Command appearance example: [getspace] x [0] y [0] floor [@dark-sand] outX [outx] outY [outy] found [found]
Mlog text example: ucontrol getspace 0 0 @dark-sand outx outy found

The search function should not be more costly than the path finding function.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Building with units would be much easier

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
> path finding function

the?

**Comment by 24110802** [comment]
one that makes units go around terrain instead of going straight to the selected location when you use rts

**Comment by Fabizocker456** [comment]
This is ridiculously expensive, basically a 2d "malloc" with additional floor tile.
