### ISSUE TITLE
Better saving system

### ISSUE THREAD

**Issue by Terra5** [Anuken/Mindustry-Suggestions#3710]
### Describe the content or mechanics you are proposing.

Saving system that will save sectors you passed, every other data etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You can save and load saves so it's much more game friendly to move between versions and not corrupt versions. It will really help out, since there's no need to open appdata folder and replace game files.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by mottom1** [comment]
If this does end up happening, I hope it also comes with the feature to have multiple saves, just in case you are wanting to do campaign with a friend. Because right now you have to export data, then re-import the data from the play session with you and your friends.
