### ISSUE TITLE
Mega needs a buff

### ISSUE THREAD

**Issue by DaVeBOI** [Anuken/Mindustry-Suggestions#3712]
### Describe what you would like changed, and why.

I believe that the mega needs to do more than what it already does because you can code a poly to do the same work as the mega using the current logic system in the game

### Describe the changes you want to propose. Include possible alternatives.

I believe that making the mega able to heal units could make it viable in pvp and pve because currently you can save resources and time just by using logic processors and making poly target damaged buildings and heal them

**Comment by BlueWolf3682** [comment]
Balancing does not focus around logic.
