### ISSUE TITLE
New Unit

### ISSUE THREAD

**Issue by complay11** [Anuken/Mindustry-Suggestions#3713]
### Describe the content or mechanics you are proposing.

New flying purple unit with built in processor, the higher tier the better the processor. For example: A T1 Flyer, named for example minicrone, with a processor with power and range of microprocessor, with itself stored in "@self" variable.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More possibilities for making for example, an AI that would play the game as enemy with actual flying, fixing and building stuff.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
This would allow for compact lag machines and a way to make saves infinitely large.

**Comment by Bottinator22** [comment]
> This would allow for compact lag machines and a way to make saves infinitely large.

There's a unit limit...

**Comment by genNAowl** [comment]
> an AI that would play the game as enemy with actual flying, fixing and building stuff.

Isn't this already possible with world processors? Also, this is (remotely) similar to the AI things that are in attack maps right?

**Comment by code-explorer786** [comment]
Nice idea, though I think this should be in a mod rather than in the base game. :+1:
