### ISSUE TITLE
Musical mechanics

### ISSUE THREAD

**Issue by RexAliis** [Anuken/Mindustry-Suggestions#3715]
### Describe the content or mechanics you are proposing.

Add variations and effects to music.
Examples:
- Guardian Music: A music that will play every time there are 1 or more enemy guardians on the map. (This is already in the trello but it is a good example)
- Terrain type music: When a player is submerged in water the music will be distorted so that the sound source will simulate being underwater.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Music has always been an important aspect in video games, good music always improves the gaming experience by 100%.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
1. Boss music already exists
2. You're better off just making music for Tantros. Audio for being submerged doesn't make much sense, as the 2D camera is not underwater.
Tantros does seem to be underwater from its effects, however.

**Comment by EclipseTheOldOne** [comment]
> I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

![Screenshot_31](https://user-images.githubusercontent.com/43229798/178133887-508c6e30-c3e0-4f56-8c32-5147662feacd.png)

**Comment by Bottinator22** [comment]
They did mention the trello

**Comment by Rex-Hm** [comment]
Eclipse, take the time to read the whole suggestion

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More <Music> before. This is a revelation. I would never have thought of adding More <Music> myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More <Music> immediately."
