### ISSUE TITLE
STEALTH COMPOSITES

### ISSUE THREAD

**Issue by SpectralSen** [Anuken/Mindustry-Suggestions#3717]
### Describe the content or mechanics you are proposing.

Self-explanatory. I emphasize putting this on mech units, a dedicated sabotage team. 

For stealth aircraft designs, make the design as sleek as possible. 

Also, make the stealth units black. Dark colors absorb more light as light colors deflect it. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A headache for the receiving end of death tortillas, I imagine putting deceiving the players that they completed a campaign node only for their cores and critical infrastructure to get yeeted to dust at the last minute.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
>
> A headache ...
> ... get yeeted to dust at the last minute.
