### ISSUE TITLE
Overheating in Space Biomes, Radiators, Space Shrapnel

### ISSUE THREAD

**Issue by SpectralSen** [Anuken/Mindustry-Suggestions#3718]
### Describe the content or mechanics you are proposing.

In space, there are no molecules that will conduct heat through conduction or convection. Turrets should overheat significantly faster in space as there is no air around the barrels, hence air cooling for computer rigs. Liquid cooling should be mandatory for vacuum environments. 

And chemical combustion drones should only use RCS thrusters or they should radiate a lot of energy through light panels (Making it a giant lightbulb is a very practical idea *sarcasm*).

Add radiators. 

Low and High-speed shrapnels from dead units and buildings will absolutely make space a living hell.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More reality-grounded gameplay, also more challenge for both sides as well as a new environment for players. We after all are limited on atmospheric battles.

This would place more emphasis on protecting cooling lines, significantly pressuring the players to absolutely protect critical infrastructure, instead of just only protecting nuclear plants. Anuken might create a dedicated turret variant for space biomes just for this.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
More realism doesn't mean more good.
