### ISSUE TITLE
TitleDo not use "Mindustry" as root in future "Mindustry BE" updates

### ISSUE THREAD

**Issue by wrtyrd** [Anuken/Mindustry-Suggestions#3719]
### Describe what you would like changed, and why.

Because of the large number of servers in 'Mindustry 135' and the author's reluctance to update to beta mods it seems necessary to keep BE coexisting with 135

### Describe the changes you want to propose. Include possible alternatives.

Change the root directory of 'Mindustry BE' to Mindustry BE

**Comment by SMOLKEYS** [comment]
> Change the root directory of 'Mindustry BE' to Mindustry BE

hmm

yes

the floor here is made out of floor

**Comment by wrtyrd** [comment]
> > 将“Mindustry BE”的根目录更改为Mindustry BE
> 
> 嗯
> 
> 是的
> 
> 这里的地板是用地板做的

I'm really bad at talking
