### ISSUE TITLE
Troop cost balancing requests

### ISSUE THREAD

**Issue by kingb74** [Anuken/Mindustry-Suggestions#372]
Anuke can u please not make daggers cost lead it will disrupt everything cause lead isn't a resource u can get everywhere and it will make making daggers harder than it need to be and please crawlers cannot cost blast they just can't cause blast is expensive to make and all crawlers do is blow up and die so please maybe even if it's 20 coal it just cant coast blast and also the price for titan mechs is a bit excessive but for 2level crawlers it makes sense same goes for fortress and 3level crawlers their prices need to be different for each upgrade 

*Maybe u wear already planing to do some of these but this is just to make sure*

**Comment by SupremeTurtle** [comment]
'-'
