### ISSUE TITLE
New generator for Erekir

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#3720]
### Describe the content or mechanics you are proposing.

Name: Stirling Generator
Size: 3x3
Build Cost: 50 Beryllium, 60 Graphite, 100 Tungsten
Input: At least 10 Water/sec, less than 10 won't work. As the input water increases, the power generation will increase(maybe should set a cap), which should be consistent with logarithm (just suggest, `f(x)=42*log(2,x-9)+200`).
Power: 200 power units/sec when water input only 10/sec, takes time to boot.
Enhancements: 20 slag/sec for 2x power output

A Stirling engine converts heat energy, to mechanical energy (work) by repeating a series of basic operations, known as its cycle. Erekir is a hot planet, so we can input water to create a temperature difference and the stirling engine would work.
![log](https://user-images.githubusercontent.com/45112661/178172137-01a15f65-fc4b-4841-8c21-8e6acf4a175b.jpg)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I just realized that Erekir's generators are too limited, if the map doesn't have arkycite, player will be forced to use the poor turbine.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
The limited power might be intended, since it forces you to be more efficient and careful how you use your power

**Comment by Hexrotor** [comment]
> The limited power might be intended, since it forces you to be more efficient and careful how you use your power

Well, once the block is built, we can't control it by using logic or disconnect powernode manually like serpulo, honestly it makes the 'efficient' be a hard thing to do.

**Comment by itcannotbe** [comment]
Well like serpulo, blocks doesn't consume power when blocks can't run. (lacking inputs/full output buffer)

**Comment by Hexrotor** [comment]
> Well like serpulo, blocks doesn't consume power when blocks can't run. (lacking inputs/full output buffer)

True, so let's back to the title. 😉
