### ISSUE TITLE
JSONScript

### ISSUE THREAD

**Issue by aawwaaa** [Anuken/Mindustry-Suggestions#3722]
### Describe the content or mechanics you are proposing.

like this:
[
    {
        "type":"log",
        "args":[
            "#string",
            "$var"
        ],
        "output":null
    },
    {
        "type":"if",
        "args":[
            {
                "type":"operation",
                "args":[
                    "==",
                    "*0",
                    "*1"
                ],
                "output":"RET"
            },
            [
                {
                    "type":"log",
                    "args":[
                        "#pass"
                    ],
                    "output":null
                }
            ],
            [
                {
                    "type":"log",
                    "args":[
                        "#not pass"
                    ],
                    "output":null
                }
            ],
        ],
        "output":null
    },
    {
        "type":"set",
        "args":[
            "*16"
        ],
        "output":"$a"
    },
    {
        "type":"while",
        "args":[
            {
                "type":"operation",
                "args":[
                    ">",
                    "$a",
                    "*100"
                ],
                "output":"RET"
            },
            [
                {
                    "type":"log",
                    "args":[
                        "#loop"
                    ],
                    "output":null
                }
            ]
        ],
        "output":null
    }
]

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think we needs a way to make mod in ios better.
so i hope you add this to the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by aawwaaa** [comment]
> 

yes,just add function,call or other...

**Comment by BlueWolf3682** [comment]
No.

**Comment by Mythril382** [comment]
Just use Java.

**Comment by code-explorer786** [comment]
1. Apple guidelines.
2. This looks like abstract syntax tree but much worse.

**Comment by BlueWolf3682** [comment]
iOS cannot be handled better with modding. Even now, JSON support really pushes what Apple allows.

Close this suggestion. it will not be added.
