### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by WiseMango13452** [Anuken/Mindustry-Suggestions#3725]
### Describe the content or mechanics you are proposing.

Please Please PLEASE add accounts. I have an installation on my phone and on pc and would love to not have to export and import saves when i want to switch.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Self-explanatory; Easier access.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Error-In-Code** [comment]
You definitely did not read the README
![the_cat_says_no](https://user-images.githubusercontent.com/43973418/178842653-57019b59-d96c-4170-ac23-cd9d38709dc7.jpg)

**Comment by TheRealIvyX** [comment]
settings > game data > import/export data

**Comment by itcannotbe** [comment]
### Describe the content or mechanics you are proposing.

Please Please PLEASE read the ReadMe. I have a list things you shouldn't suggest and would love to not see a suggestion on the said list such as  built in cloud sync

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Self-explanatory; Just Read the ReadMe.

**Comment by Mythril382** [comment]
As if the 'Export Data' button doesn't exist, and read the README.

**Comment by RouterChainsSuckk** [comment]
> ### Describe the content or mechanics you are proposing.
> Please Please PLEASE add accounts. I have an installation on my phone and on pc and would love to not have to export and import saves when i want to switch.
> 
>google drive

**Comment by end-me-please** [comment]
Accounts require centralised servers which this game doesn’t have. 

You can get this functionality by paying for the steam version, but not on mobile

**Comment by WiseMango13452** [comment]
> You definitely did not read the README ![the_cat_says_no](https://user-images.githubusercontent.com/43973418/178842653-57019b59-d96c-4170-ac23-cd9d38709dc7.jpg)

sorry guys i was wondering if the cloud meant accounts and decided against it 🤦‍♂️sorry for my stupitidy, mb
