### ISSUE TITLE
Rebuild "mask"/"overlay"/"guide" opacity slider

### ISSUE THREAD

**Issue by Photonic0** [Anuken/Mindustry-Suggestions#3727]
### Describe the content or mechanics you are proposing.

A slider in the settings menu to change how opaque the rebuild guide is

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Sometimes, depending on the person or type of terrain, it's hard to make out which block it is. For example, on snow or generally brighter terrain tiles. This would also add the option to easily disable the guide by setting the opacity to 0% and generally make the feature more accessible.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by runiArnsbjornson** [comment]
could be part of the accessibility features i suggested [here #3743](https://github.com/Anuken/Mindustry-Suggestions/issues/3743)
