### ISSUE TITLE
Destroying buildings refunds materials, but building over them doesn't.

### ISSUE THREAD

**Issue by Man-Over-Game** [Anuken/Mindustry-Suggestions#3730]
### Describe what you would like changed, and why.

When building over a block (like replacing a Surge wall with a Plastinium one), the player doesn't get refunded resources from the original block.

In order to get those resources while replacing it, the player has to first delete the original block and then manually place its replacement in the empty spot.

Usually, this wouldn't be a big deal, but it's counterintuitive.  A player would naturally assume that replacing a block is strictly a convenience for the player and wouldn't presume that the materials for the original building are lost.

### Describe the changes you want to propose. Include possible alternatives.

I can see where this might get a little complicated to program, consideringboth  how resources are usually refunded based on how deconstructed the block is while having to track the value of multiple buildings with a single replacement (like replacing 3 small walls with a larger one), but I think a plausibly easier solution is to reward the sum of the refunded materials upon completion of the larger building.

**Comment by end-me-please** [comment]
Solution: keep the old building, make the buildings stack instead 🧠

**Comment by code-explorer786** [comment]
Good suggestion!
Personally I think this should go to bugs instead...

**Comment by itcannotbe** [comment]
Loophole detected:

Attempt to place over a building then quickly deconstruct it for faster refunds.

**Comment by Manymano** [comment]
This is an annoying bug, so yeah

**Comment by Man-Over-Game** [comment]
> 

That's why my recommended solution is to only get the refund when the new block is finished

**Comment by Man-Over-Game** [comment]
> Loophole detected:
> 
> Attempt to place over a building then quickly deconstruct it for faster refunds.

**Comment by Man-Over-Game** [comment]
> Loophole detected:
> 
> Attempt to place over a building then quickly deconstruct it for faster refunds.

That's why my recommendation was to not reward the refunded materials until the new block is completed.

**Comment by TacticalMook** [comment]
Could make replacement of structures actually perform deconstruction before construction.
