### ISSUE TITLE
Adding Stone And Concrete

### ISSUE THREAD

**Issue by Tempesyad05** [Anuken/Mindustry-Suggestions#3731]
### Describe the content or mechanics you are proposing.

I think the resources in the mindustry are too few. so. I suggest adding a resource. namely stone and concrete. Stone is a resource that is commonly used to build a building structure. and it can be drilled using a pneumatic drill (or higher drill grade). stone can be made into a wall, or a core material (perhaps). Stone can also be processed into concrete using a tool. then the concrete can be used for the purposes of building structures or cores (possibly).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

First, it will add some wall options. and also some buildings. also changes in materials required in certain buildings. also make players feel this game is real. Because stone and concrete are materials that are often seen in everyday life.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Halt-alt** [comment]
1. Mindustry clearly doesn't aim for the realism vibe, so the last point doesn't hold.
2. This material wouldn't really be distinguishable from the ones that are here already... Like, you try to make it the new "basic materials" for walls and structures... But why? That's the role of copper already. Adding a new copper doesn't make much sense. Again, same with concrete - titanium sort of becomes your new "basic material" in later game, and concrete being another one doesn't make much sense.

**Comment by IVV-NCX** [comment]
If you look at how each material is used in the game, it’s pretty clear that when Anuken adds a new thing, it has a large variety of uses, or will have many uses.

Look at how in Erekir, they chose to use the same materials in general, even if graphite is nowhere similar to silicon. This idea is limited and doesn’t add any fresh and new content.
