### ISSUE TITLE
Modfolder Symlink Following

### ISSUE THREAD

**Issue by ElectronicsArchiver** [Anuken/Mindustry-Suggestions#3733]
### Describe the content or mechanics you are proposing.

Follow symlinks when loading mods to allow placing them in external locations.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Gives modders the possibility to develop with cleaner setups and not have them be forced to place their development files into the mod folder.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ElectronicsArchiver** [comment]
Wow

**Comment by Mnemotechnician** [comment]
> and not have them be forced to place their development files into the mod folder.

That's something you're really not supposed to do.
If you're experienced enough to create a symlink, then you surely can make a small bash/sh/fish script to copy your mod to the mods folder instead of storing your source code there.

**Comment by ElectronicsArchiver** [comment]
> That's something you're really not supposed to do.

Says who exactly?

> If you're experienced enough to create a symlink, then you surely can make a small bash/sh/fish script to copy your mod to the mods folder instead of storing your source code there.

So rather than have a more modular system every 
mod that wanted to have this setup should use a 
dedicated shell script to do this?

Sounds like a bad tradeoff.

**Comment by ElectronicsArchiver** [comment]
> Me. You don't store dishes, cups and tools in the fridge just because you may need them to make food, do you? Same applies here, you shouldn't store your source code where it can be modified or even deleted by the game itself (e.g. when you delete the mod from the mod menu). You're putting yourself at risk for no reason at all.

What are you even talking about?

Besides the removal part can simply stay as it is and 
not follow symblinks, then there is no risk to begin with.

Besides you risk argument falls though considering that
I haven't seen a mod that even has a copy script setup,
so they are at risk by default.

> i assume you're on json/js, because users of compiled languages do not make such statements

So you are showing prejudice against programmers just because they 
don't use the same category of language, how petty could you even get..

**Comment by Mnemotechnician** [comment]
I do agree that it would be better if it followed symlinks, but I don't agree with the fact that you're saying that "you're being forced to store your development files in the mods folder" and that the absence of this feature makes anything less clean.

> So you are showing prejudice against programmers just because they
don't use the same category of language, how petty could you even get..

This is not prejudice, this is a fact. User of a compiled language __has__ to use the shell to invoke gradle (or a different tool) to compile their mod, and hence they don't say that "using a dedicated shell script" is hard. For me, for example, it costs 0 effort to type `gradle release && cpmod mod-src` and get everything ready.

**Comment by ElectronicsArchiver** [comment]
> I do agree that it would be better if it followed symlinks, but I don't agree with the fact that you're saying that "you're being forced to store your development files in the mods folder" and that the absence of this feature makes anything less clean.

Sure.

> This is not prejudice, this is a fact. A user of a compiled language has to use the shell to invoke gradle (or a different tool) to compile their mod, and hence they don't say that "using a dedicated shell script" is hard. For me, for example, it costs 0 effort to type gradle release && cpmod mod-src and get everything ready.

Considering that most js users utilize frameworks /... they also use the cmdline though many then have their IDE setup with extension that handle that for them~

Anyways, you seem to have missed the point in that it doesn't matter if it is 100 lines or 1 line, if X people have to do it instead of 1 change in the code then it's overall more effort for everyone and possibly more support needed for more inexperienced users.
