### ISSUE TITLE
Rocket turret idea

### ISSUE THREAD

**Issue by Hexareal** [Anuken/Mindustry-Suggestions#3737]
### Describe what you would like changed, and why.

The long range rocket turret looks amazing, but it was said in the demonstration that it was unbalanced so i have a idea. 

### Describe the changes you want to propose. Include possible alternatives.

Just a little balancing thing i though about when i saw the rocket launcher, maybe it'll take a very very long time to fire between rockets, and instead of one big explosion to release all the damage, it could be one large weaker explotion, then has a lingering damage over time to finish off everything in its range but that damage over time can be stopped by an existing feature.

**Comment by IVV-NCX** [comment]
It’s still a WIP. It looks like it’ll be a high tier weapon for closer to end game, and can be shot down with faster weaponry.
