### ISSUE TITLE
It's annoying looking for enemy spawn positions on new maps

### ISSUE THREAD

**Issue by Klokinator** [Anuken/Mindustry-Suggestions#3739]
### Describe what you would like changed, and why.

On any new map, it is not at all obvious where enemies spawn, or how many spawns they have. I've been surprised by secret second and third spawn points several times already. You have to spend a full minute usually flying around the maps looking for the big red circles to appear but sometimes you fly right past them and they don't appear.

### Describe the changes you want to propose. Include possible alternatives.

To that end... just put a building that spawns enemies? That way you can see it while paused? Doesn't help that flying around in your ship is slow compared to pausing and zooming the map out. Maybe if this doesn't fit the game's tone, when you pause and zoom way out you can see the enemy spawn circles appear? Just something to eliminate the minute of searching I have to do on every new map.

**Comment by BlueWolf3682** [comment]
Check the minimap in release 136.

**Comment by Klokinator** [comment]
I ended up downloading the beta. I looked and... yeah? There's nothing on the minimap to indicate enemy spawn zones, not that I can see.

Proof:
https://i.imgur.com/nOHuWdE.png

**Comment by itcannotbe** [comment]
[README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) be like:

![Reaction here](https://c.tenor.com/QcHM2sKUa9IAAAAM/oh-come-on-jim-carrey.gif)

**Comment by BlueWolf3682** [comment]
In 136, the minimap highlights spawns with purple circles. This was PR'ed in somewhere between 135 and 136.
It is not available in 126.2, and there is no reason to keep playing 126.2.

**Comment by Klokinator** [comment]
I just loaded the newest build, the beta v7 build on Steam. I seriously have no idea what you're talking about. This is on a map with incoming waves. There are no purple circles.

https://i.imgur.com/ISq9FAr.png

Am I missing something? Can someone else post an actual image of what this guy is talking about?

https://i.imgur.com/LdNcGlR.png

https://i.imgur.com/sgsA5QI.jpeg

There is nothing there. Nothing.

**Comment by Klokinator** [comment]
And just to be clear, I AM on build 136.1

https://i.imgur.com/uOTRivj.jpeg
