### ISSUE TITLE
Seeker Searchlight

### ISSUE THREAD

**Issue by Phantasm0915** [Anuken/Mindustry-Suggestions#374]
Adds a Turret called Seeker Searchlight, allowing other Turrets to focus on units with the Highest Hp. It will have long range (more or less longer than Ripple) and it won't immediately target anything that gets within range, but will target the unit with the most health after a delay of 3 second after the first unit enters its range. Ex: A wave with Daggers and one Titan, as the first dagger enters the Seeker's range, the 3 second delay will begin, allowing the wave to enter it's range, and after the delay has passed, the searchlight will spot on the Titan, since it has the highest health, and now, turrets will prioritize in taking it down over the other units. The Seeker feeds on power like the Lancer or Arc, and needs to be connected to other turrets to work, similar to connecting power nodes (it can be connected to a max of 5 turrets, these turrets will attack the marked target,while unconnected turrets will attack like normal) if there are multiple units with the most health (Like 3 Eruptors in a wave of 30 daggers) it will mark the closest Eruptors (either closest to the core, or closest to the Seeker) if every unit within range has the same amount of health, it will not mark anything and the connected turrets will attack like normal, and will only change target if the unit is killed, or the seeker has marked a new target. it could also be toggled to target only Air units, Ground units, or both

This could be very useful in Tandem with Anti-Air turrets, Meltdowns or Artillery as they ignore other distractions and attack the marked target, most often a boss, in Anti-Air situations, they would ignore Wraths and Ghouls and focus on Revenants and Liches, while with Meltdowns, it would ignore small targets such as daggers and stopping it from wasting it's attack on low health units instead of a large boss, the Ripple connected to a search light could hit the marked target, most useful if it is in the middle of a wave, damaging everything around it. This solves the problem of Ammo or power wasted on some worthless things and be used on more important things, it also makes a fine addition to Energy turrets since there are currently only a few present

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RoyalFunnyDude** [comment]
So, to clarify what you're saying, it's that the turret would target the highest hp unit currently? So like if there are 2 reapers at full hp and one reaper gets "focused" and damaged, would the searchlight re-target to the full health reaper?

**Comment by Phantasm0915** [comment]
> So, to clarify what you're saying, it's that the turret would target the highest hp unit currently? So like if there are 2 reapers at full hp and one reaper gets "focused" and damaged, would the searchlight re-target to the full health reaper?

No, I forgot to mention that the Turret will not Re-target once it has picked it's mark, only retargeting when the marked unit is killed, so in the situation you mentioned, they will focus on the "damaged" Reaper and will only attack the other one once the primary target is destroyed

**Comment by RoyalFunnyDude** [comment]
hmm...i can't see how that would be helpful in later, mass reaper waves, since it wouldn't be good to have 5 meltdowns targeting 1 reaper...

**Comment by Phantasm0915** [comment]
> hmm...i can't see how that would be helpful in later, mass reaper waves, since it wouldn't be good to have 5 meltdowns targeting 1 reaper...

Having 5 meltdowns on one Reaper is better than 5 meltdowns targetting 5 reapers, as 5 meltdowns on a single target has a bigger chance of taking it down than 1 meltdown per target as it will only slowly whittle it's health, only to be destroyed later without even killing a single Reaper

**Comment by RoyalFunnyDude** [comment]
Wait, so after the targeted unit dies, would the turrets change target immediately? b/c if it doesn't change immediately , then, in the previous scenario with reapers and meltdowns, it would create some scenarios of severe overkill...i can imagine 2 rows of meltdowns all targeting a single reaper

**Comment by Phantasm0915** [comment]
> Wait, so after the targeted unit dies, would the turrets change target immediately? b/c if it doesn't change immediately , then, in the previous scenario with reapers and meltdowns, it would create some scenarios of severe overkill...i can imagine 2 rows of meltdowns all targeting a single reaper

Of course, it all depends on how you use it, after all, who would connect 5 meltdowns to a single seeker? You could choose what turrets to connect to it, and also, I forgot to mention again, multiple seekers cannot target the same unit, once a seeker chosen a target to mark, the other seekers will choose another different target

**Comment by Phantasm0915** [comment]
> Wait, so after the targeted unit dies, would the turrets change target immediately? b/c if it doesn't change immediately , then, in the previous scenario with reapers and meltdowns, it would create some scenarios of severe overkill...i can imagine 2 rows of meltdowns all targeting a single reaper

So more accurately, it's not the turret's problem, of course you would only connect one or two meltdowns on one seeker

But you also make a valid point about Re-targetting,

I think after choosing it's first target, the delay for  re-targetting to another unit will be lessened to 1.5 seconds to increase efficiency during long fights, but it will revert back to the 3 second delay after 5 seconds of not re-targetting

**Comment by Anuken** [comment]
Use logic for this.
