### ISSUE TITLE
Controlling turrets

### ISSUE THREAD

**Issue by salty27** [Anuken/Mindustry-Suggestions#3742]
### Describe the content or mechanics you are proposing.

The ability to control turrets to shoot a certain unit or place just like what you can do in v7 with units, or the ability to make turrets prioritise certain units according to their type or position.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will increase the efficiency of certain turrets and create new strategies. For example:
- Parallax could target only bigger units and not get distracted by the smaller ones.
- Wave turrets could target units they haven't already hit, so all units are covered in water to deal extra damage.
- Lancer could be set to attack in a single direction, ensuring it always hits a whole corridor or line of enemies, and not just one.
- Players could control turrets themselves to prioritise a group of units over a decoy.
This may create a bigger skill cap as well as more creative ways to defend from the attacks

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Logic?

**Comment by salty27** [comment]
Yeah, those things can be done with logic, but just as controlling units can be done with logic too. For some tasks like Parallax it can be easy, but to attack a certain point and change it to target the desired group would be as hard as controlling an unit with logic instead of the current system
