### ISSUE TITLE
A colorblind mode

### ISSUE THREAD

**Issue by runiArnsbjornson** [Anuken/Mindustry-Suggestions#3743]
### Describe the content or mechanics you are proposing.

A colorblind mode for accessibility, probably with several settings to cover most type of colorblindness. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I am colorblind and often find myself forced to doublecheck if it's plastanium or surge alloy which are needed in some building by going in the game database. i would very much like to be able to know at a glance. 
AND the new ressource on Erekir are WAY worse than those and until i know it by heart, it's quite annoying to need to check everytime. 
I know it might not seems importants but this would be a very much needed QoL feature. (also accessibility is needed everywhere, you have very nice website to check if your color schemes are colorblind friendly) 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

### Also thank you for this awesome game and continued maintenance/improving it

**Comment by Manymano** [comment]
Man, i feel kinda bad for you.
