### ISSUE TITLE
Pack the wiki with the game 

### ISSUE THREAD

**Issue by Raif1** [Anuken/Mindustry-Suggestions#3749]
### Describe the content or mechanics you are proposing.

Add offline access to the mindustry wiki via game. There is a ton of new and confusing things to use and understand them we need keep the game wiki in hand(messege , micro processor etc.). But when ever we want to use the wiki we need to go out of the game , go to browser , search than ( also we need to be online ). So you should add an option to download the whole wiki via game ( you can pack it with the game or add a way to download wiki optionally) I think you should add the ability to access it from the pause menu and the start page.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. Will help new players
2. Offline wiki access 
3. Over all lessen the pain.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
![image](https://user-images.githubusercontent.com/76830496/180082416-13f7fb40-1135-428e-a018-056a7f21a64a.png)
Wiki.
![image](https://user-images.githubusercontent.com/76830496/180082454-1c1397e0-69a2-42fd-a780-e4a09700335c.png)
Core DB. 

If you need the logic, download RTFM.

**Comment by Raif1** [comment]
How to do that

**Comment by Catchears** [comment]
You should be able to select the question mark after selecting a block. Alternatively, you can open the core database and tap anything in there.
