### ISSUE TITLE
Oil extractors

### ISSUE THREAD

**Issue by ritzip** [Anuken/Mindustry-Suggestions#375]
**Describe what you would like changed, and why.**
Limiting oil extractors will make cultivators an option, will at least let us see blast in servers.
- Too easy to use
- Generally overpowered

**Describe the changes you want to propose. Include possible alternatives.**
Limit oil extractors to sand, shale and water. Possibly salt.

**Comment by itcannotbe** [comment]
Yeah.

Those this only need 9 water, 0.6 sand, 180 power to make 15 oil every second.
It's stupidly insanely efficient at their current state.
