### ISSUE TITLE
Admin Team Control Tools

### ISSUE THREAD

**Issue by BiggerBrainYT** [Anuken/Mindustry-Suggestions#3751]
### Describe the content or mechanics you are proposing.

Admins should have the ability to move players to different teams. This could also be a configurable option before in the custom game menu being off by default since people always seem to see the ability for swapping teams as abuse.

There have been very similar posts but this is different. I completely understand that players would 100% abuse the ability to swap teams and that is why I think that only admins should have this power.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be the greatest thing ever for custom games and would expand the replayability and possibilities significantly and to prove that, here are two scenarios I commonly come across:

I've been playing PVP battles with my friends for a long time and it has become very clear who the better players are. As fun as the game is, certain teams of people together can make the experience for everyone else miserable. Because of this, there is a lot of coordination required to get all the right people on the right teams and if certain people leave or get eliminated, if they wish to rejoin, they may be incorrectly scattered across teams that wouldn't be fair. For example, let's say you are playing 1v1v1v1 and one of the teams gets eliminated, if they wish to rejoin they will automatically be put on the first team and can't do anything about it. If player 1 is the one who eliminated the person or is in general the best player there, then regardless of what the player who just joined the team would do (whether malicious or good), it would be considered unfair. If an admin could simply move the player that has just rejoined to another team that was struggling, there would be a possibility for a comeback and the game would continue and maintain that level of fun or possibly more.

Custom games are fun and making custom game modes are even more fun. Having interesting game modes that can be hosted among friends like zombie survivals, 1v3's, and other game modes that require team changing. These would be really easy if an admin could just move people around whenever they are supposed to but instead requires a lot of fiddling with figuring out who hosts (which can suck if only one person has the map) and whether you need to temporarily get your phone out and join with an alt so the next person who joins would join the right team.

Overall, the fact that teams are automatically made even in custom games is very limiting and this feature is so very desired by my whole friend group and probably by many more.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
Me when the /js:

**Comment by BiggerBrainYT** [comment]
Can you please explain?

**Comment by 50275** [comment]
There's an admin-only /js command that allows players to run JS (javascript) commands in Mindustry which can do pretty much anything in-game. There should be a way to change the player's team somewhere, but I don't know it. In the mean-time though, you could try screwing with `/js Vars.world.tile(X,Y).setNet(Vars.content.block(184), Team.get(2), 0)` in your server. (replace the X and Y with coordinates in-game.)

**Comment by 50275** [comment]
So I looked in the # plugins in the Mindustry discord, and I found this. https://github.com/J-VdS/TeamPlugin. Good luck.
