### ISSUE TITLE
pathfinding on elikir is broken

### ISSUE THREAD

**Issue by Marcapus** [Anuken/Mindustry-Suggestions#3752]
### Describe what you would like changed, and why.

pathfinding on elikir is broken: when you block all places to enter your base, enemy units just don't attach until you start attacking, making huge packs of more than 120 units if you wait too much, making it impossible to capture the sector.

here's an exemple of a defence that may cause this bug:
![image_2022-07-21_140034263](https://user-images.githubusercontent.com/91971949/180208754-a48dc4a0-d76b-47c0-b2f3-e83fe428ab33.png)

### Describe the changes you want to propose. Include possible alternatives.

pls fix game ;]

**Comment by Bottinator22** [comment]
https://github.com/Anuken/Mindustry/issues/new?template=bug_report.md

**Comment by Mnemotechnician** [comment]
"elikir" lmao

**Comment by Marcapus** [comment]
i cant spell it right XD
    Le vendredi 22 juillet 2022, 00:16:38 UTC+2, Mnemotechnican ***@***.***> a écrit :  
 
 


"elikir" lmao

**Comment by Anuken** [comment]
I don't see this as a bug. You have more defenses, so they build up more units. There is zero pathfinding involved in the overall RTS attack designation AI.

**Comment by Marcapus** [comment]
i didn't think of that
