### ISSUE TITLE
Adding option to play randomly generated maps

### ISSUE THREAD

**Issue by salty27** [Anuken/Mindustry-Suggestions#3753]
### Describe the content or mechanics you are proposing.

When creating a custom match, it would be great if you could chose to play in a map generated by Serpulo, Erekir or mod sector generators, being able to use your own seed and select certain things like the difficulty or resource amount.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would remove the need to look for new maps once you have already made a few custom matches, since the amount of them by default isn't big. In addition, it could allow players to change a map according to their needs faster, creating a hard challenge or a peaceful map with just a few clicks. It would create a new layer of improvisation as players would no longer know how the map looks like.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
this already exists

in the editor

**Comment by salty27** [comment]
editor is intended for developers and people who want to create and modify maps willingly, plus maps are saved until you delete them. Randomly generated maps wouldn't be able to be modified, could be created from the custom match tab, and wouldn't be stored in the custom maps tab, so they wouldn't take up extra space in the device or require you to manually remove them
