### ISSUE TITLE
Heat Source for sandbox

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#3754]
### Describe the content or mechanics you are proposing.

It would be useful for there to be a heat source.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make testing heat consuming blocks easier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
YES YES YES YES

**Comment by SoMall-dumpling** [comment]
Seems like it has been added.

**Comment by luxDuck** [comment]
Nice! I'm glad it was added!
