### ISSUE TITLE
Optimization for M1 macs

### ISSUE THREAD

**Issue by aushafer06** [Anuken/Mindustry-Suggestions#3755]
### Describe the content or mechanics you are proposing.

Simply optimizing Mindustry for M1 macs so it doesn't have to run through Rosetta 2.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would greatly improve performance for people like me who use M1 products (most commonly a base model M1 MacBook Air. Better fps, less lag, less jitter, and much better battery performance when playing unplugged. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
Man's saying "Simply optimizing Mindustry for M1 macs" like there's a magic button with the label "optimize the game for m1 macs", which makes the code run faster on m1 macs, that anuke doesn't want to press

**Comment by aushafer06** [comment]
Exactly, I'm just encouraging him to push that button. Maybe he just doesn't like Mac users...

**Comment by itcannotbe** [comment]
Is there even such button?

**Comment by IVV-NCX** [comment]
Cant you run it using JDK?

**Comment by Anuken** [comment]
If you want me to compile/optimize for M1 macs, buy me one first. I'm not going to drop $1000 on a device I won't use just so the game can run faster for a tiny fraction of users. This is not something that can be done without owning such a device.

**Comment by aushafer06** [comment]
Could you possibly start a fundraiser or something, i’ll gladly pitch in a few bucks along with many other M1 users. Maybe once it got to like $1000, you could get one for that sole purpose. Also, isn’t there a way to rent stuff like that?
