### ISSUE TITLE
the core turned into campfire 

### ISSUE THREAD

**Issue by Corsh** [Anuken/Mindustry-Suggestions#3757]
### Describe what you would like changed, and why.

make core immune to some debuff eg(incendiary, shocked,...)

### Describe the changes you want to propose. Include possible alternatives.

core= heart > heart = core >most important thing > need to be strong and protected
btw I just lost some sector cuz of core burning

**Comment by IVV-NCX** [comment]
Tsunami moment

**Comment by Corsh** [comment]
nope the fire spread very fast  even 4 tsunamis with water cant extinguish it

**Comment by genNAowl** [comment]
Add menders to keep outheal the fire?

**Comment by itcannotbe** [comment]
> nope the fire spread very fast even 4 tsunamis with water cant extinguish it

Probably tsunamis doesn't have a good supply of water.

**Comment by Corsh** [comment]
lmao i use modded water extractor that can suck up almost 100 unit of water

**Comment by Corsh** [comment]
it's really annoying to deal on low resource

**Comment by mega2335** [comment]
c r y o f l u i d

**Comment by IxGamerXL** [comment]
zomg i gave the core so many attack+overdrive buff s it no work!!1!
