### ISSUE TITLE
Logic interaction with Factories

### ISSUE THREAD

**Issue by Poloi35** [Anuken/Mindustry-Suggestions#3758]
### Describe the content or mechanics you are proposing.

A way to control spawn point of factories with logic

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

With the new rts system it has been harder to control troops, espacially grounded ones now that the pathfind/command center has been removed. Doing so would act as a once pathfind but it could help immensely nonetheless

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by runiArnsbjornson** [comment]
a bit like rally point in other rts game ? would be very nice indeed
