### ISSUE TITLE
heat router

### ISSUE THREAD

**Issue by Marcapus** [Anuken/Mindustry-Suggestions#3760]
### Describe the content or mechanics you are proposing.

add a heat redirector router pls

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would be helpful for players and will allow for more compact factories.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
It exists in erekir though. And the only things that have “heat” are thorium and blast reactors iirc. There’s no point for those 2 things.

**Comment by Marcapus** [comment]
it is for erekir -_-

**Comment by Marcapus** [comment]
and there is only the one way thing not a 3 way heat redirector

**Comment by IVV-NCX** [comment]
I think a one way is balanced as is.

**Comment by Marcapus** [comment]
yeah
