### ISSUE TITLE
Improved Flare Targeting

### ISSUE THREAD

**Issue by conquerer14** [Anuken/Mindustry-Suggestions#3762]
### Describe what you would like changed, and why.

I noticed that people like placing their inactive combustion generators inside their defenses so that the flares won't have to disturb/destroy the real power sources...so I was thinking "what if flares prioritizes energy sources that are actually producing energy instead of leading to their deaths by a clearly shown death zone?" I know some people maybe annoyed if it's changed but I just wanted to simply balance out the usefulness of flares for the attackers (unless they have some kind of logic contraption or being controlled)....

### Describe the changes you want to propose. Include possible alternatives.

-change the flare target prioritization to active energy sources or currently producing ones

-if RTS unit controls will also be applied in Serpulo, then this shouldn't be necessary anymore

**Comment by itcannotbe** [comment]
Would have to agree on this. It feels kinda stupid for units to target inactive buildings
