### ISSUE TITLE
Pasted mlog empty lines does not count?

### ISSUE THREAD

**Issue by shangjiaxuan** [Anuken/Mindustry-Suggestions#3766]
### Describe what you would like changed, and why.

When writing code that have a lot of jumps, it often make things easier by reserving line numbers and putting in labels, that makes things more stationary when filling code in between.

Currently empty lines in text mode are not imported, and line numbers can go to wrong lines. Also editing code in text is not easy.

### Describe the changes you want to propose. Include possible alternatives.

Import empty lines.
Better: Add a optional number before instruction in text mode (since no starting identifiers start with numbers, required to be no less than the line's current `@counter` value) and set the counter of that line of logic to that number.

Best (also less work, just a dictionary in interpreter, I suppose):
 Dummy 'label instruction' that marks a position of execution (many assemblers out there support this).

**Comment by random-guy1285** [comment]
I'm like 90% sure you can already jump to labels if imported from text

**Comment by shangjiaxuan** [comment]
> I'm like 90% sure you can already jump to labels if imported from text

How about syntax? Never saw any documentation on this. Just a `label xxx` line? (also does it work when labels are below the jump instruction? Like when using `if(xxx){}` clauses).

**Comment by shangjiaxuan** [comment]
Currently resorting to edited version of [dstodev/mindustry-logic-preprocessor](https://github.com/dstodev/mindustry-logic-preprocessor)

**Comment by shangjiaxuan** [comment]
> today on "people suggesting things that exist":
> 
> ```
> someLabel:
> print "frog"
> printflush message1
> jump someLabel always
> ```

Syntax correct in 136.1, but seems like `set @counter someLabel` doesn't  work. I suppose that doesn't matter.

**Comment by end-me-please** [comment]
if you’re setting counter to a static label, you can just use jumps

Labels work in older versions too. They get stripped away when importing code in-Game anyways
