### ISSUE TITLE
Multiple turret control

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#377]
**Describe the content or mechanics you are proposing.**
Just as you can control multiple units at once in 6.0, you could be able to control multiple turrets at once.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Makes it easier to control your defensive line.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by macdowntwo** [comment]
Y E S

**Comment by bsjohnson20** [comment]
Introducing spamming arcs and controlling them then aiming them **ALL** at one target quickly deleting them all... Hmm OP?

**Comment by gen-NA-owl** [comment]
This is possible with the new logic blocks (which, as of now, are still expierimental)
