### ISSUE TITLE
enemy pathing preview

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#3772]
### Describe the content or mechanics you are proposing.

![E0DAF4F0-53F1-4908-90D9-B19BDE4F4679](https://user-images.githubusercontent.com/45698812/181457660-93d6d86d-577d-4ddb-894a-7c6ea9811f56.jpeg)
preview paths enemy will take

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

PROS:
- i think it would look cool
- makes it easy to see spawnpoints
-  makes enemies more predictable

CONS:
- might be crowded on big maps
- visual style might clash 
-  makes enemies more predictable
- lowers skill celing
- might be made obsolete by new ai

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Pros: Did not read ReadMe
Cons: Read the ReadMe

**Comment by itcannotbe** [comment]
~Close this before anuke takes your soul.~
