### ISSUE TITLE
Make drawing stuff about incomplete sprites (eg: Core: Citadel) active by default in mods.

### ISSUE THREAD

**Issue by yesC48** [Anuken/Mindustry-Suggestions#3773]
### Describe the content or mechanics you are proposing.

There should be something that supports drawing input/output sprites inside blocks (eg: Pyrolysis Generator having a conduit in it when it gets connected to a liquid source.)[I'm sorry, I'm just bad at explaining. If you need an example, just look at the seams in the said generator.] render by default.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can help for modders so that they can make Erekir related content without making them render manually, which is a qol change for other mods.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by yesC48** [comment]
unfortunately…

**Comment by yesC48** [comment]
why is it not being closed

**Comment by itcannotbe** [comment]
> why is it not being closed

Because people like you put in irrelevant comments days after the one one, thus preventing the workflow from closing the issue since it needs 20 days since the last comment*.

**Comment by Anuken** [comment]
there is a close button you can press yourself... since you made the issue...
