### ISSUE TITLE
A version changer

### ISSUE THREAD

**Issue by Egamer09** [Anuken/Mindustry-Suggestions#3776]
### Describe the content or mechanics you are proposing.

If you know the minecraft Java launcher then you would know that you can launch minecraft in different versions 
I think this could work with mindustry 
For ex
Going from v7 to v6
Or going from v3(if there was one) to v7
This would also be useful with mods cause if your on a version you cNt play it on then you could change your version 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Like I said above
This would help with mods
Plus if people wish they could play on a server that they can't becuase of their version then that would be solved too

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
So basically you want a mostly free game with no consistent revenue streamm to host a server where people can download their wamted version of the game?

**Comment by Egamer09** [comment]
...

**Comment by Tert0** [comment]
> So basically you want a mostly free game with no consistent revenue stream to host a server where people can download their wamted version of the game, like in Minecraft launcher?

I think the Attachments of the Github Releases could be used for this.
For example if you want Version v126.2 you can download https://github.com/Anuken/Mindustry/releases/download/v126.2/Mindustry.jar
So i think there is no need to host a extra server for this.

**Comment by IVV-NCX** [comment]
> So basically you want a mostly free game with no consistent revenue stream to host a server where people can download their wamted version of the game, like in Minecraft launcher?

Seeing as you can download mods by linking the repo, it should be possible to do the same for v6/v7.

**Comment by stuffyAI** [comment]
> > So basically you want a mostly free game with no consistent revenue stream to host a server where people can download their wamted version of the game, like in Minecraft launcher?
> 
> I think the Attachments of the Github Releases could be used for this. For example if you want Version v126.2 you can download https://github.com/Anuken/Mindustry/releases/download/v126.2/Mindustry.jar So i think there is no need to host a extra server for this.

That will download every version you ever played in persistent storage, meaning with 10 different versions you will also take 10x the storage.

To get a proper Launcher, like the Minecraft one, a bunch of work would have to be put in.
You are free to create a Pull request implementing that.
