### ISSUE TITLE
Addon to Oil Extractor balance from issue #375

### ISSUE THREAD

**Issue by Absolute359** [Anuken/Mindustry-Suggestions#378]
Since it seems like the Oil Extractor is now bound to the different floor types (extracting oil from ground) with different efficiencies it would make sense to delete the sandinput as item.
For example if the Oil Extractor must be placed on sand it occupies 9 tiles wich could be needed for drilling sand.
For the moment 1 water buffed Laserdrill could supply around 8 Oil Extractors.
If this sounds to overpowered again the water consumption could be increased a little.

**Comment by itcannotbe** [comment]
The only reason why using shale previously wasn't that common is the block is placable almost anywhere. And people who used to use shale has no problem delivering both water and sand. I don't see this to be an issue.

**Comment by Anuken** [comment]
> it would make sense to delete the sandinput as item

One of the reasons sand is an item input is that it is involved in the process of *fracking*. Placing the oil extractor on sand should not change this requirement.
