### ISSUE TITLE
add a heat source and void block 

### ISSUE THREAD

**Issue by tuopi27** [Anuken/Mindustry-Suggestions#3780]
### Describe the content or mechanics you are proposing.

the new heat mechanic works very similarly to liquids, so it deserves its own source and void blocks.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

its currently akward to work with blocks that require heat in sandbox. add a source for heat.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
**Heat Source** already exists.

**Comment by Bottinator22** [comment]
Source exists in Bleeding Edge
Void is probably unnecessary, think heat system just wastes all extra heat anyway

**Comment by hello-hello-there** [comment]
What about a heat void that measures the amount of heat going into it?

**Comment by Bottinator22** [comment]
Literally any heat-consuming block would work for that, and better, since
heat is spread evenly across the surface. Reading the heat of a single
point would only be a third of the heat output with a heat redirector.
