### ISSUE TITLE
Valves for conduits

### ISSUE THREAD

**Issue by hello-hello-there** [Anuken/Mindustry-Suggestions#3781]
### Describe the content or mechanics you are proposing.

Monodirectional* valves with a customizable maximum fluid flow rate.

*Because, according to the Trello, conduits are becoming bidirectional

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Let's say you're producing some amount of oil, but you want only some amount to go to production, and the rest goes to defenses. If you don't have a max-flow valve, during an attack, the turrets might not get enough oil.
Or maybe you want to separate any extra slag, but you don't want to underfeed your disassemblers.
Probably plenty more uses I can't think of.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Manymano** [comment]
That's a pretty good idea, it's like a router but more controllable
