### ISSUE TITLE
Massive Suggestion

### ISSUE THREAD

**Issue by MrPigeontheCoder** [Anuken/Mindustry-Suggestions#3783]
### Describe the content or mechanics you are proposing.

Make some sort of permanent solar system (When interplanetary content is fully released) In which players compete for space, territory and resources. Players choose a starting sector and must advance through NPC factions and possibly attack/defend other players. Alliances could be made and after a month or something the world resets. Captured sectors can be attacked by enemies (Both player and NPC) and over time, captured sectors decay and become abandoned. Only border sectors can become abandoned. It is to encourage players to keep playing the game... Players could also host their own systems so they can play with just their friends, or play on the global system.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'll be fun and will make for an interesting perma-gameplay in my opinion. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> [ReadMe](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) 
> ### A few things you shouldn't suggest
> ###### These have been proposed many times already, and I won't be adding them.
> - Allied teams

**Comment by Bottinator22** [comment]
> > [README](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)
> > ### A few things you shouldn't suggest
> > ###### These have been proposed many times already, and I won't be adding them.
> > 
> > * Allied teams

that's a tiny fragment of their suggestion

**Comment by IxGamerXL** [comment]
I actually like the idea for having a global multiplayer network where players can assemble teams with other players, and battle it out for territory. Despite all that, there will need to be some form of safe zone for each team, like with Sharded's area being Ground Zero and it's adjacent sectors. This ensures that teams won't end up with no territory and have to wait until the solar system resets. There might also have to be nearby sector penalties which prevents enemy teams from easily capturing sectors around safe zones.

I think there should also be Valuable Sectors, which automatically generate pre-crafted late-game resources added along with whatever the sectors contains, which you will need for advancing research and making stronger and more effective buildings.

Speaking of Research, All teams start off with minimal amounts of research, meaning you have to race in research as quickly as possible, as well as claim as much land and fortify as much as you can.

The only issue with this is the amount of data required to hold for the solar system, and the amount of server upkeep required to have this much action happen all within the span of a month. It's not a bad idea, but it certainly has some bits to consider.

**Comment by Evo04Taser** [comment]
> > [README](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)
> > ### A few things you shouldn't suggest
> > ###### These have been proposed many times already, and I won't be adding them.
> > 
> > * Allied teams

It's not allied teams, it's ALLIANCES, basically multiple players in a single TEAM

**Comment by itcannotbe** [comment]
Also how would you even manage to host such a game mode?

**Comment by MrPigeontheCoder** [comment]
> I actually like the idea for having a global multiplayer network where players can assemble teams with other players, and battle it out for territory. Despite all that, there will need to be some form of safe zone for each team, like with Sharded's area being Ground Zero and it's adjacent sectors. This ensures that teams won't end up with no territory and have to wait until the solar system resets. There might also have to be nearby sector penalties which prevents enemy teams from easily capturing sectors around safe zones.
> 
> I think there should also be Valuable Sectors, which automatically generate pre-crafted late-game resources added along with whatever the sectors contains, which you will need for advancing research and making stronger and more effective buildings.
> 
> Speaking of Research, All teams start off with minimal amounts of research, meaning you have to race in research as quickly as possible, as well as claim as much land and fortify as much as you can.
> 
> The only issue with this is the amount of data required to hold for the solar system, and the amount of server upkeep required to have this much action happen all within the span of a month. It's not a bad idea, but it certainly has some bits to consider.

All teams should have a starter sector that cannot be captured, as you said. I don't know how to get enough money for the servers however...

**Comment by MrPigeontheCoder** [comment]
I think teams should choose a starter sector and other players can join teams. I'm not sure if alliances should be discarded however... Maybe total-war would be better? I think it would be a bit more interesting. A LOT of planets would be needed however, due to the enourmous playerbase. Please keep giving opinions.

**Comment by IxGamerXL** [comment]
> > > [README](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)
> > > ### A few things you shouldn't suggest
> > > ###### These have been proposed many times already, and I won't be adding them.
> > > 
> > > * Allied teams
> 
> It's not allied teams, it's ALLIANCES, basically multiple players in a single TEAM

And they are not permanent, nor extremely effective. From what I see, they can be used to signal that they are friendly if the alliance is accepted, but it doesn't stop one person to organize an attack on their allies. It's practically just an insecure link for two teams, and easily broken if either team decided sabatoge was the next option.
