### ISSUE TITLE
Add a note that a weapons projectile is guided

### ISSUE THREAD

**Issue by GregSCooper2514** [Anuken/Mindustry-Suggestions#3784]
### Describe the content or mechanics you are proposing.

Add a note in the database that indicates that a units/turrets weapon is firing a guided projectile.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Adding the note can help players know that these projectiles can be guided.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
Pretty sure thats the Homing attribute you're talking about. That is already available in the database.

**Comment by GregSCooper2514** [comment]
No, I am talking about the thing that anthicus, quell and disrupt fires, that will follow your mouse cursor
