### ISSUE TITLE
Neoplasm in Waves/Tsunamis

### ISSUE THREAD

**Issue by Aiden910** [Anuken/Mindustry-Suggestions#3785]
### Describe the content or mechanics you are proposing.

I have made a similar suggestion before in regards to Arkycite in Waves/Tsunamis, and it is a similar story here. I propose the addition of using Neoplasm in Waves/Tsunamis.

Potential stats in a Wave could be:
- 0.55 Knockback
- Carcinogrowth

Potential stats in a Tsunami could be:
- 0.2 Damage
- 1.3 Knockback
- Carcinogrowth

Carcinogrowth could be:
- Speed Multiplayer 85%
- Damage 6/sec
- Affinities:
- - Wet: 30 damage/sec
- - Spore Slowed: 12 damage/sec
- Opposites:
- - Freezing

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The only reason this is being suggested is because it gives more freedom/customization/options to map designers/custom map players; there is no other real reason.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
I have a feeling that if you allow the direct weaponization of what’s meant to be a dangerous byproduct, it could ruin balancing.
———————————
Look at arcs. They use a lot of energy for their damage. It’s balanced that way. However, being able to take what’s meant to be a dangerous and risky liquid, and turn it into a weapon seems simply broken. Free energy and defenses.

**Comment by OnyxFinger** [comment]
Neoplasm is meant to be a waste. It would make sense, from a logical standpoint to try and throw it at your enemies, but from a gameplay standpoint, it gives a use to something that is meant to be useless.
I still think this idea could be used, because relying on guns to get rid of your waste mostly inconsistent, and would require another way of dumping the neoplasm.

**Comment by lokyinng** [comment]
fire should be also a opposites

**Comment by lokyinng** [comment]
but that would be useful at destroying enemy water storage
