### ISSUE TITLE
Hjson alternatives

### ISSUE THREAD

**Issue by Evo04Taser** [Anuken/Mindustry-Suggestions#3787]
### Describe the content or mechanics you are proposing.

Basically means that anything and everything you can do in java and JavaScript is possible on hjson. (and then some of you will say: iTs bCuz youRe dUmb aT cOding cLose tHis isSue aNd cOpe)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Better for me and others who has (almost) zero experience at coding

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Evo04Taser** [comment]
I already know how this goes....

**Comment by Evo04Taser** [comment]
wEll iT maKes jaVa and jaVasCriPt uSeleSs

**Comment by itcannotbe** [comment]
Actually, you telling the dev to make a programming language. How do you even manage not to think this through.

**Comment by Evo04Taser** [comment]
> Actually, you telling the dev to make a programming language. How do you even manage not to think this through.

So, I'm telling the dev to make a programming language? I mean it's not like YOU can use it to create an app or a game

**Comment by Evo04Taser** [comment]
> Actually, you telling the dev to make a programming language. How do you even manage not to think this through.

So I'm telling the dev to make a programming language? IM FORCING HIM?

**Comment by Evo04Taser** [comment]
You all just ruin my parade and say; ITS IMPOSSIBLE CLOSE THIS ISSUE AND FUCKING COPE

**Comment by IxGamerXL** [comment]
> You all just ruin my parade and say; ITS IMPOSSIBLE CLOSE THIS ISSUE AND FUCKING COPE

I get it, @itcannotbe can be a b***h most times, but quite honestly seeing how his side here is reasonable enough, a game dev making a whole programming language for this one game is more daunting and less viable outside of the game than you learning JS or Java where you can use your knowledge for other things.

Whoever screwed up your previous issue were likely the typical gaslighters of the repo. Don't have them crap on your issue, cause they like doing that to others, including mine back then.

**Comment by IxGamerXL** [comment]
Also with further research, SMOLKEYS was basically trying to make you angry by constantly telling you to "cope". If anything, SMOLKEYS needs to cope, leave the repo, and maybe even go outside for once.

Him going berserk on your previous issue just because his head lit on fire was not a valid reason, let alone a permit to spam half the issue thread with bs.

**Comment by l-Luna** [comment]
Is the subject just "make hjson handle everything a programming language can"? because that necessarily requires expanding hjson into a programming language; except without editor support, worse implementation, and worse integration into the existing code than any other language you could use.

**Comment by Evo04Taser** [comment]
> Is the subject just "make hjson handle everything a programming language can"? because that necessarily requires expanding hjson into a programming language; except without editor support, worse implementation, and worse integration into the existing code than any other language you could use.

Did you just reply thinking you can use it? DID I SAY "MAKE IT A PROGRAMMING LANGUAGE"!?

**Comment by itcannotbe** [comment]
> > Is the subject just "make hjson handle everything a programming language can"? because that necessarily requires expanding hjson into a programming language; except without editor support, worse implementation, and worse integration into the existing code than any other language you could use.
> 
> Did you just reply thinking you can use it? DID I SAY "MAKE IT A PROGRAMMING LANGUAGE"!?

Yes, yes you did.

To qoute:

> Basically means that anything and everything you can do in java and JavaScript is possible on hjson.

**Comment by itcannotbe** [comment]
How does copying what **anything and everything** a programming language can do, NOT MAKE IT ANOTHER PROGRAMING LANGUAGE?

**Comment by Evo04Taser** [comment]
@itcannotbe Shut up bitch 💩💩

**Comment by markozajc** [comment]
yes mlog mods very good and sane idea

**Comment by b1tt0** [comment]
if you have 0 coding experience and want to make mods then it is probably time to get some of it

**Comment by gorodmi** [comment]
🧟
