### ISSUE TITLE
New formations for RTS control mode

### ISSUE THREAD

**Issue by Plastel** [Anuken/Mindustry-Suggestions#3794]
### Describe the content or mechanics you are proposing.

New tactical formations for RTS control mode, as example take the ones from Age of empires 2, there are 4 formations for units available there, like box (a protective box formation with the weaker units in the center), or flank(units are divided in two groups), or staggered(units are sepparated from each one, helping to combat area weapons 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it would be useful for tactical moves, like on the flank formation, you could attack with two fronts, or on the staggered formation, make area weapons (like scathe) less dangerous for your attack group

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by lokyinng** [comment]
yeah it need more formation
