### ISSUE TITLE
Remove war fog after the whole map permanent under control

### ISSUE THREAD

**Issue by Zhy54** [Anuken/Mindustry-Suggestions#3799]
### Describe what you would like changed, and why.

In Erekir , I think can remove war fog when a map finished , easy for following exploration and construction.The whole map will be lighter . Because this map is peace , don't need war fog and dark shadow anymore .

### Describe the changes you want to propose. Include possible alternatives.

Remove war fog after the whole map permanent under control

**Comment by OnyxFinger** [comment]
Funny how I was about to suggest this too. It would really be better having the whole map lit-up and not have to live in the dark.
