### ISSUE TITLE
Useless omura ability 

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3800]
### Describe what you would like changed, and why.

Omura ability to build flares is useless. These flares don't follow it and by the time you have omura you already have maximum flares

### Describe the changes you want to propose. Include possible alternatives.

Make it so omura has it's own flare limit or a new type of units. And make them follow omura

**Comment by OnyxFinger** [comment]
no but look it has to be this way so that there is an aircraft carrier in the game !! Yeah I'm just mocking this ability it's really pointless
