### ISSUE TITLE
Building like poly

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3801]
### Describe the content or mechanics you are proposing.

Add ability for the player to automatically rebuild broken blocks and restore their configuration like poly

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make repairing base much easier

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
> While it sounds very enticing it is kinda of troublesome and most important in my opinion a bit unbalanced as you would no longer need advanced tech (poly, not that advanced, but more advanced than the starting comm unit), maybe put this functionality on a building? At least now it is not something passive from the beginning?

This, it is supposed to be part of your progression that you get more and more tools to slowly automate your tasks, Polys being no exception.

While I think it sure would be _convenient_ to repair automatically from the beginning, I prefer the value of progression a bit more.
