### ISSUE TITLE
Arrays, formulas, and storage

### ISSUE THREAD

**Issue by Def-Try** [Anuken/Mindustry-Suggestions#3806]
### Describe the content or mechanics you are proposing.

Arrays, for storing data like strings(prob), ints and etc.
Formula operation - like operation, but we add multiple actions in a formula, so we domt need big constructions for just "sqrt(x1+x2*x3)"
Array cell - stores arrays, all strings in arrays will be replaced with 0 so we are not gonna store strings

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Arrays can be very useful for anything.
From:
```
a = sensor @copper in conveyor1
if a not 1 jump 0
b = sensor...
```
To:
```
a =  sensor allowed[i] in conveyor1
if a not 1 jump 0
i = i + 1
```
Why formula operations are needed explained higher

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Why would you need an array cell

A memory cell *is* an array
