### ISSUE TITLE
Planet Editor

### ISSUE THREAD

**Issue by CharlieGregg314** [Anuken/Mindustry-Suggestions#3809]
### Describe the content or mechanics you are proposing.

I know this would be difficult, considering the amount of planets in the game currently, but I would like there to be some sort of way to create your own campaign type map. Some way to connect maps in a way that makes sense, the only way I can think of this working, is a way to create planets. 

This could be made as simple as in V5, where there is not a planet-like structure, or more like what we have now. I think that it would be really cool to have a more complex generation system, where control flow is handled more like the logic blocks. This would allow for some of the complexities of the existing planets for randomised generation, while keeping it at the effort level of only a few sectors. 

This could be extended to creating solar systems. (probably not though) 

I believe you can get the idea from this, so I’ll stop here. (And I’m sure I’ve overlooked something simple and I’m wasting your time, so sorry about that.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently it takes me about 4 hours to make a really good map, and about 3 hours to play. If I could dedicate about only slightly more time to making a planet, then I could play it for a lot longer and get more out of it.

I would love the time playing to exceed the time spent creating.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by THEGAMER-10n** [comment]
Use java or javascript to do this.
