### ISSUE TITLE
9189 alfa, may be a bug with locations

### ISSUE THREAD

**Issue by Wencelsav** [Anuken/Mindustry-Suggestions#381]
just now I have Ice forest instead of start point. and during 2 turns I can not launch core 

![изображение](https://user-images.githubusercontent.com/31541176/89398328-a0ca7b00-d719-11ea-8553-06c13eaf5fed.png)
![изображение](https://user-images.githubusercontent.com/31541176/89398658-133b5b00-d71a-11ea-8ddc-f612c0473970.png)

**Comment by kingb74** [comment]
What part of its not finished dont u get
