### ISSUE TITLE
Liquid Cliffs

### ISSUE THREAD

**Issue by Aiden910** [Anuken/Mindustry-Suggestions#3811]
### Describe the content or mechanics you are proposing.

I propose the addition of a conditional cliff when placed on a liquid. This conditional clliff would in essence be a "waterfall", except, you know, it would be different depending on the liquid the cliff is on.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe this would add to the atmosphere of a good amount of maps and give a little bit more creative potential for mappers.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by hello-hello-there** [comment]
High fluid tiles: Where it goes down to the ground, it makes a waterfall and/or spills the liquid.
