### ISSUE TITLE
Optional mod reloading

### ISSUE THREAD

**Issue by Mnemotechnician** [Anuken/Mindustry-Suggestions#3812]
### Describe what you would like changed, and why.

The fact that you are forced to reload the game after editing the mod configuration (even if you've returned it in the original state afterwards) regardless of whether you did it purposefully or accidentally is frustrating. It's wasting our precious time, of which we don't have a lot, bringing us even closer to our death than we should be. 

Moreover, it often happens that i want to disable one of the UI, QOL or texture mods i have enabled, but then i remember that it will force me to reload everything, which is not something you want to do when you're messing with the console. I then decide to postpone doing this and end up forgetting about that until the moment i press the "exit game" button.

### Describe the changes you want to propose. Include possible alternatives.

Replace the "the game will now exit to reload mods" info dialog, whch is shown when you close the mods dialog, with a confirmation dialog like this:

<table>
    <tr>
        <td colspan=2 style="text-align: center">You must reload the game in order to apply the new mod configuration. 

Do you want to do it now?</td>
    </tr>
    <tr>
        <td>Later</td>
        <td>Now</td>
    </td>
</table>

**Comment by itcannotbe** [comment]
How about just a toggle you can access via console to stop automatic game start?

**Comment by OnyxFinger** [comment]
> How about just a toggle you can access via console to stop automatic game restart/reload?

I wouldn't mind a toggle, but do you really need to make in console accessed ? There could just be a button somewhere.

**Comment by itcannotbe** [comment]
> > How about just a toggle you can access via console to stop automatic game restart/reload?
> 
> I wouldn't mind a toggle, but do you really need to make in console accessed ? There could just be a button somewhere.

> Moreover, it often happens that i want to disable one of the UI, QOL or texture mods i have enabled, but then i remember that it will force me to reload everything, which is not something you want to do when you're messing with the console. I then decide to postpone doing this and end up forgetting about that until the moment i press the "exit game" button.

**Comment by OnyxFinger** [comment]
> > Moreover, it often happens that i want to disable one of the UI, QOL or texture mods i have enabled, but then i remember that it will force me to reload everything, which is not something you want to do when you're messing with the console. I then decide to postpone doing this and end up forgetting about that until the moment i press the "exit game" button.

Can't you just change that ? I mean maybe not, I'm clueless about this but it doesn't seem hard enough not to do it.

**Comment by Mnemotechnician** [comment]
> Can't you just change that ? I mean maybe not, I'm clueless about this but it doesn't seem hard enough not to do it.

You can make your own fork of mindus and do that little change here (it's a matter of one modified line), but keeping it up-to-date with the official builds is a pain in the ass.
