### ISSUE TITLE
Firefighting tsunamis/waves

### ISSUE THREAD

**Issue by MistahStealYoGril** [Anuken/Mindustry-Suggestions#3813]
### Describe the content or mechanics you are proposing.

There should be an option to have water tsunamis or waves to only shoot where there is fire, or where a friendly entity is burning or melting.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would remove the need for logic programming or it would make it easier to use other types of tsunamis.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Alternative Suggestion = #3814

**Comment by OnyxFinger** [comment]
This particular case of having to shoot and extinguish is too rare in the first place. The reason for this being that if your base is on fire, it's a skill issue. Literally. And by that I mean it's really not hard not to make a fire. And even if you do, a couple menders generally fix the issue.

**Comment by MistahStealYoGril** [comment]
But a new thing I have become fond of doing is using tar and slag. It just spreads to my walls and menders aren't always enough to stop the fires from damaging everything.
