### ISSUE TITLE
Change Targeting Priority of Title Liquid Shooting Turrets. Alernative to #3813

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3814]
### Describe what you would like changed, and why.

Change the priority of liquid shooting turrets to have a turret that will always try to extinguish fire.

### Describe the changes you want to propose. Include possible alternatives.

Wave = Prioritizes Fires
Tsunami = Prioritizes Enemy Units

**Comment by OnyxFinger** [comment]
You just made a near duplicate purposefully. Couldn't you have stated this in #3813 ?
Anyway here is some criticism : After the early game, fire really doesn't deal much damage, but water waves can be useful combined with the shocked effect. Why would I want to extinguish before debuffing ? Plus, this particular case of having to shoot and extinguish is too rare in the first place. The reason for this being that if your base is on fire, it's a skill issue. Literally. And by that I mean it's really not hard not to make a fire. And even if you do, a couple menders generally fix the issue.

**Comment by MistahStealYoGril** [comment]
> You just made a near duplicate purposefully. Couldn't you have stated this in #3813 ? Anyway here is some criticism: After the early game, fire really doesn't deal much damage, but water waves can be useful combined with the shocked effect. Why would I want to extinguish before debuffing? Plus, this particular case of having to shoot and extinguish is too rare in the first place. The reason for this being that if your base is on fire, it's a skill issue. Literally. And by that I mean it's really not hard not to make a fire. And even if you do, a couple of menders generally fix the issue.

Fair but it isn't always firefighting in the base. Mainly if your making pyratite for ammo and a horizon or flare just destroys a conveyor, it would burn down the blocks and maybe even spread even further. It's needed so the fire can be controlled.

**Comment by MistahStealYoGril** [comment]
And if I were to use it in my defenses, I would be sure the wave only has my things in range.

**Comment by OnyxFinger** [comment]
> Fair but it isn't always firefighting in the base. Mainly if your making pyratite for ammo and a horizon or flare just destroys a conveyor, it would burn down the blocks and maybe even spread even further. It's needed so the fire can be controlled.

That... is fire fighting... in the base... You make a decent point here though, but once again, that situation is rare, you can just place the wave once you need it.
