### ISSUE TITLE
All of the conveyor belt items, overflow gates, sorters, etc, but for liquids

### ISSUE THREAD

**Issue by yoyo149** [Anuken/Mindustry-Suggestions#3815]
### Describe the content or mechanics you are proposing.

All of the conveyor belt items, overflow gates, sorters, etc, but for liquids

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will allow people to create better systems for liquids

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
Who uses one pipe for multiple liquids?

**Comment by yoyo149** [comment]
That's not the point, it's being able to divert one liquid supply to multiple sources, plus, the only reason you can't do that is because of the lack of sorters.

**Comment by itcannotbe** [comment]
> That's not the point, it's being able to divert one liquid supply to multiple sources, plus, the only reason you can't do that is because of the lack of sorters.

Nope, the reason you can't do that is that liquid transport is not meant and is not coded to transport multiple types of liquids at the same time.
Liquids are not Items.

**Comment by yoyo149** [comment]
Ok, but I still think that the current stuff we have is underwhelming, maybe if it gets different logic, like a smart tank that can detect what's in it for logic purposes?

**Comment by itcannotbe** [comment]
> Ok, but I still think that the current stuff we have is underwhelming, maybe if it gets different logic, like a smart tank that can detect what's in it for logic purposes?

Can't you already do that?

**Comment by yoyo149** [comment]
I don't, think so, though I could be wrong.

**Comment by hello-hello-there** [comment]
Everything but the sorters makes sense.

**Comment by hello-hello-there** [comment]
Actually, leave in the sorters, I'm sure some logic madperson will use them somehow.

**Comment by yoyo149** [comment]
The main one is the overflow and underflow gates, for when using the item turrets, (can't remember their name) as it could lead to an inconsistent liquid source, which is why I created this request in the first place.
