### ISSUE TITLE
Research in non-campaign

### ISSUE THREAD

**Issue by Dwal32s** [Anuken/Mindustry-Suggestions#3816]
### Describe the content or mechanics you are proposing.

Adding the research ability as an **option** for custom maps, perhaps with reduced costs as usually you don't spend as much time in standalone attack/pvp/survival maps as you do in any campaign map. Alternatively use a research cost multiplier, similar to the build multiplier, instead of hand tailoring each research node twice.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This could make longer, more dynamic pvp or attack maps, instead of having a mostly static set of blocks available to the player during the entire session.
Could also prevent rushing if research is enabled, as players wouldn't have higher tier units available right away despite having the resources to build them.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RebornTrack970** [comment]
That does look like a good suggestion, but it would be better to be able to set what can be researched and their cost from the Rules menu like you you set waves.

**Comment by code-explorer786** [comment]
Good suggestion! Would be better if custom maps have custom research trees.
