### ISSUE TITLE
Purple Air Units

### ISSUE THREAD

**Issue by RFAC-Productions** [Anuken/Mindustry-Suggestions#3817]
### Describe the content or mechanics you are proposing.

I'ma be humble and say there are probably better ideas out there that can easily be coded in. That said, there are three unit classes and three unit types for Serpulo. Note this only applies to Serpulo as Erekir is a different planet. And note that I refer them as Classes and Types.

Classes:
Ground (Dagger, Nova, Crawler)
Air (Flare, Mono)
Naval (Risso, Retusa)

Types:
Red: Ranged (Dagger, Flare, Risso)
Green: Energy (Nova, Mono, Retusa)
Purple: Either Special or Melee (Crawler)
Not knowing what Purple is meant to be, I will just refer to that type as "Purple."

There's only one Class of Serpulo units that uses the Purple Type, and it's the Ground units via the Crawler Branch. Air and Naval don't have a purple branch of their own. Here is my concept for a Purple Type Air Unit

T1: Rod
Name Origin:
Lightning Rod
Purpose:
It's a tank unit, taking in attacks from Energy units and converting the damage into a buff field, buffing the shield of your units, and it can also cause the Electrified buff to your units. It also acts as a weak barrier against Ranged units, even with piercing.

T2: Cloud
The name origin:
A reference to CC or Cloud-to-Cloud Lightning, which when occurs, lightning strikes a different cloud.
Purpose:
It's the type of unit that you have to make an army of, because the damage multiplies the more there are of said units, hence why it's called Cloud. They can shoot out small arcs of lightning.

T3: Nimbus
Name Origin:
References and is short for Cumulonimbus Clouds, the type that shoots out lightning
Purpose:
It does what you think does, shoots medium sized lightning strikes. It's slow in terms of fps. But it's a heavy hitter against units that are T1 T2 or T3. But it's weal against T4 and T5 units.
(This one's underdeveloped)

T4: Ohm
Name Origin:
References Ohms, a unit which counts Electrical Resistance.
Purpose: 
Now this, is what you call a tank. It is more powerful than a Rod, being able to take a lot of damage, maybe even more than Reign, and can fire a laser once taken enough electrical and laser damage. It can also charge energy the more it moves, but to balance it out, it's a slow charge for a medium-speed air unit.

T5: Tesla
Name Origin:
Reference to Nikola Tesla, the Pioneer of the Application of Electricity.
Purpose:
This one's a heavy hitter, able to fire 3, large lightning strikes, 1 that shoots out to where you're aiming, the other 2 hitting a random target, dealing good damage. And it has a special ability: it's a Crawler factory, able to make 2 Crawlers like how Omura can make 4 Flares.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add more variety and gameplay to Mindustry, allowing players to explore new options on how to approach enemy bases or how to defend their sectors. There are some things in this suggestion that needs to be refined, and ultimately I think we're past the point where there could be more Serpulo conten so you can choose to ignore this. It's your choice, I thought it'd be an interesting read and a, at best, average idea.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by hello-hello-there** [comment]
Well done.
Don't forget purple water units!

**Comment by JP16D** [comment]
Actually your incorrect about the unit co.or coding it should be like this:

Red: Light Combat Units(lower tier), Heavy Combat Units(higher tier)
Green: Support Units, combat capable variants prioritizes disruption of enemy generators and power lines 
Purple: Infiltration Units, they prioritizes clearing a path and shifting enemies focus to them to give way to other units, in reality they're to op

This also kinda applies to the 2 new serpulo units which is the tank units(red), ship units(purple) the newest lightblue unit color type is still pretty much unknown but I would guess they're a hybrid of purple and green units being that they can go through defenses but somehow prioritizes power lines

I would say a more fitting purple unit is an extreme long range unit or something similar to crawler tree which are units that either clears a path acts as diversion or boes through your defenses, for your suggestion unit might be fitting for the new lightblue type
