### ISSUE TITLE
Mod things

### ISSUE THREAD

**Issue by sussyamogusimposter** [Anuken/Mindustry-Suggestions#3818]
### Describe the content or mechanics you are proposing.

Config option in mods

Reason: It would be super helpful and not time consuming for modders to make a makeshift config in the settings

Better HJson and Json support for mods

Reason: HJson/Json mod's can't use items from their own mod and have to use vanilla materials as with JS or Java you can do whatever you want

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Overall make the modding and mod experience better. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Because with H/JSON mods, you aren't codding in anything, in essence your just writing a configuration file that changes the characteristics of the thing you are trying to mod, unlike JS or Java where in you can program/code in the thing you want.
