### ISSUE TITLE
Multiplayer planet

### ISSUE THREAD

**Issue by JakeHasSkill** [Anuken/Mindustry-Suggestions#3819]
### Describe the content or mechanics you are proposing.

So the campaign planet is very fun, although it is mostly just single player. My idea is a way to host a planet on a dedicated server instead of just one game, and players face each other instead of the AI. When a player joins they could see the planet and are launched to a random spot, and launch to adjacent sectors to expand and find other players.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this would make multiplayer a whole new experience, it could be a more long-term adventure with your friends rather than just a few battles on single maps. This could also be a way for friends to play together if they are on at different times, since it could be a dedicated server and progress would save.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This goes to the pile of suggestions that basically suggest to host the whole planet.

**Comment by hello-hello-there** [comment]
A new mode of custom or server-hosted games?
