### ISSUE TITLE
Surge alloy bullet new ability

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#382]
**Describe the content or mechanics you are proposing.**
Instead of producing electricity arcs, turrets fed with surge alloy will stun enemies for a duration inverse proportional to their HP. ~Multiple stun shots hitting the same enemy add to the stun duration.~ _might be a bit OP, crossed out in edit_ AoE damage from the bullets inflicts a lesser stun.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Surge as ammo currently is kind of useless, and does way worse than plast despite being considerably harder to make. And so, it should get a buff.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
surge is also outperformed by blast compound

**Comment by itcannotbe** [comment]
Alternative: Instead of a stunnwould be too op then just make the unit stop shooting for a while.

**Comment by Ilya246** [comment]
Alternative 2: Instead of stunning, make it slow; Might need to be able to stack for it to be effective
