### ISSUE TITLE
Banned Units Change

### ISSUE THREAD

**Issue by Daconus** [Anuken/Mindustry-Suggestions#3820]
### Describe what you would like changed, and why.

I feel like the banned units should be able to be made, just have a unit limit of 0 so that you can still build higher tier units.

### Describe the changes you want to propose. Include possible alternatives.

Banned units should be able to be built, but have a unit limit of zero and cannot be released from payload blocks.

**Comment by itcannotbe** [comment]
This should be only the case if the next block is another reconstructor.

Otherwise it would be another way to bypass the rule.

**Comment by end-me-please** [comment]
isn’t this already the case
