### ISSUE TITLE
Campaign Saves

### ISSUE THREAD

**Issue by maxsfriend12** [Anuken/Mindustry-Suggestions#3821]
### Describe the content or mechanics you are proposing.

Different saves for campaign

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Shared computers wouldn't have to have a singular campaign for them to play, and it would be easier to manage.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Don't you have the option of export and importing saves already? Just making a UI for "hot swapping" them would work.

**Comment by Taitep** [comment]
> Don't you have the option of export and importing saves already? Just making a UI for "hot swapping" them would work.

That is for custom game saves and not campaign.

**Comment by Taitep** [comment]
Another good thing would be research stored per campaign save, not player.
If you have been playing campaign for a while but not completed it and then wanna show someone new to the game you basically need too make sure yourself that you do not use something later in the tech tree.

**Comment by hello-hello-there** [comment]
Yeah: Campaign save files should be organized in folders, with campaign info as a separate doc. Should be fairly easy, as it is just moving files around.
