### ISSUE TITLE
Unit loader

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3822]
### Describe the content or mechanics you are proposing.

Make payload loader put items into unit inventory

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Load units with explosive items to make them more dangerous

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RFAC-Productions** [comment]
I like this
Why isn't this a feature yet?

**Comment by hello-hello-there** [comment]
Auto bombs on legs: Blast Compound crawlers.
