### ISSUE TITLE
Let processors rotate blocks

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3825]
### Describe the content or mechanics you are proposing.

Let processors change block rotation

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Very compact multi level unit factories

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Can't you already accomplish this by controling a unit then using it to rotate the block?

**Comment by hello-hello-there** [comment]
@itcannotbe It's still useful. How? Idk. I'm sure someone will think of something.

**Comment by RouterChainsSuckk** [comment]
> @itcannotbe It's still useful. How? Idk. I'm sure someone will think of something.

You already can via controlling units to rotate for you, having processors directly controll movement makes no sense
