### ISSUE TITLE
Tall map tiles.

### ISSUE THREAD

**Issue by GabrielX24** [Anuken/Mindustry-Suggestions#3826]
### Describe the content or mechanics you are proposing.

A feature to the map editor, a tile that is impassable to air units and to every kind of projectile, laser, explosions, etc. the sprite could be something like the one of the cliff, and could be placed over any solid block. To make it "tall". Alternatevely, there could be an option to make every solid block be tall

_forgive me for my informal english, im not an english native speaker_

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it would give much more freedom to challenges and small attack maps. For example, i built an erekir map some time ago that to destroy a certain core you had to launch mechs over a wall using payload launchers. But i was dissapointed when i saw someone just sniping the core with a titan turret. And these tall tiles could easily be a fix to something like this, beside just placing the core really far, which isnt really an option with the scathe turret

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
It will break air unit logic
