### ISSUE TITLE
Payload mass conveyor begin

### ISSUE THREAD

**Issue by RealWetter** [Anuken/Mindustry-Suggestions#3828]
### Describe the content or mechanics you are proposing.

Begin of an payload mass conveyor capeble of leting unit go padfing in to payload mass drivers to make more padvinding poseble

(Sorry i cant spell,
and i hope i dit this under they richt place)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Padvinding of units trough mass conveyors or drivers

[Its maybe an hard one]

(I cant spell)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealWetter** [comment]
This is not an issue it was under sugjession so...

**Comment by OnyxFinger** [comment]
I never realized there was a difference between an issue and a suggestion
Guess I'm an idiot then

**Comment by RealWetter** [comment]
Lol i have alot of bugs to teport i tink
