### ISSUE TITLE
Add скат as unit

### ISSUE THREAD

**Issue by Mak992** [Anuken/Mindustry-Suggestions#3829]
### Describe the content or mechanics you are proposing.

Add скат with actual tail as secret unit

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Скат is the perfect state of unit and an ideal esthetic creature. It must exist

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by hello-hello-there** [comment]
Cat? Or what?

**Comment by Mak992** [comment]
> Cat? Or what?

Скат

https://user-images.githubusercontent.com/65508800/185237038-806b1130-a237-4aae-b1df-f87c6cc0a8de.mp4

**Comment by KayyAyeAre** [comment]
it lost the war

**Comment by OnyxFinger** [comment]
but why tho

**Comment by Mnemotechnician** [comment]
ckat has already been a part of the game, it hides deep in the bottomless oceans of tantros

long live the ckat republic!
