### ISSUE TITLE
Deep Water should provide additional water for pumps placed on them.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#383]
**Describe what you would like changed, and why.**
Deep water has restrictions on them, why not make it more useful

**Describe the changes you want to propose. Include possible alternatives.**
A boost of 3x for pumps on them.

**Comment by Ilya246** [comment]
3x might be too much, 1.5x maybe?

**Comment by DeltaNedas** [comment]
may try implementing this soon

**Comment by DeltaNedas** [comment]
2x as a middle ground

also i believe it will allow 3 deep water and 1 oil in the right spot to produce a stupid amount of oil with a rotary pump

**Comment by itcannotbe** [comment]
Closing since related pr has been merged.
