### ISSUE TITLE
Bring Back Old Planet Sector Icon

### ISSUE THREAD

**Issue by el-ang** [Anuken/Mindustry-Suggestions#3830]
### Describe what you would like changed, and why.

I was playing on Alpha Pre-Release and seek this.
![image](https://user-images.githubusercontent.com/64268522/185381691-689fea0f-f567-434b-b0d0-3ec8df894e35.png)
There were more icons available to mark sectors on planet at (Not Sure) v5 / v6 than the list available on current version. This is the back up save i just saw when I reinstall the Pre-Release.
I use those icons to mark sectors back in the day as the back up save.
![image](https://user-images.githubusercontent.com/64268522/185381519-81b170e1-9192-4123-a958-957d6c2eb86a.png)
So I hope those icons could make it back so I can land mark some sectors based on my POV on marking map of the planet.

### Describe the changes you want to propose. Include possible alternatives.

Revert/change/bring back old icons list more than the new list on current version. Also maybe optimize list for the same look/copy of some icons.

**Comment by hello-hello-there** [comment]
Also add more types of markers
