### ISSUE TITLE
How the Latum could be implemented

### ISSUE THREAD

**Issue by pocket321** [Anuken/Mindustry-Suggestions#3833]
### Describe the content or mechanics you are proposing.

The Latum is a hidden unit in the game files. So I propose THIS

Renales will spawn at the enemy spawn point, even if the sector has been captured. Renales can bury through natural walls, teleporting to the other side. It pathfinds towards the nearest neo reactor, and if it touches it, it enters the reactor.
Each phase saps 20% neo and 33% energy
Phase 1: Takes 5 minutes to complete
Phase 2: Takes all excess material going into the reactor. Takes 5 minutes to 30 minutes depending on how much material is feeding it.
Phase 3: Takes 5/s liquid and 1 phase every second (this stacks with phase 2) and will burst out once no more material is feeding it.
Please note, the Latum cant bury through walls, cause it too fat

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it will make people more careful when making their schems and make people defend their neo reactors

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Better idea:
large concentrations of Neoplasm form into a Renale, large amounts of Renales can form into a Latum

**Comment by OnyxFinger** [comment]
Anuke probably has an idea in mind already.

**Comment by Cack101** [comment]
reepy unit,isn't it?
