### ISSUE TITLE
A serious bug with the world processor that seriously affects the game experience

### ISSUE THREAD

**Issue by one-Home-cat** [Anuken/Mindustry-Suggestions#3834]
### Describe what you would like changed, and why.

The world processor can be modified by the modified client in the server, so what is the use of it?

### Describe the changes you want to propose. Include possible alternatives.

1:
Add password protection to the world processor, need a password to access!Changing the connection building and changing the internal code requires a password
2:
Added option to map information rules: non-editable world processor for all modes (including map editor)

**Comment by Bottinator22** [comment]
Or just... make the server refuse changes to world processors? This doesn't need a complicated solution

Also this is a bug, not a suggestion

**Comment by one-Home-cat** [comment]
Haha, so it can also solve the problem!
I just tested it again and found that it can be changed but will not take effect and will not be saved! (The world processor code in the same color as the player's will be saved, but will not take effect)
I'm sorry, it's my fault! Doesn't seem to affect the game! I will close this question!
