### ISSUE TITLE
Unit bind

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3836]
### Describe the content or mechanics you are proposing.

Processor can remember units as variables. What if you could write that variable in bind instruction and bind this exact unit

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will allow processor to easily control several units without the time cost of switching. Right now you have to bind every unit to find a specific one

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SomeonesShade** [comment]
`@unit` is exactly what is being talked about...

`set unit1 @unit`
`set @unit unit1`

**Comment by Mnemotechnician** [comment]
> `@unit` is exactly what is being talked about...
> 
> `set unit1 @unit` `set @unit unit1`

that's not how it works, `set @unit`ing is utterly useless.

**Comment by SomeonesShade** [comment]
My bad, i thought its alright, but it gets noop'ed


although ubind unit1 is in the game already
