### ISSUE TITLE
Show ammo consumption type when selecting turret

### ISSUE THREAD

**Issue by biox** [Anuken/Mindustry-Suggestions#3838]
### Describe the content or mechanics you are proposing.

Currently, in order to see the ammo type of a turret, you must click the question mark, which I find kind of slow. I'd prefer the ammo types to be listed in addition to the construction materials when the turret is selected in the build menu.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that it will help with onboarding, since new users don't know which turrets consume which ammo types.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Learning curve moment, also after a day's worth of playing, this will just be additional screen clutter.

**Comment by biox** [comment]
Why display resource costs then, since you could use the same argument? I don't see anything wrong with adding a tiny amount of helpful screen clutter since people who are good at the game just press hotkeys anyways & probably won't spend time hovering over icons.

**Comment by zenraged** [comment]
This is an excellent feature request. I've been searching all over for a mod that can do this. I've been playing Mindustry for years and can never remember what ammo type turrets use. This idea should be re-opened and seriously considered.

When hovering over turrets it would be awesome to see the little icons of the materials that turret uses for ammo and liquid.

**Comment by itcannotbe** [comment]
![Image](https://github.com/user-attachments/assets/40f65965-a1da-47e0-ab12-8e85491ef0ff) exists for a reason.

Also necro.
