### ISSUE TITLE
Bullet feature

### ISSUE THREAD

**Issue by Pixeltech285** [Anuken/Mindustry-Suggestions#3839]
### Describe the content or mechanics you are proposing.

I think it would be interesting to at a bullet conversation feature, for example, you can either use regular copper, or copper that has been put through a machine that comverts the copper into something like "Copper ammunition" and the stats would increase slightly, like 1.2x firerate, 3x ammo and +5 damage to base damage, it would take power to manufacture the input items into there ammunition variant, but I think it would be worth it in the long run.

The second thing I would suggest, a research tree, but not like the standard one that's current, but one that can let you research things like mine speed, unit health, damage, and conveyor speed, however, this research tree is independent to each sector, so it will reset on every core launch

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The ammunition suggestion would offer players a choice, do they sacrifice power to run things like arc turrets or parallax to produce superior ammo for Salvo or Ripple, or still with standard ammunition, and it would make the late game just a tad easier 

Research tree would aid in single player campaign mode and would make things a tad easier to manage in sprawling sectors

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
Do you know Java? JavaScript? Json? We need YOU to make a mod that does this

**Comment by Pixeltech285** [comment]
> Do you know Java? JavaScript? Json? We need YOU to make a mod that does this

I unfortunately have zero coding skills, but if I did, I would totally make a mod for this
