### ISSUE TITLE
Mass (d)river for liquids

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#384]
**Describe the content or mechanics you are proposing.**
Mass driver, but for liquids.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently pumps are useless because of the amount of space conduits take. A liquid mass driver should make pumps be used way more.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
But conduits have a high enough throughput already....

**Comment by Ilya246** [comment]
They do, but they take up too much space

**Comment by zethnest** [comment]
Placing a lot of phase water bridges will make them take like 2 spaces.

**Comment by MapleWheels** [comment]
Right now fluid transport is limited by the pumps/output devices rather than the conduits themselves.

**Comment by RoyalFunnyDude** [comment]
though it is kinda annoying to have to direct conduits through half of the map just b/c the space beside the liquid source is taken by other things...so i guess it would be convenient?

**Comment by itcannotbe** [comment]
@MapleWheels actually (conduit) bridges are the slowest transport method currently.

**Comment by MapleWheels** [comment]
> @MapleWheels actually (conduit) bridges are the slowest transport method currently.

They're almost as fast as Pulse Conduits and you can stack 4 of them on top of each other. They're fine.

**Comment by itcannotbe** [comment]
They aren't. For their use case you can't expect for a sane person to stack them to get over an obstacle.

**Comment by potatoisagender** [comment]
what is the approximate fluid transport of the different conduits, including bridges, junctions, tanks, and routers?
