### ISSUE TITLE
e-unloader should be able to be used on core!!!!!!!!!!

### ISSUE THREAD

**Issue by starstrip18** [Anuken/Mindustry-Suggestions#3840]
### Describe what you would like changed, and why.

e-unloader should be able to be used on core!!!!!!!!!!
for an easy example
after my silicon is produced,i can ues it to build units,or send into the core and then build buildings
but if i just send it into the core which most players would do, i can only use it to build buildings
it shouldn't be on a RTS game!!!!!
it's just because e-unloader can't be used on core!

### Describe the changes you want to propose. Include possible alternatives.

e-unloader should be able to be used on core!!!!!!!!!!

**Comment by OnyxFinger** [comment]
You can use routers, overflows/underflows and a healthier base design.

**Comment by Neil2101** [comment]
what tf is a E-unloader?

**Comment by Mnemotechnician** [comment]
> what tf is a E-unloader?

erekir's duct unloader, probably

**Comment by starstrip18** [comment]
> 

yes

**Comment by itcannotbe** [comment]
Erekir has different block mechanics, if you still feel the urge to use core based schems, stick to serpulo.

**Comment by itcannotbe** [comment]
On a different note:

~Make power beams be able to connect to a building regardless of angle~

See how absurb the request is.

**Comment by Funny132** [comment]
Erekir is designed to be a different planet with a whole new gameplay experience, keeping only certain features the same and changing up almost everything else. On Serpulo, a lot of people just cheesed their way through large parts of the campaign via things such as unloading resources from the core, or launching with an already built up core schematic. Erekir requires to to be flexible and produce your own resources on the sector, and unloading items from your core is pretty much just undermining all of that, so I can see why Anuken decided not to implement it in the current release. Besides, how hard is it to connect your Silicon Smelter up to a Unit Factory? Seriously, it's literally as simple as a duct router on both production lines of the resources you need.
