### ISSUE TITLE
Landing variations 

### ISSUE THREAD

**Issue by Josue8768** [Anuken/Mindustry-Suggestions#3841]
### Describe the content or mechanics you are proposing.

Make it so when you land in a sector you will land in different locations on the map everytime.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If the cores were to spawn with blocks, this feature could make these bases look slightly better.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
This is a thing already a thing in many maps. From there one can easily assume that Anuke didn't add more locations by choice (it's not hard to do).

**Comment by itcannotbe** [comment]
I think it's more complicated than that, since the map file is essentially a glorified game save file.
