### ISSUE TITLE
queue system add more options

### ISSUE THREAD

**Issue by IFRFSX** [Anuken/Mindustry-Suggestions#3842]
### Describe the content or mechanics you are proposing.

1. For flying army units similar to T3 green units, please add a module for switching between "walking" and "flying" in the control options.
2. Please allow players to order their units to surround themselves and let them follow their actions (this does not mean restoring the old command system, just adding a command option similar to the old system)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

For raiding and bombarding deep inside enemy buildings, especially for those Army robots that can both fly and walk, it is important to move in tandem and flexibly with the player, which can greatly improve the player's gaming experience.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Well I think green tree units should automatically fly unless explicitely told not to. (maybe there would be a way to toggle off auto flight)

I might also add ; A way of making ground support units mine if they can.
