### ISSUE TITLE
Remove whitelist servers

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry-Suggestions#3843]
### Describe what you would like changed, and why.

# Currently public server list is really "public"?
I can't understand why the whitelist server is in public.
I tried to connect to any server to test the game, but it was blocked due to a whitelist.
Some server can't connect but listed.

### Describe the changes you want to propose. Include possible alternatives.

Remove servers from public server list.
If possible, you must notify the server owner.

**Comment by itcannotbe** [comment]
I thought vanilla compatible plugins are allowed?

**Comment by Kieaer** [comment]
@itcannotbe I read rules wrong. plugin is allowed
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/44261958/185862384-d9e7b255-2251-4580-9c04-727dca4d9114.gif)
