### ISSUE TITLE
atmospheric condenser

### ISSUE THREAD

**Issue by fghjk455rg** [Anuken/Mindustry-Suggestions#3846]
### Describe what you would like changed, and why.

I think it's the wrong decision to put an atmospheric condenser on the "production" tab. It uses natural resources, or to be more precise, it extracts nitrogen from the atmosphere. This is not a factory.

### Describe the changes you want to propose. Include possible alternatives.

Move the atmospheric condenser to the "extraction" tab.

**Comment by OnyxFinger** [comment]
Makes sense
I guess there is an argument that could be made which claims that they are factories because they turn heat into nitrogen, but cultivators take water, and yet they're extractors, same for oilex.
