### ISSUE TITLE
Balance of Menders / Mendprojectors

### ISSUE THREAD

**Issue by ShineDownOnYou** [Anuken/Mindustry-Suggestions#385]
In my opinion Mend Projectors are way to strong. 
Spamming them en mass makes your defense nearly invincible and very very hard for PvP Players to break through with units unless you create a ton of them and lag out every server.
For the standard survival maps you setup your defense and you can basicly go AFK for the next hours and wait until they maybe break through at some point
Overdrive Projector with Phase makes them just superior to everything else.
One of the reasons why they get used instead of Force Projectors.

**Describe the changes you want to propose. Include possible alternatives.**
What i heard from Discord
- Disable the overdrive-effect on them
- Disable the overlapping mend-effect similar to Overdrive Projector and buff the mend-effect a bit to balance it out again
- Optional buff the Force Projector in a way that makes them more usefull for defenses

**Comment by Ilya246** [comment]
In 6.0 units got a big buff, so this will be no longer the case
