### ISSUE TITLE
Better schemes menu

### ISSUE THREAD

**Issue by Maffialnor** [Anuken/Mindustry-Suggestions#3851]
### Describe the content or mechanics you are proposing.

The idea is to make schemes existing not in a list, but in folder list with them. That would be better, if folder can be created inside another folder at least 3 times. (Like "logic/defence/turrets/better turret controller.msch"

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

That will simplify scheme list and make it easier to use

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fabizocker456** [comment]
Ah yes, recycling suggestions

**Comment by Mythril382** [comment]
But tags already exist-

**Comment by itcannotbe** [comment]
Ah yes another schematic folder suggestion, didn't anuke added tags instead of this?

**Comment by Maffialnor** [comment]
Tags not this convenient to use actually

**Comment by itcannotbe** [comment]
Tags are more convenient to use since you don't have to actually remember where you placed your schematic and allows them to be searchable using multiple search terms.
