### ISSUE TITLE
Add unit size limits to payload conveyors

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#3853]
### Describe what you would like changed, and why.

A lot of new players get confused about the payload conveyor unit size limits, and they are pretty vague, with some t4s allowed on the conveyor, and others not.
That's why I'm suggesting that the payload conveyor gets some extra info in it's description about what it can carry.

### Describe the changes you want to propose. Include possible alternatives.

Add "can carry tier 3 units, including [instert outliers here]." To the end of the payload conveyor's description.

An alternative would be making a display system like how reconstructors show what units they can build, though that would take longer than the above option.

**Comment by itcannotbe** [comment]
Or add the same info in each unit's info instead.
