### ISSUE TITLE
Alternative to world processors

### ISSUE THREAD

**Issue by VdobleMSG** [Anuken/Mindustry-Suggestions#3857]
### Describe the content or mechanics you are proposing.

Instead of having the world processing inside the world processors, I suggest to have a tab in the map info, where you can make separate blocks of logic. It would work exactly like the sandbox block but instead of having it in-game, it would display in the menu.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would improve by the fact of not ocuppying the map with the processors. You would have them all organized in a special tab, with no need of placing them in-game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WhyNotDogie** [comment]
rip this is a good suggestion
