### ISSUE TITLE
Launch Port

### ISSUE THREAD

**Issue by JP16D** [Anuken/Mindustry-Suggestions#3858]
### Describe the content or mechanics you are proposing.

A 5x5 payload block that can be set between [send] and [receive], a launch pad for payloads, if set to [send] it will accept payload inputs and launch it in certain interval to a target sector only if the target sector have a Launch Port set to [receive] that is empty, sending the payload to that launch port, if the block is set to [receive] it would output any payload it contains and wouldn't accept any payload inputs

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It allows sending units in captured sectors where materials or spsce for unit production is scarce and sectors that only relies in core for materials to create/upgrade units, it also lessens preparation time for captured sectors that is under attack from a nearby enemy base sector

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by KayyAyeAre** [comment]
why not have the sender and receiver be separate blocks?

**Comment by itcannotbe** [comment]
You do realize that launch pads or similar blocks doesn't exist in serpulo because passively making something to send to another sector makes the game extremely easy to cheese right?

**Comment by JP16D** [comment]
> You do realize that launch pads or similar blocks doesn't exist in serpulo because passively making something to send to another sector makes the game extremely easy to cheese right?

Do note that just like launch it only works in captured sectors, I do realize it could sound broken but if you think more throughly about it, just like all other payload blocks the receiving variant will not output the payload (unless there's payload conveyor to output iit out) if it's a unit that already reached it's unit cap clogging the mechanism and preventing further launches until its empty, also effectively the production time of that unit is still the same but is being made in another sector and iirc unit production buildings only run if the player is in the same sector + travel time from launch so it's lot more slower and ofc it should consume more energy than normal launch pads, it also is very inefficient if you think of using it for sending batch of materials with storage blocks compared to normal launch pad since it would require logic for it to work and even with that it's still would be slower than the launch pad even if they have the same launch rate

**Comment by JP16D** [comment]
> why not have the sender and receiver be separate blocks?

Nice Idea, but I really prefer the option of switch between the 2 modes than having 2 separate blocks much like how mass drivers also works in the same sense except that they're actively both a sender and receiver at the same time
