### ISSUE TITLE
Ability to disable mod descriptions

### ISSUE THREAD

**Issue by 0SomeOneRandom0** [Anuken/Mindustry-Suggestions#386]
A checkbox in the mods tab to disable descriptions, it would make life easier.

I feel like it would be way easier to navigate through the mod menu if it wasn't a wall of text

1. - [X]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Mod descriptions aren't displayed in the menu at all in the v6 mod browser.
