### ISSUE TITLE
Turret description

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3862]
### Describe the content or mechanics you are proposing.

Afflict description should mention its bullet trail and malign description should have laser modifier
And segment shouldn't be in turret folder because it's not a weapon. It should be in the same folder as force projector

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To be clear

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Erekir blocks descriptions are actually a work in progress.

Segment is actually a weapon, it shoots lasers to destroy bullets.

**Comment by Funny132** [comment]
> Segment is actually a weapon, it shoots lasers to destroy bullets.
I used the projectiles to destroy the projectiles

In all seriousness though, itcannotbe does have a point there, Segments are turrets in every sense of the word - they fire a projectile towards enemies to help defend your base. The Segment targets enemy projectiles and destroys them with their own lasers to defend your base against enemies. Additionally, it has the same colour palette, the same rotational mounted device system, and the same requirement of power as the rest of the energy-based turrets. So, yea, no, the Segment is staying where it is.

**Comment by mega2335** [comment]
> > Segment is actually a weapon, it shoots lasers to destroy bullets.
> > I used the projectiles to destroy the projectiles
> 
> In all seriousness though, itcannotbe does have a point there, Segments are turrets in every sense of the word - they fire a projectile towards enemies to help defend your base. The Segment targets enemy projectiles and destroys them with their own lasers to defend your base against enemies. Additionally, it has the same colour palette, the same rotational mounted device system, and the same requirement of power as the rest of the energy-based turrets. So, yea, no, the Segment is staying where it is.

y e s
