### ISSUE TITLE
ID for players on multiplayer 

### ISSUE THREAD

**Issue by Enderman664** [Anuken/Mindustry-Suggestions#3866]
### Describe the content or mechanics you are proposing.

One of the problems with multiplayer is the names, Players can give themselves any name they want, including names that are already used by other players, this creates confusion and can even get the wrong player banned.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Players should have a four digit ID so as not to confuse them no matter what name they have 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Phinner** [comment]
> - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

You have to be kidding.

> Players should have a four digit ID so as not to confuse them no matter what name they have

You do realize you can kick players with their entity id. You can get the list of players with their entity id by doing `/votekick` and kick them with `/votekick [id]`.

**Comment by end-me-please** [comment]
the uuid is literally one of the most important tools for server admins
