### ISSUE TITLE
The Fizzer/Shaker

### ISSUE THREAD

**Issue by pocket321** [Anuken/Mindustry-Suggestions#3868]
### Describe the content or mechanics you are proposing.

The Fizzer in a nutshell basically mixes a gas and a liquid. The Shaker does the opposite, outputting to the left and right. (Erekir)
Fizzer
General
Health: 750
Size: 2x2
Build Time: 3.46 seconds
Build Cost: 20G 100B 60S 100T 20P
Power
Power Use: 40
Liquids
Liquid Capacity: 10
Input/Output
Input:O&W C&W N&W O&A H&A N&A
Output:OW CW NW OA HA NA

Shaker
General
Health:300
Size:1x1
Build Time:1.02 seconds
Build Cost: 30G 20S
Power
Power Use: 10
Liquids:
Liquids Capacity: 30
Input/Output
Input:Aerated liquid (see above)
Output: Said gas and liquid

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It can allow people to transport more compact liquids, and will change how people transport liquids and gases together

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RFAC-Productions** [comment]
Erekir Soda

**Comment by OnyxFinger** [comment]
> Erekir Soda

yeah
I would like a slagbull please, maybe with some oila-cola.

**Comment by Breadyboi69** [comment]
Rip to erekir soda

**Comment by WhyNotDogie** [comment]
rip oila cola
