### ISSUE TITLE
maltiplay

### ISSUE THREAD

**Issue by aleph-42** [Anuken/Mindustry-Suggestions#3869]
### Describe the content or mechanics you are proposing.

I am Japanese.I used Google Translate to send it, so there may be some strange parts.It's quick, but can't we simplify multiplayer?I don't know how to open ports.I can't find it even after looking it up on the internet So I want you to be able to play multiplayer without opening ports.Is it possible?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If there is no port opening procedure,It makes it easier for us to play multiplayer with friends.If it becomes easier to play multiplayer, Making multiplayer easier means more people will play this game.That's why I want multiplayer to be easy.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The steam version is there, you just have to buy it.
