### ISSUE TITLE
Add the ability to go back to your map in the editor.

### ISSUE THREAD

**Issue by ajd07** [Anuken/Mindustry-Suggestions#387]
**Describe the content or mechanics you are proposing.**
In the editor, you can go into a black void, or in other words considered out of bounds, and in this state it's extremely hard to find where your map is.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make map maker's lives easier since they don't have to restart Mindustry to start mapping again, as this makes mapping pretty annoying for me, and potentially others.
![mindustry](https://user-images.githubusercontent.com/69254409/89589703-bfa93a00-d80b-11ea-847a-4c573cf00831.PNG)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by zethnest** [comment]
The button should be named "Center to map"
