### ISSUE TITLE
erekir units should fire not copper

### ISSUE THREAD

**Issue by sheptalo** [Anuken/Mindustry-Suggestions#3870]
### Describe what you would like changed, and why.

erekir units use copper as ammo
![2022-08-26_22-20-56](https://user-images.githubusercontent.com/104015580/186976693-75c31db1-3b5a-432d-a695-d31774778dd8.png)

### Describe the changes you want to propose. Include possible alternatives.

i think they need use alternative ore as a ammo

**Comment by Bottinator22** [comment]
Think this is more  of a bug than a suggestion, but copper's just the default ammo
