### ISSUE TITLE
Additional death animation for tanks

### ISSUE THREAD

**Issue by FreezeCactus** [Anuken/Mindustry-Suggestions#3873]
### Describe the content or mechanics you are proposing.

In real life, if you blow up a tank's ammo, it explodes and rips the turret off the tank's hull. Maybe it could be added to the game as a death animation for tanks that has a low chance of happening? Like 1% or something.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that would be a nice visual detail.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
More real doesn't mean more good.

**Comment by OnyxFinger** [comment]
You sent the same suggestion twice, be more careful next time.

**Comment by Pixeltech285** [comment]
I think that would be really cool!!!

**Comment by mega2335** [comment]
Idk, i guess
