### ISSUE TITLE
PayTakeblocks

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3874]
### Describe the content or mechanics you are proposing.

PayTake should be able to take blocks. Or PayBlockTake?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Taking and transporting blocks, like thorium reactors. Why can't logic do it? Is that so hard to make PayTake work like player controls without adding some weird setting of how many units to take, making blocktaking impossible 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
PayTake can pick up blocks tho...
just make sure there aren't random units around the block you're trying to take

**Comment by Bottinator22** [comment]
I am also talking about logic, I actually made a logic thing that makes
quads pick up and load thorium reactors out of a constructor, before
constructors became Erekir only
