### ISSUE TITLE
World Processor in Sandbox

### ISSUE THREAD

**Issue by JP16D** [Anuken/Mindustry-Suggestions#3876]
### Describe what you would like changed, and why.

The world processor runs in-game but can only be placed in edit mode currently

### Describe the changes you want to propose. Include possible alternatives.

World processor should be a sandbox mode block

**Comment by Phinner** [comment]
It's on purpose mate, world processors have too much power, even for sandbox.

**Comment by end-me-please** [comment]
this would mean that unprivileged sandbox players in multiplayer can crash servers

**Comment by THEGAMER-10n** [comment]
> this would mean that unprivileged sandbox players in multiplayer can crash servers

Then ban the block

**Comment by Phinner** [comment]
> > this would mean that unprivileged sandbox players in multiplayer can crash servers
> 
> Then ban the block

But it's not about banning the block, it's about the design of the block.
World processors were never meant to be used directly in-game, only for map scripting like Anuke said.
Don't forget they can place/destroy blocks, modify the game rules, placing text labels, etc.
So yes, making it only available as a editor block is better and safer than just banning it.

**Comment by Shidoengie** [comment]
Then maybe limit it to only single player sandbox

**Comment by Shidoengie** [comment]
> > > this would mean that unprivileged sandbox players in multiplayer can crash servers
> > 
> > 
> > Then ban the block
> 
> But it's not about banning the block, it's about the design of the block. World processors were never meant to be used directly in-game, only for map scripting like Anuke said. Don't forget they can place/destroy blocks, modify the game rules, placing text labels, etc. So yes, making it only available as a editor block is better and safer than just banning it.

Then maybe limit it to only singleplayer sandbox

**Comment by Phinner** [comment]
> > > > this would mean that unprivileged sandbox players in multiplayer can crash servers
> > > 
> > > 
> > > Then ban the block
> > 
> > 
> > But it's not about banning the block, it's about the design of the block. World processors were never meant to be used directly in-game, only for map scripting like Anuke said. Don't forget they can place/destroy blocks, modify the game rules, placing text labels, etc. So yes, making it only available as a editor block is better and safer than just banning it.
> 
> Then maybe limit it to only singleplayer sandbox

Well, you got a point.
