### ISSUE TITLE
Along with the spore storms

### ISSUE THREAD

**Issue by alann8** [Anuken/Mindustry-Suggestions#388]
**Describe the content or mechanics you are proposing.**

I saw spore storms on dev previews, and I would like to help the idea of seasons

1. Pretty common, it can change from really cold to really hot depends on it if its cold, water extracted are boosted, if it's hot thermals are boosted but thoroium reactors are more fond of exploding

2. Magnetic interference, it can make the player glitch and construction can go weird with factories and turrets that use elictricity

3 well in v.6 you added placeable slag so can you make a volcano? It can erupt sometimes the player can block the lava with walls and the turret wave with cryofluid or water

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It can make gameplay more interesting (it already is no offense) and players will be more challenged

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
1. I don't think seasons make sense in a game with short-term gameplay like Mindustry.
2. Randomly glitching out blocks doesn't seem like a good game mechanic. I'm not opposed to special solar weather patterns, but not like the ones you're describing.
3. See the Trello.
