### ISSUE TITLE
Turrets

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3881]
### Describe what you would like changed, and why.

Malign and smite should keep shooting when they destroy an enemy and aim at another one because they have a shooting delay and every time they destroy a t1 unit they stop shooting and wait this delay again, making their dps significantly smaller and making them look dump

### Describe the changes you want to propose. Include possible alternatives.

They should keep shooting while rotating

**Comment by OnyxFinger** [comment]
I'm fine with malign being the way it is, but smite should be changed.

**Comment by lokyinng** [comment]
for some reason, scathe hit air unit does no damage
