### ISSUE TITLE
T6 and (maybe) T7 Erekir units

### ISSUE THREAD

**Issue by mega2335** [Anuken/Mindustry-Suggestions#3886]
### Describe the content or mechanics you are proposing.

T6 and maybe T7 Erekir units, maybe a new assembler module.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be pretty helpful on Erekir, and would make some interesting sectors on Erekir.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Fun fact : Multiple hints point at the fact that there will be T6 units. However, it would seem that for now Anuke is fine with the current amount of content currently in the game.

**Comment by mega2335** [comment]
Yeah I agree, like one of the hints is that the assembler module is called "**basic** assembler module"

**Comment by Dangleos** [comment]
And in it's description it says
Function
Module Tier: 1
Which is not something you add if it's the only tier

**Comment by OnyxFinger** [comment]
> Yeah I agree, like one of the hints is that the assembler module is called "**basic** assembler module"

or that t4 takes a t1, t5 takes a t2, and t3 isn't yet used by any of them.

**Comment by mega2335** [comment]
> And in it's description it says Function Module Tier: 1 Which is not something you add if it's the only tier

Exactly.
