### ISSUE TITLE
RTS update 

### ISSUE THREAD

**Issue by sheptalo** [Anuken/Mindustry-Suggestions#3887]
### Describe the content or mechanics you are proposing.

on serpulo many units can follow player, mine ore and other. on erekir units cant do anything. i think they should have an option that allow them to follow player 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

imagine you go on the attack using your unit, and you need the help of your army, but you can't give the units orders. and if this option will be you will just use it and go attack with your army

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
you do know, that you can just select your army and tell it to join you or have it pre-selected right ?
You can also keep it close and/or use camera panning (or just moving your screen on mobile) to get to a point where you can view your army faster.

I believe that the current RTS system is primitive, but I never ran into this specific issue myself.
