### ISSUE TITLE
Overdrives make Meltdowns have more heat, for more damage

### ISSUE THREAD

**Issue by terminalmaid** [Anuken/Mindustry-Suggestions#3889]
### Describe the content or mechanics you are proposing.

at the moment, meltdown turrets only have a smaller cooldown when overdriven and still have 936 damage per second, while other turrets get a way faster firerate, effectively improving damage a lot
this makes meltdown a bad option in endgame compared to e.g. overdriven thorium fuses
instead, overdrives should make meltdowns attack with a more heated laser, which would deal more damage but have a longer cooldown

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would make meltdowns a more viable option in endgame, and also useful for electric turret only playthroughs (doing one myself at the moment)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
I think that this should be implemented. Right now, meltdowns suck. To make what I feel more comprehensible, here is a sort "this is better than this" chain : meltdowns take a very long time to kill high tier units, and are waayyy outclassed by spectres. But hold on, spectres are way outclassed by surge cyclones, which are themselves outclassed by surge swarmers. So, they suck. I mean, surge swarmers and cyclones do need a nerf, but even if this is considered, meltdowns still suck.

**Comment by terminalmaid** [comment]
> but even if this is considered, meltdowns still suck
not exactly, with an overdrive dome it'd have 2340 damage per second, which is very good, considering that its close to an overdrive domed thorium spectre, and its very good especially for an electric turret (also, surge swarmers are outclassed by thorium cryo overdrive dome fuses, which have 3150dps)

**Comment by OnyxFinger** [comment]
> > but even if this is considered, meltdowns still suck
> 
> not exactly, with an overdrive dome it'd have 2340 damage per second (if this gets added that is), which is very good, considering that its close to an overdrive domed cryo thorium spectre, and its very good especially for an electric turret (also, cryo odd surge swarmers are outclassed by thorium cryo overdrive dome fuses, which have 3150dps)

I actually playtested meltdowns before reading this suggestion. They still suck.

**Comment by terminalmaid** [comment]
yes

**Comment by overdramaticpanromantic** [comment]
This is a good idea. Rare terminalmaid W.

**Comment by terminalmaid** [comment]
> This is a good idea. Rare terminalmaid W.

are you implying that most of my ideas are bad? ~~they are, but still~~

**Comment by terminalmaid** [comment]
okay so, this actually doesn't make sense because overdrives make things faster, so i'll make another way for this in a new suggestion

**Comment by terminalmaid** [comment]
oh ffs its not "as completed"
