### ISSUE TITLE
More Weather

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#389]
**Describe the content or mechanics you are proposing.**
New weathers like snow storms, sand storms and rain + thunder storm. Snow storms would slow down all buildings, units and would freeze over water, turning all water tiles too ice for the time of the storm (up to map settings). It would also freeze all conduits unless it is a heated conduit which would be a conduit made 1 silicon, 1 metaglass, 1 thorium, 1 titanium and 1 plastanium, heated conduits will automaticlly be disabled and wont appear as a banned block or a allowed block in the settings if snow storms are disabled (which can be toggled). Sand storms would a storm which would happen on sand, the sand storm would make it quite hard to see on your screen and would also increase the inaccuracy of units and turrets. Thunder storms would be toggeable and would occur randomly sometimes at the same time as snow storms or sand storms. Thunder storms would cause damage and fires too buildings and the severity would depend on the map creator or custom rules, the thunder storm lightning can be harvested by a thunder rod which would generate 1 million power in a quick surge and would not result in the lightning to not deal any damage to nearby structures or units. Units will be stunned from thunder strikes.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would add more life to mindustry and would be very cool and unique giving a new strategy and value to maps.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
> Before making this issue, replace the spaces in the following boxes with an X to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

**Comment by RoyalFunnyDude** [comment]
lmao

**Comment by RoyalFunnyDude** [comment]
guess he didn't check on Trello/wiki/suggestion list and doesn't acknowledge them lmao

**Comment by stuffyAI** [comment]
> guess he didn't check on Trello

He actually did not those new weather types are planned in the trello.
