### ISSUE TITLE
Reversed survival

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3893]
### Describe the content or mechanics you are proposing.

Allow players to launch an attack on the enemy base by sending their own units. Maybe when you unlock payload units or build blocks what launch units in pods, or dropships. Baybe even transporting units between your bases 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A new alternative to building your base from scratch. And make units still usefull arter you capture a sector instead or deconstructing or nuking them

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
POV : attack gamemode.
Nah I get what you mean, but it would be awful. The only real gameplay would be to launch a big ass wave and target-move the core.

**Comment by itcannotbe** [comment]
Isn't this fully possible with what we have in the game currently?
