### ISSUE TITLE
Water obtaining block from rain

### ISSUE THREAD

**Issue by RyukoM4701** [Anuken/Mindustry-Suggestions#3904]
### Describe the content or mechanics you are proposing.

A new block to the game that collects water from rain when it rains on the sector. Had the idea come to my mind when I saw it rain on our map while playing with my friend.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's a different way to obtain water. I think it's not that bad logically.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
I've seen the same suggestion when v6 was in development

**Comment by stuffyAI** [comment]
While making maps build around rain collectors sound cool, this only seems like an annoying beginner trap to "easily get water everywhere" and not actually engage with liquid mechanics.
