### ISSUE TITLE
liquid mass driver 

### ISSUE THREAD

**Issue by Marrietas** [Anuken/Mindustry-Suggestions#3905]
### Describe the content or mechanics you are proposing.

basically mass driver but for liquid 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will help its basically just mass driver but for liquid has all tbe sane attributes, no need for obnoxious long conduits blocking paths for your conveyers

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sheptalo** [comment]
you can transport liquid in water tanks and load it in Payload Mass driver

**Comment by OnyxFinger** [comment]
> you can transport liquid in water tanks and load it in Payload Mass driver

*cough cough* Serpulo. I mean, you need a payload propulsion tower.

seriously though you guys need to stop checking the boxes if you haven't actually done what it tells you to. This has been suggested and rejected many times. The reason for this is that liquids are much less important than items on Serpulo. There is also the fact that current liquid mechanics most likely won't allow this to work properly.
