### ISSUE TITLE
Add a button block for mindustry logic

### ISSUE THREAD

**Issue by Shidoengie** [Anuken/Mindustry-Suggestions#3906]
### Describe the content or mechanics you are proposing.

This button block would have a "@ pressed" property which would have 3 states (returning a 2 when it has just been pressed , returning a 1 while the button is being pressed and returning a 0 when then button has been released or isn't pressed ).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This block would simplify a lot of things when making logic with user interactions, and, would allow for continuous pressing, a thing that simply reading the state of a switch and then disabling it wouldn't allow.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Not that hard to do with touchscreen logic

**Comment by Shidoengie** [comment]
> Not that hard to do with touchscreen logic 

But then it would take up screenspace
