### ISSUE TITLE
Ammo sharing

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3911]
### Describe the content or mechanics you are proposing.

An instruction for units in logic what would make them share their own ammo with other units or load items from their inventory into the other unit to refill it's ammo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow logic controlled units to support big units by refilling their ammo so they wouldn't need to go back to base for it because they are very slow. Or add a new class of units for this

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
I believe I asked you to think just a second before posting suggestions, this is literally working as intended, and I bet you can figure out why.
