### ISSUE TITLE
game data transfer over LAN

### ISSUE THREAD

**Issue by end-me-please** [Anuken/Mindustry-Suggestions#3915]
### Describe the content or mechanics you are proposing.

in addition to exporting as .zip, allow sending game data between devices over LAN, after confirming on both devices

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

fast, simple and painless switching between devices.

currently a third party cloud (or similar) is required to transfer game data between PC/Mobile, and its quite messy especially with locked-down devices like iPhones.

(Steam doesnt fill this niche, it's not available for mobile, which is the main use case for game data transfer)

spending 5 minutes on that every time you want to go somewhere (and take the game with you) is quite unpleasant

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Implement it using a pull request! Learning to code is a great skill to have.

on the other hand, upload save -> email or upload to discord -> download. Pretty easy, innit?

**Comment by end-me-please** [comment]
sure, email/discord works, but after the 5th time its a bit annoying, and it requires third party services

**Comment by IxGamerXL** [comment]
It's actually more secure compared to the current options to transfer game data to your phone and vise versa by exporting and importing. Even if you need to move the game data to another computer or to another phone, you should have a phone or computer respectively.

**Comment by itcannotbe** [comment]
Having to auto detect another device on your network is never fool proof.

**Comment by IxGamerXL** [comment]
> Having to auto detect another device on your network is never fool proof.

Pretty much my only problem with the feature.

**Comment by end-me-please** [comment]
it's not foolproof, but local multiplayer already works reasonably well with mindustry

sending the data over an existing multiplayer connection would also be an option, basically switching host
