### ISSUE TITLE
Feature Dump - From BasedHumanistical

### ISSUE THREAD

**Issue by BasedHumanistical** [Anuken/Mindustry-Suggestions#3916]
### Describe the content or mechanics you are proposing.

If you do add any of the units to the game I'd love to discuss names (no pressure :p)

**Path Commands -**
In other games such as (https://www.roblox.com/games/8377997/The-Conquerors-3-NEW-MAP) there is a feature where you can select your troops (similar to this one) but if you hold CRTL while doing it you can set down multiple waypoints for the troops to go to, of course in the order you placed them down.

**Formations -**
Another feature from https://www.roblox.com/games/8377997/The-Conquerors-3-NEW-MAP is formations, holding the select troops button (which is shift) and using the scroll wheel will go through some premade formations.

**Planet Editor -**
Just like from Mario Maker 2 you can make a level then upload it onto a world, I think such an idea could be used here, you make a level and plot it out on a planet. There even could be a ring for custom worlds that you can select #/# worlds, 10 worlds is ideal to me.

**Digger Unit -** (I read the Underground map layers in the readme and want to clarify I'm not asking for another layer)
A ground unit that can dig under ground to bypass enemy defenses and bring troops to the front line.

-- T1 Would be a simple unit that can walk on the surface but move very slow under ground to avoid getting hurt, they can't go under water, deep water, walls, or empty. They would take damage from heat while under the ground and would take silicon and sand to make. They would use the same damage values as a flare

-- T2 Add a close range fire attack like a mace.

-- T3 Allow the unit to move under sand water and water. The unit to cause a small earthquake but damage themselves and other units nearby,

-- T4 They aren't able to shoot but can carry units up to T3

-- T5 Can't go under water but can move units all the way up to T5 units, they are unable to use the earthquake move.

**Light Unit-**
A air unit that can blind enemies and provide light to dark areas. Really good for entry. They take Phase and Glass to make.
Blinding an enemy allows it to shoot, but it can not relock onto the target. ~shoots blindly~

-- T1 is a simple unit that can only shine light very small about 5 blocks.

-- T2 Shines a brighter light (10 blocks) and shoots a charge (light turns off when it shoots) the charge is like ARC Turret

-- T3 Shines a brighter light (20 blocks) and shoots 3 charges and faster light goes down to 5 while shooting.

-- T4 20 block bright light, flashes when shoot blinding nearby turrets and troops.

-- T5 30 block light, drops a flash like a bomb shoots a beam of light. Lights turn off when charging beam.

**Phase Unit-**
A sea unit that can phase through walls and can't be seen while doing it. Dropping Phase Fabric on them makes the move faster.

-- T1 Can drop Naval mine in deep water.

-- T2 Can fire Naval mines into deep water allowing them to go farther. Not longer drops Naval mines on themselves.

-- T3 When phase is dropped on this unit they speed up units around them as well.

-- T4 Can shoot bullets that speed up units within the radius it lands, this of course costs Phase Fabric.

-- T5 Gives off a speedy aura to all units near by.

**Phase Drill -**
4x4 are requires phase fabric to operate and drill very fast (Little slower than laser but better than pheumatic), when the item is output it moves quicker for 3 seconds.

**Editor Overhaul -**
-- Copy and Paste.
-- Mirror
-- Rotate
-- Eraser actually removing anything under it.
-- Brushes (Like World Painter having a file where you can submit brushes)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**Path Commands -**
This would help with multi-staged attacks and stop units from getting stuck on walls. Just QOL

**Formations -** 
Another QOL to help attacks.

**Planet Editor -**
Being able to make planets instead of maps and giving people a whole new campaign would be HUGE, I personally have been looking for a way to make planets so I can upload my maps but sadly I can't code.

**Digger Unit -**
Turning heat into a weapon would be revolutionary, along side being able to get behind enemy lines with these units and bring some friends along! I want to clarify that not being able to attack or be attacked and having the high T units being able to carry units really makes it different from crawler tree.

**Light Units -**
Even low rank Light units are helpful in dark maps and being able to flash enemies will add a new element to the game that I don't even know how I lived without.

**Phase Units-**
Units that can speed up other units is a powerful feature, but limiting it to water and making it cost materials to use is a wonderful feature that I will hate having to manage, Being able to add mines on the fly to set up traps for enemies can be huge.

**Phase Drill -**
Having to use a decent resource in order to mine quickly is a good way to try and balance materials, is the material your mining really worth more than Phase Fabric?

**Editor Overhaul -**
Using the Editor as a new user was very hard and painful I feel like adding these tools and maybe some more would give new users an easier time making maps and adding to the community.

I'd just like to say I have many many many more ideas but I don't want to overwhelm whoever reads this stuff, if you like what you see feel free to @ me.
-
Also feel free to throw values around I have no idea what would be considered balanced so have at it.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Path commands and formations: Agree. It’s an RTS game, so having that feature makes sense.

Planet editor: You will probably get the ability to implement your own planets more easily once Erekir is finished. You could also ask the discord how to implement one now.

Digger unit: That’s just a more powerful version of the crawler tree, which can go over defenses by T2.

Light unit: I wouldn’t be completely against an EMP/disabling unit, although that’s a mechanic best left for T3-5 due to the power it can have.

Phase units and drills: We have air blasts and overdrive. I think adding even faster options could be extremely powerful and broken, even. For the units, I think a support class could be interesting, but this type of implementation could be questionable.

**Comment by BasedHumanistical** [comment]
Phase drill should then probably go about the speed of Laser Drill, but speeding up items on exit is a nice touch.

Digger units will have different weapons and can't attack underground, and they can't be shot when underground, that's a huge difference from crawlers.

**Comment by terminalmaid** [comment]
digger units would be a bit pointless considering that flying units could go around defense, and light units shouldn't do anything else other than light up the map, and only have up to t3, considering that  navanax has an EMP cannon already

i'm quite sure formations were a thing in v6 and were removed in v7

phase drill: honestly, we don't really need another drill, since you can use overdrives to speed up conveyors and airblast and laser drills are already quite powerful

planet editor: pretty good feature, but very niche, not many players have the dedication to make a new planet, and if they do, they probably can mod a planet into the game anyway

phase units: if only limited to water it's completely pointless because naval units are fast anyway

editor overhaul: would be pretty nice actually

path commands: pretty useful too

**Comment by BasedHumanistical** [comment]
> digger units would be a bit pointless considering that flying units could go around defense, and light units shouldn't do anything else other than light up the map, and only have up to t3, considering that navanax has an EMP cannon already


Flying units can **attack and get attacked**, and light units don't **EMP** they blind, the turret can still shoot, just blindly, maybe in the same direction they were looking when they were blinded.

> planet editor: pretty good feature, but very niche, not many players have the dedication to make a new planet, and if they do, they probably can mod a planet into the game anyway


Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new **niche**.

**Comment by terminalmaid** [comment]
creating a whole new map editor for like 3 people is a waste of time
also, blinding things would be too unbalanced

**Comment by BasedHumanistical** [comment]
what you described is niche, they are asking for niche. 3 people is pretty niche, also I'm sure when it is added a lot more people will take note and attempt it.

**Comment by RFAC-Productions** [comment]
The Digger Unit, let's name em.
T1: Burrow
T2: Magma
T3: Quake
T4: Ore
T5: Vein
Now, the digger units sounds like something that fits the wormy nois, aka the Remale line. However I would like the Remale and Burrow lines to be different units. Plus while Remales are in the shaoe of grub, Burrow, Magma, Quake, Ore, and Vein could look like drill vehicles or centipedes.

**Comment by BasedHumanistical** [comment]
I love those names!
Especially Quake and Vein

**Comment by IVV-NCX** [comment]
> Phase drill should then probably go about the speed of Laser Drill, but speeding up items on exit is a nice touch.
> 
> Digger units will have different weapons and can't attack underground, and they can't be shot when underground, that's a huge difference from crawlers. Plus they can't interact with water (mostly) when underground

Mind, overdrive speeds up conveyers...

**Comment by IVV-NCX** [comment]
Blind is still OP,I said EMP because it does a similar role of disabling enemy turrets.

**Comment by BasedHumanistical** [comment]
blinding the doesn't disable the turret and can effect units as well, this doesn't stop them from moving or shooting, they just won't adjust their shoots because they can't see, having a 1-3 second delay between each flash would def make it not op.
