### ISSUE TITLE
Better mod management

### ISSUE THREAD

**Issue by salty27** [Anuken/Mindustry-Suggestions#3918]
### Describe the content or mechanics you are proposing.

Having the possibility to create presets of enabled mods (aka modpacks), and change the current UI so there are two mods per row (like when looking up mods)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Two mods per row allow players to find easily that mod they installed long time ago but forgot its name, or that you just downloaded not to forget about it. Overall it also allows to see more information at once.
Presets/modpacks give the opportunity for players to play with different configurations (for example, a set of mods for serpulo and another for erekir) without using them all (thus overloading game). Making servers, maps or challenges with several mods becomes easier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BasedUser** [comment]
Mods can be modpacks on their own. To do that, you need to reuse github downloading for every mod involved (and if all else fails, just bundle the zips of all these mods inside the mod, and copy them to the parent folder)

**Comment by salty27** [comment]
That is more of a workaround than a solution. I mean, that can be done, but having an interface that doesn't involve having to mess up with mod-making would be better. With your method, removing or adding a mod into the modpack would need you to recompile the whole modpack. Moreover, if modpacks are done this way and uploaded, creators would get no downloads or credits from using their mods
