### ISSUE TITLE
Custom gamemode enum

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#392]
**Describe the content or mechanics you are proposing.**

The adding of a new [`Gamemode`](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/game/Gamemode.java) enum that [`NetworkIO`](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/net/NetworkIO.java#L81) can use via [`Rules`](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/game/Rules.java#L118) to signify something abnormal is going on.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It'll make it more clear to players what they can expect when they join a server:
- `lobby`
- `minigame`
- `hexed`
- `limbo`
- `queue`
- `party`
- `etc`

but since adding an enum for each specific usecase is bloated, i would suggest a general term such as `custom`
(since as you know the gamemode of a server is not a string when transmitted, but translated into human by the client)

i'm not sure which would be the best way to trigger it, `canGameOver` seems like an obvious one to pick, but that might be a little to generic since there may be cases where one of the normal/existing gamemodes make use of it 🤔 

anyways, leaving this here for now, its been in my head for months, and i might even pr it someday (if @Anuken likes it)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ILiekMelons** [comment]
~~you told a server to upvote this~~

**Comment by hribik100** [comment]
Good idea

**Comment by walksanatora** [comment]
Ping

**Comment by Quezler** [comment]
> ~~you told a server to upvote this~~

yes: its not against the rules
no: i asked, it wasn't forced

**Comment by ILiekMelons** [comment]
> it was entirely voluntary ♥️
¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by Quezler** [comment]
> > it was entirely voluntary ♥️
> 
> ¯\\\_( ͡° ͜ʖ ͡°)_/¯
> 
> 

feel free to visit the announcement channel on the nydus discord if you feel the need for proof 🙃

**Comment by DeltaNedas** [comment]
I 10000% agree with this suggestion, but I don't think Anuke will care if there's 20 mostly artificial thumbs up on it or not, a good idea is a good idea.

**Comment by ILiekMelons** [comment]
> > > it was entirely voluntary ♥️
> > 
> > ¯\\\_( ͡° ͜ʖ ͡°)_/¯
> > 
> > 
> 
> feel free to visit the announcement channel on the nydus discord if you feel the need for proof 🙃

im in the nydus discord though 👁️👄👁️

**Comment by Quezler** [comment]
> I 10000% agree with this suggestion, but I don't think Anuke will care if there's 20 mostly artificial thumbs up on it or not, a good idea is a good idea.

its not artificial, each of them is a human who voted out of their own free will 🤔

**Comment by Quezler** [comment]
> im in the nydus discord though 👁️👄👁️

then you should already know it was voluntary 🙂

**Comment by Quezler** [comment]
brainfart: instead of adding just one called `custom`, simply make it hide the ` / <gamemode>` behind the map name so the gamemode can be artificially named anything by modifying the name of the map name in the packet 🤔

**Comment by Quezler** [comment]
here is a patch for my comment above (so not the initial suggestion):

this appends the gamemode string to the map name (so its not ideal for e.g. how the april fools thing was triggered)
also it is of course a bit messy to do it this way, but i could not think of another backwards compatible ping packet ✏️ 

```
From 06d05cd805d954c574b1f1701c37f2258886479e Mon Sep 17 00:00:00 2001
From: Patrick 'Quezler' Mounier <patrick@queztech.net>
Date: Thu, 13 Aug 2020 11:43:20 +0200
Subject: [PATCH] Implement string based custom gamemode

---
 core/src/mindustry/game/Gamemode.java         | 3 +++
 core/src/mindustry/game/Rules.java            | 4 +++-
 core/src/mindustry/net/NetworkIO.java         | 2 +-
 core/src/mindustry/ui/dialogs/JoinDialog.java | 3 ++-
 4 files changed, 9 insertions(+), 3 deletions(-)

diff --git core/src/mindustry/game/Gamemode.java core/src/mindustry/game/Gamemode.java
index 9de5e7105..7dfe2d260 100644
--- core/src/mindustry/game/Gamemode.java
+++ core/src/mindustry/game/Gamemode.java
@@ -41,6 +41,9 @@ public enum Gamemode{
         rules.waves = false;
         rules.enemyCoreBuildRadius = 0f;
         rules.waveTimer = false;
+    }),
+    custom(true, rules -> {
+        rules.tags.put("gamemode", "Custom");
     });
 
     private final Cons<Rules> rules;
diff --git core/src/mindustry/game/Rules.java core/src/mindustry/game/Rules.java
index 83b0c67e6..d2fa6b3ca 100644
--- core/src/mindustry/game/Rules.java
+++ core/src/mindustry/game/Rules.java
@@ -116,7 +116,9 @@ public class Rules{
 
     /** Returns the gamemode that best fits these rules.*/
     public Gamemode mode(){
-        if(pvp){
+        if(tags.containsKey("gamemode")){
+            return Gamemode.custom;
+        }else if(pvp){
             return Gamemode.pvp;
         }else if(editor){
             return Gamemode.editor;
diff --git core/src/mindustry/net/NetworkIO.java core/src/mindustry/net/NetworkIO.java
index f4b4d3a61..478bf7675 100644
--- core/src/mindustry/net/NetworkIO.java
+++ core/src/mindustry/net/NetworkIO.java
@@ -66,7 +66,7 @@ public class NetworkIO{
     public static ByteBuffer writeServerData(){
         String name = (headless ? Config.name.string() : player.name);
         String description = headless && !Config.desc.string().equals("off") ? Config.desc.string() : "";
-        String map = state.map.name();
+        String map = state.rules.mode().equals(Gamemode.custom) ? (state.map.name() + "[lightgray] / " + state.rules.tags.get("gamemode")) : state.map.name();
 
         ByteBuffer buffer = ByteBuffer.allocate(512);
 
diff --git core/src/mindustry/ui/dialogs/JoinDialog.java core/src/mindustry/ui/dialogs/JoinDialog.java
index e61caffff..351815f21 100644
--- core/src/mindustry/ui/dialogs/JoinDialog.java
+++ core/src/mindustry/ui/dialogs/JoinDialog.java
@@ -10,6 +10,7 @@ import arc.util.*;
 import arc.util.serialization.*;
 import mindustry.*;
 import mindustry.core.*;
+import mindustry.game.*;
 import mindustry.gen.*;
 import mindustry.graphics.*;
 import mindustry.io.legacy.*;
@@ -230,7 +231,7 @@ public class JoinDialog extends BaseDialog{
             }
             t.add("[lightgray]" + (Core.bundle.format("players" + (host.players == 1 && host.playerLimit <= 0 ? ".single" : ""), (host.players == 0 ? "[lightgray]" : "[accent]") + host.players + (host.playerLimit > 0 ? "[lightgray]/[accent]" + host.playerLimit : "")+ "[lightgray]"))).left();
             t.row();
-            t.add("[lightgray]" + Core.bundle.format("save.map", host.mapname) + "[lightgray] / " + host.mode.toString()).width(targetWidth() - 10f).left().get().setEllipsis(true);
+            t.add("[lightgray]" + Core.bundle.format("save.map", host.mapname) + (host.mode.equals(Gamemode.custom) ? "" : "[lightgray] / " + host.mode.toString())).width(targetWidth() - 10f).left().get().setEllipsis(true);
         }).expand().left().bottom().padLeft(12f).padBottom(8);
     }
 
-- 
2.15.2 (Apple Git-101.1)
```

**Comment by Quezler** [comment]
also i'm not sure if setting the global tag rule to something is a merge or an override, in the latter this will be troublesome.

anyways, here's a patch for the original suggestion, but this isn't flexible in the slightest, though its the least invasive: 👾 

(and `custom` might not be the best name for it since `custom game` is already a thing and is fundamentally different)

```
From a81d3f41a04e4613852d17044e3ebf814250a269 Mon Sep 17 00:00:00 2001
From: Patrick 'Quezler' Mounier <patrick@queztech.net>
Date: Thu, 13 Aug 2020 11:52:13 +0200
Subject: [PATCH] Implement enum based custom gamemode

---
 core/assets/bundles/bundle.properties | 1 +
 core/src/mindustry/game/Gamemode.java | 3 +++
 core/src/mindustry/game/Rules.java    | 4 +++-
 3 files changed, 7 insertions(+), 1 deletion(-)

diff --git core/assets/bundles/bundle.properties core/assets/bundles/bundle.properties
index 4b8026df8..f54f247a2 100644
--- core/assets/bundles/bundle.properties
+++ core/assets/bundles/bundle.properties
@@ -793,6 +793,7 @@ mode.pvp.description = Fight against other players locally.\n[gray]Requires at l
 mode.attack.name = Attack
 mode.attack.description = Destroy the enemy's base. \n[gray]Requires a red core in the map to play.
 mode.custom = Custom Rules
+mode.custom.name = Custom
 
 rules.infiniteresources = Infinite Resources
 rules.reactorexplosions = Reactor Explosions
diff --git core/src/mindustry/game/Gamemode.java core/src/mindustry/game/Gamemode.java
index 9de5e7105..19a6e74c2 100644
--- core/src/mindustry/game/Gamemode.java
+++ core/src/mindustry/game/Gamemode.java
@@ -41,6 +41,9 @@ public enum Gamemode{
         rules.waves = false;
         rules.enemyCoreBuildRadius = 0f;
         rules.waveTimer = false;
+    }),
+    custom(true, rules -> {
+        rules.canGameOver = false;
     });
 
     private final Cons<Rules> rules;
diff --git core/src/mindustry/game/Rules.java core/src/mindustry/game/Rules.java
index 83b0c67e6..a78bef1c8 100644
--- core/src/mindustry/game/Rules.java
+++ core/src/mindustry/game/Rules.java
@@ -116,7 +116,9 @@ public class Rules{
 
     /** Returns the gamemode that best fits these rules.*/
     public Gamemode mode(){
-        if(pvp){
+        if(!canGameOver){
+            return Gamemode.custom;
+        }else if(pvp){
             return Gamemode.pvp;
         }else if(editor){
             return Gamemode.editor;
-- 
2.15.2 (Apple Git-101.1)
```

**Comment by Anuken** [comment]
Implemented.
