### ISSUE TITLE
Thing

### ISSUE THREAD

**Issue by Ombav2** [Anuken/Mindustry-Suggestions#3921]
### Describe the content or mechanics you are proposing.

Can you please add an option to make derelict work like the rest of the factions (and possibly in the future a short campaign with em that follows the idea of trying to rebuild)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I like the derelict and plus, why not

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Derelict was intended to be a neutral, non-existent team, so that's very unlikely to happen

**Comment by Dangleos** [comment]
Derelict is for abandoned buildings. It was added for abandoned blocks on maps and destroyed enemy bases
+ This idea of trying to rebuild is out of mindustry style and sound like it would take a lot of work and would be boring
+ Anuken said he will never add allied factions
+ Ratio
