### ISSUE TITLE
Upgrade in-game map editing 

### ISSUE THREAD

**Issue by Karys0** [Anuken/Mindustry-Suggestions#3922]
### Describe the content or mechanics you are proposing.

Give us in in-game map editing option to place walls, floor, ores, and other things that we can place in normal editor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help in editing maps, so we don't have to constantly switch between in-game and out-game editing.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
I think there's a V7 mod that allows you to configure the map as if you had World Edit. If you know what is and isn't V7 when it comes to content, you should be able to export the map to your V6 instance unless you actually want to make a map for V7.
