### ISSUE TITLE
Duct direction markings visibility

### ISSUE THREAD

**Issue by marky0470** [Anuken/Mindustry-Suggestions#3923]
### Describe what you would like changed, and why.

The white directional markings on ducts make distinguishing items passing through slightly hard, especially given the speed at which they transport.

### Describe the changes you want to propose. Include possible alternatives.

I propose giving the duct direction markings a visibility slider, or having them be rendered below the items

**Comment by RFAC-Productions** [comment]
Uh oh, you did not checkmark all boxes.

**Comment by marky0470** [comment]
> Uh oh, you did not checkmark all boxes.

It's not required with balancing/feedback suggestions

**Comment by itcannotbe** [comment]
> Uh oh, you did not checkmark all boxes.

@RFAC-Productions where are these checkboxes you speak of? I can't seem to find them for the template for this label/issue type.

**Comment by catreplicators** [comment]
Maybe something like this:
![block-duct-ui](https://user-images.githubusercontent.com/67205542/190880736-3bcf8816-c73f-4805-af41-25b64d00aaf5.png)
