### ISSUE TITLE
Meltdown turret balancing

### ISSUE THREAD

**Issue by terminalmaid** [Anuken/Mindustry-Suggestions#3924]
### Describe what you would like changed, and why.

Currently, meltdown is in a pretty weird state, it's supposed to be an endgame turret, yet it's bad in endgame and can be unlocked right after craters

instead, the surge smelter should be locked behind tar fields or at least meltdown itself should be behind them

also, meltdowns should accept oil or slag for a much longer cooldown but a very large damage boost
 
oil would have a medium damage boost and long cooldown, but slag would have a large damage boost and a very long cooldown

however, fluid consumption will have to be boosted to about 3/4 of a fluid tank per burst

### Describe the changes you want to propose. Include possible alternatives.

an alternative would be to make meltdowns get damage boosted by overdrives, but it doesn't really make sense because overdrives make things faster

meltdown is kind of hard to balance because it's the only burst turret on serpulo, so i decided to make a suggestion

thanks to insult#2146 on the discord for the oil/slag coolant idea

**Comment by itcannotbe** [comment]
By definition, coolant is something that cools down something, and by code, coolants are liquids that have temperatures below a set threshold.

**Comment by terminalmaid** [comment]
never said it's coolant

**Comment by terminalmaid** [comment]
it's a liquid that can be inputted, but not specifically coolant

**Comment by terminalmaid** [comment]
also, the way meltdown deals damage is pretty good and the aoe is decent too, though foreshadow-like targeting would be nice

**Comment by terminalmaid** [comment]
or at least targeting where it can do the most damage, e.g. flying unit swarms

**Comment by 50275** [comment]
surge cyclones are available sooner, costing much less, so it only makes sense that we'd use them instead

**Comment by terminalmaid** [comment]
that's the point, currently meltdowns aren't worth using so they need balancing

**Comment by Slotterleet** [comment]
> surge cyclones are available sooner, costing much less, so it only makes sense that we'd use them instead

use surge swarmers instead, they are more compact and spammable
yes, swarmer has a tendency to eat all of your items pretty fast, but it's still easy to make enough surge for them between waves

**Comment by OnyxFinger** [comment]
> > surge cyclones are available sooner, costing much less, so it only makes sense that we'd use them instead
> 
> use surge swarmers instead, they are more compact and spammable yes, swarmer has a tendency to eat all of your items pretty fast, but it's still easy to make enough surge for them between waves

^^^ facts

**Comment by terminalmaid** [comment]
> > surge cyclones are available sooner, costing much less, so it only makes sense that we'd use them instead
> 
> use surge swarmers instead, they are more compact and spammable yes, swarmer has a tendency to eat all of your items pretty fast, but it's still easy to make enough surge for them between waves

true, but we aren't talking about surge swarmers here, we're talking about meltdowns
