### ISSUE TITLE
Better objectives.

### ISSUE THREAD

**Issue by Helium-ion** [Anuken/Mindustry-Suggestions#3926]
### Describe the content or mechanics you are proposing.

1.When I design a circular objective, it never works. Because its predecessor objective will never be completed.

2.Objectives do not have an "or" function. For example, I want players to get some heat in any way, both electric-heater and slogan-heater are optional, but the functionality of existing objectives is not possible. (Well, this one is achievable, just very complicated, and it adds an unnecessary burden to the map.)

3.Objectives cannot accept the value of a custom variable (perhaps?). I'm not saying a time display like a campaign). I want it to get the value of the custom variable and displayed in a specific location.

To 1.2. Flags are allowed for each object, and when the game starts, objectives will be executed starting from objectives with Start-flag. Only one of the many sub-objectives with a Breakthrough-flag objective can be completed. An objective with a General-flag activates when any of its many parent objects are completed.

To 3. Add "Objectives-cell", which can be read and written to world-processor and objectives to allow Objectives to accept variables. Or simply add the ability to display float text at specific coordinates for the world-processor.

Just a small suggestion and I believe there is a better solution.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

These changes can make map making more free and convenient.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Breadyboi69** [comment]
Slogan heater.

**Comment by Dangleos** [comment]
Game need some converter between world processors and objectives because neither can do everything alone. Like reading from cells
