### ISSUE TITLE
Rotating banned block

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3928]
### Describe the content or mechanics you are proposing.

When map has a banned block but this block is already build so you can't have too many of them you can't rotate it on mobile. Make it so players can rotate blocks whenever they can build them or not

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

ඞ

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
это было бы полезно когда строится т5 и его выход уприается в стену но в вашей функции нету смысл так как поворот постройки возможен моментально и бесплато к любым уже построенным зданиям
