### ISSUE TITLE
Neoplasm isn't that dangerous

### ISSUE THREAD

**Issue by Jaysonnn80** [Anuken/Mindustry-Suggestions#3930]
### Describe what you would like changed, and why.

At the moment, Neoplasm really isn't that dangerous. Aslong as you don't dump your neoplasm near your water-related blocks, you're fine. Furthermore, if you use a slag incinerator, the danger of neoplasm is entirely gone. In addition, I think that neoplasm needs to be more dangerous and less disposable.

### Describe the changes you want to propose. Include possible alternatives.

Possible ways to make less disposable:

- Neoplasm shouldn't be able to be simply dumped via conduits. Perhaps Neoplasm should emit flames, explode, etc upon being dumped via conduits.

- Make the incineration of neoplasm more difficult by reworking the slag incinerator to require energy, other liquid/gas input, higher building cost, more space, more slag, etc. 

Possible ways to make more dangerous:

- Neoplasm could harm/debuff units caught in its radius (slowing, damaging, lowering firerate, etc) and could attach itself to the units, increasing neoplasm spread.

- Neoplasm contaminating vents, causing them to be unusable (unless the neoplasm is somehow eliminated?)

**Comment by TheStupidCube123456** [comment]
This ^

**Comment by Anuken** [comment]
The slag incinerator accepting neoplasm was a bug; that is no longer possible at all anymore.

**Comment by TheEt1234** [comment]
add a wee bit of viscosity

**Comment by catreplicators** [comment]
To balance this, though, there has to be SOME way to get rid of it. A turret-thing similar to Wave turrets that accepts some gases or something that can temporarily "sterilize" an object to make it immune to Neoplasm for some time, also killing any neoplasm that's there.
