### ISSUE TITLE
Effects off

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3931]
### Describe the content or mechanics you are proposing.

All bullet trails dissapear instantly, and the longer the trail the worse it looks. It's very noticable without explosion effects
With effects turned off foreshadow, scorch, arc, segment, aegires, pulsar, mace, oxynoe and locus shoot invisibly.
Any electric arc dissapears.
Repair and shield regen fields become invisible.
Explosions don't show their blast radius which looks especially bad with quad, titan, scathe, thorium and impact reactors and navanax

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The option to turn off effects lets you play save resources when the game lags (especially on servers) but then many inportant details dissapear, making playing more difficult

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
Just turn on "Display Effects."
