### ISSUE TITLE
Cloud backup game data

### ISSUE THREAD

**Issue by hhjxx** [Anuken/Mindustry-Suggestions#3936]
### Describe the content or mechanics you are proposing.

1. Export and upload the game data to a http server.
2. Download and import the data from the http server.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I have multiple devices, and I hope to easily switch the devices using a same game data. And I think this feature is very helpful for backup game data.
I'm currentlly try working on it. Here is what it's look like in the settings.
![image](https://user-images.githubusercontent.com/43404732/188346996-62d3289b-bdff-41c6-a670-26f39095b562.png)
![image](https://user-images.githubusercontent.com/43404732/188347917-9a0b6ceb-55c5-4c5c-ac98-d5507ee908b6.png)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Well the steam version can do it

**Comment by hhjxx** [comment]
> Well the steam version can do it

But the mobile version seems cannot. And I think this could be helpful for those who have multiple devices.

**Comment by stuffyAI** [comment]
Please _actually_ read the README and not just tick all the checkboxes, because you clearly didn't:

Is **explicitly** states that built-in cloud sync will never be a thing.

Delete this

**Comment by itcannotbe** [comment]
> Please _actually_ read the README and not just tick all the checkboxes, because you clearly didn't:
> 
> Is **explicitly** states that built-in cloud sync will never be a thing.
> 
> Delete this

Please actually read the suggestion before asking people to "Delete this"

It is not actually cloud sync, just glorified manual upload/download using the http protocol.

Delete this.

**Comment by itcannotbe** [comment]
> Please _actually_ read the README and not just tick all the checkboxes, because you clearly didn't:
> 
> Is **explicitly** states that built-in cloud sync will never be a thing.
> 
> Delete this

@stuffyAI please actually read the suggestion before asking people to "Delete this"

It is not actually cloud sync, just glorified manual upload/download using the http protocol.

Delete this.

**Comment by stuffyAI** [comment]
> It is not actually cloud sync, just glorified manual upload/download using the http protocol.

That is cloud sync. It doesn't matter if manual or not, or if I use http, https or a custom mindustry protocol, I synchronize using some internet-accessible server.

It would even be cloud sync if they would host the server themself and use vpn to access it.

**Comment by itcannotbe** [comment]
So by extension, retrieving the server list is cloud sync because it automatically fetches the server list from github, which is basically a get request.

**Comment by hhjxx** [comment]
> So by extension, retrieving the server list is cloud sync because it automatically fetches the server list from github, which is basically an http get request.

But you can't easily update the list to github in the game. So it's not.

**Comment by stuffyAI** [comment]
> retrieving the server list is cloud sync

retrieving wouldn't be cloud sync, cloud sync usually implies that files across devices get synchronized, a game client wont update the server list...

GET and POST both are API-tools if its not specifically a webservice, there probably are Cloud services that use http to sync some settings, its just not used much due to the innate http limit to send 2MB bodies. To use them you'd need at-least some minimal cli-command like curl.
The problem with cloud services in Mindustry isn't the lack of an app either, that would be the literal game. The actual problems stem from providing the cloud itself and versioning issues between the different clients. It is probably very feasible to set up a personal game file synchronization.
