### ISSUE TITLE
The HUD flickers | BasedHumanistical

### ISSUE THREAD

**Issue by BasedHumanistical** [Anuken/Mindustry-Suggestions#3939]
### Describe what you would like changed, and why.

The editor HUD flickers whenever you screenshare on discord. 

### Describe the changes you want to propose. Include possible alternatives.

The change I want is for the HUD not to flicker when I share my screen on discord...

[https://ibb.co/8sYtcSy](url)  You can see it mid flicker here as the HUD is missing

**Comment by IVV-NCX** [comment]
This is a bug. Report it in the bugs.
