### ISSUE TITLE
schematics from #curated-schematics on discord for base sectors

### ISSUE THREAD

**Issue by terminalmaid** [Anuken/Mindustry-Suggestions#3941]
### Describe the content or mechanics you are proposing.

currently, base sectors on serpulo have pretty bad schematics, so using actually well-made schematics would be better and would make bases more challenging in some cases.
the trello does mention improved base generation, but i'm not sure if it's about serpulo or erekir

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would make bases more challenging in some cases and more interesting

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by hortiSquash** [comment]
Better schems, yes
Curated? Hell no

**Comment by terminalmaid** [comment]
why not curated

**Comment by IVV-NCX** [comment]
Those things are insanely good. Look at Qwerynoob's 14 impact SLCT. Or the supersized reactors. Just about any of the schematics are capable of doing massive things that are simply unbalanced to play against. Better ones will be appreciated though.

**Comment by OnyxFinger** [comment]
Actually well-made schems would suck, because they will always stand out as a hyper-organized rectangle/cube in the base, that doesn't seem as connected to it as a messier design. Of course, it doesn't mean the designs have to be 100% spaghetti, but they shouldn't be what you see with curated schems.

**Comment by terminalmaid** [comment]
i guess, still needs better schems

**Comment by barokvanzieks** [comment]
g
