### ISSUE TITLE
Hello, I would like to offer the opportunity to make a PVP mode with two different bases and waves.

### ISSUE THREAD

**Issue by FithingGolem** [Anuken/Mindustry-Suggestions#3944]
### Describe the content or mechanics you are proposing.

When creating a map with PVP mode and waves, enemies did not die during spawn

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

 This will allow several people to develop separately from each other, compete against each other, but at the same time also fend off the waves.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LeoSko** [comment]
There was a map on ranked with exactly that, and nobody liked it for several reasons, which lead to removing the 3rd party in a week.

Basically, if you go for PvP, you want to focus on your real opponent, and AI is just an annoying part.

Also, if you want to "compete" in terms of how you are better than the other on "vs AI" scale, simply use attack or survival mode and compare results.
