### ISSUE TITLE
Note instruction

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3946]
### Describe the content or mechanics you are proposing.

Add the instruction which has a field for writing a text with variable field size and is skipped by the processor when executing the code

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To note what every part of the code does like in the regular programming languages. "Write" doesn't work for this use because it writes text to messages and can mess up your code

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
Comment instructions has been suggested a thousand times, and ignored just as much.

If you want to have comments (as well as jump-to-label and other useful stuff), use an external editor instead of the processor GUI and then import the code into a processor.
