### ISSUE TITLE
Phase conveyors should be able to connect to bridge conveyors (but not the other way around)

### ISSUE THREAD

**Issue by chiptheunholy** [Anuken/Mindustry-Suggestions#3948]
### Describe the content or mechanics you are proposing.

phase conveyors should be able to deliver items to bridge conveyors, but not the other way around

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I thought it would be a bit more convenient for organization purposes

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
Sure it might be convenient, but that would just halve the cost of phase conveyors-pairs, not to mention what would happen to the energy cost.

I think it should stay, take it as a puzzle challenge to make your factory work without this feature, I don't see how one could be very troubled without this.

**Comment by ziszlo** [comment]
это могло бы разнообразить головоломку в построении больших схем но взамен нужно було бы повысить стоимость фазового моста и длину моста между 2 связаными фазовыми мостами , длина между фазовым и обычным мостом должна быть меньш чем между фазовым и фазоым но больше чем 5 блоков

**Comment by chiptheunholy** [comment]
> Sure it might be convenient, but that would just halve the cost of phase conveyors-pairs, not to mention what would happen to the energy cost.
> 
> I think it should stay, take it as a puzzle challenge to make your factory work without this feature, I don't see how one could be very troubled without this.

I said in the description of my suggestion that phase conveyors can connect to bridge conveyors. However, I also said that bridge conveyors cant connect to phase conveyors, so that phase conveyor chain prices cannot be cut in half. That's why I said "but not the other way around". Although, you are right on the front that it is not entirely necessary. It is really just a thing for convenience. I could be wrong about most things about the idea though, so forgive me if I am wrong. Thanks!
