### ISSUE TITLE
About processing blocks

### ISSUE THREAD

**Issue by AYJS** [Anuken/Mindustry-Suggestions#3949]
### Describe the content or mechanics you are proposing.

Reading information board and string operation

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I hope the author can add reading information board and string operation (slicing, etc.) in the processor. Thank you

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X] **You havehave** read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

> ### A few things you shouldn't suggest
>
> ###### These have been proposed many times already, and I won't be adding them.
>
> - Any sort of string manipulation in logic (reading from message blocks, reading characters, splitting strings, etc)
