### ISSUE TITLE
Weather, Rovers and Formations.

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#395]
Hey, ill be making a few suggestions, as follows:

### Weather
Weather might be a neat addition. Since the game revolves around a post-apocalyptic spore-dominated world, spore outbursts or similar might be a cool addition. They could also add random effects to the battlefield, some of the ideas are as follows:

- Clear: No effects.
- Cloudy: Slightly darker surroundings and reduced solar panel efficiency.
- Rain: Aesthetic rain effect, Solar panel efficiency further reduced. Possible new block 'Water collector' generates water.
- Storm: Solar panel efficiency reduced to a negligible amount, Possible block 'Water collectors' generate more water.
- Spore Outburst: Vision hazed, solar panel efficiency reduced.
- Haze: Vision hazed slightly, solar panel efficiency increased.

The above would also go well with a Day/Night cycle, with solar panels rendered unusable during the dark, along with less visibility, encouraging players to rely on illuminators. Visibility could also reduce Turrets' range and/or inaccuracy or turrets, giving players another reason to rely on illuminators.

### Rovers
Too much to explain here, tl;dr - a new vehicle type would be cool, accelerate with W, steer with A/D and decelerate/go back with S. It would be a fun addition if Rovers would be able to ram ground units to knock them off path or ram rovers to damage them [ramming from the side deals the most damage, with back being slightly more armoured and the front nearly impenetrable][also note that its a good idea to not have its weapons spinal, so that the weapon shoots where the mouse is, without the need to align itself]. Some ideas are as follows:
- A player-type which turns into a force projector when not moving.
- A player-type which turns invisible when moving below a certain speed
- A player type which shoots sapping shots, which, instead of dealing damage, sap power nodes or power-run structures of energy.
- A player-type which assumes control of enemy units? [possibly by ramming into them really hard, then climbing on their head and pull some dead space 2 climb-inside-body shiet, and jumping outside the body after it took too much damage.]
- A player-type which is a kamikaze time-bomb?

### Formations
Survival modes are too easy because the enemy has no plan - All units rush in at their maximum speed while attacking the closest enemy. Having formations for enemy and friendly mechs - So that ground troops have their 'meat-shields' or tanky units up front, with the fragile damage dealers behind them, healers scattered in, crawlers or similar 'kamikaze' units coming after the first wave to further damage enemy bases, bombers making synchronised bombing runs and gunners making strafing runs to confuse air defences. This could encourage the addition of an Improved Command Centre, which can help organise units, command them at certain points to make strafing runs or pushes, or to change formations mid-battle. Some of the formations could be the simple Line, Wedge, Reverse-wedge/claw and Defensive circle.
This brings to another aspect, How to break these formations. It would be a good idea to have turrets/kamikaze units which 'malfunction' the enemy units, causing them to host erratic movement patterns, shoot randomly or break down completely. Turrets which have special ammo canisters for the same might also be good, phase fabric or a new material might fit well.

For reference to the third Suggestion, i'm linking a pdf on AI, hope it helps.
[Artificial_Intelligence_for_Games_Second_-_Ian_Millington_John_Funge.pdf](https://github.com/Anuken/Mindustry-Suggestions/files/5050760/Artificial_Intelligence_for_Games_Second_-_Ian_Millington_John_Funge.pdf)
Thanks for reading.

**Comment by Anuken** [comment]
> Weather

Most of the weather you mentioned is already implemented in V6, as is a day/night cycle. See the completed items in the Trello and the [progress report on Steam.](https://steamcommunity.com/games/1127400/announcements/detail/2209520752605604724)

> Rovers

Some of the units you've mentioned are already implemented. As for rovers themselves, I don't think they would work well in this game - AI-controlled units with steering wouldn't work very well, and I don't think many players would use them, as terrain often doesn't allow much space for wheeled units or ramming.

> Formations

This is also present in V6 - units can control others in formation.
