### ISSUE TITLE
A real absolute ban on mixing tech.

### ISSUE THREAD

**Issue by Helium-ion** [Anuken/Mindustry-Suggestions#3950]
### Describe what you would like changed, and why.

That "hint" now looks like a superficial behavior. It doesn't actually do anything. If I want to create a "mix tech" map, I simply duplicate an existing "mix tech" map. And there are mods that allow direct creation of "mix tech" maps. So I suggest to cut all ties between Serpulo tech and Eriekir tech completely and never have any relationship between them.

### Describe the changes you want to propose. Include possible alternatives.

Deny any interaction between Serpulo and Erekir's blocks. For example, conveyor belts can't carry beryllium, Erekir's core doesn't accept all Serpulo's resources, and Erekir's pipes can't carry liquids for Serpulo's blocks.
Import and export of mix tech maps is absolutely forbidden. Disables starting and loading a mix tech map.
Remove the <any> option entirely instead of giving a hint.
It is absolutely forbidden to import and export blueprints that have both techs at the same time.

**Comment by Helium-ion** [comment]
Maybe this seems radical, but it's the right decision for the game.

**Comment by SomeonesShade** [comment]
I don't really get why mixtech is so servere of a distain for some people, the "ban" isn't a ban, its meant to stop new people from thinking that erekir is an extension of serpulo, and instead should be treated as separate sets, to understand how the mechanics work for each group.

But that doesn't mean mixtech isn't all bad, only full on unbalanced mixing is the worst part about it. Where the map creator can just create banning blocks, or some world proc interactions to create a unique feeling to a certain map.

**Comment by IVV-NCX** [comment]
Why? Just why?

Just turn it off if you don't like it so much???? It ain't gonna harm you?

**Comment by Sector171** [comment]
Useless suggestion, just useless totally
If the map maker wanted to make a mixed tech it is up to him, and it is his responsibility to make the balance.
Not balanced? You don't like mixed maps? Just don't play these maps, easy.
Mixed map has lot of special fun.

**Comment by catreplicators** [comment]
What if someone wanted to have Serupulo logic but Erikir directional routers? This stops the fun of such a map.

**Comment by LampbuIb** [comment]
Isn't the point of a game to have fun? what would your reaction be if sandbox or anything even remotely not challenging was removed? would mindustry be a fun game then?

The warning is enough. let people know what they're getting into, then let them do whatever they want.

**Comment by Plastel** [comment]
"holy shit mixed tech is going to kill me AAAAAA i must create a suggestion to kill it inmediately"

> Why? Just why?
> 
> Just turn it off if you don't like it so much???? It ain't gonna harm you?
>

**Comment by littlekatter330** [comment]
@Anuken please revert this
