### ISSUE TITLE
Code comment

### ISSUE THREAD

**Issue by relrypesan** [Anuken/Mindustry-Suggestions#3953]
### Describe the content or mechanics you are proposing.

Comments for the processor codes, with this block it would be easier to identify each section within large codes, in addition to being able to visualize it within an editor such as VS Code.
I have some codes with many lines and others exceeding 1000 lines, it would be very good to have a comment block for a better identification of each part of the logic.

- **In the Text Editor - (Click on the image to expand)**

<img src="https://user-images.githubusercontent.com/33105541/189547479-41412718-4f22-4e36-a9a7-8b03f0b93908.png" width="300">

- **In the in-game Code Editor - (Click on the image to expand)**

<img src="https://user-images.githubusercontent.com/33105541/189546948-ce0faa0d-6f99-4ad4-8003-3bada1e6c81e.png" width="300">

- **Add comment in game - (Click on the image to expand)**

<img src="https://user-images.githubusercontent.com/33105541/189546950-75d1c07f-9059-4ccf-858d-9bac3973ffe2.png" height="200">

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Developers use code editors and versioning in git when there is a lot of code involved, with this implementation the comments written inside the editors would not be lost when copied to the game or from the game to the editors.
This idea may seem like something very simple, but it would help a lot to see this functionality within the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Phinner** [comment]
Mate, check #3946, #3491, #2487, and more...

**Comment by RelryPeSan** [comment]
> Mate, check #3946, #3491, #2487, ...

Sorry. I had done some research on the issues but I think my filter was dirty.

I see that this type of functionality is well requested. And it seems that other colleagues also feel the same need to use an external editor and the game itself to assemble their logic.

**Comment by WhyNotDogie** [comment]
add this @Anuken
