### ISSUE TITLE
more unit command options

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#3954]
mass target selection, unit follow and help friendly unit (for OKT), unit move to specified block after it is destroyed.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

0 units do not stop healing, building , as well as attacking after taking them under command (for poly, mega)
1 after destroying a block to which the unit is going to reach that location instead of standing somewhere far from the specified location, this will reduce the amount of control needed from the player to clear the area, although this function would ruin the ability to send units to destroy the block and stay in place.
2 units can specify several targets by holding PKM + Stirl and selecting an area, the units will destroy everything in the selected area and follow the units that are in the selection, this will make it easier to hunt for maneuverable numerous enemy units.
3 the ability to click on your units or players, after which the units will chase him, help in construction, shoot at the same point where the player shoots, this will give the oct the opportunity to protect the attacking units and not (sit 20 octa over one toxoid not even participating in the attack ) also this opportunity to allow you to build more efficiently without relying on the strange intelligence of meg and poly helping in spontaneously helping in construction. This feature will return the functionality of the 6th version of units to defend and help construction, but will not worsen the new unit management system

перевод для котика любителя аниме девочек
0 юниты не прекращают лечить , строить , также как атаковать ,после взятия их под командование (для поли , мега)
1 после уничтожения блока к которому шол юнит юнит дойдет до этого места а не встанет где то далеко от указаного места , это уменьшит нужное количество контроля от игрока для зачистки местности ,хотя эта функция испортила бы возможность послать юнитов уничтожить блок и остаться на месте. 
2 юнитам можно указать несколько целей зажав пкм+стирл и выбрав область , юниты будут уничтожать все в выбранной области и ходить за юнитами попавшими в выделение , это упростит охоту за маневренными многочисленными отрядами противника . 
3 возможность кликнуть по своим юнитам или игрокам , после чего юниты будут преследовать его , помогать в строительстве , стрелять в ту же точку куда стреляет игрок , это даст окту возможность защищать атакующих юнитов а не (сидеть 20 октами над одним токсоидом даже не участвующим в атаке)  также эта возможность позволить эффективнее строить не опираясь на странный интеллект мег и поли помогающих в спонтанно помогающих в строительстве .эта возможность вернет функционал 6 версии юнитов оборонять и помогать строительстве но и не ухудшит новую систему управления юнитами

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by fghjk455rg** [comment]
Идея слишком узконаправленая

**Comment by ziszlo** [comment]
> Идея слишком узконаправленая
narrowly focused? , are you serious? a third of the entire gameplay of the Mindustri company is occupied by attacking gameplay, not to mention the maps and servers of the "attack" mode, improving the innovations in the mechanics of commanding units will greatly improve the gameplay, and that is, the popularity of the game, which is exactly what the developer wants, if you have something to answer, speak detailed.
узконаправленная? , ты серьезно? треть всего геймплея компании миндустри занимает атакующий геймплей , не говоря о картах и серверах режима "атака" , улучшение новой механики командования юнитами сильно улучшат  геймплей а то есть и популярность игры чего как раз и хочет разраб , если есть что ответить говори развернутое .
