### ISSUE TITLE
Into space with Erekir

### ISSUE THREAD

**Issue by fghjk455rg** [Anuken/Mindustry-Suggestions#3955]
### Describe the content or mechanics you are proposing.

There is currently on Erekir no alternative railgun for interplanetary deployment.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To make a launch pad in which a rocket would be created. After its creation, it will need to be refueled with oxygen and hydrogen.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Breadyboi69** [comment]
This will most likely be done. however erekir's campaign is not complete yet.
