### ISSUE TITLE
Game suggestions

### ISSUE THREAD

**Issue by StevenZhai1** [Anuken/Mindustry-Suggestions#3956]
### Describe the content or mechanics you are proposing.

First things first, thank you for reading, and hopefully, these suggestions might help you. Some of them might not even be possible since I do not know about game development, but the following is what I think will be nice to have.

1. Game popularity. I think this is such a great game to have more players it's just not a popular or not really known game.
2. Even better logic or unit controlling like the mine option can have a sub-tab that you can click on what to mine or to mine to the set amount etc. And click to set the destination 
3. Power, resources, and units display/stats/graph. Some people have power display schematic and items schematic, but since there are a lot of mods available, the resource table may be filled easily, covering the game and having to hide the GUI all the time.
4. Water platform to build on top of the water. Some maps have good resources but a lot of water which makes the buildings and conveyors extremely hard and limited. And more windswept island map, which spawns naval units in the waves, and having those platforms, you can build walls even in the deep water is great or at least build unit healer in the deep water. Going even further submarine will also be interesting for only building targeting and is invincible while moving inside the water and comes out when attacking.
5. Miner units. Even the mono, poly... can mine, but they are very limited, allowing to mine only lead and copper and titanium with mega. having more units will be just cool and more easier to adjust the resource mining option instead of using logic.
6. Steam Mindustry versions or the next suggestion
7. Very important: Mod incompatibility. There are many mods that are outdated or released for pre-alpha while the steam version is the latest, and a lot of mods are just not compatible. some of them are outdated or updated to the prealpha versions and the old versions are not longer available for the lastest version for steam.
8. The resources from the mods don't ever get implemented to the campaign have to build the map manually to have access to those, while the research the mods are always locked because the resources never get researched.
9. Having more sectors and more unique things on the new planet is good, but I think that the time that it takes to give every planet exclusive objects and building makes the game development extremely hard and time-consuming, while the game progression feels like it being reset since buildings and research items cannot be used on the other planets.
10. Vanilla enhanced mod which no longer exists, has great items that are very good, like a phase bridge, faster conveyor, a powerless drill that can mine everything but slower, 
11. More conveyors like thorium or surge conveyor bc the platinum is very hard to control since sometimes the other stuff doesn't work as intended like routers, junction, bridge etc. makes that very hard to use because it slows down the resource, especially the plastanium conveyors.
12. I think it is very important to include stuff from the mods since more downloads it has meant more in demand than the feature it is while it is available in more versions and not having a lot of mods being all not compatible.
13. Schematic export. (it can also be used for those who have a steam version and also a free downloaded version)
14. Similar to suggestion 9, instead of implementing brand new items that are all completely exclusive to that planet is better to have more progression, like buildings with stronger items and enemies.
15. Give the game a story so it makes more sense and has a better progression feel. It's good to start with text only it's very easy and an interesting feature.
16. Better resource export system like launchpad but better.
17. Better planet visuals like resources and cores being launched at enemy bases etc.
18. Transport units (not rails), flying units (also, I realize something people who use support units (mining) are kinda annoying that it covers the screen and push you around the map. It will be good to have an option to hide them)
19. Upgrade system will be cool being able to upgrade the tower or build an MKII of the same tower demanding more resources or energy. But I think this will be hard to balance. Otherwise, maybe kinda, OP

I think that's all of my suggestions. It's impossible to implement all of them but thank you for reading it. maybe its too much XD

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Most of this is pretty much explained in what I have proposed, but yeah, in short, it will make the game have a better progression, better time management, and make the game to have "more sense."
It's incredible how good this game rating on steam has but still doesn't have that many players I think ads should exist for good things like this game and not boring consumable products, I guess lmao.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
it's hard to read, even harder to understand, when you want a function you should first briefly describe it, then describe its operation in detail and describe how it improves the game, a monolith of loosely coupled small sentences is bad, but I agree with many of your ideas.
the game needs new weather conditions and not just spore rain that improves spore generators, but those that blow away units, terraform the area by flooding the coast and making shallow waters deep, the ability to dig water for the sake of building on it or dig wells for the sake of obtaining liquids.
the game needs a story inside the game, and the story is not formal but part of the game, that is, if the enemies in the company on the serpulo are not the same units as ours, but spores, distorted, strange, but for some reason functioning, significantly diversify the flora, for example, trees that need to be destroyed and in place their roots will turn out to be ore, or a tree can be dug with rock crushers and get spores, oil, coal. Add a fauna of incredible creatures that behave noturally by walking back and forth and attacking in new ways, for example, pounce on our unit and attack it with claws at close range.

это сложно читать, понять еше труднее , когды ты хочеш какуюто функцию следовало бы сначала кратко опистаь ее после развернуто описать ее действие и описать как это улудшит игру , монолит слабосвязаных мальенких предложений это плохо , но я согласен с многими  твоими идеями .
игре нужны новые погодные условия и не простоспоровый дождь что улудшает споровые генераторы а те что удувают юнитов , тераформируют месность затапливая побережья а неглубокие воды делая глубокими , возможность  закапывать воду ради возможности строить на ней или же выкапывать скважины ради получения жидкостей .
игре нужна история внутри игры причем история не формальная а являюшяяся частью игры , тоесть если враги в  компании на серпуло будут не такими же юнитами как наши а пораженые спорами , искареженые , странные но почемуто функционируюшие , значительно разнообразить флору например деревья которые нужно уничтожить и на месте их корня окажется руда или же дерево можно копать дробителями скал и получать споры , нефть , уголь . добавиьт фауну невероятных сушеств которые ведут себя нотурально ходя туда сюда и атакуют новыми образами , например набросться на нашего юнита и атаковать его когтями вблизи .
