### ISSUE TITLE
Peaks is slightly broken

### ISSUE THREAD

**Issue by Dwal32s** [Anuken/Mindustry-Suggestions#3957]
### Describe what you would like changed, and why.

Peaks should have a changing world border, similar to other maps like Atlas.
Currently players can build a small ship refabricator factory, then fly their Averts over to enemy cores before constructing two beam towers.
This is an issue as the enemy will not construct **any units** until the player builds two beam towers, thus you can beat the entire map without any damage.

### Describe the changes you want to propose. Include possible alternatives.

Adding a world border that recedes after completing the beam node task would fix this completely, and I do not know of alternatives.

**Comment by Epowerj** [comment]
Should be fixed
