### ISSUE TITLE
Picked Block Orientation

### ISSUE THREAD

**Issue by kangzoel** [Anuken/Mindustry-Suggestions#3958]
### Describe the content or mechanics you are proposing.

I think it'll be helpful if I can pick a block (by middle click) with the **_same orientation as the source block_**. Currently the orientation is set to the same as previously placed block (not the source block).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can be useful if I wanna for example place a single belt in between two routers based on the previous placed belt, so I don't need to rotate it manually nor overshoot the belt and make it back to single belt to match the orientation I wanted.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WhyNotDogie** [comment]
this is a good quality of life addon, thanks for suggestinf
