### ISSUE TITLE
There should be more command center commands such as patrol

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#396]
**Describe the content or mechanics you are proposing.**
Patrol would be a helpfull command which would make your units go around your base, they would go in single file lines following the infastructure. Upon seeing a enemy unit they will call in all units near them to report to their location where they will all begin fighting. If all troops die they will call in all idle units everywhere to report to the enemies location. There will also be a special building called a Watch Tower/Radar Tower which will detect any enemy units in its range and will fire a laser at it, which does no damage but tells all nearby units to report to the enemies location, the location will keep changing due to the enemy's movement.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will give units a use in survival world as rally is a stupid command as the units attack and then get aggrivated. Retreat just turns them into meat shields for the core + a obstruction for the player's building and attack is just turning the units into kamikaze.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Irrelevant. The Command Center Block is not a block that exist in 6.0
