### ISSUE TITLE
Show the total construction cost for what you're constructing.

### ISSUE THREAD

**Issue by Urkikk** [Anuken/Mindustry-Suggestions#3962]
### Describe the content or mechanics you are proposing.

While building, there will be a hud that shows how many resources you're going to use to build all the things you wanted.

Like if you want to build 20 conveyers it'll show you need 20 coppers, the number of resources updated as they build

Optionally, also include what other players are going to take too if both happen to use the same resource on different things and they both together will make it not enough, maybe show yellow number if it is still possible to build if other persons stop, or red number when can no longer afford it.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Give player information on how many resources they're going to take in order to build.
Show whether they have enough resources to build all of these or not, and how much they need to be able to build all of them.

Help make sure that they have exactly enough resources to build and not just stuck midway.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaysonnn80** [comment]
yes pls

**Comment by ziszlo** [comment]
КРУТАЯ ИДЕЯ АНЮК СДЕЛАЙ ЭТО ПОЖАЛУЙСТА!!!

**Comment by WhyNotDogie** [comment]
add this @Anuken
