### ISSUE TITLE
Add abort mission/withdraw option

### ISSUE THREAD

**Issue by leroyvn** [Anuken/Mindustry-Suggestions#3963]
### Describe the content or mechanics you are proposing.

Add the option to abort a mission or withdraw from a territory.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Bad decisions may put you in a situation where recovering is much more difficult than starting over, sometimes even resulting in unpleasant struggle or agony. In such cases, having the option to withdraw from a territory or abort a mission and start over would save time and avoid some frustration.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Breadyboi69** [comment]
You can already do this

**Comment by leroyvn** [comment]
Can you explain how?

**Comment by leroyvn** [comment]
For the record: this feature is indeed accessible from the mission information screen (planet view).
