### ISSUE TITLE
synchronization with the server

### ISSUE THREAD

**Issue by oleg228503** [Anuken/Mindustry-Suggestions#3964]
### Describe the content or mechanics you are proposing.

I suggest adding synchronization with the server so that another player downloads data from this server to his device.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This makes it easier to access other servers so that you don't have to look for a lot of mods.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Mods can have executable Java/JavaScript code, I think this would be a pretty bad security vulnerability

**Comment by LeoSko** [comment]
@end-me-please like you said, mods *can* have them, but mods menu is still in the game, no wonder why?

Regardless, Anuke already told he won't be doing that as an "infeasible" feature.

**Comment by oleg228503** [comment]
@LeoSko The function exists, the same Barotrouma has such a function, but in the Lua language
