### ISSUE TITLE
Mindustry PvP

### ISSUE THREAD

**Issue by antimion02** [Anuken/Mindustry-Suggestions#3965]
### Describe the content or mechanics you are proposing.

I thought about brining in a Mindustry PvP ranked system, 
many other games have a system like this so i though maby mindustry can get one too,
the way itll work is that you get an extra button in the menu where you can enther the "queue" or a sperate screen where you can see your rank, and stuff like that.
The players will then be sent to different teams on offical PvP maps, you can create a channel for these in the offical discord where you can suggest PvP maps for the PvP, you could also do 2v2 / 4v4 or similar game modes but i dont think that is that good of an idea since many new people can come in there and ruin someones experience.
Also i think it should be a steam only feature because with steam you could technicly track someones name and preserve his "rank" to his steam account. 
I hope you all like this feature idea have a great day.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will ad a whole new game style of mindustry, and a lot of more action too i think, many players will defenetly play a lot of it because the unoffical PvP servers are all played much too so i think a offical PvP would be good too.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by stuffyAI** [comment]
This might be one of the most useless and undescriptive captions ever...

Aside from that, this is incredibly tedious to implement for what value it actually gives, have you talked about this with people on the Discord?

**Comment by end-me-please** [comment]
you should play ranked if you want that
