### ISSUE TITLE
возможность задать отряду цель для следования дружественный юнит. (русское описание ниже английского)

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#3967]
### Describe the content or mechanics you are proposing.

poly, mega, oct, should help the player but their intellect interferes with this.
if oct followed the units you need and did not switch to the one he wants, it would be more convenient.
poly and mega followed a small number of players on the server rather than rushing between many players.
RATE THIS POST LIKE OR DISLIKE AND DON'T PASS BY.
поли, меги, окт , должны помогать игроку но их интеллект мешает этому.
если бы окт следовали за нужным вам юнитам а не переключался на того который ему вздумается было бы удобнее.
поли и меги следовали за небольшим количеством за игроком, на сервере а не метались между многими игроками. 
ПОСТАВЬ СВОЮ ОЦЕНКУ ЭТОЙ ЗАПИСИ ЛАЙК ИЛИ ДИЗЛАЙК А НЕ ПРОЙДИ МИМО.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

RATE THIS POST LIKE OR DISLIKE AND DON'T PASS BY
implementation description: took command of the necessary units, aimed at a friendly unit or player (for example, himself), after which the units follow the given unit or player, remaining in a certain radius (so as not to be pushed anywhere), also the units help in construction, shoot at the place where their target is aiming to follow, if their weapon has a healing effect they will automatically locate and heal those blocks but keep following the target,

in v7, the functionality of taking units to follow was removed and replaced with command, which of course added an attacking functionality but spoiled the auxiliary one, such a simple move would fix it and improve the quality of the game.
alternatives : return the command functionality from v6 as an addition to the current v7

I checked the trill but I'm not sure that I read everything

ПОСТАВЬ СВОЮ ОЦЕНКУ ЭТОЙ ЗАПИСИ ЛАЙК ИЛИ ДИЗЛАЙК А НЕ ПРОЙДИ МИМО
описание реализации : взял под командование нужных юнитов , навелся на дружественного юнита или игрока(например себя) , после чего юниты следуют за данным юнитом или игроком оставаясь в некотом радиусе(чтобы не толкали куда попало) , тажке юниты помогают в строительстве ,стреляют в место куда целится их цель следование, если их вооружение имеет лечащий эффект они будут автоматически находится и лечить эи блоки но продолжать следовать за целью , 

в в7 был убран функционал взятия юнитов для следования и заменен на командование , что конечно добавило атакующего функционала но испортило вспомогательный , подобный простой ход исправил бы его и повысил качество игры .
альтернативы : вернуть функционал командования из в6 как дополнение к текущему в7

трело я проверил но не верен что прочел все 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
дайте свой отзыв по данной идее
give your feedback on this idea

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Anything involving bringing back the old command system

**Comment by ziszlo** [comment]
> ### A few things you shouldn't suggest
> ###### These have been proposed many times already, and I won't be adding them.
> * Anything involving bringing back the old command system

this is not a return of the old, but an improvement on the new command system, a comparison with command v6 was an example.
I want to hear arguments as to why being able to target units to follow is bad or good ?
