### ISSUE TITLE
Masochist esque walls?

### ISSUE THREAD

**Issue by Yoroppa** [Anuken/Mindustry-Suggestions#397]
**Describe the content or mechanics you are proposing.** A wall which produces small amounts of power which the amount if power is dependent on the amount of damage done to a battery,block or turret behind it when fired at. It will have low hp (Around titanium wall). It will be rather expensive taking 20 Copper, 30 Lead, 5 Titanium and 13 Silicon per 1x1 block.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will help with defence a small bit by filling a role of self powered (ish) healing or defence.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Sounds similar to surge. Perhaps a combination of surge plus plast walls or even a battery would do the same thing.
