### ISSUE TITLE
Neoplasm Infecting Water Tiles

### ISSUE THREAD

**Issue by Insect1111111111111** [Anuken/Mindustry-Suggestions#3971]
### Describe the content or mechanics you are proposing.

Make neoplasm infect water tiles like deep water and the oceans, and maybe make it toggleable.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add more risk to the neoplasma reactors and it could be used as a biological weapon against enemy teams that depend on water.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
is neoplasm infected water tiles it would lag the game.
