### ISSUE TITLE
Please bring back the group control commanding system

### ISSUE THREAD

**Issue by vohai2003** [Anuken/Mindustry-Suggestions#3973]
### Describe what you would like changed, and why.

The RTS-like commanding system is good, but I find it difficult to use without supporting from group commanding system.
The RTS-like system currently not allow me to make boostable unit (Nova tree) to fly together. It also not allow all unit to open fire at a same time with player.
Attacking units lack the ability to follow player.
When being ordered for open fire at target, units always moving toward the target, even though it can shoot from afar.

### Describe the changes you want to propose. Include possible alternatives.

I'd like the group control commanding system to come back. Not necessary to replace the RTS commanding system; I'd rather see them support each other.
Or adding an option "Assisting player" for attacking unit to make them follow user and do anything user do (shooting, moving, boosting if possible)

**Comment by Sector171** [comment]
Very important and real issues need to be solved.
I will add, attacking while moving to attack a specific target, example: I want group of Corvuses to attack foreshadow, in this system the units will keep shooting useless stuff while moving slowing down their speed too much and making this attack useless, I don't want the units to attack anything till they destroy the target.
But the solution not by returning back the old system ofc, but by supporting this RTS system.
I suggest a tiny rectangle control panel in the corner (will appear if the player is in units command mod ) this control panel has few options like attack while moving, formations, boosting....when the player click it , it shows options taps. But it should be tiny and player friendly.

**Comment by ziszlo** [comment]
I have described this many times, but why only you were noticed, magic ...
the command system is cool but it needs to be improved and finalized, I agree with you.

**Comment by ziszlo** [comment]
> Very important and real issues need to be solved. I will add, attacking while moving to attack a specific target, example: I want group of Corvuses to attack foreshadow, in this system the units will keep shooting useless stuff while moving slowing down their speed too much and making this attack useless, I don't want the units to attack anything till they destroy the target. But the solution not by returning back the old system ofc, but by supporting this RTS system. I suggest a tiny rectangle control panel in the corner (will appear if the player is in units command mod ) this control panel has few options like attack while moving, formations, boosting....when the player click it , it shows options taps. But it should be tiny and player friendly.

for example, you can add a function to help a unit by simply selecting a unit and clicking on a unit or player, after which the units will follow him and help in construction, attack where the main unit shoots.

 it would be nice to have a function to sit in another unit, for example, by selecting a corvus and clicking on an oct: oct will fly up to the corvus and pick it up, double-clicking on the ground will set up a landing point where oct will fly up and put the corvus.

it would also be convenient if the squad could be ordered not to shoot / shoot / shoot where the player shoots, does not heal / heal,

**Comment by vohai2003** [comment]
> > Very important and real issues need to be solved. I will add, attacking while moving to attack a specific target, example: I want group of Corvuses to attack foreshadow, in this system the units will keep shooting useless stuff while moving slowing down their speed too much and making this attack useless, I don't want the units to attack anything till they destroy the target. But the solution not by returning back the old system ofc, but by supporting this RTS system. I suggest a tiny rectangle control panel in the corner (will appear if the player is in units command mod ) this control panel has few options like attack while moving, formations, boosting....when the player click it , it shows options taps. But it should be tiny and player friendly.
> 
> for example, you can add a function to help a unit by simply selecting a unit and clicking on a unit or player, after which the units will follow him and help in construction, attack where the main unit shoots.
> 
> it would be nice to have a function to sit in another unit, for example, by selecting a corvus and clicking on an oct: oct will fly up to the corvus and pick it up, double-clicking on the ground will set up a landing point where oct will fly up and put the corvus.
> 
> it would also be convenient if the squad could be ordered not to shoot / shoot / shoot where the player shoots, does not heal / heal,

The "Assisting player" option of supporting flying drone (Poly-tree) is already just like your first idea. The Poly will follow you and help you in construction.

**Comment by SuperThunder958** [comment]
I think there should be a way to have the old command block back and there be a settings where you are able to have the new command thing, or the old command thing, or both of the command things

**Comment by itcannotbe** [comment]
> I think there should be a way to have the old command block back and there be a settings where you are able to have the new command thing, or the old command thing, or both of the command things

Bringing back the old command system (Command Block) is out of the question.

**Comment by ziszlo** [comment]
> > I think there should be a way to have the old command block back and there be a settings where you are able to have the new command thing, or the old command thing, or both of the command things
> 
> Bringing back the old command system (Command Block) is out of the question.

stop repeating the rules, the opinion on the idea of publication is much more important, and not the commentary.
