### ISSUE TITLE
Config for constructor, payload source

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#3974]
### Describe the content or mechanics you are proposing.

Was trying using world processor to set config of small constructor to something, then I realized it is not supported!!
Really I didn't find any reason why can't we control this using world processor.
Add ability to use config with constructors, payload source and similar building. In addition to be able to use sensor of course.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Map makers may need this.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
This would probably be good for some oddly complex unit construction.

**Comment by itcannotbe** [comment]
> This would probably be good for some oddly complex unit construction.

I think you misunderstood the suggestion.
