### ISSUE TITLE
update from command prompt

### ISSUE THREAD

**Issue by pizzapiepizza** [Anuken/Mindustry-Suggestions#3975]
### Describe the content or mechanics you are proposing.

It would help me if I could update mindustry from the windows 10 command prompt so I could create a batch file to update mindustry without opening it I don't want to ask to much from you so if you don't add it, I'll understand. also sorry for the bad English.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It might help people on slower computers because then they won't have to open up the game and wait for it to load to update it.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
сколько у тебя длится загрузка?

**Comment by pizzapiepizza** [comment]
> How long does it take you to download?

About 1 minute but I meant how it could help others that had a slower computer or was going to play it later on under how it could improve the game.

**Comment by pizzapiepizza** [comment]
It also doesn't always update properly like when it downloads the update restarts then it freezes.
