### ISSUE TITLE
v5 and v4 steam beta

### ISSUE THREAD

**Issue by littlekatter330** [Anuken/Mindustry-Suggestions#3979]
### Describe the content or mechanics you are proposing.

allows you to play v5 or v4 on steam

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

you can play with v5 mods on the steam workshop

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Phinner** [comment]
This is completely **unnecessary** to implement v5 and/or v4 versions on steam. I don't even know a single steam game that allows you to play on an older version. If you really want to play Mindustry v5 with mods, you can easily grab the version you look for in the [Mindustry Github repository](https://github.com/Anuken/Mindustry/releases), and the vast majority of mods are available Github.

**Comment by end-me-please** [comment]
You can either play v4/5 without steam, or replace the .jar file in your steam files with the old version.

**Comment by Phinner** [comment]
> or replace the .jar file in your steam files with the old version

Wait, that's illegal.

**Comment by shobu13** [comment]
@Phinner for general culture, into the radius let you play the V1 of the game who was very different of the current state of the game :)
 but your right.

**Comment by littlekatter330** [comment]
@Phinner I changed my files to be more like github

**Comment by Phinner** [comment]
You're a madman.

**Comment by littlekatter330** [comment]
why

**Comment by littlekatter330** [comment]
and how

**Comment by littlekatter330** [comment]
@Phinner

**Comment by Phinner** [comment]
I just did not expected you will do it. Well, let's hope steam does not do funny stuff.

**Comment by littlekatter330** [comment]
@Phinner steam works just as well as mindustry when you buy it don't know how

**Comment by littlekatter330** [comment]
and @Phinner I can update, and look at the files and change them up

**Comment by Phinner** [comment]
Wait, we are talking about you replacing steam files right ?

**Comment by littlekatter330** [comment]
yes

**Comment by Phinner** [comment]
Ok nice

**Comment by littlekatter330** [comment]
how do i switch to v5 or v4 on steam

**Comment by littlekatter330** [comment]
i do have mindustry.jar and the source code

**Comment by littlekatter330** [comment]
what do i do with them

**Comment by littlekatter330** [comment]
oh and it is necessary for people who want to play with snek, old scorch, mods, and fun

**Comment by littlekatter330** [comment]
@Phinner

**Comment by Phinner** [comment]
Again, steam does not allow playing older versions of their games.
But if you ***really*** want to do it, go in the Mindustry game files, in the jre directory, replace desktop.jar with your own Mindustry version (same name).
Be aware that it might not work due to missing classes in the bundled jre and that you won't be able to play with older Mindustry content from the Steam workshop.

At this point, just play older versions of Mindustry without steam.

**Comment by littlekatter330** [comment]
i can't open .jar files cause of notepad being dumb @Phinner

**Comment by Phinner** [comment]
You need java installed, search adopt open jdk and download java 17

**Comment by littlekatter330** [comment]
how do i do that?

**Comment by littlekatter330** [comment]
@Phinner

**Comment by Phinner** [comment]
I give up, ask in the discord server.
