### ISSUE TITLE
Logic-button 

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#398]
Anuke, please add "logic-button". When you tap to this button, the code which can be edited by long pressing of the button was executed.

**Comment by RoyalFunnyDude** [comment]
I think...there's already a logic system in 6.0 already

**Comment by RoyalFunnyDude** [comment]
![image](https://user-images.githubusercontent.com/34819172/90090339-9c353200-dcd8-11ea-9f31-5381c4fd33cf.png)
![image](https://user-images.githubusercontent.com/34819172/90090358-a9eab780-dcd8-11ea-943e-16191a4da1c6.png)
![image](https://user-images.githubusercontent.com/34819172/90090368-b0792f00-dcd8-11ea-88ef-7a9bbfb3c2c1.png)
![image](https://user-images.githubusercontent.com/34819172/90090380-b5d67980-dcd8-11ea-8b65-01780c44eadd.png)

**Comment by Anuken** [comment]
Use a switch. After reading the value, you can disable it.
