### ISSUE TITLE
improve rts AI

### ISSUE THREAD

**Issue by dinklee** [Anuken/Mindustry-Suggestions#3982]
### Describe the content or mechanics you are proposing.

the rts AI that the editor provides you is stupid and in the majority of times i tested it it did nothing just staying there

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

making a better AI will let us to do maps with AI that will build contstanly things to defend/attack and will make the game fell more alive

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/3617#issuecomment-1146013266

> Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

**Comment by dinklee** [comment]
> [#3617 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/3617#issuecomment-1146013266)
> 
> > Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

well sorry
