### ISSUE TITLE
Synchronization of processors and data exchange from processors

### ISSUE THREAD

**Issue by RapsorG** [Anuken/Mindustry-Suggestions#3984]
### Describe the content or mechanics you are proposing.

Add a command to combine 2 processors and transfer data to a specific command. **EXAMPLE**: If you need to make a connection with processors (Computer) then with these commands it will be possible to do it much easier. Make a main processor that will process commands and control others, Make a video processor that will receive data from the main processor and display it on the screen and make RAM with a storage medium.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make it easier to work with communication with processors and their synchronization

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Memory cell: Am I a joke to you?

**Comment by RapsorG** [comment]
A memory cell cannot transmit data to a specific command. If you use it, the speed will decrease

**Comment by Mythril382** [comment]
You can make a processor that continues if exact number from cell is 1 and then set it to 0 after it is done.
