### ISSUE TITLE
Mixed tech on sandbox mode

### ISSUE THREAD

**Issue by Plastel** [Anuken/Mindustry-Suggestions#3986]
### Describe the content or mechanics you are proposing.

Make mixed tech available on sandbox 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Many people complain about that mixed tech is unbalanced, then, we should make it sandbox exclusive, because, if there's a totally unbalanced item source, very broken power source, and another very broken heat source, why there shouldn't be mixed tech on sandbox when other three things are already unbalanced?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LampbuIb** [comment]
This. I don't get why people are so against single player mixtech anyway; if you don't want to use it, just **don't**, its not like it's on campaign anymore, and you aren't going to die if there's unbalanced erekir items in sandbox... just put on a disclaimer.

**Comment by Plastel** [comment]
discord mf's on their way to to criticize mixed tech on the nanosecond a image with mixed tech appears

**Comment by octopuscaat** [comment]
this aleady exists
