### ISSUE TITLE
Multiplayer on Company And Nicknames

### ISSUE THREAD

**Issue by Zahar1loshara** [Anuken/Mindustry-Suggestions#3987]
### Describe the content or mechanics you are proposing.

You click on "Campaign", and you will see a selection window, alone or together with someone, it will be stored separately, in order for the modifications to work, it is necessary that all players who will play have them, Let the limit be 12 players, by the way, the campaign will be stored approximately like in Java Minecraft, And oh my god, you just add the "Your nickname" parameter in the settings, otherwise I have a nickname meow, Excellent!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I want to try to play the campaign with my brother, but there is no such function at all

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
It seems the translation tool you are using is bad at conveying what you actually want tell us.

**Comment by Zahar1loshara** [comment]
Google

**Comment by Zahar1loshara** [comment]
Oh, I found where to change the nickname, but still something stupid place, I would like it to be in the settings in the category "The game"
