### ISSUE TITLE
Eclipse's scorch

### ISSUE THREAD

**Issue by TacticalAlpha** [Anuken/Mindustry-Suggestions#399]
**Describe what you would like changed, and why.**
Eclipse's scorch should automatically shoot when near an enemy unit or structure instead of shooting with the lasers.

**Describe the changes you want to propose. Include possible alternatives.**
n/a

**Comment by Anuken** [comment]
- The eclipse, as an AI, already shoots with scorches automatically when a unit comes close.
- If you mean that lasers should stop shooting at units that are nearby: I don't see any reason for the targeting to work this way.
- If you mean that the scorches should shoot automatically when the *player* is controlling it: That doesn't seem necessary.
