### ISSUE TITLE
Multiple save files for Campaign & slightly reworked save system for Campaign

### ISSUE THREAD

**Issue by A765-ALEX** [Anuken/Mindustry-Suggestions#3992]
#### **Note: If this seems ambiguous/you think it's already implemented, check the "here's what I meant" comment I posted.**
We use an archive (e.g. *.zip, *.tar) or a folder for every save of the entire Campaign (every sector [every .msav file]), and allow players switching from one to another save file to play on, allow copying and deleting them, etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this will improve the game because, for instance, it will allow players to attempt different strategies on a sector without having to worry too much about losing the sector by creating a copy of the save file that's being played on.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mnemotechnician** [comment]
> [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

You are not. Everything you've suggested already exists.

**Comment by A765-ALEX** [comment]
> We use a archive (e.g. *.zip, *.tar) or a folder for every save of the entire Campaign
What I meant was **every** sector of the Campaign (every *.msav file) when I said "the entire Campaign", not just one of them. sorry for not clarifying it

**Comment by Mnemotechnician** [comment]
Literally just open the `saves` subdirectory of mindustry's data directory, h
![Screenshot_20221001_204629](https://user-images.githubusercontent.com/69920617/193421880-568e53dc-b02e-48b0-bcce-c52f457c5334.png)
Is it not clear that these are sector saves? (on the screenshot there are 4, normally there's more)

**Comment by Moth-Tolias** [comment]
it would be nice to be able to do this ingame rather than messing about with the files manually.

**Comment by A765-ALEX** [comment]
> Literally just open the `saves` subdirectory of mindustry's data directory, h ![Screenshot_20221001_204629](https://user-images.githubusercontent.com/69920617/193421880-568e53dc-b02e-48b0-bcce-c52f457c5334.png) Is it not clear that these are sector saves? (there is just 4 on the screenshot, normally there's more)

here's what I meant:
![click this image](https://user-images.githubusercontent.com/67318684/197381218-6f28dd34-6e3a-48d1-8917-bf65e70fba49.png)
