### ISSUE TITLE
Phase Fabric RTG buff

### ISSUE THREAD

**Issue by LampbuIb** [Anuken/Mindustry-Suggestions#3993]
### Describe what you would like changed, and why.

Right now, using phase fabric is utterly useless in RTGs, as you have to process it first only to achieve 60% output compared to thorium. In other words, phase is not worth using.

### Describe the changes you want to propose. Include possible alternatives.

Increase the usage time for phase in RTG's, or decrease the use time of thorium if that makes RTGs too powerful. This change would see more use of phase in Serpulo.

**Comment by Mnemotechnician** [comment]
The only reason you can fuel RTG generators with phrase fabric is because it's radioactive. It's not meant to be efficient or worth using.
