### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Demert362727** [Anuken/Mindustry-Suggestions#3996]
### Describe the content or mechanics you are proposing.

hello, where did the nuclear production complex go? in V6 it is on the same save as in V7 but in V7 it is not open. what do i need to do to open it? 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

hello, where did the nuclear production complex go? in V6 it is on the same save as in V7 but in V7 it is not open. what do i need to do to open it? 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
prob should look it up, not ask here. this is feedback/balenceing and feature request
