### ISSUE TITLE
Better banning

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#4]
**Describe what you would like changed, and why.**
The ban system for local players; there are many plugins to make vans more severe, but a lot of players still play campaigns and local servers which have none of those.

**Describe the changes you want to propose. Include possible alternatives.**
- Make banning for local servers for the duration of the session (and have a list of banned players if they want to unban)
>*due to the lack of local servers at anytime, it isn't uncommon to see a griefer that was banned, returns to the same server*
- Have a local ban list (users that are banned could be saved to a file and automatically be banned from any future sessions that the player hosts)
>*this could help deal with repeat offenders, as local servers are less abundant, and finding servers with the same host is quite easy*

**Comment by KK6DOC** [comment]
To add on to your suggestion also you should be able to remove certain players from the list easily... (Scidustry accidentally votekicked Ado1928 from the server and was *banned* for a hour)

**Comment by Katsute** [comment]
Closed due to inactivity
