### ISSUE TITLE
A type of conveyor belt that would permit outputing stuff from the core upon game start.

### ISSUE THREAD

**Issue by clepeterd** [Anuken/Mindustry-Suggestions#40]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by KK6DOC** [comment]
There is nothing here 
You probably close it @clepeterd

**Comment by Katsute** [comment]
An unloader?

**Comment by KK6DOC** [comment]
Ye I think that's already in the game
*Unloader sneks* 🐍

**Comment by clepeterd** [comment]
Can't seem to find it

**Comment by Katsute** [comment]
https://mindustrygame.github.io/wiki/blocks/effect/unloader/

**Comment by clepeterd** [comment]
Thanks ! Exactly what I needed. Sorry for the interruption.
