### ISSUE TITLE
New unit: Volt

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#400]
**Describe the content or mechanics you are proposing.**
Volt would be a an eruptor-sized unit which has 2 lasers which when fired suck out the power from units or buildings. Volt would fire 2 lasers which would suck out 200 power/second, the amount Volt sucks out is dependant on how long he has, 100 power within half a second, 200 power within a second, 500 power in 2 seconds, 650 power in 3 seconds, 750 power in 4 seconds and 900 power in 5 seconds, after this, Volt would continuously suck the power out of the unit or building, meaning that if you were generating +1000 power, volt would make it +100 power after 5 seconds. When volt is killed, he makes an arc blast which damages every unit, building or turret in a 10 block radius with arcs of lightning (pretty much a big battery exploding). If volt isnt killed and he is called back to retreat he will bring all the power he gained from his enemies back to base where he will deposit it into your power system (this is rare as he probably wont survive). Surge walls are volts kryptonite, as when he tries and steal the power from them he gets stunned for a second and takes some minor damages. Another counter, is plastanium walls, which dont let Volt fire his lasers through. Volt can be made in a factory with 10 surge alloy, 50 silicon, 25 titanium and 30 lead, the factory is 4x4 and can only make 2 volts per factory. Volt can only hit ground units 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

•we need more unique units 

•volt has a unique building recipe

•volt has unique counters

•volt has a death effect which acts as a counter, the only other unit with this is crawler

•volt has a unique ability of stealing power, which will be usefull against things like meltdowns, lancers and arcs, along with menders and mend projecters.

•volt adds more use too plastanium walls + surge walls

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rabit232** [comment]
impressive  that would  help in gameplay  good explanation

**Comment by 50275** [comment]
So if I made 3-5 lancers, would the volt win?
