### ISSUE TITLE
mindustry compatibility with linux ARM64 

### ISSUE THREAD

**Issue by tigercoding56** [Anuken/Mindustry-Suggestions#4000]
### Describe the content or mechanics you are proposing.

simply adding ARM64 linux (not macOS ) compatiblity to mindustry  

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

ARM64 compatiblity would allow  people running linux on a variety of ARM64 devices such as laptops (like pinebook pro , chromebooks  )  and  desktops (apple silicon running linux  ) and also  single board computers ( Strawberry Pi's  , rock pi , and others )  to run mindustry ,

  to prevent it from running on a raspberry pi i suggest to add code that crashes the game when a raspberry pi is detected , 
since people seem to not like the inclusion of raspberry pis (even though the raspi 4 would be more than powerfull enough to run this at 20 + fps )  in such issues 

there are not many  opensource  tower defense games available for ARM64 linux  and this is one of the most polished opensource tower defense games i have seen 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by tigercoding56** [comment]
in order to prevent this issue from becomming stale i need to comment here

**Comment by A765-ALEX** [comment]
i think it's possible with arm64 java
