### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Thegrimfew2** [Anuken/Mindustry-Suggestions#4002]
### Describe the content or mechanics you are proposing.

I would like to be able to link my mobile campaign and my desktop campaign.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think enabling everyone to play where ever will increase player base and enjoyment in the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
You did not read the readme.

**Comment by Thegrimfew2** [comment]
I read the one on got hub is that not correct?

**Comment by Thegrimfew2** [comment]
I am suggesting enabling steam link for mobile like what is already
available through desktop.

**Comment by IxGamerXL** [comment]
Linking Mobile & Desktop campaigns is basically asking for Built-in cloud support, which has been blacklisted from consideration via the [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md). Any form of online data saving that Anuken would need an external server or hostable storage medium for is not going to be implemented.

**Comment by Thegrimfew2** [comment]
Ah okay. My apologies. I figured it would be easier. Again my apologies
