### ISSUE TITLE
I NEED LOGIC

### ISSUE THREAD

**Issue by Dustbin-lst** [Anuken/Mindustry-Suggestions#4003]
### Describe the content or mechanics you are proposing.

**I NEED LOGIC FOR EREKIR**
and mixed tech is _**disabled**_ now
so i want to play with logic in erekir

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will make Erekir great again

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
no

**Comment by IxGamerXL** [comment]
As Anuken has said before, he won't be adding Logic for the planet, likely because Logic breaks the need to properly manage your assembly. Maybe if he scuffed the logic by disabling certain instruction types (which might be the most passive way to fix it), then it might be possible to add it back in.

**Comment by Urkikk** [comment]
Players shouldn't need to learn how to code to be able to play the game.
the fact that logic in Serpulo gets spared based on feedback rather than get removed too is already a blessing.

**Comment by Mnemotechnician** [comment]
> and mixed tech is disabled now

Use a console, smh.
