### ISSUE TITLE
Swarmer and Cyclone

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#4004]
### Describe what you would like changed, and why.

Make Swarmer air only and Cyclone ground only.

Swarmer and Cyclone are similar in dps, ammo requirements, range, and other such details. There should be something distinguishing the two from each other. Also, the end game lacks the niche of air only and ground only turrets, which such a change would fill. 

### Describe the changes you want to propose. Include possible alternatives.

Alternatives:
- Make Cyclone AA and swarmer ground only
- Fill the missing niche with other turrets
- Don't

**Comment by littlekatter330** [comment]
anuke is not going to do this @RealYeet
