### ISSUE TITLE
being to play mindustry on console

### ISSUE THREAD

**Issue by littlekatter330** [Anuken/Mindustry-Suggestions#4006]
### Describe the content or mechanics you are proposing.

full on console support with mods but they add on instantly to your save

please add my other thing to v8 please it would be fun #3979
@Anuken please do it i would be happy if you did that

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would bring in more players

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X] I **haven't** checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

[If you actually checked, you would have seen this](https://trello.com/c/QwPVvcQ6/)
