### ISSUE TITLE
Make option that set planet by team

### ISSUE THREAD

**Issue by Redmountain0** [Anuken/Mindustry-Suggestions#4008]
### Describe the content or mechanics you are proposing.

Change the existing planet setting to only set the environment and make a separate planetary setting that determines the technology for each team.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

With this option, we can make maps like serpulo vs erekir pvp, defending erekir units with serpulo tech, or attacking erekir enemy base with serpulo tech.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
maybe it’s possible to set revealedBlocks as a team specific rule, not sure though

also limit the resource types available to the teams

making a map like that is probably possible, but you’d need to do some trickery that can’t be done with just the editor
