### ISSUE TITLE
special boss at the end of each planet + final boss at very end of campaign

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#401]
**Describe the content or mechanics you are proposing.**

(this is NOT story based.)
in 6.0, planets can be conquered. this means there is an end to the campaign.
 if my theories are correct about how once youve fully conquered a planet youll go to the next one, id think it would be appropriate for a special boss at the end of each planet. 
basically, all it is is a really strong unit that has different phases (Ex: a unit shoots spectre like shots, then when you destroy the cannons new weapons that act like swarmers pop out). after all phases are destroyed the boss has a death animation (Ex: flying unit spins out of control, falls to the ground and explodes)
some music tracks could also be made to play during the boss fights.
additionally with this, the last "planet" shouldnt even be a planet; it should be a station of some sort thats just like a planet, only its ALL attack mode maps. at the very end of this final station, you fight the final boss.
(after being called retarded demonstrating my ideas to the discord i have refined by ideas w this a bit)
my thought is that the last boss level will start with you in a very large area. your core is 4x4, so you cant launch with a ton of stuff, and you must build up defenses for 10 minutes. after the 10 minutes are up the final boss unit, with the most phases and by far strongest attacks out of the other bosses, spawns in. if you take down the unit, somehow, youll be taken to the credits screen and all that stuff.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

i think it'll improve the game because, rather than just finishing the planets youll have a much more exciting adventure doing so. i really believe the last challenge in mindustry should be facing a super strong unit, not just a shielded reaper storm or a really, really big base. having an actual, climactic ending to the game rather than a reaper storm hex tile would be well worth the work. maybe you could implement some story too but no one seems to be on board with that.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RoyalFunnyDude** [comment]
Huh...with 10 minutes you can just spam mass daggers/wraith/revs with your starting resources...and you can get more spam just by getting a little production/power. How much hp would the boss have?

**Comment by sup3r87** [comment]
> Huh...with 10 minutes you can just spam mass daggers/wraith/revs with your starting resources...and you can get more spam just by getting a little production/power. How much hp would the boss have?

my idea is for bosses to be a little stronger than the strongest units on whatever planet, but the main thing being multiple phases and lots of help. a proper boss fight goes on for a decent amount of time

**Comment by RoyalFunnyDude** [comment]
i mean, if you have 30 fortress and a decent healing turrets then there's not a lot that can stand up to them

**Comment by RoyalFunnyDude** [comment]
even a reaper can't kill 40 daggers

**Comment by SupremeTurtle** [comment]
I like the idea of even stronger bosses, since it's mostly about quantity in v5.

**Comment by sup3r87** [comment]
> i mean, if you have 30 fortress and a decent healing turrets then there's not a lot that can stand up to them
> even a reaper can't kill 40 daggers
mhm, thats why i suggested multiple phases, so you need a well rounded defense system to handle a boss.

**Comment by BlueWolf3682** [comment]
i agree fully with this idea, ive always thought there should be a last stand attack map at the end... possibly the final boss being the crux core base and the mothership that deposits crux units and cores... win all or lose all. that would be damn entertaining

**Comment by gen-NA-owl** [comment]
> Huh...with 10 minutes you can just spam mass daggers/wraith/revs with your starting resources...and you can get more spam just by getting a little production/power. How much hp would the boss have?

I think there is a unit limit corresponding to the level/amount of your core(s), which means you can't just spam daggers, and trying to build reapers would be way to expensive.

**Comment by stuffyAI** [comment]
> level/amount of your core(s),

https://trello.com/c/qc397VGk/706-finalize-unit-cap
tough the main problem now is that even tier 2 units take some advanced resource masses and time, and with healing block nerfs spam is very susceptible to AOE damage, which i assume the bosses would have.

**Comment by itcannotbe** [comment]
Blocks has something called damage progression which essentially makes aoe damage work on blocks differently.
