### ISSUE TITLE
Payload Ammo

### ISSUE THREAD

**Issue by Daconus** [Anuken/Mindustry-Suggestions#4010]
### Describe the content or mechanics you are proposing.

I would love to see more use for payload conveyors, such as turrets that use payload ammo. Or some factory that requires a payload to function. It would be fun to see how that would work. The mod Progression Ministry has some of these features and I would love to see it in the vanilla game.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add a new tier of weapons, or possibly new resources. It could also replace ammo in turrets like the Scathe, you would have to produce the missile in a separate factory, then ship it to the Scathe, it just feels off the way it is now.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
Don’t some factories use payloads already?

**Comment by Daconus** [comment]
> Don’t some factories use payloads already?

Yes, but I would love to see more content added around that, only units use it
