### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by egamer100** [Anuken/Mindustry-Suggestions#4012]
### Describe the content or mechanics you are proposing.

2 things
1. logic blocks for ekier
2. teams for teams(will explain)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. it will add logic to eikir
2. what i mean by teams for teams is that two diffrent teams will work together (e.g. crux and malis v.s. sharded)
this would add possibilitys to both the campaign and maps
what would happen between teams
1. units cant destroy other teams units if there both on the same team
2. opation to build in core range of other teams
3. units wont attack other teams units (same with turrets 
hope you like both ideaas

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X]  I haven't read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

### A few things you shouldn't suggest

####### These have been proposed many times already, and I won't be adding them.

- Allied teams

**Comment by egamer100** [comment]
but why

**Comment by egamer100** [comment]
why will anuke not add it

**Comment by Mythril382** [comment]
erekir was made to not have logic, anuke already explained this

**Comment by egamer100** [comment]
> erekir was made to not have logic, anuke already explained this

i feel dumb
