### ISSUE TITLE
crafter/power generator warmup is a lil off

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#4014]
### Describe what you would like changed, and why.

not sure if this is a bug or intended, so im putting it here instead of bug reports
but even with a slow warmup, power generators and crafters (other than impact) simply output their full instantly after receiving sufficient input to run, instead of ramping up output with their warmup

### Describe the changes you want to propose. Include possible alternatives.

make visual warmup coincide with actual output ~~and subsequently remove the ImpactReactor class as its entire job is doing precisely this~~

**Comment by itcannotbe** [comment]
Yeah, this is working as intended.

Warmup is just visuals except for impact.

**Comment by BlueWolf3682** [comment]
thats the entire point of a suggestion you dingus
