### ISSUE TITLE
Logic improvement

### ISSUE THREAD

**Issue by Timarrr** [Anuken/Mindustry-Suggestions#402]
String, comments and for/while support in logic blocks

It will allow users to make much more compact and neat "scripts" without just repeating one command

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Strings and comments are already part of the language. Instead of loops, use jumps.
