### ISSUE TITLE
Increase output from impulse pump

### ISSUE THREAD

**Issue by Vojtak42** [Anuken/Mindustry-Suggestions#4021]
### Describe what you would like changed, and why.

Hello, please increase output from impulse pump. It has verry little output increase compared to Rotary pump per 1x1 block. Impulse pump has output per 1x1 block 13,1 and rotary has 12. And impulse pump os very inefficient - impulse p. has output per 1 power unit 1,52 and rotary p. has 2,66.
Thank you for fix.

### Describe the changes you want to propose. Include possible alternatives.

↑

**Comment by itcannotbe** [comment]
But you can reach more tiles with the impulse than with a rotary, also

STOP PLAYING MAPS THAT ONLY CONTAINS SHALLOW LIQUID TILES FOR IT'S WATER FEATURES.

The stats makes better sense when deep water tiles are used.

**Comment by itcannotbe** [comment]
related issue: #2246

**Comment by Vojtak42** [comment]
Ok but when I have enough water tiles, it it's nosense to build it because it has much bigger (1,75x per liquid unit) power consumption .
