### ISSUE TITLE
1/150 chance for special unit in title screen

### ISSUE THREAD

**Issue by LampbuIb** [Anuken/Mindustry-Suggestions#4022]
### Describe the content or mechanics you are proposing.

Have a 1/___ (150?) chance for a higher tier unit to spawn in the title screen; usually, it's just flares and monos, why not spice it up a little every now and then?

Another idea: make it so sometimes the title screen shows water instead of randomly generated terrain, so naval units can be showcased too!
wait, what if anuke or a chan spawns..?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**funny moment**

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LampbuIb** [comment]
ooh i forgor, what about erekir (and tantros in the future) units?

**Comment by Leo-MathGuy** [comment]
Like the ksp mun sandcastle?

**Comment by LampbuIb** [comment]
yeah, I guess you could say that.
