### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Alol555** [Anuken/Mindustry-Suggestions#4023]
### Describe the content or mechanics you are proposing.

Add the arabic language Please 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There is 25 country speaking Arabic so.. The number of users will increase

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> Most of the developers, or all of them even, don’t speak Arabic. If you wish for Arabic, please translate it yourself. It’s difficult for us to learn a new language.

The issue is more something to have to do with arabic language being a RTL language.

See #1981

**Comment by Leo-MathGuy** [comment]
Please rename the title to resemble the request. e.g. "Add arabic language" instead of just "Please help"
