### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Alol555** [Anuken/Mindustry-Suggestions#4024]
### Describe what you would like changed, and why.

The new update bulid 139 is have to late and i cant dawnlod't because it was'nt dawnloded on play google

### Describe the changes you want to propose. Include possible alternatives.

Fix it plz

**Comment by end-me-please** [comment]
i honestly can’t tell if this is a joke or not

**Comment by Mythril382** [comment]
me neither, maybe its both

**Comment by Leo-MathGuy** [comment]
tfw when you see a troll post and the user has joined github this month
