### ISSUE TITLE
Add intersector unit based transport

### ISSUE THREAD

**Issue by nick12344567** [Anuken/Mindustry-Suggestions#4025]
### Describe the content or mechanics you are proposing.

You may add some kind of water or air transportation system so you can transport units or items to other sectors.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will surely make capturing sectors very easy but it can be balanced so you can only transport to captured sectors.

Also this does not include carrying aircraft with naval units it can be used for ground units only.Air units will need to fly on their own.

It may be fun to transport the latest tier materials to ground zero and make a death fortress there for no real reason.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by sheptalo** [comment]
on trello you can find this feature

**Comment by nick12344567** [comment]
Well i meant adding a river system and another transport tier for the water.
