### ISSUE TITLE
Adding a "No Fly" zone for either the in-game editor and/or campaign

### ISSUE THREAD

**Issue by IGitAustin** [Anuken/Mindustry-Suggestions#4027]
### Describe the content or mechanics you are proposing.

A zone dedicated for flying units to be banned from ever crossing i.e: too deep in solid terrain, blocked from certain paths, etc

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow mapmakers (specifically pvp maps) to allow some restrictions from air units to just fly over defenses and straight up destroying the enemies' core. It will also incentives players to break through defenses rather than avoiding it all entirely via being  far enough. It can even help in campaign maps where you can just place no fly zones on certain spaces to avoid cheesing as mentioned before.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaysonnn80** [comment]
Would be cool if it gave a warning like when you fly into an enemy spawn zone in survival. It'd also be cool if it deterred your aircraft (like when flying into an enemy spawn zone) rather than acting like a wall.
