### ISSUE TITLE
Logic "Destroy" Unit Control

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry-Suggestions#4028]
### Describe the content or mechanics you are proposing.

An option in uControl to destroy a block at the given coordinates, if the unit can build.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, you can't deconstruct blocks with logic. I'm requesting this solely because I want to automate testing turrets in the mod Random Mindustry. However, it would be a cool feature to have.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
probably intentionally doesnt exist to prevent griefing, but given that ucontrol build is disabled on almost all servers anyways that doesnt really matter
