### ISSUE TITLE
an upgrade tool like the deconstructor and a rebuild tool

### ISSUE THREAD

**Issue by fetusgriffin** [Anuken/Mindustry-Suggestions#4029]
### Describe the content or mechanics you are proposing.

the upgrade tool will work by upgrading things like conveyors,walls and drills to better versions of themselves example: normal conveyors to titanium ones or walls to higher health versions of themselves and maybe it could turn other things to bigger versions of themselves if theres space like menders to mend projectors or power nodes to large ones.it will basically be like if you put a airblast drill over a laser drill but in mass quantities.

the rebuild tool will pretty much just place plans to put back all the "ghosts" of destroyed blocks in an area 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will make the transition to tit a lot easier since i find it annoying to replace all my belts or when i get graph and have to replace my drills with the better ones and just overall both tools would be nice quality of life changes

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Leo-MathGuy** [comment]
y e s  p l e a s e

tfw your entire factory clogs because you forgot to upgrade one little conveyor belt somewhere in your spaghetti
