### ISSUE TITLE
cross-CPU communication

### ISSUE THREAD

**Issue by imreallybadatnames** [Anuken/Mindustry-Suggestions#403]
**Describe the content or mechanics you are proposing.**

2 instructions: send and recieve.
The send instruction will require 2 parameters: message to send(message can be read from a variable and then sended) and reciever(building that is either a logic block or a microprocessor).
The recieve instruction will require 2 parameters too: a variable to store the message in and the sender(building that is either a logic block or a microprocessor) for filtering incoming messages by a sender.
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will not be required to use a "middle man"(usually a memory cell) to transmit messages between processors.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Use shared memory. This doesn't accomplish anything new and only adds another way to do something that was already possible.
