### ISSUE TITLE
ground zero updated tutorial ideas

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#4030]
### Describe what you would like changed, and why.

A few days ago, the [ground zero tutorial was changed](https://github.com/Anuken/Mindustry/commit/8104173b3120ace83bfff3ff0c18b9175636f13e).

There are just a few things I'd suggest changing that I noticed while testing translations, see below. 

### Describe the changes you want to propose. Include possible alternatives.

Some text can be a little difficult to read once it gets darker - maybe some sort of minimum brightness for text / different darkness in ground zero:
![java_gUqMv053zF](https://user-images.githubusercontent.com/57631841/195798663-a0697dba-f3d8-4083-890e-d15405071ba0.png)
(screenshot is in German, but still applies)

The turret hint also mentions that they need ammo, but as soon as you place them it moves on to the wall hint. If you then place the walls, it immediately spawns the wave - maybe it would be possible to check for ammo in the turrets before displaying the wall hint?
I know the first wave really isn't challenging, but it might still be more enjoyable that way.

I'm aware that there's a chance that this isn't finished yet, but I thought it was better to report anyway.

**Comment by Anuken** [comment]
The turret ammo issue was a distinct problem I noticed while testing, but since turret placement position is so flexible and vague, there was no simple way to handle it - what I essentially needed was a way to see if a *specific* type of turret was newly placed and received ammo of any kind anywhere on the map.
