### ISSUE TITLE
Itch.io Buyable Ver (and maybe an GoG version?)

### ISSUE THREAD

**Issue by VexfulNiko** [Anuken/Mindustry-Suggestions#4031]
### Describe the content or mechanics you are proposing.

Itch.io but with an option to buy it (much like in steam) this can include seamless multiplayer and automatic updates with the itch.io launcher.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Add another way to support the developers and another way for people to buy the game, especially for people who want to avoid DRM and support platforms that offer DRM-free games (like itch or GoG)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
The problem is that the reason Steam is used is for their ability to offer seamless dedicated servers. I don’t think Itch has the same capabilities.

**Comment by VexfulNiko** [comment]
@IVV-NCX Perhaps GoG then? Honestly, even then just a way to support the dev and own the game in a DRM-Free platform.

**Comment by itcannotbe** [comment]
Itch.io donation but downloading it throught the itch.io website not the launcher?

**Comment by IVV-NCX** [comment]
@VexfulNiko I believe DRM is optional for steam games. I don’t think Mindustry has DRM, especially when it’s free and open source.

**Comment by VexfulNiko** [comment]
@IVV-NCX I mean a way to support in a full DRM free platform that doesn't push DRM like steam does.

**Comment by IVV-NCX** [comment]
@VexfulNiko Steam doesn't push DRM. It is an optional feature which developers may enable if desired, as the developer guide says.

**Comment by end-me-please** [comment]
you can buy the game on itch.io already..just name your own price

**Comment by VexfulNiko** [comment]
@IVV-NCX Steam opens up everytime you try to launch a game with it even with DRM off I'm pretty sure

**Comment by IVV-NCX** [comment]
@VexfulNiko That’s not DRM. That’s because steam is a game launcher, that needs to connect to their servers. It uses steam as a middleman to get information and the like.

**Comment by VexfulNiko** [comment]
@IVV-NCX I see, still pretty annoying though imo.
