### ISSUE TITLE
A new turret, 2 new ores and titanium on erekir.

### ISSUE THREAD

**Issue by thetrulystupid** [Anuken/Mindustry-Suggestions#4033]
### Describe the content or mechanics you are proposing.

There should be a Trio turret, practically the salvo, but cheaper and for erekir. The two new ore being Tuplite, a pink ore normally found near beryllium, The other ore being ammo for the Trio, Onyx, A majorly dark metal, If Onyx is shot at an enemy: Apply the Tarred debuff. If Onyx is shot at a friendly unit: Apply the Overdrive buff. Trio would require 50 titanium and 30 tuplite (placing.) and 200 tuplite and 450 titanium (research) . Trio is significantly weaker than breach, but makes up for it in low build price as said earlier.
Rough image of the Trio. (I suck at drawing, i know.) 
![image](https://user-images.githubusercontent.com/115823161/195914995-0af1c791-3dc1-4cab-bdf2-d8154e7e500c.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'll ease up erekir a bit as you wouldnt need 550 matierals for one single tower, and perhaps delay enemies for the player to stay alive longer and make waves of enemies easier to deal with.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaysonnn80** [comment]
Eh. I don't think so. An entire resource just for ammo for one turret? Ally buffing turret? Just ain't it.

**Comment by thetrulystupid** [comment]
Jayson, i might suggest a few new ores in the future or something, so, just like erekir itself, the trio and ammo selection is w.i.p.

**Comment by thetrulystupid** [comment]
Okay, first of all, Mythril, i didnt know that, and i just feel like tungstens a bit too.. scarce? especially on levels that you badly need it.
