### ISSUE TITLE
(Suggestion) Glass walls

### ISSUE THREAD

**Issue by throwitthefuckaway** [Anuken/Mindustry-Suggestions#4034]
### Describe the content or mechanics you are proposing.

The enemy can't see it, but allies can

If the enemy shoots it, damage is applied, but they don't know that they shot (if you can't see it, does it really exist?)

Could be cool aswell if the damage gave the location of the block away

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

·This could make certain parts of the game more challenging, such as playing online
·With Glass walls you can make a glass dome around your friends units so they can't be commanded to attack your stuff (better if only ground unit have these limitations)
·"Look! that dummy forgot a big chunk of their base without any sort of walls/protection" "Why can't my units go past X point >:C"

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaysonnn80** [comment]
eh

**Comment by Leo-MathGuy** [comment]
Cool idea a bit too op maybe they are very weak like 10hp or something
