### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by Erekir-1234** [Anuken/Mindustry-Suggestions#4035]
### Describe the content or mechanics you are proposing.

Make a way that you can get crash logs in game 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make it easier to report bugs and crash reports so developer can deal with bugs more easier 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
that already exists hh

**Comment by itcannotbe** [comment]
How would be able to access the crash logs in-game when the game crashes as it loads? It's a unnecessary "FeAtUrE" if it was.

Hey look mom! My software crashes too often that I need a way to let users have crash logs through the software's UI
Said No Programmer Ever.

**Comment by itcannotbe** [comment]
When you see.....
https://github.com/Anuken/Mindustry/issues/7720

**Comment by itcannotbe** [comment]
The bug reporting template be like:

### (Crash) logs: Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.

**Comment by BlueWolf3682** [comment]
me when theres a `crashes` folder in mindustry data
