### ISSUE TITLE
walls to cliffs is absolutely horrible to use

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#4036]
### Describe what you would like changed, and why.

walls to cliffs converts EVERY F\*CKING WALL on the map to a cliff and sometimes generates terribly, while also not allowing for steep slopes made of multiple cliff layers next to each other
would heavily prefer drawing them over this mess that just f*cked an entire map in the works

### Describe the changes you want to propose. Include possible alternatives.

change the system to using a brush, and on selecting said brush it gives a left side menu for which orientation of cliff to draw
or at least allow selecting a certain type of wall to consume, and not factor already placed cliffs into its edge calculation

**Comment by Breadyboi69** [comment]
**_yes_**
