### ISSUE TITLE
Cross Progression

### ISSUE THREAD

**Issue by BlueDaisy84** [Anuken/Mindustry-Suggestions#4038]
### Describe the content or mechanics you are proposing.

I suggest a cross progression system in the game, so you can play from platform to platform (iOS to Steam edition for example)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe it will improve the game as it allows for accessibility without compromise, like being able to play some rounds on your phone while on the go, and then pulling up that save on a computer and continuing to automate your factory.
I feel like I wouldn't be the only person to benefit from this, people have time to play quick games during lunch breaks or such, people would enjoy being able to play the same save at home or on break times.
I can understand why you wouldn't implement this, or at least not yet, the only way I can see this working is having some account thing, which isn't implemented either.

Thank you for reading my request
- Aiden

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Built-in cloud sync

**Comment by BlueDaisy84** [comment]
I’m incredibly sorry, I missed that when I read through the “things you shouldn’t suggest” page
