### ISSUE TITLE
Disable Autoupdates checkbox

### ISSUE THREAD

**Issue by aegires** [Anuken/Mindustry-Suggestions#4040]
### Describe what you would like changed, and why.

I'd like to have a checkbox "Disable Autoupdates"

### Describe the changes you want to propose. Include possible alternatives.

"Disable Autoupdates" checkbox is important because once the service you are using goes offline, things are much easier to work with. The default plugin for the script is called autoupdate (see the article "Autoupdates in Vim's GUI"). To use this plugin, follow the steps in the plugin's install guide. This plugin creates special files when the service is offline (in this case, this file is autoupdate.svg), which are then downloaded to a shared file on your desktop.

There is more information about autoupdates in the manual for those who are interested.

Autoplay Autoplay makes it possible to take advantage of the current document at the very least, automatically. It also allows to create custom autopean sections for your application.

Autoplay automatically adds support for:

the file names under the "new title" textbox that is shown when you close and reopen the web browser

the URL under the search box (from a new document in other browsers)

other contextual contextualizations (like links, status, etc.)

the autoload option (to choose between the autoloading the autoload files you want.) Default: --only works only on specific versions, or in the first few releases

**Comment by itcannotbe** [comment]
I feel like this was translated poorly into english.

**Comment by aegires** [comment]
> 

No, i don't know what i can write. I use gpt-3 ;)
