### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ISDUJDDNEN** [Anuken/Mindustry-Suggestions#4043]
### Describe what you would like changed, and why.

Я нашел баг, который мне не позволяет высадиться на сектор Ravine иза того что не хватает 400 вольфрама, а на планете из которой я стартуют (Lake) нет вольфрама. И за этого весь игровой процесс встал 

### Describe the changes you want to propose. Include possible alternatives.

.

**Comment by kapzduke** [comment]
okay
