### ISSUE TITLE
Adding Steam to the mobile version of the game

### ISSUE THREAD

**Issue by VANEA2005** [Anuken/Mindustry-Suggestions#4045]
### Describe the content or mechanics you are proposing.

I wanted to see the Steam system in the mobile version of the game and the ability to play with friends on Steam, and the ability to save saves there 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will be easier to play with friends and there will be less action for friends who live in other places 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ain't steam PC only?

**Comment by VANEA2005** [comment]
maybe for PC, but there is a mobile version of Steam

**Comment by VANEA2005** [comment]
maybe for PC, but there is a mobile version of Steam

**Comment by Phinner** [comment]
> maybe for PC, but there is a mobile version of Steam
The steam mobile app is just to access the steam platform (game store pages, friends, chat, 2FA, ...), not playing for playing games.

**Comment by A765-ALEX** [comment]
steam (legally) doesn't allow non-steam copies of games to play using the steam system, so I don't think that's possible.
