### ISSUE TITLE
Password to join servers

### ISSUE THREAD

**Issue by hublylol** [Anuken/Mindustry-Suggestions#4046]
### Describe what you would like changed, and why.

Have an option where the host can put a password on a public server so not every random person is allowed to join.

### Describe the changes you want to propose. Include possible alternatives.

Implement a system when hosting a server to have a password to join a server

**Comment by KayyAyeAre** [comment]
whitelist

**Comment by hublylol** [comment]
for some reason i cant white list when i host campaign server. it says im admin but i dont even have to power to kick people
