### ISSUE TITLE
Very minor buff to titanium conveyors.

### ISSUE THREAD

**Issue by TrueBlueFlare** [Anuken/Mindustry-Suggestions#4047]
### Describe what you would like changed, and why.

The item transport rate of 11 per second provided by titanium conveyors is beyond annoying to work with when trying to make a design that uses the exact amount of items can can be inputted per second. It is such a bafflingly awkward number to work with and has caused me a simply unreasonable amount of rage and headaches.

### Describe the changes you want to propose. Include possible alternatives.

Increase the throughput of titanium conveyors from 11 to 12. Literally just increasing it by one would save me so fucking many headaches. Literally anything that doesn't leave titanium conveyors an awkward throughput.

**Comment by stuffyAI** [comment]
You lack critical information there, the titan conveyer is balanced for 10 items/sec throughput, it's simply 11 to allow Multiplayer lag to not impede efficiency.

In general I don't recommend making schematics that only work when all buildings work at 100% real time efficiency, just pretend like that 11 is a 10.

**Comment by TrueBlueFlare** [comment]
> You lack critical information there, the titan conveyer is balanced for 10 items/sec throughput, it's simply 11 to allow Multiplayer lag to not impede efficiency.
> 
> In general I don't recommend making schematics that only work when all buildings work at 100% real time efficiency, just pretend like that 11 is a 10.

Know what, that's fair. Just for the record I don't make schematics that only work with all buildings at 100%, but rather schematics that are optimized to try and keep buildings at 100%

**Comment by stuffyAI** [comment]
> I don't make schematics that only work with all buildings at 100%, but rather schematics that are optimized to try and keep buildings at 100%

Sure, but just remember that people put 2 pyrite and blast mixers for a single impact schematic, despite only one each would've been exactly enough, for a reason :)
