### ISSUE TITLE
atlas is too difficult

### ISSUE THREAD

**Issue by bukaixyz** [Anuken/Mindustry-Suggestions#4048]
### Describe what you would like changed, and why.

I'm stuck at this level

### Describe the changes you want to propose. Include possible alternatives.

decrease the difficulty

**Comment by Breadyboi69** [comment]
Skill issue

**Comment by R0cit** [comment]
Well that's your problem

**Comment by EnglishDotpl** [comment]
Basin: 'Hold my beverage...'
But legitimately, you should first ask on the server for any advice, rather than bring it straight to the staff. Otherwise, you'd be expecting *far* more "suggestions".

**Comment by bukaixyz** [comment]
I have modified this map by myself🌝

**Comment by yesC48** [comment]
> Basin: 'Hold my beverage...'

Siege: 'Hold my vodka…'
