### ISSUE TITLE
new unit not sure about the name tho..

### ISSUE THREAD

**Issue by C0RrupT3dN0d4t4F0unD** [Anuken/Mindustry-Suggestions#405]
hopefully add a new unit that has high speed but very low health and damage they come in groups of 5-10

**Comment by itcannotbe** [comment]
1. Template
2. Crawler

**Comment by C0RrupT3dN0d4t4F0unD** [comment]
> 1. Use the template
> 2. Crawler and Dagger: Hmmmmmmm

Oops sorry forgot to put the "flying type" and you must be thinking to say wraith fighters but I'm talking about something like half more speed than them and at the same time have 10% less health than the wraiths.

**Comment by Anuken** [comment]
Nah.

**Comment by C0RrupT3dN0d4t4F0unD** [comment]
sad
