### ISSUE TITLE
Encapsulated Fluids

### ISSUE THREAD

**Issue by TrueBlueFlare** [Anuken/Mindustry-Suggestions#4050]
### Describe the content or mechanics you are proposing.

A pair of buildings that encapsulate/decapsulate fluids, with encapsulated fluids functioning as items until decapsulated.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow fluids to be transported on conveyor belts as items, and to be transported between sectors in the campaign via launchpads.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LampbuIb** [comment]
neat idea! I disagree with the launchpads though; they already make the campaign quite easy, the capsules would need a big nerf with launching if they're to be balanced.

**Comment by itcannotbe** [comment]
For serpulo, it's already easy to make fluids on the spot, + logic based transport exist.

For erekir, dedicated payload blocks already do this.
