### ISSUE TITLE
Current unit control system makes it difficult to control large armies

### ISSUE THREAD

**Issue by akhial** [Anuken/Mindustry-Suggestions#4053]
### Describe what you would like changed, and why.

Currently there isn't a way to select all units on large maps, this makes it difficult to issue commands to all units as you have to pan around selecting units taking care to not forget any.

### Describe the changes you want to propose. Include possible alternatives.

It would be nice to have a "select-all" command to be able to give commands to all units on the map.
Or alternatively a way to select units from the map view, which can be zoomed out further than the normal view.
Also useful would be an option to select all units of a certain type. I think this would further improve the RTS side of Mindustry.

**Comment by oldyezero** [comment]
you can just do ctrl + double click on an unit for selecting all similar units on the map

**Comment by IVV-NCX** [comment]
Imagine, CTRL-A for select all, and something else for "automatically attack known enemies", etc. That would make PvP a little more fun without the logic, ja?

**Comment by itcannotbe** [comment]
> Imagine, CTRL-A for select all, and something else for "automatically attack known enemies", etc. That would make PvP a little more fun without the logic, ja?

That's not very RTS like of you.

**Comment by IVV-NCX** [comment]
> That's not very RTS like of you.
StarCraft is pretty similar in that regard though
