### ISSUE TITLE
_

### ISSUE THREAD

**Issue by AxoCat** [Anuken/Mindustry-Suggestions#4054]

**Comment by itcannotbe** [comment]
You do realized that preventing people from doing so was actually added in quite recently.

**Comment by Bottinator22** [comment]
it actually does hurt, the reason why it was disabled was because of how people kept complaining about balance

of course there's going to be balance issues when you're mixing things like that

**Comment by AxoCat** [comment]
IT IS OPTIONAL

**Comment by itcannotbe** [comment]
It was optional before.

That's nothing new.
