### ISSUE TITLE
Units with and without rotatable turrets and how they react.

### ISSUE THREAD

**Issue by Urkikk** [Anuken/Mindustry-Suggestions#4056]
### Describe what you would like changed, and why.

Let player-controlled Zenith, Antumbra, and Eclipse shoot without also forcing them to face toward the target's direction.
Also, make units without rotatable turrets to not wait for them to stay in complete still before starting shooting.

Right now, Zenith, Antumbra, and Eclipse despite having full 360° rotatable turrets on them, if controlled by the player will also make them face toward where the turrets are shooting.
However, this does not apply to Mega and Beta which also have full 360° rotatable turrets.

It's kind of strange that player-controlled Zenith can't shoot without also facing toward its target, resulting in a movement speed penalty, but things like RTS-commanded Zenith can shoot targets without making it face toward where it shoots, something that player-controlled can't do at all. This also includes AI-controlled Antumbra and Eclipse, guardians especially which constantly move, can also shoot while still facing at their destination.

Units that do not have any rotatable turrets like Flare, Poly, Avert and Obviate, AI-controlled units don't attack at all until they stay completely still even though they can just start shooting immediately, thus causing them to have a delay before they start rotating and shooting their target unless they already facing at its target when they come in.

This doesn't affect Avert and Obviate much since they already can slow down their movement pretty quickly but it really affects how Flare and Poly perform especially for Flare.

### Describe the changes you want to propose. Include possible alternatives.

Allow player-controlled Zenith, Antumbra, and Eclipse to shoot without affecting where they're facing. Maybe as an option or some sort of binding.
If it's a bind player can turn it on and off in combat, maybe make it work with all units too even though it can't do much but can still do something like for Quell and Disrupts with their missile, Scepter with its small turrets

For Flare, Poly, Avert, and Obviate(and enemy Alpha and Gamma?) make it so they start facing at target immediately after their target is within their range without waiting for their movement to stop so they can start shooting as soon as they can if there is a priority target. If there's no priority target, make them start doing it as soon as they're at their destination.
Or make Flare and Poly slow down their movement quicker to speed up their reaction. Speaking of slowing down movement, why we don't have any keybind to set a break on player-controlled units?

**Comment by itcannotbe** [comment]
Hope this will give rise to flanking/circling units (Units that can shoot 90° off from its direction of travel, aka shooting from the side.)
