### ISSUE TITLE
Game Data that supports multiple users

### ISSUE THREAD

**Issue by musicmonkey11** [Anuken/Mindustry-Suggestions#4057]
### Describe what you would like changed, and why.

The game is amazing, refreshingly perfect.
I think this ticket is unique.

Gamedata which is unique to the user is stored in the Mindustry folder. This creates problems on shared computers.

My son and I both own the game, and we log on as separate windows users to the same PC, we also log into separate steam accounts. The game doesn't share all its data, but there is some strange overlap.

I can't tell what file is overwriting what, and I don't know how much Steam Cloudsave is involved, but strange things seem to transfer between users when sharing a PC. I imagine if all users turned cloudsave off we would basically just be playing the same data?

Things that are shared (but should not be):
  -Schematics
  -Progress on unvisited locations (maps load with the other user's base up and running, and the sector secure flags up straight away)
  -Location availability (you can visit locations that the other user has visited, before it should be unlocked)

### Describe the changes you want to propose. Include possible alternatives.

I think many games solve this using the roaming folder or the local folder (c:\users\username\appdata) you already use roaming to store a .txt file.

If all progress data was stored there, then multiple purchases/instances per PC would be possible.

this same problem might also count for multiple users on android, I assume a similar fix would be suitable - I don't know how common this would be.

**Comment by itcannotbe** [comment]
I think this is something related to steam, since the data is already stored in

C:/Users/[Username]/AppData/
