### ISSUE TITLE
Balancing: Buff phase conduits

### ISSUE THREAD

**Issue by BalaM314** [Anuken/Mindustry-Suggestions#4058]
### Describe what you would like changed, and why.

Phase conduits are currently underpowered. Unlike phase conveyors, which are FAR faster than their normal bridge counterparts, they have the exact same speed as regular bridge conduits, making the only benefit the longer range, at the cost of power use and much higher resource cost.
This contributes to the problem of late-game fluid transport being... strange.

### Describe the changes you want to propose. Include possible alternatives.

1. Allow phase conduits to overdrive. This would make them far more useful in endgame.
or
2. Increase the throughput of phase conduits.
or
3. Decrease the cost or power use of phase conduits.
I'm not familiar with the way fluid transport is implemented internally, is it possible to do 1 or 2 without running into issues?

**Comment by itcannotbe** [comment]
You're getting speed and thoughput confused.

**Comment by BalaM314** [comment]
What's the difference? (for fluids)
