### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by IamE-T-P** [Anuken/Mindustry-Suggestions#4059]
### Describe the content or mechanics you are proposing.

Well, for the next update, if new content is added (new planet in the campaign) I would like it to bring the "Reidite" And "Zircon"

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the "Reidite" it would be a mineral which could be obtained either by mining it (if the planet had high levels of temperature and pressure) or it could be obtained by mining "zircon" and then giving that zircon to a new building capable of creating high levels of temperature and heat, 

with this material we could create a turret, which would shoot crystal fragments, which although they would not do much damage, the turret would attack with the crystals in an area of ​​5x5 and would shoot 8 times per second. compensating for its low damage

His attack range would be 18 blocks.

and the zircon could serve as ammunition for some turrets, in construction or to be used industrially. The zircon can be obtained by drills or a thing like plasma bore

that is my suggestion. I hope it can be taken into account

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Plastel** [comment]
there is zircon in dusted lands mod
try it out, it's fun.
