### ISSUE TITLE
A planet with full of water 

### ISSUE THREAD

**Issue by Jeelpatel2911** [Anuken/Mindustry-Suggestions#4060]
### Describe the content or mechanics you are proposing.

You can add 3rd planet which is full of water and the core will be underwater and instead of spacecraft you have to use submarine and we'll able use new type of gun and weapons 

[Electricity/Power]
add waves so we can use waves to generate power you can add underwater volcano which helps to get rare material and power

[Detailing]
"and yeah you can add water caustics on the bottom of the ocean (underwater surface) so that it'll help to understand everyone that we are underwater or you can add some details of bubbles or add some creatures" 

[Enemy]
also you can add robotic fish type enemy that bites our weapons and go away i mean one kind of destruction and giant robotic squids/octopus who can use his hand for destruction and can use his ink to temporary blindness to improve some difficulty robotic shark, whale, stingray as suicide bomber and electric eel/fish that can be used for power cutoff (you can use electric eel for power generation)

[Sound]
https://youtu.be/FwjlcdefiZg
This type of sound gonna be perfect for underwater scenario[Underwater sound ](https://youtu.be/FwjlcdefiZg) 

You can add new material on erekir and serpulo that's so rare and you need to find that material to make submarine and core and then you're able to play that underwater planet that means in order to play underwater planet you have to clear erekir and serpulo 1st 

Btw this game is amazing 😭 thank you for this masterpiece 🛐

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'll help to get more weapon that we can use underwater, more material different types of enemy etc... 

And as I said for submarine you can add new material that's rare right it'll help to increase curiosity about underwater planet 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
so basically you want Tantros

**Comment by Plastel** [comment]
eh


Anuke cancelled tantros development

**Comment by Jeelpatel2911** [comment]
> eh
> 
> 
> Anuke cancelled tantros development 

💀

**Comment by Jeelpatel2911** [comment]
> so basically you want Tantros

Tantros?

**Comment by Bottinator22** [comment]
The blue ocean planet that was there
It just got hidden around last v7 release
It is a blank slate

**Comment by Jeelpatel2911** [comment]
> The blue ocean planet that was there
> It just got hidden around last v7 release
> It is a blank slate

Oh i see i didn't know about that thank you ✨🐒

**Comment by Leo-MathGuy** [comment]
Maybe a new level of difficulty that you need to make a glass "roof" out of some material to build underwater, and an electric pump to pump water out of the base. You can make sealable walls so if enemies breach one "room" the whole base doesn't get flooded, this will add a new mechanic and strategy. Maybe you can even select which "floor" you want, ground or underwater, like using air bombers or building walls on the surface against boats and subs.

**Comment by Leo-MathGuy** [comment]
This will also use ducts, as they are sealed so you can transfer resources between bases
