### ISSUE TITLE
Multiplayer 

### ISSUE THREAD

**Issue by Poulposs** [Anuken/Mindustry-Suggestions#4061]
### Describe what you would like changed, and why.

Hello, can you please uprgade/rework multiplayer function on mindustry?
because honestly I loooooovvveee this game, but we cant play without knowledge in proxy and internet protocol....

### Describe the changes you want to propose. Include possible alternatives.

may be an account system or somethings like that.....

**Comment by itcannotbe** [comment]
You can just join public servers if you wanted to...

**Comment by IVV-NCX** [comment]
As they said.

Steam is another alternative. I believe they have better server support there.

**Comment by end-me-please** [comment]
there is no "easy" way to do multiplayer over the internet. It’s just not possible, especially without a central server (that would cost money to host)

**Comment by stuffyAI** [comment]
Sanest Mindustry suggestion.

**Comment by TheAirBlow** [comment]
Just use Radmin VPN (easier) or Zerotier (harder). It allows you to play campaign with your friends - go to a sector, open menu and start server. After that people who are in the same network in the app you chose will be able to detect your server as a LAN server.
