### ISSUE TITLE
Adding letters in @draw

### ISSUE THREAD

**Issue by IGitAustin** [Anuken/Mindustry-Suggestions#4062]
### Describe the content or mechanics you are proposing.

Adding a letter system (English for the meantime) that is printed on displays similar to how print works except this time it'll be on a text box(similar to how rect works) with font size, font color (RGB or hex) etc

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will be a lot easier for word displays as it will not  require a lot of logic for it to have a functional keyboard or such displays that require additional code just to draw a letter or word. We already have a really good template at the art channel in discord

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
This would be nice as a separate instruction - however:

- Only separate letters would be supported (the way draw calls are stored doesn't allow for variable-length strings)
- Significant thought needs to be put into the way letters are actually drawn (*a new monospace font is needed, letters must not be blurry, which is difficult to achieve in a straightforward way*)

**Comment by BasedUser** [comment]
Uhh... no.
