### ISSUE TITLE
Make mods unable to place blocks that haven't been researched in Campaign

### ISSUE THREAD

**Issue by A765-ALEX** [Anuken/Mindustry-Suggestions#4064]
### Describe what you would like changed, and why.

I want mods that assist players in placing blocks (AutoDrill, for example) to not be able to place blocks that haven't been researched in Campaign. Example: AutoDrill places Water Extractors next to the Laser Drills, and if I haven't researched them, the game doesn't let me place them.

### Describe the changes you want to propose. Include possible alternatives.

The reason why I'm proposing these changes is because players will be able to "cheese" the game by skipping the tech tree and Research altogether with mods.
I have noticed that mods like AutoDrill place the blocks as if the player were to select and click the blocks, then confirm. I think a possible way to fix this problem would be to simply not allow players to bypass research by banning blocks that haven't been researched, or not let players "plan" to place them like Schematics.

**Comment by itcannotbe** [comment]
Using mods are the player's choice. We can't really control people.

But I agree, mods like that kinda ruin how the game should work, but it's not the developer's problem. It's the problem of mod makers not having thought out campaign breaking senarios.

**Comment by Pointifix** [comment]
You can disable the placement of water extractors and power nodes in the mod settings.
