### ISSUE TITLE
Soundtrack on Steam

### ISSUE THREAD

**Issue by Hotmud9** [Anuken/Mindustry-Suggestions#4066]
### Describe the content or mechanics you are proposing.

Make the soundtrack available for purchase on Steam. It slaps so goddamn hard, and I want to listen to it when I'm playing other games too.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

My router in Christ it's just a good idea
You get money
I as well as everyone else gets the ability to play a slapping soundtrack

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If there is only some website were in you can freely view and download the game source code and resources.....

**Comment by Edwardl256** [comment]
Should have written this idea Before the music was freely available here on github.

**Comment by Hotmud9** [comment]
_I just wanna support the man_
