### ISSUE TITLE
make save data readable

### ISSUE THREAD

**Issue by vencorduser** [Anuken/Mindustry-Suggestions#4073]
### Describe the content or mechanics you are proposing.

making save data human readable for the ease of fixing your savefile/modifying

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make save data (such as settings.bin) use a file format like .json and store data in a way that is human readable for ease of modifying /savefile fixing(for example steam generator wont get researched on me and i cannot do anything about it since i cant modify the save data this is an actual scenario anuke pls help)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheAirBlow** [comment]
Save files are made to be binary to make it efficient. For settings usage of JSONs won't make much difference, but Anuken probably used binary anyway to save on his own time and sanity (basically sharing code is better)
