### ISSUE TITLE
Erekir unit ability names still broken

### ISSUE THREAD

**Issue by Mothyyyyyy** [Anuken/Mindustry-Suggestions#4075]
### Describe what you would like changed, and why.

Posted here since it isn't really a bug report, but it's only 10 days from v7's official launch and Tecta, Quell and Disrupt's abilities all still say "???ability.???". Looking into bundles there seems to be a name for Tecta's Shield Arc which should solve this, but it is not the case.

### Describe the changes you want to propose. Include possible alternatives.

Fix.

**Comment by end-me-please** [comment]
You’ve seen suggestions in bug reports, now get ready for bug reports in suggestions
