### ISSUE TITLE
Rotateable factory pls. 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#4076]
### Describe the content or mechanics you are proposing.

Make it possible to rotate factory after it's built. Sometimes you need to rotate heaters, heat redirector or electrolizer. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

That's would make building much comfortable.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
(PC) hold R, then use the scroll wheel to quickly rotate buildings
(Mobile) 
yeah we need support

**Comment by Kubek0212** [comment]
I'm pretty sure you aren't familiar with content already in the game. For mobile you just need to build the same building on top of existing one. This will instantly change the orientation with no extra building costs.

**Comment by Kryvytsky** [comment]
> I'm pretty sure you aren't familiar with content already in the game. For mobile you just need to build the same building on top of existing one. This will instantly change the orientation with no extra building costs.

It doesn't work with factory.

**Comment by Mythril382** [comment]
> It doesn't work with factory.

It won't work for blocks without rotations.
