### ISSUE TITLE
Right-clicking while in command mode should not cancel mining ores

### ISSUE THREAD

**Issue by Lonami** [Anuken/Mindustry-Suggestions#4077]
### Describe what you would like changed, and why.

Currently (v7.0 beta build 140), while in command mode (by default, holding shift), right-clicking to move units cancels mining ores.

### Describe the changes you want to propose. Include possible alternatives.

I think mining should not be canceled while in command mode (in fact I would prefer if right-clicking didn't cancel mining at all but I understand it might be good to keep it to easily cancel mining at any time).

Another alternative would be a Game Setting "Right-click to cancel mining" (on by default).

**Comment by haltalt** [comment]
A strongly connected issue: Polies, once controlled with shift, won't help you build. You'll need to bind them with a rpocessor and unbind them for them to return to their normal behaviour.

**Comment by Funny132** [comment]
> A strongly connected issue: Polies, once controlled with shift, won't help you build. You'll need to bind them with a rpocessor and unbind them for them to return to their normal behaviour.

Actually, they will. You just have to select them with Command Mode, and in the bottom right corner where it shows you what units you have selected, there's a set of different modes for them. Select "Rebuild" or "Assist Player". Mega units also have this behaviour.

**Comment by Lonami** [comment]
The above PR has been merged so this can be closed.
