### ISSUE TITLE
Pvp team choosing

### ISSUE THREAD

**Issue by Mechanicalenhancement1** [Anuken/Mindustry-Suggestions#4079]
### Describe the content or mechanics you are proposing.

Allowing us to choose the team we want to join on pvp matches at the start. Or at the very least giving map creators ways to indicate wich player joins wich team whilst creating a map. 

For example, If in a pvp mode I host I join blue team regardless if I placed the red core first. 

By just giving us an option to choose wich team we join at the beginning, or by letting players join teams in order of when their team cores were placed, it would add a bit more customisation.

Also, maybe adding more colours via hex codes (like the ones in hex pvp) would also be awesome!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will just add more customisation to how pvp matches can be managed and amybe adding more colour to the battlefield.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ilya246** [comment]
i made a plugin for this, look up teamChange in #plugins on the discord
