### ISSUE TITLE
Balanced mass item transport to replace snek

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#408]
**Describe the content or mechanics you are proposing.**
A new form of item transport, that consumes more power the more items it transports (similar to phase bridges, but with throughput being limited by power). Maybe something like 1-5 power consumed per item transported? Not sure how the input and output would work, maybe something that can be extended indefinitly but doesnt transport items unless powered.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would improve large multiplayer maps and late-game campaign gameplay, while providing a more balanced way of transporting items with insanely high throughput. Pretty much a more balanced snek.

Note: Im not sure if im doing this right, ping me on discord (@Scarf_Boy#1887) if im not. Thanks.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
A snek replacement is never balanced.

**Comment by ayangd** [comment]
I think, Phase Conveyors are the most suitable for snek.

**Comment by stuffyAI** [comment]
> This would improve large multiplayer maps and late-game campaign gameplay, while providing a more balanced way of transporting items with insanely high throughput. Pretty much a more balanced snek.

The current state suggests you to build more cores, which is supposed to be possible in 6.0, and transport the resources there.
I am not sure if the cores share the resources fully and you can unload them anywhere, but they can be used for building anywhere.
As for practical factories and ammunition distribution, you will have to use more belts should those exceed the 40 items/s from plastanium conveyors, at which point you won't lose too much since at this point phase conveyors should give you similar flexibility as sneks.

**Comment by Anuken** [comment]
Use phase or plastanium conveyors.
