### ISSUE TITLE
Chain Command

### ISSUE THREAD

**Issue by Alpine117** [Anuken/Mindustry-Suggestions#4084]
### Describe what you would like changed, and why.

When controlling units clicking on a point on the ground and into another, relying solely on the pathfinding can be frustrating.

### Describe the changes you want to propose. Include possible alternatives.

A proposal to allow Chaining of points, like pressing another hotkey (ctrl?, alt?, tab?) while controlling a unit will allow it to chain points it will move to. This will allow for better movement of units.

**Comment by 00001H** [comment]
This suggestion is not stale, and will be automatically opened.
