### ISSUE TITLE
Erekir cores should spawn poly like units when not used

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#4086]
### Describe the content or mechanics you are proposing.

In single player, whenever you build a core in Erekir, the core simply is used to increase unit and item capacity. It quickly becomes apparent however, that building smaller cores is useless as your production can be centralized around 2 or 3 main cores. I suggest that when an Erekir core is built but not commanded by the player (the player's core unit does not come from that core), the core unit that would normally spawn from that core should still spawn and assist the player like a poly. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This addition will make the building of additional Erekir cores actually useful when attacking sectors. As it stands right now, most players only build the cores after the sector has been captured, or often times not at all. Adding this would entice the player to invest resources into core to assist with building, instead of mostly ignoring the possibility of building more than 3 cores. 

Note, the units which spawn from the non commanded cores should not build at the full speed of a player controlled unit, as that would be broken, but they should still exist and assist the player in some shape or form.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 00001H** [comment]
REALLY GOOD
