### ISSUE TITLE
Anthicus Precept interaction

### ISSUE THREAD

**Issue by Garen7** [Anuken/Mindustry-Suggestions#4087]
### Describe what you would like changed, and why.

Currently Anthicuses can out range and outspeed Precepts and Vanquishes allowing them to kite them infinitely. Anthicuses already fill a good role for seiging due to their long range so it seems odd that they should win the fight when Precepts and Vanquishes don't have a niche to fill

From what I can tell Quells and other long range units slow down when they shoot so this shouldn't be an issue for them

Anthicus: 4.87 tiles/sec
Precept: 4.80 tiles/sec
Vanquish: 4.72 tiles/sec

### Describe the changes you want to propose. Include possible alternatives.

A very small increase to Precept/Vanquish move speed or a very small decrease to Anthicus move speed (either should only need a .2-.3 tiles/sec adjustment to prevent infinite kiting)

**Comment by Bottinator22** [comment]
Anthicus used to move much slower when firing, not sure what happened to that

**Comment by Anuken** [comment]
The slowdown was removed because it messed with the RTS AI control... I'll add it back.
