### ISSUE TITLE
Tank-like laser type UNIT.

### ISSUE THREAD

**Issue by HungryForWater** [Anuken/Mindustry-Suggestions#409]
I've been thinking of a Tanky Laser type BOSS unit that sits down whenever an enemy building or unit gets into its radius.

This Unit is a ground unit, It walks slowly, and when it detects an enemy building or unit, It sits down, charges up (make a cool animation please! :(( )  and shoots out a Meltdown-Like laser. 

I suggest placing a delay between the discovery of an enemy unit and sitting down.
Think of it like this: 
-The Unit detects an enemy building/mech
-The Unit waits for 0.5 seconds
-The Unit sits down and charges up
-BZZZZZZZZZZZ

I think this would be an amazing unit to add, It adds more variety to the current units we have. So we don't only have explosions,bullets,artillery and fire as projectiles/ammunitation in the game.

You can consider the laser a type of "energy" and make it counterable by PLASTANIUM WALLS.

**Comment by gen-NA-owl** [comment]
reminds me of the legged mechs, which means something like this might be added (As the legged boss isn't implemented yet)

**Comment by potatoisagender** [comment]
oh no its hungay

**Comment by Violet-Scarelli** [comment]
cough cough Corvus and Vela cough cough

Seriously tho congrats your idea made it
