### ISSUE TITLE
Small feature.

### ISSUE THREAD

**Issue by thetrulystupid** [Anuken/Mindustry-Suggestions#4097]
### Describe the content or mechanics you are proposing.

If a battery is damaged (~75% health or below.) and near leaking water, the water should damage all buildings touching the water. (you could decide the damage, i cant think of a fair number for this.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I personally think it could add a bit more strategy in a way, Yeah sure this would be a bit annoying if it was suddenly added and nobody knew about it, but, yeah.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
This would be annoying and unfun. It’s also not going to benefit the game, since it won’t add any depth or unique meta changes, etc.

**Comment by laserman367** [comment]
If you think it'd be annoying and unfun, why do you think it wouldn't change things? I think it's cool to have things have an inherit risk, like the neoplasia reactors with neoplasm having a dangerous waste product and some facilities blowing up violently when destroyed. Not sure if it's worth spending a lot of time on, but it might be simple to do if you reuse the surge wall effect for the damage

**Comment by itcannotbe** [comment]
This mechanic if implement will be used so rarely, it might not be even worth implementing.

Seriously, who actually runs conduits containing water near anything on serpulo? Water extractors are so prevelent that conduits containing water is rare.

Also add to the fact that power is dirt cheap on serpulo, batteries are close to useless.

Furthermore batteries aren't scattered on a normal serpulo map, players tend to just put them in some corner of the map, very far from any water.

So all that said, is it worth anyone's effort to put this in the game?

**Comment by end-me-please** [comment]
batteries already destroy stuff when destroyed. the damage they cause is worse for targets with wet status.

**Comment by TheTrueForce** [comment]
I'm neutral on this, but:
I do use pumps whenever I'm able, because I believe they're more efficient and certainly higher-volume than extractors. Because of this, I run water conduits around.
However, I don't leave them leaking voluntarily. And I also do stick my batteries off in a corner of the map where it's unlikely they'll be attacked, and I usually defend them as well.
It is a change. I don't know whether it'd be a good or a bad change. If it were me, I'd be inclined to try and mod in this behaviour to trial it first, of that's possible.

**Comment by thetrulystupid** [comment]
wow yall are fuckin angry over a small addition

**Comment by thetrulystupid** [comment]
buh-bye

**Comment by IVV-NCX** [comment]
> wow yall are fuckin angry over a small addition

Nobody was angry. They were quite reasonable about it. Simply discussing _why_ it wasn't desirable.

**Comment by thetrulystupid** [comment]
Well, different people see emotions differently n such, so.
