### ISSUE TITLE
Latum Suggestion

### ISSUE THREAD

**Issue by DanUnderscore** [Anuken/Mindustry-Suggestions#4098]
### Describe the content or mechanics you are proposing.

Renale should be a T1 and Latum a T5.

when a Latum dies, it splits into two T4s
when those T4s die, they split into two, totalling to 4 T3s
when those T3s die, they split into two, totalling to 8 T2s
when those T2s die, they split into two totalling to
16 renales

also it would be an threat to Tantros since Tantros is water

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

they're going to be super annoying so nerf some stats.

since Latum and Renale are hidden units, might as well make use for them in the new planet.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Tantros isn't going to be developed until V7 releases

And that's if someone starts to develop Tantros at all

Also, neoplasm on Tantros? You may as well just make all of Tantros a neoplasm ocean planet with a similar infection problem to Serpulo

**Comment by Bottinator22** [comment]
Considering the Tantros card on Mindustry Trello is archived, I don't think Tantros is even going to be finished

**Comment by qwertyuiop265000** [comment]
What's that game with the balloons and monkeys called again?

**Comment by DanUnderscore** [comment]
Bloons TD
