### ISSUE TITLE
Interplanetary Launch Terminal to launch to Astroid Clusters

### ISSUE THREAD

**Issue by Alpine117** [Anuken/Mindustry-Suggestions#4099]
### Describe what you would like changed, and why.

Seeing as there is Asteroid Clusters in the game, the recently removed interplanetary launch terminal can give function into launching into the Asteroid Clusters or even to Erekir itself. (Unlikely)

### Describe the changes you want to propose. Include possible alternatives.

When beating sector Planterary Launch Terminal, and getting the Interplanetary Launch Terminal, its use can be to launch to remote Asteroid Clusters to expand the game. Since it's "Interplanetary" it should be in both Tech Trees. And thus can be used to expand outside of the planets and into other celestial bodies.

With the issue of Erekir and Serpulo not having compatible tech trees, Interplanetary Launch Terminal can have only limited range or only in its orbit around the star. Meaning Erekir can only expand to its nearest Cluster of Asteroids and Serpulo can only expand to its nearest Cluster.

**Comment by A765-ALEX** [comment]
IDRK why Anuke doesn't just make the accelerator launch to asteroids, pretty sure map's already done for the asteroids.
