### ISSUE TITLE
Pixelart

### ISSUE THREAD

**Issue by FranLamark** [Anuken/Mindustry-Suggestions#410]
A new type of block usefull for only editor mode.

It would be good to make art in this game with certain blocks... at least for those who are really bored and have not much to do. Yes we have selectors that works well but not enought colors. And also the black portrait makes it look bit ugly.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Logic displays can already display pixel art; adding a third method of displaying images would be redundant.
