### ISSUE TITLE
More forgiving collision on ground units on Erekir

### ISSUE THREAD

**Issue by Hatrian** [Anuken/Mindustry-Suggestions#4100]
### Describe what you would like changed, and why.

Many of the Erekir maps have very small passages for units to move through. When you command two units to move through a small gap they will get permanently stuck against eachother until you make on of them move back. This is even worse with 15+ units because you will have to manually click on each one and move them through in a single file line. This has even affected enemies, causing my base to be completely safe with no attackers.

### Describe the changes you want to propose. Include possible alternatives.

As the title says, collision on the units could be made more forgiving so they can slip by each-other more easily. Alternatively, the AI could be adjusted so they will automatically move through without getting stuck.

**Comment by nilederg** [comment]
I have suffered with this for so long, I would love to have this fixed.
