### ISSUE TITLE
Description updates for units

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry-Suggestions#4106]
### Describe what you would like changed, and why.

I am proposing the following description updates for units to make mechanics of the game more straight forward

- Navanax lazer beams should be listed under one icon with x4 instead of each one being labeled individually
- Vanquish and Conquer should mention that they can trample buildings in their descriptions as an ability + the amount of damage done by the trampling
- Crabs should mention that they slow down when firing when applicable

### Describe the changes you want to propose. Include possible alternatives.

Small changes to the descriptions of units will allow for better readability as well as allowing newer players to understand mechanics easier. After all, it is a core database which should contain all the information that may be useful to know when using a unit.

**Comment by IlSashalI** [comment]
В целом идея хорошая,  он не сильно повлеяет на игру.
