### ISSUE TITLE
Turn mix-tech map ban into a fat warning saying smth like "this is not intended, it will be mega janky" 

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry-Suggestions#4107]
### Describe what you would like changed, and why.

I completely get not wanting to balance Serpulo and Erekir, but nobody is saying you have to. Players are going to find ways to have fun even when stuff is unbalanced. At the current state of the game, you've just created 2 separate games with a piece of scotch tape connecting them that is the option to switch which tech tree to use. Keeping mix-tech maps would create a sense of this being one cohesive game. Also, why bother learning a whole new game when I can just stay with the stuff I know? Having mix-tech would undermine that idea because you can now learn the new stuff AND stay in a familiar setting at the same time!

There's gonna be a lot of balance issues, but just having a message saying, "Hey, this is not an "intended" way of making maps and it's gonna cause some janky interactions" is a lot better than just outright banning those maps. If these balance issues are so bad, then map creators can just use the ban blocks option to fix issues, or get creative with world procs.

### Describe the changes you want to propose. Include possible alternatives.

Just allow mix-tech, with a warning stating the unbalanced nature of mix-tech, and that the two tech trees should be identified as completely different, not as Erekir is a subset of Serpulo.

**Comment by Bottinator22** [comment]
~~play the campaigns~~

also, joining a mixtech server has no warning about the balance, or anything like that, so someone who only joins big servers wouldn't know any of that

**Comment by A765-ALEX** [comment]
I agree, I think we should be able to play mixed tech outside of Sandbox with an unbalanced game warning. The only solution for now is to create a map in 138.1 and set it to <Any> planet in the game options.

**Comment by itcannotbe** [comment]
You can still play mix tech maps, you just can't create them through normal means.

**Comment by end-me-please** [comment]
this has been tried before.
People ignored the warnings and still complained, reported "bugs", etc
that’s why the option is gone now
