### ISSUE TITLE
Better sand drill on Erekir

### ISSUE THREAD

**Issue by laserman367** [Anuken/Mindustry-Suggestions#4109]
### Describe the content or mechanics you are proposing.

A new drill for sand (either ground or wall) or a way to boost the current sand crushers.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

At the moment the rate at which you obtain sand is consistent across the entire progression chain. Since you need more and more sand/silicon as you progress this gets to the point where you're spamming tons of sand crushers everywhere, individually contributing very little (unlike pumps, which also have no progression but give a large amount per pump). The further me and my friend got in the campaign, the more we grew to hate how slow this thing is. It feels as though progression on such a core material is missing. While beryllium goes from 0.75/s for a drill or 0.37/s for a square to 10.41/s for a drill (eruption) or 1.50/s for a square (boosted large plasma bore), sand just stays at 1.63/s for a drill and 0.81/s for a square.

If you don't want to make it too easy, the new drill or the overclock could require late game materials like cyanogen or phase fabric. Alternatively, (albeit not making a lot of sense), allowing heat to overclock it could be interesting due to space constraints. This would make it more about finding the optimal spots where you can supply heat while also being able to get the sand out rather than putting a sand crusher on every single spot with 2 blocks of sand. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JojoFR1** [comment]
I agree that we need more sand, but Anuke said that he will not add anything new to Erekir (and little late because the v7 is out)
But maybe something to boost can be added

**Comment by laserman367** [comment]
> but Anuke said that he will not add anything new to Erekir 

Are you sure about this? because judging by the 7.0 release post it sounds like he intends to continue work on erekir (after an extended break)

"There are still a few loose ends in the Erekir content. Those of you who have dug through the game files will know that there are several unused liquids, items, blocks and units. These may be expanded upon with future updates... eventually. I can't give any timeframe for when this will happen."

**Comment by JojoFR1** [comment]
> Are you sure about this? because judging by the 7.0 release post it sounds like he intends to continue work on erekir (after an extended break)

He talked about unused thing (so already made), for example the fissile matter, or a heat reactor,  or just some items/liquids and all, he's not creating anything new

**Comment by IlSashalI** [comment]
Для максимизации получения песка нужно ставить пескодробилки в определённых биомах. В их описании указана эффективность в разных биомах.
