### ISSUE TITLE
Command center

### ISSUE THREAD

**Issue by Nyanbou** [Anuken/Mindustry-Suggestions#4113]
### Describe what you would like changed, and why.

Reimplement the command center. It helps a lot with moving units.

### Describe the changes you want to propose. Include possible alternatives.

Units can follow the command center or automatically turn to the enemy

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Anything involving bringing back the old command system
