### ISSUE TITLE
Add a scout mode to Erekir units

### ISSUE THREAD

**Issue by ElliotTheDoge** [Anuken/Mindustry-Suggestions#4115]
### Describe the content or mechanics you are proposing.

The Problem
In the Erekir campaign it is really annoying to always tell this unit to explore this part and the other to explore the other part etc...
and it can get really annoying with big sectors.

To solve this problem I propose a "scout mode" where the unit will automatically explore unexplored areas

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The frustrating part of micromanaging exploration will be gone and the overall Erekir experience will be smoother

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by laserman367** [comment]
I feel like the inconvenience is intended. You can't do multiple things at once when it comes to others too, like you can't be mining while building or building multiple things at the same time, etc. It's a balancing act of "do I want more information of my surroundings or do I want more resources/buildings"

**Comment by ElliotTheDoge** [comment]
> I feel like the inconvenience is intended. You can't do multiple things at once when it comes to others too, like you can't be mining while building or building multiple things at the same time, etc. It's a balancing act of "do I want more information of my surroundings or do I want more resources/buildings"

Counterpoint, I think if it was really done for balancing we wouldn't be able to pause the game, give our instructions and builds and then unpause.

**Comment by BloodRaven0** [comment]
Such an option would be useful, but it would probably cause your units to self-destruct into the enemy base while trying to explore it, if there is no option to avoid enemy towers, which would be borderline logic automation, which I think is absent from Erekir for a reason.

**Comment by laserman367** [comment]
I'd say if it found the enemy base it's done its job, if you want to explore more, you could send a unit in a different direction before setting it to scout mode so it tries to explore somewhere else.

**Comment by 00001H** [comment]
> Such an option would be useful, but it would probably cause your units to self-destruct into the enemy base while trying to explore it

And that is exactly the intended drawback for using such a convenient feature.
