### ISSUE TITLE
Heat Blocks

### ISSUE THREAD

**Issue by JP16D** [Anuken/Mindustry-Suggestions#4116]
### Describe what you would like changed, and why.

Heat generation/distribution blocks should have their separate block group instead of being in "Production" block group 

### Describe the changes you want to propose. Include possible alternatives.

Add a new block group for the Heat generation/distribution blocks

**Comment by BloodRaven0** [comment]
+1 from me. Maybe the "Logic" tab (that contains only Canvas and Reinforced Message currently for Erekir) could be removed and its contents moved to the "Core" tab next to it, so we can have space for a dedicated "Heating" tab.

**Comment by IlSashalI** [comment]
Не думаю что это необходимо. Там слишком мало блоков(всего 6) чтобы выделять их в отдельную группу. Зато грузовые конвееры и котопульты я бы перенёс к конвеерам или вообще выделил в отдельную вкладку.
