### ISSUE TITLE
MORE BLOOM

### ISSUE THREAD

**Issue by adamlolgaming** [Anuken/Mindustry-Suggestions#4118]
### Describe the content or mechanics you are proposing.

in Mindustry there is a bloom option, with the max being 400% in my opinion the game looks better with higher bloom, so i think raising max bloom to 1000% would be funny and cool. (also bloom blur to 32 (optional))

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the bloom would make game more prettier for some ppl and would allow for more personalization

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
sad
