### ISSUE TITLE
Nerf arc

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#412]
**Describe what you would like changed, and why.**

Arcs are incredibly op, a 3x10 wall easily melts incoming enemies and can be supplied with just a single solar panel.

**Describe the changes you want to propose. Include possible alternatives.**

### Passive drain
Arcs drain some standby power 24/7 as to not be completely free.
They should be turned off between waves

### Power surge
No standby drain, but when draining battery power, eat it at an increased rate to promote having a power surplus for power-based turrets.

**Comment by Anuken** [comment]
Nerfed by increasing the energy usage by more than 3x.
