### ISSUE TITLE
More in depth RTS system (Starcraft like panel)

### ISSUE THREAD

**Issue by GleB2k19** [Anuken/Mindustry-Suggestions#4121]
### Describe the content or mechanics you are proposing.

Most RTS games have em but it would be nice to have it here as well. Basically a unit control panel with some extra options for all units such as: Hold/unhold position (unhold position means unit will follow target if it moves away. Stops following after reached its last known location), gather resources (this is possible alr but only with some units, but i need it with all possible ones), Force units to build diffrent buildings at the same time and etc. (Bad at explaining but if you played homeworldz aforementioned starcraft or any rts like that you will understand)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Would be easier to do pro gamer moves without learning scratch like mf (logic)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DanUnderscore** [comment]
no

**Comment by DanUnderscore** [comment]
i agre!

**Comment by GleB2k19** [comment]
Is this a good suggestion still?
