### ISSUE TITLE
New/better bridges for Erekir's Surge Conveyors and Reinforced Conduits (and a variant for Plastanium Conveyors on Serpulo)

### ISSUE THREAD

**Issue by Redoneter593** [Anuken/Mindustry-Suggestions#4122]
### Describe the content or mechanics you are proposing.

A new (item stack?) bridge can stretch longer gaps/distances and handle the throughput of a fully loaded Surge Conveyor, but is similarly more expensive and requires a small amount of power. 

A liquid/gas version (aka Conduit) of the new bridge for Erekir.

A resprited version of the new (item stack?) bridge conveyor tuned for Serpulo's Plastanium Conveyors. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Could really use an upgraded bridge for Erekir that can cover/span longer distances can keep up with Surge Conveyors, as well as a Conduit version for such. This way Surge Conveyors aren't getting clogged via Duct Bridges and don't require drones for otherwise short-ish distances.

Phase Conveyors currently can't handle the throughput from a full Plastanium Conveyor. Six full Titanium Conveyors fully load a Plastanium Conveyor, but Phase Conveyors can only handle three of those six. Adding a new (item stack?) bridge that works best with/around item stack belts (such as the Surge Conveyor) would help lots when using multiple Plastanium belts.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
For longer distances, you can always do, Payload mass driver + Loader/Unloader.

**Comment by itcannotbe** [comment]
Also you can always route other lower throughput transport methods around your higher throughput transport methods.
