### ISSUE TITLE
Maybe reset button could be shown with other color or style when the keybind is not the default

### ISSUE THREAD

**Issue by mdtrooper** [Anuken/Mindustry-Suggestions#4124]
### Describe the content or mechanics you are proposing.

It is a small UX change...I don't know if it is a lot of work, sorry.

I have change some keybinds and I don't remember what it is the default or not.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Reset button could be shown with other color or style when the keybind is not the default.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BloodRaven0** [comment]
Another way to do this would be to hide the reset button altogether when the keybind is in its default state. A lot of games do it like this.
