### ISSUE TITLE
&.0 phase bridge is op

### ISSUE THREAD

**Issue by iambadwithname** [Anuken/Mindustry-Suggestions#4125]
### Describe what you would like changed, and why.

my gory time has come to an end and also rip mass driver =(
ranking in 6.0:
-Mass driver, logic
-Phase bridge,  bridge
-unloader, platinum conveyor
-titanium conveyor, armor conveyor, container
-vault
ranking in v7:
-Phase bridge
-
-unloader
-
-
- logic
-
-Mass driver
-titanium conveyor, armor conveyor, container, platinum conveyor,   bridge, vault

And all my old schematics are trash now
I used to have a dream of many giga-factory each doing one thing and transporting using a mass driver which would be super epic and I all most made all of them so close to having all the power

![Screenshot_20221114-185045_Mindustry](https://user-images.githubusercontent.com/118178432/201653292-52f0dddf-a66b-4a68-a311-4b6dd0f442eb.jpg)

and please check out my schematic❤ it meant to run in v6 at high efficiency ( and also ignore the first 7 schematic I copy it online)

[11.14.2022.zip](https://github.com/Anuken/Mindustry-Suggestions/files/10002572/11.14.2022.zip)

### Describe the changes you want to propose. Include possible alternatives.

I want phase fabric to be Phase bridge and maybe return some old mechanics so I don't have to redesign my schematic

**Comment by hortiSquash** [comment]
phase bridges havent changed in years, and neither did mass drivers

**Comment by 00001H** [comment]
> phase bridges havent changed in years, and neither did mass drivers
yeah and what on earth does
> I want phase fabric to be Phase bridge
mean??
