### ISSUE TITLE
A slight modification to the way bullets handle targeting ground blocks

### ISSUE THREAD

**Issue by Funny132** [Anuken/Mindustry-Suggestions#4126]
### Describe what you would like changed, and why.

Currently, bullets will only hit a ground block (conveyors, ducts, or anything units can walk over) if they are targeting _that specific block._

This is good, as it prevents spamming really weak blocks to block enemy shots, but there's issues with this. To start with, a large group of units takes a very long time to clean up excess ducts/conveyors/any other ground blocks from an enemy base because excess shots don't hit anything, and it also means that certain units such as the Elude won't hit anything if they're too close to the ground block that they're targeting. So, here's what I propose.

### Describe the changes you want to propose. Include possible alternatives.

I think, rather than shots only being able to hit the specific ground block that they target, bullets and projectiles should be able to hit any ground block if the block that the unit was targeting when firing the projectile was also a ground block. Basically, if a group of units all target a duct, excess shots will hit other ducts in their path. If a unit's projectile targets a conveyor, other conveyors behave as solid blocks towards that specific projectile.

This change would fix (or at the very least help with) the issues I noted above.

**Comment by GleB2k19** [comment]
I agree since it takes like shit tonne of time to clean it
 up

**Comment by itcannotbe** [comment]
![Screenshot_20221115_154853](https://user-images.githubusercontent.com/45280919/201860362-f4b44725-098c-4835-a0b4-9410378526ef.jpg)

**Comment by iambadwithname** [comment]
you could destroy all core and then deconstruct it

**Comment by 00001H** [comment]
> you could destroy all core and then deconstruct it
uhh... I NEED the space to build factories to destroy all cores in the first place!!
