### ISSUE TITLE
(6.0) (logic) Add a comment command to the processors

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#413]
**Describe the content or mechanics you are proposing.**

Add a comment command to the micro/logic processor. It does nothing to the program, but it lets other people know what you're doing.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would make it much easier to read code in 6.0.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Rollcloud** [comment]
I've been using print statements, but a comment would be much clearer. Comments for most lines is standard in assembly, which v6 logic seems to resemble

**Comment by sample-text-here** [comment]
Ok, apparently starting a line with `#` will make the line a comment, but they get removed when you import/export from clipboard

**Comment by T1murik** [comment]
this suggestion duplicates more and more... anuke where are you
