### ISSUE TITLE
Make Slag Incinerator consume power and produce Slag

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4130]
### Describe the content or mechanics you are proposing.

Make Slag Incinerator consume power and produce Slag (instead of consuming slag) for maps that have no slag. Slag produced is per metallic item melted (Beryllium, Graphite, Tungsten, Thorium), although it can still destroy other items. Higher-grade materials will produce more slag per item.

Also, the incinerator will continue burning items even if it's full of slag and it's not outputted via conduits. (in order to keep current functionality as an item dump)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If a sector doesn't have Slag (like Stronghold), then it's impossible to make Surge Alloy and tech that sector up, even if it has an abundance of other great materials (again, looking at you, Stronghold). Even if the map has Slag, it would help if the player could produce it themselves if it's in an inconvenient or inaccessible location (like the enemy base). Requiring mineables to produce it will make it so you can't have unlimited slag on each map and will have to sacrifice your resource production for it in the early game, when you don't have access to a lot of mining nodes.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 00001H** [comment]
+1, but what if you DO have a lot of slag and don't wanna waste power? Add another block with this functionality instead? Make it the first ever building to have two modes you can switch between? or...

**Comment by BloodRaven0** [comment]
@00001H Well, mode switching is an option, but it would be somewhat complex for such a simple block.
Besides, the power requirements don't have to be anything ridiculous, something similar to a radar would work fine.
