### ISSUE TITLE
Remove Fog of War once the sector is captured

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4131]
### Describe the content or mechanics you are proposing.

Once the sector is captured, the player will be granted vision of the entire sector, without any Fog of War. Also, all Radars will stop working and stop consuming power.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, the Fog of War serves no purpose once the sector has no more enemies to fight. It is visually annoying and depressing having a lot of the map darkened and might hide parts of the map you haven't explored with units yet.
Building radars and distributing units to remove said fog consumes unnecessary power and might be annoying when trying to build over the units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EnglishDotpl** [comment]
Agreed, I do see the fog as a small thing that's bugging me after capping.

However- now, I'm unsure myself whether it will be a feature or not-, I would be curious about if and how will the fog "return" when the sector is attacked from a neighbouring base.

**Comment by BloodRaven0** [comment]
@EnglishDotpl I don't think the sector attack mechanic is implemented on Erekir (at least I haven't gotten to a point in the campaign where it happens, correct me if I'm wrong), since it does not allow you to go to other sectors while you're playing an uncaptured one. Seeing as Fog of War is only on Erekir, I don't see this as being a problem.

However, even if it were, the Fog of War could easily be re-enabled if a sector becomes contested again, and all radars will resume working.

**Comment by EnglishDotpl** [comment]
Understood that, @BloodRaven0 (counter-ping!). Guess we'd have to wait and see if perhaps later it could make an appearance on Erekir, too. 
But that aside, your suggestion has a green-light from me. ~~Now to hold up the suggestion till some dev actually reviews it!~~

**Comment by nilederg** [comment]
Will sending this message revive the issue? I agree with the premise.
