### ISSUE TITLE
Separate Serpulo and Erekir Core Databases and Schematics

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4132]
### Describe the content or mechanics you are proposing.

When playing on Serpulo, you won't be able to see Schematics made for Erekir and vice-versa.
Also, the Core Database menu will have two tabs, one for Serpulo and one for Erekir, containing the respective content. The correct menu will open by default when clicking the button while playing on each planet.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It is impossible to use Schematics made for the planet you're NOT playing on, so it's useless to pollute the menu with useless entries. This will make searching for the correct schematics faster.
The same goes for the Core Database, it's currently a mess of both planets' tech trees and it's very hard and confusing to find what you're looking for.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Devilsknock** [comment]
Instead of separating them, could maybe just make filters with tags for each planet. When you make a schematic, you can tag both planets for either. Same idea could maybe work on the database though that does feel less useful than a schematic filter toggle.

**Comment by itcannotbe** [comment]
A drop down might suffice though.

**Comment by BloodRaven0** [comment]
It would be great if someone actually read these before they get "stale" after only 20 days.
