### ISSUE TITLE
Resizable minimap (and option for Pixel-Perfect minimap)

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4133]
### Describe the content or mechanics you are proposing.

-The minimap window will be resizable via mouse-dragging or tap-and-hold-and-dragging its corner.
-The minimap will have a "Reset Scale" button (or hotkey) that will resize your minimap window, so each pixel on the minimap corresponds to one tile on the map. Basically a less finicky way to make the minimap pixel-perfect.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The current minimap is way too small on a FHD monitor, compared to the rest of the UI. Using the UI scale to make it bigger will make the rest of the UI bigger, obscuring the game screen. Detaching it from UI scale and allowing the user to manually resize it will make everyone happier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Full HD be like:
![Screenshot_20221117_150459_com cpuid cpu_z](https://user-images.githubusercontent.com/45280919/202379034-daefaac5-c779-4457-bd2f-bf1922ebb1b0.jpg)

**Comment by BloodRaven0** [comment]
Yeah forgot to mention phones have it even worse, because their resolution is even bigger than full HD and they have to reduce the UI scale to see anything, which makes the minimap comically small (mine is set to 75% and a quarter of the map is taken by the damn curve on my screen).

**Comment by COALROCK8642** [comment]
I use mini map so much I rather prefer to have left or right half for just mini map with accurate mapping.
