### ISSUE TITLE
unification of planetary technologies (unique)

### ISSUE THREAD

**Issue by SilinVeredno** [Anuken/Mindustry-Suggestions#4134]
### Describe the content or mechanics you are proposing.

addition to the campaign combining Serpulo and Erekir technologies. An important feature: each block of planets must be associated with another planet (there will be no selection of blocks by functionality for this mechanic). it is important to understand that if technologies are combined, then blocks and units must have new, similar textures to each other.

I think you can not change some blocks and not create a separate "database" as for a separate planet. I'm just really sad that there are cool things on Erekira and not on Serpulo. depending on the place where these technologies will be mixed, you can remove some blocks from the mixing technologies tree

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it will be much more interesting to play the campaign

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SilinVeredno** [comment]
Google Translate:

**Comment by BloodRaven0** [comment]
I don't think the two tech trees were made to be mixed. I think they're better off separate.

**Comment by brick96** [comment]
i think it would really cool if custom maps could make use of both tech trees

**Comment by BloodRaven0** [comment]
There may be mods that do that. I stumbled upon one called "Happy Times Mod" that claims to make Erekir components available on Serpulo, although I haven't tried it, since I have no interest in such a thing. You can find it in the mod browser and possibly even find other mods that do the same thing.

**Comment by COALROCK8642** [comment]
Let's just leave this to serpulo + erekir, PVPs
