### ISSUE TITLE
Old Campain Mode

### ISSUE THREAD

**Issue by CodeableSyth** [Anuken/Mindustry-Suggestions#4136]
### Describe the content or mechanics you are proposing.

I really liked the old campain mode, where you could only launch at certain waves, to the point i installed the older version of the game just so i could play like that agian. is there a way you could do that as a setting in the newest version of the game too?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

no clue, sadly

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BloodRaven0** [comment]
I think there is potential in this suggestion. Maybe we could have some nodes that have "endless" mode enabled and will keep spawning enemies until you extract or are wiped out. If you extract, you get to keep all the resources you gained (and these sectors could be very resource-rich), but if you go to the planetary map to play another sector, they won't produce resources passively, just save your progress and pause until you return.

Waves will get harder and more frequent the longer you stay, and there could be statistics and leaderboards showing who beat the most waves. It will give endgame players something to do in single player.
