### ISSUE TITLE
Small but significant map editor additions

### ISSUE THREAD

**Issue by Pirojok3000** [Anuken/Mindustry-Suggestions#4137]
### Describe the content or mechanics you are proposing.

**Add new objectives to the editor that can track more actions and end the game.** _Goal to survive X waves_ and _goal that ends game when previous goal is achieved_. This is basically a "win" option for custom survival maps. It will add more flexibility to custom maps and can make them more interesting when endless survival gets boring.
**Add ability to remove and place enemy spawn points with world processors or goal system**. In cases where creator needs to build a simulation of progress and movement on the map, this function will be necessary.
**Add ability to sellect enemy cores as spawn point**(just like we can configure waves for enemy spawn zones from survival). This will bring a huge improvements to attack map building. More customization - better map quality!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The game editor provides good features, but the missing details in my opinion seriously limit the creation of maps in some cases. It's not always fun to attack enemy cores or survive endless waves. Adding such features will open up new gameplay possibilities on custom maps and refresh the old attack and survival modes.
More detailed customization is possible thanks to these simple functions. With this addition, each map can have its own ending, And the presence of existing world processor capabilities and goals will allow players to create really interesting custom maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BloodRaven0** [comment]
Absolutely +1!
This could be the thing that really springs the modding and mapmaking community around this game to life.
One of the best things about the Warcraft 3 map editor was the absolute freedom it gives you to do and script whatever you like, and its community is alive to this day, 20 years later. Would love to have such a thing in Mindustry.

**Comment by Pirojok3000** [comment]
Addition: adding ability to change unit type in Destroy units objective w
