### ISSUE TITLE
Tanks shouldn't be able to interact with a junction.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#414]
**Describe what you would like changed, and why.**
Prevent directly using a junction with a tank. To prevent using junctions as a main transport method, it makes conduits useless.

**Describe the changes you want to propose. Include possible alternatives.**
None.

**Comment by ILiekMelons** [comment]
I don't think junctions with tanks should be entirely disabled because there might be some niche use case for this. Having 3/5+ junctions in a row, however, shouldn't work at all because there really isn't any use for it (besides what you mentioned)

**Comment by BlueWolf3682** [comment]
if I can't have tank with junctions I'll just have tanks 👀

**Comment by DeltaNedas** [comment]
liquid routers are tanks, this completely gimps junctions but its good

**Comment by HaphLife** [comment]
are fluid junctions faster than pulse conduit or something?

**Comment by XxsuperdeadlysniperxX** [comment]
Liquid junctions are slow tho i think

**Comment by BlueWolf3682** [comment]
lol no, junctions are for lack of a better term infinite

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
