### ISSUE TITLE
More icons for Schematic Tags

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4141]
### Describe the content or mechanics you are proposing.

All the white (monochrome) icons that are available for planetary sector selection should also be available in the schematics tags menu.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

We're missing icons for things like "Power" and "Combat", for which there are perfect icons already made. This will give users more customizability and freedom to organize their schematics better, without relying on ugly and space-consuming text tags.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by COALROCK8642** [comment]
Custom Icons? We already have custom text.
