### ISSUE TITLE
please make a easier way to kick people

### ISSUE THREAD

**Issue by tecno9877** [Anuken/Mindustry-Suggestions#4145]
### Describe what you would like changed, and why.

its getting impossible to play multiplayer because every server people delete things and its way easyer to delete than 
rebuild im not saying to slow down the "delete block" funcion just make a way to kick people before they destroy everything

### Describe the changes you want to propose. Include possible alternatives.

1-you can put a keyboard button that bans a certain person when you click on him (of course when enough people click to ban him) wen that button is pressed it create an area that select player wittin that area
2-when he is banned from the server the person will be banned for a certain time from the multiplayer and if he continues to be banned he is banned not only from the multiplayer servers for a while but also from the normal game otherwise he will just wait for time to pass in the singleplayer and will continue to disrupt other players

**Comment by Phinner** [comment]
> 1-you can put a keyboard button that bans a certain person when you click on him (of course when enough people click to ban him) wen that button is pressed it create an area that select player wittin that area

There is already a button to kick a player in the player list, why adding another ?

> 2-when he is banned from the server the person will be banned for a certain time from the multiplayer and if he continues to be banned he is banned not only from the multiplayer servers for a while but also from the normal game otherwise he will just wait for time to pass in the singleplayer and will continue to disrupt other players

The game itself would need an account system to be able to do that, but it will never happen (for obvious reasons).

Besides, anti-griefing tools are implemented by the server owners themselves. Some have great defenses against griefing (automods, revert player actions, etc...) and some don't have them. If the server you are playing in is filled with griefers, you can either tell the server owner to do something about that like using anti-grief plugins, recruiting moderators, etc... Or playing on another server that handles griefers properly.

**Comment by end-me-please** [comment]
and global moderation isn’t possible. Mindustry has no account system
