### ISSUE TITLE
Interplanetary Accelerator rework/giving it a purpose

### ISSUE THREAD

**Issue by solisruben296** [Anuken/Mindustry-Suggestions#4148]
### Describe the content or mechanics you are proposing.

So the Interplanetary Terminal launcher thing i can't remember it's name. It currently has no use, right? Well I am here to propose that when you obtain it, load it up with resources and launch it, you'll be able to land on other planets (let's say Erekir)

However, that doesn't start the normal Erekir campaign, but rather it uses up the sectors that are currently empty and combines Serpulo and Erekir elements for a sort of duel type gameplay.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Many things.
Firstly, logic with Erekir items/units would be pretty neat. Scathe basically forcing you to use a mod if you want to use it long range, and units being unable to do more intricate actions on their own.

Secondly, "variety"
It's true no real new content would be added, since it would just take two existing elements and combining them together however i see rarely any maps that combine the two together, modded or otherwise.

Thirdly, more replayability since having more items at your disposal would let you try out different things such as overdrive projectors with a Malign. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Dev: It's important to make clear that *these two planet tech trees are not supposed to be mixed* and impose restrictions on their use because nobody reads

OP: ![I don't want to see that](https://media.tenor.com/CA7TOPJp5r0AAAAM/sleep-sleepy.gif)

**Comment by IlSashalI** [comment]
Пока на эрекире нет межплонетарного ускорителя. Так что запуски ресурсов были бы односторонними
