### ISSUE TITLE
Item Source but for units

### ISSUE THREAD

**Issue by SupremeTurtle** [Anuken/Mindustry-Suggestions#415]
**Describe the content or mechanics you are proposing.**

A unit source that has a selection of all the units you can choose from, so that you can spawn them endlessly. It could be 1x1, with a time delay of when the units spawn that you can adjust. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Making units in sandbox is kinda tedious since you have to work with reconstructors. With a unit source, you can make units effortlessly.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Why do you need this again?

Also unit cap still exist in sandbox. This just messes it up as you can't order your units to suicide.
