### ISSUE TITLE
Force projector rebalance

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#4151]
### Describe what you would like changed, and why.

rework the current force projector to not work the way it does now, but instead shrink when it takes damage and expand when regenerating; also make it not overheat unless it takes damage over the amount of health it has left
i'd say this is needed since force projector is bad right now, this would make force projector much more feasible to stack and give their placement actual tactical value (as placing them closer to your walls would actually have value) which could make them more interesting to use as well
(relevant messages in #balancing: https://discord.com/channels/391020510269669376/813425645518061678/1043770876224606239)

### Describe the changes you want to propose. Include possible alternatives.

instead of working like the way it does now, make force projector decrease in radius proportional to damage taken and increase in radius as it regenerates, if health goes into the negatives, do not clamp it to 0 (maybe give it a lower limit though so you can't just shut down a force projector forever)

**Comment by IlSashalI** [comment]
Ещё было бы неплохо поднять ему хп и регенерацию. А-то он ложится после пары десятков выстрелов и никак не помогает в обороне. Даже у медной стены хп больше.
