### ISSUE TITLE
Tooltip or notification regarding launching from certain sectors

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry-Suggestions#4156]
### Describe the content or mechanics you are proposing.

I suggest that a small tooltip is added that tells you that you can open the planet map when in a sector and launch from wherever you choose.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, people get very confused when they want to launch to, say, Ravine, but can't because it requires tungsten and it's launching from Lake. There's at least 5 help requests in #help every day.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IlSashalI** [comment]
Или можно сделать так, чтобы ресы для запуска брались сразу из всех секторов. Всё равно там нужно очень мало.
