### ISSUE TITLE
rebuild deleted blocks

### ISSUE THREAD

**Issue by adamlolgaming** [Anuken/Mindustry-Suggestions#4157]
### Describe the content or mechanics you are proposing.

a button you can bind that if you hold will make a box like f or b, would rebuild last deleted structures

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

griefers are annoying, adding that button will make the grief have less impact on the game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by virat2010** [comment]
This couldn't be feasible.
Anuken rarely likes to change features of Mindustry for online server's sake. It does happen though: the Zenith Debuff.
It would also be hard to understand. Like how? The ones you deleted or someone deleted? And who's was deleted, yours or theirs? It would be extremely complicated and a waste of server and client memory to store such changes and revert then you would be proposing a git like change to mindustry history system.

**Comment by genNAowl** [comment]
Ummm,

 I don't think this is a bad idea, or a confusing really - it's just the ability to rebuilt recently deleted blocks in an area. 

Also, I don't think implementation/performance impact wouldn't be hard either; It's just a queue of deconstructed blocks, the same way broken blocks work. Think about it: All the blocks on a server can be destroyed (like by enemies) and your Mindustry will perform perfectly fine, even with the rebuild capability and ghost blocks. This is just a different version of that, as why would deconstructed blocks be much different than broken ones?
