### ISSUE TITLE
Возможность построить блок на грузовом конвеере.(для эрекира)Title

### ISSUE THREAD

**Issue by IlSashalI** [Anuken/Mindustry-Suggestions#4158]
### Describe the content or mechanics you are proposing.

Я предлогаю добавить в игру возможность строить блоки или хранилища сразу на грузовом конвеере вместо того чтобы строить их на земле и переносить. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Это позволит быстрее и легче ставить постройки на грузовые конвееры.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
- [X]  I am **not** familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Slotterleet** [comment]
> * [x]   I am **not** familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

They meant _building_ containers on top of payload blocks (in this case, conveyors). I don't think that's gonna happen TBH.

**Comment by itcannotbe** [comment]
Erekir has constructor/decontructor blocks. But I doubt anything like this would be made available for serpulo though.

**Comment by IlSashalI** [comment]
> * [x]   Я **не** знаком со всем контентом, который уже есть в игре, и не просмотрел вики, чтобы убедиться, что моего предложения еще нет в игре.

**Comment by IlSashalI** [comment]
> * [x]   Я знаком со всем контентом, который уже есть в игре, и не просмотрел вики, чтобы убедиться, что моего предложения еще нет в игре.
**К чему ты это вообще?**

**Comment by IlSashalI** [comment]
> В Erekir есть блоки конструктора/деконструктора, но я сомневаюсь, что что-то подобное будет доступно для serpulo.

Я знаю что существует блок конструктора но некто не будет ставить его и проводить все конвееры с ресурсами для того, чтобы создать 1 хранилище. + для создания блоков 3 на 3 и больше нужен большой конструктор, а но очень дорогой.

**Comment by IlSashalI** [comment]
> 

Что такое ТБХ?

**Comment by itcannotbe** [comment]
> Что такое ТБХ?

Because you should be suggesting things that already exist in the game.

Let me remind you why you are suggesting your suggestion:

> This will allow you to quickly and easily put buildings on cargo conveyors.

**Comment by Ruichka** [comment]
> > Что такое ТБХ?
> 
> Because you should be suggesting things that already exist in the game.
> 
> Let me remind you why you are suggesting your suggestion:
> 
> > This will allow you to quickly and easily put buildings on cargo conveyors.
> 
> And this is your suggestion:
> 
> > I propose to add to the game the ability to build blocks or vaults directly on the cargo conveyor instead of building them on the ground and moving them.
> 
> Things that exist in the game:
> 
> A block that will automatically make a block, a block that will load items/fluids into a block, a block that will take items/fluids out of a block, A block that will automatically deconstruct a block, and payload conveyors that can transport blocks.

I think he meant building on the conveyor with the core unit, which, tbh, doesn't make this suggestion useful anyways.

**Comment by IlSashalI** [comment]
И я так и не понял что такое TBH?

**Comment by IlSashalI** [comment]
Даже если это функция не будет очень востребована, она сделает игру проще.
