### ISSUE TITLE
Local LAN synchronization

### ISSUE THREAD

**Issue by Sky-NiniKo** [Anuken/Mindustry-Suggestions#416]
**Describe the content or mechanics you are proposing.**
If two devices are connected to the same network, a button will allow you to export a save or import a backup. But without saving anything to the devices.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This system would make it possible to quickly synchronize two devices without having to export the save on one, then transfer it and finally import it on the other, which would save a lot of time. I know that Anuke doesn't want to make a synchronization system but it would be rather easy to code since you just have to send a file over a network. But if Anuke still doesn't want to do it, it's the choise of Anuke.

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I don't see the purpose of such a system.

> This system would make it possible to quickly synchronize two devices without having to export the save on one, then transfer it and finally import it on the other, which would save a lot of time

If you set up a folder sync, none of this is necessary. Even if you don't, this isn't much slower than an elaborate save transfer system.

> a button will allow you to export a save or import a backup

You can already get the current save in multiplayer games.
