### ISSUE TITLE
Улутшение всех т3 эрекира.Title

### ISSUE THREAD

**Issue by IlSashalI** [Anuken/Mindustry-Suggestions#4160]
### Describe what you would like changed, and why.

Я считаю, что нужно усилить т3 эрекира. Они уступают т4 по силе(особенно танки т3. Они ничего не мигут)но при этом для их производства нужен торий(которого почти никогда нет на спавне). Тем временем т4 можно создавать из начальных ресов.(берилий, графит, кремень, аркацит, вольфрам)

### Describe the changes you want to propose. Include possible alternatives.

Люди начнут использовать т3, а не сразу переходить от т2 к т4

**Comment by UAdustry** [comment]
Чел, т3 на то т3 что они уступают т4

**Comment by IlSashalI** [comment]
> Чел, т3 на то т3 что они уходят т4

Да, но т3 должен быть дешевле т4, а на эрекире  т3 не только намного хуже т4, но и требуют для создания торий, а т4 можно сделать из начальных ресурсов. Создание т3 просто нецелесообразно.

**Comment by IlSashalI** [comment]
И я это уже писал
