### ISSUE TITLE
Persistent war on Ground Zero

### ISSUE THREAD

**Issue by 00001H** [Anuken/Mindustry-Suggestions#4161]
### Describe the content or mechanics you are proposing.

G0 becomes vulnerable. Every time you achieve a certain milestone(for example, 1st launchpad constructed), it gets attacked after 7 mins or so(with a warning 5 mins before the attack of course). You have to launch resources there and build high-tier infrastructure(like seperators, thermal gens, lancers, cultivators, etc) to stop the additional waves.

There will be a continuous battle on G0 where crux will continue to send higher-tier waves as you fight back and you have to setup higher-tier production there to compensate.
Also, launching should be disabled during battle to encourage players to actually build higher-tier factories and scrap-to-stuff and not just turn G0 into a purely offensive base.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can be a fun challenge, and this also makes sense as crux should hate G0 a lot(since thats where your takeover begins)
It can also be a very different experience to focus on a single sector, rather than "conquer here, cnquer there" nomad-style gameplay.

~~It also shows how much can be done with just copper,lead scrap and water, and limited launched resources.~~

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ErosAa2** [comment]
you know when north pole of the serpulo isnt enough,you try to actually make crux smarter by sending a reign in ground zero

**Comment by IlSashalI** [comment]
А что если игрок просто отдаст  G0 вразам чтобы не делать его. Там всё равно только медь и свинец.

**Comment by 00001H** [comment]
> А что если игрок просто отдаст G0 врагам чтобы не дефать его. Там всё равно только медь и свинец.

Good Q. Losing G0 will immediately make you lose the game, entirely.


(Translation: And what if the player just gives the G0 to enemies so as not to defeat it. There's still only copper and lead.)

**Comment by IlSashalI** [comment]
> 

Но что если чел будет играть неделю, дойдёт до последнего уровня, забудет про G0 и потеряет весь прогресс

**Comment by IlSashalI** [comment]
А ещё это не очень логично

**Comment by IlSashalI** [comment]
И я писал дефать - защищать. От слова defense.

**Comment by 00001H** [comment]
Well, after you re-capture G0, and go to other sectors, just like losing other sectors normally, there WILL be a lot of remains of your old buildings.
Also, you get to keep your tech tree researches, which is already very very helpful.
