### ISSUE TITLE
Map idea: Infected Mountains

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry-Suggestions#4162]
### Describe the content or mechanics you are proposing.

I propose adding a new map to Erekir after the "final" map is beaten, like a bit of a bonus map.

In this map, there's Neoplasm on the ground and Dormant Cysts in the walls- Wall Crushers have a chance of releasing these cysts.
Latums and Renales would be the main enemies in this map- more or less, it's a bit of a boss rush.

With the map, 2 new blocks would be added: The Cancerous Mixer (more consistent Dormant Cyst creation, for when RNG wants you dead), and the Biological Cultivator (a way of making Renales, and potentially even Latums).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The Dormant Cyst item and Neoplasm have no use- and one of them is even hidden. Adding them back in a way people could mess with as they could would allow for a lot of new ideas.

To be honest, I really don't know the full of how this would improve the game. I was just theorizing in the Discord and came up with this idea out of the blue.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RFAC-Productions** [comment]
Dormant Cysts could allow the production of Renale units, since they're possibly neoplasm in solid form. What stops you from using regular old Neoplasm? Honestly, I'm not that creatove enough to rhink of a reason.

**Comment by Erisfiregamer1** [comment]
Neoplasm is a liquid, Dormant Cysts are (APPARENTLY) solid. Having a completely liquid unit makes no sense, no?

**Comment by IlSashalI** [comment]
Сборьщик больших юнитов(забыл как называются) может требовать для работы неоплазму, вместо циана, маленьких юнитов(которые появляются из большого при смерти) и блоки из фазовой ткани.
