### ISSUE TITLE
Weaponizing Neoplasm

### ISSUE THREAD

**Issue by IGitAustin** [Anuken/Mindustry-Suggestions#4164]
### Describe the content or mechanics you are proposing.

Making Neoplasm useful as a type of bioweapon instead of hazardous waste that is useless

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since there is a secret unit that uses Neoplasm as health (although probably not getting implemented), at the very least try to use it as a weapon against enemy water supplies or as a risky type of ammunition in a new turret.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The main point of Neoplasm is that it is hazardous waste that you need to dispose of haphazardly, made from a end game tier building.

**Comment by BloodRaven0** [comment]
Well, you would still have to dispose of it somehow once the turret is full or your reactor will explode.

You actually already have a way to weaponize it, just use the enemy's neoplasia in their own base. For example destroying the conduit that outputs it from the reactor will make it explode, or breaking it near water containing blocks so it spills could be effective too.

But I feel Neoplasia is not hazardous enough. Maybe we could make it eat through more things, like ALL liquid-containing blocks; or have the pool keep growing (or eventually start spawning those small neoplasia enemies) if you're just spilling it and not disposing it inside a slag pit, as the description suggests.

**Comment by miner-sd** [comment]
you can currently attack enemy water systems using fluid container payloads of neoplasm
