### ISSUE TITLE
Unit Tech Tree hierarchy adjustment

### ISSUE THREAD

**Issue by larriecorvell** [Anuken/Mindustry-Suggestions#4166]
### Describe what you would like changed, and why.

The different type of Fabricators are shown on different tree levels/depth. Their corresponding Refabricators are also not connected directly to them.

This could be reorganised to indicate their relationship better.

Current Unit Tech Tree:
![unit tech tree (original)](https://user-images.githubusercontent.com/87235888/204080136-3d64b1f5-5c9c-49d4-b32c-61ca8ed13d12.jpg)

### Describe the changes you want to propose. Include possible alternatives.

Technologies of similar level should be shown on the same level so it's easy to visually recognise their counterparts in the hierarchy. Prerequisites are not necessarily indicated by connecting line (as usual by simply stating the necessary tech/resource/sector to unlock it when it was hidden/locked).

Unit types produced by the fabricator/building can be shown as a child (connected vertically) or with a horizontal branch which then goes down vertically (allowing the same building to list multiple possible units).

Adjustment examples:
![unit tech tree (revised)](https://user-images.githubusercontent.com/87235888/204080576-2c41d319-3e83-4bba-b12f-266c47cc5289.jpg)

The same principles could be applied to the other categories as well to show a more logical groupings of technologies.

NB. Compare the use of tech tree to illustrate A) technology category/grouping and/or B) their unlocking prerequisites (which would be too complicated to consistently and completely connect, considering that the sectors and resources that are required to unlock building techs are also listed on the same tree. Therefore using the tech tree to indicate the logical categories/relationship might be preferable and easier to visualise).

**Comment by IlSashalI** [comment]
Хорошая идея.
