### ISSUE TITLE
Chances of Metriod hitting the two planets

### ISSUE THREAD

**Issue by DanUnderscore** [Anuken/Mindustry-Suggestions#4167]
### Describe the content or mechanics you are proposing.

Make it so that theres a 0.01% chance that an metroid will hit Serpulo or Erekir once you beat a sector, which means you have to restart the campaign of the planet that was hit. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

"Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche."

oh yeah this will add more gameplay options

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IlSashalI** [comment]
Какой смысл? Просто сделать шанс потерять месячны прогресс?

**Comment by DanUnderscore** [comment]
Yes

**Comment by BloodRaven0** [comment]
No.
