### ISSUE TITLE
Useful parralax

### ISSUE THREAD

**Issue by UAdustry** [Anuken/Mindustry-Suggestions#4168]
### Describe what you would like changed, and why.

I want to change parralax - the most useless turret on Serpulo

### Describe the changes you want to propose. Include possible alternatives.

Remove parralax from Serpulo and make Erekir parralax.
Serpulo air units are very fast, parralax just throws them behind the defence. 
Erekir air units are much slower. Also, Erekir air units have big range, so parralax will be very useful turret (for example, we can use it with diffuse)

**Comment by Uitommyaakod** [comment]
приложение гавно, требую срочного удаления

**Comment by Uitommyaakod** [comment]
ав
ап
ыв

выр
выр
ыв
р

**Comment by IlSashalI** [comment]
Авапыв вырвырывр?
