### ISSUE TITLE
Falling on tall things

### ISSUE THREAD

**Issue by omgaXD** [Anuken/Mindustry-Suggestions#417]
There is a feature, when destroyed ships are falling to land and exploding, but when they fall onto rocks (that are taller than the ground), or into the "black zone", they hide and don't explode

Would be nice if they would fall on them faster, so if falling onto normal ground is around second, falling onto the rocks would be 0.5 sec or something like that. That would add realism to this nice feature

**Comment by SupremeTurtle** [comment]
My eyes are burning, why did you have everything in bold..

**Comment by omgaXD** [comment]
> My eyes are burning, why did you have everything in bold..

Sorry, not anymore.
