### ISSUE TITLE
Add a new world processor instruction that would allow you to drawflush to a player's screen.

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4170]
### Describe the content or mechanics you are proposing.

Add a world processor instruction that would let us flush drawn graphics to the player's screen rather than having to use displays.

I'd imagine this instruction would probably allow you to flush individually to each player to allow for more flexibility.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be really cool, and useful, to have an instruction in the world processors that would allow us to draw stuff to the screen, it could be used for custom HUD, displaying info to the player, or even just adding cool effects to your maps. Currently the only spot to keep information on screen for the player is the mission bar, but it's limited, and some people like to keep the default mission timer there.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheEt1234** [comment]
just use gorodmi's image to text
