### ISSUE TITLE
"Liquid" vs. "Fluid"

### ISSUE THREAD

**Issue by Stone-Dog-Millionaire** [Anuken/Mindustry-Suggestions#4171]
### Describe what you would like changed, and why.

There are some buildables containing the word "liquid," such as **Reinforced Liquid Junction**, **Reinforced Liquid Router**, **Reinforced Liquid Container**, and **Reinforced Liquid Tank**, in the new Erekir campaign.  These can also be used to store **Hydrogen** and **Ozone**, which are not liquids.  I almost didn't even try to put gases in the "liquid" storage, since the name implies that they are intended for liquids only.

### Describe the changes you want to propose. Include possible alternatives.

Therefore, my suggestion is that for anything that can handle gases as well as liquids, the word **Liquid** in the name be replaced with **Fluid**, since the proposed term includes both liquids and gases in its meaning.  _Satisfactory_ uses the term **Fluid** for example, since they also have a shared set of buildables for handling gases and liquids.

As for possible alternatives, I suppose you could make separate buildables for handling gases and liquids, respectively, but I think the mechanics make much sense the way they are now, so it's mostly a terminology fix.  There may be a more subtle workaround terminologically—"conduit" is perfectly ambiguous, for example—but I haven't thought of one and "fluid" seems to solve everything nicely.

**Comment by nilederg** [comment]
Mild pedantry, but easy fix I would think.
Simple search and replace?

**Comment by itcannotbe** [comment]
Might be more helpful to change erekir conduits to fluids, since people won't be expecting to pass through gasses through a liquid conduit.

As for the change, it's easy, except for the part that most translations would have to accomodate this change as well.
