### ISSUE TITLE
Turrets as radar are too powerful

### ISSUE THREAD

**Issue by nilederg** [Anuken/Mindustry-Suggestions#4172]
### Describe what you would like changed, and why.

Currently, in fog of war games, the limited knowledge in the beginning of a map adds a layer of depth to the game, forcing players to be more cautious and devote units to scouting tasks. However, this depth is lost entirely as soon as the team gets the scathe turret, because that turret, with its insanely large radar, is able to simply scan the entire map, and without even an energy cost.

Turrets should lose the internal radar entirely, and this should be made up for with higher range radars, all of which will cost energy, and some of which will cost hydrogen.

### Describe the changes you want to propose. Include possible alternatives.

- Remove turret radar entirely
- Make turrets fire based only on what is in the moment being scanned by radars (what the team can see)
- Add new, higher range radars

If this is accepted, I will try to the best of my ability to implement the change myself.

**Comment by nilederg** [comment]
I'd like to clarify that I don't think any of the new radars should have range as large as the current scathe radar range.

**Comment by BloodRaven0** [comment]
Aww, but I love map hacking with Scathes 😅

It is not a bad suggestion, but I think turrets should still have some view distance (not as much as their max range, but say 60-70% of it, excluding the scathe, which should have as much as a diffuse for example). This is because  the moment the enemy takes out your radar and you don't have any units around for vision, your entire defense will become useless.

Also radars should be buffed a bit, currently it is almost better to build any unpowered turret that won't consume power either. So more range and perhaps less power usage for radars would be sweet. A 2x2 radar that has like 70% of the view distance of the current Scathe, but consumes like 200 power would be awesome too, but make it cost carbide, so no early game maphacks.

**Comment by akhial** [comment]
Problem is fog of war can be disabled client side...

**Comment by OnyxFinger** [comment]
Fun fact : You need to get up to carbide to place a scathe.
Just saying, you're gonna need ways to get new vision for the earlier parts of the game, and towers are more expensive than units/radars then (scathe still is but has massive reach to it's not useless)

**Comment by nilederg** [comment]
> Aww, but I love map hacking with Scathes 😅
> 
> It is not a bad suggestion, but I think turrets should still have some view distance (not as much as their max range, but say 60-70% of it, excluding the scathe, which should have as much as a diffuse for example). This is because the moment the enemy takes out your radar and you don't have any units around for vision, your entire defense will become useless.
> 
> Also radars should be buffed a bit, currently it is almost better to build any unpowered turret that won't consume power either. So more range and perhaps less power usage for radars would be sweet. A 2x2 radar that has like 70% of the view distance of the current Scathe, but consumes like 200 power would be awesome too, but make it cost carbide, so no early game maphacks.

I don't think unpowered turrets should have any radar whatsoever. Powered turrets can have radar, but none more powerful than the basic 1x1 radar, and most should be far less. I want to make radar an essential, integrated part of FOW defense.

I was thinking, 3 tiers of radar. The original 1x1 radar, a 2x2 radar that uses more power and a small amount of some fluid, and a 3x3 radar that uses lots of fluid (possibly multiple), and lots of power

Currently, 1x1 radar has a range of 43 and is at silicon tier

In a possible revised system:
1x1 radar would have a range of 35 and be at silicon tier, with an input of 0.5 hydrogen/sec boosting to range 45
- Range 35
- Tier silicon
- No cost
- 5 water/sec boost
- Range boosts by +10
2x2 radar would have a range of 68.5 and be at surge or thorium tier and accept an input of 
- Range 50
- Tier surge or thorium
- Cost 2 hydrogen/sec 
- 5 nitrogen/sec boost
- Range boosts by +20
3x3 radar would have a range of 100 and be at carbide tier
- Range 100
- Tier carbide
- Cost 20 heat/s, base range scaling accordingly
- 0.5 phase/sec boost
- Range boosts by +20

Just an idea, would love feedback on it of course.

**Comment by BloodRaven0** [comment]
But most turrets don't use power, so how can they be "unpowered"? If they don't have ammo in them? Then couldn't the player manually transport some ammo in them an still use them as radars?

I think 3 tiers are too many. 2 will be better in my opinion.
Boosting the 1x1 with 5/s water is a neat idea though. I think it should also have a drastically lower power cost, so people don't just build them to scout and deconstruct them immediately afterwards (the only way I used radars, lol) - something like 10-15 max (they're currently at 36 or something ridiculous like that - that's 1/5th of a turbine condenser, which is huge in the early game)

The hydrogen cost for the 2x2 radar is appropriate, because it would make sense for forward outposts - Vent into Electrolyzer, Ozone into unit repair tower, Hydrogen into radar.
However, the 3x3 requiring heat is kinda no-no for me, especially such a huge amount of heat. Note that 3 heat costs 100 power and electric heaters are the only convenient thing you can use on the front lines (unless you have convenient vents and slag nearby). So 20 heat will use (in addition to a LOT of space) 700 power. This is ridiculous for a radar. And boosting (and/or heating) it with Phase Fabric is out of the question when it's not in your base. Also you say Scathe is overpowered, but it's got 126.5 tiles view distance, which is pretty close to the boosted version of your 3x3 radar.

Also, there are actually 3 "resource tiers" - Beryllium/Graphite is the first (and you can make Silicon with them); Tungsten tier (which gives access to Oxide and Surge Alloy); and Thorium tier (which unlocks Carbide and Phase Fabric).

So my suggestion looks like this
1x1 Radar - Silicon tier - 12 power - 40 tiles - 5/s water boost +10 tiles = 50 tiles
2x2 Radar - Tungsten tier - 35 power + 3/s hydrogen - 60 tiles -  4/s nitrogen boost + 20 tiles = 80 tiles
(the 4/s nitrogen requires 6 heat, equivalent to an extra 200 power)

**Comment by IxGamerXL** [comment]
I think having turrets only capable of targeting what it's team has uncovered should be good for a change. That, or the range would be bottle-necked in the directions being covered in fog, so if a turret were trying to find a target from north but there is a fairly large amount of fog there, the turret can only look several tiles north instead of what it normally could target from.

**Comment by nilederg** [comment]
Preface: I messed up
1x1 radar has a range of 33. I will adjust my recommended radar stats + adjustments from your advice, below.


> But most turrets don't use power, so how can they be "unpowered"? If they don't have ammo in them? Then couldn't the player manually transport some ammo in them an still use them as radars?

By unpowered, I mean any turret that does not use power.


> I think 3 tiers are too many. 2 will be better in my opinion. Boosting the 1x1 with 5/s water is a neat idea though. I think it should also have a drastically lower power cost, so people don't just build them to scout and deconstruct them immediately afterwards (the only way I used radars, lol) - something like 10-15 max (they're currently at 36 or something ridiculous like that - that's 1/5th of a turbine condenser, which is huge in the early game)

I think 3 tiers are necessary, to have a high tier radar capable of partially taking the place of scathe as a long range radar, a mid tier radar for allowing turrets in pre-thorium defense to work properly, and of course the low tier radar we already have.


> The hydrogen cost for the 2x2 radar is appropriate, because it would make sense for forward outposts - Vent into Electrolyzer, Ozone into unit repair tower, Hydrogen into radar. However, the 3x3 requiring heat is kinda no-no for me, especially such a huge amount of heat. Note that 3 heat costs 100 power and electric heaters are the only convenient thing you can use on the front lines (unless you have convenient vents and slag nearby). So 20 heat will use 700 power. This is ridiculous for a radar. And boosting (and/or heating) it with Phase Fabric is out of the question when it's not in your base. Also you say Scathe is overpowered, but it's got 126.5 tiles view distance, which is pretty close to the boosted version of your 3x3 radar.

I don't intend the 3x3 radar to be used on frontlines. In fact, I made it quite clunky specifically to make it hard to incorporate into a defense. I want to encourage using just a few of them, placed further back, to still reach out to the defense, but out of harm's way.


> Also, there are actually 3 "resource tiers" - Beryllium/Graphite is the first (and you can make Silicon with them); Tungsten tier (which gives access to Oxide and Surge Alloy); and Thorium tier (which unlocks Carbide and Phase Fabric).

I was using 'tier' to indicate all resources, ranked by standard order of progression.
Although, my 'tiers' are easily translated as the end of each resource tier;
1x1's most advanced ingredient is silicon (highest tech item in the beryl & graph tier)
2x2's most advanced ingredient is surge (highest tech item in the tungst tier)
3x3's most advanced ingredient is carbide (highest tech item in the thorium tier)


> So my suggestion looks like this 1x1 Radar - Silicon tier - 12 power - 40 tiles - 5/s water boost +10 tiles = 50 tiles 2x2 Radar - Tungsten tier - 35 power + 3/s hydrogen - 60 tiles - 4/s nitrogen boost + 20 tiles = 80 tiles (the 4/s nitrogen requires 6 heat, equivalent to an extra 200 power)

I think the 1x1 here is too powerful; effectively negating the need for unit patrol in earlygame.
The 2x2 radar should be more expensive and be a higher tier, considering its huge 80 tile range.

In my 3-tiered system, 1x1 radar is nerfed mildly in range but buffed in lower power use to encourage unit patrolling & upgrading to 2x2 without launching power usage through the roof. It would also have slightly lower build cost than current radar.


I will put my own (revised) ideas below

1x1 radar - Silicon
- Base range: 25
- Tier: Beryl & Graph
- Power: 15/s
- Boost range: 35
- Boost cost: 5 water/s

2x2 radar - Surge
- Base range: 45
- Tier: Tungsten
- Power: 60/s
- Cost: 5 water/s
- Boost range: 65
- Boost cost: 10 hydrogen/s

3x3 radar - Carbide
- Base range: 70
- Tier: Thorium
- Power: 120/s
- Cost: 8 heat/s, 8 hydrogen/s
  - Range scales proportionally to heat input
- Boost range: 90
- Boost cost: 10 nitrogen/s

The carbide radar, you might see, is quite expensive to run. This was done because by the point a player reaches carbide, they can fairly easily afford all of these things, and I want building this to carry some weight in order to prevent spamming on frontlines.

Also, I would like to reiterate that I am not asking for this to be implemented; I am asking for permission to implement it myself.

**Comment by itcannotbe** [comment]
What if turrets would update the team view just every X seconds.

While radars and non core units would still be up to date.

**Comment by GleB2k19** [comment]
Still op

**Comment by Sector171** [comment]
> Remove turret radar entirely

This is very bad idea, not only the turrets, but also all buildings should have a radar(at least one tile) vary from building to another, and this radar should be good for turrets, your base area should be visible well without any radar, radar is an extra tool to give you some advantage.

> Make turrets fire based only on what is in the moment being scanned by radars (what the team can see)

Ha, apparently you didn't think well, now with the above point what will happen if the radar got destroyed? or no power or... All the frontline turrets will be useless, having the attack and watching, doing nothing?? 0 sense or maybe I didn't understand your point well.

> Add new, higher range radars

That's ok, but as mentioned here, scathes radar already nerfed, scathe requires carbide. Is it really needed to make this, don't know. 

But if you asked me, the advanced radar should give the player the chance to "spy" (removing fow) from any spot(few tiles only) on the map for specific period (few seconds) and this feature need time to be active again after using(periodically recharge).

Also another annoying issue is, in many fow games the units or turrets that attack your units or building becomes visible (makes sense) for temporary time period(1-2 s)(and thus subject to have attack if in range), this not applied yet in mindustry. I hope to see that.

**Comment by nilederg** [comment]
> > Remove turret radar entirely
> 
> This is very bad idea, not only the turrets, but also all buildings should have a radar(at least one tile) vary from building to another, and this radar should be good for turrets, your base area should be visible well without any radar, radar is an extra tool to give you some advantage.

Radar is not an extra tool, it is essential to expand the base past the view of core radar.
Factories do not have radar. Transport does not have radar.
Visibility as a game mechanic in a **resource management game** is meant to be an additional resource to manage, and making the game hand-feed the player all the visibility they need would make this mechanic boring and, essentially, worthless.


> > Make turrets fire based only on what is in the moment being scanned by radars (what the team can see)
> 
> Ha, apparently you didn't think well, now with the above point what will happen if the radar got destroyed? or no power or... All the frontline turrets will be useless, having the attack and watching, doing nothing?? 0 sense or maybe I didn't understand your point well.

I did think it through, and a destroyed radar will only make a turret unusable in a badly designed defense. A build tower could be placed to rebuild the radar, a second radar could be placed for backup, a higher range radar could be placed behind as backup, etc.
If the enemy destroys all radars that cover the defense area, then the player has not built their defense well.
If power goes down and the turrets can no longer see, then the player has not built their energy system well. Et cetera.


> > Add new, higher range radars
> 
> That's ok, but as mentioned here, scathes radar already nerfed, scathe requires carbide. Is it really needed to make this, don't know.

Scathes are not nerfed nearly enough, and their range is still more than excessive enough to be in the realm of complete map cheese,


> But if you asked me, the advanced radar should give the player the chance to "spy" (removing fow) from any spot(few tiles only) on the map for specific period (few seconds) and this feature need time to be active again after using(periodically recharge).

I actually do quite like the idea of a 'targeted radar', and would happily explore the concept further, assuming Anuke ever notices this thread. Thanks for this.


> Also another annoying issue is, in many fow games the units or turrets that attack your units or building becomes visible (makes sense) for temporary time period(1-2 s)(and thus subject to have attack if in range), this not applied yet in mindustry. I hope to see that.

I don't entirely understand this point. Do you mean that the units that maintained radar in that area were killed? In that case, this is an intended feature. Although, I get the feeling that isn't what you're talking about. Please respond with clarification.

**Comment by nilederg** [comment]
> What if turrets would update the team view just every X seconds.
> 
> While radars and non core units would still be up to date.

This can only be implemented in the FOW system by updating the 'discovered but not currently seen' state, and turrets in the proposed system here would not fire at units in that state.
If you mean that they would update the team view every X seconds but the turrets themselves would see everything and shoot at units as they please, then it partially negates the entire point of this, as players could see where units they shouldn't be able to see are simply by viewing the turret's firing direction.

**Comment by Sector171** [comment]
> Radar is not an extra tool

It is, I rarely use it, and temporarily when I have no unit or so. In the base I depend on units and turrets and core radar.

> Factories do not have radar

I know, but some building have 1 tile radar(like fabricator) and some more about 3 or so like payload loader..etc, I am saying my opinion and what should be, all building (except normal walls and belts and so) should have at least 1 tile radar.
The good turrets radar that match its range(except for scathe) is a must.  Removing the good turrets radar has no sense at all, and will make the game as hell and super boring.

> I don't entirely understand this point

Sorry it is my fault since it is not related to radar, but one of fow mechanic that I like and see it makes since, but I mentioned to it here.

**Comment by Sector171** [comment]
> assuming Anuke ever notices this thread

I don't think he is, he is not even fixing the bugs reports so often he is taking a rest after V7 release

**Comment by nilederg** [comment]
> > Radar is not an extra tool
> 
> It is, I rarely use it, and temporarily when I have no unit or so. In the base I depend on units and turrets and core radar.

Is your point that because you use turrets for radar, we can't fix a glaring issue with the fog of war system which will force you to place all of 3 radars in your base? Radar is cheap, I don't see the validity of your point.

> > Factories do not have radar
> 
> I know, but some building have 1 tile radar(like fabricator) and some more about 3 or so like payload loader..etc, I am saying my opinion and what should be, all building (except normal walls and belts and so) should have at least 1 tile radar. The good turrets radar that match its range(except for scathe) is a must. Removing the good turrets radar has no sense at all, and will make the game as hell and super boring.

My main point in removing radar on turrets is that said radar is always active. An unpowered afflict still sees everything.
Additionally, I conflict with your idea that adding the requirement to incorporate radar systems into a defense is boring. I believe it would be quite the opposite. The requirement to manage what turrets can and cannot see would add another layer to the game and spice up defensive designing. Overall the game would become more interesting with this implemented.

**Comment by itcannotbe** [comment]
> > What if turrets would update the team view just every X seconds.
> > While radars and non core units would still be up to date.
> 
> This can only be implemented in the FOW system by updating the 'discovered but not currently seen' state, and turrets in the proposed system here would not fire at units in that state. If you mean that they would update the team view every X seconds but the turrets themselves would see everything and shoot at units as they please, then it partially negates the entire point of this, as players could see where units they shouldn't be able to see are simply by viewing the turret's firing direction.

What I mean is that they update what they player sees, it will still be uncovered but not updated in between "radar pulses"

Basically turrets can still shoot what they have already saw.

**Comment by GleB2k19** [comment]
Tbf my Opinion on this is to just cut down the range of FCR (Fire Control Radar) On turrets like Scathe, Titan, and others. Just the artillery turrets because i highly suspect other turrets have FCR integrated. For artillery turrets instead of adding "more long range radars" how about we use units. A
After all this would add extra layer of dynamic battles instead of "trench warfare"

**Comment by GleB2k19** [comment]
And making more tiers of radars would extend the "trench warfare"

**Comment by nilederg** [comment]
> Tbf my Opinion on this is to just cut down the range of FCR (Fire Control Radar) On turrets like Scathe, Titan, and others. Just the artillery turrets because i highly suspect other turrets have FCR integrated. For artillery turrets instead of adding "more long range radars" how about we use units. A After all this would add extra layer of dynamic battles instead of "trench warfare"

I don't think relying on units is a good idea; having to keep units in front of defense would be torturous to maintain, and long range radar is much easier as it can be rebuilt in the same location (also i want to reduce the radar range of units like collaris as well, though i dont care about that as much as scathe)
Also, I don't want any radar on any building that is unpowered. It makes the actual radars in game obsolete.

**Comment by nilederg** [comment]
> And making more tiers of radars would extend the "trench warfare"

How so?

**Comment by GleB2k19** [comment]
> > Tbf my Opinion on this is to just cut down the range of FCR (Fire Control Radar) On turrets like Scathe, Titan, and others. Just the artillery turrets because i highly suspect other turrets have FCR integrated. For artillery turrets instead of adding "more long range radars" how about we use units. A After all this would add extra layer of dynamic battles instead of "trench warfare"
> 
> I don't think relying on units is a good idea; having to keep units in front of defense would be torturous to maintain, and long range radar is much easier as it can be rebuilt in the same location (also i want to reduce the radar range of units like collaris as well, though i dont care about that as much as scathe) Also, I don't want any radar on any building that is unpowered. It makes the actual radars in game obsolete.

I only meant artillery turrets not every turret. Small defense ones will still have radar.



> > And making more tiers of radars would extend the "trench warfare"
> 
> How so?

Because you will still sit in the base and watch t3 radars spot stuff for scathes

**Comment by GleB2k19** [comment]
And wait until you have enough units for assault

**Comment by GleB2k19** [comment]
Thats basically what already happens

**Comment by GleB2k19** [comment]
Its only my view of things tho

**Comment by nilederg** [comment]
> > > Tbf my Opinion on this is to just cut down the range of FCR (Fire Control Radar) On turrets like Scathe, Titan, and others. Just the artillery turrets because i highly suspect other turrets have FCR integrated. For artillery turrets instead of adding "more long range radars" how about we use units. A After all this would add extra layer of dynamic battles instead of "trench warfare"
> > 
> > I don't think relying on units is a good idea; having to keep units in front of defense would be torturous to maintain, and long range radar is much easier as it can be rebuilt in the same location (also i want to reduce the radar range of units like collaris as well, though i dont care about that as much as scathe) Also, I don't want any radar on any building that is unpowered. It makes the actual radars in game obsolete.
> 
> I only meant artillery turrets not every turret. Small defense ones will still have radar.

No turrets should have radar built in, aside from powered turrets, which should have a small radar (possibly equivalent to the 1x1 radar) built in to them. It doesn't make any sense for an unpowered turret to have radar. Maintaining map intelligence over time should require a consistent resource investment over time, not just a one-time payment.

> > > And making more tiers of radars would extend the "trench warfare"
> > 
> > How so?
> 
> Because you will still sit in the base and watch t3 radars spot stuff for scathes
> And wait until you have enough units for assault

T3 radars will have far less range than scathes, and thus, if anything this will reduce trench warfare.
Scathes will not be able to shoot as far into no man's land, and this will necessitate using units to search out a target.
This will add to dynamic play. (Also, scathes are terrible against buildings anyway. They can be countered with a single regen projector.)

**Comment by GleB2k19** [comment]
How about ability for all turrets to be powered (like an optional booster) but the radar will be directional, however less power cost

**Comment by GleB2k19** [comment]
Like 40 to 60 degrees

**Comment by itcannotbe** [comment]
That would be somehow hard to implement since most likely the dev doesn't want the block to be configurable using an ui.

**Comment by GleB2k19** [comment]
Well i dont think that making all turrets conducting a great idea. And yes directional radars are pain. However there is a huge shadow of doubt that anuke will add new blocks like that. I highly suspect that all that will happen is radar nerf and well #4184 will become real

**Comment by nilederg** [comment]
Well, I would hope not. I am confident this new radar system would add considerable depth to the game.

**Comment by GleB2k19** [comment]
Also anuke wont read github for a while so we better keep the thread alive

**Comment by nilederg** [comment]
What more is there to say? I do check the thread daily though, so if anyone wants to add anything to the discussion I'll be there to respond shortly.

**Comment by nilederg** [comment]
Speaking of keeping the thread alive, a b c d e f g h i j k l m n o p q r s t u v w x y z.
