### ISSUE TITLE
Visuals for nuclear attack

### ISSUE THREAD

**Issue by PriyanthaFer** [Anuken/Mindustry-Suggestions#4175]
### Describe the content or mechanics you are proposing.

Make a visual when nuclear attacked.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently when attacked by nuclear launch, everything within radius just disappears. Make a visual when that happens. Maybe, a red aim mark randomly move towards the center of attck range, make a 'target selected' animation. Then after a small pause, a bright flash followed by a wave that destroys everything within the range. The wave can be similar to the one that plays when starting the sector accompanied with a particle effect. Just my idea, just build it in a way it suits.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by miner-sd** [comment]
i think a 3 ish tile wide red dot that slowly shrinks to a small point (like a laser targeting thing rapidly approaching) followed by a blast effect similar to that of a scathe (except very bright and big) followed by a large outward moving ring of smoke would probably look good
