### ISSUE TITLE
More comprehensive tutorial

### ISSUE THREAD

**Issue by FriederHannenheim** [Anuken/Mindustry-Suggestions#4178]
### Describe what you would like changed, and why.

I want the tutorial to explain to the user how to unlock things on the tech tree. I just picked up Mindustry yesterday and I do not understand how to unlock things. I have completed the tutorial and captured 3 sectors on Serpulo: Ground Zero, Frozen Forest and 175.
My Tech Tree looks like this:
![Screenshot_20221129-101849_Mindustry](https://user-images.githubusercontent.com/41985738/204489637-5b7064b3-eff5-4c67-9fd0-13f147f2915d.png)
When clicking the locked items they show this:
![Screenshot_20221129-101901_Mindustry](https://user-images.githubusercontent.com/41985738/204489765-1a945190-3e2b-437f-807c-d7920511d061.png)

Now I as a new user don't know what to do. I read a bit on the internet but there isn't an obvious description on what to do now.

### Describe the changes you want to propose. Include possible alternatives.

I want a tutorial explaining what to do after capturing the first sector.

**Comment by Bottinator22** [comment]
You've researched everything you can already
Launch to a new sector

**Comment by FriederHannenheim** [comment]
By watching a let's play I found out that I needed to mine coal to research new things. But the let's play also was in 6.0 and there the research objectives showed what needed to be done to unlock them. Maybe this should be brought back
