### ISSUE TITLE
Unite the 3 Assemblers into 1 Building

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4179]
### Describe the content or mechanics you are proposing.

The "Tank Assembler", "Mech Assembler" and "Ship Assembler" should just be replaced by a universal "Assembler" building, that has a selection menu that allows the player to select what kind of unit it would build. Depending on the selection it will recolor itself appropriately (same graphics as the current 3 assemblers), otherwise it would just be a generic yellow color like the Multiplicative Reconstructor when nothing is selected.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, there are way too many buildings in the "Units" tab, and this will reduce them by 2. Furthermore, it doesn't make sense to have 3 separate buildings for this, when 1 will do just fine, just like the Multiplicative Reconstructor is universal for all 3 unit trees.
This will also make it possible to produce T4 units, even when you have a module upgrade attached, if you only want to use it for input or want to switch a T5 factory to produce T4 units once you've maxed them out.

You would only be able to select units you have unlocked in the tech tree, so it won't be possible to make T4 ships and mechs in earlier-than-intended levels. Also the unit selection will be saved when a schematic is saved.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RealYeet** [comment]
Maybe the reconstructor instead, make it so that the resource you need to input becomes different depending what unit is inside the reconstructor and the unit tab is less cluttered.

**Comment by BloodRaven0** [comment]
True, the same treatment could be applied to the Refabricators. Great idea!
It could also be applied to the Fabricators as well, but I think they're better off separate.

**Comment by Sector171** [comment]
I don't think it is that easy.
Why do think he didn't do that, even so similar unified block existed in Serpulo, and even in Erekir (prime refabricator) ?? I don't know but I can predict
You see "basic assembler module"? In info , function, it says "Module Tier1", this means that in the future there could be another modules tier2, tier3...
This mean new versions of each t5. I mean this opens the door for that. Making what you suggest may break this.
