### ISSUE TITLE
About "overflow door + classifier"

### ISSUE THREAD

**Issue by IFRFSX** [Anuken/Mindustry-Suggestions#418]
The latest beta version, the "overflow door + classifier" fast conveyor belt
Fix it as a BUG
But I like this conveyor belt
I hope you can add a switch (of course it is closed by default)
So that my friends and I can continue to do this

**Comment by itcannotbe** [comment]
1. Use the template.
2. It is not a conveyor belt.
3. The reasom it was fixed is because it was a bug in the first place.
4. It's not even a beta release yet.

**Comment by ritzip** [comment]
It has been removed completely now.

**Comment by Anuken** [comment]
No. This is not coming back.
