### ISSUE TITLE
Re-Enforced Logic Processor and/or Canvas Processor

### ISSUE THREAD

**Issue by JanluOfficial** [Anuken/Mindustry-Suggestions#4180]
### Describe the content or mechanics you are proposing.

The Re-Enforced Logic Processor basically explains itself, a Logic Processor for Erekir, made with Carbide, Beryllium and Thorium

The Canvas Processor would work like the logic processor but only for modifying the canvas. It would be able to do 12 frames a second or 12 commands a second on a single canvas. Here's some basics:

- Each Frame would be drawn like on a normal canvas
- theres a menu to see all frames and add/remove them
- The Connected Canvas name needs to be manually enteread after linked (like processors)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The Re-Enforced Logic Processor will allow for new machines to be made in Erekir.

The Canvas Processor would add a whole new Group of creative people to the game. Many Animators may start playing Mindustry just for it, others may use it in combination with the Re-Enforced Logic Processor (Or in Mixed-Tech) to make fancy danger, power, warning, status and many more Indicators.

# It would bring a whole new community to the game and help the existing community bringing their creativity to life

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Did you know....

### THE DEV WANTED PLAYER PROGRAMMABLE LOGIC PUT THE GAME.

Now you're suggesting to add them to Erekir as well?

**Comment by IxGamerXL** [comment]
Logic would be nice to have in the second planet in the universe of Mindustry, and the only reason why Logic isn't supported in this planet is because it would make players too dependent on Logic yet again.

It would be better if Logic in this planet is limited to only cosmetic cases, such as drawing to Logic Displays, writing to Logic Memory Banks, etc. Using Radar or Unit control for example wouldn't function at all.

Logic's primary use inside of non-sandbox gameplay has been to make the game trivial, so disabling Logic's more impactful functionality would likely make having Logic alright.

**Comment by itcannotbe** [comment]
Won't adding limited logic functionality into erekir would just frustrate people expecting full logic be available?

**Comment by IxGamerXL** [comment]
> Won't adding limited logic functionality into erekir would just frustrate people expecting full logic be available?
> 
> A canvas processor is a lame excuse for I want a programmable logic display on erekir, which most of the time are useless,gameplay wise, even in serpulo.

Which is why simply bottle-necking existing processors is at least a more reasonable attempt. Also, limiting logic functionality can also have a warning rigged to show when you open the Logic category or attempt to build a schematic containing logic.

**Comment by overdramaticpanromantic** [comment]
Bad idea overall. Canvas processor is OK, but a reinforced logic processor will just make doing ridiculous things possible. Anuke themself has said that player-programmable logic should be removed, they just have not done it yet as it would enrage designers and logic makers.

**Comment by overdramaticpanromantic** [comment]
For example, block control, unit control, unit radar, and unit locate are all fucking busted. How would they make sure they don't check buildings outside your discovered area (in the fog of war)? How would unit control work exactly? Could people just automate entire sectors? It's a real-time strategy, not plop down a factory and processor and win.
