### ISSUE TITLE
Make hovering units (Eludes) able to go up and down cliffs

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4182]
### Describe the content or mechanics you are proposing.

Eludes should be able to drop down from and scale up cliffs, given that they're hovering units, not ground units. This will bring them closer to their flying brethren and increase their usefulness as scout units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I know cliffs aren't used very much in maps (I haven't seen even one in the Erekir Campaign), but they are very cool and should be used more, with more unit interactions.
I'm making a map that is making heavy use of cliffs and it would be awesome if players could use Eludes to scout and attack with, instead of relying only on the mech tree.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I thought hovering meant like hovercrafts not helicopters.

**Comment by BloodRaven0** [comment]
I'm pretty sure Eludes are hovercrafts, not helicopters...

**Comment by mrlegoboy** [comment]
while its easy to argue a hovercraft can't go up a cliff its much harder to argue that one can't go down a cliff
