### ISSUE TITLE
Removing/cutting down radar abilities for long range turrets

### ISSUE THREAD

**Issue by GleB2k19** [Anuken/Mindustry-Suggestions#4184]
### Describe the content or mechanics you are proposing.

Instead of long range turrets (e.g. scathe) having a radar range as much as entire map (160 blocks) cut it down to something like 20, encouraging players to scout the targets and use radars. Not sure if its a balancing thing or a feature so it will be a feature 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Will make maps a bit more interesting instead of just placing a scathe and seeing entire enemy base

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
When you realize that someone already suggested this just recently...

#4172

**Comment by GleB2k19** [comment]
Should i close it?

**Comment by GleB2k19** [comment]
Also my suggestion implies using rts system more actively but #4172 isnt bad

**Comment by nilederg** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/4172

**Comment by nilederg** [comment]
I encourage you to participate in the https://github.com/Anuken/Mindustry-Suggestions/issues/4172 thread, and to close this thread.

**Comment by GleB2k19** [comment]
Alright
