### ISSUE TITLE
Upgrade button feature

### ISSUE THREAD

**Issue by GonnaTried** [Anuken/Mindustry-Suggestions#4185]
### Describe the content or mechanics you are proposing.

I world like to see some hotkey that can upgrade block like : Conveyor, Drill, Pump, Conduit and Wall.
for example ( I want to upgrade Mechanical Drill to Pneumatic Drill, I just left click on Pneumatic Drill blueprint and press and hold G or whatever key you want to bind then it it show column like F copy or B rebuild then build and upgrade.) 
![Screenshot (21)](https://user-images.githubusercontent.com/119501348/204799349-eeb4006e-7ed4-4cae-bf91-b7504d8edb85.png)
![Screenshot (27)](https://user-images.githubusercontent.com/119501348/204799361-01236e82-bc4f-4400-bdc8-50def1c52df4.png)
And the same as conveyor and other

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If this upgrade feature come out it will make gameplay more easier and enjoyable more then before imagine you play PVP how fast you can upgrade your conveyor to titanium conveyor. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
So like a mass-upgrade feature?
