### ISSUE TITLE
Drop Mindustry for Xbox

### ISSUE THREAD

**Issue by LumpySkate6816** [Anuken/Mindustry-Suggestions#4187]
### Describe the content or mechanics you are proposing.

Pls develop Mindustry for Xbox and PlayStation!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

If the game appear on consoles you will sell more copys.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
1. "you will sell more 'copys'"
Mindustry might be paid on some places, like Steam, but all you need to get it for free on most platforms is to just go to its itch.io page
For another, porting to console is probably way more trouble than it's worth
2.
You want it on another platform? You can try porting it yourself, the game is open-source

**Comment by itcannotbe** [comment]
- [X]  I **DID NOT** check the Trello to make sure my suggestion isn't planned or implemented in a development version.

https://trello.com/c/QwPVvcQ6/

**Comment by Slotterleet** [comment]
Let's also talk about the non-existent controller support. Mindustry was NOT supposed to be played with a controller at all. If somehow you do connect the controller, well, good luck with the controls
