### ISSUE TITLE
convert radians to degrees and vice versa

### ISSUE THREAD

**Issue by imreallybadatnames** [Anuken/Mindustry-Suggestions#419]
**Describe the content or mechanics you are proposing.**
Just 2 math functions to the logic block: toDegrees and toRadians(they are called the same in java, e.g. Math.toDegrees and Math.toRadians)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will not be required to use math constants and several instructions to convert them.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Why do you need to use radians in the first place?

**Comment by imreallybadatnames** [comment]
So you can use the math functions with radians instead of multiplying degrees to some value to convert them to radians.

**Comment by Anuken** [comment]
None of the math functions use radians. `sin/cos/tan` take degrees, and `atan2` returns degrees.

**Comment by imreallybadatnames** [comment]
ok
issue can be closed
