### ISSUE TITLE
New Canvas block palette

### ISSUE THREAD

**Issue by Shidoengie** [Anuken/Mindustry-Suggestions#4191]
### Describe what you would like changed, and why.

The current canvas color palette is way too limiting, it only has 8 colors when 16 color palettes are more common and more versitile, but those 8 colors arent used wisely instead having 2 ramps of red and blue, when there could be more colors.

### Describe the changes you want to propose. Include possible alternatives.

I suggest increasing the canvas color palette to 16 colors, but if not possible replacing the current palette for DB-8 (https://lospec.com/palette-list/dawnbringers-8-color, https://pixeljoint.com/forum/forum_posts.asp?TID=26050) a rather more versitile color palette.

**Comment by GitHubUser-B** [comment]
I feel like this is a way to avoid players drawing inapropriate things because there isn't so much detail they can add to make it recognizable, but i think the low resolution already does that 🤔

**Comment by Shidoengie** [comment]
> I feel like this is a way to avoid players drawing inapropriate things because there isn't so much detail they can add to make it recognizable, but i think the low resolution already does that 🤔

There are still skin tones in the current palette if it did try to prevent that well then it failed completely.
This is just limiting creativity and what the community can achieve with the canvas block.

**Comment by Garen7** [comment]
@Shidoengie changing the colors available and number of colors available to the palette is very easy so I can just open a pull request for you. Changing the number of colors available breaks existing canvas schems but i dont see many schematics for that out there right now anyways

But can you give me the 16 color hex values that would be preferable? The current hex values are: 0x362944_ff, 0xc45d9f_ff, 0xe39aac_ff, 0xf0dab1_ff, 0x6461c2_ff, 0x2ba9b4_ff, 0x93d4b5_ff, 0xf0f6e8_ff

Do keep in mind a red overlay is applied because of erekir's weather but idk if changing the canvas color hexes just for the weather is something you should do anyways

**Comment by GitHubUser-B** [comment]
> > I feel like this is a way to avoid players drawing inapropriate things because there isn't so much detail they can add to make it recognizable, but i think the low resolution already does that 🤔
> 
> There are still skin tones in the current palette if it did try to prevent that well then it failed completely. This is just limiting creativity and what the community can achieve with the canvas block.

True, i wasn't supporting this design decision, it could also be available for serpulo as well

**Comment by Shidoengie** [comment]
> @Shidoengie changing the colors available and number of colors available to the palette is very easy so I can just open a pull request for you. Changing the number of colors available breaks existing canvas schems but i dont see many schematics for that out there right now anyways
> 
> But can you give me the 16 color hex values that would be preferable? The current hex values are: 0x362944_ff, 0xc45d9f_ff, 0xe39aac_ff, 0xf0dab1_ff, 0x6461c2_ff, 0x2ba9b4_ff, 0x93d4b5_ff, 0xf0f6e8_ff
> 
> Do keep in mind a red overlay is applied because of erekir's weather but idk if changing the canvas color hexes just for the weather is something you should do anyways
> 
> 
> 
> 
> 

000000
55415f
646964
d77355
508cd7
64b964
e6c86e
dcf5ff
i think these are it

**Comment by Garen7** [comment]
@Shidoengie nah I meant for a 16 color palette

**Comment by Shidoengie** [comment]
> @Shidoengie nah I meant for a 16 color palette

https://lospec.com/palette-list/dawnbringer-16 if you download the hex file it'll have what you need

**Comment by Shidoengie** [comment]
> @Shidoengie nah I meant for a 16 color palette

@Garen7 
140c1c
442434
30346d
4e4a4e
854c30
346524
d04648
757161
597dce
d27d2c
8595a1
6daa2c
d2aa99
6dc2ca
dad45e
deeed6
