### ISSUE TITLE
Undo, Redo and Surrender Buttons.

### ISSUE THREAD

**Issue by TheDeparted7** [Anuken/Mindustry-Suggestions#4193]
### Describe the content or mechanics you are proposing.

An Undo and Redo Button, These buttons would only appear when in the "drawing" mode, or the state when you are placing the proposed location and orientation of blocks. Clicking these buttons would undo that last proposed block. And Redo would redo an action. So you deleted a string of conveyors using the undo button, Redo would allow you to get them back. Each of these buttons would work one block at a time. 

And finally, a surrender button, this button would be located in the pause menu, and would instantly end the sector or map which you are on, after a short Warning/Confirmation screen that would say yes or no. This could also be configured different ways, to where only the host could surrender, surrender requests can b made, or a vote can be taken. Depending on the host.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There have been times, especially on mobile, in which I'll draw a line of conveyors too far. And either have to completely restart and or tap each conveyor to erase only what I want. If there was an undo button that would make this slightly more smooth it would really be helpful and keep the screen less full of hands. Same for Redo, incase you accidently deleted more than you wanted or changed your mind. 
A surrender button would also be helpful, to prevent long  a stalemate,and to keep players from getting stuck bored, or continuing on with trashy strategies or schematics. This would be especially useful, if for example neither you or the enemy can gain any ground, especially on Erekir, and to prevent you from having to wait long periods of time and or deconstruct large amounts of your base to allow for enemies to finally destroy all of your cores. Surrender would be a quality of life button. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by COALROCK8642** [comment]
Well, you will use schemes so connecting things won't be difficult.

**Comment by TheDeparted7** [comment]
Not always, especially when connecting things. Just a thought. Don't forget about the surrender button.
