### ISSUE TITLE
Make Heat Router only distribute heat to connected buildings.

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4195]
### Describe the content or mechanics you are proposing.

The heat router should only distribute heat to sides on which there is a heat-consuming building connected.

For example, if 2 of the 3 sides are used, it would split the incoming heat 50/50% to both sides, with the third unused side receiving no heat. 
If it's receiving 10 heat and the front side is occupied 3/3 tiles and the left side is occupied only 2/3 tiles, then the front will get 6 heat, and the left 4 heat, or in other words 2 heat per tile used.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The use of heat routers is currently very situational and clunky, due to the fact that it undiscriminatingly distributes the heat evenly to all 3 sides, no matter how many are actually used, wasting the heat from the unconnected tiles. This makes this building much less useful that it would otherwise be, and makes heat as a mechanic pretty clunky to set up, especially if you're trying to split heat evenly between two buildings (which is currently impossible).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
Absolutely agree. I would love to have exact heat distribution available for ratios that aren't 1:1,  1:1:1, 1:2, or some combination of those.

**Comment by nilederg** [comment]
To be able to even split heat 50/50 would be wonderful.

**Comment by itcannotbe** [comment]
> makes heat as a mechanic pretty clunky to set up.

Wasn't it intended to be this way?

**Comment by Jaeyun21** [comment]
Agreed

**Comment by Jaeyun21** [comment]
> 

No, it makes the heat recieved outputted into 3 seperate sides, even if 1 or 2 of the sides are being used
