### ISSUE TITLE
Make a normal modding guide!

### ISSUE THREAD

**Issue by Demiyanit** [Anuken/Mindustry-Suggestions#4196]
### Describe the content or mechanics you are proposing.

Or finish the existing guide on your wiki, please!!!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Stupid people like me would be able to make normal mods...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
https://github.com/Anuken/Mindustry

**Comment by Demiyanit** [comment]
> https://github.com/Anuken/Mindustry

?

**Comment by Demiyanit** [comment]
wait

**Comment by Demiyanit** [comment]
sh*t

**Comment by Demiyanit** [comment]
> > > https://github.com/Anuken/Mindustry
> > 
> > 
> > ?
> 
> It's called [RTFSC](https://www.google.com/search?q=rtfsc). It's a good read.
> 
> Though a [normal guide](https://mindustrygame.github.io/wiki/modding/1-modding/) exists, but it's limited to mainly HJSON modding.
> 
> If you're scripting, RTFSC.
im completly now to modding but i understand that hjson is limited so i wanted to know how to make java mods but there is no tutorial or guides for this.

**Comment by Slotterleet** [comment]
> im completly new to modding but i understand that hjson is limited so i wanted to know how to make java mods but there is no tutorial or guides for this.

As already mentioned above, for JS/Java modding, RTFSC.
