### ISSUE TITLE
Add T2 Of Scorch

### ISSUE THREAD

**Issue by irsyadsandriano** [Anuken/Mindustry-Suggestions#4198]
### Describe the content or mechanics you are proposing.

T2 Of Scorch (More powerful than original scorch, More bigger, and more resources that accepted to be ammo for the T2 Scorch)
If i suggest the name is Mercoch

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will be improve the gameplay. Might be good for Tower Defense-like game. And make the creativity is more wider. (Sorry for bad english)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
> This will be improve the gameplay

How exactly?

**Comment by Jaeyun21** [comment]
Scorch -> meltdown
