### ISSUE TITLE
Рельсовая пушка (рельсотрон)

### ISSUE THREAD

**Issue by beethowen** [Anuken/Mindustry-Suggestions#42]
Пушка стреляет сразу (моментально). 
Во время выстрела потребляет 
100 000 энергии моментально
Если энергии нехватает то она не стреляет. 
Если энергии для выстрела хватает то над ней горит лампочка как на кремнии
Урон 500 000
Дальность 50
Цели земля/воздух
Патроны на 1 выстрел 10 едениц ресурса
Время перезарядки
Медь 15 секунд
Свинец 15 секунд
Титан 10 секунд
Торий  10 секунд
Паластаний  6 сек.
Кинитический сплав. 4 секунды
Ускоритель на нее недействует
Фазовая ткань ускоряет на 1 секунду
Вода или криогенная жидкость не требуется

**Comment by beethowen** [comment]
Попадание 100% точное. Видимость выстрела. Как красный лазерный тонкий лучь который плавно затухает в течении секунды.

**Comment by kapzduke** [comment]
ты думаеш люди здесь говорят по русски

**Comment by kapzduke** [comment]
а еще турель слишком имбовая

**Comment by Anuken** [comment]
> ты думаеш люди здесь говорят по русски

~~I do~~

> Урон 500 000

This is far too overpowered.
