### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qlgd** [Anuken/Mindustry-Suggestions#420]
在打开卸载器菜单页面的情况下拆掉卸载器就会导致客户端崩溃
Removing the unload device while opening the unload device menu will cause the client to crash
![bug](https://user-images.githubusercontent.com/69980620/90798146-22d6b880-e344-11ea-822e-d4cf1895842a.PNG)
[crash-report-08_21_2020_00_18_41.txt](https://github.com/Anuken/Mindustry-Suggestions/files/5104220/crash-report-08_21_2020_00_18_41.txt)

**Comment by itcannotbe** [comment]
Wrong Repository.

**Comment by Colonizor48** [comment]
nice
