### ISSUE TITLE
Units should not stop when ordered to move ontop of a block they can't

### ISSUE THREAD

**Issue by BloodRaven0** [Anuken/Mindustry-Suggestions#4204]
### Describe the content or mechanics you are proposing.

When ordering a ground unit to go on top of a solid block, it should move to the closest possible open tile instead of stopping dead in its tracks.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The current behavior is really suboptimal for microing units and for general QoL.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Larofeticus** [comment]
Yes. 

Also, giving ground units an attack command on a target surrounded by solid blocks should result in the units doing _anything_ instead of _nothing_.
