### ISSUE TITLE
Formations / Battlegroups

### ISSUE THREAD

**Issue by TheDeparted7** [Anuken/Mindustry-Suggestions#4205]
### Describe the content or mechanics you are proposing.

Formations, Formations would work similar to the schematics tab, but would be for units. It would be a button, right next to the Command Button, it would be square and look sorta like a triangle. After selecting a group of units using the command tab. You could click the Formations button, to enter a sort of edit mode. It would show you all the current selected units, saved Formations, and a create and delete Formations button. It would also show formation options, which would cause certain formation to behave certain ways f the creator choose to do so. For example, move forward, move toward target, and retreat after target is destroyed. Etc. The Formations tab could also be used to create Battle Groups, which would allow you to control certain groups of units, from special tabs, from anywhere on the battlefield and as a whole unit. Similar to many RTS command systems. Especially Art of War 3. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think by adding Formations and Battlegroups, it will, not only impove the RTS aspect of the game, but add more strategy, customization and ease of use. Formations would allow for more coordinated attacks instead of blind often pointless rushes, and would prevent the current method for creating Formations, by individually moving each unit and repositioning them several times. Battlegroups would prevent you from having to travel across the map to command units, and would allow you to more easily control units in groups quicker.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by COALROCK8642** [comment]
Yeah reminds me of playing, before WW1 era, units standing like salvos waiting for order to kill,

Nope too complex. Just flank and see Napoleonic wars to learn how he manoeuvre.
