### ISSUE TITLE
Bring Back Mixed Maps

### ISSUE THREAD

**Issue by Daconus** [Anuken/Mindustry-Suggestions#4206]
### Describe what you would like changed, and why.

I don't see why people are so upset about mixed tech. If you don't like it, don't use it. I was making a map for a while about mixed tech, and then I went to click they <Any> button. I got the pop-up. I would like it back.

### Describe the changes you want to propose. Include possible alternatives.

Simply allow mixed tech to be used again.

**Comment by Jaeyun21** [comment]
Yes please

**Comment by COALROCK8642** [comment]
Let's just leave this to serpulo + erekir, PVPs

**Comment by MurkyVolcano** [comment]
I would love this as a map designer. Logic with extra payload stuff would be amazing.
