### ISSUE TITLE
Erekir unit type

### ISSUE THREAD

**Issue by Jaeyun21** [Anuken/Mindustry-Suggestions#4208]
### Describe the content or mechanics you are proposing.

Create a naval like unit tree for erekir

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Would make maps filled with slag have a better alternative then fragile air

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by kapzduke** [comment]
if you see the elude tree as "fragile", then use more shields until you find them acceptable. simple

**Comment by Jaeyun21** [comment]
Naval would still be a cool addition
