### ISSUE TITLE
(6.0) Routers and mass routers

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#421]
**Describe what you would like changed, and why.**
A normal router consts 3 copper, but a mass router is bigger, has the same function (but for units), and only costs 1 copper.

**Describe the changes you want to propose. Include possible alternatives.**
The mass router should cost at least 3 copper, but I think that a good cost for the mass router would be 9 copper. Also, mass conveyors could be 3 copper.

**Comment by Anuken** [comment]
The costs/names for "mass" blocks are just placeholder values right now.

**Comment by ILiekMelons** [comment]
mass route
