### ISSUE TITLE
Wild creatures that can be captured

### ISSUE THREAD

**Issue by Droid-Potato** [Anuken/Mindustry-Suggestions#4210]
### Describe the content or mechanics you are proposing.

I do understand that every game has it's limitations. I'm coming from games like Dwarf Fortress and Rimworld, and a cool addition to those are the addition of pets. Pets wouldn't suit the overall combat-appeal of Mindustry, probably. But the ability to capture wild creatures for use in game will surely add up a whole new door. Using creatures for extracting new types of resources (such as new liquids). Wild creatures will attack the base, while captured (tamed) ones will fight off invaders. Sounds cool?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Addition of creatures might not make a lot of sense for a factory based game. But if you consider Factorio, there are things called Biters, which are essentially creatures, just, untamable. If there are creatures that can be tamed (by using traps and all) will lure in people from Pokemon fanbases. Yeah. I don't know either what it has to do with a game like Mindustry, but at least, alien creatures, that wander around when not attacked might at least make the map a bit more beautiful overall. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Did someone aay add living creatures to a game where your units are mechanical?

**Comment by Breadyboi69** [comment]
New to mindustry;a brand new liquid:
_piss_

**Comment by Droid-Potato** [comment]
Ohh that was fast! I do understand it's quite weird. Everything is
mechanical here. But what about Alien creatures? That doesn't seem too
unreal if we consider games like Satisfactory. I agree it's bad to make
something similar to other games, but it wouldn't hurt if we introduce some
new additions those games don't, right? Take into consideration, the
following new additions the game could get:

• New resources that can be extracted from these alien-ic creatures

• An alternate form of attacking troops (Moving legs are a beauty)

• Creatures like birds that through cherry bombs on enemy territory

• Transportation (doesn't sound more effiecient than a conveyor belt, but
hey, they can defend themselves when enemies hit.

Now that I think about it, adding an elevated level of stealing and
resource thievery in multiplayer would be wuite awesome.

You may not like the idea of creatues, but I guess something similar, at
least, could be thought out from this.

Nevertheless, thanks for such a great game! I hope to see more updates
(after you're happy with the break. You surely need some good rest)

Regards,
Potato

**Comment by Jaeyun21** [comment]
What about a living spore animal?

**Comment by Droid-Potato** [comment]
> What about a living spore animal?

Sounds good!
