### ISSUE TITLE
Combustion Generator should not consum coal if energy is not used

### ISSUE THREAD

**Issue by Enomine88** [Anuken/Mindustry-Suggestions#4212]
### Describe what you would like changed, and why.

Hi,

Combustion Generator is consuming coal no matter if the energy is actually used.
So there is energy produced and disappears to nowhere.
This is a vialation against the first law of thermodynamics.
https://en.wikipedia.org/wiki/First_law_of_thermodynamics
Energy can't disappear.

See for example this module:

`bXNjaAF4nH3SS46bQBCA4aJfPCZDEgsl27mA97lArpBNlAWGlscSAxbgjCZnj+R09a8ssokl89FdVBUFyCeprLi5f4ny+ev83M9DHJ++xXWPl/Fyvs3npy/yMMZtWC/X/bLMIhKm/hSnTcz3H42EdbntcZVqWOaf8W1ZpdyGftet8pR9k+a6vMb1OC9jlG5YXk63TUsdz3GOa7+nHDveFrH9OkjYhmUdnuXjsFyvKem1n6bj1K/nmDr/kvwrOBSqEasry6YDTywQK3WV941msbK5QkrIm57NUjcN1Q2XGL1EKf/2KhQDDoKme72NXAry1T4d8sqBh0CsFKvJqabTGlWdF+F+11X6G4ZNa8nn2t4VNkcKquSVo4Cvmv8XuP/+p0igSHo+ekhX5HOxigELDjwEKHWWSvOUAgxYcOAhgBaXmjupeRU1T6vWfooDDwFyv4a30+hYigELDjwEKPVLeNB+SgEGLDjwECD1K+WdtlMKMGDBgYcA+gzlkSf/mL+yhAELDjwEyN9py3wt87XM1zJfy3wt87XM1+p8lbzXNKUAAxYceAiQ+tXyQfMUAw6CciB2IHYgdiDWEeuIdcQ6jf0BxxdJmQ==`

Energy is produced by the Combustion Generator, saved in Batterys for later and for the case of an attack it is directly connected to the Arcs-Turrets. While no enemy is there the arcs don't shoot but coal is consumed anyway.

### Describe the changes you want to propose. Include possible alternatives.

Consuming coal in Combustion Generators should stop if all batterys are full and no energy consuming thing is connected or is connected but is now not consuming energy.
If there is something connected, which is actually consuming energy but less then 60 energy / s (this is what a Combustion Generator is producing at a maximum) then the consuming of coal should be restricted.

Thanks - Enomine

**Comment by itcannotbe** [comment]
1. This is a game, not real life.
2. Generators do not care about the state of power storage devices.
3.
> So there is energy produced and disappears to nowhere.
This is a vialation against the first law of thermodynamics.
   a. That's not how spell that.
   b. You forgot heat energy is still energy. Since it's a combustion generator after all.

**Comment by IxGamerXL** [comment]
In a more general sense, any kind of power generator that doesn't need to be included in order to make the rest of the network should be disabled until it is needed.

This would definitely prevent unneeded use of potentially expensive materials, but might complicate things. Also could be seen as a way to make the game easier than normal.

**Comment by itcannotbe** [comment]
> In a more general sense, any kind of power generator that doesn't need to be included in order to make the rest of the network should be disabled until it is needed.
> 
> This would definitely prevent unneeded use of potentially expensive materials, but might complicate things. Also could be seen as a way to make the game easier than normal.

So how will the game know which generator to "turn off" and which one needs to keep running?

**Comment by Bottinator22** [comment]
There's also the fact that you absolutely do not want to turn off an Impact Reactor, since they take far too much to start back up

**Comment by Jaeyun21** [comment]
*logic*

**Comment by haltalt** [comment]
> > There's also the fact that you absolutely do not want to turn off an Impact Reactor, since they take far too much to start back up
> > Maybe not turning it off but restricted it (lower the output energy and therefore lower the consuming of resources).
> 
> If my reasoning because of real life and thermodynamics is not liked, this is still a feature request.
> 
> Main problem for me: If i have 10 Combustion Generator in a row then all coal is consumed. It would be great to be able to lower the consuming by hand.
> 
> Here is a question of a new-to-the-game-player (me): If i put several Combustion Generator in a row like in the example in my first post then the first Combustion Generator takes 50% of all coal, the second 25% of all coal (50% of that coal that is left), the third 12,5% of all coal and so on. So the 10th in the row will get <1% of coal. Is there a good way to give any Combustion Generator the same amount of coal without getting big with the environment needed?
> 
> It would be great if i could tell the router how much % it should give to the exits each.
> 
> Thanks - Enomine

Router doesn't output into a direction if it is all. With this in mind, the first combustion generator will fill up (ofc it will burn through the coal, so the router will still provide it with some along the way), then the remaining coal will be passed further, and that's basically what you want. Realise this: each piece of coal in a combustion generator produces a set amount of power. Given that combustion generators store a finite amount of coal, then every piece of coal consumed went to power production, so you're good as long as your coal is consumed in terms of power.

For the last thing, Anuke said not to suggest it, and for righteus reasons. The transport blocks are meant to be simple in their purpose and working. However, you could do that using logic.

**Comment by itcannotbe** [comment]
> > It would be great if i could tell the router how much % it should give to the exits each.

> For the last thing, Anuke said not to suggest it, and for righteus reasons. The transport blocks are meant to be simple in their purpose and working. However, you could do that using logic, but - there is simply no reason to.

### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Additional configuration of blocks, such as I/O side configuration

Yeah, that's definitely on the "do not suggest" list.

**Comment by Jaeyun21** [comment]
How does power not get used if its connected to say silicon smelters?
