### ISSUE TITLE
Add a api Call.textInput() for directly input strings

### ISSUE THREAD

**Issue by Cong0707** [Anuken/Mindustry-Suggestions#4213]
### Describe the content or mechanics you are proposing.

Add a _Call.textInput()_ method that show a menu to the player to write some strings for questions send by server.

I try to write something,it just need an return module.

@Remote(variants = Variant.both)
public static void textInput(String title,String textName,String textHelp,int textLength,Cons<String> confirmed){
    if(title == null) title = "";
    if(textName == null) title = "";
    if(textHelp == null) title = "";

    ui.showTextInput(title, textName, textLength, textHelp, confirmed) -> ??
}

just insert under the openURI method

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I'm a server plugin coder,when I want to get the player's message or other something,
maybe description kick reason, maybe enter the amount of coins,or simply enter a map serial number,
You can only listen to messages sent by players.

so this api can improve plugin a lot
just complete my code to write a return call,that's all

hope it can come ture plz

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Is this the advent of ads in mindustry?

**Comment by Cong0707** [comment]
> Is this the advent of ads in mindustry?

nope, ads has nothing to do with this api,it just make get string by players easier,and nobody want to add ads to mindustry.
