### ISSUE TITLE
Name for blue team

### ISSUE THREAD

**Issue by DARKSABR** [Anuken/Mindustry-Suggestions#4216]
### Describe the content or mechanics you are proposing.

A name for the blue team

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The name will be taloss. As purple got a name in v7, it would be nice to get a name for blue in next update(or if tantros gets added)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Spoiler alert: Tantros won't be finished.

**Comment by BloodRaven0** [comment]
Won't be finished officially* (By anuken)
There could still be mods or even a community-made fork.

Also what about green? They also need a name.
