### ISSUE TITLE
Slag heater

### ISSUE THREAD

**Issue by Dugger1** [Anuken/Mindustry-Suggestions#4217]
### Describe what you would like changed, and why.

Make it output more heat. Thats it. How can it output only 6 heat when you literally feed it molten minerals.

### Describe the changes you want to propose. Include possible alternatives.

Reduce phase heater's output. non sense

**Comment by BlueWolf3682** [comment]
Update your game. It outputs 8 heat.

**Comment by IlSashalI** [comment]
Он выдаёт так мало тепла потому, что эрекир итак очень горячая планета, и температура шлака не сильно выше температуры поверхности.

**Comment by Jaeyun21** [comment]
> Update your game. It outputs 8 heat.

Lmao +2 heat still isnt that good
