### ISSUE TITLE
Lensing based turrets

### ISSUE THREAD

**Issue by 060507** [Anuken/Mindustry-Suggestions#4218]
### Describe the content or mechanics you are proposing.

Just a turret with damage based on environment's light level

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe that it's implementation could make lighting to have more effects on gameplay (right now, as far as I know on Serpulo, it does affect only output of solar pannels and visibility only, so a turret with a mechanic that also is tied to it might make it more important)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaeyun21** [comment]
Just power a lancer using a solar panel
