### ISSUE TITLE
Sprite differences between Ozone, Hydrogen, Nitrogen, & Cyanogen

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry-Suggestions#4219]
### Describe the content or mechanics you are proposing.

Changing the shape of the sprites for liquids in general. This means changing the droplet textures and spiral textures.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Right now, the game is *directly* inaccessible to colorblind people wishing to use liquids in any capacity, especially when attempting to hook up factories that require liquids. Sure, there are ways to work around it - but it is a very simple change, and not implementing it directly makes the game less accessible.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Better feature? option to add a label to literally everything

**Comment by Jaeyun21** [comment]
Like just click on the liquid duct and it will say what liquid is in it
