### ISSUE TITLE
Armoured bridge conveyors?

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#422]
**Describe the content or mechanics you are proposing.**
Simply, an armoured bridge conveyor. Same range and throughput as normal bridges but more health.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
quality of life.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version. (I have not, I don't have time to check everything at the moment)
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by LiamDonohue** [comment]
i like it

**Comment by HaphLife** [comment]
Perhaps it could also not accept inputs from non-conveyors (to act like armoured conveyors)
