### ISSUE TITLE
Pressing Ctrl to enter and control Scathe

### ISSUE THREAD

**Issue by AndrewSod** [Anuken/Mindustry-Suggestions#4224]
### Describe what you would like changed, and why.

When I enter and manually control Scathe, I can't zoom out nearly enough to see its full range. My suggestion is for the camera to allow the player to zoom out further than usual specifically when inside the Scathe to the full range of the Scathe. This would allow the player to choose where to shoot the missile at the full range of the Scathe.

### Describe the changes you want to propose. Include possible alternatives.

Allow the camera to be zoomed out to fit the full range of the Scathe when the player manually controls it.

Alternatives? Maybe you could select the Scathe when in command mode, then select a target or location that it would shoot at. This would be similar to how units are controlled.

**Comment by BloodRaven0** [comment]
Another option is to download and install Foo's client (https://github.com/mindustry-antigrief/mindustry-client) that adds further outzooming and other QoL features.

**Comment by Jaeyun21** [comment]
Pan??
