### ISSUE TITLE
In Mindustry 7.0 Build 140.4, my friend is having trouble with how to supply turret.

### ISSUE THREAD

**Issue by some-one-of-men** [Anuken/Mindustry-Suggestions#4227]
### Describe what you would like changed, and why.

In Mindustry 7.0 Build 140.4, my friend is having trouble with how to supply turret. Our language is Chinese(simplified). 

We are play in "Campaign"-"Serpulo"-"Ground Zero", my friend is new player so he don't know how to complete "Supply Turret" (May he not is patient enough). I play "Ground Zero" in this version, this time, there didn't have any description about how to supply turret, also haven't description about holding mineral and put into core or other buildings, or supply turret example, before "Supply Turret" mission was shown. 
I play this game v126.2 at first, I think in this version"Ground Zero" campaign had better description to learn build something. Finally, I build a simple running supply turret example then he know how the example work. 

### Describe the changes you want to propose. Include possible alternatives.

I hope you can do a better description about how to play Mindustry in the "Campaign", of the future. 
I also hope you have time to do a better translation about buildings' name, because there are difference between the translation name in the past and now, I want to know the those name mean. 
Tank for you reading.

**Comment by Jaeyun21** [comment]
For real
