### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by TheDeparted7** [Anuken/Mindustry-Suggestions#4229]
### Describe the content or mechanics you are proposing.

Re Add. Elevation, and all related aspects as seen in earlier Mindustry versions. Such as V4. Would add more terrain. Depth. And usage for Crawler and Mech like units. With advantageous locations. Hence currently there are none. Besides chokepoints, and bodies of water.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Would add more usage for Terrain Scaling Crawler and Mech unit type. Would add more terrain and depth. And would all for more interesting battle scenarios. This would be especially good for larger maps. The addition of height, would allow for the creation of advantageous locations, as there are currently few in game right now. It would provide certain buffs to specifc blocks. Like increased radar range. And would make artillery work better. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
v4 doesn't even have real elevation.

**Comment by BloodRaven0** [comment]
Cliffs are available for generation in the map editor by pressing the "walls to cliffs" button. They just aren't used in the campaign maps.
