### ISSUE TITLE
Stop Duct bridges from chaining

### ISSUE THREAD

**Issue by markuskruse** [Anuken/Mindustry-Suggestions#4232]
### Describe the content or mechanics you are proposing.

A duct bridge should only go one step, with one start and one end.

Having three in a row should not cause the middle one to latch onto the last. Three is invalid and stops the flow until a fourth is added or third is removed.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Many times I want to build a bridge, then route to the side, the build another bridge. Like this:

bridge -> empty -> bridge -> router -> bridge

But the router is skipped because the bridges automatically connects over the router.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaeyun21** [comment]
I have had this issue, make it like the serpulo bridges, manually connect and disconnect

**Comment by Korne127** [comment]
Why has this been closed as completed? That's misleading; this is still an ongoing issue that should be resolved.

**Comment by nozwock** [comment]
Auto connecting is very annoying.
