### ISSUE TITLE
Erekir: seige

### ISSUE THREAD

**Issue by demigod279** [Anuken/Mindustry-Suggestions#4233]
### Describe the content or mechanics you are proposing.

This is small, but fron my experience, 10 minutes is not enough to prepare fore enemies. I think the intervals of enemy acceleration should be 15 minutes, even though it is a difficulty extreme level.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This level is designed to be an attack level, rather than a defense level. the lack of thorium makes setting up impenetrable defenses hard for the first 30 mins of the level, and nobody wants to waste a half hour only to lose your core. 

Again, its tiny, and probably wont even go through, but its not against the rules (i think) so i thought i would share.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by demigod279** [comment]
goddamn spelling mistakes i give ip

**Comment by Jaeyun21** [comment]
Lol ip
