### ISSUE TITLE
Bring back the group control

### ISSUE THREAD

**Issue by Awarela** [Anuken/Mindustry-Suggestions#4234]
Bring back the group control and integrate it as a function in the new command system (replacing the current assist player or being an alternative)
New command system It's really useful but It's complex af and makes you lose time in situations that could be solved faster with the old group control, I don't like the AI doing everything for me, attacking with a lot of drones at the same time used to be really comfy and better way than just sending the AI (cause they always end up killing itself).
I think It would be a way of doing the game comfy for more people and maybe could bring new ways of improving gameplay using both of the systems at the same time.
Also It would be better and more simple for new players, which slowly will be swapping between the two systems while they learn how to play.

**Comment by itcannotbe** [comment]
Why did you even delete the template's text?

**Comment by Slotterleet** [comment]
Have you considered reading the [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)?
