### ISSUE TITLE
Username and Password System for multiplayers

### ISSUE THREAD

**Issue by COALROCK8642** [Anuken/Mindustry-Suggestions#4235]
### Describe the content or mechanics you are proposing.

Griefers. Too many Griefers in servers. Need moderation controls?

Why, I have seen server owners make bad mods who never keep eye an inspect. Never come when needed. Neither made way to ping them.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Username and Password System for multiplayer

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
How would that even work?

**Comment by COALROCK8642** [comment]
You are simply using email.

**Comment by end-me-please** [comment]
creating a new account/email is not much less convenient than changing UUID..
wouldn’t be a big improvement over UUID+IP bans

**Comment by COALROCK8642** [comment]
I see admins sitting and doing nothing, griefers ruining games, MP community dying and becoming smaller.

**Comment by itcannotbe** [comment]
BLAME THE FUCKING SERVER OWNER, NOT THE GAME ITSELF.

**Comment by COALROCK8642** [comment]
Well, I can ASK THE GAME TO DO SOME CHANGES WHICH WILL NEVER GET ACKNOWLEDGED.
