### ISSUE TITLE
CHANGE THE F*CKING DECONSTRUCT MULTIPLIER TO 0.7 to 1

### ISSUE THREAD

**Issue by COALROCK8642** [Anuken/Mindustry-Suggestions#4236]
### Describe the content or mechanics you are proposing.

Why? you did make to reconstruct if players get banned. Atleast make defaults so that map makers never see that as a problem. Server admins lazy and never keep up so this must be one-n-end solutions.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

No.

*Edit: this make griefers efforts lesser, since we still got the resources in equal volumes.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
No.
Just exactly how you answered the "how you think this content will improve the game" question.

**Comment by COALROCK8642** [comment]
Edit: this make griefers efforts lesser, since we still got the resources in equal volumes.

**Comment by itcannotbe** [comment]
No, instead of being actually helpful, griefers will shift to spam wasting blocks

**Comment by COALROCK8642** [comment]
WE can remove them, making no losses.

**Comment by Jaeyun21** [comment]
Calm down Jamal

**Comment by Eclipse-04** [comment]
uh
i thought theres an option for that in the map setting
