### ISSUE TITLE
Campaign map

### ISSUE THREAD

**Issue by traincrisis** [Anuken/Mindustry-Suggestions#4237]
### Describe what you would like changed, and why.

What sector and seed were used to make erekir campaign map the onset? send this to me or just send me this map with the enemy bases.

### Describe the changes you want to propose. Include possible alternatives.

nothing are in this area should be

**Comment by itcannotbe** [comment]
Named sectors do not use a map generation via seed. It uses actual [map saves](https://github.com/Anuken/Mindustry/tree/master/core/assets/maps)

**Comment by itcannotbe** [comment]
Also this is not where you ask for help. This is for suggestions.

Close this already.

**Comment by traincrisis** [comment]
> Also this is not where you ask for help. This is for suggestions.
> 
> Close this already.

Closed.
