### ISSUE TITLE
Easier multiplayer for mobile

### ISSUE THREAD

**Issue by notauser123** [Anuken/Mindustry-Suggestions#4238]
### Describe the content or mechanics you are proposing.

Please just make it easier to play with friends online without needing to do anything complicated, I don't want to potentially get a virus just trying to play with just one of my friends.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make multi-player so much easier, plus I could suggest more features related to multi-player if this gets added since servers would be less of a necessity

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
there aren’t really easier ways. It’s not possible to implement. 

You can play on servers, use port forwarding, or a VPN/tunnel.
