### ISSUE TITLE
Allow unit throwing items into void

### ISSUE THREAD

**Issue by VladisS-Vostok2000** [Anuken/Mindustry-Suggestions#4239]
### Describe what you would like changed, and why.

There is the copy of last [suggestion](https://github.com/Anuken/Mindustry-Suggestions/issues/1560).
I want to say, that's this option is important.
Imagine a situation where you use the flare transport. One processor (for example, Overdrive Dome) uses Silicon to deliver it there, and when the dome is full, releases it, but the silicon resource is still left on flare. The second processor now needs delivery, but it doesn't need silicon. Then flare needs to throw out this resource, and here's the problem: I need to look for a container to do this (why?). Mkay, everyone uses Core for this. The catch is that the Core may be overflowing and there is no way to throw the resource there, so flare is inactive.

I consider it extremely necessary to add, but it seems to me that it is clear why it was not implemented: on servers this is a very simple way grief by throwing resources from the core.

At the moment, I've noticed that units can't build buildings in multiplayer, probably to limit griefing. This means that this function can also be added to the filter and there will be no problems.

### Describe the changes you want to propose. Include possible alternatives.

Changing null, zero or new @void argument in function "Throw resourse" as throwing current unit resourse into void.

**Comment by LeoSko** [comment]
There is `@air`

**Comment by VladisS-Vostok2000** [comment]
I found not @air in https://mindustrygame.github.io/wiki/logic/3-variables/
But okay. Thanks!
