### ISSUE TITLE
Allow the T4/T5 factories to be clicked on to show how many blocks and units are inside

### ISSUE THREAD

**Issue by AndrewSod** [Anuken/Mindustry-Suggestions#4240]
### Describe the content or mechanics you are proposing.

You can click on smaller unit factories and other structures like silicon arc furnaces to see a list of items in the machine. This is a nice feature but it does not work on the T4/T5 factories. I'm proposing that the T4/T5 factories be able to show how many blocks and units are currently inside the factory when they are clicked on, just like the smaller factories that show how much silicon/beryllium is inside them when clicked on.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will allow the player to see how close the T4/T5 factories are to starting construction on a unit. This would be especially nice for T5 factories, which require 20 large carbide walls.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jaeyun21** [comment]
This would be useful

**Comment by Rovstam** [comment]
Yes. And also pause on build for android. And command all units for android. 
:)
