### ISSUE TITLE
Join Substitute

### ISSUE THREAD

**Issue by Jaeyun21** [Anuken/Mindustry-Suggestions#4243]
### Describe the content or mechanics you are proposing.

Make a unique code for the room when the host hostes the world, amd allow players to join using the code.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Much more convinient than paying for servers or portforwarding.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
Not really possible. Networking just doesn’t work like that. 
use steam if you want that

**Comment by code-explorer786** [comment]
This _probably_ falls under cloud sync, but I am not 100% sure.
Would love to see someone else implement it though. Just not an official version.
