### ISSUE TITLE
More game files

### ISSUE THREAD

**Issue by AlvariCOCKe** [Anuken/Mindustry-Suggestions#4249]
### Describe the content or mechanics you are proposing.

Instead of having to delete your current campaign save file in order to start a new campaign file i suggest that there are multiple game files implemented so we can restar our campaign without having to delete our previous one

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would make it easier for people to have multiple campaign files and being able to get a fresh start without losing all their progress, or maybe if they want to share the game with a familiar so they can create their own campaign game file without having to play on an already made one, or in my case if I've been not playing this game for a long time and i want to create a new campaign file to re-learn how the game worked and what does everything do.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Have you considered, exporting your game data?

**Comment by AlvariCOCKe** [comment]
> Have you considered, exporting your game data?

i dont know how to and to be honest im a little scared to break the game by interacting with the game files

**Comment by SMOLKEYS** [comment]
> > Have you considered, exporting your game data?
> 
> i dont know how to and to be honest im a little scared to break the game by interacting with the game files

buddy an option for exporting game data exists in the settings
