### ISSUE TITLE
Mindustry Server Replacement

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry-Suggestions#4251]
### Describe the content or mechanics you are proposing.

I suggest replacing the standard anyuk server with one made in my likeness, since I think that it is much more convenient for administrators, does not mix input / output, a couple of jline chips, and the code is already outdated for current servers

[Mindustry Server Replacement](https://github.com/SSTentacleSS/MindustryServer)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

* Command History
* Adequate work with <-, ->
* Does not mix input and output
* Obtaining an API for developers to interact with the server (reflection was previously required to receive some data from the server), removing constants that interfere with developers (without problems, for example, do not make a custom map loader, since there is a boolean mapLoading (or something similar))
* The presence of events for shutting down the application and, accordingly, a message about it

Everything for the convenience of administrators, while the current version can be easily combined with the current kernel without any additions

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
I think this can be better implemented by adding to the server API (which doesn't sound very difficult), and adding new events. I am not interested in merging in/replacing large amounts of code with something I didn't write.

As for jline... as far as I'm aware, this is a library that has native dependencies, and I'd like to avoid bloating the server with these. I'm not sure if it's even supported on all architectures people run servers on, and I'd rather it be kept as a standalone plugin if possible.

**Comment by SSTentacleSS** [comment]
I understand you, I myself have questions about jline, it often breaks in stdio mode, what's the problem
Then if you don't mind, I'll think about some API for the server? I would like to see, for example, events not in the .on format, sometimes I would like the server to be more responsive to changes

*as bad example, extremely unreliable*:
![image](https://user-images.githubusercontent.com/91948148/212205000-05f045eb-ae07-4ccc-907b-f1b3ed8f83d0.png)

*why asynchronously? otherwise it is impossible, otherwise an error will be raised, as if this code was executed somewhere it is not known where ->*
```java
class Events {

public ..fire(...) {
  int size

  for (i in size) {
     listeners[i]... //i out of range exception
  }
}

}
```
