### ISSUE TITLE
Undo cancel build button

### ISSUE THREAD

**Issue by leetfin** [Anuken/Mindustry-Suggestions#4254]
### Describe what you would like changed, and why.

(Android)

I spent an hour planning out a whole sector and then accidentally hit cancel, wiping out the whole build plan. An undo or double tap to confirm would be awesome!

### Describe the changes you want to propose. Include possible alternatives.

Undo last cancel build button added to UI, probably near cancel button?

#422

**Comment by leetfin** [comment]
prevent stale.

**Comment by BalaM314** [comment]
I think double tap to confirm if there are more than, say, 50 builds would work well

**Comment by leetfin** [comment]
Prevent stale.

**Comment by leetfin** [comment]
prevent stale.

**Comment by leetfin** [comment]
This is not stale.

**Comment by leetfin** [comment]
@Anuken I love your game but this stalebot is ridiculous.

**Comment by Anuken** [comment]
I don't see why that matters at all, as the point of the stale bot is to close issues where nothing is being discussed. There is nothing being discussed here, and bumping it doesn't affect visibility - I already saw this issue when it was first posted.
