### ISSUE TITLE
Own categories for mods

### ISSUE THREAD

**Issue by xStaBUx** [Anuken/Mindustry-Suggestions#4256]
### Describe the content or mechanics you are proposing.

Change the way categories are added to the plan menu so that mods can add their own categories.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

#This will allow mods to have their own category for their content.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
At this point you mod shouldn't be using just HJson.

**Comment by xStaBUx** [comment]
I cannot modify the list of categories because it is an enum.  Of course, I can replace it, but if 1 more modification wants to add a category in the same way, there will be a conflict

**Comment by Slotterleet** [comment]
I actually also want to suggest a possibility for mods to create brand new content types, you can't make new ones for the exact same reason: ContentType is enum.
