### ISSUE TITLE
New Serpulo Liquid Turret

### ISSUE THREAD

**Issue by AzmeurYahigai** [Anuken/Mindustry-Suggestions#4258]
### Describe the content or mechanics you are proposing.

Name: Rain
Suggested size: 2x2
Suggested range: 30
Shots per second: 0.25
Effects:
• No knockback
• Splash attack (Radius of 5)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Encourages players to utilize buff combos. The current way of applying buffs is ineffective and inefficient. Only affects the frontline and eats a lot of liquid. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lolnoizcool** [comment]
How about it being on tantros
