### ISSUE TITLE
Don't play launch when the map is corrupted

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry-Suggestions#426]
**Describe the content or mechanics you are proposing.**
title

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
just convenient

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

*I stumbled upon this while making my bug report but didn't feel like it was worth making another bug report for it*

**Comment by Syncinus** [comment]
Then it's a bug not a feature

**Comment by Kyllingene** [comment]
I think his point was that if the map is corrupted, he doesn't want to have to wait for the launch sound. I wouldn't call it a bug, but it would be better as a bug report.
