### ISSUE TITLE
Keyboard and mouse for Android.

### ISSUE THREAD

**Issue by LIINAD1** [Anuken/Mindustry-Suggestions#4261]
### Describe the content or mechanics you are proposing.

Full keyboard and mouse support for the android version. Please.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make the gameplay on the Android version as comfortable as on the PC version.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
respected developer. JUST DO IT ! MAKE THE TRUTH!
Many people in the world NEED THIS! and YOU, yes YOU ANUKE! DO IT HERE AND NOW.
уважаемый разработчик. ПРОСТО СДЕЛАЙ ЭТО ! СДЕЛАЙТЕ ПРАВДУ!
Многим людям в мире ЭТО НУЖНО! и ТЫ , да ТЫ АНУКЕ ! СДЕЛАЙТЕ ЭТО ЗДЕСЬ И СЕЙЧАС
https://user-images.githubusercontent.com/71027210/212795555-080e704b-12be-4078-9a4e-a9fc11fb0321.mp4
