### ISSUE TITLE
буры устарели ,обновите .drills are outdated, update

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#4262]
### Describe the content or mechanics you are proposing.

будущее наступило старик , все используют крутые буры из модов , время обновить оригинальные буры .
1 изменить потребление воды всеми бурами с фиксированной величины на прогрессивную . при 6 воды у бура будет 1 уровень ускорения работы (добыча руды х1,5 . потребление энергии х2) . 2 уровень 12 воды : х2.4 руды , х3 потребление энергии . 3 уровень 18 воды : х3 руды , х4 потребление энергии .
добавить возможность крио охлаждения буров .
1 уровень 6 крио в сек : х3 руды , х2 потребления енергии
2 уровень 12 крио в сек : х3,8 руды , х2,4 потребления енергии
3 уровень 24 крио в сек : х7 руды , х4 потребления енергии
4 уровень 48 крио в сек : х10 руды , х6 потребления енергии

The current drills in the game are outdated and need to be updated.
The future is here old man, everyone uses cool mod drills, it's time to update the original drills.
1 change the water consumption of all drills from fixed to progressive. at 6 water, the drill will have 1 level of work acceleration (ore mining x1.5 . energy consumption x2) . 2 level 12 water: x2.4 ore, x3 energy consumption. 3 level 18 water: x3 ore, x4 energy consumption.
add the possibility of cryo-cooling drills.
Level 1 6 cryo per second: x3 ore, x2 energy consumption
Level 2 12 cryo/sec: x3.8 ore, x2.4 energy consumption
Level 3 24 cryo/sec: x7 ore, x4 energy consumption
Level 4 48 cryo/sec: x10 ore, x6 energy consumption

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

вы когда нибудь  упирались в максимум руды что можете добыть на карте? вероятнее всего нет , но я искрене люблю эту игру и хочу чтобы игроки могли добыть достаточно руды для любых проектов .

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
People using mods have no effect on people playing vanilla, more so people playing on servers.

**Comment by ziszlo** [comment]
> 
then why not let the Boers use cryogenic liquid?
all turrets have the ability to use water or cryogen, some other liquids. do drills consume different types of gases on erekir? .
but the drills on serpulo have never been updated since 2019. it's been 4 years already. please update them...

тогда почему бы не позволить бурам использовать криогенную жидкость ?
у всех турелей есть возможность использовать воду или криоген , у некоторых другие жидкости . на ерекире буры потребляют разные виды газов? .
но буры на серпуло ни разу не обновлялись с 2019 . это уже 4 года . пожалуйста обновите их ...

**Comment by Lightness-not-night** [comment]
Используй логику для добычи ресурсов квазары пульсары моно поли Меги могут копать и уголь  песок титан, но если 1 ядро это не очень эффективно, и при этом нужно иметь схемы от ядра
