### ISSUE TITLE
swarmer nerfing

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry-Suggestions#4265]
### Describe what you would like changed, and why.

alloy swarmers deal extremely high damage while cost quite low ammos. for example, killing a vela only needs about 30 alloys.

### Describe the changes you want to propose. Include possible alternatives.

increase the ammos cost in one shot. 4 per shot may be a good idea.

**Comment by IlSashalI** [comment]
4 за выстрел это слишком. Их тогда вообще никто не будет использовать
