### ISSUE TITLE
add abandoned structure in maps 

### ISSUE THREAD

**Issue by manytimeikhow** [Anuken/Mindustry-Suggestions#4266]
### Describe the content or mechanics you are proposing.

it means that there will be randomly generated structure in the story mode or other maps (but it is abandoned) 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think it will make the player more curious about wha inside those buildings and discover why it is abandoned or simply just de-craft the blocks to get material for their build

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Salt Flats, Overgrowth, Nuclear Production Complex, Impact 0078 and maybe other maps have derelict structures that can be deconstructed for extra resources. Why are you suggesting something that already exists in the game?

**Comment by Lolnoizcool** [comment]
Faction name derelict:
