### ISSUE TITLE
add mutant when contact the radioactive created from power plant

### ISSUE THREAD

**Issue by manytimeikhow** [Anuken/Mindustry-Suggestions#4268]
### Describe the content or mechanics you are proposing.

its like when a flare or a dagger got in contact with a radioactive from the power plant and it help the flare or the dagger to boost its strength or its speed but theres a catch . it will not know which is friend or foe so it will attack anyone at its sight

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think it will help improve the game by adding a new mode like mutant attack where you and the boys prepare for the attack from the mutants just like COD zombies (it just like attack but with survival in that mode and hardcore)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Eclipse-04** [comment]
robot don't mutate.

**Comment by Lolnoizcool** [comment]
Robot arent biological being, they malfuntion instead
