### ISSUE TITLE
Drill Construction Halting The Resource Pipeline

### ISSUE THREAD

**Issue by Pulchritude** [Anuken/Mindustry-Suggestions#427]
Currently, at least in my experience, starting a game means first laying out mechanical drills to gather resources for initial defense installations and prep for industrial buildings, and then upgrading those mechanical drills to pneumatic drills once graphite presses are up and running.

This is easiest done by pausing the game and queuing all the upgrades at the same time. However, on unpause, the player's craft initializes all constructions in range at once, effectively shutting off all of those mechanical drills being upgraded and halting the flow of resources from them, even when those drills are producing the resources needed to perform those upgrades.

I would suggest either a) making it so that a second building being constructed atop a first building won't deconstruct that first building until construction completes, or b) adding an option in settings that makes the player craft initiate and complete construction on buildings in the queue that are in range one at a time.

**Comment by potatoisagender** [comment]
Maybe I am mistaken, but in my experience when you replace anything (ripples with cyclones or fuses, mechanical drills with pneumatic, etc., etc.) it will build on at a time, as long as you have the resources to build them.

**Comment by itcannotbe** [comment]
@potatoisagender They do. The problem begins when you really don't enough because it causes the next one to be tried to be built.

But in hindsight you shouldn't even be laying out a lot of stuff if know you actually lack something.

**Comment by potatoisagender** [comment]
exactly. Maybe the problem here is technique rather than the game. The purpose (at least, what I think the purpose is) of the builder flicking through all items in queue is that there might be some other thing available to upgrade, but way down in the queue.

**Comment by Rybadour** [comment]
I agree with OP drills should only be disabled when they start building rather than immediately. Perhaps a building should not "start building" until there is at least one of each resource available?
