### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by go-na-swidanie-benry** [Anuken/Mindustry-Suggestions#4273]
### Describe the content or mechanics you are proposing.

Сделать шаблоны для процессоров к примеру доставка ресурсов, код для считывания кнопки, отключение при недостатке ресурсов, поможет оптимизировать миндастри. Но убирать кодинг нельзя,ведь схема может быть не универсальная. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Повышение fps, помощь схемоделам, избавление от аттем логики. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
чювак суть процесоров в их БЕЗГРАНИЧНОЙ(ограниченной) МОШИ 
ТВОИ ТРЕБОВАНИЯ СМЕХОТВОРНЫ , если не умееш кодить то попроси когонибуть помочь тебе в этом .

**Comment by Dangleos** [comment]
Анюк написал в правилах что если предложение не на английском то он не станет пытаться его прочитать
