### ISSUE TITLE
too expensive research.

### ISSUE THREAD

**Issue by Champpeace1234** [Anuken/Mindustry-Suggestions#4275]
### Describe what you would like changed, and why.

Unlocking new units is too expensive. 83 thousand silicon and 62 thousand plastanium for a quad I probably will not use?  I don't want to bother.

### Describe the changes you want to propose. Include possible alternatives.

Please reduce how expensive this is. It takes forever to get these materials, and I already use that speedhack mod.

**Comment by ziszlo** [comment]
This number is rather symbolic, for the player who understands how to build several hundred thousand resources in a couple of hours an interesting chelage. You use the disgusting schemes that give out 1-3 silicon per second, take yourself in your hands and think how to build it to the world who gives all the silicon in the world and do not sit on your ucherybic scheme for eternity.

**Comment by Bottinator22** [comment]
You have an entire planet on your hands that can produce all the resources you ever need if you just put in the effort to mass produce things

**Comment by SMOLKEYS** [comment]
an insufficient amount of skill

In a serious note, build more factories and improve production. Time control mods won't do shit if your production in general is shit.

**Comment by IlSashalI** [comment]
Просто построй больше заводов кремня в разных секторах
