### ISSUE TITLE
Provide way of using large payload mass driver on mobile

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry-Suggestions#4276]
### Describe the content or mechanics you are proposing.

There is no user controllable unit on mobile that can load 3x3 cargo into large payload mass drivers.  If units (e.g. quell) were made controllable (or at least able to be commanded to pick up/drop cargo) then the large payload mass driver could be made useful for mobile-only players.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Restores balance to the large payload mass driver for mobile players.  Being able to yeet reinforced liquid tanks and reinforced vaults really helps with production.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Try holding a block you want to carry, and then holding a position you want to unload that block onto and see. Thay should work.

**Comment by willis936** [comment]
On mobile Erekir the only user-controllable units are evoke, incite, and emanate.  Those all only have a payload capacity of 2x2, meaning there is no way to load 3x3 payloads.

**Comment by Bottinator22** [comment]
Have you tried double tapping other units?

All units (except the missiles and block-related drones) are user-controllable

**Comment by willis936** [comment]
Ah yeah that works.  I don't know why I had trouble taking control of the quell.  Maybe the tap hitbox on them is small compared to their perimeter.
