### ISSUE TITLE
More support on exporting save data on linux mint

### ISSUE THREAD

**Issue by PythonZER0** [Anuken/Mindustry-Suggestions#4283]
### Describe the content or mechanics you are proposing.

I've been having an issue with exporting my save data on linux mint. it says it downloaded the file, but I can never find the file. it would help if there was at least more support for the file system, so I could check a specific area and not just somewhere in my home folder. Thanks!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would likely help anyone who plays on both linux mint and some other platform, making it easier to transfer save data from one device or operating system to the other. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
> so I could check a specific area and not just somewhere in my home folder.

As far as I'm aware, this is a problem with the snap/flatpak version of the game only, which are not made/maintained by me. 

*(It's also why I personally avoid both of those package systems...)*

**Comment by UltraBlackLinux** [comment]
Flatseal can be used on flatpak for more flexibility. This might help
