### ISSUE TITLE
Marked sectors

### ISSUE THREAD

**Issue by Dugger1** [Anuken/Mindustry-Suggestions#4284]
### Describe the content or mechanics you are proposing.

You could select a sector and than you would be able to set it as "favourite". It would show on the top of sectors list.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Well if you're playing and you want to go to your main sector (or if you can't find it for some reason), you could just use the sectors panel and you would see your marked sector on the top of the list. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Epicgamer173** [comment]
This would be nice, especially since some of us use certain sectors for certain things and don’t use others
