### ISSUE TITLE
标题

### ISSUE THREAD

**Issue by Uiugkhbkhbkg** [Anuken/Mindustry-Suggestions#4285]
### Describe what you would like changed, and why.

Why can't Scorpio make things?

### Describe the changes you want to propose. Include possible alternatives.

Change it back.dT-Tb

**Comment by eggbanana173** [comment]
¿? ...

**Comment by Dangleos** [comment]
Toxipid can't build anymore because it was too OP. Biggest single target damage, biggest aoe damage, high mobility and self-healing
