### ISSUE TITLE
unstable ducts

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#4289]
### Describe what you would like changed, and why.

Converors always accept items from behind first and then items from the sides at 50/50 ratio but the ducts are not

### Describe the changes you want to propose. Include possible alternatives.

Make ducts act like conveyors

**Comment by itcannotbe** [comment]
https://trello.com/c/MTDk3KUh/

A trello card that's been there since July 15, 2021

**Comment by nanmenyangde** [comment]
it will break many done schemes.

**Comment by Dangleos** [comment]
I though trello card meant multiplayer desynchronization. Not unstable ducts
