### ISSUE TITLE
(v6) (logic) PlayTone command

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry-Suggestions#429]
**Describe the content or mechanics you are proposing.**
PlayTone command for processor blocks and blocks, that will output sound.
Playound command will work for only one note. You can choose how long will it play, what thone will it play, in what octave will it play, and on what volume. 
Blocks outputing sounds will have 3 tiers
1 tier: 1x1, cheap block, sound will work 50 blocks from it,
2 tier: 2x2, medium cost block for mid-game, works from 100 blocks,
3 tier: 3x3, expensive, works from max 200, the radius will be possibe to change.
Also this blocks will take 1 resocure per 20 notes, depending on resocure, other type of sound will play. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
That will give game some more options to players, various songs on ex. fortline or core. Music and sfx for games made with logic system

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
earrape schematic yes

**Comment by sk7725** [comment]
oh *yes*

**Comment by FarmerThanos** [comment]
yes
we need this for mindoomstry

**Comment by sk7725** [comment]
Alternatively, speakers and sound&sound flush blocks

**Comment by DeltaNedas** [comment]
commandblocks could have this

**Comment by Leo-MathGuy** [comment]
rickroll
