### ISSUE TITLE
Make player controls void processor controls again

### ISSUE THREAD

**Issue by JamesTDG** [Anuken/Mindustry-Suggestions#4291]
### Describe what you would like changed, and why.

In EVERY attack server I play on now, users continue making logic that harms gameplay a lot, I just want to restore how V6 handled stuff because it is causing entire arguments every single match because 1 user controls ALL of a specific unit, or worse, sometimes even all of the units.

### Describe the changes you want to propose. Include possible alternatives.

Make player controls void processor controls and allow units to be selectable despite logic controlling them.

**Comment by TheEt1234** [comment]
~~diagnosis:skill issue~~
