### ISSUE TITLE
Server order

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry-Suggestions#4295]
### Describe what you would like changed, and why.

Sorry, but I don’t understand why the change was introduced that servers are sorted by hash code, this is not sorting at all, for example, why do I need a Chinese server in 3rd place with 10,000 pings, if I live in Ukraine and want to get a server with Ukrainian localization, as a result, on all servers from 1 to 6 - we have English servers, on 7 - Russian, and large projects are still in 27th place

### Describe the changes you want to propose. Include possible alternatives.

Sorting by online is paramount, if the threshold for the average ping between all servers is not exceeded, then sorting by ping

**Comment by Darkness6030** [comment]
Сделать сортировку серверов конкретно в диалоге коннекта, а не в списке претендентов на пинг невозможно, для этого придется переписывать 500+ строчек.
Удачи этим заняться. (mindustry.ui.dialogs.JoinDialog.java)
