### ISSUE TITLE
New Turret "Artillery"

### ISSUE THREAD

**Issue by Matthew021750** [Anuken/Mindustry-Suggestions#43]
---
name: Matthew
about: Having a larger variety of mid-game anti-air turrets that can use copper as ammunition.
title: 'More Anti-Air Turrets'
labels: feature request
assignees: ''

---

**Describe the content or mechanics you are proposing.**
I was thinking of a 1x1 turret that can be anti-air and is of a different variation than the duo turrets and scatter. So I was thinking of a new turret which is called "Artillery".
It has a longer range than the duo and can accept copper as its ammunition. It would have a slightly faster firerate than the duo.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would give platers a better chance at defending against air bosses since scatter is somewhat cumbersome to have in a defence despite its range.
I would also feel that "artillery" would serve better than the scatter because the player wouldn't have to create a seperate line for lead to feed
ammo into Scatter. It would be better if the player could have just one line of the same ammunition, for example copper, and have the line go 
through the turrets and be fed without any issues.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by MEEPofFaith** [comment]
I mean, if you go through the trouble of making metaglass and using that, it's way better than putting just lead into the Scatters. But if you're dealing with air bosses, mild scatter spam can quickly deal with Revenants and on maps where you're dealing with Liches or Reapers, 40 rounds is a long time to wait, and by then you probably already have Swarmer, Cyclone, or Fuse spam. I don't really see this as a necessary thing.

Also, the name "Artillery" feels too generic. I consider it more of a turret class than an actual turret. (I mean, ArtilleryTurret is literally an existing turret type for modding.) With the other artillery turrets being Hail and Ripple, this probably has to have some simular naming scheme, whatever that would be. Weather/water?
