### ISSUE TITLE
Varied wind direction during storms. (to remove "Right Wall Phenomena")

### ISSUE THREAD

**Issue by HaphLife** [Anuken/Mindustry-Suggestions#430]
Suggestion: Make the weather able to come from various directions, rather than always push the player from the left

By making the wind not always come from the left, it would make the weather more varied, (and thus more interesting) and also might keep all the drones you aren't using from just floating to the right hand wall of the map and sitting there. The fact that they do feels weird, and a bit annoying. Perhaps you could also make weather a bit less common than it is right now (I'm sure you are working on balancing) since it feels a bit too common. 
Attached is a picture of my map screen showing a bunch of flying units that got pushed over there:
![Right_Wall](https://user-images.githubusercontent.com/45584117/90991509-89cfb980-e55e-11ea-9cb8-8451cf71a9de.PNG)

1. - [ x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
to expand, maybe you could make weather changes dependent on the region. For example, high mountain areas will suffer from rapid changes in weather, and fields or deserts not so much.

**Comment by HaphLife** [comment]
Sounds good, maybe the “higher” areas could have faster wind (pushes the player faster) as well. 

Also, I noticed that each zone has only one type of weather that occurs there (rain, snow, spore, or sandstorm) maybe it’d be cooler if they could have all types of weather, but with weighted odds.
