### ISSUE TITLE
Please add "modes" command for server to list available options

### ISSUE THREAD

**Issue by s3rvant** [Anuken/Mindustry-Suggestions#4302]
### Describe the content or mechanics you are proposing.

I am entirely new to Mindustry and immediately setup a server for family however was unable to locate documentation on which game modes are available to choose from having checked server commands as well as wiki.

Specifically for the command `host [mapname] [mode]` there is other command `maps [all/custom/default]` to list options however there is not a similar `modes` command to list those options.

I did eventually locate the 4 options Survival, Sandbox, Attack and PvP within the client custom game area and am assuming those are the same modes available for server hosting.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Idea is to provide more complete information for those wishing to host their own server especially those new to the game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Darkness6030** [comment]
@s3rvant there are currently 5 modes
pvp, attack, sandbox, survival, editor
editor is hidden, check it out :-)

**Comment by s3rvant** [comment]
> editor is hidden, check it out :-)

Oohhh, nice! Thanks :)
