### ISSUE TITLE
Pls add the B key thing in PC to Mobile.

### ISSUE THREAD

**Issue by Khoi1anh** [Anuken/Mindustry-Suggestions#4303]
### Describe the content or mechanics you are proposing.

Make it like a button like the "copy command" and the "delete command".

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Mobile player need this because of how useful it is on PC. Moreover, building on your phone is no where near as fast as on a keyboard. This will improve mobile player experience a lot.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Epicgamer173** [comment]
And how do you expect this to work? Sorry just that a computer is different from mobile and not all thing on computer can be transferred to mobile
