### ISSUE TITLE
RTS combat modes

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#4305]
### Describe the content or mechanics you are proposing.

Add attack, retreat and defend modes to the RTS controls for the combat units, similar to how support units have heal, build and mine modes

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

In attack mode units will automatically attack enemy cores or defend the spawn point like they could do in older versions.
With retreat mode you could send units back to the base in two clicks. And flying unit should first visit a heal point in this mode if they are damaged.
In defence mode units will go to the place where an allied block was damaged. I know malice have it

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Epicgamer173** [comment]
I was wondering why this wasn’t in the new version
