### ISSUE TITLE
Porting to unity

### ISSUE THREAD

**Issue by pyrexclient** [Anuken/Mindustry-Suggestions#4308]
### Describe the content or mechanics you are proposing.

Hello, recently i was started learning of unity and find out that this engine is more powerful than libGDX(arc) used in this project. Can you please rewrite this amazing game to unity, unity now have a lot of pluses.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Using unity instead of libGDX can improve performance and make writing this game more easy for anuken.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheEt1234** [comment]
but what about the mods

**Comment by Dangleos** [comment]
Rewrite the entire game to a different engine? You clearly lied when clicked on the third checkbox
