### ISSUE TITLE
NEW IDEAS

### ISSUE THREAD

**Issue by PRISSM** [Anuken/Mindustry-Suggestions#4309]
### Describe the content or mechanics you are proposing.

I think that within the game there are many things that could be changed or improved. Within this we can find that the combat is something very simple, so here I say something interesting to improve the PVE.
- Add a fauna, that is to say that living beings can be found and that they can bother.
- Better bosses, instead of a simple guardian, we can make a more interesting giant robot, or put some living being, like a stone golem for example.

In addition to this, there is little amount of map, there are only two planets that you complete quickly, so I thought this: 
- Add levels outside a planet, that is, in space itself, and have enemy ships attack you.
- Add in itself a solar system and fences passing planets and while you fence you have an interesting pvp between ships.

Inside your robots to attack. They are bad and very simple, getting to tier 5 rs is very difficult and it's not worth it, I recommend this to make it more entertaining. 
- Add more life to the tier 5, they have less than 20,000, and they break them in nothing, and they cost a lot, they better have 40,000 ps.
- More robots, the ones that exist are bad and there are only 3 by default, later you can improve them but they don't work.
- Constumization, it would be good to allow us to change him to a better armor, for example titanium, it would be very good.

The defense is simple, it would be nice to change some things to make it better.
- That the robots do not easily pass the walls, we can make it so that you can add spikes and that they do not pass.
- We can make it impossible for an aircraft to pass if we put a radar that disables flyers.

Some things that happen inside don't feel very comfortable.
- That it doesn't tell you "next wave 2 in 1:30" that takes away the emotion of "they're coming to attack me" because you know when, you better have to put a radar to tell you if they're coming or not.

That's all I think the game could be changed and improved, as it is now it's incredible, but it can be improved.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i dont now haha

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
Bing chilling
