### ISSUE TITLE
Interplanetery accelerator and traveling between planets

### ISSUE THREAD

**Issue by CIVPro1949** [Anuken/Mindustry-Suggestions#4314]
### Describe the content or mechanics you are proposing.

so you remember the interplanetary Accelerator, how about you bring it back and also make players not be able to switch between erekier and serplulo so it can actually have a use , and players would only able to switch planets if they already have a core there, if they haven't then they will have to launch one using the interplanetary accelerator

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

well it would add a new challange to the game making it so that players have to adapt to the new planet they have landed on, and also i feel like players would want it for their builds or art or something

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Epicgamer173** [comment]
erekier and serplulo Are supposed to be two different planets that are not associated with each other, also, I think the idea of the planet accelerator is that it basically adds more levels to serplulo but on a different planet with the same resources and buildings
