### ISSUE TITLE
Quell is a flawed unit that need some work

### ISSUE THREAD

**Issue by YSMQTHLQYH** [Anuken/Mindustry-Suggestions#4315]
### Describe what you would like changed, and why.

I could just say "quell op plz nerf" but that doesn't really address the issue.
I know that you don't want rock-paper-scissors balance and i fully agree with that but like, you need to balance the units by giving them strengths and weaknesses otherwise people will just math out the best unit and use that every time and the game will get boring.
The problem with quells is that they are simply excellent at everything with no weakness and no real way to stop them. You could make them cost 10 eludes and 40 beryllium walls and they would still be too strong, that would only make them slower to get going and delay the deathball gameplay.

Lets say that you are in a pvp game and you see your opponent making quells, what do you do?
You start making AA defenses, right? they can fly and just go around defenses so you need to cover the entire area of your base with that all are slow to build and need to be connected to an ammo source but even if you do manage to do that it wont work.
You see, quell outranges literally every tower that can hit air so they can just safely sit outside their range and destroy them, sure the missiles can be shot down but that's not fully reliable and some will go through. Even if you manage to shoot all of the missiles down the quells are still intact and the enemy factory is adding more of them and eventually the quell blob will grow to the point the missiles can get through so **you are not stopping quells, only delaying them**

So the quell-proof fortress wont work, what then? fight them with units?
Well quells are faster than all ground units, outrange nearly all of them and can fly over walls and hide over an unreachable part of terrain. There is nothing stopping quells from hiding out of ground unit's reach and killing them from there, meaning that **ground units can't even engage quells**.
But what if you instead ignore the quells and send your ground units at the enemy base and defeat their presumably weaker ground forces and defenses? Turns out that the quells can defend too, all units lack either the fire rate or range to shoot down the missiles before they get in the blast radius so they will be forced to tank the quells, which won't go well as the quells deal high damage and its good area damage too so they won't survive for very long. Not many walls or ground units are needed to buy the time to destroy an all in ground attack, after that the quell player is free to run over your base and the game is over.

So you take a hint from real life and make a fleet of fighter planes to take air supremacy and intercept the bomber-thing, right?
Quells can hit air units too, and its also high area damage and air units are weaker...
It's not a good idea from game design for quells to be the answer to quells for reasons i shouldn't have to explain. Disrupt is just a bigger and pointless quell so that gets lumped with quell as a counter to quell.
Averts are so weak and bunch up so much that they all die before even getting in range, and even if they do survive somehow they don't have the damage to do much.
That leaves Obviates, the only thing that can even **try** to fight quells. Quells kill obviates much faster than the reverse combined with the massive range disadvantage obviates end up being very micro intensive and if you look away from your obviates while they are even somewhat exposed the quells will be able to snipe them in a few seconds and then you lose the game. Also if the quells have some kind of air defense tower under them (they can retreat home even if they are far) the obviates can't do anything as they die quickly to fire from disperses or afflicts while not being fast at killing quells. That is ignoring that the whole thing is cost ineffective as you need at least twice the numbers, both units have the same build speed and obviates are arguably harder to make. Also ignores that obviates are far less flexible than quells so even if its an even trade its not the right choice.
(obviate tldr, they kinda work but you are far better off with your own quells)

So the problem is that once quells are out your only chance at stopping them is your own quells as they are good at everything.
Adjusting their stats a bit wont address the problem as thus either will change very few fight outcomes (if any).
Making them more expensive will only delay them. Even if the game need a unit that can do everything but is so expensive it's just a win condition on its own... shouldn't that unit be disrupt instead?

To make them be balanced you need to give them a significant change, one that gives them some kind of real weakness

Btw, if you only care about the campaign for some reason its still problematic because its not interesting as there is no reason to make anything else once you can build quells as they can simply do everything, be excellent at it and have no drawback or weakness to worry about for reasons similar to the ones above

### Describe the changes you want to propose. Include possible alternatives.

For the "easy" changes i suggest:

- Reduce their range by _at least_ 10 units, so they are still good against units but they cant just attack towers safely from outside their range and will need to actually fight instead
- Make them unable to attack air units, so they have a weakness to other, smaller, air units like real life bomber-likes
- Make their hitpoints and armor no more than a third of their current values, making them vulnerable to anything that does get in range and more importantly make air units actually be able to kill them rather quickly, also making them countered by air
- Give them some truly pathetic damage output, you can keep the slow unstoppable sieges but they'll just be really slow and quell will no longer be effective against units, air units kill them, ground can safely ignore them and attack the base that quells wont defend well
- Remove completely the area damage aspect, the misiles only damage the thing directly hit. That will also make them far less effective against units, the shot down misiles do nothing so units can reliably shoot them down too. Will still be able to tear through fortresses
- Turn quell into a "hovertank". ei make them a tad slower and make them not an actual air unit (like eludes, which its made out of supposedly). You can keep the high damage long range aspect but it won't be able to run away and attack ground units from out of reach forever.

What **NOT TO DO INSTEAD** as it won't actually address the issue
- Small non-comital nerf
- Rounded "overall" nerf
- Less fire rate
- Speed reduction
- Area of effect reduction
- Building cost increase
- Build time increase

And of course you can do a full rework to give them a completely new identity and role, really any major rework with some thought put into should work but i will leave some suggestions anyways.
Bonus there is also the issue of disrupt not having an identity as it just does the same thing as quell but more expensively so consider these for disrupt too.

- Turn it into a gunship with short range high damage weapons (cannons, lasers, doesn't matter) so its effective but has to actually get in danger to attack and is vulnerable to certain things. Make it either slow and tanky, so it can be kited and is a very easy target for towers or a bigger army even. Or instead make it fast and fragile so it can run away from unfavorable fights but not attack without being taking a big risk and being very expensive to use against defenses for the high loses it will have to take.
- Change the weapon for some kind of long range high damage weapon with limited to no pierce (like a flying foreshadow or lustre).  You can keep your flying bunker buster but it won't be effective against masses of low tier units at all as it will need to be easy to overwhelm.
- Turn it into a dedicated bomber, like a giant horizon. It can still be fast and tanky and have high damage but wont be able to hit air units and will need to get very exposed to attack at all.
- Make it slower and require to land and deploy its weapon (which takes several seconds) to be able to attack, wont be able to move in this mode and to move again will need to pack up and take off (again taking time). It can still be mighty but needs to commit before attacking as it won't be able to just run away nor kite the enemy nor attack from an unreachable part of the map. Might make more sense if the missiles get swapped with a artillery cannon or something.
- Turn it into a dedicated support unit, give it weak weapon or none at all, add a shield on top of the high health and armor and make the suppress effect do something against units.

**Comment by itcannotbe** [comment]
Stop turtling and start actively attacking.

**Comment by Larofeticus** [comment]
> It's not a good idea from game design for quells to be the answer to quells for reasons i shouldn't have to explain.

You may actually need to explain that; awareness of this fundamental principle sometimes seems to be missing in the target audience.

**Comment by Larofeticus** [comment]
Also, the regen supression field is useless. The most a regen projector could accomplish is 333 hp per second behind 20 armor. An attack by a player (not the 2 units at a time campaign ineptitude) will crush that. One bastion worth of locus will crush that.

**Comment by Eclipse-04** [comment]
get an affict bozo
