### ISSUE TITLE
World category

### ISSUE THREAD

**Issue by one-Home-cat** [Anuken/Mindustry-Suggestions#4316]
### Describe the content or mechanics you are proposing.

A class of items that can be interacted with, but not attacked by either party

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More gameplay with the world processor, and more fun with pvp maps!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Dangleos** [comment]
Like a team?

**Comment by one-Home-cat** [comment]
> Like a team?

emmm....You can understand it this way! But it's not all right, it's a special team, it has to be able to not be attacked by any team and it has to be able to interact with any team. Feels a little hard to pull off, doesn't it?
