### ISSUE TITLE
Technology sharing

### ISSUE THREAD

**Issue by LordTylers** [Anuken/Mindustry-Suggestions#4317]
### Describe what you would like changed, and why.

Say you are a new player right, fresh to the game and you have no clue what you are doing because this may be your first automation genre game. A friend who has over 50+ hours and has pretty much everything unlocked comes in and gives you everything because of sharing progress, it ruins the new players grind mood for the game and makes it so the new player does not want to play since they already unlocked everything. 

### Describe the changes you want to propose. Include possible alternatives.

I would like this to be a feature to where whenever someone joins a host that is new, or the host is someone that has many hours. Make a button that turns off technology sharing and campaign sharing. also a restart campaign button would be a good idea too, just some ideas for thought!

**Comment by CLUET-op** [comment]
You can just delete only your tech tree progress in the settings.
