### ISSUE TITLE
Unloader: mutli-filter

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#432]
**Describe what you would like changed, and why.**

i have been playing around with the forbidden campaign, and it feels as though the unloader could benefit from a multi-filter setting instead of just all/one.

![Screen Shot 2020-08-24 at 16 55 34](https://user-images.githubusercontent.com/3179271/91063249-0b424d00-e62e-11ea-94bd-775224897c74.png)

**Describe the changes you want to propose. Include possible alternatives.**

allowing you to set multiple unloader filters, no idea how this will impact existing schematics or the center color texture, but by selecting the ones you need you can avoid looping all your core resources as shown above, of course you can use alternative means like only having the items in the storage block that you want to cycle or use a bunch of filters, but that seems like a mild overhead, so i'm just throwing this in here 🍿 

> or maybe the ability to control the filter item via the new logic item instead of having multiple unloaders toggled?

**Comment by itcannotbe** [comment]
I think this is better suited to logic but make an indicator that the unloader is controled by logix.

**Comment by potatoisagender** [comment]
quezler wtf is this 
![image](https://user-images.githubusercontent.com/63363206/91064804-fb564900-e5ec-11ea-8c55-316e8da7d6be.png)

**Comment by Quezler** [comment]
that is called coal, all resources are allowed in the core in 6.0 🔥

**Comment by Quezler** [comment]
base pic for context of it being attached to the core:

![Screen Shot 2020-08-24 at 17 39 32](https://user-images.githubusercontent.com/3179271/91065470-cbc93000-e630-11ea-8338-88e9292369a7.png)

**Comment by potatoisagender** [comment]
thats a thing? huh. Maybe I should beta test 6.0 then.

**Comment by potatoisagender** [comment]
speaking of unloaders, why does 1 unloader provide slightly less than a titanium belts worth of stuff?

**Comment by DeltaNedas** [comment]
seems far too complex, just use multiple unloaders

**Comment by HaphLife** [comment]
1) Is changing the filter possible with logic?
2) If so, it’d be nice if we could unlock them in the tech tree (perhaps they would be after message blocks, since they are in the same category)
3) defo agree with potatoisagender, unloaders should unload at titanium belt speed (at *least*, faster would be nice.), and be affected by overdrive

**Comment by sample-text-here** [comment]
I agree. There should be an advanced sorter and unloader - instead of selecting one item, you can select multiple.

**Comment by DeltaNedas** [comment]
routorio vulcan router controllable by logic processors
