### ISSUE TITLE
mod restart

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#4320]
### Describe the content or mechanics you are proposing.

When you download a mod and immediately  disable it the game restarts.
When you enable and disable a mod, changing nothing in the proccess, the game restarts.
When you delete a disabled mod the game restart.
Don't forcefully restart the game. 
A message is enough

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's really annoying

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Epicgamer173** [comment]
It would be even worse if they didn’t restart the game forcefully, such as lag, because mines a new lines of code to the pre-existing code which of the game Has to take time to realize that it’s there and can’t (if it didn’t restart) because it’s running the same lines of code over and over and now there is some new lines of code, so it will try to run them which can make your game bug out and lag

**Comment by stuffyAI** [comment]
This bravely assumes that there is no downside to not restarting?

Also, this seems like a user issue, don't make changes without making changes. This should not happen often enough that a 5 second restart kills you (don't be a psychopath and download mods one by one too).

**Comment by Epicgamer173** [comment]
You missed the point, they can’t because it would kill your device more then if it restarted
