### ISSUE TITLE
New block type: multicrafter (internal name)

### ISSUE THREAD

**Issue by Evo04Taser** [Anuken/Mindustry-Suggestions#4321]
### Describe the content or mechanics you are proposing.

Add a crafter that can accept a wide variety of items and "converts" them to (a) different item/s.
Here's what it'll look like when modding with hjson: 

type: Multicrafter
name: Blast Furnace
input: {
  [
    copper: 1
    lead: 4
  ]
  [
    graphite: 2
    silicon: 2
  ]
}
output: {
  [
    titanium: 2
    slag: 1
  ]
  [
    thorium: 1
  ]
}

The first set of input/s (1 Copper and 4 Lead) corresponds with first set of output/s (2 Titanium and 1 unit of Slag). The second set of input/s (2 Graphite and 2 Silicon) corresponds with second set of output/s (1 Thorium). And so on if you add more inputs and outputs. What i call "(a) set" is items and/or liquids inside brackets or [].
    

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'll make the crafters have more options of inputs and outputs, which opens up a lot of possibilities for modders. 

Anuke(n) doesn't need to add blocks that have this type of block, this suggestion is mostly for modders.

Before you say "do it yourself in java mod," I'd humbly like to say that idk how to do Java. I already had enough with commenters ruining my posts. Idc even if the whole Mindustry community is against me -.-

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Eclipse-04** [comment]
bro can't just script

**Comment by Evo04Taser** [comment]
> bro can't just script

im not a coder what did you expect

**Comment by Slotterleet** [comment]
There's literally a library for that. Works with all languages

**Comment by Eclipse-04** [comment]
> > bro can't just script
> 
> im not a coder what did you expect

stupidity and laziness

**Comment by Evo04Taser** [comment]
> > > bro can't just script
> > 
> > 
> > im not a coder what did you expect
> 
> stupidity and laziness

thx bullcrap i appreciate it

**Comment by Evo04Taser** [comment]
> > > bro can't just script
> > 
> > 
> > im not a coder what did you expect
> 
> stupidity and laziness

thx bullcrap i appreciate it

**Comment by Evo04Taser** [comment]
> There's literally a library for that. Works with all languages

wdym and where

**Comment by Eclipse-04** [comment]
> > bro can't just script
> 
> im not a coder what did you expect

if you have 0 programming experience then stop making suggestion about it and go get some first.
i assume you don't know how most of programming works and how'd this suggestion (and many others) affect the game source, because from all the suggestions you've made so far.
