### ISSUE TITLE
Network protocol documentation

### ISSUE THREAD

**Issue by SachaTending** [Anuken/Mindustry-Suggestions#4322]
### Describe the content or mechanics you are proposing.

Documentation about network protocol

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Community can create chat apps for Mindustry, bots for auto administrating, etc.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheEt1234** [comment]
there is already documentation on it,
you can find it by searching "mindustry core api" in a search engine

**Comment by SachaTending** [comment]
i mean
information about packets
how it sends
why using both tcp and udp

**Comment by end-me-please** [comment]
chat apps and auto moderating seems like something you can do with regular plugins

also, the game is open source
you can just look at the netcode

TCP and UDP are commonly used together for video games
TCP for reliable things and UDP because it’s faster (for things like player position, if a packet gets lost, it would be useless anyways by the time it gets resent)

**Comment by SachaTending** [comment]
i checked packet send by game when joiniing

00 69 03 00 63
this is only 5 bytes of packet, rest of packet contains some private info(ex: uuid)
00 - idk
69(105) packet length, captured packet size is 107, 107 - 2(00 and 69) = 105
03 - packet id(ConnectPacket)
00 and 63 - idk
