### ISSUE TITLE
Removal of thorium and carbide from campaign loadouts

### ISSUE THREAD

**Issue by DX-36** [Anuken/Mindustry-Suggestions#4323]
### Describe what you would like changed, and why.

Post-carbide sectors are very underwhelming in terms of difficulty.

I'm pretty sure neither **hhh i 17** (created caldera & _siege_) nor **mechanical fishe** (created karst & _origin_) intended that the player be able to jump straight to T4s before getting access to thorium in their maps, and that's why I made this suggestion.
(Looking at you, epowerj, who I'm pretty sure added the thorium and carbide in the loadouts)

Why remove thorium and carbide from the loadouts?

- The current design of siege and origin restrict the player from collecting thorium until they are able to expand far enough.
- One important part of the erekir campaign is the inability to launch support in terms of resources from other sectors, but the loadouts somewhat negate that.
- T1 & T2 units will need to be used to push into thorium.
- No more progression skipping in the later sectors.
- Pyrolysis can't be rushed early, and thus usage of CCC will be seen.
- Origin less likely to become "quell spam fest".
- Maybe T3 units will also be seen since players will have to **_actually produce carbide_**.
- Post-carbide sectors become a lot harder.
- Can launch from basin to origin.
- Better prepares people for attack servers.

### Describe the changes you want to propose. Include possible alternatives.

Conclusion: by removing thorium and carbide the campaign would benefit a ton in terms of difficulty.
This suggestion could also be applied to the starting tungsten and oxide in stronghold.

**Comment by Mechanicalfish** [comment]
I agree
