### ISSUE TITLE
new planet

### ISSUE THREAD

**Issue by Mrcactusic228q** [Anuken/Mindustry-Suggestions#4325]
### Describe what you would like changed, and why.

Zagrava's satellite is a small moon, on the surface of which many crystals have been found, which form useful resources.
The Highland moon is a mountainous moon with a high plateau and strong winds that move quickly along its steep, rocky, rather low-lying plains.
Hemlock's satellite is a forest moon covered in dense vegetation and rich in biodiversity. There are many animals that lead their own way of life, and plants this month can be used to produce biofuel.
The moon Scotia is a moon with large lava lakes that can be used as a source of energy. There are also various rocks on the surface of the moon that can be used for the production of building materials.
The name of a gas planet that has these four moons could be, for example, Terrano.

### Describe the changes you want to propose. Include possible alternatives.

im create arts to moons and Planet)

**Comment by DX-36** [comment]
just make a mod for this
we aren't getting a new planet

**Comment by Slotterleet** [comment]
~~Sounds like a concept for a yet another multi-planet mod that with 99% chance will be abandoned mid-dev~~

**Comment by end-me-please** [comment]
frogs
