### ISSUE TITLE
Dedicated serves

### ISSUE THREAD

**Issue by mojokelp** [Anuken/Mindustry-Suggestions#4326]
### Describe the content or mechanics you are proposing.

Add opportunity to create Dedicated Servers in the game

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This's will add 1 way how to create an open server 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Listed servers are servers being ran by community members which adheres to certain guidelines.

The normal game client can already be run as a server. There is simply no need for this, as dedicated server is just the game but without the code and files needed to display graphics.

**Comment by TheEt1234** [comment]
> Add opportunity to create Dedicated Servers in the game
there is already the "host server" button thingy

**Comment by end-me-please** [comment]
Should anuke ever add dedicated servers, he should put the server download button right next to the game download button.

and maybe call the file "server-release.jar".

**Comment by TheEt1234** [comment]
> Should anuke ever add dedicated servers, he should put the server download button right next to the game download button.
> 
> and maybe call the file "server-release.jar". 
> 

Ohh yea, he should really do that i think

**Comment by Jaeyun21** [comment]
Use an app called zerotier
