### ISSUE TITLE
Disabling Disable Mods on startup crash if its infinitely crashing

### ISSUE THREAD

**Issue by yoehanpleaser** [Anuken/Mindustry-Suggestions#4328]
### Describe the content or mechanics you are proposing.

I recently had a problem and still to this day February 22 2023 I'm still dealing with its about the damn mods that keeps making me crash cause I just turned off Disable Mods on Startup Crash basically how I want this to work is for the zip file on itch.io to have a Turn Off Disable Mods On Startup Crash on the first page of that Zip. Version right next to the Mindustry app. Deleting the mod on steam is fine but itch.io I have no clue how to turn it off please add this in the next Mindustry version.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help people to not search a fuck ton of pages and stuff cause they did a mistake they should have not like I did

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by yoehanpleaser** [comment]
trello and read.md yes I checked and wiki maybe yes or no

**Comment by Slotterleet** [comment]
If you decided to disable that option, you should've been aware of possible future mod-related crashes. Try deleting the last mod(s) you've downloaded from the game folder, maybe it'll solve your problems?

**Comment by itcannotbe** [comment]
This is why disabling safety features is something that is not recommended.

Also you can't get yourself out of this one via your suggestion, for obvious reasons.

**Comment by itcannotbe** [comment]
Also what did you even think disabling "Disable mods on startup crash" even do? Gives you access to cheats? Makes you OP?

**Comment by TheEt1234** [comment]
> Also what did you even think disabling "Disable mods on startup crash" even do? Gives you access to cheats? Makes you OP?

its convenient for modders ~~and for people like me who really dont want to investigate a crash which happens seemingly randomly on startup~~

**Comment by TheEt1234** [comment]
> Also what did you even think disabling "Disable mods on startup crash" even do? Gives you access to cheats? Makes you OP?

its convenient for modders ~~and for people like me who really dont want to investigate a crash which happens seemingly randomly on startup~~

**Comment by CLUET-op** [comment]
Go to the models folder and delete all the mods or the one who's causing the crash if you know, then just reopen Mindustry and enable the "**Disable mods on startup crash**".
