### ISSUE TITLE
Balancing antumbra and eclipse

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#433]
**Describe what you would like changed, and why.**
Currently based on a lot of tests, eclipse is arguably worse then antumbra because of it's weapons, it has a peak DPS (Damage per second) of 660, verus the antumbra's 596, but with the eclipse, half of that DPS (330) is on the flamethrowers, 22 DPS is on the artillery in the back, and 110DPS is on the lasers. So the eclipse has the problem of most of it's damage being done by a weapon with a miniscule 7.5 block range, as well as the massive variety in weapon effectiveness distances, with the eclipse losing half of it's DPS if the flamethrower is out of range, and so on, versus both antumbra guns reaching to around 26 blocks. The other thing is that in practical testing, antumbra has been proven to actually kill a surge wall faster then eclipse, and it has a long range. The method I use for calculating a gun DPS is taking the gun "reload" property (which is ticks for reload), then divide the gun damage + area damage by the "reload" property to calculate the damage per tick, then that is multiplied by 60, and due to their being 60 ticks in a second it will end up being an accurate representation of the maximum DPS a gun can have (even with mirrored guns, the reload is doubled for each gun so this calculation works for them as well).

**Describe the changes you want to propose. Include possible alternatives.**
Ideally, the antumbra is nerfed to have lower DPS, the missiles need a less explosion radius (it's currently massive), and the spectre-like guns on it also might need to be modified a bit, antumbra should have a DPS of around 400-500 or just a bit above 500, as it is a long range unit and should stay like that. Then the eclipse should be changed to more of a medium range unit, it would be best to remove the flamethrowers and artillery on it, and replace them with something like blast flak guns like cyclone (though buffed), a lot of small bullet guns, or some lower range spectre guns, and it should have a DPS around 700-1000 which makes up for it's insane price to produce.

**Comment by itcannotbe** [comment]
Units are nowhere near finalize in any shape or form.
Even the start up screen even points this out.

**Comment by Syncinus** [comment]
Yeah, I know that, this is a recommendation on how they should be balanced for the cost and the effectiveness of each of them.

**Comment by Ilya246** [comment]
I say eclipse should have a long-range high-reload high-damage gun

**Comment by Anuken** [comment]
Implemented.
