### ISSUE TITLE
reactivable and "and" and "or" objectives

### ISSUE THREAD

**Issue by Xeononyum** [Anuken/Mindustry-Suggestions#4332]
### Describe the content or mechanics you are proposing.

1. objectives can be reactivated if enabled oprion in it
2. new "and" and "or" objective, and - completes if all parents completed, or - completes if 1 or more parents completed

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

just very useful thing

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by notAXeony** [comment]
@Anuken

**Comment by Anuken** [comment]
Pinging me for suggestions will get you blocked from this repository. Stop.
