### ISSUE TITLE
tecta

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#4335]
### Describe what you would like changed, and why.

Tecta is the most underpowered unit in all of etekir. I have never seen people unironically use it for combat and in compain mode it's obsolete as soon as you get it because you get op quells on the same map. It's not as good at rushing as vanquish, has shorter range than quell and it's shield is creating an illusion of protection

### Describe the changes you want to propose. Include possible alternatives.

Tecta should be a long range unit but possibly not long enough to avoid getting any damage and so only able to attack for as long as it's shield would last.
Or make it good for countering other units

**Comment by Mechanicalfish** [comment]
tecta should have a functional shield

**Comment by adelhamed2006** [comment]
Man I didn't use the tecta once in my 2 years of playing :), I agree anuke should probably buff it.

**Comment by Mechanicalfish** [comment]
> Man I didn't use the tecta once in my 2 years of playing :), I agree anuke should probably buff it.

the tecta hasn't existed for 2 years

**Comment by adelhamed2006** [comment]
> > Man I didn't use the tecta once in my 2 years of playing :), I agree anuke should probably buff it.
> 
> the tecta hasn't existed for 2 years

Just meant that I never used the tecta since the time it came to the game, because I played erekir right when the update came out
