### ISSUE TITLE
Return "Any planet" feature

### ISSUE THREAD

**Issue by GenosixGD** [Anuken/Mindustry-Suggestions#4337]
### Describe the content or mechanics you are proposing.

Bring back the ability to play survival and build maps with blocks from both Serpulo and Erekir. When trying to switch to this mode, there will be a message warning that the game with blocks from both planets will be unbalanced

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Mixed tech maps are very fun to play, and it's very unfair to ban the construction of such maps because of other players' complains. If this is the only problem, then it is enough to put a warning and put the blame on the player for playing in an unbalanced mode

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Your suggestions is the way it was before. Guess what happened.

**Comment by GenosixGD** [comment]
> Your suggestions is the way it was before. Guess what happened.

What

**Comment by end-me-please** [comment]
bruh

**Comment by TheEt1234** [comment]
get real and use foo's client for that
