### ISSUE TITLE
Console outputs JSON

### ISSUE THREAD

**Issue by GioIacca9** [Anuken/Mindustry-Suggestions#434]
Add an option in the server's config to change the console output from "human-readable" to a JSON object so any programming language can easily read the output from the console.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This is simply not going to happen. It's a *massive* amount of work.
