### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by History24** [Anuken/Mindustry-Suggestions#4340]
### Describe the content or mechanics you are proposing.

Заводы должны работать по-другому. Они не должны начинать работу только после того, как все ресурсы будут в нем в полном объеме. Ибо по логике завод не работает сразу с кучей сырья, он должен использовать сначала определенную часть и затем всю остальную. Например если заводу нудно 2 меди для изготовления чего-то, а у него есть только 1 медь, он может начать работать с ней, пока вторая медь уже на подходе, после чего завершить со второй частью меди.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Это ускорит и продинамиьизирует значительно геймплей, к тому же игра станет чуть реалистичнее.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by CLUET-op** [comment]
Remember this is a game (not everything could be made real) and this feature is hard too implement in reality. And you will just get the final product in less than ½ seconds for most factories as soon as resource requirement is met (not much impact on gameplay).
