### ISSUE TITLE
units control

### ISSUE THREAD

**Issue by infin251** [Anuken/Mindustry-Suggestions#4342]
### Describe the content or mechanics you are proposing.

hello! I would like to return the command center, because in different situations it can help a lot, example: you have a tense situation, let's say in the PVP and you have the problem of unit command is added to a bunch of problems, then when controlling the unit through the possibility of commanding in V7, the selected units will ignore the command center because the new control is not the most convenient, I hope that I clearly stated my idea because I used the translator as I speak Russian. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

my suggestion if it is added to the game will simplify the command of units

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
- [x] I have NOT read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by infin251** [comment]
I read README but I didn't find any mention of returning control center from v6 and earlier versions or updating unit management🤔

**Comment by TheSerjio** [comment]
![image](https://user-images.githubusercontent.com/84933638/222242160-fe928e87-a7b8-4628-a7d0-57eceacc58ca.png)

**Comment by infin251** [comment]
uh, Google website translate is bad:(

**Comment by eggbanana173** [comment]
> ![image](https://user-images.githubusercontent.com/84933638/222242160-fe928e87-a7b8-4628-a7d0-57eceacc58ca.png)

XD
