### ISSUE TITLE
Server Favorites

### ISSUE THREAD

**Issue by JamesTDG** [Anuken/Mindustry-Suggestions#4346]
### Describe the content or mechanics you are proposing.

Implement a way to add servers in the server browser to your favorites

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will save time trying to just quickly join a certain server you wish to play on, especially as more server networks bring up more servers 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JosXa** [comment]
Just came here to post this same feature request. Could we reopen?

**Comment by JamesTDG** [comment]
@JosXa I will open a new issue that revises this momentarily
