### ISSUE TITLE
Bring back mix tech

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#4348]
### Describe what you would like changed, and why.

I think the <any> (mixed tech) button should be brought back because maps with just one planet is boring for all us actually good players mix tech just gives us what you could call tier 3 production and some units for more fun and creative ways to play the game

### Describe the changes you want to propose. Include possible alternatives.

Re-enable the any or mixed tech button

**Comment by Slotterleet** [comment]
No.

**Comment by Bottinator22** [comment]
if you do get mixtech back, don't complain about the horrible balance, or the situational blocks that end up completely useless, or the fact that some blocks are just plain better than the other planet's version despite not being much more expensive

**Comment by Sector171** [comment]
Pfff I don't understand why some people object on an optional thing like this.

It is mapper choice, balancing is the mapper task, if he couldn't do that the map could be bad. We saw many mixtech map well balanced(Makise) and creative.

If someone don't like mixtech, he can simply ignore these maps, no one will force him to play them. All formal map not mixtech. It is that simple.

Also people always ask for a way to make mixtech, and actually they find a way, but it is just make the thing boring.

Anuke can make it a hidden feature needs using console to activate it, if he doesn't want to encourage this type of maps.
In my mobile I have the latest custom build which was supporting mixtech(23093 I think) just in case I wanted to do one, why this?? Just let's it available, but hide it to not encourage people.

**Comment by BlueWolf3682** [comment]
> actually good players
ok lmao
> make the game enjoyable
i prefer erekir by itself, superior planet
> don't complain about the horrible balance
oh they will and they will be incessant
> hidden feature that needs using console
youre on the right track, but im not gonna openly tell you

**Comment by TheEt1234** [comment]
There is still mixtech, you just have to figure out how to enable it

**Comment by XxsuperdeadlysniperxX** [comment]
> > actually good players
> 
> ok lmao
> > make the game enjoyable
> 
> i prefer erekir by itself, superior planet
> > don't complain about the horrible balance
> 
> oh they will and they will be incessant
> > hidden feature that needs using console
> 
> youre on the right track, but im not gonna openly tell you

Eh everyone has their own opinions

**Comment by XxsuperdeadlysniperxX** [comment]
> ### Describe what you would like changed, and why.
> 
> I think the <any> (mixed tech) button should be brought back because maps with just one planet is boring for all us actually good players mix tech just gives us what you could call tier 3 production and some units for more fun and creative ways to play the game
> 
> ### Describe the changes you want to propose. Include possible alternatives.
> 
> Re-enable the any button or mixed tech button

**Comment by XxsuperdeadlysniperxX** [comment]
> There is still mixtech, you just have to figure out how to enable it

The button that we use to create mix tech maps is disabled for the moment

**Comment by Bottinator22** [comment]
> > There is still mixtech, you just have to figure out how to enable it
> 
> The button that we use to create mix tech maps is disabled for the moment

there's a method, it's called the console
this is an open-source game with a console that basically lets you change every aspect of the game
why not go and figure it out if you so want mixtech?

**Comment by XxsuperdeadlysniperxX** [comment]
> > > There is still mixtech, you just have to figure out how to enable it
> > 
> > The button that we use to create mix tech maps is disabled for the moment
> 
> there's a method, it's called the console
> this is an open-source game with a console that basically lets you change every aspect of the game
> why not go and figure it out if you so want mixtech?

I don't code so java script is Foreign to me

**Comment by code-explorer786** [comment]
> there's a method, it's called the console
> this is an open-source game with a console that basically lets you change every aspect of the game
> why not go and figure it out if you so want mixtech?

I get your point, but you can't just assume that everyone _can_ do that sort of thing and _will want to_ do. This isn't a community full of programming nerds.
(After a couple months off Mindustry, I've realized this.)

Unless someone actually makes a tutorial that's easily accessible, your point isn't really helpful at all.
(Or maybe, a mod that removes the mixtech restriction.)

**Comment by itcannotbe** [comment]
> > there's a method, it's called the console
> > this is an open-source game with a console that basically lets you change every aspect of the game
> > why not go and figure it out if you so want mixtech?
> 
> I get your point, but you can't just assume that everyone _can_ do that sort of thing and _will want to_ do. This isn't a community full of programming nerds. (After a couple months off Mindustry, I've realized this.)
> 
> Unless someone actually makes a tutorial that's easily accessible, your point isn't really helpful at all. (Or maybe, a mod that removes the mixtech restriction.)

I get your point, but the point of having a wall is so that everyone will not easily access something they have a high chance to complain about.
This is not a community full of people who takes time to read instructions, descriptions, warnings and disclaimers. (After a couple years of Mindustry, I've realized this.)

**Comment by itcannotbe** [comment]
> > > actually good players
> > 
> > 
> > ok lmao
> > > make the game enjoyable
> > 
> > 
> > i prefer erekir by itself, superior planet
> > > don't complain about the horrible balance
> > 
> > 
> > oh they will and they will be incessant
> > > hidden feature that needs using console
> > 
> > 
> > youre on the right track, but im not gonna openly tell you
> 
> Eh everyone has their own opinions

It's not even an opinion if they are actually facts.

**Comment by XxsuperdeadlysniperxX** [comment]
> > there's a method, it's called the console
> > this is an open-source game with a console that basically lets you change every aspect of the game
> > why not go and figure it out if you so want mixtech?
> 
> I get your point, but you can't just assume that everyone _can_ do that sort of thing and _will want to_ do. This isn't a community full of programming nerds.
> (After a couple months off Mindustry, I've realized this.)
> 
> Unless someone actually makes a tutorial that's easily accessible, your point isn't really helpful at all.
> (Or maybe, a mod that removes the mixtech restriction.)

It was sarcasm lol

**Comment by XxsuperdeadlysniperxX** [comment]
> > > there's a method, it's called the console
> > > this is an open-source game with a console that basically lets you change every aspect of the game
> > > why not go and figure it out if you so want mixtech?
> > 
> > I get your point, but you can't just assume that everyone _can_ do that sort of thing and _will want to_ do. This isn't a community full of programming nerds. (After a couple months off Mindustry, I've realized this.)
> > 
> > Unless someone actually makes a tutorial that's easily accessible, your point isn't really helpful at all. (Or maybe, a mod that removes the mixtech restriction.)
> 
> I get your point, but the point of having a wall is so that everyone will not easily access something they have a high chance to complain about.
> This is not a community full of people who takes time to read instructions, descriptions, warnings and disclaimers. (After a couple years of Mindustry, I've realized this.)

The people who complain are usually people who haven't a single map a day in their lives and also some players that do complain in mindustry don't use their brains before they post the stuff they type
