### ISSUE TITLE
Liquid sorter called "filter"

### ISSUE THREAD

**Issue by jolitalk** [Anuken/Mindustry-Suggestions#435]
**Describe the content or mechanics you are proposing.**
It's like a sorter, but for liquids

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Easier liquid sorting 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> Easier liquid sorting

Are you implying that you use the same pipe for multiple liquids? That's not how liquids work. This doesn't make any sense.

**Comment by hortiSquash** [comment]
> > Easier liquid sorting
> 
> Are you implying that you use the same pipe for multiple liquids? That's not how liquids work. This doesn't make any sense.

![image](https://user-images.githubusercontent.com/45213805/120012716-28061980-bfe0-11eb-8a14-ba48e99c1bee.png)
i think they meant something alike

**Comment by Anuken** [comment]
That *is* using the same pipes for multiple liquids, which, again, doesn't make any sense.

**Comment by Kyllingene** [comment]
oh noes

you brought this upon yourself
