### ISSUE TITLE
Small UI change on the CORE Database

### ISSUE THREAD

**Issue by Ruyeex** [Anuken/Mindustry-Suggestions#4354]
### Describe what you would like changed, and why.

I would like to differentiate the serpulo and erekir sections with different colors or different symbols for clarity on the UI and seperate with labels of sectors of each planet
![image](https://user-images.githubusercontent.com/99507424/224855883-e8542a73-243e-46bb-be86-600e77219cd8.png)

### Describe the changes you want to propose. Include possible alternatives.

It would be easier to distinguish the levels of serpulo and erekir without the need to check.

**Comment by TheEt1234** [comment]
that would be awesome
