### ISSUE TITLE
Custom icon string for players

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry-Suggestions#4357]
### Describe the content or mechanics you are proposing.

Instead of only having an icon top right of your name when you are an admin, allow servers to set a string, like player.name, that is only for icons. If a player is admin, player.icons = Iconc.admin, if player is discord verified, player.icons = "[royal]" + Iconc.discord, if admin and discord, players.icons = Iconc.admin +  "[royal]" + Iconc.discord.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Servers wont have to have a billion different icons left of name to specify rank, verification status, or whatever.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Darkness6030** [comment]
This can easily be implemented and i'll try to do so

**Comment by L0615T1C5-216AC-9437** [comment]
Thanks, hopefully Anuke will merge once its done.
