### ISSUE TITLE
Underground Conveyors 

### ISSUE THREAD

**Issue by LiamDonohue** [Anuken/Mindustry-Suggestions#436]
I am proposing Underground conveyors, kinda like a reverse bridge conveyor.  This would be very useful for going under walls and stuff. it could also increase bridge conveyor usefulness, as you could place a bridge conveyor above a underground conveyor.

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
If you actually do read.........

A few things you shouldn't suggest
These have been proposed many times already, and I won't be adding them.

    Underground map layers

**Comment by Anuken** [comment]
> this would be very useful for going under walls and stuff.

You can go *over* walls with a bridge conveyor.

> you could place a bridge conveyor above a underground conveyor.

You can place bridge conveyor above another bridge conveyor. This brings nothing new to the game.
