### ISSUE TITLE
Erekir.Origin may encourage Neoplasm invasion if enemy water network was more well-connected

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#4363]
Suggestion/Idea: make the "Origin" mission on Erekir reward those players who plant Neoplasm into enemy bases (by dropping Neoplasm containers as payloads). 

Motivation: Just to add variety to the player's available strategies. 

Currently, each enemy base in Origin has 3/4 seperated water networks, making Neoplasm invasion less effective. I'm suggesting changing the map so that the enemy base has more well-connected water networks.

**Comment by AzhurniyBaklan** [comment]
that'd be quite a lot of clowning, I like this

**Comment by Daniel-Chin** [comment]
More thoughts: if a ship crashes with Neoplasm payload, it should spawn ground-neoplasm, just like how ozone-loaded ships explode on crash.
