### ISSUE TITLE
accounts with saved progress

### ISSUE THREAD

**Issue by VoID-192** [Anuken/Mindustry-Suggestions#4369]
### Describe the content or mechanics you are proposing.

why not add accounts in order to save your gameplay without fear of losing it. I imagine it like this: you go into the game and by clicking on "multiplayer game" you can under in the text field for the nickname, click on "register or log in" and then enter the email and password with the nickname when you log into your account or the same as when you log in only with a password repetition. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

No need to worry about losing progress or losing schemasNo need to worry about losing progress or losing schemas

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why not read the read me. Bruh.

**Comment by itcannotbe** [comment]
- [X] I have **not** read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Built-in cloud sync

**Comment by TheEt1234** [comment]
rtfr

r - read
t - the
f - fabulous
r - readme
