### ISSUE TITLE
Sorter cross: item source edition

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#437]
**Describe what you would like changed, and why.**

Currently the sorters display a grey line/cross texture when nothing is selected, it would be nice to have it for item sources to.

**Describe the changes you want to propose. Include possible alternatives.**

i'd like the item sources to also use such a cross texture, i've just been playing with reconstructions and silicon is invisible ^

**Comment by sample-text-here** [comment]
Also liquid sources should have the texture

**Comment by Quezler** [comment]
well for liquid sources its a little more obvious, but i support the idea for consistency 🙂

**Comment by Anuken** [comment]
Implemented.
