### ISSUE TITLE
Would like a modding wiki or a app for making mods for the game without knowing how to code cuz i cant code

### ISSUE THREAD

**Issue by penguip** [Anuken/Mindustry-Suggestions#4373]
### Describe the content or mechanics you are proposing.

don't know what to put here

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this could also help others too

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MEEPofFaith** [comment]
No coding experience is required for modding.
Usually the #modding-general channel of the discord can answer questions.
There's also the modding info in the wiki https://mindustrygame.github.io/wiki/modding/1-modding/.

**Comment by NemesisTheory** [comment]
> cuz i cant code

😬

**Comment by code-explorer786** [comment]
> > cuz i cant code
> 
> 😬

you don't necessarily code, you can use JSON (a data format, *not code*) for representing how you want your stuff in-game.

**Comment by penguip** [comment]
thx guys but I'mma explain what i was needing: when i was inserting a image nothing happened and when i tried something else it said "unable to render rich display invalid image source". so i really just need to know how inserting images works on mobile or just how it works in general
