### ISSUE TITLE
Flush message to each player individually [world processor]

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4374]
### Describe the content or mechanics you are proposing.

Add an option to specify a player reference in the 'message' instruction for world processors.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow map makers to give every player different messages. Such as custom stats, or individual objectives. I think it would make multiplayer stuff easier for some more complex minigames and maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genialnos** [comment]
i wonder: how you will know that specific person join specific server with a specific map? better to be for each team.
