### ISSUE TITLE
Block Sub Categories

### ISSUE THREAD

**Issue by JP16D** [Anuken/Mindustry-Suggestions#4376]
### Describe what you would like changed, and why.

Block Selection Menu is now filled by alot of blocks and it's getting a bit hard to keep track where are the blocks you need sometimes

### Describe the changes you want to propose. Include possible alternatives.

Adding Sub Categories for each Block Categories should make it more organized and easier to keep track e.g.

• Turret Category
  - Burst Turrets (duo, salvo, etc.)
  - Anti-Air Turrets (scatter, cyclone etc.)
  - Laser Turrets
  - ...
• Crafting Category
  - Smelters (crucible, klin, etc.)
  - Utility (melter, pulverizer, etc.)
  - Heat (phase heater, etc.)
  - ...

Here's some example layout I made using some photo editing:

![Polish_20230404_235513167](https://user-images.githubusercontent.com/77716064/229850616-9eb6ab6d-e7cd-4017-9c1f-04d213621735.jpg)

Edit:
Oh and btw assuming this gets added there should be a default sub cat named "Others" so it's just less hassle to define one everytime we make a new block in mods

**Comment by itcannotbe** [comment]
This is just a part of the learning curve, you'll soon be annoyed that you have to scroll down to select the block you need and this will mess with keyboard hotkeys some players are already too familiar to.

**Comment by JP16D** [comment]
> This is just a part of the learning curve, you'll soon be annoyed that you have to scroll down to select the block you need and this will mess with keyboard hotkeys some players are already too familiar to.

I'm in mobile so it's already annoying to scroll down and not find the block because it's confusing and some blocks looks the same (like coal centri and plast comp)

Also maybe it could become optional though that's going to be additional work so it will probably not happen if this is approved but anyways this is just a suggestion for easier searchability of blocks

**Comment by JP16D** [comment]
Also anyways this is going to be very beneficial for new players to not overwhelm them with confusion on where to find each blocks, and for old players it's not at all going to have a bad impact even if they're used to the keyboard hotkeys (if they're not on mobile) as it's going to be much easier to navigate the blocks your looking for as they're now more organized
