### ISSUE TITLE
make PvP(attack) more balanced with t2 resources (copper, lead,coal,sand,titanium)

### ISSUE THREAD

**Issue by genialnos** [Anuken/Mindustry-Suggestions#4378]
### Describe what you would like changed, and why.

T2 PvP (basically without thorium) is not balanced. because, while defense at maximum can be cyclones or swarmers. but attackers is T2 units that are mostly melee. And they get easily destroyed. basically defense is superior to attackers.

### Describe the changes you want to propose. Include possible alternatives.

to combat this, change in multiplicative reconstructor recipe. instead of thorium(650) add plastanium (200-250)

**Comment by octopuscaat** [comment]
... that would make it HARDER to make t3...
