### ISSUE TITLE
Плазма

### ISSUE THREAD

**Issue by Survivor69** [Anuken/Mindustry-Suggestions#4379]
### Describe the content or mechanics you are proposing.

Есть такая жидкость вырабатывающая как побочный продукт из реактора, так вот у меня есть идея, пушка которая в качестве топлива использует плазму и  озон в качестве ускорителя. Стреляет 5 мощными залпами лазеров  в небольшом диапазоне, которые поджигают врагов. И также при заправке его торием то 4 мини пушки  по бокам стреляли бы по воздушным целям

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Эта пушка добовляет интереса и так же с ее помощью можно разнообразить выбор оружия, так же как и применения тория в целом

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Survivor69** [comment]
Im used russian cuz im not best in english, use translator if you want read it

**Comment by KirillRum** [comment]
Кринж, анбалансная дичь, полный бред, если анюк это сделает, то игра будет выглядеть как школо мод для миндастри

(Cringe, unbalanced turret, complete nonsense, if Anuke does this, then the game will look like a schoolboy mod for the Mindustry)
