### ISSUE TITLE
Better debugging support for logic

### ISSUE THREAD

**Issue by SuperStormer** [Anuken/Mindustry-Suggestions#438]
**Describe the content or mechanics you are proposing.**
1. error messages for logic processors, so you don't have to put print statements everywhere to find out why your code isn't running
2. allow the player to view the contents of a memory cell, also to help avoid print statement debugging

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Writing logic programs will be easier.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
ah yes, the old technique of print(the theory of everything)

**Comment by Vortetty** [comment]
the ability to step through code or see what is being executed real time would also be useful, allowing to find accidental infinite loops, etc.
