### ISSUE TITLE
No build tile/ore

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry-Suggestions#4380]
### Describe the content or mechanics you are proposing.

Add invisible tile that doesn't allow building in this spot.
So here will have 2 tiles: the normal visible one such as red stone tile, and the invisible tile(to prevent building in this spot). Visually it will be like other tiles but not possible to build here. If adding 2 tiles in the same spot has deep difficulties, make it invisible ore rather than tile.

The result which I want is no build tile without any visual effect in the appearance in that tile.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Sometimes map maker wants to prevent players from building in specific spots away from the enemy core, without adding obstacles like stone wall or deep water or so.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
While this is a good mapmaking idea, such a tile will leave to frustration and/or confusion for people playing the map as there will be no visible reason why they can't build on a seemingly build able location.

Most people will just send in Bug Reports upon encountering such tile.

**Comment by Sector171** [comment]
It is time matter, they will be used to after a while.
Adding visual "effect" to that tile is ok, but not new design, so if it is dark sand it will stay dark sand with small visual change to inform player that you can't build here.

**Comment by itcannotbe** [comment]
As long that it is not invisible, I think there will not be that much of a problem.

**Comment by rekokoro** [comment]
You can figure it out with world processor.

**Comment by Sector171** [comment]
No thanks, world processor should be used to do specific custom tasks, not global need.
Also this will lead to unnecessary lag, not professional solution.

**Comment by rekokoro** [comment]
I already made a map where every single block is being monitored by several processors, including area with build prevention, different for each team.

**Comment by Sector171** [comment]
> being monitored by several processors

That's what I meant, unnecessary lag.

Anyway would you please give me the map name to see your solution, assuming that you uploaded it in the map channel in discord.

**Comment by rekokoro** [comment]
It's not uploaded cause it's an exclusive map for a server, but you can check it here:
160.16.207.141:2352
