### ISSUE TITLE
Tall Terrain Walls

### ISSUE THREAD

**Issue by NoThx149** [Anuken/Mindustry-Suggestions#4381]
### Describe the content or mechanics you are proposing.

Tall terrain (or mountainous terrain) walls would be a variant to the regular terrain walls. This would prevent air and legged units from crossing it.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be very helpful for mapping, as mappers could restrict units from entering certain locations. For example, if your map was positioned within caves, you wouldn’t want the Core drone or other units going over the walls of the cave, as that kind of defeats the purpose. Same for a mountain range map.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If your purpose if have a cave like setup, why not a gamerule that would prevent units from passing through terrain/environmental walls.

**Comment by NoThx149** [comment]
That could work too
