### ISSUE TITLE
Range Limits on Intersector Blocks

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry-Suggestions#4382]
### Describe what you would like changed, and why.

after you get the launchpad all you need to do is make a warehouse launching station and suddenly you beat the game...halfway through progression
range limits may encourage players to actually worry about their logistics instead of quickly popping over a sector to change destination, as in they would need to build relatively near the target rather than make a cheese base on the other side of the world and just avoid all risk or danger

### Describe the changes you want to propose. Include possible alternatives.

range limits on launch pads similar to cores, and other blocks like launch pads that i forgot or are yet to be implemented
an example being a launchpad with a range limit of 5 sectors in a direction, perferably moddable too.
alternatives could be a limit based on how loaded they are, so you cant launch 10000 thor to the other side of the planet and just ignore mining completely
lastly another option for cores could be that smaller tiers have a higher range or vise versa, to give the shard cores n such an actual use later in the game rather than being instantly irrelevant
and for the eventual accelerator, if there is a form of inter planet launch pad, launch speed could be the window of sectors it could get or "range" of landed sectors, this is of course just assuming that might exist one day as it could very well not

**Comment by itcannotbe** [comment]
Erekir: Not my problem.
