### ISSUE TITLE
Easier range viewing

### ISSUE THREAD

**Issue by Thatguytheman** [Anuken/Mindustry-Suggestions#4387]
### Describe the content or mechanics you are proposing.

I propose to put a circle on the map whenever you are holding a ranged item (mass drivers, turrets etc.) That shows the range of the item.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I feet as though this will be useful as sometimes I am trying to place a mass driver or payload mass driver or a foreshadow, and it is very hard to gauge how big the range extends, especially vertically. I feel as though it would be a nice Quality of Life change and would be nice for people without a lot of screen space.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Are you really suggesting something that is ALREADY in the game for pretty much THE ENTIRE TIME and you freaking didn't notice?

**Comment by Slotterleet** [comment]
![Screenshot_20230411_203658](https://user-images.githubusercontent.com/62336673/231244129-b68cb9a4-a67b-4b0f-9cd8-cc670bdecfd5.jpg)
