### ISSUE TITLE
Cross saving 

### ISSUE THREAD

**Issue by ItsOnlyMe360** [Anuken/Mindustry-Suggestions#4388]
### Describe the content or mechanics you are proposing.

I propose implementing an account system in Mindustry, along with a profile tab that allows players to select and transfer their saved files between devices. The account system would allow players to create an account and log in across different devices, linking their saved files to this account, similar to the game Infinitode. The profile tab would feature a saved file selector, allowing players to choose the file they wish to transfer. Additionally, there would be a transfer confirmation to ensure that players do not lose any local progress during the transfer.
i know that built-in cloud sync is in "A few things you shouldn't suggest" i will do it anyways cause maybe you just need a better enlightenment about this idea

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The implementation of an account system with a profile tab can significantly improve the player experience in Mindustry. This would allow players to play the game on different devices without having to manually transfer saved files. With the ease of saved file transfer, players can switch to a different device without worrying about losing their progress in the game. This can increase player retention and improve the overall user experience. Additionally, the implementation of this feature can make the game more accessible to a wider audience, encouraging more players to try the game on different platforms.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
- [x] You have **definitely not** read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure your idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Let me remind you that the game you are playing is an ad-less, no In App Purchases, and is mostly Free to Play.

And the feature you are requesting requires to maintain something that cost money to maintain.

Maybe you just need a better enlightenment about that.
