### ISSUE TITLE
make mass conveyor overdriveable

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry-Suggestions#439]
**make mass conveyor overdriveable.**

*with this it's possible to transport more units at the same time, that will help in pvp for example, will be possible "compact" units to transport more easily, that again, will help a lot, and it's a mass **CONVEYOR** so make sense, because conveyors are overdriveable.*

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ILiekMelons** [comment]
n

**Comment by itcannotbe** [comment]
I honestly see no point in this. As the time to make the fastest unit to make is multitudes more than the throughput of the mass converyor.

**Comment by rodrigolitzius** [comment]
> I honestly see no point in this. As the time to make the fastest unit to make is multitudes more than the throughput of the mass converyor.

But make sense, did I overdo it a little? Yes, but make sense
