### ISSUE TITLE
Better Fog networking logic

### ISSUE THREAD

**Issue by thedimas3007** [Anuken/Mindustry-Suggestions#4395]
### Describe what you would like changed, and why.

So far when there's Fog on a server it sends the whole map but without enemies' units, that fog can be turned off on the client side via mods/clients.

### Describe the changes you want to propose. Include possible alternatives.

So I'd like that server would not to send the whole world to the players
Benefits from this: on PvP, when Fog is obviously enabled to hide the base, will really hide it from modded/cliented users

**Comment by thedimas3007** [comment]
Maybe just don't send building to players. Send only when they're close to the building. E.g. fog radius is 10 blocks and buildings sent are 12-15 blocks away from the player for better _smoothness_

**Comment by Anuken** [comment]
This is not possible. Blocks are heavily dependent on each other in function, and everything of the sort is simulated clientside. You can't load half a base on the client and expect turrets or transportation to work properly.
