### ISSUE TITLE
Saves and backups 

### ISSUE THREAD

**Issue by H4981** [Anuken/Mindustry-Suggestions#4397]
### Describe the content or mechanics you are proposing.

It could have a partnership with Google play games where it could be done backups from any device

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Will it help players with older accounts get back into the game smoothly or make people feel safer getting back into the game after uninstalling it

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
That is not happening. Please keep in mind that this thing costs money, and you're playing a completely free to play, no ads, and no microtransactions game.

**Comment by octopuscaat** [comment]
there is a data file. you can just save the data file
