### ISSUE TITLE
transmuter

### ISSUE THREAD

**Issue by sheep253454** [Anuken/Mindustry-Suggestions#4399]
### Describe the content or mechanics you are proposing.

 a 1x1 block that turns basic ores (copper, lead scrap, ect) into other basic ores for a 2:1 exchange rate
 the cost is up to you

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

often in the mid game your core overfills and your conveyers clog, this would be helpful paired with overflow node, or if 1 resource is scarce in your map, such as islands and lead  

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083

**Comment by lokyinng** [comment]
that would be too op
