### ISSUE TITLE
Waypoint structure

### ISSUE THREAD

**Issue by Helicaste** [Anuken/Mindustry-Suggestions#44]
**Describe the content or mechanics you are proposing.**

I propose a block that, when the Command Center is set to patrol, creates a basic pathing network for friendly attack drones to follow.

This would also provide a basis for "CoolManAwees" suggestion.

Basic functionality: New command for the Command Center, "Waypoint" which directs troops to follow a path of waypoints from the closest to the Command Center to the furthest away, using normal AI pathing to get there and bypassing a waypoint if it is inaccessible. 

Additionally, multiple Waypoint types are possible.

Ex. A "patrol" waypoint that creates a pathing network between the points in order of placing with a invisible connection that has an arrow graphic displaying which direction the path goes. 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It makes drone-based defenses on maps with more than one exit far more viable. It also makes drone-based defense far more viable overall.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by TNT331** [comment]
lol isen't this the one I posted....
its the same thing...
also to add on to this, command centres should have the ability set to command a amount of unit. you can seleat the type of units you want to controll

**Comment by Helicaste** [comment]
> lol isen't this the one I posted....
> its the same thing...
> also to add on to this, command centres should have the ability set to command a amount of unit. you can seleat the type of units you want to controll

When I ran basic searches through the requests I found only one other post that described "waypoints" and it did not to a great job of it at that.

If you can direct me to YOUR post about this topic, that would be helpful.

In any case, my suggestion here is my description of the waypoints I provided, a specific unit control, number or type, would be interesting as a feature, but I believe the pathing concept here to be more useful as an overall tool, not only would it be helpful in singleplayer for defense, but it would remove the need for junction paths to direct your units.

**Comment by dbryar** [comment]
Plain way points for attack are more necessary in my opinion. At present the units will go directly from their point of manufacture to the first 'accessible' location. Sometimes this takes them via a "valley of death" that the player may want to avoid with a simple way point, which would be good.

That being said, I realise that unit control in 6.0 will be completely different, so it is unlikely this will go much further.
