### ISSUE TITLE
No obvious ways to support the developers

### ISSUE THREAD

**Issue by Raikiri** [Anuken/Mindustry-Suggestions#440]
**Describe what you would like changed, and why.**
I'd like to support the development of the game, but there's no option to do that from in-game (or I could not find it).

**Describe the changes you want to propose. Include possible alternatives.**
 I'd like to buy a supporter pack that does something 100% cosmetic (like, a badge in the main menu). Or an art book, something like that.

Alternatively, Patreon campaign works too, particularly for long-term development.

**Comment by gen-NA-owl** [comment]
You could donate by buying the game through Itch.io, or just buy it on steam. (I know this isn't what your asking for, but just putting it out there)
