### ISSUE TITLE
Mod Dependencies

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry-Suggestions#4401]
### Describe the content or mechanics you are proposing.

Allowing mods to depend on other mods, requiring multiple be installed. This is to make standard community-made tools (such as the mod Mapping Utilities) easier to use, as otherwise, people may forget to install mods others depend on.

EDIT: APPARENTLY THIS IS ALREADY A FEATURE, BUT I DO NOT KNOW HOW IT IS DONE. PLEASE READ BELOW IDK

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

- Helps promote mods "merging" their content, such as 2 materials being named the same and working with one another.
- Helps community-made tools be commonplace

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
I don't think you know about that, dependencies **already exist**. But only mandatory ones, though.
I'd really like some support for optional dependencies...

**Comment by Phinner** [comment]
> I don't think you know about that, dependencies **already exist**. But only mandatory ones, though. I'd really like some support for optional dependencies...

It's already supported. They are just called soft dependencies.

**Comment by overdramaticpanromantic** [comment]
Ah! I didn't know they existed. How are they created?

**Comment by Phinner** [comment]
> Ah! I didn't know they existed. How are they created?

Simply declare them with the `softDependencies` property instead of `dependencies`.

**Comment by overdramaticpanromantic** [comment]
Thanks!

**Comment by SMOLKEYS** [comment]
...close?
