### ISSUE TITLE
Tie building options to core tier

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4409]
### Describe what you would like changed, and why.

It's more aimed on multiplayer balance, but still appliable to singleplayer too. 

I'm proposing to limit availability of building construction to highest tier of core, that's currently placed on map. For multiplayer it'll make sure to keep PvP game mode more balanced by taking awareness of enemy tech progression and'll force to enforce basic production on PvE gamemods before advancing to next tech. On singleplayer... well, I'm not playing it but I think it'll cut down tactic "spawn low-tier core just for resources".   

### Describe the changes you want to propose. Include possible alternatives.

Introduce "required processing power" value for all buildings, ores and liquids and "processing power" for core buildings, both as float variables. If processing power exceeds required processing power, that building becomes available to build and operate. In case of multiply cores, processing power determined from core with highest processing power. Low tier core can accept high tier material but can't use it in construction except for upgrading core. 

As example, in case of Serpulo, core allows to process:
- Shard:
* Graphite
* Silicon
* Pyratite
* Titanium as material (with graphite drills)
* T1-T2 Units
- Foundation:
* Metaglass
* Plastanium
* Blast compound
* Slag, oil and cryofluid
* Thorium as material (with laser drills)
* T3-T4 Units
- Nucleus:
* Phase weave
* Surge alloy
* Airblast drills
* Let use water and oil extractors (cause i hate them XD)
* T5 Units

In case of Erikir:
- Bastion:
* Accept tungsteen as material
* Water processing
- Citadel:
* Accept thorium as material
* Hydro/Nitro/Ozone/Arkycite processing
- Acropolis: 
* Everything else
* Slug/ Cyanogen processing

Mod can define their own tech and materials with own processing power. If items handled in appropriate way like passing r radioactive thorium or heavy surge alloy in copper conveyor, structures starts to slowly deteriorate. In case if highest tier core is broken and processing power lowers, all high tear building ceases operate until the necessary teir core rebuilt.

Also some things for map making - let override default operation power of each building in map settings. Banned units and buildings will get operation power 10 as default value. And add it to a setProp command for world processor to alternate cores and building processing power.

**Comment by Greenlog12** [comment]
God no this sounds like unbalanced garbage

**Comment by octopuscaat** [comment]
question: what is slug?

**Comment by Greenlog12** [comment]
> question: what is slug?

Slag, probably?
