### ISSUE TITLE
Rework votekick

### ISSUE THREAD

**Issue by TheEt1234** [Anuken/Mindustry-Suggestions#4412]
### Describe the content or mechanics you are proposing.

- Allow players to change their opinion
- Allow the initial player to cancel the votekick
  - Allow admins to cancel the votekick
- Argument for votekick reason, required

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allowing the initial votekick starter and admins to cancel the votekick would be great and reduce false votekicks

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
All bad ideas.

The vote kick has a short enough timeout.
