### ISSUE TITLE
Feedback on unit control

### ISSUE THREAD

**Issue by Swagwagon** [Anuken/Mindustry-Suggestions#4416]
### Describe what you would like changed, and why.

You decide what needs change, this is just some feedback.

### Describe the changes you want to propose. Include possible alternatives.

My favorite part of industry is creating fully automatic self sufficient systems, and watching the enemies fail to infiltrate it as I do nothing. In other words, I don't want to do anything, I want to make systems that do things for me. These units that rely on the player for every command just ruin the automozation. I get that you wanted the player to have more to do than just build, but building and problem solving was always the fun part for me. Twice today, I loaded up the game, opened the campaign, saw that I'd have to command units to beat this next level, and then closed the game cuz I instantly lost interest.

**Comment by BlueWolf3682** [comment]
Go play Factorio then. This game will never fit the full automation genre.

**Comment by thedarkundertaker** [comment]
can you fix this, please 
![Screenshot 2023-05-06 11 03 07 AM](https://user-images.githubusercontent.com/110623941/236634759-8ec8a619-2224-435e-a829-eeabe288fc2a.png)

**Comment by thedarkundertaker** [comment]
this has been happening ever since the last update (aka when you added the join via clal link
