### ISSUE TITLE
Unit control, microprocessor guide, unit bridge and AI

### ISSUE THREAD

**Issue by herzzug** [Anuken/Mindustry-Suggestions#4417]
### Describe the content or mechanics you are proposing.

Hello

i just wanted to make two suggestions for improvement

first is about the unit control
i don't want much but that the double tap on player (you) that bonds unit's to you and the shooting gets added again

not to remove the new controlls because there good 

second is to maybe add an tutorial or a guide to the microprocessor because it's difficult too figure out how everything works or just add a info box

please

third is a unit bridge
wenn making maps or in need of getting your units from on side to the other without risking drowning them or the AI just not moving if not connected by land to the core.
like the bridge's for the material just a bit bigger.
wenn both sides connect they would make a bridge that units kann walk over. just give the bridge some length to connect.

fourth is to fix the AI of the core so you kann battle it again where the can replace brocken building or build and attack theme selves again and the unit AI so that they don't just stand There wen there is no enemy core and there land isn't connected to yours what the unit bridge idea came from.

i love mindustry

tanks 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

by making manual attacks will you are a unit with other units easy again like before the neu controls

("not" that the neu controls are to get removed)

and making the luring of how the microprocessor work more easy, so you can use them, cause else they are quite useless if you can't do anything with them because you don't know how they work. 

Get the point I'm hammering?

the unit bridge to close great gap's without changing the land and so the don't just stand There without land connection

and the unit AI so it stops becoming somewhat frustrating

good and last the core AI so you can battle against it again and some advanced controlls for great map making
so you kann still have fun even if you don't have a server or friends to fight against 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by herzzug** [comment]
sorry i meant:
four suggestions and ...
first line of description -> while you're a unit

**Comment by herzzug** [comment]
these are just basic life improvement of in the game 
and the bridge because of the unit AI

**Comment by herzzug** [comment]
danks a lot

**Comment by 5UP3R-D1N** [comment]
1. I cannot understand
2. Have you ever hover/long tap on the action in "Add" menu and read the description?
3. *Payload massdriver*.

**Comment by 5UP3R-D1N** [comment]
4. mods exist

**Comment by herzzug** [comment]
tanks a lot for your answer.
i hope that wasn´t offending, my suggestions.
enjoy your day.


Am Di., 23. Mai 2023 um 12:48 Uhr schrieb 5UP3R_D1N <
***@***.***>:
