### ISSUE TITLE
Allow players to connect to servers if they have campaign mods installed and the server does not have them installed

### ISSUE THREAD

**Issue by JamesTDG** [Anuken/Mindustry-Suggestions#4419]
### Describe what you would like changed, and why.

So, I often am finding myself relaunching the game several times just so I can play a campaign but then switch to MP. It would be as simple as having the game make it so the blocks just don't show up in the GUI (which is already possible with custom maps)

To add on to this, make it so a client on a newer version can connect to an outdated server, it gets annoying having to wait for servers to update just so I can play with others as soon as an update releases. It would get stress off of the backs of server operators too.

### Describe the changes you want to propose. Include possible alternatives.

Already previously mentioned

**Comment by itcannotbe** [comment]
> To add on to this, make it so a client on a newer version can connect to an outdated server, it gets annoying having to wait for servers to update just so I can play with others as soon as an update releases. It would get stress off of the backs of server operators too.

The server isn't the problem in this case. It's the client.

In order for this to work, the client needs to have unnecessary (obsolete) data and/code to support older versions.
