### ISSUE TITLE
New Block: The Build jammer

### ISSUE THREAD

**Issue by bsjohnson20** [Anuken/Mindustry-Suggestions#442]
**Describe the content or mechanics you are proposing.**
A block that requires a constant amount of cooling or other to prevent spamming it easily. It can be only added inside the preexisting core no-build radius to extend it further, it could display slightly differently to the normal no-build radius to differentiate between them. The device could prevent spamming enemy conveyors and cheap blocks inside a defence where there are holes or gaps as spamming conveyors is an effective strategy especially if arcs are near as it'd consume a lot of power.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Less spamming of cheap blocks inside PVP to distract a defence and waste resources as copper conveyors can waste a lot of resources for the defence. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ayangd** [comment]
Instead of the build jammer, I think the build range should be smaller than normal. Then, when building outside the range, the player should be automatically moved near the building.

**Comment by DeltaNedas** [comment]
or just have bases (long lasting blocks?) generate no-build zones
