### ISSUE TITLE
Inverted unloader

### ISSUE THREAD

**Issue by Greenlog12** [Anuken/Mindustry-Suggestions#4422]
### Describe the content or mechanics you are proposing.

It would be like a normal unloader but it unloads everythin except the selected item

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allows the construction of much more complicated or compact factorys by allowing you to single out items to go somewhere else

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
just put an inverted sorter with said item in front of the unloder

**Comment by Greenlog12** [comment]
> just put an inverted sorter with said item in front of the unloder

Eh, it would save space

**Comment by itcannotbe** [comment]
> > just put an inverted sorter with said item in front of the unloder
> 
> Eh, it would save space

The argument doesn't makes sense because you don't need this nor an inverted sorter after the unloader if you are trying to save space. Have you seen designs that are compact use inverted sorters after unloaders?

Unloaders will not output an item that will not be accepted by the receiving block.
