### ISSUE TITLE
Core liquid storage

### ISSUE THREAD

**Issue by Greenlog12** [Anuken/Mindustry-Suggestions#4423]
### Describe what you would like changed, and why.

Give the core liquid storage because it doesnt really make sense for any core past shard to not be able to store some liquids

### Describe the changes you want to propose. Include possible alternatives.

Give the foundation and nucleus cores 150 and 300 liquid capacity respectively.

**Comment by octopuscaat** [comment]
this is not a good idea.

where exactly would this be used?
its more efficent to use a container rather than route liquid all  the way to the core. this would add unneccesary input/ouput to the core. 

there is a reason this does not exist.

**Comment by Greenlog12** [comment]
> 

You make it sound like theres never any liquid near the core,  also core schems if you could take the liquid between sectors.also really? Are you going to be using all of the adjacent spaces to a core with vaults (assuming the liquid would go directly to the core though the vault like items do)

**Comment by itcannotbe** [comment]
> > 
> 
> You make it sound like theres never any liquid near the core, also core schems if you could take the liquid between sectors.also really? Are you going to be using all of the adjacent spaces to a core with vaults (assuming the liquid would go directly to the core though the vault like items do)

Do you think it's not as intented that you can't take liquids with you?

For serpulo, liquids are either abundant or easy to make.
For erekir, liquids, in particular water, is intended to be a scarce resource.

Also, liquids are used in a fast enough manner that storing them is nonsense if you intend to take with with you at the start of the game.
