### ISSUE TITLE
bring back v6 ai "ai building" option

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#4426]
### Describe what you would like changed, and why.

bring back the ai option from v6 because:

- _**maps passage, glacier and veins are litterally dead weight without it, as they rely on the v6 Ai**_
- enemy core units don't serve any purpose considering they don't rebuild (in custom game anyway) structures and cant deal damage to buildings
- v6 "Ai building" makes the game more interesting and fun
- v6 "Ai building" code is already written
- adds more urgency to campaign attack sectors, as currently after the waves are done the player can kinda take as much time as they need to build up units and stuff
- is ok if only limited to Serpulo
- "switching versions" is not an option for mobile players
- adds an extra challenge to the game
- ai building is _awesome_

### Describe the changes you want to propose. Include possible alternatives.

in the team option of custom game add a "Ai building" option
if Erekir poses a problem to it (e.g. doesn't have Erekir Ai) just disable "Ai building" if the planet is set to Erekir.

minimally, if "Ai building" is not implementable add an option to allow core units to rebuild structures. It (probably) shouldn't be hard, just if an "allow unit rebuilding" is enabled set the command of the core units to rebuild.

**Comment by Anuken** [comment]
> ai building is awesome

The reason I removed it is because I never saw anyone use it, only complaints about how the AI randomly spamming schematics was terrible. It's not difficult to add back if necessary.

> maps passage, glacier and veins are litterally dead weight without it, as they rely on the v6 Ai

They are supposed to be PvP maps.

**Comment by buthed010203** [comment]
> They are supposed to be PvP maps.

Bold of you to assume we have friends

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/commit/29855243cbc0b72695d9ba314b12250e0c9a16f1
