### ISSUE TITLE
New enemy tip

### ISSUE THREAD

**Issue by Dimonitrion** [Anuken/Mindustry-Suggestions#4428]
### Describe the content or mechanics you are proposing.

![Polish_20230519_202720010](https://github.com/Anuken/Mindustry-Suggestions/assets/134078372/5773efb8-6c93-44d5-b0c4-a6cc77a0dd42)
English :
This type of enemy is called : 
1. Priest
2. Bishop
3. Monk 
4. Church
5. Temple
This enemy fires a laser at an ambient distance
This enemy reflects the bullets back to the turrets and bullets deal damage to base ( it can't reflect liquid projectile , lighting and explosions )
You can't make this unit with using unit factory .

Русский : 
Этот тип врага называется : 
1. Священник
2. Епископ
3. Монах
4. Церковь
5. Храм
Этот враг стреляет лазерами на небольшое расстояние . 
Этот враг отражает пули обратно в турели и они наносят урон базе ( он не может отразить жидкостные снаряды , молнии и взрывы )
Это юнита нельзя создать с помощью наземной фабрики .

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

English :
It diversifies the complexity and protection .
Русский : 
Это разнообразит сложность и оборону .

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Greenlog12** [comment]
How would you make this unit type if not from a factory? Also isnt this just a glorifed phase wall on legs?

**Comment by Dimonitrion** [comment]
It's only enemy unit. And yes , it's phase wall on legs.
