### ISSUE TITLE
 Planet Editor and Planet Server Multiplayer

### ISSUE THREAD

**Issue by Wanqungk** [Anuken/Mindustry-Suggestions#4429]
### Describe the content or mechanics you are proposing.

It's slightly odd that planets are reserved for campaigns and not part of multiplayer. It is fun to play on the maps, but the planets would add a whole new dimension especially with multiple sectors to capture. Also, a planet editor would be pretty fun for the community to mess about, since there's already many custom maps.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature will enhance the flare and general gameplay of multiplayer servers, while the planet editor would definitely be great for community content. Also, many people probably already want these feature to be added.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This goes to the pile of suggestions that basically suggest to host an entire planet.

The current pile:

#3419
#3325
#2364
#2319
#2072
#2066
#2053
#1146
#1111
#1046
#916
#459

**Comment by 5UP3R-D1N** [comment]
I and my team was planning to add entire mmorpg open-world to mindustry, by splitting worlds into chunk and warp player when they go to the edge of the chunk, like actual open-world

**Comment by octopuscaat** [comment]
yea you can do this with mods. if you dont like how its not in the game, learn to make mods

**Comment by Wanqungk** [comment]
@itcannotbe I'm pretty sure I suggested a planet editor too

**Comment by Wanqungk** [comment]
@octopuscaat Anuken hasn't stopped developing this game, so why not just suggest it to him? I would probably break the game if I tried modding tbh

**Comment by Wanqungk** [comment]
@itcannotbe Does the planet editor deserved to be lumped in there too?
