### ISSUE TITLE
QoL: Better PvP teaming as a host

### ISSUE THREAD

**Issue by Medicinexs** [Anuken/Mindustry-Suggestions#4430]
### Describe the content or mechanics you are proposing.

An option to change/move players team when you're an admin for a host.

I've been playing Mindustry multiplayers with my friends and I encountered a lot of problems teaming, either someone spawned in wrong team, or players are stacked up in a team and can't change teams.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will improve the game QoL especially for custom multiplayer games

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ilya246** [comment]
there's plugins that allow you to do this, my teamChange plugin for example, has many additional QoL too
though it would make sense to have this in the base game

**Comment by Anuken** [comment]
Would be nice to implement in the next non-patch build as an AdminAction. I'd rather not break netcode compatibility with 144.1 yet, so that will be a while.
