### ISSUE TITLE
New Unit!

### ISSUE THREAD

**Issue by AtomicTalkingBomb** [Anuken/Mindustry-Suggestions#4434]
### Describe the content or mechanics you are proposing.

A summoning unit! it summons units one tier down or something like that.

Stage 1 The unit summons between two legs it uses to move around (not being a suggestive)

Stage 2 The unit sorta looks like a walking portal. (AND YOU GUESSED IT THE UNITS COME OUT OF THE PORTAL)

Stage 3 The portal before is tall now on 3 its wide.

Stage 4 It is still being debated on.

Stage 5 A floating pod that shoots smaller pods that break on impact on enemy structures.

ps Note The summoning unit can not summon more summoning units

pps The name up to you Anuke.

From AtomicTalkingBomb

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Summoning units make maps more difficult AND pvp more exciting.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Greenlog12** [comment]
What would be the units it summons? Would it cost resources to summon them? Is it flying or ground? What would it cost to create? Also it sounds really annoying to fight against in numbers.

**Comment by Greenlog12** [comment]
> 

Omura is the t5 attack ship right? If it is then its because it only summons 2 flares each time, the ship itself is more dangerous then its summons, this t5 summon unit would summon TIER 4S. And  would probably be a ground unit.

**Comment by octopuscaat** [comment]
where does it say it that it would summon t4?

**Comment by Greenlog12** [comment]
> where does it say it that it would summon t4?

At the top, says it summons units one tier down.
