### ISSUE TITLE
Serpulo Specialist Naval And Flying.

### ISSUE THREAD

**Issue by Otamamori917** [Anuken/Mindustry-Suggestions#4436]
### Describe the content or mechanics you are proposing.

10 new units
**Specialist Naval: ague, miasma, pathosis, decrepitude, phlebotomize**
    primary weapons would shoot a new bullet-type vortex it slowly deals damage to enemies inside of it and attracts them to its center and it would afflict a decay status effect (slowly deals damage and has no opposites and affinities)
**Specialist Flying: apt, deft, lithe, adroit, astucious**
    a spaceship-type unit much faster and less durable than other flying units it has the ability to lower turret damage (like Ekerir mender suppression)
    its main weapons would be shotgun or continuous laser/flames
    these units would love to target payload blocks, unit factories, and turrets.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would finish the Serpulo unit tree 3 assault types 3 support types 3 specialist types (1 normally)
(I have some of this scripted already)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Otamamori917** [comment]
An
uke If you don't like the submerged mechanic just don't do that but do the specialist naval and flying, please

**Comment by octopuscaat** [comment]
i think submarine units should have 2 states: underwater and not underwatr. they should only be able to submerge in deep water and while submerged air units cant hit them. (but ground units can) half their weapons are disabed while submerged and move speed is lowered.  while suberged it cant target air.

but this is just my opinion. i dont expect it to get added and you probably shouldent either.

**Comment by Otamamori917** [comment]
> i think submarine units should have 2 states: underwater and not underwatr. they should only be able to submerge in deep water and while submerged air units cant hit them. (but ground units can) half their weapons are disabed while submerged and move speed is lowered. while suberged it cant target air.
> 
> but this is just my opinion. i dont expect it to get added and you probably shouldent either.

anuke has already said they doesn't want underlayer mechanics in vanilla before so yea I don't expect to be added

**Comment by Otamamori917** [comment]
i just mainly want specialist naval and flying

**Comment by octopuscaat** [comment]
and what would they do

**Comment by Otamamori917** [comment]
honestly don't know yet

**Comment by Otamamori917** [comment]
maybe a new bullet type for the naval 
and an new ability for flying

**Comment by octopuscaat** [comment]
then why open a suggestion? if your intent was to give some ideas for new unit names. in my opionion the flying should be able to be a bomb-dropping class or hover units. hover units have good potental and it sucks that they are underused

**Comment by octopuscaat** [comment]
good idea

**Comment by Otamamori917** [comment]
> then why open a suggestion? if your intent was to give some ideas for new unit names. in my opionion the flying should be able to be a bomb-dropping class or hover units. hover units have good potental and it sucks that they are underused

hover units aren't classed as flying they are a gound unit and there is already a ground specialist

**Comment by Otamamori917** [comment]
and for the name i gave the naval names mean infection and the flying names mean quick and nimble

**Comment by octopuscaat** [comment]
maybe a flying that is like a unit with really good speed and good attack but low health. might have the ability to deal extra damage to walls and reduce efficency of blocks. like a unit can reduce the efficenty of a turret by like 30% or so and would passively emit the effect like disrupt does to healing blocks

**Comment by octopuscaat** [comment]
or was it quell? i forget

**Comment by Otamamori917** [comment]
the t4 and t5 disrupt mender

**Comment by Otamamori917** [comment]
> maybe a flying that is like a unit with really good speed and good attack but low health. might have the ability to deal extra damage to walls and reduce efficency of blocks. like a unit can reduce the efficenty of a turret by like 30% or so and would passively emit the effect like disrupt does to healing blocks

that be a cool idea

**Comment by octopuscaat** [comment]
yes. also air tank exist in mono tree. oct is tanky af and quad is the best "support"

**Comment by Otamamori917** [comment]
okay. the flying would make turrets deal less damage  its weapon would prb shotguns or continuous laser/flame

**Comment by octopuscaat** [comment]
they might look kinda like a rocket or a lancer but streched verticly. weapons would be like beta and can turn independently of the unit i guess. might be cool if some of their weapons have pircing considering how it is. like its bullet hits a building the bullet kina bounces to adjacent building up to a centertn amound and possibly deal less damage

**Comment by Otamamori917** [comment]
i have an idea for a mechanic for the naval
VortexBulletType slowly damages enemies caught in it and attracts them to the center of the bullet

**Comment by octopuscaat** [comment]
that would be extremly annoying. it seems like it would be an idea for a turret and not a unit. reguardless it shouldent affect air. also i guess the "stronger" or "heaver" the unit the less affected i would be. like would barely affect reign but effective against daggers. might have low damage but constantly damages enemys caught in the vortex. even so it seems more like a semi-support and wouldent be used on its own, kinda like how you dont use forshadow or wave/tsunami on its own.

**Comment by octopuscaat** [comment]
thats reasonable. one issue might be if you have multiple. like one alone would have really low fire rate but a ton under cryo and overdrive dome could lock even big units like reign in place. maybe it shouldent be allowed to have boosters and not affected by overdrive domes.  i guess it could have 1, really good range but cant target if the enemy is closer that a certen distance or 2, have a really low range but having a low range just feels like a waste. balanceing it might have low health

**Comment by Otamamori917** [comment]
> thats reasonable. one issue might be if you have multiple. like one alone would have really low fire rate but a ton under cryo and overdrive dome could lock even big units like reign in place. maybe it shouldent be allowed to have boosters and not affected by overdrive domes. i guess it could have 1, really good range but cant target if the enemy is closer that a certen distance or 2, have a really low range but having a low range just feels like a waste. balanceing it might have low health

The last time I remember overdrives don't effect unit and this bullet type wont be applied to a turret

**Comment by Otamamori917** [comment]
and yes reload would be simmalr or longer then corvus

**Comment by octopuscaat** [comment]
probably longer. closer to the fire rate of scathe

**Comment by Otamamori917** [comment]
most likely (if implemented)

**Comment by Otamamori917** [comment]
ill get back to scripting this stuff

**Comment by octopuscaat** [comment]
nice is it for ios or just pc?

**Comment by Otamamori917** [comment]
> nice is it for ios or just pc?

should work on both like any mod

**Comment by Otamamori917** [comment]
tho sprites are a different story I'm not that great at it

**Comment by octopuscaat** [comment]
yea im slightltt-less-than-ok at at sprites.  but still decent
