### ISSUE TITLE
Different Enemy Spawn Variables

### ISSUE THREAD

**Issue by Medicinexs** [Anuken/Mindustry-Suggestions#4437]
### Different Enemy Spawn Variables

It should be good if there's a way for **Enemy Spawns** to has different variables to it that we can edit each of them separately in waves generation settings. 

For example if I want to make a map that the upper half is ground and the bottom half is water, and I want to make the enemy spawns from top and bottom, with each separate unit types and unit counts.

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/67633347/52c51507-43d2-47a3-b0d3-651437d93059)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This could make the game more interesting and fun to play, especially facing different types of enemies from different spawn.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
you can already do this.... in the waves editor you can choose the spawn  you want them to spawn on....

consider closing the issue?

**Comment by octopuscaat** [comment]
(note i commented within 2 minuites of the issue being opened)
