### ISSUE TITLE
Unit Selection on PC 

### ISSUE THREAD

**Issue by Amogushacker69420** [Anuken/Mindustry-Suggestions#4439]
### Describe what you would like changed, and why.

It isn't clear how to control units and I find that ctrl dragging over the entire map to select all units then remembering to right click instead of left click (or maybe it was left click idk) and being wrong and doing it all over again to be a little annoying. 

### Describe the changes you want to propose. Include possible alternatives.

There should just be a ctrl+right click to send all units to attack one spot, the unit controller shouldn't be nessicary. Or at least existing keybindings should be more obvious.

**Comment by Amogushacker69420** [comment]
also ignore my username

**Comment by TepperPepper666** [comment]
I think if you hit 'G' while in command mode that selects all your units.
