### ISSUE TITLE
Script that runs while a sector is being played

### ISSUE THREAD

**Issue by GlennFolker** [Anuken/Mindustry-Suggestions#444]
**Describe the content or mechanics you are proposing.**
So, basically a mod's `.js` script `Object` which provides a function is called every tick a sector is being played.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will surely improve modded sector's mechanism / creativity, making said sector not to be so plain and boring.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
just check for Vars.world(.map?).sector

**Comment by GlennFolker** [comment]
> just check for Vars.world(.map?).sector

will do
