### ISSUE TITLE
Idea for Unit Producers

### ISSUE THREAD

**Issue by actinium-225** [Anuken/Mindustry-Suggestions#4445]
### Describe the content or mechanics you are proposing.

Once an unit is at maximum capacity, [Eg. 24 monos] and you switch to another unit that isnt full, [eg. flare] the full unit should be brought back in, and changed to the newly selected unit.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature would prevent clutters and allow for easier assaults on enemies.
Thanks for reading!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Greenlog12** [comment]
This would never be used in the example you gave and units from the same factory feel so similar at higher tiers it wouldnt matter, actually, how would it work with higher tier units?

**Comment by actinium-225** [comment]
good question. 

maybe it wouldnt use the mats but would do the same?
