### ISSUE TITLE
Allow any planet Worlds

### ISSUE THREAD

**Issue by Soldier-5434** [Anuken/Mindustry-Suggestions#4448]
### Describe what you would like changed, and why.

I can only have 'any' planet in sandbox.

Please change this. 

### Describe the changes you want to propose. Include possible alternatives.

![ytho](https://github.com/Anuken/Mindustry-Suggestions/assets/134946670/574e2e53-a7dd-44c4-969c-fbaacacf2805)

**Comment by buthed010203** [comment]
Download one of the many existing mods that already does this

**Comment by DX-36** [comment]
not a bug
clearly if there's text there specifically for that then it's intentional
