### ISSUE TITLE
Ban specific units in multiplayer or map editor

### ISSUE THREAD

**Issue by FollowTheTrain-CJ** [Anuken/Mindustry-Suggestions#445]
It is pretty simple,we should be able to ban units in editors or custom games

This feature is to prevent players from producing specific units. The inspiration of this feature is to make ground unit-only game fair and balance and allowing miner drones to keep up the supplies. Some maps and multiplayer games only allows ground units but there are always gamethrowers that break the rule and make the gameplays discouraging. You may suggest that banning Air Factory can prevent this from happening,but this will also disable the most important support drone, Miner drones. The aboves situation is an example to the feature,i am pretty sure there are better n smarter way to use it.So hopefully this feature will be implemented and coming handy. Allowing more tactical maps and games

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
can't you ban specific blocks...

**Comment by Ruichka** [comment]
> can't you ban specific blocks...

With 6.0 every unit factory allows to produce different types of units and also there is only one upgrade blocks line
