### ISSUE TITLE
reign buffs

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#4451]
### Describe what you would like changed, and why.

buffing reign by increasing reign defense from 14 to 18 (or 16). 

reason: reign is a tank and gets killed pretty quickly for a tank. oct, omura and navanax have 16 defense. despite this might not be a fair comparison considering they are air support and naval, my point still stands. reign is still kinda weak compared to other t5. in my opinion the dagger tree is supposed to make up for lack of abilitys with being a tank, but thats my opinion;

reign is underused due to its inferior destructive properties. increasing defense would make reign a more valuable unit.

it shouldent be hard as i assume reigns defense is just a variable (why would it NOT be a variable?) and would only take like 2 seconds.

### Describe the changes you want to propose. Include possible alternatives.

increase reign defense from 14 to 18. aternativly, increase it to 16.

**Comment by ThoriumTextile** [comment]
The reign is perfectly fine as is. It's not supposed to be a facetank; for that you'd need the Nova tree or an Oct.
Plus it would really screw over the campaign, as it's already a very strong unit as an enemy for the reason I just said.
