### ISSUE TITLE
Additional Unit Statuses For Storytelling Purposes

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry-Suggestions#4453]
### Describe the content or mechanics you are proposing.

The more functionality you make available to content creators, the better.

Specifically here, additional unit status effects such that mapmakers can craft more complex cutscenes that can be separated from gameplay.

Similar in concept to the "Unmoving" status we currently have.

"Disarmed" This unit does not automatically acquire targets nearby and fire upon them.
"Invincible" This unit can not be fired upon by any nearby units/buildings on other teams.
"Independent" This unit cannot be selected or given orders by a player.

Bonus ask: Way to get the same outcome, but with buildings. This would make something possible like visiting a base that is friendly but not part of the same team. Or the ability to use game content blocks to construct and represent triggered mechanisms. 

(example: Bring some units to this factory and you get some bonus units. The factory can be represented by something that looks like a unit factory, but can't be player controlled, attacked, or deconstructed)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A mapmaker has access to cutscene and unit movement through the world processor, but insufficient ability to separate storytelling elements from game play.

Imagine trying to setup a "dropship" scene where the player is trying to survive long enough to be rescued. The mapmaker wishes to make an ending scene where large flying ships fly to the core, some text displays, and then the rescue ships fly away. 

As is, the rescue ships _must_ be on the same team as the player, otherwise player defenses would fire upon them. 
Cutscene must be active otherwise the player could use commands to interfere with their scripted rescue.
If any enemies are along the rescue path, they could destroy the rescue ships and ruin the cutscene.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
ok so. disarmed _and_ invincible [already exist](https://mindustrygame.github.io/wiki/Modding%20Classes/StatusEffect/) ,and you checked the the second box, that clearly states "I have glanced at the wiki to make sure my suggestion doesnt exist in the game yet", but typing in "invincible" _or_ "disarmed" shows the effects page. 

as for the "independent" effect you can just disable the ability to command the unit.
