### ISSUE TITLE
Petition to Add an "Angle Difference" method in arc.math.Angles

### ISSUE THREAD

**Issue by JP16D** [Anuken/Mindustry-Suggestions#4454]
### Describe what you would like changed, and why.

just want to suggest adding angle difference because none exist it arc.math.Angles class and maybe other java modders might find it useful too, like for parts animations and such

### Describe the changes you want to propose. Include possible alternatives.

```
public static float angleDiff(float a, float b) {
	a = Mathf.mod(a, 360);
	b = Mathf.mod(b, 360);
	float dif = a - b;
	return Math.abs(dif) > 180 ? dif - (360 * Mathf.sign(dif)) : dif;
}
```
basically an angle distance but allows negatives, I have already used it so definitely sure it works well, it outputs an angle in the range of 180 to -180 to ensure it finds the closes distance possible

example results:
0° - 180° = -180
0° - 181° = 179
270° - 1° = -91
1° - 270° = 91

**Comment by octopuscaat** [comment]
you should suggest this on anukes [Arc repository](https://github.com/Anuken/Arc)

this is for _mindustry_ suggestions. mindustry just _uses_ arc. consider closing the issue and opening it there.
also holding petitions on github isnt exactly the best idea. the avrage issue has 0-1 comments.

**Comment by Anuken** [comment]
there's already [this](https://github.com/Anuken/Arc/blob/master/arc-core/src/arc/math/Angles.java#L23), except it returns the absolute difference without a sign - I don't know why you would need a signed difference; I've never needed one, and if you do, just implement it yourself.

**Comment by JP16D** [comment]
> there's already [this](https://github.com/Anuken/Arc/blob/master/arc-core/src/arc/math/Angles.java#L23), except it returns the absolute difference without a sign - I don't know why you would need a signed difference; I've never needed one, and if you do, just implement it yourself.

That's exactly what I did lol 😅 and anyways I know angleDist() exists its just it doesn't work if you need a specific angular direction, distance is most likely to be used for comparison/conditionals in the other hand angle sum/difference works for operations and well while sum is easy difference needs to account for something like transitioning value from 270 to -90 and I mean in the first place how do we have angle distance but not angle difference and I anyways already have provided a working code for it so why not consider maybe? 🤷‍♂️

**Comment by JP16D** [comment]
> (aside from you, who already copy-pasted it?) 

I literally spend hours making circle graphs in my brain just to solve how to transition the values and debugging it by testing it what I'm using 😭 cause for some reason google gives you sine formulas when asking for how to get angle difference also you never know when such a simple operation is useful but yeah I guess there's not really a point until it needs to be used

**Comment by Anuken** [comment]
> I literally spend hours

I meant you copy-pasted it into your mod source code (as opposed to using it from a utility library), not that you didn't write it yourself or took it from some site like SO.

> you never know when such a simple operation is useful

Well, it's not useful for me yet, and until it is there's no reason to add it.
