### ISSUE TITLE
Lightning should not be able to hit the same thing multiple times. (Or at least a boolean option in BulletType)

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#4455]
### Describe what you would like changed, and why.

Each lightning segment being able to hit the same unit is a major factor in how it's capable of melting units out of existence with the wet status effect.

### Describe the changes you want to propose. Include possible alternatives.

By default, the bullets spawned by lightning should not be able to hit the same target. A boolean in `BulletType` to enable this for that bullet's lightning should be included in case someone does want this to happen.

I would make a PR and do this myself, however I don't know the best way to get bullets to share their `collided` `IntSeq`s, so I'll make it a suggestion instead.  (I've tried some things, however they did not seem to have an affect in my testing.)

**Comment by octopuscaat** [comment]
what do you mean by "lightning"? do you mean the shocked effect or lightning damage (like surge alloy) ? 
side note: does that include surge walls, as to my knowlage(aka the wiki) they do not inflict shocked

**Comment by MEEPofFaith** [comment]
The actual lightning strikes.
Arc, surge wall, surge cyclone, etc
