### ISSUE TITLE
Ingame recording feature for replays

### ISSUE THREAD

**Issue by zwastik** [Anuken/Mindustry-Suggestions#446]
**Describe the content or mechanics you are proposing.**
I suggest a game match recording feature, similar to other games. In this case recording could be client side, and it could be started automatically when one enters a server and stop on disconnect. There should be a toggle in options for activating this feature.

Some useful documentation:
[Gamasutra - Developing Your Own Replay System](https://www.gamasutra.com/view/feature/2029/developing_your_own_replay_system.php)
[Implementing a replay system in Unity and how I'd do it differently next time](https://www.gamasutra.com/blogs/AustonMontville/20141105/229437/Implementing_a_replay_system_in_Unity_and_how_Id_do_it_differently_next_time.php)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This feature would improve the game because one could learn from more experienced players by replaying the game. Also one could learn from one's own mistakes. Last but not least, a replay would be useful for griefer catching

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
(I searched for "record" and "replay" -> no results.)
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
(I searched for "record" and "replay" -> no results.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
(I searched for "record" and "replay" -> no results.

**Comment by Anuken** [comment]
This won't be implemented, for a few reasons:

- Unlike some other games, Mindustry has a *lot* of state to store. If using a snapshot approach, every single time and unit would need to be saved at regular intervals - this is simply not practical.
- Mindustry is *not* deterministic at all, and making it so would be a monumental amount of work. 
- Even if the two problems above did not exist, such a feature would take a massive amount of time to implement and maintain, and I personally don't have much interest in doing so.

**Comment by animaone** [comment]
For documentation purposes only and just in case someone want to try this Colossal Task in a new source fork:
http://w3g.deepnode.de/
