### ISSUE TITLE
Strange Mindustry

### ISSUE THREAD

**Issue by Maleraik** [Anuken/Mindustry-Suggestions#4461]
### Describe the content or mechanics you are proposing.

You cold add in play store and in itch.io an game called strange mindustry, but it's just a game were you can change the versions like: "I want to stop playing build 63 and want play V5 again, then the person just switch the version of the game without downloading anything else. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It world be good because the old versions are good the revisit. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
um... just go download the build you want i guess?

**Comment by Maleraik** [comment]
But I play on my phone.

Em ter, 6 de jun de 2023 12:41 PM, octopuscaat ***@***.***>
escreveu:
