### ISSUE TITLE
time (day night cycle)

### ISSUE THREAD

**Issue by iotkido** [Anuken/Mindustry-Suggestions#4465]
### Describe the content or mechanics you are proposing.

make a way where you can tell like a day/night icon and update the solar panel info to "it might be effected by the day/night cycle

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

alot by adding variables that the player gets effected by like the day/night cycle it well limit the players energy production then to cause them to plan a bit more critically  

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
Not sure if anybody uses solar panels as main power source.

**Comment by dvahkiin31** [comment]
jump 60 notEqual goto_countdown null
set sol_multiplier 3
set day_length_min 7
set dusk_length_min 1
set night_length_min 3
set dawn_length_min 1
op add goto_countdown @counter 2
jump 31 always i null
end
op mul wait_mili 60000 wait_min
op add wait_end @time wait_mili
set time @time
jump 29 greaterThanEq time wait_end
op sub wait_diff_mili wait_end time
op div wait_diff_sec wait_diff_mili 1000
op mod wait_r_sec wait_diff_sec 60
op floor wait_r_sec wait_r_sec 60
op div wait_r_min wait_diff_sec 60
op floor wait_r_min wait_r_min 60
jump 29 lessThan wait_r_sec 0
print stage
print " ~ "
print wait_r_min
print ":"
jump 26 greaterThanEq wait_r_sec 10
print "0"
print wait_r_sec
message mission 2
jump 11 always i null
set @counter countdown_bm
end
op add goto_transition @counter 2
jump 60 always i null
end
jump 38 equal transition_reset -1
op mul transition_mili 60000 transition_min
op add transition_end @time transition_mili
set transition_reset -1
op sub transition_r_time_mili transition_end @time
op div transition_r_time_sec transition_r_time_mili 1000
op mod transition_r_sec transition_r_time_sec 60
op floor transition_r_sec transition_r_sec 60
op div transition_r_min wait_r_time_sec 60
op floor transition_r_min transition_r_min 60
op div transition_ratio transition_r_time_mili transition_mili
jump 57 lessThan transition_r_sec 0
print stage
print " ~ "
print transition_r_min
print ":"
jump 52 greaterThanEq transition_r_sec 10
print "0"
print transition_r_sec
message mission 3
jump 57 greaterThanEq @time transition_end
set transition_return transition_ratio
jump 58 always @time transition_end
set transition_return -1
set @counter transition_bm
end
jump 65 notEqual stage null
spawn @mono 375 321 90 @sharded result
spawn @mono 379 321 90 @sharded result
spawn @flare 362 309 90 @sharded result
setrule solarMultiplier sol_multiplier 0 0 100 100
packcolor light 0 0 0 0
setrule ambientLight light 0 0 100 100
set stage "Day"
set wait_min day_length_min
op add countdown_bm @counter 1
set @counter goto_countdown
set stage "Dusk"
set transition_min dusk_length_min
set transition_reset 1
op add transition_bm @counter 1
set @counter goto_transition
jump 83 equal transition_return -1
op sub transition_return 1 transition_return
op mul sol transition_return sol_multiplier
setrule solarMultiplier sol 0 0 100 100
packcolor light 0 0 0 transition_return
setrule ambientLight light 0 0 100 100
jump 75 always 1 false
set stage "Night"
setflag "summon" true
set wait_min night_length_min
op add countdown_bm @counter 1
set @counter goto_countdown
set stage "Dawn"
set transition_min dawn_length_min
set transition_reset 1
op add transition_bm @counter 1
set @counter goto_transition
jump 99 equal transition_return -1
op mul sol transition_return sol_multiplier
setrule solarMultiplier sol 0 0 100 100
packcolor light 0 0 0 transition_return
setrule ambientLight light 0 0 100 100
jump 92 always 0 false
end

I know you probably meant day/night in campaign but here's a world processor script to gradually change the map to night & change the sol multiplier

That said the ability to test if a tile is/isn't illuminated world be cool, could make a zombie map
