### ISSUE TITLE
Over/Underflow Unloaders

### ISSUE THREAD

**Issue by ThoriumTextile** [Anuken/Mindustry-Suggestions#4467]
### Describe the content or mechanics you are proposing.

Currently, there is no easy and straightforward way to manage overflow in containers/vaults, at least not in a compact way.
This is, IMO, kind of an unnecessary pain, especially for managing separator/disassembler outputs.
I.e.: Let's say you have set up a scrap to surge array
One of the resources, let's say copper, reaches the 300/1k limit, and in order to make your system take the least space possible, you don't use any conveyors. 
This is now an issue, because the copper is backing up the separators/disassemblers, therefore you won't be getting any resource at all.
You COULD use logic to solve this and be done with it, but there's the small issue that not everyone that plays this game is good at it, or knows programming concepts. Plus it's not really a straightforward solution.
You COULD simply use conveyors and gates at the top anyway, but then again, it's not compact nor straightforward.

I think there could be two implementations:
One where the unloader simply checks if any of the containers/factories or whatever has hit a resource limit, perhaps one that's configurable too.
Or the other where it has the same outputs as the conveyor gates, although I imagine this would be hardly of any use and somewhat difficult to implement.
As for the underflow variant, I think they would find the most use in unit/resource production, in order to prevent backflow.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be a noticeable quality of life improvement, and not to mention how due to the nature of Mindustry's campaign maps, where not always space is so readily available (i.e. stained mountains or in crevices), it would greatly help for tighter schematics.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What happened to

> ### A few things you shouldn't suggest
> ###### These have been proposed many times already, and I won't be adding them.
> - Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills

**Comment by ThoriumTextile** [comment]
> What happened to
> 
> > ### A few things you shouldn't suggest
> > ###### These have been proposed many times already, and I won't be adding them.
> > 
> > * Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills

Pretty sure it doesn't fall under that category. Mainly because it doesn't replace any blocks or tips game balance.
It would be merely a sister addition to the tools that the conveyor line already has.
Plus as I already said, this is already a thing with logic; i'm just trying to make it more accessible.
