### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by Thebenjiball** [Anuken/Mindustry-Suggestions#4470]
### Describe the content or mechanics you are proposing.

Blocks that can play 8-bit noises when sent inputs from a processor.

Blocks:
- Speaker (15 block radius)
- Large Speaker (40 block radius)

new processor commands:

- Audio
  [wave] [pitch] [length]
    
 (waves: square, round, triangle, sawtooth, etc,) (pitch: self explanatory) (length is in seconds)

- Audio Flush
   to [speaker]
   
   
- Control
  set [enabled] of speaker1 to 0
  
  (this will mute the speaker)
   
   
   
   
  example:
  
- Audio
  square C1 2

- Control
  set enabled of speaker1 to 1
  
- Audio Flush
   to speaker1
   
   
   
  
 new settings:
 
 - Speaker volume
 - Mute multiplayer Speakers

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Programs can be made a lot more immersive with music and sound effects, you can make warnings for when you are low on materials, ammo, or if an enemy has breached your defenses. Just really cool things in general. I feel like this should have already been a thing in the game.

It is suggested that once done making the music, you store all of it's data into a memory bank so your program doesn't have to re-create it live every time.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
:(
