### ISSUE TITLE
Realism 

### ISSUE THREAD

**Issue by XGUDLUDX** [Anuken/Mindustry-Suggestions#4471]
### Describe the content or mechanics you are proposing.

Please add air temperature and wind speed. Also add turret overheat. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make the game both easier and harder at the same time. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Thebenjiball** [comment]
bro you did not describe any of it nearly enough ☠

**Comment by Greenlog12** [comment]
What would these even do? And turret overheat sounds dumb

**Comment by octopuscaat** [comment]
i agree with that one part but the other part sounds awful. this is a great idea but it sucks so much it is good but is bad. anuke should add the one part and not add the other part but if you change the other part to be more like that one other other part it would not suck as much as the one other part and then anuke should add that part too. i 100% agree with that one part but 99.9% of that suggestion is b-

**Comment by MASTRIO** [comment]
You didn't even describe what it would do
