### ISSUE TITLE
Make overdrive have no effect on turrets and some other defense blocks

### ISSUE THREAD

**Issue by DX-36** [Anuken/Mindustry-Suggestions#4473]
### Describe what you would like changed, and why.

It's very easy to add an overdrive projector or dome to a bunch of defense blocks as opposed to making coolant, especially for the 4x4 turrets which not only need lots of coolant but receive little benefit from it. (excluding meltdown)

A single overdrive projector/dome can cover many turrets much easier than coolant, which needs to be supplied to each turret that is using it. The additional ammo and power usage of the defenses can be offset with ammo storage and overdriving the ammo source.

In addition, overdrive increases the heal frequency of menders and mend projectors, which, combined with phase fabric in both the overdrive and mend projectors, results in either the mended blocks being killed instantly or the block heals full health back almost immediately - _there is no in between here_. (this is also an issue that comes from stackable mending in serpulo)

Because of overdrive, it is significantly easier to cram a ton of firepower in one spot and kill any enemy units that approach the defense, as the projector/dome barely takes up any space and becomes more effective the more blocks it can overdrive.

In survival, this is offset primarily by massive amounts of shield HP given to enemy units, meaning the turrets cannot kill the enemy units quickly. In attack, you cannot stack so much shield HP - the limit is 40 for most units or the unit's max force field health for quasar and oct. If the enemy defensive wall contains many mend projectors and turrets all with everything the blocks can receive, with an overdrive dome to significantly boost the defenses, the defensive wall becomes extremely OP, shredding anything that walks into range, and requires tons of corvus/omura to burst through the walls or kamikaze attacks using quads or even octs loaded with blast compound. 

### Describe the changes you want to propose. Include possible alternatives.

Set in the base definition for turrets and perhaps some other defense blocks like mend projectors `canOverdrive = false` 

(side note: serpulo's stackable mending is also OP and should probably be removed or toned down)
(side note 2: this might make mixtech slightly more balanced turret-wise)
(side note 3: kamikaze needs a big direct nerf to offset the changes)
(side note 4: maybe nerf all the siege units - then again most people don't know the real counters to siege units, which is to swarm the siege units with an air force, but omura needs a really big nerf in terms of firepower - being restricted to certain areas does not justify being extremely OP and invalidating other options where it can be used, in the meanwhile make aegires healing not percentage-based on units. anthicus also kinda needs a nerf - it can be simple as cannot hit air units)

**Comment by TagGamer555** [comment]
I have only one question...
**Why?**

**Comment by itcannotbe** [comment]
Obviously, the same reason why erekir doesn't have a similar block.

**Comment by JamesTDG** [comment]
This does seem a bit odd. Many of the attack maps I play on have literal pools of coolant we can tap into. Also, while yes, overdrives can definitely boost turrets, it is not exactly going to change much. In most of my experience playing on Attack servers, I haven't seen many players opt to boost turrets, as many are merely temporary to hold off enemy forces or break into bases more efficiently. 

An addendum to this as well:
By the time overdrive domes are capable of being manufactured and used in front-line offense/defense, the game already is in its late stage and there is no need to nerf that when you have the strongest long-range turret constructible on Serpluo.

**Comment by itcannotbe** [comment]
Manufacturing phase fabric is extremely trivial, you can already do it in early mid game.

Who doesn't even use overdrives on power production in that stage?

**Comment by DX-36** [comment]
one issue I explain is that each spectre and foreshadow get a small buff from coolant while consuming 60/sec of it, while 1 overdrive dome will more than double the damage that all turrets in the range can deal

**Comment by DX-36** [comment]
overdrive is a block that's way too easy to add to any setup for far too significant effect, and serpulo kinda revolves around overdrive as a result
