### ISSUE TITLE
Автоматическая замена конвейеров.

### ISSUE THREAD

**Issue by whoiam-777** [Anuken/Mindustry-Suggestions#4474]
### Describe the content or mechanics you are proposing.

Автоматическая замена конвейеров с помощью одной кнопки. Например, титановый конвейер можно заменить полностью на пластановый/бронированный конвейер.
![Screenshot_20230618_051452_Mindustry](https://github.com/Anuken/Mindustry-Suggestions/assets/72210308/34a56be5-0083-40ec-af60-85e86ccbf800)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Явно понравится большинство игрокам. Это значительно ускорит процесс развития (особенно на большом карте). 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JamesTDG** [comment]
This could definitely be expanded upon. How will players upgrade (or even downgrade) belts? Is it automatic? Do players have to double-click a belt?

**Comment by adraxe** [comment]
на английском пиши, анюкен уже сказал что в непонятных ему языках разбираться не хочет
