### ISSUE TITLE
Make Junctions Rotatable Like Conveyors

### ISSUE THREAD

**Issue by stoltzld** [Anuken/Mindustry-Suggestions#4477]
### Describe the content or mechanics you are proposing.

Make junctions rotatable like conveyors.  I've noticed that sometimes materials get stuck in junctions if I place them poorly.  I would like to be able to rotate them to get the stuff out of them.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

One more way to help unstick stuff that gets stuck in weird places.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
When deleting and replacing them is a faster and more efficient way of dealing the problem.

**Comment by stoltzld** [comment]
Well, some days I fixate on not losing the resources trapped in them.  It'd be quicker to rotate them than destroy and build conveyors, which also loses resources.
