### ISSUE TITLE
Multiplayer 

### ISSUE THREAD

**Issue by Keks13** [Anuken/Mindustry-Suggestions#4479]
### Describe what you would like changed, and why.

Hey,

So i would like to play online with friends on my mobile devices. We dont often meet us but we still love Mindustry and playing alone or in a server isn’t that fun for us.

### Describe the changes you want to propose. Include possible alternatives.

Its just a mobile friend list.

**Comment by itcannotbe** [comment]
It's not just a mobile friend list.

It also includes physical hardware, an account system, internet connectivity. All costing real money.

You're asking a lot for a game that doesn't even run ads nor micro transactions/subscription model.

**Comment by camelStyleUser** [comment]
use CLaJ.your suggestion is too hard to make because of server costs,etc. etc.
