### ISSUE TITLE
Make processors require power

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry-Suggestions#448]
**Describe what you would like changed, and why.**
In the *real* world, processors require power. So should Mindustry processors.

**Comment by itcannotbe** [comment]
How much power are we talking here?

**Comment by potatoisagender** [comment]
maybe illuminator power, or like, mender or smth.

**Comment by Anuken** [comment]
This seems reasonable at a glance, but I don't think this will improve the game in any way. They won't use enough power to matter in a grid, and all this will do is make them flaky and unreliable in survival, further decreasing their viability in real games. In sandbox, this will make them more annoying to use and force all existing logic schematics to incorporate power sources.

**Comment by itcannotbe** [comment]
Here is a fun fact:

Actually anything won't use enough power to matter in a grid.

We have power cubes that we can spam around the map since they virtually doesn't require anything but space to produce power. It's literally broken like those early v4 thermal generators.

**Comment by itcannotbe** [comment]
It would the gameplay as it is less likely that you will spam logic block around the make and would for you to include power draw limiting self powering logic-power control systems.

Heck you can even be forced to make generators start and stop on demand through logic blocks.

**Comment by sample-text-here** [comment]
I really don't understand why hyper processors require cryofluid but not power. Just saying.
