### ISSUE TITLE
Холст

### ISSUE THREAD

**Issue by SHAURMA002** [Anuken/Mindustry-Suggestions#4484]
### Describe the content or mechanics you are proposing.

Добавить больше цветов в "холст"

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Duplicate of #4478. Why.

**Comment by octopuscaat** [comment]
yeah uh... it says "If your request is in _a language I don't understand_ and clearly doesn't follow the template, I am unlikely to bother reading it."

**Comment by Slotterleet** [comment]
> yeah uh... it says "If your request is in _a language I don't understand_ and clearly doesn't follow the template, I am unlikely to bother reading it."

Anuke does understand Russian, though.

**Comment by octopuscaat** [comment]
and how do you know?
