### ISSUE TITLE
Drones are getting big

### ISSUE THREAD

**Issue by nat3n** [Anuken/Mindustry-Suggestions#4485]
### Describe the content or mechanics you are proposing.

Would be nice to had a graphic option or something like that to allow us to bypass drones when working on contraptions. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I've encountered this issue very often where i would get to a point on a defense map where i would start creating t4 drones, put them above my deffensive wall, but then find myself not able to work on said wall, or to repair it, without having to spend 15min moving the drones away.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by c-128** [comment]
What about an option to render the flying units a bit more transparent?
