### ISSUE TITLE
Map Rule To Enable/Disable Unit Boosting

### ISSUE THREAD

**Issue by JianhuiDong9999** [Anuken/Mindustry-Suggestions#4486]
### Describe the content or mechanics you are proposing.

Self-explanatory. A map rule that allows/prohibits boosting for units like Pulsars and Velas. Boosting is enabled by default.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I am trying to make a PvP map that is themed around subterranean exploration and terrain-digging. On the map, I want all exploration done via digging terrain and I want all ground units to be usable for this map. However, having no way to turn off unit boosting, I am forced to cut the nova unit tree out of this map.

If boosting can be toggled as a map rule, it will be much more convenient for mapmakers who want to make ground-based maps. Thank you for viewing my suggestion.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
you are makeing a map. just use a world proccesor to destroy boosting unit or inflict unmoving to a unit that is flying.
