### ISSUE TITLE
Make Eradicator, Chaos Array and Erupter etc. buildable like Lich/Antumbra and Reaper/Eclipse

### ISSUE THREAD

**Issue by Humanoid-X** [Anuken/Mindustry-Suggestions#449]
In V6, Air bosses are now buildable, but ground bosses are not.

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
[X to doubt] I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

**Comment by Anuken** [comment]
None of the units you listed exist in v6.

**Comment by Humanoid-X** [comment]
Aw that was my first time using trello, not so familiar with the interface... I promise this won't happen again :(
