### ISSUE TITLE
Ability to guess which building is under construction

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4491]
### Describe the content or mechanics you are proposing.

For now all buildable blocks share the same type in game starting from @build1 to @build16  but there's no way to guess with processor which building will be in that place until it finished.

My suggestion is to let processors link with build-in-progress buildings and sensor which building will be built there by accessing @config in that building (as @type is occupied by building size)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'll let to see in logic if some of the buildings were deconstruct or still to be constructed, especially when placing or replacing schematic with large number of builds.

Also sensing with world processor will let you to control constructions before it actually done like preventing from building specific blocks in area but letting to place them outside.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JamesTDG** [comment]
It might be smart to have it be like a hologram that can be seen by all.
