### ISSUE TITLE
Setting to make erekir unloaders unload from core

### ISSUE THREAD

**Issue by bend-n** [Anuken/Mindustry-Suggestions#4493]
### Describe the content or mechanics you are proposing.

make unloading from cores with unloaders possible.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

a game mode im working on allows you to place new cores, but theyre kind of useless when you cant unload.
i get your supposed to use the whole unit cargo system, but i like my cores.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by overdramaticpanromantic** [comment]
Bad idea. Plus, it's not possible without internal shitfuckery as far as I know. Extra cores are useful due to unit cap.

**Comment by bend-n** [comment]
- why is it a bad idea
- i dont think its impossible; theres just a little flag that says [oy can i unload from core](https://github.com/Anuken/Mindustry/blob/a20ca675274aaf83888b3fbbd54dd5e966e7ce05/core/src/mindustry/world/blocks/distribution/DirectionalUnloader.java#L26)
- the alternative is allowing serpulo unloaders and spawning in titanium, which just feels... wrong.

**Comment by itcannotbe** [comment]
There's a reason why serpulo mechanics are different than erekir.

If you want serpulo mechanics, then play serpulo. It's that simple.

**Comment by bend-n** [comment]
i get your point; however, why not?

**Comment by itcannotbe** [comment]
I get your point;however, why even?

**Comment by bend-n** [comment]
it could be fun

**Comment by itcannotbe** [comment]
Hmmmm. Why not just making it work via hacky code then:

If core has items and unloader is adjacent, subtract items from core then add items to block x.

**Comment by Zerenta** [comment]
you dont even have to bother with plugins for this one
just loop through all erekir unloaders with a world processor and set them to serpulo unloaders, problem solved

**Comment by itcannotbe** [comment]
The thing with that approach is that erekir unloaders are not serpulo unloaders with allowCoreUnload = false. They're not called directional unloaders for a reason...

**Comment by bend-n** [comment]
yeah i suppose i could loop over all erekir unloaders, check if theyre next to a core, and if they are turn them into a serpulo unloader....
