### ISSUE TITLE
Holding down 'Left Alt' should temporarily swap to the Eyedropper tool when in the Map Editor.

### ISSUE THREAD

**Issue by UntotenTheo** [Anuken/Mindustry-Suggestions#4498]
### Describe the content or mechanics you are proposing.

Quite simple, really, if you have any other tool selected (Brush, Line, Bucket, etc), holding down the 'Left Alt' button should swap to the Eyedropper tool, then swap back to your previously selected tool once the button is released.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While not the most groundbreaking feature to include, I feel like it'd be helpful to at least some mappers who might want to quickly swap between different, already placed blocks on the map. Would be faster and more convenient than locating and clicking on the block you want to set down, or pressing 'I', clicking on the block you want to use, then clicking another tool/pressing the tools keybind.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
This is what L-Shift does, currently.

**Comment by UntotenTheo** [comment]
In that case, I will close this request. Thank you for the information, have a good day.
