### ISSUE TITLE
The ability to expand base to neighboring maps in V6.00

### ISSUE THREAD

**Issue by DARK0717** [Anuken/Mindustry-Suggestions#45]
**Describe the content or mechanics you are proposing.**
The ability to expand current base to neighboring maps (V6), for ex: I build base on this hex, if i stretch a conveyor to the end of the map, there will be an indicator for the neighboring map in relation to where the conveyor is (conveyor placed east, pick a neighbor map to the right, indicator shows left side of the neighbor map).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will give Mindustry a more RPG feel to it and an actual progression in the campaign, the sense of starting out with nothing and expanding to become stronger.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by QmelZ** [comment]
creative idea, i agree with that.

**Comment by Anuken** [comment]
> if i stretch a conveyor to the end of the map, there will be an indicator for the neighboring map in relation to where the conveyor is

That sounds like you want sectors to update blocks in nearby sectors, which isn't viable. Sectors are not just hexagons on a flat plane; they're rotated and have random terrain at the edges, making any sort of conveyor 'alignment' practically impossible. Resources will be transferred between sectors, but not with any standard transport blocks.

**Comment by DARK0717** [comment]
i understand, ok
