### ISSUE TITLE
Double the Text Limit of the World Message block

### ISSUE THREAD

**Issue by UntotenTheo** [Anuken/Mindustry-Suggestions#4500]
### Describe the content or mechanics you are proposing.

The text capacity of the 'World Message' is doubled from 220 to 440, allowing more text to be inserted.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Would allow more flexible text formatting for Map Makers and/or allow more words to cram in either more details or story. Should (hopefully) be inconsequential if this change is implemented, as the 'World Message' is a mapmaking tool only available in the Editor.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SunkyMP3G** [comment]
You can use processors to put more text than the limit

**Comment by UntotenTheo** [comment]
While that can be done, yes, it isn't the most accessible thing, nor is it the most convenient.

**Comment by JamesTDG** [comment]
> You can use processors to put more text than the limit

Processors aren't exactly very pretty to use though...
