### ISSUE TITLE
Saves on smartphone

### ISSUE THREAD

**Issue by VezilierN** [Anuken/Mindustry-Suggestions#4501]
### Describe what you would like changed, and why.

Impossible de sauvegarder le jeu manuellement sur téléphone,
Même si on peut en théorie charger une sauvegarde c'est dommage.

### Describe the changes you want to propose. Include possible alternatives.

Add it

**Comment by camelStyleUser** [comment]
saves exist on mobile

**Comment by TheEt1234** [comment]
wordington suggestion
