### ISSUE TITLE
Server browser addition: Pinned/favorited servers

### ISSUE THREAD

**Issue by JamesTDG** [Anuken/Mindustry-Suggestions#4503]
### Describe the content or mechanics you are proposing.

(This is a revamped version of issue #4346)
Do the following:
1. Grant users the ability to pin specific servers in the server browser to the top, perhaps displaying similar to what a server network tab looks like. 
2. Have a way to click+drag to reorganize servers in this favorites/pinned tab
3. Directly type in IP addresses to add to the pins

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

At the moment, there is an immense number of servers available to play on for Mindustry. Sure, it is nice that the game is this popular, but it makes it difficult for someone to become a server regular, as you have to scroll around and hope you find the server you wish to join. Maybe you like CN's flavor of attack or Fish's flavor of survival, but to find them, you gotta scroll around and hope you don't miss it. The proposed feature will finally quell this slowly growing problem.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JosXa** [comment]
Closed again :( Is Trello the right place for this?

**Comment by JamesTDG** [comment]
> Closed again :( Is Trello the right place for this?

I don't think commenting suggestions there will get them noticed, but you can always reference specific Github issues if you want to try.
