### ISSUE TITLE
Improved mod accessibility

### ISSUE THREAD

**Issue by JamesTDG** [Anuken/Mindustry-Suggestions#4504]
### Describe the content or mechanics you are proposing.

Revamp of issue #4419 

Fixes desired:
1. Game does not need to be relaunched to enable/disable mods, or at the very least, the game can automatically relaunch when enabling/disabling mods.

2. Be capable of having a mod enabled while a server does not have said mod.

3. (optional) When the game updates, it holds the previous version for compatibility.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. Makes switching around mods easier for the user if they launch the game not from the taskbar

2. At the moment, users have to manually disable almost every mod they have to enter most servers, making it difficult to play with others as the current system discourages using mods since not all players want to exclusively play singleplayer.

3. Yes, this will not be as good of an idea (as mentioned by itcannotbe on issue #4419, clients will end up holding obsolete code, which can be bad), but it grants users the ability to play on servers even when the game updates, this also lifts off some weight for servers, as while they still are encouraged to update, there is at least a grace period to do so.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
Your suggestion: Consume approx. 9999 dev-hours, result: you save 20 seconds when you change mods

**Comment by nilederg** [comment]
and the update thing is another 9999999 dev-hours, assuming it's even possible

**Comment by JamesTDG** [comment]
> Your suggestion: Consume approx. 9999 dev-hours, result: you save 20 seconds when you change mods

I proposed 2 options for this, one is the part that will take time (which seems to be the only way you are reacting to this), while the other simply makes the client relaunch itself, which can be run as a simple script after the user closes the mod manager. I am willing to settle for the 2nd option when it comes to saving time.

**Comment by superdinmc** [comment]
1. Due to how game load mods, it is not possible, if he does, all the mods in the game will require major porting
2. ask the mod creator *shrug* and uh it causes lot of bugs in the game when you do that(you can also manually do it by modifying content of the mod zip/jar)
3. man, become a dev, and see how hard this is
(2nd section)
1. idk, foo exist to autorestart when mod change
2. shouldnt play mod then
3. the game need to reload to do that as said in upper 1. 
hope you understand

**Comment by superdinmc** [comment]
and uh
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/42496449/227cbc26-e02c-4e8c-876c-312928bca81a)
