### ISSUE TITLE
new variable to track the unit that last attacked a certain object

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4505]
### Describe the content or mechanics you are proposing.

scenario:
locus attacks cleroi

sensor @lastAttacker in @cleroi would return @locus

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

lets mapmakers do more cool custom mechanics via world proc

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
this would require major change of codebase since bullet hit events arent run for splash damage or are unreliable
