### ISSUE TITLE
Let fetch function the same for units as it does for buildings

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4507]
### Describe the content or mechanics you are proposing.

if you want to fetch a building, you get to choose which building its looking for
if you want to fetch a unit, you cant do that
unit bind would work great for this if the proc didnt have to be same team

proposal: give fetch unit and fetch unitCount an option to choose which unit its looking for 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

makes fetch easier to use

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheEt1234** [comment]
would be awesomeh
