### ISSUE TITLE
New planet

### ISSUE THREAD

**Issue by Dimanoname2014** [Anuken/Mindustry-Suggestions#4509]
### Describe the content or mechanics you are proposing.

I would like to add a new planet. Name: Gatrox. It will flash after passing each planet and will be available after passing all the planets.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

.... 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Rather than making this kind of suggestion with basically no idea except for the name of such, JUST MAKE A MOD YOURSELF, ~then complain how hard it is afterwards~

**Comment by NemesisTheory** [comment]
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**Comment by Lime712** [comment]
If you want to add a new planet make a pr 🕱

**Comment by c-128** [comment]
Not even describing the actual content 💀💀💀💀💀💀💀
