### ISSUE TITLE
New enemies and troops

### ISSUE THREAD

**Issue by RadioactiveRBX** [Anuken/Mindustry-Suggestions#4513]
### Describe the content or mechanics you are proposing.

New troop/enemy: Warrior, Archer, Raider

Warrior mechanic: being extremely high hp but low damage, this troop/enemy would break structures with a sword that deals more damage as the more enemies are within his range or as more hp decreases from him, he would only have 3 upgrades but it would be extremely difficult to deal with....

Archer mechanic: A low hp but high range enemy/troop. This robot/drone would shoot arrows made of any material that is more visible/in more quantity in the map...it would do low damage or high depending on the material, being the strongest arrow either Uranium (which got renamed) and being the weakest coal...

Raider mechanic: basically a group of enemy that would have a total of 4 weak Warriors... It would do double the damage to walls and defenses and his main priority would be mostly walls or gates, if defeated, the weak warriors would retreat and on the next wave bring another raid rock

This is all I have to say, soon I'll give more information but this is basically a mediaeval mode for players to try to beat and experience new mechanics other than the same annoying ones... Soon I'll give more information about this new "gamemode" like new buildings and new enemies...

It's a pleasure to be a part of the community and posting my ideas!     :)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

On my opinion this would improve the guy in a small part, being a new troop would be better and also would be more fun for players to study the troops and enemies, even though is only a small update

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
this isnt mindustry style and isnt likely to be implemented

**Comment by RadioactiveRBX** [comment]
No one knows
