### ISSUE TITLE
Better unit control

### ISSUE THREAD

**Issue by adraxe** [Anuken/Mindustry-Suggestions#4515]
### Describe the content or mechanics you are proposing.

New unit control options, all i can suggest for now is area defense, hunt for enemy unit or enemy base rush.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently most units functionality is poor, you can only get them move to certain point and attack one building, they also will auto-attack enemies in their range, it is hard to use whole army effeciently. So adding new options will improve units usage

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
All of these are possible in logic except for base rush because it is not an intended feature but a strategy and should not be a feature.

**Comment by Ruyeex** [comment]
On erekir there's no logic stuff

**Comment by Aaryan-Pugarja** [comment]
> On erekir there's no logic stuff

that makes erekir even worse then.

**Comment by RadioactiveRBX** [comment]
Finally someone agrees with me that the new control system of the Units is more difficult than 1 hit Minecraft....

**Comment by StesNiash** [comment]
no need, cause unit control is already bad and i dont want this getting even worse
theres logic for anything you want
this game is not supposed to be super easy, i think it would be horrible if you just can spam units and they will be super smart or something
and auto attack mode was in v6, but anuken deleted it btw

**Comment by adraxe** [comment]
> no need, cause unit control is already bad and i dont want this getting even worse
> theres logic for anything you want
> this game is not supposed to be super easy, i think it would be horrible if you just can spam units and they will be super smart or something
> and auto attack mode was in v6, but anuken deleted it btw

is game super easy now? or will it become super easy if units will have more functions than "go there"? most of em wont even do both things at the moment when its needed, but can do it while are manually controlled. The only good units in this situation are mono-tree, they can follow you(while attacking nearby enemies) they can repair buildings on map and rebuild destroyed ones (ground analogies dont have these options for some reason).
If you think that everything is perfect as it is -

**Comment by adraxe** [comment]
> no need, cause unit control is already bad and i dont want this getting even worse
> theres logic for anything you want
> this game is not supposed to be super easy, i think it would be horrible if you just can spam units and they will be super smart or something
> and auto attack mode was in v6, but anuken deleted it btw

I dont even want bothering myself and reply to a person who says nothing but sheet

**Comment by StesNiash** [comment]
> > no need, cause unit control is already bad and i dont want this getting even worse
> > theres logic for anything you want
> > this game is not supposed to be super easy, i think it would be horrible if you just can spam units and they will be super smart or something
> > and auto attack mode was in v6, but anuken deleted it btw
> 
> is game super easy now? or will it become super easy if units will have more functions than "go there" and attack enemies in their range? most of em wont even do both things at the moment when its needed, but can do it while are manually controlled. The only good units in this situation are mono-tree, they can follow you(while attacking nearby enemies) they can repair buildings on the map and rebuild destroyed ones (ground analogies dont have these options for some reason). If you think that everything is perfect as it is -

it will become easier
area defense - no need for turrets
hunt for enemy unit - why do even need this? (seems like already in game)
enemy base rush - you would be able to just spam units without making any commands

game would probably get easier
just get gud
(oh yeah, and i saw your other reply, thats kinda rude ya know)

**Comment by adraxe** [comment]
Why shall be game hard with castrated controls? Units not as powerful as turrets and high tiers are really expensive. Nova-tree wont do the things mono-tree can, even if he able to do it even better tho

**Comment by RadioactiveRBX** [comment]
> Why shall be game hard with castrated controls? Units not as powerful as turrets and high tiers are really expensive. Nova-tree wont do the things mono-tree can, even if he able to do it even better tho

So you prefer not knowing how the f#ck control the units than actually having the old controls?
