### ISSUE TITLE
I need newbies to play till 50% of career before getting into multiplayer.

### ISSUE THREAD

**Issue by COALROCK8642** [Anuken/Mindustry-Suggestions#4516]
### Describe what you would like changed, and why.

Anuke the real most prominent reason why MP servers are dead is because players do not understand the game and keep thinking MP will teach them.

I keep seeing griefs, idiots sending units into suicide. I want an end where players 

### Describe the changes you want to propose. Include possible alternatives.

Or each server demands player to reach certain level in campaign.

**Comment by itcannotbe** [comment]
Blame the server owners not the game.

**Comment by TheEt1234** [comment]
mp servers are dead?

**Comment by TheEt1234** [comment]
> Blame the server owners not the game.

server owners cannot pick which player goes in unless they want their server to be dead

**Comment by Aaryan-Pugarja** [comment]
well, it could be like a simple test, like "make this impact reactor work"
if they omplete the task then they are allowed to join the others, if not, then "you have been kicked for being a noob"

**Comment by Sector171** [comment]
That's obvious
I can't find any playable server cus of noobs, most good players prefer single player than playing mp because of that. It is just kill mp.

The noobs(who didn't finish the campaign yet) should only have access to the formal mindustry server.

**Comment by itcannotbe** [comment]
> well, it could be like a simple test, like "make this impact reactor work" if they complete the task then they are allowed to join the others, if not, then "you have been kicked for being a noob"

It actually that this actually works.
Some server owner manage to put this functionality in his server, and it actually filter most of the garbage out. The funny thing, it was just a silicon smelter that he used. Essentially, noobs can't make silicon apparently.

**Comment by Aaryan-Pugarja** [comment]
> > well, it could be like a simple test, like "make this impact reactor work" if they complete the task then they are allowed to join the others, if not, then "you have been kicked for being a noob"
> 
> It would actually work. Some server owner manage to put this functionality in his server, and it actually filter most of the garbage out. The funny thing, it was just a silicon smelter that he used. Essentially, noobs can't make silicon apparently.

well, when i joined as a noob in a server once, i knew how to make silicon and metaglass, but not the fancy stuff like blast compound or surge alloy.
So, a simple silicon tests seems too daft, noobs may still end up blowing some thorium reactor(hopefully, I didn't do something like that back then).
