### ISSUE TITLE
a tutorial on how to use the processors 

### ISSUE THREAD

**Issue by Diamondjj1** [Anuken/Mindustry-Suggestions#4518]
### Describe the content or mechanics you are proposing.

just like the tutorial but add in the part that tells you how to use the items instead of having to go to the wiki or somewhere else to learn how to do it

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

so more people will use the items in the campaign

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by StesNiash** [comment]
bruh, theres youtube for this
processors are boring for most people so i dont think this is needed
who want to know how to use them just goes to the youtube, or trying by themself
