### ISSUE TITLE
Additional readable info from power network

### ISSUE THREAD

**Issue by nilederg** [Anuken/Mindustry-Suggestions#4519]
### Describe the content or mechanics you are proposing.

Accessible info `@maximumProduction` and `@maximumConsumption` for logic, based purely on the amount of generators and consumers connected to the grid, not what they're actually producing or could produce

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allows for smart power management even when some generators are using automatic resource conservation or when intermittent consumers aren't consuming.
Development of logic systems which alert players when there *could* be an outage, not only when there *is* one.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
While I am confused as to why this suggestion was "denied" (Ignored), I understand that even when I volunteer to implement the change myself, it may still be too much work to approve a suggestion. In light of this understanding, I leave this suggestion to go stale.

**Comment by nilederg** [comment]
Before I abandon all hope, however, I would like to point out this suggestion has significant community support, would be useful for many more technical players, and imparts no additional work onto the developers to approve.

**Comment by JamesTDG** [comment]
This would be pretty nice NGL. Would mean that I could get grids that disable specific consumers if consumption gets too high, like a fuse box in a way.
