### ISSUE TITLE
Segment/parallax turret balancing

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#452]
**Describe what you would like changed, and why.**
The stats of the segment/parallax turrets, which currently are too weak.

**Describe the changes you want to propose. Include possible alternatives.**
30%/20% strength/range buff for parallax
50% more range for segment

**Comment by Anuken** [comment]
These were buffed recently, but not exactly in the way specified.

>  too weak too pull in air bosses

Parallax turrets are not supposed to pull in bosses. Large units have very high mass, and turrets that can exert any noticeable amount of force on them would end up practically teleporting smaller units.

**Comment by gen-NA-owl** [comment]
> Parallax turrets are not supposed to pull in bosses
Ahh I see. I originally thought Parallaxes were supposed to be used as a way to prevent bosses **kiting**, but it seems like none of the air bosses do this now.
