### ISSUE TITLE
make fog reveal radius vary per unit

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4520]
### Describe what you would like changed, and why.

a disrupt shouldnt be limited to the vision of only a dagger, especially with the range differences, scouting units could be more effective in their role if they had more vision than other units

### Describe the changes you want to propose. Include possible alternatives.

make certain units have more or less vision than others, it adds another layer of strategy to what units get made when fog of war is active

**Comment by Aaryan-Pugarja** [comment]
This is a good idea.

**Comment by Sector171** [comment]
Anticus is important cus it has good radar range.
I use them with collaris (to increase the vision+protection against air units).

Any way, this is part of "radar problem".
Definitely there should be advanced radar block + units with advanced radar features(like targeted radar)
