### ISSUE TITLE
Add core database button to mobile mindustry android/ios

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#4521]
### Describe what you would like changed, and why.

Add a core database button to multiplayer so we can have icons for stuff like displays and message blocks

### Describe the changes you want to propose. Include possible alternatives.

Add core database button to mobile multiplayer

**Comment by timich5555** [comment]
It already exists in tech tree tho

**Comment by XxsuperdeadlysniperxX** [comment]
> It already exists in tech tree tho

not on multiplayer
