### ISSUE TITLE
Add ShootX and ShootY to mass drivers

### ISSUE THREAD

**Issue by StesNiash** [Anuken/Mindustry-Suggestions#4522]
### Describe the content or mechanics you are proposing.

Add ShootX and ShootY to mass drivers cause that pretty logic i think
so ShootX and ShootY of mass drivers will send x and y of mass driver which connected to it

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will make mass drivers more useful with processors

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
mmmm yes

**Comment by nilederg** [comment]
this is a very good idea

**Comment by Mythril382** [comment]
So basically, you're making mass drivers shoot at enemy units.

**Comment by Aaryan-Pugarja** [comment]
Kinda useless, mass drivers are supposed to be automatic, a mass driver shooting at some point would be useless(I think so).
What can be worse is that griefers may use this to make mass driver go haywire.

**Comment by Aaryan-Pugarja** [comment]
> this is a very good idea

How is this a good idea? plz tell me.

**Comment by StesNiash** [comment]
> Kinda useless, mass drivers are supposed to be automatic, a mass driver shooting at some point would be useless(I think so). What can be worse is that griefers may use this to make mass driver go haywire.

![mass driver](https://github.com/Anuken/Mindustry-Suggestions/assets/111519914/e8006dec-7954-430b-afc6-44ead2e869fe)

**Comment by StesNiash** [comment]
> So basically, you're making mass drivers shoot at enemy units.

no

**Comment by StesNiash** [comment]
Possible usage for example
![mass driver2](https://github.com/Anuken/Mindustry-Suggestions/assets/111519914/ed7918d8-b23f-4b99-8c93-d10c0cd53da8)

**Comment by Aaryan-Pugarja** [comment]
> Possible usage for example ![mass driver2](https://user-images.githubusercontent.com/111519914/253754728-ed7918d8-b23f-4b99-8c93-d10c0cd53da8.png)

Why not refer to the container directly, either by using link# 0 or sensor-@x-in-container1?

**Comment by StesNiash** [comment]
> > Possible usage for example ![mass driver2](https://user-images.githubusercontent.com/111519914/253754728-ed7918d8-b23f-4b99-8c93-d10c0cd53da8.png)
> 
> Why not refer to the container directly, either by using link# 0 or sensor-@x-in-container1?
> 
> Edit: Also by making special reference statements using device drivers, its going to make it messy if you try to use it in a schematic, as Shootx+3 would be invalid if the schematic was just rotated.
> The only use I see in this is for specific cases as you mentioned above, but not for using it to make schematics.

You can't refer to container when it out  of processor range dude
I need to check items in container in processor that on load station, so I can't refer to it normally

I know about problem with rotation, but you can choose direction with diode or any other rotate able block so it won't be a problem

**Comment by StesNiash** [comment]
> So basically, you're making mass drivers shoot at enemy units.

I was thinking about different thing, but that's sounds interesting

I wonder how it would look like when you shoot 120 blast compound at sb... 

Titan Serpulo version

**Comment by Mythril382** [comment]
> > So basically, you're making mass drivers shoot at enemy units.
> 
> I was thinking about different thing, but that's sounds interesting
> 
> I wonder how it would look like when you shoot 120 blast compound at sb...
> 
> Titan Serpulo version

The bullet already collides with enemies and does not apply any effects when they hit.

**Comment by Aaryan-Pugarja** [comment]
> > > > So basically, you're making mass drivers shoot at enemy units.
> > > 
> > > 
> > > I was thinking about different thing, but that's sounds interesting
> > > I wonder how it would look like when you shoot 120 blast compound at sb...
> > > Titan Serpulo version
> > 
> > 
> > The bullet already collides with enemies and does not apply any status effects when they hit.
> 
> So anuke just need to add shootx with shooty and effects for different items in bullet

what about mix items?
if a mass driver has, say 10 blast, 18 pyro, 12 meta..., calculating using ratios to give the status effect would make the in-game calculations ugly.

**Comment by JamesTDG** [comment]
This would be interesting for introducing automated distribution hubs as a viable mechanic. So for example, if you have a Tung node away from water, you can automatically ship some to it from afar, and then have the Tungsten mines distribute its supplies to different drivers as needed.  Overflow systems could be put into place as well, since if a driver receives water but its reserves are full, it will ship it elsewhere.
