### ISSUE TITLE
Question/Feature Death Delay

### ISSUE THREAD

**Issue by Otamamori917** [Anuken/Mindustry-Suggestions#4524]
### Question 
**how does stuff die?**
- i looked everywhere for action that removes and block or unit from the world, where is it???
### Feature 
**Death Delay**
- Add a function that can delay the death of a block or unit, also make it accessible in status effects

### For Modding
I was trying to make a status effect that revives a unit to 50% HP upon death once, but it dies before it can restore the 50% HP and stops the status effect from continuing its functions
all i'm asking is `unit.deathDelay` function so i can make revival status effect

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RadioactiveRBX** [comment]
This would also make a cool mod addition for like a necromancer type unit on my opinion

**Comment by Otamamori917** [comment]
> This would also make a cool mod addition for like a necromancer type unit on my opinion

The mod I'm making the status effect for has a necromancer unit named siede lol
the revived status is for an unit named Omamori

**Comment by RadioactiveRBX** [comment]
> 

Cool
