### ISSUE TITLE
New effect/New units

### ISSUE THREAD

**Issue by RadioactiveRBX** [Anuken/Mindustry-Suggestions#4525]
### Describe the content or mechanics you are proposing.

Basically a new unit type

Elemental Units: Each one has what you are thinking, the old AI or something that YOU the player can control, they have special traits that makes them great for late game, like the freeze effect will be from the unit Freezer (god this joke was awful), or Burning/Melting from the units Flamer/Lavander (another awful joke 💀) and another cool feature!

New Effect/New way to defeat your enemies/yourself: Radioactivity/Acidicy, basically radioactivity sense is produce by some ores it should give radioactivity to the player like boosting his HP, increase on size or decreasing effects...(basically rng) this would also make a great idea for a new conveyor belt that makes radioactivity not affect the players, being crafted with metaglass, titanium, copper and silicon. It also infects any living drone.

Now talking about Acidicy... Acidicy is basically the deadlier version or radioactivity, it deals constant damage very rapidly ignoring any defense or shield the unit has, it doesn't affect flying units unless hit by the Wave or Tsunami, it could only be crafted using thorium, lava and spores at a liquid maker (new building) it could only be used by 3 units with no upgrades howsoever since they will have a passive radioactivity ability, those being Gasmasker, Runit and Mutated (I can't think of other names related to mindustry, sorry about this Anuken)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

On my opinion it would make the players more curious and adventurous being made to go to the late game slow but hard, it would be a fun addition making new game modes at the multiplayer tab and servers, new blocks and landscapes would also make the game look more like it was after the humans existed (if they still don't exist)

(I know this won't be added cuz it isn't too "Mindustry" like some people said to me but it's worth a try)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Aaryan-Pugarja** [comment]
The acid part is really good, there can be a factory for producing acid.
As for the radioactivity, being machines that would have no effect on the droids, and player too is in fact a kind of droid, so no damage to the player either.

The freezer is a bit weird idea as a unit cannot have a liquid(cyrofluid) stored inside it, why not? cuz how will it refill(logically), so instead of freezer shooting cyrofluid it can maybe blow really really cold air, which slows the enemy down significantly.

And for burning effect from units, hot air would a really bad idea I think.
