### ISSUE TITLE
New type of lighting

### ISSUE THREAD

**Issue by RadioactiveRBX** [Anuken/Mindustry-Suggestions#4526]
### Describe the content or mechanics you are proposing.

Basically a cycle of day and night that would add a glow affect to certain liquids and units, it would also make a good purpose to add a useless block lol, Torch Lighter (basically produces light for 1 energy unit/second)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Just in looks...I don't expect this to be in game but if it is I will stay like....."Oh wow my suggestion came a feature now lest continue torture" and then yeah...don't expect much from this Mindustry Unit...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Zerenta** [comment]
> torch lighter
you checked 2nd box wtf u doin its called an illuminator

**Comment by RadioactiveRBX** [comment]
> > torch lighter
> you checked 2nd box wtf u doin its called an illuminator

I literally said that is most unlikely to be added and it's useless, so stop complaining will yah?
