### ISSUE TITLE
 ㅤ

### ISSUE THREAD

**Issue by StesNiash** [Anuken/Mindustry-Suggestions#4527]
ㅤ

**Comment by Bottinator22** [comment]
We can still see what you said on Discord

**Comment by Bottinator22** [comment]
Also, if you've paid any attention to the Discord's #announcements or #development at all, Anuke isn't drunk. Anuke has often been forcing himself to work on this game, which is rather painful for him, working on something with no motivation to do so. Anuke is currently on a second break, for reasons that are probably similar.

I don't know what drove you to say this, whether you've failed a map and come here in frustration, or lost a game of PVP and blamed it on the game, or if you're just doing it for the attention.

But you should really think about what you say and do.

**Comment by TheEt1234** [comment]
he regret it

**Comment by c-128** [comment]
🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿

**Comment by StesNiash** [comment]
> Also, if you've paid any attention to the Discord's #announcements or #development at all, Anuke isn't drunk. Anuke has, in the past, been forcing himself to work on this game, which is rather painful for him, working on something with no motivation to do so. I don't know if this is still what he's doing now. Anuke is currently on a second break.
> 
> I don't know what drove you to say this, whether you've failed a map and come here in frustration, or lost a game of PVP and blamed it on the game, or if you're just doing it for the attention.
> 
> But you should really think about what you say and do.

nah, im good at pvp but still, i hate most of reworks here
as example, last redesign was horrible
RTS system is cool yeah, but its laggy as hell and anuke deleted old control system without  any possibility to return it (like game rule or something)
i say this, cause server like eviction died in v7 with RTS update (i really liked it)
oh and btw, that was kinda little joke
you need therapist or something if you really think that was insult

**Comment by StesNiash** [comment]
> he regret it

nop

**Comment by Erisfiregamer1** [comment]
How to be a dick 101
