### ISSUE TITLE
Add Tab Completion

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry-Suggestions#453]
**Describe the content or mechanics you are proposing.**
Add command TAB completion when chat like minecraft.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
With the game become more popular, commands in servers will be more (In my server, there are more than 30 without alias).
The TAB completion become necessary.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
You do realize the client are not aware of any server side commands and thus this will be unimplementable since the client just sends text to the server and the only way the server knows that it is a command is by identifying it by a prefix that you append like "/" e.i. "/sync". But to reiterate, clients don't actually know that server commands exist.

**Comment by Anuken** [comment]
As said above, the system does not support this.

**Comment by way-zer** [comment]
Simplely, send "/sy" to server,then return List like [/sync]. Like TAB completion in old Minecraft

**Comment by potatoisagender** [comment]
tab completion in old minecraft is avaliable because the commands used are part of the game. The only reason why they exist in servers is because the server went out of their way to make it so. 

Mindustry doesn't have any commands. The server didn't make an autocomplete ability. Talk to them.

**Comment by way-zer** [comment]
Why mindustry can't implement an interface for TAB completion in server? A packet request with prefix, another packet response with a condidate list. It's not hard to implement.

**Comment by way-zer** [comment]
I have already implemented TAB completion in server console.

**Comment by itcannotbe** [comment]
Have you ever seen minecraft auto complete commands from server side plugins?

**Comment by way-zer** [comment]
Yes, bukkit plugin can add TAB completion for command.

**Comment by itcannotbe** [comment]
No. It doesn't. You got native minecraft commands and bukkit commands confused.

It just so happens that bukkit commands uses the same prefix and naming as minecraft commands but they have differences.

**Comment by way-zer** [comment]
Why we can't learn from bukkit? It works

**Comment by itcannotbe** [comment]
The client doesn't even have commands in the first place.

**Comment by way-zer** [comment]
We can just send the chat input prefix to server in multiplayer mode. Then the server give a candidate list.

**Comment by potatoisagender** [comment]
that would require server side programming as well. No? I guess you could create the infrastructure, but it'd still be a lot of work.

**Comment by way-zer** [comment]
I have made a new CommandApi instead existed one in game now. But it is in Kotlin. Mindustry is writed in pure java, so it need rewrite.

**Comment by Anuken** [comment]
With a networked approach, autocompletion is viable, but that wouldn't be great for latency and I'm not particularly interested in adding more to the commands system.

**Comment by way-zer** [comment]
For latency, I suggest use cache in one completion like this:
/sy[TAB]  ----Through Net-->  Get [/sync]
/syn[TAB]  ----Use cache--> [/sync]
/sync [TAB] ----Through Net--> []
/sync  [TAB] ----Already Nothing--> []
/sy[TAB] ----Less Input,Through Net--> [/sync]
Don't need send packet every TAB.

**Comment by itcannotbe** [comment]
This would be easy for built in commands but in case of mods (in your case, 30 mods) this got a lot more difficult to implement.

**Comment by itcannotbe** [comment]
What you actually want is a way to user to display every command possible using a given prefix determined by the server. That would be friendly for both platforms.

**Comment by way-zer** [comment]
Mods can choose whether support TAB completion. Simpliy, just support command name.

About too many sharing the same first few letters, user can not accept completion and input more.

Mobile is hard work without in-game input.

**Comment by DeltaNedas** [comment]
Hacker's keyboard on mobile has tab

**Comment by itcannotbe** [comment]
That's not the point. Do you expect every has it?
