### ISSUE TITLE
More Direct Resource Usage

### ISSUE THREAD

**Issue by Ferociousfeind** [Anuken/Mindustry-Suggestions#4532]
### Describe the content or mechanics you are proposing.

If your drone (whatever you may call it) is carrying a resource, it should be able to lay those down when constructing something, in addition to having access to the cache of resources at your base.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

IDK, I've just always wanted the ability to mine copper and directly use it to build conveyors in the early game, without needing to take a potentially-time-consuming detour to the base to deposit it, only to come back and use it where I came from. Sometimes I am just short by a couple dozen copper and my infrastructure is so bad that copper isn't coming in at any appreciable rate, and I just want to use the copper ore that's right next to the line of conveyors I'm trying to build.

I could imagine a chunky drone with a few "resource slots" (to hold onto like 3-4 different types at once, say copper-lead-graphite) that can act as a mobile base instead of you being tied down to one spot (in exchange for not being able to build as much traditional infrastructure), where this mechanic is crucial for being able to build anything at all, really.

That's all really! I'm not part of the PVP scene (nor am I particularly acquainted with Erekir) so I don't know how it'd really mesh with the dynamics that may be in place there.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Sector171** [comment]
The idea is good, but....big but here:

So now you can use a drill to mine thorium for example and then you can take this thorium and build stuff WITHOUT puting any thorium in the core, do you know what this means?? This can break lot of maps.
