### ISSUE TITLE
Tech tree visibility for all players in Multiplayer games

### ISSUE THREAD

**Issue by bnooijens** [Anuken/Mindustry-Suggestions#4534]
### Describe the content or mechanics you are proposing.

Right now when other players click the tech tree they will see the message "Only the host can research items.".
However, it would be nice if they could at least see the current state of the host's research.
They would not have to be able to interact with it but just to see what materials might still be needed.

An old Trello topic (https://trello.com/c/XUj2zJnl) from Oct. 2020 described a feature similar to this but doesn't mention other players just being able to see the tech tree.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would help both host and those joining as all players could then see the current state quickly without going through all building tabs (especially for new players like what I'm currently experiencing where the other players often ask me if we can research something new and if yes, what is needed for it)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nbardavid** [comment]
This will be added, it would be so good for new players. It's complicated except to know what resources we need, etc.?
