### ISSUE TITLE
Anti-Grief Measures, must be taken

### ISSUE THREAD

**Issue by COALROCK8642** [Anuken/Mindustry-Suggestions#4537]
### Describe what you would like changed, and why.

Make default deconstruction costs to x1.0 currently at x0.7 We can handle rebuild if grief.

Why becuz map moderators cannot keep asking map submissions to set it.

### Describe the changes you want to propose. Include possible alternatives.

No alternate.

**Comment by Slotterleet** [comment]
That could indirectly break campaign balancing. By doubling (0.5x is current) deconstruct refund, you could make, say, a derelict Spectre in Nuclear Production Complex give more surge alloy upon deconstruction, or quite a few containers and vaults in Overgrowth give more titanium and thorium, which might discourage resource management in the first place. (It probably won't, but who knows.)
