### ISSUE TITLE
Unit speed multiplier

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry-Suggestions#4538]
### Describe the content or mechanics you are proposing.

Add an option to change the base unit speed in the map editor. Like an option in the units category where the unit speed can be changed only for that specific map.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

In my case I want to make a mod that adds (bad) maps that are underwater with the tantros effect and it would be cool if you could change the map unit speed so it doesen't apply to units on other maps. Changing the speed mulitplier onnthe floors is also not an option because it would also affect other custom maps with the blocks from the mods that aren't underwater.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
make a status effect and apply it with world processors.

**Comment by Lime712** [comment]
set i 0
fetch unit u @sharded i @conveyor
status false burning u 9999
op add i i 1
op notEqual @counter u null
