### ISSUE TITLE
Save files

### ISSUE THREAD

**Issue by Swagwagon** [Anuken/Mindustry-Suggestions#4539]
### Describe the content or mechanics you are proposing.

I want to start getting into mods, but I don't want to mess up my progress on the vanilla version, so I've only played modded in sandbox. It would be great to be able to mod individual save files instead of the entire game.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow the player to more easily try new things without messing up their progress.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
appdata
