### ISSUE TITLE
Easier Way To Edit The Rules Of A Save

### ISSUE THREAD

**Issue by JustAnAverageUser69** [Anuken/Mindustry-Suggestions#4541]
### Describe the content or mechanics you are proposing.

Add a way to edit the rules of a sandbox saves (or any other saves) without having to use the console

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make changing the rules much easier than having to learn coding, just to change the rules in a save inside a game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
Blud didn't check the Trello 😂🔥
[trello.com/c/1v40jFbL/708-sandbox-menu](https://trello.com/c/1v40jFbL/708-sandbox-menu)

**Comment by JustAnAverageUser69** [comment]
Meh I'll wait so that he remembers

**Comment by JustAnAverageUser69** [comment]
It's not useful
