### ISSUE TITLE
processor interface is luggy and buggy

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#4542]
### Describe what you would like changed, and why.

When i hold scroll bar near the top or bottom of the screen ui tries to move as if i was holding an instruction and it fights with the movement from the scroll bar cousing the screen to violently shake.
When i edit a code with hundreds of lines on my phone the fps drops and it becomes unbearable to do anything. And it becomes very difficult to move using the scroll bar because it becomes too sensetive.
When you add a new instruction it spawns all the way at the bottom of the code and you have to drag it to the correct place which becomes extremely diffucult if your cofe us big because the movement speed depends on your fps

### Describe the changes you want to propose. Include possible alternatives.

Optimise processor interface.
Add movement option other than the scroll bar.
Make mew instructions spawn on screen where player is looking and maybe show that they are newly added.
And fix this annoying bug

**Comment by Lime712** [comment]
device issue
