### ISSUE TITLE
Please add an hover tooltip for the materials needed in unit factorys

### ISSUE THREAD

**Issue by dandud100** [Anuken/Mindustry-Suggestions#4545]
### Describe the content or mechanics you are proposing.

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/43549788/d4d358cf-e738-490b-b5f4-3d74d06a4c65)

As a beginner it is confusing to remember all of the different materials just by a picture, pleace add an hovering tooltip to the materials needed to craft drones in this thingy.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help beginners.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
info button exists and on the screenshot it shows that unit cant be released due to unit cap

**Comment by dandud100** [comment]
> info button exists and on the screenshot it shows that unit cant be released due to unit cap

I know that the unit cap is full, this is a feature request not an issue...

On the info button there is also no tooltip for the material names.

**Comment by dandud100** [comment]
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/43549788/100f1054-051e-477b-a564-cf3dabde4cd9)
Same goes for this menu
