### ISSUE TITLE
World Radar

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4546]
### Describe the content or mechanics you are proposing.

an instruction for world proc that allows radaring from anything, with infinite range, and sorting by any metric in the game

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

would let mapmakers do more cool stuff, namely in relation to custom units

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheEt1234** [comment]
cant you radar from `@this`?

**Comment by TheEt1234** [comment]
cant you radar from `@this`?

**Comment by Sector171** [comment]
RadarFrom (x,y,r)
r=radius
This is so important instruction need to be added to wp.
