### ISSUE TITLE
A sort of rapid fire minigun like turret.

### ISSUE THREAD

**Issue by mmmboiuger** [Anuken/Mindustry-Suggestions#4547]
### Describe the content or mechanics you are proposing.

Basically, a rapid fire minigun turret, that could spew out rounds really fast. It would need both power and Cryofluid to operate, essentially making it a late game turret. The trade off is that it doesn't target air, has a tiny range, and costs a lot to build. Ammo could be Plastainuim
Pyrite
And Surge Whatever. (I forgor the name)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

So we don't have a speedy late game turret (AND I KNOW ABOUT THE SPECTRE, SHUT UP.) But I'm thinking like REAL S P E E D. Like, holy s*** speed. This would potentially fill that void. Like seriously, I know Spectre+Overdrive Come+Cryofluid exists. But I want S  P  E  E  D.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
why, late game units have armor, so spamming low damage bullets is terrible (duo deals 15% damage to reign)

**Comment by mmmboiuger** [comment]
Whoops, can I edit it, or what?

**Comment by itcannotbe** [comment]
Well, if you're suggesting a turret that has the same DPS as the Spectre while having a faster fire rate.....

**Comment by mmmboiuger** [comment]
Yep. A GAU-8 Sentry turret.

**Comment by mindustery** [comment]
cyclone

**Comment by mmmboiuger** [comment]
The cyclone targets air, this turret doesn't.

**Comment by mmmboiuger** [comment]
It's called balancing.
