### ISSUE TITLE
Additional Music Options

### ISSUE THREAD

**Issue by RustedGears18** [Anuken/Mindustry-Suggestions#4548]
### Describe the content or mechanics you are proposing.

I like the music in Mindustry, both on Serpulo and Erekir; but I think it would be cool to hear additional in-game music options. 
For example, I would love to hear the music made in a partnership between anuken and ramesesB... I personally don't know how in-game music is created or generated -or if this is even possible- I submit this because I really enjoy your game and would love to see it continue to grow and thrive.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Additional music content or partnerships can bring in new audiences, better familiarize or align players with the game and its vision and may provide a richer experience for all users. 

_I know back in 2021 Anuken said he would prefer to develop the music himself; but things may have changed since then. Bringing on volunteers or specialists who focus purely on music could be a way to delegate some tasks and expand/enrich the in-game audio content_  

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Edwardl256** [comment]
While collabs can be a neat idea, what's wrong with you opening up a playlist of ramesesB in the background?

**Comment by RustedGears18** [comment]
> While collabs can be a neat idea, what's wrong with you opening up a playlist of ramesesB in the background?

I certainly do sometimes. Just a feature request that could add to the game in the future if desired.

**Comment by Edwardl256** [comment]
What's next, have it connect to an internet radio station as well? XD
