### ISSUE TITLE
New OCT mechanic

### ISSUE THREAD

**Issue by S-s-sasha** [Anuken/Mindustry-Suggestions#4549]
### Describe the content or mechanics you are proposing.

Alright, lets get started.
Some of days i played mindustry and saw that **OCT** can take turrets loaded with ammo and they gonna shoot from the **OCT**.
What can be wrong? 
Turret have very small ammo capacity and it gonna shoot 3-6 seconds only.
And i got an idea for that problem.
You can take turret and storage with ammo and turret gonna get ammo from the storage to shoot enemies longer.
To balance it in pvp gamemodes turrets that got hold by **OCT** gonna be weaker by 30%

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Thats gonna be really cool mechanic and make oct more usefull

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
Payloads are not meant to update within units and what you saw was simply a hidden game rule re-enabled.

**Comment by Lime712** [comment]
What is "**OCT**" 💀? Also why would this feature only apply to oct? mega, disrupt, quell, quad, evoke, incite and emanate all have payload storage. Also unit payload updating is a hidden feature, which can be enabled with mods or the console.
