### ISSUE TITLE
Bring back merui recoil!

### ISSUE THREAD

**Issue by LibreBulb** [Anuken/Mindustry-Suggestions#4552]
### Describe the content or mechanics you are proposing.

I don't know if it's a bug or something, but the recoil/unit knockback of the merui when firing seems to have disappeared throughout the development of v7. Bring it back!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make merui look cooler and more organic rather than just spitting out a shell

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
It was intentionally removed, as meruis (and other units) would gradually move backwards away from their target, which made controlling them rather annoying.

**Comment by LibreBulb** [comment]
oh ok

**Comment by Anuken** [comment]
~~I don't like it either, but their behavior needs improvement for recoil to work properly~~
