### ISSUE TITLE
Launchpad

### ISSUE THREAD

**Issue by HerebecauseMindustry** [Anuken/Mindustry-Suggestions#4553]
### Describe the content or mechanics you are proposing.

While some people tend to play easily, others like to do challenges. That is why I'm proposing for the launchpad. Its only for you to build rockets on it but needs a lot of resources.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While it is just a launchpad. The only way to build rockets is to build it on launchpads. Because it is cool. (its just a launchpad so idk what else to put :P)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
~~isnt lunch pad already in the game~~

**Comment by HerebecauseMindustry** [comment]
Very much sorry

**Comment by HerebecauseMindustry** [comment]
But I'm talking about a more complex launchpad

**Comment by HerebecauseMindustry** [comment]
My other issue that has to do with this is D E S T R U C T I O N
