### ISSUE TITLE
New rockets such as: Rockets for satellites, Rockets for space stations and D E S T R U C T I O N

### ISSUE THREAD

**Issue by HerebecauseMindustry** [Anuken/Mindustry-Suggestions#4554]
### Describe the content or mechanics you are proposing.

We will talk about the first rocket which you will know. The satellite rocket is built to the corresponding parts but there will be at least 10 different types of satellites (if you can make them all) in which will have different parts of the rocket. Satellites will help in: Locating the enemies base if in a large world and give signals to new buildings to make them work. Alright next one, Space Stations.(If this feature request is too long then pls don't be lazy (: ) Space stations can make the game challenging as you may unlock new items and do experiments to get new things but your opponent might send their ships to your space station so you have to make new turrets inorder to keep the space station in orbit. Now the last one which we will call ballistic missile.i don't have to explain this because you'll already know (: .

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Other people like playing the game with some more challenging stuff so yeah.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
You did not check the trello.
