### ISSUE TITLE
Campain Like Waves in map editor

### ISSUE THREAD

**Issue by Terrarian32165** [Anuken/Mindustry-Suggestions#4555]
### Describe the content or mechanics you are proposing.

My suggestion is that we get an option to select how many waves you should complete to win on a map, just like in the campain, you have to complete a sertain number of waves to capture the sector.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This addition will make some maps more intresting.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
Install the "mapping utilities" mod if you aren't on iOS

**Comment by camelStyleUser** [comment]
> Install the "mapping utilities" mod if you aren't on iOS

This is just unneeded mod in this case
after all you can set "map ends after wave" in map rules

**Comment by camelStyleUser** [comment]
> ### Describe the content or mechanics you are proposing.
> My suggestion is that we get an option to select how many waves you should complete to win on a map, just like in the campain, you have to complete a sertain number of waves to capture the sector.
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> This addition will make some maps more intresting.
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Also if you  [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
you probably should know about map ends after wave option
