### ISSUE TITLE
please add more turrets

### ISSUE THREAD

**Issue by Hamburger695** [Anuken/Mindustry-Suggestions#4556]
### Describe the content or mechanics you are proposing.

more guns that you place on the floor like for examlpe the duo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

there isnt enough turrets and the game can get boring

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DX-36** [comment]
what
there are 18 turrets in serpulo and 10 turrets in erekir

**Comment by itcannotbe** [comment]
Anuke be like: 

"Incredible. Nobody has ever even considered suggesting More Turrets before. This is a revelation. I would never have thought of adding More Turrets myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Turrets immediately."

**Comment by mindustery** [comment]
any ideas?
