### ISSUE TITLE
New planet. Tetriarch.

### ISSUE THREAD

**Issue by Jotunheim12** [Anuken/Mindustry-Suggestions#4559]
### Describe the content or mechanics you are proposing.

Tetriarch is a entirely metal planet. Think of it being similar to Stellaris’ machine worlds

this artificial planet has natural hazards like rogue pistons that can crush both you and your units, random steam pipe ruptures, giant liquid pools that can be acid, coolant (cryofluid), slag etc.

unlike the first two planets, on Tetriarch, you will instead be organic. A mutated strain of the spore growths that plagues serpulos barren surface.

You, the creature you play as, is called the primarch. The one charged with keeping the hive safe at the start
The core will be replaced by a giant heart attached to the nearest wall by disguising biological tendrils. The heart will periodically pulse which sends blood throughout them. They are basically nodes except if you can see the tendril veins, that part can be damaged which makes them bleed when what little health it has is lost.
These veins will need to be in giant loops through special organs which harvests the necessary chemicals to re oxygenated. (can’t think of a better term for it). Loops will also increase the efficiency of certain organs.
Some unique upgrade organs can be attached to the heart to give the entire network upgrades. But require more or less blood or other resources to keep functional, 
these can span from more efficient oxygen intake to hardened chitinous plating that’d mostly just increases the health of organs. (It looks cool :) ) 
Although to keep expanding, you will need to build small pillars which will spread a unique biomass called “creep”. You cannot build organs without creep.

 Unit creation building are similar to hollow purple bones. 
 These will push out two types of creatures. 
 
The worker.
A spider who’s main purpose is construction and repairing whatever damage they can. 
These are responsible for building everything you can’t. Including walls.
They are unsurprisingly, very weak. 

the second will be a large bipedal combat melee creatures. These will have Chitinous plating with special resistances to certain damage types. If they are damaged by that damage type it’s total damage is reduced by half.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This’d require you to rely more on units not only on attacking but also on construction and repair of the base itself. The first two planets you play as machines so why not try making something even more completely different and complex.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
New planets are probably not coming into the game. Anuke has had enough with Erekir development. Try making a mod yourself instead.

**Comment by Lime712** [comment]
How does being/not being a machine affect gameplay? Making another new planet will probably take a long time,

**Comment by Jotunheim12** [comment]
You have no idea how much I want to make a mod. But unfortunately my brain just can’t take it. But hey may

**Comment by Jotunheim12** [comment]
I really wish I was able to make this myself but my brain just can’t get around coding no matter how much I try. But hey maybe, just maybe, someone will go and make this a mod.

**Comment by JamesTDG** [comment]
Honestly, this thing is a neat idea, but has feature ideas that are beyond what the dev(s) can handle.  Would be cool to see someone start development of a mod for this. I could storyboard cutscenes if anyone's interested.

**Comment by mindustery** [comment]
we already have tantaros for next update

**Comment by Ismecharles** [comment]
> we already have tantaros for next update

Yes and is secret planet (mobile can't acces this planet and other)

**Comment by JamesTDG** [comment]
> > we already have tantaros for next update
> 
> Yes and is secret planet (mobile can't acces this planet and other)

I must ask, which versions of the game have access to the files? It would be interesting to scour the files to theorize what we will get for Tantaros. Is it going to be a mix of Attack/Survival like with Serp? Is it Attack focused like Erekir? Or are we to get a whole other mode to look at? 
(Anuken, if you do come across this, please for the love of god make sure the maps are able to be played at the pace that a casual would have, the later locations on Erekir sucked because it required me to rush the enemy just so that I couldn't die. They felt like MP maps rather than core experiences.)
