### ISSUE TITLE
Add a radar block

### ISSUE THREAD

**Issue by EG0RIST** [Anuken/Mindustry-Suggestions#456]
**Add a radar block.**

It will be used to detect units (and projectiles if possible) around it. 
It is needed because people use turrets as radars, but they are not meant for that and have limited range.
Detection radius should be bigger than ripples.
Size of the block should be 2x2 or 3x3.
May need plastanium and surge (advanced level of resource).

 I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
 I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
 I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Hyperprocessors have range greater than that of ripples. Use them instead.
