### ISSUE TITLE
Scathe is bad for defense. Make it attack?

### ISSUE THREAD

**Issue by gardspirito** [Anuken/Mindustry-Suggestions#4560]
### Describe what you would like changed, and why.

Scathe is a missile launcher: it fires at a slow rate, its missiles are costly, missiles are easy to intercept, enemy units can evade them.

Scathe AI usually targets the opponent's building, either wasting carbide of its creator or completely denying the enemy from building.

The most frequent use of Scathe I can find on the web is use of it as a radar, which, fortunately, was nerfed.

### Describe the changes you want to propose. Include possible alternatives.

Make Scathe a slow and predictable anti-building missile launcher.

Reasons:
- AI targets buildings anyway
- Rockets are slow, it's easier to hit buildings with them
- Creates another (mostly ineffective) way of pressuring the enemy

Methods:
- Make missiles strong anti-building weapon.
- Make missiles actually rare. It should be possible to set up Anti-Air defenses while enemy missiles are recharging.
- Make missiles predictable. Some UI that shows where the enemy missile is going to land would be great.
- Make missiles easy to intercept on launch, but hard to intercept on hit.

### Example implementation:

Scathe takes much more carbide/other resources, has 30 second cooldown, "winds up" for 10 second before each launch, drains 100 000 (or even more) energy on launch. Fired missile targets enemy energy production or important logistics (pipes/conveyors with important materials). The missile has an unlimited range, and, when is destroyed by Anti-Air defenses, splits into multiple mini-missiles, losing 1/2 or original damage. Mini-missiles have a maximum range of 20–40 blocks and gain a brief period of invincibility (something like 5 blocks of flight), during which they can neither detonate, nor be targeted by AA. When destroyed, mini-missiles further split into mini-missiles with lower damage, and so on.

Mini-missiles do not target a single block. Instead, they target a random block within some radius of their original target.

It's best to make all the missiles launch at the same time for one team. So when there are 3 teams on the map, all Scathe's of team A fire at the same time at clock time 10, 40, 70, 100, 130, 160, etc; team B fire at clock time 20, 50, 80, 110, 140, 170; team C fire at clock time 30, 60, 90, 120, 150, 180, etc.
This way, it is possible to set up AA defenses (so missiles do not shoot every 5 seconds and destroy everything the player hasn't finished building yet), existing AA defenses are easily overloaded, players are kept nervous, and not too many missiles are on the screen at the same time. 

### Countering the missiles:
There are three approaches.
1. Place AA far from the base to intercept the missile.
2. Place AA *just* aside of the building that needs to be protected. This way, mini-missiles will just disappear on hit due to invincibility and not explode.
3. Shockwave tower. Shockwave tower doesn't break missiles (or maybe only a little), but redirects them into random location within X blocks of target.

### From the attacker's perspective
Missiles are great for destroying logistics. Even when split into mini-missiles, these things easily destroy pipes and conveyors in a huge range. They require some change in tactics to be countered.
Overall, Scathe in this modification is a support turret, which can't be used to destroy enemy base (if they have at least any air defenses, its performance rapidly degrades but hardly ever goes to 0), but make it harder for enemy to advance and supports allied units in their attack. At the same time, huge energy consumption of Scathe on launch can become a problem if not taken into consideration.

P.S.: I'm not sure what to do if I come up with other balancing ideas about Scathe. Should I post them here, or close this one and open a new issue? I guess the new one.

**Comment by Bottinator22** [comment]
Scathe's massive range can come in useful for defending bases you're still building from higher tier units. But it's already more of an offensive turret.
