### ISSUE TITLE
tall walls

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4563]
### Describe the content or mechanics you are proposing.

walls that can block flying units (or crawlers if that's hard to balance)  

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it could be used to help control the pathfinding of units as it can be annoying when a few arkids sneak past your defence by going past your other wall

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Aaryan-Pugarja** [comment]
the sense of "flying" unit and "can step over most terrain" would be almost nullified, since people may spam these if this gets added.

**Comment by itcannotbe** [comment]
OP be like: Actually defending the area with turrets/units < Suggesting a player placeable wall that prevents every unit from passing through.

**Comment by mindustery** [comment]
it could also block friendly bullets

**Comment by mindustery** [comment]
and hp is temporary
