### ISSUE TITLE
neoplasm turret

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4565]
### Describe the content or mechanics you are proposing.

a turret that uses neoplasm as ammunition 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it could be a cool way to get rid of neoplasm that is also balanced by the fact that it would be an inconsistent way of getting rid of neoplasm   

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JamesTDG** [comment]
It honestly is weird to have a waste product that has no use case other than MAYBE trolling some adversary's setup that uses water.

**Comment by itcannotbe** [comment]
It honestly is weird to have a waste product that has a use case other than maybe trolling some adversary's setup that uses water.

It's a waste product that's supposed to be not easy to dispose of.

**Comment by JamesTDG** [comment]
> It honestly is weird to have a waste product that has a use case other than maybe trolling some adversary's setup that uses water.
> 
> It's a waste product that's supposed to be not easy to dispose of.

The issue there is that disposal is absolutely easy to do, just pour it into a slag pool (or incinerator) or a 3x3 area and you're done, there's literally zero challenge in handling the waste. Each time I build this machine, there is no challenge, just a mild annoyance that I am generating a product that I can just infinitely dump
