### ISSUE TITLE
a block that loads units onto payloads

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4566]
### Describe the content or mechanics you are proposing.

as is described in the title 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

well having no way of putting units back on payloads is slightly unforgiving and it could be useful for logic contraptions 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
logic can already put units inside reconstructors and payload conveyors
you can "enter" a payload conveyor to make currently controlled unit go onto the payload conv

**Comment by mindustery** [comment]
i did not know that thank you

**Comment by JamesTDG** [comment]
> logic can already put units inside reconstructors and payload conveyors you can "enter" a payload conveyor to make currently controlled unit go onto the payload conv

It would be nice to not need to use logic to achieve this. EX, you can command a unit to just go to a payload conveyor and it will automatically enter it. This could be useful for making reconstructors use space more efficiently.

**Comment by mindustery** [comment]
very true

**Comment by Aaryan-Pugarja** [comment]
> ### Describe the content or mechanics you are proposing.
> as is described in the title
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> well having no way of putting units back on payloads is slightly unforgiving and it could be useful for logic contraptions
> 
> ### Before making this issue, check the boxes below to confirm that you have acknowledged them.
> * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
> * [x]  I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .

**Comment by JamesTDG** [comment]
> I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .

I believe you are familiar with the difficulty of using payloads for precision tasks though, right? It is a pain to target something using a giant ship to drop a payload onto a conveyor. Also, I don't think Octs are reliable for transferring a unit from 1 refabricator to the next due to their speed. Also, I don't know if this can be done on Erekir with its flying units (however I have yet to try this to verify)

**Comment by Aaryan-Pugarja** [comment]
> > I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .
> 
> I believe you are familiar with the difficulty of using payloads for precision tasks though, right? It is a pain to target something using a giant ship to drop a payload onto a conveyor. Also, I don't think Octs are reliable for transferring a unit from 1 refabricator to the next due to their speed. Also, I don't know if this can be done on Erekir with its flying units (however I have yet to try this to verify)

Well, you could make a logic to make units with payload capacity to pick up units and put them on payloads or directly in the fabricators, also you could make a logic for t1/t2/t3/t4 to move to the fabricator themselves and enter the payload/fabricator.

**Comment by JamesTDG** [comment]
> > > I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .
> > 
> > 
> > I believe you are familiar with the difficulty of using payloads for precision tasks though, right? It is a pain to target something using a giant ship to drop a payload onto a conveyor. Also, I don't think Octs are reliable for transferring a unit from 1 refabricator to the next due to their speed. Also, I don't know if this can be done on Erekir with its flying units (however I have yet to try this to verify)
> 
> Well, you could make a logic to make units with payload capacity to pick up units and put them on payloads or directly in the fabricators, also you could make a logic for t1/t2/t3/t4 to move to the fabricator themselves and enter the payload/fabricator.

Not all things should need to use logic. If its using logic to cheese something, I'll allow it, but if it is to enable automation (mining, transit, etc.), I think it needs to not use logic, especially since logic locks people out of being able to control units.

**Comment by Aaryan-Pugarja** [comment]
> > > > I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .
> > > 
> > > 
> > > I believe you are familiar with the difficulty of using payloads for precision tasks though, right? It is a pain to target something using a giant ship to drop a payload onto a conveyor. Also, I don't think Octs are reliable for transferring a unit from 1 refabricator to the next due to their speed. Also, I don't know if this can be done on Erekir with its flying units (however I have yet to try this to verify)
> > 
> > 
> > Well, you could make a logic to make units with payload capacity to pick up units and put them on payloads or directly in the fabricators, also you could make a logic for t1/t2/t3/t4 to move to the fabricator themselves and enter the payload/fabricator.
> 
> Not all things should need to use logic. If its using logic to cheese something, I'll allow it, but if it is to enable automation (mining, transit, etc.), I think it needs to not use logic, especially since logic locks people out of being able to control units.

why the hell would a player want to control a unit if it has to be upgraded? Logic exists so that people can make things according to their comfort and more.

**Comment by JamesTDG** [comment]
> > > > > I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .
> > > > 
> > > > 
> > > > I believe you are familiar with the difficulty of using payloads for precision tasks though, right? It is a pain to target something using a giant ship to drop a payload onto a conveyor. Also, I don't think Octs are reliable for transferring a unit from 1 refabricator to the next due to their speed. Also, I don't know if this can be done on Erekir with its flying units (however I have yet to try this to verify)
> > > 
> > > 
> > > Well, you could make a logic to make units with payload capacity to pick up units and put them on payloads or directly in the fabricators, also you could make a logic for t1/t2/t3/t4 to move to the fabricator themselves and enter the payload/fabricator.
> > 
> > 
> > Not all things should need to use logic. If its using logic to cheese something, I'll allow it, but if it is to enable automation (mining, transit, etc.), I think it needs to not use logic, especially since logic locks people out of being able to control units.
> 
> why the hell would a player want to control a unit if it has to be upgraded? Logic exists so that people can make things according to their comfort and more.

When someone uses logic to send units to refabs, they usually also have an AI logic that locks people out of commanding them. Familiar with that one Corvus AI schem? RTS controls were added to reduce the need for AI to command units, but I shouldn't have to find the right string I have to use to send a unit onto a payload conveyor or refab.

**Comment by Aaryan-Pugarja** [comment]
> > > > > > I think what you are referring to is already present in the form of payload pickup by units like megas, quads and octs .
> > > > > 
> > > > > 
> > > > > I believe you are familiar with the difficulty of using payloads for precision tasks though, right? It is a pain to target something using a giant ship to drop a payload onto a conveyor. Also, I don't think Octs are reliable for transferring a unit from 1 refabricator to the next due to their speed. Also, I don't know if this can be done on Erekir with its flying units (however I have yet to try this to verify)
> > > > 
> > > > 
> > > > Well, you could make a logic to make units with payload capacity to pick up units and put them on payloads or directly in the fabricators, also you could make a logic for t1/t2/t3/t4 to move to the fabricator themselves and enter the payload/fabricator.
> > > 
> > > 
> > > Not all things should need to use logic. If its using logic to cheese something, I'll allow it, but if it is to enable automation (mining, transit, etc.), I think it needs to not use logic, especially since logic locks people out of being able to control units.
> > 
> > 
> > why the hell would a player want to control a unit if it has to be upgraded? Logic exists so that people can make things according to their comfort and more.
> 
> When someone uses logic to send units to refabs, they usually also have an AI logic that locks people out of commanding them. Familiar with that one Corvus AI schem? RTS controls were added to reduce the need for AI to command units, but I shouldn't have to find the right string I have to use to send a unit onto a payload conveyor or refab.

well, as far as I can tell, not majority or even a good fraction of players want this feature(and not me as well), sorry to say man, but I don't think this would be even considered by Anuken.
