### ISSUE TITLE
an explosive wall

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4567]
### Describe the content or mechanics you are proposing.

a wall made of blast compound that explodes when destroyed

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would be funny to have your defence explode at the slightest touch 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Aaryan-Pugarja** [comment]
that would be terrible, cuz walls are meant to protect not blow up.

**Comment by mindustery** [comment]
its meant to be funny

**Comment by TheEt1234** [comment]
from my experience anuke doesnt add things which are solely just "funny", don't flood the suggestions with this crap
