### ISSUE TITLE
Swarmer with Tsunami(water) is overpowered and should be NERFED.

### ISSUE THREAD

**Issue by Aaryan-Pugarja** [Anuken/Mindustry-Suggestions#4568]
### Describe what you would like changed, and why.

As the title says, swarmer with tsunami is overpowered, it makes big and expensive turrets like spectre and meltdown useless and obsolete, it seems pretty useless to have a cheap and small turret better than the big and expensive turret.

### Describe the changes you want to propose. Include possible alternatives.

Swarmer can be nerfed by lowering fire rate, range, damage effects.

**Comment by mindustery** [comment]
what if they removed cyclone and swarmer shocked debuff?

**Comment by Absolutan115** [comment]
Or make shock wet Reactive damage from 14 to 10

**Comment by jehosula** [comment]
> Or make shock wet Reactive damage from 14 to 10

that's a good nerf
