### ISSUE TITLE
Vector shooting for droids and turrets.

### ISSUE THREAD

**Issue by Aaryan-Pugarja** [Anuken/Mindustry-Suggestions#4569]
### Describe the content or mechanics you are proposing.

Instead of telling the turrret to shoot at some (x,y), it can be instead of shooting in the direction of the vector provided, with the droid/turret itself being the frame of refrence.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can make it easier to tell the droid/turret where to shoot instead of providing it coordinates that are out of its range and results in making the logic unnecessarily complex. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JamesTDG** [comment]
This would be pretty neat, but the old (x,y) feature should retain its functionality since the range of a turret extends 1-2 blocks outside its radar.
