### ISSUE TITLE
accounts

### ISSUE THREAD

**Issue by ximberguenxa** [Anuken/Mindustry-Suggestions#457]
accounts with which we can save our progress of the campaign and schematics

that would greatly improve the gaming experience since we could continue playing on our mobile or on another computer without worrying about not being able to continue our game

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This is in the "do not suggest" list.
