### ISSUE TITLE
New Menu popup

### ISSUE THREAD

**Issue by RadioactiveRBX** [Anuken/Mindustry-Suggestions#4574]
### Describe the content or mechanics you are proposing.

Basically every update of something in game or bugs patched should be shown in a pop up menu saying what the update includes,bright when the play starts the game. Only one time though but it could be checked at any given time with another button saying "Update" and when clicked the same pop up would show up

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

As some players (mostly mobile) don't check what's new in the play store when updating, I think they should know atleast what is new in game, reminder that this feature would be really small and unlikely to be added

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JamesTDG** [comment]
So, a visible changelog?
