### ISSUE TITLE
Fuse Blocks!

### ISSUE THREAD

**Issue by JamesTDG** [Anuken/Mindustry-Suggestions#4575]
### Describe the content or mechanics you are proposing.

A block that can be programmed to disable power to a part of a grid if consumption gets too high. This can be achieved with processors, kinda, but we know that not all players want to deal with processors to handle certain jobs. Would work well in conjunction with issue #4519, since this tag could interact with the block to fine-tune inputs and outputs.

(ok, this is starting to just sound like the battery diode on crack)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would act as a way for players to implement safety nets into their power grids. here are a few examples:

- A section of your power grid needs an existing source of power to stay functional (Thorium reactors for example need cryo, which needs power to be made), if your system eats up too much power, you can have power that is painful to recover. 
- You have a unit factory, but you want to not use too much of your grid
- You want to test how efficient your schem is when it is not adequately powered

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If you knew how battery diodes work, you don't need this.

**Comment by itcannotbe** [comment]
> > If you knew how battery diodes work, you don't need this.
> 
> You can't control the power delivery or have smart shut-offs.

How sure are you?

**Comment by JamesTDG** [comment]
> > > If you knew how battery diodes work, you don't need this.
> > 
> > 
> > You can't control the power delivery or have smart shut-offs.
> 
> How sure are you?

Pretty sure I can't have a diode only transfer 50k power from a grid that has 100k power available. I can't have a specific part of my system shut down if a setup eats too much power

**Comment by itcannotbe** [comment]
> > > > If you knew how battery diodes work, you don't need this.
> > > 
> > > 
> > > You can't control the power delivery or have smart shut-offs.
> > 
> > 
> > How sure are you?
> 
> Pretty sure I can't have a diode only transfer 50k power from a grid that has 100k power available. I can't have a specific part of my system shut down if a setup eats too much power
> 
> If I am making an ass of myself with this, then there's a problem with how the Battery Diode is told to the user on how it functions, there's no interface, it just looks like a way to have one-way power delivery.

1. It doesn't send power.
2. It not even limited to 50k

**Comment by JamesTDG** [comment]
> > > > > If you knew how battery diodes work, you don't need this.
> > > > 
> > > > 
> > > > You can't control the power delivery or have smart shut-offs.
> > > 
> > > 
> > > How sure are you?
> > 
> > 
> > Pretty sure I can't have a diode only transfer 50k power from a grid that has 100k power available. I can't have a specific part of my system shut down if a setup eats too much power
> > If I am making an ass of myself with this, then there's a problem with how the Battery Diode is told to the user on how it functions, there's no interface, it just looks like a way to have one-way power delivery.
> 
> 1. It doesn't send power.
> 2. It's not even limited to 50k

I think you misunderstood me, I used the 50k of 100k as an example of controlling the grid, not a specific requirement of the diode. Like I want its interactions to work similar to the Create stockpile observer in a way.

**Comment by itcannotbe** [comment]
That's the beauty of battery diode, it doesn't require any further setup by the user.

And since it doesn't send power, you won't worry about getting you main grid get shutdown due to over consumption of blocks on the receiving side of the battery diode.
