### ISSUE TITLE
Arkyid should have eight Legs

### ISSUE THREAD

**Issue by EPICGUPPY44** [Anuken/Mindustry-Suggestions#458]
**Describe the content or mechanics you are proposing.**
the Arkyid upgrade should have 8 legs

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
well you see, before the arkyid is the spiroct which has taken the role first to have six legs. and the upgrade before that, the atrax has four legs. so as it goes up in twos, I think it would make sence for the Final form to continue and have 8 legs

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
it already does
