### ISSUE TITLE
bring back latum and renale

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4582]
### Describe what you would like changed, and why.

latum was a really cool unreleased unit that would have been an excellent addition to the game functioning as a tank (figurative) and a main attacker with cool synergies with neoplasm but it was sadly never implemented 

### Describe the changes you want to propose. Include possible alternatives.

bring them back no matter how many nerfs are needed we want latum

**Comment by NemesisTheory** [comment]
They are implemented, and they were never removed, just hidden (~~rtsc~~)

**Comment by UnionofSovietSocialistRepublics** [comment]
Don't let bro cook again
