### ISSUE TITLE
tidal (wave t3)

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4583]
### Describe the content or mechanics you are proposing.

tsunami but with more range and the ability of having higher dps depending on how close enemies are to it (as high enough pressure water can cut through anything) up to the point of having higher dps then a surge cyclone against wet enemies. can only use water.   

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it could be fun to have a turret with gimmicks as we have none of them 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by UnionofSovietSocialistRepublics** [comment]
Who let bro cook

**Comment by TheEt1234** [comment]
surge+water combo i believe was an oversight

**Comment by mindustery** [comment]
oh yes i did forget about that

**Comment by DX-36** [comment]
tsunami is already good as it is

**Comment by mindustery** [comment]
> tsunami is already good as it is

not for damage

**Comment by DX-36** [comment]
it does not need to be a damage dealer
