### ISSUE TITLE
Discord suggestion: #curated-maps (i dont know where to put this, i apologize)

### ISSUE THREAD

**Issue by TheEt1234** [Anuken/Mindustry-Suggestions#4584]
### Describe the content or mechanics you are proposing.

a #curared-maps channel for the mindustry discord channel

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Why? 

to make good maps easier to find and discuss

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Larofeticus** [comment]
Yes, this. I independently arrived at the same idea today. Are we best friends now?!

**Comment by overdramaticpanromantic** [comment]
An epic and awesome and spectacular and good idea. Yeag
