### ISSUE TITLE
Hardware bans

### ISSUE THREAD

**Issue by Xaocsoul** [Anuken/Mindustry-Suggestions#4585]
### Describe the content or mechanics you are proposing.

Basically it stops someone from joining a server with a certain device

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help stop ban evaders on servers. Every server has them and they are near imposible to stop since they can just bypass every type of ban already in the game. Hardware bans would stop them from doing that.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
UUIDs are already hardware based, but the thing is nothing is preventing anyone from sending manufactured UUID, It's an open source game, anyone can look at the code and see how bans are handled and create ways to bypass it.
