### ISSUE TITLE
Option to create own function/library and use them in logic

### ISSUE THREAD

**Issue by Aaryan-Pugarja** [Anuken/Mindustry-Suggestions#4586]
### Describe the content or mechanics you are proposing.

For long logic, there can be a feature to create functions of your own using already present logic, so that one doesn't have to copy the same part of a logic over and over again,

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this can make logics clean and easy to make for most.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by gardspirito** [comment]
It's better to just write a compiler outside of the game if you want such functionality, because in-game logic is just some kind of Assembly.
