### ISSUE TITLE
slag reactor

### ISSUE THREAD

**Issue by mindustery** [Anuken/Mindustry-Suggestions#4587]
### Describe the content or mechanics you are proposing.

uses slag, oil, and cryofluid (coolant) to make 500 power units per second explodes if insufficient coolant is provided sending flaming oil everywhere (within 20 block radius)  

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

there are no good mid game generators (don't you even mention differential) so it would work as one 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NemesisTheory** [comment]
### Steam Generator 
..just the Slag Reactor but better in every way imaginable
###  Differential Generator
Maybe slightly harder to set up, but at least it doesn't explode
### Thermal Generator
#
..is there really any need for this 'Slag Reactor'?

**Comment by mindustery** [comment]
more power

**Comment by NemesisTheory** [comment]
500 power is meaningless when 2 steam gens output more

**Comment by mindustery** [comment]
not if each reactor uses low amounts of slag an cryo

**Comment by Aaryan-Pugarja** [comment]
> more power

there are already better options, like NemesisTheory said above, there is just no reason why this should be added, THREE INPUTS just to get 500 power, thats trash power bro. Also most maps(campaign AND multiplayer), don't have slag floating around.
