### ISSUE TITLE
Temperatura 

### ISSUE THREAD

**Issue by Fewcristofer** [Anuken/Mindustry-Suggestions#4588]
### Describe the content or mechanics you are proposing.

La mecánica es la temperatura del mundo y las maquinas

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

La temperatura puede indicar que las máquinas pueden llegar a temperaturas alta y bajas donde afecte la jugabilidad o las máquinas de extraer minerales o liquidos y incluyendo las máquinas que atacan, que no se como se llama perdón, pero si esta frío el lugar se pueda ralentizar las maquinas por el frío y si esta caliente el lugar pueda dejar de funcionar o volverse lenta también, pero si la maquina está super calienta y el lugar está frío tiene mejor eficiencia porque se enfría y no se sobrecalienta y eso es una idea o mecánica y también casi se me olvida que también puedes ver la temperatura del mapa completo y incluyendo las máquinas y otras.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Fewcristofer** [comment]
Para mindustry

**Comment by Fewcristofer** [comment]
Para mindustry

**Comment by camelStyleUser** [comment]
does anuke even know spanish
