### ISSUE TITLE
Multi-Hex Multiplayer

### ISSUE THREAD

**Issue by Eldog02** [Anuken/Mindustry-Suggestions#459]
**Describe the content or mechanics you are proposing.**
I saw the 6.0 teaser on steam and was immediately reminded of RTS games like Planetary Annihilation as well as turn based ones like Civ. A clear picture of a cool multiplayer mode quickly emerged in my mind. 

I propose a multiplayer "campaign" map spanning over multiple hexes. Players could play concurrently in different hexes and/or in the same hex much like the current multiplayer system. Each hex would act as an "instance" wherein it would play much like the current multiplayer, and you could swap between them much like switching levels.

Players could choose their starting hex for their core and then continually expand to nearby hexes to gather more and more resources and grow their production, eventually pushing against the enemy's hexes with their forces to try to take the core.

Some sort of map display as to which hexes were under attack and a quick way to respond would likely be a must in this gamemode, to prevent surgical sneak-attacks from being too powerful. Maybe some sort of radar you could place that would allow you to see other players in a hex on the map?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The idea of hex/instance based multiplayer is interesting because it appears to me to be rather scalable. A small map with only a few hexes nestled together could be good for a 1v1 or 2v2, but an entire planetary war could be played on a dedicated server over time.

This would also allow players to play the roles that most interest them, whether it be sitting in the back lines engineering new production solutions or upgrading the base, or commanding a battalion of land, air, or sea units to disrupt enemies and cripple their economy. Hell, you could easily be a sort of battle engineer frantically scrambling to upkeep your defenses and hold the line.

**I'm aware my idea isn't entirely fleshed out but I wanted to get the idea out there. I think this would be a unique concept that would be cool to discuss and flesh out more.**

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by D-player1** [comment]
Lmao there's already a server about that

**Comment by ShadeStrike62** [comment]
this is one of the best ideas I have read, there is a server like this, that runs a gamemode called Hex PVP, but this is way better and far more like an RTS
