### ISSUE TITLE
Sensor for Unit tier

### ISSUE THREAD

**Issue by TopCatTC** [Anuken/Mindustry-Suggestions#4592]
### Describe the content or mechanics you are proposing.

A sensor so that we can get the tier of a unit (1, 2, 3, 4, 5)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Right now the only way to get the tier of a unit is by looking at its health, A simple @tier function would add a clean method of getting the tier of a unit from radar or Uradar for example.

sensor uTier = @tier in @unit

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Zerenta** [comment]
@type exists

**Comment by Aaryan-Pugarja** [comment]
> @type exists

so if I wanted to build a targeting system for units and want them to only attack t4 and above I would have to fucking use @type in a loop for all the T! AND T2 AND t3 units,. So yeah @type exists but it ain't useful all the type.
