### ISSUE TITLE
Build Queue Improvements

### ISSUE THREAD

**Issue by Zircane** [Anuken/Mindustry-Suggestions#4597]
### Describe the content or mechanics you are proposing.

Planning out what you build isn't as smooth as it could be.
Sometimes the game inadvertently fails to place your buildings properly and you have to fix it yourself.
These problems include (In order of most importance to least important but still nice):

- Automatic Block Suggestion only works on already placed buildings and not on queued buildings which makes routing out conveyors/ducts much harder than it necessary
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/d02ba9e0-e852-4d95-81ae-0261cb190fa7)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/c31e06a6-6d61-4f00-9997-2f54b5b0ee65)
> This one might be a bit complicated to pull off both because the junction isn't directional and because sometimes you really just want to turn the junction into a conveyor/duct/conduit so it may require some extra effort in the form of checking nearby conveyors/ducts/conduits that the junction is in contact with both parallel and perpendicular.

___
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/41b6017a-7d69-49e4-83b9-e46276aa933d)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/92947fc1-5b3b-4b25-9ccf-887794e4ac68)
> It sucks either having to wait for the building to finish before continuing or having to manually place the other distribution blocks (especially bridges)

- Build Plan is reset on death or when entering another host(or core defender) 
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/0bbecdfc-3c95-4405-be1a-cb2e3aa575d2)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/c8907077-0339-4b78-b74a-a97db19bce5f)
> Having your entire plan wiped basically wasting all the time you spent making them because you died or changed hosts is irritating.

> This applies much more to Serpulo where its possible you'll face death while trying to build or at least plan to do so however it also applies to Erekir where you wish to quickly move to a core being attacked only to have all of your building plans removed

> Also an additional note: Entering a unit that can't build should just turn the entire plan red but when entering a unit that can build again would make it available again

- Automatic Block Suggestion sometimes doesn't work when trying to path around other non duct/conveyor/conduit distribution blocks

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/75a426a1-d642-4407-af1b-3899d523efa1)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/4d48e9e1-ceb6-40db-9f7a-a4c1e3ae4c44)
What it Should do:
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/4c9739a0-b079-4847-9d67-77ad44bb7df4)

> Same as the junction one from above
_____
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/250871ee-078e-4fe4-8863-f2f01d9561d2)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/ccbde85a-a4a9-4562-9c18-9af6a9475e26)
What it Should do:
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/e700b660-56c2-4353-84b8-f5d22459e577)

____
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/4c82a71c-b925-45b9-b314-e305992a982c)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/586ae5be-c40b-43db-873b-5b2963410dcf)
What it Should do:
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/48543787-2154-4e08-8d8e-4fca14a05628)

__
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/28ec4f30-869d-483d-9dcd-dbbe0cbbd0e6)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/fbfd0d2f-ab25-436f-b21c-a2ea4aaf1ef3)
What it Should do:
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/f8710390-e1d1-4e52-a40d-ed87da157f2b)

- Basically the same as the one above but it instead forgets that it needs to add bridges when trying to path past distribution blocks (like unloaders and routers etc.) And instead of pathing past them with bridges, overwrites them
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/d9baae19-9e80-4d86-8cce-222ec6c3a911)
It properly turns the ducts into bridges when placing through the beam node but not through the unloader and underflow gate (Im guessing its because it shares the same class (distribution blocks) and thus the automatic block suggestion gets overwritten by same class replacing.)

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/cba204c8-61ff-4ebe-b5ca-b8d6ae340e01)

(The same class placement i'm referring to is this
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/9ad81c96-da91-4f46-ad13-8faf7a99a1bc))
Its the same feature that allows wall upgrading and conveyor changing (titanium to plastanium or duct to armored duct)

___
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/748b6aa5-16a0-48c0-8287-3128d81360dd)

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/f7308a2e-6808-496a-8359-5071b23eee78)

- Bridge pathing is quite janky, it just thinks that any duct that is facing parallel to the ducts you are trying to path is an instance where you need to place a bridge and doesn't take into account whether the bridge will connect to any other bridge

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/ca2a4cfb-a68d-4a9d-acdc-380895ec818a)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/bf6888c1-b19c-4878-84cc-3c03cb6997f2)
___
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/bc055d2e-2c42-404b-a87c-423cf76bc8bd)
In this instance it basically ruins the already placed bridge because it has no regard whether there is or there isn't a possible connection at the end.
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/6439387b-132d-4a76-81ec-bba7db1e5d4f)
What it Should do:
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/55d2ec78-1d67-419b-8f5e-18824e5e11d9)

> This might be harder to implement but it would make accidentally pathing ducts wrong less common.

- Diagonal Placement Feature for Ducts/Conveyors/Conduits should support placing distribution

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/52f3ffd1-6c6b-455b-b089-66d9fd5ac6a4)
> Additionally is to polish it a bit more but it might be difficult to do so.

`Disclaimer: There are obviously a lot more distribution blocks and stuff that I haven't mentioned that bug out in this way but finding the other blocks should be much easier once we know what were looking for.  For instance, routers can be substituted with overflow, underflow, sorters etc.`

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

These changes might only affect a couple groups of people (mainly pvp communities and speed-running communities) and isn't too big of a change to the casual and overall player-base however I think it's a step towards making the game more polished and feel good to play.
I personally want these changes because it doesn't seem too hard to pull off and it sounds like something that will eventually be implemented in the future anyway.
Not all of the changes can be implemented but I still think some should be given the pass.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by overdramaticpanromantic** [comment]
i think this is a good thing to add but anuke likely won't do it without a pull request

**Comment by Aaryan-Pugarja** [comment]
This is actually something that has bothered me while building, nice of you to put it as an elaborate request.

**Comment by Zircane** [comment]
i just realized this isnt the pr section
my bad!!!!
