### ISSUE TITLE
Erekir version of start background

### ISSUE THREAD

**Issue by LibreBulb** [Anuken/Mindustry-Suggestions#4598]
### Describe the content or mechanics you are proposing.

like the normal background but there is a chance (probably 50%) that instead of the serpulo generation with serpulo units flying around we have erekir generation instead with flying erekir units.

if you ever decide to make tantros, the same thing could be done but with a 1/3 chance for each planet background instead.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it looks cooler, and makes sense as if there are 2+ planets in the game then why is only serpulo showcased

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by overdramaticpanromantic** [comment]
yeag

**Comment by The4codeblocks** [comment]
Maybe it could be related to the last planet you played on.
It would be 50/50 if the map you just played on is mixtech.
