### ISSUE TITLE
Payloads damage

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4602]
### Describe the content or mechanics you are proposing.

Taking in mind that there's many issues with balancing units with payloads and hidden feature to update blocks in payloads, I've come to a ~new~ feature - instead of just block/unit types to make unit and buildings payload as actual blocks units with ability to channel damage dealt from host to payload first.

If building or unit with payload got under fire, the damage is dealt to first item in the payload until it's destruction. Units can't be damaged until they run out of payload, payload belts can't be targeted if they had payload over them and unit factories can survive for longer channeling damage to the units inside. 

And also (dunno how) for balance reasons make a deployment status for units, so all deployed units from factories and yet to deploy (untill unit cap) has active status and can shoot back from payloads. Units in factories, payload belts or if picked from those by other units has suspended status and can't shoot back/provide abilities if they're over the unit cap.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Some use cases:

Block will be used as additional defense or offense for flying ships. Picking walls will temporarily extend unit HP for longer survival until that walls will be destroyed first, turret provides less defence but some additional ability to fight back. 

Payload belt defense will be usable as actual combat cause to damage the belt itself there has to be no blocks or units loaded on it.

Change the way of storing units over the cap in long payload belts. Shooting the belt won't release all stored units at once and all production won't be shut down cause of some crawler destroying payload in chain.

Some unique combinations with payload units like picking up quazars for additional shield and piercing damage or brydes for additional reach. Or, well, literally crawler bombing.

This will deal with building bombing mechanics where units can pick liquid blocks with flammables inside.  

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by bnooijens** [comment]
Sounds good to me, it might also help with the single belts that get destroyed in attacks making it less likely to happen.
