### ISSUE TITLE
Add infinite maps

### ISSUE THREAD

**Issue by Futuray-pgm** [Anuken/Mindustry-Suggestions#4609]
### Describe the content or mechanics you are proposing.

Can you add the possibility to create an infinite map. We start with a simple core surrounded by low-level ores. Then, we explore and discover more and better ores. But there are outpost of enemies how can attack and destroy us. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

We just had to clic on `new infinite map` in `Custom game` then, we choose some parameters (like magnitude and seed). Mindustry generate a ~100x100 block base map and when we go close of the border, the game generate more terrain with better ores and more enemy. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jamespire** [comment]
wouldnt that get laggy after a while? Otherwise its a good idea and i support it

**Comment by Futuray-pgm** [comment]
> wouldnt that get laggy after a while? Otherwise its a good idea and i support it
> 
> 

The game can may be _unload_ some sections far away of the player...

**Comment by itcannotbe** [comment]
Unless you have infinite ram and infinite CPU, this won't get implemented.

**Comment by Mythril382** [comment]
Won't infinite maps get boring after a while? All you do is just create more factories of the same resources you've already had.

**Comment by DX-36** [comment]
at this rate just generate multiple maps

**Comment by camelStyleUser** [comment]
1. it will get more laggy with each world tile
2. this is really hard to implement
3. resizing the map in runtime with Vars.world.resize(int width,int height) can lead to funny consequences ~~and inability to save it~~(fixable with fill())
4. you wouldnt really be able to use existing generation since it isnt adapted to go with other generation and using existing generation would make unnatural looking extensions of the current map

**Comment by camelStyleUser** [comment]
> > wouldnt that get laggy after a while? Otherwise its a good idea and i support it
> 
> The game can may be _unload_ some sections far away of the player...

where would it unload them?to disk?disk space isnt endless and writing and reading from disc is slow.to ram?there will not be enough ram

**Comment by camelStyleUser** [comment]
oh i forgot to mention what about resource transfer?if you unload something you cant update it

**Comment by camelStyleUser** [comment]
and yes the game will get more boring the more you explore

**Comment by gitmanbloggus** [comment]
Stupid ideas cause chaos

**Comment by gitmanbloggus** [comment]
Also boring as... ever

**Comment by Futuray-pgm** [comment]
> @Mythril382 
> Won't infinite maps get boring after a while? All you do is just create more factories of the same resources you've already had.
>

Yes.. This can be the problem.

> @camelStyleUser 
> This is really hard to implement
>

Yes, but it can be a big update! 

> where would it unload them?to disk?disk space isnt endless
>

Other games unload sections too, it doesn't saturate your disk. Here, maps is only in 2D.

> oh i forgot to mention what about resource transfer?if you unload something you cant update it
>

There can be a new block. You place them and it load the zone (~15x15 blocs). The only problem is for server. The core will load permanently a zone aroud her (~50x50 blocs).

> @gitmanbloggus
> Stupid ideas cause chaos
>

Thank you, very polite.

**Comment by Futuray-pgm** [comment]
I hope this will answers all your questions 🙂.

**Comment by camelStyleUser** [comment]
> > Mythril382
> > Won't infinite maps get boring after a while? All you do is just create more factories of the same resources you've already had.
> 
> Yes.. This can be the problem.
> 
> > camelStyleUser
> > This is really hard to implement
> 
> Yes, but it can be a big update!
> 
> > where would it unload them?to disk?disk space isnt endless
> 
> Other games unload sections too, it doesn't saturate your disk. Here, maps is only in 2D.
> 
> > oh i forgot to mention what about resource transfer?if you unload something you cant update it
> 
> There can be a new block. You place them and it load the zone (~15x15 blocs). The only problem is for server. The core will load permanently a zone aroud her (~50x50 blocs).
> 
> > gitmanbloggus
> > Stupid ideas cause chaos
> 
> Thank you, very polite.
@Futuray-pgm 
same problem all over again

**Comment by camelStyleUser** [comment]
and you didnt address everything else i said

**Comment by camelStyleUser** [comment]
if you unload too much to disk the game will feel slow
if you unload not enough ram will fill up

**Comment by camelStyleUser** [comment]
with current load speeds youre not going to load anything in time

**Comment by camelStyleUser** [comment]
since this is supposed to be infinite disk space will also need to be infinite for this to work

**Comment by camelStyleUser** [comment]
you cant unload everything forever you will run out of disk space eventually

**Comment by camelStyleUser** [comment]
do other games unload infinite maps into the disk space?

**Comment by camelStyleUser** [comment]
anuke wont really do anything major now

**Comment by Futuray-pgm** [comment]
We can may be parameter it, every  computer has his own balance.

**Comment by camelStyleUser** [comment]
he will wrap up neoplasm content and thats basically all

**Comment by camelStyleUser** [comment]
he isnt planning to do anything major

**Comment by camelStyleUser** [comment]
> > Will Tantros - the "unfinished" ocean planet - ever be added?
> 
> No. Erekir alone has taken far too long to implement, and I think it's best - for personal and financial reasons - for me to move on to new projects, rather than spending years creating yet another tech tree and planet.

**Comment by camelStyleUser** [comment]
is it 2d or not doesnt change much if youre unloading infinite data

**Comment by camelStyleUser** [comment]
i love mindustry consuming all my disk space!!1!!!!1111!111!!!!!11

**Comment by camelStyleUser** [comment]
im too tired to reason with you right now

**Comment by TheEt1234** [comment]
omg this would be awesome



but probably limited to a mod

**Comment by TheEt1234** [comment]
> i love mindustry consuming all my disk space!!1!!!!1111!111!!!!!11

there could be basic optimisations
such as having the infinite map be generated, and only storing buildings not the entire save

**Comment by TheEt1234** [comment]
> since this is supposed to be infinite disk space will also need to be infinite for this to work
> 

how does minecraft do it, a 3d game

**Comment by Mythril382** [comment]
> > since this is supposed to be infinite disk space will also need to be infinite for this to work
> 
> how does minecraft do it, a 3d game

Have you noticed the farther you load, the bigger the world file size?

**Comment by Bottinator22** [comment]
> > > since this is supposed to be infinite disk space will also need to be infinite for this to work
> > 
> > 
> > how does minecraft do it, a 3d game
> 
> Have you noticed the farther you load, the bigger the world file size?

takes a long time for that to be problematic

**Comment by itcannotbe** [comment]
> oh i forgot to mention what about resource transfer?if you unload something you cant update it

Exactly why this didn't push through when the dev tried it.

**Comment by camelStyleUser** [comment]
> > since this is supposed to be infinite disk space will also need to be infinite for this to work
> 
> how does minecraft do it, a 3d game

unless youre talking about infdev minecraft doesnt have infinite worlds

**Comment by camelStyleUser** [comment]
and you cant progress endlessly in infdev because of disk space

**Comment by camelStyleUser** [comment]
> > i love mindustry consuming all my disk space!!1!!!!1111!111!!!!!11
> 
> there could be basic optimisations such as having the infinite map be generated, and only storing buildings not the entire save

optimising saving infinity space would still give infinity space to store just later

**Comment by camelStyleUser** [comment]
minecraft worlds are just very large

**Comment by Bottinator22** [comment]
No Man's Sky when it has little trouble storing... pretty much infinite planets:

**Comment by Mythril382** [comment]
Infinite maps will still get boring, so this idea sucks.

**Comment by Futuray-pgm** [comment]
> Infinite maps will still get boring, so this idea sucks.

Infinite maps will be boring after may be 8 or 10 hours. It's already big!

**Comment by Futuray-pgm** [comment]
Campiagn is a bit boring too, re-begin every time the same base, on every sector...

**Comment by Xeononyum** [comment]
Sounds impossible
