### ISSUE TITLE
power transformer

### ISSUE THREAD

**Issue by rabit232** [Anuken/Mindustry-Suggestions#461]
a power block that from stored power out put positive  power that can be used or stored 

It would make for some players who bad at making power easier.
 that block convert stored to positive power
it can be charged  by
battery/node's 

main function be that it outputs positive  power from stored  power a set of power or if the is more stored  it output more positive power

it would really help in gameplay I can make base power-driven by stored power that not that hard if that block the name would be like a power transfer or voltage generator.

that would change gameplay massively 
it simply block wouldn't  take much time to make

**Comment by Anuken** [comment]
1. Use the template.
2. I don't understand most of what you're saying. It sounds exactly like a battery.

**Comment by potatoisagender** [comment]
it sounds like a device you put power into and you get more power out. I also do not speak bad grammar, so maybe I'm wrong.

**Comment by rabit232** [comment]
> it sounds like a device you put power into and you get more power out. I also do not speak bad grammar, so maybe I'm wrong.

 I mean  that a transformer that transform stored  power to active power

**Comment by potatoisagender** [comment]
literally a battery. Have you not used one?
