### ISSUE TITLE
Scathe Ammo and Cost Buff

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#4611]
### Describe what you would like changed, and why.

Scathe is a very underused tower due to how unworth it is to place one down due to how costly it is.

Having a consumption rate of 2.0 carbide per second, which is more than what a single carbide crucible with 400% effeciency makes with 1.76 carbide per second makes it impossible to stock up ammo with a single one and you would need at least 2 carbide crucibles to feed it for full uptime.

This turret also has a very high building carbide cost of 300 which increases the detriment of placing it.

### Describe the changes you want to propose. Include possible alternatives.

Scathe should gain a reduction of its carbide usage from 20 to 15 (now needing 1.5 carbide/s) or at least lower than the 17 to give some leeway when dedicating carbide prodcution for it.

Furthermore a change of the building cost
From 400 graphite, 450 silicon, 500 tungsten, and 300 carbide to 400 graphite, 450 silicon, 500 tungsten, 100 oxide, and 200 carbide should help placing down the scathe a lot more cost effeicent.

**Comment by SomeonesShade** [comment]
discussed in #balancing

**Comment by Zerenta** [comment]
gonna PR this
