### ISSUE TITLE
More maps, soundtracks and pvp 1vs1 servers) and one interesting feature

### ISSUE THREAD

**Issue by unikur1570** [Anuken/Mindustry-Suggestions#4615]
### Describe the content or mechanics you are proposing.

What about adding new maps, soundtracks and a couple of fixed official servers with main modes like pvp survival attack and sandbox so that when you enter online mode you don’t have to scroll far down, but just go to a server that will always be big online with normal modes.
About maps. For me, there are really few cards for pvp in Mindustry. It would be cool to add pvp maps for 2, 3, 4, 5 players, because sometimes you just don’t want to play in teams or go to servers in ds and look for normal pvp maps there for a very long time, which are few there. It would be even cool to just take a couple of cool cards from the players so that we don't have to spend time creating them. You can also hold a competition to create the best map for pvp survival...
It would also be cool to add some kind of tool so that the maps would be created by themselves and it would not be necessary to spend a lot of time on their basis. One of the good options, as for me, it would be nice to connect an AI that can draw at least the shape of the cards or maybe even fill them with various blocks. I think it would be a very interesting tool)
And also the most important - units. It would be cool to add more variety to air units and maybe even ground units, ideally for each unit (land air and floating) five different types. It would be fun to add more powerful things) for example, some units from mods like New horizon or Exogenesis (or just similar or maybe not). This would really add more action to the game. A pretty good way to add epicness to battles is music. it would be cool if the game understood when the team's itvy starts and the epic music starts to play.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add more content and more variety which is sometimes lacking in Mindustry especially for a fun game with friends

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
why should anuke pay for server hosting

**Comment by camelStyleUser** [comment]
he is developing this game mostly for free

**Comment by camelStyleUser** [comment]
his profit from itch.io and steam purchases is very tiny

**Comment by unikur1570** [comment]
> his profit from itch.io and steam purchases is very tiny

I agree with you
But what about other ideas?
