### ISSUE TITLE
new command

### ISSUE THREAD

**Issue by Gab304** [Anuken/Mindustry-Suggestions#4616]
### Describe what you would like changed, and why.

the game is nice, the only thing maybe adding a pc command to not show the resource table in the core on the screen

### Describe the changes you want to propose. Include possible alternatives.

as a key command for the visibility/invisibility of the state of blocks and power lasers

**Comment by camelStyleUser** [comment]
you either want it or you dont

**Comment by camelStyleUser** [comment]
you either want it or you dont
if you dont you can go into settings and switch it off
i dont see any reason to make core resource visibility switchable with a button because youre not going to switch between core reosurces shown and hidden often

**Comment by Gab304** [comment]
> you either want it or you dont

I want it, it's useful when you have many item types in the core

**Comment by camelStyleUser** [comment]
> > you either want it or you dont
> 
> I want it, it's useful when you have many item types in the core

switch it on in settings

**Comment by Gab304** [comment]
> switch it on in settings

I didn't know it could be done, where is the setting?

**Comment by camelStyleUser** [comment]
![somka killer its right there](https://github.com/Anuken/Mindustry-Suggestions/assets/124447863/d1d02749-6770-4c92-98c0-ffb4aa5cf1d6)

**Comment by Gab304** [comment]
thanks, I vaguely remembered seeing it but not finding it anymore I thought they had removed it
