### ISSUE TITLE
tech tree and planet tech tree

### ISSUE THREAD

**Issue by gaem-enthusiest** [Anuken/Mindustry-Suggestions#4617]
### Describe the content or mechanics you are proposing.

a search bar on the tech tree and a menu to change between planet tech trees

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

seems useful for large tech trees like erekir's mod planets

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
click serpulo or erekir button when in tech tree and see how to switch between tech trees. if some mod doesnt implement this, too bad for you

**Comment by gaem-enthusiest** [comment]
sucks but good to know
