### ISSUE TITLE
Too powerful enemies

### ISSUE THREAD

**Issue by lo6w** [Anuken/Mindustry-Suggestions#4618]
### Describe what you would like changed, and why.

In some destruction level blocks, enemies are too powerful to develop and defend in a very short period of time, such as block 24, which is almost impossible to win

### Describe the changes you want to propose. Include possible alternatives.

Weakening the enemies of some blocks or arranging more reasonable enemies

**Comment by camelStyleUser** [comment]
serpulo isnt very balanced anyway
