### ISSUE TITLE
Timer on each wave

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#462]
An option to make every timer of each wave editable

Making every wave the same spawn time is just too plain, timer on every wave should be editable to serve a dynamic gameplay

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Jornker** [comment]
Please! ^
