### ISSUE TITLE
Add surge ammo to every single turret

### ISSUE THREAD

**Issue by Rovstam** [Anuken/Mindustry-Suggestions#4623]
### Describe what you would like changed, and why.

I dont have to explain. Anything that doesnt use surge generally sucks if compared to those who do and giving duo surge would be interesting.

### Describe the changes you want to propose. Include possible alternatives.

Every turret can be given Surge Alloy.
Even Ripple, Hail, Fuse, **_anything and everything_**.

**Comment by overdramaticpanromantic** [comment]
You are on drugs. And not the medical kind.

**Comment by Rovstam** [comment]
Spectre is fuckin shit
Change my mind.

**Comment by Mythril382** [comment]
> Spectre is fuckin shit Change my mind.

A brain transplant will do exactly that.

**Comment by Rovstam** [comment]
"Brain transplant"
Spectre sucks. It sucks. Admit it: Its *_trash_*. Useless in every sense of the word, just get swarmers.
Orrr, give spectre surge.

**Comment by NemesisTheory** [comment]
> Orrr, give spectre surge.

or use swarmer

**Comment by Mythril382** [comment]
> "Brain transplant" Spectre sucks. It sucks. Admit it: Its __trash__. Useless in every sense of the word, just get swarmers. Orrr, give spectre surge.

Are you saying a brain transplant will not change your mind?

**Comment by Rovstam** [comment]
> Are you saying a brain transplant will not change your mind?

That would kill me. So, no. ~~spectre suxks bwhaaa~~

**Comment by Mythril382** [comment]
> > Are you saying a brain transplant will not change your mind?
> 
> That would kill me. So, no. ~spectre suxks bwhaaa~

But it would change your mind.

**Comment by python-nerd-3** [comment]
now arc can shoot surge alloy!

giving an overpowered tool to everything is not a solution to balance that tool, remember the units will not be able to keep up

**Comment by jehosula** [comment]
> "Brain transplant" Spectre sucks. It sucks. Admit it: Its __trash__. Useless in every sense of the word, just get swarmers. Orrr, give spectre surge.
seems like it's about as good as cyclone with surge
