### ISSUE TITLE
Large Payload Mass Driver buffs

### ISSUE THREAD

**Issue by Zircane** [Anuken/Mindustry-Suggestions#4627]
### Describe what you would like changed, and why.

Make Large Payload Mass Driver have universal range (connect to any Large Payload Mass Driver in the map) 
Add a Nitrogen cost (4/sec) and half its current firing rate to compensate for the insane range buff.

Right now it serves little use other than a slightly more range and larger size Payload Mass Driver. Often times it doesn't really fill the role of a large transport cannon and is rarely useful in campaign either. ( it also takes a long time to build! and you need to build two!)
This buff would make it although slightly harder to setup but more useful overall as an out of bounds/faraway transport that acts as a target for your opponent (maybe it sends t3-t5s from another base into the frontline faster considering how chonky they are)

Also why is this not possible anyway, there's already no way for t3s and above to be moved around from one closed canyon to another
Might be worth it to add a loading station t3+ can be turn into payload from deployed
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/131593362/2778a231-f3cd-4f3e-8270-1e444c5de3a1)

### Describe the changes you want to propose. Include possible alternatives.

please just buff the damn thing, even a range increase is fine

**Comment by mindustery** [comment]
a normal payload mass driver cant move 3x3 payloads
