### ISSUE TITLE
Easier unit/turret aiming for mobile players

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#463]
**Describe the content or mechanics you are proposing.**
In mobile bleeding edge builds, controlling units means you can only use the auto target feature to aim. You can get around this by going into settings and enabling pc controls. You can no longer move, but aiming with units/turrets is much easier (tap where you want to shoot). Adding a button that toggles pc controls to the hud would allow for mobile players to control units and turrets easier without having to navigate 2 layers of menu.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would improve the experience for mobile players as they can have features similar to pc users.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by kingb74** [comment]
Yes we need this

**Comment by mangblekok** [comment]
Yep, currently mobile user suffers from this kind of targeting mode.
+1

**Comment by scarf-generic** [comment]
Anuke reworked this
