### ISSUE TITLE
Incinerator pls unlock right from start - explanation

### ISSUE THREAD

**Issue by mrvice** [Anuken/Mindustry-Suggestions#4632]
### Describe what you would like changed, and why.

Incinerator should be available from the start right away.

Why:
Iam a new player and i mess up belts accidently very very frequently having to clean that mess up is very annoying.
The only way i know to do that is actualy manualy by clicking on the belt right at the moment the item i want to remove passes by this drives me tbh nuts XD
i did not found any other solution sorters do not help without incinerators really this would such be a QOL addition specialy for new players who will mess up belts quiet often.

### Describe the changes you want to propose. Include possible alternatives.

Incinerator right from the start

alternative solution
A better way to clear belts if accidently wrong items find their ways on wrong belts.

**Comment by Absolutan115** [comment]
No junction be like🗿
