### ISSUE TITLE
Add uwp support for xbox and publish to xbox store

### ISSUE THREAD

**Issue by nyakokitsu** [Anuken/Mindustry-Suggestions#4634]
### Describe the content or mechanics you are proposing.

Building mindustry as uwp via https://github.com/TheLogicMaster/switch-gdx

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will help the game cross-platfor

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Rovstam** [comment]
Buddy i don't think you have readed the https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md

I suggest _doing it_.

**Comment by Rovstam** [comment]
No. It won't happen.

**Comment by overdramaticpanromantic** [comment]
This is an absolutely dookie shit dog water peepee poopoo suggestion. Holy fuck. Anuke has already stated Mindustry is based off things that are completely incompatible with any console.

**Comment by Rovstam** [comment]
Why my comment got deleted

**Comment by nyakokitsu** [comment]
1. Xbox store == Microsoft store
2. I meant a possible publication in the store

**Comment by Rovstam** [comment]
It wont. Deal with it.
