### ISSUE TITLE
Add the ability to sensor "@message" from a message block.

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4638]
### Describe the content or mechanics you are proposing.

You would be able to use the sensor instruction to get the message of a message block as a string.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow for some simple puzzle mechanics, and simple inputs with logic. I'm imagining a puzzle map where you have to find the answer to a riddle with clues hidden in the map, and write out the answer. or maybe a complex map where you could chose a class by typing in your choice, rather than having to have a giant wall of buttons.

I don't think this counts and string manipulation, I'm not asking for any complex string mechanics, my ideas just use the simple comparisons we can already do with strings.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
> - Any sort of string manipulation in logic (reading from message blocks, reading characters, splitting strings, etc)

**Comment by camelStyleUser** [comment]
:trollface:

**Comment by SkyeTheFoxyFox** [comment]
> > * Any sort of string manipulation in logic (**reading from message blocks**, reading characters, splitting strings, etc)

😔

**Comment by camelStyleUser** [comment]
youve are been trolled by `A few things you shouldn't suggest`

**Comment by SkyeTheFoxyFox** [comment]
What if it could only read player messages. If the message was written to by a proc, just return null instead of the message. That removes any possibility for string concatenation, or any other weird string stuff (which is what I assume the biggest problem with it is). That would still allow it to be used as a user friendly input method

**Comment by Rovstam** [comment]
Why this cant be added in the first place?

**Comment by camelStyleUser** [comment]
> Why this cant be added in the first place?

> - Any sort of string manipulation in logic (**reading from message blocks**, reading characters, splitting strings, etc)
found in `A few things you shouldnt suggest`

**Comment by Rovstam** [comment]
> > Why this cant be added in the first place?
> 
> > - Any sort of string manipulation in logic (**reading from message blocks**, reading characters, splitting strings, etc)
> 
> found in `A few things you shouldnt suggest`

You are not answering my question but rather spitting a fact that it won't.
Very useless.
