### ISSUE TITLE
Add the ability to sensor the size, and possibly density, of a display.

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4641]
### Describe the content or mechanics you are proposing.

Add a "@displaySize" to the sensor instruction that would give the size of a display, and maybe a "@displayDensity"

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow people to make display logic that works regardless of the display used, allowing users of the logic to pick the display that will fit their needs. This would also allow for seamless interactions with modded displays, even displays with different pixel scales.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheDogOfChaos** [comment]
There are only two display sizes in the vanilla game, and I'm sure it's already very possible to come up with some logic that allows you to switch between the two display sizes with a literal press of a switch.

**Comment by SkyeTheFoxyFox** [comment]
> 

the issue with that is that it doesn't work with modded displays, making modded displays just about useless, because no logic supports them. if i wanted to use a modded 10*10 display for something, or a 2x density 3*3 display, i can't, because nobody else is gonna be able to use the logic. Also, having to check the type of the display, and set a value based on it is just clunky.
