### ISSUE TITLE
Auto Sort by Tags Schematics

### ISSUE THREAD

**Issue by Hot-Sausage07** [Anuken/Mindustry-Suggestions#4643]
### Describe the content or mechanics you are proposing.

Sort schematics automatically by tags
lets say
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/78838382/b51b8e3e-66c6-4ec0-bbf5-f1fb96c0ced5)
graph tag schemes will be first than silicon tag schemes
if vice versa
then silicon tag schemes will be first than graph tag scheme
non tag maybe at first before all tags or last

yea ig it'll be ignored with this feature
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/78838382/56baae87-8cca-4096-be09-f1528096103b)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It should help by easily seen scheme of first tag priority
Like boost up gameplay pvp like needs in multiplayer

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by The4codeblocks** [comment]
Exclude tag with right click and a [red] outline would be nice.
Also, hide all non-excluded tags that don't exist in any of the shown schematics.
