### ISSUE TITLE
fog radius multiplier + make fog effective in serp by making core units not reveal fog

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4644]
### Describe the content or mechanics you are proposing.

fog radius mutiplier - lets units reveal more or less depending on what the multiplier is, would be useful for map events that reduce visibility
no core unit fog reveal in serp - stops core units from trivializing fog in serp

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

lets mapmakers use fog in serp, and also lets mapmakers do more stuff with fog like periods of low or none visibility (like a snowstorm or similar, could be tied to weather but best if its a maprule)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by overdramaticpanromantic** [comment]
Good idea. Maybe PR it?

**Comment by Zerenta** [comment]
> Good idea. Maybe PR it?

tried to add core units not reavealing fog and its getting errors despite being a stat change
maybe related to recent gradle changes? idk

**Comment by jehosula** [comment]
perhaps it can be a toggle fore core units revealing fog?
