### ISSUE TITLE
New weather

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry-Suggestions#4646]
### Describe the content or mechanics you are proposing.

I propose a new weather called "Snowstorm"  it works similarly to rain but instead of applying wet (which in my opinion does nothing but buff surge ammo turrets, as the de-buff is not very noticeable), it would apply freezing effect, which has noticeable slowdown de-buff and would make blast ammo turrets more useful

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add another weather option map makers can use by adding new global effect, and graphics. The freezing would make blast ammo turrets more viable for both player and enemy to use, and leans away to the surge/thor ammo "meta" right now. The graphics could look something like sandstorm but white, perhaps with some snowflakes falling like rain does.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by python-nerd-3** [comment]
That's a good idea, I agree blast compound needs more viability. It is barely used anywhere. Here are the 6 blocks that take it:

- Combustion Generator: Earlygame item, you will be far past it by the time you can produce Blast Compound.
- Steam Generator: Same as above.
- Impact Reactor: This is probably the best intended use of Blast Compound, creating lots of power. However, using Thorium Reactors is often more popular.
- Swarmer: Very popular turret but like as you stated, surge alloy is a better option.
- Ripple: Same as above but with other ammo.
- Cyclone: Cyclone is a very fast firing turret so using blast compound, one of the hardest resources to manufacture, is not very effective.

The only thing it is really commonly used for is suicide bombing. It really needs more uses and is not required for progression at all unlike other powerful lategame materials like surge alloy and plastanium.
