### ISSUE TITLE
Item constants writes in cell as its lookup code, not `1`.

### ISSUE THREAD

**Issue by VladisS-Vostok2000** [Anuken/Mindustry-Suggestions#4648]
Currently when you try write any item constant into cell:
```
write @silicon cell1 0
```
...you will get always result `1`.
But now, when we have `lookup` command, we have enumeration presented by number-item.
So i found it very useful to convert item constants in cell not in simple `1`, but its number, presented in its enumeration.

**Comment by rekokoro** [comment]
use sensor @id

**Comment by rekokoro** [comment]
@VladisS-Vostok2000 the game still can't store color in numeric value despise using 4-byte HEX value and you're asking for some sugar? XD
