### ISSUE TITLE
Resource Filter/Search In Tech Tree

### ISSUE THREAD

**Issue by Rybadour** [Anuken/Mindustry-Suggestions#465]
**Describe the content or mechanics you are proposing.**
When viewing the tech tree allow the player to highlight all incomplete techs that require a certain resource.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I've experienced that while playing the campaign I often ask myself "I can produce graphite on this map... but how much do I need?". To answer this question currently I have to manually select all the techs and add up the graphite count in my head. If we could see how much of each resource we currently need that would go a long way to simplifying this part of the game.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
I think there should be an Icon.zoom button which has a list of all *known* materials (including unresearched ones)
Each item can be toggled which will restrict the search to that item.
So, clicking copper and titanium will only show nodes that require both.

**Comment by Rybadour** [comment]
Perfect, the only thing I'd add is that it would be great to how much copper and titanium those nodes need as well instead of requiring the user to mouse-over the node.
