### ISSUE TITLE
Unify color syntax in processors

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4650]
### Describe what you would like changed, and why.

Right now we have 3 different ways to set up colors in processors

First, display logic commands are using color format RGBA[0-255,0-255,0-255,0-255] which is 32bit integer number. Value isn't storable.
Second, it's possible to set up color using col command with alias %RRGGBBAA which is text value. Value is stored as number close to 0. 
Third, pack color command uses color format RGBA[0-1,0-1,0-1,0-1] which is, as i understand, array of floats? Value stored as 0.

Pack color and draw color using different formats which is confusing. Also although RGBA HEX values are 4-byte integer, none of those 3 formats provides number value to be working with, means no color comparison operations, easing-outs and other color functions

### Describe the changes you want to propose. Include possible alternatives.

Unify color format in comands as  RGBA[0-255,0-255,0-255,0-255] and replace color representation in variables as 0xRRGGBB or 0xRRGGBBAA integer rather than %RRGGBB string.

**Comment by camelStyleUser** [comment]
the pack color(and percent notation value) is very small but you can still get the int value if you divide them by 2^-1074(or %00000001 theyre the same)

**Comment by camelStyleUser** [comment]
also you can use strictEquals to compare colors if theyre the same

**Comment by camelStyleUser** [comment]
(equals wont work because the difference between them is very small)

**Comment by camelStyleUser** [comment]
2^-1074 exists to convert from packed color to normal values

**Comment by rekokoro** [comment]
@camelStyleUser then sensor @id is useless too cause you can just sensor @type and loop-compare it through lookup command until you hit the mark.

You missed the point that there's still 3 different color settings and no matter how you look, ingame vars display not @color object, not E-1074 number but 0 and there's no hint or whatever that value is set and set correctly.

**Comment by camelStyleUser** [comment]
> `@camelStyleUser` then sensor @id is useless too cause you can just sensor @type and loop-compare it through lookup command until you hit the mark.
> 
> You missed the point that there's still 3 different color settings and no matter how you look, ingame vars display not `@color` object, not E-1074 number but 0 and there's no hint or whatever that value is set and set correctly.

how is `sensor @id` related to colors

**Comment by camelStyleUser** [comment]
also the pack color and percent notation are the same

**Comment by camelStyleUser** [comment]
(yes the display cuts off the value and it is displayed as 0)

**Comment by rekokoro** [comment]
@camelStyleUser 

> how is `sensor @id` related to colors

There was no necessary to add that feature in the game cause you could use if arrays or lookup loop. And now yeah, as you told, u can use E-1074 number that's somehow is usable in the game to convert that 0 value to something operatable. There **is** a way. But that way is inconvenient as hell, starting from the point that nothing explains it at all.

Next is notation. Commands description as it is in the game are:
draw color r g b a 0 0 - **Set color for the next operations** (color range for command RGBA[0-255])
draw col c 0 0 0 0 0 - **Equivalent to clor, but packed. Packed colors are writtend as hex codes with a % prefix. Example: %ff0000 would be red** (well, we getting color range RGBA[0x00-0xFF])
packcolor result r g b a  - **Pack [0,1] RGBA components into a single number for drawing or rule-setting** (as it claims, range is RGBA[0-1])

Additionally we have one more way to use colors and that's [#HEX] in tags, which is again RGBA[0x00-0xFF] but with sharp instead of percent. As we remember clear, there's no text editing tools available in game which results in 4 incompatible with each other and moreover - all the commands returns 0 as it stated in game or for you java geeks - float number that's so close to zero that round precision kicks in.

**Comment by camelStyleUser** [comment]
16 instructions vs 1 instruction

**Comment by camelStyleUser** [comment]
lookup loop and if array are O(n) while `sensor @id` is O(1)

**Comment by camelStyleUser** [comment]
> > have you ever heard of speed concerns
> 
> Just array of pairs if->then to concerned units.
> 
> And the talk isn't about speed, it's about accessibility while color isn't providing any of that. You have to ask people that are involved in game development for literally basic content in the game rather than just mask out mantissa from double variable.

O(n) vs O(1) which is better
