### ISSUE TITLE
Scathe Changes

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#4653]
### Describe what you would like changed, and why.

Scathe has been accidentally hit hard with the missile fix during v146 development.(https://github.com/Anuken/Mindustry/commit/2b05264093856ec633212bc8d2fde89530b8cde5)

It was already underused beforehand, so to return to previous stats, the damage of should at least be increased to previous state or more to compensate.

v146

https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/d1a59f0a-5ada-48c3-9fa9-019b06a959f9

v145.1

https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/f8e4bd00-c2e5-49c7-8c4e-863ad0b38f12

### Describe the changes you want to propose. Include possible alternatives.

Main Damage from 700 to 1,500
Frag Damage from 85 to 100

It's Close enough to previous, being slightly stronger (although minor)

Using a replica mod tower for reference

https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/8b859edf-8f33-45d3-a539-4a752be11287

**Comment by overdramaticpanromantic** [comment]
can maybe PR it
