### ISSUE TITLE
no forced restarts

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#4658]
### Describe the content or mechanics you are proposing.

Do not automatically restart the game after the player has changed mod settings. Apply the changes after the game has been restarted naturally

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The game can restart even after you reinstall a disabled mod. That's unnecessary

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SITUVNgcd** [comment]
I also though about this, but it will cause some unexpected behaviour.
Some mods that modified game's content, changed the UI, UX,...

Possible to do this, but game maybe consume too many Memory, best option is relaunch.
