### ISSUE TITLE
Marsh sector starting space rebalancing

### ISSUE THREAD

**Issue by Catomax262** [Anuken/Mindustry-Suggestions#4660]
### Describe what you would like changed, and why.

For some reason, I think that Marsh is really unbalanced. If it's supposed to be a challenge sector maybe I can reconsider, but still.

Reasons why Marsh is unbalanced:

1. The starting space is too small to build turrets, machines, and pipes.
2. The only viable way to obtain tungsten and beryl is via impact drills. There's only a single small wall vein of beryl.
3. Impact drills work really slowly because of turbine condensers being mostly used to generate energy, yet if one of the turbine condensers was replaced with a vent condenser it would use twice or thrice as much energy in favor of water.
4. Too few water can be produced before the chemical combustion chamber starts replacing turbine condensers with vent condensers.
5. There is too many water usage, for making ozone for oxide, pumping arkycite for energy, boosting turrets, and mainly powering impact drills.
6. Just as you generate better energy, enemies start appearing right away. Knowing that your tungsten/beryl production is very poor, you can find your turrets too ineffective against lvl2 tanks. (Forgot their name lmao)
7. The grace timer before enemies start appearing is too short. Making walls is necessary but wastes valious time.
8. You can't generate any units in the time before you can even pump arkycite. Due to the small space and arkycite rivers.

### Describe the changes you want to propose. Include possible alternatives.

1. Make the starting space bigger.
2. Add 2 or 3 more vents mainly for water production.
3. Add a better way to obtain beryl that isn't from ground veins. Sure, the veins look huge but the drills are too resource hungry. There's a hard limit of 3-4 impact drills in the area.
4. Reduce arkycite pond size. Pumps do pump a good amount of arkycite, so it's enough.
5. Nerf enemy core being able to produce units so quickly.
6. Reduce silicon production. It is not as much as needed in here.

**Comment by CoderSourojeet** [comment]
hocus pocus here comes the locus

**Comment by Catomax262** [comment]
Haze on the ace THERE IS NO SPACE
