### ISSUE TITLE
Factorys

### ISSUE THREAD

**Issue by Multipiex** [Anuken/Mindustry-Suggestions#4661]
### Describe the content or mechanics you are proposing.

A new mech tree named zyel, T1 to T5 (tank + mech shape) 

T1 - Ambex (ground) 790 hp 4 defense 19 damage medium fire rate | - fires small bullets at target~

T2 - Timber, 1400 hp 6 defense 25 damage, slow fire rate -Blast ~ 12 damage 12 radius|upgraded form of ambex, fire artillery at enemy. 

T3 - sketh , 5600 hp 12 defense 12 damage, very fast fire rate, -frag ~ 6 bullets > 4 damage. | sketh fires mini gun at enemy. 

T4 - kyle, 11000 hp, 15 defense, 1st gun (artillery) -62 damage, - Blast ~24 damage,15 radius) (0.20/sec)fires at' 1'sec | 2nd gun (machine gun ) -23 damage  (0.95 × 2 / sec) | kyle fires massive artillery and machine gun at enemy. 

T5 - Treg - 22300 hp, 26 defense, 1st gun (mini meltdown) - 800 damage /sec, fires 3 second,(0.25/sec fire rate) 2nd gun (spectre) 72 damage/bullet, 3×peirce , (3/sec) (repairs nearby ally blocks or unit) carry a T3 zenith factory) -(slots -2) 

Other such as design, texture, coding etc on you, anuke, playing this game from v5, hope this mechs come soon, but, add iron cross sign on cores for 10 days after update. Please :) 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This is a mech tree made to upgrade attack and unit  productions helping length of game research. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
is this serpulo or erekir?
