### ISSUE TITLE
Add the ability to add and remove blocks and units from the banned list using `setrule` on a world processor

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4662]
### Describe the content or mechanics you are proposing.

add some method of enabling and disabling blocks from being used, maybe something like `setrule ban @copper-wall` and `setrule unban @copper-wall`, or maybe a new instruction

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow map makers to easily emulate the researching mechanics seen in the campaign, as well as giving more control over what players can and can't do during gameplay.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by snack-ie** [comment]
RANDOMIZED BLOCKS EVERY MINUTE HELL YEAH
