### ISSUE TITLE
Advanced commanding paths

### ISSUE THREAD

**Issue by python-nerd-3** [Anuken/Mindustry-Suggestions#4664]
### Describe the content or mechanics you are proposing.

Currently, the RTS system only supports a linear path for your units to take. I suggest for an ability to make complex paths composed of multiple lines. [Beautiful MSPaint drawing example](https://ibb.co/DYdKpy6). There could also be a different keybind for "sketching" plans that the units won't actually take but can be used to plan out your path to invade. When the path targets a block/unit, it must be destroyed before the unit moves on to the next node.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be a great QoL change allowing for you to plan out your path easily, allowing for complex invasions that would add on to the RTS part of the game added with Erekir. It is a pretty basic feature in a lot of RTS games that Mindustry lacks. The attack stops and sketching features would push the potential even further.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Mindustry's RTS control simply lacks an order queue.

**Comment by Jamespire** [comment]
i feel like this would allow people to make calculated attacks quickly in pvp without having to wait for the units to get to the next point where you would add the next command

**Comment by Mythril382** [comment]
This might be possible with how the pathfinder's coded.

**Comment by python-nerd-3** [comment]
> i feel like this would allow people to make calculated attacks quickly in pvp without having to wait for the units to get to the next point where you would add the next command

could be a map option to disable it

**Comment by Optimal-performer-38** [comment]
Its not perfect, but I have a similar array logic code along with display on reddit.
You could do a pathmaker script by storing coordinates whenever it updates, write it in a bank in an even and odd number order, then reading that in a loop based on the last even number.

**Comment by jehosula** [comment]
the rts system has a lot to be desired
