### ISSUE TITLE
Barrier Block

### ISSUE THREAD

**Issue by komikus1** [Anuken/Mindustry-Suggestions#4666]
### Describe the content or mechanics you are proposing.

A block that would stop items on conveyors going the wrong way.
You could place a barrier next to a router, and the router would not put items on that path.
I made a little picture of how it would work, it should be below
![barrier](https://github.com/Anuken/Mindustry-Suggestions/assets/145025250/bea5384a-7e26-472d-9a45-6bf790b8b204)
You could maybe also add something like make the router only deposit items on 2 paths (still would be able to put them on 3) by making sort of arrows that showed on what path the items would go
it would work something like this: 
![arrows](https://github.com/Anuken/Mindustry-Suggestions/assets/145025250/efda35ce-8200-410e-a7eb-d9b654910536)
(there would not be an only 1 arrow option, because you could just place a conveyor)
the same could probably be done with a distributor, but its up to you

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's a small thing that would make the game much much easier since you wouldn't have to make the conveyors bend just to have the router not put items on the wrong path.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by komikus1** [comment]
it could also be used for drills (if you add the block)

**Comment by itcannotbe** [comment]
How would you even use that block?

More importantly, why would even set up your conveyors like that?

**Comment by komikus1** [comment]
maybe if you had a conveyor with coal going next to a conveyor with lead or something and you wanted to put half of that coal into combustion generators or something like that

**Comment by SkyeTheFoxyFox** [comment]
Armored conveyors

**Comment by itcannotbe** [comment]
Junctions

**Comment by itcannotbe** [comment]
Bridge Conveyors

**Comment by komikus1** [comment]
ok

**Comment by komikus1** [comment]
i didnt really think about that

**Comment by Bottinator22** [comment]
Inverted sorters with no item set

**Comment by Slotterleet** [comment]
Or regular sorters

**Comment by komikus1** [comment]
i didnt research inverted sorters yet

**Comment by Bottinator22** [comment]
> Or regular sorters

That requires them to be configured (sorters with no config send items sideways, aka what we don't want here)

**Comment by jehosula** [comment]
armored conveyors inverted sorters with no config and bridge conveyors
