### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by Sigmagiga** [Anuken/Mindustry-Suggestions#4668]
### Describe the content or mechanics you are proposing.

Make it so that you can choose what percent of items go to a certain output area in a router, also add routers with higher capacity.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Because good. 🗿

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ceuthyn** [comment]
I'm pretty sure this falls under "do not suggest"

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Additional configuration of blocks, such as I/O side configuration

**Comment by overdramaticpanromantic** [comment]
mods. pin him down and twist his nuts counterclockwise

**Comment by Anuken** [comment]
@overdramaticpanromantic Refrain from making vulgar (and unhelpful) comments like that, unless you want to be banned from this repository.
