### ISSUE TITLE
Something small that could change much. Unloading from bridge conveyors.

### ISSUE THREAD

**Issue by KecskeGamer** [Anuken/Mindustry-Suggestions#4669]
### Describe the content or mechanics you are proposing.

Make unloaders be able to unload from bridge conveyors' sides like on the linked image.
![Mindustry 2023  09  15  9_09_07](https://github.com/Anuken/Mindustry-Suggestions/assets/145101613/dca377d4-abee-4a25-84f5-8919e6ccf89c)

If there is a single unloader attached to the side of a bridge conveyor it would take half of the selected resource from the bridge conveyor (if there is nothing selected then it will take half of every item passing through). If there is an unloader on both sides of a bridge conveyor then each unloader would take a third of the items passing through.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow for even more use of bridge conveyors and because of how they take half of the items going through unspecified unloaders could be used to make single conveyor input for things like silicon possible withouth any proper logic. Just make twice as much sand go onto the bridge conveyor as coal and you are good.

Also bridge conveyor outputs/inputs are hard to deal with sometimes and this would help to clean up things that get messed up and also allowing for just overall more creative ways to use bridge conveyors and unloaders.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by YSMQTHLQYH** [comment]
Not sure if this could break existing schematics in some way.
However it should mentioned that the erekir bridges and unloaders can do this already, so you would expect the more flexible serpulo counterparts to be capable of the same, even if its just for consistency

**Comment by KecskeGamer** [comment]
> Not sure if this could break existing schematics in some way. However it should mentioned that the erekir bridges and unloaders can do this already, so you would expect the more flexible serpulo counterparts to be capable of the same, even if its just for consistency

I don't think too many schematics would be broken though some may become less functional because I think unloaders would have to be changed more.

And now that I have though more about it on erekir its fine because you cannot control how bridges attach. But on Serpulo you can stack bridges to make a line better than a plast conveyor so if this was to be implemented for the sake of not making bridge conveyors also replace plast conveyors in unloading into factories they should be nerfed. I was thinking make them 9 items per second as it is still twice the speed of regular conveyors but makes more sense for their cost and progression placement. They would still be very good for space efficient line making but they couldn't just straight up surpass plast conveyors.
