### ISSUE TITLE
Unit shoot

### ISSUE THREAD

**Issue by Uylol** [Anuken/Mindustry-Suggestions#4670]
### Describe the content or mechanics you are proposing.

A command for logic that makes unit shoot like enemy unit

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will give even more abilities to create with logic proccessor

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
`ucontrol target` and `ucontrol targetp` exist for shooting

**Comment by camelStyleUser** [comment]
never cook again

**Comment by Slotterleet** [comment]
### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I am ***not*** familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Uylol** [comment]
> `ucontrol target` and `ucontrol targetp` exist for shooting

Bruh did you read my suggestion? It literalily says "shooting like an enemy" not your 5 dollar commands that shoot only the target you set it to shoot
