### ISSUE TITLE
Underground Units

### ISSUE THREAD

**Issue by Ruyeex** [Anuken/Mindustry-Suggestions#4671]
### Describe the content or mechanics you are proposing.

The idea is to add a way to make the units undetectable and be in the underground like moleworms which can be changed through these configurations whether "Void, Fluid, Walls, Terrain", if the unit can be submerged, if the unit can be move after leaving the ground and more if you want to add to the suggestion.
The idea came from the Miner from clash of clans.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A way to be more creative with creation of units. "Whether is for stealth or kamizake or anything"
And a new layer to make units more interesting

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jamespire** [comment]
It is easier for a camel to go through the eye of a needle than for underground units to be implemented into mindustry

**Comment by itcannotbe** [comment]
- [X] I haven't read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to didn't make sure my idea is not listed under the "A few things you shouldn't suggest" category.

### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Underground map layers

**Comment by Ruyeex** [comment]
> * [x]  I haven't read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to didn't make sure my idea is not listed under the "A few things you shouldn't suggest" category.
> 
> ### A few things you shouldn't suggest
> ###### These have been proposed many times already, and I won't be adding them.
> * Underground map layers

It's not the same thing.
The suggestion is not meant to add layers.

**Comment by itcannotbe** [comment]
How will you implement defenses and units without making a specific layer or zone where they affect each other?
