### ISSUE TITLE
Mindustry Champaign Server

### ISSUE THREAD

**Issue by Marius-Juston** [Anuken/Mindustry-Suggestions#4672]
### Describe the content or mechanics you are proposing.

Hello, currently, you can only create a server for setting up random maps and playing on those; however, what would be great would have a champaign server, where you can just setup and play on it. So you would have a server that contains, the worlds on and would autosave, etc... but the players would be able to join in and continue the campaign in a cooperative manner

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would help improve the server multiplayer experience, by allowing a different kind of cooperative mode, which has a larger progression.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by snaildos** [comment]
+1, Issue that has been requested back since 2020.
Sources:
https://github.com/Anuken/Mindustry-Suggestions/issues/3182
https://github.com/Anuken/Mindustry-Suggestions/issues/3140
https://github.com/Anuken/Mindustry-Suggestions/issues/2422
https://github.com/Anuken/Mindustry-Suggestions/issues/1510
https://github.com/Anuken/Mindustry-Suggestions/issues/993

**Comment by kennarddh** [comment]
Maybe just admin can change server current map so if no admin change the map just stay on the same map or server can you use plugin to auto rotate map but still only 1 map is loaded at a time.

I don't know how to handle loadout though. Maybe when admin manually change map the admin need to specify the loadout. or just default from server config so always same loadout.

**Comment by Marius-Juston** [comment]
I understand that you can just host multiplayer on your machine and then invite players using Steam or some kind of local host (would need to setup port forwarding or a VPN to access out of the network), but that requires that machine to always be running. And if you are using a personal machine you would not necessarily want that. In addition, some people have said to just use, VNC; however, then you would need an extra dedicated windows machine; however, for the server.jar you can just use a raspberrypi (mindustry.jar does not work on raspberrypi's).

**Comment by jehosula** [comment]
it would be very nice to have

**Comment by kennarddh** [comment]
well stale again..

**Comment by CrystalKeck27** [comment]
I want this so bad
