### ISSUE TITLE
A Serpulo building which turns tier 1-3 units to scrap

### ISSUE THREAD

**Issue by Hannik24** [Anuken/Mindustry-Suggestions#4676]
### Describe the content or mechanics you are proposing.

A 5x5 Serpulo building which has a payload input on 1 side and 15 conveyor outputs on 4 other sides. Takes T1-3 units(because t4-5 can't fit on payload conveyors) and power as an input, outputs scrap. The time to convert a unit to scrap is the same time to assemble them. The amount of scrap scales with the tier of unit inputed.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

"Scrap to..." is a very popular playstyle amongst players, with scrap being (theoretically) one of the most useful resources in the game, being able to produce most mineable recources without them actually being on the map. Being able to turn excess silicone/coal/lead to a lot of other recourses opens up a lot of new possibilities to build a large factory on maps that have little to no recources, without using launch pads(which some players don't use just out of principle)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083

**Comment by AtomicTalkingBomb** [comment]
This would be cool!
