### ISSUE TITLE
Effectless option for explosions

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4677]
### Describe the content or mechanics you are proposing.

lets u do explosions without the effect

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

custom vfx that damage units would be cool

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Optimal-performer-38** [comment]
Fetch unit count as unitC.
loop= loop+1
loop= loop % unitc 
fetch unit #unitC as unit
Sensor unit @x,@y
Do an effect or plot a point in the map, ex 90,100
UX = unitx - 90
UY= unity - 100
vector distance UX, UY
if vector <= than 1 jump to zero (here you put the detection radius you want)
Health sensor health in unit
Health=Health - 50 (this is the damage) 
Set prop @health of unit to Health
