### ISSUE TITLE
Make Hails use less ammo

### ISSUE THREAD

**Issue by gen-NA-owl** [Anuken/Mindustry-Suggestions#468]
**Describe what you would like changed, and why.**

With one graphite, Ripples and Hails each fire one time, but ripples shoot 4 bullets while hails only shoot 1. This makes no sense, as Hail and Ripple bullets have the exact same stats. Make hails use less ammo, or ripples use more. 

One can argue that ripples are more "efficient" at shooting, than Hails, but a having 400% the efficiency of a smaller turret is a bit much. 

Hails are also a bit underused (only when ripples are inaccessible), so maybe this might encourage people to use them more?

I know these aren't very big reasons, and there are definitely a lot of counterarguments to them, but small changes only require small reasons, right?

**Describe the changes you want to propose. Include possible alternatives.**

Increase the 'maxAmmo' for both ripples and hails, increase the 'ammoMultiplier' for artillery bullets, increase the 'ammoPerShot' of ripples.

**Comment by gen-NA-owl** [comment]
Im gonna close this for now; Seems too small to be considered a suggestion

**Comment by Bohaska** [comment]
Seriously, editing variables does not require advanced Hjson knowledge. Even I could do it if I spend some time...
