### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by DALLORDCR** [Anuken/Mindustry-Suggestions#4680]
### Describe the content or mechanics you are proposing.

Железо, новые механики и небольшие улучшения

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Эдравствуйте Антон, хотелось бы предложить новые механики которые я придумал:
С помощью железа (если можно то даже сделать отдельную вкладку для +-такого же) делать защитные накладки на турели или буры что бы увеличивать их прочность, так же можно добавить сталь что как то что я описал выше но лучше. Будет просто замечательно если железо и сталь можно будет использовать для какого нибудь нового сплава или хотя бы как новые снаряды. Также могу предложить новую смесь х созданная что бы жидкостные пушки были более популярны - создавать её можно будет в новой фабрике с помощью: соли, железа, жидкого кислорода(который можно будет добывать в новой фабрике (как охлаждение)) данная смесь нужна будет что бы:1-стрелять ею и наносить новый эффект(увеличение урона и комбинирование с эффектом плавится) вместе с уроном примерно 2-5в секунду

Так же хотелось бы что бы вы добавили отображение место и радиус появленияврагов на мини карте
На этом все, если хотят что нибудь понравилось то могу рассказать о чем нибудь еще что напридумываю.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Нет. Лучше сделай мод. (Но не советую, потому что моды на железо уже всем надоели)

**Comment by DALLORDCR** [comment]
> Нет. Лучше сделай мод. (Но не советую, потому что мода на железо уже всем надоели)

Я не знаю как программировать, да и идея отличается от дефолдных модов на железо, которое я предложил т.к. его давно просят, вместо него можно использовать алюминий, а жидкость х я придумал когда писал пост, её можно сделать из чего угодно

**Comment by camelStyleUser** [comment]
> > Нет. Лучше сделай мод. (Но не советую, потому что мода на железо уже всем надоели)
> 
> Я не знаю как программировать, да и идея отличается от дефолдных модов на железо, которое я предложил т.к. его давно просят, вместо него можно использовать алюминий, а жидкость х я придумал когда писал пост, её можно сделать из чего угодно

(json mods exist if you dont want to program)

**Comment by DALLORDCR** [comment]
> > > Нет. Лучше сделай мод. (Но не советую, потому что мода на железо уже всем надоели)
> > 
> > 
> > Я не знаю, как программировать, и идея отличается от дефолдных модов на железо, я предложил т.к. его давно просят, вместо него можно использовать алюминий, жидкость х, которую я придумал, когда писал пост, ее можно сделать из чего угодно
> 
> (моды json существуют, если вы не хотите программировать)

Не знал, спс, но я слишком ленивый для такого
