### ISSUE TITLE
Make Erekir core units damageable from world processor explosion command

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4682]
### Describe the content or mechanics you are proposing.

As title says

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Right now there's three ways to despawn core units, each of them having a flaw:
- Setting hp to zero and applying effects like wet+shocking, which won't guarantee the kill if unit are near healing spot. 
- Setting payload before explosion which can result in damage to buildings and units below.
- Setting unit coordinates out of the map, which can be executed only if unit isn't occupied or strict mode on server is turned off.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
explosion command literally just makes an explosion

**Comment by camelStyleUser** [comment]
you expect a little too much from it

**Comment by camelStyleUser** [comment]
also just `setprop`ing core unit's health to 0 works on my device(TM)

**Comment by camelStyleUser** [comment]
even with unit repair towers

**Comment by Optimal-performer-38** [comment]
Sensor @totalhealth in @unit
Bleed= totalH - 1 (use larger # if you want to kill instantly)
Set prop @health of @unit to Bleed.
This damages the unit each cycle. The speed depends on the tick.
I hope this helps somehow.

**Comment by rekokoro** [comment]
> explosion command literally just makes an explosion

well, not anymore

**Comment by camelStyleUser** [comment]
> > explosion command literally just makes an explosion
> 
> well, not anymore

it is still just Damage.damage with effects
@rekokoro
