### ISSUE TITLE
Effect: Light polygon

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4683]
### Describe the content or mechanics you are proposing.

we have light square, but none of the other polygons
would be similar to light square but with a sides parameter

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

would let mapmakers do more cool stuff

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Optimal-performer-38** [comment]
Agreed. There should be a static effect too that doesn't flicker or fade. Just disappears once duration is over. It would be better if the static effect don't blend their opacity too because you get this unwanted bloom

**Comment by camelStyleUser** [comment]
`effect` just displays a subset of Fx.java's effect and as far as i know there is no lightPolygon in Fx.java

**Comment by Optimal-performer-38** [comment]
![Screenshot_20231010-134416](https://github.com/Anuken/Mindustry-Suggestions/assets/145533195/25313e60-4034-4724-8f55-d8a2166c5a90)
 
Hmmm. It seems you can only draw shapes manually.
Here you go bud. Its not perfect but it works somehow.

bXNjaAF4nE2UbVATVxSGVxITjHwJTEcF9KrUStsElYhKLa18RwuBykCEhnaT3Gx2utmb7G6ARKsgBoZ+DVIRRaDM2EAtQ0eU4hQsiA6MlYqFASviWGEKVUA7Dq1aobY30B/O/jjn3Lt73vs+s+cSUkIiIsQsaYbEkkSI4my8wNmJpQbI6znaItCIJQhCwpA6yPCEV7bRxjBAjxjEaSVEAENyFJQziKL1cgPNWxjSTohITk/4mmk9h+QWDukhzyOOWGqGZsTZ5XrIMIRvHuIYwwu7UjOOJAWxlJQgPPBDLCIkuMKZhFjkg8vQ/Gpn+fV3LwO/ntKDxuBa3ZcX15we+nOiuz3xTV3dSyXFnl3Fj4ZqSguJ5AddXoXTT0bQcFmgp3Z/0J2Vrq7po5PSuraw0U3i8PzS2/4/1IL+jvDRwDHf9j8KCu5/Z3rWoN49vqkiNCKg/otB7/vkqxvnSLYrOCNk+axkz8nmkfQ1AZVVyQfUjzMc15XfXHswmQ8n5rZRR5vvNU4Fl9zebhxbqtya8TjVf8Pqh+pu/4y9f42Yrh7ecmeV3SNhIzsXee7heFP6c0F0nDp0ol5qCm1wRO31yLNpyr/9qsrmMeT4SFxTrrjg/MSpCzoZ0Xje9UZsWNbzufdLm1qMlZ2B0ab+meO3LGG7k7KUfTrnspjKe+v/7lmdXjd1cX1q3Wv/qtcoP+/srhmZIEQYF4YnxkHkprYrv1pbvpPF1OJVLnb/x8NC9rB1z1A74yjKKahSxcSd6b3rmdK/rsHrZkr6iuGqrQej95/4zE/d6ePyGJAtcSjrC+uvXlG5GpzmRtGz5+JTR5aFVL/SKJXui1I1pO70nj1wJvPTokZPuStHE0/utMY3r0wo21WYor7cDTfEz+bwpys6DrUkFr1z9dFZZnPEjfHespbFK4wdAwdA2aO3rkkKM388f/bKVN9TS/TUpSyjKjoq+de748s1MaOFcRlpNywep+R9lwZ7E3JuHZrp7ZncoU24GflB2b2p0Ae/qzcnRfa25lln0sKt3/s0dlcf633quV2T0Trz9j9t+35rrqGMfSNpmgRTcor1SKVJIn+v+cn9zGM/hZHOktiYuzWDxdqBn4MufN2q9k7KBFt2xPxie9l6rkjfRq0KKcmZbq3w062rnWkKGMudFWmUo4nEYgxVLF5E9GdTHISsNhEKgGYB/t03KWS8CSF3ydMGCAQTBP+Pg0xAQG8iWQoCnnZAQLIGwJtIC5RFRG4EZvJDyANaALxACrReIYtdeBV/RLIIt+EAazPrcHCvMAJODDQH9e6xXGhlgdCgkOW/bgc0P6+LOJqiWQVI5+wLwjRLYQWFLJuDBq0tHOGZNpOM3AI5I+LMkJNHbJu3thhba2JhLtagEMuSgKJzIbAjG7BZgOzFDQYbd68bUB4rE2hLFMBXBuDwgOe6xdynWOvmwAMjgxAH5vO1ACCLm5fbFVQAFTZtQjbGMA8BXymIcVPgeBnJ8Gi+v55kwQJXZBPmweITgzyccJg6JIn/AJlZ66I=
