### ISSUE TITLE
Add keybind for commands

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry-Suggestions#4685]
### Describe what you would like changed, and why.

version: BE24422

the use of commands is much more than that of stances. so it's better to add some keybinds also for commands

### Describe the changes you want to propose. Include possible alternatives.

Add keybind for commands

**Comment by ziszlo** [comment]
something like a separate menu where you can select a key and write something in the command field, and when you press this key, the game will use the command, yes, that would be convenient, but, but.
Meet Mr. Hater, he will set the most racist phrases on all keys and will use them on CD on all servers. just imagine that everyone will say something like this on CD:
Hitler has nothing to blame, black people should die, suck dick, your mom is fat.

**Comment by TheRadioactiveBanana** [comment]
> something like a separate menu where you can select a key and write something in the command field, and when you press this key, the game will use the command, yes, that would be convenient, but, but.
> Meet Mr. Hater, he will set the most racist phrases on all keys and will use them on CD on all servers. just imagine that everyone will say something like this on CD:
> Hitler has nothing to blame, black people should die, suck dick, your mom is fat.

You do realise admins exist right
