### ISSUE TITLE
Better implement of move command(for command queueing)

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry-Suggestions#4686]
### Describe what you would like changed, and why.

now the taget won't be considered reaching until the unit **really** arrive at the target. it's not a big problem for normal move, but for command queueing.

https://github.com/Anuken/Mindustry-Suggestions/assets/66559840/7908ab81-9a8d-4bc7-a859-192173d48081

### Describe the changes you want to propose. Include possible alternatives.

give each unit its own target pos. when commanding to move, the target of the central unit is the same as the real taget position, and add the same offset as now for other units.

(or consider adding another command "maintain formation and move" as default move command, naming the origin "move" as "gather")

**Comment by nanmenyangde** [comment]
note for the video: it's usually bad for the units to move in a line. it makes them easy to be killed

**Comment by Optimal-performer-38** [comment]
https://www.reddit.com/r/Mindustry/comments/16l35sf/unit_pathdrawer_20_made_more_compact_and_easy/

Maybe like dis?
Hmmmm.. I managed to not make them clutter formation by setting their "within" roughly based on the size of clumps they make.  Also if an enemy is near they will pause movement ai and shoot.
