### ISSUE TITLE
Allow setting the keybind to "Unset"

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry-Suggestions#4688]
### Describe the content or mechanics you are proposing.

when setting the keybind, press the ESC key to make that beykind "Unset"

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the useless keybinds have been using too much keys. for example, tech tree for a server player. it will be helpful if i can make them unset.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by snack-ie** [comment]
you should probably go in #development to give your feedback instead of making 5 suggestions in a row

**Comment by snack-ie** [comment]
well i mean this suggestion specifically isn't really feedback

**Comment by snack-ie** [comment]
but for the unit command and stance ones you should probably go there

**Comment by nanmenyangde** [comment]
ok i see
