### ISSUE TITLE
Autopause when no player is connected the server

### ISSUE THREAD

**Issue by Vojtak42** [Anuken/Mindustry-Suggestions#4689]
### Describe the content or mechanics you are proposing.

Autopause when all players disconnect (in all mods)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Hello, i would be grateful for this feature, because my dedicated server is always running for pretty long time but neither I nor any of my few friends are not connected (even for a few days) so we always lose and it is very incoveniet to always to connect to the virtual machine to pause the server.
Thank you in advance

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Can't you build a plugin for this exact use case?

**Comment by camelStyleUser** [comment]
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/124447863/55591357-9428-47c6-b768-dfeaa6dca56e)
just enable it with config easy

**Comment by camelStyleUser** [comment]
> [X]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
yes surely you checked that autoPause option doesnt exist anywhere

**Comment by camelStyleUser** [comment]
> Can't you build a plugin for this exact use case?

no need to

**Comment by Vojtak42** [comment]
sorry i tried only ggogle, because it finds things on the wiki most of the time
