### ISSUE TITLE
Some feedback on Differentrials

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#469]
**A comparison of Differentials to Pyratite Steam Generators**

*These numbers were all taken from the latest cutting edge build, last updated 9/7/2020*

**Space**
1 differential uses 9 tiles to make 1020 power. This is 113.33 power/tile
1 steam gen uses 4 tiles to make 462 power. This is 115.5 power/tile

In terms of space, **Steam > Differentials**

**Liquid**
1 differential uses 6 cryofluid to make 1020 power. This is 170 power/cryofluid
1 steam gen uses 3 water to make 462 power. This is 154 power/water

 **Steams are worse than differentials** (in this case), but you have to remember **differentials use cryofluid, not water** which In my book, effectively ties them up. 

In terms of Liquid, **Steams = Differentials**

**Materials**
In this comparison, each material will be "ranked" a cost based on how advanced it is. 
copper/lead = 1 "cost"
graphite/metaglass/silicon = 2 "cost"
titanium = 3 "cost"
1 differential costs 70 x 1 (copper) + 100 x 1 (lead) + 50 x 2 (metaglass) + 65 x 2 (silicone) + 50 x 3 (titanium) = 550 (total cost) while making 1020 power = 1.85 power/cost
1 steam gen costs 35 x 1 (copper) + 40 x 1 (lead) + 25 x 2 (graphite) + 30 x 2 (silicone) = 185 (total cost) while making 462 power = 2.50 power/cost

In terms of material cost, **Steam > Differentials**

**Item Input**
1 differential uses 1 pyratite to make 1020 power for 3.66 seconds = 3733.99 total power/item
1 steam gen uses 1 pyratite to make 462 power for 1.5 seconds = 695 total power/item

Honestly, **this is the only category where differentials do better than steam gens**, but wait, there's more. 

Steam gens are much more versatile. They can take in a variety of inputs, like coal, pyratite, or spores. this is a huge advantage over Differentials, as most players can't be bothered to set up pyratite factories anyway.

**Conclusion**
I see that Anuke has buffed differentials, and nerfed steams, but will this make differentials actually used? We shall see.

**Comment by itcannotbe** [comment]
You forgot that coal can never be scarce.

Also steam can also use spore pods and other materials.

**Comment by gen-NA-owl** [comment]
> You forgot that coal can never be scarce.

Look in the conclusion

> Also steam can also use spore pods and other materials.

Look in the Item Input section

**Comment by DeltaNedas** [comment]
agreed
i used diffs once pre-buff on desert wastes when i couldn't make coal, nevsr again

**Comment by scarf-generic** [comment]
If you have those resources, get a bit of thorium, make surge, add spores, and make an impact. Diff gens are usable in less situations than steam gens, produce less power, and for the cost of surge and spores you can make an impact.

**Comment by Anuken** [comment]
Honestly, I'm not sure if differential generators should exist at all. With their current inputs, they can't fill any specific niche. 
- If you have thorium, use thorium reactors
- If you have surge, use impact reactors
- If you're in early/midgame, use steam generators

**Comment by gen-NA-owl** [comment]
> Honestly, I'm not sure if differential generators should exist at all

You're right, but I like the idea of an upgraded steam generator. Maybe it could be reworked to fit a new niche?

**Comment by itcannotbe** [comment]
I blame impacts ease of use and the easy spammability of steam generators.

**Comment by gen-NA-owl** [comment]
well I did a small Reddit pole about what people think of differentials: 
https://www.reddit.com/r/Mindustry/comments/io0b95/what_do_you_think_about_differentials/
(I think people only picked the balanced option because of the quote)

**Comment by potatoisagender** [comment]
the way I think of differentials is as a transition from steams to impacts

You start with coal steams, upgrade to pyratite steams. Get titanium and you have differentials. Then get surge and the infrastructure is there for impacts.

The problem is that once someone goes to the trouble of making pyratite, they usually also have everything needed to make impacts.

The other problem is that thorium gens are also good for transitioning to impacts, because you make cryo AND you don't have to make pyratite. Thus they are less work and resource intensive.

The only time I ever saw someone use differentials is when we didn't have surge and we needed power.

**Comment by genNAowl** [comment]
> the way I think of differentials is as a transition from steams to impacts

I agree. The two main competitors to differentials are steam generators and thorium reactors, so maybe nerfing both of them might help.

**Comment by genNAowl** [comment]
I will close this now because my suggestion has been noted
