### ISSUE TITLE
world proc variable (like @tick, and @time) for playtime

### ISSUE THREAD

**Issue by Zerenta** [Anuken/Mindustry-Suggestions#4691]
### Describe the content or mechanics you are proposing.

i have challenges for my maps that rely on how long it took to do something in total (as in the playtime displayed at the end of the game), unfortunately, everything that counts time with world procs gets paused by pausing, it would be nice to have a way to track playtime with world procs

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

lets mapmakers do more cool stuff

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WMF-Industries** [comment]
@time doesn't get paused, it returns the playtime
