### ISSUE TITLE
Actual path finding for units using logic

### ISSUE THREAD

**Issue by EPICGUPPY44** [Anuken/Mindustry-Suggestions#4695]
### Describe the content or mechanics you are proposing.

Simply put, I want to use mech units in logic, but I’d like them to automatically pathfinder from point A to point B, not run into a wall.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Much better logic aspect

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
logic is already too op

**Comment by camelStyleUser** [comment]
(cant you already use `ucontrol pathfind`?)

**Comment by camelStyleUser** [comment]
(please explain to me why it isnt considered an implementation of this suggestion)

**Comment by camelStyleUser** [comment]
> [X]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

you have checked this box and confirmed that you ~~sold your soul to the devil~~ checked that there is no implementation of your suggestion in the game
