### ISSUE TITLE
Adding desynced client variables to world processors

### ISSUE THREAD

**Issue by ApsZoldat** [Anuken/Mindustry-Suggestions#4696]
### Describe the content or mechanics you are proposing.

Adding global variables like `@clientLocale` (most important one), `@clientName`, `@clientUnit`, `@clientName` to world processors as desync-control variables (used in `@client` mlog code)

`@clientUnit` - returns unit of player on whose device code is running (equal to `fetch player 0` but fetch only works in non-pvp maps)
`@clientName` - returns nickname string (equal to `sensor name`)
`@clientTeam` - returns team number (equal to `sensor team`)
`@clientLocale` - returns locale string from player (`en` for example)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Honestly, i know that adding controllable desync to world processors sounds weird and
> "is a hack that you don't want to encourage"

But it seems like it is the only possible way to make world processors display different information to different players depending on player's locale/team/other stats.

The overall desync idea is messy, but this feature will make it possible to localize maps (currently is a big problem in making multiplayer maps accessible, even some skilled players don't know English well) and do other useful things with processor.

These variables are required for controlled desync even with the fact that `fetch player 0` always (or almost always?) returns client's unit, because the fetch method is unintuitive and you can't use it if you don't know which team is player in.

What comes to the details of implementation, there's some things that seem to be problematic:
1. It's probably better to make these variables priveleged (like instructions), but this will require some minor changes in `GlobalVars`.
2. I don't know if there's a necessity in adding `@clientTeam` and `@clientName`, as you can sense them directly from player's unit, but they may be useful for displaying information when player doesn't have unit for some reason (for example, it haven't spawned yet).

Anyway, as the developer knows better, it's normal to change implementation in any way as required.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
How would these work?
I might be able to PR them.

**Comment by ApsZoldat** [comment]
I can PR these vars too, but the actual question is does Anuke even want to see them in the game and how will it be implemented, so i'm l

**Comment by ApsZoldat** [comment]
Missclick also

**Comment by ApsZoldat** [comment]
Added explanations to feature description (variable names were intuitive by the way)

**Comment by ApsZoldat** [comment]
Closed as i've made a pull request for this https://github.com/Anuken/Mindustry/pull/9138
