### ISSUE TITLE
Ability to change the storage capacity of the core

### ISSUE THREAD

**Issue by AFARIUS** [Anuken/Mindustry-Suggestions#4698]
### Describe the content or mechanics you are proposing.

In the process of creating the map, I noticed that the storage capacity of the Bastion core is not enough to put the Acropolis core. The capacity of the Citadel core is also insufficient for this. 

I ask you to add the ability to change the capacity multiplier of the core storage or set the capacity for each type of core both in the map settings and using the world processor. I'll give you an example:
@coreCapacity — a function in @SetProp that allows you to set a new value for the storage capacity of an individual core
@storageCapacityMultipier — a function in the map settings for each individual team that allows you to increase or decrease the storage capacity of the core with multiplier.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature will allow players to customize maps more flexibly, add new features and expand the current capabilities of map makers; let's just say it will make their lives easier:)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by idontknowhwhattoputhere** [comment]
I'm no modder, but you can probably steal the core sprite and code in your own version with custom capacity, if you're going for maps then this feature would be good though.
