### ISSUE TITLE
Better SetProp

### ISSUE THREAD

**Issue by Beelze1** [Anuken/Mindustry-Suggestions#4699]
### Describe the content or mechanics you are proposing.

Basically has more function and fun.
Example(s): 
setprop itemCapacity bastion1 100
setprop heatLevel afflict1 1000
setprop powerLevel foreshadow1 1000
setprop range unit 10
setprop maxHealth unit 1000
setprop speed unit 100
setprop shield unit 10

Would need some restrictions like for example (either ignore this)
setprop speed bastion1 10 = null (only for units)
setprop liquidCapacity unit 100 (for blocks only)
setprop ammo/ammoCapacity bastion1 100 (for turrets/units only)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make world logic more powerful than it is, plus world logic users would be able to make complex maps that would be cool thus possible to make advance maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AFARIUS** [comment]
I will also offer (can you put it in the list of examples?):
setprop heatLevel afflict1 1000
setprop powerLevel Foreshadow 1 1000

**Comment by Beelze1** [comment]
> I will also offer (can you put it in the list of examples?): setprop heatLevel afflict1 1000 setprop powerLevel Foreshadow 1 1000

Done!
