### ISSUE TITLE
New blocks suggestion.

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry-Suggestions#47]
Greetings.
I have some ideas for new blocks in Mindustry:
1) Large Liquid Tank. If there's a liquid tank in the game, why not add a large one?
Approximate capacity: 4,000
Size: 4x4
2) Bridge Platform. Can only be placed in deep liquid blocks. Allows you to place other blocks on it, just like on normal surface.
Size: 1x1
3) Large Bridge Platform. Same as a normal bridge platform, but spans multiple tiles.
Size: 2x2

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
1. a stronger tank imo is better
2. i like the idea of placeable floors
3. what does this offer over 4 of them
