### ISSUE TITLE
Unit railgun and Fusing ability

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry-Suggestions#470]
Unit railgun: Self explanitory. Has big range. Fire location set with H.
Swap: While using a mega, while you are holding a unit you can swap with it by hitting H. The mega will not be relased; It is held until H is pressed again.
FOR 6.0

The unit railgun can be used for long eange unit firing late game, useful if the enemy walls are too sttrong to break.
The swap ability could be very useful for users of the mega mech, so others dont steal it.

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This was already suggested as a unit cannon.

> hitting H

Unless a new key is absolutely necessary, I won't be adding one. The keybind dialog is already a mess.
