### ISSUE TITLE
Please make an account feature

### ISSUE THREAD

**Issue by MoNsTeR12360** [Anuken/Mindustry-Suggestions#4704]
### Describe the content or mechanics you are proposing.

Could you please make a account becuse I would really like to play on my phone and computer. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature would help people moving computers alot easier. And people with more computers beagle to switch when ever thay want and could you please reply if an answer is made and if this is already in the game can you please tell me how to do it

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
(if you mean cloud sync anuke put it in do not suggest list)

**Comment by TheEt1234** [comment]
copy your usid and uuid from your laptop to your phone

**Comment by TheEt1234** [comment]
> (if you mean cloud sync anuke put it in do not suggest list)

maybe he meant something minetest-like

**Comment by eeve-lyn** [comment]
use the steam version

**Comment by Slotterleet** [comment]
Please consider the fact that this game is mostly free to play, no ads, and no microtransactions, outside of Steam and App Store. Cloud saves are ruled out for a reason. This thing costs _money_, which I don't even know how much Anuke made from this game in the first place.

**Comment by camelStyleUser** [comment]
yes hosting servers **costs money**

**Comment by camelStyleUser** [comment]
if its free it is very limited

**Comment by camelStyleUser** [comment]
and cant be used for mindustry

**Comment by AiluroFelinus** [comment]
You could press a button to copy all the save info and put it in a file, then insert it to another Mindustry instance

**Comment by camelStyleUser** [comment]
> You could press a button to copy all the save info and put it in a file, then insert it to another Mindustry instance

you already can

**Comment by AiluroFelinus** [comment]
Where?

**Comment by camelStyleUser** [comment]
> > > You could press a button to copy all the save info and put it in a file, then insert it to another Mindustry instance
> > 
> > 
> > you already can
> 
> Where?

look in settings->game data

**Comment by AiluroFelinus** [comment]
> > > > You could press a button to copy all the save info and put it in a file, then insert it to another Mindustry instance
> > > 
> > > 
> > > you already can
> > 
> > 
> > Where?
> 
> look in settings->game data

Ok gracias
