### ISSUE TITLE
World Switch

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry-Suggestions#4705]
### Describe the content or mechanics you are proposing.

A world switch, functions exactly like regular logic switchs but with the key thing of being unbreakable by players/enemy

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would help in map making where players can get to choose between things or when there are variables that players can alter via switches

For example: in sandbox a switch that lets players alter the unitCap between 2 digits for more or less units (can help with testing stuff and lag reduction)

It would simply be remaking the switch to be unbreakable
 (if you add this please please make it place on the off state so procs can place it in the off postion)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
Switches in general should be disabled upon placement.

**Comment by Mythril382** [comment]
> Have you tried something similar? Lets say you want a unit cap between 0 and a hundred then loop back to zero once it reaches 99 On sensor enabled switch1 set prop health of switch1 to 1000 jump 0 if On === 0 set enabled of switch1 to 0 i=i+10 i=i%100 setRule unitCap to i

They wanted unbreakable switches without setting up setblocks. That was just example code... that he put for no reason.

**Comment by Optimal-performer-38** [comment]
> > Have you tried something similar? Lets say you want a unit cap between 0 and a hundred then loop back to zero once it reaches 99 On sensor enabled switch1 set prop health of switch1 to 1000 jump 0 if On === 0 set enabled of switch1 to 0 i=i+10 i=i%100 setRule unitCap to i
> 
> They wanted unbreakable switches without setting up setblocks. That was just example code... that they put for some reason.



Hmmm I don't think people will wait for the content to be added by devs if they can do it themselves.

**Comment by Optimal-performer-38** [comment]
Hmm. On second thought mindustry block health can't be expanded through setProp so they can be instantly destroyed.
So here's an autoBuild instead. It stores each position of switches in banks (but 0 to 511 only) and rebuilds them there instantly if ever buildCountNew is < than the buildCountInital

bXNjaAF4nGNgYWBmZmDJS8xNZeBLLC3JT8usUCguzyxJzmDgTkktTi7KLCjJzM9jYGBgy0lMSs0pZlCNVopWTktLNDdPjH23cKuSTj5QRW5ijkJBalFaflFuapGCsUUsEwN3bmpuflGlblJiXjYDf3l+UU6KbkFRfnJqcXF+EdA8ZgYIYARiJj4g8atiTmlAdN5hBQGVib8Oa37jUPz7KX6phvkL1g03ucxZYuQ21R6I09bUcckLCfUwsD5jsPuNxO3a+gQZky+ZJq+eTOp9YKgi/FA346WolkWKRX/kEfvLpU3hBhKHdk/7tnCP1VHmSzc13qlN8GoslLygxhXKIh2as/+Q4ploNc55Sa0/1K+zPU9U/P5JI1wr3O63YdK6qkx996otgdyBi4LkljY91d9qJ/m5ZW/hYdZX92Zp71tz2271iz1nBGOvi9r8NOp0y1ykFxs6a1fJtFsu2tXNq3pvOnbUyTz6qe0ZrNK0OLSmwKwqfUFn98cA8VjjY9/etLIlvKlb/eHEt++3+RkDl+wGBQEoLABp6p3i

**Comment by JasonP01** [comment]
> Switches in general should be disabled upon placement.

yes ik, ive suggested that as well but it went ignored so this is the better option since i cant suggest the same thing again

**Comment by JasonP01** [comment]
> Hmm. On second thought mindustry block health can't be expanded through setProp so they can be instantly destroyed. So here's an autoBuild instead. It stores each position of switches in banks (but 0 to 511 only) and rebuilds them there instantly if ever buildCountNew is < than the buildCountInital
> 
> bXNjaAF4nGNgYWBmZmDJS8xNZeBLLC3JT8usUCguzyxJzmDgTkktTi7KLCjJzM9jYGBgy0lMSs0pZlCNVopWTktLNDdPjH23cKuSTj5QRW5ijkJBalFaflFuapGCsUUsEwN3bmpuflGlblJiXjYDf3l+UU6KbkFRfnJqcXF+EdA8ZgYIYARiJj4g8atiTmlAdN5hBQGVib8Oa37jUPz7KX6phvkL1g03ucxZYuQ21R6I09bUcckLCfUwsD5jsPuNxO3a+gQZky+ZJq+eTOp9YKgi/FA346WolkWKRX/kEfvLpU3hBhKHdk/7tnCP1VHmSzc13qlN8GoslLygxhXKIh2as/+Q4ploNc55Sa0/1K+zPU9U/P5JI1wr3O63YdK6qkx996otgdyBi4LkljY91d9qJ/m5ZW/hYdZX92Zp71tz2271iz1nBGOvi9r8NOp0y1ykFxs6a1fJtFsu2tXNq3pvOnbUyTz6qe0ZrNK0OLSmwKwqfUFn98cA8VjjY9/etLIlvKlb/eHEt++3+RkDl+wGBQEoLABp6p3i

@Optimal-performer-38  good suggestion but doesnt work as the switches are in the player team and are not banned, this gives issues as deleting the switch is the same as destroying it and therefore makes it impossible to delete switches (as u can imagine the griefing that could happen with that)

**Comment by Optimal-performer-38** [comment]
> > Hmm. On second thought mindustry block health can't be expanded through setProp so they can be instantly destroyed. So here's an autoBuild instead. It stores each position of switches in banks (but 0 to 511 only) and rebuilds them there instantly if ever buildCountNew is < than the buildCountInital
> > bXNjaAF4nGNgYWBmZmDJS8xNZeBLLC3JT8usUCguzyxJzmDgTkktTi7KLCjJzM9jYGBgy0lMSs0pZlCNVopWTktLNDdPjH23cKuSTj5QRW5ijkJBalFaflFuapGCsUUsEwN3bmpuflGlblJiXjYDf3l+UU6KbkFRfnJqcXF+EdA8ZgYIYARiJj4g8atiTmlAdN5hBQGVib8Oa37jUPz7KX6phvkL1g03ucxZYuQ21R6I09bUcckLCfUwsD5jsPuNxO3a+gQZky+ZJq+eTOp9YKgi/FA346WolkWKRX/kEfvLpU3hBhKHdk/7tnCP1VHmSzc13qlN8GoslLygxhXKIh2as/+Q4ploNc55Sa0/1K+zPU9U/P5JI1wr3O63YdK6qkx996otgdyBi4LkljY91d9qJ/m5ZW/hYdZX92Zp71tz2271iz1nBGOvi9r8NOp0y1ykFxs6a1fJtFsu2tXNq3pvOnbUyTz6qe0ZrNK0OLSmwKwqfUFn98cA8VjjY9/etLIlvKlb/eHEt++3+RkDl+wGBQEoLABp6p3i
> 
> @Optimal-performer-38 good suggestion but doesnt work as the switches are in the player team and are not banned, this gives issues as deleting the switch is the same as destroying it and therefore makes it impossible to delete switches (as u can imagine the griefing that could happen with that)
> 
> Also the purpose of which i suggest this is sandbox map which again emphasizes the issue

hmmm. I would like indestructible yellow switches too.
But let's say we don't yet have them. 
Lets say you are on sandbox and you want multiple indestructible switches that can't be destroyed by other players while still being able to build their own switches freely.
Instead of fetching every switches with buildCount.
You can make a loop "i" with @links, and then getlink "i" to reference linked switches, store their positions and rebuild them if new.buildCount is lesser than initial.buildCount. The issue is that you can steal the switches for payload. If used on normal processor you can use this with a unit build script to rebuild your base.

**Comment by JasonP01** [comment]
@Optimal-performer-38  (im not refrencing that nightmare of a quote reply)

Im already sensoring `@dead` in the procs that handle the switches anyway (since we dont have that) my issue is already solved cause i can think (some people cant), thanks for trying to help but im good with what i have!

Still would really love this suggestion to be accepted @ Anuken reply (purposely didnt ping correctly)

**Comment by JasonP01** [comment]
Got told to pingus u @Anuken (look at all the reactions on the suggestion XD)
![Screenshot_20231006_214249_Discord](https://github.com/Anuken/Mindustry-Suggestions/assets/131086642/19159917-1230-4249-a776-8a54e80ba6c3)

**Comment by rekokoro** [comment]
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/17054049/9f44d46f-b957-42ad-b316-1e8bb5cf590a)
my sandbox maps using two "invisible" switches that can be activated only by players pressing them so there's no actual reason to implement world switches in game.
