### ISSUE TITLE
Add the ability to sync the data if memcells with the wproc `sync` instruction

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4706]
### Describe the content or mechanics you are proposing.

Either an option to sync memcells with wproc `sync` or anything similar instruction to sync a memcell. If desired you could also just have it sync one index, to reduce the overall amount of syncing

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

`sync` works great if you have data you're only updating once per code loop. But whenever you're looping over data (such as a `fetch` loop for all players), it becomes a huge pain to keep the variables synced, as it sometimes syncs data from the same variable at a different point in the execution. Being able to sync memcells would allow the user to store data for all the players, and keep it synced easily.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Optimal-performer-38** [comment]
I don't fully understand, why not use a slow loop and a regular loop? Example you need to store exactly 10 lines of data for each player:

fetch player count playerCount
 i= i + increment (increment = 1/10 or 0.1 per increment per cycle)
 i= i % playerCount (no. of players) 
var.player = floor of i
PlayerX fetch player var.player
Whatever sensor @whatever of PlayerX
limitLine = playerCount * 10
i2= i2 + 1
i2= i2 % limitLine 
write Whatever to bank1 at i2

(Im assuming you want a processor to only cycle to the next player once all the needed individual data has been stored. If im wrong, welp im wrong but check out this array, im self advertising lol)

https://www.reddit.com/r/Mindustry/comments/16ogqar/a_slightly_better_version_that_can_store_about/

**Comment by SkyeTheFoxyFox** [comment]
the problem is desyncing

**Comment by Optimal-performer-38** [comment]
> the problem is desyncing

What is desyncing?  And what is it supposed to do

**Comment by Varxalaxiacis** [comment]
> > the problem is desyncing
> 
> What is desyncing? And what is it supposed to do

**Comment by Varxalaxiacis** [comment]
dsync : 
basicly client 1 and 2 precive or got data diffrently like
player 1: supposed to have data(a) but got data(b)
player 2: however got data(a)

**Comment by Optimal-performer-38** [comment]
> dsync : basicly client 1 and 2 precive or got data diffrently like player 1: supposed to have data(a) but got data(b) player 2: however got data(a)

Oh you mean "read".  Dude, use simple terms. To read the data by another processor as how you stored it in the initial proc, you can : 
A. copy paste that same code so that the loop is synced and then swap the "write" with "read" and maintain the "loop" lines. This 'syncs' or reads the data in the cell incrementally.
B.if you want the other cell to purely read (and no fetches, or sensor, fetch player, buildCount etcc) Write the playerCount to a third cell then on the reading processor add 1 to it so that instead of 0≤i> p.Count.
The loop limit becomes 0≤i≥p.Count

**Comment by Optimal-performer-38** [comment]
![Screenshot_20230921-212152](https://github.com/Anuken/Mindustry-Suggestions/assets/145533195/33bdd5a5-a2f1-4bbb-b249-602df2c8d6e2)
I use something similar to store continuous data in multiple banks.
You don't encounter this issue in js because you could just auto- create more arrays for each new variable.

**Comment by SkyeTheFoxyFox** [comment]
No, desync is where the client and server have a different value for the same variable or cell index. This is because mindustry doesn't actively sync data between the server and clients to save on network usage. This leads to problems with world logic that intends to work in multiplayer, as they can end up doing different things for different people. to combat this we got the `sync` instruction, it will sync a variable when ran, however, due to the nature of it, it struggles to sync data if the variable has to change multiple times during a code loop, such as when you're looping over stuff.

**Comment by Optimal-performer-38** [comment]
Awsus. Silly me. I misunderstood. I am going to pack 
my stuff and leave this thread to keep some dignity.
