### ISSUE TITLE
Server Rule "Exchange between Teams"

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry-Suggestions#4708]
### Describe what you would like changed, and why.

Normal exchange with other teams
5 Recently I was at the “official hexes with exchange” event, it’s terrible...
if you want to make an exchange between players, simply allow the transfer of items between conveyors and catapults of different teams

1 New server setting to increase the exchange between blocks of different teams.

2 Energy nodes can connect with enemy nodes but will work like diodes and transmit excess power, that is, by connecting you share but do not take.
You can only connect manually.

3 Conveyors can also take resources from blocks.
but this will give scope for theft, but the measure of the fight lies in the turret tab

4 Catapults: if an enemy catapult is connected to other catapults, it is not available for exchange, only the unconnected catapult can accept resources

### Describe the changes you want to propose. Include possible alternatives.

new server rule: inter-team resource transfer
allow transfer between different teams of conveyors, catapults and power units.

**Comment by idontknowhwhattoputhere** [comment]
So, cross teaming?
