### ISSUE TITLE
The ability to scroll between what drills mine with the scroll wheel.

### ISSUE THREAD

**Issue by idontknowhwhattoputhere** [Anuken/Mindustry-Suggestions#4709]
### Describe the content or mechanics you are proposing.

Assume theres a single bit of copper and 4 sand under it, and you want to mine the sand with a drill. It will allways mine the ore if the drill level is high enough, what if i want the sand? Thats what this feature is for.

Since you don't need to rotate drills and the scroll wheel is free, i suggest using the scroll wheel to be able to scroll between ores,(As an example, scroll between sand, copper, and coal).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will allow us to mine 4 sand, not 1 copper.
Also generally useful.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
@idontknowhwhattoputhere and what about mobile? They have to be the same to some degree and this level of mechanics would have to be in mobile as well

**Comment by AiluroFelinus** [comment]
You could just tap it like a sorter

**Comment by ziszlo** [comment]
я уже предлагал такую идею , анюк против потомушто буры бурящие все ресурсы под собой нарушат геймдизайн игры и игрокам будет скучно постоянно сортировать ресурсы , выбор в бурах не имеет смысла потомушто просто используй другой бур заняв другое место .

**Comment by idontknowhwhattoputhere** [comment]
> @idontknowhwhattoputhere and what about mobile? They have to be the same to some degree and this level of mechanics would have to be in mobile as well

The rotate button is free...

**Comment by AiluroFelinus** [comment]
> я уже предлагал такую идею , анюк против потомушто буры бурящие все ресурсы под собой нарушат геймдизайн игры и игрокам будет скучно постоянно сортировать ресурсы , выбор в бурах не имеет смысла потомушто просто используй другой бур заняв другое место .

What if it's a new kind of drill and it drills half as fast to make up for the more work it does
