### ISSUE TITLE
[scripts] a way to read and write save data

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#471]
**Describe the content or mechanics you are proposing.**

A section in saves for modded data **that is not bound to other data**.
For example, writing an array of networks in mod section and then write the index in the networked block.

Data-wise, it could look like
```
byte numberOfModsThatCalledWriteSave
{
    String name
    byte version
    int length
    byte[length] data <-- comes from writeSave
} [numberOfMods]
```

If a mod is not present, <length> bytes can be skipped.

Mod code would look something like
```js
readSave((map, read) => {
    print(read.str());
});
writeSave((map, write) => {
    write.str("egg");
});
```

which would write `1 7 coolmod 0 5 2 egg`

read/writeSave would be wrappers in base.js using `modName` to register mod-specific handlers for reading and writing saves.

Saving the length could be removed, but that would brick saves with mods not installed\.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Mods have no (good?) way of doing save I/O.
This makes it easy, safe and versatile.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sk7725** [comment]
oh *yes*

**Comment by sk7725** [comment]
ohhhhhhhhhhhhhhhhhhh thank you so much roomba
