### ISSUE TITLE
Wet Units Get Muddy in a Sandstorm

### ISSUE THREAD

**Issue by AiluroFelinus** [Anuken/Mindustry-Suggestions#4710]
### Describe the content or mechanics you are proposing.

During a sandstorm, any units that are wet should get the muddy effect too. This reflects real life as sand is essentially flying rocks/dirt, and mixed with water it makes mud.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would make the average speed of a unit slightly lower, which matches the visibility change during sandstorms. It would also make sandstorms at least have a use.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
Only problem is muddy effect has no uses and does literally nothing, its not even applicable via cmds

**Comment by AiluroFelinus** [comment]
Oh, I saw it in the code and thought it existed. If it's there already though, it shouldn't be hard to implement and put mud tiles along with it, which would output sand or nothing if drilled and water if extracted

**Comment by Mythril382** [comment]
Mud tiles *do* apply muddy, but muddy still does nothing other than slow down. Also Mindustry isn't made to be realistic.

**Comment by AiluroFelinus** [comment]
Ok so it does work
It would only slow down a little bit and not much of the time either, but I still think it's a cool interaction
