### ISSUE TITLE
UnitCapWeight modding class for units

### ISSUE THREAD

**Issue by MaxMindustry** [Anuken/Mindustry-Suggestions#4711]
### Describe the content or mechanics you are proposing.

A modding class that responsible for the number of unit slots required for them.
For example: there is a core with a unitCapModifier 8, and a unit with UnitCapWeight 2. This means that it is possible to produce 4 such units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help to controll amount of high tier units. Sometimes all you have to do is wait for your unit factory to produсe an army of high tier units and win with a single push. UnitCapWeight can help solve this problem. For example you can make 24 t3 units (UnitCapWeight: 1 (default) ), 4 t4 units (UnitCapWeight: 6 ), 1 t5 unit (UnitCapWeight: 24 ). this means that every tier of units can
be useful. I am making a modded campaign and this change is the only way to fix problems with balance.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Zerenta** [comment]
ngl if your map design allows that, thats just a skill issue, the enemy should always escalate to the point where theres no way to actually survive it
but yeah unironically good idea and ive been wanting this for a while (to the point where i made it in world proc)

**Comment by Zerenta** [comment]
also if we could like assign our own weights to each unit through rules editor that'd be cool af

**Comment by S0meM** [comment]
Honestly, the fact that higher tiers take so long and that they take so much resources kind of works by itself. That's not to say that this isn't a good idea, just make it default to 1. Or, make it so that each unit just has it's own cap. That seems like it would be easier to use.
