### ISSUE TITLE
Alpha channel for processor draw clear

### ISSUE THREAD

**Issue by TheEt1234** [Anuken/Mindustry-Suggestions#4716]
### Describe the content or mechanics you are proposing.

Alpha channel for the processor "draw clear" command

Example: if you did clear 0 0 0 5
it would darken the screen a little

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

~~it would be cool~~

actually yeah i dont have anything else to say

hopefully i wont get destroyed in the comments

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
pro(just draw a (clear color) rectangle with specified alpha and it will work the same like what you want)
