### ISSUE TITLE
Better Translations for Indonesian Language

### ISSUE THREAD

**Issue by Kenny-Ofc** [Anuken/Mindustry-Suggestions#4717]
### Describe what you would like changed, and why.

yap, even i understand English, but some people probably get struglling when reading the description of Sector Objective even The Description of Block with Indonesian and English Language. i would to help if u like, to fixing Indonesian Language in Mindustry Game

### Describe the changes you want to propose. Include possible alternatives.

Improve an Indonesian Language in game, The Tech Tree, and Sector Objective

**Comment by Ruichka** [comment]
https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md
