### ISSUE TITLE
玩家外觀多樣性

### ISSUE THREAD

**Issue by Yrckam** [Anuken/Mindustry-Suggestions#4718]
### Describe the content or mechanics you are proposing.

皮膚系統供玩家自行娛樂使用 且只能玩家自己畫或者拿別人畫出來的又或者只用原本的皮膚

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

增加每個玩家的獨特性

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
Translation to people who refuse to translate:

**Describe the content or mechanics you are proposing.**

The skin system is for players to use for their own entertainment and can only be drawn by the player themselves or drawn by others, or only use the original skin.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Increase the uniqueness of each player

_________________________________________________________________________________________________________________________

I personally think this is a terrible suggestion if u want "diversity" on player clients just change the sprite for ur unit
