### ISSUE TITLE
Liquid Storage

### ISSUE THREAD

**Issue by Haka654321** [Anuken/Mindustry-Suggestions#4719]
### Describe the content or mechanics you are proposing.

You would be able to transport liquids across sectors with this feature allowing you to store for example slag so that you can power a tsunami you have in a different sector but you cant make slag in that area yet.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make it so we can make factories even more efficient and allow us to make defences quicker without having to build everything up and risk the core whilst doing so.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by python-nerd-3** [comment]
#1566 this has been suggested before
