### ISSUE TITLE
Wind Turbines?

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#472]
**Describe the content or mechanics you are proposing.**

A generator that makes energy from the wind in the environment. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Honestly, I feel like something like this would go well with the new weather types in 6.0; Like how solar panels don't work during the night, wind turbines don't work where there isn't much wind. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by gen-NA-owl** [comment]
This is just an idea that I'm throwing out there; I've looked into the hydroelectric power station issues and PRs, and based on their reception, am not sure if this will be received well.

**Comment by mangblekok** [comment]
Nah... It would be too easy to create power on remote area and attack the enemy with these outpost base.
I'm against this idea, unless the initial resource requirement is quite high, so players can only build this thing on late game.

**Comment by genNAowl** [comment]
> too easy to create power on remote area and attack enemy with these outpost base

Same goes for Solar Panels, but they are still in the game. 

> initial resource requirement is quite high

Why? Solar Panels don't cost that much.

**Comment by SonPlaying** [comment]
I up this. Honestly need more ways to make power, and not just the steam generators that need coal, or spore pods(needs electricity)😭

**Comment by Kyllingene** [comment]
#335
Anuke:

> and the conclusion was that hydroelectric power isn't very interesting, and would just be a slightly different version of solar/thermal generators.

Wouldn't wind turbines be even closer to solar/thermal generators than hyrdoelectric turbines?

**Comment by genNAowl** [comment]
I dunno; This concept was based on the Wind Turbine in Astroneer, and because of the fact that wind turbines only work in certain weathers there, the Wind Turbine still seems to fill a niche separate from Solar Panels.

**Comment by Kyllingene** [comment]
So they would produce more power than solar panels, right?

**Comment by itcannotbe** [comment]
What prevents this from being another solar panel?

**Comment by Kyllingene** [comment]
The different use conditions? Just like the Astroneer original, it is more a little boost of power than a main power source.

**Comment by itcannotbe** [comment]
I mean sure, you can make it give more power, but without other unique mechanics, it would just be another solar panel.

Also people hate RNG.

**Comment by itcannotbe** [comment]
Maybe it give more power if a certain area around it doesn't have blocks including environment walls but not including transport blocks (conveyors, routers, conduits and the like)

**Comment by genNAowl** [comment]
So the power production changes based on the solid blocks around it?

Kinda reminds me of the turbines from Forts.

**Comment by itcannotbe** [comment]
Yeah, the mechanic is similar enough.
