### ISSUE TITLE
Make latums and renales obtainable

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry-Suggestions#4720]
### Describe the content or mechanics you are proposing.

Latums could be created by inputting 40 neoplasm per second in a tank assembler producing conquers, this would require 2 neoplasm reactors to run at max speed. Renales would be made by putting 20 neoplasm per second in a tank refabricator.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The content would allow you to get more use out of a neoplasm reactor, as latums are quite powerful. It would force you to care about the piping to the assembler to avoid it overfilling and exploding your reactors, adding challenge to getting the unit. The addition of an "overflow valve" wich would work like an overflow gate but for liquids could be made to make the process not need to be constantly watched over. Also i just think latums and renales are neat close range units, something the erekir campaign doesn't have a lot of.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
Neoplasm is a waste product and is currently being expanded upon, if you've paid any attention to #development

It appears it will become a hostile biological faction

**Comment by Haznobrain** [comment]
well, if you could use it yourself it would be good too
