### ISSUE TITLE
Increase display logic operation limit or introduce operation to draw vertices of a shape without connecting the points

### ISSUE THREAD

**Issue by TopCatTC** [Anuken/Mindustry-Suggestions#4721]
### Describe the content or mechanics you are proposing.

I made a bug report but it seems to be a feature: I suggest either the draw limit on display logic be increased (I think its around 100 now) OR a new operation(s) that allows the player to draw the vertices of a certain shape but not connect them, essentially drawing multiple points with one operation. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow for more useful display logic, for example: Drawing all unit locations on the map to a display which can include whether they are currently targeting something, if they're damaged etc. Now this is possible however in a map where the unit cap is above the draw cap (The case in larger multiplayer maps such as Boxfort), some of the units will either not appear at all or periodically appear then disappear from the display.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
first no the graphics buffer limit is 256 not 100 and by flushing you can increase it to 1024 per tick(/!\\) and it would be hard to break the limit without antithreading
