### ISSUE TITLE
EMP cannon

### ISSUE THREAD

**Issue by MmmmmmmmmmmmmmmmmmmToast** [Anuken/Mindustry-Suggestions#4722]
### Describe the content or mechanics you are proposing.

A Large  tower that shoots a payload that has a area of affect the size of the battle area causes all enemys to be unable to move or shoot for a while does not do any DMG. Also can affect your own equipment and takes down enemy sheilds but the sheilds come back at full once the EMP is over It should require a insainly large battery system to fire it would have a large range and extreamly slow recharge rate like maby one or  once every couple of waves battle and it takes a long time to build at most the tower shoulbe late game not be able to affect air troops it should have a very large range larger than anything else. I am not sure if this would be better but the player can only shoot it becouse it takes so much energy. The range should not be able to reach a enemys bace from the center of your bace though.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

When fighting against baces you would be able to use it as artilary to disable enemy AA and use the  upgrated mono units to carry large units past some enemys fortifications. This will create a new strategy that the player can use.
Sry if this was already a thing that was removed that i didnt see.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by python-nerd-3** [comment]
No

**Comment by S0meM** [comment]
This sounds more like something that we would want to add in a mod than the base game. It would honestly still be too OP because you'd have to let logic control it, and then it'd be an anti-guardian tower.
