### ISSUE TITLE
Buff crawler

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4723]
### Describe what you would like changed, and why.

As title says, crawler presents unique way of combat but has a fatal flaw in its attack power. For units that can be easily swept by a pair of bunch of salvo/lancer constant damage at the cost of their life deals far less damage than same bunch of flares.

### Describe the changes you want to propose. Include possible alternatives.

So here's the buff - change basic crawler damage to their hp and increase explosion damage and radius proportional to amount of shields left before explosion.

In player case crawlers spawn with 0 shields which regenerates till double hp value so undamaged crawler will deal up to triple damage (if shields broken or crawler is dead, damage drop down to basic explosion).

In wave case crawlers can spawn with custom amount of shields and conveyor spam won't hold them for long as it now. 

As alternative, using world processor with explosion command can't reproduce the buff due to inability to tell how attack has been fired - after destruction (which has to be constant damage) or triggered by crawler itself (shield damage applied).

**Comment by TheEt1234** [comment]
i believe crawler is insane when you don't have titanium or can't outrange it

**Comment by BlueWolf3682** [comment]
No. Crawler is already the most busted T1 unit. Stop using it in cases that you'd want T2s or T3s.

**Comment by python-nerd-3** [comment]
crawler is pretty balanced, it only deals real damage when you have very weak defenses

**Comment by rekokoro** [comment]
Guys, this thread isn't about to make or not the crawler, but about having crawlers in enemy waves. Even dagger (technically?) can cause issue or two just by having enough shields to tank incoming damage while units behind him fries out your defense, But crawler? no matter how much shields it has, it'll still end up with "poof" and 25% damage to small walls as soon as it touch anything.
