### ISSUE TITLE
Make rule that allows units to shoot while being carried

### ISSUE THREAD

**Issue by StesNiash** [Anuken/Mindustry-Suggestions#4725]
### Describe the content or mechanics you are proposing.

Make rule that allows units to shoot while being carried
To not make this too op make another rule like "carry penalty" which will decrease damage dealt by carried unit
so megas, polys and every other support tech tree units would be more useful on front line

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

at first: ships would become more useful
support units would become more useful
this would make units like velas even more useful (quad will carry it to heal near units)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by ziszlo** [comment]
я тоже хотел предложить данную функцию , но но , поскольку мы можем переносить нескольких юнитов это будет имбалансно , мерой ограничения имбалансности предлагаю : подобранный юнит может стрелять только если он один в багажнике , если у вас более 1 юнита они не могут стрелять . 
также мерой баланса будет служить то что при гибели носильщика погибает и носимый . 

в идеале это нужно совместить с возможностью носить юнитов в которых сидят игроки , разумеется игрок может отказаться быть возимым , но возможность возить юнитов с игроками и стрелять привнесла в игру новый уровень боевых возможностей , как говорится ДОБРО ПОЖАЛОВАТЬ ВО ВЬЕТНАМ , БИЛЛИ ОНИ НА ОКТАХ!!!!
