### ISSUE TITLE
Make rule that allows to build and carry blocks by controlled units

### ISSUE THREAD

**Issue by StesNiash** [Anuken/Mindustry-Suggestions#4726]
### Describe the content or mechanics you are proposing.

Theres build command for units but it always disabled so its becomes useless
make rule that allows them to build or carry block while being controlled by processor

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

new way to transport items (megas with containers)
new possibilities to build defense in pvp modes
new way to healing units (megas with repair point/turret and batteries)
new way to blow everything (automate quads with thorium reactors)
new way to BvB (placing loaded turrets near opponents base)
new way to making schemes (you only place processor and units build everything else)
new way to have fun

only problem is griefers, but including that this will be rule this wont be problem, and there is FFA modes so this wont be a problem there either

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by WMF-Industries** [comment]
Units can already interact with payloads using processors, the build command found in logic on the other hand is controlled by whoever set up the server, instead of adding another rule ask the server owner to enable the logic command in the server config (which they likely won't do)
