### ISSUE TITLE
Serpulo core unit behavior change

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4729]
### Describe what you would like changed, and why.

Erekir core units has one specific feature that makes them much more comfortable to use than serpulo ones - they can't be targeted, and you're not stuck in respawn-death loop while under attack, especially when enemies are not enough to break your stuff but still can and do oneshot you. 

And just a remind, this is the game about protecting your core rather yourself as unit, so proposed changes are all about that. 

### Describe the changes you want to propose. Include possible alternatives.

Two changes:

1. Enemy units ignore core units unless is commanded to do so. Yes, core units can win the fight 1 vs 1 with T1 or T2, but one unit won't be enough to fight more and more increasing waves. Turrets still can target as usual.
2. Due to ability to sneak into enemy structures and deal more or less damage, enemy units will still be able to autotarget core units if they snuck into no-build core zone.

**Comment by eeve-lyn** [comment]
the entire reason erekir core units can't be targetted is because they can't fight back, they can't do anything really
erekir core units can only be targetted when carrying payload, because they could take something dangerous like an ozone tank and bring it directly to the enemy base.

**Comment by rekokoro** [comment]
Sorry but in front of t3-t5 core units can't fight back but are instantly vaporized. If we include inability to switch cores while in despawned mode, this become a kinda annoying softlock until the core or enemies are dead, while being offtarget could help in, for example, restoring supplies for turrets and etc. 

And i don't think that flying double duo with doubled range can be somehow gamebreaking - we already have typical outrange fights vs t1 units now.

**Comment by jehosula** [comment]
> Sorry but in front of t3-t5 core units can't fight back but are instantly vaporized. If we include inability to switch cores while in despawned mode, this become a kinda annoying softlock until the core or enemies are dead, while being offtarget could help in, for example, restoring supplies for turrets and etc.
it does not have to softlock and you don't get vaporized by t3 and you can't even build stuff near t4/t5 regardless
> And i don't think that flying double duo with doubled range can be somehow gamebreaking - we already have typical outrange fights vs t1 units now.

it makes it too easy to neglect defense early also it's more like 2.5x not 2x at least outrange fights have skill in maintaining distance
Enemy units ignore core units unless is commanded to do so. Yes, core units can win the fight 1 vs 1 with T1 or T2, but one unit won't be enough to fight more and more increasing waves. Turrets still can target as usual.  WHY? That is just silly 
Due to ability to sneak into enemy structures and deal more or less damage, enemy units will still be able to autotarget core units if they snuck into no-build core zone. huh? they deal 1% damage why suggest something complicated all for a non-existent problem
do you get that the weapon is only for the early waves to make it reasonable to build defense on waves 3-5 and not wave 1

**Comment by rekokoro** [comment]
Okay, i got it. You're talking about campaign experience. I'm talking about multiplayer and co-op.

So:

1. "neglect defense early". In resource acquirement terms serpulo is harden than erekir. You have to aquire at least 3 different types of resources to make duo at least decently fight back t1 units, or 5 to outrange them. Compared to it erekir is much simpler for setting premature defense - you're flying mender, energy production isn't consume anything and you can always place turret next to enemy ramming your core and they'll ignore it.

Moreover the fun fact is that i don't remember losing to first 5-6 waves early even without placing a single turret.  Fighting enemy (even with being targeted) will still consume time that you can spend on expanding production so it's not much an issue.

2.  "Enemy units ignore core units". Turrets is passive defense, meant to mark and defend territory behind them, while units is just a walking turrets without necessity to be fed with ammo. They can be used both for defense and offence, so that's why while they used for defense - they can target core units who sneak out to no-limits zone where they can't build anything.  But in offence way - well, unless enemy players specifically wants to troll, unit will just not give a damn thing about the flies flying around.

3. Even with "1% damage" you can just destroy just one single node and ruin all the plans mapmakers was expecting for.  

The thing is - this game doesn't separate singleplayer and co-op experience, so introducing thinks "only for multiplayer" is useless. This change in fact won't break balance in singleplayer - situation where you can destroy whole wave with your unit appears only in early game and jumping back and forward between sectors to not build turrets is just a dumb. In multiplayer case where multiply cores isn't a rare occurrence as much as mass attacks, it'll solve many issues with player softlocks.

**Comment by Varxalaxiacis** [comment]
> Okay, i got it. You're talking about campaign experience. I'm talking about multiplayer and co-op.
> 
> So:
> 
> 1. "neglect defense early". In resource acquirement terms serpulo is harden than erekir. You have to aquire at least 3 different types of resources to make duo at least decently fight back t1 units, or 5 to outrange them. Compared to it erekir is much simpler for setting premature defense - you're flying mender, energy production isn't consume anything and you can always place turret next to enemy ramming your core and they'll ignore it.
> 
> Moreover the fun fact is that i don't remember losing to first 5-6 waves early even without placing a single turret. Fighting enemy (even with being targeted) will still consume time that you can spend on expanding production so it's not much an issue.
> 
> 2. "Enemy units ignore core units". Turrets is passive defense, meant to mark and defend territory behind them, while units is just a walking turrets without necessity to be fed with ammo. They can be used both for defense and offence, so that's why while they used for defense - they can target core units who sneak out to no-limits zone where they can't build anything.  But in offence way - well, unless enemy players specifically wants to troll, unit will just not give a damn thing about the flies flying around.
> 3. Even with "1% damage" you can just destroy just one single node and ruin all the plans mapmakers was expecting for.
> 
> The thing is - this game doesn't separate singleplayer and co-op experience, so introducing thinks "only for multiplayer" is useless. This change in fact won't break balance in singleplayer - situation where you can destroy whole wave with your unit appears only in early game and jumping back and forward between sectors to not build turrets is just a dumb. In multiplayer case where multiply cores isn't a rare occurrence as much as mass attacks, it'll solve many issues with player softlocks.

1."talking multiplayer" well multi player < more player = more dmg and dont forget about dmg multiplier
2."multiplayer have more core" player can spwan in diffrent location
3. "defence early" yes it can go trougth but due to a lot player it can be broken in some cases or even trolling

**Comment by rekokoro** [comment]
1. more player - more player can mine and build something rather than going in full offence and solo pew-pew-pew each wave. Especially on start game where you have to acquire three(in best case four) different resources so turret'll start actually deal the damage.
2. only player controlled unit can "spawn in core", not player itself. And each respawn resets camera back to player so it's impossible on unmodded client to escape this trap.
3. "it can be broken" without stating how?
4. Yeah, but what if enemy strength is not enough to shot your core down but still enough to shot you spawning from the core?
5. what?

**Comment by jehosula** [comment]
1 only need copper for passive defense and only one or 2 players needs to be early defense before arcs and monos can be build unless the first wave is huge and in that case your suggestion is not good
2 not true and even then it only happens if the defense got destroyed mouse wheel for PC to go to a different core and dragging to one on mobile
3 it's stated at least now
4 it does not happen unless 5+ quasar or a very specific level of piercing enemies
5 got a point

**Comment by rekokoro** [comment]
Too much points for discussion results in every point makes no sence.

To sum it up - mindustry is a mix-TPS-RTS-TD game where you as ship control everything in battlefield. But due to yourself being limited as instance on the map, you have limited both in reach and view. Yeah, there are undocumented feature called a freecam which is considered as cheating in most games but not this one, so we're not counting on that. And here we got a big UX issue where player can't operate tower defense/real time strategy part cause his own unit is considered as third person shooter part. 

It's like imagine if you can't control units on starcraft/C&C cause your camera is stuck on your core base. 

And no, "but we can" isn't considered as argument due to you already have experience of doing that (like for example, I really didn't know there's freecam on button 4 in vanilla game and used mod for that), but if new player come in it won't be able to easy figure out by it's own.

So my suggestion is to remove player unit from TPS part so player can choose whatever he wants to fights on his ship or not. Or, well, there's is simple way - just remove guns from serpulo core units like in erekir, but isn't that boring?

**Comment by TagGamer555** [comment]
> Too much points for discussion results in every point makes no sence.
> 
> To sum it up - mindustry is a mix-TPS-RTS-TD game where you as ship control everything in battlefield. But due to yourself being limited as instance on the map, you have limited both in reach and view. Yeah, there are undocumented feature called a freecam which is considered as cheating in most games but not this one, so we're not counting on that. And here we got a big UX issue where player can't operate tower defense/real time strategy part cause his own unit is considered as third person shooter part.
> 
> It's like imagine if you can't control units on starcraft/C&C cause your camera is stuck on your core base.
> 
> And no, "but we can" isn't considered as argument due to you already have experience of doing that (like for example, I really didn't know there's freecam on button 4 in vanilla game and used mod for that), but if new player come in it won't be able to easy figure out by it's own.
> 
> So my suggestion is to remove player unit from TPS part so player can choose whatever he wants to fights on his ship or not. Or, well, there's is simple way - just remove guns from serpulo core units like in erekir, but isn't that boring?

Mindustry is not tower defense. Enemies can fight back and not just follow the path set.

**Comment by rekokoro** [comment]
> Mindustry is not tower defense. Enemies can fight back and not just follow the path set.

It was tower defense and that part isn't removed yet. That's why I named it as mix.

**Comment by jehosula** [comment]
> And no, "but we can" isn't considered as argument due to you already have experience of doing that (like for example, I really didn't know there's freecam on button 4 in vanilla game and used mod for that), but if new player come in it won't be able to easy figure out by it's own.

it is an argument like why fix a non-existent problem? just cause new players can't figure it out? just look at the controls or add a tutorial
