### ISSUE TITLE
Unique Faction(s) Idea Thread

### ISSUE THREAD

**Issue by Ferociousfeind** [Anuken/Mindustry-Suggestions#473]
**Describe the content or mechanics you are proposing.**
Bear with me, this is more than likely a huge undertaking which would take months of dedicated time to properly implement code infrastructure for, make in-game content for, and test, but it seems to be largely the direction the game is intended to take after Serpulo takes shape in the campaign. (For those who don't know, campaign maps are saved as `sector-serpulo-###.msav` and heavily implies that the planet not only is named Serpulo, but is not intended to be alone in the campaign.)

As Anuke said on the discord,
`The "teams" in the game right now are only for PvP/attack/custom games, they're not supposed to represent factions or future content`
`Only the 3 named teams in the campaign right now (crux/sharded/derelict) are the only ones that matter on the planet`
`if I do add new factions, they will be using different technology`

This implies that the campaign will not be largely the same sorts of fights between the Sharded (the player) and the Crux (the red team), simply with color swaps from red to blue, or green, or purple. However, that certainly doesn't discount blue or green or purple from making appearances in the campaign in other forms.

I suggest a new "team", one closely related to the occasionally-mentioned "spores" in the v5.0 campaign: _`Frozen Forest- Even here, closer to the mountains, the spores have spread. The frigid temperatures cannot contain them forever.`_

The "spores" would, of course, inherit the purple color straight out of PvP. They'd be called something like the "Spores", or the "Plague", I'm not entirely sure, it's up to discussion. They'd have a generally purple plus white palette, and a collection of buildings that exhibit their naturalistic sources. The most striking differences would be the lack of proper power generation, and the substitution of an organic blood-like fluid created from spore pods, which is used to fuel many complex structures.

- The Plague's walls would perhaps be a copper-lead blend, and a titanium-spore-pod blend to form a more rigid, bony, but fuel-hungry wall with self-healing properties.
- The Plague would have 3x3 cultivator-like structures which produce spore pods slowly but for free, gaining bonuses on mossy(?) ground, and accepting an optional "coolant" of water to double or triple production. I'm unsure on how the mines would function, but I'm sure they'd get the coveted 1x1 mine, along with either a 2x2 or 3x3 mine that requires the fluid spore pod resource to function.
- The Plague would have a couple multi-purpose buildings, one which intakes 4 coal, 5 sand, and 3 lead, (perhaps streamlined due to its multipurpose nature, perhaps 3 coal, 3 sand, 2 lead) along with the spore pod fluid for fuel, and outputs 1 graphite, 1 silicon, 1 metaglass, and 1 pyratite all at once. Adding those buildings together gives a combined production time of 4 seconds (1.5 + 0.67 + 0.5 + 1.33) though I would expect the structure to function more efficiently than one at a time, perhaps 1.5 or 2 seconds. Given the four-in-one deal compared to those four 2x2 structures, I would expect it to be either 3x3 or 4x4 in size.
- I would imagine the Plague's turrets would be the most "energy"-consuming, and perhaps requiring metal-plus-spore-pod "bullets" to function properly (squishy organic stuff can't actually handle lumps of indigestible metal very well).
- The aforementioned blood-like spore-pod-fluid would require energy to actually function, probably in the form of space-efficient solar towers which the Plague has learned to utilize, and reconstruct. It's a simple matter of energizing spore pods and liquefying them to create a nutritious fluid for all your fungal needs. This does mean that it has technically re-evolved photosynthesis to some minor extent, and it also means it won't survive for very long at night without some form of batteries. However, I want to leave that mostly up to discussion.

This thread is also meant as a catalyst for discussion of suggestions relating to new factions featuring new and unique technology and different mechanics to the (relatively) balanced mix of materials and power used by the Crux and the Sharded.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be the roots of a new and unique enemy in some maps, functioning fairly differently from how the Crux works now. I would expect the particulars of the multi-purpose blocks relying almost entirely on one homogeneous fluid to allow for less complex and more modular macro-structures, along with permitting a simple real-time building AI that wouldn't struggle immensely with balancing resource-collection, ammo-production, defense-maintaining, and the like. If a modular structure worked as a frontline defensive block, and also could relay resources forwards to other defensive blocks, then an AI would not have to worry about completely opening up defenses while deleting walls to move them forward, or reconfiguring blocks to be able to pass resources forwards to new defensive blocks, etcetera. 

I'd like to hear additional thoughts, perhaps more concrete stats, actual planning maybe? Dev thoughts? What does Anuke think of this? There is no real precedent for new factions, and both the Sharded and the Crux use the same blocks, so it's hard to tell what other options there may be- what Anuke is considering/would consider for new technologies. A highly-defensive faction with weak but longer-ranged turrets? Some weirdo cultists who summon eldritch entities instead of building drones? Who knows?

(tl;dr lemme know what you think too, let's get some discussion going)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
Honestly I feel like players will be more interested in "playing" as these enemies in PVP than actually fighting against them in campaign.

**Comment by Ferociousfeind** [comment]
Oh, hey, this didn't get immediately shot down. Neato!
I think it's a good sign if the uniqueness of the enemy makes them desirable as a playable faction- not many people want to play as the Crux, because there's nothing attractive outside of the red coloration. I'd love to play as a fungal scourge and expand my organic empire one block at a time, though that's probably just me loving fungi.

**Comment by itcannotbe** [comment]
This is hard as fuck to do, honestly.

The balancing work would be a nightmare.

**Comment by genNAowl** [comment]
> This is hard as fuck to do, honestly.
Agreed. It would be like making multiple mods at the same time.
