### ISSUE TITLE
mindustry indonesia

### ISSUE THREAD

**Issue by deltanedas** [Anuken/Mindustry-Suggestions#4732]
### Describe the content or mechanics you are proposing.

new planet called mindustry indonesia

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

:fire:

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
mindustry indonesia

**Comment by eeve-lyn** [comment]
mindustry indonesia

**Comment by Zerenta** [comment]
mindustry indonesia

**Comment by Anuken** [comment]
who let him in

**Comment by deltanedas** [comment]
you were meant to say mindustry indonesia

**Comment by Anuken** [comment]
no

**Comment by Anuken** [comment]
more like outdonesia

**Comment by Somka000** [comment]
> @Somka000 @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000  @Somka000

You are killer
