### ISSUE TITLE
Make Erekir's graphite count as ore so player can extract sand from walls with it

### ISSUE THREAD

**Issue by KsenofAlike** [Anuken/Mindustry-Suggestions#4734]
### Describe the content or mechanics you are proposing.

If graphite counted as ore there would be more space for map building and more creative ways to play 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There will be more extractable sand , it's a problem with tiny space walls covered in graphite

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TagGamer555** [comment]
This sounds very fair. I was once playing Erekir and needed quick sand so I thought I could crush the graphitic wall but nope.
