### ISSUE TITLE
erekir night 

### ISSUE THREAD

**Issue by mrTree1900** [Anuken/Mindustry-Suggestions#4735]
### Describe the content or mechanics you are proposing.

 I suggest having the dark areas of erekir actually be dark like in Serpulo night not always in daytime and of course this will be separate then fog of war

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Helps to set the visual ambience of the planet

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by zeutd** [comment]
erekir has tidal locked to sun so it doesn't have day-night cycle
and if the sector is in the night area it never be lighted, it will be annoying

**Comment by Mythril382** [comment]
Basically, this game isn't made to be realistic.

**Comment by TagGamer555** [comment]
this is also in the trello board so this is just a duplicate of what is actually planned

**Comment by Lolnoizcool** [comment]
lolno
Erekir is tidally locked, so it doesn't need a day and night cycle.

**Comment by mrTree1900** [comment]
> lolno Erekir is tidally locked, so it doesn't need a day and night cycle.

Learn how to read
