### ISSUE TITLE
Changing the balance of a large solar panel

### ISSUE THREAD

**Issue by SaloKramsalo** [Anuken/Mindustry-Suggestions#4736]
### Describe the content or mechanics you are proposing.

**I would like to change the amount of energy generated by a large solar panel, because I think that its creation is too expensive for the stage at which it can be crafted.** 

A solar panel generates 6 units of power per second, and a large solar panel generates 78 units of power per second, that is, 13 solar panels are required to generate the same amount of energy as a large one. To create one solar panel requires 10 units of lead and 15 units of silicon, that is, to create 13 solar panels requires 130 units of lead and 195 units of silicon. To create one large solar panel, 80 units of lead, 110 units of silicon and 15 units of phase fabric (60 units of thorium and 150 units of sand) are required. The difference between creating 13 solar panels and one large solar panel is 50 units of lead and 85 units of silicon, but I still think this is not a profitable crafting, since at the stage when you can create a phase fabric, it will be more profitable for you to spend lead and silicon instead of thorium and sand. 

The area of one large solar panel is 9 blocks. The difference between the areas of 13 solar panels and one large one is 4 blocks, but since the panels are small, it is easier for them to take up free space on the map than with large solar panels.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Increasing the amount of power produced by a large solar panel will force players to use them more often than before.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
maybe by 2 power/s and buff the phase cost

**Comment by S0meM** [comment]
This should probably be labeled as balancing/feedback rather than feature request.
