### ISSUE TITLE
Change for the new derelict rebuild feature

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry-Suggestions#4737]
### Describe what you would like changed, and why.

I would like it to become a map rule

So i purpose this as some map makers (myself) have made it so certain blocks can only be placed in certain areas around and they also use the deconstruction % of derelict blocks to balance a map.
(the blocks are not banned, it just gets set to derelict, as its too much effort to list every block in the entire game to refund its item cost)

The blocks get set to derelict so they can be deconstructed and provide their rss, while also not being able to function. Setting it to disabled is not a solution as the logic cant keep up with mass builds, being able to just reconstruct the block would defeat the purpose of setting it to derelict

### Describe the changes you want to propose. Include possible alternatives.

Make it a map rule toggle, and off by default (except in campaign)

**Comment by camelStyleUser** [comment]
cant they just deconstruct and reconstruct your block anyway

**Comment by JasonP01** [comment]
> cant they just deconstruct and reconstruct your block anyway

The point is to allow them to delete it, the logic would just set it back to derelict if they try to place it again

**Comment by jehosula** [comment]
> The point is to allow them to delete it, the logic would just set it back to derelict if they try to place it again

add derelict blocks from the editor? idk what the problem is

**Comment by JasonP01** [comment]
> add derelict blocks from the editor? idk what the problem is

If you dont know what the problem is, then dont comment?? Its not hard to not comment on something you dont understand

**Comment by JasonP01** [comment]
Implemented by anuke

**Comment by jehosula** [comment]
> If you dont know what the problem is, then dont comment?? Its not hard to not comment on something you dont understand

I just don't understand why that's a problem explain better
