### ISSUE TITLE
Flag negation in schematics library

### ISSUE THREAD

**Issue by suhedge** [Anuken/Mindustry-Suggestions#4738]
### Describe the content or mechanics you are proposing.

Right now, in schematics library (Main_menu->Database->Schematics) you can left click on flag at the top to show all Schematics with that flag.
I suggest, when you right click on flag Schematics that are **_not_** having that flag will be shown.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Usage of big schematic library would become alot less annoying.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
great little idea
