### ISSUE TITLE
Collapsible Core resource display

### ISSUE THREAD

**Issue by S0meM** [Anuken/Mindustry-Suggestions#4739]
### Describe the content or mechanics you are proposing.

I have a 3 mods that add resources, so my core resource display takes up more than half the height of the screen.
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/148879621/4ce6a4d1-e69c-4a31-9f81-21f72cac5443)
This makes it difficult to place items or to drop items from my ship. It would be nice to be able to collapse that instead of having to toggle the menu with C.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would improve the game when you have multiple mods.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
just disable it

**Comment by S0meM** [comment]
Oh. I didn't realize that that was there. Thanks. I looked through the settings to make sure, but I guess I missed it.
