### ISSUE TITLE
New Unit : Upgrader

### ISSUE THREAD

**Issue by IProgramForFun** [Anuken/Mindustry-Suggestions#474]
**Describe the content or mechanics you are proposing.**

The new unit could be used to upgrade certain blocks, i.e. replace conveyors with titanium conveyors, replace mechanical drills with pneumatic drills etc

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It may be a mid to late game feature which eliminates the repetitive task of flying around the map replacing everything manually.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
That unit would get useless quite easily.

**Comment by IProgramForFun** [comment]
It's not meant to be useful for a long time, you just build it, upgrade everything and then get rid of it again

**Comment by Anuken** [comment]
This doesn't need to be a separate unit. It could be possible with unit control logic.
