### ISSUE TITLE
Access to camera coordinates

### ISSUE THREAD

**Issue by Optimal-performer-38** [Anuken/Mindustry-Suggestions#4740]
### Describe the content or mechanics you are proposing.

UI element support. Well not really UI support, just the camera coordinates that is relative to the map so that one may use the effects function to draw a makeshift button that stays within frame regardless of player position/movement.
 Also, unanimated effects that can be scaled and colored despite bloom 🥺

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You can make a simple touchpad out of it using atan.
Also, you can draw buttons as placeholders for logic player abilities. Static effects will help spriting. 
Camera pan/zoom that doesn't remove player control will also do the job since you can place the buttons relative to player position and have the camera stay at you at all times.
Idk. Maybe im asking for too much
https://www.reddit.com/r/Mindustry/comments/17fo8ly/melee_fighter_atrax_logic/

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by eeve-lyn** [comment]
this... already exists

**Comment by eeve-lyn** [comment]
in fact, we have a much better way of doing ui with markers.

**Comment by eeve-lyn** [comment]
check [this](https://github.com/Anuken/Mindustry/pull/9103) out

**Comment by Optimal-performer-38** [comment]
> check [this](https://github.com/Anuken/Mindustry/pull/9103) out

Nice

**Comment by SkyeTheFoxyFox** [comment]
This is already in the code (alongside markers), it will come in the next update

**Comment by S0meM** [comment]
Plus, there's a setting for mouse coordinates already. That should already fill the function. It works for me.

**Comment by Optimal-performer-38** [comment]
Nice 🔥

**Comment by Optimal-performer-38** [comment]
> Plus, there's a setting for mouse coordinates already. That should already fill the function. It works for me.

**Comment by Optimal-performer-38** [comment]
> Plus, there's a setting for mouse coordinates already. That should already fill the function. It works for me.

Thanks for the tip. It works for me too↓
Looking forward to markers. Perhaps they have a way to differ swipes or drag from touch events.

https://drive.google.com/file/d/1XQlGGfV9Ejf21izpKlF-m-f4BGxWEs3n/view?usp=sharing

(Hmmm. How do i reply without reopening this issue)
