### ISSUE TITLE
Control units in multiplayer

### ISSUE THREAD

**Issue by S0meM** [Anuken/Mindustry-Suggestions#4741]
### Describe the content or mechanics you are proposing.

In single player, you can control units anywhere by pausing and panning. In multiplayer, that can be a little harder, especially when you don't have enough health to reach the area where your units are at. I propose making it so that in multiplayer, when you hit the space bar, it locks your unit into place and lets you pan to control units or place down blocks. It would work just like in single player, except it doesn't stop anything.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make controlling units easier in multiplayer.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
this is more like suggesting pan which is already in the game(check controls)

**Comment by S0meM** [comment]
Oh. That makes me feel stupid.
