### ISSUE TITLE
Overflow/underflow gates for pipes

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry-Suggestions#4743]
### Describe the content or mechanics you are proposing.

Add an overflow/underflow gate for pipes

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

pipes don't have any ways to dictate where you want liquid unless you manually cut them and all that

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by overdramaticpanromantic** [comment]
I don't think those are possible.

**Comment by S0meM** [comment]
With the way that fluids work, these just don't make sense. With how overflow and underflow gates work, if there's any extra liquid, it will allow it along the other paths. But with pipes, there's always some fluid lagging behind. That fluid will open the other paths, making these items act as routers, unless the prioritized path (in front for overflow and on the sides for underflow) is completely empty.

**Comment by S0meM** [comment]
If you really need this for some reason tho, the best way to do it would probably be logic. Does all this make sense?
