### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by kerharhun45** [Anuken/Mindustry-Suggestions#4746]
### Describe what you would like changed, and why.

The hungarian thranslation of mindustry is not complete. (In the description of something in erekir.

### Describe the changes you want to propose. Include possible alternatives.

Complete the hungarian translation, i can help with it.

**Comment by camelStyleUser** [comment]
so help with it

**Comment by camelStyleUser** [comment]
if you can

**Comment by kerharhun45** [comment]
How can I forward the translations? Is it okay if I send it like this message?
