### ISSUE TITLE
ANUKE! I beg of you, PLEASE MAKE A PATREON

### ISSUE THREAD

**Issue by CallMeSirEntertainmentYT** [Anuken/Mindustry-Suggestions#4749]
### Describe what you would like changed, and why.

I would really like you to make a Patreon because I would like to directly support you (and the game).

### Describe the changes you want to propose. Include possible alternatives.

Make a Patreon, Kickstarter, just anything I can use to donate to you.

**Comment by camelStyleUser** [comment]
itch.io donation thing:

**Comment by CallMeSirEntertainmentYT** [comment]
Yes, I do know that there is an Itch.io donation button, but I would like a way to **continuously** and **automatically** donate to Anuken

**Comment by eeve-lyn** [comment]
buy the game on steam every month and gift it to your friends

**Comment by CallMeSirEntertainmentYT** [comment]
I want to donate for nothing in return. Also my friends just get it for free on Itch.io

**Comment by inflexibledark** [comment]
But what about OnlyFans? 👀
