### ISSUE TITLE
Logical appearance of enemies in survival mode

### ISSUE THREAD

**Issue by Dimonchok** [Anuken/Mindustry-Suggestions#4754]
### Describe the content or mechanics you are proposing.

So that the player does not ask the question “Where do the enemies come from?” you can make them arrive on something similar to capsules that fall during the start of the wave

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This won't add any features, but it will make the game more logical

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by eeve-lyn** [comment]
you should ask better questions like who are you playing as and why is the red tesm fighting you

**Comment by Ruichka** [comment]
https://trello.com/c/bqKwLdqU/899-enemy-wave-dropship
