### ISSUE TITLE
L'automatisation d'Erekir

### ISSUE THREAD

**Issue by Plojoaze** [Anuken/Mindustry-Suggestions#4757]
### Describe the content or mechanics you are proposing.

Bonjour,
Je suis français est motivé par votre jeux et sa communauté incroyable mais je suis surtout la pour vous demander si vous pouvez dans de nouvelles mise a jour(s) améliorer l'automatisation d'Erekir. Un peut plus tard dans le jeux j'espère que Erekir sera plus autonome.

Merci de votre lecture.
Signé: plojoaze

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Un extracteur a petrole ou future ment a matière organique pour accélérer l'industrie de graphique
Et de nouvelle unité (Erekir) comme les unités aerienne qui nous aident a construire.
(Désolé je ne me souvient pas des nom de ces unités).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by S0meM** [comment]
For everyone who can't read French, they are suggesting adding an oil extractor to accelerate the graphite industry.(?? We already have an oil extractor, and we don't use oil on Erekir), and a new unit in Erekir that will help you build like the Polys do. I agree with the Poly-like Erekir unit.

**Comment by Plojoaze** [comment]
Daccord pour le pétrole sur Erekir.
Oui se serait bien que vous ajoutiez
Une unité type poly sur Erekir

Merci d'avoir lue
Plojoaze

**Comment by S0meM** [comment]
Pourquoi as-tu besoin du pétrole sur Erekir? Il n'y a rien qui l'utilise dans la jeu sur Erekir, sauf si tu as un mod. Utilises-tu des mods?

**Comment by S0meM** [comment]
Et aussi, si tu utilises des mods, lesquels?

**Comment by Plojoaze** [comment]
Non je n'utilise pas de mod (que sur Erekir)je joue comme sa mais ci il n'y
a pas de petrole sur Erekir on pourrait utiliser une matière
organique(arkirite/néoplasme).

**Comment by Plojoaze** [comment]
J'utilise exogenesis sur serpulo

**Comment by S0meM** [comment]
So, Plojoaze wants a way to synthesize graphite on Erekir. They did not realize that there isn't oil on Erekir and said that we should be able to use arkycite or neoplasm in a building to make graphite.

**Comment by Plojoaze** [comment]
Comme une nouvelle technique pour recycler le néoplasme.
