### ISSUE TITLE
Contain the ZIP file inside a folder

### ISSUE THREAD

**Issue by tukkek** [Anuken/Mindustry-Suggestions#476]
It's custom to place the game files inside a folder in your ZIP file so as to not just drop the files flat under a directory where they may get mingled with possible per-existing, unrelated files. This is obviously only a small problem as the player can create a new folder himself but it's equally easy to solve (and automate), so I thought I might bring it up.

More precisely: the `mindustry-linux-64-bit.zip` file has 3 directories on its root. Rather than having `/config.json` as the extraction path, you'd want it to be `/mindustry/config.json` (same with all other included files and directories).

**Comment by DeltaNedas** [comment]
extract > auto detect subfolder in dolphin

**Comment by tukkek** [comment]
Yes, I know how to operate a file manager, thank you. I am saying what is customary for the large majority of open source projects.
