### ISSUE TITLE
Ideas for logics.

### ISSUE THREAD

**Issue by RomanDonw** [Anuken/Mindustry-Suggestions#4761]
### Describe the content or mechanics you are proposing.

Hello! I have ideas about the logic, they will be listed below:

* Switch between text and graphic editing.
* Loading code for the processor from an external file.
* Code comments. * Tags and the ability to specify them in "jump".
* Functions for changing strings (splitting, replacing a character, searching for characters, etc.).
* Conditional constructions (with multiple choice).
* Loops (while, for, foreach, etc.).
* Ability to create your own functions.
* The main functions are setup (called once before loop) and loop (main loop).
* New block - input field.
* Display text on the screen.

Perhaps some ideas will seem difficult to you and you will not want to implement them, but I believe in you, and I believe that these ideas will appear in the game in the near future.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

These ideas will simplify the development of programs for processors, as well as expand the scope of creativity!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RomanDonw** [comment]
And arrays too.

**Comment by itcannotbe** [comment]
Why not suggest also suggest any sort of string manipulation in logic (reading from message blocks, reading characters, splitting strings, etc)? ~sarcasm~

**Comment by ApsZoldat** [comment]
> Functions for changing strings (splitting, replacing a character, searching for characters, etc.).
https://github.com/Anuken/Mindustry-Suggestions#a-few-things-you-shouldnt-suggest

> Code comments. * Tags and the ability to specify them in "jump".
https://github.com/Anuken/Mindustry/blob/f0963ef302ed2de48b126dcf2ccb0fb9bd0994ab/core/src/mindustry/logic/LStatements.java#L29

**Comment by S0meM** [comment]
Also, just copy the file to your clipboard. (Ctrl + C)
And while loops can easily be replicated exactly with the jumps.
Ability to create your own functions has already been mentioned.
[https://github.com/Anuken/Mindustry-Suggestions/issues/4586](https://github.com/Anuken/Mindustry-Suggestions/issues/4586)

**Comment by camelStyleUser** [comment]
you can use functions with the power of `@counter` actually

**Comment by Varxalaxiacis** [comment]
For text and graphic we have a ton of options we already have a lot of available compiler like js to mlog but we don't really need it since u can use a notepad or something.just my honest review.

**Comment by Varxalaxiacis** [comment]
Also for the more conditions it doesn't fit the mlog,mlog was supposed to be 1 line for 1 instructions we already have the limit of 1000 line but that is easily fixed by chaining proc using a mem cells.

Too be honest allmost all the thing this point out was almost all ready done using mlog it is nice to have this but a few are not possible due to rules of suggest.

**Comment by RomanDonw** [comment]
Sad, I'm wondering if any of what I suggested will be added?

**Comment by S0meM** [comment]
> * New block - input field.

Also, for an input field, if you just want it to input an item or something, then just use a sorter and read @ config. Tho that idea might need a little more explanation.
