### ISSUE TITLE
Remove "Generator" From RTG Generator

### ISSUE THREAD

**Issue by CallMeSirEntertainmentYT** [Anuken/Mindustry-Suggestions#4763]
### Describe what you would like changed, and why.

RTG stands for Radioisotope Thermoelectric Generator, so that means that in the game, it should not have "generator" after RTG. This is because the "G" stands for generator.

### Describe the changes you want to propose. Include possible alternatives.

Just change the name from "RTG Generator" to "RTG"

**Comment by CarsonBurke** [comment]
Or change it to "RT Generator?"

**Comment by YSMQTHLQYH** [comment]
Yall ever heard of Detective Comics Comics? 
Sure RTG generator is redundant and logically makes no sense. But in a more, spiritual, way it makes sense the current way. 
Having a block called just "RTG" feels _off_. However calling it "RT Generator" or the full "Radioisotope Thermoelectric Generator" are more reasonable while also being logical, not a fan of either but still.

**Comment by SomeonesShade** [comment]
[RAS Syndrome moment?](https://en.m.wikipedia.org/wiki/RAS_syndrome)
