### ISSUE TITLE
Bug? Maybe

### ISSUE THREAD

**Issue by mohsin1248** [Anuken/Mindustry-Suggestions#4764]
### Describe what you would like changed, and why.

I don't know what's the problem but I am a vivo mobile player. Whenever I play mundustry from my own net, that is the mobile network, I cannot play consistently on some servers like the Darkdustry server and my server list is also empty. But when I connect to any other Wifi, whether from a wifi or router, the servers show up and I can play on Darkdustry again. Even tho my net is better than the wifi i am kicked out of the game after a few seconds.
My ping is good and all but for some reason I keep getting kicked out.

### Describe the changes you want to propose. Include possible alternatives.

Also, the multiplayer interface needa improvement because you don't know when the game is searching for servers.

**Comment by GlennFolker** [comment]
Shouldn't this go to [the main repository](https://github.com/Anuken/Mindustry) instead?

**Comment by S0meM** [comment]
Ik how to fix it on Windows.

**Comment by S0meM** [comment]
If this is on Windows, you have to go to Control Panel\System and Security\Windows Defender Firewall, then click on the button that says "Allow an app or feature through Windows Defender Firewall"
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/148879621/9f4e2262-a4e6-46d7-9e1e-16096887ab7a)
Scroll down to Mindustry and allow it through both public and private firewalls. By your description, other internets are public, and so it will let it through, but your net is private so it won't let it through.
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/148879621/30507c02-0dde-4305-ab47-a03af91c46fb)

**Comment by S0meM** [comment]
Tho if it's on a phone or something, idk how to fix it, or even if it's the same problem.
