### ISSUE TITLE
Submarines and AntiSubmarine Turrets.

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry-Suggestions#477]
A Submarine unit can go under the water so normal turrets can't shoot at the Submarine.

A new Naval Factory unit with low hp, low damage and medium range but also it can shoot fire. And a expansive AntiSubmarine turrets, AntiSubmarine turret only able to shoot at the Submarines, AntiSubmarine turret have medium HP, low Damage (but enough the kill submarine in 2 shoots) and very high range.

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
Anuke has mentioned that he won't be adding "Underground map layers", and this submerging ability might count into that category. Still, nice idea though.

**Comment by Anuken** [comment]
I've seen this in other games and it's been suggested before, but I don't see much of a niche for it at the moment. It remains to see how much *normal* naval units will be used.

**Comment by RogueRedHawk** [comment]
To go along with what Anuke said, current naval units aren't very useful because of two reason: 1. most maps are mostly ground, with a few lakes or rivers and almost never oceans, and 2. there are no structures which sit on the water (besides pumps, and those sit at the edge). If either of these things were changed, those changes being to add island maps or to make buildings that can be built on water, this could be a great idea in my opinion, but as it stands it's even more useless than the already implemented naval units.

**Comment by itcannotbe** [comment]
Actually blame the map makes for that.

**Comment by darmaangelo** [comment]
> Anuke has mentioned that he won't be adding "Underground map layers", and this submerging ability might count into that category. Still, nice idea though.

just make submarine invisible just like submarine in red alert

**Comment by darmaangelo** [comment]
> To go along with what Anuke said, current naval units aren't very useful because of two reason: 1. most maps are mostly ground, with a few lakes or rivers and almost never oceans, and 2. there are no structures which sit on the water (besides pumps, and those sit at the edge). If either of these things were changed, those changes being to add island maps or to make buildings that can be built on water, this could be a great idea in my opinion, but as it stands it's even more useless than the already implemented naval units.

i wish anuke add oil ressevoire just like warcraft 2 and that make mindustry expanded in naval experience
