### ISSUE TITLE
Controller

### ISSUE THREAD

**Issue by DIDxONE** [Anuken/Mindustry-Suggestions#4771]
### Describe what you would like changed, and why.

I want them to add a “controller”, for example, so that the plant fires a specified number of times. Of course, I know that this can be done through a processor, but who needs this brand in logic? and I offer this microsorry stand, but perhaps it will be useful in schemes and overnight stays.

### Describe the changes you want to propose. Include possible alternatives.

It will be possible to set “on” “off” "operation interval" “number of operations [number]” and additional parameters for coding in the controller.

The controller can be connected to buildings within a certain radius. For example, someone has a metropolis with launchers and the player must constantly monitor whether the electricity is connected or not so that resources do not fly away to nowhere.

with the controller you can simply connect it to launchers and they will no longer waste resources but accumulate them and fire a certain number of times after going into sleep mode.

**Alternative:** Ignore the unknown user's request since the processor exists

**Comment by BlueWolf3682** [comment]
poor translator

**Comment by jehosula** [comment]
do the alternative
