### ISSUE TITLE
The ability to use copy-paste or blueprints to change the setting of tiles with settings like sorters, unloaders etc.

### ISSUE THREAD

**Issue by Tamren** [Anuken/Mindustry-Suggestions#4774]
### Describe the content or mechanics you are proposing.

Sorters, inverted sorters, unloaders and item sources in sandbox mode can all be set to a specific material or entity. Currently if you want to do something like replace a coal sorter with a copper sorter, your only options are to delete the sorter and copy-place the new one onto the same location, or manually set the coal sorter to copper by opening the sub menu. The game will not allow you to place one over the other, the location will be blocked and marked red the same as impassible terrain.

What I'm asking for is the ability to replace one sorter with another set to a different material as an in-place swap. This would be similar to how we can click on belts with the same type of belt in hand to change the direction of the belt.

If that would be too complicated for some reason, then you could give us the ability to place tiles over tiles of the same type as long as the sort settings are different. This would be no different to placing blue belt over grey belt, or over some unloaders, the old entity is removed and you construct the new one in its place.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be a QoL change that saves us a lot of time. Swapping large numbers of sorted entities could be done by setting one to the correct material and using F or MMB to copy it over the others, without having to deconstruct them first. Either individually or by dragging the mouse to place a line. Unloaders in particular are slow to build and expensive, so being able to mass-change the setting on each unloader without rebuilding or configuring them individually would be great. This ability would also extend to blueprints.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by S0meM** [comment]
> If that would be too complicated for some reason, then you could give us the ability to place tiles over tiles of the same type as long as the sort settings are different. This would be no different to placing blue belt over grey belt, or over some unloaders, the old entity is removed and you construct the new one in its place.
I think that you should just ignore whether or not it has the same sort settings. It really wouldn't make an impact.

Also, this isn't entirely related, but you should make it so that if you can replace it when it's built, you can replace it while it's  still a ghost entity or whatever it's called. In Erekir, it's frequently annoying to have to deconstruct the ghost entity pipes so that I can place down a liquid tank.
