### ISSUE TITLE
Fitur login

### ISSUE THREAD

**Issue by Groooog** [Anuken/Mindustry-Suggestions#4776]
### Describe the content or mechanics you are proposing.

Tolong tambahkan fitur login karena saya malas ulang dari awal kalo bisa sekalian tambahkan planet baru atau musuh, unit, turret, dan sumber daya baru

Please add a login feature because I'm too lazy to start over from the beginning. If possible, add new planets or enemies, units, turrets and new resources.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Tidak tau
Don't know

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
### A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Built-in cloud sync

**Comment by 9bbbl** [comment]
If so, what about the performance features? for example: mastering sorpulo, mastering erekir, killing 1000 enemies, and so on

kalau itu bagaimana dengan fitur prestasi

contohnya: menguasai sorpulo, menguasai erekir, membunuh 1000 musuh, dan sebagainya

Cttn: saya tidak memaksa ya!

**Comment by 9bbbl** [comment]
?

**Comment by Groooog** [comment]
If so, what about the performance features? for example: mastering sorpulo,
mastering erekir, killing 1000 enemies, and so on


kalau itu bagaimana dengan fitur prestasi

contohnya: menguasai sorpulo, menguasai erekir, membunuh 1000 musuh, dan
sebagainya


Saya Tidak memaksa ya!

Pada Jum, 17 Nov 2023 17.24, Kenny-Ofc ***@***.***> menulis:

**Comment by Kenny-Ofc** [comment]
performance features?? well, Buy the game on steam, so you'll get achievement. 
(kalau mau prestasi udah ada, khusus di steam)
