### ISSUE TITLE
make a second area to private network hosting (vpn(wireguard)) inside the server list 

### ISSUE THREAD

**Issue by SpilLinux** [Anuken/Mindustry-Suggestions#4778]
### Describe the content or mechanics you are proposing.

to prevent problem or to secur a network, why not create a second area inside the server list with : 

-peer 
- ip adress
- public key 
- port

the objectif is to delete problem with bot and vpn like the darkdustry story :cry

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the objective would be with the wireguard protocol to prevent censorship in certain countries, to hide everyone's identity for security, to prevent bots, to create a secure network preventing the risk of piracy, to be able to each create a server accessible via an IP and not to fear the risks...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
how would a P2P system with key pairs prevent bots anyway?bots dont care about secure keys so they can reuse some of the primes and randomness to make generating new pubkeys faster

**Comment by SpilLinux** [comment]
to be able to access the server you must have access to a key, you would just need to create an individual key system and confirmation via discord for example or any other means of verification to prevent anyone from joining the server too easily

**Comment by Volas171** [comment]
> the wireguard system is made to be very easy to use and very secure, even the creator of the server does not even know the ip addresses of its users

wireguard works as a man in the middle, it is secure, thats not a doubt, the problem is, this all falls back to a "login system" or "verification system" and honestly, i don't really remember any suggestion about any of those being added. (it would require cloud infrastructure in some way or another)

**Comment by SpilLinux** [comment]
The wireguard network can just secure the network, to be safe we need to found who is not a bot

We can create a protocol to promote the players and delete the bots :

every client has a perssonnal key
For the first time, News client can just play on a level of security one, after they play 2 hours inside his server, they can acces to the 2 level server, inside the second level they are impossible for bots to go inside because they need the acces 2

**Comment by camelStyleUser** [comment]
> The wireguard network can just secure the network, to be safe we need to found who is not a bot
> 
> We can create a protocol to promote the players and delete the bots :
> 
> every client has a perssonnal key For the first time, News client can just play on a level of security one, after they play 2 hours inside his server, they can acces to the 2 level server, inside the second level they are impossible for bots to go inside because they need the acces 2
> 
> it’s impossible because to acces at the level security 2 they need to play a long time (and bots can’t play mindustry, we just need to Add an anti-afk inside the level of security one to delete bots)

when the bots move

**Comment by SpilLinux** [comment]
It was an exemple you can add a lot of rules with the first server, you are not limited

**Comment by camelStyleUser** [comment]
> It was an exemple you can add a lot of rules with the first server, you are not limited

lot of rules such as

**Comment by camelStyleUser** [comment]
if you put a captcha attacker can use that captcha solving service to break your captcha

**Comment by SpilLinux** [comment]
you can add rule inside the first server to prevent bot exemple :

-who is afk more 5 minute is kick 
-who didn't build or destroy is kick
-who always do similar movement is kick
-who disconnected instant is ban

**Comment by camelStyleUser** [comment]
> you can add rule inside the first server to prevent bot exemple :
> 
> -who is afk more 5 minute is kick -who didn't build or destroy is kick -who always do similar movement is kick -who disconnected instant is ban

random direction of movement
place random base schematics anywhere(only the ones you can place with your resources)
