### ISSUE TITLE
one instance per IP

### ISSUE THREAD

**Issue by NexulaDev** [Anuken/Mindustry-Suggestions#4779]
### Describe the content or mechanics you are proposing.

servers getting botted every single day and i traced them on my server and they are the same ip every time all of the accounts so you should just limit 1 account per ip

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

they cannot bot anymore

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Ah yes, ISP who use IPv4 with CGNAT who can't be bothered to change to IPv6 do not totally exist...

Also as if Tunneling to IPv6 via free services don't exist...

**Comment by TheEt1234** [comment]
just download one of the MANY MANY antibot plugins

**Comment by Anuken** [comment]
I already tried this; legitimate users immediately ran into issues (i.e. with CGNATs) and it was removed within hours after the release. If it were that easy, I would have done so long ago.

This is trivial to implement with a plugin, anyway.

**Comment by Leo-MathGuy** [comment]
There is a plugin for that, it limits to 5/ip: [ohiodustry](https://github.com/Omega-Network/ohiodustry)
