### ISSUE TITLE
RTG Rework/Buff

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#4788]
### Describe what you would like changed, and why.

RTG Generators have been pretty underused because of being outclassed in almost every category inside its tier (phase/surge tier, look at impact for ex), and even comparing to its lower tier (thor-reactor). It isn't the best power-duration per thor effeciency, (rtg: 3780 vs reactor: 5400). It isn't cost effective for what's it worth (the 75 plast and 25 phase inside its cost is expensive for only 270 power), and it is in a later tier in the gameplay progression yet worse than its lower tiered counterpart (phase tech vs thor tech)

Overall, as discussed in #balancing, RTG should be the following:
1. Change its tech tier to move more into the mid game (phase -> thor/reactor tier)
2. A thorium inefficient sink (more thorium needed for the same power)
3. An easy to set up, cheap, and spammable power generator (to contrast its new rival in the new tech tier)
4. Maintain the high duration as it's description says

### Describe the changes you want to propose. Include possible alternatives.

Here are the aspects being changed:
Power 270 -> 180
Since Duration is unmodifiable on becoming lower, the only way to decrease the thor effeciency is to decrease the power output
It should be this much to have roughly half or lower than thor reactor (3780 -> 2520)
You would 2x as much thor input to have the same rough power generation as thor reactor

Cost
Lead 100 -> 60
Need to adjust accordingly, it needs to be decreased to match the power/lead for both options (3 power/lead)

Silicon 75 -> 25
RTG should be a cheaper option, this is better than the power/silicon of thor reactor (7.2 vs 4.5)

Phase 25 -> 0 <Removed>
The big one, changing the tech tier from phase to thor/reactor in order to make it easy to set up.

Thorium 50 -> 75
RTG should be more of a thorium sink, so this is the only thing that goes up, but not too much to be lethally expensive.
Also moving some of the thor cost from phase into thor at least.

Plastanium 75 -> 5.
This is absurdly large for what it does, although being kept in order to keep its unique item profile against thor reactor, allowing to decrease the rest of the stats safely without outclassing the thor reactor since it doesn't consume cyro and doesn't explode.

Comparison Pictures
23 180pu RTG 
Thor Input: 1.64... i/s
![Capture1](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/289e4d97-1f30-41c5-8860-6511dceee83e)

5 900pu Thor Reactor
Thor Input: 0.83... i/s
Titanium Input: 0.5 i/s
![Capture2](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/ee0ebe6a-cbd2-481e-99e5-53dbe7e1299e)

**Comment by SomeonesShade** [comment]
As an appendix suggestion:
Due to the nature of power rebalancing, it can affect maps heavily that uses said blocks completely.

For future power balancing (looking at erekir's flux, and the high power diffrence from pre-arky, and post arky), maybe a team specifc game rule that multiplies all power gen?

**Comment by SpilLinux** [comment]
The rtg generator is used when you need a bit energy and when you don't have place and combustion material, i think we don't need to change it

**Comment by perelllaquairusbrown** [comment]
i think the slow, its small size and how good it is when overdomed justifies the cost

**Comment by rekokoro** [comment]
This is sound like unbalanced shit ©

Well if speaking seriously, we alredy have stuff that fills the gap between thorium reactors and steam generators which is called differential generator and which is always neglected cause of costs and space to set it up. As now I see RTG as "costly but constant" power source which won't explode like thorium or suddenly drop down as impact reactor.

And for those who talking about breaking maps - one day you've changed oil extractor mechanic making it depends on floor. And nope, nobody did care about it breaking the maps.

**Comment by SomeonesShade** [comment]
For the two first comments

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/2a29e062-b7fb-4fee-ab50-195d65d8e290)

This is unbelievably expensive for what it does
You can probably make a t4, or upgrade a t4 to t5 (with some surge and cyro) with the resources, allowing one to win the game, and use cheaper power instead

Next, it may have slow consumption (hence the high 14 duration), but it eats more thorium than thorium reactors when one upscales their power
(for 1 i/s of thor, with thor reactor you get 5400 power minus the external energy costs (maybe 200-500, depends if you run water-ex), vs rtg with 3780 only)
In the end, you are consuming more thorium if you run rtg

overdrive/overdome has both similar effects on the two, if rtg with overdome is great, so does thor reactor, or any other power source also does

**Comment by SomeonesShade** [comment]
> This is sound like unbalanced shit ©
> 
> 
> 
> Well if speaking seriously, we alredy have stuff that fills the gap between thorium reactors and steam generators which is called differential generator and which is always neglected cause of costs and space to set it up. As now I see RTG as "costly but constant" power source which won't explode like thorium or suddenly drop down as impact reactor.
> 
> 
> 
> And for those who talking about breaking maps - one day you've changed oil extractor mechanic making it depends on floor. And nope, nobody did care about it breaking the maps. 

I mean fair, I can see where you are getting at with rtg replacing the niche of diff generator, but thats not the intention
It should be something that is done while thor reactors are being built, and if you have the space and thor production to feed it.
I can adjust the stats to fit that goal.

For the safety argument for rtg, its not good enough to justify the absurd cost rtg gives, especially at its current tier

If you were transitioning from diff gen, you would usually get thor reactor, but when you get phase and plast, would you even ever do rtg?, when you could just make units with the cost and win the game in attack/pvp, or into more defensive in survival?

I mean I'm fine if you think this looks very unbalanced, hence I've posted this suggestion so I can adjust the costs, changes, if given a good argument 

For the appendix, its just something that an alievate changes at least, since map makers are transitioning from source item into ore with tight power may get affected here (well i think they are transitioning anyway), its fine if you think that way because its just an appendix/not the main focus

**Comment by itcannotbe** [comment]
The problem here is that since RTG will become easier to construct, beside plastanium, you basically removed the use case for thorium reactors.

Who would even want an exploding power plant anyways?

**Comment by SomeonesShade** [comment]
> The problem here is that since RTG will become easier to construct, beside plastanium, you basically removed the use case for thorium reactors.
> 
> 
> 
> Who would even want an exploding power plant anyways?

fair, the intended draw back is that it would consume more thorium (similar to combustion gen)
By basically requiring to feed it like a lot of thorium and space (input and space inefficiency)

I guess i need to nerf the power even more (since 2x consumption vs thor reac isn't enough), and maybe i might be able to get away with a 12-11 duration, if the power gen gets too low, that it makes the plast cost too painful

**Comment by SomeonesShade** [comment]
> The problem here is that since RTG will become easier to construct, beside plastanium, you basically removed the use case for thorium reactors.
> 
> 
> 
> Who would even want an exploding power plant anyways?

fair, the intended draw back is that it would consume more thorium (similar to combustion gen)
By basically requiring to feed it like a lot of thorium and space (input and space inefficiency)

I guess i need to nerf the power even more (since 2x consumption vs thor reac isn't enough), and maybe i might be able to get away with a 12-11 duration, if the power gen gets too low, that it makes the plast cost too painful

**Comment by Sector171** [comment]
I no longer play Serpulo any more, but RTG was the best power source. 
Impacts and reactors have their own problems. The only problem RTG has is it is expensive, but it is the most reliable power source, so easy to set up, so easy to stack when needed.
It was my favorite power source, the moment i have enough of needed resources to build, after that no more power issue just spam more RTGS when needed.

**Comment by Ilya246** [comment]
> The problem here is that since RTG will become easier to construct, beside plastanium, you basically removed the use case for thorium reactors.
> 
> Who would even want an exploding power plant anyways?

RTGs would still take a large amount of thorium and eat up your space
if you want a 100% reliable power source, use solar panels

**Comment by itcannotbe** [comment]
> RTGs would still take a large amount of thorium and eat up your space
> if you want a 100% reliable power source, use solar panels

Space matters? (Well apparent for decent pvp matches or maybe speed runs). Normal people won't give a second thought on using something less efficient. As long they can build it.

**Comment by egfthomas** [comment]
> > The problem here is that since RTG will become easier to construct, beside plastanium, you basically removed the use case for thorium reactors.
> > Who would even want an exploding power plant anyways?
> 
> RTGs would still take a large amount of thorium and eat up your space if you want a 100% reliable power source, use solar panels

Except they don't work at night :)

**Comment by Catoverflow** [comment]
No.

I usually use RTG immediately when launched to a new sector, because it can run on thorium extracted from the core and give steady power with tiny thorium consumption. Another case is in late game, if I want massive power I just overdrive a lot of RTGs. Because it's simple and can be built compact around the drill and overdrive dome, one built-up will serve around 60k+ (I can't recall the exact number) power.

So for me RTG is early & late game power source, and thorium reactor is a mid-game generator when I'm tight in resources. If its construction cost is cut it'll be overwhelming in early game; and it's simplicity makes it easy to overdrive to provide comparable power to any other solutions in late game. So I think the current stats are balanced.
