### ISSUE TITLE
Deprioritize burning buildings from being rebuilt by polies

### ISSUE THREAD

**Issue by Xaphironius** [Anuken/Mindustry-Suggestions#4789]
### Describe the content or mechanics you are proposing.

Prioritize much more important things such as a downed defence. Make them rebuild it only after the fire has been set out.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This prevents a *sisyphus* moment, (rebuilds, building gets destroyed, repeat), and polies won't get stuck from this endless loop if this becomes a feature.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Tamren** [comment]
Could extend this to "do not rebuild anything currently on fire or covered in slag".
