### ISSUE TITLE
Launch Pad Feature Maybe?

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#479]
**Describe the content or mechanics you are proposing.**

I know launch pads can send materials to other sectors, but I think that launch pads should also be able to send materials to "drop" configured launch pad, in adjacent sectors. Basically a mass driver, but across sector boundries. 

**How is this not a teleporter?**

Range: They have a range limit of 1 sector (they can only send items to adjacent sectors)
Connections: One "drop" pad can only be connected to one launch pad
Throughput: They only accept a certain amount of items per second, and they can only recieve items every few seconds

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Now, most of the time, sending materials directly to the core to be fine, but I think this could add a bit more flexibility to how one could build a mega factory in a sector (there are only so much unloaders that can go near a core). 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Ah yes. That would make a very op teleporter.

**Comment by genNAowl** [comment]
> Ah yes. That would make a very op teleporter.

No, Its not exactly a teleporter; My original idea was to make it so "drop" pads could only be launched too from adjacent sectors; And since they have to take items from other launch pads, not from the global resources, and I forgot to mention their throughput is dependent on how far away the connected launch pad is

**Comment by genNAowl** [comment]
> Also, #152

Thats what I had thought people would say. see ^

**Comment by genNAowl** [comment]
I would like to add that this is essentially a mass driver with a range that stretches through sectors. If these are teleporters why aren't mass drivers too?

**Comment by itcannotbe** [comment]
What's stopping me from faking maxed throughput MD's then?

**Comment by genNAowl** [comment]
How about making it so each pad can only have one connection?

**Comment by genNAowl** [comment]
oopd

**Comment by genNAowl** [comment]
bonk
