### ISSUE TITLE
Historia para el juego 

### ISSUE THREAD

**Issue by YINX16** [Anuken/Mindustry-Suggestions#4790]
### Describe the content or mechanics you are proposing.

Lo que propongo para el juego sería una historia vace de como comenzo la disputa entre el jugador y los enemigos del cada planeta (erekir,sepultó) mostrándonos animaciones de por que nos peleamos contra esas civilizaciones de esos dos planetas y que en cada nivel nos muestren con una animación o una voz de ejemplo un comandante de lo que tenemos que hacer y prepararnos para atacar o defender nos y que sea capaz de explicar nos lo que debemos hacer en el transcurso del nivel y dándonos consejos cada cierto tiempo , y también que en el planeta erekir se puedan jugar las demás zonas 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Pues este contenido mejoraría el juego en muchas cosas por que nos guiaría sobre como jugar y que hacer y entender por qué atacamos o defendemos ,por que lo juegos es muy bueno aunque sería mejor con esta historia que les sugiero 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by eeve-lyn** [comment]
Un juego no necesita una historia para ser bueno, es mucho mejor intentar especular sobre la historia en lugar de que te la cuenten directamente.

**Comment by YINX16** [comment]
> Un juego no necesita una historia para ser bueno, es mucho mejor intentar especular sobre la historia en lugar de que te la cuenten directamente.

Bueno tienes razón la verdad especular es algo que lleva a imagina muchas cosas pero no estaría mal lo demas que dije
