### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by The1Crux** [Anuken/Mindustry-Suggestions#4793]
### Describe the content or mechanics you are proposing.

Make Base Builder IA learn how players do their strategyes

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

What I propose is that the base building AI should be trained by watching how the players play, and reviewing their strategies to counteract them or hinder their attacks.

Depending on the difficulty chosen at the menu, it could be the speed with which the AI ​​learns from your strategies to return them to you

Another idea that would be pretty cool would be to be able to let players leave some schemes so that the best ones could be added to the AI ​​database.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/3617#issuecomment-1146013266

Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

**Comment by jehosula** [comment]
at least not make it litter weird schematics all over the base

**Comment by egfthomas** [comment]
> [#3617 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/3617#issuecomment-1146013266)
> 
> Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

A neural net base builder AI would be cool .....

**Comment by Kostr8** [comment]
Хотя бы заскриптованые постройки для каждой карты

**Comment by camelStyleUser** [comment]
> > [#3617 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/3617#issuecomment-1146013266)
> > Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.
> 
> A neural net base builder AI would be cool .....

buzz buzz buzz buzz
