### ISSUE TITLE
Depleted radioactivity

### ISSUE THREAD

**Issue by foxy85391** [Anuken/Mindustry-Suggestions#480]
Add something which comes out of any sort of radioactive generator that is a depleted version of the original and can be used as ammo

It will mean that it would be much more useful to use radioactive generators (aka thorium reactor and RGT gen)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
Radioactive generators (thorium reactor in mind here) are already very efficient and powerful. Is this supposed to be a nerf or a buff?

**Comment by Anuken** [comment]
I don't think reactors need a buff. This is better suited to special production blocks, not existing reactors/RTGs.

**Comment by itcannotbe** [comment]
I think having a waste product is actually a nerf not a buff.

**Comment by foxy85391** [comment]
It would be a buff because it would be easy to get rid of

**Comment by foxy85391** [comment]
Unless you dropped the output power

**Comment by itcannotbe** [comment]
Unless you can't get rid of it that easily and would affect generation in a significant manner if not dealt with properly like an area nerf.

**Comment by foxy85391** [comment]
I geuss

**Comment by foxy85391** [comment]
Perhaps if you made it so that if you incinerate radioactive material and they damage structures around them
