### ISSUE TITLE
Solving a launchpad calculation issue

### ISSUE THREAD

**Issue by Tamren** [Anuken/Mindustry-Suggestions#4800]
### Describe what you would like changed, and why.

To calculate how many resources are sent by launchpad the game tracks the last 60 seconds of game time. The problem with the current system is that it tends to "hitch" momentarily when you enter a zone with working launchpads. For instance if the map exports 600 titanium per minute, simply by entering that map I can often cause that number to drop to 550/m or less. This is a common scenario for me because I often enter maps for the sole purpose of changing the launchpad destination.

### Describe the changes you want to propose. Include possible alternatives.

I can think of two possible solutions for this, one simpler than the other:

1. Freeze the speed of exported materials for 60 seconds unless the game calculates a higher number during that time. So for instance if I drop into a map and titanium exported per minute drops from 600 to 550 for whatever reason, the game will ignore that. If the number rises beyond the previous calculation the game will use the higher number instead to account for cases where the player left the map before maximum speed was achieved.

2. Allow players to change the destination of launchpads from the world map, without having to load into that map. You could do this by adding a new button beside Change Icon that appears if a zone has working launchpads.

**Comment by egfthomas** [comment]
I would like to piggyback off this suggestion to say that launch pads should be able to launch to the core of the sector where they are.  If a launchpad can launch from Fungle Pass to a sector halfway around the planet, it should be able to launch to the core at Fungle Pass.  

+1 for an option to change launchpad destination from the world map
Also would be great to have a button in the current sector to say "send all exports here" -- massive time saver
