### ISSUE TITLE
不要让投影消失成为遗憾和你生气的工具

### ISSUE THREAD

**Issue by 5935481654816** [Anuken/Mindustry-Suggestions#4801]
### Describe the content or mechanics you are proposing.

对于你们取消发射在星球上建出来的建筑被打坏后，仍可以用于修复的投影取消了,遗弃导致全部！全部！全部！！！损毁，并不是我想看到的。这让我的体验很糟糕。每一份的建造都是独一无二的。我不认为再次挑战是很轻松的事情。我现在的感觉很差， 很糟糕。就像你花了两个小时做制作的精美蛋糕，被人打了几巴掌一样！不是所有人都有很多时间，心情一下就变差了

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

所有版本都不要把投影取消掉，就算是遗弃。就像你这个房子你不住了，你暂时出去出差，难道它会立即自动毁掉吗？建议归还

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
Translation 

Don't let the shadow disappear become a tool of regret and your anger. 

Describe the content or mechanics you are proposing.
After you cancel the launch and the buildings built on the planet are damaged, the projections that can still be used for repair are canceled and abandoned, causing all! all! all! ! ! Damage is not what I want to see. This made my experience terrible. Each build is unique. I don't think it will be easy to challenge again. I feel very bad now, very bad. It's like you spent two hours making a beautifully crafted cake and got slapped a few times! Not everyone has a lot of time, and their mood suddenly deteriorates.

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
Do not cancel the projection in all versions, it will be considered abandoned. Just like you can no longer live in your house, and you go on a business trip temporarily, will it be automatically destroyed immediately? Recommended to return

**Comment by egfthomas** [comment]
I know, they need to stop cancelling those projections
