### ISSUE TITLE
Linked accounts

### ISSUE THREAD

**Issue by FontFar** [Anuken/Mindustry-Suggestions#4802]
### Describe the content or mechanics you are proposing.

You can use same account with same progress on different devices 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

People can use one account on different devices and play with cloud saves. Cloud saves can be downloaded and uploaded when you are connected to the net, but while you are offline you can play only with previously downloaded save. When progress differs from cloud save ( _device: 1st planet more advanced ||| cloud: 2nd planet more adviced_) the game asks you what do you prefer: to **upload cloud save** / **to download cloud save** | and probably: **to create save when both planets are low level** (_the least levels from both cloud and device save files_) / **to create save when both planets are max level** (_the highest levels from both cloud and device files_)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by eeve-lyn** [comment]
that doesn't work because the game has no servers

**Comment by egfthomas** [comment]
Use Steam and you will get cloud saves.

**Comment by camelStyleUser** [comment]
- use steam, cloud saves
- make it yourself and pay for your own servers, not tell anuke to do it

**Comment by 5GameMaker** [comment]
https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest

**Comment by gw-dev101** [comment]
Code it yourself and pay for any related costs
