### ISSUE TITLE
Interplanetary accelerator could be used to send units to attack sectors late-game

### ISSUE THREAD

**Issue by egfthomas** [Anuken/Mindustry-Suggestions#4803]
### Describe the content or mechanics you are proposing.

My 5yo son and I play Mindustry all the time.  Thank you for creating this fantastic game!  I found this game when looking for open source simcity-like games for him and I to play and it has become our favorite game of all time.  I've bought it on Steam for him and I and our friends.  He was asking me where the units come from in defense sectors.  I explained that adjacent sectors with enemy bases send units to attack - and we came up with this idea.  

Late game, after defeating all named sectors (Serpulo only) the interplanetary accelerator could be used to send units to attack and capture adjacent uncaptured sectors - (IE fab the units in the captured sector and "launch" them with the IA device or with some other launchpad type block).  I understand this may be difficult to attack cores in sectors where the attacking team does not actually have a core, but it would really bring the story of Serpulo full-circle - you start out with enemies coming in from adjacent sectors and finish the planet by doing the same. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be a nice storyline enhancement and would fit the existing mechanics of the game.  If you're like my 5yo (and me!) wondering when first starting this game how the enemy is attacking you from afar, you would get to do the same thing later in the game to finish off Serpulo.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by egfthomas** [comment]
Note;  I found this on Trello but it's not quite the same: https://trello.com/c/TogJg9CP/612-sector-transfer

**Comment by overdramaticpanromantic** [comment]
i like this (yeag)

**Comment by yesC48** [comment]
same

**Comment by Mythril382** [comment]
I always though they were dropped in from an unseen air unit, possibly just oct.
