### ISSUE TITLE
Only one player mechanic

### ISSUE THREAD

**Issue by Uylol** [Anuken/Mindustry-Suggestions#4804]
### Describe the content or mechanics you are proposing.

Commands that can make effects like effect or mark (in beta) being able to be only seen to one player

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Brings ALOOT of new content that could be created with logic

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SkyeTheFoxyFox** [comment]
The real magic is that you can already do this if you understand how to manage desynced processors

**Comment by Mythril382** [comment]
Desync world processors, simple.
