### ISSUE TITLE
Reset lost sectors

### ISSUE THREAD

**Issue by Chromograph** [Anuken/Mindustry-Suggestions#4805]
### Describe the content or mechanics you are proposing.

I believe there should be a feature, maybe a button, to reset a lost sector. What I mean by this is that when you try to capture a sector you’ve already lost, it’s hard to develop a new strategy, when there is a bunch of walls and stuff in the way which you either have to remove which takes valuable time and is frankly quite boring. Optionally you can repair the destroyed structures which also takes time and recourses. This also kind of forces you to have the same strategy you had the last time. I think this should be an option. I know this is possible on pc if you go into the files and delete the ones for a sector, but I like playing on phone, and you can’t delete files for this on the phone. Thank you for your time, I hope you consider adding this!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would really improve the game, and now I’m speaking from own experience, but I quickly loose motivation to capture new sectors when I have to remove or rebuild old structures before I can actually start capturing. When all campaign sectors you have unlocked are filled with junk from older attempts it’s difficult to find motivation, this could probably make, at least me play for longer.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
good option but the campaign is easy/much easier if you rebuild in a few minutes and simply re-try the same strategy until it works, repairing past buildings to make a lot of progress early and then use the advantage to with with bad strategy and skill

**Comment by Chromograph** [comment]
> good option but the campaign is easy/much easier if you rebuild in a few minutes and simply re-try the same strategy until it works, repairing past buildings to make a lot of progress early and then use the advantage to with with bad strategy and skill

I suppose, and I agree that it sometimes can speed up gameplay if you can rebuild, but it should really still be an option. Sometimes you try to capture a sector which you attempted long ago, when your skill wasn’t at the same level, and you didn’t have the same options for structures.
