### ISSUE TITLE
Bring the latum back

### ISSUE THREAD

**Issue by MazorcaGithub** [Anuken/Mindustry-Suggestions#4806]
### Describe the content or mechanics you are proposing.

Bring back to the latum as a neoplasm unit that can be created by the player, can be something simple as when it was hidden in the files or create a branch of units. The purpose of creating a LATUM unit would be to infect the water of the enemy players since in dying, a leather of neoplasm (could also be divided into small smokers such as in the beta)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since the new neoplasm is like an infection and is a new faction is evident that their units cannot be created by the player, so the latum would be an option for the player to use neoplasm, this could be used for the PVP as a way to destroy water from enemies. 

(it seemed that this would be its original use but with the new neoplasm it was discarded, but I hope that there are USES for the neoplasm rather than being an enemy faction, anyway the latum design is so good to delete it)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
latum went because it took up too much atlas space which the neoplasm update requires
