### ISSUE TITLE
Toxopid nerf?

### ISSUE THREAD

**Issue by Kerbutaz** [Anuken/Mindustry-Suggestions#4808]
### Describe what you would like changed, and why.

Currently, Toxopids, despite being large and tall enemies, seem to evade the targeting of anti-air defenses like the scatter. My suggestion is to consider adjusting the targeting parameters of anti-air defenses to include Toxopids. This adjustment would not only enhance gameplay by providing a more realistic and strategic challenge but also add an extra layer of complexity to base defense planning.

### Describe the changes you want to propose. Include possible alternatives.

I dont know ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Slotterleet** [comment]
Why? Toxopid is not flying. This just doesn't make ANY sense. Just use Foreshadow, it's good enough.

**Comment by TheEt1234** [comment]
why, toxopid sucks

**Comment by jehosula** [comment]
> Why? Toxopid is not flying. This just doesn't make ANY sense. Just use Foreshadow, it's good enough.

toxopid is above stuff like scatter

**Comment by AxoCat** [comment]
scatters would be useless against it anyway, this is unnecessary and unrealistic
