### ISSUE TITLE
Oct having very low offensive capabilities and how to make it more support orientated

### ISSUE THREAD

**Issue by Guncattt** [Anuken/Mindustry-Suggestions#4809]
### Describe what you would like changed, and why.

Oct, is a very good defender, and a pretty bad attacker, it can easily be killed before it has a chance to do anything most of the time, it's shield only has about the hp of a extra tier 4... it's shield goes down very quickly most of the time, then it provides nothing other then distracting foreshadows and turrets, not exactly good for the fact it's very expensive and most tier 5s would do the job better.

I would highly prefer having 1 extra corvus to my epic 6 corvus group then have a Oct protecting them to make sure they don't die. As I can easily build a large repair node behind the Corvus's (corvi? Idk)

### Describe the changes you want to propose. Include possible alternatives.

So I have 2 options, both of which would probably be abit underpowered but would help, and not change Octs main core function. (No attacks, just pure support)

Giving Oct overclock aura (similar to oxynoe) or buffing it's Regen Aura, or both.

Presumably the overclock aura of Oct, would be about as large as its shield radius, but the aura would only have 50% uptime.

And of course, the regen aura would be buffed to atleast 180 hp per second, or at the very most, 300 hp per second, I believe 250 or 240 would be just enough though.

It's that or just buff the shield I guess.

Maybe movement speed abit. Idk. Oxynoe being the only one with overclock is quite hard when you want overclock on your tier 5s. But overclock is also very strong, so maybe even a 33% uptime would be good.

What ever it is, Oct really does need a slight boost to its supportive capabilities to other units.

**Comment by JasonP01** [comment]
Honestly oct shield could use a buff, i dont think it needs status effects to improve upon its usefulness.

The regen effect, i do think it needs maybe a rework to be % instead of a flat 300 tick every (5 seconds?), so that t5 can actually utilise the regen effect without relying in the repair turrets as oct is way too slow at repairing itself or other t5 for being a non offensive unit

As for its shield, id recommend making it shield take reduced damage, give the shield damage reduction and way more health so it actually functions as a viable sheild to protect corvus, its current regen rate for the shield i think is fine, though with hp increase it would be nice to increase it as well
(Mention corvus as its the most used with oct currently, atleast in the servers i play)

**Comment by jehosula** [comment]
personally i think we should give oct a strong shield ~14k?? and a better aoe ~+100%? and give it 2 repair points ~250 hp/s each?

**Comment by divine-ray** [comment]
the repair aura from oct is so weak that i often forget about it; it could certainly use a buff and/or get repair points like vela -it‘s a tier 5 unit after all
as far as support goes, it’s barely even functional as bullet sponge (tank)

**Comment by Guncattt** [comment]
> Honestly oct shield could use a buff, i dont think it needs status effects to improve upon its usefulness.
> 
> The regen effect, i do think it needs maybe a rework to be % instead of a flat 300 tick every (5 seconds?), so that t5 can actually utilise the regen effect without relying in the repair turrets as oct is way too slow at repairing itself or other t5 for being a non offensive unit
> 
> As for its shield, id recommend making it shield take reduced damage, give the shield damage reduction and way more health so it actually functions as a viable sheild to protect corvus, its current regen rate for the shield i think is fine, though with hp increase it would be nice to increase it as well (Mention corvus as its the most used with oct currently, atleast in the servers i play)

Consider this: oxynoe is the only unit in the game to give overclock... and overclock is a very strong buff...
