### ISSUE TITLE
The mono tree name change

### ISSUE THREAD

**Issue by Puppiesss** [Anuken/Mindustry-Suggestions#4810]
### Describe the content or mechanics you are proposing.

Change it so that it goes mono>poly>quad>oct>mega

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

For consistency sake make it so the names of the mono tree increase in number so it isn't 1>many>1000000>4>8 and instead is 1>many>4>8>1000000, I would suggest renaming poly to duo but we already have a duo so this is the best i can suggest. This will confuse a lot of people but i think it's necessary sacrifice for naming consistency.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by zeutd** [comment]
swapping names this late in the game's life is extremely silly and would cause mountains of confusion for no good reason
                                                                                                          ----anuke
