### ISSUE TITLE
Customizing starting schematic on Erekir

### ISSUE THREAD

**Issue by Frolonov** [Anuken/Mindustry-Suggestions#4812]
### Describe the content or mechanics you are proposing.

Allowing player to design / customize the preset base (the one spawn when player trying to capture / re-capture a sector) on Erekir within the given resource limit in a 'pause mode' would be even more fun than using a 15x15 core schematic on Serpulo. 

This also gives player a bit more time for planning rather than modifying the current preset (which takes time to deconstruct and reconstruct) under the pressure of enemy invasion countdown.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Customizing starting schematic on Erekir gives player a lot more freedom and enables diverse gameplay(prioritize resource / unit production as needed), potentially making Erekir campaign more attractive and less frustrating for those who has trouble fighting against early rush of enemy.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
solution to problem: use the preset loadout
problem with suggestion: too difficult to balance

**Comment by Frolonov** [comment]
> solution to problem: use the preset loadout problem with suggestion: too difficult to balance

It's all up to the player design the starting base. It's not likely to make things much easier unless the player has enough knowledge of the game and this would take quite some effort in terms of learning and designing. Invasion count down could be shorter but any balancing more than that would be unnecessary in campaign mode.
