### ISSUE TITLE
Co-op Quality of Life: Shared Build Plans & Non-Host-Player viewing of Research Tree and Planet Map

### ISSUE THREAD

**Issue by ZachIngram04** [Anuken/Mindustry-Suggestions#4814]
### Describe the content or mechanics you are proposing.

These are some features that would make great quality-of-life improvements for co-op play, which I have found myself missing whilst playing the campaign with friends:

Feature 1: Ability to view/interact-with building plans of the other players while paused, as well as while un-paused.

Feature 2: Ability to review the tech research tree and planetary map of the host as a non-host player (I am _not_ suggesting being able to research as the non-host or being able to warp as the non-host).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Feature 1: The fact that you can't see or interact with the other players' building plans makes it really difficult to assist other players in what they are working on and communicate about what you're designing. This often leads to unfortunate situations where multiple players design something in the same area while paused, and upon resuming play the players immediately begin building their plans in an overlapping, conflicting manner.

Feature 2: Again, this would make it much easier to communicate about what the players would like to work towards (e.g. What buildings/units should we spend resources to research? How much more of x resource do we need to get that tech? What sector should we conquer/work on next? etc.).

These features would make going through the campaign with a friend (or two) a much smoother experience.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Heckray** [comment]
yup!
