### ISSUE TITLE
Different erekir environments based on side of the planet

### ISSUE THREAD

**Issue by FungusVendor** [Anuken/Mindustry-Suggestions#4815]
### Describe the content or mechanics you are proposing.

Since erekir is tidally locked, it feels really weird that both sides are pretty much completely environmentally equal.
I propose that, while the side of erekir facing the sun could remain pretty much unchanged, the size of the planet facing away from the sun could be covered entirely in ice-themed environment blocks rather than the oranges of the sunny side.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make erekir just a tad bit more visually interesting and less bland. Not really a "mechanics" change but just a cool flavor thing.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
have you ever heard about "atmosphere"?

**Comment by egfthomas** [comment]
+1 for different sides of tidally locked planet - dark side should be dark and generally cold.

**Comment by egfthomas** [comment]
wd

> have you ever heard about "atmosphere"?

Atmosphere would not exactly make the dark side (the side facing away from the star) bright/warm.
