### ISSUE TITLE
Weather OSTs

### ISSUE THREAD

**Issue by SpaceEarthEX** [Anuken/Mindustry-Suggestions#482]
**Make the Weather OSTs in each weather**

Please make musics according to the weather. **I recommend: "It's okay each weather if it's just one."**
It may sound very hard to make music, but I always cheer for you.  If do it for real, I will be very happy and I'm gonna keep listening to those songs.

 
**good luck..**

===================================================================================

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SpaceEarthEX** [comment]
Looks like this is not good idea

**Comment by RogueRedHawk** [comment]
I like the idea itself. I'd like to see more music in the game. I really like the existing songs but it all depends on if Anuke wants to make more songs for the game, which is his choice.
