### ISSUE TITLE
New Planet / Planet completion reward

### ISSUE THREAD

**Issue by DePusaHereBois** [Anuken/Mindustry-Suggestions#4823]
### Describe the content or mechanics you are proposing.

New Planet: Adding a whole new planet to the game, probably a fungi themed planet.
Planet completion reward: When you conquered a planet (for example is Erekir) you can get advantage to other planet like Serpulo.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New Planet: The Planet will be similar to Erekir with enemy bases to destroy and sectors to conquer. This will add more content to the game for us to explore.
Planet completion reward: After conquering a planet we can advantage to other planet, Example is reduced enemy waves or something to make completing a planet much rewarding.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
pro wants new planet,
how about you add it in a mod yourself?

**Comment by camelStyleUser** [comment]
anuke isnt going to spend 2 more years creating a planet just because a random person wants a new planet
