### ISSUE TITLE
Add the ability to `sensor` the velocity of a unit with logic.

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry-Suggestions#4825]
### Describe the content or mechanics you are proposing.

Add the ability to sensor the x and y velocity of a unit using the `sensor` instruction.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would add a more stable way to get the velocity of a unit without having to estimate it from the position.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
Actually dont even need an x and y velocity, just a flat number plus sensing unit rotation would work with determining direction and whatnot.
