### ISSUE TITLE
DestroyEvent

### ISSUE THREAD

**Issue by YmStrip** [Anuken/Mindustry-Suggestions#4828]
### Describe the content or mechanics you are proposing.

```java
//mindustry.world.building.java
Tile tile = world.tileBuilding(x, y);
//this should never happen, but it doesn't hurt to check for links
```

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There is no BlockDestroy event when demolishing a building, and there is no information about the block when breaking=true in BlockBuildBeginEvent and BlockBuildEndEvent.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
You sure this isn't meant to be in bugs report? You aren't exactly asking for any thing rather you are just stating these things happen/exist

**Comment by Mythril382** [comment]
*Someone didn't check.*
![Screenshot_2024-01-02-17-25-28-59](https://github.com/Anuken/Mindustry-Suggestions/assets/77225817/badc90af-d199-45a1-bbe7-9fd79aebc570)

And `public boolean breaking;` in `BlockBuildBeginEvent` and `BlockBuildEndEvent` is to check if the block is being deconstructed.
