### ISSUE TITLE
Feedback on Silicon Crucibles?

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#483]
So I'm not exactly sure If I should be posting feedback on new 6.0 blocks or features (they aren't exactly balanced yet), but imma do a yolo here and wing it (If you don't like it, I'll close it)

**Comparison to multi-presses**

Anyway, since there is no real way to compare these two similar blocks directly, I'll compare them to their smaller variant, and then compare those ratios to each other (If that makes any sense)

*These numbers were taken from build 9630*

**Processing Power**

A Silicon Crucible makes 8 silicon every 1.5 seconds, which is 5.33 silicon per second. A Silicon Smelter makes 1 silicon every 0.67 seconds, which is 1.5 silicon per second. 5.33 / 1.5 = 3.56, which means **a Silicon crucible has 3.5x processing power compared to its smaller variant.**
A Multi Press makes 2 graphite every 0.5 seconds, which is 4 graphite per second. A graphite press makes 1 graphite every 1.5 seconds, which is 0.67 graphite per second. 4/0.67 = 6, which means **a Multi press has 6x processing power compared to its smaller variant.**

This may seem unbalanced at first, but as Silicon crucibles can be placed on heat tiles to boost its processing power up to 7x, I'd say **in terms of processing power, Silicon crucibles are pretty balanced.**

**Efficiency**

A Multi Press makes 2 graphite for 3 coal = 0.67 efficiency. A graphite press makes 1 graphite for 2 coal = 0.5 efficiency. 0.67/0.5 = 1.33, which means **a Multi press is 1.33 times more efficient than its smaller variant.**
 A Silicon Crucible makes 8 silicon for 3 coal, 6 sand, and 1 pyratite (which is 1 coal and 2 sand + 1 lead) = 2 efficiency. A silicon smelter makes 1 silicon for 1 coal and 2 sand = 1 efficiency. 2/1 = 2, which means **a Silicon crucible is 2 times more efficient than its smaller variant.**

Yikes. **silicon crucibles are incredibly efficient**. A efficiency ratio of 2 is ridiculous, compared to the multi press's 1.33. Even considering the fact that silicon crucibles cost plastanium, I think 2 is still very high. 

**Conclusion**

Silicon Crucibles are way to efficient in my opinion. When testing 6.0, I was very surprised when I could obtain more 1.1 titanium belts of silicon while only using 1 belt of sand (As an experienced player, I usually expect silicon setups to **eat** sand). 

Maybe make them use 4 coal, 8 sand, and 1 pyratite?

**Comment by sample-text-here** [comment]
Silicon crucibles are efficient, but they take pyrite. Pyrite mixers take an additional sand and coal, along with some lead. I would say that they are balanced.

**Comment by genNAowl** [comment]
> Silicon crucibles are efficient, but they take pyrite. Pyrite mixers take an additional sand and coal, along with some lead. I would say that they are balanced.

I added the coal and sand from the pyratite into the calculation.

**Comment by genNAowl** [comment]
Anyway, this suggestion is out of date. Silicon crucibles now take 4 coal, 6 sand, and 1 pyratite, which is a nerf, I guess.
