### ISSUE TITLE
Gesture zoom control for mobile

### ISSUE THREAD

**Issue by homieto** [Anuken/Mindustry-Suggestions#4831]
### Describe the content or mechanics you are proposing.

Google Maps has had a feature since 2013, where if you double-tap the maps interface, but instead of lifting your finger after the second tap (the shortcut for zooming in), you leave it touching the screen. Then a swipe up zooms out, and a swipe down zooms in. 

It’s incredibly handy to get around the maps with a single hand. It’s also not exclusive to Google maps - it works on Apple Maps and CityMapper. 

I propose the same mechanic to be added to Mindustry. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Gesture zoom control will enhance Mindustry's mobile gameplay by introducing a more accessible and intuitive zoom control method. 

It will make it very easy to play the game single handed, with most other features of the game being able to be used single handedly already (that’s my preferred style of play on my phone) This can make the game easier to navigate, easier to pick up and play on the go (I love playing on the underground, but I can’t hold the rail and zoom in/out at the same time), adding convenience and reducing the friction in the gameplay.

and let’s not even mention the accessibility aspect of this feature - more players who have difficulty using both hands will be able to play. And personally, players will be able to play for a lot longer too, as it’ll make it so much easier to “build just one more mech fabricator” and sneak a quick game before bed for example.

 I love this game, but I don’t play it much on my computer. It’s perfect for mobile because you can play it both horizontal and vertical, and when it’s vertical, having that gesture zoom control would make the game sooooo much better.
 
Here’s an example of the feature: https://youtu.be/qj0_94Ri7D4

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by egfthomas** [comment]
Not a mobile player, but maybe I would be with some simple additions like this ?
