### ISSUE TITLE
Buildable floors

### ISSUE THREAD

**Issue by Weapon100** [Anuken/Mindustry-Suggestions#4832]
### Describe the content or mechanics you are proposing.

Make the in-game factory tiles buildable by player. Swap between building floors and normal buildings with a hotkey to allow layers.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I really enjoy the look of the factory tiles in Mindustry, and think that it would be really neat to make them buildable to the player. Rather than having a factory on a random area, you turn the landscape into a factory complete with hazard stripes and an industrial look. Since stuff can be built on top of, maybe a hotkey to change between building floors and normal buildings?

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by rekokoro** [comment]
Well, on some servers it's already buildable
