### ISSUE TITLE
custom tech tree on custom maps

### ISSUE THREAD

**Issue by L-Shiro** [Anuken/Mindustry-Suggestions#4833]
### Describe the content or mechanics you are proposing.

add the same tech tree system (from campaign) to the custom maps mode(offline)
might be a good idea to make a button to choose either to turn it on or off

you start on the custom map with the same items on ground zero, but researching for items take way less resources (so you can research everything in one game)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i liked the challenge of campaign that you don't have access to everything, but when you finish the game it's refreshing to play custom games, it would be more beautiful if you can If you can restart the game from scratch for one or two hours without wiping your progress in the campaign

there might be a problem for maps that doesn't have all the resources in the game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
you mean a mod?

**Comment by FactKys-Studios** [comment]
I really hope this gets added, I was thinking about this a couple of months ago and was looking for mods or trying to come up with a solution for this.  Research in custom games will be very cool; in co-op survival, technologies are synchronized, and in PvP, each team has its own research, this will allow you to create maps with unique gameplay, for example, a story-based campaign on one map.  You also need to add more commands to interact with the game, for example: changing the amount of resources in the core, changing object parameters, and anything else you can think of.

**Comment by L-Shiro** [comment]
> you mean a mod?

if you know a mod can do this then I'd be happy

**Comment by L-Shiro** [comment]
> I really hope this gets added, I was thinking about this a couple of months ago and was looking for mods or trying to come up with a solution for this. Research in custom games will be very cool; in co-op survival, technologies are synchronized, and in PvP, each team has its own research, this will allow you to create maps with unique gameplay, for example, a story-based campaign on one map. You also need to add more commands to interact with the game, for example: changing the amount of resources in the core, changing object parameters, and anything else you can think of.

that's cool I'd love to play with these features

**Comment by FactKys-Studios** [comment]
In general, you can write a mod that does this, but let me think in programming, but little information Mindustry API, unlike Factorio, does not allow you to fully get all the necessary architecture of the game, and a lot of things do not work for me because I do not understand how Mindustry works with JS scripts

**Comment by S0meM** [comment]
This is a really cool idea. I like it.

**Comment by yesC48** [comment]
very interesting inde
