### ISSUE TITLE
A quality of life chang to  processors

### ISSUE THREAD

**Issue by DemianCsomicWinters** [Anuken/Mindustry-Suggestions#4838]
### Describe what you would like changed, and why.

Change UI for processors structure as currently I am in able to add any block directly under process if is 1 by 1 block, meaning can't have the block above anything or risk not being able manipulate it with code from blocks such as micro processor.

### Describe the changes you want to propose. Include possible alternatives.

I was thinking of moving UI for entering coding system of processors into UI that's in the right side of screen where all the other UI stuff is found, in the section where  deconstruct and schematic copy UI are, this way it won't get in way of blocks.

Alternative is move current Processor UI directly on top and center of processor blocks instead of below them.

**Comment by egfthomas** [comment]
If I understand what you are saying, the processor binds to the building directly underneath it whether you want it to or not, I have noticed this as well.
