### ISSUE TITLE
Flux Buff

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#4844]
### Describe what you would like changed, and why.

Flux is underused, it has terrible cost and space compared to its power output. and even if it has higher arky effeciency than pyrol, neo still has better.
It is outclassed in its own niche.
The only viable combination is neoflux, and even then if you want to optimize your arky, cost, and space, you are better off with neo.

Ever since its reveal in August 2, 2022. Its finally time to buff the power of this thing.

### Describe the changes you want to propose. Include possible alternatives.

Current Flux Stat 7,200 pu (120 in the game code), 140 heat
##### (A) Buff the Power into 14,400 pu (240 in the game code)
This is a good ballpark for making the cost worth it.

##### (B) Buff the Power into 15,300 pu (255 in the game code), and change the heat to 150
This has similar arky/heat ratios as A, as well as having good ratios (only oxide has a clear division for 140, everything else is too off)

##### Adjustment 
if it still sucks somehow, get it above 18k/150 heat or 16.8k/140 heat
if neoFlux gets too powerful, nerf neo power (and adjust flux accordingly)

##### I don't recommend these adjustments (would make the power/arky ratio worse than neo)
if its too powerful overall, nerf it down to (140 heat) 12k-13.2k pu (200-220 in game)

**Comment by SomeonesShade** [comment]
Notes: 
There are mechanical suggestions that improve heat diversity (allowing more heat options), but priority is just this raw balancing to make flux usable

Here are some stats in this incomplete spread sheet for 14.4k flux

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/S0M1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/S0M1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Power Block | Base Power | Power | offset |   |   |   | Requirements: | Beryllium | Power/Beryllium | Graphite | Power/Graphite | Silicon | Power/Silicon | Tungsten | Power/Tungsten | Oxide | Power/Oxide | Surge | Power/Surge | Thorium | Power/Thorium | Carbide | Power/Carbide | Phase | Power/Phase | Heat | Power/Heat | Arky (assume cyano has separate heat) | Power/Arky | Slag | Power/Slag | Phase | Power/Phase
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Flux (base) | 14400 | 14400 |   |   | this assumes everything else is free |   |   | 300 | 48 | 600 | 24 |   |   | 100 | 144 | 300 | 48 |   |   | 200 | 72 |   |   | 140 | 102.8571429 | 120 | 120 |   |   |   |  
EHeat Flux | 14400 | 9733.333 | -4666.666667 |   | Items are based |   | 514 | 18.93644617 | 450 | 21.62962963 | 680 | 14.31372549 | 1710 | 5.692007797 | 1660 | 5.86345382 | 300 | 32.4444444 |   |   | 250 | 38.93333333 |   |   | 140 | 69.52380952 | 120 | 81.111111 |   |   |   |  
SlagHeat Flux | 14400 | 14400 |   |   | on the schem used |   | 1103 | 13.05530372 | 616 | 23.37662338 | 680 | 21.17647059 | 1190 | 12.10084034 | 500 | 28.8 | 300 | 48 |   |   | 250 | 57.6 |   |   | 140 | 102.8571429 | 120 | 120 | 700 | 20.571429 |   |  
PHeat Flux | 14400 | 14400 |   |   |   |   |   | 984 | 14.63414634 | 500 | 28.8 | 940 | 15.31914894 | 410 | 35.12195122 | 490 | 29.3877551 | 300 | 48 | 100 | 144 | 730 | 19.7260274 |   |   | 140 | 102.8571429 | 120 | 120 |   |   | 1.12 | 12857.14286
NeoHeat Flux | 14400 | 34000 | 19600 | NeoCount = | 2.333333333 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 140 | 242.8571429 | 306.6666667 | 110.86957 |   |   | 0.777778 | 43714.28571
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
CCC | 600 | 600 |   |   | Threshold Limit | using base stats, no transport   included | 40 | 15 | 30 | 20 | 40 | 15 | 40 | 15 |   |   |   |   |   |   |   |   |   |   | 40 | 15 |   |   |   |  
Pyrol | 1500 | 1500 |   |   |   |   |   |   |   | 50 | 30 | 50 | 30 |   |   | 60 | 25 |   |   |   |   | 50 | 30 |   |   |   |   | 40 | 37.5 | 20 | 75 |   |  
Neo | 8400 | 8400 |   |   |   |   |   |   |   |   |   | 500 | 16.8 | 1000 | 8.4 | 150 | 56 | 200 | 42 |   |   | 300 | 28 | 300 | 28 |   |   | 80 | 105 |   |   | 0.333333 | 25200



</body>

</html>

**Comment by BalaM314** [comment]
I think we should nerf neo and buff flux... currently neo is quite strong and 2x or 3x neos provide plenty of power power for eheat afflict spam. The most common use I've seen for flux reactors is as power void inverters... they need a balance change.

**Comment by SomeonesShade** [comment]
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/5ba33e7a-e376-459f-8692-9d0ad5b78710)

i mean sure, neo has absurd arky efficiency and neo nerfing was in the alternatives in the suggestion post

although... considering v8 with the neo units, would it make the neoplasm more deadly?

im honestly okay if the power gets reduced to like 7.2k to 5.1k neo with 12-13k flux
