### ISSUE TITLE
add Alliance between teams

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry-Suggestions#4847]
### Describe the content or mechanics you are proposing.

Ability to prevent attacks between different teams
It can control from map settings or plugins.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow more contents to many server.
ex) Personal defense

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
killer

**Comment by camelStyleUser** [comment]
have you checked the do not suggest list

**Comment by camelStyleUser** [comment]
(abd router is making it)
