### ISSUE TITLE
Yet another RTG buff

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#485]
**Describe what you would like changed, and why.**
The RTG's use time. It should be called RTG for a reason.

**Describe the changes you want to propose. Include possible alternatives.**
SEVERELY increase the RTG's use time, to 20 seconds maybe?

**Comment by Ilya246** [comment]
Note: At an use time of 20 seconds, RTGs make the same amount of power per thorium, but without the cryofluid usage. However, consider their build cost and the amount you'll need to build.

**Comment by genNAowl** [comment]
I think you can close this cause RTGs now have a use time of 15 seconds?
