### ISSUE TITLE
Spores as scorch ammo

### ISSUE THREAD

**Issue by Novanox4** [Anuken/Mindustry-Suggestions#4851]
### Describe the content or mechanics you are proposing.

Spores can be inputted into a scorch. The flame would have a subtle purple tint and apply spore slowed. It would deal less damage than pyratite but more than coal.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be a buff to scorch, and would make sense as spores are flammable. The Spore slowed would also combo as it would allow the scorch to hit units more times.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by python-nerd-3** [comment]
might be a bit op; scorch's short range would synergize with slowing as it could get a lot more hits so maybe decrease its damage but otherwise good idea

**Comment by python-nerd-3** [comment]
stale...
