### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by rty-2** [Anuken/Mindustry-Suggestions#4853]
### Describe what you would like changed, and why.

When you do some research the resources of the cores that are on non-captured sectors can't be used.

### Describe the changes you want to propose. Include possible alternatives.

Create maybe like a toggle button to save the resources on non-captured sectors.

**Comment by camelStyleUser** [comment]
killer you already use their resources in research

**Comment by rty-2** [comment]
> killer you already use their resources in research

Sorry misspelling
