### ISSUE TITLE
Tech tree unit organization (aesthetics / info)

### ISSUE THREAD

**Issue by takumi0168** [Anuken/Mindustry-Suggestions#4854]
### Describe what you would like changed, and why.

Serpulo Tech Tree
I want to change the Unit's organization in the Serpulo tech tree. Currently, it's not organized based on the rank of the units but when you unlock them. I want to line up tier 1 units (units that do not require additive reconstructor) with other tier 1 units of different types as well as tier 2 units with their reconstructor. This organization would help me understand what tier units I'm using. 

### Describe the changes you want to propose. Include possible alternatives.

Move upgrade buildings to line up with the units it produces. For example, move the additive reconstructor down to line up horizontally with, Mace, Nova, Crawler, Horizon, Poly, Minke, and Oxynoe. Currently, these units aren't aligned which is making it a bit confusing when looking at the tech tree trying to decide which unit to use. 
Alternatively, you can shift the land unit to the center for more balance extensions. (*note: I do not want to change the order in which buildings are unlocked just the organization. )

![mindustry units](https://github.com/Anuken/Mindustry-Suggestions/assets/157210808/43ab7ab8-3792-4706-8797-b807488548aa)

**Comment by yesC48** [comment]
no
