### ISSUE TITLE
Able to build cores on Serpulo in custom games

### ISSUE THREAD

**Issue by Roma39375748** [Anuken/Mindustry-Suggestions#4855]
### Describe the content or mechanics you are proposing.

In custom games, if you enable parameter "able to build new core", on Serpulo you can build core Shard and another cores in custom game. In campaign, you can't build core on Serpulo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will make custom games more interesting, and make Serpulo a little more like a Erekir. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
Just use core zones.
