### ISSUE TITLE
Ability to define functions when working with logic

### ISSUE THREAD

**Issue by Brandanvimi** [Anuken/Mindustry-Suggestions#4856]
### Describe the content or mechanics you are proposing.

A new logic that is able to be programmed, but doesn't run code, instead it would save it as a function.
Processors would then be able to connect to the function block and use the function.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

When using the existing logic interface, it is very time consuming to copy large blocks of code (such as complex mathematical operations), and it also makes it harder to know what the code does. Functions can fix that by compressing large amounts of code into a single block.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
`@counter` functions would like to talk with you
```
op add callback @counter 1
jump fun always
printflush messsage1
end
fun:
print "@counter"
print " functions "
print "are "
print "cool"
set @counter callback
```

**Comment by camelStyleUser** [comment]
if you really want to run funcs in separate procs, use cells to transmit data

**Comment by cardillan** [comment]
There are several compilers from higher level languages to mlog, making the code easier to understand and maintain. Some of them support functions and generate quite efficient code. You can find them by searching for "mlog" or "mindcode compiler" on GitHub.

(Disclaimer: I maintain one of these compilers.)
