### ISSUE TITLE
About allowEnvironmentDeconstruct rule

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#4858]
### Describe what you would like changed, and why.

Extend the rule to floor tiles so they can be replaced with other tiles if build is unlocked.

### Describe the changes you want to propose. Include possible alternatives.

Thanks to that rule you can delete blocks and use that empty space to build something. But in same case if floor is made from unbuildable tiles like @space, @empty or @deepwater, you can't nor remove it, nor build on it. So the idea if you have floor blocks buildable, they can replace all the other floors whatever they are.

**Comment by JasonP01** [comment]
Closer and closer to multiplayer editor actually working

**Comment by rekokoro** [comment]
It's already made but half of functionaliy is substitied with world processors

**Comment by JasonP01** [comment]
Anuke added this https://github.com/Anuken/Mindustry/commit/59ea35c44314952b57c89fe1db6a76325ad0f26c

**Comment by JasonP01** [comment]
Only thing missing for

> It's already made but half of functionaliy is substitied with world processors

Only thing missing for multiplayer editor is wave changing and non-host world proc config
