### ISSUE TITLE
upgrading conveyor belts does not destroy resources on them

### ISSUE THREAD

**Issue by Floriantoine** [Anuken/Mindustry-Suggestions#486]
**Describe the content or mechanics you are proposing.**

when a conveyor belt is replaced by another the content is not deleted

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

for me it is an element of logic, when we upgrade a long conveyor belt path we have to wait for the resources to come back because we all deleted on the way

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Ilya246** [comment]
Also, i'd like to add - completely deconstructing any block sends the resources it had to core, if it's rebuilt back instead, the resources remain in the block

**Comment by sample-text-here** [comment]
Great idea, but how will this work with 6.0 plastanium belts?

**Comment by genNAowl** [comment]
https://github.com/Anuken/Mindustry/pull/1049

Anuke says he sees no pressing need for a feature like this at the moment; That might change if this suggestion gets enough support, I guess.

**Comment by Ilya246** [comment]
No, he meant that the feature, at the moment it was proposed, would soon break due to game code change
