### ISSUE TITLE
(Custom game) rule change ingame

### ISSUE THREAD

**Issue by guyguyguyguyguyguyguyguyguyguy** [Anuken/Mindustry-Suggestions#4860]
### Describe the content or mechanics you are proposing.

It sucks having to make another custom game because I messed up a single rule. So I suggest there should be a way we can change the rules thru ingame menu (if rule changing on a existing game exists tell me in comments)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The mechanic will make it less time consuming as I accidentally deleted all of my data thinking it was talking about the custom game data. Thankfully I had some saves on 2 of my runs but there rest are gone.

With it being less time consuming remaking the same game over and over to get it correct, it can also solve the confusion especially the one I had when trying to see if I could go back and change the game rules.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SITUVNgcd** [comment]
My mod can help you change the rule in playtime.
If you installed my mod but it's Settings not show up in game's settings, pls sent me `lastlog.txt`

https://github.com/SITUVNgcd/MindustryModTest
