### ISSUE TITLE
Underground units

### ISSUE THREAD

**Issue by Se1d228** [Anuken/Mindustry-Suggestions#4862]
### Describe the content or mechanics you are proposing.

They go underground to the core, die in water, another units cannot attack them, only you can see them, if they are yours. Only underground turrets or another under units can attack them
You can see another team underground units with radar

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It can make the game harder

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lime712** [comment]
killer
