### ISSUE TITLE
Possible use for your resources in sectors after running out of tech tree, etc. And give liquids endless opportunities for innovative uses

### ISSUE THREAD

**Issue by Jssekekekrr** [Anuken/Mindustry-Suggestions#4865]
### Describe the content or mechanics you are proposing.

Perhaps I could interest you in adding a block and unit designer for vanilla Mindustry, you could use the resources in your core(by extracting from it, which is a button), the modulites (components of custom blocks) are fabricated using inputted (or extracted) resources, most of the production Modulites require liquid input in addition to resources.

I highly recommend checking out the unit hanger in the Unity Project mod.

Also the idea has been in my head for a while. You could potentially find pre-generated block/unit blueprints in things like Crux bases and surviving enough attacks could bring out procedurally generated units(which the blueprint for it can be obtained by scanning it using a unit/block with a scanner modulite inside it)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe that this would work very well with the new faction, as a potential counter, a enhancement to creative output, personalized playstyles and even provide uses for things like Neoplasm and Gallium(which would be quite a welcome addition)

It would enhance the experience of modes like Attack and PVP, while increasing the creative output that can be achieved and would reward players with new toys to play with. this addition will also Set Mindustry apart from other games like it. If you don't know, Mindustry is often compared to Factorio. Please don't interpret this as faction alliances (this is completely unrelated and is based on adding a more powerful creative aspect to Mindustry, not make things mingle, though being able to design custom planets and tech trees would be pretty fun and cool, as it adds another place to utilize the new features).

This would add a filled never thought of niche that can be expanded on easily in addition more Modulites, materials, etc or even an entire planet (which would be AWESOME). I really hope that this catches your fancy, as it would add a aspect of uniqueness to the existing factions and may even pave the way for Mindustry becoming not just a game, but a true masterpiece.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Ayushkiller** [comment]
This is sick,hard to code and very interesting. 10/10 would like in game.

**Comment by Leo-MathGuy** [comment]
This will need a lot of effort to balance out

**Comment by Leo-MathGuy** [comment]
This is a factory game not a chemistry simulator chill lolOn 18 Feb 2024, at 20:10, Jssekekekrr ***@***.***> wrote:﻿
I know, a good method may be making the fabricator consume additional

resources(2 times the requirements for 1 unit, in addition to 6 times the

required input for 1 unit or block a resource called Deuterium, which is an

isotope of hydrogen containing a neutron as extra, its stable, unlike

Tritium, which has 2, so Tritium would very slowly decay) to restock its

supply (basically making it require additional infrastructure to

support)(on Erekir there's the Deuterium Extraction Rig, a large 23x33 at

the standard and the most advanced being 4x6, standard ones are the most

cost efficient for large facilities and they generate 390 units of power

and consume 7, they store 2300 in abil-Puili charge, however to power one

fully you need to dump at least 12k into the most advanced variety and 789

into the standard, this excess is used to power the additional factory

zones within, however once fully powered their power generation is easily

able to offset the now extremely low consumption, though they do not self

charge, so beam nodes will be required to keep its batteries charged whilst

the factory areas are in use), they can be built on Serpulo (only the

standard can), they do optionally accept water (if vents aren't available

that is) and output normally (though you may want to vent the positively

charged Oxygen)(yes, they can break down ozone)



Additionally units built would at first contain a  Deuterium Generator

(which the Deuterium acts as a secondary ammo, but ammunition for the

Generator to provide the energy needed for the non movement functions and

non Catolite(Energy dense material that can be easily obtained based

weapons



I also feel like ozone should build up around spots where it's being vented

into the atmosphere, once a 12x12 radius has built up it will make fires

possible(consuming built up Ozone and leaving behind vaporized oxides, the

amount depends on what was used to build what could fire[excluding regular

Oxide of course] and how long it burned for, the vaporized oxides are the

oxides of the materials used to build the burnt block [so even if it

survives its function is greatly diminished or even made nearly

unsalvagable if it burned for long enough], you can use a O series Roach

unit to collect the oxides and semi-specialized equipment to them solidify

them)(the same flammability rule applies to anything containing large

amounts of Ozone, except only for the blocks containing Ozone that aren't

built to ignite it, a example of a block built to ignite Ozone is that one

power generator that is the first non vent power generator unlocked)



Oxidized Materials can be used to improve quality of your structures, used

as ammo in turrets that accept the non oxidized form of the material,

converted to their un oxidized state(producing Oxygen in the process, which

leaving it in a Reaction Class Standard liquid container will slowly turn

back into Ozone), or simply stored away for later use

**Comment by Jssekekekrr** [comment]
I know, but there's aspects of chemistry present, like hydrogen and Ozone being made in a structure that proforms electrolysis, which don't forget about all of the uses of gasses on Erekir, especially Oxide and in the Chemical Combustion Chamber. in order to combust a fuel you need Oxygen (Atomic symbol "O"), Ozone as you may know is O3(three Oxygen atoms bonded together), however some materials can actually burn without O, O3, or O2 present (I don't know any of these examples but I have reason to believe that Mg is an example) (Mg is the Atomic symbol of Magnesium). Basically I'm just suggesting a little more chemistry (because chemistry in Mindustry is fun, and the nature of Mindustry makes creativity highly effective in adding chemicals)

**Comment by Jssekekekrr** [comment]
I even took it upon myself to model Arkycite in Molview. The result was a semi metallic but mostly organic mess. I also did the same for as many different Mindustry materials as possible. To prevent inaccurate models(compared to the in-game recipe for the material) and to simplify such a task I gave myself a hard limit: The composition MUST match what the game says is needed to make it. However because this rule breaks apart into tiny pieces if the material doesn't have a usable recipe to use for finding composition(example being scrap -> slag, which doesn't tell us what either are made of) or lacks one entirely(like Arkycite), I decided to allow myself to use related recipes (like slag being fed to a separator) to get a hint of composition.

**Comment by Jssekekekrr** [comment]
The best example of me doing this to gauge the composition of something is slag.

I took the 4 recipes I see as closest related, those being both slag processing systems from Serpulo and the 2 ways of making Surge Alloy.

I determined to slag has to have some silicon and figured out the optimal amount(to satisfy the rule of composition being as close as possible to recipe) by comparing the silicon needs of both surge recipes, I then used the outputs of the slag processing systems to get a idea of what to add, but I ended up basing the amounts of Serpulo surge recipe. :(

**Comment by Jssekekekrr** [comment]
at least we can say if Arkycite had my predicted composition, it would be a bit more "Chemificult" (I am going to assume you don't get the joke), though only having proper factories that use it(like not just Cyanogen, which is just graphite plus Arkycite) and have Serpulo counterparts to compare them to would determine the accuracy of my glorified chemical mess of a 3d model of Arkycite is actually accurate.
