### ISSUE TITLE
Erekir content included in menu

### ISSUE THREAD

**Issue by Lolnoizcool** [Anuken/Mindustry-Suggestions#4866]
### Describe the content or mechanics you are proposing.

The menu only include Serpulo content as if just a whole section of the game. What about Erekir, isn't it another aspect of the game? I recommend including an Erekir screensaver

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature will shows to new players that there isn't just one single campaign and makes them aware of the Erekir section

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by yesC48** [comment]
im lovin it

**Comment by Haznobrain** [comment]
We absolutly need an erekir screensaver i agree.

**Comment by 0razec** [comment]
I agree with you, Erekir has beautiful sprites, but few are used in this context. HOW COOL IT WOULD BE TO SEE A CONQUEROR SHOOTING AT A WALL ON THE MENU.

I got excited, but that's exactly it, I hope that as the player opens the technology tree, new menus will appear, I could even include Easter eggs...
