### ISSUE TITLE
Change @solid to refer to all walls and not just stone wall

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry-Suggestions#4869]
### Describe the content or mechanics you are proposing.

It would be very useful if `@solid` in logic would just refer to if the block is a wall rather than only if it were stone-wall, comparing blocks for walls can be useful in map-gimmicks or server stuff

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Change logic `@solid` to refer to any/all walls and not just `@stone-wall`

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BasedUser** [comment]
this change specifically is impossible, you're probably looking for some kind of `.synthetic` sensor
