### ISSUE TITLE
Add wet soil (mud) to the game, a suggestion to a suggestion already made.

### ISSUE THREAD

**Issue by ARYDESTROYER** [Anuken/Mindustry-Suggestions#487]
**Describe the content or mechanics you are proposing.**
https://discordapp.com/channels/391020510269669376/404384551037698065/753987337939189882
I would like to allow players to extract water from mud. It will not be very efficient but possible. Troops should slow down tremendously when walking over mud but not die like they do in the water. Water troops should only be able to travel a very short distance in this until their propellors collapse of stress.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will enable new functions in-game, players could extract water from another source at less efficiency but at the same time, ground troops can submerge in this but not die unlike they do in water in water.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
I believe the original PR included water extractors are more efficient on mud, so this is basically already implemented. It doesn't seem useful to em to allow water troops on mud though.
