### ISSUE TITLE
We're teaching on top of Mindustry

### ISSUE THREAD

**Issue by jcornudella** [Anuken/Mindustry-Suggestions#4870]
### Describe what you would like changed, and why.

Hey Anuken!

My name is Joan, I work at Recess (tryrecess.com) where we're building the best place for kids to hang out online and do hard things together. We have a heavy focus on engineering and we've been using Mindustry to teach cohorts of kids weekly.

The results are absolutely insane and we'd love to share them with you. 

### Describe the changes you want to propose. Include possible alternatives.

If you're into this, there's a ton we'd like to talk about and collaborate on to make this an even better experience for kids. Some of our guides are starting to code their own intros and cutscenes, create killer maps and challenges, etc. We're super thankful that you created this gem!

**Comment by jcornudella** [comment]
Needless to say, we'd love to chat. You can reach out to me here: joan@tryrecess.com

**Comment by jcornudella** [comment]
Oh totally, because using Mindustry as a tool to accelerate kids' brain wiring for engineering and acquiring taste for great games through them figuring things out in Mindustry from first principles, making their own maps and events and building epic PvP experiences is bound to make a dev angry. 🤔

**Comment by Geodafence** [comment]
I am not actually sure anuke checks suggestions anymore

**Comment by jehosula** [comment]
use this game as it is

**Comment by JasonP01** [comment]
> I am not actually sure anuke checks suggestions anymore

He does, just likely not on github. A couple suggestions do get added but anuke never talks in suggestions or closes them himself
