### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by MagnumBasic** [Anuken/Mindustry-Suggestions#4872]
### Describe the content or mechanics you are proposing.

damaged blocks work slower than none damaged ones

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would make the game realistic, for example, a damaged drill would mine slower, or a damaged thorium reactor would be more likely to gain heat and explode

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
idk

**Comment by Haznobrain** [comment]
No
Just no
absolutly no fucking way
just no
who gives a shit about "ReAlISm" in a gale where massive amalgamations of silicon and metal and plastic can fly with one thruster and have infinite bullets from seemingly nowhere.
