### ISSUE TITLE
Using pkl instead of Js (or maybe Json) for modding

### ISSUE THREAD

**Issue by Minxyzgo** [Anuken/Mindustry-Suggestions#4873]
### Describe the content or mechanics you are proposing.

[Pkl](https://github.com/apple/pkl) is a configuration as code language with rich validation and tooling, which will provide more possibilities for modding.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

PKL can run on iOS to solve the problem of JS not being able to run on iOS. Besides, it is written entriely by Java so that Mindustry can integrate it easily. Also, as a configuration, it can replace Json that will overcome the challenges of JSON and JavaScript operability. All in all, I think it might be a good attempt.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
The reason of no mods on iOS isnt a compatibility issue, its that apple specifically states nothing "external"  can run code

**Comment by JasonP01** [comment]
The link to that thing for ios is in the faq channel on the discord

**Comment by Minxyzgo** [comment]
> The reason of no mods on iOS isnt a compatibility issue, its that apple specifically states nothing "external" can run code

Yeah I know you meaning, but Pkl isn't a real programming language, just as i says, it provides more possibilities than JSON. Moreover, it is created by Apple and i don't think it will be refused on ios. Also, I would like to add that this issue is mainly based on the opinions of iOS players and modders. If they believe it is not necessary, then this issue is also meaningless

**Comment by LixieWulf** [comment]
Probably not. As much as moving to PKL has many technical benefits, it does not outweigh the pain of porting mods and the parser to it. 
It would be best *alongside* JSON, but that requires effort. Best to leave the simple to simple, and use Java for more complex mods. 
~~Not to mention, from a JSON modder, iOS support is difficult for any complex mod since iOS is garbage and does not support BE builds~~

**Comment by python-nerd-3** [comment]
> The reason of no mods on iOS isnt a compatibility issue, its that apple specifically states nothing "external" can run code

i love the corporate
