### ISSUE TITLE
Message block sensor/read?

### ISSUE THREAD

**Issue by neo-228** [Anuken/Mindustry-Suggestions#4876]
### Describe what you would like changed, and why.

It would be very great if message blocks could be read, and I have two possible ideas for how to can be done. This will make logic settings and data input much easier and fast.

### Describe the changes you want to propose. Include possible alternatives.

I have 2 possible implementations for this,

The first one is to allow message blocks to be read using the “read” instruction (currently for memory cells), and have the address inputted be the index of the target character to sensor.

The second possible implementation is for the sensor instruction to get @value from message block, and store it in a variable. Then, get the characters using a new charat or getchar instruction that stores it in a new variable

I think either of these options can really help with user input, without being too unbalanced (this isn’t real string manipulation). As an option, this could be not available in micro processors, which will provide more of an upgrade to processors outside speed.

**Comment by itcannotbe** [comment]
[README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)

# A few things you shouldn't suggest

### These have been proposed many times already, and I won't be adding them.

- Any sort of string manipulation in logic (reading from message blocks, reading characters, splitting strings, etc)

**Comment by neo-228** [comment]
Sad
