### ISSUE TITLE
Increase max instructions in higher processor tiers

### ISSUE THREAD

**Issue by neo-228** [Anuken/Mindustry-Suggestions#4877]
### Describe what you would like changed, and why.

Increase the max instructions in hyper processor and medium processor

### Describe the changes you want to propose. Include possible alternatives.

I believe that the maximum instructions in hyper processor should be lifted from 1000, to provide an additional upgrade other than speed to the higher tier processors. I am thinking of 1500 and 2000 for the medium and hyper processors respectively, which will allow for bigger programs to be made, logically as processors upgrade.

My reasoning is that a higher limit for the hyper processor may increase performance, as bigger or efficient programs can be fitted into a single processor, instead of being separated and comm systems made. Also, not reducing the micro processor limit will keep existing programs valid.

**Comment by MatterNoise** [comment]
Yes!, This will greatly improve the processors since it will allow heavier things on those processors
