### ISSUE TITLE
Abandon on mobile

### ISSUE THREAD

**Issue by Andromeda-Galaxy29** [Anuken/Mindustry-Suggestions#4883]
### Describe what you would like changed, and why.

Add the abandon button to mobile pause menu. It's too difficult to find and access it currently.

### Describe the changes you want to propose. Include possible alternatives.

Add the abandon button to mobile pause menu

**Comment by camelStyleUser** [comment]
no?????its in sector info on mobile too
i just went and checked

**Comment by Lime712** [comment]
Truly

**Comment by Slotterleet** [comment]
No. It's in mobile too.
![Screenshot_20240220_151846](https://github.com/Anuken/Mindustry-Suggestions/assets/62336673/5b95d517-8daf-4472-bba9-374416159075)

**Comment by SITUVNgcd** [comment]
Click to "i", you will see!

**Comment by Andromeda-Galaxy29** [comment]
Put it in the pause menu then! How am I supposed to know that it's there
