### ISSUE TITLE
Overdriver

### ISSUE THREAD

**Issue by Floppy4** [Anuken/Mindustry-Suggestions#4884]
### Describe the content or mechanics you are proposing.

It's a mender that makes buildings faster instead of repairing them. Optionally uses silicon to boost range and efficiency.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Sometimes, you just wanna boost one thing or two. And the Overdrive projector would be practically overkill, apart from the fact that it would make that/those thing(s) faster, which may sometimes be overkill too. And sometimes you don't want to boost other stuff, like a drill so fast boosting it may clog everything up, which isn't good when you want other stuff on the conveyors and there's no space for more lines. And also put it right before the overdrive projector in the tech tree.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
BRUH just make more lines, downgrade some production, use plastanium conveyors or just deal with it bruh

**Comment by Lolnoizcool** [comment]
Support classes:
