### ISSUE TITLE
iOS / iPadOS Keyboard support

### ISSUE THREAD

**Issue by noantiq** [Anuken/Mindustry-Suggestions#4885]
### Describe the content or mechanics you are proposing.

Hi! I would really like to see keyboard and mouse control options for iOS. I played the game on PC and Android before and both "editions" let me control Mindustry with my keyboard and mouse. Then I bought it for my iPad yesterday which pretty much functions like a small laptop but sadly realized the version for iOS in particular has no keyboard and mouse control.

Is there a reason for this?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I use my iPad like a laptop with an external Keyboard and mouse. It would be really neat to be able to play Mindustry like I'm used to, the touch controls are somewhat of a hassle.

Oh and I just found https://trello.com/c/OIqZCJeS/589-fix-mobile-keyboard but I'm not entirely sure if that entails my request.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by alexlambson** [comment]
Would definitely save me some wrist pain
