### ISSUE TITLE
Support for rotatable output to logic displays

### ISSUE THREAD

**Issue by cardillan** [Anuken/Mindustry-Suggestions#4886]
### Describe the content or mechanics you are proposing.

I propose adding a new variant of the `draw` instruction for setting output rotation in degrees. The instruction would set the rotation for all subsequent draw operations, similarly to the way `draw color` or `draw stroke` set the color or line width of the following operations. The center of the rotation would correspond to the center of the logic display being used for output. Either arbitrary rotation, or rotation by multiples of 90 degrees could be supported - either of them would be useful.

Unless I misunderstood something, the Batch class, which is used to output graphic commands to logic displays, already has support for rotation. Hopefully the feature wouldn't be too difficult to implement.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature would allow to easily rotate graphical output of mlog programs. Achieving arbitrary rotation, even by multiples of 90 degrees, is way too complicated for most mlog programs, given the limited execution speeds and instruction space. Furthermore, unless a separate mechanism for text rotation is being considered, this would add support for vertical text printing to the printing mechanism already added for the upcoming Mindustry version.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
A more useful/generalized version of this instruction that I may consider implementing would manipulate the transform matrix of the batch, with scale/translation/rotation variants.

**Comment by cardillan** [comment]
So I could apply, say, rotation followed by scaling? That would be even more useful, of course. 👍

**Comment by cardillan** [comment]
https://github.com/Anuken/Mindustry/commit/e3b24ac9800436893df09a008972ffaa62470415
Wonderful, thanks! :)
