### ISSUE TITLE
Liquid bottle

### ISSUE THREAD

**Issue by VoidScript0** [Anuken/Mindustry-Suggestions#4887]
### Describe the content or mechanics you are proposing.

It can store 2 liquid units and can be caried by coveyors, also can be stacked and caried
There should be a machine to pour in to the bottle and pump out of the bottle
Also there should be a machine that makes the bottles
-void_script

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lolnoizcool** [comment]
why

**Comment by TagGamer555** [comment]
conduit with extra steps

**Comment by S0meM** [comment]
You would need 2 different machines for each liquid you bottle. This is rather pointless. This sounds like someone doesn't like making metaglass.
