### ISSUE TITLE
6.0 healer drone

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#489]
**Describe the content or mechanics you are proposing.**
Most 5.0 units have 6.0 equivalents. But there's one missing: healer drones. As of build 9641, there is no spirit repair drone in 6.0. 

The poly could be an upgrade from this new unit, with the mono moved into a new flying unit type. As a side effect, moving the mono would allow for a tier 2 miner drone. Also, this would let monos be a little less expensive in the early game while making healers more expensive.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We have builder drones, why not repair ones, too? They're super useful, not needing to place menders everywhere.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by D-player1** [comment]
Mega

**Comment by Anuken** [comment]
Mega can heal things, it just doesn't have the AI for it yet.
