### ISSUE TITLE
Multitouch gestures support on pc version

### ISSUE THREAD

**Issue by TheRealA77** [Anuken/Mindustry-Suggestions#4890]
### Describe the content or mechanics you are proposing.

I would love to be able to use my 2in1 at its maximum potential by being able to zoom using my fingers or to use the mobile ui mod along with these features to play the game on tablet mode.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be really cool for who owns a 2in1 to have this added functionality in the game. I barely know any games that do try to accommodate for 2in1 users. I think it would also affect steam deck users but idk exactly, i don't own one. Still, i would love for this game to have support for multitouch

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by A765-ALEX** [comment]
this seems relatively easy to do, considering you can alr use kbd+mouse on android
