### ISSUE TITLE
Start of erekir

### ISSUE THREAD

**Issue by Mindustryenjoyer** [Anuken/Mindustry-Suggestions#4896]
### Describe the content or mechanics you are proposing.

After you build the erekir second core, you are forced to wait for 2 minutes, but players who strategize like me, build defenses and mining before building the core, and i say for us we would need a skip button, so we dont need to wait for 2 minutes before the action.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Strategizing is in the heart of mindustry, So why not help the planners with it? And also, speedruns can be faster.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
just remove it, cause you should have at least one functioning breach and a few stells by the time you destroy the first core, and if you end up losing then you are either trolling or not qualified to play erekir
also the enemies don't come immediately after you destroy the core so there is time
and it would give a better impression of the difficulty.

**Comment by TagGamer555** [comment]
erekir is a very problematic planet, let's face it.

**Comment by jehosula** [comment]
> erekir is a very problematic planet, let's face it.

yeah but how is this relevant to this suggestion?
