### ISSUE TITLE
Some logic improvment

### ISSUE THREAD

**Issue by Mavment** [Anuken/Mindustry-Suggestions#4897]
### Describe the content or mechanics you are proposing.

Make units be able to fully locate buildings that are not in your team (right now ulocate command returns x, y and found but building stays null), also make ulocate be able to not only detect closest buildings, but also some further ones (make it work likely ubind, show futher and further buildings, and if reached furtherest, return to closest), (revolutionary one) ubind that binds unit with specific flag (for example make a command that inputs unitname and flag and binds this type of unit but only if it have specific flag) 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will let players do things such as better ai logic, smart item delievering and probably more

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
don't make logic more op
