### ISSUE TITLE
Mod download counter

### ISSUE THREAD

**Issue by Andromeda-Galaxy29** [Anuken/Mindustry-Suggestions#4898]
### Describe the content or mechanics you are proposing.

Add a download counter for mods so you can how many times it has been downloaded 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will be easier for mod developers and players to tell how popular the mod is. Not everyone does or can star a mod, so a download counter I think would be a great addition.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
this would require a server at least to receive mod add a download request and get mod download count request.
anuke isnt going to pay for servers for a free game

**Comment by Slotterleet** [comment]
Go to a GitHub repository, then Insights > Traffic.

**Comment by LixieWulf** [comment]
That tab only exists for the repository owner. Please check your information before trying to give advice.
