### ISSUE TITLE
Choosing the spawn position of flying enemies.

### ISSUE THREAD

**Issue by MikouZonata** [Anuken/Mindustry-Suggestions#49]
**Description**
Spawn Points in editor allow grounded units to spawn near the placed Spawn Point and flying units to enter the map from the edge on a variable offset. The offset depends on where the Spawn Point is placed and can cause flying units to come into the map at a very different point than the grounded units. The current system effectively allows a map designer to either set the spawn location for grounded units or flying units, not both. This makes picking the spawn location of enemies illogical and unpredictable as well as making it cumbersome to place resources and geometry that allows players to wall off both enemy types in a similar fashion. 
Spawn Point functionality should not dictate map design.

**Possible solutions**
- Flyers spawn at the same place as grounded units, using the same spawning animation.
- Flyers come in at the edge of the map closest to the Spawn Point directly above, below or to the side of the point.
- Flyers are given a seperate Flyer Spawn Point to be placed on the map by designers.

If nothing else a preview to show where flying units would spawn in the editor given the present Spawn Points would be great.

**Example**
![77091486-01615180-69df-11ea-8ed3-93ab79550024](https://user-images.githubusercontent.com/15729844/77096274-6896fa00-6a0f-11ea-8d66-f1224ee0b9c8.png)
Ground units will spawn out of the grey gates whereas flyers don't, making the west titanium and scrap deposits unnecesarely and unintentionally hard to take and defend.

**Comment by DeltaNedas** [comment]
+1

**Comment by adamcoding** [comment]
How do you set spawn points of ground enemies? 

I've made a map but there is no obvious way to set where enemies emerge. 

The editor has a search icon but this doesn't work either.

The terrain types is just a mass of icons as well.

**Comment by MikouZonata** [comment]
There's a ground tile which is just an "S" with which you choose ground spawn location. Air spawn location is then based off of that spot but is unpractical af, hence the issue.
