### ISSUE TITLE
Bridges, landing ships and raids.

### ISSUE THREAD

**Issue by EnganK** [Anuken/Mindustry-Suggestions#490]
**Describe the content or mechanics you are proposing.**
1) Maximum upgraded ships should be able to move ground units across the water (landing ships).
2) Logic screens of different sizes.
3) Campaign event: a raid on a captured sector.
4) Construction of bridges over the water for ground units.
5) Improve the generation of maps in the campaign.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1) For similar purposes, there is already a ship "Mega", but it can only lift two or three units at a time. I suggest adding a large landing ship for massive movement of units on water obstacles. The landing ship will be a large, flat ship that units can enter. After that, they will be able to move around the ship, but they will move while the ship itself is moving. At the same time, all their weapons and special abilities will continue to work.
2) It is not always convenient to use the existing 3 by 3 screen for your own purposes. For small indicators (small numbers or a warning about overheating of a remote reactor), a 1 by 1 screen with a resolution of 20 * 20 pixels is enough. 
3) The development of the captured sectors is sometimes boring. You just need to build more and more factories and sometimes improve the core. Therefore, you can diversify the gameplay by adding periodic attacks on the captured sectors, the fewer the number of others captured, the more frequent the attacks. The raid will consist of several strong waves with a small gap.
4) As a cheaper alternative to landing ships, you can use bridges across the water. But they can be destroyed by enemy aircraft, and enemy ground units can pass over them.
5) The maps from the old company were very diverse, each had its own peculiarity. However, the generated maps from Alpha 6.0 are similar to each other. In addition, there are not often narrow passages for building defenses.

Sorry for bad English, I used Google translator.
**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
You should split these 5 very different suggestions into 5 issues so they can be discussed and closed separately. It's unlikely for an "issue" as a whole to be implemented if it has many parts.

**Comment by Anuken** [comment]
1. This isn't going to happen, because ships collide with ground units and I don't see much use for it outside of very specific maps.
2. I don't think this is necessary right now.
3. This is already planned.
4. This won't be added. It isn't supported by the tile system.
5. Don't assume these maps are the final product, because they're not. I've mentioned this again and again: **the campaign is nowhere near done**.
