### ISSUE TITLE
Ammo unloader

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry-Suggestions#4900]
### Describe the content or mechanics you are proposing.

The ammo unloader would be used to move ammo from a turret to adjacent turrets wich the ammo type is compatible with. The ammo would keep the same damage but it could allow for some interesting things like making chains of cyclones with unloaders beetween them that then transport the ammo to a bunch of swarmers. The ammo cannot be obtained in item form, only moved beetween turrets by the unloader.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You could move ammo from lower firerate higher damage turrets to higher firerate turrets where that ammo does not have as high damage. this can make making lines of turrets easier to feed and can give interesting options.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
it would require changing how ammo works as turrets store ammo. not resources
and it would serpulo even more spammy that it already is

**Comment by Haznobrain** [comment]
> it would require changing how ammo works as turrets store ammo. not resources and it would serpulo even more spammy that it already is

it'd simplify turret supply lines and would make it interesting as you could give a ripple swarmer blast compound ammo or some shit, for funsies, for making interesting combinations of turrets and ammos!

**Comment by jehosula** [comment]
> > it would require changing how ammo works as turrets store ammo. not resources and it would serpulo even more spammy that it already is
> 
> it'd simplify turret supply lines and would make it interesting as you could give a ripple swarmer blast compound ammo or some shit, for funsies, for making interesting combinations of turrets and ammos!

turret lines SHOULD be difficult to set up properly it's a way to avoind making the game too easy
you can already mix ammo and turrets by adding multiple different ammo types in one belt and just placing multiple turrets on the supply like respectively

**Comment by Haznobrain** [comment]
> > > it would require changing how ammo works as turrets store ammo. not resources and it would serpulo even more spammy that it already is
> > 
> > 
> > it'd simplify turret supply lines and would make it interesting as you could give a ripple swarmer blast compound ammo or some shit, for funsies, for making interesting combinations of turrets and ammos!
> 
> turret lines SHOULD be difficult to set up properly it's a way to avoind making the game too easy you can already mix ammo and turrets by adding multiple different ammo types in one belt and just placing multiple turrets on the supply like respectively

i meant "mixing ammo" by for exemple using surge ammo from a cyclone in swarmers, wich have higher fire rate but lower damage surge ammo.

**Comment by jehosula** [comment]
it's already possible to do this just place multiple ammo types in one belt

**Comment by jehosula** [comment]
just place both turrets what's wrong?

**Comment by Haznobrain** [comment]
> just place both turrets what's wrong?

cyclone has higher damage surge ammo but slightly less fire rate and less space efficient. Swarmer has lower surge ammo damage but higher fire rate and takes up less space.

**Comment by rylid-umil** [comment]
i had a brain tumor trying to comprehend your point with this

**Comment by jehosula** [comment]
> cyclone has higher damage surge ammo but slightly less fire rate and less space efficient. Swarmer has lower surge ammo damage but higher fire rate and takes up less space.

there is nothing stopping you from doing this still
there is no point besides making things easier (lowers skill cap) (guess your name is actually correct then (joking))

![Mindustry 3_23_2024 11_31_25 AM](https://github.com/Anuken/Mindustry-Suggestions/assets/118267162/a5aa27c1-fc2a-41f3-819c-2abb71cb8ef2)
