### ISSUE TITLE
Processor Unit-Pathfind Is very finicky to use. I propose a solution.

### ISSUE THREAD

**Issue by fruitmeister101** [Anuken/Mindustry-Suggestions#4901]
### Describe the content or mechanics you are proposing.

I am Specifically Speaking of the  Unit Control - Pathfind (X,Y). 
If you want a grounded unit to find (via Unit - Locate), say, an enemy turret and walk over to it, You cannot feed in the exact coordinates of the found structure. Because Obviously there isn't a path to the inside of a block... But this behavior already exists for the Unit Control - AutoPathfind, as it tries to get the the Center of the Enemy Base by the path of 'least' resistance, and likewise for enemy units.
My proposal - Change the Unit Control - Pathfind (X,Y) command to still try to find a path to the closest walkable space if the space selected is occupied, just like the AutoPathfind or enemy units do.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Having a way to make ground / water units viable for Manual Logistical Assault would make me very happy. Thanks
(yes I know the Nova path can fly and the Walker/Crawler path can leg over stuff... I want more universal control over my units)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
logic is already super op, it should be limited

**Comment by fruitmeister101** [comment]
But then the PathFind is very hard to use...
As it is, It's useless to me, as though it doesn't even exist... and that
makes me sad
-Samuel Herron-

**Comment by jehosula** [comment]
it being useless is a good thing if it's not world logic
and why quote your email?

**Comment by TagGamer555** [comment]
nuh uh

**Comment by jehosula** [comment]
> nuh uh

?

**Comment by Mythril382** [comment]
Just do the math.
