### ISSUE TITLE
Buff pulveriser speed to 2x it's original value

### ISSUE THREAD

**Issue by DestroyThing** [Anuken/Mindustry-Suggestions#4902]
### Describe what you would like changed, and why.

Pulverisers are awkward to use in an average setting, They're 1x1, and only convert a 7th of a titanium conveyor. For your average sand needs, that's far from ideal. The solution is either buffing them, or adding a new 2x2/3x3 pulveriser entirely to design around later game sand needs. 

### Describe the changes you want to propose. Include possible alternatives.

This would allow players to have more freedom for designing sandless maps that rely on scrap. The only way to currently convert a lot of scrap into sand is through an extremely packed schematic, which isn't something the average player might have

**Comment by jehosula** [comment]
yes

**Comment by TagGamer555** [comment]
no

**Comment by jehosula** [comment]
> no

why?

**Comment by TagGamer555** [comment]
Because that would make drills on sand useless
And makes scrap maps easier
> > no
> 
> why?

**Comment by jehosula** [comment]
> Because that would make drills on sand useless And makes scrap maps easier

currently scrap maps are just pain caus you have to rely on one factory block the whole time
and drills on sand are still better it's not gonna turn 3 scrap into 4 sand every 0.2 seconds for 120 power/s or something it WILL be worse than drills on sand it's just that scrap to sand currently sucks and lacks progression it'll never be any better under normal circumstances

**Comment by jehosula** [comment]
> just install mods then

you might as well say that to literally any suggestion if you make a mod for it, no point in vanilla existing
but mods should add to the already as good as it can be game, not replace it
it should be in vanilla, we should not need mods to make good scrap only maps
