### ISSUE TITLE
No More cancel button

### ISSUE THREAD

**Issue by ironfprcefeild** [Anuken/Mindustry-Suggestions#4903]
### Describe the content or mechanics you are proposing.

Im a little optimization nerd and I love to get lost in building big processing plants or complex projects. The most frustrating experience ive ever had playing this game is after 15 minutes of designating spots to build on erekir, having to cancel it all to move an Avert to protect  some vital bores.

I suggest replacing the cancel button when building with a command button, just switch immediately to commanding. The drone wont build until you hit build. This also lets you remove  the building UI while commanding. 

In the spot the UI clears up, put a cancel build button. Allowing you erase your designations after entering command mode.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

By doing what I suggest you signifigantly increase player retention by removing the most frustrating and bumpy part of the experience. Its honestly the most bang for your buck change I can imagine. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
yeah mobile struggles

**Comment by SITUVNgcd** [comment]
You can use my mod for unit control. Control while building and turn off command mode without cancel building. Only for mobile.
Search my name in Mod browser or use this url: https://github.com/SITUVNgcd/MindustryModTest
