### ISSUE TITLE
World logic can control the display of multiple Marker IDs at the same time

### ISSUE THREAD

**Issue by DocCoVoDanh** [Anuken/Mindustry-Suggestions#4905]
### Describe what you would like changed, and why.

Currently on the test version I have tried using world logic to display 2 ID Markers at the same time but it does not work, each world logic can only be controlled to display 1 unique ID at a time. If you control 2 IDs, one ID will disappear

### Describe the changes you want to propose. Include possible alternatives.

i wish to be able to display multiple IDs at the same time with just one world logic if it is already possible to do so just i don't know how to do it can someone help me

**Comment by camelStyleUser** [comment]
what do you mean only one marker while they have different ids.
gd map has a lot of markers and it works

**Comment by DocCoVoDanh** [comment]
> ý bạn là chỉ có một điểm đánh dấu trong khi chúng có các id khác nhau. Bản đồ gd có rất nhiều điểm đánh dấu và nó hoạt động

Multiple different IDs can be displayed at the same time but require a corresponding number of world logic blocks. For example, if you want to display 100 IDs at once, you must have 100 world logic blocks to run 100 IDs. That is, each World Logic Block can only display 1 ID at the same time, 1 World Logic cannot display 2 or more IDs at the same time.

**Comment by SITUVNgcd** [comment]
@DocCoVoDanh Maybe you're mis-using, i can make 1 world processor handle more than one Marker at same time.

**Comment by camelStyleUser** [comment]
> > ý bạn là chỉ có một điểm đánh dấu trong khi chúng có các id khác nhau. Bản đồ gd có rất nhiều điểm đánh dấu và nó hoạt động
> 
> Multiple different IDs can be displayed at the same time but require a corresponding number of world logic blocks. For example, if you want to display 100 IDs at once, you must have 100 world logic blocks to run 100 IDs. That is, each World Logic Block can only display 1 ID at the same time, 1 World Logic cannot display 2 or more IDs at the same time. It is not possible to display 100 IDs at the same time with only 1 world logic block

no?
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/124447863/d9012cb9-0638-4812-bf5b-73fb54d01dc8)
```makemarker shape 0 @thisx @thisy 0
makemarker shape 1 @thisx @thisy 0
setmarker rotation 0 45 0 0
setmarker radius 0 8 0 0
setmarker radius 1 12 0 0
setmarker shape 0 45 1 1
setmarker color 0 %ff7fd9 0 0
setmarker color 1 %7fff8d 0 0
```

**Comment by DocCoVoDanh** [comment]
> > > lưu ý rằng bạn chỉ có một dấu hiệu đánh dấu khi chúng có các id khác nhau. Bản đồ gd có rất nhiều dấu hiệu và nó hoạt động
> > 
> > 
> > Nhiều ID khác nhau có thể được hiển thị cùng lúc nhưng yêu cầu số lượng khối logic thế giới tương ứng. Ví dụ: nếu bạn muốn hiển thị 100 ID cùng một lúc, bạn phải có 100 khối logic thế giới để chạy 100 ID. Tức là mỗi World Logic Block chỉ có thể hiển thị 1 ID cùng lúc, 1 World Logic không thể hiển thị 2 ID trở lên cùng lúc. Không thể hiển thị 100 ID cùng lúc chỉ với 1 khối logic thế giới
> 
> KHÔNG? ![hình ảnh](https://private-user-images.githubusercontent.com/124447863/311514702-d9012cb9-0638-4812-bf5b-73fb54d01dc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzkyOTcsIm5iZiI6MTcxMDA3ODk5NywicGF0aCI6Ii8xMjQ0NDc4NjMvMzExNTE0NzAyLWQ5MDEyY2I5LTA2MzgtNDgxMi1iZjViLTczZmI1NGQwMWRjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxMzU2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDQ2YzM3MDE2OGM1NjcwZjc0ZmVhOThmNWRlNzMzMmVhZjYzOWVhNmY5OWQ4YTRhYjQ0YjJmMjFhZjBkNzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zrna5YDvE9pH4XHOd7q45IPR4p-kL84ZVq1sv5LNX8U)
> 
> ```
> makemarker shape 1 @thisx @thisy 0
> setmarker rotation 0 45 0 0
> setmarker radius 0 8 0 0
> setmarker radius 1 12 0 0
> setmarker shape 0 45 1 1
> setmarker color 0 %ff7fd9 0 0
> setmarker color 1 %7fff8d 0 0
> ```

thank
