### ISSUE TITLE
Better Experience For Custom Games

### ISSUE THREAD

**Issue by hamabi314159** [Anuken/Mindustry-Suggestions#4907]
### Describe what you would like changed, and why.

In Sandbox mode, _Alpha_, _Beta_, and _Gamma_ **can** be commanded, while _Evoke_, _Incite_, and _Emanate_ **can't**.

In _\<Any\>_ planet, _Large Constructor_ **Can** fabricate _Serpulo_ structures, while _Constructor_ **Can't**.

It just seems a bit weird that similar items don't share the same rule..

### Describe the changes you want to propose. Include possible alternatives.

Hope that _Evoke_, _Incite_, and _Emanate_ can be commanded.
Hope that _Constructor_ can fabricate _Serpulo structures

**Comment by SunkyMP3G** [comment]
> In _<Any>_ planet, _Large Constructor_ **Can** fabricate _Serpulo_ structures, while _Constructor_ **Can't**.

Constructor has its own list of buildable things, while a large constructor hasn't, so it can build every blocks below 3x3
Here's the code of the constructor
```
 //TODO expand this list
            filter = Seq.with(Blocks.tungstenWallLarge, Blocks.berylliumWallLarge, Blocks.carbideWallLarge, Blocks.reinforcedSurgeWallLarge, Blocks.reinforcedLiquidContainer, Blocks.reinforcedContainer, Blocks.beamNode);
```
