### ISSUE TITLE
Purification Tower

### ISSUE THREAD

**Issue by Trinity-66** [Anuken/Mindustry-Suggestions#4908]
### Describe the content or mechanics you are proposing.

##Purification Tower
Significantly slows the progression of Neoplasm structures in range, and slightly slows Neoplasm units. Consumes moderate amounts of ozone and power, optionally consumes cyanogen to increase radius.
Build time: 8s
Build cost: 300 Beryllium, 200 Silicon, 150 Tungsten, 25 Carbide
Radius: 10m

### Input:
12 Ozone /s
700 power units /s

### Optional Booster(s):
4 Cyanogen /s
Radius increase: +6m

(All numbers are changeable at Anuke's discretion.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I saw someone mention a "disinfectant tower" in the Discord's development chat when a video of a Neoplasm spitting enemy was posted, and it inspired this suggestion! The Purification Tower would make dealing with Neoplasm structures more bearable, but requires multiple inputs to run effectively and is still susceptible to Neoplasm units. All it's supposed to do is make defending your base a little easier, by removing the running cost of having turrets constantly destroying new veins.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TagGamer555** [comment]
just make some kind of wave but for erekir since you want erekir to be boring
this suggestion is an absolute overkill

**Comment by Trinity-66** [comment]
> just make some kind of wave but for erekir since you want erekir to be boring this suggestion is an absolute overkill
if you have any actual improvements that you'd make to this (and not just "remove it") then please tell me those instead :)

> I am saying that anuke does not care about fun, only about balance erekir is hard and balanced, but not fun
Are you trolling or smth XD
