### ISSUE TITLE
ThermalGenerator works on overlay layer (ores, etc.)

### ISSUE THREAD

**Issue by TagGamer555** [Anuken/Mindustry-Suggestions#4909]
### Describe the content or mechanics you are proposing.

attribute from overlay tile such as an ore should count towards the attribute of the ThermalGenerator
so for example I have ore-coal.hjson have `burnable: 1.32` in `attributes: {}` and then I plug the `burnable` in the `type: ThermalGenerator` and it does not work

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

players can make more unique things for their non-java Mindustry mods (like myself)
it also adds flexibility to already limited hjson and json

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TagGamer555** [comment]
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/69044271/5acaaafc-67d6-490c-b8cf-495ae1cb0d74)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/69044271/00b9712b-caee-4395-9606-367e5ce7a597)

**Comment by Haznobrain** [comment]
...
you don't understand how it works do you
THE ORE TILES ARE BURNABLE, NOT HOT

**Comment by TagGamer555** [comment]
do you possess a human brain
> ... you don't understand how it works do you THE ORE TILES ARE BURNABLE, NOT HOT
