### ISSUE TITLE
Impact and Eruption Buffed with Boosters

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry-Suggestions#4913]
### Describe what you would like changed, and why.

_[A revised continuation of #4824]_
As it stands, the current ground drills aren't as effective as their bore counterparts...
The Eruption Drill even at max coverage still has less throughoutput (i/s) than Large Plasma Bore (LPB) and the Impact Drill gets reduced to a steppingstone against LPB. The drills are only used when it is forced via limited wall ores.

### Current State:
**Impact Drills**, although could work well ish in Pre Oxidiation Chamber Campaign Maps since the tungsten demand is low, are unable to keep up and provide enough materials that allows the player to do something in the Impact Drill to LPB transition, since it is better off to rush into Nitrogen Boosted LPB than have fun with T1-Merui/T2 Units, or even try out the Transport Tech introduced in Split. The difference is high, with only 1.33 i/s, with maybe 4-5 tung spots, while a single Nitro-LPB can be comparable against it. It isn't fun to wait, even if tung ore is common, it all depends on vent count for energy and water.

After Nitro-LPB is done, the beryllium role for Impact Drills should still be maintainable here. It doesn't hurt and can be reliable ish enough to be used in schematics, compared to just having 4 beryllium hyrdro-bores on different terrain.

Thus...
#### The Main Goal for Impact Drills:
- Make these able to support Non-Oxide Tung Tech (Merui, T2, Transport Tech)
- Carry enough tungsten into Oxide Tier to be able to build the initial Oxidation Cambers, CCC, and basal LPB, making Nitrogen-LPB not a dependency.
- Have a convenience/reliable role for being a good beryllium provider, if somehow needed, in Post Nitro-LPB.

**Eruption Drills**, while having some of that convenience factor of single input of relatively easy to acquire hydrogen, doesn't provide enough of a pull to be used because Nitro-LPB can consistently provide more throughoutput. 4.16 i/s is absurdly low for the rare complete 25 ore tiles, compared to Nitro-LPB's 4.5 i/s. Eruption Drills should not have this simplicity niche, rather, as a thor tech drill, it should be able to be a good provider of raw materials as the game reaches lategame.

The game also lacks an endgame drill which is able to increase the potential of an area maximally to handle Carbide's Tungsten Consumption and Phase's Thorium Consumption at a limited cost. Doesn't hurt to give it some endgame potential.

#### The Main Goal for Eruption Drills:
- Fulfill as a Thor Tech Drill in giving enough throughoutput.
- [Optional] Be the endgame provider of materials using Carbide/Post-Carbide Tech.

### Overall Expected Result:
- Pre-Oxide gameplay being more fun to play in and reducing tech up as a requirement.
- Post Nitro-LPB gameplay allowing to have some remnants of the Impact Drill by being a beryllium provider.
- Thorium Tech being significant in production with eruption.
- Post-Carb/Carbide Tech allowing an endgame option for production.

### Acknowledgement
As a little side note, thank you to the #balancing lads at the main Mindustry Server for making this possible. The feedback, discussions, and idea making by many members of this community were fun to be in.

[Sire starting the initial discussion on Eruption Buff, then way lower down Impact Starts getting involved sooner or later](https://discord.com/channels/391020510269669376/813425645518061678/1189073462963220550)

Thank you to BalaM314 for helping on the PR, as I'm still inexperienced in Java...
Thank you to mwm, providing the primary discussion and design philosophies I've undergone here.
and to Anuke for making a game that I still loved while playing, I wouldn't be making such a large essay if I hated the game lol.

## Main Proposal
[Using the current PR stats] [https://github.com/Anuken/Mindustry/pull/9517]

#### Ozone Booster
- 1.75x Multiplier for 3 lu/s Ozone

[tung: 1.33 i/s -> to 2.33 i/s]
[beryll: 2.66 i/s -> 4.55 i/s (yes beryl multi has changed, check below)]
Rather than going for a base buff, I've used an ozone booster for a couple of reasons:
- Having teching up as a choice between ozone for Oxidiation Chambers or For More Initial Tungsten
- Using an underutilized gas in Pre-Oxide, since only usage there is just Unit Repair
- Ozone to position the boost in the tech where it matters, pre Nitro-LPB (although it is a possible alternative, check below)

I've used 3/s to make sure in 2 Impact - 1 Electro setups to make boosting more of a challenge and less braindead, hopefully to legitimize the next change. Boost the highest output out of the two! Also, can give potential to a tech up with an additional Oxidation Chamber + 1 Electro to have 2 Impacts at full uptime. This can also give incentive to the interconnected nature of Electro which can create long connections between Item Extraction, Item Crafters, and Unit Factories. (Hydro: Extraction + Unit Production, and Ozone: Extraction, Crafters, and Defense)

#### Water Consumption Change
- 12 lu/s to 10 lu/s

Whatever the additional 2 lu/s is for... whether it might be to give some complications to the impact drill, or to have a more complex ratio for drill : vent; hopefully the Ozone Boost can fulfill that role. Two Painful Logistics for Impact is way too much while playtesting (especially in Marsh, the water complications was nuts)

#### Beryllium Multiplier Nerf
- 2.5x to 1.95x [3.33 i/s -> 2.6 i/s]

Making sure the boost reaches the desired barely above 4.55 i/s in being viable against LPB, I had to nerf the multiplier since the Boost Multiplier applies to all. Also to not go too much since Eruption Beryll Multiplier is coupled here as I am following that the ore efficiency should not be less for eruption.

#### Base Speed Increase
- 4.16 i/s -> 5.33 i/s [Tung/Thor]

High Priority to do... Picked this number since it feels like it had enough drawback, it takes only 4 ground ores to be removed to match with LPB. It should be good enough while not surpassing LPB too much and give mapmakers something to work with/limit on. This might be rewarding enough from its high thorium and silicon cost, and still has that less oxide expensive quirk in map loadouts (although saving up thor is a need). This should incentivize players in accelerated gamemodes (pvp, speedrunned attack) a nice option to work with, while slower-paced gamemode players (survival, campaign styled attack) more bang for this drill, since maximizing item extraction is going to happen eventually while waiting down those timers.

#### Cyanogen Booster
- 2x multiplier for 3 lu/s Cyanogen

[Tung/Thor: 5.33 i/s -> 10.66 i/s]
[Beryll: 7.2 i/s -> 14.4 i/s (yes, beryll multi also got nerfed, check below)]

Oriented for endgame, which means slow-paced gamemodes (survival, campaign-attack), The boost is limiting to make sure it's under boosted state isn't useless and at the correct tech level on when/where to get; the limitation helps map makers to control extraction well since it uses arkycite and graphite. It is difficult but should hopefully be rewarding on being the highest throughoutput block among all the extractors. Also, partial heat synergy with Flux (33% flux with 3 cyano-eruption drills, 66% and 2, or 100% and 1), and tank assembler synergy. Can also feed into cyano sublimates or shockwave towers. (Making Cyano Tech complete)

#### Beryllium Multiplier Nerf
- 2.5x -> 1.35x [10.416 i/s to 7.2 i/s (accounting from base speed buff]

Same rationale for the impact drill, but this time limiting to be under the 15 i/s duct speeds. If allowed, I would keep the 10.416 i/s but seems to be off the rails production with 20.833 i/s. Also due to how the game dumps items.

*Side Note: Due to how the game dumps stuff, you may need a duct unloader or container, or two sets of duct bridges/surge going out from the eruption drill (not one into the other then output), since it the ducts can't handle the input. Might be a PR limitation or my own coding skill issue*

### Possible Alternatives

Impact Nitro 
2.25x for 2/s nitro
(1.33 i/s to 3/s tung)
(2 i/s to 4.5 i/s beryl)
2.5x -> 1.5x beryllium multiplier
(3.33 i/s -> 2 i/s)

Same rough structure/reasoning for the beryll change as ozone boost. Although I discontinued this since it was better to address the current issues of progression rather than making it good Post-Nitro-LPB.

Nitro Eruption?
Nope, LPB 2.0 feel as having the same item profile, and makes the unboosted counterpart, well never going to be used. It doesn't add additional depth as it repeats the same limitations as LPB.

##### Basin, Realized It wouldn't impact Pre-Oxide Maps (power as the main limiter) but it does give tungsten ready for further progression
![Screenshot 2024-03-17 173527](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/933cebce-be9c-4637-ad8d-f3853ec7bc26)

##### Marsh Testing With 10 lu/s and ozone boost
![Screenshot 2024-02-25 101407](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/23a2e40a-7014-4f9a-a1b6-bad52c7b2aa4)

##### Siege (Before I nerfed the cyano from 1.5 to 3, felt way too easy when near perfect conditions) Perfect Place for Cyano Boost, and demonstrates that unboosted will still be used
![Screenshot 2024-03-02 234310](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/6af96ecd-f6b4-4e75-8122-443a05ee53a6)

##### Siege, Cyano Sharing with Flux! (One Eruption was decoupled)
![Screenshot 2024-03-04 223220](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/447e4cb1-5ef7-4176-b999-819239bc618e)

##### Stronghold, didn't find a lot of eruption drill opportunities (only later on, but a bit too late), but beryllium impact being nice
![Screenshot 2024-03-17 174300](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/b7b95ad7-6922-4e3e-a536-a1604eb3c5a5)

##### Custom Map (erekir attack map by mehcanical fish) painful on how slow the map is, but demo on flux + eruption drills. Limited arkycite though meant the flux was really volitile
![Screenshot 2024-03-17 175052](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/5e0f5c41-2744-4d42-9f71-7b23f902da9a)

##### Domain (non-campaign), more cyano-eruption setup.
![Screenshot 2024-03-17 175544](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/1abec2e1-0729-41a8-978f-c73069e60e3b)

#### Schematic Testing

![Erekir-Testing-1](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/eb6dce5b-e2a7-4536-a111-8e47e88e466d)

##### 85% Effeciency ae
![Erekir-Testing-3_Stell-Production](https://github.com/Anuken/Mindustry-Suggestions/assets/80511312/82b4cecf-1d3e-47d7-b38c-f75fd0625144)

*Note: I still suck somewhat at designing*

**Comment by jehosula** [comment]
> Basin, Realized It wouldn't impact Pre-Oxide Maps (power as the main limiter) but it does give tungsten ready for further progression

it does save power 60 for boost and 120 for a new drill at the very best case scenario for new impact 
but more realistically you would have sole ozone lying around and more impacts would cover less tiles good suggestion all around

**Comment by SomeonesShade** [comment]
> > Basin, Realized It wouldn't impact Pre-Oxide Maps (power as the main limiter) but it does give tungsten ready for further progression
> 
> it does save power 60 for boost and 120 for a new drill at the very best case scenario for new impact but more realistically you would have sole ozone lying around and more impacts would cover less tiles good suggestion all around

It more on, you can't really use all of the tungsten for unit production, since the bottle neck is on the energy form the vents. But yeah there is some variation with ore concentration per drill stuff that affects on how much of a power save is it.

Thanks (replying to the last phrase)

**Comment by jehosula** [comment]
sorry if my bad wording confused you, what i was ozone boosting often saves even more power and heck even water cause you need hydrogen more
it WOULD have an impact on pre oxide maps like basin if played well
