### ISSUE TITLE
Add config to drills / laser-drills sensor

### ISSUE THREAD

**Issue by hsaturn** [Anuken/Mindustry-Suggestions#4916]
### Describe the content or mechanics you are proposing.

1 / Add the type of resource gathered by a drill in the config sensor. Yet, we get null:
``` js
sensor config drill1 @config
print config
printFlush message1
```

2 / Add some other sensors (btw)
I saw that those values are null even if they could have sense:

- totalItems -> items pending (not sent through conveyors)
- itemCapacity -> max pending items
- mining -> drill stopped (because full)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I wrote some logic code that can enable or disable factories when amount in core is too low.
The core amount is sent very far through mem cells.
This cannot work for drills because a drill can gather lead copper titanium etc...

Note: we even could be allowed to change the config of the drill when the drill is built on top of more than one resource.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Scarfman1** [comment]
I would apriciate to Sensor the config of drills
