### ISSUE TITLE
Logic sensor for core items

### ISSUE THREAD

**Issue by TagGamer555** [Anuken/Mindustry-Suggestions#4917]
### Describe the content or mechanics you are proposing.

Logic sensor instruction for reading the resources available in the core

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More cool logic will be possible

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
You can already do that. Just sense `@item` from the core.

**Comment by TagGamer555** [comment]
> You can already do that. Just sense `@item` from the core.
Last time I tried it didn't work, but I'll try it again

**Comment by S0meM** [comment]
There is probably just something wrong with your logic. This has worked for years.
