### ISSUE TITLE
The mechanics of dissipating excess energy

### ISSUE THREAD

**Issue by AlexandrYaw** [Anuken/Mindustry-Suggestions#4919]
### Describe the content or mechanics you are proposing.

Currently, excess energy in the game simply gets lost. In real life, we either reduce energy production, discharge it into reservoirs, or use cooling towers. The idea is to add radiators for lower levels and cooling towers for higher levels. Power nodes can act as low-power radiators. Additionally, a block can be created to be placed on water and discharge energy by heating it. The effectiveness of this block will depend on the area or volume of the reservoir. And the efficiency of the radiator and cooling tower can depend on the biome (higher efficiency in colder biomes, lower in warmer ones) and weather conditions (increased efficiency in windy conditions, decreased efficiency during fiery storms or tornadoes). To connect to the radiator, you just need to transfer energy, and for the cooling tower, energy and water. In the case of excess energy with nowhere to go, power nodes will start heating up, and after exceeding the critical temperature, they will take damage.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Introducing mechanisms for managing excess energy within the game will greatly enhance its realism and depth. By incorporating radiators for lower levels and cooling towers for higher levels, players will have more strategic options for handling surplus energy production. This addition not only adds a layer of complexity to gameplay but also provides players with more control over their energy systems, encouraging thoughtful decision-making and resource management.

Furthermore, the inclusion of power nodes as low-power radiators and the introduction of a block that discharges energy through water heating adds diversity to the gameplay mechanics. Players will need to consider factors such as the size of reservoirs and the efficiency of cooling methods, adding an additional layer of strategy to their energy management.

The consequence of excess energy leading to damage if not properly managed introduces an element of risk and consequence, further deepening the gameplay experience. Players will need to balance energy production with the risk of potential damage, adding tension and challenge to the game.

Overall, these proposed additions will not only improve the realism of the game's energy systems but also provide players with more meaningful choices and challenges to overcome, enhancing the overall gameplay experience.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AlexandrYaw** [comment]
> > реалізм
> 
> Я не бачив літаків, які літають без палива в реальному житті

I didn't say that this game is realistic or that this mechanic will make it realistic. I'm just saying that this mechanic will add realism, thereby adding depth to this game.

**Comment by jehosula** [comment]
who gives a shi about realism where an eclipse can fly with a single thruster and shoot forever all resources are infinite and enemies can just spawn forever in survival

**Comment by AlexandrYaw** [comment]
> кому байдуже про реалізм, де затемнення може літати з одним двигуном і стріляти вічно, усі ресурси безмежні, а вороги можуть просто народжуватися вічно у виживанні

This mechanic isn't needed to make the game realistic. Instead, it will increase the number of management levels, thus making the game even more engaging. The fact that it will add a touch of realism is a side effect. Moreover, where else to draw inspiration from if not reality, thereby infusing fragments of it into the game.

**Comment by Haznobrain** [comment]
with the way it's written it almost feels like an ai prompt
still, shit idea nonetheless. I don't wanna have to care about my blocks overheating or shit.

**Comment by AlexandrYaw** [comment]
> > This mechanic isn't needed to make the game realistic. Instead, it will increase the number of management levels, thus making the game even more engaging. The fact that it will add a touch of realism is a side effect. Moreover, where else to draw inspiration from if not reality, thereby infusing fragments of it into the game.
> 
> honestly it would be kinda annoying to have to not produce excess mindustry has always been about producing enough and there being almost no producing too much this would just make the game annoying when you have to manage production to avoid producing too much rather than producing enough

In the game, I often maintained a reserve of +10k energy. And I've seen many others do the same on YouTube. There's no need to manage this manually. Let's suppose the balance could be as follows:

Power Nodes - 10 energy
Large Power Nodes - 30 energy
Radiators - 100 energy
Water Extractor - 1 water cell / 10 energy
Cooling Tower - 2000 energy
Now, if you want an energy surplus of +10k, you just place 5 cooling towers. And that's all you need to do.

**Comment by AlexandrYaw** [comment]
Caught me! I used GPT to translate into English as well as to formulate it into readable text.

> with the way it's written it almost feels like an ai prompt still, shit idea nonetheless. I don't wanna have to care about my blocks overheating or shit.

Caught me! I used GPT to translate into English as well as to formulate it into readable text.

**Comment by Haznobrain** [comment]
> Caught me! I used GPT to translate into English as well as to formulate it into readable text.
> 
> > with the way it's written it almost feels like an ai prompt still, shit idea nonetheless. I don't wanna have to care about my blocks overheating or shit.
> 
> Caught me! I used GPT to translate into English as well as to formulate it into readable text.

MY FUCKING GOD
CLOSE THIS SUGGESTION NOW YOU DUMB ATTENTION STARVED CLOUT CHASING JERK

**Comment by rylid-umil** [comment]
> > This mechanic isn't needed to make the game realistic. Instead, it will increase the number of management levels, thus making the game even more engaging. The fact that it will add a touch of realism is a side effect. Moreover, where else to draw inspiration from if not reality, thereby infusing fragments of it into the game.
> 
> honestly it would be kinda annoying to have to not produce excess mindustry has always been about producing enough and there being almost no producing too much this would just make the game annoying when you have to manage production to avoid producing too much rather than producing enough

I think this should be a togglable option in game settings, that's off by default. That way we can both play with it at times but also with normal mindustry

**Comment by S0meM** [comment]
Mindustry needs to be fun for everyone, including beginners. I don't think this is the way to go. Also, what is your point? At first, you said it would be a new level of management, to add more challenge to the game.
>This addition not only adds a layer of complexity to gameplay but also provides players with more control over their energy systems, encouraging thoughtful decision-making and resource management.
But then you said that it would be easy and pose no challenge.
> Now, if you want an energy surplus of +10k, you just place 5 cooling towers. And that's all you need to do.
You are saying that you want a new mechanic both because it adds a new challenge and then you argue that it is not going to be annoying because it poses little challenge. If there is no point in the mechanic, then don't add it.

**Comment by AlexandrYaw** [comment]
> Mindustry needs to be fun for everyone, including beginners. I don't think this is the way to go. Also, what is your point? At first, you said it would be a new level of management, to add more challenge to the game.
> 
> > This addition not only adds a layer of complexity to gameplay but also provides players with more control over their energy systems, encouraging thoughtful decision-making and resource management.
> 
> But then you said that it would be easy and pose no challenge.
> 
> > Now, if you want an energy surplus of +10k, you just place 5 cooling towers. And that's all you need to do.
> 
> You are saying that you want a new mechanic both because it adds a new challenge and then you argue that it is not going to be annoying because it poses little challenge. If there is no point in the mechanic, then don't add it.

I mean that this mechanic will add some difficulty, but it's not inherently very complicated.
