### ISSUE TITLE
join via claj link

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#4920]
### Describe the content or mechanics you are proposing.

a way to join games by copying a link after hosting a game and then pasting it to join a game 
pretty much the same as scheme size's join via CLaJ link feature

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it's a super simple way for anyone to join anyone else and it's super quick to setup the only issue is that it's a mod but it can be made even more simple if it was a vanilla feature i really don't have much to say about this because it's kind of a no brainer and super simple

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
This requires servers which are paid. The game is free, anuke isnt going to pay for servers

**Comment by jehosula** [comment]
> This requires servers which are paid. The game is free, anuke isnt going to pay for servers

the scheme size mod uses servers? (kind assumed it doesn't for some reason) also ios and steam versions of mindustry are paid and you can donate to anuke

**Comment by itcannotbe** [comment]
ThIs Is A gReAt IdEa.

~Once you ignore all infrastructure related cost to make such a system functional~

**Comment by camelStyleUser** [comment]
> > This requires servers which are paid. The game is free, anuke isnt going to pay for servers
> 
> the scheme size mod uses servers? (kind assumed it doesn't for some reason) also ios and steam versions of mindustry are paid and you can donate to anuke

yes it does use servers.donations are not sustainable.steam is pretty useless.
