### ISSUE TITLE
LightningBullet parameter in Wall block class

### ISSUE THREAD

**Issue by rylid-umil** [Anuken/Mindustry-Suggestions#4921]
### Describe the content or mechanics you are proposing.

A "LightningBullet" parameter in the Wall block class. For default, it spawns normal lightning, but if it is changed it spawns a new bullet instead of the pre-defined lightning.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will open new possibilites for mods and maybe part of the future updates

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Haznobrain** [comment]
i think this is amazing and as a modder myself this should be done
