### ISSUE TITLE
Variated Vents and a lot more

### ISSUE THREAD

**Issue by N4H4N** [Anuken/Mindustry-Suggestions#4924]
### Describe the content or mechanics you are proposing.

Adding variant of vent from 2x2 to 5x5. The efficiency of each biome is slightly different. this is also come with new building for each size. the vent efficiency also different at each biome. The size can be costumized using dynamite (meaning new factory that made blast-compound or ozone based stuff/bomb). --- small idea, like titan (or just use titan) but this thing shot ozone bomb that explode or cyanogen bomb that spread fire like molotov giving burning effect, making it good for a swarm of unit, same as using thorium.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Have more variant size of vent and with item that meant to be projectiles would add slight complexity as the player need to use the right block and can defend using literally a bomb

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Leo-MathGuy** [comment]
Maybe just a 3x3 original vent and a 5x5 vent:

* A building on top of vents, that when supplied with 1000 ozone explodes and replaces the vent with a 5x5 vent
* 5x5 vents can be harvested with a Big Vent Condenser (no big turbine though maybe) which needs tungsten and thorium to get, maybe even some carbide

**Comment by Leo-MathGuy** [comment]
Would take lots of spriting though

**Comment by N4H4N** [comment]
Youre right
