### ISSUE TITLE
Fast Forward Button

### ISSUE THREAD

**Issue by JC3** [Anuken/Mindustry-Suggestions#4925]
### Describe the content or mechanics you are proposing.

I would like a button that temporarily speeds up the game.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I spend the *vast* majority of my time just waiting for units to be built. It's not very fun. A lot of times I'll just leave the game running for 15-20 minutes while I step away and let units be built, so I can come back and play for 5 minutes and then step away again.

To that end, a fast forward button would be great for skipping through the boring parts.

Caldera is a good example of where this would make the game a lot more fun and less tedious.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
1 caldera is the issue not the game
2 anuke mentioned THIS EXACT type of feature in a list of things to never suggest

**Comment by Haznobrain** [comment]
someone didn't read "things you should not suggest"

**Comment by JC3** [comment]
Tbf I didn't check the box, lol.

**Comment by S0meM** [comment]
There is a mod for this. Install the mod.
[https://github.com/sk7725/TimeControl](https://github.com/sk7725/TimeControl)
