### ISSUE TITLE
About an open-world mode (or new game)

### ISSUE THREAD

**Issue by Zef126** [Anuken/Mindustry-Suggestions#4928]
### Describe the content or mechanics you are proposing.

It would be a great idea to add an Open World mode (or create a game) with more means of transport (trains, boats, planes) and attack vehicles (chards, planes, boats, not just robots). With the ability to expand all over the planet by building cores (and who knows, add the third dimension and tunnels...), it would be a great sequel!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will create a new parallel world for the community with new mechanisms!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
> it would be a great idea if you didnt bother anuke who wants to move on and made it yourself its hard to make open-world games so you should not ask a solo dev that wants to move on to make it

i agree HARD also this is not at all what mindustry was ever supposed to be over all this suggestion sucks

**Comment by Zef126** [comment]
I played a lot of time and propose new horison

**Comment by jehosula** [comment]
> I played a lot of time and propose new horison

odd that you would propose a completely different game if you already seem to be enjoying the current one

**Comment by Zef126** [comment]
The same mechanisms are present in a new world...it's strange that you reject them even though you like them too...I'm suggesting this to Anuen because he has a know-how that I admire and would like to see in other projects.
I find your negativity and snobbery quite distasteful!

**Comment by Zef126** [comment]
So why are you on this forum!?
And let's have a little bit of imagination... It is one of the most valuable qualities of a sandbox player!

**Comment by jehosula** [comment]
> So why are you on this forum!? And let's have a little bit of imagination... It is one of the most valuable qualities of a sandbox player!

you expect us to only say stuff if it's positive?
also a lot of stuff falls under the list if things to not suggest

**Comment by Zef126** [comment]
... only in the world already programmed!
All I expect from you is a constructive, kind and fair discussion, not praise!

**Comment by jehosula** [comment]
> ... only in the world already programmed! All I expect from you is a constructive, kind and fair discussion, not to be praise! 🤣🤣

i honestly have no idea what you are saying anymore

**Comment by Zef126** [comment]
Make an effort!

**Comment by jehosula** [comment]
> Make an effort!

bruh you should make an effort to be clear

**Comment by Zef126** [comment]
The things who are forbidden are only forbidden in the world already programmed!
All I expect from you is a constructive, kind and fair discussion.

**Comment by jehosula** [comment]
> The things who are forbidden are only forbidden in the world already programmed!

when did this suddenly turn into philosophy?
my opinion is NO, mindustry should not be like this, it WILL be very laggy with a huge open world map and trains and underground layer are never gonna be added

**Comment by Zef126** [comment]
I propose a new thing... mindustry is very well like what he is today!

**Comment by jehosula** [comment]
> I propose a new thing... mindustry is very well like what he is today!

isn't it too radical?

**Comment by Zef126** [comment]
No, it is just new!

**Comment by jehosula** [comment]
> No, it is just new! What's new and foreign often seems radical!

so radical it changes the entire games genres, just look for another game at that point my guy, why propose completely changing a game when you can look for another one, more like the one you wanted

**Comment by Zef126** [comment]
You just don't care of what I wrote before! We are turning around!

**Comment by jehosula** [comment]
> You just don't care of what I wrote before! We are turning around!

turning around? what does that mean?
also what you wrote is not a good suggestion

**Comment by Zef126** [comment]
Your opinion...

**Comment by jehosula** [comment]
> Your opinion...you can't say it for all!

doubt your opinion is anywhere near as popular as mine tho

**Comment by Leo-MathGuy** [comment]
If you want open world factory, play factorio. Making an infinite chunk generator and loader would take extreme efforts and rewriting of the game engine.

**Comment by Leo-MathGuy** [comment]
Moreover, this is an open source game, Anuken already has other projects (fau for example) and goals for mindustry.

For example:
* Performance - big maps already slow down the game a lot
* Simulation - again, this would slow down performance even more
* No point - once you max out your core and get all resources, there is no point for an open world

For there to be a point in an open world, you would need a much bigger tech tree, new resources, and basically astronomically more amount of content (like factorio) than the game currently has, which is almost a decade old. Gamemaking isn't that easy.

**Comment by Leo-MathGuy** [comment]
**MOREOVER**

This has multiple suggestions that Anuken **directly** said no to

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/86385005/ab6443aa-c501-43fb-b253-ada6596f828d)

**Comment by Leo-MathGuy** [comment]
What you are describing is literally Factorio

**Comment by itcannotbe** [comment]
> The things who are forbidden are only forbidden in the world already programmed! All I expect from you is a constructive, kind and fair discussion.

You do know that a *constructive, kind and fair discussion* goes out the window when you suggest things that are not meant to be suggested, like I don't know

**THINGS THAT IN THE DO NOT SUGGEST LIST (Found in the readme) AND THE TRELLO BOARD.**

The things that you conveniently somehow ignored.

**Comment by itcannotbe** [comment]
It's not like you were force to check the checkboxes were preventing you from submitting this suggestions in the first place, there no way you would have done that, right

**Comment by Leo-MathGuy** [comment]
> It's not like you were forced to check the checkboxes that were preventing you from submitting this suggestion in the first place, there no way you would have done that, right

Looks like Anuken has a soul to reap

**Comment by mills88812** [comment]
I’m going to try to setup something like this with a randomly generating enemy base that uses tiles that auto generate(from premade ones) with a system for tiles to become non-graphical and non-functional witch will just take there items/troops per min and each tile is 1 tile on a planet witch will allow you to send rockets kinda like the base game but I don’t think I will be able to setup conveyers between tiles without causing lag/problems but I’m trying we’ll see if I get it to work.

**Comment by jehosula** [comment]
> I’m going to try to setup something like this with a randomly generating enemy base that uses tiles that auto generate(from premade ones) with a system for tiles to become non-graphical and non-functional witch will just take there items/troops per min and each tile is 1 tile on a planet witch will allow you to send rockets kinda like the base game but I don’t think I will be able to setup conveyers between tiles without causing lag/problems but I’m trying we’ll see if I get it to work.

so not too different from the current game, besides the conveyors i guess

**Comment by mills88812** [comment]
> > I’m going to try to setup something like this with a randomly generating enemy base that uses tiles that auto generate(from premade ones) with a system for tiles to become non-graphical and non-functional witch will just take there items/troops per min and each tile is 1 tile on a planet witch will allow you to send rockets kinda like the base game but I don’t think I will be able to setup conveyers between tiles without causing lag/problems but I’m trying we’ll see if I get it to work.
> 
> so not too different from the current game, besides the conveyors i guess

It’s closer to a seamless map transition where the map is fully random.

**Comment by mills88812** [comment]
It will be the first planet that takes place mostly underground in a large production planet type of thing.

**Comment by S0meM** [comment]
> If you want open world factory, play factorio. Making an infinite chunk generator and loader would take extreme efforts and rewriting of the game engine.

He's right. This sounds a lot like factorio, and nearly all of that is in factorio. The rest is most likely in all of its mods. Just go buy factorio. It's worth it.

**Comment by azekillDIABLO** [comment]
My suggestion for you would either to direct you towards factorio which is basically what you're describing... or trying to achieve what you want to do through modding. It's too much to ask for a brand new game.

**Comment by Leo-MathGuy** [comment]
> Just go buy factorio. It's worth it.

Factorio is *always* on sale

**Comment by Zef126** [comment]
> It's not like you were forced to check the checkboxes that were preventing you from submitting this suggestion in the first place, there no way you would have done that, right

I did ...and I don't see your point!

**Comment by mills88812** [comment]
Yeah factorio is more grindy and slow passes compared to mindustry

**Comment by Zef126** [comment]
It exactly why I already saw it and didn't buy it...it some of the reasons!

**Comment by Zef126** [comment]
> Moreover, this is an open source game, Anuken already has other projects (fau for example) and goals for mindustry.
> 
> There are problems with an open world, for example:
> * Performance - big maps already slow down the game a lot
> * Simulation - again, this would slow down performance even more
> * No point - once you max out your core and get all resources, there is no point for an open world
> 
> For there to be a point in an open world, you would need a much bigger tech tree, new resources, and basically astronomically more amount of content (like factorio) than the game currently has, which is almost a decade old. Gamemaking isn't that easy.

I know that it isn't easy but I just propose something new. I don't expect anything fast... For open world maps, there are theory solutions like simulate just the part of the map who is useful for the player...In an open world covered by ennemy and large enought, there is no end because there is always someone to fight. To conclude, I didn't say anything about the core number allowed!

**Comment by Zef126** [comment]
Did you read all the discussion?

**Comment by Zef126** [comment]
> If you want open world factory, play factorio. Making an infinite chunk generator and loader would take extreme efforts and rewriting of the game engine.

As soon as it requires a bit of work, we don't do it? What a lack of tenacity!

**Comment by Zef126** [comment]
You are really disliking just because it is new and you don't exactly understand what I mean...for me, the sector mode with the sector campaign will still exist!
This other campaign would be on another planet, in parallel, like Erekir!

**Comment by Leo-MathGuy** [comment]
@Zef126 No, I have been through game dev, and made plugins and mods. Your idea would require severe rewrites of the game engine, it has taken 9 years for mindustry to get to this point.

**Comment by Zef126** [comment]
> @Zef126 No, I have been through game dev, and made plugins and mods. Your idea would require severe rewrites of the game engine, it has taken 9 years for mindustry to get to this point.

So it would be better for you if the project ran out of steam... Why not give it a fresh start?

**Comment by jehosula** [comment]
(correct me on where i got it wrong)
"factorio is cool and open world i want it"
"nvm factorio is ugly i won't buy it"
"mindustry is cool and i love it"
"wouldn't be cool if mindustry is open world"
and now you are asking an INDIE game developer that wants to MOVE ON to spend HOUNDREDS if not THOUSANDS of hours COMPLETELY rewrite the game's engine for something that the game was NOT AT ALL made or balanced for
and you are asking us to have tenacity when YOU are the one not even willing to try an open world factory building game before trying to copy it even claiming an open world mode would set it apart while it's only gonna make it more similar, not less

**Comment by jehosula** [comment]
> So it would be better for you if the project ran out of steam... Why not give it a fresh start?

actually it's not that bad for a developer that wants to move on

**Comment by Leo-MathGuy** [comment]
@jehosula Not only that, but also interrupt Anuke's existing plans for Mindustry and other projects for a gamemode that is useless without weeks, if not months of full commitment making new content to a free, open source game?

If you want it so bad, learn java and make it yourself, it's not as simple as it sounds.

**Comment by jehosula** [comment]
> @jehosula Not only that, but also interrupt Anuke's existing plans for Mindustry and other projects for a gamemode that is useless without weeks, if not months of full commitment making new content to a free, open source game?
> 
> If you want it so bad, learn java and make it yourself, it's not as simple as it sounds.

yup all great points

**Comment by Zef126** [comment]
My idea was for the moment he needed, not especially for today...and everything is taking time!
Programming Erekir has been long but it was done!

**Comment by Zef126** [comment]
@jehosula your first sentence is false!

**Comment by Leo-MathGuy** [comment]
> My idea was for the moment he needed, not especially for today...and everything is taking time! Programming Erekir has been long but it was done!

Creating a new planet took years, and it reused a lot of the code. An open world would take rewriting of not only the game, but the engine as well as it cant handle such things

**Comment by Leo-MathGuy** [comment]
> @jehosula your first sentence is false! I never said it!

Well, what you are saying is *literally* factorio, if you want an open source game with lots of content, get factorio.

**Comment by Zef126** [comment]
33€ for a game that I don't like ...

**Comment by jehosula** [comment]
> @jehosula your first sentence is false! I never said it!

i don't mean that you literally said it i mean this was your thought process

> 33€ for a game that I don't like ...
I don't have a computer and I don't like the resource system!

how would you know, you haven't even tried it my guy, you complained even tho you never played it

**Comment by Leo-MathGuy** [comment]
Moreover, it even has a demo

**Comment by Zef126** [comment]
@jehosula I never even thought what you said.
@Leo-MathGuy I said I don't have a computer.

**Comment by Leo-MathGuy** [comment]
Well, then thats closed. Mindustry being open would would make the only use of your phone be a frying pan

**Comment by mills88812** [comment]
Why is everyone basically attacking him for a suggestion this is just going in circles and is getting no where maybe start participating with new comments and not bringing up the same thing multiple times.

**Comment by Leo-MathGuy** [comment]
The op is demanding that an open world game mode should be made, and denying that it will take rewriting of the game engine, much more content, and citing the fact that erekir was made in several years as evidence which is completely unrelated.

**Comment by Leo-MathGuy** [comment]
It's not about the suggestion, but about the denial by the author of the many counter arguments this suggestion has

**Comment by camelStyleUser** [comment]
anuke should make 999999999 new blocks, 9999999 new liquids,999999999 new items and 999999999999 new units.i mean he made erekir in a few years.it shouldnt be too hard

**Comment by camelStyleUser** [comment]
oh i forgot he must also rewrite the game engine in assembly

**Comment by jehosula** [comment]
close the suggestion, people are absolutely trashing it now and there is no hope for any reasonable amount of positivity
