### ISSUE TITLE
Filter the dust and create sand from earth (and a little bit more)

### ISSUE THREAD

**Issue by Zef126** [Anuken/Mindustry-Suggestions#4929]
### Describe the content or mechanics you are proposing.

Would it be possible to create a block extracting titanium, another sand and another thorium? This would be very costly and time-consuming because it would have to filter the ground beneath it in search of pebbles to crush or these rare metals! In the same way, it would be possible to create a scrap metal compactor that would produce scrap metal from lead and copper, for example. This block would also work with sand.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Conquering certain terrains that are currently impassable or uninteresting would become a lot more fun.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
you are supposed to either bring in resources from somewhere else or just use what's there it's what makes them different

**Comment by jehosula** [comment]
> Your short-sightedness saddens me! If I bring in resources from another field, all my launch bases will go to him...it's not necessary!

only one sector's exports have to go there and why can't you just make do with what's there

**Comment by Zef126** [comment]
It becomes boring very fast sometimes and my core doesn't have any place to enter at the end of the building without importation!

**Comment by jehosula** [comment]
> It becomes boring very fast sometimes and my core doesn't have any place to enter at the end of the building without importation!

how does the core "doesen't have any place to enter at the end of the building without importation" also nubered sectors are not really intended to be fully completed  and what's the big deal with  having to import in one sector

**Comment by jehosula** [comment]
> My infrastructures are fairly complex and most of the time, even if I get as many resources in as possible through as few inputs as possible, I still don't have enough left to get them out and power my towers or factories! After a long experience of the game, I can say that the most interesting thing is the proportion and placement of resources on the terrain, but they all have to be manufacturable for it to be fun!

if it's a numbered sector, then why play them
and also not having power adds to the challenge
if it's not then go complain about the mapper issue, not suggest an otherwise dumb feature

**Comment by Zef126** [comment]
It's about your judgement, which is quite contemptuous, pointless and unjustified! Having less power is not the same as having no power at all! Adding these features will add more of a challenge than modifying the mapper once again!
What's more, if there are large quantities of resources in certain places, they must be present in the sole, at least in the form of traces!

**Comment by jehosula** [comment]
> It's about your judgement, which is quite contemptuous, pointless and unjustified! Having less power is not the same as having no power at all! Adding these features will add more of a challenge than modifying the mapper once again! What's more, if there are large quantities of resources in certain places, they must be present in the sole, at least in the form of traces! That makes sense!

whoops i meant having little power not no power (made that mistake before)
and adding these features would ruin the challenge even more 
just complain about maps instead of this

**Comment by Zef126** [comment]
It is not my point of view. Have only a tiny production of a resource is a real challenge of gestion ! Have no production is boring and makes you feel you are going in the past, at the begining of the game!

**Comment by jehosula** [comment]
> It is not my point of view. Have only a tiny production of a resource is a real challenge of gestion ! Have no production is boring and makes you feel you are going in the past, at the begining of the game!

then it's about optimizing that production? use solar panels out of desperation or don't play the map (if it's a numbered sector) simple it's CERTAINLY your point of view

**Comment by Zef126** [comment]
I am absolutely not speaking about energy...Numbered sectors must be fun to play! They exist...no!

**Comment by Zef126** [comment]
It would be a shame not to do something with it, and having maps with everything on them would just be too easy!

**Comment by jehosula** [comment]
> It would be a shame not to do something with it, and having maps with everything on them would just be too easy!

isn't that kind of what this suggestion does?
if you are complaining about the lack of resources then saying it should not be increased then wtf wrong is with you

**Comment by Zef126** [comment]
I just want a solution without changing the map!

**Comment by jehosula** [comment]
> I just want a solution without changing the map! It is amazing, we are turning around here too!

that really ruins the point of limiting resources, why limit resources when you can just place some more extractors somewhere else

**Comment by Leo-MathGuy** [comment]
You can already get every resource from scrap and water, I dont see the point in this.

**Comment by itcannotbe** [comment]
A wild items to scrap suggestion appeared!

Just so you know... Already been rejected before, a long long time ago.

https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083

**Comment by Leo-MathGuy** [comment]
> A wild items to scrap suggestion appeared!
> 
> Just so you know... Already been rejected before, a long long time ago.
> 
> [#190 (comment)](https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083)

This isnt items to scrap, this is *nothing* to scrap (completely balanced I know)

**Comment by jehosula** [comment]
> You can already get every resource from scrap and water, I dont see the point in this.

oh this suggestion just got worse

**Comment by Leo-MathGuy** [comment]
> > You can already get every resource from scrap and water, I dont see the point in this.
> 
> oh this suggestion just got worse

Yeah so basically scrap and water -> Every resource not enough. Now its air -> every resource (balanced and completely reasonable I know)

@Zef126 I would recommend closing this issue, its not going anywhere and is taking up space.

**Comment by S0meM** [comment]
How about you just make a mod for this? That would solve your problem, and I don't think these are necessary for base game. Also, here's another idea. Make these require certain tiles to function.

**Comment by Leo-MathGuy** [comment]
> How about you just make a mod for this? That would solve your problem, and I don't think these are necessary for base game. Also, here's another idea. Make these require certain tiles to function.

Thats just oil extractor but scrap extractor lmao

**Comment by Zef126** [comment]
I don't like mods, I tried some of them and they slowed the game! With a mod installed, I can't play the original game!

**Comment by Leo-MathGuy** [comment]
> I don't like mods, I tried some of them and they slowed the game! With a mod installed, I can't play the original game!

What makes you think that the same content in the game or a mod with be different in game speed?

**Comment by Zef126** [comment]
It will be more integrated and will work like the petroleum extractor... without slowing the game significantly!

**Comment by Leo-MathGuy** [comment]
What the hell is pertroleum 💀💀💀

Seriously, content from mods and content from the game are practically the same in performance, and your suggestion is too inbalanced and basically undermines the entire concept of mindsutry

**Comment by Zef126** [comment]
But it's still in the same spirit as oil and water extractors. Your primary conservatism is quite retrograde, I think! A little consistency please!

**Comment by jehosula** [comment]
> But it's still in the same spirit as oil and water extractors. Your primary conservatism is quite retrograde, I think! A little consistency please!

those two are because a lot of maps lack water and oil and those two are supposed to be the MAIN options while pumps are based on the map
pumps are super cheap to run too

**Comment by Zef126** [comment]
So why not make a secondary option that's fairly expensive in terms of resources and energy for at least the scrap metal that makes the game fully playable.
What's more, the oil extractor doesn't work on all terrains... so it can't be a viable main option!

**Comment by Leo-MathGuy** [comment]
A multi-resource that can only be gotten on certain tiles? Well we looped back to scrap as it is right now

**Comment by jehosula** [comment]
> What's more, the oil extractor doesn't work on all terrains... so it can't be a viable main option!

but it is?
like what maps lack those tiles?
water->spore->oil is the backup option that's very rarely used pumps are also an alternative in maps with oil puddles

**Comment by jehosula** [comment]
the main option does not have to be available 100% of the time
