### ISSUE TITLE
Something that should be changed

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#493]
U know that crawer units can go through walls and blocks, so i think they should can be attacked by scatters as they are taller then the wall. they already have large health, hight damage and health stealing. I know its strange to let a ground unit attacked by a anti air turret but i still hope it can be changed.

Also, the air and naval units should have a drowning effect when they get destroyed on water.

**Comment by Anuken** [comment]
I don't think so. They can *walk over buildings*, but they are not high enough up to be considered airborne. Most people would not consider them air targets, and I don't think turrets should either.
