### ISSUE TITLE
(Erekir) For of war should disappear once you capture a sector

### ISSUE THREAD

**Issue by Leo-MathGuy** [Anuken/Mindustry-Suggestions#4930]
### Describe what you would like changed, and why.

The fog of war is annoying to clear out once you capture a sector and start mindustrializing it, and since there is no war in the sector anymore, there shouldn't be a fog of war either.

### Describe the changes you want to propose. Include possible alternatives.

Once the sector is captured, the fog of war should disappear in that sector.

A possible alternative for attack sectors: Once you build a core in each core zone, then it could disappear

**Comment by jehosula** [comment]
maybe not instantly but just makes whatever reveals fog progressively reveal more and more and/or only reveals the black fog

**Comment by S0meM** [comment]
This has been suggested many times.
#4712 
#4248
#4131
#3847 
#3552
