### ISSUE TITLE
Buff reinforcedPayloadConveyor's moveTime to 30 (from 35) so that it syncs more often with the normal payloadConveyor

### ISSUE THREAD

**Issue by broganeuquoixe** [Anuken/Mindustry-Suggestions#4934]
### Describe what you would like changed, and why.

I would like to buff the Reinforced Payload Conveyor's (and consequently also the router's) move time from [35](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/Blocks.java#L5641) to 30 so that it matches *more often* with the Payload Conveyor's [45](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/payloads/PayloadConveyor.java#L19) move time

https://github.com/Anuken/Mindustry-Suggestions/assets/161990992/934c9a90-b9a0-4e82-87a5-0759321bede3

After the change:

https://github.com/Anuken/Mindustry-Suggestions/assets/161990992/f7834ed2-313e-4b96-a208-c9aa8d3b858e

### Describe the changes you want to propose. Include possible alternatives.

feel free to comment other numbers.

**Comment by jehosula** [comment]
nerf the normal one's to 40 and nerf this one to 40?!?!
idk or maybe buff the normal one to 35?

**Comment by broganeuquoixe** [comment]
It is intentional for them to have different speeds, you can't put them both at the same one

**Comment by S0meM** [comment]
Wow, that is agonizing to watch.

**Comment by broganeuquoixe** [comment]
`moveTime` is the time the payload conveyor takes between two moving attempts, so to say. The lower it is, the faster the conveyor is

**Comment by broganeuquoixe** [comment]
https://github.com/Anuken/Mindustry/issues/9731#issuecomment-2048289229
