### ISSUE TITLE
Add Aluminum or just Metal as in the old versions.

### ISSUE THREAD

**Issue by LukovDev** [Anuken/Mindustry-Suggestions#4937]
### Describe the content or mechanics you are proposing.

I suggest adding a new ore - "Iron". Yes, I know that it was in the old versions, and was converted to "Copper".

I think you can just add the ore "iron", and transfer the functionality of copper to it. And copper, in turn, should be used where it is logically needed. To make iron the first step in the development of the base, and use it where it is also logically needed.

For example, to use iron as a RAW MATERIAL for the construction of drills and conveyors. And also to mine copper as well as lead.

It is also a good idea to add a RAW iron processing plant and convert it into high-quality iron. It can be done in the same way as in the old versions, where iron and coal had to be supplied to the plant in order to obtain metal

Also, it would be possible to add a factory for quenching high-quality iron. For example, to make the plant accept high-quality iron, coal, and water. And then the high-quality iron will turn into tempered iron.
It can be used in buildings and other places where higher-quality resources are required. For example, more powerful turrets, walls, units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The fact that copper is used everywhere as a base looks somewhat strange. Copper is usually used in electronics or for thermal conductivity. In ordinary buildings or something similar, iron should be used, as in real life. For example, in drills or conveyors. The use of copper in their base looks somehow strange. Because in real life they usually use ordinary iron or high quality iron.

I believe that adding iron to the game will make it more diverse, and make it more logically correct in some places.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by LukovDev** [comment]
Perhaps, after the implementation of my idea, it will be very unusual at first. But I hope that everyone will quickly get used to such mechanics.

**Comment by jehosula** [comment]
> Perhaps, after the implementation of my idea, it will be very unusual at first. But I hope that everyone will quickly get used to such mechanics.

it's no different from suggesting new content in general, and idk the question is "is there a place for a new material there?" also the where materials are used in building is not supposed to make sense unlike the factories' input and output
