### ISSUE TITLE
Hints in the game console.

### ISSUE THREAD

**Issue by LukovDev** [Anuken/Mindustry-Suggestions#4938]
### Describe what you would like changed, and why.

I would like the game console to have prompts when entering a command.

Because without knowing the source code or the capabilities of the console, it becomes impossible to use it.

### Describe the changes you want to propose. Include possible alternatives.

It would be useful to show hints when entering a command.

By type:
Vars.world. * here is a hint - "tile()" or a list of possible commands. *

An alternative can be taken from the Minecraft game. It is implemented well there

**Comment by S0meM** [comment]
Does anyone know a good guide to the commands? I scoured the internet and couldn't find anything.
