### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Na1Sh1r0** [Anuken/Mindustry-Suggestions#4941]
### Describe the content or mechanics you are proposing.

![Picsart_24-04-02_13-22-57-317](https://github.com/Anuken/Mindustry-Suggestions/assets/153459261/28799379-a628-4034-9c13-09772eb00078)

![eQbhSLyfVsM translated](https://github.com/Anuken/Mindustry-Suggestions/assets/153459261/a7d02194-89fb-4ade-8ded-dda99cca82a5)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will increase immersion in the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
who will send video messages to a replaceable robot that only has one goal in mind

**Comment by octopuscaat** [comment]
seek mental support

**Comment by nilederg** [comment]
You should keep yourself safe

**Comment by EchoSabre2** [comment]
rip
