### ISSUE TITLE
Mod making software for mindustry

### ISSUE THREAD

**Issue by Blazindude365** [Anuken/Mindustry-Suggestions#4942]
### Describe the content or mechanics you are proposing.

A Mod making software for mindustry that includes: planet mapping, block making, unit building, wave editing, ore generating, tower building and sharing on the mod browser.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It helps unexperienced people to make Professional mods

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by S0meM** [comment]
This is not an addition to the game. It's kinda irrelevant.

**Comment by itcannotbe** [comment]
> It helps unexperienced people to make Professional mods

It won't. Rather if such were a thing, it would only lead to a lot more 0 effort mods.
