### ISSUE TITLE
alphabetical sorting for sectors

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#4943]
### Describe the content or mechanics you are proposing.

make the sectors in the sector list sort alphabetically this could be an option to turn on and off

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it's pretty hard to find the sector you are looking for at times when they are just placed seemingly arbitrarily 
so this would make it much easier to find the sector you are looking for
and/or give the list multiple columns to see more sectors at once and have a better chance to find the one you want

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by hsaturn** [comment]
The search field is great and allows to find very quickly a planet by just typing a part of it (usually two caracters is enough).
`
Instead, I'd prefer to sort them by last visit !`

**Comment by jehosula** [comment]
> The search field is great and allows to find very quickly a planet by just typing a part of it (usually two caracters is enough). ` Instead, I'd prefer to sort them by last visit !`

i completely forgot that existed
but i still think this suggestion is useful, and sorting by last visit is also a good idea
