### ISSUE TITLE
core units (spawned from a core) should not count to unit cap

### ISSUE THREAD

**Issue by octopuscaat** [Anuken/Mindustry-Suggestions#4945]
### Describe what you would like changed, and why.

core units (alpha,beta, etc) that have been spawned from a core, as in it has not been created with payload source or world proc, should not count to unit cap. this is because when the unit cap is 0 the core unit is not able to spawn.

### Describe the changes you want to propose. Include possible alternatives.

check if a unit has been spawned from a core, if it has (and unit cap is full) it will not die. 
IF the cap for that unit is full and there are other of the same type of unit that are not spawned from a core, the unit will not spawn.
this should be able to be turned off or on for each team in map settings.

**Comment by MEEPofFaith** [comment]
What you're describing seems more like a bug than balancing/feedback. Consider opening a [bug report](https://github.com/Anuken/Mindustry/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).

**Comment by octopuscaat** [comment]
why would this be a bug?

**Comment by MEEPofFaith** [comment]
> when the unit cap is 0 the core unit is not able to spawn.
You're stating it like it's incorrect behavior, which means it's a bug.

**Comment by octopuscaat** [comment]
no, I don't think this is incorrect behavior, I am pretty sure what happens is still the game correctly working. When a unit is spawned while its unit cap is full, the game will kill the unit. This probably not happen normally as you are unable to produce units while the cap is full. When a core unit spawns while the unit cap is 0 the game sees a unit while the unit cap is full and kills the unit. This is an intended.

**Comment by octopuscaat** [comment]
also I don't want to make a bug report unless I know it is _definitely_ a bug, because I don't want to waste the creators time looking over things that are arguably bugs. He looks at suggestions regularly, so chances are he already saw this.

**Comment by MEEPofFaith** [comment]
But then isn't repeatedly spawning and dying an unintended behavior?
And in what case is this happening, anyway?

**Comment by octopuscaat** [comment]
no this happens normally. if you set the unit  cap to 0 and have a team with base builder ai they cant spawn.
