### ISSUE TITLE
Make Erekir sectors' names more exclusive

### ISSUE THREAD

**Issue by Lolnoizcool** [Anuken/Mindustry-Suggestions#4947]
### Describe the content or mechanics you are proposing.

This is pretty much unnecessary, I suggest making the Erekir sectors' names more engaging and exclusive. Like giving it an exaggerated adjective or military noun.
A few names I propose:
- Lake->Melted Lake
- Basin->Scorched Basin
- Marsh->Arkycite Marsh
- Peaks->Jagged Peaks
- Ravin->Cracked Ravine
- Caldera->Slag Caldera
- Stronghold->Robust Stronghold
- Karst->Carbonated Karst

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Makes them more engaging, exclusive to Mindustry, and also differentiable from real-life geographic terminologies.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mechanicalfish** [comment]
All erekir sectors(with exceptions) will be 1 word names.

**Comment by jehosula** [comment]
i like the one word names

**Comment by Lolnoizcool** [comment]
> All erekir sectors(with exceptions) will be 1 word names.
Aw that's bad. Anyway, bye bye
