### ISSUE TITLE
More nuclear strike 

### ISSUE THREAD

**Issue by Lolnoizcool** [Anuken/Mindustry-Suggestions#4949]
### Describe the content or mechanics you are proposing.

One strike is too boring, how about spicing it up by launching a couple more in high and above threat attack sector?
It will hit the starter core of course, I haven't thought about other cores tho.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Force the player to expand, more challenging.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Lolnoizcool** [comment]
I will close if needed

**Comment by jehosula** [comment]
the nuclear strike is supposed to be a gimmick
and it's a troll so it's quite cheesable
