### ISSUE TITLE
More Mapping tool

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry-Suggestions#495]
Add new Diagonal Brush to Map editor.

diagonal brush : draws only perfect diagonal lines. Since drawing perfect diagonal lines is too hard and takes long time in big maps.

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
isn't there a line tool?

**Comment by itcannotbe** [comment]
@potatoisagender
Line tool? Yes.
Diagonal Support? No.

**Comment by SupremeTurtle** [comment]
How about just revamp the line tool completely to where it can make a line in all directions

**Comment by MrByars** [comment]
> isn't there a line tool?

There is a line tool but its dont have any diagonal support.

**Comment by potatoisagender** [comment]
For some reason I remember drawing diagonal lines with the line tool... Lemme check.

**Comment by itcannotbe** [comment]
In-game, you can.

**Comment by OnyxDog07** [comment]
It should have all blocks that will be painted highlighted in a darker yellow
