### ISSUE TITLE
Possibility of players adding their own schematics to Build AI

### ISSUE THREAD

**Issue by TagGamer555** [Anuken/Mindustry-Suggestions#4951]
### Describe the content or mechanics you are proposing.

Adding your own schematics to the Build AI

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

People can make schematics for things there aren't schematics for yet (Scrap Daggers, Scrap Novas, Scrap Foreshadow, etc.)
Also it would allow people to make schematics for the Build AI with content of different mods

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
seems like a good idea but how will the ai know where to place them?

**Comment by TagGamer555** [comment]
> seems like a good idea but how will the ai know where to place them?

make so that a schematic can have a specific tag or dependency
for example, a scrap to mega schematic could have scrap ore to depend on to be placed
or for example, an isotope generator schematic only placeable on scalar, vector, tensor or luminite ore and also requires betamindy mod as a dependency
