### ISSUE TITLE
Anti-Deconstruct Derelict Structures 

### ISSUE THREAD

**Issue by snjfhmx** [Anuken/Mindustry-Suggestions#4955]
### Describe the content or mechanics you are proposing.

add a toggle in the map making settings(under the team settings for Derelict) to make it so players can't deconstruct derelict structures

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will be helpful for map makers to create broken story elements, but ones that are permanent

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
well placement range check (can't build next to enemy buildings) kinda does that
and repairing derelict buildings is a slightly better version of the deconstruct/reconstruct trick
but your suggestion can still add to the game
