### ISSUE TITLE
Colour Blindness issues

### ISSUE THREAD

**Issue by NightShadow02** [Anuken/Mindustry-Suggestions#4956]
### Describe what you would like changed, and why.

Ozone and Hydrogen look too similar to a person with protanopia. Connected/unconnected power nodes are also similarly difficult to determine. 

I often find that scroll rotating the building to have ozone/hydrogen in the desired location to be difficult due to not being able to tell which orientation it is in. I also find myself having to put a router at each exit just to determine what fluid is coming out of that output.

### Describe the changes you want to propose. Include possible alternatives.

different overlay patterns on powered/unconnected nodes and also ozone/hydrogen conduits. (eg: horizontal/vertical/zigzag stripes overlaid on the node beams/conduits)
tweaked icon for hydrogen/ozone outputs on catalyzers.

A good tip I heard from a colorblind developer is to make everything initially grayscale when designing UI and then see what looks too similar. Colourblind people mainly have problems differentiating similar hues but are fairly okay when determining contrast/values.

**Comment by S0meM** [comment]
There saw a mod for this. Search for 'Colorblindness fix'.

**Comment by NightShadow02** [comment]
I have tried the mod prior to this. It only shows the letters _after_ you place the building down. 

It also doesn't really help while looking at pipe networks when they are far away from the building itself. The only option in that case would be to hover over the pipes to be sure what fluid is in the pipe.
