### ISSUE TITLE
Logical processors

### ISSUE THREAD

**Issue by Thunderspeed578** [Anuken/Mindustry-Suggestions#4958]
### Describe what you would like changed, and why.

Hello, I wanted to suggest if you make the logical processors also be able to read messages from the blocks and read variables from other processors, and that other types of data be saved in memory blocks.

### Describe the changes you want to propose. Include possible alternatives.

Other data in memory blocks
Processors can read other processors
That you can have several campaigns (as if they were different games and that the mods are added individually to each one

**Comment by camelStyleUser** [comment]
great. someone didnt read "do not suggest"

**Comment by Thunderspeed578** [comment]
The memory block only allows variables with numbers but does not accept
Letters or Container variables, Or if yes, then it won't let me save them

**Comment by camelStyleUser** [comment]
> The memory block only allows variables with numbers but does not accept Letters or Container variables, Or if yes, then it won't let me save them

of course it doesnt.its for numbers only.serialize
