### ISSUE TITLE
Add turret ammo capacity to the in-game help

### ISSUE THREAD

**Issue by hexagonrecursion** [Anuken/Mindustry-Suggestions#4959]
### Describe the content or mechanics you are proposing.

Each turret internally stores some ammo. Unfortunately the ammo capacity of each turret is not currently displayed in the in-game help screen and has to be determined experimentally by the player. The help screen does display liquid capacity, but not item/ammo capacity.

![image](https://github.com/Anuken/Mindustry-Suggestions/assets/52621858/06d11dc4-390b-4552-b7ce-2bd8bfdb6767)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be convenient for the player to be able to look up the internal storage capacity of each turret via the in-game help

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by S0meM** [comment]
Here's the thing, most of the time the capacity is 30. There are very few exceptions at least in vanilla. Foreshadow: 40 and Titan: 12, 
Everything else is 30.
https://github.com/Anuken/Mindustry/blob/b8c6781004f20f399c877a06f668366e420eadc2/core/src/mindustry/content/Blocks.java#L3851-L3874
https://github.com/Anuken/Mindustry/blob/b8c6781004f20f399c877a06f668366e420eadc2/core/src/mindustry/content/Blocks.java#L4196-L4237
https://github.com/Anuken/Mindustry/blob/206adf46bf6a60c52aeeebc83fe1c80fc2c46c38/core/src/mindustry/world/blocks/defense/turrets/Turret.java#L41
The first 2 show the only exceptions in vanilla, and the third shows the default.
