### ISSUE TITLE
Add the weather control system in Editor

### ISSUE THREAD

**Issue by SpaceEarthEX** [Anuken/Mindustry-Suggestions#496]
Add the weather control system for make maps. System like: **Time-limited when there is no storm, Time-limited when there is no storm. When the storm keeps coming or not, or RANDOM.** This will be fun of playing custom maps.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
https://trello.com/c/BcwMWJOL/727-define-weatherenvironment-multiplier-stuff-in-rules
