### ISSUE TITLE
add a range to pathfind

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#4963]
### Describe what you would like changed, and why.

Adding range to pathfind will massively simplify pathfinding and make it 400x more useful this will reduce the lines needed and improve reliability as well

### Describe the changes you want to propose. Include possible alternatives.

Add a range to pathfind like on approach but pathfind

**Comment by jehosula** [comment]
i don't want logic processors to be even more op so i am against this if it's not a wproc exclusive
also performance might be an issue with pathfinding a ton of tiles
also why doesn't command mode do this already

**Comment by Mythril382** [comment]
Just do a within check, and if they're not near enough, pathfind.

**Comment by XxsuperdeadlysniperxX** [comment]
> i don't want logic processors to be even more op but i am not against this if it's a wproc exclusive
> also performance might be an issue with pathfinding a ton of tiles
> also why doesn't command mode do this already

This is simply to make pathfind more useful right now it tries to pathfind directly to the building requiring custom range logic which can be a worse for lag and a nightmare to troubleshoot in xase it somehow breaks i hope i gave more context

**Comment by XxsuperdeadlysniperxX** [comment]
> Just do a within check, and if they're not near enough, pathfind.
> 
> This is probably the most basic way to do it.

Oh yeah the problem is when it gets in range you can't make them back up if an enemy unit approaches and its just inconsistent in some ways don't get me wrong it has its uses but its just not worth using in my opinion

**Comment by XxsuperdeadlysniperxX** [comment]
Some vote emotes i guess

**Comment by XxsuperdeadlysniperxX** [comment]
Bumping

**Comment by XxsuperdeadlysniperxX** [comment]
Bump it

**Comment by XxsuperdeadlysniperxX** [comment]
Dang became stale

**Comment by UltraBlackLinux** [comment]
bumping this because pathfinding will fail if there's an obstacle, which is really annoying
