### ISSUE TITLE
Maybe a new block

### ISSUE THREAD

**Issue by Wolf235m** [Anuken/Mindustry-Suggestions#4964]
### Describe the content or mechanics you are proposing.

I actually want a new block and cancelation of the need for titanium for creating separators I think beefed drills!.

Then I see asteroids in the distance🤔 what if it'll be part of the map like you need to capture both planets? Even capturing the sun? Maybe even new planets? We'll you developers have the decision but if you guys do add it will be much fanfare amongst us thank you. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will be a gamechanger many will come back many will join because of new content! 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
> i want a new block
well worry not, we have world switch now

**Comment by jehosula** [comment]
> I actually want a new block and cancelation of the need for titanium for creating separators I think beefed drills!.

what is the new block you are describing?

making Seperators require titanium is VERY important to balancing and it prevents getting titanium before you should be able to

beefed up drills don't seem necessary because there is enough progression and it would HAVE to come with t6 and a general increase in demand

**Comment by S0meM** [comment]
The separator is supposed to take titanium because it can make titanium. If it didn't, then you could get it before you should and on maps you shouldn't be able to get it. I am near certain that Anuken thought it through when he made the separator.
