### ISSUE TITLE
Endless enemy base generation/rougelike mode

### ISSUE THREAD

**Issue by Mills888dev** [Anuken/Mindustry-Suggestions#4966]
### Describe the content or mechanics you are proposing.

Simple explanation: A game mode/location that generates maps with attack bases and upon completing them be able to move forward to a new attack map while being able to take upgrades/items from the last location to the next one.

complex:

Upon loading onto the planet/location you will find the first attack map with a pre-defined layout/seed. Upon the completion of that zone, you will get to pick an upgrade card from a selection of 3 random ones from a list. Theses could be simple as start with X more of X recourse or start with X polys/monos. This could also be expanded to a custom research system through its which causes you to collect cards that unlock certain blocks (EX: basic turrets (comes with arc/hale), advanced drill (Laser drill). This would be only available for one type of tech tree (Serpulo or Erekir). Upon death you have to restart back to the start with no upgrades or unlocks being continuous.

This shouldn't add any new objects/blocks/items/creatures to the game besides for possibly a new map generation system and card-based upgrade system.
(I have terrible English so very sorry for any cohesion problems).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content would fill a niche for new gameplay as it would be a form of rouge-like/lite that could be played endlessly. This could also have mod support for it or a form of framework to allow players to add new cards. This could be used as a fun new way to play the game. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
mindustry is an rts-tower defense, not an RPG or rougelike. It will never have cards or upgrades in the way you are implying. Also, you can already generate an infinite number of attack sectors. Use serpulo sector generate with any of these sectors:
0,5,10,11,13,21,*24,25,30,31,34,36,38,47,49,*54,56,57,59,60,68,*69,70,84,114,115,121,124,125,129,133,138,148,149,154,158,180,182,223,*224,*225,226,*229,233,241,248,*254,255,257,259,*264,265

the seed does not matter. Using any of these sectors will generate an attack sector. the difficulty of the map depends of the sector used. sectors with an * have an eradication difficulty. 
if you want to see the difficulty of each sector, you can see them here: https://mindustry-unofficial.fandom.com/wiki/List_of_Sectors

please close the issue.

**Comment by mills88812** [comment]
(Same person as poster just different account)
1.  of all this isn’t an RPG an RPG is a role playing game base mindustry is closer to a RPG than this idea is.
2. mindustry is a form of rougelike especially the old version where you loaded into a map with nothing and tried to survive as long as possible.
3. I already know about attack sector generation this idea was spurred as a continuation of using that as its core(with possible changes to make them more functional and better).
4. why would I suggest this if I could mod it in I don’t make mods for mindustry nor do I have time to most of these suggestions here could be made into a mod.
5. why wouldn't mindustry have cards like that as it’s similar to a tech tree or being granted recourses from a main planet and your just an ai test to see how far you get and giving you new recourses based on how well you are doing instead of putting all eggs in one basket.

> mindustry is an rts-tower defense, not an RPG or rougelike. It will never have cards or upgrades in the way you are implying. Also, you can already generate an infinite number of attack sectors. Use serpulo sector generate with any of these sectors: 0,5,10,11,13,21,*24,25,30,31,34,36,38,47,49,*54,56,57,59,60,68,*69,70,84,114,115,121,124,125,129,133,138,148,149,154,158,180,182,223,*224,*225,226,*229,233,241,248,*254,255,257,259,*264,265
> 
> the seed does not matter. Using any of these sectors will generate an attack sector. the difficulty of the map depends of the sector used. sectors with an * have an eradication difficulty. if you want to see the difficulty of each sector, you can see them here: https://mindustry-unofficial.fandom.com/wiki/List_of_Sectors
> 
> you can literally create a mod for this for future issues, try and limit your suggestions to a single suggestion, not a group of them. please close the issue.
