### ISSUE TITLE
New option in "set marker" are requested

### ISSUE THREAD

**Issue by CutePillow** [Anuken/Mindustry-Suggestions#4967]
### Describe the content or mechanics you are proposing.

Set a new option in "set marker" in the world-processor.
It can _make the marker only be visibled to some players, instead all players._

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

"Mark marker" and "set marker" allow players to use marker to make some
"ui", it will improve the fun when playing. 
But all the players could see these markers in be version now.
Making markers only be only visibled to some players instead of all players can let Map makers to make different windows for each player.
This will Improve the fun and customization of gameplay.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SkyeTheFoxyFox** [comment]
you can already do this if you know how to intentionally desync

**Comment by camelStyleUser** [comment]
already possible with the power of ✨desync✨

**Comment by Mythril382** [comment]
it's desync time

**Comment by octopuscaat** [comment]
close issue perhaps?
