### ISSUE TITLE
Floors drowning leg unit should apply their status effect

### ISSUE THREAD

**Issue by Sh1penfire** [Anuken/Mindustry-Suggestions#4968]
### Describe the content or mechanics you are proposing.

Drowning should cancel the hover property of legged units, maybe with a new field as well

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

 It doesn't make sense for drowning leg units to drown unscathed especially on Erekir

I think this would generally be helpful to de-incentivise crossing deep liquids with legged units while not entirely blocking it via some damage/slowdown

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
yeah why the heck can legged units walk away unscathed and uninterrupted if they didn't drown first
