### ISSUE TITLE
armored conveyor/duct hp buff

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#4969]
### Describe what you would like changed, and why.

buff armored duct/conveyor hp
pros: if you are going to pay the price, it may as well be good at it
cons: annoying to clear each one out
also these have too little hp for "armored"
also might give them a minor niche that's at least better than the current ones
(discussed in # balancing) and the cost can be increased for the high options

### Describe the changes you want to propose. Include possible alternatives.

Suggestion: Buff Armored Conveyor and Duct

small: 200 hp, 300 hp
modest: 300 hp, 400 hp
high: 500 hp, 600 hp
very high: 750 hp, 700 hp
you can also just give them armor and give a smaller hp buff

**Comment by Slotterleet** [comment]
Armored ducts also serve a similar purpose to armored conveyors - not accepting non-conveyor/duct input from sides, which may help reduce spaghetti. HP does not matter imo, cuz enemies usually target literally everything _other than_ conveyors first, even if they do, they are hella easy to rebuild.

**Comment by jehosula** [comment]
> Armored ducts also serve a similar purpose to armored conveyors - not accepting non-conveyor/duct input from sides, which may help reduce spaghetti. HP does not matter imo, cuz enemies usually target literally everything _other than_ conveyors first, even if they do, they are already screwed, but hella easy to rebuild.

yeah but aren't they supposed to be ARMORED?

**Comment by itcannotbe** [comment]
If you want to give them more HP, then prepared for them to cost more.

Because It would not be sane for a conveyor to become a wall replacement.

**Comment by jehosula** [comment]
> If you want to give them more HP, then prepared for them to cost more.
> 
> Because It would not be sane for a conveyor to become a wall replacement.

yeah make them a bit more expensive fo the higher options

**Comment by itcannotbe** [comment]
It doesn't mean that if they don't get targeted they won't get damaged.

**Comment by S0meM** [comment]
But it still wouldn't work as a wall.

**Comment by itcannotbe** [comment]
Unless you nerf build time to match actual walls.
