### ISSUE TITLE
Add Schematic Folders

### ISSUE THREAD

**Issue by Stardust9681** [Anuken/Mindustry-Suggestions#497]
Add folders for schematics. It can be such a pain to scroll through 30 schems to find your power gens, or your defensive schematics, so being able to file your schematics into different folders would make that process a lot faster. Would be convenient to separate the different types into their own unique categories.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
You lied

 > I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by Stardust9681** [comment]
> You lied
> 
> > I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

My apologies, I had not seen it. Suggestion closed, then.
