### ISSUE TITLE
Optimization Title

### ISSUE THREAD

**Issue by Aantihappiness** [Anuken/Mindustry-Suggestions#4972]
### Describe what you would like changed, and why.

We urgently need to optimize the bots because they are very buggy and freezes sometimes even crashes 

### Describe the changes you want to propose. Include possible alternatives.

Rewrite the bot code or optimize them somehow

**Comment by camelStyleUser** [comment]
> very helpful description 10/10

not even clear if you are talking about some ai or units

**Comment by itcannotbe** [comment]
How do bots even crash?

**Comment by Aantihappiness** [comment]
> Кроме того, почему там написано « _Заголовок_ оптимизации» ?

Это ошибка Github

**Comment by Aantihappiness** [comment]
> > очень полезное описание 10/10
> 
> даже не понятно, о каких ИИ вы говорите или о юнитах

Это не касается определенных юнитов если их будет больше чем обычно (примерно 200) то лагает

**Comment by camelStyleUser** [comment]
> > > очень полезное описание 10/10
> > 
> > 
> > даже не понятно, о каких ИИ вы говорите или о юнитах
> 
> Это не касается определенных юнитов если их будет больше чем обычно (примерно 200) то лагает

running mindustry with 64mb of ram and a 100mhz processor of course will cause crashes and lag
