### ISSUE TITLE
Serpulo unit cap building

### ISSUE THREAD

**Issue by Twcash** [Anuken/Mindustry-Suggestions#4973]
### Describe the content or mechanics you are proposing.

Erikir has the ability for the player to make cores increasing the unit capacity, But in Serpulo is is static unless you upgrade your core. This rids of some pvp aspects I liked in v5 such as large scale combat. Maybe A building in Serpulo could be added that can add a small amount to the unit capacity.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Serpulo Unit Cap Block

What: A placeable 4x4 block (working title: "Neural Net") that:
-Costs 250 plast, 500 sili, 700 copper and 750 lead
-Adds +8 to unit capacity
-Requires core adjacency to be placed in similar manner to a Core or Vault.

And:
-To balance the new addition, reducing the Nucleus Core's population cap addition by 2 down to 22.

Why: Strict limits on population cap function as strict limits on how the player is able to express themselves in their army composition. Adding a means of customizing unit cap would allow players to optionally reinvest into large lower tech armies without encouraging complacency by still requiring forward tech progression. The need for unit cap customization is especially high in Serpulo's campaign where the simplified map conditions that allow players to freely experiment at their own pace preclude the ability to expand to additional cores in a way that Erekir and custom maps typically offer.

-The core adjacency requirement may be substituted for a thermal tile requirement in a 3x3 block. Placement requirements are assumed to be necessary to prevent unlimited access to population count expansion.
-Plastanium was selected arbitrarily as the most appropriate mid-game tech resource to limit access to Neural Net blocks. Surge alloy is a viable alternative.
-The option to actively power and supply the block to receive its benefit was considered, and appreciated, but rejected for the possibility of jank when partially or intermittently powered.
(+8 was chosen because of the added cost of core adjacency)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by clod44** [comment]
I think +4 base and +8 when powered would add more sauce to the game so it doesn't become just a drop and forget block while not annoying the player much.

**Comment by Leo-MathGuy** [comment]
More leg on mobile
