### ISSUE TITLE
Left handed ui

### ISSUE THREAD

**Issue by kerharhun45** [Anuken/Mindustry-Suggestions#4974]
### Describe what you would like changed, and why.

I would like to have a way on Android and other mobile systems to mirror the UI and move it to the left side.  This would be necessary, in my opinion, because left-handed players would be able to play more easily and enjoyably.  At the same time, it would also be very outstanding among games, because very few games offer this opportunity.  Thank you on behalf of all the players who would use this feature.

### Describe the changes you want to propose. Include possible alternatives.

I think there should be a switch "move ui to the left" under the graphics menu in the settings, which would move the ui mirrored along its vertical axis to the left, and the commamd mode button to the right. Alternatively, it would be good if it were in a separate menu in the settings  you could make a custom ui.

**Comment by camelStyleUser** [comment]
make there be

**Comment by camelStyleUser** [comment]
you can ✨ make the feature ✨ and pr it

**Comment by kerharhun45** [comment]
I can't make java codes, but i found a mod (in mindustry android ingame mod selector) named bottom left ui. If i try to use it it crashes, but If this is what I mean, it could be a good basis.

**Comment by kerharhun45** [comment]
I can write java code, but if someone shows me where to change, I can try

**Comment by OnyxFinger** [comment]
> you can ✨ make the feature ✨ and pr it

Do you even realize not everybody knows how to code
That's half of why they're suggestions

**Comment by Addaxs** [comment]
> you can ✨ make the feature ✨ and pr it

they wouldn't be suggesting if they could do it by their own.
