### ISSUE TITLE
Adding a bitwise operation

### ISSUE THREAD

**Issue by Zeleniykustik** [Anuken/Mindustry-Suggestions#4975]
### Describe the content or mechanics you are proposing.

We specify the bit number we want to start reading from and the total number of bits we want to read.
Work example:
We have a 64-bit number .....1111111100.
We specify the bit number [2].
We also specify the number of bits we want to read [8].
As a result, we cut off all unnecessary bits and get 255 as output. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This command will simplify operations with bits, which will allow you to write code based on binary logic faster. For example, a cellular automaton or data compression into something like an archive with the possibility of unzipping. Or just Tetris

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
really ez(if you get a predefined mask its even faster)
```
op shr tmp data start
op shl mask 1 length
op sub mask mask 1
op and out tmp mask
```

**Comment by Zeleniykustik** [comment]
Thanks for the optimization and the reply

**Comment by S0meM** [comment]
I don't understand that. ⬆️But, I do understand that if you use the AND operation on a number and 15, then it will get you the first four bits of the number because of this:
(15 in binary)     00001111
AND
(28 in binary)     00011100
=
(result in binary)00001100
You can do the same on any (2^x)-1 because they will all be a number of 0's with only 1's afterward.

**Comment by Zeleniykustik** [comment]
Maybe I broke something. But if I want to get a number with bitness greater than 53, the code outputs 0.

set data 511
set length 54
set start 0
op shr tmp data start
op shl mask 1 length
op sub mask mask 1
op and out tmp mask
print out
printflush message1


![1](https://github.com/Anuken/Mindustry-Suggestions/assets/126210243/37a586c4-26b0-4d7c-9869-899fd075b58a)
![2](https://github.com/Anuken/Mindustry-Suggestions/assets/126210243/2399fbac-c462-4956-b1b4-10761fc62982)
![3](https://github.com/Anuken/Mindustry-Suggestions/assets/126210243/ceee52bb-7678-4d57-9088-0e9f4a05dec4)
![4](https://github.com/Anuken/Mindustry-Suggestions/assets/126210243/657c6739-651f-48ce-9d86-a8d349f8f6aa)

**Comment by Zeleniykustik** [comment]
It's not critical for me, but still.
