### ISSUE TITLE
Sector attack

### ISSUE THREAD

**Issue by Unknown-gamer041** [Anuken/Mindustry-Suggestions#4977]
### Describe the content or mechanics you are proposing.

For sectors with an adjacent enemy base, view when it's likely to be attacked, or a percentage of how likely it is to be attacked within the hour of gameplay.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Where to direct attention, or to be able to prepare for an upcoming invasion

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
mindustry is so slow an hour is reasonable
