### ISSUE TITLE
Fog of War (Paves the way for scouting, radar, and other tech)

### ISSUE THREAD

**Issue by RogueRedHawk** [Anuken/Mindustry-Suggestions#498]
---
name: Feature Request
about: Suggest new content or mechanics for Mindustry
title: ''Fog of War (Paves the way for scouting, radar, and other tech)"
labels: feature request
assignees: ''"

---
**Describe the content or mechanics you are proposing.**

From Wikipedia: "The fog of war (German: Nebel des Krieges) is the uncertainty in situational awareness experienced by participants in military operations. The term seeks to capture the uncertainty regarding one's own capability, adversary capability, and adversary intent during an engagement, operation, or campaign. Military forces try to reduce the fog of war through military intelligence"

It would be cool if you were not able to see enemy buildings or units outside of a certain radius of friendly buildings. A mechanic similar to the fog in LEGO Battles for the DS comes to mind because that is one of the few settings I'm familiar with this mechanic being used. There is also this version of chess known as Fog of War where you are only able to see pieces near your pieces.

Basically, anything outside of some arbitrary distance away from your team's buildings/units-- say, 25 blocks for example-- will be concealed in grey fog. You are still able to see the terrain and potentially resources outside of this fog, but not enemy units or buildings.

This could be implemented in multiple ways. It could be a map setting, an environmental effect like just "fog" or potentially an effect that happens during several weather events (sandstorm, snowstorm), or it could just be added to the game.

You would not be able to see enemy units/buildings on the minimap outside of your new view distance, 25 tiles radius from your buildings.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

As a feature in general this suggestion may seem pretty mundane. However, I think it could add very dynamic aspects to the game in several ways. It does not fill a niche, but rather creates many new and interesting strategic niches.

1. New niche for scouts/patrols. Now that is impossible to see opponents bases on the minimap, there is room for a few new drones with no weapons that have cloaking technology, allowing them to scout out enemy bases without detection. These cloaks would be timed, e.g. low level has 15sec cloaking, then 30sec cloaking upon upgrade, etc. The clock would activate upon coming within range of a turret. Regardless of the implementation, the niche is there. Additionally, stronger units could be set to patrol outside walls with processors.

2. New niche for radar. Radar reveals enemy bases and troops in a certain radius significantly larger than the fog, perhaps even the entire map. This output could be directed towards processors which output to displays (outputting an angle and distances to enemy objects) allowing the community to program their own radar displays, or the results could just be sent out periodically in the form of the "classic" minimap data. Regardless of the implementation, the niche is there.

3. New niche for sabotaging supply lines. It would very cool to be able to cut off thinly defended supply lines, cutting off the main base from vital resources. With the Fog of War, it would be hard to determine whether enemies occupied the area between the resources production and the core if the supply chain of conveyors was cut off. Depending on the way radar would be implemented a small army of basic mechs could be placed at the midpoint threatening the presence of stronger units.

4. Hidden bases. If this was update it could be possible to make an island base or a secluded base producing units or resources that goes undetected. This would make scouting important yet again.

I think this should be added because I don't like the way you can just see entire enemy bases on the minimap, or if you're on mobile you can just pause and go look at the entire enemy base if it's single-player against A.I. This could also be a small indirect buff to the A.I. enemy as they might be able to know stuff a player wouldn't know, but I don't know.

I understand there might be some issues with this idea. It pretty significantly changes the amount of intel of the enemy a given team has for free. I think this is a good thing, others may think it's a bad thing. Let me know what you think.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
Also how do I add a "Feature Request" label?

**Comment by SupremeTurtle** [comment]
You could just suggest a setting of the intensity of light from units, power, etc to clear "fog" from environmental light

**Comment by Syncinus** [comment]
This seems like an interesting mechanic

**Comment by mangblekok** [comment]
I like this idea!
It's exactly like any RTS game like C&C and Red Alert (and so on), the existance of Fog of War mechanic is very useful to increase complexity of the war phase, because the enemy can't be seen without being scouted first. And also it can open up more interesting technology like Fog Generator to counter against Radar and so on.

But on Community Server, players can just fly around the map to clear up the fog, so there should be 2 types of fog.
Black Fog = Completely unexplored areas.
Grey Fog = Explored area, but cloaked again after some time. Any enemy units & buildings under these fog should be hidden.
