### ISSUE TITLE
Option to locate walls and any buildings  in unit locate logic function

### ISSUE THREAD

**Issue by rylid-umil** [Anuken/Mindustry-Suggestions#4980]
### Describe the content or mechanics you are proposing.

An option to make units locate wall buildings or any type of buildings in the logic Unit Locate function. Does exactly waht it says, locating walls, and any buildings will locate any building type (whether there is priority system is up to you).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think these two new logic functions will be useful in some cases, or just if someone for example made a map full of enemy walls and wants to see units destroy them. Or like attacking a base, destructing the base bit by bit, not caring about what block it targets, since the old command system was removed. (not a suggestion to re-add it)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by walksanatora** [comment]
this is a idea I just got so I +1 it
