### ISSUE TITLE
Change wall graphite

### ISSUE THREAD

**Issue by Novanox4** [Anuken/Mindustry-Suggestions#4981]
### Describe what you would like changed, and why.

I want the graphitic wall to be changed and behave like wall tungsten, wall berryilium and wall thorium cause for graphitic walls to actually look nice they need to be next to carbon stone walls

### Describe the changes you want to propose. Include possible alternatives.

Rename graphititc walls to something like wall graphite or graphite chunks and make it act like all the other wall ores so they can be placed on any wall because this would open up so many doors in mapmaking. The current design of graphitic walls is very limiting, and it's like making wall berrylium only placeable on berrylic walls or wall thorium be only placeable on crystal walls. Now, I think graphitic walls should be kept in the game exactly the same but make them hidden from the editor, the reason being to not break literally every erekir map made until now.

**Comment by jehosula** [comment]
yeah why the hell did anuke not have it like this from the start

**Comment by S0meM** [comment]
I've wondered the same thing.
