### ISSUE TITLE
Hydroengineering

### ISSUE THREAD

**Issue by kokos1239** [Anuken/Mindustry-Suggestions#4984]
### Describe the content or mechanics you are proposing.

the ability to manipulate the presence of bodies of water in the map by evaporating, placing machines that create shallow and deep water in the map

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

im obsessed with water transport, but enough about me, i think navy in the game should be expanded and this may be A way to do so,  making the map more accessible for naval units, canals etc

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
no, let's not add terraforming, also the water is infinite, how do you move an infinite amount of water
navals are also balanced by only being usable in water filled maps
