### ISSUE TITLE
UI improvements to non English languages

### ISSUE THREAD

**Issue by PiPolaris** [Anuken/Mindustry-Suggestions#4985]
### Describe what you would like changed, and why.

So basically I wanna suggest you guys to improve the UI to accept texts with different sizes because we do have another ways to say the same thing and sometimes it's bigger than others.

### Describe the changes you want to propose. Include possible alternatives.

Example, why do I have a 3440px1440p and the menu is so thin and shy? The content still doesn't have enough space 😢 
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/38109245/2b166d2f-5034-401d-8607-57f69fd7f40b)

**Comment by S0meM** [comment]
That does look very weird.
