### ISSUE TITLE
Friend list

### ISSUE THREAD

**Issue by Kaganpromax** [Anuken/Mindustry-Suggestions#4987]
### Describe the content or mechanics you are proposing.

It's friend list and easy connect to server

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Friend list

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
so yet another idea involving anuke run servers(that cost money btw) with no real benefits since you can just use claj and such

**Comment by broganeuquoixe** [comment]
@Kaganpromax if you want this functionality just buy the steam version of the game

**Comment by Slotterleet** [comment]
Servers cost money. Mindustry is a free game with no ads or microtransactions whatsoever. So please support the dev by buying it on Steam :wink: (P2P multiplayer included)

**Comment by WilloIzCitron** [comment]
> Servers cost money. Mindustry is a free game with no ads or microtransactions whatsoever. So please support the dev by buying it on Steam 😉 (P2P multiplayer included)

actualy non-profit game

**Comment by KrisAppi** [comment]
> > Servers cost money. Mindustry is a free game with no ads or microtransactions whatsoever. So please support the dev by buying it on Steam 😉 (P2P multiplayer included)
> 
> actualy non-profit game
This IS a paid game on steam but yea. Anyway a friends list is on steam anyway so it doesnt really matter
