### ISSUE TITLE
surge conveor/artillery tower

### ISSUE THREAD

**Issue by 1233413** [Anuken/Mindustry-Suggestions#499]
**Describe the content or mechanics you are proposing.**
Aurge conveyor can be like plastanium conveyor but faster or super fast conveyor.
Artillery tower ok that can be slow strong tower will use blast compound area damage guaranted

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
New conveyor is like more fun and that can make game easier.
There is not that much towers like artillery and blast compound has nearly no uses (it have some uses).

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> Aurge conveyor can be like plastanium conveyor but faster or super fast conveyor.

There is no need for this. Use plastanium.

> Artillery tower ok that can be slow strong tower will use blast compound area damage guaranted

Use existing artillery turrets.
