### ISSUE TITLE
手柄控制

### ISSUE THREAD

**Issue by Yrckam** [Anuken/Mindustry-Suggestions#4990]
### Describe the content or mechanics you are proposing.

Add the ability to control the game with the handle

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Some people will want to play games with a controller, but I can't use it when I link it. I don't know if there is this problem on the desktop, but the mobile terminal is absolutely available.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [ ] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yrckam** [comment]
Some people will want to play games with the controller, but when I link it, I can't use it. I don't know if this problem exists on the desktop, but it can't be used on the mobile terminal.

**Comment by camelStyleUser** [comment]
> [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

no you didnt
