### ISSUE TITLE
Title Expansion of the serpulo campaign

### ISSUE THREAD

**Issue by xASSASYNx** [Anuken/Mindustry-Suggestions#4991]
### Describe the content or mechanics you are proposing.

Adding new planets and adding back the interplanetary accelerator, adding new resource plots, more air and land units and better cores

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The original campaign will finally be developed more and will be more enjoyable to play erekir is a symbol of laziness in terms of eagerness to finish the first campaign on serpulo

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Twcash** [comment]
/:
