### ISSUE TITLE
Добавьте синхронизацию со steam

### ISSUE THREAD

**Issue by 0maxim300** [Anuken/Mindustry-Suggestions#4992]
### Describe what you would like changed, and why.

Добавьте синхронизацию телефонной версии игры со steam, а то не удобно расскачиваться сразу на двух устройствах. 

### Describe the changes you want to propose. Include possible alternatives.

Добавить синхронизацию steam версии игры с мобильной, для удобства.

**Comment by camelStyleUser** [comment]
here we go cloud sync suggestion
(why should anuke spend money to run servers for a free game)
