### ISSUE TITLE
Make a portable build of Mindustry that keeps the data in the mindustry folder or allows you to configure where the data is stored.

### ISSUE THREAD

**Issue by stoltzld** [Anuken/Mindustry-Suggestions#4994]
### Describe the content or mechanics you are proposing.

Making Mindustry keep game save data in the mindustry folder or allowing the location to be configurable would allow people to run it from flash drives at various computers.  It would also easily allow running multiple different versions for testing and such without having to import and export data.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow more people to easily test the nightly builds.  It would allow people who don't own their own computer or phone to play more easily.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by phinner** [comment]
You can do it by using the environment variable `MINDUSTRY_DATA_DIR`.
You specify the location of the data directory with that and voilà.

**Comment by stoltzld** [comment]
> You can do it by using the environment variable `MINDUSTRY_DATA_DIR`. You specify the location of the data directory with that and voilà.

Awesome.  That is good to know.  Thank you.
