### ISSUE TITLE
Fire

### ISSUE THREAD

**Issue by RonLovesMindustry** [Anuken/Mindustry-Suggestions#4995]
### Describe what you would like changed, and why.

I like to say to the dev to nerf fire spread, not only it was op but the enemies only send 1 troop and the fire just spread everywhere

### Describe the changes you want to propose. Include possible alternatives.

You guys should make the fire got more delayed or you can make the fire didn't spread to the conveyor belt

**Comment by itcannotbe** [comment]
**Describe what you would like changed, and why.**

Buff @RonLovesMindustry intelligence level.

**Describe the changes you want to propose. Include possible alternatives.**

Give the person knowledge that a Wave fed by water can put out fires.

**Comment by camelStyleUser** [comment]
millions must water wave

**Comment by camelStyleUser** [comment]
~~who is "guys" anyway~~

**Comment by jehosula** [comment]
> ### Describe what you would like changed, and why.
> Buff @RonLovesMindustry intelligence level.
> 
> ### Describe the changes you want to propose. Include possible alternatives.
> Give the person knowledge that a Wave fed by water can put out fires.

i agree, this guy is clearly suffering from low iq / stage 4 skissuephrenia 
bro just needs to realize that water waves put out fires

**Comment by MEEPofFaith** [comment]
I can't remember if the game actually mentions that somewhere.

**Comment by S0meM** [comment]
It doesn't in any tutorials, but it is intuitive. Maybe we need to add a tutorial for that, or something. On another note, fire spreading and damage is based on ammo. Pyratite greatly increases the spreading of fire. Though this might not be applicable in this case. They haven't provided enough info.

**Comment by MEEPofFaith** [comment]
No, no it does mention. https://github.com/Anuken/Mindustry/blob/8fca7aa832ddc8bd6edb8ad94bca43981ef08e65/core/assets/bundles/bundle.properties#L2142

**Comment by S0meM** [comment]
> It's only mentioned in the descriptions of wave and tsunami. https://github.com/Anuken/Mindustry/blob/8fca7aa832ddc8bd6edb8ad94bca43981ef08e65/core/assets/bundles/bundle.properties#L2142

I personally found that sufficient.

**Comment by S0meM** [comment]
Does fire exist on erekir? I can't remember, but I don't think so.
