### ISSUE TITLE
Más cosas

### ISSUE THREAD

**Issue by EDSC-SS** [Anuken/Mindustry-Suggestions#50]
Propongo que se puedan trasar rutas para que los bots las siguan asiendo una "patrulla"y más opciones en modo editor, gracias :)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ado1928** [comment]
Google translate: 

> ### More Things
> I propose that routes can be transferred so that bots continue to be a "patrol" and more options in editor mode, thanks :)
