### ISSUE TITLE
Better readability for Jump block

### ISSUE THREAD

**Issue by ThunderFound** [Anuken/Mindustry-Suggestions#5000]
### Describe what you would like changed, and why.

Sometimes it becomes hard to distinguish arrows when there is many Jump blocks
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/90287659/e096eccf-58e2-4f46-abb1-2a9ee5f5bf4c)

### Describe the changes you want to propose. Include possible alternatives.

 - Further the arrow goes - more it curves 
 - Dfferent jumps are different colors (credit to @Twcash)
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/90287659/4b7425dc-bd39-4d5c-a622-6d372fad447e)

**Comment by Twcash** [comment]
or have it where different jumps are different colors

**Comment by jehosula** [comment]
i am generally against stuff that helps logic
but this issue just makes it harder to build code but does not impact functionality at all

**Comment by camelStyleUser** [comment]
then distinguish via their destination its quite literally shown there in the name
