### ISSUE TITLE
Baiting Neoplasm units

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5001]
### Describe the content or mechanics you are proposing.

So everyone knows how crawlers want to attack blocks from conveyor tab, flares hate power geneartors and most of the units don't like a specific block type and want to destroy it.
So, i think that Neoplasm units can attack blocks containing water.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

In my opinion it will add realism, because as an "animal", Neoplasm doesn't want to die, and so it needs food, which in this case is water.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
the neoplasm should not prioritize them that much tho, it will make it too easy and too much like the crux
