### ISSUE TITLE
Objective (Map Making)

### ISSUE THREAD

**Issue by GoldGoldie** [Anuken/Mindustry-Suggestions#5005]
### Describe what you would like changed, and why.

Objective needs to have more content somewhat close to Logic.

### Describe the changes you want to propose. Include possible alternatives.

What i mean in content is having bitwise "or"/"and"/"xor", "random" and etc. to have more complex objectives when making maps.

**Comment by camelStyleUser** [comment]
just use logic

**Comment by camelStyleUser** [comment]
objectives are **NOT** replacements for world logic

**Comment by camelStyleUser** [comment]
and how would xor even work

**Comment by Leo-MathGuy** [comment]
> objectives are **NOT** replacements for world logic

Yes, moreover, with flags, world logic and objectives are *designed* to work together

**Comment by SITUVNgcd** [comment]
For future, we can use Logic filter in map editor and Map maker (objective) in world logic.
You can test them in BE build.

**Comment by octopuscaat** [comment]
> For future, we can use Logic filter in map editor and Map maker (objective) in world logic. You can test them in BE build.

where do I find BE build?

**Comment by SITUVNgcd** [comment]
> > For future, we can use Logic filter in map editor and Map maker (objective) in world logic. You can test them in BE build.
> 
> where do I find BE build?

https://github.com/Anuken/MindustryBuilds
