### ISSUE TITLE
Oil on! Complete oil rework 

### ISSUE THREAD

**Issue by DapalDev** [Anuken/Mindustry-Suggestions#5006]
### Describe the content or mechanics you are proposing.

Hey Dapal here,

Over the past years I've played Mindustry, I noticed a big problem.
It is oil usage, you see oil is pretty useless you only use it for plastanium and to make coal or even for wave with slug combo. 

So that's why I re-imaginated Oil usage! 

First off new oil types! 

Raw oil
Gasoline
Kerosene
Diesel

I will explain their use and how to get them

So you start off by pumping raw oil normally or making it with spores press

What can you do with that raw oil? Well everything you can do currently in game 
Plastanium, coal making, pvp usage 

But now, you can put it in a Oil refenery! 
The oil refenery is a 3x3 building wich cost 100 plastanium, 50 thorium, 150 titanium, 50 metaglass and 100 silicon
It consumes 500 power

There are 3 recipes you can make : 
15 Raw oil to 5 gasoline 
10 Gasoline to 5 diesel 
7.5 Diesel to 5 kerosene 

You can do something else with that raw oil you can put it in a combustion engine! 

The combustion engine cost 250 titanium, 50 Graphite, 25 plastanium and 50 silicon to make
The combustion engine can take raw oil gasoline and diesel to make power out of it. 
It is 2x3
But
the better the oil quality the more electricity so like : 
25 raw oil makes 500 power
15 gasoline makes 750 power
10 diesel makes 1000 power

Alright that's cool but what if im end game and I make most my power off nuclear explosion reactor etc etc and needs way more oil types

Well fear not! 

Advanced oil refenery! 
This time it is 4x4
Cost 150 surge alloy, 200 silicon, 100 metaglass, 300 titanium 
It consumes 1000 power
So this time it uses water in addition 

So 50 raw oil and 30 water to 40 gasoline 
45 gasoline and 30 water to 30 diesel
35 diesel and 30 water to 20 kerosene 

Alright i produce mass oil types now but what about electricity? 

Here I present to you... 
Reaction Engine! 
This time 3x4
Cost 350 titanium, 100 surge alloy, 150 graphite and 100 thorium
This times way better rate and it can tzke kerosene in more
But. 
It cannot take raw oil and needs slug
So 50 gasoline and 25 slug to 2000 power
35 diesel and 20 slug to 2500 power 
20 kerosene and 15 slug to 3000 power

So now that we have that can we use it for pvp? 
Well we sure do
In general, 
Raw oil will be the same as used in wave with combos with slug
Gasoline will be more flammable (need slug combo) 
Diesel will create a small explosion (need slug combo) 
Kerosene will create a medium explosion and will explode if anything touches it and i mean it. Don't make it leak out of a pipe

Other mechanic (optional) 
All engine can be combined if they are the same type and put in the horizontal way sticked to each other (this means the oil needed will be doubled) 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it will improve the in game life and create evn more engineer feelings and give fluids more usage even more to oil
I noticed there wasn't new ways of making electricity and making oil to make power is pretty good to revive the usage of it in game
Also for pvp the new oil types can be really useful like kerosene (even tho chaotic, don't make it leak somewhere in the base)
And it will improve the gameplay a lot as it is a bit complex but simple at the same time.
I think all players will appreciate having a new usage for oil :DD

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
1 plastanium is kinda essential and ground oil makes absurd amounts of coal
2 you are just adding all these resources that are on their own used so much less than normal oil, just making the problem you wanna fix even worse
3 the way you get oil makes it not really take anything other than space and power so it can't really be useful for much on its own
4 WHY DOES IT NEED TO MAINTAIN USUAGE?? there are few resources that do that much, most of them are just used for the same stuff and there is not a single power generator with an enhanced version besides combustion generators
5 volatile materials are not very balanceable see air unit kamikaze

overall this is a cool mod idea but should never touch vanilla

**Comment by overdramaticpanromantic** [comment]
sounds like you want factorio in mindustry. blocks can't be anything other than a square, btw

**Comment by camelStyleUser** [comment]
> sounds like you want factorio in mindustry. blocks can't be anything other than a square, btw

or can they

**Comment by Mythril382** [comment]
> > sounds like you want factorio in mindustry. blocks can't be anything other than a square, btw
> 
> or can they

*insert vsauce music*

**Comment by overdramaticpanromantic** [comment]
real (it is technically possible but requires a lot of weird stuff and jankiness)

**Comment by Haznobrain** [comment]
also add the USA, a new faction wich will attack you the moment you find oil, so it's more realistic

**Comment by jehosula** [comment]
> also add the USA, a new faction wich will attack you the moment you find oil, so it's more realistic

PROBABLY THE BEST COMMENT HERE

**Comment by Haznobrain** [comment]
> > also add the USA, a new faction wich will attack you the moment you find oil, so it's more realistic
> 
> PROBABLY THE BEST COMMENT HERE

thanks lmao

**Comment by StesNiash** [comment]
hell nah too complicated for 1 material

**Comment by Haznobrain** [comment]
> hell nah too complicated for 1 material

i agree, it's why i just joked about it in my first comment
