### ISSUE TITLE
Virtual flags / unique identifiers for enemy units

### ISSUE THREAD

**Issue by TopCatTC** [Anuken/Mindustry-Suggestions#5007]
### Describe the content or mechanics you are proposing.

Allow logic to set a virtual flag for enemy units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A new function will allow logic to assign enemy units to a virtual flag not visible by the enemy. It works the same as flags already in game, serving as a method of assigning a unique identifier to enemy units that can be read by other processors. Allows for more possibilities with larger and more complicated unit logic designs.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
so you have came a little too close and now the whole enemy army will forever chase you til the end of time
jokes aside i don't really know how to feel about this because it buffs logic procs

**Comment by TopCatTC** [comment]
It wont affect pvp much since in such an environment, manually commanding the units is much cheaper and more effective than having a massive expensive cluster of hyper procs. I made this suggestion with multiplayer survival in mind.

**Comment by walksanatora** [comment]
So you could assign a "risk level" perhaps?
