### ISSUE TITLE
Coop gameplay

### ISSUE THREAD

**Issue by Luk0510** [Anuken/Mindustry-Suggestions#5008]
### Describe the content or mechanics you are proposing.

Coop Gameplay, together in open game and / or campaign.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I would recommend that in a coop game that both users can see what the otherone is building / planning to build. 

I would also recomment (even more important than the first recomendation) that in a coop-game both players can do research....thats realy paint right now. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
do you understand how much will it increase the bandwidth used especially with large schematics

**Comment by camelStyleUser** [comment]
and research code needs to be refactored for network syncing and research.mindustry is nearing its end.that isnt happening

**Comment by Luk0510** [comment]
> and research code needs to be refactored for network syncing and research.mindustry is nearing its end.that isnt happening

just giving my input :) 

maybe it would be possible that you can see the research tree and the current status. It would be okay if only the host can controll the research but the other players should be at least have the possibility to see where are we, what possibilities do we have, what comes next. 

But i understand that it is a lot of change, as i mentioend it....only my input.

**Comment by Luk0510** [comment]
> do you understand how much will it increase the bandwidth used especially with large schematics

yea....would be a lot higher. This suggestion is no big deal, you just have to talk more.....that works fine. The other one with the research is in my eyes the bigger deal.
