### ISSUE TITLE
more Resource

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry-Suggestions#501]
Add more resource to game, there is not much resource.

my suggestions is :

Silver

Carbon

Platinum

Cassiterite

Steel (Iron+Carbon]

Aluminum

Boron

Add one of them or all of them or non of them and add different resource, I just wanna see more resource in game

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
You didn't even fully filled out in the template and broken it's formatting.

**Comment by Anuken** [comment]
> I just wanna see more resource in game

More resources without valid uses are pointless. I'm capable of finding names for resources myself.

**Comment by potatoisagender** [comment]
there are mods for this.
