### ISSUE TITLE
Mindustry lore for campaign

### ISSUE THREAD

**Issue by mahdoosh1** [Anuken/Mindustry-Suggestions#5010]
### Describe the content or mechanics you are proposing.

a lore for mindustry campaign would be very promising and so many players dont even know the story.

a guiding charactor that will explain the game and tell the story would be a good starting point.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will make mindustry enjoyable, most players (me as well) are not playing mindustry because it has no story and its only gameplay, everybody would love to see the story.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
why would you want to just read all the lore instead of piecing it piece by piece in different core database entries

**Comment by camelStyleUser** [comment]
and that doesnt make sense from a lore standpoint

**Comment by camelStyleUser** [comment]
you are just a robot fighting other robots

**Comment by mahdoosh1** [comment]
> why would you want to just read all the lore instead of piecing it piece by piece in different core database entries

database entries?

**Comment by mahdoosh1** [comment]
> and that doesnt make sense from a lore standpoint

no, i want the lore to be explained as the game goes further. not all of the lore at once

**Comment by mahdoosh1** [comment]
something like:


hey, i am your guide, this sector is called ground zero, where you start progressing from now on, use your mouse or finger to mine resources.

...

*sector captured*

ok, the units you fought were from a team called Crux, they have a lot of bases everywhere on this planet, your job is to destroy important sectors and defeat Crux, your team's name is Sharded, basically... *starts explaining part of the story*

*next sector captured*

ok, here is what happened next *explains the next part of the story*

**Comment by octopuscaat** [comment]
I believe the lore is vague by intent.
