### ISSUE TITLE
Allow World Processors to Force Players into Units

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#5011]
### Describe the content or mechanics you are proposing.

allow world processors (perhaps via Set Property) to set the unit a player is controlling or transmute it into another unit

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would increase the number of features for mappers to use. some uses off the top of my head would be making a "cutscene" that has a mega drop in a dagger for you to control until you reach the core (or mabey a mace/etc) basically just missions where you have to "capture" the core before it lets you start base building

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by walksanatora** [comment]
for example (from red alert 3) https://youtu.be/DDVwCZFg_QA?t=160

**Comment by octopuscaat** [comment]
no
