### ISSUE TITLE
Achievemnts

### ISSUE THREAD

**Issue by Scarfman1** [Anuken/Mindustry-Suggestions#5014]
### Describe the content or mechanics you are proposing.

You should add achievemnts to mobile version like on steam, but in Google play.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

To will be cool, Also people Can Grund fór achievments

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Make the google play version paid first.

**Comment by mahdoosh1** [comment]
> Make the google play version paid first.

and that will cause a lot of controversy, 

people with the steam version would argue that why is it free for mobile
and people who want to play the game would have to download it from fdroid or itch.io

**Comment by octopuscaat** [comment]
its not free for mobile

not for app store anyway

**Comment by mahdoosh1** [comment]
> its not free for mobile
> 
> not for app store anyway last time I checked

That's app store, very expected.

**Comment by camelStyleUser** [comment]
> its not free for mobile
> 
> not for app store anyway last time I checked

only on iOS and there its not free because developers need to pay 100$ every year.
thanks apple :smiling_face_with_three_hearts:

**Comment by itcannotbe** [comment]
> > its not free for mobile
> > not for app store anyway last time I checked
> 
> only on iOS and there its not free because developers need to pay 100$ every year. thanks apple 🥰

You should have let this issue die instead. Thanks for nothing.

**Comment by camelStyleUser** [comment]
> > > its not free for mobile
> > > not for app store anyway last time I checked
> > 
> > 
> > only on iOS and there its not free because developers need to pay 100$ every year. thanks apple 🥰
> 
> You should have let this issue die instead. Thanks for nothing.

thanks for not letting it die too :smiling_face_with_three_hearts:
