### ISSUE TITLE
Lua-controlled world processors

### ISSUE THREAD

**Issue by TheEt1234** [Anuken/Mindustry-Suggestions#5016]
### Describe the content or mechanics you are proposing.

So basically have a only server-ran (with functions to send data to clients) lua world processor

 # how it can be achieved
- 1) i am pretty sure someone already ported lua to mindustry or java at this point
- 2) sandboxing can be done with setfenv (lua 5.1 or luajit) or the env parameter in load, and just don't allow any bytecode
- 3) limiting can be done with debug hooks
- 4) depending on how you want it done, you can use the minetest's mesecons mod's luacontroller aproach (that aproach has sorta faulty limiting, so i recomend limiting based on time) or some coroutine aproach

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

would be easier to code complex things in it, and allow for stuff like *string manipulation* and tables, thats really it

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[no](https://github.com/Anuken/Mindustry-Suggestions/issues/3516#issuecomment-1107355182)

**Comment by walksanatora** [comment]
why add a entirely new languague. when anuke could just sandbox some JS for processors

**Comment by mahdoosh1** [comment]
are you trying to make Doom in mindustry?

**Comment by TheEt1234** [comment]
oh k
