### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Yrckam** [Anuken/Mindustry-Suggestions#5019]
### Describe the content or mechanics you are proposing.

Add the choice of musical instruments and tones in the logical commands of the game, and then use the sound through the speaker.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There are some maps in the game that are boring to play later, but I want to find something to do, so I want to use music to solve the boring problem.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
[I have not checked the Trello to make sure my suggestion isn't planned or implemented in a development version](https://trello.com/c/yij5RfGc/734-logic-sound)
