### ISSUE TITLE
QoL: Play/Pause button adjustments on mobile interface

### ISSUE THREAD

**Issue by enigmafyv** [Anuken/Mindustry-Suggestions#502]
**Describe the content or mechanics you are proposing.**

Please (1) move play/pause button to a separate location (top right?), (2) resize (slightly bigger), and (3) allow for adjustable transparency on mobile interface.  Currently the surrounding buttons (schematics & core database) get hit too often instead.  (I got fat fingers, sorry.)  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Less fumbling, trying to pause/play the game, while building.  Related but separate issue: I've tried to scale the UI bigger, to make pressing the play/pause button easier, but that ended up causing odd image artifacts where I could see images of buildings or units instead of the intended icon/image where the button should be.  This was on an Android (LG V20) phone.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Having artifacts of other sprites that aren't supposed to be there is a sign that your phone doesn't have enough video memory to support a higher sprite size.

Blame your phone. Not the game.

This maybe also due to you using a number of mods that significantly add more sprites to the game that it needs to load in that leads to corruption due to the lack of available space in your video memory.

**Comment by enigmafyv** [comment]
Not sure why this has to be about blaming someone/something.  I'm surly not blaming here, just listing my observations.  Not sure why immediate hostility is the first response.

Also, how is having 4GB total, and 700+MB free, isn't enough to support the game that at maximum only uses 108MB of total memory?  I'm only running the base game and have not installed any mods.  I only happened across this game last week and I'm a purist until I've completed the campaign in all games.  What's more, I currently have no clue how to add mods to my phone, again due to such a brief time with the app and only want to play the game as it was intended by the original developer/author.

I love this game, I think it's one of the best and only getting better, and I'm all for supporting the developer financially (already paid for it on Steam and will donate more money if it means helping to support) but I don't agree to pay for hostility.  I've no clue what your role in Mindustry is @itcannotbe, but I don't believe you're helping Anuke's cause by being so flippant to people that want to help.

**Comment by itcannotbe** [comment]
I guess the bug report you made that the developer already closed isn't enough proof that it is.

**Comment by enigmafyv** [comment]
Yeah, isupposeyoureright.  No need to fund this project anymore.  You right.

**Comment by itcannotbe** [comment]
For transparency:

My phone can do a ui scaling up to 200% above 200% causes corruption.

And this is a 4 year old phone and my phone's OpenGL 2.0 implemetation provides a max texture size of 8192.

**Comment by potatoisagender** [comment]
I think that @itcannotbe could have been a little less blunt with their replies. What he is trying to get at is that the problem has to do with your phone, and that the developer won't be able to help you much. They've seen a lot of stupid requests, and as such have no patience. They are trying to correct the implied ideas they are getting from your text.

**Comment by mwoehlke** [comment]
@itcannotbe, GL max texture size is detectable. If that's the issue, the game ought to be able to detect when it is going to be an issue and not allow UI scaling in such case. That said, only happening at different scales sounds like a bug, though it might be a shader problem or, yeah, a problem with the device's GPU.

That said... I have the same problem as (1). It would be less of an issue if the game just had an option to _pause_ in the tech tree screen; it would still be annoying, but less likely that something bad would happen at a critical moment.
