### ISSUE TITLE
针对iOS的优化。

### ISSUE THREAD

**Issue by Adell233** [Anuken/Mindustry-Suggestions#5020]
### Describe the content or mechanics you are proposing.

IOS 's Mindustry is limits.But can you optimize some of the necessary functions?For example,I have a module, and this module has a planet, but it's written in javascript, and iOS doesn't work it.It's iOS, not Macos.So I hope you can optimize it.I'm Chinese.So my English is not so good.Please forgive me.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Open more interfaces for ios

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You do realize that apple store guidelines prevent developers from doing this.

    2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps.
    [Apple App Store Guideline](https://developer.apple.com/app-store/review/guidelines/)

**Comment by camelStyleUser** [comment]
did you read apple store developer guidelines?

**Comment by Slotterleet** [comment]
Confirmed, it's literally prohibited by Apple - see the link above.

**Comment by Adell233** [comment]
> did you read apple store developer guidelines?

no,but now know,thanks
