### ISSUE TITLE
Add logic line to get payload in unit/building (not payload type)

### ISSUE THREAD

**Issue by StesNiash** [Anuken/Mindustry-Suggestions#5022]
### Describe the content or mechanics you are proposing.

add code that allow to sensor payload in unit/building by index (0,1,2 etc.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will allow some advanced processors
cause you will be able to sensor bullets, heat, items and other things
its already half possible but to make it you need to save block in variable while it still placed which decreases possibilities for massive ai processors

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by StesNiash** [comment]
> like with basically every logic suggestion i would like this as a wproc feature but not as a normal proc feature because those are too op

why tho? this feature wont add anything too OP
you will only be able to get info from payload like max HP, items in it and other

Imagine making container distribution on payload conveyors with this one
that would be really awesome

**Comment by jehosula** [comment]
> why tho? this feature wont add anything too OP you will only be able to get info from payload like max HP, items in it and other
> 
> Imagine making container distribution on payload conveyors with this one that would be really awesome

for me a buff is a buff
