### ISSUE TITLE
Programmable drone

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry-Suggestions#5024]
### Describe the content or mechanics you are proposing.

a small flying drone with a small gun that would deal 5 damage per shot with 4.5 shots per second, it'd have 110 health, be as fast as a poly, and have 30% build speed as well as 90% mine speed. it'd also have 2 tiles of payload capacity and 50 item capacity.
You can have 3 drones per station and they take 25 silicon and 20 graphite to build, and you program the drone there with the same kind of thing as logic blocks.
the station would take 90 copper, 90 silicon, and 80 graphite to build and would be a 3 by 3.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It'd be a unit that can be programmed to do things like fly around the base and shoot ennemies that come in, you could set up a loop where the unit goes around the base, maybe automatically build some stuff or something, basically be like a cheaper poly with sandbox behavior. The unit would do nothing if you don't give its station a program to follow, there could be some presets you can choose for the programs but nothing too complex (ex: a basic stand still and shoot ennemies program, a basic build helper program, etc), and you can only use one program per station (each drone is bound to the station it was built by and uses the program of the station it was built by.)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
is this just a t1 poly that ignores unit cap and has built in logic?
also the payload capacity is kinda silly

if you know v5 then you would realise this will get spammed like crazy especially when unit cap starts being is issue
the problems with this is redundancy and the lack of a unit line and ignoring the unit cap

**Comment by Haznobrain** [comment]
> is this just a t1 poly that ignores unit cap and has built in logic? also the payload capacity is kinda silly
> 
> if you know v5 then you would realise this will get spammed like crazy especially when unit cap starts being is issue the problems with this is redundancy and the lack of a unit line and ignoring the unit cap

maybe an unit cap of like 40 or smthn then, but still max 3 drones per station

**Comment by jehosula** [comment]
> maybe an unit cap of like 40 or smthn then, but still max 3 drones per station

i didn't check the notifications so the reply was late but anyway 

how is the unit cap of 40 supposed to work with upgrading the core or having multiple cores also 
it does not serve any actually unique function or does much that well
and it kinda forces learning logic to use

like i swear these people making suggestions don't know the game anywhere near as much as they claim by ticking the second box

**Comment by Haznobrain** [comment]
> > maybe an unit cap of like 40 or smthn then, but still max 3 drones per station
> 
> i didn't check the notifications so the reply was late but anyway
> 
> how is the unit cap of 40 supposed to work with upgrading the core or having multiple cores also it does not serve any actually unique function or does much that well and it kinda forces learning logic to use
> 
> like i swear these people making suggestions don't know the game anywhere near as much as they claim by ticking the second box

i mean the max amount of these drones could be 40
+ my idea was that you could make a program to make them completely automated polies, except they can transport large quantities of items and then fix blocks nearby and attack ennemies, and go help the player when he's building stuff
also it won't force you to use logic, you can still just use polies

**Comment by jehosula** [comment]
> i mean the max amount of these drones could be 40
> 
> * my idea was that you could make a program to make them completely automated polies, except they can transport large quantities of items and then fix blocks nearby and attack ennemies, and go help the player when he's building stuff
>   also it won't force you to use logic, you can still just use polies

lemme list out the issues with this
1 it's very redundant
2 logic is already too important and this block is completely unusable without it let's not make mindustry a coding game
3 the total amount of drones will have to be the usual unit cap
4 it won't fit in with literally every unit from a factory as it does not have tiers

it will just subvert the unit cap and make logic controlled stuff even more powerful overall and the lack of tiers does not help we moved on from v5 man
