### ISSUE TITLE
Inverted unloader

### ISSUE THREAD

**Issue by GamerUKgithub** [Anuken/Mindustry-Suggestions#5030]
### Describe the content or mechanics you are proposing.

thats just like the original unloader but inverted: unloads every item except selected.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

sometimes in schemes too little space for unloader, some items load in vault (1k) and not letting another load in

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
thanks for the laugh have a nice day

**Comment by mahdoosh1** [comment]
> thanks for the laugh have a nice day
> (yes this suggestion is bad)

no its not.
i like this suggestion

**Comment by walksanatora** [comment]
it is valid. but also reproducable with logic (just make it go through a selection of items you want to unload)
