### ISSUE TITLE
Contraptions

### ISSUE THREAD

**Issue by Tilted-Development** [Anuken/Mindustry-Suggestions#5032]
### Describe the content or mechanics you are proposing.

**Contraptions** could be for compounding schematics into one 1x1, 2x2 or 3x3 cube. Things inside the contraption connect to the outside by using _ports_; items, power, fluid, heat, logic and payloads. 1x1s can only have 4, 2x2s 8, and 3x3s 12. Simply Place the ports on the perimeter and they will be squashed in. Too much for that size, and it won't compress. Contraptions are just built from schematics, requiring titanium plates as well (which makes it strong ( to make sure it won't explode)).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**More complex creations!** With the need of titanium plates, it won't mess the game up too much (keeping the use of schematics). Just imagine a computer running Mindustry in Mindustry!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
this kinda removes the need for space management and it also would be tough with all kinds of things like inputs, floor tiles outputs etc
also for the space just play a bigger map, this kind of thing is just too much tbh it would simplify more than complicate and optimizing SHOULD be complicated

also there just is barely any reason to actually add this while the things it ruins are just too much and the actual implementation is quite complicated
and on top of all that it could be VERY laggy

**Comment by octopuscaat** [comment]
this invalidate the entire concept of scematics
