### ISSUE TITLE
A truly neutral team

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#5033]
### Describe the content or mechanics you are proposing.

A neutral team (not Derelict) that wont be attacked by AI but both
a. has buildings still functioning
b. but turrets/etc do nothing

this is *not* `Allied Teams` because this team does nothing except sit there.
(also team-specific things like passing through shields, or opening/closing doors work no matter who is doing said action to neutral buildings)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would be (another) tool for mappers. eg: making units appear off of the edge of the map only to then blink into a specific teams control (kinda like how in alot of Command and Conquer missions partway through the mission "reinforcements have arrived")

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
close the issue
