### ISSUE TITLE
Revamp asteroids as daily challenges

### ISSUE THREAD

**Issue by Lolnoizcool** [Anuken/Mindustry-Suggestions#5034]
### Describe the content or mechanics you are proposing.

Add daily challenges to the game and are accessible at asteroids. The challenges' modes are endless survival and attack.
Verilus (or Verlius) mainly focuses on Serpulo tech
Notva mainly focuses on Erekir tech (add a slag tiles generation for it or a slag-producing factory)
Gier mainly focuses on both planets' tech
The minimum threat level of these challenges is high and can be configurable to eradication

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Mindustry lacks replayability, so daily challenges might make it more enjoyable, and make asteroids necessary, not some unscraped junk in the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by mahdoosh1** [comment]
> I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

No you haven't. some of this suggestion is planned for v8+
which means it may happen in v9.
