### ISSUE TITLE
Erekir expansion

### ISSUE THREAD

**Issue by MindustryMyLove** [Anuken/Mindustry-Suggestions#5037]
### Describe the content or mechanics you are proposing.

It would be possible to add “non-story” sectors on Erekir, with unique enemy bases, waves of enemies, similar to numbered sectors on Serpulo, could also add a launch pad for the Erekir campaign

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This innovation would fill the holes in the Erekir campaign

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DX-36** [comment]
side sectors, sure that could be done, but in no way is erekir getting launch pads
Is the excessive thorium and carbide in the starting loadouts in sectors starting from siege not enough for you?

**Comment by GamerUKgithub** [comment]
erekir's idea is to be absolutely different from serpulo and, unfortunately, launchpads will not be here (i think).

whats about non-story sectors, i guess they will be added after campaign made fully. nice job!

**Comment by Haznobrain** [comment]
I think it was comfirmed that every numbered sector will be replaced by hand-crafted ones in V8 and above. So this suggestion is useless.
