### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by Noname0fm1nemas** [Anuken/Mindustry-Suggestions#5039]
### Describe the content or mechanics you are proposing.

when I entered this wonderful game with a gamepad, I saw that it did not work with a gamepad, I would like to see this function in the game, I myself am the owner of a gamepad.
Anuke fix it pls

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
> [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

no you didnt

**Comment by octopuscaat** [comment]
close the issue
