### ISSUE TITLE
multi legged unit mechanic

### ISSUE THREAD

**Issue by liliam2007** [Anuken/Mindustry-Suggestions#504]
**Describe the content or mechanics you are proposing.**
maybe units could target the legs of larger multi-legged units to hinder their movement speed and possibly destroy or immobolize them

 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this could make it more fun for each team or more difficult for players using multi-legged units since enemies could take out their legs

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This has been suggested many times before, but I'm not implementing it for technical and complexity reasons.
