### ISSUE TITLE
Add a list of connected blocks to the processor

### ISSUE THREAD

**Issue by Wintecks** [Anuken/Mindustry-Suggestions#5040]
### Describe the content or mechanics you are proposing.

You can also add a common name for devices. For example, if you have several factories connected to one processor, and in order not to write the name of the factory and its number in the control function every time, you can simply write this name once in capital letters or capital letters without numbers and all the factories with that name. it is also possible to connect processors to each other on different sectors and within the same sector

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this function will simply request and speed up CPU usage

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
> connect procs on different sectors

you do know that sectors are not just run in the background, right?

**Comment by camelStyleUser** [comment]
and for a list of all blocks linked to processor

**Comment by camelStyleUser** [comment]
guess what

**Comment by camelStyleUser** [comment]
we already have it

**Comment by camelStyleUser** [comment]
its called `getlink`&`@links`

**Comment by Winecks** [comment]
and can you please drop a link on how to work with these functions
