### ISSUE TITLE
sensor ammo

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5044]
### Describe the content or mechanics you are proposing.

allow sensor to sensor the specific ammo in the turret
like sensor @ copper in salvo1 returns the amount copper ammo in the salvo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this will allow a variety of options primarily with world logic such as 
making a turret in some kind of tower defense map behave differently based on the ammo
or making unique enemy bases that behave based on their ammo type
or not allowing certain ammo types to be used
or perhaps adding new mechanics to some ammo types

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by octopuscaat** [comment]
Best logic idea in a long time 
10/10
