### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by Lamanesuprame** [Anuken/Mindustry-Suggestions#5046]
### Describe the content or mechanics you are proposing.

Hi

I just think it would be cool if you could deconstruct units and place them on convenjors and even pick most of them up with the ship.    
Thanks

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Sometimes units get stuck in infrastucture and u dont want to deconstruct it. And after youve secured a sector and want to revisit it they just be laying around

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DX-36** [comment]
for deconstructing units erekir has this
units can place themselves on payload conveyors and other payload blocks
for picking up units a mega or quell can pick them up

**Comment by mahdoosh1** [comment]
> for deconstructing units erekir has this
> units can place themselves on payload conveyors and other payload blocks
> for picking up units a mega or quell can pick them up

a unit stuck on upgrading blocks cant move themselves onto payload conveyors
