### ISSUE TITLE
Big brain idea

### ISSUE THREAD

**Issue by khurtron6** [Anuken/Mindustry-Suggestions#505]
Tanks Units Unit that has wheels
Control Command center new function Follow and Set flag Set flag can Send a group of Units in that flag by using two finger or Hold Swipe to Add a group
Custom Laser Can Make laser has deferent type like Freezing Burning / incendiary and Beam And customable damage per sec and color
New Survival mode Breach Player must dominate order to win
More production more Enemy with Attack

**Comment by Anuken** [comment]
1. Already suggested
2. Already suggested
3. Groups for what?
4. Already in v6
5. Dominate what?
6. What?
