### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by Lamanesuprame** [Anuken/Mindustry-Suggestions#5050]
### Describe the content or mechanics you are proposing.

Just a reset button for a level bc it kinda easy to get yourself in a bad spot and no one to kill you.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Saves time when you know you already lost amd softlocked urself

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
-[X] OP is not familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by jehosula** [comment]
there is an abandon button that resets the sector, you clesrly are not familiar with all the content in the game
