### ISSUE TITLE
Expose "Targets Air/Targets Ground" for Units (just like Turrets)

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry-Suggestions#5052]
### Describe the content or mechanics you are proposing.

With Turrets, it's pretty straightforward and quick to check their info to see their viable targets. These should be exposed for Units as well.

This info is already shown in the table in the Wiki for Units. Having it in-game would allow players to rapidly confirm/re-check while playing.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Rapid and easy reference of unit info to check viable targets.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 1stMISHA** [comment]
This is an interesting mechanic for turrets, but not for units.
