### ISSUE TITLE
Expose item creation rates for Separator/Dissasembler in block info

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry-Suggestions#5053]
### Describe the content or mechanics you are proposing.

Currently, the various outputs are simply shown with their icons. There is no information regarding how much of each is produced. I couldn't find this information in the wiki either. I assume the only place to know is the code.

The output rate for each item should be shown in the game, as well as added to the wiki.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's clear from looking at the conveyor belt that the items aren't produced in equal ratios.

Right now, the only way to roughly gauge output is a clunky workaround where you turn off all other output sources for those ores, wait for 60 seconds, and then check the sector stat screen in the planet overview, which gives per-minute production.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
another no brainer suggestion there is a good amount of them but there are a lot of bad ones this is a good one tho
