### ISSUE TITLE
Expose power generation rates for different inputs

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry-Suggestions#5056]
### Describe the content or mechanics you are proposing.

Using the Combustion Generator as an example, giving it different inputs seems to cause it to generate different amounts of power. However, this is not exposed anywhere, whether in the game or the wiki. The game and wiki both list a single power generation number, likely for the most common input.

There is an inconsistency here because the game does expose differing rates for boosting provided by liquids, and turret damages for different ammo types, for example.

Thus, the game (and wiki) should show the actual power generation rates for each type of input the building can accept.

Another alternative is to show them as %age changes compared to the default/common input. The game does that already to show inefficiencies/efficiency boosts.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help the player plan their buildings better, by not having to guess or roughly estimate the obtained power using workarounds. They may choose to use differing inputs based on their situation.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
the power generated is flammability % of 60 power/s
coal is 100% of 60 so 60 power/s
pyratite is 140% of 60 so 84 power/s
