### ISSUE TITLE
make Bleeding Edge available on ios

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5057]
### Describe what you would like changed, and why.

add an ios version for bleeding edge on github
let's ios users play bleeding edge like my friend 

### Describe the changes you want to propose. Include possible alternatives.

add a download for an ios version of the BE releases that can be downloaded
possibly allow some other ways of accessing BE for ios

**Comment by itcannotbe** [comment]
iOS is not Android.
Sideloading barely exists on the platform.

**Comment by camelStyleUser** [comment]
please consider the reading

**Comment by camelStyleUser** [comment]
apple "sideloading" from websites still requires apple to authorize you and its only in eu
