### ISSUE TITLE
Smoke/Liquid Effect on Thorium Reactor

### ISSUE THREAD

**Issue by BnDLett** [Anuken/Mindustry-Suggestions#5058]
### Describe the content or mechanics you are proposing.

In order to properly run thorium reactors, you need to supply it with cryofluid. Given that cryofluid only remains in the system for so long implies that it is a system that expels the cryo gases (or liquid if it doesn't evaporate). With that stated, I believe that it would be more realistic if there was a smoke-like (similar to steam) effect when the reactor is running and has cryofluid in the system. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will not directly make the game better in terms of experience. Although, it will make the game more realistic and appealing in terms of visuals. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
> realistic

never seen conveyors move by themselves in real life
or turrets casting magic spells
or infinite ammo in units
or infinite ores

**Comment by BnDLett** [comment]
I hate to break it to you, but "the game isn't realistic to begin with" is a terrible argument. Sure, the game may include features that makes it unrealistic, but that doesn't necessarily mean that features that are realistic should not be added for the sake of adding more realness to the game.

**Comment by camelStyleUser** [comment]
and that feature gives nothing special and just makes the game require more power for rendering for no reason

**Comment by BnDLett** [comment]
> and that feature gives nothing special and just makes the game require more power for rendering for no reason

Unfortunately, this isn't 1995 where every last ounce of power matters. By your logic, reactors should not emit an effect upon explosion -- otherwise that would take up "more power" for "no reason."

**Comment by Dryehm** [comment]
> and that feature gives nothing special and just makes the game require more power for rendering for no reason

if you don't want it, disable it, there are other equally useless particles in the game so why bother? its just cosmetics to make the game look better than being bare bones.

**Comment by mahdoosh1** [comment]
> and that feature gives nothing special and just makes the game require more power for rendering for no reason

i disagree

if someone doesn't want to see those useless things that use "power for rendering", there is a toggle in the settings.

the game isn't made specifically for old computers or phones, it only supports them (for now, until 3d, maybe)

**Comment by goodsofa** [comment]
> > realistic
> 
> never seen conveyors move by themselves in real life or turrets casting magic spells or infinite ammo in units or infinite ores

I believe that this is really not about realism, but about the atmosphere (no pun intended) and how the game feels, i think it is a nice addition
