### ISSUE TITLE
Just a suggestion..

### ISSUE THREAD

**Issue by 3ARLB3NJI301** [Anuken/Mindustry-Suggestions#506]
Small Mechanics That I Think Would Be Great In-Game

•The Conveyor  Mechanic
-we should be able to choose which conveyor the drill/producer woul put out the resources like do we want them to put out the resources on /top/bottom/right/left conveyor so that they won't be puuting unwanted resources on a specific conveyor.

•The Formation/ Pathing Mechanics
-The units we produce or the units of the enemy should be able to move in a formation because i notice that in small areas the ground units are getting glitch in the walls athus blocking it. The pathinng mechanic for enemies is so boring i suggest a more better AI for them so that making defending more harder.

•The Joytick and Camera Control
-Put a joystick control for phone users so that we can avoid drowning in our ground mechs, and being able to lock or unlock your fixed camera on your character would be so helpfull.

• More Precise Minimap
-Have legends on the minimap and more detail would be helpfull.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
1. Already suggested many times, not happening
2. Already in V6
3. Already suggested and won't be added
4. Not sure exactly what you mean by this, but if it's icons on the minimap for specific blocks, I don't think it's necessary.
