### ISSUE TITLE
HUD Effects

### ISSUE THREAD

**Issue by Eldeston** [Anuken/Mindustry-Suggestions#5060]
### Describe the content or mechanics you are proposing.

For example, when the core is under attack, a HUD effect would show a pulsing red vignette indicating the core is indeed under attack or a special effect when the player heals and shows a pulse of green vignette or another effect that indicates about an incoming boss wave or an attack from an enemy OR a special under attack indicator such as being attacked by tar, slag, or cryo OR a special effect for weather such as the spore storm. The list goes on and on and on if you are creative enough.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

While it may be a little obtrusive (it could be disabled or enabled or adjusted for accessibility's sake), this can improve the player's response to certain situations especially in a live game where you can't pause. For example PVP maps where certain situation might require your immediate attention or in an area overcrowded with units.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
you gotta be joking, all those are already in the game bro

**Comment by Eldeston** [comment]
It's not in the game, what I mentioned is a colored vignette effect. That looks like this.
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/59617287/6d1a1932-ef43-473d-b748-fb3abb610b00)

**Comment by Eldeston** [comment]
There are times where the popup box when the core is under attack quite annoying to deal with when you are dealing with something else.

**Comment by Eldeston** [comment]
The idea I'm proposing is better ways to indicate certain events while being creative at it by using it in a multitude of effects through the HUD. A sky blue vignette when you are under attack by cryo waves, a bright orange vignette when you are under attack by slag, a slightly tarred screen that partially blocks your vision when under attack by tar.

My guy I said HUD, please read the description.

**Comment by jehosula** [comment]
is it really good to have these effects when you are mostly focusing on something else, this will be too obstructive for details that are already very easy to see
a red vignette for the core being under attack will be annoying af when the enemy pokes at the core, even more so than the message
the warning for the guardian and the guardian health bars are quite good and don't need any special effects
and the ones for effects are just annoying for no good reason, you can also just respawn, these belong in another game
all these warnings are already present is what i meant, just not in this fashion
also the weather could have a better effect but that would most likely be more annoying than good
(late respone cause i didn't check the notifications)

**Comment by jehosula** [comment]
> I doubt this could be too obstructive and I consider it a better than a pop-up message in the middle of the screen. If it's somehow more obstructive than a pop up message for let's say a small phone (unless you'd go further, like an android watch but I doubt people would even play here), reducing the vignette's length or transparency will improve accessibility. The weather effects option also had an accessibility option like this too which already exists. Among that, adding other creative ideas to the vignette (healing, cryo, slag, tar etc.) I think would be very good for the game.

what? the pop ups are never in the middle of the screen, except maybe the sector landing

**Comment by Eldeston** [comment]
The core under attack is also a popup.

**Comment by jehosula** [comment]
> The core under attack is also a popup, but now that you mentioned it that is also quite annoying. Even if there's a way to disable the popups, a better alternative would be better in terms of gameplay and accessibility such as the one I proposed in this post.

well at least it does not obstruct much
