### ISSUE TITLE
Allow turning off auto-save entirely in favour of manually saving

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry-Suggestions#5064]
### Describe the content or mechanics you are proposing.

The game currently auto-saves no matter what, with only the interval in the hands of the player. There should be an option to turn it off entirely.

It could be as simple as adding a 0 (zero) or "Off" value to the save interval slider. Or a toggle. Either is fine.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allowing the player to save manually has many possible benefits:

- The player can freely experiment with different setup options while in a sector, without worrying about the game being saved on an abortive attempt.
- They can later revisit past saves in order to replay sectors or even specific waves.
- Manual saves can be preserved and synced, e.g. via Syncthing, across devices, allowing the player to resume anywhere without worrying about conflicts.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
so you want to get all your progress lost

**Comment by Slotterleet** [comment]
- [x] I am not familiar with all the content already in the game and have not glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

https://github.com/Anuken/Mindustry-Suggestions/assets/62336673/ac5328d8-8a53-4a6e-a8d4-4a4ac0785845

(don't mind my game, it's heavily modded)

**Comment by mahdoosh1** [comment]
there is an auto-save option in the `load game` menu with the icon of a floppy disk as demonstrated in the video above. but for the campaign it is not possible. in the campaign when you are playing, other sectors continue playing as well. its like playing 50 maps in the same time, if you could turn off auto save, the game would  take 5 minutes just to save the sectors, but right now the game saves the game in a few minutes (which very little differences are made, so it saves faster)
