### ISSUE TITLE
add tags for mods

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5067]
### Describe the content or mechanics you are proposing.

make mod makers add tags to their mods to be able to fiter from or add some tags mods just select from

or have a system to be able to add tags to mods yourself and filter with those like what's already there for schematics

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will make it a lot easier to see mods of the type you want without having to scroll through many other mods before

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Haznobrain** [comment]
It would be nice to have more detailed tags for the mod loader, like for exemple if you want an erekir mod just put "erekir", if you want a mod that expands on vanilla just put "vanilla extension", etc.
i like this suggestion.
