### ISSUE TITLE
new unit type

### ISSUE THREAD

**Issue by liliam2007** [Anuken/Mindustry-Suggestions#507]
**Describe the content or mechanics you are proposing.**
maybe we could have tracked units which would be more tankier than most units in the same tier but more slower than most units in the same tier

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it can have a wide variety of units players could use and more tatics in pvp could happen using tracked units

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Already been suggested at least 2-3 times.
