### ISSUE TITLE
Less memory usage on launch?

### ISSUE THREAD

**Issue by GalaxiumNation** [Anuken/Mindustry-Suggestions#5070]
### Describe what you would like changed, and why.

Would it be possible to trim the memory usage down? I ask because since the game is supported on such old android versions (please don't remove compatibility with them 🥺) some devices have the potential to actually run it. But because the old devices have like 2-4gb of memory, they can't actually run the game and the game crashes when it tries to load 🥲

### Describe the changes you want to propose. Include possible alternatives.

optimize memory usage when launching so it uses at least 2GB instead of the 6-8gb it normally does

**Comment by buthed010203** [comment]
How many mods are you even running to get memory usage that high

**Comment by camelStyleUser** [comment]
how many mods are you using

**Comment by buthed010203** [comment]
I love asking the same thing twice

**Comment by camelStyleUser** [comment]
it runs on my android 4.4 with 1 gb of ram

**Comment by camelStyleUser** [comment]
and this phone only has 3 gb of ram so 2-4gb of ram isnt bad

**Comment by camelStyleUser** [comment]
and if you are talking about internal storage, mindustry with a few saves only takes up ~100mb

**Comment by GalaxiumNation** [comment]
Well... thats the thing.

I'm not using any...

**Comment by buthed010203** [comment]
You must have the wrong mindustry or something, it should *never* approach 8GB of memory usage

**Comment by camelStyleUser** [comment]
and might i ask where did you pull out the 8gb figure?

**Comment by GalaxiumNation** [comment]
I installed directly from the github page and installed it on a pretty _old_ tablet
Using the dev options in system settings I can view running apps and their memory usage

**Comment by buthed010203** [comment]
Android releases aren't even published in the main repo...

**Comment by camelStyleUser** [comment]
> I installed directly from the github page and installed it on a pretty _old_ tablet Using the dev options in system settings I can view running apps and their memory usage

its certainly not using 8gb of storage or ram
at most 1gb of ram and a few hundred megabytes of storage

**Comment by itcannotbe** [comment]
> Android releases aren't even published in the main repo...

There is only one thing I know off that official and has an apk on GitHub.

It's gotta BE.

**Comment by camelStyleUser** [comment]
> > Android releases aren't even published in the main repo...
> 
> There is only one thing I know off that official and has an apk on GitHub.
> 
> It's gotta BE.

and all the things i said so far are tested on BE

**Comment by SMOLKEYS** [comment]
> 6-8gb it normally does

Where did you get this information? This game runs perfectly fine on my old 4GB Galaxy S8 and current (also 4GB) Realme-C21Y. I can also pack some heavy mods in there, which increases the loading time, but otherwise, it still loads mostly fine.

**Comment by camelStyleUser** [comment]
> > 6-8gb it normally does
> 
> Where did you get this information? This game runs perfectly fine on my old 4GB Galaxy S8 and current (also 4GB) Realme-C21Y. I can also pack some heavy mods in there, which increases the loading time, but otherwise, it still loads mostly fine.

probably pulled it out of thin air

**Comment by GalaxiumNation** [comment]
nvm
I stupid
Dont listen to me :/
