### ISSUE TITLE
New solar panel

### ISSUE THREAD

**Issue by GreatSage777** [Anuken/Mindustry-Suggestions#5073]
### Describe the content or mechanics you are proposing.

I would like to add new solar panel that will be 6x6 in size and will produce max 1080 energy per second. To build this panel you have to use: 400 titanium, 250 silicon, 200thorium, 150metalglass ,150 surgealloy and 100 phase faber.
Hp: 300
Building time: 60 seconds
Special abillity: when placed give plus 5% speed to every solar panel on the map except this kind 
This buff can be upgraded up to 4 times and solar panels hav eto be placed to each others( i mean for this buff to work you have to place this panels together)
Pros: give a starting energy and buffs every solar panel by 20% if placed four times to each other
Cons: cant be placed more times than 4 on the map.
### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think when this panel will be added in the game there will be no more those stupid memes that solar panels are useles.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RzBuddy** [comment]
Imo the game should encourage players to make/feed more complex structures. Solar pannels should only be used as a last ditch effort to reboot a power grid instead of being a crutch
