### ISSUE TITLE
A "play" button in the editor "edit in game" mode

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry-Suggestions#5074]
### Describe the content or mechanics you are proposing.

A button, maybe on the top right of the screen, that enables all the machines etc so you can see what's working and what's not and the amount of power in the grid etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's kinda annoying to always have to go do playtest etc before having finished a map and adding that will allow for easier ennemy base/basic ally base construction for maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What's even the difference between a map file and a save file anyways?
It's not like it's the same thing, right?
### RIGHT?

**Comment by Haznobrain** [comment]
> What's even the difference between a map file and a save file anyways? It's not like it's the same thing, right?
> 
> ### RIGHT?

dafuq you mean

**Comment by Fabizocker456** [comment]
> > What's even the difference between a map file and a save file anyways? It's not like it's the same thing, right?
> > 
> > ### RIGHT?
> 
> dafuq you mean

You can e.g. move game saves into the map folder, and load and play them from where you saved last
