### ISSUE TITLE
Show negative production rates

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry-Suggestions#5076]
### Describe the content or mechanics you are proposing.

The stat screen in the planet map lets you know production rates for each resource. However, if your consumption exceeds production, the stat for that resource vanishes. I'm proposing showing a negative production rate in case the total consumption rate outpaces production.

Simple example: let's say you're minting thorium at a rate of 60/min in a sector. You set up a phase weaver which uses thorium at 120/min. The stat screen should then show thorium at -60/min.

Another scenario: you're producing thorium at 250/min and also exporting it from your core. A production rate of -50/min would let you know your core in that sector is slowly being emptied.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow the player to notice production inefficiencies at a glance, as well as gauge how much more of that resource needs to be produced in order to overcome the difference.

Currently, it requires either trial and error (setting up more and more production blocks until it eventually outpaces consumption), or calculating the rates of all producing and consuming blocks to come at a rough total.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
That wouldn't be helpful because the game doesn't update that statistic when the sector isn't loaded.

Because realisticly if you leave the game running consumption rates would eventually end up breaking even with production since storage is finite.

Plus the stated production rate is the an average rate of materials flowing into the core.
