### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by pcrody** [Anuken/Mindustry-Suggestions#5077]
### Describe what you would like changed, and why.

Can’t believe I paid for a game with no instructions and no tutorial
I want my money back

### Describe the changes you want to propose. Include possible alternatives.

PROVIDE INSTRUCTIONS

**Comment by jehosula** [comment]
# BRO PLAY THE CAMPAIGN
but yeah the game should provide more of a tutorial as newbies are unbelievably bad

**Comment by camelStyleUser** [comment]
cant believe you didnt check campaign

**Comment by camelStyleUser** [comment]
and you paying means nothing, you just donated to anuke.the game is free on every platform except ios

**Comment by SITUVNgcd** [comment]
First, this game is free on any platform, except iOS. You can get it free from itch.io and GitHub.
Second, PLAY THE CAMPAIGN!

**Comment by Lolnoizcool** [comment]
**PLAY THE GOD DAMN CAMPAIGN**

**Comment by Legomonster33** [comment]
"paid" bruh the game is free?????

**Comment by jehosula** [comment]
> "paid" bruh the game is free?????

only on steam and ios

**Comment by mahdoosh1** [comment]
you need a tutorial to download games from their official site.
