### ISSUE TITLE
Buffing some novas type units

### ISSUE THREAD

**Issue by GreatSage777** [Anuken/Mindustry-Suggestions#5082]
### Describe what you would like changed, and why.

I would like to buff some of the novas type units stats.

### Describe the changes you want to propose. Include possible alternatives.

Corvus:
Movement speed: 2.25 -> 3.0
Damage: 560 -> 880
Attack speed: 0.17 -> 0.08
Vela:
Mining speed: 0% -> 600%
Can mine: copper, lead, coal, titan, sand, scrap.
Quasar:
Health: 640 -> 720
Damage: 45 -> 50
Pulsar:
Attack speed: 2.5 -> 3.0
Damage: 14 -> 18
Health: 320 -> 380
Movement speed 5.2 -> 4.9
Attack radius: 7 -> 9
Nova:
Mining speed: 0% -> 40%
Can mine only copper and lead

**Comment by jehosula** [comment]
the most reasonable set is the nova one, and that says a lot about how bad the other ones are, the whole line would be insanely overpowered with this, except the nova, which will just be very good cause it was always good

**Comment by Slotterleet** [comment]
Don't even get me started on Corvus. Its abnormally high range already makes up for it. NO NEED to make it even more overpowered.

**Comment by guncatt** [comment]
petition to give corvus its mining ability back except actually good this time.
