### ISSUE TITLE
Sand mining on Erekir

### ISSUE THREAD

**Issue by fghjk455rg** [Anuken/Mindustry-Suggestions#5083]
### Describe what you would like changed, and why.

By the end of the game, cliff crusher is extremely inefficient and occupies a huge area.
Maybe add the ability to accelerate the extraction rate by 3 times by adding cyanide?
(of course, so that the player does not find out about cyanide early, make the line "accelerator" hidden)

### Describe the changes you want to propose. Include possible alternatives.

**Cliff crusher** can be accelerated three times (energy consumption is also _tripled_) using _1/s_ **cyanide**.

**Comment by OnyxFinger** [comment]
I'd prefer nitro..

Without getting into the specifics though, sand mining on erekir is extremely tedious indeed. Walls are rarely uniform and a lot of crushers are needed (even with 200% walls) for any kinda of design with more than one phase factory in it.

**Comment by jehosula** [comment]
there is also the silicon arc furnace route of just making the block good enough for the whole game by having insane base stats, silicon arc furnace is like 4 times as strong as it needs to be early on, it's also very efficient at 4 sand + 1 graphite = 4 silicon

**Comment by 1stMISHA** [comment]
this is a great idea In the form of adding a boost for sand extraction because in large industries it may not be enough

**Comment by fghjk455rg** [comment]
By the way, this includes the use of cyanide

**Comment by fghjk455rg** [comment]
More applications are good
