### ISSUE TITLE
Campaingn on dedicated server

### ISSUE THREAD

**Issue by lucyamonster** [Anuken/Mindustry-Suggestions#5088]
### Describe the content or mechanics you are proposing.

The ability to run the campaigns on a dedicated server.
I know this is a duplicate but it hasn't been implemented and the old ones stalled out.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Being able to run the campaign on a server

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SITUVNgcd** [comment]
Lol! I just think about it yesterday: A Plugin that can play campaign on dedicated server.
Im thinking about how to implement sector selection and tech tree using popupMenus. I can do that, but take time.

**Comment by lucyamonster** [comment]
> Lol! I just think about it yesterday: A Plugin that can play campaign on dedicated server. Im thinking about how to implement sector selection and tech tree using popupMenus. I can do that, but take time.

If I can help somehow I would be happy to try
