### ISSUE TITLE
add a game rule that let's you allow or ban upgrading cores without core zone tiles

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5089]
### Describe the content or mechanics you are proposing.

a game rule that makes core zone tiles necessary to upgrade a core like how erekir cores already work, but you can change it

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will allows for serpulo maps to limit how much you can upgrade particular cores
and for erekir maps to remove said restriction

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DEpObORnik** [comment]
a very good idea, should be added

**Comment by OnyxFinger** [comment]
Interesting for forgetful mapper ig

there is nothing I'm against here

**Comment by jehosula** [comment]
> Interesting for forgetful mapper ig

hmm
