### ISSUE TITLE
Block that plays sounds

### ISSUE THREAD

**Issue by Andrey-071** [Anuken/Mindustry-Suggestions#5090]
### Describe the content or mechanics you are proposing.

Add a 1x1 block that can reproduce sound at one frequency and, optionally, with a choice of waveforms (square, triangle, saw, sine). Energy consumption can be added. The block must work in tandem with a processor (using the processor to set the frequency and, if desired, the signal shape).
The block can be used as a warning of danger, that resources are running out, or simply to play some music.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This block can be used as a sound warning of danger, that resources are running out, or vice versa - the maximum quantity, and so on.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jamespire1** [comment]
I'm pretty sure logic sound is already in the trello
