### ISSUE TITLE
Max Shield 

### ISSUE THREAD

**Issue by Jamespire1** [Anuken/Mindustry-Suggestions#5091]
### Describe the content or mechanics you are proposing.

Option to set a max shield for a unit in the wave editor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Sometimes the shield can start to stack up too much and make the map unbalanced

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
well there is an option to make the original spawn end at a wave and a new one takes its place and starts with the same amount of shield and enemies spawned but the shield does not increase, but yeah it's better to make it with just one spawn instead of 2
