### ISSUE TITLE
CO-OP tech tree

### ISSUE THREAD

**Issue by cmd430** [Anuken/Mindustry-Suggestions#5094]
### Describe what you would like changed, and why.

When playing co-op only the host is able to see the tech tree, I would like to be able to view the tree as a client this would help learning the tech tree and would also allow clients to read the short info texts about the unlocks in once place to know what things can do quickly

### Describe the changes you want to propose. Include possible alternatives.

When playing co-op only the host is able to see the tech tree, i would like to have the tree visible to clients in a view only mode (host would still be in control of unlock progression 

possible alternatives: keep as is

**Comment by camelStyleUser** [comment]
ok code it

**Comment by TagGamer555** [comment]
> ok code it

ok code it
