### ISSUE TITLE
Auto Launch

### ISSUE THREAD

**Issue by GolfingCentaur** [Anuken/Mindustry-Suggestions#5098]
### Describe the content or mechanics you are proposing.

Hello,

I have a request.

After a failed attempt to capture the new sector, the game automatically chooses which sector to launch from. Right now, this seems to be determined by whichever conquered sector is closest to the sector the player needs to launch to. Sometimes, this is fine, but other times, it isn’t even possible due to a resource mismatch. 

##### resources available= 

> **Thorium**, Beryllium, Graphite, Arkycite, Tungsten 

##### Required resources: 

> Graphite, Thorium, Silicon, Beryllium, Tungsten, Oxide

##### Available Resources:

> Graphite, Beryllium, Tungsten, Slag, **[_note_: Thorium unavailable]**

The only way to launch to _Split_ from _Crevice_ is to launch _**to**_ _Stronghold_, return to planet screen, then launch to _Split_ from _Stronghold_.

It would be wonderful if the game used available resources when auto-selecting launch points.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be wonderful if the game used available resources when auto-selecting launch points.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by GolfingCentaur** [comment]
I forgot to tack this on

OS: Android 11
Game version: 146

**Comment by mahdoosh1** [comment]
you are simply asking for a way to lunch from two sectors where each of them may have different resources.

**Comment by Kenny-Ofc** [comment]
> you are simply asking for a way to lunch from two sectors where each of them may have different resources.

that is how people just asking a suggestion and not thinking how it is possible

**Comment by GolfingCentaur** [comment]
> you are simply asking for a way to lunch[_sic_] from two sectors where each of them may have different resources.

Nope, I just don't want to keep opening and closing the Stronghold map just so I can reaccess the _Split_ map. It might be possible that this is an Android exclusive problem, and the desktop versions select relevant launch points.
