### ISSUE TITLE
Изменить название Знамения/её подключения

### ISSUE THREAD

**Issue by GamerUKgithub** [Anuken/Mindustry-Suggestions#5099]
### Describe what you would like changed, and why.

Когда к процессору подключено знамение, ей выдаётся подключение foreshadow. но ведь foreshadow означает предсказывать, а не знамение.

### Describe the changes you want to propose. Include possible alternatives.

Изменить название Знамения на Предсказатель либо ее подключение на... честно, я не знаю как переводится знамение на английский.

**Comment by camelStyleUser** [comment]
сорс код проверь, называется "foreshadow"

**Comment by Krita-Burstflakes** [comment]
Зачем менять название изза 1 человека?

**Comment by Yep-Nope1** [comment]
Чел это тебе в перевод, там канал в дс есть, который по поводу перевода, предложи там, но думаю никто не будет менять

**Comment by Leyn-pl** [comment]
Чел оно так в оригинале называется
