### ISSUE TITLE
JS documentation for third-party developers

### ISSUE THREAD

**Issue by Vyber90** [Anuken/Mindustry-Suggestions#51]
I have been playing Mindustry since the classic version was launched for Android, and it was a few days ago when I wanted to program a mod to have new items and blocks for a currency system, and actually, although I like how the modding guide teaches me how to write JSON for my mods, I am currently struggling and carefully reading the game's code in order to understand how code is written in the game and how scripting in mods and Mindustry server works (nope, ExampleMod does not help me as I would expected it to).

So, I think developing a full-featured documentation on how JS scripts are interpreted by the game (let's not forget about  mindustry server live scripting), such as how items are coded into a conveyor, how a block knows whether it is connected to electricity... would help all us developers that would love to share lots of ideas with the community and friends in order to make the game deeper and larger.

Who knows, some people could work side by side in order to program the logic system for the game if they had this documentation...

**Comment by Anuken** [comment]
Documentation is planned for 6.0.
