### ISSUE TITLE
Add a efficiency booster option to the Burstdrill script

### ISSUE THREAD

**Issue by TehLeno** [Anuken/Mindustry-Suggestions#5100]
### Describe what you would like changed, and why.

I would like that there is a option to give Burstdrill based drills (impact, eruption drill) a optional efficiency booster like Serpulo drills and plasma bores.

Reason why is because this allows modders to give their own burstdrills a optional booster and this feature can even be used for future Mindustry content.

### Describe the changes you want to propose. Include possible alternatives.

The ability to give Burstdrills a boosting item/fluid and a custom efficiency multiplier for said item/fluid.

**Comment by SITUVNgcd** [comment]
Yep! PR created, but not merged.
https://github.com/Anuken/Mindustry/pull/9517
