### ISSUE TITLE
Ericer's turret:lightning

### ISSUE THREAD

**Issue by 1stMISHA** [Anuken/Mindustry-Suggestions#5105]
### Describe the content or mechanics you are proposing.

The turret will require 500 units of energy for a powerful chain lightning shot, hitting up to 5 targets and dealing 200 units of damage. cost:1000 silicon, 500 beryllium, 200 tungsten, 100 kinetic alloy. for a shot, it requires:500 units of energy and 20 heating units (maximum power).it will give an effect (charged).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will help you deal with crowds of enemies for balance.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
it's gonna compete with the afflict turret a lot, similar building resources, consumption and role

**Comment by DX-36** [comment]
afflict 2

**Comment by Krita-Burstflakes** [comment]
Ericer not erekir
