### ISSUE TITLE
steam

### ISSUE THREAD

**Issue by 1stMISHA** [Anuken/Mindustry-Suggestions#5106]
### Describe the content or mechanics you are proposing.

This is not a game room.steam can be obtained in a new unit that will require slag and water and additionally provide heating or pour water and slag into a liquid tank or tank. The steam will be an amplifier for the gas condenser and also in a new unit that will produce water from steam and cyanide for cooling, the unit will produce 20 water per second.The steam will be transmitted through the water supply

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

steam will be an enhancement for some blocks and may in the future be a resource for creating a new resource

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Krita-Burstflakes** [comment]
Crossplatform deathhh
