### ISSUE TITLE
bridge freights conveyors  

### ISSUE THREAD

**Issue by 1stMISHA** [Anuken/Mindustry-Suggestions#5107]
### Describe the content or mechanics you are proposing.

bridge conveyors will help to carry loads over short distances without using for this purpose THESE ARE NOT BRIDGE CONTAINERS FOR RESOURCES, THEY ARE FOR BLOCKS, UNITS AND 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Bridge cargo conveyors will be able to transport goods through buildings over short distances, which will help on tight maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
What are you even asking for? Can you like make a mock up of it in-game?

Last time I check bridge conveyors exist in the game.

**Comment by jehosula** [comment]
this guy is not even trying to hide the trolling anymore, describing the already existing bridge conveyors

**Comment by 1stMISHA** [comment]
These bridges are NOT FOR RESOURCES, they are for cargo, blocks, units, etc.

**Comment by mahdoosh1** [comment]
> These bridges are NOT FOR RESOURCES, they are for cargo, blocks, units, etc.

it' s unclear what you are referring to as "These"

**Comment by jehosula** [comment]
> These are not overhead conveyors, these are overhead conveyors for goods (units, blocks, containers and boxes)

well it's interesting, but the question really is why?
you wouldn't even use payload conveyors much, let alone have them restricted by other stuff, i just don't see why it would be useful, it would probably be worse for the game cause it would allow for some dumb transportation at times

**Comment by itcannotbe** [comment]
> > These are not overhead conveyors, these are overhead conveyors for goods (units, blocks, containers and boxes)
> 
> well it's interesting, but the question really is why? you wouldn't even use payload conveyors much, let alone have them restricted by other stuff, i just don't see why it would be useful, it would probably be worse for the game cause it would allow for some dumb transportation at times

For Serpulo, the only thing that go on payload conveyors are units and it less efficient to move them on payload conveyors are most units are faster than payload conveyors.

For Erekir, Payload Mass Drivers exist plus proper blocks exist to load unload payloads onto the conveyor/blocks on the conyeror.
