### ISSUE TITLE
Day counter

### ISSUE THREAD

**Issue by Foxcraft29260** [Anuken/Mindustry-Suggestions#5108]
### Describe the content or mechanics you are proposing.

An extension to the HUD which will tell us how many days (in-game) we have spent on the planet where we are (regardless of the sector) 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This information could allow for more in-depth immersion for RP or “number of days” type content and would also allow us to have an order of magnitude (in game) of the time spent on each planets. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
bro wants surviving 100 days in mindustry

**Comment by Mythril382** [comment]
"Can I survive 100 days on Serpulo?" ahh suggestion

**Comment by camelStyleUser** [comment]
count the days by hand like god intended(mindustry templeos port when)

**Comment by Leyn-pl** [comment]
I think you can already make it with logic. Use solar panel, detect when power output will start to rise and add 1 to the day counter. Then it will slowly get to the top, then lower again and start to rise again, detecting sunrise.
Can you survive 100 days in desolate rift without starting loadout???
