### ISSUE TITLE
Buffing atrax and spiroct

### ISSUE THREAD

**Issue by Charlotte1527** [Anuken/Mindustry-Suggestions#5109]
### Describe what you would like changed, and why.

Every unit has it's own strength and weakness
To Atrax,it only target ground unit so Atraxs are easily killed by flares.That's its weakness and it's reasonable.
To Spiroct its range is very short it's reasonable,too.
However when it comes to their strengths,it sucks.
Though like Arkyid and Toxopid,they can step over most terrain.
Atrax and Spiroct should be flexible enough to cause damage to their enemy,but the truth is,they move too slow to do any damage enemy's base before they are detected and killed.
Another example,Arkyid can easily catch Scepter,while Spiroct will dead before it catch Fortress.(All T3 units play a role in pvp except Spiroct)
Instead of reducing their weakness,their strength "flexibility" should be strong enough.

### Describe the changes you want to propose. Include possible alternatives.

Atrax:
movement speed: 4.5-->5.4
Spiroct:
movement speed: 4.05-->5.0

**Comment by jehosula** [comment]
atrax is pretty good for a tier 2, it does not need a buff any more than other t2s
spiroct does need a buff for sure tho

**Comment by Charlotte1527** [comment]
> atrax is pretty good for a tier 2, it does not need a buff any more than other t2s spiroct does need a buff for sure tho

As a crawler set unit(attack tended),Atrax move slower than pulsar(even without boost),and when attacking do less damage than pulsar(an assist tended unit),that make no sense

**Comment by jehosula** [comment]
> As a crawler set unit(attack tended),Atrax move slower than pulsar(even without boost),and when attacking do less damage than pulsar(an assist tended unit),that make no sense

but they go over walls without flying and they burn stuff easily also a good bit cheaper also they have almost double the hp and comparable damage also they inflict the very deadly (especially at this tier) melting status

**Comment by alphy228** [comment]
atrax is a very scary t2 unit,not in pvp but in (especially campaign)survival 
spiroct needs a buff

**Comment by guncatt** [comment]
I'd say all atrax needs is another range buff to let it have the same range as dagger and nova.

Both ground tier 2s are locked to melee.

It may need a small firerate or damage decrease if that is done though.


For spiroct I think it stealing life faster and dealing more damage at close range along with a small speed buff would be enough.

**Comment by jehosula** [comment]
> I'd say all atrax needs is another range buff to let it have the same range as dagger and nova.
> 
> Both ground tier 2s are locked to melee.
> 
> It may need a small firerate or damage decrease if that is done though.
> 
> For spiroct I think it stealing life faster and dealing more damage at close range along with a small speed buff would be enough.

nah, atrax's range is already kinda cursed
