### ISSUE TITLE
more erekir built-in maps

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5113]
### Describe the content or mechanics you are proposing.

add more built in maps for erekir
some different survival ones, maybe ones with islands and stuff, might even make base builder ai for erekir for an attack/pvp map

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

would just be nice to have more than one built in erekir map that kinda sucks when serpulo has several built in maps tha thave some variety

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Jamespire1** [comment]
I've talked to epowerj about this and he said he'd bring it up to anuke. This means there is a decent chance of this happening

**Comment by mahdoosh1** [comment]
> I've talked to epowerj about this and he said he'd bring it up to anuke. This means there is a decent chance of this happening

this might be a duplicate, and have you checked Trello? i think it is planned

**Comment by Jamespire1** [comment]
I am unaware of that then. I had better check trello again
