### ISSUE TITLE
Allows blueprint placement using logic controls

### ISSUE THREAD

**Issue by zhraa11** [Anuken/Mindustry-Suggestions#5114]
### Describe the content or mechanics you are proposing.

I want to use logic blocks to control unit placement blueprints like recursive blueprints in factorio.I also want the blueprint to contain information from the memory unit, but that's not very important

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will greatly expand the application of game logic blocks and make automation easier.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
whar

**Comment by camelStyleUser** [comment]
unit building is real

**Comment by camelStyleUser** [comment]
you can make new copies of yourself(the processor) actually

**Comment by zhraa11** [comment]
But it will be more convenient when I use units directly to place blueprints, and can achieve more complex functions.
