### ISSUE TITLE
Adjustable max line limit property for processors

### ISSUE THREAD

**Issue by Arcticzomb** [Anuken/Mindustry-Suggestions#5116]
### Describe the content or mechanics you are proposing.

Make the maximum line limit in logic processors a moddable property.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will allow for much more complex programming when porting code from an external source. Personally, I re-wrote another person's script that no longer works to converts images to 176x176 and outputs pixel data as mindustry code. ((176^2)*2 lines of code, aka, ~60,000 lines of code or 60 processors to run it (The max line limit is 999 lines)).

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by mahdoosh1** [comment]
just needs a method to set that property (or just make the variable public directly)
