### ISSUE TITLE
impact 0078 ends later than it should

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5117]
### Describe what you would like changed, and why.

make impact 0078 end on wave 40 instead of wave 45
currently the guardian spawns on wave 40 but the sector is captured on wave 45, leading to 5 waves worth of wasted time without any threats in the end, so making it end earlier will just save some time

### Describe the changes you want to propose. Include possible alternatives.

make impact 0078 end 5 waves earlier

alternatively make the guardian spawn on wave 45 instead to make the 5 waves mean something

**Comment by mahdoosh1** [comment]
don't lose motivation, playing 5 waves isnt hard

**Comment by mahdoosh1** [comment]
> don't lose motivation, playing 5 waves isnt hard

i meant this is **probably** intentional

**Comment by runiArnsbjornson** [comment]
I think it should go up to wave 78 to be honest, with a stronger guardian or several

**Comment by jehosula** [comment]
> I think it should go up to wave 78 to be honest, with a stronger guardian or several

the longest survival sector is 65 waves and that's an eradication threat numbered sector
a high threat is clearly not suited for sending enough enemies for 78 waves, even NPC with a t5 still ends on wave 50 and that's quite long for the campaign being the longest named sector, 78 waves in insane
