### ISSUE TITLE
Manage planetary Launch terminal throu planet map

### ISSUE THREAD

**Issue by Mallo321123** [Anuken/Mindustry-Suggestions#5118]
### Describe the content or mechanics you are proposing.

I think It would be cool, if you could manage all Planetary Launch terminals at once from the Planet map

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make it less a hasle, to change the destination sectors of the launch terminals. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Matita008** [comment]
>Planetary Launch terminals 

You mean the launchpad?

**Comment by Mallo321123** [comment]
Yes, exactly
