### ISSUE TITLE
V 105[Alpha]

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#512]
Player damage is too low 
Tier 1 unit takes too long to build
Naval units too fast
Pls set a tutorial for the new things that were added
Bring back rev 
Thanx 
-unjown pjnas(Mindustry)
S**me (discord)

**Comment by itcannotbe** [comment]
What happened to the template?

**Comment by Anuken** [comment]
1. It should be. Don't attack with it.
2. Be more specific.
3. Considering it's the one place they can move, I think it's fine.
4. Wait until release.
5. Zenith.

**Comment by rmperkow** [comment]
I think 2 means the air/ground/naval factories take longer to build units than the Additive reconstructor
