### ISSUE TITLE
new endgame belt type

### ISSUE THREAD

**Issue by idk2233** [Anuken/Mindustry-Suggestions#5120]
### Describe the content or mechanics you are proposing.

A super high capacity belt for late game seruplo that would act as an upgrade to the plastantium belt. To make it new and more interesting it would have super high throughput but slow speed (like bunches of 100 items that move .8 tiles per second to have 2x the throughput). would be balanced by making it very expensive (maybe 5 surge and 10 silicon per tile) to lock it to high end applications so it doesnt just get spammed everywhere like plastianium belts making them obcelete. Also the slow speed would balance the massive throughput making it take a while to start working.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A super high throughput belt would be usefull for large factories that can need hundreds of items per second and dont care about speed. I find when trying to make massive factories i have to spam plastanium belts and phaze bridges around my existing inputs to supply enough items and it becomes a mess.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
interesting idea but why not just buff the current plastanium belt, it literally gets beaten by a copper tech setup (bridge weaving) and it's a plast tier transport for the endgame

could be increased to 50/s throughput

**Comment by idk2233** [comment]
+10 items/s wouldnt do much and the buff it would take to cover the usecase i described would be very high and thats why i suggested a new belt like the copper/titanium tiers but higher end

**Comment by jehosula** [comment]
> +10 items/s wouldnt do much and the buff it would take to cover the usecase i described would be very high and thats why i suggested a new belt like the copper/titanium tiers but higher end

plastanium belt is already endgame eniugh imo, even 50 i/s is kind pushing it for a conveyor, there is ODDing said plast conveyors and it would result in 125 i/s instead of 100 i/s and surely THAT is engame enough for you

**Comment by Kenny-Ofc** [comment]
people asking suggestion > not havin fun with the existing content. play mods instead. plastanium are already great.

**Comment by idk2233** [comment]
mods dont have that tho and are usually massively overtuned to make everything trivial. I like the vannila game balance and was just wanting something that could handle massive throughput. For example plastanium is good but lets say for surge a full plast belt of lead doesnt even fill a titanium belt worth of surge alloy. Also ODD will buff the factories aswell so the relative capacity is still the same.

**Comment by jehosula** [comment]
> mods dont have that tho and are usually massively overtuned to make everything trivial. I like the vannila game balance and was just wanting something that could handle massive throughput. For example plastanium is good but lets say for surge a full plast belt of lead doesnt even fill a titanium belt worth of surge alloy. Also ODD will buff the factories aswell so the relative capacity is still the same.

the only situation where plast belt is actually lacking is when you ODD the factories and not the belt, i mentioned ODDing the belt cause the issue is with ODDing the factories but not the belt, 40 i/s is enough to supply large factories if you actually place multiple belts, cause one belt should not be able to supply whatever massive contraption that would need multiple plast belts for a single item

this suggestion would add a 200 i/s belt when ODDed, that's way more than anything should ever need, that's twice as much as an ITEM SOURCE my guy, nothing should even need ONE item source, let alone TWO

also a titanium belt of surge is a lot my guy and plast belts are easily able to make two with the production, people would only ever use, (not need) this belt for massive export bases or gigantic maps that have enough to support hundreds of items per second
