### ISSUE TITLE
balanced reactors/generators

### ISSUE THREAD

**Issue by yaxhochupizzu** [Anuken/Mindustry-Suggestions#5123]
### Describe what you would like changed, and why.

buff/nerf some reactors or generators, bc some get used much more than others 

### Describe the changes you want to propose. Include possible alternatives.

**impact**
power output 7800>>7500(6300>>6000) (-)
cryo 15/s>>18/s (-)
production time 2.33>>2.67 (+)
         **rtg**
production time 14s>>11s (-)
        **differential**
cryo 6/s>>3/s (+)
production time 3.66s >> 5.25s (+)
power output 1080>>1000 (-)
         **steam**
coal power output 330>>300 (-)
spore power output 115%>>105%(-)

**Comment by SomeonesShade** [comment]
For a ratio break suggestion, you have to use good reasoning on why a specific change is used.
Otherwise very low benefit for schematic rebuilding

also an RTG nerf? Really?

**Comment by yaxhochupizzu** [comment]
> whoa these are actually decent tho the rtg nerf is nerfing the worst stat, rtg does not need a nerf anyway diffgen buffs seem over board tho steam gen nerfs are very reasonable however

still nobody will use diffs but will mass spam rtg, thats why i would nerf them.
main differential generator problem is that in mid game nobody wants to make cryo for them, and just spam steam gens, and in late game there are better options, like impacts thor and rtgs

**Comment by yaxhochupizzu** [comment]
> For a ratio break suggestion, you have to use good reasoning on why a specific change is used. Otherwise very low benefit for schematic rebuilding
> 
> also an RTG nerf? Really?

rtg are just boring, from 1 4×4 drill without any boosts you can place 28 of them, making ~ 7.3k energy. 
and game isnt about schematics, and for me this isnt a problem to bulid smth myself.

**Comment by jehosula** [comment]
> still nobody will use diffs but will mass spam rtg, thats why i would nerf them. main differential generator problem is that in mid game nobody wants to make cryo for them, and just spam steam gens, and in late game there are better options, like impacts thor and rtgs

dude, literally no one is using rtgs besides core unloading for the campaign, and some people already use diffgen in pvp

> rtg are just boring, from 1 4×4 drill without any boosts you can place 28 of them, making ~ 7.3k energy.
and game isnt about schematics, and for me this isnt a problem to bulid smth myself.

rtg isn't op, and the ratio break does not have any good reasoning

**Comment by JasonP01** [comment]
Rtg nerf is valid, its specifically a campaign based nerf that i can agree upon. Being able to make 10k power off a single maxed airburst with rtg is crazy 

It also has the longest non-unit production time in the game, a nerf of 3 seconds is a pretty good nerf

**Comment by yaxhochupizzu** [comment]
> > still nobody will use diffs but will mass spam rtg, thats why i would nerf them. main differential generator problem is that in mid game nobody wants to make cryo for them, and just spam steam gens, and in late game there are better options, like impacts thor and rtgs
> 
> dude, literally no one is using rtgs besides core unloading for the campaign, and some people already use diffgen in pvp, people will use it with the buff, in fact it would likely be op with this big of a buff
> 
> > rtg are just boring, from 1 4×4 drill without any boosts you can place 28 of them, making ~ 7.3k energy.
> > and game isnt about schematics, and for me this isnt a problem to bulid smth myself.
> 
> rtg isn't op, and the ratio break does not have any good reasoning

i may agree that ratio break for impacts is not worth it, so its better to only keep an energy output nerf
for diffgens i would still change ratios
but rtg concept is just too good. 14s production time, 2x2 size, single resource input and a decent energy output.
maybe i would also buff pyratite efficiency in steams

**Comment by SomeonesShade** [comment]
> Rtg nerf is valid, its specifically a campaign based nerf that i can agree upon. Being able to make 10k power off a single maxed airburst with rtg is crazy 
> 
> 
> 
> It also has the longest non-unit production time in the game, a nerf of 3 seconds is a pretty good nerf

You do realize rtg has a lower item effeciency than thorium reactor? (3.78k rtg vs 5.4k thor reac [power unit * production time])
At best conditions on a 6.48 i/s ab, you can make 24.4k power on rtg, vs 34.9k power with thor reactor

Item effeciency being too good is not an argument... especially if one is more expensive with its lategame resources vs one completely composed of midgame

**Comment by jehosula** [comment]
> Rtg nerf is valid, its specifically a campaign based nerf that i can agree upon. Being able to make 10k power off a single maxed airburst with rtg is crazy
> 
> It also has the longest non-unit production time in the game, a nerf of 3 seconds is a pretty good nerf

the reason people use rtg in the campaign is that it generates a good amount of power and can easily unload from the core, no other power source has both cause they either take too much space to properly use and require liquids, or just trash
