### ISSUE TITLE
Individual Campaign Reset

### ISSUE THREAD

**Issue by Chax0180** [Anuken/Mindustry-Suggestions#5124]
### Describe the content or mechanics you are proposing.

When clicking on the "Clear Campaign Saves" button in the Game Data settings it would be great to have buttons for each planet allowing for restarting one individual planet, so one can continue with one or more other planets, if there were to be modded compatibility.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It's mainly convenient, I messed up a lot of stuff on my Erekir playthrough and have been thinking about it a lot, and abandoning ever sector doesn't work since you keep your research.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
YES
