### ISSUE TITLE
New environnement/planet and ideas linked

### ISSUE THREAD

**Issue by runiArnsbjornson** [Anuken/Mindustry-Suggestions#5125]
### Describe the content or mechanics you are proposing.

I somehow always come back to this game, and would very much love to see MORE of it. 

I dreamt of a new planet, mostly water based, where you would have to start from existing tech, and develop new ways to get ressources and manage space. While some ressources would require shallow waters some can only be found in the deepest part, some ressource could be only available on land, on the small volcanic islands for exemple.

Most of the planet and zones would be water and deep water, so most current buildings blocks and units would be useless.

To circonvent that you would have to construct, heavy ships or "boats", which come in different tiers, those boats would have several fold uses, and be blocks more than unit but could move around (still not sure if you automate the move or not, and how) :
- they would mine nearby shallow and deep water ressources (the first tier would have to move close, and use their own laser like mono ; whereas the higher tier would have special personnal drones, with last tier able to have both drones and mono-laser, or drone to send away the ressources ?)
- some boats would be used to move ressource to plateforms (more on that later), or islands where factories or usines could produce higher tiered ressources or units
- I envisionned high tier boats able to have some space on them where you could directly have some factories or turret or vault, then the boat would be moving around to re-stock the ressources needed for those factories.
- they could also have moderate defenses, or space allocated only for defense (the idea is to have those block vulnerable, moving, but not exactly free target), they would be huge (like the size of Omura or Navanax for the smallest tier, and growing to 2 time this size for the highest tier, with enough space for 6x6 blocks on top of them)

i spoke about plateforms which would be like depot hub, like container, and vault, except those plateform could be captured and their ressource with them (this could be some kind of flag defense gameplay, or majority, domination like micro game)

On this planet most of AA defense would be very powerful, meaning most of the aerial units would be sneaky stealers, or distrubers, with some stealth mecanics. Which would make multiplayer map on this ENV all the more fun, allowing creatives ways to win.

Lastly campaign wise, I was thinking about having neo-plasm as an enemy for this planet, in place of an opposing faction. Neo-plasm and water means, every map, every zone should be very time sensitive, you could see some neo-plasm units but also the big neo-plasm puddle creeping slowly on the map, because deep water means it takes time to transform entirely. I somehow imagined neo-plasm "core" to be organic looking, even beating like a gigantic creepy-ass heart, and with every pulsation the creeping progress, so if you take too much times some part of the map would innaccessible until fought hard to push back or clear or cleanse the neoplasm. 

I thought of laser based short range neo-plasm burning turret, which would be useless against neo-plasm (flying ?) units but allow to slow down the progress of the creeping death, also, developping cure like missile sent by scatters, created with a special plankton or bio ressource (fish ? bio mass ?). You also thought it could be cool to have ressources move around (fish do move around) and deplete, then reappear later on somewhere else or just slowly growing back. Even coral could be used ? (and why not include some ressource sensitive about not wasting, like now it's no malus to OVER mine, here, it could be letal to not have ressource because you burnt it)

I know there are a lot of things that needs works. But I really tried to learn code just to mod and improve mindustry but i was an utter failure on my part :'(

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this would add a whole new way of playing, probably new ressources (plancton & bio mass !, new ores, some new fluid and/or gas), and make a new planet very different gameplay wise than Erekir and Serpulo, with a focus made on moving fast, and confronting a menace which is overwhelming, while allowing may be to discover new things about the lore, (where does those faction emerged ? what exactly is the neo-plasm ? were the factions corrupted by it ? and so on...)

the very different gameplay would need some fun and new way of thinking/building, organizing. With very few conveyor and conduit, because space would be the most valued ressource, with the idea of factories built in on ships and/or factories with specific input/output direction/ressource. 

Sorry for my long post, hope some would love the ideas, improve it, or at the very least use it to create awesome mods. 

If Anuke find those ideas interesting, just contact me, i would love to speak more about everything i could not put well into words (even moreso because english is not my native langage)

Lastly i love this game <3 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
man wants neoplasm tantros 😨

**Comment by camelStyleUser** [comment]
(it aint happening though)

**Comment by Novanox4** [comment]
The developer said that another planet won't be happening since adding erekir took so much time and resources (especially a water planet since they said they won't be reviving tantros)
