### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by Zzzennzzz** [Anuken/Mindustry-Suggestions#5126]
### Describe the content or mechanics you are proposing.

This mechanic will allow players to create accounts to save data instead of importing it to the cloud data

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will improve convenience of saving progress as having accounts will be easier than importing the data to the cloud

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
oh god cloud sync suggestion number 2737842326236564235

**Comment by camelStyleUser** [comment]
(consider reading README.md)

**Comment by Zzzennzzz** [comment]
Lol my bad just wanted to ask sorry for the inconvenience
