### ISSUE TITLE
World processors spawning in PVP

### ISSUE THREAD

**Issue by alphy228** [Anuken/Mindustry-Suggestions#5127]
### Describe what you would like changed, and why.

World processors cannot spawn units for teams without cores if gamemode is PVP

### Describe the changes you want to propose. Include possible alternatives.

allow world logic to spawn units for teams without cores in PVP gamemode as an option in map settings

**Comment by camelStyleUser** [comment]
they cant in any gamemode tbh

**Comment by jehosula** [comment]
it's because of the unit cap being zero, you need a core or having a base unit cap to let them

**Comment by alphy228** [comment]
> they cant in any gamemode tbh
They can if the team youre spawning units for is "enemy team",on PVP that doesnt work

**Comment by camelStyleUser** [comment]
> > they cant in any gamemode tbh
> > They can if the team youre spawning units for is "enemy team",on PVP that doesnt work

JUST GET A BASE UNIT CAP BRO
