### ISSUE TITLE
world button

### ISSUE THREAD

**Issue by xryazik** [Anuken/Mindustry-Suggestions#5128]
### Describe the content or mechanics you are proposing.

world button

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this will be useful on the sandboxes. i apologise for not saying much, i just don't know what else to add.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
what even are you suggesting?

**Comment by SITUVNgcd** [comment]
> this will be useful on the sandboxes
To do WHAT?

**Comment by JasonP01** [comment]
Already exists
