### ISSUE TITLE
Sector Influence Based Vulnerablility

### ISSUE THREAD

**Issue by Eldeston** [Anuken/Mindustry-Suggestions#5129]
### Describe the content or mechanics you are proposing.

Adjacent or nearby sectors create a influence level. The influence level spreads to adjacent sectors in a radius. This radius increases as the level of influence increases. If the influence radius reaches into an enemy sector, the conquered sector nearest to the influenced enemy sector will be vulnerable to the enemy sector closest to it.

The influence radius should scale with the influence level and the chance of attack for a vulnerable sector should scale with the influence level. The math would look like this for a single sector (in the style of C):
```
// All of this is calculated per sector with the weights depending on how close the neighboring sectors are
float influenceLevel = adjacentSectorCount / adjacentSectorDistance;
// The attack chance is only calculated if the influence radius reaches an enemy sector "influencing" it
float attackChance = influenceLevel / adjacentEnemyDistance;
```

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will force the player to come up with a new strategy of conquering and make gameplay interesting. Scattering bases for a reduced chance of attack or setting up sectors of defense in between important sectors and nearby enemy sectors protecting the sector of importance. This mechanic is rather inspired by Factorio's pollution mechanic.

Example of a defense sector protecting the sector from vulnerability representing the red line and the influence radius representing the gold lines.
![Screenshot 2024-07-25 102612](https://github.com/user-attachments/assets/1d4b5825-8418-48f9-9a3d-036864b198f7)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Eldeston** [comment]
Other than making gameplay interesting, the current system can lead to boring midgame gameplay, and you can just sit and wait for stuff to reload in Salt Flats with nothing attacking it. If this mechanic is implemented, this will make sector defense very fun and initiating the player to attack the enemy sectors or force the player to push through the tech tree.

**Comment by Eldeston** [comment]
Something to add, it would also be interesting if you also apply this same mechanic to enemies. The player would have to search for the sector causing vulnerability issues in the fog of war (again, like how Factorio forces the player to search for the biter nest causing defense issues in the early game without radars).

**Comment by guncatt** [comment]
this idea seems peak, and if it is added, I need multiple campaign saves to exist to replay the campaign, as this would make it so damn good.
