### ISSUE TITLE
Provide Build 104.10 download in itch.io

### ISSUE THREAD

**Issue by Neba-MD** [Anuken/Mindustry-Suggestions#513]
As in your alpha game version you have mentioned that there are unfinished/missing contents, some players might want to go back to the older version (104.10) to continue the complete gameplay.  Please consider continue to provide download link for Build 104.10 until the full release of v6.

**Comment by itcannotbe** [comment]
What is the big fuzz all about? 104.6 is the same with 104.10.

**Comment by Neba-MD** [comment]
I mean here: https://anuke.itch.io/mindustry

I don't see download for build 104.10 so new players or those who got their game updated without backup will have to find the older version elsewhere.

Better not to assume everyone know how to use github.

Correct me if I overlook something.

**Comment by itcannotbe** [comment]
Oh. You mean to make the last stable be available through itch.io. not just the alpha version.

**Comment by Anuken** [comment]
This was an oversight, should be getting fixed soon.
