### ISSUE TITLE
Breakable field applies to all buildings

### ISSUE THREAD

**Issue by Sh1penfire** [Anuken/Mindustry-Suggestions#5130]
### Describe the content or mechanics you are proposing.

Allow the breakable field to affect *all* buildings, not just props
The description already implies this, but it's false by default
![image](https://github.com/user-attachments/assets/9a93b7f1-b8bc-421e-b52c-d4bc934b8401)

The check in Tile::breakable checks destructible, breakable and updates but all three of theese do different things
![image](https://github.com/user-attachments/assets/4c9e78d6-e29f-4e83-83c9-eae6d5a10903)

I think it'd be better to change Block::canBreak to return breakable and have it true by default

It'd also remove the inconsistency of unbreakable props returning canBreak as true on the same tile
![image](https://github.com/user-attachments/assets/3fa1a093-47f4-4215-827d-1ebdf0b9cc1e)

(Would make a PR for this but I still need to set up intelij on my computer so I can't test this)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Trying to make functional hjson buildings on the player's team which can't be deconstructed is impossible without abusing world switches or some other unintended behaviour, and I think it'd also de-obfuscate the field's purpose

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
You can use vs code to
