### ISSUE TITLE
Choosing resource extraction Sorry if the quality of the text is poor, I am writing through a translator. 

### ISSUE THREAD

**Issue by Chchft** [Anuken/Mindustry-Suggestions#5132]
### Describe the content or mechanics you are proposing.

I want that if the drill was standing simultaneously on several resources for extraction, we could choose which resource to extract, as in the pop-up window for selecting unit production

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will help if, for example, you want to get a lot of sand, but together with the sand there will be one tile of another resource, then you will have to break and put the drill in a new place

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
interesting idea

**Comment by itcannotbe** [comment]
# A few things you shouldn't suggest

###### These have been proposed many times already, and I won't be adding them.

- Additional configuration of blocks, such as I/O side configuration
