### ISSUE TITLE
fourth core tier for erekir

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#5133]
### Describe the content or mechanics you are proposing.

fourth core tier for erekir.

It doesnt do anything except make a better unit whose soul purpose is to have more build speed (It can have more then that I just need build speed I beg)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I NEED MORE BUILD SPEED!!!

there are no polies in erekir and I like the design choice of no support units.

it will probably make endgame erekir faster. (Dont give the fourth core more health please the acropolis already has the highest hp in the game)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
nah just buff emanate build speed if it's not enough

**Comment by guncatt** [comment]
> nah just buff emanate build speed if it's not enough

TRUE!!!!

**Comment by guncatt** [comment]
> nah just buff emanate build speed if it's not enough

I think it having 200% build speed seems good.

The lower tiers should have 125% and 160%

Breaches already take a eternity to build. spamming units as defense is always better then them

**Comment by jehosula** [comment]
> I think it having 200% build speed seems good.
> 
> The lower tiers should have 125% and 160%
> 
> Breaches already take a eternity to build. spamming units as defense is always better then them

okay yeah this is just stupid now

just buff emanate speed by 30% from 150% to 180% the lower tiers are just slow, not so slow it's actually stupid, heck emanate is not that slow either, a 10% buff just to have the consistency is probably better

**Comment by guncatt** [comment]
> > I think it having 200% build speed seems good.
> > The lower tiers should have 125% and 160%
> > Breaches already take a eternity to build. spamming units as defense is always better then them
> 
> okay yeah this is just stupid now
> 
> just buff emanate speed by 30% from 150% to 180% the lower tiers are just slow, not so slow it's actually stupid, heck emanate is not that slow either, a 10% buff just to have the consistency is probably better

honestly I am willing for any build speed buff this is good enough!!!

**Comment by Krita-Burstflakes** [comment]
For 4 erekir core you need other content for it
