### ISSUE TITLE
Multiple Save Slots

### ISSUE THREAD

**Issue by ChaoticLeah** [Anuken/Mindustry-Suggestions#5135]
### Describe the content or mechanics you are proposing.

Multiple save lots would allow for multiple different games that are totally separate to be played

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be good for if you wanted to play a new game but not delete the old one, or if you want one modded and 1 normal game or even want to take a look at a friend's save without overriding your own one. There are probably more reasons than just this but those are the ones I could think about.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by galaxyjustice** [comment]
I too would like to see this as an option.  I have one game that I've been playing through with a friend, we haven't quite finished Erekir and I'd like to give Serpulo a try on my own.  

Having this ability built into the UI would be very useful. I realize there are ways to find the game files buried on my computer and make a back up and swap things back and forth (as was mentioned in #913), but there are many players that don't have the knowhow to do this or possibly the permissions to access those files without administrator assistance. Additionally I play using Steam and I can foresee the back up/cloud sync Steam does having issues with this action.
