### ISSUE TITLE
unhide heat reactor and fissile matter

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5136]
### Describe the content or mechanics you are proposing.

add the hidden heat reactor and fissile matter to the game and give them a purpose

heat reactor would have the stats the hidden version has (stats might use some tweaking) and fissile matter could be ammo for titan and scathe
for titan fissile matter could be some kind of extra powerful ammo that deals a lot more damage but with less aoe and fire rate, but a faster projectile
for scathe it would be bigger aoe but less damage

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

adds another heating option and gives some turrets additional ammo options for some turrets (trello shows more ammo types planned), honestly dunno what to say just stuff that seems a bit cool

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Tbh I'd be down to make fissile matter a "no use" material so that slag incinerators finally get some use
But also most maps have the [core incinerates overflow feature] which kinda ruins everything

**Comment by jehosula** [comment]
> Tbh I'd be down to make fissile matter a "no use" material so that slag incinerators finally get some use But also most maps have the [core incinerates overflow feature] which kinda ruins everything

it would be cool to give it uses for ammo, would add more synergies in erekir and also we already have a waste product, neoplasm, could make neoplasia reactors produce dormant cysts to give that block a use
