### ISSUE TITLE
Skirmishes

### ISSUE THREAD

**Issue by the-scallywag** [Anuken/Mindustry-Suggestions#5139]
### Describe the content or mechanics you are proposing.

A set collection of maps that each require a set objective, time limit or wave count in order to complete and move on to the next. 

Skirmishes are tiered via size: Small would be less than 5 maps, Medium would be more than 5 maps, Large would be less than 10 maps and Extra Large is anything else above. 

Skirmishes could also have locked tech, unlocked via moving onto the next map. Such as Cyclone being locked for maps 1-3 but unlocked on 4.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow players to construct their own mock-up campaigns. It would also fill the niche of players who enjoy campaign-style content and linear missions. 

It could also indirectly allow modders to test campaigns for modded planets, such as Serpulo's set missions, like Desolate Rift or Nuclear Production Complex.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Novanox4** [comment]
GIVE. I WANT IT NOW.
