### ISSUE TITLE
Tier 2 Factories for plast, metaglass and maybe phase

### ISSUE THREAD

**Issue by MeltdownGoBWMMMMMMMM** [Anuken/Mindustry-Suggestions#5143]
### Describe the content or mechanics you are proposing.

By tier 2 factories i mean the multi-press and sili crucible, and an equivalent 3x3 plast/glass factory would make endgame a lot less painful.
 Some of my ideas(that don't involve porting the gas system over to serpulo(serpul gases when)) are: replace sand with silicon for the big metaglass factory, and replace the oil in the big plast recipe with spores, albeit at a lower efficiency. Essentially make a more efficient, but more expensive glass factory, and make a cheaper, less efficient plast factory that can be fed by a zipper. 
The metaglass thing would pair nicely with a small and inefficient silicon smelter variant that doesn't use coal(but costs plastanium and uses a lot of power to balance it out, to make it unviable in early game), so you can place them adjacent to each other. 

I'm doubtful that the game needs a big phase factory, as phase isn't really a resource you use a lot, but my idea for a phase factory would be replacing the **immense** sand consumption with a more moderate silicon or glass consumption (or maybe both? Maybe make it so it can accept both glass and silicon, but it's more efficient when using silicon)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Making plast in endgame is incredibly painful. Glass is piss-eay to make, but you need a lot of it for T3-4 units and it's used in like half the mid-endgame recipes in trace amounts. 
Also, phase weavers require Curse of Ra levels of sand, so a less sandy way of making phase fabric would be greatly appreciated

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by guncatt** [comment]
nah man metaglass fine like Ima be honest I make a single metaglass factory and everything be good.

I make 4 and I got a life time supply of metaglass in 10 minutes
