### ISSUE TITLE
3rd path units for Naval and Air

### ISSUE THREAD

**Issue by the-scallywag** [Anuken/Mindustry-Suggestions#5145]
### Describe the content or mechanics you are proposing.

Ground has 3 paths, but not air nor naval. It would be fitting if all three types of units has three paths, totalling nine unit trees. This would give players more to choose from.

3rd tree for Air: Bombers
The third tree is something I'd see as bombers. Fighters, Supporters then Bombers. The t1 unit would drop a single weak bomb or be the bomb itself, like a nerfed aerial crawler. T2s and T3s would have stronger bombs and/or more of them. T4s would have very powerful bombs akin to the Mega's but a little stronger. The T5 might be something like the Pe-8 which is a IRL bomber. A single massive bomb, or multiple powerful ones

3rd tree for Naval: Missile submarines or Missile Boats
The third tree would be fitting to have something like a specialist unit in the naval type. These naval units, if submarines, could 'submerge' into the water when not in combat, unable to be targeted by turrets but not units, when submerged, it can be seen as dark silhouettes on the water, and to attack would re-emerge, becoming vulnerable to turret fire. If not submarines, simply long ranged missile ships. The t1s could fire small missiles that travel a little bit before exploding, like the risso. The T2s and T3s could have longer ranges and stronger missiles. T4s could fire much stronger missiles and have some sort of secondary. T5s could fire massive ICBM-like missiles.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Having more units would encourage more playstyles, different metas and intriguing strategies. It would also allow players to choose from more and give a fresh breath of air to Air and Naval, and would complete the unit trees for Serpulo (unless 4th tree funni dhhfhfhfhf)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
no, we already have too many lines, 2 naval lines that already struggle to differentiate somewhat 2 air lines that can actually not compete too much, let's not make them do that, and 3 ground lines that actually seem to have different niches, but we certainly don't need another line to balance

**Comment by guncatt** [comment]
> no, we already have too many lines, 2 naval lines that already struggle to differentiate somewhat 2 air lines that can actually not compete too much, let's not make them do that, and 3 ground lines that actually seem to have different niches, but we certainly don't need another line to balance

idk man I'd argue the 2 naval lines are perfect. retusa heals, and does NOTHING else (Other then kill other naval units every other year)

Oxynoe is a great wall breaker, and its overclock buff sort of makes it mandatory in the lategame (And also really good when spamming rissos and etc)

cyeirce does sort of struggle with identity tho. both bryde and cyerce attack long range.


Aegires is a godly support unit, with its electrified debuff, healing buildings and allies.

Navanax provides a good close range tier 5 naval option and its emp's can be devastating if ignored.

**Comment by jehosula** [comment]
> idk man I'd argue the 2 naval lines are perfect. retusa heals, and does NOTHING else (Other then kill other naval units every other year)
> 
> Oxynoe is a great wall breaker, and its overclock buff sort of makes it mandatory in the lategame (And also really good when spamming rissos and etc)
> 
> cyeirce does sort of struggle with identity tho. both bryde and cyerce attack long range.
> 
> Aegires is a godly support unit, with its electrified debuff, healing buildings and allies.
> 
> Navanax provides a good close range tier 5 naval option and its emp's can be devastating if ignored.

ya got a point, but we certainly would struggle with a third line
