### ISSUE TITLE
Decrease vela's same type healing

### ISSUE THREAD

**Issue by Leyn-pl** [Anuken/Mindustry-Suggestions#5146]
### Describe what you would like changed, and why.

Velas should heal other velas less to prevent them outhealing everything
Right now velas are the best non-naval t4. The same thing was some time ago with aegires, and the fix was decreasing their same type healing. I think velas should be balanced this way too

### Describe the changes you want to propose. Include possible alternatives.

Decrease vela's same type heal by ~50% or just make them less tanky

**Comment by SomeonesShade** [comment]
I feel like nerfs to vela is less preferred than just buffing scepter/arkyid on the same level for vela, so eh…

I’d rather see something like this to motivate unit diversity, only after the other options become good picks

**Comment by alphy228** [comment]
Vela aint that good tbh
Arkyid is a better shit base destroyer and payload quad is a better offensive force

**Comment by jehosula** [comment]
vela is not that good, it's that the other t4s are bad, and this is probably not the right way to nerf vela anyway

**Comment by guncatt** [comment]
vela aint good. its just that the only other competitor for the tier 4 slot is qaud and poor ol qaud gets its bombs completely shut down by force projecters.

(Buff Arkyid my beloved, buff its movement speed, buff the close range sap range, and buff the lifesteal, scepter can prob recieve 1k more hp, a little more speed, and much more damage output.

**Comment by guncatt** [comment]
maybe give antrumbra like 4 nova cannons (That are red, so that it can lead up to eclipses red lasers better) 

(Also so it can atleast fight back against segment)

Eh antrumbra is good anyway, it is really fucking strong when there is like 7 of them. (It moves at the same speed as oct so they usually pair together well)

**Comment by alphy228** [comment]
antumbra's not anywhere near good with quads are 2 times better than antumbras when spammed(especially with blast compound) and without blast antumbra still gets melted by stuff without being able to deal significant amounts of damage with its weapons

**Comment by guncatt** [comment]
> antumbra's not anywhere near good with quads are 2 times better than antumbras when spammed(especially with blast compound) and without blast antumbra still gets melted by stuff without being able to deal significant amounts of damage with its weapons

honestly every tier 4 can still get melted without dealing significant damage. qaud really suffers from force projecters. as its only attack immediately becomes useless.

and it cant exactly place anything down if you cover everything with conveyers.

qaud is fast, but it usually isnt fast enough to deal with 4 meltdowns before it immediately dies. (Qauds entire purpose is to die, the death damage is really the only reason qaud is a offensive force)
