### ISSUE TITLE
Serpulo Rework Ideas

### ISSUE THREAD

**Issue by masterslaytm** [Anuken/Mindustry-Suggestions#5147]
### Describe the content or mechanics you are proposing.

As we're well aware, that Serpulo is known to be extremely unbalanced, whereas Erikir is known to be quite balanced but not for beginners, I suggest some ideas I have in my mind:

- As you know, we start from Ground Zero and then keep bouncing around the whole planet in an attempt to claim every sector on it. My idea is, the campaign should be totally linear, like, after Ground Zero, we can capture any other sector near it, but, some sectors which are near a hard base should be restricted for the newer audience for ease. Eventually, the sectors will open in accordance to progression.
- My second thought is, we have units that seem to be quite unique, but, I think we should focus on how to make unit combinations unique. I understand there's a strategy of defending and also doing an offense, but I mean, another level of strategy formation, like, currently we have 3 broad type of units, which provide 7 unique unit trees in itself. You see, that we have those little crawlers, but they are totally underutilised by players. My suggestion is, there should be, maybe an air unit, which could provide stun support so that those crawlers can blast in their appropriate places. Also, we have power to be a backbone in most of our factories, how about having a t3 or t4 unit which can briefly disrupt power? It's just my ideas lol, I think it might not even be necessary, considering that a single Vela can disrupt a base without the need of such units.
- We can add some sort of morale counter, to make players calculate their moves and not spam stuff. Maybe introduce it at a later sector, but I think it might balance the game. Morale can be calculated depending on how frequently you can survive a wave, how many times units get butchered due to long ranged turrets from the enemy faction, or even the resource collection in the core. It works like a happiness system in farm games, but, not too penalising, it should be rewarding too if the morale goes high.
- Maybe introduce some sort of almanac for the status effects we usually get while raining, or when we get attacked by some lancers. Most players just don't know it exists lol.
- Inter faction alliances should be a thing in the game, with upto 4 layers of relations- Friendly, Neutral, Enemy, Hazard. Friendly or Neutral factions usually don't attack when you capture some sectors near them, but enemy does attack, whereas hazard factions would keep attacking the bases without a break. Also, Friendly factions might ask for assistance, like, you'll be asked to set up a base in the same sector, where both of you will play together to take down the enemy. (BTW do remember to keep the cores at a distance). Also, a new building by the name of Embassy should be made to communicate with the friendly factions, and also negotiate with enemy factions.
- You mentioned of Meteor Showers, can we get such events in Serpulo so that we can play it endlessly? Like. For example, the least performing sectors have a slight chance of rebelling against you and joining the enemy faction, which you'll later reclaim. It won't be that common, but when it does, a group of sectors change sides, and it'll be fun fighting with myself lol. This should be introduced late game.

I guess that's it lol, if I think something new, I'll make a new note.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The above mentioned suggestions might add depths in the game, and also try to curb the problem of spamming units even after Anuke decided to cap the units to 24 at max. The embassy stuff and factions would make the game more engaging and fun to try to communicate with the game AI while having a fight. Hope that helps!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
> As you know, we start from Ground Zero and then keep bouncing around the whole planet in an attempt to claim every sector on it. My idea is, the campaign should be totally linear, like, after Ground Zero, we can capture any other sector near it, but, some sectors which are near a hard base should be restricted for the newer audience for ease. Eventually, the sectors will open in accordance to progression.

if you mean numbered sectors, then nah, if you just mean harder named ones then yeah, you can access them way too early

> My second thought is, we have units that seem to be quite unique, but, I think we should focus on how to make unit combinations unique. I understand there's a strategy of defending and also doing an offense, but I mean, another level of strategy formation, like, currently we have 3 broad type of units, which provide 7 unique unit trees in itself. You see, that we have those little crawlers, but they are totally underutilised by players. My suggestion is, there should be, maybe an air unit, which could provide stun support so that those crawlers can blast in their appropriate places. Also, we have power to be a backbone in most of our factories, how about having a t3 or t4 unit which can briefly disrupt power? It's just my ideas lol, I think it might not even be necessary, considering that a single Vela can disrupt a base without the need of such units.

there isn't an actual problem these, solve and crawler is on the stronger side in BE anyway this could be a fun rework to existing units cause we already have too many lines

> We can add some sort of morale counter, to make players calculate their moves and not spam stuff. Maybe introduce it at a later sector, but I think it might balance the game. Morale can be calculated depending on how frequently you can survive a wave, how many times units get butchered due to long ranged turrets from the enemy faction, or even the resource collection in the core. It works like a happiness system in farm games, but, not too penalising, it should be rewarding too if the morale goes high.

those are literal robots most of them made soley to fight the enemy head on, morale does not make any sense at all for a game like this can also very easily be made very wrong and end up being obnoxious and further amplified by the lack of sense

> Maybe introduce some sort of almanac for the status effects we usually get while raining, or when we get attacked by some lancers. Most players just don't know it exists lol.

just make the core database better if it's not enough, it already covers all blocks and units that inflict status along with the statuses themselves

> Inter faction alliances should be a thing in the game, with upto 4 layers of relations- Friendly, Neutral, Enemy, Hazard. Friendly or Neutral factions usually don't attack when you capture some sectors near them, but enemy does attack, whereas hazard factions would keep attacking the bases without a break. Also, Friendly factions might ask for assistance, like, you'll be asked to set up a base in the same sector, where both of you will play together to take down the enemy. (BTW do remember to keep the cores at a distance). Also, a new building by the name of Embassy should be made to communicate with the friendly factions, and also negotiate with enemy factions.

this is in the list of things to never suggest

> You mentioned of Meteor Showers, can we get such events in Serpulo so that we can play it endlessly? Like. For example, the least performing sectors have a slight chance of rebelling against you and joining the enemy faction, which you'll later reclaim. It won't be that common, but when it does, a group of sectors change sides, and it'll be fun fighting with myself lol. This should be introduced late game.

it should be optional so players don't have to be tortured, also it wouldn't make sense unless it's some sort of glitch

also additional note: this game was made by a single developer that wants to move on, it's unlikey so much will be allowed to change like this
