### ISSUE TITLE
Google play achievements

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry-Suggestions#5149]
### Describe the content or mechanics you are proposing.

The steam version has achievements, so why not add achievements to google play

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be cool to have achievements on the android version, and with the new google play on pc thing (beta iirc) it could possible be on pc as well 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
guess it's just there for steam to add a little more incentive to pay

**Comment by JasonP01** [comment]
Anuke could add an optional thing to pay for special content for the mobile varient, i think the vocal community wouldnt mind.

Either way i might look into this to see if i can pr it in, if it requires google dev acc and nonsense i wont bother (there has been a couple suggestions for this)

**Comment by JasonP01** [comment]
~~plus i want more google play xp for levels so yes (there is no reward for higher levels or level ups)~~
