### ISSUE TITLE
Build speed information

### ISSUE THREAD

**Issue by Excavator987** [Anuken/Mindustry-Suggestions#515]
**Describe the content or mechanics you are proposing.**
Show the build speed of a unit (if available) in unit information, for example in the tech tree, as shown
![image](https://user-images.githubusercontent.com/58992170/93367931-195a4680-f845-11ea-8008-cb5176b1d57f.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will greatly help with finding out what mech is best to build with, such as in v4/v5

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
There are practically no useful stats displayed at the moment. This (and other information) will be added later.

**Comment by potatoisagender** [comment]
@Anuken is there anyway I can help with things like this? Something involving less coding and more custodial work. So itch.io cleanup, data sheets for unit information, etc. etc. I suppose I could learn Java, I have some coding experience, but I was just wondering if you needed anything unrelated to code.
