### ISSUE TITLE
Buff Scathe missile speed

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#5150]
### Describe what you would like changed, and why.

buff the scathe's missile speed, the scathe almost always misses against a single unit, like a precept. or just a dagger. (Its not the Scathes fault, Its abit difficult to aim properly when controlling scathe anyway)

in return, lowering the missiles lifespan and buffing the turning speed so it would have the same range, and same missile mobility as before.

Scathe already takes a immense amount of carbide to shoot once, usually just to waste it by completely missing the shot.

### Describe the changes you want to propose. Include possible alternatives.

just double the missile speed, Half the missile lifespan, and double how fast it can turn around

I think just massively buffing the turning speed would be enough if it doesnt fix the problem. (Still would probably miss at longer ranges)

**Comment by guncatt** [comment]
![miss](https://github.com/user-attachments/assets/5cb2e64e-00c6-4887-a1fe-a1ac3d178464)
![miss2](https://github.com/user-attachments/assets/ee4415e6-eef2-4119-a033-94516784283d)


Proof. (It has happened on precepts too. no proof though)

**Comment by Bottinator22** [comment]
Isn't Scathe designed to be more of an offensive turret for sieging the enemy base?

**Comment by Slotterleet** [comment]
> Isn't Scathe designed to be more of an offensive turret for sieging the enemy base?

Huh???

**Comment by guncatt** [comment]
> Isn't Scathe designed to be more of an offensive turret for sieging the enemy base?

me when minus 70% building damage
