### ISSUE TITLE
update erekir

### ISSUE THREAD

**Issue by zeroin4ik** [Anuken/Mindustry-Suggestions#5153]
### Describe the content or mechanics you are proposing.

**please add non-plot sectors of the erekir in the mindustry**

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**new content on the erekir - it`s good**

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
how about adding numbered erekir sectors yourself with java modding

**Comment by camelStyleUser** [comment]
> new content <...> is good

he is already working on new content called neoplasm

**Comment by Novanox4** [comment]
V8 is gonna add lots content to both planets, don't worry.

**Comment by guncatt** [comment]
erekir sector generation is imperfect at the moment.

(Sometimes no beryl or graphite near spawn, resulting in there being no way to really progress or do anything. (Same with vents, you need them for power to even mine beryl or graphite)

(the waves arent even finished, think they are meant to be neo plasm enemies)

I will now show a few images.

![20240807102715_1](https://github.com/user-attachments/assets/d10697cf-8ab1-4bac-a9be-0743ae5a2f42)
I'd like to see anyone figure out theres beryl right here.

![20240807104158_1](https://github.com/user-attachments/assets/0a9203e1-2a16-4ad2-999e-a27ffcad9431)
was bouta consider this one impossible, but hey, with enough breaches, anything is possible right? (Rip the poor souls who launched here without the resources to make like 10 breaches)

![20240807104502_1](https://github.com/user-attachments/assets/8f2dfa87-d369-43fd-bd3a-ece1bc2c2460)
also this is a thing just incase you thought you only needed to get to a vent. (Erekir unloaders dont work on cores either so major L)

**Comment by guncatt** [comment]
atleast finding a vent allows you to use radars to fight the fog of war instead of breaches

**Comment by guncatt** [comment]
https://youtu.be/tysir0qkc9I?si=VsIgE7eRm_aFspPv   just barely did it by launching with a core bastion and max resources! (Assuming your using a core bastion to launch it)

so ye. (Non are impossible as far as I have seen, most are REALLY annoying to get through tho)
