### ISSUE TITLE
World logic play music

### ISSUE THREAD

**Issue by alphy228** [Anuken/Mindustry-Suggestions#5155]
### Describe the content or mechanics you are proposing.

Play music world logic instruction/add music to play sound

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Playing boss2 on world logic maps

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedMatrix1** [comment]
I think it's a good idea! em and sfx also need. And using mods we can add new sounds, bro it cool!
