### ISSUE TITLE
Containing neoplasm.

### ISSUE THREAD

**Issue by Zalimo4733** [Anuken/Mindustry-Suggestions#5158]
### Describe the content or mechanics you are proposing.

I really like the idea of containing a neoplasm heart instead of destroying it, giving the player some advantages, maybe even biologically advanced machinery, which can make chemical reactions faster, enabling some more advanced weaponry/ammo, using the neoplasm to sabotage the enemies water production. And even enabling some anti-neoplasm weaponry, ammo etc.

How to contain neoplasm:
First of all, the units will not attack neoplasm hearts unless the player commands them to. They CAN attack hearts, and you can destroy hearts. But they will not automatically target them.
If you want to contain a heart, you need a gew things:
First of all a new gas called "biosuppressor" which well, suppresses neoplasm heart's growth. You can make it by mixing cyanogen with arkcyte(the recipe can be changed. Im not sure), and some heat in "biosuppressor mixer" (biosuppressor name can be changed. I am not too creative at thinking names for stuff.)
You need to bring the biosuppressor to the heart, and put a new block called "nozzle" which releases the fluid inside the pipes controllably. You need to put the nozzle adjacent to and facing towards the heart. When supplied with biosuppressor, it will slow down its growth drastically. But can still grow. So you need to cover the heart with walls so it cant grow further. If you dont use a nozzle with suppressor, the heart will damage the walls and can grow over/through the walls. The suppressor weakens it enough to prevent it from doing so.
After that, you need an "extractor" that will extract the item from the heart (i dont know what item we extract. But it could be a good way to implenent the dormant cyst) you put the extractor right outside of the wall that is used to block the heart. The extractor has a robotic arm that reaches out to the heart and extract the stuff. The rest is just conveyors to carry the items to wherever you want. You can also pour some neoplasm into a vent (get the neoplasm from a neoplasia reactor and pour it into the vent directly with a pipe) to spawn a new neoplasm heart. Which can also be a way of how a neoplasm outbreak can happen if you arent careful and not contain the neoplasm fast enough, or you fail to supply it with enough biosuppressor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This content will add a lot more depth to neoplasm. And it seems like a cool idea tingling my brain for a long time.

Thanks for taking your time and reading all the way.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
seems like an overcomplicated way to get a new resource or unlock new tech, you could simplify it into something for a game like this by making it just a few blocks, maybe even one to build a suppressed heart and extract stuff without too many inputs, it really should not take a whole paragraph or two of explanation for something like this, it needs to not be too complicated cause mindustry basically asks for any relevant feature to be used at least once per game
