### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Sked557** [Anuken/Mindustry-Suggestions#5159]
### Describe the content or mechanics you are proposing.

I hope that the multiplayer feature can be improved and made easier, I find it difficult to play with friends only relying on local connections and I find it quite complicated to set up a server, and also I only use a mobile phone to play, that's all from me, hopefully it's read. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Maybe add online features without having to create your own server. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
anuke is an indie developer and can't afford having his own servers, there are several ways to play multiplayer globally in the discord server's pins
