### ISSUE TITLE
Logic Node

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#516]
Logic Node 

A Logic Node block that acts like power node but can connect to any blocl like processors do, their main job is for when a processors range isnt long enough, you connect it to a logic node, and connect the logic node into the block you were going to connect to processor, this helps people increase their processors range while also keeping them. When a processor connects to a logic node block, it should have power it like other blocks (enable/disable, sense, get link etc.) while also when a processor is connected to a logic node, it should have power over everything that is connected to that node, if you connect a processor to a logic node, that is connected to a [example block 1] and a logic node, that is connected to a [example block 2], the processor should have power over the nodes, example block 1 and example block 2. This may be hard to implement though but if you do it it will be a great addition. Counterparts of power nodes like big power node, surge tower, etc. would make it better but also a 3x3 power & logic node and an infinite range power (just increase power infinite's range instead) & logic node (sandbox only) would make it even better.

Now you may say, there are logic blocks with higher range, but there may be situations where we may not be able to afford them or we may have blocks that are too distinct even hyper processor cant connect to both at the same time, you may also say you could write the code to a memory cell and read from the other but it takes alot of wok (especially if your code is very long) and some people may not understand how memory cells work.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
I don't think this is necessary. By the time you are using hyperprocessors and using "complex code" in such a large range, you should be able to manipulate memory cells at that point.

**Comment by Anuken** [comment]
I don't see much need for this.
