### ISSUE TITLE
Unit Commands list

### ISSUE THREAD

**Issue by the-scallywag** [Anuken/Mindustry-Suggestions#5160]
### Describe the content or mechanics you are proposing.

This will add on to the already present unit commands in the BE version and eventually V8. I have a feeling this won't be added, but I might as well try. All of these don't have to all be added, these are just suggestions for new unit commands.

**Movement** **based**:
Spread Out: Instead of clumping up in a large ball, units will spread out around the designated area.

Long: Units choose the longest route to the area

Short: Units choose the shortest route to the area

Weak: Units choose the weakest path (least defences)

Strong: Units choose the strongest path (most defences)

Swarm: Units choose random paths to the area

**Formations**:
Bow: Longest range Units will stay behind the group

Shield: Strongest Units will stay at the front

Fodder: Weakest Units will stay at the front

Fort: Strongest Units will surround other units

**Attacking** (Unit Factories):
Assault: Target nearest enemy base as soon as unit produced

**Attacking**:
Ignore Defences: Ignores walls and any other defence type block. If target is behind a wall, do not fire until wall is destroyed OR wall not in FLOS (firing line of sight). Does not apply if wall or any other defence type block is specifically targeted

Ignore Offensives: Ignores turrets and enemy units. Does not apply if enemy unit or turret is specifically targeted

Random: Randomly select and fire at targets in range, Change target each second.

Target Ground: Fire at a location even if there are no structures

**Miscellaneous**:

Skittish: Avoids enemies, runs from target if shot at

Avoid <block/ground/thing>: Avoids the set parameters

Destruct: Automatically kills unit. Must be allied. (Not like deconstruction)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This list has many commands which would make units more of a good option for fighting and can help players develop new strategies. This can make the RTS aspect feel a little more full and can encourage players to coordinate units effectively.

Whilst it is a big list, it's just suggestions, and if you'd like to tweak some of them or take ideas, feel free to do so.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
most of these just made doing already possible and feasible stuff easier

**Comment by mahdoosh1** [comment]
i think it is too much

the path of longest and shortest is useless as you can see and think

the strongest path is useless because what's the point of that, wasting time destroying defences?

others make sense, but i want to add another option

Cutoff: attack turret and unit assembly inputs and prevent ammo from reaching turrets and material from reaching unit assemblies.

**Comment by mahdoosh1** [comment]
> 
> you can see and think so you can easily focus the transportation blocks for cutoff, not very useful

easily? i dont think so. there are attack maps with a lot of item sources or liquid sources, if you were going to attack and target one by one then what's the point of "tower defence game", you can not multi-task destroying sources AND defending core AND production & factory

anyway, that was just a suggestion for targeting and doesnt relate to path finding, it probably won't happen.

also what i mean by see and think is that it doesn't take so long to realize what's the shortest or longest path.

sorry for the long text I'm just talkative :D

**Comment by jehosula** [comment]
> easily? i dont think so. there are attack maps with a lot of item sources or liquid sources, if you were going to attack and target one by one then what's the point of "tower defence game", you can not multi-task destroying sources AND defending core AND production & factory

those maps with source spam are trash regardless, and even then it's really not that hard, and also the game is no longer primarily tower defense, erekir is "the rts planet"

**Comment by mahdoosh1** [comment]
> those maps with source spam are trash regardless, and even then it's really not that hard, and also the game is no longer primarily tower defense, erekir is "the rts planet"
> 

ok but this suggestion is good overall
