### ISSUE TITLE
Mindustry Music Discord Channel

### ISSUE THREAD

**Issue by Davidw6** [Anuken/Mindustry-Suggestions#5162]
### Describe the content or mechanics you are proposing.

Mindustry music is very appealing, some of us love it so much that they have even started making soundtracks that sound similar to the in-game music, we should be able to share our tracks on discord

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Some of the soundtracks created could possibly be added in-game if Anuke likes what others have created

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by mahdoosh1** [comment]
> Some of the soundtracks created could possibly be added in-game if Anuke likes what others have created

Yes, but how about copyright?
