### ISSUE TITLE
Block dragging in generate menu

### ISSUE THREAD

**Issue by AxoCat** [Anuken/Mindustry-Suggestions#5164]
### Describe the content or mechanics you are proposing.

A way to drag the generation steps in the generate menu like logic processor instructions instead of having to click the move up/down buttons.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would make it much more convenient to rearrange map generation steps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
You can...? Just press and hold on the colored part of the instruction.

**Comment by AxoCat** [comment]
I'm talking about map generation steps, those aren't draggable and it's quite annoying
