### ISSUE TITLE
Parallaxe

### ISSUE THREAD

**Issue by Frel495** [Anuken/Mindustry-Suggestions#5165]
### Describe what you would like changed, and why.

I propose to enable the Parallax turret to capture Allied flying troops using logical processors. In conjunction with repairing turrets, this would allow for faster transfer of resources using flying units, if Parallaxes were placed on their route, and would also allow launching not particularly massive units into the rear of enemy bases (for example, to set fire to the base using pyrotite)

### Describe the changes you want to propose. Include possible alternatives.

If this does not suit you, you can add the possibility of Parallax to attract enemy units not only strictly towards yourself, but also in the other direction within the range of the turret, and the strength of the turret will depend on the proximity of the units to the turret

**Comment by jehosula** [comment]
the first one is quite hilarious and trollish
