### ISSUE TITLE
Add Bleeding Edge as a Steam Beta branch.

### ISSUE THREAD

**Issue by Sarke** [Anuken/Mindustry-Suggestions#5166]
### Describe the content or mechanics you are proposing.

Add Bleeding Edge as a Steam Beta branch.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I recently bought the game, love it. I decided to buy it even though it is available for free on GitHub because I like the features Steam brings and I also want to support the developer.

But then I found out that the Steam version is quite a bit older than the "current" bleeding edge version. I noticed this because of a bug that I googled, and as with many such things it's fixed in the BE but not the Steam version.

So it's disappointing that I no longer play the Steam version I paid for.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by the-scallywag** [comment]
While it might take some effort, it'd be good as it could alleviate the pain for people who aren't very good at managing or downloading files and is generally an easier option for people who'd want to use bleeding edge.

**Comment by Anuken** [comment]
As nice as this would be, it's far more difficult to deploy a proper build with Java bundled than it is to deploy a single jar file (as with BE builds). I would probably have to host the minified JREs somewhere and have the build scripts download them for use in Steam deployment, which would be a lot of work to set up.

**Comment by Sarke** [comment]
Thank You!
