### ISSUE TITLE
Phase wall rework

### ISSUE THREAD

**Issue by Absolutan115** [Anuken/Mindustry-Suggestions#5169]
### Describe the content or mechanics you are proposing.

Remove bouncing projectile, add 50% projectile damage reduction. Example damage is 200, projectile damage Will take 100 damage

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Bouncing projectile kinda useless for high tier enemy unit, also very low trigger rate. Better add reduction (I really want it)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If you're relying on walls to defend against high tier units, you're playing the game wrong.

~~What are turrets? What are units?~~

**Comment by Absolutan115** [comment]
Turret already strong, wall just absolutely weak.
A single swarmer or Spectre can handle lot of thing.

**Comment by Absolutan115** [comment]
Unit too many adjustment lead to unbalanced

**Comment by Absolutan115** [comment]
I mean fighting high tier unit example desolate rift defense needed always like this? 
![Screenshot_2023-08-23-11-33-58-559_io anuke mindustry be](https://github.com/user-attachments/assets/614890d8-32ee-45af-b5ea-cb03f0fede79)

**Comment by Absolutan115** [comment]
A LOTS OF WALL

**Comment by Frel495** [comment]
I like this idea. In my opinion, similar properties for the wall are more suitable for the properties of the phase fabric (which, in my opinion, I was able to roughly understand), whose current properties reflect projectiles. It would also be quite useful if combined with plastanium walls, one "but", you need more strength to make sense of it, but I really like the idea!

**Comment by Absolutan115** [comment]
Well I hope anuke add composite wall with size 2×2 and 3×3. This wall contain all special effect with hp 5000 2×2 wall and 10000 hp 3×3 wall

**Comment by OnyxFinger** [comment]
> If you're relying on walls to defend against high tier units, you're playing the game wrong.
> 
> ~What are turrets? What are units?~

have you uh
played the game sir ??? I agree this idea is odd, but saying that walls shouldn't be used against high tier units is kinda stupid imo
if anything, it's the other way around in my experience, walls nice early on but not necessary at all, it's only later that they are necessary

**Comment by guncatt** [comment]
phase wall good tho. 

if anything I feel its far too annoying as damage feels extremely inconsistent.

**Comment by guncatt** [comment]
> If you're relying on walls to defend against high tier units, you're playing the game wrong.
> 
> ~What are turrets? What are units?~

the corvus in question:

**Comment by itcannotbe** [comment]
> > If you're relying on walls to defend against high tier units, you're playing the game wrong.
> > ~What are turrets? What are units?~
> 
> the corvus in question:

The only wall material corvus doesn't like.

**Comment by itcannotbe** [comment]
> Well I hope anuke add composite wall with size 2×2 and 3×3. This wall contain all special effect with hp 5000 2×2 wall and 10000 hp 3×3 wall

~~This isn't V3~~

**Comment by Absolutan115** [comment]
Oh yeah now V12

**Comment by Absolutan115** [comment]
> > Well I hope anuke add composite wall with size 2×2 and 3×3. This wall contain all special effect with hp 5000 2×2 wall and 10000 hp 3×3 wall
> 
> ~This isn't V3~

Idk about V3 though.

**Comment by Absolutan115** [comment]
1 reign can destroy the toughest wall in few second, corvus have good counter plastanium wall. I want phase wall become specific counter to projectile. Plastanium wall to laser, phase wall to projectile, and surge wall idk.
