### ISSUE TITLE
Let spiders walk further into dark areas

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#517]
Currenly spiders stop when facing dark areas (thick map walls). I suggest letting them go further or make darkness push spiders away slightly, like map borders do, instead of acting like a solid block.
It will let spiders go through thin dark areas like these:
![image](https://user-images.githubusercontent.com/55051135/93403751-1a18ca00-f891-11ea-9f49-c2087b9e6312.png)
https://cdn.discordapp.com/attachments/391020510269669378/755939553537425418/bandicam_2020-09-17_02-23-37-419.mp4

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by kingb74** [comment]
I'm in support i dont see anything wrong
