### ISSUE TITLE
Cleroi being able to shoot over walls like murei

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#5171]
### Describe what you would like changed, and why.

Cleroi has a very similar projectile to merui. aside from it being stronger.

Cleroi is rather weak compared to the other ground tier 2. locus. which has alot of hp. and sort of erases tungsten walls from existence in groups of 6 or more.

Cleroi's segment turret also does absolutely nothing to diffuses or sublimates. and titans afflicts etc.

I think, cleroi should be able to fire over walls, which will make it just as useful as locus and murei. (Ontop of its segment turret.

### Describe the changes you want to propose. Include possible alternatives.

cleroi shooting over walls like murei.

Its that or buff cleroi in some other way so it isnt as hard countered to like 2 ozone sublimates and tungsten walls. (Or diffuse for that matter)

**Comment by jehosula** [comment]
cleroi isn't artilery and it's insanely op, the segments block nearly everything if you have enough cleroi and the splash allows it to beat even locus in big enough fights

**Comment by guncatt** [comment]
> cleroi isn't artilery and it's insanely op, the segments block nearly everything if you have enough cleroi and the splash allows it to beat even locus in big enough fights

it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.

Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.

cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op.  (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)

**Comment by jehosula** [comment]
> it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.
> 
> Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.
> 
> cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op. (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)

1 it can absolutely beat any turret that shoots bullets, in big enough numbers, even afflict

2 you can use locus or vanquish to guard cleroi and let them splash everything

3 it absolutely can destroy titan projectiles before they get too close and quite a few turrets are affected, also merui is trash and only useful if you are struggling with unit cap

**Comment by OnyxFinger** [comment]
> > cleroi isn't artilery and it's insanely op, the segments block nearly everything if you have enough cleroi and the splash allows it to beat even locus in big enough fights
> 
> it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.
> 
> Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.
> 
> cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op. (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)

Cleroi is strong against breaches as it can nullify their shots
cleroi can outrange diffuse and sublmiate
cleroi has high dps and AOE. Cleroi has a hard time fighting against afflict and titan, but so is the case of every other t2.

In blobs, cleroi works better than locus.

So I definitely disagree with your take that cleroi is only strong on defense
but I do agree with the fact that it is good on offense.
Walls can easily make up for its lack of hp, and the point defense is good against air units (splitting groups of cleroi around your base is a good way of countering air units such as avert and obviate.

Generally speaking, cleroi is a bit overpowered as its only issue is its health, which can be made up for using some way of tanking.

The only moment where locus is better is specifically during early game pvp, since on survival cleroi works better (can sit under walls where the enemies come, which isn't doable in pvp because the enemy can attack from somewhere else and you'd lose too much time placing this many walls. And in attack, cleroi is better because it can cheese early game turrets).

giving cleroi the ability to bypass walls as well is a horrible idea

**Comment by guncatt** [comment]
> > it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.
> > Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.
> > cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op. (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)
> 
> 1 it can absolutely beat any turret that shoots bullets, in big enough numbers, even afflict
> 
> 2 you can use locus or vanquish to guard cleroi and let them splash everything
> 
> 3 it absolutely can destroy titan projectiles before they get too close and quite a few turrets are affected, also merui is trash and only useful if you are struggling with unit cap

murei is good actually. it shoots over walls, and in groups of 6 or more, it can easily destroy breaches and turrets before they can kill smh.

If murei is a choice over stele, you should use murei.

**Comment by jehosula** [comment]
> murei is good actually. it shoots over walls, and in groups of 6 or more, it can easily destroy breaches and turrets before they can kill smh.
> 
> If murei is a choice over stele, you should use murei.

merui needs you to have tungsten to build it and that means t2 units are coming, and also diffuse and sublimate wreck meruis trying to snipe over walls

**Comment by guncatt** [comment]
> > > cleroi isn't artilery and it's insanely op, the segments block nearly everything if you have enough cleroi and the splash allows it to beat even locus in big enough fights
> > 
> > 
> > it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.
> > Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.
> > cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op. (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)
> 
> Cleroi is strong against breaches as it can nullify their shots cleroi can outrange diffuse and sublmiate cleroi has high dps and AOE. Cleroi has a hard time fighting against afflict and titan, but so is the case of every other t2.
> 
> In blobs, cleroi works better than locus.
> 
> So I definitely disagree with your take that cleroi is only strong on defense but I do agree with the fact that it is good on offense. Walls can easily make up for its lack of hp, and the point defense is good against air units (splitting groups of cleroi around your base is a good way of countering air units such as avert and obviate.
> 
> Generally speaking, cleroi is a bit overpowered as its only issue is its health, which can be made up for using some way of tanking.
> 
> The only moment where locus is better is specifically during early game pvp, since on survival cleroi works better (can sit under walls where the enemies come, which isn't doable in pvp because the enemy can attack from somewhere else and you'd lose too much time placing this many walls. And in attack, cleroi is better because it can cheese early game turrets).
> 
> giving cleroi the ability to bypass walls as well is a horrible idea

I do agree, cleroi would probably need a damage nerf if it was 

> > murei is good actually. it shoots over walls, and in groups of 6 or more, it can easily destroy breaches and turrets before they can kill smh.
> > If murei is a choice over stele, you should use murei.
> 
> merui needs you to have tungsten to build it and that means t2 units are coming, and also diffuse and sublimate wreck meruis trying to snipe over walls

murei is still a better stele in half the situations it is used in,

It is better if there are bryl walls or just any walls in general as it can destroy most turrets before they can take out your clerois and locus's. (ontop of clerois defending murei's)

**Comment by OnyxFinger** [comment]
> > > it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.
> > > Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.
> > > cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op. (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)
> > 
> > 
> > 1 it can absolutely beat any turret that shoots bullets, in big enough numbers, even afflict
> > 2 you can use locus or vanquish to guard cleroi and let them splash everything
> > 3 it absolutely can destroy titan projectiles before they get too close and quite a few turrets are affected, also merui is trash and only useful if you are struggling with unit cap
> 
> murei is good actually. it shoots over walls, and in groups of 6 or more, it can easily destroy breaches and turrets before they can kill smh.
> 
> If murei is a choice over stele, you should use murei.

merui is not a choice over stell, because it costs tungsten.
If anything, it would be a choice against locus since there cost (70 tung vs 80 tung) are similar. While merui's abilities do make it poweerful as a t1, it is not powerful enough to rival with locus, even when accounting for the higher cost of tier 2 factories.

**Comment by guncatt** [comment]
> > > > it isnt as useful against turrets, its only marginally useful against breaches but diffuses shoot like 300 bullets per second and sublimate cant even be blocked.
> > > > Cleroi is rather strong against units, but locus also counters cleroi's segment turret as it doesnt shoot bullets.
> > > > cleroi also cant destroy titan projectiles fast enough. (Also like 90% of the erekir turrets arent even effected by its segment turrets, it is not op. (Cleroi is only strong on defense, unlike murei, which works at both and does a fair job at both)
> > > 
> > > 
> > > 1 it can absolutely beat any turret that shoots bullets, in big enough numbers, even afflict
> > > 2 you can use locus or vanquish to guard cleroi and let them splash everything
> > > 3 it absolutely can destroy titan projectiles before they get too close and quite a few turrets are affected, also merui is trash and only useful if you are struggling with unit cap
> > 
> > 
> > murei is good actually. it shoots over walls, and in groups of 6 or more, it can easily destroy breaches and turrets before they can kill smh.
> > If murei is a choice over stele, you should use murei.
> 
> merui is not a choice over stell, because it costs tungsten. If anything, it would be a choice against locus since there cost (70 tung vs 80 tung) are similar. While merui's abilities do make it poweerful as a t1, it is not powerful enough to rival with locus, even when accounting for the higher cost of tier 2 factories.

mf be acting like tungsten is like titanium. man would claim dagger over nova. (Nova just takes too long to build)

**Comment by OnyxFinger** [comment]
> mf be acting like tungsten is like titanium. man would claim dagger over nova. (Nova just takes too long to build)

bruh
tungsten is an important resource, it's limited early, yet very important for any building that isn't early game (electrolyzer, oxidation chambers, chemical combustion chambers, t2 refabricators). So yes, tungsten is like titanium
In fact, it's harder to get than titanium, because titanium drills are much cheaper and can be boosted. You can also more easily access a higher tier of drills (laser : graphite, silicon, titanium) once you get it, while tungsten is less straight forward (you need to spend your tungsten on oxide first, in order to get access to large plasma bores. Either that, or you make chemical combustion chambers in order to spam the incredibly power hungry impact drill).

Also it's still better to spend tung on locus than it is to spend it on merui

**Comment by guncatt** [comment]
> > mf be acting like tungsten is like titanium. man would claim dagger over nova. (Nova just takes too long to build)
> 
> bruh tungsten is an important resource, it's limited early, yet very important for any building that isn't early game (electrolyzer, oxidation chambers, chemical combustion chambers, t2 refabricators). So yes, tungsten is like titanium In fact, it's harder to get than titanium, because titanium drills are much cheaper and can be boosted. You can also more easily access a higher tier of drills (laser : graphite, silicon, titanium) once you get it, while tungsten is less straight forward (you need to spend your tungsten on oxide first, in order to get access to large plasma bores. Either that, or you make chemical combustion chambers in order to spam the incredibly power hungry impact drill).
> 
> Also it's still better to spend tung on locus than it is to spend it on merui

locus requires constant tungsten intake. murei doesn't.

also murei can counter sublimate if the enemy is stupid enough to put a ozone liquid tank near their sublimate as murei can just destroy that and their entire defense blows up.

**Comment by jehosula** [comment]
> also murei can counter sublimate if the enemy is stupid enough to put a ozone liquid tank near their sublimate as murei can just destroy that and their entire defense blows up.

so can stell, also stell is cheaper, and locus's constant input isn't that much of a hurdle

**Comment by guncatt** [comment]
> > > mf be acting like tungsten is like titanium. man would claim dagger over nova. (Nova just takes too long to build)
> > 
> > 
> > bruh tungsten is an important resource, it's limited early, yet very important for any building that isn't early game (electrolyzer, oxidation chambers, chemical combustion chambers, t2 refabricators). So yes, tungsten is like titanium In fact, it's harder to get than titanium, because titanium drills are much cheaper and can be boosted. You can also more easily access a higher tier of drills (laser : graphite, silicon, titanium) once you get it, while tungsten is less straight forward (you need to spend your tungsten on oxide first, in order to get access to large plasma bores. Either that, or you make chemical combustion chambers in order to spam the incredibly power hungry impact drill).
> > Also it's still better to spend tung on locus than it is to spend it on merui
> 
> locus requires constant tungsten intake. murei doesn't.
> 
> also murei can counter sublimate if the enemy is stupid enough to put a ozone liquid tank near their sublimate as murei can just destroy that and their entire defense blows up.

also ngl I was thinking about anthicus and how quell is far too cheap to produce enmass. (Literally costs as much as murei and then needs cyanogen, and some extra power)

This post was gonna be about anthicus but cleroi also seemed abit weak in certain scenarios. (Tungsten walls have some insane amount of hp and locus spam is like the only way to get through them, cleroi is really weak to tungsten walls plus regen projecter then you add a diffuse and its usually fine)

Anthicus should definitely have another weapon then its missiles.

**Comment by OnyxFinger** [comment]
> locus requires constant tungsten intake. murei doesn't.

merui is still incredibly expensive for barely more than a t1
that only matters if you've placed the factory with low tungsten economy, or on a map with low tungsten availability in the first place. Also, locus is a really really big improvement over t1 units. So much so that it is worth the price, if you must fight at this point of the game

> also murei can counter sublimate if the enemy is stupid enough to put a ozone liquid tank near their sublimate as murei can just destroy that and their entire defense blows up.

that is very dependant on the enemy's defense. Merui also has a hard time against breaches. It can deal much damage, but it will force high losses as well (it's important to consider it imo, because sublimate isn't the only gun you can use early on).

**Comment by guncatt** [comment]
> > locus requires constant tungsten intake. murei doesn't.
> 
> merui is still incredibly expensive for barely more than a t1 that only matters if you've placed the factory with low tungsten economy, or on a map with low tungsten availability in the first place. Also, locus is a really really big improvement over t1 units. So much so that it is worth the price, if you must fight at this point of the game
> 
> > also murei can counter sublimate if the enemy is stupid enough to put a ozone liquid tank near their sublimate as murei can just destroy that and their entire defense blows up.
> 
> that is very dependant on the enemy's defense. Merui also has a hard time against breaches. It can deal much damage, but it will force high losses as well (it's important to consider it imo, because sublimate isn't the only gun you can use early on).

true. I actually agree.

Murei works best when with other tier 2s to support its rampage against the enemys ducts and explosive material.

(Hell it even works really well with steles or eludes as distractions so merui can pick off the ducts to ammo) point is, merui is still really good, and is definitely not bad or weak in any way.
