### ISSUE TITLE
Melted effect buff

### ISSUE THREAD

**Issue by Absolutan115** [Anuken/Mindustry-Suggestions#5173]
### Describe what you would like changed, and why.

Melted currently didn't have any combination like fire oil, shock wet, and blast freeze. My opinion adding blast melted effect, damage still same like blast freeze (18). Melted mean metal become softer so it become easier to destroy with a blast.

### Describe the changes you want to propose. Include possible alternatives.

Melted is weakest effect from all debuff, because don't have any combination. If have reactive combination it Will become better.

**Comment by jehosula** [comment]
melting, DOES get synergy with oil, wdym?

**Comment by Absolutan115** [comment]
> melting, DOES get synergy with oil, wdym?

It just make melted effect longer, also the synergy that you mean is melted + oil = make longer time plus triggering burn effect.
