### ISSUE TITLE
Let "texture marker" could draw any texture.

### ISSUE THREAD

**Issue by CutePillow** [Anuken/Mindustry-Suggestions#5176]
### Describe the content or mechanics you are proposing.

Let the "texture" in "Set marker" in world-processor could draw any texture in game. It can only draw such like "@blast-drill" but can't draw a "@blast-drill-top" now.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will let world-processor do more interesting things.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
wdym it can draw a "blast-drill-top"

**Comment by camelStyleUser** [comment]
`@blast-drill-top` is not a real builtin content constant though

**Comment by camelStyleUser** [comment]
millions must string

**Comment by CutePillow** [comment]
> wdym it can draw a "blast-drill-top"

![Screenshot_2024-08-21-14-58-14-749_com github tinylake mindustryX be](https://github.com/user-attachments/assets/211ea998-264a-4af4-a184-2517b00a578e)
![Screenshot_2024-08-21-14-58-18-845_com github tinylake mindustryX be](https://github.com/user-attachments/assets/0d74e3e0-4e46-40f0-b1f4-16d702d790a4)
If I write like the first picture,it can only draw like the second picture. It can't  draw the part of the drill bit in this example.

**Comment by ApsZoldat** [comment]
It should work if you pass `"blast-drill-top"` instead of `@blast-drill-top` as argument.

This instruction actually requires a string argument, when you use `@blast-drill` game just converts a block type to string by getting block's name. And there's no such block as `@blast-drill-top`, obviously. At least this is how i rememeber it should work, let's pretend i didn't write the code of markers myself and then forget how it actually works later.

**Comment by CutePillow** [comment]
> It should work if you pass `"blast-drill-top"` instead of `@blast-drill-top` as argument.
> 
> This instruction actually requires a string argument, when you use `@blast-drill` game just converts a block type to string by getting block's name. And there's no such block as `@blast-drill-top`, obviously. At least this is how i rememeber it should work, let's pretend i didn't write the code of markers myself and then forget how it actually works later.

Oh, I'm sorry to disturb you because of my misunderstanding.
