### ISSUE TITLE
oil use options

### ISSUE THREAD

**Issue by Deut644** [Anuken/Mindustry-Suggestions#5185]
### Describe the content or mechanics you are proposing.

oil in Mindustry almost useless, because plastanium, a coal centrifuge and turrets and that's it?! Please Add new ways to process oil, such as gasoline and kerosene, as well as new liquid fuel turrets. And also, for example, gasoline generators.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I said everything in the previous field 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
nah, oil doesn't need more usage for vanilla, it's a liquid resource on serpulo and gets an appropriate amount of usage for the type, if you want more usage then make a mod for it cause that would fit a mod more than vanilla

**Comment by Ryczypisk2** [comment]
i think oil could be used in power generation

**Comment by jehosula** [comment]
> i think oil could be used in power generation

yeah it already can, by turning it to coal then using steam generators

**Comment by Deut644** [comment]
I don't know how to make mods so I'll just have to dream about better oil
usage.
(I don't know English so, I used google translator)

вс, 25 авг. 2024 г., 22:47 jehosula ***@***.***>:

**Comment by jehosula** [comment]
learn modding, get someone to make it for you or keep dreaming
