### ISSUE TITLE
Force projector with infinite Hp (kinda)

### ISSUE THREAD

**Issue by KOCTOLOM** [Anuken/Mindustry-Suggestions#5187]
### Describe what you would like changed, and why.

By rebuilding the force projector you can reset it to max HP without any cooldown and practically free, it's can be very imbalanced. (In vanilla it's not very strong but with projectors from mods with high HP and cooldown it's overpowered.)

https://github.com/user-attachments/assets/bd22727c-41a8-41f6-93e4-fc38b7e2a2b6

### Describe the changes you want to propose. Include possible alternatives.

Maybe somehow save data of the HP of the shield and its cooling state, to prevent abuse.

**Comment by jehosula** [comment]
same thing can be done by building more force projectors, the solution is to make the hp when it's built 0 and it has to ramp up

**Comment by SomeonesShade** [comment]
https://github.com/Anuken/Mindustry/commit/8b2b5d4682afaa618efa8b47675f4daea977c1e3

nice
