### ISSUE TITLE
Directory's for maps and tags

### ISSUE THREAD

**Issue by thefsfc** [Anuken/Mindustry-Suggestions#5188]
### Describe the content or mechanics you are proposing.

when I saw https://github.com/Anuken/Mindustry-Suggestions/issues/5115
There was another idea, if you can sort the maps, it would be more convenient to have directories for them, because the number of maps grows a lot after a long time and it is difficult to update them, also add the tags

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Speed up (although we are in no hurry to get anywhere, or if someone is in a hurry to find maps...) access to the favorite maps of players, among the built-in maps 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
also you should be able maps should be sorted by most recently added/edited so you don't have to look for a map you just imported/made every time you exit, and would also allow easier looking at maps you didn't touch in a long time
