### ISSUE TITLE
An interplanetary accelerator.

### ISSUE THREAD

**Issue by X-2-0** [Anuken/Mindustry-Suggestions#5190]
### Describe the content or mechanics you are proposing.

Add functionality to the Interplanetary Accelerator.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

He will send resources to another planet in the amount of 15,000 (Not necessarily of the same kind).  It will be possible to select a sector for unloading resources. It can be built anywhere, and not just one piece.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
so, like launch pad but launches to erekir?
no, erekir should never have exports

**Comment by thefsfc** [comment]
Anuken made it as a placeholder. For the campaign, it's a technology that only can using Crux

**Comment by jehosula** [comment]
following the other guy's comment, back in v6 it was aquired by beating the final sector and filling it was what made you win (no other planet to launch to), then it was removed in v7 (current version) with erekir's introduction

**Comment by thefsfc** [comment]
> following the other guy's comment, back in v6 it was aquired by beating the final sector and filling it was what made you win (no other planet to launch to), then it was removed in v7 (current version) with erekir's introduction

Right

**Comment by X-2-0** [comment]
I mean, to send some resources from one planet to another and choose which sector will receive resources (the sector must already be captured so that it would be possible to choose it for this).

**Comment by X-2-0** [comment]
This will allow you to quickly get the resources that are available on both planets.

**Comment by jehosula** [comment]
no, it simply makes no sense, the 2 planets are too different, and this wouldn't really be useful considering erekir doesn't need much production for research

**Comment by X-2-0** [comment]
Research may be inexpensive, but it will take a long time to accumulate resources, and this way it will be much faster.

**Comment by jehosula** [comment]
> Research may be inexpensive, but it will take a long time to accumulate resources, and this way it will be much faster.

accumulate for WHAT? erekir doesn't have any actual resource sink for that, research is also super easy to afford

**Comment by X-2-0** [comment]
Even if you don't take research, you need to accumulate resources for rapid development. After all, when you already have an idea how to capture sectors, then it is no longer interesting to accumulate resources and you just want to capture the sector faster, and this is not possible without quickly replenishing resources.

**Comment by jehosula** [comment]
> Even if you don't take research, you need to accumulate resources for rapid development. After all, when you already have an idea how to capture sectors, then it is no longer interesting to accumulate resources and you just want to capture the sector faster, and this is not possible without quickly replenishing resources.

just make more factories smh, having an export hub on erekir will simply allow too much BS, also it is possible to do rapid development and resource replinishment without an export hub if you are good, and this is supposed to help AFTER you have pretty much captured the sector already, so you wouldn't be that bad

**Comment by X-2-0** [comment]
> > Even if you don't take research, you need to accumulate resources for rapid development. After all, when you already have an idea how to capture sectors, then it is no longer interesting to accumulate resources and you just want to capture the sector faster, and this is not possible without quickly replenishing resources.
> 
> just make more factories smh, having an export hub on erekir will simply allow too much BS, also it is possible to do rapid development and resource replinishment without an export hub if you are good, and this is supposed to help AFTER you have pretty much captured the sector already, so you wouldn't be that bad

This method is good for passing sectors, if you are not tired at all (extraction of resources and their production). And by sending resources between planets to solve this problem:
* When all the research has been studied and you just want to capture the remaining sectors;
* When, on the second planet, you do not want to complete the entire cycle of passage entirely, since on the first planet this was quite enough for you.

**Comment by jehosula** [comment]
> This method is good for passing sectors, if you are not tired at all (extraction of resources and their production). And by sending resources between planets to solve this problem:
> 
> * When all the research has been studied and you just want to capture the remaining sectors;
> * When, on the second planet, you do not want to complete the entire cycle of passage entirely, since on the first planet this was quite enough for you.

if you have all the research then you are on origin in erekir, that planet does not have numbered sectors or anything to sink time in or something that would actually justify an ecport hub for erekir, this isn't serpulo, your point is quite confusing tbh

**Comment by X-2-0** [comment]
> if you have all the research then you are on origin in erekir, that planet does not have numbered sectors or anything to sink time in or something that would actually justify an ecport hub for erekir, this isn't serpulo, your point is quite confusing tbh

I am not saying that resources should be sent to a particular planet. I meant generally moving between planets, both to one and the other. This is the essence of adding this game mechanics.

**Comment by jehosula** [comment]
> I am not saying that resources should be sent to a particular planet. I meant generally moving between planets, both to one and the other. This is the essence of adding this game mechanics.

but well you should account for serpulo to erekir, which would completely ruin erekir

**Comment by X-2-0** [comment]
> but well you should account for serpulo to erekir, which would completely ruin erekir

Why? Wouldn't that just speed up the passage as much as possible, because even if it gets resources that it doesn't have, it won't affect research. The only thing that can happen is to open some research ahead of time (or is it enough to get these materials on another planet?).

**Comment by jehosula** [comment]
> Why? Wouldn't that just speed up the passage as much as possible, because even if it gets resources that it doesn't have, it won't affect research. The only thing that can happen is to open some research ahead of time (or is it enough to get these materials on another planet?).

it would ruin the difficulty of erekir like it already does with serpulo maps that weren't balanced around exports

**Comment by X-2-0** [comment]
> it would ruin the difficulty of erekir like it already does with serpulo maps that weren't balanced around exports

But here it is worth considering the style of passing the game by different players:
* Players who are not interested in simplifications - just ignore this mechanic, the same applies to transferring resources to another sector.
* For players who need to find an easier way, this will be the best thing, especially in sectors of higher difficulty.

As a result, this mechanic is optional and its effect on progress depends mostly on the player.

**Comment by jehosula** [comment]
> But here it is worth considering the style of passing the game by different players:
> 
> * Players who are not interested in simplifications - just ignore this mechanic, the same applies to transferring resources to another sector.
> * For players who need to find an easier way, this will be the best thing, especially in sectors of higher difficulty.
> 
> As a result, this mechanic is optional and its effect on progress depends mostly on the player.

erekir was never meant to give you freedom to make it easy and cheese it, it was made to be linear, these same arguments can be used to justify item sources in campaign my guy, easy mode should be an explicit choice, not a do stuff in a separate campaign to get it and for players that need an easier way, just quit a linear campaign should not include such a detour for an easy mode

**Comment by X-2-0** [comment]
> erekir was never meant to give you freedom to make it easy and cheese it, it was made to be linear, these same arguments can be used to justify item sources in campaign my guy, easy mode should be an explicit choice, not a do stuff in a separate campaign to get it and for players that need an easier way, just quit a linear campaign should not include such a detour for an easy mode

In this case, there should be no block using this mechanics. Although it is available at the end of the storyline (I don't remember exactly when access to the corresponding sector opens). The remaining sectors are needed, in fact, to retain the player's interest more than to accumulate and transfer resources. 

In this case, you can do this: capture the corresponding sectors on both planets and after that you can transfer resources, because off-plot sectors are optional for passage. 

Thus, the plot sectors will be completed as planned, and the rest of the sectors will be wanted as a player, because they will not give new content and will be needed only for the sake of resources.

**Comment by jehosula** [comment]
> In this case, there should be no block using this mechanics. Although it is available at the end of the storyline (I don't remember exactly when access to the corresponding sector opens). The remaining sectors are needed, in fact, to retain the player's interest more than to accumulate and transfer resources.
> 
> In this case, you can do this: capture the corresponding sectors on both planets and after that you can transfer resources, because off-plot sectors are optional for passage.
> 
> Thus, the plot sectors will be completed as planned, and the rest of the sectors will be wanted as a player, because they will not give new content and will be needed only for the sake of resources.

erekir launch pads could be justified for numbered sectors but transporting resources across both planets maybe not, just keep the campaigns seperate

**Comment by X-2-0** [comment]
> erekir launch pads could be justified for numbered sectors but transporting resources across both planets maybe not, just keep the campaigns seperate

This makes sense, because there is nothing but resources in the numbered sectors. It would make sense to separate the campaigns if the planets did not have common resources (in this case, the transfer of resources would be completely meaningless) or were in different solar systems (it would make sense because of the distance).  

Now there is nothing in the game that would prevent you from adding this, the location of the planets in the same solar system. The close distance between them, the shared resources, all this suggests the idea, and why not add transportation between them.

**Comment by jehosula** [comment]
> This makes sense, because there is nothing but resources in the numbered sectors. It would make sense to separate the campaigns if the planets did not have common resources (in this case, the transfer of resources would be completely meaningless) or were in different solar systems (it would make sense because of the distance).
> 
> Now there is nothing in the game that would prevent you from adding this, the location of the planets in the same solar system. The close distance between them, the shared resources, all this suggests the idea, and why not add transportation between them.

what about the actual gameplay and progression? the campaigns were never supposed to be intertwined in any way

**Comment by X-2-0** [comment]
> what about the actual gameplay and progression? the campaigns were never supposed to be intertwined in any way

It doesn't change the gameplay much. It's just a strong acceleration of development. If research were also transferred when sending resources, then yes, it would break the company, and so it replaces long development (capturing side sectors for the sake of resources, production and sending resources to other sectors) with fast (rapid development on the sector and its capture, rapid receipt of research - For example, on Serpulo).
(I don't know how it is on Erekir - I haven't passed it yet).

**Comment by jehosula** [comment]
> It doesn't change the gameplay much. It's just a strong acceleration of development. If research were also transferred when sending resources, then yes, it would break the company, and so it replaces long development (capturing side sectors for the sake of resources, production and sending resources to other sectors) with fast (rapid development on the sector and its capture, rapid receipt of research - For example, on Serpulo). (I don't know how it is on Erekir - I haven't passed it yet).

on erekir the only actually useful way would be to send the resources to sectors you are capturing cause research is easy there, also the campaigns are supposed to be seperate not one bigger campaign

**Comment by X-2-0** [comment]
> on erekir the only actually useful way would be to send the resources to sectors you are capturing cause research is easy there, also the campaigns are supposed to be seperate not one bigger campaign

Why should they be separate? isn't it better to give the player the opportunity to choose the way of passing - to go through first or use some resources (It is worth considering the unique resources used both for research and for various buildings).

Given the uniqueness of the resources of each campaign, it can be concluded that the interplanetary transfer of resources does not completely replace the process of resource extraction, otherwise it would make one campaign a continuation of another and then it would be meaningless.

**Comment by jehosula** [comment]
> Why should they be separate? isn't it better to give the player the opportunity to choose the way of passing - to go through first or use some resources (It is worth considering the unique resources used both for research and for various buildings).
> 
> Given the uniqueness of the resources of each campaign, it can be concluded that the interplanetary transfer of resources does not completely replace the process of resource extraction, otherwise it would make one campaign a continuation of another and then it would be meaningless.

they should be seperate so that there is an actual choice between which one that doesn't lead to an "optimal path" also both planets share too many resources but their values are different, and also the interplanetary transfer would cover a lot of items and skip most of the resource collection, it would make the planets not 100% a continuation but still significant differences

**Comment by X-2-0** [comment]
> they should be seperate so that there is an actual choice between which one that doesn't lead to an "optimal path" also both planets share too many resources but their values are different, and also the interplanetary transfer would cover a lot of items and skip most of the resource collection, it would make the planets not 100% a continuation but still significant differences

There is an optimal way on every planet. The transfer of resources would change it for every planet. Yes, there are a lot of items, but it's boring to mine and produce them, and when it comes to capturing all sectors, it becomes extremely boring. At least there is a possibility of intersectoral transfer of resources, otherwise the game would become extremely boring. At least the battles on the sectors are different and this somehow saves the day. And this applies to every planet. I do not know how to make resource collection interesting, so I suggest that we still give the functionality to that structure to send resources to the planets. Skipping most of this stage of development will brighten up the gameplay. Otherwise, the game is quite normal - the landscape and the battles.

**Comment by jehosula** [comment]
> There is an optimal way on every planet. The transfer of resources would change it for every planet. Yes, there are a lot of items, but it's boring to mine and produce them, and when it comes to capturing all sectors, it becomes extremely boring. At least there is a possibility of intersectoral transfer of resources, otherwise the game would become extremely boring. At least the battles on the sectors are different and this somehow saves the day. And this applies to every planet. I do not know how to make resource collection interesting, so I suggest that we still give the functionality to that structure to send resources to the planets. Skipping most of this stage of development will brighten up the gameplay. Otherwise, the game is quite normal - the landscape and the battles.

on serpulo yes there is an optimal path but for erekir there isn't enough choice to really make much of a difference this suggestion would make an optimal path between both planets that were intended to be seperate, also resouce collection should be interesting for someone who actually enjoys the game and 100% completion is supposed to be only for diehard fans, not the average mindustry enjoyer

**Comment by X-2-0** [comment]
> on serpulo yes there is an optimal path but for erekir there isn't enough choice to really make much of a difference this suggestion would make an optimal path between both planets that were intended to be seperate, also resouce collection should be interesting for someone who actually enjoys the game and 100% completion is supposed to be only for diehard fans, not the average mindustry enjoyer

But there is no problem here - who needs to make progress difficult will not use the existing opportunity to send resources. In addition, it is possible to install mods. The function of transferring resources on a planetary scale will have certain limitations, which will result in a kind of balance. The functionality with mods does not have a balance at all - resources and units out of thin air, adjusting various parameters, adding structures to existing campaigns... In general, it is absolutely uncontrollable and it is generally surprising that it exists at all. Therefore, this transfer of resources may well fit into the game without breaking the balance, you just need to set it up. The same pads have their own limitations, which is why they do not greatly affect the game. 

In general, the idea with this mechanics appeared not only because of the lack of functional structure. When I captured a whole cluster in the side sectors of the highest complexity, I realized that it was not interesting to play them like that at all and opened these very mods that gave an absolute advantage, it's a pity that I did not find a mod that allows you to capture a sector at the touch of a button. 
That's the problem that the game itself gives you such a choice of passing:
*Play fair (using all the built-in tools to facilitate the process; Ignore heavily facilitating tools to complicate the process);
*Play dishonestly (Download some cheats).

In capturing sectors, except for the main task (to survive waves of enemies or destroy enemy bases) there are no conditions, for example:
*Blocking of certain structures - it is impossible to build them before the capture of the sector, although they have been studied in research;
*Without extraction of certain resources (It is impossible to make one or another resource; for example, to extract coal);
*Destroy the enemy's base using certain units (you can also limit the number);
*Destroy the enemy's base by surviving a certain number of waves.
So there will be at least some interest in playing on them. And given their specifics, influence the intersectoral and interplanetary transfer of resources so that they do not circumvent the rules of the sectors. In this case, they will be limited and balanced.

**Comment by jehosula** [comment]
> But there is no problem here - who needs to make progress difficult will not use the existing opportunity to send resources. In addition, it is possible to install mods. The function of transferring resources on a planetary scale will have certain limitations, which will result in a kind of balance. The functionality with mods does not have a balance at all - resources and units out of thin air, adjusting various parameters, adding structures to existing campaigns... In general, it is absolutely uncontrollable and it is generally surprising that it exists at all. Therefore, this transfer of resources may well fit into the game without breaking the balance, you just need to set it up. The same pads have their own limitations, which is why they do not greatly affect the game.
> 
> In general, the idea with this mechanics appeared not only because of the lack of functional structure. When I captured a whole cluster in the side sectors of the highest complexity, I realized that it was not interesting to play them like that at all and opened these very mods that gave an absolute advantage, it's a pity that I did not find a mod that allows you to capture a sector at the touch of a button. That's the problem that the game itself gives you such a choice of passing: *Play fair (using all the built-in tools to facilitate the process; Ignore heavily facilitating tools to complicate the process); *Play dishonestly (Download some cheats).
> 
> In capturing sectors, except for the main task (to survive waves of enemies or destroy enemy bases) there are no conditions, for example: *Blocking of certain structures - it is impossible to build them before the capture of the sector, although they have been studied in research; *Without extraction of certain resources (It is impossible to make one or another resource; for example, to extract coal); *Destroy the enemy's base using certain units (you can also limit the number); *Destroy the enemy's base by surviving a certain number of waves. So there will be at least some interest in playing on them. And given their specifics, influence the intersectoral and interplanetary transfer of resources so that they do not circumvent the rules of the sectors. In this case, they will be limited and balanced.

exports just skip a big part of what you do in a sector and the only reason they are in serpulo is because it's too late to remove them now, just setup some stuff and then you delete half of what you do in a sector, it simply breaks the balance, especially for erekir, ruins named sectors and numbered ones are for those willing to dump all their time, this suggestion would only ruin the difficulty for whichever planet is second and numbered sectors just become easier to 100% which makes the achievement easier to get and show off eventually

**Comment by X-2-0** [comment]
> exports just skip a big part of what you do in a sector and the only reason they are in serpulo is because it's too late to remove them now, just setup some stuff and then you delete half of what you do in a sector, it simply breaks the balance, especially for erekir, ruins named sectors and numbered ones are for those willing to dump all their time, this suggestion would only ruin the difficulty for whichever planet is second and numbered sectors just become easier to 100% which makes the achievement easier to get and show off eventually

It is really too late to delete, but it is also impossible to leave it in this form, and in this case it remains only to add the appropriate functionality. The previously mentioned regimes gave at least some interest to the sectors, otherwise these side ones are not interesting at all. The only problem with Ericir is that there are few sectors, apparently there were no ideas how to implement them, most likely this will be fixed in the future and then such a transfer of resources will not be critical (in this case there will be a lot of resources on both planets and the consequences of the transfer of resources will be the same for them). Numbered sectors are just an addition to the main ones and therefore there is no point in limiting them in any way. Not giving the mechanics of transferring resources until all the main sectors (both on one and on another planet) are captured will be the best solution. In this case, the balance will not be disturbed. 

In embedded planets, unnamed sectors are only needed to receive and send resources to the main sectors and for nothing else. So what is the point of limiting them, if you can not touch them at all. Perhaps there is something in the mod planets that will make sense to capture them (for example, secret research; some faults on sectors - when capturing such sectors, access to a layer of sectors inside the planet will be opened, which may be plot or just resource).

**Comment by X-2-0** [comment]
> i half agree, you can certainly leave them in this form, but the best solution is to make them unlock after the main sectors cause numbered ones are not important to balancing, but at that point just add erekir launch pads unlocked with origin and it should be good, once again interplanetary transfer would ruin the balance of both planets unless it's after the final sector in which case it would be irrelevant

Why does it not matter if it is available after completing all the story sectors on both planets, given that the numbered sectors on both planets are needed only for resources. In this case, what is the difference between sending or extracting resources, if in both cases you can get a lot of resources. In addition, shipping does not completely replace the mining process due to the unique resources. Before this mechanic is available, the player will study everything that the developer intended.

**Comment by jehosula** [comment]
> Why does it not matter if it is available after completing all the story sectors on both planets, given that the numbered sectors on both planets are needed only for resources. In this case, what is the difference between sending or extracting resources, if in both cases you can get a lot of resources. In addition, shipping does not completely replace the mining process due to the unique resources. Before this mechanic is available, the player will study everything that the developer intended.

it matters that it's after the main sectors cause it means you don't ruin the balance of those, and also shipping not only lets you get FAR more resources MUCH faster but it also almost entirely replaces mining if you have enough, it should be available as late as possible to not break named sector balance

**Comment by X-2-0** [comment]
> it matters that it's after the main sectors cause it means you don't ruin the balance of those, and also shipping not only lets you get FAR more resources MUCH faster but it also almost entirely replaces mining if you have enough, it should be available as late as possible to not break named sector balance

The fact that it should open after the named sectors on the two planets has already been discussed. The fact that numbered sectors are optional and you can go through them any way you want was also discussed. We also discussed how to add this mechanic without major changes. 

This topic seems to have been discussed from all sides and it's time to draw a conclusion. And then the further the more this topic is retold in the same way, but in other words.

I think that in the end, this mechanic can be added if certain conditions are met.

**Comment by jehosula** [comment]
> The fact that it should open after the named sectors on the two planets has already been discussed. The fact that numbered sectors are optional and you can go through them any way you want was also discussed. We also discussed how to add this mechanic without major changes.
> 
> This topic seems to have been discussed from all sides and it's time to draw a conclusion. And then the further the more this topic is retold in the same way, but in other words.
> 
> I think that in the end, this mechanic can be added if certain conditions are met.

the only thing that can reasonably be added is erekir launch pad after origin, and even that i don't support, also check the suggestion on discord, everyone's straight up mocking your idea

**Comment by X-2-0** [comment]
> the only thing that can reasonably be added is erekir launch pad after origin, and even that i don't support, also check the suggestion on discord, everyone's straight up mocking your idea

Well, I'll check what they say.

**Comment by X-2-0** [comment]
![image](https://github.com/user-attachments/assets/af8de669-e2b4-4a61-a821-4eee2cc55f4c)

**Comment by X-2-0** [comment]
> the only thing that can reasonably be added is erekir launch pad after origin, and even that i don't support, also check the suggestion on discord, everyone's straight up mocking your idea

No one else responded to this proposal, apparently no one is interested in this topic at all.

**Comment by jehosula** [comment]
> No one else responded to this proposal, apparently no one is interested in this topic at all.

just let this suggestion go stale

**Comment by X-2-0** [comment]
> just let this suggestion go stale

Well, let's leave this proposal because there are only two people in this conversation, and to solve the problem of voting for or against, it is necessary that at least three participate.
