### ISSUE TITLE
qick sellect menu 

### ISSUE THREAD

**Issue by Ryczypisk2** [Anuken/Mindustry-Suggestions#5191]
### Describe what you would like changed, and why.

i think mindustry could use sellect all army button ald sellect all unit factories button (for setting all buildings rally to one point without having to look arround the entire map for them)

### Describe the changes you want to propose. Include possible alternatives.

it would made for esier unit managment

**Comment by jehosula** [comment]
this would only be useful for mobile cause g and h exist on pc
