### ISSUE TITLE
Vents better placement when there is more of 3*3

### ISSUE THREAD

**Issue by 00Alxe00** [Anuken/Mindustry-Suggestions#5196]
### Describe the content or mechanics you are proposing.

When in the editor you put **vents,** for example you put a 5 by 5 square of vents, It looks horrible in the game.

My idea is that **vents** can fuse to make bigger vents*.

* It will only work if the vents are in a square shape.
* It won't affect any size of electric generator.
* Bigger vents will improve the vents generator production, energy and water.
* If the vents are in a square, for example 10 by 10 or more, it can cause that the vents generator start to take damage from the overwork.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will improve the game by making vents less horrible in the design when not placed in the 3*3 square shape, making energy production better and being more useful.

Please read this and think about this, If you need more information you only need to put in the map editor a square of vents of 4 by 4 or 5 by 5 you don't need more than that.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Mythril382** [comment]
Bitmasked vents would look extremely wacky. (I'm interested in seeing it.)

**Comment by Mythril382** [comment]
(No. This doesn't mean I'm interested in the suggestion itself.)
