### ISSUE TITLE
Set Launchpad destination from Global Map View

### ISSUE THREAD

**Issue by TSCarterJr** [Anuken/Mindustry-Suggestions#5197]
### Describe the content or mechanics you are proposing.

Since all launchpads on a given tile all go to the same location.

Instead of clicking into the map, and setting the destination. It would be **nice** if we can be at our desired base. Go to the planet view, find the base we want to receive materials from, and then assign it from that view, without having to switch to that base to do so.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would be a QOL improvement. Saves a few clicks / actions. Allows for quicker assignment.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
could potentially reduce the value of an export hub but tbh i don't see why that would be much of a problem

**Comment by TSCarterJr** [comment]
> could potentially reduce the value of an export hub but tbh i don't see why that would be much of a problem

Would it though? You'd still be transporting the majority of your goods to a singular planet, but with this implemented, you'd adjust one bases settings.

Clarification: This is a per base setting, not a per planet setting.

**Comment by jehosula** [comment]
> Would it though? You'd still be transporting the majority of your goods to a singular planet, but with this implemented, you'd adjust one bases settings.
> 
> Clarification: This is a per base setting, not a per planet setting.

would make it much easier to adjust exports and an export hub is used to do exactly that, make exports easy to adjust

**Comment by TSCarterJr** [comment]
When trying to send resources to a new spot.
You have to leave the new spot... go to your hub. Then select the new spot... then go back to the new spot that you're actively working on.

This idea would be so...

You transport to the new spot... you can open up the planetary map. Select your hub, but WITHOUT going to it, you can just set the launch pad location to the new one.

As I mentioned, it's a QOL feature, that just saves you a few extra steps.

**Comment by jehosula** [comment]
> When trying to send resources to a new spot. You have to leave the new spot... go to your hub. Then select the new spot... then go back to the new spot that you're actively working on.
> 
> This idea would be so...
> 
> You transport to the new spot... you can open up the planetary map. Select your hub, but WITHOUT going to it, you can just set the launch pad location to the new one.
> 
> As I mentioned, it's a QOL feature, that just saves you a few extra steps.

yes, would make an export hub less valuable cause the main use for it is to make managing a whole planet's exports as simple as managing one sector's exports
