### ISSUE TITLE
Alarm block

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5198]
### Describe the content or mechanics you are proposing.

I'm not going to lie, this may seem useless, but i think it would actually be really nice to have a block that makes loud noises and flashes the chosen colour of light when it takes damage. This way some players (me included) will have a higher chance of surviving hard sectors while focusing on something far from the frontline.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

So, the block will attract the players attention by playing loud sounds and/or flashing a chosen colour of light (red by default). It will also call in support units that are set to repair/rebuild.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Glartemoon** [comment]
just use betamindy mod
