### ISSUE TITLE
Translate the game to the end

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5199]
### Describe what you would like changed, and why.

I saw that most of Erekir sectors' descriptions and other stuff wasn't translated correctly (at least in polish and hungarian; i didn't check other languages). In most of Erekir sectors the polish description says "trwają prace nad opisem", which stands for "the description is in progress".

### Describe the changes you want to propose. Include possible alternatives.

I said everything in the first part

**Comment by jehosula** [comment]
then become a translator and do it yourself

**Comment by itcannotbe** [comment]
[If notice something is not translated or mistranslated, you can become a translator today, by clicking this link.](https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md)
