### ISSUE TITLE
Make own units/buildings visible under trees

### ISSUE THREAD

**Issue by LeComm** [Anuken/Mindustry-Suggestions#520]
V6.0 added really cool animated trees which look great.
However, if I build something beneath a tree, it is hidden under it, which makes them very inconvenient. I suggest to make own buildings and units under a tree drawn in a semi-transparent manner over it so it is visible what is going on there. At the same time, enemy stuff should be hidden to enable ambush mechanics.

A sketch outlining the idea:

![image](https://user-images.githubusercontent.com/10799531/93458517-b0281100-f8e0-11ea-92c3-1e2f06d44df1.png)

**Comment by SonAzcuLost** [comment]
I have an idea, you could put the trees and things like in a first layer and what would be the constructions in a second layer and when a construction is in a first layer (like the turrets in the tree) there is an option to see only the second layer (the constructions

**Comment by SonAzcuLost** [comment]
because what you propose to see, a transparent medium would not look very good visually instead if a way is enabled so that with a key you can see a layer it would be better

**Comment by SonAzcuLost** [comment]
you like that idea?

**Comment by LeComm** [comment]
no
