### ISSUE TITLE
Overdriver and Mend Dome

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5203]
### Describe the content or mechanics you are proposing.

We already have Menders, Mend Projectors, Overdeive Projectors and Overdrive Domes, so i suggest adding a cheap and small Overdriver and and absolute overkill of a Mend Dome.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Overdriver will have same range as Mender and it can boost the structures by 25-30%, while a Mend Dome will have same range as Overdrive Dome.
The Overdriver is just an extremely cheap source if weak speedup (it is probably useless) and the Mend Dome can be used to heal large areas of low-health structures, like conveyors or generators

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
we really don't need either, overdriver would have to be tita tech and would be silly as we don't need overdrive there, and mend dome is also not needed as you can phase boost mend projectors and overdrive them
