### ISSUE TITLE
Infinite campaign mode

### ISSUE THREAD

**Issue by IOKAA** [Anuken/Mindustry-Suggestions#5204]
### Describe the content or mechanics you are proposing.

(Im gonna be more serius than the other time i write that wār crime in bugs report)
Nobody thinks about has a gamemode from play in endless waves on campaign maps, later of capture all sectors and survive many waves in the custom maps section, taking a lot of time make a well maded map and even more if are a minigames
So u propose an endless waves campaign mode, with all campaign maps of serpulo and erekir, with the same features of old v5 campaign mode

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Idk, is the same of V5 but has maps of both planets
With this, we can test strats in all campaign maps and have that experience of v5
This adds an new form of play mindustry and have a form of understand the game in other context

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
you can download the maps and play in custom game for that, also implementation could be done in so many ways that you didn't describe enough
https://github.com/Anuken/Mindustry/blob/master/core/assets/maps/nuclearComplex.msav

**Comment by IOKAA** [comment]
Ehem,  as.somehow i cant download any map beacause each time i try import a map gives me error, WHY?

**Comment by jehosula** [comment]
maybe you need BE
https://github.com/Anuken/MindustryBuilds/releases?page=1
