### ISSUE TITLE
Why SALVO turret is the only turret have mechanism animation in serpulo

### ISSUE THREAD

**Issue by Absolutan115** [Anuken/Mindustry-Suggestions#5206]
### Describe what you would like changed, and why.

.

### Describe the changes you want to propose. Include possible alternatives.

?

**Comment by jehosula** [comment]
# **??????**

**Comment by Kenny-Ofc** [comment]
this guy probably playin the old version

**Comment by Absolutan115** [comment]
> this guy probably playin the old version

Nah I play 146

**Comment by jehosula** [comment]
> Nah I play 146

but what are you even suggesting?

**Comment by Absolutan115** [comment]
> > Nah I play 146
> 
> but what are you even suggesting?

I just want showing confusion why only SALVO has mechanism animation while other turret only have recoil animation in serpulo. This thing make me confused as hell for few years, No issue.

**Comment by jehosula** [comment]
> I just want showing confusion why only SALVO has mechanism animation while other turret only have recoil animation in serpulo. This thing make me confused as hell for few years, No issue.

if you are not suggesting to fix it then why is this a SUGGESTION post, just go about it in the discord server

**Comment by Absolutan115** [comment]
Yeah my bad atleast, there some activity on this site. I close it now
