### ISSUE TITLE
Way to let non-host edit world processors

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry-Suggestions#5207]
### Describe the content or mechanics you are proposing.

With the new addition of editing wproc when not in editor ut would be nice if there was a rule for non-host players to edit and save the world processor

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would allow players to collaborate in creating a map with world processors, as we can already modify all in-game tiles in edit-ingame

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by broganeuquoixe** [comment]
This is now possible using the new `alloweditworldprocessors` rule:
https://github.com/Anuken/Mindustry/commit/acbd8bb190839a35349922bf3e189b43b4563d85
Update to the [latest Bleeding Edge release](https://github.com/Anuken/MindustryBuilds/releases/latest) to test it out.
