### ISSUE TITLE
Neoplasm & Steam update

### ISSUE THREAD

**Issue by strabbygamer** [Anuken/Mindustry-Suggestions#5209]
### Describe the content or mechanics you are proposing.

Add the content from v8 and add steampunk content (e.g. trains, steam, aircraft carrier units, etc.)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

IDK

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by strabbygamer** [comment]
Comment 👍 if yes or 👎 if no

**Comment by Kenny-Ofc** [comment]
look over Diacord.

**Comment by camelStyleUser** [comment]
killer couldnt even think of how it could improve the game

**Comment by camelStyleUser** [comment]
not even a "it adds more content"(which is lame but something)
