### ISSUE TITLE
Add a payload conveyor dock

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#521]
Add a payload conveyor dock.
Units can enter it to board other payload conveyors.

You could have more control over how to do upgrades. If you build a unit you can choose to upgrade it or send it out more easily.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by here-be-username** [comment]
Yes please! Right now, as soon as you send a unit out of a payload conveyor, there's no way to put it back. Accidentally filled up the horizon unitcap and can't build any more to upgrade? What can you do about that? About the only thing you can do is try and fly some into the enemy drop point or into their defenses, but that's a waste, and is a bit strange.

**Comment by rmperkow** [comment]
In 106, units can enter payload conveyors anywhere.

**Comment by rmperkow** [comment]
They cannot enter reconstructors if they leave and come back.

**Comment by rmperkow** [comment]
[Added in a different way.](https://discord.com/channels/391020510269669376/513178557653188609/832747008678297600)
