### ISSUE TITLE
Stop Launch pad when targeted sector is lost

### ISSUE THREAD

**Issue by mahdoosh1** [Anuken/Mindustry-Suggestions#5211]
### Describe what you would like changed, and why.

when launch pad is targeted to a sector and you loose that sector, the launch pad moves all the items to "None(sun)" which is very wasteful

### Describe the changes you want to propose. Include possible alternatives.

its better to just keep items in in as temporary storage instead of deleting it all. i lost around 10k of surge alloy because i didnt know it was all being wasted

**Comment by TSCarterJr** [comment]
I agree with this.

It should go into a paused state, so no resources are lost.

**Comment by TSCarterJr** [comment]
Or at minimum, add some automation aspects to determine if the planet is under our control, so we can add logic behind it. But the 'easier' solution here is to pause it.
