### ISSUE TITLE
screen shake world logic instruction

### ISSUE THREAD

**Issue by alphy228** [Anuken/Mindustry-Suggestions#5213]
### Describe the content or mechanics you are proposing.

screenshake instruction
parameters:
Power - screenshake power
local(true/false) - makes screen shake less powerful the farther away you are from source
sourceX - screenshake source x
sourceY - screenshake source y
Range - range at which local screenshake can be seen

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

will heavily improve world logic effects for volcanic eruption,large explosions,etc

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JasonP01** [comment]
Me with screenshake disables 😎

**Comment by Absolutan115** [comment]
> Me with screenshake disabled 😎

Same asw
