### ISSUE TITLE
Purple Air, Purple Naval, New units suggestion

### ISSUE THREAD

**Issue by Noahblast20** [Anuken/Mindustry-Suggestions#5215]
### Describe the content or mechanics you are proposing.

A purple Air Unit and Purple Water unit line to round out the serpulo unit groups would be a nice addition to round out the different factories.
Purple Air: [Dive bombing kamikaze based air unit, rather slow for it's tier, can't hurt air units, but will explode in a similar way to crawler in terms of AI], [Electrically charged spike based unit that fires once, grabs some energy from player power supply, then goes back to fire again, possibly stunning target?], [Resource firing unit that picks up selected unit from targeted location, then moves toward the nearest enemy structure to the pickup location, or, if no enemy structure close enough to the input, the player's core (might be fixed in v8 with new unit ai, so might just target a reload location and set target is the target of the attack)], [unit that picks up objects up to 1 2x2 turret in size, and carries them and other resources (including power), giving it weapons that cost internal resources based on what is carried (shown on top? turrets are shown on unit without base?))], [same abilities as t3 and t4, but has higher storage, higher max carry object size (4x4?)] or some other ideas
Purple naval unit line: [leech unit that has a timed life (also dies if unit it's attached to dies), deals percentage based damage to targets it's attached to], [fires a homing torpedo at enemy naval units, torpedo can also hit nearby units with explosion], [hooks onto ship and rams into it, speeding up in the process, more speed=more damage, has electrified taser that only targets really close units], [hooks multiple nearby ships towards itself, shocks nearby naval units, has extra canons with slightly low turn speed but high attack rate], [can hook any unit to drag it towards itself and to a watery grave, massive canon that shoots a really low life projectile that deals a stupid amount of damage that also has a really long recharge]

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this idea would overall add a lot more variety to naval and arial combat, adding a resource based unit line, a modular unit, more kamikaze units, and more variety when it comes to naval combat. also, I just think a we need more electricity/fire based things in mindustry. the units proposed are only possible ideas for the units. all could be completely changed, but they're still cool ideas anyways. finally, groups of three units lines for each factory are cool and would round all three factories out.

not sure if the t4 and t5 air units counts as merged blocks, If so, then they could just be able to hold and shoot out 1x1blocks/t1 units and 2x2/t2 units at things respectively.

if this is also merged behavior, Idk what I'd suggest in it's place...

personally I like the purple naval unit line idea a lot more than the purple air one... but I don't really care if they actually get added.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
we already have too many unit lines, balancing between up to 7 at once for a tier is a nightmare

**Comment by Noahblast20** [comment]
> we already have too many unit lines, balancing between up to 7 at once for a tier is a nightmare

counterargument. naval combat is already situational, and the naval unit line is just based on naval combat, so not as big of a deal for it specifically. the air line idea I had is kinda hard to balance though...

**Comment by jehosula** [comment]
> counterargument. naval combat is already situational, so it is easier to balance, and ground units don't interact with it usually, and the naval unit line is just based on naval combat, so not as big of a deal for it specifically. the air line idea I had is kinda hard to balance though... as it needs balancing based on both naval combat and ground combat.

naval combat is situational because most maps don't have enough water, more unit types would only cause more bloat for a niche fighting method, and also like i said 7 lines is too much to balance with the units having to all be viable, also 7 lines is way more than enough for the planet 3 ground units per tier, 2 air units per tier and 2 naval units per tier is good enough, adding more lines would mean that they have to keep even more uniqueness in roles and it's already kinda tough with what we have now, my argument is that it's unnecessary bloat that will make balancing even harder than it already is
also actually reading the ideas and they seem too gimmicky

**Comment by Noahblast20** [comment]
> > counterargument. naval combat is already situational, so it is easier to balance, and ground units don't interact with it usually, and the naval unit line is just based on naval combat, so not as big of a deal for it specifically. the air line idea I had is kinda hard to balance though... as it needs balancing based on both naval combat and ground combat.
> 
> naval combat is situational because most maps don't have enough water, more unit types would only cause more bloat for a niche fighting method, and also like i said 7 lines is too much to balance with the units having to all be viable, also 7 lines is way more than enough for the planet 3 ground units per tier, 2 air units per tier and 2 naval units per tier is good enough, adding more lines would mean that they have to keep even more uniqueness in roles and it's already kinda tough with what we have now, my argument is that it's unnecessary bloat that will make balancing even harder than it already is also actually reading the ideas and they seem too gimmicky

(last statement)you're telling me you didn't read the actual suggestion before making both comments? dude. 

(on naval combat)naval combat is cool, and currently doesn't feel like it has enough it. 

(already a lot of units)True, 7 unit lines is enough, why don't we just cut it down to six then? why not 5? that would be easier to balance.  but I think having so much similarity between air units and naval units while ground units are so unique is boring and sad.

(too difficult to make unique)look me in the eyes and tell me how all of the units I suggested weren't unique and too gimmicky at the same time again.

(too gimmicky)both gimmicks are simple ones. shoot different materials based on what's in inventory, and get close to other naval units and kill them. neither are too gimmicky or even more gimmicky than 90% of what's on erekir, and people still love erekir (me included.)

**Comment by jehosula** [comment]
> (last statement)you're telling me you didn't read the actual suggestion before making both comments? dude.
> 
> (on naval combat)naval combat is cool, and currently doesn't feel like it has enough it.
> 
> (already a lot of units)True, 7 unit lines is enough, why don't we just cut it down to six then? why not 5? that would be easier to balance. but I think having so much similarity between air units and naval units while ground units are so unique is boring and sad.
> 
> (too difficult to make unique)look me in the eyes and tell me how all of the units I suggested weren't unique and were too gimmicky at the same time again.
> 
> (too gimmicky)both gimmicks are simple ones. shoot different materials based on what's in inventory, and get close to other naval units and kill them. neither are too gimmicky or even more gimmicky than 90% of what's on erekir, and people still love erekir (me included.)

1 i didn't even have to read them at first cause more unit lines is just a bad idea also i did read them when making the second comment
2 they just are, using resources from the main base? that needs a lot of setup to even use and also leeching off other units is very gimmicky cause it needs other units to work at all
3 erekir does not really have too much gimmicky units
4 it's simply too late to actually remove unit lines after they have been added
also current naval units can just be made more unique or add some other units to the naval combat, we don't need more unit lines

**Comment by Noahblast20** [comment]
> > (last statement)you're telling me you didn't read the actual suggestion before making both comments? dude.
> > (on naval combat)naval combat is cool, and currently doesn't feel like it has enough it.
> > (already a lot of units)True, 7 unit lines is enough, why don't we just cut it down to six then? why not 5? that would be easier to balance. but I think having so much similarity between air units and naval units while ground units are so unique is boring and sad.
> > (too difficult to make unique)look me in the eyes and tell me how all of the units I suggested weren't unique and were too gimmicky at the same time again.
> > (too gimmicky)both gimmicks are simple ones. shoot different materials based on what's in inventory, and get close to other naval units and kill them. neither are too gimmicky or even more gimmicky than 90% of what's on erekir, and people still love erekir (me included.)
> 
> 1 i didn't even have to read them at first cause more unit lines is just a bad idea also i did read them when making the second comment 2 they just are, using resources from the main base? that needs a lot of setup to even use and also leeching off other units is very gimmicky cause it needs other units to work at all 3 erekir does not really have too much gimmicky units 4 it's simply too late to actually remove unit lines after they have been added also current naval units can just be made more unique or add some other units to the naval combat, we don't need more unit lines

1 that's way too dismissal dude...
2 so does the mono line???? they mine resources, build things (only non core line that does that RN), and can napalm your enemy through kamikaze attacks. the t5 doesn't even have weapons! BTW did you know the navinax increases factories production when nearby? I take back anything I said about that line. there's also toxopid being immune to 90% of ground hazards...
3 mech t2 has lasers that destroy projectiles, mech t3 is able to make units (it's projectiles count as units) the t1 to t2 or t4 transition for the ship line turns a ground unit into an air unit, how t4 and t5 units are made, need I say more?
4 Duh, I was being partially sarcastic, but also no??? v6 was one major version ago and the update to it removed more units than an entire unit line (player controled units)
5ish: Navanax being able to increase factory production is good enough for me in terms of uniqueness. also, the only units in the game for players are unit lines and core units so far, the enemy exclusive faction made of neoplasm might just have unit lines as well, but might just have a bunch of completely unique units.
6 why are you taking this so seriously? I'd make a mod out of this if I was actually super serious about wanting it. It's just a cool idea.

**Comment by jehosula** [comment]
ye just make a mod, we are not doing a complete overhaul of the game again, also lower nova tiers can build, mine and repair too,  and also kamikaze can be done by any air unit theoretically, and also quell and disrupt also make missile units (those are really more of a unit type than a gimmick with how it's used)

**Comment by Noahblast20** [comment]
> ye just make a mod, we are not doing a complete overhaul of the game again, also lower nova tiers can build, mine and repair too, and also kamikaze can be done by any air unit theoretically, and also quell and disrupt also make missile units (those are really more of a unit type than a gimmick with how it's used)

sure, I'll just learn an entire coding language to make a mod, no big deal/hj
But anuke already is, adding completely new maps, changing old ones (yes they are community made, but still), new pathing, more levels on erekir, the list goes on and on.
Being able to build is a v8 thing. yes, they can also mine and repair. both of those are still gimmicks, just ones that are core game features.
Yes. Air units can definitely do that. and?
Unit type is a gimmick. dude.

**Comment by jehosula** [comment]
> sure, I'll just learn an entire coding language to make a mod, no big deal/hj (I'm already planning to make a CW inspired one) But anuke already is, adding completely new maps, changing old ones (yes they are community made, but still), new pathing, more levels on erekir, the list goes on and on. Being able to build is a v8 thing. yes, they can also mine and repair. both of those are still gimmicks, just ones that are core game features. Yes. Air units can definitely do that. and? this one's first tier is just flying, electric based crawlers. Unit type is a gimmick. dude.

mining, building and repairing were always possible with the nova line, also i meant like it's a normal thing with the units, not a one off

**Comment by Noahblast20** [comment]
> > sure, I'll just learn an entire coding language to make a mod, no big deal/hj (I'm already planning to make a CW inspired one) But anuke already is, adding completely new maps, changing old ones (yes they are community made, but still), new pathing, more levels on erekir, the list goes on and on. Being able to build is a v8 thing. yes, they can also mine and repair. both of those are still gimmicks, just ones that are core game features. Yes. Air units can definitely do that. and? this one's first tier is just flying, electric based crawlers. Unit type is a gimmick. dude.
> 
> mining, building and repairing were always possible with the nova line, also i meant like it's a normal thing with the units, not a one off technically a fifth of erekir units use missile units

yes... that's still a gimick...
Yes, 3 of the 56 units in the game do have this effect! and?

**Comment by jehosula** [comment]
> yes... that's still a gimick... Yes, 3 of the 56 units in the game do have this effect! and?

you should only count the units for one planet. also the support in serpulo is really closer to 9 out of 35 having some sort of support ability and for erekir it's 3 out of 15 missile unit users

**Comment by jehosula** [comment]
also check the reactions on discord

**Comment by Noahblast20** [comment]
> > yes... that's still a gimick... Yes, 3 of the 56 units in the game do have this effect! and?
> 
> you should only count the units for one planet. also the support in serpulo is really closer to 9 out of 35 having some sort of support ability and for erekir it's 3 out of 15 missile unit users

all of the support units were introduced in v6, except the naval ones, which were introduced in v7, a total of 15 out of 38 actually. all of them use the GIMMICK of support effects. I don't see what your argument is.

Yes, 3 of 18 erekir units use missile projectiles to attack. This is still a gimmick, unless EVERY unit does it.

> also check the reactions on discord

dude, two of the 4 reactions are you and me both laughing at this idea

**Comment by jehosula** [comment]
> > you should only count the units for one planet. also the support in serpulo is really closer to 9 out of 35 having some sort of support ability and for erekir it's 3 out of 15 missile unit users
> 
> all of the support units were introduced in v6, except the naval ones, which were introduced in v7, a total of 15 out of 38 actually. all of them use the GIMMICK of support effects. I don't see what your argument is.
> 
> Yes, 3 of 18 erekir units use missile projectiles to attack. This is still a gimmick, unless EVERY unit does it.
> 
> > also check the reactions on discord
> 
> dude, two of the 4 reactions are you and me both laughing at this idea

by your logic ALL units have MULTIPLE gimmicks even all the ordinary ones and also support effects are really not that gimmicky, so many games have them, really your definition of gimmick is useless here

**Comment by Noahblast20** [comment]
> > > you should only count the units for one planet. also the support in serpulo is really closer to 9 out of 35 having some sort of support ability and for erekir it's 3 out of 15 missile unit users
> > 
> > 
> > all of the support units were introduced in v6, except the naval ones, which were introduced in v7, a total of 15 out of 38 actually. all of them use the GIMMICK of support effects. I don't see what your argument is.
> > Yes, 3 of 18 erekir units use missile projectiles to attack. This is still a gimmick, unless EVERY unit does it.
> > > also check the reactions on discord
> > 
> > 
> > dude, two of the 4 reactions are you and me both laughing at this idea
> 
> by your logic ALL units have MULTIPLE gimmicks even all the ordinary ones and also support effects are really not that gimmicky, so many games have them, really your definition of gimmick is useless here

yes, the only unit that doesn't have a gimmick is the dagger. Yes, my definition of gimmick is useless for trying to separate new gimmicks from older, more refined ones.

**Comment by jehosula** [comment]
> yes, the only unit that doesn't have a gimmick is the dagger. Yes, my definition of gimmick is useless for trying to separate new gimmicks from older, more refined ones.

even DAGGER has MULTIPLE gimmicks by your definition
1 it deals damage (a few units don't)
2 it uses regular bullets (again a few units don't)
3 it comes right out of the factory (most units need reconstructors)
4 it uses regular legs (several units use a different movement type)

**Comment by Noahblast20** [comment]
> > yes, the only unit that doesn't have a gimmick is the dagger. Yes, my definition of gimmick is useless for trying to separate new gimmicks from older, more refined ones.
> 
> even DAGGER has MULTIPLE gimmicks by your definition 1 it deals damage (a few units don't) 2 it uses regular bullets (again a few units don't) 3 it comes right out of the factory (most units need reconstructors) 4 it uses regular legs (several units use a different movement type)

1st is not a gimick. the few units that don't are the ones with the gimmick, as there are only 5 out of the entirety of all units that don't.
2nd yes, the ones that can't attack or have irregular attacks (vela and anthicus both come to mind). those are gimmicks. every other unit can shoot bullets that deal damage to enemies (some include the gimmick of healing aligned units/blocks).
3 that's not a gimmick of the dagger, that's a gimmick of the ground factory.
4 that's not a gimmick, that's just visuals. there's no difference between a dagger and a corvus in terms of actual mechanical movement. being able to fly is a gimmick, weither you fly through wings or jets, if there's no mechanical difference, then it's not a gimmick.
5 My definition of gimmick is a mechanic that deviates from the norm of the game's design. The gimmick of the origin of the thing that has the mechanic is not a gimmick of the thing that has the mechanic. E.G. Plastanium conveyors, Unloaders. Basically, if you can say, "this group is x, except for y, which is z" then z is the gimmick.
