### ISSUE TITLE
Names for unnamed teams

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5218]
### Describe the content or mechanics you are proposing.

This is just a cosmetic update; however it doesn't need much effort, and these two nonames won't bother me anymore.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Blue team could be named Ravens, and Green team could be named Syndicate. (Idk what else to say)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
you kinda placed the 2 lines in the wrong spot (irrelevant comment)

**Comment by camelStyleUser** [comment]
there are 251(since neoplastic)(249 if blue and green are considered  some kind of name) unnamed teams, dont think anuke wants to name almost every team that exists

**Comment by itcannotbe** [comment]
~~Let's just remove all the names and let's call them with RGB Hex values instead so that no color in the RGB Color space would feel unspecial~~

**Comment by camelStyleUser** [comment]
name the 2 unnamed base teams? maybe but i dont think it would help very much since there will still be 249 unnamed teams
