### ISSUE TITLE
Fast units (horizon, flare, etc.) cant be controlled on mobile

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry-Suggestions#522]
Decrease horizon speed or do something idk, same applies to flare and possibly crawler. (idk if there is anymore fast unit)

Units that are listed above are damn fast and i cant control them because you have to click & hold and how much you try it doesnt work, they escape, there is no way to control when they are under attack command (default command, which makes it worse) Possible solutions are:

1 - Change how you control a unit, instead of click & hold (Click & hold is fine so i suggest 2)
2 - So when we click and hold, they escape but we should control them, you have to make scripting for that, when we click & hold a unit, it remembers the unit even if it escapes, and then puts you to control of that unit. This should be done fast so the unit doesnt get maybe even a bit away.
3 - Change default command to idle, but this problem will still exist when units are under attack command

Now you may say you can use command center, set them to idle, and control, but this would be unbalanced and stupid because while pc players can control them easily mobile players would have to make a command center, set it to idle and then control, this would be a waste of resources and there may be situations where you may need to control when units are attacking. This issue should be fixed, please, dont leave a cool reply destroying the entire thing and close the issue. I made this a feedback because issues consist of bugs, not problems (which are the same thing but idk, you read this anyway...)

**Comment by Anuken** [comment]
> flare, possibly crawler

Let me just ask, what possible tactical advantage are you trying to gain by manually controlling units that are worse than every starter ship (and without a command center, at that)?

**Comment by Zenith-LY** [comment]
> > flare, possibly crawler
> 
> Let me just ask, what possible tactical advantage are you trying to gain by manually controlling units that are worse than every starter ship (and without a command center, at that)?

sometimes we may need to control them like maybe for tactical attacking because they just like suicide under attack command and attack nearest enemy point, but with our controls we can make it better like cintrolling them to attack somewhere else.

**Comment by Anuken** [comment]
But those units are practically useless alone. You cannot accomplish *anything* with a single one of them without a command center.

> but this would be unbalanced and stupid

First of all, I don't see a problem with PC players having an advantage over mobile. PC will always have better controls and movement, because they use a mouse and keyboard instead of an unwieldy touchscreen.

Second of all, this is not "unbalanced", because nobody tries to control these units anyway. You are effectively handicapping yourself by controlling them. They are only useful in swarms, and for that you need a command center anyway.
