### ISSUE TITLE
Liquid saturation mechanic for buildings

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry-Suggestions#5220]
### Describe what you would like changed, and why.

Right now everything that requires liquid are working as soon as any tiny drop of that liquid is passed to the building. Like T5 factory, that constructing while being connected only to the two cryofluid mixers will still go on, but slowly which makes no sense. You can ride on half-empty tank car but you can't run it where you keep tank just barely filled.

And in game you can see that liquid isn't enough only when you click on pipes or turn block state on and see it flickering, both are not intuitive at all.

### Describe the changes you want to propose. Include possible alternatives.

1. Separate each block animation between "has liquid" and "working" like thorium reactor do

2. Make every building that requires liquid to shut down and accumulate that amount of liquid before working. So if, for example,  plastanium compressor requires 15 oil/s or 15 oil each time it produces result, then if it's just connected to 6/s mechanical oil pump then it'll wait 2.5 seconds till oil accumulate in it and only then it'll produce 1 plastanium before shutting down again instead of flickering factory state.

**Comment by rekokoro** [comment]
https://github.com/user-attachments/assets/17eea844-718c-42d7-bf3b-dee00b9b39a1

Visual representation. Top factory as it is right now, bottom one is what I'm proposing - factory respects liquid requirement and displays lack resources state rather than slowing down and flickering.

**Comment by jehosula** [comment]
useless idea at best, actively bad at worst, this really makes it harder to see how undersupplied stuff is too

**Comment by jehosula** [comment]
> Excuse me, maybe you'll share how to tell if silicon smelter lacks coal or sand? Or maybe it should smelt slowly to show that it's lacking something cause there's no way to tell from silicon that not working at all.

you can VERY easily see the red and flickering diamonds

**Comment by rekokoro** [comment]
> > Excuse me, maybe you'll share how to tell if silicon smelter lacks coal or sand? Or maybe it should smelt slowly to show that it's lacking something cause there's no way to tell from silicon that not working at all.
> 
> you can VERY easily see the red and flickering diamonds

In case of lacking solid materials factory stops and not operates, why should it operate while lacking liquid materials then? Forget about real world, it doesn't make any sense in game either.

**Comment by jehosula** [comment]
> In case of lacking solid materials factory stops and not operates, why should it operate while lacking liquid materials then? Forget about real world, it doesn't make any sense in game either.

because it only needs a minscule amount of liquid for each frame, but it needs the full amount of items every time it finishes
