### ISSUE TITLE
Fix Voting

### ISSUE THREAD

**Issue by VoidNmbrZero** [Anuken/Mindustry-Suggestions#5225]
### Describe the content or mechanics you are proposing.

Lately there are people/bots joining up servers and kicking everyone because it only requires 3 votes. I was a victim of one kick so far. But seen a lot, lot more people get kicked. I think voting must require at least 75/65% of players to agree for vote to pass. It would've been great too if more than 2 people from one ip won't be able to join a server and/or multiple people wouldn't be able to join at all once.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Im afraid that soon the servers will be unplayable because of these vote kick abusers. When I and some players kicked them and prevented others getting kicked another wave joined and boom, server's dead.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
that's a server issue but maybe make it customizable

**Comment by VoidNmbrZero** [comment]
That's what im talking about

**Comment by jehosula** [comment]
> That's what im talking about

so really the only thing that can be done is adding a little customization cause servers are not owned by anuke

**Comment by VoidNmbrZero** [comment]
thanks for clarification, my brain wasnt braining
