### ISSUE TITLE
Scatter generation being at 0.00 by default (not 0)

### ISSUE THREAD

**Issue by BSp-2** [Anuken/Mindustry-Suggestions#5226]
### Describe what you would like changed, and why.

Id like the scatter feature being at 0.00 chance (less then 0.01 but bigger then 0) by default. 
![Screenshot_20240911_081122](https://github.com/user-attachments/assets/b230a8d2-250e-4fce-8fb4-69782a6cafc1)

### Describe the changes you want to propose. Include possible alternatives.

Usually it takes me 5-20 seconds to make it 0.00, since im an android mapper. Also at 0.01 the amount of generated stuff is usually way too much, and 0.00 being perfect amound. I lately make a lot of maps, and when adding scatter (i do that a lot) its verry annoying to turn it from 0.01 to 0.00.

**Comment by BSp-2** [comment]
May be a skill issus, but its a quality of life feature for me

**Comment by camelStyleUser** [comment]
0.00 is equal to 0

**Comment by BSp-2** [comment]
> 0.00 is equal to 0

No
![Screenshot_20240911_082728_io anuke mindustry](https://github.com/user-attachments/assets/437237c3-0f4d-4935-bdf9-4dee3242800e)
![Screenshot_20240911_082726_io anuke mindustry](https://github.com/user-attachments/assets/bcec12fd-1623-43f1-b545-e5781245ed1e)
