### ISSUE TITLE
A real AI

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5227]
### Describe the content or mechanics you are proposing.

A "gamemode" in which the enemy units (and eventually neoplasm) will use a real, learning AI that will invent new strategies instead of a brainless bot

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will make up a huge challenge fir veterans; however the AI should only use the information stored in the player's save. That means it will only learn from what the player does on his device. I mean, the AI on every save file will learn differently, so that it doesn't outsmart everyone immediayely. I also think it should have a button to reset the AI (if possible) after it is too good to be dealt with. Now, i know that neoplasm is going to be an AI of some sort, but it will not learn like a human would do. Altough idk if any of this is possible

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
very weird but quite interesting idea

**Comment by Mythril382** [comment]
Horrendously difficult to implement though.

**Comment by SITUVNgcd** [comment]
Good idea, but not easy to do that.

**Comment by AVeryCoolSpider-PL** [comment]
I know it will be very hard to implement; this is an idea to work on for yeats probably, as an AI is a very complex program. Altough it IS possible as i have seen games with this mechanic already; however only two.

**Comment by itcannotbe** [comment]
Error: Your computer/device is too basic to have the necessary processing power to even attempt human like decisions making.

**Comment by Gwapowo** [comment]
all your processing power are belong to us
