### ISSUE TITLE
Use monospace font and fix precision when displaying numbers

### ISSUE THREAD

**Issue by ZeroRin** [Anuken/Mindustry-Suggestions#5229]
### Describe the content or mechanics you are proposing.

right now when the game shows a changing number like 89.9 -> 90 -> 90.1, the string will jitter constantly due to the change of width. As 9 is much wider than 1, and the second number 90 has only 2 digits.
i suggest to use monospace numbers, and always keep the trailing 0, so the above case goes `89.9 -> 90.0 -> 90.1`. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

make numbers more readable and protect eyes

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This actually makes sense.
