### ISSUE TITLE
Update the "Legacy Map Importer" to "Image Map Importer", with support for all v6 tiles.

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#523]
**Describe the content or mechanics you are proposing.**

Updating the Legacy Importer to provide at least general support for v6 tiles, rather than the limited set available from v4. Possibly allowing for transparency so that we could import in 'layers' rather than overwriting the map in its entirety.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

At present, creating detailed maps in the native Mindustry editor is difficult, due to limited tools and generation filters, and making large maps (>500x500) is simply not possible outside of an image processor. Rather than reworking the native editor or adding new tools, it seems it would be easier to simply add more support for importing images created elsewhere. Because v6 supports having wall blocks with different floor tiles beneath, adding support for transparency to ignore preexisting blocks/floors in the active map would allow content creators to import maps in layers to achieve even greater detail.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
You should know that legacy map importer is called legacy because it was the way we imported maps during v3.5.

Also you can still play that older version by looking up Mindustry Classic.

**Comment by Anuken** [comment]
This is exactly what v6 already does. Extra overlays (ores) or buildings are not included in the image for obvious reasons, but those are easy enough to generate or add in the editor.
