### ISSUE TITLE
Oxide as ammo

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5232]
### Describe the content or mechanics you are proposing.

Oxide currently is only used as a building material. I suppose it can also work as ammo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Oxide could be used as better ammo for Diffuse, and maybe as an alternative ammo for Disperse; that would give it more uses

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kenny-Ofc** [comment]
put oxide as breach ammo

**Comment by Anuken** [comment]
There's a [Trello card](https://trello.com/c/iwY3vvPA/921-more-erekir-turret-ammo) for this, if you have ideas for specific ammo items with specific properties, it would be best to comment there.
