### ISSUE TITLE
Vote kick issues

### ISSUE THREAD

**Issue by Nico-234** [Anuken/Mindustry-Suggestions#5233]
### Describe the content or mechanics you are proposing.

People have been abusing the vote kick button to falsely kick players recently.
So, this is the idea:
ANTI EVADE VK

A feature where the bans should still work even if the player being vote kicked leave. People are using this to evade vote kicks.
REPORT FALSE VK

What is a false vote-kick?
A vote-kick that is not needed:
Not good reason;such as "annoying" or "shaddap". That's abusing the VK option.

If players false VK you, there should be a option to report the vote kick, with a reason.

1 - False vote kick
2 - Sexual reason
3 - Spam
4 - Political reason

These are examples for the options.
There should be an AI to review them, but it would be hard to implement, so the report button would kind of hard to implement.
VK DISABLE PREVENTION

There is a script/plugin going on that I don't know the script or how it works, but it's basically a option where people disable the ban just to evade.
I honestly don't know how to prevent that, because it's probably a mod/apk that is very deep in the internet.
AUTOMATIC PERMANENT BANS AND WARNINGS

This feature should work like this:

3 - 6 vote-kicks in a server: warning
7 - 9 vote-kicks in a server: longer bans, 120 - 320 minutes of ban.
10 vote-kicks: permanent ban.

A approved report of a fake vote kick should remove 1 vote-kick registered in a server, so people don't abuse this to unfairly perm ban people.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

These people false vote kicking/evading vote kicks ruin the multiplayer experience, especially griefers who make a fake vote kick so they can act without vote kicks.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by deepspacerunner** [comment]
Anuke does not own nor moderate any mindustry server, please take it up with the owner of the server(s) in question

**Comment by SITUVNgcd** [comment]
Each server has their own vote kick system.
