### ISSUE TITLE
Balances the number of enemies that appear on the decline map.

### ISSUE THREAD

**Issue by DIEGOTHESALSER** [Anuken/Mindustry-Suggestions#5235]
### Describe what you would like changed, and why.

I suggested a change in the difficulty of the map because many enemies appear and they are very strong and they do not stop appearing, it is almost impossible to pass it due to the exaggerated number of enemies that are generated. They do not allow what they destroy to be rebuilt.

### Describe the changes you want to propose. Include possible alternatives.

that the number of enemies that appear is simply slightly less to give time to rebuild key parts to continue

**Comment by jehosula** [comment]
what even is the map you are playing on? i am pretty sure there is no official map with that name

**Comment by camelStyleUser** [comment]
> what even is the map you are playing on? i am pretty sure there is no official map with that name

he is playing the download craft command map and he doesnt have the money for it

**Comment by AVeryCoolSpider-PL** [comment]
Are we even talking about Mindustry or its ripoffs?

**Comment by DIEGOTHESALSER** [comment]
It is in the campaign mode of the planet Erekir, the name of the level is decline

**Comment by jehosula** [comment]
> It is in the campaign mode of the planet Erekir, the name of the level is decline

are you playing on english? any mods? cause there is no erekir campaign map called decline

**Comment by BSp-2** [comment]
Maybe he plays crevice? Or wait it might also be ravine...

**Comment by AVeryCoolSpider-PL** [comment]
But i played all of the Erekir maps without using whatever kind of stuff they unlock, and it was completely fine... alright, strategy is to just spam Sublimate, you should have it unlocked by now

**Comment by Kokice5** [comment]
> It is in the campaign mode of the planet Erekir, the name of the level is decline

Could you screenshot the map?

**Comment by DIEGOTHESALSER** [comment]
![Screenshot_20240921-220801](https://github.com/user-attachments/assets/f2e67cb0-719f-4e38-af28-5bc21db9af47)

**Comment by DIEGOTHESALSER** [comment]
> > Esta en el modo campaña del planeta Erekir, el nombre del nivel es declive
> 
> ¿Estás jugando en inglés? ¿Alguna modificación? Porque no hay un mapa de campaña de Erekir llamado Declive

no, I play in Spanish, without modifying anything

**Comment by DIEGOTHESALSER** [comment]
> Pero jugué todos los mapas de Erekir sin usar ningún tipo de cosas que desbloquean, y estuvo completamente bien... bien, la estrategia es simplemente usar Sublimate, ya deberías tenerlo desbloqueado.

Yes, I do that but when I attack them, once I enter the core, normal enemies begin to appear. Once I destroy the core, enemies begin to appear non-stop.

**Comment by DIEGOTHESALSER** [comment]
I don't know if it's a bug but from what I see it happens only to me

**Comment by jehosula** [comment]
> ![Screenshot_20240921-220801](https://private-user-images.githubusercontent.com/181942698/369663882-f2e67cb0-719f-4e38-af28-5bc21db9af47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NzkzOTIsIm5iZiI6MTcyNjk3OTA5MiwicGF0aCI6Ii8xODE5NDI2OTgvMzY5NjYzODgyLWYyZTY3Y2IwLTcxOWYtNGUzOC1hZjI4LTViYzIxZGI5YWY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNDI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWQ2NGZjMjMxOTI3OGFmZDRjMjRiMDA0MTgzMWQ5NThjMDQxMTA4ZTVhODRmZDdhYjI0Y2NjYmUxMTkxMTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h_K7_Voqrwwc0ND-Bn00oYcu_lrz9APq_6WNvq28R8Y)

he meant a screenshot of the map in game

**Comment by BSp-2** [comment]
Seems like basin to me

**Comment by AVeryCoolSpider-PL** [comment]
This is Aegis, judging by the location (Basin is on the south pole)

**Comment by BSp-2** [comment]
If thats aegis this person has a massive skill issues... 😢
