### ISSUE TITLE
A "Launchpad" for Erekir

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry-Suggestions#5238]
### Describe the content or mechanics you are proposing.

This is not really a Launchpad; i have an idea to make it so that you can launch resources into the orbit and call them back when you need them. It can also be used as a missile that can crash anywhere on the map except for the core no-build zone. The result of the crash will depend on what is inside; for example if there is surge alloy in there, it will explode and shoot lightnings. If there is beryllium or tungsten, it will scatter shrapnel around.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Idk what to out here, this is probably a heavily unbalanced idea that came to my mind just now

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
the biggest issue really is that it doesn't really work for erekir's kind of thing

**Comment by itcannotbe** [comment]
So is this for storage or for offense/defense?

**Comment by ZeroRin** [comment]
sounds like some orbital strike ability
