### ISSUE TITLE
Persisting camera when you press V

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry-Suggestions#524]
**Describe the content or mechanics you are proposing.**
When you control a unit or turret and decide to leave, you get sent all the way back to the core, which is very infuriating if you need to move some blocks or units(especially that 1. there are no faster units that can build other than the core units and 2. some units cannot build). ~~So, pressing shift(boost key) and V(escape key) to instantly exit at the position you were at would be very nice. If this feels OP, maybe you can make it so you have to *hold* V+shift (waiting as a new core unit is summoned and travels to your place(aesthetically)) to exit the unit.~~

Or an alternative solution(mobile friendly, probably the better solution now that I think of it): **make the Camera persist at your last position after you press V**, until your core unit rushes in a straight line there. When the core unit is damaged or you press any of the movement keys(desktop only) in the process, your camera will only *then* snap to your core unit. (In this case, maybe shift+V will make the camera snap to the core as soon as you press V.)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You are not interrupted by the camera getting flung to the nearest core every time you press V.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
You can accomplish this by pressing the camera panning key (*mouse forward*), then pressing V. I really don't want to change the default behavior, because when *I* press V, I usually *want* to see what's happening at the core.

**Comment by sk7725** [comment]
> You can accomplish this by pressing the camera panning key (_mouse forward_), then pressing V.
Not really, since the core-spawned unit doesn't move to your last location - when you try to *move/return* your camera snaps to the core nonetheless. Pressing V+mouse forward(camera pan)+mouse back(follow cursor) doesn't do this either(although at least it should - actually, mouse back+mouse front should not make the offset camera snap back to the player at all)

**Comment by Anuken** [comment]
>  doesn't move to your last location

That's not "persisting camera", that's an entirely new form of movement that mimics mobile, which I definitely won't be adding.

> although at least it should - actually, mouse back+mouse front should not make the offset camera snap back to the player at all

But mouse movement using the back button is still movement, and a lack of snapping upon movement [was apparently unintuitive enough for someone to report it as a bug.](https://github.com/Anuken/Mindustry/issues/2417)
