### ISSUE TITLE
Game saves

### ISSUE THREAD

**Issue by Travisthenics** [Anuken/Mindustry-Suggestions#5241]
### Describe the content or mechanics you are proposing.

Please let us link a gmail account to the game we have saved because I've restarted the game like 20 times because I keep deleting it. Lets just say I'm a pro at completing the intro.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I wont have to restart every time i decide to play again. And it will be very helpful!!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kenny-Ofc** [comment]
Bro totally haven't yet open the settings. YOU can save your game into a file, by exporting it..
