### ISSUE TITLE
Logic serious renovation needed! 

### ISSUE THREAD

**Issue by Sam11870** [Anuken/Mindustry-Suggestions#5242]
### Describe the content or mechanics you are proposing.

This is not a suggestion, I am begging you please please please completely remake logic. I love mindustry, and I love the idea of logic and programming, but the execution is awful. It's so hard to program it putts me of the game. I understand programing on a phone is going to be difficult but because the screen is small and everything but you can do so much better, and the if lines are so horrid it's horrible.
A few things I, suggest, are insstead of a interface you scroll through make a map, on the right side there can be a panel with sections where you can get the blocks out of, and you can put them together, like in scratch.
This way functions can also be added. And it would fix the problem of them horrid lines and make logic so much easier.
I've been told I'm quite creative so I'd be happy to help creating this new approach to logic.
Please 🙏. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will seriously make logic seriously easier which will bring much more audience to the game. When logic is improved it will create more potential, more will be possible, with more people engaging in logic it will get more advanced, and interesting, the online servers will be so much more fun. Etc. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SomeonesShade** [comment]
An alternative is just making the code in a text editor, then import it in...
You can do functions with ```@counter``` shenanigans as current logic is assembly-like.
And remaking logic might not be worth it for minimal gain for a lot of backend/bug fixing

I'm not saying logic is flawless (it has a lot of difficulty and strife), but for what it is as of now, I think it's good enough taking everything into account.

**Comment by camelStyleUser** [comment]
want scratch? https://discord.com/channels/859455834245431296/859470553227329546 (mindustry logic server)

**Comment by Sam11870** [comment]
> An alternative is just making the code in a text editor, then import it in... You can do functions with `@counter` shenanigans as current logic is assembly-like. And remaking logic might not be worth it for minimal gain for a lot of backend/bug fixing
> 
> I'm not saying logic is flawless (it has a lot of difficulty and strife), but for what it is as of now, I think it's good enough taking everything into account.

**Comment by Sam11870** [comment]
> An alternative is just making the code in a text editor, then import it in... You can do functions with `@counter` shenanigans as current logic is assembly-like. And remaking logic might not be worth it for minimal gain for a lot of backend/bug fixing
> 
> I'm not saying logic is flawless (it has a lot of difficulty and strife), but for what it is as of now, I think it's good enough taking everything into account.

Where can I learn how to use a text editor to make logic?

**Comment by SomeonesShade** [comment]
probably in the discord server? or on your own most likely by copying the logic code and pasting into any text editor and see how the code lines turn into text

also jump labels/comments exist
```
set x 1
jump label always
set x 2
label:
set x 0
```

**Comment by Sam11870** [comment]
> probably in the discord server? or on your own most likely by copying the logic code and pasting into any text editor and see how the code lines turn into text
> 
> also jump labels/comments exist
> 
> ```
> set x 1
> jump label always
> set x 2
> label:
> set x 0
> ```

Ty i never knew you could do logic like this is so much easier

**Comment by cardillan** [comment]
There are also compilers that can translate from a high-level language into mlog. A few of these are actively developed and some produce good enough code:

[mlogjs](https://github.com/mlogjs/mlogjs): [online editor](https://mlogjs.github.io/mlogjs/guide/getting-started.html), [user's guide](https://mlogjs.github.io/mlogjs/guide/getting-started.html)
[Mindcode](https://github.com/cardillan/mindcode): [online editor](http://mindcode.herokuapp.com/), [documentation](https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX.markdown)
[Pyndustric](https://github.com/Lonami/pyndustric): this one doesn't have an online editor

Since these are high level languages, you can very easily write complicated expressions, loops or reusable functions in them.

(Disclaimer: I'm maintaining Mindcode. If you want to try it and need help, don't hesitate to [ask](https://github.com/cardillan/mindcode/issues).)
