### ISSUE TITLE
Stop instruction enhancement

### ISSUE THREAD

**Issue by cardillan** [Anuken/Mindustry-Suggestions#5246]
### Describe the content or mechanics you are proposing.

I propose the following enhancements to the `stop` instruction

- A visual indication for a stopped processor, possibly by the red diamond for non-functional blocks. I'm not sure this is available for 1x1 blocks, so a separate indication mechanism for a microprocessor might be needed.
- Make the `stop` instruction conditional:
  - The condition would be the same as in `jump`, except there would be no target. When the condition is met, the instruction stops, otherwise execution continues.
  - If tags get implemented (#5245), the `stop` instruction might contain additional parameter (say, `reason`). When stopped by the instruction, the processor's tag would get set to this value.
  - Today's `stop` instructions would need to get converted to `stop always` for backwards compatibility.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

- Visual indication of a stopped state would help spot problems with processors and their code.
- Conditional stop instructions would make the cost of adding debugging statements cheaper - just one instruction instead of two or three in case the reason should be displayed. Especially compilers from higher-level languages to mlog would benefit from this. (Disclaimer: I maintain one such compiler. I plan to use the stop instruction for some preconditions checking - such as array bounds checks - in the future. The conditional stop combined with the processor tag would be very useful, as the compiled mlog code is not generated by the user, so a sensible error message needs to be provided.)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AxoCat** [comment]
your suggestion makes no sense, stop is literally just an unconditional jump to the start

**Comment by cardillan** [comment]
> your suggestion makes no sense, stop is literally just an unconditional jump to the start

That is the `end` instruction. 

`stop` just stops the processor, preserving all variables, including the `@counter`, for inspection. There's no way to resume the processor from this state except by modifying the code.

**Comment by cardillan** [comment]
Breakpoints would be great for interactive debugging. There are actually one or two debugging mods that have something similar. I tried one just the other day, some debugging was possible, but single-stepping through the code always executed a bunch of instructions at once, which was annoying.

I envision the `stop` instruction for handling unexpected conditions in a program (e.g. an array index out of bounds) by the compiler. It is doable with the current one, but you need at least two instructions (a jump around a stop) to not lose the @counter context. Three, if you want to embed some explanation or error message in a print instruction above/below the stop.

**Comment by Mnem42** [comment]
Makes more sense to add an `exception` block that's either blocking or non blocking based on a toggle, and can show details, maybe with an optional additional jump to some exception handling code (ideally preserving `@counter`). Just makes a bit more sense for semantics

**Comment by Mnem42** [comment]
Makes more sense to add an `exception` block that's either blocking or non blocking based on a toggle, and can show details, maybe with an optional additional jump to some exception handling code (ideally preserving `@counter`). Just makes a bit more sense for semantics

**Comment by SunkyMP3G** [comment]
> Make the `stop` instruction conditional

Just put the jump instruction right before the stop

**Comment by cardillan** [comment]
> Just put the jump instruction right before the stop

That's possible, of course. I was hoping there would be a way to replace this sequence:

```
jump label1 lessThanEq index 10
print "Index out of bounds accessing ARRAY"
stop
label1:
...
```

with a single instruction `stop greaterThan index 10 "Index out of bounds accessing ARRAY"`, because it would be three times cheaper for a compiler to generate such checks, and easily readable even in the mlog code.

I'd consider the visual indication of a stopped processor the most useful, though. It would make spotting buggy code much easier.

**Comment by Mnem42** [comment]
Very late, but should be possible to make it have a yellow status indicator if stopped (because it's working and paused, but it's not not working (like a red status indicator)), and it should only appear if status indicators are enabled

**Comment by cardillan** [comment]
I wouldn't even mind the red diamond. Whether a hyperprocessor is stopped due to not having cryofluid, or due to encountering a stop instruction, it needs to be fixed.

I'm not sure the status indicators are even implemented for 1x1 blocks, though. I don't recall ever seeing one. And the disabled indicator is different for 1x1 blocks and bigger blocks.

Maybe some visual indication could easily be added by a mod. I'll try to investigate it.
