### ISSUE TITLE
Provide a way for processors to detect map reloads

### ISSUE THREAD

**Issue by cardillan** [Anuken/Mindustry-Suggestions#5247]
### Describe the content or mechanics you are proposing.

I propose to add a way for a processor to detect that a map was reloaded:

- Either by adding a map variable, say `@reloads`. The variable would be stored in a map save file, and would be increased by one every time a map is loaded (including map switches in campaign mode). A processor could compare the value to a previously stored one, detecting reloads this way.
- Alternatively, allow marking a processor as "resettable" in some way. On map reload, the `@counter` of such processors would be set to 0.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Display content isn't stored in a map file. This means that, when a map reloads, the entire display needs to be redrawn. That makes it impossible to draw an entire display just once and only update some parts of the display later on.

The second use case is that units controlled by a processor aren't stored in a map file either. This is less troublesome, though, because this situation is detectable through the `@controller` property.

Note: in Mindustry Logic v6, it was possible to detect map reloads by comparing the differences between `@time` and `@tick`. Since v7, `@time` and `@tick` are derived from the same value and can no longer be used to detect map reloads.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
do ghost cells not work for that anymore???

**Comment by cardillan** [comment]
I don't know, I haven't stumbled upon ghost cells actually. Can't find anything on the net, what it is?
