### ISSUE TITLE
Alternative gamemode for wave-based sectors

### ISSUE THREAD

**Issue by DestroyThing** [Anuken/Mindustry-Suggestions#5248]
### Describe the content or mechanics you are proposing.

A new difficulty gamemode (akin to the planned features of setting campaign difficulty and ability to turn on erekir ai) 

In this gamemode, every remaining wave is sent all at once, but your time to prepare is the combined starting prep time + all wave downtime timers

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will add replayability to the defence-based sectors by forcing people into an entirely different mindset when playing. At one hand, you don't have to waste time on the early-game defending like placing lower-tier walls and turrets for the first few waves. On the other hand, the difficulty rises exponentially and the kind of defence that works would be a lot more difficult to make. Also, i think it would be fun. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
seems like a gimmick difficulty that would work for a mod modding it to vanila more than a regular feature, unless multiple of such gamemodes are added

**Comment by DestroyThing** [comment]
I mean, technically, the planned difficulty modifiers like "fog of war in serpulo" or "units have random priority with blocks" can be considered just as gimmicky as what i just suggested, so i think it would fit right in.

**Comment by jehosula** [comment]
> I mean, technically, the planned difficulty modifiers like "fog of war in serpulo" or "units have random priority with blocks" can be considered just as gimmicky as what i just suggested, so i think it would fit right in.

the difference is that niether really affects the pacing much, FOW is only relevant early on before you scout everything and unpredictable wave ai only makes units a little less predictable in targeting, this one completely changes up everything so it might have to follow other stuff
