### ISSUE TITLE
Select Multiple Drills/Pumps to see total output rate

### ISSUE THREAD

**Issue by Nataly171** [Anuken/Mindustry-Suggestions#5249]
### Describe the content or mechanics you are proposing.

Some way to see the total output speed of a selected number of drill or pump type machines. The most intuitive way I see this being implemented is to show this total when you are placing a schematic, whether copied or being placed from the schematic menu. This way you get to see the total when placing schematics into the world, or if the machines are already placed, you can simply select them all and hold the created schematic over the same location.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since ratios are very important for efficient factories, making it more convenient to see what your inputs are goes a long way. The highest source of variance I've found in this area is with drilling items and pumping fluids. Depending on what tiles the machines are overlapping, they may produce different amounts of resources. I believe it would be an excellent quality of life feature to be able to do this as opposed to manually adding up each individual machine's output rate.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
Omg yes, I need this!!!
