### ISSUE TITLE
Floating Platforms and... Pools...? Canals?

### ISSUE THREAD

**Issue by Ferociousfeind** [Anuken/Mindustry-Suggestions#525]
**Describe the content or mechanics you are proposing.**
Special 4x4 or 5x5 blocks which essentially temporarily terraform ground into water, and water into ground, to help the player utilize the units at their disposal. Of course, they can be attacked by enemy units and deconstructed by the player to restore the original terrain (I'm not suggesting allowing the player to directly edit the map), but the main functionality is to allow bridges over deep water, and canals through dry land.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
These blocks would afford naval units greatly enhanced versatility- simply build a giant pool in front of your naval factory to house the produced units. It also affords versatility for ground units in a water-dominated map. (Though considering the strength of naval units in their element, is that really what you'd want?) The large size of the blocks would hopefully make them a little cumbersome to use outside of bridging large gaps, and having no more than a little bit of health would mean that even a few Flares could pose a threat to your bridge and/or canal if you try to use them offensively- and even defensively if they aren't properly guarded. I suppose getting units to properly recognize buildings as water might be difficult, or might introduce some issues, though if you already routinely label buildings as walls that ground units can't walk over, you can probably already label a building as liquid that a naval unit can traverse...

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Very similar to #306 and #47, but not exactly the same.

**Comment by Ferociousfeind** [comment]
I see... though, I really dislike the idea of building on top of the platforms- not only would that break the purpose of deep water being rather unusable outside of naval units and pumps, but it'd also present a saving issue- what if multiple blocks occupy the same space, what gets saved in that location? (Is that even how saving works? I'm not entirely sure, actually.)

Seems my quick search was a little too quick, regardless. Oops.

**Comment by Kyllingene** [comment]
Personally, +1. As someone who has made some maps, water is an amazing resource, but it can obsolete ground units entirely. This, though, would make them viable almost everywhere (would they work in space?), but not in the same way. You have to build a bridge, then defend it. It also makes naval units usable in maps with no/little water.

If this is implemented, would it be possible to eliminate the behavior of conveyors where ground units can walk over them as if they were ground? For example, lets say there is shallow water in the map. You want to cross it with ground units. You place conveyors over the water to make them go faster.
