### ISSUE TITLE
Seperate out the difficulity setting

### ISSUE THREAD

**Issue by bornav** [Anuken/Mindustry-Suggestions#5250]
### Describe what you would like changed, and why.

Highly opinionated, make the difficulty setting sepereate so it does not scale both the quantity and health, but one for each.

Reason for this is what usually breaks the flow and feeling is having the same enemies become bullet sponges

### Describe the changes you want to propose. Include possible alternatives.

Instead of one setting for toggling the difficulty make it 2, or add a checkbox that would scale the health of enemies with difficulty

**Comment by jehosula** [comment]
last time i checked eradication difficulty only increases hp by 50% and that doesn't really change too much

**Comment by bornav** [comment]
As said Highly opinionated, and yes 50% is not much, but would much rather increase the amount of enemies even more and leave the hp the same

**Comment by jehosula** [comment]
> As said Highly opinionated, and yes 50% is not much, but would much rather increase the amount of enemies even more and leave the hp the same

i'll be honest, 50% wasn't making a noticable difference in my experience, wouldn't change any interactions significantly, and your thing about them being bullet sponges implies they have like 3x hp if not more, also a nice little boost to the enemies stats is better than having to increasing the emount of enemies beyond 2x
