### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by Shadow93139** [Anuken/Mindustry-Suggestions#5252]
### Describe what you would like changed, and why.

Spanish version
actualmente mindustry tiene un sistema de guardado que consiste en exportar los datos de la partida y uno mismo tiene que guardarlos en algún lado. Yo ya e tenido varios problemas con ese sistema y ya e perdido sectores por qué se corrompen los archivos. Y una vez perdí todo mi progreso por qué no pude encontrar el archivo con los datos exportados. Propongo que mindustry tenga una forma de guardado en la nube como los juegos en línea. Facilitaría mucho el recuperar los datos. Yo e perdido varias veces el interés en jugar mindustry por estar teniendo que guardar manualmente los datos cada vez. Es un juego maravilloso que disfruto mucho pero me disuade mucho de jugarlo el tener que guardar yo mismo los datos pues no me gusta nada perder uno, dos o todos los sectores y progreso que me e reforzado por obtener en el juego.

English version:
Mindustry currently has a saving system that consists of exporting the game data and you have to save it yourself somewhere. I have already had several problems with that system and I have already lost sectors because the files are corrupted. And once I lost all my progress because I couldn't find the file with the exported data. I propose that mindustry have a form of cloud saves like online games. It would make recovering the data much easier. I have lost interest in playing mindustry several times because I have to manually save the data every time. It is a wonderful game that I enjoy a lot but I am very discouraged from playing it by having to save the data myself because I do not like losing one, two or all of the sectors and progress that I have been reinforced by obtaining in the game.

### Describe the changes you want to propose. Include possible alternatives.

Spanish version
Implementar un sistema de guardado en la nube automático para que los jugadores no tengamos que preocuparnos de perder nuestro progreso en el juego.

English version
Implement an automatic cloud save system so that players do not have to worry about losing our progress in the game.

**Comment by camelStyleUser** [comment]
> i propose anuke pays for servers to host cloud saves on

no
