### ISSUE TITLE
More Campaign saves

### ISSUE THREAD

**Issue by maniolos** [Anuken/Mindustry-Suggestions#5254]
### Describe the content or mechanics you are proposing.

I would like to propose adding more campaign saves into the game, basically 3 profiles to play campaign on which would have different saves.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would allow players to play on different campaign saves, this would be useful in this scenario:
You have a player invested deeply in the game, this player has 3 friends.
- he plays on one save with all of them
- 2nd save for playing with one other friend on mods
- 3rd for playing alone  

This would remove the need to mess with the game files and steam cloud.
I know this was suggested already but the user gave a bad explanation of how it will improve the game: https://github.com/Anuken/Mindustry-Suggestions/issues/913

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nilederg** [comment]
I agree that this would be a significant and worthwhile improvement.
