### ISSUE TITLE
Battery consumption while playing

### ISSUE THREAD

**Issue by nepumuk-fs** [Anuken/Mindustry-Suggestions#5255]
### Describe what you would like changed, and why.

I'd like the calculation of ressources mined (and materials produced) to be changed because I notice that my phone becomes hotter not only during a ”playing session“, but also does the maximum temperature of a session  with every new time playing.
Additionally the battery capacity decreases significantly after playing several days in a row for two or three hours.

### Describe the changes you want to propose. Include possible alternatives.

My conjecture is that the amount of ressources mined is calculated live for every sector simultaneously. I propose taking the income rates of the last five minutes ingame if they're stable for extrapolating the resources mined.
I mean, stable income rates indicate a (dynamic) equilibrium and therefore the incomes in the sectors (maybe excluding the sector the player is at) can be ”simulated“ (extrapolated) instead of calculated. (The game goes on and behaves like the player would be there in the background.

Alternatively if there's already an estimation (extrapolation) of the minerals mined and materials and liquids produced, I suggest taking a rougher estimation for efficiency and therefore not only, but also speed reasons.

**Comment by cardillan** [comment]
The game already does precisely this. The average consumption/production including imports/export is taken while actively playing each sector, based, if I'm not mistaken, on last two minutes in the sector. There's a very rough simulation, not only of resources consumption/production, but also of attack waves, for each inactive sector. I'm not sure much can be done to optimize this.

Have you tried turning the animations and maybe effects off in settings/graphics? I've never played the game on a mobile device myself, but I'd say these could help to reduce the CPU load a lot.
