### ISSUE TITLE
The map/levels and turns 

### ISSUE THREAD

**Issue by SonAzcuLost** [Anuken/Mindustry-Suggestions#526]
I was from the previous version (alpha build 104) and this improved a lot with the planet and the new things but for example the turns, so I am playing from scratch (it does not bother me) I saw that there was something new called turns which I did not know what it was for when I passed the first level I thought I was going to give 15 minutes (which lasts a turn) to build or farm and then other waves more, but no, it turned out that I had a level with no waves to face to farm even if the shifts passed

I would like that when a shift passes that another wave comes

**Comment by Anuken** [comment]
1. Use the issue template.
2. I don't think you understand how the campaign works. Turns have a specific purpose, which is not fully implemented yet.
