### ISSUE TITLE
Draw transformations not reset when editing mlog code

### ISSUE THREAD

**Issue by cardillan** [Anuken/Mindustry-Suggestions#5261]
### Describe what you would like changed, and why.

The bleeding edge version of Mindustry now supports transformations of graphical output. These transformation matrix is apparently stored within the context of the processor. When pasting a completely new code into the processor, the transformations aren't reset. Such transformations might even cause an otherwise correct graphical operations to be rendered completely outside of the display area, making diagnostics of such situation quite a bit difficult.

I'm addressing a situation I've run into a few times already:
- I have an old code producing graphics output which works
- I add graphics transformations and mess up
- I try to undo changes to the code, removing all transformations, and it suddenly doesn't work (typically it renders completely outside of the display - if it produced any output at all, it would be easy to figure out the reason). I start to wonder whether I've introduced other bugs into the code.

Demonstration

Paste this code into a processor with a large display attached:

```
draw reset 0 0 0 0 0 0
draw rotate 0 0 90 0 0 0
draw translate 0 -176 0 0 0 0
draw clear 0 0 0 0 0 0
print "TEXT"
draw print 40 40 center 0 0 0
drawflush display1
stop
```

This will output text rotated 90°.

Now paste new code into the same processor:

```
draw clear 0 0 0 0 0 0
print "TEXT"
draw print 88 88 center 0 0 0
drawflush display1
```

The text is still rotated, although nothing in the code performs any graphical transformations.

### Describe the changes you want to propose. Include possible alternatives.

I propose to reset the transformation matrix whenever a code is edited in the processor, the same way variables are reset.

**Comment by Anuken** [comment]
Transformations are actually a property of the display, just like color and stroke - those are not reset either.

**Comment by cardillan** [comment]
Sorry, I missed it! In this case there's probably no easy solution.
