### ISSUE TITLE
The real-time speed of the conduit or conveyor belt should be accessible within the logic processor.

### ISSUE THREAD

**Issue by wgqcreeper** [Anuken/Mindustry-Suggestions#5262]
### Describe what you would like changed, and why.

When writing logic in the logic processor, it would be ideal to obtain the real-time speed of an item on the connected conduit or conveyor belt (the speed that is displayed after clicking on the conveyor belt). This would provide us with better capabilities for visualizing data.

### Describe the changes you want to propose. Include possible alternatives.

Add a new command to the "sensor" command: "sensor var1 conduit1 @realTimeSpeed @<itemName/liquidName>". This command allows the real-time speed of a specific liquid or item on the conduit or conveyor belt connected to the current logic processor to be obtained.

**Comment by camelStyleUser** [comment]
> conduit

i love desync in userspace(normal proc) logic
