### ISSUE TITLE
Logic interface QOL on mobile

### ISSUE THREAD

**Issue by Markty07** [Anuken/Mindustry-Suggestions#5265]
### Describe what you would like changed, and why.

right now, swiping up and down [edit : on mobile] doesn't scroll but switches code blocks around, it's pretty counter intuitive and the actual way to scroll is imprecise for small adjustments while it's easy to accidentally move code you don't want to.

### Describe the changes you want to propose. Include possible alternatives.

Add a button on each code block that makes it move only if you swipe from that button. Swiping elswhere will simply scroll non proportionally to to code size, to avoid large codes being unpractical to navigate on smaller screens (like phone screens). Keep the side bar working as it is though to allow quick travel around the code.

Alternatively we could have small adjustment arrows, that would already help a ton.

**Comment by kyliotic** [comment]
Definitely agree with this. Editing logic on mobile is fairly janky and blocks of code end up getting deleted semi-often when scrolling or ESPECIALLY when editing `jump` targets.
