### ISSUE TITLE
Underground conveyor

### ISSUE THREAD

**Issue by EmanuelCCgames** [Anuken/Mindustry-Suggestions#5270]
### Describe the content or mechanics you are proposing.

When building conveyors We will be able to touch a button on the screen to go to the lower layer of the floor, and be able to build transporters below the ground, but it will cost more to make them, since for example: when building them you need lead and metals to make the supports for the conveyors, to prevent the ground from falling on top of the conveyors, and that we have buttons to build ramps up and others down (up: when they are underground) (down: when they are on the surface), also that it can be done with classifiers and other types of conveyors, I think they could even make machines to collect materials from the underground directly , and enemy NPCs can shoot at the ground to destroy the carrier supports to destroy them and damage whatever we have down there , And there are certain limitations, such as not being able to build under excavators or lakes of water and lava.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would help to transport materials through areas that are very crowded with others and that the bridges do not reach.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
He specifically said not to put down underground conveyors!
