### ISSUE TITLE
Allow heat draining from overheating thor reactors

### ISSUE THREAD

**Issue by Jurorno9** [Anuken/Mindustry-Suggestions#5272]
### Describe what you would like changed, and why.

Currently, Thorium reactors produce heat while running w/o Cryofluid. In Erekir, heat is a resource that can be drained/moved/spent.  I propose integrating these 2 concepts, so schemes can utilize *nuclear heating*.

Thorium reactor heating would add more nuance to mix-tech schemes, as Thorium-based schemes would be high-risk (requiring micromanaging, very explosive ), high-reward (a power-generating heater). Furthermore it would provide a avenue for more ... unconventional ... mix-tech factories as a whole, as it would create 2 competitive endgame heaters to choose from

This change would not impact any balancing of Erekir or Serpulo, but would greatly benefit mix tech gameplay

### Describe the changes you want to propose. Include possible alternatives.

Make heat produced by overheating Thorium reactors usable to adjacent heat-draining blocks

**Comment by JackAtak1103** [comment]
Cool Idea!

**Comment by jehosula** [comment]
mixtech was not meant to be played, ever, this would be a completely useless feature to both of the main planets

**Comment by BalaM314** [comment]
this is difficult due to technical limitations, as heat producers cannot be overdrived

**Comment by Jurorno9** [comment]
> mixtech was not meant to be played, ever, this would be a completely useless feature to both of the main planets

mixtech gameplay may not be *intended*, but it still is popular. Adding small additions like this has no cost to other campaigns

**Comment by Jurorno9** [comment]
> this is difficult due to technical limitations, as heat producers cannot be overdrived

Ahh, I was afraid that would be the case.  I am willing to take a stab at a implementation, as long as its not a thousand-line rewrite.

**Comment by Jurorno9** [comment]
closing for now, expect a mention in a pr later
