### ISSUE TITLE
Split servers.json to repository

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry-Suggestions#5274]
### Describe what you would like changed, and why.

Most commits are ``servers.json`` updates.
This causes significant waste of downloading time and disk space.
I don't want to see this commit being downloaded endlessly every time I do a git pull, etc.

### Describe the changes you want to propose. Include possible alternatives.

Make server list repository and put server.json files.
It need edit server list fetch url in source.

**Comment by camelStyleUser** [comment]
☠️ literally already done for BE and v8
