### ISSUE TITLE
Core Drill

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry-Suggestions#5275]
### Describe the content or mechanics you are proposing.

Every sector has it's own 5x5 chasm that you can build a Core Drill on. This drill uses water asa coolant and produces 160 slag/sec (50/sec on Serpulo). The drill is 5x5 and consumes lots of power. On Serpulo it also outputs lead too. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This Core Drill provides an amazing source of slag that is needed for bulk materials and resources.                        
                                                                        -Day 3

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
we don't need more slag 💀

**Comment by Miroslav2048** [comment]
It's a good idea for a mod, but not for a game...

**Comment by jehosula** [comment]
> It's a good idea for a mod, but not for a game...

YES, would be great for a mod but doesn't belong in vanila, i should be saying this more instead of saying "just no" or smth more often

**Comment by JackAtak1103** [comment]
Cool beans. I don't make mods, but if anyone wants to use these ideas in mods go ahead.
