### ISSUE TITLE
world processor

### ISSUE THREAD

**Issue by Miroslav2048** [Anuken/Mindustry-Suggestions#5276]
### Describe the content or mechanics you are proposing.

1) Increasing the world cell memory capacity
A total of only 128 slots for values??? Even a memory block contains more information...
There are two options: either increase the capacity to 4096 (or another value) or make the memory setting configurable for the cell.

2) Why does the "sensor" command have more parameters than the "prop" command?
I would like the ability to edit almost all parameters.
(Or even modify parameters such as maxHealth or itemCapacity for the selected block, or for all blocks at once if a checkbox is enabled.)

3) Custom blocks
It's unlikely that you will add this, but it would be great to have the ability to create custom blocks (JSON and HJSON).
(This would be specific to individual maps, as there are already mods available.)

![Скриншот 16-10-2024 201217](https://github.com/user-attachments/assets/36d4ced7-db48-47a2-83fd-1cb822eb72c6)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I believe that the proposed content will significantly enhance the game by introducing new layers of complexity and creativity.

1) Increased World Cell Memory Capacity: By expanding the memory capacity to 4096 slots or allowing customizable memory settings, players will have the ability to store and manage more intricate data and mechanisms. This enhancement will enable the creation of larger and more complex structures, allowing for innovative gameplay strategies and deeper engagement with the game.

2) Expanded Parameters for Commands: Allowing more parameters for the "prop" command will provide players with greater customization options. This flexibility will empower players to tailor their gameplay experience, creating unique blocks that fit their specific strategies. The ability to modify parameters like maxHealth or itemCapacity will also encourage experimentation, leading to diverse gameplay styles and approaches.

3) Custom Blocks: Introducing the ability to create custom blocks using formats like JSON or HJSON will open up a new realm of possibilities for players. This feature will not only foster creativity but also support a thriving modding community. Players can design unique mechanics and interactions, leading to the development of innovative maps and scenarios that can cater to various playstyles.

Overall, these enhancements will deepen the gameplay experience, attract new players, and retain the interest of veteran players by offering them more tools for creativity and strategy. This will ultimately contribute to a more vibrant and dynamic gaming community.

Good luck with the development!)

(Translated by a translator, because I'm not good at English)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
4096 numbers per world cell???? thats 32kb just for the numbers
also the memory bank contains the same amount of info as world cell for a unit of area and world cells cant be written by unpriveleged logic

**Comment by camelStyleUser** [comment]
also custom blocks?????
js,java???
json/hjson is not that big of a security risk(but anuke still wont let you custom blocks for map since somehow content removal should be done to not desync ids) but js or java?????

**Comment by Miroslav2048** [comment]
> also custom blocks????? js,java??? json/hjson is not that big of a security risk(but anuke still wont let you custom blocks for map since somehow content removal should be done to not desync ids) but js or java?????

I think you're right. With the help of programming languages, you can write malware and more...

**Comment by kyliotic** [comment]
Heavily in favor of the first 2/3 suggestions. Not sure about the 4096 values per world cell but an increase in capacity is definitely very welcome
