### ISSUE TITLE
More tutorials on some mechanics

### ISSUE THREAD

**Issue by xblade720** [Anuken/Mindustry-Suggestions#5281]
### Describe the content or mechanics you are proposing.

they shoud be tutorials for some mechanics like electricity generation, unit creation, or some mechanics (like the thing that drones will mostly aim for power sources)

something like erekir, but every friend i have presented mindustry decided to start with serpulo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will make it easier for new players to learn how to play

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
Yeah, this would be nice. There should be multiple optional in-game tutorials on different topics like mining, power generation, and unit controlling.
