### ISSUE TITLE
No-building zone tile

### ISSUE THREAD

**Issue by FallingDice** [Anuken/Mindustry-Suggestions#5283]
### Describe the content or mechanics you are proposing.

How about making a no-building zone tile?
It would be nice if you could set up an area even if it wasn't a tile.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it would add more variety to the fun.
Example: 
 •traditional tower defense game
 •anti-trick measures

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
Are you saying like a tile with the capability of a wall, but units can go travel through it?

**Comment by FallingDice** [comment]
Yes, that's right. :)
