### ISSUE TITLE
Cycles

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry-Suggestions#5284]
### Describe the content or mechanics you are proposing.

Mindustry has a day and night cycle already. I am suggesting a screen somewhere that shows the time of day, what cycle you are on, current solar%, and possibly when the current sector you are on was first visited. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This feature is mainly for solar power help. It's always useful to have stats on different things and this isn't going to affect much in-game. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
a clock could be useful but solar % can easily be seen by looking at a solar panel and doing a bit of math

**Comment by JackAtak1103** [comment]
K, thanks for the feedback.
