### ISSUE TITLE
Proximity Mine

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry-Suggestions#5286]
### Describe the content or mechanics you are proposing.

A 1x1 structure with a small range. If an enemy travels into its range, a very short time will pass. After this time the building will...BOOM! This explosion deals damage to everyone in range and gets destroyed in the process. It utilizes a reaction between blast compound and plastanium that creates a small violent explosion.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Ever need a quick one-time way to get rid of a few daggers? BAM, problem solved. Give those crawlers a taste of their own medicine!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bottinator22** [comment]
what about shock mines?

**Comment by jehosula** [comment]
too similar to shock mines tbh

**Comment by JackAtak1103** [comment]
How do you use shock mines? They always just got shot when I tried to use them.

**Comment by jehosula** [comment]
> How do you use shock mines? They always just got shot when I tried to use them.

make sure you have enough poly to build them quick and just spam them on enemy unit feet

**Comment by JackAtak1103** [comment]
Cool ty

**Comment by JackAtak1103** [comment]
Replace shock mines with proximity mines? Proximity just seems better.
