### ISSUE TITLE
Unit command option: pick up item

### ISSUE THREAD

**Issue by CheesyMeatball** [Anuken/Mindustry-Suggestions#5287]
### Describe the content or mechanics you are proposing.

A unit command that automatically makes units take an item of your choice from a container of your choice. To set this up, you click on the button for the command, click on the container you want the units to take from and click on the item you want them to take. They will automatically stop this command if the container has not had the requested item inside for more than (insert arbitrary time). Cores count as containers.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow people to set up air bombing attacks without needing to use logic. This will, in turn, mean less people using attem logic online.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
you can load them manually yourself by getting in them, it is a little slow however
