### ISSUE TITLE
Infinite Resources Confusion 

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry-Suggestions#5288]
### Describe what you would like changed, and why.

In the map editor, you can turn on "Infinite Resources". This makes the player be able to build with well, infinite resources. However, when I saw it, I thought it meant that resource patches/veins wouldn't run out. Can you change it to Infinite _Building_ Resources? Ty

### Describe the changes you want to propose. Include possible alternatives.

I might just have been dumb...

**Comment by JackAtak1103** [comment]
FYI, Factorio just released (Factorio: Space Age DLC) today. Not sure if that affects Mindustry at all.

**Comment by jehosula** [comment]
ores don't run out normally, you were just dumb

**Comment by camelStyleUser** [comment]
ores dont run out
???????????

**Comment by camelStyleUser** [comment]
unless you got limitedres which then you have specifically made them run out

**Comment by JackAtak1103** [comment]
When I saw this I thought that ores could be toggled to run out. I thought that the Campaign had infinite ore veins but in the editor, you could have limited resource per patch of ore.
