### ISSUE TITLE
New logic unit control commands — «deconstruct» and «scheme building»

### ISSUE THREAD

**Issue by 1justsomeone1** [Anuken/Mindustry-Suggestions#5289]
### Describe the content or mechanics you are proposing.

Add a new types of unit control instruction for logic processors — deconstruct and scheme building. «Deconstruct» orders bounded units to deconstruct building of your team and derelict somewhere on the map. To prevent griefing this command can be disabled in map rules. «Scheme building» orders bounded units to build a group of buildings somewhere on the map. This can be possible if you paste little scheme in symbol format into instruction

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will allow to deconstruct derelict buildings with logic and create maps with better AI or player-like enemies

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by CheesyMeatball** [comment]
logic schematic that orders units to build more of itself >:)

**Comment by jehosula** [comment]
> logic schematic that orders units to build more of itself >:)

that kinda exists already

anyway about the suggestion, i don't see any downside if it's a wproc exclusive, would simplify using world logic building a ton

**Comment by 1justsomeone1** [comment]
> anyway about the suggestion, i don't see any downside if it's a wproc exclusive, would simplify using world logic building a ton

I been thinking about that and decided not to because all wproc exclusive features are independent instructions, not types. And some people probably will not know about these commands if they will be added like that, but anyway i respect your opinion

**Comment by Accollide** [comment]
I dont see this getting added, but an alternative is for someone to make a program where you input your schem and it outputs the logic instructions to build it.

to my dismay, bridge conveyors will not connect to eachother when built with unit building and i dont see any easy way to implement that that isnt annoying. This makes most schems useless but cool idea

**Comment by 1justsomeone1** [comment]
> to my dismay, bridge conveyors will not connect to eachother when built with unit building and i dont see any easy way to implement that that isnt annoying. This makes most schems useless but cool idea

Hmm... What about suggesting also unique config to bridge conveyors that include on the which side must be connected bridge and how far is it. Like «Config: W2» (on the west and there is 2 tiles between). I could right now but my English is litlle bad
