### ISSUE TITLE
Silly easter egg

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry-Suggestions#5290]
### Describe the content or mechanics you are proposing.

![image](https://github.com/user-attachments/assets/8fb341da-285f-493c-a434-46faa746265a)
make the logo have a 1/100000 chance to do this when booting up the game.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1: it'd be funny
2: mindustry is honestly lacking silly side

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
make it yourself sure
great PR idea to make smh

**Comment by JackAtak1103** [comment]
Yes, and Yes. It is lacking on the funny side. Why so serious?
