### ISSUE TITLE
Reclaim Unit

### ISSUE THREAD

**Issue by Markty07** [Anuken/Mindustry-Suggestions#5291]
### Describe the content or mechanics you are proposing.

An Erekir unit that requires silicon to build and will reclaim any derelict around the map, even when the player is not present. It's annoying to have to clean up derelicts after conquering a sector. It will have its own factory, a bit like the Manifold unit.

To make it extra good, because no point in balancing QOL features, it will reclaim very fast.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Make it that you clean up derelict faster will leave more space for production in conquered sectors and speed up research, mainly oxide and tungsten dependant research which are very slow to get early on.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Markty07** [comment]
Heck the core can even automatically build this unit.

**Comment by jehosula** [comment]
you can already reclaim blocks super-fast in BE, and a unit that interacts differently for one particular team could be tricky to code, this feature will be completely redundant in the next version

**Comment by WilloIzCitron** [comment]
How it goes... Trying to hijack units
