### ISSUE TITLE
Smart-Core Mode

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry-Suggestions#5292]
### Describe the content or mechanics you are proposing.

If you are on the opposite side of the sector and all the sudden you see !!CORE IS BEING ATTACKED!!, the player on that team will teleport to the core and blueprints won't disappear. The player can toggle this mode on and off. If there are multiple people on a team, they each will get separate toggles. All able to attack troops within the core's build zone will defend the core. Any buildings in a power grid that are right next to the core will have power priority over buildings in the same power grid that are far from the core, unless it is a power producing building that needs power to run (like the impact 
reactor)(This power grid only matters if the power is negative). 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Kinda QOL for when the core is being attacked and you have to act fast. The toggle should be located in settings. Turrets closer to core could get priority over ammo and fluids than other turrets feeding from the same belt, but that seems super complicated to code. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
interesting feature but would probably get obnoxious SUPER fast when a flare shoots the core with a bullet or a horizon splashes there accidentally or some zenith that died in 0.5 seconds gets a tiny hit would disrupt so much if it's on and leaving it as a player setting will cause too much impact for actual gameplay, only the teleporting thing could reasonably be made as anything besides a game rule or an always active feature, you could also just teleport there yourself (not sure if it saves blueprints in BE that way) and/or mess with power grid/send units to defend
