### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Aleksander20122** [Anuken/Mindustry-Suggestions#5293]

**Comment by jehosula** [comment]
this is one of the things to never suggest cause anuke will not add them, just close this suggestion cause it's not gonna be added

**Comment by camelStyleUser** [comment]
> [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

have you
