### ISSUE TITLE
Block Under Construction Dynamic Health

### ISSUE THREAD

**Issue by deepspacerunner** [Anuken/Mindustry-Suggestions#5294]
### Describe what you would like changed, and why.

The current behavior of blocks under construction. It's very annoying to have a large, powerful, expensive turret like a Malign be at 98% build progress and get destroyed by some stray splash damage.

### Describe the changes you want to propose. Include possible alternatives.

Health of blocks under construction should increase proportionately with build progress, similarly to how materials are consumed over time during the build process instead of all at once when the block is finished. This would make it less frustrating to set up defenses while under fire.

**Comment by alphy228** [comment]
Deleting t3-t5 reconstructors with gammas is peak,no u

**Comment by JackAtak1103** [comment]
Same should go for deconstructers

**Comment by nilederg** [comment]
I agree with this completely.

**Comment by JasonP01** [comment]
Why is bro quoting a thesaurus in his comment, had to flex his grandiloquence fr.

**Comment by nilederg** [comment]
i simply desire to transmit my intended philosophy unambiguously!
