### ISSUE TITLE
Make serpulo mass driver 'bullet' scale damage based on the amount and type of inputted resource

### ISSUE THREAD

**Issue by DestroyThing** [Anuken/Mindustry-Suggestions#5295]
### Describe the content or mechanics you are proposing.

This would technically make it the strongest turret for serpulo, but the catch would be - you'd need the perfect space to align the mass driver since it doesn't have any automatic targetting, on top of being the most expensive resource sink in the entire game, being way less efficient than any turret that can use it's materials as ammo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it would be fun

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Accollide** [comment]
nobody would use this

**Comment by Mnem42** [comment]
Nah, just arrange the mass drivers in a lemniscate with the corridor in between, to make any "bullets" that miss come back to get fed back into the system to kill very slow T5s

Or a rectangle, but that's less fun to say.

**Comment by Mnem42** [comment]
Still kinda useless, but it's *fun*
