### ISSUE TITLE
Move large solar panels below phase fabric tier.

### ISSUE THREAD

**Issue by DestroyThing** [Anuken/Mindustry-Suggestions#5296]
### Describe what you would like changed, and why.

I'm not particularly sure to which tier they should be moved to, but i think plastanium at most would be decent. The problem is - RTG's already fullfill the niche of free power when you have phase fabric available to you, and not only they do it nearly 3,5x as well, they don't depend on time of day and are considerably smaller

### Describe the changes you want to propose. Include possible alternatives.

It wouldn't make large solar panels useful still, due to the day/night cycle, but this would be a step in the right direction

**Comment by jehosula** [comment]
rtgs are not technically free power and they are reliant on a kickstarter still but ig they kinda compete quite a bit, 10% extra power for both solar panels would be a nice little buff
