### ISSUE TITLE
uLocate functions the same way as uBind

### ISSUE THREAD

**Issue by swrvy71** [Anuken/Mindustry-Suggestions#5298]
### Describe the content or mechanics you are proposing.

the uLocate instruction will locate another of the type of building selected when looped back into it, Like how the ubind binds a different quad instead of the same quad previously binded. how we loop back into uBind if a condition is not met  e.g flag, controlled, uncontrolled, etc.   Just as the title says

because it keeps locating the same building, over and over again when looped back into the ulocate instruction. (i tried)
(for the user's team,)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this would allow filtering in ulocate, just like flags in uBind with senors or/and jumps. unlocking COUNTLESS new possibilities.
 ex:
it Would allow units to find a building with very specific conditions, in which for example, allows the following:
locate a turret set with unique conditions, to filter it out amongst the same of its kind: 

for ex. 5 arcs, and
the current ulocate as of now , will keep locating the 1st arc of 5 arcs, unless that 1st arc is deleted, then only moves to the 2nd arc.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by kyliotic** [comment]
Wait - this was closed by OP? Was this feature actually added? Because if so that would be HUGE
