### ISSUE TITLE
Planet Maker

### ISSUE THREAD

**Issue by Epicbatman3000** [Anuken/Mindustry-Suggestions#5299]
### Describe the content or mechanics you are proposing.

Please Add A Thing Where You Can Make Planets And Add Levels to Them As Well Where You Can Upload Them Too

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It Will Add More Stuff To Do As Well As Add More Creativity To The Game

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
then make a mod

**Comment by jehosula** [comment]
> Why Does Every Word Starts With A Capital Letter?
> 
> It is painful to read.
> 
> Also, No, just no. That would make every repetitive but with more steps. And what the sense of having a place to upload them when all you want is a bunch of procedurally generated junk.

he wanted to be able to make custom campaigns in vanila and add actual maps to them, but yeah this is not that useful and would likely take a lot of time to make, uploading them will be done in the discord server so the dev doesn't have to pay for servers (indie dev and relies on donations)

**Comment by itcannotbe** [comment]
> > Why Does Every Word Starts With A Capital Letter?
> >
> > It is painful to read.
> >
> > Also, No, just no. That would make every repetitive but with more steps. And what the sense of having a place to upload them when all you want is a bunch of procedurally generated junk.
>
> he wanted to be able to make custom campaigns in vanila and add actual maps to them, but yeah this is not that useful and would likely take a lot of time to make, uploading them will be done in the discord server so the dev doesn't have to pay for servers (indie dev and relies on donations)

I hope that's what he want not just making everything from UI including the sector that goes with it.

**Comment by deepspacerunner** [comment]
Please Make A Mod That Changes The First Letter Of Every Word Into A Capital Letter With No Punctuation So We Can All Experience Pain
:trollface:

**Comment by Epicbatman3000** [comment]
didt know GitHub was gonna be this bad
