### ISSUE TITLE
Trying to control a disabled unit(over the unit limit with a red warning sign) should kill it

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry-Suggestions#530]
**Describe the content or mechanics you are proposing.**
Trying to control a disabled unit(over the unit limit with a red warning sign) should kill it immediately.
Optionally, grounded boats that cannot move should also do this.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When you have too much of your units so you cannot produce a higher tier of said unit, you need a way to get rid of excess units. If said unit was a small ground or leg unit, you can use mega to pick it up and chuck it into the factory, but if not...there is no way.
Same is with the boat units, and even worse, you cannot place blocks on them so they are just...there. Cannot do anything while it sits.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Ferociousfeind** [comment]
I think a better way to safely clear the unit limit would be an always-available suicide button. I've been using nuclear reactors to get units to disappear without a trace, but that's relatively expensive and requires a large open area to not damage other buildings. Having more control over your units would be really nice.

**Comment by RogueRedHawk** [comment]
If this were implemented it should transfer some scrap to the core upon destruction, proportional to the unit tier deconstructed.

**Comment by sk7725** [comment]
> I think a better way to safely clear the unit limit would be an always-available suicide button. I've been using nuclear reactors to get units to disappear without a trace, but that's relatively expensive and requires a large open area to not damage other buildings. Having more control over your units would be really nice.

I really want this to be a thing - at least in sandbox. Sadly, it is an easy target for griefers on a server, if only did they not exist...(Maybe disable it/limit it to admins on server?)

**Comment by sk7725** [comment]
Implemented(kinda?)
