### ISSUE TITLE
Give Pulsar/Quasar Mine Command

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#5300]
### Describe what you would like changed, and why.

Grant Pulsar and Quasar the RTS control: Mine. Poly and Mega can mine, so why not the nova tree too? 

### Describe the changes you want to propose. Include possible alternatives.

Give Pulsar, Quasar RTS control: mine. Only alternative as of now: logic blocks. If this is to be implemented, ideally the units will mine exactly as a poly would (boost the entire time).

**Comment by jehosula** [comment]
they also have the rebuild and assist player in BE so why shouldn't they be able to mine logicless (also nerf their mining to go with this)
