### ISSUE TITLE
Reduce late-game research costs in serpulo. 

### ISSUE THREAD

**Issue by DestroyThing** [Anuken/Mindustry-Suggestions#5302]
### Describe what you would like changed, and why.

I've tried to play a repeat playthrough of this game, and i really realized how insanely overpriced most research truly is. Most things require a lot of silicon, plastanium, surge, phase - all materials that are rather not easy to produce in extreme bulk. I personally can keep up with the costs, but by interacting with newer players, i noticed an increasingly high trend of people struggling with research, or skipping some altogether due to this. Waiting isn't fun. And to not wait, expecting people fresh to this game genre to have a grand total of 10000 silicon/second production divided among all sectors is unrealistic otherwise. 

To reduce the time to wait, and to decrease the milestone of total production required in order to not have to wait too long between sectors, i propose cutting all post-titanium tech costs by 2x at the very least. Perhaps by more if needed. 
For units, reduce it by 5x. A lot of people come to the server to ask which units to research, get told that one in particular is good, and then use said one unit against all remaining sectors, because the rest are unreasonably expensive

### Describe the changes you want to propose. Include possible alternatives.

Why do these 2 windows want you to write the same thing anyway? Isn't describing what i want changed already the description of the changes i want to propose? what am i missing here
Regarding alternatives, the one i could propose for units in particular is to have units be unlocked for free when the respective reconstructor is unlocked and other research requirements are met, exactly like it is in erekir.

**Comment by Kev-Vily** [comment]
literally wanted an easy way to beat the game

**Comment by DestroyThing** [comment]
> literally wanted an easy way to beat the game

No. The game is already easy, i just merely wanted it to be less tedious. It's really hard to get my friends into this game when they have to wait for hours between sectors just for research

**Comment by MissPotato** [comment]
Having played both planets through, I think Erekir hits a much better balance of research cost. Often finishing a sector with a full core would be enough to unlock any research.  Where as with Serpulo I'm often waiting around for research.

A counter point however is that with Erekir there are no sub-tiles. With Serpulo I imagine the idea is that you're supposed to spend your downtime capturing tiles surrounding progression tiles.
