### ISSUE TITLE
Submergible unit tree and more water sectors

### ISSUE THREAD

**Issue by Alecks1608** [Anuken/Mindustry-Suggestions#5304]
### Describe the content or mechanics you are proposing.

A set of water units that can submerge and go under water and enemy fire unharmed as their ability (like Nova to Vela units can fly) could be a great idea for a sub DPS support/Glass cannon (ironic because they're made of metalglass) naval unit like the crawler tree, meant for close combat and to deliver big and quick bursts of damage to partially or totally breach the front lines in shores and water based sectors.

(Although, the code behind submerging and emerging against targets would be hard for AI to use at its prime essence).

–––––––––––––––––––––––––––––––––––

The drawback or gimmick would be that when submerged, they can't attack any structure or unit that's in shallow water tiles and land/air, and if an unit/building is in water and/or deep water (their target criteria), then these submergibles can attack them but with limited firepower from their arsenal. Also, most naval units can attack them back with some of their weapons.

They would also be relatively more fragile than the Risso and Retusa trees but slightly faster than them when not submerged (contrary to Nova tree that their ability allows them to fly so they can reach their destination faster, these ships move slower to compensate their capacity to avoid enemy fire at most).

–––––––––––––––––––––––––––––––––––

Also, a turret idea that can prove to be useful inside and outside of its main purpose, which is (the name and descriptions is a mere concept and can be renamed/shortened for easier understanding):

• Scrambler: An anti land (and also under water) version of a Scatter and fused with Ripple, can use Metalglass, Plastanium, Blast Compound and Surge Alloy as ammo. Its Objective: Shoots a projectile that upon detonation due to reaching its point where the turret aimed (like Ripple), shatters and spreads a volley of lots of smaller projectiles that deal small amounts of damage over an great and extensive area.

This turret acts as an artillery to hit fast moving/slightly scattered units across the battlefield, great for crowd control and are directly designed to also harm underwater units with less efficiency (which means a bit less damage), the main bullet shot is weak on impact but quick with great AoE damage and has multiple sharpnels to extend the AoE coverage.

The effects from their ammo would follow a similar rule like the others.
Metalglass: the weakest option but adds a bit of attack speed.
Plastanium: the sharpnels have more sharpnels (yes, we've put bombs in your bombs)
Blast Compound: bigger AoE and higher base damage.
Surge Alloy: discharges electricity arcs on impact.

This turret would be a mid game 3x3 sized turret unlock in the same sector as the one required to unlock the Retusa tree, Copper, Titanium, Silicone, Metalglass and a bit of Plastanium are required for its construction and requires cooling to operate (foreshadowing the need of coolant for Meltdown) further allowing for use in a dedicated sector with THE naval units mentioned in the beginning.

–––––––––––––––––––––––––––––––––––

The so called "dedicated sector" would be a major sector that's a survival one like most of the rest, which would also be needed to unlock the submergible tree (which will be featured here in great numbers up to a tier 4 guardian which will mark the end of the sector) and to allow "Naval Fortress" to be attacked.

Minor tweaks would be needed to also feature these ships in numbered sectors and in Naval Fortress so it doesn't become a one time experience (like the entirety of the naval tree after Naval Fortress), adding a great experience with naval units.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This can:
• Give Naval units more playable content outside of custom maps.
• Add a niche mechanic that could change the way us, players approach water sectors in terms of strategic defense planning.
• Add variety in general when it comes to options for attack plans.

–––––––––––––––––––––––––––––––––––

• Have an excuse to add more water sectors

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
i wonder how many times submerging units were suggested, anyway that is quite a list

**Comment by Alecks1608** [comment]
> i wonder how many times submerging units were suggested, anyway that is quite a list

Sorry if it was very long but it's just that I got a bit carried away by the idea I got so suddenly.

Still I tried my best to elaborate it so it's interesting in any way
