### ISSUE TITLE
shield graph for mapmaking

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry-Suggestions#5307]
### Describe the content or mechanics you are proposing.

when making waves there is a graph for the amount of each enemy, the total amount of enemies and the total hp of the enemies

![Mindustry 11_1_2024 4_14_54 AM](https://github.com/user-attachments/assets/5955871c-3415-4838-9407-f66c99425adc)

i suggest adding a shield graph for the total amount of shield the enemies have, or a shield+hp graph showing the total between shield and hp

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

this will make it significantly easier to use shield scaling when making maps and to know how much shield the player will have to get through before doing playtests of your own

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
Yes please...
