### ISSUE TITLE
New mining method

### ISSUE THREAD

**Issue by Blackcurtainer** [Anuken/Mindustry-Suggestions#531]
For example, if you put a mechanical drill on two or more ores, it will be either one, right?
However, in this proposal, I would like you to change what comes out when you touch it, like a sorter or a reversing sorter.
I really wish I could do it.
Please adopt.

(Note: This uses google translate, so you may be a little poor at English...)

**Comment by Anuken** [comment]
This has been suggested many times, and I won't be implementing it.
