### ISSUE TITLE
Add tags to mod browser

### ISSUE THREAD

**Issue by Sangar2728** [Anuken/Mindustry-Suggestions#5310]
### Describe the content or mechanics you are proposing.

The idea is add tags for clasificate the mods more efficiently, one example will be: texture pack, QoL, informative, new content, new planet, etc.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This will improve the search of mods, specially when the mod is in another language like Russian 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
would 100% help with finding certain types of mods, 10/10 suggestion
