### ISSUE TITLE
Turrets stall when quickly switching targets

### ISSUE THREAD

**Issue by Accollide** [Anuken/Mindustry-Suggestions#5311]
### Describe what you would like changed, and why.

When turrets switch targets quickly, such as trying to kill 200 flares, turrets will stop firing while switching to a new target. when it does this quickly it will stop firing for while and this becomes an issue when lots of enemys exist. this is a very large issue where turrets that require charging time like malign wont fire at all. I dont know the code of the game or anything so this is based on observations. 

### Describe the changes you want to propose. Include possible alternatives.

turrets dont stop firing when switching targets if there is still enemys within its firing range. It only lasts a short period to switch to a new target if possible so it wont keep shooting if it needs to turn to hit a target.

**Comment by jehosula** [comment]
a completely unfair buff to low tier spam and an unfair nerf to some turrets, nothing wrong with fixing THAT so amazing suggestion that should be added 100%

**Comment by Accollide** [comment]
nerf to what turret? also how does this help low tier units?
care to elaborate?

**Comment by jehosula** [comment]
> nerf to what turret? also how does this help low tier turrets? care to elaborate?

oh the retarget delay nerfs (or nerfed) turrets like malign and smite which need charge up and even titan has noticable impact, and it buffs low tier spam because lower tiers die and force retargeting much more than higher tiers

**Comment by Accollide** [comment]
ah I misunderstood what you had said.
