### ISSUE TITLE
More difficulty modifiers

### ISSUE THREAD

**Issue by nakiri0209** [Anuken/Mindustry-Suggestions#5313]
### Describe the content or mechanics you are proposing.

2 more ideas for more difficulty modifier toggles to go along with the unpredictable wave ai and fog of war.
1. A Hardcore toggle - this toggle deletes your entire campaign save upon failing to capture a sector and locks the difficulty to eradication - much like minecraft's hardcore difficulty, you are only given 1 chance.
2. A toggle which bans launchpads - another option to increase the difficulty further, stopping reliance on export hubs and encouraging more efficient resource management upon launch.
3. For the hardcore toggle I also think that you should only be able to change the difficulty upon starting the campaign on ground zero - no more changing difficulty in the middle of a playthrough, this also makes the previous achievements of playing in hardcore and banning launchpads more prestigious and easy to verify.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I figured with the new eradication difficulty it wouldn't hurt to add an even higher level of (optional) difficulty for players who end up conquering even the future campaign submission maps on the hardest difficulties.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
the first thing to do is check the fairness of maps on eradication difficulty, also for hardcore it should be the only one you HAVE to set at the start, maybe launch pads being banned could also be unchangeable later? but the regular difficulty and other modifiers should be changeable so people don't get stuck doing something beyond their skill level and just stop playing

**Comment by nakiri0209** [comment]
> the first thing to do is check the fairness of maps on eradication difficulty, also for hardcore it should be the only one you HAVE to set at the start, maybe launch pads being banned could also be unchangeable later? but the regular difficulty and other modifiers should be changeable so people don't get stuck doing something beyond their skill level and just stop playing

you can also add a toggle which locks the difficulty and all other toggles tbh (and warn the player)

**Comment by Novanox4** [comment]
You don't need to have these added into the game though. You can set the difficulty to eradication, wipe campaign saves on death and not modify difficulties to simulate hardcore and just not use launchpads on serpulo.

**Comment by jehosula** [comment]
> You don't need to have these added into the game though. You can set the difficulty to eradication, wipe campaign saves on death and not modify difficulties to simulate hardcore and just not use launchpads on serpulo.

well yeah kinda

**Comment by nakiri0209** [comment]
> You don't need to have these added into the game though. You can set the difficulty to eradication, wipe campaign saves on death and not modify difficulties to simulate hardcore and just not use launchpads on serpulo.

and that's exactly the same for minecraft except bedrock has been begging for a hardcore mode despite it being self imposable, the point is to up the stakes and have a reward (being bale to flex your achievements without others worrying that you've easily cheated by changing the difficulty mid-run).

**Comment by jehosula** [comment]
> and that's exactly the same for minecraft except bedrock has been begging for a hardcore mode despite it being self imposable, the point is to up the stakes and have a reward (being bale to flex your achievements without others worrying that you've easily cheated by changing the difficulty mid-run).

true
