### ISSUE TITLE
The size of the input window in the mlog editor

### ISSUE THREAD

**Issue by ZeleniyKustik** [Anuken/Mindustry-Suggestions#5314]
### Describe what you would like changed, and why.
I want to increase the size of the input window as it is a little small.  For example, if I write bankram as the name, only bankr will be visible.

![Снимок экрана 2024-11-08 220015](https://github.com/user-attachments/assets/00317e42-135b-4638-8699-401dc1a35fd7)

### Describe the changes you want to propose. Include possible alternatives.
I would like to increase the size of the window for entering the name of the memory block. In the read and write operations.
To make it look more like a window like in sensor
![Снимок экрана 2024-11-08 215323](https://github.com/user-attachments/assets/d18114cc-2db9-47c0-a787-ff22050ddab2)

**Comment by Accollide** [comment]
very good
