### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry-Suggestions#5315]
### Describe the content or mechanics you are proposing.

In settings a toggle to change the colors to support colorblind people in gameplay.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More inclusive...

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
electrolyzer is the prime example of anti colorblind

**Comment by JackAtak1103** [comment]
Then don't change that in colorblind mode.?

**Comment by JackAtak1103** [comment]
or especially do?

**Comment by jehosula** [comment]
> Then don't change that in colorblind mode.?

i meant that it's extra hard for colorblind ppl, so it def needs a change
