### ISSUE TITLE
conveyors can be built over derelict conveyors

### ISSUE THREAD

**Issue by Accollide** [Anuken/Mindustry-Suggestions#5316]
### Describe what you would like changed, and why.

Currently if you try to build conveyor over a derelict conveyor of the same type and rotation it won't let you build. However using a differnt rotation or conveyor type allows you to. While this is primarily a problem with conveyors and walls, it also applys to other structures. For example, you cant build a solar panel over a derelict solar panel but you can build a large solar panel over a derelict small one. 

### Describe the changes you want to propose. Include possible alternatives.

Allow building over the structures. I assume that it is currently not allowed because you cannot build a conveyor of the same type and rotation over another one of your team. I am aware of the idea of repairing derelict structures and this suggestion does not overlap with it. Its totally fine to just delete the tile being built over, But an idea may be to reduce the cost for building over derelict structures.

**Comment by jehosula** [comment]
you already can in BE (dev build) there you can build a conveyor facing up on a derelict one facing up even if they are the same type and what it does is repair the derelict, this DOES in fact overlap with the derelict repair

**Comment by Accollide** [comment]
awesome
