### ISSUE TITLE
Underwater resources

### ISSUE THREAD

**Issue by MeanSand** [Anuken/Mindustry-Suggestions#5318]
### Describe the content or mechanics you are proposing.

Resouces come from ground, wall, and even the atmosphere, so underwater ones are not too far-fetched. Sand, oil, and various metals can be found in river, sea, etc., so it doesn't have to be new resource. For Erekir, Arkycite may have gas deposits.

All resources should use only one type of extractor (like how drill must choose which resource to drill underneath) and collection should be only via drones which the extractor builds.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I feel like naval units are just discounted air units. Sure, they are more powerful but air units get the job done just as well. Maybe not competitively though, I'm not familiar with that. So if there is competition in water area, not just a place units can move through, water units can be more valuable.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
Naval units aren't discounted air units. Even though they can only move in water and can't travel over walls, they are much more powerful than air units. Naval units sacrifice mobility for power.
