### ISSUE TITLE
V6 Alpha Campaign: Strategic Gameplay Feedback

### ISSUE THREAD

**Issue by LordForte** [Anuken/Mindustry-Suggestions#532]
Hello,

I've been playing the V6 alpha campaign for a few dozen hours now. Understanding it is alpha and it can radically change, I am doing the dangerous hobby of peering into the crystal ball.

I like what it proposes to do, but I am concerned over its long term problems. For example, invading every sector in the world would take forever for 'complete planetary conquest'. I suspect the progression map sectors (e.g, The Craters) is a fast track to winning or will be, but I am slogging through them still.

For consideration, I'd like to offer how Total War: Warhammer 1 and 2 (and Total War as a series) handles this kind of idea. That game is split between strategic and tactical (comparable Mindustry's sector world view/the actual base building, in sector gameplay). The strategic layer is turn based, with all major actions like army moving or sector-enhancements being done there. When armies collide it goes into pure tactical combat mode. I noticed Mindustry tracks its global resources/sector attacks in real time, which _can work_ but I wonder about tightening it up.

So, there are two ideas coming up here: Mindustry's strategic level becoming turn based, and enhancing sectors.

**By making Mindustry's strategic actions turn based**, you can tie resource income, enemy behavior, research(?), and many 'global' effects to the turn system. This can vastly simplify for players what they'll be getting the next turn, and what to potentially expect (e.g, an incoming attack). It'll also allow you to better get a read on a player's actions on a per-turn basis, if for example you want to teach the AI to be more aggressive against resource hogging, stationary players. Then, once something at the tactical level happens (e.g, a player is attacked or invades a new sector), there is the real time gameplay to do there.

**For enhancing sectors**, the idea is to marry procedural generation and meaningful purpose together. Currently you expand to sectors to make more bases for more resources for more research. This is a solid underlying principle, however even if it is, players can experience fatigue at the same idea again and again. Hence, to enhance sectors is to diversify their purposes while adhering to this principle.

- To expand on this, imagine a sector as more than 1 hex-tile; it is now a group of hex tiles up to X tiles in size.
- Each tile is now called a 'region', so each sector is divided up into regions.
- Each sector has a _Headquarters_ region that establishes who owns the sector and receives all its resources/benefits.
- Now, there are two other types of regions: military and resources.
- A military region provides benefits to war, such as a radar facility that warns about incoming attacks, provides reinforcements to an attacked region, etc.
- A resource region provides resources of whatever procedural type was generated for it, and simply fuels the economy.
- Players can build in on their own initiative inside of Headquarter and Military regions, but not resource regions. However, Headquarter and Military regions can _still provide resources_ if the player decides to build them that way.
- Resource regions exist to passively fuel the economy, and perhaps can be improved upon through research or building up the Headquarters region.
- A player or enemy may _invade_ a resource region (or any region within reach) to create a _Foothold_ that will allow them to further attack that sector. The invasion of a sector can thus be defined by which regions are attacked and taken over, depending on its strengths or weaknesses.

Now, what this does is create the potential for easily scalable topology, focus the player's meaningful actions, and create a strategic world. Some regions are given more value in either what they possess, or the path they make for attacks. Rather than 'take all regions', a player can strike to claim a sector in one or a few decisive battles. Ergo, for however complex the sector is affects how much time and effort the player needs to work in or attack it.

I can see many ways this system can tie into the campaign, and the versatility of a Sector+Regions model can offer much. For example, tying certain buildings or units to owning particular sector--e.g, you need a naval yard sector to go down the naval tech tree. Or perhaps you must own a particular sector to research and build Boss-type units. Maybe the enemy's "original headquarters" is too tough to invade until you dismantle their surrounding sectors, etc. There is also the ability for a player to choose how large/small, complex/simple, etc, a sector might be, and so curate their campaign experience to what they want.

**Conclusion**
I am hopeful this helps you in developing Mindustry, however you see fit to utilize it. I'm quite eager to see what more V6 and future development can bring, and what is there already has dozens of hours out of me lol

Thank you for reading.

**Comment by Salanderous** [comment]
This is some top quality feedback, and seems like these ideas could make the new campaign mode cooler than it already is!
