### ISSUE TITLE
plase update steam version, tks

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Anuken/Mindustry-Suggestions#5321]
### Describe what you would like changed, and why.

The steam version has fewer and fewer servers it can link to due to not getting updates for a long time

### Describe the changes you want to propose. Include possible alternatives.

...

**Comment by camelStyleUser** [comment]
???

**Comment by camelStyleUser** [comment]
and pinging anuke to get attention is not ok

**Comment by SomeonesShade** [comment]
Anuke checks suggestions anyway,
a quick read and ignore prob
