### ISSUE TITLE
Very good idea

### ISSUE THREAD

**Issue by Acid010** [Anuken/Mindustry-Suggestions#5323]
### Describe the content or mechanics you are proposing.

Mindustry please add in game a function that add avatar editor
Pls like in Roblox
And add a JavaScript panel
Here is all scripts

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I like mindustry

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Haznobrain** [comment]
get bricked

**Comment by Accollide** [comment]
_avatar editor?_ what avatar? you mean the unit you control? Also if you want to use JavaScript, just use the console. there are mods that let you access it. If you just want cheats there are mods for that too. 

close the issue please. 

%1

**Comment by Mnem42** [comment]
How's that even meant to work? The unit types are *not* cosmetic and actually mean something.
