### ISSUE TITLE
LOD(Level of Detail)

### ISSUE THREAD

**Issue by shan-luan** [Anuken/Mindustry-Suggestions#5325]
### Describe the content or mechanics you are proposing.

We need an LOD (Level of Detail) feature. LOD is an optimization technique that simplifies rendering details at lower zoom levels, such as replacing certain floors or buildings with solid colors (e.g., green for grass) or reducing complex effects (shadows, splitting bullets, unit buffs, effects of units walking on certain floors like shallow water, etc.), as these are less noticeable. This feature could be added to both the game and the map editor (especially the latter, as it often requires smaller zoom levels).

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It just improves performance with minimal cost. You can enjoy the details at high zoom levels, or quickly shift focus and enter RTS mode at lower zoom levels, even though you might not allow a feature that enables zoom levels smaller than the minimap’s minimum zoom level to be included in the vanilla version. However, purely performance optimizations will not affect anyone, especially since you can add a toggle to let players decide for themselves.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by JackAtak1103** [comment]
This in theory sounds like a great idea... IDK much about LOD but it sounds like it might be hard to implement.
