### ISSUE TITLE
Major balancing changes

### ISSUE THREAD

**Issue by KOCTOLOM** [Anuken/Mindustry-Suggestions#5328]
### Describe what you would like changed, and why.

I wrote this because I think balancing of Serpulo and (partially) Erekir isn't perfect.

There are few issues in Erekir, but I'd like to point out that **Vanquish** has too low ram damage (and pretty low dps compared to other t4 units), and **Precept** has none of it ( ram damage can make it more usefull among other t3, now its outclass in damage+mobility with **Obviate*). Also **Conquer** can't utilize its large ram and average ranged damage potential due to lack of some sort of survivability.

it's pretty much all for Erekir for now.

Serpulo, on the other hand, has a lot more problems:

1. Bad usage of _armor mechanic_.
It reduces damage by a flat amount, up to 10% of the original damage. 10% is a lot, which often allows to deal with heavily armored targets with high amounts of low damage.
Suggestion: reduce minimum damage cap to unit's max HP / reduce min dmg cap to 5% or less.

Vanilla units also have way too _low armor values_ - even 18 armor reduces damage by up to 20-30% of relevant turrets of that stage of the game, which more often than not doesn't really impact the outcome, cuz reducing ~2k DPS vs a 20k HP unit by 30% will only make a difference of at most 2 seconds.
Suggestion: buff units' armor - T1: 0-3, T2: 5-7, T3: 10-12 (less for flying units), T4: 13-20, T5: 25-32.

(Also I'd be glad if modded turrets and units could have variables for: ignoring a certain amount of armor, mass multiplier and turn acceleration) 

2. Status effects ignore armor.

A _combination of lightning and water is busted_. Surge alloy Swarmers and Cyclones outclass everything else and are only weak to T5 swarms. This combo also is relatively cheap and not dangerous to handle, unlike blast + cryofluid combo (storages can just explode and destroy def).

Solution: nerf this combo's damage / make armor absorb some of status effects' damage.

3. T5 outclassed ways of damaging

Unlike Erekir, Serpulo has another problem of relevancy of some T5s.

**Corvus** is very strong due to its range, thus easily outmatching other ground units.

On the other hand we have:

**Toxopid** is easily killable at melee range (which is its own effective range too), and artillery is useless if shot at a couple of Segments.

**Scepter** & **Reign** are just outclassed by others' attack range, mobility and DPS all at once.

Solutions:
Add _hittable: false_ to **Toxopid**'s main artillery shell to reduce Segment's effectiveness, but reduce attack speed by 10-15% (it can be stopped via force fields). Increase its health by 3-5k. Buff leg damage to further improve its melee damage.
**Scepter**: add +1 pierce but reduce lightning damage.
**Reign**: rework reign main weapon reducing piercing to 2/3 and make it pierce buildings, also make _fragOnHit: false_ and increase projectiles' lifetime for better range. (it can make reign the strong foe, which focuses on damaging logistics & mend projectors)

T5s might be immune to Shocked & Blasted for better survivability.

Such changes coupled with armor buff will help divide high tiers into different roles:
**Toxopid** will be melee-oriented with good survivability.
**Reign** will deal point building damage thanks to wall piercing.

And **Scepter** will be able to compete with other T4s.

Less obvious problems:

**Nova** in fact isn't much different from **Dagger** in PvE scenarios, I wish they had some kind of _difference_.

Solution: **Nova** gets +30% reload but +30% damage so that DPS is unchanged and a unit will be more burst damage centered.

**Oct** is a weak T5 which oftentimes isn't worth making, expanding its offensive or defensive functions should make it more useful.

Solution: **Oct** gets a building repair aura / a repair mount instead, and maybe give him some heal percent to make it more useful in offense.

Turrets have a lot of ammo options, but most of them aren't much different from each other, they can be given special use cases, not some secondary effects.

Suggestion: **Blast Compound** - lower fire rate, but higher base damage; Plastanium - higher avg damage, with AP frags; Spectre's Pyratite ammo may be reworked to not pierce and split into frags instead for crowd control and so on. Ripple might get some slowing ammunition to be viable as late-game debuff.
**NERF MEND PROJECTORS**: walls in front of them literally tank everything if spammed, with 3k-4k heal per second. Also its boosted version is literally never used.
Solution:
a) _Reduce range_, leave boosted range unchanged.
b) Add maximum _regen cap_ so spamming isn't as viable now.
Launch Pads are a direct problem of Serpulo campaign, because you can essentially transport infinite resources everywhere.
Solution: Add a resource cap for vulnerable sectors. (i.e. 900 resources per wave (2 minutes), or 7.5/sec

I'll finish for now, there's a lot of things already. Let me know in interested in any of this.

### Describe the changes you want to propose. Include possible alternatives.

In the text above

**Comment by jehosula** [comment]
bring that up in #balancing in the discord server

**Comment by a-a-Cat** [comment]
нет, balance is fine

**Comment by jehosula** [comment]
> нет, balance is fine

not rly
