### ISSUE TITLE
New planet and units? 

### ISSUE THREAD

**Issue by Dragon7227** [Anuken/Mindustry-Suggestions#5331]
### Describe the content or mechanics you are proposing.

New planet and mechanic olny water? Ship carrer 
Battlespace ship and new ore war of see lava see or acid and new units erikir and surpulo. Surpulo tank? And carrer aircraft can build aircraft unit tier 3 or 4 and building can build on water I don't no but you Like? 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Possible player like. New planet units but the game can big and bug? Lag? I don't no and the game get need to update, last time update 2023 game not boring the game have mods the player fun. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
it would be too much, the dev himself said erekir burned him out and confirmed that a third planet would never be made

**Comment by Dragon7227** [comment]
Oh whether to add new units

Pada Kam, 21 Nov 2024, 20.50, jehosula ***@***.***> menulis:

**Comment by jehosula** [comment]
> Oh whether to add new units 

for units it's probably just gonna be unnecessary bloat to either planet, existing units can just be made more unique
