### ISSUE TITLE
make minArmorDamage calculation yield constant output

### ISSUE THREAD

**Issue by Frolonov** [Anuken/Mindustry-Suggestions#5334]
### Describe what you would like changed, and why.

There's minArmorDamage = 0.1 in Vars.java, 
while in Damage.java:
"return Math.max(damage - armor, minArmorDamage * damage)"

Unit still takes considerable damage (10% of the DPS) when facing fast reload weapon or those with lots of frag bullets although "armor > bullet damage". 

Heavy armor units, especially slow ground units, become even easier to take down when defender has coolant & overdrive to boost turret reload, let alone multiple turrets fire at the unit at the same time(10% DPS still being OP compared to unit's HP).

### Describe the changes you want to propose. Include possible alternatives.

To make heavy armor actually useful,
use minArmorDamage alone as actual damage when armor > bullet damage,
"return Math.max(damage - armor, minArmorDamage)"

It makes heavy armor unit (20~40 armor) actually able to last long enough against fast reload turrets.

Alternatively reducing minArmorDamage down to 0.02 without changing "minArmorDamage * damage" expression.

**Comment by jehosula** [comment]
did we agree on this in #balancing ?

**Comment by Frolonov** [comment]
> did we agree on this in #balancing ?

It's not possible to get every player's agreement before making suggestions though.
Currently "armor > bullet damage" is a rare case on serpulo and there's been discussion to make serpulo unit armor ramp up steeper so "unit vs turret" is not mostly "HP vs DPS".
