### ISSUE TITLE
Level improvement in a couple of clicks

### ISSUE THREAD

**Issue by Pupirish** [Anuken/Mindustry-Suggestions#5336]
### Describe the content or mechanics you are proposing.

(I stole the idea from Factorio). You can add a level upgrade conca. If you click on it, you can select the zone, as with the copy button. After the allocation of the territory, a window pops up in which you can select buildings that can be upgraded to the next level, or replaced with others (for example: select a ton of conventional conveyors in a couple of clicks and change them to titanium, reinforced or plasteel; mechanical drills to pneumatic, or 4 drills (pneumatic or mechanical) to an air drilling rig)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There will be less routine

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
i am sure it's more satisfying and overall more controlled to manually upgrade blocks, there is really not much need or this feature at all considering how much you have to go through to really make it work

**Comment by Pupirish** [comment]
Hmm, you're right, after all, we don't have so many buildings that can be improved, so there's not much point in that (

**Comment by merll002** [comment]
You can do this with foo's client. type !builder all in chat

**Comment by jehosula** [comment]
> You can do this with foo's client. type `!builder all` in chat

fool's client should not be a reason to add/not add something but ig it will be an example of how it'll go

**Comment by merll002** [comment]
I'm adding it as an existing solution
