### ISSUE TITLE
Building mechanic rework

### ISSUE THREAD

**Issue by 1justsomeone1** [Anuken/Mindustry-Suggestions#5337]
### Describe what you would like changed, and why.

1. Change building at multiplayer, because its hard to cooperate with other players.
2. Rework assist units building mechanic, because they are slowly move and rotate so you must endure their pauses while building bunch of structures or making base across the map.
3. Also change health of buildings under construction. Right now any damage (except for core units) instantly destroys almost built structure
4. We need replace mechanic. Currently you must replace conveyors and small nodes with their better variants on your own. This is annoying.

### Describe the changes you want to propose. Include possible alternatives.

1. Make building plan common for all players or make plans of other players visible.
2. When you press the hammer icon support units build your plan individually, instead of assisting you.
3. Make health of structures under construction equal to the stage of construction.
4. Add replace command. When you press some button (maybe L) and choose area two squares will appear. In left you can choose what structure will be replaced and in right the new structure. Empty square counts as air (If left is empty — place specific building at free space, if right — destroy specific building). You cant choose buildings with different sizes.

**Comment by Pupirish** [comment]
Everything is quite logical, except for the last point, I would say that it would be cool to make the amount of health of a building under construction proportional to the stage of construction

**Comment by 1justsomeone1** [comment]
> Everything is quite logical, except for the last point, I would say that it would be cool to make the amount of health of a building under construction proportional to the stage of construction

That probably was what i mean. Im just not very good at English

**Comment by Pupirish** [comment]
You're not the only one here. 😁

**Comment by jehosula** [comment]
for 1 i wonder how it will be code wise
for 2 it's intentionally supposed to be that way and the developer does not wanna change it
for 3 the worst it does is make it harder to interrupt building than it should be cause you have to deal decent amounts of damage
for 4 a mix of 1 and 2's reasons including i find it more fun to manually replace instead of one button for a huge area

**Comment by 1justsomeone1** [comment]
> for 1 i wonder how it will be code wise for 2 it's intentionally supposed to be that way and the developer does not wanna change it for 3 the worst it does is make it harder to interrupt building than it should be cause you have to deal decent amounts of damage for 4 a mix of 1 and 2's reasons including i find it more fun to manually replace instead of one button for a huge area

1.  In this case building plan should atleast visible. I dont think its too hard
2. If you want to be assisted you press pawn icon. Hammer supposed to build but not follow you
3. Its annoying when dagger bullet destroys almost built wall
4. Its very easy to code and useful. Its boring to always replace nodes and conveyors at new save and especially at servers
