### ISSUE TITLE
Range for some structures

### ISSUE THREAD

**Issue by 1justsomeone1** [Anuken/Mindustry-Suggestions#5338]
### Describe what you would like changed, and why.

I think overdrive, mend structures (also maybe processors and nodes but Im not very sure) need another range. They are very inconvenient due to their circle range. You must place them in specific pattern or very close to each other if there isnt much free space

### Describe the changes you want to propose. Include possible alternatives.

Make their range square with the same lenght. Some will not like that, but... Why not?

**Comment by Pupirish** [comment]
It would be possible to make a choice of the de-range yourself (square or round), but the square one should be made slightly smaller than the round one, so that there would not be much imbalance
