### ISSUE TITLE
Host multiplayer games

### ISSUE THREAD

**Issue by Abdulrhman64** [Anuken/Mindustry-Suggestions#5346]
### Describe the content or mechanics you are proposing.

Host your own private server to play with friends 
If you want to make it public you can
Please

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

WHY NOT

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 1justsomeone1** [comment]
Bro just download scheme size with ingame browser. Anuke cant support free servers

**Comment by camelStyleUser** [comment]
ah yes why not make anuke pay for servers

**Comment by jehosula** [comment]
> ah yes why not make anuke pay for servers

exactly, he can't afford it on what he earns for the game

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/1153#issuecomment-725813205

Wow, a 4 year old comments still applies, who knew?

**Comment by Abdulrhman64** [comment]
> ah yes why not make anuke pay for servers
Wait you pay for servers
I mean you create your own servers not anuke

**Comment by Abdulrhman64** [comment]
Ok why doesn't he make micro transactions or stuff like that

**Comment by sulillll** [comment]
This function can be implemented with a module

**Comment by jehosula** [comment]
> Ok why doesn't he make micro transactions or stuff like that

micro transactions suck, and you can also make your own server if you are willing to set stuff up
