### ISSUE TITLE
surge alloy cost change and minerals to scrap

### ISSUE THREAD

**Issue by walksanator** [Anuken/Mindustry-Suggestions#535]
**Describe what you would like changed, and why.**
change the build cost of surge constructor to no longer use thorium and instead uses plastanium and titanium
a scrapper which can scrap ores (will always be like 5 copper to 1 scrap or something horrible that is not worht it in most situations but is good recycling)
**Describe the changes you want to propose. Include possible alternatives.**
surge constructor contains titanum only and lots of copper and lead
scrapper will constantly consume power whilst in use even if nothing is in it
(this is technically a feature request but changing cost is also balancing/fed back so idek)

**Comment by Anuken** [comment]
> surge constructor contains titanum only and lots of copper and lead

Without any justification? No.

> a scrapper which can scrap ores

This is horribly broken in terms of balance.

**Comment by potatoisagender** [comment]
#190
