### ISSUE TITLE
Learning helper / tips and documentation menu

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry-Suggestions#5351]
### Describe the content or mechanics you are proposing.

I am proposing that a learning helper similar to those present in Factorio and RimWorld be added. I think that the learning helper should detail on mechanics more in-depth than the simple tip popups that you get upon doing something for the first time, for the purposes of allowing one to refer back to relearn and review things.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that a learning helper would improve the game by providing a method for players new and experienced alike to refer back to previous knowledge. As of right now, the tip popups only appear once and are limited in number. Not only can they not be referred back to, they don't explain mechanics in-depth. I think that providing a menu wherein one can review previous concepts and reassess things would address this game's unfriendly nature towards new players.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment]
i'd assume this could be linked to the core database and the info button in some way considering it's another information center

**Comment by overdramaticpanromantic** [comment]
> i'd assume this could be linked to the core database and the info button in some way considering it's another information center

yeah, probably another option in the main menu near the core database
