### ISSUE TITLE
Foreshadow damage

### ISSUE THREAD

**Issue by EnynCait** [Anuken/Mindustry-Suggestions#5355]
### Describe what you would like changed, and why.

Okay, foreshadow is getting a debuff of 60% damage cap, meaning any unit under 1250 health is going to need 2 foreshadow shots regardless of their health(not including their shields) along with a new ammo type.
The setting is good as it would waste a lot of ammo when it's being used against low tier units.
As for the reason of my suggestion? Just to make the noobs suffer a lot more....

### Describe the changes you want to propose. Include possible alternatives.

My suggestion is very much like the one which is getting implemented....
I think it would be a great idea to make the damage dependent on the max health of the unit being attacked with a bit of static damage. Doing calculations, I think **[**300+4.2%*(max health)**]** would be good and won't break the game balance.
In v7 foreshadow needs 20 shots to defeat a reign ignoring all the status and healing effects. With this new damage though, it would take 19 shots from a foreshadow to defeat a reign. And well, the more health a unit has, the more damage would foreshadow deal and Units having less than 314 max health would be one shotted(meaning all the t1s) T2s would generally need 2 while T3s would generally need 3 shots to destroy, not including any status or shield.

**Comment by jehosula** [comment]
> well I got from community that a new type of ammo would be introduced for foreshadow(internally referred to as _RailBulletType_).

ah i thought you meant an ammo item, yeah it's railbullettype iirc, i am pretty sure it dosn't need a drastic rework like this suggestion after the already existing nerf

**Comment by EnynCait** [comment]
> > well I got from community that a new type of ammo would be introduced for foreshadow(internally referred to as _RailBulletType_).
> 
> ah i thought you meant an ammo item, yeah it's railbullettype iirc, i am pretty sure it dosn't need a drastic rework like this suggestion after the already existing nerf

Hmmm, tru but it would just make it better for even op mods and well lower tier units would make the turret waste a lot more ammo and more importantly it is both buff and nerf.

**Comment by jehosula** [comment]
> Hmmm, tru but it would just make it better for even op mods and well lower tier units would make the turret waste a lot more ammo and more importantly it is both buff and nerf.

ye it's partially a rework but more of a nerf cause it allows the turret to actually be blocked
