### ISSUE TITLE
Improved PvP, unit management system

### ISSUE THREAD

**Issue by univeeum** [Anuken/Mindustry-Suggestions#5360]
### Describe the content or mechanics you are proposing.

I feel like the unit management system was added over a year ago and it still sucks (So PvP in RTS game too). I propose to solve most of the inconveniences due to which players do not prefer to update the game. 

**Firstly add hot buttons for selected units.** 
Something like A - Attack the closest target to the cursor, D - hold the position (attack if a unit approaches, etc.) and maybe one button G - for example, just shooting in the direction of the cursor? It's still much more convenient and important to switch modes on the keyboard. Of course, it is possible that these buttons are already occupied, but you can change them to something else (after all, as for me, managing groups in an RTS game is more important than managing a player on WASD). 

**Secondly**, I think there was often a problem that you sit in a unit, go with your army to destroy your friend and he simply kills the unit in which you are sitting and the army is left without control and it just dies... Why can't you just make it so that your character stays at the base and controls groups without having to move around the map? (I know that the game has a function called pan camera (free cam), but it's set to the 4th mouse button by default, ahaha) !Of course, no one has such a mouse, and setting it to the mouse wheel or other buttons is also inconvenient, you just have to constantly hold this button, and if you accidentally let go, everything is lost... It would be much more convenient if your camera itself stayed on the controlled groups. Or maybe a good solution was to not hold down the key for the free camera, but to press it once to turn it on.

Of course, it's better to add new maps to the campaign than to add more PvP maps. I just have a question why is there so little attention to PvP in this game? The game has been around for 5 years, but it does not have normal maps for PvP. I have completed a maximum of 10 levels in the campaign, because it is not as interesting as playing PvP with friends (or as it was possible on the server before). Why does no one understand that the game breathes and lives on this mode?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

New pvp maps, adequate unit management system in the RTS game - all this is what should be in any RTS from the very beginning.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by AVeryCoolSpider-PL** [comment]
This is a very good idea in my opinion. I have thought of one more thing though: in BE builds there is the patrol command. I wish it also had an option "chase unit if spotted" and then "return to patrolling" after destroying the targeted unit or maybe letting it go if it goes away from the core.

**Comment by a-a-Cat** [comment]
> ...managing groups in an RTS game is more important than managing a player on WASD.
Over half of the sectors have no enemy bases, so the only units most players will produce are monos, polys and megas. Those units do everything they are supposed to do without the RTS controls so those controls go unused in those sectors. Moving around the unit you use to build is done in literally every sector because of the limited build range.
> Of course, no one has such a mouse, and setting it to the mouse wheel is also inconvenient, you just have to constantly hold this button, and if you accidentally let go, everything is lost...
1. Many people have mice with side buttons, but i agree that it should be a different key by default.
2. It only resets when you move, but having the option to reset it using a specific key instead would be nice.

**Comment by jehosula** [comment]
1 can't you use enter to seperate the stuff so it's more readable
2 for
> I propose to solve most of the inconveniences due to which players do not prefer to update the game. Firstly add hot buttons for selected units. Something like A - Attack the closest target to the cursor, D - hold the position (attack if a unit approaches, etc.) and maybe one button G - for example, just shooting in the direction of the cursor?

A can just be done manually D

3 for
>Secondly, I think there was often a problem that you sit in a unit, go with your army to destroy your friend and he simply kills the unit in which you are sitting and the army is left without control and the it just dies... Why can't you just make it so that your character stays at the base and controls groups without having to move around the map? (I know that the game has a function called pan camera, but it's set to the 4th mouse button by default, ahaha)!Of course, no one has such a mouse, and setting it to the mouse wheel is also inconvenient, you just have to constantly hold this button, and if you accidentally let go, everything is lost... It would be much more convenient if your camera itself stayed on the controlled groups. But until this is fixed, this system will suck.

you can still control your army when dead, it just isn't visible also you CAN control from the base already

4 for 
> Of course, it's better to add new maps to the campaign than to fix this problem. Why is there so little attention to PvP in this game? The game has been around for 5 years, but it does not have normal maps for PvP. I have been playing since 2019 and during all this time I have completed a maximum of 10 levels in the campaign, because it is not as interesting as playing PvP with friends (or as it was possible on the server before). Why does no one understand that the game breathes and lives on this mode?

pvp is managed by the community as it isn't really a thing you add base game content to, the game has been around for way longer than 5 years you don't even know the game's history and there ARE built in pvp maps, also it's 100% been possible to do pvp with friends and in servers
also lastly, the game doesn't rely on pvp just to live, the pve community is still very healthy

**Comment by Juni-0220** [comment]
the one thing i agree with that was mentioned is the RTS camera needs a mode detached from the core ship. even if its a copy of how mobile works

**Comment by a-a-Cat** [comment]
> the one thing i agree with that was mentioned is the RTS camera needs a mode detached from the core ship.

This already exists, it's called freecam.

**Comment by univeeum** [comment]
> 1 разве вы не можете использовать клавишу Enter для разделения текста, чтобы он был более читабельным? ПРАВКА: мой комментарий был очень запоздалым, и вы исправили это [art 2 for
> 
> > Предлагаю решить большинство неудобств, из-за которых игроки не предпочитают обновлять игру. Для начала добавить горячие кнопки для выбранных юнитов. Что-то вроде A - Атаковать ближайшую к курсору цель, D - Удерживать позицию (атаковать, если приближается юнит и т. д.) и может быть одну кнопку G - например, просто стрелять в направлении курсора?
> 
> A можно просто сделать вручную D
> 
> 3 для
> 
> > Во-вторых, я думаю, часто возникала проблема, что вы сидите в отряде, идете со своей армией уничтожать своего друга, а он просто убивает отряд, в котором вы сидите, и армия остается без управления и просто умирает... Почему нельзя просто сделать так, чтобы ваш персонаж оставался на базе и управлял группами, не перемещаясь по карте? (Я знаю, что в игре есть функция pan camera, но она по умолчанию настроена на 4-ю кнопку мыши, ахаха)! Конечно, ни у кого нет такой мыши, а настраивать ее на колесико мыши тоже неудобно, приходится постоянно держать эту кнопку, а если случайно отпустить, то все теряется... Было бы гораздо удобнее, если бы ваша камера сама оставалась на контролируемых группах. Но пока это не исправят, эта система будет отстойной.
> 
> вы все еще можете контролировать свою армию, когда она мертва, просто ее не видно, также вы МОЖЕТЕ управлять ею с базы
> 
> 4 для
> 
> > Конечно, лучше добавить новые карты в кампанию, чем исправлять эту проблему. Почему в этой игре так мало внимания PvP? Игра существует уже 5 лет, но в ней нет нормальных карт для PvP. Я играю с 2019 года и за все это время прошел максимум 10 уровней в кампании, потому что это не так интересно, как играть в PvP с друзьями (или как это было возможно на сервере раньше). Почему никто не понимает, что игра дышит и живет этим режимом?
> 
> PvP управляется сообществом, так как это не то, к чему можно добавить контент базовой игры. Игра существует уже более 5 лет. Вы даже не знаете ее историю. В нее ВСТРОЕНЫ PvP-карты. Кроме того, PvP можно играть с друзьями и на серверах. И, наконец, игра не полагается на PvP только для того, чтобы выжить. PvE-сообщество по-прежнему очень здоровое.

Apparently this is written by a person who has played PVP twice in his life... Why are you writing if you don't read my sentence carefully? What did you want to say from points 2-4? 2 - xd... like I didn't know (by the way, not all the functions I talked about are there) 3 - I just HIGHLIGHTED that after death it causes big problems 4 - come on.. Are PVP maps really built in? Read the post again dude, then write plz. I think there are NOT ENOUGH maps and there is a huge undeveloped potential in PVP mode. Why do they make a huge number of maps for the campaign and never make new ones for PVP? Hahaha, why is this here? - "You don't even know its history."

**Comment by jehosula** [comment]
> Apparently this is written by a person who has played PVP twice in his life... Why are you writing if you don't read my sentence carefully? What did you want to say from points 2-4? 2 - xd... like I didn't know (by the way, not all the functions I talked about are there) 3 - I just HIGHLIGHTED that after death it causes big problems 4 - come on.. Are PVP maps really built in? Read the post again dude, then write plz. I think there are NOT ENOUGH maps and there is a huge undeveloped potential in PVP mode. Why do they make a huge number of maps for the campaign and never make new ones for PVP? Hahaha, why is this here? - "You don't even know its history."

1 i played pvp way more than 2 times

for point 2, ye the wording was confusing but the idea was that it's pretty easy to do manually

for point 3 freecam exists for controlling units while staying in your base and dying doesn't actually prevent you from commanding, just hides the lines and stuff

for point 4 ye there are 3 built in maps that are playable for pvp and you never mentioned that it was not enough, you said there aren't any normal maps
also like i mentioned earlier the community is making the pvp maps you download for or play in servers, and about the "You don't even know its history." that was for correcting the age of the game you specified, it's way older than 5 years

**Comment by univeeum** [comment]
> > Apparently this is written by a person who has played PVP twice in his life... Why are you writing if you don't read my sentence carefully? What did you want to say from points 2-4? 2 - xd... like I didn't know (by the way, not all the functions I talked about are there) 3 - I just HIGHLIGHTED that after death it causes big problems 4 - come on.. Are PVP maps really built in? Read the post again dude, then write plz. I think there are NOT ENOUGH maps and there is a huge undeveloped potential in PVP mode. Why do they make a huge number of maps for the campaign and never make new ones for PVP? Hahaha, why is this here? - "You don't even know its history."
> 
> 1 i played pvp way more than 2 times
> 
> for point 2, ye the wording was confusing but the idea was that it's pretty easy to do manually
> 
> for point 3 freecam exists for controlling units while staying in your base and dying doesn't actually prevent you from commanding, just hides the lines and stuff
> 
> for point 4 ye there are 3 built in maps that are playable for pvp and you never mentioned that it was not enough, you said there aren't any normal maps also like i mentioned earlier the community is making the pvp maps you download for or play in servers, and about the "You don't even know its history." that was for correcting the age of the game you specified, it's way older than 5 years

Yes, at the moment it is really problematic to play three in pvp in mindustry. I even remember looking in the community and it took more than one day to find normal map for pvp. And what does the history of the game have to do with it?) What difference does it make whether I know it or not? If anything, I know that the game existed before 2019, but I play from the first Steam release and here it is still not clear what can be considered its appearance. If anything, I've been playing since the classic version came out and I don't think I'm bad at it.

**Comment by jehosula** [comment]
> Yes, at the moment it is really problematic to play three in pvp in mindustry. 

wdym with this?
> I even remember looking in the community and it took more than one day to find normal map for pvp. 

which place did you look in? searching "pvp" in the discord server should give you a decent map way faster
for the rest of what you said, ye it wasn't meant to go that far, it was just correcting something and then it somehow got to this

**Comment by univeeum** [comment]
> > Yes, at the moment it is really problematic to play three in pvp in mindustry.
> 
> wdym with this?
> 
> > I even remember looking in the community and it took more than one day to find normal map for pvp.
> 
> which place did you look in? searching "pvp" in the discord server should give you a decent map way faster for the rest of what you said, ye it wasn't meant to go that far, it was just correcting something and then it somehow got to this

I searched both on discord and on the internet. It's hard to find a map for an odd number of players, at least for three. But what difference does it make where it went?? If a regular player can't find it (I have many examples besides me) then what is there to talk about at all? Just why isn't this in the game? That's the only reason we're writing this here, isn't it? Looking at your words, it seems to me that you came here for criticism, not for achieving some result. I don't see any point in talking there to you anymore.

**Comment by jehosula** [comment]
> I searched both on discord and on the internet. It's hard to find a map for an odd number of players, at least for three. But what difference does it make where it went?? If a regular player can't find it (I have many examples besides me) then what is there to talk about at all? Just why isn't this in the game? That's the only reason we're writing this here, isn't it? Looking at your words, it seems to me that you came here for criticism, not for achieving some result. I don't see any point in talking there to you anymore.

ah, a map for an odd number of players, those are uncommon for good reason, also what result are you trying to achieve? if you are proposing adding built in pvp maps then suggest ones that wouldn't feel too out of place from the current ones already in the game
