### ISSUE TITLE
Crawler rework

### ISSUE THREAD

**Issue by 1justsomeone1** [Anuken/Mindustry-Suggestions#5363]
### Describe what you would like changed, and why.

Currently crawler is pretty inconvenient unit. In contrast of its name its cant walk over structures, instantly destroys nearby any enemy building (even conveyors) and just weak.

### Describe the changes you want to propose. Include possible alternatives.

Add a two unique commands for crawler to command mode - «Explode when enemy structures is nearby» and «Dont explode».
Add choice of what type of explosives will crawler use - if you put for example spores instead of coal into ground factory then crawler will have spores in inventory. Spores have 115% of flammability and 0% of explosiveness, so crawler will leave a big amount of fire after explosion and deal no or little explosive damage. Same with coal, pyratite, blast compound, surge alloy and probably other materials. Currently you can do same in game, but you must posess into unit and grab items from core, which wastes a lot of time and also makes the explosion not much stronger.
Also let it walk over blocks like other units of its tree

**Comment by jehosula** [comment]
crawler should be good enough in the BE versions of the game cause hold fire exists, solving the crawler exploding when you don't want it to and that alone makes it great, for auto loading units, logic exists and why should it have to be added automatically like this, walking over blocks will def make it insane after V8 comes

**Comment by 1justsomeone1** [comment]
I haven't checked BE
