### ISSUE TITLE
Add option to disable pause on lost window focus

### ISSUE THREAD

**Issue by MetaMuffin** [Anuken/Mindustry-Suggestions#539]
Add an option to make the game not pause when it loses focus.
I consider this useful as it allows me to use application on a second monitor or another desktop while playing.
Thanks

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by here-be-username** [comment]
That would be awesome. Sometimes, I get tired of waiting to build up thousands of surge in the core, and would like to do something else while I wait for said surge to be produced.

**Comment by arkhne** [comment]
I have never had the game pause on focus loss. Are you sure it's not a configuration issue on your end? In fact, I have the game on a second monitor right now, and it's not pausing while I type this.

**Comment by MetaMuffin** [comment]
Then this might even be platform dependent. I use Linux with i3 as a window manager. If this works everywhere else I am sorry that my setup is just not working as intended.
Also a quick note: I don't want this feature to be used to afk for very long because that wouldn't improve the games strategy ( and also be something like speeding up game speed).

**Comment by arkhne** [comment]
That could be it. I am using Win7. Could be the way it is running on Linux. Some windows programs default to using less resources on focus loss, which causes things running in them to pause, even if they don't have that ability. I could certainly see this happening on Linux, too.

**Comment by ToiletGaming3000** [comment]
For my problem, if you have 2 windows in split screen (one is Mindustry and one is whatever), Mindustry pauses. And I can't idle for some reason. It's not a bug.

**Comment by ToiletGaming3000** [comment]
nvm, I fixed it, In the settings, disable pause on background.
