### ISSUE TITLE
Turrets and Systems.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#54]
Turrets.
Aims to make other turrets useful.

Least used Turrets:
Duos (Very early game turret, Easily Upgradable)
Scorch
Hail (Yes Hail, Bad in a few maybe okay with a lot but not really)
Waves (Against enemies)
Fuse
Spectre

As to why the reasons vary, but mostly due to other turrets are simply better.
[To be updated based on additional feedback]

Proposed Changes:
[To be updated]

**Comment by itcannotbe** [comment]
Closing due to significant changes to turrets and units made.

**Comment by BlueWolf3682** [comment]
(scorch sucks more now)
