### ISSUE TITLE
Let Processor Toggle Power Nodes

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#540]
**Describe the content or mechanics you are proposing.**

What if processors can `control` power nodes? You can disconnect an area of factories/projectors from the power grid. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Example use case: to disconnect all energy weapons in between waves, so that power may build up in your Battery matrix. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Isn't that complicated?

It's easier to disable the building or use a battery diode and disable that.

**Comment by Daniel-Chin** [comment]
> Isn't that complicated?
> 
> It's easier to disable the building or use a battery diode and disable that.

That sounds right. Closing the issue now.
