### ISSUE TITLE
Dynamic Shadow Casting according to Planet-Star Orientation

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#541]
**Describe the content or mechanics you are proposing.**

So we already have day-night cycle. Things look pretty at night.  
Why not let the planet spin slowly according to the day-night duration?  
Units cast shadow realistically, according to the angle of the star.  
At sunset/sunrise, units (and maybe walls) cast long shadows, creating scenematic gameplay.  
Hopefully, an efficient fake-3D shadow drawing algorithm can be found.  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Things will look prettier. The shadow will not always be in the same spot anymore.  

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
There isn't even the concept of shadows in-game.

**Comment by Daniel-Chin** [comment]
> There isn't even the concept of shadows in-game.

For example, the player has shadow.

**Comment by itcannotbe** [comment]
Those aren't even shadows.
There just shapes that just follow units around.

Buildings don't even have shadows.

**Comment by Syncinus** [comment]
Yes, but buildings could have shadows.
