### ISSUE TITLE
Discourage people from using doors as walls

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#542]
**Describe what you would like changed, and why.**

Currently, player that don't have titanium but have access to coal and sand use doors as walls (due to them having higher health than copper walls). I don't think doors should be used this way. 

**Describe the changes you want to propose. Include possible alternatives.**

Multiple solutions including: 
- nerfing door hp
- buffing copper wall hp
- adding a "graphite wall" with more hp than a door
- reworking the door to have the health of the walls around it (If no walls around, se health to less than copper wall)

**Comment by Anuken** [comment]
Making them use titanium is the simplest solution.

**Comment by genNAowl** [comment]
> Making them use titanium is the simplest solution.

Bruh I can't believe I didn't think of that.
