### ISSUE TITLE
6.0 Random Maps and Access to Resources

### ISSUE THREAD

**Issue by Draco18s** [Anuken/Mindustry-Suggestions#544]
Currently the landing zone on random maps is fixed (once the map has been generated and visited, all future visits will start the core in the same location) and aside from the 2 copper drills that start with your base, access to copper can sometimes be very difficult.

Suggest altering either the core landing spot to prioritize a location near a procedurally generated copper deposit of sufficient size, or include an unbuilt-on copper deposit as part of the landing alterations (similar to the 8 tiles that generate under the initial drilling platforms).

**Comment by here-be-username** [comment]
There should always be copper (and lead) within manual mining range of the core. Without, the start gets super annoying (flying back and forth is not fun), and that's boring and not fun. I think that generating a ore deposit within 10 or so blocks of core would probably work, and look ok.
