### ISSUE TITLE
Player's Vision Zone Clears Sandstorm Effect

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#546]
**Describe the content or mechanics you are proposing.**

At night, the player emits light, so that they can see nearby stuff. This is really nice.  
Why not do this to the sandstorm effect too? The effect would be transparent within a radius of the player.  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently, Coal on Dark Sand is really hard to see in a sandstorm at night:  
![image](https://user-images.githubusercontent.com/34157591/93692301-f1f4c980-fb23-11ea-82b2-b9722df4e55d.png)  
With this new feature, the game experience can be improved.  

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
That would cause a lot of lag, and simply is not going to happen.
