### ISSUE TITLE
[V6] Mono drones unable to mine in weather change.

### ISSUE THREAD

**Issue by 1Night101** [Anuken/Mindustry-Suggestions#549]
**Describe what you would like changed, and why.**
The mono drones CAN NOT, mine if the weather is moving the drones too much. They will just stand in place.  

**Describe the changes you want to propose. Include possible alternatives.**
I would like a weather change or just increase the speed of the drones as they are unable to mine because of the weather conditions, Im not sure if this intentional but i am someone who used to rely on the draug (now mono) drones ALOT,
I am sending a video to demonstrate more clearly. 
It could be made so that the drones do not get affected by weather.

https://www.youtube.com/watch?v=3tQMXzA2DwM&feature=youtu.be

**Comment by kingb74** [comment]
Yea it maybe should slow them down but not wnough to make them useless

**Comment by Anuken** [comment]
This is basically a bug.

**Comment by 1Night101** [comment]
> 
> 
> This is basically a bug.

Could you show me where to report bugs for next time please?

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/issues/new/choose
