### ISSUE TITLE
Make other turrets great.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#55]
Turrets.
Aims to make other turrets useful.

Least used Turrets:
Duos (Very early game turret, Easily Upgradable)
Scorch
Hail (Yes Hail, Bad in a few maybe okay with a lot but not really)
Waves (Against enemies)
Fuse
Spectre

As to why the reasons vary, but mostly due to other turrets are simply better.
[To be updated based on additional feedback]

Proposed Changes:
[To be updated]

**Comment by itcannotbe** [comment]
Duplicate

**Comment by MEEPofFaith** [comment]
*It seems as if you haven't tried mass Fuse spam before.*

**Comment by itcannotbe** [comment]
> _It seems as if you haven't tried mass Fuse spam before._

Fuses are great but their lack of range prove useless against higher ranged enemies.

**Comment by Syncinus** [comment]
Fuse is incredibly OP, buffing them would be bad.

**Comment by MEEPofFaith** [comment]
_*Have you tried killing a Reaper with mass Fuse spam before?*_

**Comment by itcannotbe** [comment]
I do but it involves you actually luring them into their range. Not fun.

**Comment by MEEPofFaith** [comment]
n o n

**Comment by Daniel-Chin** [comment]
Duo's damage output to boss units shall not be underestimated. If you calculate damage per second **PER TILE**, Duo actually dominates a lot of other non-AOE turrets, even when supplied with copper.
