### ISSUE TITLE
Don't mind me, just brainstorming new units

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#550]
Oh hi, it's me, iLag, and I'll just brainstorm some units. This is based on the fact that all can have up to four colours - there are three for Ground, one for naval and two for air; yellow, green and purple. Looking at the list of possible units [dagger, crawler and the green one], it seems that enough space for one more unit. I'll take this colour as White, although it could be any colour at all.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Well, first of all, here's what I thought of:

Ground:

- White: Rovers. Could not fly at all, and `Left Shift` would just speed it up for a short amount of time. Could ~yeet~ ram itself into ground units to damage them - most damage from the side, least head-on. Damage could also depend on the speed of the rover. Idk why this isn't implemented yet, rovers, imo, would be an obvious choice for ground units.
Suggested Name-series: Past Lunar rover missions: example, Yutu, Lunokhod, Carnegie, etc.

Air:

- Purple: Spy Planes. This is an idea I got while going through other suggestions, when I found this: https://github.com/Anuken/Mindustry-Suggestions/issues/498. Since fog-of-war and this one compliment each other, I decoded to go with it - Spy planes were typically much stealthier than gunships. Having a Radar which gave away your troops coming towards the enemy would be a problem, right? Wrong, the spy plane could travel much faster and be nearly invisible until hit or until it fires on an enemy, or until it gets *very* close to an enemy ship or turret. This would pave the way for the reconstructed version of the spy plane, which could possibly use its `G` or `Left Shift` ability to scramble or jam enemy radars that it's close to. Radars don't seem too much of a problem anymore - just assume control of a spy plane, stealthily go into an enemy base, scramble their radars and boom, they'll never see you coming. Scramblers could also be used to make turrets malfunction, or to make ships malfunction; either to cut off their sight entirely or to make them lose control of movement or building - one would risk exposing himself to the enemy for this, though.
- White: Drone. Any ship in the game, as of now, needs to turn itself around completely to fire [exception - beta and Horizon] and to move in said direction with its maximum speed, as, in all fairness, all aircrafts do, with one exception: Helicopters and similar drones. This would allow the aircraft to move in any direction without much delay in turning around. Having a turret-weapon [like that of Beta] would go well with this, since it complements the design of it.

Naval:

- Green: Support ships: Could drop small packages in the water with it's `G` ability, which could be picked up by allied ships to regain health [maybe also transportable by 'Mega' dropship]. Final tier could be like a naval Quasar, as in it would support nearby units - by increasing their rate of fire and periodically healing them with the health packages.
- Purple: Offense-support ship. Just like the Green support ship could drop health packages, the Purple ship could drop Mines with its `G` ability. Built for pre-determined combat more than direct, these mines could take a while - say, ten seconds - to be primed, and then detonate if any ship passed near it, possibly killing it, if not seriously damaging it. A good fleet of these ships could turn the *tide*, no pun intended, of the battle. Since ship controls are a bit, er, floaty[?], dodging large clumps of naval mines might be a hard task. 
- White: Submarines. With their `G` ability, these submarines could dip into water, turning invisible to enemies, at the cost of losing vision of anything outside of arm's reach. Naval mines would also detonate if a submerged submarine is close by, giving them another purpose. Larger submarines could shoot mines to prematurely detonate them, hence also acting as minesweepers.

That's about it. If you're Anuke, do tell me if any of these are worth adding, and if you're not, do give feedback or smth.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
> ~~yeet~~

so i see you're a man of culture as well

**Comment by Ferociousfeind** [comment]
I like the idea of a few wheeled vehicles, something quick and agile, but has to use naval movement limitations (can only move forward, and can only turn while moving) except with the added bonus of being able to drive backwards too.
