### ISSUE TITLE
6.0 Campaign Loadouts 

### ISSUE THREAD

**Issue by djradnad** [Anuken/Mindustry-Suggestions#551]
**Describe what you would like changed, and why.**
Would like to bring items into secured sectors.
Currently, in 6.0 campaign, you cannot bring a loadout to sectors that you have already secured. Because of this, depending on the order that you complete sectors, you may miss your chance to bring higher tier items into the sector, whereas you would normally be able to, especially if you plan ahead. Even then u still run into a choice of which sector to sacrifice having the mats in depending on your order. Would be much more enjoyable to simply be able to bring them whenever instead of needing to do multiple playthroughs in order to play with each mat on every map. 

**Describe the changes you want to propose. Include possible alternatives.**
Be able to bring mats into secured sectors either via a loadout prompt, or being able to unload global mats from your hub once the sector is secured.

**Comment by RogueRedHawk** [comment]
Afaik global mats are going away. All resources will be stored locally in sectors and launchpads will be reworked to allow you to move resources to secured sectors.

**Comment by RogueRedHawk** [comment]
Check the Trello

**Comment by djradnad** [comment]
will do, thanks

**Comment by Anuken** [comment]
Launch pads will move items between sectors once they are properly implemented.
