### ISSUE TITLE
Increase Poly unit's assist detection range

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#552]
Poly unit does not fly to assist a player if they are far away (especially if moved away by the storm weather).
I suggest increasing their build detection range or alter their AI to follow a player in a similar way Phantoms did.

Video file of the issue: https://cdn.discordapp.com/attachments/414179246693679124/757305424918872064/poly-range-too-low.mp4

**Comment by A5TR0spud** [comment]
Following was annoying, so I think the range should be increased.
