### ISSUE TITLE
Dynamic size of the core resources UI is the problem sometimes

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#554]
Core resources UI is shaking too much when resource numbers change.
Possible fix is separating resources by the grid with even sector sizes.
~~I know it's still WIP~~

Video demo: https://cdn.discordapp.com/attachments/752272276912865280/757316672242712676/bandicam_2020-09-20_21-43-13-872.mp4

**Comment by potatoisagender** [comment]
this might apply here: https://github.com/Anuken/Mindustry/issues/new/choose

**Comment by Anuken** [comment]
> this might apply here

It's not a bug, so no.
