### ISSUE TITLE
Transparency drill feature

### ISSUE THREAD

**Issue by EG0RIST** [Anuken/Mindustry-Suggestions#555]
During selection, drills must be translucent to see that there are no unnecessary blocks under it

Mining scrap instead of sand, because you missed 1 scrap tile - common thing. With that feature there will be less pain for people.

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/93722353-2daf8380-fb64-11ea-8529-174565498137.png)

Drills already display the resource they will mine upon placement. This should not be necessary.
