### ISSUE TITLE
Feedback on grey unit outline

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#556]
**Describe what you would like changed, and why.**
A couple people, me included dislike the look of the new grey unit outline, used to see unit guns more clearly. Some people like it some dont. I think the ability to enable/disable unit outlines in graphics settings would make everyone happy.

**Describe the changes you want to propose. Include possible alternatives.**
As before, the ability to toggle grey unit outlines via graphics settings.

**Comment by Anuken** [comment]
> the ability to enable/disable unit outlines in graphics settings

This is not happening. I will not make (more) significant visual settings options; this essentially means I have two maintain *two styles at once* and make sure neither have problems or visual bugs. Either outlines should be a core part of the game's style, or not at all.
