### ISSUE TITLE
Some Ideas about Satellites

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#557]
**Describe the content or mechanics you are proposing.**

I saw on Trello that Satellites may be added to the campaign in the future. Here are some ideas. 

* Satellites sound like they should be global, i.e. shared between sectors.  
* Resource uplink and downlink. You can download resources to Ground Zero (?)  
* Resource sharing between multiple players in the campaign.  
* Oribital bombardment (mentioned on Trello) and orbital airdrop (??)  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Just expanding the notion of a satellite as a game element here.  

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
isn't orbital airdrop basically launching of core?

**Comment by Daniel-Chin** [comment]
> isn't orbital airdrop basically launching of core?

I was thinking unit drops.

**Comment by potatoisagender** [comment]
ah, so like the enemy drop points.
