### ISSUE TITLE
New turret

### ISSUE THREAD

**Issue by jajasaludos** [Anuken/Mindustry-Suggestions#558]
Well, I have several ideas on how to improve the game, I am not saying that it is bad, they are just some things that I think would be good to put them

 first 1 type of new turret that is a kind of cannon that constantly shoots energy at enemies both on the ground and in the air, although of course for it to work it will obviously need electricity and something to cool it because as I say it will fire constantly without stopping unless run out of energy or get hot the amount of energy it consumes would be 500 per second The damage would be 130 for each hit, I know that is a lot but for that I have another idea that I will put in another comment so that this one does not become too long.

**Comment by Anuken** [comment]
1. Use the template.
2. V6 has a persistent energy turret already.
