### ISSUE TITLE
Pause game while waiting for other players in PVP

### ISSUE THREAD

**Issue by flippy1345** [Anuken/Mindustry-Suggestions#56]
I would suggest that the game has a pause feature.
More so for when the message "Waiting for other players" appears.

The current problem is, when other players disconnect in pvp, you are getting ported to the spawn and have to wait for the other players.
In the time you can't do anything, the game still runs.
Which results in unfair advantages.
- Production still runs
- Bots still attack  

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by KSean222** [comment]
Should probably rename this issue to "Pause game while waiting for other players in PVP" or something, the current name is a bit misleading

**Comment by itcannotbe** [comment]
The problem lies in players. Not the game. But yes a game freeze would be better that a simple teleport to core and can't spawn in.

**Comment by flippy1345** [comment]
> The problem lies in players. Not the game. But yes a game freeze would be better that a simple teleport to core and can't spawn in.

I wouldn't say that it is not a game problem.
Players can disconnect for different reasons.
The only thing a player can control in this situation is to close the game session, which is more then suboptimal.
The ai still attacks the production runs, but the player can't stop them due to them being ported to the spawn.

A multiplayer pause function would be great.

**Comment by C0rn3j** [comment]
@Anuken Can this be open again? As all 3 issues related to it are either closed as stale or dupe.

**Comment by Anuken** [comment]
What? This was implemented [16 months ago.](https://github.com/Anuken/Mindustry/commit/b7ec90e7c028c860f34c72a95a9040c8c2a142d4#diff-0032de7c53171fdcc85619161148739afad351c4d1f7d199e8a1dc272a34e43cR783)

**Comment by C0rn3j** [comment]
Ah I see, the specific use case (waiting for other players) is implemented I assume, but the issue #296 (closed as dupe) and #261 (closed as stale) want pause while hosting at any time, which is what I wrongly assumed this issue is also about.

So I really should've made this comment on #261.

**Comment by Anuken** [comment]
Issue get closed because there's no discussion occurring on them. If there's nothing more to discuss, I don't see a reason to reopen them. If you have a different suggestion, open a new issue.
