### ISSUE TITLE
Make tier 5 air support (oct) a little bit better

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#560]
**Describe what you would like changed, and why.**
It's current payload capacity is just under what it could be, and it can _almost_ carry 2 reign's or 3 toxopids, or 8 fortresses, etc.

**Describe the changes you want to propose. Include possible alternatives.**
Change the ``payloadCapacity`` value to ``(4.6 * 4.6) * 8 * 8`` instead of ``(4.5 * 4.5) * 8 * 8``, which would allow it to pick up multiple of some bigger units. I get why it wouldn't be this though, as it is pretty powerful as it is.

**Comment by Syncinus** [comment]
Perhaps even bring it up high enough to allow it to pick up omura

**Comment by Syncinus** [comment]
Another possible buff that would work for it would be making it a command unit, which would be useful once it drops off the units.

**Comment by scarf-generic** [comment]
Seems very similar to mine, but with numbers

**Comment by here-be-username** [comment]
I agree with this. The oct doesn't feel as good as the other t5 units. Also, I think that it should be able to move all the units around, because sometimes you end up having to build omura in a tiny little pond, and there's no way to get it to where it needs to be except to carry it.

**Comment by Syncinus** [comment]
I also wrote that down, in the comment

**Comment by scarf-generic** [comment]
It would balance naval units a bit more, especially on attack maps with many lakes. If the front line is constantly moving, it would probably be good if all units were able to reach it. Allowing oct to carry t4 and t5 naval units means that they are useful in more situations. Also to balance,  maybe lower the acceleration of the oct while its carrying heavier units?

**Comment by Syncinus** [comment]
Yeah, payload carrying units should maybe lose some speed based on how much stuff they are carrying

**Comment by Anuken** [comment]
(I implemented this during testing before I even read this suggestion)
