### ISSUE TITLE
Allow spider units to be dropped on top of structures from carriers

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#561]
(Not using template as this a very simple issue)
Literally the title, right now spider units are treated the same as ground units when dropping payload, which doesn't let them be placed on top of structures, they should be able to do that as they are basically air units that can't go over top of the black areas.

**Comment by here-be-username** [comment]
Yes please! Can't wait for SURPRISE TOXOPID over enemy core!

**Comment by kingb74** [comment]
> Yes please! Can't wait for SURPRISE TOXOPID over enemy core!

Yea i can imagine gust seeing one fly over and then Suprise Mutherf**kers

**Comment by Syncinus** [comment]
Okay this seems to have been implemented, closing this now
