### ISSUE TITLE
Status Effects: Why are they so underused?

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#562]
**Describe what you would like changed, and why.**

Status effect overhaul?

**Describe the changes you want to propose. Include possible alternatives.**

Introduction: 
A underused concept of Mindustry is it's status effects, or its Unit buff/debuffs. It's a great concept - I see it in almost every good tower defense game I play (like the BTD series). Usually, they play a big part in defenses and planning. However, they aren't to prominent in Mindustry, because the effects that they have are almost irrelevant. Here's why. 

Speed Multipliers:
Now slowing down units is usually great in other tower defense games, as it gives turrets more time to damage the enemy. In Mindustry, it is useless. Why slow down a Unit when you can block it with walls or overwhelm it with sheer DPS?

Damage: 
The "burning" status effect is the most common of the effects. It does damage over time. Unfortunately, it doesn't stack, which means that it can only do a set amount of DPS. The more time you let the enemy burn, the more damage it deals. However, for Mindustry players, letting a enemy burn also means leaving it alive for longer. This ultimately leads to it dealing more damage, rendering killing the enemy outright a much better strategy than letting them burn with this sort of status effect.

Armor: 
Reducing the armor of an enemy will help in most cases, but, currently, a decrease of 1 or 2 armor is almost irrelevant. I think it is safe to say one would be better off replacing the armor debuffing thing with more damage dealing turrets. 

Conclusion: 
Currently, status effects are almost completely useless. They aren't good at what they do, and what they do isn't even good in a Mindustry players defense. 

Ultimately, the problem with status effects don't lie with the concept or even the efficiency itself. These aren't problems one can solve with buffs. Instead, the core of the matter lies on two things: the "wall" style defense that most Mindustry players build, and the inefficiency of the things that spread these status effects. Now both of these topics are subject to controversy, and I won't be covering them in this Issue. 

~~Anyway, that's all for today. Remember to leave a like and subscribe to my YouTube channel.~~

**Comment by RogueRedHawk** [comment]
Burning itself is good against structures. When something catches on fire the whole place can burn down.

As for slowness, I actually use cryo waves frequently to slow down bosses.

So that's ⅔ of your points that I don't actually think apply strongly.

**Comment by itcannotbe** [comment]
Armor works differently in v6 compared to v5

**Comment by itcannotbe** [comment]
Armor works differently in v6 compared to v5

**Comment by genNAowl** [comment]
> the whole place can burn down

Did you read? I said against units. 

> cryo waves frequently to slow down bosses.

the waves have such a low range that bosses easily go by them or get blasted back by other turrets (like cyclones) before getting targetted

> Armor works differently in v6 compared to v5

I know, but I still feel like an extra turret is better than a debuffing one. It certainly is a lot simpler, with no need to route another type of ammo to your defenses.

**Comment by itcannotbe** [comment]
Actually why people chooses one ammo over the other, it's usually due to one being over powered.

**Comment by genNAowl** [comment]
> ammo over the other

???
I meant that usually it is simpler to add another turret that uses the existing ammo then to route an extra debuffing ammo (like slag or pyratite) to the front line.

**Comment by itcannotbe** [comment]
Pyra is considered useless as anmo in v5 because frag can take enemies down quicker.

**Comment by BorisA11** [comment]
I totaly agree. Only place where you see buffed units in old v5 campaign is Ruinous Shores, with some faster crawlers. In v6, some ships have status effects, but most have none.

**Comment by genNAowl** [comment]
bonk
