### ISSUE TITLE
Boss Music [for v6]

### ISSUE THREAD

**Issue by Eschatologue** [Anuken/Mindustry-Suggestions#563]
**Describe the content or mechanics you are proposing.**

In game and especially in PvP/Multiplayer there should be a feature where the music gets intense when an opposing Tier 4 and up unit is deployed, and the music gets louder the closer their T4> unit to your core

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think it'll be an interesting feature in the game, you get warned visually and audibly about your incoming doom. Or in PvP warns your enemy that their demise is coming. Its not really a revolutionary feature to add but a fun one notheless

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
oh god. Imagine when you are late game and 100 t5 units show up. I don't quite agree.

**Comment by ItzAlen** [comment]
Music when that happen be like :
**DUN DUN DUN DUN DUN WJWNDJISKWEJUDJEIE**
Well there of course should be a limit also on how intense it should be. The music should just constantly play after reaching circum wave

**Comment by Jamtime729** [comment]
YES
