### ISSUE TITLE
The meltdown like laser on T4 ground support goes through plast walls

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#564]
**Describe what you would like changed, and why.**
Basically, the meltdown laser on the T4 support (vela), will go through plast walls, which causes it to pretty much be better then the T5's laser, as it's uncounterable.

**Describe the changes you want to propose. Include possible alternatives.**
Add the same thing that is used on the lancer laser / eclipse laser / corvs laser, for the continous laser on the vela, which will make it counterable.

**Comment by potatoisagender** [comment]
or, you can make it absorbed/reflected by the shield projector

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/93894542-d7a22380-fcbc-11ea-83e8-226debf04c1c.png)

What?
