### ISSUE TITLE
Tile History / Antigriefing tools

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#565]
**Describe the content or mechanics you are proposing.**
*(this seems like something that should've been asked, but I couldn't find anything so here it is)*

A hotkey or menu to see a tile's history (deletions, builds, rotates, etc).

*pic taken from hellomouse's antigrief tool*
![Screenshot 2020-09-21 211433](https://user-images.githubusercontent.com/45698812/93843671-7ee87180-fc4f-11ea-94c0-e7e1ce4dbb8a.jpg)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I was just in a very frustrating game (6.0 so agclient didn't work) where several griefers kept destroying pads and unlinking power nodes and since the server had instant build on, it was impossible to see who did it. Having this tool would make it very easy to find and boot griefers, improving the multiplayer experience.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
so why dont you use hellomouse antigrief

**Comment by Highfire1** [comment]
> (6.0 so agclient didn't work)

**Comment by Highfire1** [comment]
aw yeah very cool thanks anuke

**Comment by Highfire1** [comment]
mm I'm back, because not being able to see who deleted a block is something I think is useful

(I wouldn't mind if it meant the bar on top of the build menu is on all the time but maybe that's bad for mobile)

**Comment by 50275** [comment]
why not just have a /history command built into servers like /help

**Comment by itcannotbe** [comment]
> why not just have a /history command built into servers like /help

Plugins.
