### ISSUE TITLE
Ability to select n-th unit as the radar output instead of first

### ISSUE THREAD

**Issue by ErrorDAR32** [Anuken/Mindustry-Suggestions#566]
**Describe the content or mechanics you are proposing.**
When a radar instruction outputs a reference to a unit, it is always the elements who best fits the sorting criteria, for example the nearest unit, so my proposal is to be able to output any unit that matches the radar criteria given an index. for example returning the second nearest unit when given index two (if it exists). 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This enables new mechanics that weren't possible with just being able to select one unit, for example real radars.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Ilya246** [comment]
would be very useful

**Comment by ErrorDAR32** [comment]
*edit: typo on instead
