### ISSUE TITLE
Reconstructor resource consumption rework

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#567]
**Describe the content or mechanics you are proposing.**
Instead of consuming the resources all at once, unit pads and reconstructors consume resources gradually while building their unit. Also, additionally, if you partially deconstruct one, it shouldn't lose its resources.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make it consistent with the way you build blocks. About the second suggestion, often missclicks make you lose insane amounts of resources that were stored in the pad.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
> if you partially deconstruct one, it shouldn't lose its resources.
where would the "resources" go? to the core, or reappear if you construct it to 100% again?

**Comment by itcannotbe** [comment]
> > if you partially deconstruct one, it shouldn't lose its resources.
> 
> where would the "resources" go? to the core, or reappear if you construct it to 100% again?

Isn't that prone to being duped?

**Comment by Quezler** [comment]
hence why i asked ^

**Comment by itcannotbe** [comment]
Might be better to send them to the core since you're clearing it's inventory. And it shouldn't be that much.

**Comment by Quezler** [comment]
_teleported items go brrrrr_

**Comment by Ilya246** [comment]
Yeah, send to core

**Comment by Ilya246** [comment]
Or could be made to reappear unless it's fully deconned
