### ISSUE TITLE
Naval unit feedback

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#568]
Currently, naval units just stay on land if they are dropped.
Naval unit factories can only be placed on water, which makes it hard to do reconstructor chains.

Naval units should explode if they are dropped on land.
Naval unit factories should be able to be placed on land.

**Comment by Syncinus** [comment]
Naval factories can be placed on land now in the newest be build, and I don't think they can be deployed on land anymore from mega or from factory/reconstructor. But if they could still go on land, why would they explode, that would just end up causing a resource waste for building the unit, and it wouldn't really make too much sense, as touching ground doesn't blow a boat up.

**Comment by rmperkow** [comment]
> Currently, naval units just stay on land if they are dropped.
They also stay there with no way of moving them.
