### ISSUE TITLE
Make the surge tower something people actually care about

### ISSUE THREAD

**Issue by AlvarGD** [Anuken/Mindustry-Suggestions#569]
Right now its just a thing you SOMETIMES use when you want to connect electriciy from both sides but you cant build anything in between. It isnt as special as it should be.

Thing that could make it better: 
1) give it more connections
2) make it smaller
3) give it more range. It seems like a lot at first but when you compare it to 3 large power nodes or the mass driver its not that much. Maybe give it the range of a mass driver or at least 50% more range than now

**Comment by itcannotbe** [comment]
Actually. It's fulfilling the use case it was meant to fulfill.

It's the thing you use to connect places where you can't use regular power nodes to connect.

Although It would be nice if it has more range and more HP.

**Comment by here-be-username** [comment]
^
I think that it could use a range buff to at least mass driver range (~35 blocks), though a health buff is unnecessary.

**Comment by AlvarGD** [comment]
i just want THREE connections. Maybe 4.

**Comment by AlvarGD** [comment]
> ^
> I think that it could use a range buff to at least mass driver range (~35 blocks), though a health buff is unnecessary.

The health buff is very useful in certain ocasions

**Comment by Electro9899** [comment]
maybe make it so that it can connect different v6 zones
