### ISSUE TITLE
Way for mods to use the file picker

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#570]
**Describe the content or mechanics you are proposing.**

Some way for mods to prompt the user to select a file.
Should be a non-blocking version of readString for user-selected files.

Examples:
```js
selectFile("Select an image", "png", contents => {...})
selectFile("Log a file", null, print)
selectFile("pls select /etc/shadow so i can set fish shell yes yes", "", passwords => {hack()})
```

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Currently the only way for mods to read arbitrary files is to import them from the clipboard.
This would allow for simple file selection and reading with no fluff.

The third example demonstrates that it's not easy to abuse this as the user would have to be very stupid.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
bumping, see modding-toolbox outliner tool, incredible ux of:
1. `base64 -w 0 < rabbit.png | xclip -sel primary -i /dev/stdin`
2. Click export
3. `base64 -d > rabbit-outline.png`
horrible to use on binbows.

also adding request for file writing
@Anuken

**Comment by Anuken** [comment]
This is fairly low priority as far as modding goes, and I don't want to go around trying to implement something that fits *your* use case. The [file chooser code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/core/Platform.java#L121) is very simple, submit a PR.
