### ISSUE TITLE
Some Units Should Have Built-in Point Defense

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#571]
**Describe the content or mechanics you are proposing.**
Certain 6.0 units, such as T4 and T5 Mega and T4 and T5 Quasar, should have built-in point defense.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
No unit has built-in point defense yet. And since these are support units, and not war units, it makes sense. The player could control them and be protected and protect others, but maybe the maximum amount of PD would be about 3-8, so as not to be overpowered. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Syncinus** [comment]
Player controlling the point defense would be super difficult, because bullets move fast, I would say it would have to be automated.

**Comment by A5TR0spud** [comment]
Yes, automated point defense is what I had in mind.

**Comment by BorisA11** [comment]
*Actually*, the Antumbras and Eclipses in build 8000 or something had it. It was later removed.

**Comment by Violet-Scarelli** [comment]
Supplanting the idea that @Syncinus had a bit ago (link [here](https://github.com/Anuken/Mindustry-Suggestions/issues/580)), the Oct should have PD turrets around its body to further its role as a defense/command unit.

**Comment by Colonizor48** [comment]
Ye this is a good idea
