### ISSUE TITLE
Flag that makes schematics possible to be placed only if there are enough resources in the core

### ISSUE THREAD

**Issue by LeoVen** [Anuken/Mindustry-Suggestions#572]
**Describe the content or mechanics you are proposing.**

A flag that makes players' schematics placeable only if there are enough resources to completely build it.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

In the beginning of multiplayer maps a lot of players start by placing really expensive schematics that might not ever be completed. Having this flag, where the server admin can opt-in can prevent the early-game spam of schematics simply because of not having enough resources early on. This also forces people to not have such an easy start early on, having to design their own builds.

Drawback: Some multiplayer maps start with quite a few resources, possibly making a race between players to see who can place their schematic first before depleting resources.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
i suggest making it 0 to 1 rather than a boolean, say for allowing placement if there's half the resources available

**Comment by scarf-generic** [comment]
Maybe instead of making the schematic unplaceable, warn the person placing it by a color change on the schem menu or something?

**Comment by LeoVen** [comment]
@scarf-generic I think that not being able to place a schematic given the right conditions is the center of this suggestion. For example:
Power cubes that make use of a bit of plastanium and a lot of silicon wouldn't be placed by players early on. When someone starts a really expensive schematic, the early game resources (copper, lead and even graphite) are depleted really fast. With this new flag (or a value between 0.0 and 1.0 as suggested by @DeltaNedas ) could prevent these early on bursts of resource usage, stalling the early game.

**Comment by scarf-generic** [comment]
I think that if you place a schematic that you know you cant afford, you deserve to run out of resources

**Comment by Ilya246** [comment]
But multiplayer

**Comment by DeltaNedas** [comment]
h

**Comment by Kyllingene** [comment]
Would it be better to do a 0.0 - 1.0 system, or a 0% - 100% system (to make it easier to understand)? Programmatically, they are pretty much the same.
