### ISSUE TITLE
Mobile players cannot use payload units to carry multiple units

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#574]
**Describe what you would like changed, and why.**
Add two buttons to the hud for mobile players when using payload units, allowing them to seperate the actions of picking up and dropping units. Currently double tapping picks up/drops a unit, but attempting to pick up a second unit just drops the first one.

**Describe the changes you want to propose. Include possible alternatives.**
Add two buttons to the mobile players hud when controlling a payload unit that pick up/drop units.

**Comment by scarf-generic** [comment]
See https://github.com/Anuken/Mindustry-Suggestions/issues/463 for another hud change that would balance mobile gameplay a bit more

**Comment by kingb74** [comment]
Yep mobile needs alot of stuff

**Comment by kingb74** [comment]
Yea mobile needs better controls

**Comment by Anuken** [comment]
I am not adding any unit control related buttons to mobile.

**Comment by Syncinus** [comment]
But then it would just end up giving mobile players a huge disadvantage, and I don't think it would clutter too much space to add two small buttons to pick up and put down.

**Comment by scarf-generic** [comment]
I agree, but it seems it isnt going to happen.
