### ISSUE TITLE
Poly Drone Should Heal Blocks

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#575]
**Describe the content or mechanics you are proposing.**
The green missile the Poly uses should be able to heal blocks. It would shoot a damaged block, or do the green circle thing to heal a block. The missile's fire rate is slow, so it wouldn't be too overpowered. And, the missile is green, and in my mind, that means healing. But it can't heal.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would fill the void of the Spirit Repair Drone. The Mega does this, kind-of, but the mega is T3 and healing should be available earlier in the game, like T2. And it kinda makes sense. The Poly *repairs* broken buildings, helps build, and *heals* units. It should be able to repair damaged blocks, not just broken ones.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I don't agree. Healing *any* block *anywhere* on the map is a big enough deal for it to be only available to a T3 unit, e.g. Mega. A unit that both builds *and* heals will not be added.

**Comment by A5TR0spud** [comment]
Fair enough
