### ISSUE TITLE
Being Able to Make units Even When They're Full (6.0)

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#576]
**Describe the content or mechanics you are proposing.**
I understand why this is in the game, but it kinda should be smarter than just 'stop making this unit.' It should be based more on reconstructors.

This is how it should work:
1. The factory will only stop making units if they're full AND the factory does not have an output, such as a payload conveyor or a recontructor
2. A payload conveyor will NOT deposit a unit if the said unit type is full
3. A reconstructor will only stop reconstructing if the unit type it will turn into is full, AND it does not have an output, such as a payload conveyor or another recontructor
4. Repeat step 3 for every type of reconstructor
5. If a unit is in a factory/reconstuctor but the type is full (you deleted the output), and you switch it over to a new type, the stuck unit will self-destruct
6. You can manually delete units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I built a Mono/Poly drone factory, and (obviously) the Monos finished first. But my Polys weren't being built anymore. I went to see why, and I realized that it was because the game stopped all Mono production, even though I needed Polys desperately. I had already captured the sector, so I couldn't kill a Mono. And so, I'm left with 8 Monos and 1 Poly. This would fix that. It would let me make both at once without a problem.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
In my mind, the reason drones stop working after a certain unit cap is because the bandwidth to the core that controls the units is used up (obviously the technical reason is lag, blah blah) so this doesn't really make sense. Instead, I would propose that disabled drones (that have the little warnings) should be able to be deconstructed just like any block, with the little hammer. This seems a much better way because it doesn't just start randomly destroying your drones, wasting resources.

**Comment by A5TR0spud** [comment]
I didn't say remove the cap?

**Comment by RogueRedHawk** [comment]
Yes, I read your entire post, including the title, your 6 points, and your conclusion. My critique is on the fact that you proposed a range of somewhat arbitrary rules that will be hard for players to understand, and these rules seem to work best for this particular situation. _My_  suggestion is simpler, as it doesn't have any rules-- everything expects exactly as you would expect it to, and you can manually destroy the units just as you'd expect it to. This seems a far better solution than disabling factories and reconstructors, or restricting units from being offloaded. As a new player, how are you supposed to figure out that you've reached some sort of cap? It would seem to this new player as if their game just randomly stopped working.

**Comment by A5TR0spud** [comment]
There is a visible cap limit, already in game. The factories already shut off by themselves. That's why I made this post. So that it won't stop unexpectedly, like it did for me, it will keep going as long as they get upgraded, but stop when the caps are reached. They won't be visible rules, they'll be in the code somewhere somehow. But maybe the self-destruct system after some time isn't the way to go.

**Comment by RogueRedHawk** [comment]
Ah, I understand what you are saying now. It was unclear in the original post, but now that you explain it differently, I actually agree.

**Comment by A5TR0spud** [comment]
Sorry I explained it weird. And sorry for the confusion.

**Comment by Anuken** [comment]
Factories are already able to produce even when the unit cap is full.

**Comment by A5TR0spud** [comment]
I wasn't aware of the bleeding edge version when I made this post, sorry.
