### ISSUE TITLE
Mise a jour pour le multijoueur

### ISSUE THREAD

**Issue by stakiri** [Anuken/Mindustry-Suggestions#577]
Le fait de pouvoir créer des parties privé en ligne un peu comme sur d'autres jeu comme Minecraft ou d'autres. 

Dans le menu ''rejoindre une partie'' l'on pourrait mettre ''créer une partie'' ou '' rejoindre une partie'' pour rejoi'dre il faudrait mettre le nom du serveur que l'on veut créer ou rejoindre et le mots de passe s'il et privés. Pour créer la partie il faudras préalablement sélectionner ces mods deuxièmement faire ''créer une partie'' ensuite entrée un nom de partie choisir une Map parmi celle enregistrer choisir l'option privé ou non et si sais privé il faudrait entré un mots de passe.

Ceci et une proposition pour de futurs mise a jours.
Je vous remercie de votre attention.
Et j'espère avoir un retour de votre part.
Avec mes meilleures salutations

**Comment by Anuken** [comment]
Use Steam for this.

**Comment by DeltaNedas** [comment]
anuke i didnt know you were a french spy
