### ISSUE TITLE
What about new defensive weapons?

### ISSUE THREAD

**Issue by LordPedru** [Anuken/Mindustry-Suggestions#578]
**Describe what you would like changed, and why.**
Im following the game for a time and im seeing a lot of new units and the different types, but what about the defenses? Im still leveling up in the beta to see if the defenses handle the new units very well, but i wanna know if there will be new defenses to deal with them, thats all, thx anuke.

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by Anuken** [comment]
There won't.

**Comment by LordPedru** [comment]
Okok thx bro c:

**Comment by potatoisagender** [comment]
there are a few, but not anymore I don't think
