### ISSUE TITLE
Carrying big units with payload carriers

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#579]
**Describe what you would like changed, and why.**
One of the things I noticed was units like omura have an insanely high weight in payload form right now, at 2500, and bringing oct up to that would cause it to need to have a payload capacity of ``6.5 * 6.5 * 8 * 8``, which would make it too overpowered when picking up other kinds of units. Though it would be really nice if units like oct could pickup omura, or other huge units, which would give it a good use in transporting stuff like omura between ponds.

**Describe the changes you want to propose. Include possible alternatives.**
I have two suggestions, my first one is to basically give certain units a "payload weight" which could be more or less then it's actual payload size, like changing omura from having a 2500 weight to being more like to maximum weight of the oct, this would basically allow for big units to be counted as less heavy, and for small units to be counted as more heavy. This kind of mechanic could also probably allow for setting spider units to be bigger then they currently are.
My second suggestion would be to basically allow oct to "strap" a single giant unit to it, like an omura, and having a seperate capacity for "strapping" a single unit to the bottom of it (like it seems to do, if you set the oct to be able to set omura right now), which would be higher then the original capacity, but it would only work for a single unit, basically making it so that the thing can either have a big single unit capacity, for one big unit, or a less capacity for a lot of smaller units.
I think doing these would basically allow for carriers to be just a bit more useful then they currently are, as a lot of people have suggested that the oct can carry omura, so I think that doing this would allow that to be done without causing carriers to be overpowered by being able to carry way too much weight.

**Comment by here-be-username** [comment]
Very good idea. Being able to move giant units is very useful. If you're on a map with lots of lakes and ponds, you're going to want to be able to move your extremely expensive (and powerful) omuras as you advance.

**Comment by Syncinus** [comment]
Yeah exactly, that would be good, ideally another thing that should be changed if "strapping" is implemented then is that big units shouldn't render at all if they are in the "payload bay", versus they should render if they are using the single payload strapping system.

**Comment by itcannotbe** [comment]
I don't see the need to be transporting T4s and T5s via carrier. It undermines the drawbacks of them being large and expensive.

**Comment by Syncinus** [comment]
Kind of, but it's super useful to be able to transport stuff like omura, for reasons that were stated by here-be-username. And it's really only going to be useful for that, as the oct can already pick up multiple of other tier 5 units, like 4 toxopids and like 2 reigns. It's not really too weird if it was suddenly able to pick up a gigantic thing.
