### ISSUE TITLE
Oct really should be a command unit

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#580]
**This is a simple suggestion, so I'm not going to do the two things**
Basically, right now oct is pretty much the perfect unit to be a command unit, it lacks any guns, it has a big shield, it's a carrier, and most aspects of it pretty much scream "command unit", which is why it's interesting that it isn't one. We also currently lack any kind of command unit that isn't on the ground. It would just make a lot of sense if oct was a command unit, as it's pretty much built perfectly to be one.

**Comment by scarf-generic** [comment]
Yeah, it fits very well with the whole support aspect of it, where its weak by itself but strong if it has other units to protect.

**Comment by kingb74** [comment]
Yea i also agree if u see this agree so anuke is more compelled to do it

**Comment by BorisA11** [comment]
Agreed.

**Comment by Syncinus** [comment]
Okay now it's a command unit.
