### ISSUE TITLE
2x2 memory cell

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#582]
**Describe the content or mechanics you are proposing.**
What the title says. Could store 512 variables to be 2x as efficient as the 1x1 cell.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make some things previously impossible or hard possible to do. Also, 22x22 CGoL.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by imreallybadatnames** [comment]
[REDACTED]

**Comment by LeoDog896** [comment]
Has been done, called the "Memory Bank"
