### ISSUE TITLE
Block upgrades

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#583]
An ability to upgrade existing blocks. The upgrades should cost a lot of basic materials, to make sure you have an use for them in late game. They shouldn't be very large, but a bit by bit, you will get better equipment. Upgrades should reaquire different upgrades to be done earlier, so you need to for example upgrade core to be able to upgrade defences.
Here is an example for the upgrades
Mechanical drill:
+0.04 Base mine rate (15000 copper, 4000 lead), max level 20, cost increase: +10% each level
+5% Efficency when cooled with water (5000 metaglass, 10000 lead), max level: 10, cost increase: +20%
Special upgrade (max everything to unlock):
+20% Mine rate (50k copper)
Now, I know this is a *big* thing, but if not in v6, maybe add it in v7 or something.
Same should be for units, so you get better units when you upgrade
Enemy will also have certain upgrades, defined by sector difficulty.

Cores will have very large upgrades list, as it's the main block and some upgrades might affect other blocks

This will certainly improve the game in many ways. It will make the campaign more interesting, since you will take longer time to max. It will also make later waves easier to make, since you wont need thousands of weak units. 

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Similar issue #203

**Comment by BorisA11** [comment]
This one is different, they are in tech tree, not a block

**Comment by genNAowl** [comment]
This Suggestion is very confusing, and you should of specified that all these upgrades would be in the tech tree, not done in-game. 
The balancing work will also be a nightmare; 
just as an estimate, 4 upgrades * around 100 blocks is 400 upgrades to balance. The tech tree would look like spaghetti, and some blocks will probably have more than 4 upgrades.

**Comment by BorisA11** [comment]
Agreed. I said it's **hard** to make, but it will be awesome. 

Tech tree won't spaghettify actually. You open upgrades by holding on the icon of the block. Then they pop up and close if you open other upgrade selection

**Comment by Anuken** [comment]
No.
