### ISSUE TITLE
Broken - scatter not accepting any ammo

### ISSUE THREAD

**Issue by rix117** [Anuken/Mindustry-Suggestions#585]
**Describe what you would like changed, and why.**
The scatter just won't accept any ammo no matter how you try to input it 
i've tried 
 Putting ammo in directly via placing them next to mines
putting ammo in through conveyor directly by just ending the conveyor into it
putting ammo in through any sorta router/gates.

**Describe the changes you want to propose. Include possible alternatives.**
not a big deal as it's not needed but it is broken.

**Comment by RogueRedHawk** [comment]
This is more appropriate for a bug report, where you should mention what build you are on and how to reproduce this bug.

**Comment by rix117** [comment]
i'll put it there just found it's location.
