### ISSUE TITLE
Turrets, titanium ammo

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#587]
I would like to make some turrets more useful. This means balancing. Here is the proposal:

**Salvo** - Little faster fire rate, faster shells. It's impossible to actually hit anything with it. Maybe 1 tile more range

**Ripple** - Less damage and fire rate. It's overpowered

Arcs and Lancers are already fixed in v6

**Scatter** - Less powerful. - 20% damage and impact area

**Fuse** - 0.5 tiles less range. Thorium as ammo is good :D 

**Segment** - Faster fire rate. At least + 15%

**Scorch** - Already fixed. We all saw what can this beast do to eradicators in v5

Maybe add an ability to use titanium for ammo. It should deal good damage (between graph and thorium) and have *pierce* ability, pierces targets, losing damage each hit. Since it has high durability and low mass, it should be able to fly further, maybe increasing effective range of shell by 2 tiles (can be achieved by increasing speed). 

Also make graphite ammo better for turrets, instead of 0.6 refire rate, make it 0.7. This should add a big difference between it and copper.

**Comment by Ilya246** [comment]
Segment and salvo should not be buffed, and fuse/ripple should not be nerfed - segment and salvo are good if used properly, in many cases ripple is useless, and there is no reason to nerf fuse range - if it gets nerfed any more fuse will become useless

**Comment by BorisA11** [comment]
Ripple at least. Think of 20 blast ripples. That's  a **ton** of damage, and virtually no cost. Why would you use any ground turret except it?

**Comment by Ilya246** [comment]
flyers

**Comment by Ilya246** [comment]
ripple takes a lot of space that could be used for antiair up
