### ISSUE TITLE
building quality-of-life suggestion 

### ISSUE THREAD

**Issue by lordburgerr** [Anuken/Mindustry-Suggestions#589]
when laying down new buildings, ones that are already placed but scheduled for destruction should be ignored. I often place down plans while waiting for big things to build like impacts, but because i cant put down any blueprints on stuff i have marked for destruction, ill have to wait for the other stuff im building to finish so i can destroy that one part and continue. it would just be nice quality of life if i didnt work this way, since theres no reason you would want to avoid placing over stuff you want gone. another note is that it would be nice to override build and destruction priority by clicking on the thing you want prioritized, just as a side note.

**Comment by Ilya246** [comment]
why did you kill the template
