### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by memepeoples** [Anuken/Mindustry-Suggestions#590]
**Describe the content or mechanics you are proposing.**

hi

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
hi

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
hi

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
autoclose. Stop wasting our time

**Comment by Syncinus** [comment]
Why did you make this?

**Comment by memepeoples** [comment]
because i wanted to say high also this is great game and can you add hover crafts
its a unit that goes on both land and water and can transport other units
but the units that it has on it can shoot off it and enimes

**Comment by potatoisagender** [comment]
lmao late response. Also Oct is close enough to it.
