### ISSUE TITLE
Unit buff

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#591]
Units can change bullets to buff them
Its gonna be fun

examples:

Graphite
1.5x bullets
2 block 2 area damage
120% damage
150% bullet speed
-0.10 reload speed

Silicon:
2x bullets
110% damage
+0.20 reload speed
Homing

Thorium
1x bullets
180% damage
200% bullet speed 
- 0.20 reload speed

Metalglass
2x bullets
70% damage
110% bullet speed
+0.50 reload speed
Frag

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
"Template murdered again"
-llya246
