### ISSUE TITLE
Memory cell interface

### ISSUE THREAD

**Issue by Vladislav117** [Anuken/Mindustry-Suggestions#595]
**Describe the content or mechanics you are proposing.**
It would be useful to make an interface to memory cells. When you click on the block, a "pencil" appears (as in the message block) and you can go to the data view. A table is displayed where the column on the left is the cell index and the column on the right is the value. These values could be edited manually.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make it easier to view these programs. It is not always convenient to display text in a message block

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by LeoDog896** [comment]
Thats a great idea Vlad 👍

**Comment by DeltaNedas** [comment]
deltanedas/ldb
