### ISSUE TITLE
Unconditional jump

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#596]
Add an unconditional jump in v6 logic.
It could be a dropdown option of the regular jump command.

This would help to move around in processor code.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Ilya246** [comment]
Just set @counter to a variable (starts from 0)

**Comment by BorisA11** [comment]
No need for it. You can make a variable that's always 1, and every time you need uncoditional jump you say if x == 1. That's it, no need for a new block

**Comment by Ilya246** [comment]
or just have the jump's condition be true == true

**Comment by DeltaNedas** [comment]
OR
set @counter <wherever>
the jump block having a shortcut for this wouldn't be too bad

**Comment by rmperkow** [comment]
Just realized it
