### ISSUE TITLE
Water extractor

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#598]
I would like to reduce power of water extractor. It extracts around 7 liquid units, like a small pump. And it takes only 60 power. This leads to making the well-known nothing-to-power thingies.

Also, steam generators are the best power source in game, bescause of water collectors being OP.

Noone really uses pumps, conduits or anything, just strap a water extractor and you are good to go!

Make it use 100 power and extract 5 instead of 7. This makes water more of a resource, less a free thing

If not make it less powerful, make pumps better at least.

**Comment by Ilya246** [comment]
it was already nerfed in 6.0; Also, template murdered again?

**Comment by lokyinng** [comment]
> I would like to reduce power of water extractor. It extracts around 7 liquid units, like a small pump. And it takes only 60 power. This leads to making the well-known nothing-to-power thingies.
> 
> Also, steam generators are the best power source in game, bescause of water collectors being OP.
> 
> Noone really uses pumps, conduits or anything, just strap a water extractor and you are good to go!
> 
> Make it use 100 power and extract 5 instead of 7. This makes water more of a resource, less a free thing
> 
> If not make it less powerful, make pumps better at least.

steam generator is nerfed one also water extractor is nerfed to require god damn metaglass if nerf once more steam generator become the worst generator pls buff steam generator

**Comment by itcannotbe** [comment]
Use pumps instead of relying on that freaking overpowered Power cube that's the epitome of free power.
