### ISSUE TITLE
Water extractor balance change

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#599]
**Describe what you would like changed, and why.**
Water extractors in v6 are unreliable. They certianly need a nerf (free power squares sucked) and affinity nerfs were a good idea to make them less spammable. Sadly, this makes them also extremely unreliable, confusing, and just overall inconsistant. A nerf that doesnt lower water output based off special terrain would be an improvement.
**Describe the changes you want to propose. Include possible alternatives.**
Instead of lowering or increasing water output based off special terrain, increase or decrease power cost. Also, increasing base power cost would help too. Maybe base power use is 120 power/sec, and things like snow decrease power cost and char increases power cost? Something like this would make them more consistant while simultaniously nerfing powercubes and encouraging use of other pumps.

**Comment by 50275** [comment]
In other words, special terrain affects power cost instead of extraction rate?

**Comment by apolar-narwal** [comment]
yes, I'm inclined to agree for multiple reasons, but mainly because as of right now the reliability of water extractors has changed so drastically it hasn't just nerfed the water extractor but also nerfed certain other buildings with water requirements

**Comment by scarf-generic** [comment]
> In other words, special terrain affects power cost instead of extraction rate?

Exactly. If im an idiot and put my water extractors on hot rocks, i end up paying for it in power cost, and the water extractors are still reliable, just more expensive to use in some places and cheaper in others.

**Comment by Ilya246** [comment]
Just - implement liquid mass driver, the only problem with just using pumps currently is that even an amount of solar panels equal to the amount of conduits makes more energy than you save by using conduits instead of water extractors

**Comment by scarf-generic** [comment]
> Just - implement liquid mass driver, the only problem with just using pumps currently is that even an amount of solar panels equal to the amount of conduits makes more energy than you save by using conduits instead of water extractors

Couple reasons this would not really solve the issue
1. While liquid mass drivers are a cool idea, they do not change the unreliability of water extractors
2. In my experience mass drivers are most likely to fail due to sync errors (because they do not autoconnect), i dont think another unreliable building would help this situation (multiplayer exclusive)
3. Increased power cost for water extractor means its better to use conduit in most situations
Who knows, maybe both will get added.

**Comment by Colonizor48** [comment]
This is a good idea.

**Comment by DeltaNedas** [comment]
good idea, might make a pr today

**Comment by DeltaNedas** [comment]
ok i didnt im very good at procrastinating

**Comment by stuffyAI** [comment]
> ok i didnt im very good at procrastinating

now pls

**Comment by scarf-generic** [comment]
> > ok i didnt im very good at procrastinating
> 
> now pls

dont rush @DeltaNedas im sure that if he still wants to he will get around to it sometime

**Comment by unjown** [comment]
good idea

**Comment by scarf-generic** [comment]
Anuke wants them to be unreliable.
