### ISSUE TITLE
Building icon placement

### ISSUE THREAD

**Issue by AndersenJ** [Anuken/Mindustry-Suggestions#6]
**Describe what you would like changed, and why.**
Right now, the building icons you choose from when placing structures are all in a grid. That grid has no gaps. When a new building is unlocked in the tech tree, other buildings are shifted over to make room. When this happens, the hotkeys for those buildings get changed. Having the hotkeys for common items like the router change from mission to mission is a bad user experience.

**Describe the changes you want to propose. Include possible alternatives.**
I propose that each building have a fixed position that does not change when things get unlocked. Hotkeys would not change for anything. It might look slightly worse initially, but the user wouldn't be subject to ever-shifting hotkeys and icon locations.

Hopefully that makes sense.

**Comment by Katsute** [comment]
While the item is not researched it could display a placeholder icon (_to keep the item truly hidden_) `[1]`;
 or place a lock over the item (_since playing a non-campaign map reveals what the items are anyways_) `[2]`
![draft2](https://user-images.githubusercontent.com/58778985/75611853-3703d080-5aec-11ea-8efe-ff00d8134ddb.png)

**Comment by AndersenJ** [comment]
I like the lock idea.

**Comment by Katsute** [comment]
if lock is implemented, then an `x` overlay could also be implemented for banned items (to keep consistency with how the icons look)
![draft3](https://user-images.githubusercontent.com/58778985/75619154-19635500-5b46-11ea-83fc-61e5e774437f.png)

**Comment by hilezi** [comment]
> **Describe what you would like changed, and why.**
> Right now, the building icons you choose from when placing structures are all in a grid. That grid has no gaps. When a new building is unlocked in the tech tree, other buildings are shifted over to make room. When this happens, the hotkeys for those buildings get changed. Having the hotkeys for common items like the router change from mission to mission is a bad user experience.
> 
> **Describe the changes you want to propose. Include possible alternatives.**
> I propose that each building have a fixed position that does not change when things get unlocked. Hotkeys would not change for anything. It might look slightly worse initially, but the user wouldn't be subject to ever-shifting hotkeys and icon locations.
> 
> Hopefully that makes sense.

I agree it has bad UX. Because I always click and hover on it to see the hotkeys.

But I doubt if each building has a fixed position, and hotkeys not change, what expect if I added modules that have the same hotkeys and it conflict?

e.g. In other games, like Minecraft, it provides another mod to manage those hotkeys.

**Comment by Katsute** [comment]
Hotkeys are now fixed https://github.com/Anuken/Mindustry/pull/2170
