### ISSUE TITLE
6.0 Solar Panel

### ISSUE THREAD

**Issue by Pogreu** [Anuken/Mindustry-Suggestions#60]
As for the upcoming 6.0 update, solar panels must generate more energy than at night. meaning that as time pass by, it generates either more or less energy

**Comment by InfernoSuperNova** [comment]
do you mean, assuming it's day time exactly 50% of the time, increase the power gen by 100% so it overall generates the same amount of power?

**Comment by kapzduke** [comment]
> solar panels must generate more energy at day than at night.

thats already a feature

**Comment by DS-3K** [comment]
There´s a night time? Or did you mean lighting, wich can be changed in the
editor? It would be interesting to have day/night cicles in Mindustry.

Am Do., 30. Apr. 2020 um 14:49 Uhr schrieb kapzduke <
notifications@github.com>:

**Comment by Pogreu** [comment]
yes day and night cycles

**Comment by stuffyAI** [comment]
Since this has been added this should be closed
