### ISSUE TITLE
Launch pad destination should be able to be reset

### ISSUE THREAD

**Issue by vooxal** [Anuken/Mindustry-Suggestions#600]
**Describe what you would like changed, and why.**
I would like to reset the destination of the launch pad to none again for use in the skill tree.

**Describe the changes you want to propose. Include possible alternatives.**
Possibly instead of having materials coming out of no where you instead have a storage sector which is a huge playground to do anything in. which you send things there instead.

**Comment by potatoisagender** [comment]
any materials stored in core go toward tech tree. Don't unload all the mats if you want to research.

**Comment by agergo100** [comment]
I have a really good idea how to use the Launch pad.
Just set the package local, and you can send support items to other local that need it.

**Comment by vooxal** [comment]
> any materials stored in core go toward tech tree. Don't unload all the mats if you want to research.

Well there is storage, a max of 4k or more depending on your storage but id you can send for research you can have almost infinite materials

**Comment by potatoisagender** [comment]
perhaps the idea ISN'T TO GIVE INFINITE MATERIALS?????
research things one at a time

**Comment by vooxal** [comment]
well just don't choose a location and get everything, the default just puts it into limbo so its normal.
