### ISSUE TITLE
REDACTED

### ISSUE THREAD

**Issue by gelo2801-dot** [Anuken/Mindustry-Suggestions#602]
**Describe the content or mechanics you are proposing.**
A cannon that needs flammable ores to start it shoots bombs that is a bit stronger then a bomber it has long range and can only hit ground units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** the cannon will be fun for sandbox and useful for survival!

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by gelo2801-dot** [comment]
Oops the second answer in the third thingy is actually check oops

**Comment by scarf-generic** [comment]
Plast ripples already exist

**Comment by gelo2801-dot** [comment]
Oops then im going to delete it

**Comment by gelo2801-dot** [comment]
How to delete?

**Comment by Gdeft** [comment]
You can close this issue, it technically *deletes* it.

**Comment by Kyllingene** [comment]
If you would like to delete the issue, you can comment something (such as "Closed.") and instead of clicking "Comment", click "Close with comment" (it's red).
