### ISSUE TITLE
Mining in water using naval units

### ISSUE THREAD

**Issue by gelo2801-dot** [Anuken/Mindustry-Suggestions#604]
**Describe the content or mechanics you are proposing.**
There should be a naval unit desinged for mining in water and the ores should be more less in water or the water whould be ugly then there should a port device where the mining naval unitz whould drop the ores

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** so the ocean will be a bit useful and and cool! Plus more ores that should be in water like clay,sand,coal that should be the only 3 ores in the water

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Mechanicalfish** [comment]
This is a pretty good idea but i am surprised that you could post this without marking the 3 requierements at the bottom
