### ISSUE TITLE
New function for the "Control" block in processors

### ISSUE THREAD

**Issue by EnganK** [Anuken/Mindustry-Suggestions#605]
**Describe the content or mechanics you are proposing.**

It should be possible to additionally control blocks with a choice of something, for example - sorters, unloaders and factories - using processors. For unloaders and sorters, you can choose an item, for factories - a unit, etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This feature should improve the automation of factories and defense - for example, it will be possible to change the produced units along with the supply of materials with one button.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by LeoDog896** [comment]
The control block does some of that, but its very possible to add new keywords that can be changed.

**Comment by DeltaNedas** [comment]
it does none of that
it just enables and shoots

**Comment by LeoDog896** [comment]
Sorry, I mean *can do*

**Comment by hortiSquash** [comment]
I 100% second this feature, this is exactly what i need for my ultra compact factories designs
