### ISSUE TITLE
Add a light source to the campaign tech tree

### ISSUE THREAD

**Issue by EnganK** [Anuken/Mindustry-Suggestions#606]
**Describe what you would like changed, and why.**

It seems rather strange that nothing can illuminate the area at night. The ability to add lights to the campaign will make the game a little more enjoyable.

**Comment by LeoDog896** [comment]
There's a block for that, the illuminator. If you had a cost idea I can definitely add that.

**Comment by EnganK** [comment]
I know about the illuminator, I just forgot its name :). It had a cost and is available on custom maps and servers with lighting. All that remains is to add it to the campaign.
