### ISSUE TITLE
Bigger variety of trees

### ISSUE THREAD

**Issue by Mechanicalfish** [Anuken/Mindustry-Suggestions#609]
**Describe the content or mechanics you are proposing.**
Currently there is only 1 type of tree but i want a few more to added

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently there is only 2 main colors for trees wich is white and blue but they cant be used that much so a few more colours or 
trees with different structure.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by gelo2801-dot** [comment]
Yeah anuke should add this cuz what? Are trees always dead? He should add this
