### ISSUE TITLE
Nerf Sandstorm

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry-Suggestions#610]
Please nerf sandstorm, PLEASE. I was playing with some friends on a survival map and we kept getting sandstorms and we hated them so much, being pushed around and unable to just makes the game really painful to play, I get it might have sounded good in theory but in reality these things are literal hell 

What to change? make the amount of sand in the sandstorm less, and also removing the pushing. you don't have to remove too much sand, but try to avoid having it so bad you get frustrated trying to find something/look at something.

**Comment by Jornker** [comment]
Also if you don't think its that bad, try playing a long game with sandstorm on, they just become stupid thing very quickly

**Comment by potatoisagender** [comment]
or maybe a setting to remove weather effects

Butcher the template why don't you.

**Comment by Jornker** [comment]
> or maybe a setting to remove weather effects
> 
> Butcher the template why don't you.

I will admit I was a little off and sorry about that lol, I'm just pissed off from having to deal with like 10 in a single game.

**Comment by Draco18s** [comment]
Getting pushed around makes trying to accurately build things very difficult, especially on wider zoom levels. Its annoying and frustrating. Its a neat gimmick for about 10 seconds, but when sandstorms (and other weather effects) last for *ten minutes* its ridiculous.

**Comment by Dav-Edward** [comment]
The sandstorms/wind is an utter deal breaker for me. Making a game 'hard' because you mangle the control system is not how difficulty should be added to a game. I'm trying to do base planning and every time I try to build my plans, the push keeps making me not only miss, but do dragging I'm not asking for. The game basically keeps going "oh, drag to the top-right? sure thing!" when I'm trying to place a single object because the push effect is moving the whole game ergo, it moves my mouse pointer too!

Trying to build with any level of accuracy goes right out the window whenever a storm happens, and there are storms more than not-storms during any game session. These are a constant source of aggravation and I assure you if they don't get removed officially, people WILL mod them out.

**Comment by Daniel-Chin** [comment]
Even a "sandstorm supressor block" in the tech tree could be something to look forward to.

**Comment by Jornker** [comment]
> The sandstorms/wind is an utter deal breaker for me. Making a game 'hard' because you mangle the control system is not how difficulty should be added to a game. I'm trying to do base planning and every time I try to build my plans, the push keeps making me not only miss, but do dragging I'm not asking for. The game basically keeps going "oh, drag to the top-right? sure thing!" when I'm trying to place a single object because the push effect is moving the whole game ergo, it moves my mouse pointer too!
> 
> Trying to build with any level of accuracy goes right out the window whenever a storm happens, and there are storms more than not-storms during any game session. These are a constant source of aggravation and I assure you if they don't get removed officially, people WILL mod them out.

Yeah, Screwing up controls is one of the worst ways to make a game more difficult

**Comment by RogueRedHawk** [comment]
I think it's a cool gimmick, in my opinion though it should punish players who are unprepared. It should be avoidable through some unit upgrade or a block, perhaps making crawlers the unit of choice when building in windy areas or such.

**Comment by Jornker** [comment]
> I think it's a cool gimmick, in my opinion though it should punish players who are unprepared. It should be avoidable through some unit upgrade or a block, perhaps making crawlers the unit of choice when building in windy areas or such.

How do you prepare for it though? + there's the visibility problem, spore storm is ok, because you can see at least. but sandstorm, try looking at something complex in that. if there was just something like a "Weatherdome" that would more or less block all weather in a range, that would be awesome
