### ISSUE TITLE
A More Bandwidth-Dense Transport System (or, Repurposing The Block Payload System)

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#611]
**Describe the content or mechanics you are proposing.**
A 5th tier of transport conveyor that isn't the phase conveyor. It'd be the opposite of the phase conveyor, and a compliment to the plast conveyor: instead of having narrow bandwidth and extremely high speeds, it would have modest speed and insane bandwidth. I imagine a kind of 2x2 version of the plast conveyor: a highway conveyor, with vehicles that travel on it. It would be hard for it to turn, as it would require a full 2x2 space to do so. 

This would in essence be a refinement of the experimental block loader/unloader system with more purpose-built components and a higher (and less jerky) speed, as well as having more refined specs and a less janky feel. 

The vehicles that travel on the roadway would be able to carry a maximum of 100 units of resource. HOWEVER they, like containers, are able to hold 100 of each kind of item, for a total of 1600 items if fully loaded with each type. This scenario, however, is highly unlikely. More likely is a mixed-belt analog setup that's holding about 200 items per truck. Trucks would not display hovering "backpack" icons like plastanium roombas do, instead showing either a gauge on their back to indicate their fill level for each item, or no gauge at all, requiring the player to click the segment of conveyor the truck is in to see how many items are in the truck. Trucks would depart their station after a set amount of time with no item fill, say, two seconds or so.

When loading, they'd accept items only from the back of the conveyor line, or from a 2x2 loader station placed somewhere along the belt. A truck could be created at either a loader station or the back of the conveyor. The trucks would automatically stop at these stations (which have extremely high transfer rate but ONLY to the "trucks" on the conveyor) to pick up items on their way to their destination, but only if they have room. Otherwise they'll pass the station entirely. The trucks would unload at any unloader station placed at the belt, but if the station is full (it counts as a container for purposes of core connection) it will simply move on after dumping all of the load that it can, or vanish like a plastanium roomba if it cannot go any further. An additional tentative feature is the ability to dump to reconstructors, as the larger tiers take ages to fill, and this system wouldn't reduce the fill time, only reduce the number of belts necessary to fill it, as the belt supplying it could be loaded up with all the resources it needs as it snakes its way to the reconstructor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Having a system that has extremely high bandwidth and modest transfer rate would be extremely applicable in terms of "core highways". Too often, the space around the core gets eaten up very quickly with belts. Having a system that's mainly meant to be a "last-mile" delivery system would be useful in getting mixed items to the core, but also in moving mixed ammo to the front lines, delivering large amounts of resources to advanced factories (and pulling the finished resources out of said advanced factories), and in general acting as a lower-speed, higher-bandwidth system.

Here's why I believe this would fit well in Mindustry:

1. We already have plast conveyors, so it wouldn't be too much of a stretch to say that there's another system like it that just uses repurposed mechs. 

2. It wouldn't clash with the existing high-bandwidth transport methods, as phase conveyors require power and die if not fully powered (this would only need power at the loader/unloader stations and only slows down if not fully powered), mass drivers don't do mixed-bag transport very well (they have one allocatable space per mass shot, which can easily be filled with irregular proportions of items) as well as being very slow, though long-range, and plast conveyors are too easy to jam up with mixed loads, as the little roombas that inhabit them can only carry one item type at a time and jam if a different item type is fed before they've got a full load.

3. It wouldn't REPLACE existing high-bandwidth transport systems, either. It can't match the cost-to-distance ratio that mass drivers can do, as my proposed truck system would need a clear path to its destination and relatively expensive conveyor to go there. It can't match the raw speed of phase conveyors, which provide an expensive but extremely fast way to transport items from A to B in end-game matches, and can be high-bandwidth if you've got the space to place a lot of them. It's a lot bigger than plast conveyors, which can easily turn around a corner. And most of all, it can't feed factories directly. 

In short, this system would have a wide enough applicable range of scenarios to merit inclusion, in addition to repurposing the loader/unloader system originally for the payload conveyors into something more immediately useful. While not as directly useful as a 2x2 of conveyor belts, it provides better utility by being able to handily accept mixed loads and having a high load/unload speed. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
High throughput is always a plus
