### ISSUE TITLE
Send Units to location

### ISSUE THREAD

**Issue by JamesTheNerd** [Anuken/Mindustry-Suggestions#614]
Players should be able to command a unit to go to a certain place without having to take control and drive it over there. That takes a long time for higher tier units, which are the ones that most need to be moved around, and is boring. Maybe something like control-shift click to select unit, and then click again to set the point it will go to. The unit will then stay there, as if there was a rallying command block, until you control-shift click it again.

This would be useful for more unit-based defenses as well as quickly patching holes in your defense without sending all your units there.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by BasedUser** [comment]
Violation of point 2 - checking the trello.

**Comment by JamesTheNerd** [comment]
Sorry, didn't see that point.
