### ISSUE TITLE
Jump Pads, and/or Payload Bridges

### ISSUE THREAD

**Issue by l-Luna** [Anuken/Mindustry-Suggestions#616]
**Describe the content or mechanics you are proposing.**

A Jump Pad would be a kind of Payload Mass Driver. A Jump Pad would accept a unit from a Payload Conveyor, and launch it to another Jump Pad within range, which would move the unit onto a Payload Conveyor in front of it.

Alternatively, Payload Bridges would connect to other Payload Bridges aligned to them similar to existing Bridge Conveyors, allowing the transport of units across other tiles.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

These new blocks would allow for easier integration of Payload Conveyor lines across e.g. existing conveyors - currently, any existing conveyors must be replaced by bridge/phase conveyors. Jump Pads, in particular, would make it easier to seperate unit production and unit usage without needing to wait as long for units to move, and have holes for ground units to travel.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

Note: #553 considers these, but includes them as a larger proposal and in less detail.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Colonizor48** [comment]
I like this idea
