### ISSUE TITLE
V6 snek patch

### ISSUE THREAD

**Issue by bishbosh69420** [Anuken/Mindustry-Suggestions#617]
**Describe what you would like changed, and why.**
Plast conveyors in V6 should be a bit faster as junction spam is still faster, junctions will become the new sneks

**Describe the changes you want to propose. Include possible alternatives.**
just up the speed on plast conveyors.

**Comment by hortiSquash** [comment]
Wrong, plast conveyors are way faster
The problem is they need two inputs to be able to reach their maximum speed of 40/s

**Comment by itcannotbe** [comment]
40/s under normal circumstances.
They do more under OD.

**Comment by rabit232** [comment]
> Wrong, plast conveyors are way faster
> The problem is they need two inputs to be able to reach their maximum speed of 40/s

haha i been doing tests on plast and they are really  slow https://cdn.discordapp.com/attachments/689230537575104523/760044920706039818/Screen_Recording_20200921-132944_Mindustry_BE_1.gif

look in the gif all plast got 2 input  and 7.3k ore stored there and they are useless for me

**Comment by itcannotbe** [comment]
Who even told you that routers are a good loading method.
Literally no one.

**Comment by RogueRedHawk** [comment]
Plast conveyors were never meant to be better at everything. They are high throughput. Just because you can show a case where the other conveyors work better doesn't mean they're bad. Use those conveyors for those situations and the plast conveyors for others.

**Comment by bishbosh69420** [comment]
closed the issue due to my comment being wrong
