### ISSUE TITLE
[Bullets] Merge 'healbullet' and 'bullet' type

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#618]
**Describe the content or mechanics you are proposing.**

Instead of having 'HealBulletType' as a separate class, add a variable in bullet that determines whether this bullet can heal blocks and how much it will heal the block. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This, if implemented correctly, will allow support units to heal blocks, as currently, the mega and the tau are the only ones that can do such. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have not checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Colonizor48** [comment]
yes good idea

**Comment by genNAowl** [comment]
bonk
