### ISSUE TITLE
Full screen on iphone X

### ISSUE THREAD

**Issue by tregouetkevin** [Anuken/Mindustry-Suggestions#619]
On iphone X, iphone 11 and bigger screen, game is not in full screen mode.

**Comment by genNAowl** [comment]
If it is a bug, report it here: https://github.com/Anuken/Mindustry/issues/new/choose

**Comment by DeltaNedas** [comment]
then you would make an issue saying that the notch hides ui and the game is broken.

**Comment by tregouetkevin** [comment]
> then you would make an issue saying that the notch hides ui and the game is broken.

lol i'm a developer too, and yes i try to make every app better and better with new techno... it depends of what is your priority...

when i lauch an application, i try to add the best ui design for the confort of my customer.

so its hope to the dev, this game if really good and very addicting. i don't understand why the main dev doesn't want update the core ui... its a shame :(

**Comment by RogueRedHawk** [comment]
>it depends of what is your priority
>the main dev doesn't want update the core ui

He doesn't want to deal with it. That's the entire reason, and it's ok he feels that way.

>i'm a developer too, and yes i try to make every app better and better with new techno

Mindustry is open source. If you are passionate about the game and have the skills, you should go ahead and contribute to fixing the mobile UI. This repo is littered with examples of players asking for better mobile controls, I'm sure if someone like you put the time into it you could make it amazing.

**Comment by pusherbox** [comment]
> 
> 
> then you would make an issue saying that the notch hides ui and the game is broken.

yes! the notch hides too much! let's hope this will be fixed soon

**Comment by tregouetkevin** [comment]
Yes, for the bottom too, need some padding at top and bottom
