### ISSUE TITLE
[Discord Server] Moderation issues

### ISSUE THREAD

**Issue by Darkwatch-MINDUSTRY** [Anuken/Mindustry-Suggestions#62]
**Due to the recent events, I feel inclined to propose something that will make the server a safer and cleaner place.**

**Option 1 - Expand the moderation team.**
A good way to ensure the server is monitored 24/7 is to hire more people who would do that. It is necessary for the community, as thanks to the server growth it will begin attracting unwelcome elements of discord fairly soon, including but not limited to: 
NSFW & NSFL raiders
Mass pingers
Selfbots 
Harassers
DM advertisers

_Having a staff team of at least 10 users would cover the server most of the time so the regulars won't have to deal with one guy spamming shock content for 30 minutes before the moderator comes online._

**Option 2: Automoderation**
Improve the Core bot so it executes basic automod functions such as automatic warns, mutes and bans. It's not as effective _but it removes the possibility of rogue mods._

To sum it all up, the server may look like it's not in a big need of moderators. The raids are rarely even happening, _but all of that can change **very** quickly._

**Comment by itcannotbe** [comment]
This is an over reaction.

We had these kinds of things before.

**Comment by Darkwatch-MINDUSTRY** [comment]
You just said that we had these problems before and it's an overreaction to propose a thing to **stop** them from happening **again**. Big brain time

**Comment by DeltaNedas** [comment]
> hire

jannies by definition do it for free

> team of 10 jannies

thats far too many and currently prosta does fine mostly on his own

i think regulars should be given mute powers which is a quick solution

> corebot automod

you can write that yourself

btw i dont think this is the right place for thia
