### ISSUE TITLE
Being able to enter the Reconstructors manually while controlling a unit or mech. (v6)

### ISSUE THREAD

**Issue by ZygZagGaming** [Anuken/Mindustry-Suggestions#620]
**Describe the content or mechanics you are proposing.**
I propose that either:
a) it is possible to manually enter the new Reconstructor blocks while controlling a unit/mech to upgrade yourself.
b) a new type of Reconstructor for each type that **only** works for manual entry

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will easier allow mechs/units to be upgraded and make it more practical to control them.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by here-be-username** [comment]
Adding a reconstructor just for manual entry is a bit extreme. Allowing you to just directly walk into one is a much better idea (which I support). Also, I suggest being able to manually enter payload conveyor, by being on top of them and then clicking. This will allow you to transport units across the map in a more organized fashion.

**Comment by RedstonerKBC** [comment]
So this is being added in v7, right? Many of players will be very grateful.

Tiny suggestion, what if units can't enter unless they're at full health? Makes sense but what do you think?
