### ISSUE TITLE
Unit feedback

### ISSUE THREAD

**Issue by kingb74** [Anuken/Mindustry-Suggestions#621]
Actually from my perspective the units are all good but there a few problems that need to be dealt with like the controls for them

1.Oct is a unit that does 2 things on mobile if u press twice which can complicate things like lets say im carrying an troop and then wana control the troops near me for fire power I end up dropping the troop in the process then if I tap 2times again I pic it up but then give up my controll can u fix this with something like maybe buttons or something 
2.this is for all control type units when controlling unit u cant be specific u just control the nearest ones which can be anoying like what if i just wanted controll of specific units so in future I propose u should be able to control a unit by clicking on it when close and repeating to control another one instead of just controlling as many as possible randomly

**Comment by genNAowl** [comment]
why murder the template?
