### ISSUE TITLE
Segment is dominated by Mend Projector + Thorium Wall

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#624]
**Describe what you would like changed, and why.**

Even after being buffed (see this [issue](https://github.com/Anuken/Mindustry-Suggestions/issues/452)), Segment, I think, is still too weak. Here I show that Mend Projector + Thorium Wall dominates Segment.  
A Segment can destroy 6 bullets per second and consumes 480 power/s. (This takes 4 tiles of space.)  
Using the same amount of energy, you can afford 5.33 Mend Projectors, healing 588 HP/s to a Large Thorium Wall. Compared to this, Segment is like a joke. Let alone multiple Thorium Walls can be healed simultaneously. Let alone Segment cannot intercept melee/laser/shock attacks.  
The only downside is the extra space (~21 tiles of space) required. However, you can arguably place your Mend Projector much farther away from the frontline than you can with Segments, saving real estate.  

**Describe the changes you want to propose. Include possible alternatives.**

One possible solution: Include a high-tier unit that fires powerful artillery shots at a very slow rate. Then players can place Segments in the back to cover those without wasting fire rate on small bullets.

**Comment by here-be-username** [comment]
Toxopid: Am I a joke to you?

Adding something that segment can counter isn't really a good fix. There are other ways to fix segment, such as allowing it to hit multiple bullets at once, extending it's range slightly, and/or allowing it to hit units (If you can blow a bullet out of the sky, why can't you hit a unit that's much bigger and slower?).
