### ISSUE TITLE
System of 3D block rendering

### ISSUE THREAD

**Issue by nerootter** [Anuken/Mindustry-Suggestions#625]
I would like to suggest a feature - System of 3D block rendering, using known textures as examples to fill the blocks' faces, pseudo (voxels?) or pure 3D feature to add depth in, ability to edit face textures for blocks, best camera allignment will be placing it isometric (example: Sonic 3D Blast) or top-down with small rotate up on the Rotate-Y axis and closer to world on the basic Y axis as well. (Unknown if items, mechs, etc have to be rendered or not as they might not have as much importance when rendered at isometric perspective, might be deadly when rendered)

1. - [-] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
thats suggesting an entirely different game, see mindy.
