### ISSUE TITLE
Scorch Still OP

### ISSUE THREAD

**Issue by Daniel-Chin** [Anuken/Mindustry-Suggestions#626]
**Describe what you would like changed, and why.**

Even after fixing the multiple-pierce per hit bug, Scorch is still OP, simply because it is 1x1. 
![image](https://user-images.githubusercontent.com/34157591/94364691-dc703880-00fd-11eb-86bb-5c0dcbfa6ea7.png)
Values are calculated from in-game turret descriptions of V6 build 106.  
As we can see, Scorch with Pyratite dominates Spectre and Meltdown in terms of damage.  
Even Scorch with coal dominates Spectre.  
Also, Cyclone seems to be the weakest turret and I did not even include it in the table. Is there some feature about Cyclone that I don't understand? 

**Describe the changes you want to propose. Include possible alternatives.**
Maybe further decrease the range of Scorch. Make it more fun and special. Also mention its very high Damage/s/tile in the description. Players (including me) who haven't calculate usually never give Scorch a proper try!

**Comment by Ilya246** [comment]
But where have you seen the amounts of coal/pyratite required to fuel scorch for extended periods? Also, it still has no range.
About cyclone - yes, it should be buffed.

**Comment by DeltaNedas** [comment]
scorch is useless outside of sandbox on maps with tiny drop zones.
arcs are much better as spam turrets.
scorch is bad enough as is, it should have a bigger range but just light units on fire instead of doing massive damage.

**Comment by Ferociousfeind** [comment]
I'd like to see the on-fire effect do variable amounts of damage based on how long it'll last (say, 10 damage, then 9 the next frame, then 8, then 7, all the way down to being extinguished after doing 1 last damage), and for that to replace much of scorch's raw damage
