### ISSUE TITLE
Buff the Corvus and vela

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#627]
**Describe what you would like changed, and why.**
The Corvus and Vela and very very weak for there sizes. A vela should be able to at least hold its own vs a reign for a bit. Considering its a t4 unit. But it gets annihilated by the reign and the vela only does slightly more damage to it then a gamma. The thing has trouble taking out crawlers. Same thing with the Corvus though it is a bit stronger to be fair. And on top of all of this there lasers can't heal stuff, nor can they build, nor do they have shields like the quasar. And they are super expensive. And on top of everything else they turn way too slow to be effective in combat. The vela is outclassed by the scepter/chaos array And the Corvus is outclassed by the Reign/erradicator.

**Describe the changes you want to propose. Include possible alternatives.**
My solution for this would be a few things. 1. Buff there damage. The Vela should have damage around maybe 25-50% of a cryofluid meltdown and the corvus should be like 200% meltdown damage but nerf its range to like 50%-75% of that of a ripple. It would be balanced for corvus because its not a continuous beam. 2nd. Make the beams able to heal. Not 100% needed but nice to have as its green and green bullets are supposed to heal. 3rd make the units able to build. The quasar is able to build. So should its upgrades. 4th. Give them quasar shields. They would be slightly stronger then the quasar but still balanced. 5th. Make them turn faster and move faster. Self explanatory.

**Comment by Colonizor48** [comment]
Mabye my damage buffs would be abit op but please do buff damage somehow

**Comment by genNAowl** [comment]
RIP template again

**Comment by Colonizor48** [comment]
I followed the template but deleted the template text. Instead of saying RiP tEmPlAtE can you offer some constructive feedback please?

**Comment by genNAowl** [comment]
Dude once you delete the template text it's not called "following the template" anymore.

**Comment by Colonizor48** [comment]
There i added the template text

**Comment by genNAowl** [comment]
Thank you; You are one of the first people who actually added the template back after being criticized.

**Comment by Syncinus** [comment]
Corvus and Vela are already incredibly powerful, though they may need a slight buff. They are very good for structure attacking, due to their insane laser power, and they are also very good for defensive purposes, a map I know of which is spawning 30 tier 5 units per wave, is only defendable using corvus, because of how good it is due to it's very high range and pierce, and the damage which imo is in a pretty good place.

**Comment by Colonizor48** [comment]
That would be a vailid point if they werent hard countered by platanium walls. Also the corvus is very very vunerable to attack while its firing. And can barely turn. Making aiming at units hard to do. A corvus could probably easly be destroyed by a few zeniths or horizons.

**Comment by Colonizor48** [comment]
The erradicator has range on par with a ripple. And while it cant pierce through walls it can break through them very easly. And once its behind your walls it can do alot more damage them a corvus or vela could ever hope to do. And cant be eliminated by a few zeniths. It does actual damage that you cant just repair in a few seconds. Unlike the walking waste of resorces that is the corvus. also if the corvus is so op why does it need a buff at all?

**Comment by DS-3K** [comment]
Why not make the chorvus and vela more early game or give them a supportive ability?

**Comment by Colonizor48** [comment]
Just give them shields and make them fire quicker and make them able to build. That way they would actually be usable as support units.

**Comment by kingb74** [comment]
> Just give them shields and make them fire quicker and make them able to build. That way they would actually be usable as support units.

Yea that makes sense especially the shields maybe a sheild thats at least as powerful as a normal force projector but no where near the power of octs shield

**Comment by Colonizor48** [comment]
I would also make them a bit faster so you can use them like you would use a mega but that is optional.
