### ISSUE TITLE
Make shard cores placeable like nucleus and foundation cores.

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#628]
The ability to place shard cores freely like we can other cores.

We can already freely place Foundation And Nucleus cores. This is just for the sake of consistency

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
You can't build those cores freely. You need a core base.

**Comment by Colonizor48** [comment]
It used to require a base. Now it doesn't

**Comment by itcannotbe** [comment]
Wrong.
![Screenshot_20200928_123351_io anuke mindustry be](https://user-images.githubusercontent.com/45280919/94391082-2bae7b80-0187-11eb-9904-253ddc0b073b.jpg)

It still needs a base.

**Comment by Highfire1** [comment]
![image](https://user-images.githubusercontent.com/45698812/94398061-b0fb4700-0119-11eb-8628-377ed0e8684d.png)
Chiming in here, new cores are placeable in both the public servers, but doesn't work in singleplayer (not sure bout campaign)
~~is this a bug?~~

**Comment by itcannotbe** [comment]
It has been recently patched. Hasn't reached the alpha though. But on thing is certain. The premise of this suggestion is wrong.

**Comment by Colonizor48** [comment]
This turned out to be a bug and was patched

**THREAD L0CKED**
