### ISSUE TITLE
land transport vehicles

### ISSUE THREAD

**Issue by thompson8964** [Anuken/Mindustry-Suggestions#631]
**Describe the content or mechanics you are proposing.**
what if we had land transport vehicles like the trains in factorio

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

it will provide long-range transport 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
From the README on this repo:

>These have been proposed many times already, and I won't be adding them.
>- Trains, or any transportation system that uses something analogous to rails 

These will not be added to the game.
