### ISSUE TITLE
Add a thing a the mobile

### ISSUE THREAD

**Issue by SixOfDark** [Anuken/Mindustry-Suggestions#632]
Please put a shoot button for the people who want to randomly shoot for testing

**Comment by RogueRedHawk** [comment]
See #574, no unit control buttons are coming to mobile.

**Comment by DeltaNedas** [comment]
murdered the template

**Comment by BasedUser** [comment]
Use Keyboard+Mouse mode.

**Comment by kingb74** [comment]
> Use Keyboard+Mouse mode.

Yea but u cant move when u do
