### ISSUE TITLE
Command Units

### ISSUE THREAD

**Issue by Jammo2000** [Anuken/Mindustry-Suggestions#633]
**Describe the content or mechanics you are proposing.**
All units should be able to command other units of the same type.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be useful to separate units based on type. Different units are needed in different places, and this would make it easy to use each unit in its own niche.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
I think units should be able to command units of the same type at a lower tier.

**Comment by JamesTheNerd** [comment]
Do you mean like fortresses could command titans and daggers, but not other fortresses?

**Comment by rmperkow** [comment]
Yes.

**Comment by Mechanicalfish** [comment]
I'd rather have an option to controll units of some specific tier at a time and not multiple tiers

**Comment by JamesTheNerd** [comment]
That seems to solve the problem in the best way. We don't even need level
restrictions because if you have high tier units you want to control, you
could just hop into them. The restrictions seem silly from that perspective.
