### ISSUE TITLE
(6.0) Building new cores

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#635]
*This was made for fun. Even with all the limitations, building cores are op. I'll still be happy if this gets implemented, though*

**Describe the content or mechanics you are proposing.**
A few builds ago, you could build cores. This was obviously *way* too overpowered and was most likely a bug. But the ability to build cores, although overpowered, was fun and could improve the game. Here's an idea to let people build cores without it being completely unbalanced.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
First of all, you shouldn't be able to build t2 and t3 cores. Also, each tier of core should need to be build on the tier directly below it (t3 can only upgrade t2, t2 can only upgrade t1). Second, you should be able to build shard cores. Looking at the campaign, it looks like they take (2k) 2000 copper and (1k) 1000 lead to build, which I think is fine. However, they should take a *long* time to build, possibly over a minute.
- For pvp, the copper, lead, and time required will mean that most people won't build cores
- For attack, players might place more cores to raise the unit or resource cap, but again, the time and resources won't make it that viable
- For survival (late-game), players can build cores to build factories with or places to put materials.
- For sandbox, it's sandbox. Cores should be placeable.

**Wait, can't this teleport items?**
If you're talking about placing a second core, then unloading from it to access items from the first, yes. Here are some possible solutions
- Make cores more expensive: While this won't solve the teleportation problem, it will make it relatively more expensive than the Mindustry classic teleporters.
- Make cores have their own inventories: This would open a lot of logistic problems, like which core does building draw from? Do the building resources get taken evenly between cores, or do they take from the closest one? Which core will mining drones go to? 
- Combination of both: The nucleus core can teleport, but t1 and t2 cores have their own inventories and cannot.
- Just let them teleport: If you had infinite resources, it would still take over a minute to build the shard core. Maybe teleportation would be the best thing for cores?

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
coresnek 2 electric boogaloo

**Comment by Colonizor48** [comment]
This is actually a good idea

**Comment by sample-text-here** [comment]
Also: If this gets implemented, griefers might use cores to cover up valuable ores because you can't deconstruct them. So, you should be able to deconstruct cores **unless it's the last core remaining**. Griefers can deconstruct cores, then, but since it would take a long time to deconstruct, you can probably catch them.

**Comment by itcannotbe** [comment]
I agree with DeltaNedas.

> coresnek 2 electric boogaloo
And yes. Majority of the community won't get that reference.

**Comment by bishbosh69420** [comment]
> Also: If this gets implemented, griefers might use cores to cover up valuable ores because you can't deconstruct them. So, you should be able to deconstruct cores **unless it's the last core remaining**. Griefers can deconstruct cores, then, but since it would take a long time to deconstruct, you can probably catch them.

how about being able to deconstruct cores that have been placed by a player but not by the map maker

**Comment by sample-text-here** [comment]
> how about being able to deconstruct cores that have been placed by a player but not by the map maker

That's a much better idea

**Comment by SupremeTurtle** [comment]
> Also: If this gets implemented, griefers might use cores to cover up valuable ores because you can't deconstruct them. 
There are soooo many better alternatives for griefing. Change conveyor, disconnect power, it doesn't require that much effort and it's efficiently griefed.

**Comment by LeoDog896** [comment]
If anything, this behavior doesn't have to be added normally, but we can expose some sort of setting to allow it for modders.

**Comment by sample-text-here** [comment]
I'm going to close this as I don't think it's going to be implemented.
