### ISSUE TITLE
Move mod.hjson for Java mods.

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry-Suggestions#636]
**Describe what you would like changed, and why.**
I think place `mod.hjson` at the root of the project is a bad idea (for Java mods).

**Describe the changes you want to propose. Include possible alternatives.**
`mod.hjson` should be in `src/main/resources/mod.hjson`.

**Comment by DeltaNedas** [comment]
thats your build configuration's fault, not mindustry's

**Comment by summetdev** [comment]
> thats your build configuration's fault, not mindustry's

ExampleJavaMod uses project root to store mod.hjson

**Comment by Anuken** [comment]
> is a bad idea

Why?

**Comment by summetdev** [comment]
> Why?
In Java projects, such files are usually located in the `resources` folder, it would be more logical to put it there too.

**Comment by Anuken** [comment]
I don't like that convention, it's messy and makes editing/viewing the file more annoying than it should be. Resources like meta information being put in the `src` directory is misleading (*it's not source code!*), and you should not need to go through 3 levels of directories just to view/edit basic plugin/mod info. `plugin.hjson` being put in the resources director was somewhat of a mistake, and will be changed when I update the example.

**Comment by summetdev** [comment]
Ok, thanks for the quick response.
