### ISSUE TITLE
Unit speed senseables

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#637]
**Describe the content or mechanics you are proposing.**
Two additional sensor subvariables, `@speedX` and `@speedY` determining a given unit's speed.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Ordinarily, you have access only to the basic attributes of a unit - its position, team, health parameters, and content type. There's one attribute missing - the unit's speed; which turrets can freely access but processors can't, for whatever reason. Accessing speed would allow constructs such as analog input, extra processing, as well as potentially better targeting systems (which is what one of processor uses should be anyway).
An unorthodox way of applying `speed*` to blocks, if such an interaction is ever thought of, would be measuring flow speed in a given direction.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by BoopKittie** [comment]
There's a mod for this, I don't remember the name though.

**Comment by SupremeTurtle** [comment]
> There's a mod for this, I don't remember the name though.

Would be better if implemented in the game itself
