### ISSUE TITLE
make plast. Conveyors literally usable

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry-Suggestions#638]
**make plast. Conveyors literally usable.**

**[]()https://docs.google.com/document/d/1Ij7-o7RYH3EE7rDFirYpWVno1d1kJMx6bn6YoI7-u9w/edit?usp=drivesdk.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
The doc is private. Not that we need to see the doc, it's probably just the same rhetoric that gets posted here twice a week. If that's the case, search plast conveyors on the repo, this conversation has already conversed.

**Comment by itcannotbe** [comment]
Might as well this gets auto closed. You can't even see what this suggestion is all about.

Also plast conveyors are not a direct upgrade to conveyors, but they are a different means of transportation altogether.

**Comment by rodrigolitzius** [comment]
Yeah, i forgot to share it.... Im so dumb...
