### ISSUE TITLE
PC-like shooting on andriod and ios

### ISSUE THREAD

**Issue by gelo2801-dot** [Anuken/Mindustry-Suggestions#639]
**Describe the content or mechanics you are proposing.**
There should be a option in the settings called "manual shooting" on andriod and ios heres how it will work: first hold on the screen with one finger then the other placed down too then the second finger moves around then the jet thingy shoot to where ever the second finger will move to remember to cancel of what you were building

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** the game didnt allow to andriod and ios to shoot manually so here it is! And this will help some of andriod and ios players too

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [  ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SupremeTurtle** [comment]
Joystick for shooting instead?

**Comment by itcannotbe** [comment]
See #506
