### ISSUE TITLE
Multi-platform progress synchronization 

### ISSUE THREAD

**Issue by HUSKGames** [Anuken/Mindustry-Suggestions#64]
I want to see new feature in Mindustry - online multi-platform progress synchronization. 

This feature will be very useful for people who play both on PC and phones. 

I suggest this because it's very uncomfortable to import/export each time. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
you can already do this with git
