### ISSUE TITLE
Iron

### ISSUE THREAD

**Issue by ZappE77** [Anuken/Mindustry-Suggestions#640]
hello anuke, I like the idea of iron in the mindustry because it would leave the most dynamic game with a new ore and also machines that cost it, but left to do on V7

**Comment by itcannotbe** [comment]
In a time not too long ago, legends have it iron existed. But it was replaced because it got too confusing.

Also I am sensing anuke will auto close this because you murdered the template. You murderer!

**Comment by potatoisagender** [comment]
everyone here are psycho butcherers

**Comment by genNAowl** [comment]
Agreed, no one respects the template anymore

**Comment by DeltaNedas** [comment]
4 iq

**Comment by Colonizor48** [comment]
this looks like somthing i would write at 4am when i'm barely awake.
