### ISSUE TITLE
[Campain] the info panel (in game) "wave <number>". It could be better "wave <number>/<limit>"

### ISSUE THREAD

**Issue by mdtrooper** [Anuken/Mindustry-Suggestions#641]
**Describe what you would like changed, and why.**

I am old player (from the 5 version) and I am enjoy with the new 6 version. And I think the show more information in the panel could be good.

**Describe the changes you want to propose. Include possible alternatives.**

The info panel (in game) "wave <number>". It could be better "wave <number>/<limit>"

The current screenshot (in spanish sorry), it is the wave (marked with blue circle):

![image](https://user-images.githubusercontent.com/1285451/94546515-4992e380-024e-11eb-8063-c05d1020c1da.png)

And I made with gimp a change (in purple colour but the colour is not important) with the limit for to win the level is:

![image](https://user-images.githubusercontent.com/1285451/94546796-aabab700-024e-11eb-9ac1-79d9d7a2e627.png)

**Comment by rmperkow** [comment]
Where are the template checkboxes?

**Comment by JamesTheNerd** [comment]
I think this would be a good idea.

**Comment by genNAowl** [comment]
Oof template but still a good idea so :|

**Comment by mdtrooper** [comment]
Is there a template for this info panel?

**Comment by genNAowl** [comment]
Yes, it looks like this: 

**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

It should automatically be there when you make a new issue

**Comment by mdtrooper** [comment]
1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by LeoDog896** [comment]
Sounds good! I'll check it out for yall. What happens when it passes (minimum level requirement)? May be a little confusing as it makes it seem like that's as far as you can go

**Comment by mdtrooper** [comment]
But in the 6 version, when you finish a level there are not new waves.

**Comment by mdtrooper** [comment]
Thanks. I am playing the 6 version Build 109 ..and there is this issue implemented:

![image](https://user-images.githubusercontent.com/1285451/96511310-32e51880-125f-11eb-9c93-aa66b62b8d77.png)


Close this issue?
