### ISSUE TITLE
Conveyor should only transform to junction when +, not T

### ISSUE THREAD

**Issue by matheod** [Anuken/Mindustry-Suggestions#642]
**Describe what you would like changed, and why.**

Currently, if you try to create a conveyor and it overlap with the end of a conveyor, it get transformed to a junction :

![image](https://user-images.githubusercontent.com/339611/94580898-bc19b880-027a-11eb-8512-1b2bc33bd074.png)

**Describe the changes you want to propose. Include possible alternatives.**

I think it should only transform to a junction if the conveyor continue in the green square.

**Comment by sk7725** [comment]
What if a router was at green? Or another block or factory that accepts items?

**Comment by matheod** [comment]
If there is any item that accept item at green, then it should transform to junction.
