### ISSUE TITLE
(v6.0 for modded Campaign) Create a new campaign planet for mod maps

### ISSUE THREAD

**Issue by SkyGamingPHYT** [Anuken/Mindustry-Suggestions#643]
This suggestion adds new content to the campaign.

**Describe the content or mechanics you are proposing.**
If you activate a mod, a new planet can be created if the mod has zones in it. This can create a mindustry solar system. That would be beautiful if you ask me.
![USER_SCOPED_TEMP_DATA_orca-image--1122232458](https://user-images.githubusercontent.com/71017108/94581547-cdc88380-02ad-11eb-99fe-a5af52a39680.jpeg)
![USER_SCOPED_TEMP_DATA_orca-image--242634259](https://user-images.githubusercontent.com/71017108/94581552-cf924700-02ad-11eb-8c9e-34c78dad708c.jpeg)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Modded campaign is very popular in mindustry v5, but now the major update of v6 is arriving and the campaign is a planet, mods can add planets that neighbors the mindustry planet. The planet's size varies to how many zone the mod has, more zones is a large planet, 1 - 2 zones can be a small or dwarf planet. If the mod has no zone then it will not create a planet.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
Sounds cool

**Comment by WarmWooly** [comment]
Maybe a sort of code for planet generation? The only problem is that it may be buggy or difficult to use, and it will definitely not be a small task.

**Comment by SkyGamingPHYT** [comment]
But mindustry will be good after that, solar system like campaign will be very good for the planetary update of mindustry.

**Comment by UltraUnitilezer9909** [comment]
nice

**Comment by BlakePlayzS2043** [comment]
If this is possible currently, is there a file that contains the code for this to work?

**Comment by XxsuperdeadlysniperxX** [comment]
_i think it happened not sure tho_

**Comment by XxsuperdeadlysniperxX** [comment]
Also please close this

**Comment by Rtiooo** [comment]
> This suggestion adds new content to the campaign.
> 
> **Describe the content or mechanics you are proposing.** If you activate a mod, a new planet can be created if the mod has zones in it. This can create a mindustry solar system. That would be beautiful if you ask me. ![USER_SCOPED_TEMP_DATA_orca-image--1122232458](https://user-images.githubusercontent.com/71017108/94581547-cdc88380-02ad-11eb-99fe-a5af52a39680.jpeg) ![USER_SCOPED_TEMP_DATA_orca-image--242634259](https://user-images.githubusercontent.com/71017108/94581552-cf924700-02ad-11eb-8c9e-34c78dad708c.jpeg)
> 
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** Modded campaign is very popular in mindustry v5, but now the major update of v6 is arriving and the campaign is a planet, mods can add planets that neighbors the mindustry planet. The planet's size varies to how many zone the mod has, more zones is a large planet, 1 - 2 zones can be a small or dwarf planet. If the mod has no zone then it will not create a planet.
> 
> **Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** _Failure to do so may result in your request being closed automatically._
> 
> 1. * [x]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 2. * [x]  I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Hhh
