### ISSUE TITLE
Old unit vision in editor

### ISSUE THREAD

**Issue by Mechanicalfish** [Anuken/Mindustry-Suggestions#644]
**Describe the content or mechanics you are proposing.**
Right now in v6 you see the waves in a graph but i want a option in settings to view them in old way

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes looking at them in old way helps.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
I agree. It is hard to figure out the count in the line graph.

**Comment by Jornker** [comment]
^^^^ Please

**Comment by WarmWooly** [comment]
This is honestly really important because sometimes it is hard to tell exact numbers on the graph.

**Comment by 50275** [comment]
What if putting your mouse on a line in the graph showed what wave that was, and how many units were there on the wave you had your mouse above?
