### ISSUE TITLE
Better Plastanium Conveyor Movement

### ISSUE THREAD

**Issue by WarmWooly** [Anuken/Mindustry-Suggestions#645]
**Describe the content or mechanics you are proposing.**
I was playing the alpha, and was utilizing a lot of plastanium conveyors in my second mega base, and had a consistent problem: Plastanium conveyors had less interaction compared to the normal (titanium as the example) ones. I was brainstorming for a while, and I think I have a fitting idea that may help improve plastanium conveyors: plastanium junctions, bridges, and routers. Upon thinking, I came up with 2 different ideas on how they would function.
### _Idea 1: With Normal Conveyor Compatibility_
With this, plastanium bridges, junctions, and routers would work in pair with normal conveyors. 
> The bridge could would work similar to a plastanium conveyor, where things entering must be in stacks of 10 before they will be brought across. Up to 3 stacks could fit into the bridge, and the bridge would span over 1-3 blocks. The bridge can connect to another plastanium bridge like normal. At the end of the bridge, it will act like a normal plastanium bridge (if there is a plastanium conveyor connected to it, or it will disassemble its contents into moral conveyors like the end of a plastanium bridge. All other mechanics are the same as a normal bridge. (Optional) This bridge can connect to normal bridges, but it would be disassembled like if a plastaium conveyor was disassembling into a normal conveyor. This would also work vice-versa, where the normal bridge can go into plastanium bridges, but will only move once in a stack of 10. 
> The junction would act like a normal junction with the directional storage and everything, but it can only hold 1 stack from the plastanium. It will not disassemble the contents unless the output is a normal conveyor. Otherwise, it will act like a normal junction.
> The router will work similar to a normal router. Loose items will only go through to normal conveyors unless needed to, and vice versa for stacks of items. if loose items can only be routed through a plastanium conveyor, it will act like a normal conveyor entering into a plastanium conveyor (only moving once there is a stack of 10). On the other hand, a stack will be evenly disassembled among the normal conveyors, like the end of a platinum conveyor.
### _Idea 2: Without Normal Conveyor Compatibility_
With this idea, the plastanium versions of the bridge, junction, and conveyor will be exclusive for plastanium stacks only.
> A plastanium bridge will carry up to 3 stacks over a 3 block gap. It only accepts stacks of items (regardless of size) from plastanium conveyors. It will only exit onto plastanium conveyors. The plastanium bridge can connect with other plastanium bridges respectively. All other bridge mechanics remain.
> A plastanium junction will have directional storage per side that can only hold 1 stack of items (regardless of size) from plastanium conveyors. It will only interact with plastanium conveyors, when entering and exiting the junction. If you have the plastanium junction unlocked, and cross between a plastanium conveyor with another plastanium conveyor, it will auto fill the cross with the plastanium junction. All other junction features remain the same.
> A plastanium router will act like a router, but will only take input and output with stacks of items (regardless of size) from plastanium conveyors. It will have a storage of 1 stack (regardless of size). The router will only split the stacks, not the individual items in the stacks. All other router functions remain the same.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would improve upon the plastanium conveyors by making it easier to move things from plastanium conveyors, regardless of it it will or will to be compatible with the normal conveyors. Also, it would help fill in a gap for stack transportation. For players that start Mindustry when v6 comes out, it would make more sense if there was a plastanium counterpart to the bridge, junction, and router. Overall, it would add content that would tie the plastanium conveyor ribbon into a bow.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
#629
