### ISSUE TITLE
Change the Memory Banks storage capacity to 1024

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#646]
**Describe what you would like changed, and why.**
I would like the memory banks storage capacity changed to be able to hold 1024 values, the main reasons for this are 
a) more storage (duh)
b) 512 doesn't have a natural square root which is a problem for certain applications
c) the materials needed to make them are relatively expensive and they currently only have a density which is twice that of the normal memory cells.

**Describe the changes you want to propose. Include possible alternatives.**
some alternatives to this would be having a 3x3 memory unit which would store an increased amount of data (or an infinite amount) preferably 256, 1024, 4096, or 16384 numbers.

**Comment by DeltaNedas** [comment]
infinite data = new double[] from logic, very very very very bad
