### ISSUE TITLE
pls add

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#647]
Anuke
pls add titanium router and junction
a new liquid mix of every liquid
chrome and gold reconstructor
buff cryofluid pls
pls remove the nerf of steam

**Comment by genNAowl** [comment]
Rip template

**Comment by genNAowl** [comment]
> pls add titanium router and junction

Why is it needed? Routers and junctions both have high throughputs already

> a new liquid mix of every liquid

What for?

> chrome and gold reconstructor

chrome/gold are not in-game concepts, and no colors in the palette will even work with them. What will these reconstructors even do? Make gold units? Seems like a mod, so keep it there please. 

> buff cryofluid pls

Cryofluid is already pretty powerful already. 

> pls remove the nerf of steam

see https://github.com/Anuken/Mindustry-Suggestions/issues/469 for why it was nerfed

**Comment by DeltaNedas** [comment]
this wasnt me

**Comment by Colonizor48** [comment]
This looks more like free verse poetry then a suggestion.

**Comment by unjown** [comment]
router and junc are soo slow.
why not
if Anuke wants..he can do it
ehhh okok

**Comment by unjown** [comment]
ohhh okok get it
>steam thingy

**Comment by itcannotbe** [comment]
> router and junc are soo slow.
> why not
> if Anuke wants..he can do it
> ehhh okok

Actually Routers as as fast as overflows and underflows now.

Junctions can already do much more than a titanium conveyor.
Everything instant is gone now. Why would he consider bringing something back.
