### ISSUE TITLE
Ability to build cores on top of the vaults connected to core

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry-Suggestions#648]
I think it would be really nice if we could upgrade the vaults connected to core to actual cores.

It will make use stay more in maps and expand the unit capasity in end game situations. It wont be that over powered as well if we think of the core build price.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
🐍

**Comment by itcannotbe** [comment]
🔪🐍

**Comment by RebornTrack970** [comment]
sorry, i just think t will be nice to have that feature.

**Comment by Colonizor48** [comment]
This is a good idea. Please stop spaming YoU mUrDeReD tHe TeMpLaTe. Its nothing but annoying and adds nothing to the conversation.

**Comment by itcannotbe** [comment]
It's actually a queue for the OP to actually fill in the templete which when done correctly would make it easier to understand the suggestion in a greater and more sensible manner.

Also the tick boxes should already prevent people from making duplicates, already planned, or things already in the game.

So yes. The following the template is actually important.

**Comment by Colonizor48** [comment]
> 
> 
> It's actually a queue for the OP to actually fill in the templete which when done correctly would make it easier to understand the suggestion in a greater and more sensible manner.
> 
> Also the tick boxes should already prevent people from making duplicates, already planned, or things already in the game.
> 
> So yes. The following the template is actually important.

I would agree with you to an extent. The template is important. However instead of just saying that. Also offer constructive feedback for the suggestion. In addition to suggesting they follow the template next time

**Comment by itcannotbe** [comment]
🐍

and

🔪🐍

are the feedback.

**Comment by DS-3K** [comment]
> 🐍
> 
> and
> 
> 🔪🐍
> 
> are the feedback.
> 
> You're too new to even know what we are talking about, but the rest of the community is fully aware.

Wait, it´sss all snakess?
Alwayss hass been
*Sssssssssstab*
