### ISSUE TITLE
Liquid Distributor

### ISSUE THREAD

**Issue by GodGodixon** [Anuken/Mindustry-Suggestions#649]
Just Distributor(a.k.a. Large Router) is on here, but Liquid Distributor isn't.

We uses Liquid Router so many times, but liquid Distributor and Liquid filter, Isn't here. why :(

so, using liquids is not easier than using solid(ores).

p.s. ohno

**Comment by rmperkow** [comment]
You murdered the template.

**Comment by WarmWooly** [comment]
:/ Rip the template.

**Comment by DeltaNedas** [comment]
no

**Comment by genNAowl** [comment]
see https://github.com/Anuken/Mindustry-Suggestions/issues/360 for why Anuken said no to this suggestion

**Comment by itcannotbe** [comment]
Probably.

1. - [LOL NOPE] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

**Comment by GodGodixon** [comment]
> You murdered the template.

ahh sry :(
