### ISSUE TITLE
Add enemy drop point map marker

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#65]
It will help players to find a drop point on new maps or maps with a random drop point location.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
> It will help players to find a drop point 

This is not a good thing. Not showing an explicit marker encourages exploration instead of giving you everything you need on a silver platter immediately.
