### ISSUE TITLE
(6.0) Core Variants & Tweaks

### ISSUE THREAD

**Issue by ZygZagGaming** [Anuken/Mindustry-Suggestions#652]
**Describe the content or mechanics you are proposing.**
A few core variants & tweaks:
a) A core with a mass driver built in to it 
b) A core with liquid storage and compatibility with adjacent tanks (possibly fluid unloaders and sorters?)
c) A 6x6 core with functionality for mass drivers shooting into it, but not out.
d) A core that has a turret like an Arc built in to it, and can store power (power unloader???????)
e) A 1x1 placeable 'terminal' that functions as an extension to the Core (uses power, maybe Mass Driver input as well?)
f) 'Plastanium Unloader' that can unload a full Plastanium Conveyor from adjacent objects
g) Expensive 2x2 'Core Extension' that has to be adjacent to the Core to function, and not another extension, but can still have vaults/containers next to it

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will allow for endgame optimization of the Core and also a few new variants that can open up possibilities for maps, sectors, and map creators

**Edit**: ignore a), b), and d)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
![bruh](https://user-images.githubusercontent.com/68400583/94709257-6127a600-02fa-11eb-8c4c-916f69c859e9.jpg)

**Comment by rmperkow** [comment]
> **Edit**: ignore a), b), and d)
