### ISSUE TITLE
cache all targets in radar

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#654]
**Describe what you would like changed, and why.**

Radar only caches the first/last target which can't be used array-style.

**Describe the changes you want to propose. Include possible alternatives.**

Cache all targets for a radar.
Instead of applying the sort at cache update time, apply it after.

Basically:
- Radar first run, build radar targets array and return popped
- Radar run right after, return popped or null if empty.
- If radar cache is empty and timer has elapsed, update cache and reset timer before returning target again.

If radar is spammed it will just get a lot of `null`s.

Knowing when the targets have been fully iterated is helpful e.g. knowing when to clear a visual radar, waiting until there is a target, evenly distributing targets among turrets, etc.

Because this uses Seq, its probably still abusable to cause lots of memory i/o

**Comment by dgudim** [comment]
Nice suggestion, approved
