### ISSUE TITLE
Tint the Pipes of Liquid Turrets

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#655]
**Describe the content or mechanics you are proposing.**

Tint the pipe of liquid turrets.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Something like this: 
![tinted-pipes](https://user-images.githubusercontent.com/68400583/94772029-928d8980-036d-11eb-8e8c-463ebf754710.jpg)
Idk, it looks a bit better, I guess. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have not done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have not checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am ~~not~~ familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
close.exe

**Comment by genNAowl** [comment]
Thats sad because I made a reddit poll asking if people liked it and it was 169:7 in favor of tinting. 
https://www.reddit.com/r/Mindustry/comments/j3jm63/does_tinting_the_pipes_of_liquid_turrets_make/

:(
