### ISSUE TITLE
Oct ammo counter

### ISSUE THREAD

**Issue by Suggestedone9** [Anuken/Mindustry-Suggestions#657]
Have the ammo counter removed from the Oct unit because it doesn't use any, or use it as the shield heath bar

**Comment by Suggestedone9** [comment]
Just a small QOL suggestion for the unit and possible other future non ammo units

**Comment by kingb74** [comment]
I actually do agree that the bar should be replaced with a shield bar to show how much of its shield is left

**Comment by Syncinus** [comment]
Hmmm, it would be best then if some other units like quasar would also display a shield bar.
