### ISSUE TITLE
Newer Surge Smelter which is faster aka Surge Forge

### ISSUE THREAD

**Issue by Meltdown-Altair** [Anuken/Mindustry-Suggestions#658]
Adding the the surge forge would really help, since the regular surge smelter produces surge at a rather...*incompetent* rate : 1 surge per smelter 
The Surge Forge would help to create more Surge at a rapid rate, with some new material input like 6 copper,6 lead, 6 titanium, 6 silicon and 1 blast for 3 pieces of surge at a rapid pace. also adding 1 blast is nice since the the asymetry of the normal surge smelter just hurts my two eyes 
-Roomba

The Surge Forge would be better as a replacement to the regular Smelter , as it lets players have more surge than a normal smelter would produce. It would fill the rapid demand of surge in the newest version , the so called "Age of Surge Alloys".It would also fill a niche in the game's current high tier material factories being so scarce.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Meltdown-Altair** [comment]
Ill see if anuken even sees this

**Comment by genNAowl** [comment]
partially relevant: https://github.com/Anuken/Mindustry-Suggestions/issues/290

**Comment by l-Luna** [comment]
the alloy smelter is already a large endgame block, and is supposed to be scarce even in the endgame.

**Comment by Colonizor48** [comment]
If you can make a sprite for this i can make this into a pull request.

**Comment by genNAowl** [comment]
![rejected](https://user-images.githubusercontent.com/68400583/95141027-04c2ed00-0725-11eb-9aa9-6165399c10d9.jpg)
