### ISSUE TITLE
New Power Sources

### ISSUE THREAD

**Issue by Idontknow9898** [Anuken/Mindustry-Suggestions#659]
Could you add a new power source? Like a water or wind power source?

**Comment by rmperkow** [comment]
What happened to the entire template?

**Comment by itcannotbe** [comment]
You forgot this @Idontknow9898 

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by genNAowl** [comment]
Water power: see https://github.com/Anuken/Mindustry-Suggestions/issues/335, https://github.com/Anuken/Mindustry/pull/2232 for why Anuke says no. 
Wind power: https://github.com/Anuken/Mindustry-Suggestions/issues/472, which is currently open, so you can close this.

**Comment by Idontknow9898** [comment]
k

**Comment by Idontknow9898** [comment]
So i just wanted to ask this question. I removed it because I didnt check trello and other sites. Sorry
