### ISSUE TITLE
input output toggle on blocks that need it

### ISSUE THREAD

**Issue by bigbsonnier** [Anuken/Mindustry-Suggestions#660]
As part of a menu that you get when you click on a structure, for those that have inputs and outputs a toggle on each one that switches between input only, output only, and either or.  See image.  This is just for instance but green is input red is output and yellow is either / or.  Natural state is either / or.  If you copy with schematic it will copy state as well. This would allow tighter builds as well as allow conveyors to pass by drills without having to pickup the materials.

![image](https://user-images.githubusercontent.com/72210744/94822053-df9e4980-03c7-11eb-9f54-3d1c541498e3.png)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
armored conveyor

**Comment by itcannotbe** [comment]
>**A few things you shouldn't suggest**
**These have been proposed many times already, and I won't be adding them.**
    Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

How on earth did you even missed this?

**Comment by DS-3K** [comment]
Imagine how disguistingly compact and complicated schematics could become oof

**Comment by bigbsonnier** [comment]
sorry i missed the configuration thing but i did search a little.  It is easy to overlook the billion suggestions out there. 

It would be gloriously compact and no more complicated than the current mess of junctions, bridges, routers, etc...
