### ISSUE TITLE
Large Batteries build over (small) Batteries

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#662]
**Describe the content or mechanics you are proposing.**
Allow Large Batteries to be placed directly on top of smaller batteries, similar to the way large walls can now be placed directly over several smaller walls. If stored power can be retained in the large battery, that would be great, but not required.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Allowing large batteries to overwrite small batteries would make it easier for players upgrading their power storage, and would make the building mechanic more consistent, allowing direct block upgrades to be placed on top of their predecessors (as seen with walls and cores). Allowing stored power to be retained in the large battery would mean that no power is lost when upgrading storage, which would also simplify logistics for players.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
close.exe
