### ISSUE TITLE
Upgrade containers to vaults

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#663]
**Describe the content or mechanics you are proposing.**

Similarly to how cores can be upgraded, containers should be upgradable to vaults. Keeping the items when upgrading would also be nice.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would make it simpler for players to upgrade storage and would just be a good QOL change in general.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
might become a bit messy for when a core is already surrounded by the 2x2 ones so no 3x3 can fit due to overlap, but overall it would be a nice thing to have, and it makes perfect sense 👍

**Comment by sample-text-here** [comment]
Yesss much thank Anuke

**Comment by Quezler** [comment]
ehmm, no idea why you've closed it, but you might have confused me for anuke or had a conversation with him elsewhere 👀

**Comment by DS-3K** [comment]
Wait 2x2 blocks being replaced by 3x3 blocks?
Wait, thats not illigal?
