### ISSUE TITLE
More Utility For The Oct (And Commanders In General)

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#664]
**Describe the content or mechanics you are proposing.**
In my honest opinion, Oct should have more utility as a commander. Right now it's just a really big, rather slow carrier that can control six units, which isn't a whole lot. So here is a list of several improvements that would make Oct a much more useful unit, and a couple of tweaks that would make commanders in general more useful.

1. Give Oct more command capability. Right now six is not enough, unless you're hauling t4 units around with you. I personally think eight or ten would be a better amount, as it would allow for better protection and would allow the Oct to be more viable as a secondary combat unit. 

2. Give Oct the ability to act as a mobile resupply point. This alone would make it an extremely useful unit. The ability to store charge and ammunition and dole it back out again to units that need it would cement Oct's role as a t5 commander. Additionally, adding a SupplierComp.java class to the general classes would open the gates for future mobile resupply points. A possible smaller air-based resupply would be a useful future addition.

3. Allow Oct, and commanders in general, to match speeds with the _slowest_ unit in their formation. This may sound odd, but it would allow formations to stay together and not have them lag behind their commander, or break up entirely if some of the units are slower or faster than others. 

4. Make it so that Oct cannot command other Octs (or units without guns). This is just useless. 

5. Add PD turrets on Oct's perimeter, that draw from its internal power supply. This would give the Oct additional defensive capability, and add a second layer of defense in the event its shield goes down. 
 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
These features that I propose would complete Oct's featureset, changing its role from a secondary carrier to a primary commander/resupplier, and make it a more used unit. Right now the most used units (that I have seen) are the Reign, Toxopid, Corvus and Antumbra, for their combat capabilities. The Oct needs a little more love, and what better way to do that than to give it the role of supplying and defending even better than it already does?

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Colonizor48** [comment]
Yes this is good idea

**Comment by CapWarrior2** [comment]
Agreed

**Comment by sample-text-here** [comment]
I would replace the point defence with a slower repair point, but I agree with everything else
