### ISSUE TITLE
Allow logic blocks to read from messages

### ISSUE THREAD

**Issue by blahblahbloopster** [Anuken/Mindustry-Suggestions#666]
**Describe the content or mechanics you are proposing.**
Either make a new instruction for reading from a message block or make read able to get characters.  Also make the jump instruction comparisons compatible with strings.  Maybe add a codepoint op in the operation instruction.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will allow people to more easily make synchronized logic builds.  It will also make it easier to input large amounts of data to a program, like images.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
bruh no

**Comment by blahblahbloopster** [comment]
Why not?

**Comment by Colonizor48** [comment]
infinite memory storage. instead of using built in memory just use a message for infinite storage.

**Comment by blahblahbloopster** [comment]
Messages have length limits

**Comment by Kyllingene** [comment]
I personally _have_ a use for this right now. I want to make a unit controller with a unit selector, so you can easily swap between units, but the current way takes a bunch of jumps.
