### ISSUE TITLE
Redoing the Command Mechanic

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#667]
**Describe what you would like changed, and why.**
The command mechanic. Right now, it's a little non-intuitive for assembling squadrons. A commander will arbitrarily pick up units around itself and place them in formation, which can be irritating when you want to load up on high-damage units but accidentally pick up a couple of Monos instead. 

**Describe the changes you want to propose. Include possible alternatives.**
I propose that instead of simply picking up units when the command hotkey is pressed, _holding_ the command hotkey will highlight units in grab range, and clicking units while the command hotkey is held will add them to the formation. Command-clicking and dragging will allow a commander to reposition units in a formation around itself. Clicking units that are already in formation while holding the command hotkey will release them from the formation. 

EDIT (proposed/inspired by the-red-soul): one of two other mechanics should be added:
One: pressing a new hotkey would cycle the formation size and shape, or holding this new hotkey while scrolling would change the size of your formation. 
Two: dragged units would retain their location within the commander's command radius, effectively allowing custom formations. If this were implemented, formations should be able to rotate with the commander.

**Comment by Colonizor48** [comment]
Anuke pls add this.

**Comment by MEEPofFaith** [comment]
So like how you ctrl click to possess, you g click to add to control.

**Comment by Violet-Scarelli** [comment]
> So like how you ctrl click to possess, you g click to add to control.

Yeah, pretty much. I was thinking that would be more useful than just grabbing all the units around you.

**Comment by Meltdown-Altair** [comment]
yeah seems right
especially when you have toxopoids but the command button just pulls in the annoying monos nearby you

**Comment by MEEPofFaith** [comment]
or my army of corvuses

**Comment by Colonizor48** [comment]
> 
> 
> or my army of corvuses
https://github.com/Anuken/Mindustry-Suggestions/issues/627#issue-709828815
corvus is bad. you should probably be using erradicator or toxopod until it gets buffed

**Comment by the-red-soul** [comment]
An addition with this is the commands formation. With higher tiered units they have a larger command "pool" and can command more units, however the units formation tends to be in a very large circle away from the commanding unit  which is not nearly as useful. depending on the type of units commanded, say the T5 boat commanding its air army  the flares will be so far away that most of their fire will not even reach where you want. and for the T3 ground unit its the same issue. the unit circle is too large if you have enough units under your command. some way to control formation would be nice.

**Comment by Syncinus** [comment]
This would be much better, it makes the command system way less painful.

**Comment by BasedUser** [comment]
Workaround: ctrl+mouse2 removes a ship from your command.

**Comment by Xusk947** [comment]
and you cant command other plyer unit
