### ISSUE TITLE
Unit Spawners

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#668]
**Describe the content or mechanics you are proposing.**
New sandbox only unit spawners that would allow you to select a unit to spawn and how frequently to spawn it. Once these 2 things are selected it would spawn units until it couldnt anymore due to unit cap. All of it parameters could be changed by processors. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be very useful for maps where you want units to spawn passively. As the only way to do this now takes up a lot of space. And you cant easly change how often units spawn.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Syncinus** [comment]
This would actually be pretty nice, because in 5.0 the unit spawning of bigger units is easy, and mods will make it still just like a 7x7 block to spawn a reaper. It does need to have some kind of frequency setup though, because if it didn't then having it spawn eclipses at the same speed as flares would be broken.

**Comment by Colonizor48** [comment]
yeah. And its frequency should be controlable via microprocesser. That way you can make it speed up or slow down over time
