### ISSUE TITLE
Make it so the enemy can retake sectors you have already captured in campaign mode

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#669]
**Describe the content or mechanics you are proposing.**
The enemy should be able to retake sectors that you have already conqured. Conquring a sector would make it safe for the time being. But every turn the enemy would have a chance to launch an attack on that sector if the sector is bordered by unconqured sectors. The more unconqured sectors it borders the higher the chance is.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make campaign mode more interasting as it would mean you cant just dissasemble your defense once your done with the sector. You would have to keep updating the defense until you were able to retake all the sectors adjacent to it.  And it will make campign mode feel more alive and make the enemy feel like an actual enemy.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by userlol2** [comment]
Sounds interesting but its gonna be really bad when u have captured lots of sectors

**Comment by stuffyAI** [comment]
> every turn the enemy would have a chance to launch an attack

Every turn a chance for each adjacent uncaptured tile, I imagine having multiple planets half taken and just losing 5 sectors in one turn. Perhaps this could happen should you fail to capture a sector or every x turns you have to defend a sector.

**Comment by Colonizor48** [comment]
This wou

> 
> 
> > every turn the enemy would have a chance to launch an attack
> 
> Every turn a chance for each adjacent uncaptured tile, I imagine having multiple planets half taken and just losing 5 sectors in one turn. Perhaps this could happen should you fail to capture a sector or every x turns you have to defend a sector.
This wouldnt be too big of a deal if you just had defenses there.
