### ISSUE TITLE
Payload Overflow gates/sorters and liquid overflow gates

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#670]
**Describe the content or mechanics you are proposing.**
Literaly just overflow gates but for liquids and payload conveyors and sorters for payload conveyors.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be very very very useful in a number of circumstances. because right now we have to use these things respective routers instead of overflow gates. Which can cause inefficiencies which can be prevented with overflow gates.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by unjown** [comment]
nice 
phase condult too (i hope)
