### ISSUE TITLE
V6 Wiki

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#671]
pls add a v6 wiki especially for strategist
especially the call command of troops and thier "Evolution"

**Comment by itcannotbe** [comment]
You forgot this @unjown 

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
Also considering that v6 is still alpha. Changing the wiki over to v6 is unfeasible. v5 is still the latest stable and v6 is still a work in progress and a lot of adjustments are still going to happen. And doing so would make people think otherwise.

**Comment by unjown** [comment]
oh ok
good point but atleast the basics. :)
106 is ok
