### ISSUE TITLE
AA ripple

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#672]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
AA ripple 
an long ranged air kinda inacurate like ripple

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [/ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [/ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
to bad Anuken will no longer be accepting new turrets for 6.0

**Comment by Colonizor48** [comment]
this is literaly just the scatter/cyclone

**Comment by unjown** [comment]
> this is literaly just the scatter/cyclone

Dont u get it? LONG. RANGE SEMI INACCURATE AA

**Comment by Violet-Scarelli** [comment]
So kinda like 100mm flak?

**Comment by unjown** [comment]
> So kinda like 100mm flak?

yup 
but literally same bullet as ripple but attacks air only

**Comment by unjown** [comment]
> to bad Anuken will no longer be accepting new turrets for 6.0

@genNAowl not anymore he just said he will add something 2 turrets in dev prev in discord

**Comment by stuffyAI** [comment]
> not anymore he just said he will add something 2 turrets in dev prev in discord

those were determined a while ago
