### ISSUE TITLE
Enemy Spawn in sectors

### ISSUE THREAD

**Issue by Paum380** [Anuken/Mindustry-Suggestions#674]
**When the sector is captured, the enemy spawn will be deleted.**

**When capture the sector, the enemy spawn continues, and removing then it more easy to build on that area.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
I mean. You got half the template ig
