### ISSUE TITLE
Old "boost" mechanic

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry-Suggestions#675]
**Describe what you would like changed, and why.**

Currently most ships/mechs are very slow at moving and getting from place to place. However some of the ground support class have the old boost *flying* functionality that lets them go faster, however it is not that much of a speed increase. This boost button should be more generalized and available to more units so that you can have on demand speed when required. For ships it obviously increases thrust, for mechs it could 

**Describe the changes you want to propose. Include possible alternatives.** 

For ships obviously it increases their amount of thrust allowing them to move faster, as well as making turning more akin to the old javelin but less extreme. Bigger ships obviously dont get as much speed as smaller ones. Weapons are disabled or heavily inaccurate. For the T2 bombers disable their bombs.

For the ground mechs that are too big to fly on their own it could simply disable their guns and have them begin to sprint in a way, with or without some acceleration and depending on how big again, reduced turning capabilities. weapons disabled while sprinting or horrendously inaccurate.

If the ground mech is small enough to fly _like nova the old tau_ then it can keep its original functionality.

Walkers. . . . . im unsure if in theory they should actually be able to walk faster. . . . its a lot of large heavy legs that all need to be dealt with.

Boats could also have their speed affected but with a slower acceleration than the other units, and make turning not possible while at high speeds due to the risk of capsizing the boat. again bigger boat = less top speed like it is now.

I had more ideas but while writing this I kinda forgot what they were. If anyone has any other suggestions or reccomendations you know theres a comment section

**Comment by Colonizor48** [comment]
yesyesyesyesyes

**Comment by A5TR0spud** [comment]
Please
