### ISSUE TITLE
Carrier units(Mobile)

### ISSUE THREAD

**Issue by kingb74** [Anuken/Mindustry-Suggestions#676]
**Describe what you would like changed, and why.**
On mobile the main issue is that we can only carry one by one when using carrier units but on pc u can carry multiple which is kinda unfair

**Describe the changes you want to propose. Include possible alternatives.**
I propose that u add a button(sorry but I see it ass the only way)that u can use to differentiate between carrying and dropping cause it will make these units better to use and if u can add one for Oct that would be cool because if u wana carry as oct u control at the same time which can make problems

**Comment by l-Luna** [comment]
perhaps double-tap on a unit to pick them up, and double tap on the unit you're controlling to drop all?

**Comment by Syncinus** [comment]
IMO mobile controls should have a button for carrying, and double tap will trigger a command unit to make stuff into a formation.

**Comment by D-player1** [comment]
Double tap to carry and hold to release maybe? Idk

**Comment by Xusk947** [comment]
может все таки добавить UI элемент для этого?

**Comment by kingb74** [comment]
> Double tap to carry and hold to release maybe? Idk

Yea hold to release does make sense and then dovle tap the unit to carry it when close the double tap ure own unit to control others
