### ISSUE TITLE
Make the toxopid main gun non rotatable

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#677]
**Not using template, very simple suggestion**
The purpose of it being rotatable, from what I remember, was to show that the gun was actually there. Now due to the unit outline, that is covered and I don't think it should be rotatable anymore, as it looks weird in my opinion.

**Comment by kingb74** [comment]
This doesn't seam necessary I actually think its cool and makes toxopod more versatile
