### ISSUE TITLE
Total rebalance list

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#678]
**Describe what you would like changed, and why.**
Here i attempt to list and fix most of the block unbalances that exist.
Solar panels are *still* underpowered, they should cost less silicon or make more power, up to 5 p/s.
Arc was not stopped from being meta - maybe have it have decreased damage for each next enemy it hits?
Wave is too weak.
Cyclone is too weak, to the point that even Swarmer is stronger.
Spectre is too weak compared to Meltdown.
Parallax should get an even bigger range buff, there is currently no usecase for it.
There is currently no usecase for RTG - by the time you get the types and amounts of materials required to build it, you already have better power sources. If you don't, you wouldn't be able to obtain the materials in the first place.
Plast walls need a nerf - they allow for literal immortality if combined with proper other blocks. A possible nerf could be making them take double damage from lasers.
Buff crawler speed, they're the most useless unit currently.
Make enemy pathfinding not avoid shock mines.

If you have any critique about this list, feel free to comment.
(NOTE: the list does not cover small scale and long-to-discuss balance)

**Describe the changes you want to propose. Include possible alternatives.**
All specified above.

**Comment by BasedUser** [comment]
Arcs are weak enough. Toning up the power usage to 6 and focusing on coolant effectiveness would be more realistic.

**Comment by Ilya246** [comment]
No, you'll never make arcs weak by nerfing their power usage and coolant - you have to nerf their AoE.

**Comment by BasedUser** [comment]
> maybe have it have decreased damage for each next enemy it hits
but then also have a minor increase of the arc length

**Comment by D-player1** [comment]
1. Yes
2. Maybe decrease it's attack speed?
Also, people use ripples and scatters now
3. Use Tsunami (BE)
4. Swarmer ammo is a bit expensive
5. The coolant is just h, i'd rather spend my coolant on reconstructor.
6. I don't even know why this thing should exists in the first place.
7. Power usage can be even bigger sometimes, and this is also good for kickstarting when power fails
8. Ok
9. Less silicon and fast build speed, good for spamming, maybe make it as fast as half the speed of flare and cause fire

**Comment by Ilya246** [comment]
2 - Decreasing the firerate won't do anything, you have to decrease its AoE capability.
3 - What if you can't afford Tsunami because the fire *destroyed your economy*?
4 - The units it destroys are even more expensive.
7 - Except, if power fails in the first place, you probably wouldn't be having enough materials or thorium to build RTG arrays.z
9 - Yes, crawler could be made to cause fire.

**Comment by D-player1** [comment]
Hmm, kinda agree with 2 because i don't use it anymore, but
3. This is the ultimate pain in PvP, there's nothing you can do about it
4. Swarmer costs plast too, and people should be able to build T4 at that time
7. Tbh RTGs are only used when there's literally no more ways to make power except if you have thorium

**Comment by Xusk947** [comment]
salvo can over range 1.5 with thorium bullets, no?

**Comment by D-player1** [comment]
Also, adding to number 4, no one really cares about defense in PvP anyway

**Comment by Colonizor48** [comment]
Buff corvus and vela. they are really really bad compared to spider/dart trees

**Comment by Ilya246** [comment]
No, they're very good, it's just that plast walls need a buff; corvus and vela can snipe power nodes

**Comment by Colonizor48** [comment]
Vela barely does damage. Corvus can be stoped by a single layer of plast wall. And takes forever to fire. During that time it can be easly destroyed by several turrets.

**Comment by Colonizor48** [comment]
Also toxopod can snipe power nodes aswell. in adition to being able to build and having a much better attack.

**Comment by Colonizor48** [comment]
see https://github.com/Anuken/Mindustry-Suggestions/issues/627 for why corvus and vela need a buff. #buffcorvusandvela

**Comment by Ilya246** [comment]
How could corvus be destroyed by turrets when it ourtranges them all? But yes, vela does need a buff

**Comment by Colonizor48** [comment]
Segment is weak. It cant counter the toxopod. Plus it can literaly jsut step right over your walls like they are nothign and stomp everything. They dont even need to fire to be deadly. COrvus on the other hand takes longer then the age of the known universe to fire and reload. And is very very conerable while firing. giving plenty of time for an erradicator to come in and destroy it. Or for it to be destroyed by foreshadows.

**Comment by Ilya246** [comment]
Segment can indeed counter the toxopid, and do so well. Also, if you have a proper defense, the toxopid wouldn't be able to even get close. Fuse absolutely obliterates toxopid. And why would an eradicator come in and destroy it when it can just flee? Also foreshadows are an endgame turret and are supposed to do that.

**Comment by Colonizor48** [comment]
it would be able to if plastanium walls didnt exist. Even with your proposed nerf they would still be a hard counter to the corvus. and be even easier to setup then the segment. You could easly just spam mend projectors if they took more damage.

**Comment by Colonizor48** [comment]
also the fuse probably wouldnt be able to counter the erradicator. While not as long as the corvuses range it  is still nothiong to scoff at. And plus its bullets cant be abosrbed completly by a wall and deal no damage. The erradicator may not be bale to fire through walls but it can break though them with conciderable ease. Also lets not forget using the reaper. Those things can also snipe power nodes as they have beams on them. In adition to there other weapons. The fact of the mator is the corvus is weak and outclassed.

**Comment by Ilya246** [comment]
Plastanium wall has already been nerfed, about an hour ago. The problem is not Corvus being underpowered, but plast walls + segments + mendspam + fuse being OP. However, what you are saying is partially true, so yes, the Corvus may need a buff.

**Comment by Colonizor48** [comment]
I would say make the corvus and vela more like the quasar. give them sheilds and make thema ble to build in adition to making them faster. Buff the corvus by making it able to turn and move while firing and making it turn faster. But in compensation reducing its damage very slightly so it doesnt become overpowered. For the vela incresse its range and damage in adition to making it able to build and hgiving it a shield. keep in mind the shields wouldnt be that strong. Probably only slightly stronger then the quasar's shield. Also give them both a special healing pulse effect allowing them to heal nearby blocks and units.

**Comment by Syncinus** [comment]
Corvus is already overpowered, it doesn't really need a buff.

**Comment by Colonizor48** [comment]
Anything corvus can do toxopod or erradicator can do better.

**Comment by D-player1** [comment]
The real problem is that PvP are completely different than the other gamemodes. In survival yes, it's not that strong, but in PvP it's useful, it can fly and walk, countering ripples and scatters, it's ability to fly can be used to avoid enemy defenses and attack enemy power source and cause fire. So the problem is not how they're too OP or too weak, they're just stupid to do what they're supposed to do. (Basically AI problem)

**Comment by itcannotbe** [comment]
The real problem is anuke doesn't account enough for pvp during balancing.

All balancing is confined with campaign mode.

**Comment by itcannotbe** [comment]
On the subjects of arcs being powerful.
They are.

How about you make each succeeding node of one arc bolt deal half the damage of the preceding node.

**Comment by Colonizor48** [comment]
Vela barely does damage. i tested it and it barly does more damage then a gamma to an erradicator. Corvus is better but it turns too slow and reloads too slow to be useful. during that time being very very vonerable to other units. Mainly erradicator and toxopod.

**Comment by Colonizor48** [comment]
And on top of that the vela is almost in some ways a downgrade from the quasar. As it cant build. And doesnt have a shield and probably has simmilar dps.

**Comment by sample-text-here** [comment]
I agree that solar panels should cost less. The cyclone is weaker than a swarmer, but cyclones can take metaglass as ammo which is very cheap while the swarmer needs pyrite, blast, or surge. RTGs are good for kickstarting power and are the safest power source to use (If impacts go down, they take power, thorium reactors can explode, diff gens need power to get pyrite and cryo). Parallaxes are good at drawing enemies into scatters, but they do need a range boost. Also I agree with the shock mines - they're supposed to be undetectable by the enemy.

Also about the buff vs no buff for the corvus, I think they should be buffed. They used to have the longest range (making them good for sniping) but is now outranged by the foreshadow. Imo all t5s should be able to build. For attack, the toxopid is better than the corvus. (by spamming phase walls you can take out turrets faster than a corvus can)

**Comment by Colonizor48** [comment]
Yup. And i know from experiecne the erradicator is also better then the corvus. Yeah the corvus might be able to literaly attack through walls. But the erradicator can get through walls pretty easly as well and has range on par with a ripple. And once its behind your walls it does much much more damage then a corvus could ever hope to.

**Comment by DeltaNedas** [comment]
![h](https://user-images.githubusercontent.com/39013340/95358024-1d174100-08b8-11eb-9c14-47670f560fe7.png)

**Comment by DS-3K** [comment]
I think every tier 4/5 unit is kinda op :p

**Comment by TNT331** [comment]
swarmer is NOT OP, the ammo is expensive and it just drinks the ammo. Sure Cyclone also do but swamer is just na

**Comment by itcannotbe** [comment]
You're replying to a suggestion made based of things what ever build was mindustry on during the first week of october 2020.
