### ISSUE TITLE
Fog Of War

### ISSUE THREAD

**Issue by Xusk947** [Anuken/Mindustry-Suggestions#679]
***Add:***
- **fog**
- **radar**
- **jammer**
- **description**: add more new startegy in pvp or attack
-----
***FOG***
- **description**: darkness covering the field of visibility, it is impossible to see enemy units or enemy blocks in it if there is no radar or ally nearby, has its own types **"supply",** **"temporary",** **"not supply"**
- supply: supply if he is not in sight
- not supply: it is enough to explore the area once so that there is no fog
- temporary: something like un-rush time with a preset time
-----
***RADAR***
- **description**: allows you to see an area in the fog of war, when destroyed, it hides it if the type of fog (not disappearing), units and blocks in the radar zone are visible on the map
-----
***JAMMER***
- **description**: blocks visibility even in a fog that does not transmit radars cannot see its area of ​​action

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by summetdev** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/498
