### ISSUE TITLE
Increase first half of maps difficulty

### ISSUE THREAD

**Issue by abowen** [Anuken/Mindustry-Suggestions#68]
**Describe what you would like changed, and why.**

The first half of maps are incredibly easy so that the defense you typically build by wave 20 could last you to 100.

I'm a bit of a beginner, and with pretty much every map I could repeat the same basic tactics with almost little care of what I feed into turrets, and I could almost entirely ignore 50% of the items I was unlocking.  The only unlocks I cared about was gaining resources for more unlocks.
For example: outside the Phantom builder drone, I'm yet to build drones or feel the need for them.

It's not until Overgrowth until you actually have to REALLY plan about what to do. And the moment that I was wiped out, I was ecstatic. All of a sudden I started looking at mines, shields and assess what could work for this new boss.

While the game is addictive and we enjoy it, there was certainly no stress in those first few maps, or requirement for me as a player to adapt new strategies.

I feel increasing the difficulty would be a lot more rewarding for players, and make the early game a lot more interesting.

Additionally, this would increase replayability for maps
The first time you play a map, you scrape through to get to wave 30.
After a few unlocks + new strategies, you can now make it to wave 50.
Once you've mastered a bunch of strategies, you can make it to 100.

**Describe the changes you want to propose. Include possible alternatives.**

There are a variety of ways I'm sure you could do this but I'll list out what I think is the simplest 

Significantly increase the difficulty of waves for the early maps through increasing the amount of spawns. e.g. Where there is 25 enemies being spawned, make it 100

I know this is subjective, but my ideal play style would be:

- 1-5 waves: Gaining new resources, optimising product lines
- 6-9 waves: Preparing for next boss / upgrading existing defense
- 10th wave: Killing boss / fixing up everything it broke

This would lead to a stress / relief cycle for the player and continually assessing their weak spots.

Alternatives?

- Call this mode "hardcore" and leave it as optional
- Add a turbo mode that reduces time between waves + increase of rewards for finishing the map
- Increase the cost of turrets the more you place. It's just so easy to use a wall of early game turrets and not even bother with adding that new turret you just unlocked
- Give maps more specific enemies, such as maps that are flying only, or enemies that immune to certain damage types
- Set a limit of maximum of each turret you can do. This can only be increased by completing more maps and unlocking more turrets

**Comment by boogiebogus** [comment]
I would absolutely like if this was a "hardcore mode" setting, although not a basic thing. Although i think that if it does become a setting, it should be something you are able to turn on and off midgame.

**Comment by DS-3K** [comment]
Thank you for map making ideas! Hehe

**Comment by FedorDol** [comment]
There are plenty of maps on the steam workshop that can be quite challenging to survive mainly due to the shear quantity of enemy spawns. I am currently playing on Siege of Mount Xenothi and even with cryo cooled fuse walls holes in my defenses are getting punched. There are 14 enemy spawn zones on that map.

**Comment by FedorDol** [comment]
There are plenty of maps on the steam workshop that can be quite challenging to survive mainly due to the shear quantity of enemy spawns. I am currently playing on Siege of Mount Xenothi and even with cryo cooled fuse walls holes in my defenses are getting punched. There are 14 enemy spawn zones on that map.

**Comment by abowen** [comment]
Cheers. I'll see about playing those maps while I wait for the campaign to be balanced, or told that it's exactly how it should be.

**Comment by xetrov05** [comment]
How beginner friendly would this be? Someone who's only just getting familiar with the game under one minute/wave pressure or under the threat of a few extra liches isn't exactly very nice if you don't know a wall at a funneling point can wipe them all out.

**Comment by abowen** [comment]
There's a tutorial + you could leave first map as is if that's a large concern?
