### ISSUE TITLE
Logic feedback and ideas

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#680]
**This is made like a list, so I will list what I want changed along with the solution to them, in the same list item, as it's better then using the template**
The logic system is currently great, but I have a few problems with it that I think would be nice to fix.
### Major things
**- Sensor variables**: the problem with these is that some stuff in it like "@x" and "@y" apply to units and turrets, some of it doesn't, and the generic list in the last tab is large and contains a lot of stuff, it also lacks a lot of variables that would be useful, and some stuff that should have variables like @shootX and @shootY (like parallax) don't properly read them. What I think should happen is mainly, the sensor block should have categorized variables in it, like "this variable is for units" or "this variable is for turrets", etc. It would also be nice to see a few more things added to it, or using reflection of some sort to allow access directly to the values internally. Some other useful stuff would be the ability to see if a turret is being player controlled, and in general there needs to be a lot of extra variables and they need to be categorized. I would say the most important variables would be a block and unit type variable, to check what something is.
**- Lack of internal functions**: Mainly stuff like ``Prediction.intercept`` for turrets, turrets that aren't logic controlled have the advantage of being able to predict a unit position and shoot there, so it will hit, versus with logic that isn't possible, meaning that by logic controlling a turret to do specific targeting it means it will be less accurate then the actual turret AI is, and there is no real way to add this to logic from blocks because of how complex the function is. An essential thing is access to functions like this directly from logic, as they are really useful for making logic turret controls and other stuff.
**- Equality for units and blocks**: Right now blocks don't equal each other properly, there isn't really a way to check the type of a block, and the equality is messed up on them, as you basically have to use position to properly check if two blocks are equal, which is very painful to do. Units and blocks themselves should of course, be direct checking, unit and block types should check based on type.
**- Control block**: The control block is pretty useful right now, but it really needs to be more consistent, like a parallax tractor beam turret doesn't get affected by the shoot block. What control is mainly lacking right now is the ability to set block config, this is extremely important imo, as it will allow logic to do a lot of useful things, like automatically alternating a unit factories units between a few things. It could also use a few other functions, but I believe that config really needs to be a settable thing on it.
**- Optimization**: One of the things that is noticable on servers with a lot of logic, is that it causes a lot of lag, even when you aren't directly looking at it, it seems to reduce your FPS. Logic needs a lot more optimization, as it's caused my gaming laptop to go down massively in FPS, and I bet it causes the game to become nearly unplayable on mobile.
**- Memory cells**: Currently memory cells are only able to store numbers, it makes sense why, but they should also be able to store stuff like blocks, units, strings, and other data types, to allow passing that stuff along. Those should maybe take more slots in the cell or something like that, to ensure it's not too good, though that would bring up a few problems because of things like "what if you access x slot, but it's covered by a larger value" and therefore return the larger value, or what happens if you set something on a slot that is covered, would it delete the larger value, or corrupt it? And it could end up very confusing.
**-Link naming**: Number assignement to stuff can get really annoying, when you deselect something, it should free up the number, and it should always try and take the lowest number possible, or at least have some system to clear up previously numbered things, as this gets really finicky in setting things correct. Something that would be useful here would be allowing you to assign names to links, like being able to change the name of a radar turret to "enemyDetector" or something like that.
### Minor things
**- Radar**: This isn't too big, but there should be the ability to set a radius of radar, and also set it to run on an arbitrary position, this is useful for turret setups, and detecting units from farther away and triggering some kind of event chain as an alarm.
**- Player controls**: There is a lot of stuff that could be done to this, like having some kind of "player controller block" that allows a player to attach to it with ctrl, and then allows the logic to switch the player between controller blocks, allows for keyboard input, and allows for camera position changing. This kind of system would be very useful in doing some kind of large scale base control, or like switching into a whole array of turrets and firing them. This isn't too important, and it might be a bit too complicated for something that isn't super important, but it would be really interesting to see and use.
**- Quality of life blocks**: Mainly if statements, loops, comments, a "set if not already set", and possibly functions. If statements, loops, and functions would allow for much less clutter, as a lot of jump statements makes it messy very quickly. Comments are self explanatory of course, they let people understand what your thing is doing, which is useful when playing online, and a "set if not already set" would be nice to have for most programs because a lot of the time you are trying to define a variable, and you need to use a bunch of jump blocks to avoid redefining it, if it isn't going to end up being constant.
**- Faster instruction execution, processor clusters**: If there are big programs, then what I think should happen is processors should be able to "cluster", by putting processors next to each other there should be some kind of ability to "link" them directly, and make a cluster, and allow for higher execution speed. I don't know if this would be really too practical because it might make microprocessor overpowered, but having it do this on hyperprocessors would allow for bigger programs without having to set up clusters in a weird way.
**- Objects and more complex data types**: Kind of like JS objects, a collection of keys and values, arrays would be interesting, but I don't think they would really fit or work very well due to them needing stuff like a "push" function, or having then be an exact length which I don't think would be really liked.

**Comment by UtoECat** [comment]
Arrays would be really useful, since it is very difficult to implement them on memory cells and loops

**Comment by Colonizor48** [comment]
yes we need this. Logic shouldnt be based on friccin assembly.

**Comment by itcannotbe** [comment]
It's not even assembly...............

**Comment by DeltaNedas** [comment]
i agree with basically this whole suggestion but:
- i think a tuple cell should be its own block as it's different from standard double array
- loops, functions, etc. are best left to higher level languages
- logic processors shouldn't have arrays, objects as it almost entirely defeats the purpose of memory cells

- if logic is killing server break spammed setups.
additionally, my phone can run lots of anukes fine, in sure my old 2ghz i3 laptop that blew up wouldn't have trouble compared to your "gaming" laptop
- @Colonizor48 go away

**Comment by UtoECat** [comment]
> yes we need this. Logic shouldnt be based on friccin assembly.

i disagree with your opinion. 
I partially agree only that it is difficult and time-consuming.

**Comment by Colonizor48** [comment]
Why Should logic be based on Assembly? A language known for being hard to read and write in.

**Comment by Colonizor48** [comment]
Logic should be as easy as possible to read and write in. While Still having advanced features for those who wish to use them. Right now it is cluttered and hard to read.

**Comment by UtoECat** [comment]
> Logic should be as easy as possible to read and write in. While Still having advanced features for those who wish to use them. Right now it is cluttered and hard to read.

Not always...

**Comment by Colonizor48** [comment]
> 
> 
> > Logic should be as easy as possible to read and write in. While Still having advanced features for those who wish to use them. Right now it is cluttered and hard to read.
> 
> Not always...

Why Not? You cant just say not always. You have to give a valid reason.
