### ISSUE TITLE
Please add a code comment

### ISSUE THREAD

**Issue by lotanzoe** [Anuken/Mindustry-Suggestions#681]
The joining method is similar to adding a sentence, but you can write comments. 
Otherwise no one will be able to understand what I wrote>_<

**Comment by rmperkow** [comment]
It would look like
`comment [string]`

**Comment by Quezler** [comment]
did you mean: being able to add comments to logic blocks?

**Comment by lotanzoe** [comment]
yes. 
Similar to game "Human Resources Machine"

**Comment by sample-text-here** [comment]
#413
