### ISSUE TITLE
Logic NEEDS the trajectory calculation normal aiming has

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#682]
**Not using template, suggestion too simple**
Normal aiming uses ``Predict.intercept``, logic really needs this, right now setting a turret to target stuff with logic is nearly useless due to the lack of that, because it causes the turret to waste loads of ammo trying to hit anything flying. We really need some method of using functions like that integrated into logic, because of how useless it renders it when trying to hit wraith and small units like that.

**Comment by potatoisagender** [comment]
excuses scamuses

USE THE TEMPLATE >:(

/s

**Comment by itcannotbe** [comment]
No. Because you're removing the drawbacks of turret with accuracies greater than 0 and turrets with bullets that have a slow travel speed.

**Comment by Syncinus** [comment]
Okay shootp exists now, closing
