### ISSUE TITLE
Scrap Walls

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#683]
**Describe the content or mechanics you are proposing.**
New crafters and scrap walls to be available to build.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Since scrap walls cant be built why not make a new crafter so you can build them.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Colonizor48** [comment]
yeah you should be bale to make scrap walls but what da hecc is a "new crafter"

**Comment by DevZeff** [comment]
@Colonizor48 it means a new craft8ng device for mindustry so you _**can**_ make a material from scrap to make the walls

**Comment by Colonizor48** [comment]
Why is that needed? Why not make them literaly like very other kind of wall?

**Comment by Colonizor48** [comment]
As in you just use scrap to  make them

**Comment by stuffyAI** [comment]
>     * I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Are you sure about that?

**Comment by Tokuu** [comment]
Are you guys replying to my issue or did ghost just copy my whole goddamn issue
