### ISSUE TITLE
Transmission Tower

### ISSUE THREAD

**Issue by NexusDarkshade** [Anuken/Mindustry-Suggestions#684]
**Describe the content or mechanics you are proposing.**

Similar to the Surge Tower, the Transmission Tower would cover a large area, but instead apply to logic blocks. It would would function similar to a processor, but only be able to make two links and only use the read, write, sensor, and control commands. Its main function is transmitting data over long ranges: instead of using a chain of many processors and memory cells, wasting valuable space and resources, you could instead use 2 or 3 Transmission Towers and memory cells to cover one side of the map to the other.

**Stats:**
Health: 200
Size: 2x2
Build Cost:
- Lead: 360
- Thorium: 50
- Silicon: 100
- Surge Alloy: 25

Link Range: 62 blocks
Links: 2
Instructions: 240 /sec

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would allow for easier long-range data transmission.
**Example:** You have some resource intensive system across the map from your core. Due to resource limitations of the map you are on, you need to launch resources from another map into this one and send it via mass driver to your system (because there is no more room for belts, and/or you need _speed_). There is a vault in your system which supplies it with the resources it needs, which the mass driver feeds the resources into. You want to use logic to manage which resources the drivers deliver from your core, based on the stock in the vault. Normally, you'd have a chain of dozens of micro processors (or several expensive hyper processors) to send this data, but you'd only need a few Transmission Towers to do the same function.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
Could be called a radio tower, radio transceiver, or something similar.

**Comment by itcannotbe** [comment]
Could have a better title.

Like " Transmission Tower, a better way to connect distant logic blocks".

But this makes sense.

**Comment by NexusDarkshade** [comment]
> 
> 
> Could be called a radio tower, radio transceiver, or something similar.

including "radio" in the name would imply that it could make many links.

**Comment by RogueRedHawk** [comment]
@NexusDarkshade Perhaps it could? You could put maybe op to 16 unique values and transmit them within some range, and there could be a logic command for reading these transmissions. This limits the throughput of data at such a long range, and filled a niche of dissipating information over a large area quickly. (Perhaps fill field 1 with a number depending on whether the base is in defense mode, offense mode, etc.)

**Comment by DS-3K** [comment]
This seems like a _logical_ suggestion to me! xD

**Comment by NexusDarkshade** [comment]
> 
> 
> @NexusDarkshade Perhaps it could? You could put maybe op to 16 unique values and transmit them within some range, and there could be a logic command for reading these transmissions. This limits the throughput of data at such a long range, and filled a niche of dissipating information over a large area quickly. (Perhaps fill field 1 with a number depending on whether the base is in defense mode, offense mode, etc.)

So, you're saying instead of a Surge Tower but for logic, it's a memory cell + processor?

**Comment by swenkeratmicrosoft** [comment]
I think the original "Only Two Links" suggestion is sufficient.

Really, what I want is to send a single yes/no value all the way across the map.

Here's pseudo-code for how useful this would be:

Logic Processor #1: If Thorium at "Core: Nucleus" is full (13000), write 1 to memory block A.  Else, write 0 to memory block A.

Transmission Tower: Read memory block A, write memory block B.  A and B are very far away.

Logic Processor #2: Read memory block B.  If 1, turn on Thorium Mine.  If 0, turn off Thorium Mine.

Thus, you stop mining Thorium if your core is full even when the actual mine is far away from your core.

**Comment by FlyveHest** [comment]
I've just started playing with the logic part of Mindustry, and this was literally the first thing that came to mind when I wanted to try something a little more advanced than turning of a burner when batteries are full :)

If it needs to be a little more limited than just over-the-air signalling, it could just be a kind of network cable you could connect two memory cells together with, and then they would just mirror the values, if you write to register 0 at cell A, then register 0 at cell B would be updated at the same time, and vice versa.

I think the functionality sort of could be done with just chaining processors and cells, but that takes a lot of space and would just be really tedious to do.

**Comment by swenkeratmicrosoft** [comment]
@FlyveHest 

> I think the functionality sort of could be done with just chaining processors and cells, but that takes a lot of space and would just be really tedious to do.

Great minds something something?  ;)

> You can do it with existing processors, but it's really expensive in resources and takes up a ton of room.
