### ISSUE TITLE
Corvus and vela(balancing)

### ISSUE THREAD

**Issue by kingb74** [Anuken/Mindustry-Suggestions#685]
**Describe what you would like changed, and why.**
Corvus and vela need a buff cause I mean sure they are quite op as they are now but compared to a unit like toxopid/araknid their not worth the hassle to make them and lack in fire power

**Describe the changes you want to 
propose. Include possible alternatives.**

I peopose u give them something like a shield or something like that to give it more defence because these troop get annihilated when alone or just better healing capabilities cause corvus heals slowly and vela(not sure if it does heal didnt check)but im just saying a little buff to make them worth it helps alot

**Comment by D-player1** [comment]
They are OP in PvP

**Comment by kingb74** [comment]
> They are OP in PvP

They totally are but not as much as araknid or toxopid thats the problem

**Comment by Colonizor48** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/627

**Comment by SirMachinegun** [comment]
its about strategy, corvus should keep a long distance between its enemy so while he can hit the enemy wouldn't be able to.

I can't tell anything about vela though, maybe damage and range increase?
