### ISSUE TITLE
Mindustry protocol

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry-Suggestions#686]
I am suggesting a `mindustry://` for the game, so you can make links which automatically start the game and connect you to the server. I am already providing these links at https://mindservlist.de but obviously they don't work yet.

I see this is only a QoL feature, but would be kinda cool to have these since they are easy to add and a lot of people could use them on their websites (and discord servers also I think?).

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
> I am already providing these links ...
Why?

**Comment by Shawak** [comment]
Because why not, it's not like I can link anywhere else anyways. But how is that important to the request?

**Comment by summetdev** [comment]
Good

**Comment by sample-text-here** [comment]
Ideas
- `mindustry://schematic/<base64>` (download a schematic)
- `mindustry://join/<ip/url here>` (join a server)
- `mindustry://map/<base64>` (download a map)

**Comment by Quezler** [comment]
schematics & maps in the url might become massive 🤔

**Comment by Shawak** [comment]
Yeah that's a prettz good addition, I like the idea a lot! Also it should be fairly simple to implement.

**Comment by DeltaNedas** [comment]
maps would not work at all, schematics would be fine though (assuming its not something like a 200x200 portrait of the cat)

**Comment by sample-text-here** [comment]
Yeah, the map uri would be too big (although afaik there isn't a uri length limit). Also, `mindustry://help/<internal name>` would be nice and could help with links from inside the game. 

(Yes, I meant to type [uri](https://stackoverflow.com/questions/176264/what-is-the-difference-between-a-uri-a-url-and-a-urn) not url)

**Comment by Kyllingene** [comment]
The server joining mechanism would be interesting. I personally have no use for it, but acknowledge the usefulness. However, the thing I'm worried about is advertising (Example: A hyperlink such as "More Info" that really opens Mindustry to a server).
