### ISSUE TITLE
Suggestions on new control methods 关于新控制方式的建议

### ISSUE THREAD

**Issue by CPXMC** [Anuken/Mindustry-Suggestions#687]
**Describe the content or mechanics you are proposing.**

添加一对摇杆,用于控制移动和攻击，有一个按钮用于切换它和滑动的操作模式，还有一个准星用于瞄准，然后在滑动的操作模式下在屏幕中心也添加一个准星，用于查看移动的目的地（可以自动隐藏）[仅限安卓]

Add a pair of joysticks to control movement and attack. There is a button for switching its and sliding operation modes, and a crosshair for aiming. Then in the sliding operation mode, add a crosshair in the center of the screen. To view the destination of the move (can be automatically hidden) [Android only]

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

它应该可以使安卓用户的操作更好。
我提出该建议的原因是安卓版本的客户端在多人服务器中，v107版本新添加的水上单位的控制不是很正常(总是无法航行到屏幕中心，会向一个方向一直移动），PC版本则没有该问题。

It should make the operation of Android users better.
The reason I made this suggestion is that the Android version of the client is in the multiplayer server, and the control of the newly added water unit in the v107 version is not very normal (it is always unable to navigate to the center of the screen and will move in one direction), while the PC version is There is no such problem.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by CPXMC** [comment]
我希望在移动平台是这样

**Comment by CPXMC** [comment]
I hope this is the case on the mobile platform

**Comment by itcannotbe** [comment]
Isn't this topic discussed to death ever since 3.x?

Truth of the matter is mobile has a small screen. Adding more controls to the game would result to a cluttered screen. If you want better control just use mouse+keyboard controls.

**Comment by itcannotbe** [comment]
Also. #632
