### ISSUE TITLE
Coloring/Naming Sectors

### ISSUE THREAD

**Issue by WarmWooly** [Anuken/Mindustry-Suggestions#688]
**Describe the content or mechanics you are proposing.**
What if there was a way to name and/or color sectors on the planet, such as a settings button on the menu when you click on the sector you want to edit. It would give you a menu that will let you choose the color of the sector (similar to how you set lighting in custom maps) and a rename option that will let you change the name of the sector, while also having a button to reset it back to default.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
With so many sectors I control, it gets increasingly harder to find my 'main base' sector, or to keep track of the current sector I'm in. Also, any campaign levels that have merged with my sector 'blob' are very difficult to find.
A blob of sectors close together:
<img width="517" alt="Screen Shot 2020-10-04 at 6 19 17 PM" src="https://user-images.githubusercontent.com/68318069/95028591-22357f80-066f-11eb-8a73-f023c640a1e4.png">
Lastly, sectors that I have dubbed for specific reasons (such as Otter Caverns dubbed for the shape) would be lost if I didn't keep a sheet of paper by my side.
Otter Caverns:
<img width="751" alt="Screen Shot 2020-10-04 at 6 23 15 PM" src="https://user-images.githubusercontent.com/68318069/95028573-fe723980-066e-11eb-9e29-2a5428fd7095.png">
It will make the planet more manageable, and will take away the stress of looking through multiple sectors to find a certain one.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by JamesTheNerd** [comment]
that would be nice

**Comment by dudecon** [comment]
We now have the ability to re-name and add icons to sectors. Colors would be nice too, but I feel the current functionality is sufficient.
