### ISSUE TITLE
Naval Units and Naval Defense Systems

### ISSUE THREAD

**Issue by IEternityI** [Anuken/Mindustry-Suggestions#69]
I propose that the developer would add naval units to the game. The factories of light naval units could only be built adjacent and/or in shallow water. The factories of heavy naval units, however, could only be built adjacent and/or in deep waters. 

The structures that will defend against these units could also be placed in shallow/deep waters, and could target both light and heavy naval units. Existing defensive structures may also be configured to attack and destroy these naval units if they will be implemented in the game.

These are my suggestions for units that may be implemented in the future:

1.FAC (Fast Attack Craft)-Light Ship
FACs are the lightest naval units. As their name suggests, they are extremely mobile and can be overwhelming when used in swarms. They may be the naval equivalent of Dagger units.

2. Frigates/Destroyers-Light Ship/s
Frigates and Destroyers are often used as escorts for larger vessels. They may be used to detect and clear naval mines. They can detect submarines, but couldn't attack them because of the lack of proper armament. (Although Destroyers are commonly larger in size and more powerful in armaments.) They are mobile, have considerable armor and light armament. They may be the naval equivalent of Titan units, but with much higher range.

3. Cruisers-Heavy Ship
Cruisers are commonly the largest warships in many nations' navies today. They play many roles, including submarine and mine detection. In-game, they have heavy armor, slow moving and with powerful long range armament and torpedoes for self-defense against submarines. They may be the naval equivalent of Fortress units. 

4. Dreadnoughts-Heavy Ship
Dreadnoughts used to be the most powerful ships. They are armed only with large-caliber guns and are heavily armored, however, they are extremely expensive to manufacture. There are no Dreadnoughts in active service today because the preferred method of warfare is no longer face-to-face, where the Dreadnought excels. Dreadnoughts may be a type of boss unit in-game, or an extremely expensive naval unit that can be produced by the player.

4. Transport- Light/Heavy Ship
Transports can be used to transfer ground units from one place to another via water body. They may be lightly armored or heavily armored, and bear no arms.

5. Submarines
Submarines could move undetected without the proper countermeasures, so they may be used to ambush underprepared opponents. In-game, they may be armed with long-range missiles against land units/structures and torpedoes for naval units. They may be detected by Frigates/Cruisers/Destroyers. The only structure that could detect them is the Typhoon. (Elaborated below.)

Suggestions for Naval Defense Systems:

1. Typhoon
Typhoons can target both naval and aerial units. They may use flak/Surface-to-Air Missiles for aerial units and torpedoes/Surface-to-Surface missiles for naval units. If submarines are implemented, the Typhoon is the only structure that could detect them.

2. Naval Mines
Although deemed as inhumane, naval mines are extremely potent against naval units. If submarines are implemented, they could trigger naval mines but will not be revealed unless destroyed.

Extra-currently existing turrets that can possibly target naval units are:
Lancer, Salvo, Cyclone, Hail, Spectre, Ripple, Meltdown and Swarmer.

Adding naval units and the structures to counter them would add more depth to the game. Implementing these features would add some function to the water bodies of Mindustry, instead of just having them as sources of water to use as coolant and produce cryofluid. 

I hope some of these features would be implemented in the game. Thank you for reading.

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by YouDontSay1** [comment]
That is a good idea. Also, when there are naval units, naval mech pads would also be cool.

**Comment by Nat3ss** [comment]
I like this idea. Adds a whole other layer to mindustry. Though it would undeniably take a lot of effort and hardwork.

**Comment by itcannotbe** [comment]
I like this idea. But the problem is, it's already implemented before this suggestion was made.

**Comment by Colonizor48** [comment]
nice
