### ISSUE TITLE
support and specialist naval

### ISSUE THREAD

**Issue by Suggestedone9** [Anuken/Mindustry-Suggestions#690]
**Describe the content or mechanics you are proposing.**
I have and have had for quite a while now what the specialist and support navy could look like. Everything here is just a vision for what it could be like and can be changed if it needs to be.

support- support naval could be a sort of carrier class, in which the units produce either support (low tier naval) or attack (t3 and above naval) aircraft. They could function in a similar way like the omura, but with some other features. T1 could produce 1-2 monos and T2 could make 2 monos and 1 poly. They would also have the ability to heal nearby units. T3 and above could work in a squadron sort of way. T3 can produce and mange 1 squadron of about 4 flares and 1 horizon. After about 2-3 minutes any remaining aircraft would return to the carrier and heal up. Any missing aircraft would be recreated. Squadrons could only launch if all aircraft are ready on the carrier. T4 could manage 6 flares and 2 horizons per squadron with up to 2 squadrons and could have a medium range missile battery similar to the sei, but weaker. T5 would be a massive (bigger or around the size of the omura) carrier that could manage up to 3 squadrons and would have 8 flares, 3 horizons and 1 zenith per squadron, and would have 2 medium range missile batteries. Their appearance would be a sort of blocky/octagonal long platform. Their names could be based around trees with their names based around the size of the tree. They could have medium range health and extremely slow speed.

specialist: specialist could be a type of submarine vessel that would hide underwater. If the vessel isn't moving in shallow water for 2 seconds it submerges until it moves. If its in deep water it can submerge after 2 seconds even if it is moving, however, it would move much slower than above water (about 3 times as slow). If the vessel is submerged, other vessels can go above it. It also cannot be seen by any other turret or unit and disappears completely to the enemy team (friendly units and players could see a dim outline of the unit if it is submerged. Its weapons would be a new type of missile that has a full on sprite(like a unit) and could pass over walls like artillery projectiles. It would also be more durable compared to regular projectiles, taking more shots from a segment to be destroyed. It would also have none to barely any inaccuracy. It would have a explosion similar to that of the bombs dropped by a quad, just without the green colour and the "star" in the centre. The missiles would be its only weapon and can only be used under water, a bit like a submarine launched ICBM. Submarines would have missile silos. The missile silo is essentially a static barrel locked to the submarines rotation. The more silos there are, the longer it takes one to reload a single silo, however, it also means that more locations can be targeted at once. This is the main "threat". A sub can target several locations in one launch volley. T1 has one short range silo with a low yield weapon. T2 and T3 are similar, but with better range and with +1 silo per tier. T4 would have 6 silos with the ability to multi target(pervious ones would have the missiles fire in the vicinity of the target). T5 could have weapons capable of doing similar damage to thorium reactor explosions, and would have up to 10 silos with a long interval between shots and would have a massive 65 block range. Their appearance would be a sort of elongated pill with certain parts expanded i.e by the middle wider. They could be named after sharks(this would work like the attack naval naming system). They would have the lowest health range out of everything, having significantly less than other units. In order to get rid of them, naval mines could be added or a sort of torpedo turret class. Their AI would be significantly more advanced than other units, being practically blind when submerged. This means other units must spot for them, or they have to surface to get the positions of building. They would also be more focused on destroying things, hiding when they find threats and focusing on their destruction. They could also have a sonar vision when submerged, only showing units in water and other submarines, while only showing the shore and not showing things on land.
 
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would add a whole new threat and defence system to the game, making players want to be more aware of coastlines and water bodies for any possible threats. It would also add more potential for modding community, providing a new type of unit classification and a new type of defence.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Suggestedone9** [comment]
i forgot to mention that submarines have a medium-slow speed above water and that it takes a submarine 3 seconds to submerge/surface and that it needs to wait 10 seconds after surfacing to submerge. It can also force a surface by pressing `shift`

**Comment by 5382Ander2** [comment]
I think submarines should be purple naval
