### ISSUE TITLE
Allow Repair Points to be Boosted

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#692]
**Describe the content or mechanics you are proposing.**

Let Repair points be boosted by liquid coolant or silicon. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Repair Points, being 1x1 and kindof like menders for units, and should have the same boost capabilities as well. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
Partially Relevant: https://github.com/Anuken/Mindustry-Suggestions/issues/364

**Comment by Quezler** [comment]
i'm in favor of of giving the existing one a liquid based boost that increases range & heal speed 🤔 
(probably lots of it, and only uses it when the beam is active, 50% range increase and 250% heal)

**Comment by genNAowl** [comment]
bonk
