### ISSUE TITLE
(QoL) A New ‘Advanced’ Sorter and Unloader

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#695]
**Describe the content or mechanics you are proposing.**
A new advanced sorter(includes inverted) and unloader. Possibly purple (logic and such). They would have logic support, and you would be able to select multiple items to filter out.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would seriously compact some belt spaghetti. And it makes sense that you would be able to select multiple options.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Why would such compact a "conveyor belt spaghetti"

**Comment by potatoisagender** [comment]
hasn't this been suggested?

**Comment by potatoisagender** [comment]
#432

**Comment by mick-2006** [comment]
This is so much better that my blocker ideas I might scrap it

**Comment by stuffyAI** [comment]
> It would seriously compact some belt spaghetti. And it makes sense that you would be able to select multiple options.

So you want the game to be easier. Mods should be able to do that for you

**Comment by potatoisagender** [comment]
I still haven't gotten a response, because #432 is the exact same. This is useless now.

**Comment by A5TR0spud** [comment]
That is for the old blocks to get a new feature, not for a new block to have that feature.

**Comment by A5TR0spud** [comment]
> Why would such compact a "conveyor belt spaghetti"

Imagine if you want 3 materials from a conveyer with 6 on it for some reason. Or you want to take 4 different materials from the core. You would have to build entirely different lines and combine them, so maybe not seriously compact, but compact nonetheless.

**Comment by A5TR0spud** [comment]
Again, this is quality of life, not a necessity.

**Comment by A5TR0spud** [comment]
That was for a feature in an existing block, this was for a new one.
It would compact spaghetti - by letting you pull multiple resources without unloaders/sorters and a bunch of conveyors to merge them.

**Comment by potatoisagender** [comment]
Not really a new block, and the other can be interpreted as a new block as well. 

> It would compact spaghetti - by letting you pull multiple resources without unloaders/sorters and a bunch of conveyors to merge them.
I guess, though I don't know how much space you would save with all the other logic elements...
