### ISSUE TITLE
(QoL) Radar Block for Logic

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#696]
**Describe the content or mechanics you are proposing.**
The idea is simple. There would be a radar block in the logic section, which has a range and can be used with the radar command in logic to sense things. It would have a few upgrades and get bigger each time. 1x1 is slightly farther than a duo. 2x2 fairly large. 3x3 is absolutely huge, but needs cryo and maybe some power. It would let processors sense things farther away, without using a turret and/or taking away from the aesthetic.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would look good with processors, and have a long range due to that being their sole purpose. Maybe some balancing though? They would probably consume power.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
[X to doubt] I have done a quick search in the list of suggestions to make sure this has not been suggested yet

#456

**Comment by potatoisagender** [comment]
prob searching open.
