### ISSUE TITLE
New Specifically Fast Unit

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#697]
**Describe the content or mechanics you are proposing.**
A unit that is meant for *s p e e d*. That is it’s sole purpose. Sure, it can attack, just not accurately. Pretty fast attack speed and movement speed. Fairly low damage, health, and ammo capacity. Every upgrade, it gets faster, less accurate, faster attack speed, slightly higher ammo capacity, and a bit more health. At T3 and above it has a mini-shield thing, those orange orbs that act as extra health (not force). When it’s not being controlled, that doesn’t mean it’s useless. It’s not a bad hit-and-run drone, but don’t expect it to come back alive. It would use electricity as ammo and would also use *tiny tiny* lancers as weapons instead of bullets or arcs. It is the purple specialty drone of the skies.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
So far the fastest air unit (afaik) is the Gamma. A default unit. We don’t have a nice, fast unit for players to control. Not since javelin was removed. This would provide a speedy way for players to get around. Sacrifices were made for the shear speed of this. A very fragile, light, aerodynamic craft with little weapons and ammo to way it down, just enough to protect itself.

Update: maybe they should increase attack speed per upgrade?

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Syncinus** [comment]
It would be nice to see a quick kind of unit, right now things like oct that are made for building are painstakingly slow, so having a unit that could just zoom around would be pretty cool. Though IMO they should be armed a bit somehow, preferabbly with some kind of high speed weapon like cyclone, and the tier 5 should be faster then the tier 1 is, and basically the speed should go up per tier instead of down.

**Comment by MEEPofFaith** [comment]
And as we've discussed in DMs, the names would be:
`dart -> arrow -> spear -> javelin -> harpoon`

**Comment by Syncinus** [comment]
They should have similar abilities to the old javelin, like they build up some kind of speed cone thing as it gains speed.

**Comment by unjown** [comment]
My suggestion for this :
Name: phase something
Materials to build unit: Phase, Titanium
Materials to build unit fac: phase ,plast, Thor ?

**Comment by MEEPofFaith** [comment]
Why would it have its own factory? Just use the Air Factory.

**Comment by unjown** [comment]
> Why would it have its own factory? Just use the Air Factory.

good point 
but its up to anuke to decide 
Anuke havent seen this i think should i tag(ping) him

**Comment by A5TR0spud** [comment]
wait a bit more before pinging him

**Comment by unjown** [comment]
> wait a bit more before pinging him

now?

**Comment by A5TR0spud** [comment]
maybe

**Comment by DS-3K** [comment]
Haha, unit goes brrrrrr

**Comment by A5TR0spud** [comment]
in case you're wondering, MEEPofFaith and I are working on a mod that adds these. MEEPofFaith/purple-air-units
