### ISSUE TITLE
Allowing proper block placement for carriers

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#699]
**Describe what you would like changed, and why.**
Recently in a multiplayer game, I found it very difficult to use the block movement feature on an oct, it really doesn't position properly. It's pretty much useless right now, on oct at least, on quad and mega it can at least be used to some degree of positioning.

**Describe the changes you want to propose. Include possible alternatives.**
When you press the "]" key, it should allow for you to select within a certain area where the block should be placed, or it should be a system where you hold down they key and it allows for you to select a position and drop it. This will make placement much more practical, and allow carriers to actually be used to move blocks around, which will make the carry feature much more useful then it currently is.

**Comment by sample-text-here** [comment]
I think it would be nice to tap ] to place the block, but hold it to highlight where it would be placed. This way you can move and see where the block would be placed.

**Comment by Syncinus** [comment]
Yeah, that is kind of what I was thinking would be how it should work.
