### ISSUE TITLE
Build while flying ground mechs

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#7]
**Describe what you would like changed, and why.**
It used to be that building while flying was possible, but since the shift key is now used to copy to clipboard, it is not possible to build any items while flying in a **ground** mech (because the fly and copy share the same key).

**Describe the changes you want to propose. Include possible alternatives.**
Change the copy feature so that if the user is flying a **ground** mech it will select the item instead of copying it.

**Comment by Katsute** [comment]
The current setup is especially noticeable when trying to build when flying over water. (when playing USS Iowa, or Ariel Command Cruiser for example)

**Comment by DS-3K** [comment]
I would suggest planing out your building while it´s paused and unpause it while fliing if you really need to fly while building. Also, if you´re hovering over a tall block you don´t need to hold the shift key.

**Comment by Katsute** [comment]
> I would suggest planing out your building while it´s paused and unpause

Doesn't work on multiplayer.
> Also, if you´re hovering over a tall block you don´t need to hold the shift key.

True but it wouldn't work when nothing has been built yet.
