### ISSUE TITLE
[modding] custom bullets should be able to use and modify all built in bullets

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry-Suggestions#70]
**Describe the content or mechanics you are proposing.**

Custom defined bullets are currently limited to 8 specific types

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think it would expand upon what's possible with json/hjson modding, such as an item turret with a more powerful lancer laser

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This was implemented in 6.0.

**Comment by Solokil** [comment]
i have done a hjson file with a bullet script... but I do not know the name of the content folder to put it.. some one can tell me?
