### ISSUE TITLE
Facet query and navigation

### ISSUE THREAD

**Issue by isergey** [Anuken/Mindustry-Suggestions#701]
Hello!
Need next things in facets:
1. Filters and queries by facet values. Eg:
```
facets: {
   phrases: [
      [ aaa bbb ccc, 200],
      [aaa ccc eee, 100],
      [eee fff ggg, 50],
     [
   ]
}
```

In search request set params:
`facet.phrases.q =  aaa AND aaa`

Then in results:
```
facets: {
   phrases: [
      [ aaa bbb ccc, 200],
      [aaa ccc eee, 100],
     [
   ]
}
```

Or:
`facet.years.filter =  $value > 2000 and $value < 2020`

Then in results:
```
facets: {
   years: [
      [ 2001, 200],
      [2019, 100],
     [
   ]
}
```

2. Facet sorting and navigation:

In search request set params:
`facet.phrases.sort =  value|count asc|desc`
`facet.phrases.limit =  10`
`facet.phrases.offset =  10`

Thanks a lot!

**Comment by b1tt0** [comment]
why

**Comment by DeltaNedas** [comment]
thats not a pull request bro
