### ISSUE TITLE
Naval builder unit 6.0 (T1)

### ISSUE THREAD

**Issue by Spacewars09** [Anuken/Mindustry-Suggestions#702]
**Name: proton
Weapons: 2 light single shot lasers on the sides
Health: 300
Speed: 2
Storage cap: 60
Command = no
Fly = yes
 Can mine: copper, lead, coal
Mining speed: fast
Build: medium**

**This will allow players to establish island and coastal bases more easily it will also allow players to setup defense against enemy naval forces.**

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SupremeTurtle** [comment]
Bold go brr

**Comment by DS-3K** [comment]
Remove noisey details please
You dont need to dictate every statistic,
Thats how good issues with good ideas sometimes fail, just cus the suggested side details arent gud
Why would it mine? 
Why wouldnt it command?
