### ISSUE TITLE
Plastanium Type Selection

### ISSUE THREAD

**Issue by JamesTheNerd** [Anuken/Mindustry-Suggestions#703]
**Describe what you would like changed, and why.**
Players should be able to change they type of a plastanium conveyor. Currently the loading(x), unloading(o), and transport(v) are set by default, and sometimes I want them to be something else.
Also, when unloading a plast conveyor into multiple things, it should be able to recognize when one of them is full and load into the other. Right now, it always unloads exactly evenly, even if that means waiting a long time for something to use an item.

**Describe the changes you want to propose. Include possible alternatives.**
Clicking on a plast conveyor should toggle its type between loading, unloading, and transport.
Or it could turn on something similar to the bridge conveyor UI, and then be changeable.

**Comment by potatoisagender** [comment]
This is just asking for griefing.

**Comment by JamesTheNerd** [comment]
No more than the little that already is possible with bridge conveyors.

**Comment by potatoisagender** [comment]
At least you can see bridge conveyors, esp. with the new qol thing. Plast belts won't tell you what they are like if items are on them. Additionally, you usually use plast conveyors a lot more than bridges.

**Comment by stuffyAI** [comment]
> Players should be able to change they type of a plastanium conveyor. Currently the loading(x), unloading(o), and transport(v) are set by default, and sometimes I want them to be something else.

There might be balancing thoughts behind this to limit their usability.

**Comment by itcannotbe** [comment]
But why.

**Comment by Quezler** [comment]
- being manually able to set the types would be a technical & usability nightmare

- it already unloads as much as it can per tick, one side already being full should not cause it to wait at all unless anuke has changed that in the past

**Comment by JamesTheNerd** [comment]
I think I was a bit too hasty in submitting an issue.
