### ISSUE TITLE
New Heal turret Idea. 

### ISSUE THREAD

**Issue by BigGoose69420** [Anuken/Mindustry-Suggestions#705]
** A vampiric turret that uses the stolen health to heal ally units. This would allow healing while still having a viable defense It would have heal rate based on how much health the enemy has, bigger enemies lose health slightly faster than smaller enemies. If an enemy gets fully drained by a turret the enemy will vanish with no death animations because the turret turned them into scrap parts for healing. 

** It could be a high tier heal turret that runs off of thorium and cryofluid like a built in thorium reactor just for itself but doesn’t make power to avoid the multipurpose buildings rule. This would make it harder to use properly but less spammable to prevent lag and make defenses more coordinated. The stealing and healing effect doesn’t work on buildings and can only target one enemy at a time. The turret could also have a slight tractor beam affect to pull enemies closer to the defense which makes them less spammable since players won’t want a reaper getting pulled past their defense and killing it from the inside 

1. - [ X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Thank you for using you time to read this message. I thank you for being open to new suggestions daily and making a game worth every cent on my platform. Good luck and thanks again 

                                              Sincerely,
                                               Big Goose

**Comment by itcannotbe** [comment]
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Now where did this go?

**Comment by stuffyAI** [comment]
> Now where did this go?

what is template i never seeeeen

**Comment by DS-3K** [comment]
So a unreliable source of heals that depends on your enemys?
I prefer the tier 2 repair point...

This is a good idea for a gun on a unit-
Oh wait, crawler tree :b

**Comment by unjown** [comment]
> I prefer the tier 2 repair point...

true
