### ISSUE TITLE
[Feature Request] Launchpad like block for research

### ISSUE THREAD

**Issue by ThaDaVos** [Anuken/Mindustry-Suggestions#708]
**Describe the content or mechanics you are proposing.**

I am proposing a block which functions like the launchpad and allows one to select a research in the research tree to send items to. This way the researches which require you to collect 300K+ materials, multiple times, should be easier to complete.

Because it may be out of scope I would also like to propose that only 1 research can be selected at the time, only 1 item type can be sent at the same time (so you can place multiple blocks down for copper but not one block for copper and one block for silicon).
And maybe make it a half the speed of a launch pad and double the energy to prevent people for running it AFK (or even make the launch manual, send like 1K at the time, but allow high amount of storage with cooldowns between launches)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will improve the research part of the game for the high item count researches (they take so long!)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
It was sort of suggested here https://github.com/Anuken/Mindustry-Suggestions/issues/597 but I suggest a more limited option,   for example only 1 itemtype at the time
2. - [ X ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Spfwniw** [comment]
Cores cost alot, others may be fine.

**Comment by bigbsonnier** [comment]
i could get behind this
