### ISSUE TITLE
Unit-Type based Command Center

### ISSUE THREAD

**Issue by Absolute359** [Anuken/Mindustry-Suggestions#709]
**Describe the content or mechanics you are proposing.**
Add 3 different Command Center for Ground, Air and Naval forces in the color based on their unit factory for example.
Naval Command Center only placeable on water maybe.
And maybe include Team-colors somehow like Type-color outside and Team-color in the middle.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Gameplay has a higher focus on Units and groups of units.
3 different Command Centers makes them easier to control and form groups of one Type of units.
For example, having Naval and Air Forces around one CC makes it hard to form groups with only one type.
Another example to form defensiv rally's at different locations to defend against enemies of the same type while other unit types couldn't reach there.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
For this to properly work, You need more than 3 because there are different kinds of units.

**Comment by unjown** [comment]
i want this too

**Comment by Absolute359** [comment]
maybe an additional shortcut like **strg + g** to command only units of the same type

**Comment by Cpppppppppplus** [comment]
This could also be used to control what ore mining units mine, and where building and healing units can go (since they often go to battle frontiers and destroy themselves).

**Comment by unjown** [comment]
> For this to properly work, You need more than 3 because there are different kinds of units.

this idea for me is the best
cuz 

> maybe an additional shortcut like **strg + g** to command only units of the same type

will be hard for mobile
