### ISSUE TITLE
Add if / else functions for logic processors

### ISSUE THREAD

**Issue by TheUzbek** [Anuken/Mindustry-Suggestions#710]
**Describe the content or mechanics you are proposing.** 
Add if/else functions. 
I know that there is already a jump function, which can be used as if/else statement, but it would be much more convinient to use if function instead. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will make programming in 6.0 a little bit easier, and would make it better to understand for newbies. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
no

**Comment by TheUzbek** [comment]
> no

why

**Comment by DeltaNedas** [comment]
because:
- if does absolutely nothing
- else would be annoying to place, would probably need to be serialized in `if`

**Comment by johann-lau** [comment]
I belive the jump functions are enough :D

**Comment by Kyllingene** [comment]
https://www.reddit.com/r/Mindustry/comments/m60qli/mindcode_a_higher_level_language_that_compiles/

**Comment by itcannotbe** [comment]
Let's hijack this thread by mentioning that 
"The problem with logic, as I see it, is that it is very low-level, closer to assembly than to a "real" programming language."

Don't burn me alive, I just pasted a qoute from the thread mentioned above.
