### ISSUE TITLE
Make building take exponentially longer the closer building is to enemy building.

### ISSUE THREAD

**Issue by Cpppppppppplus** [Anuken/Mindustry-Suggestions#711]
Updated Post: https://github.com/Anuken/Mindustry-Suggestions/issues/719

It is possible to cheat in a way by spamming several turrets right next to enemy buildings. This can often make it so that troops aren't even required to pass a level.

There's also a cheat in multiplayer that allows the side being attacked to spam conveyors at a very fast rate. Conveyors spammed like this can make it so that the defending team doesn't even need walls.

Making building take exponentially longer the closer the building is to certain enemy buildings will prevent the spamming. These "certain buildings" would need to be expensive enough so that players in multiplayer can't just spam them all over the place to make it impossible for the other team to build. There could also be a maximum number of these buildings per team, in order to prevent abuse.

**Comment by potatoisagender** [comment]
core no build radius?

**Comment by Cpppppppppplus** [comment]
@potatoisagender What I wrote above is intended for the regions where both sides can build and fight over.

**Comment by potatoisagender** [comment]
Isn't the whole idea of those areas... to build and fight and contest.......

**Comment by potatoisagender** [comment]
also f template

**Comment by itcannotbe** [comment]
> @potatoisagender What I wrote above is for the regions where both sides can build and fight over.

Basically every inch of the map?

**Comment by genNAowl** [comment]
You call it cheating but I think a more accurate term would be "cheesing" or playing a game/beating a level in a way that is not intended. 

Anyway, I support the idea of preventing BvB (building vs building) attacks, but this is not the way to go.

**Comment by MLGTASTICa** [comment]
Anti-build projector , takes a lot to build and covers like 50~ tiles around it , Prevents enemies from building until it is destroyed.

**Comment by itcannotbe** [comment]
There is an anti build area around the core already.

**Comment by zethnest** [comment]
@itcannotbe *If you're not replying to Author,*

Yes but outside the build zone is free real-estate. This makes it very easy for enemies spam turrets nearby core. In result this favors the enemy more than you and you cannot make an epic comeback once your enemies reaches your no build zone perimeter. 

Basically what this suggestion's problem meant.

**Comment by itcannotbe** [comment]
It kinda takes time for the enemy to actually make a stronghold outside your no build zone and the quicker way of elimination is actually killing the core directly with units. this kinda delays your imminent defeat. To prevent this the map should be made in a way to provide an additional way of weaking the enemy ie: Sabotaging the enemies supply lines.

**Comment by Cpppppppppplus** [comment]
@itcannotbe Making a stronghold outside the base is the best way to prevent the enemy from gaining resources. The building spam (especially conveyors and lancers) becomes often becomes an issue later in the game (two specters powered by cryofluid with a overdrive projector nearby can be stopped by a single person spamming conveyors). With regards to defending resource, I think that the only resource difficult to defend is titanium (and lead for ground units), since nothing shoots it.

**Comment by MEEPofFaith** [comment]
I'm not cheesing, I just know good strategies.

**Comment by bvcbvc** [comment]
conveyor

**Comment by SupremeTurtle** [comment]
How about when players PvP they just agree to not do BvB, it's as simple as that.

**Comment by DS-3K** [comment]
This would be a mess to code and feel like a patchworky solution to the problem, there surely are better options...

**Comment by XxsuperdeadlysniperxX** [comment]
You really want us to suffer?

**Comment by DS-3K** [comment]
This got a LOT of attention lmao xD

**Comment by zethnest** [comment]
> This would be a mess to code and feel like a patchworky

Not really. I think it's fairly easy. You just set another radius bigger than the no_build zone. If enemy build in the said radius, the closer it is to core, the higher build speed penalty.

The idea of this suggestion however, I don't think it's that good tbh.
