### ISSUE TITLE
Phase turret

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#712]
**Describe the content or mechanics you are proposing.**

A turret that uses phase as ammo and requires collant

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Cuz theres a turret that uses surge so why not phase

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [/ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [/ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [/ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
> Before making this issue, replace the spaces in the following boxes with an X to confirm that you have acknowledged them.

Reading Comprehension skills: Failed

**Comment by itcannotbe** [comment]
While at it why not make

A tUrReT tHaT sHoOtS sAnD.

Cause every item needs to be fired from a turret and ReQuIrEs "collant"

**Comment by sample-text-here** [comment]
at this point why not make mass drivers turrets that can shoot anything
wait that's not an awful idea

**Comment by unjown** [comment]
> > Before making this issue, replace the spaces in the following boxes with an X to confirm that you have acknowledged them.
> 
> Reading Comprehension skills: Failed

my eng is not very good

**Comment by Colonizor48** [comment]
I have an actually good idea for a turret that uses phase and spores.

**Comment by unjown** [comment]
> I have an actually good idea for a turret that uses phase and spores.

what? 
btw what u discord @Colonizor48
