### ISSUE TITLE
Put slag in turrents

### ISSUE THREAD

**Issue by oran-dycheh** [Anuken/Mindustry-Suggestions#713]
It would fill the liquid of course and it wouldn't give a speed boost ,but it would make all ammo incendiary.

**Comment by oran-dycheh** [comment]
And it would make all liquids go into turrents

**Comment by itcannotbe** [comment]
@oran-dycheh You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by BlueWolf3682** [comment]
...why? who even uses incendiary ammo on a regular enough basis to make this request?

**Comment by Colonizor48** [comment]
Meme idea. Make it so u can use slag as a coolant but it just makes the turret overheat and explode. Just for the memes.

**Comment by MEEPofFaith** [comment]
Fire does very little anyways.

**Comment by bvcbvc** [comment]
this but its slows the turrets rather then suddenly fire

**Comment by DS-3K** [comment]
It sounds really fun to mess around with weak big turrets in sandbox c:

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
Slag is like anticoolant, so if you stick it in a turret it would probably shoot slower. Also it would constantly take damage because you're basically dumping lava on a piece of metal.
