### ISSUE TITLE
New Function for Processors

### ISSUE THREAD

**Issue by Surviavlist** [Anuken/Mindustry-Suggestions#714]
**Add "Wait function for processors:
__Seconds__ __ms/sec/min__**

**This will very help to work with processors**

1. - [ X] Sorry I backspaced this but X
2. - [ X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

> This will very help to work with processors

How exactly? I can't even think of a use case.

**Comment by rmperkow** [comment]
Sometimes I need a program to wait for some time.

`wait "milliseconds"`

**Comment by itcannotbe** [comment]
Well you can't. As processors does not even run at 1000hz

**Comment by Vortetty** [comment]
> How exactly? I can't even think of a use case.
countless times i have needed to do delays, so example scheduling something to happen in an animation, or delayed execution to make processors cooperate with each other, etc

**Comment by Colonizor48** [comment]
You can kinda do this with jump statements But this would be useful nonetheless as a function
