### ISSUE TITLE
Missile turret suggestion

### ISSUE THREAD

**Issue by MLGTASTICa** [Anuken/Mindustry-Suggestions#715]
**Describe the content or mechanics you are proposing.**
Missile launcher turret, a 5 x 5 turret that takes graphite , blast compound or surge alloy .It has extremly long range and fires homing missiles at air units.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
There's plenty of maps that for example have a lot of mountains. ON these maps air defense becomes a major issue, especially when the air units keep flanking all the time. This turret would fill the niche of long-range air defense meant for small amounts of units that make it past the main defense (such as T1 ,T2 and T3 air units)

1. - [X]  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Ah yes. Extremely long range.....



Nope.

**Comment by MLGTASTICa** [comment]
> Ah yes. Extremely long range.....
> 
> Nope.

Why not ? just argument your point a little.

**Comment by itcannotbe** [comment]
Your use case doesn't even consider using the turret outside your inteded use case. Which is a matter of fact create an overpowered turret.

**Comment by MLGTASTICa** [comment]
> Your use case doesn't even consider using the turret outside your inteded use case. Which is a matter of fact create an overpowered turret.

its a 5 x 5 that fires long range homing missiles. It could be made even bigger but it ideally wouldn't have enough DPS to be considered that good of a defense. Idealy a spectre would be more than 200 times better than this.
If people decide to spam it and waste space that's life. Ideally the turret should take a lot of time to build and take a lot of round-start resources.
Another way to remedy the issue would be by making it lose effectiveness with range , meaning the more the bullet goes the less damage it will deal

**Comment by unjown** [comment]
Anuke said that he won’t add turrets so basically Anuke will reject this (99%)

**Comment by potatoisagender** [comment]
swarmer?
And @itcannotbe is getting at the fact that one can use it to outrange ripples.....

**Comment by MLGTASTICa** [comment]
> swarmer?
> And @itcannotbe is getting at the fact that one can use it to outrange ripples.....

its only supposed to aim at air. Not at any ground unit or structures.

**Comment by potatoisagender** [comment]
okay. Still applies with swarmer.

**Comment by MLGTASTICa** [comment]
> okay. Still applies with swarmer.
I wouldn't call it a swarmer , since it shouldn't have a high rate of fire. But  its preety  much a swarmer that is specialized for units that flank.

**Comment by MEEPofFaith** [comment]
Manually controlling a Spectre or Foreshadow to shoot something out of range is already really powerful, we don't need something like that that can _**e x p l o d e**_.
Also, aren't Cyclones strong enough to deal with those T1-3 air units already? And if they're too fast just add Parallaxes.

**Comment by MLGTASTICa** [comment]
> Manually controlling a Spectre or Foreshadow to shoot something out of range is already really powerful, we don't need something like that that can _**e x p l o d e**_ while having even longer range.
> Also, aren't Cyclones strong enough to deal with those T1-3 air units already? And if they're too fast just add Parallaxes.
It would only detonate if it has blast compound , and im preey sure that swarmer missile explosions don't deal damage to structures.

**Comment by MLGTASTICa** [comment]
> > Manually controlling a Spectre or Foreshadow to shoot something out of range is already really powerful, we don't need something like that that can _**e x p l o d e**_ while having even longer range.
> > Also, aren't Cyclones strong enough to deal with those T1-3 air units already? And if they're too fast just add Parallaxes.
 It would only detonate if it has blast compound , and im preey sure that swarmer missile explosions don't deal damage to structures.

**Comment by unjown** [comment]
basically t2 swarmer? (pls answer yes or no only) @MLGTASTICa

**Comment by MEEPofFaith** [comment]
But swarmer does damage buildings...

**Comment by MLGTASTICa** [comment]
No to T2 Swarmer , and it won't target buildings by default.

**Comment by unjown** [comment]
so basically [this](https://github.com/Anuken/Mindustry-Suggestions/issues/672l)

**Comment by unjown** [comment]
Only targets air , long ranged

**Comment by MLGTASTICa** [comment]
that doesn't link to anything

**Comment by unjown** [comment]
> that doesn't link to anything

?? u said long ranged AA

**Comment by MLGTASTICa** [comment]
im talking about your hyperlink, tag in the issue ID directly instead of trying to hyper it

**Comment by unjown** [comment]
> No to T2 Swarmer , and it won't target buildings by default.

yup only air ik sort of V1.5 swarmer only targets air

**Comment by unjown** [comment]
just search AA ripple it will come out

**Comment by MLGTASTICa** [comment]
> just search AA ripple it will come out

That idea won't work since it would require anti-air projectiles to have crazy speed , which anuke will probabl wouldn't want.

**Comment by unjown** [comment]
> > just search AA ripple it will come out
> 
> That idea won't work since it would require anti-air projectiles to have crazy speed , which anuke probably wouldn't want.

 Oh. Mine is not very fast.
