### ISSUE TITLE
Logic function

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#716]
A function editor where you can make functions and call them in code.
Each processor has a different amount of maximum functions.
Microprocessor: 3 functions max
Logic processor: 5 functions max
Hyperprocessor: 10 functions max

Useful for parts of processing that you need to repeat without copying the code.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Jumps exist.

**Comment by rmperkow** [comment]
You could call a function anywhere and it would return to the next block after the function finishes.

**Comment by Cpppppppppplus** [comment]
@rmperkow Functions are implemented as jumps in real computers (unless there is some sort of CALL instruction, like x86, which is really just a jump that stores the return address anyways).

**Comment by rmperkow** [comment]
Useless.
