### ISSUE TITLE
plated conduit cap makeover

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#717]
**Describe what you would like changed, and why.**

the plated conduit has a cap sprite that gets drawn when there isn't anything in front to justify it leaking less than normal, but the sprite completely closes it off, so the leak comes from seemingly nowhere:

![cap](https://raw.githubusercontent.com/Anuken/Mindustry/master/core/assets-raw/sprites/blocks/liquid/plated-conduit-cap.png)

![Screen Shot 2020-10-08 at 15 38 57](https://user-images.githubusercontent.com/3179271/95466403-98dac180-097c-11eb-858e-d71304e73e7f.png)

**Describe the changes you want to propose. Include possible alternatives.**

the original cap was a little harder to see, but it had room on either side where some liquid could leak through:

![og](https://raw.githubusercontent.com/Quezler/Mindustry/74212771dcde4caac3ddb2897d8156e9a86c59de/core/assets-raw/sprites/blocks/liquid/plated-conduit-cap.png)

![original](https://user-images.githubusercontent.com/3179271/68214049-02b85180-ffdd-11e9-84f9-6636a78ac46a.png)

this one was to subtle [according to anuke](https://github.com/Anuken/Mindustry/pull/999#discussion_r344454840), but it always felt like the new texture made no sense since it completely closes it off instead of leaving a gap 💧 

anyways, here are 2 solutions i'm proposing:

- keep the current sprite and remove leaking from the plated conduit entirely (great when laying new pipes without loss!)
or
- change the sprite to contain a gap at either the edges or the center where it can actually leak through

(react with 🚀 to vote for the leakless solution, and 🎉 for a visible spillway)

**Comment by DS-3K** [comment]
Mission success!

**Comment by DS-3K** [comment]
The dude killed half the template and still got accepted, respect!

**Comment by genNAowl** [comment]
Well he's Quezler

**Comment by itcannotbe** [comment]
Actually the template is complete, since it's balancing/feedback. Duh.
