### ISSUE TITLE
`yes` command for server CLI

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry-Suggestions#718]
**Describe the content or mechanics you are proposing.**
A command with the same intent as [nvbn/thefuck](https://github.com/nvbn/thefuck), used to reply to `Command not found. Did you mean 'commandname'?` messages; correcting the misspelling of a command and executing it. If `commandname` is null (e.g. a command successfully executed), show a message describing the `yes` command (?).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Quality of life feature, less keystrokes if you misspell a command.

> (...) how it may add more gameplay options/fill a new niche

N/A

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
close.exe
