### ISSUE TITLE
Launch Pad Logic Control

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#720]
**Describe the content or mechanics you are proposing.**

Have a logic command to set the destination of launch pads, as well as one to read the destination.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will help to make launch pads better and more practical to use.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by HoldOffHunger** [comment]
I like this suggestion -- to be clear, my problem is this:

1) Start a new map,
2) To get all launchers to point to new map, I must go to every single map I have previously gone to before (where I have placed launchers).
3) That can mean going to 20, 30, 40 maps, as soon as I start a brand new map?  This is a massive chore and doesn't contribute to gameplay value.

**Comment by Ae-Mc** [comment]
It shouldn't be closed
