### ISSUE TITLE
New turret. The radiator

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#721]
**Describe the content or mechanics you are proposing.**
A new very large turret that takes phase fabric as ammo in addition to requiring coolant and power to operate. The radiator would emit shockwaves around it that deal moderate damage. But also have a chance to give enemies the new irradiated status effect. The effect would cause enemy ai to go beserk doing things like blocking other units or friendly firing and sometimes just strieght up exploding dealing damage to the enemy and you alike. And sometimes causing the enemy unit to completly turn and start attacking the team that origionaly made it for a bit before exploding(you wouldnt be able to control the unit doing this)In addition to dealing a poison like effect to the enemy.(some of this might need tweaks.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be meant to be an AOE type turret that would deal poision damage. This would also add a new elemet to pvp because a team would have to decide do they want to send a large attack and risk it being turned against them by the radiator. OR do they want to launch a smaller attack and be more safe?

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by unjown** [comment]
Noice
similar to my phase turret 
mine is a spectre that shoots faster
but goood idea

**Comment by unjown** [comment]
![Uploading Radiator.png…]()

**Comment by NexusDarkshade** [comment]
There is no image

**Comment by unjown** [comment]
> There is no image

its uploading lol wifi is slow
![Uploading Radiator.png…]()

**Comment by unjown** [comment]
![Radiator2](https://user-images.githubusercontent.com/71381907/95540517-8cf60a80-0a23-11eb-9c0a-3a2c0e6886d8.jpg)

**Comment by unjown** [comment]
u can make it better 
my idea is not a turret btw

**Comment by unjown** [comment]
the middle will glow when activated 
another suggestion input 
phase and thor and coolant so it will be harder to run

**Comment by Colonizor48** [comment]
that would be too much. But it would take phase and collant in edition to lots of power.

**Comment by Colonizor48** [comment]
Why wouldnt it be a turret though?

**Comment by unjown** [comment]
Cuz it doesnt technically shoot it releases waves (shockwaves) so it doesnt seem like a turret to me

**Comment by SupremeTurtle** [comment]
Fun Fact: Anuke will not accept new turrets ideas or PRs.

**Comment by Colonizor48** [comment]
> 
> 
> Fun Fact: Anuke will not accept new turrets ideas or PRs.

M8 that's cool and all but i'm looking around trying to find who da frick asked.

**Comment by Colonizor48** [comment]
also thats only for v6. Im hopping this gets added after v6

**Comment by unjown** [comment]
> Fun Fact: Anuke will not accept new turrets ideas or PRs.

Not really if he likes it he add it.
He added 2 turrets in v6

**Comment by stuffyAI** [comment]
> Not really if he likes it he add it.
> He added 2 turrets in v6

yeah those were good suggestions with functioning PRs tough
