### ISSUE TITLE
Button for Respawn on Mobile

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#722]
A button that appears in mobile. When pressed, you will respawn at the core.

This will make respawning faster since for huge maps you have to swipe to core and it can be very far, which is a problem. Also, sometimes there may be too many blocks that you may not even be able to see the core. And the last thing, while swiping to the core, your unit will follow you to the core until you respawn which is another big problem because when you want to leave a unit at some place and respawn that is only possible with command center or by taking control of a turret. PC players don't need these while we do, so please, a button is required.

Don't say you can pause to go to core and respawn becuse that won't work on multiplayer and this issue happens most on multiplayer.

I think that you think mobile controls are pretty much finished but there are things to do, also you can't manually shoot and move at the same time.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
sadly, anuke already said he doesnt plan to add more unit control related buttons to mobile. maybe he has changed his mind, but i think its safe to assume we are stuck with multipurpose controls :/

**Comment by SupremeTurtle** [comment]
RIP mobile players

**Comment by DemoneX1704** [comment]
Why Anuke doesn't plan add more botton controls to mobile?

**Comment by unjown** [comment]
> Why Anuke doesn't plan add more botton controls to mobile?

he doent really like adding more buttons bec of screen size

**Comment by itcannotbe** [comment]
> Why Anuke doesn't plan add more botton controls to mobile?

Because it's too damn crowded already!
![Screenshot_20201015_094734_io anuke mindustry be](https://user-images.githubusercontent.com/45280919/96067121-98d24880-0ecb-11eb-95b8-b0b4c383299f.jpg)
