### ISSUE TITLE
Placing Walls on Walls

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry-Suggestions#723]
Placing a same type of wall on a wall should make it so that its repaired to full HP.

For when menders take long time to repair (or there isnt menders at all), we should be able to repair walls by ourselves. This will make it so that you don't need to delete a wall to place a full HP one. This can take less time than the time you spend building a wall since you are repairing instead of constructing, but it also can take more time since it takes time for deleting walls and constructing, but I prefer the less time since it makes more sense. If you can't make mechanics like that then it should either be instant or it should take as much time you spend building a wall.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
I don't think the code would like this
