### ISSUE TITLE
Infiltration raids (Coreless missions)

### ISSUE THREAD

**Issue by AlbatrozFeroz** [Anuken/Mindustry-Suggestions#725]
The idea is to have a little fun gamemode that mimics a top down shooter, where you start controlling a certain unit, and you have to go around the map fighting other robots and completing objectives.
You get defeated once all of your units gets destroyed, certain areas of the map may give you more units.

Is a shorter gamemode, very different than the normal sector work, it maybe could have a appearance in the planed daily missions

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
Cant you make maps that kinda work like that or do you need mods for something like this?

**Comment by ThatOneBepis** [comment]
> Cant you make maps that kinda work like that or do you need mods for something like this?

No, you require a core if you are to play a map

Perhaps feature mobile cores instead? "certain areas of the map may give you more units" May refer to areas that allow you to build a limited amount of units, both for technical and logistical reasons. Mobile cores also may give you an initiative to lay your forces more strategically and it in-game feels more realistic to severe the connection to the area if it is destroyed.
**Note that mobile core is a unit, rather than, well, a mobile block.**

**Comment by DS-3K** [comment]
> > Cant you make maps that kinda work like that or do you need mods for something like this?
> 
> No, you require a core if you are to play a map
> 
> Perhaps feature mobile cores instead? "certain areas of the map may give you more units" May refer to areas that allow you to build a limited amount of units, both for technical and logistical reasons. Mobile cores also may give you an initiative to lay your forces more strategically and it in-game feels more realistic to severe the connection to the area if it is destroyed.
> **Note that mobile core is a unit, rather than, well, a mobile block.**
> 
> Needless to say, it would be a nice mini-game of sorts.

**_may make a map of this concept out of spite_**
(v5 steam)
