### ISSUE TITLE
Mute Player Chat

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry-Suggestions#727]
**Describe the content or mechanics you are proposing.**
Please add a feature to mute specific player chat.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes there are some players who like to send spam or trash talk or trolling, it would be nice if we can mute them.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by summetdev** [comment]
Cool idea, I'll try to implement it.

**Comment by DS-3K** [comment]
Wait, there are multiple devs?

**Comment by RogueRedHawk** [comment]
@DS-3K The game is open source. Anuke is the developer, but anyone can add to the code. You call these people contributers, not devs.

**Comment by DS-3K** [comment]
> @DS-3K The game is open source. Anuke is the developer, but anyone can add to the code. You call these people contributers, not devs.

**Its communist code? :pppppp**
