### ISSUE TITLE
Make shield projectors block crashing airplanes

### ISSUE THREAD

**Issue by MLGTASTICa** [Anuken/Mindustry-Suggestions#729]
Describe the content or mechanics you are proposing.
Make shields capable of bouncing / blocking crashing airplanes

Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
Air units crash and deal damage.  Inevitably this will go past any defense as they will instantly take out conveyors since they low health or power nodes
Before making this issue, replace the spaces in the following boxes with an X to confirm that you have acknowledged them. Failure to do so may result in your request being closed automatically.

[x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
[x]I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
[x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by JamesTheNerd** [comment]
Yes please. Crashing air units is extremely annoying. Also, force projector is underpowered and this is a good way to give it a use case.

**Comment by DS-3K** [comment]
Air units crash and do damage?? This was from a old Suggestion its so cool it was added xD
