### ISSUE TITLE
Auto mod updater

### ISSUE THREAD

**Issue by jojoblackFr** [Anuken/Mindustry-Suggestions#73]
**Describe the content or mechanics you are proposing.**
When you download a mod with github path(like:username/mod), the game save the path and auto download update the mod if an update is available

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
That addons can be good for mod player because is very long to search all update and all bug in mod can be fixed with an auto updater

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
`git pull`

**Comment by ILiekMelons** [comment]
so..

**Comment by Anuken** [comment]
Use the workshop for *automatic* mod updating.
