### ISSUE TITLE
A New Unit: Glory

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#730]
**Describe the content or mechanics you are proposing.**
Glory, a new unit that the player could perhaps not make. This unit would be alot like the titan, it would have 1000 health points. This unit would be a medium-close ranged ground unit manning 2 Fully Automatic Shotguns. These shotguns would be like the fuse but alot more nerfed, there would be 12 pellets, each dealing about 10 damage, at closest ranges, the unit would deal 480 damage per second, this would be hard to accomplish as the spread is about 54°. The firerate would be 120rpm (240 for both guns).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would be the first shotgun unit in the game and would be a unit that possibly cant be made. This unit would also be cool in the way that its damage depends on range, like the fuse but more severe.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
I would suggest that YouTube begin with the request for a unit of wich damage depents on range, instead of going unto your obtimal example, that is the glory.
From a game maker perspective, you need first to be convinced the concept will improve your game, instead of reading through all the noisey details before getting to the point
Let anuken do the fine tuning and game designing, just try to lead him into ideas you Like

I myself like your idea, really do. But you have so many unnecesary details like having it be only in waves and stuff


Sorry for bad grammer, im on my phone with german autocorrect and Im tired
Tis a nice issua, hava gud day <3

**Comment by DS-3K** [comment]
YouTube= you* oof

**Comment by jaygamer81** [comment]
> I would suggest that YouTube begin with the request for a unit of wich damage depents on range, instead of going unto your obtimal example, that is the glory.
> From a game maker perspective, you need first to be convinced the concept will improve your game, instead of reading through all the noisey details before getting to the point
> Let anuken do the fine tuning and game designing, just try to lead him into ideas you Like
> 
> I myself like your idea, really do. But you have so many unnecesary details like having it be only in waves and stuff
> 
> Sorry for bad grammer, im on my phone with german autocorrect and Im tired
> Tis a nice issua, hava gud day <3

True. I just think a unit that someone cant make would be unique. I think it would improve the game as more units is just fun. I have an idea, perhaps the unit can rush the walls or maybe it can armor itself up like the Omega from V5 when it is in closer ranges.

**Comment by DS-3K** [comment]
> > I would suggest that YouTube begin with the request for a unit of wich damage depents on range, instead of going unto your obtimal example, that is the glory.
> > From a game maker perspective, you need first to be convinced the concept will improve your game, instead of reading through all the noisey details before getting to the point
> > Let anuken do the fine tuning and game designing, just try to lead him into ideas you Like
> > I myself like your idea, really do. But you have so many unnecesary details like having it be only in waves and stuff
> > Sorry for bad grammer, im on my phone with german autocorrect and Im tired
> > Tis a nice issua, hava gud day <3
> 
> True. I just think a unit that someone cant make would be unique. I think it would improve the game as more units is just fun. I have an idea, perhaps the unit can rush the walls or maybe it can armor itself up like the Omega from V5 when it is in closer ranges.

What if the armor is active when it **isn't** firing?
It would make more sense for a short range unit c: closing dat distance :D

**Comment by ThatOneBepis** [comment]
Im more for making Glory a pull request rather than a plain suggestion. Im saying this as it not only for the sake of balancing, but also _how are we even going to code this thing._
