### ISSUE TITLE
Space Units and space battles between planets (if more are added after v6.0)

### ISSUE THREAD

**Issue by Cmonster820** [Anuken/Mindustry-Suggestions#731]
**Describe the content or mechanics you are proposing.**

Space Units - units constructed on [PLANET NAME HERE] or in orbit that can attack with planetary bombardment or attack other space units
Space battles- battle other space units, space bases, or massive spacecraft you can land a special core on and then blow up a massive reactor to kill
Previously mentioned massive spacecraft- multiple “sub sectors”(sectors off planet and on the ship) with incredibly hard enemies
The space bases I mentioned would basically just be the spacecraft I talked about but with a different design
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More gameplay of just, space, also, more modding opportunities being better units and harder spaceship and space bases areas

These would work alongside the satellites on the trellis list
(If they are added)￼

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Cmonster820** [comment]
Trello*

**Comment by unjown** [comment]
nice idea

**Comment by Cmonster820** [comment]
> nice idea

Thanks

**Comment by Cmonster820** [comment]
Also, a side note is that, to invade the ship, then, you would break through the vacuum-proof glass
