### ISSUE TITLE
Give Spectre a bit of pierce

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#732]
**Describe what you would like changed, and why.**

Here's a Meltdown VS 100 crawlers:
![meltdown](https://user-images.githubusercontent.com/68400583/95642838-ff84db80-0a5f-11eb-9387-76b348900067.gif)

Here's a Spectre VS 100 crawlers:
![spectre](https://user-images.githubusercontent.com/68400583/95642843-0ca1ca80-0a60-11eb-8ca5-06ebc4fc7e92.gif)

Yikes. It does way worse. Although I know the Spectre was already buffed in V6.0, It still seems really weak against grouped enemies. 

**Describe the changes you want to propose. Include possible alternatives.**

I think the Spectre should be an well-rounded turret. Giving it infinite pierce would make it too strong. Giving it splash damage wouldn't make too much sense. I feel like a nice solution would be to give it a bit of pierce with the pierceCap variable? 

I tried it out, here's what a Spectre with 3 pierce looks like (3 is a bit strong, maybe 2 would work?): 
![buffed-spectre](https://user-images.githubusercontent.com/68400583/95642911-92257a80-0a60-11eb-8657-7f78a0643fde.gif)

**Comment by itcannotbe** [comment]
Spectres are meant to quickly shoot down high HP enemies, not a horde of low HP ones.

**Comment by genNAowl** [comment]
> Spectres are meant to quickly shoot down high HP enemies, not a horde of low HP ones.

Fair enough, but now we have takedowns to do that; I think Spectres should be more of a well rounded turret, with the ability to take out bunches of enemies if it needs to. Idk, might ask the community what they think about it.

**Comment by SupremeTurtle** [comment]
(imo) It's big boi bullet and it's fast, so having just tiny pierce would make sense.

**Comment by genNAowl** [comment]
Looks like spectre thorium and pyratite bullets have 2 pierce now.

**Comment by DS-3K** [comment]
Something like a 4x4 turret should NOT be countered by the lowest level unit: crawler
Having a Pierce of 2 is completely appropriate

**Comment by 50275** [comment]
Anuke nerfed crawlers a lot. Those 100 crawlers would cost 2000 silicon and 1000 coal and would easily be destroyed with a handful of conveyors.

**Comment by genNAowl** [comment]
> nerfed crawlers a lot

Not that I know of. 

> would cost

Does it matter? This is about the unit, not how much it takes to make it. 

> easily be destroyed with a handful of conveyors.
![get your facts right](https://user-images.githubusercontent.com/68400583/96939068-d7927080-1480-11eb-9389-c9eb9227f771.gif)

Dude before you comment this stuff get your facts right.

**Comment by 50275** [comment]
> Note that 6.0 crawlers do more than 2x the damage of 5.0 crawlers.
Just because they do 80 damage doesn't mean that 80 damage will be useful. You can just... spam junctions. It works perfectly, I've just tested it. You see, you're going to need to use 5x the coal to make the unit EXCLUDING sand cost. 
I don't understand how you can call this balance change a *buff* to the crawler.

With that same amount of silicon you could make a few dozen lancers and tear those crawlers apart.

This isn't a fair comparison. Any reasonable situation with a decent map would have both of those turrets destroyed by 100 of a different unit, presumably one that isn't a waste of resources.

**Comment by genNAowl** [comment]
All your points just boil down to one: Crawlers are too expensive. While this is a fine example of a nerf, you forgot to consider that creating Units is only a part of gameplay, and the main part, survival, is about defending from them. The build cost of a crawler does not matter to the spawn point in a sector. Meanwhile, the AI and damage/AOE of crawlers have been buffed, something applicable in all parts of the game. 

Anyways the current problem is that you say things without checking if they are true or not, and although crawlers have been nerfed, you forgot to mention their buffs, and even stated "[they] would easily be destroyed with a handful of conveyors.", which is definently not true.
