### ISSUE TITLE
Add pierce to specific bullet types

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#733]
**This suggestion does not fit well into template, as it is literally a list, please do not bug me about it**
Basically, due to the new pierce cap, I think a few specific things should have pierce added to them, and also have pierce cap added.
Railgun shots - Railgun shots should keep the infinite pierce, as it works out well for it.
Reign - Reign's "purpose" is to be a defensive unit, and it's pierce kind of keeps it good for that, it should have a very high pierce limit like 20 or 30.
Spectre - Spectre should add pierce cap, and have different caps for each bullet type: Graphite - Cap of 3, Pyratite - Cap of 2, Thorium - Cap of 4. (Maybe this should be a bit lower though)
Salvo - Salvo should also have pierce added to it's shots, kind of like spectre, but only for specific bullet types: Graphite - Cap of 1, Thorium - Cap of 2
Duo - Duo shares the graphite bullet type with Salvo, so it will end up having a graphite pierce cap of 1.

Tell me if there is anything I missed or anything that is too unbalanced

**Comment by itcannotbe** [comment]
Defensive units can also be used offensively. So reign with a high pierce cap value is extremely op.

**Comment by itcannotbe** [comment]
Also not that high damage values together with high pierce cal values tend to be on the op side of things.

**Comment by genNAowl** [comment]
Dude the pierce caps you are setting are all pretty high...

Here's what a Spectre with 3 pierce looks like, and it's already really op. 
![](https://user-images.githubusercontent.com/68400583/95642911-92257a80-0a60-11eb-8657-7f78a0643fde.gif)

**Comment by Syncinus** [comment]
That's against crawlers... Use it on fortresses or something else, then try to use Reign on the same thing, I owuld say it would be okay to reduce the spectre pierce cap I proposed a bit, but for crawlers specifically, Spectre is a high tier turret and should be able to annihilate them. I did reduce the caps on the original suggestion though.

**Comment by Syncinus** [comment]
And itcannotbe, reign doesn't even have a pierce cap right now, I think it will be okay if it gets a very high one though, as that's the thing that makes it better then Toxopid in some situations.
