### ISSUE TITLE
Add the Ability to Store Liquids in the Core

### ISSUE THREAD

**Issue by Crowned2** [Anuken/Mindustry-Suggestions#734]
Add the ability to store liquids in the core, or maybe a higher tier of core, to allow for transportation of liquids to areas where they are scarce, or to store excess hard to obtain liquids, for ease. You can carry all sorts of items in the core, why not liquids?

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Because liquid scarce location doesn't deserved to be liquid scarce. Right (Sarcasm: 100)

**Comment by itcannotbe** [comment]
So basically......

> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Why not?

**Comment by bsjohnson20** [comment]
Me wondering why you need it for scarce locations when it's infinitely extractable, maybe an area to where there is no liquid of that type but I still don't see the point
