### ISSUE TITLE
a way to collect the enemy drops

### ISSUE THREAD

**Issue by USMP-lancer** [Anuken/Mindustry-Suggestions#735]
**a way to collect the enemy drops**
**a new block that collects the enemy drops and send them to a core, would be like a core extention you can't use unloaders on maybe**

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Isn't that just,,, Enemies drop resources in settings???
