### ISSUE TITLE
Add a New Block for Deploying/Retrieving Naval Units from Payload Conveyors

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#737]
**Describe the content or mechanics you are proposing.**
While payload conveyors can logically transport naval units across land, having the conveyor simply stop and the boat appear in the water does not make much sense for a block which never appears submerged. A new block should be added that fills the purpose of a slipway or boat launch, which bridges the gap between land-based transport and deployment to the sea. Naval Factories and reconstructors would still be able to output directly to water, but conveyors transporting boats would need an intermediate ramp from which to launch. Optionally, boat ramps could also be used as a method of loading boats back onto payload conveyors, without the need for significant air support.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Adding a slipway block would add diversity to unit transport, and augment the uniqueness of the naval class. Requiring a ramp for boats further reinforces that shallow water *is* still water, and not just "wet" land. Allowing boats to load back onto payload conveyors unassisted would also provide some independence to a class that, while powerful, is highly dependent upon other units for support. 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
I mean, reloading boats is nice I guess...

But this seems like unnecessary work for a block that is basically an aesthetic...

**Comment by motaywo** [comment]
Perhaps, but my reasoning that using just plain payload conveyors would make it too easy to mobilize boats, considering their firepower

**Comment by potatoisagender** [comment]
They can't fire on conveyors, can they?

**Comment by motaywo** [comment]
no, no - they're inert, just like normal. But letting boats reboard is something that's only currently possible using megas or higher (depending on boat size), and simplifying that down to just needing a lil' copper and graphite seemed a bit too extreme
