### ISSUE TITLE
Rename Plastanium Conveyors

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry-Suggestions#738]
**Describe what you would like changed, and why.**
Plastanium Conveyors should be renamed to highlight the differences between them and regular conveyors. Presently, plast conveyors operate in an entirely different manner, and renaming them would help eliminate confusion and frustration among players unfamiliar with them. Plast "conveyors" can't interface regularly with normal conveyors and handle items in an entirely unique matter. Indeed, the plast conveyors do not even have a moving "belt" instead having packets or carts of items moving under their own power.

**Describe the changes you want to propose. Include possible alternatives.**
Plastanium Conveyors should be renamed to Plastanium Rails, or a similar name indicating that they operate differently than a conveyor belt. I personally feel 'rail' is a good choice, considering how they appear to guide items rather than actually move them directly. Other alternatives could possibly be plastanium chutes, or viaducts, but anything signaling the uniqueness of plastanium item transport would be beneficial.

**Comment by Quezler** [comment]
> Trains, or any transportation system that uses something analogous to rails

**Comment by DS-3K** [comment]
Wait, did Anuken accidentaly make trains? Lmao
Plastanium conveyors = forbidden train confirmed

**Comment by Quezler** [comment]
@motaywo while i agree with your reasoning, there simply isn't really a better name for them that's self explanatory enough 🤔

**Comment by Quezler** [comment]
"plastanium track" is probably the only thing that gets close, but overall its nearly identical to conveyors, so the name is justified 😗

**Comment by motaywo** [comment]
I suppose, but then perhaps change the sprite animation so the conveyor belt actually moves?

**Comment by XEN0PHIL** [comment]
I **o***b*E***y***

**Comment by Quezler** [comment]
> I suppose, but then perhaps change the sprite animation so the conveyor belt actually moves?

it would not make sense since the roombas are clearly hauling the items around with turning and everything

**Comment by motaywo** [comment]
~~Plastanium Roomba Ride~~

All in favour?

**Comment by motaywo** [comment]
In all seriousness tho, why not just invent a new word? This is a video game after all.

I personally like Plastanium Directrix? Advector? Impellor? The Latin derivatives alone give us hundreds.
