### ISSUE TITLE
Damage Falloff

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#739]
**Describe the content or mechanics you are proposing.**
I suggest a new value for projectiles: damage falloff. This value will decrease damage(maybe speed too) of projectiles,
depending on their age and type. (differant value for each bullet)
For beams I suppose they could do decreased damage on distance and they should visibaly thin out at the
tip to indicate them getting weaker.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A fun way to play units in Mindustry is to get close to your oponents defenses, and AI do the same. 
Now, the most effective way to deal damage is to hog at your maximum range to get less attention from enemy guns
the problem is, mindustry **doesn´t reward the most fun** playstyle for offensives nor does the ai make use of the current
system of staying at maximum range as they walk up to everything.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

Mindustry if a wonderfull game, and you are designing it well. Even if you don´t want to add damage falloff
I hope I inspired you with a idea you might one day see use in :3 

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Quezler** [comment]
_random crits are fair and balanced_

**Comment by genNAowl** [comment]
the drag variable already decreases speed
