### ISSUE TITLE
TRUE router block with priority setting

### ISSUE THREAD

**Issue by Remint32** [Anuken/Mindustry-Suggestions#74]
**Describe the content or mechanics you are proposing.**
==

This block is a combination of a **Router**, **Overflow gate**, and **Underflow gate**, and introduces some **new necessary functionality**.

_The idea for this block came to me while thinking about the idea of setting priority for the flow of items during routing, which was submitted to me by one of the players._

By _clicking_ on the block, you can open the menu shown in the image:

![image](https://user-images.githubusercontent.com/13190430/77849400-faeb8a80-71d3-11ea-8768-a7ca313f0971.png)

On the _sides_ of the block, you can choose the **direction** of _input / output_ of the flow of items or **prohibit** it (for example, if there is a _production block_ close by and you do **not want** to interact with it).
At the _corners_, you can choose the **priority** of the item flow for input or output (depending on which mode is selected for the related side)

The priority value can mean both the number of items per game tick, and the relation to the other priorities of the other sides of the block. Depending on how the game mechanics are arranged and which option is more acceptable to implement.

***

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
==

The block combines the functionality of several blocks with _a narrow functionality_ and eliminates the list of logistics blocks from _repeating elements according to the principle of operation_.

![image](https://user-images.githubusercontent.com/13190430/77849511-caf0b700-71d4-11ea-9dc9-897a6471c394.png)

The proposed block also solves the routing problem _directly_, allowing you to **allow** and **prohibit** input/output for **different sides**, specify the **direction** and **prioritize** i/o flow of items.

***

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by CaribbeanMax** [comment]
So instead of using the existing blocks to come up with creative designs, you want a single block that just does everything on its own?

**Comment by Remint32** [comment]
> So instead of using the existing blocks to come up with creative designs, you want a single block that just does everything on its own?

On the contrary, I created it based on a long practical experience in the game and as a result of feeling the lack of some important opportunities in logistics, which, of course, can be achieved by current means, but it will be extremely difficult, unstable, and also impractical due to the speed of the gameplay.
It **doesn't** do _everything_, you can **choose** what it should do in a particular case. In this way, you can achieve the logic of existing gateways, as well as configure logistics more flexibly, without resorting to thinking out sophisticated schemes in a short time.

**Comment by MikouZonata** [comment]
Logistical challenges are the core gameplay and must be maintained. This block relieves too much challenge and I feel like it should therefor not be added.

**Comment by Remint32** [comment]
> Logistical challenges are the core gameplay and must be maintained. This block relieves too much challenge and I feel like it should therefor not be added.

It seems that you didn't really get into the essence of the issue, but just wrote a negative opinion in a rush.
If you look **_carefully_**, you will see that it does not solve all the problems **at once**, but allows you to **choose** a **specific logic** for a **specific case**, so that the logical challenges will **not** suffer in **any** way.
All that the block brings to the game is just a more accurate distribution in ratios.

**Comment by Remint32** [comment]
I hope that I eliminated all the stupid questions with the previous answer and you will begin to understand the essence of the proposal. Thank you for your respect.

**Comment by itcannotbe** [comment]
We read your initial post and to be frank your getting contrary to it.
![Screenshot_20200403_160045](https://user-images.githubusercontent.com/45280919/78337947-71b5c880-75c4-11ea-9543-37f4c935d355.jpg)

**Comment by Remint32** [comment]
> We actually read your initial post and to be **respectful** and frank, your reply is contrary to it.

If in your logic you think it contradicts, then I have bad news for you...

**Comment by Anuken** [comment]
This is not being implemented for several reasons:
- It's much more complex to grasp as a concept than the individual blocks it's supposed to replace. Sure, it's more powerful, but you have to learn how the UI and priorities work.
- It *can't* replace the old blocks, because so many designs use them and many people are used to the old mechanics. Yes, I could do some clever substitution and replace every blocks with an equivalent configuration, but that would be even more confusing for older players ("why is my entire design routers now?")
