### ISSUE TITLE
Seperate waves at once

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#740]
**Describe the content or mechanics you are proposing.**

Seperating waves in groups you can assign to droppoints

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will add the ability to have differant units come from differant angles, like crawler tree from the right,
dagger tree from the left, flare tree from the bottom....
Adding this wave customizability will be usefull in good map creation
Oh and another thing: --droppoints for every team--

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

with love<3
DS3K

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
YES. PLEASE.

**Comment by ThatOneBepis** [comment]
> Oh and another thing: --droppoints for every team--

idc if anything else is gonna be included
**but we need this one**

**Comment by potatoisagender** [comment]
Bee spam

**Comment by DS-3K** [comment]
Imagine pvp but you got wave support
Minute 3 wave for green
Minute 5 wave for purple
t-7m wave green
t-9m wave purple
and so on.. totes fun!:'D
