### ISSUE TITLE
Illuminator is redundant

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#742]
**Describe what you would like changed, and why.**
I would like the illuminator to produce a slightly stronger light, as currently you can just use a power node. The illuminator light is *overpowered* by power nodes. And it requires power, so you don't even notice the light.

**Describe the changes you want to propose. Include possible alternatives.**
Illuminator should produce slightly brighter. Alternatively, make power nodes and other power-related things less bright.

**Comment by potatoisagender** [comment]
opaque light just makes everything impossible to see

**Comment by Catchears** [comment]
I don't know where you're testing this, but for me Illuminators are significantly brighter than power connections/nodes.

![image](https://user-images.githubusercontent.com/57631841/95771188-ea57b900-0cba-11eb-8a4a-9fcff0bf7c38.png)

**Comment by A5TR0spud** [comment]
Weird. I gave mine power and it was no brighter than a powered power node or a solar panel.

**Comment by potatoisagender** [comment]
maybe because you had a map with little darkness
