### ISSUE TITLE
Illuminator Color can be Picked by Processor

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry-Suggestions#743]
**Describe what you would like changed, and why.**
The illuminator color should be able to be controlled by processor, similar to the color command in draw.

**Describe the changes you want to propose. Include possible alternatives.**
A color option in control, a new command, or using draw to change the color of the light produced by the illuminator.

**Comment by bsjohnson20** [comment]
I'm curious how many came here to upvote because of Quezler obligating us by the power of his mindustry server to vote up...

**Comment by A5TR0spud** [comment]
What?

**Comment by Mieew** [comment]
i like this idea maybe like you type a hex in the configure in the control command and when you sense the config of the illuminator it would say: ffffff not #ffffff

**Comment by genNAowl** [comment]
This is now ingame so close please
