### ISSUE TITLE
smarter launch pads

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#744]
**Describe what you would like changed, and why.**

currently launch pads keep firing even when the core in the target sector is full, it appears the resources are simply lost.

**Describe the changes you want to propose. Include possible alternatives.**

for the launchpad to not fire any resources that cannot be losslessly accepted by the destination sector.

> `# not a bug # 6.0 campaign # plz no mad`

**Comment by genNAowl** [comment]
`# plz no mad`
