### ISSUE TITLE
Trello change

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#746]
**Describe what you would like changed, and why.**

Trading cards/etc. and daily missions be available in Git and Discord 
it will be unfair

daily missions can be pls in game (discord/git/steam not required)
**Describe the changes you want to propose. Include possible alternatives.**
Trading cards/etc. and daily missions be available in Git and Discord 
it will be unfair

daily missions can be pls in game (discord/git/steam not required)

**Comment by itcannotbe** [comment]
>**Describe what you would like changed, and why.**
Trading cards/etc. and daily missions be available in Git and Discord
it will be unfair

How can this be changed whennot doesn't even exist yet.?

**Comment by unjown** [comment]
Read trello
