### ISSUE TITLE
Phase and surge reactor

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#747]
**Describe the content or mechanics you are proposing.**

sort of T2 thor reactor

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

With the increase of power demand its hard to coupe up

PS: why not impact?
A: it requires power to run i want a T2 thor reactor 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by unjown** [comment]
anyone??

**Comment by DS-3K** [comment]
What about the 2x2 thor/phase reactor?
You want a upgrade of that?
Well I think Phase is a bit too niche,
Im not sure if making power out of it will 
be a good addition to mindustry, but
it is a intruiging idea ^^

**Comment by itcannotbe** [comment]
Did anyone said a 2x2 power generator that uses phase or thorium?
Isn't that called a........

**Comment by DS-3K** [comment]
> Did anyone said a 2x2 power generator that uses phase or thorium?
> Isn't that called a........

Yeah I was talking about that one
I forgot what its called so I just described it

**Comment by stuffyAI** [comment]
> With the increase of power demand its hard to coupe up

no

**Comment by unjown** [comment]
> What about the 2x2 thor/phase reactor?
> Edit: its called RTG I remember know
> You want a upgrade of that?
> Well I think Phase is a bit too niche,
> Im not sure if making power out of it will
> be a good addition to mindustry, but
> it is a intruiging idea ^^

3x3 or 4x4 thats the size i want

**Comment by unjown** [comment]
> > With the increase of power demand its hard to coupe up
> 
> no

for pvp in attaner gaming yes it doeant apply to all (especially in campaign )

**Comment by unjown** [comment]
answer all ur issues? @itcannotbe @DS-3K @stuffyAI

**Comment by stuffyAI** [comment]
> for pvp in attaner gaming yes it doeant apply to all (especially in campaign )

no, especially pvp will always be balanced because your enemy has the same power problems as you, and if he doesn't he is better than you.

**Comment by DS-3K** [comment]
> > for pvp in attaner gaming yes it doeant apply to all (especially in campaign )
> 
> no, especially pvp will always be balanced because your enemy has the same power problems as you, and if he doesn't he is better than you.

A good game doesnt need to be balanced, a good game needs to be fun. The thing is, if something doesnt increase the fun it needn't be
