### ISSUE TITLE
A new kind of unit idk

### ISSUE THREAD

**Issue by Joshwelyt** [Anuken/Mindustry-Suggestions#748]
**Describe the content or mechanics you are proposing.**
WORM unit can go underground then strike from below, some ppl have been waiting for this making it a meme hehe idc wtf they say Haha request go brrrrrrrrr

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will be a great game give it 5 starts also the worm unit be kewl 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will be a great game give it 5 starts also the worm unit be kewl

How exactly?

**Comment by unjown** [comment]
Anuke saud "Do not suggest anything underground"
