### ISSUE TITLE
Make T4/5 pads treat payload conveyors/routers as air

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#749]
**Describe what you would like changed, and why.**
Since T4/5's can't get onto payload conveyors, I think it would make sense if they treated them as air/regular conveyors when exiting pads/factories. 

![image](https://user-images.githubusercontent.com/45698812/95672098-beb9bf00-0b52-11eb-9bc5-5cc078be2462.png)
^ Doesn't currently work but ought to work (imo)

![image](https://user-images.githubusercontent.com/45698812/95672107-d6914300-0b52-11eb-9102-896fd164f601.png)
^ T4/5 coming out through regular conveyors

**Describe the changes you want to propose. Include possible alternatives.**
alternatively, let t4/5s get onto payload conveyors somehow
(this isn't urgent/important in any way I just think it'd be nice to have)

**Comment by unjown** [comment]
I would suggest T2 payload conveyer

**Comment by itcannotbe** [comment]
No one wants a 7x7 conveyor TBH and the speed of the higher tier reconstructors kinda make it pointless to have a means of transporting units made from them.

**Comment by bsjohnson20** [comment]
Ah, but you see on certain maps it isn't possible to get the full amount In a row and having the conveyor would allow the ones that aren't conveyable to be so and not restrict the unit tier

**Comment by sample-text-here** [comment]
I had a hard time reading that comment.

Is there a need to move t5 units on conveyors?

From what I assume you were trying to say, trying to get the materials to the reconstructors is the fun part (make factories there, use mass drivers, use unit logic, or unload from core?)

**Comment by bsjohnson20** [comment]
Yes the part of connecting the resource intakes but the part where the unit conveyor could be made to support T5 and T4 units and essentially make it more of a ease to connect to T4 and T5 say if there was a large area that fitted an entire T4 but not be able to chain a T5 this would prevent t5s from.being built instead a conveyor could be added to connect to another larger area for the T5.

**Comment by stuffyAI** [comment]
> T4 but not be able to chain a T5

Then you have to build your factory better
