### ISSUE TITLE
Make shock ammo trigger on hits

### ISSUE THREAD

**Issue by CaribbeanMax** [Anuken/Mindustry-Suggestions#75]
**Describe what you would like changed, and why.**
Currently ammo with the shock effect only triggers on bullet timeout, but not when they hit.
This makes using surge as ammo for turrets really underwhelming and also makes Chaos Arrays as enemies a lot less threatening.
It also obsoletes the use of plastanium walls for defensive purposes.

**Describe the changes you want to propose. Include possible alternatives.**
Let shock ammo trigger on hits. Maybe add a chance to it if 100% would be too good.

**Comment by MikouZonata** [comment]
Agree with this. Feeding surge into turrets is a huge investment for very late game and should have an equally great impact. Triggering shock on Chaos Arrays gives them a distinctive feature which is desperately needed in the enemy roster.

**Comment by gen-NA-owl** [comment]
I think this is already implemented in 6.0
https://github.com/Anuken/Mindustry/blob/8f8117e94beca121b2fce1fc60be8eaf5bba22bb/core/src/mindustry/entities/bullet/BulletType.java#L159
