### ISSUE TITLE
Make drones (always) rebuild async

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#750]
**Describe what you would like changed, and why.**

for the building ai drones to distribute their broken block tasks more efficiently & reliably.

(here they all repair the same random conveyor every ~2 secs instead of the other ghosts)

![Screen Shot 2020-10-11 at 14 11 58](https://user-images.githubusercontent.com/3179271/95678273-e0a35800-0bcb-11eb-851d-27db2fae6e89.png)

**Describe the changes you want to propose. Include possible alternatives.**

sometimes the drones spread out to do their tasks async, but more often than not they all just build the same thing at the same time, instead of "reserving" a task so the other drones will try to (re)build something else nearby.

> code wise it would probably make the most sense to assign a drone to the rebuilding task that has the least amount of drones already on it so that if there are less tasks than drones they can still help speed it up, whilst also taking travel distance into account somewhat 🤔

**Comment by potatoisagender** [comment]
#102?

**Comment by Quezler** [comment]
that suggestion collects several v5 builder drone concepts, in v6 they are rewritten and already behave differently ^

**Comment by potatoisagender** [comment]
actually, could we use logic to control how many drones go to each area? Like x for each player and y for the defenses. and also split all rebuilding tasks among the defensive drones?

**Comment by Quezler** [comment]
the scope of this suggestion is just to make them not all try to rebuild the same ghost when more are nearby ^

**Comment by potatoisagender** [comment]
I was just considering expansion.

**Comment by DS-3K** [comment]
Gitta hate it when the crew be doing tasks togheter :/
Spread Out dammit
