### ISSUE TITLE
Material colours are included as part of the logic API

### ISSUE THREAD

**Issue by Rollcloud** [Anuken/Mindustry-Suggestions#751]
**Describe the content or mechanics you are proposing.**

Material colours are included as part of the logic API, either as @color-copper or @copper-color, etc. This information is already available has part of the game, see https://mindustrygame.github.io/wiki/items/copper/.

Alternatively, to match the current drawing API: @lead-red, @lead-green, @lead-blue.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would allow colour display's to easily and accurately represent the material they are indicating, eg, resource graphs. This functionality does not currently exist and requires manually looking up the RGB values of #d99d73 each time.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
why not draw itemcolor @copper` which uses item.color
and `draw blockcolor @router` which samples the icon at init time

**Comment by Rollcloud** [comment]
I like that too :)

Semi-related: is there a list of existing @references? I'm not as familiar with the commands as I would like to be.

**Comment by sample-text-here** [comment]
@DeltaNedas Why not combine item olor and blockColor into just contentColor?

**Comment by Rollcloud** [comment]
@DeltaNedas 
> deltanedas/rtfm

An invaluable resource, thank you.
