### ISSUE TITLE
Add block emojis for discord

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#752]
**This doesn't fit the template at all**
The discord should add emojis for all blocks, it has emojis for all units, and all items, so why not for all blocks? The current block ones should be removed, and all the new block ones should follow the name scheme of "block<block name>", kind of like what units do. This would make the discord cooler, which is why I am proposing it.

**Comment by Quezler** [comment]
keep in mind that there is an emoji cap limit on discord

**Comment by itcannotbe** [comment]
> **This doesn't fit the template at all**

The number of blocks in mindustry doesn't even fit the custom emoji cap on discord **at all**

**Comment by Highfire1** [comment]
for reference cause I was curious,
- the servers currently has 76 emojis out of 100.
- there is a total of 138 buildings, 33 troops, 16 items, and 4 liquids so far in 6.0. (not including terrain)
- In other words, 191 potential emojis.
