### ISSUE TITLE
Defense score

### ISSUE THREAD

**Issue by ThatOneBepis** [Anuken/Mindustry-Suggestions#753]
**Describe what you would like changed, and why.**
How sector destruction works. In other words, make it scale with defenses built, and properly simulate enemy attacks.

**Describe the changes you want to propose. Include possible alternatives.**
Introduce "defense score" mechanic, which is a sum of all defensive equipment (menders/walls/turrets/other defensive equipment) what is currently functioning. Walls , turrets and majority of defensive blocks would provide flat boost to it (ie. 3 duos with copper ammo would give out 1.5 or 0.9 defense score, while 1 meltdown cooled with water but causing power outages upon shooting would give out 5-8 defense score, depending on severity of the power outage), while menders and overdives would be multiplicative (with a specific limit), which would be then compared to sector's difficulty. After a turn ends, sector's defensive score would be subracted with sector's difficulty, and blocks would be damaged proportionally. If by any means defense score ends up being lower than 0, the sector in question is considered lost.
Possibility in unit's inclusion in the scheme is currently uncertain.

**Comment by stuffyAI** [comment]
Okay but where did the other half of the template go mate.

As you describe it rn you could just put tower in all corners, fill them with ammo and let that be, and any bigger simulation calculation for conveyors will be quite expensive for a mobile game.

**Comment by ThatOneBepis** [comment]
Considering the majority of sector layouts, i cannot say that would be any turret that wouldn't be used at one point. I tried to keep the concept as simple as needed, so various concepts that come out of it can be discussed.
