### ISSUE TITLE
Make schematic descriptions useful

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#755]
**Describe the content or mechanics you are proposing.**

Clicking on the info button for a schematic should show the description. Also, the search bar should also include the description in its search.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

In the latest bleeding edge build (10375 at the time of writing) players can add descriptions to schematics. They are almost completely useless. Adding the two features mentioned above will make descriptions more useful; the search feature would let players add keywords to their schematics (like "logic" or "power"). The description being shown in the info seems like a feature that would make sense to add.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by motaywo** [comment]
Not to diminish your idea, because it is a good one, but we already have the ability to add "keywords" to our schematics. I personally have a bunch of 3/4 letter codes I add to the beginning of any schematic I make, and then just search for that code - eg: `[LGC]` for logic, `[DEF]` for defense, `[GEN]` for power generation, etc...

**Comment by sample-text-here** [comment]
Yeah, but putting them in the description would make it less messy. Also there’s a character limit to the title. Finally, because the schematic power calculation doesn’t account for overdrive, you can put the actual power production amount (and other useful stuff too, like build time or input/output per second)

**Comment by RedstonerKBC** [comment]
I was just about to suggest this. Having the description visible in the info section as well as the editor section would be useful. Anuke, please add.
