### ISSUE TITLE
eject payloads into space

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#756]
**Describe the content or mechanics you are proposing.**

![bonk](https://user-images.githubusercontent.com/39013340/95690887-752cab00-0c0a-11eb-956f-72c1b2a8732b.jpg)
This should delete payloads, making them spiral off into oblivion.

`Dagger was not an Impostor`

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Good

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
every time you do this there has to be a cutscene that shows the unit spiraling off into space

~~payload yeeter~~

Also for slag too

**Comment by Volas171** [comment]
hmm it is an epic idea lol 
haha payload go brrr

**Comment by DeltaNedas** [comment]
yes for liquids too, they should drain into the void

**Comment by sample-text-here** [comment]
No, I mean dumping units in slag. Then watching them burn and drown at the same time.

**Comment by DS-3K** [comment]
What happens when you yeet naval units into slag or oil or burning oil?
