### ISSUE TITLE
Anti herrasment turret

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#757]
**Describe the content or mechanics you are proposing.**
Experienced players will always find ways to dodge your defenses and annoy the crap out of you. I suggest a cheap big(bad to stack) sniper turret that can one shot light units, costs power and has really low dps(long reload)
So you have time for proper defenses until they come in with multiple units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Hail/lancer and scatter currently serve this purpose but fail doing so against experienced Navigation and scatters take time to set up cus they need lead or scrap or glass.
This tower will remove single annoying targets even if they know how to dodge until you get proper defenses or they come with multiple units (RIP) I wouldnt suggest having cooland do much boosting, and dont give it penetration
Its all about single target destruction and should fail when chellanged with armies.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

Thanks for listening Anuken, good luck with all the balancing :3

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
What is herrasment? Has this something to do with hera?

**Comment by MLGTASTICa** [comment]
Good idea , we really need a long range turret to counter  player controlled units , Especially air as they are always used to flank and ruin factories.

**Comment by DeltaNedas** [comment]
very good idea
