### ISSUE TITLE
ISSUE CLOSED - i was dumb

### ISSUE THREAD

**Issue by konstantys** [Anuken/Mindustry-Suggestions#758]
**Describe the content or mechanics you are proposing.**

Titanium conveyors automatically making intersections when placed over plastanium conveyors. This isn't the case now (build: 10405).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think that the way this content could improve the game is obcious

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Apparently it is not obcious how it is not benefitial to have intersections with plastanium conveyors.

**Comment by genNAowl** [comment]
Honestly, I've seen way to many players on 6.0 servers thinking that plastanium conveyors are just upgraded titanium conveyors; **NO**. They are conveyors with an entirely different ruleset and function, and if any of you just took a bit of time in sandbox to play with them a bit, you would know it too.

**Comment by DS-3K** [comment]
I respect the realisation <3
