### ISSUE TITLE
Higher tier repair point

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry-Suggestions#759]
**Describe the content or mechanics you are proposing.**
Larger, with way wider range, more advanced repair point for healing up larger units. Could require phase fabric.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently, single repair point is sustainable for single, low tier units. As the technology goes up, it's more tedious to heal up units with big hp pool. Two possibilities include: destroying the unit, and producing the new one (waste of resources) or spamming repair points (power consumption can reach up few thousands while healing T5 units, it's also waste of space).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
I thought repair points heal a fraction of the max HP of the unit not a defined hp value?

**Comment by Kubek0212** [comment]
> I thought repair points heal a fraction of the max HP of the unit not a defined hp value?
From my quick testing, player ships heal up way faster than t5 units, so that's not the case.

**Comment by DS-3K** [comment]
**YES PLEASE**
I've always wanted this since doing health multipler map schenanigens.
Blocks get a mend projec,
Wheres our big boy repair point? Maybe cryo boosted too 3:
