### ISSUE TITLE
Google Play Games Achievements

### ISSUE THREAD

**Issue by Lapis256** [Anuken/Mindustry-Suggestions#76]
I would suggest supporting Google play games achievements in the same way as steam achievements.

Achievements allow you to add an extra element of fun to your game.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I won't be implementing any Google Play integration. This is a feature that will stay on the Steam version.
