### ISSUE TITLE
Trivial Sector Autocapture

### ISSUE THREAD

**Issue by stuffyAI** [Anuken/Mindustry-Suggestions#760]
**Describe the content or mechanics you are proposing.**
When you reach a certain point in the game, going back to capture low difficulty sectors just for more production becomes a nuisance: you quickly roll out you endgame defences with launched resources, and spam skip whilst sometimes waiting for energy/ammo to replenish, just to deconstruct it all. There is no challenge, just waiting.

This can be bypassed by either making the enemy retreat (Out of fear from you Tech level), perhaps by costing you some resources, or add another mechanic that increases the potency of units globally should you reach x Tech, x Turns or x Sectors captured. Latter might be hard to realize as some early maps lack sand and scrap, requiring launchpad support.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Removal of unneeded repetition.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
>Removal of unneeded repetition.
![Screenshot_20201013_184231](https://user-images.githubusercontent.com/45280919/95852509-71259800-0d86-11eb-9f4a-a5fb42c31244.jpg)
Isn't making stuff need user inputs actually stops you from "afking"?

**Comment by stuffyAI** [comment]
> Isn't making stuff need user inputs actually stops you from "afking"?
> 
> So much for actually checking the [Trello Board](https://trello.com/b/aE2tcUwF/mindustry-trello)

Please read my suggestion.

**Comment by DS-3K** [comment]
What if there was a 10x speed mode with super simplified graphics you could activate to ease the wait? :D
Actually sounds really fun to me!
