### ISSUE TITLE
Razor

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#761]
**Describe the content or mechanics you are proposing.**
A new unit called Razor. It would be black and white and would look like a modern day stealth bomber. It would be extremely fast and would bring a new mechanic to the game! This new mechanic which I call "Atmosphere Abort" is where the stealth bomber turns slightly opaque and makes it where all turrets and defences cant kill it (its too high), there is a con to this, since it cant attack also while in this stage. The Razor's Arch-Nemisis is the paralax due to the fact that it slows the Razor down and that just reverts the Razor's most powerfull asset. The thing that makes the razor the most fatal of all is the fact that some turrets cannot hit the razor due to its speed, things like the spectre, meltdown and Swarmer are most vunerable to this. The Razor's health would only be a measlly 100hp and its damage would be a staggering 300hp per bomb (it drops 5 bombs per bombing run). Here is a pro and con list of the Razor:

Pros:
Can fly over defences
Has Massive Damage
Can outrun Spectre's bullets, Meltdown's Blast and Swarmer's Rockets
Fast as heck

Cons:
Cant attack when flying overhead
Has a massive weakness to the Parallax
Low health
Is weak to fragment ammo

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I heard Anuke wants more fast units, so here is one for ya! There are other names for it too like Phantasm (inspired from a mod). And this unit would also be really annoying too.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
_this sounds **so annoying** to fight..._
I recommend merging this with the speed unit tree suggestion

**Comment by NexusDarkshade** [comment]
> turns slightly opaque

Opaque (noun):
1. not able to be seen through; not transparent.

**Comment by 50275** [comment]
This sounds like a very fat Wraith/Flare that instantly kills all transportation lines and scatters, which can also force you to defend every single part of your base even from the inside unless you get foreshadows and parallaxes literally everywhere
