### ISSUE TITLE
Mine

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#762]
**Describe the content or mechanics you are proposing.**
A mine that explodes when an enemy walks on it, not a shock mine, a explosive mine. This mine costs 5 blast compound, 10 silicon and 5 graphite and it deals 500hp of damage on step with aoe. Perhaps there could be a sea variant that deals 2000hp of damage costing 20 blast compound, 15 silicon and 10 graphite with 5 titanium and it is 2×2.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
We can have blast compound in core so why not.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
I forgot you can put blast in core in v6 so I was a tid confused at first... xD

**Comment by Ilya246** [comment]
Maybe have smaller coal+lead+copper mines instead?

**Comment by DS-3K** [comment]
It would be gud to have some stronk mines
What if they were proximity mines? Walkers and air couldnt dodge them then :c

**Comment by SirMachinegun** [comment]
Blast compound was a *resource* which couldn't get in the core. The reason resources can get in the core in v6 is because they are used for *research* in campaign. Other than that, they are *not* used as a building *material* (materials are items like copper, titanium, surge alloy... which can *get in the core* and can be used for *building*).

**Comment by stuffyAI** [comment]
> Other than that, they are _not_ used as a building **material**

not yet*

**Comment by catatagun** [comment]
> Blast compound was a **resource** which couldn't get in the core. The reason resources can get in the core in v6 is because they are used for **research** in campaign. Other than that, they are _not_ used as a building **material** (materials are items like copper, titanium, surge alloy... which _can_ get in the core and can be used for building).

Wat
