### ISSUE TITLE
Tile blocks showing who broke the block above them and what the block is.

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry-Suggestions#765]
**A small text, like the "last accesed by" when hovering your cursor over a tile block, that tell who broke the block above, and what was the block above was.**

**It will make it significantly easier to detect grief, replace what has been griefed and it will be a nice "Quality of life" change.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
This solution is messy to look at.
