### ISSUE TITLE
Actual naval branches/rework

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#766]
**Describe the content or mechanics you are proposing.**
Split the naval unit tree into 2 branches - assault and a new support branch. Should be self-explanatory. Additionally, remove minke's and bryde's abilities, and give them more hp/firepower, plus rework Omura.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More unit diversity.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
I **love** the idea of unit making units like the current tier 5.
I hope the naval branch goes more into this dirrection, with maybe one of them just being a aircraft carrier c:

**Comment by SupremeTurtle** [comment]
_Support naval should shoot lasers too_
