### ISSUE TITLE
Bigger Payload Conveyors

### ISSUE THREAD

**Issue by SirMachinegun** [Anuken/Mindustry-Suggestions#767]
Bigger payload conveyors, their stats may differ from the original one but its ability would be able to carry higher tier units.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by genNAowl** [comment]
NGL 7x7 conveyors seem like a YIKE.

**Comment by itcannotbe** [comment]
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Where did even this go?

**Comment by itcannotbe** [comment]
> NGL 7x7 conveyors seem like a YIKE.

Yeah. Big YIKE indeed. Also there is no need for you to move higher teir units with conveyors.

**Comment by sample-text-here** [comment]
#553 

And as expected, Anuke doesn't like this idea.
