### ISSUE TITLE
New controls for command center

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#769]
**Describe the content or mechanics you are proposing.**
Command center can pick which kind of troop the will command (ground, air, naval) 
maybe long hold for mobile than ctrl shift for pc??
similar to a older suggestion but instead of making a new cc adding a feature

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

ex. enemy def is only aa so u have all but only want naval to attack 
will help a lot in pvp/bvb

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by stuffyAI** [comment]
See logic blocks, they can somewhat do that

**Comment by bigbsonnier** [comment]
i like it

**Comment by Catchears** [comment]
Nice idea, but Anuke did say that better unit control won't be added:

https://trello.com/c/aWaX8E9F

**Comment by unjown** [comment]
> Nice idea, but Anuke did say that better unit control won't be added:
> 
> https://trello.com/c/aWaX8E9F

technically its a 50/50 cuz it half related

**Comment by unjown** [comment]
> See logic blocks, they can somewhat do that

..... not everyone knows how

**Comment by stuffyAI** [comment]
> not everyone knows how

Then they cannot use this feature, imagine being unable to use plastium conveyors, then you just cannot use them.

**Comment by itcannotbe** [comment]
Making units follow you isn't that hard and making just about anyone make units follow them is going to be a nightmare on servers. And besides, it isn't required to use unit logic to win the campaign.
