### ISSUE TITLE
Player abilities and upgrade modifiers

### ISSUE THREAD

**Issue by LeoVen** [Anuken/Mindustry-Suggestions#77]
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Mechs are cool but they don't add too much capability as a player if you wish to single-handled destroy the enemy base or defend your base. With player abilities and upgrade modifiers, there is another entire gameplay niche. These serve to buff the player so that the ship/mech will eventually be able to take down one of the top tier defenses by itself (maybe even more powerful, possible discussion).

This could add challenges like "No defenses map" where the player needs to build up and defend the base only using abilities and upgrades.

**Describe the content or mechanics you are proposing.**

__Upgrade Modifiers__

The player can have slots to add modifiers to the ship/mech. Some possible slots: thrusters, weapons, hull, shields, etc. These can be unlocked in the research tree.

These modifiers need to be crafted in each game possibly using some kind of new block that specializes in crafting them for the player.

There can be different tiers of modifiers depending on which item was used to craft them; e.g. a thruster modifier out of surge should be better than a thruster modifier out of titanium __OR__ have these modifiers use up multiple items __OR__ even better: have certain items be specialized to certain modifier slots. For example: titanium is mostly used for hull upgrades, phase fabric used more for shield, etc.

__Player Abilities__

Player abilities that can be researched in the tech tree. To use them you need to have a personal battery, resource pack and liquid tank (researched before any ability):

* __Personal Battery__: Stores energy (1000~) to be used for abilities;
* __Resource Pack__: Stores items (100 of each or some number around that) to be used by abilities;
* __Liquid Tank__: Stores liquids to be used by abilities.

The numbers can change for more or less and there can be upgrades to them as well.

To fill these up you will have to stand on a platform or your base with resources stored or you will have to manually pick them up (at first).

Abilities could serve three purposes (all numbers can be subjected to changes for balancing gameplay):

__Utility__

* Overclock: Increases building speed by 10 seconds by 10X. Uses 1000 units of power.
* Rally: Increases a bit of attack speed and damage of all nearby friendly defenses and units.

__Attack__

* Radioactive cloud: A cloud that damages enemies passing by. Uses 100 units of water and 20 units of thorium.
* Electric cloud: Forms a cloud of electricity. Enemies passing by take damage. Uses 100 units of water and 400 units of power.
* Force Wave: Launches a cone of energy dealing some damage to enemies. Uses 200 units of power.
* Hose: throws some selected liquid (Melting, Tarred, Freezing).

__Defense__

* Combat Shields: Adds a row of 1x1 defensive blocks in front of the player. Upgraded versions of this ability will require better items to create stronger defense blocks.
* Force Shields: Adds a temporary force projector. Upgraded versions of this ability can create a bigger force field, using up more energy.

__Notes__

Of course, some of these abilities might not fit into the game, but this is just to get some idea of the many possibilities. There is a big opportunity here to add another section of gameplay where the player is capable of being so strong to defend the base by himself/herself. 

__Edit__

Also, these abilities could be specific to each mech. The number of modifier slots can also be specific to each mech (tankier mechs have more hull modifiers and faster mechs have more thrusters modifiers).

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by LeoVen** [comment]
Added some more notes

**Comment by ifritdiezel** [comment]
Might also make abilities manually activated like in earlier 4.0 alpha.

**Comment by LeoVen** [comment]
Yes I forgot to mention that. These abilities are activated by the player. In fact, almost everything in the list should be activated only by the player, except maybe automatic loading of resources. This could make the player a lot more busy too

**Comment by DS-3K** [comment]
You are very much able to edit the health and damage to make a no defenses chellange, so a slight amount of your suggestion is already possible :D

**Comment by DS-3K** [comment]
This suggestion is very promising for moding, so if it is added, there can be some cool stuff made with it.

**Comment by LeoVen** [comment]
This idea came to me in a way to add some different styles of gameplay to mindustry. After playing the game for a while it gets a bit repetitive. You build some drills, make your initial defense, add more drills, upgrade defense, upgrade drills, upgrade defenses, build units...

**Comment by Rofle44** [comment]
What if you could upgrade Turrrets?

**Comment by LeoVen** [comment]
Upgrade turrets or upgrade modifiers. Something that really falls short is the range of certain turrets. People in PVE always build cyclones because of their better range and the higher tier defenses are left off.

**Comment by Anuken** [comment]
Abilities or upgrades that add on to existing units conflict with my design goals, and will not be added.
