### ISSUE TITLE
New ammo scatter

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#770]
**Describe what you would like changed, and why.**

more ammo for scatter 

**Describe the changes you want to propose. Include possible alternatives.**
make scatter accept - plast, blast, surge 

why not cyclone "AGAIN" i want air only turret i was planning on T2 scatter or plast scatter but peps in discord said no so i decided to make this suggestion

**Comment by SupremeTurtle** [comment]
No

**Comment by unjown** [comment]
> No

??

**Comment by stuffyAI** [comment]
> ??

No, if you think about it giving the scatter more ammo is pointless, by the time you get those ammo types you already have better anti-air options (not like scatter metaglass needs improvements)

**Comment by D-player1** [comment]
No

**Comment by Kubek0212** [comment]
Scatter is low-tier turret. Giving it high-tech ammo is pointless. The same apply to hails not being able to shoot blast compund. Reason: don't mix early and late game contents.
