### ISSUE TITLE
Mega likes suicide

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#772]
**Describe the content or mechanics you are proposing.**
Don't make Megas move forward when attacking

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
No more Mega suicide shit

Because they can get past your main defense

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
If stuff stops moving when it shoots and you don't have any long range stuff or have thick walls you're screwed.
