### ISSUE TITLE
Shield + Logic Blocks

### ISSUE THREAD

**Issue by HumanBean06** [Anuken/Mindustry-Suggestions#774]
**Describe the content or mechanics you are proposing.**
The ability to get statics about shields from logic blocks using the sensor command. (and a side thing: input/outputs for specific resources?)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I think it would help with combat logic control/statistics, or just informational gathering in general. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
> (and a side thing: input/outputs for specific resources?)

**A few things you shouldn't suggest**
**These have been proposed many times already, and I won't be adding them.**
    Additional configuration of blocks (e.g. I/O side configuration, which has been suggested a million times)

**Comment by Catchears** [comment]
> The ability to get statics about shields from logic blocks using the sensor command

Which values would you like to be able to detect?
