### ISSUE TITLE
destructive instruction set config option

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#775]
**Describe the content or mechanics you are proposing.**

A config option, enabled for singleplayer and disabled for servers by default, that allows dangerous logic operations like breaking, placing, rotating blocks, etc.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Allows for more advanced stuff but still lets server owners not have someone delete the whole map.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
I think unit control logic is also destructive enough for a toggle to exist for it also.

**Comment by DeltaNedas** [comment]
maybe just a general instruction toggle like `config logic ubind false`
or `config ucontrol.build false`

**Comment by sample-text-here** [comment]
We also need a config option. I saw this on the trello for logic, but getting units to to this would be great.
