### ISSUE TITLE
Making Maps Bigger Than 500 x 500

### ISSUE THREAD

**Issue by RainbowRogue** [Anuken/Mindustry-Suggestions#776]
**Describe the content or mechanics you are proposing.**

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - ['X'] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - ['X'] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - ['X'] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

### Big Maps
**My Request**

So I really would like to make maps bigger than 500 x 500 and ive seen them get bigger but i think it requires modifying the msave which is really hard for me. Please make the option bigger in v6 or maybe update the current version. I don't know how the updates work and stuff but i would be happy to see this change. -RainbowRogue

**Comment by RainbowRogue** [comment]
This is my first ever time using github account so sorry if i did stuff wrong

**Comment by RainbowRogue** [comment]
ah i feel like i did something wrong looking at other requests
should i restart the request

**Comment by DeltaNedas** [comment]
1. template
2. already suggested

**Comment by RainbowRogue** [comment]
oh
