### ISSUE TITLE
(logic) Switches remember state

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#777]
**Describe the content or mechanics you are proposing.**

When making a schematic with switches, they should remember their state.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It's annoying to have to reset all the switches in logic schematics. You can use logic to set switch states, but it might try to set the switch before it's built, breaking everything.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
implementing soon

**Comment by DeltaNedas** [comment]
oh, this already exists @sample-text-here

**Comment by sample-text-here** [comment]
oh yES it's implemented!
