### ISSUE TITLE
Units, Structures and Mechanics

### ISSUE THREAD

**Issue by DemoneX1704** [Anuken/Mindustry-Suggestions#779]
**Describe the content or mechanics you are proposing.**

## **—Two New types of Naval Units—**

**Amphibious Unit:** Have low health and low damage per shoot (to avoid replace ground and regular naval unit) but have a high DPS.
**Submarine Unit:** Is just a Submarine

## **—Defense and Unit—**
**Torpedo Defense and Torpedo Bomber:** The will be focus in destroy any Naval Units (Ships, Submersible, Submarine), but cannot destroy Hovers (because use levitation and really never touch water), and can't attack Air Units (for obvious reasons) or Land Units (except if Land Units are in water). The Torpedo is basically a """"new"""" type of Torret and the Torpedo Bomber is exactly like the Torpedo Defense but can fly. Torpedos follow the enemy.

## **—New Buildings and Other Things—**
**Massive Teleport Gate** Cost a lot of Resource, Energy and time to build and you need two of this Gates. Can teleport many Units to another teleport in another location.

### RTS
The V6 looks like a RTS version of Mindustry. This is a list of things that can be added
— **Fog of War Option Configuration** If the planet/map have natural ilumination with this option activated all your structures and units will be visible but you cannot see the enemy. When you see a zone that you explored before, for example you see that the enemy is building a T5 Factory and is at 50%, when you will look this zone without explore it again the T5 Factory still looks like at 50% of build, even if really is at 100% and is building Units. With this you are avoiding see any form of enemy progress, and only see the enemy progress with a radar/sonar (but cannot know what structure or unit is from that radar/sonar signal) or exploring the area again.
- **Spy Plane and Land Explorer** Have Low Health, don't have Weapons but have a High Speed and High Vision Range
- **Radar and Sonar** The Radar can detect Air, Land, Naval Ships, Hovers and Enemy Structures but a cannot detect the Sumergible and Submarine Units. And the Sonar can detect Naval Ships, Sumergible and Submarine Units. Radar and Sonar used energy. Torpedo Defense and Torpedo Bomber will need a have the ability of the Sonar (with less range) to be useful, in this situation.
- - The enemy structures looks in the map like colored figures
- **Stealth Fields Generator** This are a Structure and Units that make a field of Stealth, making impossible to a Regular Radar or the Sonar detect what are inside of the Stealth Field. A High Radar/Sonar Tech ignore the Stealth Fields of the enemy

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Why Amphibious Units can be very useful?**
The Amphibious Unit can useful to maps that have the enemy cores very inside of the land and with a ocean between each other, making impossible to naval units shoot the core (because is out of their range) and making useless the ground units. In this scenary the Amphibious units can be turns in a very useful tool to destroy the enemy defense and helping the allied air units to destroy the core. 
This are the two types of Amphibious Unit
 - **Hover** can travel on land, water and lava without burn because use levitation
- **Submersible** Have more health and damage that a Hover Unit. Can travel in land and can travel underwater making impossible for the regular units shoot it when they are underwater. The Underwater Amphibious Unit cannot shoot underwater (maybe in High Techs).

**Submarine Unit:** You need destroy this ship but avoid the air units? This sound a work for a Submarine, they will shoot torpedos underwater to destroy this annoying Omura ships and reclaim the Ocean.

**Torpedo Defense and Torpedo Bomber:** The will be focus in destroy any Naval Units (Ships, Submersible, Submarine), but cannot destroy Hovers (because use levitation and really never touch water), and can't attack Air Units (for obvious reasons) or Land Units (except if Land Units are in water). The Torpedo is basically a """"new"""" type of Torret and the Torpedo Bomber is exactly like the Torpedo Defense but can fly. Torpedos follow the enemy.

**Massive Teleport Gate** Cost a lot of Resource, Energy and time to build and you need two of this Gates. But when you link a Gate with other Gate this Gate will be share energy (so if for example use one Gate cost 5000 of Energy, when the two Gate are linked will cost 10000 of Energy) but only one will need have this would Energy (this is just don't make another massive energy production in the zone). Making possible Teleport a big army of Land, Air and Naval units more close to the enemy core. The huge cost of the Massive Teleport Gate will be obligate the players build before a base to protect the Gate that there will use to teleport the Army. For guide the units to the center of the Gate a **Command Center** can be very useful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
> **Massive Teleport Gate** Cost a lot of Resource, Energy and time to build and you need two of this Gates. Can teleport many Units to another teleport in another location.

> **These have been proposed many times already, and I won't be adding them.** 
... 
\* Teleporters

hmmm

some of these ideas are good, but some of them (like teleporters) are too op or are not going to be implemented

**Comment by DemoneX1704** [comment]
Yeah, and somethings like the Massive Teleport Gate can be replaced by the Amphibious Units (except if exist a wall between you and your enemy) , but the Massive Teleport Gate isn't OP is more a Mid-Game (if you are playing in teams) and you rush to build a very good defensive position in another part of the map, because this is like the Item Teleport (need two Teleports to work) or a End-Game, maybe can take 5 minutes (the actual T5 Factory cost 2 minutes to be builded)

**Comment by itcannotbe** [comment]
As proven by 3.x Teleporters are freaking over powered even with nerfs.

**Comment by DemoneX1704** [comment]
I have in mind a Teleport Unit of 9x9 or more bigger, or that you need build individual parts of the Teleport for example build 8 2x2 piece of the teleport around a completely clear area of 15x15. And to be used cost 10k of energy or even more

**Comment by itcannotbe** [comment]
I have in mind that you stop suggesting teleporters as in the **DO NOT SUGGEST LIST** to begin with.

**Comment by DemoneX1704** [comment]
With Teleporters probably refers the Teleport of ITEMS of Mindustry Classic https://mindustry.fandom.com/wiki/Teleporter

The thing what I'm suggesting is Teleport for UNITS not items

**Comment by itcannotbe** [comment]
Does it even matter what does the thing teleports when it generally said not to suggest teleporters?

And yes, there was a time where unit teleporters where considered and was scrapped because teleportors in general are OP. Just fly in your units if you want a faster way to bring in fat units.

**Comment by RogueRedHawk** [comment]
I agree with you Fog of War idea. Mindustry is the perfect game to have this type of RTS PVP feature. I posted about it as well in #498

**Comment by stuffyAI** [comment]
> Mindustry is the perfect game to have this type of RTS PVP

How does a factory building game have perfect properties for RTS features?

**Comment by DemoneX1704** [comment]
**My Reasons**
- The V6 looks like a RTS version of the game but the conveyors still be needed (things very great).
- And even if Anuke don't want add the RTS features to the campain, can be optional configuration to the Map Editor.

**Comment by stuffyAI** [comment]
>     * The V6 looks like a RTS version of the game

Have you actually played V6 outside of sandbox?
Where do you see RTS features?
The only real way to finely control multiple units is to write many lines of code in logic blocks, and even then you still need to produce vast amount of resources for your unit production, while defending you base with towers, like in an tower defence game...

**Comment by DemoneX1704** [comment]
I don't  want individual control for units (for this exist Command Units), just Fog of War

**Comment by DemoneX1704** [comment]
> > ```
> > * The V6 looks like a RTS version of the game
> > ```
> 
> ¿Has jugado V6 fuera de la caja de arena?
> ¿Dónde ves las funciones de RTS?
> La única forma real de controlar con precisión varias unidades es escribir muchas líneas de código en bloques lógicos, e incluso entonces, todavía necesita producir una gran cantidad de recursos para la producción de su unidad, mientras defiende su base con torres, como en un juego de defensa de torres. ...

Yes, I play the Mindustry V6 Campain and capture 4 sectors and I played a lots of times Mindustry V5 (actual version), and multiplayer gamer. This is enough?
