### ISSUE TITLE
Repair Centre

### ISSUE THREAD

**Issue by iutisteli** [Anuken/Mindustry-Suggestions#780]
We all know the repair point, that thing which heals the nearest unit.
We also need a repair centre, which is a 3x3 version of the repair point. Uses slightly more power, but it heals much more, and can heal 3 units at the same time. What do you think?

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by stuffyAI** [comment]
>     * I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Do that
