### ISSUE TITLE
Skirmish - AI Fights, Create, validation and revision

### ISSUE THREAD

**Issue by Void-Syrex** [Anuken/Mindustry-Suggestions#782]
I present to you - fights with AI

Fights against ai should be an independent development of the opponent without the participation of the player, that is the construction of management and Other

What can the fight with AI present?
1 learning is the main phases of the game, because primary learning is still an under-done thing. 
2. Entertainment - well that's understandable
3. Improving opinion about the game
4. Learning how to do it
5 More bugs
6 Hell's Ashes for loser bot players

Creation technology? - A Pvp-based database (pvp only 2 by 2, 1 on 1, 3 on 3 and 4 on 4) is entered into the game
Next, the AI analyzes the player's fights and actions, his stats, what he's done, the tactics and the memorized
After that the video is stored as comparatively, that is the fact this video the bot compares with another fight. 

After watching all this, the bot is tested by alpha testers whose fights are also recorded and tested. 

After successful passage begins a closed beta test and in which participants fight the bot through different tactics, from spam daggers to anything. Throughout the test, the bot compares all losing battles with the winning, their causes, tactics of the players and other things, after which it makes a saved dump file that uses as a guide

At the end of the closed beta, the AI update goes into the closed alpha version where there is already a program training bot based on the bot against the bot. 100 templates will be given for battles, each pattern can be finished by another correct template. 

After that, the bot is fed another 400 new templates where it again fights with itself, at this stage the AI gets at its disposal schemes that developers must designate and sign for the bot what the scheme is responsible for and where to put it. 

After that, the bot again goes to the closed beta, but already it merges with its first part and begins to use dump files. At the chewing stage the bot is given already players who play different tactics

After the closed beta, the bot goes to the stage of reviewing its slops and victories, where he is engaged in rechecking himself. 

Then the bot is trained to move units correctly, that is, if 1 unit stepped on a mine bot is looking for another way - an example. 

After all this is left to sew it into an open beta testing where he again learns the developers and revises himself, eventually the bot after leaving the beta Begins to look after the servers and their happening (except sand servers).

After a while, the bot stops co-ingling information and now it all depends on the developers 

The end

**Comment by itcannotbe** [comment]
What is your concept what "AI" is anyway?

**Comment by Void-Syrex** [comment]
> I present to you: Disregarding The Template.
> 
> On a serious note.
> What is your concept of what "AI" is anyway?

I think it's just a technology that has to think, do and solve problems, so it has to act like a human, not like a sledge jumping from the 6th floor with a cry of, "Go ****" 
As for the template, what did you mean?

**Comment by itcannotbe** [comment]
Do you even know how one makes an ai and the limitation and drawbacks of the certain way one makes one?
