### ISSUE TITLE
Tractor Beam

### ISSUE THREAD

**Issue by HumanBean06** [Anuken/Mindustry-Suggestions#783]
**Describe the content or mechanics you are proposing.**
Well, a tower, probably of 2x2 or up, in size, that uses power & shoots a beam that attracts enemy flying units, dealing no damage. Optional fluids/phase fabric to make it suck harder/faster? I do know that the parallax sucks enemy fliers in, but having a dedicated tower that does only that, and more powerfully, just seems neat!

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It may add more gameplay options by just having more anti-air options. Flying units are avoiding your anti-air? Stick a tractor beam! It may not get all of them, but it'll help! I don't know why I just wrote an ad for tractor beams, but that's an ad for tractor beams.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Didn't you just described what a parallax does but at the same time asking for another turret with the same functionality?

This suggestion is confusing TBH.
