### ISSUE TITLE
Tesla Coil/Charger?

### ISSUE THREAD

**Issue by HumanBean06** [Anuken/Mindustry-Suggestions#784]
**Describe the content or mechanics you are proposing.**
When I was asking why the Corvus (and I'm assuming other energy units) can't get charged, so nak#7428 on the Mindustry discord was suggesting random things that might charge them, then they said that there might be a tesla coil/charging station in the future, so I asked them if I could suggest it, and here we are.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This basically is just a Resupply Point but for units who need a charge. That makes units that are a struggle to build (like the Corvus) not have limited uses.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Catchears** [comment]
You realise that they recharge from batteries?

**Comment by stuffyAI** [comment]
It isn't fully implemented yet
