### ISSUE TITLE
A Major Minor Update For Logic (Plus Carrier Units)

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#785]
**Describe the content or mechanics you are proposing.**
I would like to see a little bit of tweaking done to logic. Namely, _tags_. Here's how those would work.
A new command would be added. In text, it would show up as `utag` but in the editor it would be `Unit Tag`. Using this command would apply a string tag to the first bound unit that matches the requested type the processor finds. An example: `utag @flare "Surge Carrier"`. Then, you would be able to sense said tag by asking for `@tag in @unit` with `sensor`, or rebinding with `bind @flare (tag here)`. Tags would show up above a unit like a name would, and could be colored with a drop-down menu inside the Unit Tag command. Each color would behave as a separate tag. If you want to input a tag manually, there could even be a command, `/tag`, that could be used while you're controlling a non-starter unit, that would give said unit a tag, using the same coloring commands as you would for a name. 

Additionally, I would like a third class of air unit, _carriers_. These units would have modest armor and no weapons, devoting themselves to speed and backpack capacity. The first tier would have 25 capacity and only cost 10 silicon to make. The second tier would double that, for 50 capacity. The third tier would have 100 capacity and 2x2 block capacity, the fourth 200 and 3x3 block capacity, and the fifth would have a whopping 500 capacity and be able to pick up 4x4 blocks. The t4 and t5 carriers would have much smaller hitboxes than the Oct, being closer to the Quad or even Reign in size. All five of these units would have speed comparable to the Flare, dropping only slightly, with the t5 being about as fast as a Zenith.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This one little change would vastly improve unit logistics. By adding a way to differentiate between two of the same unit, it would suddenly be possible to create much more complicated logistics systems. An example: 

You have a satellite crucible (no belts leading to/from it) you want to supply, using four of the t2 carrier units (three for input, one for output). Normally, this would be a daunting task of either using one unit and making three trips to load the crucible and one to empty it, or trying to issue commands to each one somehow, but with the tagging system, you can tag one of the carriers as `coal`, one as `sand`, one as `pyratite`, and one as `silicon output` and issue commands to them individually, or even use individual processors to talk to each one. 

The carrier units would just be a nice logistics addon, making it so that we don't have to use existing units in the logistics system, instead having purpose-built units to do that.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by imreallybadatnames** [comment]
ok
