### ISSUE TITLE
Compaign is hard

### ISSUE THREAD

**Issue by SupinePandora43** [Anuken/Mindustry-Suggestions#786]
In v6: compaign is super hard!!!
It would be much better if enemies won't deal so much damage.
Or if player can manually start waves, without timer

**Comment by stuffyAI** [comment]
> In v6: compaign is super hard!!!

You probably already have heard that from other games: git gud


If you only believe that because you updated during a ongoing campaign im sorry, you have to return to a sector and start with launched ressources

**Comment by itcannotbe** [comment]
@SupinePandora43 You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by itcannotbe** [comment]
> **Describe what you would like changed, and why.**

How exactly did the "compaign" got harder compared to the version you were comparing it to?

**Comment by SupinePandora43** [comment]
in v6: enemies can easily kill player.
in v5: they would need more time to do so.
in v6: spawncamping enemies isn't possible, because game spawn much more enemies comparing to last waves.
in v5: build a tunnel using walls, and build many `Duo` behind them (+regenerator), no one can go through it alive

**Comment by itcannotbe** [comment]
Actually spawn camping is a thing the developer wants to remove since v3.5

And also why the fuck do you even attack the enemy as an alpha. Upgrade yourself -_-

**Comment by DeltaNedas** [comment]
use the template and git fuckin gud.

**Comment by tghy71** [comment]
IMO it is true that the campaign is more difficult than it was before. However, there were only 1 or 2 difficult levels in the old campaign, so this is a welcome change of pace.

**Comment by SupinePandora43** [comment]
> And also why the fuck do you even attack the enemy as an alpha. Upgrade yourself -_-
instantly killing enemy was good tactic, because i can don't think about enemy, and concentrate on resources

**Comment by itcannotbe** [comment]
> because i can don't think about enemy, and concentrate on resources

Besides the fact I can barely understand what you just said, If you play the game just by focusing on gathering resources, you will lose. Harder maps on v5 are a testament to this.

**Comment by SupinePandora43** [comment]
It's for (xxx where x - number) maps
