### ISSUE TITLE
Apk modification detection

### ISSUE THREAD

**Issue by Kiki012184** [Anuken/Mindustry-Suggestions#787]
We have hacked apk problem on internet,may anime interested using some code from this game who detecting apk modification then make the game is unplayable for person who modify the apk
And this is painful https://imghub.io/i/oDny

**Comment by Kiki012184** [comment]
Some of word are wrong because I activated word correction

**Comment by DeltaNedas** [comment]
imagine if someone could `./gradlew android:assembleDebug -Pbuildversion=108`

**Comment by DeltaNedas** [comment]
if you dont want to download malware why are you downloading mindustry from malware websites

**Comment by Kiki012184** [comment]
Yeah I know but it's annoy me, I was given them a warn to don't do this but they ingored me,and delete message from me

**Comment by DeltaNedas** [comment]
tough luck

**Comment by Kiki012184** [comment]
H,they delete it,notice, now *insert menacing noises + effect
I spamming same message
