### ISSUE TITLE
in core database, show miner units' ores

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#788]
**Describe the content or mechanics you are proposing.**

```java
StringBuilder h;
ores.each(ore -> {
    if(unit.canMine(ore)){
        h.append(ore.emoji);
        h.append(' ');
    }
});
stats.add(h.toString());
```

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

A number on its own is pretty useless, the ores a unit can mine should also be displayed.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
You should really do a pull. I think it's easy enough to implement. Just seq the ores and their hardness and compare it to the mining power and list them XD

**Comment by Quezler** [comment]
currently there isn't a lot of room in the unit description window in the `v6` campaign tech tree.
imo this has a chance of being implemented once the core database & descriptions return in full. 🤔

**Comment by itcannotbe** [comment]
It doesn't need to be on the tech tree, just on the database/block info.
