### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Pekka-Angelo** [Anuken/Mindustry-Suggestions#789]
Hello Anuke, I wanted to ask you if you will add the option so that we have access to the tech tree in multiplayer because I am playing with a friend in version 6 and I cannot have any recource. Thank anuke

**Comment by itcannotbe** [comment]
Is it even that hard for people not to DELETE and properly use the template?

**Comment by itcannotbe** [comment]
TBH. The suggestion could have been worded better.

**Comment by Pekka-Angelo** [comment]
Hello sorry for not having formulated my sentence well.
If not, you are the person with whom we must communicate our suggestions


Le ven. 16 oct. 2020 à 19:36, itcannotbe <notifications@github.com> a
écrit :
