### ISSUE TITLE
Naming local servers

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#79]
**Describe the content or mechanics you are proposing.**

Adding the ability to add a custom name to a "local server" like it is possible to do with community servers

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think having a player´s name for a local servers name is not very representative of the servers contend, and leaves open questions like, if the server is private but shown online, I personally like to host a PVP match on a local server but rarely anybody joins even after long waiting times so it would be great to have a title to verify that everyone is very welcome to join and that I don´t have a private game accidentaly put on public, as that is suprisingly common to happen with local servers.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

Thank you for reading my suggestion

**Comment by itcannotbe** [comment]
I am quite confident that you do not know what is a local server and how does it work.

Has anyone already successfully joined your server, whatever the gamemode is?

**Comment by itcannotbe** [comment]
I am quite confident that you do not know what is a local server and how does it work.

Also what context is this? Steam or non-steam?

Has anyone already successfully joined your server, whatever the gamemode is?

**Comment by DS-3K** [comment]
Context: Steam server, yes people have successfully joined before on all gamemodes, but I´m talking about PVP specifically.
