### ISSUE TITLE
New Support Naval Unit Type

### ISSUE THREAD

**Issue by Pietro303HD** [Anuken/Mindustry-Suggestions#790]
**Describe the content or mechanics you are proposing.**
A new Naval type of unit which has a big storage, meaning it could get lots of resources, and move it to other places. It also could build, for supporting other Naval Units and, it would heal blocks, similar to a Mega. As a disadvantage, it moves really slow.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would fill in the empty space that the Naval Units have for only having one Naval type, and, would make water only maps more interesting, where you really would need to build defenses, and defend you base.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 1hu37y** [comment]
h
