### ISSUE TITLE
Reduce the Amount of Sectors in Campaign

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#791]
**Describe what you would like changed, and why.**

I do know that campaign is unfinished, but currently, it is a bit too grindy in my opinion. Yes, capturing a planet should be hard, but right now, I feel like there are too much sectors to capture.

With sector raids and other things planned, I feel like it will be a bit hard to micromanage lots of sectors in campaign.

With too many sectors, it also becomes hard to differentiate one from another. 

**Describe the changes you want to propose. Include possible alternatives.**

Reduce the amount of sectors.

**Comment by stuffyAI** [comment]
Check #760 ,perhaps that could address it

**Comment by genNAowl** [comment]
Honestly I don't want an autocapture either I want each sector to be an unique place that is memorable for its contents, and currently the generated sectors don't have enough variety for the amount of sectors it is used for.

**Comment by stuffyAI** [comment]
Well it is inevitable that some beginning sectors simply have to be similar because that's where you start out, we have to think of those beginning the game.

**Comment by Kyllingene** [comment]
The thing is, it is really hard to make memorable auto-generated maps. It may be better to have fewer sectors, but you really can't expect a memorable proc-gen map.

**Comment by genNAowl** [comment]
bonk
