### ISSUE TITLE
Plastanium pipes

### ISSUE THREAD

**Issue by Juliosh422** [Anuken/Mindustry-Suggestions#795]
**Describe the content or mechanics you are proposing.**

Plastanium pipe that seals its end so no liquid spills.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Since in V6 plastanium is going to be a very special material and essential for late-game bases, plastanium pipes can be a very useful feature. They would be very useful also for a nice defense, so a pipe can break without spilling all the nitrogen, it can be like the armored one (can't recieve liquid from sides and has more health).

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by JamesTheNerd** [comment]
plated conduits already do this

**Comment by genNAowl** [comment]
Yeah and plastanium pipes make me think of a version of plastanium conveyors with liquids instead of items...
