### ISSUE TITLE
Lock multiplayer + mods behind a requirement

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#8]
**Describe what you would like changed, and why.**

Currently any idiot that can't read is able to download mods and cry, or join a server to grief it and/or cry.
Locking mods/multiplayer behind a certain zone + wave would help weed out bad players.

**Describe the changes you want to propose. Include possible alternatives.**
Multiplayer: desolate rift, play it
Mods: desolate rift, wave 10

Once someone is able to use mods/mp then it could pop up showing a quick rundown on everything like dont "fix" peoples stuff without asking, simons modding docs, etc. and an I Understand button to close it.

Mods button is removed until the user unlocks it and WAN server access can be removed as to help with the griefing situation on default server list.

**Comment by Katsute** [comment]
One change that could be made to the server lists is to have the listing appear in red if they have incompatible mods (_since mods aren't automatically installed like maps yet_).
In the future the client could probably disable its mods, and only use the servers mods automatically.

![draft](https://user-images.githubusercontent.com/58778985/75611728-12f3bf80-5aeb-11ea-912f-e3476602c60f.png)

**Comment by DeltaNedas** [comment]
then it would need to ping every available server to see what mods are enabled, whenever mod list is changed and `join` is entered

**Comment by DeltaNedas** [comment]
now with be being how it is, maybe this could be looked at

**Comment by Anuken** [comment]
This is too invasive. Servers should implement their own tests for literacy if they so choose. In the long run, people will complain far more about a requirement like this than they do about the current state of things.
