### ISSUE TITLE
[QOF] Procedural Sector Names

### ISSUE THREAD

**Issue by Bedsurfer** [Anuken/Mindustry-Suggestions#806]
**Describe the content or mechanics you are proposing.**
Every sector gets a random name based on a few built in names/phrases (Generate once)

- Based on map type, biome(s), size, location, or derelict structures (If possible)

- include words like "Forsaken" "Desolate" "Volcanic" "Infected" before words like "Pass" "Valley" or "Shore"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more game play options or how it will fill a new niche.**
It would not only make the planet have a little more character, but It would make remembering certain sectors a lot easier, as number labels don't tell the full story.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
that would be ***very epic***

**Comment by SJPBP** [comment]
There need to be a way to destroy my own unit

**Comment by itcannotbe** [comment]
Don't hijack this suggestion. @SJPBP
