### ISSUE TITLE
Diagonal support for Line Tool

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry-Suggestions#807]
A new Option for line tool that let's us draw perfect diagonal lines

Add a new option to Line tool in mapping that allow us to draw only perfect diagonal lines for mapping becouse long diagonal lines is takes too much time and it's annoying without having a diagonal support for line tool.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Duplicate of #495

**Comment by itcannotbe** [comment]
Oh wait. YOU SUGGESTED IT BEFORE -_-.

**Comment by iLagSoUhax** [comment]
**MrByars** *used* **Confusion!**
*It's* **Super Effective!**

**Comment by MrByars** [comment]
> Oh wait. YOU SUGGESTED IT BEFORE -_-.

Oh, did I?

**Comment by MrByars** [comment]
Well, github not works I guess I dont see my old suggestion about this :/.
