### ISSUE TITLE
Enemy base carrier-dropping

### ISSUE THREAD

**Issue by konstantys** [Anuken/Mindustry-Suggestions#808]
**Describe the content or mechanics you are proposing.**
Right now, you cannot build in the opposite team's zone. To enhance warfare, i personally think that allowing carrier units to drop blocks into the enemy zone would be a nice idea. It would pair up very nice with https://github.com/Anuken/Mindustry-Suggestions/issues/699.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

In my opinion it would make warfare more tactical, allowing to make stationary war camps, etc.
Even though it may appear OP, it isn't so hard to defend against - you only need to be aware of an attack of this type to counter it, even with a traditional scatter spam strategy.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Drop Zone Radius: Exist.

**Comment by sample-text-here** [comment]
@itcannotbe I think they mean core no-build radius
