### ISSUE TITLE
Reading @config from a unit factory should return the unit type

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#809]
**Describe the content or mechanics you are proposing.**

When you use sensor to read `@config` from a unit factory, it will return the unit type (such as `@flare`, `@mega`, or `@spiroct`)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

`@config` is supposed to read configuration data. I think this would make sense and fit in with the current logic system.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sk7725** [comment]
Addition: @enabled should read whether the selected unit reached the unit cap(0 if it did, 1 if it didn't)
