### ISSUE TITLE
Auto repair mode / Auto repair all button

### ISSUE THREAD

**Issue by Pyrko69** [Anuken/Mindustry-Suggestions#81]
**Describe the content or mechanics you are proposing.**
I have idea for new button in gui, it can be switchable with hammer button Build/Destroy/Rebuild(Repair). 
When I am in building mode I see transparent buildings in place, where they are destroyed, and this is annoying to rebuild them one by one. In rebuild mode when you click and drag mouse over area (like destroying things) it should request build all destroyed buildings.

Other idea is to add button, which will select whole map and rebuild all. But I think reperair mode is a better idea. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
After big waves our defenses, turrets, conveyours are damaged and destroyed, it would be super duper good, when u could be able to rebuild base in seconds. I am android player, and this is really annoying to build destroyed conveyors near drills 

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
Getting a spirit drone should do the trick ;D

**Comment by YouDontSay1** [comment]
Yes, spirit and phantom drones are the answer. But an auto repair/rebuild button? No. Because...
1) ...this would make phantoms and spirits useless.
2) ...that would result in a too easy gameplay.

**Comment by Dotakiin** [comment]
I would appreciate this button. It doesn't make the game any easier, just saves the time of replacing the blueprints for destroyed buildings, which can be done while paused anyway.
