### ISSUE TITLE
Logic Speaker

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry-Suggestions#810]
**Describe the content or mechanics you are proposing.** The Logic Speaker, which can be connected to the processor to play a specific sound like `pew`, `boom`, `click`, etc. This may include modded sounds.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** This could be very useful for making alarm systems for different cases. ~~Or just for having fun with friends making loud noise.~~

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sk7725** [comment]
Planned in the "future" category of the Trello.

**Comment by TheSlaylord** [comment]
Logic Sound? Yeah, I saw that

**Comment by sk7725** [comment]
> Logic Sound? Yeah, I saw that

> I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

hhhhhhh bad boi

**Comment by Pietro303HD** [comment]
mp3 to logic/mp4tologic

**Comment by TheSlaylord** [comment]
> mp3 to logic/mp4tologic

it'd be probably impossible, but sounds funny

**Comment by bsjohnson20** [comment]
Imagine how many spammy logic controllers with a ruckus of noise...

**Comment by QmelZ** [comment]
when i saw the title it sounded like you want something similar to minecraft note blocks.
