### ISSUE TITLE
New Naval Unit

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry-Suggestions#811]
New Naval Unit for Naval Factory

Since we have 1 option for Naval Factory I think we need more, my idea is a Carrier Ship wich can pick up ground units and transport them to somewhere else becouse ground units is useless in most of Sea, Ocean type maps.
LvL 1 Ship can carry like 5 tier1 unit but tier 2 ship can carry more and Tier 2 also have anti air systems,Tier 3 Carrier Ship is can carry tier 3 Ground units also Tier3 Ship have better Anti Air system and Anti Ground system, 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Suggestedone9** [comment]
i have a similar suggestion which is number #690

**Comment by Pietro303HD** [comment]
I think it would be better if the ground unit could mount the boat, so it would be able to shoot,  while it's on the boat.
