### ISSUE TITLE
Переведите на русский язык 

### ISSUE THREAD

**Issue by DMITRY50** [Anuken/Mindustry-Suggestions#812]
![Screenshot_20201017_125152_io anuke mindustry be](https://user-images.githubusercontent.com/65097538/96334208-ac221700-1077-11eb-8e2f-903ba5fb792e.jpg)
**Describe what you would like changed, and why.**

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by TheSlaylord** [comment]
1) please make english title
2) do it in #translations in official discord

**Comment by Catchears** [comment]
Yes. Don't suggest translations here. Either do it yourself or ask if someone else can do it on discord. Also, try to stick to the format next time.

**Comment by BasedUser** [comment]
For now, the translators reached a consensus of not translating it until Anuke implements (or doesn't) some kind of text <-> graphics view change in logic.

На данный момент мы (переводчики) согласились, что это не будем переводить до окончательного завершения (или незавершения) интерфейса логики, а именно переход между текстовым и графическим режимами. После финализации менюшки можно будет переводить.
