### ISSUE TITLE
New super weapon

### ISSUE THREAD

**Issue by Pe4enkaAaAa** [Anuken/Mindustry-Suggestions#813]
**Describe the content or mechanics you are proposing.**

Super weapon - Controlable orbital laser strike
Like in factoryo end game rocket, we need to place silo, and get resourses in it.(Many resources for balance)
After it, rocket with satellite go to orbite.
Also we need to place turret/block to call laser strike, and you can control it for 5s.
Laser can destroy your buildings too.
(In pvp,rocket silo designate to other players)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This weapon can help at hard waves, diversify the pvp

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
deltanedas/routorio
