### ISSUE TITLE
Tree technology multiplayer

### ISSUE THREAD

**Issue by Pekka-Angelo** [Anuken/Mindustry-Suggestions#818]
**Hello, I would like to add a button to have access to the tech tree in MULTIPLAYER because I often play in multiplayer with a friend in V6 but I cannot unlock anything because there is no access to the tech tree.**

**I want us to have access to the tech tree in MULTIPLAYER because in v6 it prevents us from unlocking things in multiplayer which is annoying because I farm in multiplayer, I suggest adding the tech tree button in multiplayer next to the chat button 💬 thank Anuke**

**Comment by RogueRedHawk** [comment]
While I agree with this suggestion, it is a duplicate of #792, #789, and was discussed and dismissed in Anuken/Mindustry#2641. Also, see #687, #574, #722 for why Anuke is hesitant to add so many mobile controls.

**Comment by itcannotbe** [comment]
@RogueRedHawk Curiously the duplicate issues were made the the OP. though this suggestion is the clearest of the three.

**Comment by RogueRedHawk** [comment]
@itcannotbe I noticed OP was the same on three. He shouldn't post the same thing multiple times, and certainly not without closing the old ones. Also, that is why I linked relevant ones as well. I agree, this was the clearest of the three and I support the suggestion itself, just avoid duplicates.

**Comment by Pekka-Angelo** [comment]
Hello thank you for taking the time to take the time to take an interest in my proposal, would it be possible to warn me if Anuke will add the button of the technological tree in MULTIPLAYER because in solo there is the technological button but as soon as we host a game the tech tree button is no longer there 😔

**Comment by Pekka-Angelo** [comment]
![inCollage_20201018_124026770](https://user-images.githubusercontent.com/64195823/96365204-25387180-113f-11eb-80a6-dcd08a8603b0.jpg)
![inCollage_20201018_123410273](https://user-images.githubusercontent.com/64195823/96365206-26699e80-113f-11eb-971f-741244cb635c.jpg)

**Comment by Pekka-Angelo** [comment]
@RogueRedHawk

**Comment by Pekka-Angelo** [comment]
@RogueRedHawk

**Comment by roblabla** [comment]
At least, it'd be a good first step if both players could view the tech tree in multiplayer - even if only the host is able to interact with it.

I often play with a friend in multiplayer while voice chatting over discord. Discussing which upgrades to take next is made complicated by the fact that only one of us (whoever hosts the game) can see the tech tree.

Having a read-only view of the tech tree for guest players would help a lot.

**Comment by RogueRedHawk** [comment]
@roblabla This has been fixed I'm the latest update (build 121)
