### ISSUE TITLE
Thermal Pumps, why are they worse

### ISSUE THREAD

**Issue by DS-3K** [Anuken/Mindustry-Suggestions#82]
**Describe what you would like changed, and why.**

Having thermal pumps more efficient than rotary pumps because  they are more expensive than them and even theit discription agrees that they should be superior

**Describe the changes you want to propose. Include possible alternatives.**

Thermal pumps give 10LU per space, rotary pumps give 12LU per space.
Thermal pumps are way more expensive, it makes no sense to have them be worse.
Airblast drills are exactly as efficient as laser drills wich is underpowered but having the best pump be worse than the one before it doesn´t make any sense to me. I´m sorry if I may be a bit inpolite but it just bothers me. And yes I am aware that they have more size wich is an advantage but you rarely want to get more of the spaces from water covered, it´s more importand to just get most from the edges of water pockets.

**Comment by potatoisagender** [comment]
technically they are better, because while drills can cover the whole area, often, especially with large tar or deep water sources, you actually can only get the perimeter, and so by covering more land you get more water. It is really jank, but thermal pumps are for when rotary pumps aren't enough and you need more liquid but can't place any more.

**Comment by HaphLife** [comment]
I agree, the fact that there are situations where they are worse is really dumb. They should just be buffed to be 13liquid per block per sec.

**Comment by itcannotbe** [comment]
Here are the current stats:
Rotary vs Thermal
Power Usage | Per Tile | Per Liquid Unit
9 | 2.25 | 0.1875 vs 18 | 2 |  2
Tile Occupied
4 vs 9
Total Output | Output Per Tile
48 | 12 vs 90 | 10

**Comment by itcannotbe** [comment]
Also as pointed out by @potatoisagender, do can't go in the middle of deep liquid tile. The only time you can place in those places are when the pump or conduit is beside non deep liquid tiles.

Also you wouldn't cover a 2x2 using a thermal pump. It will cost more.
