### ISSUE TITLE
Shock mine

### ISSUE THREAD

**Issue by laok233** [Anuken/Mindustry-Suggestions#820]
**Describe what you would like changed, and why.**

Buff shock. Cause no one are using that, and usually forgotten

**Describe the changes you want to propose. Include possible alternatives.**
Buff the shock mine damage or make it cheaper to build

**Comment by SirMachinegun** [comment]
Making it not hittable by enemies would be the only and best solution.

**Comment by BasedUser** [comment]
dying = very yes

**Comment by RogueRedHawk** [comment]
Duplicate of #819 obviously, looks like you posted twice. Also similar to #323, in which we concluded the same as SirMachineGun. Also #762 seems like a better way of adding variety, in conjunction with making them not hit by bullets, vs. a solution of just straight up giving them more damage/cheaper.

**Comment by itcannotbe** [comment]
Mines in general are not supposed to be use as wall defenses.

Because units shoot walls and mines can be hit by bullets but in v6 unit control is a thing so mines needs some kind of mechanic change to be still effective when used properly.
