### ISSUE TITLE
A Real Mine

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#821]
**Describe the content or mechanics you are proposing.**
A real mine which would blow up on step. It would be pretty straight forward. There would be a landmine and a heavy mine. The landmine would be 1×1 and would deal 500 damage with aoe with fragmentation, it would cost 5 blast compound, 5 silicon and 5 graphite. The heavy mine would be 2×2, would deal 1000 damage, it would have more aoe with less fragments, it would be quite expensive at 50 blast compound, 60 silicon and 15 thorium.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

We got blast compound in core so why not. It would also be nice to have for crawlers.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
duplicate of #762
