### ISSUE TITLE
"Launch Core" and "Planet Map" Buttons When Core is Clicked

### ISSUE THREAD

**Issue by RogueRedHawk** [Anuken/Mindustry-Suggestions#822]
**Describe what you would like changed, and why.** On the Trello right now, it looks like Anuke is working on launching the core, trying to make it clearer how core launching works, etc. Specifically, the "Launch Core" option is hidden in the pause menu on mobile. Usually, the pause menu contains no game elements, and only contains things that operate "outside" of the game (graphics and controls settings, multiplayer configuration options, exit game). It can be concluded the "Launch Core" mechanic *does not* belong in the pause menu.

**Describe the changes you want to propose. Include possible alternatives.** I think the launch core mechanic should be available when the core is selected. This seems like the most intuitive option for me: not only are you launching the core, but you are also configuring resources to be launched, which you are already moving to the core. The "Planet Map" option should also be available when the core I clicked, for similar reasons as above and also maybe in the lore the core has access to data of adjacent sectors and cores around the planet via radar or similar.

I would suggest placing the buttons next to or below the resource UI that pops up when you currently click on the core.

**Comment by itcannotbe** [comment]
This might be solved when a tutorial is created.
