### ISSUE TITLE
A (water) sieve 

### ISSUE THREAD

**Issue by Thunderbeast0** [Anuken/Mindustry-Suggestions#823]
**Describe the content or mechanics you are proposing.**

A new building that can recieve water, and gives diffrent minerals as an output. It would work similarly to how slag works, except with water.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** 

I rember before I joined the beta, I was having a problem getting to a higher level in the begging maps, for the lack of no titanium, or other materials to make electricity. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. 
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
Sounds cool but also very op, would need to provide either little resources or have massive power requirements.

**Comment by Thunderbeast0** [comment]
> Sounds cool but also very op, would need to provide either little resources or have massive power requirements.

Of course, im not saying the new building should function exactly like the slag, but I am suggesting that it would be similar, like a late game building that needs lots of water and power. Maybe a 3x3 building that constantly needs at least 3 of it ports filled with water?

**Comment by 50275** [comment]
So if I went to Ruinous Shores and put a big line of pumps and Water Sieves, then I would get free resources for... almost nothing?
