### ISSUE TITLE
Item switch for logic

### ISSUE THREAD

**Issue by SuperNova-ReImagined** [Anuken/Mindustry-Suggestions#824]
**Describe the content or mechanics you are proposing.**
The ability to change the type of items chosen by a block that can do so, such as sorters, inverted sorters, sources, and unloaders, though code in logic processors

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It can open up more abilities to improve sorting, or for maps that implement item sources, change the source as needed. (or do the same with unloaders, if there is not enough of a resource in the vault/container/core)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sk7725** [comment]
More: Let @enabled be an integer, not a boolean(yes IK it *is* technically both double) and make it reflect the # for any block that has a configuratuon of integers, so you can read the configured item, unit(in unit factories) and more!
