### ISSUE TITLE
If and when anuke adds another planet, i think before that he should add a moon to the current one (for campaign)

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#825]
**Describe the content or mechanics you are proposing.**

Title says it all, basically add a moon before another planet, and maybe some asteroids

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Idk it will look cool and having a moon means more interesting maps so yay

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by GrandTeki** [comment]
To add to this, could asteroids utilize the new space tiles?

**Comment by 50275** [comment]
Don't think that's coming to V6 especially *after the beta build*
