### ISSUE TITLE
Cross platform cloud save

### ISSUE THREAD

**Issue by NoXZos** [Anuken/Mindustry-Suggestions#826]
Basically,saving data between devices.
It's a pain to have to manually export and import the data every single time I play on a different device.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
1. duplicate
2. why should mindustry have to do anything, use git, <cloud storage client of choice>, scp, etc

**Comment by itcannotbe** [comment]
I therefore conclude that who ever suggested this hasn't read the "**DO NOT SUGGEST LIST**"

**Comment by thw0rted** [comment]
FYI the issue template has been updated and now directs you to check the "do not suggest" section, which I didn't know was there beforehand.

**Comment by Kyllingene** [comment]
> # A few things you shouldn't suggest
> ## These have been proposed many times already, and I won't be adding them.
> - Mechanics that increase game speed (fast-forward)
> - Teleporters
> - Underground map layers
> - Trains, or any transportation system that uses something analogous to rails
> - Item-liquid junctions
> - Controller support
> - Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills
> - ***Built-in cloud sync***
> - Additional configuration of blocks, such as I/O side configuration, which has been suggested a million times

I see you are using the old template (pre-update #1169), which does not tell you to check README.md. So, I do not blame you entirely for not checking. However, in the future (for your sake), please check the README.md, [A few things you shouldn't suggest.](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest)

**Comment by Johnystar** [comment]
> > # A few things you shouldn't suggest
> > ## These have been proposed many times already, and I won't be adding them.
> > 
> > * Mechanics that increase game speed (fast-forward)
> > * Teleporters
> > * Underground map layers
> > * Trains, or any transportation system that uses something analogous to rails
> > * Item-liquid junctions
> > * Controller support
> > * Turrets on top of cores, or similar "merged behavior" blocks like turrets with drills
> > * _**Built-in cloud sync**_
> > * Additional configuration of blocks, such as I/O side configuration, which has been suggested a million times
> 
> I see you are using the old template (pre-update #1169), which does not tell you to check README.md. So, I do not blame you entirely for not checking. However, in the future (for your sake), please check the README.md, [A few things you shouldn't suggest.](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest)

@Kyllingene 

That is unfortunate because the game's current state doesn't allow you to easily sync save files across multiple devices without additional scripts. Mindustry bundles campaign progression and settings into one file:  https://github.com/Anuken/Mindustry-Suggestions/issues/380#issuecomment-846549516

Saves should be the same across different machines, but settings should not.
