### ISSUE TITLE
Managing the weather in a campaign

### ISSUE THREAD

**Issue by Westheimer-Lambda** [Anuken/Mindustry-Suggestions#827]
**Describe the content or mechanics you are proposing.**

I offer the on/off weather feature in the campaign.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This function is necessary so that those who have a weak device can disable weather events during heavy braking, such as a sandstorm. It doesn't change the game much, but it improves it for a comfortable game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by b1tt0** [comment]
shameless plug time
i suggested it like a month ago

**Comment by Westheimer-Lambda** [comment]
Похоже я слишком быстро смотрел, что не заметил это, прошу прощения, как можно убрать этот запрос функций?

**Comment by Westheimer-Lambda** [comment]
Sorry, I didn't notice. How can I remove this feature offer?

**Comment by b1tt0** [comment]
close the issue
