### ISSUE TITLE
Merge Planet Map & Launch Core Buttons

### ISSUE THREAD

**Issue by SirMachinegun** [Anuken/Mindustry-Suggestions#828]
Merging Planet Map & Launch Core buttons to one button so its better.

Currently there are 2 buttons which open planet map, one for checking your sectors and one for checking where you can launch. My idea is to merge those buttons into one button so that when it is clicked you can see planet map, your sectors, and where you can launch. This is better because it may be confusing for players when they see 2 buttons that do similar things. Also there'd be less buttons.

**Comment by QmelZ** [comment]
there could also be an option to show/hide the sectors you can launch, would make sense along this idea.

**Comment by stuffyAI** [comment]
What if I don't want to launch and just resume a sector?

It might be that launching to an ongoing sector may be treated as restarting it later

**Comment by SirMachinegun** [comment]
> What if I don't want to launch and just resume a sector?
> 
> It might be that launching to an ongoing sector may be treated as restarting it later

you go back then

**Comment by SirMachinegun** [comment]
> What if I don't want to launch and just resume a sector?
> 
> It might be that launching to an ongoing sector may be treated as restarting it later

you go back then

**Comment by SirMachinegun** [comment]
As I see it, it is implemented in beta 110 (I didn't looked for it now) so I closed this.
