### ISSUE TITLE
Logic Input Block

### ISSUE THREAD

**Issue by Pietro303HD** [Anuken/Mindustry-Suggestions#829]
An block that acts like a message, but when you finish the message, the block automatically wipes itself. Can be used with processors to get the inputted sentence

They would improve some logic designs, and improve the strong bond between the player and logic. With a block like this, casual players will get more and more will to use logic, since it's able to simplify a lot of stuff in Mindustry.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Sluethen** [comment]
This is already possible with a normal message block + logic commands

**Comment by Pietro303HD** [comment]
can you READ a message block?

**Comment by BasedUser** [comment]
use switches, can't be that hard to make *a qwerty keyboard*

**Comment by DeltaNedas** [comment]
you can't do much with strings in vanilla, this belongs in deltanedas/anuke-logic
