### ISSUE TITLE
Creator's name on buildings

### ISSUE THREAD

**Issue by Reiner91** [Anuken/Mindustry-Suggestions#83]
Good day, I was playing on public servers, dealing with people and trying to kick griefers and have them banned to prevent repeat offenders and thought it would be very convenient if there was a little bit of info on who built what blocks. It could even help find someone who may not know very much about building efficiently and we could explain it to that person if we only knew who it was.

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by claw4oo** [comment]
There is an anti grief client which can show anyone who modifies anything, so adding a creator, and last modified by would be really great to have.
