### ISSUE TITLE
Powered Doors

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry-Suggestions#830]
**Describe the content or mechanics you are proposing.**

Changing how doors work by adding a feature to them that allows powered activation (Doors may still be triggered by hand without power).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Powered doors could help automate how units move(even though logic blocks exist) because logic blocks and processors are a bit pricey early game.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
why would you ever want a door that costs 24 silicon and graphite when you can't afford 40 silicon for logic what
