### ISSUE TITLE
Scrap wall design not seeded

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#832]
**Describe what you would like changed, and why.**
Scrap walls have the same design on a tile even if they are replaced.

**Describe the changes you want to propose. Include possible alternatives.**
Change the way scrap wall designs work so the design type will be random on a tile.

(There are no checkboxes on the template)

**Comment by AgentAvis** [comment]
Last time this issue was marked wont fix, not a bug
