### ISSUE TITLE
"Fog of war" gamerule via lighting

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#833]
**Describe the content or mechanics you are proposing.**
Have enemyLights not only make enemies produce no light, but also disable minimap for players, for "true" fog of war. Additionally, have it be toggleable in the map editor.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More varying gameplay.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by summetdev** [comment]
> I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Are you sure?
https://github.com/Anuken/Mindustry-Suggestions/issues/679
https://github.com/Anuken/Mindustry-Suggestions/issues/679

**Comment by Ilya246** [comment]
This is not the same as the one you have posted

**Comment by 50275** [comment]
Disabling the minimap not only prevents you from seeing the enemy base, but it also prevents you from seeing *your base* as well.
