### ISSUE TITLE
Switch Statement for Logic

### ISSUE THREAD

**Issue by SirMachinegun** [Anuken/Mindustry-Suggestions#834]
Just like the switch statement in java, we need a switch statement for logic. This makes it so that we dont have to make a bunch of if statements making the code hard to understand.

So Anuke this game is written in java and I say It contains at least one switch statement meaning you know what it is. Just like how the if statement in java and if statement in logic are similar, we also should have a switch statement for logic, for easier writing code instead of making a bunch of if statements making the code messy and running slow.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
this sounds great except:
- ui would be clunky
- serialization would probably be a nightmare

**Comment by SirMachinegun** [comment]
> * ui would be clunky
> * serialization would probably be a nightmare

I can't say anything about serialization since i dont know but UI will be completely reworked in the future.
