### ISSUE TITLE
Melee units

### ISSUE THREAD

**Issue by ricardo1003** [Anuken/Mindustry-Suggestions#835]
Make melee units wat can't shoot, only... Punch or somthin?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** Idk

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by z0mbiesrock** [comment]
Melee units are a _YES PLEASE_.

**Comment by motaywo** [comment]
Isn't that basically the mace?

**Comment by notrealn** [comment]
mace and crawler exist
