### ISSUE TITLE
Sector Scanning/Radar

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry-Suggestions#836]
**Describe the content or mechanics you are proposing.**
As of build 109, selecting a sector does not show you what resources are available. Even if you lose a sector, it simply shows up as "unexplored" when you try to recapture it.
_As of build 111, this has been dealt with_

The addition of a radar scanner block would allow you to identify a sector before launching into it.
It can also allow for generating the sector and its minimap beforehand so you can plan a strategy for when you eventually launch there.

It can also allow for checking the composition of enemy waves in a sector.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Entering a fresh sector without any idea of what lies ahead can make it challenging to advance into unknown locations since you will most likely need to pause the game as soon as you land and pan around before doing anything.

Balancing the radar scanner should be simple enough, such as having a very high power consumption and taking some time to scan the sector, which can be sped up using multiple scanners.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
imagine going into a sector with only copper and lead *but on difficulty 8*

this actually happened
