### ISSUE TITLE
Use Texture dithering + scrolling for better animated liquids.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#837]
**Describe the content or mechanics you are proposing.**
Use texture dithering and scrolling to get incredible looking water simmilar to what you can find in nintendo games, https://noclip.website/#smg2/UnderGroundDangeonGalaxy;ShareData=ALb6DUuT/&8/~*$UF(2UVtfI:z,;8PUcxo4UQ|vfWcHj19U^jf9a::KUif]hW~2 (look at the water)

![image](https://user-images.githubusercontent.com/54417042/96494865-ee348f80-1214-11eb-9f1a-9005ffb95c17.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Mothership007** [comment]
I love this!
