### ISSUE TITLE
Limiting sorter chains to 60 item/s

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry-Suggestions#84]
**Describe what you would like changed, and why.**
Currently, sorter chains can transport far over 60 item/s when the client/server is under 60FPS
https://cdn.discordapp.com/attachments/674328534000467989/690315383109976125/unknown.png

And they can transport roughly around 60~ item/s when it is over.
https://cdn.discordapp.com/attachments/674328534000467989/690315281138319410/unknown.png

**Describe the changes you want to propose. Include possible alternatives.**

A compromise between the poll going in the discord right now, and this inconsistency,would be to set the hard limit of the chain to 60 item/s.

**Comment by CaribbeanMax** [comment]
You linked the same picture twice ;)

**Comment by Katsute** [comment]
The sorters should be changed to handle items at the speed comparable to routers and junctions.

**Comment by claw4oo** [comment]
> 
> 
> You linked the same picture twice ;)

Fixed it by editing the link,
https://cdn.discordapp.com/attachments/674328534000467989/690315383109976125/unknown.png
