### ISSUE TITLE
Greenish Water & Deep Water for Oceans like Atlantic Ocean

### ISSUE THREAD

**Issue by SirMachinegun** [Anuken/Mindustry-Suggestions#840]
Greenish Water & Deep Water (Tropical water), they are the same as normal water & deep water but they are just more greenish like Atlantic Ocean's water, so only difference is sprite/texture

This will give map makers a second option for making oceans, some people like them so much too.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by MEEPofFaith** [comment]
so grass water

**Comment by MEEPofFaith** [comment]
I'll... do that after class.

**Comment by MEEPofFaith** [comment]
By after class I mean procrastinate a few hours

**Comment by Bohaska** [comment]
You could have just made a pull request... Sprite changes aren't that complicated.

**Comment by MEEPofFaith** [comment]
I'm lazy and haven't even started yet.
