### ISSUE TITLE
Land in zones with (or as a) more powerful units

### ISSUE THREAD

**Issue by SarisWinterwisp** [Anuken/Mindustry-Suggestions#841]
**Describe the content or mechanics you are proposing.**

Upon being able to craft a powerful unit (such as an Oct or Toxopid) it would be cool to be able to bring one with you (or spawn in as one if the entity can create blocks) to defend your base from the first few waves of enemies

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It can be menial to set up a defense of duos or scorches, only to immediately delete them to replace them with lancers and arcs (and other such transitions). By allowing players to drop powerful units they can allow players to ignore defenses while they get up to speed with tech and macros. It would help give players a sense of how powerful they become over the planet if they're able to just spawn into a world with a small army or large unit to protect the core as it sets up defenses for itself. Perhaps it could be a later unlock in a tech tree so that you don't steamroll all the early zones until you're sufficiently powerful enough to do so.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
like imagine landing in every sector bringing a T5, just waiting for the waves to end without building
