### ISSUE TITLE
New power source 

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#842]
**Describe the content or mechanics you are proposing.**
So, basically when surge is used as ammo it has a shock effect. So why not turn it into power? My idea is this: A5x5 reactor that requires surge as power, but also needs oil and cryo. But here's the unique part: it will output power and slag, and if you don't remove all the slag it will catch on fire. And I think it should output like 13k power ish but idk. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will add a power source that requires waste disposal witch is unique 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by MEEPofFaith** [comment]
more extreme than fire. just a straight up meltdown, big explosion, and slag sprayed everywhere. Which then sets the oil on fire and then `this is fine`.

**Comment by MEEPofFaith** [comment]
though couldn't you just leave an incinerator next to it to delete the slag.

**Comment by RouterChainsSuckk** [comment]
> though couldn't you just leave an incinerator next to it to delete the slag.

Yes that's 1 option although I think incinerators are a bit to op as they are

**Comment by MEEPofFaith** [comment]
~~Mines scrap out of water.~~

**Comment by unjown** [comment]
we need this

**Comment by DeltaNedas** [comment]
impacts and arc reoucters exist
mod

**Comment by Mothership007** [comment]
Love this idea!

**Comment by RedRanger5577** [comment]
i like it, it should also have a huge verry destructive explosion were it to break or you cant get slag out or cryo out fast enough.

**Comment by 50275** [comment]
Let's compare this to the impact reactor. It takes Copper, Lead, Silicon, Titanium, and Sand (the rest can be made with sand)
It makes... 13k power. Why not just get 2 impacts for much cheaper and more power production?
Why not turn the Lead, Sand and Titanium into impacts?

there's really nothing unique to this, it's effectively a big differential generator that requires an incinerator, with slag input that won't do anything

**Comment by unjown** [comment]
No response from Anuke :cry:

**Comment by sample-text-here** [comment]
> No response from Anuke 😢

> How do I know if you've read my suggestion? 
If it's been 24 hours, I've most likely read it. I check this repository daily. If I like it, I'll implement it.

@unjown relax. just because anuke doesn't respond to every comment or idea doesn't mean they didn't read it
