### ISSUE TITLE
Prevent multiple units from mining from a same ore tile at a time

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#844]
**Describe what you would like changed, and why.**
When it comes to mining, Units have the upper hand because they can capitalize just mining a single tile all at the same time, while only one drill can occupy the same ore tiles.

**Describe the changes you want to propose. Include possible alternatives.**
Ore tiles should prevent multiple units from mining from them at the same time.

**Comment by Quezler** [comment]
![4j5cla](https://user-images.githubusercontent.com/3179271/96575235-ca368400-12d0-11eb-8b17-9ca5cd7a808d.jpg)

**Comment by itcannotbe** [comment]
> That's like the entire reason to get mining drones at all on maps with little resources.

Then the map still has little resources then. XD.

**Comment by itcannotbe** [comment]
Aside from those maps this would improve game balance. Cause spamming units won't be the answer.

**Comment by scarf-generic** [comment]
> Aside from those maps this would improve game balance. Cause spamming units won't be the answer.

Cause we all know that spamming units is sooooo easy in v6, not like theres a unit cap to prevent this or anything...

**Comment by itcannotbe** [comment]
This suggestion would only affect you if you are forcing your units to mine near the closest drop point.

**Comment by Iloveidea** [comment]
I like this suggestion. Mining units simplifies the logistics system, Disrupt the game and waste CPU

**Comment by itcannotbe** [comment]
![Screenshot_20201025_164432](https://user-images.githubusercontent.com/45280919/97102656-3b67a400-16e2-11eb-8419-8072afc1dc0f.jpg)
This suggestion exist because this is stupid. Don't you agree?

**Comment by itcannotbe** [comment]
Implemented as of build 111

**Comment by DS-3K** [comment]
The entire point of mining units is so you dont need to have copper and lead infra, so why would you nerf them OUT OF THEIR VERY USECASE???

**Comment by asdfasdfasdfasdf213981274098127409** [comment]
Lol doesnt actually care about monos just wants attention

**Comment by OnyxDog07** [comment]
I would've preferred if it was limited to 2-5 units per ore block

Would've made monos a bit more useful

also Draug Miners in v5 did the same thing.
