### ISSUE TITLE
Trains and Factory Stuff

### ISSUE THREAD

**Issue by MasterOktagon** [Anuken/Mindustry-Suggestions#845]
**Describe the content or mechanics you are proposing.**

Larger Maps: 
This is already in Trello, but in shelved ideas. I think it could be cool to make bigger and bigger factories but the maps are being small at the end.
Factory Buildings/Domes:
You can build them, they protect the things inside, but they dont regenerate their lives like a energy shield. maybe units cant come in
Mining pit excavator:
A "Unit Block" which you can move to the destination and then turn into a block, which you can connect.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Larger Maps:
More and bigger Factories
Factory Buildings/Domes:
A little bit like a primitive force projector. would be cool because all factories would concentrate in one of these like in real world.
Mining pit excavator:
It would be a very good Mine, but you have to produce them in unit factories.

sorry for bad english

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by XEN0PHIL** [comment]
![image](https://user-images.githubusercontent.com/55051135/96588246-1642f200-12ec-11eb-9870-4e8bb5efa019.png)

**Comment by MasterOktagon** [comment]
oops...

**Comment by notrealn** [comment]
close the issue?

**Comment by ThePythonGuy3** [comment]
wtf i love when ppol literally dont read the stuff

**Comment by RedRanger5577** [comment]
this isn't factorio and we have mass drivers

**Comment by MasterOktagon** [comment]
Right... and plastanium conveyors.
I have to read better next time.

But what about the other stuff?

**Comment by Bohaska** [comment]
I can't understand your scramble of suggestions. Can you knock the train and rails part out?

**Comment by MasterOktagon** [comment]
Ok
