### ISSUE TITLE
Map logic blocks for history and events

### ISSUE THREAD

**Issue by MasterOktagon** [Anuken/Mindustry-Suggestions#846]
**Describe the content or mechanics you are proposing.**
Map logic blocks which makes logic for mapping. Like logic blocks, but they are not destroyable. with several extra actions like print [Text] at x,y or spawn unit at x,y or change weather to ...

I would make two versions. one only goes through one tike and one always checking statusses or Something like this

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

you could do more mapping stuff like stories

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by motaywo** [comment]
Is this something that players could interact with and modify, or something only configurable in the editor?

**Comment by MasterOktagon** [comment]
Something only configurable in the editor
