### ISSUE TITLE
Remote Server control

### ISSUE THREAD

**Issue by 0x454d505459** [Anuken/Mindustry-Suggestions#848]
**Describe the content or mechanics you are proposing.**

I think it would be useful to somehow be able to control our Mindustry server everywhere in the world. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would be really useful for guys like me that are never at home and ssh doesn't really work so yeah this would be a great feature. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
have you heard of chrome remote desktop, or other similar remote access software that is made specifically for *this*

**Comment by DeltaNedas** [comment]
ssh *does* work

**Comment by Vortetty** [comment]
lets see how many things can already do this:
one of the hundreds of remote desktop apps
ssh 
telnet
you could write a remote access script
