### ISSUE TITLE
2x - 4x game playback speed

### ISSUE THREAD

**Issue by bitt0008** [Anuken/Mindustry-Suggestions#85]
**Describe the content or mechanics you are proposing.**
Additional speed for game playback - so it all can go up to **4 times**.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Lower the waits between waves (in case the player wants to farm) and possibly make new challenges.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by CNC-er** [comment]
Is this directly increasing the speed at which the game runs? If yes then slowing down the game to 0.25X would be really nice on later waves so that fps doesn't tank.

**Comment by bitt0008** [comment]
> Is this directly increasing the speed at which the game runs? If yes then slowing down the game to 0.25X would be really nice on later waves so that fps doesn't tank.

yep, but wont be a feature in multiplayer - only campaign / singleplayer

**Comment by CNC-er** [comment]
This would also be sweet on quite a few maps where you either have to wait long times for things to happen like resource accumulation or waves to come when you can't force them to come.

**Comment by itcannotbe** [comment]
What also would be great if you know that speeding up the game dependent on how much available resources allocated to the game has. As for most people typically running a late game at 60 fps is already a chore, let alone speeding it up.

**Comment by Anuken** [comment]
This has been proposed many times; the game doesn't support it and I will never add it as an option.

**Comment by Dank-Null** [comment]
could you potentially create a list of things you will never add?

**Comment by rmperkow** [comment]
@Dank-Null He did.
