### ISSUE TITLE
Change turret cooling amount

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#850]
**Describe the content or mechanics you are proposing.**
1x1 turret = 6 water/sec
2x2 turret = 12 water/sec
3x3 turret = 30 water/sec
4x4 turret = 120 water/sec

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Haha nerf go brrr

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RedRanger5577** [comment]
Nah i think its good being different for every weapon

**Comment by 50275** [comment]
hail and ripple both eating 12 cyro/sec _seems fair_ /s
