### ISSUE TITLE
Show an error message or don't let players attempt to export schematics with forbidden symbols in the file names

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#852]
**Describe the content or mechanics you are proposing.**
When attempting to enter a symbol that isn't supported (: / < > " * etc) into the file name when exporting a schematic, show an error message and/or don't even let the player attempt to save it.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently (beta 109), when trying to do so, the game will either export nothing, or create a file with a size of 0kb and name it whatever you typed into the file name box up until the forbidden symbol. This could potentially be confusing.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
only / (and \0 ofc) is forbidden on normal systems.

**Comment by itcannotbe** [comment]
Blame windows/ntfs

**Comment by DeltaNedas** [comment]
mkdir -p $(dirname a/b/c/d.msch)
