### ISSUE TITLE
Rtg gen rebalance

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#853]
**Describe what you would like changed, and why.**
Basically as of right now rtg gens are never used due to cost and steam gens produce more power. What i suggest is having rtg gens not require phase to bulid. Also being able to imput phase should be removed or buffed because it makes no sense that phase produces less power then thor.

**Describe the changes you want to propose. Include possible alternatives.**
What I Basically said up there + make it over all cost less and produce 50+ more power ish

**Comment by D-player1** [comment]
All your statements here is false.
First, steam gens doesn't produce more power, they need water, and what would you do if there is no water, yes, water extractor, wext needs 90 energy while steam gems produce 330 energy, that means 330-90=240, it's lower than RTG's 270 power/sec.
Saying that RTG doesn't need phase is like removing plastanium from overdrive construction cost.
If no one literally cares about putting blast compound into generators, why should we care about inputting phase on RTGs.

And plus, RTG makes 4050 power with just 1 thorium

**Comment by scarf-generic** [comment]
Or maybe just make them more expensive but not require thorium input? Currently we have no reliable power source in the game, expensive rtg could fix this

**Comment by D-player1** [comment]
Sounds like solar panel but with extra steps, and not affected by day and night cycle lol

**Comment by BlueWolf3682** [comment]
(considering irl rtgs are built and then generate power forever at a constant rate without needing input, i see where thats going)

**Comment by scarf-generic** [comment]
> Sounds like solar panel but with extra steps, and not affected by day and night cycle lol

Thats exactly the idea. A stable power generator that is **not affected by anything except taking damage and breaking**. This would mean that at least one power source in the game wont stop working for whatever reason (weather, ground tiles, anuke hitting the big red "nerf" button on his desk, daylight cycle, etc.)

**Comment by itcannotbe** [comment]
Nobody pointed out that RTGs use up their fuel at a already slow rate.

**Comment by potatoisagender** [comment]
yup. we need someone to tell us comparisons between fuel and power generated.

**Comment by genNAowl** [comment]
Yes rtgs are balanced, but they aren't very interesting, and aren't too distinctive; I would prefer something like tile affinities or something else?

**Comment by RouterChainsSuckk** [comment]
> All your statements here is false.
> First, steam gens doesn't produce more power, they need water, and what would you do if there is no water, yes, water extractor, wext needs 90 energy while steam gems produce 330 energy, that means 330-90=240, it's lower than RTG's 270 power/sec.
> Saying that RTG doesn't need phase is like removing plastanium from overdrive construction cost.
> If no one literally cares about putting blast compound into generators, why should we care about inputting phase on RTGs.
> 
> And plus, RTG makes 4050 power with just 1 thorium, RTG is just low on power/second

No they do produce less power then steam gens because your not factoring in laser drill power cost

**Comment by MLGTASTICa** [comment]
> > All your statements here is false.
> > First, steam gens doesn't produce more power, they need water, and what would you do if there is no water, yes, water extractor, wext needs 90 energy while steam gems produce 330 energy, that means 330-90=240, it's lower than RTG's 270 power/sec.
> > Saying that RTG doesn't need phase is like removing plastanium from overdrive construction cost.
> > If no one literally cares about putting blast compound into generators, why should we care about inputting phase on RTGs.
> > And plus, RTG makes 4050 power with just 1 thorium, RTG is just low on power/second
> 
> No they do produce less power then steam gens because your not factoring in laser drill power cost, also power per secound matters a whole lot more then power over time so even though it might be efficient thorium wise, its power per second makes it not very good. Also your whole inputting blast to steam gen thing makes no sense because blast causes steam gens to explode where as phase doesn't. Also rtg gens aren't a advanced solor pannel because they require power to kick start

RTG's are currently the simplest form to make energy , and honestly almost the most efficient , with a single thorium blast drill you can fuel an enormous amount of RTG (40+) , they are also much more efficient than  water generators , because in the space used by a steam generator setup (steam generator + water extractor) it uses twice the space , compared to a RTG which  uses all the space for itself without further requirements.
If you overdrive them and overcharge them with phase and silicon ,you can get 600~ energy output , this makes a block of 30 RTG's generate 18000 energy, they are if im being honest better than most energy sources , only balanced by the rarity of thorium and their material requirements.

**Comment by 50275** [comment]
V6 Beta Build 109
To get the 18000 power you'll need about 30 RTGs with phase overdrives, which use (1/15*2.25) thorium per second. That's... quite effective. It only takes a little less than 4.5 thorium per second.
