### ISSUE TITLE
Minable blocks

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#854]
**Describe the content or mechanics you are proposing.**

Unlike mining wall blocks these would be completely new blocks that will be minable. The new block will be generated it cannot be placed and it promotes the usage of mining units to clear out areas to use for factories and whatnot. This can also be used by map makers as they wish. They should only be in the variants of hard ice and compressed sand (maybe stone but I think that doesn't make much sense. It seems too hard). 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will add a new middle - end game thing you can do as a player. If you are strapped for space then you can mine out these areas. if you need more ores to mine from these areas might uncover some. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
So... destroying terrain with units?

**Comment by the-kido** [comment]
> So... destroying terrain with units?

Yeah basically, just not the terrain blocks already in the game. I can already guess someone requested a future like that so I thought of a better approach that lets the mapmaker decide where and how to place these _breakable blocks_. Think of them like copper walls if you will.

**Comment by Bohaska** [comment]
What does mining ice give you? Water?

**Comment by the-kido** [comment]
> What does mining ice give you? Water?

Nothing. Just space and sometimes uncovered ores.

**Comment by the-kido** [comment]
Anuke prob saw this so imma close
