### ISSUE TITLE
6.0 Units (this time for real)

### ISSUE THREAD

**Issue by Arackulele** [Anuken/Mindustry-Suggestions#858]
**Describe what you would like changed, and why.**
(I messed up making this the first time sorry)
So basically in 6.0 where all units produced are controllable, there arent any real upgrades or usable units that are fast and can build . In 5.0 theres lots of fast and snappy ships, and in 6.0 everything feels slower and more tedious because units are all sooooo slow and controlling most offers basically no real benefit in basic tasks

**Describe the changes you want to propose. Include possible alternatives.**
Roght now i think High tier units should be faster and more practical to use (more units that can build and are better to controll) or adding a unit type that is fast and can build or something like that because everything in 6.0 feels a but too slow especially when controlling big ships you can take minutes flying from 1 side to the map to the other

**Comment by motaywo** [comment]
Well, absolutely yes to all of that, but faster units are something that have been requested _many_ times already, and are on the trello as something not being worked on. 

_+100 Stealth tho, for just deleting the part of form asking you to check those things..._

**Comment by rmperkow** [comment]
@motaywo There aren't any checkboxes in this template

**Comment by Arackulele** [comment]
> 
> 
> Well, absolutely yes to all of that, but faster units are something that have been requested _many_ times already, and are on the trello as something not being worked on.
> 
> _+100 Stealth tho, for just deleting the part of form asking you to check those things..._

I didnt delete any , there werent any at all lol and sorry for not checking everything but i couldnt find anything suggesting current units should be faster

**Comment by GrandTeki** [comment]
Megas are still fast enough to be useful, and they have a 2,5 times faster building speed than Gamma.

**Comment by Arackulele** [comment]
> 
> 
> Megas are still fast enough to be useful, and they have a 2,5 times faster building speed than Gamma.

Im not saying there arent usable units, just that the speed of the fastest units is a joke , and that there should be at least a fast option for movement not bulding speed
