### ISSUE TITLE
New Campaign Map: Delta Valley

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#859]
**Describe the content or mechanics you are proposing.**
A new map called "delta valley". It would be a lushious earth-like map. It would have a massive river in the middle of the valley. Your core would be right beside the river. The river would open up to the wide ocean (hence "delta" valley). There would be mud and dirt with some stone also. This map would unlock below fungal pass on the left side, the required things you would need to unlock to unlock this map would be: the Rotary pump and the water tank.

This map would be the first of its kind to have **naval units** in waves, there would also be air units but no ground units as the units come in from the ocean.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

No other maps have naval units

It would have more use for the naval units in the campaign

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
> This map would unlock below fungal pass on the left side, the required things you would need to unlock to unlock this map would be: the Rotary pump and the water tank.

In the 6.0 campaign, this doesn't mean anything. It is completely reworked.

I think a more general suggestion, such as "Add a map that has the spawn point over water, with naval and air units spawning" is a better suggestion than this. That way you can convey the idea that a problem (no naval units in waves) needs to be fixed with a general solution (maps with naval units in waves).

**Comment by potatoisagender** [comment]
honestly, I'm getting really tired of these 'add this specific unit'. Like, we don't really care, just post it on discord or smth. It's kinda stupid. At this rate, you might as well just make the unit/map and suggest it to anuken or make a mod. Additionally, Anuken is probably not adding anything else, except schematics.

**Comment by DS-3K** [comment]
> honestly, I'm getting really tired of these 'add this specific unit'. Like, we don't really care, just post it on discord or smth. It's kinda stupid. At this rate, you might as well just make the unit/map and suggest it to anuken or make a mod. Additionally, Anuken is probably not adding anything else, except schematics.

Yeah I've made my first suggestions like that too, and I can confirm that its much better to just give a idea and not a finished product
Source: 1.new turret: the enforcer
2. Anti herassment turret
Those are basically the same issue, but the first got immidiatly rejected and the second got quite popular :D
