### ISSUE TITLE
Material specific coloring for Phase conveyors and Mass drivers

### ISSUE THREAD

**Issue by Dank-Null** [Anuken/Mindustry-Suggestions#86]
**Describe the content or mechanics you are proposing.**
Stripes on phase conveyors based on the material inside them and the same thing for mass drivers. Additionally the purple dot on the phase conveyors could be also/instead used to show what item is in a phase conveyor. 

I believe stripe logic for the phase conveyors could work as follows:
Display stripes on the phase conveyor the same color as the material that is in the conveyor, if two materials are in the phase conveyor then one stripe could be for one material and the other  stripe for the other material. If more than two materials are in the phase conveyor, then just display the current phase conveyor design or multiple partial length stripes, one partial length stripe for each material.

Example:
[https://imgur.com/gallery/eQ0rwTm](url)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Currently whenever you use multiple phase conveyors side by side for instant item transport  across annoying terrain or obstacles to things like defensive position knowing what is in each conveyor can be quite difficult and may require flying all the way to place where items are input to the conveyor lines. Additionally when just flying around my base I may want to hook something up to an existing phase conveyor line but in order to find whats in a specific line you have fly to the input side of the chain. 

Same thing with Mass drivers, once you get multiple mass driver lines setup to feed resources to something far away across annoying terrain or obstacles avoiding sending items to the wrong mass driver can become a hassle and eventually mistakes are made and purging of 100's of items to remove the contamination is for me the fastest method in very cramped spaces, which isn't nice when you accidentally send plastanium into a line carrying phase fabric.
Consice pdf attached.
[Proposed alteration of phase conveyor and mass driver appearance.pdf](https://github.com/Anuken/Mindustry-Suggestions/files/4432073/Proposed.alteration.of.phase.conveyor.and.mass.driver.appearance.pdf)

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by CNC-er** [comment]
The igmur url is broken. Here is the url again.
https://imgur.com/gallery/eQ0rwTm

**Comment by Katsute** [comment]
How would mixed lines work?

**Comment by CNC-er** [comment]
Read starting at:
I believe stripe logic for the phase conveyors could work as follows:

**Comment by Katsute** [comment]
Would the mass driver have a storage bar? Showing all the resources inside the driver?

**Comment by CNC-er** [comment]
I think that by itself would also be nice addition, since currently we know how much is in a mass driver not whats in it. So a similar display to you what you get when you click on something like a silicon smelter would be nice.
