### ISSUE TITLE
Comment blocks for logic

### ISSUE THREAD

**Issue by Vortetty** [Anuken/Mindustry-Suggestions#860]
**Describe the content or mechanics you are proposing.**
Add comment blocks for logic

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will allow people to be able to better understand code, and if you write your code in text (i do and i know a few others do at least, i find it alot easier to read since we cant zoom out and jumps often get cluttered very quickly) it will make using jumps considerably easier, since you dont have to account fro the extra lines a comment currently adds

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
> I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

Hmmm not saying that’s not true but #413 hmmm yes

**Comment by DeltaNedas** [comment]
1. comments already exist
2. they dont take up addresses

**Comment by Vortetty** [comment]
> Hmmm not saying that’s not true but #413 hmmm yes

didnt see that sorry

> comments already exist

they do but we have no way to comment in processors and when you use text editors to program stuff you have to account for comments adding lines that arent doing to be there in the processor, so making them able to be in game would fix 2 problems

**Comment by DeltaNedas** [comment]
they dont add lines

**Comment by Vortetty** [comment]
they dont add lines in a processor

they add lines in text form

meaning that when writing code as text, not in a processor, but as text, you have to account for the ide counting that as a line
