### ISSUE TITLE
Launchpad managment

### ISSUE THREAD

**Issue by BlockOfBudder** [Anuken/Mindustry-Suggestions#861]
**Describe the content or mechanics you are proposing.**

I beleive having launch pads launch resorces from one sector to another is already planned, but I think there should be some way to visualize, change, and manage those launch pads from the planet map view. You get a list of all the launchpads, their resources per second, home sector and destination sector, and you can chnage where the destination is by clicking a sector on planet view.

Also it would be cool if you could launch units

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would help inprove game as the sectors would feel more connected, your bases would feel more connected, and making cool inter sector factories could also be cool. (you send lots of sand to another sector that only has coal for an exanple). Also if you were in trouble in one map you could send tons of resources or units with only a few button clicks instead of needing to go to each sector and change each pad individually.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
Launch units? Ok, but please make that option unavailable until you get the Large Launch Pad.

**Comment by iccor56** [comment]
i am far more interested in a visual indication on the world map as to where the launches are coming from and going too.
