### ISSUE TITLE
Walls

### ISSUE THREAD

**Issue by miking666** [Anuken/Mindustry-Suggestions#862]
Please add barriers from flying units.
There are not enough walls from flying units, lekgo's enemies can fly around the guns and destroy the base, and it is very expensive to put turrets everywhere.
In the new version, you can pilot huge ships, some of them can transport robots. The enemy alone can fly around the defense and destroy you and this is very annoying.
I hope that you will take this into account, and one day everyone will be able to see it in the game.

**Comment by D-player1** [comment]
Putting scatters all around the base isn't expensive, and it looks like you're a victim of PvP

**Comment by miking666** [comment]
> Разбрасывать скаттеры по всей базе не дорого, и похоже, что вы стали жертвой PvP
1.weapons take up a lot of space.
2. It's not always useful

**Comment by Idontknow9898** [comment]
an air wall would make no sense

**Comment by TheSlaylord** [comment]
really, just place scatters around

**Comment by potatoisagender** [comment]
force projector is close enough.

**Comment by DeltaNedas** [comment]
why wouldnt an air unit just fly over the air wall

**Comment by DS-3K** [comment]
I fully support the idea of a block that walls off flying units- as a terrain block for map creation!

A buildable air block wall does not make sense,
the closest thing Id like to that would be some aoe slow down field generator, like with shields
But we have waves with cryo wich do work kinda well too c:

**Comment by 50275** [comment]
In V5, you only need a thin line of fuses and mend projectors to kill a few thousand revenants.
In V6, you still have the fuse, and if they get a T5 air unit, just get a foreshadow.
