### ISSUE TITLE
More info about units

### ISSUE THREAD

**Issue by EnganK** [Anuken/Mindustry-Suggestions#863]
**Describe the content or mechanics you are proposing.**
At the moment, the database contains only the most basic information about units - health, speed, item capacity, and mining / construction speed. This information is too little to understand well the characteristics of the units.
I propose to make sure that other information is displayed, in particular - a detailed description of the unit's weapons (type, range, rate of fire, damage, AOE, etc.) and its features (Quasar's shield, carrying capacity of units of the Mega line, etc.) Also, the units themselves would benefit from a short description.
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
A detailed description of the units will allow better planning of attacks. And in principle, it is interesting to learn their characteristics not only from Mindustry code.
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by D-player1** [comment]
~~Rtfsc~~
