### ISSUE TITLE
Speed Minimizer

### ISSUE THREAD

**Issue by Idontknow9898** [Anuken/Mindustry-Suggestions#864]
**Describe the content or mechanics you are proposing.**

A 2x2 tower who has a 10 block range. Slows everything of the enemy down(factorys,mechs...) ,if in range. Needs power and thorium.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will make pvp more interesting and survival more easy if you get to higher waves.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by rmperkow** [comment]
Here is a tile I made for it
![unitdisruptor](https://user-images.githubusercontent.com/63563342/96734056-21e3f680-1388-11eb-8e78-dccce5315b33.png)

**Comment by Idontknow9898** [comment]
> Here is a tile I made for it
> ![unitdisruptor](https://user-images.githubusercontent.com/63563342/96734056-21e3f680-1388-11eb-8e78-dccce5315b33.png)

lol

**Comment by rmperkow** [comment]
I tried

**Comment by sample-text-here** [comment]
Have you heard of *waves/tsunamis with cryofluid*

**Comment by 50275** [comment]
this sounds bad
why wouldn't you just shoot the enemy air units with scatters before they got 15 blocks from you
don't even mention ground units at 15 tiles away the lancer is still broken

**Comment by Bohaska** [comment]
whats wrong with the lancer?
