### ISSUE TITLE
Show core database on gamemodes other than campaign

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry-Suggestions#865]
**Describe what you would like changed, and why.**
The core database is only on campaign.

**Describe the changes you want to propose. Include possible alternatives.**
Show the core database on custom games so you can check unit stats.

**Comment by MasterOktagon** [comment]
The core Database is actually in custom games
![Screenshot_20201022-171813](https://user-images.githubusercontent.com/57826808/96893098-a28b1b80-148a-11eb-9d30-bde9d3ec84d5.png)
In the right korner of the top bar on mobile and om PC

**Comment by rmperkow** [comment]
Will check soon

**Comment by GrandTeki** [comment]
The computer version of the game does not have the top bar present, it's only on mobile. Why do you say it is there?

**Comment by rmperkow** [comment]
Where is it on PC?
- [ ] found it

**Comment by GrandTeki** [comment]
> Where is it on PC?
> 
> * [ ]  found it

That bar is replaced by the bottom bar, and the keyboard.

**Comment by MasterOktagon** [comment]
oh, sorry

GrandTeki <notifications@github.com> schrieb am Fr., 23. Okt. 2020, 23:39:

**Comment by rmperkow** [comment]
It is here
