### ISSUE TITLE
Multiple keyboard layouts

### ISSUE THREAD

**Issue by Osiris-Team** [Anuken/Mindustry-Suggestions#866]
**Describe the content or mechanics you are proposing.**
Enable the user to save & use multiple keyboard layouts.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
-It would be useful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
why would it be useful

**Comment by Osiris-Team** [comment]
@DeltaNedas Because u can save multiple keyboard layouts and try different layouts

**Comment by Catchears** [comment]
Why would you need multiple keyboard layouts? 

>mention how it may add more gameplay options or how it will fill a new niche

**Comment by Osiris-Team** [comment]
> Why would you need multiple keyboard layouts?
> 
> > mention how it may add more gameplay options or how it will fill a new niche

@Catchears why wouldn't u?
- You can try out new/different keybindings

**Comment by 50275** [comment]
You can already do this, even in V5. *Have you even looked at the settings?*
![image](https://user-images.githubusercontent.com/68676339/96775508-9e40fe80-13b5-11eb-8bb0-8a9d8de0d8aa.png)

**Comment by Osiris-Team** [comment]
@50275 And where exactly are those multiple keyboard Layouts of I may ask?

**Comment by 50275** [comment]
You can simply just change the controls to simulate different positions of keys on the keyboard
Why would a player ever want to suddenly switch to a new set of keys that are completely unfamiliar after getting used to the controls they already have

**Comment by Osiris-Team** [comment]
@50275 Ah fk it

**Comment by DeltaNedas** [comment]
if you yourself wouldnt dream of using it, dont suggest it
