### ISSUE TITLE
Touch controls for Windows/Linux editions

### ISSUE THREAD

**Issue by Osiris-Team** [Anuken/Mindustry-Suggestions#867]
**Describe the content or mechanics you are proposing.**
There are some ultrabooks out there running windows but with a touchscreen. Implementing these touch controls from the mobile version to the desktop version would be great!

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Osiris-Team** [comment]
Linked to: https://github.com/Anuken/Mindustry-Suggestions/issues/866

**Comment by DeltaNedas** [comment]
touch is worse than keyboard why would you want that

**Comment by Osiris-Team** [comment]
@DeltaNedas I like to use my notebook like a big tablet that's why.

**Comment by AgentAvis** [comment]
I agree with orsiris, it would be very nice to be able to use touch controls on windows version.

**Comment by itcannotbe** [comment]
I don't agree cause touch controls has too many drawbacks to mouse and keyboard controls on pc.

**Comment by Osiris-Team** [comment]
> I don't agree cause touch controls has too many drawbacks to mouse and keyboard controls on pc.

@itcannotbe But its not like that keyboard controls would disappear lol. U would be able to choose which controls u want to use. Also it would be so hard to add this feature, as there are already touch controls existing for the mobile version.

**Comment by DeltaNedas** [comment]
the problem is:
1. you didnt read existing suggestions (in mindustry repo)
2. desktop sdl backend doesnt support touch

**Comment by Kyllingene** [comment]
> you didnt read existing suggestions (in mindustry repo)

Wait, are you saying there was an issue on the main repo about this? I thought *this* was the place for suggestions, and *that* was the place for bug reports only.

**Comment by Hycord** [comment]
If I were to make a pr that implements touchscreen would you merge it? (Assuming all requirements are met of code standards, etc.)
