### ISSUE TITLE
Programmable Speaker

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#868]
**Describe the content or mechanics you are proposing.**
It will make sound signals and show an icon with a provided message on minimap. Identical to Factorio one.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
E.g. you are want to be aware of enemies coming or material deficit in some point. Currently there is no way for logic to tell you about these events without you checking these places.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by TheSlaylord** [comment]
This is similar to #810

**Comment by sample-text-here** [comment]
> I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.

[press x to doubt](https://trello.com/c/yij5RfGc/734-logic-sound)

**Comment by RandomTNT** [comment]
> earrape schematic when

Bro, it can be delayed, i mean, spam would be skipped

**Comment by rmperkow** [comment]
I made a tile for it
![speaker](https://user-images.githubusercontent.com/63563342/97013114-a82e4300-1516-11eb-948c-ec88dfa3904a.png)

**Comment by rmperkow** [comment]
I think it should be a beep speaker

**Comment by RandomTNT** [comment]
> I think it should be a beep speaker

Burn it
!!!
