### ISSUE TITLE
Factory chains | a way to revolutionize factory designs (Controversial)

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#871]
**Describe the content or mechanics you are proposing.**

I would like to be able to make factories less than 3 blocks long _chainable_ meaning if a resource goes into one of the factories it is evenly spread across all of them. These chains overlay factories and whenever factories are being mined the chain is mined first. The chains will cost something each factory for a somewhat heavy price. This would be useful for end-game players strapped for room and can make some interesting designs. I call It controversial because it eliminates the usage of distribution chains but it's really up to Anuke.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will help the players strapped for space, it will help players who don't want to use slow distribution chains and It prove interesting for players and how they use it. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
![image](https://user-images.githubusercontent.com/56274831/96776045-4eeed400-139d-11eb-8d21-3139292eec56.png)
This would be way too op

**Comment by DeltaNedas** [comment]
bruh just use phase router
if your map is just a 3 tall ribbon then dont play on it

**Comment by the-kido** [comment]
yeah, I was expecting horribly good things like that. Was curious how the community would feel about something like this tho
c l o s e d
