### ISSUE TITLE
Option to make friendly units transparent

### ISSUE THREAD

**Issue by SarisWinterwisp** [Anuken/Mindustry-Suggestions#873]
**Describe the content or mechanics you are proposing.**

An option in the menu that would allow you to make your friendly units (and perhaps enemy units) see through. Maybe a hotkey to quickly toggle it on and off. Perhaps an aura around your mouse or finger location that makes them transparent around it so you can focus on what you're building.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It can be frustrating to build units and have them follow you and then have them completely obscure anything you might be trying to do. In these two examples you can clearly tell you can't see anything. In the second there's 18 large solar panels that you can't see. (These examples are from v5 but it still applies even more so in v6 since units that follow are larger and more common.)
![image](https://user-images.githubusercontent.com/73077434/96824750-6f8e4c80-13e4-11eb-94ea-79aec411dc41.png) 
![image](https://user-images.githubusercontent.com/73077434/96824763-74eb9700-13e4-11eb-8399-ea20421490c8.png)
This relatively small Q.O.L. improvement would be immensely useful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DS-3K** [comment]
Amazing!
I love the idea of the cursor aura when building,
Because then it wont be annoying outside of its use case :3

**Comment by Quezler** [comment]
_brace yourselves, shadows are coming._ ❄️

**Comment by SarisWinterwisp** [comment]
It's actually quite a bit worse in v6. Toxopids aren't really fun to try and deal with either
![Scared](https://user-images.githubusercontent.com/73077434/97641591-7af30080-1a00-11eb-8ae1-be3d0cbcd06f.png)
