### ISSUE TITLE
[Editor] Prevent "Terrain" filter from overwriting existing /terrain/tiles/blocks

### ISSUE THREAD

**Issue by Bedsurfer** [Anuken/Mindustry-Suggestions#874]
**Describe what you would like changed, and why.**

When using the "Terrain" tool in the editor, clicking "Apply" erases all previous terrain & tiles. I'd suggest that it leaves any previously placed tiles/terrain/blocks down. I feel as if it would make using the tool easier to use/create the map you want. If users wanted to overwrite everything, they would just erase everything. It would also prevent accidents where people who don't know how the tool works accidentally erase massive portions of their project. It would also help in the creation of proceduraly generated maps without the use of external tools. And to be honest, I don't see a real use of it clearing everything besides a pseudo "clear all" button.

**Describe the changes you want to propose. Include possible alternatives.**

- Using the "Terrain" tool no longer clears previously placed blocks/terrain/tiles
- Consider adding a "clear everything" button, If a tool to start from scratch is even needed.

**Comment by 50275** [comment]
> Consider adding a "clear everything" button
Just make a new map and name it the same thing, overwriting a previous version
