### ISSUE TITLE
bind one unit

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#875]
add "count" option to "uBind". Option.change unit count for bind, (1,2,3,4....999, or "all" or value getted from uRadar)

Using this option players can bind one or more unit, and bind unit variables getted from uRadar

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by TheSlaylord** [comment]
Just use `ubind` for like 12 times to bind 12 units

**Comment by Sluethen** [comment]
it doesnt slaylord? It binds all units of one type, not one unit of one type

**Comment by sample-text-here** [comment]
`ubind` only binds a single unit. The unit can be accessed through `@unit`. The problem is that because logic processors run in "cycles", it `ubinds` a unit, `ucontrols` it, then starts from the beginning binding a different unit, which can cause tons of units being bound.

**Comment by Sluethen** [comment]
Yes, but this suggestion is asking to add a built-in limit to how many units it cycles through.

**Comment by sample-text-here** [comment]
Just bind a unit then add an infinite loop at the end to only bind one. Or use loops

**Comment by Sluethen** [comment]
Thats a workaround that is harder to do then just not having that happen in the first place, hence this suggestion

**Comment by Legomonster33** [comment]
> Thats a workaround that is harder to do then just not having that happen in the first place, hence this suggestion

having what you suggested makes the existing system even more complicated, we have the basics enough to do most things (if there is something you cant do its either already been suggested, denied, or nobody knows about it)
