### ISSUE TITLE
Commanded units should fly with you

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#876]
**Describe what you would like changed, and why.**
basically #778 but with flight 
![image](https://user-images.githubusercontent.com/45698812/96863203-5d7bd080-141b-11eb-9815-b5334421e61f.png)
._.

**Describe the changes you want to propose. Include possible alternatives.**

**Comment by kingb74** [comment]
Its been fixed my man

**Comment by Highfire1** [comment]
yay
