### ISSUE TITLE
New transportation drone

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#877]
**Describe the content or mechanics you are proposing.**
I will like to suggest a mech that will be called the Turg transportation drone. It is a aerial drone. It has a speed of 0.3 which increases to 0.4 when near a power node. It has a capacity of 200 units of energy and 100 items. Moving for 1 second uses 15 units of energy, limiting its range. When it runs out of power, it will explode, releasing the contents of the drone. Transportation drones can pick up items, drop off items and recharge at ports. Transportation drones can pick up and drop off items at cores. Transportation drones will cost 10 silicon and 5 titanium to produce, factories will use 40 power units per second when producing transportation drones, max active units per factory will be 2, factories will cost 30 copper, 60 lead, 40 titanium, 50 graphite and 50 silicon to produce, and production times will be around 15-20 seconds for each drone. Ports will have a 200 item storage capacity, cost 20 copper, 40 lead, 40 titanium and 30 silicon to produce and require 50 power units per second to charge transportation drones.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** 
It will increase the amount of resources that a player can harvest dramatically since the amount of resources that can be transported wouldn't be limited by inconvenient cliffs. Transportation drones will also offer another target that players will have to defend/attack. Transportation drones have no defence, so players will need to use towers and units to defend their supply lines.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by the-kido** [comment]
Cool idea, doesn't seem too outlandish. I would like to know how different this would be from a mass driver and how useful it would be to most players. Also, I think it should use a bit more energy and hold a bit more energy too.

**Comment by Bohaska** [comment]
Maybe 250 units of energy and 20 units usage will be better. This drone is available earlier than a mass driver due to the lower material costs, and wouldn't need as much power and be easier to expand. However, mass drivers are usually more suitable for transportation, so when players reach that stage they might rely on transportation drones less. Good points raised.

**Comment by Xeloboyo** [comment]
isnt this covered by unit logic in v6?

**Comment by Sluethen** [comment]
Yeah, and since units that attack can also carry items it'd be better just to use logic to configure it

**Comment by Bohaska** [comment]
Unit logic? Sorry, but I use the latest stable version, not the beta, so I didn't know that newer versions have unit logic. Can you explain what unit logic is?

**Comment by Bohaska** [comment]
I will close this thread soon

**Comment by 50275** [comment]
So if I get about 100 thorium, I can get a mass driver that doesn't explode?

**Comment by Xeloboyo** [comment]
Unit logic allows you override the unit's ai for other purposes, like delivering items, attacking specific things in specific ways, or building things automatically.
Cost-wise for the purpose of logistics, it takes only silicon lead and copper (as opposed to lead titanium thorium and silicon) to set up a flare(wraith fighter in v5) delivery system that can deliver to any container in the map, which comes with its obvious advantages of being extremely compact and infinite range, and disadvantages since its serviced by units and has low throughput with long distances and few units.

**Comment by Bohaska** [comment]
thanks.
