### ISSUE TITLE
Starting and capturing New Sectors

### ISSUE THREAD

**Issue by mnewhart** [Anuken/Mindustry-Suggestions#878]
**Describe what you would like changed, and why.**
First, when starting a new sector, especially around Ground Zero, not having enough resources to get a proper base started before the 1st wave comes seems to be an issue. There is not enough time (and resources) to get your setup done to feed the hub and building defense at the same time. We are limited to what we can bring into that sector from another sector. 

**Describe the changes you want to propose. Include possible alternatives.**
I think extending the first wave time to allow for proper defense and economy setup would help.
 
---------------------------------------------
**Describe what you would like changed, and why.**
Second, this compounds with the first issue above. We are limited with 1st wave time to get some defenses setup. In some sectors I went from 1st wave - 1 to 3 enemies to 2nd wave - 10 and up to 20 enemies. Also, by the 4th or 5th wave the enemies in some cases are way over powered compared to what defenses I have the ability to setup. In most cases it is because of limited resources and the time it takes to build something. The other issue with this is having multiple enemy spawn areas in sectors around Ground Zero. I can see late game on harder sectors this being ok but not in sectors around Ground Zero.

**Describe the changes you want to propose. Include possible alternatives.**
You need to balance the waves better both with count and strength. In most cases I can't build enough defense in time to handle the bosses or the shear number of enemies at wave 25 and we have to get to 30 or 40 in some cases. Also, throwing big bosses on these maps at wave 25 is a joke. They just walk through my defenses. I find this annoying since it just took 20 to 40 minutes setting up pretty awesome defense only to have the a big boss walk through it and you lose the sector. It is extremely discouraging and time consuming to try and advance (read next issue as part of this).

---------------------------------------------
**Describe what you would like changed, and why.**
Third, and part of the first issue of limited resources. When you are alerted that Ground Zero is being attacked and you go back to that sector, you can't "bring" better resources to that sector. The waves jumped from 30 to 50 and you had to get to wave 70. The second time it jumped from 70 to 100. How are you supposed defend against higher waves without being able to bring better materials into that sector to upgrade weapons and defense to handle these higher waves?

**Describe the changes you want to propose. Include possible alternatives.**
Capturing a sector should be just that.  Either allow us to use our Global Resources everywhere or get rid of the "Under Attack" feature. Once a sector is captured I don't think you should have to go back and "mess" with it other than maybe increasing how fast you can gather resources. Again without being able to bring better materials, you can't really upgrade the starter sectors that don't have those resources available (better belts, better miners, more power, etc.).

I was reading one players comments, and I agree, that having multiple sectors under attack while you are focused on capturing another sector doesn't make sense. You can't very well leave the one you are on to go fight 20 more waves on an existing map (time it takes to do so) and then go back to capturing the current sector. The time it takes to setup and then having to upgrade and add more defense (if you can, if you have the right resources and research to do so) seems astronomical. I have spent 15+ hours trying to just capture the sectors around Ground Zero only to lose one or two of them. Some in the first three waves. Looking at that big world of sectors, I am getting discouraged to continue playing because I am looking at spending 100's of hours just to get half way around that globe. Instead of being inspired or excited to get to the next sector with my shiny new research and tech, I look at it more like a 40+ minute rinse and repeat per sector and "oh crap" what sector am I going to lose on the way and now I have to go spend another 30 minutes defending one, two, or three that I don't have the resources or tech to defend. I don't mind putting time into new sectors. But having to go back and mess with old ones doesn't make sense.

**Comment by D-player1** [comment]
Use launch pad, and you're supposed to capture all the tech tree maps before capturing numeric sectors

**Comment by Legomonster33** [comment]
> How are you supposed defend against higher waves without being able to bring better materials into that sector to upgrade weapons and defense to handle these higher waves?

that's what launch pads are for, 

> not having enough resources to get a proper base started before the 1st wave comes seems to be an issue

it shouldn't be an issue as on most maps you can ignore the first 3-5 waves (just kill them with your mech or some basic turrets near the drop point)

**Comment by DeltaNedas** [comment]
yeah i think only 1 sector should be under attack at a time, i cant capture new sectors without losing old ones or being autistic and constantly flipping back and forth between them
i left a sector for 2 waves and nearly my entire base was incinerated, next few waves were very peaceful so i doubt a reign gang strolled through unannounced

**Comment by potatoisagender** [comment]
most of the first enemies are just crawlers. use conveyor belts...
