### ISSUE TITLE
Menders should scale depending on how many blocks it heals.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#879]
**Describe the content or mechanics you are proposing.**

Basically, menders should use less or more energy depending on how many tiles it healed in one _wave._ For example if a wave uses 60 power to heal 20 tiles then it would use 3 power to heal 1 tile. So players don't get confused the description for the mender should say the energy it uses per tile. For instance, the big mender uses 90 power. Using pi the big mender can heal 355 tiles (Counting the little pieces left out). I think it's fair for 1 energy per tile because I highly doubt there will be a situation where all 355 tiles are hurt. This would be useful for starter bases because the small menders still use max energy even if healing one tile. This also makes room for a strategy on the opposing team.
 _These are my rough thoughts and I'd like everyone to help polish the idea._

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will give a much better reason to use hit and run units with AoE attacks because menders would need to use more energy than usual rather than it just heal all of the blocks and make the attack seem insignificant. This also means weapons like slag tsunamis can be more useful too. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Actually, phase increases mender speed and significantly increases mender range for mend projectors, making it much better than normal ones.
Also, this makes small walls even worse. Not only would they heal slower than large walls, they would also *cost* more than large walls to heal.
If you're concerned about power, Anuke added logic parts. You can disable the menders and have them stop using power.

**Comment by itcannotbe** [comment]
If you concerned about 2x2 being than 1x1 walls better under this suggestion then why not just base it per tile then?

**Comment by the-kido** [comment]
1. i forgot about the speed thing thanks for that
2. this system is per tile
3. i am not concerned about power but i am interested in how this can play out in PVP. absorbing enemy energy can be a useful technique 
4. Slags don't do damage but they burn. Ripples do damage but not consistent damage. Im considering the opportunities to waste enemy energy.

**Comment by the-kido** [comment]
> If you're concerned about 2x2 being than 1x1 walls better under this suggestion then why not just base it per tile then vs per block

Sorry, whenever i mention the word block I meant tile. Changing now

**Comment by itcannotbe** [comment]
Alternate Mechanic:
Power Consumed = Summation of all blocks in heal range (Heal Rate * Max HP* Power Conversion Factor)

**Comment by the-kido** [comment]
> Alternate Mechanic:
> Power Consumed = Summation of all blocks in heal range (Heal Rate * Max HP* Power Conversion Factor)

I'm sorry but can you elaborate a bit? What you said doesn't click for me

**Comment by 50275** [comment]
I think it means
For each block in the mender's range, it will consume (Heal Rate of mender * Max HP of block to heal * Preset Multiplier so that things like thorium walls don't take more than 3200 power to heal)

**Comment by the-kido** [comment]
ah okay

**Comment by the-kido** [comment]
Anuke prob saw this and doesnt like it so bye
