### ISSUE TITLE
Actual Logic If-loops

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry-Suggestions#880]
**Describe the content or mechanics you are proposing.**
At the moment we just have a Jump feature, that kind of overcomplicates stuff, and makes it expecially difficult for newbies like me, to understand how to make if loops.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It makes it easiert for newbies to make stuff.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
whats the difference between
`if addr condition`
and
`jump addr condition`

**Comment by UltraBlackLinux** [comment]
jump seems to only go back to some code, if only runs code if the condition is met

**Comment by UltraBlackLinux** [comment]
Bruh: #710

**Comment by DeltaNedas** [comment]
that code is awful
just use op and control

**Comment by UltraBlackLinux** [comment]
What do you think? I am quite a newbie here. I dont even get anywhere bc I have to If loops.
Using true/false doesn't work on other stuff than doors, as far as I tried.

**Comment by Highfire1** [comment]
![image](https://user-images.githubusercontent.com/45698812/96916200-1661ff80-145c-11eb-8915-56b7c32f4efb.png)
what he means is using booleans (which tbf is NOT intuitive) 

- if getfluid > 0, it will return 1, if getfluid not > 0, it will return 0

**Comment by DeltaNedas** [comment]
how is that not intuitive

**Comment by Legomonster33** [comment]
if that's not intuitive for you, you should probably read the manual, or just realize that your not the type of person to be good at logic (which is completely fine (you could also go out of your way to learn))
