### ISSUE TITLE
Random Ore Generation with Fixed Placement "Blank Ore"

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#881]
**Describe the content or mechanics you are proposing.**
Random Ore Generation with Fixed Placement

Allow map creators to place Blank Ore tiles. If left as normal, they would vanish - they are effectively used as a template.
Map makers would be given a (Blank Ore Generation Select?) setting which would allow them to set a chance for blank ore tiles to become a different ore. For example: 
![image](https://user-images.githubusercontent.com/68676339/96910257-364def00-146d-11eb-9bb8-5e55a3db3187.png)
Pretending Pebbles were Blank Ore tiles, I would be able to set a chance for these ores to become copper, lead, coal, titanium, thorium or scrap depending on my map generation settings. All the connected ores on Dirt tiles would always be the same as each other; however, the Mud tiles might have a different ore than the dirt tiles.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Random ore generation will be more viable for map creators. (This is not my image, but it is a good example of why random ore gen has issues)
![image](https://user-images.githubusercontent.com/68676339/96916887-2c7cb980-1476-11eb-9e55-39c254940927.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I've run into this problem as well, but the idea of having special hidden overlay blocks created solely for the ore generation filter doesn't appeal to me. I went for a slightly different  approach: Simply allowing ore generation to specify the floor or overlay that they will generate onto, like some other filters do. 

This has two potential applications:
- Marking areas for ore generation by using a different floor.
- Marking areas for specific ore generation by using an *overlay* (like your example, but with actual pebbles), then wiping any leftover overlay with the `Clear` filter set to the target overlay. This is somewhat of a roundabout method, but it's more powerful and doesn't require adding any special blocks.

**Comment by 50275** [comment]
Beta Build 109
I am unable to clear pebbles using the clear tool, 
![image](https://user-images.githubusercontent.com/68676339/96950310-fceea100-14b7-11eb-942c-06d2d3e6aeb4.png)

Scatter only allows me to place pebbles, but not replace them with something else
Blend allows me to interact with pebbles, but only to make them larger

**Comment by Anuken** [comment]
> Beta Build 109

Of course you can't do any of the stuff I mentioned in 109, the features I'm talking about are not in that version. I can't retroactively add stuff to a build I already released.
