### ISSUE TITLE
Air support unit on campaign

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#882]
**Describe the content or mechanics you are proposing.**
Limit poly and mega based on enemy core

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
No more poly spam in campaign

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Do you mean limit player team poly drones based on the enemy core count, or limit enemy team poly drones based on the enemy team core count?

**Comment by MasterOktagon** [comment]
You can say for yourself that you dont want more than lets say 21 polys. its easy.
