### ISSUE TITLE
nerf poly into the ground

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#883]
**Describe what you would like changed, and why.**

![bad](https://user-images.githubusercontent.com/39013340/96929080-176d4e00-14a9-11eb-9b6a-d52baacefdcd.jpg)
bullshit
bullshit
bullshit
fucking hate these little pricks so much
there is no enemy core, and the sector has no occupation there shouldn't be so many of the bastards spawning

**Describe the changes you want to propose. Include possible alternatives.**

1. Limit to 1-3 per core
2. Remove entirely from survival sectors (good)

**Comment by 50275** [comment]
They only have a build speed of 50% though

**Comment by potatoisagender** [comment]
![image](https://user-images.githubusercontent.com/63363206/96947766-3ec01d00-14a1-11eb-9401-9bc4a19da2db.png)
hmmmmmmmmmmmmm 

> They only have a build speed of 50% **and are the only way to automatically replace broken buildings**

yeah.... have you heard of enemy building?

**Comment by l-Luna** [comment]
the enemy should build on *attack* maps. that makes sense. they shouldn't build on survival maps with zero resources.

**Comment by sample-text-here** [comment]
I think the problem is that there are too many of them spawning.
