### ISSUE TITLE
Anti cheat

### ISSUE THREAD

**Issue by RandomTNT** [Anuken/Mindustry-Suggestions#884]
**Describe the content or mechanics you are proposing.**

Built-in Anti-Cheat (AAC - Anuken Anti-Cheat)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Wiil protect the game from cheaters, kick them from games immediately when the process is enabled.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
Yes

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
1. what cheats
2. plugins
3. how will you detect these cheats

**Comment by markozajc** [comment]
I wish you good luck implementing a clientside (I assume this is what you're suggesting) anticheat on an opensource and very moddable game

**Comment by markozajc** [comment]
aac is an audio codec

**Comment by scarf-generic** [comment]
Yeah its that easy, just give it a fun name and tada, you got a working anticheat

**Comment by markozajc** [comment]
drm couldn't be easier! try now!

**Comment by genNAowl** [comment]
I think this suggestion would be better titled: "Name Suggestion for an Automatic Anti-Cheat Program ~~that will probably never exist!~~"

**Comment by Legomonster33** [comment]
> I wish you good luck implementing a clientside (I assume this is what you're suggesting) anticheat on an opensource and very moddable game

I feel like it would need to be server side, (and could be a plugin)

**Comment by markozajc** [comment]
if it's a plugin then don't make a suggestion on upstream mindustry

**Comment by Cpppppppppplus** [comment]
"anit-cheat" is incorrect and inefficient. The correct way to do this is to just calculate everything server-side to begin with, and just reject absurd client requests. An easy way to do this would be to make the server only accept key presses, and mouse-presses as data.

**Comment by markozajc** [comment]
1) that's just stupid
2) good luck playing a game on speeds less than 5 gbps
3) keylogger server

**Comment by Cpppppppppplus** [comment]
1. Stupid how exactly? My suggestion is superior in every way to "anti-cheat".
2. 5gpbs? My suggestion would result in less bytes being set across the network.
3. keylogger? Windows only have access to button clicks when they have the focus, so this would not be keylogging. Google Forms also knows what keys you click (it's called "typing"). Are you going online text programs keyloggers too?

**Comment by markozajc** [comment]
it appears that you don't know exactly how optimizing an online game works. your implementation would face the exact same issues that nvidia's online render offload sink did - any latency would cause severe lag and possibly stuttering, since I assume you'd also take any client side predictions out. sending occasional movement events uses up less of your bandwidth than sending the entire heap of key and mouse events. the problem mindustry is facing that the server doesn't validate the movement packages, and implementing such verification (preferably through a plugin) would be the proper solution here. neither does your solution make sense from a trust perspective. I don't exactly see what you were on about with google forms, but in this scenario you trust your client, but not necessarily the server, sending more information than the server even needs would be very silly and possibly hazardous.
please, do not even argue such silly ideas. it would put more strain on the servers and allow them to collect a lot more information than they need to operate. it's not how anticheat systems work, and it never will be because it's a silly idea.

**Comment by itcannotbe** [comment]
> 
>     1. Stupid how exactly? My suggestion is superior in every way to "anti-cheat".

It is stupid. No questions asked.

>     2. 5gpbs? My suggestion would result in less bytes being set across the network.

Every movement is a packet is a unnecessary. It goes against bandwith optimization and computers resource considerations

>     3. keylogger? Windows only have access to button clicks when they have the focus, so this would not be keylogging. Google Forms also knows what keys you click. Are you saying that all online text programs are keyloggers?

If you put it that way, the it totally is. Duh.

**Comment by DeltaNedas** [comment]
>scared of google forms being a keylogger (it is)
>use michaelsoft binbows

**Comment by markozajc** [comment]
send inking (???) and typing data to improve your microsoft r windows tm experience

**Comment by Cpppppppppplus** [comment]
@markozajc I never said that the data would be sent every frame (and even if that were the case, it would still take less internet bandwith, because the keys would just be a byte each, and the mouse data a pair of ints or floats, whereas the anti-cheat and probably the current server implementation requires sending update packets with larger data). I also never said that the raw events would be sent. You can merge arrow-key combinations into single values (in custom enums), and of course, it should be implied that these are only changed when the velocity changes. A byte (custom input-enum) is smaller than whatever movement data that would have been set. 

We can even ignore the idea of sending keys, because that was not my main point. My main point is that the server calculates what happens whenever data is sent, instead of trusting the client, and then doing some kind of inaccurate mitigation later to avoid the largest types of hacks (while allowing many smaller ones to occur). The "ani-cheat" approach is the reason developers have to keep "updating" their server software for "vulnerabilities" (just imperfect server implementations that trust the client and prevent only a few illegal actions here and there from occurring).

**Comment by Cpppppppppplus** [comment]
@itcannotbe ^

**Comment by markozajc** [comment]
guy is still trying
why don't you spend your time instead by spamming the fuckers over at github who took down youtube-dl

**Comment by markozajc** [comment]
yes, that's pretty hot matter right now, and it's not looking pretty

**Comment by Cpppppppppplus** [comment]
@markozajc WHy don't you actually learn how to program you imbecile?

**Comment by markozajc** [comment]
might wanna check out my repositories before throwing accusations around

**Comment by Cpppppppppplus** [comment]
@markozajc Or at least read what I posted.

**Comment by Cpppppppppplus** [comment]
@markozajc All I see are scripting languages...

**Comment by markozajc** [comment]
you're arguing about some shitty anticheat implementation while github is actively killing foss

**Comment by Cpppppppppplus** [comment]
@markozajc Ever used a system call in your life?

**Comment by DeltaNedas** [comment]
man 2 exit

ok so he can kode, but its javascript, but its java not c, but its not x86 asm, but its not manually poking the transistors
stop being autistic and stay half on topic

**Comment by markozajc** [comment]
java the scripting language

**Comment by markozajc** [comment]
how about you maybe check out how 99% of server side anticheat implementations that aren't broken experimental shits work

**Comment by markozajc** [comment]
thanks to our sponsor live github refresh you can now have im conversations in github issue threads

**Comment by DeltaNedas** [comment]
waiting for op to respond to my 3 questions

**Comment by markozajc** [comment]
yes I somehow doubt you'll await that

**Comment by Bohaska** [comment]
I feel like this is going off topic...

**Comment by sample-text-here** [comment]
> WHy don't you actually learn how to program you imbecile?

**Cpppppppppplus doesn’t have any public repositories yet.**

**Comment by markozajc** [comment]
no no I'm sure they're a master pro koder in vs kode and he can write hello world in cpp plus because after all that's their name right

**Comment by Cpppppppppplus** [comment]
@sample-text-here Because it's not like this account was just made for a single Mindustry issue. Plenty of people don't post code on Github anyways.

**Comment by Cpppppppppplus** [comment]
@markozajc And yes, I am a master coder. If you want to argue about any meaningful programming topic, let's go ahead and argue, so that I can show anyone reading this post what an idiot you are.

**Comment by itcannotbe** [comment]
> @sample-text-here Because it's not like this account was just made for a single Mindustry issue. Plenty of people don't post code one Github anyways.
I think creating this account only in september kinda refutes your claim of not making this account just for mindustry.

**Comment by Cpppppppppplus** [comment]
@itcannotbe Yes, this account is just for Mindustry. That's what I said above.

**Comment by ritzip** [comment]
> idiot
java the scripting language

**Comment by ritzip** [comment]
There really is no need for anticheat in a moddable game though. If you are talking about servers, most of calculations are done serverside already.

**Comment by markozajc** [comment]
master pro koder creates a new account to shitpost on suggestions threads ((exp0sed))

**Comment by markozajc** [comment]
@ritzip precisely. I feel like the proper solution here would be adding a bit more verification to the movement packages (since you can pretty much teleport nowadays from what I've heard, unless this has been already patched). adding clientside anticheat to an opensource game is as futile as it gets

**Comment by itcannotbe** [comment]
Actually there already a function that check valid movement packets server side on the last version but it disregards the unit type.

**Comment by ritzip** [comment]
@markozajc Abnormal movement can stopped with strict mode, It depends on the host whether they enable it or not. Strict mode also stops custom builds (unless compiled with `-Pbuildversion=buildnumber`)

**Comment by markozajc** [comment]
oh, gotcha. there's a problem with blocking custom builds like that, though, since fdroid builds are marked as unofficial from what I know

**Comment by itcannotbe** [comment]
Maybe plugins can be an alternative for detecting illegal movements

**Comment by DeltaNedas** [comment]
fdroid is still marked as official, otherwise you couldnt join servers with it

**Comment by markozajc** [comment]
ok so it isn't regarded as a custom build even though it says custom build?

**Comment by DeltaNedas** [comment]
play with Version in the console and see

**Comment by markozajc** [comment]
h

**Comment by sample-text-here** [comment]
what's wrong with `strict movement`?

**Comment by ActualWina** [comment]
The game is open source you cant just make a normal anticheat.

**Comment by markozajc** [comment]
yes

**Comment by RandomTNT** [comment]
> it appears that you don't know exactly how optimizing an online game works. your implementation would face the exact same issues that nvidia's online render offload sink did - any latency would cause severe lag and possibly stuttering, since I assume you'd also take any client side predictions out. sending occasional movement events uses up less of your bandwidth than sending the entire heap of key and mouse events. the problem mindustry is facing that the server doesn't validate the movement packages, and implementing such verification (preferably through a plugin) would be the proper solution here. neither does your solution make sense from a trust perspective. I don't exactly see what you were on about with google forms, but in this scenario you trust your client, but not necessarily the server, sending more information than the server even needs would be very silly and possibly hazardous.
> please, do not even argue such silly ideas. it would put more strain on the servers and allow them to collect a lot more information than they need to operate. it's not how anticheat systems work, and it never will be because it's a silly idea.

Dumb, yes.

**Comment by markozajc** [comment]
@RandomTNT please address @DeltaNedas's questions

**Comment by markozajc** [comment]
oh wait you closed it nevermind

**Comment by markozajc** [comment]
live github refresh

**Comment by Anuken** [comment]
@markozajc
> the problem mindustry is facing that the server doesn't validate the movement packages

This is false. I suspect the rumor may have started after I *intentionally disabled strict movement* on my sandbox server and started teleporting around, after which everyone discovered that they could do the same by installing dev-mode changing unit speeds in their console.

In the latest beta build, at least, it's not possible unless you explicitly disable it on your server. Try setting your speed to 100 and see what movement looks like.

**Comment by markozajc** [comment]
@Anuken blame @DeltaNedas

**Comment by DeltaNedas** [comment]
op just said "bad yes" instead of answering my 3 short questions h

**Comment by markozajc** [comment]
1. mindustri.ru free hakc client [MOD APK] ulimiited resourc speed 10 mach
2. plugins
3. if useragent equals mindeustry ru hack client then ban fi
you're welcome

**Comment by GitHubUser-B** [comment]
> @markozajc
> 
> > the problem mindustry is facing that the server doesn't validate the movement packages
> 
> This is false. I suspect the rumor may have started after I _intentionally disabled strict movement_ on my sandbox server and started teleporting around, after which everyone discovered that they could do the same by installing dev-mode changing unit speeds in their console.
> 
> In the latest beta build, at least, it's not possible unless you explicitly disable it on your server. Try setting your speed to 100 and see what movement looks like.

I'm your fan!

**Comment by markozajc** [comment]
pov: necroposting

**Comment by GitHubUser-B** [comment]
> pov: necroposting

What is this?

**Comment by Legomonster33** [comment]
> > pov: necroposting
> 
> What is this?

necroposting is commenting on a thread that has been inactive for a while

**Comment by itcannotbe** [comment]
> > > pov: necroposting
> > 
> > 
> > What is this?
> 
> necroposting is commenting on a thread that has been inactive for a while

You realize that's what you actually did this time.

**Comment by GitHubUser-B** [comment]
> > > pov: necroposting
> > 
> > 
> > What is this?
> 
> necroposting is commenting on a thread that has been inactive for a while

What's the problem with that? Does it reset the time for the bot to close the thread?

**Comment by markozajc** [comment]
yes, and it spams approximately 12 users' email inboxes by default

**Comment by jgminer1501** [comment]
@markozajc holy shit bro, this threat is way too funny #necroposting

**Comment by deltanedas** [comment]
mmmmmmmmmmmrajc

**Comment by jp-x-g** [comment]
> > > > pov: necroposting
> > > 
> > > 
> > > What is this?
> > 
> > 
> > necroposting is commenting on a thread that has been inactive for a while
> 
> You realize that's what you actually did this time.

Necroposting is the WORST!

**Comment by RandomTNT** [comment]
necroposting continue

**Comment by RandomTNT** [comment]
i dont even remember posting this
