### ISSUE TITLE
Core Immunity against Container/Vault Explosions, and Fires

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#885]
**Describe what you would like changed, and why.**
Make cores completely immune from taking damage from surrounding containers and vaults

**Describe the changes you want to propose. Include possible alternatives.**
It's incredibly annoying when a ~300 HP container or vault gets destroyed and instantly destroys your core, no matter how much health it has, or when your core eternally catches fire from coal that you had to store for researches in campaign.

**Comment by Legomonster33** [comment]
rip format

**Comment by D-player1** [comment]
Seems like there's another PvP victim

**Comment by 50275** [comment]
I've only experienced it once (to my core) in V5, but it's a lot worse in V6.

**Comment by BlueWolf3682** [comment]
waves and tsunamis, menders and megas: allow us to introduce ourselves

**Comment by GrandTeki** [comment]
> waves and tsunamis, menders and megas: allow us to introduce ourselves

You need like 3 fully supplied Waves in v6 to extinguish a T2 core. Fire was buffed in v6, and there's so little you can do against it now.
At least oil fields do not catch on fire now...

**Comment by 50275** [comment]
The core with certain resources is much more flammable than you think
It's completely impractical to try to put it out with water

**Comment by 50275** [comment]
Forget about it, there's options to disable building explosions and fires
