### ISSUE TITLE
AI enemy poly

### ISSUE THREAD

**Issue by Quick-korkc** [Anuken/Mindustry-Suggestions#886]
**Describe what you would like changed, and why.**
make the ai enemy poly had building cooldown

**Describe the changes you want to propose. Include possible alternatives.**
they built random building which can overhelmed player, especially new player, so building cooldown can make them easier to cleaned, also more difficult sector, the cooldown more less

**Comment by Bohaska** [comment]
Try improving your grammar first.

**Comment by l-Luna** [comment]
"Make enemy poly drones have a cooldown after building. They constantly build random buildings that can overwhelm players, especially new ones. The cooldown should be lower on more difficult sectors."
