### ISSUE TITLE
Kamikaze aerial drones

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#888]
**Describe the content or mechanics you are proposing.**
Kamikaze aerial drones will have the same speed as a wraith fighter in v5 and be stuffed with four times the explosive power of a crawler and 100 health. Kamikaze drones rush towards their target, self-destructing when they reach the target. They will cost 3 thorium, 3 plastanium and 10 silicon to produce in a kamikaze drone facility. Kamikaze drones factories will cost 10 thorium, 10 plastanium, 30 silicon and 20 titanium to produce. Factories will have 400 health. Production times will be 10 seconds. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Aerial battles will be more common, since kamikaze aircraft do tons of damage. It will also cause players to bolster up their aerial defence systems so they can defend against kamikaze attacks. Players may send kamikaze attacks before sending their army and task the kamikaze drones to attack conveyor belts so that towers will run out of ammo.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Anuke isn't planning on adding any more units; the game has reached the beta stage already.

**Comment by Luxray5474** [comment]
You can do this using Flares and Logic. Flares are very fast and you can control them to bomb enemies by carrying pyratite, blast compound, or coal to them.

**Comment by Bohaska** [comment]
Thanks for the comments. I will be closing this suggestion.
