### ISSUE TITLE
Code block editor

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#889]
**Describe the content or mechanics you are proposing.**
Custom block code mechanic

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

You will be able to create your own code blocks with unique capabilities (custom code blocks will be created from those added by Anuke), and the user block will display the number of instructions needed to execute all the block code.  If you copy the code from the processor, it will look something like this:
CustomCB Open
id: func
input: 
area int x 50 50 20 20, text "+", area int y 50 50 20 20
code: 
op add z x y
jump .output 1 greaterThan z 2
output: 
jump
CustomCB Close

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Basically schematics

**Comment by hshsxhsb** [comment]
> Basically schematics

what?

**Comment by DeltaNedas** [comment]
op add retaddr @counter 2
jump .func always

...

set @counter retaddr

**Comment by hshsxhsb** [comment]
> op add retaddr @counter 2
> jump .func always
> 
> ...
> 
> set @counter retaddr

what it is?

**Comment by DeltaNedas** [comment]
how to do functions

**Comment by sample-text-here** [comment]
functions are already possible but something like this or #838 would be nice
