### ISSUE TITLE
Moving areas in map editor

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#890]
**Describe the content or mechanics you are proposing.**

- select an area in a map
- drag to move it
- copy and paste-able

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

- move large areas when you resize a map
- copy and paste buildings or selections of terrain
- rotate terrain
- not be sad when you have to move everything when the map is a few tiles too short so you click resize but everything is centered and you want a specific part of the terrain to be at the bottom of the map so you have to recreate everything by hand but a few tiles lower and it takes a long time and your hand gets sore and it’s really boring and you get mad so you write a passive-aggressive suggestion to mindustry-suggestions
- makes it easier to edit maps
- #339 and #259 
- oh
- i already wrote this so I’ll claim i’m bumping the suggestions or whatever

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
I’m bumping the other map schematic suggestions because it’s been a while since they were posted and because there’s discord integration now

**Comment by RedstonerKBC** [comment]
Anuke please tell me you plan on adding this. Every map editor has to have some sort of selection tool that lets you copy/cut areas and paste them to a different area.

**Comment by RedstonerKBC** [comment]
I noticed this and related issues are still open. They still plan on doing this, right? Please, it takes days just to hand-paint a single map with certain custom designs.
