### ISSUE TITLE
Automatic update on Windows

### ISSUE THREAD

**Issue by Sky-NiniKo** [Anuken/Mindustry-Suggestions#891]
**Describe the content or mechanics you are proposing.**
Could you add a viable solution allowing automatic update on Windows ?

- Either by an in-game button e.g.: “Search for updates” and “Automatically search for updates (at each startup)”.
- Or by using a platform like [chocolatey](https://chocolatey.org/).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Phones, iOS and Linux already have viable solutions for automatic updates. However, Windows does not. This is why it seems normal to me that this option exists. But if this feature is too complicated to be implemented, I can understand why it is refused.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Kubek0212** [comment]
For windows you can use steam.
As of free solution, you can try downloading itchio and try automatic update from that platform.

**Comment by itcannotbe** [comment]
The itch.io updater already exist for this.

**Comment by DeltaNedas** [comment]
steam itch.io and be updater do this
if he packages for choco, he may as well package for debian main

**Comment by Sky-NiniKo** [comment]
Thank you for your answers, I didn't know itch.io could do it.
