### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by alextheOMFG** [Anuken/Mindustry-Suggestions#892]
**Describe the content or mechanics you are proposing.**
Mending objects by hand without menders or drones

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
What i think is very annoying is that every time i play the game the enemies will destroy the walls so can you please do something about it not like i can place menders everywhere
especially when no power sources are nearby its very frustrating to find a way to link all the way to the mender and just for one or two menders
(*im also in early stages of the game*)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DayTimer** [comment]
Use poly, mega or quad. All of them can heal blocks. But you defence MUST have some menders (else enemies will destroy it)

**Comment by QmelZ** [comment]
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
doubt it.

**Comment by 50275** [comment]
If you play mindustry you will need to drag power nodes everywhere

**Comment by Bohaska** [comment]
I know it is frustrating to link everything together using power nodes when you don't have thorium, but that is how Mindustry was designed, and if you don't like that feature, then maybe Mindustry is not the game for you.

**Comment by QmelZ** [comment]
> I know it is frustrating to link everything together using power nodes when you don't have thorium

what does it have to do with thorium?

**Comment by l-Luna** [comment]
just rebuild things - mending is *supposed* to require some infrastructure.

**Comment by Bohaska** [comment]
> > I know it is frustrating to link everything together using power nodes when you don't have thorium
> 
> what does it have to do with thorium?

You will have better nodes by then.

**Comment by QmelZ** [comment]
> > > I know it is frustrating to link everything together using power nodes when you don't have thorium
> > 
> > 
> > what does it have to do with thorium?
> 
> You will have better nodes by then.

i asked the reason you mentioned thorium in the first place, its unrelated
