### ISSUE TITLE
[Logic]Code cell, code bank, and 3 code blocks

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#893]
**Describe the content or mechanics you are proposing.**

**new blocks:** code cell, code bank
**new code blocks:** Cwrite, Cadd, Cread
**new mechanics:** saving the required code to the code cell / bank with the Cwrite command.  Getting code from code cell / bank and executing it.  Adding code to code cell / bank with the Cadd command.
**main characteristics of blocks:** code cell: 4 cells with the ability to store 128 lines of code each
code bank: 32 cells with the ability to store 128 lines of code each

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

the ability to leave only the settings in the processors.  Ability to easily use a single processor for multiple areas.  Dynamic code reconstruction without player intervention.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
what we need is a compile instruction
`compile "set egg 1" addr`
`set @counter addr`

**Comment by hshsxhsb** [comment]
> what we need is a compile instruction
> `compile "set egg 1" addr`
> `set @counter addr`

explain to me what is it and what do you want?

**Comment by DeltaNedas** [comment]
compiles code at the end of the processor and sets addr to the address

**Comment by hshsxhsb** [comment]
> compiles code at the end of the processor and sets addr to the address

if you need it, what do you do under my suggestion

**Comment by Cpppppppppplus** [comment]
@DeltaNedas A "compile" keyword wouldn't make sense for this. Either you compile code beforehand, or a JIT (why do JIT language even exist?) automatically selects the best portions to compile to begin with. What hshsxhsb wants can be done with arrays of opcodes.
