### ISSUE TITLE
[Logic]processor extension cord

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#894]
**Describe the content or mechanics you are proposing.**

if you connect the processor to one or more extension cords, then when you select this processor will also be allocated and the impellers can thus connect the processor to the blocks remote from its area.  Multiple processors can be connected to one extension cord.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

With this unit you do not have to try to fit everything in the reach of the processor.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Duplicate of #684
