### ISSUE TITLE
Thorium Fuse

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#895]
**Describe the content or mechanics you are proposing.**
Make Thorium Fuse shoots pink lasers

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
PiNk LaZeRs Is GoOd

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
yes

**Comment by the-kido** [comment]
Yes but no more ammo for the fuse. 3 is enough and thorium is a good choice.

**Comment by Bohaska** [comment]
This is pretty minor. Anuke should probably not waste his time on this, but if anyone will make a pull request for this then Anuke probably will accept it.

**Comment by braainsiogame** [comment]
> This is pretty minor. Anuke should probably not waste his time on this, but if anyone will make a pull request for this then Anuke probably will accept it.

👀

**Comment by l-Luna** [comment]
implemented in 7e323f1ebf379729c9428771639c31ab47aadb68.
