### ISSUE TITLE
The Foreshadow should be able to use titanium

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#896]
**Describe what you would like changed, and why.**
Surge alloy is a weird and hard to make material. I suggest that titanium be a substitute for surge alloy. It would have its side affects via damage and perhaps rate of fire, but would be a nice thing.

**Describe the changes you want to propose. Include possible alternatives.**

Perhaps a earlier version of the foreshadow only costing titanium and silicon that would fire titanium. It could be 2x2 and would be much worse but still good.

**Comment by DeltaNedas** [comment]
why not copper or sand foreshadow?

**Comment by genNAowl** [comment]
Yeah if you give foreshadow any ammo besides surge, surge will never be used.

**Comment by l-Luna** [comment]
> Surge alloy is a weird and hard to make material
that's the point.

**Comment by Slava0135** [comment]
High-tier materials for a high-tier turret. No reason to add an another ammo type.

**Comment by BlueWolf3682** [comment]
its a railgun, billy. it likes magnetic stuff.
