### ISSUE TITLE
Repair points should use phase to make it stronger and its range longer

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#897]
**Describe the content or mechanics you are proposing.**

The title says it all. Phase Fabric is "A near-weightless substance used in advanced electronics and self-repairing technology." so I thought to make it a bit quirky the repair points should shoot the stuff at the drones in an AoE heal affect. The range for the shots would be farther than the Repair points usual range and although it won't heal the units quicker it makes up for it my healing more than one unit at once. The heal it does per second should be accounted for and using phase should be the same pace as using any old repair point.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This is to stop people from asking for a better repair point because it's basically that - a somewhat better repair point. I think that the shooting the phase thing is a different approach to healing the units and is - to rephrase - quirky.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ritzip** [comment]
It would be better fitting if they used silicon, like menders.

**Comment by Bohaska** [comment]
Why not both? Silicon will improve the effectiveness of repair points and phase fabric will improve the range and amount of units a repair point can heal?

**Comment by itcannotbe** [comment]
I think giving a range buff would be pointless. Just make it stronger or make it able to have multiple beams when boosted.

**Comment by Bohaska** [comment]
> I think giving a range buff would be pointless. Just make it stronger and/or make it able to have multiple beams when boosted.

Umm, you probably didn't read the part in which repair points upgraded with phase fabric would heal more then 1 unit at a time.

**Comment by itcannotbe** [comment]
I read that and I am just disagreeing with the range buff.

**Comment by l-Luna** [comment]
I think sillicon would be more appropriate - repair points are more in-line with menders than mend projectors. as-is, a range boost is kind of necessary given that units don't try to get to repair points and often sit just outside of its radius. if units actually tried to go to repair points when damaged, it would be much less necessary.

**Comment by the-kido** [comment]
> I think sillicon would be more appropriate - repair points are more in-line with menders than mend projectors. as-is, a range boost is kind of necessary given that units don't try to get to repair points and often sit just outside of its radius. if units actually tried to go to repair points when damaged, it would be much less necessary.

I thought using phase makes sense as per its lore and it would also look nice as a bonus. it doesn't make too much sense to lob silicon around to heal units. Phase, after all, is "used in self-repairing technology". That's my two cents.
