### ISSUE TITLE
Split Enemy Spawn

### ISSUE THREAD

**Issue by Humanoid-X** [Anuken/Mindustry-Suggestions#898]
**Describe the content or mechanics you are proposing.**
The enemy spawn can spawn Ground, Air and Naval.
I think that Anuke must split it into three tile:
1.Ground Enemy Spawn
2.Air Enemy Spawn
3.Naval Enemy Spawn
The ground spawn will be orange, air spawn green, and naval spawn blue.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Sometimes you will want the units to spawn in different location.
Sometimes you will want naval units to spawn in your map. But your want to spawn ground units too.
Then it will either be **Ground units spawning in water** or **Naval units spawning in land**.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
[X to Doubt] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.

#325

**Comment by l-Luna** [comment]
air units already spawn seperate to naval and ground units.

**Comment by Jamtime729** [comment]
Spawners on water will deletus yeetus the land bots,

**Comment by DS-3K** [comment]
Pls respect my suggestion "seperate waves at once" my good copycat frend ;-;

**Comment by Humanoid-X** [comment]
> [X to Doubt] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> #325

Oops

**Comment by Humanoid-X** [comment]
> > [X to Doubt] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> > #325
> 
> Oops

Removed it
