### ISSUE TITLE
Password for socket input of the server.

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry-Suggestions#899]
**Describe the content or mechanics you are proposing.**

What I propose is to add something like a password that will need to be sent when connecting, and you can edit it in the server config.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Right now, in order to connect and control the server through a socket input, we just need to know the socket input port, which is not secure because anyone can just ping each port and hack the server.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Probably not the best place to discuss this.

**Comment by summetdev** [comment]
> Probably not the best place to discuss this.

Why? It's suggestion.

**Comment by itcannotbe** [comment]
Because it's a security issue (sort of)

**Comment by summetdev** [comment]
Well, I'll make a new in original repo.
