### ISSUE TITLE
Team change in pvp

### ISSUE THREAD

**Issue by Polar4ik** [Anuken/Mindustry-Suggestions#900]
when a person enters the pvp server, the team selection window will be displayed when you click on the color, then you become a member of this team

when loading a pvp save, the player can change the team, If there are few people on the server or a lot of people on the same team, then the admin can change the team through the list by the player

**Comment by itcannotbe** [comment]
Let's totally not abuse this if it ever gets implemented.

**Comment by itcannotbe** [comment]
OP forgot to...

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by Bohaska** [comment]
@itcannotbe How could this be abused?

**Comment by genNAowl** [comment]
Switch to the opposite team, grief, come back OR
grief team, switch team, grief new team, leave.

**Comment by Polar4ik** [comment]
> Переключитесь на противоположную команду, горе, вернитесь или
> команда скорби, смени команду, новая команда скорби, уходи.

first this feature will be available at the beginning as soon as you log in to the server
