### ISSUE TITLE
Quality of life autorouter

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#901]
**Describe the content or mechanics you are proposing.**
If you're drawing a conveyor with its starting point on another conveyor, put a router there

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would make it more convenient to make branching conveyors

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by braainsiogame** [comment]
hi ilya

**Comment by QmelZ** [comment]
oh no the real ilya

**Comment by Bohaska** [comment]
What if someone wants to extend the original conveyor?

**Comment by Ilya246** [comment]
of course it will be optional, just like all other such features

**Comment by Ferociousfeind** [comment]
I think that if the input feed of the first conveyor queued to be built is pointing to a block which is a conveyor, which is NOT facing the queued conveyor, then it can replace the perpendicular or opposite-facing conveyor with a router.

But that feels a little complex, and might be surprising and unpleasant to someone just trying to draw parallel conveyors that diverge at the same spot.
