### ISSUE TITLE
(NOT DIRECTLY RELATED TO THE GAME) Register an official website

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#903]
**Describe the content or mechanics you are proposing.**
Mindustry should have its own independent URL. If it does, it will look more professional and official then every function scattered around on itch.io, Github and Trello. (I think mindustry.app is a good url for this game)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Unavailable.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
i dont think anuke wants to directly handle payment or write his own roadmap software and port it from trello

**Comment by Bohaska** [comment]
Maybe this suggestion should wait until Anuke finally officially releases the full game...

**Comment by QmelZ** [comment]
just to remind you, the "full game" is already released

**Comment by ritzip** [comment]
https://mindustrygame.github.io/
