### ISSUE TITLE
essentially mkdir -p created fi's

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#904]
**Describe the content or mechanics you are proposing.**

When writing a Fi, make sure its parent exists.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

`rm -rf crashes` will prevent crash logs from being created as Fi wont try to make the crashes folder first

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
whats a Fi?

**Comment by DeltaNedas** [comment]
`arc.files.Fi`
