### ISSUE TITLE
[Ligic]Unit bind byFlagAndType

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#905]
**Describe the content or mechanics you are proposing.**

Add new option to unit bind - bindByFlagAndType. this opton will bind units by Flag (flag value) and type (unit type (mono, poly, dagger ...)).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will not put a million jump to determine the desired unit for the flag.  It will be easy to intercept the control of the unit with another processor.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
that just needs 1 jump

**Comment by hshsxhsb** [comment]
> that just needs 1 jump

Really, im stupid.
