### ISSUE TITLE
Weak walls (name W.I.P)

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#907]
**Describe the content or mechanics you are proposing.**

These walls should be weaker than copper walls but buildable with 2 copper and 2 lead and is a bit faster than copper walls to build. These walls are super early game and should be replaced by copper walls soon. They are susceptible to fire but and can reflect explosion damage but take more damage from it too. Let me repeat again, these walls should only be used for the first few waves and should have no reason for existing after that.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I find the early game pretty challenging for myself so I can imagine others feel the same way too. Having these should be enough to protect for the start but not for the harder maps. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DarkBrick** [comment]
I think copper is enough for early game, we don't need an another wall type just for the first couple waves

**Comment by itcannotbe** [comment]
Let me guess because op has issues setting up early game defenses that could last long enough.

Or OP can't multitask preparing defenses and mining for resources/crafting other resources.

**Comment by 50275** [comment]
There is no need for a smaller or weaker wall, because at that point you should use conveyors or junctions

**Comment by sample-text-here** [comment]
*builds scrap walls out of scrap*

**Comment by the-kido** [comment]
> Let me guess because op has issues setting up early game defenses that could last long enough.
> 
> Or OP can't multitask preparing defenses and mining for resources/crafting other resources.

Thats probably exactly why lmao. When i first played the new version i found it difficult i guess i should just get gud
