### ISSUE TITLE
Option for turning off endless waves in Campaign

### ISSUE THREAD

**Issue by Retrisma** [Anuken/Mindustry-Suggestions#908]
**Describe what you would like changed, and why.**

The fact that waves continue up to and past wave 100 in Campaign means that it's difficult for players to focus on one map at a time, and it means that players need to constantly rebuild maps like Ground Zero that don't have access to menders. I think that there should be a maximum cap on each area for the number of waves.
**Describe the changes you want to propose. Include possible alternatives.**
- Maximum cap on the number of waves that can appear in each area before it's captured for good.
  - Make the maximum cap editable to be higher or lower (or endless).

love you anuken <3

**Comment by itcannotbe** [comment]
This is kinda stupid as why would you make campaign have that setting when infinite waves are part of an effort to actually eliminate afking strategies that existed in the previous version.

v3 have waves that scaled to a point where you must manually repair structures in the late game.
I don't really know why people are making a fuss out of this change.

**Comment by Retrisma** [comment]
The thing is, the way the campaign was changed makes it feel like you're conquering a planet. Players would clearly strive to hold all of the hexagons on the world map, viewing them as individual levels. Trying to play two levels at once is hard enough, not to mention a dozen or more. It doesn't feel great (especially for new players) to lose a sector just because they didn't have the mental capacity or time to attend to it, and then it feels like it was out of their control and not their fault that they lost it. The established mental model is that areas pause when you aren't directly playing on them, so the idea that your factories can continue accruing resources and enemies can continue attacking your base is difficult to handle. It's hard to make a sustainable base and then leave it to go to another sector if waves keep increasing linearly forever, and the play pattern of continually rebuilding from where you left off is tiring as well. Not saying that the new campaign is bad, and I'm just asking for a setting so that people can play as they want. (If this goes against Anuken's vision for the game, I totally understand why they wouldn't want to include it, but this suggestion would raise accessibility and let players play how they want, either conquering the world one by one or only playing one level at a time and leaving each sector for dead when you're done with it. Maybe the option should be "freeze time when not in a sector" or something so that you can't farm resources with no downside.)

**Comment by itcannotbe** [comment]
Well. The trade of between getting basically free resources from already conquered sectors and the possibility of losing them is a fair actually. Otherwise this game would be one of the many examples of idles games out there.

**Comment by Retrisma** [comment]
Yeah, I like that a lot! Let players decide the level of risk/reward they want to have. Thanks for the feedback!

**Comment by itcannotbe** [comment]
Also the campaign is not exactly playing how ever you want. That's the job of custom games to begin with.

**Comment by Retrisma** [comment]
That one is up to the developers. I'm not going to pretend to know whether Anuken thinks this would be a good idea to implement in the campaign or not. I just thought I'd suggest it because I thought of it while playing.

**Comment by stuffyAI** [comment]
> Maximum cap on the number of waves that can appear in each area before it's captured for good.
> * Make the maximum cap editable to be higher or lower (or endless).

Just capping the amount of sectors that can be simultaneously attacked would be fine, that way you actually get a chance to spread before having to attack red sectors
