### ISSUE TITLE
limit sectors under attack simultaneously

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#909]
**Describe what you would like changed, and why.**

Crux forces should only be able to attack a few sectors at a time, perhaps scaling with the player's ability to defend sectors passively.

The game currently is just half-repairing sectors you left for 2 waves that got torn apart at "6%" damage, while another 2 are attacked.
The damage algorithm is currently horrendous and as such attacks should be more managable.

**Describe the changes you want to propose. Include possible alternatives.**

max sectors under attack = sqrt(number of sectors captured) and some curve for how weak the enemy is, as not to allow the last crux sector to have 10 sectors under attack

**Comment by Retrisma** [comment]
This taps into a similar concern as my previous suggestion. Ultimately I agree that this is a problem and this is a potential solution.

**Comment by itcannotbe** [comment]
#753 is also a suitable alternative.

And yes. The damage algorithm is currently horrendous
