### ISSUE TITLE
Layers on map maker

### ISSUE THREAD

**Issue by Mr-Farenheit141** [Anuken/Mindustry-Suggestions#91]
**Describe the content or mechanics you are proposing.**

In the map editor, have the ability to edit on different layers, I.E. the ground layer (water/sand/mountain/oil/etc), the mineral layer (copper/lead/titanium/scrap/thorium), the mining and production layer, and the turret layer (ability to toggle on and off turret range) . 

Also grant the ability to turn layers off and on as well as opacity so we can see where everything lies without having to delete everything. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Easier and more fun to make maps. Easier to see if something will clog the system/drill in the wrong spot/etc. 

1. - [X ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Locking edits to ground or walls is fine, but I won't be implementing an entire layer system for *everything*. It's a lot of work and I don't see such a system being used often.
