### ISSUE TITLE
Map editor, allow the changing of drill speed of drills

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#910]
**Describe what you would like changed, and why.** what the title said, allows more intresting maps

**Describe the changes you want to propose. Include possible alternatives.** allow a option to change the drill speed the same way you change block dmg and such

**Comment by itcannotbe** [comment]
Ah yes. Now where did I put my EXTREMELY OVERPOWERED MAP OPTION again?

**Comment by the-kido** [comment]
> Ah yes. Now where did I put my EXTREMELY OVERPOWERED MAP OPTION again?

I don't see why that's a bad thing. It's up to the player. If they want that, go ahead. If they want to lower the speed, they can do that too.

**Comment by 50275** [comment]
This looks like a way to disable schematics without disabling them, or hiding ridiculous overpowered settings from the player.

**Comment by RouterChainsSuckk** [comment]
I just thought it would make low recourse maps easier without adding more ores
