### ISSUE TITLE
Shadows + Atmospheric enhancements + Colour stuff | Help make the game look nicer.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#911]
**Describe the content or mechanics you are proposing.**
- -  Shadows - - -
-Depending on where the sun is, the shadows of blocks will follow. Right now the blocks look light they are floating because of the shadows outlining it. These new shadows will stop that. (Could be a setting)
Before:
![before](https://user-images.githubusercontent.com/63456333/97087838-016fa280-15fb-11eb-9d08-e0e6ccbba9b3.PNG)
After:
![finished](https://user-images.githubusercontent.com/63456333/97087841-059bc000-15fb-11eb-9d99-c8ff0fc1bf72.png)
- -  Atmosphere - - -
-When it is afternoon the world should be slightly tinted yellow-orange for a warm effect. 
-When its morning or dawn the world should be tinted a bit red-orange to emphasis it's becoming morning/dawn
-Any time at night that isn't midnight should have a purple tint (So everything doesn't look so dull)
Example:
Before:
![purple thing](https://user-images.githubusercontent.com/63456333/97087977-dd609100-15fb-11eb-9661-705b56043d05.PNG)
After (Really badly done but gets the idea across)
![purple thing acual purple](https://user-images.githubusercontent.com/63456333/97087982-e2bddb80-15fb-11eb-8792-bf1ef765ed66.png)
- - Really extreme changes Anuke may/may not like - - -
-At night all glow should have a second layer of glow much smaller to make the lights stand out really nicely.
Before: 
![Capture](https://user-images.githubusercontent.com/63456333/97086904-2e6c8700-15f4-11eb-9a5f-22d38a3e1ac7.PNG)
After: 
![Capt1ure](https://user-images.githubusercontent.com/63456333/97086907-33313b00-15f4-11eb-9161-134841f2acd5.PNG)
If implemented it would look really nice but I'm not sure how much effort it would take to add something like this. 
Another example:
Before:
![Ca1pture](https://user-images.githubusercontent.com/63456333/97087352-64f7d100-15f7-11eb-9c80-feb2fcc3a2cc.PNG)
After:
![Ca11pture](https://user-images.githubusercontent.com/63456333/97087355-6d500c00-15f7-11eb-9039-b0a2116f9157.png)
-Surge alloy should glow. Its surge alloy so its _surging with energy_ I guess. This is just for aesthetics. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will help make the game look nicer without losing much of the charm it has. None of these should be game-changing, however.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
The game doesn't even have the concept of where the sun is and on a map with a shit ton of blocks that's a lot of calculations which I am doubtful phones could even handle.

**Comment by DeltaNedas** [comment]
looks great but would be hell to implement and would murder poor phone gpus

**Comment by the-kido** [comment]
> looks great but would be hell to implement and would murder poor phone gpus

When i was making this I was really worried this might be too much work on peoples phones (and even potato computers) so I suggest these all be settings

**Comment by the-kido** [comment]
> > looks great but would be hell to implement and would murder poor phone gpus
> 
> When i was making this I was really worried this might be too much work on peoples phones (and even potato computers) so I suggest these all be settings - players choice

**Comment by the-kido** [comment]
> The game doesn't even have the concept of where the sun is and on a map with a shit ton of blocks that's a lot of calculations which I am doubtful phones could even handle.

Campain has a planet and sun does it not?

**Comment by genNAowl** [comment]
Tried it before, too much math, gave up.

**Comment by the-kido** [comment]
> looks great but would be hell to implement and would murder poor phone gpus

I'm not very educated in coding at whatnot. But for the glowing colour overlay can't you just draw the glow onto the sprite like this?:
![temporarite](https://user-images.githubusercontent.com/63456333/97091275-c07e8a80-1608-11eb-99d5-8ad579ce494a.PNG)

**Comment by the-kido** [comment]
anuke prob saw this closing
