### ISSUE TITLE
Give Spectre Silicon Ammo

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#912]
**Describe what you would like changed, and why.**

Currently, Spectre is kinda like a upgraded form of the Duo/Salvo (similar ammo types, similar shooting style, etc). Unfortunately, they can't shoot silicon a mid-tier ammo, while Duos and Salvos can.

**Describe the changes you want to propose. Include possible alternatives.**

Let the Spectre shoot silicon, just for consistency.

**Comment by DeltaNedas** [comment]
good

**Comment by genNAowl** [comment]
bonk
