### ISSUE TITLE
Multiple campaign saves

### ISSUE THREAD

**Issue by jtb1313** [Anuken/Mindustry-Suggestions#913]
I would like to have multiple save files for the campaign.

I really enjoyed the progression of the game and want to do it again.  I would like to have a new save file with all the progression reset.  It would also be cool if the save files worked across platforms.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by QmelZ** [comment]
> 3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

oh please read this before putting an x there

**Comment by jtb1313** [comment]
My apologies I have not played in about 6 months and I was itching to play through again with the full progression but as a data horder I do not want to delete any save files.  Is this an implemented feature?

**Comment by DeltaNedas** [comment]
1. you can clear campaign data
2. since when do saves not work across platforms? i sync my data on pc and phone with git and don't have any issues.

**Comment by Cpppppppppplus** [comment]
jtb1313 would like the ability to have multiple save files, not just the ability to erase them.

**Comment by itcannotbe** [comment]
Back up your saves then clear campaign data. You don't need this to be a dedicated button/option in game -_-.

**Comment by jtb1313** [comment]
Cpppppppppplus 

> jtb1313 would like the ability to have multiple save files (visible in the in-game GUI), not just the ability to erase them and import/export data. 

Is right on this is something that would make it super simple
