### ISSUE TITLE
Smarter Distributor

### ISSUE THREAD

**Issue by Nyther** [Anuken/Mindustry-Suggestions#915]
Distributors should be able to be placed on top of conveyors like the routers and even on top of routers like you can with small walls.

I believe this would be a nice quality of life change to easy the making of designs.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Esnardo** [comment]
I cannot count the number of times I've had my design flow interrupted by having to make room for a distributor

**Comment by Esnardo** [comment]
That actually gives me an idea for another suggestion just a sec

**Comment by Esnardo** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/917
