### ISSUE TITLE
Planet Based Multiplayer

### ISSUE THREAD

**Issue by Nyther** [Anuken/Mindustry-Suggestions#916]
Instead of hosting one sector at a time and the clients dropping when the host changes sectors the game should instead host the whole planet.

It would create interesting interactions such as players asking for help and regrouping in one sector to overcome an obstacle or players that are good at creating production lines launching resources to sectors of players that are good at creating defenses so they can clear more space for the production players.

This is probably a bit difficult to be implemented but it would be a great addition to the multiplayer side of the game, even more if the game limits can be pushed far enough to the point where multiple planets are supported, maybe one day this could become a MMO game ;)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
This proposal is resource intensive in terms of compute requirements. A normal multiplayer game already struggles to keep up during mid-late game.

**Comment by DeltaNedas** [comment]
ok so dont host on a phone problem solved

**Comment by itcannotbe** [comment]
Well community servers are hosted on a vps and they still cannot maintain 60 tps on mid/end game.
