### ISSUE TITLE
Setting to allow replacing of any block with any other

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry-Suggestions#917]
**Describe the content or mechanics you are proposing.**
Make a setting that, when enabled, allows any block to replace any other, regardless of category, similar to how you can already place conveyors over any other conveyor blocks. This would work regardless of block size, allowing you to place large blocks over small ones or small blocks on large ones. The actual way this would be implemented is that when you attempt to build one thing over another, it would automatically destroy the blocks that were there, then build the new blocks

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would vastly improve the play experience for some players, allowing them to design and build faster. It would also make upgrading a factory or defence much faster.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by AgentAvis** [comment]
Yeah this would be nice.

**Comment by itcannotbe** [comment]
Griefers: Wow. What a nice mechanic you have there.
Also Griefers: Abuse
Also Griefers: Abuse
Also Griefers: Abuse

**Comment by Esnardo** [comment]
It's literally exactly the same as deleting some buildings and then placing new ones, just more convenient. How could a griefer abuse this in a way they couldn't before? 


On October 25, 2020, at 12:05 a.m., itcannotbe <notifications@github.com> wrote:

Griefers: Wow. What a nice mechanic you have there.
Also Griefers: Abuse
Also Griefers: Abuse
Also Griefers: Abuse

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/Anuken/Mindustry-Suggestions/issues/917#issuecomment-716084203">https://github.com/Anuken/Mindustry-Suggestions/issues/917#issuecomment-716084203</a>", "url": "<a href="https://github.com/Anuken/Mindustry-Suggestions/issues/917#issuecomment-716084203">https://github.com/Anuken/Mindustry-Suggestions/issues/917#issuecomment-716084203</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by Esnardo** [comment]
Oops, probably should've removed that junk before sending the reply email.

**Comment by itcannotbe** [comment]
It's just as convenient for griefers.

**Comment by Pietro303HD** [comment]
imagine accidentally placing a batterie on top of a vault and lose all the items that were stored and make your Thorium Reactor factory overheat, explode and fuck you up.

**Comment by Esnardo** [comment]
> imagine accidentally placing a batterie on top of a vault and lose all the items that were stored and make your Thorium Reactor factory overheat, explode and fuck you up.

That's why it's a setting, and defaults to off. Also, you can already accidentally destroy a vault with the normal destroy function.
I really don't understand why people are against this, it's literally just a more convenient way to destroy blocks.

**Comment by 50275** [comment]
imagine a griefer deleting your T5 reconstructor in 0.03 seconds with a conveyor

**Comment by Esnardo** [comment]
> imagine a griefer deleting your T5 reconstructor in 0.03 seconds with a
conveyor
Are you people not even reading my suggestion. It would take just as long to replace the T5 as it would to destroy it and then place the conveyor, because that's exactly what your player ship does. The only thing that changes is that you don't have to enter 2 separate commands. If a griefer wanted to grief, they would deconstruct the reconstructor. If this suggestion were implemented, that would still be all they could do, and it would still take just as long.

**Comment by itcannotbe** [comment]
You forgot the part where deconstructing a block stops it from working and the materials you get refunded for deconstructing a block is less than how much you would need to reconstruct it.

**Comment by Esnardo** [comment]
Wow, deconstructing sounds like such a good griefing tool, maybe anuke should remove it /s
> You forgot the part where deconstructing a block stops it from working and the materials you get refunded for deconstructing a block is less than how much you would need to reconstruct it.

**Comment by DS-3K** [comment]
This is a amazing suggestion that is so misunderstood :(
I fully support you on this one my lad! <3

**Comment by 50275** [comment]
this sounds like a disaster, waiting for someone to make a mistake
just a little off and you can accidentally start to destroy a vault

**Comment by genNAowl** [comment]
Bruh DK-3K and his reactions yikes
