### ISSUE TITLE
Lower the bloom threshold to include solid colors

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry-Suggestions#918]
**Describe what you would like changed, and why.**
Let bloom make "darker" colors also glow, mainly raw colors like Color.red, Color.green and Color.blue.
I don't know what value the new threshold should be(hence this is a suggestion and not a PR), but it would be nice to make a solid red glow, like The Powder Toy's PHOTons.
And besides, Draw.z was introduced so applying bloom is more utilitized anyways; if this changes some glow, you can leave stuff out using Draw.z.

**Describe the changes you want to propose. Include possible alternatives.**
Lower the bloom threshold(the brightness at which bloom is applied) to include solid? raw? colors(excuse my poor vocabularly). By solid colors I mean colors that have a HSV value of 1.

Alternatively, an invisible to the naked eye variable(like a pixel's alpha being 0.99 instead of 1.0) can determine.

Alternatively, apply bloom if the pixel's value(in HSV) is 1, but I have a slight concern that converting every pixel from RGB to HSV will deter performance(but it may not either; I con't know for sure!).

**Comment by Ferociousfeind** [comment]
You can easily approximate the saturation of a RGB pixel- if any of its three values are 1 (or 255), it's 100% saturated. Otherwise, the brightest value is the % saturation.

**Comment by sk7725** [comment]
![image](https://user-images.githubusercontent.com/58885089/97243457-babbbb80-1839-11eb-877e-7112c997918e.png)
^ What I want bloom to do(PHOT from Powdertoy)
