### ISSUE TITLE
 Nameable Logic Processors

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#919]
**Describe the content or mechanics you are proposing.**
An additional text field at the very top of the logic programming area that allows the user to name the processor. The name is visible when a user hovers their mouse over the processor, and can be used to search for a specific processor by name using the Unit Locate command.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The ability to allow units to find a specific processor could allow for more complex logic-based delivery systems. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
why find a specific processor by name and not just any block?
