### ISSUE TITLE
[Logic]Use radar without turret

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#921]
**Describe the content or mechanics you are proposing.**

Make the radar can be used without a turret.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will allow players to scan the entire map for enemies, and possibly even pave the best way.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Duplicate of
#696 
#456

**Comment by Ruichka** [comment]
Radar is already usable without turret, use processor instead

**Comment by Bohaska** [comment]
What's radar?

**Comment by sample-text-here** [comment]
Use `@this` instead of a turret to use the processor as a radar

**Comment by abaines** [comment]
What buildings/etc. can be used with the `Radar` function? I assume just the three processors (range 10, 22, 42) and any turret? Is there anything else that can serve as a radar? Mass driver? Core? (Or link to site/page/resource with this consolidated information please.)

I also assume mech units and players can be used with the `Unit Radar` function.

(Sorry to ninja this thread, but I wasn't able to find this answer anywhere else and I suspect someone following this knows the answer, given the very specific topic. 🙏)

Thanks so much! 🧡
