### ISSUE TITLE
Parallax push mode

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#922]
**Describe the content or mechanics you are proposing.**
Have the parallax be configurable to either pull or push instead of only pull.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
More uses for parallax, which is kind of useless at the moment.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
It's kinda useless because of low range.

**Comment by Slava0135** [comment]
You have Tsunami now. And it's incredible at pushing enemies back.

**Comment by Ilya246** [comment]
The problem is not how hard is it to push the enemy but how useful is parallax

**Comment by itcannotbe** [comment]
Tsunamis and waves uses liquids, Parallaxes uses power.

**Comment by DS-3K** [comment]
Ok this might sound insane but...

what if instead of giving paralanx a new usecase,
we make its current usecase actually usefull

Doesnt that sound nice??
**Increase the dang range! Its purpose is to close the distance to smol units, but when the units get in parallanx range, they are already close enough :(**
