### ISSUE TITLE
[Logic]Bind any unit

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry-Suggestions#926]
**Describe the content or mechanics you are proposing.**

Add "any" point to unit bind

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will allow players not to put a bunch of unit bind with different values ​​in type.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Pietro303HD** [comment]
`@all` existes you know right? irc they stopped working for some reason...
