### ISSUE TITLE
nerf mega into brazil

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#927]
**Describe what you would like changed, and why.**

![a](https://user-images.githubusercontent.com/39013340/97104343-1dcb1800-16ab-11eb-8cd1-0bf3302a82d5.jpg)
one wave of megas that hide in the corner until an enemy block is broken
too much

**Describe the changes you want to propose. Include possible alternatives.**

1. greatly reduce mega spawns, this is absurd
2. make them act as offensive units when there are no damaged blocks

**Comment by the-kido** [comment]
no no _**this is fine**_

**Comment by BlueWolf3682** [comment]
nerf the spawns but do NOT make them act as offensive units. they do not have offensive weaponry.

**Comment by DeltaNedas** [comment]
if you hadn't noticed, they definitely took out my arcs and what not.

**Comment by itcannotbe** [comment]
Is it me or did @BlueWolf3682 forgot that heal bullets actually damages non team block and units?

**Comment by scarf-generic** [comment]
So not nerf the unit, nerf the campaign spawns?

**Comment by Anuken** [comment]
(since a commit three days ago, mega units don't even spawn in the campaign)

**Comment by potatoisagender** [comment]
:eyes:
