### ISSUE TITLE
Paralysis

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#929]
**Describe the content or mechanics you are proposing.**
Paralysis, a bigger, more powerfull version of the parallax. It would be 3×3, would require water or cyrofluid, and would use 700 power per second, it can be boosted to increase effectiveness by 25% by using phase fabric or cyrofluid (or both). This turret would be made with 50 phase fabric, 100 thorium, 150 surge alloy, 100 titanium, 150 plastanium, 200 copper and 175 silicon. This unit would be able to take down bigger units (T3&T4 and maybe T5 if there are multiple Paralysi), they can also pull in ships onto land.
 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Right now the parallax is useless against bigger, more advanced units like the eclipse so this could help.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Why would you ever use the parallax against a T5 unit for damage
Anuke himself said that "_Parallax turrets are only meant to reel in/damage very small units_" https://discord.com/channels/391020510269669376/396416151032299521/734040372044628058
also this sounds like a really bad meltdown

**Comment by DS-3K** [comment]
This is a good example of how not to make a suggestion.
You should have just said
"New turret, a upgraded parralanx thats also good against big units"
So now nobody wastes any time going through details that are unneeded
Your advantage: if your idea is good, but your details are bad you will get more feedback about whats really importand and less about the noisey details
Source: "new turret: the enforcer" (bad suggestion)
"Anti herassment turret" (good suggestion)
Both are pretty much the same, but one doesnt have noisey details and was much more successfull. <3
