### ISSUE TITLE
Editor block/unit type rules

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#931]
**Describe the content or mechanics you are proposing.**
New bottom at rules on editor where you can pick a block or unit to configure and set its multiplier,things you can configure : block health,block damage (turrets),block build cost,block build speed,unit health,unit damage,unit production speed(factories),unit speed and unit item capacity (max for speed would be ×10 so they dont break the map)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.** 

 • Would make maps more interesting

 • More experiments

 • Allows players to do much more stuffs (like 
   making a teleporting flare that can kill quad)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
it's better to leave this kind of thing as a mod
