### ISSUE TITLE
Centipede like unit

### ISSUE THREAD

**Issue by Joshwelyt** [Anuken/Mindustry-Suggestions#932]
**Describe the content or mechanics you are proposing.**
A unit made when it first goes out it's just a little unit but when the factory produces another the other one will latch on to the other unit and combine to one see routorio router pede for a better thing of waht I propose

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will give more unique ways to destroy my fps and make it fun for me atleast and a new unit is cool not only that there is only a few amount of ground units, this can be used by modders as well to make easier things like the routerpede

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
1. just use routorio
2. having an efficient worm class by anuke would be nice

**Comment by Joshwelyt** [comment]
Yes routorio but worm WORMWORM
YES yes and also
Some modders might want to make those kind of units without scripting just like frickin sh- me

**Comment by 50275** [comment]
Mindustry V6 has already reached the beta stage. It's too late, your worm won't get added.

**Comment by Joshwelyt** [comment]
Well we don't know if anuke sees this he might add it before finishing v6

**Comment by DeltaNedas** [comment]
having the class doesnt mean there needs to be a vanilla unit for it

**Comment by z0mbiesrock** [comment]
100% not happening outside of mods
![image](https://user-images.githubusercontent.com/19158169/97636363-65390780-1a0f-11eb-9e87-2186b944aba5.png)

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
c r a w l e r  w o r m
