### ISSUE TITLE
bunkers

### ISSUE THREAD

**Issue by liliam2007** [Anuken/Mindustry-Suggestions#933]
**Describe the content or mechanics you are proposing.**
maybe have a bunker which smaller units can take cover and fire from

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this could open up more kinds of defenses and schematics along with some different strategies

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
So... I'll build a few walls in the shape of a U and put units into it. This is my amazing bunker.

**Comment by DS-3K** [comment]
Elegance is when components serve multiple purposes.
Making a component that is just better at a single function of something else is counterintuative
Why not just use open doors? Your units can move and shoot through, while they block your enemys shots ^^
