### ISSUE TITLE
Per-team Custom Game Settings

### ISSUE THREAD

**Issue by a-soulspark** [Anuken/Mindustry-Suggestions#934]
**Describe the content or mechanics you are proposing.**
Allowing the customization of Custom Game settings/map rules for each team (Block Health or Damage, Unit Production Speed, etc.)
These settings currently apply to all teams.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Balancing Attack Mode games, allowing for different gameplay styles, or helping out a friend who isn't as good by buffing them when doing PvP.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
You can already do this by doing things like giving them extra resources
Alternatively, increase starting resources but manually remove some resources from your core
Alternatively, prohibit yourself from using certain units that may be better than others
Alternatively, give them a few starting buildings / infinite power (if they're really inexperienced)
Alternatively, a third AI team that has buildings just to annoy you like duos in your ores
Alternatively, editing AI ammo supplies and mender strength/quantity

**Comment by a-soulspark** [comment]
None of these solutions work with PvE, and/or require editing the map. Plus, prohibiting the use of certain units also feels lazy.
This isn't an absolute priority, ik, but I think it'd allow for quite a lot more playstyles.
