### ISSUE TITLE
Foreshadow balance change suggestion

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#935]
**Describe what you would like changed, and why.**
Make force field take damage and block foreshadow shots from hitting things protected by the force projector, oct's force field, and quasars force field.

**Describe the changes you want to propose. Include possible alternatives.**
As above, make force projector able to interact with foreshadow shots. Pretty simple, to protect other buildings from getting instantly killed by a player/logic controlled foreshadow. Currently there are no armored power nodes so all it takes is someone killing a couple power nodes and an entire defense can fall. Thanks for reading!

**Comment by itcannotbe** [comment]
The foreshadow doesn't benefit from liquid boost already and compared to spectres and meltdowns the come mediocre to sieging. Their only advantage is stupid range.

**Comment by scarf-generic** [comment]
> The foreshadow doesn't benefit from liquid boost already and compared to spectres and meltdowns, it come mediocre to sieging. Their only advantage is stupid range.
This just is not true... their advantage is that they can **shoot over any wall, building or unit** and target weaker buildings behind them. Its flat out the best seige turret because it has no counter. It ignores everything except its target, has stupid range, and one shots most buildings in the game. You cant mend what is already dead.

**Comment by 50275** [comment]
a force projector has 750 shield HP, so for each foreshadow (1350 damage) you get I'll just get ~2 of force projectors and water them
have fun lol

**Comment by scarf-generic** [comment]
> a force projector has 750 shield HP, so for each foreshadow (1350 damage) you get I'll just get ~2 of force projectors and water them
> have fun lol
Click on force projector twice, click on power node powering force projector

**Comment by 50275** [comment]
Force projector wars
