### ISSUE TITLE
[Editor] "Place enemy spawn" Filter

### ISSUE THREAD

**Issue by Bedsurfer** [Anuken/Mindustry-Suggestions#936]
**Describe the content or mechanics you are proposing.**

In the editor, a new "place enemy spawn filter" could be used to place a enemy spawn block/core at the point furthest from the core possible, aka still in valid enemy pathing areas. Include a block selection dialog that include an enemy spawn and all core types.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will make maps using post-generation methods of creation possible 100% of the time, instead of needing to use unintuitive methods like tile-block canceling.
Example: Filter would automatically place an enemy spawn somewhere in the red circle.
![image](https://user-images.githubusercontent.com/72096570/97113014-2e7c8d80-16ad-11eb-9c69-657332fd6077.png)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
Can't you just fill that red area with enemy spawns, then use the "select enemy spawn" filter to pick one?

**Comment by Bedsurfer** [comment]
Right. This isnt needed then.
