### ISSUE TITLE
Allow mobile users to rotate buildings without breaking/rebuilding them, similar to how PC users can

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#937]
**Describe the content or mechanics you are proposing.**
Let mobile users rotate buildings like pc users can. No new buttons are needed for the mobile ui, just allow buildings to be placed where they already are, assuming they have a different rotation. It appears conveyors can already do this, but they might take time to build. Similar to how you "build over" walls to upgrade them, allow this with buildings of the same type that are directional. Best example is reconstructors. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will make mobile less of a downgrade of mindustry. Doesnt add more gameplay options, adds pre-existing gameplay options to a different platform. Thank you for reading!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
that moment when a conveyor has 666 edits....

**Comment by scarf-generic** [comment]
Partially got added. Made new issue that is more up-to-date with the current builds. ( #1143 )
