### ISSUE TITLE
Buff the Sei

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry-Suggestions#939]
**Describe what you would like changed, and why.**
The Sei (Tier 4 Naval) unit is extremely weak, unable to destroy most things with menders or healing. 

**Describe the changes you want to propose. Include possible alternatives.**
A more powerful missile battery or a ripple type artillery weapon. Possibly a railgun type weapon like the Omura. 
SIDE NOTE: the check boxes are missing from the template, the ones that confirm that the user has searched GitHub and Trello.

**Comment by D-player1** [comment]
~~change swarmer ammo to surge~~

~~Or if that's not enough, make it shoot as fast as a cyro swarmer~~

~~OR IF THAT'S NOT ENOUGH OVERDOME THE WEAPON, AND YOU HAVE THE MOST OP UNIT IN MINDUSTRY~~

**Comment by BlueWolf3682** [comment]
github needs an ohno emote

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/97124887-4e8d6a80-1708-11eb-9d24-f515aa871de7.png)

**Comment by ritzip** [comment]
once again, the checkboxes are for feature requests

**Comment by scarf-generic** [comment]
Yeah, needs a buff for sure. If it cant break through 2 layers of small menders and its a t4 unit, something is very wrong. Arent navals supposed to be broken as hell in damage/health stats but limited to water? This seems like its just bad...

**Comment by 50275** [comment]
Quasar T3/Fortress T3 is better
alternatively you can probably kill 1-2 of those with a quad

**Comment by z0mbiesrock** [comment]
Not happening. Anuke confirmed
