### ISSUE TITLE
能否增加逻辑支持单位

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Anuken/Mindustry-Suggestions#940]
希望增加逻辑运算单位，可以用于指挥导航等，以及增加黑客玩法[通过特殊机种入侵干扰敌方单位，但需要非常多的逻辑计算机/单位支持，可以夺取控制权，单位越高级越难以入侵]，希望向mono线路加入子弹/导弹制导功能，并且增加巡航导弹生产线，以及能否增加天基武器?

**Comment by itcannotbe** [comment]
Besides not using/following the template. This suggestion is better suited to be found in the reviews of google play store.

**Comment by 50275** [comment]
Google translate

I hope to increase the logic operation unit, which can be used for command and navigation, etc., and increase the hacker gameplay [invading and interfering with enemy units through special aircraft types, but it requires a lot of logic computers/units to support and can seize control. ], hope to add bullet/missile guidance function to the mono line, and increase the cruise missile production line, and can add space-based weapons?

**Comment by Gdeft** [comment]
French.
