### ISSUE TITLE
Discord rich presence map naming

### ISSUE THREAD

**Issue by soupman69** [Anuken/Mindustry-Suggestions#942]
**Describe what you would like changed, and why.**
Currently, the rich presence shows map names, although, when said map has a colour (e.g, [#ff5656])
The main reason for this to change is just so the rich presence looks cleaner, with less clutter.

**Describe the changes you want to propose. Include possible alternatives.**
I propose that map names in the rich presence dont include the data in [ ] or just removes any hexadecimal included in the maps name.
![Screenshot 2020-10-26 111020](https://user-images.githubusercontent.com/39944733/97165582-da8caa00-177b-11eb-897d-e59bc3c0f2b1.png)

**Comment by DeltaNedas** [comment]
bruh make a pr with Strings.stripColors

**Comment by summetdev** [comment]
Implemented by Anuke, you can close this now.
