### ISSUE TITLE
Water platforms

### ISSUE THREAD

**Issue by cheems-cheese** [Anuken/Mindustry-Suggestions#943]
I had troubles with the map "archipelago" because of just one island that was too far for the other islands, and it would be really helpful for a water platform or just something to build on water.

It'd be really helpful for water maps or do for space too

**Comment by itcannotbe** [comment]
@cheems-cheese  You forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety

Also duplicate of #306
