### ISSUE TITLE
isBound unit property for logic

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#945]
**Describe the content or mechanics you are proposing.**
isBound property for units via logic command. Returns true if unit is bound (wow)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This way you can detect idle units. E.g. you can unflag them which is impossible at the moment without unflagging ALL units. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
> you can unflag them which is impossible at the moment without unflagging ALL units.

I'll... just put this here

```
ubind @poly
jump 0 equal @unit null
sensor flag @unit @flag
jump 0 notEqual flag 12345
ucontrol flag 67890 0 0 0 0
```

**Comment by Slava0135** [comment]
ok you still can remove flags one by one but what if you have 100 units? And you need to find them all.

**Comment by Slava0135** [comment]
And I propose a different approach to make it auto-configurable and self-maintaining.

**Comment by sample-text-here** [comment]
> ok you still can remove flags one by one but what if you have 100 units?

This code changes/removes the flags of *all* units with a specific flag. If you use flags correctly, you could, say, set the flag to `-1` when you're using a unit and then reset it to `0` when you're done. Then you could check if the flag is 0 to see if it's bound
```py
#bind to a flare
ubind @flare
#does the unit exist?
jump 0 equal @unit null
#is the flag not set?
sensor flag @unit @flag
jump 0 notEqual flag 0
#flag it to not have it stolen by another processor
ucontrol flag -1 0 0 0
#do stuff askdjhksdjhk
#more code here skasjlj
#then flag it back to say "this unit is free now"
ucontrol flag 0 0 0 0
#and now an infinite loop to stop it from running the code again
jump 5 notEqual x false
```

**Comment by Slava0135** [comment]
> If you use flags correctly, you could, say, set the flag to `-1` when you're using a unit and then reset it to `0` when you're done. Then you could check if the flag is 0 to see if it's bound

"Let's say" - but in my recent logic schematic I can use ***any*** flag not only 1. So it's not working for me. *Just stop*

**Comment by Slava0135** [comment]
The problem is that the processor can set a flag but later has been destroyed and nobody cares about unit and it's flag. Technically it's unbound but it's flag can be whatever number.

**Comment by summetdev** [comment]
> Returns true if unit is bound

Maybe return 0 or 1?

**Comment by summetdev** [comment]
Implemented. :rocket:

**Comment by CardealRusso** [comment]
this was removed?
