### ISSUE TITLE
Tanks

### ISSUE THREAD

**Issue by Dastianzerg** [Anuken/Mindustry-Suggestions#946]
**Describe the content or mechanics you are proposing.**
Tanks and Other Treaded Vehicles 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Cant fly but can switch to a boat-like form where the treads are the floats and it lowers a prop to move in the water but it is more fragile, still can fire while in boat form.
They should do more damage and have more health but cost more and move slower (also heavier so only higher tier carrier drones can pick them up.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
(resuggesting as a previous one wasnt in a correct format)
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by OnyxDog07** [comment]
Classic. It's a good idea but maybe needs a bit more balancing.

**Comment by Colonizor48** [comment]
We need the bob semple tank in mindustry https://en.wikipedia.org/wiki/Bob_Semple_tank
