### ISSUE TITLE
Another Naval Unit Type: The Purple ones

### ISSUE THREAD

**Issue by Pietro303HD** [Anuken/Mindustry-Suggestions#947]
They would have a different mechanic, where they can bring in ground units. For example, let's say you have a lot of ground units in a naval map. You could make the new naval type, and place the ground units on top of the boat. Being useful for bringing in powerful ground units to water with a quick speed. They would be able to carry units from the same tier and below. 
**Logic Addition:**
For the logic part, it would be like a payload. You can use payTake to take an unit, and payDrop to drop an unit.

It's (again) going to be a neat little naval unit variation, with a cool mechanic. It's what i think the purple naval units would look like. It would also allow for a lot more of naval maps, since you could just move ground units along the sea, and make even better defenses.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Dastianzerg** [comment]
i dont think this is in the correct format?

**Comment by Pietro303HD** [comment]
wdym

**Comment by Dastianzerg** [comment]
scan the other suggestions, do they look like yours?

**Comment by Pietro303HD** [comment]
i just removed some text

**Comment by Dastianzerg** [comment]
yeah, that makes it  slightly incorrect, and also i am yelling at a new person on the discord

**Comment by Pietro303HD** [comment]
> Describe the content or mechanics you are proposing.

> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

**Comment by Dastianzerg** [comment]
yep those 2
put em in it

**Comment by Pietro303HD** [comment]
@potatoisagender those aren't naval support units

**Comment by Pietro303HD** [comment]
and the issue is closed
