### ISSUE TITLE
Scorch and "Inferno"

### ISSUE THREAD

**Issue by OnyxDog07** [Anuken/Mindustry-Suggestions#948]
Scorch now can use Slag and Oil as a bonus liquid. Oil makes its flame linger on the ground and slightly increases range but not too high, slag gives a damage boost.
'Inferno', a new T2 of the scorch, requires coal or pyratite AND oil or slag to fire a flame in a 135 degree angle, an effective weak unit killer. It also has more range than the scorch, kind of an almost-scatterer range but slightly less. The inferno can attack air units but is less effective against them

This can be used to counter some things such as t1-t3 unit spam on ground, but it requires some things that aren't oftenly used in the front lines, such as oil and slag. (Scorch would have a damage reduction because of the slag bonus)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
(Figured this would be a more 'balanced' version)

2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.

3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by the-kido** [comment]
The name needs changing but this is cool

**Comment by XEN0PHIL** [comment]
Flamethrower turret with limited turn angle, where did I see it...

**Comment by DeltaNedas** [comment]
ripping off factorio but i dont care it makes scorch less useless

**Comment by 50275** [comment]
I don't get it
Why the hell would you need either, the scorch already has an extremely low time to kill and it will kill those units almost instantly if they get in range - but, almost all mechs outrange it to begin with, which essentially means that your opponent will sit outside the range of your scorch and tear it to bits anyway

**Comment by RogueRedHawk** [comment]
Not very useful imo, as in 6.0 hordes of weak units have been ditched favoring a few stronger units. Crowd control is far less useful now. The liquid boosting with effects is cool, but a T2 scorch is unnecessary.

**Comment by BlueWolf3682** [comment]
toxopid shredder? dont mind if i do. name should be Inferno to fit the names better.

**Comment by OnyxDog07** [comment]
I figured most of the flame turrets are way more useful in Survival than PVP because of the wave amount.

**Comment by 50275** [comment]
But.. why would you ever need a better scorch, it already does good damage
