### ISSUE TITLE
Delay enemy unit spawn

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry-Suggestions#949]
Delay enemy unit spawn by a bit, so their landing zone is cleared from blocks before their arrival.
This will prevent easy and cheap wave clear with reactor and battery explosions.

**Comment by 50275** [comment]
This already happens. The surrounding area is already destroyed before the units arrive.

**Comment by machond** [comment]
Dealy a bit (50 ms more) because explosion before spawning, killing spawned units.
