### ISSUE TITLE
[QOL] Indicator for missing resources on schematic.

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry-Suggestions#95]
**Describe what you would like changed, and why.**
~~Similar to how items are grayed out when you have insufficient resources, have schematics also be grayed out when you don't have enough resources to create them.~~
Have an indicator on schematics with missing resources.
This would make it easier to see which schematics you can build fully.

**Describe the changes you want to propose. Include possible alternatives.**
~~Gray out schematics with insufficient resources~~
Add an indicator on the lower showing a red slash over resources that are insufficient OR display a number of missing resources over the resource icon.

<details>
<summary>Old draft</summary>

![draft](https://user-images.githubusercontent.com/58778985/79055491-9260cc80-7c1b-11ea-91e0-d95978fe3e59.jpg)

</details>

**Comment by Anuken** [comment]
Implemented.

**Comment by DS-3K** [comment]
Awesome!

Am Fr., 24. Apr. 2020 um 17:49 Uhr schrieb Anuken <notifications@github.com
