### ISSUE TITLE
Why not to tap-upgrade?

### ISSUE THREAD

**Issue by Buffoonogg** [Anuken/Mindustry-Suggestions#950]
**Describe what you would like changed, and why.**
Why not to able to upgrade after leaving a factory or a payload conveyor? Just being a crawler and going to the next upgrading. 

**Describe the changes you want to propose. Include possible alternatives.**
If you double-tap on a factory while being a unit, you enter the factory and able to upgrade. Also alpha beta and gamma should be upgraded too.

**Comment by 50275** [comment]
So... commanding units to put themselves into buildings such as reconstructors?

**Comment by Buffoonogg** [comment]
> So... commanding units to put themselves into buildings such as reconstructors?

Well to be honest its not really a reconstrution, its like entering in the factory anytime, everywhere after the chain reaction. Because yeah in mindustry you cannot enter without the chain reaction

**Comment by RedRanger5577** [comment]
This is a good idea because flying mechs can't be put onto a payload conveyor and it would be cool if at any time you could land/stand on a payload conveyor to go onto it
