### ISSUE TITLE
Naval Support Units And Structures

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#951]
**Describe the content or mechanics you are proposing.**
Currently there's only one branch of naval units: the ones designed specifically to attack. What I propose is another branch of naval units, support units. They'd be able to build just like other support units, and would be as follows:

Orinoco: Small t1 support. Carries a single repair gun that shoots in quick bursts of 3, as well as a weak heal-field generator. Costs 15 silicon and 30 metaglass. 
Baiji: t2 support. Carries two heal-missile launchers (homes in on damaged blocks) and a minelayer (deposits mines in the water that fade to near-invisibility, deal heavy damage to naval units but cannot hurt anything else).
Clymene: t3 support/defense. Carries a pair of PD cannons, a rapid-fire AA gun (think Cyclone but a bit slower) and a shield projector. 
Vaquita: t4 heavy support. Carries a fragmenting artillery cannon (like the Toxopid but many less secondary shots), a strong heal-field generator and a cluster minelayer (spits out shotgun clusters of mines).
Orca: t5 heavy support/defense. Slowest of any naval unit, carries a large shield that's much less durable than the Oct's, but trades a single powerful shield for additional defensive capability in the form of a highly accurate Spectre-style cannon that can both heal blocks and deal damage, though it's not as powerful as the actual Spectre.

There would be few support structures, but they would be as follows:

2x2 Deepwater Platform: constructed with 30 plast and 50 metaglass, will float in the water and allow buildings to be built on top of it. If it is destroyed, all buildings on top of it are destroyed as well.
5x5 Deepwater Platform: constructed with 50 plast, 75 metaglass and 10 phase.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Adding naval supports to the game would make naval combat much more viable and fun, and provide additional combat options to people who like to play support. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
Hasn't this been posted?...

**Comment by potatoisagender** [comment]
#947 #811 #805 #766 #702 #690... The list goes on and on and on, and I have no time to go through...
 >  I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
a lie, apparently

**Comment by Violet-Scarelli** [comment]
> #947 #811 #805 #766 #702 #690... The list goes on and on and on, and I have no time to go through...
> 
> > I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
> 
> a lie, apparently

Thanks for your concern.
