### ISSUE TITLE
Allow Users Possessing a Unit (Ctrl+click) that can't build to build if they are commanding units (with G) that can build

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry-Suggestions#952]
**Describe the content or mechanics you are proposing.**
If a user is possessing (ctrl+click on a unit. for example, the reign.) and they are commanding (G) 8 megas, they should be allowed to build even though the reign is not able to build itself.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
No more rapidly ctrl + clicking on your units that can build and pressing G before they run away from you lol
quality of life stuff

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by AgentAvis** [comment]
I would suggest extending this: allow all units to place things, just not construct them fully. So you could basically plan out things as whatever and other units could fly it and autoamtically build it

**Comment by DeltaNedas** [comment]
very yes
