### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by RedRanger5577** [Anuken/Mindustry-Suggestions#953]

**Comment by 50275** [comment]
I don't think this is going to be added into the game. Anuke has already put V6 into beta. Too late.

**Comment by BlueWolf3682** [comment]
1. better name than Hive please 
2. thats op for a starter unit
3. make it in a mod .-.

**Comment by potatoisagender** [comment]
WHY DO PEOPLE KEEP SUGGESTING THINGS LIKE THIS??????????????????? YOU'VE DONE ALL THE WORK NEEDED TO MAKE A MOD, SO MAKE ONE PLEASE. I HATE SEEING SUGGESTIONS LIKE THIS.

**Comment by itcannotbe** [comment]
> WHY DO PEOPLE KEEP SUGGESTING THINGS LIKE THIS??????????????????? YOU'VE DONE ALL THE WORK NEEDED TO MAKE A MOD, SO MAKE ONE PLEASE. I HATE SEEING SUGGESTIONS LIKE THIS.

Agreed. Plus there too many units already.

**Comment by 50275** [comment]
here's a better idea
while you're busy getting the hive how about I get a Quad and destroy all of it
