### ISSUE TITLE
Hovering over a processor should show the unit it's controlling

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#954]
**Describe the content or mechanics you are proposing.**

Similarly to how hovering over units show the bound processor, hovering over a processor should show its bound unit

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will help with debugging

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Legomonster33** [comment]
due to how most programs loop over all units it would likely end up just rendering as a circle of arrows

**Comment by summetdev** [comment]
@sample-text-here implemented. ❤️

**Comment by sample-text-here** [comment]
Oh yes

**Comment by sample-text-here** [comment]
Thank you
