### ISSUE TITLE
Redoing The Command Mechanic

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#955]
**Describe the content or mechanics you are proposing.**
Instead of the command-unit key scooping up every single unit in a certain radius, holding the command key and clicking units within a certain radius will add them to the command formation. Doing the same while a unit is commanded will release them from command, and clicking and dragging while holding the command-unit key will drag them around in the commander's formation. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This change would make the command mechanic so much more palatable to use, and since all units can command now, it's a lot more relevant. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
Recommend using Shift instead of G
