### ISSUE TITLE
More realistic unit control for 6.0

### ISSUE THREAD

**Issue by NextRank** [Anuken/Mindustry-Suggestions#956]
**Describe what you would like changed, and why.**
     The current method of unit control is unrealistic, because once you are controlling a drone or turret, your original ship disappears. The ship should have to go somewhere. I believe that for many players find it frustrating to have to return to the core each time they switch units, especially if the map is large.
**Describe the changes you want to propose. Include possible alternatives.**
     Instead of the current method, why not have the player's original ship float alongside the controlled unit? A disappearing ship just does not look right in my opinion. For example, if you want to control a turret, your original ship will fly next to the turret, and land. The turret will be controlled by you. When you want to use your original ship again, just press V, and your ship is able to take back off, and the turret is no longer controlled. As for a drone, the player's ship will be floating alongside the ship; much like holding a balloon by the string. Of course, there is the issue of enemy ships targeting and destroying your disabled ship. There are two ways in my opinion that this could be addressed. One way is that simply, your ship cannot take damage. That is unrealistic, which is where my other idea comes into play. Instead, when the disabled ship takes damage, the player has the option of sharing some of the unit's health with the ship. Regardless of which method used, once your main ship dies, you lose control of the unit and have to re-spawn at the core. I also think this presents a bit of a challenge, as when you begin to control another unit, you risk destroying your ship. As for when your controlled unit dies, you regain control of your main ship.

**Comment by Mothership007** [comment]
The ship disappearing and you needing to respawn at the core encourages players to use support units such as poly and pulsar instead of the alpha, beta and gamma starting ships.

**Comment by 50275** [comment]
if you pick a unit that is too slow then good luck
I'm going to get my megas

**Comment by NextRank** [comment]
> The ship disappearing and you needing to respawn at the core encourages players to use support units such as poly and pulsar instead of the alpha, beta and gamma starting ships.

Well that would bring up the 5.0 prospect of upgrade pads.

**Comment by NextRank** [comment]
Okay I will be closing this now.
