### ISSUE TITLE
Actualy make sqrt(-x) or x/0 = NaN instead of 0

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#957]
**Describe the content or mechanics you are proposing.**
Make it so in a processor sqrt(-x)m x/0 and other invalid functions actually output NaN or null instead of 0

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Just so something doesn't accidentally break with processors when someone tries to make something and it ends up dividing by 0 accidentally.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
nan is a nightmare in normal languages let alone assembly.

**Comment by Colonizor48** [comment]
we already have a null value for non existant variables. Just make invalid functions equal null and its good then.

**Comment by DeltaNedas** [comment]
yes

**Comment by itcannotbe** [comment]
Having NaN be processed is counterintuitive. Just make the processor throw an error and stop the loop.

**Comment by Colonizor48** [comment]
Did you not read my comment. Just make it output null and mabye a function to check if somthing is null

**Comment by sample-text-here** [comment]
> mabye a function to check if somthing is null

`jump 0 equal asdksjfhhksanas null`

**Comment by Colonizor48** [comment]
yeah we dont need a function on 2nd thought. (though i really really really would like to see imaginary numbers/complex numbers added to logic that would probably be a nightmare to code)
