### ISSUE TITLE
Blue kind of units, new type

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry-Suggestions#958]
**Describe the content or mechanics you are proposing.**
Add new kind of units that would be called universal, units of that type would have higest mobility from all units. All new uniyts added/chaged in V6 are slow. I hate lack of javelin-like unit

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
How would they work?
Being high/higest mobility unit would be the fastest way to move, but not only. They would be air type units.
For balacing high mobilty of course small amout of health, weak attacks/slow build speed.
Names/attacks/how would work.
T1 - Mico - Attack like mono, slighty faster than other units. Cargo: 20
T2 - Fulgur - Basically same mechanic like javelin, but slighty slower than in v6 Cargo: 45
T3 - Viatorem - Faster, no attack, only makes arcs from momentum Cargo: 60
T4 - Motus - Same speed like T3, no attack in any form, would teleport in curos position on Shift+Alt in 30 sec delay Cargo: 80
T5 - Celeritas - The fastest unit, on getting speed would make a small shield and great arcs, teleport could teleport after 1 minuts-40 secs delay, teleporing makes lost all momentum. Can take to T3 unit and 4x4 blocks, deceracing speed by 20-10% Cargo: 110

Cost to build T1 unit: 20 silicon, 10 titanium, 20 copper

But why?
Make huge maps more playable, allowing getting faster to pleace when theres defences leak, fire, etc.
Optional mechanic:
Units over 2T would take water as cargo and drop it by holding G button, would make fires less scary and easier to put them out, would be very useful on multiplayer.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
unit that uses lancer to move

**Comment by QmelZ** [comment]
> unit that uses lancer to move

already exists, its named quasar
