### ISSUE TITLE
What can you actually suggest, since Mindustry is already in beta?

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#960]
**Describe what you would like changed, and why.**
The list of stuff that you should not suggest

**Describe the changes you want to propose. Include possible alternatives.**
Add all the types of things you wouldn't add if suggested e.g. if you don't need more types of drones, then put it in.

**Comment by Bohaska** [comment]
By the way, this template doesn't have checkmarks, so don't bash me for not including them

**Comment by 50275** [comment]
Why are you asking this on GitHub, where anuke gets notifications?

**Comment by itcannotbe** [comment]
The do not suggest list already exist. See the [read me](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)  of this github repository.

Also you can still suggest thing not included in the do not suggest list, thing being is that the probability of anuke adding them in this late is close to nil.

**Comment by itcannotbe** [comment]
The do not suggest list already exist. See the [read me](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md)  of this github repository.

Also you can still suggest thing not included in the do not suggest list, thing being is that the probability of anuke adding them in this late is close to nil.

**Comment by sample-text-here** [comment]
> Also you can still suggest thing not included in the do not suggest list, thing being is that the probability of anuke adding them in this late is close to nil.

they're asking what suggestions they should make that isn't "close to nil".

**Comment by itcannotbe** [comment]
Balancing Suggestions.

**Comment by Bohaska** [comment]
Any more?
