### ISSUE TITLE
[Logic] Unit idle pathfind

### ISSUE THREAD

**Issue by Khanx** [Anuken/Mindustry-Suggestions#961]
**Describe the content or mechanics you are proposing.**

Some units are idle because their "pathfind" don't command anything.

I would like to know WHEN a unit is idle to command it work. 

Examples:

if unit (mega) idle mine ore otherwise pathfind

if unit (poly) idle look for damaged allied buildings and shoot them to health them

etc

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This content may be interesting to take advantage of idle units WITHOUT losing their vanilla behavior

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
I'm sure you can already do this with logic parts.
