### ISSUE TITLE
Add stone and lava

### ISSUE THREAD

**Issue by CoinCaribou2070** [Anuken/Mindustry-Suggestions#963]
**Describe the content or mechanics you are proposing.**
Stone (mined from pebbles or made from lava) and/or Lava (made from stone, generated in pools, or extracted using a Lava Extractor)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Stone can be used as low-level ammo or melted into lava and used as liquid ammo. lava can also be used to power a new type of generator. Lava could also be cooled back into stone. This will give the player more options on how to power their machines and weapons. Lava would be stronger than slag when used as ammo, but would require special pipes to transport, and would cause fires if spilt, so it wouldn't be super powerful.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by 50275** [comment]
This isn't mindustry v3. Anyway:
Copper duos replace stone turrets.
Slag replaces lava. 
Please close this suggestion.

**Comment by DeltaNedas** [comment]
scrap is low tier ammo
slag is usable in a wave

**Comment by NextRank** [comment]
Yes. You are asking for something that already exists. Like they said, please close the suggestion, as nobody can close it for you.

**Comment by NextRank** [comment]
>     3. * [x]  I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

You also failed to meet the requirements of the above check, which means you did not take time to read the wiki at all.

**Comment by Bohaska** [comment]
You forgot to tick this
- [X] I have never checked the wiki and never played with recent versions of Mindustry, therefore my suggestion is trash.
