### ISSUE TITLE
New Logic Air Units (And A Tweak To Unit Binding)

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#964]
**Describe the content or mechanics you are proposing.**
Logic air units solely for transporting items. No guns, no anything else. Just high capacity and good speed. 
T1: holds 30 items.
T2: holds 60 items.
T3: holds 120 items.
T4: holds 240 items.
T5: holds 480 items.

Additionally, I would propose that the `ubind` command be slightly reworked: units would now remember what processor they were last bound to, and favor that processor in any subsequent rebinding attempts. Also, the closer a unit is to a processor, the higher its binding priority, making it so that each processor has an effective bubble where it can easily bind units. Thus, a unit can be manually transferred from one processor to another by controlling it and moving it closer to the other processor, overriding the rebind priority with distance priority. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
The logic tweaks would instantly make unit logic a lot less frustrating, and the flying logic units would simply be a nice QoL addition. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
> T5: holds 150 items.

what

aren't they supposed to be logistic drones

why not just use a mega and logic it to carry containers

if they're logistic drones they should carry more

**Comment by Violet-Scarelli** [comment]
> > T5: holds 150 items.
> 
> what
> 
> aren't they supposed to be logistic drones
> 
> why not just use a mega and logic it to carry containers
> 
> if they're logistic drones they should carry more

Thanks for pointing that out-

**Comment by sample-text-here** [comment]
Ok, this is a lot better. Although...

Logistic T3: holds 120 items. Mono T3: can carry a container (300 items) + carrying cap

Logistic T4: holds 240 items. Mono T4: can carry a vault (1000 items) + carrying cap

Logistic T5: holds 480 items. Mono T5: can carry a vault + container (1300 items) + carrying cap

Not even including the carrying cap, and you can tell that the new drones will never be used. If these are added, they should have a *lot* more capacity. 1.5k items would be balanced for t5 but... *1.5k items in one drone?*

Alternatively, they could also be carrier drones. The t3 could be like the mega but trades weapons for speed
