### ISSUE TITLE
Levels of Enemy Build AI

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry-Suggestions#966]
**In editor, there should be like a small selection for enemy AI levels. Easy, Normal and Hard. They all might be same but Hard being faster and Easy being slower.**

**It will sertainly give map maker more control and it will solve the problem that enemy AI builds really slow.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
The enemy has no function to build it's own base.

**Comment by DeltaNedas** [comment]
it does
easy = 1 poly
medium = 3 poly
hard = 50000 poly

**Comment by RebornTrack970** [comment]
> The enemy has no function to build it's own base in the first place.

There is an option called AI Building in editor.

**Comment by DayTimer** [comment]
There should be an "AI building speed" field
