### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#968]
**Describe what you would like changed, and why.**
The Mindustry Wiki

**Describe the changes you want to propose. Include possible alternatives.**
Add all new items added to 6.0 beta to the Mindustry Wiki. If that is done, people upgrading to beta can check out the new features

Just in case **itcannotbe** decides to check this suggestion for issues
- [X] I haven't checked existing suggestions on whether this issue was made before
- [X] I am incapable of checking the Trello board because I'm lazy
- [X] I didn't check the wiki for this suggestion.

**Comment by TheSlaylord** [comment]
> * [x]  I haven't checked existing suggestions on whether this issue was made before
> * [x]  I am incapable of checking the Trello board because I'm lazy
> * [x]  I didn't check the wiki for this suggestion.

h

**Comment by QmelZ** [comment]
> * [x]  I haven't checked existing suggestions on whether this issue was made before
> * [x]  I am incapable of checking the Trello board because I'm lazy
> * [x]  I didn't check the wiki for this suggestion.

might as well close the suggestion and add the items yourself, contributing to the wiki isn't a bad thing.

**Comment by Bohaska** [comment]
> > * [x]   I haven't checked existing suggestions on whether this issue was made before
> > * [x]   I am incapable of checking the Trello board because I'm lazy
> > * [x]   I didn't check the wiki for this suggestion.
> 
> might as well close the suggestion and add the new stuff yourself, contributing to the wiki isn't a bad thing.

1. I wouldn't be asking this question if I knew everything new added in v 6.0. I haven't even tested the functions of payoff conveyors and routers, which have no description attached to them in-game.
2. Blank
3. Wasted digital space.

**Comment by sample-text-here** [comment]
https://mindustrygame.github.io/wiki-testing/
