### ISSUE TITLE
Ban system improperly used by griefers in multiplayer

### ISSUE THREAD

**Issue by Endersult** [Anuken/Mindustry-Suggestions#97]
**Describe what you would like changed, and why.**
The Ban system in multiplayer should be tweaked a little bit, because of a recent event that happened in a multiplayer server: A griefer starts to destroy the base while vote-kicking an innocent player to prevent anyone to ban the griefer. So my suggestion is that the same person should not be vote-kicked over and over again by the same player. Example: I was being vote-kicked for no reason, when the vote ends (not banned), I should not be able to be vote-kicked by the same player and other people (and me) can vote-kick the person trying to vote-kick me. I'm not sure how to explain this but I hope you understand what i mean, and i have not consider the pros and cons yet because of how complicated it is to explain this. Once again, I hope you understand. Thanks.

**Comment by dtmm122** [comment]
Where you in tower defense and a griefer was predending to be me (dtmm122)

**Comment by dtmm122** [comment]
Just currious

**Comment by khaotik** [comment]
If there's no working permission system (i.e you are only allowed to build on certain part of map), I dunno how to solve the griefing problem.

**Comment by itcannotbe** [comment]
Griefers exist because they can. They see satisfaction in others dissatisfaction. The most effective way to stop them is making them believe that they are really ruining the experience from others but really aren't.

**Comment by DeltaNedas** [comment]
admins can always ban, temporary votekicks can be abused
i instead suggest removing cooldown on votekicking for each player, so someone cant spam /votekick to stall it forever

**Comment by berg44** [comment]
The other awful situation is where the griefer is destroying the base while the vote is happening and takes 30s. They should not be able to build while being voted on

**Comment by itcannotbe** [comment]
Ah yes. What that made it worse when the griefer actually places a vote kick on you first. Pointless.
