### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by westernat** [Anuken/Mindustry-Suggestions#971]
Can bank and cell add viewing or editing functions?I think their too troublesome.I dont know whats in them.

**Comment by scarf-generic** [comment]
Goodbye template

**Comment by DeltaNedas** [comment]
1. template
2. to look at cell contents install deltanedas/ldb

**Comment by Catchears** [comment]
Cells exist for processors to either store information or communicate with each other, not to show the player what the processor is doing. If you want to be able to read cells and banks, go install the mod named above or just make a processor print the contents of each cell location to a message.
