### ISSUE TITLE
Space tile Additions

### ISSUE THREAD

**Issue by OnyxDog07** [Anuken/Mindustry-Suggestions#972]
**Describe what you would like changed, and why.**
Allow walker units to go over short gaps of the Space tile, it looks like they can but they actually cant.

**Describe the changes you want to propose. Include possible alternatives.**
Walkers can go across 3 or 4 space gaps of space to another area of land. An Alternative is making a space 'Platform' that costs things like Metaglass, Plastanium, and Titanium. These platforms would have buildable spots on them as well. They will also be able to be built on deep liquids

(The last part is a bit of a feature addition suggestion, but i thought it fits)

**Comment by 50275** [comment]
There is no point, if you need a bridge why did you make seperate islands on your map

**Comment by OnyxDog07** [comment]
I said the platform as an alternative

The thing is, space maps are practically air only.
walkers looks like they should be able to cross short gaps in space

**Comment by 50275** [comment]
It's the mapper's problem
You could do the same thing with water maps; why don't they add bridges over deep water
