### ISSUE TITLE
Filter by "Any" in `ulocate` aswell as allow to filter for specific block types

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#974]
**Describe the content or mechanics you are proposing.**
allow for a filter for any block, along with the ability to specific a specific block.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
this will improve the usefulness of the ulocate feature and logic unit control in general as right now if you want your units to just target [enemy block] you have to look for a whole bunch of different block types / categories.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by scarf-generic** [comment]
If we make enough of these maybe anuke will add it

**Comment by Legomonster33** [comment]
> If we make enough of these maybe anuke will add it

maybe
