### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry-Suggestions#975]
**Describe the content or mechanics you are proposing.**
Enable team change in sandbox

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
yes

**Comment by scarf-generic** [comment]
this is a yeah

**Comment by rmperkow** [comment]
https://trello.com/c/1v40jFbL/708-sandbox-menu

**Comment by D-player1** [comment]
Ah thank you
