### ISSUE TITLE
Allow non-host to view tech tree

### ISSUE THREAD

**Issue by Ansraer** [Anuken/Mindustry-Suggestions#976]
In MP only the host can see the tech tree. When another player tries to open it all they see is a popup that only the host can access it. Especially in the early game this leads to other players constantly asking "how long until we have x".

It would make things significantly easier for everyone if non host players could see (but not interact) with the host's tech tree. Instead of having to constantly ask the host what is needed they could independently work towards the next unlocks.

**Comment by NightOmega** [comment]
YOU ARE RIGHT!!!!
