### ISSUE TITLE
why a endgame enemy on threat level two?

### ISSUE THREAD

**Issue by shadow8749** [Anuken/Mindustry-Suggestions#977]
i was thinking it would nice to get titanium then i see guardian approaching i think it could be a enemy i could deal with but take a good hit and then im slapped with a top tier crawler mech (forgot its name toxopod i think) when all i had is hails scorch's and duos and a few salvos it seems a little unbalanced to me i do understand this would take a small time hopefully to fix but you can focus on other things (edit) i now know there could be a base or rather its because the wave system sends in "guardian" after a while so i went to other sectors and got what what i needed eventually and i went back to that sector i still lost but i just went off and continued but in case some people who aren't using the beta i was in the beta

**Comment by D-player1** [comment]
Capture all the maps in the tech tree before going to numeric sectors

**Comment by l-Luna** [comment]
Chaos Arrays don't exist anymore. the top tier purple ground unit is the Toxopid, which has two Fuse-like attacks + a purple ball that explodes into more purple balls. which sector is this?

**Comment by Colonizor48** [comment]
There was an enemy base right next to frozen forest for me. So i have to deal with a revenant while only having scatters as my strongest anti air turret.

**Comment by l-Luna** [comment]
numeric sectors are balanced to be more difficult than preset sectors, about as hard as Overgrowth's waves. air units in particular are especially difficult.

**Comment by shadow8749** [comment]
> Capture all the maps in the tech tree before going to numeric sectors



> Chaos Arrays don't exist anymore. the top tier purple ground unit is the Toxopid, which has two Fuse-like attacks + a purple ball that explodes into more purple balls. which sector is this?

i renamed the sector to the frozen forest but i think something around 170? i know it was near ground zero

**Comment by shadow8749** [comment]
> shadow8749 these top tier crawler mechs are most likely chaos arrays, if they don't explode and shoot giant Hail-like bullets.

true they were removed in the beta thats what version i was using

**Comment by shadow8749** [comment]
and apologizes for not responding i hardly check my gmail

**Comment by shadow8749** [comment]
> Capture all the maps in the tech tree before going to numeric sectors

in hindsight i should've done this so thanks for the advice
