### ISSUE TITLE
Make Illuminators more important + maybe a buffed version

### ISSUE THREAD

**Issue by andr658** [Anuken/Mindustry-Suggestions#978]
**Describe what you would like changed, and why.**
The current illuminator is meant to provide light, but it's light is almost entirely overshadowed by the light the power node provides, which doesn't need power and is cheaper. Putting illuminators everywhere may get annoying, so a larger expensive version could be added as well. 
**Describe the changes you want to propose. Include possible alternatives.**
Make power nodes provide little to no light on their own, maybe only making the lines between nodes be visible in the dark. Or maybe make Illuminators brighter and overpower power-node light as to provide some purpose for using them in campaign. This would allow for a more customizable atmospheric environment too.

**Comment by D-player1** [comment]
I don't think illuminator is overshadowed by power node
![Uploading Screenshot_2020-10-28-01-07-32-82.png…]()

**Comment by Legomonster33** [comment]
You can overdrive them for a large increase in brightness and range but they are mostly cosmetic as maps dont go dark enough you ***need*** them

**Comment by XxsuperdeadlysniperxX** [comment]
@Legomonster33 illuminators help even though they are basically useless however the dark can be annoying for some people or even make it nearly impossible to see cuz of their brightness boi setting

**Comment by XxsuperdeadlysniperxX** [comment]
4 moths later and this is still open
