### ISSUE TITLE
Add a turret that has a short ranged AoE attack that damages and slows enemies by using cyrofluid

### ISSUE THREAD

**Issue by Rorr4** [Anuken/Mindustry-Suggestions#979]
**Describe the content or mechanics you are proposing.**
The turret I am suggesting is a short ranged land and air unit targeting turret that has a limited range (slightly less than duo) that is called the S.L.O.D (Slushee Launcher Of Death), that when fed Cryofluid, will release a cloud that spans 90 degrees of ice particles that multiply an affected unit's speed by 0.75 and deal small amounts of damage

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
As I know of, there are very few AoE turrets in the game, let alone turrets that can apply debuffs. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
1. factorio bruh
2. blue scorch why would anyone use it, it would get destroyed instantly due to no range

**Comment by the-kido** [comment]
Doesn't seem too useful not even early game (although I don't think you would be using cryo-fluid in the early-game but whatever)

**Comment by 50275** [comment]
This would be useful... never. I'll get a tsunami and a scorch - the scorch has pierce now.

**Comment by Colonizor48** [comment]
Just use tsunami with cryofluid
