### ISSUE TITLE
Make higher tier enemies receive no damage from lower damage turrets.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#98]
**Describe what you would like changed, and why.**
This is to make using single damage turrets more sense.

**Describe the changes you want to propose. Include possible alternatives.**
This entails changing turret damage values to segregate turrets that are good vs swarms and not.

Basically anything that are good vs swarms that are bullet based are considered small arms.

Energy Based Turrets are not included.

**Comment by abowen** [comment]
I like it. Make the weak weapons redundant against bosses.

It's a little disappointing you can take down a Chaos Array with the most basic turret by circling the enemy...

**Comment by MEEPofFaith** [comment]
I mean, you can kill an Erad by flying around it and placing shock mines under it.

**Comment by abowen** [comment]
Yes, and in a way, it'd be nice if some earlier maps taught you skills like that.
e.g. Defend against waves of enemies with zero turrets or units :)

Teach to use different ships + walls + mines to defend.

**Comment by Anuken** [comment]
This was partially implemented with an armor system. Higher tier units get less % damage from weak turrets.
