### ISSUE TITLE
Much needed quad balancing

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#980]
**Describe what you would like changed, and why.**
Quad is broken right now. Its probably the best t4 unit, (sei is a joke, everything else is avarage) and it needs some stat changes. Make it less of a "fly over defenses and two shot core" unit and more of a support unit. Make the bomb it drops deal about half as much damage, but heal buildings and units that are within range and on the same team. This makes quad more of a support style unit, similar to oct, but less tanky with an actual way of attacking.

**Describe the changes you want to propose. Include possible alternatives.**
As above, cut quad bomb damage in half and make it heal friendly buildings and units. This makes it fit with the support style that mono branch has, while not making it useless like sei. I guess an alternative is to just nerf the damage, but i think that the block/unit heal mechanic fits well with the other units in its branch.

**Comment by AgentAvis** [comment]
Sounds like someone was playing pvp

**Comment by scarf-generic** [comment]
> Sounds like someone was playing pvp

No, my build is never up to date. While playing singleplayer attack maps (i dont have internet all the time) i realized how easy it is to win with quad. Try it for yourself, and keep in mind that this is a *support* unit branch. Given that it outdamages all the other t4s by a large amount id say it needs a more support based rework.

**Comment by scarf-generic** [comment]
Oh yeah forgot to include this, the support bomb idea fits super well with the current other units, its a transition from the healing mega/poly to the tank as hell oct. Personally i think it fits much better with the other units than what we have now

**Comment by D-player1** [comment]
~~Tbh all the support units should deal reduced damage to enemies and more healing to ally~~

**Comment by scarf-generic** [comment]
> ~Tbh all the support units should deal reduced damage to enemies and more healing to ally~

Thats the thing though, it hardly heals at all. Its not a support unit in the slightest, even though everything else in its unit branch is.

**Comment by D-player1** [comment]
Quad can heal blocks btw

**Comment by scarf-generic** [comment]
> Quad can heal blocks btw

Yeah, but it doesnt heal units also iirc

**Comment by 50275** [comment]
Cutting it's damage still isn't enough, because it has 9000 HP and can walk through 2 lines of metaglass scatters and live, moving through all of your factories. Now, any map that requires you to have any air defence of any reasonable size will get you killed easily.

**Comment by potatoisagender** [comment]
*cryo overdrive spectre wall*

**Comment by 50275** [comment]
Not practical, obviously
