### ISSUE TITLE
More database info

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry-Suggestions#981]
**Describe the content or mechanics you are proposing.**
More database info like: Unit damage(in general and of projectile[dps]) and unit attack types. Those weren,t menitoned in mindustry trello.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Would fill empty data about ounits. If v6 i mainly about units, why dont make more info about them

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by EnganK** [comment]
- [X]  Я быстро поискал в списке предложений, чтобы убедиться, что это еще не было предложено.

#863
