### ISSUE TITLE
Minor Tweak To Unit Logic

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#982]
**Describe the content or mechanics you are proposing.**
When a unit is constructed, it would be assigned a unique _bindcode_: that is, a code similar to a flag that can be used in place of the `@<unit>` code. This would supplant but not replace flags by providing a secondary layer to identify a unit that is unique to each unit. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I can easily imagine a scenario for a processor that binds a unit while a switch is on, stores the bindcode of the bound unit in a memory cell, then on subsequent passes, only attempts to bind units whose bindcodes have been stored in the memory cell, thus preventing any conflicting bind attempts by multiple processors. 
A simpler version would be making a guard unit that is bound to a processor by its bindcode instead of its type, thus allowing all other units of that type to avoid 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet. 
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Nester23** [comment]
> When a unit is constructed, it would be assigned a unique _bindcode_: that is, a code similar to a flag that can be used in place of the `@<unit>` code. This would supplant but not replace flags by providing a secondary layer to identify a unit that is unique to each unit.

Did you know that you can set @unit to a variable, the same way radar does?
It's pretty much what you have described, except that you can't store that in a memory cell.
