### ISSUE TITLE
Wait instruction for processors

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry-Suggestions#983]
**Describe the content or mechanics you are proposing.**

A wait instruction for processors

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would allow you to wait x seconds, or wait until the next multiple of x seconds. This would provide an easier way to wait certain amounts of time than using the @time and @ipt variables.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by T1murik** [comment]
try this:
bXNjaAF4nGNgYmBkYmDJS8xNZeAwNDI2MTUzt2DgTkktTi7KLCjJzM9jYGBi4M/NTC7K1y0oyk9OLS7OL2JgKy7PLEnOYABJggAfELdWzElOSUjYETknapHAm1dv3j8XWpNwYmr8ggnRsxZPmBkeExQyK2bSzPnhPNNNjR94nTuvrXnqfKDHWW+fU56+gRp653U8zxmEGDQ46E1InOkgleGT5MU1YSanifFqk+0OB10U1bfusFBRNjy/VUClL4XRL5iXc1ZW4/GQBc8lJG8sTGOcycOgG+O5l5mRgZGBgYuBEQBg3UoO
(or in mlog):
set SECONDS 1
op mul instructions SECONDS 60
control enabled switch1 0 0 0 0
set i 0
op add i i 1
jump 4 lessThanEq i instructions
control enabled switch1 1 0 0 0
set i 0
op add i i 1
jump 8 lessThanEq i instructions
