### ISSUE TITLE
Make crawlers require a unique click rather than a hold to explode

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry-Suggestions#984]
**Describe what you would like changed, and why.**

Normally a crawler requires you to only hold the fire button to explode. This combined with the fact that you automatically control the nearest crawler after you die means that if you accidentally hold the button you'll destroy all your crawlers

**Describe the changes you want to propose. Include possible alternatives.**

Make it so it needs the beginning of a click rather than a hold, or make some kind of reload delay. This should probably be a bug report TBH.

**Comment by 50275** [comment]
I don't think this is a good idea, because let's say I tried to access the stats of a turret and accidentally clicked outside the menu on the bottom right corner

**Comment by Esnardo** [comment]
> I don't think this is a good idea, because let's say I tried to access the stats of a turret and accidentally clicked outside the menu on the bottom right corner

That already makes you explode. The only thing that changes is that you don't take every crawler on the map with you
