### ISSUE TITLE
arc surge wall

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry-Suggestions#985]
**Describe what you would like changed, and why.**

make it so that when an arc (or any electric attack for that matter) hits a wall it arcs more (bounces more so it hits more targets) and gains some damage. the reason why i think this makes sense is because surge walls are electric and as such should charge a electric arcs that pass through them

**Describe the changes you want to propose. Include possible alternatives.**

+ arcs deal more damage and gain more power from surge walls

alternatives:
add diminishing returns so even thought the entire defense is surge it will only deal a small (ish) amount of damage
make it so it can only arc so often so arc spam wont surge the walls too much

**Comment by 50275** [comment]
So... buff surge wall arc attack?
