### ISSUE TITLE
Some way to incresse unit cap

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry-Suggestions#986]
**Describe the content or mechanics you are proposing.**
Some way to increse unit cap besides upgrading core.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make zerg rushing a viable strat. And allow you to choose quality or quantity with units. And this would also make pvp more interasting. Because were not capped at 20 units per type anymore. Though there should probably be a hard limit somewhere so people dont lag servers this way.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by D-player1** [comment]
If you can't rush with 20 units just make a higher tier one

**Comment by itcannotbe** [comment]
Alternative mechanic #988

**Comment by itcannotbe** [comment]
> If you can't rush with 20 units just make a higher tier one

Now that undermines the point of rushing.

**Comment by sample-text-here** [comment]
Maybe make specific blocks increase unit cap. Each command center could add +2 to the unit cap. Also a new, expensive block that adds +5 to 8 to the max cap

**Comment by 50275** [comment]
oh god no
that's basically a way to force players to use more logic otherwise get less units

**Comment by sample-text-here** [comment]
> that's basically a way to force players to use more logic otherwise get less units

@50275 who said anything about logic?

**Comment by Andraez** [comment]
i dont know how i did it, but i remember making a custom game, and the capacity was 17,000 units, i'm not even kidding.
i really am trying to recreate this, but im having a hard time finding out what effected the capacity last time.

**Comment by RogueRedHawk** [comment]
@Andraez Adding multiple cores can increase the unit cap.

**Comment by Andraez** [comment]
> @Andraez Adding multiple cores can increase the unit cap.

I just discovered this 30 seconds ago, lol, one of my maps has cores surrounding the perimeter, but you cannot connect anything to them as they are blocked off. I only did this to add a really high item capacity. There is only one actual core you can get to.
I tried it with this map, and I added a row of more cores. The cap is now 23,000. Time to crash the game.

**Comment by DreoDemo** [comment]
Umm i have an idea that you can add to the game that increases unit cap the new building is The HANGAR in Mindustry v7 increases unit cap by 2 thats all

**Comment by Kyllingene** [comment]
Not only is that very nearly against principles suggested in the README.md, it is also useless. 2 units? What can you possibly do with 2 units (excluding the really good T4-T5s)?

**Comment by itcannotbe** [comment]
> Not only is that very nearly against principles suggested in the README.md, it is also useless. 2 units? What can you possibly do with 2 units (excluding the really good T4-T5s)?

They mean x additional unit cap above the base cap.
