### ISSUE TITLE
Cameras! 

### ISSUE THREAD

**Issue by TanekoKyuu** [Anuken/Mindustry-Suggestions#987]
Since we have Displays now, why don't we add some kind of "security camera" block or logic command? 

-You can chill near the core, while seeing how your defenses are doing. 

-You asked your friend to fix the silicon clogging problem, and you can see them at the Display struggling while laughing the sadist you are. 

-You can secretly add a camera to the enemy base (idk how they are dumb enough not to see it tho) so you can see what heinous things they're up to. 

I don't have any sort of coding experience, so I don't know if this impossible or hard to implement tho. 

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Gdeft** [comment]
You can just pan your camera instead.

**Comment by TanekoKyuu** [comment]
> You can just pan/move your camera instead. Three of the situations you mentioned can be done by doing that.

I primarily play on mobile and I think lots of others too, having to swipe all the time is a pain, also whenever you want to go see something, your ship goes there too.

Also also, with cameras, you can see all of these at the same time.

**Comment by sample-text-here** [comment]
how exactly would they work? what would the logic block look like? i think that if it is added, the syntax should be `draw camera camera1` or something like that unless you have a better idea

**Comment by TanekoKyuu** [comment]
> how exactly would they work? what would the logic block look like? i think that if it is added, the syntax should be `draw camera camera1` or something like that unless you have a better idea

I'm thinking something like the Force Projector, but it's a square rather than a hexagon.

**Comment by anar4732** [comment]
zoom on minimap (not fullscreen map) can do this job
