### ISSUE TITLE
Change unit cap from per unit to a a global cap with higher tier units contributing more towards the cap.

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#988]
**Describe what you would like changed, and why.**
Currently the unit system emphasizes only more expensive units and therefore limiting strategies to who has the better units

Chnaging this to a higher global cap would force a different game mechanic where players have control on which units they want more and thus brings back the possibility of swarm attacks with lower tier units and/or multiple mining units deployed 

**Describe the changes you want to propose. Include possible alternatives.**

Change unit cap from per unit to a a global cap with higher tier units contributing more towards the cap.

**Comment by 50275** [comment]
isn't the whole point of the reconstructors to get better units, which the unit limit encourages?

**Comment by itcannotbe** [comment]
Nope. The whole point of reconstructor is to simply unit creation by not having dedicated factory for each unit/upgrade/type

**Comment by 50275** [comment]
a cap like this feels like an excuse to stop players from making too many powerful units like T5s

**Comment by Colonizor48** [comment]
Just add a way to incresse unit cap.

**Comment by Colonizor48** [comment]
Oh my goodness no no no no no no. Not without some way to incresse unit cap anyway.

**Comment by itcannotbe** [comment]
> Oh my goodness no no no no no no. Not without some way to incresse unit cap anyway.

Why? The suggestion actually entails the global cap to actually large enough, while retaining the correlation of more/larger core/s = more capacity.

**Comment by Colonizor48** [comment]
Because i dont want to be limited in the number of t5 units i can spam at once.

**Comment by itcannotbe** [comment]
Well, you don't have to, since the ability to have more than 20 lower tier units can force matches to be quick.

**Comment by 50275** [comment]
Sounds stupid. A few arcs and a Lancer will shred that.

**Comment by itcannotbe** [comment]
I said lower tier not T1 units.

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~
