### ISSUE TITLE
Make logic displays appear in the minimap

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#989]
**Describe the content or mechanics you are proposing.**

![image](https://user-images.githubusercontent.com/56274831/97389384-6810ec80-1897-11eb-9615-072656a51db5.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It would be easier to label places and could show alerts if something's wrong. Large logic displays could render numbers to show items/sec or power from a distance. People can already use sorters to display stuff, so why not logic displays?

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Basically sorter art but worse?

**Comment by sample-text-here** [comment]
1. No, the logic display would definitely be more hi def. 
2. Of course it could be abused to make art, but I think the abuse risk could be fine considering that you can’t really grief it. (Same as sorters)

**Comment by itcannotbe** [comment]
It kinda ruins the aesthetics of the minimap though.

**Comment by sample-text-here** [comment]
I think it would be very useful, but you’re right. Maybe pixelize it a little? Or add a outline? The idea is that you can use the small displays to label areas of the map or for alerts and use large ones for more detailed info, but displays not used for that purpose could make it a little messy. I still think it’s useful though.
