### ISSUE TITLE
Translatable server messages

### ISSUE THREAD

**Issue by GioIacca9** [Anuken/Mindustry-Suggestions#99]
Make all server messages translatable from the `bundle.properties` file. (Like the ones in the photos).

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

![immagine](https://user-images.githubusercontent.com/39232448/79127174-b3ebc080-7da1-11ea-99e2-9c7ff462b7a2.png)
![immagine](https://user-images.githubusercontent.com/39232448/79127241-d54cac80-7da1-11ea-99d0-f4eb073ad1c4.png)

**Comment by Quezler** [comment]
the server does [not have access](https://github.com/Anuken/Mindustry/blob/master/server/build.gradle#L48) to any of the lines in `bundle.properties` 😗
