### ISSUE TITLE
Oil/Slag as lubricant 

### ISSUE THREAD

**Issue by SarisWinterwisp** [Anuken/Mindustry-Suggestions#991]
**Describe the content or mechanics you are proposing.**

Instead of just cooling down weapons and drills with water and cryofluid, you could lubricate them to fire efficiently or drill even faster

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Within the campaign and certain maps there may be very little of a resource, so being able to draw more resources from it with the assistance of oil would be beneficial to such maps. Additionally it could add another layer of complexity and effectiveness to high end defenses where you want everything to be lubricated, cooled, and overdriven to help take on the newer, much harder enemies. As well it gives another purpose to oil/slag than just being fuel for plastanium/a source for seperators.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
For a fact anuke made stuff spontaneously combust in some builds ago when using oil to "lubricate" turrets

But he has since removed it because of too many "bug" reports

**Comment by DeltaNedas** [comment]
how on serpulo is molten scrap a lubricant

**Comment by potatoisagender** [comment]
that moment when really hot scrap metal (probably with chucks of metal in it) a lubricant, and if it isn't, it definitely isn't a coolant
