### ISSUE TITLE
Parallax balance

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#992]
**Describe what you would like changed, and why.**
Make Parallax make no damage at all but instead give it larger range and pull strength. Perhaps make it 3 by 3.

**Describe the changes you want to propose. Include possible alternatives.** Many units can be outside of turrets' range. This will make Parallax more important in defense as it can help out other turrets to target enemies. 
Units should have an advantage in attacking and the ability to "safe" attack. But also there should be a way to counter such attacks in some way (not using logic).

**Comment by Slava0135** [comment]
I am not concerned about buffing it's pull strength. Since more range -> more turrets in range -> better pull strength (on one unit).

**Comment by 50275** [comment]
It already makes them slow enough to shoot easily
If you're planning on using fuses against long range units good luck

**Comment by l-Luna** [comment]
the pull strength really needs a buff, given that two parallaxes can't pull a horizon and parallaxes can only target one enemy each.
