### ISSUE TITLE
Unit banned

### ISSUE THREAD

**Issue by UnionofSovietSocialistRepublics** [Anuken/Mindustry-Suggestions#994]
**Allow banned unit type in Editor and Customize Rules **

**It will make the game more challenging.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
#445
