### ISSUE TITLE
allow stealing items from enemy cores

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#996]
**Describe what you would like changed, and why.**

currently you cannot steal items from an enemy core gotten from ulocate.
this would be nice and cheeky but should only apply to cores, nothing else as that would be infuriating.
it would be harmless at best as ideally you would have air defences preventing units from sweeping in and stealing your silicon

**Describe the changes you want to propose. Include possible alternatives.**

allow units to steal items from enemy cores

**Comment by Ilya246** [comment]
oct stealing 210 surge alloy

**Comment by DayTimer** [comment]
Imagine having no resources because your enemies stole it.

**Comment by D-player1** [comment]
This feels really illegal

**Comment by PlanetOrca** [comment]
i think IF this was added, it should be its own unit, and doesn't have any attack itself, and there should be a land variant which can carry a large amount of items, and an air unit which is fast and can fly over walls, but is weak and can only carry a few items

**Comment by 50275** [comment]
There's no point of this
If you can get close enough to steal an item, why can't you just shoot them to death

**Comment by PlanetOrca** [comment]
> There's no point of this
> If you can get close enough to steal an item, why can't you just shoot them to death

You’re trying to compare destroying someone’s business with stealing the profits of said business. Maybe you want to play late game and that’ll help support you. Maybe you’re playing a specific custom game mode where you have to steal instead of destroy. It’s not a fair comparison to make

**Comment by 50275** [comment]
You see, the thing is that units are slow and have small inventories. Unless you dedicate a group of at least ~50 air units it won't be fast enough to be practical, and someone WILL shoot the units while they're on their way. It's simply a waste.

**Comment by scarf-generic** [comment]
> You see, the thing is that units are slow and have small inventories. Unless you dedicate a group of at least ~50 air units it won't be fast enough to be practical, and someone WILL shoot the units while they're on their way. It's simply a waste.

This is the result of a joke in the #logic channel on the discord. Its not supposed to be practical, its supposed to be a dumb thing that you are able to do but doesnt really benefit you much (examples are blast in steam generators and phase in rtgs). Also in multi team pvp it might be worth it to steal some resources before you break the core, as the game does not end when that core is broken.
