### ISSUE TITLE
Conveyer-Conduit Junction

### ISSUE THREAD

**Issue by PlanetOrca** [Anuken/Mindustry-Suggestions#997]
**Describe the content or mechanics you are proposing.**
A junction which has conveyer input and output on 2 sides, and conduit input and output on the other 2.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will allow easier placement of infrastructure, take less time and space to place, and generally improve quality of life.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by ritzip** [comment]
did you read README.md?

**Comment by PlanetOrca** [comment]
I'm sorry. I checked everything I told it to check, and I used a direct link to suggest a new issue.
