### ISSUE TITLE
Configurable Unit Cap

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry-Suggestions#998]
**Describe the content or mechanics you are proposing.**
Make it such that the unit cap for each type of unit can be configured per-map.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would prevent people from just making t5 units, because if the unit cap for each t5 could be set low and the cap for other, smaller units was higher, then you could promote supporting a large unit instead of spamming it.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
Alternative mechanic #988
