### ISSUE TITLE
Make the 5 sided sectors special

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry-Suggestions#999]
**Describe the content or mechanics you are proposing.**

Make the sectors with 5 sides be special in some way, beyond just having 5 sides. Maybe they're heavily fortified enemy bases, maybe a coordinate error mans you can't launch resources into them, I just feel like they should be different in some way.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It will make the game have more variety, and be more interesting. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
My suggestion is that 5 sided sectors should have an elevated difficulty level. They have thorium, but resources can only be sent from neighboring sectors.

**Comment by DeltaNedas** [comment]
i agree, pentagons should be heavily fortified control centres
